== The Preface

After a labor of more than twenty-five years,
this history at last appears in public view;
to the compiling of which I was induced from the consideration
that the rise and increase of that religious society,
(which in this work I have given a detailed account of)
is indeed so rare and wonderful a thing,
that I think few will be met with in modern histories which may be compared therewith.
For the Quakers, so called, have become a great people,
under such heavy oppression as is herein mentioned,
and this came about not by any human power, or by making resistance,
but merely by their harmless deportment,
and the exercising of patience--for bearing arms and resisting
the wicked by fighting they have always counted unlawful,
and contrary to the doctrine of our Savior.
Thus they who had no king, prince, nor potentate to protect them,
and who in the beginning had not among themselves any man of renown or literature,
but relying on their integrity, and trusting to God alone,
have at length triumphed over the malice of their opposers by suffering
(to such a degree that it was at the expense of the lives of many
of them) under violent oppression from high and low,
and the opposition of learned and unlearned.

All this after much searching, being found out by assiduous diligence,
appeared so wonderful to me, that I resolved to give a relation thereof,
notwithstanding the great labor I soon perceived this work required.
To this may be added, that when I considered that several authors,
both Germans and others,
had published books and accounts of this people stuffed with gross untruths,
I was the more spurred on thereby to set down in due order (for my countrymen`'s^
footnote:[William Sewel was a native of Holland, and his native tongue was Dutch.]
sake) what I knew of the matter;
for it seems indeed to be of little advantage that when anything is well known to us,
we keep that knowledge only to ourselves, without imparting it to others.

Now however difficult I found it, yet having made a beginning, I resolved to go on;
and so I did, though often stopped by several occurrences, and also other work.
For during this labor I have not only translated several bulky books into Dutch,
besides Kennet`'s Antiquities of Rome, but also composed several treatises of importance,
and among these my great dictionary, English and Low Dutch.
And notwithstanding all these impediments,
I continually resumed this work by intervals so often,
that I have written it almost three times over to make it complete;
for doubting of some things, and finding others defective,
it made me write to England for better information.
And having received it at length, after much pains and long writing,
I was several times obliged to lay aside part of
my former description and make a new one;
which happened so often, that had I not been supported by an unwearied application,
the difficulty of the labor (which was much greater in Holland,
than if I had composed the work in England) would have made me give it up.
But I went on, and so finished this history in that form as it now appears.

And I am not without thoughts that I was prepared
to be instrumental for such a work as this;
for I have made use of several remarkable things which I had noted
down before ever I thought of composing such a history;
and even in my young years, when I was in England,
I copied out from manuscripts several pieces and
letters which are inserted in this history,
and which may hardly be found elsewhere.

I received narratives of many remarkable occurrences
given forth in print from my acquaintances in England,
and many authentic pieces in manuscript.
From there, and from my own collection of matters known to me,
I have compiled the greatest part of this history.
But as to the life and transactions of George Fox, who is largely treated in this work,
I took them chiefly from his journal; and the greatest part of other occurrences,
or the lives and transactions of others, I have taken from the works of deceased authors,
and out of abundance of small books published in print not long after the things happened,
and not contradicted by anything I could find.

Thus I have endeavored to assert nothing but what I had good authority for;
which in regard to some circumstances,
would have been yet far more difficult after the expiration of some years.
For now time gave opportunity to be informed of many things
which some ancient people had yet remembrance of,
and which after their decease perhaps would have been buried in oblivion.

I cannot well omit here publicly to acknowledge the signal kindness and
diligence of my well-beloved and much esteemed friend Theodore Eccleston,
of London, who has furnished me with abundance of materials,
which were not only very useful,
but also absolutely necessary for the compiling of this work.
From him I received intelligence on that account,
and have exchanged a multitude of letters.
And thus by a long continued correspondence I came to be
acquainted with many things and circumstances which,
after some years, might have been more difficult to obtain.

Add to this, that I have described several things which are well known to me,
which few besides myself within these thirty or forty years had better knowledge of.
I have also mentioned several remarkable cases,
which I noted down from the mouths of credible persons who have been dead many years,
and thought not that at any time I should have published them in print.
In the meantime I took account of what seemed worthy to be left upon record,
and collected a great quantity of books,
wherein many occurrences mentioned in this history were related.
I have made use of such relations and accounts,
without taking from them all that was truly remarkable;
for it has not been for lack of material that this history is not a larger work,
since I could have made it three times as big, if I had been of a mind to do so.
But as I was unwilling to extend my work any further than
my strength and health in all probability should permit,
so I also did not desire to overload my reader with many things of a similar nature;
but have endeavored, by variety of material, to quicken his appetite;
and therefore have intermixed the serious part sometimes with a pleasant anecdote.

Yet I have not thought myself bound to take notice of every
odd case that may have happened among the Quakers,
so called.
For there have been found among them some who acted some particular
things that were not approved of by those of that society.
And if any one, swayed by human passion,
commits any excess which is disapproved of by his fellow members of the church,
such an act may not be duly imputed to the people he makes profession with.
Among such particulars may be reckoned the case of one Hester Biddle,
which Croese makes mention of near the end of his history.
For though it was told him from the relation she gave of it at Amsterdam,
not with any intention that he should publish it,
yet this was a particular case which she herself must be responsible for;
since experience has taught that imagination sometimes works so powerfully on the mind,
that one thinks himself obliged to do a thing which is better left undone.

Even so, it is true that men fearing God, may mistake,
and through ignorance do something which others might rightly judge to be not commendable.
Also it may happen that some, from a godly fear, have omitted what others, no less pious,
would not have scrupled.
And though some among the Quakers, in the beginning of their rise,
for fear of transgressing Christ`'s command, "`Do not be called Rabbi,
for one is your Master, even Christ,`" speaking to persons in authority,
called them by the name of Friend;
yet others of the same persuasion have not therefore thought themselves
bound to refuse to magistrates their distinguishing titles of magistracy.
And if any, for some special reason,
may not have given a full or direct answer to a query,
yet others of the same society have not looked upon this as a pattern to imitate.
For the most eminent valiants among this people in the beginning,
were not men of note or learning, though of great courage;
insomuch that their immoveable steadfastness sometimes so exasperated their enemies,
that their fear of doing or omitting anything which they judged would displease God,
often has been branded with the odious name of stubbornness and stiff-neckedness;
but they have borne this patiently,
believing that it was their duty to persevere immovably in minding their Christian profession,
and in frequenting their religious assemblies.

It is true, there have been some among the Quakers,
who were exceedingly bold in representing to their enemies their evil behavior and deportment;
but this has been a peculiar characteristic of many pious men,
of whom examples are extant in the book of martyrs, i. e.
that some of them in very plain terms told their persecutors of their wickedness.

And it cannot be denied that there have been at times
among this society some people of an odd behavior,
who in process of time embraced strange opinions and perverse notions;
but that is no new thing, since this has happened also among those of other persuasions,
though none of these would allow that this was the consequence or effect of their doctrine.
We find in Sacred Writ, that even in the primitive Christian church there were apostates;
either such as maintained strange doctrine (as the Nicholatians),
or such who finding the straight way too narrow for them, left it, and like Demas,
falling in love again with the world, entered into the broad way.
And therefore it can now, no more than then, be argued from there,
that the exorbitances to which some launched out,
were the effects of the doctrine they forsook.

Since in this history some predictions are also mentioned,
and some who are biased by prejudice will perhaps look upon them as frivolous,
imagining that the Quakers pretend to have the spirit of prophecy;
I will answer as follows:
That though among thousands of them there may have
been one that prophetically foretold a thing,
which afterwards truly happened;
yet many others of that society did not presume to have
that gift any more than to have the gift of being a preacher,
being not called to that work.
Now though some have maintained the false opinion that to be able to predict future
things was a quality the Quakers attributed to themselves because of their doctrine,
that Christians ought to be led by the Spirit of God;
yet this is a very sinister and preposterous opinion;
for what they say concerning the leading and guiding of the Spirit
of God is agreeable with the doctrine of the apostle,
who says, "`As many as are led by the Spirit of God, they are the sons of God.`"
And this was also the doctrine of the first reformers.
What must we think then of those who will not be led by this Spirit,
but instead call this doctrine by the odious name of "`enthusiasm`"?^
footnote:[At this time,
the word enthusiasm referred to religious fanaticism or emotionalism.]
The same apostle tells us also, "`If anyone does not have the Spirit of Christ,
he is not His.`"
And he says also,
"`The manifestation of the Spirit is given to every man to profit withal.`"
But from here it in no way follows that the spirit of prophecy is given to everyone;
nor that, though it might please God to reveal to one a thing which yet was to come,
such a one therefore is endued with such a prophetical spirit
that he is able at any time to predict future things.

There have been many pious men among other Christian
persuasions who predicted remarkable things,
which afterwards really happened; such as (among many others), James Usher,^
footnote:[Author of Annals of the World, and many other well-known Protestant works.]
archbishop of Armagh, and primate of Ireland,
who foretold the rebellion in Ireland forty years before it came to pass,
along with the civil war and miseries that befell England,
and other things that were fulfilled;
and this leads us not to reject as frivolous his prediction of the dreadful
persecution that would fall upon all the Protestant churches by the Papists.^
footnote:[Throughout this history,
the term Papist is used to refer to those persons whose
loyalties were to the Pope and the Roman Catholic Church.]
For though one of his friends once objected to him,
that since Great Britain and Ireland had already suffered so deeply,
there was reason to hope that the judgments of God might have been past;
yet he replied to it:

Do not fool yourselves with such hopes,
for I tell you that all you have yet seen has been but the beginning of sorrows,
compared to what is still to come upon the Protestant churches of Christ,
who will before long fall under a sharper persecution than ever yet has been upon them.
Therefore, be sure you are not found in the outward court,
but rather a worshipper in the temple before the altar;
for Christ will measure all who profess His name and call themselves His people;
and the outward worshippers He will leave out, to be trodden down by the Gentiles.
The outward court is the formal Christian,
whose religion lies in performing the outside duties of Christianity,
without having an inward life and power of faith and love, uniting them to Christ.
These God will leave to be trodden down and swept away by the Gentiles.
But the worshippers within the temple and before the altar,
are those who indeed worship God in spirit and in truth,
whose souls are made His temples,
and He is honored and adored in the most inward thoughts of their hearts,
and they sacrifice their lusts and vile affections, yes, and their own wills to Him;
and these God will hide in the hollow of His hand and under the shadow of His wings.

If any now-a-days should speak in this way,
it is likely that many who think themselves to be
good Christians would condemn this as mere enthusiasm.
But the said bishop is still in such great repute with the learned,
and has obtained such a high esteem by his writings,
that his words are likely to be of more weight with many than those of other pious men.
And therefore I was willing to quote them, and to revive his memory,
if perhaps this might make some impression upon the minds of any.
For this is a certain truth, that no outward performances will be of avail to any,
who do not worship God in spirit and in truth; for such worshippers God seeks,
according to what our Savior has said.
And besides, "`not everyone that says to Him, Lord, Lord,
shall enter into the kingdom of heaven.`"
No, when many in that day will say to Him, "`Lord, have we not prophesied in your name?`"
He will say to them, "`I never knew you; depart from me you that work iniquity.`"

As the many extraordinary cases related in this history will no
doubt afford pleasant entertainment to curious readers,
so they will also be found instructive.
For we shall not only meet with instances of true piety and love to one`'s neighbor,
and of saints triumphing on their death beds,
and also with remarkable examples of sinners truly penitent at the hour of death;
but we may also find here an abundance of proofs of a peaceable behavior.
For the Quakers, so called, have never plotted against the government,
nor meddled with treasonable practices or rebellions;
and however so much they were oppressed, yet they were always quiet,
and never made any resistance;
but with a harmless patience they have borne their most heavy oppressions and injuries,
and so at length overcame.
For to be subject to magistracy has always been one of their principles;
and they have showed at all times that they were really dutiful subjects,
paying obedience to the higher powers in all they could do with a good conscience.
And when anything was required of them,
which from a reverential respect to God they dared not do or omit,
they have showed their obedience by suffering, without making any resistance,
or joining with others who were inclined thereto.

Many have made it their business to represent the Quakers in odious colors,
and to write great untruths concerning them;
attempting to fasten doctrines upon them which they never approved,
and represent their honest behavior and religious life as Pharisaical righteousness,
even though Christ and His apostles earnestly recommended such a life of godliness.
For what mean these words of our Savior, "`Be perfect,
even as your Father which is in heaven is perfect;`" but that we ought to endeavor,
to the utmost of our power, to lead a virtuous and godly life?
The apostle Paul says, "`Be not conformed to this world,
but be transformed by the renewing of your mind.`"
And the apostle Peter, agreeable to this, says, "`As obedient children,
not fashioning yourselves according to the former lusts in your ignorance;
but as He which has called you is holy,
so be holy in all manner of conduct;`" all which clearly implies,
that a Christian ought to be very strict and careful in his conduct;
and of this judgment were also the first reformers.
But though the Quakers have endeavored to make their
life and conduct align with their Christian profession,
yet this has raised envy, grudge, and malice against them.
And among the clergy there have been such,
who (in order to render them odious) did not hesitate
to represent them as disguised Papists,
notwithstanding these were some of their greatest enemies.

I have related nothing in this work but what I believed to be unquestionably true;
for whatever seemed doubtful to me, I rather chose to pass by,
having never been of so gullible a temper, as to easily take things on trust,
without due examination.
For, indeed,
we often see that high soaring imaginations make
people believe things that are far from being true.
But, on the other hand,
we ought not to reject as untrue everything that appears strange or unusual,
since experience convinces us of the contrary, namely,
that sometimes we have seen a thing which, if we had not beheld with our own eyes,
we could hardly have believed.
Therefore I would not reject as untrue what was extraordinary or unusual,
when it was told me by credible persons, or confirmed by eye-witnesses.
And therefore, though my reader may meet with some very extraordinary occurrences,
yet this is true,
that I have endeavored to the utmost to relate nothing but
what (after a careful inquiry) seemed to me to be true,
or at least very probable.
And yet I have silently passed over some cases which I did not question to be true,
lest any might think me too credulous.

As to the transactions of state affairs,
I have taken them mostly from The History of the Rebellion and the Civil Wars in England,
written by Edward, Earl of Clarendon, and from the Memoirs of Edward Ludlow.
Yet a few things relating to state affairs that have not been mentioned by them,
nor in any other public history that I know of,
I thought worthy to be delivered to posterity by my pen.

As for my style, I know it to be unimpressive.
I do not pretend to elegancy in the English tongue; for, being a foreigner,
and never having been in England but about the space of ten months,
and that near fifty years ago,
it ought not to be expected that I should write English so well as Dutch,
my native language.
If therefore my pen has sometimes been guilty of a Belgicism,^
footnote:[A word, expression,
or phrase that is unique to the languages of the Belgian regions.]
I beg excuse of my reader.

What the envious may judge of this work I little care for,
well knowing that the most eminent authors have been exposed to envy,
and been obnoxious to the censures of pedantic critics.
Whatever any may think, this I am well assured of,
that my chief scope has been by the relation of many unusual occurrences,
not only to please my reader, but also to lead him to virtue.
If I may be so happy as to have contributed thereto,
I shall think my pains well-rewarded; and if not,
I shall have at least this satisfaction, that according to my ability,
I have endeavored to be beneficial to others and
to edify my fellow-mortals in that which is good;
which I cannot but think to be well-pleasing to God.
And if I have performed anything that is good,
the honor and glory thereof belongs to Him, who is the Giver of all good gifts;
and it is from Him alone I have received all my ability to do any good thing.
Thus concluding, I wish the reader discretion, and an impartial judgment.
