== Chapter 1

[.section-date]
1415--1650

That the wonderful work of reformation was small and of very little account in its beginning,
and yet has been advanced with remarkable progress, will,
I believe be denied by none that have with attention and
due consideration read the history of its first rise.
For God, the beginner and author of this glorious work, proceeding by steps and degrees,
used therein such remarkable wisdom and prudence,
that (when every circumstance is duly considered,
instead of censuring any part thereof) we shall be obliged to cry out, "`You, O Lord,
alone know the right times and seasons to open the eyes of the people,
and to make them capable of Your truth!`"

If we look to the first beginnings, to go back no further than John Huss, we shall find,
that though in many things he was considerably enlightened,
yet he continued still in several apparent errors;
for although he had a clear sight of the vain doctrines of purgatory,
praying to and worshipping of images, etc.,
nevertheless it is reported of him that he favored the invocation of saints,
the seven sacraments, auricular confession, and other tenets of the church of Rome;
and yet Christian charity constrains us to believe (though
we find Protestant writers who deny him the name of a martyr),
that by his death, which he suffered in the flames at Constance in Germany,
on the 6th of the month called July, in the year 1415,
he was an acceptable sacrifice unto God.
And the calm and well-composed mind with which he suffered death,
may be understood by this,
that seeing a country-fellow very zealously carrying wood to burn him, he said,
with a smiling countenance, "`O holy simplicity!`"
And after the fire was kindled, he sang with joy in the flames,
his mind being firmly fixed on God.
For he had been faithful according to his knowledge,
and had not hid his talent in the earth, but improved it,
having shown himself a zealous promoter of that small
illumination which God was pleased to grant him.
And this small measure of light was, without question,
great enough in that grievous night of darkness,
when idolatry had so universally blinded mankind, that, morally speaking,
it would have been impossible for them to have understood
the proclamation of an entirely reformed religion.
But it is evident that the most sober and discreet people of that age were capable
of understanding the doctrine and sermons of that honest man.

To give a clearer view into this matter, let it be considered,
that if a man had been kept shut up a long time in a dark prison,
where he could neither behold the light of the sun nor moon,
and should have been suddenly let out at clear noon day,
he would not only be unable to endure the bright day light,
but would also (if he strove to open his eyes by force) be endangered of loosing
his sight and falling into a worse condition than he was in before.
However, if he had been brought into the open air at the time of twilight, he would,
by degrees, have learned to discern the objects,
and come to an ability of beholding everything in a clear day aright.

Agreeably to this, in the reigns of kings Henry the VIIIth, and the bloody Queen Mary,
the principal test in England was whether a man acknowledged
the bodily presence of Christ in the sacrament;
and he who denied this, was to be burnt as a heretic.
Also in the Netherlands,
it was enough to bring a man to the stake if he but confessed to have been re-baptized.
Thus, in those days,
it seems that the Lord did raise up zealous men chiefly
to testify against the idolatry of the host,
and the error of infant baptism,
that so He might gradually break down the great structure of human inventions.

Now, however small the beginnings of this great work of reformation were,
yet it increased over time;
and oftentimes extraordinary instances were seen
of the workings of the power and Spirit of God.

In the year 1513, I find that one John Le Clerc, of Meaux in France,
being at Metz in Lorrain, was filled with such zeal against idolatry,
that he broke to pieces the images in a chapel,
which the next day were to have been worshipped in a very solemn manner.
And being taken prisoner for this act, and cruelly tortured to death,
he was so eminently strengthened (even to the amazement
of the beholders) that in the height of the torments,
being torn with red hot pincers,
he said (from Ps. 115) "`Their idols are silver and gold, the work of men`'s hands.`"

// lint-disable invalid-characters à
Not less was the zeal of one Aymond à Vie, imprisoned in France about the year 1541,
because he had preached the gospel undauntedly.
And though he had been advised to flee, yet he would not be persuaded thereto,
but said with a heroic mind, "`I would rather never have been born,
than commit such a base act; for it is the duty of a good pastor not to flee from danger,
but to stay in it, lest the sheep be scattered.`"
He was tortured cruelly to betray the names of his fellow believers; but no torment,
however so great, could extort the name of any from him.
He suffered death valiantly for the testimony of Jesus,
feeling himself very powerfully strengthened by the Spirit of God,
which worked so gloriously in the martyrs of those times,
that those of Merindol in Provence said, "`The Holy Spirit is an infallible teacher,
by whose inspiration all Christians receive the knowledge of truth.
This Spirit dwells in them, He regenerates them to a new life,
He slays the old man in them, and He makes them alive to every good work,
consoling them in tribulations, and strengthening them in adversities,`" etc.

And the pious professors at Meaux, I find mentioned in the year 1546,
that though a great number of men and women were led prisoners by but a few,
they yet made no resistance, but showed themselves harmless, not sad with grief,
but singing with joy.
And so powerfully did God work in Gabriel Beraudin,
who was executed at Chambery in Savoy, in the year 1550,
that after his tongue was cut off by the hangman, he spoke intelligibly to the people,
and proclaimed God`'s praise in a miraculous manner.

Claude Morier being burnt very cruelly at Lyons in France, wrote while in his prison,
"`Let us pray to our heavenly Father continually, that He create in us a clean heart,
that He give us a new heart, that He guide our will by the leadings of His Spirit.`"

It is also very remarkable that Godfried de Hammelle, one year after this,
being imprisoned at Tournay in the Netherlands,
and being told that the Apostle in his Epistle to the Ephesians,
had called marriage a sacrament, said in a letter,
"`That though at first this had puzzled him,
yet the Lord had not long left him in this difficulty, but put him in mind by His Spirit,
that the word there was not sacrament, but mystery.`"
For the martyrs of those times did not hesitate to profess (in agreement with
the primitive Christians) that the children of God must be led by His Spirit.

Peter Schryver, burnt at Lyons about the year 1552, wrote from prison,
"`That he having heard God`'s pure word preached, believed it,
because the Spirit of God gave him a testimony +++[+++or evidence]
of it in his heart, and did so confirm it to him,
and he could not question it in the least.`"
He also said in his letter, "`That once having prayed to God,
he had been so refreshed by the virtue of His Spirit, and so strengthened,
that though he sat in a dark nasty place, yet he felt such consolation and joy,
that it overcame all sorrow and anguish.
No,`" said he, "`the least comfort and joy I feel now in my bonds,
surpasses all the joys that ever I had in my life;
for now the Holy Spirit puts me in mind of those gracious promises
that are made to those who suffer for His name`'s sake.`"
And being asked how he knew that which he asserted to be the pure word of God,
he answered, "`Because it did agree with the doctrine of the prophets and apostles,
and that of Jesus Christ; and that the Holy Spirit gave him a certain evidence of it.`"
Concerning the indwelling of God`'s Spirit in man,
he also speaks very notably in his letter to John Chambon,
(whose wonderful conversion in prison was an eminent proof of the truth of his sayings),
telling him, "`That his heavenly Father was near him,
and by His Spirit dwelt in his heart.`"

That this was also the doctrine of John Calvin,
appears from his letters to the said man and his fellow-prisoners, where he says,
"`Do not doubt but God will, in those things wherein He will use your service,
give you that power, by which the work in you being begun will be perfected,
for that He has promised to do.
And we have many examples and instances of that excellent faith by which we clearly know,
that God has never in anything failed those who have been led and guided by His Spirit.
Trust firmly, brethren, that when it is needful,
you will become so strong and steadfast that you
shall not faint under any burden of temptations,
however great and heavy.
The fight is now at hand, to which the Holy Spirit exhorts us,
not only that we should go, but even that with all alacrity of mind, we should run.`"
Many other excellent testimonies of eminent men of those times might be produced.
And it also is very remarkable that Peter Bergier, being prisoner at Lyons,
in the year 1553, and afterwards suffering death, cried out in the midst of the flames,
"`I see the heavens opened.`"

Now that the doctrine of being taught by the Spirit of God
was generally received by the martyrs of those times,
we learn from many of their writings.
Denis Peloquin, burnt in the same year at Vile Franche, said in his confession,
"`That it was the Holy Spirit that bore witness in his conscience,
that the books of the Old and New Testament were the Holy Scripture.`"
Lewis de Marsac being about the same time put to death by fire at Lyons,
when he was asked how he knew the Holy Scriptures to be the gospel, said,
"`God has taught me so by His Spirit.`"
And being also asked whether it was his incumbent duty to read the Holy Scriptures,
and who had instructed him concerning them, he answered,
that "`God by His Spirit had effected it,
and that without His grace and the enlightening of His Spirit,
I could not comprehend and understand anything in the gospel.`"
John Calvin did also write to the aforesaid Peloquin and Marsac;
"`God will cause the confession which you will make according
to the measure of the Spirit He has given you,
to produce a greater fruit of edification, than all others that might be sent to you.`"
And to Matthew Dymonet, prisoner at Lyons, he wrote thus:
"`Submit modestly to the guidings of God`'s Spirit;
answer with all moderation and discretion, keeping to the rule of the Scriptures,
'`I have believed,
and therefore I will speak;`' but let not this hinder you to speak freely and sincerely,
being persuaded that He who promised to give us a mouth,
and such wisdom as the gainsayers cannot withstand, will never forsake you.`"

More of the like instances of the operations of the
Spirit of God in his witnesses I could recount,
if I had so intended;
but I give here only a slender sketch of the sincerity and the principles
of those that were come but to the dawnings of the Reformation.
Nor can I esteem that time any higher than the dawnings of the day,
because the eyes of the most zealous men of those days were still
so much clouded with the fogs which then covered the church,
and the prejudice of the old leaven,
that they did not discern all things in a full clearness.
For one saw the error of one thing, and others of another,
but human affection did work too strong, and thereby they also judged one another,
as is abundantly mentioned in history.

If we rightly look into this,
it seems very absurd to think that the Reformation (which in former
times had been largely advanced by some eminent men;
such as Luther, Melancthon, Ecolompadius, Calvin, Menno, and others),
was then brought to perfection;
for we find that even those reformers themselves
at first had not such a clear sight into many things,
as they afterwards obtained.
Therefore,
since England is the chief stage on which the things
I intend to describe have been transacted,
I will turn my face there,
to take a cursory view of the beginning and progress of the Reformation there.

Passing by Wycliffe and others, I begin with Thomas Cranmer,
who (because of his sincere and good life,
being advanced by King Henry the VIIIth to the Archbishop`'s seat of Canterbury) did
all that was in his power to reform the errors which had crept into the Church of Rome.
Therefore in the year 1536, he exhorted the king, who much loved him,
to proceed to a reformation,
saying that nothing in religion should be determined without clear proofs from Scripture;
and therefore he proposed that the following points needed to be inquired into:
"`whether there was a purgatory; whether deceased saints ought to be invoked;
and how images were to be regarded;`" for it began
to appear that several things were errors,
for which some people not long before had suffered death.

Some time after, Thomas Cromwel a chief minister of the kingdom,
and a great friend of Cranmer,
published some injunctions in the king`'s name wherein all
churchmen were required to cease recommending images,
relics, or pilgrimages, and instead to teach the people the Lord`'s Prayer, the Creed,
and the Ten Commandments in English.
This was a great step towards the translation of the Bible into English,
which being also furthered by Cranmer, the next year came out in print;
and by the king`'s warrant, the clergy were required to set up Bibles in their churches,
so that now all that could, might read the holy Scripture in their native tongue.
Cranmer not content with this, obtained in the year 1539,
a permission for all people to have the Bible in their houses.
However, despite all this,
he was still an asserter of the bodily presence of Christ in the
host until in the year 1549. In the reign of King Edward VI.,
when the times were more free, he was induced by Nicholas Ridley (a zealous reformer,
and afterwards a martyr under Queen Mary) to inquire better into this doctrine,
and to discover the absurdity of it;
after which he did not only oppose and suppress this superstition, but also many others;
and it is likely, that if opportunity had been given him,
he would have reformed even more.
Nevertheless it cannot but be wondered at,
that he who seems to have been a man of a meek temper,
could give his vote to the burning of those whom he looked upon to be heretics;
such as John Nicholson (alias Lambert) in the reign of Henry VIII.
for denying the bodily presence of Christ in the sacrament;
and Joan Bocher and George Parr,
under Edward VI. first for denying that Christ had taken flesh from the Virgin Mary,
and the latter for not believing the deity of Christ.
From this we may see what strong zeal for religion is able to effect.
But without question, he had come to be of another mind when, in the year 1556,
under the bloody reign of Queen Mary,
he was also forced to undergo the same lot of being burnt alive.

Now, though after his death,
the bishops under Queen Elizabeth were content with the reformation made by Cranmer,
yet it pleased God in the year 1568,
to raise up other persons to testify publicly against many of the remaining superstitions.
And although Coleman, Burton,
Hallingham and Benson were imprisoned by the queen`'s order,
yet they gained many followers, and also acquired the name of Puritans.
And notwithstanding the Archbishop, in order to prevent this,
drew up some articles of faith to be signed by all clergymen,
yet he met with great opposition in the undertaking.
For Robert Brown, a young student of Cambridge,
(from whom the name Brownists was afterwards borrowed), and Richard Harrison,
a schoolmaster, published some books in the year 1583,
wherein they showed how much the Church of England was still infected with Romish errors.
This had such an effect, that the eyes of many people came thereby to be opened,
who so valiantly maintained that doctrine which they believed to be the truth,
that some of the most zealous among them (namely, Henry Barrow, John Greenwood,
and John Penry, about the year 1593) were put to death because of their testimony.
It is believed that this was done more by the instigation of the clergy,
than by the desire of the queen; for sometime after it happened,
she asked Dr. Reynolds his opinion of those men, especially Barrow and Greenwood,
to which he answered, "`It will not avail anything to show my judgment concerning them,
seeing they were already put to death.`"
But upon the queen yet pressing him further, he said, "`I am persuaded if they had lived,
they would have been two as worthy instruments for the Church of God,
as had been raised up in this age.`"
At which the queen sighed and said no more.
But afterwards, when riding by the place where they were executed,
and calling to mind their death, she inquired of the Earl of Cumberland,
who was present when they suffered, what sort of end they made.
He answered, "`A very godly end, and they prayed for your Majesty and for the State.`"
Moreover one Philips, a famous preacher, having seen Barrow`'s preparation for death,
said, "`Barrow, Barrow, may my soul be with yours.`"

After the death of Queen Elizabeth, when James I. had ascended the throne,
the followers of those men suffered much for their separation from the Church of England.
But it is very remarkable,
that even those of that persuasion (many of whom
in the reign of King Charles I. went to New England,
to avoid the persecution of the bishops) afterwards
themselves turned cruel persecutors of pious people,
by inhuman whippings,
etc. and eventually by putting some to death by the hands of a hangman.
And this is a clear proof indeed,
that those in whom such a ground of bitterness remained (though it had not always
brought forth the same abominable fruits) had not yet come to a perfect reformation;
for though the stem of human traditions and institutions had sometimes been shaken strongly,
yet much of the old root was left.
Therefore it pleased God, who generally enlightens men gradually,
to make yet a clearer discovery of His truth,
which in some places had already sent forth its beams to mankind,
in a time when many godly people were zealously seeking
after a further manifestation of the will of God.
These had a sense that,
notwithstanding all their outward observations of religious performances,
there still stood a partition wall whereby the soul was hindered
from living in perfect peace with its Creator.

For in that time there were in England many separate Christian societies,
and among the rest were those who were called Seekers,
who at first seemed to be a people of great promise,
but their end showed that their foundation was not the Rock of Ages,
for many of them soon lost their first integrity.
Now it was that those people who began to take heed to a divine conviction in the conscience,
and accordingly preached to others the doctrine of an inward light,
with which Christ had enlightened men,
began to increase in number (in the latter end of the time of King
Charles I.) and they became a separate society among men,
and in the process of time the name of Quakers was in scorn imposed on them.
And finding that in most countries in Europe they
have been accused of many exorbitant absurdities,
both in life and doctrine, I have designed to describe impartially,
and according to truth, the first beginnings and rise,
and also the progress of this people,
and to stretch out the relation of their increase and transactions
so far as my time of life and leisure will permit.

I enter upon a work which, consisting of many very extraordinary occurrences,
in its beginning appears hard and difficult, and in the process often sad and dreadful.
For among manifold adversities, we shall not only meet with bitter revilings,
scornful mockings, rude abuses, and bloody blows from the fool-hardy rabble;
but also severe persecutions, hard imprisonments, grievous banishments,
unmerciful spoil of goods, cruel whippings, cutting off of ears, smothering in prisons,
and also putting to death by the hands of the hangman, by order of the magistrates;
afterwards a time of quiet and rest, and then again severe persecution,
until the furious promoters of it were at last wearied,
and desisted from their mischievous labor for a time--more for being at their wits end,
than out of mercy.
And among all these fluctuations,
notable instances have been seen of unfeigned godliness, sincere love,
much true-heartedness, extraordinary meekness, remarkable patience, ardent zeal,
undaunted courage, and unshaken steadfastness, even among the female sex,
which though the weakest, yet in the hardest attacks, showed a more than manly spirit;
insomuch, that few ages have afforded more powerful examples of virtue to be seen.

The first I find to have been thus immediately reached in his mind,
was a young man called George Fox, born at Drayton in Leicestershire,
in the month called July, in the year 1624,
from parents that were members of the public church,
or Church of England (as appears to me from a paper, drawn up by his order,
in his life-time, at my request, and sent to me).
His father was Christopher Fox, a weaver by trade, an honest man,
and of such a virtuous life that his neighbors used to call him Righteous Christer.
His mother was Mary Lago, an upright woman, and of the stock of the martyrs.
This George Fox was even in his minority endued with a gravity
and staidness of mind that is seldom seen in children;
so that he seeing how old people carried themselves lightly and carelessly,
had such an aversion to it, that he would say within himself,
"`If ever I come to be a man, surely I will not be so careless.`"
His parents in the meantime endeavored to train him up, as they did their other children,
in the common way of worship, his mother especially contributing thereto,
as being eminent for piety.

But even from a child he was seen to be of another frame of mind than his brethren;
for he was more religious, retired, still, and solid,
and was also observant beyond his age, as appeared from the answers he gave,
and the questions he asked, concerning religious matters,
to the astonishment of those that heard him.
His mother seeing this extraordinary temper and godliness,
which so early shined through him, so that he would not meddle with childish play,
did not think fit to trouble him about the way of worship,
but carried herself indulgent towards him.
Meanwhile he learned to read pretty well,
and to write as much as would serve him afterwards to signify his meaning to others.
When he had come to eleven years of age, he endeavored to live a pure and righteous life,
and to be faithful in all things, both inwardly to God, and outwardly to man;
for the Lord by His good Spirit had showed him, that he was to keep his word always,
and that he ought not to commit excess in eating or drinking.
Thus growing up in virtue,
some of his relations were for having him trained
up in the schools to make a priest of him;
but others persuaded to the contrary,
and so he was put apprentice to a shoemaker who also dealt in wool and in cattle.
In his master`'s employment he took most delight in sheep,
and was very skillful in what belonged thereto,
for it was an employment that very well suited his mind;
and his thus being a shepherd was (as an eminent author says),
"`a just symbol of his later ministry and service.`"
He acquitted himself so diligently in his business, and minded it so well,
that his master was successful in his trade while George was with him.
He often used in his dealings the word "`Verily,`" and then he kept so strictly to it,
that people that knew him would say,
"`If George says '`Verily,`' there is no altering him.`"

Now, though my design is not to give a description of state affairs,
yet I find it necessary to mention something of the chief temporal occurrences in England,
in as much as they may have relation to the affairs of the church,
lest my history might seem an incomplete work.
Briefly therefore I will say, that in England about this time,
there appeared the beginnings of a civil war, in which religion had some share;
for the bishops began to introduce several innovations,
causing rails to be made around the communion table (which now was called the high altar),
and requiring those who approached it to bow three times,
and each bow was made at the pronouncing of the name of Jesus.
Such ceremonies increased over time, and the preachers who were truly religious,
and who spoke most unto edification, were slighted and set by;
for the bishops chiefly sought to promote such rituals as favored popery.^
footnote:[Throughout this history, __popery__ refers to the doctrines, practices,
and ceremonies associated with the Pope or the papal system; i.e. Roman Catholicism.]
This was not only done in England,
but in Scotland also endeavors were made to bring in episcopacy.^
footnote:[Episcopacy refers to the governance of the church
by a hierarchy of bishops appointed by the state.]
This caused a great stir among the people,
which at last came to an insurrection that was generally
believed to be for religion`'s sake,
and which made some cry in the open streets, "`To your tents, O Israel!`"
And because the Parliament was of the opinion that
King Charles I. encroached upon their privileges,
which they would not permit,
this so exasperated the prince that he brought together an army, and set up his standard,
first on the castle of Nottingham, where it was blown down the same evening,
on the 25th of the month called August, in the year 1642.
But before that time the king had taken possession of some fortified places,
and the Parliament on the other hand, had also got territory in their power.
Some time after,
a battle was fought between the royalists and the Parliament near Edge Hill,
in Warwickshire, where neither party prevailed much.

About this time, George Fox, who more and more endeavored to lead a godly life,
having come to the nineteenth year of his age, it happened at a fair,
that a cousin of his and another coming to him,
asked whether he would drink a jug of beer with them.
He being thirsty, said yes, and went with them to an inn;
but after each had drank a glass, they began to drink healths,^
footnote:[To toast, or drink to the health or honor of another.]
and said, "`he that would not drink should pay for all.`"
This grieved George much,
seeing that people who professed to be religious behaved themselves in this way,
and therefore he rose up to be gone; and putting his hand into his pocket,
he took a groat,^
footnote:[A silver coin, worth four pence.]
and laid it down upon the table, saying, "`If it must be so,
I will leave you,`" and so he went away.
And when his business was done, he returned home, but did not go to bed that night,
but prayed and cried earnestly to the Lord;
and it seemed to him that his supplications were answered by the Lord after this manner,
"`You see how young people go together into vanity, and old people go into the earth;
therefore you must forsake all, both young and old, and be as a stranger to them.`"
This, which he took to be a divine admonition,
made such a powerful impression on his mind,
that he resolved to break off all familiar fellowship
and conversation with young and old,
and even to leave his relations, and live a separate and retired life.

On the 9th of September, in the year 1643, he departed to Lutterworth,
where he stayed some time, and from there went to Northampton,
where he also made some stay, and then passed to Newport-Pagnel, in Buckinghamshire;
and after having stayed a while there, he went to Barnet,
where he came in the month called June, in the year 1644.

While he thus led a solitary life, he fasted often,
and read the Holy Scriptures diligently, so that some professors^
footnote:[Throughout this history,
the word __professors__ refers to those who profess faith in Christ.
Here the word has nothing to do with teachers or scholars.]
took notice of him and sought to be acquainted with him.
But he soon perceiving they did not possess what they professed, grew afraid of them,
and shunned their company.
In this time he fell into a strong temptation, almost to despair,
and was in great trouble, sometimes keeping himself retired in his chamber,
and often walking solitary to wait upon the Lord.
In this state he saw how Christ had been tempted;
but when he looked to his own condition, he wondered, and said, "`Was I ever so before?`"
He began to think also that he had done wrong to his relations,
because he had forsaken them; and he called to mind all his former time,
to consider whether he had wronged any.
Thus temptations grew more and more;
and when Satan could not effect his design upon him that way,
he laid snares for him to draw him to commit some sin, thereby to bring him to despair.
He was then about twenty years of age, and continued a long while in this condition,
and would eagerly have been freed from it;
which made him go to many a priest to look for comfort,
but he did not find it from them.

In this miserable state he went to London,
in hopes of finding some relief among the great professors of that city;
but having come there, he saw them to be much darkened in their understandings.
He had an uncle there, one Pickering, a baptist,
and those of that persuasion were tender then;
yet he could not resolve to impart his mind to them, or join with them,
because he saw all, young and old, where they were.
And though some of the best would have had him stay there, yet he was fearful,
and so returned homewards;
for having understood that his parents and relations were troubled at his absence,
he would rather go to them again lest he should grieve them.
Now when he had come into Leicestershire, his relations desired him to marry;
but he prudently told them he was but a lad, and must get wisdom.
Others desired him to join the auxiliary troops among the forces of the Parliament,
which being entered now into a civil war with the king, had, with their forces this year,
beaten not only the king`'s army under Prince Rupert,
but also had conquered the city of York.
But to persuade George to enlist himself as a soldier, was so against his mind,
that he refused it, and went to Coventry,
where he took a chamber for a while at a professor`'s house and stayed some time,
there being many people in that town who endeavored to live religiously.
After some time he went into his own country again, and was there about a year,
in great sorrows and troubles, walking many nights by himself.

Nathaniel Stevens, the priest of Drayton (the town of George`'s birth),
would often come to him, and George to the priest.
And when Stevens visited him, he would sometimes bring another priest along with him,
and then George would ask them questions, and reason with them.
Once Stevens asked him why Christ cried out upon the cross.
"`My God, My God, why have You forsaken Me:`"--and why He said, "`If it be possible,
let this cup pass from Me; yet not My will but Yours be done.`"
To this George answered thus: "`At that time the sins of all mankind were upon Christ,
and their iniquities and transgressions with which He was wounded, which He was to bear,
and to be an offering for them, according as He was man;
but He died not according as He was God: and so, in that He died for all men,
and tasted death for every man, He was an offering for the sins of the whole world.`"
When George Fox spoke this,
he was in some measure sensible of Christ`'s sufferings and what He went through.
And his saying did so please the priest, that he said it was a very good full answer,
and such a one as he had not heard before.
He would also applaud and speak highly of George Fox to others,
and what George said in private discourse with him,
he would preach on the First-days of the week; for which reason George did not like him.

After some time he went to an ancient priest at Mansetter, in Warwickshire,
and reasoned with him about the ground of despair and temptations;
but he being altogether ignorant of George`'s condition,
bid him take tobacco and sing psalms.
But George said that he was no lover of tobacco, and as for psalms,
he was not in a state to sing.
Then the priest bid him come again, and that then he would tell him many things.
But when George came, the priest was angry and peevish,
for George`'s former words had displeased him.
And he was so indiscreet, that what George had told him of his sorrows and griefs,
he repeated to his servants, so that it got among the dairy-maids;
and it grieved him to have opened his mind to such a man,
saying to himself they were all miserable comforters.
Then he heard of a priest living near Tamworth who was considered an experienced man,
and so he went to him, but found him like an empty hollow cask.

Hearing afterwards of one Dr. Cradock of Coventry, he went to him also,
and asked him from where temptations and despair did arise,
and how troubles came to be wrought in man.
The priest, instead of answering, asked him who was Christ`'s father and mother.
George told him, "`Mary was His mother; and He was supposed to be the son of Joseph;
but He was the Son of God.`"
Now as they were walking together in Dr. Cradock`'s garden, it happened that George,
in turning, set his foot on the side of a flower bed,
which so disturbed this teacher that he raged as if his house had been on fire.
Thus all their discourse was lost; and George went away in sorrow,
worse than he was when he came, finding none who could reach his condition.
After this he went to one Macham, a priest of high regard; and he,
being no more skillful than the others, was for giving George medicine and bleeding him;^
footnote:[At this time, __blood-letting__ was a common practice among physicians,
believed to prevent and cure all sorts of illness and disease.]
but they could not get one drop of blood from him, either in the arms or the head,
his body appearing dried up with sorrows, grief, and trouble.
At this time, his afflictions were indeed so great upon him,
that he could have wished to have never been born,
so as not to behold the vanity and wickedness of men; or that he had been born blind,
so as never to have seen it; or deaf, that he had never have heard vain and wicked words,
or the Lord`'s name blasphemed.
And when the time called Christmas came,
while others were feasting and sporting themselves,
he went from house to house looking for poor widows, and giving them some money.
And when he was invited to marriages (as sometimes he was), he would go to none at all;
but the next day, or soon after, he would visit those that were newly married;
and if they were poor, he gave them some money;
for he had enough both to keep himself from being chargeable to others,
and to administer something to the needy.

While the mind of George Fox was thus in trouble,
the state of England was also in a great stir;
for the Parliament was in favor of removing all bishops,
and introducing the Presbyterian Directory; which, however,
could not yet be well accomplished.
Nevertheless, William Laud, Archbishop of Canterbury,
had been made to stoop to the block,^
footnote:[i.e. kneel down to the wooden block to be decapitated.]
and the power of the king by this time was much weakened.
This summer near Naseby, not far from Leicester,
the king`'s army was overcome by an army of untrained troops,
and about six thousand men were taken prisoners (among whom were many great officers),
and his cabinet, with an abundance of letters of great importance, was seized.

But since a circumstantial description of these state affairs is not within my design,
I will return again to George Fox, who in the beginning of the year 1646,
as he was going to Coventry and entering towards the gate,
a consideration arose in him how it was said that all Christians are believers,
both Protestants and Papists.
And it was opened to him that true believers were those who had been born of God,
and had passed from death to life, and that none were rightly called believers but these,
though many others said they were believers.
At another time as he was walking in a field on a First-day morning,
it was made known to his understanding that to be educated at Oxford
or Cambridge was not enough to make a man a minister of Christ.
At this he marveled, because it was the common belief of people;
but he took this to be a divine revelation, and admired at the goodness of the Lord,
believing now that the ordinary ministers were not such as they pretended to be.
This made him unwilling to go any more to "`church,`" as it was called,
to hear the priest Stevens, believing that he could not truly profit thereby.
And therefore, instead of going there, he would go into the orchards or fields,
by himself, with his Bible (which he esteemed above all books),
seeking thus to be edified in solitude.
At this his relations were much troubled; but he told them,
"`Did not John the Apostle say to the believers, '`they needed no man to teach them,
but the anointing teaches them all things;`'`" and though they knew this to be Scripture,
and that it was true,
yet it grieved them because he would not go to hear the priest with them,
but separated himself from their way of worship.
For he saw now that a true believer something other than they looked upon it to be,
and that being educated at the universities did not
qualify a man to be a minister of Christ.
Thus he lived by himself, not joining with any, not even among the dissenting people,^
footnote:[The dissenting people, or dissenters, were Christian people who,
for a variety of reasons, did not agree with or conform to the religion of the state.]
but became a stranger to all, relying wholly upon the Lord Jesus Christ.

Some time after, it was opened in him, that God, who made the world,
did not dwell in temples made with hands.
And though this seemed at first strange to him,
because both priests and people used to call their churches dreadful places, holy ground,
and temples of God; yet it was immediately showed him,
that the Lord did not dwell in these temples which man had erected,
but in peoples hearts, and that His people were the temple He dwelt in.
This was shown to him when he was walking in the fields to the house of one of his relations.
And when he came there, he was told that Nathaniel Stevens the priest had been there,
and had said he was afraid of Fox, for going after new lights.
This made him smile, because now he saw the true state of the priests.
But he said nothing of this to his relations, who,
though they saw that something more was required than the common way of worship,
yet they continued therein,
being grieved because he would not also go to hear the priests.
Yet he would tell them there was an anointing in man, to teach him;
and that the Lord would teach His people Himself.
He had great openings now concerning the things written in the book of Revelation;
and when he spoke of them, the priests and professors would say,
that was "`a sealed up book.`"
But to this he said,
"`Christ could open the seals,`" and that "`the things contained in that book,
very nearly concerned us;
since the Epistles of the Apostles were written to the saints of those times,
but the book of Revelation speaks of things to come.`"

In those days, there were people of very odd notions in England,
and among the rest such as held that "`women have no souls.`"
Coming upon some of these, he could not forbear reproving them,
since the Scripture (as he told them plainly) held forth the contrary;
for the blessed Virgin Mary said, "`My soul does magnify the Lord;
and my spirit has rejoiced in God my Savior.`"
He also came among a people that relied much on dreams; but he told them,
"`Except they could distinguish between dream and dream,
their observations would be nothing but confusion,
since there were three sorts of dreams;
for multiplicity of business sometimes caused dreams,
and there were whisperings of Satan in the night seasons,
and there were also speakings of God to man in dreams.`"
But because these people were more in need of a clear discerning, than of good will,
they at length came out of those imaginations,
and at last became fellow-believers in Truth with him.
But though he had great openings in his understanding,
still great trouble and temptations many times came upon him; so that when it was day,
he wished for night, and when it was night, he wished for day.
Nevertheless, among all these troubles, his understanding was so opened,
that he could say with David, "`Day unto day utters speech,
and night unto night shows knowledge;`" for even in these troubles
he had great openings of many places in Scripture.

As to state affairs, things continued in a disturbed condition; for the king,
who after his army had been beaten, fled to the Scots,
and was by them delivered up to the English; to whom now he could no more prescribe laws,
but was willing to receive them.
And the Churchmen were also at variance;
for the Independents (several of whom sat also in Parliament) began to say,
that the difference between Episcopacy (against which
they had fought conjointly) and Presbytery,
was only in the name and in a few outward circumstances;
seeing that people of a tender conscience might expect to be no
less oppressed by the Presbyterians than they had been by the Episcopalians;
and that this fear was not vain or idle, time afterwards has shown abundantly.

But let us return to George Fox, who in the beginning of the year 1647,
feeling some drawings to go into Derbyshire, went there,
and meeting there with some friendly people, had many discourses with them.
Then passing further into the Peak-Country, he met with more such people,
and also some that had been swayed by empty and high notions.
And traveling into Nottinghamshire, there he met with a tender people,
and among these was one Elizabeth Hooton, of whom more will be said in its place.
With these he had some meetings and discourses,
but his troubles and temptations still continued.
He fasted much, and walked often abroad in solitary places, taking his Bible with him;
and would sit in hollow trees and lonesome places till night came on.
And frequently in the night he would walk mournfully about,
being surrounded with many sorrows in the times of
these first workings of the Lord in him.

During all this time, he never joined in religious profession with any,
but gave himself up to the disposing of the Lord;
having forsaken not only all evil company, but also taken leave of father and mother,
and all other relations; and so he travelled up and down as a stranger on the earth,
whichever way he felt his heart inclined.
And when he came into a town, he took a chamber to himself there,
and stayed sometimes a month, sometimes more, sometimes less, in each place;
for he was afraid of staying long in any one place, lest, being a tender young man,
he should be hurt by too familiar an interaction with men.

Now, though it might seem not very agreeable with the seriousness of my work,
to mention what kind of clothes he wore in these first years of his peregrination;
yet I do not count it absurd to say here,
that it is indeed true what a certain author named Gerard Croes relates of him,
that he was clothed with leather.
But this was not (as the said author adds) because he could not, nor would not,
forget his former leather work; but partly for the simplicity of that dress,
and also because such a clothing was strong, and needed but little mending or repairing,
which was convenient for him who had no steady dwelling place,
and everywhere sought to live in a solitary state.
For keeping himself thus as a stranger, he sought heavenly wisdom,
and endeavored to get knowledge of the Lord, and to be weaned from outward things,
to rely wholly on the Lord alone.

Although his troubles were great, yet they were not so continual,
but that he had some intermissions, and was sometimes brought into such a heavenly joy,
that admiring the love of God to his soul, he would say with the Psalmist, "`You, Lord,
make a fruitful field a barren wilderness, and a barren wilderness a fruitful field.`"
Now he regarded the priests but little,
because he clearly saw that to be trained up in the universities,
and to be instructed in languages, liberal arts, and the like sciences,
was not sufficient to make anyone a minister of the gospel.
For a time he looked more towards the dissenting people;
yet as he had forsaken the priests, so he left the separate preachers also,
because he saw there was none among them all that could speak to his condition.
And when all his hopes in them, and in all men were gone,
then he heard (according to what he himself relates) a voice which said, "`There is one,
even Christ Jesus, that can speak to your condition.`"
Having heard this, his heart leapt for joy,
and it was showed him why there was none upon the earth that could speak to his condition--namely,
that he might give the Lord alone all the glory,
and that Jesus Christ might have the preeminence.

He then experientially knowing that Christ enlightens man, and gives him grace, faith,
and power, his desires after the Lord,
and his zeal in the pure knowledge of God grew even stronger;
so that he wished to increase therein without the help of any man, book, or writing.
And though he was a diligent reader of the Holy Scriptures,
which speak much of God and Christ, he knew Him not except by revelation,
according as He, who had the key, did open.
Thus he entered into no fellowship with any society of people,
because he saw nothing but corruptions everywhere,
which made him endeavor to keep fellowship only with Christ.
For in the greatest temptations, when he almost despaired, it was showed to him,
that Christ had been tempted by the same devil,
but that He had overcome him and bruised his head, and that therefore through the power,
light, grace, and Spirit of God, he himself might also overcome.
Thus the Lord assisted him in the deepest miseries and sorrows,
and he found His grace to be sufficient; insomuch that,
though he had yet some desires after the help of men,
his thirst was chiefly after the Lord, the Creator of all, and His Son Jesus Christ,
because nothing could give him any comfort except the Lord by His power.
And he clearly saw that all the world, though he had possessed a king`'s estate,
would not have profited him.

In this condition his understanding came more and more to be opened,
so that he saw how death in Adam had passed upon all men; but that by Christ,
who tasted death for all men, a deliverance from it, and an entrance into God`'s kingdom,
might be obtained.
Nevertheless his temptations continued,
so that he began to question whether he might have sinned against the Holy Spirit.
This brought great perplexity and trouble over him for many days;
yet he still gave himself up to the Lord.
And one day, when he had been walking solitarily abroad, and had come home,
he became exceeding sensible of the love of God to him,
so that he could not help but admire it.
Here it was showed to him, that all was to be done in and by Christ;
that He conquers and destroys the tempter, the devil, and all his works,
and that all these troubles and temptations were good for him,
for the trial of his faith.
The effect of this was that, though at times his mind was much exercised,
yet he was stayed by a secret belief; and his soul,
by a firm hope (which was to him as an anchor), was kept unhurt in the dissolute world,
swimming above the raging waves of temptations.
After this, (as he relates himself), a pure fire did appear in him;
and he saw that the appearance of Christ in the heart was as a refiner`'s fire,
and as the fuller`'s soap.
A spiritual discernment was given to him,
by which he saw what it was that veiled his mind, and what it was that did open it;
and that which could not abide in patience, he found to be of the flesh,
which could not give up to the will of God, nor yield itself up to die by the cross,
which is the power of God.
On the other hand,
he perceived it was the groans of the Spirit which did open his understanding,
and that there must be a waiting upon God in that Spirit to obtain redemption.

About this time he heard of a woman in Lancashire who had fasted twenty-two days,
and he went to see her.
But coming there he saw that she was under a temptation,
and after speaking to her what he felt on his mind, he left her,
and went to Duckenfield and Manchester,
where he stayed awhile among the professors there,
and declared to them that doctrine which now he firmly believed to be truth.
Some were convinced, and received the inward divine teaching of the Lord,
and took that for their rule.^
footnote:[That which should govern or have authority in the heart and life of a believer.]
This, by what I can find, was the first beginning of George Fox`'s preaching;
which as I have been credibly informed, in those early years,
chiefly consisted in but a few, powerful and piercing words,
to those whose hearts were already in some measure
prepared to be capable of receiving this doctrine.
And it seems to me that these people, and also Elizabeth Hooton (already mentioned),
have been the first who, by such a simple or weak preaching,
came to be his fellow-believers;
though there were also some others who were convinced directly by the Lord,
as George Fox himself was,
and came to see that they ought diligently to take heed to the
teachings of the grace of God that had appeared to them.
And thus it happened that these unexpectedly and unaware came to meet with fellow-believers,
with whom they were not acquainted before, as will be more fully related hereafter.

But to return again to George Fox;
it set the professors of those times in a rage that
some of their adherents hearkened to his preaching;
for they could not endure to hear perfection spoken of, and a holy and sinless life,
as a state that could be obtained here.
Not long after this he travelled to Broughton in Leicestershire,
and there went into a meeting of the Baptists,
where some people of other nations also came.
This gave him an occasion to preach the doctrine of truth among them,
and that not in vain; for he had received great openings in the Scriptures.
And because a special power of the Lord`'s working had begun to spring up in those parts,
several were so reached in their minds that they came to be convinced,
and were turning from darkness to light, partly by his preaching,
and partly by reasoning with some.
Yet he himself was still sometimes under great temptations,
finding none to whom he could open his condition but the Lord alone,
unto whom he cried night and day for help.

Some time after he went back into Nottinghamshire,
and there it pleased the Lord to show him that the
natures of those things which were hurtful without,
were also found within, in the minds of wicked men; and that the natures of dogs, swine,
vipers, and those of Cain, Ishmael, Esau, Pharaoh,
etc. were in the hearts of many people.
But since this did grieve him, he cried to the Lord, saying, "`Why should I be thus,
seeing I was never addicted to commit those evils?`"
And inwardly it was answered him that "`It is needful
you should have a sense of all conditions;
how else could you speak to all conditions?`"
He also saw how there was an ocean of darkness and death,
but also an infinite ocean of light and love, which flowed over the ocean of darkness;
in all which he perceived the infinite love of God.
About this time it happened that while walking in the town of Mansfield,
by the side of the steeple-house,^
footnote:[Early Friends used the term steeple-house to refer to large
mass-houses or church buildings generally used by the Church of England.]
it was inwardly told him,
"`That which people trample upon must be your food;`" and at the saying of this,
it was opened to him that it was the life of Christ which people did trample upon,
and that they fed one another with words,
without seeing that thereby the blood of the Son of God was trampled under foot.
And though it seemed strange to him at first,
that he should feed on that which the high-minded professors trample upon,
yet it was clearly opened to him how this could be.

Then many people came far and near to see him;
and though he sometimes spoke and opened religious matters to them,
yet he was fearful of being drawn out by them.
Now the reason of people thus flocking to him might proceed partly from this:
there was one Brown,
who upon his deathbed spoke many notable things concerning George Fox by way of prophecy,
and among the rest,
said that "`He should be made instrumental by the Lord to the conversion of people.`"
And concerning others that were then something in appearance, he said,
"`They should come to nothing;`" which was fulfilled in time,
though this man did not live to see it, for he was not raised up from his sickness.
But after he was buried,
George Fox fell into such a condition that he not only looked like a dead body,
but unto many that came to see him he seemed as if he had really been dead;
and many visited him for about fourteen days time,
who wondered to see him so much altered in countenance.

At length his sorrows and troubles began to wear off,
and tears of joy dropped from his eyes,
so that he could have wept night and day with tears of joy, in brokenness of heart.
And to give an account of his condition to those that are able to comprehend it,
I will use his own words: "`I saw,`" says he, "`into that which was without end,
and things which cannot be uttered;
and of the greatness and infiniteness of the love of God,
which cannot be expressed by words.
For I had been brought through the very ocean of darkness and death,
and through and over the power of Satan, by the eternal glorious power of Christ;
I was brought even through that darkness which covered all the world,
and which chained down all, and shut up all in the death.
And the same eternal power of God which brought me through those things,
was that which afterwards shook the nation, priests, professors, and people.
Then I could say, I had been in spiritual Babylon, Sodom, Egypt, and the grave;
but by the Eternal power of God I had come out of it, and was brought over it,
and the power of it, into the power of Christ.
And I saw that the harvest was white, and the seed of God lay thick in the ground,
as ever wheat did that was sown outwardly, and there was none to gather it;
and for this I mourned with tears.`"
Now a report went abroad, that George Fox was a young man that had a discerning spirit;
whereupon many professors, priests, and people came to him, and his ministry increased;
for having received great openings, he spoke to them of the things of God,
and was heard with attention by many, who going away, spread the fame thereof.
Then came the tempter, and set upon him again,
charging him that he had sinned against the Holy Spirit; but he could not tell in what,
and then Paul`'s condition came before him,
how after he had been taken up into the third heavens,
and seen things not lawful to be uttered, a messenger of Satan was sent to buffet him,
that he might not exalt himself.
Thus George Fox, by the assistance of the Lord, got over that temptation as well.

Now the 47th year of that century drew to an end,
and state affairs in England grew more and more clouded and complicated; for the king,
not thinking himself any longer safe at Hampton Court
(where he had been brought from the army),
withdrew to the Isle of Wight.
The Parliament still insisted upon the abrogation of Episcopacy,
and sought to be master of the military forces.
And the king, not being willing to yield to this, was therefore kept in closer custody,
and was no more regarded as a Sovereign to whom obedience was due from the Parliament.

Under these domestic troubles,
the minds of many people were fitted to receive a nearer way and doctrine of godliness,
and it was in the year 1648 that several persons who were seeking the
Lord become fellow-believers and entered into society with George Fox.
These began to have great meetings in Nottinghamshire, which were visited by many.
About that time there was a meeting of priests and professors at a justice`'s house,
and George Fox went among them and heard them discourse
concerning how the Apostle Paul said,
"`He had not known sin, but by the law, which said, you shall not lust.`"
And since they held this to be spoken of the outward law, George Fox told them,
"`Paul spoke this after he was convinced; for he had the outward law before,
and was raised up in it, even when he was in the lust of persecution.
But here Paul spoke of the law of God in his mind, which he served,
and which the law in his members warred against.`"
This saying found so much entrance,
that those of the priests and professors that were most moderate yielded,
and consented that it was not the outward law but
the inward which showed the inward lust,
which the Apostle here spoke of.
After this, he went again to Mansfield,
where was a great meeting of professors and other people; and being among them,
and moved to pray, such an extraordinary power appeared,
and seized on the hearts of some in so eminent a manner,
that even the house seemed to be shaken.
And after he had prayed, some of the auditory began to say,
"`This resembles the days of the Apostles, when on the day of Pentecost,
the house where they were met was shaken.`"

Not long after this, there was another great meeting of professors,
where G. Fox came also, and hearing them discourse about the blood of Christ,
he cried out among them, "`Do you not see the blood of Christ?
You must see it in your hearts, to sprinkle your hearts and consciences from dead works,
to serve the living God.`"
This was a doctrine which startled these professors,
who sought to know the blood of Christ only without them,
not thinking that it was to be felt inwardly.
But a certain captain, whose name was Amos Stoddard, was deeply reached,
and seeing how they endeavored to bear G. Fox down with many words, he said,
"`Let the youth speak!
Hear the youth speak!`"
And coming afterwards to be more acquainted with G. Fox,
he had an opportunity to be further instructed in the way of godliness,
of which he came to be a faithful follower.

Some time after, G. Fox returned to Leicestershire, his own country,
where several tender people came to be convinced by his preaching.
Passing from there into Warwickshire, he met with a great company of professors,
who having come together in a field, were praying and expounding the Scriptures.
Here a Bible was given to him,
which he opened to the 5th of Matthew where Christ expounded some parts of the law.
From this passage G. Fox took occasion to open to
them the inward and outward state of man;
and as that which he declared began to get ground in some,
they fell into a fierce contention among themselves, and so parted.

Then he heard of a great dispute to be held at Leicester,
wherein people of several persuasions (such as Presbyterians, Independents, Baptists,
and Episcopalians) were all said to be concerned.
The meeting being appointed to be in the steeple house, he went there,
where an abundance of people had met, some of those who spoke being in pews,
and the priest being in the pulpit.
At last, after much debate, a woman started a question, and asked,
"`What is that birth which the Apostle Peter spoke of,
a '`being born again of incorruptible seed, by the word of God,
that lives and abides forever.`'`" Instead of answering this question,
the priest said to her,
"`I permit not a woman to speak in the church;`" though
he had before given liberty for any person to speak.
This kindled G. Fox`'s zeal, so that he stepped up and asked the priest,
"`Do you call this place (the steeple-house) a church?
Or do you call this mixed multitude a church?`"
But the priest not answering this, asked him what a church was.
G+++.+++ Fox told him,
"`The church is '`the pillar and ground of truth,`' made up of living stones,
living members, a spiritual household, which Christ is the head of:
but He is not the head of a mixed multitude, or of an old house made up of lime, stones,
and wood.`"
This caused such a stir, that the priest came down out of his pulpit,
and others came out of their pews, so that the dispute was marred.
But G. Fox went to a great inn,
and there disputed with priests and professors of all sorts,
maintaining what he had said before, till they all went away.
Yet several were convinced that day, and among these,
the woman who had first asked the question.

After this, G. Fox returned again into Nottinghamshire, and went into the Vale of Beavor,
where he preached repentance to the people.
Staying there some weeks, and passing through several towns,
many were convinced of the truth of his doctrine.
About this time, as he was sitting by the fire one morning, a cloud came over him,
and a temptation beset him.
And as he sat still, it was suggested to him, "`All things come about by nature.`"
For a time he was in a manner quite clouded, but continuing to sit still,
the people of the house perceived nothing.
At length a living hope arose in him, and also a voice that said,
"`There is a living God,
who made all things;`" and immediately the cloud and temptation vanished away,
whereby his heart was made glad, and he praised the Lord.

Not long after this,
he met with some people that held the mischievous notion that there was no God,
and that all things came about by nature.
But reasoning with them, he so confounded them,
that some were made to confess that there was a living God.
Then he saw that it was good for him to have been tried under such a cloud.
Now in those parts he had great meetings,
and as the divine power was working in that part of the country, many were gathered.
Then coming into Derbyshire, there was a great meeting of his friends at Eaton,
where many of them began to preach the doctrine of truth,
who afterwards were moved to declare the truth in other places as well.

George Fox coming about this time to Mansfield,
heard that in a town about eight miles off there was to be a meeting
of justices to deliberate about the hiring of servants.
Feeling a constraint upon his mind, he went there,
and exhorted them not to oppress the servants in their wages,
but to do what was right and just to them;
and he likewise admonished the servants to do their duty, and to serve honestly,
and they all received his exhortation kindly.
He felt himself also moved to go to several courts
and steeple-houses at Mansfield and other places,
warning them to leave off oppression, deceit, and other evils.
And having heard at Mansfield of a man in that country who was a common drunkard,
a noted whore-master, and a poet also, he went to him, and reproved him in an awful^
footnote:[Throughout this history, the word __awful__ carries its original meaning:
full of awe, serious, weighty, or reverent.]
manner for his evil courses.
This so struck the man, that coming afterwards to G. Fox,
he told him that he was so smitten when he spoke to him,
that he had scarce any strength left in him.
This man was so thoroughly convinced,
that he turned from his wickedness and became an honest and sober man,
to the astonishment of those that knew him before.
Thus the work of G. Fox`'s ministry went forward,
and many were thereby turned from darkness to light; and many meetings of his friends,
who had much increased in number since the year 1646, were now set up in several places.

George Fox had now come up to quite another condition than he had formerly lived in;
for he not only knew a renewing of the heart, and a restoration of the mind,
but also the virtues of created things were opened to him,
so that he began to deliberate whether he should practice medicine for the good of mankind.
But God had another service for him;
and it was showed him that he was to enter into a spiritual labor,
and also that those who continued faithful to the Lord might
attain to a state in which the sinful inclination was subdued.
Moreover, the three great professions in the world, namely, medicine, theology, and law,
were opened to him,
and he saw how the physicians were lacking the wisdom
of God by which created things were made,
and so knew not their virtues.
He saw how the lawyers generally were void of equity and justice,
and so were outside of the law of God, which went over the first transgression,
and over all sin, and was in accordance with the Spirit of God that was oppressed in man.
And he saw how the priests, for the most part, were outside of the true faith,
which Christ is the author of, and which purifies the heart,
and brings man to have access to God.
So that these physicians, lawyers, and priests, who pretended to cure the body,
to establish the property of the people, and to cure the soul,
were all without the true knowledge and wisdom that they ought to possess.
Yet he felt there was a divine power by which all might be reformed,
if they would only receive and bow unto it.

And he saw also that, though the priests did err,
yet they were not the greatest deceivers spoken of in the Scriptures;
but that the greatest deceivers were such who, like Cain, had heard the voice of God,
and who, like Korah, Dathan, and Abiram, and their company,
had come out of Egypt and through the Red Sea,
and had praised God on the banks of the sea shore; and who having come as far as Balaam,
could speak the word of the Lord, having heard His voice and known His Spirit,
so that they could see the star of Jacob, and the loveliness of Israel`'s tents,
which no enchantment could prevail against.
These who could speak so much of their divine experience,
and yet turned from the Spirit of God and went into rebellion,
these he saw would be the great deceivers, far beyond the priests.
He saw also how people generally did read the Scriptures
without having a true sense of them;
for some cried out much against Cain, Ishmael, Esau, Korah, Balaam, Judas,
etc. not regarding that the nature of these was yet alive in themselves;
thus they always applied to others that nature in which they themselves still lived.

The Lord also opened to him at this time,
that every man was enlightened by the divine light of Christ;
and he saw that those who believed in His light, came out of condemnation,
and became the children of the light; but those who hated it and did not believe in it,
were condemned by it, though they made a profession of Christ.
All this he saw in the pure openings of the light.
He also saw that God had afforded a measure of His Spirit to all men,
and that thereby they could truly come to serve the Lord and to worship Him;
and that His grace, which brings salvation,^
footnote:[Titus 2:11]
and had appeared to all men, was able to bring them into the favor of God.

And at a certain time, as he was walking in the fields,
he understood that it was said to him:
"`Your name is written in the Lamb`'s Book of Life,
which was before the foundation of the world.`"
This he took to be the voice of the Lord, and believed it to be true.
Then he felt himself powerfully moved to go abroad into the world,
which was like a briery thorny wilderness,
and he found then that the world swelled against him,
and made a noise like the great raging waves of the sea;
for when he came to proclaim the day of the Lord among the priests, professors,
magistrates, and people, they were all like a disturbed sea.
So he was sent to turn people from darkness to the light,
that they might receive Christ Jesus; for he saw,
that to as many as would receive Him in His light,
He would give power to become the sons of God.
Therefore he was to turn people to the grace of God, and to the Truth in the heart,
that by this grace they might be taught and thereby obtain salvation;
since Christ had died for all men, and was a propitiation for all,
having "`enlightened all men`"^
footnote:[John 1:9]
with His divine saving light,
and given "`the manifestation of the Spirit of God to every man to profit withal.`"^
footnote:[1 Corinthians 12:7]
Being thus sent out to preach the everlasting gospel, he did it with gladness,
and endeavored to bring people off from their own ways, to Christ,
the new and living way; and from their churches, which men had made and gathered,
to the church in God, the general assembly registered in heaven,
of which Christ is the head; and from the world`'s teachers, made by men,
to learn of Christ, who is the way, the truth, and the life; and of whom the Father said,
"`This is My beloved Son, hear Him;`" and off from the world`'s worship,
to the Spirit of God in the inward parts, that in this they might worship the Father,
who seeks such as these to worship Him.

Now he found also that the Lord forbade him to put off his hat to any man,
of whatever social class;
and that he was required to __Thee__ and __Thou__ every man and woman without distinction,^
footnote:[Editor`'s Note--Most modern English speakers are unaware that the words "`you`"
and "`your`" were originally __plural__ pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600`'s,
it became fashionable (as a means of showing honor or flattery) to use
the plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Early Friends stuck to what was then considered "`plain
language`" (using thee and thou to every single person,
and you and your to two or more),
rather than showing preferment by addressing certain individuals in the plural.]
and not to bid people "`Good Morrow`" or "`Good Evening,`"
neither could he bow or scrape with his leg to anyone.^
footnote:[The normal greetings between peers at this time
involved scraping the right foot backwards along the ground,
bowing low while removing the hat,
and then addressing one another with titles like
"`your Lordship,`" "`your Eminency,`" etc.]
This was such an unusual thing with people,
that it made many from all persuasions and professions rage against him;
but by the assistance of the Lord, he was carried over all,
and many came to be his fellow-believers and turned to God in a little time.
It is almost unspeakable what rage and fury arose, what blows, pinchings,
beatings and imprisonments these believers underwent,
besides the danger they were sometimes in of losing their lives for such little matters;
so injudicious is man in his natural state.
For it availed nothing to say that the hat-honor was an
honor from below which the Lord would lay in the dust;
that it was an honor which the proud looked for,
without seeking the honor which came from God alone;
that it was an honor invented by men in the fall,
who therefore were offended if it were not given to them;
even though Christ Himself said, "`How can you believe,
who receive honor from one another, and seek not the honor that comes from God only?`"
All these reasons found little entrance with priests, magistrates, and others;
for bitter revilings, mistreatment,
and shameful abuses quickly became the lot and share of those who (for
conscience-sake) could no longer follow the ordinary customs of the times.
For though it was alleged that the putting off of the hat was but a small thing,
which none ought to scruple;^
footnote:[The word __scruple__ appears often throughout
this history both as a noun and a verb.
It is used to speak of a feeling of doubt or hesitation with regard
to the morality or propriety of a course of action.]
yet it was an incredible thing to see what a great disturbance this pretended
small matter caused among people of all sorts of people;
for even those who desired to be looked upon as humble and meek,
soon showed what spirit they were of, when this worldly honor was denied them.
But all this served to strengthen the fellow-believers
more and more in their plain deportment,
and made them live up faithfully to the convincement of their conscience,
without respect of persons.

Meanwhile the troubles of the land continued.
We left the king in the foregoing year in the Isle of Wight, having been, in effect,
uncrowned.
Some time after this,
the Duke of York (second son to the king) being then past fourteen years of age,
fled to Holland, disguised in woman`'s apparel.
His eldest brother, the prince of Wales, who two years before had fled to France,
came now to Hellevoetsluis in Holland,
and went from there with some English men of war whose commanders were for the king,
to the Downs in England, with the intention of taking the ships coming from London.
He also made known by the spreading of a declaration, that he came to release his father.
Now there was also a negotiation begun between the king and the Parliament,
and there seemed some hopes of a settlement,
had not the army (the chief instrument in breaking down the royal power) opposed it,
by calling for justice against all those who had wronged the country, none excepted.
This broke off the treaty,
and several suspected members were removed from the Parliament,
and the king was carried to Windsor about the time called Christmas.
It was resolved from this time to send no more deputations to him,
nor to receive any from him, who now was no more called King,
but only Charles Stuart--a very strange turn of national affairs,
and a mighty evidence of their fluctuating inconstancy.
But things did not stop here, for it was concluded to bring Charles Stuart to a trial;
and the Parliament appointed General Thomas Fairfax and Oliver Cromwell,
Lieutenant General, with more than a hundred other persons, to be his judges.
These being formed into a court of justice,
the king was conducted from Windsor to St. James`'s,
and from there was brought before them in Westminster Hall,
where he was arraigned as guilty of high treason for having
levied war against the Parliament and people of England.
But he not acknowledging this court to be lawful, nor acknowledging their authority,
said, "`I am not appointed by the people; they are mine by inheritance.`"
And being unwilling to answer the charge, he was on the 27th of the month called January,
sentenced to death as a tyrant, traitor, murderer,
and a public enemy to the Commonwealth.

But before this sentence was pronounced,
the king desired that he might be permitted to make a proposition
to both Houses of Parliament in the painted Chamber,
designing (as was afterwards said) to propose his own resignation,
and the admission of his son, the prince of Wales, to the throne.
But this request was denied by the Court.
Now though the said Prince of Wales, in consideration of his father`'s danger,
had applied himself to the States-General of the United Provinces at the Hague for assistance;
and though these sent two Ambassadors to the Parliament who arrived
in London the same day that the fatal sentence was pronounced,
and were afterwards with Fairfax and Cromwell, and other commanders,
and one of them had an audience before the Parliament
to intercede with them for the king`'s life;
yet all proved in vain.
For on the 30th of the aforesaid month,
the king was brought on a scaffold erected before the banqueting house,
and his head was severed from his body.
The same day the Parliament ordered a declaration to be published,
whereby it was declared treason to endeavor to promote the prince of Wales,
Charles Stuart II., to be King of England,
or any other single person to be the chief governor thereof.
And then, after having abolished the House of Peers,
they assumed to themselves the chief government of the nation, with the title of,
The Parliament of the Commonwealth of England.

As soon as news of the king`'s death had come into Scotland, Charles, Prince of Wales,
was proclaimed the king of Great Britain at Edinburgh,
provided he should (before assuming the royal authority)
give satisfaction about some matters concerning religion.
And though this displeased the English,
yet the Scots asserted that they might very well do so,
for the English had done the same after the death of the late King`'s father,
in the year 1625.

Leaving state affairs, let us return to G. Fox, who in the year 1649,
was much exercised to declare openly against all sorts of sin.
He therefore went not only to the courts, crying for justice,
and exhorting the judges and justices to do justice,
but he warned also those that kept public houses for entertainment,
not to let people have more drink than what would do them good.
He also testified against wakes, may-games, plays, and shows,
by which people were led into vanity, and drawn out from the fear of God;
for the days which were set aside for holidays,
were usually the times when God was most dishonored.
When he came into markets, he also declared against deceitful merchandising,
and warned all to deal justly and to speak the truth;
and he testified against the con artists playing tricks on their stages.
And when occasion offered,
he warned schoolmasters and schoolmistresses to teach
their children to mind the fear of the Lord,
saying that they themselves ought to be examples and patterns of virtue to them.
But it was very burdensome to him when he heard the
bell ring to call people together to the steeple-house,
for it seemed to him just like a market bell,
to gather the people that the priest might set out his merchandise to sell.

Going once on a First-day of the week, in the morning,
with some of his friends to Nottingham, to have a meeting there;
and having seen from the top of a hill the great steeple-house of the town,
he felt it required of him to cry against that idol temple and the worshippers therein.
He said nothing of this to those that were with him,
but went on with them to the meeting, where after some time he left them,
and went away to the steeple-house.
There, the priest took for his text these words of the Apostle, 2 Pet.
1:19, "`We have also a most sure word of prophecy,
whereunto you do well that you take heed, as unto a light that shines in a dark place,
until the day dawn, and the day-star arise in your hearts.`"
And he told the people that this "`more sure word`" was the Scripture,
by which they were to try all doctrines, religions, and opinions.
G+++.+++ Fox hearing this, felt such mighty power and godly zeal working in him,
that he was made to cry out, "`O no, it is not the Scriptures, but the Holy Spirit,
by which the holy men of God gave forth the Scriptures, and whereby opinions, religions,
and judgments are to be tried.
It was this which led into all truth, and gave the knowledge thereof.
For the Jews had the Scriptures, and yet resisted the Holy Spirit, and rejected Christ,
the bright Morning Star, and persecuted both Him and His Apostles;
and though they took upon themselves to judge their doctrine by the Scriptures,
yet they erred in judgment, and did not judge them aright,
because they did it without the Holy Spirit.`"
Thus speaking, the officers came and took him away,
and put him into a nasty stinking prison.
At night he was brought before the mayor, aldermen, and sheriffs of the town,
and while examining him,
he told them that the Lord had moved him to come there into the steeple-house.
And though the mayor at first appeared peevish and fretful, yet he in time became calm.
Nevertheless, after some discourse, G. Fox was sent back to prison.
But some time after, the head sheriff John Reckless sent for him to his house,
and when G. Fox came in, the sheriff`'s wife met him in the hall,
and taking him by the hand said,
"`salvation is come to our house;`" for his speech
in the steeple-house had so amazed many,
that they could not get the sound of it out of their ears.
And not only was this woman affected, but also her husband, children,
and servants were much changed by the power of the Lord.

George Fox thus coming to lodge at this sheriff`'s house, had large meetings there,
and some persons of quality in the world came to them,
and were reached very eminently in their minds by an invisible power.
John Reckless being one of this number,
sent for the other sheriff and for a woman they traded with,
and told her in the presence of the other sheriff,
that they had wronged her in their dealings with her,
and that therefore they ought to make her restitution.
Reckless exhorted the other sheriff to do the same,
being himself made sensible that this was an indispensable duty;
for a mighty change had now wrought in him, and his understanding came to be opened.
And on the next market day, as he was walking with G. Fox in the chamber,
in his slippers, he said,
"`I must go into the market and preach repentance to the people;`"
and accordingly he went in his slippers into the market,
and into several streets, preaching repentance.
Some others in the town were also moved to speak to the mayor and magistrates,
and to the people, exhorting them to repent.
But this the magistrates could not endure; and to vent their passion on G. Fox,
they sent for him from the sheriff`'s house, and committed him to the common prison,
where he was kept till the court session came on.
He was then to have been brought before the judge,
but because the sheriff was somewhat long in fetching him,
the judge had risen before G. Fox came to the session-house.
However, the judge was a little displeased, having said,
"`I would have admonished the youth (meaning G. Fox), if he had been brought before me.`"
So he was carried back again to prison.
In the meantime, such a wonderful power broke forth among his friends,
that many were astonished at it, and even several of the priests were made tender,
and did confess to the power of the Lord.
G+++.+++ Fox having been kept prisoner a pretty long time, was at length set at liberty,
and then travelled as before in the work of the Lord.

Coming to Mansfield-Woodhouse, he found there a deranged woman under a doctor`'s care,
being bound and with her hair loose.
The doctor was attempting to bleed her but could get no blood from her,
which made G. Fox request to have her unbound; and after this was done,
he spoke to her and bade her in the name of the Lord to be quiet and still.
This proved of such an effect that she became still, and her mind coming to be settled,
she mended, and afterwards received the doctrine of truth,
and continued in it to her death.

While G. Fox was in this place,
he was moved to go to the steeple-house and declare
the truth to the priest and the people;
but while he was doing so, the people fell upon him, struck him down,
and almost smothering him, for he was cruelly beaten and bruised with their hands,
bibles, and sticks.
Then they dragged him out, though hardly able to stand, and put him in the stocks,
where he sat for some hours, while some brought horsewhips and threatened to whip him.
After some time they brought him before the magistrates, at a knight`'s house;
who seeing how cruelly he had been treated, set him at liberty, after much threatening.
But the rude multitude stoned him out of the town; and though he was scarce able to walk,
yet with much difficulty he got about a mile from the town,
where he met with some people who gave him something to comfort him,
for he was inwardly bruised.
But it pleased the Lord soon to heal him again;
and some people were convinced of the truth that
day which had been declared by him in the steeple-house,
at which he rejoiced.

Out of Nottinghamshire he went to Leicestershire, accompanied by several of his friends;
and coming to Barrow, he discoursed with some Baptists.
One of these said, "`What is not of faith is sin.`"
Fox asked him, "`What is faith, and how is it wrought in man?`"
But they, turning off from that subject, began to speak of their water-baptism;
which gave occasion for G. Fox and his friends to ask, "`Who baptized John the Baptist,
and who baptized Peter, John, and the rest of the Apostles?`"
But they were silent at those questions.
After some other discourse they parted.
On the next First-day of the week, G. Fox and those that were with him came to Bagworth,
and went to a steeple-house; and after the priest had finished,
they had some service there by speaking to the people.

Passing from there, he heard of a people that were in prison in Coventry for religion;
and as he was walking towards the jail, the word of the Lord,
(as he relates) came to him, saying, "`My love was always to you,
and you are in My love.`"
By this he was overcome with a sense of the love of God,
and was much strengthened in his inward man.
But coming into the jail, a great power of darkness struck him;
for instead of meeting such as were imprisoned for religion,
he found them to be blasphemers,
who had come to such a degree of deception that they claimed to be gods.
This wicked opinion they endeavored to maintain by Scripture,
misapplying what was said to the Apostle Peter when the sheet was let down to him,
namely:
"`What I have sanctified you should not call common or unclean;`"
also using the words of the Apostle Paul,
concerning "`God`'s reconciling all things to himself,
both things in heaven and things on earth.`"
G+++.+++ Fox was greatly grieved at this profaneness,
and told them that these Scriptures served nothing to their purpose.
And seeing they said they were gods,
he asked them if they knew whether it would rain tomorrow.
They replied saying, "`We cannot tell;`" and he told them "`God could tell.`"
He asked them also if they thought they should always be in this condition,
or if it would change.
Again they answered, "`We cannot tell.`"
G+++.+++ Fox told them that God could tell it, and He did not change.
This confounded them and brought them down for a time,
and after having reproved them for their blasphemous expressions he went away.
Not long after this, one of these ranters, whose name was John Salmon,
gave forth a book of recantation, upon which they were set at liberty.

From Coventry, G. Fox went to Atherstone, where, going into the chapel,
he declared to the priests and the people that God had come to teach His people Himself,
and to bring them off from all their man-made teachers, to hear His Son.
And though a few raged, yet they were generally pretty quiet, and some were convinced.
After this service, he went to Market-Bosworth,
and coming into the public place of worship, he found Nathaniel Stevens preaching,
who (as has been said already) was priest of the town where G. Fox was born.
Upon G. Fox taking occasion to speak, Stevens told the people that he was mad,
and that they should not hear him;
though before he had said to Colonel Purfoy concerning him,
"`There was never such a plant bred in England.`"
The people now being stirred up by this priest, fell upon G. Fox and his friends,
and stoned them out of the town.
Nevertheless this wrought on the minds of some, so that they were made loving.

G+++.+++ Fox now traveling on, came to Twy-Cross,
where he spoke to the tax officers and warned them to take heed of oppressing the poor.
There being in that town a wealthy man who had long lain sick,
and been given over by the physicians, he went to visit him in his chamber.
After having spoken some words to him, he was moved to pray by his bedside;
and the Lord was entreated, so that the sick man was restored to health.
But after G. Fox had come downstairs, and was speaking to some that were there in a room,
a servant came in with an unsheathed dagger in his hand, and threatened to stab him.
But George, looking steadfastly upon the man, said, "`Alas for you, poor creature!
What will you do with your carnal weapon?
It is no more to me than a straw.`"
The man being thus stopped, went away in a rage,
and his master hearing of it later discharged him of his service,
and was afterwards very loving to Friends; and when G. Fox came to that town again,
both he and his wife came to see him.

After this he went into Derbyshire,
where his fellow-believers were increasing in godly strength.
And coming to Chesterfield, he found one Britland to be priest there,
who having been partly convinced of the doctrine of truth,
had spoken much in behalf of it, and had seen further than the common sort of priests.
But when the priest of that town died, he got the parsonage.
G+++.+++ Fox now speaking to him and the people,
endeavored to bring them off from man`'s teaching unto God`'s teaching;
and though the priest was not able to oppose, yet they brought George before the mayor,
and threatened to send him to the house of correction.
But when it was late in the night the officers and the watchmen led him out of the town.

Concerning state affairs,
it has been said already that Charles II. was proclaimed king by the Scots;
but he being still in Holland,
they sent to him there requesting him to subscribe their Covenant,
and to abolish Episcopacy in Scotland;
it was also desired that he would put away certain lords from his service.
But those that were sent, received only an answer from the young king in general terms,
which made them return home again, where we will leave them,
to see in the meantime how it went with G. Fox,
who had been sent away (as has been said) from Chesterfield,
and came to Derby in the year 1650.

Here he stayed at the house of a doctor,
whose wife was convinced of the truth he preached.
Now it happened, that as he was walking there in his chamber, he heard the bell ring,
and asked the woman of the house what the bell rung for.
She told him there was to be a great lecture that day,
so that many of the officers of the army, and priests and preachers were to be there,
as well as a colonel who was a preacher.
Feeling himself moved to go to that congregation,
he waited until the service had finished,
and then spoke to them what he believed the Lord required of him;
and they were pretty quiet.
But there came an officer, who took him by the hand,
and said that he and the other two that were with him must go before the magistrates.
Being brought about the first hour in the afternoon before them,
they asked him why he came there; to which having answered that God had moved him to it;
and he further said, that God did not dwell in temples made with hands,
and that all their preaching, baptism, and sacrifices, would never sanctify them;
but that they ought to look unto Christ in them, and not unto men,
because it is Christ that sanctifies.
Then, seeing them run into many words,
he told them they were not to dispute of God and Christ, but to obey Him.
But this doctrine did so displease them, that they often put him in and out of the room,
and sometimes told them scoffingly that he was "`taken up in raptures.`"
At length they asked him whether he was sanctified; and he answering,
"`yes;`" they then asked if he had no sin; to which he said,
"`Christ my Savior has taken away my sin, and in Him there is no sin.`"
Then he and his friends were asked how they knew that Christ did abide in them.
G+++.+++ Fox said, "`By His Spirit, that He has given us.`"^
footnote:[1 John 3:24]
Then they temptingly asked if any of them was Christ; but he answered, "`No,
we are nothing, Christ is all.`"
At length they also asked, "`If a man steals, is it no sin?`"
To which he answered with the words of scripture, "`All unrighteousness is sin.`"
So when they had wearied themselves in examining him,
they committed him and another man to the house of correction in Derby for six months,
as "`blasphemers,`" as appears by the following court order.

[.embedded-content-document.legal]
--

[.salutation]
To the Master of the House of Correction in Derby, Greetings.

We have sent you herewith the bodies of George Fox,
of Mansfield in the county of Nottingham; and John Fretwell,
of Staniesby in the county of Derby, husbandman, brought before us this present day,
and charged with the avowed uttering and broaching of several
blasphemous opinions contrary to a late act of Parliament,
which, upon their examination before us, they have confessed.
This order is therefore to require you, immediately upon sight hereof, to receive them,
the said George Fox and John Fretwell into your custody,
and safely to keep them during the space of six months, without bail or mainprise,
or until they shall find sufficient security to be of good behavior,
or be there delivered by an order from ourselves.
Hereof you are not to fail.

[.signed-section-closing]
Given under our hands and seals this 30th day of October, 1650,

[.signed-section-signature]
Gervas Bennet, Nathaniel Barton.

--

George Fox being thus, as has been said, locked up,
the priests bestirred themselves in their pulpits
to preach the necessity of sin for term of life;
and they endeavored to persuade people that it was an erroneous doctrine
to assert a possibility of being freed from sin in this life,
as was held forth by the "`Quakers.`"
For this was the term that was now used (in a reviling
way) to refer to G. Fox and his fellow believers;
and since this name has continued from that time onward,
we cannot therefore pass by its first rise with silence.
Until this time,
those who professed the light of Christ as shining in man`'s heart and reproving for sin,
were not improperly called Professors of the Light, or Children of the Light.
But Gervas Bennet,
one of the justices of the peace who signed the aforementioned court order,
hearing that George Fox bade him and those about him to "`tremble at the Word
of the Lord,`" took hold of this weighty saying with such an airy mind,
that he took occasion to scornfully call Fox and his friends, QUAKERS.
This new and unusual appellation was adopted so eagerly,
and spread so quickly among the people, that not only the priests in that place,
but those all over England,
would use no other name to refer to the Professors of the Light.
And not stopping there,
the name quickly reached to the neighboring countries and adjacent kingdoms, insomuch,
that the said Professors of the Light,
for distinction sake from other religious societies,
have everywhere been called by that English name,
though it sounds very odd in the ears of some foreign nations,
and has also given occasion to many silly stories.

Now in those early times, among the many adherents of this persuasion,
there were some who had been previously people of a rude and dissolute life.
When these came so to be pricked to the heart,
and grew truly penitent with real sorrow for their former transgressions;
it happened that some not only burst out into tears in meetings,
but also were affected with such an unusual astonishment of mind,
that shaking in their bodies was perceived.
Some people are more naturally affected with passions of the mind than others,
for even anger does affect some men so violently that it makes them tremble;
and others will quake with fear.
And so it is no wonder if some were struck with the
terrors of God in such a way that made them tremble.
But this being seen by envious men,
they took occasion to propagate the falsehood that the Professors
of the Light performed their worship with shaking.
Yet they themselves never asserted that trembling
of the body was an essential part of their religion,
but have occasionally said the contrary;
though they did not deny themselves to be such as tremble before God;
and did not hesitate to say that all people ought to do so;
although they thereby did not seek to encourage a bodily shaking.

We have seen just now,
how one Fretwell was committed with G. Fox to the house of correction;
but this man not standing faithful in his testimony,
he obtained (by intercession of the jailer) the permission
of the justice to go see his mother,
and thus got his liberty.
Then a report was spread, that he had said that G. Fox had bewitched and deceived him.

George Fox had now become the object of many people`'s hatred; for magistrates,
priests and professors were all in a rage against him.
And the jailer, in order to find something with which to ensnare him,
would sometimes ask him silly questions, such as,
whether the door were latched or not--thinking thereby to draw from him
a sudden unadvised answer by which he might charge sin upon him.
But he was kept so watchful and circumspect, that these could take no advantage of him.
Not long after his-commitment,
he was moved to write both to the priests and magistrates of Derby.

Now since G. Croese in the beginning of his history,
represents George Fox as one altogether unfit, not only to write legibly,
but also to express his mind clearly in writing,
and that therefore he always was obliged to employ others to set down his meaning intelligibly,
it will not be beside my purpose to say that this is more than any man is able to prove.
For though it cannot be denied that he was no elegant writer, nor a good speller,
yet it is certain that his characters were tolerable, his writing was legible,
and the subject matter he treated of was very intelligible,
though his style was not like that of a skillful linguist.
And though at times he indeed employed others, because he was no quick writer,
yet generally these were young lads who would not
have dared attempt to alter his words and phrases,
nor been skillful enough to refine his style.
This I do not write from hearsay, but have seen it various times.
And whether it is true what the same author says,
that G. Fox wrote scarcely more than a rough collection of Scripture passages,
may be seen further on in this history, where the reader will find many of his writings.
The first of his letters I meet with is the following,
which he wrote to the priests of Derby, from the house of correction,
where he certainly had not the convenience of a scribe.

[.embedded-content-document.letter]
--

O Friends, I was sent unto you to tell you, that if you had received the gospel freely,
you would minister it freely without money or price;
but you make a trade and sale of what the prophets and apostles have spoken,
and so you corrupt the truth.
And you are the men that "`lead gullible women captive,`" who are "`ever learning,
and never able to come to the knowledge of the truth.`"
You have "`a form of godliness; but you deny the power.`"
Now just as Jannes and Jambres withstood Moses, so do you resist the truth;
being men of corrupt minds, reprobate concerning the faith.
But you shall proceed no further; for your folly shall be made manifest to all men,
even as theirs was.
Moreover the Lord sent me to tell you, that He does look for fruits.
You asked me, if the Scripture was my rule; but it is not your rule,
to rule your lives by; but only to talk of in words.
You are the men that live in pleasures, pride, and looseness,
in fullness of bread and abundance of idleness; see if this be not the sin of Sodom.
Lot received the angels, but Sodom was envious.
You show forth the vain nature,
and stand in the steps of those who crucified my Savior and mocked Him.
You are their children, for you show forth their fruit.
They had the chief place in the assemblies, and so do you.
They loved to be called Rabbi, and so do you.

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
That which he wrote to the magistrates who committed him to prison, was to this effect:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

I am forced, in tender love unto your souls, to write unto you,
and to beseech you to consider what you do, and what the commandments of God call for.
Does He not require justice and mercy, to break every yoke,
and to let the oppressed go free?
But who calls for justice or loves mercy, or contends for the truth?
Is not "`judgment turned backward, and does not justice stand afar off?`"
Is not "`truth silenced in the streets, and equity cannot enter?`"
And do not "`those who depart from evil, make themselves a prey?`"
O! consider what you do in time, and take heed whom you imprison.
For magistrates are set for the punishment of evil doers,
and for the praise of those who do well.
Now, I entreat you, in time, take heed what you do, for surely the Lord will come,
and will make manifest both the builders and the work.
And if it be of man, it will fail; but if it be of God, nothing will overthrow it.
Therefore I desire and pray that you would take heed, and beware what you do,
lest you be found fighters against God.

[.signed-section-signature]
G+++.+++ Fox

--

George Fox having thus cleared his conscience, continued waiting in patience,
leaving the outcome to God.
And after some time he felt himself constrained to
write to the justices that had committed him to prison,
in order to lay their deeds before them,
that so they might come to a due consideration thereof.
One of them (already mentioned) was justice Bennet, the other, named Nathaniel Barton,
was both a justice and a colonel, and also a preacher.
To these he wrote as follows:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

You did speak of the good old way, which the prophet +++[+++Jeremiah]
spoke of; but the prophets cried against the abominations which you uphold.
If you knew the power of God, you would not persecute the good way.
He that spoke of the good way was set in the stocks; the people cried,
"`Away with him to the stocks,`" for speaking the truth.
Ah, foolish people, who have eyes and see not, ears and hear not,
and are without understanding! "`Do you not fear Me? says the Lord.
Will you not tremble at My presence?`"
O your pride and abominations are odious in the eyes of God: you,
(that are preachers) have the chiefest place in the assemblies,
and are called of men "`Master;`" and such as these were, and still are,
set against my Savior and Maker.
They shut up the kingdom of heaven from men, neither do they go in themselves,
nor permit others.
Therefore you shall receive the greater damnation, who have their places,
and walk in their steps.
You may say, if you had been in the days of the prophets, or of Christ,
you would not have persecuted them; wherefore you are witnesses against yourselves,
that you are the children of them, seeing, you now persecute the way of truth.
O consider, there is a true judge,
that will give every one of you a reward according to your works.
O mind where you are,
you that hold up the abominations which the true prophets cried against!
O come down, and sit in the dust!
The Lord is coming with power; and He will throw down everyone that is exalted,
that He alone may be exalted.

--

Having thus written to them jointly, he after some time, wrote to each of them separately.
To justice Bennet he wrote thus:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You that profess God and Christ in words, consider how you follow Him.
To take off burdens, and to visit those who are in prison, to show mercy,
and clothe your own flesh,
and give your bread to the hungry--these are God`'s commandments.
To relieve the fatherless, to visit the widows in their afflictions,
and to keep yourself unspotted from the world--this is pure religion before God.
But if you profess Christ, and yet follow covetousness, greediness,
and earthly-mindedness, you deny Him in life, and deceive yourself and others,
and seek to use Him as a cloak.
Woe to you greedy men, and rich men, weep and howl for the misery that shall come.
Take heed of covetousness and extortion; God does forbid such things.
Woe to the man that covets an evil covetousness, that he may set his nest on high,
and cover himself with thick clay.
O do not love that which God forbids; for "`you are that one`'s servant whom you do obey,
whether it be of sin unto death, or of obedience unto righteousness.`"
Think upon Lazarus and the rich man; the one fared sumptuously every day,
the other was a beggar.
See, if you are not the rich man.
Be not deceived; God is not mocked with vain words.
"`Evil communication corrupts good manners.
Awake to righteousness and sin not.`"

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
And to justice Barton his words were:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You who preach Christ and the Scriptures in words,
when any comes to follow that which you have spoken of,
and to have the life of the Scriptures,
then those who speak of the Scriptures but do not lead their lives according thereunto,
persecute those who do.
Mind the prophets, and Jesus Christ, and His apostles, and all the holy men of God;
what they spoke was from the life; but they that had not the life (but only the words),
persecuted and imprisoned those that lived in the life, which they had backslidden from.

[.signed-section-signature]
G+++.+++ Fox

--

Now, though the Mayor of Derby did not sign the court order,
yet having had a hand with the rest in sending G. Fox to prison,
he also wrote to him after this manner:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You are set in place to do justice,
but in imprisoning my body you have done contrary to justice, according to your own law.
O take heed of pleasing men more than God,
for that is the way of the Scribes and Pharisees;
they sought the praise of men more than God.
Remember who said, "`I was a stranger and you did not take Me in; I was in prison,
and you did not visit Me.`" O friend, your envy is not against me,
but against the power of truth.
I had no envy to you, but love.
O take heed of oppression, "`For the day of the Lord is coming,
that shall burn as an oven; and all the proud, and all that do wickedly,
shall be as stubble; and the day that comes, shall burn them up, says the Lord of Hosts:
it shall leave them neither root nor branch.`"
O friend, if the love of God were in you, you would love the truth,
and hear the truth spoken, and not imprison unjustly.
The love of God bears, and suffers, and envies no man.
If the love of God had broken your hearts, you would show mercy;
but you show forth what rules in you.
Every tree does show forth its fruit; you show forth your fruits openly.
For drunkenness, swearing, pride, and vanity, rule among you,
from the teacher to the people.
O friend!
Mercy, true judgment, and justice are cried for in your streets.
Oppression, unmercifulness, cruelty, hatred, pride, pleasures, wantonness,
and fullness are in your streets; but the poor are not regarded.
O take heed of the woe: Woe be to the crown of pride!
Woe be to them that drink wine in bowls, while the poor are ready to perish.
O remember Lazarus and the rich man: one fared sumptuously every day,
and the other was a beggar.
O friend, consider these things, for they are near,
and see whether you are not in the rich man`'s state.

--

[.offset]
To those of the Court at Derby, he also wrote the following exhortation.

[.embedded-content-document.letter]
--

I am moved to write unto you, to take heed of oppressing the poor in your courts,
or laying burdens upon poor people which they cannot bear.
And take heed of false oaths, or making them take oaths which they cannot perform.
The Lord says, "`I will come near for judgment,
and I will be a swift witness against the sorcerers, against the false swearers,
and against the idolaters, and against those that do oppress widows and the fatherless.`"
Therefore take heed of all these things speedily.
The Lord`'s judgments are all true and righteous, and He delights in mercy.
So love mercy, dear people, and consider in time.

--

[.offset]
And to the bell-ringers of the steeple-house, called St. Peter`'s, in Derby, he wrote:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Take heed of pleasures, and prize your time now while you have it,
and do not spend it in pleasures or worldliness.
The time may come that you will say, you had time, but it is past.
Therefore look at the love of God now, while you have time;
for it brings you to loathe all vanities and worldly pleasures.
O consider, time is precious!
Fear God and rejoice in Him who has made heaven and earth.

--

While G. Fox was in prison there, several of the professors came to discourse with him,
and he perceiving that they came to plead for sin and imperfection,^
footnote:[i.e. to contend for the necessity of continuing
in sin through the entirety of this life.]
asked them whether they were believers, and had faith?
And they saying "`Yes,`" he further asked them, "`In whom?`"
To which they answered, "`In Christ.`"
He replied, "`If you are true believers in Christ, you have passed from death to life;
and if you have passed from death, then from the sin that brings death.
And if your faith is true, it will give you victory over sin and the devil,
and purify your hearts and consciences (for the true faith is held in a pure conscience),
and it will bring you to please God, and give you access to Him again.`"
But such language as this they could not endure,
for they said they could not believe that any could
be free from sin on this side the grave.
To which he answered, "`Then you might give over your talking concerning the Scriptures,
which were the words of holy men; while you yourselves plead for unholiness.`"
At another time, another company of such professors came,
and finding they also pleaded for sin, he asked them whether they had hope?
To which they answered.
"`Yes, God forbid but we should have hope!`"
Then he asked, "`What hope is it you have?
Is it Christ in you, the hope of your glory?
Does it purify you, even as He is pure?`"
But they could not abide to hear of being made pure here,
and therefore he likewise bade them to forbear talking of the Scriptures,
which were the holy men`'s words.
"`For the holy men that wrote the Scriptures,`" said he, "`pleaded for holiness of heart,
life, and conduct here; but since you plead for impurity and sin, which is of the devil,
what have you to do with these holy men`'s words?`"

Now the keeper of the prison, who was also a proud professor of religion,
was much enraged against G. Fox, and spoke wickedly of him.
But it pleased the Lord one day to strike him, so that he was under great anguish of mind.
And G. Fox walking in his chamber, heard a doleful noise, and standing still to listen,
heard him say to his wife, "`Wife, I have seen the day of judgment,
and I saw George there, and was afraid of him, because I had done him so much wrong,
and spoken so much against him to the ministers, and professors, and to the justices,
and in taverns and alehouses.`"
After this, towards the evening, the keeper came up into his chamber and said to him,
"`I have been as a lion against you, but now I come like a lamb,
and like the jailer that came to Paul and Silas trembling.`"
And he desired that he might lie in his chamber; to which G. Fox answered,
"`I am in your power, and you may do what you please.`"
But the keeper said, "`No, I wish to have your leave;
and I could desire to be always with you, but not to have you as a prisoner.`"
G+++.+++ Fox, unwilling to deny his desire, complied with it,
and allowed him to lie in his chamber.
Then the keeper told him all that was in his heart,
and said he believed what George had said of the true faith and hope to be true;
and he wondered why the other man that was put into
prison with him did not stand in the truth;
"`For,`" said he, "`that man was not right, but you are an honest man.`"
He also confessed,
that at those times when G. Fox had asked him to let him
go and speak the word of the Lord to the people,
and at his refusal had laid the weight of it upon him,
that he then found himself under great trouble,
feeling bewildered and almost distraught for some time.
The next morning the keeper went to the justices and told them
that he and his house had been plagued for G. Fox`'s sake.
To which one of the justices, that is, Bennet,
said the plagues were on them too for keeping him.
The justices now, in order to be rid of him,
gave leave that he should have liberty to walk a mile.
But George, perceiving their end,
told the jailer that if they would set down to him how far a mile was,
he would take the liberty of walking it sometimes;
for he believed they thought he would go away;
and indeed the jailer told him afterwards that this was their intent.
But he signified to him that he had no mind to get his liberty that way.
And so he remained a prisoner, and was visited by the jailer`'s sister,
who was so affected with what he spoke to her, that she coming down,
told her brother these Quakers were an innocent people, that did no hurt to any,
but good to all; and she desired that he might be treated civilly.

Now, since by reason of his restraint,
he had not the opportunity of traveling about to declare the doctrine of truth,
in order to discharge himself,
he wrote the following paper and sent it forth for the opening
of people`'s understandings in the way of truth,
directing them to the true teacher in themselves.

[.embedded-content-document.paper]
--

The Lord does show unto man his thoughts, and discovers all the secret workings in man.
A man may be brought to see his evil thoughts, and his running mind,
and vain imaginations, and may strive to keep them down, and to keep his mind in;
but he cannot overcome them, nor keep his mind turned within towards the Lord.
Now, in this state and condition,
submit to the Spirit of the Lord that shows these things,
and this will bring you to wait upon the Lord; and He that has discovered them,
will destroy them.
Therefore stand in the faith of the Lord Jesus Christ
(who is the author of the true faith) and mind Him;
for He will discover the root of lusts, and evil thoughts, and vain imaginations,
and how they are begotten, conceived, and bred; and then how they are brought forth,
and how every evil member does work.
He will discover every seed from its own nature and root.

So mind the faith of Christ, and the anointing which is in you, to be taught by it,
which will discover all that is working in you.
And as He teaches you, so obey and forsake; else you will not grow up in the faith,
nor in the life of Christ, where the love of God is received.
Now love begets love, its own nature and image; and when mercy and truth do meet,
what joy there is!
And mercy does triumph in judgment,
and love and mercy do bear the judgment of the world in patience.
That which cannot bear the world`'s judgment, is not the love of God;
for love bears all things, and is above the world`'s judgment;
for the world`'s judgment is foolishness.
And though it be the judgment and practice of the world to cast all the world`'s filthiness,
that is among themselves, upon the saints, yet their judgment is false.
Now the chaste virgins follow Christ the Lamb, who takes away the sins of the world.
But they who are of that spirit which is not chaste,
will not follow Christ the Lamb in His steps, but are disobedient to Him in His commands.
So the fleshly mind does mind the flesh, and talks fleshly, and its knowledge is fleshly,
and not spiritual; but savors of death, and not of the Spirit of life.

Now some men have the nature of swine, wallowing in the mire.
And some men have the nature of dogs, to bite both the sheep and one another.
And some men have the nature of lions, to tear, devour, and destroy.
And some men have the nature of wolves, to tear and devour the lambs and sheep of Christ.
And some men have the nature of the serpent (that old adversary), to sting,
envenom and poison.
He that has an ear to hear, let him hear, and learn these things within himself.
And some men have the natures of other beasts and creatures, minding nothing,
but earthly and visible things, and feeding without the fear of God.
Some men have the nature of a horse, to prance and vaunt in their strength,
and to be swift in doing evil.
And some men have the nature of tall sturdy oaks,
to flourish and spread in their wisdom and strength,
who are strong in the evil which must perish, and come to the fire.
Thus the evil is but one in all, but works in many ways.
And whatever outward things a man`'s or woman`'s nature is addicted to,
the evil one will suit him with that, and will please his nature and appetite,
to keep his mind in his own inventions, and in the creation, away from the Creator.

O therefore let not your mind go forth from God; for if it does, it will be stained,
and envenomed and corrupted.
And if the mind goes forth from the Lord, it is hard to bring it in again.
Therefore take heed of the enemy, and keep in the faith of Christ.
O therefore, mind that which is eternal and invisible,
and Him who is the Creator and Mover of all things;
"`for the things that are seen are not made of things that do appear;`"^
footnote:[Hebrews 11:3]
for the visible covers the invisible sight in you.
But as the Lord (who is invisible) does open you by His invisible Power and Spirit,
and brings down the carnal mind in you,
so the invisible and immortal things are brought to light in you.
O therefore, you that know the light, walk in the light!
For there are children of darkness that will talk of the light, and of the truth,
and not walk in it; but the children of the light love the light, and walk in the light.
But the children of darkness walk in darkness, and hate the light;
and in them the earthly lusts and the carnal mind choke the seed of faith,
and this brings oppression on the seed, and death spreads over them.
O therefore, mind the pure Spirit of the everlasting God,
which will teach you to use created things in their right place,
and which judges the evil.

To You, O God, be all glory and honor, who are Lord of all visibles and invisibles!
To You be all praise, who bring out of the deep unto yourself; O powerful God,
who are worthy of all glory!
For the Lord who created all, and gives life and strength to all, is over all,
and is merciful to all.
So You who have made all, and are over all, to You be all glory; in You is my strength,
refreshments, and life, my joy and my gladness, my rejoicing and glorying forevermore!
To live and walk in the Spirit of God, this is joy, and peace, and life;
but the mind that goes forth into the creation,
or into any visible things away from the Lord, this brings death.
Now when the mind has gone into the flesh, and into death, then the accuser gets within,
and the law of sin and death gets into the flesh;
and then the life suffers under the law of sin and death;
and so there is distress and failings.
For then the good is shut up, and self-righteousness is set on top,
and then man does work in the outward law, and he cannot justify himself by this law,
but is condemned by the light;
for he cannot get out of this state except by abiding in the light,
and resting in the mercy of God, and believing in Him, from whom all mercy does flow.
For there is peace in resting in the Lord Jesus.

This is the narrow way that leads to Him, the life; but few will abide in it.
Therefore keep in the innocency, and be obedient to the faith in Him.
And take heed of conforming to the world, and of reasoning with flesh and blood,
for this brings disobedience;
and then imaginations and questionings do arise to
draw away into disobedience to the truth of Christ.
But the obedience of faith destroys imaginations, and questionings, and reasonings,
and all the temptations in the flesh, and buffetings, and lookings forth,
and fetching up things that are past.
But not keeping in the life and light,
and not crossing the corrupt will by the power of God, the evil nature grows up in man;
and then burdens will come, and man will be stained with that nature.
But Esau`'s mountain shall be laid waste, and become a wilderness, where the dragons lie;
but Jacob, the second birth, shall be fruitful, and shall arise.
For Esau is hated, and must not be lord; but Jacob, the second birth,
which is perfect and plain, shall be lord; for he is beloved of God.

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
About the same time he wrote to his friends the following paper:

[.embedded-content-document.paper]
--

The Lord is King over all the earth!
Therefore all people, praise and glorify your King in true obedience, in uprightness,
and in the beauty of holiness.
O consider, that it is in the true obedience that the Lord is known,
and an understanding from Him is received.
Mark and consider in silence, in lowliness of mind,
and you will hear the Lord speak unto you in your mind.
His voice is sweet and pleasant; His sheep hear His voice,
and they will not hearken to another.
And when they hear His voice, they rejoice and are obedient and also sing for joy.
O, their hearts are filled with everlasting triumph!
They sing and praise the eternal God in Zion,
and no man shall ever take their joy from them.
Glory be to the Lord God forevermore!

--

And since many who had been convinced of the truth,
turned aside because of the persecution that arose,
he wrote the following lines for the encouragement of the faithful:

[.embedded-content-document.epistle]
--

Come you blessed of the Lord, and rejoice together; keep in unity and oneness of spirit.
Triumph above the world; be joyful in the Lord, reigning above the world,
and above all things that draw away from the Lord; that in clearness, righteousness,
pureness, and joy you may be preserved to the Lord.
O hear, O hearken to the call of the Lord, and come out of the world,
and keep out of it forevermore!
And come, sing together you righteous ones, the song of the Lord, the song of the Lamb,
which none can learn but they who are redeemed from the earth and from the world.

--

Now while G. Fox was at Derby in the house of correction, his relations came to see him,
and being sorry for his imprisonment,
they went to the justices (by whose order he had
been put there) and desired that he might be released,
offering to be bound for one hundred pounds, and others in Derby for fifty pounds apiece,
on condition that he should no more come there to declare against the priests.
But being brought before the justices,
he would not consent that any should be bound for him,
because he believed himself to be innocent from any ill behavior.
Then justice Bennet rose up in a rage,
and as G. Fox was kneeling down to pray to the Lord to forgive him,
Bennet ran upon him and struck him with both his hands, crying, "`Away with him, jailer;
take him away, jailer!`"
Whereupon he was carried back again to prison,
and kept there until the time of his commitment for six months had expired.
But now he had liberty of walking a mile, which he made use of in his own freedom.
And sometimes he went into the market and streets, and warned the people to repent.
And on First-days he now and then visited the prisoners in their religious meetings.
But the justices then requiring sureties for his good behavior,
it came upon him to write to them again, as follows:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Consider what it is in you that does imprison; and consider who is head in you,
and see if something in you does not accuse you?
Consider, you must be brought to judgment.
Think upon Lazarus and the rich man; the one fared sumptuously every day,
the other was a beggar; and seeing you now have time, prize it, while you have it.
Would you have me be bound for my good behavior?
I am already bound to good behavior, and do cry out for good behavior from all people,
to turn from vanities, pleasures, oppression, and from all the deceits of this world;
and there will come a time that you shall know it.
Therefore take heed of pleasures, and deceits, and pride.
Look not at man, but at the Lord; for He says, "`Look unto Me, all you ends of the earth,
and be saved.`"

--

[.offset]
Not long after he wrote to them again, saying:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Would you have me be bound for my good behavior, from drunkenness, swearing, fighting,
adultery, and the like?
The Lord has redeemed me from all these things,
and the love of God has brought me to loathe all looseness and vanity,
blessed be His name.
Those who are drunkards, and fighters, and swearers, have their liberty without bonds;
and you lay your law upon me, whom neither you, nor any other,
can justly accuse of these things, praised be the Lord!
I can look to no man for my liberty, but to the Lord alone;
who has all men`'s hearts in His hand.

--

[.offset]
And after some time, not finding his spirit clear of them, he wrote again, as follows:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Had you known who sent me to you, you would have received me;
for the Lord sent me to you to warn you of the woes that are coming upon you,
and to bid you to look to the Lord, and not to man.
But when I had told you my experience, what the Lord had done for me,
then your hearts were hardened,
and you sent me to prison where you have kept me many weeks.
If the love of God had broken your hearts, then you would see what you have done.
But you would not have imprisoned me had not my Father permitted you;
and by His power I shall be loosed, for He opens and shuts, to Him be all glory!
In what way have I misbehaved myself, that any should be bound for me?
Neither the promises of men, nor their bonds, will do any good to keep my heart,
if I do not have a guide within to keep me in the upright life to God.
But I believe in the Lord,
that through His strength and power I shall be preserved
from ungodliness and worldly lusts.
The Scripture says to receive strangers, but you imprison them.
As you are in authority, take heed of oppression and oaths,
and injustice and gifts or rewards, for God does loathe such things.
But love mercy and true judgment and justice, for in these the Lord delights.
I do not write with hatred to you, but to keep my conscience clear.
Take heed how you spend your time.

--

[.offset]
To the priests of Derby he also wrote again in this manner:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

You profess to be the ministers of Jesus Christ in words,
but by your fruits you show forth what your ministry is.
Every tree shows forth its fruit; the ministry of Jesus Christ is in mercy and love,
to unloose those who are bound, to bring out of bondage,
and to let those who are captivated go free.
Now friends, if the Scriptures are your rule,
where is your example to imprison for religion?
Do you have any command for it from Christ?
If that life which you profess were in you,
you would walk in the footsteps of those who spoke forth the words of Scripture.
But he is not a Jew, who is one outwardly, whose praise is from men; but he is a Jew,
who is one inwardly, whose praise is from God.
But if you build upon the prophets and apostles in words, and pervert their life,
then remember the woes which Jesus Christ spoke against such.
They that spoke the prophets`' words, but denied Christ, they professed a Christ to come;
but had they truly known Him they would not have crucified Him.
The saints who were changed by the love of God,
were brought by it to walk in love and mercy; for "`he that dwells in love,
dwells in God.`"
But where envy, pride, and hatred rules, the nature of the world still rules,
and not the nature of Jesus Christ.
I write with no hatred to you, but only that you may weigh yourselves,
and see how you pass your time.

--

Having thus cleared his conscience to the priests,
it was not long before a concern came upon him to write again to the justices,
which he did as follows:

[.embedded-content-document.letter]
--

I am moved to warn you to take heed of giving way to your own wills.
Love the cross, and do not satisfy your minds in the flesh,
but prize your time while you have it.
Walk according to what you know, in obedience to God,
and then you shall not be condemned for what you do not know,
but only for what you know and do not obey.
Consider in time, and weigh yourselves, and see where you are, and whom you serve.
For if you blaspheme God, and take His name in vain; if you swear and lie;
if you give way to envy, hatred, covetousness, greediness, pleasures, fleshly freedom,
or any other vices, be assured then that you do serve the devil.
But if you fear the Lord, and serve Him, you will loathe all these things.
He that loves God will not blaspheme His name;
but where God is opposed and the devil is served, such a profession is sad and miserable.
O prize your time, and do not love that which God forbids: lying, wrath, malice, envy,
hatred, greediness, covetousness, oppression, gluttony, drunkenness, whoredom,
and all unrighteousness.
So consider, and be not deceived, "`evil communication corrupts good manners.`"
Be not deceived, God will not be mocked with vain words,
for "`the wrath of God is revealed from heaven against all ungodliness.`"
Therefore obey that which does convince you of all evil,
and tells you that you should do no evil.
This will lead to repentance, and keep you in the fear of the Lord.
O look at the mercies of God, and prize them, and do not turn them into licentiousness!
O turn your eye to the Lord, and not to earthly things!

--

Besides this, he wrote the following letter to Nathaniel Barton,
who (as was hinted before) was both a justice and a preacher.

[.embedded-content-document.letter]
--

[.salutation]
Friend,

Do not cloak and cover yourself.
There is a God who knows your heart, and will uncover you; indeed He sees your way.
"`Woe to him that covers, and not with My Spirit, says the Lord.`"^
footnote:[Isaiah 30:1 KJV]
Do you act contrary to the law, and then put it from you?
Mercy and true judgment you neglect, but look what was spoken against such.
My Savior said, "`I was sick and in prison, and you did not visit Me;
I was hungry and you did not feed Me; I was a stranger and you did not take Me in.`"
And when they said, "`When did we see You in prison and did not come to You,`" etc.
He replied, "`Inasmuch as you did not do it for one of these little ones,
you did not do it for Me.`" Friend,
you have imprisoned me for bearing witness to the life and power of truth,
and yet you profess to be a minister of Christ.
But if Christ had sent you, you would bring out of prison, and out of bondage,
and would receive strangers.
You have been careless upon the earth;
you have lived plenteously and nourished your heart as in a day of slaughter.
"`You have killed the just one.`"^
footnote:[James 5:6]
O look where you are, and how you have spent your time!
O remember yourself, and now while you have time, prize it,
and do not slight the free mercy of God, and despise the long-suffering of God,
which is unto salvation.
But mind that in you which convinces you of sin, and would not let you swear, nor lie,
nor take God`'s name in vain.
You know you should do none of these things,
though you have learned to do that which will condemn you.
Therefore obey the light, which does convince you of evil, and forsake your sins,
and look to the mercies of God and prize His love in sparing you till now.
The Lord says, "`Look unto Me all you ends of the earth, and be saved;`" and,
"`Cease from man, whose breath is in his nostrils.`"
And friend, prize your time, and consider whom you serve;
for "`You are that one`'s slave whom you obey, whether of sin unto death,
or obedience unto righteousness.`"
If you serve God and fear Him, you will not blaspheme His name, nor curse, swear,
or take His name in vain; nor follow after pleasures, fleshly liberties, whoredom,
drunkenness, wrath, malice, revenge, rashness, conceit, pride, gluttony, greediness,
oppression, covetousness, or foolish jesting and vain songs;
for indeed God does forbid these things, along with all unrighteousness.
If you profess faith in God, and yet act any of these things, you take Him for a cloak,
and serve the devil.
Consider within yourself, and do not love that which God does hate.
He that loves God, keeps His commandments.
The devil will tell you it is a hard thing to keep God`'s commandments;
but it is an easy thing to keep the devil`'s commandments,
and to live in all unrighteousness and ungodliness,
turning the grace of God into licentiousness.
"`But let the unrighteous man forsake his ways, and turn unto Me,`" says the Lord,
"`and I will have mercy.
Turn, why should you die?`"
says the Lord.
Howl you great ones, for plagues are pouring out upon you!
Howl you oppressors,
for recompense and vengeance is coming upon you! "`Woe unto
them that covetously join one house to another,
and bring one field so nigh unto another, that the poor can get no more ground,
and that you may dwell upon the earth alone.`"^
footnote:[Isaiah 5:8]
These things have come to the ears of the Lord of Hosts.

--

It has been said already,
that G. Fox and some of his friends were sometimes moved to preach the doctrine of truth.
And in this year it also happened that Elizabeth Hooton (of whom mention has been made),
from a true experience of the Lord`'s work in herself,
also felt moved publicly to preach the way of salvation to others,
being the first woman preacher (by what I am informed) among
those who were now generally called by the name of Quakers.
Yet I have found in a Dutch book, printed at Dordt in the year 1647,
and called, [.book-title]#History of the Troubles in England#,
that among the various other religious persuasions at London,
there were also women that did preach in large meetings,
who were heard by many with great satisfaction;
so that the preaching of a woman was not such a novelty as otherwise it might have been.

In the foregoing year, it is said that some Scotch Commissioners,
having been with Charles II. in Holland, returned to Scotland;
and though the king at first seemed reluctant to consent to the Presbyterian Covenant,
yet seeing no other way open to the Scottish throne, he came to another mind.
Going then over to Scotland,
he made his entry into Edinburgh through the gate on which were placed the quarters^
footnote:[James Graham, the Earl of Montrose was hanged, beheaded, and quartered,
and his body parts nailed to the gate of Dundee.]
of the Earl of Montrose, who having endeavored not long before to subdue the Scots,
had been beaten with his forces, taken prisoner, and executed.
The young King having now come into Scotland,
seemed willing to comply as much as possible in order to ingratiate himself,
not only with the Scots, but also with the English, if possible.
And for this purpose he gave forth the following declaration at his Court at Dumfermling,
dated the 16th day of August, 1650, and in the second year of his reign:

[.embedded-content-document.address]
--

Though his Majesty, as a dutiful son, is obliged to honor the memory of his royal father,
and have in estimation the person of his mother,
yet he does desire to be deeply humbled and afflicted in spirit
before God because of his father`'s hearkening to evil counsels,
and his opposition to the Work of Reformation,
and to the Solemn League and Covenant (by which so much of the
blood of the Lord`'s people has been shed in these kingdoms),
and also for the idolatry of his mother.

--

Here the king confessed openly that his father`'s house was guilty of great crimes,
and plainly signified that the nation indeed had been wronged by his father`'s behavior;
and he seemed to promise amendment if he came to be restored.
In the meantime,
seeing in England that the Scots were likely to make headway against them,
the Parliament therefore gave orders for General Fairfax to go there with an army.
But Fairfax showed himself unwilling to go,
chiefly (as was believed) because the advice of his wife,
who hearkened to the counsel of the Presbyterian preachers--these
thinking it would contribute to their own settlement,
if those of their own persuasion in Scotland were not resisted.
But the Parliament, many of whose members were Independents, were not deterred,
but rather resolved, seeing Fairfax resigned voluntarily,
to set up Oliver Cromwell as general of the national forces in his place.
And this being done, Cromwell was sent with an army to Scotland,
and defeated the Scots not far from Edinburgh,
whereby that city not long after surrendered to him.

In this year was born in Holland, on the 14th of the month called November,
William the Third, Prince of Orange,
whose mother was daughter of the late King Charles the First.
And this prince, by a strange revolution of human affairs,
has since been advanced to the English throne; and is at present, while I write this,
King of Great Britain.
