== Chapter II

[.section-date]
1650--1652

The year 1651 had scarcely begun when the Scots resolved,
notwithstanding their overthrow, to crown their new King,
which (after he had sworn to maintain the Covenant)
they did in the beginning of the month called January.
But leaving this for now, we return again to George Fox, whom we left at Derby,
in the house of correction.
It was about this time that a trooper came to him and said that,
having been in the steeple-house listening to the priest,
an exceedingly great trouble came upon him, and then a voice,
(which he took to be that of the Lord) said to him,
"`Do you not know that my servant is in prison?
Go to him for direction.`"
G+++.+++ Fox speaking to his condition, told him,
"`That which shows you your sins and troubles you for them,
will also show you your salvation; because He that shows a man his sin,
is the same that takes it away.`"
While he was thus speaking,
the trooper`'s understanding began to be opened concerning the truth,
and he was sensible of God`'s mercies,
which made him speak boldly in his quarters among the soldiers and others,
demonstrating from the Scriptures what he believed to be the truth.
He also said that his colonel (which I take to be Barton) was as blind as Nebuchadnezzar,
for casting the servant of the Lord into prison.
This greatly incensed his colonel;
and when the two armies lay near one another at the battle of Worcester,
and two from the king`'s army challenged any two
of the Parliament`'s army to fight with them,
the said colonel chose this soldier and another to answer the challenge.
And though his companion was slain in the encounter,
he succeeded in driving both his enemies within a musket-shot of the town,
without ever firing a pistol at them; thus he returned victorious.
But having seen the deceitfulness of the officers,
and how wonderfully the Lord had preserved him (and in process of time
also becoming sensible that fighting was unlawful for a true Christian),
he laid down his arms, and so began to fight under the banner of the Prince of Peace,
by entering into the spiritual warfare.

Now the time of G. Fox`'s commitment to the house of correction being very nearly over,
and there being many new soldiers raised up,
the commissioners desired to make Fox captain over them,
and the soldiers cried that they would have none but him.
So the keeper of the house of correction was commanded to bring
him up before the commissioners and soldiers in the market place;
and there they offered him that preferment (as they called it),
asking him if he would take up arms for the Commonwealth against Charles Stuart.
G+++.+++ Fox,
never having been a fighter (though it has appeared he was
bold and valiant) told them he could not do so,
for he well knew from where all wars arise (namely, from the lusts of men,
according to the doctrine of the apostle James),
and that he lived in the virtue of that life and
power which took away the occasion of all wars.
The commissioners, in order to fawn upon him,
said they had offered him the office in love and kindness, because of his virtue.
But he not minding those flattering words, replied, "`If this is your love and kindness,
I trample it under my feet.`"
This bold answer quickly showed how shallow their pretended kindness was;
for it so enraged them, that they said, "`Take him away, jailer,
and put him into the dungeon among the rogues and felons.`"
Thus G. Fox was put into a louse-infested, stinking place among thirty felons,
where he had no bed, and was kept almost another half a year,
except at times when he was allowed to walk in the garden (for they believed
of him that he would not run away.) Being in this nasty prison,
it was said among the people that he would never come out.
But, trusting in God, he believed the contrary,
it having been shown him from the Lord (according to what he relates) that he was not
yet to be removed from that place because there was a service for him to do.

In the meantime, it was noised abroad that he was in Derby dungeon,
and his relations came again to see him, they being much troubled about it;
for they thought it a matter of great shame to them that he should thus lie in jail.
Besides, it was a strange thing at this time to be imprisoned for religion.
Some judged him to be mad, because he maintained the possibility of purity,
righteousness, and perfection in this life.
Among others that came to see him, there was also a soldier from Nottingham,
who said to him, "`Your faith stands in a man that died at Jerusalem;
and there was never any such thing.`"
This so grieved G. Fox, that he said to him, "`What!
Did not Christ suffer outside the gates of Jerusalem by the professing Jews,
the chief priests, and Pilate?`"
"`No,`" said the soldier, "`he did not suffer there outwardly.`"
Then G. Fox asked him whether there were not Jews, chief priests, and Pilate outwardly?
This puzzled the soldier a little, so that he could not deny it.
Then George told him, "`As certainly as there was a chief priest, and Jews, and Pilate,
so certainly did Christ suffer there outwardly under them.`"
Yet this imprudent person insisted that none of the prophets or
apostles or holy men of God ever suffered anything outwardly;
but that all their sufferings were inward.
Then G. Fox instanced many of the lives of the prophets and apostles,
how they had suffered, and by whom they suffered,
thereby confounding his silly imaginations.
Yet such was the malice of some at this time,
that a slander was then raised among the people,
that the Quakers denied the Christ who suffered and died at Jerusalem.
This, indeed, is a remarkable evidence of the credulity of some people,
believing upon trust any story (however false) when it relates
to those that have become the object of odium.

In the time of his imprisonment,
he was much afflicted in mind about the proceedings of the magistrates,
because men were being put to death for stealing cattle, money, etc.
And he was the more troubled because such practices were
even contrary to the law of God in the old covenant.
He therefore wrote the following letter to the judges:

[.embedded-content-document.letter]
--

I am moved to write unto you to take heed of putting
men to death for stealing cattle or money,
etc.; for the thieves under the law were to make restitution;
and if they had not the means, they were to be sold for value of their theft.
Mind the laws of God in the Scriptures, and the Spirit that gave them forth;
and let these be your rule in executing judgment.
Show mercy, that you may receive mercy from God, the Judge of all.
And take heed of receiving gifts and rewards, and of every form of pride;
for God forbids such things, and they blind the eyes of the wise.
I do not write in order to give liberty to sin; God has forbidden it.
But I write that you should judge according to His laws, and also show mercy;
for He delights in true judgment and in mercy.
I beseech you to mind these things, and to prize your time now that you have it;
and fear God and serve Him, for He is a consuming fire.

--

While G. Fox was in prison among the felons, it grieved him to hear their foul language,
and he often reproved them for their wicked words and evil behavior towards each other.
Indeed,
many were amazed that he was so preserved among this
bad company without being defiled by their conduct.
But the fear of God so prevailed in his heart,
that he could not be charged with any evil word or action all the time he was there.
Yet seeing that it was dangerous to converse with such a naughty crew,
he therefore laid before the judges what a hurtful
thing it was for prisoners to lie so long in a jail,
because they learned wickedness from one another by talking freely of their evil deeds;
and that therefore speedy justice ought to be done.

Now while he was confined here,
there was a young woman in the jail for robbing her master of some money;
and finding that she was to be tried for her life,
he wrote concerning her to the judge and jury,
showing them how contrary it was to the law of God to put people to death for stealing;
and that it was an incumbent duty to show mercy.
But notwithstanding his writing so, she was condemned to die,
and a grave was prepared for her.
Having heard this, G. Fox wrote a few words to the people, containing:
"`A warning for all people to beware of covetousness, and to fear the Lord,
and prize their time, while they have it; that so they might avoid wickedness.`"
And when the woman was carried forth to execution at the time appointed,
he gave this writing to be read at the gallows.
And when she was already upon the ladder, with a cloth over her face,
and ready to be turned off, she was reprieved, and was brought back again to prison,
where she afterwards came to be convinced of the
truth as held forth by G. Fox and his friends.

In the jail there was also detained a wicked man, who was said to be a conjurer.
This man threatened G. Fox, and also the jailer,
that he would raise the devil and break down the house;
so that he made the jailer afraid.
But G. Fox went to him and said, "`Come, let us see what you can do.
Do your worst.
The devil is raised high enough in you already, but the power of God chains him down.`"
At this undaunted speech the fellow slunk away.

Now in order to get rid of G. Fox, the justices resolved to make him a soldier;
and seeing he would not voluntarily accept a command,
Bennet sent constables to offer him pay in advance.
But George told him that he had been brought off from outward war, and was dead to it.
And though the commissioners over and again offered him money, yet he would not take it.
At this they grew so angry, that he was committed close prisoner.^
footnote:[Depending upon the severity of the crime (or other extenuating considerations)
prisoners were often afforded certain liberties during the time of their imprisonment.
Some were allowed to continue in their trades, to visit their families,
or to walk to nearby towns to buy necessities.
"`Close prisoners`" were stripped of all such freedoms,
and were generally confined to a cell at all times.]
Hereupon G. Fox wrote to the justices, and those that were concerned in his commitment,
the following lines:

[.embedded-content-document.letter]
--

You who are without Christ, and yet use the words which He and His saints have spoken,
consider how neither He nor His apostles did ever imprison anyone.
My Savior is merciful even to the unmerciful and rebellious,
and brings out of prison and bondage.
But men, while the carnal mind does rule, oppress and imprison.
My Savior says "`Love your enemies, and do good to those that hate you,
and pray for those that despitefully use you and persecute you.`"
For the love of God does not persecute any, but rather loves all, wherever it dwells.
"`He that hates his brother,`" is a murderer.
Now, you profess to be Christians, and one of you a minister of Jesus Christ,
yet you have imprisoned me who am a servant of Jesus Christ.
The apostles never imprisoned any; but were imprisoned themselves.
Take heed of speaking of Christ in words, and denying Him in life and power.
O friends, the imprisoning of my body is to satisfy your wills;
but take heed of giving way to your wills, for this will hurt you.
If the love of God had broken your hearts, you would not have imprisoned me;
but still my love is to you, as to all my fellow creatures.
This has been written so that you may weigh yourselves, and see how you stand.

--

About this time he gave forth the following paper
to those that had been convinced of the truth,
to show them the deceit of the world, and how the priests had deceived the people:

[.embedded-content-document.paper]
--

Christ was ever hated; and the righteous were hated for His sake.
Consider who they were that did ever hate them.
"`He that was born after the flesh, did persecute him that was born after the Spirit;
and so it is now.`"
And consider who were the chief opponents of Christ.
Were they not the great and learned men, the heads of the people,
the rulers and teachers that professed the law and the prophets,
and said they looked for the Christ.
Indeed they looked for an outwardly glorious Christ to hold up their outward glory,
but Christ spoke against the works of the world,
and against the priests and scribes and Pharisees and their hypocritical profession.
He that is a stranger to Christ is a hireling;
but the servants of Jesus Christ are freemen.
The false teachers always laid burdens upon the people;
and the true servants of the Lord did speak against them.
Jeremiah spoke against hirelings, saying,
"`It was a horrible thing,`" and "`What will you do in the end?`"
For the people and priests were given to covetousness.
Paul spoke against those who sought their own gain from the people,
and exhorted the saints to turn away from covetous and proud men,
who loved pleasures more than God, who "`had a form of godliness but denied the power.`"
"`For of this sort,
(said he) are those who creep into households and make captives of gullible women,
who are ever learning, but never able to come to the knowledge of the truth;
men of corrupt minds, reprobate concerning the faith;
and as Jannes and Jambres withstood Moses, so, (says he) do these also resist the truth;
but they shall proceed no further, for their folly shall be made manifest unto all men.`"
Moses forsook honors and pleasures, which he might have enjoyed.
The apostle in his time saw this corruption entering
(which now has spread over the world),
of having a form of godliness, but denying the power.
Ask any of your teachers, whether you may ever overcome your corruptions and sins?
None of them believes it; but as long as man is here (they say),
he must carry about with him the body of sin.
Thus pride is kept up, and all unrighteousness,
and that honor and authority which Christ denied,
though there are multitudes of teachers, heaps of teachers,
and a golden cup full of abominations!
Paul did not preach for wages,
but labored with his hands that he might be an example to all that follow him.
O people, consider who it is that follow Paul!
There are now many, as the apostle said,
who "`intrude into those things which they have never seen,
being vainly puffed up with a fleshly mind;`" and,
as the Scriptures declare of some of old, "`They go in the way of Cain,
(who was a murderer) and in the way of Balaam,
who coveted the wages of unrighteousness.`"
The prophet Micah also cried against those judges who judged for reward,
and the priests who taught for hire,
and the prophets that prophesied for money and yet leaned on the Lord, saying,
"`Is not the Lord among us?`"

--

[.offset]
He also wrote a serious exhortation to the magistrates of Derby,
to consider whom they imprisoned.

[.embedded-content-document.letter]
--

[.salutation]
Friends,

I desire you to consider in time,
that the magistrates are appointed for the punishment of evil-doers,
and for the praise of those that do well.
But when the Lord sends His messengers unto you,
to warn you of the woes that will come upon you (unless you repent),
then you persecute them, and put them into prison, and say, "`We have a law,
and by our law we may do it.`"
You indeed justify yourselves before men, but God knows your hearts.
He will not be worshipped with your outward forms and professions, and shows of religion.
Therefore consider, you who talk of God, whether you are subject to Him;
for they are His children that do His will.
"`What does the Lord require of you, but to do justice, to love and show mercy,
to walk humbly with Him;`" and to help the widows and fatherless,
but instead of this you oppress the poor.
Do not your judges judge for rewards, and your priests teach for hire?
The time is coming, when He who sees all things will uncover all your secrets.

I desire you to consider these things, and search the Scriptures,
and see whether any of the people of God did ever imprison another for religion,
though they themselves were imprisoned.
And I desire you to consider how it is written that when the church has met together,
they may "`all prophesy, one by one;`" that all may hear, and all may learn,
and all be comforted.
And then, "`If anything be revealed to him that sits by, let the first hold his peace.`"
Thus it was in the true church; and thus it ought to be.
But it is not so in your assemblies now, for he that teaches for hire may speak,
and none may contradict him.
Also, consider the liberty that was given to the apostles (even among the unbelieving Jews),
when after the reading the law and the prophets,
the rulers of the synagogue said unto them, "`You men and brethren,
if you have any word of exhortation for the people, you may say it.`"
I desire you to consider this in stillness, and strive not against the Lord,
for He is stronger than you.
O friends, lay these things to heart, and let them not seem light things to you.
I wrote unto you in love, to mind the laws of God, and your own souls,
and to do as the holy men of God did.

--

During his imprisonment there,
he found himself under a great exercise and travail of spirit,
because of the wickedness of that town;
for though some had been convinced of the doctrine of truth,
yet generally they were a hardened people.
And seeing the visitation of God`'s love pass away from them, he mourned,
and wrote the following lamentation.

[.embedded-content-document.epistle]
--

O Derby!
As the waters run away when the flood gates rise up,
so does the visitation of God`'s love pass away from you.
Therefore look where you are, O Derby; see how you are grounded, and consider,
before you are utterly forsaken.
The Lord moved me twice to come and cry against the deceit and vanity that are in you;
and to warn all to look to the Lord, and not to man.
The woe is against the crown of pride, and against drunkenness and vain pleasures,
and against those who make a profession of religion
in words but are high and lofty in mind,
and live in oppression and envy.
O Derby!
Your profession and preaching stinks before the Lord.
You profess a Sabbath in words, and meet together,
dressing yourselves in fine apparel and upholding your pride.
Your women "`walk with stretched forth necks, and shameless eyes`" etc.,
which the prophet of old cried against.
Your assemblies are odious and an abomination to the Lord; for pride is set up,
and bowed down to, and covetousness abounds.
He who acts wickedly is honored, so that the deceit in one permits the deceit in another;
and yet you profess Christ in words.
O, it does even break my heart to see how God is dishonored in you, O Derby!

--

After he had written this,
he perceived that his imprisonment there would not continue long;
for the magistrates grew uneasy about him, and could not agree what to do with him.
Some would have sent him up to the Parliament,
and others were for banishing him to Ireland.
At first they called him a deceiver and a blasphemer; and afterwards,
when the judgments of God befell them, they said he was an honest and virtuous man.
But their speaking well or ill was nothing to him; for the one did not lift him up,
nor did the other cast him down.
At length they turned him out of jail, about the beginning of the winter,
in the year 1651,
after he had been prisoner in Derby about a year--six months in the house of correction,
and the rest of the time in the common jail and dungeon.

Being set at liberty, he went into Leicestershire, and had meetings as he went,
preaching so effectually that several were convinced.
Afterwards he went to Nottinghamshire again, and from there into Derbyshire,
where having visited his friends, he passed into Yorkshire,
and coming into Doncaster and other places, he preached repentance.
After this he came to Balby,
where Richard Farnsworth and several others were convinced by his preaching.
And coming afterwards into the parts near Wakefield,
James Nayler and William Dewsbury came to him and also acknowledged
the truth of the doctrine he held forth;
and these three men in time also became ministers of the gospel.
But by the way,
I must say that William Dewsbury was one of those
who had already been directly convinced of the truth,
as G. Fox himself was, and afterwards coming to him, found himself in unity with him.
Another of these was George Fox the younger, of whom more more will be said hereafter.^
footnote:[George Fox the younger became a well-known minister among the early Quakers.
He was not related to George Fox, and was in fact older, but came to be called
"`the younger`" to distinguish him from his more prominent friend, whom he regarded
as older in the Truth. --FLP]

But I return to the other G. Fox, who coming about Selby, passed from there to Beverly,
where he went into the steeple-house, and after he that preached there had finished,
George Fox spoke to the congregation, saying,
"`They ought to turn to Christ Jesus as their teacher.`"
This struck a dread among the people, and the mayor spoke to him;
but none meddled with him.
In the afternoon he went to another steeple-house, about two miles off, where,
after the priest had finished, he spoke to him and the people,
showing them the way of life and truth, and the true ground of election and reprobation.
The priest saying he could not dispute, G. Fox told him he did not come to dispute,
but to hold forth the word of truth,
that they might all know the one Seed to which the promise was,
both in male and in female.
Here his speaking did so please the auditory,
that he was asked to come again on another day, and to preach there.
But he directed them to their teacher Christ Jesus, and so went away.

The next day he came to Crantsick, to Captain Pursloe`'s,
who accompanied him to Justice Hotham`'s, and entering into discourse with G. Fox,
told him he had known this principle of light and life above ten years,
and was glad that the Lord did publish it abroad among the people.
While G. Fox was there,
a great woman of Beverly came to speak with the said justice about some business,
who in discourse said that the last sabbath-day (as she called
it) there was an angel or spirit that came into the church at Beverly,
and spoke the wonderful things of God, to the astonishment of all that were there.
And that when it had finished, it passed away, they not knowing from where it came,
or where it went.
But it astonished all, both priest and professors, and the magistrates of the town.
This relation was afterwards conveyed by justice Hotham,
and G. Fox told him that it was he who had been that day at Beverly steeple-house,
and had declared the truth there.

The next First-day of the week captain Pursloe came to G. Fox,
and they both went to the steeple-house,
where G. Fox (when the priest had finished) spoke to both priest and people,
and directed them to where they might find their teacher, the Lord Jesus Christ--that is,
inwardly, in their hearts.
His preaching was of such effect,
that some received the doctrine of truth and continued in it.
In the afternoon he went to another steeple-house about three miles off,
where one preached who bore the title of doctor.
He took his text from Isaiah 55, "`Everyone that thirsts, come to the waters,
and he that has no money, come, buy and eat, yes come, buy wine and milk, without money,
and without price.`"
G+++.+++ Fox stayed till the priest had finished, and well knowing what kind of teacher he was,
he was kindled with such a zeal that he said, "`Come down you deceiver!
Do you bid people to come freely, and to take of the water of life freely,
and yet you take three hundred pounds a year from them!
Should you not blush with shame?
Did the prophet Isaiah and Christ do so, who spoke these words,
and gave them forth freely?
Did not Christ say to His ministers, whom He sent to preach, '`Freely you have received,
freely give?`'`" The priest being amazed, hastened away,
and so gave G. Fox as much time as he could desire to speak to the people;
who then directed them to the light and grace of God,
and to the Spirit of God in their inward parts, to be taught and instructed by Him.
Having thus cleared himself among the people,
he returned to justice Hotham`'s house that night, who embracing him, said,
"`My house is your house;`" and also signified that
he was exceedingly glad at the work of the Lord,
and that His power was revealed.

From there G. Fox passed through the country and came at night to an inn,
where he asked the woman of the house if she had any food.
But because he said "`thee`" and "`thou`" to her, she looked strangely upon him.
Then he asked her if she had any milk, and she said,
"`No.`" But believing she spoke falsely, and seeing a butter churn standing in the room,
he thought try her further, and asked if she had any cream;
but she denied that she had any.
Then a little boy playing by the butter churn, put his hands into it,
and pulling it down, threw all the cream on the floor.
Thus the woman appeared to be a liar, and being amazed,
she took up the child and whipped it sorely.
But George reproved her for her lying, and going out of the house, went away,
and lay that night in a stack of hay in rain and snow.
The next day he came to York, and on the first day of the week he went to the cathedral.
When the priest had finished,
he said he had something from the Lord God to speak to the priest and people.
"`Then,`" said one of the professors, "`Speak quickly;`" for it was very cold weather.
G+++.+++ Fox then told them, "`This is the word of the Lord God unto you:
that you live in words, but God Almighty looks for fruits among you.`"
As soon as these words were out of his mouth,
he was hurried out and thrown down the steps.
But he got up again without hurt, and went to his lodging.
Yet several of the people were so reached, that they became convinced of the truth.

Having now finished his service in York,
he went from there and came the next day to Burraby, and going into a certain meeting,
where there was a priest also, had occasion to declare the truth,
and many were convinced.
The priest himself confessed to the truth of what was spoken,
though he came not to live up to it.
The following day G. Fox passed to Cleveland,
where he had a meeting and some were convinced.
The first day of the next week he went to the steeple-house,
and when the priest had finished, he directed the people to their teacher within,
Christ Jesus, who had bought them.
The priest then coming to him, had a little discourse with him,
but was soon put to silence.

From there he went to Stath, where he had large meetings,
and many received the truth that he preached, among whom was Philip Scarth, a priest,
who afterwards came to be a minister of the gospel among those called Quakers.
This people now began to increase in number in these parts, and had large meetings.
And it happened here that a certain Scotch priest, while walking with G. Fox,
asked him many questions concerning the light and the soul;
to all of which he was fully answered.
But after they parted, this Scotch priest met Philip Scarth,
and breaking his cane against the ground, said in anger,
"`If ever I meet with George Fox again, I will have his life,
or he shall have mine;`" adding, "`I will bet my head,
that G. Fox will be knocked down within a month.`"
Yet what is marvelous, is that this same Scotch priest, after some years,
came to be one of the people called Quakers,
and afterwards G. Fox visited him at his house.
Not unlike this story, was that of a woman of note among the Independents, who,
being swayed by prejudice against G. Fox,
said she would willingly have gone to see him hanged.
But when she heard him preach, she was so reached and convinced of the truth he declared,
that she came to be one of his friends.
Oftentimes he had opportunity to speak with the priests, who,
when they heard of his coming, would sometimes hide themselves;
for it was a dreadful thing to them when it was told them,
"`The man in leather breeches has come.`"
For this was indeed his dress in those days, not out of any superstition,
but because leather clothes (being strong) were suitable
for one that travelled as much as he did.

Coming to Malton he had large meetings;
but it was considered a strange thing for a man to preach in houses,
and many dared not come there for fear of their relations.
He was therefore much desired to come and preach in the
churches (as the steeple-houses are commonly called).
One of the priests himself, named Boyes (who was so taken with him,
that he called him brother), invited him to preach in his steeple-house;
but G. Fox had little inclination to that,
because both priests and people called these places of worship
"`The house of God;`" whereas the apostle said to the Athenians,
"`God dwells not in temples made with hands.`"
He therefore endeavored to draw people off from such superstitions,
and to make them understand that God and Christ ought to dwell in their hearts,
that so their bodies might be made the temples of God.
Yet at one time he did go into the steeple-house at Malton,
where there was not above eleven hearers, to whom the priest was preaching;
but after it was known in the town that G. Fox was there, it was soon filled with people.
And when the priest had finished, he sent the other that had invited him there,
to bring him up into the pulpit.
But G. Fox sent him word that there was no need to go into the pulpit.
This priest, not satisfied with this refusal, sent again, desiring him to go up unto it,
"`For,`" said he, "`it is a better place to be seen of the people.`"
But G. Fox answered, that he could be seen and heard well enough where he was;
and that he did not come there to hold up such places,
or their forced maintenance and trade.
This creating some displeasure,
one suggested that these were the false prophets that were to come in the last times.
But this saying grieved many of the people, and some began to murmur at it.
Whereupon G. Fox stepped up on a high seat and requested all to be quiet;
and since something had been spoken about false prophets,
he declared to the auditory the mark of the false prophets,
and showed how they had already come, and were out of the steps of the true prophets,
and of Christ and His apostles.
He also directed the people to their inward teacher, Christ Jesus,
who would turn them from darkness to light.
And having opened several Scriptures to them,
he directed them to the Spirit of God in themselves, by which they might come to God,
and also to know who the false prophets were.
And having thus had a long time to preach to the people,
he went away without any disturbance.

After some time he came to Pickering,
where the justices held their court sessions in the steeple-house,
justice Robinson being chairman.
At the same time G. Fox had a meeting in the schoolhouse,
where many priests and professors came and asked several questions,
which were answered to their satisfaction, so that many persons (and among these,
four chief constables) were convinced that day.
Word was carried to justice Robinson that his priest,
whom he loved more than all the others, was overthrown and convinced.
After the meeting had finished, they went to an inn, and the said priest was very loving,
and would have paid for G. Fox`'s dinner; but this he would not allow by any means.
Then he offered his steeple-house to preach in, but George refused,
telling him and the people that he had come to bring
them off from such things unto Christ.

The next morning he went with the four chief constables to visit justice Robinson.
Meeting him at his chamber door,
G+++.+++ Fox told him he could not honor him with man`'s honor;
to which the justice said he did not desire it.
Then he went into his chamber and spoke to him concerning
the state of the false prophets and of the true;
and also concerning election and reprobation,
showing that reprobation stood in the first birth, and election in the second;
for the promises of God belonged to the second,
and the judgment of God was against the first.
All this so pleased justice Robinson, that he not only confessed it to be truth,
but when another justice that was present made a little opposition,
he informed him of his opinion; saying to G. Fox at their parting,
"`It is very well that you do exercise the gift which God has given you.`"
Then he took the chief constables aside and would have given them some money for G. Fox,
saying, "`I desire that he not be at any charge in this country.`"
But they told him, that they themselves could not get him to take any money.
G+++.+++ Fox passing from there, priest Boyes went along with him.
But this year being now come to an end,
let us take a short view of how it stood with state affairs.

It has been said already, that Charles the II. had been crowned king by the Scots,
but after he and his forces had been beaten by Cromwell,
he marched afterwards with a new army into England,
and took Worcester without opposition.
However, in the month of September, his forces were so entirely routed by Cromwell,
that king Charles (to prevent being taken prisoner after
the battle) hid himself a whole day in a hollow oak,
and afterwards, being clothed like a servant and called by the name of William,
passed through the country, and through many hazards escaped out of England,
and arrived on the coast of Normandy in France.

Here we will leave him and return again to G. Fox,
who coming with priest Boyes into a town, and hearing the bells ring,
asked what they were for.
They told him it was for him to preach in the steeple-house.
Walking there, he saw the people were gathered together in the steeple-house yard.
The priest who accompanied him, desired him to go into the steeple-house;
but he said it was not necessary.
This seemed strange to the people,
that he would not go into that which they called the house of God.
But he stood up in the steeple-house yard,
and declared to them that he had not come to hold up their idol temples,
nor their priests, nor their tithes, nor their Jewish and heathenish ceremonies;
and that the ground on which their temples stood
was no more holy than any other piece of ground.
He declared the purpose for which the apostles went into the Jews
synagogues and temples was to bring people off from that temple,
and from the offerings and tithes, and covetous priests of that time;
and those who were converted, and who believed in Christ,
afterwards met together in dwelling-houses.
And that now, all who preach Christ, the Word of life, ought to preach freely,
as the apostles did, and as Christ commanded;
and that the Lord God of heaven and earth had sent him to preach freely,
and to bring people off from the outward temples made with hands,
where God does not dwell,
that so they might know their bodies to become the temples of God and Christ.
Moreover, that they ought to leave all their superstitious ceremonies, traditions,
and doctrines of men,
and not regard such teachers of the world as took tithes and high wages,
preaching for hire, and divining for money; whom God and Christ never sent,
according to their own confession, for they confess they never heard God`'s voice.
That therefore people ought to come to the Spirit and grace of God in themselves,
and to the light of Jesus in their own hearts.
Thus they will come to know Christ (their free teacher) to bring them salvation,
and to open the Scriptures to them.
This speech had such an effect that many of them
declared they were convinced of the truth.

From this place he went to another town, and priest Boyes went along with him.
Many professors came to him there, but he sat silent before them for some hours;
which made them often ask the priest, "`When will he begin?
When will he speak?`"
To which the priest said,
"`Wait;`" and told them that the people waited upon Christ a long while before He spoke.
Now, though G. Fox by silence was to famish people from words,
yet at length he felt himself moved to speak, which he did so effectually,
that many were reached, and there was a general convincement among them.

From here he passed on, the priest continuing to go with him, as did several others.
And as they went along, some people called to the priest and said, "`Mr. Boyes,
we owe you some money for tithes, please come and take it.`"
But throwing up his hands, he said, "`I have enough, and will receive none of it.
You may keep it;`" and he praised the Lord he had enough.
At length they came into this priest`'s steeple-house in the moors;
and the priest going in before him, held open the pulpit door.
But G. Fox told him he would not go into it.
And this steeple-house being very much painted,
he told him and the people that the painted beast had a painted house.
Then he spoke to them concerning the rise of all such houses,
and their superstitious ways; and told them that,
even as the end of the apostles`' going into the
temples and synagogues was not to hold them up,
but to bring people to Christ, the substance;
so the end of his coming there was not to hold up these temples, priests, and tithes,
but to bring people off from all these things, unto Christ, the substance.
Moreover, he declared to them what the true worship was, which Christ had set up;
and he distinguished Christ, the true way, from all the false ways,
opening the parables to them, and turning them from darkness to the true light,
that by it they might see themselves and their sins, and Christ their Savior,
that thus believing in Him, they might be saved from their sins.

After this, he went to the house of one Birdet, where he had a large meeting,
and the priest Boyes accompanied him still, leaving his steeple-house.
Then he returned towards Crantsick, to Captain Pursloe`'s and Justice Hotham`'s,
who received him kindly, being glad that truth had spread,
and that so many had received it.
And Justice Hotham said, "`If God had not raised up this principle of light and life,
which G. Fox preaches, the nation would have been overrun with Ranterism,^
footnote:[Ranters were a somewhat odd,
non-conformist group that sprung up in the mid 1600`'s,
and who received their name because of their extravagant discourses and practices.
Some of them appear to have been genuine seekers of truth,
who (in the words of William Penn) "`did not keep in the humility and in the fear of God,
and after the abundance of revelation, were exalted above measure;
and for lack of staying their minds in a humble dependence upon Him that
opened their understandings to see great things in His law,
they ran out in their own imaginations, and mixing them with those divine openings,
brought forth a monstrous birth, to the scandal of those that feared God.`"
Ranters would often interrupt established religious gatherings with shouting (ranting),
singing, playing instruments, or making other loud noises.]
and all the justices in the nation could not have stopped it with all their laws.`"

Now, though G. Fox found good entertainment, yet he did not settle there,
but kept in continual motion, going from one place to another, to beget souls unto God.
I do not intend to relate all his occurrences,
but will give a short hint of some of the chief of them.

Coming then towards night into Patrington, he walked through the town,
and meeting the priest in the street, he warned both him and the people to repent,
and to turn to the Lord.
As the people gathered about him, he declared to them the word of life,
directing them to the inward Word, that is, the light wherewith they are enlightened.^
footnote:[John 1:9]
Going afterwards to an inn (for it was dark) he desired lodging, but it was denied him;
then he asked for a little food or milk, offering to pay for it,
but this also was refused him.
Being thus put off, he walked out of the town, and some rude fellows following,
asked him, "`What news?`"
To which his answer was, "`Repent, and fear the Lord.`"
After he had gone a fair ways out of the town,
he came to another house where he desired to have some food, drink,
and lodging for his money, but they would not allow him to stay there.
So he went on to another house, but met with the like refusal.
By this time it had grown so dark that he could not see the highway,
but perceiving a ditch, he found a little water, and so refreshed himself.
Then, going over the ditch, and being weary,
he sat down among the furze bushes until it became day.
When he arose and had passed on through the fields,
a man came after him with a pike-staff, and went along with him to a town,
where he incited the people with the constable and
chief constable before the sun had risen.
G+++.+++ Fox seeing the multitude,
warned them of the day of the Lord that was coming upon all sin and wickedness,
and exhorted them to repent.
But, laying hold of him,
they carried him back to Patrington and guarded him with halberts, pikes, staves, etc.
Having come to the said town, all was in an uproar;
and as the priest and constables consulted together what to do with him,
he took the opportunity to exhort the people to repentance,
and to preach the word of life to them.
At last a thoughtful man called him into his house, where he got some milk and bread,
not having eaten for some days before.

Then he was carried about nine miles to a justice; and when he had come near his house,
a man came riding after him, and asked whether he was the man who had been apprehended.
G+++.+++ Fox asking him, "`Why?`"
The other said, "`For no harm.`"
Then, telling him he was, the man rode away to the justice.
Now the men that guarded G. Fox said it would be well if
the justice was not drunk when they came to him,
because he was usually drunk early.
G+++.+++ Fox being brought in before him, and not putting off his hat, and saying _thou_ to him,
the justice asked the man who had ridden there before whether he was not confused or mad?
But the man said, "`No: it is his principle to behave himself so.`"
G+++.+++ Fox, being unwilling to let any opportunity slip without admonishing people to virtue,
warned the justice to repent,
and bid him come to the light with which Christ had enlightened him,
that by it he might see all his evil words and actions,
and so return to Christ Jesus while he had time, and that he ought to prize that time.
"`Yes, yes,`" said the justice,
"`the light that is spoken of in the third chapter of John.`"
G+++.+++ Fox desired that he would mind and obey it; and then laying his hand upon him,
the justice was so brought down by the Lord`'s power that all the watchmen stood amazed.
He then took G. Fox with him into a parlor along with the other men,
and desired to see what letters or intelligence he might have in his pockets;
for it seems they suspected him to be an enemy to the Commonwealth.
Then he pulled out his linen, and showed that he had no letters;
which made the justice say,
"`By his linen I can see he is no vagrant,`" and so set him at liberty.
Then G. Fox went back to Patrington again,
with the man who had ridden before him to the justice, and who lived in that town.
Coming to his house, he desired G. Fox to go to bed, or to lie down upon it;
which he did--that they might say they had seen him in a bed, or upon a bed.
For there was a silly report spread abroad that he would not lie upon any bed,
doubtless having been raised because at this time he often passed the night outdoors.

When the First-day of the week had come,
he went to the steeple-house and declared the doctrine of Truth to the priest and people,
without being mistreated.
Then soon after, he had a large meeting at the man`'s house where he stayed,
and many were convinced that day of the truth that he preached,
and were exceedingly sorry that they had not given him lodging when he was there before.
From there he travelled through the country,
warning people in both towns and country villages to repent,
and to turn to Christ Jesus their teacher.

On a First-day of the week he came to one colonel Overton`'s house,
and had a large meeting of the chief people of that country;
where he opened many things out of the Scriptures which they never had heard before.
Coming afterwards again to Patrington,
he understood that a tailor and some wild young men in that
town had occasioned his being carried before the justice.
This tailor came to ask him forgiveness, fearing he would complain of him.
The constables also were afraid lest he should trouble them, but he forgave them all,
and exhorted them to turn to the Lord, and to amend their lives.
Now that which made them the more afraid was that,
having not long before been in the steeple-house at Oram,
there came a professor that gave him a push on the
breast and bid him "`Get out of the church.`"
To which G. Fox said, "`Do you call this steeple-house the church?
The church is the people, whom God has purchased with His blood, and not the house.`"
But having heard of this man`'s thus abusing G. Fox, justice Hotham sent a warrant,
and bound the said man over to the court sessions.
So zealous was this justice to keep the peace,
that he had asked G. Fox before whether any people had abused him.
But esteeming it his duty to forgive all, George told him nothing of that kind.

From Patrington he went to several rich men`'s houses,
warning them to repent.
Some received him lovingly, and some slighted him.
Passing thus through the country,
at night he came to another town where he desired lodging and food,
offering to pay for it;
but they would not lodge him unless he went to a constable to ask leave,
which they said was the custom for strangers.
But he told them that this custom was for persons suspected of crimes,
and not for such as he, who was an innocent man.
So after he had warned them to repent, and to mind the day of their visitation,
and directed them to the light of Christ, and Spirit of God, he passed away.
As it grew dark he spied a hay-stack, and went and sat under it till morning.
The next day he came to Hull,
where he admonished the people to turn to Christ Jesus that they might receive salvation.
And being very weary with traveling on foot so far, he got a lodging there that night.

From there he went to Nottinghamshire, visiting his friends there;
and then passed into Lincolnshire, where he did the same.
And coming to Gainsborough, where one of his friends had been preaching in the market,
he found the town and people all in an uproar; in part,
because a certain man had raised a false accusation,
reporting that G. Fox had said he was Christ.
Here, going into the house of a friendly man, the people rushed in after him,
so that the house soon was filled; and among the rest was also this false accuser,
who said openly before all the people that G. Fox said he was Christ,
and that he had witnesses to prove the same.
G+++.+++ Fox kindled with zeal, stepped upon the table, and said to the people,
that "`Christ is in you, except you be reprobates;`"^
footnote:[2 Corinthians 13:5]
and that he had said it was Christ, the eternal power of God,
that spoke in him at that time; but not that he was Christ.
This gave general satisfaction, except to the false accuser himself.
So G. Fox called to this man, and told him he was a Judas,
and that Judas`'s end should be his, and that this was the word of the Lord to him.
The minds of the people coming thus to be quieted, they departed peaceably.
But it was very remarkable, that this Judas shortly after hanged himself,
and a stake was driven into his grave.
Now, though this was a well known thing in this country,
yet some priests spread a report that a Quaker had hanged himself in Lincolnshire,
and had a stake driven through him.
But this wicked slander prevailed so little,
that many people in Lincolnshire were convinced of the truth preached by G. Fox.

After this he passed into Yorkshire, and coming to Warnsworth,
he went to the steeple-house in the forenoon, but found no acceptance.
And being thrust out, he was sorely beaten with staves,
and clods of dirt and stones were thrown at him; yet he exhorted them to repent,
and to turn to Christ.
In the afternoon he went to another steeple-house,
but the sermon was finished before he got there;
so he preached repentance to the people who had not yet departed,
and directed them to their inward teacher, Christ Jesus.
From here he came to Doncaster, where he had formerly preached in the market.
But now on the First-day of the week he went into the steeple-house,
and after the priest had finished, he began to speak, but was hurried out,
and hauled before the magistrates who threatened
him with death if ever he came there again.
But notwithstanding all this, G. Fox bid them to mind the light of Christ in them,
saying, "`God has come to teach His people Himself, whether they would hear or not.`"
After a while, being put out on the street with some of his friends that were with him,
they were stoned by the rude multitude.
A certain innkeeper, who was also a bailiff, seeing this,
came and took them into his house,
but one of the stones that were thrown hit George`'s head,
so that blood ran down his face.

The next First-day G. Fox went to Tickhill;
where he went into the steeple-house and there found
the priest and the chief of the parish in the chancel.
Beginning to speak to them, they immediately fell upon him,
and the clerk struck him with his bible so violently on the face,
that the blood gushed out and he bled exceedingly.
Then the people thrust him out of the steeple-house, beat him and threw him down,
and dragged him along the street, so that he was besmeared with blood and dirt,
and his hat was taken away.
When he had gotten up again,
he spoke to the people and showed them how they dishonored Christianity.
Some time after, the priest coming by,
scoffingly called G. Fox and his friends "`Quakers.`"
But he was spoken to in such authority and dread, that he fell a trembling,
which made one of the people say, "`Look how the priest trembles and shakes,
he is turned a Quaker also!`"
Some moderate justices now hearing how G. Fox and his friends had been abused,
came to examine the business.
The clerk was afraid of having his hand cut off for striking him in the church,
but G. Fox, as a true Christian, forgave him, and would not appear against him.

Thus far G. Fox has alone been mentioned as a preacher of repentance;
but now some others of his persuasion began also to preach publicly, namely,
Thomas Aldam, Richard Farnsworth, and, not long after, William Dewsbury.
This made such a stir that the priest of Warnsworth procured
a warrant from the justices against G. Fox and Thomas Aldam.
The constable who came with this order took Thomas Aldam and carried him to York,
and G. Fox went with him twenty miles.
But though the constable had a warrant for him also, yet he meddled not with G. Fox,
saying he was unwilling to trouble men that were strangers;
but Thomas Aldam was his neighbor.
About this time Richard Farnsworth went into an eminent steeple-house in or about Wakefield,
where he spoke so powerfully that the people were amazed.
The priest of that place, whose name was Marshal,
spread a slanderous report that G. Fox carried bottles about with him,
and made people drink, which made them follow after him;
and also that he rode upon a great black horse,
and was seen in one country upon that horse,
and in the same hour in another country sixty miles off.
But these horrid lies were so far from turning to the priest`'s advantage,
that he preached many of his hearers away from him;
for it was well known that G. Fox had no horse at that time, but travelled on foot.

G+++.+++ Fox coming now into a steeple-house not far from Bradford;
the priest there took his text from Jerermiah 5:31,
"`My people love to have it so;`" leaving out the foregoing words,
"`The prophets prophesy falsely, and the priests bear rule by their own power.`"
Unwilling to let this pass unregarded,
G+++.+++ Fox showed the people the priest`'s unfair dealing; and,
directing them to Christ the true inward teacher,
declaring that God had come to teach His people Himself,
and to bring them off from all the world`'s teachers and hirelings,
that they might come to receive freely from Him;
concluding his speech with a warning of the day of
the Lord that was coming upon all flesh.
He passed from there without much opposition,
and travelled now for some time with Richard Farnsworth,
with whom he once passed a night in the open field on a bed they had made of ferns.

Then parting from him, he came to Wentzerdale, where he went into the steeple-house;
and after the lecture,
he spoke to the people in much the same terms as he usually did on similar occasions,
and found not much opposition there.
Thus he went from place to place and often met with strange occurrences;
some of his hearers being more silly than serious; others very rude,
or even dangerous to his life.
But he trusted in God, really believing that He had sent him to preach repentance,
and to exhort people to a true conversion.

Thus traveling on, he came near Sedbergh.
There he went to a meeting at Justice Benson`'s,
where a people met together who had separated themselves from the public worship.
By his preaching in this place he gave such general satisfaction that
most of the hearers were convinced of the Truth declared by him.
Thus the number of his fellow-believers increased so greatly,
that they now had meetings by themselves in many places of the country.

There being at this time a fair at Sedbergh,
G+++.+++ Fox declared the day of the Lord throughout the fair;
and afterwards went into the steeple-house yard where an abundance of people came to him.
Here he preached for several hours,
showing that the Lord had come to teach His people Himself,
and to bring them off from all the world`'s ways and teachers, unto Christ,
the true teacher, and the true way to God.
Moreover, he showed the declining state of the modern priests and teachers,
and exhorted the people to come off from the temples made with hands,
and wait to receive the Spirit of the Lord that they
might know themselves to be the temples of God.
None of the priests (several of whom were present) spoke against what he had declared;
but a captain said, "`Why will you not go into the church;
for this is not a place fit to preach in?`"
G+++.+++ Fox told him that he did not approve of their church.
Then stood up one Francis Howgill, who was a preacher,
and though he had never seen G. Fox before,
yet he was so affected by his words that he answered the captain,
and soon put him to silence; "`For,`" said Howgill, "`This man speaks with authority,
and not as the scribes.`"
After this,
G+++.+++ Fox opened to the people how the ground and house of
that building was not more holy than any other place,
and that the house was not the church, but the people, of whom Christ was the head.
The priests then coming to him, he warned them to repent;
upon which one of them said he was mad.
But notwithstanding his saying so, many were convinced there that day,
and among these was one Captain Ward.

The next First-day G. Fox came to Firbank chapel in Westmoreland,
where the said Francis Howgill and one John Audland had been preaching in the morning.
The chapel at that time was so full of people, that many could not get in;
and Howgill said afterwards that he thought G. Fox had looked into the chapel,
and his spirit was ready to fail.
But G. Fox did not look into it.
However,
Howgill had been so reached when he heard him preach in the steeple-house yard at Sedbergh,
that he was (as it were) checked, and therefore quickly made an end of his sermon,
thinking (as well as others) that G. Fox would preach there that day, as indeed he did.
For having refreshed himself at noon with a little water out of a brook,
he went and sat down on the top of a large rock by the chapel,
intending to have a meeting there.
At this the people wondered,
because they looked upon the church (so called) as a holy place, requisite for worship.
But G. Fox told them afterwards that the ground whereupon
he stood was as good as that of the steeple-house;
besides, we find that Christ Himself did preach on a mountain and also at the seaside.

Now in the afternoon, the people gathered about him, with several of their preachers,
and among these, Francis Howgill and John Audland.
To this auditory, which was judged to consist of more than a thousand people,
G+++.+++ Fox began to preach, and spoke about the space of three hours,
directing all to the Spirit of God in themselves,
that so they might be turned from darkness to light, and from the power of Satan,
which they had been under, unto God.
By this, he said, they would become children of the light,
and be led into all truth by the Spirit of Truth;
and so feel and understand the words of the prophets of Christ, and of the apostles,
and come to know Christ to be their teacher to instruct them,
their counsellor to direct them, their shepherd to feed them,
their bishop to oversee them, and their prophet to open divine mysteries to them.
Thus their bodies would be prepared, sanctified,
and made fit temples for God and Christ to dwell in.
Moreover he explained the prophets, and the figures, and shadows,
and directed his hearers to Christ the substance.
He also opened the parables and sayings of Christ,
and showed the intent and scope of the apostles`' writings,
which are epistles to the elect.
Then he spoke also concerning the state of apostasy,
that has been since the apostles`' days,
explaining how the priests had gotten the Scriptures
without being in that Spirit which gave them forth;
and how they were found in the steps of the false prophets, scribes,
and Pharisees of old, and were such as the true prophets, Christ,
and His apostles cried against;
insomuch that none that were guided by the Spirit of God now could acknowledge them.

While G. Fox was thus preaching,
many old people went into the chapel and looked out at the windows,
thinking it a strange thing to see a man preach on a hill,
and not in the church (as they called it).
Perceiving this, he said, "`The steeple-house, and the ground whereupon it stands,
is no more holy than this hill; and those temples,
which are called the '`dreadful houses of God,`'
were not set up by the command of God and Christ;
nor were their priests instituted as Aaron`'s priesthood was;
nor were their tithes appointed by God as those among the Jews were.
But Christ has come, who ended both the temple and its worship,
and their priests and their tithes; and therefore all ought to hearken unto Him.
For Christ said, '`Learn of me;`' and God said of Him, '`This is My beloved Son,
in whom I am well pleased,
hear Him.`'`" In conclusion he said that the Lord
God had sent him to preach the everlasting gospel,
and Word of life among them, and to bring them off from all these temples, tithes,
priests, and rudiments of the world, which had risen up since the apostles`' days,
and had been set up by those who had gone astray from the
Spirit and power that the apostles were in.
Thus preached G. Fox,
and his ministry was at that time accompanied with such a convincing power,
and so reached the hearts of the people,
that many (including all the teachers of that congregation,
who were many) were convinced of the Truth that was declared to them.

After this meeting was over, G. Fox went to John Audland`'s who,
along with Francis Howgill and others,
had been quite brought over by his effectual preaching.
And as these had been zealous preachers among those of their former persuasion,
so it was not long before they became publishers of that doctrine, which now,
by the ministry of G. Fox, they had embraced.
And these were so far from approving their former service,
that they gave back the money they had received for
their preaching to the parish of Colton in Lancashire;
being now resolved to give freely what they had received freely.
And here I shall make a small digression,
in saying something concerning these two excellent men.

John Audland was a young man, and of a handsome countenance, and very lovely qualities.
When he was but seventeen or eighteen years old, he was very religious,
and a zealous searcher of the Holy Scriptures;
and having a good understanding and strong memory,
he thereby gathered a large treasury of Scripture learning
and became an eminent teacher among the Independents,
having a very numerous auditory.
But when he heard G. Fox preach, he was thereby so reached to the heart,
that he began in process of time to see the emptiness of his great literal knowledge,
and that "`all his righteousness was as filthy rags.`"
This brought him to a state of mourning,
for now he saw that all his profession and wisdom could not bring him to true happiness.
But the Lord, who does not break the bruised reed, nor quench the smoking flax,
did pity him in this state of deep humiliation,
and bore him up again by His supporting power;
whereby in time he came to be prepared for that service he was appointed to by God.

Concerning Francis Howgill; he was also a religious man, who,
having seen the superstitions of the Episcopal church, had left it,
and applied himself to the Independents.
But although he, who had been trained up in the university to be a minister,
became a teacher among the Independents, and was zealous in virtue,
yet he remained dissatisfied in himself, finding that notwithstanding all his fasting,
praying, and good works, the root of sin still remained in him.
And although the common doctrine was that Christ had taken the guilt of sin upon Himself,
yet this could not satisfy him; because his conscience told him,
"`You are that one`'s slave whom you obey.`"^
footnote:[Romans 6:16]
Thus increasing in understanding,
it was made clear to him that the Lord (according to what
the prophets had foretold) would teach His people Himself;
and it also seemed to him, that this time was near at hand.
Some time after this it happened, as has been said already,
that he was present when G. Fox preached,
and when he heard him say that "`the light of Christ in man was
the way to Christ,`" he believed this to be the word of truth,
and saw how he had been ignorant of the substance of true religion.
Submitting then to the reproofs of this inward light,
he saw the unfruitfulness of all his labor, and anguish and sorrow seized upon him,
and judgment went over all his former actions.
But being given up and resigned in this state, saying within himself, "`You, O God,
are just in all Your judgments,`" it pleased the
Lord in due time to fill his heart with joy,
and to make him a minister of His everlasting Word.
But no sooner did he enter into that service, but both priests and magistrates,
of whom he formerly had been beloved, became his enemies.
And so great was the envy which was kindled against him,
that he was locked up in a nasty place at Appleby, in Westmoreland,
and was kept there prisoner for some time.

But let me now return to G. Fox, who coming to Kendal,
had a meeting there in the town hall.
Here he declared the word of life,
showing the people how they might come to the saving knowledge of Christ,
and to have a right understanding of the Holy Scriptures,
opening to them what it was that would lead them into the way of reconciliation with God.
This was of such effect, that several became convinced of the truth proclaimed by him,
and others were so drawn to him, that when he went to Under-Barrow,
several people accompanied him.
He had great reasonings with some of these, but especially with one Edward Burrough, who,
though a young man of extraordinary natural abilities and acquired knowledge,
was not able to withstand the efficacious sayings of G. Fox.
And because this Burrough became an eminent man among the Quakers (so called),
being endued with courage and understanding sufficient to overcome his opposers,
and to break even stony hearts, I will mention here a little of his descent and quality.

He was born in the barony of Kendal, in Westmoreland,
of parents who were in good repute for their honest and virtuous life.
He was well educated and trained up in such learning as that country did afford.
His knowledge and understanding soon surpassed his years;
for being but a boy he had the spirit of a man,
and in his youth was endued with wisdom above his peers.
Moreover, he was very religious,
conversing frequently with those that were in esteem for piety and a godly life.
He was not inclined to the ordinary pleasures of youth,
but it was his delight to be exercised in reading of Holy Scripture,
wherein he was well versed.
By his parents he was trained up in the Episcopal worship;
yet when but twelve years of age,
he often went to the meetings of the Presbyterians because their doctrine (in
many things) seemed to approach nearer to truth than that of the national church;
for which he became a follower of the Presbyterians,
although he was reviled for it by his acquaintances.

But having come to the age of about seventeen years,
and growing more and more aware of his own condition, he was often struck with terror.
And once, when he had been praying, he heard, as it were, a voice which said,
"`You are ignorant of God; you know not where He is, nor what He is;
to what purpose is your prayer?`"
This brought him under such a concern, that he began to take diligent heed to his life,
so that he abstained not only from all vanities,
but (when the occasion offered) he sometimes reproved
others for their vain conduct and wickedness.
For this he was derided and looked upon scornfully by many,
yet he continued to live religiously, and felt sometimes sweet refreshments to his soul.
But though he had the Truth in his comprehension,
yet he lacked the real and experiential knowledge of it, and so became darkened again,
losing what he once possessed.
And then, being too ready to flatter himself,
he would sometimes comfort himself with that saying, "`Whomever God loves once,
He loves forever.`"
But he grew weary of listening to the priests;
for he saw that they did not possess what they spoke of to others;
and at times he began to question his own experience.
Having many times come to such an impasse, he seemed almost to be at a loss.

It was in this condition that he heard G. Fox preach, and afterwards reasoned with him.
And it pleased the Lord to open his understanding so that he perceived
(as he relates himself) that he was "`in the prodigal state,
above the cross of Christ,^
footnote:[That is to say, not under it, bearing its judgment, but lifted above it,
trampling it underfoot.]
and not in the pure fear of the Lord.`"
Being thus convinced, he entered into the society of the despised Quakers,
though he was now rejected by his relations, and, by a blind zeal,
turned out of his father`'s house.
This he bore patiently, and continued faithful in the doctrine he had embraced.
And in the process of time he so advanced in true knowledge,
that he became a very eminent minister of the gospel.
But oh, what adversities did he not undergo?
Reviling, slandering, buffeting, and caning^
footnote:[Being beaten with a cane as a form of corporal punishment.]
were often his lot; watching and fasting were many times his portion;
and he was frequently acquainted with imprisonments, great jeopardies,
and danger of life.
But nothing could make this champion shrink; he was always laborious,
and seldom had any hours of rest.
In his preaching he was very acceptable and eloquent in his speech,
and had the tongue (according to what an eminent author relates,
who knew him from his youth) of a learned orator,
able to declare himself to the understandings and
consciences of all men that he met with.
He was also a great writer,
and often would engage in disputes with those of other persuasions,
sparing no pains where he thought he could serve the Lord and the church.
This much, for now, concerning Edward Borrough.

Let us return now to G. Fox, whom we left at Under-Barrow,
where (with the consent of the inhabitants) he had a large meeting in the chapel,
where many were convinced and received the truth preached by him.
From there he went to Lancashire, and having in some places spoken in the steeple-houses,
he passed on to Ulverstone, and so to Swarthmore, to the house of Thomas Fell,
a judge in Wales, where many priests frequently came.
The judge was abroad at that time, employed in the exercise of his office,
and his wife Margaret had also gone abroad that day.
G+++.+++ Fox in the meantime coming there, met the priest William Lampitt,
who was a proud notionist,^
footnote:[i.e. one whose religion stood only in notions and doctrinal opinions.]
and full of words.
But soon perceiving that this priest was without the possession of what he professed,
G+++.+++ Fox opposed him boldly.
Before it was night, Margaret Fell returned home,
and heard from her children that Lampitt and Fox had disagreed,
which did somewhat trouble her; for at that time she had a high regard for the priests,
and especially admired Lampitt.
The same night G. Fox reasoned with them there, declaring the Truth to her and her family.
The next day Lampitt came again,
and G. Fox discoursed with him in the presence of Margaret Fell,
who then began to clearly discern the priest.

The following day being appointed for a fast,
Margaret went with her children to the steeple-house at Ulverstone,
having previously asked G. Fox to go with her.
But he replied that he must do as he was ordered by the Lord, and so left her,
and walked into the fields,
where he afterwards felt a strong motion to go also to the steeple-house.
When he came there the people were singing, but the words that they sang were,
according to his view, altogether unsuitable to their states.
After they had finished, he stepped up on a bench, and asked permission to speak.
The priest giving his consent, G. Fox began with this Scripture:
"`He is not a Jew that is one outwardly; neither is that circumcision which is outward.
But he is a Jew that is one inwardly; and that is circumcision, which is of the heart.`"
And so he went on, and said that Christ was the light of the world,
and had enlightened every man that comes into the world,^
footnote:[John 1:9]
and that by this light they might be gathered to God, etc.
Margaret Fell, standing in her pew, wondered at this doctrine,
having never heard any such before.
In the meantime G. Fox continued, and opening the Scriptures, said,
"`These are the prophet`'s words, and Christ`'s, and the apostles`' words;
and what they spoke, they also enjoyed and possessed, having received it from the Lord.
But to what purpose do men speak of the Scriptures,
if they come not to the Spirit that gave them forth?
You will say, '`Christ says this, and the apostles say this;`' but what can _you_, O man,
say yourself concerning this?
Are you a child of the light?
Do you walk in the light?
And what you speak, do you possess it inwardly from God?`"
He then declared that "`God has come to teach His people Himself by His Spirit,
and to bring them off from their churches, and religions,
and their own ways of worship,`" etc.
These words did so effectually reach the aforesaid Margaret,
that she sat down in her pew again, and weeping bitterly,
cried in her spirit to the Lord, saying, "`We are all thieves!
We are all thieves!
We have taken the Scriptures in words, and know nothing of them in ourselves.`"
G+++.+++ Fox still going on, declared against the false prophets,
and said that their way of worship was but talking of other mens`' words,
while they themselves were outside of the life and
Spirit which those were in who gave them forth.
Then a justice of peace named John Sawrey cried out, "`Take him away!`"
But Margaret Fell said to the officers, "`Leave him alone.
Why may not he speak as well as any other?`"
Priest Lampitt (likely to please her) said also, "`Let him speak.`"
Then having spoken yet awhile, G. Fox was at length led out by the constable,
according to the order of the said justice Sawrey;
and then he spoke to the people in the graveyard.

In the evening he came again into the house of judge Fell,
where he took occasion to speak to the servants and those of the family,
most of whom came so effectually to be convinced by him,
that they embraced the Truth which he preached.
Among these was also William Caton, of whom more will be said hereafter.
Margaret Fell in the meantime having come home, was so reached,
that she scarce knew what to do with her husband being away from home;
for she clearly perceived what she had heard G. Fox preach, was truth.

The First-day after, he went to Aldenham steeple-house, where,
when the priest had finished,
he spoke to the people and admonished them to return to the Lord.
From there he went to Ramside, where there was a chapel,
in which one Thomas Lawson (who was an eminent priest) used to preach.
Having some notice of G. Fox`'s coming, Lawson preached in the morning,
and told the people that G. Fox was to come there in the afternoon,
by which means very many people were gathered together.
When he came,
he saw there was no place more convenient to speak to the people as the chapel,
and therefore he went into it.
Priest Lawson, willing to give a full opportunity to G. Fox,
did not go not up into the pulpit, but left all the time to him.
And here G. Fox so powerfully declared the doctrine of Truth, that many received it,
and among this number was the priest himself, who left off preaching for hire,
and in the process of time came to preach the Lord
Jesus Christ and His glorious gospel freely.
This however did not hinder him from exercising himself in the knowledge of herbs,
wherein he came to be so experienced, that he was, as I have been told,
one of the most skillful botanists in England.

Now I return again to G. Fox, who having performed his service about Ramside,
went somewhere else, and then came to Briercliffe,
where he found some people who told him they were not able to dispute with him.
But he bid them to fear the Lord, and not to speak the words of God in an airy manner,
but to do the things required.
Moreover, he told them they ought to mind the light of Christ,
and take heed to His Spirit in their hearts,
whereby they would come to see their evil thoughts, words, and actions;
for this light (he said) would show them their sins,
and by following this light they would also see that
their Savior Christ Jesus could save them from sin.
And, he said, the first step to peace was to stand still in the light,
which showed them their sins and transgressions.
By this they would see they were in the fall of the old Adam, in darkness and death,
alienated from the covenant of the promise, and without God in the world;
thus they would see that Christ who died for them, was their Savior and Redeemer,
and their way to God.
After G. Fox had spoken these things, he went to a newly built chapel near Gleaston,
wherein none had yet preached.
Here came a great many people, unto whom he preached, and many were convinced.

From there he returned to Swarthmore again; for Margaret Fell,
being full of fear and expecting her husband`'s return home, had desired G. Fox to come.
For some of the influential people of that country, having gone to meet her husband,
had informed him that a great disaster had befallen the family, and that the Quakers,
who were witches, had turned them from their religion;
and that he must come and send them away, or all the country would be undone.
Without any question, this was a very hard message for judge Fell,
and he came home greatly offended.
And one may easily imagine what a condition his wife was in,
being in fear that she should either displease her husband, or offend God.

At that time Richard Farnsworth and James Nayler were at her house,
and she desired them to speak to her husband, which they did very moderately and wisely.
And though at first he was displeased, yet after he had heard them speak,
he was better satisfied.
And seeing that they made preparations to go away, she desired them to stay,
because she expected G. Fox that evening,
and she wished for an opportunity wherein both he and they might speak
to her husband and satisfy himself further about their principles.
Dinner having been made ready, judge Fell and his wife Margaret sat down at the table,
and while they were sitting, an extraordinary power seized upon her,
and operated so upon her mind that he was struck with amazement,
and knew not what to think of it.
But he remained quiet and still,
and the children also had become so grave and modest that they
could not play on the musical instruments they were learning.

At night G. Fox came, and judge Fell sitting in the parlor,
Margaret asked him if G. Fox might come in; to which he answered, "`Yes.`"
George then came in without any compliment, and presently began to speak,
at which the entire family (together with James Nayler
and Richard Farnsworth) entered the room.
Speaking to them,
he declared what the practice of Christ and the apostles was in their day,
and showed how the apostasy had came in since,
and what the practice of the modern priests was in the apostasy.
He also answered all the objections of judge Fell,
and so thoroughly satisfied him by the Scriptures, that he was convinced in his judgment,
and asked if he was the same George Fox whom justice Robinson
had so highly commended among many of the parliament men?
To this G. Fox answered him,
that he had been with the justices Robinson and Hotham in Yorkshire,
that they had been very civil and loving to him,
and that they were convinced in their judgments by the Spirit
of God that the light he bore testimony to was the Truth,
and that they saw beyond the priests of the nation.
All this so satisfied judge Fell that he was very quiet that night, and went to bed.

The next morning Lampitt, the priest of Ulverstone, came to the house,
and walking with the judge into the garden,
spoke much to him there to render the doctrine of the Quakers odious to him,
having also said to others that G. Fox held strange notions.
But judge Fell had seen so much the night before
that the priest got little entrance upon him.
And when Lampitt came into the house again, G. Fox spoke sharply to him,
and asked him when God had spoken to him and called him to preach to the people?
The priest not liking such questions, went away before long.
And while some were speaking of how several in those
parts were convinced of the Truth that had been declared,
and that they knew not where to get a meeting place, judge Fell said of his own accord,
"`You may meet in my hall, if you desire.`"
So the next First-day there was a meeting at his house, and a large one indeed,
being the first meeting of the people called Quakers at Swarthmore;
and so it continued to be kept there until the year 1690,
when a new meetinghouse was built there.
Judge Fell not being willing to appear in this meeting,
went that day to the steeple-house, and none went with him but his clerk and his groom.
Yet in the process of time he came to be so well-affected
by the doctrine of the Quakers (so called),
that, though he did not enter publicly into their society, yet he loved them,
and for several years prior to his death, did not frequent the steeple-house any more.

After G. Fox had stayed some days at the house of judge Fell, he went to Lancaster,
and there preached in the marketplace.
On the next First-day he had a large meeting in the street among the soldiers,
to whom he declared the Truth.
And in the afternoon he went to the steeple-house; but speaking there,
and directing people to the Spirit of God,
he was hauled out and stoned along the street.

Then, having travelled about for some time,
and preached in some places (sometimes with rude opposition), he returned to Swarthmore,
where, in a discussion with several priests at judge Fell`'s house,
he asked them whether any of them had ever heard the voice of God or Christ commanding
them to go to any people and declare the word of the Lord to them.
None of them answered in the affirmative, yet one said,
"`I can speak of my experience as much as you.`"
But G. Fox told told him that experience was one thing, but to go with a message,
and to have the word of the Lord as the prophets and apostles had, was quite another.
Then an ancient priest, whose name was Thomas Taylor,
did candidly confess before judge Fell that he had never heard the voice of God,
nor of Christ, but that he spoke his own experiences,
and the experiences of the saints in former ages.
This very much confirmed judge Fell in the persuasion he had already formed,
that the priests were not what they pretended to be;
for he had formerly thought (as the generality of the people
then did) that the priests of the day were sent from God.
At this time,
the words of G. Fox wrought so deeply on the mind of the said Thomas Taylor,
that he was convinced, and travelled with him into Westmoreland.
And coming into the Crossland steeple-house, T. Taylor`'s mouth was opened,
so that he declared among the people how he had been before he was convinced;
and like the good scribe, he brought forth things new and old from his treasury;
and showed the people how the priests were out of the right way.

Now great rage arose among the priests, and they began, as much as they could,
to stir up persecution; for not only did Thomas Taylor begin to preach the gospel freely,
but several others, namely, John Audland, Francis Howgill, John Camm, Edward Burrough,
Richard Hubberthorn, Miles Halhead, and others,
appeared as zealous preachers among those called Quakers,
often declaring the doctrine they professed in steeple-houses and markets;
whereby the number of their friends began greatly to increase.
