== Chapter III

[.section-date]
1652--1654

In the meantime, G. Fox returned into Lancashire and went to Ulverstone,
where Lampitt (before mentioned) was priest.
He now seeing how the people called Quakers had set up meetings,
and met in private houses, said, "`they had forsaken the temple,
and gone after Jeroboam`'s golden calf-houses;`" though formerly he had
preached of a people to come who would acknowledge the teachings of God,
and that both men and women should declare the gospel.
G+++.+++ Fox told him that the old mass houses^
footnote:[First built and used by the Roman Catholic church.]
(which they called churches) were more like Jeroboam`'s calves-houses,
though men strove to persuade people that such buildings were the house of God;
whereas Christ is the head of the church, and never was called the head of an old house;
and the apostle, speaking of Christ, said, "`Whose house we are,`"^
footnote:[Hebrews 3:6]
This puts me in mind of how some of the parliament soldiers,
observing over some of the steeple-house doors the words of the patriarch Jacob,
when God had appeared to him in a dream, "`This is none other than the house of God,
and this is the gate of heaven,`" could not endure
to see this gross delusion written upon these buildings,
and so erased out the words,
"`of God,`" and "`of heaven,`" so that nothing was
left but "`This is none other than the house;
and this is the gate.`"
And certainly the zeal of these men was more reasonable
than the imagination of those who think that,
in the gospel days, a building of lime and stone should be called the house of God.
It also seems a silly practice to call a house furnished with a steeple, a church;
but to deny this name to the congregation-houses used by dissenters,
calling them only by the name of meetinghouses.
But this deceit has kept up the esteem of those large mass-houses and their priests.
And that they might not lose profit in their burials,
they have endeavored to keep people in the belief
that the ground of these buildings is holy;
all of which gave occasion to the people called Quakers
to call those buildings steeple-houses.

G+++.+++ Fox going to the steeple-house where priest Lampitt was preaching,
John Sawrey (the justice) came to him and said,
"`If you will speak according to the Scriptures, you may speak.`"
G+++.+++ Fox told him he would indeed speak according to the Scriptures,
and bring the Scriptures to prove what he had to say.
But then Sawrey, contradicting himself, said he should not speak;
and then incensing the people against him, they fell upon G. Fox, knocked him down,
kicked him, and trampled upon him.
At last Sawrey came, took him from the people, and led him out of the steeple-house,
bidding the constables to whip him.
Then he was dragged out of the town and given over to the rage of the rude multitude,
who did so terribly beat him with switches and staves, that he at length fainted,
and fell down upon the wet ground.
But recovering again, and being strengthened by an immediate power, he stood up,
and stretching out his arms, said with a loud voice, "`Strike again, here are my arms,
my head, and my cheeks!`"
Then a mason gave him such a heavy blow over the back of his hand with his staff,
that it was marred, and his arm was so benumbed,
that he could not draw it back to him again, so that some of the people cried out,
"`He has spoiled his hand forever!`"
But he being preserved through the love of God, stood still,
and after a while felt such an extraordinary strengthening power,
that he instantly recovered strength in his hand and arm.

This made the people argue among themselves;
and some said to G. Fox that if he would give them money,
they would protect him from the rest.
But, instead of doing so, he showed them their false Christianity,
and told them they were more like Jews and heathens than true Christians,
and that their fruits were an evidence of the unprofitable ministry of their priests.
Then he felt himself moved to return to Ulverstone, and went into the marketplace there.
And as he went, a soldier met him and said, "`Sir, I see you are a man,
and I am ashamed and grieved that you should be thus abused.`"
But G. Fox told him, "`The Lord`'s power is over all.`"
And this he indeed experienced, for when he walked through the people in the market,
none of them had power to touch him at that time, though some of his friends were abused.
And then seeing the soldier among them with his sword unsheathed,
he bade him put up his sword if he desired to go along with them.
For this soldier was desiring to draw him away from the crowd,
lest some mischief should be done to him.
And yet, a few days after this, seven men fell upon this soldier,
and beat him cruelly because he had taken part with G. Fox and his friends.

Having performed his service at Ulverstone, G. Fox came again to Swarthmore,
where he found several of his friends dressing the wounds
and bruises they had received by the hearers of priest Lampitt.
And now the priests began to prophesy,
that within half a year the Quakers would all be put down and gone.
But they reckoned wrong; for it happened with this people as with trees,
which grow best when they are most lopped.

G+++.+++ Fox keeping in continual motion, went with James Nayler to Walney Island,
having first had a meeting at a little town called Cockan,
where a man came to him with a pistol and pointed it at him, but it would not go off.
G+++.+++ Fox then zealously spoke to him so that he was struck and trembled with fear,
and went away.
The next morning G. Fox went over in a boat to the home of James Lancaster,
and as soon as he came to land, about forty men with staves, clubs,
and fishing-poles fell upon him, beating and punching him,
and endeavored to thrust him back into the sea.
Attempting to press on, he was knocked down and stunned, and when he came to himself,
he saw James Lancaster`'s wife throwing stones at his face,
and her husband was lying over him to ward off the blows and the stones;
for the people had persuaded this woman that G. Fox had bewitched her husband,
and had promised her to kill him when he came there.
But the Lord, by His invisible power, wonderfully preserved him,
so that they could not take away his life.
At length he got up, but was soon beat down again into the boat.
James Lancaster observing this, came to him and pushed off into the water.
And having come to the other side,
they saw how the wicked crew had fallen upon James Nayler, with a horrible cry,
"`Kill him; Kill him.`"
For while they had been beating G. Fox, they had not minded Nayler,
who was walking up into a field.

Having now come again to Cockan, G. Fox met with no better reception,
for the people came on with pitchforks, flails, and staves to keep him out of the town,
crying, "`Kill him; Knock him on the head.`"
But he was preserved alive; and after having been much abused,
they drove him a fair distance out of the town and left him.
Then James Lancaster went back to look after James Nayler.
In the meantime G. Fox went to a ditch of water,
and washed himself from the blood and dirt.
After which he walked about three miles to the house of one Thomas Hutton,
but was so bruised that he could hardly speak;
only he told them where he had left James Nayler.
Whereupon Thomas Hutton and Thomas Lawson (the priest mentioned before,
who then lodged at Hutton`'s house) took each of them a horse,
to see if they could find James Nayler; and coming upon him,
they brought him there that night.

The next day, hearing what had befallen G. Fox, Margaret Fell sent a horse for him,
but he was so sorely bruised that he was not able
to bear the shaking of the horse without much pain.
When he had come to Swarthmore,
the justices Sawrey and Thompson gave forth a warrant against him;
but judge Fell coming home, made it ineffectual,
and sent out warrants into the Isle of Walney to apprehend all those riotous persons;
whereupon some of them fled the country.
But what is remarkable, James Lancaster`'s wife, who had behaved herself so wickedly,
later so repented of her evil that she became one of G. Fox`'s friends.

Judge Fell now desired G. Fox to give him a relation of what had befallen him,
but he was reluctant,
and said that those people could do nothing else in the spirit they were in,
and that they manifested the fruits of their priests`' ministry.
This made the judge afterward say to his wife,
"`G. Fox spoke of these things as a man that had not been concerned.`"

The occasion upon which a warrant was issued against him was a
design which the priests had laid to take away his life,
for they had spread a report that in a certain meeting he had spoken blasphemy;
and in order to uphold this forgery, they had incited false witnesses.
The time of the court sessions at Lancaster having come,
G+++.+++ Fox went there with judge Fell,
who on the way told him that such a matter had never been brought before him,
and that he did not know what to do in such a case.
But G. Fox said, "`When Paul was brought before the rulers,
and the Jews and priests accused him of many false things,
he stood still all that while till they had finished; and when they had finished, Felix,
the governor, beckoned to him to speak for himself.
And so,`" said G. Fox, "`you may do with me.`"

Having come to the court sessions at Lancaster, some forty priests appeared against him,
and these had chosen one Marshal (priest of Lancaster) to be their speaker;
and the witnesses they had provided were a young priest, and two priests`' sons.
When the justices were set,
and had heard all the charges of the priests and the witnesses--which were,
that G. Fox had said that God taught deceit,
and that the Scripture contained but a parcel of
lies--then then witnesses were examined upon oath.
But these men were so confounded and at such a loss that one of them (not being able
to answer directly to what was asked him) said that the other could answer it;
which made the justices say, "`Have you sworn to it,
and now you say the other can answer it?
It seems you did not hear those words spoken yourself,
though you have given it in upon your oath.`"
Now there were several persons in the court who declared
that they had heard one of the two priests`' sons say that,
if he had power, he would make George deny his profession,
and that he would take away his life.
And the young priest, who also was a witness,
confessed that he would not have meddled with the thing had not
another priest sent for him and set him upon it.

After all the accusations had been heard,
several men of reputation in the country affirmed in court that no such
words as had been sworn against G. Fox were spoken by him at the meeting;
for most of the serious men on that side of the county
who were then at the sessions had been at that meeting,
wherein the witnesses swore he spoke the aforesaid blasphemous words.
Colonel West, being a justice of the peace, and then upon the bench,
was so well pleased with these evidences, that he,
(having long been weak in body) said he blessed the Lord that had healed him that day;
adding, that he never saw so many sober people, and good faces together in all his life.
And then turning himself to G. Fox, said, "`George,
if you have anything to say to the people, you may freely declare it.`"
He then began to speak, but priest Marshal, the orator for the other priests,
presently left the room.
Now that which G. Fox declared, was,
that the Holy Scriptures were given forth by the Spirit of God,
and that all people must first come to the Spirit of God in themselves,
that by this they might know God and Christ,
of whom the prophets and apostles had learned, and also know the Holy Scriptures.
For as the Spirit of God was in those that gave forth the Scriptures,
so the same Spirit of God must also be in those that
come to know and understand the Scriptures;
and it is by this Spirit that they might have fellowship
with the Father and with the Son,
and with one another; but without this Spirit, they could neither know God nor Christ,
nor the Scriptures, nor have right fellowship with one another.
No sooner had he spoken these words,
but about half a dozen priests burst out into a passion, and one of them,
whose name was Jackus, said that the Spirit and the letter were inseparable.
This made G. Fox answer, "`Then everyone that has the letter, also has the Spirit;
and they might buy the Spirit along with the letter of the Scripture.`"
To which judge Fell and colonel West added, that according to this position,
a man might carry the Spirit in his pocket, as he did the Scriptures.
The justices also bid Jackus to prove what he had said.
But finding himself caught, he tried to deny it,
and some other priests endeavored to disguise his words with a pretended meaning.
But the justices would allow no other meaning than the plain sense of the words.
And seeing the witnesses did not agree,
and perceiving that they were set to work by the envy of the priests,
they discharged him,
and after judge Fell had spoken to the justices Sawrey and Thomson
concerning the warrant they had given forth against G. Fox,
showing that it tended to encourage such riots as those in the Isle of Walney,
he and colonel West granted an annulment, to stop the execution of the said warrant.

G+++.+++ Fox, being thus cleared in open sessions,
many people rejoiced and were that day convinced
of the Truth declared by him in the court;
and among these, one justice Benson, and the mayor of Lancaster whose name was Ripan;
also one Thomas Briggs, who had formerly been very averse to,
and an opposer of the Quakers (so called).
And this same Briggs afterwards became a faithful minister of the gospel among them,
and remained so to the end of his days.

G+++.+++ Fox stayed yet some days at Lancaster,
but to relate all that he and his friends met with is not my intention;
for to set down in detail all such occurrences would be a work
requiring more leisure and strength than can be expected from me.
And therefore I intend only to describe what I find most remarkable,
though many notable things have also happened of which I could
not fully be informed in every circumstance as to name,
place, time, etc.
But perhaps this may give occasion in England for some other author after
me to publish such discoveries as will cause their posterity to wonder.
For the great abuses which G. Fox met with,
were also the share of many others of his friends, especially the preachers,
who this year were not less than twenty-five in number.
And in almost every place where they came, they met with opposition,
and became (as it were) the prey of the rude multitude.
But neither the beatings, buffetings, or stonings of the mad rabble,
nor the jails and whippings that befell them from the magistrates,
were able to stop the progress of the truth they preached to the people in markets,
streets, and also in steeple-houses.
And many of even those who had been enraged like wolves,
became afterwards to be like lambs;
and patiently suffered from others what they themselves, in a blind zeal,
had formerly committed.

Thus the Quakers (so called), by a firm and lasting patience,
have surmounted the greatest difficulties, and have at length become a numerous people,^
footnote:[At the time of this writing, which was around 1715.]
many not valuing their own lives when they met with
any opportunity for the service of God.
And though their enemies on this account have charged them with stubbornness and obstinacy,
yet they meekly resigned to whatever befell them,
well knowing that to be thus accused has always been the
lot of those who suffered for the testimony of truth.
Neither could they be charged with resistance or making opposition against their persecutors;
for a single man did sometimes lead a great many of them to prison,
though they never forsook their religious assemblies, however hot the persecution was.
That this was also the practice of the primitive Christians, appears by what Cyprian,
who died a martyr, wrote to Demetrian: "`They could have resisted, and that unto blood,
but they had not so learned Christ.`"
But let not my reader think that these I have described
have been the greatest sufferings of this harmless people;
for I believe them to have been a hundred times more than my pen is able to mention.
But now I take up again the thread of my relation.

G+++.+++ Fox being acquitted by the court, as has been said,
it made the priests fret to hear it spread abroad that the Quakers had won the day.
To avenge this, they got some envious justices to join with them,
and at the following court session at Lancaster complained
to judge Windham against G. Fox,
which so prevailed upon him that he commanded colonel West (who was clerk
of the court session) to issue a warrant for apprehending him.
But colonel West told the judge of George`'s innocency, and spoke boldly in his defense.
Being offended at this, the judge commanded him again to either write a warrant,
or step down from his seat.
Then the colonel told him in plain terms that he would not do it,
but that he would offer up all his estate and also his body for G. Fox.
Thus the judge was stopped.
But G. Fox coming that night to Lancaster,
heard that a warrant was to be issued against him,
and therefore judged it better to show himself openly
than to make his adversaries seek him.
So he went to the chambers of judge Fell and colonel West, and as soon as he came in,
they smiled, and the colonel said, "`What!
Have you come into the dragon`'s mouth?`"
But G. Fox was always undaunted, and was not one to flinch in danger.
So he stayed some days in town, and walked up and down without being meddled with,
or questioned by any.

Yet his Friends in the meantime did not cease to suffer;
for all the villainy or insolence that could be thought up against them,
was judged by some not sufficient to afflict them.
It was about this time that Richard Hubberthorn and several
others were hauled out of a meeting by some wicked men,
and carried some distance off in the fields,
where they were bound and left in middle of the winter season.

G+++.+++ Fox being now having come again to Swarthmore,
wrote several letters to the magistrates and priests who had raised persecutions thereabouts.
That to justice John Sawrey, was very sharp, and after this manner:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You were the first to begin all the persecution in the North.
You were the first to stir up men against the righteous seed,
and against the truth of God;
and the first to strengthen the hands of evil-doers against the innocent and harmless;
and you shall not prosper.
You were the first to stir up strikers, stoners, persecutors, stockers, mockers,
and imprisoners in the North; and also revilers, slanderers, railers, false accusers,
and scandal-raisers.
This was your work, and this you have stirred up!
So your fruits declare your spirit.
Instead of "`stirring up the pure mind`"^
footnote:[2 Peter 3:1]
in the people, you have stirred up the wicked, malicious and envious,
and taken part with the wicked.
You have made the people`'s minds envious, up and down the country; this was your work.
But God has shortened your days, and limited you, and set your bounds,
and broken your jaw, and uncovered your religion to the simple and babes,
and brought your deeds to light.

How has your habitation fallen and become the habitation of devils!
How is your beauty lost, and your glory withered!
How have you served God with your lips, though your heart is far from Him!
How has your teaching showed itself to have the mark of the false prophets,
whose fruit declares itself!
You shall have your reward according to your works.
You cannot escape; the Lord`'s righteous judgment will find you out,
and the witness of God in your conscience shall answer it.
How have you caused the heathen to blaspheme, going on with the multitude to do evil,
joining hand in hand with the wicked!
How are you exalted and puffed up with pride!
And yet how have you fallen down with shame,
and come to be covered with that which you stirred up and brought forth.
Let not John Sawrey take the words of God into his mouth, until he has reformed.
Let him not take His name into his mouth, until he has departed from iniquity.
You have a form of godliness, but not the power,
and have made them that are in the power the object of your derision, your bye-word,
and your talk at your feasts.
Your ill savor, John Sawrey, the country around you has smelled,
and all who fear God have been ashamed and grieved at your unchristian behavior.
In the day of account you shall know it, even in the day of your condemnation.
You mounted up, and set your nest on high, but never got higher than the fowls of the air.
But now you have run among the beasts of prey, and have fallen into the earth;
so that earthliness and covetousness have swallowed you up.

[.signed-section-signature]
G+++.+++ Fox

--

Strong indeed was this letter; but G. Fox thought himself moved by the Lord to write it.
And it is remarkable that this justice Sawrey,
who was the first persecutor in those parts, afterwards was drowned,
and so died not a natural death.
He wrote also to the priest William Lampitt, and another letter to others,
to reprove them for their wickedness.

Some time after this he went to Westmoreland, where mischief was intended against him,
but it was prevented by justice Benson and some others.
Coming to Grayrigg, he had a meeting there where a priest came to oppose,
saying first that the Scriptures were the word of God.
To this G. Fox said, "`They are the words of God, but they are not Christ,
who is the Word.`"
And when he urged the priest to prove what he had said, he was at a loss,
and soon went away.

The year now coming to an end, and a war having been kindled between England and Holland,
King Charles II. (then in exile) asked permission of the
Dutch to be received in their navy as a volunteer,
without any command; but this was courteously refused by the States General.
Oliver Cromwell in the meantime, strove for the supreme authority in England,
more especially because he perceived that some of the parliament (who were jealous
of his increasing greatness) endeavored to cross him in his design.
This made him labor to get the parliament dissolved.
But things not progressing as quickly as he would have them,
in order to put an end to their term, he resolved arbitrarily to dismiss them.
And so, entering the house in the month called April, 1653,
having rudely censured them for the misuse of their authority,
and insisting that without their dissolution the kingdom would not be safe,
etc. he at length cried out, "`You are no parliament!`"
Then ordering some musketeers to enter, he made the members depart the house,
and gave orders the doors be shut;
thus putting an end to an assembly that had been sitting near thirteen years.

But what is remarkable, G. Fox not long before this having come to Swarthmore,
and hearing judge Fell and justice Benson discoursing together concerning the parliament,
he told them, "`Before two weeks have passed, the parliament will be broken up,
and the speaker will be plucked out of his chair.`"
And so it really happened; for at the breaking up of the parliament,
the speaker being unwilling to come out of his chair,
said he would not come down unless he were forced.
This made general Harrison say to him, "`Sir,
I will lend you my hand;`" and thereupon taking him by the hand, the speaker came down.
This agreed with what G. Fox had predicted,
and so caused justice Benson to say to judge Fell,
that now he saw George was a true prophet.

Now in Cumberland great threats were spread abroad that if ever G. Fox came there again,
they would take away his life.
Hearing this, he went there; but nobody did him any harm.
Returning then to Swarthmore, where justice Anthony Pearson was at that time,
he so effectually declared the truth, that this justice was convinced,
and not long after entered into the society of the despised Quakers.

G+++.+++ Fox then, going again into Cumberland, went to Bootle,
and there found a priest from London preaching in the steeple-house,
who gathered up all the Scriptures he could think of that speak of false prophets,
antichrists, and deceivers, and made application of them all to the Quakers.
But when he had finished, George began to speak,
and returned all those Scriptures back upon the priest; who being displeased at this,
said that he must not speak there.
But G. Fox told him that his hour-glass had run,^
footnote:[At this time,
an hourglass was used by priests to measure the length of their sermon.]
and since he had finished, the time now was free for him,
as well as for the priest (who was himself but a stranger there).
Having said this, he went on and showed who the false prophets were,
and what marks the scriptures gave them, directing the people to Christ their teacher.
When he had finished,
the priest of the place made a speech to the people in the steeple-house yard, and said,
"`This man has gathered all the honest men and women in Lancashire to him;
and now he comes here to do the same.`"
To which G. Fox replied, "`What then will you have left?
And who will be left with the priests, but such as themselves?
For if it is the honest who have received the Truth and have turned to Christ,
then it must be the dishonest that follow you, and are such as you are.`"
Then some words were exchanged about tithes,
and G. Fox told them that Christ had ended the tithing priesthood,
and had sent forth His ministers to give freely, even as they had received freely.

From there he went to Cockermouth, where he had appointed a meeting.
And coming there, he found James Lancaster speaking under a tree,
which was so full of people that it was in danger of breaking.
G+++.+++ Fox looked around for a place to stand upon,
for the people were spread about up and down.
But at length a person came to him and asked if he would not go into church.
Seeing no place more convenient to speak to the people, he told him, "`Yes.`"
Whereupon the people rushed in suddenly,
so that the house was so full of people he had much difficulty to get in.
When they were settled he stood up on a seat, and preached about three hours;
and several hundreds were convinced that day of the truth of this doctrine.

From there he went to other places, and particularly to Brigham,
where he preached in the steeple-house with no less success.
Coming afterwards into a certain place, and casting his eye upon a woman unknown to him,
he told her that she had lived a lewd life;
to which she answered that many could tell her of her outward sins,
but none could speak of her inward sins.
He then told her that her heart was not right before the Lord, and she was so reached,
that she afterwards came to be convinced of God`'s truth.

Coming then near Coldbeck, to a market town, he had a meeting at the market cross,
and some received the truth preached by him.
From there he went to Carlisle, where the teacher of the Baptists,
with most of his hearers, came to the abbey where G. Fox had a meeting.
After the meeting the Baptist teacher (who was a notionist,
and an airy man) came to him and asked what it was that must be damned?
George told him, "`That which speaks in you is to be damned.`"
This stopped his mouth.
Then George opened to him the states of election and reprobation,
so that he said he had never heard the like in all his life,
and came afterwards also to be convinced of the Truth.

He then went up to the castle among the soldiers,
who by beating of the drum called the garrison together.
Among these he preached,
directing them to the measure of the Spirit of Christ in themselves,
by which they might be turned from darkness to light, and from the power of Satan to God.
He also warned them not to do violence to any man.
Having thus discharged himself, none opposed him, except some sergeants,
who afterwards came to be convinced.
On the market-day he went into the market,
though he had been threatened that if he came there, he would meet with rude treatment.
But desiring to obey God more than man, he showed himself undaunted,
and going upon the cross,
declared that the day of the Lord was coming upon all deceitful ways and doings,
and all deceitful merchandise; and that they should put away all swindling and cheating,
and keep to yes and no, and speak the truth to one another.

On the First-day following, G. Fox went into the steeple-house,
and after the priest had finished he began to preach.
The priest having left, the magistrate requested G. Fox to depart, but he went on,
telling them he came to speak the word of life and salvation from the Lord among them.
And he spoke so powerfully that the people trembled and shook,
and they thought the steeple-house shook also; indeed,
some of them feared it was about to fall down on their heads.
In the meantime, some women made a great bustle,
and at length the rude people of the city arose and
came with staves and stones into the steeple-house,
whereupon the governor sent some musketeers to appease the tumult.
These, taking G. Fox by the hand in a friendly manner, led him out.
Then he came to the house of a lieutenant, where he had a very quiet meeting.

The next day the justices and magistrates sent for him to come before them in the town-hall,
where he had a long discourse with them concerning religion,
showing them that though they were great professors
of Christianity (both Presbyterians and Independents),
yet they were without the possession of what they professed.
But after a long examination they committed him to prison as a blasphemer, a heretic,
and a seducer.
There he lay till the court session came on,
and then the talk of the land was that he was to be hanged; indeed,
the high sheriff Wilfrey Lawson was so eager to have his life taken away,
that he said he would bring G. Fox to execution himself.
This made such a noise in those parts that even high-class ladies came to see him,
as one that was about to die.
But though both judge and magistrates were contriving how they might put him to death,
yet the judge`'s clerk advanced a question which puzzled them and confounded their counsels,
so that he was not brought to a trial as was expected
(which nevertheless was contrary to law).
But such was their envy against him,
that the jailer was ordered to put him among the thieves and murderers,
and some evil women,
which wicked crew were so covered with lice that one woman was almost eaten to death.
But what made the prison even worse, was there was no latrine,
and in this nasty place men and women were put together against all decency.
Yet these prisoners, however depraved, were very loving to G. Fox,
and so hearkened to his wholesome counsel, that some of them became converts.
But the under-jailer did him all the mischief he could.
Once when he had been near the bars to receive the food his friends had brought him,
the jailer fell to beating of him with a great club, crying,
"`Come out of the window!`" though he was then far enough from it.
But while the jailer was thus beating him,
he was so filled with joy that he began to sing, which made the other rage all the more,
so that he went and fetched a fiddler, thinking thereby to annoy him.
But when this fellow played, George sang a hymn so loud,
that with his voice he drowned out the sound of the fiddle,
and thereby so confounded the player that he was made to give up and go his way.

Not long after this,
Justice Benson`'s wife felt herself moved to eat no food but what
she would eat with G. Fox at the bars of the dungeon-window.
And afterwards she herself was imprisoned at York when she was expecting a child,
for having (it seems) spoken zealously to a priest.
And when the time of her travail came, she was not permitted to go out,
but delivered her child in the prison.

While G. Fox was in the dungeon at Carlisle, there came to see him one James Parnell,
a little lad of about sixteen years of age;^
footnote:[From his own writings, it is evident that prior to this encounter,
James Parnell had already experienced a real conversion of heart, having,
at around fourteen years of age, been brought to see the formality of the priests,
and separated himself from the customary form of worship to wait on the Lord alone;
so that by this interview with George Fox,
he was merely convinced that the Truth which Fox preached was the same
as that into which he had himself been led by the Spirit of Truth.]
and he was so effectually reached by the words of G. Fox
that he became convinced of the truth of his sayings.
And notwithstanding his youth,
this boy was quickly made by the Lord a powerful minister of the gospel,
showing himself both with his pen and his tongue to be a zealous promoter of religion,
although he underwent hard sufferings on that account, as will be mentioned hereafter.

There were also many others at this time who,
not allowing themselves to be hindered by any adversities,
came to be zealous preachers of repentance.
Among these was Thomas Briggs, already mentioned, who went through many cities, towns,
and villages with this message: "`Repent, repent,
for the mighty terrible day of the Lord God of power is appearing,
wherein no worker of iniquity shall stand before Him,
who is of purer eyes than to behold iniquity; for He wills not the death of a sinner,
and if you repent and turn to Him, He will abundantly pardon.`"
Sometimes he went into markets and steeple-houses, and was often cruelly abused.
Once being in a steeple-house at Warrington in Lancashire,
and speaking a few words after the priest had finished,
he was very violently knocked on his head; after which, a man taking hold of his hair,
struck him against a stone, and pulled off a handful of it.
Upon which, taking up his hair from the ground, Thomas said mildly,
"`Not one hair of my head shall fall to the ground without my Father`'s permission.`"
At another time, after speaking to a priest in Cheshire,
as he was continuing on his journey,
the priest made it known that he was much offended at him; so that one of his hearers,
in a supposed revenge for this pretended offense,
struck Thomas on the head and knocked him down.
But getting up again, and turning his face to the smiter,
he was then struck on the teeth so that the blood gushed out exceedingly,
which some of the witnesses could not help but cry out against.
But not long after this, the man who struck him fell sick, and when dying,
cried out upon his deathbed, "`Oh that I had not struck the Quaker!`"
Once when going through Salisbury, and calling the inhabitants to repentance,
this Thomas was apprehended and brought before several
justices who required him to take the oath of allegiance^
footnote:[An oath established in 1606 by King James I.,
by which citizens were required to swear loyalty to the king of England,
and disavow all power or policy that the Pope or
Church of Rome might claim to depose the king.]
under pretense of his being a Jesuit.
But Thomas saying he could not swear,
because Christ had commanded that he "`Swear not at all,`"^
footnote:[Matthew 5:34]
was sent to prison, where he was kept a month.
He also went up and down the streets of Yarmouth,
proclaiming the terrible day of the Lord,
that all might repent and fear Him who made heaven and earth and the sea.
And being followed by a great multitude of rude people,
he turned about and spoke so powerfully to them, and with such piercing words,
that they ran away for fear.
At length an officer came and took hold of him, but leading him gently,
he had opportunity to continue preaching to the people and to clear his conscience.

When he came to Lynn and warned people to repent, a great mastiff dog was set upon him,
but the dog coming near him, behaved friendly towards him.
Thus he went through many places, passing sometimes five or six towns in one day;
and though swords were drawn against him, or axes taken up to strike him down,
yet he went on, and spoke with such dreadful power,
that even some who did not see his face were so reached
by the power that accompanied him,
that they became converts.
Coming to Clayzons in Wales, and finding many listening to him attentively,
the constable stirred up the rude people and cried, "`Kill him;
Kill him;`" as if he had been a mad dog.
Here they threw such large stones upon him, that he was astonished they did not kill him;
but he was preserved by such a mighty power that the stones
(according to his account) were to him as a nut or a bean.
He met with many other rude encounters,
but was preserved wonderfully in the greatest of dangers;
which strengthened him not a little in the belief that God,
who so miraculously saved him, did require this service from him.
He went also to America, and died at a good old age,
after having labored above thirty years in the service of the gospel.

Miles Halhead was also one of the first zealous preachers among the Quakers (so called),
and was the first of his persuasion to be imprisoned at Kendal.
Once as he went to Swarthmore to visit his friends, and to assist at their meeting,
he met by the way the wife of the justice Thomas Preston;
and because he passed by her quietly without the ordinary way of greeting,
she grew so offended that she commanded her servant to go back and beat him;
which he did.
At this, being kindled with zeal, Miles said to her, "`O you proud Jezebel!
Can you not allow a servant of the Lord to pass by you quietly?`"
She then held forth her hand as if she would have struck him, then spit in his face,
saying, "`I am untouched by your words.`"
This made Miles say again, "`You proud Jezebel,
who harden your heart and brazen your face against the Lord and his servant;
the Lord will plead with you in His own time,
and set in order before you the things that you have done this day.`"
And so he parted with her, and went to Swarthmore.
About three months after this, he felt himself moved to go and speak to her;
and when he had come to Houlker Hall, he asked for Thomas Preston`'s wife.
She then coming to the door,
and Miles not immediately recognizing her (being perhaps in different dress),
asked her if she were the woman of the house; to which she said, "`No,
but if you desire to speak with Mrs.
Preston, I will entreat her to come to you.`"
She then went in, and coming back with another woman, said, "`Here is mistress Preston.`"
But then it was manifested to Miles that she herself was the woman, and he said, "`Woman,
how dare you lie before the Lord?
You are the woman I came to speak to.`"
And she being silent and not speaking a word, he proceeded,
"`Hear what the servant of the Lord has to say unto you: O woman,
harden not your heart against the Lord; for if you do,
he will cut you off in His sore displeasure.
Therefore take warning in time,
and fear the Lord God of heaven and earth that you may end your days in peace.`"
Having said this, he went away,
she being withheld (not knowing by what) from doing him any harm.
But notwithstanding this warning, she continued the same;
for it happened that several years after this, when G. Fox was prisoner at Lancaster,
she came to him and belched out many abusive words,
saying (among the rest) that his tongue should be cut off, and he should be hanged.
But some time after this the Lord cut her off, and she died, as it was reported,
in a miserable condition.

But before I leave this woman,
I must also say that about three years after she had made her servant beat Miles,
it happened that as he was riding from Swarthmore, near to Houlker Hall,
he met with a person who said to him, "`Friend, I have something to say unto you,
which has lain upon me this long time.
I am the man that, about three years ago, at the command of my mistress,
did beat you very severely; for which I have been very much troubled,
more than for anything that I ever did in all my life.
For truly,
night and day it has been often in my heart that I did wrong in beating an innocent man,
who never did me any hurt or harm.
I pray you forgive me, and I desire the Lord to forgive me,
that I may be at peace and quiet in my mind.`"
To this Miles answered, "`Truly friend, from that time to this day,
I never had any thing in my heart against you, nor your mistress, but love.
The Lord forgive you both.
I desire that it never be laid to your charge; for you knew not what you did.`"
Here Miles stopped, and so went on his way.

Traveling once in Yorkshire, he came to Skipton, where declaring the word of truth,
he was so sorely abused and beaten, that he was left for dead.
Nevertheless, by the Lord`'s power, he was healed of all his injuries,
and within three hours was healthy and sound again,
to the astonishment of those that had so abused him,
and to the convincing of many that beheld him.
Then he went to Bradford, Leeds, and Halifax,
where he also declared the doctrine of truth among the people,
but not without meeting with great persecution.

From there he came to Doncaster,
and went on a First-day of the week to the steeple-house, where,
after the worship had finished, he spoke to the priest and people.
But instead of hearkening to what he said, they fell upon him in a great rage,
and drove him out of the town; and being so sorely bruised, he was again left for dead.
But before he had left his home,
he had been firmly persuaded that the Lord would preserve him in all dangers.
And so it happened to him according to his belief; for he got up again,
and went to a friend`'s house, where he laid himself down upon a bed.
But not long after, he felt a very strong motion to go to a certain chapel,
and there to declare the word of the Lord,
feeling also an inward assurance that if he gave up to do so,
the Lord would heal him from his bruises.
Thereupon he arose as well as he could, and came down the stairs with great difficulty,
taking hold of the walls for a stay.
And going out of the house, he began to mend by degrees;
and coming at length into the chapel, he spoke as he was moved,
and when he had cleared himself, he went back to the house from which he came,
and the Lord made him sound of all his wounds and bruises.

From there he went to York and spoke to the lord mayor and other rulers of that city.
Then passing through Yorkshire, he went into several steeple-houses to exhort the people,
and though he met with great hardships, yet he was supported by an invisible hand.
Feeling clear of that country, he returned to his house at Mount-joy, in Underbarrow,
in the county of Westmoreland.
But his going so often from home, was an exceedingly great trial to his wife,
who in the first year after his change (not being of his
persuasion) was very much troubled in her mind,
and would often say from discontent, "`I wish to God I had married a drunkard,
then I might have found him at the alehouse;
but now I cannot tell where to find my husband.`"
But after the space of a year, it pleased the Lord to visit her.
She had a little son of about five years of age, which child she loved extraordinarily,
insomuch that she considered it her only delight and comfort.
But it happened that this dear child died,
and some time after this she spoke thus to her husband: "`Truly, husband,
I have something to tell you.
One night being in bed, mourning and lamenting with tears in my eyes, I heard a voice,
saying, '`Why are you so discontented concerning your husband?
I have called and chosen him to My work; My right hand shall uphold him.
Therefore be content and pleased that he serves Me,
and I will bless you and your children for his sake;
and all things shall prosper that you shall take in hand.
But if you will not be content, but grudge and murmur,
and repine against Me and My servant, whom I have chosen to do My work,
I will bring a greater trial upon you.`' These words
being fresh in my mind both night and day,
I often said within myself.
'`What trial could this be,
that would be greater than the absence of my husband?`' But for all this,
I would not be content.
All the joy I had, or could find, was in our little boy, who,
when he saw me weeping and mourning, would often hold me around my neck and say,
'`My dear mother, please be content,
for my father will come home in a little time.`'
This child would often comfort me in this manner;
but for all this I would not be content.
Not long after, it pleased the Lord to take from me this my only son, my chiefest joy.
Then the voice which I had heard came afresh into my mind,
and perceiving that this was the trial which the Lord would bring upon me,
I smote my breast, and said within myself,
that '`I was the very cause why the Lord had taken away
my little son.`' A great fear then seizing upon me,
and I said, '`O Lord, my God!
Give me power to be content to give up my husband freely to do Your will, lest, O Lord,
You take away from me all my children.`' From that time I have never dared oppose you,
my husband, anymore in the work of the Lord,
for fear that His judgments might also fall upon me and my children.`"
This served not a little to strengthen and encourage Miles.

Some time after this, walking in his garden,
he felt a motion to go to Stanley chapel in Lancashire.
And though he expected to meet with a rude reception there,
yet he consulted not with flesh and blood, but went to the aforesaid chapel.
Having come, he was not allowed to enter, but the door was violently shut against him.
He then walked in the yard till the worship had finished,
and the people then came out fell upon him with great rage,
and one captain William Rawlinson took hold of his arms and shoulders,
and calling another man to take him by the feet and legs, they threw him over the wall,
by which fall he was exceedingly bruised, so that he had great difficulty to get home.
On the way it was inwardly said to him,
that he must be content with what was befallen him that day,
and that if he was faithful in what the Lord required of him,
then He would heal him again.
Having come home, he waited upon the Lord to know His will.
In this state of resignation, within six days,
he was moved to go to Windermere steeple-house, and it was said unto him,
"`Fear not the face of any man, but speak the word of the Lord freely;
and then you shall be made sound again from all your bruises.`"
So he went to the said steeple-house,
and having spoken the word of the Lord to the priest
and people without receiving any harm,
he was healed that day of his sore bruises.

Some time after this, by another motion of the Lord, he came to Furness in Lancashire,
to the house of captain Adam Sands, where he found a great number of professors gathered,
and priest Lampitt preaching.
But as soon as Miles entered, Lampitt fell silent, and when he had continued so a while,
captain Sands said to him, "`Sir, what is the matter?
Are you not well?`"
To which the priest answered, "`I am well,
but I shall speak no more as long as this dumb devil is in the house.`"
"`A dumb devil,`" said the captain, "`where is he?`"
"`That is he,`" said the priest, pointing with his hand, "`who stands there.`"
Then the captain said, "`This man is quiet and has said nothing to you.
I pray you, sir, go on in the name of the Lord;
and if he troubles or molests you in my house, I will send him to Lancaster castle.`"
But the priest said again,
"`I shall not preach as long as this dumb devil is in the house.`"
Then the captain said to one Camelford, another priest, "`Pray sir,
you stand up and exercise your gift, and I will see that you are not disturbed.`"
But this priest answered like the other,
"`I shall not speak as long as this dumb devil is in the house.`"
Then some of the people cried out, "`The Lord rebuke you Satan; the Lord rebuke you Satan.
What manner of spirit is this that stops the mouths of our ministers?`"
Then the captain came to Miles, and taking him by the hand, led him out of the house.
In all this time he had not spoken a word,
but he saw now the accomplishment of what he had been shown before,
that an invisible power would by him confound the
wisdom of the priests without ever speaking a word.
This priest Camelford was one who, a good while before this,
had stirred up the rabble against G. Fox.
The other was the same Lampitt who has been mentioned already,
and who had been so esteemed by Margaret Fell before she was acquainted with G. Fox.

Some time after this occurrence, Miles went to Newcastle, and there said to the mayor,
the rulers, and the priests of that town,
that God`'s anger was kindled against them because
they had shut the kingdom of heaven against men,
and would not enter themselves, nor permit those who desired to enter.
Because of this he was imprisoned.
But the mayor being much troubled,
sent for the sheriff (for these two had committed Miles); and when he had come,
said to him, "`We have not done right in committing an innocent man to prison.
Come now, let us release him.`"
The sheriff giving his consent, Miles was set at liberty.
He then declared the word of the Lord in those parts,
and many were convinced of the truth held forth by him.
But now I part with this Miles Halhead, who hereafter will be mentioned again.

About this time, in the summer, general Oliver Cromwell had called a new parliament,
consisting mostly (as has been said by some) of members of his own choice;
for it was a certain number of persons out of each county and city in England, Scotland,
and Ireland, nominated by the council of officers,
and called together to meet at Westminister.
Into the hands of these, Cromwell delivered the supreme authority of the nation,
by a commission signed by himself and the officers.
But the authority of this assembly lasted scarce half-a-year,
as will be mentioned hereafter.

To this parliament a report was given,
that there was a person imprisoned at Carlisle who was to die for matters of religion.
This was G. Fox, whom we left thus long in the dungeon at Carlisle,
and now are returning to him again.
The parliament then caused a letter to be sent down
to the sheriff and other magistrate concerning him.
And G. Fox,
knowing how scandalously he had been represented as having spoken blasphemous words,
gave forth a paper,
wherein he challenged all who found fault with his doctrine to appear in public,
since he was willing to have put to the test whatever he might have spoken.
He also wrote a significant letter to the justices at Carlisle,
wherein he showed them plainly the injustice of their dealings,
and the horrid evil of persecution, as having always been the work of the false church.
Mention has been made already of the justices Benson and Anthony Pearson;
these had sought permission, on more than occasion, to visit G. Fox in prison;
but this having been denied them, they wrote a letter to the magistrates, priests,
and people at Carlisle,
wherein they emphatically described the wickedness of persecution,
and what would be the reward of persecutors.
They showed also,
that these persecutors were worse than the heathen that put Paul into prison,
because none of his friends or acquaintance were hindered by them from coming to him.
However,
at length Anthony Pearson got an opportunity to come with
the governor into the dungeon where G. Fox was kept,
and they found the place so bad, and of so foul a smell,
that the governor cried shame on the magistrates for allowing
the jailer to treat G. Fox in such a manner.
And then, calling the jailers into the dungeon,
he required them to post bond for their good behavior,
and put the under-jailer (who had been very cruel
to G. Fox) into the dungeon along with him.
In the meantime, those who had imprisoned G. Fox began to grow afraid,
perhaps more so because the parliament took notice of these doings;
and it was not long after that he was released.

Then coming to the house of one Thomas Bewly, near Coldbeck, in Cumberland,
there came a Baptist teacher to oppose him.
But this man found what G. Fox spoke to be so efficacious,
that he became convinced of the truth thereof.
There was then a man named Robert Widders, who was moved to go to Coldbeck steeple-house,
and this Baptist teacher went with him.
Coming into the steeple-house,
Widders began to speak to one priest Hutton who was preaching;
but the rude people threw him down and dragged him into the yard,
where they pushed and beat him till the blood gushed out of his mouth,
and he lay as one dead for some time.
But a certain woman coming to him, held up his head,
so that at length he recovered his breath.
The Baptist teacher who had gone along with him, had his sword taken from him,
and was sorely beaten with it.
Yet this did not frighten or discourage him; and he not only left off wearing the sword,
but also freely gave up the inheritance of an income of tithes.

The same day that this preacher was thus attacked
with his own sword (being the first of the week),
several of G. Fox`'s friends, and among them, William Dewsbury,
went to various other steeple-houses, and by this means,
the number of the friends increased in those parts;
though Dewsbury at that time was so violently beaten
by the people that he was almost killed;
but the Lord`'s power healed him.

But to return to Robert Widders;
having recovered from the rude treatment he had previously met with,
he felt himself so encouraged and strengthened in his undertakings,
that he went the same day in the afternoon seven miles to Ackton steeple-house.
Here he spoke to priest Nichols, and called him an enemy of Christ,
telling him also that the hand of the Lord was against him.
Then William Briscoe, a justice of Crofton, commanded the constable to secure Robert;
which he did, and carried him to the priest`'s house.
Being examined by the justice there, the priest began to flatter him,
but Robert told the priest that the spirit of persecution lodged in him.
But the priest said, "`No, I am not such a man.`"
Yet soon after this priest said to the justice,
that Robert had stolen the horse upon which he came,
and that he could find in his heart to become his executioner with his own hands.
This made Robert say,
"`Did I not say unto you that the spirit of persecution lodged in you?`"
Then the aforesaid justice wrote a warrant to send Robert to Carlisle jail;
and after having given the warrant to the constable,
he asked Robert by what authority or power he came to seduce and bewitch the people?
Robert answered, "`I came not to seduce and bewitch people,
but I came in that power which shall make you, and all the powers of the earth,
bend and bow down before it, namely, the mighty power of God.`"
While Robert was thus speaking, the dread of the Lord seized up the justice,
and so struck him, that he called for the warrant again,
took it out of the constable`'s hand, and allowed Robert to go his way.

Being thus freed, he did not cease visiting the steeple-houses from time to time,
for which he was sometimes imprisoned, and at other times saved remarkably.
Once coming near Skipton in Yorkshire, at the steeple house,
he spoke very sharply to a priest named Webster,
knowing him to be one who had been partly convinced of the doctrine of the inward light,
but who, becoming disobedient to it, had turned back again.
He also spoke to the people, and to justice Coats,
bidding them to mind the Word of God in the heart
which divided between the precious and the vile.
After having cleared himself,
he went to a place where a few of his friends had met together;
but he had not been long there, when some horsemen and officers came and took him away,
and carried him before the said justice.
Upon examining him,
the justice said he had broken the law by disturbing the minister and the people,
and that he might send him a prisoner to York castle.
Robert answered, "`Send me to jail there, if you dare;
for I appeal to the witness of God in your conscience.`"
But this justice, being a moderate man, said,
"`I neither dare nor will;`" and taking Robert by the hand,
told him he might take his own time in going away.

To relate all the occurrences of this Robert Widders would be too tedious;
therefore I will only say that, as he was very zealous in speaking to the priests,
so he suffered very much in his estate,
because for conscience-sake he refused to pay them tithes.
On that account there was taken from him, at various times, the value of 143,
besides what he suffered for meetings, and for "`Sunday shillings`" (so called),
which also amounted to a considerable sum.
And this not only befell him, but it was the portion of many hundreds, no,
perhaps thousands of those of his persuasion.
Wherefore I will not undertake to relate all that might be mentioned of this kind;
for that would be beyond my reach.

However, by what has been said,
it may be seen by what means the Quakers (so called)
grew so numerous in those early times.
For on the one hand the Lord had raised up many zealous preachers; and on the other,
there were an abundance of people in England at that time who, having searched all sects,
could nowhere find satisfaction for their hungry souls.
And these, now understanding that God by His light was so near in their hearts,
began to take heed thereunto,
and soon found that this gave them far more victory over the corruption
of their minds (under which they had long groaned) than all the self-willed
worship which they had performed with zeal for many years.
And besides those who were thus prepared to receive
a greater manifestation of the way of life,
there were also many of a dissolute life, who being pricked to the heart,
and won over by the Christian patience of the despised Quakers,
became as zealous in doing good, as formerly they had been in working evil.

Perhaps some will think it was very indecent that they went so frequently to the steeple-houses,
and there spoke to the priests.
But whatever any may judge concerning this,
it is certain that these teachers generally did not bring forth the fruits of godliness,
as was well known to those who themselves had been priests,
and who freely resigned their ministry to follow Christ in the way of his cross;
and these were some of the most zealous against that
society among whom they formerly had ministered.
Yet they were not for using sharp language against any such teachers who,
according to their knowledge, truly feared God;
but were led to take aim chiefly at those who were only rich in words,
without bringing forth true Christian fruits and works of righteousness.
Hence it was that one Thomas Curtis, who was formerly a captain in the parliament army,
but who afterwards entered into the society of the people called Quakers,
wrote these words in a letter to Samuel Wells, priest of Banbury,
and a persecutor of those of that persuasion: "`To your shame,
remember I know you are scandalous.
How often have you sat up evening after evening playing cards,
and sometimes whole nights, playing, and sometimes compelling me to play with you,
for money.
Yet at that time you were called by the world '`a
minister,`' and now have become a persecutor,
etc.`"
None therefore need think it strange,
that those called Quakers looked upon such teachers as "`hirelings.`"
And that there was a great number of this sort,
appeared plainly when King Charles II. was restored;
for those who had formerly cried out against episcopacy
and its liturgy as false and idolatrous,
then became turn-coats, and put on the surplice^
footnote:[The white garment worn by the Episcopal clergy in England.]
to keep in the possession of their livings and benefits.
But by so doing, these hypocrites lost not a few of their auditors,
for this opened the eyes of many,
who began to inquire into the doctrine of the despised Quakers,
and saw that they had a more sure foundation,
and that this is what made them stand unshaken against the fury of persecution.

Let us again take up the thread of these events which concern G. Fox; who,
now traveling through many places in the north of England, had large meetings everywhere,
though he now and then met with opposition; sometimes from tongues,
and other times from hands.
At Derwentwater, in Northumberland, he fell into a dispute about perfection,
and to prove his position said that Adam and Eve were perfect before they fell,
and all that God made was perfect,
and that the imperfection came by the devil and the fall; but Christ,
who came to destroy the works of the devil, said, "`Be perfect.`"
To this, one of the professors answered that Job said,
"`Shall mortal man be more pure than his Maker?
The heavens are not clean in His sight.
God charged His angels with folly.`"
But G. Fox showed him his mistake, and told him that it was not Job who said so,
but one of those men that contended against him.
Then some professors insisted that the outward body was the body of death and sin.
But G. Fox replied that both Adam and Eve had an outward
body before the body of death and sin got into them;
and that men would still have bodies when the body of sin and death was put off again,
and were renewed into the image of God again by Christ Jesus.

Thus G. Fox found work almost everywhere, and passing to Hexham,
he had a large meeting there on the top of a hill.
The priest there had threatened to come and oppose, but he did not come.
Traveling on, G. Fox then came into Cumberland,
where he had a meeting of many thousands of people on a hill near Langlands.
Once he came into Brigham steeple-house before the
priest was there and declared the Truth to the people.
When the priest came in, he began to oppose,
but was so wearied that at length he went away.

There being now several others who also preached the doctrine
of the inward light of Christ that convinces man of sin,
the number of professors of the light greatly increased.
And as it had been said at first that they should be destroyed within a short time,
so now the priests began to say that they would impoverish one another.
For after meetings, many of them having a long way to go,
stayed at their friends`' houses along the way,
and sometimes there were more people than beds to lodge,
so that some would lay on piles of hay.
This made some from the national church grow afraid
that such hospitality would cause poverty,
and that when these friends had eaten out each others`' provisions,
they would need to be maintained by the parishes, and so be chargeable to them.
But it turned out quite otherwise, for these people were the more blessed,
and greatly increased without falling into poverty.
This puts me in mind of what one of the daughters of judge Thomas Fell once told me,
namely, that her father having been abroad, and coming home with his servants,
found the shed so full of the horses of strangers that he said to his wife,
"`This is the way to be ruined, for soon we shall be in need of hay.`"
But to this Margaret said in a friendly way, that she did not believe,
when the year was at an end, that they should have any less for having shared.
And it so turned out;
for that year their stock of hay was so great that they
sold a great parcel of what they had in abundance.
Thus the proverb was verified,
that '`charity does not impoverish.`' The truth of this
was also experienced by the people called Quakers;
for though many people at first were shy and would not deal with
them because of their nonconformity with the common salutations,
and their saying _Thee_ and _Thou_ to a single person, instead of _You_,
etc. insomuch that some who were tradesmen lost their customers,
and could hardly get enough money to buy bread; yet this changed in time,
when people found by experience they could better trust the word of this people,
than that of their own persuasion.
Hence it was, that often when any came into a town and needed something, they would ask,
"`Where is there a draper, or tailor, or shoemaker, who is a Quaker?`"
But this so exasperated some others, that they began to cry out,
"`If we let these Quakers alone,
they will take the trade of the nation out of our hands.`"
Now the cause of their trade`'s thus increasing,
was because they were found to be upright in their dealings;
for integrity did then shine among them above many others.
And indeed, it was the fear of God that led them into this practice,
and they exhorted one another to it from time to time.
G+++.+++ Fox also wrote a general epistle to them, which was as follows:

[.embedded-content-document.epistle]
--

[.salutation]
To you all, Friends everywhere, scattered abroad:

In your measure of the life of God, wait for wisdom from God,
even from Him from whom it comes.
And all you who are babes of God, wait for the living food from the living God,
in order to be nourished up to eternal life, from the one fountain from which life comes.
Thus you may all be guided, and walk orderly and in order; servants in your places,
young men and young women in your places, and rulers of families; that everyone,
in your respective places may adorn the Truth, everyone in their measure of it.
Let your minds be kept turned to the Lord Jesus, from whom truth does come,
that you may be a sweet savor to God, and be ordered and ruled in wisdom,
that you may be a crown and a glory one to another in the Lord.
And let no strife, or bitterness, or self-will appear among you,
but condemn all such things with the light, in which is the unity.

And let every individual see to,
and take care for the ordering and ruling of their own family,
that it may be governed in righteousness and wisdom,
with the fear and dread of the Lord set in everyone`'s hearts,
that all may come to receive the secrets of the Lord, and become stewards of His grace,
to dispense to everyone as they have need.
Thus you shall all be kept in the savor of right discernment,
so that nothing which is contrary to the pure life
of God may be brought forth in you or among you,
but all that is contrary to it may by it be judged.
Thus you may all live in light, in life, and love, and all that is contrary to the light,
and life, and love, may be brought to judgment, and by the light be condemned.
And thus no fruitless trees will be among you;
but all such will be cut down and condemned by the light, and cast into the fire,
so that everyone may bear and bring forth fruit unto God,
and grow fruitful in His knowledge and in His wisdom.
And let none appear in words beyond what they are in the life that gave forth the words.
In this way none shall be as the untimely figs, or be of those trees whose fruit withers;
for these go in the way of Cain, away from the light,
and so by the light they are condemned.
And let none among you boast above your measure,
for in doing so you exclude yourself from God`'s kingdom.
For pride rises up in the boasting part, and strife,
which is contrary to that light which leads to the kingdom of God,
and gives an entrance thereto,
and an understanding to know what belongs to the kingdom of God.

Let no image or likeness be made,
but wait in the light that will bring condemnation on the part that would make images;
for that part holds down the Just One.
And do not yield your eye or your flesh to the lust,
for the pride of life stands in that which keeps you out of the love of the Father,
and upon this His judgments and wrath abide.
For where men seek after the love of the world, and the mortal crown, there evil enters,
which is cursed, and brings forth briars and thorns.
Here death reigns, and tribulation and anguish are upon every soul,
and the Egyptian tongue is heard; all of which is condemned by the light.
And here is that earth which must be removed, as it is seen by the light,
and shaken out of its place, and removed by the power.
Therefore all you whose minds are turned to this light,
(which brings condemnation upon all those things before-mentioned,
which are contrary to the light),
wait upon the Lord Jesus for the crown which is immortal, and which fades not away.

[.signed-section-signature]
G+++.+++ F.

--

This epistle was sent to be read at the meetings of his friends.
Not long after, a certain priest of Wrexham in Wales, whose name was Morgan Floyd,
sent two of his congregation into the north of England
to inquire what kind of people the Quakers were.
These two coming there, were convinced of their doctrine and embraced it;
and then after some stay, they returned home.
One of these was called John ap John,
a man who continued faithful and became a minister of the gospel he had thus received.
But the other afterwards departed from his convincement.

Let us now take a short view of state affairs in England.
We have seen already how Cromwell`'s power had become so
great that he ventured to dissolve the long parliament,
and that he called another in its place.
But before the year`'s end,
this Parliament resigned their power into the hands of Cromwell,
from whom they had received it.
Thus he, with his council of field officers,
saw himself again in the possession of the supreme government.
And it was not long before this council declared:
"`that henceforth the chief rule of the nation should be entrusted to a single person,
and that this person should be Oliver Cromwell,
chief general of all the forces in England, Scotland, and Ireland;
that his title should be '`Lord Protector of the Commonwealth`' of England, Scotland,
and Ireland, and all the dominions belonging thereunto;
and that he was to have a council of twenty-one persons to assist him in the government.`"

The matter being thus stated, the Commissioners of the Great Seal, the Lord Mayor,
and Aldermen of London were required to attend Cromwell
and his council on the 16th of December in Westminster-hall.
Having come there,
Cromwell stood with his hat off while the terms of government
(whereby he was declared Lord Protector) were read.
Then major-general Lambert, kneeling,
presented him with a sword in a scabbard representing the civil sword.
Cromwell accepting the sword, then put off his own,
to signify thereby that he would no longer rule by the military sword.
The said document being written on parchment, contained the following particulars:
"`That the Protector was to call a Parliament every three years;
that their first meeting should be on the 13th of September next ensuing;
that he should not be permitted to dissolve a parliament before it had sat five months;
that the bills presented to him for his consent,
if he did not confirm them within twenty days, should have the force of laws;
that he was to have a council, who were not to exceed twenty-one persons in number,
nor be less than thirteen; that immediately upon his death,
the council was to choose another Protector; that no Protector after him,
should be capable of being chief general of the army;
and that it should be in the power of the Protector to make war and peace.`"
While this document was being read, Cromwell held his hand on the bible,
and afterwards took the oath that he would perform all that was contained therein.
This being done, he put his hat back on his head, while all the others remained uncovered.
Then the commissioners delivered the seals to him,
and the Lord Mayor of London the sword;
all which he restored again with an exhortation to use them well.
Afterward general Lambert carried the sword before him to his royal couch,
in which he went to Whitehall, where he was proclaimed Protector,
which was also done in the city of London.
Henceforth he was attended like a prince, and created knights, as kings used to do.
Thus Cromwell, by a remarkable, and very strange turn of world affairs,
found himself placed in the palace,
from which he and his adherents had cast out King Charles the First.
