== Chapter IV

[.section-date]
1654

In the beginning of the year 1654,
seeing himself invested with the supreme authority of the nation,
Oliver Cromwell required the oath of fidelity, both of the soldiers and others.
This presented a convenient opportunity for those among the soldiers
who had been convinced of the doctrine of the Quakers (so called),
to leave the military service; for when the oath was tendered to them,
they declared that in obedience to Christ`'s command they could not swear;
whereupon they were dismissed.
Among these was John Stubbs, a man skilled not only in Latin, Greek, and Hebrew,
but also in the Oriental languages.
He was convinced by G. Fox when he was in Carlisle prison,
and afterwards became a faithful minister of the gospel.
But there were some of the soldiers who had been convinced in their judgment,
but did not continue steadfast, and so took the required oath.
Not long afterwards, marching into Scotland and passing by a garrison there,
some of these were fired upon (thinking they had been enemies),
whereby several were killed.

G+++.+++ Fox now seeing the churches of his friends in the North settled,
passed from Swarthmore (where he was about the beginning of this year) to Lancaster,
and from there to Synder-hill-green,
where he had a large meeting of some thousands of people,
among whom were many persons of note.
Here a great number were convinced,
so that many people entered into the communion of those called Quakers.
About about this time, Ambrose Rigge was also united to this people.
Having been inclined to godliness from his youth, upon hearing G. Fox preach,
he was convinced of the truth of his doctrine,
and received it and became a professor of it,
though for that reason he was cast out by his parents and relations.

We have seen the first rise of these Christians (called Quakers) in the North of England,
and how they increased under the oppression of persecution,
so that in most places in those parts meetings were settled.
It remains to relate how they spread further.

There were now about sixty ministers of the word raised up among them,
and these went out in the service of the gospel,
to turn people (wherever they found opportunity) from darkness to the light,
and from the power of Satan to God.
Of these, Francis Howgill and Edward Burrough went to London;
John Camm and John Audland went to Bristol;
Richard Hubberthorn and George Whitehead went to Norwich; Thomas Holmes went into Wales,
and others went other ways.
G+++.+++ Fox, well knowing this to be a weighty work, wrote a large epistle to these ministers,
wherein he admonished them to prudence,
advising them to know the seed of God in themselves which bruises the head of the serpent;
also to know the power of God, and the cross of Christ;
to receive wisdom from God by the light;
and not to be hasty or to run in their own wills, but to continue in patience.

I will first mention something of the occurrences at London,
where Edward Burrough and Francis Howgill,
with Anthony Pearson (who had been a justice of peace)
came in the fore-part of the summer.
Howgill and Pearson were the first of the people
called Quakers that had a meeting in this great city,
where they preached in the house of one Robert Dring, in Watling-street.
Edward Burrough, as I have been informed,
was that day in an assembly of a separate society.
Yet I have been told also, that Ruth, wife of William Crouch, merchant in London,
said that even somewhat before that time,
there had been meetings of a few persons in the same house, of whom she was one,
and also Anne Downer (afterwards married to George Whitehead).
It is also reported that one Isabella Buttery, with another woman,
having spread some books in London, and among them one of G. Fox`'s,
called The Way to the Kingdom, had met with this small company,
of which were but two or three men, one of which was Amos Stoddard,
formerly a military officer, mentioned already;
and at times the said Isabella Buttery spoke a few words in this small meeting.
But when Francis Howgill and Edward Burrough had come to London, things began change;
for they laid hold of all opportunities they could to preach the gospel.

At London there is a custom in summer time, when the evening approaches,
and tradesmen leave off work,
that many robust fellows meet in the fields to try their skill and strength in wrestling,
and generally a multitude of people stand gazing in a circle.
Now it so happened, that Edward Burrough passed by the place where they were wrestling,
and standing still among the spectators,
saw how a strong and dexterous fellow had already thrown three others,
and was waiting for a fourth champion, if any dared to enter.
At length, none being bold enough to try, E. Burrough stepped into the ring,
and having looked upon the wrestler with a serious countenance,
the man was not a little surprised; for instead of a strutting antagonist,
he met with a sober and solemn young man.
All stood as it were amazed at this sight,
eagerly expecting what might be the outcome of this combat.
But it was quite another fight that E. Burrough aimed at.
For having already fought against the spiritual wickedness
that had once prevailed over him,
and having overcome in measure by the grace of God,
he now endeavored also to fight against the same in others,
and to turn them from the evil of their ways.
With this intention, he began very seriously to speak to the bystanders,
and this he did with such heart-piercing power,
that he was heard by this mixed multitude with no less attention than admiration;
for this speech tended to turn them from darkness to the light,
and from the power of Satan to God.
He labored with convincing words, showing how God had not left Himself without a witness,
but had given to man a measure of His grace,
and enlightened everyone with the light of Christ.
Thus he preached zealously, and though many might look upon this as an oddity,
yet it was of such effect that some were convinced of the Truth.
For this Burrough was a breaker of stony hearts,
and therefore (by a certain author) was not unjustly called "`a son of thunder;`"
though he also failed not in due season to speak a word of consolation to those
that were of a broken heart and a contrite spirit.

But to thunder against sin and iniquity was his peculiar talent; insomuch,
that once preaching very zealously in a meeting,
and perceiving that there were some contrite souls
that needed spiritually-refreshing food,
he was heard to say that, though his present speaking was not milk for babes,
yet he would remember such shortly, and administer to them also;
but now he must thresh the harlot.
And indeed he was one of those valiants whose bow never turned back,
nor did his sword return empty from the slaughter of the mighty;
for the Lord blessed his powerful ministry with very glorious success.
Indeed, he was such an excellent instrument in the hand of God,
that even some mighty and eminent men were touched to the
heart by the power of the word of life which he preached.
And although coals of fire, so to speak,
came forth from his mouth to the consuming of briers and thorns,
and passing through unbeaten paths he trampled upon wild thistles and tares,
yet his wholesome doctrine dropped as the oil of
joy upon the spirits of mourners in Zion.
Hence it was that Francis Howgill not unjustly said of him when deceased, "`Shall days,
or months, or years, wear out your name, as though you had had no being?
Oh no!
Shall not your noble and valiant acts,
and mighty works which you have wrought through the
power of Him that separated you from the womb,
live in generations to come?
Oh yes!
The children that are yet unborn shall have you in their mouths,
and your works shall testify of you in the generations who yet have no being.`"

The said Howgill, also an eminent and eloquent man, being now at London,
went to court to utter what was in his mind to Oliver Cromwell.
And after having spoke to him,
he thought it convenient to express himself further in writing;
as he did in the following letter:

Friend, I was moved of the Lord to come to you, to declare the word of the Lord,
and deal plainly with you as I was commanded, and not to petition you for anything,
but to declare what the Lord had revealed to me concerning you.
And when I had delivered what I was commanded,
you questioned whether it was the word of the Lord or not,
and sought by your reason to put it off.
And now we have waited some days, but cannot again speak to you,
therefore I was moved to write to you and clear my conscience, and so to leave you.

Therefore hear the word of the Lord.
Thus says the Lord:
I chose you out of all the nations when you were little in your own eyes,
and threw down the mountains and the powers of the earth before you,
which had established wickedness by law.
I cut them down, and broke the yokes and bonds of the oppressor,
and made them stoop before you; and I made them as a plain before you,
so that you passed over them, and trod upon their necks.
But thus says the Lord, now your heart is not upright before Me. You take counsel,
but not of Me. You are establishing peace, but not by Me. You are setting up laws,
but not by Me; and My name is not feared, nor am I sought after,
but you establish your own wisdom.
What?
says the Lord, have I thrown down all the oppressors, and broken their laws,
and you are now going about to establish them again,
and are going to build again what I have destroyed?
Will you limit Me, and set bounds to Me, as to when, and where, and how,
and by whom I shall declare Myself, and publish My name?
Then will I break your cord, and remove your stake, and exalt Myself in your overthrow.

Therefore this is the word of the Lord to you, whether you will hear or refuse:
If you will not take away all those laws which are made concerning religion,
whereby the people which are dear in My eyes are oppressed, you shall not be established;
but even as you have trodden down My enemies by My power,
so shall you be trodden down by My power, and you shall know that I am the Lord.
For My gospel shall not be established by your sword, nor by your law, but by My might,
and by My power, and by My Spirit.
Unto you, this is the word of the Lord: Limit not the eternal Spirit,
by which I will publish My name, as to when and where, and how I will do it;
for if you do, you shall be as dust before the wind; the mouth of the Lord has spoken it,
and He will perform His promise.
For this is what I look for at your hands, says the Lord:
that you should undo the heavy burdens, and let the oppressed go free.
Are not many shut up in prison, some stocked, some stoned, and some shamefully treated?
Some are judged blasphemers by those who know not the Lord,
and by those laws which have been made by the will of man,
and stand not in the will of God.
Some suffer now because they cannot hold up the types and shadows,
and so deny Christ come in the flesh;
and some have been shut up in prison because they could not swear,
and because they abide in the doctrine of Christ.
Some, for declaring openly against sin in the markets, have suffered as evil-doers.
And if you now let them suffer in this way by these laws, and consider this justice,
I will visit for those things, says the Lord.
I will break the yoke from off their necks, and I will bring deliverance another way,
and you shall know that I am the Lord.

Moved of the Lord to declare and write this, by a servant of the Truth for Jesus`'s sake,
and a lover of your soul, called,

Francis Howgill.

The last of the First Month, about the ninth hour, waiting in James`'s Park, at London.

How this was received by him, I am not aware; but this I have understood,
that some of Cromwell`'s servants (and among these one Theophilus Green, and Mary,
afterwards the wife of Henry Stout) were so reached by Francis Howgill`'s discourse,
that after some time they entered into the society of the Quakers (so called).

Now in the above-mentioned letter or speech,
we find notice taken of laws made concerning religion.
I do not believe this to refer to any new laws made by Cromwell himself,
but such as were made in former times,
which he could have altered if he was willing to do so;
even as afterwards many penal laws were abrogated
under the reign of King William and Queen Mary,
as will be said in its proper place.
For I do not find that in Cromwell`'s time any laws were made to constrain
people to attend the worship of the public or national church.
But notwithstanding,
at this time the Quakers (so called) were imprisoned for refusing to swear,
or for not paying tithes to maintain the priests.
Moreover, they were whipped like vagabonds for preaching in markets,
or in other public places;
or they were fined for not taking off their hats before
magistrates (for this was called contempt of the magistracy).
And when for conscience sake they refused to pay such a fine,
either the spoiling of goods or imprisonment became their share.
And thus a cloak or cover was always found to persecute them,
and malice never lacked pretenses to vex them.
And it also often happened that Edward Burrough and Francis Howgill
were opposed by the chiefest of several Christian sects,
whereby disputes were raised,
which many times gave occasion for some of the hearers to embrace
the doctrine maintained by the said Burrough and Howgill;
which so enraged their enemies, that no slanders were spared,
and they sometimes branded them as witches.

In the meantime,
the people called Quakers so increased in London that they began to have settled meetings,
the first of which was in Aldersgate Street, at the house of one Sarah Sawyer.
The first woman of this society who preached publicly
in London was Anne Downer (already mentioned),
who afterwards married one Greenwell, and then becoming a widow,
in process of time entered into matrimony with George Whitehead,
as has been hinted already.
Another one of the meetings of this people in London was in the house of one Bates,
in Tower Street, and still another at Gerard Robert`'s, in Thomas Apostles;
until the church became so great that a house known by the name of the Bull and Mouth,
in Martin`'s le Grand, near Aldersgate, was hired for a meetinghouse.
This, being a building that had belonged to a wealthy man,
had a large hall in it that would hold many people,
and so was very convenient for a meeting place.

An abundance of books, written by the priests and teachers of several sects,
were now written and spread against the Quakers,
branding them seducers and false prophets; for these priests,
perceiving that many of their hearers had forsaken them,
left no stone unturned to stop this.
But the outcome did not answer their hope,
for Burrough and Howgill did not allow these writings to go unanswered,
but clearly exposed the malice and absurdities of those writers.

Leaving them busy with this work, we will take a turn toward Bristol,
to behold the endeavors of John Audland and Thomas Airey;
who came there in the month called July in this year.
Going into the meetings of the Independents and Baptists,
they found opportunity to preach Truth there, and also had occasion to speak to others,
so that many received their testimony.

From there they went to Plymouth in Devonshire, and so to London,
where they met with John Camm; but after a short stay there,
John Audland returned to Bristol with John Camm,
and found there a door opened for their ministry.
Among those that did receive their testimony were Josiah Coale, George Bishop,
Charles Marshal, and Barbara Blaugdone,
concerning which persons more is to be said hereafter.
It was not long before F. Howgill and E. Burrough, having gathered a church at London,
came also to Bristol, where persecution now began to appear with an open face;
for the magistrates commanded them to depart from the city and the surrounding areas.
To this they answered, that they came not in the will of man,
and that when He who moved them to come there, did move them also to depart,
they would obey; and that if they were guilty of the transgression of any law,
they were not unwilling to suffer by it, for they were freeborn Englishmen,
being free from the transgression of any law;
and that if by violence they were put out of the city,
they were ready to suffer it and would not resist, etc.
And having responded in this way, they departed out of the presence of the rulers.
But now the priests, especially one Ralph Farmer, began to incite and enrage the people,
and to set the city (so to speak) on fire.

Hence it was that John Camm and John Audland, intending to have a meeting at Brislington,
about two miles from Bristol, and passing over a bridge,
were assaulted by the rabble of the city and several
apprentices of Ralph Farmer`'s parish,
who having got notice of their coming, had gathered there.
This mob violently abused them with beating, kicking, and a continual cry of,
"`Knock them down!`" "`Kill them!`" or "`Hang them presently!`"
Thus they were driven back, and forced into the city again,
narrowly escaping with their lives.
But the tumult did not yet cease; for some of the multitude were heard to say,
that the mob would find more protection from the magistrates than those strangers,
Camm and Audland.
But the officers of the garrison,
thinking it unwarrantable to permit such a tumult (since
it was not without reason to be feared that the royalists,
or abettors of King Charles,
might take hold of such an opportunity to raise an insurrection),
caused three of the violent ringleaders to be seized.
But this made such a stir,
that the next day more than five hundred people (as it was
thought) gathered together in a seditious manner,
and obtained the liberty of their companions.
This made the tumultuous mob even more bold and saucy,
especially having heard how the magistrates had bid
John Camm and John Audland to depart the town.

Now the riotous multitude did not hesitate to rush violently
into the houses of the Quakers (so called) at Bristol,
under the pretense of preventing plots of treason.
And when some in zeal told the priests that these were the fruits of their doctrine,
they incited the people all the more,
and induced the magistrates to imprison some of those called Quakers.
This instigated the rabble to such degree,
that now they thought they had full liberty to use
all manner of insolence against the said people--beating,
striking, pushing, and often treading upon them until blood was shed;
for they had become a prey to every impudent fellow,
as a people that were outside the protection of the law.
This began to cause tumults in the town;
and some have said (and not without good reason),
that the young apprentices who were active in this work,
would not have dared leave their work, had not their masters given them permission.
And a certain person informed the mayor and aldermen upon his oath,
that he had heard an apprentice say, that they indeed had permission from their masters,
and were encouraged to do so.

Now an order of the court came forth,
that the constables were to make diligent search within their several
districts for all strangers and suspicious persons;
and that all people were to be forewarned not to
be present at any tumult or other unlawful assembly,
or to gather into companies or multitudes in the streets,
on pain of being punished according to law.
But this order was to little purpose, for the tumultuous companies and riots continued;
and once when a proclamation was read in the name
of the Lord Protector requiring everyone to depart,
some of the rioters were heard to say, "`Why do you tell us of a Protector?
Tell us of King Charles!`"
In the meantime the Quakers (so called) were kept in prison,
and it plainly appeared that this order against unlawful
assemblies was leveled against their meetings.
And though the magistrates pretended that they must answer for it to the Protector if
they let the Quakers alone without disturbing their meetings (which at that time,
for the most part, were held in silence, and nothing was spoken,
except when now and then one of their ministers from abroad visited them),
yet this was not at all in concordance with the Protector`'s speech which
he made to the parliament on the 12th of the month called September,
in the painted chamber, where he spoke these words:

Is not liberty of conscience in religion a fundamental?
So long as there is liberty for the supreme magistrate to exercise his conscience in
erecting whatever form of church government he is satisfied he should set up,
why should he not give this liberty to others?
Liberty of conscience is a natural right, and he that would have it,
ought also to give it.
Indeed this has been the vanity of our conflicts: every sect says,
"`Give me liberty;`" but when it is given, he will then not yield it to anybody else.
Where is our wisdom?
Truly this is a thing that ought to be very reciprocal.
The magistrate has his supremacy, and he may settle religion according to his conscience.
And I may say to you, I can say it,
all the money in the nation would not have tempted
men to fight upon such an account as they have engaged,
if they had not had hopes of liberty--more than they had from episcopacy,
or would have had from a Scottish Presbytery, or an English either,
if it had made such steps,
or been as sharp and rigid as it threatened when it was first set up.
This I say is a fundamental; it ought to be so.
It is for us and the generations to come.

Cromwell spoke more in confirmation of these things;
and indeed he would have been a noble man,
if he had really performed what he here asserted with binding arguments.
But though he seemed now to disapprove the behavior of the
Presbytery (for at this time he was in favor of Independency),
yet after some time he courted the Presbyterians;
and these then fawning upon him from the pulpit as
their preserver and the restorer of the church,
he allowed the Quakers to be persecuted under his government,
though he pretended not to know it, when he might easily have stopped it.
But by hearkening to the flatteries of the clergy, he at length lost his credit,
even among those with whom he had fought for the common liberty.
And so at last, after his death,
he seemed to bring upon himself the curse which he pronounced in the forgoing speech,
if ever he would depart from allowing liberty of conscience.
For he further said upon this occasion,
that "`liberty was a fundamental of government,`"
and that "`it had cost much blood to have it so,
even the hazarding of all.`"
And in conclusion he said, "`I could sooner be willing to be rolled into the grave,
and buried with infamy,
than give my consent to the willful throwing away of such a government.`"
Now who does not know what infamy befell him afterwards,
when in the reign of King Charles the Second,
his corpse was dug up and buried near the gallows,
as may be further mentioned in its due place.^
footnote:[His body was hanged in chains at Tyburn, London and then thrown into a pit.
His head was cut off and displayed on a pole outside Westminster Hall until 1685.]

But I return now to Bristol,
where several were still kept in prison with no liberty granted them,
and were even charged with what they utterly denied themselves to be guilty of.
Among these, one John Worring was accused of having called the priest, Samuel Grimes,
a devil; but Worring denied this,
though he did not hesitate to say that he could prove
something similar to it by the priests own words.
And it being asked him how,
he answered that the priest had declared at the meeting
that he sinned in everything he did;
and if he sinned in all things,
then the same is true in his preaching as in other things;
yet the Scriptures hold forth that "`He who sins is of the devil.`"
It may be easily conjectured that this answer did not please the priests`' followers,
and therefore Worring and some others were kept in prison.
Among these prisoners was also Elizabeth Marshall, who in the steeple-house,
after the priest John Knowls had dismissed the people with what is called the blessing,
spoke to him, and said, "`This is the word of the Lord to you.
I warn you to repent, and to mind the light of Christ in your conscience.`"
And when the people, by order of the magistrates then present, violently assaulted her,
giving her many blows with staves and clubs, she cried out,
"`The mighty day of the Lord is at hand, wherein He will strike terror upon the wicked.`"
Some time before this she spoke also in the steeple-house
to the priest Ralph Farmer (before-mentioned),
after he had ended his sermon and prayer, and said,
"`This is the word of the Lord to you: Woe, woe,
woe from the Lord to those who take the word of the Lord in their mouths,
and the Lord never sent them.`"

A good while after this, the magistrates gave out the following warrant:

City of Bristol.

To all the constables within this city, and to every one of them.

Forasmuch as information has been given us, that John Camm, and John Audland,
two strangers, who were commanded to depart this city, have, in contempt of authority,
come into this city again, to the disturbance of the public peace:
these are therefore to will and require you forthwith to apprehend them,
and bring them before us to be examined, according to law.

Given this 22nd of January, 1654.
Signed,

William Cann, Richard Vickirs, Dept.
Mayor.
Joseph Jackson, Henry Gibbs, Gabriel Sherman, John Lock.

Camm and Audland had departed the town before this time,
having never been commanded (as the warrant says) to depart the city,
either by the magistrates themselves, or by anyone else at their command;
though Francis Howgill and Edward Burrough had been required to do so.
This warrant proving ineffectual,
the magistrates caused another to be written in these words:

City of Bristol.

To the constables of the peace of the district of +++________+++ and to every one of them.

Forasmuch as information has been given us upon oath,
that certain persons of the Franciscan order in Rome have of late come over into England,
and under the notion of Quakers, drawn together several multitudes of people in London;
and whereas certain strangers, going under the names of John Camm, John Audland,
George Fox, James Nayler, Francis Howgill, and Edward Burrough, and others unknown,
have lately resorted to this city, and in like manner, under the notion of Quakers,
drawn multitudes of people after them, and occasioned very great disturbances among us;
and forasmuch as by the said information it appears to us to be very probable,
and much to be suspected,
that the said persons so lately come here are some of those that came from Rome,
as aforesaid; this is therefore given in the name of his highness, the Lord Protector,
to will and require you to make diligent search through
your district for the aforesaid strangers,
or any of them, and all other suspected persons,
and to apprehend and bring them before us to be examined and dealt with according to law.
Hereof fail not.

Given the 25th of Jan.
1654+++.+++ Signed,

John Gunning, Mayor.
William Cann, Gabriel Sherman, Joseph Jackson, Henry Gibbs, John Lock, George Hellier,
Richard Vickirs.
Gabriel Sherman.

Hereunto these magistrates affixed their seals;
and that alderman Sherman might be sure his name was among them, he wrote it twice.
Now, even a child might perceive how frivolous was the
pretense of these men being of the Franciscan order;
for the Quakers had by this time so multiplied in the North of England,
that they could no more be looked upon as an unknown people.
And as for G. Fox and James Nayler, they had not yet been at Bristol,
and therefore it seemed absurd to seek for them there.
But it was thought expedient to brand the Quakers with odious names,
so that under such a cloak they might be persecuted as disturbers of the public peace.
This appeared clearly in the case of one Thomas Robertson and Josiah Coale,
who being at Nicholas`' steeple-house,
and standing still without speaking a word until
the priest Hazzard had ended and dismissed the people,
were very rudely treated.
For when Thomas was about to lift up his voice, even when the word was yet in his mouth,
he was struck on the head by many, as was also his companion,
though he did not even attempt to speak.
But Thomas, after having a little recovered from a heavy blow, began to speak again,
and said to the people, "`Tremble before the Lord, and the word of His holiness.`"
But this so kindled their anger,
that both these men were hurried out of the steeple-house,
and with great rage driven to the mayor`'s, who commanded them to Newgate prison.

Not long after this, one Jeremy Hignel, being in his shop attending his calling,
was sent for by the mayor and aldermen to come before them.
When he had come, the mayor asked him whether he knew where he was; he answered he did.
Then the mayor asked "`Where?`"
He replied, "`In the presence of the Lord.`"
"`Are you not,`" said the mayor, "`in the presence of the Lord`'s justices?`"
His answer was, "`If you are the Lord`'s justices, I am.`"
Upon this, without any more words passing at that time, one of the aldermen said,
"`We see what he is; take him away to Newgate prison.`"
For since J. Hignel did not take off his hat, it was concluded he was a Quaker,
and this was considered cause enough to send him to prison.
So he was immediately brought to Newgate,
where the keeper of the prison received him without a court order,
and kept him close prisoner for nineteen days,
permitting none to come to him but his wife.

No better was the treatment of Daniel Wastfield, who, being sent for by the mayor,
appeared before him and alderman Vickirs.
The mayor said to him, "`Wastfield, come here;`" and so drawing near,
the mayor asked him three different times, "`What are you?`"
Though he knew him well enough, having called him by his name as above said.
Wastfield answered, "`I am a man.`"
"`But what is your name?`"
said the mayor.
"`My name is Daniel Wastfield,`" answered he.
Then the mayor said to one of his officers, "`Take him and carry him to Newgate;
for he came here to scorn justice.`"
To which Wastfield replied, "`No,
I came here in obedience to your order;`" for the mayor had sent for him,
as has been said.
Thus he was carried away without a court order,
the mayor saying "`his word was a court order;`" and he
was kept a close prisoner for thirty-three days.
None were permitted to come to him but his servants, notwithstanding he was a widower,
and was made to leave his house and trade to their management;
and a child of his died during his imprisonment and was buried,
and he was kept from seeing it.

The magistrates having thus begun persecution, became more and more vigorous over time,
insomuch that several others were imprisoned, and among these Christopher Birkhead.
This man had stood still in Nicholas`' steeple-house with his hat on,
and being asked by the priest, Ralph Farmer, what he stood there for; answered,
"`I stand in obedience to the righteous law of God in my conscience;
I have neither offended the law of God, nor of the nation.
'`An astonishing and horrible thing is committed in the land...`'^
footnote:[Jeremiah 5:30-31 "`An astonishing and horrible
thing has been committed in the land.
The prophets prophesy falsely, and the priests rule by their own power;
and My people love to have it so.
But what will you do in the end?`"]`" More he would have spoken,
but he was stopped with beating and thrusting, and so carried to prison.

Now the magistrates were greatly incited to persecution by the said Ralph Farmer.
Some of his hearers, who were very bold, did not hesitate to write strong letters to him,
and, after his sermon, to tell his indecent behavior to his face;
and those who did so were sent to prison.
At length these prisoners were brought to trial;
and since it could not be proved that they had transgressed any law,
some of the magistrates seemed inclined to set them at liberty,
if they would declare that they were sorry for what they had done.
Among them was one William Foord, against whom nothing substantial could be charged,
except that he was one of the people called Quakers.
Being asked whether he was sorry for what he had done; he denied it,
and so was sent to prison again.
There was also among these a woman named Temperance Hignel, who,
having said in the steeple-house to the priest (after he had ended his sermon),
"`Woe from the Lord God to you, Jacob Brint,`" she was presently struck down,
and so violently abused that blood ran down her face.
Being then committed to prison, she fell sick;
and when they saw her that life was in danger, she was carried out in a basket,
and died three days later.
The reason she gave, when in prison, why she spoke in that manner to the priest,
was that he had scarce any hearers but those who were swearers, drunkards, strikers,
fighters, and railers, etc., and that therefore his ministry was in vain,
being one who preached for gain, but did not bring forth good fruits.

How long the others were kept in prison, I do not know for certain; however,
it was a pretty long time, for George Bishop,
Dennis Hollister (who formerly had been a member of the parliament) and three others,
put all these transactions in writing at length, and sent it to the magistrates,
in hopes that thereby they might see the evil of persecution.
But as this proved in vain, they gave it out in print five months after,
so that everyone might know how the people of Bristol treated their inhabitants,
which was to that degree, that one author wrote,
"`Was such a tyrannical iniquity and cruelty ever heard of in this nation?
Or would the ministers under king Charles have ventured to do so?
Was not Stafford but a petty transgressor in comparison of these?`"
And though Archbishop Laud was beheaded,
yet it could not be proved that the Episcopalians had persecuted as fiercely
as these pretended asserters of liberty of conscience had done,
who, having got possession of the power, oppressed more than those they had driven out.
This made the persecuted ones (some of whom had formerly fought for the common
liberty) the more earnestly against those that were now in authority.

But I will turn away from Bristol towards Norwich,
where Richard Hubberthorn and George Whitehead had gone.
Here it happened, that Richard Hubberthorn,
having spoken to a priest in a steeple-house yard,
and not having taken off his hat before the magistrates, was imprisoned in the castle,
where he was kept for great part of the following year.
In the meantime, he wrote several epistles of exhortation to his friends;
while the preaching of George Whitehead, his companion, had such an effect,
that a meeting of their friends was settled in that city.

But before I go on,
it will be convenient to give some account of the quality of these two persons.
Richard Hubberthorn was born in the North of Lancashire,
and descended from very honest parents.
His father was a yeoman of good reputation among men, and Richard was his only son,
who from a youth was inclined to piety.
Having grown to be a man, he became an officer in the parliament`'s army,
and from a zeal for godliness, preached sometimes to his soldiers.
But entering afterwards into the society of the Quakers (so called),
he left his military employment and testified publicly against it;
for he had now become a soldier under another banner--that of Christ Jesus,
Prince of Peace; not fighting (as formerly) with the outward sword,
but with the sword of the Spirit, which is the word of God.
In his ministry he had an excellent gift,
and though his voice was not as loud as some others,
yet he was a man of a quick understanding, and was very edifying in his preaching.

G+++.+++ Whitehead (who, while I write this, is yet alive^
footnote:[George Whitehead was born in 1636 and died in 1723.]) was trained up to learning,
and though but a youth, instructed others in literature,
and continued in that calling sometime after he came to be convinced
of that Truth which was preached by the professors of the light.
But before this change he was a diligent hearer of the world`'s teachers,
and usually frequented the steeple-house at Orton in Westmoreland.
Yet the singing of David`'s psalms became so burdensome to him,
that he sometimes could not join in this custom,
for he saw that David`'s conditions were not generally
suitable to the states of a mixed multitude;
and he found himself to have come short of what they sung.
This consideration brought him into such distress,
that he often dared not sing the psalms which the
priests had given their hearers to sing,
lest he should have spoken lies unto God.
He also began to see that the priests`' lives and
practices did not agree with their doctrine;
for they spoke against pride and covetousness, and yet still lived in such things.
This made him go to hear some who had separated from the national church,
and had gotten into a more plausible form of godliness; but he soon saw that,
though there was a difference in the ceremonial part,
and that these had a more true form of words than the priests,
still they were such as ran before they were sent by God,
speaking peace to that nature in him wherein he felt no true peace.
And when he was about seventeen years of age, which was in the year 1652,
he first heard the doctrine of Truth preached by
those that were reproachfully called Quakers.
Their testimony wrought so powerfully upon his mind, that he received it,
and so entered into their communion.
And then he found, that to grow up in the true wisdom,
and to become wise in the living knowledge of God,
he must become a fool to that wisdom wherein he had been feeding upon the tree of knowledge,
having (in that state) no right to the tree of life.
And so continuing in faithfulness,
it pleased the Lord to ordain him a minister of the gospel;
in which service he acquitted himself well,
to the convincing of many others and the edification of the church.

But now leaving him, let us go and see what happened at Oxford in the year 1654.
At the latter end of the month called June, there came two women,
named Elizabeth Heavens and Elizabeth Fletcher.
These spoke in the streets to the people, and in the college they exhorted the students,
who wickedly requited their zeal by violently pushing Elizabeth Fletcher against a gravestone,
and then throwing her into a grave.
Their malice grew to such a height, that they tied these two women together,
and drove them under the water pump.
And after they were exceedingly welted by pumping water upon them,
they were thrown into a miry ditch, through which they dragged Elizabeth Fletcher,
who was a young woman, and so cruelly abused her,
that she remained in a painful condition until her death,
which took place not long after.
Some short time after this rude encounter, she and her companion,
on a First-day of the week, went into the steeple-house at Oxford,
and when the priest had ended, they began to admonish the people to godliness.
But two justices being present, commanded them to be taken into custody,
and carried to the prison called Bocardo, where none but felons were kept.
The justices desiring the magistrates to meet on this account,
the mayor would not meddle with it, but said,
"`Let those who have committed them deal with them according to law,
if they have transgressed any;`" adding that he had nothing to say against them,
but would provide them with food, clothes, or money, if they needed any.
Yet afterwards he came into the assembly where these women were examined,
and where the vice-chancellor of the university had also come,
who charged them with having blasphemed the name of God, abused the Spirit of God,
and dishonored the grace of Christ.
Then, asking them whether they did read the Scriptures, they answered, yes they did.
Then he asked whether they were not obedient to the power of the magistrate;
to which their answer was, they were obedient to the power of God,
and were subject to any power that was of God for conscience-sake.
"`Well,`" said the vice-chancellor, "`you profane the word of God,
and I fear you know not God, though you so much speak of Him.`"
Then the women being made to withdraw,
it was concluded that there was cause enough for their commitment and punishment,
and they agreed that an order should be drawn up for their being whipped out of the city.
When the order was written, it was presented to the mayor to set his hand to it;
but he refused, and said he was not willing to do so.
Then one of the justices said,
that it was the privilege of the city that if any vagrant
was taken within the franchises and liberties thereof,
an order must be drawn up and sealed with the office seal.
But the mayor refused this as well.
This made some of them say, "`If you will not, it will be done by us.`"
Then it was agreed upon, that these women should be whipped soundly;
which was performed the next morning, though with much unwillingness in the executioner;
and the mayor had no hand in it.

But leaving these, I will turn to another, one Barbara Blaugdone,
of whom mention has already been made that she was one of those that received
the Truth by the ministry of John Audland and John Camm.
She was from her youth inclined to godliness,
and her employment was a teacher of children.
But being entered into the society of those called Quakers, she became plain,
both in speech and dress, and thereupon the children she taught were taken from her.
Going sometimes into the steeple-houses to bear testimony against their formalities,
she was put in prison and kept there a quarter of a year at a time.
Afterwards she led a very self-denying life, and abstained from all meat, wine, and beer,
drinking only water for the space of a whole year.
In the meantime she grew up and prospered in true piety.
Once it happened, that coming from a meeting at George Bishop`'s house at Bristol,
a rude fellow ran a knife, or some sharp instrument, through all her clothes,
into the side of her belly, which if it had gone but a little further,
might have killed her.
She then went to Marlborough, where,
exhorting people in the steeple-houses and other places to fear God,
she was put into prison for the space of six weeks,
and there she fasted several days and nights.
When she was released, she went to Isaac Burges, the man that committed her,
and upon discoursing with him, he was really convinced of the Truth,
but could not resolve to take up the cross.
Nevertheless, he was afterwards very loving to her friends,
and stood by them upon all occasions, never more persecuting any of them.
And coming some time after this to Bristol,
he went to her house and confessed that he knew her doctrine was Truth,
but that he could not take up the cross to walk in that way.

A while after she went into Devonshire, to Moulton, Barnstable, and Bediford,
in all which places a prison was her lot.
She went also to see one who was afterwards the earl of Bath,
at a place where she had formerly vainly spent much time,
but now she was moved to call this family to leave off their vanity.
She asked to speak with the lady of the house; but one of the servants that knew her,
bid her to go to the back door,
and their lady would come forth that way and go into the garden.
Barbara having come there, a great mastiff dog was set loose upon her;
which ran fiercely towards her as if to devour her,
but then turned suddenly and went away crying and limping,
whereby she clearly saw the hand of the Lord to preserve her from this danger.
The lady then came and stood still, and heard what Barbara spoke,
and gave her thanks for her exhortation, yet did not invite her to come in,
though she often had lodged there, and had eaten and drank at her table.

Then Barbara went to Great Torrington, and, going into the steeple-house,
spoke something to the people by way of exhortation;
but not having sufficient opportunity to clear herself,
she went to her lodging and began writing.
After noon the constables came to her, took away what she had written,
and commanded her to go along with them to their place of worship.
To this she answered, that they would not allow her to speak there,
and that she knew no law that could compel her to go there twice in a day,
and they all knew she was there in the morning.
Being thus unwilling to go, the next day the mayor sent for her.
When she had come, she found him moderate and reluctant to send her to prison;
but the priest (being present) was very eager,
and said she ought to be whipped as a vagabond.
She then bid him prove wherever she had asked anyone for a bit of bread;
but he said she had broken the law by speaking in their church.
This priest so pressed the mayor, that at length he made him write a court order,
and send her to Exeter prison, which was twenty miles distant.
There she remained for some time, until the court session came,
but she was not brought forth to a trial.
And after the sessions were over,
she was made to lodge one night among a great company
of gypsies that were then in prison.

The next day the sheriff came with a church officer^
footnote:[Called a Beadle]
who brought her into a room, and whipped her till the blood ran down her back,
though she never winced at a blow, but rather sang aloud,
and was made to rejoice that she was counted worthy to suffer for the name of the Lord.
This made the church officer say, "`Do you sing?
I will make you cry soon enough;`" and with that he whipped
her so hard that one Ann Speed seeing this began to weep.
But Barbara was strengthened by an uncommon and more than human power,
so that she afterwards declared if she had been whipped
to death in the state she was then in,
she would not have been terrified or dismayed.
And the sheriff, seeing that all the wrath of man could not move her,
bid the fellow leave off striking; and then Ann Speed was allowed to dress her wounds.
The next day she was discharged from the prison together with all the gypsies,
and the church officer followed her two miles out of the town;
but as soon as he left her, she returned back,
and went into the prison to see her friends who were prisoners there;
and having visited them, she went home to Bristol.

But on the way, as she was coming to Bediford,
she was taken up and put into the town-hall,
and searched to see whether she had either a knife or scissors in her possession.
The next day she was brought before the mayor, who discoursing much with her,
had a sense of the truth which she spoke to him;
and at last he set open two doors before her, one right next to the other,
and said he would give her the choice which way she should go,
whether back to prison again, or home.
Barbara told him that she would choose liberty rather than bonds, and so went homeward.
The mayor then took his horse and followed; and overtaking her on the road,
would have had her ride behind him; but when any whom he knew met them on the road,
he would slacken his pace; and as soon as they had passed, he came up again to her.
So he rode three or four miles with her, and discoursed all the way,
and when they parted, she kneeled down and prayed for him.
All of this time he was very serious, and afterwards became very solid and sober.
She wrote once to him; but not long after this, he died.

Having come home she was moved to go to Basingstoke,
to endeavor to obtain liberty for two of her friends, namely,
Thomas Robinson and Ambrose Rigge,
who had been taken up at the first meeting that their friends had had there.
But when she came there she was denied entrance to the prison.
Having a letter from John Camm to these two men, she put it in at the chink of the door,
and then went to the mayor to seek their liberty.
The mayor told her, that if he saw the letter which had she brought to them,
they would have their liberty.
She responded, "`You shall see it;`" and so went and fetched it.
And having read it, the mayor told her that she should have her brethren out,
but that he could not let them out presently.
Yet it was not long before her friends had their liberty.

Now leaving Barbara for some time, we return to Miles Halhead.
In the First month of this present year,
he was moved to go to Ireland and declare the word of the Lord there;
and speaking of this to James Lancaster and Miles Bateman,
they quickly resolved to keep him company.
So they went to Ireland, where they proclaimed the Truth in cities, towns, villages,
and before magistrates, as occasion offered; and their testimony was received by many.
After they had discharged themselves, they returned to England,
where Miles soon found himself moved to go to Scotland.
On his way there, he met his friend James Lancaster, who felt very free to accompany him,
and so they went into Scotland.
But these were not the first of those called Quakers in that country;
for Christopher Fell, George Wilson, and John Grave had been there before,
so that a little church made up of those of their
communion was already planted in that kingdom,
before Miles Halhead went there.
And one Alexander Hamilton, a year before any Quakers appeared in Scotland,
had erected a meeting at Drumbowy, and also at Heads,
and he received their testimony when they came there, along with his wife Joan,
James Gray, James Miller, and others.
I find also that Scotland was early visited by Catherine Evans and Sarah Cheevers,
two eminent women, of whom something extraordinary is to be related in its due time.

But I return to J. Lancaster and Miles Halhead, who, having come to Dumfries,
went on a First-day of the week into the steeple-house in that town,
where they saw many people gathered together, howling and crying,
and making great lamentation, as if they had been touched with a sense of their sins.
Miles was silent until their worship had finished; but then,
being grieved with their deceit and hypocrisy, spoke as he was moved.
But he met with great opposition,
for many of the people were in such a rage that they
drove him and his companion out of the town,
near to the side of a great river;
and it was intended that the women of the town should stone them.
But the men prevented this by wading through the river.

Having thus safely passed the water, they went to Edinburgh and Leith,
where they stayed about ten days.
During that time, Miles spoke to the people when occasion offered,
and also to the garrisons, and to the captains and officers of the army,
who were much affected, and confessed that the Lord had been very good unto them.
For Miles`'s message was that the anger of the Lord was kindled against them because
they had not performed their promises which they made to Him in the day of their distress,
when their enemies encompassed them on every side.
For the Lord had then delivered them, and gave them victory;
but they had returned Him evil for good,
and committed violence against those He sent to declare His word among them.
This being told them at length by Miles, he then went to Glasgow and Stirling,
where he also spoke as he was moved; and so returned to England.

But before I leave Scotland, I may say,
that as the first meetings were at Drumbowy and Heads,
so it was not long before meetings were settled also at Garshore, at Edinburgh,
and also at Aberdeen.
The first Scotch preachers of those called Quakers, I find to have been William Osborn,
Richard Ree, and Alexander Hamilton, already mentioned.
Of the said Hamilton, I may mention an unusual instance:
after he and his wife and sister had separated themselves from the society of the Independents,
it happened that Thomas Charters, a teacher of that sect (at Kilbride,
not far from Drumbowy), seeing that he could not draw Hamilton and his family back again,
threatened them with excommunication, and appointed a day for it,
giving notice thereof to Hamilton some days beforehand.
Hamilton warned him to forbear, or else the anger of God would seize upon him.
But Charters answered, "`It is but Alexander Hamilton that says so.`"
To this Hamilton replied in the presence of many witnesses, that it was not only he,
but what he had said was of the Lord.
But Charters persisting in what he intended,
and walking two days before the appointed time in
the steeple-house yard where his horse was feeding,
stepped up to stroke him; but the horse grew unruly,
and gave Charters such a violent kick on his side that he died two days later,
about the same hour which was appointed by him for the excommunication.
Whether this case happened in the year I now describe, I am not certain;
but it was either in, or near it.

This year Miles Halhead came to Berwick in Northumberland,
and went to the mayor of that town, and spoke to him in his shop, saying: "`Friend,
hear what the servant of the Lord has to say unto you.
Give over persecuting the Lord`'s servants,
whom He sends in love to this town of Berwick,
to show you the way that leads to life eternal.
I charge you, O man, touch not the Lord`'s anointed, nor do His prophets any harm,
least you procure the anger of the living eternal God against you.`"
This bold language so offended the mayor, that he sent Miles to prison,
where he remained about ten weeks, and then was brought to the court sessions.
There a bill was drawn up against him and read in open court;
but he denied the contents thereof, yet said,
"`But what I said to the mayor of this town, I will not deny.`"
And then he related the aforesaid words which he had spoken to the mayor.
Upon this, the recorder said, "`Sirs, as I understand by his own words,
if he cannot prove the mayor of the town a persecutor,
in my judgment he has wronged him.`"
To this Miles answered,
"`If the mayor of this town of Berwick dare say in the presence of the Lord,
whose presence is here, that he is no persecutor,
but that the persecuting nature is slain in him,
I will be willing to abide by the judgment of the court.`"
Then the clerk of the court said, "`Mr. Mayor,
if you will say that you are no persecutor,
but that the persecuting nature is slain in you,
he is willing to abide by the judgment of the court.`"
To this the mayor answered, "`I know not what to do.
I wish I had never seen him.
I pray you, let him go, and let us be no more troubled with him.`"
Then Miles said, "`I will prove this mayor the greatest persecutor in town or country.
I was once,`" he went on, "`committed to the prison in this town before,
by some of the justices that are now in this court; but you, O man,
have exceeded them all.
For you have committed me, and kept me a close prisoner for about ten weeks,
for speaking to you privately in your own shop.
Now I make my appeal to the recorder of this town of Berwick,
as I am a freeborn Englishman, whether my imprisonment be legal,
according to the law of this nation, or not?`"
Then the recorder of the town stood up and said,
"`It is not legal for any minister of the law to imprison a man for his own cause.`"
Then the court cried, "`Take him away!`"
The chief priest of the town then stood up,
and requested the court that he might ask Miles one question.
To this Miles said, "`The Lord knows your heart, O man,
and at this present time He has revealed your thoughts to His servant; and therefore,
now I know your heart also, you high priest, and the question you desire to ask me.
And if you will promise me before the court,
that if I tell you the question you wish to ask me, you will deal honestly with me,
I will not only tell you your question, but I will answer it.`"
Then the priest said he would.
So Miles proceeded: "`Your question is this:
you wish to know whether I acknowledge that Christ who died at Jerusalem, or not?`"
To this the priest, marveling, said, "`Truly, that is the question.`"
Then Miles said, "`According to my promise, I will answer it before this court.
In the presence of the Lord God of heaven,
I acknowledge no other Christ than Him who died at Jerusalem,
and made a good confession before Pontius Pilate,
to be the light and way that leads fallen man out of sin and evil, up to God eternal,
blessed forevermore.`"
No more questions were asked of him, but the jailer was commanded to take him away.
Yet within a short time, the court gave order to release him.
Then going to Newcastle, he returned to his wife and children at Mount-joy,
where we will leave him for some time, and in the meantime return again to G. Fox,
whom we left at Synder-hill-green.
From here he travelled up and down in Yorkshire, as far as Holderness,
visiting his friends, and finding the churches in a flourishing state.
To relate all his occurrences there, would be beyond my scope.

Passing then through the countries, he went to Lincolnshire,
where the sheriff of Lincoln came to a meeting where he was,
and made a great contention for a time.
But at length the power of the Lord so reached him that he was convinced of the Truth,
along with several others who also had opposed him.
While G. Fox was in this country,
the church of his friends increased and many received the doctrine preached by him,
and among these was one sir Richard Wrey,
with his brother, and the brother`'s wife, who both continued steadfast till they died;
but sir Richard found this way so narrow that he afterwards ran out;
for persecution at that time fell so hard on those called Quakers,
that none could abide in their society but such as were willing to hazard all.

G+++.+++ Fox now went to Derbyshire,
and the above-mentioned sheriff of Lincoln traveling with him,
they came into Nottinghamshire, and so came into the Peak country.
There they had a meeting at Thomas Hammersley`'s,
where several ranters came in and opposed him.
And when he reproved them for swearing, they said, "`Abraham, Jacob, and Joseph swore.`"
But though G. Fox did not deny this, yet he said, "`Christ,
(who said '`before Abraham was, I am`') says,
'`Swear not at all.`' And Christ ends the prophets, and also the old priesthood,
and the dispensation of Moses; and He reigns over the house of Jacob, and of Joseph,
and says, '`Swear not at all.`' And God,
when He brings the first-begotten into the world, says,
'`Let all the angels of God worship Him,`' namely, Christ Jesus, who says,
'`Swear not at all.`' And as for the plea that men make for swearing to end their discord,
Christ (who says, '`Swear not at all`') destroys the devil and his works,
who is the author of discord; for that is one of his works.
And God said, '`This is My beloved Son in whom I am well pleased,
hear Him.`' So the Son is to be heard, who forbids swearing.
And the apostle James, who did hear the Son of God, and followed Him, and preached Him,
also forbids all oaths.`"
Thus G. Fox prevailed, and many were convinced that day.
And it is remarkable that this Thomas Hammersley, being summoned to serve upon a jury,
was allowed to serve without an oath.
And when (being the foreman) he brought in the verdict,
the judge declared that he had been a judge so many years,
but had never heard a more upright verdict than that
which this Quaker had then brought in.

G+++.+++ Fox traveling on, came to Swanington, in Leicestershire,
where there was a general meeting, to which many of his friends came from several parts,
and among these, John Audland and Francis Howgill, from Bristol; and Edward Burrough,
from London.
After this, G. Fox came to Twycross, and some ranters there sang and danced before him;
but he reproved them so earnestly that some of them were reached,
and became modest and sober.

Then George went to Drayton, his birth-place, to visit his relations.
Here, Nathaniel Stevens, the priest, along with another priest, sent for him.
Having been three years abroad, G. Fox, knew nothing of their design,
but at last went to the steeple-house yard where the two
priests had gathered together an abundance of people.
They desired him to go into the steeple-house, but he asked them what he should do there?
And it was answered him, "`Mr. Stevens cannot bear the cold.`"
To which G. Fox said,
"`He may bear it as well as I.`" But at last they went into a great
hall (Richard Farnsworth being with him) where they entered into
a dispute with the priests concerning their practice,
how contrary it was to Christ and His apostles.
The priests asked them where tithes were forbidden or ended;
whereupon G. Fox showed them out of the epistle to the Hebrews, chapter 7,
that not only tithes, but the priesthood that took tithes, had ended;
and that the law had been brought to an end and annulled
by which the priesthood was made,
and by which tithes were commanded to be paid.
Moreover, knowing Steven`'s condition, he laid open his manner of preaching,
showing that he (like the rest of the priests) "`applied
the promises of God to the first birth,
which must die; whereas the promises were to the seed, not to many seeds,
but to the one seed, Christ, who was one in male and female.
For all were to be born again, before they could enter into the kingdom of God.`"
Then Stevens said that he must not judge so.
But G. Fox told him, "`He that was spiritual judged all things.`"^
footnote:[1 Corinthians 2:5]
Stevens confessed that this was a scripture; "`But neighbors,`" he said,
"`this is the issue: G. Fox has come to the light of the sun,
and now he thinks to put out my star-light.`"
To this G. Fox replied, "`I would not quench the least measure of God in any man,
much less put out his star-light, if it were true star-light,
light from the Morning Star.
But if you have anything from Christ, or God, you ought to speak it freely,
and not take tithes from the people for preaching;
seeing Christ commanded His ministers to give freely as they had received freely.`"
But Stevens said he would not yield to that.

This dispute, having ended for that time,
was again taken up a week after by eight priests, in the presence of many people.
And when they saw that G. Fox remained unshaken, they fawningly said,
"`What might he have been if it had not been for the Quakers!`"
Afterwards the dispute was resumed in the steeple-house yard, where G. Fox showed,
by an abundance of Scriptures,
that they who would not preach without wages or tithes did
not serve the Lord Jesus Christ but their own bellies.
This he treated on in such depth, that a professor said, "`George, what!
Will you never be done?`"
To this he answered, that he would be done shortly.

Then they broke up the meeting, and priest Stevens desired that G. Fox,
with his father and mother, might go aside with him and speak to him in private.
Though his relations yielded to it, George was very reluctant to do so; yet,
that it might not be said he was disobedient to his parents, he went along.
But many of the people desiring to hear, drew close to them.
Then Stevens said, if he was out of the right way, George should pray for him;
and if George was out of the right way, he would pray for him.
Moreover, he desired to give George a set form of words by which to pray.
To this G. Fox replied,
"`It seems you do not know whether you are in the right way or not;
but I know that I am in the everlasting way, Christ Jesus, which you are out of.
And here you desire to give me a set form of words to pray by,
and yet you deny the common prayer book to pray by,
as well as I. If you would have me pray for you by a set form of words,
is this not to deny the apostles`' doctrine and practice
of praying by the Spirit as it gave words and utterance?`"
Here, though some of the people fell a laughing, yet others,
that were grave and sober were convinced of the Truth,
and the priests were greatly shaken.
Hearing these things,
George`'s father (though a hearer and follower of the priest) was so well satisfied,
that he struck his cane upon the ground, and said, "`Truly I see,
if a man will but stand to the Truth, it will carry him out.`"

G+++.+++ Fox did not stay long at Drayton, but went to Leicester, and from there to Whetstone,
where a meeting was to be held.
But before the meeting began,
there came about seventeen troopers of colonel Hacker`'s regiment, who,
taking him into custody, brought him to the said colonel,
where were also his major and captains.
Here he entered into a long discourse with them about the priests, and about meetings;
for at this time there was a rumor of a plot against Cromwell.
George spoke much concerning the light of Christ,
which enlightens every man that comes into the world.
The colonel hearing him speak of this,
asked whether it was the light of Christ that made Judas betray his Master,
and afterwards led him to hang himself?
G+++.+++ Fox told him, "`No; that was the spirit of darkness which hated Christ and his light.`"
Then the colonel said to George that he might go home, and keep at home,
and not go abroad to meetings.
But George told him he was an innocent man, free from all plotting,
and he denied all such works.
Then the colonel`'s son, Needham, said, "`Father, this man has reigned too long;
it is time to have him cut off.`"
G+++.+++ Fox asked him, "`For what?
What have I done, or whom have I wronged from a child?
And who can accuse me of any evil?`"
Then the colonel asked him if he would go home and stay there.
To this G. Fox answered, that if he should promise him to go home,
and make his home a prison to himself, it would imply that he was guilty of something;
and if he then went to meetings, they would say he broke their order.
Therefore he would continue to go to meetings as the Lord should order him,
and could not submit to their requirings.
And having further added that he and his friends were a peaceable people,
the colonel said, "`Well then,
I will send you tomorrow morning by six o`'clock to my lord Protector, by captain Drury,
one of his life-guard.`"

The next morning, about the appointed time, he was delivered over to captain Drury.
G+++.+++ Fox requested the captain to let him speak again with the colonel before he went;
and so he was brought to the colonel`'s bedside,
who again bade him go home and keep no more meetings.
But G. Fox told him he could not submit to that;
but must have his liberty to serve God and go to meetings.
"`Then,`" said the colonel, "`you must go before the Protector.`"
Whereupon G. Fox kneeled on his bedside, and prayed the Lord to forgive him; since,
according to his judgment,
he was like Pilate (for the colonel had been stirred up and provoked by the priests),
though he would wash his hands of the guilt.
Therefore George said to him,
"`When the day of your misery and trial shall come upon you,
remember then what I have said to you.`"
Surely it was far from the mind of Needham, who desired to have G. Fox cut off,
to think that the same would one day happen to his father in an ignominious manner,
at Tyburn.
But what afterwards happened,
when the colonel was condemned as one of the judges of King Charles the First,
will be related in its due place.

G+++.+++ Fox, having left colonel Hacker, was carried prisoner by captain Drury to London,
where the captain went to give the Protector an account of him.
Coming again to him,
he told G. Fox that the Protector required that he should promise not to take
up a sword or weapon against him or the government as it then was,
and that he should write this in whatever words he saw good, and set his hand to it.
G+++.+++ Fox considering this, the next morning wrote a paper to the Protector,
by the name of Oliver Cromwell,
wherein he did in the presence of God declare that
he denied the wearing or drawing of a carnal sword,
or any outward weapon, against him or any man;
and that he was sent of God to stand a witness against
all violence and against the works of darkness;
and to turn people from darkness to the light,
and to bring them off from the occasion of war and fighting to the peaceable gospel;
and off from being evil-doers, which the magistrates sword should be a terror to.^
footnote:[Romans 13:3]
Having written this, he set his name to it, and gave it to captain Drury,
who delivered it to Oliver Cromwell.

After some time returning to the Mermaid, near Charing-cross, where G. Fox was kept,
he carried him to Whitehall,
and brought him before the Protector who was not yet dressed,
it being pretty early in the morning.
Coming in, George said,
"`Peace be in this house,`" and bid the Protector keep in the fear of God,
that he might receive wisdom from Him, and that by it he might be ordered,
and with it might order all things under his hands to God`'s glory.
He had also much discourse with him concerning religion,
wherein Cromwell carried himself very moderately,
but said that G. Fox and his friends quarreled with the ministers, meaning his teachers.
G+++.+++ Fox told him, he did not quarrel with them,
but they quarreled with him and his friends.
"`But,`" he continued, "`if we acknowledge the prophets, Christ, and the apostles,
we cannot uphold such teachers, prophets, and shepherds, as the prophets, Christ,
and the apostles declared against;
but we must declare against them by the same power and Spirit.`"
Moreover, he showed that the prophets, Christ, and the apostles preached freely,
and declared against them that did not declare freely, but preached for dishonest gain,
and divined for money, or preached for hire, being covetous and greedy,
like the dumb dogs that could never have enough;
and that those who had the same Spirit which Christ, the prophets, and the apostles had,
could not do otherwise but declare against all such now, even as they did then.
He also said, that all Christendom (so called) had the Scriptures,
but they lacked the power and Spirit, which those who gave them forth did have;
and that this was the reason they were not in fellowship with the Son,
nor with the Father, nor with the Scriptures, nor with one with another.
While he was thus speaking, Cromwell several times said, "`It is very good,`" and,
"`It is truth.`"
G+++.+++ Fox had many more words with him; but seeing people coming in,
George drew a little back, and as he was turning, Cromwell caught him by the hand,
and with tears in his eyes, said, "`Come again to my house;
for if you and I were but an hour of a day together,
we should be nearer one to another;`" and then added,
"`I wish you no more ill than I do to my own soul.`"
To this G. Fox replied, that if he did, he wronged his own soul;
and then bid him hearken to God`'s voice, that he might stand in His counsel and obey it;
and if he did so, this would keep him from hardness of heart;
but if he did not hear God`'s voice, his heart would be hardened.
This so reached the Protector, that he said, "`It is true.`"

Then G. Fox went out; and captain Drury following,
told him that the lord Protector said he was at liberty, and might go wherever he wished;
yet he was brought into a great hall, where the protector`'s gentlemen were to dine.
George asked why they had brought him there?
They told him it was by the Protector`'s order, that he might dine with them.
But George bid them tell the Protector he would not eat a bit of his bread,
nor drink a sip of his drink.
When Cromwell heard this, he said, "`Now I see there is a people arisen and come up,
that I cannot win either with gifts, honors, offices, or places;
but all other sects and people I can.`"
In response to this it was told him, that the Quakers had forsaken all that was theirs,
and were not likely to look for such things from him.

It was very remarkable that captain Drury, who, while G. Fox was under his custody,
would often scoff at him because of the nickname Quakers (which
the Independents had first given to the professors of the light),
afterwards came to him and told him that as he was
lying on his bed to rest in the day time,
a sudden trembling seized upon him, his joints knocked together,
and his body shook so strongly that he could not rise from his bed.
He was so shaken, that he had not strength enough left to rise.
But he felt the power of the Lord was upon him, and he tumbled off his bed,
and cried to the Lord, saying he would never more speak against the Quakers,
nor any such who trembled at the word of God.

The particular occurrences that befell G. Fox, when he was at liberty in London,
I pass by.
He had great meetings there,
and the throngs of people were such that he could hardly
get to and from the meetings because of the crowd.
In the meantime the number of his friends increased exceedingly,
and some belonging to Cromwell`'s court were also convinced of the Truth preached by him.
About that time he wrote several papers, one of which was against pride, gaudy apparel,
and the world`'s fashions.

I do not find that at this time there were any persecutions
from the magistrates at London,
but in other places there were.
And it was in this year that Anne the wife of John Audland,
coming into a steeple-house at Banbury, said (after the priest had finished),
that those who oppose the doctrine of Christ,
"`though they say '`the Lord lives,`' yet they speak falsely,`" according
to Jeremiah 5:2. For this she was imprisoned as guilty of blasphemy,
and two boys swore against her, that she had said that the Lord did not live.
Thus false accusations prevailed, and in this way persecution was cloaked.

The year drew now to an end, and Cromwell secured a peace with the United Netherlands;
for to get things more clear at home, it seems he endeavored to remove troubles abroad.
And there being a rumor spread of a plot against him (as has been hinted already),
in order to be more assured of the parliament,
he caused a guard to be set upon the door of the house to keep out whatever
members refused to sign a paper promising to be faithful to the Lord Protector,
and to make no alteration in the government as it was settled.
But several of the members would not sign this paper,
saying that it was a violation of the privileges
of the parliament and deprived them of their liberty.
Therefore these were kept out; but others who subscribed the said paper were admitted.
Yet this assembly, not acting to the satisfaction of Cromwell,
he dissolved them after a session of only five months.
Meanwhile, the young king Charles, who lived in exile,
had left France and come to Cologne on the Rhine, where he stayed for some time.

But I return to London, where we left G. Fox.
He was in that city continually at work, discharging his duty everywhere,
both by mouth and by pen, permitting no time to be lost.
There being commissioners appointed for the examining of ministers,
he wrote a paper to them,
wherein he advised them to see whether they were not such whom the prophets, Christ,
and the apostles disapproved; and who would "`flatter people to gain advantage,`"^
footnote:[Jude 1:16] etc.
He stayed at London till the year 1655, and after having cleared himself,
he went to Bedfordshire and came to the house of John Crook, a justice of peace,
where there was a large meeting.
Many were convinced of the Truth he declared, of which number John Crook also was one;
but for this he was soon dismissed from being a justice.

While G. Fox was in Bedfordshire, there was also Alexander Parker,
one of the early ministers among those called Quakers.
But leaving them there, I now intend to speak of Willam Caton, who,
as it has been said already, was one who lived in the family of judge Fell.
When he was but about fourteen years of age,
his father procured leave for him to dwell in the said family;
and his behavior was so pleasing,
that he was allowed to be the companion of the judge`'s son, both night and day.
He ate as he did, and went with him hunting, shooting, and fishing,
partaking of the same pleasure with him in everything, and living in ease and plenty;
so that he had cause to rejoice that Providence had cast his lot into such a noted family;
for not only judge Fell, but also his wife Margaret and their daughters,
were persons of quality.
Living with such choice company, William Caton grew up in piety,
and was very zealous in performing his private devotions,
staying often in the bed-chamber till the judge`'s son (his bed-fellow) had gone down,
so that he might more freely pour out his heart before God in prayer.
Having attained to the age of fifteen years,
he was very diligent to write down the chief points of the lectures he attended;
for such members of the family as could repeat sermons, and paraphrase thereupon,
were held in high esteem.
But William Caton found that what he reaped in this way,
would not satisfy the hunger and thirst of his immortal soul.

After he and the judge`'s son had for some time learned Latin together
in the family (for there was a priest that instructed them),
they were removed to a school at Hawkshead;
but William found the company of his school fellows
far less desirable than that of the judge`'s family.

It was in the year 1652, about Midsummer,
that G. Fox (as has been said in its proper place)
first came to the house of judge Fell at Swarthmore.
And though W. Caton wondered at his non-conformity to the ordinary salutations,
this did not hinder him from giving due attention to the doctrine which G. Fox preached,
which in substance was to give heed to the light
with which Christ Jesus had enlightened us,
and which, shining in our hearts, convinces us of sin and evil.
This so reached W. Caton,
that in due time he began to be subject to this inward convincement,
by which he came to be much restrained in his conduct,
and could not allow himself so great liberty as he was accustomed to do;
for though he was in no way extravagant,
yet now he saw that a true Christian must be weaned from all vanity,
and that the common diversions of youth were displeasing to God.
This he clearly perceived,
for the witness of God had awakened and reproved him for all that
was was contrary to true seriousness and sobriety of mind.
He had not yet finished school; but, though he was pretty far advanced in his learning,
the composition of Latin verses became a burden to him because he could
not give his thoughts the same liberty for invention as others did;
neither could he any longer give to the master of the school the compliment of the hat,^
footnote:[i.e. removing the hat and bowing.]
as he used to do (this I heard from his own mouth).
One may easily guess that hereby he was brought into a strait; but Margaret Fell,
seeing that he longed to be freed from the school, caused him to stay at home,
where he was employed by her in writing and teaching her children.
And when he was about seventeen years of age,
he became more and more strengthened in the spiritual warfare,
and his heart was often filled with joy,
because of the mercy and lovingkindness of the Lord to him.

Thus advancing in godliness,
he was frequently moved to go to the places of public worship,
and also to markets to call people to repentance;
and on these occasions beating and buffeting was his share,
and because of his youth he was despised by many.
Yet he did not faint; and soon,
esteeming it his duty to give himself to the ministry of the gospel,
he desired to be discharged from his service.
Judge Fell was very unwilling to part with him; but Margaret his wife,
though she could not easily give him up before,
yet believing that the Lord required his service, not only freely resigned him,
but also prevailed with her husband to let him go;
for he did not desire his liberty to serve other men,
but to enter into the service of the Lord, and to proclaim the everlasting gospel.
About the end of the year 1654, being eighteen years of age,
he took his leave of this family,
which was not done without mutual shedding of tears at parting.

He then went to visit his friends in Lancashire, Yorkshire, Derbyshire, and Warwickshire;
and from there to Norwich, and so to Wellingborough, in Northamptonshire,
where he found an opportunity to declare the Truth of God in the steeple-house.
After that he travelled to Cambridge, visiting his friends there,
and then returned to Norwich, where he visited his friends in prison,
and had large meetings in that city.
He then went to London,
where he was very kindly received by those of the household of faith;
and on a First-day of the week was at two steeple-houses.
At one of these he had great liberty to speak, being indeed very persuasive in speech;
and in the afternoon he had liberty to preach the Truth without opposition or
contradiction at a meeting of those who dissented from the public worship.
Many were added to the faith;
for at that time there were twelve ministering brethren in London,
most of them having come down out of the North of England.
Among these was John Stubbs, already mentioned, with whom William travelled into Kent;
and coming to Dover, where they were altogether strangers,
not knowing anybody in the town, they took their lodging at an inn.

John Stubbs went on the first day of the week to a meeting of the Baptists,
and William Caton to the steeple-house, where he had but little liberty granted him;
but in the yard he had more of an opportunity to clear his conscience to the people.
In the afternoon he went up to the castle, where the Independents performed their worship.
Shortly after, he and John Stubbs went into the Baptists`' meeting,
where there was a great number of people,
and many began to be affected with their testimony, and adhered to it.
This made such a stir, that they were hauled before the magistrates,
who examined them and ordered that none should entertain
them or they would face certain penalty;
whereupon they were turned out of their lodging.
But one Luke Howard, a shoemaker, who had already heard William Caton in London,
and afterwards at Dover in the steeple-house yard,
though he little regarded him at London, and said to his companion,
"`I know more than he can tell me,
or more than either I or he is able to live up to;`" yet
now he became so affected with William Caton`'s testimony,
that he invited him and John Stubbs to his house, where he entertained them.
And not long after this they had a meeting there,
and he heard the testimony of his guests with no less satisfaction
than Agrippa of old heard the speech of the apostle Paul,
when he said to him, "`You almost persuade me to be a Christian.`"^
footnote:[Acts 26:28]
For Luke Howard had not yet come so far that he could
resolve to conform himself with the Quakers (so called);
but even so,
such was his love to them that when the mayor of
the town sent four constables to his house,
with an order to deliver them up, that so they might be carried out of the town,
he refused to do so, relying on his right as a freeman of the corporation.
The doors being shut, he kept the constables out of his house,
and told them from the shop window that the mayor had no
lawful authority to have these men hauled out of his house,
and sent out of town, there being no public summons for them.
So they stayed some days longer in his house,
and he became so strengthened by their ministry, that he joined with them in profession,
and also gave up his house to become a meeting-place for their friends.

Then William Caton and John Stubbs departed the town and went to Folk-stone,
and from there to Hithe, in both which places they found opportunity to preach the Truth.
After some stay, they went to Romney, and so to Lydd.
Here it was that Samuel Fisher, both by their ministry,
and by that of Ambrose Rigge and Thomas Robinson (who now
had also gone forth in the service of the gospel) was convinced,
and brought over to their society.

Samuel Fisher was a man trained up in literature,
who had studied diligently in the university; and though but young then,
he was of a pious conduct,
and disliked many of the ceremonies and usual customs of the schools.
When he had finished his course of study there,
he was ordained a priest of the Church of England,
and a certain wealthy man took him to be his chaplain;
and after this he received a salary from the parish
at Lydd worth about two hundred pounds a year.
But after having been thus employed some time,
he came to see that infant baptism was a human institution,
and that to preach for wages was unlawful.
Now it is remarkable that the aforementioned Luke Howard,
some time before he knew the Quakers (so called),
not being satisfied concerning the singing of David`'s psalms at the public worship,
so troubled his master with whom he had been an apprentice, that he got Samuel Fisher,
as a learned minister, to come and discourse with him, and to try to convince him.
Samuel Fisher having come, Luke Howard told him, "`God is a Spirit,
and must be worshipped in Spirit and Truth by all who will worship Him acceptably.`"
Furthermore, he said, "`It is contrary to Truth for a proud man to sing David`'s words,
that '`his heart is not haughty, nor his eyes lofty,
neither did he concern himself with things that are too profound for him,`"^
footnote:[Psalm 131:1]
when he lives in pride, which God resists.`"
Moreover, he thought it "`very indecent for man to sing,
'`Rivers of tears run down my eyes, because other men do not keep Your law,`'^
footnote:[Psalm 119:136]
when he had never known a true sorrow and repentance for his own sins.`"
These comments of Luke Howard against the customary singing in
their worship services had so much influence upon Samuel Fisher,
that from that time onward he stopped giving out
David`'s conditions to the people to sing.
And in time,
becoming more and more uneasy to go on in a role that was burdensome to his conscience,
he resolved to desist from his ministry,
and so went to the bishop and relinquished the commission
that he had received from him to preach.
Then, casting himself upon God`'s providence, he took a farm, and turned herdsman,
by which means he maintained his wife and children in much greater peace than before.

Having departed from the Episcopalian church, he went over to the Baptists,
and became a zealous teacher among them.
It was about this time, that William Caton and John Stubbs came to Lydd,
whom Samuel Fisher received into his house, remembering that Scripture exhortation,
"`Be not forgetful to entertain strangers,
for many thereby have entertained angels unaware.`"^
footnote:[Hebrews 13:2]
William Caton went to the meeting of the Independents,
and Stubbs went to that of the Baptists, where Fisher then preached.
Being given an opportunity to speak,
Stubbs declared Truth so plainly that Samuel Fisher (being very much affected
with it) began to paraphrase upon it with excellency of speech.
Departing this place, William Caton and John Stubbs went to another town in this county,
but not long after returning to Lydd,
they found Samuel Fisher in fellowship with themselves.
For it had happened that his fellow-teacher, George Hammond, in a sermon,
so violently inveighed against those called Quakers,
that Samuel Fisher could not be satisfied until he stood up in the meeting,
and bore a testimony against the revilings of Hammond; saying to him, "`Dear brother,
you are very near and dear to me, but the Truth is nearer and dearer.
It is the everlasting Truth and gospel which they hold forth.`"
And speaking more words to this effect,
he openly defended the doctrine of the reviled Quakers.
This so vexed Hammond, that falling into an even greater rage, he said,
"`Our brother Fisher is also bewitched!`"
But Fisher returned not reviling for reviling, but continued with patience in the faith.
And this was he who afterwards wrote a book called Rusticus ad Academicos,
wherein he often confounded the priests with their own weapons;
for he was very dexterous at this, and was so well versed in the ancient poets,
that he now and then (with their words) gave strong blows to his adversaries,
allowing himself sometimes the freedom of the prophet
Elijah against the prophets of Baal.
He wrote also a paper in Hebrew to the Jews, in which language he was very skilled.
