== Chapter V

[.section-date]
1654--1656

But before I say more of Fisher, I return to William Caton and John Stubbs.
These went from Lydd to Ashford, Tenterdeu, Cranbrook, and Staplehurst,
where they found an open and tender-hearted people who embraced their doctrine,
and some would have given them money, yes, even forced it upon them,
but they would not take any.
For as they had freely received, so they freely gave,
and told the people it was not theirs, but them, which they sought.
From there they travelled to Maidstone,
where John Stubbs went to the public place of worship,
and William Caton to the meeting of the Independents.
Stubbs was apprehended at the steeple-house, and Caton, the day following,
was taken from his inn, and both were sent to the house of correction,
where they were searched, and their money, inkhorns, and bibles,
etc. were taken from them.
Afterwards they were stripped, and their necks and arms were put in the stocks,
and in that condition they were desperately whipped.
A hard sentence indeed, especially for such a young man as William Caton was;
but they were supported by an invisible hand.

After this, means were used to compel them to work;
and it was told them that "`he who would not work, would not eat.`"
But they did not feel free to consent to such demands, because they esteemed it unjust,
not being guilty of the breach of any law.
Thus they were kept without food for some days,
only a little water once a day was allowed them.
In the meantime, the felons that were there would have given them some of their bread;
even the women of the house (being moved with compassion)
would have given them something secretly;
but they did not feel free to accept of either.
Now the report of this cruelty having spread in the town,
many began to be offended at it;
so that an officer was sent to make restitution of some
of their possessions which had been taken from them,
and then they bought food with their own money.
Not long after this they were separated, and conveyed by officers out of the town,
one at one end of it, and the other at the other.

At length William Caton came to London where he found his companion John Stubbs;
but having come there,
it came upon them from the Lord to return to the town from which they had been expelled,
which was no small trial to them.
Nevertheless they resigned, and gave up to what they believed to be the will of the Lord.
Now Providence so ordered it that no one meddled with them when they had returned,
even though, in order to be more fully seen,
they went to the steeple-house on a First-day of the week.
They went also to Canterbury, where, at the meetings of the Baptists and Independents,
they had pretty good liberty to declare the Truth among them; and some, being convinced,
received their testimony.
They were likewise at Sandwich,
where William Caton had some service among the Dutch people at their steeple-house.

It was now near Midsummer,
and he felt a motion to go over to Calais, in France.
For thus purpose he went to Dover, and so sailed to Calais,
where coming to their high place of worship,
his spirit was very much grieved and burdened with
the great idolatry that was in vogue there;
for he saw how some were worshipping before their dumb idols,
and he could not well ease his spirit for lack of speaking the language.
Having walked for some time in the town,
his presence came to be known by some of the chief men of the city,
who desiring to speak with him, came down in person to the dock to look for him;
and understanding he was aboard the ship,
he was called ashore and conveyed to a large house,
where several had come to see and hear him.
There being a Scotch lord who interpreted for him,
he had a very good opportunity to declare the Truth among them.
And after he had cleared his conscience, they allowed him to depart quietly.

Soon after this he returned for England and found his companion John Stubbs at Dover;
and it resting upon Stubbs to go for Holland, William Caton felt free to accompany him.
With this intent, they went together to Yarmouth,
but could not find a passage there for Holland, and so they passed further to the North.
Coming eventually to Swarthmore, Caton found his friends very glad to see him,
especially Margaret Fell, who had been as a nursing mother to him.
After a short stay there, having been abundantly refreshed, they went to Shields,
where they heard of a ship bound for Flanders; but having little inclination to go there,
they returned soon after to Yarmouth, where they found a ship intended for Flushing,
in Zealand.
With this vessel they went over the ocean, and arrived safely at the said town.
And on the First-day of the week,
they went to the congregation of the English and Scotch,
where many wondered at them because of their non-conformity;
and after they began to speak,
there arose a great stir that they were soon hurried out of the house.

The same day they went to Middleburg before their afternoon`'s worship had ended,
and one of them began to speak after the priest had finished.
But he was immediately stopped,
the priest thinking at first that they were such as came there begging;
but perceiving the contrary, he and others were the more violent with them.
After this, the priest sent for them to his house, and reasoned awhile with them there;
but he being of a lofty mind, they found but little reception there.
After a short stay in town, they embarked for Rotterdam, in Holland, where,
after a few days in the city, they obtained a meeting at an English merchant`'s house.
But finding that the man who interpreted for them did not render their words rightly,
it seemed not to satisfy the hearers.
After some time they returned to Zealand, and from there again to England,
where having arrived, William Caton journeyed to Swarthmore,
and was received there with joy.
Then feeling some drawings to Scotland, he went to Bishopric,
where he found his companion John Stubbs again, with whom he travelled towards Scotland.
It was about the beginning of the month called December
when they came to Berwick upon Tweed.
William Caton went into the large public assembly, and when the priest had finished,
stepped upon a seat and began to speak, while the priest made haste to get away.
There he spoke with great boldness, and had pretty good liberty to declare the Truth.
But when he had finished, he was taken hold of and brought before the magistrates,
who ordered that he should be turned out of the town; which was done.
John Stubbs was that day in a meeting of the Baptists, and had some service there.
Not long after, W. Caton (after wandering up and down,
and not finding any who would lodge him for his money) returned,
and came into the town again, the guard allowing him very freely to pass.

Then they both travelled to Edinburgh, in Scotland,
where they found the affairs of the church somewhat out of order,
through the unfaithfulness of some that had been convinced of the Truth;
but their ministry was so effectual among them,
that they were brought into better order again;
and so they edified the church according to their ability.
The meeting was there kept at the house of William Osborn,
who had been a lieutenant-colonel,
and afterwards become a zealous minister among the flock of Christ.
While Caton was there, he went once to the chief steeple-house, where,
after the priest had finished, he spoke to the people.
But the multitude quickly collecting, he was not allowed to say much,
but was carried out; and coming into the street,
found a guard of soldiers who conducted him with
drawn swords to the places where he desired to be.
He was about that time also with general Monck,^
footnote:[General George Monck (1608-1670) was an English soldier and politician,
and a key figure in the Restoration of the monarchy to King Charles II in 1660.]
who behaved himself moderately, and heard him.
John Stubbs now returning to England, William Caton went to Stirling,
where he was brought before the governor, who at first appeared proud;
but when Caton (who was a man of meek behavior) had spoken a little to him,
he became cool and sedate.
He then went to the English chaplain`'s house, who was kind to him.
From Edinburgh he went to Glasgow, where,
going into the great cathedral after the service had ended,
he had some liberty to speak to the multitude in the yard,
the rude people being kept calm by the English soldiers, who were moderate;
so that he had very good service there.
He also went to Douglas, where his services were similar,
both in the steeple-house and elsewhere.
Thus, having cleared himself in Scotland, he returned to England,
and came again to Swarthmore, where he was received as formerly in very great love.

Leaving him there, I turn again to George Fox, whom we left in Bedfordshire.
From there he went by London to Kent, and came to Romney,
not long after William Caton and John Stubbs had been there.
Here he had a very large meeting, where Samuel Fisher came also,
and there was a great convincement that day,
so that many were turned to the light of Christ.
And after the meeting Samuel Fisher`'s wife said,
"`Now we may discern between flesh and spirit,
and distinguish spiritual teaching from fleshly.`"

From here G. Fox went to Dover and Canterbury, and further into Sussex,
and so to Reading, where they had a large meeting, and many were convinced that day.
To this meeting came also George Bishop of Bristol, who, being a captain,
then wore a sword, though in time he entirely left it off.

G+++.+++ Fox, going from here, passed up to London, where we will leave him for a time,
and go on to behold the life and occurrences of James Parnell, who was born at Retford,
in Nottinghamshire, and trained up in the schools of literature.
This young man labored very early in the ministry of the gospel,
having been convinced by G. Fox when not quite sixteen years of age;^
footnote:[This took place in 1653, while George Fox was in prison at Carlisle,
in whose journal we find it stated, "`While I was in the dungeon in Carlisle,
James Parnell,
a little lad of about sixteen years of age came to see me and was convinced.`"
Prior to this, James Parnell had not had any interaction with Friends,
although the people with whom he had before associated in
religious worship had been brought very near to their principles.
From what we find in Parnell`'s writings,
it is evident that before this time he had already experienced real conversion of heart,
had been brought to see the formality of the priests,
and had separated himself from the customary form of worship to wait on the Lord alone;
so that by this interview with George Fox,
he was merely convinced that the Truth which Fox preached was the same
as that into which he had himself been led by the Spirit of Truth.]
however, for embracing the Truth he was despised and rejected by his relations.
Though low of stature, he was endued with great abilities, and did not fear,
wherever he came, to call people to repentance.
Being imprisoned at Cambridge for his zealous testimony,
and afterward cast out of the town like a vagabond,
he soon came back and disputed with the students of the university,
but met with rude and bad entertainment from them.
In the beginning of this year he came into Essex, being then about eighteen years of age,
and preached the gospel in several parts of that county, such as Felsted, Stebbing,
Witham, Coggeshall, Halsted, and other places,
and many received the word by his ministry.
About the middle of the summer he came to Colchester,
and there preached the gospel on a First day of the
week in a steeple-house after the sermon had ended.
He then preached in a large meeting appointed for that purpose,
and afterwards disputed with the town-lecturer and another
priest in the French school--all of this in one day.
Many were convinced of the Truth preached by him, and among these also was Stephen Crisp,
of whom more will be said hereafter.
James Parnell spent that week in the said town, preaching, exhorting, and disputing,
to the convincing of many; though others were enraged, insomuch,
that his godly zeal was often rewarded with blows.
Once when coming out of Nicholas`' steeple-house,
he was struck by one with a great staff, who said, "`There,
take that for Christ`'s sake!`"
To which Parnell meekly answered, "`Friend, I do receive it for Jesus Christ`'s sake.`"
Many other grievous abuses he bore without showing any heat or anger,
so that he was a real pattern of patience and meekness.

Having labored in the gospel about ten days in Colchester, he went to Coggeshall,
where a fast was proclaimed to be held upon the 12th of the month called
July to "`pray against the errors of the people called Quakers.`"
Having come there,
James Parnell went into the steeple-house and stood
still till the priest was coming out of the pulpit.
Now since this priest Sammes, who was an Independent,
had cried out fiercely against the Quakers, calling them deceivers, etc.,
Parnell esteemed it his duty to say something in response to that.
The first words he spoke were, "`This is the order of the true church:
'`that all may speak one by one; and if any thing be revealed to him that stands by,
let the first hold his peace.`'`"^
footnote:[1 Corinthians 14:30-31]
Then he began to speak on behalf of those called Quakers.
But the priest, interrupting, asked what he would object against him?
To which J. Parnell answered, "`In that you reviled the people called Quakers,
and said they were built upon a sandy foundation, and so called them Shakers.
But,`" said he, "`I will prove their foundation not to be sandy,
and you to be a false prophet.`"
After some more words spoken by him, some accused him that he acknowledged no church.
This he said was false.
Then it was asked him what church he acknowledged?
And he answered, "`The church in God.`"
Then priest Willis stood up and said he spoke nothing but nonsense.
But Parnell desired him to name one word which he had spoken that was nonsense.
To this Willis said, "`To say '`the church in God.`'`" Then Parnell took out his bible,
and read 1 Thes.
1:1, where the apostle writes "`to the church which is in God the Father.`"
The priest now was at a loss,
and Parnell told him that he blasphemed in saying the church in God was nonsense.
Then priest Stellum stood up and accused Parnell with lies and slanders,
and not permitting him to respond to those accusations,
he got up into the pulpit and began to pray.
But Parnell not taking off his hat, the magistrates called to him to put it off.
To which he returned, "`Why not order the priest to put off his cap?`"
And then further said, that instead of being subject to their wills,
he would rather go out of the meeting place; and so he went out.

Not long after,
justice Dionysius Wakering followed him and struck him with his hand upon his back,
saying he arrested him in the name of the Lord Protector.
Parnell, not knowing him to be a magistrate, asked him where his court order was.
Wakering said he had one, but showed none.
He was brought where four justices and six or seven priests had met together.
Then justice Wakering pulled Parnell`'s hat from his head,
and threw it away and they questioned him concerning many things;
all of which he answered, along with many frivolous questions asked only to ensnare him.
At last he was committed to the common jail at Colchester,
where none of his friends were permitted to come to him.
When the time of the court sessions at Chelmsford had come, he,
with several felons and murderers,
was fastened to a chain and thus led about eighteen miles through the country,
remaining chained both night and day.

Having been brought into the court before judge Hills,
the jailer took off his hat and cast it upon the floor.
Then the clerk read his indictment, and asked him if he was guilty.
To this Parnell said he denied all guilt, and asked to see his accusers.
The judge said he would see them,
but that he first ought to say "`guilty,`" or "`not guilty.`"
Upon which Parnell told him, he was not guilty.
Then a jury of twelve men was called (whose foreman was a drunkard);
priest Willis was also called, who swore his oath against him, along with two justices.
The accusations were that,
in a riotous manner he had entered into the parish church at Great Coggeshall,
and there stood up and told the minister he blasphemed and spoke falsely,
and used many other reproachful words against him.
Moreover, it was alleged that he could not give a good account where he was last settled,
or anything concerning his life and conduct, and so appeared to be an idle person.
And finally he was accused with contempt of the magistracy and of the ministry.
To all of this Parnell answered,
that he in no way entered the steeple-house in a riotous manner,
but came there quietly and alone;
for being followed by several boys that would have come in after him,
he asked them to go in before him,
rather than to enter in a disorderly manner whereby to occasion any disturbance.
That he had said to priest Willis,
he blasphemed by saying the church in God was nonsense, he did not deny;
but did not acknowledge himself to be a vagabond or an idle person.
Moreover he did not think it indecent to call an unjust judge, unrighteous; a persecutor,
persecutor; and a deceiver, deceiver.
Thus Parnell pleaded his cause.
Yet the judge said to the jury, that if they did not find him guilty,
the sin would be upon their heads;
thus condemning the prisoner before the jury had considered the case.
Then Parnell began to speak in order to inform them concerning his motive,
but the judge would not permit him, though one of the jury desired him to continue.
After consulting together,
the jury had nothing to lay to his charge (except
for a paper in which he had answered the court order,
though he had already acknowledged this paper to be his writing).
Yet the judge and the clerk strove to draw some words from the foreman,
which the other jurymen did not consent to,
and he himself was unwilling to fully answer their intentions.
Then Parnell was made to withdraw from the court; and being called in again,
the judge fined him the value of about forty pounds,
for contempt of the magistracy and ministry; "`for,`" he said,
"`the Lord Protector has charged me to punish such persons
as should contemn either magistracy or ministry.`"
Thereupon James Parnell was carried back again to the prison,
being the ruins of an old castle, built, as it is reported,
in the time of the ancient Romans.^
footnote:[Colchester Castle is a Norman castle,
built in the later half of the 11th century.
The castle is still standing at this day (January 2020),
and is currently used to house the Colchester Museum,
with its large collection of Roman exhibits.]
Here he was to be kept until the fine should be paid;
and the jailer was commanded not to let any "`giddy-headed people`"
(by which they meant his friends) come to see him.

The jailer was willing enough to comply with this order,
for he allowed none to come to him but such as abused him.
And his wife, who was a wicked shrew, not only set her servant to beat him,
but several times herself laid violent hands upon him,
and swore she would have his blood.
She also set other prisoners to take away the food
that had been brought to him by his friends;
and would not let him have a trundle bed which they
would have brought for him to lie upon,
so that he was forced to lie on the cold and damp stones.
Afterwards he was put into a hole in the wall,
a room that looked much like a baker`'s oven;
for the walls of that building are of an excessive thickness, as I have seen myself,
having been in the hole where this pious young man ended his days,
as will be said by and by.
Being confined in the said hole in the wall (which was, as I remember,
about twelve feet from the ground), and the ladder being six feet too short,
he was made to climb up and down by a rope on the broken wall in order to fetch his food,
or other necessities.
For though his friends desired to give him a cord
and a basket in which to draw up his food,
yet such was the malice of his keepers that they would not allow it.

Continuing in this moist hole, his limbs grew numb; and once it happened that,
as he was climbing up the ladder with his food in one hand,
and had come to the top thereof, reaching for the rope with his other hand, he missed,
and fell down upon the stones, whereby he was exceedingly wounded in his head,
and his body was so bruised that he was thought to be dead.
They then put him into a hole underneath the other;
for there were two rows of such vaulted holes in the wall.
This hole was called "`the oven,`" and was so little,
that some baker`'s ovens are bigger, though not so high from the ground.
Here there was scarcely any air, for the door was shut, and there was no window or hole.
And after he had a little recovered from his fall,
they would not allow him to go out for fresh air,
though he was almost spent for lack of breath.
And though some of his friends (namely William Talcot and Edward Grant)
did offer their bond of forty pounds to the justice Henry Barrington,
and another (whose name was Thomas Shortland) offered to lie body for body in his place,
so that Parnell might but have his liberty to come to W. Talcot`'s house,
and then return when recovered; yet this was denied.
Indeed, so immoveable were they set against him,
that when it was desired that he might only walk a little sometimes in the prison yard,
they would not grant it by any means.
Once, the door of the hole being left open,
he came forth and walked a bit in a narrow yard between two high walls.
But this so incensed the jailer, that he locked up the hole,
and shut him out in the yard all night, being in the coldest time of the winter.
This hard imprisonment did so weaken him,
that after ten or eleven months he fell sick and died.
At his departure there were with him Thomas Shortland and Ann Langley;
and it was one of these (who had come often to him) who
long after brought me into the hole where he died.

Several things which are related here, I have from the mouth of eyewitnesses,
who lived in that town.
When death approached, he said, "`Here I die innocently.`"
A little after he was heard to say, "`Now I must go;`" and turning his head to Thomas,
he said, "`This death I must die.
Thomas, I have seen great things; don`'t hold me here, but let me go.`"
Then he said again, "`Will you hold me?`"
To which Ann answered, "`No, dear heart, we will not hold you.`"
He had often said that one hour`'s sleep would cure him of all;
and the last words he was heard to say,
were "`Now I go;`" and then stretched himself out, and slept about an hour,
and breathed his last.
Thus this valiant soldier of the Lamb conquered through sufferings.
But so great was the malice and envy of his persecutors,
that to cover their guilt and shame,
they spread among the people that by immoderate fasting,
and afterwards with too greedy eating, he had shortened his days.
But this was a wicked lie;
for though it was true that he had no appetite to
eat for some days before his last sickness,
yet when he began to eat again, he took nothing but a little milk,
as was declared by credible witnesses.
During his imprisonment he wrote several edifying epistles to his friends.

By continuing this relation without breaking off, I have advanced somewhat as to time;
but now going back a little,
let us see the transactions of Edward Burrough and Francis Howgill.
It was in the summer of the year 1655 that they went together to Ireland,
and stayed more than six months.
They spent about three months at Dublin without being disturbed,
though they omitted no opportunity to declare the doctrine of Truth.
Henry Cromwell, son of the Protector, was at that time lord deputy of Ireland;
and it was in his name that they were carried from
Cork (where they were gone) back to Dublin;
for since several had received their testimony and adhered to the doctrine they preached,
it was resolved upon not to let them stay any longer in Ireland.
Here it was (as I have been told) that William Ames,
by the ministry of Burrough and Howgill,
was brought over into the society of the Quakers (so called).
He was a Baptist teacher, and also a military officer,
who being of a strict life himself, kept his soldiers under a severe discipline.
I remember he used to tell us,
how when any soldier under his colors was found guilty
of any immorality on a First-day of the week,
he presently had him bound neck and heels.
But being now entered into the society of the despised Quakers,
and in process of time becoming a minister among them,
it was not long before he was cast into prison; about which more will be said hereafter.

Now Edward Burrough and Francis Howgill were banished out of Ireland;
but on the same day that they were sent away, Barbara Blaugdone arrived there.
She went from England in a vessel bound for Cork,
but because of foul weather she was carried to Dublin.
When the tempest was high, the seamen said that she being a Quaker was the cause of it,
and they conspired to cast her overboard.
Aware of this plot, she told the master what his men designed to do,
and said that if he did permit this, her blood would be required at his hands.
So he charged them not to meddle with her.
The storm continuing, and it being the First-day of the week, she went upon the deck,
feeling herself moved to speak to the seamen by way of exhortation, and to pray for them;
for their priest (who was afraid like the rest) could not say anything among them.
Having spoke what rested upon her, she concluded with a prayer;
and all the ship`'s crew became very quiet and sedate,
saying they were more obliged to her than to their priest, because she prayed for them;
and he, for fear, could not open his mouth to speak.
At length they arrived safe at Dublin, without any damage, which indeed was strange,
and made the master of the vessel say that he had never
been in such a storm without receiving any loss.

Having gone ashore, she went to the house of the deputy;
but the people there told her she would not be permitted to speak with him;
for he had just banished two of her friends out of the nation the day before.
Then she met with the secretary, and desired him to help her speak with the deputy.
He answered that he did not think he could.
She then asked him if he would be so civil as to go up and tell the deputy
that there was a women below that desired to speak with him;
and if he then refused, she would take that for her answer.
So the secretary went up, and soon a man came to fetch her into a private room;
and after she had been there awhile, a person came out of the deputy`'s chamber,
and all who accompanied him stood by with their hats off;
for they knew she had never seen the deputy.
But she had a sense that this man was a priest,
who had appeared with his hat on to deceive her.
The room being almost full of people,
they asked her why she did not give her message to their lord.
But she answered, "`When I see your lord, then I shall give my message to him.`"
A little after this the deputy came forth, and sat down on a couch.
Barbara then stood up, and speaking to him what was upon her mind,
bade him beware that he was not found fighting against God in opposing the Truth,
and persecuting the innocent; but likewise Gamaliel, to let them alone;
for if it was of God, it would stand; but if of man, it would fall.
Further, she told him that the enmity did not lie so much in himself,
but that he was stirred up to it by evil magistrates and bad priests;
but that God`'s people were as dear to him now as ever; and they who touched them,
touched the apple of his eye.
"`But now,`" she said, "`in your name, and by your power,
there was much hurt done to the people of God all over the nation,
and it will lie heavy upon you at last.`"
Moreover, she told him that the teachers of the people did cause them to err,
and that he knew the priests`' condition.
Touching upon this subject, the deputy said to the priest that stood by,
"`That`'s for you, Mr. Harrison!`"
She spoke with such power that it made the deputy much concerned;
and when she had finished,
he asked the priest what he had to say to that which she had spoken.
And he said, it was all very true and very good,
and that he had nothing to say against it, if she did speak as she meant.
Then she told the priest, that the Spirit of God was true,
and did always speak as He meant, and meant as He spoke;
but that men of corrupt minds did pervert the Scriptures
by putting their own imaginations and conceivings upon them,
and so did deceive the people.
But the holy men of God wrote and gave forth the
Scriptures as they were inspired of the Holy Spirit;
and so they are of no private interpretation,
nor can they be understood but by the same Spirit that gave them forth.
After having thus spoken, she went away and returned to her lodging,
which was at one captain Rich`'s house.
And this captain coming home,
told her that the deputy was so sad and melancholy after she had been with him,
that he could not go to lawn bowling, or to any other pastime.

Barbara having now performed her service at Dublin, went to Cork,
where she had some relations and acquaintances;
but great were her sufferings in those parts,
for she was imprisoned in almost every place she went,
being moved to follow her acquaintances into several
steeple-houses in order to declare the truth.
Yet wherever her mouth was opened, there were some who received her testimony.
Once she was made to speak in a market-place where
a butcher swore he would cleave her head;
and having lifted up his cleaver to do it, a woman came up behind him,
caught his arms and stopped him, until some soldiers came and rescued Barbara.
Many of her acquaintances, whom she knew very well, were now afraid of her;
for sometimes she spoke with such power in their houses that it made them tremble.
Some said she was a witch; and, running away, had the servants remove her from the house.

After having been there some time, she returned home to Bristol,
but it was not very long before she was moved to go to Ireland again;
and having come near Dungarvon, the ship capsized near the shore.
The master and the passengers got into a boat,
save one man and a woman who were swept away; and Barbara, who was still in the cabin,
was almost stifled by waves that beat in upon her;
yet at length she got up upon the deck.
The master in the meantime having come ashore,
called to her saying that if she would leap down,
he and another would venture to come into the water to save her.
Accordingly they came out up to their necks, and when she leaped they caught her;
but having become entangled in the ropes in leaping down,
she was drawn away from them again.
But presently a wave rolled in and beat the ship outward,
which was to their preservation; for if it had beaten the ship inward,
it might have killed all three of them.
They soon caught hold of her again, and drew her to shore.
From there she went to Dublin, where, coming into the court of justice,
she spoke to the judges, and exhorted them to righteousness.
But this was taken so poorly that she was put into prison,
where she lay upon straw on the ground, and when it rained,
the excrement from the lavatory ran in underneath her.
Being charged at the court, she was required to plead "`guilty`" or "`not guilty.`"
She answered that there was no guilt upon anyone`'s conscience
for what was done in obedience to the Lord God.
But not answering in the particular form of words they required of her,
she was sent back to prison again, where she suffered much.
In the meantime, there happened a remarkable instance,
which I cannot pass by with silence.

At that time there was in prison an innkeeper with his family, being accused of a murder.
Now the brother of the one who was either murdered or lost,
could not inherit some land unless he could prove that his brother was dead;
and in order to do so,
he brought a fellow into the prison who said he would
prove that the man had been killed at such an inn,
and buried under a wall.
So he accused the innkeeper and his wife, their servant, maid,
and a blacksmith of being guilty of this murder; they being already in prison.
Having heard of this, Barbara found means to go to this desperate fellow,
and asked him how he could conceal this murder so long,
when he was (according to law) as guilty of it as any of them, if what he said were true.
At this question the man trembled so exceedingly that his knees struck one against another,
and he confessed that he had never before seen the people with his eyes,
nor was he ever at the place in his life, nor knew anything of it,
but had been drawn in by the man who desired to inherit the land,
and was persuaded to act as a witness to the murder.
Other prisoners heard this confession also, and Barbara sent to the deputy,
desiring him to send down his priest, that he might hear the said confession.
The priest came, and the fellow confessed the same to him as he had done to Barbara;
and he once also confessed the same before the judge.
But afterwards he ate his words;
for the man who had induced him to testify came every day,
and made him drink plentifully,
and also caused the jailer to lock up Barbara so that she might not come to him.
She then wrote to the innkeeper, and his wife and servant, and also to judge Pepes,
telling him that the day of his death drew nigh wherein
he must give an account for his actions,
and that therefore he ought to take heed that he did not condemn innocent people,
having but one witness, in whose mouth were found so many lies,
the others all saying they were innocent.
But for all this, judge Pepes went on and condemned all the accused,
and the accuser also, as being conscious of the crime.
Hereupon a priest came to speak with the maid that was condemned,
who was in the same prison with Barbara, but she would not see him, saying, "`No,
he can do me no good; I am done with man forever; but God,
you know that I am innocent of what they lay to my charge.`"
Thus they were all hanged, and the witness first,
probably for fear that he should have changed his
confession after he saw the others hanged.

Now some friends of Barbara, namely, Sir William King, Colonel Fare, and the Lady Brown,
hearing she was in prison, came to see her,
and afterwards went to judge Pepes to get her released.
But when they came to him, he told them that he was afraid for his life.
At this they laughed, and said they had known Barbara from a child,
and there was no harm in her at all.
And being all very earnest to get her liberty, they at last obtained it.
Then Barbara went to the steeple-house where this judge was, and cleared herself of him;
and he, having come home, went to bed, and died that night.
The news of his sudden death being spread abroad,
made people say that Barbara had been a true prophetess unto him.

She now went to Limerick, where she was put into prison, but after a while,
being released, she took shipping for England again.
At sea she was robbed of all that she had by a privateer, who, coming on board,
took the master of the vessel away until he should
pay a particular sum of money for the ship and goods.
Nevertheless, she came safe to England, always traveling at her own expense,
paying for what she needed.

But leaving her, I will return to Miles Halhead, who,
as he was following the plough in the beginning of this year,
felt a motion to go to London.
Passing by York and Hull on his way,
and going from there through Lincolnshire and Leicestershire,
he came to the city of London, from which, after some stay,
he went to Bristol with Thomas Salthouse, and so to Exeter and Plymouth,
where he suffered much persecution and was imprisoned about one year.
About this time, he wrote a letter to his wife, which I think worthwhile to insert here.
It is as follows:

[.embedded-content-document.letter]
--

[.salutation]
Anne Halhead,

My dear heart, my dear love in the Lord Jesus Christ salutes you and my children.
My soul, my soul is poured forth in love to you daily,
and the breathing of my soul to my Father is for you,
that you may be kept in the fear of the Lord, and in His counsel daily,
that so you may come to the rest and peace that is laid up for all who fear Him,
and walk in obedience to the light with which Jesus Christ has enlightened them.
So my dear heart, I declare to you, in the presence of the living God,
who is Lord of heaven and earth, and before men and angels,
there is no other way that leads to peace and eternal rest,
but walking in obedience to the light that comes from Jesus Christ,
and of this light you have received a measure.
Therefore my dear heart, be faithful to the Lord in what is made known unto you,
that you may come to witness true peace and rest, for eye has not seen, nor ear heard,
neither has it entered into the heart of man, what is laid up for all who fear Him.

So, my dear heart, as I have found peace and eternal rest to my soul from the Lord,
so I am moved of the Lord in love to your soul,
to show you the way that leads to peace and eternal rest; which way is Christ,
who is the light, and the way that leads to the Father, from which all light comes;
and of this light which comes from Christ,
I bear record that you have received a measure.
Therefore, in dear love, I exhort you to walk in obedience to your measure,
which you have received from the Lord.
And in the presence of the Lord God I do declare,
that walking in obedience to this light that comes from
Christ is the way that leads to eternal rest and peace.
Therefore, as you care for the eternal good of your soul,
be faithful to the light that comes from Christ, which light bears witness against lying,
and swearing, and vain talking, and all manner of evil.

So, my dear wife, in dear love to your soul, which is more precious than all the world,
I have showed you the way.
If you will walk in it, it will lead you into the eternal covenant of life and peace.
So, my dear wife, in love, in love I have cleared my conscience to you,
in the presence of the living God, as a true and faithful husband to you,
desiring your eternal good and welfare as my own, the Lord God is my witness.
Dear wife, remember my dear love to all my friends and countrymen,
according to the flesh; for I desire the eternal good and welfare of you all,
and that you all may come to believe in the light in your own consciences,
with which Jesus Christ has enlightened you; which light bears witness against lying,
and swearing, and all manner of evil.
This is the light of Christ,
and walking in obedience to this light is the way that leads out of sin and evil,
up to God eternal, blessed forevermore.
And he that acts contrary to this light in his own conscience, it is his condemnation.
Now, dear friends, while you have time, prize it.

[.signed-section-closing]
Your husband, and a lover of your soul,

[.signed-section-signature]
Miles Halhead

[.signed-section-context-close]
Wiltshire, the 7th of the Third month, 1655.

--

[.offset]
This year also he wrote the following epistle to his fellow-believers.

[.embedded-content-document.letter]
--

Dearly beloved friends and brethren in the North of England, even to the South,
the land of our nativity,
whom the Lord God of heaven and earth has called and chosen
in this the day of His eternal everlasting love,
to serve Him in truth and in righteousness,
who have received the Lord`'s Truth in the love of it, not only to believe in His name,
but to suffer bonds and imprisonments,
and hard sentences for the Word of God and the testimony of Jesus.
Dear friends, and beloved brethren, my prayers to the Lord God of heaven and earth,
and my soul`'s desire is for you all,
that you may all dwell together as children of one Father,
in the eternal bond of love and oneness of the Spirit;
that you may all grow in the eternal living Truth of God,
to be established upon the rock and sure foundation,
that the gates of hell and death cannot prevail against you.
May you all be kept and preserved in peace and rest
under the shadow of the wings of the Almighty,
now in the day of trial and hour of darkness, when hell has opened her mouth,
and the raging sea has cast out her proud waves, even to overflowing of the banks.

Glory, glory,
and eternal living praises be given to the Lord God of all the children of the light,
and to the Lamb forevermore, who has found a resting place for all His dear ones, lambs,
and babes, and children of light to flee into, in the needful time of trouble,
where none can make them afraid, nor take away their peace,
as they abide faithful to Him, who is our way, our light, our life, our strength,
and eternal portion forever.
My dear friends and brethren, I beseech you in dear and tender love,
that you walk as dear children,
faithful to Him who has called you with an honorable calling,
and loved you from the beginning with an everlasting love,
that all your friends and neighbors and men of this world,
that see your life coupled with fear, may be made to confess and acknowledge,
to the honor and glory of the living Lord,
that the God whom we serve and fear is the only true God of Israel.
Herein you become a precious savour unto the living eternal God,
and a sweet smelling savour unto all the children of light,
and no good thing will the Lord God withhold from you.
The mouth of the Lord God of Hosts has spoken it,
whose promises are yes and amen to His own seed forevermore.

[.signed-section-signature]
Miles Halhead.

[.signed-section-context-close]
Given forth the 14th of the Sixth Month, 1655,
when I was a prisoner at the prison-house in the city of Exeter, in Devonshire,
for the testimony of Jesus, and the word of God.

--

A chief cause why he was imprisoned there, was that Thomas Salthouse,
with whom Miles travelled,
had asked George Brooks (a priest belonging to the Nightingale frigate
who had spoken many good words in favor of the Quaker`'s doctrine),
whether he lived the life of what he spoke?
Further, he said, "`He that does not enter by the door, but climbs up some other way,
is (as Christ said) a thief and a robber.`"
For Thomas Salthouse thought (and not without good reason,
as will be shown by and by) that the praises of this priest were no better
than those of the slave girl possessed with a spirit of divination,
who spoke concerning Paul and Silas, "`These men are the servants of the Most High God,
who proclaim to us the way of salvation.`"^
footnote:[Acts 16:16-17]
Now what Thomas Salthouse had spoken to the priest, was called provoking language;
the more so, because when the priest was speaking of the trinity,
Thomas had asked him where that word was to be found in the Scriptures?
Saying.
"`I know no such Scripture that speaks of the three '`persons`' in the
'`trinity;`' but the three that the Scripture speaks of are the Father,
the Son, and the Holy Spirit, and these three are one.`"^
footnote:[Early Friends were not deniers of the Trinity, or the Holy Three that are One,
as some have falsely asserted.
They objected only to the use of unscriptural or academic terms
when referring to the Godhead (i.e. "`three individual persons`",
"`three separate substances`", or the name "`trinity`"),
feeling more comfortable adhering to scriptural language when speaking of heavenly mysteries.]
From here Thomas Salthouse and Miles Halhead were
accused of denying the Holy Three that are One.
But because their prosecutors were unable to prove this accusation in the court,
something else was thought of to ensnare them: namely,
they were required to take the oath of abjuration of the Pope.
This oath the mayor of Plymouth had already tendered to them when they were first apprehended,
and refusing to swear, they were sent to Exeter prison.
And now being brought to trial, when the said oath was required of them,
they answered in this manner:

"`In the presence of the Eternal God, and before all this people, we do deny,
with as much detestation as any of you do, the Pope and his supremacy,
and the doctrine purgatory; and all that is in the form of the oath mentioned,
we declare freely against.
And we do not deny to swear because of any guilt that is upon us,
but rather in obedience to the command of Christ, who says,
'`Swear not at all;`' and we will not come under the condemnation of an oath,
for the liberty of the outward man.`"

Thus refusing to swear,
merely that they might not offend against the command of our Savior,
they were sent back to prison again as being men who clandestinely adhered to the Pope.
And this same snare has been used during the space of many
years in order to persecute the Quakers (so called).
The next day the prisoners were brought again before the bench, and were asked:
"`Will you confess that you wronged George Brooks in calling him thief,
and be sorry for it, and make him satisfaction?`"

To this Miles Halhead answered: "`One of us did not speak one word to him,
and therefore I deny to make him satisfaction,
or to be sorry for something I did not say.
And what was spoken +++[+++by Thomas Salthouse]
was no such thing as you say; therefore we will not lie to gain our liberty,
nor confess that we are sorry for that which we never spoke.`"

Then the court fined them five pounds a piece;
and they were sent to the house of correction till payment,
and to find sureties for their good behavior.
And for refusing to take the oath,
the court threatened to send into the North to seize their estates.
So they were returned to prison;
and the following was entered as the official record of these proceedings:

[.embedded-content-document.legal]
--

"`July 10, 1655.
Thomas Salthouse, and Miles Halhead, for provoking words against George Brooks, clerk,
who refused to be tried by the country, fined 5£ a piece,
committed to Bridewell till payment, and finding sureties for their good behavior.`"

--

What is said here of their refusing to be tried by the country was a notorious untruth.
And as to finding sureties,^
footnote:[A sum of money,
paid either by the person under indictment or some other interested party,
guaranteeing the good behavior of the accused until
their appearance at the next court sessions,
or for some other set period of time.
Similar to bail.]
that seemed of little importance;
for though the giving of security had been offered before when they were
taken prisoners (by two friends named Robert Cary and Arthur Cotton),
yet this was not accepted; and the mayor, John Page,
had the boldness to assert that they refused to give security,
as will appear by the warrant by which he sent them to the common jail in Exeter,
of which the following is a true copy.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
County of Devon

John Page, merchant, mayor of the borough of Plymouth, in the county aforesaid,
and one of his highness`'s justices of the peace within the said district,
to the keeper of his highness`'s jail at Exon castle,
or to his lawful deputy in that behalf, greetings.

I send you herewith, by the bearer of this warrant, the bodies of Thomas Salthouse,
late of Dragglibeck, in the county of Lancaster, husbandman; and Miles Halhead,
late of Kendal, in the county of Westmoreland,
lately apprehended here as disturbers of the public peace,
and for several other high misdemeanors against a late proclamation prohibiting
the disturbing of ministers and other Christians in their assemblies and meetings,
and against an ordinance of his said highness the Lord Protector and his council,
lately made against duels, challenges, and all provocations thereto.
These have refused to give sufficient security for their personal
appearance at the next general sessions of the peace,
to be held for the county of Devon;
and in the mean time to be of good behavior towards his highness the Lord Protector,
and all his dutiful people.
This warrant is therefore, in his highness`'s name, to will and command you,
that when the bodies of the said Thomas Salthouse
and Miles Halhead shall be unto you brought,
you safely detain them and keep them,
until by due course of law they shall be delivered from there.
Hereof fail not at your peril.
Given under my hand, and seal of Plymouth aforesaid, the 28th day of May,
in the year of our Lord God, 1655.

[.signed-section-signature]
John Page, Mayor.

--

By this may be seen under what frivolous pretenses the people called Quakers were imprisoned,
that is, because of an ordinance made against duels, etc.
And as for their having refused to give security, the falsity of this,
as well as other accusations, may appear from the following certificate:

[.embedded-content-document.legal]
--

We, whose names are hereunto subscribed,
do testify that the several particulars in an answer made by our friends, are true,
and that they did not at all disturb the public peace,
nor were they at any other meeting (besides that
which was appointed by us) to disturb any ministers,
or other Christians in their assemblies and meetings;
nor were they guilty of any challenges, duels, or provocations thereunto,
in the least measure while they were among us.
And as for their refusal to give security, two of us,
whose names are Robert Cary and Arthur Cotton,
had given security to the mayor by entering into
recognizance for their appearance at the next sessions,
the day before their sending to prison; but the town-clerk made it void the next day,
pretending it could not be according to law.

[.signed-section-signature]
Ralph Fogg, Thomas Faulkener, Arthur Cotton, Nicholas Cole, Robert Cary, John Martindale,
Richard Smith, Richard Lepincote, Anthony Todde, John Harris, Sr., John Harris, Jr.

--

Now to what a height of confidence the aforesaid mayor Page, was come, in saying,
that Thomas Salthouse and Miles Halhead had refused to give bail, no,
that this was the cause of their confinement,
may also appear from the following letter he wrote to general Desborough,
to excuse his proceedings against him.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Plymouth, June 1, 1655.

[.salutation]
Right honorable general Desborough,

Captain Hatsell has communicated to me what you wrote him in reference to those two men,
Thomas Salthouse and Miles Halhead, of whom, and of their imprisonment,
your honor had heard something from some persons of this place,
and received a copy of a letter which they sent to me.
By the enclosed copies of their examinations,
your honor will see some part of the cause of their confinement,
which was on their refusal to give bail for their appearance at
the next general sessions to be held for the county of Devon;
they being, as I conceive,
offenders within the late ordinance of his highness the Lord Protector and council,
made against duels, challenges, and all provocations thereunto,
and also his highness`'s late proclamation against Quakers;
and they still refusing to give bail for their appearance as aforesaid,
went from here to the jail at Exon on Tuesday last.
Indeed, sir, their carriage here was not becoming men, much less Christians;
and besides their contempt of authority, all the while they were in prison,
they never sought God by prayer at any time,
nor desired a blessing on any provisions they received, or gave thanks for them.
And these very men were about two months past taken up by colonel Cupplestone,
high sheriff of our county, and after fourteen days restraint,
were sent away by him for Taunton,
showing no occasion why they have to come to these parts.
They are by profession Quakers, but husbandmen by their calling.
One of them is a Lancashire man, the other of Westmoreland; and they left their families,
relations, and callings, about three months ago, as they say, and do not work,
nor employ themselves in their calling, to procure themselves a livelihood,
but wander up and down in all parts to vent their wicked opinions,
and discover their irregular practices in the breach
of peace and disturbance of good people.
Indeed, sir, they hold many sad opinions, destructive to the true religion,
and the power of godliness.
I have hereby according to my duty,
given your honor an account of what passed here in reference to these men.
I could say much more in reference to their examination and discourse with them;
but I fear I have already trespassed upon your honor`'s
patience in the perusal of these lines;
and humbly desiring your excuse for giving you this trouble,
I do most thankfully acknowledge your honor`'s continued favors to this place,
for which we stand very much obliged,
desiring your honor still to retain such an opinion of us
as those that desire to do nothing unbecoming of Christians,
and persons that desire the welfare and peace of this commonwealth and government,
and shall ever labor to appear,

[.signed-section-closing]
Your honor`'s very humble servant, (for myself and my brethren),

[.signed-section-signature]
John Page, Mayor.

--

That General Desborough was unsatisfied with this letter, seems not improbable, because,
inquiring into the matter, he let others have a copy of it,
so that Thomas and Miles wrote an answer to it.
It was also, some time after, given out in public print at London, by Giles Calvert,
with other writings relating thereto.
Now as to what is said in this letter of his highness`'s proclamation against Quakers,
it was a gross untruth; for in the said proclamation the Quakers were not named;
but it was against all disturbing of Christians in their assemblies.
And besides,
the Quakers (so called) judged that their public worship was permitted
them by the 37th article of the legislation of government,
which said, "`That all who profess faith in God by Jesus Christ,
shall not be restrained from, but be protected in,
the profession of the faith and exercise of their religion,`" etc.

As concerning the contempt of authority that the mayor charged them with,
it was nothing else but that, for conscience sake,
they could not take off their hats to the magistrates;
neither did they give that honor to any other man, but to God alone.
And as to what was said,
that all the while they were in prison they never sought God by prayer, etc.,
this was no other matter than that they did not follow the formal way of praying;
for they were indeed religious men, who often prayed to God, and gave Him thanks.
And though they were represented in the letter as being very wicked men,
and vagabonds that had left their calling and wandered up and down the country,
yet it was well known that they were honest men, and travelled on horseback,
staying at the best inns on the road, and paying for whatever they received there.
And, therefore, after they had received a copy of the said letter,
they wrote a long letter to the mayor John Page, showing him his abominable untruths,
and telling him that they had been moved several times both in prison,
as well as out of prison,
to pray and to give thanks for the blessings of God which they received.
And in the conclusion of their letter,
they signified that they did not desire to return railing for railing;
"`but,`" they said, "`in the spirit of love and meekness we exhort you all to repent,
and fear to offend the Lord.`"

Now as concerning provoking words of Thomas Salthouse against the priest George Brooks,
for which they had been fined, it has been said already what they were.
But this Brooks was of a dissolute life, and was a debauched fellow,
having for his drunkenness not only been turned out
of the navy vessels in which he had served as priest,
but also once in the ship Nightingale, was ignominiously exposed with a quarter can^
footnote:[The editor of this history has been unable to determine the meaning
of the term "`quarter can,`" but believes it was some sort of distinguishing
mark or stigmatization placed upon those guilty of a certain type of behavior,
in this case public drunkenness.]
about his neck, as appears by the following testimonies.

[.embedded-content-document.testimony]
--

I having been formerly desired to relate upon what account it was that Mr. George Brooks,
chaplain of the frigate under my command, was put on shore.
First, because he was a busy-body, and disturbed the whole ship`'s company.
Secondly, being on shore,
it was his common practice to abuse the creation of God
in such a way that he was drunken and void of good reason.
Indeed, he would abuse any one that came in his company by ill language,
besides the abuse of himself and the good creation,
daily complaints coming unto me both aboard and on shore.
Therefore, knowing him to be a debauched fellow, and not fit for that employment,
I put him on shore,
and I will dare acknowledge it to whoever shall call upon me to question.
Witness my hand,

[.signed-section-signature]
Robert Vessay.

--

[.embedded-content-document.testimony]
--

Mr. Brooks being formerly with me in the Nightingale, I found him to be very idle,
and continually drunk, which once made me to put a quarter can about his neck;
whereunto I subscribe,

[.signed-section-signature]
John Jeffery

[.signed-section-context-close]
Captain of the Nantwich.

--

[.embedded-content-document.testimony]
--

The person above-mentioned I have seen drunk on shore,
in testimony whereof I have set my hand,

[.signed-section-signature]
Richard Potter

[.signed-section-context-close]
Captain of the Constant Warwick frigate.

--

From such evidence as this,
it appears that it was not without reason that he and the
like priests were sometimes treated somewhat bluntly.
But to return to M. Halhead; he continued prisoner many months before he was released.

In the meantime it happened that George Whitehead, Richard Clayton, and John Harwood,
coming on the 30th of the month called July to Bures, in Suffolk,
were imprisoned on this occasion.
Richard Clayton had set up a paper on the steeple-house door,
containing the following queries:

[.embedded-content-document.paper]
--

Whether it is right to set up such ministers who "`seek for their
gain from their territory,`" such as the prophet disapproves,
Isaiah 56:11; and such as the prophet Jeremiah disapproves, Jer.
5; and of whom mention is made also in Ezekiel 34 and Miciah 3;
such who are called by men "`masters,
loving the chief places in the assemblies,`" such as Christ disapproved, Matt, 23;
and the apostle Peter disapproves, 2 Pet.
2; and the apostle Paul disapproved also, Phil.
3? Or when those who are set up will not "`allow another to speak who stands by,
when anything is revealed,`" 1 Cor 14:30; but instead send him to prison,
whether this was not the setting up a persecuting spirit, limiting the Spirit of God,
and "`despising prophecies,`"^
footnote:[1 Thessalonians 5:20]
not daring to "`test all things`"^
footnote:[1 Thessalonians 5:21]? Whether it was right to give to scoffers, scorners,
drunkards, swearers, and persecutors, David`'s conditions to sing?
And if men were now set up that took tithes,
though the apostle has said that "`the priesthood has changed, and the law also,`" Heb.
7:12, whether by the setting up such men,
they did not set up those who do not labor in the Lord`'s vineyard?

--

This paper being set up, people came to read it.
George Whitehead being there, and laying hold of this opportunity,
spoke a few words to the people and exhorted them to turn to the
Lord from the vanities and wickedness they lived in.
And when G. Whitehead and his fellow-travelers were passing away,
there came a constable who stopped them and carried them before Herbert Pelham,
justice of peace.
This justice asking several vain questions, and behaving himself rudely,
Whitehead began to speak to him concerning his rage;
but Pelham said he did not send for him to preach.
And not being able to lay the transgression of any law to their charge,
he sent them by the constable to Thomas Walgrave, justice of peace at Smallbridge,
in Suffolk.

Having come into his house,
Richard Clayton was first examined concerning his name and country,
and where he had been.
The same and some other frivolous questions were asked of George Whitehead.
Justice Pelham now having come there also,
the two justices consulted together what to do in the case;
and not long after Thomas Walgrave asked G. Whitehead if he would work in the hay fields?
But he denied to be bound to such task-masters,
as already being about the calling whereunto God had called him,
and wherein he had always paid his own way.
The conclusion of their consultation was, that they caused Richard Clayton to be whipped,
under pretense of having fastened a "`seditious paper`" to the steeple-house door;
and the other two were imprisoned.

It was about this time that William Dewsbury,
and several other of his friends were put into prison at Northampton.
For it happened that when he was in Wellingborough, going along the streets, the priest,
Thomas Andrews, called to him in these words, "`Cease deceiving the people,
lest the plagues of God fall on you.`"
To this Dewsbury returned, "`Do you say I deceive the people?
Make it manifest wherein I deceive them.`"
Then Andrews said, "`You say there is not any original sin.`"
To this Dewsbury replied, "`Did you hear me say so?`"
But the priest, unwilling to answer that question, went away.
Afterwards Dewsbury went into the steeple-house in the said town,
and after the sermon had finished,
he demanded of the priest that he would prove before
the people what he had openly accused him of,
namely, that he had said there was no original sin.
Yet the priest would not answer, but went away.
There was also information given that Dewsbury had said, "`The priests preach for hire,
and the people love to have it so, but what will you do in the end thereof?`"
But that this was really so, I do not find.

Dewsbury then being committed to prison, and kept there above half a year,
was at last brought to his trial at Northampton, with several other prisoners,
his friends.
And being brought to the bar, judge Atkins said to the jailer,
"`Do you usually bring prisoners before the court in this manner?
You deserve to be fined ten pounds for bringing them
before the court with their heads covered!`"
The jailer answered, "`If you command me, I will take off their hats.`"
To which the judge gave command, and the jailer`'s servant took them off.
Then the judge said to Dewsbury, "`What are you here for?`"
Dewsbury answered, "`The court order will express what I was committed for,
but I am denied a copy of it by the keeper of the jail.`"
The next question of the judge was, "`What is your name?`"
And the answer was, "`Unknown to the world.`"
"`Let us hear,`" said the judge, "`what name this is that the world knows not.`"
"`It is,`" said Dewsbury, "`known in the light, and none can know it but he that has it;
but the name the world knows me by is William Dewsbury.`"
Then said the judge, "`Of what country are you?`"
Dewsbury answered, "`Of the land of Canaan.`"
"`That is far off,`" replied the judge.
"`No,`" said Dewsbury, "`for all that dwell in God are in the holy city, New Jerusalem,
which comes down from Heaven, where the soul is at rest,
and enjoys the love of God in Jesus Christ,
in whom is the union with the Father of light.`"
To this the judge returned, "`That is true; but are you ashamed of your country?
Is it a disparagement for you to be born in England?`"
"`No,`" said Dewsbury, "`I am free to declare that my natural birth was in Yorkshire,
nine miles from York, towards Hull.`"
Then the judge said, "`You pretend to be extraordinary men,
and to have an extraordinary knowledge of God.`"
To which Dewsbury replied,
"`We witness the work of regeneration to be an extraordinary work,
wrought in us by the Spirit of God.`"
"`But,`" said the judge, "`the apostles wrought with their hands in their callings.`"
"`They had,`" answered Dewsbury, "`callings in the world, some were fishermen,
Paul was a tent-maker; but when they were called to the ministry of Christ,
they left their callings to follow Christ, where He led them by His Spirit,
to preach the word.
And I too had a calling in the world as they had,
and in it I did abide until the Father revealed His Son in me and called
me from the calling I had in the world to preach the eternal Word,
which He had made known to me in the great work of regeneration.`"
"`Why,`" asked the judge, "`did you not abide in your own country,
and teach people in those parts?`"
"`There I did stay,`" returned Dewsbury,
"`until I was called from there to go to where I was led by the Spirit of the Lord;
and as many as are led by the Spirit of God, these are the sons and daughters of God;
and they that have not the Spirit of Christ are none of his.`"
To this the judge said, "`You say well;
for we must in charity conclude that everyone in this place has the Spirit of God in him.
But how do you know that you are guided by the Spirit of God?`"
"`They that have the Spirit of God,`" replied Dewsbury, "`are known by their fruits.
And he that believes in Jesus Christ, and is guided by His Spirit,
has the witness in himself.`"
"`That is true,`" said the judge, "`yet notwithstanding, I see by your carriage,
that what my brother Hale did at the last court session,
in requiring bond for your good behavior, he could justly do it;
for you are against magistrates and ministers.`"
But Dewsbury replied, "`Make manifest wherein we are against them.`"
Then said the judge to the clerk, "`Robert Guy, what have you against these men?`"
At which he gave a relation of what Dewsbury had said to priest Andrews in the steeple-house.
Dewsbury then giving an account of the matter of fact, and how the thing happened;
and that it was not any breach of the law of the nation; the judge resumed,
"`But in that you are found wandering in the country, you break the law;
for there is an old law that if any did go from their dwellings
to travel in the country without a certificate from some justice,
they were to be taken up as wandering persons.`"
To this Dewsbury said, "`If there is any such law, read it to us.
But if there is such a law,
you know in your conscience that it is contrary to the Scripture;
for the apostles and ministers of Christ went to and fro in the country,
preaching the Word of eternal life,
and there were added to the church daily such as should be saved;
and the number of the saints and brethren daily increased.
The law that is now in force in this nation,
does allow all who profess faith in Jesus Christ
to have free liberty to walk in the faith,
which is according to Scripture.`"
To this the judge said, "`You have an eloquent tongue, and you are proud of it.`"
"`Pride I deny,`" replied Dewsbury, "`but the Truth I witness,
which will judge all pride, and torment all that live in it, until it is destroyed.`"
The judge then spoke to the other prisoners; and though he behaved himself moderately,
yet he could not resolve to set them at liberty.
So they were continued in prison,
though they had been already kept there above twenty-nine weeks.

One of these prisoners was John Huchin,
whom they had nothing else to charge with but that he had come into the
steeple-house at Wellingborough and stood there peaceably in silence;
but before half the sermon was over, priest Andrews commanded to have him taken away.
This was done by the church-warden, Henry Hensnan, who carried him to an alehouse,
where it was told him by the constable that if he would promise
not to come to the church in the afternoon he would be set free.
But refusing to make such a promise, though they let him alone at that time,
yet some days after a constable came to his master`'s shop where he was working,
and took him away without showing any warrant.

Another of the prisoners was Michael Pattison, who having been in the same steeple-house,
stood peaceably in silence until priest Andrews had
finished and the people were going away,
and then said to him, "`Friend,
can you witness this to be the word of the Lord that
you have spoken here before the people?`"
But this so offended the priest, that he commanded the officers to take Michael away,
which John Brown, the constable, did.

Thomas Goodyear was also one of these prisoners.
Having come to Northampton to visit his friends in prison there,
he was denied by the jailer; and meeting the mayor and some aldermen in the streets,
he spoke to them about persecution.
But one of the aldermen struck off his hat,
and said he would teach him better manners than to
stand and talk before the mayor with his hat on.
Then they required sureties for his good behavior; but he told them,
"`I am bound to good behavior by the righteous law of God.`"
So refusing to find sureties,
he was taken up in the street and sent to prison without a court order or further examination.
But I will not detain my reader any longer with these prisoners;
for if I should relate all the occurrences of this nature that have come to my knowledge,
and the unreasonable pretenses under which they were committed,
even committing to prison many who were not yet fully
entered into the communion of those called Quakers,
I must write much more than I would be able to do,
though my life should yet be lengthened considerably.

I find among my papers of this time, the names of about one hundred persons, who,
for not paying tithes to the priests, and refusing to swear,
suffered either by seizure of their cattle and goods, or imprisonment.
Thomas Aldam, for not paying of tithes to the priest Thomas Rookby, of Warnsworth,
was imprisoned at York in the year 1652,
where he was kept more than two and a half years,
and besides had thirteen cows and two horses taken from him.

But passing by a multitude of similar cases, I return again to G. Fox,
whom I left at London.
He, having had there several large meetings, went from there to Colchester, where,
with difficulty he visited James Parnell in prison.
From Colchester he went to Ipswich, and so passed on to Norwich and Yarmouth,
finding service everywhere he went.

Traveling further towards Lynn in company with Richard Hubberthorn,
and along the way being in bed at an inn, a constable and officers came there,
being sent with a __hue and cry__^
footnote:[A __hue and cry__ was a public summons where all citizens
and bystanders were called upon to apprehend a criminal.]
from a justice of peace,
to search for two horsemen in grey clothes that rode upon grey horses,
alleging that a house had been broken into that night.
Now, though Fox and Hubberthorn said they were honest and innocent men,
yet a guard with halberds^
footnote:[A halberd is a large battleaxe with a spear at the tip.]
and pikes was set upon them that night,
and in the morning they were carried before a justice of peace about five miles off.
The justice grew angry because they did not put off their hats to him;
but G. Fox told him, "`I have been before the protector,
and he was not offended at my hat; why then should you be offended at it,
who are but one of his servants?`"
The justice, having examined them,
said he believed they were not the men that had broken into the house,
but stated he was sorry that he had no more against them.
But G. Fox told him, "`You ought not to be sorry for not having evil against us;
but rather to be glad.`"
The justice, though enticed by the constable to send them to prison, yet let them go.
Being thus set at liberty, G. Fox travelled on to Lynn, from which he went to Sutton,
where he had a large meeting, many people from other places having come there,
and also the mayor`'s wife from Cambridge.
Many hundreds were convinced of the truth he preached.
From there he passed to Cambridge, and though the students were exceedingly rude,
yet he got safe into an inn.
In the dark of the evening, the mayor of the town came and fetched him to his house,
where some friendly people were sent for, and he had a meeting there.
Next morning he departed the town and returned to London, where he stayed some time.

In this year came out the oath of abjuration against King Charles,
whereupon he wrote to the protector, acquainting him that many of his friends,
who could not swear for conscience sake, suffered much on this account.

From London he went to Leicestershire, and coming to Whetstone,
where formerly he had been taken prisoner by colonel Hacker, he now had a large meeting,
to which Hacker`'s wife and his marshal came, and they, besides many more,
were convinced by G. Fox`'s ministry.
Leaving there, and passing through many places, he came again to London,
where meeting James Nayler, and casting his eyes upon him,
he was struck with a fear concerning him;
having a sense of some great disaster that was likely to befall him.

In this year Edward Burrough wrote a letter to the protector,
wherein he told him that the Lord`'s controversy was against
him because he had not been faithful in God`'s work;
but that he had taken his rest and ease upon a lofty mountain of pride and vain glory;
having set up himself to be worshipped, and exalted his own horn,
without giving glory and honor to God.
Moreover, he had not performed his vows made to the Lord in the day of distress;
but had allowed grievous oppression, cruelty, and tyranny to be acted in his name,
by unjust imprisonments and persecution of the Lord`'s people;
saying also that the Lord would therefore bring His judgments upon him,
except he did repent.
But though Burrough spoke very boldly in his letter to Cromwell,
yet I do not find that he showed himself angry because of it.
Nevertheless, he hearkened too much to the flatteries of those teachers, who,
having now entered into the possession of the Episcopalians,
exalted him as their idol by their applause.
And Cromwell considering the priests as those who
could strengthen his authority over the people,
winked at their grievous persecution carried on against the Quakers (so called).

In the meantime there were many malcontents,
who thought it unjust for Cromwell to force the members of parliament
to consent to make no change to the government then established;
for he would not permit any one to sit in the house without
having promised by writing not to oppose the present government.
This gave occasion for even some who had been his eminent friends to reprove him sharply.

Among these was lieutenant-colonel John Lilburn, who being an extraordinarily bold man,
very stiff and inflexible,
had more than once showed himself a public asserter of the people`'s liberties and freedoms.
For this he had been prosecuted at law; once in the year 1645,
when he was imprisoned as guilty of treason, but was discharged; and afterwards,
in the year 1649, when,
having published several books to expose to the public the
arbitrary power he thought was exercised in the government,
he was confined in the Tower of London; and,
after having been prisoner about seven months, was impeached of high treason.
But he defended his cause so vigorously,
that though strong persuasion had been used to move the jury to bring him in guilty,
yet he so far prevailed, that at length he was set at liberty again;
though I find that he was once whipped for a crime laid to his charge,
of which he gloried publicly.
And when Cromwell had usurped the supreme power, Lilburn boldly charged him,
both by word of mouth and by writing, with falseness and tyranny.
Cromwell then, foreseeing that if this man continued thus to expose his doings,
he would not be able to maintain his credit and authority,
ordered him to be taken into custody and impeached of high treason.
When Lilburn, thus accused, appeared before the court,
he behaved himself with such undauntedness, and so defended his cause,
that he seemed less to plead for his life than for the freedom of his country.
Then, having boldly answered what was objected to him,
he insisted that what he had done was not only no high treason,
but that the government was in such a state that
no high treason could be committed against it;
and that therefore all true Englishmen were obliged to oppose
the tyranny that was exercised against them.
He also said, that having once been in favor with Cromwell,
he might have attained great preferment if only he had kept quiet;
but that having thought this unlawful, it had now been decided to take his life away;
which he did not fear, because he stood for a good cause.
Thus vigorously Lilburn pleaded, and he defended his cause with such strong arguments,
that the jury brought him in not guilty,
notwithstanding the endeavors of the judges to the contrary.

Now, though according to law, he must have been set at liberty,
yet Cromwell would not consent to it, but kept him a prisoner.
And because he indeed feared him, as one that would weaken his government,
he ordered him to be carried from one prison to another,
till at length he came to be confined in the castle of Dover.
In this town lived Luke Howard, mentioned before,
who thereby having occasion to speak with Lilburn concerning religion,
gave him such convincing reasons for his profession
as prevailed upon Lilburn to receive the Truth;
as he himself signified in a letter he wrote to his wife; who,
having visited him in prison, first wrote to him this following exhortation.

[.embedded-content-document.letter]
--

[.salutation]
My dear,

Retain a sober patient spirit within you,
which I am confident you will find to be of more strength to recover you,
than all your boldness of spirit has been.
I hope God is doing such a work upon you and me too,
as shall make us study ourselves more than we have done.

--

These words were so acceptable to Lilburn,
that first repeating them in his letter to her, he answered thus:

[.embedded-content-document.letter]
--

[.salutation]
O, my dear love!

I have already deeply entered into my part of this.
May the mighty power of God enable you to get in too, and also to go through yours,
and effectually to go cheerfully and willingly along hand in hand with me,
which would render you abundantly more amiable, lovely, and pleasant in my eyes,
although you were then clothed in rags, than you could be to me by drawing back,
or standing still where you were when I last saw you,
though therein you were clothed all over with rich
and outwardly glistering earthly diamonds,
and in the greatest of earthly prosperity.
I am sorry you are so pressed for money; but to live upon God by faith,
in the depth of straits, is the lively condition of a Christian.
O that your spirit could attain unto this, according to your desire in your letter,
and my own present frame of spirit!
I now can contentedly feed upon bread and cheese and small beer alone,
for the saving of money.
And for my liberty,
about which you so weary and spend yourself (as your letter acquaints me you do),
I can say to you that I am in my present temper of spirit,
really ready with Peter (at the sight of the glorious transfiguration of Christ) to say,
'`it is good for me to be here.`' For here in Dover Castle,
through the lovingkindness of God, I have met with a more clear, plain,
and evident knowledge of God and myself, and His gracious manifestations to my soul,
than ever I had in all my lifetime,
not excepting my glorying and rejoicing condition under the bishops.
And now submissively and heartily I can say,
the will of my heavenly Father be done in me, by me, and for me;
in whose will I leave you and yours, with all your and my friends,
and rest yours in the strength of renewed true love,

[.signed-section-signature]
John Lilburn

[.signed-section-context-close]
From Dover Castle,
the place of the present enjoyed delightful dispensation of the eternal,
everlasting love of God unto my soul.
The 4th of the Tenth Month, 1653.

--

While Lilburn was prisoner here,
it seemed that Oliver Cromwell was willing to release him,
if he would sign a declaration stating he would never draw a sword against his government.
But Lilburn,
not being yet fully convinced that to refrain from the use
of the carnal sword was the duty of a true Christian,
refused.
For though George Fox had signed such a declaration,
he thought it not fitting for himself,
not yet entirely approving that point of self-denial.
Nevertheless, continuing faithfully in that measure of knowledge he had already attained,
in the process of time, he became such an asserter of the true Christian life,
that in a paper (which at his desire was given out
in print) he expressed himself in the following words:

[.embedded-content-document.paper]
--

I have now the faithful and true Witness in my own soul.
Indeed, the Lord Himself has become, within me, the teacher of my soul,
who enables me to walk in a measure of His pure ways and paths.
Yes, and so clear a teacher within me has He already become to me,
that with confidence I do believe that my inward "`teacher
shall never more be removed into a corner;`" but is,
and shall be, as a continual voice speaking in my ears, "`This is the way, walk in it.`"^
footnote:[Isaiah 30:20-21]
By this divine teaching, I am now daily taught to die to sin,
and am led by it into living power,
to be raised up and enabled to live in a pure measure of righteousness.
And by this inward spiritual teaching, I am, I say again,
brought up into power in Christ, by which I can, and do hereby witness,
that I am already dead,
or crucified to the very occasions and real grounds of all outward wars,
and carnal sword fighting, and fleshly bustlings and contests.
Therefore,
I now confidently believe that I shall never hereafter
be a user of a temporal sword any more,
nor a joiner with those that so do.
And this I do here solemnly declare, not in the least to avoid persecution,
or for any political ends of my own,
or in the least for the satisfaction of the fleshly wills of any of my great adversaries,
or for satisfying the carnal will of my poor weak afflicted wife;
but by the special movings and compulsions of God now upon my soul,
I am in truth and righteousness compelled thus to declare;
that so I may take away from my adversaries all their fig-leaf coverings, or pretenses,
for their continuing me in these unjust bonds.
And therefore, if I must yet be an imprisoned sufferer,
may it from this day forward be for the Truth as it is in Jesus;
which Truth I witness to be truly professed and practiced
by the savoriest of people called Quakers.

And to this my present declaration,
which I exceedingly long and earnestly desire to have in print,
and for which I know that I can cheerfully and assuredly lay down my life,
if I be called to witness the truth of it, I subscribe my name,

[.signed-section-signature]
John Lilburn.

[.signed-section-context-close]
From my innocent and every way causeless captivity in Dover Castle,
the place of my soul`'s delightful and contented abode,
where I have really and substantially found that
which my soul many years has sought diligently after,
and with unsatisfied longing has thirsted to enjoy: this present First-day of the week,
being the 4th of the Third Month, 1655.

--

It sufficiently appears by this,
that Lilburn did not think that this declaration would procure his liberty;
and he guessed not wrong, for Cromwell died before he was finally released.
Lilburn being then discharged from his confinement,
continued steadfast to the doctrine of the Truth he had embraced,
and died at London in the year 1660.
But being advanced in the time, I go therefore back a little,
and intend in the sequel to give a more circumstantial description of Cromwell`'s death.

And thus I conclude this book with the year 1655,
in which year there was a plot of the royalists against Cromwell;
and in Nottinghamshire they had already risen up in some places,
and towards the West the city of Salisbury.
The young king (Charles) had come from Cologne into Zealand,
to be the nearer if the attempt succeeded.
But his time of ruling had not yet come;
for the cavaliers were soon forced to give way to the power of Cromwell;
and the plot being thus squashed, king Charles returned to Cologne.
In the meantime, in order to raise his esteem abroad,
Cromwell sent a fleet under the command of admiral Penn,^
footnote:[Sir William Penn (1621-1670), was an English admiral and politician,
who sat in the House of Commons from 1660 to 1670; also the father of William Penn,
founder of Pennsylvania.]
to the West Indies, and another under the command of admiral Blake,
towards the Mediterranean sea.
