== Chapter 6

[.section-date]
1656

Near the beginning of the year 1656, G. Fox went from London to Surry, Chichester,
Portsmouth, and Pooel; where Willam Baily, a Baptist teacher, and some others,
were convinced by G. Fox`'s ministry and entered into the society of those called Quakers,
and this Baily afterwards became an eminent minister.
From Poole, G. Fox went to Southampton and Dorchester,
where he desired of the Baptists to have their meetinghouse to meet in;
but this being refused,
he sent them word that they might come to his inn if they pleased.
Many of them came, with their teacher, and they fell into a discourse about water baptism.
G+++.+++ Fox asked them whether they could say they had been sent of God to baptize people,
as John was; and whether they had the same Spirit and power, that the apostles had.
To this they answered, no.
Then he asked them, "`How many powers are there?
Are there any more than the power of God, and the power of the devil?`"
They said, "`There are not any other powers besides these two.`"
"`Then,`" said G. Fox, "`If you do not have the power of God which the apostles had,
then you act by the power of the devil.`"
And his speaking was of such effect,
that many substantial people were convinced that night.
But the next morning when he was passing away,
some of the Baptists began to shake the dust from off their feet after him.
"`What,`" said he, "`in the power of darkness?
We who stand in the power of God shake off the dust of our feet against you.`"

Leaving Dorchester, he came to Weymouth, where, inquiring after the sober people,
about eighty of them gathered together at the priest`'s house,
and most of them turned to Christ Jesus who had enlightened them with His divine light,
by which they were reproved for their sins.
There was at that time an officer in the town who
rode about seven miles out of town with G. Fox.
This officer was of such a merry temper, and so exceedingly given to laughter,
that G. Fox several times spoke very seriously to him about it;
but it had become so customary to him that he would laugh at almost anything he saw.
But G. Fox admonished him to seriousness and to the fear of the Lord,
and he spoke to him again about this when they parted.
The next time G. Fox saw him,
the captain told him that when he spoke to him at
parting the power of the Lord so struck him,
that before he got home he was serious enough, and had left off his laughing.
And indeed, he became a serious and good man; and being convinced of the Truth,
he died in the real profession of it.

For brevity`'s sake I do not intend to mention all the places G. Fox passed through,
much less all his occurrences.
At Kingsbridge he had good service, and then returned in the evening to his inn.
There being many people drinking,
he was moved to go among them and to direct them to the light which Christ,
the heavenly man, had enlightened them with,
by which light they might see all their evil ways, words, and deeds;
and by the same light they might also see Christ Jesus their Savior.
But this discourse did not please the innkeeper,
seeing it hindered his guests from drinking.
And hearing G. Fox speak so much of the light, he took up a candle, and said, "`Come,
here is light for you to go into your chamber.`"

The next day, G. Fox went to Plymouth, and from there to Cornwall;
and travelling through the country, he came to Market-Jew.
Staying there at an inn, he met with some trouble from the magistrates.
He wrote a paper to show that the Lord had come to teach His people Himself,
by Jesus Christ, etc.
This paper came accidentally to the hands of Peter Ceely, a major in the army,
and also a justice of peace at Ives, where G. Fox came.
Here Edward Pyot and William Salt (who were traveling
with G. Fox) were hauled before the said major,
while G. Fox was walking down to the seaside.
But hearing of this, George followed them, and came also into the justice`'s house,
where the aforesaid paper was produced.
It was asked him, whether he would acknowledge having written it.
He said, "`Yes.`"
Then the major tendered them the oath of abjuration,
upon which G. Fox put his hand into his pocket,
and drew forth the answer to it which he had given to the protector.
A priest being present there found fault with his hair, which was then pretty long,
and asked to have cut it; but G. Fox told him he had no pride in it.
G+++.+++ Fox and his companions were then taken into custody,
and with a guard of horsemen were sent to prison with the following court order.

[.embedded-content-document.letter]
--

Peter Ceely, one of the justices of the peace of this county,
to the keeper of his highness`'s jail at Launceston, or his lawful deputy on that behalf,
greeting:

I send you by the bearers of this letter, the bodies of Edward Pyot, of Bristol,
and George Fox, of Drayton and Clay, in Leicestershire, and William Salt, of London,
which they claim to be the places of their habitations,
who go under the notion of Quakers, and acknowledge themselves to be such.
These have spread several papers tending to the disturbance of the public peace,
and cannot render any lawful cause of coming into these parts,
being persons altogether unknown,
and having no pass for their travelling up and down the country,
and refusing to give sureties for their good behavior,
according to the law provided on that behalf, and refuse to take the oath of abjuration, etc.
This order is therefore, in the name of his highness, the Lord Protector,
to will and command you, that when the bodies of the said Edward Pyot, George Fox,
and William Salt, are brought unto you, you shall receive them,
and in his highness`'s prison aforementioned you safely
keep them until by due course of law they shall be delivered.
Hereof fail not, as you will answer the contrary at your peril.

[.signed-section-closing]
Given under my hand, and seal, at St. Ives, the 18th day of January, 1656.

[.signed-section-signature]
P+++.+++ Ceely.

--

By this court order it appears under what odd pretences the Quakers, so called,
were committed to prison;
for such reasons as are mentioned therein might be found and charged at any time.
Thus G. Fox and his companions were carried through Redruth, Falmouth, and Bodmin,
to Launceston.
On the way they suffered great abuses, both from the soldiers that conducted them,
and from others, by the connivance of captain Keat;
but I will not detain my reader with all those particulars.
Having come to Launceston, Keat delivered the prisoners to the jail.
Many were greatly enraged against them,
and expected that these prisoners (who "`thee`'d`" and "`thou`'d`" all,
and did not put off their hats to any man) should be condemned
to be hanged if they did not pay that respect to the court.
Yet there were many friendly people, from several parts of the country,
that came to visit them;
for it was about nine weeks from the time of their commitment to the court session,
so that many got opportunity to speak with them, which had such a good effect,
that several were convinced of the truth of the doctrine held forth by them.

At the time of the court session,
an abundance of people came from far and near to hear the trial of the Quakers;
who being guarded by soldiers and the sheriff`'s men to the court,
had much difficulty to get through the multitude that filled the streets;
the doors and windows also being filled with people looking out upon them.
Being brought into the court, G. Fox after all was quiet, said, "`Peace be among you.`"
Judge Glyn, who was then chief justice of England, said to the jailer,
"`What are these men you have brought here into the court?`"
"`Prisoners, my lord,`" said he.
"`Why do you not put off your hats?`"
said the judge to them.
Saying nothing in response, the judge again said,
"`Put off your hats;`" and they still continuing silent, the judge said,
"`The court commands you to put off your hats.`"
Then George Fox began to speak, and said, "`Where did ever any magistrate, king,
or judge, from Moses to Daniel,
command any to put off their hats when they came before them in their courts,
either among the Jews (the people of God), or among the heathen?
And if the law of England does command any such thing,
show me the law either written or printed.`"
The judge, then growing angry, said, "`I do not carry my law books on my back.`"
"`But,`" said G. Fox, "`where is it printed in any statute-book, that I may read it?`"
At this the judge said, "`Take him away, rogue!
I`'ll rattle him!`"
Then the prisoners were taken away and put among the thieves.
But soon after the judge called to the jailer, "`Bring them up again.`"
This being done, he said, "`Come now,
where does it say that they had hats from Moses to Daniel?
Answer me; I have you now!`"
To this G. Fox replied, "`You may read in the third chapter of Daniel,
that the three young men were cast into the fiery furnace by Nebuchadnezzar`'s command,
with their coats, their trousers, and their hats on.`"
This plain instance stopped him; so that not having anything else to say, he cried again,
"`Take them away jailer.`"
Accordingly they were taken away, and being thrust among the thieves,
they were kept there a while, and at length carried again to prison;
but in the afternoon they were brought up again into the court.

G+++.+++ Fox seeing the jurymen there, gave them a paper which he had written against swearing.
This paper passing from the jury to the justices, they presented it to the judge;
and he bid the clerk to give G. Fox the paper,
and then asked him whether that "`seditious paper`" was his.
To this George requested that they read it in open court, that he might hear it,
and if it was his, he would acknowledge it and stand by it.
The judge desired G. Fox to take it and look upon it in his own hand.
But he requested again that it might be read, that all in the court might hear it,
and judge whether there was any sedition in it or not; for if there were,
he was willing to suffer for it.
At length the clerk of the court session read it with an audible voice;
and when he had finished, G. Fox said, "`It is my paper, and I will acknowledge it;
and so might you too, unless you deny the Scripture.
For is it not Scripture language, and the words and commands of Christ and the apostles,
which all true Christians ought to obey?`"
Then they let that subject fall,
and the judge speaking again about the hats of the prisoners,
bid the jailer to take them off.
The prisoners then asked why they had lain in prison for these nine weeks,
seeing now that nothing was objected against them except what concerned their hats.
"`And,`" said G. Fox, "`as for putting off our hats,
that is the honor which God will lay in the dust, though you make so much ado about it.
For the honor which is of men, and which men seek from one another,
is the mark of unbelievers.
For Christ says, '`How can you believe, who receive honor from one another,
and seek not the honor that comes from the only God?`' And Christ says also,
'`I do not receive honor from men.`' And all true Christians should be of His mind.`"
Then the judge made a speech about how he represented the Lord Protector`'s person,
and how the Protector made him lord chief justice of England, etc.
Upon hearing this,
the prisoners then desired that he would do them justice for their false imprisonment,
which they had suffered for nine weeks.

But instead of this, an indictment was read against them that was so full of untruths,
that G. Fox thought it had been against some of the thieves;
for it contained a charge that they came by force of arms,
and in a hostile manner into the court;
though in truth they were brought there as prisoners.
This made George say it was all false,
and they cried for justice for their false imprisonment,
having being taken up in their journey without cause, by major Ceely.
Then the said Peter Ceely, who, as a justice of peace, sat also on the bench,
said to the judge, "`May it please you, my lord, to hear me.
This man (pointing to G. Fox), went aside with me,
and told me how serviceable I might be for his design,
and that he could raise forty-thousand men at an hour`'s warning,
and involve the nation in blood, and so bring in king Charles.
I would have aided him out of the country, but he would not go.
And if it please you, my lord, I have a witness that will swear to it.`"
And so he called upon his witness, who, without doubt, was one that was bribed.
But the judge, perceiving this palpable lie, was not forward to examine the witness.
Then G. Fox desired the judge that he would be pleased to let his court order be read,
in which the pretended crime was signified for which he had been committed to prison.
But the judge said it should not be read.
G+++.+++ Fox still insisting to have it read, said, "`It ought to be read;
for if I have done anything worthy of death, or of bonds,
then let all the country know it.`"
Seeing then they would not read it, he said to one of his fellow-prisoners,
"`You have a copy of it; read it up.`"
"`It shall not be read,`" said the judge; "`Jailer, take him away;
I will see whether he or I shall be master.`"

Then G. Fox was taken away, and after a while was called for again.
He still called to have his court order read; and the people being eager to hear it,
he bid his fellow-prisoner to read it up.
This being done, G. Fox said to the judge and justices,
"`You who say you are chief justice of England, and you who are justices, you know,
that if I had put in sureties, I might have gone wherever I pleased,
and could have carried on the design, if I had one,
which major Ceely has charged me with.
And if I had spoken these words to him, which he has declared,
then you may judge whether bail or sureties could have been taken in that case.`"
Then directing his speech to major Ceely, he said, "`When or where did I take you aside?
Was not your house full of rude people,
and you as rude as any of them at our examination, so that I asked for a constable,
or other officer, to keep the people civil?
And if you are my accuser, why do you sit on the bench?
That is not a place for you to sit in; for accusers do not sit with the judges.
You ought to come down and stand by me, and look me in the face.
Besides, I would ask the judge and justices this question:
whether or not major Ceely is not guilty of this treason, which he charges against me,
in concealing it so long as he has done?
Does he understand his position, either as a soldier or a justice of the peace?
For he tells you here that I went aside with him,
and told him what a design I had in mind;
and how serviceable he might be for it--that I could
raise forty-thousand men in an hour`'s time,
and bring in King Charles, and involve the nation in blood.
Moreover, he declared that he would have aided me out of the country, but I would not go;
and therefore he committed me to prison for lack of sureties for good behavior,
as the court order declares.
Now do not you see plainly,
that major Ceely is guilty of this plot and treason that he talks of,
and has made himself a party to it, by desiring me to go out of the country,
and demanding bail of me;
and also by not charging me with this pretended treason till now, nor discovering it?
But I deny and abhor his words, and am innocent of his devilish design.`"

The judge seeing clearly by this that Ceely, instead of ensnaring G. Fox,
had ensnared himself, let fall that whole issue.
But then Ceely got up again and said to the judge, "`If it please you, my lord,
to hear me: this man struck me, and gave me such a blow, as I never had in my life.`"
G+++.+++ Fox smiling at this, said, "`Major Ceely, are you a justice of peace,
and a major of a troop of horsemen,
and you tell the judge here in the presence of the court and country, that I,
who am a prisoner, struck you, and gave you such a blow,
as you never had the like in your life?
What!
Are you not ashamed?
I ask you, major Ceely, where did I strike you; and who is your witness for that?
Who was standing by?`"
To this Ceely said it was in the castle-green,
and that captain Bradden was standing by when G. Fox struck him;
and then desired the judge to let him produce his witness for that.
George called again upon Ceely to come down from off the bench;
telling him it was not fit that the accuser should sit as judge over the accused.
Ceely then said,
"`captain Bradden is my witness,`" which made G. Fox say
to captain Bradden (who was present in the court),
"`Did you see me give him such a blow, and strike him as he says?`"
Bradden made no answer, but only bowed his head.
G+++.+++ Fox then desired him to speak up, if he knew any such thing;
but he only bowed his head again.
"`No,`" said G. Fox, "`speak up, and let the court and country hear,
and let not bowing of the head serve for your answer.
If I have done so, let the law be inflicted on me.
I fear not sufferings, nor death itself;
for I am an innocent man concerning all his charge.`"
But Bradden would not testify to it.
And the judge, finding those snares would not hold, cried, "`Take him away,
jailer;`" and fined the prisoners twenty marks apiece for not putting off their hats,
and said they were to be kept in prison till they paid their fine;
and so they were brought back to jail again.

At night captain Bradden came with seven or eight justices to see the prisoners,
and they being very civil, said that they did not believe that either the judge,
nor any in the court, believed the charges which major Ceely had made upon G. Fox.
And Bradden said, major Ceely had an intent to have taken away G. Fox`'s life,
if he could have obtained another witness.
"`But, captain Bradden,`" said G. Fox, "`why did not you witness for me or against me,
seeing major Ceely claimed you for a witness, that you saw me strike him?
And when I desired you to speak either for me or against me,
according to what you saw or knew, you would not speak.`"
To this Bradden replied, "`When Major Ceely and I came by you,
as you were walking in the castle-green, he put off his hat to you, and said,
'`How do you do, Mr. Fox?
I am your servant, sir.`' Then you said to him, '`Major Ceely, take heed of hypocrisy,
and of a rotten heart; for when did I come to be your master, or you my servant?
Do servants cast their masters into prison?`' This
was the great blow he meant that you gave him.`"
G+++.+++ Fox hearing this, remembered that as they were walking by,
Ceely had indeed spoken the aforesaid words,
and that he himself had made such an answer as was mentioned.
And now it was clear that George had not mistaken in his words,
seeing how Ceely had so openly manifested his hypocrisy and rotten-heartedness
when he complained of this to the judge in open court,
seeking to make all believe that G. Fox gave him an outward stroke with his hand.
A report of this trial was spread abroad,
and many people (some of whom being of great account in the world)
came from far and near to see him and his friends in prison,
which tended to the convincement of some.

Being settled in prison upon such a commitment from
which they were not likely to be soon released,
they declined giving the jailer seven shillings a week apiece for themselves,
and as much for their horses, which he had in a manner sought to extort from them.
But upon this occasion,
he grew so very wicked that he put them down into a nasty stinking place
where they used to put persons condemned for witchcraft and murder.
This place was so utterly vile, that it was observed that few who went into it,
did ever come out again in health; for there was no latrine in it,
and the excrement of the prisoners that over time had been put there,
had not been carried out for many years.
Thus all was like mire, and in some places its depth was to top of the shoes;
and the jailer would not allow them to cleanse it,
nor let them have beds or straw to lie on.

At night some friendly people of the town brought them a candle and a little straw;
of which they were about to burn a little to take away the stink.
The thieves lay over their heads, and the head jailer was in a room by them,
also over their heads.
But it seems the smoke went up into the room where he lay,
which put him into such a rage, that he took the pots of the thieves`' excrements,
and poured them down through a hole upon their heads; whereby they were so bespattered,
that it was loathsome to touch themselves, or one another;
besides the stink so increased, that by it and the smoke,
they were almost in danger of being suffocated.
But all this could not satisfy the rage of this cruel jailer,
and he railed against them so hideously, and called them such horrible nicknames,
that they never had heard the like before.
In this manner they were forced to stand all night, for they could not sit down,
the place being so filthy.
Thus he kept them a great while before he would let them cleanse it,
or allow them to have any food brought in, besides what they got through the grate.
And even this could not be done without difficulty;
for a young girl one time having brought them a little food,
the jailor sued her in the town-court for breaking into the prison; perhaps,
because she had a little bent a half-broken bar of the grate,
in order to get a small dish through it.
That this jailer was so desperately wicked, is not so much to be wondered at, since,
as they were informed, he had been a thief,
and on that account had been burned both in the hand and on the shoulder;
and the under-jailer in like manner; their wives had also been burned in the hand.^
footnote:[At this time,
burning of the skin (branding) was a common form
of punishment for several sorts of crimes,
and also served as an indelible mark that permanently
and publicly manifested a person`'s criminal record.]
It was not at all strange then,
that the prisoners suffered most grievously from such a wicked crew;
but it was more to be wondered at, that colonel Bennet, a Baptist teacher,
having purchased the jail and lands belonging to the castle,
had placed this man there as head-jailer.

It was much talked of, that spirits haunted this dungeon and walked there,
and that many had died in it; some thinking to terrify the prisoners with such stories.
But G. Fox told them that if all the spirits and devils in hell were there,
he was over them in the power of God, and feared no such thing; for Christ,
their Priest (who bruised the head of the devil)
would sanctify the walls and the house to them,
just as the priests were to cleanse the plague out
of the walls and the houses under the law.

Now the time of the sessions at Bodmin having come,
the prisoners drew up their suffering case, and sent the paper there.
Upon reading it,
the justices gave order that the door of Doomsdale
(thus the dungeon was called) should be opened,
and that they should have liberty to cleanse it, and to buy their food in the town.
Having obtained this liberty, they wrote to London,
and requested Anne Downer (a young woman already mentioned in this
history) to come down and to buy and prepare their food,
which she was very willing to do.
Thus she was greatly serviceable to them, and was also a good writer,
and could take things in shorthand.
They then sent up a relation of their sufferings to the protector,
who thereupon sent down an order to the governor
of Pendennis Castle to examine the matter.
And on this occasion Hugh Peters, one of the protector`'s chaplains,
told him they could not do George Fox a greater service for the
spreading of his principles in Cornwall than to imprison him there.
This was not altogether untrue, for he was visited very frequently,
and many were turned from darkness to the light;
notwithstanding the mayor of Launceston was a fierce persecutor,
casting in prison all he could get;
and he did not hesitate to search grave and respectable women for letters.

In Devonshire things were not much better; for many of those called Quakers,
that travelled through the country,
were taken up and whipped under pretense of being vagabonds.
Yes, even some tailors, who were going to mill with their cloth,
and other respectable men, were seized and whipped; and Henry Pollexsen,
who had been a justice of peace for nearly forty years before,
was cast into prison under pretense of being a Jesuit.

In the meantime Edward Pyot, who had been a captain,
and was a man of good understanding in the laws and rights of the nation,
wrote a large letter to the lord chief justice John Glyn,
wherein he plainly set before him his unlawful dealings;
and questioned whether his saying, "`If you will put off your hats,
I will hear you and do you justice,`" was not an overturning
of the laws that were made to maintain rights and justice.
Many other particulars, and among the rest,
that of G. Fox`'s "`striking`" major Ceely were also mentioned in this letter.
G+++.+++ Fox himself wrote also several papers,
wherein the odiousness of persecution was plainly set forth.

Among those that came to visit him was Thomas Lower, a doctor of medicine at London; who,
while I am writing this, is yet alive.
He asked many questions concerning religious matters,
and received such satisfactory answers from G. Fox,
that he afterwards said his words were like a flash of lightning,
they so pierced through him;
and that he had never met with such wise men in all his life, etc.
Thus he came to be convinced of the Truth,
and so entered into the communion of the despised Quakers.
While G. Fox was still in prison,
one of his friends went to Oliver Cromwell and offered himself body for body,
to lie in Doomsdale prison in his stead, if he would allow him,
and let G. Fox go at liberty.
But Cromwell said he could not do it, for it was contrary to law;
and then turning to those of his counsel said, "`Which of you would do so much for me,
if I were in the same condition?`"

Thus G. Fox continued in prison,
and it was yet a good while before he and his fellow-prisoners were released.
The next year, however, the wicked jailer received a recompense for his deeds;
for he was removed from his position, and for some wicked act was cast into jail himself;
and there his carriage was so unruly,
that he was (by the succeeding jailer) put into Doomsdale, locked in irons, beaten,
and bid to remember how he had abused those good men whom he had wickedly,
and without any cause, cast into that nasty dungeon;
but now he would deservedly suffer for his wickedness,
and the same measure he had used for others, would now be measured back to himself, etc.
And so this mischievous fellow,
who might have grown rich if he had carried himself civilly, now grew very poor,
and so died in prison.

About the same time that G. Fox was released, Cromwell called a parliament,
which met for the first sitting in the painted chamber at Westminster,
on the 17th of the month called September.
Samuel Fisher got an opportunity to come into this assembly,
where he heard the protector`'s speech, in which Cromwell spoke these words,
"`that he knew not of a single man that had suffered imprisonment unjustly in all England.`"
And after S. Fisher had found an opportunity to stand,
he said that he had a word to speak from the Lord to the protector, to the parliament,
and the people, and then he began thus:

[.embedded-content-document]
--

The burden of the word of the Lord God of heaven and of earth,
as it came unto me on the 22nd day of the last month,
and as it now lies upon me to declare it in His name, even unto you, Oliver Cromwell,
protector, (so called) of these three nations, England, Scotland, and Ireland;
and also to all you who are chosen out of the several
parts thereof to sit in parliament this day,
to consider of such things as concern the commonwealth;
and likewise to the three nations themselves, and all the people thereof,
whose rulers and representatives you are.
And as you surely do not deem yourselves too high, or too great, or too good,
to be spoken to from the Lord,
and as you desire not to fall under the guilt of that sin of "`saying to the seers,
'`See not,`' and to the prophets, '`Prophesy not, prophesy not unto us right things,
prophesy smooth things, prophesy deceits,`'`"^
footnote:[Isaiah 30:10]
I charge you all, in the name of the living God, that without interruption or opposition,
whether you like it, or like it not, you stand still and hear it;
and when I have finished, you may do with me as the Lord shall give you leave,
seeing that no law of equity condemns a man before he is heard,
especially when he speaks on so high an account as from the God of heaven Himself.

--

Scarce had he spoken thus much, when some cried, "`A Quaker, a Quaker; keep him down,
he shall not speak!`" though the protector and the
parliament men remained still and quiet.
But some others, among whom were two justices of peace, had not so much patience.
But Fisher, as he related afterwards,
believed that the protector and the parliament men would have given him audience,
had not others despised and disregarded him--some saying the protector
had already spoken long and was very hot and weary,
and that he, +++[+++Fisher]
should be ashamed to occasion his staying any longer.
Thus Fisher was interrupted, and the protector and parliament men rose and went away.

Fisher being thus prohibited, later published his speech in print,
just as he intended to have delivered it,
though not one syllable of it had been written before.
It was pretty long, and contained a sharp reproof to the hypocrisy of those who,
under a show of godliness, made long prayers, kept fasts,
and nevertheless lived in pride, pomp, and luxury,
persecuting those who really were a pious people.
And to the protector he said, that unless he took away the wicked from before him,
and all flattering voices and false accusers,
his throne would never be established in righteousness.
And in the introduction to his printed speech,
he said that before this burden came upon him,
he had prayed to God that he might be excused from delivering such a message,
thinking that a more unworthy one than himself could not have been chosen;
but that no matter what he did, he could not be rid of it;
and though he spent a whole week in fasting, tears, and supplication,
yet during this time of abstinence, he felt a daily supply and refreshment to his spirit,
so that he at last fully resigned to do what he believed
was required of him from the Lord,
and then felt all fears of the frowns of men removed from him.
Some other speeches which he intended to have made to the parliament,
but was obstructed therein, he also published afterwards in print.

In the latter part of this year it happened that Humphrey Smith,
coming to Evesham in Worcestershire, was disturbed in a meeting by the mayor,
Edward Young, who said "`he would break up the Quakers`' meetings,
or else his bones should lie in the dirt.`"
Thus resolved, he came in the month called October,
on a First-day of the week in the morning into their meeting,
in a house where H. Smith was;
and several persons (after being rudely abused) were hauled away to prison.
In the afternoon a meeting was kept in the street,
and some of the people called Quakers were (by the
order of the said mayor) put into the stocks,
and others, of which the aforesaid H. Smith was one, were shut up in a dark dungeon.
And though the mayor then said this was an "`unlawful assembly,`"
but if they would meet in houses he would not molest them;
yet, on the next First-day of the week,
upon seeing one going to a meeting that was appointed in a house, he put him in prison.

Humphrey Smith and his friends had some bedding and bed-clothes sent to them,
but the mayor caused it to be taken away from them;
and afterwards when some straw was brought for them to lie upon,
the jailer would not allow it.
And when one came and asked for liberty to fetch out their dung from them,
the mayor denied it, and ordered this man to be put in the stocks.
The place where they were kept was not twelve feet square,
and the hole to take in air was but four inches wide,
so that even during the day they were made to burn a candle for light,
when they could get one.
Here they were kept over fourteen weeks, with their own dung in the same room;
so that one of them grew sick of the stench, and yet the jailer said,
if they had been there for theft or murder he could have granted them more liberty,
but he dared not do it because of the mayor.
James Wall, one of the prisoners, was a freeman of the town and a shopkeeper,
and yet the mayor forbade his wife to stand in the market-place,
which for many years she had done.
She going to him about it, he began to ridicule her, saying:
"`I hear that your husband does abuse you.`"
To which she answered, "`My husband did never abuse me;
but as for the religious profession which he now holds,
I at one time could not acknowledge it; but seeing now how it is so much persecuted,
makes me acknowledge it, because the way of God has always been persecuted.`"
Hearing her speak in this way,
the mayor said she should not have a standing place in the market for five pounds.

About a month after,
Margaret Newby and Elizabeth Courton came to this town and
had a meeting at the house of one Edward Pitwayes;
but coming in the afternoon to visit the prisoners,
the mayor himself laid violent hands on them and caused them to be put in the stocks,
with their legs spread near a yard one from another.
He would not allow them to have a block to sit on, though they requested it.
Yet desiring to be seen as one who had some modesty,
he bid the constable to fetch a block and put it between their legs,
while he uttered some indecent expressions.
In this posture they were kept for the space of fifteen hours; and then,
in a freezing night were sent out of the town,
without allowing them to go to any place to refresh themselves.
And as to Humphry Smith, and those with him,
they were kept a good while longer in prison.

In this year Alexander Parker was at Radnor in Wales,
and bearing a testimony there against the priest Vavasor Powel,
he also preached the doctrine of Truth as occasion presented.
It was, I think, about this time that Ambrose Rigge and Thomas Robinson came to Exeter.
From there they went on to Bristol, and afterwards to Basingstoke in Hampshire.
Here, after much difficulty, they got a meeting appointed;
but before all the people had assembled, the chief priest, with the magistrates,
came there and caused them to be taken away, and tendered them the oath of abjuration.
But denying to swear for conscience sake, they were committed to prison,
where the jailer nailed planks before the window to deprive them of the light;
neither would he allow them to have a candle at night.
Here they were kept about a quarter of a year, having nothing to lie on but some straw.
But their suffering in this way had such an effect,
that some of the inhabitants seeing these unreasonable dealings,
began to inquire into the doctrine held forth by the sufferers,
and so came to be convinced of the truth thereof.
When at last they were released, Robinson went to Portsmouth where he preached repentance.
Some time after Ambrose Rigge came there also,
and in some respect reaped what Robinson had sowed;
though it was not long before he was sent out of the town.
But returning again within a short time, he found opportunity to have a meeting there,
and by his preaching some were convinced and embraced the truth.

From there he went to the Isle of Wight,
where some also received the doctrine maintained by him.
After a short stay he returned to Sussex, where he had great service.
And traveling up and down the county, he came to Weymouth and Melcombe-Regis,
where speaking in the steeple-house against the priest,
he was seized and locked up in a nasty dungeon where
there was nothing to lie on but some filthy straw,
and a stone to sit upon.
There was also no latrine; but on the ground lay a heap of dung,
where he was also forced to relieve himself.
But there being an opening at the top of the room,
he could see people go along the streets, and thus took occasion,
from this subterranean cave,
to preach to the people with such power and efficacy that his doctrine
entered into the hearts of the hearers and stuck there.
This manner of preaching became common at this time in England, and I myself,
in my young years, have been an eye-witness of it.
I have heard the prisoners lift up their voices so
that they could be heard very easily in the streets;
which made people that passed by stand still,
and hearken to what was spoken by such zealous preachers.
And though these men and women were often hindered of having meetings,
yet it was impossible to stop up the fountain from which their words flowed.
Thus it was also with Ambrose Rigge, who, after an imprisonment of eleven weeks,
was set at liberty, and then travelled up and down again.
But in many places where he came, a prison was his lot;
sometimes even when nothing could be laid to his charge except
that he had "`gone out from his dwelling-place;`" for the parliament
had made a law that all who were gone from home,
and could not give a "`satisfactory account`" of their business,
should be taken up as vagabonds.
Under this pretense,
many who travelled to the markets with their goods were seized by the way;
for if it did but appear that such a one was a Quaker (which
could easily be seen by his not putting off his hat),
then there lacked no pretense to lock him up in prison.

Ambrose Rigge traveling on,
came also to visit some of his friends in prison at Southampton.
This so incensed the mayor, Peter Seal, that without an examination,
he caused him to be fastened to the whipping-post in the market place,
where he was severely lashed by the executioner, and then put into a cart,
and sent out of the town in freezing snowy weather.
The mayor also threatened him, that if ever he returned,
he should be whipped again and burnt in the shoulder with an "`R.`" signifying _rogue_.
Notwithstanding this, he was moved of the Lord to return,
and the mayor was very eager to have this threat executed upon him;
but the other magistrates would not consent;
and not long after the mayor died of a bloody flux.^
footnote:[i.e. dysentery]
This relation has carried me a little beyond the course of time.
But now I leave Ambrose Rigge for a while,
intending to make further mention of him hereafter.

In this year William Caton went again into Scotland, and after returning,
he travelled to Bristol, and from there to Plymouth, and so on to London.
From there he made a voyage again to Holland,
where William Ames and John Stubbs had been,
and also found some among the English people at Amsterdam
who had received the doctrine they preached,
though afterwards they turned from it again.
Caton then arrived at Dort, and from there traveled to Rotterdam, where,
for lack of an interpreter that understood English, he had to make use of Latin.
But it grieved him exceedingly to meet with some unruly spirits there,
who having been in some measure convinced by William Ames,
ran out under the denomination of Quakers, into extremes, both in words and writings.
Some of these persons I know,
and have seen also some of the books they published in print, in which,
under a pretense of "`plainness,`" not one capital letter was to be found,
not even for proper names, or for the names of the authors themselves.
And because they ran out into several other extravagancies,
it was not much to be wondered at that the magistrates locked them up in Bedlam.^
footnote:[An asylum for the mentally ill.]

The ringleader of these people, was one Isaac Furnier,
who formerly (as I have heard my uncle tell, who had seen it himself),
lived like another Diogenes.^
footnote:[Diogenes (405-323 BC) was the antisocial,
ascetic philosopher who lived in a barrel and rejected
all of the norms of civilized behavior.]
And now coming among the Quakers, so called,
he made it a piece of holiness to use the most blunt language he could think of,
regardless of however absurd and irregular.
In short, he behaved himself in such a way,
that the orthodox Quakers rejected his society.
It was he, as I have understood, who was the author of that ridiculous saying,
"`My spirit testifies,`" which, though not approved nor used by the true Quakers,
yet has been so spread among the people in the Low Countries,
that it has been constantly asserted that the Quakers
used to say so of anything they intended to do.
Dr. Galenus Abrahams once told me, that this man, coming to his door,
and finding the doctor`'s name written on the post of the door (as is usual in
Holland) took his knife and scratched out the letters "`Dr.`" signifying doctor.
Upon this occasion the doctor asked him why he did so, and his answer was,
"`because the Spirit did testify so unto me.`"
And being further asked, if that spirit did move him to stab the doctor with the knife,
would he follow that motion, he answered (as the doctor affirmed to me) "`Yes.`"
But whether this anecdote be true or not,
this is true--that this Isaac Furnier was a passionate and giddy-headed man,
whom the true Quakers could not acknowledge as one of them,
though he had translated many of their books out of English into Dutch;
and would also preach among them.
But at length he left them, and turning Papist, fell into a dissolute and debauched life.

But to return to William Caton; coming to Amsterdam,
he did not find much more satisfaction there than at Rotterdam;
for several highly conceited professors,
who seemed to approve the doctrine preached by the Quakers,
were more willing to take it upon themselves to teach,
than to receive instruction from others.
Wherefore W. Caton did not stay long at Amsterdam, but returned to Rotterdam,
and from there went to Zealand, and arrived at Middleburgh.
He was accompanied by a certain young man,
who went to some of the meeting-places in that city, and there was apprehended.
Caton understanding that his friend had been committed, went to visit him,
and the officials perceiving that he was his companion, imprisoned him also.
And after having been kept in prison some days, being weak in body,
it was ordered that they should be sent to England;
and so they were carried in a coach-wagon to the waterside,
being conducted by a guard of soldiers to protect them against the rude multitude,
and brought on board a ship of war.
Here Caton suffered great hardship;
for the seamen were so ill-natured that they would not allow
him so much as a piece of sailcloth for cover,
but he was made to lie upon the bare boards in very cold and stormy weather.
But though thus poorly treated, yet he felt his strength increase,
and so experienced the mercies of God.
It was in November when he arrived at London,
where he was kindly received by the brethren; and after some stay there,
he went to Hampshire, Surry, Sussex, and Kent.

Not long before this, G. Fox came to Exeter, where James Nayler was in prison,
and spoke to him by way of reproof.
Nayler slighted G. Fox`'s correction, though he offered to kiss him;
but George was unwilling to permit this, saying,
since Nayler had turned against the power of God,
he could not receive his show of kindness.
It appeared by letters which the magistrates found in Nayler`'s pocket at Bristol,
that the Quakers had found fault with him,
and had reproved him of his high-mindedness before it launched out into
that extravagant act which made so great a noise in the world,
and which now has been mixed with many untruths and false turns.
I have therefore thought it worthwhile to inquire carefully into it,
in order to give a true relation of matters of fact.

This James Nayler was born of honest parents,^
footnote:[His father was a husbandman of good repute,
having a competent estate on which to live industriously,
according to the manner of the country where he dwelt.
He was well educated in English, and wrote well.
About the age of twenty-two he married, and then removed into Wakefield parish,
where he continued until the wars broke out in 1641.
He then went into the army, and was a soldier eight or nine years,
first under the Lord Fairfax,
and was afterwards quarter-master under major-general Lambert,
till he was disabled by sickness in Scotland,
and returned home about 1649.--J. Whiting`'s account.]
in the parish of Ardesley, near Wakefield in Yorkshire, about the year 1616.
He had served in the parliament army,
being quarter-master in major-general Lambert`'s troop in Scotland.
He was then a member of the Independents, and afterwards, in the year 1651,
he entered into the communion of the Quakers, so called.^
footnote:[He and Thomas Goodair were convinced by George Fox, near Wakefield around 1651,
as were also Richard Farnsworth, Thomas Aldam, William Dewsbury, and wife,
about the same time.
And in the beginning of the year following, as he was in the field at plough,
meditating on the things of God, he heard a voice,
bidding him to go out from his kindred and from his father`'s house;
and a promise was given with it, that the Lord would be with him;
whereupon he did exceedingly rejoice that he had heard the voice of God,
whom he had professed from a child and endeavored to serve.
And when he went home he made preparation to go; but then not being obedient,
the wrath of God was upon him, so that he became a wonder to many,
and it was thought he might die.
But he was afterwards made willing, and upon going out with a friend,
not thinking then of a long journey, he was commanded to go into the West,
not knowing what he was to do there; but when he came,
it was given him what he was to declare.
And so he continued, not knowing one day what he was to do the next;
and the promise of God (that He would be with him) he found
made good to him every day.--Collection of J. N.`'s writings.]
He was a man of excellent natural abilities, and at first did acquit himself well,
both in word and writing among his friends,
so that many came to receive the Truth by his ministry.
He came to London towards the latter end of the year 1654, or beginning of 1655,
and found there a meeting of Friends which had already been gathered
in that city by the service of Edward Burrough and Francis Howgill.
There he preached in such an eminent manner, that many, admiring his great gift,
began to esteem him much above his brethren,
which excessive esteem brought him no benefit,
and gave occasion for some discord in the society.
This tension rose to such a hight, that some forward and inconsiderate women,
of whom Martha Simmons was the chief,
assumed the boldness to dispute with Francis Howgill
and Edward Burrough openly in their preaching,
and thus to disturb the meetings;^
footnote:[We may suppose that the practice of these women was somewhat
like that which gave occasion to the apostle Paul to say,
"`Let your women keep silence in the churches,
for it is not permitted unto them to speak.`"
1 Cor.
14:34. This prohibition of speaking, must refer to a voluntary discourse,
by way of reasoning or disputing,
and not to those times when they had an immediate impulse or burden to prophesy;
for the apostle, in the same epistle,
has defined prophesy to be "`speaking unto men to edification, exhortation,
and comfort.`"
chapter 14:3. And he has also, in chapter 11,
made express mention of women`'s praying and prophesying, together with the men. --W. Sewel]
whereupon they, who were truly excellent preachers,
did not fail (according to their duty) to reprove this indiscretion.
But these women were then so disgusted, that Martha and another woman,
went and complained to James Nayler in order to incense
him against F. Howgill and E. Burrough;
but this did not succeed,
for he showed himself afraid to pass judgment upon his brethren as they desired.
Hereupon Martha fell into a passion, in a kind of moaning or weeping, and,
bitterly crying out with a mournful shrill voice, said, "`I looked for judgment,
but behold oppression; for righteousness but behold a cry!`"^
footnote:[Isaiah 5:7]
And so she cried aloud in a passionate lamenting manner,
which so entered and pierced J. Nayler,
that it smote him down into so much sorrow and sadness,
that he was much dejected in spirit and disconsolate.
Fear and doubting then entered him, so that he came to be clouded in his understanding,
bewildered, and at a loss in his judgment,
and then became estranged from his best friends,
because they did not approve of his conduct;
for he began to give ear to the flattering praises of some whimsical
people which he ought to have abhorred and reproved them for.
But his sorrowful fall ought to stand as a warning,
even to those that are endued with great gifts, that they do not presume to be exalted,
lest they also fall, but rather endeavor to continue in true humility,
in which alone a Christian can be kept safe.

Hannah Stranger, whom I know very well,
and have reason to believe to be a woman of high imaginations,
at this time wrote to him several very extravagant letters,
calling him the everlasting Son of Righteousness, Prince of Peace,
the only begotten Son of God, the fairest of ten thousands, etc.
In the letters of Jane Woodcock, John Stranger, and others,
were expressions of the like extravagancy; and the said Hannah Stranger, Martha Simmons,
and Dorcas Erbury, arrived to such a height of folly, that in the prison at Exeter,
they kneeled before Nayler and kissed his feet:
but as to what has been divulged concerning his committing of fornication,
I never could find (though I was very inquisitive
into the case) that he was in the least guilty thereof.^
footnote:[In a published statement of recantation,
printed after his release from prison and reconciliation to the Society of Friends,
James Nayler wrote the following words in reference to this accusation:
"`It is in my heart to confess to God, and before men, my folly and offense in that day.
Yet there were also many things formed against me in that day (to take away my
life and bring scandal upon the Truth) of which I am not guilty at all;
such as the accusation that I committed adultery with some
of those women who came with us from Exeter prison,
and also those who were with me at Bristol the night before I suffered there.
With regard to both of these accusations I am clear before God,
who kept me in that day both in thought and deed, as to all women, like a child;
God is my witness.
This I mention in particular (hearing of some who still do not cease to reproach God`'s
Truth and people therewith) that the mouth of enmity might be shut from evil speaking;
though this touches not my conscience.`" [.book-title]#Collection of James Nayler`'s Writings#, p. 54.]
But even so, he was already too much carried away, and grew even more exorbitant;
for being released from that prison, and riding to Bristol in the beginning of November,
he was accompanied by the aforesaid women and various other persons;
and passing through the suburbs of Bristol,
one Thomas Woodcock went bareheaded before him,^
footnote:[At this time,
removing the hat (or going "`bareheaded`") was a sign of honor and respect,
and one that Quakers used only in their solemn approaches to the Lord in prayer.]
one of the women led his horse, and Dorcas, Martha,
and Hannah spread their scarfs and handkerchiefs before him, while the company sung,
"`Holy, holy, holy, is the Lord God of hosts, Hosannah in the highest: holy, holy, holy,
is the Lord God of Israel.`"
Thus these mad people sung, while they were walking through the mire and dirt,
till they came into Bristol,
where they were examined by the magistrates and committed to prison;
and not long after Nayler was carried to London to be examined by the parliament.
How it went there may be seen in the printed trial,
which the parliament was pleased to publish.^
footnote:[But the extravagancy of the sentence which that parliament passed upon him,
together with other circumstances,
give great reason to suspect the account was not impartially taken,
and was published to justify their cruelty.
Regarding this publication, John Whiting wrote,
"`Some of his answers were innocent enough, some not clear,
and some aggravated by his adversaries; some of them he denied, some he acknowledged;
they reported the worst, and more than was true in some things,
adding and diminishing as they were inclined.
Much was lacking of what he had spoken to the committee,
who were wresting and perverting his words in what way they could,
endeavoring to draw words out of him to ensnare him and take away his life.
And to show their confusion when he was before them,
they bid him kneel and put off his hat to them,
though a part of the charge against him was that some had kneeled to him.`"]
I believe that James Nayler was clouded in his understanding
during the whole course of these events.
But however grievous his fall was, yet it pleased God,
in His infinite mercy to raise him up again,
and to bring him to such a sincere repentance,
that (as we may see in what follows) he abhorred not only this whole business,
but also manifested his heavy sorrow in heartbreaking expressions, which were published,
as will be shown in its proper place.

What has been said of the odd happenings in Exeter prison,
and of his riding into Bristol, was not denied by him,
nor by the rest of the company when they were examined by a committee of parliament,
who made their report on the 5th of December, to which the house agreed the next day.
On the 16th, this business,
which had been treated both forenoons and afternoons (and not without much opposition,
for many members of the parliament did not approve the severity used against him),
was proposed for the twelfth time--which made a clever author say afterwards,
that it was a wonder to many why this foolish business
should hold so many wise men so long at work.
But on the 17th, after a long debate, they came to this resolution:

[.embedded-content-document.address]
--

That James Nayler be set in the stocks, with his head in the stocks, in the Palace-yard,
Westminster, during the space of two hours, on Thursday next,
and then be whipped by the hangman as he is conveyed through the streets of London,
from Westminster to the Old Exchange.
There he is likewise to be set in the stocks,
with his head in the stocks for the space of two hours,
between the hours of eleven and one, on Saturday next,
in each place wearing a paper containing an inscription of his crimes.
Then, at the Old Exchange his tongue is to be bored through with a hot iron,
and his forehead is to be stigmatized with the letter
B+++.+++ Afterwards he is to be sent to Bristol,
and be conveyed into and through the said city on horseback, with his face backward,
and there also be publicly whipped the next market-day.
From there he is to be committed to prison in Bridewell, London,
and kept from the society of all people,
and put to hard labor till he shall be released by parliament;
during which time he is to be debarred the use of pen, ink, and paper,
and shall have no relief but what he earns by his daily labor.

--

It was long before they could agree on the sentence;
for though they supposed that blasphemy has been committed,
yet his tongue seemed not properly guilty of it,
since it was never proved that any blasphemous words had been spoken by him.^
footnote:["`At the Lancaster court sessions,
the priest got some to swear blasphemy against George
Fox (which was the common accusation in those days),
but he was cleared, and the priests were enraged,
who thereupon sent a petition to the council of state against George Fox and James Nayler,
who answered the same in a book called, [.book-title]#Saul`'s Errand to Damascus#.
After this, J. Nayler was persecuted in several places, beaten, stoned,
and cruelly treated by the priests and their rude followers, and in danger of his life.
Afterward, by the instigation of the priest,
he and Francis Howgill were committed to Appleby Jail,
and tried on an indictment for blasphemy,
for saying that '`Christ was in him,`' according to Col. 1:27.
'`Christ in you the hope of glory.`'
He was also another time charged with blasphemy for asserting in a book that
'`justification is by the gift of God`'s Righteousness,`'
which he proved from Romans 5,
and so stopped their mouths, and cleared himself.
By this we may see what this generation, who were righteous in their own eyes,
would have called __blasphemy__.`"
--John Whiting`'s account.]
And indeed,
many thought it a very severe judgment to be executed upon one whose crime seemed more
to proceed from a clouded understanding than from any willful intention of evil.

Now although several persons of different religious persuasions,
being moved with compassion towards Nayler as a man carried away by foolish imaginations,
had offered petitions to the parliament on his behalf,
yet it was resolved not to read them until the sentence was pronounced against him.

There lived then at London, one Robert Rich, a merchant (a very audacious man),
who wrote a letter to the parliament, wherein he attempted to show what blasphemy was;
and on the 15th of December, several copies thereof were delivered to particular members;
and in that which was given to the speaker, these words were written at the bottom:
"`If I may have liberty of those that sit in parliament, I do here attend at their door,
and am ready, out of the Scriptures of Truth,
to show that not anything James Nayler has said or done is blasphemy,`" etc.

After judgment was concluded,
the parliament resolved that the speaker should be authorized
to issue his warrants to the sheriffs of London and Middlesex,
the sheriff of Bristol, and governor of Bridewell,
in order to see the said judgment put in execution.
By some it was questioned whether this was a sufficient warrant,
unless the protector concurred in the matter;
but Cromwell seemed unwilling to meddle with it.
The issue being thus far agreed upon, J. Nayler was brought up to the bar,
and when the speaker, sir Thomas Widdrington,
was about to pronounce the aforementioned sentence,
Nayler said he did not know his offense.
To which the speaker replied, "`You shall know your offense by your punishment.`"
After sentence was pronounced, though J. Nayler bore it with great patience,
yet it seemed he would have spoken something, but was denied the liberty.
Nevertheless he was heard to say with a composed mind, "`I pray God,
He may not lay it to your charge.`"

The 18th of December, J. Nayler suffered part of the sentence;
and after having stood a full two hours with his head in the stocks,
he was stripped and whipped behind a cart, from Palace-yard to the Old Exchange,
receiving three hundred and ten stripes.
The executioner would have given him one more (as he confessed to the sheriff,
for there were three hundred and eleven kennels) but his
foot slipped and the stroke fell upon his own hand,
which hurt him much.
All this Nayler bore with so much patience and quietness,
that it astonished many of the beholders,
though his body was in a most pitiful condition.
He was also much hurt by the horses treading on his feet,
whereon the print of their nails could be seen.
Rebecca Travers, a sober and respectable person, who washed his wounds,
in a certificate which was presented to the parliament, and afterwards printed, said,
"`There was not the space of a man`'s fingernail free from stripes and blood,
from his shoulders near to his waist.
His right arm was sorely striped,
his hands much hurt with cords so that they bled and swelled.
The blood and wounds on his back did very little appear at first sight,
by reason of abundance of dirt that covered them, till it was washed off.`"
Indeed, his punishment was so severe,
that some judged his sentence would have been more
mild if he had been presently put to death.
And it seemed that there was indeed a party,
who not being able to prevail so far in parliament as to have him sentenced to death,
yet strove to the utmost of their power to make him sink under the weight of his punishment.
The 20th of December was the time appointed for executing the other part of the sentence,
that is, the boring through his tongue and the stigmatizing of his forehead;
but by reason of the most cruel whipping, he was brought to such a low condition,
that many persons of note, being moved with compassion,
presented petitions to the parliament on his behalf,
who then respited his further punishment for one week.

During this interval, several persons presented another petition to parliament,
in which were these words:

[.embedded-content-document.address]
--

Your moderation and clemency in respiting the punishment of James Nayler,
in consideration of his illness of body,
has refreshed the hearts of many thousands in these cities,
who are altogether unconcerned in his practice.
Wherefore we most humbly beg your pardon,
who are constrained to appear before you in such a suit (not daring to do otherwise),
requesting that you would remit the remaining part
of your sentence against the said J. Nayler,
leaving him to the Lord, and to such gospel remedies as He has sanctified.
We are persuaded you will find such a course of love
and forbearance more effectual to reclaim him;
and it will leave a seal of your love and tenderness upon our spirits.

--

This petition being presented at the bar of the house
by about one hundred persons on behalf of the whole,
was accordingly read and debated by them;
but believing it not likely to produce the desired effect,
the petitioners thought themselves bound in duty and conscience to address
the protector for remitting the remaining part of the sentence;
who, thereupon, sent a letter to the parliament,
which occasioned some debate in the house.
But seeing the day for the execution of the remaining
part of the sentence was drawing near,
the petitioners made a second address to the protector.
Indeed,
it was very remarkable that so many inhabitants who
were not of the society of those called Quakers,
showed themselves so much concerned in this business.
To me this seems to have proceeded merely from compassion
towards the person of James Nayler,
whom they regarded as one who had rather fallen into error through unwatchfulness,
than to have been guilty of willful blasphemy;
for then he would not have deserved so much pity.

But, notwithstanding all these humble petitions,
the public preachers (it seems) prevailed so much with Cromwell,
that he could not resolve to put a stop to the intended execution.
Five of these ministers, whose names I find to be Caryl, Manton, Nye, Griffith,
and Reynolds, came on the 24th of December,
by order from the parliament (as it was said) to Nayler,
in order to speak with him concerning the things for which he was detained;
and would not permit either friend or any other person to be present in the room.
A certain impartial or neutral person desired earnestly that this be allowed,
but it was denied him.
However, this man, coming into the prison after the conference,
asked Nayler what had been the issue of their meeting, who told him:
that he had told those ministers he saw they had an intent
to make him suffer (though innocent) as an evil-doer,
and therefore had denied any to be present that might
be an indifferent judge between them and him;
and that therefore he should not say anything,
unless what passed between them was written down,
and a copy thereof was given him to keep, or left with the jailer,
having been signed by them.
This was consented to by them, and so they propounded several questions unto him,
and took his answers in writing.
They asked him if he was sorry for the blasphemies that he was guilty of,
and whether he did recant and renounce the same; to which he answered:
"`What blasphemies?
Name them.`"
But they not being able to instance in any particular, he continued,
"`Would you have me recant and renounce, you know not what?`"
Then they asked him whether he did believe there was a Jesus Christ?
To which he answered, he did believe there was,
and that Jesus had taken up His dwelling in his heart and spirit,
and that it was for the testimony of Him he now suffered.
Then one of the preachers said,
"`But I believe in a Jesus that never was in any man`'s heart;`" to which Nayler replied,
he knew no such Christ, for the Christ he witnessed filled heaven and earth,
and dwelt in the hearts of believers.

Next they demanded of him why he allowed those women to worship and adore him?
To this he replied, "`Bowing to the creature I deny;
but if they beheld the power of Christ, wherever it was, and bowed to it,
I had nothing by which I might resist that, or gainsay it;`"^
footnote:["`The most that I find in his examination, either in Bristol or London,
before the committee of parliament, as published from their report,
was that James Nayler acknowledged that Christ was in him, but never that he was Christ;
and that he took the honor given, not as to himself,
but as to Christ in him--which yet is more than any man ought to receive;
for when the beloved disciple, John, fell at the angel`'s feet to worship him,
he (though an angel) said unto him, '`See you do it not, I am your fellow servant,
and of your brethren that have the testimony of Jesus, worship God.`' Rev.
19:10. But that J. Nayler received this to himself, as a creature,
he utterly denied (see Trial, p. 15),
saying that there could not be a more abominable thing than to take from the Creator,
and give to the creature, etc.`"
--John Whiting]
and then he said to the ministers, "`Have you thus long professed the Scriptures,
and do you now stumble at what they hold forth?`"
Whereupon they desired of him one instance in Scripture
wherein such a practice was held forth.
Nayler answered,
"`What do you think of the Shunamite`'s falling down
at the feet of Elisha and bowing before him?
As well as several others in Scripture who are spoken of, such as Abigail to David,
and Nebuchadnezzar to Daniel.`"
Upon this they pause awhile, and said at length,
"`That was but a civil act or acknowledgement;`" to which he replied,
"`So you might interpret the act of those women also, if your eye were not evil,
seeing the outward action is one and the same.`"
Then, perceiving that they were seeking to wrest words from him to serve their purpose,
he said, "`How soon have you forgotten the works of the bishops,
and are now found in the same, seeking to ensnare the innocent.`"
Whereupon they rose up, and with bitterness of spirit, burned what they had written,
and so left him with some bemoaning expressions.
And when they were departing,
he desired of them that the parliament would send him such
questions in writing as they desired to have answered,
and give him leave to return his answers in writing also.

By this it seems that Nayler, though still under some cloud,
yet was a little more clear in his understanding than before;
but he was encountered by fierce enemies,
and therefore the execution of his sentence was not stopped,
but performed on the 27th of December.
Robert Rich, that forward man, of whom something has been mentioned already,
was this day at the parliament door from eight in the morning till about eleven,
crying out to the various parliament men as they passed by.
To one whom he judged to be innocent, he said, "`He that dwells in love, dwells in God,
for God is love!`"
And to another, whom he thought to be swayed by envy, he said,
"`He that hates his brother is a man-slayer,
and he that hates his brother is a murderer.`"
Some then thought that Nayler would not have to suffer any further punishment because
many honorable persons had approached parliament and the protector on his behalf;
but Rich knowing how the case stood,
told the people that the innocent was going to suffer;
and to some of the parliament men he cried out that
he was clear from the blood of all men;
and that he desired them to be so too.
Rich then went towards the Exchange, and got up on the stocks,
where he held Nayler by the hand while he was burnt
in the forehead and bored through the tongue;
and he was more than a little affected with Nayler`'s suffering,
for he then licked his wounds, seeking (as it seems) to allay the pain.
He then led him by the hand down from the stocks.
It was very remarkable that though there were perhaps many thousands of people,
yet they were very quiet,
and few were heard to revile him or seen to throw anything at him.
And when he was burning, the people both before and behind him, and on both sides,
with one consent stood bareheaded,
as seeming generally moved with compassion and goodwill towards him.

However, many of his enemies now rejoiced,
seeing how a few among the Quakers (such as Robert Rich
and the like sort of people) did side with Nayler,
while the Quakers in general spoke against him and his doings;
for those who hoped to see their downfall manifested
openly that things now went as they desired,
seeing that the Quakers (as they said) were divided among themselves.
But time showed that this pretended division soon came to an end,
and that those diviners and guessers overshot their mark.
How it went with the execution of Nayler`'s sentence at Bristol, I am not informed;^
footnote:["`He was sent to Bristol, and there whipped from the middle of Thomas street,
over the bridge, up High street, to the middle of Broad street,
all which he bore with wonderful patience, as related by an eye-witness.
He was then sent by Tower lane the back way to Newgate,
and from there returned to Bridewell, London, according to the sentence.`"
--John Whiting]
but by a letter from one Richard Snead, an ancient man of about eighty years,
I have understood that Nayler had written a letter to the magistrates of Bristol,
wherein he had disapproved, and penitently condemned, his conduct there.^
footnote:[After Nayler was set at liberty, he went to Bristol, where in a public meeting,
he made confession of his offense and his former fall,
and spoke in so powerful a manner as tendered and broke the meeting into tears,
so that there were few dry eyes (as was related by some then present),
and many were bowed in their minds and reconciled to him.--John Whiting`'s account.]
After this he was brought to Bridewell, London (according to his sentence),
where he continued a prisoner about two years,
during which confinement he came to a true repentance for his transgression;
and having been granted the use of pen and ink,
wrote several books and papers condemning his error, which were published in print.
And after his release, he published several others, one of which, by way of recantation,
is as follows:

[.embedded-content-document.paper]
--

Glory to God Almighty, who rules in the heavens,
and in whose hands are all the kingdoms of the earth; who raises up,
and casts down at His will; who has ways to confound the exaltation of men,
to chastise His children, and to make men know they are as grass before Him.
Indeed, His judgments are above the highest of men, His pity reaches the deepest misery,
and the arm of His mercy is underneath, to lift up the prisoner out of the pit,
and to save those who trust in Him from the great destruction which vain man,
through his folly, brings upon himself.
For He has delivered my soul from darkness,
and made way for my freedom out of the prison-house,
and ransomed me from the great captivity; He who divides the sea before Him,
and removes the mountains out of His way,
in the day when He takes upon Himself to deliver the oppressed
out of the hand of him that is too mighty for him in the earth.
Let His name be exalted forever, and let all flesh fear before Him,
whose breath is life to His own, but a consuming fire to the adversary.

And as for the Lord Jesus Christ, His everlasting dominion is upon earth,
and His kingdom is above all the power of darkness;
even that Christ of whom the Scriptures declare, who was, and is, and is to come,
the light of the world to all generations.
Of His coming I testify with the rest of the children of light,
who are begotten of the immortal seed; for His truth and virtue now shine in the world,
being the Savior of all who believe therein unto righteousness and eternal life.
He has been the rock of my salvation,
and His Spirit has given quietness and patience to
my soul in deep affliction for His name`'s sake.
May He be praised forever.

But condemned forever be all false worship with which any
have idolized my person in the night of my temptation,
when the power of darkness had risen above in me.
All the casting of their clothes in the way, their bowing and singing,
and all the rest of those wild actions which did in any way tend to dishonor the Lord,
or draw the minds of any from the measure of Christ Jesus in themselves,
to look at flesh (which is as grass),
or to ascribe to something visible that which belongs to Christ Jesus.
All of that I condemn,
by which the pure name of the Lord has been in any
way blasphemed through me in the time of my temptation,
or by which the spirits of any have been grieved who truly
love the Lord Jesus throughout the whole world,
in whatever profession.
This offense I confess, which has been sorrow of heart,
that the enemy of man`'s peace in Christ should get
this advantage in the night of my trial,
to stir up wrath and offenses in the creation of God--a
thing the simplicity of my heart did not intend,
the Lord knows; who in His endless love has given me power over it now, to condemn it.

And also that letter which was sent to me in Exeter, by John Stranger,
when I was in prison, with these words, "`Your name shall be no more James Nayler,
but Jesus;`" this I judge to be written from the imagination;
and a fear struck me when I first saw it, so I put it close into my pocket,
not intending that any should see it.
But they finding it on me, spread it abroad,
which the simplicity of my heart never approved.
So this I deny also, that the name of Christ Jesus was received instead of James Nayler,
or ascribed to me; for that name is to the promised Seed to all generations;
and he that has the Son, has the name, which is His life and power,
the salvation and the unction, into which name all the children of light are baptized.
So the name of Christ I confess before men,
which name to me has been a strong tower in the night and in the day.
This is the name of Christ Jesus, which I confess, the Son and the Lamb,
the promised Seed, wherever He speaks in male and female.
But whoever does not have the Son in himself, does not have the life,
neither can they have it by idolizing my person, or the person of any flesh.

And all those ranting, wild spirits,
who then gathered around me in that time of darkness,
and all their wild actions and wicked words against the honor of God,
and His pure Spirit and people--I deny that bad spirit,
together with its power and works.
And as far as I gave advantage, through lack of judgment,
for that evil spirit to arise in any, I justly take shame to myself,
having formerly had power over that spirit in judgment and discerning, wherever it was.
This darkness came over me through lack of watchfulness
and obedience to the pure eye of God,
and through not diligently minding the reproof of life,
which condemns the adulterous spirit.
So the adversary got advantage, who always seeks to devour;
and being taken captive from the true light,
I was walking in the night where none can work, as a wandering bird fit for a prey.
And truly, if the Lord of all my mercies had not rescued me, I would have perished;
for I was as one appointed to death and destruction,
and there was none that could deliver me.
All of this I confess, that God may be justified in His judgment,
and magnified in His endless mercies, who did not forsake His captive in the night,
even when His Spirit was daily provoked and grieved;
but has brought me forth to give glory to His name forever.

It is in my heart to confess to God, and before men, my folly and offense in that day.
Yet there were also many things formed against me in that day (to take away my
life and bring scandal upon the Truth) of which I am not guilty at all;
such as the accusation that I committed adultery with some
of those women who came with us from Exeter prison,
and also those who were with me at Bristol the night before I suffered there.
With regard to both of these accusations I am clear before God,
who kept me in that day both in thought and deed, as to all women, like a child;
God is my witness.
This I mention in particular (hearing of some who still do not cease to reproach God`'s
Truth and people therewith) that the mouth of enmity might be shut from evil speaking;
though this touches not my conscience.

And concerning the report that I raised Dorcas Erbury from the dead physically,
this I also deny, and I condemn this testimony to be out of the Truth;
though that power which quickens the dead I do not deny,
which is the Word of eternal life.
This I give forth,
that it may go as far as the offense against the Spirit of Truth has gone abroad,
that all burdens may be taken off of the Truth, and that the Truth, the true light,
and all that walk therein may be cleared, and the deeds of darkness be condemned;
and also that all who are yet in darkness may not act in the night,
but stay their minds upon God, who dwells in the light,
and has no fellowship with the workers of iniquity.
For had I done this when darkness first came upon me, and not been led by others,
I would not have run myself against the Rock to be
broken (which Rock had so long borne me,
and of whom I had so largely drank, and of which I now drink in measure).
To Him be the glory of all, and to Him every tongue must confess, as Judge and Savior,
God over all, blessed forever.

--

Nayler added to this an exhortation to the reader how to behave if, at any time,
he comes to be tempted to sin, and also a warning not to rely too much upon gifts,
wisdom, and knowledge, and then concluded with these words:

[.embedded-content-document.paper]
--

These things I have learned in the depths and in secret, when I was alone,
and now declare openly in the day of Your mercy, O Lord.
Glory to the Highest forevermore,
who has thus far set me free to praise His righteousness and His mercy;
and to the eternal, invisible, pure God, over all, be fear, obedience,
and glory forevermore.
Amen.

[.signed-section-signature]
James Nayler

--

He wrote another paper wherein he related at length,
how it was by unwatchfulness that he came to fall,
after having once obtained much victory over the power of Satan, by the grace of God,
when he daily walked humbly in his fear;
for he had formerly labored faithfully in the ministry of the gospel for some years.
But what is remarkable is that,
though he used to pass with great boldness through all opposition,
yet coming to the city of London (just prior to his fall) he entered
it with the greatest fear that ever he knew in any place,
foreseeing in spirit (as he relates) something to befall him there,
but not knowing what it might be:

[.embedded-content-document.paper]
--

Yet I had at that time (he continues) the same presence and power I had known before,
in whatever place or service I was led of the Spirit;
for keeping in that life I never returned without victory in the Lord Jesus Christ.
But not minding in all things to stand single and
low to the motions of that endless life,
by Him to be led in all things within and without,
but giving way to the reasoning part with respect to some
things which in themselves had no seeming evil,
little by little my mind was drawn out after trifles, vanities, and persons,
which took hold in the affectionate part.
By this my mind was drawn out from the constant watch and pure fear,
into which I was once begotten.
Thus, having in a great measure lost my own guide, and darkness having come upon me,
I sought a place where I might be alone to weep and cry before the Lord,
that I might find His face and recover my condition.

But by then my adversary, who had long waited his opportunity, had got in,
and bestirred himself every way, so that I could not be hidden;
and several messages came to me, some true, and some false, as I have seen since.
So, knowing some to be true (namely, how I had lost my condition),
with this I let in the false messages also;
and so letting go of what little remained of the true light in myself,
I gave myself up wholly to be led by others,
whose work was then to divide me from the children of light,^
footnote:[i.e. The Society of Friends]
which was done, though much was done by several of them to prevent it,
and in tender love many labored to help me.
And after I was led out from them,
the Lord God of my life sent several of His servants with His word after me,
calling for my return, all of which was rejected.
Yes, my provocation in that time of temptation was exceedingly
great against the pure love of God;
yet He left me not.
And after I had given myself under the power of my adversary,
and darkness had risen above in me,
then he so prevailed that all things were turned and perverted against my right seeing,
hearing, or understanding; only I had a secret hope and faith in my God,
whom I had formerly served, that He would bring me through it, and to the end of it,
and that I should again see the day of my redemption from under it all.
And this quieted my soul in my greatest tribulation.

--

The author then, seriously exhorting others who might also fall into great temptation,
concludes with these words:

[.embedded-content-document.paper]
--

He who has saved my soul from death thus far, and has lifted my feet up out of the pit,
even to Him be glory forever.
Let every troubled soul trust in Him, for His mercy endures forever.

[.signed-section-signature]
James Nayler

--

That he came to a perfect recovery out from having been so deceived,
seems to appear plainly by the following thanksgiving to God for His mercies,
which he also published after his fall:

[.embedded-content-document.paper]
--

It is in my heart to praise You, O my God.
Let me never forget You, what You have been to me in the night,
by Your presence in the day of trial, when I was beset in darkness,
when I was cast out as a wandering bird, when I was assaulted with strong temptations;
then Your presence in secret did preserve me, and in a low state I felt You near me.
When the floods sought to sweep me away,
You set a boundary for them how far they should pass over.
When my way was through the sea, and when I passed under the mountains,
there You were present with me.
When the weight of the hills was upon me, You upheld me,
else I would have sunk under the earth.
When I was as one altogether helpless;
when tribulation and anguish was upon me day and night,
and the earth was without foundation; when I went on in the way of wrath,
and passed by the gates of hell; when all comforts stood afar off,
and he that is my enemy had dominion; when I was cast into the pit,
and was as one appointed to death; when I was between the millstones,
and as one crushed with the weight of his adversary; as a father, You were with me, yes,
the rock of Your presence.
When the mouths of lions roared against me, and fear took hold of my soul in the pit,
then I called upon You in the night, and my cries were strong before You daily.
You answered me from Your habitation, and delivered me from Your dwelling-place; saying,
"`I will set you above all your fears,
and lift up your feet above the head of oppression.`"
I believed, and was strengthened, and Your word was my salvation.

You did fight on my behalf when I wrestled with death;
and when darkness would have shut me up, then Your light shone about me,
and Your banner was over my head.
When my work was in the furnace, and as I passed through the fire,
I was not consumed by You, though the flames ascended above my head.
When I beheld the dreadful visions and was among the fiery spirits, Your faith stayed me,
else through fear I had fallen.
I saw You and believed, so the enemy could not prevail.

When I look back into Your works I am astonished, and see no end of Your praises.
Glory, glory to You, says my soul, and let my heart be ever filled with thanksgiving.
While Your works remain, they shall show forth Your power.
Then did You lay the foundation of the earth, and lead me under the waters,
and in the deep did You show me wonders, and Your forming of the world.
By Your hand You led me in safety, till You showed me the pillars of the earth.
Then did the heavens shower down, they were covered with darkness,
and the powers thereof were shaken, and Your glory descended.
Yes, You filled the lower parts of the earth with gladness,
and the springs of the valleys were opened, and Your showers descended abundantly,
so that the earth was filled with virtue.
You made Your plant to spring, and the thirsty soul became as a watered garden.
Then did You lift me out of the pit, and set me forth in the sight of my enemies.
You proclaimed liberty to the captive, and called my acquaintances near me.
They to whom I had been a wonder, looked upon me,
and in Your love I obtained favor from those who had forsaken me.
Then did gladness swallow up sorrow, and I forsook all my troubles; and I said,
"`How good is it that man be proved in the night, that he may know his folly;
so that every mouth may become silent in Your hand until You make man known to himself,
and have slain the boaster, and showed him the vanity that vexes Your Spirit.`"

[.signed-section-signature]
James Nayler

--

This plainly appears to be a poetical piece,
as the author makes use of allegorical sayings throughout to signify
the great anguish and tribulation he had been under,
expressing how the powers of darkness had so prevailed
in him as to grieve the Spirit of God,
to put a stumbling block in the way of the simple,
and to cause the way of Truth to be evilly spoken of.

The hatred of his enemies was the fiercer, because, prior to his fall,
he had undisguisedly and clearly demonstrated the duty of rulers, preachers, and lawyers;
for in a certain book, published by him in the year 1653,
in order to exhort men to repentance, he writes thus to the rulers:

[quote]
____
O you rulers of the people, who are set up to judge between a man and his neighbor,
should you not judge for God, and not for man?
Should you not be men fearing God and hating covetousness,
not judging for gifts and rewards?
Should you not approve and encourage those who do well,
and to be a terror to those who do evil?
Justice is so.
And he that is of God, and bears His sword,
turns the edge of it against all sin and wickedness, injustice and oppression;
and so sets up justice and judgment in the gates,
that the poor may be delivered from him that is too mighty for him,
and that the cause of the fatherless, widow, and stranger may not fall.
Such a ruler as this has an ear open to the cries of the poor and helpless,
who has but little money, and few friends;
that a poor man may not be afraid to appear in a good cause,
against the greatest oppressor in the nation.

And should you not judge without respect to persons, or without seeking respect,
worship or honor from men; but only to advance justice, equity, and righteousness,
which is of God; that so you may be honored by the Lord.
For true humility is honor, and he that honors the Lord, him will He honor.
Such men have been honored in all ages, though they have never sought honor from men.
____

[.offset]
This and much more he wrote to the rulers; and to the preachers he wrote thus:

[quote]
____
You who say you are the teachers of the nation,
how long will it be before you look at your own ways?
Is not all manner of filthiness among you, which you should lead the people out of?
Is there not among you drunkenness, gluttony, whoredom, and sporting,
sitting down to eat and to drink, and rising up to play; swearing, lying, backbiting,
false accusing, railing, slandering, contention, strife, and envy?
Yes, are not the best of you given to pride and covetousness, which is idolatry;
"`fullness of bread, and abundance of idleness`"? Are you not hirelings,
who teach for the fleece?
Do not you contend for money from your own hearers,
and sue them at law for it--even those who cannot satisfy your
demands without sinning against the light in their own consciences,
and so sin against God?
Are you not bitter persecutors of any that come to uncover your lewdness,
fleeing to the magistrate to uphold you in your beastly ways,
and to stop the mouths of all those whom God has sent to witness against you?
And many more works of this nature are among you,
which the pure all-seeing God has showed unto His people,
and therefore it is that they come out from you,
lest they partake with you of your sins and plagues.
____

[.offset]
In the same writing the lawyers also received a stroke:

[quote]
____
And you lawyers,
should you not plead the cause of equity between man and man for equity sake,
without respect to yourselves or others, but only to truth itself?
But is not the cause of justice sure to fall if the
party has not enough money to satisfy your demands,
which are many times very unreasonable?
And you who should instruct people in the ways of truth and peace,
do you not by your wisdom teach them lies and strife?
Do you not advise your plaintiffs to declare things that are not true,
and make small offences seem very great by false glosses?
For say you, "`we may declare what we will,
and prove what we can,`" but you know beforehand
that scarce one thing in ten can be proved,
and neither are they true.
Is this the way to make up the breach, and preserve peace and truth among people?
O miserable fall from God, when that law which should preserve in peace,
is used to aggravate offences and so make differences greater!
And do you not delight to fish in troubled waters?--for
the greater the dissension among the people,
the more is your gain.
Are your purses not filled, and your estates raised up in the ruins of the people?
The law, as it is now used, is scarce serviceable for any other end,
but for the envious man, who has much money to revenge himself upon his poor neighbors,
which, it may be, never did him wrong.
____

[.offset]
Much more he wrote to the lawyers, to stir them up to do justice,
and then addressed himself to the people in general, in these words:

[quote]
____
And you people of the nation, O when will you cease to provoke the Lord by your sins?
Where is your Redeemer whom you have professed for so long in words and forms?
Do you bear witness to Him in your works?
And what has He redeemed you from?
For He says, "`Why do you call Me Lord, and do not do what I say?`"
Is He your Lord, and yet you remain servants to all manner of filthiness?
And notwithstanding you have seen His wonders in this nation,
still you exceed all that ever went before you in pride, covetousness, drunkenness,
swearing, envying, quarreling, backbiting, slandering, false accusing, self-love,
and deceit in all manner of merchandise and trading; false weights and measures,
speaking things that are not true.
How many false oaths and idle words are used in every bargain in your markets,
and in the open streets, without anyone blushing or being ashamed?
Yes, it is enough to break the hearts of any who know the pure God,
to see it and to hear it; for it is come to such a height of deceit,
that none can trust his brother.
And though lying, swearing, and forswearing abound in the nation,
will you yet profess yourselves to be the members of Jesus Christ?
Does Jesus Christ have such a body as this?
No, all that are members of him, are of one heart, and one soul.

You talk of a communion of saints,
but have ever the saints had such a communion as this--to profess a Redeemer,
but remain servants to the devil, and your own lusts?
What redemption is this you witness?
So long as sin, the partition wall between God and you, stands whole in your wills,
you will be drunk, swear, lie, and commit adultery, satisfying your lusts in all things,
and yet say, "`We are redeemed.`"
Did ever Jesus Christ redeem such a people, or dwell in such a people?
Those whom He has redeemed, He has freed from the servitude of sin,
by separating them from sin, and reconciling them to God,
from whom they have fallen through sin: for God and sin cannot dwell in one.
And to these He says, "`Be holy, for I am holy.`"
And as He is the "`Lamb of God who takes away the sins of
the world,`" now tell me how your sin is taken away,
when the kingdom of darkness does wholly rule in you,
and leads you into the works and ways of darkness?
Are you reconciled to God, and do you have fellowship with Him?
Are not you yet strangers to Him, and worship an unknown God?
"`For he that commits sin, has not seen Him, neither known Him,`"^
footnote:[1 John 3:6]
and so worship, they know not what, in forms and superstition.
____

Thus James Nayler wrote before his fall.
But, by the wiles of Satan,
he accepted the idolatrous honor of those whom he should have swiftly reproved;
and so stupefied was he in his understanding,
that he imagined that the bowing and kneeling before
him was not done on account of his person,
but for Christ.
With this false opinion he blinded himself for a time, till it pleased God to pity him,
and to give him light again,
after he had suffered such an unheard of punishment for his transgression,
as has already been related.
And because his preaching against unrighteousness in former
times had fallen so sharply on all classes of people,
undisguisedly and clearly demonstrating the Christian duty of rulers, preachers,
and lawyers, so the hatred of his enemies was the fiercer.
Indeed, several had long been angry with him,
and took occasion from his crime to revenge themselves barbarously upon him,
making him suffer a cruel punishment which was in no way proportionable to his transgression.
But this barbarous cruelty was so conspicuous,
that the soberest inhabitants did detest it,
and therefore the aforementioned petition was presented to the parliament,
desiring a discharge of part of the punishment,
to which the first subscriber was colonel Scroop, who was governor of Bristol.

But while he lay in the house of correction,
he wrote several papers to manifest his regret and repentance for his crime;
some of which have already been inserted,
but the following letter has since come to my hand.
It is a letter to his friends, written with his own hand:

[.embedded-content-document.epistle]
--

[.salutation]
Dear brethren,

My heart is broken this day for the offense that
I have occasioned God`'s truth and people,
and especially you, who in dear love followed me, seeking me in faithfulness to God,
which love I rejected.
For I was bound in that from which I could not come forth, till God`'s hand brought me,
to whose love I now confess.
I beseech you to forgive wherein I evilly repaid your love in that day.
God knows my sorrow for it (since I have been enabled to see it),
that ever I should offend the Spirit of God in any, or reject His counsel.
And now that paper you have seen lies much upon me, and I greatly fear to offend further,
or to do something amiss whereby the innocent Truth or the people of God should suffer,
or that I should disobey therein.

Unless the Lord Himself keeps you from me,
I beseech you let nothing else hinder your coming to me,
that I might have your help in the Lord.
In the mercies of Christ Jesus I beg this of you, as if it were your own case;
let me not be forgotten by you.

And I entreat you, speak to Henry Clarke, or whoever else I have most offended;
and by the power of God, and in the Spirit of Christ Jesus,
I am willing to confess my offense, that God`'s love may arise in all hearts as before,
if it be His will, who alone can remove what stands in the way.
I do not intend to cover anything; God is my witness herein.

--

He also wrote several other confessions of his faults about this time, in one of which,
among others, I find these words:

[.embedded-content-document.epistle]
--

And concerning you, the tender plants of my Father, who have suffered because of me,
or with me, in what the Lord has allowed to be done with me,
in this time of great trial and temptation: May the Almighty God of love,
who has numbered every sigh, and put every tear in His bottle,
reward it a thousand fold into your bosoms, in the day of your need,
when you shall come to be tried and tempted.
And in the meantime, may He fulfill our joy with His love, which you seek after.
The Lord knows, it was never in my heart to cause you to mourn,
whose suffering is my greatest sorrow that ever yet came upon me,
for you are innocent herein.

--

When he had finished this letter, and set his name,
he then wrote the following postscript:

[.embedded-content-document.letter]
--

I beseech you (all that can),
to receive this even as you would desire to be received of the Lord; and as for the rest,
may the Lord give me patience to suffer till He makes up the breach.

--

While he was in Bridewell, he wrote to the parliament,
who had punished him as a blasphemer,
to let them know his true opinion concerning Jesus Christ.

[.embedded-content-document.letter]
--

Christ Jesus (the Immanuel, of whose sufferings the Scriptures declare),
Him alone I confess before men.
For His sake I have denied whatever was dear to me in this world, that I might win Him,
and be found in Him, and not in myself.
I seek to serve Him alone, in spirit, soul and body, night and day,
according to the measure of grace working in me, that in me He may be glorified,
whether by life or death.

But to ascribe this name, power, and virtue, to James Nayler,
or to that which had a beginning, and must return to dust, or for that to be exalted,
or worshipped, to me is great idolatry,
and with the Spirit of Christ Jesus in me it is condemned;
which Spirit leads to lowliness, meekness, and long-suffering.

So having an opportunity given, I am willing with readiness,
in the fear of God the Father, in honor to Christ Jesus,
and in order to take off all offenses from every simple heart,
to declare this to all the world, without guile or deceit,
daily finding it to be my work to seek peace in truth with all men in that Spirit.

[.signed-section-signature]
James Nayler

--

After this,
hearing that some had wronged him concerning something
he had spoken to the committee of the parliament,
and understanding how men had perverted his words, he wrote a paper,
declaring himself further concerning his belief of Christ, and His sufferings, and death, etc.
He also denounced a paper which someone had published anonymously,
under the title of [.book-title]#James Nayler`'s Recantation#,
wherein they had much perverted his words.

[.embedded-content-document.paper]
--

And with regard +++[+++he writes]
to the printing of that paper called __James Nayler`'s Recantation__, it was not done by me,
nor with my knowledge in the least, nor do I yet at all know the man that has done it.
But I know it was done out of the Truth, and against the Truth, and for evil towards me,
whoever it was.
May the Lord God of my life, who has kept me alive in all distress, turn it for good,
and forgive the evil.
Nevertheless, what measure of truth there is in the paper, I shall acknowledge:
for thus it was, that after I was put into the hole at Bridewell,
I heard of many wild actions done by a sort of people who pretended to take my side.
These were busily stirred up in that day, and with much violence,
and many unseemly actions,
went into the meetings of the people of the Lord called Quakers,
on purpose to hinder their peaceable meetings.
And yet these would take the holy and pure name of
God and Christ frequently in their mouths,
whereby the name of the Lord was much dishonored, and His pure Spirit grieved,
for they caused much disorder in many places of the
nation to the dishonor of Christ Jesus,
for which I felt wrath from God.
But when I understood that they had any influence through me,
I used all means I could to declare against that evil spirit,
which under the name of God and Christ, was against God and Christ,
and against His Truth and people.
I wrote something about a year and a half ago in denial of these spirits,
which it seems to me the author of this paper has seen,
and to it has added the thoughts of his own heart,
and so has published his work of darkness, and people know not what to make of it.

Therefore, so far as this paper testifies against those unclean, ranting spirits,
and all the actions wherein the holy name of God has been dishonored,
and His Spirit grieved, that far I acknowledge it.
But in that it suggests that I denied the Lord Jesus Christ,
and His Truth which has called me out of the world,
or His people whom He has called into light--in these things I deny it.
For in the patience and tribulation of Christ Jesus,
and with those who have the power this day to testify
therein against all the evils of this present world,
I am one in heart and soul to the utmost of my strength,
till the coming of the Lord Jesus over all.
May the throne of meekness and truth be set on the top of all enmity and deceit.
And now, in the faith and power of Christ, I am given up to live or die,
to suffer or rejoice, as God wills, even so be it, without murmuring.

[.signed-section-signature]
James Nayler

--

This is certain,
that James Nayler came to very great sorrow and deep humiliation of mind; and therefore,
because God forgives the transgressions of the penitent, and blots them out,
and remembers them no more,
so James Nayler`'s friends could do no other than forgive his crime,
and thus take back the lost sheep into their society.
And having afterwards obtained his liberty,
he behaved himself as became a Christian--honest and blameless in conduct,
and patiently bearing the reproach of his former offenses.
