== Chapter VII

[.section-date]
1656--1657

When King Charles the Second had ascended the throne,
a man by the name of Richard Blome published a book entitled, [.book-title]#The Fanatic History#,
which was said to be published with the approbation of orthodox theologians (so called),
and dedicated by him to the king.
This book struck chiefly against the Quakers,
and was stuffed with a multitude of lying stories,
along with a greatly exaggerated account of the fall of James Nayler.
He being then alive,
took up the pen and answered the falsities contained in it that were related to himself.
And because Richard Blome, in his dedication to the king, said,
"`That if his majesty does not put forth his royal
hand of power quickly to restrain them,
they are so numerous and seducing that they will, in a little time,
diffuse their poison over the better part of his kingdom,
which none but a royal authority can stifle,`" so
Nayler responded in the following words:

[quote]
____
What has happened to your spiritual weapons?
Have not your teachers told people of the strength of Truth, and the power of godliness?
Have you lost both, and do you now run to the arm of flesh,
to get errors (as you call them) stifled, or else your hope is lost,
and your faith fails you?
Did ever any of Christ`'s ministers take off their
spiritual weapons and run to the arm of flesh,
or to a carnal weapon to stop seducers?
I say, no.
This they never did;
but with spiritual weapons they wrestled and overcame spiritual wickedness,
and with spiritual weapons they cut down heresies, blasphemies, and false worship,
cleared the churches of Christ of them, and brought them down before them in the world;
for indeed, none could resist the Spirit by which they spoke.
But the false priests and false worshippers cried
out to rulers and people (as you do now),
'`Help us, or all will be overrun:
for they that turn the world upside down are come here!`'^
footnote:[Acts 17:6; 21:28]
And then the rude multitude ran upon them, and fell upon them with rods and fists,
and assaulted the houses that entertained them, even as you do,
and so hauled them before rulers, and put them in prison, and often whipped them.
Is this your cry for help against so contemptible a people (as you count them)?
What!
Have you preached and wrestled yourselves out of all hope and faith,
so that now you must either have sudden help from the king or all is lost and overrun?
Surely then it may be said, you have been bad watchmen, and idle shepherds.

And whereas you say your book is of great importance,
and so you presume to make King Charles the patron of it,
and then ask pardon for your presumption: I say, you indeed have need of his pardon.
For the substance of your book is made up of false accusations,
gathered up out of books formerly written against us,
all of which have been disproved by clear answers, and printed several times over.
And to these old accusations you have added a few new ones, as false as the old,
and have spied out the failings of a few,
who have mourned before God that ever they should sin and
give occasion to the enemies of God so to blaspheme.
And to all of this you have included many things which were done and spoken by others,
who are not of our society, nor ever were.

And as for the charges you have against James Nayler,
through the everlasting mercy of my God, I have yet a being among the living,
and breath to answer for myself,
despite the intentions of many cruel and bloodthirsty spirits,
who pursued my soul unto death (as much as in their power lay)
in that day of my calamity when my adversary had risen above,
and wherein I was made a sign to a backsliding generation.
These rejoiced against this piece of dust,
and had little pity towards him that had fallen into their hands;
at which time God was just in giving me up for my disobedience, for a moment,
as a father to correct me.
Yet these should not have sought to aggravate things against me, as you do now;
for it was a day of deep distress, and it lay sore upon my soul,
and the merciful God saw it, who, though He was displeased with me for a time,
yet His thoughts were not to cast me off forever, but to extend mercy,
as it is at this day.
Eternal glory be to His name from my delivered soul.

But, O man, or men, whoever you are,
whose work it is to gather the failings of God`'s people in the time of their temptation,
or in the night of their trial, and aggravate them,
adding thereto the wickedness and mischievous lies of your own heart,
as you have done in your book,
and then thereby to reproach God`'s everlasting holy Truth--I say,
you are put to work by an evil spirit,
and you do but show yourselves enemies to God and His children.
For it is our great sorrow,
that any of us should have given occasion for Truth to be spoken against;
and it has been trouble of soul to all the people of God who have ever loved righteousness,
when they have thus occasioned the joy of the wicked,
or fed the man that watches for iniquity and feeds on mischief.
Yet know this, you that are of that brood, God will not cast off His people,
though He is sometimes provoked to correct them,
even before their adversaries (which is a sign to them),
yet His anger is but for a moment, and His favor shall return as streams of life.

But that which was, and is the sorrow of my heart,
is the advantage which the enemy then took against the name of Christ, His Truth,
and His despised people, in that time of my temptation,
which is what you are now pursuing with hatred and with lies,
saying that I was suspected to have a woman in bed
with me the night before I suffered at Bristol.
But as to this, and several other false things you have written in your book,
I am clear before the Lord, so that they touch me not at all.
And it is to God alone I look, in His time, to be cleared from all offenses in His sight,
who alone knows my heart in this thing, and in whose presence I can say,
that nothing is more odious and burdensome to my soul than that
any of the glory or worship which belongs to God or to Christ,
should be given to flesh and blood, either in myself or others.
And as for how it was with me in that day, there are many who talk, but few who know;
so the judgment of such I bear, desiring that none, in their judging of me,
condemn themselves in the sight of God; for His counsels are great and deep,
and the end of His work is past finding out, till He Himself reveals them.

And however myself or any others may yet be left alone to be tried in the night,
or should any of us utterly fall,
or whatever else may be acted by any man or woman that is not right in God`'s sight,
yet in vain do you gather up sin and watch for iniquity,
in order to cast it upon the light of Christ.
For it is the light of Christ that condemns sin in every enlightened mind.
And this I know by the Spirit of Jesus, which I have received, and which works in me,
that this work of yours is not His work, nor is it His seed.
You are not in Him that loves His enemies,
but the old accuser of the brethren is he that works strongly in you.
And in that light which you reproach, you are seen to be the man that makes lies,
and "`carries tales to shed blood.`"
Ezek. 22:9.
____

This and much more did James Nayler write to answer the falsehoods of which he was accused,
and to show that the fault of his crime must in no way be
attributed to the doctrine which he had professed,
as many envious persons in those times asserted; namely,
that his fall was a consequence of the doctrine that
men must take heed to the saving grace of God,
the inward anointing,
or the light wherewith every man coming into the world is enlightened from God.^
footnote:["`James Nayler was a man who had been highly
favored of God with a good degree of grace,
which was sufficient for him, had he kept to its teachings; for while he did so,
he was exemplary in godliness and great humility, was powerful in word and doctrine,
and thereby instrumental in the hand of God for turning many from darkness to light,
and from the power of Satan to the power of God.
But he, poor man, became exalted above measure, through the abundance of revelation;
and in that exaltation did depart from the grace and Holy Spirit of God,
which had been his sufficient teacher.
Then blindness came over him, and he did allow himself to be esteemed above what he ought.
Here he slipped and fell, but not irrecoverably;
for it did please God of His infinite mercy, in the day of his affliction,
to give him a sight and sense of his outgoings and fall, and also a place of repentance.
And he, with the prodigal, humbled himself for his transgression,
and besought God with true contrition of soul,
to pardon his offenses through Jesus Christ.
God, I firmly believe, forgave him, for He pardons the truly penitent.
His people received him with great joy, for that he who had gone astray from God,
was now returned to the Father`'s house,
and for that he who had separated himself from them through his iniquity, was now,
through repentance and forsaking of it, returned into the unity of the faith,
and their holy fellowship in the gospel of Christ.
And I do hereby testify,
that I do esteem it a particular mark of God`'s acknowledging His people,
in bringing back into unity with them, a man who had so dangerously fallen,
as did James Nayler.
And here let none insult, but take heed lest they also, in the hour of their temptation,
do fall away.
Nor let any boastingly say,
'`Where is your God.`' Or blasphemously suppose His
grace is not sufficient for man in temptation,
because the tempted may go from, and neglect the teaching of it.
David and Peter,
as their transgression came by their departing from this infallible guide,
the Holy Spirit,
so their recovery was only by it.`"--Joseph Wyeth in [.book-title]#A Switch for the Snake#]

After his recovery, he also wrote many papers and edifying letters.
And when the persecution in New England burned so fierce,
and two letters were sent from there to England--one under the name of John Endicot,
governor of Boston,
and the other under that of Richard Bellingham--in defense of their actions,
arguing that the persecution of the Quakers was lawful and necessary,
these were answered at length by James Nayler,
who showed how little agreement there was between their crime of
persecution and the name wherewith they had called themselves,
namely, Independents.
For by this name they would have it known that they were independent of all,
except the Spirit of Jesus Christ, on whom they pretended alone to be dependent.
And yet, nevertheless,
it now appeared clearly that it was a fleshly arm whereby they supported themselves.
He also wrote some papers to the parliament, and the rulers,
to check the vanities that were publicly committed, and to mend their faults,
to ease the oppressed, and to take care for the maintenance of liberty.

At length he died at Huntingdonshire,^
footnote:["`Ever after his fall and recovery, J. Nayler was a man of great self-denial,
and very watchful of himself.
At last, departing from the city of London,
about the latter end of the Eighth month 1660, he headed North,
intending to go home to his wife and children at Wakefield, in Yorkshire.
On the way he was seen by a Friend of Hertford,
sitting by the road in a very serious and weighty frame of mind,
who invited him to his house, but Nayler refused,
signifying that it was his mind to press forward.
He went on foot as far as Huntingdonshire where he was observed
by another Friend passing through the town in such a heavenly frame,
that he looked as if he had been redeemed from the earth, and was a stranger on it,
seeking a better country and inheritance.
But going some miles beyond Huntingdon, he was taken ill, having been, as it was said,
robbed along the way and left bound.
Whether he received any personal injury is not certainly known,
but being found in a field by a countryman toward evening,
he was taken or went to a Friend`'s house at Holm, not far from King`'s Rippon,
where Thomas Parnel, a doctor of medicine, came to visit him.
Being asked if any friends at London should be sent for to come and see him;
he said '`No,`' but expressed his care and love to them.
Being shifted on the bed he said, '`You have refreshed my body,
may the Lord refresh your souls.`' Not long after he departed this life,
in peace with the Lord, about the Ninth month, 1660, and the 44th year of his age,
and was buried in Thomas Parnel`'s burying ground
at King`'s Rippon aforesaid.`"--John Whiting`'s account.]
in the latter end of the year 1660, about the 44th year of his age.
About two hours before his death,
he spoke the following words in the presence of several witnesses:

[.embedded-content-document.address]
--

There is a Spirit which I feel, that delights to do no evil, nor to revenge any wrong,
but delights to endure all things, in hope to enjoy its own in the end.
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptations.
As it bears no evil in itself, so it conceives none in thought to any other.
If it is betrayed, it bears it;
for its ground and spring is the mercies and forgiveness of God.
Its crown is meekness, its life is everlasting love unfeigned.
It takes its kingdom with entreaty, and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regard it or acknowledge its life.
It is conceived in sorrow, and brought forth without any to pity it;
nor does it murmur at grief and oppression.
It never rejoices but through sufferings, for with the world`'s joy it is murdered.
I found it alone, being forsaken.
I have fellowship therein with those who lived in
dens and in desolate places of the earth,
who through death obtained this resurrection, and eternal holy life.

--

This was J. Nayler`'s last testimony, or dying words; and thus he gave proof that,
though he had erred, yet with great confidence he hoped for a happy resurrection.^
footnote:[There is a passage in the book called, The Complete History of England, vol.
iii. page 201, which says that James Nayler died with no fruits,
nor so much as any signs of repentance.
How the author of this book came by such information, we cannot tell,
but that it is a manifest mistake we doubt not but that
the impartial reader is by this time abundantly convinced.]
So I conclude the story of J. Nayler, and leaving him now, time calls me to New England.

It was in the month called July, of this present year,
when Mary Fisher and Ann Austin arrived in the road before Boston,
before ever a law was made there against the Quakers.
Nevertheless, they were very ill-treated; for before they came ashore,
the deputy-governor,
Richard Bellingham (the governor himself being out of town) sent officers aboard,
who searched their trunks and chests,
and took away the books they found there (which were
about one hundred) and carried them ashore,
after having commanded the women to be kept prisoners aboard.
The said books were then, by an order of the council,
burnt in the marketplace by the hangman.
Afterwards the deputy-governor had the women brought on shore,
and committed them by a court order to prison as Quakers, upon this proof only:
that one of them speaking to him had said "`thou,`" instead
of "`you;`" whereupon he said he needed no more evidence,
for now he saw they were Quakers.
They were then shut up as close prisoners,
and a command was given that none should come to them without leave;
a fine of five pounds being laid upon any that should otherwise come to,
or speak with them, even at the window.
Their pens, ink, and paper were taken from them,
and they were not allowed to have any candle-light in the night.
What is more, they were stripped naked, under pretense to know whether they were witches,
though in searching, no token was found upon them but of innocence;
and in this search they were so barbarously misused
that modesty forbids me to mention it.
And that none might have communication with them,
a board was nailed up before the window of the jail.

Seeing they were not provided with food, nor was liberty granted to send them provisions,
Nicholas Upshal, one who had long lived in Boston and was a member of the church there,
was so concerned about it that he purchased their food from
the jailer at the rate of five shillings a week,
lest they should have starved.
And after having been about five weeks prisoners, William Chichester,
master of a sailing vessel,
was bound for one hundred pounds to carry them back to England,
and to not permit any to speak with them.
After they were put on board, and the jailer kept their beds,
which had been brought out of the ship, and their Bible for his fees.

Such was the entertainment that the Quakers first met with at Boston,
and that from a people who claimed that, for conscience-sake,
they had chosen the wilderness of America before the well-cultivated land of old England.
Afterwards, however, when they had taken away the lives of those called Quakers,
in order to excuse their cruel actions,
they did not hesitate to say that at first they had
used no punishment against the Quakers.

Scarce a month after the arrival of the aforesaid women at Boston,
there came also Christopher Holder, Thomas Thirstone, William Brend, John Copeland,
Mary Prince, Sarah Gibbons, Mary Whitehead, and Dorothy Waugh;
they were locked up in the same manner as the former, and after about eleven weeks stay,
were sent back.
Robert Locke, a master of a ship,
was compelled to carry these eight persons back on his own charge,
and to land them no where but in England,
having been imprisoned till he committed so to do.

The governor, John Endicot, whose blood-thirstiness will appear in what follows,
having now come home, bid them "`Take heed you break not our ecclesiastical laws,
for then you are sure to hang by a halter.`"
And when they desired a copy of those laws it was denied them;
which made some of the people say, "`How shall they know then when they transgress?`"
But Endicot remained stiff, having said before when he was at Salem,
hearing how Ann Austin and Mary Fisher had been dealt with at Boston,
"`If I had been there, I would have had them well-whipped.`"
Then a law was made,
prohibiting all masters of ships from bringing any Quakers into that jurisdiction,
and also prohibiting the Quakers themselves from
coming in on penalty of the house of correction.
When this law was published, Nicholas Upshal, already mentioned,
could not forbear to show the persecutors the unreasonableness of their proceedings,
warning them to take heed that they were not found fighting against God,
and so draw down a judgment upon the land.
But this was taken so ill, that though he was a member of their church,
and of good repute, as a man of unblameable conduct,
yet he was fined twenty-three pounds, and imprisoned also for not coming to church,
and next they banished him out of their jurisdiction.
This fine was exacted so severely that Endicot said,
"`I will not lower his fine one groat.`"
And though a weakly old man,
yet they allowed him but the space of one month for his removal,
so that he was forced to depart in the winter.

Coming at length to Rhode Island, he met an Indian prince,
who having understood how he had been dealt with, behaved himself very kindly,
and told him, if he would live with him, he would make him a warm house.
And further said,
"`What a God have the English?--who deal so with one another about their God!`"
But this was but the beginning of the New England persecution, which in time grew so hot,
that some of the Quakers were put to death on the gallows,
as will be related in its due time.

Now I return to Old England, where we left G. Fox at Exeter,
from which he went to Bristol.
Here he had a great meeting in an orchard;
and since some thousands of people had come there, and many were very eager to see him,
he stepped upon a great stone that stood there, and having put off his hat,
stood a pretty while silent, to let people look at him.
A Baptist was there named Paul Gwyn, who began to find fault with G. Fox`'s hair,
and at last said to the people, "`You wise men of Bristol, I wonder at you,
that you will stand here and hear a man speak, and affirm things which he cannot prove.`"
Hereupon G. Fox asked the people whether they had ever heard him speak before,
or had ever seen him before?
And he bid them take notice what kind of man this Paul Gwyn was,
who so impudently said that he spoke and affirmed that which he could not prove;
and yet neither Gwyn nor they had ever heard him or seen him before;
and that therefore it was a lying, envious, and malicious spirit that spoke in him.
Then G. Fox charging Gwyn to be silent, began to preach, which lasted some hours,
without being disturbed.

After this meeting, G. Fox departed from Bristol, and passing through Wiltshire,
Marlborough, and other places, he returned to London.
When he came near Hyde Park, he saw the protector coming in his coach;
whereupon he rode up to the coach side,
and some of his lifeguard would have put him away; but the protector forbade them.
Then riding by his coach side,
he spoke to him about the sufferings of his friends in the nation,
and showed him how contrary this persecution was to Christ and his apostles,
and to Christianity.
And when they were come to the gate of St. James`'s Park, G. Fox left Cromwell,
who at parting desired him to come to his house.
The next day Mary Sanders, afterwards Stout, one of Cromwell`'s wife`'s maids,
came to G. Fox`'s lodging, and told him that her master coming home,
said he would tell her some good news; and when she asked him what it was,
he told her G. Fox had come to town; to which she replied, that was good news indeed.
Not long after, G. Fox and Edward Pyot went to Whitehall,
and there spoke to Cromwell concerning the sufferings of their friends,
and directed him to the light of Christ who had "`enlightened
every man that comes into the world.`"
To which Cromwell said, "`This is a natural light;`" but they showed him the contrary,
saying that it was divine and spiritual, proceeding from Christ,
the spiritual and heavenly man.
Moreover G. Fox bid the protector lay down his crown at the feet of Jesus.
And as he was standing by the table, Cromwell came and sat upon the table`'s side by him,
and said he would be only as high as G. Fox was.
But though he continued to speak in a light manner,
yet afterward he became so serious that when he came to his wife and other company,
he said that he never parted so from the Quakers before.

Having visited the meetings of his friends in and about London,
G+++.+++ Fox departed from there and travelled almost through all England,
not without many occurrences, which for brevity`'s sake I pass by.
At length he returned to London again, this year being now come to an end.

In the parliament which Cromwell had called,
a law was made whereby Charles Stuart`'s title of king was rejected,
and the year 1657 having come, subsidies were granted to Cromwell,
and there was a secret contrivance underway to make him king, of which,
though he expressed his dislike to it, yet he seemed not altogether averse to it;
for speaking once with general Fleetwood and colonel Desborough,
he began to jest with them about the word "`monarch,`" saying,
it was but a feather in a man`'s cap,
and therefore he wondered that men would not please the children,
and permit them to enjoy their rattle.
But these men not obscurely signified to him that this business did displease them;
and told him, that those who put him upon it were not true enemies to Charles Stuart;
and that if he accepted this title, he would infallibly draw ruin upon himself.
Now, though he would not openly oppose them, yet he did not hesitate to tell them,
they were a couple of fastidious fellows, and so left them.
It is related also, that major-general Lambert told Cromwell,
that if he accepted the crown, he could not assure the army to him.

This design thus miscarrying,
and Cromwell having now seen that the matter would not go so smoothly,
he refused the title of king;
and the parliament confirming him in his title of protector,
it was agreed that the parliament henceforth should consist of a lower house,
and another house; and that the protector should name a successor in the government.
Now that he was solemnly established in his authority,
a throne for that purpose was erected in Westminster Hall,
and he being clothed in a purple robe lined with ermine fur,
and the scepter and sword being presented him, he took the oath to rule faithfully.
Cromwell having called a new parliament, it consisted of two houses, namely,
a house of commons, and another house as they called it.
And many formerly excluded members having taken a place again in the house of commons,
it was believed that more than a hundred of the members were enemies to Cromwell;
and the authority of the upper house began to be called in question by some,
because it was filled up with many of his puppets, some of them of low rank.
And this matter was so carried on in the house of commons,
that Cromwell soon dissolved the parliament,
and also made major-general Lambert surrender his commission.

Edward Burrough, who often wrote to Cromwell,
having heard of the design of making him king, wrote a letter to him, wherein I find,
that after having told the protector that he had had many warnings from the Lord,
he thus speaks to him:

[.embedded-content-document.letter]
--

I as one that has obtained mercy from the Lord, and unto whom His word is committed,
being moved of Him, do hereby in His presence yet once more warn you,
that you fear before Him, and diligently hearken to Him,
and seek Him with all your heart,
so that you may know His will and counsel concerning you, and may do it,
and find favor in His sight and live.
Now is the day that His hand is stretched forth unto you to make you a blessing,
or to leave you a curse forever; and the days of your visitation are near an end,
when God will no more call unto you, nor hear you,
when in the day of your trouble you call to Him.
And if you reject the counsel of the Lord, and follow the desires of your own heart,
and the wills of men,
and will not have the light of the world--Christ Jesus--to rule you alone,
and to teach you (who condemns all evil) then shall evil surely fall upon you,
if you love not the light in you which condemns it; and so the judgments of God,
and the day of His last visitation with vengeance, you will not escape.

Therefore consider and mark my words, and let this counsel be acceptable unto you.
Let it move you to meekness, to humbleness, and to fear before the Lord;
assuredly knowing that it is He that changes times and things,
and who brings down and sets up whomever He will, and how He raised you from a low state,
and set you over all your enemies.
And in that day when you were raised up, when the fear of the Lord was before your face,
and your heart was towards Him, and you were but little in your own eyes,
then it was well with you, and the Lord blessed you.
And it was not once thought concerning you at that time,
that the hands of the ungodly would have been strengthened
against the righteous under you,
or that such grievous and cruel burdens and oppressions
would ever have been laid upon the just,
and acted against them in your name, and under your dominion,
as has come to pass in these three years.
And this--your allowing of such things--is your transgression,
and you have not requited the Lord well for His goodness unto you,
nor fulfilled His will in allowing that to be done under you, and in your name,
which the Lord raised you up against, and to break down,
had you been faithful to the end.

Again, consider, and let it move upon your heart not to exalt yourself,
nor to be high-minded, but to fear continually, knowing that you stand not by yourself,
but by Another,
and that He is able to abase you and give you into
the will of your enemies whenever He will.
Consider how the Lord has preserved you sometimes wonderfully, and does unto this day,
from the murderous plots and crafty policy of evil men,
who seek your evil and would rejoice at your fall,
and in the desolation of your family and country.
Have they not, and do they not still lay snares for your feet,
that you may be cut off from among men, and die unhappily, and be accounted accursed?
And yet to this day He has preserved you, and been near to keep you,
though you have hardly known it.
The Lord`'s end is love to you in all these things,
and yet a little longer He will try you, that you may give Him the glory.
O that your heart were opened to see His hand, that you might live unto Him,
and die in Him, in peace.
And beware lest you slight His love, and hardness of heart possess you;
and so you will be shut up in darkness and given over to the desires of your enemies,
and left to the counsels of treacherous men, who may seek to exalt you by flattery,
that they may the better cast you down, and destroy you.

But now, O consider, and let it enter into your heart,
that despite all this you have not answered the Lord, but have been lacking towards Him,
and have chosen your own way and glory, rather than His,
and not fulfilled His purpose in raising you up.
For the bonds of cruelty are not loosed by you, and the oppressed are not set free;
neither is oppression taken off from the back of the poor, nor are the laws regulated,
or liberty of conscience allowed.
Rather these dominions are filled with cruel oppressions,
and the poor groan everywhere under the heavy hand of injustice.
The needy are trodden down under foot, and the oppressed cry for deliverance,
and are ready to faint from longing after true justice and judgment.
The proud exalt themselves against the poor,
and the high-minded and rebellious despise the meek of the earth,
and those who have departed from iniquity have become a prey to oppressors.
Many are unjustly and woefully sufferers,
because they cannot swear on this or that occasion,
though in all cases they speak the truth, and do obey Christ`'s commands.
Many of these are trodden upon by unjust fines charged upon them,
and this is by the corruptness of some who bear rule under you,
who do not rule for God as they ought.
Some suffer long and tedious imprisonments, and others cruel stripes and abuses,
and danger of life many times from wicked men, solely for reproving sin,
and crying against the abominations of the times
(which the Scriptures also testify against),
in streets or other places.
Some have been sent to prison after being taken on the highway,
with no evil charged against them.
Others are taken out of peaceable meetings, and whipped and sent to prison,
without the transgression of any law, just or unjust.
Some in prison have suffered superabundantly from
the hands of the cruel jailers and their servants,
by beatings and threatenings, and putting irons on them,
and not permitting any of their friends to visit them with necessities;
and others have died in the prisons, whose lives were not dear to them,
whose blood will be reckoned on account against you one day.

Some have suffered hard cruelties, because they could not respect persons,
and bow with their hat or knee;
and from these cruelties you can not be altogether excused in the sight of God,
for they are brought forth in your name, and under your power.
Consider, friend, and be awakened to true judgment, and let the Lord search your heart;
and lay these things to mind, that you may be an instrument to remove every burden,
and may at last fulfill the will of God.
O be awakened, be awakened, and seek the Lord`'s glory, and not your own.
And if men would give you honors and high titles, and princely thrones, take them not;
for that which will exalt and honor you in the world, will betray you to the world,
and cast you down in the sight of the world.
And this is God`'s word to you: What?
Shall the whole nation be perjured men, and you be the cause of it?
And will you transgress by building again that which you have destroyed?
Give heed unto my words, and understand my speech; be not exalted by man,
lest man betray you.
Deal favorably, and relieve the oppressed.
Do not boast; for though the Lord has used you in His hand;
He can cast you as a rod out of His hand, into the fire, if He so desires.
If you will honor Him, He will honor you; otherwise he can, yes, and will confound you,
and make you as weak as water before Him.

His love through my heart breathes unto you.
He desires your happiness, if you do not willfully contemn it,
by exalting yourself and seeking your own glory,
and hardening your heart against the cry of the poor.
This I was moved with a heart of pity to lay before you, who am your friend,
not in flattery, but in an upright heart, who wishes you well in the Lord.

[.signed-section-signature]
Edward Burrough.

--

That which Edward Burrough mentions in the forepart of this letter,
of the grievous burdens and oppressions which were laid upon the just,
seems chiefly to regard the tithes which the priests extorted from the Quakers,
so that many thereby were reduced to poverty.
The heinousness of this was not unknown to Cromwell;
for when he was about to go into battle against his enemies, near Dunbar in Scotland,
he said in his prayer to God,
that if the Lord would be pleased to deliver him at that time,
he would remove the great oppression of tithes.
But this promise he never performed,
but allowed himself to be swayed by the flatteries of his teachers.
It was therefore not without great cause that Edward
Burrough laid this grievous oppression before him.
A copy of the said letter (of which but a part is inserted here,
to avoid prolixity) was given into the hands of Oliver
Cromwell in the third month of this year.
In the next month Edward Burrough spoke with him about it,
and Cromwell told him in effect that all persecution and cruelty was against his mind,
and said he was not guilty of those persecutions acted unjustly upon Burrough`'s friends.
This made Edward Burrough write again to him, and bid him:

[.embedded-content-document.letter]
--

Consider what the cause is, why what you say you desire not to be done, is yet done.
Is it not so that you may please men?--thus manifesting you are more willing
to give pleasure to the false teachers and wicked men of this nation,
than to acknowledge the people of God by relieving them,
and easing them of their cruel burdens and oppressions, laid upon them by unjust men?
For a word from your mouth,
or a show of your countenance in dislike of these cruel and unjust persecutions,
would bind the hands of many blood-thirsty men.
Therefore consider:
you cannot be clear in the sight of the Lord God
from these evils which are acted under your power,
and in your name.
For you know of some in this city, and elsewhere, whom all acknowledge to be just men,
who suffer imprisonment and the loss of their liberties
because for conscience-sake they cannot swear.
And many others in this nation are suffering cruel treatment upon similar grounds:
even for well-doing, and not for evil.
Such oppression might be removed, and their unjust sufferings relieved by you,
by a mere word from your mouth or pen.

And concerning the light of Christ, at which you stumble,
by which every man that comes into the world is enlightened, in short, I say this:
this light is given to you of God, and you must acknowledge it to be your only teacher,
to receive by it from the Father, and to be guided by it in all things,
if ever you will inherit God`'s kingdom.

The kingdom of Christ is being set up by His own power,
and all must bow and become subject thereto.
He needs none of your policy, nor the strength of your arm to advance it;
yet He does not desire you to prove yourself an open enemy thereof, by doing,
or allowing to be done,
cruelty and injustice against those whom the Lord is redeeming out of this world,
into subjection unto His kingdom; lest you be one of those who will not enter yourself,
nor permit others to enter.
Wherefore arise as out of sleep, and slumber not in this world`'s glory and honor.
Be not overcome by the pleasures of this world, nor the flattering titles of men.
Wink not at the cruelty and oppression acted by some who take shelter under you,
and make your name a cloak for mischief against the upright.

Consider, I say, consider, and be changed in your mind and heart;
lest having forgotten God, and His many deliverances,
you are shut up and numbered for destruction.
I desire the Lord may give you a more perfect understanding of His ways and judgments,
and that you may strive for the crown immortal by meekness and righteousness,
through relieving the oppressed, and showing mercy to the poor,
and removing every burden which lies upon the innocent.
This is the desire of him who is your friend,
and would not have you crowned with dishonor,
through allowing the people of God to be oppressed in your name,
which will surely be your overthrow if you remove it not,
by turning and easing the oppressed.

[.signed-section-signature]
E+++.+++ Burrough.

--

This letter was delivered to Oliver Cromwell, in the fourth month,
and in the month following Edward Burrough wrote to him again,
saying that the good name "`Protector`" was abused and subverted
by the great oppression acted in his name;
and that instead of protection, great injustice was acted under it, and covered with it.
Besides that, several justices of the peace, and other officers in trust under him,
when they had shown approval of the people called Quakers,
had been cast out of their places;
though they had not denied to serve Cromwell and the commonwealth,
nor had unfaithfulness to their office been proved against them.

In September, Edward Burrough wrote another letter to Cromwell,
wherein he signified to him that he had many enemies,
some of which endeavored to destroy him by any means,
without regarding the danger that might be in the attempt.
And that, because he continued oppressing through tyranny, or allowing it,
perhaps the Lord might raise up the wicked to be a plague to wickedness,
and permit the oppressors to overthrow oppressions.
He told him that there were others (namely,
the Fifth Monarchy men) who secretly murmured against him, and envied him,
not being friends to his government,
claiming to have been cast out and rejected without just cause.
"`And as to us,`" said he, "`how can we mention you in our prayers to God,
except it be to be delivered from you, who are daily and unjustly sufferers by you,
or because of you?
Or how can we be friends to that government under
which we daily suffer such hard and cruel things,
such as the loss of our liberty and estates, and are in danger of life also?`"

It was about the beginning of this year,
that Christopher Birkhead came to Zealand,
having been before at Rochelle, in France.
Here, having spoken and written against the popish religion,
he was imprisoned and examined by the bishop; and some would have had him burned,
but the criminal judge absolved him.
It was in the latter end of the month called February, when he came to Middleburgh,
in Zealand; and going to the English congregation there, after the preacher,
William Spanke, had preached about three quarters of an hour, he said, "`Friends,
the apostle says, that we may all prophesy, one by one;
that two or three prophets may speak, and the others judge;
and if anything be revealed to another that sits by, let the first hold his peace.`"^
footnote:[1 Corinthians 14:29-30]
This speaking caused a great stir in the congregation, and the more,
because he stood in the place where the women were accustomed to sit.
So he was apprehended by order of the magistrates,
and examined in the presence of some of the public preachers.
When he was asked what his name was?
He answered, that his name, according to the flesh, was Christopher Birkhead.
Then it was asked him, whether he had yet another name?
And his answer was, "`Yes, written in the Lamb`'s book of life.`"
Being inquired what that name was, he made answer, "`None knows it but he that has it.`"
To which was said, "`Why, if you have it, tell it to us.`"
"`No,`" replied he, "`read it, if you have seen the book of the Lamb opened;
it is forbidden me to tell it.`"
Then the English teacher, Spanke, asked whether he had seen the book of the Lamb opened?
And he answered, "`Yes.`"
The next question was, whether he had opened it?
"`No,`" said Birkhead, "`it was the Lamb that did it.`"
Then Spanke asked, whether his name in the book of the Lamb was not Jesus.
"`No,`" said Birkhead, "`that is the name of the Lamb.`"
Spanke put other questions to him to ensnare him,
and after being examined by the magistrates concerning the place of his abode,
his calling or trade, etc.
Spanke was asked what he had to say against him,
who then related what had happened in the congregation.
Several questions were asked of Birkhead concerning this,
but since he did not understand Dutch, and knew the French tongue but imperfectly,
he complained that he could not fully answer for himself as he wished.
He was asked also, whether anybody else came along with him?
And he was charged to speak the truth.
To which he said, that God did not permit him to lie.
One of the preachers then said that all men were liars.
To this Birkhead replied, that though all men were liars,
yet he knew a deliverance from lying.
And it being strongly asserted, that all men were liars,
Birkhead took occasion from there to ask Spanke whether he was a liar?
Who, without hesitation, answering, "`Yes,`" Birkhead bluntly told him,
"`Then you are of your father the devil.`"
Now the matter of James Nayler having caused strange reports of the Quakers everywhere,
and Birkhead, for lack of the language,
not being able to answer every objection so plainly, his offense, without question,
was aggravated the more;
and the conclusion was that he was sentenced to be confined in the house of correction.
But after some time he was released, at the intercession of the Heer Newport,
ambassador of the States General in England.

In this year it was, I think, that one George Baily coming into France,
was taken into custody, and died in prison there;
he having zealously testified against popery,
and spoken boldly against worshipping of images.

William Ames returning this year to Amsterdam,
and one named Humble Thatcher (whom I could never learn to have
been truly in communion with the Quakers) coming with him,
it caused some suspicion.
For Ames, who formerly had been in military employment, was an extraordinary bold man;
and about this time it seems a paper was put on the door of the English meetinghouse,
though Ames declared he knew nothing of it, or who was the author.
About this time also,
the strange business of James Nayler was being noised
abroad by a book that was published in print at Amsterdam,
along with some other pamphlets that were filled
with several untruths and abominable lies;
so it was not to be wondered at that the magistrates, fearing some mischief,
sent for Ames and Thatcher to appear before them,
and commanded them to depart from the town within twenty four hours.
However, being persuaded of their own innocency, they did not obey this command.
Appearing again before the magistrates the next day, and not putting off their hats,
it seems they were looked upon as those who did not acknowledge magistrates
(for this the Quakers stood charged with in public print,
and were compared to the tumultuous crew of Fifth Monarchy men,
or the Anabaptists in Munster in the foregoing age^
footnote:[The Anabaptist Rebellion in Munster,
1534-35]). So they were kept in custody for some days,
and then at night were led through the Regulars gate, and so banished out of the town.
But William Ames judging that he had committed no evil,
came again the next day into the city, and passed by the great market-place,
called the dam.
It is reported,
that some of the magistrates seeing him out of the windows of the town-house,
walking along the street, said, "`Lo, there`'s the Quaker;
if we had a mind now to make martyrs, here would be an opportunity for it.`"
But it seems not without reason, that it was looked upon to be most safe to wink at this;
for though strange reports were spread up and down about the Quakers,
yet there was no proof of their evil carriage here.
Meanwhile Ames stayed some time in town,
and the doctrine he preached found a little entrance, even among some of the collegians.

It was about this time, that my parents, Jacob Williamson Sewel,
of Utrecht (free citizen and Surgeon at Amsterdam), and his wife, Judith Zinspenning,
born in this town, both members of the Flemish Baptists church there,
were convinced of the Truth preached by William Ames;
she having before had immediate openings, that if ever she would become a child of God,
she must give heed to this light which reproved for sin.
They, with two or three more, were the first orthodox Quakers in Amsterdam;
orthodox I say,
because I very well remember what a strange and odd sort of people
about that time did flock to the Quakers in this country.
But these whimsical people, not being sincere in heart,
but more inclined to novelties than to true godliness,
perceived in time that they were not regarded by them.
They were also contradicted by Ames and others, and so that at length,
after many acts of exorbitance, they left the Quakers.

In the forepart of this year, William Caton came also to Amsterdam.
Before he left England, he had had a meeting at the east side of Sussex,
on the day called Shrove Tuesday, where there had never been any of his friends before.
But the people there, being on that day more rude than ordinary,
came up to the house with a drum in such a desperate manner,
it seemed as if they would have pulled the house down.
Caton stepping out, asked what they wanted; they answered,
"`Quakers;`" at which he told them he was one.
He then spoke so plainly to them, and with so much power, that fear fell upon them,
and they withdrew with shame and confusion.

Not long after he went to London, and from there to Holland;
and having safely arrived at Rotterdam, he proceeded to Amsterdam;
where he came in due time to stop the unruliness of some self-willed spirits, among whom,
one Anne Garghil, an English woman, was not the least.
Indeed her rudeness grew in time to such a degree that she would
not permit William Ames to preach peaceably in the meeting,
but laid violent hands on him; so that at length, to be rid of her,
he bade an English seaman that was present to take her away, which was done accordingly.
How haughty this woman was, and continued to be, I well remember still.
William Caton procured also some books to be printed at Amsterdam,
to prevent evil and malicious reports concerning the Quakers;
and he went with W. Ames to Zutphen in Gelderland;
where meeting with nothing but opposition, he returned to Amsterdam,
and from there by Leyden and the Hague, to Rotterdam;
from which place he went to Zealand,
where he wrote the book called [.book-title]#The Moderate Enquirer Resolved#, both in Latin and English,
which was afterwards translated inadequately into Dutch.
After some stay, Caton returned again to England, and came to London,
where the society of his friends was in a thriving condition,
and many were added to the church.

In this city we left G. Fox.
Here he wrote several papers for the opening of the understandings
of people and for the edification of his friends.
From there he travelled into Kent, Sussex, and Surry; and coming to Basingstoke,
though the people were rude there, yet he had a quiet meeting in the place;
however in the inn he had some trouble with the innkeeper, who was a drunkard.
Afterwards he came to Portsmouth, Exeter, Bristol, and into Wales,
where many came to hear him.
At Brecknock he was accompanied by Thomas Holmes,
who was the first of the Quakers to preach the doctrine of the inward light in Wales;
and by John-ap-John,
who three years before had been sent by a priest out of Wales into the North,
to inquire what kind of people the Quakers were.
There he had a great meeting in the steeple-house yard, where there was a priest,
and one Walter Jenkin who had been a justice, and another justice.
Here he preached so effectually, that many were convinced; and after the meeting,
he went with Jenkin to the other justice`'s house, who said to him,
"`You have this day given great satisfaction to the people,
and answered all the objections that were in their minds.`"
At Leominster he had a large meeting, where priest Tombs made some opposition,
by saying that the light G. Fox spoke of was but a natural light;
but G. Fox asserted the contrary, saying,
he had spoken of no other light than that which John bore
witness to--"`The Word which was in the beginning with God,
and which Word was God;
and that was the true light which enlightens every man that comes into the world.`"

G+++.+++ Fox coming from this place to Tenby, as he rode in the street,
a justice of the peace came out and desired him to alight and to stay at his house,
which he did.
On the First-day of the week he had a meeting there, where the mayor and his wife,
and several others of the chief of the town came.
John-ap-John, who was then with G. Fox, left the meeting and went to the steeple-house,
and was cast by the governor into prison.
The next morning the governor sent one of his officers to the justice`'s house,
to fetch G. Fox.
This grieved the mayor and the justice, and so they went up to the governor,
and a short time after G. Fox went up also with the officer, and upon coming in,
said "`Peace be unto this house.`"
And before the governor could examine him,
he asked why he had cast his friend into prison?
The governor answered, "`For standing with his hat on in the church.`"
"`Why,`" resumed G. Fox, "`did not the priest have two caps on his head,
a black one and a white one?`"
"`These are frivolous things,`" said the governor.
"`Why then,`" said G. Fox,
"`do you cast my friend into prison for such frivolous things?`"
Then the governor asked him whether he believed in election and reprobation?
"`Yes,`" said he, "`and you are in the reprobation.`"
This so incensed the governor that he told G. Fox
he would send him to prison until he proved it.
G+++.+++ Fox, not at all at a loss for words, said, "`I will prove it quickly,
if you will but confess to the truth.`"
He then asked him whether wrath, fury, rage,
and persecution were not marks of reprobation?
For he that was born of the flesh, persecuted him that was born of the Spirit;
and Christ and His apostles never persecuted nor imprisoned any.
This speech of his so struck the governor,
that he fairly confessed that he had too much wrath, haste, and passion in him.
This made G. Fox say, "`Esau, the first birth, is raised up in you, and not Jacob,
the second birth.`"
By this the man was so reached, that he confessed to Truth, and then,
inviting G. Fox to dinner with him, he set his friend at liberty.
It was with great satisfaction that G. Fox departed the town;
and in several other places of Wales he had some unusual occurrences;
and though the people were rude, yet some were convinced.

At length he came to Lancaster, where, at the inn, he met with colonel West,
who was very glad to see him.
Next he came to Swarthmore, where he wrote some epistles and other papers.
After having stayed there some days, he went to some other places in the North,
and then to Scotland.
Here, traveling from town to town, he met with great opposition from some priests.
For in an assembly, they had drawn up several articles, or curses,
to be read in their steeple-houses, the first of which was:
"`Cursed is he that says every man has a light within
him sufficient to lead him to salvation;
and let all the people say.
'`Amen.`'`" An independent pastor preaching one day against the Quakers, and the light,
and calling the light natural, cursed it, and so fell down as dead in his pulpit.
The people carrying him out, and pouring strong waters into him,
brought him to life again; but he was listless, and, as one of his hearers said,
he never recovered his senses.

In October G. Fox came to Edinburgh, where he was summoned to appear before the council,
who, though somewhat civil, yet told him,
he must depart the nation of Scotland within a week from that day;
against which order he not only spoke but also wrote.
While G. Fox was in Scotland, his friends there were brought to a great strait; for,
having been excommunicated by the Presbyterian teachers,
a charge was given that none should buy or sell, nor even eat nor drink with them.
Hence it came to pass, that some of those called Quakers,
having bought bread or other provisions from their neighbors,
found that many who were frightened with the curses of their priests,
did run and fetch it from them again.
But colonel Ashton, a justice of peace, put a stop to these proceedings,
and being afterwards convinced of the Truth, had a meeting settled at his house,
and declared the Truth, and lived and died in it.

G+++.+++ Fox now travelled over almost all of Scotland,
and had in some places good opportunities to declare the gospel,
being often heard with satisfaction by the English soldiers;
but the Scotch generally gave little heed.
He went also among the Highlanders, who were a mischievous people.
Returning at length to Leith,
the innkeeper told him that the council had granted warrants to apprehend him,
because he had not gone out of their nation after the seven days had expired.
Some others told him the same, to whom he said,
"`What do you tell me of their warrants against me?
If there were a cart load of them I would not heed them;
for the Lord`'s power is over them all.`"
From Leith he went to Edinburgh again, and came to the inn where he had lodged before,
and no man offered to meddle with him.
Alexander Parker and Robert Widders also being there,
he resolved to go with Parker to Johnston,
out of which town he had some time before been conducted by soldiers.
He came into Johnston just as they were drawing up the bridges,
and the officers and soldiers never questioned him.

And coming to captain Davenport`'s house, out from which he had been hauled before,
he found there many officers, who lifting up their hands,
wondered that he came there again; but he told them,
the Lord God has sent him among them again.
Then the Baptists sent him a letter by way of challenge,
that they would discourse with him again the next day.
And he sent them word, that he would meet them at a certain house,
about half a mile out of the town, at such an hour.
For he thought if he should stay in town to speak with them, they might,
under pretense of discoursing with him,
have stirred up people to carry him out of the town again, as they had done before.
At the time appointed he went to the place,
captain Davenport and his son accompanying him; and there he stayed some hours,
but none of the Baptists came, whereby their intention was sufficiently discovered.
Being thus disappointed, he went back again to Edinburgh, and passed through the town,
as it were, into the cannon`'s mouth.

The next day, being the first day of the week, he went to the meeting in the city,
and many officers and soldiers came to it, and all was quiet.
The following day he went to Dunbar,
where walking with a friend or two in the steeple-house yard,
and meeting with one of the chief men of the town there,
he requested one of his friends to tell him that about the ninth hour
the next morning there was to be a meeting there of the people of God,
called Quakers, of which they desired him to give notice to the people of the town.
To this the man said, they were to have a lecture there at the ninth hour;
but that a meeting might be kept there at the eighth hour, if they so desired.
G+++.+++ Fox thinking this not inconvenient, he requested him to give notice of it.
Accordingly in the morning many came, both poor and rich;
and a captain of horsemen being quartered in the town, came there also with his troopers.
To this company G. Fox preached,
and after some time the priest came and went into the steeple-house;
but G. Fox and his friend being in the steeple-house yard,
most of the people stayed with them; so that the priest, having but few hearers,
made short work, and coming out, he stood a while and heard G. Fox, and then went away.
This was the last meeting he had in Scotland,
and he understood afterwards that his labor had not been in vain,
but that the number of believers increased.
Now he departed from Dunbar and came to Berwick in Northumberland,
and from there to Newcastle, where we will leave him awhile,
and return again to New England.

We have seen before, that a law was made there,
to prevent the Quakers from coming into Massachusetts Bay Colony.
The first ones I find that came after that, were Anne Burden, a widow,
whose business was to gather up some debts in those parts that were due to her;
and Mary Dyer from Rhode Island, who, before her coming,
knew nothing of what had been done there concerning the Quakers.
These two were both imprisoned; and upon William Dyer (Mary`'s husband) hearing of it,
he came from Rhode Island, and did not get her released without a great deal of pains;
having to become bound under great penalty not to lodge her in any town in that colony,
nor permit any to speak with her.^
footnote:[This is an evident token that William Dyer
was not then a member of the society of Quakers,
so called, for otherwise he would not have entered into such a bond;
nor would he have escaped being locked up in prison himself.]

As for Anne Burden, she was kept in prison, though sick, about a quarter of a year.
While she was under this restraint,
some tender-hearted people had collected of her debts
to the value of about thirty pounds in goods;
and when she at length was to be sent away,
she desired that she might have liberty to stop in Barbados on her way to England,
because her goods were not fit for England.
Now, however reasonable this request was,
yet the master of a ship was compelled to carry her straight
to England without her goods for which she had come there,
except to the value of about six shillings,
which an honest man had given her upon an old account.
And when the master of the ship asked who should pay for her passage,
the magistrates bid him take as much of her goods as would answer for it.
But he was too honest to do so, being persuaded that she would not let him lose by her,
though he could not compel her to pay, knowing she went not of her own will.
Yet despite all this she paid him at London.
After she had gone,
when he that held the trust from her husband desired to convey her goods to Barbados,
these rapacious people charged him the value of six
pounds ten shillings for her passage to England,
for which they had paid nothing;
and then seven shillings more for boat-hire to carry her on ship-board,
though the master of the ship had offered the governor to carry her in his own boat.
Besides this, they took the value of fourteen shillings for the jailer,
to whom she owed nothing.
Now, though this widow had made such a great voyage to get something of what was due to her,
in order to relieve her and her fatherless children,
yet after three years she had nothing of it come to her hands;
and whether she got anything since then I never heard.

The next of the Quakers that came to Boston was Mary Clark, who, having left her husband,
John Clark, a merchant tailor, with her children at London,
came there to warn these persecutors to desist from their iniquity.
But after she had delivered her message,
she was unmercifully rewarded with twenty stripes
of a whip with three cords on her naked back,
and detained prisoner about twelve weeks in the winter season.
The cords of these whips were commonly as thick as a man`'s little finger,
having each some knots at the end;
and the stick was sometimes so long that the hangman made
use of both his hands to strike the harder.

The next that came were Christopher Holder and John Copeland,
who had been banished before; and coming to Salem, a town in the same colony,
Holder spoke a few words in their meeting after the priest had finished.
But he was hauled back by the hair of his head,
and a glove and handkerchief were thrust into his mouth,
and so was cast out with his companion.
The next day they were conveyed to Boston,
where each of them received thirty stripes with a knotted whip of three cords,
the hangman apparently measuring his ground,
and fetching his strokes with the greatest strength he could.
This so cruelly cut their flesh, that a woman seeing it fell down as one dead.
They were then locked up in prison, and the jailer kept them three days without any food,
or so much as a swallow of water; and none were allowed to come speak with them.
Thus they were kept nine weeks prisoners, lying on boards without bed or straw,
and without a fire in the cold winter season.
And Samuel Shattock of Salem,
who endeavored to stop the thrusting of the glove
and handkerchief into Christopher Holder`'s mouth,
lest it should have choked him, was also carried to Boston and there imprisoned,
until he had given bond for twenty pounds to appear at the next court sessions,
and was bid not to come to any meeting of the Quakers.

The career of this cruelty did not stop here; for Lawrence Southick and Cassandra,
his wife,
members of the public church at Salem (and an ancient and grave couple)
having given hospitality to the aforesaid C. Holder and J. Copeland,
were committed to prison, and sent to Boston.
Upon Lawrence being released, his wife was kept seven weeks prisoner,
and then fined forty shillings for owning a paper of exhortation
written by the aforesaid Holder and Copeland.

The next that came from England,
as being under a necessity from the Lord to come to this land of persecution,
was Richard Dowdney, who was apprehended at Dedham, and brought to Boston,
having never before been in that country.
Nevertheless, they spared him not, but thirty stripes were also given him,
in like manner as the former two men.
And after twenty days imprisonment,
he was sent away with Holder and Copeland after having been
threatened with cutting off their ears if they returned.
These cruel dealings so affected many inhabitants,
that some withdrew from the public religious assemblies,
and meeting by themselves quietly on the First-days of the week,
they were fined five shillings a week, and committed to prison.
The first whose lot this was, were the aforementioned Lawrence and Cassandra Southick,
and their son Josiah, who, being carried to Boston,
were all of them (notwithstanding the old age of the two) sent to the house of
correction and whipped with cords in the coldest season of the year.
They also had taken from them to the value of four pounds thirteen shillings,
for not coming to church.

Leaving New England for a while, I will turn another way.
It was in this year, about the latter end of summer,
that a certain young man named George Robinson felt a motion to travel to Jerusalem.
For this purpose, he embarked in a ship bound for Leghorn, in Italy,
where having stayed about two weeks, being daily visited by English and others,
he went with a French ship towards St. John D`'Acre, formerly called Ptolemais,
a city in Asia bordering upon the Mediterranean sea, near Palestine.
From here, having lodged about eight days in a French merchant`'s house,
he embarked in a vessel bound for Jaffa or Joppa.
What occurred by the way with some Turks, who demanded unreasonable tribute of him,
I pass by; but a certain Armenian on that occasion having seen his meek behavior,
said he was a good Christian, and was very kind to him.
Having arrived at Jaffa, he went to Ramoth,
but the friars at Jerusalem having heard of his coming, gave orders to some to stop him,
which was done accordingly.
And after having been locked up about a day, there came an ancient Turk,
a man of great repute, who took him into his house and courteously entertained him.
After four or five days, there came an Irish friar from Jerusalem, with whom,
falling into discourse of religious matters, the friar at first behaved himself kindly,
but told him afterwards, that this was not the business he came about,
but that he was sent from his brethren, the friars at Jerusalem,
to propound to him some questions: 1. Whether he would promise,
when he came to Jerusalem, that he would visit the holy places as other pilgrims did?
2+++.+++ Whether he would pay so much money as pilgrims used to do?
3+++.+++ Whether he would wear such a sort of dress as was usual with pilgrims?
4+++.+++ That he must speak nothing against the Turks`' laws.
5+++.+++ And when he came to Jerusalem, he must not speak anything about religion.

Not being willing to enter into such a promise,
he was taken by the Irish friar (with a guard of horsemen and footmen
he had brought with him) and carried back to Jaffa.
There he was made to embark in a vessel bound for St. John D`'Acre; where having come,
a French merchant called Surrubi took him into his
house and lodged him about three weeks.
This man entertained him very kindly,
and would say sometimes that it was the Lord`'s doing; "`For,`" said he,
"`when my own countrymen come to me, it means little to me,
but you I can willingly receive.`"

After much trouble, Robinson got opportunity (by the help of the said French merchant,
who was an ancient man) to return by sea to Jaffa.
From there he went on his journey on foot, and by the way met three men,
two of them riding upon asses, and the other going on foot.
These asked him for money, one holding a gun to his breast,
and another putting his hands into his pockets and taking some things out.
Robinson allowing all this without any opposition,
the man that took his things from him put them back again; then one of the three,
taking him by the hand, led him a little on his way in a friendly manner,
and so left him.

At length Robinson came to Ramoth, where his presence was quickly known,
and two that belonged to the friars laid hold on him and hurried him away.
Then two Turks took him from the friars, and one leading him by one arm,
and the other by the other, they brought him into a mosque, or Turkish temple.
Thus innocently entering there, many people came flocking in,
and also some of the Mohammedan priests, who, having him to sit down,
asked him whether he would turn to the Mohammedan religion?
But finding that he refused, they pressed him much, made great promises,
and said that he had no need to fear what the Christians might do unto him.
Nevertheless he answered he could not turn unto their religion for all the world.
But they continued to strive much with him,
and desired him to hold up one of his fingers as a sign of acknowledging them;
and one man bid him say, "`Christ is bad;`" but he answered, he knew Him to be good,
and that he was His servant.
Then some growing angry, said if he would not turn to their religion, he must die.
To this he replied that he would rather die than turn their religion;
and so it was answered that he indeed must die.
And so by their order,
the executioner hauled him away to the place where it was expected
that he should have been burnt to death with camel`'s dung.
Here he was made to sit down upon the ground as a sheep among wolves.
While he was thus sitting with his mind turned unto the Lord,
the Turks began to argue among themselves, and while they were at odds,
a grave ancient Turk, a man of note,
came up to him and told him that whether he would turn from his religion or not,
he should not die.
Then he was brought before the priests again, who asked him, "`Will you turn?`"
and he answering "`No,`" they recorded in a book
that he was no Roman Catholic but of another religion;
for though he denied being a Catholic, yet he had acknowledged that he was a Christian.

The Turks coming now to be more composed,
the aforesaid ancient man ordered his servants to conduct Robinson to his house,
where he was entertained in a friendly manner,
and soon perceived that the friars had thus plotted against him;
for he had not gone into the mosque of his own accord, but was led into it; nevertheless,
heaven had preserved him.
After having been four or five days in the house of the ancient Turk,
there came a guard of horsemen, hired by the friars, to carry him to Gaza;
for they had pre-informed the bashaw^
footnote:[A man of high rank or office in countries under Turkish rule.]
of that place against him.
But when Robinson had come there, things took another turn than they expected;
for the Turks having acquainted the bashaw with the mischievous design of the friars,
he made them not only pay a considerable fine,
but also commanded them to convey Robinson safely to Jerusalem.
While he was at Gaza, he was visited by many Turks, Greeks, and Armenians;
the latter of which, having heard he was a Christian,
and that he chose rather to die than to turn from his religion, became very loving,
as were the Turks, and also the Jews showed themselves moderate towards him.
Then, according to the aforementioned order of the bashaw, he was carried to Jerusalem,
and there, by the appointment of the friars, was brought into their convent,
where at first they seemingly showed love unto him.
One of them confessed that they now had an evident sign that he was a good Christian,
for he had come through persecution and sufferings;
and those things which had been spoken in his prejudice were manifest to be untrue.
Robinson told the friar that it was he and his brethren
that had been the cause of his sufferings,
and had withstood his coming to Jerusalem.
To this the other replied, that the English friar had misinformed them by his writing,
which had caused them to do what they had done;
and that therefore they desired he would now pass by those things,
seeing he had come through in such a miraculous manner;
"`for,`" (continued the friar) "`it was the Lord`'s work thus to carry you through,
and you may praise God you were preserved.`"

The next morning a friar came to him and asked if he would become an obedient child,
and go to visit the holy places, according to their custom.
He answered, "`No.`" Then the friar said,
"`Whereas others give great sums of money to see them, you shall see them for nothing.`"
But Robinson replied, "`I shall not visit them in your manner,
for in so doing I would sin against God.`"
This did not please the friar,
yet he said they would honor him as much as ever
they honored any Englishman that came there,
if he would conform unto them.
But Robinson continued immoveable, and said he would not conform; and as for their honor,
it mattered not to him.
Then the friar became angry,
and said they would make him an example to all Englishmen that came there.
To which Robinson replied, "`I choose your dishonor rather than your honor.`"
The friar seeing he could not prevail, went away in anger,
and within a short time came again.
Other friars being present at this time, one asked him if he would visit their church,
and the holy sepulcher, and Bethlehem,
with the rest of the holy places as other pilgrims did?
But he told them, at present he had no business to visit them,
and in their manner he should not visit them at all, that is, to worship them.
Then one said to him, "`How can you be a servant of God,
and will not go to visit the places where the holy men of God dwelt?`"
To which he replied, that they,
under pretense of doing service to God in visiting the places where the holy men dwelt,
did oppose that way, and resist that life, in which the holy men of God lived and walked.
Then one of the friars said, "`What do you preach unto us for?`"
To which he replied,
that he desired them to turn from those evil practices they lived in,
else the wrath of the Almighty would be kindled against them.
But they did not at all like such discourse, and therefore said,
"`if you will not go and visit the aforesaid places,
yet you must give twenty-five dollars, as is the manner of those that visit them;
for,`" said they, "`the Turks must be paid, whether you will visit them, or not.
But if you will visit them, then we will pay it for you.`"
To this he signified that he could not submit to such unreasonable terms.

Then they brought him before a Turk in authority in that place,
who asked him several questions, to all of which he gave sober answers.
And as they were discoursing about the worship of the Christians,
the Turk also asked him the ground of his coming to Jerusalem.
To this he answered,
that it was by the command of the Lord God of heaven and earth he came there;
and that the great and tender love of God was made manifest in visiting them;
His compassionate mercies being such that He desired
to gather them in this the day of His gathering.
This was the message which Robinson believed he had from the Lord to declare unto them,
whether they would hear or refuse.
And afterwards, he wrote that having thus cleared his conscience,
he found great peace with the Lord, and therefore he magnified His glorious name,
who had gone along with him and preserved him in many trials.
For the friars, who intended him mischief,
were commanded by the Turks to carry him again safe and free of charges to Ramla.
Here I leave him, because I do not find how he came home;
but that he returned there in safety,
appears to me from the relation he afterwards published of his travels.
