== Chapter VIII

[.section-date]
1657--1659

The year having come to an end, I return again to G. Fox, whom we left at Newcastle.
While he was there, he, with Anthony Pearson, visited some of the aldermen;
and among these one named Ledger,
who (as well as the priests) had boasted that the
Quakers would not come into any great towns,
but only lived in the fields like butterflies.
G+++.+++ Fox desired to have a meeting among them, but they would not yield to it.
He therefore asked Ledger, whether they had not called his friends butterflies,
saying they would not come into any great towns?
"`But,`" said he, "`now we have come into your town, and you will not come to us;
who are the butterflies now?`"
No permission for a public meeting being obtained,
G+++.+++ Fox managed to get a little meeting among his friends,
and some friendly people at Gateside.

Traveling from there and passing through Northumberland, and Bishopric,
he came to Durham, where a man had come down from London to set up a college there,
in order to make ministers of Christ, as he said.
G+++.+++ Fox entering into discourse with this man, said that to teach men Hebrew, Greek,
and Latin, and the seven arts, was not the way to make ministers of Christ;
for the languages began at Babel,
and to the Greeks that spoke Greek as their mother tongue,
the preaching of the cross of Christ was foolishness;
and to the Jews that spoke Hebrew as their mother tongue, Christ was a stumbling block.
And as for the Romans, who spoke Latin, they persecuted the Christians; and Pilate,
one of the Roman governors, set Hebrew, Greek,
and Latin on top of Christ when he crucified Him.
Thus the languages, which began at Babel, had been set above Christ the Word.
And John the apostle, who preached the Word that was in the beginning,
said that the beast and the whore had power over tongues and languages,
and that they were like waters, and in the mystery Babylon, for they all began at Babel;
and the persecutors of Christ set languages over Him when He was crucified by them.
"`Do you think,`" said G. Fox to the man,
"`to make ministers of Christ by these natural confused languages,
which sprang from Babel, are admired in Babylon, and set atop of Christ, the life,
by a persecutor?`"
The man, puzzled a little by this, confessed to many things spoken by G. Fox.
Then it was showed him further, that Christ made His ministers himself,
and gave gifts unto them,
and bid them pray to the Lord of the harvest to send forth laborers.
And he showed how Peter and John, though unlearnt and ignorant as to school-learning,
preached Christ the Word, which was in the beginning before Babel was;
and that Paul also was made an apostle, not of man, nor by man, but by Jesus Christ,
who is the same now, and so is His gospel, as it was at that day.
This discourse had such effect upon the man, that he became very loving;
and having considered the matter further, he never set up his intended college.

From Durham G. Fox passed to Nottingham, where he gathered again a scattered people,
that having about eight years before been convinced of the Truth,
had been led aside by one Rice Jones.
From here he went into Warwickshire,
and passing through Northamptonshire and Leicestershire, he came into Bedfordshire,
and so to John Crook`'s house, where a general yearly meeting was appointed,
which lasted three days.
Many of G. Fox`'s friends from most parts of the nation came to it,
so that the inns in the towns thereabouts were filled.
Here came also William Caton, who after the meeting had ended,
went with Thomas Salthouse (formerly his fellow servant
in the house of judge Fell) to Westmoreland,
Cumberland, and Swarthmore in Lancashire.
In the said general meeting,
G+++.+++ Fox made a long speech concerning the several states of man,
but more especially gave instruction of the ministers of the word,
exhorting them at length to be circumspect in their station.

After the meeting was over,
there came a party of horsemen with a constable to seize G. Fox,
who then was walking in John Crook`'s garden; and though when they came to the house,
somebody had told them that G. Fox was there, yet they were so confounded,
that they came not into the garden to look for him, but went away without him.

Parting from there, he came to London, where he heard that a Jesuit,
who had come over with an ambassador from Spain,
had challenged all the Quakers to dispute with them at the earl of Newport`'s house.
G+++.+++ Fox then let him know by some of his friends, that they would meet him there;
whereupon the Jesuit sent word that he would meet with twelve
of the wisest and most learned men they had.
A while after he sent word, he would meet with but six; and after that,
he sent word again, he desired only three to come.
Then G. Fox went to the aforesaid house with Edward Burrough and Nicholas Bond,
and bade them to go up and enter the discourse with the Jesuit,
while he would be walking in the yard, and then come up after them.
He had advised them to state this question: Whether the church of Rome, as it now stood,
had not degenerated from the true church which was in the primitive times,
from the life and doctrine, and from the power and Spirit that those believers were in?
They having stated the question accordingly,
the Jesuit affirmed that the church of Rome now was
in the virginity and purity of the primitive church.
By this time G. Fox had come in,
and the Jesuit was asked whether they had the Holy Spirit poured forth upon them,
as the apostles had?
And he said, "`No.`" Then said G. Fox,
"`If you have not the same Holy Spirit poured forth upon you,
and the same power and Spirit that the apostles had,
then you are degenerated from the power and Spirit which the primitive church was in.`"
And he asked the Jesuit, what Scripture they had for setting up cloisters for nuns,
abbies and monasteries for men, and for their praying by beads and to images,
and for making crosses, for forbidding of meats and marriages,
and for putting people to death for religion?
"`If,`" said he, "`you are in the practice of the primitive church,
in its purity and virginity, then let us see by Scripture,
wherever they practised such things?`"
For it was agreed mutually, that both the Jesuits and the Quakers,
should make good by the Scriptures what they said.
Then the Jesuit said there was "`a written and an unwritten word.`"
Which made G. Fox ask, what he called his "`unwritten word`"? And he answered,
"`The written word is the Scriptures,
and the unwritten word is that which the apostles spoke by word of mouth,
which are all those traditions that we practice.`"
Then G. Fox bid him to prove this by Scripture,
and the Jesuit alleged the words of the apostle, 2 Thess.
2:5. "`When I was with you, I told you these things:`" "`That is,`" said the Jesuit,
"`I told you of nunneries and monasteries, of putting to death for religion,
and of praying by beads and to images,`" etc.
This he affirmed to be the unwritten word of the apostles, which they spoke of then,
and which had since been continued by tradition unto these times.
Then G. Fox desired him to read that Scripture again,
that he might see how he had perverted the apostles`' words,
since that which the apostle said there he had told them before,
was not an unwritten word, but was written down there; namely, that the man of sin,
the son of perdition,
should be revealed before the great and terrible day of Christ should come,
of which he was writing.
And therefore Paul was not telling them any of those
things which the church of Rome practiced.
Besides,
the apostle in the third chapter of the same epistle told the church
of some disorderly persons he heard were among them,
busy bodies, who did not work at all;
concerning whom he had commanded them by his unwritten word, when he was among them,
that if any would not work, neither should he eat;
which now he commanded them again in his written word in this epistle, 2 Thess.
3.

The Jesuit now finding no other scriptural proof for the tradition of the church of Rome,
let that point fall, and came to the sacrament of the altar,
to prove the reality of which, he began with the paschal lamb, and the showbread,
and so came to the words of Christ,
"`This is my body,`" and to what the apostle wrote to the Corinthians,
concluding from there, that after the priest had consecrated the bread and wine,
it became immortal and divine, and that he who received it, received the whole Christ.
To this G. Fox said, that the same apostle told the Corinthians,
after they had taken bread and wine in remembrance of Christ`'s death,
that they were reprobates if Christ was not in them.
But that if the bread they ate was Christ, He must of necessity have been in them,
after they had eaten it.
Besides,
if the bread and wine which the Corinthians ate and drank was Christ`'s actual body,
how then (continued he) has Christ a body in heaven?
And he also signified to him, that both the disciples at the supper,
and the Corinthians afterwards,
were to eat the bread and drink the wine in remembrance of Christ,
and to show forth His death till He came;
which plainly proved that the bread and wine which they took, was not His body.
For if it had been His real body that they ate, then He had been come,
and was then there present;
and it would have been improper to have done such a thing "`in
remembrance of Him,`" if He had then been present with them;
as He must have been, if that bread and wine, which they ate and drank,
had been His real body.
And as to the words of Christ, "`This is my body,`" G. Fox told him,
"`Christ calls himself a vine and a door, and is called in Scripture a rock;
is Christ therefore an outward rock, door, or vine?`"
"`Oh,`" said the Jesuit, "`these words are to be interpreted.`"
"`So,`" said G. Fox, "`are those words of Christ, '`This is my body.`'`"

And having thus stopped the Jesuit`'s mouth, he made this proposal: that,
seeing he said the bread and wine was immortal and divine, and was the very Christ,
and that whoever received it received the whole Christ;
a meeting might be appointed between some such Papists
as the Pope and his cardinals should appoint,
and some of those called Quakers.
"`And then,`" said he, "`let a bottle of wine, and a loaf of bread be brought,
and divided each into two parts,
and let them consecrate which of those parts they desire;
and then let the consecrated and unconsecrated bread and wine be set in a safe place,
with a careful watch upon it;
and let trial then be made whether the consecrated
bread and wine will not lose its goodness--that is,
whether the bread will grow dry and moldy,
and the wine turn dead and sour--as well and as soon as that which was unconsecrated;
for by this means the truth of this matter may be made manifest.
And if the consecrated bread and wine do not change,
but retain their savour and goodness, this may be a means to draw many to your church.
But if they change, decay, and lose their goodness,
then you ought to confess and forsake your error, and shed no more blood about it,
as has been done, especially in queen Mary`'s days.`"
To this the Jesuit made this reply: "`Take a piece of new cloth,
and cut it into two pieces, and make two garments of it,
and put one of them upon king David`'s back, and the other upon a beggar`'s,
and the one garment shall wear away as well as the other.`"
"`Is this,`" said G. Fox, "`your answer?`"
"`Yes,`" said the Jesuit.
"`Then,`" said G. Fox, "`by this the company may all be satisfied,
that your consecrated bread and wine is not Christ.
Do you now say that the consecrated bread and wine,
which you have told people was immortal and divine,
and the real body and blood of Christ, will wear away, or decay as well as the other?
Then I must tell you, Christ remains the same today as yesterday, and never decays;
but is the saints`' heavenly food in all generations, through which they have life.`"
To this the Jesuit replied no more, but let the thing fall;
for he perceived that those which were present saw his error,
and that he could not defend it.

Then G. Fox asked him, why the church of Rome did persecute,
and put people to death for religion?
The Jesuit answered, it was not the church did it, but the magistrates.
G+++.+++ Fox asked,
whether those magistrates were not counted and called believers and Christians?
"`Yes,`" said he.
"`Are they not members of the church?`"
asked G. Fox.
"`Yes,`" said the Jesuit.
Then G. Fox left it to the people to judge, whether the church of Rome did not persecute,
and put people to death for religion.
Thus they parted; the Jesuit`'s subtlety being comprehended by the simplicity of G. Fox,
and his friends.

While G. Fox was at London, his friends, both in England and Ireland,
were under great sufferings, which made him write to the protector about it.
And because there was much talk of making Cromwell king,
he went to him and warned him of the dangers that would attend it, which,
if he did not avoid, would bring shame and ruin upon him and his posterity.
This counsel Cromwell seemed to take well, and thanked him for it:
yet G. Fox wrote again concerning the same thing to him in this manner:

O Protector,

You who have tasted of the power of God,
which many generations before you have not so much known,
since the days of apostasy from the apostles; take heed that you do not lose His power,
but keep royalty off your head, which the world would give to you;
and keep all earthly crowns under your feet,
lest you cover yourself with it and so lose the power of God.
When the children of Israel went out from the gift of God within them,
they desired to have kings as other nations had, and as transgressors had;
and so God gave them one; but what did they do then?
And when men would have taken Christ and made him a king by force,
He hid himself from them.
He hid from that which would have made him a king, He who was the king of the inward Jews.
O Oliver, take heed of ruining yourself, by running into things that will fade, that is,
the things of this world that will change.
Be subject and obedient to the Lord God.

George Fox.

About this time G. Fox wrote also another letter to Oliver Cromwell,
wherein he signified to him that if he had been faithful and denounced all deceit,
he would yet have done many mighty things.
And he also advised him not to scorn sober and true-hearted men,
but to mind the law of God, and abide in His fear and dread; to take heed of flatteries,
and to prize his time now that he had it.

The lady Claypole, Cromwell`'s most beloved daughter,
being sick and much troubled in mind,
so that none that came could minister any comfort to her,
G+++.+++ Fox visited her with the following letter:

Friend,

Be still and cool in your own mind and spirit from your own thoughts,
and then you will feel the seed of God to turn your
mind to the Lord God from whom life comes,
whereby you may receive His strength and power to allay all blustering storms and tempests.
It is this which works the heart up into patience, into innocency, into soberness,
into stillness, into staidness, into quietness, up to God with His power.
Therefore,
mind this seed--this is the word of the Lord unto
you--that you may feel the authority of God,
and know your faith to be in this, which will work down that which troubles you.
For it is this which keeps peace,
and raises up the witness in you which has been transgressed,
to feel after God with His power and life, who is a God of order and peace.

When you are in the transgression of the life of God in your own particular,
the mind flies up in the air, and the creature is led into the night,
and nature goes out of its course, and an old garment goes on as the uppermost clothing.
Thus your nature is led out of its course, and comes to be all on a fire,
in the transgression; and this defaces the glory of the first image.
Therefore be still awhile from your own thoughts, your own searching, seeking, desires,
and imaginations, and be stayed in the seed of God in you,
that it may raise your mind up to God, and stay it upon God,
and so you will find strength from Him, and find Him to be a God at hand,
a present help in the time of trouble and of need.
And having come to the seed of God, which has been transgressed, it will keep you humble;
and the humble God will teach His way, which is peace; and such as these He does exalt.

Now as this seed of God in you has been transgressed, come to it,
that it may keep your mind down low to the Lord God; and so deny yourself,
for you must be kept from your own will that is earthly;
then you will feel the power of God, which will bring nature into its course,
and give you to see the glory of the first image.
Here the wisdom of God will be received (which is Christ,
by which all things were made and created),
so that you may thereby be preserved and ordered to God`'s glory.
And here you will come to receive and feel the Physician of value,
who clothes people in their right mind, whereby they may serve God and do His will.
For all distraction, unruliness, and confusion, is in the transgression;
and transgression must be brought down,
before the seed of God (which has been transgressed against) will be lifted up,
whereby the mind may be seasoned and stilled,
and a right understanding of the Lord may be received.
Thus His blessings enter, and are felt over all that is contrary,
in the power of the Lord God, which raises up the seed of God within,
and gives a feeling after God, and in time gives dominion.

Therefore keep in the fear of the Lord God--this is the word of the Lord
God unto you--for all these things happen to you for your good,
and for the good of those concerned for you, to make you know yourselves,
and your own weakness, and that you may know the Lord`'s strength and power,
and may trust in Him.
Therefore let the time that is past be sufficient to everyone,
who in anything has been lifted up in transgression, out of the power of the Lord:
for He can bring down and abase the mighty, and lay them in the dust of the earth.
Therefore let all keep low in His fear,
that thereby you may receive the secrets of God and His wisdom,
and may know the shadow of the Almighty, and sit under it in all tempests, storms,
and heats.
For God is a God at hand, and the Most High rules in the children of men.

So then, what the light does make manifest and discover--such as temptations,
distractions, confusions--do not look at the temptations, confusions, corruptions,
but at the light which discovers them and makes them manifest.
And with the same light you may feel over them, to receive power to stand against them.
The same light which lets you see sin and transgression,
will let you see the covenant of God, which blots out your sin and transgression,
and gives victory and dominion over it, and brings into covenant with God.
For looking down at sin, corruption and distraction, you are swallowed up in it;
but looking at the light which discovers them, you will see over them.
This will give victory, and you will find grace and strength;
and here is the first step to peace.
This will bring salvation,
and by this light you may see to the beginning and to the
glory that was with the Father before the world began;
and so you will come to know the seed of God, which is the heir of the promise of God,
and of the world which has no end--the seed which bruises the head
of the serpent who stops people from coming to God.
Thus you may feel the power of an endless life, the power of God which is immortal,
which brings the immortal soul up to the immortal God, in whom it does rejoice.
So in the name and power of the Lord Jesus Christ, may God Almighty strengthen you.

G+++.+++ Fox

This paper being read to the aforesaid lady, it stayed her mind somewhat;
but she lived not long after.
Thus Oliver Cromwell met with almost continual trouble,
for discontent against him increased more and more.

Now, since the Protestants in the valley of Lucerne, and elsewhere, were much persecuted,
there came forth a declaration from the protector to keep a fast,
and another declaration for a collection for the relief of distressed Protestant churches.
On this occasion,
G+++.+++ Fox wrote the following paper to show what kind
of fast it was that God requires and accepts.

To the heads and governors of this nation,
who have put forth a declaration for the keeping of a day of solemn fasting and humiliation,
for the persecution, as you say,
of many people beyond the seas who profess the reformed religion, which, you say,
has been transmitted unto them from their ancestors.

A profession of the reformed religion may indeed be transmitted to generations,
and so be held by tradition;
and in that part wherein the profession and tradition is held,
there the day of humiliation is also kept; all of which stands in the will of man.
This is not the fast that the Lord requires,
"`to bow down the head like a bulrush for a day,`" and the day
following to be in the same condition as they were the day before.
To the light of Christ Jesus in your consciences I do speak,
which testifies for God every day, and witnesses against all sin and persecution;
which measure of God`'s grace, if you be guided by it, does not limit God to a day,
but leads to the fast which the Lord requires, which is,
"`To loose the bonds of wickedness, to undo the heavy burdens, to break every yoke,
and let the oppressed go free.`" Isa. 58:6-7.
This is the fast the Lord requires; and this stands not in particular times,
nor in the traditions of men, but rather stands in that which was before times were,
and which leads out of time, and which shall be when time shall be no more.
And it is those who "`teach as doctrine the commandments of men,`"^
footnote:[Matthew 15:9]
that have ever persecuted the life and power when it came.

Now, whereas you take into your consideration the sad persecution, tyranny,
and cruelty exercised upon them, whom you call your Protestant brethren,
and do contribute and administer to their outward needs; this is good in its place,
and we acknowledge it, and see it good to administer to the necessities of others,
and to do good to all.
And we who have been sufferers by a law derived from the Pope,
are willing to join and contribute with you in assisting their outward necessities.
"`For the earth is the Lord`'s, and the fullness thereof;`"^
footnote:[Psalm 24:1; 1 Corinthians 10: 26, 28]
who is good to all, and gracious to all, and willing that all should be saved,
and come to the knowledge of the Truth.

But in the meantime, while you are doing this, and taking notice of others`' cruelty,
tyranny, and persecution, turn your eye upon yourselves,
and see what you are doing at home.
To the light of Christ Jesus in all your consciences I speak, which cannot lie, err,
or bear false witness; but always bears witness for God, and cries for equity, justice,
and righteousness to be executed.
See what you are doing, you who profess the Scriptures,
which were given forth by the saints in light,
who dwelt in the light and in the life of them.
For those who do now witness the same light, the same life,
and the same power which gave forth the Scriptures (which you in words profess),
these you persecute; these you haul out of your synagogues and markets; these you beat,
stock, and imprison.
Now let the gift of God in your consciences, which is just and righteous and equal,
examine and try whether you have any example or precedent to exercise this persecution,
which now many in this nation suffer under, who are a harmless and innocent people,
walking in obedience towards God and man.
And though you account the way of Truth they walk in to be "`heresy;`" yet therein
they always seek to have a conscience void of offense towards God and man,
as you may read the saints of old did, (Acts 24:14-16). These wrong no man,
nor give any just cause of offense, but rather speak the truth in Christ,
their consciences bearing them witness that they do not lie.
But for this they suffer under you,
who in words profess the same thing for which they suffer.

Now consider if any age or generation did ever persecute as you do.
For you profess Christ Jesus, who reveals the Father,
and yet persecute those who witness the revelation
of the Father by Christ Jesus unto them.
You profess Christ Jesus, who is the light of the world,
"`that enlightens everyone that comes into the world,`"^
footnote:[John 1:9]
and yet persecute those who bear witness and give testimony to this light.
You profess that the Word has become flesh, and yet persecute those who witness it so.
You profess that "`whoever does not confess that Jesus Christ has come in the flesh,
is an antichrist;`"^
footnote:[1 John 4:3]
and yet persecute those that do confess Him to have come in the flesh,
and call them antichrists and deceivers.
You profess that the kingdom of Christ has come;
and yet persecute those who witness it to have come.
You profess Christ Jesus the resurrection and the life;
and yet persecute those who witness Him to be so.

But if you say,
"`How shall we know whether these people who say they witness these things,
do so or not?`"
I answer, turn your minds to the light with which Christ Jesus has enlightened you,
which is one in all.
And if you walk in the light, you shall have the light of life,
and then you will know and see what you have done,
who have persecuted the Lord of glory (in His people), in whom is life,
and the life is the light of men.
We turn you to no other touchstone but that in your own consciences,
and there you shall find the truth of what we have declared unto you,
and of what we bear testimony to, according to the Holy Scriptures.
And when the books of consciences are opened, and all are judged out of them,
then shall you witness us to be of God, and our testimony to be true,
though now you may stop your ears, and "`harden your hearts, while it is called today.`"
But then you shall know what you have done, and whom you have transgressed against;
and you will see that no other persecutors,
in any age or generation that ever went before you,
did ever transgress against that light and measure of God
made manifest in such a manner as you have done.
For though Christ and the Apostles were persecuted in their times,
yet the Jews (for the most part) did not know that He was the Christ when He
came (notwithstanding that they had the Scriptures which prophesied of Him);
neither did they believe that He had risen again when the apostles preached His resurrection.
But you say you believe He has come; and you say you believe His resurrection,
and yet you persecute those who witness Him to have come in the flesh.
Those who are buried with Him in baptism, those who are conformable to His death,
and know the power of His resurrection, those you persecute;
those you haul before magistrates, and allow to be beaten in your synagogues;
those you cause to be whipped and stocked and shamefully entreated,
and cast into prison--as many jails in this nation
at this day will testify to your faces.

Therefore, honestly consider what you are doing,
while you are taking notice of others`' cruelties, lest you overlook your own.
There is indeed a difference in many things between the
Popish religion and that which you call the Protestant,
but in this persecution of yours there is no difference.
For you will say that the foundation of your religion is grounded upon the Scriptures,
and yet now you are persecuting those that are in the same
life which they were in who spoke forth the Scriptures;
you yourselves being under a mere profession of the words they spoke:
and this you shall one day witness.
So you have a profession and a form, and yet persecute those that are in the possession,
life, and power.
Therefore, turn your minds to the light of Jesus Christ in your consciences,
which searches and tries you.
Stand still, and wait there to receive the righteous law,
which is according to that gift of God in the conscience, which is now rising,
and is bearing witness against all ungodliness and unrighteousness of men.

Our rejoicing is in the testimony of our consciences,
that in simplicity and godly sincerity (not with fleshly wisdom,
but by the grace of God) we have conducted ourselves in the world;
not handling the word of God deceitfully, but, in the manifestation of the Truth,
commending ourselves to every man`'s conscience in the sight of God.
And if our Gospel is veiled, it is veiled to those who are lost;
and it is for holding the mystery of faith in a pure conscience that we suffer.
For this is commendable, if because of conscience toward God one endures grief,
suffering wrongfully.
And in this is our joy and rejoicing, to have a good conscience,
notwithstanding we are evilly spoken of as evil-doers; for these will be ashamed,
who falsely accuse our good conduct in Christ;
which is not only the putting away of the filth of the flesh,
but the answer of a good conscience towards God by the resurrection of Jesus Christ.

Therefore, I say again, turn your minds to the eternal light of Christ Jesus,
the searcher and trier of all hearts, and see what you are doing,
lest while you are professing the Scriptures, you persecute the life, light,
and power which gave them forth.
For the stone cut out of the mountain without hands is now striking at the feet of the
image--the great profession which is set up and stands in the will of man.
And now that light is made manifest, unto which all must answer,
and in which all must appear before the judgment seat of Christ,
that everyone may receive the things done in his body, whether good or bad.

G+++.+++ Fox

Many of his friends being at this time in prisons and dungeons,
several others of them went to the parliament and offered to lie
in the same prisons where their brethren lay in their place,
so that those who were in prison, might not perish in stinking dungeons,
and their persecutors thereby bring innocent blood upon their own heads.
But this could not be obtained;
for some of the parliament threatened these compassionate
men with whipping if they did not desist.
And because the parliament that was then sitting consisted mostly of such who,
pretending to be more religious than others,
were indeed great persecutors of those that were truly pious,
G+++.+++ Fox could not let this hypocrisy go unreproved, but wrote the following lines to them:

O friends, do not cloak and cover yourselves; there is a God that knows your hearts,
and who will uncover you.
He sees your way: "`Woe to him that covers with a covering, but not of My Spirit,`"^
footnote:[Isaiah 30:1]
says the Lord.
Do you act contrary to the law, and then excuse yourselves?
You neglect mercy and true judgment.
Look, what my Savior spoke against such: "`I was sick, and you visited me not;
I was hungry, and you did not feed me; I was a stranger, and you did not take me in;
I was in prison, and you did not visit me.`"
But they said, "`When did we see you in prison, and did not come to you?`"
"`Inasmuch as you did it not unto one of these little ones, you did it not unto me.`"^
footnote:[Matthew 25:43-46]
Friends, you imprison those who are in the life and power of Truth,
and yet you profess to be the ministers of Christ.
But if Christ had sent you, you would bring people out of prison, and out of bondage,
and also receive strangers.
"`You have lived on the earth in pleasure and luxury;
you have fattened your hearts as in a day of slaughter.
You have condemned, you have murdered the just; he does not resist you.`"^
footnote:[James 5:5-6]

G+++.+++ F.

It was not G. Fox alone who was grieved with the said hypocrisy,
but others of his friends also declared zealously against it.
A certain woman came once into this parliament with a pitcher in her hand, which,
breaking before them, she told them,
"`so shall you be broken to pieces;`" which came to pass not long after.
And because,
when the great sufferings of G. Fox`'s friends were laid before Oliver Cromwell,
he would not believe it,
this gave occasion to Thomas Aldam and Anthony Pearson to go through all,
or most of the jails in England to get copies of
their friends commitment under the jailers`' hands,
so as to lay the weight of the said sufferings upon O. Cromwell.
But when this had been done;
finding that he was still unwilling to give order for their release,
Thomas Aldam took his cap from off his head, and tearing it to pieces, said to Cromwell,
"`So shall your government be rent from you and your house.`"

About the beginning of this year,
Edward Burrough wrote a letter to O. Cromwell and his council, complaining of,
and warning them against persecution,
as being that which would draw down God`'s anger against them.
Several copies of the said letter were delivered to Oliver and his council;
and some months after E. Burrough wrote the following letter to him.

To the Protector.

Friend,

The salutation of my life wishes well unto you in the Lord,
and most especially that your precious soul may be redeemed out of death to God,
and so live, and find rest and a habitation in Him when this world is no more.

Now, whereas it is a general outcry among the teachers and people of this nation,
and has been sometimes objected by yourself, that the people called Quakers are deluded,
deceived, and in error, etc.; therefore,
in order that yourself and others may be resolved concerning us,
I request that you put all your objections and doubtings into plain positions,
or let the wisest of your teachers do it for you; whatever you can object against us,
or what you doubt of, or stumble over,
either with respect to our doctrines or our practice--let
the matter be stated in plain words,
in positions, or queries, and if God permit,
a sufficient answer will be given to remove all conscientious scruples,
and to confound all subtle allegations and evasions.
Hereby you may forever be altogether inexcusable of all doubting, or speaking against us,
or allowing evil to be done or spoken against us upon that account.

I am moved to give forth and send this to you that you may be satisfied,
and that all things may be tried and made manifest in the sight of all men;
and that all rash judgment and false supposition, which lodges in the hearts of many,
may be confounded and brought down, and all things brought to light and true judgment;
so that what is proved to be the Truth may be acknowledged and not persecuted anymore.
For we are willing to be made manifest to all men,
and if anything is objected against us which we cannot
sufficiently answer or resolve to sober men,
then our enemies are more free, and have something to glory in against us.
But if all occasion of stumbling is removed by our answers, according to the Scriptures,
and if our principles, practices, and doctrines are thereby vindicated,
then let all the teachers, and all our adversaries,
shut their mouths from biting at us and railing against us,
and accusing of us before you.
And may your ear be shut from believing lies against the innocent;
and may no man suffer in your dominion under the cruelty of men upon such a ground.

Hereof I shall be glad to receive an answer; and in the meantime, and always,
am a lover of your soul, but a witness against all oppression.

E+++.+++ B.

This was delivered to his hands at Hampton Court, in the Fourth Month, 1658.
I never understood that anything of importance followed upon this letter;
but about two months afterwards, he wrote another letter to Cromwell,
which was delivered to him at Hampton Court, in the sixth month.

To the Protector

Friend,

Know that there is a God that does whatever He will.
All power is in His hand, and He brings to pass the counsel of His own heart.
He rules in the kingdoms of men, and brings down and sets up; He kills and makes alive;
He changes times, and seasons, and governments, bringing to nought the counsels of men.
For all power in earth and in heaven is in Him, and all His doings are right,
and His ways are equal, and you and all mankind are as clay in the hand of the potter.
He can honor and exalt as He pleases,
and He can spoil and break to pieces and dishonor whenever He will.
Therefore, be humble and low in heart before Him, for He is the highest power,
that subdues all things under His feet.
If He wounds, who can heal?
And if He kills, there is none who can make alive.
Know therefore, that it is the Lord God Almighty that does this,
in whose hands are the issues of life and death;
and He it is who can break you down and build you up; who can wound you and restore you;
who can bring you to destruction, and say unto you, "`return.`"

Be faithful in what the Lord calls you to, and you shall have your reward.
Seek His honor, and He will honor you.
Let your mind be to the Lord in all things,
and feel His word and power and presence in you, to quench all that which is contrary,
and then you will be blessed in this life, and in the life to come.
But if you continue in your oppression, the Lord will suddenly smite you.

From a friend to you in the Lord,

E+++.+++ B.

That the Lord, according to this prediction, did suddenly smite Cromwell, time verified;
for he lived but about a month after the receipt of this letter.
And it appears to me from several circumstances that E. Burrough did tenderly love him,
and that it was the ardent desire he had for his eternal
welfare which occasioned this plain language to him.

G+++.+++ Fox also wrote to him, saying it was not improbable that, because of his wickedness,
the Lord might raise the royalists against him,
to be the instruments of executing His wrath;
even as Cromwell had himself once been an instrument in their overthrow.
And a very short time before his death,
G+++.+++ Fox went to Hampton Court in order to speak with
him about the sufferings of his friends.
With this intention, he met Cromwell riding into Hampton Court park;
and before he came to him (according to his relation),
he perceived a waft of death go forth against him; and coming close to him,
said he looked like a dead man.
So after G. Fox had presented the sufferings of his friends before him,
and had warned him, Oliver bid him come to his house; whereupon G. Fox went to Kingston,
and the next day came to Hampton Court again.
But there he was told that the protector was sick;
and Dr. Harvey told George that the doctors were
not willing that he should speak with him.
So he passed away, and never saw Oliver Cromwell again; who,
since the death of his daughter, the lady Claypole, had been unwell,
and troubled with a malignant tumor in his foot; which,
when his physicians endeavored to disperse it, moved upward (as was said) to his heart;
and then being seized with a violent fever, he grew weaker and weaker.
Nevertheless, his preachers endeavored to conceal the danger he was in;
and it is reported that Dr. Goodwin, one of his chaplains,
in a prayer during the time of his sickness, made use of this expression, "`Lord,
we beg not for his recovery, for that You have already granted and assured us of;
but for his speedy recovery.`"
While the protector was sick,
Edward Burrough wrote the following letter to his wife and children.

Friends,

Remember, that by the Lord you were raised from a low state; and when He so desires,
he can also abase you, and bring you down.
He gave you the palace of princes, and cast out them before you.

O, remember this, every one of you, and come to the witness of God within you,
and be humble, and meek, and lowly, and let the Lord`'s fear be in your hearts.
Be of a tender spirit, having your minds exercised in purity, in holiness,
and in righteousness.
Do not exalt yourselves, nor be lifted up in your hearts in the pride, vainglory,
and honors of this world, lest the Lord cast you down,
and make your name and posterity a reproach, as He has done with many before you.
And surely, if you walk in the same steps, and do the same things,
and become guilty of the same abominations,
and allow the children and servants of the Lord to
be persecuted (as many are at this day,
some unto death), shall the Lord spare you?
No, He will cause you to feel His hand of judgment, and bring you down with sorrow.
He will vex you in His wrath, and smite you with His rod more and more,
till you learn His fear, and depart from all your iniquities.
The Lord will deface your glory, and pull off your crown,
and make you know that He is Lord, that does whatever He will.

Therefore humble yourselves under the hand of God, search your own hearts,
and cast out the abominations that vex the Spirit of the Lord;
and permit not the people of the Lord`'s precious
flock to be devoured and made a prey to the wicked.
For it is because of this that the rod of affliction comes upon you,
and may suddenly break you to pieces.
But mind the Seed of God in you, which is oppressed,
and wait to know the power of the Lord which will redeem you out of sin and death,
and reconcile you to God,
and bring you into fellowship with Himself to enjoy peace and rest for your souls,
that you may be made heirs of the inheritance of an endless life.
This would make you truly honorable, and will be more satisfaction to you, and joy,
and contentment, and true rejoicing, than all worldly crowns and worldly glories;
for all these things will waste away and be consumed, and leave you miserable.
And remember that you are now warned from the Lord God,
by whom I am moved to write this unto you, in dear and tender love to you all;
and one day you shall witness it to be so.

And as concerning the Quakers (so called), who are accounted vile in the sight of men,
and are cast out of all power and place in the nation, being despised of all;
and are also reproached, persecuted, and imprisoned,
with all manner of evil and injustice unrighteously done
and spoken against them by wicked and corrupt men in authority--yet
are these the children and servants of the living God,
and are greatly beloved of Him, and are as dear to Him as the apple of His eye.
His power and presence is with them,
and the time is at hand that the Lord will make their persecutors fall,
and their enemies bow and tremble,
though now they suffer unjustly and are trodden down
as those not deserving a place on the earth.
Yet it is for righteousness sake,
and because they show forth the image of the Father that they suffer,
and not for evil doing; and will not their sufferings lie upon you?
For many hundreds have suffered cruel and great atrocities, and some the loss of life,
though not by, yet in the name of, the protector.
And about a hundred at this present day lie in holes, and dungeons, and prisons,
up and down the nation, some of whom are sick, near unto death,
whose sufferings cry out for vengeance, and the Lord hears the cry.
Therefore save yourselves, and let the innocent be delivered,
and the cruel bonds of oppression be broken,
and the exercise of a pure conscience go free, without persecution.
Then the Lord will turn away His anger, and cease to smite you with His rod;
and He will give you peace, and make you blessed,
if you come to be led by His Spirit into all Truth.

And though these innocent lambs of Christ suffer thus under this present power,
yet are they not enemies to you, but are friends to your persons and families,
and pity you, and love you, and desire well for you in the Lord.
They desire that you may repent and be healed,
and even that your hearts may be opened to receive refreshment to your souls,
and that you may be established in righteousness and truth over all your enemies,
and may not be confounded, nor your posterity brought into reproach,
which is hastening unto you.
And though our love be despised, and we accounted hateful in your sight,
and looked upon with derision, yet we bear all these things in patience,
truly desiring your returning and repentance, and not your destruction.

But if these doleful sufferings of the Lord`'s poor
lambs be continued by this present power,
it will destroy you, and undo you, and break you, and confound you;
and the Lord will not cease to smite you with His rod of sharp rebukes.
Oh, if you but knew how hundreds have and do presently suffer!
How the bodies of some have been tortured by stocks and cruel whippings!
And how some lie sick in stinking holes and dungeons, on the ground,
or upon a little straw at best; ten, or often more, in one chamber together,
and sometimes their own friends not permitted to come to visit them with necessities!
Oh, did your eyes but behold, or your hearts perceive,
the greatness of the cruelty which some of the Lord`'s dear servants,
and your faithful friends, undergo, it would make your hearts ache,
and your spirits tremble!
And all this is done in the name and under the authority of "`Protector.`"
Therefore, how can the Lord not lay it to your charge,
and afflict both him and his family?
He will make you know that there is a God that can do whatever He will,
and that life and death are in His hands,
and all creatures are as clay in the hand of the potter.
He rules in the kingdoms of men, and puts down one, and sets up another,
according to His pleasure.
And so if the love of God is withheld from you, it is because of disobedience to Him,
and transgression.
Therefore, be obedient to Him, and love His ways and judgments,
that He may make you more happy with a crown immortal that never fades away.
And remember once more that the Lord has warned you, by a friend unto you in the Lord.

E+++.+++ Burrough.

Written the 1st day of September, 1658.

Oliver Cromwell was snatched away by death unaware;
however the day before his decease this letter was delivered to his relations.
It was not until the last period of his life that
he named his son Richard to be his successor.
And when death looked him in the face, remorse did not stay behind; for,
according to what Ludlow relates,
Cromwell seemed above all else concerned for the reproaches
which (he said) men would cast upon his name,
in trampling on his ashes when dead.
In this frame of mind he departed this life about two in the afternoon,
on the 3rd of September, at the age of about fifty-five years.

The news of his death being brought to those who had met together to pray for him,
one Sterry stood up and said, "`This is good news;
because if he was of great use to the people of God when he was among us,
now he will be much more so, having ascended to heaven, there to intercede for us!`"
O horrid flattery!
Thus I call it, even if he had been the greatest saint on earth;
which he came far short of, though he was once endued with some eminent virtues.
His dying day was remarkable because a most grievous tempest, not only in England,
but also in the Low Countries,
where trees were torn out of the ground by the violence of the wind,
and many ships were lost.
"`He was,`" says Edward, Earl of Clarendon,
"`one of those persons whom even his enemies could not vilify without praising him.`"
And I have heard impartial men say, that in the beginning of his achievements,
he was indeed an excellent man; but having come to a high station,
he soon lost that zeal for the public welfare by
which at first he seemed to be animated.

The body of the deceased was laid in Somerset House,
in an apartment enlightened with only wax candles, the corpse being richly adorned.

After his death, Richard, eldest son to Oliver,
was proclaimed Protector of the Commonwealth; to whom Edward Burrough wrote a letter,
addressed to: "`Richard Cromwell, chosen to be protector and chief magistrate,
etc.`" wherein he gave him some account of the most cruel sufferings of his friends;
and speaking of the rulers, he says thus:

As for magistracy, it was ordained of God to be a dread, terror and limit to evil-doers,
and to be a defense and praise to all that do well, to condemn the guilty,
and to justify the guiltless.
But the exercise of magistracy at this day in this nation is degenerated,
and some who are in authority are greatly corrupted,
and regard not the just and pure law of God, to judge only thereby.
Instead they oppress the poor by injustice,
and subvert the good laws of God and men to a wrong end and use, abusing authority,
and turning the sword against the righteous, whereby true judgment is turned backward,
and the innocent are made unjustly to suffer for righteousness sake,
through the corruption of men in authority.

And if you but knew what we have suffered in this regard, it would pierce your heart.
For it is frequent among some of the judges and magistrates to commit a man to prison,
and impose a great fine upon him,
and to cast him into a dungeon or hole among thieves and murderers for a long season,
for no other offense or breach of any law, but because he cannot put off his hat to them,
and respect their persons by the hat or by bowing the knee.
And many others suffer who fear God, but for conscience sake cannot swear upon a book,
by kissing it, and laying hands upon it, because Christ says,
"`Swear not at all,`" though they deny not to speak and do the truth in all things,
as in the presence of God and all men.
And many others suffer because they are moved to cry against
sin and declare against the iniquities of the times,
in teachers, rulers, and people, perhaps in a market or steeple-house, or highway,
or other places, as they are moved of God.
And still others, because for conscience sake they cannot pay tithes,
nor give money and wages to maintain a priest, or false teacher,
from whom they receive no profit;
or to maintain a steeple-house where the world worships in vain traditions,
and not in the spirit and power of God.
And many have been taken out of peaceable meetings,
where they were waiting upon the Lord; and some out of their inns or friends`' houses;
and many have been taken on the way, traveling about their lawful occasions,
and some from their very callings and labors.
For these causes, through the envy of wicked men,
and without any just conviction of the breach of any law,
or any lawful trial or examination, have hundreds of just men, being wholly innocent,
been sent to prison, and lain many months, and some for years; or been whipped,
or put in the stocks,
and grievously abused by the cruel executioners of wicked men`'s envy and injustice.
Yes, friend, it is hard to be expressed, and too large to be declared,
how many of the Lord`'s servants have and do suffer great injustice in these nations,
through the abuse of good government,
and degeneration of magistracy from its perfect state and place
whereunto it was ordained of God in the beginning.

This remonstrance, though large and powerful, had not its intended effect;
but persecution continued, without being stopped by him.
For the churchmen fawned upon him,
calling him not only their "`Joshua,`" but the preachers
of Suffolk said in their address to him,
Sol occubuit, nox nulla secuta est.
That is, "`Though our sun has gone down, yet no night has ensued.`"

About this time a paper was given forth called,
"`The Church Faith;`" and G. Fox having gotten a copy of it before it was published,
wrote an answer to it; so that when the book of the church faith appeared,
his answer was also in print.
This so incensed some of the parliament men, that one of them told G. Fox,
they must take him to Smithfield.^
footnote:[Smithfield was a district of central London where many well-known heretics
and political rebels were publicly burnt at the stake over the course of several centuries.]
To this he answered that he "`was over their fires,
and feared them not;`" and further asked,
whether all the people had been without a faith these sixteen hundred years,
that now the priests must make them one?
And since Christ Jesus was the author of the apostles`'s faith,
and of the church`'s faith in the primitive times, and of the martyrs`' faith;
should not all people look unto Him to be the author and finisher of their faith,
and not unto the priests?
Nothing material was given in answer to this,
but the priests called G. Fox`'s friends "`house-creepers,`"
because they met together in houses,
and would not support the priests`' temples.
One major Wiggan, that was present when G. Fox discoursed with the parliament men, said,
"`Christ has taken away the guilt of sin,
but has left the power of sin remaining in us.`"
G+++.+++ Fox told him this was strange doctrine;
for Christ came to destroy the devil and his works, and the power of sin,
and so to cleanse men from sin.

At this time there was a great persecution,
both by imprisonment and by the breaking up of meetings.
Many died in prisons; for the priests spoke evil of the Quakers,
and so kindled the insolence of the rabble not a little,
so that they did not hesitate to throw squibs^
footnote:[A little pipe or hollow cylinder of paper,
filled with gunpowder or combustible matter.]
into the meetings, to cast rotten eggs on those that had met together,
to beat drums and kettles so to make a hideous noise,
and to abuse people most grievously with blows and violent pushes.

One day there being a meeting appointed near London,
the rabble beat and abused about eighty persons who came out of the city to meet there,
tearing their coats and cloaks from off their backs,
and throwing them into ditches and ponds.
The next First-day of the week after this, G. Fox, though at that time very weak,
went there, and preaching with a bible in his hand, showed the rude people their,
and their teachers`' fruits,
and how disagreeable those mad actions were with
the doctrine contained in the Holy Scriptures.
Many of his imprisoned friends were now brought up to London to be tried by the committee,
where sir Henry Vane, being chairman,
would not allow them to come in unless they would put off their hats.
But since many of them had been imprisoned upon "`contempt`"
(as the not putting off hats before magistrates was called),
others said that it must not be expected that they should now comply;
and so through the mediation of some who persuaded H. Vane,
they were at length admitted into the court, where they so well defended their cause,
that several were set at liberty.

Sufferings then growing very sharp,
G+++.+++ Fox wrote the following lines in order to encourage his friends:

My dear friends, everywhere scattered abroad, in prison, or out of prison,

Fear not, because of the reports of sufferings;
let not the evil spies of the good land make you afraid,
if they tell you the walls are high, and that there are Anakims in the land;
for at the blowing of the ram`'s horns the walls of Jericho fell down,
and they who brought the evil report perished in the wilderness.
But dwell in faith, patience, and hope, having the Word of life to keep you,
which is beyond the law; and having the oath of God, His covenant, Christ Jesus,
which divides the waters asunder, and makes them stand in heaps.
Stand firm in this,
and you shall see all things work together for good to those who love God;
and in this you will triumph when sufferings come, whatever sort they may be.
Have your faith, your shield, your helmet, your armor put on,
and so be you will be ready to skip over a mountain, or a wall, or a hill,
and to walk through the deep waters, though they be heaps upon heaps.
For the evil spies of the good land may preach up hardness,
but Caleb (which signifies a heart) and Joshua (a savior) will triumph over all.

G+++.+++ Fox

There was at that time great discord among those that were at the helm of government,
and G. Fox relates that he then foresaw the king`'s coming in again;
and that therefore when some forward spirits who frequented the meetings of his friends,
desired to purchase Somerset House to keep meetings in, he dissuaded them from it.
There came also a woman to him,
who (as she said) had received a revelation concerning the
restoring of king Charles three years before he came in,
and said she must go to him to declare it.
But G. Fox advised her to keep this revelation to herself,
since if she went with such a message, it would have been counted treason.

How the corpse of Oliver Cromwell was laid in Somerset
House to be seen has been described already;
but afterwards, an effigy or image of him lying there in that state,
was accompanied with trumpeters, who sounded over the said image.
This vanity so grieved G. Fox, that he wrote to those responsible saying, "`Oh friends,
what are you doing!
And what do you mean to sound trumpets before an image?
Will not all sober people think you are mad?`"
Sometime after this, the funeral of Oliver Cromwell was solemnized with very great pomp,
which was not at all agreeable to the condition he was once in;
for there was a time when he would have abhorred such idolatrous
honor as was now paid to his image.

On the day of this pompous funeral, which was the 23rd of November,
it happened that Edward Burrough came riding from Kingston into London,
not knowing anything of what was happening there.
As he entered at Charing-cross,
he beheld a great multitude of people thronging exceedingly,
the streets being filled as far as he could see,
and an abundance of people gazing at the windows, and upon the balconies and house tops.
There were also guards of horsemen and footmen that stopped his horse,
and he was told that he might not pass that way.
Yet he did not know what was the matter;
but at length he perceived that Cromwell`'s image, richly adorned,
was to be carried that way towards Westminster.
The consideration of this was like an arrow which pierced his breast;
and because of this idolatry, he felt such a fire kindled in him, that he was,
as it were, filled with the indignation of the Lord, whose fury ran through him to cry,
"`Plagues, plagues, and vengeance against the authors of this abomination.`"
And considering that all this sinful idolatry was concerning the funeral of Oliver Cromwell,
Burrough said within himself: "`Alas, for him,
who was once a great instrument in the hand of the Lord,
to break down many idolatrous images!
Did not the Lord once stir up his heart against all such things?
And did not his children, officers, soldiers and army, once pull down all the images,
crosses and all such popish stuff, wherever they met with it?
What grievous and abominable work is this?
Have they now made a costly image of him?
And are such as were once his soldiers now guarding it, and watching over it,
and his children and officers following it,
and a multitude of the inhabitants of London wondering and gazing after an image of him?
This is sad and a great pity!
What a change has taken place in so short a time!`"

Now since the persecution of E. Burrough`'s friends (notwithstanding
all he had written to Richard Cromwell) did not cease,
and finding that all exhortations and warnings had been rejected,
in the month called December,
E+++.+++ Burrough wrote the following lines to Richard and his council:

To the Protector and his Council:

The Lord God will shortly make you know that we are His people;
though we are accounted as sheep for the slaughter;
yet our King of righteousness will break you to pieces,
if you harden your hearts and repent not.
And though His love will not draw you,
neither will the gentle leadings of our God have any place in you,
yet His judgments shall awaken you,
and His heavy hand of indignation shall lie upon your consciences,
and you will be scattered and broken to pieces.

E+++.+++ Burrough

How soon this prediction was fulfilled, we shall see in the next year;
for it was but a few months after the delivering of this letter,
when Richard laid down the government.

In the meantime, we will again take a view of the persecution in New England.
There was, as has been said already,
a fine imposed of five shillings a week to be paid for not coming to church,
as it was called.
And thus, from time to time,
occasion was found to use cruelty against the inhabitants of New England,
though they were not of those called Quakers who came from abroad.
William Shattock, a shoemaker at Boston,
being on a First-day of the week found in his house,
instead of coming to the public worship, was hauled to the house of correction.
Here, at his first entrance, he was cruelly whipped, and then kept to work,
while his wife and innocent children were impoverished because of his absence.
In the meantime the deputy-governor, Richard Bellingham,
did not hesitate to say to William`'s wife, that since he was poor,
and could not pay five shillings a week for not coming to church,
they would continue him in prison.
Thus was verified that saying of Solomon, "`cruel are the mercies of the wicked.`"
Bellingham also endeavored to persuade this woman that what her husband had done,
was in order to be rid of her, and therefore advised her to disown him.
Now these persecutors began to be abundantly busy; for taking away goods,
and cruel whippings became almost a daily work,
which was performed without regard of age or sex;
to relate all of which would exceed my limits.

Two women, named Sarah Gibbons, and Dorothy Waugh, having come to Boston,
and spoken a few words in the public meeting-place after the lecture had ended,
were brought to the house of correction, where the three days before they were whipped,
and the three days after, they were kept from food,
though they had offered to pay for it.
And when Sarah afterward asked the governor, John Endicot,
whether this was justice or equity; adding,
that by this all might see that God was with them,
that they were thus preserved without food; and if they perished,
their blood would fall heavy on those that were the occasion of it; he answered,
that it mattered not to him.

Not long after, Hored Gardner, an inhabitant of Newport, in Rhode Island,
came to Weymouth with her nursing babe, and a girl to carry it.
From this place, for being a Quaker, she was hurried to Boston,
where both she and the girl were whipped with a three-fold knotted whip.
After the whipping,
the woman kneeled down and prayed the Lord to forgive those persecutors,
which so reached a woman that stood by, that she said,
"`Surely she could not have done this, if it had not been by the Spirit of the Lord.`"

But when should I be done,
if I would describe all the whippings inflicted upon
the Quakers (so called) in those parts!
For now a law was made, which furnished continual work to the persecutors there.
The contents thereof were,
that whoever of the inhabitants should directly or indirectly
cause any of the Quakers to come into that jurisdiction,
he should forfeit a hundred pounds and be committed to prison,
there to remain till the penalty should be fully paid.
And whoever should accommodate them, knowing them to be Quakers,
should forfeit forty shillings for every hour`'s accommodation or concealment,
and then be committed to prison till the forfeiture should be fully paid and satisfied.
And further, that all and every one of those people that should arise among them there,
should be dealt with and suffer the same punishment as the
laws provided for those that came in from abroad;
namely, that for the first offense, if a male, one of his ears should be cut off,
and be kept at work in the house of correction till
he should be sent away on his own charge.
For the second offense, the other ear should be cut off,
and he be kept in the house of correction as aforesaid.
If a woman, they were to be severely whipped, and kept as aforesaid, just as the male,
for the first offense.
For the second offense they were to be dealt with as at first.
And for the third offense,
both male and female should have their tongues bored through with a hot iron,
and be kept in the house of correction,
being put to work till they be sent away on their own charge.

In the latter part of the Fifth month, it came to pass,
that William Brend and William Leddra, having been at Salem, came to Newbury.
There, at the house of one Robert Adams,
they had a conference with the priest in the presence of captain Gerish,
who had promised that they should not suffer; but after the conference had ended,
the captain would not let them go unless they promised presently to depart from the town.
Being reluctant to comply with this condition, they continued on their way,
when they were sent for, and captain Gerish riding after them, commanded them to return;
which they refusing, he compelled them to do so, and sent them with a constable to Salem.
There, being brought before the magistrates, they were asked whether they were Quakers;
to which they answered, that they were such that were in scorn called so.
Next it was objected against them that they maintained dangerous errors.
Upon asking what these errors were,
it was told them that they not only denied that Christ
at Jerusalem had suffered upon the cross,
but that they also denied the Holy Scriptures.
This they boldly contradicted,
and said they acknowledged no other Jesus than He that had suffered death at Jerusalem,
and that they also acknowledged the Scriptures.

Now, although nothing could be objected against this,
yet they were carried to the house of correction, as such who,
according to the law made at Boston, were not permitted to come into those parts.
Some days after this they were carried to Boston,
where in the next month they were brought into the house of correction to work there.
But being unwilling to submit to this unreasonable demand, the jailer,
who sought his profit from the work of his prisoners, would not give them food,
though they offered to pay for it.
But he told them, it was not their money, but their labor he desired.
Thus he kept them five days without food,
and with a three-corded whip gave them each twenty blows.
An hour after this he told them they might go out,
if they would pay the marshal who was to lead them out of the country.
They judging it very unreasonable to pay money for being banished, refused to do so,
but yet said that if the prison-door was set open, they would willingly go away.

The next day the jailor came to William Brend, a man advanced in years,
and put him in irons,
with his neck and heels so close together that there was no more
room left between them than for the lock that fastened them.
Thus he kept them from five in the morning till after nine at night,
being the space of sixteen hours.
The next morning he brought him to the mill to work, but Brend refusing,
the jailer took a pitched rope about an inch thick,
and gave him twenty blows over his back and arms, with as much force as he could,
so that the rope untwisted.
Then, going away, he came again with another rope that was thicker and stronger,
and told Brend, that he would cause him to bow to the law of the country,
and make him work.
Brend judged this not only unreasonable in the highest degree,
since he had committed no evil, but he was then altogether unable to work;
for he now had no strength for lack of food, having been kept five days without eating,
and also whipped, and now thus unmercifully beaten with a rope.
But this inhuman jailer relented not,
but began to beat him anew with his pitched rope on this already bruised body;
and foaming at his mouth like a madman,
with violence he laid ninety-seven blows more upon him,
as other prisoners that beheld it with compassion, have related.
And if his strength, and his rope had not failed him, he would have laid on more;
for he threatened also to give him the next morning just as many blows more.
But a higher power, who sets limits even to the raging sea, and has said,
"`hitherto you shall come, but no further,`" also limited this merciless fellow;
who was yet impudently bold enough to say his morning prayers.

To what a most terrible condition these blows brought the body of Brend,
who because of the great heat of the weather, had nothing but a thin gown over his shirt,
may easily be conceived.
His back and arms were bruised and black,
and the blood hung down as in bags under his arms;
and so thoroughly was his flesh beaten,
that the sign of a particular blow could not be seen; for all had become as a jelly.
His body being thus cruelly tortured, he lay down upon the boards, so extremely weakened,
that his natural parts began to decay, and his strength quite failing,
his body turned cold.
There seemed, as it were, a struggle between life and death.
His senses were stopped, and he had for some time neither ability to see, feel, or hear,
till at length a divine power prevailed, life broke through death,
and the breath of the Lord was breathed into his nostrils.

Now, the noise of this cruelty spread among the people in the town,
and caused such a cry,
that the governor sent his surgeon to the prison to see what might be done.
But the surgeon found the body of Brend in such a deplorable condition, that,
as one without hope,
he said his flesh would rot from off his bones before
the bruised parts could be brought to heal.
This so exasperated the people, that the magistrates, to prevent a tumult,
set up a paper on their meetinghouse door, and up and down the streets, as it were,
to show their dislike of this abominable, and most barbarous cruelty;
saying that the jailer should be dealt withal the next court.
But this paper was soon taken down again upon the instigation of the high-priest,
John Norton, who having from the beginning been a fierce promoter of the persecution,
now did not hesitate to say,
"`William Brend endeavored to beat our gospel ordinances black and blue;
if he then has been beaten black and blue, it is but justice upon him;
and I will appear on behalf of the one that did so.`"
It is therefore not much to be wondered at, that these exacting and bigoted magistrates,
who desired to be looked upon to be eminent for piety,
were so cruel in their persecuting,
since their chief teacher thus wickedly encouraged them to it.

In the meantime, it pleased God, even miraculously, to heal William Brend,
and to keep him alive.
But it seemed as if the hearts of these persecutors were even more hardened by this;
for to show themselves obedient followers of their teacher,
they made an order that if the Quakers that were in his custody refused to work,
the jailor should whip them twice a week--the first time with ten lashes,
the next time with fifteen, and so at each time with three more, until they would work.
This was performed on four persons, two of whom were William Leddra and John Rouse,
who will be mentioned more hereafter.
And to keep the passionate jailer within due bounds,
it was ordered that each time he should seek two constables to witness the execution.
But how little moderation was truly intended by this order,
and that this was more like a jest,
may appear by that fact that the jailer laid fifteen lashes
apiece on the said persons for their first refusal to work,
and so added five more stripes to this number often.

It happened about this time, that some of the people called Quakers that lived there,
being brought before the magistrates,
demanded to know how it was they identified a Quaker; to which Simon Broad-street,
one of the magistrates, answered, "`You are one, for you came in with your hat on.`"
This made the other reply, that it was a horrible thing to make such cruel laws,
so as to whip, cut off ears, and bore through the tongue, for not putting off the hat.
Then one on the bench said that the Quakers held forth blasphemies at their meetings.
To this,
one of the others desired him to make it appear what blasphemies they held forth,
and if it were so, then they might be convinced.
And he further added,
that they should do well to send some men to their meetings that they might hear,
and give account of what was done and spoken there;
and not pass judgment upon something they knew not.
"`But,`" said major-general Denison, "`if you meet together, and say anything at all,
we may conclude that you speak blasphemy.`"
A very strange syllogism indeed!
No better was the argument of Charles Chauncy, chief teacher at the university,
who in a sermon at Boston, argued thus to prove persecution lawful:
"`Suppose you should catch six wolves in a trap,
and you cannot prove that they killed either sheep or lambs;
and now that you have them they will neither bark nor bite.
Yet because they have the plain marks of wolves, you must therefore knock them down.`"
A base expression, thus to compare a man to a beast; for God said in plain terms to Noah,
"`Whoever sheds man`'s blood, by man shall his blood be shed.`"
But these persecutors thought there was weight enough
in this argument to call the Quakers wolves;
and seeing one who did not put off his hat to men,
they considered it sufficient reason to say, "`Knock him down; it is a wolf.`"

And if it was not the hat, then they found fault with something else;
for at Salem twelve persons were fined forty pounds
nineteen shillings for not coming to church;
and from others much money was extorted because their
wives absented themselves from the public worship.
William Marston, of Hampton, was fined ten pounds for possessing two books in his house,
namely, John Lilburn`'s Resurrection, and William Dewsbury`'s Mighty Day of the Lord.
Thus these people did whatever they desired,
without any regard to the laws in Old England:
and when at one time some prisoners appealed to the laws of England,
the governor John Endicot and his deputy Bellingham, cried out, "`No appeal to England!
No appeal to England.`"
Indeed they seemed to fear no repercussions for what they did to the Quakers,
according to what major-general Denison said in open court,
"`This year you will go and complain to the parliament,
the next year they will send some men to see how things go,
and in the third year the government will be changed.`"
Thus, not at all caring for Old England,
they denied the prisoners their request of being
tried according to the laws of that realm,
by a jury.
And seeing that the rulers dealt thus arbitrarily,
the jailer of the house of correction did the same;
for when some of his prisoners showed themselves willing to work,
provided that their families should receive something of the gain,
the jailor would not allow this,
unless they paid him eight-pence for every twelve-pence they gained;
and when they refused this, he resorted to the whipping-post.

But to go on; in the foregoing year,
mention was made of John Copeland and Christopher Holder.
These men coming in the sixth month to Dedham, lodged there one night; but the next day,
they were taken up by a constable and carried to Boston,
where being brought before the governor, he said in a rage,
"`You shall surely have your ears cut off.`"
Not long after this, John Rouse came again to Boston,
and was also taken up and committed to prison.
On the 17th of September, he, with Christopher Holder and John Copeland,
were brought before the magistrates in the court,
where the deputy-governor told them that,
they having come there again in contempt of the magistrates and ministers,
in order to seduce the people,
might know that whatever befell them--whether the loss of their ears,
or of their lives--their blood would be upon their own heads.
They denying this, and saying that the Lord had sent them here, the governor, Endicot,
said, "`You are greater enemies to us than those that come openly;
since under a pretense of peace, you come to poison the people.`"
Being asked for proof that the Lord had sent them, they replied,
that it was some kind of proof that the Lord had sent them,
seeing they received the kind of reception that Christ had
told His disciples would be given to them for His name sake,
namely, whipping, etc.
To this, major-general Denison said, "`Then when malefactors are whipped,
they suffer for Christ`'s sake.`"
Then John Rouse, whose father was a lieutenant-colonel in Barbados, said,
"`If we were evil-doers,
the judgments of God would be heavier upon us than what we suffer from you.`"
To which major Denison replied, "`Mr. Rouse, (for so I may call you,
having heard your father is a gentleman),
what judgment of God do you think could be greater than that which is now upon you:
to be driven from your father`'s house,
and to run about here as a vagabond with a company
of deceivers?...except you look for a noose?`"
To this Rouse said, "`I was not driven from my father`'s house,
but in obedience to the Lord I left it;
and when the Lord shall have cleared me of this land, I shall return to it again.`"
Then Endicot called to the secretary to read the law,
who thereupon read this clause in it: that if any who had suffered by the law,
should presume to return again, they should have one of their ears cut off.
Some more words were spoken, and among the rest, Endicot said,
"`The Quakers have nothing by which to prove their
commission but the spirit that is within them,
and that is the devil.`"
And when one of the prisoners said, "`We have seen some of your laws,
that have many scriptures written in the margin;
but what example do you have in Scripture for cutting off ears?`"
Endicot asked, "`What Scripture is there for hanging?`"
To which Denison said scoffingly, "`Yes, they should be crucified.`"
Then Endicot called the three prisoners by name, and said in a great passion,
"`It is the sentence of the court that each of you
have his right ear cut off by the hangman.`"
They were then carried to the prison, and on the 16th of September,
the Marshal`'s deputy came there, letting as many come in as he thought fit;
and when the doors were shut and locked, the said marshal read the following order:

To the marshal-general, or his deputy: you are to take with you the executioner,
and repair to the house of correction,
and there see him cut off the right ears of John Copeland, Christopher Holder,
and John Rouse, Quakers; in execution of the sentence of the court of assistants,
for the breach of the law, entitled Quakers.

Edward Rawson, Secretary.

The prisoners were then brought into another room, where John Rouse said to the marshal,
"`We have appealed to the chief magistrate of England.`"
To which the marshal answered, he had nothing to do with that.
C+++.+++ Holder said, "`Such an execution as this should be done publicly, and not in private;
for this is contrary to the laws of England.`"
But captain Oliver replied, "`We do it in private to keep you from tattling.`"
Then the executioner took C. Holder, and when he had turned aside his hair,
and was going to cut off his ear, the marshal turned his back on him,
which made John Rouse say, "`Turn around and see it; for so was your order.`"
The marshal then, though filled with fear, turned about and said, "`Yes, yes,
let us look on it.`"
Rouse, who was more undaunted than his persecutor, suffered the same,
as well as the third, and then they said, "`Those that do it ignorantly,
we desire from our hearts that the Lord forgive them;
but for those who do it maliciously, let our blood be upon their head;
and such shall know in the day of account,
that every drop of our blood shall be as heavy upon them as a millstone.`"
Afterwards these three persons were whipped again;
but this practice having become so common in New England as if it was but play,
I will not detain my reader with it.

Persecution having now come to the cutting off of ears, did not stop there,
but went higher, and did not cease before it came to the taking away of lives.
But to accomplish this proved very difficult;
for there were many honest people who abhorred such cruelty.
Yet John Norton, and the other priests,
petitioned the magistrates to cause the court to make a law to banish the Quakers,
upon pain of death.
This gave encouragement to the magistrates,
for since it was the churchmen who pushed forward this wicked business,
no scruple was made to go on with this bloody work.
The court of magistrates voted this law to be put in execution by a country court,
which was made up of three magistrates,
the majority of which might hang a person at pleasure, without trial by a jury;
a thing not heard of in Old England,
but one that served the purpose of Norton and his fellow preachers.

Now the court where this law was approved consisted of twenty-five persons;
and when it was put to the vote it was carried in the affirmative,
the speaker and eleven others being on the negative,
but thirteen were on the affirmative, so that one vote carried it.
This so troubled one Wozel when he heard it, having through illness been absent,
that he came to the court,
and weeping for grief that his absence should occasion such a law to pass, said,
if he had known, he would have crept there upon his knees,
rather than allow it to have passed.
But what he said proved in vain; for they had now passed the Rubicon,^
footnote:[i.e. passed the crossroads, or point of no return.]
and what had been eagerly desired was now obtained.
Yet there was a great disagreement in the court,
and the twelve that had voted in the negative resolved
to enter their dissents to that law;
which the others seeing, and believing that so many difficulties would weaken their law,
they admitted this addition: that they would be tried by a special jury;
though a standing law of the country said that none could be sentenced
to death and banishment but by a special jury and a court of assistants,
and that such a court must consist of seven magistrates at the least.
But it was now resolved to prosecute the Quakers to death; and all their trial,
when it came to it, was only a question of whether or not they were Quakers,
which they judged by their coming into court with hats on,
and whether they had been formerly banished out of the country.
Now, in order to enter upon this bloody business,
the following act was made at a general court, held at Boston, the 20th of October,
in this year, 1658.

Act made at a general court, held at Boston, the 20th of October, 1658.

Whereas there is a pernicious sect, (commonly called Quakers) lately arisen,
who by word and writing have published and maintained many dangerous and horrid tenets,
and do take upon them to change and alter the received laudable customs of our nation,
in giving civil respect to equals, or reverence to superiors,
whose actions tend to undermine the civil government,
and also to destroy the order of the churches,
by denying all established forms of worship,
and by withdrawing from orderly church-fellowship,
allowed and approved by all orthodox professors of the Truth, and instead thereof,
and in opposition thereunto, frequently meeting by themselves,
insinuating themselves into the minds of the simple,
or such as are least inclined to the order and government of church and commonwealth,
whereby many of our inhabitants have been infected,
notwithstanding all former laws made upon the experience
of their arrogant and bold obtrusions,
to disseminate their principles among us, prohibiting their coming in this jurisdiction,
they have not been deterred from their impetuous attempts to undermine our peace,
and hazard our ruin.

For prevention thereof, this court does order and enact, that every person, or persons,
of the cursed sect of the Quakers, who is not an inhabitant of,
but is found within this jurisdiction, shall be apprehended without warrant,
where no magistrate is at hand, by any constable, commissioner, or select man,
and conveyed from constable to constable, to the next magistrate,
who shall commit the said person to close prison, there to remain, without bail,
unto the next court of assistants, where they shall have a legal trial.
And being convicted to be of the sect of the Quakers,
these shall be sentenced to be banished upon pain of death.
And every inhabitant of this jurisdiction, being convicted to be of the aforesaid sect,
either by taking up, publishing, or defending the horrid opinions of the Quakers,
or stirring up mutiny, sedition, or rebellion against the government,
or by taking up their absurd and destructive practices, namely,
denying civil respect to equals and superiors,
and withdrawing from our church assemblies,
and instead thereof frequent meetings of their own, in opposition to our church order;
or by adhering to, or approving of any known Quaker,
and the tenets and practices of the Quakers,
that are opposite to the orthodox received opinions of the godly,
and endeavoring to disaffect others to civil government, and church orders,
or condemning the practice and proceedings of this court against the Quakers,
manifesting thereby their complying with those whose design
is to overthrow the order established in church and state,
every such person, upon conviction before the said court of assistants,
in manner as aforesaid, shall be committed to close prison for one month, and then,
unless they choose voluntarily to depart this jurisdiction,
shall give bond for their good behavior, and appear at the next court.
And continuing obstinate, and refusing to retract and reform the aforesaid opinions,
they shall be sentenced to banishment upon pain of death; and any one magistrate,
upon information given him of any such person, shall cause him to be apprehended,
and shall commit any such person to prison, according to his discretion,
until he come to trial, as aforesaid.

Here ends this sanguinary act,
being more similar to the decrees of the Spanish Inquisition,
than to the laws of a reformed Christian magistracy, consisting of such who,
in order to shun persecution themselves (which was but a
small fine for not frequenting the public worship),
had left Old England.
This act was answered by Francis Howgill, and the said answer published in print,
wherein was plainly shown that it spoke the language
of the ancient persecuting Jews and heathen.
In what follows, we shall see the bloody execution of it upon some persons.
