== Chapter IX

[.section-date]
1659--1660

In the forepart of the year 1659, there was great discord,
and several factions appeared among the people in England;
for some adhered to the protector Richard,
and others to the chief members of the long parliament;
and the royalists were also a party.
G+++.+++ Fox being under a concern lest some young or raw people,
who sometimes came among his friends,
might be drawn into some of these various interests,
wrote an epistle warning such to be careful, and not at all to meddle with any plotting,
but to consider that their warfare was a spiritual one,
and not at all needing the use of carnal weapons.

About this time William Caton came again into Holland,
and finding at Amsterdam some malicious people who endeavored
to bring his fellow-believers there into trouble,
and to stir up the mob against them so that the magistrates
might take occasion to look upon the Quakers as rioters,
advised those of that persuasion to be circumspect,
and so to avoid as much as possible the impending storm.
In order thereto,
it was thought fit that their religious meetings on the first days
of the week should not always be kept in one place,
but sometimes in one, and at other times in another house.
Sometimes a meeting was kept in an alley at the town wall near the Regulars Gate,
where several English people dwelt (from which it was called the English Alley,
and has that name still).
To this place came a very rude company, who committed acts of great insolence.
The time before when William Caton was in Holland,
he met with an extraordinary rude encounter at the said place,
insomuch that he seemed in danger of his life; for some wicked people,
not daring to execute their intentions in the house where he was,
pushed him out of doors; but then a woman pulled him into her house where he was safe,
though at first he knew not whether he was among friends or foes.
I still well remember this fact,
being at that time with my parents in the said disturbed meeting.

Now Caton, being a discreet and judicious person,
and perceiving that some of his friends there had more of a rash zeal than true wisdom,
advised the most moderate of them often to change meeting-places.
In the beginning a meeting was kept now and then in St. John`'s street (so called);
and afterwards on Eland`'s Graff, in an alley, at the house of one Richard Langham;
and also on the Angelier`'s Graff, in the house of my father;
and some time after in the English Alley above said;
and also outside the town near the river Amstel, in Cooper`'s Lane;
from which the meeting was removed in the forepart of this year,
(if my memory does not deceive me) into the Dyers`' Lane.

After some stay in Holland, William Caton returned again to England.
I think it was in this year that William Ames went into Germany,
where having come into the Palatinate, he went to Heidelberg,
and came to the court of the prince elector, Charles Lodowick, who treated him kindly,
even at his own table, and seemed not to take offense at Ames`'s hat, which he kept on,
though the lords and others that were in the company stood bareheaded.
The baron of Helmont, who also was at that court, would often tell afterwards that Ames,
walking once with his hat on next to the prince in his garden,
the courtiers asked the prince whether they should question Ames about this incivility;
but the prince said, "`No, for I did expect that.`"
At another time the prince made his chaplain and Ames both dine with him,
with the purpose (as it seemed) that Ames, whom he knew to be a bold man,
might find occasion to reprove his chaplain;
for at meals this chaplain allowed his jester to come,
who played his tricks while the chaplain remained silent.
But Ames, who loved sobriety, and was averse to such jesting,
indeed took occasion from here to reprove such vain actions;
but chiefly he aimed his reproof at the chaplain, who,
because of his silence at the lewd behavior of the jester, was compared to a silent dog;
which seemed to please the prince.

Now while William Ames was in the Palatinate,
he became acquainted with the Baptists at Kriesheim, a town not far from Worms;
and among those people he found such an entrance,
that some of the families who received the doctrine
he preached bore a public testimony for it there,
and so continued till the settlement of Pennsylvania in America,^
footnote:[In the mid 1680`'s.]
when they unanimously went there,
not (as it seemed) without a remarkable direction of Providence; for not long after this,
a war ensued in Germany, and the Palatinate was altogether laid waste by the French,
and thousands of people were bereft of their possessions and reduced to poverty.

But to return to Ames, when some in the Palatinate began to give an ear to his preaching,
a fine was inflicted upon those that gave him entertainment: but the prince elector,
being informed of this, revoked the fine;
and though some from the consistory did send for Ames,
the prince generously ordered them not to meddle with him.
The prince`'s sister also behaved herself very kindly towards him,
and received his exhortations favorably.

A year after this, Ames came again into the Palatinate with John Higgins,
and visiting the prince elector,
he heard from the captain of the prince`'s guard
that the prince was glad of Ames`'s return there.
Awhile after this, Higgins delivered a book of G. Fox,
with a letter of Ames to the said prince, who was so well pleased with it,
that he bade Higgins to thank Ames on his behalf,
saying also that he took the coming of Ames and Higgins to him and his family very kindly,
and really believed that what they spoke was in love to their souls.

Several years after this,
some others of Ames`'s friends from England visited the aforesaid prince elector,
and he always received them kindly.
William Ames, who was several times in Germany, came not only to Hamburg,
but travelled also through Bohemia to Dantzic, and from there to Poland.
At Hamburg and Dantzic he met with some who received the Truth that he preached;
but in Poland the people were too rude and haughty to get entrance among them.

In the forepart of this year, W. Ames being at Rotterdam in Holland,
was confined there in Bedlam;^
footnote:[An insane asylum.]
which having made a great a noise, I will give a brief relation of it here.
At Moordrecht, a village near Gouda, lived at that time one Martin Martinson,
a cooper by trade.
This man, having approved the doctrine preached by Ames at Rotterdam and elsewhere,
began to assert it as truth;
and seeing that he and some of his sober neighbors at times kept a meeting in his house,
this caused a great stir in the town,
insomuch that sometimes he suffered rude treatment from the people.
Ames coming there once, and attending a meeting in Martin`'s house,
great insolence was committed by the wicked rabble.
And going from there to pass over the water to Gouwerek,
he was followed by a multitude of riotous people, both young and old,
with a hideous cry of "`Quake, Quake,
Quake!`" and was pelted with stones and clods of dirt until
he came to the boat that carried him over.

Hearing the noise,
the preacher of Gouwerek came to the boat and asked what the matter was,
why the people made such a great noise?
To this Ames answered, "`It seems the people have not been taught better.`"
To which the preacher returned,
"`They do not usually make such a commotion against honest people;
but I believe you to be a deceiving wolf, that comes among the sheep to seduce them,
and therefore they cry out so.`"
"`Prove this,`" replied Ames.
"`I do not know you,`" said the preacher.
"`Then learn`" replied Ames, "`better manners than to call one you do not know,
a wolf and a deceiver.`"
Continuing on his way, he shortly after wrote from Rotterdam to Martin Martinson,
and desired him to go to the preacher,
and request him to appoint a time to prove that Ames was a deceiving wolf.
But to this the preacher showed himself reluctant; yet, in order to be rid of Martin,
he said at length, "`Come, I will prove it presently.`"
But Martin replied, "`I have not come for that;
but this must be done before William Ames;`" and insisting thereupon, the preacher said,
"`Well, let him come next Sunday before noon, after the sermon;
then I will prove it publicly before all the people.`"

Of this Martin sent word to Ames; but things were so managed,
that this projected proof was quashed:
for the preacher of Gouwerek went to his colleague at Moordrecht,
and consulted with him what to do in the case;
and Ames having come to Moordrecht on the first day of the month called March,
and the last of the week, though it was late at night, was seen and known by some,
who committed much violence upon the house of Martin where Ames had entered.
The next day it was reported that some of the sheriff`'s men of
Gouda had come to Gouwerek to apprehend Ames when he came there;
and at Moordrecht the mayor`'s men came for the same purpose;
and so they took Ames prisoner, and carried him to Rotterdam,
where he was locked up in Bedlam as a madman.
And a week after, Martin, for having kept meetings at his house,
where not more than eight persons had come together,
was also taken prisoner by the mayor`'s men in his house, and carried to Rotterdam,
where he was locked up with Ames.
Who the instigators of this business were is plain enough, though I do not mention them.

After Ames had been a little more than three weeks in Bedlam,
the deputy-governor of the house, on the 27th of the month,
came to him and Martin at night and said, "`If I was in your place, I would go out.`"
This made Ames ask whether he would permit them to do so?
To this the deputy answered that he would not hinder them.
Then Ames replied, "`I will not be reputed as one that broke out of prison.`"
To which the deputy replied, "`No, why should you be reputed so?
You may go out freely; all is unlocked, and the door will stand open for you;
for the governors are not of the mind that you should stay here.`"
Then Ames said, "`Well then, I intend to go out tomorrow.`"
The next day Martin`'s wife came to see her husband,
but the deputy told her that he had an order in writing from the mayor that,
rather than to let Martin`'s wife come to him, he would let him and Ames go out together.
Thus they were both let out that morning, it being the 28th of the month.
But they stayed at Rotterdam,
intending not to depart the town before they had
given notice to the mayor of their being let out,
lest occasion might be given for saying that they had broken out of prison.
And it was not without reason they were so cautious; for the next day, in the morning,
the deputy came to them and said, "`I desire that you will not bring me into trouble,
for I am an ancient man; and the mayor has been with me, and asked for you;
to which I answered, that you had gone out; but he took this very ill.
I desire, therefore, that you would say to him that you went out without my knowledge.`"
But this was not to be expected from Ames, whom I knew so well,
that I truly believe that he would rather have died than to have spoken a lie;
for in this case he was doubtless of the same mind as Christian
Languedul (an uncle to my grandmother on the mother`'s side) who,
when at Antwerp, he, with other martyrs, was led to the stake to be burnt,
and cried out undauntedly, "`If we had but once told a lie, we might have escaped this!`"
But to return to Ames, he told the deputy,
that he himself intended to go and speak with the mayor;
and if he was displeased at their going out,
he might put them in again where they had been;
for they would not have the name of prison-breakers.

Then they both went to the mayor, and told him in what manner they had come out,
saying also that they would not have it be said that they prison-breakers.
"`That name,`" said the mayor, "`you would have had, if you had departed the town;
for the deputy has told me that you got out by breaking a window.`"
After some other words were exchanged, he further said,
"`I have nothing to object against your life and conduct,
having heard nothing concerning you but a good report;
neither do I seek to persecute you.
But would you be willing to return to Bedlam?`"
Ames answered, "`Here we stand before you; you may do with us according to your pleasure.
And if you desire us to return there, we will do so.`"
The mayor signifying that this was his desire,
said that they might go and walk in the gardens till another order came.
So, on the 31st of the month, they were locked up again, each in a hole by himself.
Now Ames acquainted the deputy that he heard from the mayor,
that he had been informed by him that they had gone out by breaking a window.
But the deputy denied to have said so.
They were detained there yet some time, and were frequently visited,
and this often by such as sought nothing but to scoff at them.
Among these a certain clergyman who went as far as to say
that Ames was a deceiver because he wore pewter buttons,
in order to make people believe they were silver ones.
While Ames was confined here, he wrote some papers which he afterwards published,
and among these was a reply to an answer of one Jacob Koelman,
to eighty-three queries given forth by the said Ames.
At last being set at liberty, he travelled to Germany, as has been said before,
and from there went back to his native country,
and after some time returned again into Holland, as did also William Caton.

But now I turn again to England,
where an account was published in print of the sufferings of the people called Quakers,
which being offered to the parliament, was delivered to the speaker, Thomas Bampfield.
This contained a relation of more than one hundred and forty persons,
all distinguished by their names, who for keeping meetings, refusing to swear,
not putting off their hats, not paying of tithes,
or for traveling up and down the country, had been taken up and imprisoned.
Many had also been deprived of their goods,
and twenty-one of these died either by sickness in prison, or by violent abuses.
Among these was one Richard Sale, of West Chester, who being a constable,
had a minister of the people called Quakers brought before him with a pass as a vagabond,
whose conduct so convinced the constable, that he gave him his liberty.
And because the said Sale came to see how both priests and people were exceedingly darkened,
he entered upon an extraordinary act,
to show them by a sign that they needed to be enlightened; namely,
he came in the daytime with a lantern and a burning candle into the steeple-house,
during the time of the sermon.
But this was resented to such a high degree,
that by order of the mayor he was put into prison,
and thrust into a hole called Little Ease.
This hole was so narrow, that it could not well receive his body;
but he was thrust in with such violence that his body was bruised, and he spit up blood.
Shortly after this he grew very sick;
and his body swelling (occasioned by the squeezing
it into the hole) he died in great pain.

In the before-mentioned printed account it was also shown that in the last six years,
about two thousand persons, for being Quakers, had suffered in their body and goods.
To this was added a paper,
signed by more than one hundred and sixty persons (several of whom I knew),
whereby they offered to the parliament to put themselves in the stead of their
brethren who were confined either in prisons or houses of correction,
or in dungeons, some being fettered, and others lying sick only on a little straw;
wherefore they declared themselves ready to change places with them out of true love,
that so they might go out, and not die by hardship, as many had done already;
to prevent which,
they were willing to take upon themselves the sufferings of their brethren,
and lay down their lives for them.
Under their names they added, "`If we had been of Esau`'s race,
we should have fainted before this time; and if we had been of Cain`'s progeny,
we should have fought with his weapons.
But this never was,
neither is it now the way of the righteous and chosen from the foundation of the world,
of which we are.`"
It was in the month called April, that this paper was delivered to the parliament,
but I do not find that this offer was accepted,
nor that anything was done for releasing the imprisoned.

About this time also Edward Burrough published a paper,
containing a very remarkable prediction of what followed the next year,
when king Charles the Second was placed on the throne.
In it he says, that as he was traveling in Warwickshire in the 1st month,
his meditations being upon the Lord,
and considering what unjust and woeful sufferings had been
inflicted upon the Lord`'s people within these few years,
a cry went through him, "`The Lord will be avenged,
the Lord will be avenged upon His enemies, and He will avenge the cause of His people.`"
This cry struck him deeply,
and by it his heart was even broken and his spirit was melted before the Lord,
and it seemed that it was said to him, "`Write unto the rulers,
and yet once more warn them of that recompense, and of that indignation,
which is at hand upon them, even a just recompense for all their deeds.
As they have done, even so shall it be done to them.
As they have sought to destroy the generation of the righteous,
even so shall they be destroyed from off the face of the earth.
As they have unjustly judged and condemned the innocent, so shall they be condemned,
and justly judged of the Lord.
As they have cast the bodies of the poor lambs of Christ into prison,
and been a snare upon them, even so shall they be ensnared,
and into captivity shall they go.
And as they have caused the goods and possessions of the innocent to be spoiled,
and made a prey,
even so in like manner shall the curse of the Lord spoil their substance.
Indeed, as they have done, so shall it be done unto them;
and as they have measured to others, so shall it be measured to them again.`"
"`Then,`" said E. Burrough, "`I saw a great misery and desolation near at hand,
even the sword of the Lord, that it should slay them.
And I beheld it was made ready for the slaughter;
and in the sense of these things a sadness fell upon my spirit,
considering the desolation and the judgment that is at hand,
to be executed upon the cruel oppressors.`"
Thus he wrote to them as follows:

[.embedded-content-document.epistle]
--

Wherefore all you rulers, and all you that have trodden down the heritage of God,
and you that have disregarded these many warnings that you have had; I say unto you all,
in the power of the Lord God, in His dominion, and by His Spirit:
This is once more a warning to you from the Lord that these things
must surely come to pass and be fulfilled in their season,
and no man shall be able to deliver his brother; but every man shall bear his own burden,
and drink his own cup prepared for him.
And though it has been counted a light thing among you,
and you have despised the reproof, and gone on without fear; yet the Lord has spared you,
and not speedily executed judgment upon you, but rather waited for your return.
Nevertheless, the dealing of the Lord towards you, in sparing of you,
you have not accepted, and therefore His judgments shall be the greater upon you.

Come now to the witness in your own consciences,
and tell me what evil this people has done?
Whose ox have they taken, or what have they sought from you?
Wherein have they been a burden to you, except in reproving you for your iniquities,
and desiring your redemption?
If you would only consider this, and confess to the Truth in your consciences,
will that not tell you that they have patiently suffered
all things that you have cruelly imposed upon them?
And have they not walked peaceably towards you, and humbly, meekly,
and justly among their neighbors?
And have they not been meek and innocent even as lambs,
and as the sheep before the shearers?
And have they wrought offenses towards any?
Have they sought the overthrow of the government,
or have they ever sought vengeance against their enemies?
Or what injury have they done to any person or estate, except to Satan and his kingdom?
Have they not sought to reform and reclaim the ungodly from their ways?
Have they not pitied and prayed for their enemies?
And have they not in all things walked in good conscience
towards the Lord and towards all men?
Yes, my friends, in the day of the Lord,
when the witness in your consciences shall not be limited, but shall speak plainly,
and when the impartial Judge shall appear upon His throne,
then shall you acknowledge these things.

Therefore I say unto you: Receive the judgment of the Lord to purify you,
otherwise the judgment shall destroy you.
Come now to be more wise, so that some of you may be as a brand plucked out of the fire,
and be saved from being consumed; for the visitation of the Lord is near an end,
when His lovingkindness will be shut from you, and His long-suffering turned into fury.
He will make you know that we are His people, with whom you have thus dealt; yes,
you shall suddenly know it.
Oh, what shall I say unto you?
For the deep sense thereof remains upon my heart when I consider
how that in all ages the Lord did avenge His people`'s cause,
and when the time of their suffering had expired,
He broke the bonds of iniquity and set them free.
Thus He did with Israel of old,
and many times it was His way with His people to bring them low by suffering,
and then to raise them up again in glory;
and He permitted their enemies for a season to glory over them,
that He might bring them down.
And thus He did in England, in the case between the bishops and their persecutors,
and the poor people at that day called Puritans.
Did He not confound that persecuting crew, and deliver His people?
And is He not the same now?
And will He not effect the same work at this very day?
Yes, doubtless, and much more will He do,
inasmuch as the manifestation of Truth is more clear than it was in their days,
and inasmuch as the rulers and people of this nation have rejected a more
clear testimony than either the Papists in Queen Mary`'s days,
or the bishops and prelates in their days.
For the Lord has regarded the sufferings of His people,
and He has said "`it is enough;`" for He has tried them and found them faithful,
and all this has been allowed to prove them, and not to destroy them.
And even as He has preserved them in patience and peace through it all,
so He will give them hearts to walk answerably to their deliverance.
And as they have abounded in patience in their sufferings,
so they shall abound in everlasting praises in the day of their freedom,
when the Lord has broken the yoke of the oppressed, and set His people free,
inwardly and outwardly.
Then they shall sing to the Lord over all their enemies,
who shall be tormented and vexed in the Lord`'s sore displeasure; for their reward comes,
and their recompense shall be even as their work,
and He will give unto them sorrow and anguish, instead of rejoicing.

But again,
when I considered the long-suffering and patience and forbearance
of the Lord`'s innocent people under all their sufferings;
and when I looked at their innocency, and at their righteousness,
and the spirit of holiness with which the Lord has blessed them,
my heart was made glad in the consideration of this.
And my joy was the more as I beheld their innocence,
and the guiltlessness of their cause,
whereby the unjustness of their sufferings did the more appear.
And when I looked and beheld how they increased under all their sufferings,
and how the Lord turned all these things to their good,
and to the overthrow of their enemies;
and how by the way which their enemies intended to destroy them from being a people,
even thereby did the Lord most wonderfully increase them to be a great people;
for through all they have grown in life and power, and in strength and number,
and so have been encouraged to follow the Lord with even more zeal and boldness.
And in the consideration of this I did rejoice and magnify the Lord,
that He had brought forth His praise, even through the wickedness of the wicked,
and that He had increased His people and exalted
them through the cruelty of all their enemies.
When I consider this, how the Lord has given them dominion,
and brought their life to reign over all their enemies, these things were a joy unto me;
and looking back into ages, seeing there was nothing, nor any people for generations,
that had grown and risen through all opposition like unto these;
therefore it is a sign and testimony that we are the Lord`'s,
and that these things are of Him, and from Him, and by Him alone,
that He might be praised forever.

Again, when I do consider how the Lord has carried on this work among His people,
it has not been by anything of man, nor by the arm of flesh;
but in pure innocency and simplicity it has been accomplished;
not by the wisdom of this world, nor by men in places of honor,
and of power in the nations, for this people has lacked all these things;
and what they now are, it has been through the opposition of all this;
for they have had none of the great men of the earth
on their side to defend them and establish them,
but all have been against them; and indeed,
oppression and tyranny have been executed upon them,
rather than any approbation or justification from men in outward authority.
So it may truly be said, there has been nothing of man in this work, but all of the Lord,
by His own power;
and the beginning and carrying on of these things has been
in a contrary way to all the false sects and false churches.
For we know that all the sects in this nation have risen and been
established through the countenance of men in place and power;
and the rise and fall of all false churches has depended upon man,
and the wisdom of this world, and the authority of the powers of the earth.
As the powers of the earth have sided with them, so they have been set up;
and at the displeasure of authority, they have been cast down.
But as for this people, they have been raised up by the Lord and established by Him,
even contrary to all men.

Therefore let all the persecutors bow before the Lord,
and let all the saints walk humbly in His sight,
and let them continue in that innocent life in which they have begun.
And let them never forget the mercies of the Lord, and what He has brought to pass,
who has manifested great things,
and will do more and more to the confounding of all His enemies,
and to the praise of His elect people.
And all you saints upon the earth, look to the Lord continually,
and do not turn unto idols, but let the Lord be your joy forevermore.

[.signed-section-signature]
E+++.+++ B.

--

Not long after the publishing of this paper, in the month called May,
Edward Burrough and Samuel Fisher went from Dover to Dunkirk,
where there was an English garrison.
The news of their coming there quickly spread over the town.
As the governor, Lockhart, was not there, his deputy, colonel Alsop,
with the council of officers, sent for them; and having come,
they were asked what their business was there.
To this they gave an answer, and the next morning signified in writing,
that their coming was to visit the Jesuits, friars, priests, and other Papists,
to show them the errors of their ways and the falseness of their worship,
etc. they being called to preach the everlasting gospel to the nations.
They were some hours in discourse with the said deputy and the officers,
and not unkindly treated;
but the deputy however said that it would be dangerous for them to stay in the town,
and he therefore desired them to depart.
To this they answered, that if he desired them, they could not receive any such desire;
and if he commanded them, they could not obey his command in that case;
because they could not depart the town except in the will of God,
according to which will they had come there.
After much reasoning they left them, and the next day went to the Capuchin friars,
and had some discourse with the chiefest of them in their garden,
concerning the light of Christ with which every man is enlightened; and they told them,
that the mighty day of the Lord was at hand upon them,
and that the Lord had come to search and try them,
and that He would hew down their idolatrous ways, worships and works.
The next day Burrough wrote some queries to the friars and nuns in and about that town,
which were sent to them in Latin.
The introduction was thus:

[.embedded-content-document.epistle]
--

The mighty day of the Lord is come, and is coming upon you, and upon all the world.
Awake, awake, you that sleep in the earth,
for the dreadful God is arising to plead with you,
and to give unto all the world the cup of His fierce indignation,
because of your idolatries, and hypocrisies, and abominations,
which have corrupted the earth, and are come up before Him, and have provoked Him.
The cry of the just, who have been smitten and laid slain,
has entered into the ears of the Most High, and His sword,
which is the Word of His mouth, is awakened to wound and destroy all His enemies.
The day of your visitation is now come, wherein the Lord is searching you,
and trying you, that He may recompense you: and this is the word of the Lord to you.

Therefore, I am moved of the Lord to propound a few queries to you,
for the trial of your spirits and ways; to which I request your answer,
that all things may be brought to light and true judgment,
and that you may be judged justly,
and by the Spirit of the Lord either cleared or condemned according to your deeds.

--

These queries were partly concerning the orders of friars and nuns,
whether any such thing was in the church in the apostles`' days;
and concerning the popish worship and ceremonies,
demanding proof of their lawfulness from the Holy Scriptures.
After delivering these queries to the Capuchins,
Edward Burrough and Samuel Fisher went also to the friars of other orders,
and entered into discourse with them,
but their plain words against the idolatrous rites and ceremonies found no entrance.
After some stay in the town, having gone to the college of the Jesuits,
they got into discourse with their chief rector;
and after a conference of about three hours, he grew weary,
and claiming to have other business, said he would stay no longer with them;
and so they parted.
They asked him whether he would admit more discourse at some other time;
but he refused it.
Burrough afterwards wrote a letter to him, which began thus:

[.embedded-content-document.letter]
--

Friend, your wisdom and your knowledge is earthly and sensual,
and thereby you cannot know the things of the kingdom of God.
+++[+++And he concluded with this query:]
What is that whore that has sat upon multitudes of people?
And what is that golden cup in her hand?
And what are the abominations and fornication of which her cup is full,
which she has caused the kings and people to drink?

--

But neither this query nor the others were answered.
Burrough and Fisher did also visit the nuns; and speaking to them through a grate,
they asked if they were of the order of those called Quakers;
and soon perceiving they were such, they said they could not hear them,
and so presently passed away.
Edward Burrough wrote also some propositions to the Jesuits, priests, and friars,
wherein he particularly represented the tyranny of the church of Rome in true colors;
and these propositions were sent to them in Latin.
They stayed yet some days in town, and had several meetings among the English soldiers:
and Burrough also wrote to them, and bid them be faithful to the Lord,
and not to seek themselves in their service, but the honor of God.
He also showed them what their duty was in their military station; and told them,
"`What do you know but the Lord may have some good work for you to do,
if you be faithful to Him?
It is,`" said he, "`the Lord`'s work, I know, to make men truly religious;
but yet He may work by you to break down the briars and thorns,
and the rocks and hills that have set themselves against the Lord.`"
He also advised them, if ever such a work fell to be their lot, not to be ambitious,
nor vain-glorious,
but to make it their work to seek the annulling of
the popish inquisition and their cruel laws.
And he charged the officers not to be as tyrants and oppressors over the poor soldiers,
but to be loving and meek, and examples of all goodness unto them, and then added:
"`and so having no sin lying upon your consciences,
then shall you face your enemies with courage, and will not fear death,
but shall be ready to lay down your lives in a good cause.`"
But lest any might think he was for the bearing of arms,
and not for harmlessness or non-resistance,
he told them also that the Lord had a more honorable work, that is,
to destroy the kingdom of the devil and the ground of wars.
And that there was a more honorable victory to be sought, namely, the victory over sin,
etc.

Burrough and Fisher being once sent for by the governor Lockhart,
found many officers with him; and after some friendly discourse,
they advised them to moderation and the fear of God, and so parted from them.
And after having performed their service in the town, they returned to England.

Not long after this Burrough gave the aforesaid queries out in print,
and also wrote a paper to the parliament,
exhorting those that were members of that assembly to fear God,
and not to oppress honest people, but to free them from oppression and tyranny;
lest the Lord come suddenly upon them and break them to pieces.

Finding that the power of the protector Richard Cromwell was already declining,
he was prevailed upon by the officers of the army to dissolve this parliament,
which began to make inquiry how the subsidies were employed;
and by the direction of some of the chief republicans,
the long parliament was called again.
This parliament set up a committee of safety for
apprehending those that disturbed the peace,
and for making an alteration among the military officers, either by dismissing them,
or by some other means.
And as this parliament increased in power, it also erected a council of state;
and then word was sent to Richard Cromwell (who was now
deprived of all power) to remove from the palace of Whitehall,
which at length he did,
the parliament allowing him two thousand pounds for the charges of removing,
and promised to pay his debts contracted for the public.
His brother Henry, who was lord deputy of Ireland,
was also called back by the parliament,
and thus these two brothers were again reduced to the state of private citizens.

E+++.+++ Burrough now wrote a letter to the parliament,
and in it seriously exhorted them to desist from all persecution for religion,
and to take away those laws which gave occasion thereto.
About this time there was an insurrection in Cheshire in support of king Charles,
under the command of sir George Booth; who, having received a commission from the prince,
gathered such numbers of followers that he seized the city of Chester.
In the meantime the parliament sent Edmund Ludlow
to Ireland to be commander in chief of the army there,
instead of Henry Cromwell, and general Lambert was sent with an army against Booth.
Now since some rash people that went under the name of Quakers
were in favor of taking up arms under Lambert,
and finding that the committee of safety offered
great positions and commands to some of that persuasion,
thereby to draw them off from the truth they professed, G. Fox wrote a paper,
wherein he showed the unlawfulness of wars and fightings,
representing it as a work not at all becoming the followers of Christ.
He exhorted his friends not to join with those that took up arms,
but to fight only with spiritual weapons,
which would take away the occasion of all carnal weapons.
This he also recommended in his preaching,
for a harmless and inoffensive life was that which he always asserted and practiced.

As for George Booth, he was defeated,
and endeavoring to make his escape in women`'s clothes,
was discovered in an inn and taken into custody;
and being carried to London by an order of the parliament, he was committed to the Tower.
The officers of the army, of which George Fleetwood was now commander in chief,
were very busy to get the upper hand of the parliament;
which caused great division and confusion in the nation;
for it was well known that if the supreme power was offered up to the army,
they could then do what they would, and thus the nation would be governed by the sword.
It was also fresh in memory,
that it was the army by which Cromwell had been advanced so as to become protector,
and supreme ruler of the nation; and therefore many opposed the design.

About this time also, the military officers moved to remove the burden of tithes,
and to settle another maintenance for the national preachers.
But being unwilling that the parliament should be masters of the army,
they complained of having been deceived by the parliament;
and colonel Desborough said that the parliament had not performed
any part of the promises they had made to the army;
that they had taken no care to secure religious liberty for tender consciences,
and that their intention was to remove the principal officers,
and to place others in their commands who were of different principles.

Now the council of military officers was in favor of calling a new parliament;
but this met with no small opposition.
In this bustle the council of officers began to seek the favor of the clergy,
and they agreed with them that their maintenance by tithes should not be taken
away till another revenue as ample and certain should be settled upon them.
They also agreed that some provision should be made for those who
differed in faith and worship from the established church,
but that the Quakers and some others,
whose principles they said "`tended to the destruction
of civil society,`" should not be tolerated at all.
In this distracted state of affairs, when some were for,
and others against the parliament,
so that it was hardly known in whom the supreme authority resided,
Edward Burrough wrote and published in print a large speech, which he entitled,
"`A message to the present rulers of England, whether committee of safety, so called,
council of officers, or others whatsoever.`"
He signified by way of introduction,
that the contents had been upon him to deliver by
speech and word of mouth to the men then in power;
but no way being made for him so to do, he had written what was upon him.

[.embedded-content-document.address]
--

[.salutation]
Friends,

My Master, is a high, and mighty, and powerful prince, and very honorable; and all fear,
reverence, respect, and subjection belong to Him alone, from you and all mankind.
He is wise and understanding, and of great strength,
and His dominion is from everlasting to everlasting.
He can do whatever He will in heaven and earth,
for He rules with His iron rod over the world, and whatever He says, it is done;
for His word is an everlasting command.
If He says to a man, live, it is so; if He says to a man, die, it comes to pass.
If He give peace to a man, or a nation, none can make war;
and if He make war with a person, or in a nation, no man is able to make peace.
For He has all power in His hand, and to Him all judgment and authority is given;
He is the Son of the living God, the everlasting Creator.
He was, and is, and is to come; His eye beholds all things,
and His arm encompasses heaven and earth; and what His purpose is,
He has always and will ever bring it to pass.
If He set up rulers, they must rule; and if He pull them down none can hinder.
Whom He will, He honors; and if it be His pleasure, He brings men to shame.
If He break a nation down, none can build it up;
and if He confound powers and authorities in the kingdoms of men,
they all fall as withered grass before Him.
Behold, you men!
He is so great and mighty, and of so great authority, that whatever He says, it is done;
and whatever He wills, it comes to pass;
and none is able to resist Him and overcome His power,
when His pleasure is to accomplish a work.
He is just and merciful, full of goodness, righteousness, and truth;
all virtue dwells in Him, and His judgment and mercy, His authority and meekness,
and His wrath and His love, they are companions.
What are you before Him?
Or how shall you be able to resist Him, or to turn backward His purpose concerning you,
and this nation?
For you have no being nor breath without Him.
Behold you men!
You are verily as the dust before the wind; so are you to Him, soon blown away,
and your place is not found.
As the grass before the mower, so are you before Him, soon cut down and withered,
and your beauty utterly extinguished.
As a potter`'s vessel under an iron rod, even so are you to Him,
He can immediately break you, never to be bound up.
As a drop to the fountain, so are you to Him, soon dried up and made nothing.
Therefore, you men, you mortal creatures, you ignorant persons, sons of transgressors,
dust and ashes--for thus you are in comparison of Him,
this mighty Prince--hearken to His message, which comes to you from Him.
Hear and fear, and be not obstinate against the Lord God,
that is about to speak unto you.

As for this little island of England, wherein your present place and being is,
it is an island which the Lord has showed great favor to in ages past,
and in this present time; and I must tell you, He has a purpose of love towards it,
and to honor it in the view of the world, though through great tribulations.
He has an intent of great good unto it, for He has a seed,
a precious seed in it scattered abroad, and He has a people that fear His name,
and have walked in His ways, and He has made them, and elected them, and what they are,
it is by Him, that He may dwell among them, and have the whole government over them all.
Yes, He has a purpose concerning this nation, and He will purify it in judgment,
and refine its inhabitants through the fire of tribulations,
that it may be pleasant to Him, and fit to do His will.
He has a purpose to work some great thing in it, I must tell you,
as He has said unto me so to do.
He will have His name exalted and reverenced in this island,
and His terror shall be sent out of it through the world,
and His branch from it shall spread over the earth.
He does purpose in His season to take it into His own hand,
and to sway the government thereof with His own scepter,
and to set up righteousness alone, and to overthrow all oppressors and oppressions;
for the kingdoms of this world must become the kingdoms of the Lord and of His Christ.

True it is, that for many ages past, my Master has been, as it were,
banished from the nation, and has not been allowed to enjoy His right;
but has been expelled, even, as it were, by the forces of Satan and antichrist,
who have long usurped authority over the inhabitants of this nation;
and in my Master`'s absence, lamentable injustice, cruelty, unmercifulness, tyranny,
and oppression have been exercised upon the inhabitants;
and the poor creatures have been held in great slavery by their rulers,
who have ruled by the dragon`'s power.
These have been kept in great blindness and ignorance, and under great oppression,
both in body and spirit, by anti-christian teachers for this many years,
even while the great King has been absent, and, as it were, gone into a far country.
Thus, in all this time antichrist and the devil have ruled and reigned,
and have made and executed oppression, and tyrannical laws and decrees,
both in church and state; and all the nation has been out of right order,
and laid waste and barren of good fruit.
Men that have ruled for many years, have not ruled singly by my Master`'s authority,
but by another power; though not without the knowledge of my Lord,
neither as though He had not power to have done otherwise;
but for His own pleasure He has allowed it thus to be.
Men go on to rule and govern in their own wills and after their own lusts;
and the people have walked wickedly towards Him, and towards one another.
All this He has allowed--not as if He gave approval of it (for His messengers and His
witness in people`'s consciences have been reproving the people`'s ungodly ways;
and He has often showed His dislike by many ways, with tokens, and many judgments,
and strange overturnings of both rulers, prophets,
and teachers of this nation--but yet they have gone on against His mind,
and contrary to His will, notwithstanding His reproofs and judgments.
Yet He has been long-suffering and of great patience, and has borne all things,
and taken the injustice and cruelty, and wickedness, and idolatry,
and all unrighteousness that has abounded in the nation upon Himself,
and suffered under it, and borne it for its season,
while woeful and lamentable oppressions have been practiced in civil state,
even hellish laws, and devilish executors of them.
Merciless tyrants have borne the scepter,
and reigned for many years over the inhabitants,
and in church and state there have been heinous idolatry and superstitious
vanities committed in a high nature and measure,
even from the prince to the beggar, rulers and subjects, teachers and people,
judges and prophets.
They have been corrupted both in heart and hands,
and they have dealt falsely and wickedly towards Him and towards one another;
even to the great displeasure and vexation of Him and His blessed Spirit.
All this while He has lain as it were asleep, and at rest in Himself;
and He has left men to try them, as to what they will do, and He has given them a day;
many kings and rulers, and let them have a little time, to see how they would use it,
but they have abused it and not ruled for Him,
nor accomplished His work nor fulfilled His will,
but acted even in defiance of Him and of His power, and to His great dishonor.

Alas!
I must be plain with you: my Lord has been utterly exiled, and greatly dishonored,
and highly provoked and vexed by reason of such proceedings
as have been in this nation for this many years,
through the corruption of all sorts of men in position and power,
who have not ruled for Him, but for the devil to their own corrupted ends.
Yet He has permitted men to go on in their course for a season;
some as it were appearing on the stage for a time,
and suddenly cast down again for their iniquities sake.
His hand has been in all these things, though very privately and secretly,
not known and discerned by the sons of men, yet has He ruled over the kingdoms of men,
and pulled down one, and set up another.

And such was the cruelty, tyranny,
oppression and idolatry both in church and civil state,
that the people of this nation were held under in the days of papal^
footnote:[i.e. Roman Catholic]
power; such, I say, was the exceeding height of the cruelty and tyranny of that time,
that scarce any that feared or reverenced my Lord, in any measure, could live,
or have a being in the nation.
Hell`'s mouth was opened against every man that did but incline towards Him,
and desire the knowledge of His ways, and they were swallowed,
and many of their lives taken from the earth,
by the hellish power that had in that day usurped authority in this island.
And when it was thus, then He looked down from heaven,
and His bowels of compassion were opened,
for the sake of the oppressed people that desired after Him,
in so much that He broke and threw down the power of their oppressors in some measure,
as it stood in papal authority, and when the iniquity of that power was filled up,
He took vengeance upon it.
And I must tell you, it was He that brought it about,
even the destroying of that power in this nation, and freeing the nation from it,
though the men that were instruments in the cause were not His servants,
any more than as Nebuchadnezzar served him.
For He has a secret way of using the wicked, and such is His power,
that He can turn the wickedness of the wicked to His glory,
and He can make a rod to whip His adversaries, and then burn it when He has finished,
and He has often destroyed one wickedness by another.

But to leave that,
though He did in some measure free the nation from much
tyranny and cruelty in the casting out of popish authority,
yet alas! the nation in a few years was nearly as overrun
by injustice and cruelty under the succeeding power,
as ever it was once under the papal power.
And though there had been some small reformation and change
in outward appearance (though little in ground and nature),
yet oppression, and idolatry, and superstition, in church and state,
and all profaneness and wickedness among people grew
as high as it had done under the papal power before;
and all that desired after the Lord, and were weary of iniquity,
and of the present oppressions and idolatries, were persecuted, and slain, and destroyed.
Indeed, injustice and cruelty were exercised upon them,
almost to the rooting out of righteousness, and to the grieving of the Lord`'s Spirit.

But then, because of the cry of the people,
and the oppression of the nation under that authority, my Lord looked down again;
and even for His name`'s sake, and for His seed`'s sake,
He had compassion on this nation, to set it free, and to break off its oppressions.
And in a great measure He did deliver the people of this nation in many things,
and there was a partial reformation wrought, and much more pretended and looked for.
All this came to pass through Him, and my Lord did accomplish it;
however the instruments by which He wrought proved deceitful, and became oppressors,
as the others before them.
And though there was in this nation a day of great troubles, and wars, and contention,
and great strife, and the wasting of much blood,
and earthly treasure (and none of these things, I must tell you,
fell out without the ordering of my Master`'s hand), yet so it was, and came to pass,
that after this nation was restored to peace,
though much unrighteousness and injustice was removed,
yet there was much also left behind.
And many of the men that He had used as instruments in His hand, in a good work,
and to whom He had given wisdom and understanding,
and had appeared in much mercy and in great deliverance,
yet these turned aside to seek themselves,
and became corrupted in the spoils of their enemies.
And when peace and plenty abounded, the Lord was forgotten again,
and then the land fell under oppressors, and began again to cry out for freedom,
as other horns of the first beast sprang up,
and went out each of them against his fellow.
And though one horn has striven to break another, yet after one has been cast down,
another has risen, and ruled and reigned by the same spirit and authority,
derived from the dragon`'s power in cruelty and oppression;
and made laws and executed them to the dishonor of the Lord,
and to the great oppression of His people,
and to the filling of this island with injustice and cruelty,
even from one generation to another, until this day.

And thus up and down the times and seasons have been altered; powers and authorities,
statutes, laws, and decrees have been changed;
for as the iniquity of one power was filled up, then that power was cast down,
and another had its day, till the measure thereof was also filled up,
that it might partake of the same judgments.
And in all these over-turnings, breaking-downs, and overthrowings,
the very hand of my Lord has been present, though secretly, and not discerned.
Yet His power has brought about and allowed all these things to come to pass;
and who shall charge Him with injustice?
Or, who shall say, "`What have You done?`"
Or, "`Why have You done it?`"
For, as I have said, He is a high and mighty prince, and can do whatever He will;
and He is the supreme power and authority,
who rules and reigns in and over all the kingdoms of men.
And what if He has seen fit to use wicked men as an instrument to accomplish His work,
and has made the wicked His rod, so that one wickedness should destroy another,
and one oppressor break down another, and the kingdom of antichrist confound itself?
All flesh must be silent before Him, and all people,
and the whole earth must be subject unto Him;
for the government and dominion over heaven and earth is His,
and all power and dominion belongs to Him alone, and all judgment is in His hand,
to bring to pass whatever He will, and by whomever, according as He pleases.

But now, my friends, though I desire not to be tedious to you,
yet I must tell you the truth, and faithfully deliver the Lord`'s message unto you.
As concerning this last overturning, there was something of the hand of my Lord in it;
and He can and will bring forth His own work and praise by it,
and it shall be for the good of all His people that wait upon him,
though there was much ambition and corruption in the instruments,
and neither part was perfectly single to the Lord in their proceedings,
but their work was tainted with the false and idolatrous spirit of self-seeking.
Nevertheless, the Lord is able to bring forth His government, and His pleasant plant,
through and beyond all this, even out of another root,
which yet appears not among either of these; and righteousness may arise in the nation,
contrary to both of them, out of another stem; for He will set up His kingdom,
and in the meantime leave one potsherd of the earth to break another.

And as for you that now sit on the throne and bear rule, alas,
you are but another horn of that fourth beast, that has been made to rule over the world,
and upon the earth for many generations, and are but little more refined than the last,
and are of the last, even as the eighth was of the seventh, spoken of by in Rev.
17:11. And this your present government is leavened with the spirit of the old dragon,
that has killed the saints, and drunk their blood, and how should the Lord establish it?
No, your kingdom will prove but small and little, and full of uproars and troubles,
and there will be little peace and satisfaction and establishment in it to yourselves,
or to the people under you; but confusion will attend it, and fears will encompass it.

Though this I must tell you, as you are men,
you have your day of trial as to what you will do, as many others have had before you.
And there is something you may and ought to do,
for you have a talent put into your hands, which you may improve to the Lord`'s honor,
and to the nation`'s good, and to your own happiness; which,
if you will be faithful to the Lord, to do what He requires of you,
and if you become meek and humble men, and fear His name, and deny yourselves,
and not seek your own honors, nor any earthly advantage to yourselves; I say,
if you do this, then my Lord will show mercy to you,
and you shall not suddenly fall before your enemies, though many may rise up against you.
And if you walk in this way, and rule only for the Lord,
then you shall be honored as men, if not as an authority,
and you and the nation shall be preserved in peace,
and the force of the wicked shall be turned backward, and you shall not suddenly fall.
And let the various overturnings in this nation be examples to you,
that you follow not the steps of those that God has cast out,
lest you come to the same end of confusion and misery.
For, concerning that assembly of men who last sat on the throne,
in some things they served my Lord, and they were a rod in His hand to smite His enemies;
yet they were not faithful to the end, till all His enemies were destroyed,
but rather joined themselves to fight against the Lord and His people,
and were hastening on in the way of oppression and persecution.
And so came the time for the Lord to remove them,
and to lay them aside as an empty vessel, which was formerly useful;
and to break them as a rod, formerly of service as a scourge upon His enemies.
And when the day of their trial was over, which God gave unto them,
no longer being fit instruments in His hand, He then cast them into the fire;
for they entered into the very same spirit of wickedness, of oppression and persecution,
which the Lord had once reproved through them, and cast out by them.

And though some of you present rulers be looked upon as
great traitors and tyrants in your dealings towards them;
and doubtless the men of that party will seek vengeance against you,
even by their preaching and praying, and they will curse you in the name of their God,
and seek continually your destruction,
as those who have taken away part of their strength, and cast down their idol;
yet alas! all of this is nothing; for the Lord does not account as men do.
For these things must necessarily come to pass for the furtherance
of the kingdom and government of Jesus Christ,
that it may spring and arise through all.
And if you were but faithful to what the Lord requires of you in your proceedings,
then what you have done unto them would not be reckoned against you, neither by God,
nor by good men.
But if you of the army continue to be treacherous and disobedient towards Him,
and abuse your power, and disregard your talent that God has given you,
and trifle away your time about positions of honor, and such self-seeking matters,
and the cause of God be neglected by you,
and His people continually oppressed under you (as they have long been),
then you shall be cast aside with shameful disgrace,
and the heavy hand of the Lord shall be upon you in judgment,
and you shall be smitten more than any before you.
Your estates shall not be spared from the spoiler, nor your souls from the pit,
nor your persons from the violence of men, no, nor your necks from the axe.
For if you be unfaithful, and continually treacherous to the cause of God,
then you shall be left to the will of your enemies,
and they shall charge treachery and treason upon you,
and your persons and estates shall be given for a prey to your enemies;
and you shall not deliver yourselves,
neither will the Lord deliver you from the execution of merciless men;
for my Lord shall leave the cruel-hearted to plead with you.

Therefore, that you may be warned, I advise you to be faithful;
let not the cause of God fall, nor the cause of his enemies prosper before you;
for there is no other way whereby you can be preserved,
nor any other defense shall you ever find from the wrath of the Lord,
and from the fury of your devouring enemies, than your faithfulness in God`'s cause.
Therefore, relieve the oppressed, and take off all oppressions,
break down all unjust laws, and set all people free from unjust burdens,
and let all oppression cease, both in church and civil state.
And as for oppressive laws, and unjust judges, and evil men in power,
let all these be removed,
and let the nation be clean and free from all men and laws that have held persons,
estates, and consciences of the good people under oppression; for this my Lord,
the great King, requires of you,
and He will suddenly have it brought to pass in the nation, if not by you,
then contrary to you, and to your utter destruction.

And this is the very substance of my message to you,
that my Master has given me to say unto you.
On His behalf I have come to claim of you my Master`'s long lost right.
Let Him have His right, from which He has long been banished.
He demands it of you, all who seem to bear rule in the nation;
I charge you in His name to let Him have His title and prerogative.
Let Him be wholly the Lord and King in His own kingdom;
let Him have the exercise of His people`'s consciences by His own
Spirit in all things relating to His worship and service.
Let Him have the full authority by His Spirit in
all things pertaining to church and ministry,
and faith, and religion;
and let His Spirit have the only authority to persuade and dissuade people from, or to,
such or such a ministry, worship, and practices of religion.
Let all forced maintenance to ministers, and tithes, be speedily taken away;
and let all laws and decrees whatsoever,
which were made and practiced in the days of antichrist, upon the bodies, estates,
and consciences of the people, in oppression and unrighteousness,
having to do with church, and worship, and religion, be utterly repealed and made void,
and never more be put in force in this nation.
Rather let my Lord be sole ruler and governor,
and have the full authority in His own kingdom,
and in all things whatsoever pertaining thereunto.
For it pertains to Him only to be the sole judge,
and to have full power in His own kingdom; and until you give Him the right,
and deliver up unto Him His own kingdom,
and the exercise of peoples`' consciences in all things about religion,
you shall never prosper, nor will any that comes after you,
who in any measure limit my Master of His proper right,
from which He has long been banished.
And until His right be given Him, as has been said,
He will dash one wicked man against another, and none shall ever be established;
but horn after horn shall be broken,
and one power after another shall be brought into confusion.

And, therefore, you men, do not strive with Him in this matter,
but yield unto Him the exercise of your own consciences by His Spirit in you,
and let Him do so unto all others, even as you hope to prosper in yourself.
And let just men, and righteous men, and meek men,
and men that have the fear and wisdom of God in them (without acceptation by birth,
or otherwise), let such as these have the power and judgment committed to them,
to determine in things between man and man.
Down with all the false-hearted flatterers, with all that judge for rewards.
Away with all hireling rulers, who execute the law for money,
and will not plead the cause of the poor without great fees.
Down with all who will not serve positions of trust without large stipends;
away with all these things out of the land, for they are heinous oppressions unto men,
and great abominations in the sight of God.
For the Lord`'s purpose is one way or other to cleanse
the land of all these and other oppressions,
that the people of this land may be a free people from all the heavy yokes of antichrist,
which have long sorely pressed them down.

And whereas there is a great cry about ministry,
about sending forth and maintaining ministers,
and encouraging a godly ministry (as you say)--this I will answer on my Lord`'s behalf.
I must tell you plainly; as for a true godly ministry, truly called and sent of God,
such a ministry, and such ministers you will never be able to hinder;
but the Lord will send them out,
maintaining them and preserving them whether you desire it or not.
And while you are troubling yourselves about such a matter,
you are but meddling with things above your line, and out of your jurisdiction;
for it belongs to His government to send out ministers, whomever He desires,
and to maintain them and defend them according to His own pleasure,
and all this without you.
For such ministers, who are truly called thereunto, and sent of the Lord,
will not come to you to be sent forth, or to be maintained by you; but even without you,
and contrary to you, they will be sent out and maintained;
so that the Lord will have a ministry in this nation purely of His own, and not of man,
nor by man, and such a ministry you shall not be able to hinder.

And I must tell you plainly, as for these men called ministers in this nation,
the way of their setting up, and sending forth, and the way of their maintenance,
and the way of their standing and defense, and in every particular of their being such,
they are now the greatest and most woeful oppression in the nation.
Truly, the most abominable and unjust cruelties and tyrannies are acted through them,
and they are (as aforesaid) the woeful cause of the
nation`'s groaning under merciless dealing.
What shall I say of them?
The earth is oppressed by them, the inhabitants groan under them,
and the righteous God is vexed by them,
and they and all their practices (as such) are the fuel of His anger,
to be consumed by the fire of His jealousy.
The nation is weary, together with its inhabitants, and the Lord is weary,
because of these men.
And is this the ministry regarded by you as godly and pious?
Are these the men that the nation must be forced to maintain in their pride and idolatry?
Is this the ministry that must be encouraged?
Well, if these are the men,
and this is the ministry which must be established and encouraged by you,
in so doing you shall never prosper, but thereby gain the displeasure of the Almighty.
For I must tell you, the hand of my Lord is against them;
and whoever shall seek to defend them, shall not prosper in their doings,
because their oppressions, cruelties, deceits, and abominations,
are near finished and fulfilled.
Therefore take heed unto yourselves, for this is my Master`'s advice unto you;
let this ministry alone, and do not join yourselves to Baal, lest you perish.

And, last of all, I must tell you that my Master has a people in this nation,
even a suffering people, that have borne the burden of the cruelty, injustice,
and wickedness, both of rulers and teachers, who have (as it were) trodden them down,
and made them a prey to their devouring mouths.
The very cry of their sufferings has reached unto heaven,
and the sound thereof your ears have heard.
Truly, this people are greatly beloved, and my Lord will assuredly honor them,
and His hand shall continue to preserve them and defend them against all their enemies.
For He does reserve them to Himself for a glorious work that He has to do by them;
and He has formed them for Himself,
and they cannot join with any of the horns of the great beast,
neither can a place of honor pervert them from their perfect way.
My Lord encompasses them about on every side, and has kept them in the midst of trials,
reproaches, and sufferings, and covered them in the heat, and in the storm,
till His pleasure is to make further use of them.
They are His, and not their own; and they must fulfill His will, and no other.
And truly, they lie at rest in Him, even while mountains are overturned,
and while one potsherd of the earth breaks another;
and this must be even till the appointed time.
Therefore, O men, touch them not, neither afflict them, if you hope to prosper.
Remember their cause, and permit it not always to be rejected, as it has long been,
but keep yourselves free from the injustice and cruelty
of those who have gone before you,
who have been merciless oppressors of this people, even till my Lord has confounded them,
and brought them into confusion.

Thus I have delivered the Lord`'s present message unto you, which I received from Him,
and thus far I am clear; and whether you accept it, or reject it,
my peace and reward is forever with Him.
So I remain a subject of His kingdom, and a friend to this nation,
however otherwise judged by ignorant men.

[.signed-section-signature]
E+++.+++ Burrough.

[.signed-section-context-close]
The Ninth month, 1659.

--

Now how soon after these sayings of Burrough,
"`Your estates shall not be spared from the spoiler, nor your necks from the axe;
your enemies shall charge treason upon you,
and if you seek to stop the Lord`'s work you shall
not cumber the earth very long,`" were fulfilled,
we shall see shortly.

About this time also he wrote several epistles to his friends,
wherein he so powerfully exhorted them to faithfulness and steadfastness,
that thereby he has procured to himself a name that will never die;
as living still in the remembrance of thousands,
though he long ago went the way of all flesh,
having laid down his life in bonds for the testimony of Jesus,
as will be said in its due place.

I have also a piece of a letter written about this time to the royalists,^
footnote:[Supporters of Charles Stuart`'s return to the crown.]
which, whether done by E. Burrough, or by George Fox the younger, or by George Bishop,
I cannot tell: but thus it speaks:

[.embedded-content-document.letter]
--

The very spirit of pride and oppression and idolatry has entered into them (that is,
your enemies), and now lives in them in as high a measure as ever it lived among you.
Their iniquities are well near finished,
and the Lord will one way or other correct and reprove them;
and they shall be dealt with in like manner as they have dealt with you;
for they were no more than a rod in the hand of the Lord for a season,
and they must also be broken and cast into the fire.
And whether the Lord may ever make use of you to reprove them,
as he did of them to reprove you, this I determine not,
but leave it to Him who can bring about whatever He will, by what instrument He pleases.
It is true, you have made many attempts to revenge yourselves upon them,
but you have not hitherto prospered; but if you would allow yourselves to be humbled,
and come into the meek Spirit of the Lord, then you might prosper.
Hitherto the Lord has always defeated you,
and bowed you down under a people as unworthy as others;
but their time will come to an end.
Submit therefore unto the will of the Lord in what has come to pass,
and seek not vengeance to yourselves, and then the Lord will avenge your cause;
for the iniquities of your adversaries are ripe.
And Charles Stuart must either be converted to God and ruled by Him,
or else he can never rightly rule for God in this nation; though this I believe,
it is not impossible but that he may be a rod to smite those who once smote him;
and their oppressions and ambitions may receive a check through him.

--

Among several other eminent preachers,
Stephen Crisp had now also become a public minister of the word of God;
and it was about this time that he went to Scotland, to preach the gospel there,
and to edify the churches with his gift.

This year, G. Fox the younger wrote an exhortation to the military officers and the army,
showing them how they had departed from their first integrity,
and fallen into pride and wantonness.

G+++.+++ Fox the elder, about the Tenth month, was at Norwich,
where a meeting had been appointed.
The mayor having received notice of it,
intended to have given out a warrant to apprehend him, but having heard of this,
he sent some of his friends to the mayor to speak with him about it.
His answer was, that he feared such a meeting would cause tumults in the town.
But being spoken to in a kind way, he behaved himself moderately,
and a large peaceable meeting was held; to which, among others,
several priests also came, and among these was one Townsend, who stood up and cried,
"`Error, Blasphemy!`" etc.
G+++.+++ Fox desired him not to burden himself with that which he could not prove.
But he asserted it to be error and blasphemy that G. Fox had said
that people must wait upon God by His power and Spirit,
and feel His presence when they did not speak words.
Upon this,
G+++.+++ Fox asked him whether the apostles and holy men of God did not hear
God speak to them in silence before they spoke forth the Scripture,
and before it was written?
He replied "`Yes,`" and confirmed it by saying plainly,
that David and the prophets did so.
Then G. Fox showed people how absurd it was that
Townsend had called such a practice error and blasphemy.
This so puzzled Townsend, that he said,
"`O this is not that George Fox I would speak with; but this is a subtle man.`"
Now when some of the auditory called to the priest,
and bade him prove the blasphemy and error with which he had charged G. Fox,
he went away; and being afterwards spoken to by George Whitehead and Richard Hubberthorn,
who were then also in Norwich, he was soon confounded and humbled.

The committee of safety being now in power,
Edmund Ludlow continued to urge the restoring of the parliament; and general Monk,
who commanded the army in Scotland and aimed at the restoration of the king,
yet wrote to the speaker, William Lenthal, that he would act for the parliament;
and so it was restored.

G+++.+++ Fox the younger, wrote a letter to this parliament,
wherein he told them that their day was turned into darkness,
and that the sun was gone down over them; yes, that the decree had gone out,
and was sealed against them, and it could not be recalled,
with many other remarkable expressions.
He had written at other times to the army and to the parliament,
as did also Richard Hubberthorn, which to avoid prolixity, I pass by.

Let us now again take a view of the persecution in New England.
I have already made mention of Lawrence and Cassandra Southwick, and their son Josiah,
of whom more is to be said hereafter; but first I will speak of Daniel and Provided,
son and daughter of the said Lawrence and Cassandra.
These children,
seeing how unreasonably their honest parents and brothers were dealt with,
were so far from being deterred thereby,
that they rather felt themselves encouraged to follow their steps,
and not to frequent the assemblies of such a persecuting generation.
For their absence they were fined ten pounds,
though it was well known that they had no estate,
their parents being already brought to poverty by their rapacious persecutors.
To get this money, the following order was issued in the general court at Boston.

[.embedded-content-document.legal]
--

Whereas Daniel Southwick, and Provided Southwick, son and daughter of Lawrence Southwick,
absenting themselves from the public ordinances,
have been fined by the courts of Salem and Ipswich, pretending they have no estates,
and resolving not to work, the court,
upon perusal of a law which was made upon the account of debts,
in answer to what should be done for the satisfaction of the fines,
resolves that the treasurers of the several counties are,
and shall be fully empowered to sell the said persons
to any of the English nation at Virginia,
or Barbados, to answer the said fines, etc.

[.signed-section-signature]
Edward Rawson, Secretary

--

The subject of this order was answered effectually at length in print by George Bishop,
who showed the unreasonableness of this work very plainly from sacred writ;
as from Amos 2:6,
where the judgments of God are denounced against those who sold the righteous for silver,
and the poor for a pair of shoes; and from Levit.
25:42, where making bondmen of the children of Israel is expressly forbidden;
this being not lawful except in the case of theft,
if the thief had nothing to make satisfaction with.
But to return to Daniel and Provided,
there lacked nothing but the execution of the said order against them.
Wherefore Edmund Butter, one of the treasurers, to get something of the booty,
sought for a passage to send them to Barbados for sale,
but none were willing to take or carry them; and a certain master of a ship,
to put the thing off, pretended that they would spoil all the ship`'s company.
To this Butter replied, "`No, you need not fear that,
for they are poor harmless creatures, and will not hurt anybody.`"
"`Will they not?`"
replied the shipmaster,
"`and yet you will offer to make slaves of such harmless creatures?`"
Thus, seeing that the winter was at hand, Edmund Butter,
in spite of his wicked intentions, sent them home again to fend for themselves,
till he could find a convenient opportunity to send them away.

It happened also in this year, that a girl about eleven years old, named Patience Scot,
whose religious mother had been cruelly whipped by these people,
bore witness against their wicked persecution;
which so incensed the persecutors that they sent her to prison.
But being examined by the magistrates,
the child spoke so well to the purpose that she confounded her enemies;
some of whom declared that they had many children who had been well educated,
but that "`it would be well if they could say half so much for God,
as she could for the devil.`"
But this child, not being of years to be offensive to the law, however wicked they were,
it seems they could not resolve to proceed to banishment, as they did with others.

All that hitherto I have said of the New England persecution is but cursory,
and only a very small part of those manifold whippings that were inflicted there;
besides the extortions of fines, which were exorbitant to a high degree,
as may appear by what was done to William Maston, at Hampton.
This man was fined ten pounds for two books found in his house,
five pounds for not attending their church, and three pounds besides,
as supposedly due to the priest; and not being free in conscience to pay this fine,
he had taken from him what amounted to more than twenty pounds.
I find also, that not long after this time,
above a thousand pounds was extorted from some,
only because they had separated themselves from the persecuting church.
Such as these, it seems, were also accounted shut out from the protection of the law;
insomuch that Thomas Prince, governor of Plymouth, did not hesitate to say that,
in his conscience, the Quakers were such a people that deserved to be destroyed, they,
their wives and children, their houses and lands, without pity or mercy.
I find also that one Humphrey Norton at New Haven, for being a Quaker,
was whipped severely, and burnt in the hand with the letter H. to signify heretic.

This cruelty of the English did also stir up the Dutch to persecution;
for without inquiring what kind of people the Quakers were,
they seemed ready to conclude them to be men of pernicious opinions,
since the leaders of their own nation,
who pretended to more purity than other Protestants, did so severely persecute them.

It happened that one Robert Hodshone, being in the Dutch plantation at Hamstead,
had a meeting with some of his friends that were English, and who lived there;
but as he was walking in an orchard, an officer came and took hold of him,
and brought him before one Gildersleve, an Englishman and a magistrate there,
who committed him to prison, and rode to the Dutch governor to acquaint him therewith.
Coming back with a guard of musketeers,
the fiscal searched the prisoner and took away his knife, papers, and bible,
and then bound him, and kept him so all that night and the next day.
And making inquiry to find those who had entertained him,
he took into custody two women on that occasion, one of whom had two small children,
the one still nursing.
Then they got a cart and carried the women away in it,
and Robert was fastened to the hinder part of the cart, bound,
and thus drawn through the woods at night, whereby he was much torn and abused.
And having come to New Amsterdam (now New York),
he was loosed and led by the rope with which he had been fastened to the cart,
to the dungeon, being a filthy place, full of vermin;
and the two women were carried to another place.
Sometime after this he was examined,
where one captain Willet of Plymouth much incensed the governor against him,
who before had been moderate.
At the conclusion, a sentence was read to Robert in Dutch, to this effect:
that he was to work two years at the wheelbarrow with a negro, or pay,
or cause to be paid, six hundred guilders.
To this he attempted to make his defense in a sober way, but was not allowed to speak,
and was sent to the dungeon again, where no English were allowed to come to him.
After some days he was taken out and bound,
and being set with his face towards the court chamber, his hat was taken off,
and another sentence was read to him in Dutch, which he did not understand;
but that it displeased many of that nation did appear by the shaking of their heads.
Then he was cast again into the dungeon, where he was kept some days.

At length, early in the morning, he was hauled out and chained to a wheelbarrow,
and commanded to work; to which he answered, he was never brought up,
nor accustomed to such work.
Upon which they made a negro to take a pitched rope, near four inches around,
and beat him until Robert fell down.
Then they picked him up again,
and caused the negro to beat him with the said rope until he fell down the second time,
and it was believed that he received about one hundred blows.
Thus he was kept all that day in the heat of the sun, chained to the wheelbarrow,
his body being much bruised and swelled with the blows.
But though he was kept without food, and grew very faint,
he sat upon the ground with his mind retired to the Lord and resigned to His will,
whereby he felt himself supported.
At night he was locked up again in the dungeon,
and the next morning he was chained again to the wheelbarrow,
and a sentinel was set over him, that none might so much as to speak with him.
On the third day he was brought forth and chained in like manner;
and it is no wonder that he still refused to work,
for besides the unreasonableness of requiring such
servile work of a man who had committed no evil,
he was not in a condition to perform it,
being made altogether unable by the cruel blows that were given to him.
In this weak state he was brought before the governor who demanded him to work,
"`otherwise,`" he said, "`you shall be whipped every day.`"
Robert asked him what law he had broken, and called for his accusers,
that he might know his transgression.
But instead of receiving an answer he was chained to the wheelbarrow again and threatened,
that if he spoke to anyone, he would be punished worse.
Yet he did not forbear to speak to some that came to him,
according as he saw fit and thought convenient.
Then seeing they could not keep him silent, they put him into the dungeon again,
and kept him close there three days and two nights;
one day and a half of it without bread or water.

After this, he was brought very early in the morning into a private room,
and stripped to the waist, and hung up by his hands,
with a great wooden log tied to his feet, so that he could not turn his body.
Then a strong negro was made to whip him with rods, who laid many stripes upon him,
which cut his flesh very much.
He was then let down again, and put into the dungeon as before,
and none were permitted to come to him.
Two days after this he was brought forth again and hung up as before,
and many more stripes were laid upon him by another negro.
Almost fainting, and not knowing but his life might be taken away,
he desired that some English might be permitted to come to him; which was granted,
and an Englishwoman came and washed his stripes,
finding him brought so low that she thought he would not live till the next morning.
And she telling this to her husband, it made such an impression upon him,
that he went to the fiscal and offered him a fat ox,
to permit Robert to stay at his house until he was well again.
But the fiscal would not permit this unless the whole fine was paid.
And though there were some that would willingly have paid the fine for him,
yet he could not consent to it.
But within three days after he had thus been whipped, he was made whole,
and as strong as before, and was free to labor, that he might not be burdensome to any.

Some others of those called Quakers,
who had came there from the plantations in New England to enjoy liberty of conscience
(and whose names and sufferings I pass by for brevity`'s sake),
met also with hard measures from the governor,
by the instigation of the aforesaid Captain Willet.
Robert now being kept like a slave to hard work, it raised compassion in many,
and the governor`'s sister, who was much affected with his sufferings,
became instrumental in obtaining his liberty;
for she so urged her brother that he at length set him free without paying one penny,
or having anybody pay for him.
By this the governor showed that,
though he had been too easily wrought upon to commit evil,
yet he had not come to the same height of malice as the New England persecutors.
For these increased in their hard-heartedness, and became so inured to cruelty,
that if anyone among them would not give his vote for persecution,
he was counted unworthy to be a magistrate; as appears by a letter of one James Cudworth,
written some time before to one of his friends in Old England,
wherein I meet with these words:

[.embedded-content-document.letter]
--

As for the state and condition of things among us, it is sad.
The antichristian persecuting spirit is very active, and that in the powers of this world.
He that will not whip and lash,
persecute and punish men that differ in matters of religion, must not sit on the bench,
nor sustain any office in the commonwealth.
Last election Mr. Hatherly and myself left the bench,
and I was discharged of my captainship because I
had entertained some of the Quakers at my house,
that thereby I might be the better acquainted with their principles.
I thought it better to do so, than with the blind world to censure, condemn, rail at,
and revile them, when they neither saw their persons,
nor knew anything of their principles.
But the Quakers and myself cannot unite in several things;
and so I signified to the court that I was no Quaker,
but must give my testimony against sundry things that they held,
as I had occasion and opportunity.
But nevertheless, I told them, that, "`though I am no Quaker,
neither will I be a persecutor.`"

--

Now I shall enter upon the narrative of their putting some to death, who died martyrs;
for this was yet lacking to complete this tragedy,
which it seems could not be done to the satisfaction
of the actors without playing a murdering part.

The two first that sealed their testimony with their blood were William Robinson,
merchant of London, and Marmaduke Stevenson, a countryman of Yorkshire.
These coming to Boston in the beginning of September,
were sent for by the court of assistants,
and there sentenced to banishment on pain of death.
This sentence was passed also on Mary Dyer, mentioned formerly, and on Nicholas Davis,
who were both at Boston.
But William Robinson, being looked upon as a teacher,
was also condemned to be whipped severely;
and the constable was commanded to get an able man to do it.
Robinson was then brought into the street and there stripped;
and having his hands put through the holes of the
carriage of a great gun where the jailer held him,
the executioner gave him twenty stripes with a three-fold cord whip.
Then he and the other prisoners were shortly released and banished;
and that this was for no other reason than their being Quakers,
may appear by the following warrant:

[.embedded-content-document.legal]
--

You are required by this, presently to set at liberty William Robinson,
Marmaduke Stevenson, Mary Dyer, and Nicholas Davis,
who by an order of the court and council, had been imprisoned,
because it appeared by their own confession, words, and actions, that they are Quakers;
wherefore a sentence was pronounced against them
to depart this jurisdiction on pain of death,
and that they must answer it at their peril, if they,
or any of them after the 14th of this present month, September,
are found within this jurisdiction, or any part thereof.

[.signed-section-signature]
Edward Rawson.

[.signed-section-context-close]
Boston, September 12, 1659.

--

Now though Mary Dyer and Nicholas Davis left that jurisdiction for that time,
yet W. Robinson and M. Stevenson, though they departed the town of Boston,
could not yet resolve (not feeling free in their minds) to depart that jurisdiction,
though their lives were at stake.
And so they went to Salem,
and some places thereabout to visit and build up their friends in the faith.
But it was not long before they were taken and put again into prison at Boston,
with chains locked to their right legs.
In the next month Mary Dyer also returned, and as she stood before the prison,
speaking with one Christopher Holder,
who had come there to inquire for a ship bound for England where he intended to go,
she was also taken into custody.
Thus they had three persons, who, according to their sanguinary law,
had forfeited their lives.
And on the 20th of October, these three were brought into the court,
where John Endicot and others were assembled.
And being called to the bar, Endicot commanded the jail-keeper to pull off their hats:
and then said that they had made several laws to keep the Quakers from coming among them,
and that neither whipping, nor imprisoning, nor cutting off ears,
nor banishing upon pain of death, would keep them away.
And further he said, that he or they desired not the death of any of them;
yet notwithstanding, his following words, without more ado, were, "`Give ear,
and hearken to your sentence of death.`"
William Robinson then desired that he might be permitted to read a paper,
giving an account of the reason why he had not departed that jurisdiction.
But Endicot would not allow it to be read, and said in a rage, "`You shall not read it,
nor will the court hear it read.`"
Then Robinson laid it on the table.
This paper had been written the day before, and in it he related how,
being in Rhode Island,
the Lord had commanded him to go to Boston and to lay down his life there,
and that he had also felt an assurance that his soul
was to enter into everlasting peace and eternal rest.
This command he dared not but obey, without inquiring further concerning it,
believing that it was fitting for him as a child to show obedience to the Lord,
without any unwillingness.
This, he stated, was the cause why after banishment on pain of death,
he stayed in their jurisdiction; and now with sincerity of heart he could say,
"`Blessed be the Lord, the God of my life, who has called me hereunto,
and counted me worthy to testify against wicked and unjust men,`" etc.
This paper being handed to Endicot, he read it to himself, and after he had done,
said to Robinson, "`You need not make such ado to have it read;
for you spoke yesterday more than what is here written.`"
Yet this was not so;
for the paper contained a circumstantial relation of the divine operations on his mind,
explaining that he had not come there in his own will, but in obedience to his Creator;
and that traveling in Rhode Island, on the 8th of the Eighth month,
he had been moved thereto from the Lord,
and therefore had submitted to His divine pleasure without murmuring.
Robinson requested again that the paper might be read,
so that all who were present might hear it.
But this was denied him, and Endicot said,
"`W. Robinson hearken to your sentence of death;
you shall be taken back to the place from which you came (that is, the prison),
and from there to the place of execution,
to be hanged on the gallows till you are dead.`"
This sentence was not altogether unexpected to W. Robinson;
for it was four months now that he had believed that this would be his lot.

Robinson being taken away, M. Stevenson was called, and Endicot said to him,
"`If you have anything to say, you may speak.`"
Knowing how they dealt with his companion, he was silent,
though he had also written in prison a paper containing
the cause of his having come there;
but he kept it with him, and afterwards found occasion to deliver it to somebody.
Then Endicot pronounced sentence of death against him, saying, "`Marmaduke Stevenson,
you shall be taken to the place from which you came, and from there to the gallows,
and there be hanged till you are dead.`"
Whereupon M. Stevenson spoke thus: "`Give ear, you magistrates, and all who are guilty;
for this the Lord has said concerning you, and will perform His word upon you,
that the same day you put His servants to death,
shall the day of your visitation pass over your heads,
and you shall be cursed forevermore.
The mouth of the Lord of hosts has spoken it.
Therefore in love to you all, I exhort you to take warning before it be too late,
that so the curse may be removed.
For assuredly if you put us to death, you will bring innocent blood upon your own heads,
and swift destruction will come upon you.`"

After he had spoken this, he was taken away, and Mary Dyer was called,
to whom Endicot spoke thus: "`Mary Dyer, you shall go to the place from which you came,
and from there to the place of execution, and be hanged there until you are dead.`"
To which she replied, "`The will of the Lord be done.`"
Then Endicot said, "`Take her away, marshal.`"
To which she returned, "`Yes, joyfully I go.`"
And in her going to the prison, she often uttered speeches of praise to the Lord; and,
being full of joy she said to the marshal, he might let her alone,
for she would go to the prison without him.
To which he answered, "`I believe you, Mrs.
Dyer; but I must do what I am commanded.`"
Thus she was led to prison,
where she was kept a week with her other two companions that were also condemned to die.

The paper of Marmaduke Stevenson, mentioned before,
which he gave forth after he had received sentence of death, was as follows:

[.embedded-content-document.paper]
--

In the beginning of the year 1655, I was at the plough, in the east parts of Yorkshire,
in Old England, near the place where my outward habitation was,
and as I walked after the plough I was filled with
the love and presence of the living God,
which did ravish my heart when I felt it;
for it did increase and abound in me like a living stream.
The love and life of God did run through me like precious ointment,
giving a pleasant smell, which made me to stand still; and as I stood a little still,
with my heart and mind stayed upon the Lord,
the word of the Lord came to me in a still small voice, which I did hear perfectly,
saying to me, in the secret of my heart and conscience,
"`I have ordained you a prophet unto the nations.`"
And at the hearing of the word of the Lord, I was put to a stand,
being that I was but a child for such a weighty matter.
So at the time appointed, Barbados was set before me,
unto which I was required of the Lord to go, and leave my dear and loving wife,
and tender children; for the Lord said unto me immediately by His Spirit,
that He would be as a husband to my wife, and as a father to my children,
and they should not lack in my absence, for He would provide for them when I was gone.
And I believed that the Lord would perform what He had spoken,
because I was made willing to give up myself to His work and service,
to leave all and follow Him, whose presence and life is with me,
where I rest in peace and quietness of spirit (with my dear brother),
under the shadow of His wings.
He has made us willing to lay down our lives for His own name sake,
if unmerciful men be allowed to take them from us; and if they do,
we know we shall have peace and rest with the Lord forever in His holy habitation,
when they shall have torment night and day.

So, in obedience to the living God, I made preparation to pass to Barbados,
in the Fourth month, 1658.
And after I had been some time on the said island in the service of God,
I heard that New England had made a law to put the servants of the living God to death,
if they returned after they were sentenced away, which did affect me at that time.
And as I considered the thing, and pondered it in my heart,
immediately the word of the Lord came unto me, saying,
"`You know not but that you may go there.`"
But I kept this word in my heart, and did not declare it to any until the time appointed.
So, after that, a vessel was made ready for Rhode Island, which I passed in.
So, after a little time that I had been there,
visiting the seed which the Lord has blessed, the word of the Lord came unto me, saying,
"`Go to Boston with your brother William Robinson.`"
And at His command I was obedient, and gave up myself to do His will,
that so His work and service may be accomplished: for He has said unto me,
that He has a great work for me to do; which is now come to pass.
And for yielding obedience to, and obeying the voice and command of the ever-living God,
who created heaven and earth, and the fountains of waters, do I, with my brother,
suffer outward bonds near unto death.
And this is given forth to be upon record, that all people who hear it may know,
that we came not in our own wills, but in the will of God.
Given forth by me, who am known to men by the name of

[.signed-section-signature]
Marmaduke Stevenson.

[.signed-section-context-close]
But having a new name given me, which the world knows not of, written in the Book of Life.

[.signed-section-context-close]
Written in Boston prison, in the 8th Month, 1659.

--

Mary Dyer being returned to prison, wrote the following letter,
which she sent to the rulers of Boston.

[.embedded-content-document.letter]
--

[.salutation]
To the General Court in Boston.

Whereas I am by many charged with the guiltiness of my own blood;
if you mean by my coming to Boston, I am therein clear and justified by the Lord,
in whose will I came, who will require my blood of you, be sure,
who have made a law to take away the lives of the
innocent servants of God if they come among you.
These are called by you "`cursed Quakers,`" although I say,
and am a living witness for them and the Lord,
that He has blessed them and sent them unto you.
Therefore be not found fighters against God,
but let my counsel and request be accepted with you, to repeal all such laws,
so that the Truth and the servants of the Lord may have free passage among you,
and you be kept from shedding innocent blood,
which I know many of those among you would not do, if they knew it so to be;
nor can the enemy that stirs you up thus to destroy His holy seed,
in any measure compensate for the great damage that you will procure by thus doing.

Therefore, seeing the Lord has not hid it from me, it lies upon me,
in love to your souls, thus to persuade you.
I have no self-ends (the Lord knows); for even if you were to grant me my life,
it would not avail me, nor could I expect it of you,
so long as I should daily hear or see the sufferings of this people, my dear brethren,
and the seed with whom my life is bound up, as I have done these two years;
and now such suffering is likely to increase, even unto death, for no evil doing,
but only for coming among you.
Was ever such a law heard of among people that profess Christ having come in the flesh?
And have you no other weapons but such laws,
with which to fight against "`spiritual wickedness,`" as you call it?
Woe is me for you!
Of whom do you take counsel?
Search with the light of Christ in you, and it will show you of whom,
as it has done for me and many more, who have been disobedient and deceived,
as now you are.
And as you come into this light, and obey what is made manifest to you therein,
you will not regret that you were kept from shedding blood, though it were by a woman.
It is not my own life I seek (for I choose rather to suffer with the people of God,
than to enjoy the pleasures of Egypt), but the life of the seed,
which I know the Lord has blessed,
and therefore the enemy seeks thus vehemently to destroy it`'s life,
as he ever has done in all ages.
O hearken not unto him, I beseech you, for the seed`'s sake, which is one in all,
and is dear in the sight of God; for they that touch this, touch the apple of His eye,
and cannot escape His wrath.
And I, having felt this wrath,
cannot but persuade all men (especially you who name the name of
Christ) to depart from such iniquity as shedding blood,
even the blood of the saints of the Most High.

Therefore let my request have as much acceptance with you, if you be Christians,
as Esther`'s had with Ahasuerus,
whose relation comes short of that which is between Christians;
and my request is the same that hers was.
For the king said not that he had made such a law,
and it would be dishonorable for him to revoke it; but rather,
when he understood that those people were so prized by her,
and so nearly concerned her (as in truth these people are to me),
you may see what he did for her.
Therefore I leave these lines with you,
appealing to the faithful and true witness of God, which is one in all consciences,
before whom we must all appear, and with whom I shall eternally rest,
in everlasting joy and peace, whether you will hear or forbear.
With Him is my reward, with whom to live is my joy, and to die is my gain,
even if I had not been given your forty-eight hours warning
for the preparation of the death of Mary Dyer.

And know this also,
that if (through the enmity) you shall declare yourselves worse than king Ahasuerus,
and so confirm your law, though it is by the taking away of one of our lives,
that the Lord will overthrow both your law and you by His
righteous judgments and plagues poured justly upon you,
who now, while you are warned thereof, and tenderly sought unto,
may avoid the one by removing the other.
If you neither hear nor obey the Lord, nor His servants,
yet will He send more of His servants among you, so that your end shall be frustrated,
who think to restrain those you call "`cursed Quakers`" from coming among you,
by anything you can do to them.
Yes, verily, He has a seed here among you for whom we have suffered all this while,
and yet suffer.
And the Lord of the harvest will send forth more laborers to gather
them out of the mouths of the devourers of all sorts,
into His fold, where He will lead them into fresh pastures,
even the paths of righteousness, for His name`'s sake.
Oh, let none of you put this good day far from you,
which verily in the light of the Lord I see approaching,
even to many in and about Boston,
which is the bitterest and darkest place professing Christianity that ever I heard of.
Let the time past, therefore,
suffice for such a profession as brings forth such fruits as these laws are.
In love, and in the spirit of meekness, I again beseech you,
for I have no enmity towards any individual; but you shall know,
that God will not be mocked; but what you sow, that shall you reap from Him,
who will render to everyone according to the deeds done in the body,
whether good or evil.
Even so be it, says

[.signed-section-signature]
Mary Dyer.

[.postscript]
====

A copy of this was given to the general court after
Mary Dyer had received sentence of death,
about the 8th or 9th month, 1659.

====

--

The day appointed to execute the bloody sentence was the 27th of October,
when in the afternoon the condemned prisoners were led to the gallows
by the marshal Michaelson and captain James Oliver,
with a band of about two hundred armed men, besides many horsemen;
as if they were afraid that some of the people would have rescued the prisoners.
And that no actors on the stage might be lacking, the priest Wilson joined the company,
who, when the court deliberated how to deal with the Quakers, had said, "`Hang them,
or else...`" (drawing his finger across his throat, as if he would have said,
"`Dispatch them this way`"). So the march began,
and a drummer going ahead before the condemned beat the drums,
especially when any of them attempted to speak.
Glorious signs of heavenly joy and gladness were
beheld in the countenances of these three persons,
who walked hand in hand, Mary being the middlemost.
This made the marshal say to her (who was an elderly man),
"`Are not you ashamed to walk thus hand in hand between two young men?`"
"`No,`" she replied,
"`this is to me an hour of the greatest joy I could enjoy in this world.
No eye can see, nor ear can hear, no tongue can utter, and no heart can understand,
the sweet income and the refreshing influence of
the Spirit of the Lord which now I feel.`"
Thus going along, William Robinson said, "`This is your hour, and the power of darkness.`"
But immediately the drums were beaten;
yet shortly after the drummers left off their beating, Marmaduke Stevenson said,
"`This is the day of your visitation, wherein the Lord has visited you.`"
More he spoke, but he could not be understood by reason of the drums being beaten again.
Yet they went on with great cheerfulness, as going to an everlasting wedding feast,
and rejoicing that the Lord had counted them worthy
to suffer death for His name`'s sake.

When they had come near the gallows,
the priest said in a taunting way to William Robinson,
"`Shall such jacks as you come before authority with their hats on?`"
To which Robinson replied, "`Mind you, mind you,
it is for the not putting off the hat we are put to death!`"
Now having come to the ladder, they took leave of each other with tender embraces,
and then Robinson went cheerfully up the ladder, and having got up, said to the people,
"`This is the day of your visitation, wherein the Lord has visited you:
this is the day the Lord has risen in His mighty power to be avenged on all His adversaries.`"
He also signified that he suffered not as an evil-doer,
and then desired the spectators to mind the light that was in them; that is,
the Light of Christ, of which he testified, and was now going to seal it with his blood.
This so incensed the envious priest that he said, "`Hold your tongue; be silent;
you are going to die with a lie in your mouth.`"
The rope being now about his neck, the executioner bound his hands and legs,
and tied his neckcloth about his face.
This being done, Robinson said,
"`Now you are made manifest;`" and the executioner being just about to turn him off,
he said, "`I suffer for Christ, in whom I live, and for whom I die.`"
He being turned off, Marmaduke Stevenson stepped up the ladder, and said,
"`Be it known unto all this day, that we suffer not as evil-doers,
but for conscience sake.`"
And when the hangman was about to turn him off, he said,
"`This day shall we be at rest with the Lord;`" and so he was turned off.

Mary Dyer seeing her companions hanging dead before her, also stepped up the ladder;
but after her coats were tied about her feet, the halter put about her neck,
and her face covered with a handkerchief, (which the priest Wilson lent the hangman),
just as she was about to be turned off, a cry was heard, "`Stop, for she is reprieved!`"
Her feet then being loosed, they bade her come down.
But she whose mind was already as it were in heaven, stood still,
and said she was there willing to suffer as her brethren did,
unless they would annul their wicked law.
Little heed was given to what she said, but they pulled her down,
and taking her by the arms, the marshal and others carried her to prison again.
That she thus was freed from the gallows, this time, was at the intercession of her son,
to whom it seems they could not then resolve to deny that favor.
Having heard why she was reprieved, the next day, being the 28th of October,
she wrote the following letter to the court.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
The 28th of the Eighth month, 1659.

Once more to the general court assembled in Boston, speaks Mary Dyer, even as before.
My life is not accepted, neither does it avail me,
in comparison with the life and liberty of the Truth, and the servants of the living God,
for which in love and meekness I entreated you.
Yet, nevertheless, with wicked hands you have put two of them to death,
which makes me to feel that "`the mercies of the wicked are cruel.`"
I rather choose to die than to live, as from you, being guilty of their innocent blood.
But seeing that my desire is hindered,
I leave you to the righteous Judge and searcher of all hearts, who,
with the pure measure of light He has given to every man to profit withal,
will in His due time let you see whose servants you are,
and of whom you have taken counsel, which I desire you to search into;
but all His counsel has been slighted, and you have desired none of His reproofs.
Read your portion in Prov.
1:24-32. For verily the night comes on you quickly, wherein no man can work,
in which you shall assuredly fall before your own master.

In obedience to the Lord, whom I serve with my spirit, and in pity to your souls,
which you neither know nor pity, I can do no less than once more to warn you,
to put away the evil of your doings.
Kiss the Son, the light that is in you, before His wrath be kindled in you; for indeed,
where His wrath is kindled,
there nothing outside of you can help or deliver you out of His hand;
and if these things prove not to be so,
then you can say there has been no prophet from the
Lord sent among you (for though we are nothing,
yet by things that are not, it is His pleasure to bring to nought the things that are).

When I heard your last order read, it was a disturbance unto me,
who was then so freely offering up my life to Him that gave it to me,
and who sent me here so to do; which obedience being His own work,
He gloriously accompanied with His presence and peace and love in me,
in which I rested from my labor; until by your order and the people,
I was so far disturbed that I could not retain any more of the words thereof,
except that I should return to prison and there remain forty-eight hours;
to which I submitted, finding nothing from the Lord to the contrary,
that I may know what His pleasure and counsel is concerning me, on whom I now wait.
Truly He is my life, and the length of my days; and as I said before,
I came at His command, and go at His command.

[.signed-section-signature]
Mary Dyer.

--

The magistrates now perceiving that putting William Robinson and Marmaduke
Stevenson to death caused great discontent among the people,
resolved to send Mary Dyer away, thereby to calm their minds a little.
And so she was put on horseback,
and by four horsemen conveyed fifteen miles towards Rhode Island,
where she was left with a horse and a man to be conveyed the rest of the way,
which she soon sent back, and so returned home.
By the style of her letters, and her undaunted carriage,
it appears that she had indeed some extraordinary qualities.
I find also that she was of a comely and grave countenance, of a good family and estate,
and a mother of several children; but her husband it seems was of another persuasion.

I now leave her at home, and go on to relate that one John Chamberlain,
an inhabitant of Boston, having seen the execution of W. Robinson and M. Stevenson,
was so reached by their pious words,
that he received the doctrine of the Truth for which they died.
But his visiting those who were then in prison was so ill-resented,
that afterwards he was whipped several times.
Also, one Edward Wharton, an inhabitant of Salem,
having said that the guilt of Robinson and Stevenson`'s blood was
so great and heavy that he was not able to bear it,
was, for this his pretended impertinence,
whipped with twenty lashes and fined twenty pounds.

But before I take leave of the persons that were hanged, I must say, that being dead,
their countenances still looked fresh (for the terror of death
had not seized them.) But being cut down from the rope,
they were very barbarously treated; for none taking hold of their bodies,
they fell down on the ground in such a way that thereby
the skull of William Robinson was broken;
and even their shirts were ripped off with a knife,
and their naked bodies cast into a hole which was dug, without any covering.
And when some of their friends desired to have laid their bodies into coffins,
it was denied them.
Neither would they allow the place where the bodies were cast to be fenced with pickets,
lest ravenous beasts might prey upon them.

When the people returned from the execution, many seemed sad and heavy;
and coming to the drawbridge, one end of it fell upon some, and several were hurt,
especially a wicked woman who had reviled the two men at their death.
But now this woman was so bruised, that her flesh rotted from her bones,
which made such an offensive stink that people could not endure to be with her;
and in this miserable condition she remained until she died.
But the magistrates, instead of taking notice of this, grew more hardened;
and priest Wilson went so far as to compose a ballad
about the men who had been executed.

Now I return again to Mary Dyer, who having come to Rhode Island,
went from there to Long Island, where she stayed the most part of the winter.
Then, coming home again, she was moved to return to the bloody town of Boston,
where she came on the 21st of the Third month, 1660,
and on the 31st she was sent for by the general court.
Having come, the governor, John Endicot, said,
"`Are you the same Mary Dyer that was here before?`"
For it seems he was expecting an evasion from her,
there having been another of the same name who recently returned from Old England.
But she was so far from disguising herself, that she answered undauntedly,
"`I am the same Mary Dyer that was here the last general court.`"
Then Endicot said, "`You will acknowledge yourself a Quaker, will you not?`"
To which Mary Dyer said, "`I acknowledge myself to be reproachfully so called.`"
Then the jailer (who also desired to say something) said, "`She is a vagabond.`"
And Endicot said, "`This sentence was past upon her the last general court,
and now likewise: You must return to the prison,
and there remain till tomorrow at nine o`'clock;
then from there you must go to the gallows, and there be hanged till you are dead.`"
To which Mary Dyer said, "`This is no more than what you said before.`"
And Endicot returned, "`But now it is to be executed;
therefore prepare yourself tomorrow at nine o`'clock.`"
She then spoke thus:
"`I came in obedience to the will of God during the last general court,
desiring you to repeal your unrighteous laws of banishment on pain of death;
and the same is my work now, and my earnest request; although I told you,
that if you refused to repeal them,
the Lord would send others of His servants to witness against them.`"
Hereupon, Endicot asked her whether she was a prophetess?
And she answered that she simply spoke the words that the Lord spoke in her;
and now the thing had come to pass.
And beginning to speak of her call, Endicot cried, "`Away with her; away with her.`"
So she was brought to the prison house where she had been before,
and was kept shut up until the next day.

About the appointed time the marshal Michaelson came and called her to come out hastily;
and coming into the room where she was, she desired him to stay a little;
and speaking mildly, said, she would be ready presently.
But he being of a rough temper, said he could not wait upon her,
but she must wait upon him.
One Margaret Smith, her companion, being grieved to see such hard-heartedness,
spoke something against their unjust laws and proceedings; to which he said,
"`You shall have your share of the same.`"
Then Mary Dyer was brought forth, and by a band of soldiers was led through the town,
the drums being beaten both before and behind her, and so they continued,
that none might hear her speak all the way to the place of execution,
which was about a mile.
With this guard she came to the gallows, and having gone up the ladder, some said to her,
that if she would return, she might come down and save her life.
To which she replied, "`No, I cannot, for in obedience to the will of the Lord I came,
and in His will I abide faithful unto death.`"
Then captain John Webb said, that she had been there before,
and had received the sentence of banishment upon pain of death,
and had broken the law in coming again now;
and therefore she was guilty of her own blood.
To which she returned, "`No, I came to keep blood-guiltiness from you,
desiring you to repeal the unrighteous and unjust law of banishment upon pain of death,
made against the innocent servants of the Lord;
therefore my blood will be required at your hands, who willfully do it.
But for those that do it in the simplicity of their hearts,
I desire the Lord to forgive them.
I came to do the will of my Father, and in obedience to His will,
I stand even unto death.`"
Then priest Wilson said, "`Mary Dyer, O repent, O repent,
and be not so deluded and carried away by the deceit of the devil!`"
To this Mary Dyer answered, "`No, man, now is not the time to repent.`"
And being asked by some whether she would have the elders pray for her, she said,
"`I know no elders here.`"
Being further asked whether she would have any of the people to pray for her?
She answered that she desired the prayers of all the people of God.
Thereupon some scoffingly said, "`Perhaps she thinks there are none here.`"
She looking about her, said, "`I know but few here.`"
Then they spoke to her again, that one of the elders should pray for her;
to which she replied, "`No, first there must be a child, then a young man,
then a strong man, before there can be an elder in Christ Jesus.`"
After this she was charged with something which was not understood,
but she seemed to hear it, for she said, "`It is false, it is false;
I never spoke those words.`"
Then one mentioned that she had said something of being in paradise.
To which she answered, "`Yes, I have been in paradise several days.`"
And more she spoke of the eternal happiness into which she was now to enter.
And in this well-disposed condition, she was turned off, and died a martyr of Christ,
being twice led to death, which the first time she expected with undaunted courage,
and now she suffered with Christian fortitude.

Thus this honest, valiant woman finished her days.
But so hardened were these persecutors, that one of the court scoffingly said,
"`She hung as a flag for others to take example by.`"
Putting to death for religion did not here cease, as will be related hereafter;
but first I will turn again to Old England,
where there was now great division and a revolution in the state.
