== Chapter X

[.section-date]
1660

About the beginning of this year,
E+++.+++ Burrough wrote the following letter to the parliament,
which then had the power again in their hands.

Friends

All these over-turnings, and almost astonishing changes,
were effected through the justice of the Lord`'s hand.
You are now again at the stern of government, and upon the throne;
and I dare not but say it is of and by the Lord,
and that He has done it contrary to the expectations of many; and what His end is in it,
remains with Him.
But I am sure one cause is that you may execute part of His wrath upon
that treacherous generation of hypocritical and deceitful men,
I mean some who are of the army.
I need not say to you, how many of them were raised up from a low estate; and,
instead of serving the nation, became their lords and oppressors.
They have abused the Lord`'s mercy to them, and exalted themselves,
and so became as great oppressors, and as grievous to the nation,
as ever those were that went before them.
Some of them took the very tithes and estates of their enemies,
and then followed their evil spirit as well, though the Lord was long-suffering to them,
and gave them a day,
and put opportunity into their hands wherein they might have done good;
but they too neglected to serve God and the nation, and preferred themselves.
And because of the ambition and pride of some of them,
the Lord permitted them to make this last interruption upon you,
which was great treachery in man`'s account,
that thereby their measure might be filled up,
and that He might give you occasion against them,
and allow you to be filled with indignation towards them, to break them to pieces;
and what you do to some of them, in casting them out, and afflicting them,
you are but God`'s executioners therein.
For they have long enough disguised themselves in this nation,
in professing more than others, and yet doing less; therefore their downfall is now.
And God has looked upon you as hard-hearted and cruel enough
to be very fit executioners of vengeance upon such men,
as I have mentioned.

But now concerning you and your present state,
as you are presently in position and power, I have something to say to you:
Though they have fallen, and you yet stand, and you have a little time after them,
yet this I say; do not glory over their fall,
neither glory as though you should stand forever;
for they were not greater sinners than you are,
neither are you one bit more righteous than some of them;
but you are as sure to fall as they have fallen,
with no less measure of dishonor and affliction than has come upon them.
You are in your last hour; and I dare say,
that God expects much more from you than to be the
executioners of justice upon men as sinful as yourselves.
So do not glory over those who have fallen, but know that your time also is but short,
and your fall may prove to your destruction,
and theirs may prove to make them better and refine them.
And if God has chosen you to execute some part of His wrath upon them,
because of their wickedness,
He will doubtless find instruments to execute His wrath upon you,
else He will do it with his own hands; for He purposes not to spare you,
for your sins cry as loud as any other people`'s,
and the oppression is as great under you as under those whom you condemn.
And I desire, if there be any good men among you, that such who are wise may consider,
and mind the hand of the Lord in and through all these things that have come to pass;
for God is working as well as you.
He is seeking to set up a kingdom as well as you,
and His government and yours cannot stand together.
He will make you know that He is stronger, and that His government is of more force,
and that your kingdom cannot stand in place with His.

Therefore I say, oh that you would take heed!
Oh that you would be wise, that some of you may be spared!
Be not too zealous in your way, nor too furious in your proceedings;
but do unto others as you intend to receive from others, and also from the Lord.
And go not beyond your commission;
for you have had permission from God to scourge the hypocrites,
and to be a judgment upon that hypocritical and seeming-religious
generation of men aforesaid,
who have many a time, as it were, mocked God and pretended love to Him with their lips,
when their hearts have yearned after self-honor and the treasures of this world.
I say, your present hour and permission is for this end,
but not to persecute the people of the Lord, nor to destroy God`'s heritage.
But if you shall extend your power unto such a work,
and if you will persecute the innocent without cause,
and make war against the Lamb and His followers, and make laws,
and execute them to the oppression of the saints of the Most High,
then you go beyond your commission; for God has not called you unto this,
but to be instruments in another cause.
The children of Zion trust in the living God, and fear not the terror of mighty men,
neither can they be afraid at the roaring of the sea,
nor at the present threatening of the heathen, for God is with them.
And I say unto you,
the servant of the Lord has pondered and considered all these proceedings,
and viewed the present state of things at this day,
and there is no vision from God unto you of peace and comfort,
nor of a happy and lasting government as you now stand.
If any prophet shall foretell this unto you,
he speaks what he has not received from the Lord, but from the vision of his own heart,
and he deceives both you and himself.
For you are not established upon a right foundation,
neither are you acted by a right spirit which can truly govern for God;
but the spirit of wrath and fury is put into you for the work to which you are called.
And I know not how to warn you, that you do not persecute the people of God.
For it may be that you must fill up your measure of wickedness thereby,
that God may break you perpetually; yet your judgment will be the less if you do it not.
But if you do it, the Lord will take occasion against you to wound you,
and you shall never be healed, and according as you afflict others,
so and much more shall it be done unto you from the Lord.

Therefore, consider what I have said; for this is the vision of the Almighty unto you,
which shall not go unfulfilled.
And what you do, you must do it quickly;
for your time is short and God will soon subdue your power,
and He will speedily exalt His kingdom and power over your heads,
and make you and the nations know that He is God, and that all power is with Him,
and that He can do whatever He will.
Indeed, it is His right alone to reign,
and it is His children`'s portion to possess the kingdom with Him.
Let the whole earth, and all the powers thereof, bow and tremble before Him.
Let not your hearts be stout and rebellious against Him, for He can grind you to powder,
and sink you into confusion and misery, as a stone into the sea.

E+++.+++ Burrough

This was directed for the hands of the speaker in parliament,
and accordingly was given to William Lenthal,
being enclosed to him with these lines following:

Friend,

The enclosed letter I do commend unto you to present before the house,
and to endeavor sincerely the reading of it in your assembly;
for it is of special concernment to you all.
And in the name of the Lord, and by His Spirit,
I do charge you not to be negligent in this matter,
as though it were not of worth to you; and I do lay it upon you,
as you will answer the contrary at the dreadful day of God,
when the King of Righteousness shall judge you and all mankind.

E+++.+++ Burrough.

The 24th of the Eleventh month, 1659.

This parliament did so order it that about fifteen hundred military officers were discharged,
and others were put into their places.

About this time George Fox the younger also wrote
a letter to the parliament and the army,
which was as follows:

Your day has turned into darkness; the sun has gone down over you.
You have had a large day, and power given unto you to have done the will of God,
but you have abused the power, and slighted your day;
you have refused to do the Lord`'s work, and have sought to serve yourselves,
and not the Lord.
Therefore the day wherein you might have worked for
God in justice and righteousness is taken from you;
and the thick dark night of confusion has come upon you,
wherein you are groping and stumbling and cannot work.
The decree has gone out, and is sealed against you, and it cannot be recalled.
You are not the men (as you stand) in whom God will appear
in order to work deliverance for His people and creatures;
and yet deliverance shall come, but not according to man`'s expectations.
But as for you, you have rejected the counsel of the Lord, and grieved His Spirit,
and He has long borne with you.
Yes, you have departed from the Lord, and His presence has departed from you.
Indeed He has hewn with you, and if you had been faithful to the end,
He would have honored and prospered you, and would have been your sufficient reward.
You were His axe, but you have boasted yourselves against Him.
Therefore, as you have beaten and hewed and broken others,
even so you must now be beaten, hewed, and broken;
for you have grievously provoked the Lord;
and if He should now allow the tree that you have cut to fall upon you,
and to break part of you, it would be just.

O you treacherous, willful, proud, self-seeking people,
who have despised the counsel of the Lord, and would not take warning,
though He has sent His prophets and servants early and late among you,
some of whom you have imprisoned and despitefully used.
What will you do now?
To whom will you now run for help, seeing you have departed from the Lord,
and are found rending and tearing, biting and devouring one another, for proud,
ambitious, and selfish ends?
And mark this: if you would now build again the thing that you once destroyed,
that shall not be able to hide or shelter you from the wrath of the Lamb;
and that way whereby you think to strengthen yourselves, shall only make you much weaker,
and help bring forward your own destruction.
You are now but a rod, so remember your end, which hastens quickly.
For now breach upon breach, insurrection upon insurrection, overturning upon overturning,
heaps upon heaps, division upon division shall come, until He comes to reign,
whose right it is.
All nations must bow before Him, else He will break them with His iron rod.

They that trust in, or lean upon you for help,
it is as if they leaned upon a broken reed, which is not able to help itself, nor others.
Indeed you have been called to do many good things,
but you would not go through with the work which God desired to be accomplished,
and so these things have come upon you.
Therefore tremble and dread before the Lord,
you who have been like strong oaks and tall cedars, for now your strength shall fail you,
and you shall be weak, even as the weakest of men.
But if you would yet believe in the light,
and truly submit to God`'s righteous judgments,
many of you might still come to witness your souls saved in the day of the Lord;
though (because of your grievous backslidings) many of your bodies
are to be thrown by and counted unworthy to be the Lord`'s workmen.

There is a small remnant yet among you for whom my soul breathes,
who may be winnowed out; and if these will acknowledge the judgments of the Lord,
and truly and thoroughly deny themselves, and follow His leadings,
He will heal their backslidings and purge them,
that so they may be instruments in His hand.
But those who will continue with you in your sins,
shall surely partake with you of your judgments.

The rod of the wicked shall not always rest upon the back of the righteous;
yet even as gold is tried, so shall they be tried,
that they may be white and without spot before the Lamb.
But God will avenge their cause, and then woe will be to all their oppressors.
And then the majesty and the glory of the Lord shall fill His people,
who have long been trodden underfoot, and they shall be the dread of all nations;
the zeal of the Lord of Hosts shall perform this.

George Fox, the younger.11th Month, 1659

This letter being printed,
a copy of it was given to each parliament man before
General Monck and his army came into London.
And how soon the predictions contained therein,
as well as those of E. Burrough in the foregoing year, came to be fulfilled,
when many of the great ones were hanged and quartered,^
footnote:[A form of punishment for those found guilty of treason,
in which the guilty party was first hanged by the neck almost to the point of death,
then emasculated, disemboweled, beheaded, and chopped into four pieces (quartered).
The remains would then often be displayed in a prominent place across the country,
such as the London Bridge, to serve as a warning to others.]
we shall see in what follows.

General Monck now came out of Scotland into England, with part of the army he commanded,
and made great alterations among the officers,
putting in such as were believed to be no enemies to Charles Stuart.
For whatever Monck said of his resolution to be true and faithful to the parliament,
and to promote the interest of a commonwealth,
yet it appeared before long that he aimed at something else;
which design he found to be easier having many adherents in the parliament;
though he did not hesitate to say to Edmund Ludlow, "`We must live and die for, and with,
a commonwealth;`" and to others he declared that he would
oppose to the utmost the setting up of Charles Stuart.
In the meantime,
he so ordered it that many members of the parliament who had been long excluded as unqualified,
took session again in that assembly; and these caused sir George Booth,
who was confined to the Tower for having carried on a design to restore Charles Stuart,
to be set at liberty.
Neither was the city of London in a condition to oppose Monck,
for he caused and doors of the city gates and the posts to be pulled down;
and the royalists had now become so bold that they printed a list of the
names of the judges that had condemned king Charles the First to death.
Some of these men were secured, while others fled away.
General Lambert was also sent to the Tower, and Monck, whose authority now increased,
sent for the lords, who until the year 1648 had sat in parliament,
and bade them return to the house where they formerly used to sit.

In these over-turnings G. Fox came to London in the
time when they were breaking the city gates.
He then wrote a paper to those that were now sinking,
and told them that now the prophecies were being fulfilled
concerning them which had been spoken to them;
and that they who used to call the Quakers "`fanatics,`"
and "`giddy-heads,`" now seemed themselves rather giddy,
and were as fugitives or wanderers.

From London G. Fox went to Sussex, and from there to Dorsetshire.
At Dorchester he had a great meeting in the evening at the inn where he lodged,
and there came many soldiers, who were pretty civil.
But the constables and officers of the town came also,
under the pretense of looking for a Jesuit whose head, they said, was shaved.
So they took off G. Fox`'s hat, but not finding any bald place on his head,
they went away with shame.
This meeting was of good service among the soldiers and others,
and it affected the people, who were turned to the Lord Jesus Christ.

Then he passed into Somersetshire, where his friends meetings were often disturbed.
One time there came a wicked man, who having a bear`'s skin on his back,
played ugly pranks in the meeting;
and setting himself in front of the person that was preaching,
lolled his tongue out of his mouth, and so made sport for his wicked followers,
and caused a great disturbance in the meeting.
But as this man went back from there, an eminent judgment overtook him;
for there being a bull-baiting^
footnote:[A "`blood sport`" that involved pitting an enraged bull against another animal,
usually a dog or a bear.]
along the way, he stayed to watch it; and coming within his reach,
the bull pushed his horn up under the man`'s chin, into his throat,
and forced his tongue out of his mouth so that it hung out in the
same manner as when he had lolled it out in derision in the meeting.
And the bull then running his horn into the man`'s head,
swung him about in a most fearful manner.

G+++.+++ Fox traveling through Somersetshire, came into Devonshire, and so went into Cornwall,
till he came to the Land`'s End.
While he was in Cornwall, there were great shipwrecks near the Land`'s End.
Now it was the custom of that country,
that at such times both rich and poor went out to get as much of the wreck as they could,
not caring to save the people`'s lives; and this custom so prevailed,
that in some parts of the country they called the shipwrecks "`God`'s grace.`"
This grieved G. Fox not a little,
considering how these professed Christians conducted
themselves far worse than the heathen at Malta,
who courteously received Paul and the others that had suffered shipwreck with him,
and made him a fire.
On this consideration, he was moved to write a paper to the magistrates, priests,
and others, both high and low, in which he showed them the wickedness of their deeds,
and reproved them for such greedy actions,
showing them how they were ready to fight with one another for the spoil,
and then to spend what they got in taverns or alehouses,
leaving those who had escaped drowning to go begging up and down the country.
He therefore seriously exhorted them to do unto others
what they would have done to themselves.

This paper was sent to all the parishes thereabouts;
and after having had many meetings in Cornwall where several
eminent people were convinced of the Truth preached by him,
he went to Bristol,
where the meetings of his friends were exceedingly disturbed by the soldiers.
Having heard this, he desired George Bishop, Thomas Gouldney, Thomas Speed,
and Edward Pyot, to go to the mayor and aldermen,
and request them to let his friends have the town-hall to meet in,
provided it should not be on such days when the mayor
and aldermen had business to do in it;
and that for this use they would give twenty pounds
a year to be distributed among the poor.
These four persons were astonished at this proposal,
and said that the mayor and aldermen would think them mad;
for the mayor and the commander of the soldiers had
joined together to make a disturbance in their meetings.
But G. Fox so encouraged them that at last they consented to what he desired.
Having come to the mayor, they found him moderate beyond expectation;
and when they had laid the thing before him, he said, "`For my part,
I could consent to it; but I am but one.`"
So they left him in a loving frame of mind; and coming back,
G+++.+++ Fox desired them to go also to the colonel that commanded the soldiers,
and to acquaint him of their rude carriage, and how they disturbed the meetings.
But the aforesaid four persons were reluctant to go to him.
Next morning, being the First day of the week, a meeting was kept in an orchard,
where many people came; and after G. Fox had been preaching quite a while,
there came several rude soldiers, some with drawn swords, and some drunk,
and among these was one who had bound himself with
an oath to cut down and kill the man that spoke.
But when he came pressing in through the crowd, and was within two yards of G. Fox,
he stopped at those four persons before mentioned, and fell to arguing with them;
and at length his sword was put up again.
The next day they went and spoke with the colonel,
and he having heard how mischievous his soldiers had been, sent for them,
and cut and slashed some of them.
But when this was told to G. Fox, he blamed his four friends,
believing they might have prevented the cutting of the soldiers,
if they had gone to the colonel when he desired them.
Yet this had such effect,
that the meeting there was kept without disturbance for a good while after.

G+++.+++ Fox then also had a general meeting at Edward Pyot`'s, near Bristol,
at which were several thousands of people;
and so many from Bristol attended this meeting that some said the city looked naked,
and all was quiet.

But in other places, about this time, things were not so quiet; for the soldiers,
under general Monck`'s command, were often very rude in disturbing their meetings.
But when complaint was made to him, who was then at Westminister,
he showed that he would not countenance such wickedness, and in this respect,
did better than several other generals had done, for he gave forth the following order.

St. James`'s, March 9, 1659-60.

I do require all officers and soldiers to forbear
to disturb the peaceable meetings of the Quakers,
as they do nothing prejudicial to the parliament or commonwealth of England.

George Monck.

Monck having thus long declared for a commonwealth, and against a king,
began now to take off the mask;
for the old lords had now taken their places again in the House of Peers,
out of which they had been kept so many years.
And by the advice of general Monck,
Charles Stuart (who for several years had lived at Cologne, and,
having made a voyage to Spain,
was from there come to Brussels by way of France) proceeded to Breda, in Holland.
And it now being resolved upon in England to call him back and restore him,
he gave forth the following declaration at Breda;
thereby to persuade those that were yet reluctant to acknowledge him.

Charles, by the grace of God, king of England, Scotland, France, and Ireland,
defender of the faith, etc., to all our loving subjects, of whatever degree or quality,
greetings.

If the general madness and confusion which has spread over the whole kingdom,
does not awaken all men to a desire and longing that those wounds (which
have for so many years together been kept bleeding) may be bound up,
all we can say will be to no purpose.
However, after this long silence,
we have thought it our duty to declare how much we desire to contribute thereunto;
and that as we can never give over the hope,
in good time to obtain the possession of that right
which God and nature has made our due;
so we do make it our daily petition to the Divine Providence, that He will,
in compassion to us and our subjects, after so long a time of misery and suffering,
remit, and put us into a quiet and peaceable possession of that which is our right,
with as little bloodshed and damage to our people as is possible.
Nor do we desire to enjoy what is ours more than we would
see all our subjects enjoy what by law is theirs,
by a full and entire administration of justice throughout the land,
and by extending our mercy where it is needed and desired.

And to the end that the fear of punishment may not incite any,
who are conscious in themselves of what is past,
to a perseverance in guilt for the future by opposing the peace
and happiness of their country in the restoration both of king,
peers, and people, to their just, ancient, and fundamental rights; we do hereby declare,
that we grant a free and general pardon,
which we are ready upon request to affirm under our great seal of England,
to all our subjects, of whatever degree or quality, who,
within forty days after the publishing hereof,
shall lay hold upon this our grace and favor,
and shall by any public act declare their doing so,
and that they return to the loyalty and obedience of good subjects;
excepting only such persons as shall hereafter be excepted by parliament.
Excepting these only, let all our subjects, however they may be at fault,
rely upon the word of a king, solemnly given by this present declaration,
that no crime whatsoever committed against us, or our royal father,
before the publication of this, shall ever rise in judgment,
or be brought into question against any of them, to the least injury of them,
either in their lives, liberties, or estates; or, as far forth as lies in our power,
so much as to the prejudice of their reputations, by any reproach or term of distinction,
from the rest of our best subjects.
We desire and ordain that henceforward all notes of discord, separation,
and difference of parties, be utterly abolished among all our subjects,
whom we invite and call to a perfect union among themselves, under our protection,
for the resettlement of our just rights, and theirs, in a free parliament, by which,
upon the word of a king, we will be advised.

And because the passion and uncharitableness of the
times has produced several opinions in religion,
by which men are now engaged in parties and animosities against each other (who,
when they shall hereafter unite in freedom of conversation,
will perhaps better understand each other),
we do declare a liberty to tender consciences,
and that no man shall be troubled or called in question for differences of opinion
in matters of religion which do not disturb the peace of the kingdom.
And we are ready to consent to such an act of parliament, as, upon mature deliberation,
shall be offered to us for the full granting of this indulgence.

And because, in the continual confusion of so many years,
and so many and great revolutions,
many grants and purchases of estates have been made to and by, many officers, soldiers,
and others, who now possessed the same,
and who may be liable to actions at law upon several titles,
we are likewise willing that all such differences,
and all things relating to such grants, sales, and purchases,
shall be determined in parliament,
which can best provide for the just satisfaction of all men who are concerned.

And we do further declare, that we will be ready to consent to any act,
or acts of parliament, to the purposes aforesaid,
and for the full satisfaction of all financial obligations
due to the officers and soldiers of the army,
under the command of general Monck;
and that they shall be received into our service upon as
good pay and conditions as they now enjoy.

Given under our sign and signet at our court at Breda, this 14th day of April, 1660,
in the Twelfth year of our reign.

The original of this declaration was sent to the House of Lords,
and a duplicate was sent to the House of Commons,
which was copied and sent in a letter to General Monck, the council of state,
and the officers of the army.
Hereupon it was resolved by the parliament to prepare an answer;
and both in the House of Lords, and in the House of Commons,
it was voted to proclaim king Charles at Whitehall, and in London,
as the lawful sovereign of these kingdoms,
which was done on the 8th of the month called May.

Now the king, who by the Spaniards was invited to return to Brussels,
and by the French to come to Calais, chose,
at the pressing invitation of the States-general of the United Provinces,
to go by way of Holland.
And so he went, with the yachts of the States to Rotterdam,
and from there with coaches to the Hague, where having stayed some days,
he took shipping at Schevenningen for England,
and made his entry at London on the anniversary of his birthday.
Thus we see Charles the Second (who not long after was crowned) restored,
not by the sword, but by the marvelous hand of the Lord.

About this time G. Fox the younger came to Harwich,
where he was hauled out of a meeting and imprisoned
under a pretense of having caused a tumult.
But in order to give to the reader a true sight of the matter, I must go back a little.

About four years before this time,
some of the people called Quakers having come into the said town,
one of them spoke a few words by way of exhortation
to the people that came from the steeple-house;
and then passing on, he and those with him went to an inn.
The mayor hearing of this, sent to them and commanded that they should depart the town,
which they did after a short while; but at night they returned and lodged at their inn,
and the next day passed away peaceably.
Not long after this,
the woman who kept the inn was commanded to come before the magistrates,
who threatened to take away her license,
unless she promised to lodge no more such persons.
But though they proved eager to keep out the Quakers, yet it proved ineffectual;
for it seems that some of those who had been spoken to in the streets, were so reached,
that they came to be obedient to the inward teachings
of the Lord to which they had been directed.
And thus a way was made for meetings to begin in the town,
whereby the number of those of that society began to increase.
And because these could no longer comply with the superstitious burials of the times,
they bought a piece of ground in which to bury their dead.
But this met with great opposition; and once, when several came along to bury a corpse,
it was taken from them by force, and set by the seaside,
where having lain above ground part of two days and one night,
it was privately covered by some with small stones.

In the month called May, G. Fox the younger came to Harwich to preach the Truth there.
The mayor of the town, whose name was Miles Hubbard, having heard of this,
stopped several that were going to the meeting.
Then a rude multitude, seeing the people gather, grew insolent,
and made a hideous noise before the house where the meeting was kept,
and some were in favor of pulling the house down.
G+++.+++ Fox hearing the noise while he was preaching, grew very zealous,
and with a mighty power was made to say, "`Woe,
woe unto the rulers and teachers of this nation, who allow such ungodliness as this,
and do not seek to suppress it.`"
Some that heard him thus speaking went and told the magistrates of it,
perhaps not in precisely the same words as were uttered by him.
The officers then coming,
the mayor commanded the constables to take the said G. Fox into custody;
who hearing this, said, "`If I have done anything worthy of death or bonds,
I shall not refuse either; but I desire you to show me what law I have transgressed;
which you ought to do before you send me to prison,
that I may know for what reason I am sent there.`"
But the mayor told him that he would know that afterward;
and so he was carried to prison.

Robert Grassingham, who was a shipbuilder for the admiralty in that port,
being at the meeting from which G. Fox was hauled,
in love went freely along with him to prison.
This seemed to please the mayor,
who some days before had been heard to say concerning Grassingham,
"`If I could but get him out of the town,
I could then know what course to take with the other Quakers.`"
Some time after G. Fox was imprisoned, a court order was sent to the jailer,
in which the prisoner was charged with causing a
tumult in that town and disturbing the peace.
This court order was signed by Miles Hubbard, mayor, Anthony Woolward, and Daniel Smith;
and these magistrates sent notice of what they had done to the parliament,
under the spurious pretense, that so they might not fall into disgrace.
Having received this information, the parliament issued forth the following order:

Monday, May 21,1660.

The house being informed that two Quakers, that is to say,
George Fox and Robert Grassingham, have lately made a disturbance at Harwich,
and that the said George Fox, who pretends to be a preacher,
did lately in his preaching there speak words much
reflecting on the government and ministry,
to the near causing of a mutiny,
and is now committed by the mayor and the magistrates there:

It is therefore ordered that the said George Fox and Robert
Grassingham be immediately brought up in custody;
and that the sheriff of the county of Essex receive them,
and give them his assistance for conveying them up accordingly,
and delivering them into the charge of the sergeant-at-arms attending this house.

It is also ordered,
that the thanks of this house be given to the mayor and magistrates of Harwich,
for their care in this business.

William Jessop, Clerk of the Common House of Parliament.

By this it appeared that the magistrates of Harwich had special friends in the parliament.
Robert Grassingham being at liberty, had gone to London;
and when this order came to Harwich,
G+++.+++ Fox was delivered to the sheriff of Essex and his men.
These went with him to London, and upon the road they met with Grassingham,
who was coming from London to Harwich,
in pursuance of an order which he had received from
the commissioner of the admiralty and navy,
for mending one of the king`'s frigates.
But notwithstanding Grassingham showed his order to the sheriff,
yet he was brought back to London with Fox,
and delivered into the custody of the sergeant-at-arms attending the house,
who committed them to Lambeth house.
Having been there about three weeks,
they wrote a letter to the House of Commons wherein they gave some
account of the manner of their imprisonment and desired that they
and their accusers might be brought face to face before the parliament,
saying that if anything could be proved against them worthy of punishment,
they would not refuse it.
But they thought it unjust and unreasonable that a man should
be hauled out of a peaceable meeting and sent to prison,
without being examined,
only for declaring against the cursing and wickedness of the rude people,
and against such as allowed such ungodliness and did not seek to suppress it.

This was the chief contents of their paper,
which they enclosed in a letter to the speaker of the House of Commons in these words:

For the Speaker of the House of Commons.

Friends,

We desire you to communicate this enclosed letter to the House of Commons,
it being a few innocent, just, and reasonable words to them,
though not in the eloquent language of man`'s wisdom,
yet it is in the truth which is honorable.
We are friends to righteousness and truth, and to all that are found therein.

Robert Grassingham, George Fox.

Nevertheless, the speaker did not deliver the paper,
under pretense that it was not directed with the ordinary title,
"`To the Right honorable the House of Commons.`"
Therefore, by the help of their friends, they got it printed,
that so each member of parliament might have a copy of it.
Now after they had lain about fourteen weeks in Lambeth gate-house without being examined,
one of the members of parliament moved this business in the house;
whereupon the following order was made:

Thursday, October 30th, 1660.

Ordered that George Fox and Robert Grassingham,
who by virtue of a former order of this house,
were taken into custody by the sergeant at arms attending
this house for some disturbance at Harwich,
be immediately released and set at liberty, upon bail first being given for themselves.

William Jessop, Clerk of the House of Commons

Shortly after this order was issued forth,
the sergeant at arms sent his clerk to demand fees and chamber rent from the prisoners,
asking fifty-pounds for fees, and ten shillings a week for chamber rent.
But since no evil had been laid to their charge,
they could not resolve to satisfy this unreasonable demand,
yet offered to pay two shillings and six pence a week,
though the chamber where they had lain was the highest room in a lofty tower,
and all the windows were open until they had gotten them glazed,
without any charge to the sergeant.
Matters standing thus, their cause was referred to the king`'s privy council.
But it was still a good while before they were released;
for several evasions were made use of to keep them in custody.

While G. Fox was prisoner, he wrote a little book which he called,
"`A Noble Salutation to king Charles Stuart,`" wherein
he showed him how matters had gone in England,
namely:
That his father`'s party scorned those that appeared in
arms against them because of their unimpressive appearance;
for they were tradesman, plowmen, servants, and the like;
which contemptible instruments God made use of to bring down the loftiness of the others.
But then, when those of the parliament party grew successful and prevailed,
they got into the place of those they had conquered,
and fell into the same pride and oppression which they had cried out against in others;
and many of them became greater oppressors and persecutors
than the king`'s party had been.
Moreover,
the author exhorted the king to observe the hand of the Lord in restoring of him.
"`Therefore,`" said he, "`Let no man deceive you,
by persuading you that these things are thus brought
to pass because the kingdom was your own proper right,
and because it was withheld from you contrary to all right;
or because those called royalists are much more righteous
than those who are now fallen under you.
For I plainly declare unto you, that this kingdom, and all the kingdoms of the earth,
are properly the Lord`'s. And this you must know, that it was the just hand of God,
in taking away the kingdom from your father and from you, and giving it unto others;
and that it is also the just hand of the Lord to take it again from them,
and bring them under you;
though some of them went beyond their commission against your father,
when they were brought as a rod against you.
And it will be well for you not to become guilty of the same transgressions.`"

The author further exhorted the king to consider that this, his current station,
was not without danger, because of the changeableness of the people,
a great part of whom were perfidious.
For, at one time they had sworn for a king and parliament,
but shortly thereafter swore against a king, a single leader, and a house of Lords;
and then again did swear for a single leader.
A short time after this they extolled a parliament again.
And when Oliver Cromwell had turned out the parliament, and set up himself,
then the priests prayed for him, and asserted his authority to be just.
And when he died, they fawned upon his son Richard,
and blasphemously termed his father "`the light of their eyes,
and the breath of their nostrils;`" and they told Richard,
that "`God had left him to carry on that glorious work which his father had begun.`"
Yes, some priests compared Oliver to Moses, and Richard to Joshua,
who should carry them into the promised land.
Thus they continually flattered those that were at the helm.
And when George Booth made an uprising, and they thought there would be a change,
some of the priests then cried out against the parliament,
and cursed all who would not go out against them.
But when Booth was taken, then many began to petition the parliament,
and to excuse themselves, that they had no hand in that uprising.

Next the author set forth the wickedness of the people who,
with excessive drinking and drunkenness, pretended to show their loyalty to the king;
and he also relates,
how having preached at Harwich against the grievous wickedness of the people,
he was hauled to prison in the king`'s name.
Finally, he exhorts the king to take heed of seeking revenge; and to show mercy.

This paper, which was not a small one, for it took up several sheets,
was delivered in writing by Richard Hubberthorn, into the king`'s hand at Whitehall,
and was not long after published in print by the author.

At this time one of the most eminent royalists drew up several queries to the Quakers,
desiring them to answer them, and to direct their answer with this superscription,
"`Tradite hanc amico Regis,`" that is, "`Deliver this to the king`'s friend.`"
For it had been clearly seen, that several of their predictions came to be fulfilled,
of which those of Edward Burrough were not the least.
And therefore some (as it seems),
thought that by the Quakers they might get some knowledge concerning
whether any stability of the king`'s government was to be expected.
By these queries it appeared that the author of them was a man of understanding,
and of some moderation also; and though I do not know who he was,
yet I am not without thoughts that Edward Hyde, earl of Clarendon, and high chancellor,
may have been the penman thereof.
The tendency of these queries was chiefly to know from the Quakers
what their judgment was concerning the king`'s right to the crown;
and whether they ever did foresee his return,
and also whether they could judge if his reign and government should be blessed or not.
Moreover, it was asked whether he might justly forgive, or avenge himself;
and whether he might allow liberty of conscience to all sorts of people, etc.

Edward Burrough answered these queries, and published his answer in print,
directing it to the king and the royalists.
In it he showed that in some of their writings it had already been
signified that they had some expectations of the king`'s restoration,
and that the king`'s coming to the throne was reasonable and equitable,
being brought about through the purpose of the Lord.
He also stated that his reign and government might be blessed, or not blessed,
according to how he carried himself; and that he might justly forgive his,
and his father`'s enemies; for though he and his father might have been injured,
yet for as much as they had turned to the sword to
determine their controversy with the nation,
so the sword had gone against them; and it was by that whereby they thought to stand,
that they did fall.
And who then should they blame for what befell them, seeing how the sword,
which they themselves did choose, destroyed them.
However, the author signified, that this was not meant in reference to the king`'s death;
that being quite another case.

To the query, whether the great afflictions sustained by the king for several years,
from the subjects of his own nation, and the guilt thereof,
did lie upon all the subjects in general; or upon any,
or upon some particular people who were more guilty than others;
E+++.+++ Burrough made this answer:

In so far as his sufferings were unjust,
the guilt thereof does not lie upon all the subjects in general,
but upon some more than others;
and these are easy to distinguish from others if it be considered
who it was that raised the war in this nation against the king,
and who first preached and prayed up the war,
and prosecuted it against the king`'s father,
and who cast out the bishops and prelates from their places,
and took their revenues and benefices, and became men as corrupt,
covetous and self-seeking, as proud and ambitious, as unjust persecutors,
as ever the men were which they cast out.
And consider also who it is that has gotten great estates in the nation,
and worldly honor, and raised themselves from nothing by these wars,
and by your sufferings; and who took the estates and titles of their enemies,
and pretended to free them from all oppression, but have not done it;
but have rather continued the old oppression,
while striving among themselves about who should rule, and who should be great.

And as for us, who are called Quakers,
we are clear from the guilt of all the king`'s sufferings.
We have not cast out others and taken their places of great benefices,
neither have we made war with carnal weapons against any, ever since we were a people.
Neither have we broken oaths and engagements, nor promised freedom and deliverance,
and then for selfish ends and earthly riches betrayed
(as others have done) what we vowed to do.
And in many particulars it does appear that we are clear from his sufferings,
for we have been a suffering people as well as they,
by the same spirit which caused them to suffer, which has been much more cruel, wicked,
and unjust towards us, than it has been towards them,
though our persecution has been in another manner.
But what they have done against us we can freely forgive them,
and would have you to follow the same example.
And if you could accuse them in many things, so could we;
but this is not a time to accuse one another, but to forgive one another,
and so to overcome your enemies.
When they had gotten the victory, they did not reform, but became oppressors,
and were cruel towards all who would not say and do as they did.
And for this cause the Lord has brought them down,
and may justly allow others to deal with them as they have dealt with others.

Yet notwithstanding I must still say, and it is my judgment,
that there was very great oppression and vexation under the government
of the late king and the bishops who were under his power,
which the Lord was offended with, and many good people were oppressed thereby.
And for this cause, the Lord could and did justly raise up some to oppose,
and to strive against oppressions and injustice,
and to press after reformation in all things.
And that seed of sincerity,
which in some things carried them on in opposing oppressions and pressing after reformation,
I can never deny, but must acknowledge it; though many soon lost it,
and became self-seekers, forgetting the cause they claimed to uphold.

This is but a small part of the queries, and the answers thereunto,
which E. Burrough concluded with a bold exhortation
to the king to fear and reverence the Lord.

Now we return again to G. Fox the elder, whom we left about Bristol;
from which he passed to Gloucester, Worcester, Drayton (the place of his nativity),
and Yorkshire.
In that country at that time a Yearly meeting was kept at Balby, in an orchard,
where some thousands of people had met together.
At York, about thirty miles off, notice being given of this meeting,
a troop of horsemen came from there.
G+++.+++ Fox stood preaching in the meeting on a stool, when two trumpeters came riding up,
sounding their trumpets pretty near to him.
Then the captain bid George to come down, for he had come, he said,
to disperse the meeting.
But G. Fox told the captain, that he knew these were a peaceable people;
and if he did question whether they met in a hostile manner,
he might make a search among them,
and if he found either sword or pistol about anyone there, such may suffer the penalty.
But the captain told G. Fox that he must see them dispersed,
for he had ridden all night on purpose to disperse them.
G+++.+++ Fox asked him,
"`What honor is it for you to ride with swords and
pistols among so many unarmed men and women?
But if you will be still and quiet,
the meeting will probably not continue above two or three hours; and when it is done,
as they came peaceably together, so they shall part.
For you may perceive,
that the meeting is so large that all the country thereabouts cannot lodge them,
but they intend to depart towards their homes this night.`"
But the captain he could not stay so long.
G+++.+++ Fox then requested that if he himself could not stay to see the meeting ended,
he would let a dozen of his soldiers stay.
To this the captain said he would permit them one hour`'s time;
and so he left six soldiers to stay there, and then went away with his troop.
And when he had gone,
the soldiers that were left told those that were
met together that they might stay till night,
if they desired.
This they would not do, but parted about three hours after, without any disturbance.
But if the soldiers had been of such a temper as their captain,
perhaps the meeting would not have ended thus quietly.
For this captain was a desperate man,
having once told G. Fox in Scotland that he would obey his superiors`' command,
even if it were to crucify Christ;
and that he would even execute the great Turk`'s commands against the Christians,
were he under his command.

Now G. Fox went to Skipton,
where there was a general meeting concerning the affairs of the church.
For many of his friends suffered much at this time, their goods being taken from them,
and some were brought to poverty, so there was a necessity to provide for them.
This meeting had stood several years;
for when the justices and captains had come to break them up,
and saw the books and accounts of collections for relief of the poor,
and how care was taken that one county should help another and provide for the poor,
they commended such practice, and passed away in love.
Sometimes there would come two hundred poor people belonging to other societies,
and wait there till the meeting had finished;
and then the Friends would send to the bakers for bread,
and give every one of these poor people a loaf, regardless how many there were;
for they were taught to do good unto all, though especially to the household of faith.

From here G. Fox went to Lancaster, and so to Swarthmore,
where he was apprehended at the house of Margaret Fell (who was now a widow,
judge Thomas Fell, her husband,
having deceased about two years before.) Now some imagined
that they had accomplished a remarkable feat;
for one said, he did not think a thousand men could have taken G. Fox.
They led him away to Ulverstone, where he was kept all night at the constable`'s house,
and a guard of fifteen or sixteen men were set to watch him;
some of whom sat in the fireplace, for fear he should go up the chimney.
The next morning he was carried to Lancaster, but was exceedingly abused along the way;
and having come to the town,
he was brought to the house of a justice whose name was Henry Porter,
and who had granted the warrant against him.
He asked Porter, for what, and by whose order, he had sent forth his warrant,
and he complained to him of the abuse he had received
from the constables and other officers;
for they had set him upon a horse behind the saddle, so that he had nothing to hold to,
and then by maliciously beating the horse,
made him kick and gallop and throw off his rider.
But Porter would not take any notice of that, and told G. Fox he had an order;
but would not let him see it, for he would not reveal the king`'s secrets.
After many words were exchanged, he was carried to Lancaster prison.

Being kept there a close prisoner in the common jail, he desired two of his friends,
one of which was Thomas Green, the other Thomas Cummings,
a minister of the gospel (with whom I was very familiarly acquainted),
to go to the jailer and request of him a copy of his court order.
They went, but the jailer told them he could not give a copy of it;
yet he gave it them to read, and to the best of their remembrance,
the matters therein charged against G. Fox stated that he was a person
generally suspected to be a common disturber of the peace of the nation,
an enemy to the king, and a chief upholder of the Quakers`' sect; and that he,
together with others of his fanatic opinion,
had lately endeavored to raise insurrections in these parts of the country,
and to embroil the whole kingdom in blood.
For this reason, the jailer was commanded to keep him in safe custody,
till he should be released by order from the king and parliament.
It is no wonder that the jailer would not give over a copy of his court order,
for it contained almost as many untruths as words.
G+++.+++ Fox then wrote a defense,
wherein he gave answers at length to all these false accusations.
And Margaret Fell, considering what injury had been offered to her,
by hauling G. Fox out of her house, wrote the following information, and sent it abroad.

To all magistrates, concerning the wrong taking up,
and imprisoning of George Fox at Lancaster:

I do inform the governors of this nation, that Henry Porter, mayor of Lancaster,
sent a warrant with four constables to my house, for which he had no authority nor order.
They searched my house, and apprehended George Fox in it,
who was not guilty of the breach of any law, or of any offense against any in the nation.
After they had taken him, and brought him before the said Henry Porter,
bail was offered for what he would demand for his appearance,
to answer what could be laid to his charge: but he (contrary to law,
if he had taken him lawfully), denied to accept of any bail;
and clapped him up in close prison.
After he was in prison, a copy of his court order was demanded,
which ought not to be denied to any prisoner,
that so he may see what is laid to his charge: but it was denied him.
A copy he could not obtain; only his friends were permitted to read it over.
And everything that was there charged against him was utterly false;
he was not guilty of any one charge in it, as will be proved,
and manifested to the nation.
So, let the governors consider of it.
I am concerned in this thing, inasmuch as he was apprehended in my house;
and if he be guilty, so I am too.
So I desire to have this searched out.

Margaret Fell.

After this, Margaret determined to go to London,
to speak with the king about this matter; and Porter, hearing of this,
said he would go too, and so he did.
But because he had been a zealous man for the parliament against the king,
several of the attendants of the royal court put
him in mind of his plundering of their houses.
And this so troubled him, that he quickly left the court, and returned home,
and then spoke to the jailer about contriving a way to release G. Fox.
But in his court order Porter had overshot himself,
by ordering G. Fox to be kept prisoner till he should be delivered by the king or parliament.
G+++.+++ Fox also sent him a letter,
and put him in mind of how fierce he had been against the king and his party,
though now he desired to be thought zealous for the king.
And among other passages, he called to his remembrance how,
when he held Lancaster Castle for the parliament against the king,
he was so rough and fierce against those that favored the king,
that he said he would leave them neither dog nor cat,
if they did not bring in provision to his castle.

One Anne Curtis coming to see G. Fox, and understanding how he stood committed,
resolved also to go to the king about it; for her father,
who had been sheriff of Bristol,
was hanged near his own door for endeavoring to bring in the king.
Upon this consideration,
she was in hopes to be admitted to the king`'s presence to speak with him.
Coming to London, she and Margaret Fell went together to the king, who,
when he understood whose daughter Anne was, received her kindly.
Having acquainted the king with the case of G. Fox,
she desired that he would be pleased to send for him and hear the case himself.
This the king promised her he would do,
and commanded his secretary to send down an order for the bringing up G. Fox.
But it was long before this order was executed, for many evasions were sought,
through caviling at a word, and by other craft,
whereby the sending of G. Fox was delayed above two months.
Thus continuing prisoner, he wrote several papers, and among the rest was this:

To the King.

King Charles,

You came not into this nation by sword, nor by victory of war;
but by the power of the Lord; and now if you do not live in this power,
you will not prosper.
And if the Lord has showed you mercy, and forgiven you,
and you do not show mercy and forgive, the Lord God will not hear your prayers,
nor them that pray for you.
And if you do not stop persecution, and persecutors,
and take away all laws that do hold up persecution about religion,
and if you do persist in them, and uphold persecution,
it will make you as blind as those that have gone before you.
For persecution has always blinded those that have run into it; and such as these, God,
by His power, overthrows, and so brings salvation to His oppressed ones.
And if you do bear the sword in vain, and let drunkenness, oaths, plays, may-games,
with fiddlers, drums, and trumpets to play at them,
where such like abominations and vanities are encouraged
or go unpunished--such as setting up maypoles,
with the image of the crown atop of them,
etc.--the nation will quickly turn like Sodom and Gomorrah,
and be as bad as the old world, who grieved the Lord till He overthrew them.
So He will overthrow you, if these things are not suddenly prevented.
Never was there so much wickedness at liberty before now, as there is at this day;
as though there was no terror, nor sword of magistracy,
which does not adorn a government, nor is it for the praise of those who do well.
Our prayers are for those that are in authority,
that under them we may live a godly life, in which we have peace;
and that we may not be brought into ungodliness by them.
So hear, and consider, and do good in your time, while you have power.
Be merciful and forgive, that is the way to overcome, and obtain the kingdom of Christ.

G+++.+++ Fox

The sheriff of Lancaster still refused to remove G. Fox, unless he would become bound,
and pay for the sealing of the writing, and the charge of carrying him up to London.
But this he would not do.
Then, consulting how to convey him,
it was at first proposed to send a party of horsemen with him.
But he told them, if he were such a man as they had represented him to be,
they had need to send a whole troop or two of horsemen to guard him.
But considering that this would be a great charge to them,
they concluded to send him up guarded by only the jailer and some bailiffs.
Upon further consideration, they found that this also would be costly,
and thereupon told him,
if he would but put in bail that he would be in London on such a day,
he should have leave to go up with some of his own friends.
G+++.+++ Fox told them, he would neither put in any bail, nor give any money;
but if they would let him go up with one or two of his friends, he would go up,
and be in London on such a day, if the Lord did permit.
So at last, when they saw they could not make him bow,
the sheriff consented that he should go up with some of his friends,
without any other engagement than his word,
to appear before the judges at London upon such a day, if the Lord did permit.
Whereupon they let him go out of prison, and after some stay,
he went with Richard Hubberthorn and Robert Withers to London,
where he came on a day that some of the judges of king Charles
I were hanged and quartered at Charing Cross.
For at this time,
what Edward Burrough and others had plainly foretold was being fulfilled upon them.

The next morning G. Fox and those with him went to judge Thomas Mallet`'s chamber,
who then was putting on his red gown in order to
pronounce sentence against more of the king`'s judges,
and therefore he told him he might come another time.
G+++.+++ Fox did so, being accompanied by Marsh Esq., one of the king`'s bed-chamber.
When he came to the judge`'s chamber, he found there also the lord chief justice Foster,
and delivered to them the charge that was against him.
But when they read those words that "`he and his friends were embroiling
the nation in blood,`" etc. they struck their hands on the table.
G+++.+++ Fox then told them that he was the man whom that charge was against,
but that he was as innocent of any such thing as a newborn child,
and that he had brought the charge to them himself,
and that some of his friends came with him, without any guard.
Prior to this, the judges had not minded G. Fox`'s hat, but now seeing his hat on,
they asked him why did he stand with his hat on?
He told them, he did not do so in any contempt to them.
Then they commanded one to take it off;
and having called for the marshal of the King`'s Bench, they said to him,
"`You must take this man and secure him, but you must let him have a chamber,
and not put him among the prisoners.`"
But the marshal said his house was so full,
that he could not tell where to provide a room for him, except among the prisoners.
Judge Foster then said to G. Fox,
"`Will you appear tomorrow about ten o`'clock at the King`'s Bench Bar,
in Westminster Hall?`"
"`Yes,`" said he, "`if the Lord give me strength.`"
Hereupon the said judge said to the other judge, "`If he say yes, and promises it,
you may take his word.`"

So he was dismissed for that time,
and the next day appeared at the King`'s Bench Bar at the hour appointed,
being accompanied by Richard Hubberthorn, Robert Withers, and esquire Marsh,
before-named.
And being brought into the middle of the court,
he looked about and turning to the people, said, "`Peace be among you.`"
Then the charge against him was read,
and coming to that part which said that he and his
friends were embroiling the nation in blood,
and raising a new war, and that he was an enemy to the king,
etc. those of the bench lifted up their hands.
Then, stretching out his arms, he said, "`I am the man whom that charge is against;
but I am as innocent as a child concerning the charge,
and have never learned any war postures.
Do you think, that if I and my friends had been such men as the charge declares,
that I would have brought it up to London against myself?
Or that I should have been allowed to come up with only one or two of my friends with me?
For had I been such a man as this charge sets forth,
I had need to have been guarded up with a troop or two of horsemen.
But the sheriff and magistrates of Lancashire had thought
fit to let me and my friends come up by ourselves,
almost two hundred miles, without any guard at all,
which we may be sure they would not have done if
they had looked upon me to be such a man.`"
Then the judge asked him, whether the charge should be filed, or what he would do with it?
And he answered, "`You are judges, and able, I hope, to judge in this matter;
therefore do with it what you will.`"
The judges then said, they would not accuse him, for they had nothing against him.
Whereupon esquire Marsh stood up and told the judges,
"`It is the king`'s pleasure that G. Fox be set at liberty,
seeing no accuser has come against him.`"
Then they asked him, whether he would bring the matter before the king and council?
He answered, "`Yes, very willingly.`"
Thereupon they sent to the king, who upon perusal of this,
and consideration of the whole matter, being satisfied of G. Fox`'s innocency,
commanded his secretary to send the following order to judge Mallet for his release:

It is his Majesty`'s pleasure that you give order for the releasing,
and setting at full liberty, the person of George Fox, late a prisoner in Lancaster jail,
and commanded here by an habeas corpus.
And this signification of his Majesty`'s pleasure shall be your sufficient warrant.
Dated at Whitehall, the 24th of October, 1660.

Edward Nicholas.

For Sir Thomas Mallet, knight, one of the justices of the King`'s Bench.

When this order was delivered to judge Mallet,
he immediately sent his warrant to the marshal of the King`'s Bench,
for G. Fox`'s release; which warrant was as follows:

By virtue of a warrant which this morning I have
received from the right honorable sir Edward Nicholas,
knight, one of his Majesty`'s principal secretaries,
for the releasing and setting at liberty of George Fox,
late a prisoner in Lancaster jail, and from there brought here by habeas corpus,
and yesterday committed unto your custody;
I do hereby require you accordingly to release and set the said prisoner, George Fox,
at liberty: for which this shall be your warrant and discharge.
Given under my hand the 25th day of October, in the year of our Lord God, 1660.

Thomas Mallet.

To Sir John Lenthal, knight, marshal of the King`'s Bench, or his deputy.

G+++.+++ Fox having been prisoner now above twenty weeks,
was thus very honorably set at liberty by the king`'s command.
After it was known that he was discharged,
several that were envious and wicked were troubled, and terror seized on justice Porter;
for he was afraid that G. Fox would take the advantage
of the law against him for his wrong imprisonment,
and thereby bring about his ruin.
And indeed G. Fox was encouraged by some in authority
to have made him and the rest examples.
But George said he would leave them to the Lord; if the Lord did forgive them,
he should not trouble himself with them.

About this time, Richard Hubberthorn got an opportunity to speak with the king,
and to have a long discourse with him, which soon after he published in print.
Being admitted into the king`'s presence,
he gave him a relation of the state of his friends, and said,
"`Since the Lord has called us, and gathered us to be a people, to walk in His fear,
and in His truth,
we have always suffered and been persecuted by the powers that have ruled,
and have been made a prey for departing from iniquity.
And when the breach of no just law could be charged against us,
then they made laws on purpose to ensnare us;
and so our sufferings were unjustly continued.`"

King: It is true, those who have ruled over you have been cruel,
and have professed much which they have not done.

R+++.+++ Hubberthorn:
And likewise the same sufferings do now abound in
more cruelty against us in many parts of this nation.
As for instance, one at Thetford in Norfolk, where Henry Fell,
while ministering unto the people, was taken out of the meeting and whipped,
and sent out of the town, from parish to parish, towards Lancashire.
The chief ground of his accusation, as is stated in his pass +++[+++which was shown to the king]
was, that he denied to take the oath of allegiance and supremacy;
and so because for conscience sake we cannot swear,
but have learned obedience to the doctrine of Christ, which says,
"`Swear not all;`" hereby an occasion is taken against us to persecute us.
And it is well known that we have not sworn for any, nor against any,
but have kept to the truth, and our yes has been yes, and our no, no, in all things,
which is more than the oath of those that are out of the truth.

King: But why can you not swear?
For an oath is a common thing among men to any engagement.

R+++.+++ Hubberthorn: Yes, it is manifest, and we have seen it by experience;
and it is so common among men to swear, and to engage either for or against things,
that there is no regard taken to them, nor fear of breaking an oath.
Therefore that which we speak of in the truth of our hearts,
is more than what they swear.

King: But can you not promise before the Lord, which is the substance of the oath?

R+++.+++ Hubberthorn: Yes, what we do affirm, we can promise before the Lord,
and take Him to be our witness in it; but our so promising has not been accepted,
but the ceremony of an oath has been insisted upon,
without which all other things were accounted of no effect.

King: But how may we know from your words that you will perform what you say?

R+++.+++ Hubberthorn: By proving us;
for they who swear are not known to be faithful except by proving them.
And so we, by those that have tried us,
are found to be truer in our promises than others by their oaths;
and to those that will yet prove us, we shall appear to be the same.

King: Pray, tell me, what is your principle?

R+++.+++ Hubberthorn: Our principle is this, "`That Jesus Christ is the true light,
which enlightens everyone that comes into the world,
that all men through Him might believe;`" and that all are
to obey and follow this light as they have received it,
whereby they may be led unto God, unto righteousness and the knowledge of the truth,
that they might be saved.

King: This all Christians do confess to be truth;
and he is not a Christian that will deny it.

R+++.+++ Hubberthorn: But many have denied it, both in words and writings,
and have opposed us in it;
and above a hundred books are put forth in opposition to this principle.

Then some of the lords standing by the king said
that none would deny that everyone is enlightened.
And one of the lords asked, how long we had been called Quakers,
or did we approve that name?

R+++.+++ Hubberthorn: That name was given to us in scorn and derision, about twelve years ago;
but there were some that lived in this truth before we had that name given to us.

King: How long is it since you acknowledged this judgment and way?

R+++.+++ Hubberthorn: It is near twelve years since I owned this truth,
according to the manifestation of it.

King: Do you acknowledge the sacrament?

R+++.+++ Hubberthorn: As for the word sacrament, I do not read of it in the Scripture;
but as for the body and blood of Christ I acknowledge it,
and that there is no remission without blood.

King: Well, that is it; but do you not believe that everyone is commanded to receive it?

R+++.+++ Hubberthorn: This we do believe, that according as it is written in the Scripture,
that Christ at His last supper took bread and broke it, and gave to His disciples,
and also took the cup and blessed it, and said unto them,
"`And as often as you do this (that is, as often as they broke bread),
you show forth the Lord`'s death till He come;`" and this we believe they did;
"`and they did eat their bread in singleness of heart from house to house;`"
and Christ did come again to them according to His promise,
after which they said, "`We being many, are one bread,
for we are all partakers of this one bread.`"^
footnote:[1 Corinthians 10:17]

King`'s friend: Then one of the king`'s friends said, It is true;
for as many grains make one bread, so they being many members, were one body.

And another of them said, "`If they be the bread, then they must be broken.`"

R+++.+++ Hubberthorn:
There is a difference between that bread which He broke at His last supper,
wherein they were to show forth, as in a sign, His death until He came;
and this whereof it is said, "`they being many,
are one bread;`" for here they had come more into the substance,
and to speak more mystically, as they came to know it in the Spirit.

Then the king`'s friends said: "`It is true, he has spoken nothing but truth.`"

King: How do you know that you are inspired by the Lord?

R+++.+++ Hubberthorn: According as we read in the Scriptures,
that "`the inspiration of the Almighty gives understanding;`" so by His
inspiration an understanding is given us of the things of God.

Then one of the lords said: "`How do you know that you are led by the true Spirit?`"

R+++.+++ Hubberthorn: This we know, because the Spirit of Truth reproves the world of sin,
and by it we were reproved of sin, and also are led away from sin,
unto righteousness and the obedience of truth,
by which effects we know it is the true Spirit;
for the spirit of the wicked one does not lead into such things.

Then the king and his lords said it was truth.

King: Well, of this you may be assured,
that none of you shall suffer for your opinions or religion,
so long as you live peaceably, and you have the word of a king for it.
And I have also given forth a declaration to the same purpose,
that none shall wrong you or abuse you.

King: How do you acknowledge magistrates, or magistracy?

R+++.+++ Hubberthorn: Thus we do acknowledge magistrates: whoever is set up by God,
whether king as supreme, or any set in authority by him,
who are for the punishment of evil-doers, and the praise of them that do well,
such we shall submit unto, and assist in righteous and civil things,
both by body and estate.
And if any magistrates do that which is unrighteous, we must declare against it;
but we will submit under it by a patient suffering,
and not rebel against any by insurrections, plots, and contrivances.

King: That is enough.

Then one of the lords asked, "`Why do you meet together,
seeing every one of you have the church in yourselves?`"

R+++.+++ Hubberthorn: According as it is written in the Scriptures, the church is in God, Thes.
1:1 And they that feared the Lord, did meet often together in the fear of the Lord;
and to us it is profitable,
and herein we are edified and strengthened in the life of Truth.

King: How did you first come to believe the Scriptures were truth?

R+++.+++ Hubberthorn: I have believed the Scriptures from a child to be a declaration of truth,
when I had only a literal knowledge, natural education, and tradition.
But now I know the Scriptures to be true by the manifestation and
operation of the Spirit of God fulfilling them in me.

King: In what manner do you meet, and what is the order in your meetings?

R+++.+++ Hubberthorn: We do meet in the same order as the people of God did, waiting upon Him;
and if any have a word of exhortation from the Lord, he may speak it;
or if any have a word of reproof or admonition, and as every one has received the gift,
so they may minister one unto another, and may be edified one by another;
whereby a growth into the knowledge of the Truth is administered to one another.

One of the lords: Then you do not yet know as much as you may know,
but there is a growth to be experienced?

R+++.+++ Hubberthorn: Yes, we do grow daily into the knowledge of the Truth,
in our exercise and obedience to it.

King: Have any of your friends gone to Rome?

R+++.+++ Hubberthorn: Yes, there is one in prison in Rome.

King: Why did you send him there?

R+++.+++ Hubberthorn: We did not send him there,
but he found something upon his spirit from the Lord,
whereby he was called to go to declare against superstition and idolatry,
which is contrary to the will of God.

The king`'s friend: There were two of them at Rome, but one is dead.

King: Have any of your friends been with the great Turk?

R+++.+++ Hubberthorn: Some of our friends have been in that country.

Other things were spoken concerning the liberty of the servants of the Lord,
who were called by Him into His service,
that to them there was no limitation to parishes or places,
except as the Lord did guide them in His work and service by His Spirit.

The king having promised Richard Hubberthorn over and again,
that his friends should not suffer for their opinion or religion, they parted in love.
But though the king seemed a good-natured prince, yet he was so misled,
that in the process of time he seemed to have forgotten
what he so solemnly promised on the word of a king.

Now, because in this discourse mention was made of Rome I will
say in passing that one John Perrot and John Love,
having gone to Leghorn in Italy, and having been examined there by the inquisition,
answered so well that they were dismissed.
And having come afterwards to Venice, Perrot was admitted to see the duke in his palace,
where he spoke with him and gave him some books;
and from there he went with his fellow traveller to Rome.
Here they bore testimony in such a public manner
against the idolatry that is committed there,
that they were taken into custody.
John Love died in the prison of the inquisition;
and though it was said that he fasted to death,
yet some nuns have said that he was executed in the night,
for fear he should annoy the church of Rome.
However it was, he died in sincerity of heart, and so was more happy than John Perrot,
who though at that time was perhaps in a pretty good frame of mind,
yet afterwards he turned an eminent apostate,
having continued prisoner at Rome a great while, and at length got his liberty.
He was a man of great natural abilities, but, not continuing in true humility,
he ran out into exorbitant imaginations, of which more will be said hereafter.

About this time Samuel Fisher and John Stubbs were also at Rome,
where they spoke with some of the cardinals,
and testified against the popish superstitions.
They also spread some books among the friars,
some of whom confessed the contents thereof to be truth; "`but,`" said they,
"`if we should acknowledge this publicly, we might expect to be burnt for it.`"
Nevertheless, Fisher and Stubbs went free, and returned home unmolested.

The case of Mary Fisher, a maiden,
and one of the first Quakers (so called) that came into New England,
I cannot pass by in silence.
She having come to Smyrna, to go from there to Adrianople,
was stopped by the English consul and sent back to Venice,
from where she came by another way to Adrianople,
at the time that Sultan Mahomet the fourth was encamped with his army near the said town.
She went alone to the camp, and got somebody to go to the tent of the grand vizier,^
footnote:[A high-ranking political advisor or ministry.]
to tell him that an English woman had come who had
something to declare from the great God to the Sultan.
The vizier sent word that the next morning he should
procure her an opportunity for that purpose.
She then returned to the town, and came again the next morning to the camp,
where she was brought before the sultan,
who had his great men about him in such a manner as he was accustomed to admit ambassadors.
He asked by his interpreters (of which there were three
with him) whether it was true what had been told him,
that she had something to say to him from the Lord God?
She answered, "`Yes.`"
Then he bade her speak on: and as she was not quick to speak,
but rather weightily pondered what she would say,
he supposed that she might be fearful to utter her mind before them all,
and so asked her whether she desired that any of them might go aside before she spoke?
She answered, "`No.`" He then bade her speak the word of the Lord to them,
and not to fear, for they had good hearts, and could hear it.
He also charged her to speak the word she had to say from the Lord,
and neither say more nor less, for they were willing to hear it, be it what it was.
Then she spoke what was upon her mind.

The Turks hearkened to her with much attention and gravity until she had finished;
and then the sultan asked her whether she had anything more to say?
She asked him whether he understood what she had said?
And he answered, "`Yes, every word,`" and further said,
that what she had spoken was truth.
Then he desired her to stay in that country, saying,
that they could not help but respect such a one as would take so much pains to
come to them as far as from England with a message from the Lord God.
He also offered her a guard to bring her into Constantinople, where she intended to go.
But she not accepting this offer, he told her it was dangerous traveling,
especially for such a one as she;
and marveled that she had passed safely as far as she had: saying also,
it was in respect to her, and kindness that he offered it,
and that he would not for anything see her come to the least hurt in his dominions.

She having no more to say, the Turks asked her what she thought of their prophet Mahomet?
She answered warily that she knew him not; but Christ, the true prophet, the Son of God,
who was the light of the world and enlightened every man coming into the world,
Him she knew.
And concerning Mahomet she said, that they might judge of him to be true or false,
according to the words and prophecies he spoke; saying further,
"`If the word that a prophet speaks come to pass,
then you shall know that the Lord has sent that prophet; but if it come not to pass,
then shall you know that the Lord never sent him.`"
The Turks confessed this to be true; and Mary having performed her message,
departed from the camp to Constantinople, without a guard,
where she arrived without the least hurt or scoff.
And so she returned safe to England.

Concerning Catharine Evans, and Sarah Cheevers, two women,
who at this time lay in the prison of the inquisition at Malta,
and were not released till after three years confinement,
where they suffered most grievous hardships; I intend to speak hereafter,
when I come to the time of their deliverance;
and then I propose to make a large and very remarkable description concerning it.

In the meantime I return to the affairs of England,
where the government was now quite altered.
Many of the late king`'s judges were now hanged and quartered;
among these was also colonel Francis Hacker, of whom, about six years before this time,
it has been said that he took George Fox prisoner.
But he now himself was in prison,
and was impeached not only as one of those that kept the king prisoner,
but also that he signed the warrant for the king`'s execution,
and had conducted him to the scaffold.
To all of these charges and more he said little,
except that what he did was by order of his superiors,
and that he had endeavored to serve his country.
But this did not avail him, for he was condemned for high treason,
and hanged and quartered in October.
A day or two before his death Margaret Fell visited him in prison;
and when he was put in mind of what formerly he had
done against "`the innocent,`" he remembered it,
and said he knew well whom she meant, and had trouble upon him for it.
For G. Fox (who had compared him to Pilate) had bade him,
when the day of his misery and trial should come upon him,
to remember what he said to him.
And as Hacker`'s son-in-law, Needham, did not hesitate then to say,
that it was "`time to have G. Fox cut off,`" so it came to be the lot
of Hacker himself to be cut off at Tyburn where he was hanged.

Such now was the end of many, who were not only guilty of the king`'s death,
and the putting to death of others who were supporters of king Charles the Second,
but who had also transgressed against God by persecuting godly people.
These had been often warned,
and several times told that God would hear the cries of the widows
and fatherless who had been cruelly oppressed by them.
And just as they had made spoil of the goods of those whom in scorn they called Quakers,
so now fear and quaking was brought upon them,
and their estates became a spoil to others.
How plainly Edward Burrough had foretold this has been shown before;
and not to mention others, I will only say,
that one Robert Huntington came once into the steeple-house at Brough, near Carlisle,
with a white sheet about him, and a halter about his neck,
to show the Presbyterians and Independents there that the surplice^
footnote:[The white liturgical vestment used by the Church of England.]
was to be introduced again, and that some of them should not escape the halter.
Now however mad this act was said to be then,
yet time proved it a prediction of the impending disaster of the cruel persecutors;
for when king Charles had ascended the throne,
his most fierce enemies were dispatched out of the way.

The parliament sitting at this time,
some of those called Quakers were admitted to appear in the House of Lords,
where they gave reasons why they could not attend the public worship, nor swear,
nor pay tithes; and they were heard with moderation.
The king also about this time showed himself moderate; for, being solicited by some,
and more especially by Margaret Fell,
he set at liberty about seven hundred of the people called Quakers who
had been imprisoned under the government of Oliver and Richard Cromwell.
This pardon passed the easier,
because those who were now at the helm had also suffered under the former government;
and for a short time there seemed some inclination to grant liberty of conscience.
But just at this time,
something took place which put a stop to the giving of such a liberty;
though it had advanced so far that an order was drawn up
for permitting the Quakers the free exercise of their worship.
Only the signing and seal was lacking for the passing of this order,
when all on a sudden the Fifth Monarchy-men made an insurrection.
There was at that time a great number of this turbulent people in England; who,
perceiving that their exorbitant opinion was inconsistent
with the kingly government which had now taken power,
decided they could not sit still while the government, which was yet but new,
should be fully settled and established.
Perhaps they had also some intent to free some of
the late king`'s judges who were still imprisoned;
for among these prisoners was also Sir Henry Vane,
who having been one of the chief of the commonwealth party,
was likewise said to be one of the heads of the Fifth Monarchy-men.

It was in the night when these people made their uprising; which caused such a stir,
that the king`'s soldiers sounded an alarm by the beating of drums.
The trained bands appeared in arms, and all was in an uproar,
and both the mob and soldiers committed great abuses for several days.
And though altogether innocent,
the Quakers became the object of the fury of their enemies,
and many were hauled to prison out of their peaceable meetings.

At that time George Fox was at London, lodging in Pall-mall.
At night a company of troopers came and knocked at the door where he was;
which being opened, they rushed into the house and laid hold of him.
One of these who had formerly served under the parliament,
pushed his hand to G. Fox`'s pocket, and asked whether he had any pistol?
G+++.+++ Fox said to him, "`You know I do not carry a pistol;
why do you ask such a question of me, knowing me to be a peaceable man?`"
Others of these men ran up into the chambers and there found esquire Marsh,
before-mentioned, in bed, who though he had access to the king`'s bed-chamber,
yet out of love to G. Fox, came and lodged where he did.
When the troopers came down again, they said, "`Why should we take this man away with us?
We will let him alone.`"
"`Oh no,`" said the parliament soldier, "`he is one of the heads,
and a chief ringleader.`"
Upon this the soldiers were taking him away.
But esquire Marsh hearing of it, sent for the man that commanded the party,
and desired him to let G. Fox alone, since he would see him shortly in the morning,
and then they might take him.

Early in the morning there came a company of footmen to the house;
and one of them drawing his sword, held it over G. Fox`'s head, which made him ask,
"`Why do you draw your sword at an unarmed man?`"
At this, one of his fellows, being ashamed, bid the soldier to put up his sword,
and sometime after this they brought George to Whitehall.
As he was going out, he saw several of his friends going to the meeting,
it being then the First day of the week.
He intended to have gone there himself, if he had not been stopped,
but as it was now out of his power to keep them company, he commended their boldness,
and encouraged them to persevere therein.
When he had come to Whitehall, seeing how the soldiers and people were exceedingly rude,
he began to exhort them to godliness.
But some influential persons coming by, who were envious of him, said, "`What?
Do you let him preach?
Put him into a place where he may not stir!`"
So he was put into such a place, and the soldiers watched over him;
but G. Fox told them that though they could confine his body, and shut that up,
yet the word of life they could not stop.
Some then asked him what he was?
He told them he was a preacher of righteousness.
After he had been kept there two or three hours, esquire Marsh spoke to the lord Gerard,
who came and bid them set G. Fox at liberty.
When he was discharged, the marshal demanded fees.
But G. Fox told him he could not give him any; and he asked him,
"`How can you demand fees of a man who is innocent?`"
Nevertheless he told him, that in his own freedom, he would give him two-pence,
with which he and the soldiers could buy drink.
But they exclaimed against such an idea, which made him say, "`If you will not accept it,
that is your choice.
But I cannot give you fees.`"
Then he passed through the guards, and came to an inn,
where several of his friends at that time were prisoners under a guard,
and about nightfall he went to the house of one of his friends.

This insurrection of the Fifth-Monarchy-men caused great disturbance in the nation;
and though the Quakers had nothing to do with those boisterous people,
yet they fell under great sufferings because of them.
Both men and women were dragged out of their houses to prison,
and some sick men were dragged off their beds by the legs;
among which was one Thomas Pachyn, who being in a fever,
was dragged by the soldiers out of his bed to prison, where he died.

This persecution going on throughout the nation,
Margaret Fell went to the king and gave him an account how her friends,
who were in no way involved in the said insurrection and riots, were treated;
for several thousands of them had been cast into prison.
The king and council wondered how they could have gotten such intelligence,
since strict charge had been given for the intercepting of all letters,
so that none could pass through London unsearched.
But notwithstanding this, so much was divulged about the numbers of the imprisoned,
that Margaret Fell went a second time to the king and council,
and acquainted them of the grievous sufferings of her friends.
G+++.+++ Fox then wrote a letter of consolation to his suffering friends;
and also published in print a declaration against all sedition, plotting, and fighting,
wherein he manifested that they were a harmless people who denied all wars and fightings,
and could not make use of the outward sword, or other carnal weapons.
This declaration was presented to the king and his council, and had such an effect,
that the king gave forth a proclamation that no soldiers
could go to search any house except with a constable.
And when afterwards some of the Fifth Monarchy-men
were put to death because of their insurrection,
they openly cleared the Quakers (so-called) of having had any hand in,
or knowledge of their plot.
This and other evidences caused the king, being continually importuned thereunto,
to issue forth a declaration that the Quakers should
be set at liberty without paying fees.

Many of the Presbyterian preachers now began to conform,
and in order to keep their benefices, joined with the Episcopalians,
and did not hesitate to put on the surplice.
But this gave occasion to many of their hearers to leave them,
and to join with the Quakers (so called) who would not comply with the times.
Others, who were a little more steadfast, made use of their money to get liberty,
though when still under the government of Cromwell
they would permit no liberty of conscience to others.
One Hewes, who was an eminent priest at Plymouth in Oliver Cromwell`'s days,
when some liberty of conscience was then granted,
prayed that God would put it into the hearts of the chief
magistrates of the nation to remove this cursed "`toleration.`"
But this same Hewes, after the king had come in,
being asked whether he would account toleration accursed now,
answered only by shaking his head.

Now though many of the Quakers, as has been said, were released from prison,
yet they suffered exceedingly in their religious assemblies.
Once a company of Irishmen came to Pall-Mall when G. Fox was there,
but the meeting had already broke up, and George had gone up into his chamber.
But hearing one of those rude persons, who was a colonel,
say he would "`kill all the Quakers,`" G. Fox came down and told him,
"`The law said an eye for an eye, and a tooth for a tooth;
but you threaten to kill all the Quakers, though they have done you no harm.`"
And he further said, "`Here is gospel for you: here is my hair, here is my cheek,
and here is my shoulder,`" turning it to him.
This so surprised the colonel, that he and his companions stood amazed, and said,
"`If this is your principle, according as you now say,
we have never seen the like in our lives.`"
To which G. Fox said, "`What I am in words, I am the same in life.`"
Then the colonel behaved lovingly;
though a certain ambassador who had stayed outside and then came in,
said that this Irish colonel was such a desperate man,
that he dared not come in with him, for fear he should have done great mischief.

Notwithstanding such like rude encounters,
yet some stop was put to the fierce current of persecution;
for the king being but newly settled on the throne, showed some inclination to leniency.
But this quiet did not last long, and proved but a short time of rest; for the churchmen,
who it seems were instigated by the abettors of popery, continued to be envious,
and waited for an opportunity to show their malice.
An instance of which has already been seen following the insurrection of the Fifth Monarchy-men,
and in what follows it will be seen much clearer.
For, though they did not appear at this time to persecute for conscience-sake,
yet in the name of justice,
laws were made use of in order to persecute dissenters that
had formerly been enacted for the suppression of popery,
and to protect the kingdom against Jesuits and other traitorous papists.

That it may be known what laws these were,
and that it may also appear what an unreasonable use has been made of them,
I shall here set them down, or abstracts from them;
that so it may be more plainly seen what awkward means have been made use of,
and how malevolently the laws were executed.
Sometimes I may interweave among these abstracts, some observations,
or an account of a case, which, though not placed in due time,
may yet be serviceable to give a true notion of things.
I now turn to these laws.

In the 27th year of king Henry the eighth, a law was made for payment of tithes;
for that king having either given or sold many chapels and abbeys to laymen,
those laymen had no right (as the priests claimed to have) to summon
to ecclesiastical courts those that failed to pay tithes.
Because of this, a law was provided,
by virtue of which a judge of an ecclesiastical court might be helpful to laymen,
and in that law it was said,

If the judge of an ecclesiastical court make complaint to
two justices of peace (quorum unus) of any noncompliance,
or any misdemeanor committed by a defendant in any suit there depending for tithes,
the said justices shall commit such defendant to prison,
there to remain till he shall find sufficient surety to be bound before them by recognizance,
or otherwise to give due obedience to the process, proceedings, decrees,
and sentences of the said court.

By this law, which is supposedly still in force,
many honest people have suffered and been kept very long in prison; for,
refusing to find surety for the payment of tithes--which for conscience-sake
they could not give to such ministers as lived from a forced maintenance,
and who did not, as they judged,
profit the people--it was in the power of the priests to
detain them prisoners until the pretended debt was paid.
This was judged to be so unreasonable by those who were persecuted,
that some have therefore continued in prison for many years,
choosing rather to die in jail than to maintain such preachers by paying tithes to them.

Now the Quakers (so called) have never offered resistance,
but suffering and forbearance have always been their weapons,
though they were almost continually harassed with laws that were never made against them.
And more especially were they molested with the oath of supremacy,
which was made in the beginning of the reign of queen Elizabeth, which runs thus:

I, +++_______+++, do utterly testify and declare in my conscience,
that the king`'s highness is the only supreme governor of this realm,
and of all other his highness`'s dominions and countries,
as well in all spiritual or ecclesiastical things or causes.
And that no foreign prince, prelate, state, or potentate, has,
or ought to have any jurisdiction, power, superiority, preeminence, or authority,
ecclesiastical or spiritual, within this realm.
And therefore I do utterly renounce, and forsake all foreign jurisdictions, powers,
superiorities, and authorities, and do promise that from henceforth I shall bear faith,
and true allegiance to the king`'s highness, his heirs and lawful successors;
and to my power, I shall assist and defend all jurisdiction, privileges, preeminences,
and authorities, granted, or belonging to the king`'s highness, his heirs and successors,
or united and annexed to the imperial crown of his realm.
So help me God, and the contents of this book.

In the first year of queen Elizabeth,
an act was made for uniformity of common-prayer and church-service, having this clause:

Every person shall resort to their parish church, or upon the impossibility thereof,
to some other, every Sunday and holiday,
upon pain of punishment by censures of the church, and also to forfeit twelve-pence,
to be levied by the church-wardens there, for the use of the poor,
distrained from the offender`'s goods.

Now, since the aforesaid law was not strictly obeyed, not only by papists,
but also by others who aimed at a further reformation and could
no longer comply with the rites of the Church of England,
therefore, in the 23rd year of Elizabeth, a more severe law was made, with this clause:

Every person not attending church, according to the statute of 1 Eliz.
2, shall forfeit twenty pounds for every month they so make default.
And if they so refuse for the space of twelve months,
after proof thereof is made unto the King`'s Bench,
a justice of the court in the county where they dwell shall bind them
with two sufficient sureties of 200 pounds at least to their good behavior,
from which they shall not be released until they
shall attend the church according to the said statute.

This law it seems was not thought severe enough;
therefore in the 29th year of the said queen, another law was made with this clause:

The queen may seize all the goods,
and two-thirds of the lands and leases of every offender not attending church as aforesaid,
for the sum then due for the forfeiture of twenty pounds a month, and yearly after that,
according to the rate of twenty pounds a month for so long a time as they
shall refuse to come to church according to the said statute of 23 Eliz.
1.

Upon these acts many were prosecuted.
But in the height of these proceedings, George Whitehead, Gilbert Latey and others,
solicited king Charles the Second on the behalf of their friends;
which had the effect that the king ordered a stop to it in various counties.
Nevertheless, afterwards the prosecution of this law was continued until after his death,
both with regard to imprisonment, as well as seizing of goods.
Other old laws were also made use of; for in the 35th year of queen Elizabeth`'s reign,
when the papists sometimes were forming plots against the queen,
an act was made containing this clause:

If any of above sixteen years of age shall be convicted
of having absented themselves above a month from church,
without any lawful cause, or opposed the queen`'s authority in causes ecclesiastical,
or frequented conventicles,^
footnote:[A secret assembly gathered for the purpose of plotting against the government.]
or persuaded others so to do, under pretense of exercise of religion,
they shall be committed to prison, and there remain until they shall conform,
and make such open submission as hereafter shall be prescribed.
And if within three months after such a conviction
they refuse to conform and submit themselves,
they shall depart the realm.
And if such an offender refuses to depart, or having gone away accordingly,
does then return without the queen`'s license, he shall be adjudged a felon,
and shall not enjoy the benefit of clergy.
But if before he is required to depart, he makes his submission,
the penalties aforesaid shall not be inflicted upon him.

Though it may be supposed that this act was made chiefly against papists,
yet some of the Quakers (so called) were prosecuted thereupon, and that for their lives.
For even if these had been willing to depart the realm, yet such,
who for conscience-sake could not swear at all,
could not bind themselves by an oath that they would do so.
And this being very well known, it once happened, that one William Alexander,
of Needham in Suffolk, being with several more indicted upon this act, was asked,
"`Guilty or not guilty?`"
He not being hasty to answer, the judge said,
"`Why don`'t you plead guilty or not guilty?`"
To which Alexander replied, "`What would you advise us to plead?`"
The judge (who was generally considered a severe man) said, "`Do you ask my advice?`"
"`Yes,`" said Alexander.
"`Then,`" returned the judge, "`you shall have it;
and I`'ll advise you to plead not guilty.`"
So the prisoners accordingly pleaded not guilty.
Then the judge said to the prosecutors,
"`Now you must prove that these men have neither been at their own parish church,
nor at any other church or chapel, else they are not within this act,
which is a wicked law.`"
Thus the judge carried on his discourse,
to the discharge of Alexander and his friends from that severe indictment;
for the prosecutors were not able to prove this with evidence, as the law required.
One William Bonnet, had also been long in prison at Edmondsbury in Suffolk on this act,
and one Richard Vickris near Bristol.
But now I return.

After the demise of queen Elizabeth, when James the First had ascended the throne,
the papists still continued their wicked designs,
of which the gunpowder plot may serve for an instance.^
footnote:[The Gunpowder Plot was a failed assassination attempt against King
James I by a group of provincial English Catholics led by Robert Catesby.
The plan was to blow up the House of Lords during
the State Opening of Parliament on 5 November 1605,
as the prelude to a popular revolt in the Midlands
during which James`'s nine-year-old daughter,
Elizabeth, was to be installed as the Catholic head of state.]
To suppress therefore these malicious people, and for the better discovering of them,
in the third year of that king`'s reign, an act was made,
in which was contained the following oath,
which was to be taken by papist noncomformists:

I +++_______+++, do truly and sincerely acknowledge, profess, testify,
and declare in my conscience before God and the world,
that our sovereign lord king James, is lawful and rightful king of this realm,
and of all other his majesty`'s dominions and countries; and that the Pope,
neither of himself, nor by any authority of the church, or see of Rome,
or by any other means, with any other, has any power or authority to depose the king,
or to dispose of any of his majesty`'s kingdoms or dominions,
or to authorize any foreign prince to invade, or annoy him, or his countries,
or to discharge any of his subjects from their allegiance and obedience to his majesty,
or to give license or leave to any of them to bear arms, raise tumults,
or to offer any violence or hurt to his majesty`'s royal person, state, or government,
or to any of his majesty`'s subjects, within his majesty`'s dominions.
Also I do swear from my heart, that notwithstanding any declaration,
or sentence of excommunication, or deprivation, made or granted,
or to be made or granted, by the Pope or his successors, or by any authority derived,
or pretended to be derived from him or his see, against the said king, his heirs,
or successors, or any absolution of the said subjects from their obedience,
I will bear faith and true allegiance to his majesty, his heirs and successors,
and will defend him and them to the uttermost of my power,
against all conspiracies and attempts whatsoever,
which shall be made against his or their persons, their crown and dignity,
by reason or color of any such sentence or declaration, or otherwise.
And I will endeavor to disclose, and make known unto his majesty,
his heirs and successors, all treasons, and traitorous conspiracies,
which I shall know or hear of to be against him, or any of them.
And I do further swear, that I do from my heart abhor, detest, and abjure,
as impious and heretical, this damnable doctrine and position,
that princes which are excommunicated, or deprived by the Pope, may be deposed,
or murdered by their subjects, or any others whatsoever.
And I do believe, and in my conscience am resolved, that neither the Pope,
nor any person whatsoever, has power to absolve me of this oath, or any part thereof,
which I acknowledge by good and full authority to be lawfully ministered unto me,
and do renounce all pardons and dispensations to the contrary.
And all these things I do plainly and sincerely acknowledge,
and swear according to the express words by me spoken,
and according to the plain and common sense and understanding of the same words,
without any equivocation, or mental evasion, or secret reservation whatsoever.
And I do make this recognition and acknowledgment, heartily, willingly, and truly,
upon the true faith of a Christian.
So help me God.

This oath, commonly called the oath of allegiance,
was afterwards called by the name of the test.
And though the introduction of it makes mention of the gunpowder-plot,
and signifies that this oath was contrived to discover papists;
yet many of the people called Quakers have suffered thereby for many years.
For though they did not refuse to declare their allegiance to the king,
yet because it was well known that they would not swear at all,
this oath was continually made use of as a snare to imprison them.
Now the punishment stated against these nonconformists, was a premunire;^
footnote:[Premunire was a legal judgment designed to disenfranchise
those who refused to formally swear allegiance to the king of England.
Those under a sentence of premunire were considered traitors to their country.
They lost all rights to property and possessions,
were removed from under the kings protection, and were often imprisoned for life.]
and how grievously many Quakers have been oppressed on this account is not easily conveyed,
yet I will give some instances in what follows.
Other severe laws for persecution have been made since,
as will be seen in their proper time.

At the close of this year,
Edward Burrough wrote a consolatory epistle to his
fellow-laborers in the ministry of the gospel,
which I cannot omit to insert here,
because it shows very evidently how valiant he was in the service of Truth,
which epistle is as follows:

Dearly and well-beloved brethren in the heavenly relation and blessed immortal birth,
of which we are born most dearly in our Father`'s love;
my salutation extends unto you all,
as one with you perfectly in sufferings and in rejoicings, in faith and patience,
and even in all things which you do and suffer for in the name of the Lord our God.
My soul greets you, and embraces you, and fervently wishes peace, love, unity,
and the increase of every good gift unto you all; for I am perfectly one with you.
If you receive of our Father`'s fullness, I am refreshed; and if you rejoice, I am glad;
and if you suffer and are in heaviness, I freely partake with you.
Whatever is yours, whether liberty or bonds, whether life or death, I partake of the same.
And whatever I enjoy, the same also is yours; for we are of one birth, of one seed,
of one line, even of the generation of Him who is without beginning of days,
or end of life, who is a high priest, made after the power of an endless life.
And as He was blessed of the Father, so are we, because we are of the same birth,
and are partakers of His nature, and He lives in us, and we in Him.

Well, my dear companions, I need not multiply words unto you,
as if you knew not these things; for what do I know that you do not?
Or, what can I say, but you know the same?
Yet bear with me, for my heart is very full, and my soul is ready to be poured forth,
that I may once more express a little of what is abounding in my heart; for love,
even perfect love, even that love wherewith we are beloved of the Father,
fills my heart at this time towards all of you, from the least to the greatest.
Indeed, I know nothing but love towards you all,
and I doubt not but in the same love you do receive this my salutation,
which is from the fountain of love, which at this time is opened in my heart.

Now, dearly beloved,
the present considerations of my heart are very many
concerning the great love of the Father,
which hitherto has been shown unto us.
We all know, how He called us by His grace,
and turned our hearts from the vanities and evil ways of this world,
and sanctified us by His word, and put His image upon us, and called us by His name,
and redeemed us unto Himself,
and gave us the testimony of His holy Spirit in our own hearts,
that we should be His people, and He should be our God.
He taught us, and instructed us, and fed us, and gave us peace and rest in Himself,
and freed us from the bondage of sin and corruption, and from His terror because of sin.
He removed our transgressions and blotted them out, and ceased to smite us any more,
but brought us into the land of rest, flowing with mercy, and peace, and knowledge,
and all good things.
This the Lord our God did do for us in the days of our infancy;
even when we were yet in our sins He called us forth, and cleansed us from them.
And when we were strangers to Him, He made Himself known unto us;
and when we were wholly ignorant, He gave us knowledge; and when we were not a people,
He raised us up and made us worthy to be called by His name.
And thus, after this manner, did the Father love us, and show His love unto us.
This you know, even as I do, and the consideration of it causes me thus to express it.

Again, when He had thus wrought for us, and showed His love unto us,
He was pleased to call us out into His work,
to the turning and converting of others unto the way of life.
He put His Spirit into us, and gave us gifts of knowledge and utterance,
and armed us with wisdom, and strength, and courage,
and every way fitted us for that work and service in which He has carried us on.
He, I say, fitted us for His work, and called us into it,
and carried us on joyfully in it, and all this has been of His free love,
and infinite power; and what we have been, and what we have done,
it has been only of the Lord, and not of ourselves, even of His love,
so that we may marvel.
For alas, what were we but children, and neither prophets, nor the sons of prophets?
And our education, was it fitting for these things, to perform such a calling?
And therefore it is the Lord, and only He, that has effected His own purpose through us,
and by us, as instruments poor of ourselves, but by Him very excellent.

But oh, He has mightily prospered us in His work,
and a glorious effect we have beheld of our labors, and travels, and testimony.
Yes, the Lord has been with us abundantly, and His arm has compassed us about,
and He has often given us great victory over the wise and prudent of this world.
He has made His own word often very powerful in our mouths,
to the wounding of the consciences of our enemies;
and the Lord has blessed our testimony, to the confounding of the wisdom of this world,
and to the gathering of many unto Himself.
And He has gone forth before us in His authority,
and has been with us always in His own work; and our testimonies, labors,
and travels have been very precious and pleasant unto the Lord, and all His people;
and the effect thereof causes my soul to rejoice, because the Lord has been with us,
and has prospered us into a great people who have received our witness,
and accepted thereof unto their salvation.
And it is unto the Lord alone, that the glory of all this appertains.

And for these eight years and upward,
the hand of the Lord has carried us through great labors and travels in His service,
and many dangers, and persecutions, and afflictions have attended us all this time.
And you know that many a time has the Lord delivered us
from the hands of such as would have destroyed us;
and we have been delivered again and again out of dangers and difficulties,
and the Lord has been a present help unto us in the time of our trouble.
For the plotting of the wicked, and the purposes of ungodly men,
have often been broken for our sakes,
even many a time have we been delivered out of the snare that has been laid for us,
and we have seen our enemies fall before us on the right hand and on the left,
even the wise in their worldly wisdom, and the foolish in their brutishness,
both professors and profane has our God often cut short
in their desires and endeavors for our destruction,
and we have been wonderfully preserved unto this day.
And all this I attribute to the infinite love and power of the Lord God,
who is blessed forevermore.

Through all these things we are yet alive, and the Lord has not failed us unto this hour,
but He lives and walks in us, and His testimony is with us,
even the seal of His good Spirit in our hearts that we are His sons and servants.
Yes, we are confirmed by many tokens that He is our God, and we are His people,
and the great oppressions which we have met with have not restrained us,
but through it all have we grown and prospered unto this day.
And concerning the things whereof we have testified these many years,
I am no way doubtful but that our God will fulfill them,
neither can my confidence be shaken by what is or can come to pass;
for antichrist must fall, and God will confound false ministry and worship,
false ways and doctrines, and the Lord will lay low false power and false churches,
and truth and righteousness must reign.
And God will gather His people more and more, and glorious days will appear.
God will exalt His kingdom upon earth, and throw down the kingdom of the man of sin.
All oppression must cease, and the oppressors shall be no more,
and God will free His people, and they shall be happy in this world and forever.
These things have we prophesied from day to day,
and my faith is constant and unmovable that God will effect these things in His season.
For the Lord has never yet deceived me, but what He has said will surely come to pass.

And therefore, brethren, let us be in hope and patience,
and live in the word of patience, and not be fainthearted,
as though the Lord had forgotten us or was unmindful of us,
or as though He will not perform what He has testified of by us.
For He is not a man that He should lie, nor as a man that is given to change.
But lift up your heads, for the Lord is with us,
even in our greatest tribulations and afflictions, and He will accomplish His purpose;
for He is mighty to save His people, and to destroy His enemies.

It is true, the gates of hell at this time seem to be open against us,
and we are a people likely to be swallowed up by our enemies,
and floods of wickedness seem to overflow,
and the waves of the great sea seem to be void of mercy,
and the hope of our adversaries is to extinguish us from being a people,
and to destroy us from the face of the earth.
And the hands of our persecutors are highly exalted at this day,
as though all that we have done for the Lord, by our labors and travels,
should now be made of no effect.

Well, dear brethren, though it be thus, yet our God can deliver us,
and confound our adversaries; and we can appeal to our God,
and can spread our cause before Him.
For He knows that our sufferings and afflictions are altogether unjust, and unequal,
and unrighteous, and that our persecutors do afflict us out of their envy,
and without any just cause administered unto them by us.
God knows it, angels and saints know it,
that we are at this day a persecuted people for religion`'s sake;
and this our present affliction is not any just punishment,
either from the justice of God or from the justice of men.

For God has given us the witness of His eternal Spirit
that wrath is not in Him towards us.
Let His wrath be to His enemies, but unto us is joy and peace forevermore.
And if the Lord clears us, and He justifies us, who then shall condemn us?
He charges no guilt upon us, as if we were the cause, by our evil deeds,
of these our present sufferings,
or as if this had come to pass upon us as punishment from the hand of God.
I say, it is not so; these present sufferings are not out of God`'s anger towards us,
for His love is to us.
For unto all the world we can say (and God Himself shall plead our cause),
whom have we wronged or done evil to?
What evil have we done to any man`'s person?
Whose goods have we falsely taken or coveted?
Against whom have we designed mischief?
May the Lord Himself be judge between us and our persecutors in this matter;
for unto Him it is known that we do desire the good of all, and not the hurt of any,
and yet we are dealt with as evil-doers.
The God of heaven is witness in our consciences that we neither plot nor contrive,
nor agitate in thought or word the hurt of any man`'s person;
but we walk justly towards all,
it being our principle to do to others as we desire them to do unto us.
And we can plead our cause unto our God, and He shall plead our cause with our enemies,
and this is the present state of our case:
what we suffer at this time is singly in the cause of God, and for righteousness-sake,
and for the testimony of Jesus, which we hold.
Therefore let us freely commit our cause unto the God of heaven, and if we die,
it is for Him, and if we live, it is to Him;
and we seek not vengeance against our enemies,
but leave it to the Lord to plead with them.

And, dearly beloved,
I hope I need not exhort you to be patient and faithful in this day of our trial,
knowing that the cause is so excellent in which we are tried.
It is God`'s cause and not our own;
and I hope you all have the testimony of His Spirit in your consciences,
verifying the truth of the cause for which we suffer.
And having this evidence, we need not be doubtful towards God, nor ashamed before men,
so long as everyone feels the evidence of the Spirit of
God bearing witness that we suffer for righteousness-sake,
and for the name of Christ Jesus.

And so dear brethren, lift up your heads, and be assured that we are the Lord`'s,
and it is in His cause that we are tried,
and He will judge and avenge our persecutors in His season,
and we shall still be a people when the Egyptians lie dead upon the sea-shore.
When the raging sea is dried up, this same people shall be safe;
for has not the Lord done excellent things for us?
Has He not led us forth, and blessed us unto this day?
Has He not preserved us hitherto through many tribulations and dangers?
Has He not showed infinite love and favor unto us to this hour?
And will He now allow us to be destroyed from being a people?
Surely no.
Will He give our enemies their heart`'s desire to cut us all off,
that they may blaspheme His name?
Surely no.
And if it be the pleasure of the Lord that some of
us should seal our testimony with our blood,
good is the will of the Lord; not ours, but His will be done.
For the testimony that we have borne for these many
years has been so excellent in its fruits and effects,
that the finishing of it deserves the best seal that we can possibly sign it with,
which is indeed our heart`'s blood.
And yet, though it should be thus, my confidence is sure,
that the work of the Lord shall prosper, and our testimony shall be glorious forever,
and this people shall never be extinguished from being a people.

And I know not anything that remains on our part at this day,
but that we commit ourselves into the hand of the Lord, living in the Seed of God,
wherein our election is sure.
And let us remember one another, and pray for one another;
and let us stir up all the children of our Father to faithfulness and patience,
while we have time.
I say, let us walk to the glory of the Lord,
keeping faith and a good conscience to our very end.
For our testimony shall never die,
nor our memories ever perish when we have ceased to be;
and though we suffer now the loss of life, and all we have,
yet the effects thereof will be glorious in ages to come,
and our present sufferings will hasten the glory of God`'s work throughout the world.
Receive this as my salutation to you all.

It is now eight days since I left Ireland,
where my service has been for the Lord for a full six months,
all which time the Lord carried me in much faithfulness and diligence in His service,
to the confirming of many in the truth of God, and to the converting of others.
And because of the presence of the Lord which was with me, I had a very precious time,
and was wonderfully preserved through many dangers and trials.
I travelled near two thousand miles to and fro in that land,
and had very free passage in the principal cities and towns,
till my work for the present had fully ended there,
having more time than could be expected to clear my conscience to all people.
It would be too large to mention every particular transaction
wherein I perceived the eminent hand of God with me;
and also many things I observed concerning the present
state of things which I shall not mention;
for what have we to do with the affairs of worldly kingdoms?
But as for Friends, it was well with them there.
They grow and increase in the blessings and fullness of the Father;
and when I came from there all was quiet, and very few were in prison, though,
I suppose that the tidings of things as they are
here will produce the same sufferings upon them.
But I hope they will be bold and valiant for the truth,
in giving their testimony by faithful sufferings, until these things be finished.

Thus I remain in life and death, and when I am no more, in everlasting remembrance,
your dear brother and companion,
by doing and suffering for the name of the Lord and His truth.
I am well, and at liberty, as yet.

E+++.+++ B.

Eleventh of the Twelfth month, 1660.
