== Chapter XI

[.section-date]
1661--1662

The year 1661 having begun, the government was altogether changed,
Charles the Second was now seated on the throne of England in peace,
and the power of persecution seemed somewhat restrained,
so that there was an appearance of some quiet and calm.
Therefore I will now take a turn to New England,
to draw back the curtains of the bloody stage at Boston.
We have already seen in the foregoing relation, how William Robinson,
Marmaduke Stevenson, and Mary Dyer, were put to death by their persecutors,
but their blood-thirstiness was not yet quenched.

William Leddra, who was banished from Boston on pain of death,
felt himself under such necessity of conscience,
that he could not forbear returning there;
where he came about the conclusion of the foregoing year.
He was soon taken prisoner, and being fastened to a large wooden log,
was kept night and day locked in chains in an open prison, during a very cold winter,
where we will leave him for the present.
In the meantime,
I will insert here a written "`vindication`" of the
Boston persecutors concerning their cruel carriage,
which may serve to confirm the truth of what has
been already related of their wicked dealings.
For it seems,
that fearing their bloody deeds would be disapproved by the court of England,
they thought it safest to paint their transactions with a delusive pretense;
though this had no other effect than to thereby more
expose their own shame to public view;
and in process of time they also incurred the king`'s displeasure.
For though Charles the Second was inclined to voluptuousness, yet he was good-natured,
and the persecution in his reign proceeded chiefly
from the instigation of other malicious men.
But to come to the vindication or declaration of the bloody persecutors,
it was as follows:

[.embedded-content-document.address]
--

Although the justice of our proceedings against William Robinson, Marmaduke Stevenson,
and Mary Dyer, supported by the authority of this court, the laws of this country,
and the law of God,
may rather persuade us to expect encouragement and
commendation from all prudent and pious men,
rather than convince us of any necessity to vindicate the same;
yet for as much as men of weaker understanding,
out of pity and commiseration (which is a commendable and Christian virtue,
yet easily abused,
and susceptible of sinister and dangerous impressions
for lack of a full information) may be less satisfied;
and because men of perverse principles may be led
to slander us and render us as bloody persecutors;
therefore to satisfy the one, and stop the mouths of the other,
we thought it requisite to declare what follows.
About three years ago,
several persons professing themselves Quakers (of whose pernicious opinions and
practices we had received intelligence from good hands in Barbados and England),
arrived at Boston,
whose persons where only then secured to be sent away at the first opportunity,
without censure or punishment, although their professed tenets,
and turbulent and contemptuous behavior to authority,
would have justified a more severe condemnation.
Yet the prudence of this court was exercised,
only in making provision to secure the peace and
order here established against their attempts,
whose design (we were well assured by our own experience,
as well as by the example of their predecessors in
Munster) was to undermine and ruin the same.

Accordingly a law was made and published,
prohibiting all masters of ships from bringing any Quakers into this jurisdiction,
and themselves from coming in on penalty of being confined
in the house of correction till they should be sent away.
Notwithstanding this, by a back door they found entrance,
and the penalty inflicted upon them proving insufficient
to restrain their impudent and insolent obtrusions,
it was increased by the loss of the ears of those who offended the second time.
This also being too weak a defense against their impetuous frantic fury,
it necessitated us to seek our own security; and upon serious consideration,
after the former experience of their incessant assaults,
a law was made that such persons should be banished upon pain of death,
according to the example of England in their provision against Jesuits.
This sentence being regularly pronounced at the last
court of assistants against the parties above named,
and they either returning,
or presumptuously remaining in this jurisdiction after the time limited,
were apprehended, and having acknowledged themselves to be the persons banished,
were sentenced by the court to death according to the law aforesaid,
which has been executed upon two of them.
Mary Dyer, (upon petition of her son,
and the mercy and clemency of this court) had liberty to depart within two days,
which she has accepted.
The consideration of our gradual proceedings will
vindicate us from the clamorous accusations of severity,
and our own just and necessary defense requiring
us (other means having failed) to hold out the sword,
which these persons have violently and willfully rushed upon,
and thereby become _felons de se_ +++[+++i.e. those who have killed
themselves]. And that this might have been prevented,
and the sovereign law and safety of the people been preserved, our former proceedings,
as well as the sparing of Mary Dyer upon an inconsiderable intercession,
will manifestly evince, and it will be seen that we desired their lives absent,
rather than their deaths present.

[.signed-section-signature]
Edward Rawson, Secretary.

--

In this vindication, in which the Quakers (who always were a harmless people,
and never made resistance with outward arms) are compared
to the mutinous and riotous Anabaptists of Munster,
it is also said of them that they found entrance "`by a back door.`"
This reflects on some who unexpectedly came into New England by land,
since they could find no opportunity to come by sea, because the ship-masters,
fearing the severity of the Boston laws, were unwilling to carry any Quakers there.
This gave occasion to Thomas Thirstone (who having been already at Boston,
was sent away on board a ship) to think of other means;
for finding himself moved in spirit to go there again,
he and Josiah Coale (of whom mention has been made before,
and who may be further spoken of hereafter) went from England to Virginia,
from which they, with one Thomas Chapman,
travelled several hundreds of miles on foot through vast wildernesses and woods,
and so at length came into New England.
This made the persecutors there astonished, for they thought this to be impossible,
that wilderness having been considered impassable for any besides the Indians.
Their journey, however, was very hard;
for they had not only hunger and cold to encounter (it being winter time),
but they were also in danger of being devoured by wild beasts,
and of perishing in unknown marshes or bogs.
But they were preserved by an Almighty hand;
though this marvelous passage was represented as a criminal
contempt by these New England persecutors.

It seems to me that the aforesaid vindication, which was published in print,
and likewise answered, was given forth before Mary Dyer was put to death.
But after her death,
the general court of Boston sent over an address to king Charles the Second,
signed by their governor John Endicot, to justify their cruel proceedings.
In this address they said that they had chosen rather the pure Scripture worship,
with a good conscience, in that remote wilderness among the heathen,
than the pleasures of England with subjection to
the imposition of the then prevailing hierarchy,
which they could not enjoy without doing offense to their conscience.
And concerning the Quakers, they said that they were open capital blasphemers,
and seducers from the glorious Trinity, the Lord Christ, and the blessed gospel;
that they were open enemies to government itself,
and malignant promoters of doctrines directly tending to subvert both church and state.
Moreover they said, that at last they had been constrained for their own safety,
to pass a sentence of banishment against them on pain of death,
since the magistrate in conscience judged himself appointed for the defense of all,
to keep the peace with
the point of the sword held towards them;
and that this could do no harm to those who would be warned thereby.
But the Quakers rushing themselves thereupon was their own act,
and a crime that brought their blood upon their own heads.

Could they have made the king believe this, they would willingly have done it;
but he had too much sense to be thus imposed upon,
though they did whatever they could to prevent his hearing the other party,
saying to him, "`Let not the king hear men`'s words; your servants are true men,
fearers of God and the king, and not given to change.
We are zealous of government and order; not seditious to the interest of Caesar.`"

However smooth and plausible this seemed, yet it could not stand the test;
and Edward Burrough, who answered it in print, addressed the king thus:

[.embedded-content-document.letter]
--

O king, my occasion to present you with these considerations is very urgent,
and of great necessity, even on the behalf of innocent blood,
hoping that my work will find such favor with you,
as to induce you to the reading and serious consideration thereof.

--

E+++.+++ Burrough then examining all their pretended reasons,
represented also to the king how some of these petitioners some time before
this had not hesitated to write in a letter from Boston to one Gordon:
"`There is more danger in these Quakers, to trouble and overcome England,
than in the king of Scots,^
footnote:[i.e. speaking of Charles Stuart II.,
when he had been declared king of Scotland, but had not been crowned in England.]
and all the popish princes in Germany;`" which plainly denoted,
that they reputed the king a troubler of England,
whom they numbered with the popish princes of Germany.
What E. Burrough obtained of the king for his friends, we will see hereafter.

But first I return to William Leddra, whom I left in prison.
It was on the 9th of the First month of this year,
that he was brought into the court of assistants with his chains and log at his heels.
Upon asking the jailer when he intended to take the irons off from his legs,
the jailer roughly answered, "`When you are going to be hanged.`"
W+++.+++ Leddra then being brought to the bar, it was told him by the rulers,
speaking of their law, that he was found guilty, and so he must die.
He said, "`What evil have I done?`"
The answer was, that his own confession was as good as a thousand witnesses.
He asked what his confession was?
To which they answered, that he had acknowledged those Quakers who had been put to death,
and that they were innocent.
Besides that, he would not put off his hat in court, and he said "`thee`" and "`thou.`"
Then William said to them, "`You will put me to death for speaking English,
and for not putting off my clothes?`"
To this major-general Denison returned, "`A man may speak treason in English.`"
And William replied, "`Is it treason to say '`thee`' and '`thou`' to a single person?`"
But none answered, only Simon Broadstreet, one of the court,
asked him whether he would go for England?
To which he answered, "`I have no business there.`"
Hereupon Broadstreet, pointing to the gallows, said, "`Then you shall go that way.`"
To which William returned, "`What,
will you put me to death for breathing the air in your jurisdiction?
For what you have against me I appeal to the laws of England for my trial;
and if by them I am found guilty, I refuse not to die.`"
Of this no notice was taken, but instead thereof,
they endeavored to persuade him to recant of his error (as they called it),
and to conform; to which with a grave magnanimity he answered,
"`What! and join with such murderers as you are?
Then every man that meets me will say, '`behold,
this is the man that has forsaken the God of his salvation.`'`"

While the trial of W. Leddra was going on, Wenlock Christison,
who was already banished upon pain of death, came into the court.
This dampened their spirits to a degree,
insomuch that for some space of time there was silence in the court;
but at length one of the bloody council cried out, "`Here is another one,
fetch him up to the bar!`"
Which the marshal performing, secretary Rawson said,
"`Is not your name Wenlock Christison?`"
"`Yes,`" said Wenlock.
"`Well,`" said the governor, John Endicot, "`what are you doing here?
Were you not banished upon pain of death?`"
To which Wenlock answered, "`Yes, I was.`"
And to the question, "`What are you doing here?`"
he answered, "`I have come here to warn you that you shed no more innocent blood;
for the blood that you have shed already cries to
the Lord God for vengeance to come upon you.`"
Whereupon it was said, "`Take him away, jailer.`"

W+++.+++ Leddra having been told that at the last general
court he had liberty given him to go for England,
or to go out of their jurisdiction; and that promising to do so,
and to come there no more, he might save his life; he answered,
"`I stand not in my own will, but in the will of the Lord.
If I may have my freedom, I shall go, but to make you such a promise, I cannot.`"
But this was so far from giving them contentment,
that they proceeded to pronounce sentence of death against him; which being done,
he was led from the court to the prison again,
where the day before his death he wrote the following letter to his friends:

[.embedded-content-document.letter]
--

[.salutation]
Most dear and inwardly beloved,

The sweet influences of the Morning Star,
like a flood distilling into my innocent habitation,
has so filled me with the joy of the Lord in the beauty of holiness,
that my spirit is as if it did not inhabit a tabernacle of clay,
but is wholly swallowed up in the bosom of eternity, from which it had its being.

Alas, alas, what can the wrath and spirit of man, that lusts to envy,
aggravated by the heat and strength of the king of the locusts,
which came out of the pit,
do unto one that is hidden in the secret places of the Almighty,
or unto those who are gathered under the healing wings of the Prince of Peace?--under
whose armor of light they shall be able to stand in the day of trial,
having on the breastplate of righteousness, and the sword of the spirit,
which is their weapon of war against spiritual wickedness, principalities, and powers,
and the rulers of the darkness of this world, both within and without.
Oh, my beloved!
I have waited as a dove at the windows of the ark, and have stood still in that watch,
until the Master (without whom I could do nothing) did reward
me with the fullness of His love at His coming,
wherein my heart did rejoice,
that I might in the love and life of God speak a few words to you,
sealed with the spirit of promise,
and that the taste thereof might be a savor of life to your life,
and a testimony in you of my innocent death.
And if I had been altogether silent, and the Lord had not opened my mouth unto you,
yet he would have opened your hearts,
and there have sealed my innocency with the streams of life,
by which we are all baptized into that body which is in God,
in whose presence there is life.
And as you abide in this life, you stand upon the pillar and ground of truth; for,
knowing that the life is the truth and the way, so go not one step without it,
lest you should only circle a mountain in the wilderness;
for unto everything there is a season.

As the flowing of the ocean tide does fill every creek and branch thereof,
and then retires again towards its own being and fullness, and leaves a savor behind it,
so does the life and virtue of God flow into every one of your hearts,
whom He has made partakers of His divine nature; and when it withdraws but a little,
it leaves a sweet savor behind it,
so that many can say they are "`made clean through the Word that He has spoken to them,`"^
footnote:[John 15:3]
in which innocent condition you may see what you are in the presence of God,
and what you are without Him.

Therefore, my dear hearts, let the enjoyment of the life alone be your hope,
your joy and consolation,
and let the man of God flee those things that would lead the mind out from the cross,
for then the savor of the life will be buried.
And although some may speak of their experiences which they received in the life,
yet if the life is veiled,
and the savor that is left behind is washed away by the fresh floods of temptation,
then the condition that they did formerly enjoy in the life, and boasted of,
will be like the manna that was gathered yesterday, without any good scent or savor.
For, it was only well with man while he remained in the life of innocency;
but being driven from the presence of the Lord into the earth, what can he boast of?
And although you know these things, and many of you know much more than I can say; yet,
for the love and zeal I bear to the truth and honor of God,
and the tender desire of my soul to those that are young,
that they may read me in that Spirit from which I write,
to strengthen them against the wiles of the subtle serpent that beguiled Eve, I say:
stand in the watch within, in the fear of the Lord, which is the very entrance of wisdom,
and the state where you are ready to receive the secrets of the Lord.
Hunger and thirst patiently; be not weary, neither doubt.
Stand still, and cease from your own working,
and in due time you shall enter into the rest, and your eyes shall behold His salvation,
whose testimonies are sure and righteous altogether.
Let them be as a seal upon your arm, and as jewels about your neck,
that others may see what the Lord has done for your souls.
Confess Him before men, yes, before His greatest enemies,
and fear not what they can do unto you; for greater is He that is in you,
than he that is in the world.
And He will clothe you with humility,
and in the power of His meekness you shall reign over all
the rage of your enemies in the favor of God.
And so long as you stand here, in faith, you are the salt of the earth; and many,
seeing your good works, may glorify God in the day of their visitation.
So take heed of receiving that which you did not see in the light,
lest you give ear to the enemy.
Bring all things to the light, that they may be proved, whether they be wrought in God.
The love of the world, the lust of the flesh, and the lust of the eye,
are outside the light, in the world.
Therefore possess your vessels in all sanctification and honor,
and let your eye look straight at the mark.
He that has called you is holy: and if there be an eye in you that offends, pluck it out,
and cast it from you.
And let not a temptation take hold, for if you do,
it will keep you from the favor of God, and that will be a sad state; for,
without grace possessed, there is no assurance of salvation.
By grace you are saved; and the witnessing of this grace is sufficient for you,
to which I commend you all my dear friends, and in it remain,

[.signed-section-closing]
Your brother,

[.signed-section-signature]
William Leddra

[.signed-section-context-close]
Boston Jail, the 13th of the First Month, 1661. +++[+++The day before he suffered.]

--

The next day after this letter was written, the execution of W. Leddra was performed,
which was on the 14th of the First month.
After the lecture had ended, the governor, John Endicot,
came with a guard of soldiers to the prison,
where W. Leddra`'s irons were taken off (according to what the jailer once said,
as has been related before),
with which he had been chained to a log both night and day during a cold winter.
William then having taken his leave of Wenlock Christison,
and others who were then in bonds, went forth to the slaughter,
encompassed with a guard to prevent his speaking to his friends.
Edward Wharton, an inhabitant of Salem, and also banished on pain of death, seeing this,
and speaking against it, one among the company said, "`O Edward,
it will be your turn next!`"
To which Captain Oliver added, "`If you speak a word, I`'ll stop your mouth.`"
Being then brought to the foot of the ladder, W. Leddra was bound,
and as he was about to ascend, he took leave of his friend E. Wharton, to whom he said,
"`All that will be Christ`'s disciples, must take up the cross.`"
Standing upon the ladder, somebody said, "`William,
have you anything to say to the people?`"
Thereupon he spoke thus: "`For the testimony of Jesus,
and for testifying against deceivers, and the deceived, I am brought here to suffer.`"
This took so much with the people, that it wrought a tenderness in many.
But to quench this, priest Allen said to the spectators, "`People,
I would not have you think it strange to see a man so willing to die;
for that is no new thing.
And you may read how the apostle said, that some should be given up to strong delusions,
and even dare to die for it.`"
But he did not say where the apostle spoke these words,
neither have I found it anywhere in holy writ;
though I know that Paul said in Romans 5:7. "`Peradventure
for a good man some would even dare to die.`"
But it seems it was sufficient for Allen if he could
but render Leddra odious to the crowd,
who nevertheless continued cheerful.
For as the executioner was putting the halter about his neck, he was heard to say,
"`I commit my righteous cause unto you, O God.`"
The executioner then being told to make haste, W. Leddra, at the turning of the ladder,
cried, "`Lord Jesus receive my spirit!`" and so he was turned off,
and finished his days.

The hangman cut down the dead body,
and lest it should be so barbarously treated as those
of William Robinson and Marmaduke Stevenson (which,
because none held them when they were cut down,
fell to the ground so violently that W. Robinson`'s skull was broken), Edward Wharton,
John Chamberlain, and others caught the body in their arms and laid it on the ground.
The hangman then stripped it of its clothes, and having done so,
said that he was a comely man, as indeed he was.
William`'s friends then took the body, laid it in a coffin, and buried it.
For further confirmation of what has here been related,
the following letter of one of the spectators, who was there accidentally, may be added:

[.embedded-content-document.letter]
--

[.letter-heading]
To Mr. George Lad, master of the "`America`" of Dartmouth, now at Barbados.

[.signed-section-context-open]
Boston, March 26, 1661.

On the 14th of this month, there was one William Leddra who was put to death.
The people of the town told me he might go away if he so desired;
but when I made further inquiry,
I heard the marshal say that he was chained in prison from
the time he was condemned to the day of his execution.
I am not of his religious opinion;
but yet truly I thought the Lord did mightily appear in the man.
I went to one of the magistrates of Cambridge who
had been one of the jury that had condemned him,
as he told me himself, and I asked him by what rule he did it?
He answered me that "`he was a rogue, a very rogue.`"
"`But`" said I, "`what is this to the question?
Where is your rule?`"
He said, he had abused authority.

Then I went after the William Leddra and asked him whether he did not
look on it as a breach of rule to slight and undervalue authority?
And I said that Paul gave Festus the title of honor, though he was a heathen.
(I do not say that these magistrates are heathens).
Then, when the man was on the ladder, he looked on me, and called me friend, and said,
"`Know that this day I am willing to offer up my life for the witness of Jesus.`"
Then I desired permission of the officers to speak, and said, "`Gentlemen,
I am a stranger both to your persons and country,
and yet a friend to both;`" and then I cried aloud, "`for the Lord`'s sake,
take not away the man`'s life; but remember Gamaliel`'s council to the Jews:
if this is of man it will come to nothing, but if it is of God, you cannot overthrow it.
Be careful you are not found to be fighters against God.`"
And the captain said, "`Why did you not come to the prison?`"
"`The reason`" I said, "`was,
because I heard the man might go if he pleased;`"
and therefore I called him down and said,
"`Come down, William, you may go away if you will.`"
Then captain Oliver said it was not so; and asked me what I had to do with it?
Then he bid me be gone; and I told them, "`I am willing to leave;
for I cannot endure to see this.`"
And when I was in the town, some did seem to sympathize with me in my grief.
But I told them that they had no warrant from the word of God,
nor precedent from our country, nor power from his majesty to hang the man.

[.signed-section-closing]
I rest your Friend,

[.signed-section-signature]
Thomas Wilkie.

--

William Leddra being thus dispatched,
it was resolved to make an end also of Wenlock Christison.
He therefore was brought from the prison to the court at Boston, where the governor,
John Endicot, and the deputy-governor, Richard Bellingham, being both present, told him,
"`Unless you renounce your religion, you shall surely die.`"
But instead of shrinking, he said with undaunted courage, "`No,
I shall not change my religion, nor seek to save my life;
neither do I intend to deny my Master; but if I lose my life for Christ`'s sake,
and the preaching of the gospel, I shall save my life.`"
This noble resolution gave such a check to his persecutors,
that they did not then go on with the trial, but sent him away to prison again.
And it being said by somebody that William Leddra was dead,
a certain person said to Wenlock, "`O your turn is next!`"
To which he gravely replied,
"`The will of the Lord be done,`" showing thereby his entire resignation.

Being now locked up again in prison, he was kept there till about the Fourth month.
But when the court was at last set, a spirit of confusion appeared there,
and a division arose among several of the members.
For though the greatest part were for taking the same course with
him as they had done with those that were already put to death,
yet several would not consent to it.
And as natural occurrences sometimes cause reflections among observing people,
so it happened here;
for during their deliberations concerning how to deal with Wenlock Christison
(which lasted for the space of two weeks) the sun did not shine,
a thing at that season which was somewhat extraordinary.
This gave occasion for some to say that "`the sun, abhorring this bloody business,
hid itself from them.`"
But after many debates, the sanguinary council at length came to an agreement,
and Wenlock was brought to the bar.
There the governor, John Endicot, asked him what he had to say for himself,
why he should not die?
He answered, "`I have done nothing worthy of death.
If I have, I refuse not to die.`"
To this another said, "`You have come in among us in rebellion,
which is as the sin of witchcraft, and ought to be punished.`"
Hence it appears how perversely these blood-thirsty persecutors
applied the Holy Scriptures to their cruel ends,
and so made a wrong use of the prophet Samuel`'s words to Saul.
To this false conclusion Wenlock answered, "`I came not in among you in rebellion,
but in obedience to the God of heaven; not in contempt to any of you,
but in love to your souls and bodies; and this you shall know one day,
when you and all men must give an account of the deeds done in the body.
Take heed,`" he thus continued, "`for you cannot escape the righteous judgments of God.`"
Then major-general Adderton said, "`You pronounce woes and judgments,
and those that came before you pronounced woes and judgments;
but the judgments of the Lord God have not come upon us yet.`"
So insolent and hard-hearted may man become,
as not to hesitate even to defy the Most High.
But before we draw the curtains of this stage,
we shall see the tragic end of this Adderton, who now received this answer from Wenlock:
"`Be not proud, neither let your spirits be lifted up.
God does but wait till the measure of your iniquity be filled up,
and you have run your ungodly race.
Then will the wrath of God come upon you to the uttermost.
And as for your part, it now hangs over your head,
and is near to be poured down upon you, and shall come as a thief in the night suddenly,
when you think not of it.`"

Then Wenlock asked, "`By what law will you put me to death?`"
The answer was, "`We have a law, and by our law you are to die.`"
"`So said the Jews of Christ,`" replied Wenlock, "`'`We have a law,
and by our law He ought to die.`' Who empowered you to make that law?`"
To which one of the board answered, "`We have a patent, and we are the patentees;
thus we have power to make laws.`"
Hereupon Wenlock asked again, "`What?
Do you have power to make laws that are repugnant to the laws of England?`"
"`No,`" said the governor.
"`Then,`" replied Wenlock, "`you have gone beyond your bounds,
and have forfeited your patent; and that is more than you can answer for.
Are you subjects to the king, yes or no?`"
"`What good will this do you?`"
replied the secretary.
"`If you are,`" answered Wenlock, "`then say so; for in your petition to the king,
you desire that he would protect you,
and that you may be worthy to kneel among his loyal subjects.`"

To which one of them said, "`Yes, we are subject.`"
"`Well,`" said Wenlock, "`so am I, and for all I know, I am as good a subject as you,
if not better; for if the king did but know your hearts as God knows them,
he would see that they are as rotten towards him as they are towards God.
Therefore seeing that you and I are subjects to the king,
I demand to be tried by the laws of my own nation.`"
It was answered,
"`You shall be tried by a bench and a jury;`" for it seems they began
to be afraid to go on in the former course of trial without a jury,
this being contrary to the laws of England.
But Wenlock said, "`That is not according to law;
for I have never heard nor read of any law in England to hang Quakers.`"
To this the governor replied that there was a law to hang Jesuits.
To which Wenlock returned, "`If you put me to death,
it is not because I go under the name of a Jesuit, but of a Quaker.
Therefore I appeal to the laws of my own nation.`"
But instead of taking notice of this, one said, "`You are in our hands,
and have broken our law, and we will try you.`"
Wenlock appealed again to the law of his own nation; yet the jury being called over,
went out, and quickly returned, bringing in a guilty verdict.
Upon this, the secretary said, "`Wenlock Christison, hold up your hand.`"
"`I will not,`" said Wenlock, "`I am here and can hear you.`"
Then the secretary cried, "`Guilty or not guilty?`"
"`I deny all guilt,`" replied Wenlock, "`for my conscience is clear in the sight of God.`"
But the governor said, "`The jury has condemned you.`"
Wenlock answered, "`The Lord does justify me; who are you that condemns?`"

They then voted concerning the sentence of death, but were in a manner confounded,
for several could not vote him guilty of death.
The governor seeing this division, said, "`I could find in my heart to go home!`"
And being in a rage, he flung something furiously on the table.
This made Wenlock cry, "`It would be better for you to be at home rather than here,
for you are about a bloody piece of work.`"
Then the governor put the court to a vote again; but this was done confusedly,
which so incensed the governor that he stood up and said, "`You that will not consent,
record it.
I thank God I am not afraid to give judgment.`"
Thus we see that to be drunk with blood, does not quench the thirst after blood;
for Endicot the governor, seeing others unwilling to vote,
precipitately pronounced judgment himself, and said, "`Wenlock Christison,
hearken to your sentence: You must return to the place from which you came,
and from there to the place of execution,
and there you must be hanged until you are dead, dead, dead!`"
To which Wenlock said, "`The will of the Lord be done, in whose will I came among you,
and in whose counsel I stand, feeling His eternal power,
which will uphold me unto the last gasp.`"
Moreover he cried thus: "`Let it be known unto you all,
that if you have power to take my life from me,
my soul shall enter into everlasting rest and peace with God,
where you yourselves shall never come.
And if you have power to take my life from me (which power I do question),
I do believe you shall never again take any Quakers`' lives from them; note my words.
Do not think to weary out the living God by taking away the lives of His servants.
What do you gain by it?
For after the last man that you put to death,
here are five more who have come in his place.
And if you have power to take my life from me,
God can raise up the same seed of life in ten of His servants,
and send them among you in my place, that you may have torment upon torment,
which is your portion; for there is no peace to the wicked, says my God.`"
The holy confidence with which he uttered these words does show,
and what follows made it appear plainly,
that something supernatural was contained in them.
And it is remarkable, that among the imprisoned Quakers,
there were then several that had been banished on pain of death,
and among these also Elizabeth Hooton, and also one Edward Wharton,
who stayed in his habitation contrary to his sentence of banishment.

Wenlock, having received a sentence of death, was brought to prison again,
where having been detained five days,
the marshal and a constable came to him with an order from the
court for his release with twenty-seven more of his friends who
were then in prison for their testimony to the Truth,
saying they were ordered by the court to make him acquainted with their new law.
"`What does this mean?`"
said Wenlock, "`You have a new law?`"
"`Yes,`" said they.
"`Then you have deceived the people,`" said Wenlock.
"`Why?`"
said they.
"`Because,`" said he, "`you told them that the gallows was your last weapon,
and that your law was a good and wholesome law made for your peace,
and the safeguard of your country.
Have your hands now become weak?
The power of God is over you all.`"

Thus the prison doors were opened, and Wenlock, with twenty-seven more of his friends,
as aforesaid, were set at liberty, save two of them, namely,
Peter Pearson and Judith Brown, who, being stripped to the waist and fastened to a cart,
were whipped through the town of Boston with twenty stripes apiece.

Now, though not long after this an order came from the king (as will be mentioned shortly)
whereby these persecutors were charged to desist from putting the Quakers to death,
yet is seems they had already caught a scent of the king`'s displeasure,
who had a mind to stop their bloody career.
For having gotten a book written by George Bishop containing
a relation of the cruel persecution in New England,
he read a passage therein concerning major-general Denison, who,
to put off those that complained of their wicked proceeding, said,
"`This year you will go to complain to the parliament,
and the next year they will send to see how it is here;
and the third year the government will be changed.`"
The king took much notice of this, and calling to the lords to hear it, said, "`Lo,
these are my good subjects of New England; but I will put a stop to them.`"

It was not long before an opportunity was offered;
for the news of William Leddra`'s death having come into England,
with information of the danger that others were in of going the same way,
their friends took it to heart.
And Edward Burrough, having gotten an audience with the king, said to him,
"`There is a vein of innocent blood opened in your dominion,
which if it is not stopped will overrun all.`"
To this the king replied, "`But I will stop that vein.`"
Then Burrough desired him to do it speedily; "`for we know not,`" said he,
"`how many may soon be put to death.`"
The king said to some present, "`Call the secretary, and I will do it presently.`"
The secretary having come, a judicial writ was immediately granted.
A day or two after, going again to the king to desire a dispatch of the matter,
the king said he had no occasion at present to send a ship to New England;
but if they would send one, they might do it as soon as they could.
Edward Burrough then asked the king if he would willingly
grant his deputation to one called a Quaker,
to carry the judicial writ to New England.
The king answered, "`Yes, to whomever you desire.`"
Whereupon E. Burrough named one Samuel Shattock, who being an inhabitant of New England,
had been banished on pain of death, if ever he returned there.
The king accordingly granted the deputation to him, with full power to carry the writ,
which was as follows:

[.embedded-content-document.legal]
--

[.salutation]
Charles R.

Trusty and well-beloved, we greet you well.
Having been informed that several of our subjects among you, called Quakers, have been,
and are imprisoned by you, whereof some have been executed,
and others (as has been represented unto us), are in danger to undergo the like;
we have thought fit to signify our pleasure on their behalf for the future,
and do hereby require,
that if there be any of those people called Quakers among
you who are now already condemned to suffer death,
or other corporal punishment,
or that are imprisoned and subject to the like condemnation,
you are to forbear to proceed any further therein.
Rather,
you are to forthwith send the said persons (whether condemned
or imprisoned) over into this our kingdom of England,
together with the respective crimes or offenses laid to their charge,
to the end that such course may be taken with them
here as shall be agreeable to our laws,
and their demerits.
And for so doing, this letter shall be your sufficient warrant and discharge.

[.signed-section-closing]
Given at our court at Whitehall, the 9th day of September, 1661,
in the 13th year of our reign.

[.signed-section-closing]
By his majesty`'s command,

[.signed-section-signature]
William Morris

--

[.offset]
The superscription was:

[.embedded-content-document.letter]
--

To our trusty and well-beloved John Endicot, Esq.
and to all and every other governor or governors of our plantations of New-England,
and of all the colonies thereunto belonging, that now are, or hereafter shall be;
and to all and every minister and officer of our said plantations and colonies whatsoever,
within the continent of New England.

--

Thus favorable the king manifested himself;
and in England persecution for religion was a little at a stand;
but this was only a kind of respite.
G+++.+++ Fox the younger, a man of excellent qualifications and great boldness,
foresaw an imminent storm; and lest any carelessness might enter among his friends,
in the Fourth month he wrote the following exhortation to them:

[.embedded-content-document.epistle]
--

What my heavenly Father has determined for these men to do, no man can stop it.
Oh that patience might be abode in by all that know His name,
and His will submitted unto by them that He has called.
O be still, strive not, but drink the cup which our Father allows to be given.
I know it will be bitter to some,
but whoever strives against it shall come to loss and shame.
For the Lord will yet further try His people,
till it be fully and clearly manifest who are approved in His sight.
This He will certainly do;
therefore let not the present calm beget a wrong security in any, for lo the day hastens,
and comes swiftly, when another storm must arise;
and it will be in vain to flee to the tall cedars and strong oaks for shelter;
for nothing but the name of the Lord can preserve in that day.

[.signed-section-signature]
George Fox, the younger.

--

George Fox the younger was not mistaken in this exhortation when he said "`the
day hastens when another storm must arise,`" as we shall see before long;
but first we must take a view of things in America.

The judicial writ to the rulers of New England having been obtained, as has been said,
a quick dispatch was thought necessary to send it there.
And Samuel Shattock having been empowered by the king to carry it,
an agreement was made with one Ralph Goldsmith, who was master of a good ship,
and also one of those called Quakers,
for three hundred pounds (goods or no goods) to sail in ten days.
He then immediately made all things ready to set sail,
and with a prosperous gale arrived in about six weeks
time at the town of Boston in New England,
upon a First-day of the week.
The townsmen seeing a ship come into the bay with English colors, soon came on board,
and asked for the captain.
Ralph Goldsmith told them he was the commander.
They then asked him whether he had any letters, and he said "`Yes.`"
Whereupon they asked if he would deliver them; but he said, "`No, not today.`"
So they went ashore and reported there was a ship full of Quakers,
and that Samuel Shattock was among them,
who they knew was by their law liable to be put to death for coming in again after banishment.
But they knew not his errand nor authority.

All being thus kept quiet,
and none of the ship`'s company allowed to go on shore that day,
the next morning Samuel Shattock, the king`'s deputy, and Ralph Goldsmith,
the commander of the vessel, went on shore.
Then sending the men that brought them ashore back to the ship,
the two of them went through the town to the governor John Endicot`'s door, and knocked.
He sending a man to know their business,
they sent him word that their business was from the king of England,
and that they would deliver their message to none but the governor himself.
Thereupon they were admitted to go in,
and the governor came to them and commanded Shattock`'s hat to be taken off,
and having received the deputation and the judicial writ, he laid off his hat.
Then, ordering Shattock`'s hat to be given him again, he looked upon the papers,
and went out with the deputy-governor,
and bid the king`'s deputy and the master of the ship to follow him.
Having come to the deputy-governor, and having consulted with him about the matter,
he returned to the two aforesaid persons and said,
"`We shall obey his majesty`'s command.`"
After this, the master of the ship gave liberty to the passengers to come ashore,
which they did,
and met together with their friends of the town to offer
up praises to God for this wonderful deliverance.

Now for as much as several of their friends were yet in prison at Boston,
the following order was given forth by the council not long after.

[.embedded-content-document.legal]
--

[.salutation]
To William Salter, keeper of the prison at Boston.

You are required by authority, and order of the general court,
forthwith to release and discharge the Quakers, who at present are in custody.
See that you do not neglect this.

[.signed-section-closing]
By order of the court,

[.signed-section-signature]
Edward Rawson

[.signed-section-context-close]
Secretary:Boston, 9th Dec. 1661.

--

They then consulted what to do that they might not incur the king`'s displeasure;
and it was agreed to send a deputation to him.
First,
colonel Temple was sent to acquaint the king with their having set the Quakers at liberty;
and he was followed not long after by the chief priest John Norton,
and Simon Broadstreet, one of the magistrates.

The year was now spent; but before I conclude it I must take notice,
as a glaring instance of the marvelous fluctuation of worldly affairs,
that in the forepart of this year, the body of Oliver Cromwell,
which had been buried with great fanfare in Westminster Abbey, was dug up,
as were also the bodies of Bradshaw and Ireton,
which three corpses were carried in carts to Tyburn, and there hanged on the gallows.
Then the executioner chopped off the heads, stamped with his foot on the bodies,
which were tumbled into a pit, dug near the gallows;
and the heads were exposed on the top of Westminster Hall,
where I remember to have seen them.^
footnote:[Cromwell`'s head remained on a pole above Westminster Hall until 1685,
when it blew off during a strong storm.
After this, it was in the hands of various private collectors and museums until March 25,
1960 when it was at last buried at Sidney Sussex College in Cambridge,
Cromwell`'s alma mater.]
And that now befell Cromwell which he said about
seven years before in his speech to the parliament,
as has been mentioned in its due place, namely,
that he would rather be rolled into the grave and buried with infamy,
than give his consent to the throwing away one of the fundamentals of that government,
namely, liberty of conscience.
And yet he allowed persecution to go on, as has been related at length; but now,
according to his own words, he was roiled with infamy into the grave,
which may serve indeed for a remarkable instance
of the justice and equal judgments of God.

About this time a book came out at London, bearing the title of [.book-title]#Semper Idem#,
i+++.+++ e. __Always the Same; a Parallel of Fanatics.__
The author concealed his name, but he made it sufficiently manifest that he was a Papist,
and perhaps a Jesuit:
for he inveighed not only against the Quakers and Baptists,
but also against the Presbyterians, and even Episcopalians,
and consequently against all Protestants.
Indeed,
the martyrs that were burnt during the bloody reign of queen Mary (the eldest daughter
of king Henry the Eighth) were no less vilified than the Quakers in the said book,
by the scornful name of "`rebels,`" and "`fanatics.`"
This book was sold publicly,
and it seemed that none dared oppose it for fear of displeasing the court.
But Edward Burrough, who was of an undaunted courage, and so continued till his death,
employed his pen to refute it, and gave forth his answer in print,
plainly showing what the anonymous author aimed at, namely,
that he would have the cruel usage of fire and faggots revived,
and wished to see the burning of reputed heretics brought again into vogue.
This was the more to be taken notice of,
because such a publication of vilifying the martyrs with calumnies,
had not been seen at London for over a hundred years,
and all the groundless positions of the said author were
very distinctly answered by the said E. Burrough.

And since persecution in the latter end of this year
began to appear again with open face,
he published a book, which he called [.book-title]#Antichrist`'s Government Justly Detected#.
This he dedicated to all the rulers, etc. in the (so called) Christian world;
and therein, with sound arguments,
he manifested the unlawfulness and injustice of persecution,
and from which it had its rise; and showed how dangerous it was to compel a religion.

He also treated at length concerning heresy,
and what punishment belonged to such as are truly convicted of it.
But lest any might think that he was for opposing
the duty of the civil magistrate against malefactors,
he said concerning the punishment of heresy (which
he stated to be only an ecclesiastical censure),
that he only intended this,
"`where the error of a man and his heresy in his mind and judgment,
did only extend to the hurt of his own soul, and against God,
and not to the harm of his neighbor`'s person or estate.
But,`" he continued,
"`if his error and heresy do extend further than only against God and his own soul,
even to outward wrongs, or evils, or violence, or visible mischiefs committed,
such as murders, or other the like crimes against men, to the injuring of others,
then I forbid not outward external punishment to be corporally
inflicted upon the person and estate of such a man.`"
The author also wrote circumstantially concerning the government of antichrist,
and showed the deceit that was in it, and who were the subjects of his kingdom.

It was a little before this time that George Fox the younger, being a prisoner,
and seeing an intent of promoting popery, wrote the following letter to the king:

[.embedded-content-document.letter]
--

The King of kings has beheld, yes,
the King of kings has seen even all your actings in the dark,
and He has traced your walking in obscure places;
and you have not hid your counsels from the Almighty,
but He has seen all the intents of your heart,
and your good words have not at all deceived Him,
nor those who purely stood in His counsels; for He has seen the snares,
and beheld the pits which have secretly been prepared for the innocent
(even in the time when smooth words have been given),
and He has showed them unto others.

Oh that you would have taken counsel of the Lord, and obeyed Him,
for then you would have prospered;
but you have taken counsel of those who have caused you to err.
You have also sought to exalt and establish yourself, and your own honor,
and not the truth and honor of God only; which if you had truly done (in self-denial),
God would have honored you.
You have not taken the Lord for your strength and stay,
but have leaned upon that which cannot help you,
even upon that which will prove a broken reed unto you,
if you come to prove its strength.
You have greatly dishonored and grieved the Lord,
by your setting up ministers which He loathes,
and by your providing a forced maintenance for them by an unjust law,
that so they may yet make a prey of His people,
who for conscience-sake cannot put food into their mouths,
being spiritually gathered therefrom by the Word of the Lord.
You have also grieved the Spirit of the Lord,
in that you have not put a difference between that which moves by the Spirit of the Lord,
and that which is moved by the evil lusts of men;
and hereby you have justified that which God has condemned,
and condemned that which He has justified, and will justify in the sight of His enemies.

O, friend, it is not the person of any man which the Lord regards,
but it is righteousness which He has respect to,
and so far as man (whatever he may be) by the drawing of the Truth comes into righteousness,
and acts therein, so far the Lord has unity with him, and no further.
These things should have been considered by you.
You have also grieved the Holy Spirit by allowing all these wicked and
profane shows and sports which have abounded since your coming in,
by which the Lord`'s good creation has been abused, wasted, and devoured.
You have highly displeased the Lord God,
by your allowing persecution to be acted in your name,
even while you in words have promised liberty; yes,
many are this day in holes and prisons for the testimony of a good conscience,
and for obeying the doctrine of Christ.
Oh! the Lord is grieved with the pride and wickedness that is lived in,
both in your family and dominions,
and you yourself have not been such a pattern and
example among them as you ought to have been.

O, friend!
When I behold the wickedness, cruelty, and oppression,
that abounds in this nation in open view,
and also the secret abominations which are committed,
and are lurking and being plotted in the inner chambers;
verily my life is even bowed down because of the fierce wrath of the Almighty,
which I see is kindled;
and because of the great destruction which I see attends the wicked,
whose ends and counsels the Lord will frustrate,
and upon whom He will pour out everlasting contempt.
Yes, and it has often been in me, before you came into the land, and also since,
when it has been shown to me what idolatry is intended secretly to be brought in;
and certainly it had been better for you that you had never come,
for I have seen it tending to your destruction.
And when I have seen the abomination and cruelties which are committed and intended,
a pity has arisen in me towards you for your soul`'s sake; and it has been my desire,
if it might stand with the will of God,
that He would put it into your heart to go out of the land again,
so that your life might be preserved, and that you might have time to repent;
for although many men flatter and applaud you for selfish ends,
yet I see the Lord is displeased with your ways.
Let no man deceive you by feigned words; God will not be mocked: such as you sow,
that you must reap.
You cannot hide yourself from the Lord, nor deliver yourself from the stroke of His hand.
O consider how soon the Lord has taken away your brother, who,
according to outward appearance might have lived longer than you!^
footnote:[Henry Stuart, Duke of Gloucester, died of smallpox in September of 1660,
at twenty years of age.]
O, think not that men can preserve you, though all the nations about promise to help you!
For when the Lord appears against you, then you must fall;
verily there is a great desolation near, your hand cannot stop it;
God has decreed that He may exalt His own kingdom.
The nations are like a boiling pot, a little flame will set them on fire,
and the windy doctrine of the priests shall help to kindle it;
oh the day will be terrible, who may abide it!
The stubble will be consumed, and the chaff shall be burned; the ungodly shall be abased,
for they cannot stand in judgment; but the seed shall be exalted.

O what shall I say that might be for your safety?
Verily I can say little; the Lord`'s decree must stand, the Lord is highly displeased,
and His wrath is near to be revealed.
He is swift in His goings,
and He will shorten the days of His enemies for His elect`'s sake.
O that your soul might be saved in the day of the Lord!
My spirit is in suffering for you,
my soul is afflicted within me because of the approaching of the day of your calamity,
from which no man can deliver you.
This is the Truth that must stand, and in love to your soul it is declared,
by him who must deal uprightly with all men; though for it I suffer outwardly,
yet I have a witness in your conscience, unto which I am made manifest;
and peace with the Lord is my portion, which is better than an earthly crown.

[.signed-section-signature]
George Fox, the younger.

[.signed-section-context-close]
Given the 9th day of the Eighth month, 1660.

--

This letter (a clear evidence of the author`'s innocent
courage) was delivered to the king,
who read it, and seemed to be reached thereby, and touched at heart.
But his brother, the duke of York, was displeased with it,
and being violently set against the author, advised the king to use severity towards him.
But the king, being good-natured, said, "`It would be better for us to amend our lives.`"

While George Fox the younger was prisoner in Lambeth-house,
he wrote also a small treatise called, [.book-title]#England`'s Sad Estate and Condition Lamented#.
Herein he reproved the grievous abominations committed among the inhabitants,
oppression by persecution, and the hypocrisy of the priests.
He also predicted the pestilence which will be mentioned hereafter in its due place;
and signified not obscurely,
that endeavors would be used publicly to introduce superstition and idolatry,
but that those who intended to do so would be frustrated by the Lord in their attempts.
And others, whose worship did displease the Lord, should grind and waste one another,
but that beyond their expectation, He would pluck out from among them,
and preserve a holy seed.
And that after He will have executed His vengeance
upon the rebellious and treacherous dealers,
He will then bring forth the remnant of His holy seed,
which will be preserved from their fury; and then they shall spread over all,
and stand in dominion.
"`But,`" he continued, "`although these things, concerning the holy remnant,
shall certainly be fulfilled in their season, yet before they will be fully accomplished,
great will be the trials of many of the righteous,
and there will be great judgments executed in you, O land,
by Him who ofttimes makes a fruitful land barren,
because of the wickedness of them that dwell therein.`"
This, and much more he wrote and published it in print.
Several of his predictions we have seen fulfilled,
as in the progress of this history may appear;
and this last we will refer to at the proper time.
After the writing of this treatise, he also gave forth the following prayer.

[.embedded-content-document.prayer]
--

Surely it was You, O Lord, that gave bounds unto the sea,
that the floods thereof could not overwhelm Your chosen.
You can let forth the winds and permit a storm, and You can make a calm when You please.
You have the glory of all, O King of saints and Savior of Israel!
You can do whatever You please, therefore we will trust in Your name,
and will fear not what men can do unto us, because You will not forsake us;
but You will plead our cause in the sight of our adversaries,
and they shall know that You are our God, who is able to save to the uttermost.
O Lord, our righteousness, we will praise Your name; for Your mercies endure forever.
Our eyes, O God, are unto You, for we have no other helper.
Our faith, O Lord, stands in You, who cannot forget Your people.
You have revealed and brought up Jacob, who wrestles with You, and prevails as a prince,
therefore the blessing must come.
O Lord, the birth of Your seed cries unto You, Your own elect,
which has long been oppressed.
You cannot deny Yourself, therefore we have faith, and a hope that does not disappoint.
O Lord, how unsearchable are Your ways!
You have even amazed Your people with the depth of Your wisdom;
You alone will have the glory of their deliverance,
and therefore You have allowed these things to come to pass.
O Lord, You are righteous in all Your judgments;
only preserve Your people which You have gathered,
and will gather unto Yourself in the day of trial, that so they may sing of Your power,
and magnify Your name in the land of the living.

--

This George Fox +++[+++the younger]
wrote also in prison several other papers and epistles,
for exhortation and consolation of his friends; but his work was soon done,
so that not long after this he departed this life, which was in this or the next year.
He was, as may be seen from his writings, a man of extraordinary resignation and courage;
and that he gave up his life, may appear from a small book that he wrote,
being prisoner in Lambeth-house,
which he called, [.book-title]#The Dread of God`'s Power Uttering
its Voice through Man, unto the Heads of the Nation#.
Herein he exhorted the rulers very earnestly to do justice; and said among other things,
"`Friends, I must deal plainly with you in the sight of God,
who has made me a prophet to the nation.
I may not flatter any of you.
My life is in the hand of my Maker,
and not one hair of my head can fall to the ground without His providence.
He has redeemed my soul from hell, and my mind from the earth;
and He has given me His good Spirit to lead me.
I am henceforth no more my own, but I am the Lord`'s, who has formed me to His praise,
and has brought me forth, that I may sound forth His powerful Truth among the people.
Therefore I must not fear man, neither must I be afraid of the sons of men.`"

Thus he showed himself undaunted; but it was not long before he made his exit,
of which I cannot but say something.
In his sickness, I find that, though he was weak in body, yet he was strong in spirit,
so that he would sing for joy of heart.
He exhorted his friends to keep in unity, foreseeing, it may be,
that something would rise which might give occasion for division.
And then with much fervency of spirit, he prayed God, and exhorted his friends,
to keep their garments unspotted from the world,
because great was the day of trial that was at hand.
Afterwards recommending them to the Lord, he took his leave of them,
and slept in perfect peace with the Lord, being of sound mind to the last.
Now the dust was returned to the earth, and the spirit unto God who gave it;
and thus he was freed from all danger of losing the crown of immortal life,
which man by temptation, and the casualties of this life, is liable unto,
if he continues not diligently watchful.
But this valiant was now beyond the reach of all temptations, and so I leave him,
that I may pass on to other matters.

In this year Edward Burrough wrote a paper to the king and his council,
which he called, [.book-title]#A Just and Righteous Plea#, in which he proposed, at length,
the reasons why the people called Quakers refused to take the oath of allegiance,
showing that it was not because they would not be faithful to the king,
but only for conscience-sake, since Christ so expressly had commanded his followers,
"`Swear not at all,`" which command they dared not transgress.
Yet to assure the government of their faithfulness, he said thus:

[.embedded-content-document.paper]
--

We are now, and shall continue to be faithful, innocent,
and peaceable in our several stations and conditions,
under this present government of king Charles the Second,
whom we acknowledge to be supreme magistrate and governor over this kingdom;
and for conscience-sake we are obedient and submissive to him, as such,
in all his commands, either by doing and performing what he justly requires,
or by patiently suffering under whatever is inflicted upon us in
the matters for which we cannot be obedient for conscience-sake,
when anything is required of us different from the just law of God.
And to this subjection to the king and his government,
we are bound by the law of righteousness;
and this has ever been our principle and practice, and is unto this day:
even to be quiet, peaceable and patient, under every authority that is set over us,
and not to plot in unrighteousness, or contrive,
or rebel against any government or governors,
nor to seek our own deliverance from injustice and oppression in such a way.

We are persuaded to seek the preservation of the king`'s person and authority,
by all just and lawful means, and not to rebel against him with carnal weapons;
and so far as his government is in justice, mercy, and righteousness,
we declare true and faithful subjection and obedience thereunto.
And wherein it is otherwise,
we shall be subject by patient suffering what is wrongly imposed upon us,
and yet not rebel in any turbulent way of conspiracies and insurrections;
for our principles are not for war, but for peace with all men, so much as in us lies.
Nor may we render evil for evil to any,
but are to be subject to the king and his government, actively or passively,
upon the conditions aforementioned.

And we also renounce all foreign authority, power, and jurisdiction of the Pope,
or any other, from having any supremacy whatsoever over the king,
or any of the good subjects of England.
And this we declare, acknowledge, and testify,
in the fear and presence of God (to whom we and all
mankind must give an account) without secret equivocation,
or any deceitful mental reservation.

--

Thus fully E. Burrough declared himself,
and gave also a circumstantial relation of the practice of his friends meeting together,
or their way of public worship,
thereby to assure the government of their peaceable behavior and fidelity.
But all this proved in vain; for it being well known that the Quakers denied swearing,
they continually were vexed and persecuted under a pretense of
not giving due satisfaction of their being faithful to the government,
and so transgressing the laws.

Now the deputies of New England came to London,
and endeavored to clear themselves as much as possible, but especially priest Norton,
who bowed no less reverently before the archbishop than before the king.
And thus fawning upon the Episcopalians,
they found means to keep in a position to vex the Quakers, so called,
though they were forbidden to put them to death.
And the fact that many of the bishops were great enemies to the said Quakers,
appeared plainly from the cruel persecution which after a short calm arose in England.

But to return to the New England deputies,
they would eagerly have excused themselves altogether;
and priest Norton thought it sufficient to say that
he did not assist in the bloody trial,
nor had advised to it; however John Copeland, whose ear was cut off at Boston,
charged the contrary upon him.
George Fox (the elder) also got occasion to speak
with them in the presence of some of his friends,
and asked Simon Broadstreet, one of the New England magistrates,
whether he had a hand in putting to death those who were nick-named Quakers?
Not being able to deny this, he confessed he had.
Then G. Fox asked him and his associates that were present whether they
would acknowledge themselves to be subjects to the laws of England;
and if they did, by what laws they had put his friends to death?
They answered, they were subjects to the laws of England,
and they had put his friends to death by the same
law as the Jesuits were put to death in England.
Hereupon G. Fox asked them whether they believed that his friends,
whom they had put to death, were Jesuits, or influenced by Jesuits?
They said, "`No.`" "`Then,`" replied G. Fox, "`you have murdered them;
for since you put them to death by the law that Jesuits are put to death here in England,
it plainly appears, you have put them to death arbitrarily, without any law.`"
Thus Broadstreet finding himself and his company ensnared by their own words, asked,
"`Have you come to ensnare us?`"
But he told them, "`You have ensnared yourselves,
and might justly be tried for your lives;`" and he further said that if the father
of William Robinson (one of those that were put to death) were in town,
it was probable he would question them, and bring their lives into jeopardy;
for he not being of the Quakers`' persuasion,
would perhaps not have so much regard to forbearance as they had.
Broadstreet seeing himself thus in danger, began to flinch and to skulk;
for some of the old royalists were desirous that
the Quakers would prosecute the New England persecutors.
But G. Fox and his friends said they left them to the Lord, to whom vengeance belonged,
and He would repay it.
Broadstreet however, not thinking it safe to remain in England, left the city,
and with his companions went back again to New England.

Not long before this time, G. Fox, with the help of John Stubbs and Benjamin Furly,
published a book called, [.book-title]#A Battledore#.^
footnote:[A battledore, also called a hornbook,
was a leaf or page containing the alphabet or other educational materials,
covered with a sheet of transparent horn and fixed in a frame with a handle,
formerly used in teaching children to read.]
In this book were set forth examples from about thirty languages,
to show that every language had its particular denomination
for the singular and the plural number in speaking to persons;
and in every place where the description began, the shape of a battledoor was delineated.
This work was promoted to public view by G. Fox in order to show the learned
that the custom of the people called Quakers to say "`Thou`" to a single person,
though it were to the king, and not "`You,`" was not irregular nor absurd,
but had used generally;
and that therefore they could not justly be charged with disrespect for not following
the common custom which had only crept in because of the pride of men.
Now, though Gerard Croese does disapprove of G. Fox putting his name to this book,
as well as J. Stubbs and Benjamin Furly,
yet I do not think it so improper as the said author does;
for G. Fox was a great promoter of that work, and though he was not skilled in languages,
and some were for calling him an idiot or a fool,
yet I know him to have been a man of good understanding and of deep judgment.
In his journal he freely acknowledges that John Stubbs and
Benjamin Furly took great pains in compiling the said book,
which he put them upon, and then added also some things to it;
so that in some respect he might be esteemed an author too.

This book (in which J. Stubbs and B. Furly also gave
directions for learners to read the Hebrew,
Oriental, and other languages), was liberally distributed.
Some of them were presented to the king and his council, to the archbishop of Canterbury,
to the bishop of London, and also one to each university.
The king confessed that the distinction between plural and singular,
in regard of persons, was the proper language of all nations;
and the archbishop being asked what he thought of it, was so at a stand,
that he could not tell what to say to it; for it appears he would not commend it,
neither could he resolve to disapprove it.
Yet this did so inform and convince people,
that many afterward were not nearly so much offended
at hearing "`thee`" and "`thou`" to a single person,
as they were before.

Now many Papists and Jesuits began to fawn upon those called Quakers,
and said publicly that of all the sects the Quakers
were the best and most self-denying people,
and that it was a great pity that they did not return to the holy mother church.
But though they might have been in hopes thereby
to have gained proselytes from the Quakers,
yet they were disappointed.
In the meantime they did but poor service to the Quakers thereby,
for this gave occasion to their enemies to diffuse the rumor that there
was an affinity and complicity between the Quakers and the Papists.

At this time,
some Jesuits signified that they would willingly discourse with the Quakers,
and G. Fox consented to it; and in order thereunto, a time and place were appointed.
G+++.+++ Fox asked them the same question he had asked once before,
as has been related already, that is,
whether the church of Rome had not degenerated from
the church in the primitive times--from the spirit,
power, and practice that they were in in the apostles`' time.
The Jesuit to whom the question was put said he would not answer it.
G+++.+++ Fox asked him, "`Why?`"
But he would give no reason.
His companion then said they had not degenerated from the church in the primitive times.
Then G. Fox asked the other whether he was of the same mind; and he said, "`Yes.`"
G+++.+++ Fox, to give no room to any excuses of a mistake, repeated his question thus:
"`Whether the church of Rome now was in the same purity, practice, power, and spirit,
that the church in the apostles`' time was in?`"
The Jesuits seeing how exact G. Fox sought to be with them,
said it was presumption in any to say they had the
same power and spirit that the apostles had.
But G. Fox told them,
it was presumption in them to meddle with the words of Christ and his apostles,
and make people believe they succeeded the apostles,
and yet be forced to confess that they were not in the same
power and spirit that the apostles were in.
"`This,`" said he, "`is a spirit of presumption,
and is rebuked by the apostles`' spirit.`"
Thereupon he showed them how different their fruits and
practices were from the fruits and practices of the apostles.
This so displeased the Jesuits, that one of them said, "`You are a company of dreamers.`"
"`No,`" said G. Fox, "`you are the dreamers, who dream you are the apostles successors,
and yet confess you have not the same power and spirit, which the apostles were in.`"
Then he began to tell them also how they were led by an evil spirit,
and that this spirit had induced them to pray by beads, and to images,
and to put people to death for religion.
He spoke yet more; but the Jesuits soon grew weary of this discourse, and went away,
giving charge afterwards to those of their persuasion not to dispute with the Quakers,
nor to read any of their books.

Sometime after this G. Fox went to Colchester, where he had very large meetings.
From there he went to Coggeshall;
not far from which there was a priest convinced of the truth
of the doctrine held forth by him and his friends,
and he had a meeting in his house.
And after having visited his friends in their meetings thereabouts,
he returned to London, where he found more work; for John Perrot,
of whom mention has been made already that he was at Rome,
had so far yielded to his vain imaginations,
that he thought himself further enlightened than G. Fox and his friends.
From this presumption,
he declared he would not approve that when any one prayed in the meeting,
others should put off their hats,
calling this a formality and a common custom of the world,
which ought to be departed from.
And since novelties often draw people after them, so it was in this case,
insomuch that he gained a good number adherents.
But he did not stop here; for as one error proceeds from another,
so he made other extravagant steps, and let his beard grow,
in which he was followed by some.
In the meantime, G. Fox labored both by word and writing to stop his progress,
and though most of his friends also bore testimony against it,
yet there passed several years before this strange fire was altogether extinguished.
John Perrot, who now walked in an erroneous path, grew worse and worse,
even to such a degree that, having come into America,
he fell into manifest sensualities and works of the flesh;
for he not only began to wear gaudy apparel, but also a sword;
and having gotten into some place in the government, he became a severe exactor of oaths,
whereas before he had professed that for conscience-sake he could not swear.
Before I leave Perrot,
I will insert here a letter written by him from Rome when he was released from prison;
and though I believe he was then in a better state than afterward,
yet in this letter some sparks of spiritual pride may be seen,
which though then under some limitation,
yet in process of time so broke forth that it caused his fall.
The letter was thus:

[.embedded-content-document.letter]
--

O Israel; the host of the most high God;
His majesty has fulfilled to me the vision of my head,
having showed Himself to be the Holy and just One.
He has lately delivered me from the prison of the city of Rome,
together with the two lambs who are with me, whose faces, through God, are turned to you;
for which I beseech you in the holy spirit of meekness,
to bless the name of the Lord God.
Give thanks to Him for His power.
The God of life promote you all in the virtue of His mercy and forgiveness,
and keep you in the power of His everlasting love, unto the end.

[.signed-section-signature]
John.

[.signed-section-context-close]
Written to you all without the gates of Rome, the 2nd day of the Fourth month, 1661.
Send this forward and read my life in your meetings.

--

He added not his surname, in imitation, as it seems, of the apostle John.
He omitted it likewise in another letter he wrote from the prison at Rome,
which began thus:

[.embedded-content-document.letter]
--

I John the prisoner, being in the sense of the Spirit of life with you all, etc.

--

Who the two lambs were he mentions in his letter, I cannot tell;
whether they were persons that had been imprisoned with him in the inquisition jail,
and converted by him (as he thought), or whether he meant John Stubbs and Samuel Fisher,
I know not.
It may rather be supposed that he meant Charles Bayley and Jane Stoakes,
who went to Rome to procure his liberty.
If I am not mistaken, it was about this time that these were at Rome, and they perhaps,
having endeavored to obtain his liberty, departed before him towards England.

When Perrot afterward lived in America, about the beginning of the year 1665,
John Taylor wrote thus from Jamaica concerning him:

[.embedded-content-document.letter]
--

One of the judges of this place told me that he never had seen one who
so severely exacted an oath from people as John Perrot did.
And another judge that was also present,
said that Perrot had altogether renounced his faith, and aimed at nothing but his profit.

--

Such a man was John Perrot, though even some wise men admired him for a time;
but he became a man of a rough behavior.
Whether he ever repented sincerely, I cannot tell.
Robert Rich, who took too much part in the extravagancies of James Nayler,
as has been related, did also join with Perrot, and became estranged from the Quakers,
and in that condition he died.
But he was of the number of those of whom the apostle John said, "`They went out from us,
but they were not of us.`"

Now since persecution continued in England, Edward Burrough,
who continually was laborious with his pen to oppose this evil,
wrote also a small book which he called, [.book-title]#The Case of Free Liberty
of Conscience in the Exercise of Faith and Religion,
presented unto the King and both Houses of Parliament.#
In this treatise he showed that to deprive honest and peaceable
people of liberty of conscience in the exercise of worship to God,
was unjust, an encroaching on God`'s sovereignty, and a usurpation of His authority.
He also recommended it to their consideration,
that to impose by force a religion upon men was the way to fill the land with hypocrites.
And he showed with sound reasons,
that to persecute people for the exercise of religion and their worshipping of God,
must unavoidably tend to destroy trading, husbandry, and merchandise.
To this he added, that such as were called heretics were punished as malefactors,
whereas drunkards and other vicious persons were left unpunished; which,
to inculcate with more strength, he made use of the words of Dr. Taylor,
a bishop in Ireland, who said thus:
"`Why are we so zealous against those we call heretics,
and yet great friends with drunkards, and swearers, and fornicators,
and intemperate and idle persons?
I am certain a drunkard is as contrary to the laws of Christianity as a heretic.
And I am also sure that I know what drunkenness is;
but I am not so sure that such and such an opinion is heresy,`" etc.

It happened about this time in England that some covetous persons,
in order to wrest inheritances for themselves,
sought to call the marriages of those called Quakers in question.
And it was in this year that such a cause was tried at the court session at Nottingham.
A certain man, called a Quaker, died and left behind a wife who was carrying a child,
and an estate in copyhold lands.
When the woman delivered the child,
one that was near of kin to her deceased husband endeavored to prove the child illegitimate.
The plaintiff`'s counsel, willing to blacken the Quakers`' reputation,
asserted the child to be illegitimate because the
marriage of its parents was not according to law;
and also said bluntly (and very indecently) that
the Quakers joined together like brute beasts.
After the counsel on both sides had pleaded, the judge, whose name was Archer,
opened the case to the jury, and told them that there was a marriage in Paradise,
when Adam took Eve, and Eve took Adam,
and that it was the consent of the parties that made a marriage.
And as for the Quakers, he said he did not know their opinions,
but he did not believe they joined together as brute beasts, as had been said of them,
but rather as Christians; and therefore he believed the marriage was lawful,
and the child was the lawful heir.
And in order to better satisfy the jury,
he related to them another case where a man who was weak in body, and kept his bed,
had a desire in that condition to marry.
The man declared before witnesses that he did take such a woman to be his wife;
and the woman also declared that she took that man to be her husband.
This marriage was afterwards called in question,
but all the bishops at that time did conclude it to be a lawful marriage.
The jury having received this instruction, gave in their verdict for the child,
and declared it to be the legitimate heir.

It has been mentioned before, that G. Fox, when prisoner at Derby in the year 1650,
was exceedingly vexed and poorly treated by the keeper of the prison.
But this man, being struck with the terrors of the Lord, became such a notable convert,
that in the year 1662, he wrote the following letter to G. Fox:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

Having such a convenient messenger,
I could do no less than give you an account of my present condition,
remembering that in my first awakening to a sense of life, and of the inward Seed,
God was pleased to make use of you as an instrument;
so that sometimes I am taken with admiration that
it should about come by such means as it did;
that is to say, that Providence should order you to have been my prisoner,
in order to give me my first real sight of the Truth.
It makes me many times to think of the jailer`'s conversion by the apostles.
And although my outward losses are such since that time,
that I have become nothing in the world,
yet I hope I shall find that all these light afflictions, which are but for a moment,
will work for me a far more exceeding and eternal weight of glory.
They have taken all from me; and now instead of keeping a prison,
I am rather waiting when I shall become a prisoner myself.
Pray for me, that my faith fail not, but that I may hold out unto death,
that I may receive a crown of life.
I earnestly desire to hear from you, and of your condition,
which would very much rejoice me.
Not having else at present, but my kind love unto you,
and all Christian friends with you, in haste I rest,

[.signed-section-closing]
Yours in Christ Jesus,

[.signed-section-signature]
Thomas Sharman

[.signed-section-context-close]
Derby, the 22nd of the Fourth month, 1662.

--

I have heretofore made some mention of the imprisonment of Catharine
Evans and Sarah Cheevers by the inquisition at Malta.
It was about this time that they were released; for G. Fox and Gilbert Latey,
having understood that the lord d`'Aubigny could procure their liberty, went to him,
and having informed him concerning their imprisonment,
desired him to write to those in authority at Malta for their release.
This he promised to do, and told them if they would come again within a month,
perhaps they might hear of their discharge.
They went again to him about that time,
but he said he thought his letters had miscarried; yet he promised he would write again,
and so he did; and this had such an effect,
that the said two women were discharged of their long imprisonment.
G+++.+++ Fox had now opportunity to reason with this lord (who
was a Roman Catholic priest in orders) about religion,
and he brought him to confess that Christ had enlightened
every man that comes into the world with His spiritual light;
and that He had tasted death for every man; and that the grace of God,
which brings salvation, has appeared to all men;
and that it would teach them and bring their salvation if they did obey it.
Then G. Fox asked him what the Romanists would do with all their
relics and images if they did acknowledge and believe in this light,
and receive the grace of God to teach them and bring their salvation?
And the priest answered,
that those things were but policies to keep people in subjection.

But leaving these discourses,
I will now give a clear and circumstantial relation of the imprisonment
of the aforementioned Catharine Evans and Sarah Cheevers,
chiefly collected from letters and papers written by them in prison,
and sent from there to England,
where they were published in print not long after their return, in the year 1662.

In the year 1658, these women having drawings in their mind to travel towards Alexandria,
went in a ship from England to Leghorn in Italy,
and having been thirty-one days between Plymouth and Leghorn,
they at length safely landed at that city.
There they found some of their countrymen and friends, and stayed several days,
dispersing many books when occasion offered.
They spoke also with people of various degrees, without being troubled by any.
From there they got passage in a Dutch ship bound for Alexandria, or Scanderoon;
but the master of the ship being in company with another ship going to Malta,
went also there, though he had no business in the place.
But before they came there, Catharine fell into such an anguish of mind,
that she cried out, "`Oh, we have a dreadful cup to drink at that place!`"
Having come into the harbour, and standing on the deck of the ship,
and looking upon the people who stood on the walls, she said in her heart,
"`Shall you destroy us?
If we give up to the Lord, then He is sufficient to deliver us out of your hands;
but if we disobey our God, all these could not deliver us out of His hand.`"
And so all fear of man was taken from them.

The next day, being the First-day of the week, they went on shore,
where the English consul met them, and asked them what they came there for.
They answered what they thought appropriate, and gave him some books.
He then told them there was an inquisition, and kindly inviting them to his house,
said all that he had was at their service while they were there.
They accepting this invitation, went there, and many came to see them,
whom they called to repentance, so that several became tender.
About night they went on board the ship, and the next day came again into the city,
and going to the governor he told them he had a sister
in the nunnery who desired to see them.
Thereupon they went to the nunnery and talked with the nuns, and gave them books.
One of their priests, who brought them into the chapel,
desired them to bow to the high altar, but they refused,
being grieved because of the idolatry committed there,
and so went to the consul`'s again, where they stayed some weeks.

During this time they once went into one of the places
of worship during the time of worship;
and Catharine standing in the midst of the people, turned her back to the high altar,
and kneeling down, she lifted up her voice in prayer to the Lord.
The priest that officiated put off his surplice,
and kneeled down near her till she had finished.
He then reached forth his hand to them to come to him, and offered her a token,
which she taking to be the mark of the beast, refused.
Thereupon he put the piece into Sarah`'s hand, but she gave it to him again,
and showed him her purse that she had money to give, if any had need,
and as yet was in no need.
He then asked if they were Calvinists or Lutherans?
And they answered, "`No.`" He asked if they would go to Rome to see the Pope?
They denying this, he asked if they were Papists;
to which they said they were true Christians, servants of the living God.
But since they had yet learned but little of the language spoken there,
they expressed themselves very defectively.
What they did communicate was partly in words and partly by signs, as well as they could.
Many that came around them were amazed, but at last they departed peaceably.
Some time after this they went again to a mass-house,
where the sacrament (as they call it) was administered.
There were many lights, and great costliness and fineries;
and being grieved because of their idolatry,
they stood about three quarters of an hour weeping and trembling, especially Catharine.
This so struck the congregation with amazement,
that some removed further from them for fear.
At length they both went out, but yet under such a trembling,
that they went along the street reeling and staggering,
so that they became a wonder to all that saw them.

They were about three months at the house of the English consul; and he, for that reason,
being under suspicion, did not do what he might have done to save them;
but in some respect, delivered them up to the inquisition,
though by his oath he was obliged to protect the English there.
In the meantime he kept them in his house, and did not permit them to go abroad,
though the governor had told him he might let them go about their business;
"`For,`" he said, "`they are honest women.`"
The consul might also have let them go free before
they came under the power of the black rod.
Catharine and Sarah perceiving at this time that
something to their prejudice was in agitation,
and feeling certain already that a prison would be their lot,
they signified to the consul that they suspected him,
and told him that Pilate desired to do the Jews a service,
and yet washed his hands in innocency.
The man being at a loss,
requested a sign of them to prove that they were messengers of God.
And they gave him to understand, that this might serve for a sign:
that it would be well with them; but that it should not end well with him.

Afterwards it happened that they were sent for by the inquisition.
That very day the consul`'s wife brought them some food;
but as she passed by them Catharine was smitten as with an arrow to the heart,
and she seemed to hear a voice, saying, "`she has obtained her purpose.`"
Then Catharine would not taste of the food, but rather went aside and wept exceedingly.
The consul having called her, told her that the inquisition had sent for them,
having received orders from Rome, but that he did hope they should be set free.
This however was not true,
for he knew (as they came to understand afterwards) that a room
had been prepared for them in the prison of the inquisition.
It was not long before the chancellor, the consul, and a man with the black rod,
came to them and brought them before the lord inquisitor.
He asked them whether they had changed their minds;
for it seems that this had been required of them previously.
But they answered, "`No,`" and that they should not change from the Truth.
Then he asked what new light it was they talked of?
They answered it was no new light,
but the same light which the prophets and apostles bore testimony to.
Next he asked how this light came to be lost since the primitive times?
They replied, it was not lost; for men still had it in them,
but they did not know it by reason of the night of
apostasy that had overspread the nations.
Then he said, if they would change their minds, and do as they were told,
they should say so, or else they would treat them as they pleased.
But the two women, signifying that they would not change their religion, said,
"`The will of the Lord be done.`"
The lord inquisitor then arose and went away with the consul, leaving them there;
and the man with the black rod, and the keeper,
took and put them into an inner room in the inquisition
which had only two little holes in it for light and air.
This place was so exceedingly hot, that it seemed as if their intent was to stifle them,
as we may see in what follows.

Not long after this they were brought before the inquisitors to be further examined,
and they not only asked their names, but also the names of their husbands and parents,
what children they had, and also why they came there?
To this they answered that they were servants of the living God,
and had come there to call them to repentance.
The next day they were called again, but were then examined separately.
Sarah being asked whether she was a true Catholic, said that she was a true Christian,
worshipping God in Spirit and in Truth.
Then they held forth a crucifix to her, and bid her swear she would speak the truth.
To this she said, she would indeed speak the truth, but she would not swear;
for Christ had commanded, "`Swear not at all.`"
The English consul who was present endeavored to persuade her to swear,
and said that none would do her any harm.
She having some books with her, they were taken from her;
and they asked her for what reason she had brought those books; to which she answered,
because they could not speak their language.
Then they asked her what George Fox was?
She answered, "`A minister.`"
They asked her again why she had come there?
She replied, to do the will of God as she was moved of the Lord.
The next question was, how the Lord did appear unto her?
To which she answered, "`By His Spirit.`"
And being asked whether she did see His presence and hear His voice,
her answer was that she heard His voice and saw His presence.
They then asked what He had said to her?
She answered, that He required of her to go over the seas to do His will.
This made them ask how she knew it was the Lord who required this of her?
To which she answered that the Lord had signified to her
that His living presence would go along with her,
and she found Him to perform His promise, for she indeed felt His living presence.
After this they went away.

Two days after this the inquisitors came and called for Catharine,
and offering her the crucifix,
they told her that the magistrates commanded her
to swear so that she would speak the truth.
To this she said that she would speak the truth, for she was a witness for God;
but she could not swear, since one greater than the magistrates had said,
"`Swear not at all; but let your yes, be yes, and your no, be no;
for whatever is more than these is from the evil one.`"
Then said they, "`You must obey the justice; and he commands you to swear.`"
She returned, "`I shall obey justice, but if I should swear, I would do an unjust thing;
for the Just One (Christ) said,
'`Swear not at all.`'`" Then they asked her whether she
did acknowledge the Christ that had died at Jerusalem?
She answered, "`We acknowledge the same Christ, and no other; He is the same yesterday,
today, and forever.`"
Next they asked her what she would do at Jerusalem?
She answered that she did not know that she should go there,
but that she intended to have gone to Alexandria.
They asked "`To do what?`"
Her answer was, "`To do the will of God.
And if the Lord opened my mouth, I would call people to repentance,
and declare to them the day of the Lord, and direct their minds from darkness to light.`"
They also asked her whether she did see the Lord.
She answered, "`God is a spirit, and He is spiritually discerned.`"

Now, though from the answers of these women little could be obtained to blame them,
yet they were kept close prisoners, which seemed to grieve the English consul,
for he came to them with tears in his eyes and said
he was as sorry for them as for his own flesh.
For it seems he had received something for delivering them up,
which he would willingly have given back,
if thereby he could have obtained their liberty; but a slavish fear possessed him,
and he never had peace while he lived.
Some days after this came a magistrate, two friars, the man with the black rod, a scribe,
and the keeper of the inquisition to examine them.
They were again required to swear, but they answered as before, that Christ said,
"`Swear not at all;`" and that the apostle James had given the same charge.
Hereupon the magistrate asked if they would speak truth, and they said, "`Yes.`"
He then asked whether they believed the creed,
to which they said they did believe in God, and in Jesus Christ,
who was born of the Virgin Mary, and suffered at Jerusalem under Pontius Pilate,
and arose again from the dead the third day, and ascended to His Father,
and shall come in judgment, to judge both quick and dead.
He further asked, how they did believe the resurrection?
They answered,
that they believed that the just and the unjust should arise according to the Scriptures.
Next he said, "`Do you believe in the saints, and pray to them?`"
To which their answer was, "`We believe in the communion of saints,
but we do not pray to them, but to God only, in the name of Jesus.`"
His next question was, whether they did believe in the Catholic church?
They answered, they did believe in the true church of Christ,
"`but the word Catholic,`" said they, "`we have not read in Scripture.`"
He also asked if they believed in purgatory, to which they said, "`No;
but a heaven and a hell.`"
Then one of the friars, who was an Englishman,
said "`We are commanded to pray for the dead;
and since those that are in heaven have no need,
and for those that are in hell there is no redemption,
therefore there must be a purgatory.`"
Then he asked if they believed the holy sacrament, to which they responded,
"`We have never read the word sacrament in Scripture.`"
The friar replied,
"`Where you read in your bibles '`sanctification,`' it says '`sacrament`' in ours.`"
He then said their holy sacrament was bread and wine,
which they converted into the flesh and blood of Christ, by the virtue of Christ.
"`Then,`" said the women, "`you work miracles;
for Christ`'s virtue is the same as it was when he
turned water into wine at the marriage in Cana.`"
The friar said, "`If we do not eat the flesh and drink the blood of the Son of God,
we have no life in us.`"
They replied, "`The flesh and blood of Christ is spiritual, and we do feed upon it daily;
for that which is begotten of God in us, can no more live without spiritual food,
than our temporal bodies can live without temporal food.`"
Then he said, "`You never hear mass.`"
"`But,`" they said, "`we hear the voice of Christ,
and He alone has the words of eternal life; and that is sufficient for us.`"
He said, "`You are heretics and heathens;`" to which they replied,
"`They are heretics that live in sin and wickedness,
and such are heathens that know not God.`"

Then it was asked them who was the head of their church?
They told him, "`Christ.`"
It was again asked what George Fox was, and they said, "`He is a minister of Christ.`"
And it being asked whether he had sent them, their answer was, "`No,
the Lord did move us to come.`"
Then the friar said, "`You are deceived, and have not the true faith;
even if you have all virtues.`"
They replied, "`Faith is the ground from which virtues proceed.`"
Hereupon it was told them that if they would take
the holy sacrament they might have their liberty;
otherwise the Pope would not free them for a million pieces of gold,
and they should lose their souls and bodies too.
To this they said, "`The Lord has provided for our souls,
and our bodies are freely given up to serve Him.`"
Then it was asked them if they did not believe that marriage was a sacrament?
They answered that it was an ordinance of God.
It was further asked if they did believe men could forgive sins?
Their answer was that none could forgive sins but God only.

After some other words back and forth, the women asked, "`Wherein have we wronged you,
that we should be kept prisoners all the days of our life?
Our innocent blood will be required at your hands.`"
The friar said he would take their blood upon him.
They replied,
"`The time will come when you shall find you have enough upon you without it.`"
Then it was told them that the Pope was Christ`'s vicar,
and what he did was for the good of their souls.
To this they answered, "`The Lord has not committed the charge of our souls to the Pope,
nor to you either; for He has taken them into His own possession;
glory be to His name forever.`"
Then it was said unto them they must be obedient;
to which they replied they were obedient to the government of Christ`'s Spirit or light.
The friar said, "`None have the true light but the Papists;
the light that you have is the spirit of the devil.`"
But they said, "`Woe to him that curses Jesus.
Can the devil give power over sin and iniquity?
That would destroy his own kingdom.`"
"`You,`" replied the friar, "`are laughed at and mocked by everyone.`"
"`But,`" said they, "`what will become of mockers?`"
"`It was no matter,`" he said, "`you run about to preach,
and do not have the true faith.`"
They replied, "`The true faith is held in a pure conscience,
void of offense towards God and men.
Everyone has the true faith that believes in God and in Jesus Christ whom He has sent.
But they that say they do believe, and do not keep His commandments, are liars,
and the truth is not in them.`"
The friar confessed this to be true,
though he was continually very troublesome to them with threats, to make them turn.
And to this end they were locked up in a room which was so exceeding hot,
that it was said it was impossible they could live long in it.
They were also so exceedingly stung by gnats when they lay in bed,
that their faces became swollen, as if they had been sick of the small-pox,
so that many began to be afraid of them;
and the friar said to Sarah that he spied an evil spirit in her face.

At another time, being examined,
they were asked how many of their friends had gone forth into the ministry,
and into what parts of the world.
They answering that question what they knew,
it was told them that all who came where the Pope had power, should never go back again.
But they said, the Lord was as sufficient for them,
as He was for the three men in the fiery furnace, and their trust was in God.
Catharine being sickly, she was asked why she looked so, and whether her spirit was weak?
She answered, "`No: my body is weak, because I eat no food.`"
The friar hearing this, offered her a license to eat meat, for it was during their Lent.
But she refused this, and said she could not eat anything at all.
And going afterwards to bed, she lay there night and day for twelve days together,
fasting and sweating, for she was in much affliction, and great was her agony.

After having lain there ten days, there came to her two friars, the chancellor,
the man with the black rod, a physician, and the keeper.
One of the friars commanded Sarah to go out of the room,
and then pulled Catharine`'s hand out of the bed, and said,
"`Is the devil so great in you, that you cannot speak?`"
To which she said, "`Depart from me you worker of iniquity;
the power of the Lord is upon me, and do you call Him a devil?`"
Hereupon he took up his crucifix to strike her on the mouth;
and she asked him whether that was the cross that had crucified Paul to the world,
and the world unto him?
This ignorant monk said it was.
But she denied this, and said,
"`The Lord has made me a witness for Himself against all workers of iniquity.`"
He then bade her be obedient, and went to strike her.
At this she said, "`Will you strike me?`"
And he saying he would, she further said, "`Then you are out of the apostles`' doctrine,
for they were no strikers.
I deny you to be any of those who are sent forth in the name of the Lord.`"
To this he said he had brought her a physician in charity; but she replied,
"`The Lord is my physician, and my saving health.`"
The monk growing angry, said she would be whipped and quartered,
and burnt that night at Malta, and her friend too.
But she told him modestly that she did not fear, for the Lord was on her side,
and he had no power but what he had received;
and if he did not use his power to the same end for which the Lord had given it to him,
He would judge him.
At these words they were all struck dumb, and went away.
Then the friar went to Sarah and told her that Catharine
had called him a worker of iniquity.
"`Did she?`"
said Sarah, "`Are you without sin?`"
To which he said he was.
"`Then,`" replied Sarah, "`she has wronged you.`"

Late in the evening,
something was proclaimed at the prison gate with the beating of a drum,
and early in the morning some came again with a drum and guns.
It seems to me that this was done on purpose to frighten these poor women,
and to make them believe that they should be put to death;
for indeed they expected little else,
having for several weeks believed that they would be led to the stake.
Nevertheless, they were fully resigned,
and given up to what the Lord might be pleased to permit.
In the meantime, Catharine continuing sickly, the friar came again with the physician;
but she told him she could not take anything unless she felt freedom.
He then said that they would never come forth out of that room while they lived;
and then pretending to be kind to them, he further said, "`You may thank God and me,
that it is no worse for you; for it was likely to be worse.`"
Thereupon they said, if they had died,
they would have died as innocently as ever any servants of the Lord did.
The friar then, turning to Sarah,
bade her take notice what torment Catharine would be in at the hour of death; saying,
"`thousands of devils would come and fetch her soul to hell.`"
But Sarah told him she did not fear any such thing.
He then asked Catharine if she did not think it right
for the elders of the church to pray over the sick.
She replied, "`Yes, such as are moved of the Spirit of the Lord.`"
He then fell down on his knees,
and began to howl and wish curses upon himself if he had not the true faith.
The physician in the meantime was enraged because she did not bow to him.

Now while Catharine was sick, Sarah was not without great affliction,
for it grieved her to see her dear companion so ill,
and she easily foresaw that if Catharine died, her own sufferings would be heavier.
Yet she was given up to the will of the Lord,
and would not in the least resent Catharine`'s coming to eternal rest.
But in time Catharine began to mend, and growing hungry and eating, she was refreshed.
But the room wherein they were locked was so excessively hot,
that they were often obliged to rise out of their bed and
lie down at the crack of the door for air to breathe.
This heat was the greater because it came not only from without,
but also from within the jail, which so affected them that their skin was parched,
the hair fell out of their heads, and they often fainted.
Indeed, their afflictions were so great, that when it was day they wished for night,
and when it was night, they wished for day; yes, through human weakness,
they even desired death, eating their bread weeping,
and mingling their drink with tears.

One time, the monks coming to her with a physician, and saying it was in charity,
Catharine asked whether they did not keep them in that hot room in order to kill them,
and then bring a physician to keep them longer alive?
To this the friar said,
the inquisitor would lose his head if he should take them from that room,
and it was better to keep them there than to kill them.
They then wrote to the inquisitor and laid their innocency before him; and said also,
that if it were their blood they thirsted after, they might take it any other way,
as well as to smother them in that hot room.
But this so incensed him that he sent the friar to them,
who took away their pen and ink (their bibles having been taken from them before).
They asked them why their goods were being taken away.
To this it was answered, "`All is ours; and your lives too, if we so desire.`"
Then they asked how they had forfeited their lives; to which it was told them,
"`By bringing in books and papers.`"
To this they replied that if there were anything in them that was found to be not true,
they might write against it.
To this the monk said, "`We do not write to fools and asses who did not know true Latin.`"
And it was further told them that the inquisitor desired to have them separated,
because Catharine was weak and she should go into a cooler room;
but Sarah should remain there.
Then Catharine took Sarah by the arm, and said, "`The Lord has joined us together,
and woe be to them that part us.
I had rather die here with my friend, than part from her.`"
This so struck the friar, that he went away and came no more for five weeks,
and the door of their room was not opened in all that time.

Then the monks came again to separate them,
but Catharine was sick and had broken out with an inflammation from head to foot.
They thereupon sent for a doctor, who said they must have air, or else they will die.
This was told to the inquisitor,
and he ordered the door to be set open six hours in a day.
But ten weeks after this the two were separated,
which was such a grievous affliction to them,
that they declared death itself would not have been so hard.
But the monks said they corrupted each other,
and that being separated they would bow and submit.
But these men saw themselves disappointed;
for the women were stronger afterwards than before,
the Lord fitting them for every condition.
Before they were separated, the friars brought them a whip of small hempen cords,
asking them if they desired to have it,
and saying that the monks would often whip themselves till the blood ran down.
But the women said, "`That cannot reach the devil, for he sits upon the heart.`"
Then the monks said, "`All the people of Malta are for you,
and if you will change and become Papists, then all will like you.`"
To this they replied, "`The Lord has changed us into that which changes not.`"
The monks then said, "`All our holy women do pray for you;
and you shall be honored by all the world if you will turn.`"
They replied, "`The world lies in wickedness; and we have denied its honor and glory.`"
To this the monks said, "`You shall be honored of God too;
but if not you will be hated by all.`"
"`This,`" said one of the women, "`is an evident sign whose servants we are;
for the servant is not greater than his Lord.`"

Once, on a First-day of the week,
the friars came and commanded them to kneel down with them in prayer.
But the women said they could pray only as they were moved by the Lord.
Then the friars commanded them a second time,
and then kneeled down by their bedside and prayed after their manner.
This being done, they said to the women, "`We have tried your spirits,
and now we know what spirit you are of.`"
But they told them they could not know that,
unless their minds were turned to the light of Christ in their consciences.
The English friar then growing angry, showed them his crucifix and bade them look upon it.
But they told him, "`The Lord says,
'`You shall not make to yourself the likeness of any thing that is in heaven above,
or in the earth beneath, or in the water under the earth; you shall not bow down to them,
nor worship them;
for I the Lord your God am a jealous God.`'`" The
friar seeing Sarah speak so boldly to him,
called for irons to chain her.
She then bowed her head, and said to him, "`Not only my hands and feet,
but my neck also for the testimony of Jesus.`"
The friar seeming appeased, said he would do them any good he could,
for he saw that what they did was not done in malice.
And they often said to them, "`If you would do but a little, you would be set at liberty;
but you will do nothing at all, but are against everything.`"
To this they replied, that they would do anything that might tend to the glory of God.

While they were imprisoned here,
it happened that the inquisition house was newly built or repaired,
which took up the space of about a year and a half.
During this time, some notable people came to see the building,
which gave opportunity to these women to speak to them,
and to declare the Truth in the name of the Lord.

Now, though they were threatened by the monks for preaching the light of Christ so boldly,
yet not only the magistrates, but the lord inquisitor grew moderate towards them,
and gave order they should have pens, ink,
and paper given to them in order to write to England.
Some seemed inclined to have them set at liberty,
but the friars worked mightily against it;
for they had labored about three quarters of a year
to separate them before they could bring it to pass.
And when at length they had effected it,
they told Catharine that they should never see one another`'s faces again.

In the meantime Catharine, being sickly, had little appetite to eat,
and had no desire to eat anything but what came from Sarah to her.
And having told one of the friars that she needed somebody to wash her linen,
and to prepare some warm food for her,
he sent to Sarah to know if she would do this for her.
Sarah said she would,
and by this means they heard from each other every day for some weeks.
The friar once said to Catharine, "`You may free yourself of misery whenever you will;
for you may make yourself a Papist,
and then have your freedom to go wherever you desire.`"
To this she answered, "`Thus I would have a name that I did live when I was dead.
You have enough Papists already,
but if you would endeavor to bring some of them to the light in their consciences,
then they would '`stand in awe and sin not.`'`" This friar was so eager,
that he said he would loose one of his fingers if she and Sarah would turn Papists.
But she told him, "`Babylon is the city that is built with blood,
but Zion is redeemed through judgment.`"

Many ways were used to draw them from their convictions;
and once they sought to persuade her to set a picture at the head of her bed for a representation;
but she said with abhorrence, "`What!
Do you think I need a calf to worship?
Do you walk by the rule of Scriptures?`"
To which the friar said, "`We do, but we have traditions too.`"
She replied,
"`If your traditions derogate or dissent from the fundamentals of Christ`'s doctrine,
the prophets, and apostles, I deny them in the name of the Lord.`"
But he asserted that they did not.
She then asked what rule they had to burn those that could not join with them for conscience-sake.
He replied, "`St. Paul did worse,
for he gave them over to the devil,`" and he further told her,
that they judged all to be damned who were not of their faith.
She then objected to him regarding several of the
superstitious rites of the church of Rome,
and mentioned also the forbidding of marriage, "`which,`" she said,
"`is a doctrine of devils, according to the saying of the apostle.`"
The friar being put to a stand, told her that St. Peter was the first Pope of Rome,
and built an altar there, and the Pope was his successor, and could do what he desired.
But she refuted this with sound reason.
He then boasting of the antiquity of their church,
she signified that the church she belonged to was yet older; "`For,`" said she,
"`our faith was from the beginning; and Abel was of our church.`"
The friar being at a loss, and no longer able to hold out against Catharine,
went to Sarah, and talked with her along the same lines.
She also told him that Abel was of our church; to which he said,
"`Abel was a Catholic;`" and quite overshooting himself, he said likewise,
"`And Cain and Judas were so.`"
To which Sarah returned, "`If that is true, then the devil is a Catholic;
and I will not be one.
I will not turn; though you tear me to pieces,
I believe the Lord will enable me to endure it.`"

At another time the said friar, whose name was Malachy, came again to Catharine,
and told her if she would be a Catholic, she must say so;
otherwise they would treat her badly, and she would never see the face of Sarah again,
but would die by herself, and a thousand devils would carry her soul to hell.
She then asked him if he were the messenger of God to her.
He said "`Yes.`"
"`Why?`"
she asked, "`What is my sin,
or wherein have I provoked the Lord that He does send me such a message?`"
"`It is,`" replied the monk, "`because you will not be a Catholic.`"
Whereupon Catharine said, "`I deny you and the message too,
and the spirit which speaks in you; for the Lord never spoke so.`"
Growing angry,
he said that he would lay her in a pile of chains
where she would see neither sun nor moon.
She intimating how resigned she was,
said he could not separate her from the love of God in Christ Jesus,
lay her wherever he would.
And saying further that he would give her to the devil, she resumed,
"`I do not fear all the devils in hell; the Lord is my keeper.
Though you had the inquisition, with all the countries round about it on your side,
and I was alone by myself, I do not fear them.
And if they were thousands more, the Lord is on my right hand;
and the worst they can do is but to kill the body;
they can touch my life no more than the devil could touch Job`'s.`"
Then the monk said she would never go out of the room alive.
To which she courageously said, "`The Lord is sufficient to deliver me;
but whether He will or not, I will not forsake the living Fountain,
to drink at a broken cistern.
And you have no law to keep us here, but such a law as Ahab had for Naboth`'s vineyard.`"
The monk then, cursing himself and calling upon his gods, ran away;
and as he was pulling the door, he said, "`Abide there, member of the devil.`"
To which she said, "`The devil`'s members do the devil`'s works;
and the woes and plagues of the Lord will be upon them for it.`"

The monk then went and told the inquisitor of this, who laughed at him;
and before he came again, Catharine had been moved out of that room.
When he came to her, he brought one of the inquisitor`'s men with him,
and two very good hens, and said, the lord inquisitor had sent them in love to her.
To this she said, she received his love,
but showed herself not very ready to accept of the gifts,
signifying that she was willing to pay for them,
but desired not to be chargeable to any while she had some money of her own.
The friar, who it seems desired them to lay down their money at his feet,
said they must not count anything their own,
for in the primitive times they sold their possessions,
and laid them down at the apostles`' feet.
He further said, "`You shall not lack anything, though we should spend a thousand crowns.
But you are proud,
because you will not take the inquisitor`'s hens which he sent to you in charity.`"
But she asked him, "`What kind of charity is this, since he keeps me in prison?`"
The friar said, it was for the good of their souls that he kept them in prison;
further adding, "`If you had not been going about to preach,
you might have gone wherever you desired.`"
She replied, "`Our souls are out of the inquisitor`'s reach.
But why should your love extend more to us than to your own people?
For they commit all manner of sins which you cannot charge us with.
Why do not you put them into the inquisition, and bid them to turn?`"
He then said, "`You have not the true faith;`" and showing her his crucifix,
asked her if she thought he did worship it?
She asked him, "`What then do you do with it?`"
To which he answered, it was a representation.
And she replied, it did not represent Christ,
for He was the express image of his Father`'s glory, which is light and life.
"`But,`" she continued, "`if you can put life into any of your images,
then bring them and show me.
What representation did Daniel have in the lion`'s den, or Jonah in the whale`'s belly?
They cried unto the Lord, and He delivered them.`"
The friar, who could not abide to hear her speak so much against idols,
said she talked like a mad woman, adding, "`I will give you over to the devil.`"
She not fearing this, said, "`Give what is your own;
I am the Lord`'s.`" He then stood up, and said,
"`I will do to you as the apostles did to Ananias and Sapphira.`"
She then standing up also, said, "`I deny you in the name of the Lord, the living God;
you have no power over me.`"
Then away he went with the hens to Sarah, telling her that Catharine was sick,
and the lord inquisitor had sent two hens,
and that Catharine would be glad to eat a piece if she would dress one of them presently,
and the other tomorrow.
Sarah, no less circumspect and cautious than Catharine,
and unwilling to receive this gift before she knew what might be expedient,
answered him accordingly as Catharine did.
Then, carrying the hens away again, the friar said, "`You would eagerly be burned,
because you desire to make the world believe that
you love God so well as to suffer in that way.`"
Catharine hearing this, said, "`I do not desire to be burned;
but if the Lord should call me to it,
I believe He will give me power to undergo it for His Truth.
And if every hair of my head was a body,
I could offer them all up for the testimony of Jesus.`"

The friar coming afterwards,
again asked Catharine whether she had not been inspired of the
Holy Spirit to be a Catholic since she had come into the inquisition.
She said, "`No;`" but he arguing to the contrary, said,
"`You are those who call the Spirit of God the Spirit of the devil.`"
"`No;`" they replied (who though they were separated, could hear one another),
"`the Spirit of the God in us resists the devil;
and the inspiration of the Holy Spirit is not wrought in the will of man,
nor in man`'s time; but in God`'s will and time.`"
More discourse they had about this matter, and then asking for their bibles,
which had been taken from them, he said they should never see them again,
for they were false.

Thus they were often troubled and pressed by the friars,
who generally came two at a time, though sometimes only one.
One of these often lifted up his hand to strike them, but did not;
for the women not being moved by fear, he was embarrassed,
and would say they were good women, and he would do them any good he could.
As indeed sometimes he did work for them, and would say it was for God`'s sake,
and that they ought to thank him for it; to which they replied,
"`Those that do anything for God, do not look for a reward from man.`"
This once made him so angry, that he said they were the worst of all creatures,
and that they would be treated worse than the Turks, Armenians, and Lutherans.
Whereupon one of them said, "`The pure life was ever counted the worst; and if we suffer,
we are the Lord`'s, and can trust Him.
Do what you will with us, we do not fear any evil tidings.
We are settled and grounded in Truth, and the more you persecute us,
the stronger we grow.`"
For this they experienced indeed, according to what they signified in their letters,
though they were separated a year from each other.

Once it happened that an Englishman who lived there,
having heard that Sarah was in a room with a window next to the street,
got up by the wall, and spoke a few words to her;
but he was violently hauled down and cast into prison to be tried for his life;
for he was one they had taken from the Turks, and had made a Papist of him.
The friars coming to them to know whether he had brought them any letters,
they said "`No.`" Nor had Catharine seen him;
yet it was told them that he was likely to be hanged.
Of this Sarah gave information to Catharine,
by writing a few lines to her (for it seems at this point they could not hear one another),
and she told her she thought the English friars were the chief actors in this business.
This grieved Catharine,
and she wrote to Sarah again (for they had a private way to send letters to each other).
In this letter, after her salutation,
she said to Sarah that she might be sure the friars were the chief actors,
but that she believed the Lord would preserve that poor Englishman for his love,
and that she was moved to seek the Lord for him with tears;
and that she desired her to send him something once a day if the keeper would carry it.
She also said that she had felt ravished with the love of God to her soul,
and her Beloved was "`the chiefest of ten thousands;`"
and that she did not fear the face of any man,
though she could feel their arrows.
Moreover, she signified that she had a prospect of their safe return into England.
And in the conclusion of this letter,
she bade Sarah take heed not to be tempted with money.

But this letter (by what means they never knew) came to the English friar`'s hands,
who translating it into Italian, delivered it to the lord inquisitor;
and afterwards came with the inquisitor`'s deputy to Catharine.
He showed her both the papers, and asked her if she could read the English one.
"`Yes,`" she said, "`I wrote it.`"
"`O, did you indeed?`"
he said.
"`And what is it you say of me here?`"
"`Nothing but what is true,`" she replied.
Then he said, "`Where is the paper Sarah sent?
Give it to me, or else I will search your trunk, and everywhere else.`"
She then bidding him to search wherever he desired, he said,
"`You must tell me who it was that brought you ink,
or else you shall presently be tied with chains.`"
She replied, she had done nothing but what was just and right in the sight of God;
and what she did suffer on that account would be for Truth`'s sake.
Then he said, "`For God`'s sake tell me what Sarah did write!`"
And she told him something of what she had written, and said what she spoke was truth.
"`But,`" he replied, "`you say it is likely we will tempt you with money.`"
And this indeed happened afterwards.
The deputy then took Catharine`'s ink and threw it away; and so they left also;
and the poor Englishman was released the next morning.
They now coming to Sarah, told her that Catharine honestly had confessed all,
and that it would be best for her to confess too.
They threatened her with a halter, and that they would take away her bed and trunk,
and her money too.
To this Sarah said,
"`It may be that I may not send to Catharine any more,`" but she
then asked the deputy whether he was a minister of Christ,
or a magistrate; for if he were a magistrate, he might take her money,
but she would not give it to him.
He then growing angry, said she was possessed; to which she replied, "`If so,
then it is with the power of an endless life.`"

Thus from time to time they suffered many assaults;
and sometimes it so happened that those who came to see them were struck to the heart,
which offended the friars.
Now at length their money was almost gone, they having sometimes used it for food.
But the friars told them they might have kept their money for other services;
for they would have maintained them while they kept them prisoners.
To this they said they could not keep their money and be chargeable to others.
Then it came to pass that their appetites were taken away,
and they ate but little for three or four weeks,
till at length they found themselves obliged to fast for several days together.
This made the friars say it was impossible for any
to live with as little food as they did.
And it was told them that the lord inquisitor had
said they might have any thing they desired.
To this they replied that it was not in their own will that they fasted,
but must wait to know the mind of the Lord, what He would have them do.
They continued weak, especially Sarah, who, apprehending her death to be near,
dressed herself as she would lie in the grave.
They both were so feeble that they could not put on their clothes, neither take them off,
being also unable to make their beds.
And though they desired to be together in one room, yet the friars would not permit it.
In this condition they concluded they were likely to die;
but heaven had provided otherwise.

Catharine about that time,
being exercised in supplication to the Lord that it might please Him to
put an end to their trial whichever way it seemed good in His sight,
thought she heard a voice saying, "`You shall not die.`"
She took this to be a heavenly voice,
and from that time they felt themselves refreshed with the living presence of the Lord,
to their great joy and comfort, so that they felt freedom to eat again.
They were then provided with good food,
but yet remained under a fear of eating anything which in
some respect might be counted unclean to them.
They therefore cried unto the Lord and said,
"`We would rather die than eat anything that is polluted and unclean.`"
And Catharine believed it was said to her from the Lord, "`You may as freely eat,
as if you had worked for it with your hands.`"
And Sarah, who sometimes worked for others in the inquisition house,
was persuaded that it was told her by inspiration,
"`You shall eat the fruit of your hands, and be blessed.`"
So they did eat, and for eight or ten days got whatever they did call for.

But sometime after this, they were so afflicted for lack of food,
that it did them more hurt than their fast.
Yet they being preserved alive, the friar said,
"`The Lord keeps them alive by His mighty power, because He desires them to be Papists.`"
To this they replied, "`It shall be known one day the Lord has another end in it.`"
But the friars told them plainly there was no redemption for them.
Whereupon they said,
"`With the Lord there is mercy and plenteous redemption;`" and they bade them take heed,
"`you be not found fighters against God.`"
To this the friars replied, "`You are foolish women.`"
"`Then we are,`" they replied "`the Lord`'s fools;
and such are dear and precious in His sight.`"
The friars then showing their shaven crowns, said that they were the Lord`'s fools;
and pointing to their gowns, said they did wear them for God`'s sake,
to be laughed at by the world.
One of the friars about this time did what he could to send Catharine to Rome;
and not succeeding, he said they would go both.
But this not taking effect,
the friar was sent there with a paper containing charges against Catharine;
but she speaking zealously to the scribe,
pronounced woe against what was contained in the letter,
and defied it in the name of the Lord.
Before the friar departed, he told Sarah that Catharine was a witch,
and that she knew what was done elsewhere.
He said this, because once telling Catharine an abundance of lies,
she told him she had a Witness for God in her that was faithful and true;
and she believed this Witness more than his words.

After he was gone,
the English consul came to her with a dollar from the master of a ship,
who came from Plymouth.
She told him she did receive her countryman`'s love, but could not receive his money.
He then asked her what she would do if she would take no money; to which she answered,
"`The Lord is my portion, and thus I cannot lack any good thing.
We were in your house near fifteen weeks,
did you see any cause for death or bonds in us?`"
And he saying "`No,`" she signified to him that in some
respect he had been an accessory to their imprisonment,
and had not been ignorant of their intent.
"`You knew,`" said she, "`that a room was provided for us in the inquisition;
and had we not been kept alive by the mighty power of God,
we would have been dead long ago.`"
Endeavoring to excuse himself, he said, "`How could I help it?`"
She then put him in mind of what happened at his house, when they were there,
and how they had called them to repentance and forewarned them.
To which he said, "`However it be, it will go well with you.`"
Then she reminded him how he had required a sign of her when they were at his house,
if they were the servants of the Lord God;
and she asked him whether it was not true what they had spoken to him:
"`You are a condemned person, and stand guilty before God.
Yet nevertheless repent, if you can find a place for it.`"
While she thus spoke to him, his lips quivered and he trembled,
so that he could scarcely stand upon his legs.
And though otherwise a very handsome man, and in his prime,
yet he now looked like one that was pining away.
This was a sufficient sign for the whole city, if they had duly taken notice of it.

Catharine having refused the piece of money, he went to Sarah with it.
She likewise told him she could not take it;
but if he had a letter for them she would be free to receive it.
He saying he had no letter, asked her what she needed; and she answered,
"`The Lord is my shepherd, I can lack no good thing; though I do long for my freedom.`"
He, not willing to discourage her, said, "`That you may have in time.`"
But he did not live to see it, for the next time they heard of him he was dead.

While the friar was gone to Rome, it was told them that they were also to be sent there;
and there was indeed a great stir about it;
but it seems they could not agree in the matter.
In the meantime, Catharine and Sarah remained separated,
and there were five doors between them with locks and bolts.
Nevertheless, Sarah sometimes found an opportunity,
either by the carelessness of the keeper, or that it was done on purpose,
to come where she could see Catharine; and though the friars did watch them,
yet she came often to Catharine`'s door by night.
But being once discovered, she was locked up again; yet not long after this,
the doors were once more left open, so that they sat in sight of each other.

Sometimes there were people of various nations brought prisoners into the inquisition,
and the friars, and other chief men, endeavored in their way to make Christians of them.
Then these women would often show the errors of popery, and declare the Truth,
for which they were willing to suffer death, if required.
But this was taken very ill.
At length it happened that two Englishmen came into the city,
and tried to obtain their liberty, but in vain.
Yet a little while after,
the magistrates sent for them and asked them whether they were sick;
or whether they lacked anything; saying they might write to England,
and ordering the scribe to give them ink and paper.

Not long after this came one Francis Steward, a captain of a ship,
and a friar of Ireland, who both took great pains to get them released;
and their friends in England had not failed to do
anything that might procure their liberty.
But the time for it had not yet come.
The said captain, and the new English consul, endeavored much to procure their liberty;
but it was not in the magistrates power,
for the inquisitor said he could not set them free without an order from the Pope.
Yet Catharine and Sarah were brought into the court chamber,
and the English consul asked them if they were willing to go back to England,
and they said, "`Yes, if it were the will of God they would.`"
The captain of the ship, who also was there, spoke to them with tears in his eyes,
and told them what he had done in their behalf, but in vain.
"`It is the inquisitor,`" said he, "`who will not let you go free;
for you have preached among these people.`"
To this they said, they had witnessed to the Truth,
which they were willing to seal with their blood.
He replied, if they could be set free,
he would freely give them their passage and provide for them.
And they replied that his love was well-accepted of the Lord.
He also offered them money, but they refused to take any.
Then they gave him a relation of their imprisonment and sufferings,
and said they could not change their convictions though they were to be burned to ashes,
or chopped in small pieces.
The friar then drawing near, said they did not work; but this was not true,
for they had work of their own, and did work as they were able.
They also told him their work and business was in England.
He confessing that this was true, said they had suffered long enough, and too long,
and that they should have their freedom within a short time,
but that there was needed an order from the Pope.
In the meantime it grieved the captain that he could not obtain their liberty;
and going away, he prayed God to comfort them.
The women besought the Lord to bless and preserve him unto everlasting life,
and never to let him go without a blessing from Him for his love;
for he ventured his own life in that place, laboring to get their freedom.

After he was gone, they met with worse treatment.
The inquisitor came and looked upon them with indignation,
for it seems the taking away of their lives was again on the table,
and their doors were shut up for many weeks.
After some time the inquisitor came again into the tower where they sat;
and Sarah called to him,
and requested the door might be opened for them to
go down into the court to wash their clothes.
He then ordered the door to be opened once a week,
and not long after this it was open every day.
And since it had been said that they could not be released without the Pope`'s leave,
Sarah said to him, "`If we are the Pope`'s prisoners, we appeal to the Pope.
Send us therefore to him.`"
But those that had their abode in the inquisition, especially the friars,
were their true mortal enemies,
although they would have sometimes fed them with the best of their provisions,
and given them whole bottles of wine, if they would have received them.
But this troubled them so greatly that they refused to eat and drink with them,
looking upon them as their fierce persecutors.

Once there came two or three English ships into the harbor,
and the English consul telling them of it, said that he had done what he could for them,
but the inquisition would not let them go unless they would turn Papists,
and therefore they must suffer still more imprisonment.
Before Sarah knew these ships had come there, she had seen them at night in a dream,
and heard a voice saying to her that they could not go yet.
When the ships had gone, the women were sent for,
and it was asked them if they would turn Papists.
To this they answered, "`We are true Christians, and have received the Spirit of Christ.`"
One of the magistrates showing them the cross,
they told him they did take up the cross of Christ daily,
which was the power of God to crucify sin and iniquity.
Knowing that there was one friar, who, as the captain had told them,
took a great deal of pains for them,
but not seeing him there (for he secretly favored them, but was now absent),
they said to those that were present,
"`One of your fathers has promised us our liberty.`"
But this availed nothing.
Yet they acknowledged this man`'s kindness,
and told him afterwards he would never have cause to regret it.

A friar once coming to them, said, "`It is God`'s will that you should be kept here,
or else we could not keep you.`"
In reply to this Catharine told him, "`The Lord allows wicked men to do wickedness,
but He does not will them to do it.
He allowed Herod to take off John the Baptist`'s head, but He did not will him to do it.
He allowed Stephen to be stoned, and Judas to betray Christ;
but He did not will them to do so.
For if He had willed it, He would not have condemned them for doing these things.`"
The friar hereupon asking, "`Are we then wicked men?`"
She answered, "`They are wicked men that work wickedness.`"
"`But,`" said he, "`you have not the true faith.`"
To which she answered, "`By faith we stand, and by the power of God we are upheld.
Do you think it is by our own power and holiness we are kept from a vain manner of life,
and from sin and wickedness?`"
He then saying that it was their pride, she told him, "`We can glory in the Lord,
for indeed, we were children of wrath once as well as others;
but the Lord has quickened us who were dead by the living Word of His grace,
and has washed, cleansed, and sanctified us in soul and spirit--in part,
according to our measures.
And we do press forward towards that which is perfect.`"
The friar then said, "`You are good women; but yet there is no redemption for you,
except you will be Papists.`"
At another time, the friars said to them, "`You may be Papists,
and keep your own religion too, and no one need know that you are Papists,
except when you are brought before a justice.`"
To this they replied, "`What, should we profess a Christ that we are be ashamed of?`"

Some of those that came to see them would pity them for not turning Papists;
but others showed their hatred by crying out that they must be burnt, and by bawling,
"`__Fuoco, fuoco__,`" (fire, fire.) While they were separated from each other,
Catharine was often much concerned for Sarah, and afraid that she would be ensnared;
for one of the friars many times accosted her with flattering words.
But they both continued steadfast,
and were often ravished by the inward joy and consolation they felt from the Lord.
Catharine in one of her letters said that the Spirit of prayer was once upon her,
but that she was afraid to speak to the Lord,
for fear she should speak one word that would not please Him.
And then it was returned from the Lord, "`Fear not, daughter of Zion; ask what you will,
and I will grant it, whatever your heart can wish.`"
But she desired nothing of the Lord but what would make for His glory,
whether it were her liberty, or bondage, life or death.
And in this resignation she found herself accepted of the Lord.

Sometimes they spoke so effectually to those that came to them,
that they could not dispute with them, but were made to confess that God was with them;
though others would make a hideous noise and cry, "`Jesu Maria,`" and run away,
as people that were struck with fear.
Catharine`'s prison being so near the street that
she could be heard by those that went by,
she was sometimes moved to call them to repentance and turn
them to the light wherewith they were enlightened,
which would lead them from of all their wicked ways and works to
serve the true and living God in spirit and in truth.
This so reached some, that they did sigh and groan, and stay to hear her;
but they could not stay long, it being strictly forbidden.
Yet some that passed by to their worship houses were so wicked,
that they threw stones at her window, and often made a sad noise and howled like dogs.
Thus they were assaulted both from without and from within by the friars,
who fiercely threatened them for their bold testimony against idolatry.
Once they showed Sarah the virgin Mary and her babe in a painting upon a wall,
and desired her look upon it.
But she, to show her zeal against idol-worship, stamped her foot and said,
"`Cursed are all images, and image-makers, and those that fall down to worship them.`"

It happened that some French and Spanish ships came to join with the cavaliers of Malta,
to fight against the Turks.
Sarah hearing this, said, "`God is angry.
Do not go forth to kill one another; Christ came not to destroy life, but to save it.`"
This she told many who were persuaded they would obtain a victory;
but it happened otherwise, for their fleet was beaten by the Turks,
and they returned with great damage.

A friar coming once to Catharine, asked her why she did not work;
which made her say to him, "`What work do you?`"
He answered, "`I write.`"
To which she replied, "`I will write too, if you will bring me pen, ink, and paper.`"
He not willing she should write, said, "`St. Paul worked when at Rome;
and by knitting you might get about three half-pence a day.`"
She told him, "`If we could have that privilege from you,
which Paul had at Rome under Caesar (who was a heathen prince),
we also would have worked, and not have been chargeable to any;
for he lived in his own hired house two years,
preaching the gospel and the doctrine of the Lord Jesus Christ.`"
She asked him also whether he knew the holy war of God?
"`And if you know it,`" said she,
"`then you must know how we cannot be without exercise day nor night.`"
This stopped his mouth;
besides it was well known that they did not spend their time idly;
for they knit stockings for those that were helpful to them.
They also made garments for the poor prisoners, and mended their clothes;
though they were not willing to work for the friars.
These men sometimes came to her, kneeled down,
and desired Catharine to repeat after them the words that they spoke.
But this she refused to do, though it made them grow more angry.
Such and the like occurrences so grieved her,
that once in anguish of spirit she cried out to God,
"`It would be better for me to die than to live like this!`"
For being almost continually constrained to testify against idolatry and superstition,
she would have willingly laid down her life for a testimony against it,
if it had been required of her.
And when once the friars told her that Sarah was to be carried to Rome,
while she should remain at Malta,
it so grieved her that with supplication she asked the Lord
if He did not count her worthy to go to Rome also,
and to offer up her life there for the testimony of Jesus.
For, if she was at liberty to choose,
she would rather do so than return without Sarah to England.

At another time, when it was told them that their bibles were false,
Catharine asked the friar that said so, "`In what way are they false?`"
He replied, because the books of the Maccabees were not in them.
To which she answered, that though something might be lacking,
yet the rest might still be good; but if something were added,
then the bible was corrupted.
This struck at some additions she had seen in the bibles there.
He then asked her whether she did not think that everyone must bow at the name of Jesus;
and she answering, "`Yes,`" he said,
"`Jesus!`" and bade her to kneel down or to bow herself.
To this she said that her whole heart and body were bowed down under the name of Jesus;
but that she would not bow at the will of man.
"`He that departs from iniquity,`" she thus continued, "`bows before the name of Jesus;
but they that live in sin and wickedness, do not bow before the Son of God.`"
Then the friar said that he and his companions stood in the same power,
and were led by the same Spirit as the apostles.
This made her ask why then they abused that power, and used carnal weapons?
He answered, they did not do so, for their inquisition,
and even their chains and fetters were spiritual.
Then he asked her whether she did not believe that
all were damned that were not of her persuasion?
She said, "`No, Christ has not taught us so;
for those that are today in a state of reprobation, the Lord, if it please Him,
can call them out of it tomorrow.`"
He then said, "`We think you are damned, and all those who are not of our belief.`"
To this she replied, "`The judgment of man does not hurt us.`"

Sometimes some came to the prison upon their saints`' days,
and asked the women if they knew what day it was;
and they not being acquainted with those saints would answer, "`We do not know.`"
When the others then told them that it was such or such a saint`'s day,
and that this saint would punish them that night because they did not observe his day,
they answered, "`We know the saints to be at peace with us,
and therefore we do not fear them.`"
Another time a friar came and told them that it was seventeen days until Christmas,
and that the Virgin Mary conceived that very day.
On hearing this, Catharine remarked that this was indeed very strange,
that she bore a child only seventeen days.
Such like occurrences grieved her exceedingly,
when she considered the gross darkness that these people were in.
And once,
as she was crying to the Lord in prayer that all their travail and labor seemed fruitless,
she felt this answer: "`Be not grieved, though Israel will not be gathered,
the seed of Malta is to increase into a multitude.
That which you have sown shall not die, but live.`"

After Catharine and Sarah had been imprisoned at Malta about three years,
there came one Daniel Baker, who did whatever he could to obtain their liberty,
and went also to the inquisitor; but all was in vain.
For it seems the inquisitor required that some English merchants at Leghorn or Messina,
should be bound for four thousand dollars, assuring that, if they were released,
they should never return into those parts.
But they were unwilling to enter into those terms,
not knowing what the Lord one time or another might require of them.
Daniel, seeing he could not obtain their deliverance this way,
offered himself to be imprisoned instead of them; and this not being accepted,
he went yet further,
and signified that he was willing to lay down his life for their liberty,
if it could not be purchased otherwise.
Great love indeed, of which but few instances are to be found!
The women hearing of this, were touched with exceedingly great admiration.
In the meantime, Daniel Baker found a way to get some letters delivered to them,
and wrote also himself, both to comfort and exhort them to steadfastness.
At length he also found a means to speak to them; for once,
as they stood at the prison gates,
he came in their sight and saluted them with these words:
"`The whole body of God`'s elect, dearly beloved, acknowledge your testimony,
and you are a sweet savor unto the Lord and His people.`"
To which one of them answered,
that it was a trouble to them that they could not be more serviceable.
This made his heart melt with pity and compassion,
considering the wonderful mercy of the Lord in preserving
them without fainting in that sharp trial;
and they, seeing one another at a distance through the iron grates,
were mutually refreshed at that season.
They afterwards wrote to him, and signified with the most tender expressions,
how highly they valued his great love;
and also sent him letters for their friends and relations in England;
and he failed not to write back to them during his stay,
which was in the forepart of the year 1662.
Nevertheless, he was forced to leave them prisoners there;
but the time of their redemption drew near,
which was brought about at the solicitation of George Fox and Gilbert Latey,
by writing to the lord Aubigny, as has been said already.

Some time before Daniel Baker came to Malta,
it had been told them that if they would turn Catholics, they might dwell at Malta.
To this their answer was, that they were true Catholics.^
footnote:[The word "`catholic`" means universal or general,
and was originally used to refer to the universal or world-wide church of Christ.
Over centuries, the term slowly became synonymous with the Church of Rome (or Popery).]
One of the magistrates said, that if they would not turn Catholics,
they must yet suffer long imprisonment by the Pope`'s order
(yet it was not true that there was such an order).
It was also told them, if they would kiss the cross, they would be released;
and then they might stay at the house of the English consul
until an opportunity offered to carry them to England.
In the meantime they heard that the Pope had given order
to let them pass to England without doing them any harm.
But whatever the case, they were preserved well-contented,
and they said resolutely that they would not kiss the cross,
nor purchase their liberty at that price.
It seems the consul aimed at some monetary advantage by their release;
for he told them that the inquisitor had said,
if anyone would offer sureties of three or four thousand
dollars to be paid if ever they came there again,
they would be set at liberty.
This he said also to Daniel Baker, and added,
that if none would bind themselves as surety, they must die in prison,
and that this was the Pope`'s order.
After Baker`'s departure,
word was sent to some English merchants concerning such an engagement,
but none appeared willing to enter into it.
And the prisoners were so far from desiring it, that they spoke against the idea.
Yet there were many who sought to obtain their liberty,
showing themselves willing to engage for what was reasonable;
but all these endeavors were in vain.

Once they fasted three days, and though it was the cold season,
yet they sat upon the ground, with very little clothes, without stockings or shoes,
and having nothing upon their heads but ashes.
The inquisitors seeing it, wondered exceedingly;
and Sarah began to speak zealously against superstition and idolatry.
And when the time of their fast had expired, Catharine composed the following:

[.letter-heading]
A Hymn to God

[verse]
____
All praise to Him that hath not put
Nor cast me out of mind,
Nor yet His mercy from me shut,
As I could ever find.

Infinite glory, laud, and praise
Be given to His name,
Who hath made known in these our days
His strength and noble fame.

Oh none is like unto the Lamb!
Whose beauty shines bright,
O glorify His holy name,
His majesty and might.

My soul praise Thou the only God,
A fountain pure and clear,
Whose crystal streams spread all abroad
And cleans far and near.

The well-springs of eternity,
Which are so pure and sweet,
And do arise continually,
My bridegroom for to meet.

My sweet and dear beloved one,
Whose voice is more to me
Than all the glory of the earth,
Or treasures I can see.

He is the glory of my life,
My joy and my delight;
Within the bosom of His love
He closed me day and night.

He doth preserve me clean and pure
Within his pavilion,
Where I with Him should be secure,
And saved from all wrong.

My soul praise Thou the Lord, I say,
Praise Him with joy and peace;
My spirit and mind both night and day
Praise Him and never cease.

O magnify His majesty,
His fame and His renown,
Whose dwelling is in Zion high,
The glory of His crown.

O praises, praises to our God,
Sing praises to our King;
O teach the people all abroad,
His praises for to sing.

A Zion song of glory bright,
That doth shine out so clear;
O manifest it in the sight
Of nations far and near;

That God may have His glory due,
His honor and His fame;
And all His saints may sing anew
The praises of His name.
____

After Catharine had thus joyfully sung, she went to the well in the court,
and drank much water in the sight of the prisoners, as did Sarah also;
for they were very dry.
And Sarah, washing her head also in cold water, they cried out in their language,
"`You will kill yourselves, and go to the devil!`"
But this they did not fear, nor did they catch any cold,
and so they became a wonder to others.

About half a year after Daniel Baker was gone, it came into Catharine`'s heart,
that if she could speak with the inquisitor, he would grant them their liberty,
and it was not long after this that he came to the inquisition court chamber.
The women hearing that he had come, requested to speak with him, which was granted,
and being admitted into his presence,
they told him they had not wronged or defrauded any,
but had suffered innocently almost four years for conscience-sake, etc.
After this the inquisitor was very courteous to them,
and promised their liberty in a few days,
saying he would send for the consul and get him to engage for five
hundred dollars to be paid for them if ever they came again.
And in case the consul denied this, he would send to Rome to the Pope,
requesting permission to set them at liberty without any obligation.

Not many days after this the inquisitor came with his lieutenant, the chancellor,
and others, and after some discourse,
asked them whether they were willing to return back again to their husbands and children,
if it were the will of God.
To this they answered that it was their intent in the will of God to do so.
Hereupon they were released, and the inquisitor took his leave very courteously of them,
and wished them a prosperous return to their own country;
so likewise did the magistrates and the inferior officers,
not requiring one penny for fees or attendance;
yet in their own freedom they gave something to the keeper and some poor men.

Being thus set at liberty,
they kneeled down and prayed God never to lay to
their charge what they had done unto them,
because they knew them not.
And then they were delivered into the consul`'s hands,
who told them that he had engaged for them to get their freedom;
but they could never discover that this was true.
Now they were kept eleven weeks at the consul`'s house before
they could get a passage from there to England.
Catharine in the meantime,
being under a great concern because of a judgment
that she felt was impending over the city,
wrote a paper to the rulers of Malta, in which she said,
that on the 25th of the month called August,
it came upon her from the Lord to write thus to them in His name:

[.embedded-content-document.paper]
--

My wrath is kindled against you, and My judgment is set up among you,
because of your hard-heartedness and unbelief.
I the Lord, who desires the death of no man, but that all should return unto Me and live,
have cast My servants among you, contrary to their will, and without their knowledge,
to go and forewarn you of the evil that was coming upon you.
For all the wicked shall be brought to judgment.
Indeed, I will establish my beloved Son upon His throne,
and He shall rule in His princely power, and reign in His kingly majesty,
whose right it is over all;
and His own spiritual government shall He set up in all places,
righteous rule and pure worship in Spirit and in Truth.
There is nothing that can hinder the Lord.
If you will not hear My servants who speak My words,
whom you proved these almost four years, whose lives have been harmless and spotless,
in pure innocency among you, then I will bring woe upon woe,
and judgment upon judgment upon you, till the living shall not be able to bury the dead.
My mouth has spoken it, and My zeal will perform it;
and every man`'s hand shall be upon his loins for pain;
for the day of recompense has come.
But if you will hear My servants which speak in My name,
and return in your minds to the light in your consciences, which convinces of all evil,
and deny all evil thoughts, words, and actions, then will I pour out My Spirit upon you,
and will soon cure you of your diseases, and heal you of your pains.

--

This and more she wrote,
and delivered it to the consul to give to the grand master and the rest of the governors;
but the consul not being pleased with it, threatened her with imprisonment again.
What further became of the paper I do not find.
But on the 8th of October, there was great thunder and lightning,
which set on fire and blew up one of the powder-houses about a mile out of the city,
and another powder-house was thrown down; and in the city, five houses were overthrown,
most of the glass windows of the palaces and other houses broken,
the doors lifted off their hooks, the walls torn, and the whole city terribly shaken,
so that at midnight, a cry went through the whole city and the bells were rung.
At the foot of the bed where Catharine and Sarah lay,
was a glass window which also was broken, but they received no hurt,
though the house was so shaken that they did exceedingly fear and quake;
but being given up unto the Lord to live or die,
their fear was soon taken from them and turned into joy in the Lord.
When it was day the consul came to them, and they being still and quiet,
he asked whether they were not dead.
And while he was speaking, others came in telling what had happened in the city;
and he told them that even the ships in the harbor had suffered damage.
Then the women said, "`One woe is past, and behold another woe comes quickly,
if you do not repent.`"

Some days after this Sarah fasted, sitting upon the ground with ashes upon her head,
her neck and shoulders bare;
and she spoke to the consul to request the grand master to proclaim a fast,
and to make the people meet together to wait upon the Lord,
with their minds turned to Him, so that He might turn away His judgments from them;
for the hour of His judgments had come,
wherein the painted harlot should be stripped naked,
and receive a cup of trembling from the hand of the Lord.
The consul delivered this message to the magistrates,
and the friars said the women had good intentions.
Sometime after this the inquisitor came, and talking with them, said,
"`Your intent is good, but the devil has deceived you.`"
They asked him whether the devil could give power over sin; to which he said,
the devil could transform himself into an image of light.
This they assented to, but said he could not hide himself from the children of light,
though they who were in the dark could not discern him.
The inquisitor could not abide to hear this, but went away; and the consul,
who was present, worked against them to get them into bondage again, but in vain.
Many then died in the town of a violent fever;
but whether any other disaster followed upon their prediction, I cannot tell.^
footnote:[It is interesting to note, that shortly after this time,
Malta suffered the worst plague epidemic in the island`'s history.
In December of 1675,
there was an outbreak of bubonic plague that continued until
August 1676 and resulted in approximately 11,300 deaths,
around one-sixth of the island`'s population.
Most deaths were in the urban areas, including the capital Valletta and the Three Cities,
// lint-disable invalid-characters `%`
which had a mortality rate of about 41%. Bartholomeo dal Pozzo (1637-1722),
a well-known contemporary historian of the Order of St John,
began his description of this outbreak by asserting that "`Divine
vengeance ordained the punishment of plague for our sins.`"]

At length there came one of the king of England`'s frigates called the Sapphire,
commanded by captain Samuel Titswel, who took Sarah and Catharine in,
together with some knights of Malta.
Among them also was the inquisitor`'s brother,
who often spoke to the captain that the women should
not lack anything that was on the ship,
and he told them that if they came again to Malta, they would not be so persecuted.
And to the captain he said, "`If these women go to heaven one way, and we another,
yet we shall all meet together at last.`"
But they told him that Jesus Christ, the light of the world,
was the only way to the Father.

Departing from Malta, after some time they came to Leghorn,
where the merchants showed them great kindness,
and sent wine and other things for their refreshment, offering them also money;
but they were unwilling to accept it.
From there they came to Tangier,
which the king of England had acquired in his marriage
with the daughter of the king of Portugal.
This place was at that time besieged by the Moors,
yet Catharine and Sarah entered the town,
and many came flocking into the house where they were lodged,
for they boldly exhorted the people to depart from wickedness.
They also went to the governor,
who was courteous to them and took their admonition kindly,
and promised to follow their counsel.
He would have given them money, but they took none, though they accepted his love;
for he commanded that none of the garrison should abuse them either in word or deed,
upon pain of severe punishment;
yet it seemed that the Portuguese and Irish were ready enough to have done them mischief.
They being inclined to go out and speak to the Moors,
requested the governor to let them go forth,
but he told them they must expect nothing but cruel death from that savage people,
or bonds forever.
And though they signified to him that they believed the Lord would preserve them,
since they were persuaded that He required of them to go to the Moors,
yet the governor in a friendly manner withheld them from going.
Being thus stopped, they believed that the Lord accepted their willingness,
and when they went aboard again (though in another ship)
several took shipping with them from a belief that,
on their account, they would have a safe passage.
The captain and others that were in the ship behaved
themselves very civilly towards them;
and though they met with tempests, yet at length they arrived safe in England.

Catharine afterwards related, that when in the inquisition,
she was for many days together in expectation that they would be burned at the stake.
At this time she saw in a dream in the night, a large room,
and a great wood fire in the chimney,
and she beheld one sitting in the chair by the fire, in the form of a servant,
whom she took to be the Eternal Son of God.
She likewise saw a very amiable well-favored man-child,
sitting in a hollow chair directly over the fire (not appearing
to be above three-quarters of a year old,
and having no clothes on but a little fine linen about the
upper parts) and the fire flamed about him;
yet the child played, and was merry.
She then desired to pick up the child, for fear it would be burned;
but He that sat in the chair bid her let it alone.
Then turning around she saw an angel,
and at last He who sat in the chair bid her pick up the child, which she did,
and found it had received no harm.
Upon awaking, she told her dream to Sarah,
and desired her not to fear since the heavenly host thus followed them.

I have collected this relation of the occurrences
of these women at Malta from several papers and letters,
which not long after their return home were published in print.
And since no due order was observed in their publication,
and many things were mentioned which, to avoid prolixity I have passed by,
I may have unintentionally missed in some case or
other as to the order or series of time;
but yet I think the matters of fact are not distorted.
Now to give the reader an idea of the frame of these women`'s minds,
and their sufferings, I will insert some of their own letters.
Among those which they wrote to their friends in England was this following:

[.embedded-content-document.letter]
--

O dearly beloved friends, fathers, elders, and pillars of God`'s spiritual house,
and brethren and sisters in the Lord Jesus Christ,
in the measure of love and life of our God, do we salute you all,
and do embrace you in that which is eternal,
and we do greatly rejoice and glorify the name of our heavenly Father,
that He has counted us worthy to be partakers of the death
and sufferings of His blessed Son with you.

Though we are the least of God`'s flock,
yet we are of the true fold whereof Christ Jesus is shepherd;
and He has had as tender a care over us,
as He has had of over all of the lambs which He has
called forth in this day of His power.
He has carried us through and over great afflictions,
as with many others of our brethren and sufferers for His name, both in mockings,
scoffings, scornings, reproaches, stripes, contradictions, perils at land, perils at sea,
fiery trials, cruel threatenings, grief of heart, sorrow of soul, heats and colds,
fastings, and watchings, fears within, and fightings without,
terrible temptations and persecutions, dreadful imprisonments and buffetings of Satan.
Yet in all these trials, the Lord was very gracious unto us,
and did not absent Himself from us, neither permitted His faithfulness to fail us,
but did bear us up and keep us from fainting in the midst of our extremity.
We had not another unto whom to make our cry, but the Lord alone;
neither could we expect a drop of mercy, favor, or refreshment,
except what He did distill from His living presence and work by His own strength.
For we sat one in one room, and the other in another nearly a year, as owls in deserts,
and as people forsaken in solitary places.
But then did we enjoy the presence of the Lord,
and did behold the brightness of His glory, and we did see you, our dear friends,
in the light of Jesus,
and did behold your order and steadfastness of your faith and love to all saints,
and were refreshed in all the faithful-hearted,
and felt the issues of love and life which did stream from
the hearts of those that were wholly joined to the fountain,
and were made sensible of the benefit of your prayers.

O the sorrows, the mournings, the tears we have known.
"`But those that sow in tears, shall reap in joy.`"
A true sorrow begets a true joy; and a true cross brings a true crown.
For when our sorrows did abound, the love of God did abound much more;
the deeper the sorrows, the greater the joys; the greater the cross,
the weightier the crown.

Dear friends and brethren, marvel not that Israel is not gathered;
our judgment remains with the Lord, and so do our labors.
It was not for lack of travail, nor pain, nor love to their souls;
for truly we could have been contented to have fed upon the grass on the ground,
that we might have had our freedom to speak among them.
For, had it not been for the great opposition,
they would have followed after us as chicks after a hen, both great and small.
But oh, the swelling seas, the raging and foaming waves, stormy winds and floods,
the deep waters, high mountains and hills, hard rocks, rough ways, crooked paths,
tall cedars, strong oaks, fruitless trees,
and corrupted ones that encumber the ground and hinder the righteous Seed to be sown,
and the noble plants from being planted.
Oh, they shut up the kingdom against the simple-hearted,
and hide the key of knowledge from the innocent ones,
and will not enter into the kingdom themselves, nor allow those that desire to enter!
Instead, they stir up the magistrates to form carnal weapons,
thinking to prevent the Lord from receiving His inheritance,
and to dispossess the Son who is heir of all,
that He might not have a dwelling-place among them, nor a habitation near them.
But His light will discover their darkness,
and His brightness will burn up all their abominations, and mar their beauty,
and stain their glory, their pomp, and their pride,
that it may perish as the untimely figs, and fall as the flower of the field,
and wither as the grass upon the house-top.
Oh, the belly of hell, the jaws of Satan,
the whole mystery of iniquity is at a great height,
and all manner of abominations that make desolate stand where they ought not,
which are upheld by a law that upon pain of death none must speak against it,
nor walk contrary to it.

But praises to our God, He carried us forth to declare against it daily.
Oh, the blind guides, the seducing spirits that do cause the people to err,
and compel them to worship the beast and his image,
and have his mark in their foreheads and in their hands,
and bow to pictures and painted walls, and to worship the works of their own hands,
and to fall down before that which their own fingers have fashioned,
and will not allow them to look towards Zion upon pain of death,
nor walk towards Jerusalem upon pain of faggot and fire, but must abide in Babel,
and believe whatever they speak or declare to be truth.
But oh, the ways, the worships, the fashions, forms, customs, traditions, observations,
and imaginations, which they have drawn in by their dark divinations,
to keep the poor people in blindness and ignorance,
so that they perish for lack of knowledge,
and are corrupted because the way of Truth is not made known among them.
They are all in the many ways, and out of the one true living way.
Indeed, their ways are so many and so monstrous, that they are unspeakable.
But the Lord our God has kindled a fire in the midst of them that will consume all forms,
fashions, customs, and traditions of men, and will burn up the briers, thorns, tares,
stubble, fruitless trees, and corrupted ones.
He will blast all the fruits, works, and labors of wicked and ungodly men,
with the mildew of His wrathful indignation,
and will scatter all His enemies with the whirlwinds of His displeasure.

--

This letter was signed by both of them, though perhaps Catharine was the writer,
who also wrote a letter of exhortation to the popish inquisitor at Malta,
and another to friar Malachy.
Among the letters she wrote to her husband and children,
I count the following really worthy to be delivered to posterity:

[.embedded-content-document.letter]
--

For the hands of John Evans, my right dear and precious husband,
with my tender-hearted children,
who are more dear and precious to me than the apple of my eye.

Most dear and faithful husband, friend, and brother, begotten of my eternal Father,
of the immortal Seed of the covenant of light, life, and blessedness,
I have unity and fellowship with you day and night,
to my great refreshment and continual comfort.
Praises, praises be given to our God forevermore,
who has joined us together in that which neither sea nor land can separate or divide.

My dear heart, my soul does dearly salute you, with my dear and precious children,
who are dear and precious in the light of the Lord, to your endless joy,
and my everlasting comfort.
Glory be to our Lord God eternally, who has called you with a holy calling,
and has caused His beauty to shine upon you in this the day of His power,
wherein He is making up His jewels,
and binding up His faithful ones in the bond of everlasting love and salvation,
among whom He has numbered you of His own free grace.
In this, I beseech you dear hearts, in the fear of the Lord,
to abide in your measures according to the manifestation
of the revelation of the Son of God in you.
Keep a diligent watch over every thought, word, and action,
and let your minds be stayed continually in the light,
where you will find out the snares and baits of Satan, and be preserved out of his traps,
nets, and pits, that you may not be captivated by him at his will.
Oh, my dear husband and children,
how often have I poured out my soul to the everlasting Father for you,
with rivers of tears night and day,
that you might be kept pure and single in the sight of our God,
improving your talents as wise virgins, having oil in your vessels,
with your lamps burning, and clothed with the long white robe of righteousness,
ready to enter the bed-chamber, and to sup with the Lamb,
and to feed at the feast of fat things where your souls may be nourished, refreshed,
comforted, and satisfied, never to hunger again.

My dear hearts, you do not lack teaching; you are in a land of blessedness,
which flows with milk and honey among the faithful stewards,
whose mouths are open wide to righteousness,
to declare the eternal mysteries of the everlasting kingdom,
and of the endless joys and eternal glory,
whereunto all the willing and obedient shall enter and be blessed forever.

My dear hearts, the promises of the Lord are large,
and are all "`Yes`" and "`Amen`" to those that fear His name.
He will comfort the mourners in Zion,
and will cause the heavy-hearted in Jerusalem to rejoice because of the glad tidings.
They that bear the cross with patience, shall wear the crown with joy;
for it is through long-suffering and patient waiting that
the crown of life and immortality comes to be obtained.
The Lord has exercised my patience, and tried me to the uttermost, to His praise,
and my eternal comfort,
who has not failed to provide everything for us in His own due time.
Indeed, we are witnesses that He can provide a table in the wilderness,
both spiritual and temporal.
Oh, the endless love of our God,
who is an everlasting fountain of all living refreshment,
whose crystal streams never cease running to every thirsty
soul that breathes after the springs of life and salvation!

In our deepest affliction, when I looked for every breath to be my last,
I could yet not wish that I had not come over the sea,
because I knew it was my eternal Father`'s will to prove me,
together with my dear and faithful friend.
In all afflictions and miseries the Lord remembered mercy,
and did not leave nor forsake us, nor allow His faithfulness to fail us,
but caused the sweet drops of His mercy to distill upon us,
and the brightness of His glorious countenance to shine into our hearts,
and failed not to grant us revelations and visions.
Oh, how may I set forth the fullness of God`'s love to our souls?
No tongue can express it, no heart can conceive it, nor can a mind comprehend it.
Oh, the ravishments, the raptures,
the glorious bright shining countenance of our Lord God,
who is our fullness in emptiness, our strength in weakness, our health in sickness,
our life in death, our joy in sorrow, our peace in disquietness, our praise in heaviness,
our power in all needs or necessities.
He alone is a full God unto us, and to all that can trust Him.
He has emptied and purged us of ourselves,
and has wholly built us upon a sure foundation, the rock of ages, Jesus Christ,
the Light of the World, where no swelling seas, nor raging, foaming waves,
stormy winds (though they beat vehemently) are able to move us.
Glory, honor, and praise to our God forever, who, out of His everlasting treasures,
does fill us with His eternal riches day by day.
He nourishes our souls with the choicest of His mercies,
and feeds our bodies with His good creation,
and relieves all our necessities in a full measure.
Praises, praises be to Him alone, who is our everlasting portion,
our confidence and our rejoicing, whom we serve acceptably with reverence and godly fear;
for our God is a consuming fire.

Oh, my dear husband and precious children,
you may feel issues of love and life which stream forth as a river to every one of you,
from a heart that is wholly joined to the fountain.
My prayers are for you day and night without ceasing,
beseeching the Lord God of power to pour down His tender mercies upon you,
to keep you in His pure fear, to increase your faith,
to confirm you in all righteousness,
and to strengthen you in believing in the name of the Lord God Almighty,
that you may be established as Mount Zion, which can never be moved.
Keep your souls unspotted from the world,
and love one another with a pure heart fervently.
Serve one another in love, build up one another in that which is Eternal,
and bear one another`'s burdens for the Seed`'s sake, and so fulfill the law of God.
This is the word of the Lord unto you, my dearly beloved.

Dear hearts, I do commit you into the hands of the Almighty, who dwells on high,
and to the Word of His grace in you,
who is able to build you up to everlasting life and eternal salvation.
By me, who am your dear and precious wife, and spouse, in the marriage of the Lamb,
in the bed undefiled,

[.signed-section-signature]
C+++.+++ E.

[.postscript]
====

My dearly beloved yokemate in the work of our God does dearly salute you.
Salute us dearly to our precious friends in all places.
I do believe we shall see your faces again with joy.

====

[.signed-section-context-close]
Written in the Inquisition at Malta, in the 11th month, in the year 1661.

--

[.offset]
The following letter was written by Sarah to her husband, Henry Cheevers, and children.

[.embedded-content-document.letter]
--

My dear husband, my love, my life is given up to serve the living God,
and to obey His pure call in the measure of the manifestation of His love, light, life,
and Spirit of Christ Jesus, His only begotten Son,
whom He has manifested in me and thousands more by the brightness of His appearing,
in order to put an end to sin and Satan, and bring immortality to light,
through the preaching of the everlasting gospel, by the Spirit of prophesy,
which is poured out upon the sons and daughters of the living God,
according to His purpose; whereof He has chosen me, who am the least of all.
But God, who is rich in mercy, for His own name-sake has passed by my offenses,
and has counted me worthy to bear testimony to His holy name,
before the mighty men of the earth.
Oh the love of the Lord to my soul!
My tongue cannot express,
neither has it entered into the heart of man to conceive of the
things that God has laid up for them that fear Him.

Therefore my soul does breathe to my God for you and my children, night and day,
that your minds may be joined to the light of the Lord Jesus,
to lead you out of Satan`'s kingdom, into the kingdom of God,
where we may enjoy one another in the life eternal,
where neither sea nor land can separate us.
In this light and life I do salute you, my dear husband, with my children,
wishing you to embrace God`'s love, in making His truth so clearly manifest among you;
whereof I am a witness,
even of the everlasting fountain that has been opened by
the messengers of Christ who preach to you the word of God,
in season and out of season, directing you where you may find your Savior,
to purge and cleanse you from your sins, and to reconcile you to His Father,
and to have unity with Him and all the saints in the light,
that you may be fellow-citizens in the kingdom of glory, rest, and peace,
which Christ has purchased for them that love Him, and obey him.
What profit is there for to gain the whole world, and lose your own souls?
Seek first the kingdom of God and the righteousness thereof,
and all other things shall be added to you.
Godliness is great gain, having the promise of this life that now is,
and that which is to come; which is fulfilled to me,
who have tasted of the Lord`'s endless love and mercies to my soul.

And from a moving of the same love and life do I breathe to you my dear husband,
with my children.
My dear love salutes you all; my prayers to my God are for you all,
that your minds may be joined to the light with which you are enlightened,
that I may enjoy you in that which is eternal, and have communion with you in the Spirit.
"`He that is joined to the Lord, is one spirit,`" one heart, one mind, one soul,
to serve the Lord with one consent.
I cannot by pen or paper set forth the large love of God
in fulfilling His gracious promises to me in the wilderness,
being put into prison for God`'s truth, there to remain all the days of my life,
being searched, tried, examined upon pain of death,
among the enemies of God and His Truth; standing in jeopardy for my life,
until the Lord subdued and brought them under by His mighty power,
and made them to feed us, and would have given us money or clothes;
but the Lord did deck our table richly in the wilderness.
The day of the Lord is appearing in which He will discover every deed of darkness,
regardless how secretly it be done;
for the light of Christ Jesus will make it manifest in every conscience.
Indeed, the Lord will rip up all coverings that are not of His own Spirit.
The God of peace be with you all. Amen.

[.signed-section-closing]
Written in the Inquisition prison by,

[.signed-section-signature]
Sarah Cheevers.

--

Several other letters both she and Catharine wrote to their husbands and relations.
But since a great part of my narrative was gathered from there, I pass them by.
But by these inserted, one may see that they were not women of a dull temper,
but intelligent and cheerful.

[.offset]
In a letter of Sarah`'s to her friends in Ireland, I find these words:

[.embedded-content-document.letter]
--

My life is given up to the service of the Lord.
Bonds, chains, bolts, irons, double doors, death itself,
is too little for the testimony of Jesus, and for the Word of God.
Thus may the seed be gathered, it is but a reasonable sacrifice.
Bonds and afflictions become the gospel of Christ.
Those that will live godly in Christ Jesus, must suffer persecution.

--

[.offset]
And in a letter to Daniel Baker, Catharine said,

[.embedded-content-document.letter]
--

The time is too short for me to disclose the twentieth part of the terrible trials;
but whenever we were brought upon any trial, the Lord did take away all fear from us,
and multiplied our strength,
and gave us power and boldness to plead for the Truth of the Lord Jesus,
and wisdom of words to stop the mouths of the gainsayers.
But then they would say, "`You have not the true faith, but you have all virtues.`"
Dearly beloved, pray for us, that we fall not, nor fail,
whereby our enemies may have any advantage to rejoice and say,
we served a God that could not serve us, and called upon a God that could not deliver us;
as if we were like them, to call upon stones, pictures,
painted walls and dead things that cannot hear, see, or speak.
We do beseech you to tell all our dear friends, fathers, and elders,
the pillars of our spiritual building, with all the rest of our Christian brethren,
that we do desire their prayers, for we have need of them.

--

[.offset]
This letter they concluded with the following poem:

[verse]
____
How strong and powerful is our King
To all that do believe in Him!
He doth preserve them from the snare,
And teeth of those that would them tear.

We that are sufferers for the Seed,
Our hearts are wounded, and do bleed
To see the oppression, cruelty,
Of men that do thy Truth deny.

In prisons strong, and dungeons deep,
To God alone we cry and weep:
Our sorrows none can learn nor read,
But those that in our path do tread.

But He whose beauty shines bright,
Who turns darkness into light,
Makes cedars bow, and oaks to bend,
To Him that`'s sent to the same end.

He is a fountain pure and clear,
His crystal streams run far and near,
To cleanse all those that come to Him,
For to be healed of their sin.

All them that patiently abide,
And never swerve nor go aside.
The Lord will free them out of all,
Bondage, captivity, and thrall.
____

They composed several others, which fell into the hands of their enemies,
and copies of them were given to the inquisitor.
But now I leave them.
