== Chapter XII

[.section-date]
1662--1664

Before I return to transactions in England,
I shall relate a remarkable case of Daniel Baker,
who having come to Smyrna with an intent to travel from there to Constantinople,
was stopped by the English consul and sent to the Isle of Zante,
where a ship lay bound for Venice, in which he embarked.
Having come into that city, he stayed there a week, and went from there to Leghorn,
with an intent to take shipping there for England.
But during his stay in that place, he inwardly felt drawings towards Malta,
to see whether he could be helpful to Catharine and Sarah who were prisoners there,
having several times felt stirred up thereto.
And though the difficulty of the matter had kept him back,
yet he now could not find peace in his mind before he had given himself up to that service.
So he embarked in a French ship for Sicily, and coming to Syracuse,
he stayed there five days, and then set sail for Malta.
Having arrived, he got admittance to speak to the Pope`'s inquisitor,
to whom he spoke in the Italian tongue in this way:
"`I have come to demand the just liberty of my innocent friends,
the English women in prison in the inquisition.`"
The inquisitor asked him if he were related to them as husband or kinsman,
and whether he came out of England on purpose with that message.
To this Daniel answered that he had come from Leghorn for that purpose.
But the inquisitor told him that they must abide in prison till they died,
unless some English merchants, or others that were able,
would engage for the value of three or four thousand dollars
that they should never return into those parts.
His request being thus denied,
he went to the English consul and spoke with him and several others.
But all his endeavors proved vain; and he himself was threatened with the inquisition.
Moreover, the Pope`'s deputy desired to have him bound,
that he would neither speak good nor evil to any body while he was on the island,
except to him and the English consul.

After a stay here of three weeks, he passed again to Italy,
and from there took shipping for England.
But having come into the Straits of Gibraltar,
he saw that the high mountain there was the same
place he had seen the foregoing year in a dream,
when prisoner in Worcester jail in England.
Here the ship wherein he was, along with several other vessels,
lay about a month because of the contrary wind, so that they could not set sail.
In the meantime, being under a burden, he perceived there was a service for him on shore.
But considering this to be dangerous, he wished to have been excused from it;
but felt no peace until he had fully gave up,
regardless whether bonds or death might ensue.
While the fleet lay here wind-bound, several ships attempted to pass through,
but could not; and a similar temptation attended him as that of Jonah, that is,
to flee from the place and so to escape the burden of the Lord under which he labored.
But he found (as he afterwards signified in a printed
account) that obedience was his duty,
though it was required of him to be a sign against the idolatry of the church of Rome.
He then told the master of the ship in which he was a passenger, something of the matter,
and said that he believed that God would soon give opportunity
for the fleet to pass away after his service was performed.
The master was hard to be persuaded to put him ashore,
yet at length he allowed it upon the day they used to call Maundy Thursday.

Having come on shore, he went to the town, and then into the mass-house,
where he found the priest at the high altar upon his knees, in his white surplice,
adoring the host.
After viewing this idolatry for some time,
he felt the indignation of God kindled in his heart against it,
and turning his back upon the priest and his dead god,
he set his face towards the people and saw the multitude
upon their knees also "`worshipping they knew not what.`"^
footnote:[John 4:22]
In this posture, spreading forth his arms,
he slipped off his upper garment and rent it from top to bottom in several pieces,
which he cast from him with indignation.
Then he took his hat from his head, as being the uppermost covering of man,
and casting it down, stamped upon it with his feet.
Then appearing in a sackcloth covering, he with a loud voice,
thrice called out for repentance,
and said that the life of Christ and of His saints was not to be found in the host,
but had risen from the dead.
And so he passed away undisturbed,
sounding the same message with repentance through the streets,
till he came to the sea-side, where he kneeled down to pray,
and gave thanks to the Lord for His wonderful preservation,
having allowed no man to touch or do him any harm.
Being on shore, he also delivered a paper, written in the Spanish tongue,
to the governor and inhabitants of Gibraltar, along with some books in Latin.
That to the governor was as follows:

[.embedded-content-document.paper]
--

Behold, behold, the great day of God, and of His wrath, and of the wrath of His Lamb,
has come.
The hour of His judgment has come.
Wherefore, O inhabitants of the earth, repent, repent, repent! "`Fear God,
and give glory and honor to him that made heaven and earth and the fountains of waters.`"^
footnote:[Revelation 14:7]
Woe, woe, woe to the inhabitants of the earth.
"`John heard another voice from heaven saying, '`Come out of her my people,
that you partake not of her sins, and that you receive not of her plagues.`'`"^
footnote:[Revelation 18:4]
These are the words of the power of Christ, which is contrary to the false church.
Behold, behold, plagues, plagues, plagues are coming upon the church of Rome,
and upon her heads in all parts of the world.

--

Daniel having now come again on board the ship,
the next day the Lord gave them a rear wind, and all the fleet set sail;
and after some time he arrived safe in England.
But having come to London,
it was not long before he who had travelled without hurt in foreign parts,
was imprisoned by his own countrymen, as will be related hereafter.
And being shut up in prison, he wrote a narrative of his travels,
from which I have taken my relation.

About this time John Stubbs returned into England,
having been in the dominion of the great Turk.
But I do not find that he met with any remarkable occurrences,
except that he had spread some books.
He and Alexander Parker coming to London found G. Fox there,
with whom they travelled towards Bristol.
By the way they had several meetings, and having come to Bristol,
they understood that the officers were likely to come and disturb the meeting.
On the First day of the week they went a meeting, and A. Parker stood up first to preach;
but while he was speaking, the officers came and took him away.
Then G. Fox stood up and preached undisturbed, so that the meeting ended peaceably.
Then he, staying in town that week, visited his friends, and was visited by them.
The next First-day some of his friends came to him,
and endeavored to persuade him not to go to the meeting that day; "`For,`" said they,
"`the magistrates have threatened to take you away, and in order to do so,
they have brought a trained company.`"
G+++.+++ Fox desired them to go their way to the meeting,
without telling them what he intended to do.
Yet not long after this he went there too; but being met by some of his friends,
they did what they could to stop him, saying, "`What,
will you go into the mouth of the beast?`"
"`Will you go into the mouth of the dragon?`"
said another.
But G. Fox would not allow himself to be thus prevented, but went on.
Having come, he perceived a concern and fear upon his friends for him,
but his preaching there was so powerful, that all fear departed from them;
and having concluded his sermon with a prayer, he stood up again and told the auditory,
"`Now you may see there is a God in Israel that can deliver.`"
For the officers and soldiers had gone and broken up another meeting,
which had taken up their time; and they were in a great rage that they had missed G. Fox;
for it had been resolved upon to persecute the Quakers, and,
if possible to root them out.

G+++.+++ Fox, after having tarried yet some days at Bristol,
went through Wiltshire and Berkshire, back again to London;
yet he did not stay long there, but travelled towards Leicestershire,
and passing by Barnet Hills, he found there one captain Brown, a Baptist,
whose wife belonged to the society of those called Quakers.
This captain, for fear his wife would go to meetings and be cast into prison,
had left his house at Barrow, and taken a place in Barnet Hills,
thinking himself more safe there.
G+++.+++ Fox going to see the wife, and having come into the house, asked him how he did.
"`How I do?`"
said he, "`the plagues and vengeance of God are upon me, for I am a fugitive, a Cain!
God must look in vain to me, and such as me, to be a witness for Him;
for if all men were no more faithful than I,
then God would have no witness left in the earth.`"
In this condition Brown lived there on bread and water, and thought it too good for him.
But at length he returned with his wife to his own house at Barrow,
where he came to be convinced of the Truth professed by those called Quakers,
and died in it.
And a little before his death,
he said that though he had not borne a testimony for Truth during his life,
he would bear a testimony in his death;
desiring to be buried in his orchard in a plain way.

But I return to G. Fox, who having come into Leicestershire, went to Swanington,
to the house of a widow woman.
There one called the lord Beaumont, and a company of soldiers,
came to him at night and took him out of the hall where he was,
and brought him to the said lord, who asked him his name.
To this he answered, "`My name is George Fox, and I am well known by that name.`"
"`Aye,`" said Beaumont, "`you are known all the world over.`"
Then he put his hands into George`'s pockets to search them,
and pulled out his comb-case,
and afterwards commanded one of the officers to search for letters.
This made G. Fox say that he was no letter carrier,
and he asked him why he came among a peaceable people with swords and pistols,
but without a constable, since this was contrary to the king`'s proclamation;
nor could it be said that there was a meeting,
for G. Fox had only been talking in the hall with the widow woman and her daughter.
Beaumont sending then for the constables,
gave them charge to watch G. Fox and some that were with him that night.
Accordingly the constables set a watch upon them,
and next morning brought them to Beaumont`'s house,
who then told them they met together contrary to the act;
for not long before this time the parliament, by instigation of the clergy,
had made an act against conventicles,^
footnote:[i.e. an unlawful religious gathering.]
stating that if any were convicted of having been at a conventicle,
they should incur a fine not exceeding five pounds,
or imprisonment not above three months.
Upon G. Fox saying to the lord Beaumont that he did not find them in a meeting,
and so there was no transgression of the said act,
Beaumont asked him whether he would take the oaths of allegiance and supremacy.
To this G. Fox answered,
"`I never took any oath in all my life;`" and then requested him to show him the oath,
that they might see whether it was not made for the uncovering of popish recusants.
But Beaumont being unwilling,
caused a court order to be made which mentioned that Fox and his friends were intending
to have a meeting--a cunning artifice indeed to trouble an innocent people.
And with this court order he charged the constables to convey them to Leicester jail.

The constable who was charged to bring G. Fox and
his friends to prison was unwilling to do it himself,
and being harvest time, it was hard to get anybody to go with them.
He therefore desired that the court order be given to them,
to carry it themselves to the jailer.
This they refused to do, though sometimes some of their friends had done so;
for the constables had such experience of their fidelity,
that they dared trust them even in such a case, without fearing they would try to escape.
So the constable hired a poor man, who was reluctant to go with them on this errand.
Yet they rode with him through the country, being five in number,
and some carried their bibles open in their hands,
and passing through towns they told people they were
the prisoners of the Lord Jesus Christ,
going to suffer bonds for His name`'s sake.
Having come to Leicester, and going into an inn,
the master of the house seemed somewhat troubled that they should go to prison;
but they being unwilling to consult with lawyers (to which
they were advised) allowed themselves to be taken to prison.
Having come there,
G+++.+++ Fox asked whether the jailer or his wife was the master of the jail,
and it was told him, "`The wife.`"
This woman, though lame, and not able to move about without crutches,
yet would beat her husband when he came within her
reach if he did not do as she desired him.

G+++.+++ Fox perceiving from this that without her permission
he would not be able to make an agreement with her husband,
got somebody to bargain with her for a room for him and his friends,
and to leave it to them to give her what they would; to which she consented.
But then it was told the prisoners that the jailer would not permit
them to bring any drink from the town into the prison,
but must drink only the beer that they bought from him,
and which (as was easily to be guessed) would be at a very high rate.

This made G. Fox say he could remedy this;
for since the jailer could not deny them water, he would get a pail of water once a day,
and put some wormwood into it,^
footnote:[Wormwood was thought to purify unclean water from toxins and parasites.]
and that might serve for them.
So long as G. Fox was in prison there,
he and his friends had a meeting every First-day of the week in the yard,
to which came not only the debtors and felons who were prisoners,
but also several people out of the town and country;
whereby many were convinced of the truth he preached,
and continued faithful witnesses for it.

While G. Fox was confined there, several more of his friends were sent to prison,
to the number of about twenty.
And when the court sessions came they were brought before
the justices and tendered the oaths of allegiance and supremacy;
for this was the common snare used against this people,
when no other thing could be found to lay to their charge.
But G. Fox told them he never took an oath in his life; "`And,`" he said,
"`you know we cannot swear because Christ and His apostles forbade it;
and therefore this is but a snare to us.
However, if you can prove that after Christ and His apostles forbade swearing,
they then did command Christians to swear, then we will take these oaths.
Otherwise we are resolved to obey Christ`'s command, and the apostle`'s exhortation.`"
To this it was asserted that they must take the oath
in order to manifest their allegiance to the king.
G+++.+++ Fox, to show that he was not unfaithful to the king,
told them that he had formerly been taken prisoner by colonel Hacker,
and taken from that town to London,
under pretense that he held meetings to plot for bringing in king Charles.
Then he requested that their court order might be read,
which showed the cause of their commitment to be their intention to have a meeting.
And he said further that the lord Beaumont could not send them to jail by this act,
unless they had actually been taken at a meeting;
and therefore he urged the reading of the court order,
that it might be seen how wrongfully they were imprisoned.
But whatever he said, they would not take notice of the court order, but called a jury,
and indicted the prisoners by refusing to take the oaths of allegiance and supremacy.

While the prisoners stood waiting in the court,
a pickpocket had put his hand into the pockets of some of them,
which they told the justices of, and showed them the man.
They then called him up, and upon examination he could not deny what he had done;
yet they let him go free, as if the robbing of those called Quakers was no crime.

It was not long before the jury returned, and brought in the prisoners a guilty verdict.
The justices then whispered together,
and bade the jailer to take the prisoners and carry them back to jail.
But a little after they were in prison again, the jailer came to them and said,
"`Gentlemen, it is the court`'s pleasure that you should all be set at liberty,`" etc.
Thus they were suddenly released, which was indeed remarkable,
because the jury had brought them in guilty,
and a sentence was supposed to have followed.
But G. Fox`'s liberty seems to have been owing to the following cause:
he had received a letter from the lord Hastings, who having heard of his imprisonment,
had written from London to the justices of the sessions to set him at liberty.
This letter he had not as yet shown to the justices,
though it seems that they had received some knowledge
of the lord Hastings`' mind from another hand,
which made them resolve on this sudden discharge.
G+++.+++ Fox now being free, carried this letter to the lord Beaumont,
who having opened and read it, seemed somewhat troubled;
and yet threatened him that if he had any more meetings at Swanington,
he would disperse them and send him to prison again.
But notwithstanding these threats,
he and his friends went to Swanington and had a meeting there without being disturbed.
From there he travelled to London, where we will leave him,
and in the meantime see what happened elsewhere.

Some time before this,
Thomas Goodair and Benjamin Staples were imprisoned at Oxford,
and being brought into the court of judicature before Sir William Walter,
who sat there as judge, and Goodair being examined and nothing found against him,
the oath of allegiance was tendered,
to which he answered that he acknowledged the king
as supreme ruler in civil temporal matters,
and that he was willing to obey him in all just commands.
"`But,`" said he, "`if king Charles and those who are in authority under him,
enjoin me to do anything contrary to the command of Christ,
then I must obey Christ rather than king Charles, or those in authority under him.
It is for conscience-sake that I cannot swear,
though I could gain the whole world thereby; for Christ has forbidden it,
saying '`Swear not at all;`' and James says,
'`Above all things swear not.`'`" But whatever Goodair said was in vain,
for they demanded that he swear.
He continuing to refuse swearing,
justice Walter asked those that were with him on the bench whether
they had anything to say against his passing sentence against them.
These all having said no, he spoke thus to Goodair: "`Hearken to your sentence.
You are out of the king`'s protection.
All of your lands, real estate,
and personal possessions are forfeited and shall be seized for the king`'s use;
and you are to remain prisoner during the king`'s pleasure.`"
Then he bid the jailer to take Goodair away,
who asked whether the jailer had been commanded to chain him,
for he had been chained as thieves and felons before he had been brought into the court.
Whereupon the judge answered, "`The jailer may do with you what he will;
for you are now out of the king`'s protection.`"
Then he was led away, and Benjamin Staples was brought to the bar,
to whom the oath being also tendered; and he refusing to take it,
the same sentence was passed upon him.
Both men having returned to prison,
the jailer then said to the other prisoners that were there for evildoing or debts,
"`If you need coats, you may take those of the Quakers,
for they are now out of the protection of the law.`"
But one of these prisoners was so honest as to say he would
rather go naked than to take away those men`'s coats.
How long they were in prison, and whether they died there, or were at length released,
I know not.^
footnote:[According to John Witing`'s account,
both of these men were discharged at the next "`general jail delivery.`"
Thomas Goodair was later imprisoned for some years at Warwick,
having been premunired without legal trial or judgment.
At length he died at Selby in Yorkshire, in 1693.]

But now I return to Ambrose Rigge, who having come to Hurst Pier-point in Sussex,
had a meeting there at the house of his father-in-law, captain Thomas Luxford.
This so displeased the priest Leonard Letchford,
that Rigge was taken and brought before the justices, Walter Burril, Nisel Rivers,
and Richard Bridger, who being of a mind to bring him under sufferings,
tendered him the oath of allegiance.
He saying that for conscience-sake he could not swear,
was sent directly to Horsham prison,
and at the time of the court session was brought into the court,
where judge Samuel Brown passed the sentence of premunire upon him.
Then he was carried back, and by the instigation of the said Leonard Letchford,
committed close prisoner, where he remained above ten years,
and suffered during that time much hardship by the malice of the jailers,
since such prisoners as he were shut out of the king`'s protection.
In the meantime the aforesaid priest Letchford summoned Rigge`'s wife for tithes,
and she refusing payment, was also imprisoned at the prosecution of this priest.
The priest then seized her goods,
taking away also that which her husband had earned in prison by his hard labor,
not leaving him and his wife a bed to lie on.
Indeed, he also took away a pot they had borrowed from other prisoners to boil food in,
and boasted that he had bound Rigge so securely,
that it was not in the king`'s power to release him.
But notwithstanding this wicked boast, yet to his great disquiet and vexation,
he lived to see Rigge released by the king under the great seal.
Thomas Luxford, Ambrose Rigge`'s father-in-law,
having also become one of the society of those called Quakers,
upon refusing to pay him tithes, felt likewise the effects of Letchford`'s fury;
for he caused him also to be cast into jail, where he kept him six years.
And after these prisoners were at length released by the sheriff,
T+++.+++ Luxford was then excommunicated by Letchford,
and afterwards sued under the statute de __excommunicato capiendo__,^
footnote:[The Statute __de excommunicato capiendo__ was a writ in old English law,
ordering the imprisonment of an excommunicated person
until he or she submitted to the national church.]
whereby he was shut up again in prison,
until eventually set at liberty by an act of parliament.

Not long after this,
Letchford got a warrant to sue also some others of
the Quakers (so called) belonging to his parish,
for not paying tithes.
But before he could get them imprisoned it happened that,
having at night gone to bed healthy, in the morning he was found stiff dead in his bed,
according to the testimony of his neighbors;
and this prevented the stroke he had leveled against the others.

Not being willing to finish this relation abruptly, I have advanced in time,
but now I return to the year 1662.
In the middle of this year, Sir Henry Vane and John Lambert,
both vigorous champions against king Charles the First,
and having been in great authority under the former government,
were brought to their trial.
Vane behaved himself with very great presence of mind.
How far he was guilty I am not to inquire; but he was declared guilty,
and afterwards beheaded on Tower-Hill.
He was reputed to be a man of great knowledge,
having been one of the chief members of the long parliament,
and also an opposer of Cromwell; for he was an entire republican,
and had a great share in the administration of state affairs.
Lambert, who had been an eminent general, saved his life; for since Vane, as Ludlow says,
pleaded for the lives and liberties of his country, and Lambert for his own,
he evaded the storm which took away Vane.
Lambert now, though condemned to death, begged for mercy,
and was confined to perpetual imprisonment, and carried to a small isle near Plymouth^
footnote:[Drake`'s Island]
where he finished his days.

Now upon the insurrection of the Fifth-monarchy-men,
occasion was taken to make an act against plotting and seditious meetings,
and so the persecution against the Quakers increased.
And under a pretense that their meetings were dangerous,
and a terror to the king`'s subjects,
a further act was made against those who refused to take an oath:

[.embedded-content-document.legal]
--

[.blurb]
=== An act for preventing mischief and danger that may arise by certain persons called Quakers, and others refusing to take lawful oaths.

Whereas of late times, certain persons under the name of Quakers,
and other names of separation,
have taken up and maintained sundry dangerous opinions and tenets, and among others,
that the taking of an oath, in any case whatsoever, even before a lawful magistrate,
is altogether unlawful and contrary to the word of God;
and because the said persons do daily refuse to take an oath, though lawfully tendered,
whereby it often happens that the truth is wholly suppressed
and the administration of justice much obstructed;
and whereas the said persons, under a pretense of religious worship,
do often assemble themselves in great numbers in several parts of this
realm to the great endangering of the public peace and safety,
and to the terror of the people,
by maintaining a secret and strict correspondence among themselves,
and in the meantime separating and dividing themselves
from the rest of his majesty`'s good and loyal subjects,
and from the public congregations, and usual places of divine worship, therefore:

For the redressing and better preventing the many forms of mischief
and danger that do and may arise by such dangerous tenets,
and such unlawful assemblies, (1) It is enacted by the king`'s most excellent majesty,
by and with the advice and consent of the spiritual and temporal lords,
and by authority of the parliament, that if any person or persons,
who maintain that the taking of an oath in any case
whatsoever (although before a lawful magistrate),
is altogether unlawful and contrary to the word of God,
from and after the 24th of March in this present year of our Lord 1661,
shall willfully and obstinately refuse to take an oath that is lawfully tendered,
(2) or shall endeavor to persuade any other person,
to whom any such oath shall be duly and lawfully tendered,
to refuse and forbear the taking of the same, (3) or shall by printing, writing,
or otherwise go about to maintain and defend that the taking
of an oath in any case whatsoever is altogether unlawful;
(4) and if the said persons, commonly called Quakers,
shall at any time after the 24th day of March,
depart from the places of their habitations,
and assemble themselves to the number of five or more,
of the age of sixteen years or upwards, at any one time, in any place,
under pretense of joining in a religious worship,
not authorized by the laws of this realm, (5) that then, in such a case,
the party so offending, being lawfully convicted thereof by verdict of twelve men,
or by his own confession, or by the notorious evidence of the fact,
shall lose and forfeit to the king`'s majesty, for the first offense,
such a sum as shall be imposed upon him or her, not exceeding five pounds.

(6) And if any person or persons, being once convicted of any such offense,
shall again offend therein and be lawfully convicted, he shall, for the second offense,
forfeit to the king such a sum as shall be imposed upon him or her,
not exceeding ten pounds;
(7) with the said penalties to be levied by seizure of property,
and sale of the party`'s goods so convicted.
(8) And for lack of such a seizure,
or non-payment of the said penalty within one week after conviction,
then the said convicted parties shall, for the first offense,
be committed to the common jail or house of correction, for the space of three months;
and for the second offense six months, without bail or main-prize,
there to be kept to hard labor.
(9) And if any person, after he has been twice convicted of any the said offenses,
shall offend the third time, and be lawfully convicted thereof,
then every person so offending shall, for his or her third offense, abjure the realm,
or be transported in any ship or ships,
to any of his majesty`'s plantations beyond the seas, etc.

--

This act caused Edward Burrough to write a small book,
called, [.book-title]#The Case of the People called Quakers#, Stated,
to Show the Falsehood of the Accusations Charged upon Them.
First he showed in this treatise that,
even if it were supposed that the Quakers were heretics
and erroneous people (which has never been proved),
yet we find no examples in Scripture that such should be imprisoned,
or afflicted with bodily punishments.
And having treated of this matter at length,
he laid down the state of their way of meeting and worship,
appealing to others on this account, with these words:

[quote]
____
What judgment do our neighbors give in this case?
Concerning our meetings,
they say they have known us to meet together in such a manner for many years,
in towns and villages, and have never seen or known any harm or injury therein,
nor were any harmed in either their persons or estates by our meetings.
The very witness of God in all our neighbors does testify and give judgment,
that our meetings have always been peaceable and quiet,
and that we come together in peace and good order, and we part in the same,
and no person has ever been harmed by our meetings.
Inquire of the neighborhoods,
and they will tell you they believe in their consciences that our meetings are for good,
and have good effects, and are not evil, nor bring forth any evil to any.

And as for the manner of our meeting and sitting together, it is orderly, decent,
and of good report among men.
And as for any doctrine that ever was held or heard by any among us,
none can truly accuse it of being either error, heresy, or sedition; but on the contrary,
they know that it witnesses against all sin and iniquity,
and tends to the turning of people from ungodliness
and unrighteousness to truth and holiness.
Indeed, many can declare that this is effected by the doctrine preached in our meetings;
and our neighbors can witness that we part from our meetings in peace and good order,
and at a respectable time; and they can tell you that they are not terrified,
nor the peace of the land disturbed by our meetings,
which are held in the fear of God and to the glory of His name,
being according to the law of God, the gospel, and the primitive Christian example.

We are accused as heinous offenders,
and imprisoned because it is supposed we do not submit
to obey the known laws of the land,
but rather break them, and will not conform to the national church, pay tithes,
take oaths, though we know the laws of the land command these things.

But to this, I say: First, as to submitting to all known laws of the land;
this is known to God and our neighbors, that our principle and practice is,
and has ever been, to submit to every government, and to submit to all laws of men,
either by doing or by suffering,
as at this day we resist not the greatest of afflictions
and tribulations that can be imposed on us.
And this is well known to our neighbors and all people,
that we are submissive to all laws of men, by patient suffering without resistance.
For whenever a law requires anything of us which we cannot perform for conscience-sake,
we fulfill that law by patient suffering, resisting no man,
nor rendering evil for evil to any.
And the judgment of the Scriptures, according to both law and gospel,
and the precedents of saints, do justify us in this case,
in our choosing patiently to suffer the greatest
penalties of the law rather than to obey,
(by __doing__) any such law as requires things contrary to our pure consciences.
And this is according to the example of the three young men in Daniel 3,
who were commanded to fall down and worship the golden
image when they heard the sound of the music,
upon the penalty of being cast into the midst of the fiery furnace;
which commandment they could not obey, nor could they fall down to worship the image,
but rather chose to suffer the penalty of being cast into the midst of the fire,
which accordingly was done to them.
Again in the case of Daniel, chapter 6,
who was commanded to make no petition to any god or man for thirty days,
except to king Darius,
upon the penalty and affliction of being cast into the lion`'s den.
But Daniel chose rather to suffer this penalty than to obey the commandment,
and so was cast into the lion`'s den.
By these examples of holy men, with many more that might be given out of the Scriptures,
it is evident that righteous men will rather choose to suffer than
to obey any law of man that is contrary to their consciences.
So the law of God, the example of saints,
and the Holy Scriptures give judgment for us in this case,
in our choosing rather to suffer than to obey laws contrary to our consciences.
And these consequently also do condemn such as persecute and imprison us,
because they require obedience of us in things that are against our consciences.

Secondly: Though we disobey some laws,
and cannot actively obey every law of man when it requires
and commands things contrary to a good conscience,
yet herein are we also justified by the law of God, the example of saints,
and the Holy Scriptures, and they give judgment in our favor,
and consequently against our enemies in this case.
This is particularly evident in the two examples before-mentioned in Daniel,
where the three young men were expressly commanded
to fall down and worship the golden image,
and where Daniel was also required by the king`'s decree not to pray to any God or man,
save to king Darius.
Yet all these holy men of God did absolutely disobey
the law and decree so requiring them,
and acted contrary to the commandment.
Also the apostles of our Lord Jesus Christ (Acts.
4:18) were commanded to preach no more in the name of Jesus;
but they disobeyed their commandment and went on
preaching in the Spirit and power of Christ,
contrary to the commandment of the rulers,
and appealing to them "`that they ought to obey God rather than man.`"^
footnote:[Acts 5:29]
Many examples we might collect out of the Scriptures where the
servants of God did disobey the commands of kings and rulers,
and could not obey (by __doing__) any command contrary to God,
but rather chose to suffer afflictions and even death itself,
rather than to obey such laws and decrees as required anything contrary to a pure conscience.
And this is our case at this day.
We cannot obey (by __doing__) anything against our consciences,
but must break the laws of men and disobey their commandments,
rather than break the law of God and sin against our own consciences,
whatever we suffer for it;
and the examples of saints and Scriptures justify us in this regard.

Therefore,
let our enemies cease to cry out that we are "`rebellious and disobedient to laws and
government;`" for we are not such as willfully and obstinately disobey any laws of men,
but only for conscience-sake, and that we may not sin against God,
nor offend His witness in us.
It is for this reason we cannot obey laws contrary to our consciences,
whatever we suffer (which sufferings we resist not,
nor do we rebel against any in this case).
Our principles and practices are to obey every law and government,
either by doing or by suffering.
And though we disobey such laws as are not according to the law of God,
and rather do choose to suffer, yet herein we are justified by the law of God,
and the Holy Scriptures.

Thirdly: And as for our conduct among men,
in respect to our daily walking and converse with them in our dealing,
that it is in all honesty and faithfulness, truth and justness in our works and words,
our neighbors shall witness for us.
We will not justify ourselves herein; it is God that justifies us, and the law of God,
the gospel of Christ, the Scriptures, the example of holy men, our neighbors,
and the witness of God in all men`'s consciences shall bear witness unto our conduct.
O Lord God everlasting, may You be the judge of our cause.
Make manifest to all the world, in Your due season, that we are your people,
and that we love You above all, that we fear Your name more than all,
that we love righteousness and hate iniquity,
and that we now suffer for Your holy name and truth, for Your honor and justice,
and for Your truth and holiness.
O Lord, you know we are resolved to perish, rather than to offend You in the least thing.

Let our accusations and answers be truly considered and weighed
in the balance of justice and truth in every man`'s conscience.
And let all the world judge in this case: Do we deserve to be ruined, destroyed,
imprisoned, banished, and devoured of wild beasts, as our enemies threaten to do?
Are we heretics?
Are we seditious?
Are we drunkards?
Are we double-dealers?
Are we such as the law of God condemns?
What evil have we done in the land?
Do we hurt anybody?
Are we not innocent before the Lord and men?
We appeal to the just Witness of God and men.
Let it be answered; and though no man will hear and consider our cause this day,
yet the Lord will plead our cause in His time and season,
and make the world to know that we are His people.
In the meantime we are willing to suffer the reproaches of ungodly men,
till the Lord works deliverance in the earth.

But now it may be objected by the magistrates and rulers,
that you now have a law against us, and that we must suffer the penalty of it,
for you cannot help but put the law into execution, according to your oaths and offices;
and that it is not you that persecute us,
but it is the law of the land by which we now suffer,
and that you cannot be blamed for our suffering because you only execute the law, etc.
This is the reasoning of some at this day.

To all of which I answer: It is true there is a law now enacted against us,
which is said to be the ground of our suffering.
And whether this law is in itself just or unjust, I shall not now demonstrate,
but shall leave it to the judgment of all Christian men that know us, our principles,
doctrines, ways, and conduct;
and let them judge whether we deserve the penalties and punishments therein
described for any of the principles or practices that we hold or maintain.
But though there is a law against us,
yet the magistrates who are the executors of it may
execute the same with moderation or with violence;
with discretion or with excessive rigor;
and it will be well for all to use moderation and discretion in this case,
and thereby save themselves from the weight of anger and indignation which
will come upon all violent-doers who seek to destroy the innocent,
and rejoice when an occasion is administered.

And though this law is enacted against such meetings as are "`dangerous to the
public peace,`" and "`a terror to the people,`" yet our meetings are not such,
and therefore this law may not justly extend in its
execution to the breaking up of our meetings,
which are for the worship of God,
and are peaceable and of good report among all good men;
and are not for the disturbance of the peace, nor the terror of the people.

And though this law is pretended against us,
in order to banish us and rid the land of us,
must it necessarily be executed to its height, without limitation or restriction?
Must this law be executed more than some others laws that are as truly enacted,
and as fully in force as this act can be?
For indeed there are some laws which deserve greater execution than this,
and yet they lie dormant, as is apparent at this day.
As, for example, is the case with __4 Jac. c. 5__, in which are found these words:

[.small-break]
'''

"`Let it be enacted, that all and every person or persons who shall be drunk,
and of this offense of drunkenness shall be lawfully convicted,
shall for every such offense forfeit and lose five shillings,
to be paid to the hands of the church-wardens of that parish where the offense is committed,
who shall be accountable therefor, to use for the poor of the same parish.
And if the said person or persons so convicted shall
refuse or neglect to pay the said fine,
then the same shall be levied from his goods by warrant of precept from the court, judge,
or justices, before whom he was convicted.
And if the offender is not able to pay the sum of five shillings,
then he shall be committed to the stocks for the space of six hours.`"

[.offset]
Also in __1 Jac. c. 7__, are found these words:

"`That all persons going about begging; all idle persons going about in any country,
either begging or using any subtle craft, or unlawful games or plays,
or pretending that they can tell fortunes, or such other like fantastical imaginations;
and all fencers, bear-baiters,^
footnote:[Those who trained and pitted bears against
dogs for the entertainment of the public.]
and common minstrels who go wandering abroad, shall be taken, adjudged,
and deemed as rogues, vagabonds, and beggars,
and shall suffer such pains and punishments as are expressed in __39 Eliz. c. 4.__ namely,
that every such person shall be stripped naked from the middle upwards,
and shall be openly whipped, until his or her body be bloody,`" etc.

[.small-break]
'''

Read this statute at length, and then consider how duly it is executed now,
and why the late act against us is more rigorously enforced upon honest, sober persons,
who are of good conduct.
For many of these are hauled out of their meetings
where they have met together only to worship God,
and for no other end.
And many are sent to prison, and persecuted to the very height of the said act,
whereas idle persons following unlawful games and plays, bear-baiters,
and minstrels of various kinds, do wander up and down city and country;
and yet such persons and things, though appearing publicly, are yet permitted,
and little or no notice is taken of them by some of the magistrates,
so as to punish them for the breach of law.

Seeing then that this law against us is put into
execution far more than these other laws,
it therefore appears that there is more envy against us and our
peaceable religious meetings than there is against profaneness,
wickedness, drunkenness, stage-playing, and such like things.
And such magistrates, wherever they are,
are not excusable in the sight of God when they prosecute a law against us,
but do nothing to enforce other good laws against profane and ungodly persons and practices.
And therefore,
these are also compelled to acknowledge that it is
not only because there is a law against us,
but it is also, or rather, because there is enmity, and wrath,
and wickedness in the hearts of men against us,
which is the main cause of our sufferings at this day.
____

Thus was E. Burrough always laborious,
and like a faithful and diligent minister of Christ,
he was so totally devoted to the service of God and the church,
both in preaching and writing in the defense of the gospel,
that he scarce reserved any time for himself.
He seldom took rest,
but continued to work incessantly till the time of his departure drew near;
plainly manifesting that it really was his food and
drink to do the will of his heavenly Father;
and this he endeavored unweariedly to the end of his days.

Now I turn again to New England, where though the murdering part was acted to the full,
yet their blood-thirstiness was not quenched,
as may appear from the following relation I shall
give of the cruel whippings inflicted on some.
If I should relate all of that kind that happened in New England,
it would make up a pretty big volume by itself;
and therefore I will mention only a few instances only.

Among these, I meet with Josiah Southick, (whose father and mother,
Lawrence and Cassandra,
had been among the first that were banished from Boston because of their religion,
as has been said before;
and whose brother and sister had been ordered to be sold for bond-slaves).
This young man, having been in Old England,
in time found himself obliged to return to Boston, notwithstanding their severe laws.
For this he was sentenced to be whipped behind a cart, first at Boston,
and then at Roxbury and Dedham, when with out-stretched arms,
he said to those who sentenced him, "`Here is my body;
if you need a further testimony of the Truth I profess; take it, and tear it to pieces;
it is freely given up.
And as for your sentence, it matters not to me;`" adding further,
"`it is no more terrifying unto me than if you had taken a feather,
blown it into the air, and said,
'`take care it does not hurt you.`' For surely tongue cannot express
or declare the goodness and love of God to His suffering people.`"
Then he was stripped and tied to the back of a cart in Boston,
where the hangman scourged him with as much vehemency as he could.
It is remarkable that the whip used for these cruel executions was not of whip of cords,
like those used in England, but of dried intestines,
and every string had three knots at the end, which, being fastened to a stick,
the hangman often laid the blows with both his hands, causing violent injury to the body.
But all this cruelty was not able to make Josiah faint;
for as he was led through the streets of Boston at the cart`'s tail, he sang aloud,
and was heard to utter these words: "`They that know God to be their strength,
cannot fear what man can do.`"
The same day he was whipped also at Roxbury, and the next morning, it being very cold,
he was discharged and sent out into the wilderness;
for so inhuman were these furious New England professors,
that they seemed to think that nothing could be done amiss to the Quakers.
Indeed, it has happened that, being locked up with thieves,
and endeavoring to turn them from their wicked lives,
they have been ill-treated on that account,
and the thieves set at liberty lest they should turn Quakers.

At Dover, in New England, Anne Coleman, Mary Tomkins,
and Alice Ambrose were sentenced to very cruel whipping, for only having come there.
The warrant was as follows:

[.embedded-content-document.legal]
--

To the constables of Dover, Hampton, Salisbury, Newbury, Rowley, Ipswich, Wenham, Lynn,
Boston, Roxbury, Dedham.
Until these vagabond Quakers are carried out of this jurisdiction:

You and every one of you, are required in the king`'s majesty`'s name,
to take these vagabond Quakers, Anne Coleman, Mary Tomkins, and Alice Ambrose,
and bind them fast to the end of a cart,
and while driving the cart through your several towns,
to whip them upon their naked backs,
not exceeding ten stripes apiece on each of them in each town;
and thus to convey them from constable to constable until they are out of this jurisdiction,
as you will answer this at your peril.
This shall serve as your warrant.

[.signed-section-signature]
Richard Waldron.

[.signed-section-context-close]
At Dover, dated December 22, 1662.

--

Cruel indeed was this order;
because to whip these three tender women through all eleven towns,
with ten stripes apiece at each place, through a length of near eighty miles,
in bitter cold weather, would have been enough to have beaten their bones bare,
and their lives out of their bodies.

Now it happened that upon a very cold day, the deputy Walden, at Dover,
caused these women to be stripped naked from the middle upward, and tied to a cart.
He then whipped them while the priest looked on and laughed;
which some of their friends seeing, and taking notice of Walden`'s cruelty,
testified against him; for which Walden put two of them in the stocks.

The women being thus whipped at Dover, were carried to Hampton,
and there delivered to the constable, William Fifield, who, the next morning,
desired to have whipped them before it was daylight; but the women refused,
saying they were not ashamed of their sufferings.
Then he said he would whip them upon their clothes when he had them tied to the cart.
But they said, "`Either set us free,
or do according to your order,`" which was to whip them on their naked backs.
He then spoke to another woman who was present,
and ordered her to take off the women`'s clothes;
but she said she would not do so for all the world.
"`Well then,`" said he, "`I profess I will do it myself.`"
So he stripped them, and then stood trembling with the whip in his hand,
and so performed the execution, though at first he professed himself to be a stout man.
He then brought them to Salisbury, through dirt and snow half a leg deep,
and there they were whipped again.

Among the rest of the spectators,
one Edward Wharton happened to be passing along that way; and beholding the whipping,
Thomas Broadbury, clerk of the courts of Salisbury and Hampton, said to him,
"`Edward Wharton, what are you doing here?`"
"`I am here,`" he answered, "`to see your wickedness and cruelty,
that so if you kill these women, I may be able to declare how you murdered them.`"
For indeed, their bodies were so torn, that if Providence had not watched over them,
they might have been in danger of losing their lives.
But it fell out that after this whipping the women were discharged;
for one Walter Barefoot requested that he be deputized to carry them on to Newberry,
but instead of this he set them at liberty; though John Wheelwright, the priest,
advised the constable to continue on with their punishment.

Being thus unexpectedly released, these three women went to New Quechawanah,
where they had a meeting, and Shubal Drummer, the priest of the place,
came there also and sat quietly.
When the meeting had ended, this priest stood up and said, "`Good women,
you have spoken well and prayed well; please tell me,
what is the rule by which you walk?`"
They answered, "`The Spirit of God is our rule to walk by, and it ought to be yours,
and all men`'s.`" But he replied, "`It is not my rule, nor I hope ever shall be.`"
A clear evidence how prejudice may bias even discreet people;
for being prepossessed thereby, men will sometimes speak rashly,
without considering what they say.

Not long after, these women returned to Dover to visit their friends,
and being in a meeting the next First-day of the week, the constables,
Thomas Roberts and his brother John, rushed in,
and laid hands on Alice Ambrose as she was in prayer.
Taking her, one by the one arm, and the other by the other, they dragged her outdoors,
almost a mile, with her face towards the snow which was near knee deep,
over stumps and old trees,
having put on their old clothes on purpose so as not to dirty their better suits.
They then locked her up in a certain house, and so went back to fetch Mary Tomkins,
whom they dragged in the same manner, which their father, old Thomas Roberts seeing,
lamented, and cried, "`Woe that ever I was father to such wicked children!`"
But it seemed not to matter what their father said.
This old man had been a member of the church at Dover above twenty years;
but because he no longer frequented their worship because of their degeneracy,
they took away his cow, which with its milk, helped to support him and his wife.

Having brought Mary Tomkins into the house where Alice was, Anne Coleman was also fetched.
The next morning the constables got a canoe,
and threatened the women that they would now do something that
would keep them from being troubled with them any more--apparently
signifying that they would give them up to the mercy of the sea.
Then one Edward Weymouth took Mary by the arms,
and dragged her on her back over the stumps of trees, down a very steep hill,
by which she was much bruised and often fainted away.
They also took hold on Alice, whom they threw violently into the water,
and kept her swimming by the canoe so that she was
in danger of being drowned or frozen to death.
Anne Coleman was also rudely dealt with,
and all this was in in the presence of a ruling elder named Hate-evil Nutwel,
who stirred up the constables to this wicked action,
and so showed that he bore the wrong name.
But the wicked intention of these men was stopped by a power from on high,
for suddenly a great tempest arose,
so that they brought the women back again to the house,
and at about midnight they sent them all out into the snow,
the weather being so frosty that Alice`'s clothes were frozen like boards.
However barbarously these women were treated,
yet the Lord was pleased to preserve their lives and support them.

Afterwards it happened that Anne Coleman and four
of her friends were whipped through Salem,
Boston, and Dedham, by order of William Hawthorn, who before he was a magistrate,
had opposed compulsion for conscience.
And when during the government of Cromwell it was proposed
to make a law that none should preach without license,
he publicly said at Salem, that if ever such a law took place in New England,
he should look upon it as one of the most abominable
actions that were ever committed there,
and that it would be an eminent token of God`'s having forsaken New England.
Nevertheless,
afterward this man became a fierce persecutor of those who asserted liberty of preaching.
But to return to Anne Coleman, when she was to be whipped at Dedham,
and fastened to a cart, deputy Bellingham having seen Hawthorn`'s warrant, said,
"`The warrant is firm;`" and then bade the executioner go on; who, thus encouraged,
laid stripes on her so severely,
that with the knot of the whip he split the nipple of her breast, which so tortured her,
that it almost cost her her life.
And she, who was a small and weakly woman, thinking this might be her lot,
once said that if she should happen to die in this way,
she was willing that her body should be laid before Bellingham`'s door,
with a charge from her mouth that he was guilty of her blood.

The treatment Elizabeth Hooton met with, I cannot pass by in silence because of her age,
being about sixty, who hearing of the wickedness committed by those of New England,
was moved to make a voyage to America.

She went from England in the year 1661, having one Joan Broksup with her,
a woman near as aged as herself, who freely resolved to be her companion;
and because they could not find a shipmaster that was willing to carry them to
New England because of the fine for every Quaker that was brought there,
they set sail towards Virginia,
where they met with a vessel that carried them part of the way,
and then went the rest by land, and so at length came to Boston.
But there they could not easily find a place of reception,
because of the penalty upon all those that received a Quaker into their house.
Yet at length a woman received them.
The next day they went to the prison to visit their friends,
but the jailer being altogether unwilling to let them in,
carried them to the governor Endicot, who with much abusive language called them witches,
and asked Elizabeth what she had come for.
To this she answered, "`To do the will of Him that sent me.`"
And he demanding what that was, she replied:
"`To warn you of shedding any more innocent blood.`"
To this Endicot replied that he would hang yet more;
but she told him he was in the hands of the Lord, who could take him away first.^
footnote:[Which was fulfilled,
for after this time he never took away the lives of any more of those called Quakers,
and died March 15, 1665.]
This so displeased him, that he sent them to prison,
where were many more of their friends.
After consultation what to do with them,
they were carried two days journey into the wilderness, and left among wolves and bears.
But by Providence they got to Rhode Island, where they took shipping for Barbados,
and from there to New England again, and so they returned to Boston.
But then they were put into a ship which carried them to Virginia,
and from there Elizabeth departed to Old England,
where she stayed some time in her own habitation.

But it came upon her to visit New England again; and so she did,
this time taking her daughter Elizabeth along with her.
And having arrived,
the magistrates that were present would have fined the master of the ship
a hundred pounds for bringing her there contrary to their law.
But he telling them that Elizabeth had been with king Charles II,
and that she had liberty from him to come there to buy a house,
this so puzzled these snarling persecutors that they found themselves at a loss,
and thus were stopped from seizing the master`'s goods.

Having come to Boston, notwithstanding the rulers,
Elizabeth went to them and signified that she came
there to buy a house for herself to live in.
She was four times at the court for that purpose, but it was denied her;
and though she said that this denial would give her occasion
if she went to England again to lay it before the king,
her words were in vain, and had no influence upon them.

Departing then, and passing through several places,
she came to Cambridge and was thrust into a stinking dungeon,
where there was nothing to lie down or sit upon.
Here they kept her two days and two nights,
without affording her anything to eat or drink;
and because a certain man brought her a little milk in compassion,
he also was cast into prison and fined five pounds.
Being brought to the court, they ordered her to be sent out of their coasts,
and to be whipped at three towns with ten stripes at each.
So at Cambridge she was tied to the whipping-post and lashed with ten stripes,
with a three-stringed whip with three knots at each end.
At Water Town she had ten more stripes laid upon her with willow rods; and to conclude,
at Dedham, on a cold frosty morning,
she received ten more cruel lashes bound to the back of a cart.
Then, being thus beaten and torn,
she was put on horseback and carried many miles into the wilderness,
and towards night was left where there were many wolves, bears, and other wild beasts,
and also many deep waters to pass through.
But being preserved by an invisible hand,
she came in the morning into a town called Rehoboth, being neither weary nor faint.
From there she went to Rhode Island, where coming to her friends,
she gave thanks to God for having counted her worthy
and enabled her to suffer for His name`'s sake,
beyond what her age and sex, generally speaking, could otherwise have borne.

After some stay there she returned to Cambridge, about eighty miles,
to fetch her linen and clothes,
which the inhuman persecutors would not allow her
to take with her after they had whipped her.
Having retrieved these things,
and going back with her daughter and Sarah Coleman (another ancient woman),
she was taken up by the constable of Charlestown and carried prisoner to Cambridge.
There, being asked by one of the magistrates, whose name was Daniel Goggin,
why she came there, seeing they had warned her not to come there anymore,
she answered that she came not there of her own accord, but was forced there,
after she had gone to retrieve her clothes,
which they would not let her take with her when she was whipped and sent away; and now,
returning back, she was taken up by force out of the highway, and carried there.
Then the other old woman was asked whether she acknowledged Elizabeth and her religion,
to which she answered, "`I acknowledge the Truth.`"
And of Elizabeth`'s daughter he demanded, "`Do you acknowledge your mother`'s religion?`"
But though she remained silent,
yet they were sent to the house of correction with orders to be whipped.
The next morning the executioner came before it was light,
and asked them whether they desired to be whipped there;
but this made Elizabeth ask "`Have you come to take away our blood in the dark,
being ashamed that your deeds should be seen?`"
But not heeding what she said,
he took her downstairs and whipped her with a three-stringed whip.
Then he brought down the other ancient woman, and did the same to her.
And taking Elizabeth`'s daughter he gave the like to her also,
who had never been there before, nor had said or done anything.
After this, Elizabeth (the mother) was whipped again,
being bound to the back of a cart at Boston and other places,
where she had come to see her friends.
But after this time I have several times seen her in England in a good condition.

I could relate many more severities of the New England persecutors;
but I long to come to an end, and therefore shall take a large step,
and outrun some space of time.

In the year 1664, it happened that Mary Tomkins and Alice Ambrose came again to Boston,
having been in Virginia,
where for their religion they had not only been put into the stocks,
but whipped each of them with thirty-two stripes, with a whip of nine cords,
and every cord with three knots.
These women were handled so severely, that the very first lash drew blood,
and made it run down from their breasts.
Having afterwards arrived at Boston,
Mary grew so sick that she was thought to be near death,
which made Edward Wharton with Wenlock Christison come from Salem to visit her.
But after they had been there a little time, two constables came in,
and notwithstanding Mary`'s weak condition, forced them all to the governor`'s house.
Now though Mary seemed to be mending a little,
yet she was still so ill that she fainted and fell down along the way.
But one of the constables stayed with her till she came to herself again,
and then brought her before the governor,
where were also deputy Bellingham and Thomas Daufort, one of the magistrates.
Here all four of them were ordered to be whipped; but because Mary was so weak,
and lest she might die under their hands,
they gave orders that she and Alice should not be whipped at Boston,
but at the towns beyond.
And this would have been executed, were it not for colonel Temple who, coming in,
interceded and prevailed for three of them.
But then Edward Wharton became the object of their fury,
on whom they vented their passion,
though they had nothing to charge him with but that he had
come from Salem to Boston to visit his sick friend;
and for this pretended crime the following warrant was framed:

[.embedded-content-document.legal]
--

[.salutation]
To the constables of Boston, Charlestown, Maiden, and Lynn.

You are each required to take into your custody Edward Wharton,
convicted of being a vagabond from his own dwelling-place.
The constable of Boston is to whip him severely with thirty stripes on his naked body.
And then from constable to constable you are required
to convey him until he has come to Salem,
the place where he says he dwells; and in so doing this shall be your warrant.

[.signed-section-signature]
John Endicot.

[.signed-section-context-close]
Dated at Boston, the 20th of June, 1664.

--

Pursuant to this warrant, E. Wharton, (who therein was called a vagabond,
for no other reason than having departed from his
dwelling-place) was led away to the market place,
where he was stripped, and his arms were bound to the wheel of a great gun.
Then the constable John Loel, bade the hangman to do his work severely;
which he did so cruelly that it was testified that peas might lie in the holes
that the knots of the whip had made in the flesh of his arms and back.
His body was swollen and very black from the waist upwards.
Such was the conduct of those who, in order to enjoy the free exercise of their worship,
had left Old England; and thus they treated a man that was of good reputation,
and who had lived in those parts more than twenty years,
and was once by the governor himself acknowledged to be his friend,
when he given to him in a time of need, saying then,
that if ever it lay in his power he would repay him; which now he did,
but in what an inhuman and barbarous manner!
That this governor Endicot had once been a man of meager economic condition,
appears from a letter written to him shortly after the death of Mary Dyer,
by one John Smith, because he had not only caused his wife to be whipped severely,
but had also kept her prisoner a whole winter, separate from her children,
and had been assisting in the making of an order that no
man or woman should bring anything to the imprisoned Quakers,
or carry anything from them, upon the penalty of five pounds for the first time,
and ten pounds for the second.
In this letter John Smith said:

[.embedded-content-document.letter]
--

O my spirit is grieved for you,
because the love I did once see in you has departed from you,
and there remains in you a spirit of cruelty and of hard-heartedness to your poor neighbors,
who you have formerly been much obliged to, and helped by, in the time of your need,
when you had no bread to eat.
O consider these times, and forget them not,
and the love you did find among poor people in the time of your necessity.
And consider how evil you have dealt with these, and repaid some of them now;
and how you do walk and act contrary to what you did formerly profess.
Yes, I have heard you say that all the armies on earth cannot subdue one lust in man or woman.
And now you pronounce sentence of death upon some,
because they cannot submit to your wills, nor worship as you do.

--

But I return to Edward Wharton,
who after his whipping was not led the direct way to Salem, but by Charlestown,
and so about the country, as if they had a mind to make a show of him.
Yet at Charlestown the constable was so compassionate
that he entertained him in his house,
and dressed his stripes, and the next day conveyed him to his home.
Since that time the said Wharton was whipped again severely;
but I pass by the particulars to avoid prolixity.
Yet I cannot forbear to say, that before he was whipped at Boston, as has been said,
it was told him that if he would promise the governor
to come no more to the Quakers`' meeting in Boston,
then it was likely the governor would let him have his liberty; to which Edward replied,
"`Not for all the world.
And friends, I have a back to give to the smiter,
and I have felt your cruel whippings before now,
and the Lord has made me able to bear them; and as I abide in His fear,
I need not fear what you will be allowed to do to me.`"

The case of one Anne Needham being also very remarkable, I will give a short hint of it.
She was fined at Boston for being one of the people
called Quakers and sentenced to be whipped,
which the constable, Thomas Roots, performed with great cruelty;
for seeing she kept silent while he lashed her,
he did whatever he could with his tormenting whip to make her cry out;
but all his endeavors proved in vain.
This made him say that the Quakers were a hard-hearted people;
however this appellation much better fitted himself,
and all those cruel persecutors that had really become hard-hearted to the highest decree,
insomuch that they had not only shaken off humanity, but all true sense of piety,
which I shall prove by instances wherein some were even blasphemous.

There was one Barlow, who formerly had been a preacher at Exeter,
but afterwards turned lawyer, and at length having become a marshal,
would boast that when he went to seize property for the payment of fines,
he would think to himself what goods were most serviceable to the Quakers,
and then he would take them away.
By such doings he encouraged others to vice;
for a certain Indian taking a knife from an Englishman`'s house,
and being told he should not steal, answered that he himself had thought so as well,
but now he had seen what Barlow and the magistrates did to the Quakers.
This Barlow grew rich in the days of Cromwell with the spoils of the innocent,
but grew poor after king Charles was restored.
This made Barlow say that he hoped for good times again,
but then took the shameful liberty to add,
"`but I believe the Quakers will not allow me to be in need.`"

At Hampton, priest Seaborn Cotton,
understanding that one Eliakim Wardel had entertained Wenlock Christison in his home,
went with some of his hearers to Eliakim`'s house,
having like a sturdy herdsmen put himself at the
head of his followers with a club in his hand.
Wenlock seeing him in this posture, asked him what he planned to do with the club;
to which he answered, "`I have come to keep the wolves from my sheep.`"
Wenlock then asking whether those he led were his sheep, got no answer,
but instead was led away by this crew to Salisbury.
This same priest Cotton having heard that major Shapleigh had become a Quaker said,
"`I am sorry for it, but I will endeavor to convert him.`"
And afterwards drinking in a house near the river Piscataway,
and hearing the major was there in a warehouse, he went there to speak with him.
But going upstairs, and being overcome with drink, he tumbled down,
and had such a heavy fall, that the major himself came to help this drunken converter.

When Edward Wharton was told once by governor Endicot,
that every soul ought to be subject to the higher power,
he thereupon asked whether that which set up the golden image,
and required all to fall down and worship it, was the higher power?
Endicot answered, "`Yes.`"
Then Edward queried whether the power that required Daniel to be cast
into the lion`'s den for praying to any besides the king for thirty days,
was the higher power?
The governor said, "`Yes.`"
The next question Edward asked was,
whether the three children that were cast into the fiery furnace
did well in not falling down and worshipping the golden image;
and whether Daniel did well in praying to his God,
contrary to what the higher power did command?
The governor replied, "`Yes,`" again.
But secretary Rawson, seeing how the governor had talked himself into a noose,
in order to help him out said,
"`They obeyed the higher power by suffering under it;`" to which Edward replied,
"`So do we.`"

Another of these magistrates whose name was Brian Pembleton,
was asked by George Walton and his wife Alice (who was reputed to be one
of the most godly women thereabouts) what the anointing was which the
apostle John exhorted the saints to mind in their day?
But the wickedness of this Pembleton may appear by the abominable
answer he gave--that John was either a fool or a madman,
or else he did not know what he said.
And blasphemous to a very high degree was what he said in response to the question,
"`What was that light which shone around Paul?`"
For his answer to this question was, "`It was the light of the devil for all I know.`"

Joshua Scotaway, also one of the magistrates,
asked Mary Thomkins in the court at Boston where she dwelt;
to which she answered with the words of the apostle, "`In God;
for in Him we live and move, and have our being.`"
To this Scotaway did not hesitate to say, "`So does every dog and cat.`"
Truly it is no wonder that men thus darkened in their minds,
grew also so hardened in their persecuting so as to glory in it.
This was indeed the case of one Thomas Daufort, a magistrate of Cambridge,
who in the governor`'s house at Boston, laid his hand on Wenlock Christison`'s shoulder,
said to him, "`Wenlock I am a mortal man, and I must die, and that before long;
and I must appear at the tribunal seat of Christ,
and must give an account for my deeds done in the body.
And I believe it will be my greatest glory in that day,
that I have given my vote for you to be soundly whipped at this time.`"
This made Wenlock say, "`O wicked man,
if you have nothing to glory in that day but in drawing the blood of the innocent,
and in laying stripes upon the servants of the living God,
your glory will be turned into shame, and woe will be your portion.`"

But no exhortation, no matter how extraordinary,
seemed to take any hold on these persecutors.
For once a girl of thirteen or fourteen years of age named Hannah Wright,
whose sister had been banished for religion, was stirred with such zeal that,
coming from Long Island some hundreds of miles into the bloody town of Boston,
she appeared in the court there,
and warned the magistrates to spill no more innocent blood.
These words so struck them at first, that they all sat silent;
till Rawson the secretary said, "`What, shall we be baffled by such a one as this?
Come, let us drink a dram!`"

Here we see the religion of these men,
who were once so careful that they would not join
with the worship of the Church of England.
But it seems not improbable that they fell away to this hardness of heart because,
having been convinced in their understandings of some superstitious
ceremonies that yet remained in the Church of England,
they did not set their light on the candlestick and
faithfully testify against these things,
but rather fled to America to shun the cross and avoid sufferings.
And yet these men were so presumptuous as to say they were the purest church on earth,
and that their magistrates and preachers very godly men.
But whatever these English people thought, they appeared to be worse than many others,
for in some places in America lived also Swedes,
who in regard of their worship were no less despised
by the English than were the Samaritans by the Jews;
and yet these Swedes entertained the Quakers when they came
among them far better than the English did.
Thus they made it appear that they surpassed them in their life and conduct,
if not in their religious profession.
But these rigid New England men seemed to place great virtue in an inflexible severity,
of which the following is an instance.

A Dutchman, an Ostender, whose name was John Lawrence,
was taken into custody for adultery, and brought before the court at Boston,
where the governor John Endicot asked him whether he was guilty or not guilty.
To this the prisoner, who it seems spoke very little English, said "`No guilt.`"
Upon which Endicot said in a scoffing manner, "`No gelt, there`'s no money!`"
For "`gheld`" means money in Dutch.
Thus the Dutchman`'s words and meaning were scoffingly distorted,
and though there was no clear evidence against him, yet he was condemned to be hanged.
But as the Dutchman denied any wrongdoing, the execution was deferred,
and in the meantime the priests John Wilson and James Mayo came
to him in prison to see what they could get out of him.
Priest Mayo told him his time was near an end and that he must shortly die,
and he therefore requested him now to confess.
The prisoner then asked him if he thought he should confess that which he never did?
But Mayo did not desist, but said, "`Confess, my son, and give glory to God.`"
Yet the prisoner continued in denying the charge, and affirmed he was clear.
"`But,`" said the priest, "`You cannot be clear; for our Lord and Savior says,
'`Whoever looks upon a fair woman, and lusts after her,
he has committed adultery with her already in his heart;`'`"--truly
a very perverse use of the Scripture for achieving a false end.
But the Dutchman seeing how they came to betray him, was cautious, and at length,
after a long and tedious imprisonment, found means to break prison,
and thus escaped from those who grew accustomed to be merciless;
thus sometimes others as well as Quakers, felt the weight of their severity.

It also happened about the time when William Leddra was put to death,
that one Elizabeth Nicholson and her two sons, Christopher and Joseph,
were charged with the death of her husband and their father Edmund Nicholson,
who was found dead in the sea.
And because information was given out that these people had shown love to those
they called "`cursed Quakers,`" they were all three fetched from their habitation
at Salem and carried to Boston to be tried for their lives merely on suspicion.
But even though nothing of murder was proved against them,
yet the mother was fined a great sum,
and her two sons were sentenced to stand under the gallows
for certain hours with ropes around their necks,
and to be whipped in the market place, which was performed accordingly.
And because these young men were not daunted, priest Wilson standing by, said, "`Ah,
cursed generation.`"
And they were ordered to be whipped at Salem also,
which was done so mercilessly that one of the young
men sunk down or fainted away under the torture,
though he was raised up again afterwards.

By this we may see how these New England persecutors
had become hardened to excessive severity.
But before I leave them, I must also mention the dreadful departure of some of them.

The last act of governor Endicot`'s bloody part that I find
was the cruel whipping of Edward Wharton at Boston,
related before; for the time had come for him to go off the stage,
and give an account of his extravagant severity before
another tribunal besides that of his sanguinary court.
The measure of his iniquity was now filled up,
and he was visited with a loathsome disease, insomuch that he stunk alive,
and so died with rottenness,
his name being likely to give a bad savor through ages to come.

Yet more remarkable was the death of major-general Adderton,
who when Mary Dyer was hanged said scoffingly, that she "`hung as a flag,
for others to take example by.`"
This man also,
when Wenlock Christison was condemned to death and warned
the persecutors of the righteous judgments of God,
presumptuously said, "`You pronounce woes and judgments,
and those that are gone before you pronounced woes and judgments;
but the judgments of the Lord God have not come upon us as yet.`"
But how he himself was struck by these judgments, and served for an example to others,
we are to see now.

He, upon a certain day, having exercised his soldiers,
was riding proudly upon his horse towards his house,
and came near the place where they usually loosed the Quakers
(so called) from the cart after they had whipped them.
Just then a cow came and crossed the way,
at which his horse took fright and threw him down so violently that he died,
his eyes having popped out of his head, his brains come out of his nose,
his tongue out of his mouth, and his blood ran out of his ears.
Thus God`'s judgments came upon him suddenly and unaware.

And John Norton, the chief priest of Boston, died likewise suddenly.
It was he who promoted the putting to death of those martyrs who died at Boston,
as has been related;
and when he saw the magistrates pause upon the execution
of William Robinson and Marmaduke Stevenson,
he encouraged them thereto, especially because John Winthrop,
the governor of Connecticut,
earnestly sought to dissuade them from the shedding of innocent blood.
He it was also who, when William Brend was beaten so barbarously with a rope,
as has been related in its due place, did not hesitate to say,
"`Since William Brend endeavored to beat our gospel ordinances black and blue,
it was but just upon him if he was beaten black and blue also.`"
But this Norton was now struck with a blow that made him sink;
for having been at his worship house in the forenoon,
and intending to go in the afternoon,
as he was walking in his house he let out a great groan,
and leaning his head against the mantle of the chimney, he was heard to say, "`The hand,
or the judgments of the Lord are upon me!`"
These were his last words, and he sunk down dead,
and would have fallen into the fire if he had not been caught by somebody that was present.
More examples of this nature I could produce, but these may suffice.

What I have related of these cruelties and much more,
was published in print about that time so that the king
and parliament of England might know what happened there;
for these actions had come into public view, and were known there all around the country.
All that was done in response was to set a false color upon their severity,
and to disguise matters.
And indeed,
these New England persecutors were fortunate they
had not to do deal with a revengeful people,
else they might have been involved in great difficulties;
but the friends of the victims committed all vengeance to God,
though some of the magistrates in England advised them to sue the persecutors,
which according to law they might have done.

Richard Bellingham, a fierce persecutor, and the governor after John Endicot,
lost his mental faculties ten years after, and died in that condition.
Not long before this time, William Coddington, governor of Rhode Island,
wrote a letter to him wherein he put him in mind of the former times;
for he (the said Coddington) had been one of the first erectors of colonies in New England,
and the first who built a house at Boston, and afterwards was a magistrate seven years.
But when persecution first arose he declared openly against it.
The case was debated three days in the court, but the moderate party was the weakest,
and was opposed by all the priests, except one John Cotton,
who said he remembered how at their departure from England he had preached on Acts 4:11,
showing from that text that there was an inward grace which was to be minded,
and that therefore he would not give his vote for
persecuting the asserters of that doctrine;
showing thereby much more sense of religion than the other persecuting priests.
Now though William Coddington was one of the greatest merchants or traders in Boston,
and in all probability might have acquired great riches there,
yet seeing his good counsel was not hearkened to,
he resolved to depart that place and to go and live somewhere else.
But whatever he said in his letter to Bellingham,
this man remained hardened like Pharaoh, and showed himself cruel,
even when Mary Fisher and Anne Austin first came to Boston,
where he treated them in a barbarous manner.

Yet one thing remarkable I may mention here, which when I first heard,
I could not fully give credit to;
but thinking it worth the while to make a narrow inquiry into it, I did so,
not only by writing, but also from the mouths of persons that had been eye-witnesses,
or had been informed by such.
From all these I got this concurring observation, namely,
that the country around Boston was formerly a very
fruitful soil that produced excellent wheat,
but that since the time this town was stained with the blood of the Quakers (so called),
no wheat, etc. would grow to perfection within twenty miles,
though the ground had been plowed and sown several times.
Sometimes what was sown was spoiled by vermin or insects; at other times it grew up,
but scarce yielded more than was sown, and so could not offset the cost;
and in another year the expected harvest was ruined by another accident.
And these disappointments continuing for many years,
the people at length grew weary of making further trial, and so left the ground untilled,
notwithstanding that twenty miles away from Boston the soil remains very fruitful,
and the yields of corn very good.
But there having been so many reiterated instances of unfruitfulness nearer the town,
and ancient people that are alive still and remember the early times,
generally agree in their opinion that this is a judgment from heaven,
and a curse on the land, because of the shedding of innocent blood at Boston.
This relation I have received from many credible persons,
though the one knew nothing of the other.
Yet what they told me did so well agree in the main,
that I could not help but believe it, though I am not given to being gullible;
and therefore I have been the more exact in my inquiry into the facts.
Thus I can no longer question the case;
but it seems to me to be a punishment on that blood-thirstiness
which now has ceased long ago.

In the island of Barbados,
those called Quakers also suffered much at the hands of the people,
being instigated not a little by the priests Samuel Graves, Mathew Gray,
Thomas Manwaring, and Francis Smith; for these being often drunk,
gave occasion thereby to be reproved.
One Thomas Clark coming once into the place of public worship,
and exhorting the auditors to desist from lewdness and to fear God,
was so grievously beaten with sticks, that he fell down in a swoon.
Then priest Graves who had preached that morning, went to the house of Thomas Clark,
pulled his wife out of doors, and tore her clothes from her back.
And priest Manwaring,
who had threatened T. Clark that he would procure a law
to be made by which his ears should be cut off,
once wrote in a letter to him, "`I am sorry that your zeal surpasses your moderation,
and that a club must now beat out of you what the devil has inspired.`"
And this was because T. Clark had told him that his drunken
conduct was not fitting for a minister of the Gospel.
Other rough treatment which Clark met with I pass by,
though once he was set in the stocks and imprisoned.
But now I leave America, and return to England.

[.the-end]
End of Volume I
