== Chapter XIII

[.section-date]
1662

Having now left America and returned to England,
let us go and see the state of persecution at London, where desperate fury now raged;
though it was not in that chief city alone that the
Quakers (so called) were most grievously persecuted.
For a little before this time there was published in print a short
relation of the persecution of this people throughout all England,
signed by twelve persons,
showing that more than four thousand and two hundred of those called Quakers,
both men and women, were in prison in England,
denoting the number of them that were imprisoned in each county,
either for frequenting meetings, or for denying to swear, etc.
Many of these had been grievously beaten, or their clothes torn or taken away from them;
and some were put into stinking dungeons where some
men said they would not have put their hunting dogs.
Some prisons were crowded full both of men and women,
so that there was not sufficient room for all to sit down at once;
and in Cheshire sixty-eight persons were in this manner locked
up in a small room--an evident sign that they were a harmless people,
that such a number would not make any resistance or use force.
By such ill-treatment many grew sick, and not a few died in such jails;
for no age or sex was regarded, but even ancient people of sixty, seventy,
and older were not spared.
Most of these being tradesmen, shopkeepers, and husbandmen,
they were thus reduced to poverty;
for their goods were also seized for not going to church (so called),
or for not paying tithes.
Many times they were made to lie in prisons on cold nasty floors,
without being allowed to have any straw;
and often they have been kept several days without food.
It is no wonder therefore that many died by such hard imprisonments as these.

In London and its suburbs were imprisoned at this
time no less than five hundred of those called Quakers.
Some were put into such narrow holes that every person
scarcely had convenience to lie down,
and the felons were often allowed to rob them of their clothes and money.
Many who were not imprisoned,
nevertheless suffered hardships in their religious meetings,
especially at the meetinghouse in London known by the name of Bull and Mouth.
Here the trained military bands would frequently come armed with muskets, pikes,
and halberds, being conducted by an officer by order of the city magistracy;
and rushing into the meeting in a very furious manner,
these would begin beating those who had gathered to wait upon the Lord,
whereby many were grievously wounded, some fell down in a swoon,
and some were beaten so violently that they lived not long after it.

Among these was one John Trowel, who was so bruised and crushed,
that a few days afterwards he died.
His friends therefore thought it appropriate to carry
the corpse into the aforesaid meeting-place,
that it might lie there exposed for some hours to be seen of everyone.
This being done raised commiseration and pity among many of the inhabitants of London;
for the corpse, which had been beaten like a jelly, looked black,
and was swollen in a dreadful manner.
This gave occasion for some to send for the coroner, and he having come,
impanelled a jury of the neighbors and gave them a charge, according to his office,
to make true inquiry upon their oaths,
and to present what they found to be the cause of his death.
This jury viewing the corpse,
and having a surgeon or two with them to know their judgment concerning it,
at length withdrew without giving in their verdict,
only requesting the friends to bury the corpse, which was done accordingly that evening.
And though the coroner and jury met several times together upon this occasion,
and had many consultations,
yet they never would give out a verdict for the cause of death;
though it was sufficiently clear that the man was killed by violent beating.
The reason which some gave for the withholding of a verdict was,
that though John Trowel had been seen beaten and knocked down,
yet it having been done in such a confused crowd,
no particular man could be accused as his murderer.
And if a verdict was given that the deceased person was killed,
and yet no particular person could be charged,
then the city was liable to a great fine at the pleasure of the
king for allowing such a murder to take place in the daytime;
for this crime was not committed in a corner, but in a public place,
and they had failed in apprehending the murderer, but allowed him to escape.

In the meantime the friends of the deceased man did
not fail to give public notice of the fact,
and sent also a letter to the lord mayor, which letter they afterwards gave out in print,
together with a relation of this bloody business.
In the letter it was said, "`It may be supposed you have heard of this thing,
for it was not done in the night, but in the middle of the day; not suddenly, unaware,
or by mishap, but intentionally, and over a period of time; and not in a corner,
but in the streets of the city of London;
all which circumstances do highly aggravate this murder,
to the very shame and infamy of this famous city and its government.`"

A certain person who spread some of these printed relations was imprisoned for his pains.
However, another brought one of them to the king, and told him how things had been done;
at which the king said,
"`I assure you it was not by my advice that any of your friends should be slain;
you must tell the magistrates of the city of it, and prosecute the law against them.`"
This saying of the king was not long after also published in print:
but violence prevailed still;
for the person that was apprehended for spreading the said books
was sent to prison by the special order of alderman Richard Brown.
And since mention will be made several times in this work of Richard Brown,
it gives me occasion to say something of what kind of man he was.
In the time of Cromwell he had been very fierce against the royalists,
especially at Abington, not far from Oxford;
for this error he endeavored now to make compensation
by violently persecuting the harmless Quakers.
He was a handsome man, and could commit cruelty with a smiling countenance;
but more of his actions will be represented hereafter.

The Quakers (so called), seeing that they could not obtain justice,
let the matter of the murdered persons alone; for suffering was now their portion,
and they therefore left their cause to God.
Oftentimes they were kept out of their meetinghouses by the soldiers;
but they would then not go away, but would stand in front of the place,
and one or other of their ministers would generally step upon a bench,
or some high place, and so preach boldly.
So their number soon increased,
for they sometimes got more hearers than they otherwise might have had.
And sometimes the one preaching was soon pulled down,
which then gave occasion for another to stand up and preach, and thus often four or five,
one after another, were taken away as innocent sheep,
and carried to prison with others of their friends, at times forty or fifty at once.

This puts me in mind of what I heard my mother Judith Zinspenning say,
who in the following year went for England (with William Caton and his wife,
who lived at Amsterdam) to visit her friends there.
Coming to London, and going with others to the Bull and Mouth meeting,
entrance was denied them, so they met in the street,
where she saw one preacher after another pulled down at the cry an officer, saying,
"`Constable, take him away!`"
Several being thus led away, the constable came also to her,
and perceiving by her dress that she was a Dutch woman,
pulled her by the sleeve and said with admiration, "`What,
a Dutch Quaker!`" but meddled no further with her.
This keeping of meetings in the streets then became a customary thing in England;
for the Quakers (so called) were persuaded that the exercise of their
public worship was a duty from which no man could release them,
and they believed that God required the performing of this service from their hands.
And by this meeting in the streets, it happened sometimes that more than one, yes,
as many as three or four did preach at a time, one in one place, and another in another,
which in their meeting places could not have been done conveniently.
Thus they got an abundance of auditors, and among these sometimes were eminent men,
who passing by in their coaches, made their coachmen stop.
In this way they found there was indeed a great harvest,
and thus their church increased under sufferings.
And in those trying times they were pretty well purified of dross,
since the trial was too hot for such as were not sincere;
for by attending their meetings at such a time, one was in danger of being imprisoned,
or beaten until lame, or even unto death;
but this could not quench the zeal of the upright.

Now the taking away of one preacher, and the standing up of another,
became an ordinary thing in England, and it lasted yet long after this,
as I myself have been an eye-witness of there.
And when there were no more men preachers present,
sometimes a woman would rise and minister to the meeting.
Indeed, there were some who were not more than boys as to their age,
who were endued with a manly zeal, and who encouraged their friends to steadfastness.
In the meantime many also were imprisoned without being hauled out of their meetings;
for some were apprehended for merely speaking something on the behalf of their friends.
Such was the case of Rebecca Travers, who, going to the lieutenant of the Tower,
requested him to have compassion on some who were imprisoned for having attended meetings.
But the lieutenant grew angry at this; and as she went away,
one of the jail keepers gave her ill language;
whereupon she exhorted him to do good in his place,
while it was the Lord`'s will he had it.
But he was so offended that, going back to the lieutenant,
he complained that she had spoken treason,
and thereupon she was apprehended and sent to prison.

At times the rude soldiers were encouraged to cruelty
by officers who were not one bit better,
for they themselves would sometimes lay violent hands on peaceable people.
Among the rest, was the aforementioned alderman Richard Brown,
who formerly had been a major-general under Cromwell,
and now behaved himself with such outrageous fierceness,
that even the comedians did not hesitate to expose him by an allusion to his name Brown,
saying, "`The devil was brown.`"

A book was also printed,
wherein many base abuses along with his furious behavior were exposed to public view;
and this book was dedicated to him with this small epistle:

Richard Brown,

If you are not sealed up already for destruction,
and if repentance be not utterly hid from your eyes, may the Lord convert you,
and forgive you for all your hard and cruel dealings towards us.
We desire your repentance rather than your destruction.
And may the Lord God of heaven and earth give judgment
of final determination between you and us,
that all the earth may know whether your cause against us, or our cause,
is just before Him, who only is the righteous judge.

The said book, though published without the author`'s name, was not only sent to Brown,
but about thirty copies were also delivered to the lord mayor and the sheriffs of London,
that so they might know what was acted under their authority; for some,
though not authorized, yet being favorites at court,
were bold in their actions against the Quakers in
whatever way their malice prompted them.
Among these was one Philip Miller, who, though not an officer,
yet in the month called May of this year,
came into a meeting of the said people in John`'s street, in the parish of Sepulchres,
at London, without any order or warrant.
And holding a cane in his hand,
he commanded the rabble who attended him to secure whom he pleased,
and then fetched a constable who he forced by threats to go along with him,
and thus five persons were apprehended, among whom was John Crook,
of whom further mention will be made shortly.
Some days after,
this Miller came again to the said meeting place and struck several
persons with his cane because they would not depart at his command,
and then charged the constables whom he brought along with him
to secure and take into custody whomever he pleased.

About the latter end of the aforesaid month, on a First-day of the week,
one captain Reeves, and some soldiers with muskets and drawn swords,
came violently rushing into the Bull and Mouth meeting,
where they pulled down one who was preaching,
and presently laid hold of another who requested
Reeves to show a court order for his doings.
To this Reeves replied that he would not do so in that place;
but it appeared afterwards that he could not, having been granted no warrant at all.
Nevertheless,
he caused his soldiers to take away about forty persons
(some of whom were not at the meeting,
but had been taken up in the streets) and convey them to Paul`'s yard,
where they were kept till the public worship had ended there.
Then alderman Richard Brown came into the place where the prisoners were guarded,
and with great rage and fury laid hands first on a very aged person,
and pulled him down twice by the brim of his hat, whereby he lost it.
He then abused another in like manner as a soldier struck
this person a great blow with a pistol on his bare head.
Two others Brown treated in the like manner, and then sent them all to Newgate prison,
guarded by soldiers.

The same day some soldiers came to a meeting in Tower street,
and without any warrant took away twenty-one persons
called Quakers and carried them to the Exchange,
where they kept them some time, and then brought them before the said Richard Brown,
who in a most furious manner struck some and kicked others.
Seeing how Brown struck one with his fist in the face, and kicked him on the shin,
this made one of the prisoners say, "`What!
Richard, will you turn murderer?
You did not do so when I was a soldier under your command at Abingdon.
For then you commanded me and others to search people`'s houses for pies
and roast meat because they celebrated Christmas as a holy time;
and we brought these persons as prisoners to the guard for observing their superstitions.`"
For at that time, under Cromwell,
Brown was such a strict man that he pretended to
root out these superstitious customs from the church;
though there is reason to question whether his heart was sincere in this respect.
However, such blind zeal was unfit to convince people of their superstition;
and Brown well knowing that by his former behavior he had
very much disobliged those of the Church of England,
now endeavored to make amends for it by his fierce brutality against the harmless Quakers,
and so to come into favor with the ecclesiastics and the attendants of the king.
One of Brown`'s family having heard what was said to him, replied,
"`There is an Abingdon bird.`"
To which Brown returned,
"`He is a rogue!`" and then struck him with his fist under the chin,
which made another prisoner say, "`What, a magistrate and striker?`"
Upon which Brown with both his hands pulled him down
to the ground by the brim of his hat,
and then commanded the soldiers to take them all away and carry them to Newgate prison.

Upon a First-day of the week, in the month called June,
a company of soldiers came into the Bull and Mouth meeting with pikes, drawn swords,
muskets, and torches, as if they were going to fight;
though they knew well enough they should find none there but harmless people.
The first thing they did was to pull down the man that preached,
whom they hauled out of the meeting,
rejoicing as if they had obtained some great victory.
Then they brought him to the main guard at Paul`'s,
and returned to the Bull and Mouth where they apprehended some more,
whom they also carried to Paul`'s. After some hours,
these prisoners were carried to the house of the fore-mentioned Brown, and he,
asking the names of the prisoners, and hearing that of John Perrot, said, "`What,
you have been at Rome to subvert,`" but recalling himself said, "`to convert the Pope.`"
To which Perrot replied that he had suffered at Rome for the testimony of Jesus.
Whereupon Brown replied, "`If you had converted the Pope to your religion,
I should have liked him far worse than I do now.`"
To which Perrot replied, "`But God would have liked him better.`"
After some more short discourse, Brown committed them all to Newgate.

After this manner, the meetings of those called Quakers were disturbed at that time,
of which I could produce, if necessary, many more instances.
Once, one Cox, a wine-cooper, came with some soldiers into a meeting, where,
after great violence,
they took up two men of those called Quakers whom they beat
most grievously because they refused to go along with them,
though they showed no warrant for it.
At length the soldiers forced them with muskets into Paul`'s yard,
and when they had laid them down,
they dragged one of them by the heels on his back in a very barbarous manner.
This being done, the said wine-cooper was heard to say,
he would go and get a cup of wine, for these devils had wearied him out.
He then went to another meeting-place of these people,
where he also behaved himself very wickedly.
And being asked for his order, he answered by holding out his sword and saying,
"`This is my order.`"
Thus it seems he would ingratiate himself with Brown, who then being in favor at court,
was knighted, and sometime after also chosen to be lord mayor of London.

By the furious behavior of Richard Brown,
the soldiers were also encouraged to commit all manner of mischief; insomuch,
that being asked what warrant they had for their doings, one lifting up his musket, said,
"`This is my warrant.`"
Nor did these soldiers respect age,
for they took away out of a meeting at Mile-end two boys,
one about thirteen and the other about sixteen.
And when these were brought before the lieutenant of the Tower,
one who was present said he supposed they were not of the age of sixteen years,
and thus not punishable by the act.
But another returned, "`They were old enough to be whipped,
and should be whipped out of their religion.`"
So he sent them to Bridewell,
where their hands were put into the stocks and so pinched for the space of two hours,
that their wrists were much swollen.
This was done because they refused to work,
being persuaded that they had not deserved to be treated in this manner.
They also ate nothing at the charge of the said workhouse.
These lads, though they continued pretty long in that prison, yet remained steadfast,
rejoicing they were counted worthy to suffer for the name of the Lord.
They also wrote a letter to their friends`' children,
exhorting them to be faithful in bearing their testimony for the
Lord against all wickedness and unrighteousness.

Some days before this time, Thomas and John Herbert, living in London,
and some other musketeers,
came with their unsheathed swords into some private dwellings
and broke two or three doors (for at this time,
when some persons were seen to enter a house, though it was only to visit their friends,
it was called a meeting.) Now it happened in one house that
these rude fellows found five persons together,
one of whom was William Ames, who had come there out of Holland,
and another was Samuel Fisher.
And when it was demanded what warrant they had, they held up their swords and said,
"`Do not ask us for a warrant; this is our warrant.`"
Thereupon they took away these persons by force, and carried them to Paul`'s yard,
where they were made a laughing-stock to the soldiers.
From there they were brought to the Exchange,
where they met with no better reception from the rude soldiers;
and from there they were conducted to alderman Brown`'s house in Ivy-lane.
Brown seeing these prisoners,
sent them to Bridewell with a court order to be kept at hard labor.
But afterwards,
rethinking the matter and finding that his court order was not
founded on justice (for these persons were not taken from a meeting),
the next morning he sent another court order,
wherein they were charged with unlawfully assembling themselves to worship.

Thus these persons were committed to Bridewell prison and were required to beat hemp;
and they were treated so severely, that William Ames grew sick and was discharged,
being near to death;
for it being alleged that he was of Amsterdam (where he had lived most of the time for
some years successively) it seems they desired not to have him die in prison,
as some of his friends had done.
The others having been six weeks in Bridewell,
were presented at the court sessions in the Old Bailey;
but instead of being tried for what had already been charged against them,
they were required to take the oath of allegiance as the only business
of the court (according to what the deputy recorder said).
The prisoners then demanded that the law might be read,
by virtue of which the said oath was required of them.
This was promised by the court to be done; but instead of this,
they ordered the clerk to read only the form of the oath itself,
but would not permit the law for imposing the oath to be read.
And before the prisoners had either declared their willingness to take it,
or their refusal of it, they were commanded to be taken away;
which the officers did with such violence that they threw some of them down upon stones.
This made Samuel Fisher say, "`Take notice people,
that we have not yet refused to take the oath;
and that the court has refused to perform its promise
which they made just now before you all,
that the statute for the oath should be read.
If such doings as this ever prosper, it must be when there is no God.`"
But this was not regarded; and the prisoners, without any justice,
were sent to Newgate prison.

Among these was also one John Howel,
who had been sent by alderman Brown to work at Bridewell because,
being brought before him, he did not immediately tell him his name.
And being demanded in the court why he did not tell his name, he answered,
because he had been beaten and abused in the presence
of Richard Brown when he was brought before him.
Brown, who was also on the bench, asked him roughly, "`How were you abused?`"
And Howel replied, "`Blood was drawn from me in your presence;
which ought not to be done in the presence of a justice of peace.`"
But Brown growing very impetuous, replied, "`Stop your prating,
or the same will be done again here in the presence of the court.`"

About midsummer, Daniel Baker returned into England (who, as has been related,
had been at Malta,) and about two weeks after his arrival he, with four others,
were taken by a band of soldiers from the Bull and
Mouth meeting and carried to Paul`'s yard,
where having been kept for some hours, they were conveyed to Newgate prison.
In the evening they were brought before alderman Brown, to whom Baker with meekness said,
"`Let the fear of God and His peace be set up in your heart.`"
But Brown fell a laughing, and said,
"`I would rather hear a dog bark;`" and using more such scoffing expressions he charged
Baker and the others with the breach of the king`'s law in meeting together.
To this Baker said,
"`The servants of God in the apostles`' days were
commanded to speak no more in the name of Jesus;
and they answered, and so do I, '`Whether it be better to obey God than men,
you judge.`'`" He also instanced the case of the three young men in Babylon,
and Daniel who did not obey the king`'s decrees.
But Brown grew so angry that he commanded his men to smite D. Baker on the face.
This they did, and pulling him four or five times to the ground,
they smote him with their fists, and wrung his neck as if they would have murdered him.
This these fellows did to please Brown, showing themselves ready for any service,
however abominable.
And Baker, alluding to his travels,
signified that even Turks and heathens would abhor such brutish actions.
His fellow-prisoners were also abused by Brown, and then sent to Newgate prison again.

After some days they were called to the court sessions where their indictment was read,
which like others in such cases, did generally run in these terms: that "`the prisoners,
under pretense of performing religious worship,
contrary the established laws of the kingdom of England,
unlawfully and tumultuously had gathered and assembled themselves
together to the great terror of his majesty`'s people,
and to the disturbance of the peace of the king, in contempt of our said lord the king,
and his laws, and to the evil example of all others,`" etc.
The indictment being read, no witness appeared against the prisoners except for Brown,
who also sat on the bench.
Therefore the oath, as the ordinary snare, was tendered to them;
for it was sufficiently known that their profession did not allow them to take any oath.
They denying to swear, were sent back to prison,
to remain until they should be willing to take the oath.

If I would here set down all such like cases as have happened,
I might find more work than I should be able to perform.
For this ensnaring with the oath had become so common,
that some were taken up in the streets and brought to a justice of the peace,
only that he might tender the oath to them, and in case of denial, send them to prison,
though this was directly contrary to the statute of Magna Charta, which expressly says,
"`No freeman shall be taken or imprisoned, or be dispossessed of his estate or liberties,
but by the law of the land.`"
But this was not regarded by Richard Brown, who did whatever he wished;
for force and violence now prevailed.
And sometimes when the prisoners were brought to the bar for attending meetings,
freedom was denied them to justify themselves;
but to be bullied and baffled was their lot.

Once it happened, that a prisoner, who had been a soldier formerly under Richard Brown,
seeing that no justice or equity was observed, called to him, saying,
"`You are not fit to sit on the bench; for you made a son to hang his father at Abingdon,
and I can prove you to be a murderer.`"
This bold saying caused some disturbance in the court,
and Brown did not deny the thing in court, nor clear himself from it.
Nevertheless,
the other Quaker prisoners did not approve this prisoner`'s reviling of Brown,
but signified, that even if the fact were true,
yet they were not for reproaching any magistrate who sat upon the bench,
whose place and office they did respect and honor.
But I do not find that Brown ever prosecuted (on
that account) the man who spoke so boldly,
although otherwise he did whatever he desired,
without fearing that his fellow-magistrates would disclaim it,
as may appear by this following instance.

A certain person who had been taken by the soldiers
out of a meeting in a very violent and abusive manner,
said in the court,
that his refusing to go was because they would not
show him any warrant for their apprehending him;
since for all he knew,
they might be robbers or murderers with whom he was not bound to go.
But Brown, who was for violence, said to this,
"`If they had dragged you through all the gutters in the street, it had served you right,
if you would not go with them.`"
This he spoke in such a furious manner, that one of the prisoners told him,
"`You have had many warnings and visitations in the love of God, but have slighted them;
therefore beware of being sealed up in the wrath of God.`"
Hereupon one of the jailers came with his cane and struck some of the prisoners so hard,
that several of them were much bruised; and it was reported by some that Brown cried,
"`Knock him down,`" though others (mitigating it a little) claimed his words were,
"`Pull him down.`"
The former, however, seems most probable,
for the blows were so violent that some of the spectators cried out, "`Murder!
Murder!`" and asked, "`Will you allow a man to be murdered in the court?`"
Whereupon one of the sheriffs came in person down from his seat to stop the beating.
But Brown was so desperately filled with anger, that he said to the prisoners,
"`If any of you are killed,
your blood shall be upon your own head;`" and the
hangman standing by with his gag in his hand,
threatened the prisoners to gag any of them that should speak anything.
Thus innocence was forced to give way to violence.
And once, when being asked the common question, "`guilty, or not guilty,`" one answered,
"`I deny I am guilty,`" and "`I can say I am not guilty;`" and also in Latin,
saying "`Non reus sum.`"
Yet he was sentenced as a mute, and fined accordingly,
though the words he spoke fully signified not guilty,
albeit he had not expressed them in the exact terms.
But now it seemed they were for opposing the Quakers in every respect.

I will yet mention some more instances of Brown`'s brutality before I leave him.
Another being demanded to answer to his indictment, guilty, or not guilty,
and not immediately answering, but thinking a little how to speak safely,
Brown scoffingly said, "`We shall have a revelation shortly.`"
To this the prisoner said, "`How long will you oppose the innocent?
How long will you persecute the righteous seed of God?`"
But while he was speaking,
Brown indecently began to cry out in the language of those
wenches that go calling up and down the streets,
saying, "`Aha, aha, will you have any wall-fleet oysters?`"
And, "`Aha, have you any kitchen-stuff?^
footnote:[Kitchen-stuff was fat collected from pots and pans.]`"
And when a prisoner at the bar said he could not for conscience-sake
forbear meeting among the people of God,
Brown scurrilously replied, "`Conscience,--a dog`'s tail!`"
And when alderman Adams speaking to one of the prisoners said,
"`I am sorry to see you here,`" Brown replied, "`Sorry!
What should you be sorry for?`"
"`Yes,`" said Adams, "`He is a sober man.`"
But Brown, who could not endure to hear this, replied,
"`There was never a sober man among them,`" meaning the Quakers.
The spectators, who took much notice of him, disapproved his conduct exceedingly.
But he seemed to be quite hardened;
for at a certain time two persons being upon trial for the robbing of a house,
he told them, "`You are the greatest rogues in England, except for the Quakers.`"

Sometimes it happened that the prisoners were brought to the bar without being indicted;
and when they said, "`What have we done?`"
and desired justice, Brown (having no indictment against them) often cried,
"`Will you take the oath?`"
And when they replied saying,
"`For conscience-sake we cannot swear,`" they were condemned as transgressors,
though such proceedings as these were directly against the law.
But this seemed at that time to be little regarded.

However, sometime before this, it happened at Thetford in the county of Norfolk,
that judge Windham showed himself more just in a similar case,
for he sharply reproved the justices upon the bench
for having not only committed some persons to prison,
but also having them brought to the bar when no accuser had appeared against them.
But Richard Brown did whatever he desired,
and showed himself most furiously wicked when any prisoner
was brought before him with his hat on.

One John Brain, being taken in the street, and not in any meeting,
was brought by some soldiers before Brown.
Seeing him with his hat on,
Brown ordered him to be pulled down to the ground six or seven times,
and when he was down, they beat his head against the ground and stamped upon him.
Then Brown, like a madman, bid them to pull off his nose;
whereupon they very violently pulled him by the nose.
And when he got up, they pulled him again to the ground by the hair of his head,
and then by the hair pulled him up again.
And when he would have spoken on his own behalf against this cruelty,
Brown bade them stop his mouth.
Whereupon they not only struck him on the mouth,
but gagged his mouth and nose also so tightly, that he could not draw breath,
and was close to being choked;
at which actions Brown fell a laughing and at length sent him to jail.

Thomas Spire being brought before Brown, he commanded his hat to be taken off;
and because it was not done with as much violence as he intended,
he caused it to be put upon his head again, saying,
"`It should not be pulled off so easily.`"
Then T. Spire was pulled down to the ground by his hat, and pulled up again by his hair.
William Hill being brought before him, Brown commanded his hat to be pulled off,
so that his head might be bowed down;
whereupon he too was pulled to the ground and then
plucked up again by the hair of his head.
George Ableson was thus pulled to the ground and plucked up by his hair five times,
one after another, and was so beaten on his face, or the sides of his head,
that he staggered and bled, and for some days was under much pain.

Nicholas Blithold being brought before Brown, he took his hat with both his hands,
endeavoring to pull him down to the ground;
but because he did not fall all the way to the ground forwards,
he pushed him to throw him backwards, and then he gave him a kick on the leg,
and thrust him out of doors.
Thomas Lacy being brought before him, Brown himself gave him a blow on the face;
and Isaac Merrit, John Cook, Arthur Baker, and others were not treated much better;
so that he seemed more fit to have been a hangman than an alderman or justice.
But I grow weary of mentioning more instances of his cruelty.
These abominable achievements were published in print,
more at length than I have mentioned them; and the book, as has been said already,
was dedicated to him.

In this hot time of persecution,
Francis Howgill wrote and gave forth the following
paper for the encouragement of his friends.

The cogitations of my heart have been many, deep, and ponderous some months, weeks,
and days,
concerning this people which the Lord has raised to bear testimony unto His name,
in this the day of His power; and intercession has been made often for them to the Lord,
and a patient waiting to know His mind concerning them for the time to come;
in which often I received satisfaction as to myself.
But yet I was drawn by the Lord to wait for something more,
that I might comfort and strengthen His flock by an assured testimony.
And while I was waiting out of all visible things,
and quite out of the world in my spirit,
and my heart set upon nothing but the living God,
the Lord opened the springs of the great deep,
and overflowed my whole heart with light and love;
and my eyes were as a fountain because of tears of joy, because of His heritage,
of whom He showed me, and said unto me in a full, fresh, living power, and a holy,
full testimony, so that my heart was ravished there with joy unspeakable,
and I was out of the body with God in his heavenly paradise,
where I saw and felt things unutterable, and beyond all demonstration or speech.
At last the life united with my understanding, and my spirit listened unto Him;
and the everlasting God said,
"`Shall I hide anything from them that seek My face in righteousness?
No, I will manifest it to them that fear Me. I will speak;
you listen and publish it among all My people, that they may be comforted,
and you be satisfied.`"
And thus said the living God of heaven and earth, upon the 28th of the Third month, 1662.

The sun shall leave its shining brightness, and cease to give light to the world;
and the moon shall be altogether darkness, and give no light unto the night;
the stars shall cease to know their office or place; my covenant with day, night, times,
and seasons, shall sooner come to an end, than the covenant I have made with this people,
into which they have entered with me, shall end, or be broken.
Yes, though the powers of darkness and hell combine against them,
and the jaws of death open its mouth, yet I will deliver them, and lead them through all.
I will confound their enemies as I did in Jacob,
and scatter them as I did in Israel in the days of old.
I will take their enemies, I will hurl them here and there,
as stones are hurled in a sling; and the memorial of this nation, which is holy unto Me,
shall never be rooted out,
but shall live through ages as a cloud of witnesses in generations to come.
I have brought them to the birth, yes, I have brought them forth;
I have swaddled them and they are Mine.
I will nourish them and carry them as on eagles`' wings;
and though clouds gather against them, I will make My way through them.
Though darkness gathers together in a heap, and tempests abound,
I will scatter them as with an east wind; and nations shall know they are My inheritance,
and they shall know I am the living God,
who will plead their cause with all that rise up in opposition against them.

These words are holy, faithful, eternal, good, and true.
Blessed are they that hear and believe unto the end.
And because of these words no strength was left in me for a while;
but at last my heart was filled with joy,
even as when the ark of God was brought from the house of Obed-Edom,
when David danced before it, and Israel shouted for joy.

Francis Howgill.

It is certain that this writing of F. Howgill, who was a pious man of great abilities,
together with many other powerful exhortations of those who valiantly went before,
and never left the oppressed flock,
tended exceedingly to their encouragement in this hot time of persecution.
For however furious their enemies were,
yet they continued faithful in supplications and fervent prayers to God,
that He might be pleased to assist those in their upright zeal,
who aimed at nothing for self, but from a true fear and reverence before Him,
dared not leave off their religious assemblies.
And they found that the Lord heard their prayers,
insomuch that I remember to have heard one say,
that at a meeting where they seemed to be in danger of death from their fierce persecutors,
he was (as it were) so overcome by the power of the Lord,
that he hardly knew whether he was in or out of the body.
And thus, persevering in faithfulness to what they believed the Lord required of them,
in the process of time,
when their enemies had taken such measures to suppress and extinguish the Quakers,
they saw how the Lord God Almighty rose up in their defense,
and subdued and confounded the wicked devices of their cruel persecutors,
as will be seen in the course of this history.

In the meantime, let us take a view of the persecution in Southwark.
Here the Quakers`' meetings were no less disturbed than in London.
Several persons having been taken from their religious meetings were committed to prison;
and after having been in White-lion prison about nine weeks,
they were brought to the bar, where Richard Onslow sat as judge of the sessions.
The indictment drawn up against them was as follows.

The jurors for our lord the king do present upon their oath, that Arthur Fisher,
of the parish of St. Olave, in the borough of Southwark, in the county of Surry, yeoman;
Nathaniel Robinson, of the same, yeoman; John Chandler, of the same, yeoman; and others,
being wicked, dangerous, and seditious sectarians and disloyal persons,
and above the age of sixteen years, who on the 29th day of June,
in the year of the reign of our lord Charles the
Second (who by the grace of God is king of England,
Scotland, Ireland, etc.), have obstinately refused to attend some church, chapel,
or usual place of hearing the common prayer,
according to the laws and statutes of this kingdom of England.
And furthermore, on the 3rd day of August, in the parish of St. Olave aforesaid,
these did voluntarily and unlawfully join in, and were present at an unlawful assembly,
conventicle, and meeting, under the pretense of the exercise of religion,
against the laws and statutes of this kingdom of England,
in contempt of our lord the king, his laws,
and to the evil and dangerous example of all others.

I have inserted this indictment,
that the reader may see not only the manner of their proceeding,
but also with what black and heinous colors the religious
meetings of those called Quakers were represented.
This indictment being read,
the prisoners desired that they might be tried according
to the late act of parliament against conventicles.
But it was answered that they might try them by whatever law was in force.
Then the prisoners desired that the statute (that is,
the 35th of Elizabeth) might be read.
This was done but in part, and it was then said to the clerk that he had read enough.
The prisoners then said that this act was made in a time of ignorance,
when the people had but newly stepped out of popery;
and then they endeavored to show how unjustly they had been dealt with.
But being required to plead guilty or not guilty to the indictment,
some who were not very quick to answer, were hauled out of the court,
as pro confessi +++[+++in English, as having confessed], and so sent back to prison.
The rest, being twenty-two in number, pleaded not guilty.

The jurymen were then called, and when the prisoners had protested against one,
the judge would not allow it, because he did not like the reason they gave, namely,
that they saw envy, prejudice, and a vain behavior in him.
Another was protested against because he was heard to say that he "`hoped before long,
that the Quakers should be arraigned at the bar,
and be banished to some land where there were nothing but bears.`"
At this the court burst out into a laughter; yet the exception was admitted,
and the man was put by.
The prisoners not thinking it convenient to make more exceptions, the jury were sworn in.
Then two witnesses were called,
who testified nothing more than at such a place they took such persons who had met together,
whose names were specified in writing.
Then the prisoners bid the jury to take heed how
they did sport or trifle with holy things,
and that those things which concerned the conscience were indeed holy things.
And as a man was not to trifle with the health or illness of his neighbor,
so he was not to trifle with the liberty or the banishment of his neighbor.
And whereas they were accused of being wicked, dangerous, and seditious sectarians,
that was not true; for they were not wicked, but such as endeavored to live soberly,
righteously, and godly in the world.
Neither were they seditious, but peaceable.
And whereas they were charged with not coming to hear the common prayer,
this was incongruous;
for that service book was not yet printed until several
weeks after the said 29th of June;
so that they could not be charged with neglecting
to hear that which could not be be heard anywhere.
This puzzled the court not a little,
and other pinching reasons were also given by the prisoners,
some of whom were men of learning;
insomuch that the judge was not able to answer their
objections except by shifts and evasions.
At length the jury went out to consult, and one of them was heard to say,
as they were going upstairs, "`Here is a deal to do indeed,
to condemn a company of innocent men!`"

After some time the jury returned again,
and being asked whether the prisoners at the bar were guilty or not guilty,
they said they were "`guilty in part, and not guilty in part.`"
But this verdict did not please the judge.
The jury then going out again, and prevailing upon one another, quickly returned,
and declared the prisoners guilty according to the form of the indictment.
Hereupon judge Onslow pronounced sentence, namely:
That they should return to prison again, and lie there three months without bail;
and if they did not submit according as the law directed,
either at or before the end of the aforesaid three months,
then they must depart the realm.
But in case they refused to abandon the realm,
or should refuse to depart within the time specified,
or should return again without permission, they should be proceeded against as felons.

Just before the sentence was given, the judge said to one of the prisoners,
there was a way to escape the penalty, namely, submission.
And being asked what he meant, the judge answered, "`To come to hear the common prayer,
and to refrain from these meetings.`"
The prisoner giving reasons for their refusal of both, the judge said,
"`Then you must abjure the land.`"
"`To abjure,`" replied the prisoners, "`is to renounce upon an oath.`"
To which one of the justices said laughingly,
"`And you cannot swear at all;`" as if it were a
matter of jest thus to treat religious men.
But they had signified already to the jury that they would rather die than do so.
How long they were kept prisoners, and when they were released, I could not find;
but this I know, that many in the like cases have been long kept in jail,
till sometimes they were set at liberty by the king`'s proclamation.

In this year it was the lot of John Crook (who himself had once been a
justice) to be taken out of a meeting at London in John`'s street,
as has been said already, by one Miller, though he was not an officer.
He with others was brought to his trial in the said city before the lord mayor of London,
the recorder, chief justice Forster, and other judges and justices,
among whom was also Richard Brown.

Now since John Crook published this trial in print, and by that we may judge,
as ex ungue leonem, +++[+++in English: from the part we may judge the whole]
of other trials of the Quakers, I will give it here at length:

J+++.+++ Crook being brought to the courthouse in the Old Bailey, with two of his friends,
Isaac Gray, doctor of medicine, and John Bolton, goldsmith;
one of the prisoners was called to the bar, and then asked by the chief judge:

Chief Judge: What meeting was it that you were at?

Prisoner: I desire to be heard, where is my accuser?

Chief Judge: Your tongue is not your own,
and you must not have liberty to speak what you wish.

Prisoner: I speak in the presence and fear of the everlasting God.
My tongue is indeed not my own, for it is the Lord`'s,
and to be disposed of according to His pleasure, and not to speak my own words.
Therefore I desire to be heard.
I have been so long in prison... +++[+++then he was interrupted by the judge.]

Judge: Leave off your canting!

+++[+++He then commanded him to be taken away, which he was accordingly by the jailer.
This was the substance of what the prisoner aforesaid spoke the first time.]

Chief Judge: Call John Crook to the bar; +++[+++which the crier did accordingly,
he being kept among the felons as aforesaid.]

Chief Judge: When did you take the oath of allegiance?

J+++.+++ Crook: I desire to be heard.

Chief Judge: Answer the question, and you shall be heard.

J+++.+++ Crook: I have been about six weeks in prison, and am I now called to accuse myself?
For the answering to this question in the negative, is to accuse myself,
which you ought not to force me upon; for, Nemo debet seipsum prodere +++[+++in English:
No one should be obliged to betray himself.]
I am an Englishman, and by the law of England I ought not to be taken, nor imprisoned,
nor deprived of my possessions, nor called in question, nor made to answer,
except according to the law of the land; which I challenge as my birthright,
on my own behalf,
and all that hear me this day +++[+++or words to this purpose].
I stand here at this bar as a delinquent,
and do desire that my accuser may be brought forth to accuse me for my delinquency,
and then I shall answer to my charge, if there is any I am guilty of.

Chief Judge: You are here demanded to take the oath of allegiance,
and when you have done that, then you shall be heard about the other charge;
for we have power to tender the oath to any man.

J+++.+++ Crook: Not to me upon this occasion, and in this place;
for I am brought here as an offender already, and am not to be made an offender here,
or made to accuse myself.
For I am an Englishman, as I have said to you,
and I desire the benefit of the laws of England;
for by them is a better inheritance derived to me as an
Englishman than that which I received from my parents;
for by the former the latter is preserved,
and this is seen in the 29th chapter of Magna Charta,
and the "`petition of right,`" mentioned in the third of Car.
I., and in other good laws of England.
Therefore I desire the benefit and observance of these laws;
and you that are judges upon the bench ought to be my counsel, and not my accusers,
but rather to inform me of the benefit of those laws.
And wherein I am ignorant, you ought to inform me,
that I may not suffer through my own ignorance of those advantages
which the laws of England afford me as an Englishman.

+++[+++Reader, I here give you a brief account of how I was taken and imprisoned,
that you may judge the better what justice I had from the aforesaid court;
which is as follows.

I being in John`'s street, in London, about the 13th day of the third month (called May),
with some others of the people of God, to wait upon Him, as we were sitting together,
there came in a rude man called Miller with a long cane in his hand,
who laid violent hands upon me, with some others, beating some,
and commanding the constables who came in after him; but they having no warrant,
were not willing to meddle.
But as his threatenings prevailed, they being afraid of him,
joined with him to carry several of us before justice Powel (so called),
who the next day sent us to the court sessions at Hicks`'s Hall;
where after some discourse several times with them,
we manifested to them the illegality both of our commitment and their proceedings thereupon.
Yet notwithstanding, they detained me and others,
and caused an indictment to be drawn against us,
founded upon the late act against Quakers and others; and then remanded us to New Prison,
where we continued for some days; and then removed us to Newgate Prison,
where we remained until the court sessions in the Old Bailey as aforesaid.
Hereby you may understand what justice I met with, by what went before,
and now further follows:]

Chief Judge: We sit here to do justice, and are upon our oaths.
We are to tell you what the law is, and not you us; therefore, sirrah,^
footnote:[Sirrah was a word of reproach and contempt, used in addressing vile characters.]
you are too bold.

J+++.+++ Crook: Sirrah is not a word fit for a judge; for I am no felon.
Nor ought you to threaten the prisoner at the bar;
for I stand here arraigned as for my life and liberty,
and the preservation of my wife and children, and my outward estate,
they being now at stake.
Therefore you ought to hear to the full what I can say in my own defense.
Therefore I hope the court will bear with me, if I am bold to assert my liberty,
as an Englishman, and as a Christian; and if I speak loud, it is my zeal for the Truth,
and for the name of the Lord; and my innocency makes me bold.

Judge: +++[+++Interrupting John Crook]
It is an evil zeal.

J+++.+++ Crook: No, I am bold in the name of the Lord God Almighty, the everlasting Jehovah,
to assert the Truth, and stand as a witness for it.
Let my accuser be brought forth, and I am ready to answer any court of justice.

+++[+++Then the judge interrupted me,
saying "`sirrah,`" with some other words I do not remember.
But I answered:]

J+++.+++ Crook: You are not to threaten me,
neither are those insults fit for the mouth of a judge;
for the safety of the prisoner depends upon the impartiality of the court.
And you ought not to behave yourselves as a party,
all seeking advantage against the prisoner,
but not heeding anything that may help for his clearing or advantage.
+++[+++The judge again interrupting me, saying:]

Judge: Sirrah, you are to take the oath, and here we tender it to you,
+++[+++bidding one to read it].

J+++.+++ Crook: Let me see my accuser,
that I may know for what cause I have been six weeks imprisoned;
and do not put me to accuse myself by asking me questions,
but either let my accuser come forth, or otherwise let me be discharged by proclamation,
as you ought to do.
+++[+++Here I was interrupted again.]

Judge Twisden: We take no notice of your being here otherwise than of a straggler,
or as any other person or people that are here this day;
for we may tender the oath to any man.
+++[+++And another judge spoke to the like purpose.]

J+++.+++ Crook: I have been brought to your bar as a prisoner restrained of my liberty,
and I do question whether you ought in justice to tender
me the oath on the account I am now brought before you.
I am supposed to be an offender; or else why have I been six weeks in prison already?
Let me be first cleared of my imprisonment,
and then I shall answer to what is charged against me,
and to the question now propounded; for I am a lover of justice with all my soul,
and am well known by my neighbors where I lived to keep a conscience
void of offense both towards God and towards man.

Judge: Sirrah, leave off your canting.

J+++.+++ Crook: Is this canting, to speak the words of the Scripture?

Judge: It is canting in your mouth, though they are Paul`'s words.

J+++.+++ Crook: I speak the words of the Scripture, and it is not canting, though I speak them;
but they are words of truth and soberness in my mouth, they being witnessed by me,
and fulfilled in me.

Judge: We do ask you again, whether you will take the oath of allegiance?
It is but a short question, you may answer if you will.

J+++.+++ Crook: By what law have you power to tender me the oath?
+++[+++Then, after some consultation together by whispering, they called for the statute book,
and turning over the pages, they answered:]

Judge: By the third of King James.

J+++.+++ Crook: I desire that statute may be read; for I have consulted it,
and do not understand that you have power by that statute to tender me the oath,
being here before you in this place and upon this occasion, as a delinquent already.
Therefore I desire the judgment of the court in this case,
and that the statute may be read.

Judge: +++[+++Then they took the statute-book, and consulted together upon it, and one said:]
We are the judges of this land, and better understand our power than you do;
and we do judge that we may lawfully do it.

J+++.+++ Crook: Is this the judgment of the court?

Judge: Yes.

J+++.+++ Crook:
I desire the statute to be read that empowers you to tender
the oath to me upon this occasion in this place;
for, Vox audita perit, sed litera scripta manet +++[+++in English: Words only spoken are lost;
but writing remains], therefore let me hear it read.

Judge: Hear me.

J+++.+++ Crook: I am as willing to hear as to speak.

Judge: Then hear me.
You are here required to take the oath by the court,
and I will inform you what the penalty will be in case you refuse.
Your first denial shall be recorded,
and then it shall be tendered to you again at the end of the sessions.
Upon the second refusal, you run yourself into a premunire,
which is the forfeiture of all your estate (if you have any) and imprisonment.

J+++.+++ Crook: It is justice I stand for;
let me have justice by bringing my accuser face to face, as by law you ought to do,
for I stand at your bar as a delinquent.
And when that is done, I will answer to what can be charged against me,
as also to the question of the oath.
Until then, I shall give no other answer than I have already done, at least at present.

+++[+++There was then a cry in the court saying,
"`take him away,`" which occasioned a great interruption,
and J. Crook spoke to this purpose, saying:]

J+++.+++ Crook: Mind the fear of the Lord God, that you may come to the knowledge of His will,
and do justice.
And take heed of oppressing the innocent,
for the Lord God of heaven and earth will assuredly plead their cause.
As for my part, I desire not the hurt of one of the hairs of your heads;
but let God`'s wisdom guide you.
+++[+++These words he spoke at the bar and as he was being carried away.]

+++[+++On the sixth day of the week, in the forenoon following, the court having sat,
John Crook was called to the bar.]

Chief Judge: Friend Crook,
we have given you time to consider of what was said yesterday to you by the court,
hoping you may have better considered it by this time.
Therefore, without any more words, will you take the oath?
+++[+++He then called to the clerk, and bid him read it.]

J+++.+++ Crook: I did not, neither do I deny allegiance to the king,
but I desire to know the cause of my so long imprisonment.
For, as I said, I stand at your bar as a delinquent, and am brought here by force,
contrary to the law.
Therefore, let me see my accuser, or else free me by proclamation, as I ought to be,
if none can accuse me of the breach of any law.
For the law is grounded upon right reason, and whatever is contrary to right reason,
is contrary to law.
Therefore if no accuser appears, you ought to acquit me first,
and then I shall answer (as I have said) if any new matter appears;
otherwise I am being unlawfully forced, which our law abhors.
For what is not legally done, should not be done at all.
And therefore I am in the condition of not being rightfully brought before you.
It therefore cannot be supposed, in right reason, that you have power at this time,
and in this place, to legally tender me the oath.

Judge: Read the oath to him.
+++[+++And so the clerk began to read.]

J+++.+++ Crook: I desire justice, according to the laws of England.
You ought first to convict me concerning the cause of my long imprisonment.
For you are to proceed according to the laws already made, and not to make laws;
for you ought to be ministers of the law.

Judge: You are a saucy and impudent fellow.
Will you teach us the law, or our duties?
+++[+++Then he said to the clerk:]
Read on! +++[+++And when the clerk had finished reading, John Crook said:]

J+++.+++ Crook: Read the preface to the act.
I say again, read the title and preamble to the act; for titles to laws are claves legum,
as keys to open the law; for by their titles, laws are understood and known,
as men by their faces.
+++[+++Then the judges would have interrupted me, but I said as follows:]
If you will not hear me, nor do me justice,
I must appeal to the Lord God of heaven and earth, who is judge of the living and dead,
before whom we must all appear to give an account of the deeds done in the body;
for He will judge between you and me this day, whether you have done me justice or not.

+++[+++These words following, (or the like,) I spoke as I was being pulled away from the bar.]

J+++.+++ Crook: Mind the fear of the Lord God, that you may do justice,
lest you perish in His wrath.

+++[+++For sometimes the court cried, "`Pull him away,`" and then said, "`Bring him again!`"
And thus they did several times, like men in confusion and disorder.
The same day, in the afternoon, silence being achieved, John Crook,
was called to the bar before the judges and justices aforesaid.
The indictment being read, the judge said:]

Judge: Mr. Crook, you have heard your indictment, what do you say?
Are you guilty or not guilty?

J+++.+++ Crook: I desire to speak a few words in humility and soberness,
as my estate and liberty lie at stake,
and I am likely to be a precedent for many more of my Friends.
Therefore I hope the court will not deny me the right and benefit of the law,
being an Englishman.
I have good reason, before I speak anything to the indictment, to demand and tell you,
that I desire to know my accusers.
I have been kept these six weeks in prison, and I still know not my accusers,
nor have I seen their faces.

Judge: We shall afford you the right of the law, as an Englishman.
God forbid you should be denied it.
But you must answer first, guilty, or not guilty,
that so in your trial you may have a fair hearing and pleading.
But if you go on as you do (and will not answer guilty,
or not guilty,) you will run yourself into a premunire,
and then you lose the benefit of the law,
and expose yourself--body and estate--to great hazards; and then,
whatever violence is offered to your person or estate,
you are out of the king`'s protection, and lose the benefit of the law;
and all this by your not answering guilty, or not guilty.
If you plead not guilty, you may be heard.

J+++.+++ Crook: It is recorded in the statutes of the 28 Edw. 3. and 3,
and 42 Edw. 3. and 3. in these words.
"`No man is to be taken, or imprisoned, or made to answer,
without presentation before justices, or matter of record, or by due process,
according to the old law of the land.
And if anything be done to the contrary, it shall be void in court of law,
and held for an error.`"
And also in the 25th of Edw. 1. 2. and the 3 Car. 1. and the 29 cap.
Magna Charta: "`No freeman shall be taken and imprisoned but by the law of the land.`"
These words, ("`the law of the land,`") are explained by the statute of 37 Edw. 3. 8. to be,
"`without due process of law;`" and if any judgments are given contrary to Magna Charta,
they are void, 25 Edw. 1. 2.

Judge: Mr. Crook, you are out of the way, and do not understand the law.
Though you adore the statute law so much, yet you do not understand it.

J+++.+++ Crook: I desire you to tell me the right way.

Judge: Mr. Crook, hear me.
You must say, guilty, or not guilty.
If you plead not guilty, you shall be heard,
and then you may see how far the law favors you.
And the next thing is,
there are no circumstances whatsoever that are the cause of your imprisonment,
which you question, but those in which you have your remedies if you will do as we say,
and waive other things, and answer guilty, or not guilty.
What the law affords you, you shall have, if you do what the law requires you;
or else you will lose the benefit of the law, and be out of the king`'s protection.

J+++.+++ Crook: Observe how the judge seeks to draw me into a snare--by first pleading guilty,
or not guilty, and when I have done so, they may put me as an outlawed person,
out of the king`'s protection; and how then can I have remedy for my false imprisonment?
Therefore first clear me, or condemn me for my false imprisonment,
while I am still in a capacity to have the benefit of the law;
and do not first outlaw me for an offense that you have created to stop my mouth,
and then tell me that if I have been wronged, or falsely imprisoned,
I may have my remedy afterwards.
This is to ensnare me, and is contrary to both law and justice.

Judge: You must plead guilty, or not guilty.

J+++.+++ Crook: In humility and meekness I must say, I shall not do it.
I dare not betray the honesty of my cause,
and the honest ones of this nation whose liberty I stand for, as well as my own.
For truly,
I am not satisfied in my judgment nor in my conscience that
I ought to plead to a new offense created by you,
before I am first acquitted of the cause of my being brought prisoner to your bar.
I therefore see no other way than to urge this further:
that I may see my accusers... +++[+++Interruption].

Judge: The most notorious thief may say he is not satisfied in his conscience.

J+++.+++ Crook: My case is not theirs.
But even so, they are allowed to see their accusers; and may I not call for mine?
Therefore, call for them, for you ought to do so, as Christ said to the woman, "`Woman,
where are your accusers?`"
So you ought to say to me, "`Man, where are your accusers?`"... +++[+++Interruption].

Judge: Your indictment is your accuser,
and the grand jury has found you guilty because you would not swear.
What do you say, Mr. Crook, are you guilty, or not guilty?
If you will not answer, then what you have said already shall be taken for your answer;
and as I told you before, you will lose the benefit of the law.
What I tell you is for your good.

J+++.+++ Crook: What is truly for my good, I hope I shall take it so.

Judge: If you will not answer, you run yourself into a premunire;
and you will lose the benefit of the law, and the king`'s protection,
unless you plead guilty, or not guilty.

J+++.+++ Crook: I stand as one brought forcibly and violently here;
nor would I have been here but by a violent action.
That you should take no notice of this seems strange to me; and not only so,
but that you should hasten me so quickly into a course
of action wherein I shall not be able,
in any way, to help myself,
by reason of your hasty proceedings against me to put me out of the king`'s protection,
and the benefit of all law.
Was ever the like case known, or heard of, in a court of justice?

Judge: Friend, it is not here in question whether or not you were unjustly brought here.
If you were brought by a wrong hand, you have a plea against them;
but you must first answer guilty, or not guilty.

J+++.+++ Crook: How can I help myself after you have outlawed me by premunire?
Therefore, let a proclamation be made in the court that I was brought here by force,
and let me first be cleared by proclamation, as you ought to do;
for you are discernere per legem, quid sit juslum, +++[+++in English:
to determine justice by way of law,]
and not to do what seems good in your own eyes.

+++[+++Here I was interrupted again,
but might have spoken justice Crook`'s words in Hampden`'s case, who said,
"`We who are judges speak upon our oaths,
and therefore must deliver our judgments according to our consciences;
and the fault will lie upon us if it be illegal, and yet we deliver it as law.`"
And he further said,
"`We that are judges must not give our judgments according to policy, or rules of state,
nor conveniences, but only according to law.`"
These were his words, which I might have spoken; but was interrupted.]

Judge:
Even though no man tendered you the oath when you were committed
(as you say,) it is now tendered to you.
And from the time you refused it (being tendered
to you by a lawful authority) you are indicted.
We look not upon why you were brought here, but finding you here, we tender you the oath;
and finding that you refuse it, your imprisonment is now just, and according to law.

J+++.+++ Crook: How did I come to be here?
I have told you already it was by force and violence, without a court order,
which our law altogether condemns.
And therefore, as I am not legally before you, so I am not before you;
for what is not legally so, is not so.
For as I was brought illegally to your bar,
you ought not to take notice of my being here,
and much less to create further charges against me.

Judge: No, no, you are mistaken; for so you may say of all the gazers who are here,
they not being legally here, are not here.
I tell you, though a man be brought here by force, yet we may tender him the oath;
and if he does not take it, he may be committed to prison.
Authority has given us this power,
and the statute-law has given us authority to tender the oath to any person,
and so we have tendered it to you; and for your not taking it,
you are indicted by the grand jury.
Answer the accusation, or confute the indictment; you must do the one or the other;
answer, guilty, or not guilty.

+++[+++Here I was interrupted, but I might have said, that the people that were spectators,
beholding and hearing the trials,
are not to be called "`gazers,`" as the judge termed them;
because it is their liberty and privilege as Englishmen,
and the law of England allows it.
So that they are not to be termed gazers upon this account,
but are legally in that place to hear trials, and to see justice done.]

J+++.+++ Crook: The law is built upon right reason, or right reason is the law;
and whatever is contrary to right reason, is contrary to law; the reason of the law,
being the law itself.
I am no lawyer, and my knowledge of it is but little,
yet I have had a love to it for the right reason which I have found in it,
and have spent some leisure hours in the reading of it.
The law is that which I honor, and it is good in its place;
many laws being just and good--not all of them, but, I say,
a great part of them--and it is not my intention in the
least to disparage or derogate from them.

Judge: Mr. Crook, you have been told, you must plead guilty or not guilty,
or else you will run yourself into a premunire.
Do not be your own enemy, nor be so obstinate.

J+++.+++ Crook: I do not desire to stand obstinately before you, neither am I so.
If you understand it otherwise, it is a mistake indeed.

Judge: Will you speak to the indictment, and then you may plead?
If you will not answer guilty, or not guilty, we will record it,
and judgment shall go against you.
Clerk, enter it.

Recorder: Mr. Crook, if you will answer, you may plead for yourself.
Or will you take the oath?
The court takes no notice of how you came here.
What do you say?
Will you answer?
For a man may be dragged out of Smithfield by his head and shoulders,
and the oath tendered to him, and may be committed to prison,
without taking any notice how he came here.

J+++.+++ Crook: That kind of proceeding is not only unjust,
but unreasonable also--+++[+++here was some interruption]--and
it is against the laws aforementioned, which say:
"`No man shall be taken or imprisoned but by warrant, or due process of law,`"
so that this speech of the recorder`'s savors more of passion than justice;
more of cruelty than due observance of law;
for every forcible restraint of a man`'s liberty, is an imprisonment in law.
Besides, this kind of practice, to take men by force and imprison them,
and then ask them questions, the answering of which makes them guilty,
is not only unrighteous in itself, but is against the law,
and makes one evil act the ground of another; and one injury offered to one,
becomes the foundation of another; and this is my case this day--+++[+++Interruption.]

Judge: Mr. Crook you must not be your own judge; we are your judges.
But for our parts we will not wrong you.
Will you answer, guilty or not guilty?
If not, you will run yourself into a premunire unavoidably,
and then you know what I told you would follow; for we take no notice how you came here,
but finding you here, we tender you the oath.

J+++.+++ Crook: Then it seems you make the law a trap to ensnare me, or as a nose-of-wax,^
footnote:[The term "`nose-of-wax`" was used to refer to a person
or thing that was easily twisted or swayed in any direction.]
or whatever you please.
Well, I shall leave my cause with the Lord God, who will plead for me in righteousness.
But suppose I do take the oath now, at this time, you may call me again tomorrow,
and make a new tender; or others may call me before them.

Judge: Yes, if there be new matter;
or if there be any sudden occurrence whereby you give new occasion on your part.
Mr. Crook, will you swear?

J+++.+++ Crook: If I do take it today, it may be tendered me again tomorrow, and so next day,
ad infinitum,
whereby a great part of my time may be spent and
taken up in taking the oath and swearing.

Chief Judge: When you have once sworn, you may not be put upon it again,
unless you minister occasion on your part.

J+++.+++ Crook: Is this the judgment of the court,
that the oath once taken by me is sufficient, and ought not to be tendered a second time,
without new offense given on my part?

Judge: Yes; so long as you make it appear that you have once taken it.

J+++.+++ Crook: Is this the judgment of the whole court?
For I would not do anything rashly.

Judges.
Yes, it is the judgment of the court, +++[+++to which they all standing up, said "`Yes.`"]

J+++.+++ Crook:
Then it seems there must be some new occasion given by me after I have once taken it,
or it ought not to be tendered to me the second time.

Judges.
Yes.

J+++.+++ Crook: Then by the judgment of this court,
if I may make it appear that I have taken the oath once,
and I have given no new occasion on my part whereby
I can be justly charged with the breach of it,
then it ought not to be tendered to me a second time.
But I have indeed taken it once, when I was made a freeman of the city of London;
witness the records in Guildhall, which I may produce;
and there has been no new occasion appearing to you on my part.
If there is, let me know it.
If not, you ought not, by your own judgment,
tender me the oath a second time.--+++[+++Interrupted by the shout of the court,
when these last words might have been spoken.]

Judge: Mr. Crook, you are mistaken, you must not think to surprise the court,
nor draw false conclusions from our judgments.

J+++.+++ Crook: If this is not a natural conclusion from the judgment of the court,
let right reason judge.
And if you retreat from your own judgments, what justice can I expect from you?
For, if you will not be just to yourselves, and to your own judgments,
how can I expect you should be just to me?

Judge: Mr. Crook, even if you have taken the oath, yet if there be a new emergency,
you are to take it again.
As for instance, the king has been out of England, and has now come in again.
There are many that have taken it twenty, thirty, or forty years ago,
yet this new emergency requires it again.
And although you have taken it,
yet you must not make it appear before you answer guilty,
or not guilty.
Therefore do not wrong yourself, and endanger yourself and family.
Do you think that every fellow that comes here shall argue as you do?
We need nothing else but to know of you whether you will answer guilty, or not guilty,
or take the oath, and then you shall be freed from the indictment.
What do you say?
Are you guilty, or not guilty?

J+++.+++ Crook: Will you not stand to your own judgments?
Did you not say, even now, that if I had once taken the oath,
it ought not to be tendered to me the second time,
unless I administered new occasion on my part that I have not kept it?
But no such occasion appearing, you ought not to tender it to me the second time,
by your own confession, much less to indict me for refusal.

Judge: If you will not plead, we will record it, and judgment shall be given against you.
Therefore say, guilty, or not guilty, or else we will record it.
+++[+++The clerk beginning to record it.]

J+++.+++ Crook: Before I answer, I request a copy of my indictment;
for I have heard it affirmed by counsel learned in the law,
that if I plead before I have a copy, or have made my exceptions,
my exceptions afterwards against the indictment will be made void.
Therefore I desire a copy of the indictment.

Judge: He that said so deserves not the name of a counsel; for the law says,
you must first answer, and then you shall have a copy.
Will you plead guilty or not guilty?

J+++.+++ Crook: If my pleading guilty, or not guilty,
will not deprive me of the benefit of quashing the indictment for insufficiency,
or other exceptions that I may make against it, I shall speak to it.

Judge: No, it will not.
Will you answer, guilty, or not guilty?
If you do not plead, the indictment will be found against you.
Will you answer?
We will stay no longer.

J+++.+++ Crook: I am upon the point.
Will not my pleading deprive me of the benefit of the law?
For I am tender in that respect, because it is not my own case only,
but may be the case of thousands more;
therefore I would do nothing that might prejudice others, or myself, as a Christian,
or as an Englishman.

Judge: You shall have the right done to you as an Englishman.
The way is to answer, guilty or not guilty.
If you plead, and afterwards find the indictment not good, you may have your remedy.
Answer, guilty or not guilty.

J+++.+++ Crook: As to the indictment it is very large, and seems to be confused,
and made up of some things which are true, and some things which are false.
My answer therefore is, what is true in the indictment I will not deny,
because I make what I say a matter of conscience.
Therefore, with regard to what is true, I confess myself guilty,
but I am not guilty of what is false.

Judge: That is not sufficient, either answer guilty, or not guilty,
or judgment will be given against you.

J+++.+++ Crook: I will speak the truth, as before the Lord,
as all along I have endeavored to do.
I am not guilty of that which is false, contained in the indictment,
which is the substance thereof.

Judge: No more ado.
Are you guilty or not?

J+++.+++ Crook: I must not wrong my conscience.
I am not guilty of what is false, as I said before.
What is true, I am guilty of; what is not true,
I am not guilty of that--which is the greater part thereof, as I said before.

Recorder: It is enough, and shall serve turn.
Enter that, clerk.

The seventh day of the week, called Saturday.

Silence being made, John Crook was called to the bar.
The clerk of the sessions read something concerning the new jury,
which was impaneled on purpose,
the previous jury being discharged who had been eyewitnesses
of what passed between us and the court.
Several of this new jury were soldiers,
some of whom had by violence and force pulled and hauled Friends out of their meetings,
and some of us out of our houses; and this was the jury by whom we were to be tried.
The clerk then read the indictment +++[+++as I remember].

J+++.+++ Crook: I desire to be heard a few words, which are these:
I request that we may have liberty till the next quarter sessions to traverse the indictment,
it being long and in Latin, and likely to be a precedent for many others.
I hope I need not press this issue; because I understood that you promised,
(and especially the recorder, who, when asked, declared "`You shall have counsel`"),
which we cannot be expected to have had the benefit of as yet, the time being so short,
and we kept prisoners, and not permitted to go forth to advise with counsel,
neither could we find a way to get counsel to come to us.
And as we had no copy of the indictment before this morning,
and today being so suddenly hurried down to the court sessions,
we cannot reasonably be supposed to be prepared (as
to matter of law) to make our defense.

Judge: We have given you time enough, and you shall have no more.
We will try you at this time, therefore swear in the jury.

J+++.+++ Crook: I desire we may have justice, and that we may not be ensnared in our trial,
but that we may have time till the next quarter sessions, our indictment being in Latin,
and so large as it is.
This is only reasonable, and is the practice of other courts.
For, in any case for the value above forty shillings,
it is not ordinarily ended in under two or three terms.
And in the quarter sessions, if a man be indicted for a trespass,
even if only for the value of five shillings, he has liberty to enter his defense,
and upon security given, he is granted liberty till the next sessions,
which is the ordinary practice.
This liberty we also desire, and we hope, as it is so reasonable,
that it will not be denied, especially upon this occasion,
as we are likely to be made a precedent for others.

Judge: There is no great matter of law in the case; it is only matter of fact,
whether you have refused to take the oath or not.
This is the point in issue; and what precedent can arise here?

Recorder: Mr. Crook, there is no need for law or counsel in this case;
and therefore we considered of it last night, and sent you word.
The keeper of the prison was spoken to, to tell you that we intended to try you this day,
and we therefore ordered that counsel might come to you if you so desired;
and also the clerk was told to give you a copy of the indictment.
This is fair; therefore we will go on to swear the jury,
for the matter is only whether you refuse the oath or not?
Therefore it is in vain to say anything, for the court is resolved to try you now;
therefore swear in the jury, cryer.

J+++.+++ Crook: I hope you will not try to surprise us.

+++[+++Then the other prisoners (who also were indicted) cried out, "`Let us have justice,
and let not the jury be sworn in till we have first been heard.`"
So there was a great noise, the court being in a confusion, some crying,
"`Take them away;`" others, "`Stay, let them alone;`" others saying,
"`Go on to swear the jury;`" and the cryer, in this uproar and confusion,
did do something to that end.
Then we all cried out for justice and liberty until the next sessions.
The court continued in a state of confusion, some crying one thing, and some another,
which I now cannot call to mind, neither what we said to them, nor they to us.
The noise was great, and the commands of the court to the officers were various,
some commanding them to take us away; others, to let us alone; others,
to bring us nearer;
others cried to put us back into the place where the felons used to stand,
which we were accordingly forced to do.
And in this great disorder and confusion that was among them,
some men were sworn to testify that we refused to take the oath,
which we never positively did.
Other officers of the court, whom they desired to swear, refused to do it,
and though pressed to it by the chief justice, they desired to be excused.
Then one of the prisoners spoke again,
but he could hardly be understood by reason of the noise in the court.
But speaking to the people with a loud voice by way of exhortation,
some could hear the substance of what he said,
which cannot now be particularly called to mind; but was, in essence,
to express the presence and love of God to himself,
and to exhort others to mind His fear, that they also might become acquainted with God,
etc.]

Judge: Stop his mouth, executioner! +++[+++Which was accordingly done.]

Prisoners: Will you not give us leave to speak for ourselves?
We except against some of the jury, as being our enemies.
Indeed some are the very men who by force commanded us to be pulled out of our meetings,
contrary to law, and carried us to prison without warrant or due process of law.
Shall these now be our judges?
We except against them.

Judge: It is too late now,
you should have done it before they had been sworn in as jurymen.
Jury, go together now.
That which you must determine is whether they have refused to take the oath or not,
which has been sworn before you that they did refuse.
You need not go from the bar.
+++[+++Similar words were spoken by the recorder and others,
there being a confusion and noise in the court, many speaking at the same time.]

+++[+++Then we cried for justice, and that we might be heard,
desiring to make our defense before the jury gave their verdict.
But the judge and recorder said we would not be heard, crying out again,
"`Stop their mouths, executioner!`", which was done accordingly with a dirty cloth.
The executioner also endeavored to have me gagged, striving to get hold of my tongue,
having a gag ready in his hand for that purpose; and so we were treated several times.
Then I called out with a loud voice:]

J+++.+++ Crook: Will you condemn us without a hearing?
This is to deal worse with us than Pilate did with Christ.
For though he condemned Christ without a cause,
yet it was not without hearing Him speak for Himself.
But you deny us both.

Judge: Let Mr. Gray come to the bar.

+++[+++Room being made, Isaac Gray was conveyed by an officer in the inner bar,
where he spoke to the court to this purpose:]

Isaac Gray: I desire to know whether, according to law, and the practice of this court,
myself and my fellow prisoners may have liberty to put in bail,
in order to prosecute our defense at the next sessions?

Court: No, we will try you presently.

Judge: Stop their mouths, executioner! +++[+++And this was the cry of many upon the bench,
they being still in a continued confusion; some crying to the jury,
"`Give in your verdict,
for we will not hear them;`" with other words which
could not be heard because of the noise,
the court being in confusion.]

J+++.+++ Crook: You might as well have caused us to have been murdered before we came here,
as to bring us here under a pretense to try us,
and then not give us freedom to make our defense,
but instead command us to be thus abused, and to have our mouths stopped.
Was anything like this ever known?
Let the righteous God judge between us!
Will you hear me?
You have often promised that you would.

Judge: Hear me, and we will hear you.
+++[+++He then began to speak, and some others of the bench interrupted him.
Sometimes two or three spoke at one time,
and there was a noise among the officers of the court.
But the judge said:]
We can give you liberty until the next sessions, but it is our choice;
and therefore we choose to try you now.

J+++.+++ Crook: +++[+++I bid the people:]
Take notice of their promise, that I should have liberty to speak.
+++[+++Then speaking to the judges:]
See now, be as good as your word.

Judge: The law of England is not only just, but merciful;
and therefore you shall not be surprised or ensnared,
but shall have what justice the law allows.

J+++.+++ Crook: The judge has said just now that the law of England was a merciful law;
and the court said that they might, if they were willing,
give us liberty till the next sessions, but they would not.
The maxim of the law is, Summum jus est summa injuria, +++[+++in English:
The extreme of the law is extreme injustice]. Therefore
I hope your practice will make good this maxim,
and show the law of England to be a merciful law; and not to execute summum jus,
+++[+++the extreme of the law]
upon me, and thereby condemn yourselves out of your own mouths.

Judge: Jury, give in your verdict.

J+++.+++ Crook: Let me have liberty first to speak; it is but a few words,
and I hope I shall do it with what brevity and pertinency my understanding will allow,
and the occasion requires.
It is concerning these two heads: Matter of law, and matter of conscience.
With regard to matter of law, I have this to say: First, as to the statute itself,
it was made against the papists, occasioned by the gunpowder plot,^
footnote:[The Gunpowder Plot was a failed attempt to blow
up King James I and the Parliament on November 5,
1605, led by Robert Catesby, who sought to restore the Catholic monarchy.]
and is entitled, "`For the better discovery and suppressing of papist recusants.^
footnote:[i.e. Roman Catholic non-conformists]`" But now these have liberty,
and we are destroyed.--+++[+++Interrupted by the judges
and disturbance of the court.]--As to conscience,
I have something to say, and that is, it is a tender thing,
and we have known what it is to offend it;
and it is for this reason that we dare not break Christ`'s commands, who said.
"`Swear not at all;`" and the apostle James said,
"`Above all things my brethren swear not.`"--+++[+++Interrupted.
The court then called again to the executioner to stop my mouth,
which he did accordingly with his dirty cloth, as aforesaid, and his gag in his hand.]

Judge: Let us hear the jury.

+++[+++The jury then said something to him, which was supposed to be the verdict.]

Judge: Cryer, make silence in the court.
+++[+++Then the recorder, taking a paper into his hand, read:]

Recorder: The jury for the king do find that John Crook, John Bolton,
and Isaac Gray are guilty of refusing to take the oath of allegiance;
for which you do incur a sentence of premunire,
which is the forfeiture of all your real estates during your life,
and your personal estates forever; and you are now put out of the king`'s protection,
and shall be imprisoned during his pleasure.
This is your sentence.

J+++.+++ Crook: But we are still under God`'s protection.

[.asterism]
'''

Then the prisoners were remanded to Newgate prison,
where John Crook found opportunity to make a narrative of the whole trial,
which was printed as aforesaid, together with the Latin indictment,
in which he showed several errors, either by wrong expressions or by omissions.
Thus the injustice of these arbitrary proceedings were exposed to public view,
that the king himself might see thereby how wrongly his subjects were treated.
But at that time there were so many among the leading men and bishops
who were inclined to promote the extermination of the Quakers,
that there seemed to be no human help.
John Crook also showed particularly how in many cases
of trial they had acted against law;
for he himself having formerly been a justice, knew well enough how,
and after what manner, justice ought to be administered and maintained.
How long he continued prisoner, I cannot find.
But by this trial alone the reader may see how the Quakers
(so called) were treated with regard to the oath.
Such kind of proceeding was the lot of many of them,
because the intent at that time of those in authority
seemed to be to suppress this people.

By these and the like treatments,
we see how the persecutors endeavored to root out the Quakers, if possible;
for the effecting of which, alderman Richard Brown did whatever he could,
continually letting loose the reins of his exorbitant malice,
without regarding whether that which he was bent against was really punishable, or not,
whereof the following instance may serve for an evidence.

A certain mender of old shoes, who belonged to the society of the Quakers,
was desired by a laboring man, on a Seventh day of the week, late at night,
to mend a pair of shoes for him,
that he might have them again in the morning because he had no other shoes to wear.
The cobbler, to accommodate the man, stayed up at work till after midnight;
but the shoes not being then finished, he went to bed, and rising early in the morning,
went to his work again as privately as he could in his chamber.
But an envious neighbor informed against him for working on a Sunday;
whereupon he was brought before the said Richard Brown,
who committed him to Bridewell to be there kept to hard labor.
And he refusing to beat hemp,
as being fully persuaded that he had not deserved such a punishment, was cruelly whipped.
But he bore this with great constancy, and not yielding,
he was put among those of his society who were imprisoned there on a religious account.

As this case, which befell an honest man, was to be pitied,
so there also happened about that time something
among the Quakers in London which was equally ridiculous.
For several of them, having been taken out of their religious meetings,
were confined in Newgate prison where they lodged in a single large room,
having in the middle of it a great pillar.
To this pillar many fastened their hammocks at the one end,
and to the opposite wall on the other, all around the room, three stories high,
one on top of another;
so that those who lay in the upper and middle rows were made to go to bed first,
being obliged to climb up to the higher hammocks by first getting into the lower.
And underneath the lower level of hammocks, were laid beds upon the floor.
Such a multitude of bedding for so many persons in
one room could not but somewhat infect the air,
and cause an unhealthy steam; so that some of the prisoners grew sick,
and one of them died.
This caused some commotion,
and it was not without good reason that an ancient and grave citizen,
having seen the prisoners thus crowded up,
said "`This is enough to breed an infection among them.`"
And this having been told to Sir Willam Turner, one of the sheriffs of London,
he came into Newgate,
and bid the turnkey to bring down the said prisoners to him in the press-yard,
and then ordered they should return to Bridewell where they had been before.

Now among these was a shameful fellow, who, in order to get food without working,
had thrust himself among the Quakers when they were taken at a meeting,
on purpose to be sent to prison and to be maintained by them.
This lazy scoundrel was no small burden to our prisoners;
for whenever any food was brought in to them, either purchased with their money,
or sent to them by their friends, he did not hesitate to thrust in with his knife,
and make himself his own carver.
And such was his impudence, that if he saw that the provisions were small,
he would be sure to take enough for himself, though others were left in need.
But however burdensome this lazy sluggard was to the prisoners,
they could get no relief from him; for to whom should they complain,
since the jail-keepers, as well as others, were for afflicting and oppressing them?
But at length an opportunity came to be rid of his troublesome company.
Among the prisoners was Thomas Ellwood, a man of literature, and of an acute wit,
with whom (long after this) I entered into a familiar
and pleasing correspondence by letters.
The said T. Ellwood, when he had heard that they were to be sent to Bridewell,
drew near to the sheriff, and pointing to the aforesaid fellow, said,
"`That man is not only not one of our company, but he is an idle and dissolute fellow,
who has thrust himself among our friends that he might live upon them;
therefore I desire we may not be troubled with him at Bridewell.`"
The sheriff smiling, and seeing this fellow standing with his hat on,
and looking as gravely as he could that the sheriff might take him for a Quaker,
called him forth, and said to him, "`How did you come to be in prison?`"
"`I was taken at a meeting,`" said he.
"`But what business did you have there,`" said the sheriff.
"`I went to hear,`" replied the fellow.
"`Ay, you went with a worse design than that, it seems,`" replied the sheriff;
"`but I will disappoint you, for I will change your company,
and send you to those who are more like yourself.`"
Then calling for the turnkey, he said, "`Take this fellow, and put him among the felons;
and be sure that he trouble the Quakers no more.`"
This fellow, not a little astonished at the hearing of his fate,
suddenly parted with his Quakership; for off went his hat,
and he began bowing and scraping, and then said to the sheriff, "`Your worship,
have pity upon me, and set me at liberty!`" "`No, no,`" said the sheriff,
"`I will not disappoint you.
Since you had a mind to be in prison, in prison you shall be.`"
Then bidding the turnkey once more to take him away,
he took him up and put him among the felons.
After this manner this pretended Quaker was rewarded according to his deeds;
and so the true Quakers were rid of him.

Breaking off now this humorous, though true, narrative,
I return to a serious relation of the sufferings of the faithful,
which caused the death of some of them.
Among these was Richard Hubberthorn,
who some time before (as has been related) had a conference with the king,
who then promised him that he and his friends should
not suffer for their opinions or religion.
But now, in the month called June,
he was violently hauled from the meeting called the Bull and Mouth,
and brought before alderman Richard Brown,
who with his own hands pulled down Richard Hubborthon`'s hat upon his
head with such violence that he brought his head near to the ground,
and then committed him to Newgate.
There, being thronged among many others, he soon grew sick;
and his sickness so increased,
that he had hardly been two months in prison before he was taken away by death.
Two days before his departure, being visited by some of his friends,
who asked him if anything was upon his spirit,
he said that there was no need to discuss matters,
for he knew the ground of his salvation,
and was satisfied forever in his peace with the Lord.
He also said, "`That faith which has wrought my salvation, I well know,
and I have a grounded satisfaction in it.`"
In the morning before he deceased, one Sarah Blackberry was with him, to whom he said,
"`Do not seek to hold me here, for it is too confining for me,
and out of this confinement I must go; for I am departing into liberty,
and am to be lifted up on high, far above all.`"
In this frame of mind he departed this life, in the evening,
and so entered with happiness into eternity.
