== Chapter XIV

[.section-date]
1662--1664

Now I come also to the glorious exit of Edward Burrough, that valiant hero,
of whom mention has often been made in this history.
For several years he had been very much in London,
and there preached the gospel with piercing and powerful declarations.
That city was so near to him, that oftentimes, when persecution grew hot,
he said to Francis Howgill, his bosom friend,
"`I could freely go to the city of London and lay down my life for a testimony
to that Truth which I have declared through the power and Spirit of God.`"
Being this year at Bristol and thereabouts, and feeling moved to return to London,
he said to many of his friends when he took his leave of them,
that he did not know whether he would see their faces anymore,
and therefore exhorted them to faithfulness and steadfastness
in that wherein they had found rest for their souls.
And to some he said, "`I am now going up to the city of London again,
to lay down my life for the gospel, and to suffer among Friends in that place.`"

Not long after this, coming to London,
and preaching in the meetinghouse called the Bull and Mouth,
he was violently pulled down by some soldiers, brought before alderman Richard Brown,
and committed to Newgate.
Several weeks afterwards, being taken to the sessions-house in the Old Bailey,
he was fined by the court twenty marks, and required to lie in prison till payment.
But judging this fine to be unreasonable in a high degree,
he could not comply with it for conscience-sake.
Thus he was kept in prison there about eight months,
with nearly one-hundred and fifty other prisoners beside, upon the same account.
But these being so crowded together, they were greatly suffocated for lack of room,
and many grew sick and died, of which number he was one.
And though a special order from the king was sent to the
sheriffs of London for his and some other prisoners`' release,
yet such was the enmity of some of the city magistrates, especially Richard Brown,
that they did whatever was in their power to prevent the execution of the said order.
Thus E. Burrough continued prisoner, though his sickness increased.

During the time of his weakness, he was very fervent in prayer,
as well for his friends as for himself,
and many consolatory and glorious expressions proceeded from his mouth.
Once he was heard to say,
"`I have had the testimony of the Lord`'s love unto me from my youth; and my heart,
O Lord, has been given up to do Your will.
I have preached the gospel freely in this city,
and have often given up my life for the gospel`'s sake.
And now, O Lord, rip open my heart and see if it be not right before You.`"
Another time he said, "`There is no iniquity that lies at my door;
but the presence of the Lord is with me, and I feel His life to justify me.`"
Another day he was thus heard in prayer to God,
"`You have loved me when I was in the womb; and I have loved You from my cradle,
and from my youth unto this day, and have served You faithfully in my generation.`"
And to his friends that were around him, he said, "`Live in love and peace,
and love one another.`"
And at another time he said, "`The Lord takes the righteous from the evil to come.`"^
footnote:[Isaiah 57:1]
And praying for his enemies and persecutors, he said, "`Lord, forgive Richard Brown,
if he may be forgiven.`"
And being sensible that death was approaching, he said,
"`Though this body of clay must turn to dust,
yet I have a testimony that I have served God in my generation;
and that Spirit which has lived and acted and ruled in me,
shall yet break forth in thousands.`"
The morning before he departed this life (which was about the latter end of this year),
he said, "`Now my soul and spirit is centered into its own being with God;
and this form of person must return from where it was taken.`"
And after a little time he gave up his spirit.
This was the exit of Edward Burrough, who, in his flourishing years,
about the twenty-eighth year of his age, in an unmarried state,
changed this mortal life for an incorruptible,
and whose youthful summer flower was cut down in the winter season,
after he had very zealously preached the gospel for about ten years.

About the 19th year of his age, he first came to London with a public testimony,
and continued almost eight years preaching the word of God in that city with great success;
so that many came to be convinced, and great numbers were added to the church there.
In his youth he surpassed others of his age in knowledge; and though G. Croese,
who wrote his pretended history of the Quakers,
calls him a "`rustic fellow,`" yet he was no more so than the said author himself;
for he was well educated and instructed in that learning
which the place of his nativity (that is,
the barony of Kendal in Westmoreland) afforded.
Insomuch that, though he was not skillful in languages,^
footnote:[i. e. Greek, Hebrew, and Latin.]
yet he had the tongue of the learned;
and in his public ministry he was very fluent and elegant in speech,
even according to the judgment of learned men.

His enemies now began to rejoice, for they seemed to imagine that because of his decease,
the progress of that doctrine which he so powerfully and
successfully had preached would be stopped or retarded;
but they made a wrong reckoning.
Francis Howgill then gave forth a kind of lamentation which, though written in prose,
was not void of poetical expressions, and was as follows:

Shall days, or months, or years, wear out your name, as though you had no being?
Oh no!
Shall not your noble and valiant acts,
and mighty works which you have wrought through the
power of Him that separated you from the womb,
live in generations to come?
O yes!
The children that are yet unborn shall have your name in their mouths,
and your works shall testify of you in generations who have not yet a being,
and shall count you blessed.
Did your life go out as the snuff of a candle?
O no!
You have penetrated the hearts of many, and the memorial of the just shall live forever,
and be held in renown among the children of men.
For you have turned many to righteousness,
and shall shine as a star in the firmament of God`'s power forever and ever;
and they that are in that, shall see you there, and enjoy you there,
though you are gone away from here, and can no more be seen in mutability;
yet your life and your spirit shall run parallel with immortality.

Oh Edward Burrough!
I cannot but mourn for you, yet not as one without hope or faith,
knowing and having a perfect testimony in my heart of your well-being,
by the Spirit of the Lord; yet your absence is great,
and years to come shall feel your absence.
Shall I not lament as David did for a worse man than you, even for Abner,
when in wrath he perished by the hand of Joab without any just cause,
though he was a valiant man?
David lamented over Abner, and said, "`Died Abner as a fool dies?`"
Oh no!
He was betrayed of his life.
Even so have you been bereaved of your life by the hand of the oppressor,
whose habitations are full of cruelty.
Oh let not my soul enter into their council,
for your blood shall be required at the hands of those who thirsted after your life;
and it shall cry as Abel`'s who was in the faith; even so were you,
and it shall weigh as a heavy millstone upon their necks, and shall crush them under,
and be as a worm that gnaws and shall not die.

When I think upon you, I am melted into tears of true sorrow;
and because inheritance of the Lord has such need of you,
my substance is even as dissolved.^
footnote:[Job 30:22]
Shall I not say as David did of Saul and Jonathan when they were slain in mount Gilboa,
"`The beauty of Israel is slain upon the high places`"?
Even so were you stifled in nasty holes and prisons,
with many more who were precious in the eyes of the Lord.
Surely you were precious to me, oh dear Edward, I am distressed for you my brother!
Very pleasant have you been to me, and my love to you was wonderful,
passing the love of woman.
Oh you whose bow never turned back,
nor whose sword was ever free from the blood of the slain,
from the slaughter of the mighty;
you who made nations and multitudes shake with the Word of life in your mouth,
and were very dreadful to the enemies of the Lord!
For you did cut like a razor, and yet to the seed of God which He brought forth,
your words dropped like oil and your lips were as the honeycomb.

You shall be recorded among the valiants of Israel who attained to the first degree,
through the power of the Lord that wrought mightily in you in your day;
for you were worthy of double honor, because of your works.
You were an expert in handling your weapon, and by it the mighty have fallen,
and the slain of the Lord have been many.
Many have been pricked to the heart through the power of the Word of life;
and coals of fire from your life came forth from your mouth, so that many thickets,
briers and thorns were kindled,
and the fire did devour much stubble that encumbered the ground and stained the earth.
Oh how certain a sound did your trumpet give!
And how great an alarm did you sound in your day,
that made the host of the uncircumcised greatly distressed!
What man so valiant, though as Goliath of Gath, would your valor not have encountered,
though many despised your youth?
And how have I seen you wound the mighty with your sling and your stone!
And that which has seemed contemptible to the dragon`'s party,
even like the jaw bone of a donkey,
with it you have slain the Philistines heaps upon heaps, even as Samson.
You have put your hand to the hammer of the Lord,
and have often fastened nails in the heads of the Lamb`'s enemies, as Jael did to Sisera.
Many a rough stone have you polished and squared,
and made it fit for the building of God;
and much knotty wood have you hewed down in your day,
which was not fit for the building of God`'s house.

Oh you prophet of the Lord, you shall forever be recorded in the Lamb`'s book of life,
among the Lord`'s worthies, who have followed the Lamb through great tribulations,
as many can testify of you from the beginning.
And now at last you have overcome,
and been found worthy to stand with the Lamb upon Mount Zion, the hill of God.
Oh I have often seen you with your heart well-tuned as a harp to praise the Lord,
and to sound forth His great salvation,
which many a time has made glad the hearts of those that did believe,
and strengthened their faith and hope.

Well now, you are at rest, and bound up in the bundle of life;
and I know all tears were wiped away from your eyes,
because there was no cause of sorrow in you.
For I know you witnessed the old things done away, and there was no curse,
but rather blessings poured upon your head as rain, and peace as a mighty shower,
and trouble was far from your dwelling.
Though in the outward man you knew trouble on every side,
and have had a greater share in that (for the gospel-sake,
though but a youth) in your time than many others; but now you are freed from that,
and have obtained a name through faith with the saints in light.
Well, did you have more to give up than your life for the name of Jesus in this world?
No, but only to seal the testimony committed unto you with your blood,
as you have often said in your day,
which shall remain as a crown upon you forever and ever.
And now you are freed from the temptations of him who had the power of death;
and from your outward enemies, who hated you because of the love that dwelt in you.

And now you remain at the right hand of God,
where there is joy and pleasure forevermore in the everlasting light,
which you have often testified unto,
according to the word of prophecy in your heart which
was given unto you by the Holy Spirit;
and are at rest in the perfection thereof, in the beauty of holiness.
And yet your life and your spirit I feel to be present, and have unity with it,
and in it, beyond all created and visible things,
which are subject to variation and change;
and He who is your life shall enter into others, to testify unto the same Truth,
which is from everlasting to everlasting; for God has raised,
and will raise up children unto Abraham, of those who have been as dead stones.
Indeed, His power is Almighty,
and He is great in His people in the midst of their enemies.

With these sublime expressions Francis Howgill lamented
his endeared friend Edward Borrough.

In the latter end of this year, William Ames also deceased at Amsterdam,
having come from England in a weak condition,
for he had suffered so much hardship in Bridewell, London,
that his health was much impaired when he came into Holland.
In his sickness, which was a lingering disease,
he was told that among the Baptists and collegians,
it was said of him that he had changed his judgment,
and was grieved for having judged them wrongfully.
But to this he said, "`It is not so; but I still judge their way of worship,
and especially their disputations and will-worship, to be out of the way of the Lord.`"
And in this belief he died in peace.

In his youth he was of a cheerful temper, and a lover of merry company;
but being in that condition often disquieted in his mind,
he became a close follower of the priests and teachers,
and exercised himself diligently in reading the Holy Scriptures, which,
though good in itself, yet did not bring him to true peace with God.
Nevertheless, being of a quick understanding, he could talk much of them,
insomuch that entering into society with the Baptists, he became a teacher among them.
At that time, though he was more careful, and endeavored to avoid the committing of sins,
yet he found that the root from which sin sprang remained alive in him;
for when he met with something that was contrary to his own will or mind,
anger soon prevailed.
Yet in that state he would often speak of justification,
sanctification and cleansing by the blood of Christ,
though he himself had not come to that pure washing.
In this state he perceived that he was no true member of Christ,
because regeneration was still lacking.
Thus he saw that a zealous profession of religion would not avail,
and that something more was required to obtain a happy state; but as yet,
he knew not what it was that thus disquieted him; though sometimes,
upon committing any sin, he felt something that struck him with terror.

At length it pleased the Lord that,
upon hearing one of the Quakers (so called) preach that that which convinces
man of sin was the "`light of Christ which enlightens every man coming
into the world,`" this doctrine entered so deeply with him,
that he embraced it.
And thus walking with great circumspection and fear before the Lord,
he found that by giving diligent heed to that which
inwardly reproved and condemned him for evil,
he came to be delivered therefrom, and to witness a real sanctification.
And thus advancing in godliness he himself became a zealous preacher of that doctrine,
which had struck him so to the heart.
He was indeed a zealous man, and though some were ready to think him too zealous,
yet he was prudent; and I know that he was condescending in unimportant matters,
thinking that there were customs which, though not followed in one country,
were yet tolerable in another.
He was also generous, and lest he might seem to be burdensome to any,
he rather choose to work with his hands.

Now I return again to the occurrences of G. Fox, whom we left at London,
where having spent some time, he went about the beginning of the year 1663 to Norwich,
and from there to Cambridgeshire, where he heard of Edward Burrough`'s decease.
And being sensible how great a grief this loss would be to his friends,
he wrote the following lines to them:

Friends, be still and quiet in your own conditions,
and settled in the Seed of God which does not change;
that in that you may feel dear E. B. among you, in the Seed, in which, and by which,
he begot you to God, with whom he now is.
Thus, in the Seed you may all see and feel him,
in which is the unity with him in the life;
and so enjoy him in the life that does not change, which is invisible.

G+++.+++ Fox

G+++.+++ Fox afterwards traveling through several places, came again to London,
where having visited his friends in their meetings (which were numerous),
he travelled with Thomas Briggs into Kent.
Coming to Tenterden,
they had a meeting there where many came and were convinced of the Truth that was declared.
But when he intended to depart with his companion,
he saw a captain and a company of soldiers with muskets and lit torches.
Some of these men coming to them, said they must come with them to their captain.
When they were brought before him, the captain asked, "`Where is George Fox?
Which one is he?`"
To which G. Fox answered, "`I am the man.`"
The captain being somewhat surprised, said,
"`I will secure you among the soldiers;`" yet he carried himself civilly,
and some time after said, "`You must come along with me to the town.`"
Having come there,
he brought G. Fox and T. Briggs with some more of their friends to an inn,
which was the jailer`'s house.
And after a while the mayor of the town, with the said captain and the lieutenant,
who were justices, came and examined G. Fox,
asking him why he came there to make a disturbance?
G+++.+++ Fox told them, he did not come to make a disturbance, neither had he made any there.
They then said there was a law against the Quakers`' meetings,
which was made only against them.
G+++.+++ Fox told them he knew of no such law.
Then they produced the act which was made against Quakers and others.
G+++.+++ Fox seeing it, said,
"`This law is against such as are a terror to the king`'s subjects, and are enemies,
and hold principles dangerous to the government;
and therefore it was not against my friends, for they hold the truth,
and their principles are not dangerous to the government,
and their meetings are peaceable, as is well known.`"

Now it was not without good reason that George said he knew of no such law;
since they had said,
"`there was a law made only against the Quakers`' meetings;`" whereas the act
had the appearance of being made against plotters and enemies to the king,
which certainly the Quakers were not.
Yet it was then suggested to G. Fox that he was an enemy to the king.
But this he denied,
and he told them how he had once been cast into Derby dungeon about the time
of Worcester battle because he would not take up arms against the king;
and how afterwards he had been sent up to London
by colonel Hacker as a plotter to bring in king Charles,
and that he was kept prisoner at London till he was set at liberty by Oliver Cromwell.
They asked him then whether he had been imprisoned at the time of the insurrection?
He answered, "`Yes,`" but that he was released by the king`'s own command.
At length they demanded bond for his appearance at the court sessions,
and desired him to promise to come there no more.
But G. Fox refused the one as well as the other.
Nevertheless, these men behaved themselves moderately,
and told him and Thomas Briggs and the others, "`You shall see we are civil to you;
for it is the mayor`'s pleasure that you should all be set at liberty.`"
To which G. Fox replied, their civility was noble; and so they parted,
and he passed on to many places, where he had various remarkable occurrences,
and though many snares were laid for him,
yet sometimes he escaped the hands of his persecuting enemies.

Coming into Cornwall he found there one Joseph Hellen and George Bewly, who,
though they professed the truth, yet had allowed themselves to be seduced by Blanch Pope,
a ranting woman, who had ensnared them chiefly by asking, "`Who made the devil,
did not God?`"
This silly question, which J. Hellen and G. Bewly were at a loss to answer,
they propounded to G. Fox, and he answered it saying: "`No;
for all that God made was good, and was blessed, but the devil was not so.
He was called a serpent before he was called a devil and an adversary;
and afterward he was called a dragon, because he was a destroyer.
The devil abode not in the truth,
and it was by departing from the truth he became a devil.
Now there is no promise of God to the devil, that ever he shall return into truth again;
but to man and woman, who have been deceived by him,
the promise of God is that '`the seed of the woman shall bruise
the serpent`'s head,`' and break his power and strength to pieces.`"
With this answer, G. Fox gave satisfaction to his friends present;
but Joseph Hellen was so poisoned and gone out from the truth, that they denied him.
George Bewly, however, was recovered from his fault by sincere repentance.

G+++.+++ Fox, having performed his service there,
went to Helston near Falmouth where he had a large meeting at which many were convinced;
for he opened to the auditory the state of the church in the primitive times,
and the state of the church in the wilderness,
as also the state of the false church that had risen up since.
He next showed that the everlasting gospel was now being preached again,
over the head of the whore, the beast, the antichrist, and the false prophets,
which had risen up since the apostles`' days;
and that now the everlasting gospel was being received,
which brought life and immortality to light.
This sermon was of such an effect,
that the people generally confessed it was the everlasting
Truth that had been declared there that day.

G+++.+++ Fox passing on,
he came at length to the Land`'s End where there was an assembly of his friends,
and also a fisherman called Nicholas Jose who preached among them,
having three years before been convinced there by the ministry of G. Fox.

While in these parts, there occurred a very dismal and dreadful event.
Since the king had come in, one colonel Robinson had been made justice of the peace,
and become a cruel persecutor of those called Quakers.
Many of these he sent to prison,
and hearing that the jailer had granted some liberty to
them to come home sometimes to visit their wives and children,
he made complaint thereof to judge Keeling at the court session;
who thereupon fined the jailer a hundred marks.
Not long after the court session, this colonel Robinson sent to a neighboring justice,
desiring he would accompany him "`fanatic hunting,`" (by which he meant
disturbing and breaking up Quakers`' meetings.) On the day that he intended
thus to go "`hunting,`" he sent his servant with his horses,
and walked himself to a building where his cows and dairy were kept,
and where his servants were then milking.
Having come there, he asked for his bull,
and the maids told him they had shut him into the field,
because he was unruly among the other cows.
He then going into the field,
and having formerly accustomed himself to play with the bull,
he began to fence at him with his staff, as he used to do.
But the bull snorting, went a little back,
and then ran fiercely at him and struck his horn into his thigh.
And then lifting him upon his horn, threw him over his back,
and so tore him from his thigh up to his belly.
And when he landed upon the ground, he broke his leg,
and the bull then gored him again with his horns, and roared,
and began to lick up his blood.
One of the maid servants hearing her master cry out, came running into the field,
and took the bull by the horns to pull him off; but he, without hurting her,
gently put her aside with his horns,
and continued to gore the colonel and lick up his blood.
The maid then ran and got some workmen that were
not far off to come and rescue her master;
but they could not at all beat off the bull,
until they brought mastiff dogs and set them upon him; and then the bull fled.

His sister having received notice of his disaster, came and said, "`Alas, brother,
what a heavy judgment is this!`"
And he answered, "`Ah, sister, it is a heavy judgment indeed; pray,
let the bull be killed, and the flesh given to the poor.`"
So he was taken up and carried home,
but was so grievously wounded that he died soon after; and the bull had become so fierce,
that they were forced to kill him by shooting.
This was the outcome of Robinson`'s mischievous intent to go "`fanatic hunting.`"
I remember that in my youth I heard with astonishment
the relation of this accident from William Caton,
who by a letter from England had received intelligence of it;
for the thing was so remarkable, that the tidings of it were soon spread afar off.

Now I return to G. Fox, who from Cornwall travelled to Bristol, and so into Wales,
from which place, passing through Warwickshire and Derbyshire, he came to York.
Here he heard of a plot which made him write a paper to
his friends wherein he admonished them to be cautious,
and not at all to meddle with such activities.
And traveling towards Lancashire, he came to Swarthmore,
where they told him that colonel Kirby had sent his lieutenant there to search for him,
and that he had searched trunks and chests.
G+++.+++ Fox having heard this, the next day went to Kirby hall where the said colonel lived;
and having come to him, he told him, "`I have come to visit you,
understanding that you desired to see me;
and now I would like to know what you have to say to me,
and whether you have anything against me.`"
The colonel, who did not expect such a visit,
and being then about to go up to London to the parliament, said before all the company,
"`As I am a gentleman I have nothing against you; but Mrs.
Fell must not keep great meetings at her house; for they meet contrary to the act.`"
G+++.+++ Fox told him, "`That act does not take hold on us,
but on such as meet to plot and contrive, and to raise insurrections against the king;
and we are none of those, but are a peaceable people.`"
After some words more, the colonel took G. Fox by the hand,
and said he had nothing against him; and some others said that he was a commendable man.

Then G. Fox parted, and returned to Swarthmore,
but shortly after he heard there had been a private meeting
of justices and deputy lieutenants at Houlker-hall,
where justice Preston lived, and that there they had issued a warrant to apprehend him.
Now he could have gone away at that time and gotten far out of their reach,
but knowing that there was a rumor of a plot in the north,
he considered that if he should go away, they might come against his friends;
but if he stayed and was taken, then his friends might escape the better.
He therefore gave up himself to be taken.
The next day an officer came with his sword and pistols to take him.
G+++.+++ Fox told him, "`I knew your errand before, and have given up myself to be taken;
for if I desired to have escaped imprisonment, I could have been forty miles off;
but I am an innocent man, and so it matters not what you can do to me.`"
Then the officer asked him how he heard of it,
seeing the order was made privately in a parlor.
G+++.+++ Fox said it was no matter how; it was sufficient that he heard of it.
Then he asked the officer to show his order.
But he laying his hand on his sword, said, "`You must go with me before the lieutenants,
to answer such questions as they shall propound to you.`"
Now though G. Fox insisted to see the order,
telling him it was but civil and reasonable to show it, still the officer would not;
and so G. Fox said, "`I am ready.`"
So he went along with him, and Margaret Fell also, to Houlker-hall.

Having come there, there was one justice Rawlinson, Sir George Middleton,
justice Preston, and several more whom he did not know.
Then they brought one Thomas Atkinson, one of his friends, as a witness against him,
for some words which he had spoken to one Knipe, who had informed against him;
and these words were, that "`he had written against the plotters,
and had knocked them down.`"
But from these words little could be made against him.
Then Preston asked him,
whether he had a hand in the Battledore (the book already mentioned)?
"`Yes,`" said G. Fox.
He then asked him whether he understood languages?
He answered, "`sufficient for myself.`"

Preston having spoken something more on that subject, said, "`Come,
we will examine you concerning higher matters.`"
Then said George Middleton, "`You deny God, and the church, and the faith.`"
"`No,`" replied G. Fox, "`I acknowledge God, and the true church, and the true faith.`"
"`But,`" asked George (having understood Middleton
to be a papist) "`what church do you acknowledge?`"
This man, instead of answering this question, said "`You are a rebel and a traitor.`"
G+++.+++ Fox perceiving this Middleton to be an envious man, asked him, "`To whom do you speak?
Who is a rebel?`"
The other remaining silent a while, at last said, "`I spoke to you.`"
G+++.+++ Fox then striking his hand on the table, told him,
"`I have suffered more than twenty such as you, or any that are here.
For I have been cast into Derby dungeon for six months together,
and have suffered much because I would not take up
arms against this king before the Worcester fight.
And I have been sent up as a prisoner out of my own country by colonel
Hacker to Oliver Cromwell as a plotter to bring in king Charles.
You talk of the king, a company of you; but where were you in Oliver`'s days;
and what did you do then for the king?
But I have more love to him, for his eternal good and welfare, than any of you have.`"
Then they asked him, whether he had heard of the plot?
And he said, "`Yes.`"
Hereupon he was asked how he had heard of it, and whom he knew that was involved in it?
He answered that he had heard of it through the high sheriff of Yorkshire,
who had told Dr. Hodgson that there was a plot in the north;
but that he never heard anything of it in the south;
and that he knew none who were involved in it.
Then they asked him, "`Why would you write against it,
if you did not know some that were involved in it.`"
"`My reason was,`" answered he,
"`because you are so quick to mash together the innocent and guilty;
therefore I wrote against it to clear the Truth from such things,
and to stop all forward and foolish spirits from running into such things.
And I sent copies of it into Westmoreland, Cumberland, Bishopric, and Yorkshire,
and to you here.
I sent a copy also to the king and his council;
and it is likely it may be in print by this time.`"
Then said one of them, "`Oh this man has great power.`"
"`Yes,`" said he, "`I have power to write against plotters.`"
"`But,`" said one of them, "`you are against the laws of the land.`"
"`No,`" said he,
"`for my friends and I direct all the people to the Spirit of God in them,
to mortify the deeds of the flesh.
This brings them into well-doing,
and away from that evil which the magistrates`' sword is against.
This indeed eases the magistrates, who are for the punishment of evil doers.`"

Middleton now weary, as it seemed, of his speaking, cried, "`Bring the book,
and put the oath of allegiance and supremacy to him.`"
But G. Fox knowing him to be a papist, asked him whether he who was a swearer,
had taken the oath of supremacy?
For this oath, which rejected the Pope`'s power in England,
was a kind of test to try people whether they were papists or not.
"`But as for us,`" said G. Fox, "`we cannot swear at all,
because Christ and His apostles have forbidden it.`"
Now some of these that set there, seeing Middleton thus pinched,
did not desire the oath to be put to G. Fox.
But others desired it, knowing that this was their last snare,
and that they had no other way to get him into prison,
for all other things had been cleared.
So they tendered G. Fox the oath, and he refusing to take it,
they consulted together about sending him to jail; but all not agreeing,
he was only commanded to appear at the sessions,
and so for that time they dismissed him.

He then went back with Margaret Fell to Swarthmore, where colonel West,
who was at that time a justice of the peace, came to see him.
And G. Fox asking him what he thought they would do with him at the next court sessions,
he replied, they would tender the oath to him again.
The time of the sessions then approaching, G. Fox went to Lancaster,
and appeared according to his engagement, where he found upon the bench justice Flemming,
who in Westmoreland had offered five pounds to any man that would apprehend G. Fox.
There were also justices Spencer and Rawlinson, and colonel West;
and a great concourse of people in court, and when G. Fox came up to the bar,
and stood with his hat on, they looked earnestly upon him.
Then a proclamation being made for all to keep silence upon pain of imprisonment,
George said twice, "`Peace be among you.`"
Then Rawlinson, who was chairman, spoke, and asked if he knew where he was?
To which G. Fox answered, "`Yes, I do; but it may be that my hat offends you.
But that is a low thing, and not the honor I give to magistrates;
for the true honor comes from above,
and I hope it is not the hat which you look upon to be your honor.`"
To this the chairman said, "`We look for the hat too.
Wherein do you show your respect to magistrates, if you do not put off your hat?`"
G+++.+++ Fox replied, "`In coming when they call me.`"
They then bid one to take off his hat.
After some pause, the chairman asked him whether he knew of the plot.
To this he replied that he had heard of it in Yorkshire,
by a friend that had word from the high-sheriff.
The next question was, whether he had declared it to the magistrates; and his answer was,
"`I sent papers abroad against plots and plotters, and also to you,
as soon as I came into the country,
to take all suspicion out of your minds concerning me and my friends.
For it was, and is our principle to declare against such things.`"
Then they asked him if he knew not of an act against meetings.
To this he made answer,
that he knew there was an act that took hold of those
who met to terrify the king`'s subjects,
and were enemies to the king, and held dangerous principles.
"`But I hope,`" said he, "`you do not look upon us to be such men;
for our meetings are not to terrify the king`'s subjects, neither are we enemies to him,
or to any man.`"

That which followed hereupon was the tendering of
the oath of allegiance and supremacy to him.
To which he told them that he had never taken any oath in his life;
and that he could not take any oath at all,
because Christ and His apostles had forbidden it.
Then Rawlinson, who was a lawyer, asked him whether he believed it was unlawful to swear?
G+++.+++ Fox presently perceived this question to be put on purpose to ensnare him;
for by a certain act 13 and 14 Car. 2. cap. 1, such who said,
"`it is unlawful to swear,`" were liable to banishment or to a great fine.
Therefore to avoid this snare he told them, "`In the time of the law among the Jews,
before Christ came, the law commanded men to swear; but Christ,
who fulfilled the law in the gospel time, commands not to swear at all;
and the apostle James also forbids swearing,
even to those who were Jews and had the law of God.`"
Now after much other discourse, the jailer was called and G. Fox was committed to prison.
He then having the paper in his possession which he had written against plots,
he desired it might be read in the court; but this they would not allow.
Being thus committed for refusing to swear,
he said to those on the bench and to all the people,
"`Take notice that I suffer for the doctrine of Christ,
and for my obedience to His command.`"
Afterwards he understood that the justices had private
instructions from colonel Kirby to prosecute him,
notwithstanding his fair carriage and seeming kindness to him before.

Leaving G. Fox in prison, I am to say that the act already mentioned,
whereby a penalty was laid upon all such who should say,
"`it is unlawful to take an oath,`" was one which extended to banishment,
being made not long before and expressly leveled against the Quakers,
as plainly appeared by the title.
This is that act,
by direction whereof many of the Quakers (so called) were afterwards banished,
as may be related in its due time and place.
And though the king himself was pretty good-natured,
yet he allowed himself to be so swayed by the instigations of some envious men (both
among the ecclesiastics and the laity) that he gave royal assent thereto.

While G. Fox was prisoner at Lancaster,
many of his friends were also imprisoned for frequenting religious meetings,
refusing to take oaths, and for not paying tithes to the priests;
but since he was not brought to his trial till next year, we will leave him in jail,
and in the meantime take a turn to Colchester,
where persecution now was exceeding fierce.

In the month of October, William More, mayor of that town,
came on a First-day of the week and broke up the meeting of the Quakers (so called),
and committed some of them to prison.
The next week he did so again,
and a week after he caused a party of the county`'s
military troops to come into the meeting.
These beat some, and did much mischief to the benches, seats,
and windows of the meeting-place.
And afterwards,
the mayor employed an old man to stop people from going in at the gate into the meeting-room,
telling all that desired to enter that the mayor had set him there to keep them out.
Now though they knew he was no officer, nor had any warrant, yet they made no resistance;
but gathering together in the street, they thus kept their meeting in a peaceable manner,
not feeling free for conscience-sake to leave off their public worship of God,
though at that time of the year it was cold and often wet weather.
Thus they continued for many weeks, though attended with much difficulty.

In the forepart of December there came about forty of the
king`'s troopers on horseback into one of these meetings,
in their armor, with swords, carbines, and pistols, crying,
"`What the devil are you doing here?`"
And falling violently upon this harmless company,
they chased them to and fro in the streets, beating them,
some with swords and others with carbines, without distinction of male or female,
old or young, until many were much bruised.
The next First-day of the week these furious fellows came again, having now gotten clubs,
with which (as well as with their swords and carbines) they most grievously
beat those that were peaceably met together in the street to worship God.
This cruel beating was so excessive, that some received over a hundred blows,
and were beaten so black and blue that their limbs lost their natural strength.
There was one whom a trooper beat so long,
that the blade of his sword fell out of the handle, which he who was thus beaten seeing,
said to the trooper, "`I will give it back to you again,`" which he did,
with these words, "`I desire the Lord may not lay this day`'s work to your charge.`"

But to avoid prolixity,
I shall not mention all the particular abuses which I find to have been committed there.
These cruel doings continued yet several weeks,
and some were beaten so violently that their blood was shed in the streets,
and they sunk down and fainted away.
One Edward Graunt,
a man of about seventy years of age (whose wife and
daughters I was well acquainted with),
was so terribly knocked down that he lived but a few days afterwards.
So hot was this time of persecution, that these worshippers,
when they went to their meeting, seemed to go forth willing to meet their death;
for they could not promise to themselves to return home either whole or alive.
But notwithstanding all this, their zeal for their worship was so lively,
that they dared not stay at home, though human reasoning might have advised them thereto.
And some of these had been people of note in the world; as,
among others one Giles Barnadiston,
who having spent six years in the university in the study of human literature,
afterwards came to be a colonel; but in process of time,
having heard George Fox the younger preach,
he was so entirely convinced of the Truth declared,
that he laid down his military command and entered
into the society of those called Quakers.
And continuing faithful,
he in time became a minister of the gospel among the said people,
being a man of a meek spirit, and one whom I knew very well.
This Giles Barnadiston did not forbear attending meetings,
regardless how hot the persecution was,
being fully given up to hazard his life with his friends.

One Solomon Fromantle, a merchant, with whom I was well acquainted,
was so grievously beaten that he fell down and lost much of his blood in the street;
and yet the barbarous troopers did not leave off beating him.
His wife, a daughter of the aforesaid Edward Graunt, fearing lest he should be killed,
fell down upon him to cover and protect him from the blows at the hazard of her own body,
as she herself told me in the presence of her said husband--a conjugal
love and fidelity well worthy to be mentioned and left upon record.
And though she then did not receive very fierce blows,
yet there were some women whose lot it was to be sorely beaten by clubs with iron spikes.
Among the rest was an aged widow,
who received no less than twelve such bloody blows on several parts of her body;
and another woman was pierced in her loins with such a spiked club.
An ancient man of sixty-five years was followed a
great way by three men on foot and one on horseback,
and was so beaten and bruised that a woman, pitying this old man,
spoke to these mischievous fellows to cease.
But this so incensed the one who was on horseback that he, with cursing and railing,
gave her a hard blow with his sword on the shoulder.
This barbarity continued until the persecutors seemed
to be more wearied out than the persecuted,
who seemed to grow valiant in these sore tribulations, regardless how grievous.
A great promoter of this furious violence was captain Turner,
who drove his troopers on to act in this manner.
Such was his malice, that once at the breaking up of a meeting,
he not only gave an order to beat the people, but also to destroy the doors, windows,
and walls, so that the damage came to twenty-five pounds.

Now I could enter upon a large relation of the trial of
many prisoners at Worcester before the judges Hide and Terril;
but since this trial was much after the same manner as that of John Crook,
here before-mentioned at length, I will but cursorily make some mention of it.
When the prisoners, being brought to the bar,
asked why they had been kept so long in prison, they were answered with the question,
whether they would take the oath of allegiance,
and endeavors were used to draw some out to accuse themselves,
by asking them where they had been on such-and-such a day.
For if they had said "`at a meeting,`" then it would have appeared
from their own mouth that they had acted contrary to the law;
but they answered cautiously, knowing they were not bound to accuse themselves.
Others by evidence were charged with having been at a meeting;
and when they said that their meetings were not always for public worship,
but that they also held meetings for the care of widows, fatherless,
and others that were needy,
yet it was said to the jury that even though there was no
evidence that there had been any preaching in the meeting,
yet if they did but believe that the prisoners had kept a meeting for religious worship,
it was sufficient to prove the indictment.
And yet such proceedings in other cases would have been thought entirely unwarrantable.

One Edward Bourn being imprisoned for having been at a meeting,
and afterwards brought to his trial, the oath was tendered to him.
Among other words he spoke in his defense, he said,
"`Suppose Christ and His apostles kept a meeting here in this time,
would this act against conventicles also take hold of them?`"
"`Yes,`" said the judge, "`it would.`"
But then, rethinking his response, he said, "`I won`'t answer your questions;
you are no apostles.`"
The conclusion was that Bourn and several of his friends were each fined five pounds.

Now since those that were fined for such things did not generally pay the fines (judging
that the thing for which they were fined was an indispensable duty they owed to God,
and therefore they could not pay any such fine with a good conscience),
the consequence thereof was generally imprisonment and the seizing of their goods,
whereby some lost twice, or even three times as much as the fine amounted to.
Some of the prisoners made it appear clearly that
they had been somewhere else at the time of the meeting,
and not in the house of Robert Smith where it was held;
yet because they gave no satisfactory answer to the question
whether they had not been there at some time that day,
they were declared guilty.
The said Robert Smith was premunired; for the oath of allegiance was tendered to him,
and he (being threatened by the judge with a premunire) asked,
for what purpose the law concerning this oath had been made,
and whether or not it was made for Papists.
And having a suspicion that some of that persuasion were sitting on the bench,
he asked also whether they who were present, for the satisfaction of the people,
ought not also to take the oath.
But the judge waived this, telling him that he must take the oath,
or else sentence would be pronounced against him.
Smith then asked, whether the example of Christ should decide the question;
but the judge said,
"`I have not come here to dispute with you concerning the doctrine of Christ,
but to inform you concerning the doctrine of the law.`"
Then Smith was led away, and afterwards,
when an indictment for his refusing the oath was drawn up,
he was brought into the court again,
and asked whether he would answer to the indictment or not.
But the reasons he gave not being accepted,
the judge (before Smith had finished speaking) said, "`This is your sentence,
and the judgment of the court: You shall be shut out of the king`'s protection,
and forfeit your personal estate to the king forever,
and your real estate during your lifetime.`"
To this Robert said with a composed mind, "`The Lord has given,
and if He allows it to be taken away, His will be done.`"
Thus Robert Smith suffered, with many more of his friends,
both there and elsewhere--all which I believe my life-time
would not be sufficient to describe in detail.

Passing then by the other persecutions of this year,
I will relate one remarkable case that happened in this year, 1663,
where patience triumphed very eminently over violence.
But before I enter upon this narrative, it may not be amiss to go back a little,
and mention some remarkable cases concerning the chief actor
in the story I am going to describe.

His name was Thomas Lurting, who formerly had been an officer on board a man-of-war,
and had often been preserved in imminent dangers.
Once being at the Canary islands under admiral Blake, commander in this expedition,
they defeated the admiral and vice-admiral of the Spanish galleons, and this being done,
he with seven men was sent with a small rowboat to set on
fire the three galleons that remained in the bay.
This order he executed by setting one of them on fire,
which in turn set fire to the other two.
But when returning, and passing by a fort, they received a volley of small gunshot,
by which two men (nearby where Thomas sat) were killed, and a third was shot in his back;
though Thomas received no harm.
Then going out of the bay, they came within about four ships lengths of the castle,
which had forty guns; and when they had come directly in front of the castle,
the guns were fired, and a shot cut the bolt-rope a little above Thomas`'s head,
though without hurting him.
He was eminently preserved in other dangers as well, but that I may not be too tedious,
I will now relate how from a fighting sailor he became a harmless Christian.

About the year 1654, it happened that among the soldiers that were in his ship,
there was one who had been at a meeting of those called Quakers in Scotland,
and there were also two young men in the ship who had some conversation with him;
but this man was soon taken away from this ship.
Yet these two young men seemed to be somewhat convinced of the truth;
for about six months after this, they scrupled to go and hear the priest,
and to put off their hats to the captain,
because of which they came to be called Quakers.
These two often met together in silence, which being observed by others in the ship,
their number soon increased.
But this troubled the captain exceedingly,
and the priest on board also grew not a little angry, and so said to Thomas Lurting,
"`O Thomas, you are an honest man and a good Christian;
but there is a dangerous people on board--the Quakers,
a blasphemous people who deny the ordinances and the word of God.`"
This made Thomas so furious,
that in a bigoted zeal he fell to beating and abusing
these men when they were religiously met together.
But he soon found that this was not the way to have a quiet and sedate mind;
for the remembrance of his former deliverances from death weighed so heavily upon him,
that he found he could no more beat any of the said people.
After this Thomas came to a clearer sight concerning what sort of fellow this priest was;
for when he could no longer abuse the Quakers,
he then was not accounted by the priest either an honest man or a good Christian.
Now, about this time,
feeling himself under condemnation because of the outgoings of his mind from the Lord,
he made many promises to the Lord; but these being made in his own will and strength,
proved to be of little effect.

Among those in the ship who were called Quakers was one Roger Dennis,
whom he loved entirely, and therefore never struck him;
for this man had such an influence on Thomas that, by only looking upon him,
he dared not touch any of the men whom he intended to have abused.
Remaining in this state for some time, and feeling no peace in his mind,
he very much desired to get alone and more freely pour out his heart before the Lord;
and though he then felt himself inwardly condemned,
yet the Lord`'s judgments became pleasant to him,
because thereby his heart was made tender and broken.
In this state he could not forbear sometimes crying out, "`O Lord!`"
But this, being observed by the ship`'s crew, made some say he had gone mad,
and others that he was unwell; and concerning these things some wrote home to England.
Then it fell to his share to be mocked and ridiculed,
but he endeavored to be fully given up to the Lord if he
might but have peace in his conscience with God.

And being alone one evening,
he was very earnest with the Lord to know what people he should join himself to;
and then it was plainly showed him that he must join with the Quakers.
But this so startled him at that time,
that he desired of the Lord rather to die than to live;
for to join with a people whom he had so often beaten
and abused seemed harder to him than death itself.
And by the subtlety of Satan he was often assaulted by various thoughts,
to keep him away from the said people.
But when the Lord made him mindful of his manifold preservations and deliverances,
it mollified his heart, so that at last he came to this resolution:
"`Whether Quaker or no Quaker, I am in need of peace with God.`"
Yet it cost him many a bitter sigh, and many a sorrowful tear,
before he could come to a full resignation.
But the inward reproofs of the Lord, attended with judgments,
followed him so closely that he could no longer forbear, and at last gave up.

He then took the opportunity to expose his heart to his friend Roger Dennis,
who spoke to him in such a way that he received great satisfaction.
But not long after this, temptations again assaulted him in this manner, "`What,
will you join yourself to such a foolish people?`"
And the very thoughts of this were so grievous to him,
that he grew even weary of his life;
for thus to expose himself to scorn seemed an intolerable cross to him.
But he found that this struggling against the truth was not the way to get peace with God.
The First-day of the week having come, he resolved to go to the small meeting,
which was now six in number;
but it being reported that he had met together with the Quakers,
many of the other company left their worship in order to see him,
and there made a great noise.
When their time of worship was over, the captain asked the reason for that noise,
and it was told him, "`Thomas is among the Quakers;`" upon which he sent for him.
There were several officers also present at this time,
but the first who spoke was the priest, saying, "`Thomas,
I took you to be a very honest man, and a good Christian,
but I am sorry you should now be so deluded.`"
And the captain then endeavored to prove from the bible that the Quakers were no Christians.
Thomas in the meantime was still and quiet,
and the others seeing they could not prevail upon him that way,
took another course and offered many false reports
about those called Quakers on board the ship.
But because Thomas knew these accusations to be altogether false,
and saw how they sought to bear him down with lies, he was the more strengthened;
so that going to his friends afterwards, he said to them, "`When I went to the captain,
I was only half a Quaker; but by hearing their lies and false reports,
they have made me almost a whole Quaker; or at least I hope to be one.`"

Continuing to meet with his friends for the performance of worship,
some more came to be joined to them,
so that in less than six months there were twelve men and two boys,
one of whom was the priest`'s son.
Now there were none on board who would abuse the Quakers,
though they were much tried by the captain;
for he incited some men from other ships on purpose to vex them.
But regardless how fiercely these others behaved themselves, a higher power limited them.
At length,
there was a sickness on board the ship which swept away more than forty in a short time.
Most of those who were called Quakers had the distemper also, but none died of it,
though some were brought very low.
They took great care of one another when sick,
and whatever one possessed was given for the use of all.
This care being seen by others, made some of them cry out upon their deathbed,
"`O carry me to the Quakers, for they take great care of one another,
and they will take care of me also.`"
Now this visitation of sickness in the ship so changed the captain,
that he became very kind to Thomas.
And Thomas, seeing him in such a good humor,
requested of him to have use of the cabin for a meeting-place for his friends.
The captain was now so well pleased with him, that when something needed to be done,
he would often say, "`Thomas, take your friends,
and do such-and-such a thing;`" (for as yet, these men were not against fighting,
and therefore were not complete Quakers).
And thus, when Thomas and his friends were sent out on some expedition,
they did their work beyond the captain`'s expectation.
But though they were not yet brought off from fighting, yet when, with others,
they marched against their enemies, they would take none of the plunder.
In all these contests they received no hurt,
though several others were killed and wounded;
and they behaved themselves so valiantly that their captain would say to other captains,
that he cared not if all his men were Quakers,
for they were the hardiest men in his ship.
But though this was a time of outward peace,
yet Thomas looked upon it as a forerunner of further exercise;
for he saw what was done to him now in pretended friendship,
was only to serve their own ends; and therefore he expected a time of trial would come,
and so it did.

For having come to Leghorn,
they were ordered to go to Barcelona in order to take or burn a Spanish man-of-war.
Their command was then to lie against a castle and batter it, which they did,
and those called Quakers fought with as much courage as any.
And finding that one corner of the castle began firing some shot into their ship,
Thomas was for battering down that part.
He then, being stripped to his waistcoat, and going into the forepart of the deck,
began to level the guns, but said, "`Do not fire,
until I go out and see from where they are shooting,
that we may so aim our guns higher or lower.`"
But as he was coming out to see from where the enemy`'s shots proceeded,
it suddenly run through him, "`What if you now kill a man?`"
This struck him as a thunderbolt; and He that can turn men`'s hearts at His pleasure,
changed his in a minute`'s time to such a degree that,
whereas just before he had employed all his strength to kill men,
he now found in himself no will thereto at all, though it were to gain the world;
for he immediately perceived that this conviction came from the Lord.
Then, putting on his clothes,
he walked upon the deck as if he had not seen the guns being fired,
and being under great exercise of mind, some asked him if he was hurt.
He answered, "`No;
but I am under some scruples of conscience on account of fighting,`"
though at this time he knew not that the Quakers refused to fight.

When night came, they went out of the range of the castle guns,
and he took occasion to speak with two of his friends in the ship,
inquiring their judgment concerning fighting.
His friends gave little answer, but said however, "`If the Lord sends us well home,
we will never do it again.`"
To this Thomas replied, that if he stood honest to the gift of God in his own conscience,
and they were sent to fight tomorrow,
then with the Lord`'s assistance he would bear his testimony against it;
for he clearly saw, that though they had been such great actors in fighting before,
they must now bear their testimony against it, and wait to see what the outcome would be;
saying among themselves, "`The will of the Lord be done.`"
The next day they heard that several had been killed on shore,
which grieved Thomas not a little.
Some time after this,
one of Thomas`'s friends went to the captain requesting to be discharged.
The captain asking why, his answer was that he could fight no longer.
To this the captain said, "`If anyone denies to fight in a time of engagement,
I will put my sword into his guts.`"
"`Then,`" said the other, "`you will be a man-slayer,
and guilty of shedding blood;`" for which the captain (who was
also a Baptist preacher) beat him sorely with his fist and cane;
so that he who had been their friend, now became their open enemy.

Some time after this, about the year 1665, being at Leghorn,
they were ordered to go cruising,^
footnote:[i.e. sailing back and forth in search of enemy ships.]
and one morning spied a great ship bearing down upon them,
which they supposed to be a Spanish man-of-war.
Orders were immediately given to clear the ship and prepare to fight.
Thomas then being upon the deck, saw plainly that a time of trial had now come,
and he prayed to the Lord very earnestly for strength.
That which then seemed most expedient to him was to meet together with his friends,
which, after notice given, was done accordingly.
Having come together, he told them how it was with him,
and that things seemed very dark and cloudy;
yet his hope was that the Lord would deliver him, and all such who were of his faith;
to which he added, "`I do not lay this as an injunction upon anyone,
but leave you all to the Lord.`"
Moreover he said, "`I must tell you, that the captain puts great confidence in you.
Therefore let us be careful that we give him no just occasion for offense.
And all that are of my mind, let us meet in the most public place upon the deck,
in full view of the captain,
that he may not say we deceived him by not telling him that we would not fight,
so that he might have put others in our place.`"

Then Thomas went upon the deck and stood with his back against the capstan,^
footnote:[A capstan is a vertical-axled rotating machine developed for use on
sailing ships to multiply the pulling force of seamen when pulling ropes.]
and a little after, turning his head, he saw his friends come up behind him.
At the sight of this, though he rejoiced, yet his heart rolled within him for them,
feeling that they stood there as sheep ready for the slaughter.
Within a little time the lieutenant came and said to one of them,
"`Go down to your quarters;`" to which the man replied, "`I can fight no more.`"
The lieutenant then going to the captain, made the worst of it, saying,
"`The Quakers are all together, and it may be that they will mutiny;
and one says he cannot fight.`"
The captain having asked his name, came down to him, flung his hat overboard, and then,
taking hold of his collar,
beat him with a great cane and dragged him down to his quarters.
He then went upon the deck again and called for his sword,
which his servant having brought him, he drew with great fury.
No sooner was this done, but the word of the Lord (as Thomas took it) ran through him,
saying, "`The sword of the Lord is over him; and if he desires a sacrifice,
offer it to him.`"
This word ran so powerfully through him, that Thomas quivered and shook,
though he endeavored to stop it, fearing they would think he was afraid,
which he was not.
Then, turning his head over his shoulder, he said to his friend Roger,
"`I must go to the captain.`"
To which Roger replied, "`Be certain you know what you do.`"
And Thomas replied, "`A necessity is laid upon me.`"
Then seeing the captain coming towards them with his drawn sword,
Thomas fixed his eye with great seriousness upon him and stepped towards him,
keeping his eyes upon him in much dread of the Lord,
feeling himself to be lifted up above his furious looks.
At this the captain`'s countenance suddenly turned pale, and he, turning himself around,
called to his servant to take away his sword, and so he went off.
Not long after, the ship with which they expected to fight proved to be a Genoese,
their friend;
and before night the captain sent the priest to Thomas
requesting him to excuse his anger,
saying he had acted in passion.
To this Thomas`'s answer was that he had nothing but good will to him;
and he bade the priest to tell the captain to beware of such passions,
for if he killed a man in his passion,
he might seek for repentance and perhaps not find it.
Thus Thomas overcame this storm, and at length got safe home.

Then, leaving military vessels, he afterwards went to sea in a trading ship;
but it then fell to be his lot several times to be forced into the king`'s service;
and so being carried into a man-of-war, he suffered very much.
Once he fasted five days, taking at times only a swallow of water,
for he could easily see that if he had eaten of their food,
it would have gone worse with him; for he scrupled to do any ship-work,
though it was not active fighting,
for he judged this to be an assistance to those whose business it was to fight.
Therefore, in such a ship, he found he could do almost nothing, whatever it was,
without helping and assisting in war.

In this condition he met with several rude occurrences for some years together.
Being once at Harwich, hard at work in a ship,
heaving out corn into a small flat-bottomed boat,
he was drafted into the king`'s service.
But one of the men there saying he was a Quaker, the captain,
who with his boat had come aboard, said in a scoffing manner to him, "`You are no Quaker,
for if you were a Quaker, you would be waiting upon the Lord,
and letting His ravens feed you,
and not toiling with your body;`" for Thomas being stripped down to his shirt and drawers,
his shirt was wet with sweat.
Being a little time silent, at length Thomas said to the captain,
"`I perceive you have read some part of the scriptures.
Did you ever read that he is worse than an infidel who will not provide for his family?
I have often heard the Quakers blamed for not working,
but you are the first who ever I heard blame them for working.`"
At this the captain said, "`Take him away, he is a Quaker!`"
But a little after this he cried, "`Bring him to me again; he is no Quaker.`"
Then he said to Thomas, "`You are no Quaker, for here you bring corn,
and from it bread is made, and by the strength of that bread we kill the Dutch.
You are therefore no Quaker.
Or are you not just as accessory to their deaths as we?
Answer me.`"
Thomas, not immediately replying, was much scoffed and jeered by the seamen;
but at length he said to the captain, "`I am a man that can feed my enemies,
and so may I feed you, who pretend to be my friends.`"
To which the captain replied, "`Take him away, he is a Quaker!`"

But a few days after he was forced again out of the same trading vessel,
and carried on board a man-of-war.
There he was ordered to go into the cabin, where the captain and several officers were.
Having entered, the captain began to curse the Quakers,
and swore that if he did not hang Thomas, he would carry him to the duke of York,
and surely he would.
But Thomas said very little, and felt himself kept by the Lord from fear.
And when the captain had tired himself with clamoring and railing, he said more mildly,
"`What, do you say nothing for yourself?`"
To this Thomas answered,
"`You say enough for yourself and for me too;`" for he found it most safe to say little.
This was indeed the best way; for generally no reasons, however good,
avail with passionate men,
who often think it below them to hearken to what
is said by one they look upon to be their inferior.
But these sometimes find they reckon amiss, as this captain did, who,
notwithstanding his haughtiness, was soon struck by a superior power.
For the very next night a sudden cry was heard, "`Where is the Quaker?
Where is the Quaker?`"
Thomas hearing this, said, "`Here I am.
What is needed at this time of the night?`"
To which it was told him, "`You must come to the captain immediately.`"
He then coming to the cabin door, the captain said, "`Is the Quaker there?`"
Thomas answering, "`Yes,`" the captain said, "`I cannot sleep.
You must go on shore.`"
Thomas replied, "`I am in your power, and you may do with me as you please.`"
So with the boat he was put on shore at Harwich, by order of the captain,
who in his fury had previously said that hanging was too good for him.
But now, because his mind was disquieted, he could not sleep, though Thomas,
who lay on the hard boards, slept very well.

Having said thus much of this seaman, let us now behold how,
and in what an industrious manner he retook a ship that was taken by a pirate,
without passing the bounds of a peaceable disposition.
This happened in the year 1663, after this manner:

About the month of October, a master of a ship whose name was George Pattison,
one of the society of those called Quakers,
being with his ship in the Mediterranean on their way from Venice,
near the island of Majorca, was chased by a pirate of Algiers;
and because their vessel was sailing well, they endeavored to escape.
However, by carrying too much sail, some of their equipment gave way,
by which means the Turks came up along side of them
and commanded the master to come on board their ship,
who accordingly, with four other men, went in the small boat,
leaving only his mate (the before-mentioned Thomas
Lurting,) with three men and a boy on board his vessel.
As soon as these Englishmen came on board the pirate ship,
the Turks put thirteen or fourteen of their men into
the boat to return to the English ship.
In the meantime Thomas was under great exercise of mind,
and more so because the master with four of his men were then with the Turks,
and those that were left on board the vessel were somewhat unruly.
In this concern, however, he believed it was told him inwardly by the Lord,
"`Be not afraid, for you shall not go as prisoners to Algiers.`"
And having had great experience formerly of the Lord`'s deliverances,
as has been mentioned above,
he had already learned to trust in God despite all outward appearances.
Upon consideration of this, all fear was removed from him,
and going to the ship`'s side to see the Turks come in,
he received them as if they were his friends, and they also behaved themselves civilly.
He then showed them all the parts of the vessel, and what she was loaded with.
Afterwards he said to the men that were with him, "`Be not afraid,
for despite all this we shall not go to Algiers.
But let me request of you that, as you have been willing to obey me,
so now to be as willing to obey the Turks.`"
This they promised him, and by so doing,
he soon perceived they gained favor with the Turks; for seeing the seamen`'s diligence,
they grew the more careless and favorable to them.
And having taken a small amount of the cargo, some of them went again to their own ship,
and eight Turks stayed with the English.

Then Thomas began to think of the master,
and the other four that were in the Turk`'s ship.
As for himself and the others with him, he had no fear at all; indeed,
he was so far from it, that he said to one of his men, "`Were the master but on board,
and the rest of our men, then if there were twice as many Turks, I would not fear them.`"
By this he encouraged the seamen, who not being of his religious persuasion,
thought much differently than he,
and would have been willing enough to have killed the Turks if they had seen an opportunity.
In the meantime,
Thomas`' earnest desire to the Lord was that he would put it into
the heart of the Turks to send the master and the four others back.
And his desire was answered; for soon after this,
the master and those men were sent back on board.

Then all manner of fear concerning going to Algiers was taken away from him,
which made some say he was a strange man, since he was afraid before he was taken,
but now he was not.
For before they were taken, he having heard there were many Turks at sea,
endeavored to persuade the master to go to Leghorn and to wait there for a convoy.
But to this the master would not agree.
Therefore, to answer the seamen who thought his behavior strange, Thomas said to them,
"`I now believe I shall not go to Algiers; and if you will remain under my direction,
I will act for your delivery as well as my own.`"
However, though he spoke thus boldly, yet he saw no way for their deliverance;
for the Turks were all armed, and the English were without arms.

At one time when the English were all together, except for the master,
Thomas said to them, "`What if we should overcome the Turks, and then go to Majorca.`"
At this the crew very much rejoiced, and one said,
"`I will kill one or two;`" "`And I,`" said another,
"`will cut as many of their throats as you will have me.`"
But at these sayings Thomas was much troubled, for he intended not to hurt any of them,
and therefore told the men, "`If I knew that any of you would touch a Turk to hurt them,
I would tell it the Turks myself.
But,`" said he, "`if you will submit to my direction, I will act for you.
If not, I will be still.`"
The others, seeing that he would not allow them to take their own course,
agreed to do what he desired of them.
"`Well then,`" said he, "`if the Turks bid you do anything, do it without grumbling,
and with as much diligence and quickness as you can, for that pleases them,
and will cause them to let us remain together.`"
To this the men all agreed.
Thomas then went to the master and told him their intention.
But the master replied, "`If we rise up against them, and they overcome us,
we had as good be burnt alive.`"
Thomas knew very well the master was in the right, namely,
that if they failed in the attempt,
they were likely to meet with the most cruel treatment
from the Turks that could be imagined.
Now the reason why the master, though a very bold-spirited man,
did not readily consent to the proposal, was because he feared they would shed blood.
But Thomas told him that they were resolved to do it without shedding one drop of blood;
"`And besides,`" he said, "`I would rather go to Algiers, than to kill one Turk.`"
Speaking thus,
he so swayed the master that he at last agreed to let him do what he would,
provided they killed no one.

Now since two Turks remained in the cabin with the master,
it was agreed that he should continue to lie there, lest they should suspect something.
In the meantime it began to be bad weather,
so that they lost the company of the Turkish man-of-war,
which was the thing that Thomas much desired.
And the Turks seeing the diligence of the English sailors, grew careless concerning them,
which was also what Thomas aimed at.
The second night after this,
the captain of the Turks and one of his company went
to sleep in the cabin with the master.
Thomas then persuaded one to lie in his cabin,
and about an hour afterwards another in another cabin; and at last,
because it was raining very much, he persuaded them all to lie down and sleep.
When they were all asleep, he came to them and got their arms into his possession.
This being done, he told his men, "`Now we have the Turks at our command,
but no man shall hurt any of them; for if you do, I will be against you.
But this we will do, now that they are under the deck, we will keep them there,
and go to Majorca.`"
And having ordered some to guard the doors, they steered their course to Majorca,
and because there was then such a strong gale, in the morning they drew near it.
Then Thomas ordered his men, that if any of the Turks desired to come out,
let it not be above one or two at a time; and when one came out,
expecting to have seen his own country,
he was not a little astonished instead thereof to see Majorca.
Then Thomas said to his men, "`Be careful now of the door,
for when he goes in and speaks to the rest we shall see what they will do.
But have a care not to spill any blood.`"
The Turk having gone down to the cabin and told his comrades what he had seen,
and how they were going to Majorca, they, instead of rising up, all fell to crying,
for their courage was quite sunk;
and they begged the English that they might not be sold as slaves.
This Thomas promised them, saying they would not be sold.
And when he had appeased them, he went into the cabin to the master,
who as yet knew nothing of what had been done,
and gave him an account of the sudden change, and how they had overcome the Turks.
And understanding now what had taken place,
he informed the captain of the Turks that the vessel was now no more in their possession,
but in his again; and that they were going to Majorca.
At this unexpected news the Turkish captain wept,
and requested the master not to sell him; which he promised he would not.
They then told him also, they would make a place to hide them in,
so that the Spaniards who came aboard would not find them.
And so they did accordingly, at which the Turks were very glad.

Having come into the port of Majorca, the master, with four men, went ashore,
and left Thomas on board with ten Turks.
The master having finished his business, returned on board, not taking a license,
lest the Spaniards should come on board and see the Turks.
But another English master, being an acquaintance, lying in the same port with his ship,
came at night on board; and after some discourse, they told him what they had done,
under promise of silence, lest the Spaniards should come and take away the Turks.
But this man broke his promise,
for he desired to have two or three of the Turks to bring them to England;
but his design being seen, his demand was denied, and seeing he could not prevail,
he said to Pattison and his mate that they were fools,
because they would not sell the Turks,
which were each worth two or three hundred pieces of silver.
But they told him, that if they were offered many thousands, they could not have one,
for they hoped to send them home again; "`And,`" said Thomas,
"`I would not sell them for the whole island.`"

The other master then coming ashore, told the Spaniards what he knew,
who then threatened to take away the Turks.
But Pattison and his mate having heard this, called together the Turks and said to them,
"`You must help us, or the Spaniards will take you from us.`"
Hearing this, the Turks, as one may easily guess, were very ready to assist,
and so they quickly got out to sea.
And the English, in order to save the Turks,
put themselves at risk of being overcome again by them,
for they continued hovering several days because they would
not put into any port of Spain for fear of losing the Turks.
For four or five days the Turks were given liberty,
until they made an attempt to rise up against the English, which Thomas perceiving,
he prevented, without hurting any of them, though he once had to lay hold of one.
Yet generally he was so kind to them,
that some of his men grumbled and said he had more care for the Turks than for them.
To which his answer was, they were strangers, and therefore he must treat them well.
At length, after several occurrences,
Thomas told the master that he thought it best to go to the coasts of Barbary,
because they were then likely to avoid their men-of-war.
To this the master consented.
However, to deceive the Turks, they sailed to and fro for several days;
for in the daytime they were going towards Algiers,
but when night came they steered the contrary way, and went back again,
by which means they kept the Turks in ignorance, so as to be quiet.

But on the 9th day, being all upon deck,
when none of the English were there but the master, his mate, and the man at the helm,
the turks began to be so obstinate and haughty, that it rose in Thomas`' mind,
what if they should lay hold of the master and cast him overboard?
For they were ten lusty men, and the captain but a little man.
This thought struck him with terror, but recollecting himself, and taking heart,
he stamped with his foot to call the men up upon the deck,
whereupon one asked for a crowbar, and another for the axe,
in order to fall upon the Turks.
But Thomas ordered them not to hurt any, and said,
"`I will lay hold on their captain,`" which he did.
For having heard them threaten the master, he stepped forward,
and laying hold of their captain, he told him he must go down below,
which he did very quietly, with all the rest following him.

Two days after, this, having come to the coast of Barbary,
they were (according to what the Turks said) about fifty miles from Algiers,
and six from land.
In the afternoon the sea became calm,
but how to set the Turks on shore was yet not resolved upon.
Thomas saw well enough that, since he was the man who had begun this business,
it would be his lot also to bring it to an end.
He then acquainted the master that he was willing to carry the Turks on shore;
but how to do this safely, he did not yet know;
for to give them the small boat was too dangerous,
for then they might gather more men and arms,
and so come and retake the ship with its own boat.
To carry them on shore with two or three of the ship`'s men was also a great hazard,
because the Turks were ten in number.
And to put one half on shore was no less dangerous;
for then they might alert the men of the country,
and so surprise the English when they came with the other half.
In this great strait Thomas said to the master,
"`If you will let me have the small boat and three men to go with me,
I will venture to put the Turks on shore.`"
The master, relying perhaps on his mate`'s conduct, consented to the proposal,
though not without some tears dropped on both sides.
Yet Thomas taking courage, said to the master, "`I believe the Lord will preserve me,
for I have nothing but good-will in venturing my life,
and I have not the least fear upon me, but trust that all will be well.`"

Having received the master`'s consent, Thomas called up the Turks,
and going with two men and a boy into the small boat, took in these ten Turks,
all loose and unbound.
Perhaps somebody will think this to be a very inconsiderate act,
and that it would have been more prudent to have tied the Turks`' hands,
especially because he had made his men promise they
would do nothing to them without his leave,
giving them all freedom to act on behalf of their own lives as they judged convenient.
For since he knew not how near he would be able bring the Turks to the shore,
and whether they would not have to swim a little,
it seemed not prudent to do anything which might exasperated them;
for if it happened that they would have to swim, they would then need to be untied,
which would be dangerous.
Yet Thomas did not omit to be as careful as he possibly could.
For calling in the captain of the Turks, he placed him first in the boat`'s stern;
then calling for another, he placed him on his lap, and then one on each side,
and two more on their laps, until he had placed them all,
which he did to prevent their ability to make a sudden uprising.
He himself sat with a boat-hook in his hand on the bow of the boat,
having next to him one of the shipmen, and two that rowed,
one having a carpenter`'s chisel, and the other a drawknife.
These were all the arms they carried, besides those that belonged to the Turks,
which they had in their possession.
Thus the boat went off, and headed for the shore.
But as they came near it, the English men grew afraid,
and one of them cried out suddenly, "`Lord have mercy on us,
there are Turks in the bushes on shore!`"
The Turks in the boat perceiving the English to be afraid, all rose at once.
But Thomas, who in this great strait continued to be undaunted,
and showed himself now to be a man of courage.
He then bid the men to take up such arms as they had,
but to do nothing with them until he gave them permission.
And then, seeing that there were no men in the bushes,
and that it was only the other`'s imagination, all fear was taken away from him.
His courage increasing, he thought with himself, "`It is better to strike a man,
than to cleave his head;`" and so turning the boat-hook in his hand,
he struck the captain a smart blow, and bid him to set down, which he did instantly,
and so did all the rest.
After the boat had come so near the shore that they could easily wade in the sea,
the mate bid the Turks jump out, and so they did;
and because they said they were about four miles from a town, he gave them some loaves,
and other necessaries.

They would eagerly have persuaded the English to go with them ashore to a town,
promising to treat them with wine and other good things;
but though Thomas trusted in Divine Providence,
yet he was not so careless as to freely enter into apparent
danger without there being any necessity for it.
For though he then believed that the Turks would not have done him any evil,
yet it seemed too hazardous to thus yield to the mercy of those that lived there;
and therefore he very prudently rejected their invitation,
well knowing that the Scripture says, "`You shall not tempt the Lord your God.`"
The Turks seeing they could not persuade him,
took their leave with signs of great kindness, and so went on shore.
The English then putting the boat closer in, threw all their arms on shore,
being unwilling to keep anything of theirs.
And when the Turks got up upon a hill, they waved their caps at the English,
and so joyfully took their last farewell.
And as soon as the small boat came again on board the ship, they had a fair wind,
which they had not all the while the Turks were on board.
Thus Thomas Lurting saved the ship and its men; which being thus wonderfully preserved,
returned to England with a prosperous wind.

Now before the vessel arrived at London,
the news of this extraordinary case had already come there;
and when she was coming up the Thames, it was told to the king, the duke of York,
and several lords who were at Greenwich,
that there was a Quaker`'s vessel coming up the river that had been taken by the Turks,
and who had redeemed themselves without fighting.
The king hearing this, came with his barge to the ship`'s side,
and holding the entering rope in his hand,
he heard from Thomas`' own mouth how the thing had happened.
But when he heard him say how they had let the Turks go free, he said to the master,
"`You have done like a fool, for you might have had good gain for them.`"
And to Thomas he said, "`You should have brought the Turks to me.`"
But Thomas answered, "`I thought it better for them to be in their own country.`"
At this the king and others smiled, and so went away,
thinking that the master had done foolishly.
But he and his mate were of another opinion,
and thus they made it appear that they approved the lesson of our Savior,
"`Love your enemies, and do good to those that hate you,`" not only with their mouths,
but also with their deeds.

Though I have described these facts from a printed relation,
yet I have added some circumstances from the mouth of Thomas Lurting,
with whom I had some acquaintance.

Several years afterwards,
when some seamen of the people called Quakers were in slavery at Algiers,
G+++.+++ Fox wrote a book to the grand sultan, and the king at Algiers,
wherein he laid before them their indecent behavior, and unreasonable dealings,
showing them from their Koran that this displeased God,
and that Mahomet had given them other directions.
To this he added a succinct narrative of what has been related
here of George Pattison`'s ship being taken and retaken,
and how the Turks were set at liberty without being made slaves,
by which the Mahometans might see what kind of Christians the Quakers were, that is,
such as showed effectually that they loved their enemies,
according to the doctrine of their supreme lawgiver, Christ.

Now concerning those Quakers at Algiers,
of whom mention has been made that they were slaves there,
it was a pretty long time before opportunity was found to redeem them.
But in the meantime,
they so faithfully served their masters that they
were allowed to go loose through the town,
without being chained or fettered;
and liberty was also allowed them to meet at set times for religious worship.
Their masters themselves would sometimes come and see what they did in these meetings,
and finding no images or pictures (such as the Papist
slaves made use of in the exercise of their worship),
but seeing rather that these slaves reverently adored and worshipped the living God,
the Creator of Heaven and Earth, they commended them for it, and said it was very good,
and that they might freely do so.
And since one of them was raised up to speak by way of edification to his friends,
some other English slaves attending their meeting came to be united with them.
In the meantime the Quakers`' name came to be known at Algiers
as a people that might be trusted beyond others.

It was in this year that William Caton went to England
with his wife from Holland (where he had been married),
and two other friends, one of which was Judith Zinspenning, my mother,
who was moved to speak at the meeting at Kingston,
where William Caton interpreted for her.
At another time being in a meeting at London, W. Caton not being present,
and feeling herself stirred up to declare of the lovingkindness
of the Lord to those that feared Him,
she desired one Peter Sybrands to be her interpreter; but he, though an honest man,
was not very fit for that service.
Nevertheless,
one or more friends told her that they were so sensible of the power by which she spoke,
that though they did not understand her words,
yet they were edified by the life and power that accompanied her speech,
and therefore the lack of interpretation mattered little;
and so she went on without any interpreter.
She had indeed a very good gift, and left such a savor behind her,
that I coming into England several years after this,
kindness was showed to me in several places on her account.
After a stay of some weeks at London and thereabouts,
she went to Colchester in order to return with W. Caton`'s wife to Holland.
But first making some stay in that town, she there wrote a book of proverbs, which,
W+++.+++ Caton having translated into English, was printed at London.
After her departure for Holland, Caton stayed behind, travelled through Essex,
Warwickshire, Staffordshire, Derbyshire, Nottinghamshire, and Yorkshire;
and then coming into Lancashire, he returned to Swarthmore,
and found there not only his ancient mistress, Margaret Fell,
who received him very kindly, but also G. Fox, not long before he was taken prisoner.

From there Caton went to Sunderland, and so to Scarborough, where,
meeting with a vessel bound for Holland, he embarked and went off with a fair wind.
But it was not long before the wind changed, and being about ten leagues from the land,
the sky began to look tempestuous.
This made Caton advise the master to return,
but he thinking the weather would soon change, was unwilling to do so.
Yet it happened that soon a violent storm arose,
by which the ship was so exceedingly tossed,
that she grew leaky and took on so much water that
the pumps had to continually be kept going.
This so wearied the seamen, that Caton also began pumping;
for though he found himself prepared to meet death if it had been the will of the Lord,
yet he knew it to be the duty of a man to preserve his life by lawful means,
as long as possible.
Besides, he pitied the poor seamen,
and so was made willing to help them as much as lay in his power.
But at length they lost the use of the rudder, and drew near the sands and shallows,
by which the danger greatly increased, and death seemed to approach.

Now Caton, though given up in the will of the Lord,
and prepared to have found his grave in the deep, yet did not omit to call upon the Lord,
and to pray to the Most High for deliverance, if it were consistent with His holy will.
And when the storm was at its highest, his supplication was heard,
and the tempest all the sudden began to cease and the wind to abate.
This indeed gave him occasion to praise the Almighty for
the great mercy showed to himself and to the mariners.
Yet the wind being contrary, the master then resolved to enter Yarmouth,
at which place Caton met with another kind of storm.
For on the First-day of the week, being at a meeting of his friends,
he with seven more were apprehended and carried to the main guard.
The next day they were brought before the bailiffs of the town,
who tendered them the oath of allegiance; which they refusing to take,
were sent to prison, where he was kept more than six months.
Thus it was not until the next year that he returned into Holland.

While he was in jail at Yarmouth,
Stephen Crisp came the first time into Holland to visit his friends there,
and to edify them with his gift.
It would not be amiss here to say a little of Stephen Crisp`'s qualifications.
He was a man of notable natural abilities,
and had been zealous for religion before he ever
entered into fellowship with those called Quakers.
But when the report of this people spread abroad in the place where he lived,
he made inquiry after them and their doctrine,
and though he heard nothing but evil spoken of them,
it nevertheless made some impression upon his mind
when he considered how they were derided,
hated, slandered, and persecuted,
knowing that this generally had been the lot of those that truly feared God.
But having heard that one of their tenets was that sin might be overcome in this life,
this seemed to him to be a great error.
And therefore, when young James Parnell came to Colchester,
Stephen armed himself with arguments to earnestly oppose him;
and looking upon him as one who was but a youth,
he thought he should be able to prevail upon him.
Stephen Crisp was then about twenty-seven years of age,
being not only well-versed in sacred writ,
but also in the writings of many of the ancient philosophers.

After he had heard Parnell preach very powerfully,
and found his words more piercing than he had imagined,
he ventured to oppose him with some queries;
but he soon found that this young man was endued with sound judgment,
and with all his wisdom and knowledge Crisp was not able to resist him,
but was forced to submit to the truth that he held forth.
He then thought himself so enriched by this new understanding,
that for a month or two he made it his business, by the strength of his own reason,
to defend the Truth which he had embraced.
But he soon found that this was not sufficient;
for self was not yet subdued under the cross,
and he had not yet come to an experiential knowledge
of what he asserted and defended with words.
In this condition he saw that he must truly become poor in spirit,
if God ever would enrich him with heavenly wisdom.
This brought him to mourning and sorrow,
by which he came more and more to be weaned from his natural knowledge,
wherein he used to delight.
And continuing faithful in this way of self-denial,
he at length began to enjoy peace in his mind,
and so advanced in virtue and real knowledge,
that in time he became an eminent minister of the gospel; and traveling to and fro,
many were converted by his ministry.

About this time appeared in England, one Lodowick Muggleton,
who pretended that he and one John Reeves were the two witnesses which are spoken
of in Revelation 11:3. And though it was not long before Reeves died,
yet Muggleton continued in his wild imaginations, which grew to such a degree,
that he gave forth a paper in which he said that he was "`the chief
judge in the world,`" who was commissioned to pass the sentence
of eternal death and damnation upon the souls and bodies of men.
He further claimed, that in obedience to his commission,
he had already cursed and damned many hundreds of people both body and soul,
away from the presence of God, both elect men and angels, for all eternity;
and that neither the Spirit of Christ, nor any god,
could or would be able to deliver from his sentence and curse.
These abominable blasphemies he gave forth in public.

Richard Farnsworth, a zealous and intelligent minister among those called Quakers,
answered this blasphemer in writing,
and uncovered the horribleness of his profane and cursed doctrines and positions.
In a book he published in print, he said, among other things,
"`Consider the nature of your offense, and how far it extends; and that is,
to pass the sentence of eternal death and damnation both
upon the bodies and souls of men and women to all eternity.
Consider that your injustice, done under the pretense of a heavenly office,
deserves to have a punishment proportionable to the offense;
and can this offense in the eyes of the Lord be any
less than a sin against the Holy Spirit,
because you have pretended to do it in the name of the Holy Spirit,
and so would make the Holy Spirit the author of your offense, which He is not?
And seeing you are guilty of a sin against the Holy Spirit,
there is a punishment already proportioned for such an offense;
and you are also punishable by the law of the land for presuming,
under pretense of a commission, and as a judge,
to pass the sentence of death upon the bodies of men and women,
claiming a certain authority in so doing, as the judges of the land do.`"
Thus continued Farnsworth to answer Muggleton at length,
showing him how his judgment was not only contrary to truth,
but also against the law of the land.
But Muggleton was daring enough to give a reply to this serious answer, and said in it,
that he would commend Farnsworth, first, for setting his name to it; and, secondly,
for setting down his words so truly and punctually,
that it made his commission and authority shine the more bright and clear.
He then insisted that he was indeed "`as true an ambassador of God,
and judge of all men`'s spiritual estate,
as any ever has been since the creation of the world.
And if you Quakers, and others,`" he continued,
"`can prove that there never was any man commissioned of God to bless and curse,
then you shall all escape the curse I have pronounced upon so many hundreds;
and I only shall suffer for cursing others without a commission from God.
However, my commission is no pretended thing, but is as true as Moses`'s, the prophets`',
and the apostles`' commissions were.`"

A multitude more abominations this blasphemer belched out, and among the rest,
the claim that no man could come to the assurance of the favor of God,
but by believing that God gave this power unto John Reeves and himself;
that he had power given him over all other gods and infinite spirits whatsoever;
that he (Muggleton) had the keys of heaven and of hell,
and that none could get into heaven, except he opened the gates.
He also alleged to have power to remit the sins of those who received his doctrine,
and to retain and bind the sins of others,
for their despising or not receiving his doctrine.
He said that he was unique in doctrine, knowledge, judgment, and power, above all men,
either prophets, or apostles, since the beginning of the world,
or that should be hereafter while the world does endure;
and that there was no true minister, messenger,
or ambassador of God in the world besides himself,
neither would there be any more sent of God after him to the world`'s end.
Furthermore, he claimed that a God outside of him, had spoken to him by a voice of words,
to the hearing of the ear,
and that no person who had been condemned by him could make an appeal unto God,
either by himself, or by any other, because God was not in the world at all.
"`This power to condemn,`" he says "`God has given unto me,
and in this regard I am the only and alone judge concerning
what shall become of men and women after death;
neither shall those that are damned by me, see any other god or judge but me.`"
I am reluctant to transcribe more of these most horrible blasphemies,
and we have cause to wonder at the long forbearance of God,
that He thus bore the disdainful affront offered by this
inhuman monster in defiance of His Almightiness.

This Muggleton also said to Richard Farnsworth that,
because he was not yet under the sentence of his curse by verbal words or writing,
he would give an answer to his letter.
"`For,`" said he,
"`I never give answers in writing to anyone that is under the sentence of my condemnation.`"
This contrivance,
claiming not to be bound to answer when he had shut up anyone under his pretended damnation,
seemed comical and facetious.
Yet Farnsworth did not fail to answer his blasphemous positions publicly,
and to show the absurdity of Muggleton and John Reeve`'s being the two witnesses.

Hereafter I shall have occasion again to make mention of this Muggleton,
for he lived yet several years;
and I do not find that any punishment was inflicted
upon him by the magistrates other than the stocks,
and a half a year`'s imprisonment;
though many think (not without good reason) that such blasphemers
ought to be secluded from interaction with other men.

Francis Howgill, in the latter part of this year,
being about his business in the market at Kendal, in Westmorland,
was summoned by the high constable to appear before the justices of the peace at a tavern;
for, being a zealous preacher among those called Quakers,
occasion was sought to imprison him under some pretense of justice, however unjust.
Having come to the place appointed, the oath of allegiance was tendered to him;
and because for conscience-sake he refused to swear,
they committed him to prison till the court session at Appleby.
Then appearing at Appleby, the same oath was tendered to him in court by the judges,
and remaining unwilling to take it,
he was indicted and given liberty to answer to the indictment at the next court session.
In the meantime, there was a jail delivery^
footnote:[A collective acquittal of a large number of prisoners,
as a result of either lax or reckless administration of the law, or defects in the law.]
at Appleby, and he was required to enter into bond for his good behavior.
But well knowing that this was only a snare to bring him into further bonds, he refused,
and so was recommitted to prison.
And not being tried until the following year, we shall leave him there.

About this time happened a remarkable case, which I cannot well pass by unmentioned.
One Oliver Atherton, a man of a weak constitution,
having refused to pay tithes to the countess of Derby (who laid claim
to the ecclesiastical revenues of the parish of Ormskirk where he lived),
was by her prosecution imprisoned at Derby in a wet and unwholesome hole.
This imprisonment so weakened him, that after having lain there two years and a half,
he grew sick; and a letter was written in his name to the countess,
in which was laid before her not only the cause why
he had refused the payment of tithes (namely,
for conscience-sake),
but also that his life was in danger if he stayed longer in that unwholesome prison.
It was therefore requested that she show compassion,
lest she draw down the guilt of innocent blood upon her.

Now though Oliver`'s son, who brought this letter,
met with rough treatment for not uncovering his head,
yet the letter was delivered into her own hands.
Nevertheless, the countess continued hard-hearted.
Godfrey Atherton, the son,
returned to his father in prison and told him (who was now on his death bed),
that the countess would not allow him any liberty.
To which he said, "`She has been the cause of much bloodshed;
but this will be the heaviest blood to her that she ever spilled.`"
And not long after this he died.
His friends having gotten his corpse, carried it to Ormskirk; but at Garstang, Preston,
and other towns they past along the way,
they fastened to the market cross the following inscription,
which also had been put on his coffin.

This is Oliver Atherton from the parish of Ormskirk,
who by the countess of Derby has been persecuted to death
for keeping a good conscience towards God and Christ,
in not paying tithes to her.

Now, though three others who with Oliver were imprisoned for the same cause,
gave notice of this to the countess,
hoping that they might not likewise die in prison as their fellow prisoner had,
yet she would show no pity;
and also threatened to accuse those at Garstang before the king and his council,
for allowing the said inscription to be put up.
But by this she opened the people`'s mouth`'s all the more,
and an omnipotent hand prevented the executing of her threat;
for exactly three weeks after the day Atherton was buried, she died.

This year also in October, Humphrey Smith, a preacher among those called Quakers,
having been prisoner a year at Winchester prison for his religion,
was by death delivered from his bonds.
He had a vision in the year 1660, in the month called July,
concerning the fire of London, which happened six years afterwards;
a relation of which he gave forth in print.

In the year 1662, being about London,
he said to some of his friends that he had a narrow path to pass though;
and more than once signified that he saw he would be imprisoned,
and that it might cost him his life.
And coming not long after to Alton in Hampshire,
he was taken from a meeting of his friends, and committed to a stinking,
small prison at Winchester, where after a whole year`'s imprisonment, he fell sick;
and in the time of his sickness spoke many excellent words to those about him,
signifying, that he was given up to the will of the Lord either in life or death.
And lying in great weakness, he said, "`My heart is filled with the power of God.
It is good for a man at such a time as this to have the Lord to be his friend.`"
At another time he was heard to say, "`Lord, You have sent me forth to do Your will,
and I have been faithful unto You in my small measure, which You have committed unto me;
but if You will yet try me further, Your will be done.`"
He also said, "`I am the Lord`'s, let Him do whatever He will.`"
Not long before his departure he prayed very earnestly, saying, "`O Lord,
hear the inward sighs and groans of Your oppressed,
and deliver my soul from the oppressor.
Hear me, O Lord, uphold and preserve me.
I know that my Redeemer lives.
You are strong and mighty, O Lord.`"
He also prayed to God that He would deliver His people from their cruel oppressors.
And for those that had been convinced by his ministry,
he prayed that the Lord would be their teacher.
He continued quiet and sensible to the last period of his life,
dying a prisoner for bearing witness to truth;
and thus he stepped from this troublesome and transitory
life into one that is everlasting.
