== Chapter XV

[.section-date]
1664

In the foregoing year we left G. Fox in Lancaster prison, where at the sessions,
the oath of allegiance was tendered and refused by him,
and he was brought to his trial in the month called March, which began the year 1664.^
footnote:[Until 1752,
March was considered the first month of the year in all of England and its colonies.]
Being brought to the bar before judge Twisden, he said, "`Peace be among you all.`"
At which the judge looking upon him, said, "`What!
Do you come into the court with your hat on?`"
Whereupon the jailer taking it off, G. Fox said,
"`The hat is not the honor that comes from God.`"
Then the judge said, "`Will you take the oath of allegiance?`"
G+++.+++ Fox answered, "`I never took any oath in my life.`"
"`Well,`" said the judge, "`will you swear or no?`"
G+++.+++ Fox replied, "`I am a Christian, and Christ commands me not to swear;
and so does the apostle James likewise; and whether I should obey God or man,
you may judge.`"
"`I ask you again,`" said the judge, "`whether you will swear or no?`"
To which he made the following answer: "`I am neither Turk, Jew, nor Heathen,
but a Christian, and should show forth Christianity in all that I do.
Do you not know that Christians in the primitive times, under the ten persecutions,
and also some of the martyrs in queen Mary`'s days,
refused swearing because Christ and the apostle had forbidden it?
You have experience enough how many men have sworn first to the king,
and then against him.
But as for me, I have never taken an oath in all my life;
and my allegiance does not lie in swearing, but in truth and faithfulness;
for I honor all men, and much more the king.
But Christ, who is the great Prophet, who is the King of kings, the Savior of the world,
and the great Judge of the whole world, He says I must not swear.
Therefore the point is this, whether I must obey Christ or you.
For it is in tenderness of conscience, and in obedience to the command of Christ,
that I do not swear.
And we have the word of a king in defense of our tender consciences.`"

G+++.+++ Fox having spoken thus much, then asked the judge, "`Do you acknowledge the king?`"
To which he said, "`Yes, I do acknowledge the king.`"
"`Why then,`" said Fox, "`do you not observe his declaration from Breda,
and his promises made since he came into England,
that no man should be called in question for matters of religion,
so long as they lived peaceably?
Now if you acknowledge the king, why do you call me into question,
and put me upon taking an oath, seeing that neither you, nor anyone else,
can charge me with unpeaceable living?`"
The judge looking angry, said, "`Sirrah, will you swear?`"
To which G. Fox told him, "`I am none of your sirrahs.
I am a Christian; and for you, who are an old man and a judge,
to sit there and give nicknames to the prisoners,
is not fitting either for your grey hairs or your office.`"
The judge being a little more cool, after some words back and forth, said, "`George Fox,
say whether you will take the oath, yes, or no?`"
To which he replied, "`If I could take any oath at all, I would take this;
but I do not deny some oaths only, or on some occasions, but all oaths,
according to Christ`'s doctrine, who said, '`Swear not at all.`' Now if you,
or any of you present, or any of your ministers or priests here,
will prove that ever Christ or His apostle, after they had forbidden all swearing,
commanded Christians to swear, then I will swear.`"
None of the priests offering to speak, the judge said, "`I am a servant to the king,
and the king did not send me to dispute with you, but to put the laws into execution;
and therefore I tender you the oath of allegiance.`"
G+++.+++ Fox continuing to refuse swearing, was sent again to prison.
Two days after this, being brought again before the judge,
it was asked him whether he would deny the indictment or submit?
To this G. Fox said, "`I desire I might have liberty to examine the indictment,
and try it.`"
Then order was given to take him away,
and he was kept in prison until the next court session.

Being prisoner in Lancaster castle,
there was much talk of the great Turk`'s progress in Hungary,
there being at that time a war between the Emperor and the Turks.
Many being afraid, George said to some, that once when walking in his chamber,
he saw the Lord`'s power turn against the great Turk, causing him to turn back again.
And within a month after this, news came that he was defeated.
At another time, as he was walking in the room with his mind upon the Lord,
he saw an extraordinary great light, and looking up,
he beheld an angel of the Lord with a glittering sword stretched southward,
which shone so bright, as if the court had been all on fire.
For proof of this I have what G. Fox says of it in his journal,
and also another small book he gave out with the title of A Warning to England.
Not long after this, a war broke out between England and Holland;
afterwards the pestilence appeared at London^
footnote:[The Great Plague of London, lasting from 1665 to 1666,
was the last major epidemic of the bubonic plague to occur in England.]
(which lies southward from Lancaster),
and shortly thereafter the city was turned into rubbish by the fire.^
footnote:[The Great Fire of London was a major fire
that swept through the central parts of London,
from Sunday, the 2nd of September, through Thursday, the 6th of September 1666.
It destroyed 13,200 houses, 87 parish churches, St Paul`'s Cathedral,
and most of the buildings of the city authorities.
It is estimated to have destroyed the homes of 70,000 of the city`'s 80,000 inhabitants.]

But I return to the Lancaster court session.
Margaret Fell, who was now a widow,
was also under confinement for refusing the oath of allegiance.
And G. Fox being in prison, wrote several papers to the magistrates,
in which he manifested the evil of persecution, and exhorted them to virtue and piety.

In the month called August, the court session was held again at Lancaster,
where judge Turner then sat on the crown-bench.
G+++.+++ Fox being brought there, and being called to the bar,
the judge asked the justices whether they had tendered
him the oath of allegiance at the foregoing sessions?
They saying they had, and having sworn to it, the jury were sworn too.
Then the judge asked George whether he had refused the oath at the last court session?
To this he answered, "`I never took an oath in my life;
and Christ the Savior and Judge of the world said,
'`Swear not at all.`'`" The judge seeming not to take notice of this answer,
asked him whether or not he had not refused to take the oath at the last court session?
G+++.+++ Fox continuing to maintain the unlawfulness of swearing,
the judge said he was not at that time to dispute whether it was lawful to swear,
but to inquire whether he had refused to take the oath or not.
G+++.+++ Fox then signifying that he did not disapprove of the things mentioned in the oath,
said, "`Plotting against the king, and approving the Pope`'s, or any other foreign power,
I utterly deny.`"
"`Well,`" said the judge, "`you say well in that; but did you deny to take the oath?`"
"`What would you have me to say?`"
he replied, "`I have told you before what I did say.`"
After some more words from both sides, the indictment was read.
G+++.+++ Fox having informed himself of the errors that were in it,
said he had something to say about it, for there were many gross errors in it.
The judge signified that he would not hear him,
but when he was at the point of giving his judgment, the jury went out,
and then returned, and brought in a guilty verdict.
Whereupon G. Fox told them that both the justices and they too had forsworn themselves,
which caused such confusion in the court,
that the pronouncement of the judgment was delayed.
Margaret Fell being the next one brought to the bar, was also declared guilty.

The next day she and G. Fox were brought up again to receive their sentence.
Her counsel pleading many errors in her indictment, she was set aside;
and G. Fox then being called, showed himself unwilling to let any man plead his case,
which seemed to make some stop in their proceedings.
Yet at length he was asked by the judge what he had to say
as to why they should not pass sentence upon him.
At this, G. Fox told him, "`I am no lawyer, yet I have much to say,
if you will but have patience to hear me.`"
Thereupon those on the bench laughed, and said, "`Come now, what have you to say?`"
Then he asked the judge whether the oath was to be tendered to the king`'s subjects,
or to the subjects of foreign princes.
To this the judge said, "`To the subjects of this realm.`"
"`Then,`" said George, "`look on the indictment,
and you may see that you have left out the word '`subject`';
and not having named me in the indictment as a subject,
you cannot premunire me for not taking the oath.`"
They then looked at the statute, and the indictment, and saw that it was true,
and the judge confessed that it was an error.
Next G. Fox told him he had something else to say,
and he requested them to look what day the indictment said
the oath was tendered to him at the sessions there.
They looking, said it was the eleventh of January.
Then he asked, "`What day of the week was that sessions held on?`"
"`On a Tuesday,`" they said.
To which G. Fox said, "`Now look in your almanac,
and see whether there was any session held at Lancaster on the eleventh of January.`"
They looking, found that the eleventh day was the day called Monday,
and that the sessions had been on the day called Tuesday,
which was the twelfth day of the said month.
"`Look now,`" said George,
"`you have indicted me for refusing the oath in the quarter-sessions
held at Lancaster on the eleventh day of last January,
and the justices have sworn that they tendered me
the oath in open sessions here that day,
and the jury upon their oath have found me guilty thereupon;
and yet you see there was no sessions held at Lancaster that day.`"
The judge, to cover the matter,
asked whether the sessions did not begin on the eleventh day?
To which some in the court answered, "`No; the sessions held but one day,
and that was the twelfth.`"
Then the judge admitted that this was a great mistake.
Some of the justices grew so angry at this, that they seemed ready to go off the bench,
and stamping their feet said, "`Who has done this?
Somebody has done this on purpose.`"
Then G. Fox said, "`Have not the justices here who have sworn to this indictment,
forsworn themselves?
But this is not all; I have yet more to offer why sentence should not be given against me.
In what year of the king was it that the last court session,
which was in the month called March, was held here?`"
To this the judge said it was in the sixteenth year of the king.
"`But,`" said G. Fox, "`the indictment says it was in the fifteenth year.`"
This also was acknowledged to be an error;
but both judge and justices were in such a fret, that they knew not what to say;
for they had also sworn that the oath was tendered
to G. Fox the fifteenth year of the king,
whereas it was in the sixteenth.
This made G. Fox say, "`Has not the court here forsworn itself also,
they having sworn a whole year off?`"
Some other remarkable errors he showed as well, but having no mind to be tedious,
I pass these by with silence.

G+++.+++ Fox then saying he did not look for mercy, but desired justice, the judge said,
"`You must have justice, and you shall have the law.`"
This made G. Fox ask,
"`Am I now free from all that has been done against me in this matter?`"
"`Yes,`" said the judge; but then starting up in a rage he said,
"`But I can tender the oath to any man here; and I will tender you the oath again.`"
G+++.+++ Fox then telling him that he had examples enough
of yesterday`'s swearing and false swearing;
"`For I saw before my eyes,`" he said,
"`that both justices and jury forswore themselves.`"
Yet the judge asked him if he would take the oath?
But he replied,
"`Do me justice for my false imprisonment all this while;`" for
he had been locked up (as was well known) in a wet and cold room,
and therefore he said, "`I ought to be set at liberty.`"
At this the judge said, "`You are at liberty, but I will now put the oath to you again.`"
G+++.+++ Fox then turning himself around, said to the people, "`Take notice, this is a snare.
I ought to be set free by the jailer, and by this court.`"
But the judge, instead of hearkening to that, cried out, "`Give him the book!`"
G+++.+++ Fox then taking the book, and looking in it, said, "`I see it is a Bible,
and I am glad of it.`"
In the meantime, the jury stood by, having been called by the judge;
for though they had desired to be dismissed after they had brought in their former verdict,
yet he told them he could not dismiss them yet,
because he would have business for them to do,
and therefore they must attend and be ready.
G+++.+++ Fox, perceiving his intent, looked at the judge in the face, which made him blush.
Nevertheless he caused the oath to be read,
and then asked G. Fox whether he would take the oath or no.
To this George said, "`You have given me a book here to kiss, and to swear upon;
but this book says, '`kiss the Son;`'^
footnote:[Psalm 2:12]
and the Son says in this book, '`Swear not at all,`'^
footnote:[Matthew 5:34]
and so also does the apostle James.
And now I am saying what the book says, and yet you imprison me,
for doing as the book bids me.
Why do you not imprison the book for saying so?
Why is it that the book is at liberty among you, which bids me swear not?
Why do you not imprison the book also?`"
While he was speaking thus,
he held the bible open to show the place where Christ forbids swearing.
But the book was taken from him, and the judge said, "`No,
but we will imprison George Fox.`"

This case was so remarkable,
that it was spread over all the country that they gave G. Fox a book to swear upon,
which commanded him not to swear at all; and that this book (the Bible) was at liberty,
and he in prison, for doing as the Bible said.
But still the judge urged him to swear; to which G. Fox said,
"`I am a man of a tender conscience; consider therefore,
that it is in obedience to Christ`'s command that I cannot swear.
But if any of you can convince me that after Christ
and the apostle had commanded not to swear,
they did alter that command, and commanded Christians to swear,
then you shall see that I will swear.`"
And he seeing there several priests, said, "`If you cannot do it,
then let your priests do it.`"
But none of the priests said anything; and the judge said,
"`All the world cannot convince you.`"
To this he replied, "`How is it likely that the world should convince me?
For the whole world lies in wickedness.
But bring out your spiritual men, as you call them, to convince me.`"
Then the sheriff and the judge said, that the angel swore in the Revelations.
To which G. Fox replied, "`When God brought His first-begotten Son into the world,
He said, '`Let all the angels of God worship Him;`' and it is He who said,
'`Swear not at all.`'`" "`No,`" said the judge, "`I will not dispute.`"
Then G. Fox told the jury, it was for Christ`'s sake that he could not swear;
and therefore he warned them not to act contrary to the gift of God in their consciences,
because they must all appear before His judgment seat.
After some more words spoken, the jailer took him away.

In the afternoon he was brought up again;
and the jury having brought him in guilty of what he was charged with in the indictment,
that is, his not taking the oath, the judge asked him what he had to say for himself.
He then requested the indictment to be read,
since he could not answer to that which he had not heard.
The clerk reading it, the judge said, "`Take heed it has no errors again.`"
But the clerk read it in such a manner, that G. Fox could hardly understand what he read.
And when he had finished, the judge asked G. Fox what he had to say to the indictment.
To this he said, "`Hearing so large a writing read all at once,
and that at such a distance that I could not distinctly hear all the parts of it,
I cannot well tell what to say to it.
But if you will let me have a copy of it, and give me time to consider,
I shall answer it.`"
This put the court to a little stand;
but at length the judge asked him what time he desired to have?
And he answered, "`Till the next court session.`"
"`But,`" said the judge, "`What plea will you make now?
Are you guilty, or not guilty?`"
To which G. Fox replied,
"`I am not guilty at all of denying to swear '`obstinately and
willfully;`' and as for those things mentioned in the oath,
as Jesuitical plots, and foreign powers, I utterly deny them in my heart.
And if I could take any oath, I should take this;
but I never took any oath in all my life.`"
To this the judge returned, "`You say well.
But the king is sworn in, the parliament is sworn in, I am sworn in,
the justices are sworn in, and the law is preserved by oaths.`"
On which G. Fox told him that they had had sufficient experience of men`'s swearing,
and had seen how the justices and jury swore falsely the other day.
And continued he, "`If you have read in the book of Martyrs,
you may see how many of them did refuse to swear,
both within the time of the ten persecutions, and in bishop Bonner`'s day,
and you may see that to deny swearing in obedience to Christ`'s command is no new thing.`"
To this the judge said that he wished the laws were otherwise.
G+++.+++ Fox then said, "`Our yes is yes, and our no is no.
And if we transgress our yes and our no, let us suffer as they do, or should do,
that swear falsely.
This I have offered to the king, and the king said it was reasonable.`"

After some further discourse, G. Fox was committed to prison again,
and Colonel Kirby ordered the jailer to keep him secluded,
and to allow nobody to come to him, as one that was not fit to be discoursed with.
The jailer did not hesitate to follow this order, for he locked him up in a smoky tower,
where the smoke from the other prisoners came up so thick into his room,
that sometimes one could hardly see a burning candle.
Indeed, there seemed to have been an intent to choke him;
for the turnkey could hardly be persuaded to unlock
one of the upper doors a little to let out the smoke.
Besides this hardship, it was wet weather,
and it rained in upon his bed to such a degree that his shirt grew wet.
In this pitiful condition he lay during a long and cold winter, which so afflicted him,
that his body swelled and his limbs were much benumbed.
Here we will leave him till he was brought again to his trial,
which was not before the next year.

But before I part with him,
I must mention that some time before this he had written several papers to the emperor,
the kings of France and Spain, and also to the Pope.
These writings were by somebody else translated into Latin and so given out in print.
In these papers he leveled chiefly against persecution for religion`'s sake.
He reproved the king of Spain more especially because of the inquisition,
and the burning of people at the stake.
And he did not spare the Pope,
intermixing his writings with many demonstrations
that the Romish church was the whore of Babylon,
and that it was she who had defiled herself with idolatry and superstition,
and had bathed herself in the blood of the saints,
having furiously attacked them with both sword and fire.
This he concluded with these words: "`The plagues of God will be your portion, O Pope,
who have deceived the nations.
And all you Jesuits and cardinals, howl, for your misery is coming,
the mighty day of the Lord God comes upon you all;
for the Lord God will be worshipped in spirit and in truth,
and with none of your inventions.`"
Thus G. Fox wrote in that day to the Pope and his counsellors;
and it is no wonder that he paid dear for this strong
language against the head of the Church of Rome;
for it was believed that a great many of the royal
party in those days were either concealed Papists,
or favorers of them.
And yet among the national clergy, and even those of other persuasions,
many branded the Quakers with the name of clandestine Papists,
thereby to make them incur the hatred of the people.

Now I return to Francis Howgill, whom in the foregoing year we left in prison at Appleby.
It was in the forepart of this year that he was brought to his trial.
Having come into court before the judges,
he spoke to the clerk of the court session and told him,
he did not know whether they expected his appearance at that time or not.
The clerk said,
"`You have done well in coming,`" and said that he would acquaint the judge,
who would only engage to him to appear at the next
court sessions to answer the indictment against him.
Francis then bid him do whatever he needed to do.
In the meantime, Sir Philip Musgrave,
(so called) a great adversary to the Truth and the great and chief prosecutor of Francis,
had informed the judges against him that he was a dangerous person, a ringleader,
and one who held meetings that were of dangerous consequence,
and destructive of the peace of the nation.
They therefore concluded that Francis should appear in court;
and so the clerk informed him, and told him about what time he should be called.
When the court began, judge Twisden gave the charge to the grand jury, in which he said,
"`There is a sort of people, who under pretense of conscience and religion,
seem to build upon the king`'s declaration from Breda, and under this cover,
hatch treason and rebellion.`"
He then gave the jury charge to inquire into and uncover such men as these,
so that the peace of the nation might be preserved.
They then impaneled the jury, and Francis was called to the bar,
and the judge spoke as follows.

Speaking calmly to him, the judge said,
"`The appearance of things has much altered since the last court
session,`" and then made a large speech to him and the country,
telling him that all sects under pretense of conscience did violate the laws,
and hatch rebellions.
"`Not,`" said he, "`that I have anything to charge you with;
but seeing the oath of allegiance was tendered to you the last court session,
and you refused to take it,
it was looked upon that such persons were enemies to the king and government.`"
He then said, "`I will not trouble you now to answer to your indictment,
but I must do that the next court session.
In the meantime you must enter into bond for your good behavior.`"

To this Francis Howgill answered,
"`I desire liberty to speak,`" which was granted without interruption,
and he said as follows:

F+++.+++ Howgill: Judge Twisden, you very well know upon how slender an account, or none,
I was brought before you the last court session,
where you were pleased to tender me the oath of allegiance,
though I believe both you and the rest of the court did know it
was a received principle among us not to swear at all.
Many reasons I gave you then, many more I have to add, if I may have audience.
For it may appear to you an absurd thing, and obstinacy in me to refuse it,
if I should not offer my reasons.
I am none of those that make religion a cloak for maliciousness,
nor do I make my claims of conscience a cloak for carry on plots or conspiracies;
the Lord has redeemed me and many more out of such things,
and seeing I am engaged to appear at the next court session,
I desire no further thing may be required of me.

Judge: You must enter into bond during this dangerous time; therefore consider it,
and tell me either now, or before the court session ends.

The second day of the court session he was called again.

F+++.+++ Howgill: Seeing you are pleased to let me answer to the indictment,
which I am willing to do, I have been of good behavior, and shall so continue;
but it seems a hard thing to me, and full of severity,
that seeing I am obliged to appear to answer an indictment of so serious a nature,
which aims at the loss of my liberty for life, and my property forever,
I hope the court will not also deprive me of my liberty for the next five months.

Judge Turner: We do not desire your imprisonment, if you will be of good behavior.

F+++.+++ Howgill then pressed that they would not force him to give bond to be of good behavior,
knowing himself to be bound by the truth, so that he could not misbehave.

One Daniel Flemming,
another persecuting justice who had framed another
indictment against him for attending a meeting,
stood up (fearing that the snare of giving bond would not hold) and said as follows:

D+++.+++ Flemming: My lord, he is a great speaker,
and it may be the Quakers cannot go on without him.

Judge: Let him be what he will, if he will enter into bond.

F+++.+++ Howgill then said he had nothing to accuse himself of,
for his conscience bore him witness that he loved peace, and sought it with all men.

Judges: Why do you speak of conscience?
We don`'t meddle with it; but you disregard the laws, and keep up great meetings,
and do not go to church.

F+++.+++ Howgill: We have fallen in a sad age,
if meeting together peaceably without arms or force, or any intention to hurt any man,
but only to worship God in Spirit, and exhort one another to righteousness,
and pray together in the Holy Spirit as the primitive Christians did of
old--that this should be reckoned a breach of peace and misbehavior.

Judge Twisden: Do you compare these times with them?
They were heathens that persecuted, but we are Christian magistrates.

F+++.+++ Howgill: It is a doctrine always held by us,
and a received principle which we believe,
that Christ`'s kingdom cannot be set up with carnal weapons;
nor can the gospel be propagated by force of arms,
nor the church of God built with violence;
but because the Prince of Peace has been manifested among us, we can learn war no more,
but love our enemies, and forgive those that do evil to us.

Philip Musgrave then stood up and said, "`My Lord,
we have been remiss towards this people, and have striven with them,
and put them in prison again and again, and fined them,
and as soon as they are out they meet again.`"

Then stood up John Lowther, called a justice, and said, "`My Lord, they grow insolent,
notwithstanding all laws, and the execution of them, yet they grow upon us,
and their meetings are dangerous.`"

Philip Musgrave then stood up with justice Flemming
and produced a paper written in great capital letters,
and gave it the judge.
He then told the judge that it happened that some Quakers were sent to prison,
and one of them died at Lancaster, and they carried his corpse through the country,
and set that paper upon his coffin, "`This is the body of such a one,
who was persecuted by Daniel Flemming unto death.`"

Judge: We have spent much time with you; I will discourse no more.

F+++.+++ Howgill: I acknowledge your moderation towards me, allowing me liberty to speak.
I shall not trouble you much longer.
I shall be willing to appear and answer the indictment at the next court session,
and in the meantime to live peaceably and quietly, as I have done,
if that will satisfy the court.

Judge: You must enter into bond that you will attend no more meetings.

F+++.+++ Howgill: I cannot do that; if I did,
I would be treacherous to God and to my own conscience,
and the people and you would but judge me a hypocrite.

They were reluctant to commit him, yet at last they did.
This was in the latter part of the month called March,
and he was kept about five months as before in a filthy room,
and none were allowed to speak with him but those
who got to him without the jailer`'s knowledge.

It was about this time that John Audland departed this life.
He and his bosom friend, John Camm,
(whose decease was some years before) had travelled
much together in the ministry of the gospel.
I will therefore give an uninterrupted relation of their latter end,
beginning with that of John Camm.

He was born at Camsgil of very good parentage, in the barony of Kendal in Westmoreland,
which seat had been possessed by his ancestors long before him.
From his childhood he was inclined to be religious, and seeking after the best things,
he joined with those that were the most strict in performing religious duties.
And having afterwards heard G. Fox, he embraced as truth the doctrine he preached,
and growing up in it,
he himself became an eminent minister of the gospel among those called Quakers.
He and his bosom friend John Audland were the first
of that society who preached in Bristol,
where having been in the meetings of the Baptists and Independents,
they also had meetings in several places outside of the city,
where there was a great concourse of people, and many received their doctrine.
Since that time these two ministers travelled much together,
and many were convinced by their ministry.
But at length John Camm, who did not spare himself,
began to fall under a kind of consumption,
insomuch that through weakness he was forced to stay at home.
He then often called his children and family together, exhorting them to godliness,
and praying to the Lord for them.
Some weeks before his death, he once expressed himself thus:
"`How great a benefit do I enjoy above many,
having such a long time of preparation for death, being daily dying,
that I may live forever with my God in that kingdom that is unspeakably full of glory.
My outward man daily wastes and molders down, and draws towards its place and centre;
but my inward man revives,
and mounts upwards towards its place and habitation in the heavens.`"
The morning that he departed this life, he called his wife, children, and family to him,
and exhorting them to fear the Lord, to love His truth, to walk in it,
and to be loving and kind to one another, he told them that his hourglass had run,
that the time of his departure had come,
and that he was now to enter into everlasting ease, joy, and rest,
charging them all to be patient and content with their parting with him.
He then fainted away and passed into a sweet sleep.
But by the weeping and crying of those around him, he awakened,
and requested to be helped up a little in his bed, and then he spoke to this effect:
"`My dear hearts, you have wronged me and disturbed me; for I was at sweet rest.
You should not so passionately sorrow for my departure;
this house of earth and clay must go to its place,
and this soul and spirit is to be gathered up to the Lord, to live with Him forever,
where we shall meet again with everlasting joy.`"
Then taking leave of his family, he charged them to be content with his departure,
and lying down, within a little time deceased.

His beloved friend John Audland,
(who often bemoaned the loss of so dear a companion) died also of a kind of consumption;
for his ardent zeal often made him strain his voice
beyond what his body was well able to bear.
In a meeting, which he once had with John Camm, in a field outside of Bristol,
where Charles Marshall was one of his auditors, after John Camm had finished speaking,
he stood up with an awful and shining countenance; and lifting up his voice as a trumpet,
he said,
"`I proclaim a spiritual war with the inhabitants of the
earth who are in the fall and separation from God,
and I prophesy to the four winds of heaven.`"
Thus he went on with mighty power, exhorting the people to repentance,
and spoke with such a piercing authority,
that some of the auditory fell on the ground and
cried out under the sense of their transgression.
And when at Bristol, he many times preached in an orchard to a great multitude,
and would raise his voice exceedingly in order to be heard by all.
Thus he spent his natural strength, though he was but a young man.
About the twentieth year of his age, he married one Anne Newby of Kendal,
a virtuous maid, not only of a good family, but also excelling in piety.
She freely gave him up to travel in the service of the gospel,
notwithstanding his company was very dear to her,
often saying that she believed few ever enjoyed a
greater blessing in a husband so kind and affectionate.
And how heartily and tenderly she loved him,
may be seen by the following letter she wrote to him.

Dear Husband,

You are dearer to me than ever; my love flows out to you,
even the same love with which I am loved by my Father.
In that love, I desire that you salute all my friends on my behalf,
for you are all dear unto me, and my life is much refreshed in hearing from you.
I received your letters,
and can say that all my soul desires is to hear from you in the life.
Dear heart, dwell in the life, for there I am with you out of all time, out of all words,
in the pure power of the Lord, where is my joy and strength.

O, how refreshed I am to hear from you,
to hear of your faithfulness and boldness in the work of the Lord.
I cannot utter the joy I have concerning you.
Your presence I have continually with me in spirit and am filled with joy;
all glory and honor be to our God forever!
O blessed be the day in which you were born,
that you are found worthy to labor in the work of the Lord.
Surely the Lord has found you faithful in little,
and therefore has committed much unto you.
Go on then in the name and power of the Lord Jesus Christ, from which all strength comes,
to whom be all glory and honor forever.
O dear heart, go on, conquering and to conquer, knowing this, that your crown is sure.
Now is the time of the Lord`'s work, and few are willing to go forth into it.
All the world lies in wickedness, doing their own work; but blessed be the Lord forever,
who has called us from doing our own work into His great work.
O, marvelous are His works, and His ways past finding out.

O dear heart, you know my heart,
and you may read in it daily how I rejoice in nothing
more than in your prosperity in the work of the Lord.
Truly it is past my utterance to express the joy that I have for you.
I am full of love towards you; never before have I known such love as this.
Now may the mighty power of the Lord go along with you, and keep you faithful, valiant,
and bold in His pure counsel, to stand single-minded out of all the world.
My love to you is purer than gold seven times purified in the fire.
O pure is He that has loved us, therefore let purity and holiness cover us forever.
A joyful sound it was to me to hear that you were moved to go for Bristol.
O my own heart, my own life!
In that life which you now feel, act and obey, that you may stand upon your guard;
and let your prayers be for me, that I may be kept pure, out of all temptations,
to dwell entirely in the life.
So farewell.

Anne Audland.

By this letter it appears that there was an endeared
mutual love between this virtuous couple.
He was a man of great knowledge,
but when his understanding came to be opened by the preaching of G. Fox,
he would sometimes say, "`Ah, what have we been doing?
What avails our great religious profession?
All our building comes tumbling down; our profession is as high as the wind,
and the day of the Lord is upon it.
His Word, as a fire, consumes it as dry stubble,
and puts an end to all empty professions and high notions that are without life or substance,
and to all the wisdom of fallen man.
We must forsake the world, and all its glory;
for it is all but vanity and vexation of spirit.
It is a Savior that I long for; it is Him that my soul pants after.
O that I may be gathered into His life, overshadowed with His glory,
sanctified thoroughly by His Word, and raised up by His eternal power!`"
Continuing in this state of daily supplication and inward travail of soul,
it pleased the Lord at length to furnish him with
an extraordinary qualification to proclaim His word,
which he did for some years faithfully and with great zeal.
And though his wife loved him dearly,
and preferred his company above what the world could give,
yet in regard of his gospel service, she gave him up freely to be much away from home;
whereby, during a great part of the time of their marriage,
she did not have his desirable company.

In the meantime,
he labored diligently in the Lord`'s harvest until his bodily strength began to fail;
and meeting with hard imprisonments, he was seized with a most violent cough,
which was followed by a fever, so that his sleep was taken from him.
This made him grow very weak, but he bore his sickness with great patience,
and once said, that in those great meetings in the orchard at Bristol,
he often forgot himself,
not considering the inability of his body from a desire to be heard by all;
nevertheless his reward was with him, and he was content to be with the Lord,
which his soul valued above all things.
Not long before his departure, being visited by some of his friends,
he spoke comfortably and with great power,
as one that was beyond the feeling of his weakness.
To his wife, who was big with child, and near her delivery,
well knowing how tenderly she loved him, he said, "`My will is in true subjection,
submitting to the will of the Lord, whether in life or death;
therefore give me up freely to His disposing.`"
And she, though he was very dear to her, did so; which gave him some ease,
seeing her sincere resignation.
Being sometimes overcome with joy, he praised God in his sickness; and indeed,
so ardent was his zeal, that once, though very weak,
he desired to be helped up in bed upon his knees;
and thus he fervently supplicated the Lord on the behalf of the churches,
that they might be preserved in the truth, out of the evil of the world,
and that the gospel might spread and be published
to the gathering of all that pertain to Israel.

His strength now diminishing daily,
he sweetly departed this life at the age of thirty-four years,
about three weeks after the fever first seized him.
And his widow, who ten days after his decease gave birth to a son,
behaved herself discreetly, and said afterwards in a paper concerning him:
"`The eternal God, who by His providence,
joined us together in marriage in our young days,
in His blessed counsel also caused His day to spring from on high upon us.
And in the bright shining of His marvelous light, He revealed His Son Jesus Christ in us,
and gave us faith to believe in Him, the eternal Word of life,
by which our souls came to be quickened and made alive in Him.
And also, in and by the quickening power of His holy power,
we were made one in a spiritual and heavenly relation,
our hearts being knit together in the unspeakable love of truth, which was our life, joy,
and delight, and made our days together exceedingly comfortable;
for by this all our temporal enjoyments were sanctified and made a blessing to us.
How hard it was,
and how great a loss to part with so dear and tender a husband as he was to me,
is far beyond what I can express.
My tongue or pen is not able to declare the pain of my heart.
Yet in this I contented myself,
that it was the will of the Lord that he was taken from this evil world;
and that my loss, though great, was not to be compared to his eternal gain.`"
This widow, in the process of time, was married again to Thomas Camm,
the son of John Camm, her former husband`'s bosom friend.
She was indeed a woman of great virtue, but now I part with her,
with the intention to say more of her when I shall come to the time of her decease.

I return to Francis Howgill, whom we left in prison,
and who now appeared again at the court session, which was held at Appleby,
in the month called August.
Having obtained liberty to speak with the clerk of the court session,
he was told that he must prepare himself to come to a trial.
To this he answered that he was prepared,
but thought that all he could say would avail little,
believing they purposed to prosecute him with all severity.
This proved to be the case, as will appear by what follows;
for the county justices had incensed the judges against him beforehand.
Yet Howgill endeavored all he could to convince them of his innocency;
and to that end wrote the substance of the oath in
several heads which he could subscribe to;
to this he joined another paper to judge Turner,
showing the cause of his first commitment and the former proceedings against him,
and how unjust it was to prosecute him upon a statute made against popish recusants.
He also signified in that paper that he was a man of a tender spirit,
and feared the Lord from a child,
and that he had never taken any oath but once in his life, which was twenty years ago.
He explained that his refusing to take the oath of allegiance
was not in any evil intent to the king`'s person or government,
but merely upon a conscientious account, and that he could not swear,
being otherwise persuaded of the Lord,
seeing it was against the command of Christ and the apostle James`'s doctrine.
Besides this,
that he said he was able to make it evident that swearing was against
the example of the primitive Christians for several hundred years,
and so it was no new opinion.
He further stated that he did neither in willfulness nor obstinacy refuse the oath,
being sensible of the damage that would come thereby
if they did prosecute him upon that statute,
he having a wife and children, and a small estate,
which he knew lay at stake in the matter; but that though his life were at stake also,
he could not revolt from or deny that which he had most certainly believed in.
However, he said that if any could convince him otherwise either by scripture or reason,
he had an ear to hear.
And therefore all these things considered,
he desired he might be dismissed from his bonds and
from their persecution of him upon that account.
These papers were delivered to the judges and justices before he appeared in court,
and were read by them.
He then being called to the bar at the court session held at Appleby,
judge Turner said to him,
"`Here is an indictment against you for refusing to take the oath of allegiance;
so you must plead to it, either guilty or not guilty.`"

F+++.+++ Howgill, with a heart girded up with strength and courage, said: "`Judge Turner,
may I have liberty to speak, and make my defense,
for I have none to plead my cause but the Lord?`"

Judge: You may.

F+++.+++ Howgill: I will lay the true state of my case before you,
and of the proceedings against me from the first, seeing judge Twisden is not here,
who had knowledge of all the proceedings hitherto.
I am a countryman, born and brought up in this country;
my carriage and conduct are known, how I have walked peaceably towards all men,
as I hope my countrymen can testify.
About a year ago being at my neighboring market-town
about my reasonable and lawful occasions,
I was sent for by a high constable out of the market to the justices of peace,
before whom I went; and when I came there, they had nothing to lay to my charge,
but began to ask me questions about our meetings to ensnare me.
And when they could find no occasion,
they said they would tender the oath of allegiance to me,
though they never read it to me, neither did I positively deny it,
yet they committed me to prison.
So I was brought here to this court session,
and then the court order by which I was committed was called for, and the judge read it,
and said to the justices that it was insufficient.
Nevertheless judge Twisden tendered the oath of allegiance to me at that time.
Many things I did allege then, and many more I have to say now, if time will permit.
From that time I was under an engagement to appear at the next court session,
and so was called, and did appear at the last jail-delivery,
but a further obligation was required of me for good behavior,^
footnote:[This entering into bond for good behavior included
a promise that he would attend no more religious meetings.]
which I could not give, lest I should be brought into a further snare.
Since that time I have been committed prisoner these five months,
of which time I have been kept under great restraint,
my friends not being permitted to speak to me;
and thus briefly I have given you an account hitherto.
As to the oath, the substance thereof, with the representation of my case,
is presented to the court already, unto which I have set my hand,
and also shall in those words testify the same in open court, if required;
and seeing it is the very substance the law does require I desire it may be accepted,
and I cleared from my imprisonment.

Judge: I have come to execute the law, and the law requires an oath,
and I cannot alter it.
Do you think the law must be changed for you, or for only a few?
If this be permitted, the administration of justice is hindered, no action can be tried,
nor evidence given for the king, nor other particular cases tried.
Your principles are altogether inconsistent with the law and government;
I pray you show me which way we shall proceed, show me some reason,
and give me some ground.

F+++.+++ Howgill: I shall:
"`In the mouth of two or three witnesses every truth
is confirmed;`" and we never denied to give,
and are still ready to give evidence for the king wherein it concerns us,
and in any other matter for the ending of strife between man and man in truth and righteousness,
and this answers the substance of the law.

Judge: Do you think this is a good answer?
The law requires an oath.

F+++.+++ Howgill:
Still evidence is and may be given in truth according to the substance of the law,
so that no detriment comes unto any party,
seeing that true testimony may be borne without an oath.
I did not speak of changing the law; yet seeing we never refused giving a true testimony,
which answers the intent and substance of the law,
I judged it was reasonable to receive our testimony,
and not to expose us to such sufferings,
seeing we scrupled an oath only upon a conscientious account,
in tenderness of conscience, for fear of breaking the command of Christ,
the Savior of the world; which if we do,
there is none of you who are able to plead our cause with Him.

Judge: But why do not you go to church, but meet in houses and private conventicles,
which the law forbids?

F+++.+++ Howgill: We meet together only for the worship of the true God in Spirit and Truth,
having the primitive Christians for our example,
and to no other end but that we may be edified, and God glorified;
and when two or three are met together in the name of Christ,
and He in the midst of them, there is a church.

Judge: That is true.
But how long has it been since you have been to church?
Or will you go to the church that the law does allow?
Give me some reasons why you do not go.

F+++.+++ Howgill: I have many to give you, if you have patience to hear me.
First, God dwells not in temples made with men`'s hands.
Secondly, the parish house has been a temple for idols, that is,
for their ceremonies and images; and I dare have no fellowship with idols,
nor worship in idols`' temples; for what have we to do with idols,
their temples and worship?

Judge: Were there not houses in Scripture called the houses of God, and temples?

F+++.+++ Howgill: Yes, under the law; but the Christians, who believed in Christ,
separated from these,
(and the temple was made and left desolate,) and from the Gentiles`' temples too,
and met together in houses, and broke bread from house to house.
And the church was not confined then to one particular place, neither is it now;
many more things I have to say.
+++[+++The judge interrupted.]

Judge: Will you answer to your indictment?

F+++.+++ Howgill: I know not what it is, I never heard it, though I have often desired a copy.

Judge: Clerk, read it.

So the clerk read it, stating that F. Howgill "`had willfully, obstinately,
and contemptuously denied to swear when the oath was tendered.`"

F+++.+++ Howgill: I deny it.

Judge: What do you deny?

F+++.+++ Howgill: The indictment.

Judge: Did you not deny to swear?
And the indictment convicts you that you did not swear.

F+++.+++ Howgill: I gave unto the court the substance of the oath, as you all know.
Secondly, I told you I did not deny it out of obstinacy or willfulness,
neither in contempt of the king`'s law or government;
for my will would rather choose my liberty, than bonds.
And I am sensible it is likely to be a great damage to me;
for I have a wife and children, and some estate,
which we might subsist upon and do good to others, and I know all this lies at stake.
But if it were my life also, I dare not but do as I do,
lest I should incur the displeasure of God.
Do you judge I would lose my liberty willfully, and suffer the spoiling of my estate,
and the ruining of my wife and children for obstinacy and willfulness?
Surely no.

Judge: Jury, you see he denies the oath, and he will not plead to the indictment,
but only excepts against it because of the form of words; but you see he will not swear,
and yet he says he denies the indictment, and you see upon what ground.

Then they called the jailer to witness and swear that at
the last court session F. Howgill did refuse the oath,
etc.; and then the jury, without going from the bar,
gave in their verdict as "`guilty,`" and the court broke up that night.

The next day towards evening, when they had tried all the prisoners,
Francis was brought to the bar to receive his sentence.

The judge stood up and said, "`Come now, the indictment is proved against you,
what do you have to say as to why sentence should not be given?`"

F+++.+++ Howgill: I have many things to say, if you will hear them.
First, as I have said, I denied not out of obstinacy or willfulness,
but was willing to testify the truth in this matter of obedience,
or any other matter wherein I was concerned.
Secondly, because swearing was directly against the command of Christ.
Thirdly, it is against the doctrine of the apostle James.
Fourthly, even some of your principal pillars of the Church of England; as bishop Usher,
for a time archbishop of Ireland,
said in his works that the Waldenses denied all swearing in their
age because of that command of Christ and the apostle James,
and that this was a sufficient ground; and Dr. Gauden, late bishop of Exeter,
in a book of his I lately read,
cited very many ancient fathers to show that for the first
three hundred years Christians did not swear,
so that this is no new doctrine.

To this the court seemed to give a little ear, and said nothing,
but talked one to another as Francis stood silent.
Then the judge said,

Judge: Surely you mistake.

F+++.+++ Howgill: I have not the books here.

Judge: Will you say upon your honest word that they denied all swearing?

F+++.+++ Howgill: What I have said is true.

Judge: Why do you not come to church, and hear service, and be subject to the law,
and to every ordinance of man for the Lord`'s sake?

F+++.+++ Howgill: We are subject, and for that cause we pay taxes, tribute, and custom,
and give unto Caesar the things that are his, and unto God the things that are His,
namely, worship, honor, and obedience; and if you mean the parish assembly,
I tell you faithfully, I am persuaded, and upon good ground,
that their teachers are not the ministers of Christ,
neither is their worship the worship of God.

Judge: Why, it may be for some small things in the service, you reject it all.

F+++.+++ Howgill: First, it is manifest they are time-servers,^
footnote:[A time-server is one who adapts his opinions and manners to the times,
or to the changing ruling powers.]
for a time they preach up as divine service what another time they cry down as popish,
superstitious and idolatrous.
And that which they have preached twenty years together,
they make shipwreck of all in a day; and then later will again call it divine,
and compel all to believe what they themselves once made void.

Judge: What, since the king came in?

F+++.+++ Howgill: Yes, the same men that preached against it once,
now commend it and compel all to believe.
They are so unstable and wavering,
that we cannot believe them to be the ministers of Christ.
Secondly, they teach for hire, and live by forced maintenance,
and would force a faith upon men, contrary to Christ and His apostle`'s rule,
who said that everyone must be persuaded in their own minds, and,
"`whatever is not of faith is sin.`"
And though the priests say,
"`faith is the gift of God,`" yet they would force theirs upon us;
and because we cannot receive it, they cry,
"`you are not subject to authority and the laws,`" and nothing but seizing of goods,
imprisonment and banishment is threatened.
I could mention more particulars.
+++[+++Then the judge interrupted.]

Judge: Well, I see you will not swear, nor conform, nor be subject,
and you think we deal severely with you, but if you would be subject,
there would be no need.

F+++.+++ Howgill: I do so judge indeed,
that you deal severely with us for obedience to the commands of Christ.
Can you show me how any of those people for whom the act
was made have been proceeded against by this statute?
Though I envy no man`'s liberty.

Judge: Oh yes, I can instance you many up and down the country that are premunired.
I have done it myself, pronounced sentence against several.

F+++.+++ Howgill: What, against papists?

Judge: No.

F+++.+++ Howgill: What, against the Quakers?
So I have heard indeed.
Therefore, though the statute was made against papists, you let them alone,
and execute it against the Quakers.

Judge: Well, you will meet in great numbers, and do increase,
but there is a new statute will make you fewer.

F+++.+++ Howgill: Well, if we must suffer, it is for Christ`'s sake, and for well doing.

Francis then being silent, the judge pronounced the sentence, but spoke so low,
that the prisoner, though near to him, could scarce hear it.
The sentence was: "`You are put out of the king`'s protection,
and the benefit of the law; your lands are confiscated to the king during your life,
and your goods and belongings forever; and you are to be prisoner during your life.`"

F+++.+++ Howgill: A hard sentence for my obedience to the commands of Christ;
the Lord forgive you all.

So he turned from the bar.
But the judge speaking, he turned again,
and many more words passed to the same purpose as before.
At last, the judge rose up and said,

Judge: Well, if you will yet be subject to the laws, the king will show you mercy.

F+++.+++ Howgill: The Lord has showed mercy unto me, and I have done nothing against the king,
nor government, nor any man, and blessed be the Lord, therein stands my peace;
for it is for Christ`'s sake I suffer, and not for evil doing.

And so the court broke up.
The people were generally moderate, and many were sorry to see what was done against him.
But Francis signified how contented and glad he was that
he had anything to loose for the Lord`'s precious Truth,
of which he had publicly borne testimony,
and that he was now counted worthy to suffer for it.

This he did cheerfully, and died in bonds, after more than four years imprisonment,
as may be related in its due time.
He was a man of learning, and a great writer among his fellow believers.
During his confinement he wrote not only several edifying epistles to
exhort his friends to constancy and steadfastness in the doctrine of Truth,
but also some books to refute the opposers of it.

We have just seen how the judge said,
"`there is a new statute which will make you fewer.`"
This statute bore the title of An Act to Prevent and Suppress Seditious Conventicles.
And though an act made two years previously did extend to banishment,
yet that punishment was renewed and expressed more at length in this new act,
an excerpt of which follows:

An Act to Prevent and Suppress Seditious Conventicles

For providing of further and more speedy remedies against
the growing and dangerous practices of seditious sectaries,
and other disloyal persons, who under pretense of tender consciences,
do at their meetings contrive insurrections, as late experience has showed:

Let it be it enacted by the king`'s most excellent majesty,
by and with the advice and consent of the lords (spiritual and temporal),
and by the authority of this present parliament,
that if any person of the age of sixteen years or upwards, being a subject of this realm,
at any time after the 1st day of July, 1664, shall be present at any assembly,
conventicle or meeting,
under pretense of any exercise of religion in a manner other than that
which is allowed by the liturgy or practice of the Church of England,
in any place within the kingdom of England and dominion of Wales; at which conventicle,
meeting, or assembly, there shall be five persons or more assembled together,
over and above those of the same household;
then it shall be lawful for any two justices of the peace,
or the chief magistrate of the county wherein the offense aforesaid shall be committed,
to make a record of every such offense under their hands and seals,
after it has been demonstrated by the confession of the party, an oath of a witness,
or by evidence of the fact.
Thereupon the said justices or chief magistrate shall commit every
such offender so convicted to the jail or house of correction,
there to remain without bail for any time not exceeding the space of three months,
unless the offender shall pay to the said justices or chief
magistrate a sum of money not exceeding five pounds,
which money shall be paid to the church wardens for the relief of the
poor of the parish where such offender did last inhabit.

And let it be further enacted by the authority aforesaid,
that if such an offender so convicted, shall at any time again commit the like offense,
contrary to this act, and be convicted thereof,
then the offender convicted of a second offense shall incur the penalty of imprisonment
in the jail or house of correction for any time not exceeding six months,
without bail,
unless the offender shall pay down to the said justices
or chief magistrate a sum of money not exceeding ten pounds.

And let it be further enacted by the authority aforesaid,
that if any such offender so convicted of a second offense,
shall at any time again commit a third offense contrary to this act,
then any two justices of the peace, or the chief magistrate,
shall commit every such offender to the jail or house of correction,
there to remain without bail until the next general quarter sessions.
And if the offender shall be lawfully convicted of such an offense,
either by confession or verdict,
or if such offender shall refuse to plead or confess to the indictment,
then the respective justices of the peace are hereby enabled and
required to cause judgment to be entered against such offender,
that they shall be banished beyond the seas to any of his majesty`'s foreign plantations
(Virginia and New England only excepted) there to remain for seven years.

And let it be further enacted by the authority aforesaid,
that every person who shall knowingly and willingly allow any such conventicle,
unlawful assembly, or meeting aforesaid of five persons or more,
to be held in his or her house, outhouse, barn or room, yard, woods or grounds,
shall incur the same penalties and forfeitures as
any other offender against this act ought to incur,
and shall be proceeded against in all points,
in such manner as any other offender against this act ought to be proceeded against.

And in regard to the sect called Quakers,
if these are found also to be obstructing the proceedings of justice
by their obstinate refusal to take oaths that are lawfully tendered
unto them in the ordinary course of law;
then, in such a case,
the respective courts wherein such a refusal shall be made are hereby enabled
and required to record or register such refusal as a conviction of the offense;
and every person offending in this manner shall incur the judgment and
punishment of banishment overseas in such manner as previously described.

A learned man at London, of what religious persuasion I know not,
published a little book in relation to this act,
wherein he showed from the laws of England the absurdity of it.
For, he said, if all acts of religion exercised by six persons,
not according to the formality of the Church of England, were forbidden,
then it would be reckoned a transgression if,
when a woman in childbirth was in danger of losing her life,
one of the company said a prayer.
The same would be true if anyone spoke something
to comfort the near relations of a deceased person,
or prayed for the health or happiness of a young married couple, etc.
Thus it might happen that some, by the malice of their enemies,
could not only incur imprisonment for three months, but also be condemned to banishment.
Now, that this was not an unreasonable supposition,
appeared sufficiently by what judge Orlando Bridgman said at Hertford to the jury:
"`You are not to expect plain evidence against them
for anything said or done at their meeting;
for they may speak to one another, though not with or by audible sounds,
but by a glance of the eye, or a motion of the head or foot, or gesture of the body.
So that if you find or believe in your hearts that they were in
the meeting under pretense of religion in their way,
though they only sat still and looked upon each other, it was an unlawful meeting.`"

Now, since at that time many were resolved to banish the Quakers (so called),
George Whitehead published a little book in which
he showed the unreasonableness of the persecutors,
and also strengthened his friends with solid arguments against the charge of stiff-neckedness,
answering some deceptive objections.
Among the rest, it was suggested that Quakers might keep small meetings;
for if they would not meet above five in number,
they would keep outside of the reach of the law; and by keeping small, private meetings,
they might also acquit their consciences before God.
But to this George Whitehead answered,
that it might have been objected to the prophet Daniel that he might have prayed secretly,
and not with an open windows three times a day, after king Darius had signed the decree.
But Daniel, notwithstanding this decree, continued to pray to God as before.
"`Since then,`" said G. Whitehead, "`our meetings are kept in obedience to the Lord God,
and according to the freedom that He has given us,
we may not leave off our testimony for God in this case; but we must be faithful to Him,
whatever we suffer on that account.
For neither the threatenings of men, nor their severity or cruelty acted against us,
however far it may be extended,
can make us forsake the Lord in not keeping our assemblies,
or to be ashamed of Christ before men,
lest hereafter He be ashamed of us before His Father who is in heaven.`"
Besides this,
he showed how unreasonable it was to incite the jury on an ill-grounded suspicion,
without leaving them to the liberty of their own judgment.
He also showed how improper it was that the very
soldiers who had abused Friends in their meetings,
should be called as witnesses against them;
and that Friends should be locked up with thieves and felons,
since this was contrary to the right of a free-born Englishman.
But this publication of G. Whitehead was largely disregarded,
since many were resolved to go on banishing the Quakers,
and transporting them to the West Indies, though, according to the ancient laws,
this might not be done to a free-born Englishman against his will.
Josiah Coale about this time also gave forth a paper,
being a warning to the king and both houses of parliament,
to dissuade them from persecution.
But this did not avail, for persecution went on.

In the month called August, eight of those called Quakers, namely: Francis Prior,
Nicholas Lucas, Henry Feast, Henry Marshal, Jeremiah Hern, Thomas Wood, John Blendale,
and Samuel Trahern, were tried at Hertford before judge Orlando Bridgman,
already mentioned.
The indictment alleged that they had been at an unlawful meeting under pretense of religion,
and the witnesses declared that they had met together above the number of five,
and were taken at such times, and such places;
but the witnesses also declared that they neither heard them speak any words,
nor saw them do anything at their meeting, besides sit still.
The indictment having been delivered to the grand jury,
they could not agree in their verdict;
for there were some among them whose consciences would not
give them leave to be accessary to this work of persecution;
and therefore they brought in their verdict ignoramus.^
footnote:[Meaning there is not enough evidence to support the charges.]
Now, though such a verdict as this ought not to be rejected,
yet judge Bridgman standing up, and seeming to be angry,
spoke to the jury after this manner: "`My masters, what do you mean to do?
Will you make a nose-of-wax^
footnote:[Something that can be easily bent, changed, or influenced.]
out of the law, and permit the law to be confounded?
Those who think to deceive the law, the law will deceive them.
Why do not you find them guilty?`"
To this,
one of the jury said that it concerned them to be
careful and well-satisfied in what they did,
for men`'s lives were at stake for all they knew.
"`No,`" said the judge, "`I desire not their lives,
but their reformation;`" and then he gave the jury some directions,
and so colored the matter, that they going out again,
they soon returned with a guilty verdict.

Then four of the prisoners were called to the bar.
Their indictment was read, and they were asked, "`Guilty, or not guilty?`"
To this they answered, "`Not guilty,`" stating that they had transgressed no just law.
"`But,`" said the judge, "`you have transgressed this law (having the act in his hand),
and you have been twice convicted already upon record,
and if you are found guilty by the jury this time,
I must pass the sentence of banishment upon you.
But you shall see that we do not desire to strain the law to the highest severity;
neither do I believe that it was the aim of the law-makers to be severe,
but to make you conform.
Now, if you will promise that you will not go, or be at any more such meetings,
I will show you this favor, as to acquit you for what is past.
This favor you may receive before the jury brings in their verdict;
but afterwards I cannot do it.
And know also, that if the jury, for lack of punctual evidence,
should not find you guilty, yet if you are taken again,
you will be in the same case you now are in.
What do you say?
Will you promise to meet no more?`"
To this the prisoners answered that they could promise no such thing.
Then a jury was called, and the indictment read a second time,
alleging that the prisoners had been at an unlawful meeting at such a time and place,
the first, second, and third time.
The witnesses being called, gave the same evidence as before,
and then the judge said to the jury: "`My masters, the jury,
you hear what evidence the witnesses give; how these men were taken at such times,
at such places, which are places they use to meet in.
You see that they were above the number of five,
besides the persons of the family where they met;
and that they were twice convicted already upon record.
This is the third offense,
which incurs the sentence of banishment if you find them guilty.`"
He then spoke the words which have been mentioned already:
"`You are not to expect plain evidence against them
for anything said or done at their meeting;
for they may speak to one another, though not with or by audible sounds,
but by a glance of the eye, or a motion of the head or foot, or gesture of the body.
And they themselves say that the worship of God is inward, in the Spirit,
and that they can discern spirits, and know one another in spirit.
So that if you find or believe in your hearts that they were in the meeting,
under pretense of religion in their way, though they only sat still,
it was an unlawful meeting,
their use and practice not being according to the liturgy of the Church of England,
which allows and commands when people meet together in the church,
that divine service shall be read, etc.
Therefore you must find them guilty;
for you must have respect to the meaning and intent of the law,
which the king and parliament have in wisdom and policy made,
not only against conventicles, but the words '`assembly`' and '`meeting`' were added;
for we have recently had experience of the danger
of such meetings under pretense of religion,
and it is an easy matter at such meetings to conspire and consult mischief.
Therefore the wisdom and policy of the king and parliament,
lest they should be undermined, have made this law,
which is not a law against conscience, for it does not touch conscience at all,
as I confess some other laws do, which require coming to church, and some other things.`"
This and more judge Bridgman spoke to the jury,
to persuade them to bring the prisoners in guilty.
And the jury going out, within the space of an hour returned,
and their foreman declared that Nicholas Lucas and the other three were guilty.

What the judge had said,
that they had lately experienced the danger of such meetings under pretense of religion,
was of no force at all;
for it never appeared that the Quakers did anything other
than the performance of worship in their religious meetings,
though there was evidence to the contrary concerning the Fifth monarchy-men.
But it was universally known that the Quakers had no part with that people,
nor joined with them in the least degree.
It was also very absurd of the judge to assert that this law did not touch conscience;
for it was entirely for conscience-sake that the Quakers did not
frequent the public service and liturgy of the Church of England,
and thus kept religious meetings by themselves.
But the jury seemed well-satisfied with what the judge had told them;
and having thus obtained his aim,
he read the prisoners`' names, and said to them,
"`What can you say for yourselves,
that judgment of banishment should not be given against you?`"
To this they said, "`We are innocent, and have transgressed no just law.
But if we must receive that sentence,
we give up our bodies freely into the hands of the Lord; the will of the Lord be done.`"
"`Have you nothing more than this?`"
said the judge.
"`Nothing, but that we are innocent,`" replied the prisoners,
"`and that we have wronged no man.`"
"`Then hearken to your sentence,`" said the judge.
"`You shall be transported beyond the seas to the island of Barbados,
there to remain seven years.`"

Then Jeremiah Hern and Thomas Wood were called to the bar,
and their indictments were read, to which they pleaded, "`Not guilty,
but innocent;`" and Jeremiah said he was no such person as the act described,
being averse to plotting and contriving insurrections.
The judge interrupting him, said, "`You are a forward man,
and you have an estate;`" and so he caused him to be set by.
To Thomas Wood he said, "`I hear a good report of you; therefore, consider what you do.
I am sorry, seeing you have a good report among your neighbors,
that you should be found guilty, which I fear you will be if you put yourself upon trial.
I am willing to show you favor,
and it may be that one man may fare the better than another.`"
This he said reflecting upon Jeremiah, who, by the malice of one John King,
had been falsely represented to the judge.
Yet Jeremiah showing how he had been wronged,
the judge said that they should both partake of his favor, if they would but desire it;
and his favor consisted in this: that he would wave the proceedings of the court,
and give them until the next court session to consider better for themselves.
"`What do you say,`" he continued,
"`will you have your judgment deferred till the next court session?
For if the jury finds you guilty, you will be sent to Jamaica;
you must not all go to one place.`"
To this the prisoners replied, "`We have transgressed no law of God, nor wronged any man.
We leave it to the court, but we do not desire it.`"
"`If you do not desire it,`" replied the judge, "`then I cannot, nor will I do it.`"

Then three other prisoners were brought to the bar, among whom was one John Reynolds,
who, according to the deposition of the witnesses,
had been within a yard of the door of the meeting-place,
with his face turned away from it.
The judge then said,
"`God forbid that I should do anything that is not right and just against my conscience;
for I see written upon the wall before me a reminder that I should not judge for man,
but for God.`"
Then turning to the jury,
he spoke to them almost after the same manner as he did concerning the other four prisoners.
And to induce them to declare Reynolds guilty (who was apprehended,
but had not been in the meeting), he spoke thus: "`Suppose a man be killed in a house,
and nobody saw him killed,
but a man is found coming out of the house with a bloody knife in his hand;
it is a very probable evidence that he is guilty of the murder.
So though the witnesses say that they did not see or take this man in the meeting,
yet they swore he was within a yard of the door where they usually met;
and he has been taken twice already, and is convicted upon record.
My masters, I leave it to you; go forth.`"
Then a bailiff was called, and charged to provide the jury a room,
and to let none speak with them, nor to let them have either bread, drink, or candle,
until they brought in their verdict.
The jury having gone out, soon came to an agreement, and after they had returned said,
that "`four of the five prisoners were guilty,
and that the other who stood outside the door was not guilty.`"
So Reynolds was acquitted; but the other four being brought to the bar,
the judge asked them,
"`What can you say why judgment of banishment should not be given against you?`"
Their answer was, "`We are innocent,
and have not offended any just law of God or man to deserve that sentence.
We leave it to the witness of God in your consciences.`"
Then the judge said,
"`You have offended against this law (having the
act before him) which is made by the king and parliament,
and executed by us their subordinate ministers.
If it is not righteous and just, we must answer for that.`"
Then he asked the prisoners, "`Have you any more to say?`"
To which they answered, "`Nothing, but that we are innocent.`"
Then he said, "`Hear your sentence: you shall be transported beyond the seas,
to the island of Jamaica, being one of his majesty`'s foreign plantations,
there to remain seven years.
And now I have this one thing to acquaint you with,
that if either of you will here pay to the court a hundred pounds,
before the court is dismissed,
every one of you shall be discharged and clearly acquitted for what is past.
And I will show you this favor, not to dismiss the court at this present moment,
but wait till afternoon.`"
This was done; and the court having met again,
the judge asked the condemned prisoners if they would pay the hundred pounds;
but they answering, "`No,`" the court was soon dismissed.

Not long after this,
seven of these prisoners were carried aboard a ship to be transported to the West Indies;
but remarkably,
by contrary winds and stormy weather the ship was hindered from going to sea.
Not only the master, whose name was Thomas May, but also his men,
grew very uneasy at this; for they believed that heaven was against them.
Indeed,
the sailors threatened to leave the ship if the master would not set the prisoners ashore.
And the master himself, considering how they had long lain in the Downs,
and more than once attempted to set sail, but were hindered by contrary winds,
resolved at length (after having lingered about two months),
to set the banished men upon the shore.
And so he did, giving them a certificate, of which I have a copy in my possession,
that they had not run away, but were freely put ashore by him, for which, among others,
he gave these reasons: that seeing the great adversities they had met with,
he concluded from there, that the hand of God was against him,
and that he therefore dared not sail with these prisoners,
because he found them to be honest men, who did not deserved banishment.
He also stated that there was a law in existence that no native-born
Englishman could be transported against his mind,
and also that his men refused to proceed on the voyage
if he would carry away these people.
This certificate he gave under his hand, and so let them go away free;
and not long after the ship set sail with a fair wind.
I do not find that the banished men, who then returned home,
were ever prosecuted on this account;
for the sentence against them was executed as far as it could be at that time,
and they had made no opposition to it, but had been sufferers.

Persecution in the meantime did not cease;
but this did not discourage those called Quakers.
They continued valiant,
as I have seen in many letters sent about that time to some of my acquaintances.
One said in a court of law, "`We are in the service of the Lord,
and must not abandon it.`"
Another who was offered to be freed of banishment if he would pay a hundred pounds, said,
"`Though I had a hundred lives to lose, and could redeem them all for a hundred pence,
yet I would not do it.`"
But none of this did stop the violence of the persecutors,
until a heavier hand reached them, as will be related hereafter.

In the months of October and December many were condemned to banishment,
and among these several women, whose trials I shall but cursorily speak of;
for if I should relate all the particulars, the description would far exceed my limits.
I will therefore but touch upon a few things.

On the 13th of October, sixteen of those called Quakers were tried at Hicks`'s Hall,
in Middlesex, for the third offense, as they called it.
The grand jury consulting together about the indictment, could not well agree.
The justices then giving them a reproof,
one of the jurymen requested to know by what law they ought to find a person guilty,
when there were no witnesses present to testify to the act committed.
To this an answer was made by the court,
that their records testified that the crime or act had been committed,
and that their record was a sufficient witness without the testimony of any man.
The jury having already gone out twice before upon this business,
was sent out a third time; and Edward Shelton, the clerk,
said he would go out to help them, and so he did; it having been threatened,
that if the jurymen did not find them guilty they should be fined.
Nevertheless, when they returned they answered, "`No verdict.`"
Whereupon, finding that the jurymen did not answer their ends,
the justices separated and examined them one by one,
telling them that the only thing they were to consider was whether
the Quakers had assembled together above the number of five persons;
which, according to what they said, their records showed.
This made some of the jury comply; but others stood firm,
and signified that in conscience they could not consent to what was required of them.
But the greater part complying with the justices (upon being threatened),
and the others being strongly pressed, the indictment was, by a kind of force,
at length accepted.
But how painful a case this was to some,
appeared by the mournful confession of one of the jury,
who to ease his conscience published in print a small book,
with the title of The Wounded Heart, or The Juryman`'s Offenses.
In this book he openly disapproved the indictment,
which he had been induced to accept by fear.
And the clerk was reported to have said that he would rather have
paid twenty pounds than to have gone to such pains in order to
persuade the jury to bring in a guilty verdict.

The next day the prisoners were brought to the bar,
and William Proctor of Gray`'s Inn sat as judge in the court.
The questions and answers I will pass by for brevity sake, but one Hannah Trigg,
pleading that she was innocent, was asked how old she was.
To this she stated that she was not yet sixteen years old,
and one of the justices did not hesitate to say, "`She tells a lie,
and I thought the Quakers would not lie!`"
But it soon appeared that he said so only by guess,
for according to a certificate presented by some that were
present at her birth (which was also divulged in print),
it was proved that she, being the daughter of Timothy Trigg,
was born at London on the 20th of the month called August, 1649,
and was but fifteen years of age, and so had been prosecuted contrary to the law.
But this young maid falling sick,
died in prison after the sentence of banishment had been past upon her;
which sentence was also now pronounced against twelve other persons,
among whom were four other young maids.
Four married women were also condemned to a confinement
of eleven months in Bridewell prison.
The judge pronouncing these sentences was so disturbed in his mind,
that ordering some to be transported to Virginia, and others to Barbados,
he also condemned some to be sent to Hispaniola;
at which the people were not a little surprised,
since Hispaniola was not within the dominion of the king of England.

On the 15th of October above forty of the prisoners called
Quakers were tried before the judges Hide and Keeling.
To mention all the exorbitances of this trial (which were not few), I consider needless;
for as to the questions and answers, and the passing of the sentence,
the reader may form an idea of it from what has been said already of the trial at Hertford, etc.
A maid being asked to plead guilty or not guilty, answered,
"`I never was taken at any seditious meeting or conventicle in my life.`"
To which the judge said, "`But, woman,
were not you taken at the Bull and Mouth the 21st of August?`"
She answered, "`I am innocent in the sight of God and all good people.`"
That this was true the judge did not deny, but said, "`I believe that, woman,
but you have transgressed a law.`"
She replied, "`As for the Bull and Mouth meeting,
I believe I have been there a hundred times, and if the Lord permit me life and liberty,
I do not know but I may go there a hundred times more.`"
The judge then saying, "`Woman, will you plead or not, guilty or not guilty,
or else I must pass sentence upon you.`"
She answered, "`The will of the Lord be done, I am innocent.`"
Yet this did not help her, and she was set by as mute, or pro confesso,
as to the charges against her in the indictment.
Others who complained of the unreasonableness of the proceedings, were mocked as impudent.

In the meantime,
there were some among the witnesses who did not even know the prisoners by face,
so that there was reason enough to disprove their testimony.
But whatever was objected, the business went on.
For though one of the witnesses declared that the meeting
from which the prisoners had been taken was peaceable;
and though one of the prisoners said that the law was made against seditious meetings,
and that nothing of sedition had been proved against them;
nevertheless judge Keeling said that the act was made to prevent such meetings,
because under color and pretense of religion, plots and conspiracies might be carried on.
And when a prisoner said that he was at a peaceable and godly meeting,
and had received much comfort there; the judge replied, "`That is all that we desired.
You have confessed that you were there; and though it was a peaceable meeting,
yet it was an unlawful one.`"
Another of the prisoners who pleaded that the law by which the court had acted
was contrary to both Magna Charta and the ancient fundamental laws of the land,
was answered by judge Hide,
"`If the king and parliament should make a law that two justices, without a jury,
could condemn a man to death for the third offense as a felon,
without the benefit of clergy, it would be a good law, and according to Magna Charta,
and the laws of the land; and we would be bound to execute it.`"
It seems this judge (who not long after this was suddenly summoned
to appear before the divine court session) was of the opinion that,
since the legislative power resided in the king and parliament,
all that they resolved and enacted must be considered a "`good law.`"

But if I should mention all the absurdities that I meet with in these proceedings,
when should I come to an end?
True it is, that sometimes a show was made of pity; for judge Keeling said to two maids,
"`We are sorry that such young maids should be thus deluded.`"
But because they would not promise to go to the public church,
though they declared themselves ready to attend divine service,
they were deemed as guilty.
Another prisoner being asked by judge Hide whether he would go to church, answered,
"`If I have my liberty, I shall indeed go to church.`"
But when it appeared that he did not mean the established or national church,
this promise could not save him.
One Richard Poulton, a lad of fifteen years of age,
who by a certificate showed that he was not yet sixteen years old,
and therefore no transgressor of the law, was asked,
"`Will you swear that you are not sixteen?`"
To which he answered that he was not brought up to swear.
And being asked whether he would promise to go to church,
he answered that he could promise no such thing.
Then he was returned to the rest that were to be sentenced.

On the 17th of the aforesaid month, nineteen persons, among which were some women,
were condemned to banishment,
and four married women were condemned to twelve months imprisonment in Bridewell.
It seems that none of the judges had a mind to pronounce the sentence,
and therefore they left this business to the city recorder.
He then bidding the prisoners to hearken to the judgment of the court,
spoke so softly that he could not well be heard,
which made one of the prisoners say he ought to speak louder,
for they could not hear him.
But he continuing to speak softly as before,
two or three others of the prisoners told him they could not hear what he said.
To this the recorder answered that he cared not whether they did or not; and then said,
"`Hearken to your sentence, you and every one of you,
shall be transported beyond the seas, the men to Barbados, and the women to Jamaica,
being two of his majesty`'s plantations, there to remain seven years.`"
Thus the persecutors endeavored to be rid of the Quakers;
but though persecution was now very hot, yet they fainted not,
neither did they lack many vigilant assistants,
who both by example and words continually encouraged them to faithfulness.

Among these was Josiah Coale, who about this time, as I have been told,
was in prison at London;
and who both by writing and word of mouth did exhort his fellow-believers to constancy.
For, when he was under confinement, he applied himself to his pen,
and recommended to his friends that they not forsake their meetings,
though they were to undergo great sufferings,
since it was God`'s good pleasure to let their patience be tried.
"`And,`" said he, "`knowing that these afflictions come upon us by God`'s permission,
who then shall challenge Him,
or endeavor to reason with Him about matters of so great a concern,
since His way is hidden from man.`"
He also signified to them that this was allowed to try their faith,
and that therefore they ought to continue bold, and to persevere valiantly.
"`And though,`" said he, "`great sufferings and afflictions do attend us,
yet my heart (praised be the Lord) is not troubled, neither has fear seized me,
because I see the intent of the Lord in it.`"
And in one letter he spoke thus: "`Friends, know this:
that for the sake of the remainder of the seed which is yet ungathered,
my life is freely sacrificed up into the hands of the Lord;
and I am ready and willing to lay it down for the testimony of God`'s blessed truth,
which He has given me to bear, if I am called thereunto.
For bonds and afflictions attend me daily, and I may say,
we are in jeopardy of our lives every day.
So let your prayer to God be for me, that I may be kept unto the end,
to finish my testimony with joy,
and in all things to bring glory and honor to the name of the Lord, who is over all,
blessed forever.`"
This Christian desire he later obtained, as will be shown in its due place.

It was a time of suffering; and those to whose lot it fell continued valiant.
Others did not neglect to exhort the king and parliament to leave off persecution.
Among these was William Bayly,
who gave forth the following serious exhortation and warning against persecution:

For the King and Parliament, etc.

Friends,

The God of heaven has put it into my heart to write a few words unto you,
in the fear and dread of His name, and in the counsel of His own will,
concerning the work which you have taken in hand against Him and His people.
This is not the end and work for which the Lord God has
granted you the places of government and rule in this nation,
nor is it the way for you to prosper or prolong your days in the earth,
thus to persecute and afflict an innocent and harmless people, who are peaceable,
and walk uprightly towards God and man,
endeavoring in all things to keep their consciences void of offense.
These have no helper in the earth but the Lord alone;
neither is their kingdom of this world,
but they are verily the children and servants of the most high God,
whom He has gathered from among men to be a sort of first fruits unto Him in this age.
We are His, and not our own; He has brought us and redeemed us unto Himself,
and to Him alone we have committed our innocent cause,
and He has undertaken to plead it for us with all our adversaries.

Therefore friends, be awakened and open your eyes,
and see what a great stir and commotion is here in this nation;
to haul and drag out from their peaceable meetings a company of tender, innocent,
and harmless people--men, women,
and children--who meet together in the fear and tender love of God,
without any evil or bad intention toward any,
but rather good-will and compassion toward all men, even the worst of our enemies,
as the Lord bears us witness.
But these are driven as sheep to the slaughter,
and thrown into your filthy jails and prisons and houses of correction,
by rude and brutish people whom you have set to work by your authority,
until many of them have patiently suffered death,
whose innocent blood will assuredly be required at your hands.
And thus you may see how the disciples of Christ Jesus are
as sheep and lambs in the midst of wolves in this age,
and as a lily among thorns,
only for obeying His commands and for worshipping
the everlasting invisible God in spirit and in truth,
according to the Scriptures.
And surely, if you knew and understood what you have done against them,
you would tremble to have caused so many little ones, who believe in Christ,
to so grievously suffer,
for He said it were better for a millstone be hanged about his neck,
and be drowned in the depth of the sea,
then to offend one of these little ones that believes
in Me. And as sure as Christ Jesus suffered,
and rose again, and as God lives, who raised Him from the dead,
we are some of the little ones that believe in Him,
who (in derision and scorn) are called Quakers--as you might also call Moses,
the prophets and the apostles,
who in days past quaked and trembled at the presence of the Lord,
who is the same now as ever He was, though the ungodly do not know Him or His power.

But what shall I say unto you?
If you will not, or cannot,
believe our faithful testimony (or the testimony of God through us),
and the innocency of our cause and our sufferings,
neither will you believe if one should rise from the dead and declare it unto you.
For you have had many tender visitations, timely warnings,
and gentle reprehensions from the pure Spirit of the Lord God,
both from His witness in your own consciences,
and from His faithful servants and messengers,
who have written and declared unto you in His name and power.
And as for my part (who am one of the least of the thousands of Israel),
I could willingly have been silent toward you at this time, but the Lord,
whom I serve in my spirit, has laid it upon me to warn you once more,
for whose sakes I have borne a burden in the true sight and sense of your sad condition,
seeing a day of thick darkness, wrath,
and distress hastening upon you from the Almighty.

Therefore, be not proud nor rebellious, but hear and obey the word of the Lord.
For thus says the Lord God that made heaven and earth, "`Let My innocent people alone,
and touch them no more as you have done; for they are Mine, and I have called, chosen,
and redeemed them; they are My jewels, which I am making,
and they shall show forth My glory before men to the whole world.
I have anointed them, and I will preserve and deliver them,
and crown them with an everlasting salvation.
I will rebuke kings and rulers for their sakes, and distress nations,
and dethrone the mighty from their seats who rise up against them, as I have done.
So let My everlasting gospel have a free passage in these nations,
and do not reproach and afflict My servants and messengers any more,
whom I have chosen and sent to preach and declare the way
of life and salvation to the ends of the earth;
but rather bow your ear and your heart unto their testimony,
that it may go well with you, and prolong your days.
For he that blesses them shall be blessed, and he that curses them shall be cursed,
and every hand that opposes them shall wither.`"

"`But if you will not hear, but will persist and go on as you have done,
to oppress My heritage and harmless people,
and make war and opposition against My power and truth,
and thus set yourselves and your power against Me, the living God,
I will bring you down suddenly to the astonishment of nations,
and I will cut your day short, and turn your pleasures into howling and lamentation,
and then shall shame and contempt cover your memorial as a garment.
Thus I will work for the deliverance of My seed, and none shall hinder it.`"

Therefore, look to what you are doing, and consider your ways,
and what the effect of your work will be.
You are but men, and the children of men; your breath is in your nostrils,
and your life is but a vapor, which will soon vanish away.
You labor to feed the fire, and bring forth wind,
which blows up the flame of that which will consume
you and deprive you of all happiness forever.
Oh that you had hearts to consider it!
For the more you strive against the Lord, and oppress His people,
the more will they multiply and grow stronger and stronger.
And you shall wax weaker and weaker, and your works shall be like a heavy burden.

But friends, have not you yourselves been under sufferings,
and some of you been driven into strange countries
or lands for your "`cause`" (as it was called)?
Indeed, did not even the king himself once flee for refuge in a tree^
footnote:[After the final Royalists defeat in the English Civil War (September 3, 1651),
Charles II was forced to flee from Parliament soldiers,
and avoided detection by hiding in an oak tree in Boscobel Woods.]
to save himself from his enemies hands?
And was this not a great mercy and deliverance from God,
so to hide and preserve him from those who pursued him?
Are these things forgotten?
Do you remember and love His mercies by doing justly and walking humbly with Him,
as He does require?
Or do you boast in vain glory, as if your own arm had done it,
or your own strength had delivered you?

Do you say that these sufferings, which you sustained by those who opposed you,
were unjust and unequal?
If you should say, "`they were;`" then I say,
is it not much more unjust and very unequal in the sight of God
(and of all sober people that fear Him) for you to thus inflict
such cruel sufferings on an innocent and harmless people?
For you imprison, stifle to death in filthy jails and holes among thieves and murderers,
and pronounce sentence of banishment upon a peaceable people
who do not oppose you in the least with any outward force,
neither do the thoughts of it lodge within our breasts, as the Lord God knows,
who has called us to peace; but on the contrary,
we have sought and do seek your welfare and happiness,
both in this world and in the world to come, which in time shall be manifest to all.

And let me tell you again, that by these unreasonable and unjust dealings,
the understandings of thousands have been the more opened; and the tender,
sober part in many can feel the weight and burden
of this grievousness which you have prescribed,
and how you do so eagerly pursue and imprison so many innocent
persons and free-born people of this nation.
And your unnatural and cruel sentence of banishment,
separating dear and tender husbands from their dear and tender wives,
and tender children, and little innocent babes.
Oh, how do you break the heart of the meek of the earth, whom God has blessed!
What has become of all your promises of liberty for tender consciences?
May God Almighty cut short your work in righteousness,
and shorten the days of oppression and cruelty for His elect`'s sake,
who cry out night and day unto Him,
and make known His name and power to the ends of the earth.

O righteous, holy, pure, eternal God!
Though You have come near for judgment,
yet You are unknown to all who sit in darkness and dwell
in the spirit of enmity against You and Your people,
Mal.
3:5. Your way of life and salvation is hid from them,
therefore they hate us without cause, and evilly treat us in the darkness of their minds,
and in the ignorance and hardness of their hearts.
For this my soul does pity them, and even entreats You for them,
that if possible their eyes may yet be opened, and their hearts yet softened,
and their spirit humbled, that they may see what they are doing in the dark,
and consider the effects of their work, which will assuredly follow.
And if Your warnings and gentle visitations will not humble them,
then let Your judgments awaken them and bring them down, and humble them,
that they may perceive something of what You are doing in these latter days.
For You have begun, and You will go through and perfect Your work;
You will raise Your seed, and gather Your elect from the four winds,
and bring them from the ends of the earth,
and scatter the proud in the vain imaginations of their hearts.
You will break through all that oppose You in this day of Your mighty power,
in which You have arisen "`to finish transgression, and make an end of sin,
and bring in and establish everlasting righteousness;`"^
footnote:[Daniel 9:24]
that the kingdom of this world may become Your kingdom,
as You have promised and are now fulfilling.
Glory, honor, thanks, and everlasting praises be to Your glorious name, world without end.
Amen.

So friends,
you are and have been warned again and again by the
faithful messengers and servants of the Lord,
in love to your souls; and now you are left without excuse.
By this you may perceive how the Lord does strive with you,
that you might repent and be saved from the wrath to come,
though some of you now feel little of it in your own consciences.
But His spirit will not always strive with you;
for if you will not regard what has proceeded out of your own mouths,
nor perform your own words and public engagements in that which is just,
nor remember His past and present mercies, and His long-suffering towards you,
but trample all under foot; I say, if it be thus with you, and you are resolved to go on,
then you will wholly be given up, become exceedingly hardened,
and grow more desperate in cruelty and oppression against God and His truth and people.
And then (as true as God lives), the floods will come upon you,
and you will fall after the manner of Egypt;
and the weight of the dreadful judgments shall suddenly
sink you down into the pit that is bottomless.

From His servant, who is a lover of the welfare of all your souls,

William Bayly.

Written in the Tenth month, 1664, at Hartford.
