== Chapter XVI

[.section-date]
1644--1667

Again in December, twelve of those called Quakers were condemned to banishment;
for it was resolved to continue,
notwithstanding what George Bishop gave forth in print and caused
to be delivered to the king and the members of parliament,
which was as follows:

[.embedded-content-document.epistle]
--

[.salutation]
To the King and both Houses of Parliament, this says the Lord:

"`Meddle not with My people, because of their conscience to me,
and banish them not out of the nation because of their conscience; for if you do,
I will send my plagues upon you, and you shall know that I am the Lord.`"

[.signed-section-closing]
Written in obedience to the Lord, by his servant,

[.signed-section-signature]
George Bishop

[.signed-section-context-close]
Bristol, the 29th of the Fifth month, 1664.

--

The fulfilling of this prediction we shall see;
for within a short time a war ensued with the Dutch, and the pestilence^
footnote:[The Great Plague of 1665 was the worst outbreak of bubonic plague in England
since the Black Death of 1348. The plague killed an estimated 100,000 people,
almost a quarter of London`'s population, in 18 months.]
appeared at London.
But before the plague broke out,
still more of the imprisoned Quakers were condemned to banishment, namely,
thirty-two persons, both men and women, who were sentenced by the court on the 6th, 14th,
and 15th of December; for whatever they said in defense of themselves proved ineffectual.
One asked, "`If we meet truly to worship God, must we suffer for that?`"
Judge Hide answered, "`Yes, you must.`"
But judge Keeling, in order to mend the matter a little, said,
"`You shall not suffer for worshipping God,
but for being at an unlawful assembly contrary to the law.`"
Another said, "`I meet to worship the eternal God in Spirit,
as He persuades my heart and conscience;
and must I be condemned to banishment for that?`"
"`Yes, yes,`" said judge Keeling, "`for the law is against it.`"
To which judge Twisden added, "`Here he has confessed that he was there to worship God;
and their worship is contrary to the liturgy of the Church of England.`"
Thus we see that if there was but evidence that the prisoners had been at a meeting,
this was counted sufficient to condemn them.
A woman being asked what she had to say to the evidence given, answered,
"`Let it be known unto you all, that if I had as many bodies as hairs on my head,
I could lay them all down for the living eternal truth of the living God.`"
After all the prisoners had been called to the bar,
they were at length sentenced to be transported to Jamaica,
and to remain there for seven years.

This year in September died my mother, Judith Zinspenning, at Amsterdam in Holland,
where she had been born of religious parents who were among the Baptists,
into whose society her father Conrad Zinspenning had entered in an unusual manner.
And though it may seem somewhat out of my way,
yet because of the remarkable steps of Providence appearing therein,
I will give a short account of him.
He being of Cologne in Germany, was bred a Papist;
and after he had past the Latin schools,
his father thrust him into a cloister (for the Papists there used to think
it meritorious to offer up one of their children to the clergy).
His father died before the probation year had expired,
and he finding the monastical life so much against his inclination,
he begged his mother to assist him in his intention to leave the fraternity,
since he was not yet bound by vow.
She complied with his desire, and so he got out, and then he was put to a trade.
After he had served his time, he resolved to travel, and first took a journey to Holland,
from there to France, and then to Italy, and the metropolis Rome, and so back home again.
Having been a lay-friar,
he got letters of recommendation to such monasteries as
were of the order of those monks he had lived with,
that so he might freely find lodging there sometimes.
But having liked Holland so well, he resolved to stay there for a time; which he did,
coming in the course of time to live with a Baptist who employed him as a journeyman.
He never till then had met with the New Testament; but beginning to read it very eagerly,
and the Lord cooperating by His good Spirit, his understanding was opened,
and he obtained a clear sight of the superstitions and errors
of the popish religion in which he had been raised.
Eventually entering into some discourse with his master,
he was persuaded to renounce popery and to enter into the communion of the Baptists.
This ended all his plans concerning his further travels;
and so resolving to settle where he was, he took one Catharine de Mol, a virtuous maid,
as his wife,
whose father was one of the primitive Baptists that arose under the persecution in Flanders,
from where he with many more came to settle in Holland.

From these parents my mother descended, who was religiously inclined even from her youth,
and became very well versed in the Holy Scriptures.
She was so diligent in writing by memory many of the sermons she heard,
that her father sometimes said, "`It is a pity that this girl is not a boy,
for then in time she might become an eminent instrument in the church.`"
After she had come of age, though much inclined to lead a single life,
yet at length she was married to my father, Jacob Williamson Sewel,
a very religious young man who endeavored to walk in the narrow way,
and conversed mostly with the strictest professors of those days.
His father was William Sewel, from Kidderminster in Worcestershire,
who was one of those Brownists that left England and settled in Holland,
and married a Dutch wife at Utrecht, where my father was born.
In time both my father and mother grew dissatisfied
with that worship to which they were joined;
yet in clearness of understanding my mother exceeded my father.
Nevertheless she continued dissatisfied as well as he,
with the common way of worship to which she belonged, so that oftentimes,
when she came home from their meetinghouse, she resolved not to go any more,
saying she reaped no real and substantial benefit by it.

However, when the first day of the week would come again, she was in a strait,
thinking that however their worship was,
yet we are exhorted by the apostle not to forsake assembling together.
In this irresolute condition she continued a long time;
and being encumbered with the cares of the family,
she was not so much at liberty for performing religious duties (i.e. prayers,
reading and meditating upon the Holy Scriptures, visiting the sick,
and such like pious exercises), as she was before she was married.
This made her wish sometimes she had never entered into matrimony,
and that she might live to again enjoy that peace and quiet which once she had known.
But she knew not yet that it was the love of the Lord that was thus working upon her,
to draw her off from all transitory things.
In this state she was often seized with grief and sorrow,
so that she counted herself the most miserable of women;
for neither husband nor children, nor any outward enjoyments,
could afford her any pleasure; but all her desire was to attain to an undefiled state,
in which she might live an unblameable life, not only before men, but also before God.
For feeling there was yet something in her which was evil and polluting,
she struggled to overcome it; but all her labor proved in vain.
This made her cry earnestly to the Lord as one in great danger;
and her doubts whether it was possible to attain such a perfection increased.

But in this forlorn state it pleased the Lord to manifest Himself to her in some measure,
though she knew not then it was He. And she often cried out,
"`Lord what will it avail me to know that You have sent Your Son into the world,
and that He was crucified and died for the sins of the world, if I am not saved by it?
Lord forgive my sins, and have mercy upon me!`"
And once when she was alone, pouring out her heart before the Lord,
He made himself known to her, and spoke to her soul, that if she desired to be perfect,
she must follow His light in every respect.
Having heard this, she desired to know what this light was;
and the Lord showed her that "`the light was the life of men.`"^
footnote:[John 1:4]
This she understood in some degree,
and so separated herself as much as she could conveniently
do from interaction with others,
endeavoring to live more retiredly.
And having about this time heard Dr. Galenus Abrahams, an eminent Baptist teacher,
preach upon the parable of the seedsman, that which he spoke concerning the good ground,
and how the ground must be fitted by the Lord`'s working, so affected her,
that she resolved to rest from all her own labor,
and so stopped frequenting the Baptists`' assemblies.

In this retired state she continued a good while,
and at length came to hear William Ames preach;
and he declaring the light of Christ as the true teacher,
this agreed with what had already been made known to her
inwardly by the immediate manifestations of the Lord.
Thus she came fully to be convinced that this was
the truth which she had so long desired to know,
and now she saw clearly that it was her duty to give up all, and to keep nothing back;
for she had already seen that if she would be Christ`'s disciple, she must forsake all,
even her own self.
And though a fear of the cross was no small impediment to her,
yet she gave up in obedience,
and soon saw that her former performances had been defective,
and now all previous failures came clearly into remembrance.
This caused sorrow; but she prayed to the Lord both night and day,
and then He manifested His power by which she was led out
of the darkness and bondage wherein she had been held captive.
And her supplication to the Lord was that things might not be with her as formerly,
namely, that sometimes she had great zeal, and at other times coldness again;
but that she might continue in fervency of spirit.
After a long time of mourning, the Lord manifested His kindness to her,
by which she came to be quickened and refreshed;
and by the judgments of the Lord all was thoroughly searched out,
so that nothing could be hidden;
and a separation was made between the precious and the vile, and death passed over all.
But thus to part with all her own wisdom, and to forsake her great attainments,
was no small cross.
Nevertheless she became willing to bear it,
although many violent tempests arose to draw her off (if
possible) from closely adhering to the Beloved of her soul.

However, she was not quick to imitate any man; for my father,
who when he was convinced of the truth preached by W. Ames and W. Caton,
soon left off the common way of salutation,
would sometimes persuade her by arguments to do so too; but she told him,
that if forsaking that custom was a thing the Lord required,
she believed He would show it to her in His own time,
because she was given up to follow His requirings.
And so the Lord did in due time.
And because she continued zealous and faithful,
He was pleased after my father`'s death to give her a public testimony,
and she became eminently gifted;
for her natural abilities surpassed the ordinary qualifications of her sex.
And as she became more sanctified by the Spirit of the Lord,
it could not but produce good effects,
so that she came to be much visited and sought after by professors,
and even the Fifth Monarchy-men applauded her heartfelt admonitions.
But she was above flattery, and trampled upon it.
Indeed, she was so well esteemed,
that I remember once when she felt drawings to visit the
collegians in their meeting,
after one of them had finished speaking,
she stood up and said that she had something upon
her mind to speak to them by way of exhortation.
But knowing that they did not allow women to speak among them,
she did not desire bluntly to intrude herself, but desired their permission,
which they readily granted, and one of their chief speakers said to her, "`It is true,
friend, we do not allow women to speak in the church; yet we bear that respect to you,
that we grant you the liberty of speaking.`"
She then cleared her conscience before them,
having formerly been a frequenter of that assembly.
And when she had finished speaking, I do not remember that she was contradicted by any;
but one of their speakers concluded the meeting with a prayer.

Before that time she wrote and published a small book to those of her former society,
which she called a [.book-title]#Serious Reproof of the Flemish Baptists:#
in which she dealt very plainly with them, and showed how they had apostatized.
She also wrote some other treatises, still in print,
and was much beloved and well esteemed by English friends,
as appears by several letters written to her from England.
Those of her own nation often resorted to her for instruction,
she being so well experienced in the way of the Lord that
she was able to speak a word in season to various conditions.
Many times she visited the meetings at Alkmaar, Haarlem and Rotterdam,
and was often invited by her friends to come and edify them with her gift.
She also wrote many letters for edification and admonition to particular persons,
and some epistles to the church.
But it pleased the Lord to take her early to Himself.
When she fell sick, she soon had a sense that she was not likely to recover,
and therefore spoke much to me in private,
and acquainted me with several things having to do with myself,
and relating to her outward estate.
The night before she departed,
she called me to her bedside and exhorted me very fervently to depart from evil,
and to fear the Lord; which, by the mercy of God,
in time made very deep impressions upon my mind,
so that I still find reason to bless the name of the Lord
that I was the son of such an excellent mother.
Early the next morning, when she felt death approaching, she called me up out of my bed,
and sent me to fetch her brother and William Caton to come and see her;
and I had hardly returned a quarter of an hour before she departed this life,
and slept in peace.

To give a small instance of her true zeal for God,
I will insert here the following epistle she wrote to her friends,
to stir up the pure mind in them.

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle to the Friends of the Church.

Grace and peace be multiplied among you, my dearly and much beloved friends,
you who have received a blessing from God the heavenly Father in Christ Jesus,
the Lord of glory; who by His unspeakable love and His unchangeable light,
has drawn you off from all imaginary worships,
and brought you in measure to know Him who was from the beginning.
Dear friends, keep in the light by which you are enlightened,
and in the knowledge of God, which every one has received for himself;
watching against the seducing of Satan, that your eyes may be kept open,
lest deceit should prevail in any of you, by which truth might lose its splendor,
and the brightness of the Lord become darkened.

Though but young, I write these things to you in true love,
as one that takes care for you.
The Lord knows how often you are in my remembrance,
desiring that you may not only know the truth,
but that you may be found to be living witnesses of it.
For knowing the preciousness of it,
I cannot but desire that others may also participate in the same.
Therefore, labor for it my friends,
that so when the Lord comes and calls you to an account,
everyone may be found faithful according to what he has received.
For this is the talent which the Lord has given, that is,
the knowledge of Him who is true, and who rewards everyone according to his deeds.
But the negligent and slothful servant said that his Lord was a hard master,
and that he gathered where he had not sown, and this was his condemnation;
for the Lord said, "`You knew that I was an austere man;
why then did you not put My money in the bank,
that at My coming I might have collected it with interest?`"
Mind these things, my beloved friends, you that have an ear to hear,
and dig after this parable in yourselves.
For we have all received talents, some more, and others less.
Therefore let everyone be faithful to the Lord according to what he has received;
for truly some of you, I believe, have received five talents.
Let it but be duly considered and seen in the light of the
Lord what knowledge you have had of the eternal God,
beyond many others.
How often has the Lord appeared and clearly manifested Himself?
And how abundantly has He made it known in your hearts
that it is He who is worthy to be feared and served?
Certainly that is a great and weighty talent, and therefore the Lord may justly say,
"`What could I have done more for My vineyard?`"
O my friends, and besides all this,
He has caused His eternal light to shine into our hearts,
whereby we have seen the corrupted ways of the world, and the paths that lead to death.
This, I say, the Lord has showed us by His eternal light;
glory and praises be given to our God forever.

Dear friends, go on in that life in which you have begun;
for I can bear witness for the Lord that His love
has been abundantly shed abroad upon us,
without respect of persons.
For those that fear Him and work righteousness are acceptable to Him;
and He makes His truth manifest among us, and causes His peace and mercy to rest upon us.
It is true that Satan does not cease his attempts to scatter us,
and to sow doubts and unbelief in our hearts;
but keeping close to the Lord we are preserved from his snares;
and happy is he who has found a place where he is freed from tempests.
But before this place of safety can be found,
there are many hidden rocks that may be easily struck, which are not unknown to me.
And therefore I have true compassion on all who have not safely passed them;
for shipwreck may easily be the result of any of these.

Yet in all this danger there is something upon which we may safely rely,
and to which we may trust, being as a beacon; namely,
the light that shines into our hearts, though it be sometimes only as a spark,
and so small in comparison to the manifold seducings
of the enemy that it can hardly be discerned.
Here then is experienced no small amount of grief and anguish;
here all the mercies of the Lord (which we formerly enjoyed
in abundance) are called into question and doubted;
here there is danger, and yet there is certainty; for by not sinning,
the beacon is minded,
and by relying on a true hope to be saved we are preserved in the tempest.
I write these things for the information of those who are
traveling towards that city which has foundations,
and whose builder and maker is God.
To such as these my love is extended,
and my desire to the Lord for them is that they may be kept
by His power and remain standing at His coming.

Dear friends, keep your meetings in the fear of the Lord,
and have a care that your minds are not drawn out after outward words;
but stand in the cross to that which desires refreshment from without.
And when at any time you feel very little refreshment,
let it not enter into your hearts that the Lord is not mindful of you;
but center down in yourselves, in His pure light, and stand still therein.
Then perhaps you will find the cause why the presence
of the Lord has departed from you for a time;
and by putting away the cause, you shall enjoy the Lord again to your great comfort.

May God Almighty preserve you all by His power,
lest any strife or discord be found among you; and may you grow up in love,
and thereby be obliged to bear each other`'s burdens.
Let no transitory things encumber your hearts, but be resigned to the Lord;
for that to which we are called cannot be compared with what is transitory or perishing.
Truly, the most glorious part of this world is but vanity of vanities.
O, my friends,
let no one be hindered by any impediments from entering into the kingdom of heaven;
but all strive to enter the narrow gate.
Every one of you search your own hearts with the light wherewith you have been enlightened,
which shall manifest to you your true states; and keeping there,
it shall multiply your peace, and everyone shall find therein his own teacher,
as all have experienced who have sought the Lord with all their heart.

Now may the God of all mercies, who alone is immortal,
keep you and us together to the end,
that so in these dangerous times we may remain standing to the glory of His great name.
Oh friends, keep out all craftiness,
and enter not quickly into discourse with those that are outside of the truth;
for they speak in their own wills, and are crafty, and, knowing no bridle to their mind,
they ensnare the simple and innocent.
Keep rather in that light wherein you can see their subtlety; for then,
though you may not have one word to defend yourselves, yet you shall abide above them.

This is written in love to you, from a young plant,
according to the gift received from the Lord.
My salutation is to you all in the light of truth.

[.signed-section-signature]
Judith Zinspenning.

--

In the year 1664,
a small book came forth in print addressed to the king and to both houses of parliament,
wherein was set forth not only the violent persecution
taking place over almost all of England,
with the names of persons, places, and cases, which indeed were woeful, and some bloody;
but it was also shown that there were at that time above
six hundred of the people called Quakers in prison,
merely for religion`'s sake.

In the month called January, in the year 1665, thirty-six of that persuasion,
among which were eight women, were condemned to be transported to Jamaica.
The jury, not being as forward to declare the prisoners guilty as the court desired,
were persuaded however by the threatenings of judge Keeling, the recorder Wild,
and the boisterous Richard Brown, to do what was demanded of them.

On the 18th and 22nd of the next month,
thirty-four of the said people were sentenced to be carried to Jamaica,
and five to Bridewell.
The details of their trial I pass by with silence, to avoid prolixity.
Those that were tried on the 18th were sentenced by judge Wharton;
and those on the 22nd by judge Windham.
One Anne Blow, declaring that, because the fear of the Lord was upon her heart,
she dared not conform to anything that was unrighteous, judge Windham replied:
"`Anne Blow, I will show you as much favor as the court will allow you,
if you will say that you will go no more to that seditious meeting,`" meaning the Bull-and-Mouth.
To this she answered, "`Would you have me sin against God in my own conscience?
If I were set at liberty today, if the Lord required it of me,
I would go to the Bull-and-Mouth tomorrow.`"

Concerning one John Gibson, the said judge spoke to the jury in this manner: "`Gentlemen,
although it is true, as this Gibson says,
that it cannot be proved that they were doing any evil at the Bull-and-Mouth;
yet it was an offense for them to be gathered there,
because in the process of time there might be evil done in such meetings.
Therefore this law was made to prevent them.`"
By this we may see with what specious colors the persecutors cloaked their actions.
I find among my papers,
a letter of John Furly and Walter Miers (both of whom I knew well),
mentioning that some of the jury,
for refusing to give such a verdict as was required of them,
were fined a great sum and put into prison until they should pay the fine.

Having now said thus much of their sentencing,
it grows time to speak of the execution thereof.

Some of the persons sentenced to banishment fell sick and died in prison;
some became apostates, and some were redeemed by relations who were not Quakers.
Nevertheless, a considerable number was, though with great pains,
brought on board a ship to be transported to the West Indies.
We have seen already how those that were sentenced at Hertford by judge Orlando Bridgman,
returned home having been put ashore by the master of the ship.
And it was not long after this that three of their friends,
being on board the ship called _The Many-Fortune_ of Bristol,
were also set on shore with a certificate from the master of the ship,
signed by him and seven of his men,
wherein they stated that God had spoken (as it were) in their hearts:
"`Accursed be the man that separates husband and wife;
and he who oppresses the people of God, for many plagues will come upon him.`"

But the first of those called Quakers who really
tasted banishment were Edward Brush and James Harding,
who were banished not only out of London (where they as citizens
had as much right to live as the chiefest magistrates),
but also out of their native country, contrary to the right of a freeborn Englishman.
These two men, with one Robert Hays, were on the 24th of the month called March,
fetched from Newgate Prison in London early in the morning,
and brought to Blackfriars`' stairs, where they were put into a boat,
and so carried down to Gravesend, and there placed on board a ship.
Hardly any warning had been given to these prisoners; and Robert Hays being unwell,
had got nothing to eat before he came to Gravesend,
and since it was very cold that morning,
he was seized in the ship with so severe a sickness that he died of it,
and his corpse was carried to London and there buried.
The other two men were carried to Jamaica, where, by the providence of God,
in time it fared well with them, and Edward Brush lived to return into England.
It was remarkable, however, that not long after these persons were banished,
the great pestilence broke out in London, and it started in a house on Bearbinder-lane,
next door to the house where the said Edward lived.
Some thought this worthy of notice;
since that house was the first to be shut down because of the plague.

With the other prisoners they had more trouble and pains,
because no shipmasters could be found that were willing to carry them.
Therefore an embargo was laid upon all merchantmen with an order that
none could go down the river without having a pass from the admiral;
and this they would give to no shipmaster going to the West Indies unless he
made promise to carry some Quakers along with him to the place of their banishment.
Whatever any of the shipmasters spoke against this, intimating that there was a law,
according to which no Englishman could be carried
out of his native country against his mind,
was in vain.
At length, by force, they got one to serve their purpose,
and on the 18th of the month called April,
seven persons who were sentenced to banishment were
carried from Newgate Prison to Blackfriars`' stairs,
and so into a boat to Gravesend.
But in the meantime, the pestilence increased in London, and not long after, judge Hide,
who had been very active in persecuting, was, with many others,
suddenly taken out of this life.
Having been seen in the morning at Westminster in health as to outward appearance,
it was said that in the same afternoon he was found dead in his chamber;
being thus summoned to appear and give an account for his
deeds before a higher court than ever he presided in.

But notwithstanding this scourge from heaven, banishment had not yet come to an end.
First, as has been said, three persons, next seven,
and then on the 16th of the month called May,
eight were carried down the river to Gravesend and put on board a ship.
But as the number of those that were transported beyond the seas increased,
so also the number of those that died of the pestilence much more increased.
Nevertheless, a master of a ship was at length found who said, as was reported,
that he would not hesitate to transport even his nearest relations.
And so an agreement was made with him that he should
take between fifty and sixty Quakers into his ship,
and carry them to the West Indies.
Eight or ten at a time were therefore brought to the waterside,
and with boats or barges were carried to the ship which lay at anchor in the Thames,
in Bugbey`'s-hole, a little beyond Greenwich.
Many of these prisoners, among whom were several women,
not showing themselves willing to climb into the ship,
lest it should seem as if they were instrumental in their own transportation,
were hoisted up with tackle.
The sailors showing themselves unwilling to do this work,
and saying that if it were merchants`' goods they
would not be unwilling to hoist them in,
the officers took hold of the tackle, and said, "`They are the king`'s goods.`"
This was on the 20th of the month called July, and on the 4th of the next month, when,
according to the bill of mortality three thousand and forty died in one week,
the rest of the banished prisoners were carried by soldiers to the said ship,
in which now were fifty-five of the banished Quakers, and among these eighteen women.
But something adversely hindered this ship from going to sea,
and when it was found that the pestilence had also entered into it,
which quickly took away the lives of many of the prisoners,
the rest were freed from their banishment.

But though the pestilence grew even hotter in London,
and a war had arisen between England and Holland,
yet the fire of persecution continued hot as well,
and they ceased not to disturb the meetings of those called Quakers,
and to imprison many of them.
Indeed, so hardened and unrelenting were some of these persecutors,
that when in London more than four thousand people died in one week,
they said that the only means to stop the plague
was to send the Quakers out of the land.

In September some meetings of this people continued to be disturbed in London,
though the number of dead in one week had risen to above seven thousand.
Those who intended to have met at the Bull-and-Mouth
were kept out of their meetinghouse,
but meeting together in the street, they were not disturbed;
for by this time some fear had arisen among the common people,
and many grew discontented because there was now little money to be made by tradesmen.
The city also came to be so emptied that grass grew
in the streets which were once very crowded,
few people now being seen coming and going.
Thus the city became as a desert, and the misery was so great,
that it was believed some died for lack of attendance.

It was about this time that Samuel Fisher died piously in prison.
He had first been a prisoner at Newgate in London, and then afterwards in Southwark,
since the beginning of the year 1663 until this time, being about a year and a half.

It is reported that the king, in the time of this great mortality,
once asked whether any Quakers had died of the plague?
And having been told, yes, he seemed to slight the sickness,
and to conclude that then it could not be looked
upon as a judgment or plague upon their persecutors.
But surely his chaplains might have put him in mind of that saying of Solomon,
that "`One event happens to the righteous and to the wicked;`"^
footnote:[Ecclesiastes 9:2]
and of this saying of Job, "`He destroys the blameless and the wicked;`"^
footnote:[Job 9:22]
as also that of the prophet, "`That the righteous is taken away from the evil to come.`"^
footnote:[Isiah 57:1]

Traveling in the country was then stopped,
which made some people go with boats along the coast,
and then go ashore wherever they had a mind.
Thus did Stephen Crisp, who came about this time to York,
where the duke of York was then, with many of the great ones.
About this time Alexander Parker and George Whitehead came to London,
where they had good service in preaching the truth.

Great fires were now kindled in the streets in an attempt to purify the contagious air;
but no relief was found by it;
for in the latter end of September there died in
London above eight thousand people in one week,
as I remember to have seen in one of the bills of mortality at that time.
In the meantime, the ship in which the banished prisoners were held could not set sail,
but continued to lie in the river as a gazing-stock for all ships that passed by;
for the master was imprisoned for debt.

But now the prediction of George Bishop was fulfilled,
for the plagues of the Lord fell so heavily on the persecutors
that their eagerness to banish the Quakers and send them away,
began to abate.
The same George Bishop, about mid-summer,
wrote a letter to his friends from the prison at Bristol,
exhorting them to steadfastness, and foretelling that if they happened to be banished,
God would give them grace in the eyes of those among whom they should be sent,
if they continued to adhere to Him; and that when He had tried them,
He would bring them again into their native country, and none should root them out.
He also said that the Lord would visit their enemies with the sword and pestilence,
and strike them with terror, etc.
This is but a short hint of what he wrote at length.

G+++.+++ Fox the younger had also, in the year 1661,
given forth a little book (of which some small mention has been made before),
in which he lamented over England because of the judgments that
were coming upon her inhabitants for their wickedness and persecution;
saying, among other things, that the Lord had spoken in him concerning the inhabitants,
"`The people are too many, the people are too many.
I will thin them, I will thin them.`"
Besides this, the Spirit of the Lord had signified unto him that an overflowing scourge,
yes even an exceeding great and terrible judgment, was to come upon the land,
and that many in it should fall and be taken away.
And that this decree of the Lord was so firm,
that though some of the Lord`'s children and prophets
should appear so as to stand in the gap,
yet His decree should not be altered.
This with much more he wrote very plainly; and though he had deceased long before this,
yet this paper was reprinted to show the inhabitants
how faithfully they had been warned.

What Isaac Penington, being a prisoner, wrote about this time to the king and parliament,
and published in print, was also very remarkable,
being designed with Christian meekness to dissuade them if possible
from going on with this mischievous work of persecution.
In this paper, containing some queries, among many weighty expressions,
I find the following:

[.embedded-content-document.paper]
--

After you have done all you can, even made laws as strong as you can,
and put them in the strictest course of execution you can,
yet one night from the Lord may end the controversy,
and show whether we please the Lord in obeying Him,
or you please Him in making laws against us for our faithfulness and obedience to Him.

If you mistake your work, misinterpreting His providence,
and erring in heart concerning the ground of His displeasure; and so,
through an error of judgment, set yourselves in opposition against Him,
replanting that which He desires not to grow, and plucking up the plants of His planting;
do you not in this way provoke the Lord to put forth His arm against you?
We are poor worms.
Alas, if you had only us to deal with, we should be nothing in your hands!
But if His strength stands behind us, we shall prove a very burdensome stone,
and you will find it very hard to remove us out of the place where God has set us.
And it would be happy for you, if instead of persecuting us,
you were drawn to wait for the same begetting of His Spirit which we have felt,
out of the earthly nature and into His life and nature,
and then did learn of Him to govern in that.
Then indeed you might be established,
and be freed from the danger of these shakings and over-turnings
which God is hastening upon the earth.

Now, because you may be apt to think that I write these things for my own sake,
and for the sakes of my friends and companions in the truth of God,
in order that we might escape the sufferings and
severity which we are likely to undergo from you,
and not mainly and chiefly for your sakes,
lest you should bring the wrath of God and misery
upon your souls and bodies--to prevent this mistake,
I shall add what follows.
Indeed, this is not the intent of my heart; for I have long expected,
and do still expect this cup of outward affliction and persecution from you,
and my heart is quieted and satisfied therein,
knowing that the Lord will bring glory to His name, and good to us out of it.
But I am sure it is not good for you to afflict us
for that which the Lord requires of us,
and in which He accepts us;
and you will find it the bitterest work that ever you went about,
and in the end will wish that the Lord had rather never given you this day of prosperity,
than that He would allow you to make use of it in this way.
Now, that you may more clearly see the temper of my spirit,
and how my heart stands in this thing,
I shall a little open unto you my faith and hope about it in these following particulars:

First, I am assured in my heart and soul that this despised people, called Quakers,
is of the Lord`'s begetting in His own life and nature.
Indeed, had I not seen the power of God in them,
and received from the Lord an unquestionable testimony concerning them,
I had never looked towards them; for they were otherwise very despicable in my eyes.
And this I cannot but testify concerning them,
that I have found the life of God in me acknowledging them,
and felt that which God has begotten in my heart refreshed by the power of life in them.
And none but the Lord knows the beauty and excellency of
glory which He has hid under this lowly appearance.

Secondly, the Lord has hitherto preserved them against great oppositions,
and is still able to preserve them.
Every power hitherto has made nothing of overrunning them; yet they have hitherto stood,
by the care and tender mercy of the Lord;
and the several powers which have persecuted them, have fallen one after another.

Thirdly,
I have had experience myself of the Lord`'s goodness and preservation
of me in my suffering with them for the testimony of His truth,
who made my bonds pleasant to me,
and my loathsome prison (which was enough to have destroyed my weakly
and tenderly educated nature) a place of pleasure and delight,
where I was comforted by my God night and day, and filled with prayers for His people,
as also with love to, and prayers for,
those who had been the means of outwardly afflicting
me and others on the Lord`'s account.

Fourthly, I have no doubt in my heart that the Lord will deliver us.
The strength of man, the resolution of man, is nothing in my eyes compared with the Lord.
Whom the Lord loves, He can save at His pleasure.
Has he begun to break our bonds and deliver us, and shall we now distrust Him?
Are we in a worse condition than Israel was, when the sea was before them,
the mountains on each side, and the Egyptians pursuing behind them?
He indeed that looks with man`'s eye, can see no ground of hope,
nor hardly a possibility of deliverance; but, to the eye of faith,
it is now nearer than when God began first to deliver.

Fifthly,
it is the delight and glory of the Lord to deliver His people
when it seems impossible to the eye of sense.
It is then that the Lord delights to stretch forth His arm, when no one else can help.
And it is then that it pleases Him to deal with the enemies of His truth and people,
when they are lifted up above the fear of Him,
and are ready to say in their hearts concerning His people, "`They are now in our hands,
who can deliver them?`"

Well, were it not in love to you, and in pity concerning what will certainly befall you,
if you go on in this course, I could say in the joy of my heart,
and in the sense of the good-will of my God to us,
who allows these things to come to pass: go on, try it out with the Spirit of the Lord.
Come forth with your laws, and prisons, and spoiling of our goods, and banishment,
and death, and see if you can carry it out.
For we do not come forth against you in our own wills,
or in any enmity against your persons or government,
or in any stubbornness or refractoriness of spirit;
but with the lamb-like nature which the Lord our God has begotten in us,
and which is taught and enabled by Him both to do His will,
and to suffer for His name-sake.
And if we cannot thus overcome you, even in patience of spirit, and in love to you;
and if the Lord our God is pleased not to appear for us,
we are content to be overcome by you.
So may the will of the Lord be done, says my soul.

--

This the author concludes with a postscript,
containing a serious exhortation to forsake evil.
Besides this,
he gave forth another paper wherein he proposed the following
question to the king and both houses of parliament:
"`Whether laws made by man, in equity,
ought to extend any further than there is power in man to obey?
And if it is not cruel to require obedience in such cases
wherein the party has not a capacity in him of obeying?`"
And to explain this a little further, he said, "`In things concerning the worship of God,
wherein a man is limited by God Himself, both in what worship he will perform,
and what worship he will abstain from,
here he is not left at liberty to obey what laws
shall be made by man that are contrary thereto.`"
Thus Penington strove by writing to show the persecutors the evil of their doings.
Nevertheless, a fierce party prevailed at that time,
and the clergy continually blew upon the fire of persecution.
Indeed, many presumed that the time had now totally come to destroy the Quakers;
and in December twelve more were condemned to banishment.

Concerning those banished who now lay in a ship in the River Thames,
I will yet leave them there, and look again to George Fox,
who in the foregoing year we left in prison at Lancaster.
In the month called March of this year he was brought
again to his trial before judge Twisden;
and though judge Turner had given charge at the court session before,
to see that no such gross errors were in the indictment as before,
yet in that respect this was not much better than the former,
though the judge examined it himself.
The jury then being called in to be sworn,
and three officers of the court having testified that the
oath had been tendered to him at the last court session,
according to the indictment, the judge then asked him what he had to say to it,
and whether he had taken the oath at the last court session?
George Fox thereupon gave an account of what had been done at that time,
and how he had said that the book which they gave him to swear upon, says,
"`Swear not at all.`"
And repeating more of what he spoke then, the judge said,
"`I will not dispute with you except in point of law.`"
George Fox offering to speak something to the jury concerning the indictment,
he was stopped by the judge.
Fox then asked him whether the oath was to be tendered to the king`'s subjects only,
or to the subjects of foreign princes?
The judge replied, "`To the subjects of this realm.`"
"`Well,`" said Fox, "`look to the indictment,
and you may see that the word '`subject`' is left out of this indictment also.`"
Several other great errors as to time and date he also observed in the indictment,
but no sooner had he spoken concerning the errors, then the judge cried out,
"`Take him away jailer, take him away;`" and so he was hurried away.

The people thought he would have been called again; but that was not done.
After he was gone, the judge asked the jury whether they had come to an agreement?
They said, "`Yes,`" and gave judgment for the king and against him.
The reason why George Fox was led away so suddenly,
seemed to be that they expected he would have proved
the officers of the court to have sworn falsely,
seeing that the day on which the oath had been tendered to him
at the court session before was wrong in the indictment;
and yet they had sworn that on that day he had refused to take the oath.
Now, before George Fox was brought before the judge,
he had already passed a sentence of _premunire_ against
Margaret Fell for having refused to take the oath.
And though this sentence had not been passed against George Fox,
yet he was recorded as a premunired person;
though it had not been asked him what he had to say
why sentence should not be pronounced against him.
And so he continued prisoner in Lancaster castle.

While he was there, though weak of body, he wrote several papers;
but the neighboring justices labored much to get
him removed from there to some remote place;
for it was pretty well known among the people how the court had dealt with him.
So about six weeks later,
they got an order from the king and council to remove him from Lancaster castle.
They also received a letter from the earl of Anglesey,
wherein it was written that if these things which
he was charged with were found to be true,
he deserved no clemency or mercy;
and yet the greatest matter they had against him was his refusal to take the oath.

His persecutors now having prepared for his removal,
the under sheriff and the head sheriff`'s men, together with some bailiffs,
came and fetched him out of the castle, when he was so weak by lying in that cold, wet,
and smoky prison, that he could hardly move or stand.
So they brought him down into the jailer`'s house
where justice William Kirby and several others were.
They called for wine to be given to him, but well knowing their malice against him,
he told them he would have none of their wine.
They then cried, "`Bring out the horses.`"
G+++.+++ Fox therefore desired that if they intended to remove him,
they would first show him their court order, or a copy of it.
But they would not show him any but their swords.
He then told them that no sentence had been passed upon him,
neither was he yet premunired that he knew of;
and therefore he was not made the king`'s prisoner, but was the sheriff`'s;
for they and all the country knew that he was not fully heard at the last court session,
nor allowed to show the errors that were in the indictment,
which were sufficient to quash it.
And they all knew there was no sentence of premunire passed upon him;
and therefore he not being the king`'s prisoner, but the sheriff`'s,
desired to see their order.
But instead of showing him their order, they hauled him out,
and lifted him upon one of the sheriff`'s horses;
for he was so very weak that he was hardly able to sit on horseback.
Riding thus along the street, he was much gazed upon by the people,
and had great reason to say that he received neither Christianity, civility,
nor humanity; for regardless of how ill and weak he was,
yet they hurried him away about fourteen miles to Bentham in Yorkshire;
and so wicked was the jailer, one Hunter, a young fellow,
that he lashed the horse on which G. Fox rode with his whip,
in order to make him skip and leap, insomuch that he had much difficulty to sit upon him.
Then this shameless fellow would come and, looking him in the face, say, "`How do you do,
Mr. Fox?`"
To which George answered, that it was not civil of him to do so.
Yet this malicious fellow seemed little to regard it;
but he had not long to delight in this kind of insolence;
for he was soon after cut off by death.

G+++.+++ Fox having come to Bentham, was met by a marshal, several troopers,
and many of the gentry,
besides an abundance of people who had come there to stare at him.
Having entered the house, and being very tired,
he desired that they would let him lie down on a bed, which the soldiers permitted;
and the marshal, to whom he was delivered, set a guard about him.
After having stayed there a while, they got horses,
and sending for the bailiff and the constables, they took him to Giggleswick that night.
There they raised the constables, who sat drinking all night in the room next to him,
so that he could get but little rest.
The next day, coming to a market town, several of his friends came to see him,
and at night he asked the soldiers where they intended to carry him?
To which some said, "`beyond the sea,`" and others "`to Tinmouth Castle.`"
And though there was a fear among them that some might attempt to rescue him,
there was not the least reason for it.
The next night he was brought to York, where the marshal put him into a great chamber,
where many of the troopers then came to him.
He then speaking something by way of exhortation to the soldiers,
many of them became very loving to him.
A while after this, the lord Frecheville, who commanded that troop of horsemen,
came to him and was civil and loving,
and G. Fox gave him an account of his imprisonment.

After a stay of two days at York,
the marshal and five soldiers were sent to convey him to Scarborough Castle;
these behaved themselves civilly to him.
On the way they lodged at Malton, and permitted his friends to see him.
Afterwards having come to Scarborough, they brought him to an inn,
and gave notice of it to the governor, who sent six soldiers to guard him that night.
The next day they brought him into the castle,
and there put him into a room with a sentinel to watch him.
From this room they soon brought him into another,
which was so open that the rain came in, and it was exceedingly filled with smoke,
which was very offensive to him.

One day the governor, sir John Croslands, came into the castle with one sir Francis Cob.
George desired the governor to come into his room and see how it was;
they found it so filled with smoke, that they could hardly find the way out again.
This man being a Papist,
G+++.+++ Fox told him that this was his purgatory which they had put him into.
It plainly appeared that he had been placed there with an intent to vex and distress him;
for after he had spent fifty shillings to keep out the rain,
and something else to ease the smoke, they put him into a worse room,
which had neither chimney nor fireplace; and lying much open toward the seaside,
the wind drove the rain in so strongly that the water not only ran about the room,
but also came up into his bed.
And he having no fire to dry his clothes when they were wet,
his body was benumbed with cold,
and his fingers swelled to that degree that one grew as big as two.
And so malicious were his persecutors that they would
hardly allow any of his friends to come to him;
not so much as to bring him a little food,
so that he was forced to hire somebody to bring him his necessaries.
Thus he spent about a quarter of a year,
and afterwards being put into a room where a fire could be made,
he hired a soldier to fetch him what he needed.
He then ate almost nothing but bread, and so little of this,
that a threepenny loaf commonly served him for three weeks.
Most of his drink was water with wormwood steeped in it;
and once when the weather was very sharp, and he had taken a great cold,
he was given some elecampane beer.

Now, though he desired his friends and acquaintances might be permitted to come to him,
yet this was refused; but some others were admitted to come and gaze upon him,
especially papists.
Once, when a great company of them had come, they affirmed that the Pope was infallible,
and had been so ever since St. Peter`'s time.
But G. Fox denied this, alleging from history that Marcellinus,
one of the bishops of Rome, had denied the faith and sacrificed to idols,
and therefore was not infallible.
He said also, "`If the papists were in the infallible spirit,
they would not maintain their religion by jails, swords, gallows, fires, racks,
and tortures, etc., nor need such means to sustain it.
For if they were in the infallible spirit, they would preserve men`'s lives,
and use none but spiritual weapons in matters of religion.`"
He also told them how a certain woman who had been a papist,
but afterwards entered into the society of those called Quakers,
having a tailor at work at her house,
and speaking to him concerning the falseness of the popish religion,
was threatened to have been stabbed by him, for which end he drew his knife at her;
saying it was one of the principle of the papists, if any turn from their religion,
to kill them if they can.
This story he told the papists, and they did not deny this to be their principle,
but asked if he would declare it abroad.
And he said, "`Yes, such things ought to be declared abroad,
that it may be known how contrary your religion is to true Christianity.`"
Whereupon they went away in a rage.

Some time after this another Papist came to discourse with him,
and said that all the patriarchs had been in hell,
from the time of creation until Christ came;
and that when Christ suffered He went into hell, and the devil said to Him,
"`What have you come here for, to break open our strong holds?`"
And Christ said, "`To fetch them all out.`"
And so, he said that Christ was three days and three nights in hell,
to bring them all out.
Upon which G. Fox told him that this was false; for Christ had said to the thief,
"`This day you shall be with me in paradise.`"
He also said that Enoch and Elijah were translated into heaven;
and that Abraham also was in heaven,
since the Scripture says that Lazarus went to his bosom.
And Moses and Elijah were with Christ upon the mount of transfiguration before He suffered.
With these instances he stopped his adversary`'s mouth, and put him to a stand.

Another time there came to him a great physician, called Dr. Witty,
being accompanied with the lord Falconbridge, the governor of Tinmouth Castle,
and several knights.
G+++.+++ Fox being brought before them, this doctor undertook to discourse with him,
and asked what he was in prison for?
G+++.+++ Fox told him, because he would not disobey the command of Christ and swear.
To this the doctor said he ought to swear his allegiance to the king.
But G. Fox knowing him to be a great Presbyterian,
asked him whether he had not first sworn against the king and the house of lords,
and taken the Scotch covenant;
and whether he had not since then sworn his allegiance to the king?
The doctor having no ready answer to this, G. Fox asked him,
"`What then is your swearing good for?`"
And further said, "`My allegiance does not consist in swearing,
but in truth and faithfulness.`"
After some further discourse, G. Fox was led away to his prison again.

A while after, this doctor came again, having many distinguished persons with him,
and affirmed before them all that Christ had not
enlightened every man that comes into the world;
that the grace of God, which brought salvation, had not appeared unto all men;
and that Christ had not died for all men.
G+++.+++ Fox then asked him what sort of men those were, whom Christ had not enlightened,
and to whom His grace had not appeared?
To this the doctor answered, "`Christ did not die for adulterers, and idolators,
and wicked men.`"
Then G. Fox asked him whether adulterers and wicked men were not sinners?
The doctor said, "`Yes.`"
This made G. Fox say, "`And did not Christ die for sinners?
Did He not come to call sinners to repentance?`"
"`Yes,`" said the doctor.
"`Then,`" replied G. Fox, "`you have stopped your own mouth.`"
And so he showed that the grace of God had appeared to all men,
though some turned His grace into licentiousness, and walked despitefully against it;
and that Christ had enlightened all men, though some indeed hated His light.
Several of those that were present confessed it was true;
but the doctor went away in a rage, and came no more to him.

Another time the governor came to him with two or three parliament-men
and they asked him whether he acknowledged ministers and bishops.
To this G. Fox said, "`Yes, those whom Christ sends forth;
such as have freely received and would freely give; and such as are qualified,
and are in the same power and Spirit that the ministers were in in the apostles`' days.
But such bishops and teachers as yours are,
that will do nothing without a great benefice, I do not acknowledge;
for they are not like the apostles.
For Christ said to His ministers,
'`Go into all nations and preach the gospel.`' But you parliament-men keep your
priests and bishops in such great fat benefices that you have spoiled them all;
for do you think they will go into all nations to preach,
or will go any further than their great fat benefices?
Judge yourselves, whether they will or not.`"
To this they could say little, and whatever was objected to G. Fox,
he always had an answer in readiness; and because sometimes it was simple and plain,
his enemies from there took occasion to say he was a fool.
But regardless what they said, it is certain that he had a good understanding,
though he was not educated in the schools of human learning.
This I know by my own experience, for I have had familiar conversation with him.

In this prison he was much visited, even by many people of note.
General Fairfax`'s widow once came to him with a great company,
one of which was a priest who began to quarrel with him,
because speaking to one person he said _thee_ and _thou,_ and not _you;_
and those that spoke so, the priest said, he counted but fools.
This made G. Fox ask him whether those who had translated the Scriptures,
and had made the grammar book were fools, seeing they translated the Scriptures so,
and made the grammar book so, _thou_ to one, and _you_ to more than one.
With these and other reasons he soon silenced the priest;
and several of the company acknowledged the truth he declared to them,
and were loving to him; and some of them would have given him money,
but he would not receive it.

While I leave him yet prisoner, I will go to other matters,
and relate the remarkable case of one William Dundas,
who being a man of some repute in Scotland,
came into the communion of those called Quakers in a remarkable manner.
He was a man of a strict life,
and observed the ecclesiastical institutions there
as diligently as any of the most precise;
but in time he saw that "`bodily exercises profited little,`"^
footnote:[1 Timothy 4:8]
and that it was true godliness which the Lord required from man.
In this state, becoming more circumspect than he was accustomed to be,
he did not frequent the public assemblies so much as formerly.
But this was soon taken notice of, and being asked the reason why,
he said that there was something beyond that, which he looked for.
Being then told that this was a dangerous principle,
Dundas replied that he was not to receive the law from the mouth of man.
Then the minister (so called) told him that he tempted God.
To which Dundas replied, that God could not be tempted to evil.
Now that which made him more averse to the priests of that nation,
was to see their domineering pride;
and how they forced some that were not one with them
in principle to comply with their institutions,
sprinkling the children of parents even without their consent.
Besides this, they often passed from one benefice to another,
being always ready to go over from a small church to a greater one,
under pretense of more service for the church;
whereas it plainly appeared that selfish interest generally was the main cause.
This behavior of the clergy, and their rigid persecution,
if any deviated a little from the church ceremonies and the common form,
turned Dundas`'s affection from them.

An instance of this rigidness appeared in the case of one Wood,
who had some charge in the custom-house of Leith;
and having approved in some respect the doctrine of those called Quakers,
he affirmed that Christ was the word, and that the letter was not the word.
For this he was cited before the ecclesiastical assembly of Lothian,
where Dundas was present.
But Wood so well defended his view, that none were able to overthrow his arguments;
chiefly drawn from these words of John, "`That the Word was made flesh,
and dwelt among us.`"
Wood continuing to maintain his assertion,
they began to threaten him with excommunication,
and would not allow him so much time as to give his answer at the next assembly.
Excommunication there was such a penalty,
that people under it were very much deprived of their interaction with men.
In a little time, the fear of this made Wood comply;
and meeting Dundas about three months afterwards in the street at Edinburgh,
he told him that he had been forced to bow to the assembly against his own light;
for if he had been excommunicated, he had lost his livelihood.
Thus Wood bowed through human fear, but he hardly outlived this two years.

In the meantime, the priests became more and more distrustful of Dundas;
for as he did not hold them in such an esteem as they wished,
they said that he would infect the whole nation.
And they did not stop here, but in order to know with whom he corresponded in England,
they opened (so great was their power) his letters at the post-house,
and sometimes kept them.
But if they found nothing in them by which they could prejudice him,
they caused them to be sealed up again and delivered to him.
By this base practice, they came to know that one Gawen Lawry, a merchant of London,
had sent him a box with about three pounds sterling worth of books.
Dundas found afterwards that the priest, John Oswald, had taken these books away;
and whatever he did, he could not get them again until the English came into Scotland,
but then many of them were missing.
Dundas in the meantime being unwilling to comply with the kirk,
he was at length excommunicated; but he was generally so well esteemed,
that none seemed to regard his sentence, so as to keep at a distance from him;
which made this act the more contemptible.
Now though Dundas favored the doctrine of the Quakers,
yet they were such a despised people, that he,
who was a man of some account in the world, could not as yet give up to join with them.

It happened once that he was riding from Edinburgh to his house in a winter evening,
and hearing a noise of some men fighting,
he bade his servant to ride up in haste to see what it was.
Having done so,
he called out that there were two men on horseback beating another on foot.
Dundas then riding up to them, saw the two beating the other man, who then said to them,
"`What did I say to you, except to bid you to fear God?`"
By this Dundas presently perceived that the man being beaten was a Quaker;
and upon asking his name, recognized it, though he did not know the man by sight.
Dundas then began beating the two with his rod,
and ordered those that were with him to carry them to the next prison;
but the said Quaker entreated him to let them go, which he did,
after having asked their names and dwelling-places.
About a week after this, the said Quaker spoke to a relation of Dundas,
and told what kindness he had showed him,
and how he had in some manner been saved by him; "`Yet,`" said he,
"`I found the same spirit in him that was in the other two men who beat me.`"
Such a remark as this would have offended some men,
but with Dundas it had a contrary effect; for these words so reached him,
that some time after meeting the said Quaker again,
he requested that whenever he passed that way, he would make his house his lodging place;
which kind invitation he seemed willing to accept.
Dundas had now attained so much experience,
that he could discern between the spirits of meekness and rashness;
but yet he could not bow so low as to join in society with the Quakers,
though he secretly endeavored more and more to live up to their doctrine,
and therein he enjoyed more peace in his heart than formerly.

But his outward condition in the world not being very prosperous, he went into France,
and settled at Dieppe.
While he dwelt there, a certain woman out of England came there with her maid,
and spread in the town some books of George Fox and William Dewsbury,
translated into French; and she herself having written some papers,
got them translated into French by Dundas, and so distributed them.
But the chief reason she came to that place she hid from him,
and that not without reason;
for what she acted there was so unusual that if it had been known before,
it is probable she would not have been able to perform it.
Though I do not know for certain what her intent was in this thing,
yet it seems likely to me that she, not knowing the language there spoken,
sought to testify by a sign against their proud apparel in the following way.
On the First-day of the week she came to the meetinghouse of the Protestants there,
where some thousands of people had met together.
And having set herself in the most conspicuous place, before the service was finished,
she stood up together with her maid,
took off a mantle and hood that she was covered with,
and appeared before all clothed wearing sack-cloth,
with her hair hanging down and sprinkled with ashes.
Thus she turned herself around several times, that all the people might see her.
This sight struck both preacher and auditory with no small consternation;
and the preacher`'s wife afterwards telling somebody how this sight had affected her,
said, "`This had a deeper reach than I can comprehend.`"
The said women having stood awhile, fell down upon their knees and prayed,
and then went out of the meeting with many following them,
to whom they distributed some books.
They then returned to their lodging, which was in a Scotchman`'s house;
but he refusing them entrance, they came to Dundas`'s lodging,
who knew nothing of all this.
They therefore told him that the work they had come for in that nation was now done.
He asking them what they had done, they told him,
and signified that they needed lodging until they went away.
Dundas went about to see if he could find lodging for them, but in vain,
and so offered them his bed, being willing to shift for himself somewhere else.
But the women refusing to accept of his offer,
and his landlady being unwilling to let them sit up that night in any of her rooms,
they were made to stay that night in an out-house.

Now this business had made such a stir in the town,
that one of the king`'s officers came the next day to Dundas,
and told him he had transgressed the laws of the nation
by receiving persons of another religion into his lodging;
for the king tolerated only two religions: Papists and Protestants.
To this Dundas said that he had not transgressed the law of hospitality,
and he had been forced to do so, since he could not let them lie in the street,
where they would have been in danger of their lives by the rude multitude.
The women were then taken away and sent to prison; and they not being provided with food,
Dundas took care of that.
Sometime after this, an order came from the parliament, at Rouen, and was read to them,
requiring that they be transported straightaway back to England with the first passage-boat,
and all their papers and books were to be burnt in the market, and themselves also,
if ever they should come to that nation again.
In pursuance of this,
they were put into a passage-boat during the night and so sent to England.

Afterwards the papists at Dieppe intended to pursue Dundas as one of their persuasion;
but he was unwilling to be looked upon as such,
though the Protestants had informed against him that he did not come to their meetings.
But of this no crime could be alleged, and Dundas told them that, if they persecuted him,
being a merchant and trading there,
they might expect the like to be done to their merchants in England.
And when the judge affirmed that Dundas was of the judgment of those two women,
he told them that they were better than he;
but that their way was too narrow for him to walk in.
There happened after this two remarkable things which Dundas took notice of; the one was,
that the Scotchman who shut out the women, died within twelve months after;
and the other, that the house of his landlady, who refused them a chamber to stay in,
burned down within the said time, without its being known from where the fire came;
and no house was burnt besides, though it was in the middle of the town.

In the meantime Dundas continued in an unquiet condition; for by reason of human fear,
he found himself too weak to profess publicly before
men what he believed to be the truth.
He then went to Rouen, but could get no rest there, being somewhat indisposed in body.
And having received a large number of books from England
treating of the doctrine of those called Quakers,
he sent some of them to the criminal judge at Dieppe,
and some to the Jesuits`' college there, and at Paris.
Afterwards he spread some books also at Caen where many Protestants lived.
But since these books spoke against papists,
and the Calvinists were in fear that thereby they might be brought into sufferings,
they complained of Dundas to the lieutenant-general of the
town as being one that did not come to their meetings.
By this he was forced to leave that place and went to Alencon, where staying a while,
the criminal judge sent for him, and after a long discourse,
he and Dundas agreed so well, that he invited him to come and see him more often,
and that if he so desired,
he might have an opportunity to discourse with some of the Jesuits.
But Dundas told him that he was not seeking to dispute with anyone,
though he should not be afraid to maintain his principles
against all the Jesuits of the nation.
This being told to the Jesuits, it so displeased them against him,
that once being out of town,
they caused his chamber-door to be broken down in order to search his lodging.
Complaining of this to the criminal judge, the judge told him that he knew nothing of it,
and if there was anything,
it surely proceeded from the Jesuits because of his confidence against them.
This seemed not improbable,
for several times he found his letters opened at the post-house,
and when he challenged the post-master about it,
he was told that the letters came to him in that condition.

Some time after this he returned to Caen,
where he had not been long when his correspondent at Alencon
sent him word that the day after he left from there,
the governor of the town had been at his lodging to seek for him.

In the next year, when a war arose between England and France,
he came again to Dieppe in order to return to England,
having acquired a passage in company with Lord Hollis, ambassador from England.
Having arrived, he frequently attended the meetings of those called Quakers,
but was not yet bold enough to acknowledge the name of Quaker,
and continued in the common way of salutations, etc.
Yet at length the truth that this people professed had such power over him,
that not being able to enjoy peace without yielding
obedience to the inward convictions upon his mind,
he finally gave up, and so entered into their society,
obtaining that true peace with the Lord which he had long reasoned himself out of.
In the process of time he published a book in print,
from which I have drawn this relation, which he concluded with a poem,
in which he thanked God for His remarkable dealings and mercies bestowed upon him,
wishing that others might reap benefit by it.

Thus parting with William Dundas, I am now to say, that in this year, 1665, in December,
William Caton died at Amsterdam.
He was a man not only of literature, and zealous for pure religion,
but of a courteous and amiable temper and conduct,
by which he was in good esteem among those he was acquainted with.
And as to the respect he had there, the following may serve as an instance.
Holland at this time being at war with England,
there were several English prisoners of war in the
prison of the admiralty court in Amsterdam,
who now and then were visited by Caton, and supplied with some food.
But in performing this service he was hindered by an officer of that court,
who seemed to be offended because Caton did not give him the hat honor.
This gave occasion to Caton to complain of if to the mayor of the city,
I believe the lord Cornelius Van Vlooswyh,
who at that time was one of the lords of the admiralty.
This man bid Caton to come to his house at such a time as he was to go to the court;
and when he did, he went with the said mayor towards the court.
Having come and again found that entrance was denied him by the aforementioned officer,
the mayor charged the officer not to hinder Caton from visiting the prisoners.

About this time a law was made in England called,
__An Act for Restraining Non-Conformists from Inhabiting in Corporations.__
This act was chiefly made against the Presbyterians and Independents
who formerly had been employed in the public church,
requiring an oath they they would not "`distill the poisonous principles
of schism and rebellion into the hearts of his majesty`'s subjects,
to the great danger of the church and kingdom.`"
All vicars, curates, lecturers,
and persons in holy orders were by this law required to take the follow oath:

[.embedded-content-document.legal]
--

I, +++_______+++ do swear, that it is not lawful upon any pretense whatsoever,
to take arms against the king;
and that I do abhor that traitorous position of taking arms against his person,
or against those that are commissioned by him, in pursuance of such commission;
and that I will not at anytime endeavor any alteration of government,
either in church or state; etc., on pain of forfeiting 40.

--

But though, as has been said,
this act was chiefly leveled against the Presbyterians and Independents,
yet they suffered but little by it.
It was, however, cunningly made use of to vex the Quakers, who,
because for conscience-sake they could not swear,
were on account of this law prosecuted and imprisoned, etc.

Now since the pestilence had been so fierce this year in London,
that about a hundred thousand people were swept away by it,
and also many of those called Quakers,
there were consequently many poor widows and fatherless
children among those of that society.
And because the men, who at times kept meetings to take care for the poor,
found that this burden grew too heavy for them,
they offered part of this service and care to the
most grave and solid women of their church,
who for this service met once a week at London;
and this in time gave rise to the women`'s monthly meetings in other places in England.

I return now to the ship with the banished prisoners which I left lying in the Thames.
The owners having put in another shipmaster whose name was Peter Love, the ship,
after long lingering, left the river and came into the Downs.
In the month called January of the ensuing year, Luke Howard wrote from Dover,
that of the fifty-four banished persons who almost
half a year ago had been brought on board,
only twenty-seven remained, the rest having died.
Because of this long delay, the ship several times needed a fresh supply of provisions,
and the ship`'s crew grew so uneasy,
that two of them having gone ashore with the small boat, ran away,
leaving their boat floating, by which it was dashed to pieces.
At length the master, though he had but few sailors, and these mostly raw men,
and though he was poorly provided with food, yet resolved to set sail.
So they weighed anchor, and went down the channel as far as Plymouth,
where after some stay, they set sail again,
which was on the 23rd of the month called February.
But the next day, having advanced as far as the Land`'s End,
a Dutch privateer came and took the ship; and to avoid being retaken,
went around the backside of Ireland and Scotland,
and so after three weeks arrived with some of the banished persons at Horn,
in North Holland, and some days later the rest of them also entered into that port.
Here they were kept some time in prison,
but the commissioners of the admiralty having understood that there was no likelihood
to get the banished Quakers exchanged for Dutch prisoners of war in England,
resolved to set them at liberty, and gave them a letter of passport,
along with a certificate that said they had not made an escape,
but were sent back by them.
Coming then to Amsterdam,
they were provided by their friends with lodging and clothes (for their
own necessities had been taken from them by the privateer`'s crew),
and in process of time they all returned to England, except one,
who not being an Englishman, stayed in Holland.
Thus the banished were delivered,
and the design of their persecutors was brought to nought by an Almighty hand.

In the meantime, G. Fox continued a prisoner in Scarborough Castle,
where the access of his friends was denied him,
though people of other persuasions were admitted.
Once, one doctor Cradock with three priests came to him,
accompanied by the governor and his wife, and many others besides.
Cradock asked him what he was in prison for?
He answered, for obeying the command of Christ and His apostle in not swearing.
"`But,`" said Fox, "`if you, being both a doctor and a justice of peace,
can convince me that after Christ and the apostle had forbidden swearing,
they later commanded christians to swear, then I will swear.`"
"`Here`'s a bible,`" he continued, "`show me any such command if you can.`"
To this Cradock said, "`It is written, you shall swear in truth and righteousness.`"
"`Yes`" said G. Fox, "`that was written in Jeremiah`'s time,
but that was many ages before Christ commanded not to swear at all.
But where is such a thing written after Christ forbade all swearing?
I could bring as many instances out of the Old Testament for swearing as you,
and it may be more too,
but of what force are they to prove swearing lawful in the New Covenant,
since Christ and the apostles forbade it?
Besides, where it is written,
'`You shall swear in truth and righteousness,`' was
this said to the Gentiles or to the Jews?`"
To this Cradock would not answer; but one of the priests said, "`It was to the Jews.`"
"`Very well,`" said G. Fox,
"`but where did God ever give a command to the Gentiles to swear?
For you know that we are Gentiles by nature.`"
"`Indeed,`" said Cradock,
"`in the gospel-time everything was to be established
out of the mouths of two or three witnesses,
and there was to be no swearing then.`"
"`Why then,`" replied G. Fox, "`do you force oaths upon Christians,
contrary to your own knowledge of the gospel-times?
And why do you excommunicate my friends?`"
Cradock answered, "`For not coming to church.`"
"`Why,`" said G. Fox, "`you left us above twenty years ago, when we were but young,
to the Presbyterians, Independents, and Baptists, many of whom made spoil of our goods,
and persecuted us because we would not follow them.
Now we being but young, knew little then of your principles,
and those that knew them could have sent us your epistles;
for Paul wrote epistles to the saints, though he was in prison;
but we might have turned Turks or Jews for all we had from you for instruction.
And now you have excommunicated us, that is, you have put us out of your church,
before you have got us into it, and before you have brought us to know your principles.
Is not this madness in you to put us out, before we were brought in?
But what do you call the church?`"
he continued, "`That which you,`" replied Cradock, "`call the steeple-house.`"
Then G. Fox asked him, "`Was Christ`'s blood shed for the steeple-house?
Did He purify and sanctify the steeple-house with His blood?
And seeing the church is Christ`'s bride and wife, and that He is the head of the church,
do you think the steeple-house is Christ`'s wife and bride;
and that He is the head of that old house, or of His people?`"
"`No,`" said Cradock, "`Christ is the head of the people, and they are the church.`"
"`But,`" replied G. Fox,
"`you have given that title which belongs to the people to an old house,
and you have taught people to believe so.`"
He also asked him why he persecuted his friends for not paying tithes;
and whether God did ever give a command to the Gentiles that they should pay tithes;
and whether Christ had not ended tithes,
when He ended the Levitical priesthood that took tithes;
and whether Christ when He had sent forth His disciples to preach,
did not command them to preach freely, as He had given to them freely;
and whether all the ministers of Christ were not bound to observe this command of Christ.
Cradock then said he would not dispute that; and being unwilling to stay on this subject,
he turned to another matter.
But finding G. Fox never to be at a loss for answer,
and that he could get no advantage over him, he at length went away with his company.

With such people G. Fox was often troubled while he was prisoner there;
for most that came to the castle would speak with him,
and many disputes he had with them.
But with respect to his friends, he was as a man buried alive,
for very few of them were allowed to come to him.
Josiah Coale once desiring admittance, the governor told him,
"`You are an understanding man, but G. Fox is a mere fool.`"
Now, though the governor spoke harshly of him, yet in time he altered.
At one time, the deputy governor told G. Fox that the king,
knowing Fox had a great influence over the people,
had sent him there so that if there should be any stirring in the nation,
they should hang him over the wall.
And among the Papists also, who were numerous in those parts,
there was much talk then of hanging G. Fox.
But he told them that if that was it they desired, and the Lord permitted them,
he was ready, for he never feared death nor sufferings in his life;
but was known to be an innocent and peaceable man, free from all stirrings and plottings,
and one that sought the good of all men.
But the governor in time growing kinder,
G+++.+++ Fox spoke to him when he was about to go to the parliament at London,
and desired him to speak with esquire Marsh, sir Francis Cob, and some others,
and to tell them how long he had lain there in prison, and for what.
This the governor did,
and at his coming back told him that esquire Marsh said he knew G. Fox so well,
that he would go a hundred miles barefoot for his liberty;
and that several others at the court had spoken well of him.

After he had been prisoner in the castle there above a year,
he sent a letter to the king, in which he gave an account of his imprisonment,
and the harsh treatment he had met with there,
and also that he had been informed that no man could deliver him but the king.
Esquire Marsh, who was a gentleman of the king`'s bed-chamber,
did whatever he could to procure his liberty,
and at length obtained an order from the king for his release.
The substance of which order was,
"`That the king being certainly informed that G.
Fox was a man principled against plotting and fighting,
and had been ready at all times to discover plots, rather than to make any, etc.,
that therefore his royal pleasure was that Fox should be discharged from his imprisonment,
etc.`"
This order being obtained, was not long after brought to Scarborough,
and delivered to the governor, who upon the receipt thereof, discharged him,
and gave him the following passport:

[.embedded-content-document.legal]
--

Permit the bearer thereof, George Fox, recently a prisoner here,
and now discharged by his majesty`'s order, quietly to pass about his lawful occasions,
without any molestation.

[.signed-section-closing]
Given under my hand at Scarborough Castle, this first day of September,

[.signed-section-signature]
Jordan Croslands

[.signed-section-context-close]
Governor of Scarborough Castle.

--

G+++.+++ Fox being thus released,
would have given the governor something for the civility
and kindness he had of late showed him;
but the governor would not receive anything, and said,
whatever good he could do for him and his friends, he would do it,
and never do them any hurt.
So he continued loving to his dying day;
and if at any time the mayor of the town sent to him for soldiers
in order to disperse the meetings of those called Quakers,
if he sent any, he privately charged them not to meddle with the meeting.

The very next day after G. Fox was released, the great fire broke out in London,
and the report of it came quickly down into the country,
how the city had been turned into rubbish and ashes,
insomuch that after an incessant fire which lasted near four days,
but little of old London was left standing,
there being about thirteen thousand and two hundred houses burnt.
The account of this fire has been so circumstantially described by others,
that I need not treat of it at length; but I cannot omit to say that Thomas Briggs,
some years before passing through the streets of London,
preached repentance to the inhabitants; and coming through Cheapside,
he cried out that unless London repented as Nineveh did, God would destroy it.

[.offset]
Now I may relate another remarkable prediction.

Thomas Ibbitt, of Huntingdonshire,
came to London a few days before the burning of that city,
and as has been related by eye witnesses, did upon his coming there,
alight from his horse and unbutton his clothes in a loose a manner,
as if they had been put on in haste just out of bed.
In this manner he went about the city on the sixth (being the day
he came there) and also on the seventh day of the week,
pronouncing a judgment by fire which should lay waste the city.
On the evening of these days some of his friends had meetings with him,
to inquire concerning his message and his call to pronounce that impending judgment.
And in giving his account thereof,
he said that he received a vision of the fire some time ago,
but had delayed to come and declare it as he was commanded, until he felt,
as he expressed it, the fire in his own bosom.
This message or vision very suddenly proved to be sadly true,
as the foregoing brief account does in part declare.
The fire began on the 2nd of September, 1666, on the first day of the week,
which did immediately follow those two days wherein the said Thomas
Ibbitt had gone about the city declaring the judgment.

Having gone up and down the city, as has been said,
when afterwards he saw the fire break out, and beheld the fulfilling of his prediction,
a spiritual pride seized upon him, which, if others had not been wiser than he,
might have tended to his utter destruction.
For the fire having come as far as the east end of Cheapside,
he placed himself before the flame, and spread his arms forth,
as if to stay the progress of it; and if one Thomas Matthews, with others,
had not pulled him from there (who now seemed to be altogether beside himself),
it is likely he might have perished in the fire.
Yet in the process of time, as I have been told, T. Ibbit came to some recovery,
and confessed this error, giving evident proof of human weakness,
and a notorious instance of our frailty,
when we assume to ourselves the doing of anything which heaven alone can enable us.

I cannot well pass by this event without taking notice of how,
about three weeks before the said fire,
the English landed in the island of Schelling in Holland,
under the charge of captain Holmes, and setting the town on fire,
there were above three hundred houses burnt down,
belonging mostly to Baptists that did not bear arms.
It may be further observed, that the English were beaten at sea this summer by the Dutch,
under the charge of admiral De Ruyter, in a fight which lasted four days.
Thus the English had occasion to call to mind how
often these judgments of God had been foretold them,
which now came over their country, namely: pestilence, war, and fire.

G+++.+++ Fox being at liberty, did not fail to visit his friends,
and in their meetings to edify them with his exhortations,
whereby others sometimes came to be convinced.
And coming to Whitby, he went to a priest`'s house,
who fourteen years before had said that if ever he
met G. Fox again he would have his life,
or Fox should have his.
But now his wife had not only become one of G. Fox`'s friends,
but this priest himself favored the doctrine professed by his wife,
and was very kind to G. Fox, who passed from there to York, where he had a large meeting,
and visited also justice Robinson, who had been loving to him from the beginning.
At this time there was a priest with him, who told G. Fox,
"`It is said of you that you love none but yourselves.`"
But George showed him his mistake, and gave him so much satisfaction,
that they parted friendly.

In this county G. Fox had many meetings, and one not far from colonel Kirby`'s abode,
who had been the chief means of his imprisonment at Lancaster and Scarborough castles;
and who, when he heard of his release, said he would have him taken prisoner again.
But now, when G. Fox came so near him, he himself was caught by the gout,
which seized him so strongly that he was made to stay in his bed.
Kirby afterwards met with other adversities,
as did most of the justices and others who had been
the cause of the imprisonment of G. Fox.
Coming now to Synder-hill Green, G. Fox had a large meeting there,
where the priest sent the constable to the justices for a warrant;
but the notice being short and the way long,
and having spent time in searching for Fox in another house,
the meeting had ended before the officers came there,
though they had almost spoiled their horses by hard riding.

G+++.+++ Fox passing from there through Nottinghamshire, Bedfordshire, Buckinghamshire,
and Oxfordshire, and visiting his friends in all places where he came,
and edifying them in their meetings, came at length to London.
But by this time he was so weak from having lain
almost three years in hard and cold imprisonments,
and his joints and body were so stiff and benumbed,
that he could hardly get on horseback.

Being now at London, he beheld the ruins of the city,
and saw the fulfilling of what had been shown to him some years before.
But notwithstanding this stroke on London, persecution did not cease,
which gave occasion to Josiah Coale to write these lines to the king:

[.embedded-content-document.letter]
--

[.salutation]
King Charles,

Set the people of God at liberty,
who suffer imprisonments for the exercise of their conscience towards Him,
and give liberty of conscience to them to worship and serve
Him according as He requires and leads them by His Spirit;
or else His judgments shall not depart from your kingdom,
until thereby He has wrought the liberty of His people, and removed their oppressions.
And remember you are once more warned,

[.signed-section-closing]
By a servant of the Lord,

[.signed-section-signature]
Josiah Coale

[.signed-section-context-close]
London, Dec. 2nd, 1666.

--

About this time, or it may be in the next month, Stephen Crisp published an epistle,
containing an exhortation to his friends,
and also a prediction concerning succeeding times, which is as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Friends,

I am drawn forth at this time to visit you with an epistle,
because the Lord has given me some sight of His great and dreadful day,
and His workings in it, which is at hand, and greatly hastens.
Concerning this I have something to say unto you,
that you may be prepared to stand in His day,
and may behold His wondrous working among His enemies,
and have fellowship with His power therein,
and may not be dismayed nor driven away in the tempest, which will be great.

With regard to the succeeding times,
the Spirit of the Lord has signified that they will
be times of horror and amazement to all that know,
and yet do reject His counsel.
For as the days of His forbearance, warning and inviting, have been long,
so shall His appearance among those that have withstood Him be fierce and terrible;
even so terrible, that "`who shall abide His coming?`"
For the Lord will work both secretly and openly,
and His arm shall be manifest to His children in both.
Secretly He shall rise up a continual fretting anguish among His enemies,
one against another,
so that being vexed and tormented inwardly they shall seek to make each other miserable,
and delight therein for a little season.
And then the prevailer must be prevailed over,
and the digger of the pit must fall therein;
and the confidence that men have had one in another shall fail,
and they will beguile and betray one another, both by counsel and by strength.
And as they have banded themselves together to break you (whom God has gathered),
so shall they band themselves one against another,
to break and spoil and destroy one another.
And through the multitude of their treacheries, all credit or belief in them shall fail;
so that few men shall count themselves, or what is theirs,
safe in the hand of any friend who has not chosen his safety and
friendship in the pure light of the unchangeable truth of God.
All the secret counsels of the ungodly shall be brought to nothing,
sometimes by the means of themselves,
and sometimes by impossibilities lying in their way,
which shall make their hearts fail of ever accomplishing what they have determined.

In this state men shall fret themselves for a season,
and shall not be able to see the hand that turns against them,
but shall turn to fight against one thing, and another, and a third thing,
and shall stagger and reel in counsel and judgment as drunken
men that know not where to find the way to rest.
And when they do yet stir themselves up against the holy people,
and against the holy covenant of light, and those who walk in it,
they shall be but the more confounded; for His people shall be helped with a little help,
which all the ungodly shall not hinder, namely, the secret arm of the Lord,
maintaining their cause,
and raising up a witness in the very hearts of their adversaries to plead their innocency,
and this shall cause them yet the more to trouble themselves.
For when the enemies of truth shall look upward to their religion, to their power,
policy, preferments, friendships, or whatever else they had trusted in and relied upon,
they shall then have cause to curse it.
And when they look downwards to the effects produced by all those things, behold,
then trouble, horror, and vexation will take hold on them, and drive them to darkness.
And so having no help but what is earthly,
and being outside of the knowledge of the mighty overturning power of the Lord God Almighty,
they shall despair and wear out their days with anguish.

Besides all this, the terrible hand of the Lord is, and shall be,
openly manifested against this ungodly generation,
by bringing grievous and terrible judgments and plagues upon them,
tearing down all things in which their pride and glory stood,
and overturning even the foundations of their strength.
Yes, the Lord will lay waste the mountain of the ungodly,
and the strength of their fenced city shall fail.
Ah!
My heart relents, and is moved within me in the sense of these things,
and much more than I can write or declare, which the Lord will do in the earth,
and will also make haste to accomplish among the sons of men,
in order that they may know and confess that the
Most High does rule in the kingdoms of men,
and pulls down and sets up according to His own will.
And this shall men do before "`seven times`" pass over them,
and shall be content to give their glory unto Him that sits in heaven.

But, oh friends, while all these things are working and coming to pass,
repose yourselves in the fortress of that Rock which all these shakings shall not move,
even in the knowledge and feeling of the eternal power of God,
keeping you given up to His heavenly will.
Feel this daily to kill and mortify that which remains of this world in any of you;
for the worldly part in any is the changeable part, which is up and down, full and empty,
joyful and sorrowful, according as things go well or ill in the world.
For as the truth is but one, and many are made partakers of its spirit;
so too the world is but one, and many are partakers of the spirit of it;
and as many as do partake of it, will be distressed and perplexed with it.
But they who are single to the truth,
waiting daily to feel the life and virtue of it in their hearts,
these shall rejoice in the midst of adversity.
The hearts of these shall not be moved with fear,
nor tossed with anguish because of evil tidings (Psalm 112:7-8),
because that which anchors them remains with them.
These shall know their entrance with the bridegroom and so be kept from sorrow,
though His coming be with a great noise.
And when night has come upon all man`'s glory, yet these being ready and prepared,
will find that it is well with them;
and having a true sense of His power working in themselves,
they cannot help but have unity and fellowship with the works of His power in the earth,
and will not at all murmur against what is taking place, nor wish it were different.
These will be at rest till the indignation passes over,
and having no design to carry on or promote any party in the earth,
they cannot possibly be defeated or disappointed in their undertakings.

And when you see divisions, and parties, and rending in the heart of nations,
and rumors and tempests in the minds of the people,
then take heed of being moved to this or that party,
or giving your strength to this or that way, but stand single to the truth of God,
in which there is neither war, rent, or division.
And take heed of that part in any of you which trusts and
relies upon men of this world in the day of their prosperity;
for the same party will bring you to suffer with them in the time of their adversity,
which will not be long after.
For there will be no stability in that ground; but when they shall say,
"`come join with us in this or that,`" remember you
are already joined to the Lord by His pure spirit,
to walk with Him in peace and in righteousness; and feeling this,
you will be gathered out of all bustlings, and noises, and parties, and tumults,
and be led to exalt the standard of truth and righteousness by your innocent conduct.
So many shall be turned to the truth, and it shall be a refuge for many of the weary,
tossed, and afflicted ones in those days,
and a shelter for many whose day of visitation is not yet over.

So dearly beloved friends and brethren,
who have believed and known the blessed appearance of the truth,
let not your hearts be troubled at any of these things.
Oh let not the things that are at present, nor things that are yet to come,
move you from steadfastness; but rather double your diligence, zeal,
and faithfulness to the cause of God.
For they that know the work already wrought in themselves,
shall rest in the day of trouble.
Yes, though the fig-tree fail, and the vine brings not forth,
and the labor of the olive-tree ceases, and the fields yield no food,
and the sheep be cut off from the fold, and there be no bullocks in the stall,
yet then may you rejoice in the Lord, and sing praises to the God of your salvation (Hab.
3:16-17).

How near these days are to this poor nation, few know;
and therefore the cry of the Lord is very loud unto
its inhabitants through His servants and messengers,
that they would prize their time while they have it, lest they be overturned, wasted,
and laid desolate before they are aware, and before destruction come upon them,
and there be no remedy, as has already happened upon many.
Oh, London!
London!--that you and your rulers would have considered, and hearkened and heard,
in the day of your warnings and invitations, and not have persisted in your rebellion,
till the Lord was moved against you to cut off the
thousands and multitudes from your streets,
and the pressing and thronging of people from your gates,
and then to destroy and ruin your streets also, and lay desolate your gates,
when you thought to have replenished them again.

And oh, says my soul, that your inhabitants would yet be warned,
and be persuaded to repent and turn to the Lord,
by putting away the evil that is in their hearts
against the appearance of truth in yourselves,
and against those that walk in it,
before a greater desolation and destruction overtakes you.
Oh, what shall I say to prevail with London, and with its inhabitants!
The Lord has called aloud, He has roared out of Zion unto them,
but many of them have not hearkened at all, nor considered.

Well, my friends, (and you, oh my soul), return to your rest,
and dwell in the pavilion of the house of your God, and my God.
Shelter yourselves under the shadow of His wings,
where you shall be witnesses of His doings, and see His strange acts brought to pass,
but shall not be hurt therewith, nor dismayed.

Oh, my friends,
in the bowels of dear and tender love I have signified these things unto you,
that you might stand armed with the whole armor of God, clothed in righteousness,
and your feet shod with the preparation of the gospel of peace,
freely given up in all things to the disposing of the Lord, who will deliver us,
not by might, nor by sword, nor spear, but by His own eternal, invisible arm.
Yes, He will yet save us and deliver us, and get Himself a name by preserving us;
and we shall yet live to praise Him who is worthy of glory, of honor and renown,
from the rising of the sun to the setting of the same, now and forever, amen, amen,
says my soul.

[.signed-section-signature]
Stephen Crisp

--

The aforesaid Armorer came very often to the house of Thomas Curtis, at Reading,
to disturb the meeting there, taking many persons prisoners,
on one occasion thirty-four at a time, both men and women.
And when these were brought to their trial,
the oath was tendered them as the most ready means to ensnare and to keep them in prison.
Among the prisoners taken out of the meeting was one Henry Pizing,
who coming to the bar with his hat in his hand, judge Thomas Holt said,
"`Here is a man that has some manners,`" and asked
him if he would take the oath of allegiance?
To this Pizing answered that he had taken it twice already.
"`But`" said the judge, "`You were no Quaker then.`"
To which the said Henry replied, "`Neither am I now,
but I have been many weeks among them, and I never met with any hurt by them,
but found them to be an honest and civil people.`"
Upon hearing this, William Armorer, who had taken him prisoner said,
"`Why did you not tell me so before?`"
to which Henry replied, "`Your worship was so wrathful, that you would not hear me.`"
Then the judge said, "`He must take the oath again.`"
The oath being read, he took it, upon which they let him go free without paying any fees.
But they requiring him to go out at a back door, and to come no more among the Quakers,
Pizing replied "`I hope that, now I am free, I may go out which door I wish.`"

Thomas Curtis afterwards being called,
the judge asked him if he would take the oath of allegiance?
To this he answered that he did not refuse the oath upon
the account of not bearing allegiance to the king,
but because Christ had commanded not to swear at all;
for he was persuaded that he had manifested himself to be
as good a subject to the king as most in the county,
since he came into it, and that if he could take any oath,
either to save his estate or life, he professed he would begin with that oath.
He then requested that the court would be pleased to let
some of their ministers show him by the Scriptures,
how he might take it and not break the command of Christ.
The judge then called to one Worrel, a priest that was near him,
and desired him to satisfy Curtis in that particular.
But the priest putting off his hat, and bowing to the court, desired to be excused,
saying, he had spoken with some of them already,
but they were an obstinate people and would not be satisfied.
"`Aye,`" said Curtis, "`this is commonly the answer we have from these men,
when they are requested to answer us a question according to the Scripture;
for when we make it appear that they give no satisfactory answer to the question,
they say, we are obstinate.`"
Curtis (whose wife Anne was a daughter of the sheriff of Bristol,
who had been hanged near his own door for endeavoring to
bring in the king) was released after a short time.
But soon after this he was taken prisoner again by Armorer,
who perceiving that he intended to have gone to the Bristol fair,
caused him to be brought to an inn, where he told him, "`You are going to Bristol fair,
but I will stop your journey.`"
And then commanding the constable to carry him to prison,
he was compelled there without a court order.

About this time Curtis`'s imprisoned friends wrote a paper,
and it is likely he had a hand in it,
to show the hurt and mischief proceeding from swearing.
This paper being sent by him to one of the magistrates,
and leave being given him to read it in the council chamber,
at the reading of these words,
"`Because of swearing the land mourns,`" alderman Johnson said it was very true.

Sometime after this it happened that Thomas Curtis,
his wife and man-servant all being prisoners,
Armorer sent his servant to inquire if there were any in the house besides the family.
The maid having answered no, Armorer came himself and knocked at the door;
but the maid being in fear, did not open it.
Armorer then pulling an instrument out of his pocket, picked the lock, entered the house,
and searching from room to room,
came at length to a room where he found one Joseph Coale, who dwelt in the house,
and was not well at that time.
Armorer taking him by the arm, and pulling him downstairs, said to him,
"`Will you take the oath of allegiance?`"
Coale refusing to do so was sent to the house of correction,
where the day before seven women, taken from a meeting, had also been brought.
This bold act of picking the lock was done at other times also,
and once when the maid had gone out to carry some
food to her master and mistress in prison.
While she was gone, he searched the warehouse, where there was much cloth;
and to a woman that was there, who spoke against his picking the locks, he said,
"`What have you to do with it?`"
And then said, "`Where`'s that whore?`"
meaning the maid servant.
The woman answered him that she did have to do with it,
for she was to see that nobody stole anything out of the house.

Besides this,
Armorer continually made it his business to disturb
the meeting which was commonly held twice a week.
At these times he used to curse, and to strike those he found there with a great cane,
always sending some to prison.
Having once caused three women to be brought before him from the house of correction,
he demanded they pay a fine for having been at a meeting.
To this, one Anne Harrison said, "`You have taken our house already that we built,
and our means to support ourselves; and would you have me pay more money now,
when I have broken no law?
Besides, there were but four of us above the age of sixteen years,
and the act says it must be above four.`"
To this Armorer said, his servant told him there were six, and two of them ran away.
"`That is false,`" said Anne, "`Frances Kent, being a midwife,
was fetched out of the town; and as for the sixth, she was not there.`"
But Armorer not regarding whatever Anne said, spoke in a rude manner, "`I shall get Mrs.
Kent as well, and then even if the best lady in the land has need of her,
she shall not go, except the king or court send for her.`"

If I should mention all the enormities of Armorer`'s violent behavior,
this relation would swell too large;
I therefore pass by most cases and touch upon but a few.
More than once it happened when the prisoners reproved Armorer for his injustice,
and put him in mind that he must eventually give an account for his bad deeds;
he in a most impudent manner said,
"`You shall see at the day of judgment whose ass will be blackest, yours or mine.`"
And when a prisoner told him that it was an uncivil
thing for one called a justice to speak such words,
he replied, "`Why, sirrah, what incivility is it?
Is not your nose your nose, and your ass your ass?`"
I pass by other absurdities the prisoners met with in the court,
along with how they were sometimes treated when they refused the oath.
From what has been said already in more than one place concerning similar cases,
one may easily guess how matters were transacted here,
which sometimes was so rudely that even the spectators showed their dislike.
When once for lack of good witnesses the jury could not come to an agreement,
Armorer rose off the bench and appeared as a witness himself.
But notwithstanding this,
the jury returned the second time and brought in a verdict of _ignorumus._
Upon hearing this, the other justice told the jury that sir William Armorer,
an honorable gentleman, had also taken his oath in this case.
To which the jury replied, it was true, sir William Armorer was an honorable gentleman,
but he was also a man subject to passion.
And they continuing unwilling to bring in the prisoners guilty,
the two justices Proctor and Armorer (for there were then
no more on the bench) still refused to discharge the prisoners,
and instead sent them again to jail as "`seditious persons;`"
for Proctor had told the jury the day before,
that if they did not bring in the prisoners guilty,
it would appear that William Armorer and the clerk had sworn falsely.

Anne, the wife of Thomas Curtis,
being called to the bar and asked if she would take the oath, said,
"`I look on it as a very hard thing that I should be required to take this oath,
being under covert,^
footnote:["`Under covert`" was a legal status in common law whereby, upon marriage,
a woman`'s legal rights and obligations were subsumed by those of her husband.
An __unmarried__ woman had the right to own property and make contracts in her own name.
But a woman "`under covert`" was legally considered one person with her husband,
and was not recognized as having legal rights and
obligations distinct from those of her husband.]
and my husband being currently a sufferer for the same thing.
For there is no other woman in England, that I have heard of,
who is under covert and is also required to take that oath,
and kept in prison on that account.`"
But Armorer, full of passion, cried, "`Hold your tongue, Nan, and turn your back!`"
And so she, with another woman that had also been required to take the oath,
was sent back to jail "`as dangerous and suspected persons.`"
At length some justices procured her liberty,
and this so displeased Armorer that he did not rest before he had her in prison again.
But it seems that some others so eagerly desired her liberty,
that she was discharged a second time,
though her husband`'s goods and money had been seized.
I cursorily skip over how a prisoner who spoke something
in his own defense was threatened to be gagged,
how young girls were sent by him to the house of correction,
and how Armorer coming in winter-time into the meeting,
threw water in a nasty bowl in the faces of some young maidens.
But he seemed exceedingly offended with Anne Curtis, who being a witty woman,
did not omit when occasion was offered, to tell him of his uncivil behavior.
He therefore soon had her in jail again;
and when it was proposed in the summer-time to discharge
some of the prisoners because of the extreme hot weather,
provided they gave security, Armorer said, "`No, Mrs.
Curtis shall not go out, even if she will give security,
but she shall lie in jail till she rot.`"
But regardless of his wickedness,
yet he could not prevent that all his exorbitant behavior
against the Quakers was published in print.

But such conduct was at that time no rare or uncommon thing;
for since persecution was continually cloaked with a pretense
of rebellion and sedition all over the country,
there were many who persecuted the Quakers to the utmost of their power.
Among others, there was one Henry Marshall, priest at Crosthwait in Westmoreland,
who having several benefices and a large maintenance from the church,
yet kept poor people of that persuasion in prison for not paying tithes to him;
and once he said very presumptuously from the pulpit,
that "`not one Quaker should be left alive in England.`"
But after making this rash assertion he did not live long;
for as he was going half-undressed to his chamber to bed,
he fell down a flight of stairs, as was concluded from the circumstances;
for he was found lying on the floor with his skull broken, wrestling with death,
without being able to speak one word.
He died leaving his wife and children in such a condition,
that by reason of debts they fell into poverty.

About this time a certain papist author,
who expressed his name no further than with the letters A. S.,
gave forth a book called, [.book-title]#The Reconciler of Religions;
or, A Decider of all Controversies in Matters of Faith.#
Josiah Coale, who was very zealous for the truth, and well saw what this author aimed at,
answered him in a book that appeared in print, with the title of, [.book-title]#The Whore unveiled;
or The Mystery of the Deceit of the Church of Rome Revealed.#
Now although the said A. S. chiefly struck at the Quakers as the worst of heretics,
falsely perverting their doctrine as asserting that
the same spirit that reproved Judas of sin,
also induced him to hang himself;
yet he failed not to attack the doctrine of other Protestant societies.
He affirmed the Roman church to be the true church,
from which these had unjustly departed, and to whom they must all return again;
for the Roman, said he, was the holy catholic and apostolic church, which was infallible,
and could not err, and had the power to work miracles.
He also asserted that she was one in matters of faith,
that she was governed by one invisible head Christ, and by a visible head, the Pope;
and that therefore she was the true church, etc.
Josiah Coale did not fail to answer all of these pretenses distinctly and emphatically;
for he was an undaunted and zealous disputant.
Besides the superstition, idolatry,
and cruel persecution of the Roman church which had taken
away the lives of many thousands of honest and pious people,
Josiah Coale supplied abundant matter to demonstrate other papist errors,
and clearly to prove it to be a false church.
For though he did not deny that the true church was universal,
yet he denied that the universality of the Church of Rome
was a sufficient argument to prove her to be the true church.
"`What church,`" he queried, "`is more universal than the great whore, the false church,
who had a name written, '`Mystery Babylon the Great, the Mother of Harlots,
and Abominations of the Earth,`' who sits upon the waters, which are peoples,
and multitudes, and nations, and tongues?
And did not the whole world marvel after the beast that carried the whore?
Did she not sit as queen over them all, with her fair religious profession,
or golden cup in her hand, full of abominations and the filthiness of her fornication?
And did not all the inhabitants of the earth, and the kings of the earth,
drink of the wine of her fornication and commit fornication with her?
Mark how universal was this great whore--the false church--and how confident she was;
for she said in her heart that she would see no sorrow, glorified herself,
and reigned over the kings of the earth.
Is not this the very state of the Church of Rome at this day?
Does she not reign over the kings of the earth?
And has she not done so long, even for many ages?
And that she has exercised authority over kings may
appear from the case of the emperor Frederick,
who was made to hold the Pope`'s stirrup while he got on horseback.
And did not the great whore, which John saw,
drink the blood of the saints and martyrs of Jesus?
Surely the histories of many generations past testify to this.`"
In this way Josiah Coale encountered the masked A. S.,
and in a copious way answered his assertions.
And as he answered these and other objections at length,
so he also showed the vanity of their boast of miracles,
of which the Church of Rome gloried;
and he refuted all the falsities which that anonymous
author had belched out against the Quakers,
declaring they were a people that might be wronged without incurring any danger.
But I omit to recite all J. Coale`'s answers for brevity sake.

Thus zealously J. Coale wrote against popery; and yet such has been the malice of many,
that they represented the Quakers as favorers of the Church of Rome,
though on many occasions they had effectually shown the contrary.
But their enemies endeavored to brand them many ways,
and left no stone unturned to blacken them;
to which sometimes false brethren gave occasion.
For about this time there were still adherents of the aforementioned John Perrot,
who often ill-treated and spoke evil of those who did not approve their absurdities.
The revilings of Perrot and his followers fell also upon Richard Farnsworth,
one of the first preachers among those called Quakers,
though he was a man of a notable gift,
and on his dying bed he gave evidences of a firm and steadfast trust in God.
It was about this time that R. Farnsworth fell sick and died in London,
and among the many expressions which signified his good frame of mind,
and the divine consolation he felt, were also these words,
that were taken in writing from his mouth:

[.embedded-content-document.address]
--

[.salutation]
Friends,

God has been mightily with me, and has stood by me at this time.
His power and presence has accompanied me all along,
though some think that I am under a cloud.
But God has appeared for the acknowledging of our testimony,
and has broken in upon me as a flood,
and I am filled with His love more than I am able to express.
Truly God has appeared for us.

--

This he spoke but a short time before his departure;
and exhorted his friends to faithfulness and steadfastness,
that nothing might be permitted to creep in of another nature than the truth they professed,
to intermix therewith, saying, "`No garment of mixed linen and wool must be worn.`"
He then spoke some other consolatory words,
and his last testimony was as a seal unto all the
former testimonies he had given for the Lord.
And after having lain yet an hour or two, he slept in peace with the Lord,
and left a good savor behind him with all who truly were acquainted with him,
and knew how zealously he had labored in the ministry of the gospel for many years.

I now return again to G. Fox, who was this year not only in Wales,
but in several other places without being imprisoned.
However, at Shrewsbury, where he had a great meeting,
the officers were called together by the mayor to consult what to do against him,
since it was said, "`the great Quaker of England had come to town.`"
But they could not agree among themselves, some being for imprisoning him,
and others for leaving him alone; and because they were thus divided,
he escaped their hands.

As several eminent men among those called Quakers were taken away by death,
so others came in who filled their places.
Among these, and not one of the least, was Robert Barclay, son of colonel David Barclay,
descended from the ancient and famous family of the Barclays, and of Katharine Gordon,
from the house of the dukes of Gordon.
Robert, being born at Edinburgh in the year 1648,
was educated in France and trained up in literature,
having lived some years with his uncle at Paris,
where the Papists were very busy to bring him over to their religion.
But though at that tender age he seemed a little to hearken to them,
yet growing up in years, and so advancing in knowledge,
he soon got a clear sight of their errors.
During his stay in France, he not only became master of the French,
but also of the Latin tongue;
and after he had been instructed in the languages of the learned,
and other parts of human literature, he returned to Scotland.
But during his absence, his father had received the doctrine of the Quakers,
and showed by his pious behavior that he had not therein acted inconsiderately.
Robert Barclay having attained the age of nineteen years,
and having come to a good maturity of understanding,
found so much satisfaction in the religion which his father made profession of,
that he also embraced it,
and openly showed before all the world that the despised name of Quakers could not hinder
him from maintaining boldly that which he now apprehended to be the truth.
Indeed, he grew so zealous and valiant in the doctrine he now professed,
that he became a public promulgator of it,
and was often engaged in disputes with scholars, not only verbally, but also by writing.
For Robert Barclay was so skillful in school learning,
that he was able to encounter the learned with their own weapons,
and of such a quick apprehension, as not to be inferior to the most refined wits.
His meekness also was eminent,
and these qualifications were accompanied with such a wise deportment,
as rendered him very acceptable to others.
And though his natural abilities were great enough
to have made him surpass others in human learning,
and so to have become famous among men, yet he so little valued that knowledge,
that he in no way endeavored to be distinguished on that account.
But his chief aim was to advance in real godliness,
as the relationship I had with him undoubtedly assured to me;
for I was well acquainted with him.

I was also well acquainted with Roger Haydock of Lancashire,
a learned and intelligent man,
who about this time also came to enter into society with those called Quakers,
whose doctrine his eldest brother John Haydock had received before him.
But it so happened, that Roger once coming to his father`'s house,
was by his mother sent to discourse with his brother John,
in hopes that thereby he might draw him off from the way of the Quakers.
But John gave such weighty reasons for what he asserted to be truth,
that he quickly put Roger to silence.
This so displeased his mother, who was inclined to the Presbyterian way,
that she blamed him for not having held out longer against his brother.
But Roger told her, "`It is truth, and I dare not speak against it.`"
Being thus convinced, he also became a public professor of the doctrine of the Quakers,
and in time a zealous preacher of it too.
And he being a man of great abilities, well read and full of learning,
many times engaged in disputes with the priests,
sometimes making use of his pen also to that end.
He was an unwearied laborer,
and suffered the spoiling of his goods and several imprisonments;
and though he was attended with bodily weaknesses, yet he did not spare himself,
but travelled much to visit the churches in England, Scotland, Ireland, Holland, etc.
He continued steadfast to the end of his days; not only for which,
but also because of a special affection he bore to me,
his remembrance is dear to me still.

I must now make some mention again of Miles Halhead,
who has several times been named in this history.
This year coming into Devonshire, and being brought before the magistrates,
it was asked him what business he (who dwelt in Westmoreland) had in Devonshire?
To this he answered that he had come there to see his old friends, who formerly,
about ten years ago, he had some acquaintance with.
One of the magistrates asked him what were the names of those friends?
To which he replied, "`Sir John Coplestone, who was then high sheriff of Devonshire;
John Page, who was mayor of Plymouth; justice Howel,
who was then the judge of the sessions of Exeter, and colonel Buffet,
who was also a justice at that time.`"
One of the magistrates then said to the others, "`Truly, gentlemen,
this man calls these men his friends, yet they have been his persecutors.`"
Another of the magistrates then gave him an account
into what pitiful conditions those men had fallen,
and how they had lost their estates.
Indeed, colonel Buffet had been committed to prison for high treason,
escaped out of jail, and could not be found in his own country.
He further said to M. Halhead, "`Thus I have given you a true account of your old friends.
If these men were your persecutors, you may be sure they will trouble you no more;
for if they that trouble and persecute you have no better fortune than these men,
I wish that neither I, nor any of my friends, may have any hand in persecuting you.`"
And thus these discreet magistrates allowed him to go his way, without meddling with him.

Persecution at this time was not generally so hot in England as it had been before;
nevertheless the Presbyterians and some others dared not keep their public meetings,
lest they should be fined.
At times when they met together for worship, they have had tobacco pipes,
bread and cheese, and cold meat on the table,
having agreed before-hand that if the officers came in,
they would leave off their preaching and praying, and commence eating a meal.
This made G. Fox say to one Pocock, whose wife was one of his friends,
"`Is this not shameful to you who persecuted and imprisoned us, and spoiled our goods,
because we would not follow you and be of your religion, and called us house-creepers?`"
"`Well,`" said Pocock, "`we must be wise as serpents.`"
To this G. Fox replied, "`This is the serpent`'s wisdom indeed.
Who would ever have thought that you Presbyterians and Independents,
who persecuted and imprisoned others for not following your religion,
would now flinch away, and not stand to acknowledge your own religion.`"

G+++.+++ Fox travelled this year through England, and visited his friends in their meetings.
But I pass by his occurrences.
This year also a peace was concluded between England and Holland,
not long after the Dutch had burnt some of the king`'s ships in the Thames River.
