== Chapter XVII

[.section-date]
1668--1670

In the beginning of the year 1668, William Penn, son of admiral sir William Penn,
began to show himself openly an adherer to,
and an asserter of the doctrine of those called Quakers.
He had been trained up in the university of Oxford,
and he was afterwards by his father sent into France,
where for some time he lived (as he once told me) with the famous preacher,
Moses Amyrault.
After a considerable stay in that kingdom,
he returned home and then came for a time into Ireland,
where he attended a meeting of those called Quakers.
This meeting being broken up by magistrates,
he (though finely clothed as a young gentleman,
and wearing a large periwig) with several others was carried from there to prison,
where by conversation with his fellow prisoners,
he was more confirmed in that doctrine which he already apprehended to be truth.
But when it come to be known that he was the son of Admiral Penn, he was soon released.
This change grieved his father not a little,
who had intended to train him up for the court, but now saw his eldest son,
being in about the twenty-second year of his age,
enter into the society of the despised people called Quakers.
Several means were used to draw him off from his resolutions,
even withdrawing from him his necessaries.
But all devices and wiles proved in vain; for he continued steadfast,
and conversed much with Josiah Coale,
who likewise in his young years had came over to the Quakers.

This summer Stephen Crisp was prisoner at Ipswich,
where the number of friends had considerably increased by his ministry.
I, with some other friends of Holland, visited him there in prison,
and we found him in a cheerful condition, as well contented as if he had been at liberty;
for he suffered for the ministry of the gospel,
and continued to preach in prison when his friends came to visit him.

I pass by the journey which G. Fox made this year through England and Wales.
The latter part of the summer he returned to London,
where with great satisfaction I heard him preach several times before a numerous auditory;
for about this time, the meetings of dissenters were not disturbed in London.
Indeed, all was so quiet,
that the Quakers (so called) were allowed to build a large meeting place in Gracechurch-street,
where the first time a meeting was kept, I was present, and saw G. Fox,
and heard him preach there.

While he was at London, he paid a visit to esquire Marsh,
who now was a justice of the peace in Middlesex,
and it so happened that he was at dinner when G. Fox came to his house,
which so pleased him, that he kindly invited him to sit down with him to eat,
but G. Fox courteously excused himself.
There were at that time several notable persons at the table with justice Marsh,
who said to one of them, (a papist), "`Here is a Quaker you have not seen before.`"
From this the said papist took occasion to ask G. Fox whether
he did acknowledge the christening of children?
To this G. Fox answered that there was no Scripture for any such practice.
"`What!`" said he, "`Not for christening children?`"
"`No,`" replied G. Fox, "`the one baptism by the one Spirit into one body,
we acknowledge; but to throw a little water on a child`'s face,
and to call that baptizing and christening, there is no Scripture for that.`"
Then the papist asked him whether he did not acknowledge the catholic faith?
"`Yes,`" said G. Fox, "`but neither the Pope nor the papists were in the catholic faith;^
footnote:[The word catholic means universal.]
since the true faith works by love and purifies the heart;
and if they were in that faith which gives victory,
by which they might have access to God,
they would not talk to the people of a purgatory after death;
neither would they ever use prisons, racks, or fines,
to force others into their religion;
for this is not the practice of the apostles and primitive Christians;
but it was the practice of the faithless Jews and heathens to use such forcing means.
But,`" continued G. Fox, "`seeing you are a great and leading man among the papists,
and say there is no salvation but in your church, I desire to know of you,
what it is that brings salvation in your church?`"
To this the papist answered, "`A good life.`"
"`And nothing else?`"
said G. Fox.
"`Yes,`" replied the other, "`good works.`"
"`Is this your doctrine and principle?`"
asked G. Fox.
"`Yes,`" said he.
Then G. Fox replied, "`Then neither you nor the Pope,
nor any of the papists know what it is that brings salvation.`"
Then the papist asked him, "`What brings salvation into your church?`"
G+++.+++ Fox answered, "`The same that brought salvation to the church in the apostles`' days,
namely, the grace of God, which the Scripture says '`brings salvation,`'^
footnote:[Titus 2:11]
and has appeared to all men, and teaches us to deny ungodliness, and worldly lusts,
and to live godly, righteously, and soberly in this present world.
By this it appears, that it is not good works, nor a good life that brings the salvation,
but the grace.`"
"`What!`" said the Papist, "`does this grace, that brings salvation,
appear unto all men?`"
"`Yes,`" said G. Fox.
"`I deny that,`" returned the other.
"`All that deny it,`" replied G. Fox, "`are sect-makers,
and are not in the universal faith, grace, and truth, which the apostles were in.`"
Then the papist began to speak about the mother-church,
which gave occasion to much discourse,
and G. Fox asserted that if any outward place had claim
to be called the mother-church above all other churches,
then Jerusalem had much more right to it than Rome.
But in conclusion he said, "`there is no other mother-church but the heavenly Jerusalem,
which is above, and is free, and is the mother of us all, as the apostle says.`"

After some other discourse together, G. Fox,
got an opportunity to go aside with the said Marsh into another room,
and to request that seeing he had much of the management of affairs,
he would prevent the persecution of his friends as much as he possibly could.
Marsh showed himself not averse to this,
but said he was in a strait how to act between the Quakers and some other dissenters.
"`For,`" said he, "`you say you cannot swear, and the Independents, Baptists,
and Fifth-monarchy people, also say they cannot swear.`"
To this G. Fox said, "`I will show you how to distinguish:
the members of those societies you speak of do swear in some cases,
but we cannot swear in any case.
If anyone should steal their cows or horses,
and you should ask them whether they would swear they were theirs,
many of them would readily do it.
But if you try our friends, they cannot swear even for their own goods.
Therefore when you puts the oath of allegiance to any of them,
ask them whether they can swear in any other case; as for their cow or horse?
Which, if they be really of us, they cannot do,
though they will readily bear witness to the truth.`"
Then G. Fox gave Marsh a relation of a trial in Berkshire,
how a thief having stolen two animals from one of those called Quakers, was imprisoned.
But somebody having informed the judge that the man who prosecuted the thief was a Quaker,
and he, (the judge) perceiving that he would not swear,
refused to hear what the man could say,
but instead tendered him the oath of allegiance and supremacy, which the Quaker refusing,
the judge premunired him, and let the thief go free.

Esquire Marsh having heard this relation, said that judge was a wicked man.
And by what G. Fox had told him,
he sufficiently perceived how he might distinguish between the Quakers and other people.
True it is,
that the Baptists in those days made some profession of the unlawfulness of swearing,
but when they came to be tried on that account,
they soon desisted from that part of their profession,
as will be shown more at length in what follows.
But they and the Independents were very reluctant to take the oath of
allegiance principally because of a grudge they had against the government;
and this was well known to those that were in leadership.
But the Quakers were continually exposed to the malice of their persecutors,
and bore the hardest impact of the laws made against dissenters.
But now justice Marsh did not fail to free the Quakers
from persecution as much as was in his power;
for he kept several from being premunired in those parts where he was a justice.
And when sometimes he could not avoid sending those
that were brought before him to prison,
he sent some only for a few hours, or for a night.
And even this was such hard work for him,
that at length he told the king that he had sent some of
the Quakers to prison contrary to his conscience,
and that he could not do so any more.
He also advised the king to give liberty of conscience;
and was so serviceable to stop the violence of persecution,
that around this time little was heard about disturbing of meetings.

About the forepart of this year, if I mistake not, there occurred a case at Edmundsbury,
which I cannot well pass by in silence.
A certain young woman having delivered a bastard child, destroyed it,
and was therefore committed to prison.
While she was in jail, it is said that William Bennit, a prisoner for conscience-sake,
came to her and in discourse asked her whether during the course of her life,
she had not many times transgressed against her conscience?
And whether she had not often thereupon felt secret checks and inward reproofs,
and been troubled in her mind because of the evil committed?
This he did in such a convincing way,
that she not only assented to what he laid before her,
but his discourse so reached her heart, that she came clearly to see,
that if she had not been so stubborn and disobedient to those inward reproofs,
in all probability she would not have come to such a miserable place as she now was.
For man not desiring the knowledge of God`'s ways, and departing from Him,
is left helpless, and cannot keep himself from evil,
though it may be an evil that he formally would have abhorred in the highest degree,
and would have said with Hazael, "`What, is your servant a dog,
that he should do this great thing?`"^
footnote:[2 Samuel 9:8]
This wholesome admonition of W. Bennit did so work upon her mind,
that she who never had conversed with the Quakers
and was altogether ignorant of their doctrine,
now came to apprehend that it was '`the grace of God that
brings salvation`' which she had so often withstood;
and that this grace had not yet quite forsaken her,
but now made her sensible of the greatness of her transgression.
This consideration wrought so powerfully upon her, that from a most grievous sinner,
she became a true penitent,
and with hearty sorrow she cried to the Lord that it might
please Him not to hide His countenance from her.
And continuing in this state of humiliation and sincere repentance,
and persevering in supplication, she felt in time a measure of relief;
and giving heed to the exhortations of the said Bennit,
she attained at length to a sure hope of forgiveness
by the precious blood of the immaculate Lamb,
who died for the sins of the world.

Of this change she gave manifest proofs at her trial before judge Matthew Hale,
who having heard how penitent she was, eagerly desired to spare her,
and so purposely caused to be inserted in the indictment
that she had committed the fact "`willfully and designedly,`"
that from there she might find occasion to deny the charge,
and so to quash the indictment.
But she being asked according to the form, "`Guilty or not guilty,`" readily answered,
"`Guilty.`"
This astonished the judge, and therefore he told her,
that she seemed not to duly consider what she said,
since it could not easily be believed that such a one as she,
who perhaps inconsiderately had roughly handled her child,
should have killed it willfully and designedly.
Here the judge opened a back door for her to avoid the penalty of death.
But now the fear of God had gained so much room in her heart, that no tampering would do;
no fig leaves could serve for a cover,
for she knew now that this would have been adding sin to sin,
"`covering herself with a covering, but not of God`'s Spirit.`"^
footnote:[Isaiah 30:1]
She therefore plainly signified to the court that she had
indeed committed the mischievous act intentionally,
thereby to hide her shame for having a child out of wedlock;
and that she having sinned thus grievously, and being affected now with true repentance,
could by no means excuse herself,
but was willing to undergo the punishment that the law required;
and therefore she could not but acknowledge herself guilty,
since otherwise how could she expect forgiveness from the Lord?
This undisguised and free confession being spoken with a serious countenance,
did so affect the judge that tears trickling down his face, and he sorrowfully said,
"`Woman, such a case as this I never met with before.
Perhaps you, who are but young, and speak so piously,
as one being struck to the heart with repentance, might yet do much good in the world.
But now you force me, that __ex officio__^
footnote:[An obligation that one is under by virtue of their office.]
I must pronounce the sentence of death against you, since you will allow no excuse.`"

Standing firm in what she had said, the judge pronounced the sentence of death.
And when afterward she came to the place of execution,
she made a moving speech to the people, exhorting the spectators,
and especially those that were young, to have the fear of God before their eyes,
to give heed to His secret reproofs for evil,
so as not to grieve and resist the good Spirit of the Lord;
for not having minded this herself, it had made her run on in evil,
and thus proceeding from wickedness to wickedness,
it had brought her to this dismal scene.
But since she firmly trusted in God`'s infinite mercy, and truly believed that her sins,
though of a bloody dye, were washed away by the pure blood of Christ,
she could contentedly depart this life.
Thus she preached at the gallows the doctrine of the Quakers (so called),
and gave heart-melting proofs that her immortal soul was to enter into paradise,
not unlike that of the thief on the cross many centuries before.
I have been credibly informed by a person who had it from
the mouths of those who were present at the execution,
that in her request to God she prayed that it might please Him to give a visible sign,
that she had been received into His favor.
And that though it was then a cloudy day,
yet immediately after she was turned off the scaffold, the clouds broke a little,
and the sun for a few moments shined upon her face, and then the sky continued overcast.
She thus in a serious frame of mind, suffered death, which her crime justly deserved.

This year at London died Thomas Loe, a man of an excellent gift,
who had zealously labored in the ministry of the gospel in Ireland,
and by his preaching had brought many over into the society of his friends,
and among others William Penn, to whom on his deathbed he spoke these words:
"`Bear your cross, and stand faithful to God;
then He will give you an everlasting crown of glory that shall not be taken from you.
There is no other way which shall prosper than that
which the holy men of old have walked in.
God has brought immortality to light, and life immortal is felt.
Glory, glory to Him, for He is worthy of it.
His love overcomes my heart; oh my cup runs over.
Glory be to His name forever!`"
It is no wonder that these words,
coming from one who was at the point of entering into eternity,
served to further confirm William Penn in that doctrine
which he had already embraced as truth.
At another time Thomas Loe said to his friends who stood at his bedside,
"`Be not troubled, the love of God overcomes my heart.`"
And to George Whitehead and others he said, "`The Lord is good to me;
this day He has covered me with His glory.
I am weak, but am refreshed to see you.
The Lord is good to me.`"
Another friend asking him how it was with him, he answered, "`I am near leaving you,
I think; but am as well in my spirit as I can desire.
I bless the Lord.
I never saw more of the glory of God than I have done this day.`"
And when it was thought he was departing, he began to sing praises to the Lord, saying,
"`Glory, glory to You forever!`"
Which deeply affected those who were standing by, thus to hear a dying man sing.
And in this glorious state he departed this life the 5th of October.

Now since persecution was at a stand this year at London,
those of other persuasions sometimes bitterly inveighed
from the pulpit against the Quakers,
and would challenge them also to a dispute.
William Burnet and Jeremy Ives, eminent Baptist teachers,
had encountered George Whitehead this summer at Chertsey, and Horn, in Surry,
about the resurrection, and Christ`'s body in heaven,
endeavoring to blacken the Quakers in respect of those points,
because they kept to Scripture words, from which the others departing,
advanced very gross absurdities.

One Thomas Vincent, a Presbyterian teacher,
was much disturbed because some of his auditory had
gone over to the society of the Quakers;
and to render them odious,
he and his fellow teachers accused them of holding
an erroneous doctrine concerning the Trinity.
This was chiefly because the Quakers,
though they believed in the "`three that bear record in heaven, the Father, the Word,
and the Holy Spirit,`"^
footnote:[1 John 5:7 Although Friends objected to the notion
of three "`distinct`" and "`separate Persons`" in the Deity,
and did not often use of word "`Trinity,`" or other school terms not found in Scripture;
yet this was not from any dissatisfaction or disunity with the
scripture doctrine of the Holy Three that bear record in heaven,
the eternal divinity of the Lord Jesus, his propitiatory sacrifice on the Cross,
as the one universal offering for the sins of the whole world,
or any of his offices for man`'s salvation.
Friends openly declared their full faith in all these,
and that they were seeking to attain to a more full and practical
experience of the heart-changing efficacy of vital religion,
free from those outward rites and impositions of men, on which they believed themselves,
as well as others, to have been improperly relying,
instead of pressing after the living virtue and power of the gospel,
to redeem the soul from the pollution of sin,
and to enable it to walk in newness of life.
In a published response to accusations on this point,
George Fox wrote as follows:
{footnote-paragraph-split}
"`We acknowledge the Father,
the Son and the Holy Ghost, as the Apostles have declared.
'`And it is the Spirit that bear witness, because the Spirit is truth;
for there are Three that bear record in Heaven, the Father, the Word, and the Holy Ghost,
and these Three are one; and there are Three which bear record in earth,
etc.,`' which we own, 1 John, 5:6-7. And now let none be offended,
because we do not call them by those unscriptural names of Trinity, and Three Persons,
which are not Scripture words; and so do falsely say, that we deny the Father, the Word,
and the Holy Ghost, which Three are one that bear record in Heaven, etc.,
which Three we acknowledge with all our hearts, as the Apostle John did,
and as all true Christians ever did, and now do.
And if you say we are not Christians, because we do not call the Father, Son,
and Holy Ghost, the '`Trinity,
distinct and separate persons,`' then you may as well conclude that John was no Christian,
who did not give the Father, Word, and Holy Ghost,
these names.
{footnote-paragraph-split}
We believe concerning God the Father, Son,
and Spirit, according to the testimony of the Holy Scripture,
which we receive and embrace as the most authentic
and perfect declaration of Christian faith,
being indited by the Holy Spirit of God, that never errs: 1st,
That there is one God and Father, of whom are all things; 2ndly,
That there is one Lord Jesus Christ, by whom all things were made,
John 1 and 17. and Rom 9, who was glorified with the Father before the world began,
who is God over all, blessed forever, John 14. That there is one Holy Spirit,
the promise of the Father and the Son, and leader, and sanctifier,
and comforter of his people, 1 John 5. And we further believe,
as the Holy Scriptures soundly and sufficiently express, that these Three are one,
even the Father, the Word, and Spirit.`"--FLP]
did not approve of such expressions as were not to be found in the holy Scriptures,
as that of "`three distinct and separate persons.`"
On this subject a dispute was held in the Presbyterian meetinghouse
at London between the said Vincent on one side,
and George Whitehead on the other.
That which Vincent and his brethren advanced first, was an accusation,
that the Quakers held "`damnable doctrines.`"
George Whitehead denying this,
requested to give the people information on the principles of his friends;
but Vincent instead thereof stated this question, "`Do you acknowledge one Godhead,
subsisting in three distinct and separate persons?`"
Whitehead and those with him saying that this was an unscriptural doctrine,
Vincent framed this syllogism.

[.syllogism]
* There are three that bear record in heaven, the Father, the Word, and the Holy Spirit: and these three are one.
* These are either three manifestations, three operations, three substances, or three somethings else besides subsistences.
* But they are not three manifestations, three operations, three substances, nor three anythings else besides subsistences. Ergo, they are three subsistences.

G+++.+++ Whitehead rejected these terms as not to be found in Scripture,
and not deducible from the 1 John, 5:7, the place Vincent instanced.
And therefore he desired an explanation of those terms,
insomuch as God did not usually wrap up His truths in heathenish metaphysics,
but in plain language.
But whatever was said,
he could obtain no better explanation than distinct "`persons,`" or "`modes of a substance.`"
G+++.+++ Whitehead and William Penn (who also was there) alleged
several places from Scripture showing God`'s complete unity.
Then W. Penn denied the minor proposition of Vincent`'s syllogism; "`For,`" said he,
"`no one substance can have three '`distinct`' subsistences,
and still preserve its own unity; for every subsistence must have its own substance;
so that '`three distinct subsistences`' will require three distinct substances or beings;
consequently three Gods.
For if the infinite godhead subsists in three separate or distinct forms,
then none of them is a perfect and complete subsistence without the other two;
so that God must have parts, and something finite is in Him; or if infinite,
then three distinct infinite subsistences; and what is this, but to assert three Gods,
since none is infinite but God?

After several words on both sides, G. Whitehead,
to bring this strange doctrine nearer to the capacity of the people,
compared their "`three separate persons`" to three apostles,
and said he did not understand how Paul, Peter,
and John could be three persons and yet one apostle.
At this, one Maddocks, one of Vincent`'s assistants, framed this odd syllogism:

[.syllogism]
* He that scornfully and reproachfully compares our doctrine of the blessed Trinity of Father, Son, and Spirit, one in essence but three in persons, to three finite men, as Paul, Peter, and John, is a blasphemer.
* But you, George Whitehead, have done so.
* Ergo, you are a blasphemer.

A rash conclusion; but I leave the judicious reader to determine how solid it is.
I have no mind to enter further into this quarrel,
since the parties on both sides went away unsatisfied.
For Vincent had not been able to prove the doctrine
of the Quakers damnable as he had asserted,
but rather had been transported by passion.
And to those of his own society,
he said from the pulpit that he would rather they go to
a whore-house than to frequent the Quakers`' meetings,
because of their erroneous and damnable doctrines.
And pointing to the window he further said,
"`If there should be a cup of poison standing there, I would rather drink it,
than suck in their damnable doctrines!`"
But this untimely zeal did not profit him;
for it gave occasion to some of his hearers to inquire into the doctrines of the Quakers,
and thus some came to be convinced of the truth thereof.

Now since the aforesaid dispute made a great noise in London,
William Penn published a book with the title, [.book-title]#The Sandy Foundation Shaken,#
in which he explained the disputed points,
and defended his positions with good reason and the Holy Scriptures.
But even this book, which he himself spread, caused such a stir,
that it was spoken against,
and not long after this he was committed to the Tower of London;
and some thought not without his father`'s being acquainted with it,
perhaps to prevent something worse.

This was in the latter part of the year,
about which time Josiah Coale fell into a sickness,
which took him off the stage of this life.
He had languished long, and yet did not at all spare his voice,
but often raised it in both preaching and praying,
so that he spent his natural strength exceedingly,
though he was yet in a flourishing age.
And truly, it was his life and joy to declare the gospel,
and to proclaim the word of God, for which he had an excellent ability;
and when he spoke to the ungodly world, an awful gravity appeared in his countenance,
and his words were like a hammer and a sharp sword.
But though he was a "`son of thunder,`" yet much agreeable speech flowed from
his mouth like a pleasant stream to the consolation and comfort of pious souls.
Oh, how movingly have I heard him pray, when he,
being in some measure transported and ravished by the Spirit,
humbly beseeched God that it might please Him to reach to the hard-hearted,
to support the godly, and to preserve them steadfast!
And with what a charming and melodious voice did he sound
forth the praises of the Most High in his public prayers!
But his work was now done, he had finished his course,
and a time of rest from his labors had come.

Although he grew weak, yet his manly spirit and great courage bore him up for some time.
But his disease, which seemed to be a kind of consumption, at length so increased,
that he was made to stay indoors for several weeks.
Then mending a little, he went abroad again, and came to a meeting in London,
where I beheld his countenance much unlike what it used to be,
for it clearly manifested his bodily indisposition.
Nevertheless he preached with a godly zeal,
and his salutary exhortations flowed like a stream from his lips,
which seemed to be touched with a coal from the altar of heaven
while he was preaching the gospel to the edification of his hearers.
Indeed, he lifted up his voice again to such a degree that, judging from this,
one would have supposed him to have been pretty well restored.
But the ground of his distemper not being taken away,
it was soon necessary for him to remain at home again.
His natural strength then wasted away so fast, and he so greatly declined,
that his death began to be expected, which not very long after took place accordingly.

A little before he died, G. Fox having come to see him,
asked whether anything lay upon him to write to friends in England?
But J. Coale signified that he had nothing to write,
only desired that his love might be remembered to them,
and desired G. Fox to pray to God that he might have an easy passage,
for he felt his end approaching.
Having complied with his desire, and seeing that he appeared tired,
G+++.+++ Fox bid him go and lie on the bed, which J. Coale did.
But finding himself, as it seemed, more uneasy there,
with the help of his friends he rose again and sat on the side of the bed,
with his friends sitting about him.
Then finding himself so livingly and powerfully raised up,
he spoke to them after this manner: "`Well, friends, be faithful to God,
and have a single eye to His glory.
Seek nothing for self, or your own glory; and if anything of that does arise,
judge it down by the power of the Lord God, that so you may be clear in His sight,
and answer His witness in all people; then you will have the reward of life.
For my part, I have walked in faithfulness with the Lord;
and I have thus far finished my testimony, and have peace with the Lord.
His majesty is with me, and His crown of life is upon me.
So convey my love to all friends.`"
Then he ceased speaking; and a little time after he said to Stephen Crisp, "`Dear heart,
keep low in the holy seed of God, and that will be your crown forever.`"
After a short pause, he then said, "`A minister of Christ, must walk as I have walked.`"

A little after this he fainted, and being supported by his friends,
he departed in their arms, without the least sigh or groan,
but as one falling into a sweet sleep; and being filled with heavenly consolations,
he passed from this mortal life to that which is immortal,
having attained the age of thirty-five years and two months,
and having preached the gospel about twelve years.
He had travelled much in the West Indies, sustained great hardships,
and labored in the ministry at his own charge,
being freely given up to spend his substance in the service of the Lord.
And though he went through many persecutions, imprisonments, and other adversities,
yet he was not afraid of danger, but always valiant, continuing in an unmarried state,
that so he might more freely labor in the heavenly harvest;
and many were converted by his ministry.
He lived to see the desire of his heart accomplished;
for when first he was reached by the Spirit of Truth,
being under the sense of his former transgressions,
he had cried to the Lord for deliverance, saying with David, "`If you, O God,
will thoroughly help me, then will I teach transgressors your ways,
and sinners shall be converted unto you.`"
He traveled for a long time in a mournful state,
though he was naturally of a cheerful temper;
and having at last passed through a path of sorrow,
he was the more able to comfort the mourners of Zion.
The church was very sensible of this great loss;
and I have reason to think that his corpse was attended
to the grave by more than a thousand of his friends,
among whom I was then one; for his burial being very public and well known,
drew the eyes of many spectators towards it.
Let none think it strange that I have here somewhat
enlarged upon the life and death of this good man;
for he was indeed very dear to me,
and I have his kind treatment still in fresh remembrance; for the piety of my mother,
whom he had seen in England,
caused him to give me marks of the esteem he bore to her memory.
And his excellent gifts so affected me,
that I was eager to go to whatever meeting I heard he was likely to attend.
Truly, I saw something in him so extraordinary valuable,
that I bore a very reverent respect to him, and the more,
because the difference of our age deprived me of a very familiar communion with him.

On the 20th of the First month called January, 1668-9, Francis Howgill,
after a sickness of nine days, died in the prison at Appleby,
where he had been kept above five years.
During his sickness he remained in perfect understanding,
and was often very fervent in prayer,
uttering many comfortable expressions to the great refreshment of those around him.
He was often heard to say that he was content to die,
and praised God for the many sweet enjoyments and
refreshments he had received in his prison-house-bed,
whereupon he lay, freely forgiving all who had a hand in his confinement.
And he said, "`This was the place of my first imprisonment for the truth,
here in this town, and if it be the place where I lay down the body, I am content.`"
Several persons of note, inhabitants of Appleby, such as the mayor and others,
came to visit him; and some of these praying that God might speak peace to his soul,
he replied, "`He has done it.`"
About two days before his departure,
being attended by his wife and several of his friends, he said to them: "`Friends,
with respect to words, you must not expect much more from me;
neither is there any great need of it,
nor to speak of matters of faith to you who are already satisfied.
Only remember my dear love to all friends who inquire of me;
for I ever loved friends well, or any in whom truth appeared.
Truly God will acknowledge His people, as He has hitherto ever done,
and as we have daily witnessed.
For no sooner had they made the act of banishment,
to the great suffering of many good Friends,
but the Lord stirred up enemies against them,
whereby the violence of their hands was taken from them.
I say again, God will acknowledge His people, even all those that are faithful.
And as for me, I am well, and am content to die, I am not at all afraid of death.
But there was one thing in my heart that I intended
to have written to George Fox and others,
even something which I have observed, namely, that this generation passes fast away.
We have seen many good and precious friends within these few years taken from us;
and therefore Friends have great need to watch, and be very faithful,
that we may leave a good, and not a bad savor, to the next succeeding generation;
for we see that it is but a short time that any of us have to stay here.`"
A few hours before he departed, some friends from other places having come to visit him,
he inquired about their welfare, and prayed fervently, with many heavenly expressions,
that the Lord by His mighty power,
might preserve them out of all such things as would stain and defile.
His voice then, by reason of his great weakness, began to fail him,
but a little after he recovered some strength, said,
"`I have sought the way of the Lord from a child, and lived innocently among men;
and if any inquire concerning my latter end,
let them know that I die in the faith in which I lived, and for which I suffered.`"
After these words, he spoke some others in prayer to God,
and so sweetly finished his days in peace with the Lord,
in the fiftieth year of his age.

He left a good name behind him among all who knew him.
Sometime before his sickness, considering this mutable state,
and finding in himself some decay of nature, he made his will, in which,
as his love was very dear to his brethren with whom he had labored in the ministry,
so he gave to each of them a remembrance of his love;
he left also a gift to the poor friends where he lived.
For although his movable goods were forfeited to the king forever,
yet the confiscation of his real estate was only for life;
so that having something left from there, he was able to dispose of it by his will.

During his imprisonment, he failed not to comfort and strengthen his brethren by writing,
effecting that by his pen, which he could not by word of mouth.
He also defended his doctrine against those who opposed it; and among others,
he wrote a large treatise against oaths,
contradicting the opinion of those who account it lawful to swear under the gospel.

About two years before his decease,
he wrote an epistle of advice and counsel as his
last will and testament to his daughter Abigail,
a child whom he much loved, who was born in a time of deep exercises and trouble,
which nevertheless by the Lord`'s goodness he was patiently brought through.
He therefore named this child Abigail, which means, the father`'s joy.
In this testament he gave her the following instructions
for the future conduct of her life:

[.embedded-content-document.letter]
--

[.salutation]
Daughter Abigail,

This is for you to observe, and keep, and take heed unto all the days of your life,
for the regulating of your life and conduct in this world; that your life may be happy,
and your end blessed, and that God may be glorified by you in your generation.
These things I bequeath unto you, and counsel you ever to observe,
being the chief things alone I have to bestow upon you,
which I prize more than outward riches.
May you do so also, and observe and keep my sayings; and I charge you before God,
and by the coming of our Lord Jesus Christ, that you observe what I say.
I am moved of the Lord to leave this behind for you,
in tender love and affection unto you, my daughter,
that the Lord may give His blessing unto you, and make your ways prosperous,
and your latter end peace.

First of all, know this: I was never born into great possessions,
nor did I inherit great matters in this world;
but the Lord has always endowed me with sufficiency and enough,
and has been as a tender Father unto me, because my heart trusted in Him,
and did love the way of righteousness from a child.
I have no great portion to bestow upon you of the things of this world;
yet of that little which I have, and God has blessed me with,
there is something I shall give you, which I shall not mention here;
but you will know of it at my decease.
But I commend you to your dear mother, who, I trust, will provide sufficiently for you;
unto whom my heart has been upright before the Lord.
She had a sufficient portion and dowry when I married her,
which I desire not much to lessen or impair;
and whatever was hers (if it please the Lord I die before her) I freely leave unto her,
as was ever my intention and purpose, which has not, nor ever shall change,
through the strength of God--as God only knows, and bears me record.
This shall be manifest unto all in due time, as it is already manifest unto the Lord,
who has been with me in the midst of many troubles, trials, and sufferings,
and has lifted up my head above my adversaries, because I trusted only in his Name;
which at all times I found to be a refuge, and a present help in time of need;
and so it will be unto you, if you fear his Name, and trust in Him forever.

And now, dear child, hearken unto the words of my mouth, and listen unto my counsel.
Ponder these things I leave behind me for you to observe,
that your days may be long upon the earth, and be blessed and comfortable unto you,
and an honor to God in your generation.

The time when you were born and came into the world,
was a time of deep exercise and trouble with me--not from the Lord,
who always spoke peace unto me,
and did sustain me--but by reason of the adversary of mankind,
who always seeks to devour the good in all,
and is the sower of discord and mischief in the hearts of those who fear not the Lord,
neither abide in His counsel.
Into these he enters, as any place is given unto his temptations,
and there he corrupts the mind.
But though there was then a great trial that came upon me,
the Lord kept my heart in uprightness unto Him and gave me much patience.
And though the earth had been removed into the sea,
and all outward things had run into confusion, and nature had changed its course,
yet the Lord gave me a resolution and strength not to be troubled or offended,
because He did support me.
At that time you were born; and therefore I called your name Abigail,
which means the father`'s joy or delight; for in you I was comforted,
and my present trouble was mitigated.

Now, my counsel unto you is that you remember your Creator in the days of your youth,
and fear the Lord in your youth, and learn to know Him and serve Him all your days.
Seek first the kingdom of God, and the righteousness thereof.
His kingdom is not far from you; it is within you.
It consists of life and power, and stands in righteousness, truth, equity, justice,
mercy, long-suffering, patience, love, light, and holiness;
this is the being and centre thereof.
Therefore, seek not the "`lo here`'s`" or "`lo there`'s`" without you,
in this or that outward observation; for many seek there and never find it.
But seek, and you shalt find; wait, and you shall receive.

If you inquire,
'`in what must I seek,`' and '`in what must I wait,`'
and '`how must I seek,`' I inform you:
You must silence all your own thoughts,
and you must turn your mind to that gift which is pure, holy, and good, within yourself.
Seek and wait in that, in the Light of Jesus Christ, wherewith you are enlightened,
and which shows you when you do evil, and checks and reproves.
Take heed unto that, and it will show the evil motions and thoughts; and as you love it,
it will also subdue them, and preserve you out of evil for the time to come.

For though you are born into the world a reasonable creature, yet you must be born again,
and be made a __new__ creature, or else you cannot enter into God`'s kingdom.
You must know the Seed of the kingdom in yourself (of which
you must be born) and be formed again into God`'s image.
I have told you that God has sown it in you-a grain of it, a measure of it,
a portion of it, a measure of Light and Truth, of righteousness and holiness.
Keep turned in your mind to that; love it,
and you will feel the Heavenly Father working in you, and creating you anew unto life,
through Jesus Christ who has enlightened you.
And you will feel the power of the Lord strengthening you in your little,
and making you to grow in the immortal Seed of His kingdom,
and to out-grow and over-grow all evil, so that you will daily die to evil,
and have no pleasure in it, but rather in the Lord,
and in His goodness and virtue shed abroad in your heart,
which you will taste and feel within, and have joy and comfort therein.

Love the Lord with your heart and soul,
even Him that made you and gave you (and all other things in heaven and earth) a being.
Wait for the knowledge of Him in yourself; He is not far from you, but near unto you,
and unto all who call upon Him with an upright heart.
Inquire of your dear mother and she will inform you; she knows Him,
and the way to life and peace; so hearken unto her instruction.

God is a Spirit, a pure Spirit of light, life, and power.
It is He that searches the heart, and shows you when you do evil, or think evil,
or speak evil; and He shows unto men and women their thoughts.
That which shows the evil is good, and that which shows a lie is Truth.
This is within; take heed unto it.
This is called God`'s Spirit in the Scriptures; believe in it, love it,
and it will quicken your heart to good, and also subject the evil.
Here is your teacher near you; love it.
If you act contrary to it, it will condemn you;
therefore take heed unto this Spirit of Truth, and it will enlighten and enliven you.
It will open your understanding, and give you to know what God is,
and to do that which is good and acceptable in His sight.
This Spirit never errs, but leads out of all error and into all truth.

O Abigail, believe my words!
They are the words of God and Truth.
Be not careless, but sober-minded in your youth.
Wait on the Lord within, and hearken unto Him.
God is Light immortal, Life immortal, Truth immortal; an everlasting and eternal Spirit.
He speaks spiritually and invisibly within the hearts and consciences of men and women.
Hear what He speaks and obey His voice, and your soul shall live.
Fear to offend Him, or to sin against Him; for the wages of sin is death.
Therefore prize His love in your young and tender years.

Read the Scriptures and Friends`' books, and take heed unto what you read to obey it,
as far as you understand.
Pray often unto the Lord that He give you His knowledge,
and open your understanding in the things of His kingdom.
Search your heart often with the Light of Christ in you;
manifest and bring your deeds to the Light, that they may be tried.
Examine yourself how the case stands between the Lord and you;
and if you see yourself to be wrong, humble yourself and be sorry.
Turn unto Him, and He will show you mercy;
then take heed for the time to come that you run not into the same evil again.
Keep your heart clean; watch against the evil in yourself in that light which shows it;
therein there is power, and thereby you have power to overcome all evil.

And dear child, mind not the pleasures of sin which are but for a moment,
and their end is misery; but cross and keep under your own will and affections.
Thus your mind will have no pleasure in evil, but only in good;
and you will feel the immortal Seed springing up in you,
to which is God`'s peace and love.

O Abigail! these are great and weighty things, not to be slighted!
Keep company always with those who fear the Lord,
who fear and worship Him in spirit and truth, and lead a holy and a blameless life.
Deny them not, but love them and suffer with them.
And take heed that you follow not the hireling teachers, who preach for gain and riches,
and do not abide in Christ`'s doctrine.
Believe them not, heed them not, for they do people no good;
but you will see them for yourself.
These have an outside show of godliness sometimes,
but deny the power of God and true holiness.
Remember I have told you, as one who has had a perfect knowledge of them.

Be sure that you let nothing separate your love from God and His people.
Those are His people who keep His law, and obey Christ`'s voice, and lead a holy life.
These were ever hated and opposed and persecuted,
and always had evil spoken of them by bad and loose people.
These are God`'s people, and His love and peace and blessing is with them.
Therefore, grow up among them as a natural branch of the living Vine;
and continue all your days in obedience unto God`'s will.
So you will feel joy and love in your heart, which you should pursue above all things,
and you shall attain to and obtain everlasting peace.
May the Lord grant this unto you, according to the riches of His mercy and love,
which endure forever and ever, amen.

And now Abigail, concerning your well-being in this life,
this is my advice and counsel unto you: Love your dear mother,
and always obey and honor her.
See that you grieve her not, nor be stubborn or willful, but submit unto her,
and be as an obedient child to her;
for her love and care has been great over you and your sisters,
which has brought much trouble upon her.
Learn in your youth to read and write a little, and sew and knit,
and all points of good labour that belong to a maid;
and flee all idleness and sloth which nourish sin.
And as you grow up in years, beware of pride, and extravagance, and curiosity;
but be well content with such apparel as your mother will permit you,
in which you may also be a good example unto others.
Be not reckless, nor wild, nor light; but rather temperate, moderate, and chaste,
and not forward in words or speech, but swift to hear, slow to speak.
Always live with your mother,
and be a help to her and cherish her in her old age and latter years,
that she may be comforted in you, and her soul may bless you.
Love your sisters, and be always courteous to them, and to your brother Thomas;
encourage one another in good.

And Abigail, if you live to be a woman of mature years, keep yourself unspotted,
and let not your mind go out after sports and pastimes,
for the end of all these is sorrow; nor seek after young men.
If you have a desire to marry, do not seek a husband, but let a husband seek you;
and if you live an honest and virtuous life in God`'s fear,
then those who fear God will seek after you.
Do not let your affections out after every one that offers love, but be considerate;
and above all things (if you do marry) choose one that loves and fears the Lord,
whose conduct, manner and course of life you know well, before you give consent.
Be discreet and wise.
Hide nothing from your mother, and she will no doubt advise you for your good;
and if she is living, marry not without her consent.
And if you join to a husband, be sure you love him in your heart,
and be obedient unto him, and honor him in the presence of all;
so will his heart be more to you, and his love increase.
Do not grieve him, but be gentle and easily entreated, minding your own business.
And if the Lord gives you children, bring them up in the fear of God,
and in good discipline, keeping them in subjection to you.
And be an example of virtue and holiness unto them,
that you may feel the Lord`'s blessing in youth, and in old age, and all your life long.

O Abigail! remember these things; keep them in mind!
Read over this letter often; get it copied over.
Lay up my words in your heart, and do them;
so you will be happy in this life and in the life to come.
These things I charge you to observe, as expressive of my unalterable mind, and will,
and counsel, unto you; in witness whereof I have set my hand.

[.signed-section-closing]
Your dear father,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
26th of the 5th month, 1666.

--

In the beginning of this year,
the members of this society held a general yearly-meeting at London, which,
since that time, has been held there annually in the week called Whitsun-week,^
footnote:[It has since been fixed to be held on the Second-day
immediately following the third First-day in the 5th month.]
because that time of year is commonly best for traveling.
Several are sent from all places to attend this meeting,
and the general concerns of the church are there treated upon.

Persecution for religion now seemed to be at a stand,
which displeased some of the most rigid sort of churchmen,
as we have not only shown already, but will again demonstrate in its due place.

About this time, I believe, a certain bishop said that the Quakers,
by their unlimited freedom, increased much,
and therefore it was very needful to take care of them,
seeing they often had much greater assemblies than the national church; "`For,`" said he,
"`at such a time I preached myself, and there were but a few hearers,
when at the same time the Quakers`' meeting nearby was crowded full.`"
He thereupon desired them to consider whether it was not time to stop these sectaries.
After he had set forth his argument at length,
another lord then present among the others said,
that indeed it seemed the lord bishop had spoken what was very true,
that the sectaries had often more hearers than the national church preachers,
and that it was not strange to him that it displeased him,
since he took so much upon himself; "`For,`" said he,
"`his lordship has just said that he '`preached himself;`' and the Quakers,
who have such great assemblies, preach Christ Jesus;
it is therefore no wonder that they had the more hearers.`"
This was such a witty turn upon the bishop as no doubt made
him think it not wise to enter upon the debate,
for it was observable this lord`'s turn upon the bishop
was chiefly to stop him from promoting persecution.

Traveling to York this spring,
G+++.+++ Fox went through several other places in the North of England;
and although he came near to his old enemy colonel Kirby, who had a fit of the gout,
and had threatened him, yet he passed by unmolested.
He continued on to Liverpool,
from which he with some of his friends--among whom were
Thomas Briggs and John Stubbs--passed over for Ireland;
and having arrived at Dublin, he was kindly received by his friends.
Journeying into the country, he met with no small opposition from the Papists,
of whom there were many.
And having come to a certain place, he challenged the Jesuits, priests, and monks,
to try whether their god, which they make of a wafer, was an immortal god,
but they would not do it; wherefore he said, they were worse than Baal`'s priests,
for Baal`'s priests were willing to try their god.
He then went to Cork,
where they had knowledge of his coming and intended to take him prisoner;
for the Quakers in Ireland were many years sharply persecuted,
as were their brethren in England,
but to mention all such circumstances would make a very large treatise.

At this time there were many prisoners at Cork, among whom was Samuel Thornton,
with whom I was well acquainted.
He having met together with his friends in a chamber one First-day,
the officer Quinnal came and shut the door of the room and locked them in,
to the number of eighty persons, and carried the key to the mayor, Matthew Dean.
The mayor then gave order that there should be neither food nor drink carried to them,
and they could only get what was pulled up with ropes through the grate,
or thrown in through a hole.
Under this chamber the soldiers were ordered to keep guard so that none might get away,
and they made so great a fire, that many of the prisoners were sick from the smoke,
among whom were some weakly old people,
and some pregnant and nursing women who were almost stifled.
A complaint being made to the mayor, he answered in a scoffing manner,
"`They are all brethren and sisters, let them lie upon one another;
and if they are stifled it is their own fault.`"
Thus they were kept for twenty-four hours, and afterwards some were taken to prison.

Solomon Eccles, who I also knew very well,
was this year in prison at Gallaway in Ireland, where he was put by a strange incident.
He was an extraordinarily zealous man, and what he judged to be evil he warmly opposed,
even to the hazard of his life.
This zeal led him to perform a strange action in
a chapel of the papists outside of the town;
for he went naked above his waist,
with a dish of coals and burning brimstone on his head,
and entered the chapel when all the people were on their knees to pray to their idol,
and spoke as follows: "`Woe to these idolatrous worshipers!
God has sent me this day to warn you,
and to show you what will be your portion except you repent.`"
When he had finished, he went away to the town, where he was soon made a prisoner.
What the benefit of this strange action might be, I leave.

Amongst the martyrs of the reformed,
we find some instances of persons who were zealous to a strange degree,
as William Gardiner at Lisbon, and Bertrand le Bias at Tournay,
whose actions were not less remarkable.
The latter was said to have snatched the host from
the priest in their church as they were at mass,
which was certainly a bold attempt,
and not praiseworthy if only an act of human contrivance;
but I find it safest to leave the judgment thereof to God;
more so because he did this deed expecting the sharpest punishment that they could inflict,
and seemed not to shrink from it, but rather to be strengthened.
And though so sharp a consequence did not fall to Solomon Eccles`'s lot,
I still find it safer not to judge hastily of this uncommon performance.
He was, to my knowledge, a bold and undaunted man,
and prior to this action in the chapel,
he did something of a like nature in London during the time of the fair,
amongst the plays,
where he suffered much by the coachmen whipping him grievously on his naked back.
But this did not quench his fervent zeal,
which was kindled not only against the immodest and
ungodly behavior of the pretended fools,
but also against other vanities there indulged.

To what height his zeal carried him, the following instance will show.
He had been a member of the church of England, and then went to the Presbyterians,
and afterwards to the Independents, and after that became a Baptist,
during all of which time he had been an eminent musician,
so that by his art he could get near 150 a year.
But at last becoming a Quaker, he could not, for conscience-sake,
continue what he now called his Babylonish trade of music.
He therefore learned to make clothes to earn a living,
and sold his musical books and instruments.
But, as he declared, he still had no peace in his conscience;
for believing them to be instruments of vanity, he judged they ought to be destroyed.
He therefore bought them again (although they were
worth above 20) and carried them (i.e. harpsichords,
fiddles, etc.) to Tower-hill, where laying them all together, he set fire to them.
But when some who were nearby endeavored to hinder him,
and to get one of the harpsichords away, he stamped upon it with his foot,
and would not rest until he had destroyed it.
Afterwards this he said he found peace in his conscience,
having made an offering of that which he once entirely loved,
and in the use of which he had been educated; for not only his father and grandfather,
but his grandfather`'s father had been musicians,
and he himself had the name of an eminent music-master.

I now return to G. Fox at Cork in Ireland, where there was a design to take him prisoner.
Nevertheless they let him go unmolested, although he rode through the market,
and by the mayor`'s door, who not only saw him, but said,
"`There goes George Fox,`" and yet let him pass by quietly.
After he had traveled through many places in Ireland, he came again to Dublin,
from which he returned again to England.
Coming into Gloucestershire,
he heard at Nailsworth a report which had been spread abroad in the country,
that he had turned Presbyterian,
and that they had prepared a pulpit for him in the
open yard where he was to preach to the people.
G+++.+++ Fox hearing this, thought it very strange, whereupon he went to the place spoken of,
and indeed found a pulpit.
But the case was this: a certain Presbyterian preacher named John Fox,
who went preaching about the country, was to preach there,
and it seems some had changed his name from John to George,
whereupon it was reported that G. Fox had turned from being a Quaker to a Presbyterian.
This begat so great a curiosity among the people,
that many went there to hear this Quaker turned Presbyterian;
and so John Fox came to have a great auditory of several hundreds
who otherwise would not have traveled a foot to hear him,
had they known it.
But some hundreds of them hearing afterwards that
the real G. Fox was not far off at a meeting,
they went there and were sober and attentive,
and were by him directed to the grace of God in themselves
which would teach them and bring them salvation.
And when the meeting was over,
some of the people said they liked George Fox the Quaker`'s preaching,
better than George Fox the Presbyterian.

Not long after this,
a complaint was made in the house of commons against
this John Fox for having a tumultuous meeting,
in which treasonable words were spoken.
Now John Fox had formerly been priest of Marshfield in Gloucestershire,
and having been put out of that place,
he was afterwards permitted by a common-prayer priest to preach sometimes in his steeple-house.
At length,
it seems that John Fox presumed too far upon the parish priest`'s former grant,
and began to be more bold than welcome, desiring to preach there whenever he wished.
This caused a great bustle and contest between the two priests,
and between their hearers on either side,
at which time the common-prayer book was purportedly cut into pieces,
and it is said that some treasonable words were then spoken by the followers of John Fox.
This case was quickly put into the newspapers,
and some malicious Presbyterians caused it to be worded so as to suggest
that the treason proceeded from the mouth of G. Fox the Quaker.
Nevertheless,
some members of the house of commons certified it
under their hands that it was indeed John Fox,
formerly priest of Marshfield, who was the ringleader of this unlawful assembly.

After this G. Fox traveled to Bristol, where he met with Margaret Fell, then a widow,
who came there to visit her daughter Yeomans.
Before this time he had intimated to her his affection,
and proposed to take her in marriage at a suitable time;
but though he had a sense in himself that this was of the Lord,
yet he had not previously found freedom to accomplish it.
But all obstructions being now removed, he so proposed the matter to her,
that if she was willing to give her consent, she would first send for her children.
These all having come together,
G+++.+++ Fox asked both her daughters and their husbands whether they
had any thing against his taking their mother to be his wife?
And they all individually expressed their satisfaction therein.
He then asked Margaret, whether she had performed her first husband`'s will?
And asked the children whether, if their mother married again,
they would lose anything by it?
The children all said she had fulfilled their father`'s will to them,
and so desired him to speak no more of that.
So observing they were all well satisfied, he proceeded in marriage,
and took Margaret Fell to be his wife in a public meeting of Friends in Bristol.
She was a woman of a noble endowment, and this I know not only by her writings,
but I have also heard her preach for an hour together,
delivering her matter succinctly and orderly.

Being married, G. Fox stayed with his wife about a week in Bristol,
and then they went together to Oldstone.
Taking leave of each other there, they parted, she going homeward into the north,
and he traveling through Wiltshire, Berkshire, Oxfordshire, Bucks, and so to London:
for although now he had a wife,
yet he did not neglect his care towards the churches over all the nation,
in the gift which he had received of God, both in word and writing to their edification.
And among the rest he had a special regard that the poor might be taken care of,
to which end he wrote an epistle in London,
enjoining that poor children should be put forth as apprentices to trades,
whereby in time, they might help their aged parents,
and enable them to bring up their families, and maintain themselves comfortably.

G+++.+++ Fox stayed not long in London; but the year 1670 having now come,
he travelled through Hertfordshire, Cambridgeshire, Huntingdonshire, and Leicestershire,
where he expected to have met with his wife;
for he had written her word to meet him there, if she found it convenient.
But instead of this,
he there discovered that she had been hauled out
of her house and carried to Lancaster prison,
upon the charge of an old premunire which was executed upon her five years before,
from which she had been discharged by order of the king and council the previous year.
Therefore, after he had visited friends in those counties, he returned to London,
where he found two of his wife`'s daughters,
and encouraged them to go quickly to the king,
to acquaint him how their mother had been dealt with.
This they did, and met with much difficulty; but at last, through assiduous application,
they were permitted to speak to the king, to whom one of them said,
that instead of their waiting upon him to return thanks for the discharge of their mother,
they were now necessitated to make complaint of their
mother`'s being cast into prison a second time.
Whereupon the king gave command to sir John Otway, to write to the sheriff of Lancashire,
to set her at liberty;
which letter G. Fox accordingly hastened his daughters with into the country.

[.offset]
The parliament now sitting, made a law entitled:
__An Act to Prevent and Suppress Seditious Conventicles,__ which is as follows:

[.embedded-content-document.legal]
--

[.blurb]
=== For providing farther and more speedy remedies against the growing and dangerous practices of seditious sectaries and other disloyal persons, who under pretense of tender consciences, have or may at their meetings contrive insurrections (as late experience has shown):

[.numbered-group]
====

[.numbered]
I+++.+++ Let it be it enacted by the king`'s most excellent majesty,
by and with the advice and consent of the spiritual and temporal lords,
and this present parliament assembled, and by authority of the same,
that if any person of the age of sixteen years or upwards, being a subject of this realm,
at any time after the tenth day of next May, shall be present at any assembly,
conventicle, or meeting, under pretense of an exercise of religion,
in a manner other than according to the liturgy and practice of the church of England,
in any place within the kingdom of England or dominion of Wales, at which conventicle,
meeting, or assembly, there shall be __five persons or more__ assembled together,
over and besides those of the same household,
it shall be lawful for any one or more justices of the peace of the county to make a
record of every such offense under his or their hands and seals respectively:
and thereupon the said justice, justices, or chief magistrate,
shall impose on every such offender so convicted,
__a fine of five shillings for their first offense:__
which record and conviction shall be certified by the said justice, justices,
or chief magistrate,
at the next quarter-sessions for the county or place where the offense was committed.

[.numbered]
II. And let it be further enacted by the aforesaid authority,
that if an offender so convicted shall at any time
again commit the like offense or offenses,
contrary to this act, and be thereof convicted,
then such offender shall for every such offense __incur the penalty of ten shillings;__
which fine or fines shall be levied by seizure and
sale of the offender`'s goods and estate;
or in case of the poverty of such offender,
upon the goods and estate of any other person or persons who shall
be then convicted of the like offense at the same conventicle,
at the discretion of the justice, justices, or chief magistrate respectively,
so as the sum to be levied on any one person in case of the poverty of other offenders,
amount not in the whole to above the sum of ten pounds, upon occasion of any one meeting.

[.numbered]
III.
And let it be further enacted by the authority aforesaid,
that every person who shall take upon himself to preach or teach in any such meeting,
assembly or conventicle, and shall thereof be convicted, as aforesaid,
shall forfeit for his first offense __the sum of twenty pounds,__
to be levied in manner aforesaid upon his goods and estate.
And if the said preacher or teacher be a stranger, and his name and habitation not known,
or he has fled and cannot be found, or in the judgment of the justice,
shall be thought unable to pay the same,
the said justice is hereby empowered and required to levy the same by warrant upon the
goods and estates of any such persons who shall be present at the same conventicle.
And if such offender so convicted shall at any time again
commit the like offense or offenses contrary to this act,
and be thereof convicted in manner aforesaid,
then such offender shall for every such offense, __incur the penalty of forty pounds,__
to be levied and disposed as aforesaid.

[.numbered]
IV. And let be it further enacted by the authority aforesaid,
that every person who shall willingly allow any such conventicle, meeting,
or unlawful assembly to be held in his or her house, outhouse, barn, or yard,
and be convicted thereof in manner aforesaid, __shall forfeit the sum of twenty pounds,__
to be levied in the manner aforesaid, upon his or her goods and estate;
or in case of his or her poverty or inability,
upon the goods and estates of such persons who shall
be convicted of being present at the same conventicle; etc.

====

--

By this law, many an honest family was impoverished;
for the Quakers did not cease meeting together publicly.
Many of the most sincere amongst them became even more zealous,
and thus were separated from the chaff, who, in times of ease,
sometimes crept in amongst the truly religious people.
In London, as well as at other places,
many were spoiled of their goods very unmercifully,
and many times people of good substance brought to mere poverty,
seeing that not only the shop goods of some, but also their household goods were seized.
In some cases, the very sick have had their beds taken out from under them,
and they themselves were laid upon the floor.
Indeed, they have been so cruel as to leave some families nothing;
for finding an infant eating from a metal dish,
they have thrown out the food in order to take the dish.

Were I to relate all the particulars I have received regarding this time,
the account I could give would make a volume in itself; for the informers^
footnote:[Informers were those who would report "`unlawful
conventicles`" to the local magistrates,
with the expectation of receiving a third of the money or goods seized from the Quakers.]
were generally poor, and sometimes also the justices,
and so they learned to divide their plunder in such
a way that the king and the poor got very little.
Nevertheless it sometimes happened,
that those taken in meetings were freed by the justices;
for it was well known that these informers, who also acted as witnesses,
were cunning sharks, principally concerned with getting their third of the booty.
Thus it has sometimes happened that an honest justice would
clear a man or woman who had been taken in a meeting,
if it was found that the informer had mistaken, either in the day of the month,
or some other small error.

In London there once appeared before the lord mayor, sitting at a court of aldermen,
an impudent informer having such a large list of parties to report for
fines as would have amounted to the value of 1500. But the mayor,
despising such practices, adjourned the court and went away.
But this determined informer was not content to let the matter thus fall,
and continued to appear before the court from time to time,
seeking to make a prey of honest people`'s goods.
Nevertheless, they still put him off,
until at last he himself was arrested for debt and carried to prison,
where he ended his days.

Although the law against seditious conventicles
had passed upon a suspicion that the Presbyterians were ready to rise--considering
the bustle and tumult occasioned by John Fox in Gloucestershire,
which was much taken notice of (as I have mentioned before)--yet nevertheless
the Quakers`' meetings became the chief object in the execution of this law.
Whereupon G. Fox being in London, set forth in print the injustice of this law, in order,
if possible, to persuade the government not to put it into execution.
Nevertheless, being also sensible that a great storm hung over the heads of his friends,
he also wrote an epistle to them, exhorting them to faithfulness,
encouraging them to stand fast in their testimony,
and bearing with Christian patience the suffering that had come upon them.

Now the first day that this law was put into effect,
he went to the meeting of friends at Gracechurch-street in London;
but having come to the place, he found the street full of people,
and a guard to keep them out of their meetinghouse.
He thereupon went to Lombard street,
from which there was also a passage to the meetinghouse, but here he also found a guard.
There being a courtyard before the door which was full of people,
one of the Quaker ministers was there preaching to the people, and when he had ended,
G+++.+++ Fox stood up and said, "`Saul, Saul, why do you persecute me?
It is hard for you to kick against the pricks.`"
With these words he explained that it was Saul`'s nature that persecuted;
and that they who persecuted Christ in His members were kicking against the pricks;
and that it was the birth of the flesh that always persecuted the birth of the Spirit,
and the nature of dogs to tear and devour the sheep;
but that they who suffered like sheep, who did not bite back, were a peaceable people,
who loved even their persecutors, etc.
While G. Fox was thus preaching, there came in a constable and an informer with soldiers,
who pulled him down from the place where he stood.
Then he said,
"`Blessed are the peace-makers,`" but the commander
of the soldiers ordered them to secure him,
"`For,`" said he, "`you are the man I was looking for.`"
Therefore he with two more of his friends, John Burnyeat and another,
were taken before the lord mayor; and as they were going, the informer said,
"`It will never be a good world,
until all people come to the good old religion that was two hundred years ago.`"
G+++.+++ Fox hearing this, said, "`Are you a papist?
What?
A papist informer?
For, two hundred years ago there was no other public profession
of religion but that of the papists in this nation.`"

It vexed the informer that G. Fox had heard him speak in this way;
for he now saw he was ensnared in his own words.
When he came into the court before the lord mayor`'s house,
some people who were there asked G. Fox why he had been brought there a prisoner?
"`Ask the informer,`" he said, "`and ask him his name;`" but he would not tell his name.
Then one of the mayor`'s officers told him he should tell his name before he went away:
"`For,`" said he,
"`the lord mayor will desire to know by what authority you have intruded yourself with
soldiers into the execution of laws which belong to the civil magistrate to execute,
and not the military.`"
The informer hearing this, got away, but not without some difficulty,
because they would not then let him out of the court.
But forcibly pulling open the door, and having gone out into the street,
the people gave a great shout, crying out, "`A papist informer!
A papist informer!`" and he likely would have been injured,
had not G. Fox advised the constable and soldiers
to keep him out of the hands of the common people.
He thereupon went into the house and changed his periwig, and so fled away.

When the lord mayor came home, and G. Fox was brought before him, he said, "`Mr. Fox,
you are an eminent man among those of your own profession; pray,
will you be instrumental to persuade them from meeting in such great numbers?
For seeing Christ has promised, where two or three are met in His name,
He will be in the midst of them;
and the king and parliament are graciously pleased
to allow of four to meet together to worship God,
why will you not be content to partake both of Christ`'s promise to two or three,
and the king`'s indulgence to four?`"
To which G. Fox answered as follows:
"`Christ`'s promise was not to discourage many from meeting together in His name;
but to encourage the few, that the fewest number might not forbear to meet,
because of their fewness.
But if Christ has promised to manifest His presence in the midst of so small an assembly,
where but two or three were gathered in His name,
how much more would His presence abound where two
or three hundred are gathered in His name.`"
G+++.+++ Fox then wished him to consider whether this act would not have taken hold of Christ,
with His twelve apostles and seventy disciples, if it had been in their time,
who used to meet often together, and that with great numbers?
"`However,`" he said, "`this act does not concern us;
for it was made against seditious meetings of such as meet under
pretense and color of religion in order to contrive insurrections,
as, the act says.
But we have been sufficiently tried and proved, and have always been found peaceable.
Therefore you would do well to make a difference between the innocent and the guilty.`"
The lord mayor then said that the act was made against meetings,
and against a worship that was not according to the liturgy.
G+++.+++ Fox told him, "`__according to,__ does not mean __the very same thing.__
Is the liturgy according to the Scriptures?
And may we not read Scriptures, and speak from Scriptures?`"
The lord mayor said "`Yes.`"
G+++.+++ Fox then told him,
"`This act takes hold of those who meet to plot and contrive insurrections,
'`as late experience had shown;`' but they have never experienced this from us.
Just because thieves are sometimes on the road,
must honest men therefore not be allowed to travel?
And because plotters and contrivers have met together to do mischief, must honest,
peaceable people, not be allowed to meet together to do good?
Now consider,
if we had been a people that desired to meet to plot and contrive insurrections,
we might have drawn ourselves into groups of fours;
for four might do more mischief in plotting than four hundred;
because four might speak out their minds more freely
one to another than four hundred could.
Therefore, we being innocent, and not the people this act concerns,
we keep our meetings as we always have.`"
He then said to the lord mayor,
"`I believe you know in your conscience that we were innocent.`"

After this and more discourse, the lord mayor, whose name was Samuel Starling,
let them go, seeing the informer had gone out before, and now nobody accused them.
The treatment this informer met with made others hesitant,
yet several of their meetings in London were disturbed,
and some of their preachers were cast into prison.
But though the Baptists and other dissenters ceased their public meetings,
yet the Quakers continued to keep theirs as they always had,
whereby it happened that some of their meetinghouses were pulled down,
and amongst others the meetinghouse at Ratcliffe,
which was a substantial building and almost new.

After some time, the heat of persecution in the city began to abate,
but in other places it raged more fiercely.
This engaged G. Fox to leave the city,
and travel about the country in many places to visit his friends.

This year G. Fox had a very great fit of sickness,
to such a degree that for a time he became both blind and deaf,
and his recovery was despaired of by some; but after a time he grew better.

In the meantime, persecution in many places grew very dismal;
for many of the friends were beaten with swords, and pikes, and muskets,
to such a degree that their blood ran along the ground,
and the informers were so very eager to hunt after their prey,
that they sometimes informed about meetings when there had been none.
Amongst others, the following was an instance.
A Droitwitch, John Cartwright came to a friend`'s house there, who,
sitting down to supper, prayed before they ate.
This being heard by an informer, the room being next to the street,
he thereupon went immediately and informed that there was a meeting in the house,
and so got a warrant to distrain their goods.
But when he came riding with the officers in the evening,
he fell from his horse and broke his neck,
thereby getting death instead of the prey which he hunted after.
