== Chapter XVIII

[.section-date]
1670--1674

Now, although persecution was not so hot in London, as in other places in the country,
yet sometimes even there it was very severe,
as may be seen by the instance of William Penn and William Mead,
who were taken from a meeting and imprisoned, and tried in the month of September.

The indictment contained, that "`William Penn and William Mead,
with several other persons, to the number of three hundred, at Grace-church-street,
in London, on the 15th of August, with force and arms,
had tumultuously assembled together; and that William Penn,
by agreement between him and William Mead, had preached there in the public street,
thereby causing a great concourse and tumult of the people,`" etc.
Now, that there was a public meeting in the street proceeded from necessity;
for a guard was placed at the door to hinder friends from going into their meetinghouse.
But it was a great untruth that they had met with force and arms,
which were never used by the Quakers.

This indictment being read before the court, the prisoners were demanded to answer,
according to custom, whether they were guilty or not guilty?
Whereupon William Penn said,
"`It is impossible that we should be able to remember the indictment verbatim;
we therefore desire a copy of it, as is customary on the like occasions.`"
The recorder, John Howel said hereupon,
"`You must first plead to the indictment before you can have a copy of it.`"
Then W. Penn said that he desired that no advantage might be taken against him,
nor he be deprived of any benefit which he might otherwise receive,
and that the court would promise him a fair hearing, and liberty of making his defense.
Upon this the court said that no advantage should be taken against him,
and that he would have liberty, and would be heard.
W+++.+++ Penn then said that he pleaded not guilty in manner and form.
Then W. Mead was required to answer whether he was guilty or not guilty,
and he answered the same as W. Penn.
The court then proceeded with the business of trying thieves and murderers,
making the prisoners wait five hours before returning them to prison;
and after two days brought them again before the court.

The officers of the court having taken off the prisoners`' hats, the lord mayor,
Samuel Starling, showed himself displeased with it,
and ordered the officers to put their hats back on again.
This being done, the recorder John Howel, who upon all occasions showed his fierceness,
accused them of showing no respect to the court,
and condemned them for it with a fine of forty marks each for not taking off their hats.
Thereupon W. Penn said that he desired it might be observed,
that they came into court with their hats off, (that is,
taken off) and if they had been put on since, it was by order from the bench,
and therefore the bench, and not the prisoners, should be fined.
The jury then being sworn in, and the indictment read again, the witnesses were called,
who declared that they saw William Penn speaking to the people
who were assembled in a great number in Gracechurch-street,
but they could not hear what he said.

The recorder then asked William Mead whether he was there?
Who answered, that "`It is a maxim in your own law, _nemo tenetur seipsum accusare,_
which if it be not true Latin, I am sure it is good English,
that '`No man is bound to accuse himself.`' Why then
do you offer to ensnare me with such a question?`"
Hereupon the recorder showed himself so displeased that he said, "`Sir, hold your tongue,
I did not go about to ensnare you.`"
Then William Penn said, "`We confess ourselves to be so far from recanting,
or declining to vindicate the assembling of ourselves together to preach, pray,
or worship the Eternal, Holy, Just God, that we declare to all the world,
that we believe it to be our indispensable duty to meet regularly upon so good an account;
nor shall all the powers upon earth be able to divert us
from reverencing and adoring the God who made us.`"
Then Richard Brown, said.
"`You are not here for the worshipping of God, but for breaking the law.
You do yourselves a great deal of wrong by going on in that discourse.`"
Hereupon W. Penn answered, "`I affirm I have broken no law,
nor am I guilty of the indictment that is laid to my charge.
And in order that the bench, the jury, and myself, with these that hear us,
may have a more direct understanding of this procedure,
I desire you would let me know by what law it is you prosecute me,
and upon what law you ground my indictment?`"
The recorder answered, "`Upon the common law.`"
"`Where is that common law?,`" asked W. Penn.
"`You must not think,`" said the recorder,
"`that I am able to give you an account of so many years, and so many adjudged cases,
which we call common law, to answer your curiosity.`"
"`I am sure that this answer,`" replied W. Penn, "`is very short of my question;
for if it be common, it should not be so hard to produce.`"
The recorder replied, "`Sir, will you plead to your indictment?`"
"`Shall I,`" answered W. Penn, "`plead to an indictment that has no foundation in law?
If my indictment contains the law that you say I have broken,
why should you decline to produce that law,
since it will be impossible for the jury to determine, or agree to bring in a verdict,
when they have not seen the law by which they should measure the truth of this indictment,
and my guilt or innocence.`"
The recorder being angry, said, "`You are a saucy fellow; speak to the indictment.`"
W+++.+++ Penn replied, "`I say, it is my place to speak to matters of law.
I am arraigned as a prisoner; my liberty, which is next to life itself,
is now concerned.`"

At this time several upon the bench argued against the prisoner in order to bear him down.
W+++.+++ Penn said, "`You are many mouths and ears against me,
and if I must not be allowed to make the best of my cause, I find that to be hard.
I say again, unless you show me and the people the law you ground your indictment upon,
I shall take it for granted that your proceedings are merely arbitrary.`"
The recorder then replying, said, "`The question is,
whether you are guilty of this indictment.`"
"`The question,`" said W. Penn, "`is not whether I am guilty of this indictment,
but whether this indictment be legal.
It is too general and imperfect an answer to say
'`it is the common law,`' unless we know both where,
and what the law is.
For where there is no law, there is no transgression; and a law which is not in being,
is so far from being common, that it is no law at all.`"
The recorder the snapped, "`You are an impertinent fellow!
Will you teach the court what law is?
It is _lex non scripta_ +++[+++i.e. an unwritten law],
that which many have studied thirty or forty years to know,
and would you have me tell you in a moment?`"
"`Certainly,`" replied W. Penn, "`if the common law is so hard to be understood,
it is far from being very common;
but if the lord Coke in his institutes be of any consideration,^
footnote:[Sir Edward Coke (1552-1634) was an English lawyer, judge, and politician,
considered to be the greatest jurist of his time.
He is best known for his four-volume [.book-title]#Institutes of the Laws of England,#
and his thirteen-volume [.book-title]#Law Reports.#]
he tells us that common law is common right;
and that common right is the great charter privileges confirmed,
9 Hen. 3. 29. 25 Edw. 1. 1. 2 Edw. 3. 8. Coke`'s Institutes, 2. p. 56.`"
The recorder taking no pleasure in this speech, said,
"`Sir, you are a troublesome fellow,
and it is not for the honor of the court to allow you to go on.`"
"`I have,`" replied W. Penn, "`asked but one question, and you have not answered me;
though the rights and privileges of every Englishman be concerned in it.`"
"`Well,`" said the recorder,
"`if I should allow you to ask questions till tomorrow morning,
you would be none the wiser.`"
"`That would depend`" said W. Penn, "`upon the answers.`"
"`But,`" said the recorder, "`we must not stand to hear you talk all night.`"
Whereupon W. Penn replied, "`I desire no affront to the court,
but only to be heard in my just plea.
And I must plainly tell you, that if you deny me a sight of that law,
which you suggest I have broken, you do at once deny me an acknowledged right;
and you also evidence to the whole world your resolution to sacrifice
the privileges of Englishmen to your sinister and arbitrary designs.`"
This so enraged the recorder, that he called out to the officers, "`Take him away!`"
And to the lord mayor he said, "`My lord,
if you do not take some other course with this pestilent fellow, to stop his mouth,
we shall not be able to do anything tonight.`"
Then the lord mayor cried, "`Take him away; take him away; put him into the bail-dock^
footnote:[A bail-dock was a secured small compartment in a courtroom
used to hold a criminal defendant during their hearing.].`"

W+++.+++ Penn seeing how force and violence prevailed, said, "`These are just vain exclamations.
Is this justice or true judgment?
Must I therefore be taken away because I plead for the fundamental laws of England?`"
Then addressing himself to the jury, he said, "`However,
this I leave upon your consciences who are of the jury, and my sole judges:
that if these ancient fundamental laws which relate to liberty and property,
and are not limited to particular persuasions in matters of religion,
must not be indispensably maintained and observed,
who can say he has right to the coat upon his back?
Certainly our liberties may be openly invaded, our wives ravished, our children enslaved,
our families ruined, and our estates led away in triumph,
by every sturdy beggar and malicious informer as their trophies,
by our pretended forfeits for conscience-sake.
The Lord of heaven and earth will be judge between us in this matter.`"
The hearing of this emphatic speech was so troublesome to the recorder, that he cried,
"`Be silent there!`"
At which W. Penn returned,
"`I am not to be silent in a cause wherein I am so much concerned, and not only myself,
but many ten thousands of families besides.`"

He being now hauled into the bail-dock, it was William Mead`'s turn to plead,
who spoke thus: "`You men of the jury,
I now stand here to answer to an indictment against me,
which is a bundle stuffed full of lies and falsehoods;
for therein I am accused of meeting by illegal force of arms.
There was a time when I had freedom to use a carnal weapon,
and then I thought I feared no man; but now I fear the living God,
and dare not make use of such a weapon, nor hurt any man,
nor do I conduct myself as a tumultuous person.
I say, I am a peaceable man;
therefore it was a very proper question that William Penn demanded in this case,
to have a sight of the law upon which our indictment is grounded.`"
To this the recorder said, "`I have made an answer to that already.`"
W+++.+++ Mead then turning his face to the jury, said, "`You men of the jury,
who are my judges,
if the recorder will not tell you what constitutes a riot or an unlawful assembly, Coke,
he that once they called the lord Coke, tells us what makes a riot or unlawful assembly.
'`A riot is when three or more are met together to beat a man,
or to enter forcibly into another man`'s land, to cut down his grass, his wood,
or to break down his fencing.`'`" The recorder interrupting him,
and scornfully pulling off his hat, said, "`I thank you, sir,
that you will tell me what the law is.`"
And Richard Brown, that inveterate enemy of the Quakers, said, "`He talks at random,
one while an Independent, another while of some other religion, and now a Quaker,
and next a Papist.`"
Mead, not being willing to openly to affront this alderman,
told him this well-known Latin verse:

[verse]
____
"`Turpa est doctori cum culpa redarguit ipsum.`"

+++[+++In English: It is shameful to blame others for the things you do yourself.]
____

For Brown himself had formerly been an Independent,
though he now belonged to the church of England, and was of the court party.
But the lord mayor, who it seems was a great friend of Brown`'s, said to Mead,
"`You deserve to have your tongue cut out.`"
"`And,`" added the recorder, "`if you discourse in this manner,
I shall take occasion against you.`"
To which Mead replied, "`You did promise me that I would have liberty to be heard.
Why may I not have the privilege of an Englishman?
You should be ashamed of such dealing.`"
At this, the envious recorder said,
"`I look upon you to be an enemy to the laws of England,
which ought to be observed and kept.
Nor are you worthy of the privileges that others have.`"
Mead well seeing that force and violence here prevailed,
and that his speaking could not avail, said with a composed mind,
"`The Lord be judge between me and you in this matter.`"

Upon this he was taken away into the bail-dock,
and the recorder gave the jury the following charge:
"`You have heard what the indictment is; it is for preaching to the people,
and drawing a tumultuous company after them; and Mr. Penn was speaking.
If they are not stopped, you see they will go on.
There are three or four witnesses that have proved this, that he did preach there;
and Mr. Mead did not deny it.
Beyond this, you have heard by substantial witnesses what is said against them.
Now we are upon the matter of fact, which you are to keep to and observe,
as you have fully sworn to do, at your own peril.`"
That the recorder spoke this to the jury in the absence of the prisoners,
was indeed irregular; wherefore W. Penn, who heard this from afar,
spoke with a very raised voice, so that he might be heard by those on the bench,
after this manner, "`I appeal to the jury, who are my judges, and to this great assembly,
whether the proceedings of the court are not most arbitrary and void of all law,
in offering to give the jury their charge in the absence of the prisoners.
I say it is directly opposite to,
and destructive of the undoubted right of every English prisoner, as Coke in the 2 Inst.
on the chapter of Magna Charta, speaks.`"
The recorder, being thus unexpectedly lashed for his extra-judicial procedure,
said with a disdainful smile, "`Why, you __are__ present; you heard me, did you not?`"
To which Penn returned,
"`No thanks to the court that commanded me to be put into the bail-dock.
And you of the jury take notice, that I have not been heard,
neither can you legally depart the courtroom before I have been heard,
having at least ten or twelve material points to
offer in order to invalidate their indictment.`"
This plain speaking of W. Penn so enraged the recorder, that he cried,
"`Pull that fellow down!
Pull him down!`"
For Penn it seems, to be heard the better,
had climbed up a little on the rails of the bail-dock.
Then W. Mead said,
"`Is it according to the rights and privileges of Englishmen that we should not be heard,
but rather turned into the bail-dock for making our defense,
and the jury to have their charge given them in our absence?
I say, these are barbarous and unjust proceedings.`"
The recorder yet more incensed, cried, "`Take them away into the hole!
To hear them talk all night, as they surely would,
does not become the honor of the court.`"

The prisoners being taken to a stinking hole,
the jury were commanded to go out and agree upon their verdict;
and after an hour and half`'s time, eight came down having agreed,
but four remained above.
The court then sent an officer for them, and they accordingly came down;
but the court used many indecent threats to the four that dissented,
and after much menacing language, and very domineering behavior against the jury,
the prisoners were brought back to the bar.
The jury foreman was then asked, "`What do you say;
is William Penn guilty of the matter whereof he stands indicted, or not guilty?`"
The foreman replied: "`Guilty of speaking in Gracechurch-street.`"
The next question was, "`Is that all?`"
To which the foreman said, "`That is all I have in commission to say.`"
This answer so displeased the recorder that he said, "`You might as well say nothing!`"
Then the lord mayor Starling, said, "`Was it not an unlawful assembly?
You mean he was speaking to a tumult of people there?`"
To which the foreman replied, "`My lord, this was all I was commissioned to say.`"
Some of the jury now seemed to buckle under the questions of the court;
but others still opposed,
saying they allowed of no such word as an "`unlawful assembly`" in their verdict;
at which some of the bench took occasion to vilify them with opprobrious language.
And because the court would not dismiss the jury
before they gave a more satisfactory verdict,
they called for pen, ink, and paper, and so went upstairs again.
And returning in half an hour, they delivered the following verdict in writing:

[.embedded-content-document.legal]
--

We, the jurors hereafter named,
do find William Penn to be guilty of speaking or preaching to an assembly,
met together in Gracechurch-street, the 14th of August last, 1670;
and that Willam Mead is not guilty of the said indictment.

[.signed-section-signature]
Foreman Thomas Veer, Charles Milson, Edward Bushel, Gregory Walklet, John Hammond,
John Baily, Henry Henly, William Lever, Henry Michel, James Damask, John Brightman,
William Plumsted.

--

This verdict was so highly resented by the mayor and recorder,
that they exceeded the bounds of all moderation and civility.
The recorder then said, "`Gentlemen,
you shall not be dismissed until we have a verdict that the court will accept.
And you shall be locked up without food, drink, fire, and tobacco.
You should not think to thus abuse the court; we will have a verdict by the help of God,
or you shall starve for it.`"

Now, though the jury had given in their verdict,
and signified that they could give no other, yet all was in vain.
W+++.+++ Penn seeing how they were treated against all reason, said, "`My jury,
who are my judges, ought not to be thus menaced.
Their verdict should be free, and not compelled.
The bench ought to wait upon them, but not hinder them.
I desire that justice may be done,
and that the arbitrary resolutions of the bench may
not be made the measure of my jury`'s verdict.`"
This modest speech so incensed the recorder, that he cried,
"`Stop that prating fellow`'s mouth, or put him out of the court!`"
And the lord mayor said to the jury, "`You have heard that he preached,
and gathered a company of tumultuous people,
and that they not only disobey the martial power, but the civil also.`"
To which W. Penn replied, "`That is a great mistake.
We did not make the tumult, but rather those that interrupted us.
The jury cannot be so ignorant as to think that we
met there with a design to disturb the civil peace,
since, first, we were by force of arms kept out of our lawful meetinghouse,
and had met as near it in the street as the soldiers would allow.
And, secondly, because this meeting was no new thing,
nor accompanied by circumstances expressed in the indictment,
but what was usual and customary with us.
It is very well known that we are a peaceable people,
and cannot offer violence to any man.`"

The court now being resolved to send the prisoners to jail,
and the jury to their chamber, Penn spoke as follows:
"`The agreement of twelve men is a verdict in law,
and such a one having already been given by the jury,
I expect the clerk of the peace to record it, as he will answer it at his peril.
And if the jury brings in another verdict contradictory to this,
I affirm they have foresworn themselves.`"
And looking upon the jury, he said, "`You are Englishmen; mind your privilege;
give not away your right.`"
To which E. Bushel, one of the jury, replied, "`Nor will we ever do it.`"
Another of the jurymen pleaded indisposition of body,
and therefore desired to be dismissed; but the lord mayor said,
"`You are as strong as any of them.
Starve then, and hold to your principles.`"
To this the recorder added, "`Gentlemen, you must be content with your hard fate.
Let your patience overcome it; for the court is resolved to have a verdict,
and that before you can be dismissed.`"
And though the jurymen said, "`We have agreed, we have agreed,
we have agreed,`" yet the court appointed several
persons to keep the jury all night without food,
drink, fire, or any other accommodation; indeed, they had not so much as a chamber-pot,^
footnote:[A round container generally used in bedrooms for urination and defecation.]
though it was requested.
Thus force and violence prevailed.

The next day, though it was the first day of the week, commonly called Sunday,
the court sat again.
The prisoners being brought to the bar, the jury were called in,
and their foreman was asked,
"`Is William Penn guilty of the matter whereof he stands indicted, or not guilty?`"
To which the foreman answered as before,
"`William Penn is guilty of speaking in Gracechurch-street.`"
The lord mayor then asking, "`To an unlawful assembly?`"
Edward Bushel answered, "`No, my lord,
we give no other verdict than what we gave last night;
we have no other verdict to give.`"
"`You are,`" replied the lord mayor, "`a belligerent fellow.
I will take a course with you.`"
"`I have,`" said Bushel, "`done according to my conscience.`"
This so displeased the mayor, that he said,
"`That conscience of yours would cut my throat!
But I will cut yours as soon as I can.`"
To which the recorder added, "`He has inspired the jury; he has the spirit of divination.
I think I can feel him.
I will have a positive verdict, or you shall starve for it.`"

Then W. Penn said, "`I desire to ask the recorder one question:
do you accept the verdict given concerning William Mead?`"
To this the recorder answered, "`It cannot be a verdict,
because you are indicted for a conspiracy.
One cannot be found guilty, and not the other.
This cannot be a verdict.`"
This made Penn say, "`If '`not guilty`' cannot a verdict,
then you make both the jury and Magna Charta a mere nose-of-wax.^
footnote:[As mentioned in chapter 13,
the expression "`nose-of-wax`" refers to a person or thing that
is easily twisted or swayed in any direction.]`" "`What?`"
asked W. Mead "`is '`not guilty`' no verdict?`"
"`No,`" said the recorder, "`It is no verdict.`"
To this Penn replied,
"`I affirm that the consent of a jury is a verdict according to law;
and if W. Mead is not guilty, it consequently follows that I too am clear,
since you have indicted us of conspiracy, and I could not possibly conspire alone.`"
After this, the court spoke to the jury, and caused them to go up again,
if possible to extort another verdict from them.
The jury being called yet again, and asked by the clerk, "`What do you say?
Is William Penn guilty of the matter whereof he stands indicted, or not guilty?`"
The foreman answered, "`Guilty of speaking in Gracechurch-street.`"
To which the recorder returned, "`What good is that?
I tell you I will have a verdict.`"
And speaking to E. Bushel, said, "`You are a belligerent fellow,
I will set a mark upon you; and while I have anything to do in this city,
I will have my eye upon you.`"
The mayor, addressing the other members of the jury, then said,
"`Have you no more wit than to be led by such a pitiful fellow?
I will cut off his nose.`"

Thus the court endeavored to baffle the jury;
and therefore it was not without very good reason that William Penn said,
"`It is intolerable that my jury should be thus menaced.
Is this according to the fundamental laws?
Are not these my proper judges according to the great charter of England?
What hope is there of ever having justice done when juries are threatened,
and their verdict is rejected?
I am concerned to speak, and grieved to see such arbitrary proceedings.
Are you not plainly seeking to condemn as '`belligerent
fellows,`' whoever will not answer your ends?
It is sad indeed when juries are threatened to be fined, starved,
and ruined when they will not give verdicts contrary to their consciences.`"
These plain expressions so troubled the recorder, that he said to the lord mayor,
"`My lord, you must take a course with this fellow.`"
And then the mayor cried, "`Stop his mouth jailer; bring fetters,
and stake him to the ground!`"
To this W. Penn said, "`Do your pleasure; I care not for your fetters.`"
The recorder then ventured to say,
"`Until now I never understood the reason and the prudence
of the Spaniards in allowing the Inquisition among them.
And certainly it will never be well with us,
till something like the Spanish Inquisition be established in England.`"
The jury being required to find a different verdict,
and they saying they could give no other, the recorder grew so angry, that he said,
"`Gentlemen, we shall not always be at this impasse with you.
You will find that after the next sessions of parliament there will be a law made,
that those that will not conform, shall not have the protection of the law.
Your verdict is nothing; you make a mockery of the court.
I say now, you must go together and bring in a different verdict, or you shall starve,
and I will have you carted about the city as in Edward the third`'s time.`"

The jury refusing to give another verdict,
since they had all agreed to that which they had given,
and showing themselves unwilling to go out again,
the lord mayor bid the sheriff to make them go.
The sheriff then coming off his seat, said, "`Come, gentlemen, you must go out;
you see I am commanded to make you go.`"
Upon which the jury went out,
and several were appointed to keep them without accommodations as aforesaid,
till they brought in their verdict.
The prisoners were remanded to Newgate Prison, where they remained until the next morning.
Being brought again into the court and set to the bar, the jury were called and asked,
"`Is William Penn guilty of the matter whereof he stands indicted, or not guilty?`"
The foreman answered, "`You have in writing our verdict already,
and our hands have signed it.`"
The clerk who had the paper was then stopped from reading it by the recorder;
and it was said by the court, that "`the paper was no verdict.`"
The clerk then asked, "`What do you say?
Is William Penn guilty or not guilty?`"
To this the foreman answered, "`Not guilty.`"
The same question being asked concerning W. Mead, the foreman answered likewise,
"`Not guilty.`"
The jury then being asked by the clerk whether they all said so, they answered, "`We do.`"
The bench still unsatisfied,
commanded that every person should distinctly answer to their names,
and give in their verdict, which they unanimously did, in saying, "`Not guilty.`"
The recorder, who could not bear this, at last said, "`I am sorry, gentlemen,
you have followed your own judgments and opinions,
rather than the good and wholesome advice which was given to you.
God keep my life out of your hands.
For this the court fines you forty marks a man, and imprisonment until it is paid.`"

W+++.+++ Penn then stepping up towards the bench, said, "`I demand my liberty,
having been freed by the jury.`"
"`No,`" said the lord mayor, "`you are still in for your fines.`"
"`Fines!`" returned Penn, "`for what?`"
"`For contempt of the court,`" said the lord mayor.
"`I ask,`" replied Penn, "`if it is according to the fundamental laws of England,
that any Englishman should be fined or penalized,
except by the judgment of his peers or jury,
since it expressly contradicts the 14th and 29th chapters of the great charter of England,
which say,
'`No freeman ought to be fined except by the oath of good and lawful
men of the vicinity.`'`" Instead of answering to this question,
the recorder cried, "`Take him away, take him away!
Take him out of the court.`"
On which W. Penn said, "`Whenever I urge the fundamental laws of England, you cry,
'`take him away, take him away.`' But it is no wonder,
since the Spanish Inquisition has so great a place in the recorder`'s heart.
God Almighty, who is just, will judge you for all these things.`"
W+++.+++ Penn was not allowed to speak any more,
but he and W. Mead were hauled to the bail-dock, and from there sent to Newgate Prison,
along with their jury.
How they came at length to be freed, I do not know.

This trial was afterwards published in print more at length than is set down here,
and an appendix was subjoined to it,
in which were demonstrated not only the invalidity of the evidence,
but also the absurdity of the indictment, the illegal proceedings of the court, and how,
according to the great charter, the prisoners had been dealt with contrary to law.
The case of lord chief justice Keeling is also mentioned,
who having put restraints upon juries, a committee of parliament,
on the 11th of December, 1667,
came to the resolution that his proceedings were innovations
in a trial of men for their lives and liberties;
and that he had used an arbitrary and illegal power,
which was of dangerous consequence to the lives and liberties of the people of England,
and tended to the introducing of an arbitrary government.
Moreover, that in the place of judicature he had undervalued,
vilified and condemned Magna Charta, and therefore,
that he should be brought to trial in order to receive punishment,
in such manner as the house shall judge most fit and requisite.
Two days after, on the 13th of December,
it was resolved that the precedents and practice
of fining or imprisoning jurors for verdicts is illegal.
The book containing the aforementioned trial of W. Penn
and W. Mead was reprinted I think more than once;
for it came to be much requested,
because the liberties of the people were therein well-defended,
and arbitrary power was controlled.
The title of it was, [.book-title]#The People`'s Ancient and Just Liberties Asserted;#
and underneath was added this well known verse of Juvenal,

[verse]
____
Sic volo, sic jubeo; stat pro ratione voluntas.

(in English: Thus I wish, thus I order, my will stands in place of reason.)
____

This matter was more circumstantially treated of
in a book in print by Thomas Rudyard a lawyer,
who showed therein at some length the right of juries,
and the unlawfulness of the proceedings that were then in vogue;
which he made appear plainly both from the law and
by citations from the books of eminent lawyers.
And having sometimes vigorously pleaded the cause of the oppressed,
he also became the object of persecuting fury,
which could not endure his faithful defending of the innocent.
Therefore, in the summer of this year,
the magistrates of London issued a warrant to break
open his house in the dead of the night,
in order to apprehend him.
This warrant was executed by the soldiers of one captain Holford;
and the next day T. Rudyard was sent to Newgate Prison by a court
order under the hands and seals of the lord mayor Samuel Starling,
William Peak, Robert Hanson, and several others,
under pretense that he had "`stirred up persons to disobedience of the laws,
and abetted and encouraged such as met in unlawful and seditious conventicles,
contrary to the late act.`"
But his case being brought before the justices of the court of Common Pleas,
at Westminster, by a _habeas corpus_,^
footnote:[i.e. a writ of unlawful imprisonment.]
that court, after solemn debate,
gave their judgment that Thomas Rudyard had been unjustly imprisoned and unjustly detained;
and so he was set at liberty.
But the lord mayor Samuel Starling, fretting at this discharge,
found out new stratagems to accomplish his desire upon him.
For an indictment was formed against him for having
hindered due course of law against one Samuel Allingbridge.
But Rudyard so well defended himself, that he was acquitted on this charge;
which so incensed the lord mayor,
that not long after this he again committed him to Newgate Prison on a religious account,
namely, for having been in the meeting at Whitehart-court in Gracechurch-street.
The proceedings against him and others on this account were
no less arbitrary than those against W. Penn and W. Mead,
already mentioned, and therefore Rudyard exposed his and their trials in print.
And seeing he well understood the law,
he was the more able to show the unjustness of these proceedings,
and how inconsistent such prosecutions were with the laws of the land.

But to avoid prolixity I shall relate but little of these other trials,
since many things occur therein which have been mentioned already in other cases.
How the recorder John Howel was inclined with regard to religion,
may be deduced from what has been said already of his encomium upon the Spanish Inquisition.
And to Rudyard and his fellow-prisoners,
he gave no obscure evidence what religion he preferred;
for upon the prisoners saying that they were always quiet and peaceable in their assemblies,
and that the laws against riots were never intended against them,
but against Papist or such like disturbers of the peace, the recorder replied,
that the Papists were better subjects to the king than they were;
and that the Quakers were a stubborn and dangerous people,
and must either be brought under, or there was no safe living by them.
The prisoners offering to vindicate themselves from these odious and foul aspersions,
were not permitted to say anything in their own defense; but instead of hearing them,
they were by order of the lord mayor and the recorder thrust into the bail-dock,
and treated almost in the same way as W. Penn and W. Mead had been before.

But now violence prevailed; and the recorder,
because of his outrageous behavior against the Quakers,
was so much in favor with the court of justice,
that alderman J. Robinson did not hesitate to tell them that he
deserved a hundred pounds for his service done at the Old Bailey^
footnote:[The Central Criminal Court of England and Wales.]
the last sessions.
And this proposal so took,
that the court consented to pay him for the said
service a hundred pounds by the chamberlain of London.
This being very well known to T. Rudyard,
he named the date of the said order--the 8th of October, 1670--in a book he published,
and showed that other orders had been given for two
hundred pounds to him within the past eight months.
And in order to reprehend such doings in a satirical way, he called them,
"`an excellent way to ease the treasury of being over-burdened
with orphans`' money,`" for by such sinister ends,
and distribution of its cash,
the chamber was so deeply in debt that it was almost incredible.

Now, since Rudyard as a lawyer had a more full knowledge of these unlawful
proceedings against him and his friends than many others,
he composed a treatise of those prosecutions,
which he called [.book-title]#The Second Part of the People`'s Ancient and Just Liberties Asserted.#
Many true lovers of their country were pleased with this publication;
for the party which countenanced popery,
and therefore endeavored to violate the people`'s rights,
was now striving to get the upper hand.

Persecution was now very hot and fierce all over the country,
because a door had been opened for all sorts of base
and wicked fellows to get booty by informing;
for according to the act against meetings,
the informer was to receive a third part of the imposed fine.
This set many a vile person to work (and among these
sometimes thieves and infamous fellows),
attempting to give any gathering of Quakers-- though it was but a social visit or a
burial--the name of a "`meeting,`" and then swearing that a meeting had been kept there.
Indeed, sometimes they swore only by guess, that in such a place a meeting had been kept,
though the witnesses had not seen it, as was requisite by law.
And this informing came so much in vogue, that even some magistrates turned informers.

[verse]
____
Quid non mortalia pectora cogis Auri sacra fames!

+++[+++In English: Accursed thirst for gold, what do you not compel mortals to do!]
____

I might write a large volume of these abominable deeds, if I could find leisure for it;
yet now and then I will mention a few instances,
by which the reader may make a conjecture of the rest.

This year at Alford in Somersetshire, in the month called August,
the corpse of one Samuel Clothier was buried,
and though in the burying-place all remained silent, yet the justice, one Robert Hunt,
fined some that had been at the burial for having attended this supposed meeting.

In Nottingham it happened in the latter end of this year, that the justice,
Penniston Whaley,
who had fined many of those called Quakers for attending their religious meetings,
encouraged the people at the court sessions to persecute the Quakers without any pity,
saying to them, "`Harden your hearts against them;
for the act of the 35th of queen Elizabeth is not made against the papists,
since the church of Rome is a true church, as well as any other church.
But these Quakers are erroneous and seditious persons.`"
By these words one may easily judge to what religion this justice of peace was inclined;
but many such pretended to be Protestants, that so they might bear honorable offices.
I pass by unmentioned many persons, who by beating, pushing, and trampling,
were grievously abused in their meetings,
to such a degree that some survived not long after the violence committed upon them,
and felt the painfulness or smart of it until their death.

This year about midsummer, Thomas Bud deceased at Ivelchester in Somersetshire,
after having been prisoner about eight and a half years because, for conscience-sake,
he could not swear.
Some hours before his death,
he was heard to say that he had renewed his covenant with God,
and was well-satisfied in it;
and that he believed God would sustain him by the right hand of His justice;
and that he rejoiced and thanked God that all of
his children walked in the way of the Lord.

At Warborough in Oxfordshire,
those called Quakers were also most grievously abused in their religious meetings,
and even aged women were not spared.
This often caused the cry of innocent children ascend
to heaven when they saw their mothers thus ill treated.
For it was but an ordinary thing at this time for magistrates themselves
to break their canes to pieces on the bodies of those who had met together,
and then sometimes to find other sticks to make use of.
Women were also often stripped of their upper garments,
and such abuse was often accompanied with the spoiling of goods.
However,
that the persecutors were thus enraged was not strange when we
consider that some were stirred up to it by their religious teachers;
an instance of which was given by one Robert Priest of the same place,
who said in his sermon that the king`'s laws, though contrary to the law of God,
yet ought to be obeyed.
Quite otherwise was the doctrine of the apostle Peter and John,
when they said to the Jewish council,
"`Whether it is right in the sight of God to listen to you more than to God, you judge.`"

In Northamptonshire, where persecution was also very hot,
the bishop of Peterborough said publicly in the steeple-house,
after he had commanded the officers to put in execution
the last act against seditious meetings,
"`This law has done its business against all fanatics, except the Quakers;
but when the parliament sits again, a stronger law will be made,
not only to take away their lands and goods, but also to sell them for bond slaves.`"
Thus the churchmen blew upon the fire of persecution.

At York also, the spoiling of goods was fiercely driven on by alderman Richardson;
and even boys and girls that were under sixteen years of age,
and therefore not subject to the penalty of the law, were fined.
And when the constables showed themselves unwilling to assist in such robbery,
they were snarled at, and one was persecuted for not performing his duty,
because he had refused to take away a man`'s cloak.
But if I should mention the ill-treatment committed in all counties and places,
when should I come to a conclusion?

Thomas Green, a grave man, with whom I have been very familiarly acquainted,
being in prayer at a meeting at Sawbridgworth in Hertfordshire,
was pulled off his knees and dragged out.
And being brought before the justices Robert Joslin and Humphrey Gore,
they fined him twenty pounds for speaking or preaching at the said meeting,
and granted a warrant to constables John Smith and Paul Thomson to seize upon his goods;
upon which they went into the said Thomas Green`'s shop in Royston,
and took away as much goods as were worth fifty pounds.
But this did not quench his zeal; for like a true and faithful pastor,
he continued to feed the flock, and to edify the church with his gift,
in which he was very serviceable.

At another time,
justices Peter Soames and Thomas Mead gave a warrant to seize twenty pounds worth of
goods from the said Thomas Green for preaching at a meeting in Upper-Chissel in Essex.
And the officers going to Thomas Green`'s shop, took all they could get,
leaving nothing in the shop but a single skein of thread,
which had fallen on the ground and was not observed by them.

Theophilus Green also suffered great spoiling of his goods;
for having preached in a meeting at Kingston-upon-Thames,
he was put into the stocks for some hours, and fined twenty pounds.
And having preached the three next first-days of the week at Wadsworth,
he was for each occasion fined at the same rate.

The week following, being at Uxbridge,
and visiting some poor children of his friends whose
father and mother died shortly one after another,
he took two of them as his own, and saw to the placing of the rest.
And staying there till the first day of the week,
he went to the meeting and exhorted his friends to
keep their meetings in the name of Jesus.
After speaking these words,
the constable and an informer came in and carried him away to justice Ralph Hawtrey,
who fined him twenty pounds,
and sent him prisoner to Newgate in London with a court order,
wherein he was charged with exhorting the people
to keep their meetings in the name of Jesus,
notwithstanding the laws of men were to the contrary.
Warrants being issued to seize his goods for the above-mentioned
fines (which amounted to one hundred pounds,
five shillings) they came and opened the door of
his home and took away all that they found,
leaving him neither bed nor stool.
And after he had been kept prisoner three months,
he with seven more was brought to the session`'s-house at Hicks`'s Hall,
and there the oaths of allegiance and supremacy were tendered to them.
To this Theophilus Green answered, "`As an Englishman,
I ought either to be acquitted or condemned for the cause for which I was committed,
before I should answer to any other matter or cause.
Besides, I look upon myself to be illegally imprisoned,
as being both fined and committed to jail for the same fact.`"
But they told him he must first answer whether he would swear or not,
and then he would be heard.
But continuing to refuse swearing, he was remanded to prison with the rest;
and afterwards being sent for again,
and still being unwilling to break Christ`'s command not to swear at all,
the sentence of _premunire_ was read against him and his fellow prisoners,
and so they continued in jail above two years,
till they were discharged by an _Act of Grace_ from the king.

The meetings of those called Quakers were miserably
disturbed in Horslydown in the county of Surry.
On the 25th of September several musketeers came into the meetinghouse,
and hauling those that had met together out into the street,
the troopers came riding amongst them and beat and abused them violently,
pushing them with their carbines^
footnote:[A short barreled rifle carried by horsemen.]
and with the but-ends of their muskets to such a degree
that above twenty persons were wounded and sorely bruised.
Indeed, so desperately wicked were these mischievous fellows,
that a party of horsemen attempted to ride over these harmless people; but the horses,
being more merciful than the riders, and not going forward, they turned them,
and by curbing and reigning them backward, strove to do whatever mischief they could.
On the 2nd of October these peaceable people being kept out of their meeting-place,
there came a party of footmen,
and a party of horsemen who abused them no less violently than the week before;
insomuch that with beating and knocking they broke several of their muskets and pikes,
and one carbine,
and above thirty persons were so sorely wounded and bruised
that their blood was spilled in the streets.

On the 9th of the said month, the soldiers,
both horsemen and footmen came again to the meeting at the aforesaid place,
and one of them having a shovel,
threw the dirt and mire from the channels on both men and women.
After this the horsemen and footmen came and fell upon them,
striking and knocking them down without respect to age or sex,
until they drew blood from many.
And when some of the inhabitants in pity took them into their houses to save their lives,
the soldiers forced open the doors, hauled them into the street again,
and plucked off their hats that they might strike them on their bare heads;
insomuch that many had their heads grievously broken open.
Some troopers also tore the women`'s clothes off their backs,
and hauled them through the mire by their horse sides.
Some of the foot soldier`'s put their hands in a
most shameful manner under the women`'s coats;
and one soldier went as far as to strike two times a woman
that was big with child with his musket on the belly,
and once upon the breast, while another flung dirt in her face, so that she miscarried.
Above fifty persons this day were grievously wounded and bruised.

The 16th of the said month,
these conscientious people meeting again to perform their worship to God,
a great party of horsemen and footmen came and fell to beating them so violently,
as if they would have killed all on the spot,
so that the blood ran down about the ears of many.
And when one of the constables endeavored to stop
the wicked crew from shedding more blood,
they fell upon him also, and broke his head.
When they were rebuked for their cruel dealing, some said,
"`If you knew what orders we have, you would say we dealt mercifully with you.`"
And being asked,
"`How can you deal thus with a people who make no
resistance nor opposition;`" they answered,
"`We had rather, and it would be better for us, if you _did_ resist and oppose us.`"
From this it appeared plainly that this mischief was done in order to provoke opposition,
that they might then have excuse to imbrue
their hands in the blood of these sufferers,
and so have had their lives and goods for a prey.
It was therefore thought convenient to acquaint the
king and his counsel with this barbarous cruelty;
which had such an effect, that some stop was made to these excessive cruelties,
though their abuses did not altogether cease.

About this time it happened that Solomon Eccles came to Cork in Ireland,
and went into the cathedral, where the priest, Benjamin Cross,
preached in an Episcopalian surplice.
This priest had formerly been a Presbyterian preacher in Dorsetshire in England,
and there had said that he had rather go to the stake and be burned,
than to put on a surplice; but now had become a turn-coat for profit.
Having finished his sermon and concluded with a prayer, Solomon Eccles said,
"`The prayer of the wicked is an abomination to the Lord.`"
And knowing the deceitfulness of this priest, and his being an apostate, he added,
"`What shall be done to the man that makes shipwreck of a good conscience?`"
For this, S. Eccles was taken and committed to prison by the mayor, where,
after having being kept ten days, he was accused of being a vagabond,
and without any examination, whipped along the streets of Cork,
from North-Gate to South-Gate, receiving about ninety stripes,
and was then expelled from the city.
We have previously seen some instances of his great zeal;
and though in some respects he might have been transported by it a little too far,
yet he gave proofs of having a sincere heart.
For once, sometime after this,
having said to one John Story (who launched out into great haughtiness and arrogance)
that it was the word of the Lord that he should die that year,
yet Eccles himself said afterwards, both at London and Bristol, and elsewhere,
that he had not spoken this according to the counsel of the Lord;
but that it had rather been in his own will, and from his own forward mind.
He also confessed that he had felt the anger of the Lord,
because he had called his own words the word of the Lord; which he truly repented of.

In the beginning of the year 1671, G. Fox was in London,
and though he continued weak after a time of heavy sickness,
yet he did not cease preaching;
and about this time he made the following prayer to the Lord, which he put in writing:

[.embedded-content-document.prayer]
--

O Lord God Almighty!
Prosper the Truth, and preserve justice and equity in the land,
and bring down all injustice and iniquity, oppression and falsehood,
and cruelty and unmercifulness in the land, that mercy and righteousness may flourish.

And, O Lord God!
Establish and set up verity, and preserve it in the land;
and bring down in the land all debauchery, vice, whoredom, and fornication;
and this rapine spirit, which causes and leads people to have no esteem of you, O God,
nor or their souls or bodies, nor of Christianity, modesty, or humanity.

And, O Lord,
put it in the magistrates`' hearts to bring down all this ungodliness and violence,
and cruelty, profaneness, cursing and swearing;
and to put down all these whore-houses and play-houses,
which corrupt the youth and people, and lead them from the kingdom of God,
where no unclean thing can enter; for such works lead people to hell.
In mercy bring down all these things in the nation to stop your wrath, O God,
from coming on the land.

[.signed-section-signature]
G+++.+++ Fox.

[.signed-section-context-close]
This Prayer was written the 17th day, at night, of the 2nd Month, 1671

--

G+++.+++ Fox thinking his wife was at liberty, now understood that her enemies,
notwithstanding the king`'s order to release her,
had found means to hold her still in prison.
Therefore he did not give himself rest,
till by the help of others he obtained from the king a discharge under the great seal,
to clear both her and her estate, after she had been a prisoner ten years,
and premunired.
This royal order he sent immediately down to her, and thus she was set at liberty.

Now since at this time the heat of persecution began to cool,
he felt himself inclined to make a voyage to America, to visit his friends there.
Of this intention he gave notice to his wife by a letter,
and desired her to come up to London; which she accordingly did.
And having taken leave of her,
he set sail in the latter part of the summer towards America,
with several of his friends that accompanied him.

Now while I leave him on board the ship,
I cannot forbear to mention that this year at London
a witty pamphlet came forth with this title, [.book-title]#An Easy Way to get
Money cum Privilegio# +++[+++i.e. without fear or cumber],
printed for the society of informers.
This book contained a satirical rebuke to the informers, beginning with these words:
"`To all you that are able to work, but will not;
and to all those that through other ways of extravagance
have brought yourselves into debt,
necessity, or other needs; for your speedy supply and future support,
there is an opportunity put into your hands that is both safe, profitable, and honorable.
It is to become informers.`"

Next the author said, "`This is an easy way,
since it entails no more than to seek out in any house, barn, or stable,
where there are five persons together, besides those of the family;
even if they never speak a word.
If you will but swear it to be a conventicle, then it is a conventicle.
It matters not if there was never a thought in their hearts as to plotting
or contriving insurrections (for which the law was made),
for merely being together is sufficient to have them
fined five shillings apiece the first time,
and twenty pounds for the house; and for the second time ten shillings apiece;
and it may be for the second time you may get twenty pounds more for the house,
although the act does not grant it.
And of all these fines, the third part is yours.
This you may easily have; for the justices are afraid of your power,
since you are protected by law; indeed, they will not much as question you,
lest they be counted fanatics.
Can your hearts desire more?
Who would not be informers?`"

And as to the profitableness of this employment, the author said,
"`Besides the twenty pounds and ten shillings apiece for a meeting,
if you can but tempt any who are present, by your questions or other provocations,
to speak but a word to answer you, it will serve to make him a preacher;
and then for the first offense there is twenty pounds, and for the second forty pounds.
It is no matter what is spoken, or to what purpose;
if you will but swear that you did hear such a one speak,
it is enough to make him a preacher.`"

In this way the author treated the matter,
taking out of the way all difficulties and scruples which any might have objected;
and though he did this in a comical way, yet what he said was so firm and strenuous,
that he gave proofs of being a man of understanding, and also of great wit.
For though in an ingenious way he showed the abominableness of this informing trade,
yet he proposed it to be safe in every way; for it was never attended with loss,
but always with certain gain.
He further said,
"`And when to all these infallible profits is added the honor of the position,
what could one desire more?
For was it not honorable indeed to command both magistrates and
military officers to follow an informer wherever he would go?
And to obtain this high office, one needed not pay a great cost to purchase it,
nor break his brains with studying;
since at their very first conventicle they might begin as professionals.`"
But of what religious profession these informers could be,
the author himself seemed not to know.
For "`they must be no Jews,`" he said,
"`for these were not to covet their neighbors`' ox, nor ass,
nor anything that was their neighbors.
Neither could they be gentiles, for according to Paul,
the gentiles had a conscience that accused them,
and '`did by nature the things contained in the law,
having the law written in their hearts.`' And they could by no means be Christians;
for these say they forsake the devil and all his works, and all the lusts of the flesh,
and will not hurt any by word or deed.`"

Now I return to George Fox, whom we left in the ship going to America.
During his voyage he suffered much in his body;
for the many hurts and bruises he had formerly received,
and the griefs and infirmities he had contracted in England by cold, hardships,
and long imprisonments, returned upon him now that he was at sea,
and caused him great pain.
And after having been seven weeks and some odd days at sea, he,
with his fellow-travelers, came safe to the island of Barbados.
His occurrences there have been described at length in his journal.
Many of the great men of that place, especially the governor, showed him much kindness.
And after he had edified his friends there on many occasions,
and exhorted them to maintain of good order, both in things relating to the church,
and in the right governing of their blacks, he now, being restored to health again,
departed the island after a stay of three months, and set sail for Jamaica.
He had not been there long,
before Elizabeth Hooton (who has been mentioned several
times in this work) departed this life,
having been well the day before she died;
and thus she finished her days in a good frame of mind.
After he had been there about seven weeks, he performed his service to his satisfaction.

In the beginning of the year 1672 he took shipping for Maryland, where having come,
he and his companions traveled through woods and wildernesses,
over bogs and great rivers, to New England.
Along the way he had sometimes opportunities to speak to the Indians and their kings;
and at other times he met with remarkable cases, all of which, for brevity`'s sake,
I pass by in silence.
He went also to the town formerly called New Amsterdam,
which name is now changed to New York.
Here he lodged at the governor`'s house, and also had a meeting there.
From there he returned again to Maryland, and came also into Virginia and Carolina,
and thus spent above a year traveling to and fro in America.

While he was there, England and France had entered into war against Holland,
and though I still have those times in fresh remembrance,
and in what a wonderful manner it pleased the Lord to save
our country from being quite overrun and subdued,
yet I shall not mention those things, since they are at length set down by other writers.
Yet transiently I will mention something of the remarkable exaltation of William III.
prince of Orange, who afterwards was king of Great Britain.

I have already said in its due place,
how there was an attempt to exclude him by a perpetual
edict from ever being stadtholder or deputy.
But however strong this edict was sworn to, yet heaven brought it to nothing,
and broke the ties of it by the common people of the nation;
for when the French had come into the province of Utrecht,
and all seemed to run into confusion,
the women and many others of the mob forced the magistrates to break their oaths,
and to restore that young and magnanimous prince William
to the honor and dignity of his renowned ancestors.
The miserable fate of the two brethren, John and Cornelius de Wit,
who had been chief instruments in making the said perpetual edict,
and were killed and butchered in a most abominable
manner by the inhabitants of the Hague,
was not without good reason disapproved by many grave and serious people.
It is true, it was a great mistake that they acted in this way,
seeming thus to set limits to the Almighty;
but I do not believe their intention was such,
but rather that what they did in making void the stadtholdership,
they judged conducive to the benefit of their country.
After they were murdered,
the widow of Cornelius de Wit seemed to have a firm
belief that they had entered into everlasting glory;
for though for some time after their death she was under a great concern,
considering how they were hurried out of this life suddenly and unaware; yet at length,
early in the morning, either in a dream or in a vision,
she claims to have beheld them both in a cloud in a glorious form, with hands lifted up,
and clothed with pure white raiment.
By this sight, all her former concern and fear was taken from her,
and she was fully satisfied regarding their eternal well-being.
I have this relation from several credible persons,
who said they had it from her own mouth;
and they all agreed in the material circumstances.

In England,
where it was observed that persecution for religion during
the war could not but be prejudicial to the public,
the king published a declaration whereby the execution of the penal laws was suspended.
But since the Papists, against whom most of these laws had been made,
thus got liberty to enter into offices of trust,
many of the people grew uneasy on this account;
insomuch that the parliament in the year 1673, showed their dislike to the king,
telling him that the penal statutes about ecclesiastical
matters could not be suspended except by an act of parliament.
The king, needing money to continue the war,
yielded somewhat to parliament in respect to the Papist priests and Jesuits,
consenting that the laws against them should continue in force.

This summer G. Fox returned to England and arrived at Bristol,
of which he gave notice to his wife by a letter.
She delayed not to go to him, and with her came her son-in-law Thomas Lower,
and two of her daughters.
Her other son-in-law John Rouse, accompanied by William Penn and some others,
came also from London; and since at that time there was a fair at Bristol,
many other friends came there from other parts of the country.
A large meeting was therefore held there,
in which G. Fox preached concerning the three chief teachers, namely:
That God was the first teacher of man and woman in paradise;
and that as long as they kept to God`'s teaching, they kept in the image of God,
and in righteousness, holiness, and dominion over all that God had made.
But when they hearkened to the false teaching of the serpent, who was out of truth,
and so disobeyed God, they lost the image of God--namely,
righteousness and holines--and so coming under the power of Satan,
they were turned out of paradise.
This serpent was the second teacher, and man following his teaching came into misery,
and into the fall.
Christ Jesus then was the third teacher, of whom God said,
"`This is My beloved Son in whom I am well pleased, hear Him;`" and the Son Himself said,
"`Learn of Me.`" He is the true gospel teacher who never fell,
and was therefore to be heard in all things, since He was the Savior and the Redeemer,
and having laid down His life, had bought His sheep with His precious blood.
Of this subject he treated at length in the said meeting.
After some stay at Bristol, he went to Gloucestershire;
and going from there to Oxfordshire, he came at length to London,
where persecution being not so hot now as formerly,
the Baptists and Socinians were still very active in misrepresenting
the Quakers by publishing several books against them,
in which they asserted that the '`Quakers were no Christians.`'
But these malicious books were not left unanswered,
nor the falsehoods contained in them left unrefuted.

After G. Fox had been some time in London,
he went with his wife and Thomas Lower to Worcester;
and when he signified to her that it was likely a prison would be his share,
she seemed (not without reason) grieved at this news.
Not long after this, he had a meeting at Armscot in Tredington parish,
and after the meeting had ended, he, with Thomas Lower,
sitting in the parlor and discoursing with some friends,
were both taken prisoner on the 17th of December and sent to Worcester
jail by justice Henry Parker under pretense of having kept large
meetings that might be prejudicial to the public peace.
His wife with her daughter then returned into the north;
and by the time he thought she could have arrived home,
he wrote a short letter to her and exhorted her to be content with the will of the Lord.
He also wrote a letter to the lord Windsor, who was lieutenant of Worcestershire,
and other magistrates, wherein he informed them of his imprisonment,
and that he had not been taken in a meeting, but in a house where he had some business.
He also signified that he intended to have visited his mother,
from which he had now been stopped, and could not obtain his liberty.
Yet Thomas Lower might have been set free if he so desired it; for his brother Dr. Lower,
being one of the king`'s physicians,
had procured one Henry Savil to write to the said lord Windsor to release Thomas Lower.
But his love to his father-in-law, G. Fox,
was such that he kept the said letter in his pocket and never sent it;
and so they both continued prisoners.

Now while I leave them in prison, I return once more to Miles Halhead,
of whom mention has been often made already.
He being at Plymouth in this year, felt himself stirred up to go see John Lambert,
who having previously been a general, was now, as has been said in due place,
confined to perpetual imprisonment in a little island not far from Plymouth.^
footnote:[Drake`'s Island]
To this island Halhead passed over, and though he found there a strong guard of soldiers,
yet he got leave to see J. Lambert; and having come to him, he said, "`Friend,
is your name John Lambert?`"
To which Lambert answered, "`Yes:`" which made Miles say, "`Then I pray you, friend,
hear what the servant of the Lord has to say to you;`" and he continued thus: "`Friend,
the Lord God made use of you and others for the deliverance of His people,
and when you cried to Him, He delivered you in your distresses,
as at Dunbar and other places, and gave an opportunity into your hands to do good;
and you promised what great things you would do for the Lord`'s people.
But truly, John Lambert,
you soon forgot the promises you made to the Lord
in that day and time of your great distress,
and turned the edge of your sword against the Lord`'s servants and handmaids,
whom He sent forth to declare His eternal truth; and made laws, and consented to laws,
and permitted laws to be made against God`'s people.`"

To this Lambert said, "`Friend, I would have you know, that some of us never made laws,
nor consented to laws to persecute you, or any of your friends;
for we were ever against persecution.`"
To this Miles replied, "`It may be so;
but the Scriptures of truth are fulfilled by the best of you;
for although you and some others have not given your
consent to make laws against the Lord`'s people,
yet you permitted it to be made and done; and when power and authority was in your hands,
you might have spoken the word,
and the servants and handmaids of the Lord might
have been delivered out of the devourers`' hands.
But none was found amongst you that would plead the cause of the innocent;
and so the Lord God of life was grieved with you,
because you slighted the Lord and His servants, and began to set up your self-interest,
and to lay field to field, and house to house, and make your names great in the earth.
Then the Lord took away your power and authority, your manhood and your boldness,
and caused you to flee before your enemies, and your hearts fainted with fear,
and some ended their days in grief and sorrow,
and some lay in holes and caves to this day.
So the Lord God of heaven and earth will give a just
reward to everyone according to his works.
So, my dear friend, prize the great love of God to you,
who has not given your life into the hands of the devourers,
but has given you your life for a prey, and time to prepare yourself,
that you may end your days in peace.
And truly the Lord is good to all them that fear Him, and believe in His name; for,
though all the powers of the earth rose up against a poor innocent people,
yet the Lord God of life and love was with them, and pleaded their cause,
although all men slighted them.
And truly, the best was but as a brier, and the most upright among them as a thorn hedge.
If the Lord had not pleaded our innocency,
we would not have had a being in the land of our nativity.
But glory to His name forever, who has not permitted more of the wrath of man, nor laws,
nor decrees of men, to come against his people, that believe in his name,
than has been for His honor, and for His glory,
and for the eternal good of all His sons and daughters, and servants.
And the rest, the Lord God of life and love has restrained to this day;
glory and honor and living eternal praises be given and returned to the Lord God,
and the Lamb forever!`"

Thus Halhead ended his speech, and Lambert, who had heard him with good satisfaction,
desired him to sit down, which Halhead did.
Lambert then called for beer, and gave him some drink; after which he said to him,
"`Friend, I do believe you speaks to me in love, and so I take it in love.`"
And then he asked him if he was at the battle of Dunbar?
To which Halhead having answered "`No;`" he further asked,
"`How do you know what great danger we were in at that time?`"
Upon this Halhead gave him to understand that he
passed that way a little time after the fight,
and having viewed the town of Dunbar, and the ground around it were the English army lay,
how the sea was on one side of them, and the hills and mountains on the other,
and the great Scotch army before and behind them,
he then took into serious consideration the great danger the English had been in,
and thought how greatly the Englishmen were indebted to the Lord for their deliverance,
to serve Him in truth and uprightness of heart all the days of their life.
"`Truly John,`" said Halhead then to Lambert, "`I never saw your face before to know you,
although I have been brought before many other English
commanders in the time of Oliver Cromwell.`"
Lambert then asking who these were, Halhead named the generals Fleetwood and Desborough,
major Blackmore, and colonel Fenwick,
before whom he had stood when he was governor of Edinburgh.
Lambert then said that he knew most of those men to have been very moderate,
and that they were ever against persecution.
To this Miles replied, "`Indeed they were very moderate,
and desired not to be seen persecuting or being severe with the Lord`'s people.
But truly, they permitted others to do it,
and took little notice of the sufferings of the people of God;
so that none were found to plead our cause, except for the Lord our God.`"
To this Lambert said,
"`But although you and your friends suffered persecution and hardships in that time,
your cause therein is not now the worse for all that.`"
"`That is very true,`" replied Miles, "`but let me tell you,
in the plainness of my heart, that this is no thanks to you and the other commanders,
but to the glory to the Lord forever.`"
For about two hours Miles discoursed with Lambert, his wife and two daughters,
and after he had cleared himself, he took leave of them and so parted in love.

Now before I leave Halhead,
I will insert here a copy of a letter he wrote in the year 1674 to G. Fox,
who was then prisoner in Worcester jail.
The said letter is as follows:

[.embedded-content-document.letter]
--

[.salutation]
George Fox,

You dear and well-beloved of the Lord, whom He sent out of His eternal love to me,
and many more, who were in darkness and in blindness, seeking the living among the dead,
to show and direct us to the way that leads out of sin and evil, up to God eternal,
blessed forevermore.
May the living, eternal God of life and love, who sent you into the north,
now keep and preserve me by His eternal arm and power,
and keep all my dear friends and brethren truly sensible of His eternal love,
which I bear record has been exceedingly great since the
day the Lord made His precious truth known amongst us.
Therefore, dear George Fox, pray for me, for I am old, and infirm of body,
and the sight of my eyes grows exceedingly weak.
Oh pray that I may be kept faithful and upright to
the Lord in the measure I have received of Him,
in this day of His eternal love, so that I may give my account with joy and rejoicing,
and gladness of heart, and be presented with you, and all my brethren,
blameless before the Lord, and so go to my grave in peace, and rest forevermore.
Amen.

My dear love to my good old friends, Margaret Fox, and Thomas Lower;
their dear and tender love and care to me in months past cannot be forgotten by me,
as I dwell and abide faithful to Him who is my light and life, my joy and peace,
God over all, blessed forevermore.
Amen.

[.signed-section-signature]
Miles Halhead.

--

In the month called January, 1674,
G+++.+++ Fox and Thomas Lower were brought to their trial in the court at Worcester,
it being the last day of the sessions.
When they came in, those on the bench were struck with paleness in their faces,
and continued awhile speechless, insomuch that a butcher in the hall said, "`What!
Are they afraid?
The justices dare not speak to them?`"
At length justice Parker,
by whose order G. Fox and T. Lower had been committed to prison, made a long speech,
much to the same effect as the contents of their court order,
and added that he thought it a milder course to send them to jail,
than to put his neighbors to the loss of two hundred pounds,
which they must have paid if he had put the law in execution against conventicles.
But this was a very poor shift, and a silly evasion;
for there being no meeting when G. Fox came, nor any to inform about,
he had no evidence by which to convict them or his neighbors.

When Parker had ended his speech, the justices spoke to the prisoners,
beginning with Lower, whom they examined concerning why he came into that country.
When they had finished with him, they asked G. Fox for an account of his travels,
which he gave them, and showed them clearly that he and his friends,
of whom so great a noise had been made by justice Parker,
as if many had come together from several parts, were in a manner all but one family.
When he had ended speaking, the chairman Simpson said,
"`Your relation or account is very innocent.`"
Then, after he and justice Parker had whispered awhile together,
the chairman stood up and said, "`Mr. Fox, you are a famous man,
and all this may be true which you have said; but so that we may be the better satisfied,
will you take the oaths of allegiance and supremacy?`"
Now, though G. Fox answered to this,
that they had said they would not try to ensnare him, and that this was plainly a snare,
since they knew that he and his friends would not take any oath, etc.;
yet all was in vain.
They then caused the oath to be read, which being done, G. Fox told them,
"`I never took an oath in my life, but I have always been true to the government.
I was cast into the dungeon at Darby, and kept prisoner six months there,
because I would not take up arms against king Charles at the battle of Worcester.
And for going to meetings,
I was carried out of Leicester and brought before
Oliver Cromwell as a plotter to bring in king Charles;
and you know in your own consciences, that we, the people called Quakers,
cannot take an oath, or swear in any case, because Christ has forbidden it.
But as to the matter or substance contained in the oaths, this I can and do say,
that I do approve and acknowledge the king of England to
be the lawful heir and successor to the realm of England;
and I do abhor all plots and plotters, and contrivances against him;
and I have nothing in my heart but love and good will to him and all men,
and desire his and their prosperity; the Lord knows it,
before whom I stand an innocent man.
And as to the oath of supremacy, I deny the Pope and his power,
and abhor it with my heart.`"
While he was yet speaking, they cried, "`Give him the book!`" (meaning the Bible).
"`The book,`" said G. Fox,
"`says '`Swear not at all;`'`" and he going on to declare his mind further, they cried,
"`Take him away, jailer!`"
The jailer not showing himself very willing, they cried again, "`Take him away!
We shall have a meeting here; why do you not take him away?`"
And one of the bench said, "`That fellow,`" meaning the jailer,
"`loves to hear him preach.`"
The jailer then taking him away, as G. Fox was turning from them, he said,
"`The Lord forgive you, who cast me into prison for obeying the doctrine of Christ.`"
After G. Fox was led away, the justices told Thomas Lower that he was at liberty,
for they did not think it safe to deal with him in the same way as they did with G. Fox,
knowing that he had some protection at court.
Lower asked then, "`Why might not my father-in-law be set at liberty as well as me,
since we were both taken together, and our case is alike?`"
But they telling him they would not hear him, said, "`You may go about your business,
for we have nothing more to say to you, seeing you are discharged.`"

This was all Lower could get from them at that time; therefore,
after the court had risen, he went to speak with them at their chamber,
desiring to know what cause they had to detain his father seeing they had discharged him,
and wishing them to consider whether this was not partiality.
Upon this, chairman Simpson said, "`If you are not content,
we will tender you the oath also, and send you to your father.`"
To which Lower replied, "`You may do that, if you think it fit;
but whether you send me or no, I intend to go and wait upon my father in prison;
for that is now my business in this place.`"
Then justice Parker said to him, "`Do you think, Mr. Lower,
that I had no cause to send your father and you to prison,
when you had such a great meeting,
insomuch that the parson of the parish complained to me
that he had lost the greatest part of his parishioners;
and that when he comes amongst them, he has scarce any auditors left?`"
To this Lower returned,
"`I have heard that the priest of that parish comes so seldom to visit his flock,
but once, or maybe twice in a year to gather up his tithes,
so that it was but charity in my father to visit such a forlorn and forsaken flock.
And therefore you had no cause to send my father to prison for visiting them,
or for teaching, instructing, and directing them to Christ their true Teacher,
seeing that they had so little comfort or benefit from their pretended pastor,
who comes amongst them only to seek his own gain.`"
Upon this the justice fell a laughing, for Dr. Crowder, the priest spoken of,
was then in the room, sitting among them, though Lower did not know him;
but he had the sense to hold his tongue, and not try to vindicate himself.
But after Lower had gone away, the justices so teased Dr. Crowder, that he grew ashamed,
and was so annoyed with it that he threatened to
sue T. Lower in the bishop`'s court for defamation.
Having heard this, however, T. Lower sent him word that he might do so if he desired;
and that he would answer him, and bring his whole parish as evidence against him.
And afterwards told him the same to his face, which so cooled the priest`'s eagerness,
that he thought it more safe for him to let him alone.

Soon after the court sessions were over,
a writ of _habeas corpus_ was sent down to Worcester,
for the sheriff to bring up G. Fox to the king`'s bench bar,
whereupon his son-in-law T. Lower conducted him;
for the under sheriff had made Lower his deputy, to convey G. Fox to London.
Having arrived there, he appeared before the court of the king`'s bench,
where he found the judges moderate.
They patiently heard him as he gave them an account of how
he had been stopped in his journey and committed to jail;
and how at his trial, the oath of allegiance and supremacy had been tendered to him;
and also what he had offered to the justices as a declaration,
and that he was willing to sign this declaration instead of taking the said oaths.
To this it was told him, by the chief justice, that they would further consider it.
Being then delivered to the keeper of the king`'s bench,
he was permitted to go and lodge at the house of one of his friends;
for though he continued a prisoner,
yet they were sufficiently persuaded that he would not run away.
But after this,
justice Parker (as it was said) moved the court that G. Fox might be sent back to Worcester,
in order that his cause might be tried there;
for Parker saw clearly that if G. Fox had been acquitted in London,
it would have tended to his shame, for having committed him unjustly.

A day was then appointed for another hearing,
and G. Fox appeared again at the king`'s bench.
Hearing that it was under deliberation to send him back to Worcester,
he signified to them that this was only to ensnare him by putting the oath to him,
that so they might _premunire_ him.
And he further told them, that though he had never taken an oath in his life,
yet if he broke his yes or no,
he was content to suffer the same penalty as those that break their oaths.
Now seeing Parker had spread a report at London,
and it had been said in the parliament-house,
that when he took G. Fox prisoner there were many substantial
men with him out of several parts of the nation,
and that they had a design or plot in hand,
G+++.+++ Fox did not fail to show the fallacy of that malicious story.
And since he thus laid open Parker`'s shame before his friends at court,
it was not surprising that the king`'s judges complied with
Parker`'s desire to remand Fox back to Worcester jail.
Whatever G. Fox said in his defense, he found he could not prevent it;
only this favor was granted him, that he might go his own way, and at his leisure,
provided he would be there without fail by the time of the court sessions,
which were to begin on the 2nd day of the month called April.

Therefore, after some stay in London, G. Fox went down leisurely,
and having come to Worcester,
he was on the 2nd day of the aforesaid month brought
from the jail to an inn near the sessions hall.
However, not being called that day,
the jailer came to him at night and told him he might go home, meaning to the jail;
whereupon he walked there himself, being accompanied by one of his friends.
Next day being brought up again, a boy about eleven years old was set to be his keeper.
Having in my relation of the proceedings before the
king`'s bench passed over most parts of the pleading,
I shall do likewise here,
to avoid repetitions of what has several times been
related already concerning such trials.
Yet I cannot pass by in silence,
that after he had given an account of his journey before he was taken, he added,
that since his imprisonment, he had heard that his mother,
who was an ancient and weak woman, and had desired to see him before she died,
hearing that he had been stopped and imprisoned in his journey
so that he was not likely to come and see her,
it struck her so, that she died soon after; which had been very hard for him.
Judge Turner, who formerly had been very severe to him, seemed now, as some thought,
inclined to have him set at liberty, since he saw they had nothing justly against him.
But Parker, who had committed him, endeavored to incense the judge against him,
knowing that if he were released,
then he would bear the blame for having committed G. Fox unjustly.
Parker therefore told the judge that G. Fox was a ringleader,
that many of the nation followed him, that there was no telling what it might come to.
The judge gave but little ear to all this, being willing to be moderate;
though he could not resolve to set G. Fox at liberty, lest he should displease others.
Thus in conclusion, G. Fox and his cause were referred to the next sessions,
and he remained a prisoner, but with this proviso,
that he could have the liberty of the town.

By this he got opportunity to speak with many persons, and sometimes with priests too,
one of which asked him whether he was grown up to perfection?
To this he answered, what he was, he was by the grace of God.
"`This,`" replied the priest, "`is a modest and civil answer.
But,`" he continued in the words of the apostle John, "`If we say that we have no sin,
we deceive ourselves, and the truth is not in us.`"
And asking what he said to that, G. Fox replied with the words of the same apostle,
"`If we say that we have not sinned, we make Him a liar, and His word is not in us.`"
Moreover he said, "`Christ came to destroy sin, and to take away sin.
There is a time for people to see that they have sinned,
and there is a time for them to confess their sin, and to forsake it,
and to know the blood of Christ to cleanse them from all sin.`"
After some more reasoning, the priest said,
"`We must always be striving;`" to which G. Fox replied,
"`It is a sad and comfortless sort of striving,
to strive with a belief that we will never overcome.
Paul, who once cried out because of the body of death,
did afterwards thank God who gave him the victory,
and said there is no condemnation to them that are in Christ Jesus.
So there is a time of crying out for lack of victory,
and a time of praising God for the victory.`"
"`But,`" said the priest, "`Not even Job was perfect.`"
To which G. Fox replied,
"`God has signified in Scripture that Job was perfect and upright,
and that he eschewed evil.
And the devil himself was forced to confess that God had set a hedge about him;
which was not an outward hedge, but the invisible heavenly power.`"
"`Yet,`" replied the priest, "`Job charged His angels with folly,
and said the heavens are not clean in His sight.`"
"`That is a mistake,`" said G. Fox, "`for it was not Job who said so, but Eliphaz,
who contended against Job.`"
"`Well,`" said the priest, "`but what do you say of that Scripture,
'`the justest man that is, sins seven times a day`'? "`There is,`" answered G. Fox,
"`no such scripture.`"
So the priest was silent, and this conference was broken off.
I have related thus much to show that G. Fox was not such a simple
person as some (from mere envy) have attempted to represent him;
for he was never at a loss for an answer, but always had one in readiness.

Now when the time of the sessions had come again, G. Fox was called before the justices,
and one justice Street, being the chairman,
exceedingly misrepresented the case by telling the people that G. Fox
had a meeting at Tredington with people from all parts of the nation,
to the terrifying of the king`'s subjects.
"`For this,`" said chairman Street, "`he has been committed to prison;
and for the trial of his fidelity,
the oaths of allegiance and supremacy were tendered to him.`"
Then turning to G. Fox, he asked him, since he had time to consider it,
whether he would now take the oaths?
G+++.+++ Fox having obtained liberty to speak for himself, gave a relation of his journey,
and showed that he and his friends had in no way kept a
meeting that occasioned terror to any of the king`'s subjects.
And as to the oaths, he showed why he could not take them,
and also what he could declare instead thereof.
But notwithstanding all this, the oaths were read to him again;
and he persisting in his refusal to take them, the indictment was read also.
Afterwards the chairman asked him if he was guilty?
G+++.+++ Fox answered, "`No,
since the indictment is a bundle of lies,`" which he proved in several particulars,
asking him if he did not know in his conscience that they were lies.
The chairman then told the jury what they should do in this case;
and before they gave in their verdict, G. Fox said to them, "`It is for Christ`'s sake,
and in obedience to His and His apostle`'s command that I cannot swear.
Therefore take heed what you do; for you shall all be brought before His judgment seat.`"
The chairman then said, "`This is canting.`"
G+++.+++ Fox replied, "`If to confess Christ our Lord and Savior, and to obey His command,
is called canting by a judge of a court,
it is to little purpose for me to say more among you.
Yet you shall see that I am a Christian, and shall show forth Christianity;
and my innocence shall be manifest.`"
By speaking in this way, the people generally were affected;
but the jury still gave a verdict against him, to which G. Fox nevertheless objected.
Thus the matter could not be finished at that time,
and he was therefore asked to put in bail till the next court sessions.
This he refused, and warned his friends who seemed willing to be bound for him,
not to meddle with that, since there was a snare in it.
Yet he told the justices, that he would promise to appear,
if the Lord would give him health and strength, and he was at liberty.
Some of the justices showed themselves loving,
and endeavored to stop the rest from indicting him, or putting the oath to him.
But the chairman said he must continue according to law.
Yet liberty was given G. Fox until the next quarter-sessions.

He then went up to London, where the time of the yearly meeting was approaching.
But at the solicitation of some of his friends,
he appeared again before the judges of the king`'s bench,
and delivered to them the following declaration,
setting forth what he was willing to promise instead of
taking the oaths of allegiance and supremacy.

[.embedded-content-document]
--

This I declare in the truth, and in the presence of God,
that king Charles the Second is the lawful king of this realm,
and of all others under his dominion; and that he was brought in,
and set up king over this realm by the power of God;
and I have nothing but love and good-will to him and all his subjects,
and desire his prosperity and eternal good.
And I do utterly abhor and deny the Pope`'s power and supremacy,
and all his superstitious and idolatrous inventions; and do affirm,
that he has no power to absolve sin.
And I do abhor and detest his murdering of princes or other people by plots and contrivances.
And I likewise deny all plots and contrivances,
and plotters and contrivers against the king and his subjects,
knowing these to be works of darkness, and the fruits of an evil spirit,
and against the peace of the kingdom, and not from the Spirit of God,
the fruit of which is love.
I dare not take an oath, because it is forbidden by Christ and His apostle;
but if I break my yes or no,
then let me suffer the same penalty as they that break their oaths.

[.signed-section-signature]
George Fox.

--

This declaration,
being the substance of what the oaths of allegiance and supremacy contain,
G+++.+++ Fox presented to the judges of the king`'s bench;
but knowing that the proceedings had continued at Worcester,
they were unwilling to meddle with the business,
and only referred it to the next quarter-sessions at Worcester.

The Yearly-Meeting at London having ended, he returned again to Worcester,
where the sessions were held in the month called July.
G+++.+++ Fox being called to the bar, the indictment was read,
and justice Street caused the oaths to be read also, and tendered them to him again.
G+++.+++ Fox then told him he had come to object against the indictment.
But when he began to show the errors that were in
the indictment (which were sufficient to quash it),
he was soon stopped, and the oath was required of him; and he persisting in his refusal,
was found guilty by the jury.
The chairman, though having shown himself very active against G. Fox,
yet now put on a troubled countenance,
and told him of the sad sentence he had to speak against him.
To this G. Fox replied that he had many more errors to allege against the indictment,
besides those he had already mentioned.
Whereupon the chairman told him that he was going to tell him the danger of a _premunire,_
"`which,`" he said, "`is the loss of your liberty, and all your goods and estate,
and to endure imprisonment during your life.
But,`" he added, "`I do not deliver this as the sentence of the court,
but only as an admonition to you.`"
The jailer was then bid to take him away;
and G. Fox was later informed concerning this pretended admonition,
that the chairman had said to the clerk of the peace,
that what he had spoken would stand as Fox`'s sentence.

Now while G. Fox was in prison,
there came to him (amongst others) the earl of Salisbury`'s son, who was very loving,
and appeared much concerned that they had dealt with him in this way;
and he himself took a copy in writing of the errors that were in the indictment.
G+++.+++ Fox afterwards got the circumstances of his case
drawn up in writing and delivered to judge Wild.
He also wrote a letter to the king,
wherein he gave an account of the sentiments of those called Quakers concerning swearing;
and how they abhorred all plotting and contrivances against the king.
Not long after this he fell into such a sickness,
that some began to doubt of his recovery.
One of his friends then went to justice Parker,
by whose order he had been first committed to prison,
and desired him to give order to the jailer that he might
have liberty to go out of the jail into the city.
Whereupon Parker wrote the following letter to the jailer.

[.embedded-content-document.letter]
--

[.salutation]
Mr. Harris,

I have been much importuned by some friends of George Fox to write to you.
I am informed by them that he is in a very weak condition, and very much indisposed.
Whatever lawful favor you can grant him for the benefit of the air, for his health,
please show him.
I suppose the next term they will make application to the king.
I am,

[.signed-section-closing]
Sir, your loving friend,

[.signed-section-signature]
Henry Parker

[.signed-section-context-close]
Evesham, the 8th of October, 1674.

--

This letter was a sufficient warrant for the jailer to permit G.
Fox to be brought from prison to the house of one of his friends.
His wife had come to him before this time,
and after having been with him about seventeen weeks,
and seeing that no discharge was likely to be obtained, she went up to London.
Coming to Whitehall, and meeting with the king there,
she gave him an account of her husband`'s long imprisonment, and how weak he was,
being not without danger to his life.
But to this the king said he could do nothing,
and that she must go to the lord chancellor.
So she went to the lord Finch, who was then chancellor;
and having given him an account of the matter,
told him that the king had left the matter wholly to him,
and if he did not show pity and release her husband out of prison,
she feared he would end his days there.
But the chancellor said to her,
that the king could not release him unless it was by a pardon.
Now G. Fox could not resolve to be freed in this way,
well knowing that he had done no evil.
He therefore would rather have lain in prison all his days,
than to be thus set at liberty; otherwise he needed not to have lain in prison so long,
since the king had been willing long before this to have given him a pardon.
The king had also said to one Thomas More,
that G. Fox needed not scruple about being released by a pardon;
"`for many a man that was as innocent as a child had been granted one.`"
Nevertheless, G. Fox was unwilling to receive a pardon,
but desired to have the validity of his indictment tried before the judges.
The lord chancellor, who showed himself a discreet man,
then procured a writ of _habeas corpus_ in order to bring G. Fox to London,
once more to appear before the king`'s bench.
This _habeas corpus_ was immediately sent down by his wife to Worcester;
but they would not part with him at first (finding
him now a little recovered of his sickness),
under the pretense that he was premunired, and could not go out in that manner.
Thus it became necessary to send to London again;
and another order was obtained and sent down to bring G. Fox before the king`'s bench.
Being still somewhat weak, he was carried to London in a coach,
with the under-sheriff and the clerk of the peace accompanying him.

Having come down, he was brought before the four judges at the king`'s bench,
where counselor Thomas Corbet pleaded his cause, and acquitted himself exceedingly well;
for he started a new plea,
and told the judges that by law they could not imprison any man upon a _premunire._
The judges then saying they must have time to look into their books,
and to consult the statutes, the hearing was put off till the next day.
And since it appeared that Corbet was in the right, they chose to let their plea fall,
perhaps for fear of worse consequences.
They then began to examine the errors of the indictment,
which proved to be so many and so great,
that all the judges were of the opinion that the indictment was quashed and void,
and that G. Fox ought to have his liberty.
The same day several lords and other great men had the oaths
of allegiance and supremacy tendered to them in open court;
and some of G. Fox`'s adversaries pressed the judges
to have the oaths tendered to him again,
saying, he was too dangerous a man to be at liberty.
But judge Matthew Hale, who was then lord chief justice of England,
and really an excellent and pious man (as has been hinted already before) said,
he had indeed heard some such reports of G. Fox,
but he had also heard many more good reports of him.
This statement proved serviceable,
and M. Hale and the other judges ordered G. Fox to be freed by proclamation.
Thus he was set at liberty in an honorable way, and his counselor Corbet,
who had pleaded for him, got great fame by it;
for many other lawyers told him he had brought something
to light which had not been known before.
And after the trial, one of the judges said to him,
"`You have obtained a great deal of honor by your
way of pleading G. Fox`'s cause in court.`"
