== Chapter XIX

[.section-date]
1674--1676

The year was now coming to an end, but before I go over to the next,
I must mention that the Baptists in England,
losing from time to time some of their best members,
wrote very fiercely against the Quakers,
endeavoring thereby to render them no Christians.
But these writings were continually answered in print with so many convincing reasons,
that the Quakers gained even more adherents by it.
The consequence of this was that a public dispute was appointed to be held between
the Baptists and the Quakers in the meetinghouse of the Baptists at London.
For the Quakers, there spoke by turns, George Whitehead, Stephen Crisp, William Penn,
and George Keith; and the opponents were Jeremy Ives, William Kiffin, Thomas Plant,
Thomas Hicks, and one Robert Ferguson,
a Presbyterian who afterwards was eminently known in Holland because of
the fierce declaration he drew up in the name of the duke of Monmouth,
when that unhappy prince went over to England with armed
forces to dispute the throne against king James.

Jeremy Ives was an eminent teacher among the Baptists who had been in prison
in London fourteen years previous to this time on a religious account,
and chiefly because, for conscience-sake, he refused to take the oath.
Not long after his confinement,
he wrote a sharp letter from prison to two members of his society,
who having been imprisoned with him for the same cause,
had taken the oath in order to obtain their liberty.
In this letter he reproved his brethren for falling away,
and signified that they had thus increased the burden of the faithful.
But what a changeable creature is man if he does not continue watchful,
and keep close to the divine grace, continually laying hold thereon!
For scarcely five days after writing this letter,
this inconstant Jeremy grew weary of imprisonment,
and took the oath also to get out of prison.
Nor did he stop there;
for it was plain to all that he had now departed from his religious profession.
Therefore, in order to save face, and to find excuses for what he had done,
he put forth a book in print wherein he asserted the lawfulness of swearing.

It was asked of him at this public dispute whether he was that same Jeremy Ives
who once had been of such a tender conscience that he dared not take an oath,
and then had afterwards publicly defended swearing as lawful?
And he did not deny the fact, for it was notoriously known;
but he went about to disguise the matter, and said,
"`I am that Jeremy Ives who took the oath of allegiance,
and wrote a book to prove that some oaths were lawful, though not all.`"
Nor did he deny the aforementioned letter, for it was in print, and is as follows:

Brother Pitman and Brother Shewel,

I am at this time surprised with a holy passion;
and though Jonah could not say concerning the gourd that he did well to be angry, yet,
if my experience in the word of the Lord does not deceive me,
I can truly say that I do well to be angry with you!
For I am surprised that you are so easily persuaded to part with your spiritual liberties,
and so unwilling to suffer for them.
Oh my brethren!
Where is your first love?
How unlike the Christians in former times are you?
I always did believe,
that those who would abandon the cause of righteousness
would also abandon the ways of holiness,
as yesterday`'s sad experience has proven, to the perpetual joy of your adversaries,
and the saddening the hearts and adding afflictions
to the bonds of the prisoners of the Lord.

I therefore do call upon you, as you will answer the great God one day, to consider,
that now is the time for you to look to your ministry,
and to the flock over which the Lord has made you overseers,
that you may be able through grace to say, you are clear from the blood of all men.
And observe, that God has now come to prove you,
to see whether you will keep His commandments or not.
Remember when that apostate`'s case was debated,
you had no zeal nor indignation against him, but you smothered all with these words:
"`If it were in a matter of faith and worship that he had fallen from,
we would have risen as one man against it.`"
Well, behold the Lord has brought it home to you,
for the matter now is purely about worshipping God.
Now God is proving you to see whether you will obey Him or no.
And did not yesterday`'s work show that you were willing to prefer
the fear of a man (who must die) before the fear of the great God;
and the fear of them that can kill the body, before the fear of the Lord,
who can cast both body and soul into hell?
I have no more to say but this,
that your cowardly compromising and complying with the precepts of men makes
me concerned that your fear towards the Lord is taught by the precepts of men.
I do not desire to be too censorious, but my grounds are great,
and my bonds are my crown; but your cowardly spirit is my great cross.
You little know what a scandal it is amongst us to hear it affirmed that one of you said,
you had rather have given fifty pounds than to have sworn,
and yet now say that you will swear willingly.
Oh! for the Lord`'s sake, do something that may roll away this reproach.
This is the prayers of your brother, who wishes he could call himself,

Your companion in tribulation,

Jeremy Ives

Jan. 14, 1660.

Thus zealously Jeremy Ives wrote to his fellow-teachers, who, because of human fear,
and to avoid sufferings,
had taken an oath contrary to both their profession and the conviction of their consciences.
But who could have imagined on sight of such a letter,
that he himself within so short a space of time,
would have done that which he reproved so severely in others?
Certainly in this case the saying of the prophet Jeremiah seems to be very applicable,
"`The heart is deceitful above all things, and desperately wicked; who can know it?`"
And, "`Let therefore him who stands, be cautious lest he fall.`"
Happy had this man been,
if he had been as sensible of his transgressions as one Edward Chilton,
who though by profession a Quaker,
yet when it came to a trial whether he would take the oath of allegiance or be premunired,
he wavered and fainted.
Yet he fell not away totally;
for he then became so penitent for the evil he had committed,
that he found himself constrained to give proof thereof by a letter he wrote to his
friends who remained prisoners because for conscience-sake they could not swear;
whereas he, to be released from imprisonment,
had taken the oath that was demanded of him.
But what a bitter taste this became to him,
and what terror and horror he was afterwards seized with, the following letter will show:

My dear Friends,

I desire to lay before you my condition in this my fall,
that so my fall may be no cause for you to stumble,
and that by it you may be the more encouraged to stand.
For I have yielded to the betrayer, and so betrayed the innocent Seed in me;
for I forsook the counsel of the Lord, consulted with flesh and blood,
and so I fell into the snare of the world.
Indeed I rested satisfied in what I had done for some hours;
but when the Lord in His power looked back upon me, then I remembered what I had done;
then I remembered that I had denied the truth which once I had professed,
though I once believed I would have stood when others fell.
So now the terrors of the Lord have taken hold of me,
and I lie under the judgments of the Lord.

And now I feel the truth of the words that were spoken by Christ,
that he who fails in one tittle, is guilty of all;
and now I feel the truth that it is better to forsake wife and children,
and all that a man has, even life itself, for Christ and the truth`'s sake,
than to break one tittle of the law of God written in the heart.
So I hope that, by mercy and judgment, the Lord will redeem me to Himself again.
The Lord may allow some to fall,
that the standing of those who stand faithful may seem to be the more glorious,
and for them to take heed lest they also fall.

Now I know and feel that it is better to part with anything of this world,
though it be as dear to one as their right hand or eye, than to break our peace with God.

Pray for me; for my bonds are greater than yours.

Edward Chilton

Windsor, the 22nd of the 11th month, 1660.

It is remarkable that E. Chilton in the conclusion of his letter
says that his bonds were greater than those of his friends,
who neither feared a premunire, nor the loss of their liberty,
if they must pay so dear for it as with the taking of an oath.
For when any one truly abides in the fear of God,
he dares not transgress Divine commandments against the convictions of his conscience,
or seek evasions to avoid the stress thereof; for certainly God will not be mocked.
Could our Savior have spoken in more plain and express terms than He did when He said,:
"`Swear not at all.`"
And yet what cunning devices have been invented by those who boast of the name of Christians,
to weaken the force of these express words.
It is not a proper place here to refute their reasons,
but yet I cannot think it unsuitable to show briefly how dangerous
it is to act against the express commandments of Scripture,
or against the conviction of one`'s conscience, in order thereby to avoid persecution.
For not only the apostle James said, "`Whosoever shall offend in one point,
he is guilty of all;`" but our supreme lawgiver Christ Himself says,
"`Whosoever shall deny Me before men,
him will I also deny before My Father who is in heaven.
And whosoever shall be ashamed of Me, and of My words,
of him also shall the Son of Man be ashamed when He comes in the glory of His Father,
with the holy angels.`"
And to encourage us to faithfulness He has also said, "`Fear not those who kill the body,
but are not able to kill the soul;
but rather fear Him who is able to destroy both soul and body in hell.`"
Which words indeed are so emphatic,
that it ought not to displease any that I repeat them as
they have been left on record by the evangelist Luke,
thus: "`I say unto you, my friends, be not afraid of them that kill the body,
and after that have no more that they can do.
But I will forewarn you whom you shall fear: fear Him, who after He has killed,
has power to cast into hell: yes, I say unto you, fear Him.`"
How can these words not make a powerful impression on a real Christian?
And the more when we consider that nothing in the
world can retrieve or restore a perishing soul,
as may appear from these words of our blessed Lord,
"`What profit is it if a man shall gain the whole world, and lose his own soul?
Or what shall a man give in exchange for his soul?`"
A clear proof that the whole world, and all that is contained therein,
is not able to save one soul, or to afford anything that can redeem it.
If I here thought it requisite,
a godly zeal at present would make me say more on this subject;
but not to enlarge too far beyond the limits of this historical tract,
I shall not pursue this digression any further,
but return to my relation from which I thus stepped aside.

To take up again then the broken thread of my discourse, I once more come to Jeremy Ives,
who, to avoid persecution, had taken the oath contrary to his understanding.
It was Thomas Rudyard, mentioned here before, who mentioned the letter to him;
and Ives feeling himself pinched by it,
endeavored to break the force of it by saying that
the reason he had blamed his friend in the letter,
was only for his saying he had rather have given
fifty pounds than have taken the oath of allegiance,
and yet swore he took it freely and willingly.
But who cannot see what a poor evasion this was?

Now to come to the dispute;
I already mentioned it was asserted that the Quakers were no Christians;
and to maintain this, Thomas Hicks used the following syllogism:

They that deny the Lord`'s Christ, are no Christians;

But the Quakers deny the Lord`'s Christ;

Therefore the Quakers are no Christinas.

To this W. Penn said, "`I deny the minor,^
footnote:[A categorical syllogism consists of three parts: a major premise,
a minor premise, and a conclusion.
Arguing with syllogisms was the most common form of public
debate amongst the educated class at this time.]
that is that the Quakers deny the Lord`'s Christ.`"
And T. Hicks returned:

They that deny Christ to be a distinct person outside of them, deny the Lord`'s Christ;

But the Quakers deny Christ to be a distinct person outside of them;

Therefore, the Quakers deny the Lord`'s Christ.

W+++.+++ Penn then requested that T. Hicks would explain what he meant by the term "`person.`"
And T. Hicks answered, "`I mean the man Christ Jesus.`"
To which W. Penn replied, "`Then I deny the minor, that is,
that we deny the man Christ Jesus.`"
To which Hicks replied, "`I can prove you deny the man Christ Jesus.
One of your own writers says that Christ was never seen with carnal eyes,
nor heard with carnal ears.`"
To this J. Ives added,

He that denies that Christ was ever seen with carnal eyes,
etc. denies the man Jesus Christ;

But the Quakers deny that Christ was ever seen with carnal eyes;

Therefore the Quakers deny the man Jesus Christ.

George Keith then said, "`I answer by distinguishing the following:
Christ as God was never seen with carnal eyes; but as man He was seen with carnal eyes.`"
To this J. Ives returned: "`But He was Christ as He was man;
how then was not Christ seen with carnal eyes?`"
To this question G. Keith answered thus:
"`We are to consider that the terms or names '`Jesus
Christ,`' are sometimes applied to Him as God,
and sometimes to Him as man; yes, sometimes even to the very body of Jesus.
But the question is, whether those names do more properly, immediately,
and originally belong to Him as God, that is,
as He was before He took the manhood upon Him; or to the manhood itself?
We affirm that those names are given to Him most properly and eminently as God;
and less properly, yet still truly, as man; and least properly to His body,
yes even to His dead body.`"
Then J. Ives asked, "`Where do you read that the carcass was called the Christ?`"
This irreverent expression so displeased many, that some cried out,
"`Where did you ever read that Christ`'s dead body was called a carcass?`"
From this disgust W. Penn said, "`I beseech you for the Lord`'s sake,
that we may treat of these things as is fitting for Christians.`"

G+++.+++ Keith then resuming the discourse, answered J. Ives`'s question thus:
"`I prove that the dead body of Jesus was called Christ, from the words of Mary,
'`Where have you laid Him?`' For she had just before called
the body her '`Lord.`' Likewise the angel said to her,
"`See the place where the Lord lay.`"
And the fact that He was Jesus Christ even before He took flesh,
I prove from the saying of the apostle, "`God, who created all things by Jesus Christ.`"^
footnote:[Ephesians 3:9]

Then T. Hicks said, "`I will prove the Quakers to be no Christians.`"
And J. Ives added: "`They that say that Christ cannot be seen with carnal eyes,
and was never visible to wicked men, do deny the Lord`'s Christ;
for He was seen with carnal eyes, and by wicked men.`"
To this W. Penn said,
"`I distinguish upon the word '`seen;`' for wicked
men might see Him in that bodily appearance,
and yet not see Him to be the Christ of God.
They saw His manhood, but not His Christ-ship.
This I will prove from Christ`'s words to Peter, when he confessed Him to be Christ,
the Son of the living God, saying, "`Flesh and blood has not revealed this unto you,
but My Father who is in heaven.`"
Therefore, it follows that Peter, with a carnal eye,
could not have seen the Lord`'s Christ; much less could wicked men really see Him.
My second proof is from the apostle`'s words,
"`Whom none of the rulers of this world knew; for had they known Him,
they would not have crucified Him.`"
W+++.+++ Penn enlarging a little more on this subject, said also,
that seeing and knowing in Scriptures are sometimes equivalent.
And G. Keith added, "`Christ said, '`He who has seen Me,
has seen the Father;`" but no wicked man has seen the Father,
and therefore no wicked man has truly seen Christ, as such.`"
Ives and his companions scoffed at this distinction,
but the Quakers affirmed that all who saw Jesus as the carpenter`'s son,
did not truly see Him as the Christ of God.

Then Ives asked, "`Is the manhood a part of the Lord`'s Christ?`"
To this W. Penn returned, "`You have not yet answered us one question.
But I shall answer J. Ives his question, if he will promise to answer mine.`"
Ives then saying that he would answer it, W. Penn replied, "`I here declare,
that we do faithfully believe that holy manhood to be a member of the Christ of God.`"
And then directing his question to Ives, he said,
"`Was He the Christ of God before He was manifest in the flesh?`"
"`He was,`" answered Ives, "`the Son of God.`"
"`But,`" replied W. Penn, "`Was He the Lord`'s Christ?
I will prove Him to have been the Lord`'s Christ both before and after: first,
from the apostle Paul`'s words to the Corinthians,
that Israel "`drank of that spiritual Rock that followed them,
and that Rock was Christ.`"
Next from Jude, where some Greek copies have it thus,
"`That Jesus brought the people of Israel out of Egypt.`"
But to this Ives gave no answer, regardless how many times he was called upon for it.
And this was no great wonder,
since it was well known that there were such among
the Baptists who favored the Socinian principles.
But Ives, that he might not appear altogether mute, came on again with a question,
saying, "`Do you believe that Christ in His human nature is in heaven?`"
This made G. Whitehead say to the auditory, "`You have heard the charge against us,
and the distinction that has been made between two sorts of seeing of Christ;
namely between the spiritual saving sight of the Lord`'s Christ,
and the seeing of his outward man, person, or body.
In this last sense it was never intended that He was not visible to the outward eye;
but rather as He was the Christ, the spiritual Rock which all Israel drank of,
and as He was before Abraham was,
and as He was glorified with the Father before the world began;
and as Christ Himself said to Philip, '`He that sees Me,
sees My Father also.`' For only saints, or children of light, could truly say,
'`We have seen His glory as the only begotten of the Father,
full of grace and truth.`' In all these last considerations, or senses of seeing,
the Lord`'s Christ was only seen spiritually, and not with carnal eyes.`"
This Ives granted, that so this subject might be left.
Yet immediately after, instead of proving the Quakers to be no Christians,
he asked again,
"`Do you believe or acknowledge that Christ is in heaven with His human nature?`"
To this W. Penn answered,
"`We do believe the man Christ Jesus to be glorified in heaven.`"
But finding that Ives refused to accept this answer
because it was not in the terms of his question,
Penn asked,
"`What difference do you make between the manhood and human nature of Christ?`"
"`None,`" returned Ives, "`if you speak candidly.`"
To which Penn replied, "`I do speak candidly;
we do believe that holy manhood to be in heavenly glory.`"

Now since it began to grow dark, the Baptists desired to leave off the debate,
and to resume the matter at another time; but the parties could not agree on this.
For though the Baptists continued to assert that the Quakers were no Christians,
yet they found that the Quakers had an abundance of reasons to maintain the contrary;
and this they did so effectually, that those of the other party,
under a pretense of the meeting-place being overcharged with people,
and the possibility that the gallery might give way,
broke up the meeting without a final conclusion.

Persecution in this year was not very sharp in London,
but it was very active in other places,
so that I do not lack matter to make a long relation of it.
But to avoid prolixity, I will mention but one case.

One Robert Tillet, in Buckingham, being sick of a consumption,
and believing his death to be near at hand, desired some of his friends to visit him.
At this invitation some came to his house, yet not above the number of fourteen persons.
Two informers then went and acquainted a justice of the peace,
who recorded this small assembly as a seditious meeting,
and fined the sick man twenty pounds for his pretended transgression;
and so his goods were seized, and six cows were taken from him.
And one Robert Smith,
having been heard by the informers to have spoken five or six words,
was fined also twenty pounds as a preacher;
which fine was afterwards extorted from some others who were then present.

The peace between England and Holland concluded this year, at the importunity of Spain,
but the war between Holland and France continued still.

I now pass over to the year 1675,
about the beginning whereof G. Fox came to London while the parliament
was sitting and advising the king to suppress of the growth of popery;
but in the meantime the Quakers still bore the chiefest share of persecution;
for their religious meetings were commonly dubbed seditious conventicles.

After G. Fox had been at the yearly-meeting of his friends in London,
he left the city and went to Lancaster, and from there to Swarthmore.
Here, having a dwelling-place of his own,
he stayed about two years in order to rest himself,
for he had contracted various ailments through hardships
and imprisonments which had much weakened his body.
While there,
he understood that four young students at Aberdeen were convinced at a dispute which
Robert Barclay and George Keith had held with some of the scholars of that university.
And being visited by some of the neighborhood, among the others came also colonel Kirby,
his old persecutor, who now carried himself very lovingly,
and bid him welcome into the country.
Yet notwithstanding this appearance of kindness,
sometime afterwards he ordered the constables of Ulverstone to
tell G. Fox that they must have no more meetings at Swarthmore,
for if they did, they were commanded by him to break them up;
and they would come the next Sunday after.
But this threatening did not make G. Fox afraid; for he, with his friends,
held their meeting on that First day of the week, and none came to disturb them.
During his abode at home,
when he did not travel to and fro in the country to edify his friends as he used to do,
he supplied this need with his pen,
and exhorted them by writing wherever he could not do it by word of mouth.
And besides such letters and epistles he wrote other serviceable treatises,
for he was a diligent man.

In the meantime, persecution for the worship of God did not cease altogether.
The act against seditious conventicles gave opportunity for the
malicious to disturb the religious meetings of the Quakers,
who never met in a clandestine manner, but always publicly.
On this account many fines were extorted from them, to which may be added,
that oftentimes they were still very ill treated and most grievously abused,
as at Long Claxston in Leicestershire,
where some women were dragged by the neck along the street.
Among these was a widow, the skin of whose neck was rubbed off by this rudeness;
and an ancient woman, above seventy years, who was violently thrown down to the ground.
Some of the men were dragged by their hair, and others by their legs,
besides the many blows that were given them.
Indeed, some were trodden upon till the blood gushed out of their mouth and nose.
Yet all this they bore patiently, without making any resistance;
whereby it happened sometimes that those who had not a gift of
preaching nevertheless reached others by their patient suffering;
showing by their meek behavior that their works did agree with their Christian profession.
And though many were robbed of all they had, even their clothes and their beds,
yet they continued steadfast without fainting;
though often it was called a "`meeting`" when some had come
together not properly to perform religious worship,
as has been related already.

At Kirby Muckloe,
where some had come to the house of John Penford to provide for their poor,
the priest of the parish, called John Dixon,
informed against them by a letter to Wenlock Stanly of Branston,
who sent three of his servants to inspect the said meeting.
And though these men looked into the book where the
charitable distributions had been entered,
and found that this meeting had been only to consider the necessities of the poor,
yet several were fined, and J. Penford himself was fined twenty pounds for his house,
and ten pounds for preaching; for having heard him speak,
this was counted sufficient to make him pass for a preacher.
Now though he and Richard Woodland appealed for justice,
yet the court positively denied their appeal unless
they would first take the oath of allegiance.
This was the old snare; thus their hearing was denied,
and treble damages were levied against them.

At Lewes in Sussex, the priest, William Snat, became an informer himself,
and went several times to the Quakers`' meeting there,
and from there to the justice Henry Shully,
to whom he declared upon oath where the meeting had been held, and who had preached.
This business was so shameful,
that once he gave false information with respect to the house;
but the gain proceeding from this work, regardless how abominable,
did shine so alluringly, that his kinsman, James Clark,
also entered upon the office of an informer; which anyone could easily do.

In Norfolk, the rage of the persecutors was such that some, having been bereaved of all,
were obliged even in winter time to lie upon straw, as was the case with Joseph Harrison,
his wife and children.
Yet this family, unwearied, did not leave off attending their religious meetings.
Indeed, not even the dead were not allowed to rest,
for this outrageous barbarity came to such a height, that Mary,
the wife of Francis Larder, being dead and buried, was, by order of one Thomas Bretland,
dug up again, whereby the coffin was broken and carrying away,
and the corpse was exposed in the market-place.
Thus this deceased woman was no more allowed to lie
quiet in her grave than she was in her sick bed,
where the day before her death,
she had been threatened by an order from one Christopher Bedinfield,
to have her bed taken from under her while living.
Now the reason for thus taking up her corpse was that,
though her husband was one of those called Quakers,
yet she not being properly a member of that society,
it was taken ill that she had been buried in a plain way,
without paying to the priest his supposed fee for the customary service over the dead.

In Somersetshire thirty-two persons were fined for having been at a burial.
The same happened in the county of Derby,
where Samuel Roe (his wife being deceased) was fined twenty pounds because
his friends met in his house to conduct the corpse to the grave.
Of this the priest, John Wilson, acted as informer to the justice of peace, John Loe;
and out of the house of the said Samuel Roe was taken the value of thirty pounds;
so that the share of the informer was no less than ten pounds, since according to law,
his due was a third of the spoil.

I could here relate several instances of great calamities
and sad judgments that befell some of these cruel persecutors;
but so as not to elaborate too far, I have silently passed by many remarkable cases.
Yet, in general terms I may say, that many of the persecutors, both justices, informers,
and others, came to a miserable end.
Some were taken out of this life by sudden or unnatural deaths,
and others by lingering sicknesses or distempers, or by foul and stinking diseases;
while some, who by spoil had gathered great riches,
later fell to great poverty and beggary.
Many names I could set down, and mention also the time and place;
and among these some rapacious ecclesiastics who came to a sad end;
but I intentionally omit particularizing such instances
in order to avoid the appearance of grudging and envy.
Some of those that had been so active in spoil,
declared with their own mouths the terrible remorse of conscience
that they felt for having persecuted the Quakers;
insomuch, that some roared out their gnawing grief, mixed with despair,
under the grievous pains they suffered in their body.
And it was judged by many a very remarkable case, that one Christopher Glin,
priest at Burford, who had acted with a very indiscreet zeal against the Quakers,
having about the year 1663 read his text in the pulpit,
and then intending to read his sermon, was all of the sudden struck with blindness,
and continued blind until he died.
But none of the persecutors seemed to take notice, or to regard such instances;
but rather let their rage loose against the Quakers; who, despite all that,
continued in patience;
though they did not think it unlawful to give notice of
the grievous oppression to those that were in authority,
lest they might have excused themselves as ignorant of these violent proceedings.
Therefore,
they did not fail to publish in print many of the
notorious instances that have been here related,
and to present them to the king and parliament with humble addresses to that purpose.
But all of this found but little entrance.
King Charles, it seemed, was not the man who would take off this yoke of oppression;
this work was reserved for others.
His brother James who succeeded him, made a beginning thereof,
with what intention Heaven only knows; and William III.
(that excellent prince) brought it to perfection as far as it was in his power.

This year deceased at sea William Bayly,
coming from the West Indies in the ship called the '`Samuel`', of London,
in the latitude of 46 degrees and 36 minutes.
He had been a teacher among the Baptists, and had read much in the books of Jacob Boehme,
but could not thereby find true satisfaction to his soul.
And being afterwards entered into society with the Quakers, so called,
he became a zealous preacher among them.
When in this his last voyage he had grown sick and felt death approaching,
he bid John Clark, master of the said vessel,
to remember him to his dear wife and little ones, and also, to George Fox,
George Whitehead and others; and being filled with joy, began to sing, saying,
"`The creating Word of the Lord endures forever.`"
He took several that were about him by the hand and exhorted them to fear the Lord,
and not to fear death.
"`Death,`" said he, "`is nothing in itself; for the sting of death is sin.
Tell the Friends in London, who would have been glad to have seen my face,
that I go to my Father and their Father, to my God and their God.
Remember my love to my dear wife; she will be a sorrowful widow;
but let her not mourn too much, for it is well with me.`"
And having spoken something concerning his outward business to the master,
he said in regard to his wife and children, "`I have left them no outward portions,
but my endeavor has been to make God their father.
Shall I lay down my head upon the waters?
Well, God is the God of the whole universe; and though my body sink in the sea,
I shall swim a-top of the waters.`"
Then taking his leave of the company, he said, "`I cannot see any of you,
but I wish you all well.`"
And when one asked how it was with him, he answered, "`I am perfectly well.`"
After having spoken many more sensible words,
at about four in the morning he quietly departed, as if he had fallen asleep.
His wife Mary,^
footnote:[Mary Bayly`'s maiden name was Mary Fisher,
mentioned in chapter 7 and 10 of this history.]
the same that had formerly been at Adrianople and spoken with the emperor of the Turks,
gave an excellent testimony in writing concerning him.
And John Crook, in a preface to W. Bayly`'s works,
gave the following testimony of him (the truth of which I know by my own experience):

As he was bold and zealous in his preaching,
being willing to improve his time (as if he had known it was not to be long amongst us),
so was he as valiant in suffering for his testimony when called thereunto.
I saw him once stand at the bar to plead his innocent cause, like holy Stephen,
in the senate-house,
when the threats of his persecutors resembled the
showers of stones falling upon that blessed martyr,
crying out with a hideous noise, "`take him away, jailer,`" etc.,
and yet all this while he changed not his countenance,
except by the additional ornament of some innocent smiles.
Sometimes by cruel persecutors he has been thrown down and
dragged upon the ground by the hair of his head,
and his mouth and jaws were endeavored to be rent and broken asunder,
so that the ground whereon he lay was smeared with his blood.
And as if this butchering had not been enough to make him
a fit sacrifice for the shambles of their cruelty,
a heavy bodied persecutor stamped upon his breast with his feet,
endeavoring to beat the breath out of his body.
And when this persecutor had done his pleasure, he commanded the jailer to take him away,
and put him in some nasty hole for his entertainment and cure.
And had not the God of Israel been his physician there,
he had been taken from us long before this.

At the beginning of this year, 1676, one Matthew Hyde died at London.
This man had made it his business, during the space of about twenty years,
to publicly contradict the Quakers in their meetings,
and to disturb them in their worship of God,
thinking (from a blind zeal) that he did God acceptable
service by zealously opposing what he judged to be heresy.
Now, however much this man was bent against them, yet he showed this moderation,
that in his gainsaying he did not behave himself furiously,
but appeared to be well-meaning, although he erred exceedingly,
and often hindered the preaching of ministers among the Quakers.
This induced William Penn sometimes to pray to God very earnestly for him,
and to tell him in the presence of many auditors that God
would plead with him by His righteous judgments;
and that a time would come when he should be forced to confess
to the sufficiency of that light which he then opposed,
and to acknowledge that God was with those who were called Quakers.

This same Hyde being brought to the brink of death by sickness,
requested that George Whitehead and some of his friends might be sent for;
and to one Cotton Oade,
who asked him if he had anything to say to clear himself concerning his having
so often opposed the people called Quakers in their ministry and prayers,
he said, "`I am sorry for what I have done; for they are the people of God.`"
G+++.+++ Whitehead then, though it was late in the evening,
having come to him with some others, said,
"`I have come in love and tenderness to see you.`"
To which Hide replied, "`I am glad to see you.`"
Whitehead said, "`If you have anything on your conscience to speak,
I desire you to clear your conscience.`"
To this M. Hide replied, "`What I have to say, I speak in the presence of God.
As Paul was a persecutor of the people of the Lord, so I have been a persecutor of you,
His people; even as the world persecutes the children of God.`"
He spoke more, but being very weak, his words could not well be understood.
Then G. Whitehead resumed, "`Your understanding was darkened when darkness was over you,
and you have opposed the truth and people of the Lord;
and I knew that that light which you opposed, would rise up in judgment against you.
I have often, with others, labored with you to bring you to a right understanding.`"
To this Hide said, "`This I declare in the presence of God, and of all who are here:
I have done evil in persecuting you who are the children of God, and I am sorry for it.
May the Lord Jesus Christ show mercy unto me, and the Lord increase your number,
and be with you.`"
After some pause G. Whitehead said to him, "`I would have you, if you are able to speak,
to ease your conscience as fully as you can.
My soul is affected to hear you thus confess your evil,
as the Lord has given you a sense of it.
In repentance there is mercy and forgiveness; in confessing and forsaking sin,
there is mercy to be found with the Lord, who in the midst of judgment remembers mercy,
that He may be feared.`"
M+++.+++ Hide being in great anguish, and striving for breath, said, a little after,
"`I have done evil in opposing you during your prayers; may the Lord be merciful unto me.
And as I have been an instrument to turn many from God,
may the Lord raise up many instruments to turn many to Him.`"
G+++.+++ Whitehead resumed,
"`I desire that you may find mercy and forgiveness at the hand of the Lord.
How is it now with your soul?
Do not you find some ease?`"
"`I hope I do,`" answered Hide, "`and if the Lord should lengthen my days,
I would be willing to bear a testimony for you,
just as publicly as I have appeared against you.`"
His wife then said, "`It is enough; what more can be desired?`"
"`If,`" queried Whitehead, "`the Lord does not lengthen your days,
do you desire that what you have said should be communicated to others?`"
"`Yes,`" answered Hide, "`I do.
You may; I have said as much as I can say.`"
After some silence, he being very much short for breath, Whitehead said,
"`If this company is wearisome unto you, we may withdraw.`"
To which he replied, "`You may use your freedom.`"
G+++.+++ Whitehead then taking leave of him, said, "`I shall leave you to the Lord,
desiring he may show mercy and forgiveness unto you, as I hope He will.`"
Upon this, M. Hide replied, "`May the Lord be with your spirits.`"

All of this was spoken to G. Whitehead and his friends in the presence of Hide`'s wife,
and some others of his acquaintance, about two hours before his death,
and thus he gave manifest proofs of a sincere repentance.
For Elizabeth, his wife, having perceived him to be much troubled in his mind,
had asked him if he desired to speak with some of the Quakers?
And he smiting his hand on his breast, had said, "`With all my soul.`"
After G. Whitehead and his friends were gone, it being the seventh day of the week,
he desired several times that he might live until morning,
and bear on that day (the first day of the week)
a testimony for the truth that he had so often opposed;
yet he signified that he had already found some ease to his spirit.
He also exhorted his wife, who conversed much with people that were great in the world,
to use the plain language of the Quakers.
And after some more words to this purpose, spoken by him with good understanding,
he stretched himself out and died very quietly.
Thus, indeed, we see a very evident token of God`'s unspeakable mercy,
who wills not the death of a sinner, but that he should repent and live; and who,
entirely knowing the real disposition of man`'s heart, forgives sin by mere grace,
without any merit in man, but for His own sake, as He has said Himself,
"`I am He that blots out your transgressions for My own sake,
and will not remember your sins.`"^
footnote:[Isaiah 43:25]
The truth of which saying very plainly appeared in the converted thief on the cross,
though his impenitent fellow-sufferer hardened his heart against it.

In this year, while G. Fox was at Swarthmore, died William Lampitt,
the priest of Ulverstone,
who formerly had been a great friend to Margaret (now the wife of G. Fox),
but who grew so envious against the friends she was
in society with that he said in the year 1652,
he would wage his life that the Quakers would all
vanish and come to nothing within half a year.
But on his deathbed he said to one of his hearers who came to visit him,
"`I have been a preacher a long time, and thought I had lived well;
but I did not think it would be so hard a thing to die.`"

At Norwich now great spoil was made upon the Quakers because of their religious assemblies.
Erasmus Cooper coming once into the house of Anthony Alexander,
said to his wife who was expecting a child, that he came to seize "`all she had.`"
"`All?`"
said she, "`For a fine of seven pounds?
That is hard.`"
But he slighting what she said, replied that he would not leave her a bed to lie on.
They then began to break the doors with a pick-axe;
and he and his companions behaved themselves so desperately,
that it drew tears from some of the neighbors who beheld it.
At one point these plunderers forced Alexander`'s servant to help them;
which made Alexander say that it was a most unreasonable thing
to require a servant to assist in taking his master`'s goods.
In response to this, the warden, Robert Clerk, snarled at him and said,
"`They are our goods.`"
The aforesaid officers came also to the house of Samuel Duncon,
and with them came the informer Charles Tennison, and the hangman.
Here they stayed several days and nights, and kept Samuel`'s wife,
who was xpecting a child, a prisoner in her own house,
not allowing her to speak with any, nor permitting any to come to her.
And after they had broken open all the locked doors,
they took away to the value of about forty-three pounds in goods.
So insolent were these informers, that one did not hesitate to say,
"`I will make the mayor wait upon me as often as I will, at my pleasure.`"
Indeed,
this wicked crew had become so powerful that none dared
oppose them for fear of falling into disgrace with the court;
for they were encouraged by those who were in high stations,
and probably at the importunity of the Papists, or popishly affected.
The constable, William Poole,
coming this summer into a meeting of the Quakers at Norwich with an informer,
who made him come, and hearing the preaching there, cried out with tears in his eyes,
"`What shall I do?
I know the power of God is among you;`" and then he told the informer,
that if there were a curse hung over any people upon the earth,
it was over the informers.
And Tennison the informer, who had assisted in taking away Samuel Duncon`'s goods,
being afterwards committed to prison for debt,
confessed he never prospered since he put a hand to that work;
and said if he were at liberty, he would never meddle with it again.

In Nottinghamshire also, great spoil and havoc was made,
to which the justice Robert Thoroton was greatly instrumental.
For at Sutton he gave forth a warrant to seize the goods of two persons,
one of which was a woman, who having spoken five or six words in a meeting--which,
according to the testimony of some officers that were present,
were not at all like preaching--was however informed against as a "`preacher,`"
and so fined by the said justice Thoroton twenty pounds.
She being unable to pay, one half of the fine was charged upon her,
and the other half was charged upon John Fulwood.
At another time, Thoroton gave order to seize the goods of William Day, a miller.
This man, having been at a meeting at Sutton, in the street,
had a fine of twenty pounds charged upon him when
the supposed preacher was unable to pay;
though W. Day proved (and the officers who kept the friends out of their meeting
place also declared) that the words which were called "`preaching`" at this meeting,
were no more than an answer to what another had spoken.
But for all that, Thoroton, in order to protect and to gratify the informer, said,
"`Though but one word was spoken, it is sufficient.`"
A poor woman at South Collingham,
who was already bereaved of almost all that she possessed,
and who since had been provided with a bed and other necessaries by her friends,
was also deprived of these things too, because she continued to attend meetings.
Matthew Hartly, a poor man, who lived by spinning wool, was likewise,
for attending the meeting there, bereaved of what he had; and so it was with many others,
whose names and surnames I could mention if I had a mind to enlarge.
And if their friends had not taken care of them,
and other impoverished families who had lost all by spoil, many might have perished.

In the town of Hereford the meetings were also disturbed from time to time,
chiefly by boys who threw not only stones and excrement, but also burning squibs;^
footnote:[A little pipe or hollow cylinder of paper,
filled with powder or combustible matter and sent into the air.
Similar to a modern firecracker.]
and used all manner of insolence and mischief against these harmless people,
either by breaking the glass windows, or the benches and seats.
One of the leaders of this turbulent company was the son of one Abraham Seward,
who about this time was elected mayor.
But when complaints were made to him concerning the
outrageous actions of this wicked crew,
he pretended to be ignorant of his son`'s doings,
and threatened those that came to him with the execution of the
law upon them if they did not discontinue their meetings.
And as it was well known that the chief master of the town-school
was displeased at the excessive insolence of some of his students,
so it was reported also, that he was forbidden to correct them for it,
and that the college priests had encouraged them to do it,
saying they would back them up in what they did;
for some of these brutish boys were singers in the choir.
Two friends went to the justices, Robert Simons and Thomas Simons,
to acquaint them with the excessive abuses that they had met with.
But the justices not at all regarding their complaint,
R+++.+++ Simmons endeavored to draw some confession of a meeting from one of them, intending,
as he himself said, to immediately have fined him if he had confessed.

Now since the insolence of these boys was thus encouraged by the authorities,
it was no wonder it continued there a whole year.
At length eight men were taken from the meeting by the aforesaid mayor, Abraham Seward,
and carried to the town-hall; and in their passing along,
he said they would never meet there again.
In response to this, a friend, going with him, said,
"`We are a people gathered by the power of the Lord;
and therefore the power of man cannot scatter us.`"
Having come to the town-hall,
the oaths of allegiance and supremacy were tendered to them, on which they said,
"`We are Christians,
and therefore cannot break the command of Christ which forbids us to swear at all.
But, to render just and lawful allegiance to the king, we do not deny or refuse.`"
And persisting in their refusal to swear, they were committed to prison.
The next day, one Walter Rogers, a clergyman, walking by the Quakers`' meetinghouse,
and observing how it was broken, said to some to some of the youth,
that they were very good boys, and had done their work better than he thought they had.

At one of the quarter-sessions in Nottingham, one John Sayton appeared, who,
having been fined twenty pounds for allowing a conventicle in his house,
in the parish of Blyth, came to appeal for justice.
The witness produced against him, said, "`I was there on that day,
and there were several people met together, but all were silent,
and there were no words spoken amongst them; but I did not see John Sayton there.`"
Now, that the said John Sayton was above sixty miles away from home
the same day was made appear in open court by substantial evidence.
Then the counsel for the defendant said, "`In the first place,
forasmuch as there was neither preaching, praying, nor reading,
as their own witness does testify,
it therefore could not have been a religious conventicle.
Secondly, seeing they cannot prove he was there,
how can it therefore be judged that he did either
knowingly or willingly consent to that meeting?`"
To this the informer`'s counsel objected, saying, "`Although there was neither preaching,
praying, or reading,
yet it is evident enough that they met under a pretense of religious exercise;
and seeing that there were more than five who were not of John Sayton`'s family,
therefore it must necessarily be a conventicle.
And as to the second question, seeing we cannot prove he was there,
we must leave it to the consciences of the jury,
whether he did willingly consent to the meeting or no.`"
After the counsel had spoken on both sides, Peniston Whaley,
one of the justices who sat in the chair as judge of the court, stood up,
and said to the jury,
"`Although there was no visible religious exercise that can be proved,
yet the Quakers say they worship God in spirit and truth;
and we know their manner is to sit sighing and groaning,`" etc.
The jury returning, and being asked by the court, "`Do you find for the king,
or for the defendant?`"
answered, "`For the defendant.`"
This so displeased the said justice Whaley,
that he bid them go forth again and reconsider.
But one of the jurymen saying that they had agreed,
and had considered the thing very well, he thereupon fell into such a rage, that he said,
"`You all deserve to be hanged; for you are no better than highway robbers!`"
Perhaps he himself was either an informer, or a special friend to such,
and therefore was sorry that the jury had deprived him of the booty, or a share of it.

There was now great persecution in all parts of England,
and it faired no better in the principality of Wales.
This summer, in the county of Merioneth, in the town Bala,
nine persons were taken prisoners and brought to the court session
upon an indictment for not attending their parish churches,
and the oaths of allegiance and supremacy were tendered to them.
Upon their refusal to take these oaths,
judges Kemick Eyton and Thomas Walcot declared it as their opinion in open court,
that in case the prisoners would refuse the oaths a second time,
they should be prosecuted as traitors; the men should be hanged and quartered,
and the women burnt.
But this threat did not make them afraid;
for at the next court session when the oaths were tendered to them again,
they continued in refusing,
though they solemnly acknowledged allegiance to the king as the supreme magistrate.
They were thereupon remanded to close imprisonment, where one of them named Edward Rees,
being above sixty years of age, was not able to bear the cold,
and so died about the height of the frost, not having been allowed the use of a fire.

Sometime before this, it happened within the corporation of Pool, in Montgomeryshire,
that the justice David Maurice,
came into a house where a small number of people were peaceably met in silence,
and required them to depart.
Hereupon Thomas Lloyd, one of the company,
began to speak a few words by way of defining true religion, and what true worship was.
Now what he said was so reasonable,
that the said justice approved of it as being sound and
according to the doctrine of the church of England.
Notwithstanding, he still fined the said Thomas Lloyd twenty pounds for preaching.

This year died in prison John Sage, being about eighty years of age,
after having been in prison at Ivelchester in Somersetshire
almost ten years for not paying tithes.
It also appeared that since the restoration of king Charles,
more than two hundred of the people called Quakers had died in prisons in England,
where they had been confined because of their religion.
I could relate an abundance of occurrences this year if I had a mind to extend my work;
yet cannot omit to mention, that in this year, in the island of Barbados,
in the West Indies,
a law was made to prevent negroes from coming into the meetings of the Quakers,
which is as follows:

Whereas of late,
many negroes have been allowed to remain at the meetings
of the Quakers as hearers of their doctrine,
and have been taught their principles,
whereby the safety of the island may be much hazarded; let it be enacted,
that if at anytime after the publication hereof, any negro, or negroes,
be found with the people called Quakers, at any of their meetings,
as hearers of their preaching,
he or they shall be forfeited--one half to such as shall seize or sue for him or them,
if belonging to any of the Quakers, and the other half to the public use of the island.
And if such negro, or negroes,
do not belong to any of the persons present at the same meeting,
any person or persons may bring an action upon this statute
against any of the persons present at the said meeting,
at the election of the informer, and so recover ten pounds for every negro, or negroes,
present at the said meeting as aforesaid, to be divided as aforesaid.

And no person whatsoever shall keep any school, to instruct any child in any learning,
unless he first take the oaths of allegiance and supremacy before
some justice of peace of the parish where the party lives,
and have a certificate thereof, or have a special license from the governor,
on pain of three months imprisonment, and forfeiture of 300 lbs.
of Muscovado sugar--the one half going to the informer,
and the other to the public use of the island.
And no person whatsoever, who is not an inhabitant and resident of this island,
and has been so for twelve months together,
shall hereafter publicly discourse or preach at the meeting of the Quakers,
on pain of six months imprisonment, and forfeiture of 1000 lbs.
Muscovado sugar, the one half to such as sue for it,
the other to the public use of the island.

Read, and passed the council the 21st of April, 1676,
and consented to by his excellency +++[+++the governor]
the same day.

Edward Steed Deputy-secretary.

Although in the beginning of this statute,
the instructing of the negroes in the doctrine of the Quakers is represented
as a thing whereby the "`safety of the island might be much hazarded,`"
yet the outcome shows that this was not at all the issue,
but that it was endeavored to deprive the Quakers of their due liberty.

This year Robert Barclay wrote a letter to the Herr Adrian Pacts,
with whom he had some discourse when the said Herr returned from Spain,
where he had been ambassador for the States of the United Provinces.
Herr Pacts, having a strange opinion of the doctrine of the Quakers,
had a good while ago written a letter^
footnote:[To be found in the book called Prastantium ac
eruditorum virorum Epistole Eccksiastique & Theologica.
Amatelodami apud Franciscum Halman.
1704]
to Christian Hartzoeker, at Rotterdam, about their doctrine;
and having afterwards discoursed with Barclay concerning
the inward and immediate revelation of the Spirit of God,
this induced Barclay to write a letter to the aforementioned
Herr on the subject in Latin,
wherein he made a larger reply to his arguments than he had done in person.
This letter being sent over from Scotland to Holland,
was delivered by Benjamin Furly at Rotterdam, to the said Herr Pacts,
with a desire that he might be pleased to return an answer to it,
which he promised he would do.
But he continuing deficient in the case,
Furly at last published the said letter in print,
but without mentioning the name of him to whom it was written,
only that it was addressed to Cuidam legato +++[+++in English: To a certain ambassador.]

In this letter was set down first the objection of Herr Pacts, namely,
that since the being and substance of the Christian
religion consists in the knowledge of,
and faith concerning, the birth, life, death, resurrection,
and ascension of Christ Jesus,
he considered the substance of the Christian religion to be a contingent truth;^
footnote:[A contingent truth is a proposition that is true but could have been false.
The truth of the proposition depends upon something else.
A necessary truth is a proposition that could not be false upon any circumstances,
because its negation implies an impossibility or a contradiction in reality.]
which contingent truth was a matter of fact.
And matter of fact, he argued,
could not be known except by the relation of another person,
or by the perception of the outward senses;
because there are naturally in our souls no ideas of contingent truths,
such as there are concerning necessary truths, such as, that God is,
or that the whole is greater than the part.
And since it might without absurdity be said that God cannot
make a contingent truth to become a necessary truth;
neither can contingent truths or matters of fact
be revealed except trough the outward senses,
the conclusion drawn from there was that men are not obliged to believe
that God produces any revelation in the soul concerning matter of fact,
unless He also add some miracles that are obvious to the outward senses,
by which the soul may ascertain that the revelation undoubtedly comes from God.

All of this was treated at length by Barclay, as may be seen in the following letter;
and several years afterwards, when the Herr Pacts was at London,
being one of the commissioners for the Dutch East India company,
Barclay spoke with him again, and so represented the matter,
that Pacts readily yielded that he had been mistaken in his notion of the Quakers;
for he found they could make a reasonable plea for the foundation of their religion.
Thereupon R. Barclay translated the said letter into English as follows:

My Friend,

Albeit I judge I did fully answer all your arguments in that conference we had,
concerning the necessity and possibility of inward immediate revelation,
and of the certainly of true faith proceeding therefrom; nevertheless,
because after we had ended and were parting,
you recommended me to the further consideration of the strength of your argument,
as that in which you suppose the very hinge of the question to lie;
in order that I might satisfy your desire, and that the truth might more appear,
I did further consider of it; but the more I weighed it, I found it the weaker.
And therefore, that you yourself may make the truer judgment of it,
I thought fit to send you my further considerations thereon;
(which I would have done before now, had not I, both at London and elsewhere,
been diverted by other necessary occasions,) wherein I doubt not,
but that you will perceive a full and distinct answer to your argument.
But if you cannot as yet yield to the truth,
or think my answer in any part to be defective,
so that there yet remains with you any matter of doubt or scruple;
I do earnestly desire you, that as I for your sake, and out of love to the truth,
have not been lacking to examine your argument,
and to transmit to you my considerations thereon,
so you may give yourself the trouble to write and send me what you have further to say:
which my friend N. N. who delivers this to you, will at whatever time you shall appoint,
receive from you, and transmit to me, that at last the truth may appear where it is.

And that the whole matter may the more clearly be understood,
it will be fit in the first place to state your argument,
whereby you oppose the immediate revelation of God in the saints,
and from there conclude that you have fully overturned
the foundation of the people called Quakers.
Which argument of yours is:

That since,
(as you judge) the being and substance of the Christian
religion consists in the knowledge of,
and faith concerning, the birth, life, death, resurrection,
and ascension of Christ Jesus,
you consider the substance of the Christian religion to be a contingent truth;
which contingent truth is a matter of fact.
From which you reason that:

"`Matters of fact cannot be known except by the relation of another person,
or by the perception of the outward senses;
because there are naturally in our souls no ideas of contingent truths,
such as there are concerning necessary truths, such as, that God is,
or that the whole is greater than the part.
And since it might without absurdity be said that God cannot
make a contingent truth to become a necessary truth;
neither can contingent truths or matters of fact
be revealed except trough the outward senses,
so men are not obliged to believe that God produces
any revelation in the soul concerning matter of fact,
unless He also add some miracles that are obvious to the outward senses,
by which the soul may ascertain that the revelation undoubtedly comes from God.`"

All this you endeavor also to prove from the Scripture, Romans 10,
where the apostle says,
"`Faith comes by hearing;`" and because the apostle speaks
afterwards of those who were sent in the plural number,
from here you conclude that what is spoken of is
outward preaching by the ministry of men.
And since the apostle uses a question, saying,
"`How shall they believe unless they hear,`" you
gather from the induction and connection of the text,
that the apostle speaks only of outward hearing;
and from there conclude that without outward hearing, faith cannot be produced.
Therefore you say that there can be no immediate revelation
by the simple operation of the Spirit of God in the mind,
unless there be something also proposed to the outward senses.

Before I proceed to a direct answer to this argument,
some things are necessary to be premised:

First then:
That it is falsely supposed that the essence of the Christian religion
consists in the historical faith and knowledge of the birth,
death, life, resurrection, and ascension of Jesus Christ.
This faith and historical knowledge is indeed a part of the Christian religion,
but not such an essential part as that without it the Christian religion cannot exist.
But it is an integral part, which goes to the completing of the Christian religion,
even as the hands or feet of a man are integral parts of a man,
without which nevertheless a man may exist, but not an entire and complete man.

Secondly:
If by immediate revelation you understand such a revelation of God as begets
in our souls a historical faith and knowledge of the birth of Christ in the flesh,
without the means of the holy Scripture,
we do not contend for such a revelation as something that is commonly given,
or something to be expected by us, or any other Christians.
For albeit many other evangelical truths be manifested
to us by the immediate manifestation of God,
not using the Scripture as the means;
yet the historical knowledge of Christ is not commonly manifested to us,
nor to any others, except by the holy Scripture as the means,
and that by way of a material object.

Thirdly: Nevertheless we do firmly assert, that God can most easily, clearly,
and certainly, manifest to our minds the historical truths of Christ`'s birth,
etc. whensoever it pleases Him, even without the Scripture, or any other outward means.
And because your argument seems to be formed against the possibility of such a revelation,
therefore I shall proceed to discuss it; but first you may notice,
that the prophets who foretold Christ`'s coming in the flesh,
and His being born of a virgin, and afterwards put to death, etc.,
did know these matters of fact by the inward inspiration of God,
without any outward means:
for the proof of which see 1 Peter 1:10-11. Now that which has been may still be.

Fourthly:
This argument of yours does at most conclude that
we cannot naturally know any matter of fact,
except by the relation of another without us, or by the perception of the outward senses;
because there are naturally in our minds no ideas concerning contingent truths
(and every matter of fact is a contingent truth) as there are of necessary truths.
This then proves that we cannot naturally know any
contingent truth except by the relation of another,
or the perception of the outward senses;
but this hinders not the truth that we may know a
contingent truth by a supernatural knowledge,
wherein God supplies the place of an outward relator; who indeed is so true,
that He ought to be believed, since God is the fountain of truth.

Fifthly:
When God does make known unto men any matter of fact by divine immediate revelation
or inspiration--God speaking as to the ear of the heart of the inward man,
or as by his finger writing therein--two things are to be
considered in such an immediate revelation.

1+++.+++ To Materiale, The matter of fact or thing revealed, which is contingent.

2+++.+++ To Formale, The form or mode, how the revelation is made: which form is an inward,
divine, and supernatural revelation,
which is the voice or speech of God inwardly speaking
to the ear of the inward man or mind of man,
or a divine writing supernaturally imprinted therein.

Now as to the material part, or the thing and matter revealed,
this is indeed a contingent truth, and of itself it is not manifest to the mind;
but because of the form, that is,
because of the divine mode and supernatural inward operation,
the matter is known to be true.
For that divine and supernatural inward operation
which the mind does feel and perceive in itself,
is the voice of God speaking unto man,
which by its nature and specific property is as clearly
distinguished and understood to be the voice of God,
as the voice of Peter or James is known to be the voice of such men.
For every being as a being is knowable,
and that by its own specific nature or property proceeding from its nature;
and this has its proper idea, by which it is distinguishable from every other thing,
if so be its idea be stirred up in us, and clearly proposed to us.

Sixthly: Now as some beings are natural and some supernatural,
so some ideas are natural and some supernatural.
And as when any natural idea is excited in us, we clearly know it;
so also when a supernatural idea is raised in us,
we clearly know the thing whereof it is the idea.
But the voice of God speaking to the mind of man is a supernatural being,
and stirs up in us a supernatural idea,
by which we clearly know that inward voice to be the voice of God,
and not the voice or operation of another, or of any evil spirit, or angel,
because none of these have a supernatural idea as His divine operation has.
For the voice of God is full of vigor, virtue, and divine glory, as the psalmist says,
who had often experienced it; and we also in our measures are witnesses thereof,
for the voice of God is known to be His by its divine virtue.

Seventhly: The senses are either outward or inward;
and the inward senses are either natural or supernatural.
We have an example of the inward natural sense in being angered or pacified,
in love and hatred, or when we perceive and discern any natural truth.
But an example of an inward supernatural sense is,
when the heart or soul of a pious man feels in itself divine motions, influences,
and operations, which sometimes are as the voice or speech of God,
sometimes as a most pleasant and glorious illustration
or visible object to the inward eye,
sometimes as a most sweet savor or taste, sometimes as a heavenly and divine warmness,
or, so to speak, a melting of the soul in the love of God.
Moreover, this divine and supernatural operation in the mind of man,
is a true and most glorious miracle;
which when it is perceived by the inward and supernatural
sense divinely raised up in the mind of man,
does so evidently and clearly persuade the understanding to assent to the thing revealed,
that there is no need of an outward miracle;
for this assent is not because of the thing itself revealed,
but because of the revelation proposing it, which is the mighty voice of God.
For when the voice of God is heard in the soul,
the soul does as certainly perceive the truth of that voice,
as the truth of God`'s being, from whom it proceeds.

These things being thus premised, I now proceed to a direct answer.
As for what you have said,
that God cannot make a contingent truth to become a necessary truth, I agree.
However, when any contingent truth is manifest to us by the immediate revelation of God,
there is in this two things to be considered; namely,
the thing revealed (which is contingent), and the revelation itself.
And upon the supposition that it is indeed a divine revelation,
then it is no contingent truth, but a most necessary truth.
For all mankind will agree that this proposition,
"`every divine revelation is necessarily true,`" is as clear and evident
as the proposition that "`every whole is greater than its part.`"

But you will say, how do you know that a divine revelation is a divine revelation?
I answer, how do you know that a whole is a whole, and that a part is a part?
You will say, by the natural idea that is excited in me of a whole, and of a part.
I answer again;
even so a divine revelation is known to be such by a supernatural idea of divine
revelation stirred up in us by a divine motion or supernatural operation.
But it is no wonder that men who have no experience of supernatural ideas,
or at least do not heed them, do deny them.
This is as if a man naturally blind denied the existence of light or colors,
or a deaf man denied sounds, only because they the did not experience them.
Therefore, we cannot conceal that we feel a fervent zeal, even divinely kindled in us,
against such an absurd opinion as affirms that God cannot
make known to us His will in any contingent truth,
except by proposing it to the outward senses.
This opinion does in a manner turn men into mere brutes,
as if man were not to believe his God,
unless He propose what is to be believed to the outward senses,
which senses the beasts have in common with us.
Indeed, it derogates from God`'s power, and imputes weakness to Him,
as if He could not do that which not only both good and evil angels can do,
but which the lowest creatures can do, and the most insensible.
As for instance, the heat of the fire, the coldness of the air and water works upon us;
yes, if a pin prick us, we certainly feel it, and that by the outward senses,
because these objects are outward and carnal.
But since God is a most pure and glorious Spirit,
when He operates in the innermost parts of our minds by His will;
shall He and His will not be clearly felt according to His nature, that is,
by a spiritual and supernatural sense?
For as the nature of God is, so is the nature of His will, that is, purely spiritual,
and therefore requires a spiritual sense to discern it.
And this spiritual sense, when it is raised up in us by a divine operation,
does as clearly and certainly know the voice or revelation of the
will of God concerning anything which God is pleased to reveal,
however contingent, as the outward senses know and perceive the outward object.

And it is no less absurd to require of God, who is a most pure Spirit,
to manifest His will to men by the outward senses,
as it is to require a man to see sounds, and to hear lights and colors.
For as the objects of the outward senses are not to be confused,
but every object is to have its proper sense;
so we must judge the same of inward and spiritual objects,
which also have their proper sense whereby they are to be perceived.
And tell me,
how does God manifest His will concerning matters
of fact when He sends His angels to men,
since angels (as is commonly received) have no outward senses,
or at least not so gross ones as ours are?
Yes, when men die, and appear before the tribunal of God,
whether unto eternal life or death, how can they know this,
having laid down their bodies together with their outward senses?
And nevertheless this truth of God is a truth of fact,
as is the historical truth of Christ`'s birth in the flesh.

Or to bring it yet further,
how do good and holy men even in this life most certainly
know that they are in the favor and grace of God?
No outward revelation makes this known unto them.
But the Spirit, as says the apostle,
bears witness with our spirits that we are the children of God.
For the mere testimony of a human conscience,
without the inward testimony of the Holy Spirit,
cannot beget in us a firm and immoveable testimony of our sonship,
because the heart of man is deceitful.
And even if the testimony of a mere human conscience were true,
it is still at most but a human testimony, which begets in us only a human faith.
But that faith, by which holy men believe they are the sons of God, is a divine faith,
which leans upon a divine testimony of the Holy Spirit
witnessing in them that they are the sons of God.
Moreover, when a good man feels in himself that undeclarable joy of the Holy Spirit,
concerning which the holy Scripture speaks,
and which is the common privilege of the saints, how or from where does he feel this joy?
Truly, your position argues no less against this heavenly spiritual joy,
which is begotten in the souls of the saints by the Holy Spirit,
than it does against the immediate revelation of God.
For there is no natural idea of this spiritual joy, or else mere natural men, yes,
even such as are profane and ungodly, would feel it as much as the godly.
But because it is a supernatural thing,
therefore it can have no true idea formed but what is supernatural.
Moreover,
how is it that profane men sometimes feel in themselves the wrath of God as a fire,
when all things, as to the outward, go on as prosperously with them as with the godly,
and oftentimes more prosperously?
For there is no natural idea in men of this inward wrath of God.
There is also an inward grief oftentimes raised up
in wicked men from the sense of God`'s wrath,
which very much vexes and torments their minds;
and nevertheless this grief has no natural idea in us.
For oftentimes wicked men do not feel this sorrow, and God is, as it were, silent,
while the wicked continue in sin, as in Psalm 1.

All of which most clearly demonstrates,
that there are in men supernatural ideas of supernatural things;
which ideas are nevertheless not perceived by us unless
they are stirred up by some supernatural operation of God,
which raises up in us supernatural and spiritual senses, which, by their nature,
are as distinguishable from the natural senses (whether inward or outward) as
the natural senses are distinguished one from another by their specific differences.
Scripture speaks frequently of these spiritual senses, as in Hebrews 5:14,
where spiritual senses are spoken of in general,
by which the spiritual man has the "`discerning of good and evil.`"
Now the "`good`" mentioned here is of a spiritual nature,
and conduces to feed in us a spiritual and divine life;
and the "`evil`" is that by which the spiritual life is in us hurt; that is to say, sins,
whether carnal or spiritual;
all of which cannot be discerned except by such as
have spiritual senses stirred up in them,
as the apostle says.
In other places the Scriptures also speak of these spiritual senses in particular;
as of the spiritual seeing and tasting. Psalm 34:8.
Of the spiritual hearing, Psalm 85:8. Of spiritual smelling,
Song of Solomon 1:3. Of spiritual touching, 1 Sam.
10:26,
and in many other places of Scripture we read of those spiritual senses in particular.
Yes, it is the promise of the gospel,
that the glory of God shall be "`seen`" by holy men, such as are clean of heart,
even in this life: Isaiah 33:17. Mat.
5:8; which promises were fulfilled in the primitive Christians, see John 1:14. 1 John 1:
2-4. 2 Cor.
3:18,
and chapter 4:6. But what is this vision of God and divine
glory which the souls of the saints enjoy in this life?
Is it not the earnest or first-fruits of that more
abundant glorious vision in the life to come,
concerning which the Scripture so much declares,
which is the highest happiness of the immortal soul?

Therefore, if there be such a thing as supernatural ideas, then there are also senses,
or perceptive faculties by which those ideas are perceived;
for these two are related to each other, and suppose and infer one another.
But in wicked men these senses or faculties do, as it were, sleep,
just as with the vision faculty of a blind man; but in the godly they are stirred up.
Now by these divine and spiritual senses,
which are distinct and distinguishable from all the natural faculties
of the soul (whether of imagination or natural reason),
spiritually minded men do behold the glory and beauty of God, in respect whereof,
and compared to which, all the glory of this world is despicable to them; yes,
even as dross and dung.
And they also hear God inwardly speaking in their souls, words truly divine and heavenly,
full of virtue and divine life; and they savor and taste of divine things, and do,
as it were, handle them with the hands of their souls.
And these heavenly enjoyments do as really differ in their nature
from all false similitudes and fictitious appearances of them (which
either the mind of man by its own strength can imitate,
or any evil spirit to deceive man can counterfeit)
as a true man differs from the dead image of a man;
or true bread, honey, wine, or milk, differs from the mere picture of those things.
And albeit either the imagination of man, or subtlety of the devil,
may counterfeit false likenesses of these enjoyments by
which men may be deceived (and no doubt many are deceived),
yet this does not hinder the fact that these divine enjoyments are clearly
perceived by those in whom the divine and spiritual senses are truly opened,
and the true supernatural ideas of those things are truly raised up.

And if there be at any time a mistake,
then the divine illumination is not the cause of that mistake,
but rather some evil disposition of the mind;
as also happens in those things relating to natural reason.
For there are many false appearances of reason, which differ as much from true reason,
as those false and pretended revelations and diabolical
inspirations differ from such as are truly divine.
Now, though there are many men who would be esteemed philosophers,
yet who are miserably deceived by those false likenesses of reason,
judging their false reasons to be the true similitudes of things and solid logic;
yet this nevertheless moves any man of sound reason to reject
sound and solid reason as doubtful and uncertain.
For even sound natural reason is an excellent gift of God, and very useful to mankind,
when used in its proper place.
But let none think to comprehend by their natural reason
things that are of a divine and supernatural kind.

But to proceed: If we will hear the Scriptures (as all Christians should),
they testify to us that God has declared His mind and will,
even concerning contingent truths to come, in the prophets;
as the first chapter to the Hebrews does evidently declare: "`God,
who at sundry times and in various manners spoke to our fathers in the prophets.`"
Yes, let us hear the prophets themselves; Hosea chapter 1 says plainly,
that "`the word of the Lord was made in him,`" as it appears in the Hebrew.
Habakuk also says, that he was "`standing on his watch,
to see what Jehovah would speak in him.`"^
footnote:[Habakkuk 2:1 literal translation]
And it is so clearly manifest that the most heavenly revelations are by
inward illustrations and inspirations in the very minds of the prophets,
that it is strange how any who believe in the Scripture should doubt of it.
And it is also certain that, even when they foretold contingent truths to come,
they were most certainly persuaded that they were divinely inspired,
even without the corroboration of any outward miracle.
For John the Baptist did no miracle;
and many others prophesied where no miracle appeared,
as in Scripture may be often observed.
And we also,
by the inspiration of the same Divine Spirit by which the prophets prophesied,
do believe their words and writings to be divine,
concerning both contingent truths that are past and those that are yet to come.
And indeed, we need no outward miracles to move us to believe the Scriptures;
and therefore much less were miracles necessary to the prophets who wrote them.
For we see in many places of the prophets where they
declare prophesies revealed to them of God,
that there is not a word mentioned of any outward miracle
as that by which they were certain of it.

Moreover, the falseness of your argument does appear,
in that the Scripture does declare many contingent
truths to have been revealed to the prophets in dreams.
Now even as natural and wicked men do not see what
they dream by a real perception of the outward senses,
but rather by inward ideas which are presented to the mind and perceived by it,
so it is also in divine revelations of this nature.
Of this we have a clear example in Joseph, the husband of the blessed Virgin, who,
when he observed his wife with child,
was told in a dream that she had conceived by the Holy Spirit.
Now I would have you tell me, to which of Joseph`'s outward senses was this revealed?
Or what miracle did he have to induce him to believe that which,
being against the order of nature, did certainly clash with his reason?
The Scripture mentions no miracle in this matter;
and yet no doubt Joseph would have sinned had he disbelieved this
revelation and rejected his wife as an adulteress.

Now as to these words of the apostle in Romans 10,
that "`faith comes by hearing;`" Zwingli observed well that the apostle
intended not to affirm faith to come by the hearing of the outward word;
neither do the following words prove it, "`How shall they believe, unless they hear?
And how shall they hear without a preacher?
And how shall they preach, unless they be sent?`"
For the apostle uses these questions, not as his arguments,
but rather as objections which might be formed,
as he does in many other places;
which objections he also answers in the same chapter, as appears verse 18.
"`But I say, have not they all heard?
Yes, truly their voice went into all the earth;`" that is,
the voice of the Father and Son, or of the Father in the Word;
which Word is not only near us, but according to the same apostle in the same chapter,
is "`in our mouths, and in our hearts.`"
But further, to insist that faith is begotten by outward hearing only, and not otherwise,
would be to suggest that nothing can be certainly believed,
except where something is proposed to the outward hearing,
which indeed destroys your whole hypothesis.
For you have before affirmed that outward miracles are sufficient
to render one certain of the truth of any revelation;
whether it be the healing of the sick, or the raising of the dead, etc.
But now these miracles would avail nothing,
because they (and nearly all miracles) are obvious to the sight, and not to the hearing.

But lastly: If all the certainty of our faith, hope, and salvation,
did depend upon the infallibility of outward senses, then we would be most miserable,
since it is well known that these senses can be easily deceived,
as well as weakened or impaired by many outward causes and natural infirmities.
And there are (as the Scriptures affirm) also false miracles, which, as to the outward,
cannot be distinguished from the true;
of which we cannot infallibly judge by the outward senses,
which only discern what is outward.
There is a necessity, therefore, to have recourse to some other means of certainty.

From all which which it does appear, how fallacious and weak this argument is.
But thanks be unto God,
who would not have our faith be built upon so uncertain and doubtful a foundation.
And whoever has known true faith,
or has felt the divine testimony of God`'s Spirit in his soul, will judge otherwise;
neither will he be moved by such reasonings.
I pray God therefore to remove these clouds which darken your understanding,
that you may perceive the glorious gospel of Christ;
which is that saving Word of grace which I commend you unto.
And that God may give you a heart inclinable to believe and obey the truth,
is the desire of your faithful friend,

Robert Barclay From the prison of Aberdeen, in Scotland,
where I am confined for the sake of the testimony of Jesus.
November 24,1676.
