== Chapter XX

[.section-date]
1677--1684

The year 1677 had scarce begun, when G. Fox began to travel again,
though the roads were yet covered with snow.
After he had passed many places, and preached in the meetings of his friends,
he came to York, and going from there to Nottingham,
he went to the house of John Reckless,
who was sheriff there when G. Fox preached the first time in that town,
and was imprisoned on that account.
But this sheriff, taking G. Fox into his house at that time,
had been so reached by what he spoke, that he embraced the doctrine held forth,
and never departed from the profession thereof.
From here G. Fox passed through Leicestershire, Derbyshire, Warwickshire,
Buckinghamshire, and Bedfordshire, where he met with William Dewsbury,
and so came again to London.
Having attended the annual meeting there, he, with William Penn, Robert Barclay,
George Keith, and some others, went over to Holland to see his friends there,
and to edify them with his gift.
William Penn and Robert Barclay travelled up into Germany,
and since R. Barclay the year before had spoken with the
princess Elizabeth of the Palatinate (the daughter of Frederick,
king of Bohemia, and sister of Sophia, late duchess of Hanover, mother of George,
king of Great Britain), William Penn had also written two letters to her from England,
which she answered by this following:

Hereford, May 2, 1667.

This, friend, will tell you that both your letters were very acceptable,
together with your wishes for my obtaining those virtues which may make
me a worthy follower of our great King and Savior Jesus Christ.
What I have done for His true disciples is not so much as a cup of cold water;
for it affords them no refreshment;
neither did I expect any fruit from my letter to the duchess of L. as I expressed
at the same time unto B. F. But since Robert Barclay desired I should write it,
I could not refuse him, nor omit to do anything that was judged conducive to his liberty,
though it should expose me to the derision of the world.
But this a mere moral man can reach; the true inward graces are yet lacking in,

Your affectionate friend,

Elizabeth

G+++.+++ Fox also from Amsterdam wrote a letter to this virtuous princess,
wherein he commended her modest and retired life,
and exhorted her to piety and godliness; to which she answered with this letter:

Dear Friend,

I cannot but have a tender love to those that love the Lord Jesus Christ,
and to whom it is given not only to believe in Him, but also to suffer for Him.
Therefore your letter, and your friends`' visit, have both been very welcome to me.
I shall follow their and your counsel, as far as God will afford me light and unction;
remaining still

Your loving friend,

Elizabeth Herford, the 30th of August, 1677.

This correspondence gave occasion to William Penn
and Robert Barclay to pass towards Herford,
a town on the frontiers of Paderborn, and to give the said princess, who resided there,
a visit.
With her lived Ann Maria, countess of Homes; and in one of the chambers of the princess,
William Penn and Robert Barclay had a meeting with the princess, the countess,
and several others, to their great satisfaction.
The countess, who was one of Labadie`'s adherents,
signified to William Penn that she wished a meeting might
be held where the inferior servants might freely attend.
William Penn not refusing this, the princess consented to it;
and after the meeting (where she was not present,
that so her servants might have a more free access),
she expressed much satisfaction in having had that good opportunity,
and then so earnestly invited William Penn and Robert
Barclay (who lodged at an inn) to sup with her,
that they not being well able to refuse the invitation, yielded to it.

There was then with her a French woman of quality,
who having had before a very slight opinion of the Quakers, now became deeply broken,
and very affectionately kind and respectful to William Penn and Robert Barclay.
The next day was the first of the week;
and it being agreed with the princess to have another meeting,
William Penn desired that not only as many of her own family,
but as many of the town as would willingly be there, might be admitted.
To this she yielded,
and thus William Penn and Robert Barclay had a large opportunity to preach effectually,
and to discharge themselves.
After the meeting was done, the princess came to William Penn,
and taking him by the hand,
she spoke to him of the sense she had of the power
and presence of God that had been among them.
And thus going on she broke forth into an extraordinary passion, crying out,
"`I cannot speak to you, my heart is full,`" clapping her hand upon her breast.
This affected William Penn not a little,
yet he spoke a few words to her by way of admonition; and then taking his leave of her,
she said, "`Will you not come here again?
Please stop here as you return out of Germany.`"
To this he returned, "`We are in the hand of the Lord, and being at His pleasure,
cannot so fully dispose of ourselves.`"
A solemn leave then being taken, Robert Barclay returned to Amsterdam,
and William Penn went to Paderborn, and so by the way of Cassel,
(where he spoke with the aged and learned Dureus) to Frankfort.
Here he found various persons of note, with whom he had several meetings,
and one at the house of a young gentlewoman of noble birth,
called Johannah Eleonora Merlane, who said to him, "`Our quarters are free for you.
Let all come that will come; and lift up your voices without fear.`"

Departing from there, William Penn came to Chrisheim, a village near Worms,
where then lived some of his friends who afterwards
went to Pennsylvania and settled themselves there.
While William Penn was in the Palatinate, he wrote an epistle of exhortation^
footnote:[See Penn`'s Travels in Holland, etc. 3rd impression, p. 77.]
to Elizabeth princess Palatine, and Anna Maria countess of Homes.
He then went to Heidelberg, the chief city of the Palatinate,
to speak with the prince Elector, Charles Ludowick,
brother of the said princess Elizabeth,
but the said prince happened then to be out of town.
And since W. Penn`'s chief message was to request the prince
that the Quakers at Chrisheim might be treated more mildly,
he took occasion from there to write a letter to him;^
footnote:[Ibid. p. 84.]
for not only were tithes being exacted from his friends there by the parson of the village,
but also by the Papist priests of Worms;
and the mayor of the town had endeavored to restrain
their due liberty of religiously meeting together.
Returning afterwards to Chrisheim, and preaching there in a meeting of his friends,
he was overheard by the mayor, who stood at the back-door that he might not be seen.
But this man was so well pleased with what he heard, that he afterwards told the parson,
that though it was his work to discover if the Quakers were heretics,
"`for my part,`" he said, "`I heard nothing but what was good,
and therefore I will not meddle with them.`"
For the parson had busied himself to persuade the
mayor that it was his duty to suppress heresy;
but he here made it known that he had no mind to persecute any for religion`'s-sake.
W+++.+++ Penn having now cleared his conscience, returned by way of Frankfort, Cologne, Cleves,
etc. to Amsterdam, where at Cologne he received a letter from the princess Elizabeth,
in answer to that which he had written to her from the Palatinate.
The said letter was as follows:

September, 1677.

Dear Friend,

I have received your greetings, good wishes, and exhortations, with much joy,
and shall follow the latter as far as it will please
our great God to give me light and strength.
I can say little for myself, and can do nothing of myself;
but I hope the Lord will conduct me in His time, by His way, to His end,
and that I shall not shrink before His fire.
I do long for it; and when He assures my ways,
I hope He will give me power to bear the cross I meet therein.
I am also glad to hear the journey has been prosperous
both in the constitutions of your bodies,
to withstand the badness of the weather, and in the reception you had in Cassel,
Frankfort, and Chrisheim.
Nothing surprised me there but the good old Dury,
in whom I did not expect so much ingenuousness, having lately wrote a book, entitled,
Le veritable Chretien that does speak in another way.
I wish to know what reception you have had at Fredericksburg,
and if this find you at Cleves,
I wish you might take an occasion to see the two pastors of Mulheim,
who do really seek the Lord, but have some prejudice against your doctrine,
as also the countess there.
It would be of much use for my family to have them freed from their misconceptions;
yet God`'s will be done in that, and all things else concerning

Your loving friend in the Lord Jesus,

Elizabeth

While William Penn made this journey into Germany,
George Fox had gone to Hamburg and Frederickstadt, to visit his friends there.
Penn having returned to Amsterdam, went from there to Friesland,
and met George Fox as he was coming back to Holland, at Leewarden;
from which he made a step to Wiewart, where a society of the Labadites dwelt.
Here he spoke with the famous Anna Maria Schurman, the gentlewomen Somerdykes,
the French pastor Peter Yvon, and others.
After some discourse from both sides,
when Yvon had given a relation concerning John de Labadie,
how he was bred among the Jesuits, and had deserted them,
and embraced the Protestant religion,
and how becoming dissatisfied with the formal Protestants,
he with some that adhered to him, had separated themselves from the common assemblies,
Anna Maria Schurman began to speak, and gave an account of her former life,
of her pleasure in learning, and her love to the religion she was brought up in,
but confessed she knew not God or Christ truly all that while.
And though from a child God had visited her at times,
yet she never felt such a powerful stroke, as she did by the ministry of John de Labadie.
Only then did she see her learning to be vanity, and her religion like a body of death;
and therefore resolved to despise the shame,
desert her former way of living and acquaintance,
and to join herself with this little family that was retired out of the world.
This and much more she spoke in a sensible frame, and with a serious mind,
not without some trembling.
And then one of the Somerdykes gave also an ample relation, concerning her inward state,
and how she had been reached by the preaching of Labadie;
and how before that time she had mourned because of the
deadness and formality of the common Christians,
and said within herself, "`O the pride, the lusts,
the vain pleasures in which Christians live!
Can this be the way to heaven?
Is this the way to glory?
Are these followers of Christ?
O no!
O God where is Your little flock?
Where is Your little family that will live entirely to You, that will follow You?
Make me one of that number.`"
Then she told how, being pricked to the heart when she heard Labadie preach,
she had resolved to abandon the glory and pride of this world; and further said,
that she counted herself happy to have joined with this separated family.

After some others had likewise given an account of their change,
William Penn also gave a circumstantial relation how he had been
gradually drawn off from the vanity and pride of life;
mentioning the adversities he had met with in the university at Oxford
because of his not joining with the debauchery committed there;
and how, after having lived some time in France,
he had been convinced by the effectual ministry of Thomas Loe,
and so came to be joined with the despised Quakers.
This relation he concluded with a serious admonition how they ought to go on,
and to grow in the true fear of God.
At parting, one of the pastors asked him if the truth did not arise first amongst a poor,
illiterate, and simple sort of people.
"`Yes,`" answered William Penn;
"`and it is our comfort that we owe it not to the learning of this world.`"
To which the pastor replied,
"`Then let not the learning of this world be used to defend
that which the Spirit of God has brought forth;
for scholars now coming among you,
will be apt to mix school learning amongst your simpler and purer language,
and thereby obscure the brightness of your testimony.`"
W+++.+++ Penn, having answered something to the purpose, took his leave,
and travelled by way of Groninghen to Embden,
where the Quakers at that time were persecuted severely with imprisonments and banishments.
But I will withhold the relation thereof,
because it has long ago been published in print, and the magistrates there,
being afterwards moved to pity by the persecution the protestants suffered in France,
came to a better resolution, as may be mentioned in what follows.

When W. Penn came to Embden, he went to speak with the burgomaster Andre at his house,
and asked him if he and the senate had not received a letter
in Latin from an Englishman about two years since,
concerning their severity towards the people called Quakers?
The burgomaster said he had.
W+++.+++ Penn then replied, "`I am that man,
and am constrained in conscience to visit you on their behalf.`"
The burgomaster deported himself with more kindness than was expected,
and gave some faint hope of a change;
but it appeared sufficiently that the senate was not as yet so disposed,
for persecution continued there yet a long while.

A copy of W. Penn`'s letter, being translated into English, runs thus,
and deserves the serious consideration of all magistrates.

To the Council and Senate of the City of Embden.

May the King of kings, and Lord of lords, who is God of all the families of the earth,
incline your hearts to justice, mercy, and truth.

The noise of your severe treatment of several persons that are inhabitants of your state,
reproachfully termed Quakers, has reached these parts,
and filled several with compassion and surprise:
compassion to hear of the miseries of innocent and upright men,
against whom you have nothing to object besides the
pure exercise of their conscience to God;
surprise, that you, a Protestant state, should employ your civil power to deter, punish,
and grievously afflict men for following the convictions of their consciences,
and acting according to the best of their understanding.

Protestants got their name by protesting against imposition;
and now will you turn imposers?
They condemned it; and will you practice it?
They thought it a mark peculiar to the beast;
and can you now regard it the as the duty of a Christian magistracy?
I mean, that persons must not live under your government,
unless they receive your mark in the forehead or right hand?
Which, in plainer terms, is to submit their consciences to your edicts,
and to ask your permission what religion they should follow.
Remember that faith is the gift of God; and that what is not of faith is sin.
Nothing can be more unreasonable than to compel men to believe against their beliefs,
or to trouble them for practicing what they believe
when it opposes not the moral law of God.

You doubtless take yourselves to be Christians,
and would esteem it no little insult to be otherwise represented;
yet what is more unchristian than to use external force to sway
the consciences of men about the exercise of religious worship?
Christ Jesus, the Lord and author of the Christian religion,
censured His own disciples that would have called fire from heaven to
destroy those that would not conform to what their blessed Master taught.
Are you more sure of your religion?
Are you better Christians?
Or have you more Christian authority than those who
were chosen to be the witnesses of Jesus?
However, remember, they called for fire from heaven;
but you seek to kindle fire on earth to devour them--they who are of your own people,
and merely for their religious dissent from you.

I am well persuaded, that those you inflicted such severe penalties upon,
mean well in what they believe,
and that the reason of their present distance from
you is not to introduce dangerous or strange opinions,
but to live a life of more holiness, purity, and self-denial, than before.
They do not think that you walk in accordance with your own principles,
and they have reason to believe that the power of godliness is much lost among you.
And having long lain under a sense of decay and languishing
of soul for lack of true spiritual nourishment,
they have now resorted to that heavenly gift and
grace of God in themselves for divine satisfaction,
even that holy anointing that is able to teach them all things
necessary for them to know (as the blessed apostle speaks);
and indeed, they find the joys of the Holy Spirit in so doing.
And I am persuaded that they are not less peaceable, sober, just,
and neighborly than before,
and that they remain altogether as consistent with the prosperity of civil society.

If you were able to give faith,
it would be more excusable for you to punish those who resist.
But since that is impossible, then the other is unreasonable;
for it is to afflict men for not being what they cannot be unless they turn hypocrites.
This is the highest point that your coercive power can arrive at;
for surely it never did convert or preserve one soul to God.
Instead thereof it offers violence to conscience,
and puts a man either upon the denial of his faith and reason,
or being destroyed for acting according to them.
And what do your prisons, fines, and banishments accomplish in the mind of any man?
Surely they inform no man`'s judgment, resolve no doubts, convince no understanding.
The power of persuasion is not to be found in any such barbarous actions;
for such a course only destroys the bodies and estates of men,
instead of saving their souls.
If they are in the wrong, it would be better for you to use God`'s weapons,
the sword of His Spirit, which saves the creature, and slays the evil in him.

I beseech you for the sake of the Lord Jesus Christ,
that you would have a care how you exercise power over men`'s consciences.
My friends, conscience is God`'s throne in man, and the power of it is His prerogative.
To set lords over it, is to usurp His authority, and to boldly ascend His throne.
If their conduct was scandalous and destructive to the good of your state,
then you would be held excusable; but verily,
no man of mercy and conscience can defend your practice upon men so peaceable and harmless.
Gamaliel will rise up in judgment against you, if you persevere in your course.
In much love I entreat you, as is fitting for Christian men and true Protestants,
that you leave men to their particular persuasions
in affairs relative to the other world,
so long as these have no ill effects on the affairs of this.
But vice has an evil consequence with respect to both worlds; therefore punish vice,
and aspire to truth and righteousness.
Use not your civil power to torment religious dissenters, but to pursue a good life,
which is lamentably lost amidst the great pretenses that are made to religion.
Doubtless magistracy was both ordained of God, and elected by men,
to be a terror of evil-doers, and not to them that do well,
though they be of different judgments.

Remember that these are men just like yourselves, born free,
and have an equal plea to natural and civil common privileges with yourselves.
The different persuasion of their consciences about things relating
to another life life can in no way render them unfit for this.
They have the same right to their liberty and property as ever,
having by no practice of theirs in the least forfeited any of those human
advantages which nature and Scripture have conferred upon them.
If they are in the wrong, it is more than they know.
Will you persecute men for being what they must be, if they will be true to themselves?
I beseech you, seek some cheaper way to accommodate yourselves than by their destruction,
for they are very far from seeking yours.
Oh, the day will come wherein one act of tenderness about matters
of conscience shall find a better reward than all the severity
men use to propagate their own persuasions in the world.
And indeed, there is great reason for this, for the one flows from the Savior,
the other from the destroyer of men.
In fine, let your moderation be known unto all men, for the Lord is at hand,
whose reward is with Him; and He will recompense every man, family, state, kingdom,
and empire, according to the nature of their works committed in His mortal body.

Imitate the God of nature and grace by being gracious to all.
His sun shines on all; His rain falls on all, He gives life and being to all;
His grace visits all, and in times of ignorance he winks.^
footnote:[Acts 17:30]
And though you may repute us as ignorant, I hope you cannot think that you wink at it,
seeing you make such great manifestations of your displeasure.
Oh, how forbearing and merciful is God towards you?
Have you so lately escaped the wrath of your enemies,
and can you already thus harshly treat your friends?
Let His goodness to you prevail with you, to express clemency to others,
so that the great God of the whole earth--even the God of
the spirits of all flesh who is no respecter of rich,
poor, or powerful in judgment--may show you mercy in the day of His righteous judgments.
Amen.

Your friend in the universal seed of love and truth,

W+++.+++ Penn.
London, December 14, 1674.

After W. Penn had stayed some time at Embden,
he took a turn again to Herford where he was received
very kindly by the princess Elizabeth and the countess of Homes.
More than once he had a meeting in her chamber,
where the princess was so reached and affected by his speaking that she said,
"`I am fully convinced; but oh my sins are great!`"
This gave occasion to W. Penn to speak to the princess and the countess apart,
with respect to their particular conditions, which made a deep impression on their minds,
especially the countess`'s. Being much pressed by the princess to stay and sup with her,
he yielded; and the countess from a serious sense of her compliance with the world,
told him, "`Il faut que je rompe, il faut que je rompe,`" i. e. "`I must break off,
I must break off!`"
And at another time with a weighty countenance she cried out,
"`O the encumber and entanglements of this vain world; they hinder all good.`"
Once the princess said to them, "`It is a hard matter to be faithful to what one knows.
I fear that I am not weighty enough in my spirit.`"
At another time she told him,
"`Among my books I have records that the gospel was
by the English first brought from England into Germany;
and now it has come again.`"
Thus this excellent princess signified how highly she valued
the preaching of the gospel to her by W. Penn,
and how much she esteemed his labor and ministry.
When he took his leave of these eminent persons, having taken the princess by the hand,
which she received with a weighty kindness, being much broken in spirit,
he wished the blessing and peace of Jesus with and upon her;
and then exhorting the countess, she frequently besought him to remember her,
and implore the Lord on her behalf.

Next taking a wagon to Wesel, from there he travelled to Duisburgh, Dusseldorp,
and Cologne, and then back again to Dusseldorp,
to see if he could get an opportunity at Mulheim to speak with the countess of Falkenstein,
who was reported to be a very religious person.
In his former journey he had endeavored to visit her, but in vain;
for the count of Bruch and Falkenstein, her father,
kept her as it were under confinement, because she was of a religious temper;
and therefore he called her a Quaker,
though she did not at all converse with any of the Quakers.
He had also treated W. Penn very roughly, when, being necessitated to pass by his castle,
he being lord of that country,
asked him and his friends from where they came and where they went?
To this they answered, that they were Englishmen come from Holland,
and going no further in those parts than his town Mulheim.
But not pulling off their hats, the count called them Quakers, and said,
"`We have no need of Quakers here.
Get out of my dominions; you shall not go to my town.`"
And he commanded some of his soldiers to see them out of his territory.
Thus W. Penn, and those with him, were made to lie that night in the open air.
But the next day he wrote a letter to the said count, and therein told him,
"`For your saying, '`we need no Quakers here,`' I say, you most certainly do.
For a true Quaker is one who trembles at the word of the Lord,
and who works out his salvation with fear and trembling.`"

W+++.+++ Penn having come to Mulheim,
could no more find opportunity to speak with the
countess than the first time he was in those parts;
and therefore he went on to Duisburgh, Wesel, and Cleves,
where having had conferences with some religious people,
he returned by way of Utrecht to Amsterdam, where G. Fox had also come back again.

Here W. Penn and G. Fox had a conference and dispute with Dr. Galenus Abraham,
an eminent Baptist teacher, and some of that persuasion.
Galenus asserted that nobody in these days could be accepted as a messenger of God,
unless he confirmed his doctrine by miracles.
W+++.+++ Penn was lacking no arguments to contradict this,
since the Christian religion had been once already confirmed by miracles,
and that therefore this now was needless among Christians.
G+++.+++ Fox from time to time spoke also something to the matter;
but he being at the time somewhat short of breath, several times went away and returned,
which some were ready to impute to a passionate temper;
but I well know that therein they wronged him.
This dispute was indeed a troublesome business;
for the parties on both sides were made to speak by an interpreter,
which generally was performed so imperfectly,
that at last the conference broke off without coming to a decision,
although many weighty arguments were objected against the position.
Certainly it cannot be denied that John the Baptist was sent of God to preach repentance;
and yet in sacred writ it is positively said that John did no miracles;
and yet many believed in him.
And although there were some among the prophets that wrought miracles,
yet we do not find in the Scriptures that Jonah,
who was indeed a notable preacher of repentance, did any miracles,
and nevertheless the Ninevites believed him.
Of several other true prophets we find not the least mention of any miracles they did;
but on the contrary,
the Scriptures signify that possibly false prophets might arise and give signs or wonders.
And that the doing of miracles could not always be a proof, or sure evidence,
that anyone was sent of God, appears plainly from what our Savior Himself said,
that among those to whom He should one day say,
"`Depart from Me,`" would be such that should say,
"`Have we not in Your name cast out devils, and in Your name done many wonderful works?`"
And what shall we think of the sorcerers of Egypt?
Did they not seem to do the same wonders as Moses and Aaron did?
And yet those wonders with which they deceived Pharaoh
and his men were in no ways wrought by a divine power.
Now, since it appears plainly from the holy Scriptures, and Christ Himself said,
"`There shall arise false prophets,
and shall show great signs and wonders,`" we might with good reason
suspect the doctrine of one who now wrought miracles on purpose
to make what he declared pass for truth.

This being duly considered,
it seems very absurd to require miracles again for the confirmation
of the same gospel which already has been confirmed by miracles;
or to desire that the truth of what once has been declared by the apostles,
and strengthened by wonderful works, should be sealed anew with more outward wonders.
But it would indeed have been another case if a new gospel was preached,
or that any pretended to give forth new holy Scriptures;
for then it might be said with some reason that it was necessary that
this new gospel should be made credible and confirmed by visible miracles.
But where no other gospel is preached than what has been once delivered
to the Christians by the first promulgators of Christianity,
and where this is not done amongst heathens, but amongst Christians,
or at least among such as bear the name,
there it cannot be rightly required to confirm this doctrine once more with miracles.
To this may also be added, that the miracles which Christ and His apostles wrought,
to give credit to the appearing of the Son of God in the flesh,
may be considered as types and figures of those spiritual or inward
wonders which should be wrought in the souls of people when Christ
was to be seen "`the second time,`" and to appear by His Spirit,
to the "`salvation of those who wait for Him.`"^
footnote:[Hebrews 9:28]
For the eyes of the mind being blinded, they must be opened and enlightened by Him;
and many that are dead in sin and trespasses, shall by Him be raised and made alive.
This I think may suffice to show that the position
of Dr. Galenus could not stand the test;
but whatever was objected against it, he continued to maintain his opinion.

Not long after this dispute, G. Fox and W. Penn returned to England, where,
having sustained a violent tempest at sea, they arrived safely at Harwich.
Passing from there to London,
W+++.+++ Penn there received the following letter from the princess Elizabeth,
in answer to his:

Herford, Oct.
29, 1677.

Dear Friend,

Your tender care of my eternal well-being does oblige me much,
and I will weigh every article of your counsel and follow it as much as lies in me;
but God`'s grace must be assistant, as you say yourself;
for He accepts nothing that does not come from Him.
If I had stripped myself of all worldly goods,
and yet left undone what He requires most--I mean to do all in and by
His Son--I would be in no better condition than I am at present.
Let me feel Him first governing in my heart, then do what He requires of me;
but I am not able to teach others, being not taught of God myself.
Remember my love to G. Fox B. F. G. K. and dear Gertrude.^
footnote:[This was Gertrude Dericks, who had visited the princess,
and afterwards came to live in England, and was married to Stephen Crisp.
She died about four years after.]
If you write no worse than your postscript, I can make a shift to read it.
Do not think I go from what I spoke to you the last evening;
I only stay to do it in a way that is answerable before God and man.
I can say no more now, but recommend to your prayers,

Your true friend,

Elizabeth

P+++.+++ S. I almost forgot to tell you,
that my sister writes me word that she had been glad you had taken your journey by Osenburgh,
to return to Amsterdam.
There is also a Drossard of Limbourg near this place
(to whom I gave a copy of Robert Barclay`'s apology),
who is very desirous to speak with some of his friends.

W+++.+++ Penn received yet another letter from the said princess,
in answer to one that he wrote from the Briel, in his passage towards England,
which was as follows:

To the princess Elizabeth, Salvation in the Cross, Amen.

Dear and truly respected friend,

My soul most earnestly desires your temporal and eternal felicity,
which stands in your doing the will of God now on earth, as it is done in heaven.
O dear princess, do it!
Say the word once in truth and righteousness, "`Not my will, but Yours be done, O God!`"
Your days are few, and then you must go to judgment.
Then an account of your talent God will require from you.
What improvement have you made?
Let it prove and show its own excellency, that it is of God,
and that it leads all that love it to God.
O that you may be able to give an account with joy!

I could not leave this country without testifying the sentiments I bear in my mind,
of that humble and tender reception you gave us at your court.
May the Lord Jesus reward you, and surely He has a blessing in store for you.
Go on, be steadfast, overcome, and you shall inherit.
Do not despond; one that is mighty is near you;
a present help in the needful time of trouble.
O let the desire of your soul be to His name, and to the remembrance of Him.
O wait upon the Lord, and you shall renew your strength!
The youth shall faint, and the young men shall fail,
but they that trust in the Lord shall never be confounded.

I wish you all true and solid felicity, with my whole soul.
May the Lord God of heaven and earth have you in his keeping, that you may not lose,
but keep in that divine sense, which by His eternal Word, He has begotten in you.
Receive, dear princess, my sincere and Christian salutation.
Grace, mercy, and peace, be multiplied among you all that love the Lord Jesus.

Your business I shall follow with all the diligence and discretion I can,
and by the first means available give you an account,
after it shall please the Lord to bring me safe to London.
All my brethren are well, and present you with their dear love,
and the rest in your family that love Jesus, the light of the world.
You have taught me to forget you are a princess, and therefore I use this freedom;
and to that gift of God in you I am manifest; and I know my integrity.
Give, if you please, the salutation of my dear love to A. M. de Homes, with the enclosed.
Dear princess, do not hinder, but help her.
Something may be required of her, which (considering your circumstances),
may not yet be required of you.
Let her stand free, and her freedom will make the passage easier unto you.
Accept what I say, I entreat you,
in that pure and heavenly love and respect in which I write so plainly to you.
Farewell, my dear friend, and the Lord be with you.
I am more than I can say,

Your great lover, and respectful friend,

W+++.+++ Penn

I refer you to the enclosed for passages.
We visited Gichtel and Hooftman, and they us.
They were at one or two of the meetings at Amsterdam.
Vale in sternum.

To this letter the princess returned the following answer.

This 17 November, 1677.

Dear Friend,

I have received a letter from you that seems to have
been written at your passage into England,
which I wish may be prosperous.
It is without date,
but not without virtue to spur me on to do and suffer the will of our God.
I can say in sincerity and truth, "`Your will be done,
O God,`" because I desire it heartily;
but I cannot speak in righteousness until I possess
that righteousness which is acceptable unto Him.
My house and my heart shall be always open to those that love Him.
Gichtel has been well satisfied with the conferences between you.
As for my business, it will go as the Lord pleases, and I remain in Him

Your affectionate friend,

Elizabeth

G+++.+++ Fox now having come to London, there received letters from New England,
with an account of the cruel proceedings of the magistrates against his friends there.
For persecution being hot in Old England,
it made things even worse for those in New England;
insomuch that they did not only whip the Quakers that were there,
but also whipped some masters of ships that were not Quakers,
only for bringing some of that persuasion there.
But about that time the Indians made an attack upon the English,
and slew sixty of their men; and having taken one of their captains,
they flayed the skin off of his head while he was alive, and carried it away in triumph.

Now since the people called Quakers were also much persecuted in Scotland,
they drew up an account of their sufferings and delivered
it to the king in the beginning of this year;
but whether they got any benefit thereby, I cannot tell.

In the latter part of this year, G. Fox travelled through many places in England.
In the meantime, I will again make some mention of the persecution there.
At Plymouth about this time,
those called Quakers were generally kept out of their meetinghouse,
and so performed their worship in the open street, as a duty they owed to God.
They suffered exceedingly in this, not only in winter by the sharpness of the weather,
but also in summer;
for it was more than twelve months that they thus kept their meetings in the open street,
being grievously abused by the rabble and the soldiers.
Beating and punching seemed not sufficient,
and fiery squibs and burning coals were thrown among them,
and filthy excrement was cast down upon them out of a window.
Besides this, fines were extorted for their having been at the meeting,
and one Richard Samble, was fined as preacher for having been on his knees at prayer,
which fine was laid upon four others that were present at the said meeting.

At Frenchay in Gloucestershire, the justice, John Merideth,
behaved himself exceedingly furious in disturbing the Quaker`'s meetings;
for he himself did not only beat them,
but more than once drew his knife to "`mark them,`" as he called it,
but was restrained by his servants,
who nevertheless could not prevent his taking some by the hair of the head,
and pulling them away.
Indeed, the havoc and spoil which was made was so extravagant,
that from one Thomas Holbrow, an ancient blind man, they took his bed out from under him,
so that he and his wife lay about a quarter of a year on straw.
And when his friends provided him with some clothing for the winter,
part of that was also taken from him.
For such plundering now took place,
that even the basest men were authorized to deprive others of their goods,
if there was but a justice to favored it.

At Bayton, in Suffolk, Edmund Bally was, by a warrant from justice Burwel,
despoiled of what he had, both within doors and without,
his goods having been seized five times.
And though he was made to lie upon straw, yet he was not left unmolested,
for they once came in the night armed with pistols, broke open his door,
and threatening to destroy him.
It happened in this place also, that a poor blind widow, on her sick bed,
was visited by some friends.
This was called a conventicle, for which they were fined,
and warrants were issued by the aforesaid justice to seize their goods.
In many other places things went no better;
but I will not detain my reader with every particular.

This year died in prison William Dobson, of Brightwell in Berkshire,
having been spoiled of his goods time and again during the space
of thirteen years (and almost always while he was in prison),
until his hard sufferings ended his life.

It was also in this year that William III., prince of Orange,
came from Holland into England, and there entered into matrimony with the princess Mary,
eldest daughter of the duke of York,
which in process of time made way for him to ascend to the throne of Great Britain.
He accomplished his marriage there on the 4th of November, being his birthday,
and not long after returned to Holland with his spouse.

About the beginning of the year 1678, G. Fox came to London,
and as the parliament was sitting at that time,
he and George Whitehead presented to them an account of the grievous
sufferings of their friends by laws made against the Papists.
Finding that several members of that grand assembly seemed to favor them,
they were not without hopes of obtaining some ease;
but the parliament was suddenly prorogued, whereby a stop was put to their endeavors.

G+++.+++ Fox then traveling through many places,
came home to Swarthmore in the latter part of the year;
and since many of his friends at this time were under great persecution, and in prisons,
he wrote the following epistle to them:

My dear Friends,

Who are sufferers for the Lord Jesus`' sake, and for the testimony of the truth;
may the Lord God Almighty with His power uphold you,
and support you in all your trials and sufferings;
and give you patience and contentedness in His will,
that you may stand valiant for Christ and His truth upon the earth,
over the persecuting and destroying spirit which
makes to suffer in Christ (who bruises his head),
in whom you have both election and salvation.
From the foundation of the world, the Lord has done much for God`'s elect sake;
as may be seen throughout the Scriptures of Truth; and they that touch them,
touch the apple of God`'s eye, they are so tender to Him.
And therefore it is good for all God`'s suffering children to trust in the Lord,
and to wait upon Him; for they shall be as mount Zion that cannot be removed from Christ,
their rock and salvation, who is the foundation of all the elect of God,
of the prophets and the apostles, and of God`'s people now and to the end.
Glory to the Lord and the Lamb over all.
Remember my dear love to all friends; and do not think the time long,
for all time is in the Father`'s hand and power.
And therefore keep the word of patience, and exercise that gift;
and may the Lord strengthen you in your sufferings, in His Holy Spirit of faith.
Amen.

George Fox

Swarthmore, tho 5th of the 12th month, 1678.

Persecution was now very hot in many places.
At Bawnasse, in Westmoreland,
it happened that those of the society called Quakers being religiously met together,
were much abused by the rude people;
and besides other acts of insolence that were committed, a dog was thrown among them.
One John Thompson said to this wicked crew that they
ought to behave themselves civil and moderate;
and for saying so, he was informed against as a preacher,
and on that account fined twenty pounds.
Mary Tod, a poor ancient widow in Yorkshire, having had a meeting at her house,
was also fined twenty pounds by justice Francis Driffield;
and when the informers told him that her goods were not worth that much,
he ordered them to take all that they could find.
This they did, not leaving her a bed to lie on, nor any clothes.

This year the ambassadors of the king of France, and those of the United Netherlands,
with those of several other potentates, met together at Nimeguen,
to speak about a general peace;
and therefore Robert Barclay wrote an epistle to them in Latin,
to exhort them to this good work.
The epistle, together with his Apology for the true Christian Divinity, in Latin,
was delivered to each of the said ambassadors, a book for every one of them.
George Fox also wrote an epistle of exhortation to them,
which being translated and printed in Latin, was also sent.
And before this year came to an end, the peace was concluded.

In the meantime, persecution went on in England,
and those that were envious did not lack a specious pretense to cover their malice.
For about this time a plot of the Papists being discovered,
there seemed a necessity to watch against seditious assemblies; insomuch,
that even those who had no mind to persecute, were in a manner constrained to it.
An instance of this was seen in the year 1679, at Castle Dumington in Leicestershire.
For John Evat having been fined for a meeting at his house,
and goods enough to answer the fine not being found,
the constable and three other officers were each five pounds,
because they had been unwilling to take away the said Evat`'s goods.
But the ecclesiastics showed themselves even more
covetous to get what they pretended to be their due;
and one Michael Reynolds, at Farringdon in Berkshire, was this year despoiled of cattle,
barley, and beans, to the value of more than ninety-seven pounds,
and all this for only one year`'s tithes.

Thus honest men were oppressed,
which gave occasion to a certain writer of that time
(who in print gave many similar instances) to say,
"`Truly the Papists may laugh because of their victory,
now that they have a law whereby one Protestant fights against another.`"
This comment was chiefly leveled against conventicles;
for thereby many families were impoverished,
being often robbed of thrice as much as the fine amounted to,
and the basest means imaginable were used to enrich
the persecutors with the spoil of the innocent.
For it happened once that when four of those called Quakers were traveling together,
it was deemed a transgression when a fifth joined them who was not even of their society.
And so great was their power, that the informers (some of whom were often prostitutes,
or the wives of informers) branded it a meeting,
and on this account the goods of the said four persons were seized.
More abominable actions of that kind I could mention,
if I did not think it might seem tedious.
Such despoiling was now permitted to any naughty fellow, and this made them so insolent,
that one John Hill, constable at Walsingham in Norfolk,
when he was showed the injustice of the warrant he had, said "`Justice or no,
I will take it anyway.`"

At Norwich lived one William Wat,
who for several years had carried on the trade of informing,
but whatever he gained by it turned to no account;
and he was often seized with such fits of weakness that he could not stand upon his legs.
But this year, in October, the hand of God fell so heavily upon him,
that it put a period to his life.
He had supped at night, and was as well as ever, according to his wife`'s relation;
but on a sudden he sank down to the ground, and his daughter crying aloud,
he seemed to look at her, and then died without more ado.
But what was looked upon as a very strange thing,
was that his corpse stunk so grievously, that none were willing to carry it,
and the overseers of the poor were necessitated to
hire four men to carry it to the grave.

Far otherwise was the exit of Isaac Penington,
an eminent minister and author among those called Quakers, and a man of an acute wit,
and great natural giftings, who in the year 1658,
on Whitsunday (so called) being in a meeting at the house of John Crook in Bedfordshire,
was so reached by the preaching of G. Fox, that he,
who before that time had contradicted the Quakers with his natural wisdom,
now embraced their doctrine as truth,
and did not hesitate to make public profession of it,
for which he afterwards several times suffered imprisonments
during the space of many years.
But he continued steadfast to the end without fainting, and died piously in October,
at his house near Goodnestone in Kent,
from which his corpse was carried to Buckinghamshire, where he formerly lived,
and was honorably interred there.

Some time before this, G. Fox had written some queries to the Pope and the Papists,
which being translated into Dutch, and printed,
I was requested by him to translate into Latin and to send to Rome to the Pope.
This I did at his desire, but never received or heard any answer to them.
The queries were as follows:

To Innocent XII.
Pope of Rome, S.

Great Prelate,

You will perhaps at first sight marvel that the writing enclosed should be sent to you;
but know it was done at the request of the author; and not undeservedly;
for if you rightly weigh and consider the matter,
you must with us acknowledge that it would be very unworthily
done to keep this little treatise from your view,
which has been already printed in the Dutch language,
and carries the Pope`'s name in the frontispiece.
Nor will you be able to deny, that you are not only not wronged hereby,
but that we have also performed a duty that we owed you,
in transmitting these questions which properly belong to you.
And if you will be pleased to read them and return an answer,
you will both oblige the author,
and also remove the suspicion of error from your religion in the sight of all Christendom,
provided you can give a clear answer to the objections, not only in word,
but in deed also,

I write this at the request of certain of my friends called Quakers.

William Sewel

Amsterdam, the 23rd day of the month called April, 1679.

Some questions presented to the Papists, and the Pope of Rome,
as the supreme head of their church, and commended to their consideration by George Fox.

Friends,

1+++.+++ Why is it that the Pope and cardinals do not grant the Protestants living in Spain,
Italy, and at Rome, the liberty of meeting together for the performing of divine worship,
which you yourselves enjoy in England, Holland,
and other places where the Protestants have the chief power?
Would not the Pope and his ministers persecute, deliver to the inquisition,
and burn them, if they should at any time set up as many meetings in Spain, Italy,
and at Rome, as you yourselves enjoy in many places in Protestant countries?

Does this fulfill the royal law of God,
which teaches to do to all men whatsoever we would have done to ourselves?
Matt.
7:12. Would you have those things done to you by Protestants, which you have done to them?
But if not, where then are the royal law and gospel among you?
God forbid that we should deny liberty to any one that acknowledges God,
and believes in His Son, the Lord Jesus Christ.
It seems therefore very strange to us that the Pope and
Papists do deny the same liberty in the aforementioned places,
which they themselves enjoy among the protestants.
The apostle affirms,
"`That he that was born after the flesh persecuted him that was born after the Spirit.`" Gal.
4:29. Have not the Papists therefore openly showed in themselves the fleshly birth,
which is contrary to reason, law, and gospel?

2+++.+++ Where did Christ or His apostles ever command men to bow themselves to images,
and to worship them, and keep holy days?
Where did they command holy days to be appointed in remembrance of themselves,
and the same to be honored?
Why do you not tell us where in the gospels, epistles, or in the revelation,
any such things were commanded of the churches which were
in the time of the apostles and primitive Christians?
Where, I say, did Christ or His apostles give command to whip, hang, or burn men;
or even to imprison men because they dissented from
them and could not adhere to their religion?

3+++.+++ Where did Christ or His apostles in the primitive churches
ever command that candles should be lit at noon-day?
Show us where it is written, whether it be in the gospels, or epistles.
Has not the Roman church degenerated from the church of the primitive times?
Has she not fallen from spiritual weapons to carnal weapons?
Has she not revolted from that purity and virginity wherein she
formerly witnessed Christ to be the head of His churches?

4+++.+++ Did the churches of ancient time make choice of a private man,
and account him for the head of the universal church?
Wherever did the primitive church command infants to be sprinkled with water?
Did not Christ say, "`Teach all nations, baptizing them,`" etc. Mat.
28:19. Ought they not therefore to be taught before they are baptized?
Have you not degenerated from that faith of which Christ is the author and finisher,
which purifies the heart and gives victory over sin and evil (which separate from God),
and by which we have access to God, and wherewith He is well pleased?
Have you not degenerated from the light, truth, grace, power and spirit,
wherein the apostles were?

5+++.+++ Have you not degenerated from the ancient church,
because you do not allow the people to read the holy Scriptures in their mother-tongue?
For does not the apostles say, "`And when this epistle is read amongst you,
cause it to be also read in the church of the Laodiceans,`" Col.
4:16. And elsewhere, "`I charge you by the Lord,
that this epistle be read unto all the holy brethren,`" 1 Thess.
5:27. Yes, did not Christ also say, "`O fools,
and slow of heart to believe all that the prophets have spoken.`" Luke 24:25.
How can it possibly be that your common
people should believe those things which Christ,
the prophets, and apostles have spoken,
unless it be granted them to read the same in their own tongue,
to the end they might both hear and understand them by the Spirit who gave them forth?
Why then do you take away the use of the holy Scriptures from the common people?
Are you afraid lest the truth should appear manifest,
whereby they might see and believe what is written in the law and prophets,
and by Christ and His apostles?
Did not the Jews have the law and the prophets in their mother-tongue,
that their children might read them?
Ought not therefore all Christians likewise to have the New Testament,
that tells of Christ and His apostles, in their mother-tongue?
But if not, why do you not show us where Christ or His apostles have forbidden it?

But what do you say of the "`sacrament of the altar,`" as it is called?
Why have you slain many, and burnt others alive in England, France, the Low Countries,
and other places, because they could not approve or receive it?
You assert it as a certain thing, that the bread and wine,
as soon as you have consecrated them, are made Christ; yes, the whole Christ,
consisting of soul, spirit, flesh, blood, and bones.
Besides this,
you boldly affirm that all who receive this sacrament do receive the whole Christ,
and that after your consecration, the very thing becomes immortal and divine.

Therefore come, O Pope, cardinals and priests,
let us take a bottle of wine and a loaf of bread,
and equally divide the wine into two basins, and cut the bread into two parts.
Then let the Pope, cardinals, or priests consecrate one part, whichever they please;
and then let us lay up the consecrated and the unconsecrated together,
in some safe place, securing them with seven locks and keys on your part,
and with as many on ours, both Papists and Protestants keeping watch over it.
And if it plainly appear, that the consecrated bread and wine are immortal and divine,
and lose nothing of their virtue and savor, nor grow moldy or sour,
as though they had been unconsecrated, then we will come over to you.
But, if they lose their property, quality, and savor,
and both parts of the bread do alike grow moldy,
then it will be reasonable for you to come over to us,
and confess that your "`sacrament of the altar`"
(so called) is neither Christ nor His flesh,
nor anything immortal or divine; for His flesh saw no corruption, Acts, 2:27-31;
13:35-37, and His precious blood, which delivers from sin and corruption,
cannot be corruptible.

Let a trial then be made of this; and let judgment be left to just and equal arbitrators,
both Papists and Protestants,
and that in a place where the protestants may have the same power that you have;
for it would be unjust to make this trial where you
have the whole administration of the commonwealth,
and an equal liberty is denied the protestants.
This thing will make the truth manifest, and turn to the honor of God; for indeed,
you have slain multitudes of the people of God, and shed much blood upon this occasion.

7+++.+++ Further, where did Christ or His apostles ever speak to the saints of a purgatory,
wherein men should be purged from their sins after death?
Show us where it is written in the New Testament.
Is this not therefore a plain denying that Christ`'s blood purges from all sin,
to tell the people a fable of a purgatory that will purge them from sins after death?
Is it not likewise a denying of Christ`'s baptism with the Holy Spirit,
and of spiritual circumcision, and faith in Christ, which purges from sin in this life,
and gives the victory?

8+++.+++ Did not Christ answer some that desired fire might come down
from heaven and consume those that would not receive Him;
"`You do not know what manner of spirit you are of`"? Did He not rebuke them,
saying that He "`came not to destroy men`'s lives but to save them?`" Luke, 9:54-56.
But you have destroyed such a vast number of men and women
for their dissenting from you about rites and ceremonies,
and taken away their lives by such instruments as racks
and fires--things which were not sent down from heaven,
but rather devised and invented by yourselves.
Are you not worse than they who desired fire to be
called from heaven to destroy men`'s lives?
And seeing Christ told them that they knew not what manner of spirit they were of,
do you know what manner of spirit you are of,
who have devised and made use of so many ways for the tormenting and killing of men?

For when did Christ or any of His apostles ever give command, or by their example teach,
that anyone who was disobedient to them, or who rejected their doctrine and religion,
should be persecuted and imprisoned, or punished by carnal weapons?
Tell us where anything of this kind is found, either in the four evangelical histories,
or in the epistles written to the Christian Churches?
Did ever Christ or His apostles go to the rope-makers to buy whips and halters,
to whip and hang men for dissenting from them as you have done?
Did they ever go to the blacksmiths to make chains, fetters, bolts and locks?
Or to the gunsmiths to buy guns and muskets;
or to the sword-cutlers to buy swords and halberts?
Did they ever build prisons,
or get holes and vaults dug in the ground to force
men by such means to turn to their religion?
Show us an example and precept given by Christ or His apostles,
which commands and makes use of such weapons and instruments.

But if you cannot make proof thereof,
it is necessary for you to confess and acknowledge that you are
fallen and degenerated from the true Christian weapons,
which the apostles and primitive Christians used, saying,
"`The weapons of our warfare are not carnal, but mighty through God,`" that is,
spiritual, 2 Cor.
10:4.

G+++.+++ Fox

To Innocent XI. Pope of Rome, S.

Behold, great prelate, a few questions written for the sake of you, and your adherents,
a copy whereof we sent you by post about three months ago;
but being uncertain whether it was delivered into your hands or not,
we thought good to write the questions over again and send them to you,
that we may not be responsible if you do not read them.
For we think it appropriate that you should earnestly
concern yourself to inspect what has here been printed;
which if you shall please to do, and also answer both by fact and writing,
it will satisfy the author`'s desire,
and remove a doubt or scruple out of many persons`' minds.
Farewell.

This I have written in the name of some of my friends called Quakers.

William Sewel

Amsterdam, the 24th of the month called July, 1679.

This year there was a great commotion in England about a
plot carried on by the Papists against the life of the king,
who made his brother, the duke of York, go beyond sea for some time;
for the parliament suspecting him of this plot,
a motion was made in the house of commons to exclude
him from the succession to the crown;
but this project was quashed.

In the beginning of the year 1680, it happened that George Whitehead and Thomas Burr,
having come to Norwich and preached there in the meeting of their friends,
were taken prisoners, as it was said,
under the frivolous pretense that G. Whitehead might have been a Jesuit.
Being brought before justice Francis Bacon, who then was recorder of the city,
he after some odd examination, demanded of them the fine of twenty pounds a man,
as preachers.
They refusing to pay, he asked them whether they would take the oath of allegiance;
and they answering that they could take no oath for conscience-sake, he said,
if they would neither pay the fines, nor take the oath, he would commit them to jail.
They having showed that they were no vagrants,
but well-known men of competent estates with settled habitations, Bacon said,
"`De non apparentibus, et non existentibus eadem est ratio,`" +++[+++in English:
That which cannot be seen is the same as that which does not exist]; meaning,
that though G. Whitehead had an estate in London, and T. Burr dwelt in Ware,
these things not presently appearing, were as if they did not exist.
Now though they showed the absurdity of this strange kind of logic,
yet justice Bacon would not listen, but called them seducers, and seditious,
and told them that there was a statute yet in force,
that was made in queen Elizabeth`'s days, to hang such persons as they were.
And they asking him if he could prosecute them upon that law, or execute it upon them,
he answered, "`Yes, if the king should give order to have it put in execution,
I would do it, and have you hanged, if you would not leave the realm.`"
From this it may appear what a violent man this recorder was,
and that the prisoners could not expect any good treatment from him.
So night having come, he sent them to the jail.

About a month after this, at the quarter-sessions,
they were called into the court of judicature to be tried.
Being brought to the bar, George Whitehead said, "`We have been five weeks in prison.
It is fitting the court should know for what; please let our court order be produced.`"
But the recorder who sat as judge in the court, said,
"`There is no need for your court order to be read here.
I will give an account of the cause.`"
He then told the court how these two had gathered together a company of about two-hundred,
and that officers had been sent from him to dissipate them, but could not;
that thereupon he had sent the sheriff, who took them away;
and that when they were brought before him,
he offered to release them if they would pay their fines; and that they refusing,
he tendered the oath of allegiance to them; which they not being willing to take,
he sent them to jail.

And though G. Whitehead with good reason said, that they being Englishmen,
had a right to travel in any part of the nation;
and T. Burr added that he being a person that was concerned in trading in corn,
by the law of England he might travel from place to place about his concerns;
yet this so displeased the recorder, that he said,
"`It had been better for you to turn your malt at home, than to come here to preach.
The Scripture says,
'`God added to the church such as should be saved;`' but you draw from the church.`"
And he further said,
"`The church of England will never be at peace till some of you be hanged.`"
G+++.+++ Whitehead then showed how unreasonably the recorder behaved himself,
showing that a judge ought not to thus berate the prisoners and threaten them;
and he alleged as a notable instance, how, in the case of Humphrey Stafford,
an arch traitor,
the chief justice Hussey had been unwilling (in compliance with the king`'s desire)
to declare his opinion concerning him before he was judicially proceeded against.
The recorder then asked, "`What king`'s reign was that in?`"
"`In the reign of king Henry VII,`" replied George Whitehead.
"`I perceive you are well-read,`" replied the recorder.
And so he was indeed; and he defended his cause so well in the court,
that the magistrates seemed to be at a loss.
For he showed so evidently that he was unjustly committed to prison,
that the mayor (to whom he had appealed) said, "`You have appealed to me;
but truly we are tradesmen, and no lawyers.
We leave matters of law to the recorder.
He knows the law, and we must acquiesce in his judgment.`"

If I should repeat here all that was spoken pro and con,
I should be almost as lengthy as I have been in the relation
of the trials of John Crook and William Penn.
I therefore will only say briefly, that, after much reasoning,
the recorder tendered the oath of allegiance again to them,
that so by their refusal he might get occasion to premunire them.
But this recorder, before the whole process came to an end,
was turned out by the magistrates, so that things did not come to such a height.
It nevertheless was a good while before the aforesaid
George Whitehead and Thomas Burr were released,
after they had shown the illegality of their imprisonment; first,
by more than one warrant from the recorder, and afterward,
by an order from the quarter-sessions.

This year those called Quakers in London,
published a brief relation of the sufferings that their
friends had met with since the king`'s restoration,
and presented it to the king and parliament, showing therein,
how many had been fined by the bishops`' courts, robbed of all they had,
put into prisons, and there died.
This number was computed to be two hundred and forty-three persons,
many of whom had been so grievously beaten and wounded
because of their attending religious assemblies,
that they died of their hurts and wounds.
There came forth also a printed account of the unjust proceedings of the informers,
and how at their demand, without a judicial process,
the accused were often bereaved of their goods,
the unlawfulness of which was plainly shown from the books of eminent lawyers.

G+++.+++ Fox now travelled through many places,
and came to London about the time of the annual meeting;
and traveling afterwards again into the country, he returned into the said city,
and stayed there the most part of the winter.

The parliament was then very busy with enquiring into the plot carried on by the Papists;
and the house of commons was especially active in the case,
so that the bill to exclude the duke of York from the succession
to the crown passed after a third reading.
But this was opposed in the house of lords; for by a majority,
among which were the bishops who would not consent to the exclusion,
the bill was rejected.
Now since some ill-natured Episcopalians were very
eager to place the Quakers amongst the plotters,
G+++.+++ Fox gave forth the following declaration to the parliament:

It is our principle and testimony,
to deny and renounce all plots and plotters against the king, or any of his subjects;
for we have the Spirit of Christ, by which we have the mind of Christ,
who came to save men`'s lives, and not destroy them.
And we desire that the king and all his subjects be safe.
Therefore we do declare, that we will endeavor, according to our power,
to save and defend him and them,
by discovering all plots and plotters which shall come to our knowledge,
that would destroy the king or his subjects.
This we do sincerely offer unto you.
But as to swearing and fighting, which in tenderness of conscience we cannot do,
you know, that we have suffered these many years for our conscientious refusal thereof.
And now that the Lord has brought you together,
we desire you to relieve us and free us from these sufferings,
and that you will not impose upon us to do those things,
which we have suffered so much and so long already for not doing.
For if you do, you will make our sufferings and bonds stronger, instead of relieving us.

George Fox

Not long after this, he also wrote a paper to all rulers and magistrates in England,
Scotland, and Ireland, to dissuade them from persecution for religion.
His labor seemed not altogether ineffectual with the parliament,
for about the beginning of the year 1681, the house of commons resolved the following:

"`That it is the opinion of the house,
that persecution of Protestant dissenters upon penal laws,
is at this time grievous to the subjects; a weakening of the Protestant interest,
an encouragement to popery, and dangerous to the peace of this kingdom.`"

But though the house of commons came to this resolution, yet it did not stop persecution;
for as long as the laws by which they persecuted were not repealed (which could
not be done without the concurrence of the house of lords and the king),
those who were malicious continued in their old ways,
which lasted yet another three or four years.

George Fox now also came into some trouble,
finding that he and his wife were sued for tithes,
though she had lived forty-three years at Swarthmore,
and in all that time no tithe had ever been paid or demanded.
Of this George Fox had certificates;
but since they would not accept them without an oath,
it made his case the more difficult.
He proposed the matter to four judges in London,
and found one more moderate than the others;
which put a stop to what her enemies designed.
And the judges marveled when they heard he had made a promise
in writing never to meddle with his wife`'s estate.

This year the king dissolved the parliament, and called a new one to sit at Oxford,
and so it did; but for all this he could not make it comply with his demands,
and so he dissolved that parliament also.
Some time after this he requested the prince of Orange to come over,
who thereupon came from Holland into England, and after a short stay,
returned to the Hague.

It was also in this year that the king gave a great
tract of land in America to William Penn,
with a patent under the great seal to him and his in perpetuum,
since the king owed him still a considerable sum for the services of his father,
the admiral sir William Penn.
This tract of land on the river Delaware, from the fortieth degree to the forty-third,
with all the islands belonging to it, the king gave to W. Penn,
with full power to erect a new colony there, to sell land, to create magistrates,
to make laws not contrary to the laws of England, and power to pardon crimes.
And in this patent,
the king declared that this tract of land henceforth should bear the name of Pennsylvania.
This favor of the king, William Penn chiefly owed, I think, to James, then duke of York.
For sir William Penn, being chief admiral of England,
on his dying bed had requested the duke to protect his son against his enemies, who,
because of his religion, were likely to fall hard upon him.
This the duke promised and performed.
And it was not without reason that William Penn afterwards,
when the said duke had ascended the throne,
showed himself ready to be serviceable to him in
all that he thought might be beneficial to the kingdom.
William Penn now went with much company to America.
And having seen the land given to him, he founded there the chief city Philadelphia,
and some other towns.
And that he might the more peaceably enjoy the country,
he purchased from the Indians so much land that he became
proprietor of a tract twice as big as all the United Provinces,
as he himself once told me.
And this colony increased so quickly, that after a few years,
there were built six hundred brick houses in Philadelphia.

William Penn`'s father had deceased long before this,
and on his dying bed declared that he had a gracious God,
and gave marks of a true Christian disposition of mind.
He also gave his son several wholesome admonitions how to behave himself in this world.
He complained much of the wickedness of the times, and was heard at sundry times to say,
"`Woe to you, O England!
God will judge you, O England!
Great plagues are at your door, O England!`"
He also said, "`God has forsaken us.
We are fools, and will shut our eyes.
We will not see our true interest and happiness.
We shall be destroyed.`"
When he was near death, and took his leave of his relations, he said to William Penn,
"`Son William, if you and your friends keep to your plain way of preaching,
and keep to your plain way of living,
you will make an end of the priests to the end of the world.
Bury me by my mother, live all in love, shun all manner of evil.
And I pray God to bless you all; and He will bless you.`"
Thus died the valiant admiral Penn, father of William Penn, proprietor of Pennsylvania;
and now I return to other matters.

I left George Fox at London, and since he continued thereabouts a good while,
I will take a turn to Bristol, where in the year 1682,
a dismal scene of persecution had opened.
The meetings of those called Quakers were disturbed,
not only by grievously abusing and imprisoning them,
but they were also harassed by people breaking into their houses,
and committing all manner of violence.
Among the rest, this was the case in the house of one Richard Marsh,
an eminent merchant in that city.
For, to get from him the fine that was alleged,
first a cask of wine worth twenty pounds was taken and sold for four pounds.
This often happened,
for goods that were taken in this manner would often sell for less than half their value,
because honest people were unwilling to buy them,
and so they were sold to any one that would but bid some money, no matter how little.
And what was still remaining of the fine was then taken anew from the fined person,
as they did in this case; for they broke open his counting-house, sought for money,
and took away his ledger, journal, cash-book, and other books and accounts,
besides many household goods.
Several of his rooms were rifled through,
though the wife of the said R. Marsh lay all this time in bed with a newborn child.
The chief actors of this insolence were the sheriff John Knight,
and John Helliar an attorney, who, with his companions Lugge, Tilley, Casse, Patrick,
Hoare, and Watkins, served as informers.
Knight and Helliar came frequently with a multitude of boys
and rude rabble to disturb the meetings of the Quakers;
and then they carried them to the prisons, which grew so full,
that about fifty persons were crowded into a single room.
This room was so nasty, that one of the aldermen, sir Robert Cann, said,
if he had a dog that he loved he would not put him there.
And though the mayor of the city, sir Thomas Earl, and some justices and aldermen,
at the request of others,
showed themselves inclined to move the prisoners to a better place,
yet the power of the aforesaid sheriff John Knight was such that he hindered it.

The meetings of other Protestant dissenters were now also disturbed,
but they generally fainted and gave way; whereas the Quakers stood firm,
no matter how they were harassed, which often was done in a very outrageous manner.
For their meetings were not only often disturbed with the noise of drums and fiddles,
but liberty was given to the vilest fellows to commit all kinds of insolence
without showing any regard to those of the female sex,
whose hoods and scarfs were torn from them.
And John Helliar, to give the boys a sign to attack the women, used to say to them,
"`Look after your hoods and scarfs!`"
And then the boys would fall upon them,
and both aged women and ancient men were carried to prison,
and forced by pushing and pinching their arms black
and blue to go faster than they could.
And when once a girl spoke a word against this cruelty, she was pulled by the hair,
and hauled to prison.
Indeed, even little boys were beaten on the head till they grew dizzy,
and then they were carried to Bridewell,
where J. Helliar charged the keeper to "`get a new cat of nine tails,`" endeavoring
to terrify the children by making them believe they should be whipped,
unless they would promise to come to no more meetings.
But this did not succeed;
for his extravagant malice did not subdue the constancy of these children.

With such diabolical rage they persecuted this people at Bristol,
that not a stone was left unturned to afflict them.
Once they were locked inside their meetinghouse with boards and nails,
and thus kept for the space of six hours; which must have been very hard to nature,
since there were also women of no insignificant families present,
and among these the widow of the upper sheriff Lane.
And so many were taken prisoners,
that at length there was no more room for them in the jails.
By these proceedings many families were ruined; for their goods were taken from them,
not only on the account of meetings, but when any were believed to have good estates,
the oath of allegiance was tendered to them.
At court it seems they were the more offended against
the Quakers because in the election of parliament,
some had voted for such as they believed to be moderate men, and no favorers of popery.
It was therefore said underhandedly,
that if Mr. Penn or Mr. Whitehead would convince
the Quakers not to vote at elections of parliament-men,
there would be no further persecution of them.

In the meantime,
the behavior of the persecutors in the meetings was brutish in the highest degree;
insomuch that a certain woman,
seeing that the attorney John Helliar lifted up her child by the hair of his head,
asked him why he so abused her child, and was for it ill-treated herself by him.
And by order of the said Helliar,
a young girl was committed to Bridewell prison because she gave an impudent boy,
who attempted to turn up her coats, a box on the ear.
But for defending her modesty,
this brutish Helliar called her a "`rioter and a seditious person;`" for he was,
as has been said already, a leader of insolent and saucy boys,
which he often took along with him to disturb the meetings of the Quakers.
And sheriff Knight did often with his cane very violently beat those who had met together,
and he once grievously abused an ancient man named Britton,
and pinched some women violently in their arms.
Susannah York, an aged woman, was thrown down to the ground;
Mary Hooper was very roughly handled by Helliar, had her scarf torn off her back,
and was so pushed and flung about, that she was much out of order for a long time after.
Mary Page, being big with child, was so violently hauled out of the meeting,
that her life was endangered by it.
With Helliar it became customary to call men "`rogues,`" and the women "`whores, jades,
carrions, and damned bitches.`"
He also bid the boys to tear their scarfs and take up dirt to throw upon them.
Of this beastly rage there were many witnesses;
for these abominable dealings displeased many people of other religious persuasions.
But it seems these enraged fellows had encouragement from the court,
upon which they dared to rely; for the sheriff John Knight was knighted,
and therefore grew more insolent than before.
Once it happened that Helliar, having disturbed a meeting,
drove the women along the streets as if they had been cattle.
And being asked by one if he sought to make beasts of them, he answered,
"`You are worse than beasts; for beasts will be driven, but you will not.`"

This disturbing of meetings continued till almost
all the men belonging thereto were confined in prison.
Some of these, sending a petition to the mayor and justices of the city,
requesting that they might be allowed larger rooms, since not only their health,
but their lives also were endangered,
the said magistrates showed themselves inclined to
allow the prisoners some ease or freedom.
But the power of sheriff Knight was such, that whatever they said or did,
all proved in vain.
Now the mayor informed the sheriff that he desired
that all convictions be made above board,
and not in ale-houses and taverns;
and that all confiscated goods be brought into a public warehouse, and not in a by-lane.
But though the mayor ex officio was to have commanded the sheriff,
yet this officer was so countenanced by those in power,
that he did not care for whatever the mayor said.
Indeed, he was so exorbitant,
that his adherents began to threaten the mayor that he should no longer be a parliament-man;
insomuch that he was forced to comply in some degree.

In the meantime, the havoc and spoil was so enormous,
that generally twice as much was taken as the fine amounted to.
The prisoners, some of whom lay on the floor, others in hammocks,
and some in a cold and open room, being exposed to the wind and injury of the weather,
suffered great inconveniences.
The jailer Isaac Dennis, imagining that nothing could be too bad for them,
would show them no favor, and his wife showed herself no less unreasonable than he,
so that one extortion came upon the heels of another.
Four physicians of Bristol, namely: John Griffith, William Turgis, J. Chauncy,
and T. Bourn, seeing how closely the prisoners were penned up and thronged together,
gave a certificate under their hands in which they declared that,
feeling moved with compassion,
and considering what dangerous consequences such a close confinement might cause,
they were compelled to certify that such conditions
had a great tendency to breed infectious diseases,
to the endangering of their lives, etc.
But all this did not avail them, it being not counted worthwhile to be concerned for them.
Indeed, so desperately wicked was the jailer,
that when the prisoners complained for lack of room, he said to his servant,
that as long as he could shut the door, it was well enough.
But in due time we shall see what anguish and horror befell him.

After most of the men called Quakers in Bristol were in prison,
the women who continued to keep up their religious meetings were also seized,
and confined in such great numbers,
that at length few or none but children (who stayed with
the servants in the houses of their parents) were left free.
The number of prisoners in this place for the sake of their
religion amounted now to one hundred and fifteen,
and some of them were confined in Bridewell,
among whom were also Barbara Blaugdon (several times
mentioned before,) and Catharine Evans,
who had learned in Malta what it was to suffer a tedious and hard imprisonment.
It is very remarkable that children under sixteen years of age
now performed what their parents were hindered from doing;
for these children kept up their religious meetings as much as was in their power.
But though they were not within the reach of the law,
yet once nineteen of these youths were taken and carried to the house of correction,
where they were kept for some time.
And though they were threatened with whipping if ever they returned to the meeting,
yet they continued valiant without fainting,
though they suffered exceedingly from the wicked rabble.
But so great was their zeal,
that they remained steadfast despite all reproach and insolence, and thus showed that,
in spite of their enemies,
God would not permit the meeting of Quakers to be altogether suppressed, as was intended.
The persecution here continued till the next year,
as it did in several other places also; for there was no lack of informers,
who continually lay in wait for their prey, even to such a degree,
that once when some of those called Quakers had come from other places to market,
and had gone into an inn to refresh themselves,
an informer did not hesitate to declare upon his
oath that the Quakers had kept a meeting there.

But before I leave Bristol, I must give some account of a ridiculous act,
performed by one Erasmus Dole, who bore the name of a Quaker.
He having said that he did not scruple to declare the contents of the oath of allegiance,
it was planned that he would repeat after the clerk,
and skip over such words as he disliked, and use others in its place,
such as "`I declare,`" instead of "`I swear.`"
This took place, and while he was thus speaking, the jailer held his hand to the book,
and when Erasmus had said all, he put the book up to his mouth,
to make this pass for kissing it.
With this the court seemed satisfied; and the bishop of Bristol,
seeing these apish tricks,
told the court that this was no different than taking the oath, at which they gloried,
as having obtained a victory.
But this was a pitiful victory; for Erasmus being a man of an irregular life,
the Quakers had but little cause to regret the loss of such a member.
And growing increasingly dissolute,
in process of time they found themselves necessitated
to disown him because of his offensive conduct.

In Gloucestershire the people called Quakers were also under
great sufferings by imprisonment for keeping their meetings.
It was here that the wife of one John Boy,
being at a peaceable meeting at Little Badmanton,
was through instigation of the priest of the parish,
in a violent manner dragged out of the meeting by the lord Herbert`'s footmen.
Because of these abuses, this woman fell sick and miscarried,
to the endangering of her life; and her husband,
who was also taken prisoner at the same place,
was not allowed at his request to see his wife.

In Leicestershire things were no better.
One Elizabeth Hill being in a meeting at Broughton,
was by the rude boys dragged out and so abused that
she was seemingly quite spent and near dead.
And as she lay in the dirt, one of the boys, in order to try whether she was still alive,
put his finger into her mouth, and perceiving her to breathe, said,
"`Let us go at her again.
The devil is still in her, and we will squeeze him out!`"
These cruel abuses made a neighborly woman cry out, "`What, will you kill the woman?`"
To which the boys said, "`What do we care?
Mr. Cotton bid us do so.`"
"`Did he indeed?`"
asked the woman.
"`Yes, indeed,`" replied the boys.
"`Then,`" said she, "`he should be ashamed of it.`"
Thus these boys openly said that it was the parson, Thomas Cotton,
the priest of the parish, who encouraged them to this excessive wickedness.
And the servant of this priest, whose name was Thomas Ambrose,
did not hesitate to say that nothing would drive
the Quakers away but either fire or water;
and if the house were his (meaning the house where they met together),
he would burn it down upon their heads.
More instances of such exorbitant wickedness which happened at sundry places,
could be mentioned, if I did not desire brevity.

George Fox being in London this year about the time
of choosing new sheriffs for the city,
wrote a few lines to the candidates for that office who
desired his friends to give their voices in support of them.
And in the conclusion he said, "`Will we be free to serve and worship God,
and keep His commands, if we give our voices in support of you?
For we are unwilling to give our voices for those who will imprison and persecute us,
and spoil our goods.`"
The constables in London were sometimes sent with
warrants to disturb the Quakers`' meetings;
but it was easily seen that they would rather have been freed from such a commission;
for though they would bid George Fox or others who preached to cease from speaking,
yet they and the soldiers who sometimes accompanied
them generally behaved themselves moderately,
sufficiently showing that they were not in favor of persecution,
and that what they did was for the sake of their office.
Sometimes they indeed hindered friends from going into their meetings;
but even though some where thus kept out, their numbers nevertheless increased.

Once it happened that George Fox was stopped by the
constables from going into Devonshire-house meeting;
and after having stood awhile in the yard till he was weary,
one gave him a stool to sit upon.
After a little while he stood up and preached, and in his declaration said,
"`You need not come against us with swords and staves, for we are a peaceable people,
and have nothing in our hearts but good-will to the king and magistrates,
and to all people upon the earth.
And we do not meet under pretense of religion in order to plot against the government,
or to raise insurrections; but to worship in spirit and in truth.`"
When he had spoken what was upon him at that time, he sat down,
and after a while concluded the meeting with prayer,
at which the constables and soldiers as well as others put off their hats.
And when the meeting had finished, a constable taking off his hat, said very seriously,
"`The Lord bless you;`" and all were allowed to pass away unmolested.

Thus this year came to an end.
All other Protestant dissenters were now suppressed;
for they were restrained from exercising any public worship.
But there were some of these, who, in their nocturnal meetings,
would pray that God would keep the Quakers steadfast,
that so they might be as a wall around them,
in order that other dissenters might not be rooted out.
And yet these same Protestants had formerly been very active
in setting the Quakers forth in very ill colors,
in order to render then odious.
But this people continued now so valiant, and without fainting,
that some of their persecutors were heard to say, "`The Quakers cannot be overcome;
the devil himself cannot uproot them.`"

In the year 1683, persecution continued in many places;
and by computation it appeared that above seven hundred
of those called Quakers still suffered imprisonment in England.
I could mention several instances of persecution in Leicestershire, Northamptonshire,
and elsewhere; but to avoid prolixity, I will only turn again to Bristol,
where persecution continued to such a degree that
if any of the people called Quakers came to a meeting,
they were presently committed to prison.
Among these was one Richard Lindy, a blind man, of about ninety years of age,
who was carried to jail and forced to sit up three nights in a chair,
though others offered to pay for his lodging if some
convenient place to lie down had been allowed him.
Some of the prisoners, being tradesmen,
would willingly have worked in prison to earn something for their sustenance;
but the jailer, Isaac Dennis, would not permit them this liberty.
Other prisoners fell sick of the spotted fever, and some died of it;
yet all this did not soften the said hard-hearted jailer.
But at length a heavy stroke fell from heaven upon him;
for about the middle of the month of October he fell sick,
and was seized with terrible anguish of mind.
He then wished he had never seen the inside of the jail,
and requested some of the Quakers to pray for him,
and to forgive him for what he had done.
To this they answered that they indeed did forgive him,
but he should ask forgiveness of God.
But still his anguish increased; and when the physicians ordered him to be bled,
he said no medicine would do him good, for his ailment was another thing,
and no man could do him any good, for his day of visitation was over,
and there was no hope of mercy from God for him.
Some of those called Quakers seeing him in this woeful condition,
told him that they desired, if it was the will of the Lord,
that he might find a place for repentance.
They also told him they hoped his day of visitation was not over,
because he had such a full sense of his condition.
To this he answered, "`I thank you for your good hope; but I have no faith to believe.`"
And he further said, "`Faith is the gift of God.`"
Whatever was spoken to him, he continued in saying that his day was over,
and that there was no mercy for him.
Such a gnawing worm is the guilt of conscience;
and in this desperate state he continued a little more than a month,
and then died the last of November without any visible signs of forgiveness;
but the judgment thereof we must commit to God.

Although the people called Quakers were oppressed by sufferings all over the country,
yet generally they continued valiant;
and as George Fox did not omit from time to time to encourage
them by letters to faithfulness and steadfastness,
so several others of their teachers did not neglect
to exhort them to perseverance both by word and writing.
And what was indeed remarkable, was that those who travelled to and fro in the country,
and publicly preached in the meetings of their friends, generally had their freedom,
and the informers were often disappointed of catching a preacher.
I find it left upon record by Charles Marshall, an eminent minister,
that though in the time when persecution was the most hot,
he travelled through the nation, yet none laid hands on him,
or fined him for his preaching, which was the more remarkable because,
he being a very zealous man, used to lift up his voice in a very powerful manner.

William Dewsbury, who had now grown ancient in his imprisonment at Warwick,^
footnote:[William Dewsbury was a prisoner a total of nineteen years in Warwick jail.]
wrote an epistle of consolation to his suffering friends,
which was thought fit to be reprinted, and is as follows:

Dear Brethren and Sisters,

Hear the word of the Lord.
Thus says the Lord: Though you now drink the cup of adversity,
and eat the bread of affliction,
and are trampled upon as though you were not worthy to live upon the earth,
yet notwithstanding all the fury of men,
you are resolved in the strength of My Spirit forever
to be deprived of the sweet enjoyments of wife,
husband, tender children, parents, and outward possessions, liberty and life,
before you deny the testimony of My name before the sons of men.
Oh, you dear and tender children, who love not your lives unto death this day,
in order that you may finish a good testimony for the glory of My name,
says the Lord God; lift up your heads in the light of My covenant,
and believe in My name, for I am near unto you, says the mighty God of safety.
And let not any weight or burden lie upon you;
for I will be more than a husband to your wives, and more than a wife to your husbands,
or parents to children, or children to parents; yes, I will be a husband to the widow,
and a father to the children who are deprived of
their tender parents for My name`'s sake.
I will enlarge your borders in the life of My righteousness.
And you who suffer in true innocency, I will refresh you with the depth of My mercies;
yes, I will guard you with the angel of My presence,
and all that devise mischief against you shall be
confounded before the glory of My power,
with which I will keep and preserve you in the word of My patience, and safety,
in My presence, says the Lord God.

Therefore, you dear children, who drink the deepest of sufferings, think it not hard,
for it is My purpose unto you all, who do not have an eye turned to self,
but who alone seek My glory in all that you do.
I will make you more and more honorable in the glory of My life,
and double My blessings upon you and yours; for I have beheld your integrity,
and My heart is mightily moved with compassion towards you.
Therefore I have arisen for your sakes this day, to declare unto you,
My suffering people, that not a hair of your head shall perish,
neither shall you be detained in prisons and desolate holes any
longer than I have determined shall be for your eternal good,
and for the glory of My name forever.
Therefore stand faithful in My life, resisting every evil thought,
or whatever would cause you to murmur or desire anything
but what you know will advance the glory of My name,
and the exaltation of My truth over all that rises up against it.
Be subject to the measure of My light and life,
which will not let any seek a preeminence or esteem amongst men.
Neither let self-striving nor self-serving have power in any, but in true humility, love,
and meekness, watch one over another; and let the strong take the weak by the hand,
that you may all gently, in love, meekness, and holy fear, dread My name,
and serve one another; that your love may be manifest unto Me, says the Lord your God,
and to one another in the naked simplicity of your spirits.
Then I will make my dwelling amongst you, and with you;
and My dreadful and glorious presence you shall all
feel mightily within you and amongst you,
moving in the exercise of My Spirit to the renown of My name,
and to the comfort of one another.
And I will crown you with heavenly blessings, and with the glory of My powerful life;
and you shall praise My name forever, because I made you My jewels,
and counted you worthy to suffer for the testimony of My name.
I will go before you through all the waters and floods of afflictions;
and I will appear with you before all the councils of the sons of men.
My saving power shall compass you about in your hot and sharp afflictions,
all you who have your confidence alone in Me, the Lord your God.
Therefore, trust in My name, My dear children,
and cast all your care upon Me. And if any of you
joyfully suffer the spoiling of your goods,
I will supply you with what is needful for you and yours;
and if any of you seal your testimony with your blood in the word of My patience,
I will take care of your tender wives, children, or parents,
for whom your souls have been poured forth in prayers unto Me for their good.

Therefore hear My word,
which is sounded unto you from the throne of My grace and eternal glory:
rejoice not too much in spirits being made subject to you,
but throw your crowns down before Me, that a self-seeking,
self-serving spirit may not be found in the family of My people.
But all feel the immortal birth raised up in the resurrection of My life in you all,
which truly makes self of no reputation, so that all loftiness is laid low,
and all haughtiness is bowed down in everyone,
that I the Lord God in you all may be loved, obeyed, and exalted.
For I am taking, and will take My great power, and will exalt the meek upon the earth,
and reign over all the pride of the children of men
(which is exalted above My witness in their conscience),
that so My sons may be brought from afar, and My daughters from the ends of the earth,
in the sight of all people.
And I will make all confess, in subjection to My power,
that you are the beloved people of the most high God,
and are of the righteous seed which the Lord has blessed.
Not any weapon formed against you shall prosper, but all will come to nothing;
and my will shall be performed according to what is here declared,
to your eternal joy and comfort;
and you shall assuredly know the mouth of the Lord has spoken it.

The word of the Lord, above expressed, came to me in the prison-house at Warwick,
the 13th day of the First-month, 1664,
which constrained me to send it to be read amongst you, dear, faithful,
and suffering people of the Almighty God,
in whom I remain your brother and companion in the tribulation
and kingdom of patience in the Lord Jesus Christ.

William Dewsbury

While persecution was hot in England,
there occurred some division among those called Quakers,
which had its rise some years before.
Those who first introduced the conflict were John Wilkinson and John Story,
preachers among them, who showed themselves discontented against George Fox,
chiefly about the management of church affairs,
finding that things did not always go as they would have it.
And since George Fox had been the first institutor of good order amongst his friends,
he was also the chief object of the envy of the malcontented.
Now because in the beginning there were no such meetings for order or discipline,
and yet they had lived in mutual peace and unity,
it was asserted that such meetings were needless,
and that everyone ought to be guided by the Spirit of God in his own mind,
and not to be governed by any rules of man.
Thus it appeared,
that these men were against the establishing of any order of government in the church.
They were particularly bent against the women`'s meetings, who as deaconesses,
met together at certain times to provide for poor
families and sick people that were in need.
Now it is true,
that in these meetings there were sometimes issues
debated that were not so appropriate in every respect,
because young women were admitted there also to see and learn how
matters were handled by the serious and ancient women;
and perhaps some were a little too forward in meddling
with affairs properly belonging to the men.
Nevertheless,
the creeping in of a wrong use can by no means justify
abrogating that which is really useful;
and that honest and ancient women took care for the poor
and indigent members of the church was indeed laudable.
But as in large communities there are generally found
some who love to govern without being fit for it,
so some of the people adhered to John Wilkinson and John Story.
These men, and several others,
besides being opposed to the good order and government of the church,
were in favor of meeting secretly,
rather than to come to public meetings and so be exposed to the fury of their enemies.
They also advocated the paying of tithes to the priests rather
than suffering spoil or imprisonment for the refusal thereof.

From here a schism or rent arose, first in the north of England,
and some who went under the denomination of Separatists,
began to keep meetings by themselves, leaving their former friends,
though they pretended to agree with them in matters of doctrine.
To these Separatists joined several who were not strict in their manner of living,
and were therefore unwilling to submit to wholesome church discipline;
for it had become a common saying of these people,
that everyone having received a measure of the Spirit of God,
ought to regard that leader, without minding any rules prescribed by men.

In the process of time,
William Rogers and Thomas Crisp appeared in print against their former brethren,
and upbraided them with accusations of imprudent behavior and inconsiderate acts.
Besides that, on mere hearsay, they published a multitude of untruths,
and denounced even lawful things;
an instance of which appeared when Rogers (in paltry verses) scornfully
reviled them for having given something to a few traveling preachers,
who, so as not to neglect their public ministry,
could not duly mind their private affairs;
though this supply never exceeded their necessary provisions.
Rogers would continually appeal to the "`primitive times`" of friends,
and to give some weight to what they asserted,
he and his adherents published a paper with Edward Burrough`'s name on it,
who had been dead above twenty years.
But George Whitehead and others gave good proofs that the apostate
John Perrot had been the author of that so much applauded paper.
At length this rent appeared also in London, where malcontents were likewise not lacking,
who not being strictly conscientious in their conduct,
would rather live without any restraint.
And even some who were honest, were by fair words persuaded into separation;
for among the Separatists one Charles Harris preached,
who was pretty fluent in speech and elegant in his expressions,
as I have seen and heard myself.
But however specious the pretenses of these Separatists were,
and whatever endeavors were made, yet they were not able to continue and subsist firmly;
but at length they decayed and vanished as the snow in the fields;
for the best among them came in time to see that they had been deceived,
and the less honest grew worse.
Indeed, among themselves they were not free from division; and though George Keith,
(whose apostasy will be mentioned in its place) endeavored to lurk among them,
yet he got no adherents there.
I have often wondered how Wilkinson, Harris,
and Keith (all of whom I have personally known) could
apostatize to such a degree as they did.
But this is not so exceedingly strange as some may think it to be;
for we find on record that even in the primitive apostolical church,
there was an Alexander the coppersmith, and Hymeneus and Philletus,
who made shipwreck of the faith,
and caused such a rent that it was said their words spread like a cancer.

In London the meetings this year were often disturbed;
but the magistrates themselves seemed not to approve of it,
for they clearly saw there was nothing to be feared from the Quakers,
and yet they were reluctant to give offense to the court party which then prevailed.
G+++.+++ Fox coming once to the meeting at Gracechurch-street,
and being kept out by the constables, stood up in the court and preached to the people;
but a constable plucked him down, and afterwards let him go free.
At another time having been in the meeting at the Savoy, and being brought to a justice,
there was one Gabriel Shad, an informer, who was so full of impertinent talk,
that the justice grew angry.
Nevertheless this justice thought himself bound to do something,
and so asked G. Fox if he did not preach in the meeting?
To this question George warily answered,
that he did confess what Christ had done for his soul, and did praise God for it;
and that he thought he might do this in the streets and in all places;
and this he was not ashamed to confess,
neither was it contrary to the liturgy of the church of England.
To this the justice said the laws were against such
meetings as were contrary to the church of England;
and at length spoke of sending G. Fox to Newgate prison,
signifying that he would make a court order for him after he had dined.
But when the constable came again after the evening service,
the justice told him he might let G. Fox go;
and the next day he signified to one of G. Fox`'s friends,
that by some chance event he had been disappointed of fining him.

Thus G. Fox was freed and remained in London,
where a plot was said to be on foot against the king and the duke of York,
of which the duke of Monmouth was said to be the head.
This design, whatever it was, cost the lives of several persons,
among whom was the earl of Essex, who unfortunately perished in the Tower,
and the lord Russel, who was made to bow to the axe.

Now since persecution continued with some pretense of justice,
those called Quakers drew up the following address to the king:

To the King.

The humble address of the people commonly called Quakers.

O King,

May the King of kings, and Lord of the whole earth,
incline your heart to that which is just and merciful in His sight,
and to make such clear and equal distinctions,
as that the innocent may not suffer in any case for the guilty;
that it may ever redound to your honor and safety,
and the comfort of your peaceable subjects.

Our innocency, love, and good-will to your person and government,
which God has committed to you,
encourages us in this our humble address and application.

Whereas the plot against the king, and his brother the duke of York,
etc. is made an occasion to persecute many of us for our religious meetings,
even more severely than formerly,
we therefore do solemnly declare that it is known to the Divine Majesty,
to the all-seeing wisdom whereby kings reign and princes decree justice,
that our manifold, extreme, and continued sufferings (being only on a religious account),
have not been the least motive or provocation to us to desire, much less to contrive,
the least harm, either to your person or government,
or to the person of your brother the duke of York.
We are clear in the sight of God, angels, and men, from all hellish plots,
traitorous conspiracies,
and from all murderous designs and undertakings against the king, his brother,
or any person on earth whatsoever, knowing such to be works of the devil and darkness,
and having contrariwise learned of Christ Jesus our Lord.
For we have been taught, by His light and grace in our hearts,
to not so much as defend by force, much less avenge ourselves from the injuries done us,
but rather to commit the cause to Him that judges righteously,
as peaceable followers of our Savior and Redeemer, in His patient example and sufferings,
who is the Prince of Peace.

O king, we do further declare,
that God Almighty has taught and engaged us to acknowledge,
and actually to obey magistracy, as His ordinance,
in all things that are not repugnant to His law and light in our consciences,
which is certainly agreeable to the holy Scripture,
and admits not of any immoral or injurious actions.
And even where, through tenderness of conscience, we cannot conform,
it is our duty patiently to suffer, and not to rebel, nor seek revenge.
We hope, by His divine grace,
ever to demean ourselves as peaceable-minded Christians in our conduct,
under the civil government;
and as we do sincerely and with reverence confess to Divine power and
Providence in your restoration and the preservation of your person hitherto,
so our prayers and supplications are to the Almighty for your future safety and peace,
and that in a thankful remembrance of God`'s great mercies towards you,
you may be thereby obliged to show mercy,
and relieve the oppressed from these unmerited afflictions and persecutions,
which a great number of us do even at this day suffer under, in our persons and estates.
And our sufferings are not only because of laws made against,
but also because of laws never intended against us;
and (what is even more extreme) several severities have recently been,
and are still inflicted upon us, for which no pretense of law has been or can be alleged.
Several jails are now so filled, as that they lack air,
and many innocent persons are held under extreme distress, without regard to age, sex,
or condition, to the loss of some lives already, and the apparent hazard of many more.
Many houses, shops, barns, and fields, have been ransacked and swept of goods, corn,
and cattle, tending to the great discouragement of trade and husbandry,
and to the impoverishing of a great number of quiet and industrious people;
and this for no other cause,
but for their religious worship and exercise of their tender
consciences towards Almighty God that made them,
who is the sovereign Lord of all, and the King in men`'s consciences.

Therefore we humbly entreat you, O king, in princely justice, christian charity,
and compassion, to open our prison doors and take off our bonds,
wherever the innocent are oppressed in your land--men and women who fear God, and,
in their conduct, truly honor the king.
Let not the ruin of such as are quiet in the land,
the widows and the fatherless for their peaceable consciences,
lie at the door of a prince who professes the tender and compassionate religion of Christ.

This address was presented to the king at Windsor, on the 8th of the month called August,
in this year, by George Whitehead, Alexander Parker, Gilbert Latey, and Francis Camfield,
on behalf of themselves and their friends.
It was read to the king and his brother the duke of York,
who was then present with some others, but no considerable ease followed.
King Charles, it seems, was not to be the instrument to alleviate their sufferings;
and though this prince was not hard-hearted by nature,
yet there were some that could persuade him to severity.

I find about this time that Gabriel Shad, mentioned previously,
who had made it his business to serve as an informer against the Quakers,
and who had lately informed against G. Fox,
was confined in Newgate prison in London for stealing goods
from one William Leman to the value of three hundred pounds.
But though he was found guilty of felony at the Old Bailey,
he had such friends in power that he was freed from the gallows;
and having obtained the benefit of the clergy,
was discharged with only being burnt in the hand.
Such infamous persons were these informers;
for honest people scorned to meddle with such a base and abominable work.

This year the princess Anne, daughter of the duke of York,
was married to prince George of Denmark.
The duke of Monmouth^
footnote:[James Scott, 1st Duke of Monmouth (1649-1685),
was the illegitimate son of King Charles II and his mistress Lucy Walter.]
having been under disgrace, came into favor again;
for his father the king indeed loved him, though he was reluctant,
in preference to his brother the duke of York, to declare him his legitimate son,
as some great men wished he had.
But the king persisted in his declaration,
that he never had been married to Monmouth`'s mother.

In the next year, 1684, G. Fox and Alexander Parker,
came into Holland to visit their friends there; and after some stay,
they returned to their native country.

In this year died Thomas Stordy of Moorhouse in Cumberland,
a gentleman who twenty-two years before had been condemned to a premunire,
because for conscience-sake he could not swear.
Because of this, sheriff John Lowther seized his estate, real and personal,
for the king`'s use, and kept him prisoner eleven or twelve years,
until he was at last discharged by the king`'s declaration in 1673,
and his real estate was restored.
After this,
he suffered under great fines and spoiling of his goods for attending meetings,
and later was prosecuted on the act for twenty pounds
a month for not coming to their worship.
On this charge he continued a prisoner several years, till he died in December,
having been made willing rather to lose all for Christ`'s sake,
than to be disobedient to Him.
This Thomas Stordy also released to the land-owners, and to their heirs forever,
an impropriation of ten pounds per annum,
which had descended to him from his father and grandfather,
showing that he was conscientiously opposed both
to the receiving and the paying of tithes.
Not long before his decease, he exhorted those who had come to visit him to faithfulness;
"`For,`" said he, "`if you continue faithful to the Lord while you live in this world,
He will reward you, as He now rewards me, with His sweet peace.`"
Thus piously Thomas Stordy departed this life,
showing forth that he was really a gentleman,
whose chiefest nobility consisted in virtue.
I could mention some other instances, or cases of persecution,
but to make more speed towards a conclusion,
I will not detain my reader with the relation thereof.

Thomas Briggs, who also had suffered very much,
having been one of the first preachers among the Quakers, now grew old and weak.
About this time he wrote a letter to G. Fox,
in which he signified his perseverance in godliness; and not long after,
about the beginning of the year 1685, he died.

It was about this time also that the king was seized with violent fits of convulsion,
and died in the month called February.
The throne becoming vacant by his death,
was filled again by his brother James II who succeeding him,
and who was the same day proclaimed king.
Now I cannot help but notice, that persecution went on up to the death of king Charles,
and continued very hot to that very instant.
And he having gone off the stage, many seemed to fear that worse times were at hand,
and that burning of heretics would come again into vogue, as in the former ages.
Yet there were some who believed that ease was likely to follow;
and time showed that they guessed not amiss.
