== Chapter XXI

[.section-date]
1685--1688

King James had not long been at the helm of the government,
when the dissenters applied to him for liberty of worship,
and among these were also the Quakers, who made the following petition:

[.embedded-content-document]
--

To the King and both houses of parliament:
humbly presenting the suffering condition of the peaceable people called Quakers,
only for tender conscience towards Almighty God.

Showing, that of late more than one thousand five hundred of the said people,
both men and women, having been detained prisoners in England, and part of them in Wales,
(some of which being since discharged by the judges, and others freed by death,
through their long and tedious imprisonment), so that there are now remaining,
according to the latest accounts,
about one thousand three hundred and eighty-three prisoners;
two hundred of which are women.
Many of these are under sentence of premunire, both men and women,
and more than three hundred are near to it; not for denying their duty,
nor for refusing the substance of the oath of allegiance itself,
but only because they dare not swear.
Many are under writs of excommunication and fines for the king,
or under the act for banishment,
besides above three hundred and twenty who have died in prison since the year 1660,
thereby making widows and fatherless, and leaving them in distress and sorrow.
The last two hard winters, and the close confinement of great numbers in many jails,
unavoidably tended towards their destruction,
their health being evidently impaired thereby.

And here in London,
the jail of Newgate has been from time to time crowded within these last two
years (having sometimes near twenty in one room) to the prejudice of their health;
and several poor innocent tradesmen of late have
been so suffocated by the coldness of the prison,
that they have been taken out sick of a malignant fever, and died a few days after.

Besides these long-continued and destructive hardships
upon the persons of men and women as aforesaid,
great violence, outrageous distress,
and woful havoc and spoil have also been (and still
are) frequently made upon our goods and estates,
both in and about this city of London, and other parts of this nation,
by a company of idle, extravagant, and merciless informers,
through their prosecutions upon the conventicle act;
many of our people being convicted and fined without
being summoned or heard in their own defense.
All of this has tended to the ruin of trade, husbandry, and farmers,
and the impoverishing of many industrious families, without compassion shown to widows,
fatherless, or desolate.
To some not a bed has been left to rest upon; to others,
no cattle has been left to till their ground, nor corn for bread or seed,
nor tools to work with.
The said informers and sheriffs`' bailiffs in some places
being outrageous and excessive in their distresses,
and seizures, breaking into houses, and making great waste and spoil.
And all these and other severities are done against us by
them under pretense of serving the king and the church,
thereby to force us to a conformity without inward
conviction or satisfaction of our tender consciences,
wherein our peace with God is concerned.

[.offset]
The statutes on which we, the said people, suffer imprisonment, distress, and spoil,
are as follows:

[.syllogism]
* The 5th of Elizabeth ch. 23+++.+++ De Excommunicato Capiendo.
* The 23rd of Elizabeth ch. 1, for twenty pounds per month.
* The 29th of Elizabeth ch. 6, for continuation.
* The 35th of Elizabeth ch. 1, for abjuring the realm, on pain of death.
* The 1st of Elizabeth ch. 2, for twelve pence a Sunday.
* The 3rd of King James I. ch. 4, for Premunire, imprisonment during life, and estates confiscated.
* The 13th and 14th of King Charles II. against Quakers, etc. for banishment.
* The 22nd of King Charles II. ch. 1, against seditious conventicles.
* The 17th of King Charles II. ch. 2, against nonconformists.
* The 27th of King Henry VIII. ch. 20, some few suffer thereupon.

Upon indictments at common law,
pretended and framed against our peaceable religious assemblies for riots,
breaches of the peace, etc. many, both men and women, have thereupon been fined,
imprisoned, and detained for non-payment, some till death.
Take for instance the city of Bristol,
where a great number have been for several years straitly confined and crowded in jail,
mostly above one hundred persons at a time on such pretenses,
about seventy of them women, many aged.
And in the city of Norwich, in the years 1682 and 1683,
about seventy were kept in prisons,
forty-five of which were put in holes and dungeons for many weeks together,
where they have suffered great hardships.
So that our peaceable meetings are sometimes fined
on the conventicle act as for a religious exercise,
and other times they are persecuted under common law, as being riotous,
etc. when nothing of that nature could ever be proved against them,
there being nothing of violence or injury either done, threatened, or intended,
against the person or property of anyone whatsoever.

The long and tedious imprisonments are chiefly upon the writs _de excommunicatu capiendo_,^
footnote:[A writ ordering the imprisonment of an excommunicated
person until he or she submitted to the national church.]
upon the judgment of premunire, or upon fines said to be for the king.

The great spoil and excessive distresses and seizures
are chiefly based on the conventicle act,
and for twenty pounds a month, two-thirds of estates, and upon writs of _qui tam_.^
footnote:[A writ of __qui tam__ is where a private party brings a lawsuit
against an individual on behalf of the king or government.]
In some counties many have suffered by seizures and distresses from eight years previous,
and writs have been issued for further seizures in
several counties for twenty pounds a month,
amounting to the value of many thousands of pounds,
sometimes seizing for eleven months at once,
and making sale of all goods and possessions, within doors and without,
both of household goods, beds, shop-goods, cattle, etc.
Prosecution hereupon still continues, and in several counties has much increased,
so that several who have long employed some hundreds of poor families in manufacturing,
and paid considerable taxes to the king,
are greatly disabled from both by these writs and seizures,
as well as by long imprisonments.
Many weavers in Plymouth, who kept above five hundred poor people at work,
are disabled by imprisonment.
There are many in the county of Suffolk who suffer long imprisonment,
and are sentenced to a premunire,
one of whom employed at least two hundred poor people
in the woolen manufacture when he was at liberty.
Omitting other instances, that we may not seem too tedious,
these may evince how destructive such severities are to trade and industry,
and ruinous to many poor families.

By means of the conventicle act,
within these last two years many in and about this
city of London have been extremely oppressed,
impaired, and spoiled in their estates and trades,
upon numerous convictions and warrants made against them in their absence,
merely upon information sworn by informers,
several of whom being impudent women who swear for their share of the fines and seizures,
their husbands being prisoners for debt through their own extravagancies.
The warrants commonly made to break open and enter houses,
are carried out with rigor and great spoil, not sparing widows, fatherless,
or poor families who are sustained by their daily care and industry,
and often not leaving them a bed to lay upon.
The fines upon one justice`'s warrants amounting to many hundreds of pounds;
frequently ten pounds a warrant,
and two warrants at once for twenty pounds executed upon one person.
Three warrants were executed at once from another justice
for the amount of sixty pounds upon another person,
and all his goods were carried away in about ten cart loads;
and five warrants at once for the amount of fifty pounds upon another,
etc. besides what we have suffered by others in the like kind.
And in this destructive course, the informers receive encouragement,
and are allowed to go on,
to the ruining of many families in their trades and livelihoods;
several becoming so discouraged and disabled that they are
forced to give over their shops and trades.

These informers are commonly accepted as credible witnesses,
yet they clearly swear for their own profit and gain,
and often in the absence of the persons who are being prosecuted.
This we think a very hard and undue proceeding,
and not consistent with common law or justice.
Now whether this be equal or just, we ask you please to consider,
you who are wise and judicious men; and whether it be for the king`'s honor,
and the people`'s interest, that idle, drunken, extravagant informers,
should be encouraged or permitted to go on thus to ruin trade, husbandry and families,
or to command and threaten justices of peace with the forfeiture of a hundred pounds
if they do not make convictions and issue out warrants upon their information,
and uncertain depositions, frequently in the absence of the accused.

Be pleased to make our case your own,
and do unto us as you would desire to be done to yourselves.
For as you would not wish to be oppressed or destroyed in your persons or estates,
nor have your properties invaded and posterities ruined for serving and
worshipping Almighty God according to your persuasions and consciences,
but would, no doubt, enjoy the liberty thereof,
so we entreat you to allow the same liberty to our tender consciences,
who live peaceably under your government.
And we ask you to be pleased to annul the said conventicle act,
to stop these devouring informers, and also to take away all sanguinary laws,
corporal and pecuniary punishments, merely on the basis of religion and conscience.
Let not the ruin and cry of the widow, fatherless, and innocent families,
lie upon this nation, nor at your door,
who have not only a great trust reposed in you for
the prosperity and good of the whole nation,
but also do profess Christianity, the tender religion of our Lord Jesus Christ.

And notwithstanding all this long-sustained oppression, we, the said suffering people,
do solemnly profess and declare in the sight of the all-seeing God,
who is the searcher of hearts,
that as we have never been found in any seditious or treasonable designs
(they being wholly contrary to our Christian principle and profession),
so we have nothing but good will and true Christian affection to the king and government,
sincerely desiring his and your safety, prosperity, and concurrence in mercy and truth,
for the good of the whole kingdom.

Having thus given you, in short, the general state of our suffering case,
in matter of fact, without personal reflection, we, in Christian humility,
and for Christ`'s sake,
entreat that you will tenderly and charitably consider the premises,
and find out some effectual way for our relief from prisons, spoil, and ruin.

--

[.offset]
The following application was likewise presented.

[.embedded-content-document]
--

[.letter-heading]
To King James the Second.

[.signed-section-context-open]
The humble application of the people called Quakers.

Whereas it has pleased Almighty God, by whom kings reign,
to take away the late king Charles the Second,
and to preserve you peaceably to succeed him;
we your subjects heartily desire that the Giver of all good and perfect gifts
may be pleased to endue you with wisdom and mercy in the use of your great power,
to His glory, the king`'s honor, and the kingdom`'s good.
And it being our sincere resolution, according to our peaceable principles and conduct,
by the assistance of Almighty God,
to live peaceably and honestly as becomes true and
faithful subjects under the king`'s government,
and a conscientious people that truly fear and serve God,
we do humbly hope that the king`'s tenderness will
appear and extend with his power to express the same;
recommending to his princely clemency,
the case of our present suffering friends hereunto annexed.

--

This annexed list, with the aforesaid petition to the king and parliament,
was not altogether ineffectual; for there was much talk now of liberty of conscience.
Many seemed to be in expectation that some grant of liberty would be published in print,
and thus it became a common saying that "`liberty of conscience
was in the press,`" which being of an equivocal signification,
sometimes afforded matter for jesting.
But many of the Episcopal church were so strongly
bent to withhold that liberty from other Protestants,
that there were reports of some in authority who had promised the
king to give their vote for liberty of conscience to the Papists,
provided it was not granted to other dissenters.
Nevertheless, the above-said petition of the Quakers had such an effect,
that the king resolved to ease the burden of their oppression by way of a pardon;
for his power reached thus far.
But the abrogating of laws could not be done without the consent of the parliament,
which grew concerned that by the repeal of those laws,
the Papists (who now had a king of their own persuasion) would become too powerful.
In the meantime the king published the following proclamation:

[.embedded-content-document.address]
--

[.salutation]
James R.

To all archbishops and bishops, to their chancellors and commissioners,
and to all archdeacons and their officials,
and all other ordinaries and persons executing ecclesiastical jurisdiction.

Whereas our most beloved brother, the late king,
had signified his intentions to his attorneys general for the pardoning such
of his subjects who had been sufferers in the late rebellion for their loyalty,
or whose parents or nearest relations had been sufferers
in the late rebellion for that cause,
or who had themselves testified their loyalty and affection to the government,
and yet were prosecuted, indicted, or convicted for not taking,
or refusing to take the oaths of allegiance and supremacy,
or had been prosecuted upon any writ, or any penalty for not coming to church,
or not receiving the sacrament:

In pursuance of the said will of our most dear brother,
and in consideration of the sufferings of the said persons, our will and pleasure now is,
that you cause all proceedings against the said persons to be wholly suspended and void.
And if any of the said persons be decreed or pronounced excommunicated,
or have been so certified, or are in prison upon the writ de __excommunicato capiendo__,
for any of the causes aforesaid,
our pleasure is that you absolve and cause such persons to be cleared, discharged,
or set at liberty,
and that no proceedings whatsoever be hereafter made in any court
against any of the said persons for any cause before-mentioned,
until our pleasure therein shall be further signified.

Given at our Court at Whitehall, this 18th of April, 1685,
in the first year of our reign.

[.signed-section-closing]
By his majesty`'s command,

[.signed-section-signature]
Sunderland

--

This was the king`'s first step towards liberty of conscience,
both for Papists as well as persons of other persuasions,
which put an effectual stop to persecution,
and the power of the informers was thereby much broken.
Thus the persecuted Quakers got some rest; for persecution not only ceased, but many,
who for religion`'s sake had been kept several years in prison,
obtained their liberty by the favor of a Popish prince,
something they had not been able to get from his Protestant brother,
king Charles the Second.
Now many of the fierce persecutors came to shame, some to poverty,
and others to a miserable end,
of which no small number of instances might be produced if I were of a mind to enlarge;
however I will only mention one or two.

There was one Edward Davis, who once professed to be a Quaker, but not being sincere,
had found that way too narrow for him, and so left his friends; and afterwards,
having become keeper of the jail of Ivelchester in Somersetshire,
he harassed them most grievously.
From mere malice he put some into iron fetters,
saying once to John Whiting when hand-bolting him to another,
that those bolts would not be taken off even if lice did eat them up.
And his comrade Joseph Newberry was but little better,
for when somebody told him that their hands did swell because of the irons,
he said he did not care if their hearts did swell also.
And when one John Dando once asked Edward Davis what
he thought would become of him when he died,
he answered, "`I know what will become of me then,
and therefore I will make the best of my time now.`"
He also signified that he knew where he had gone out,
and where he must come back in again, if ever he was to be saved;
but if he decided he would never return again, he would then be as wicked as he could.
Truly a most desperate saying!
As if the door of mercy continued always open for man,
and the day of the visitation of God`'s love never passed over his head,
though he persevered in rebellion.
But this Davis came to a most pitiful state, so that he fell into poverty,
and was himself imprisoned for debts, of which I will mention more hereafter.
And Joseph Newberry fell into a sad condition, being taken with a severe palsy,
and yet he did not leave off cursing and swearing,
and talking of the devil in a dreadful manner.
And by lying long in bed, the flesh began to rot on his back;
and he who had formerly said concerning the hand-bolted
prisoners that he did not care if their hearts did swell,
now got such a sore tongue, that it swelled out of his mouth and grew black,
and so he died miserably on the 10th of December.
Thus God sometimes punishes the wicked even in this life.
And though persecutors come not always to such a miserable end,
yet many of these fell into poverty,
and others were discontented because they saw that those whom they had cruelly persecuted,
now enjoyed an undisturbed liberty;
for the king who was now on the throne continued to give
liberty to those that had been oppressed for religion.

But before I say more of this,
I cannot but mention something of the plot of the unhappy duke of Monmouth,
who at the death of his father king Charles the Second, had gone to Brussels.
Having come from there into Holland,
he was spurred on so vigorously by some hot-headed Englishmen,
that having received money and assistance from various malcontents,
he gave forth a fiery declaration against king James (which was written,
as I have been credibly told, by the violent Robert Ferguson,^
footnote:[Robert Ferguson (1637-1714) was a Scottish Presbyterian minister,
a conspirator against Charles II and James II,
and a notorious writer of violent anti-government pamphlets.])
and went over to England with three men of war and some troops.
Monmouth having landed with his forces in the West of England, near Lime,
was afterwards routed by the king`'s troops and taken prisoner,
having been betrayed by a certain lord, who thereby obtained a pardon for himself.
Robert Ferguson, however, escaped by a cunning artifice,
crying out along the road where he came galloping on horseback, "`The rebels are routed,
the rebels are routed!`" as if he had been a courier sent on this errand.
Thus he escaped, and having afterwards come into Holland,
he told this crafty trick to his acquaintances.
Monmouth having been declared guilty of high treason by a bill of attainder^
footnote:[Legislation that could impose the death
penalty without a trial or judicial hearing.]
was beheaded but two or three days after his arrival at London.
I count it not unworthy to be mentioned, however,
that he undauntedly received the news of the death-warrant being issued;
and on the scaffold on Tower-Hill, he said to the bishops that accompanied him,
"`If I had not experienced true repentance,
I would not be so free from the fear of death.`"
And when it was objected that he ought not to rely too much on that,
since it might be the effect of natural courage, he said, "`No;
I do not ascribe this to my nature; for naturally I am more fearful than others;
but now I am freed from fear,
because I feel something in me which gives me assurance that I shall go to God.`"
The executioner gave him several strokes with the
ax before his head was at last severed from his body.
Some ecclesiastics afterwards said he died an enthusiast for not
showing himself very willing to comply with their services,
and for saying that something within him assured him that he should go to God.
But whatever it was, yet it seems very probable to me that he was a true penitent,
and so died in peace; for though I cannot but disapprove of his plot,
yet by true repentance it is possible that he not only obtained forgiveness of God,
but also had a full assurance of it.

It faired no better for the earl of Argyle, who rebelled in Scotland against king James.
But I will not detain my reader with this,
nor with a relation of the dismal execution of many who having
been found guilty of high treason (either for actual rebellion,
or for having been abetters of Monmouth) were sentenced
to death by the infamous George Jeffries,
who then was lord chief justice, and afterwards chancellor.
The fierceness of cruelty of this judge was such that some lost their
lives only for having given some hay or food to Monmouth`'s soldiers.
But this not being within my scope, I will pass it by, and go over to the year 1686.

Therefore leaving England, I will take a turn to Embden, in East Friesland,
where a small company of those called Quakers had
been under severe persecution for several years,
as I have hinted before.
But finding that the magistrates had been stirred up to
persecution by the instigation of their preachers,
the citizens began to be displeased with it.
And since the Protestants in France were now persecuted violently,
and a popish prince had mounted the English throne,
those at Embden grew more inclined to moderation.
Probably the decay of trade also contributed a little to this change;
for it appeared that the magistrates were now in
favor of getting more inhabitants into their town,
though they should be Quakers.
And this was counted a matter of such importance,
that the common council deliberated on the subject,
and two of the members of that board were sent to Magdalena van Loar,
an inhabitant of Embden,
requesting her to write to England and Holland that the magistrates of the city
had resolved to give liberty to the people called Quakers to live,
trade, and traffic there; which grant they offered to confirm by the city seal.

According to their request, notice was given to those of that persuasion at Amsterdam,
from which an answer being returned to the said Magdalena van Loar,
she gave it to the counsellor Polman, and he delivered it to the senate.
After some deliberation, the magistrates with the council of forty,
and the ecclesiastical court met together and came to a resolution,
of which a copy was sent to Amsterdam.
In this writing were mentioned some conditions upon which the magistrates at
Embden were willing to grant liberty to the Quakers to live in their city.
But the Quakers in Amsterdam, having weighed and duly considered the thing,
found that the proposal contained some expressions which might be used as snares
against the Quakers by others who might afterwards come into power.
They therefore thought it more safe not to enter
into any engagement upon such terms as were prescribed.
Yet it was concluded to acknowledge the good intention of the magistrates of Embden,
by drawing up the following letter and sending it to them.

[.embedded-content-document.letter]
--

[.salutation]
To the Lords, Burgomasters, Counsellors, and Rulers of the city of Embden.

This is to acquaint you, with due respect, that a plan of yours,
dated the 11th of February, 1686, has come to our hands, which having been perused by us,
we have thought it convenient in the fear of the Lord, to send you the following answer.

First,
we thank God Almighty for the ease and liberty which
our friends at present enjoy under your government,
and are likely to enjoy in the future.
And, secondly, we cannot but acknowledge very acceptably your clemency and meekness,
which you show by taking notice of the state of a despised and oppressed people,
who because their way and worship differs from the many ways in the world,
are opposed everywhere.
We are therefore the more stirred up in our minds to pray
fervently to the Lord God for your peace and prosperity,
and the continuance of your good resolution;
so that all those who serve the Lord in uprightness of heart
may lead a peaceable and godly life among you,
showing forth the fruits of true Christianity in truth, sincerity, and righteousness.

Now as to what you have been pleased to declare,
that you are willing to confirm the aforesaid good resolution by a public act,
we let you know,
that we are so well-satisfied with your word and
oral declaration concerning the aforementioned thing,
that this is more to us than anything we could further desire,
knowing that good men think themselves bound by their good words to perform what is good.
And since you are sensible on what ground you came to the aforesaid resolution,
we doubt not but that the same persuasion and reason continuing with you,
will prove a more strong engagement to you to perform the same,
than any outward seal can be.

And as to what you request of us,
we declare in the nakedness and simplicity of our hearts,
that in regard to our temporal conduct and deportment,
we desire no protection further than we are willing to deal righteously to all,
and walk according to the golden rule,
doing unto all men what we desire should be done to us.
And concerning our religion and worship, which we believe we owe to Almighty God,
we have found that since it differs from other persuasions,
it makes us obnoxious not only to the mocking and reviling of ignorant people,
but also exposes us to the malice and envy of many who hate us without a just cause.
For this reason we stand in need of your favorable interpretation,
and your best construction of what we do, and what we leave undone.
And if we should err in these matters, then we shall be the greatest losers by it;
and if truth be on our side, then our adversaries shall not be able to prevail;
for truth is the strongest, and it is not good for any to fight against it.
We therefore hope you will be pleased,
if we behave ourselves peaceably and honestly towards you and all men,
to let us be partakers with our peaceable neighbors of your general protection.
And though you desire to give us a public act of your aforesaid resolution,
yet we clearly foresee that our enemies, by twisting some or other of the words,
or by a wrong interpretation of the expressions contained therein,
may be able to make us appear guilty of transgression, and so find matter against us.

We therefore think it very safe to rely on your word and good resolution,
in which it has pleased you to declare that we shall
enjoy liberty to live and trade in your city,
provided we pay customs and taxes, which other citizens are subject to;
and that then we shall be at liberty to meet together to worship
God in such a way as He has convinced us we ought to do,
and to call upon Him, and to exhort one another to love and good works,
and a Christian conduct.
And on your behalf it will tend to the praise of the magistrates,
that you favor us in this.
And it will also be to the promoting of God`'s glory, and will oblige us to pray for you,
that the Lord God may be pleased to preserve you,
and to make you continue in such a good, wholesome, and well-grounded resolution.
We are, and rest,

[.signed-section-closing]
Your true friends and well-wishers,

[.signed-section-signature]
Barent Van Tongeren, William Sewel, Jacob Claus, Stephen Crisp, John Roelofs, John Claus,
Peter Hendriksz.

[.signed-section-context-close]
Amsterdam, the 9th of the Third month, alias March, 1686.

--

In answer to this,
the senate sent the following resolution to the subscribers of the aforesaid letter,
being, as appears by the contents,
the decree of the senate according as it was entered into their records,
of which the authentic copy, signed by the city`'s secretary, is in my custody.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Lunce 15 Marti, 1686.

Received a letter on the 12th of this month,
written at Amsterdam the 9th of the same month, and signed by Barent Van Tongeren,
William Sewel, Jacob Claus, Stephen Crisp, John Roelofs, John Claus, Peter Hendriksz,
in answer to our resolution of the 16th of February last,
with thanks for the promised admission and protection of this city, in their free trade,
and the exercise of their religion, without offending any; signifying thereby also,
that they will be content without an act under our seal,
and are willing to rely on our words.
This having been under deliberation, it was thought fit and resolved,
that our word shall effectually be kept to the subscribers,
and all others of their persuasion,
and that the promised protection shall be really performed.

[.signed-section-closing]
Ad mandatum senatus speciale,

[.signed-section-signature]
O+++.+++ Hillings, Sec.

--

Thus it pleased the senate of Embden to give those
called Quakers liberty to dwell among them,
with the free exercise of their religion.
Sometime after this it happened that the burgomaster Andrews,
coming to the house of Magdalena Van Loar,
and a preacher named Alardyn coming to the house of her daughter Magdalena Haasbaant,
both requested that they would cause what the senate had resolved to be sent to England,
that so it might be known there that if any of the Quakers`'
persuasion would come over and settle at Embden,
they should be well received there.

Hereby we see how God has the hearts of all men in His hands,
and that He turns them wheresoever He will.
For the magistrates of Embden some years before this,
from a blind zeal kindled by those who ought to have stopped it,
had given forth very severe edicts against the Quakers, and persecuted them fiercely;
but now they allowed them an entire liberty.

But leaving Embden, I return again to England,
where persecution at this time also came to a stand,
insomuch that the king ordered that all imprisoned
Quakers who were in his power to release,
should be set at liberty;
for those that were in prison for not paying tithes were under the ecclesiastical jurisdiction,
which was out of the king`'s reach.
But many others who had been in custody several years appeared
now in London for the annual meeting of their friends,
to the great joy of their brethren.
And when some of these went to thank the king for his favor, they were kindly admitted.
He thereby drew their inclination towards him; for his endeavors were now, as he said,
to bring about a complete liberty of conscience.
What exactly his aim was, I cannot say, for he never attained it.
But in the meantime he made persecution generally to cease, not only in England,
but also in other places of his dominions.
For having heard that the Quakers in the isle of Barbados, in the West Indies,
were very much molested because for conscience-sake they could not bear arms,
he ordered some of the members of his council to write the following letter:

[.embedded-content-document.letter]
--

After our hearty commendations,
his majesty having been pleased to refer unto us
the petition of the Quakers inhabiting Barbados,
we have thought fit hereby to request and require you to examine
the allegations of the said petitions and papers hereunto annexed.
And in as much as his majesty, having lately extended his favor to this people here,
is inclined to continue the same towards them in this case,
we desire you to report unto us what ease may be
given them in reference to the militia act,
and the penalties thereby imposed,
as far as it may consist with the safety of the island and the preserving of the militia,
according to the intention of the said act.
And so we bid you heartily farewell.
Your loving friends,

[.signed-section-signature]
Jefferies, Craven, Albemarle, Middleton.

[.signed-section-context-close]
From the Council chamber, Whitehall, the 23rd July, 1686.

--

From this letter it appears plainly that the king endeavored to relieve
the Quakers from the burden of persecution that they were under.
The following letter is also a proof of this intention,
written by the earl of Sunderland, then president of the privy council,
to the earl of Huntington,
to stop the persecution in Leicestershire and Nottinghamshire
where one John Smith had acted most grievously.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Whitehall, Dec. 7, 1686.

[.offset]
To the right honorable earl of Huntingdon,
one of his majesty`'s most honorable privy council, chief recorder of Leicester,
keeper of the records of the county of Leicester.

[.salutation]
My Lord,

The king being informed that one John Smith, a common informer,
does very grievously persecute the Quakers in the county
of Leicester and in the town and county of Nottingham;
and his majesty being pleased to extend his favor to those of that persuasion,
his majesty would have your grace direct the justices of
peace to give no sort of countenance to the said John Smith,
and his prosecution against the Quakers.

My lord, I am for his grace the duke of Newcastle,
one of his majesty`'s most honorable privy council, etc.

[.signed-section-closing]
Your grace`'s most faithful and humble servant,

[.signed-section-signature]
Sunderland, P.

--

The king being thus inclined to give liberty to prisoners who were in custody for religion,
neglected no opportunity to obtain it; of which the following petition is an evidence.

[.embedded-content-document.legal]
--

[.letter-heading]
To chief Justice Herbert and judge Wright,
assigned to hold court session and jail-delivery for the western circuit,
at Wells for the county of Somerset, the thirtieth of the month called March, 1686.

[.salutation]
Several of the people called Quakers, now prisoners in the jail at Ivelchester,
in the county of Somerset, on behalf of themselves and many others of the same people,
in humility show:

That since the wise Disposer of all things has ordered your employment
in this honorable service to relieve the oppressed and deliver the captives;
and since king James II has committed part of his clemency to your custody,
to distribute the same according as the Lord has inclined his heart;
and having taken particular notice of our sufferings,
and signified his will and pleasure, that we, the people commonly called Quakers,
should receive the full benefit of his general pardon,
with all possible ease (which grace and favor we with all
thankfulness acknowledge to God as the chief author,
who has the hearts of kings at his disposal; and to the king,
as being ready herein to mind that which the Lord inclined his heart unto);
and also hearing the report of your nobility and moderation
in managing this weighty trust committed to you,
we are emboldened thus to address ourselves, though in plainness of speech,
yet in sincerity of heart, to lay before you our case.
We have for several years been prisoners in the aforesaid jail,
not for any plotting against the king or government, or harm done to his subjects,
(for our peaceable lives have manifested our fidelity to the king and love to our neighbors,
it being contrary to our principles to do otherwise), but only for conscience-sake,
because in obedience to Christ Jesus we dare not swear at all,
nor cease to worship God as He has ordained,
nor conform to a worship in which we have no faith; for if we were to omit the former,
or practice the latter, we should therein sin, and so wound our consciences,
and break our peace with God.
And then what good would our lives do us,
even if we might enjoy ever so much of the world`'s favor and friendship?

Our humble request therefore to you is,
to consider and have compassion for our suffering condition,
and to use the power and authority that God and the
king has entrusted you with for our relief and liberty;
knowing that we, through God`'s assistance,
heartily intend to continue manifesting our fear to God, honor to the king,
and honesty to all his subjects, by our godly, humble, and peaceable conduct.
The particular causes of our imprisonments are herewith attested,
under our jail-keeper`'s hand.
And we further request, that all mercenary informers,
and those who enviously persecute us only for conscience-sake, may,
according to your wisdom and prudence,
be discouraged from prosecuting such actions by which many industrious
and conscientious families and persons are in danger of being ruined.
Thereby we will also be encouraged in our diligence in our respectable callings,
and may enjoy the benefit of our industry,
and so shall be the better enabled to perform with cheerfulness the duties we owe to God,
the king, and all men.
The Lord guide you in judgment, and more and more incline your hearts to love mercy,
and do justice, and may He grant you the reward thereof,
which is truly our desire and prayer.

--

This petition was signed by sixteen persons, some of whom had been imprisoned fifteen,
others ten, and some fewer years;
and along with the length of their imprisonment was
added the account for which they had been imprisoned,
that is, for premunire, excommunication, tithes, etc.
This petition had such an effect, that chief justice Herbert discharged these prisoners;
nevertheless, before this was done, several of those who had been imprisoned there died.
Many were also set at liberty by the king`'s proclamation;
and it was indeed so unusual a thing for this people to enjoy such a free liberty,
that it seemed the malicious persecutors were restrained by a higher power.

George Fox was now mostly in and about London,
endeavoring to bring all things among his friends into good order;
and since he could not be everywhere in person, he therefore wrote several papers,
in addition to discharging his duty by word of mouth.
And lest carelessness should creep in, by reason of the liberty that was now enjoyed,
he wrote the following epistle to his friends:

[.embedded-content-document.epistle]
--

[.salutation]
Friends,

The Lord by His eternal power has opened the heart of the king, to open the prison doors,
by which about fifteen or sixteen hundred are now set at liberty;
and this has given a check to the informers,
so that in many places our meetings are pretty quiet.
So my desire is that both liberty and sufferings may all be sanctified to His people,
and that friends may prize the mercies of the Lord in all things, and to Him be thankful,
who stills the raging waves of the sea, and allays the storms and tempests,
and makes a calm.
Therefore it is good to trust in the Lord,
and to cast your care upon Him who cares for you.
For when you were in your jails and prisons,
then the Lord did by His eternal arm and power uphold you,
and sanctified these sufferings to you,
and unto some he had made their prisons as a sanctuary.
Indeed He tried His people, as in a furnace of affliction,
both in prisons and through the spoiling of goods.
And in all this the Lord was with His people,
and taught them to know that the earth was the Lord`'s, and the fulness thereof;
and that He is in all places, "`who crowns the year with His goodness,`" Psalm 65.

Therefore let all God`'s people be diligent and careful to keep the camp of God holy,
pure, and clean; and to serve God and Christ, and one another,
in the glorious peaceable gospel of life and salvation,
which glory shines over God`'s camp.
For His great prophet, and bishop, and shepherd is among or in the midst of them,
exercising His heavenly offices in them;
so that you His people may rejoice in Christ Jesus, through whom you have peace with God.
For He who destroys the devil and his work, and bruises the serpent`'s head,
is the heavenly foundation and rock for all God`'s people to build upon;
which was the holy prophets`' and apostles`' rock in days past,
and is now the rock of our age; which rock and foundation of God stands sure.
And upon this, may the Lord God establish all His people.
Amen.

[.signed-section-signature]
George Fox.

[.signed-section-context-close]
London, the 25th of the Seventh month, 1686.

--

In this year David Barclay died at Ury in Scotland.
Before his departure he uttered many excellent expressions indeed,
so that I may not omit to mention some particulars.
In the latter end of September, being past the 76th year of his age,
he was taken with a fever which continued two weeks;
and being much troubled with the gravel,^
footnote:[i.e. kidney stones]
his sickness was accompanied with much pain in urinating.
Two days before his death, feeling his weakness, and being in agony,
he said to his son Robert who was with him, "`I shall now go to the Lord,
and be gathered to many of my brethren who have gone before me.`"
On the 11th of October, very early in the morning, growing weaker,
the said Robert Barclay signified to him that his prayer
was that He that loved him might be near him to the end.
To this David answered, "`The Lord is near;`" and further said to those about him,
"`You are my witnesses in the presence of God that the Lord is near.`"
And a little after he said, "`The perfect discovery of the Day-spring from on high,
how great a blessing it has been to me and my family!`"
Robert Barclay`'s wife asking if he would have something to refresh him,
he said it was not needed; and laying his hand upon his breast, he said,
"`I have that which inwardly refreshes me.`"
A little while after, he was heard several times to say,
"`The truth is over all;`" and taking his eldest son to him, he blessed him and said,
"`I pray to God you will never depart from the truth.`"
Then his son`'s eldest daughter coming near, he said, "`Is this Patience?`"
(for that was her name,) "`Let patience have its perfect work in you.`"
And after kissing the other four of his son`'s children,
he laid his hands upon them and blessed them.
The apothecary that attended him coming also near, he took him by the hand, and said,
"`You will bear me witness,
that in all this exercise I have not sought to tamper nor to pamper the flesh.`"
To which the apothecary said, "`Sir,
I can bear witness that you have always minded the better and more substantial part;
and I rejoice to see the blessed end the Lord is bringing you to.`"
To this, the sick man replied, "`Bear a faithful and true witness.
It is the life of righteousness, the life of righteousness it is,
that we bear testimony to, and not to an empty profession.`"
Then he called several times, "`Come, Lord Jesus, come, come!`"
And said also, "`My hope is in the Lord.`"

Afterwards he slept on and off for some hours,
and seeing a carpenter coming into the room, he said to his son,
"`Be sure you charge him to make no manner of superfluity on my coffin.`"
In the afternoon several of his friends came to see him, which he having observed,
said they had come at a seasonable time.
After some words were spoken, and Patrick Livingston had prayed, which ended in praises,
the sick old man held up his hands and said, "`Amen, amen, forever!`"
And after those who were present stood up he said,
"`How precious is the love of God among His children, and their love to one another!
Thereby shall all men know that you are Christ`'s disciples, if you love one another.
How precious a thing it is to see brethren dwell together in love!
My love is with you.
I leave it among you.`"
Several of his friends, pretty late at night, stood around his bed,
and he perceiving some of them to weep, said, "`Dear friends, all mind the inward man,
heed not the outward.
There is One that does reward, the Lord of Hosts is His name.`"
The next morning, after he had heard the clock strike three, he said,
"`Now the time comes.`"
And a little after he was heard to say, "`Praises, praises, praises to the Lord!
Let now Your servant depart in peace.
Into Your hands, O Father, I commit my soul, spirit and body!
Your will, O Lord, be done in earth as it is in heaven.`"
These sentences he spoke by little intervals, one after another;
and soon after five in the morning, the 12th of October, he slept in peace and quiet,
there being present at his end above twenty persons
who were witnesses to what has here been related.
His corpse was attended to the grave by numerous people;
and though he had ordered that not many be invited to his burial,
yet a great number of the gentry came uninvited,
from the esteem they bore to his memory.

In this year also Anne Downer departed this life,
one of the first of those called Quakers in London.
She had been married first to Benjamin Greenwel,
and was afterwards the wife of George Whitehead.
Being taken ill, she removed to a place outside of London, and her sickness increasing,
she perceived it was likely to take her away.
When her ancient friend Mary Stout visited her, she asked if she knew her,
and Anne answered, "`Yes, very well, it is Mary Stout.
I have my memory very well, and my understanding is clear, though I am very weak;
but I am given up to the will of the Lord, whether to die or to live;
for I have been faithful to Him in what I knew, both in life and death.`"
Perceiving some to be troubled concerning her, she said,
"`There is no cause for you to be troubled or concerned; for I am well,
and am in peace.`"
Many Christian exhortations she gave on her dying bed,
and said to some of her friends who came to visit her, "`What,
do you come on purpose to see me?
I take it as a fruit of the love of God, and I pray that God bless your children.`"
To another she was heard to say, "`If I never see your face more, it is well with me.
God knows my integrity, and how I have been and walked before Him.`"
The evening before she died, she said to her husband George Whitehead,
"`The Lord is with me, I bless His name.
I am well.
It may be you are afraid I shall be taken away; and if it be,
the will of the Lord be done.
Do not trouble yourselves, nor make any great ado about me.
My dear, go to bed; go to rest; and if I should speak no more words to you,
you know the everlasting love of God.`"
She was heard also to say, that she had finished with all things in this life,
and she had nothing to trouble her, but was at true peace and felt easy every way.
A few hours before she departed, she said, "`Though I am in a dying condition,
yet it is a living death; for though weakness seizes the body,
yet my understanding is as clear as when in health.`"
Thus she departed this life quietly, about the age of sixty-three years,
having been a woman well-gifted and very serviceable to the church,
not only with wholesome exhortations,
but also by her Christian care for the sick and poor, and for widows and orphans,
who by her decease lost an eminent mother.

About this time George Fox wrote several general epistles,
some of which were pretty large, to his friends, exhorting them to shun strife,
to keep to mutual love and unity, and to mind true piety.
He also wrote many other edifying papers; and because the Papists now appeared openly,
and performed their worship publicly, and there was much talk of their praying to saints,
and by beads, etc., in the year 1687 he wrote the following paper concerning prayer,
not fearing to contradict openly that which he judged to be superstition,
though the king himself was of the popish religion.

[.embedded-content-document.paper]
--

Christ Jesus, when He taught His disciples to pray, said unto them, "`When you pray, say,
Our Father, who is in heaven, hallowed be Your name,`" etc.
Christ does not say that they should pray to Mary the mother of Christ;
nor does He say that they should pray to angels, or to saints that are dead.
Christ did not teach them to pray to the dead, nor for the dead.
Neither did Christ or His apostles teach the believers to pray by beads,
nor to sing with outward organs;
but the apostle said he would sing and pray in the Spirit,
for the Spirit makes intercessions;
and the Lord who searches the heart knows the mind of the Spirit.

To take counsel of the dead was forbidden by the law of God;
but they were to take counsel of the Lord.
And He has given Christ in the new covenant, in His gospel-day,
to be a counsellor and a leader to all who believe in His light.
Men are not to run to the dead in search of the living;
for the law and testimony of God forbids it.
The Jews who refused the running waters of Shiloh,
the floods and waters of the Assyrians and Babylonians
came over them and carried them into captivity;
and they who refuse the waters of Christ,
they are overflown with the flood of the world that lies in wickedness.
Those who asked counsel of stocks and stones,
their state was in the spirit of error and whoredom, and they played the harlot from God,
Hos.
4:12. And those who joined themselves to Baal-Peor,
and ate the sacrifices made to the dead,
provoked the Lord`'s anger and brought the Lord`'s displeasure upon them, Psal.
106:28-29. So here you may see, the sacrifices made to the dead were forbidden.
"`For the living know that they will die; But the dead know nothing,
and they have no more reward, for the memory of them is forgotten.`"
Eccles.
9:5. "`Woe to the rebellious children, says the Lord, that take counsel, but not of Me;
and that cover with a covering, but not of My Spirit, that they may add sin to sin.`"
Isa. 30:1

[.signed-section-signature]
George Fox.

--

On the 20th of the month called March, Robert Widders,
one of the first preachers among those called Quakers, died.
G+++.+++ Fox was now much in London; but he grew more and more weak in body,
having endured many hardships and cruel imprisonments for the truth.
Sometimes he went into the country to take the fresh air,
and at other times he was awhile at the country-house of his son-in-law, William Mead,
who married one of his wife`'s daughters.
In the meantime he wrote much, for he was of a laborious temper,
and did not fail under all his business to visit the meetings of his friends,
and to edify them by his admonitions and exhortations.
For now they were permitted to keep their meetings unmolested, since the king,
in the month called April,
published his long expected declaration for liberty of conscience to all his subjects,
which contained:
"`That henceforth the execution of all penal laws concerning ecclesiastical matters,
for not coming to church, for not receiving the sacraments,
or for any other non-conformity with the established religion,
or for performing religious worship in any other way, should be suspended,`" etc.

It would indeed have been more acceptable if this
liberty had been established by the king and parliament,
this being granted as yet only by virtue of his royal prerogative; but nevertheless,
a real liberty was enjoyed,
whereby dissenters were permitted to perform their worship freely,
provided their preaching did not tend to make the minds of people averse to the government.
Thus friends in London,
seeing how other persuasions presented addresses of thanks
to the king for his declaration for liberty of conscience,
thought it convenient to draw up an address also, and present it to the king,
which was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To King James II, over England, etc.

[.offset]
The humble and thankful address of several of the king`'s subjects,
commonly called Quakers, in and about the city of London,
on behalf of themselves and those of their communion.

[.salutation]
May it please the king,

Though we are not the first to appear in this way,
yet we hope we are not the least sensible of the great favors
for which we have come to present the king our humble,
open, and hearty thanks; since no people has received greater benefits,
both by opening our prison-doors,
or by his late excellent and Christian declaration for liberty of conscience;
none having more severely suffered or stood more generally
exposed to the malice of ill men upon the account of religion.
And though we receive this act of mercy with all the acknowledgments
of a persecuted and grateful people,
yet we must say, it does the less surprise us,
knowing that it has been the declared principle of the king, both long before,
and since he came to the throne of his ancestors.

And as we rejoice to see the day that a king of England does, from his royal seal,
so universally assert this glorious principle that conscience ought not to be constrained,
nor people forced for matters of mere religion,
(the lack of which has been the desolation of countries, and a reproach to religion);
so we do with humble and sincere hearts render to God first, and to the king next,
our sensible acknowledgments.
And because our appreciation cannot be better expressed than by a godly, peaceable,
and dutiful life, it shall be our endeavor, with God`'s help,
to always prove ourselves the king`'s faithful and loving subjects;
and we hope that after this gracious step the king
has made towards the union of his people,
and the security of their common interest, has had a due consideration,
there will be no room left for those fears and concerns
that might render the king`'s reign uneasy,
or any of his subjects unhappy.

That which remains, great prince, for us to do,
is to beseech Almighty God (by whom kings reign,
and princes decree justice) to inspire you more and
more with His excellent wisdom and understanding,
to pursue this Christian design of ease to all religious dissenters,
with the most agreeable and lasting methods.
And we pray God to bless the king, his royal family and people, with grace and peace;
and that after a long and prosperous reign here,
he may receive a better crown amongst the blessed.

[.signed-section-closing]
Which is the prayer of, etc.

--

This address was received favorably,
and therefore some deputies from the yearly-meeting (which was
held in London a short time after) also prepared an address,
and went to Windsor where the court then was.
William Penn, being the one who had been chosen to present the address,
then made the following speech to the king:

[.embedded-content-document.address]
--

[.salutation]
May it please the King,

It was the saying of our blessed Lord to the captious Jews respecting tribute,
"`Render to Caesar the things that are Caesar`'s,
and to God the things that are God`'s.`" As this distinction ought
to be observed by all men in the conduct of their lives,
so the king has given us an illustrious example in his own person that excites us to it;
for while he was a subject, he gave Caesar his tribute; and now that he is a Caesar,
he gives God his due, that is, the sovereignty over men`'s consciences.
It would be a great shame then for any Englishman that professes Christianity,
not to give God His due.
By this grace the king has relieved his distressed subjects from their cruel sufferings,
and raised to himself a new and lasting empire, by adding their affections to their duty.
And we pray that God will continue the king in this noble resolution,
for he is now upon a principle that has a both a good nature, that is, Christianity,
and the goodness of civil society on its side.

I hope that none shall think we came here with the design to fill the Gazette^
footnote:[An early English newspaper, first published in 1665.]
with our thanks; but as our sufferings would have moved stones to compassion,
so we would be even harder, if we were not moved to gratitude.

Now since the king`'s mercy and goodness have reached
to us throughout the kingdom of England,
and principality of Wales, our assembly from all those parts,
which is now met together in London about our church affairs,
has appointed us to wait upon the king with our humble thanks, and me to deliver them.
This I do by this address, with all the affection and respect of a dutiful subject.

--

After W. Penn had spoken this much, he then presented the written address to the king,
who after kindly receiving it, gave it again to William Penn to read,
which was as follows:

[.embedded-content-document.address]
--

[.salutation]
To King James II over England, etc.

The humble and grateful acknowledgements of his peaceable subjects called Quakers,
in this kingdom, from their usual yearly-meeting in London,
the 19th day of the third month, commonly called May, 1687.

We cannot but bless and praise the name of Almighty God,
who has the hearts of princes in His hand,
that He has inclined the king to hear the cries of his suffering subjects for conscience-sake;
and we rejoice, that instead of troubling him with complaints of our sufferings,
he has given us so eminent an occasion to present him with our thanks.
And since it has pleased the king out of his great
compassion thus to commiserate our afflicted condition,
which has so particularly appeared by his gracious proclamation this last year
(whereby above twelve hundred prisoners were released from their severe imprisonments,
and many others from spoil and ruin in their estates and properties),
and by his Christian declaration for liberty of conscience,
in which he does not only express his aversion to all force upon conscience,
and grant all his dissenting subjects an ample liberty to worship
God in the way they are persuaded is most agreeable to his will,
but gives them his kingly word the same shall continue during his reign;
for all of this we do, as our friends of this city have already done,
render the king our humble, Christian, and thankful acknowledgements,
not only on behalf of ourselves,
but with respect to our friends throughout England and Wales.
We pray God with all our hearts to bless and preserve you, O king,
and those under you in so good a work;
and we can assure you that these things are well
accepted in the counties from which we came,
so that we hope the good effects thereof, in the peace, trade,
and prosperity of the kingdom,
will produce such a concurrence from the parliament
as will secure it to our posterity in after-times.

[.signed-section-closing]
His peaceable, loving, and faithful subjects.

--

[.offset]
After William Penn had read the said address, the king spoke as follows:

[.embedded-content-document.address]
--

[.salutation]
Gentlemen,

I thank you heartily for your address.
Some of you know, I am sure you do, Mr. Penn,
that it was always my principle that conscience ought not to be forced;
and that all men ought to have the liberty of their consciences.
And what I have promised in my declaration, I will continue to perform as long as I live;
and I hope before I die,
to settle it so that after-ages shall have no reason to alter it.

--

Here we see what the king declared to be his intention; but perhaps he did not consider,
that if such a general liberty had been procured,
he would not have been able to make it continue longer
than the popish clergy would have thought it convenient.
For who is ignorant what an unlimited power the Roman prelates have usurped,
not only in the ecclesiastical, but also in the political arena?
Insomuch, that though the king`'s intention might have been really sincere,
yet it is likely it would have been thwarted,
though he might have desired that it should be otherwise.
That his meaning was sincere, many indeed believed who were not of his persuasion,
and among these there were those who thought that
liberty of conscience might have been so established,
that it would not have been in the power of the Papists to break it.
But time has shown that king James was not to be
the instrument for settling such a liberty of conscience,
and that the repealing of the penal laws was reserved for another prince.
Yet the king was by some thought to have done what he could to stop the rapacious persecutors,
and to restrain their power with respect to imposing of oaths.
Some indeed said the king was unable to do do anything regarding the imposition of oaths;
for by granting this liberty to the Quakers,
he would open a door for the Papists to bear offices without taking the required oaths.
However, that he did discharge the Quakers from some oaths,
may be seen by the following order to the lord mayor of London:

[.embedded-content-document.legal]
--

[.salutation]
My Lord,

The king being informed that Edward Brooker, Henry Jefferson, and Joseph Tomlinson,
being Quakers, are by Mr. Barker, steward of Southwark, nominated for several offices,
as constables and the like, which they are willing to do;
but the oaths being tendered to them,
from which they think themselves exempted by the
king`'s declaration for liberty of conscience,
they are threatened to be fined and otherwise molested for their refusal to take them.
His majesty commands me to let your lordship know, that his pleasure is,
that the said Edward Brooker, Henry Jefferson, and Joseph Tomlinson,
and all other Quakers, should now, and for the future,
either be allowed to serve the said offices without taking any oaths,
or else that they be not fined or otherwise molested upon that account;
and his majesty would have you give order therein accordingly.

[.signed-section-closing]
I am, my Lord, your Lordship`'s most humble servant,

[.signed-section-signature]
Sunderland

--

Now whereas in some places goods taken from the Quakers still lay unsold,
the king ordered these goods to be restored to them,
as may appear by the following letter written to the mayor and aldermen of Leeds,
in Yorkshire:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Whitehall, December 14, 1687.

[.salutation]
Gentlemen,

The King being informed that some goods belonging to John Wales,
and other Quakers of Leeds,
which were seized and taken from them upon the account of their religious worship,
do remain unsold in the hands of John Todd, who was constable at the time of the seizure,
or in the hands of some other persons;
and as his majesty`'s intention is that all his subjects shall receive
the full benefit of his declaration for liberty of conscience,
his majesty commands me to signify his pleasure to you that
you cause the goods belonging to the said John Wales,
and all other Quakers of Leeds,
which were heretofore seized upon the account of religious worship, and are unsold,
in whose hands soever they remain,
to be forthwith restored to the respective owners without any charge.

[.signed-section-closing]
I am, gentlemen, your affectionate friend and servant,

[.signed-section-signature]
Sunderland

--

By such means some received back the goods which
had been taken upon the account of religious worship;
for in many places they lay long unsold, because few would buy goods so taken.
And that the king by these his favors drew the love
and affection of many of his subjects towards himself,
none need to wonder; for regardless of his religion,
he delivered them from a grievous burden under which
they had been oppressed for many years.
To this may be added, that he treated them kindly in all respects,
and would not allow his servants to molest any for not pulling
off their hats when they came near his royal person.
Indeed, so far went his condescension,
that when a certain countryman of the Quakers`' persuasion
came to him with his hat on his head,
the king took off his own hat, and held it under his arm; which the other seeing, said,
"`The king needs not keep off his hat for me.`"
To which the prince replied, "`You do not know the custom here,
for it requires that but one hat remain on.`"
I have been told of more similar occurrences, which I pass by;
but it appears from all this that the king endeavored to have among
the Quakers the reputation of a mild and courteous prince.
This year he also granted full liberty of conscience in Scotland,
and freed those who were still under sufferings,
allowing them the free liberty of their religious meetings.
The said liberty he also granted to the Presbyterians,
provided that they should not meet in the fields, or in sheds, as some did.

The king having thus granted liberty of conscience to people of all persuasions,
then did whatever he could to introduce popery in England;
for he permitted the Jesuits to erect a college in the Savoy in London,
and permitted the friars to go about publicly in the dress of their monastical orders.
This was a very strange sight to Protestants in England;
and it caused no small fermentation in the minds of people when the fellows of Magdalen
College at Oxford were by the kings`' order dispossessed in order to make way for Romanists.
This was such an open usurpation, that W. Penn did not omit to blame the king for it,
and to tell the him that it was an act which could not in justice be defended,
since the general liberty of conscience did not allow a depriving
any of their property who did what they ought to do,
as the fellows of the said college appeared to have done.
But this could not cool the king`'s zeal for popery,
for without disguise he drove on so fast, and to such a degree,
that the Pope`'s ambassador, Fernando d`'Ada,
made his public entry at Windsor this summer in very great pomp.

Great endeavors were now made to repeal the "`test and penal laws,`"^
footnote:[The "`test and penal laws`" were laws passed against Roman Catholics
in Britain and Ireland after the Reformation that penalized the practice of the
Roman Catholic religion and excluded them from holding public office.]
for if this point were gained,
then Papists might be admitted into the government as well as others.
Such a general liberty of conscience making an alluring show,
several dissenters (Baptists as well as others) served
the king with their pens on this account;
and W. Penn, who always had been a defender of liberty of conscience,
was also not inactive in this affair with good intent,
howbeit he might have failed in his expectation.
I remember when in those days the patrons of the church of Rome
asserted liberty of conscience to be a Christian duty.
In reference to this I heard one say, "`Can the Ethiopian change his skin,
or the Leopard his spots?`"
The king labored also to persuade the prince and princess
of Orange to give their assent to the repealing of the "`test
and penal laws,`" but this could not be obtained from them.
And since the king caused the advocate James Stuart^
footnote:[Sir James Stewart of Goodtrees (or Steuart; 1635-1713) was a Scottish lawyer,
political opponent of the Stuarts, and reforming Lord Advocate of Scotland.]
to write concerning this matter to Mr. Fagel (counsellor
and chief pensionary at the Hague),
Fagel answered this paper in a letter to the said James Stuart,
wherein he declared the judgment of the prince and princess in this case,
that they were willing to assent to the repealing of the penal
laws as far as they had any tendency to the exercise of worship,
but as for those that debarred Papists from sitting in parliament,
they could not give their assent to the repealing of such limitations.
This letter was generally approved by the Protestants in England,
but the king nevertheless went on with the introducing of popery;
and about the beginning of the year 1688,
he not only installed several Romanists at Oxford,
but also endeavored to usher those of his persuasion into the magistracy.
Now, to better cloak this design, he sought to have other dissenters also chosen;
but they generally rejected this offer, as did Stephen Crisp, at Colchester,
who was too prudent to be caught in this trap, and therefore declined the offer.

On the 27th of the month called April,
the king`'s declaration for liberty of conscience was published
again to show that he was firm and constant in his resolution,
and that his intentions had not changed since he first issued it.
He sought also to excite his subjects to join in with it,
and to choose such members of parliament as might
do their part to finish what he had begun.
Now, to this declaration was annexed an order of the council that it
be read in all churches and chapels throughout the kingdom;
also ordering the bishops to send and distribute the declaration
throughout their several dioceses to be read accordingly.
This, however, they refused to do, alleging that it was not legal,
though some of these bishops were no doubt opposed to liberty of conscience.
Then the archbishop of Canterbury and six other bishops petitioned the
king not to insist upon the distribution and reading of his declaration;
asserting that their great averseness to the distribution and publication of it in their
churches proceeded not from any lack of duty and obedience to his majesty,
nor from any lack of due tenderness to dissenters;
but only because such an order was founded upon such a dispensing
power as had been often declared illegal in parliament.

This refusal the king so resented, that he sent these bishops to the tower of London.
While they were thus confined, there was much discourse everywhere about this matter;
and since it was well known that some bishops had been the promoters of the former persecutions,
some it seems spoke also against these men that were now in confinement.
This being reported to them, they said that the Quakers slandered them,
proclaiming that they (the bishops) had been the cause of the death of some of them.
This gave occasion to Robert Barclay to visit the bishops in the tower;
and speaking with them, he gave them undeniable proofs of some persons who,
by order of bishops, had been kept in prison until their death,
though the bishops had been warned of the danger these persons
were in by physicians who were not Quakers.
This was so evidently manifested by R. Barclay, that the bishops were not able to deny it.
Nevertheless, Barclay told them that since they were now under oppression,
the intention of the Quakers was in no way to publish such matters,
lest thereby they should exasperate the king against them.
And indeed,
they were careful not to do anything that might aggravate the case of these prisoners;
for it was not the time to rub old sores,
since the bishops themselves seemed to be inclined to declare for liberty of conscience.
And since this liberty was now enjoyed all over the kingdom,
those called Quakers thought it convenient at their yearly meeting (which
was held this summer in London) to draw up again an address to the king,
and to acquaint him with one thing more which continued to be troublesome to them.
The address they presented to him was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To King James II over England, etc.

[.offset]
The humble address of the People called Quakers, from their Yearly-Meeting in London,
the 6th day of the month called June, 1688.

We, the king`'s loving and peaceable subjects, from various parts of his dominions,
having met together in this city after our usual manner to inspect
the affairs of our Christian society throughout the world,
think it our duty humbly to represent to him the blessed effects
which the liberty he has graciously granted his people has had,
both on our persons and estates.
For whereas formerly we regularly had long and sorrowful
lists brought to us from almost all parts of his territories,
telling of prisoners and the spoiling of goods by
violent and ill men upon an account of conscience,
we now bless God, and thank the king, the jails are everywhere clear,
except in cases of tithes and the repairs of parish churches, and a few about oaths.
We therefore, in all humility,
lay it before the king to consider the hardships our friends
are yet under for conscience-sake in these respects;
who on the one hand are exposed to the present anger of the offended
clergy who have lately imprisoned some of them till death,
and on the other hand are rendered very unprofitable both to the public and to themselves.
And as we humbly hope you may relieve as,
so we confidently assure ourselves you will ease us in whatever you can.

Now since it has pleased you, O king,
to renew to all your subjects your gracious intention to pursue the establishment
of this Christian liberty upon an unalterable foundation,
and in order to accomplish this, to hold a parliament next November,
we think ourselves deeply engaged to renew our assurance of fidelity and affection,
and with God`'s help intend to do our parts for the
completing of so blessed and glorious a work,
so that it may be out of the power of any one party
to hurt another upon the account of conscience.
And as we firmly believe that God will never desert
this just and righteous cause of liberty,
nor desert the king in maintaining it,
so we hope by God`'s grace to let the world see that we can honestly
and heartily appear in support of liberty of conscience,
and yet be entirely true to our own religion,
whatever the folly or malice of some men may suggest to the contrary.

--

This address being presented to the king, was well received.
Some have thought that the latter part of this address concerned the office of a magistrate,
which position, it is believed,
a Christian may serve with no more disparagement to an inoffensive life,
than it is inconsistent for a pious father to give
due correction to his rebellious child.
For though our Savior tells us not to resist evil, but to love enemies;
and when Peter from a forward zeal cut off the high priest`'s servant`'s ear,
Christ reproved him saying,
"`Put up your sword into the sheath;`" and though
the apostle James also disapproves of war and fighting,
yet we find in Scripture that the apostle Paul calls the magistrate,
a "`minister of God for good,`" and "`a revenger to execute
wrath upon him that does evil;`" saying in plain terms,
that "`he bears not the sword in vain.`"^
footnote:[Romans 13:3-4]

But to return to my relation,
and to take up again the thread of this history from
which I have been diverted a little by this digression;
I know there were some in those days,
who thought that if people of all persuasions in England had a share in the government,
proportionable to their number, a means might have been found out to hinder any party,
especially the Papists, from exalting themselves above the others.
But to me it seems not improbable, that if this had taken effect,
it would have appeared that these men did not reckon well.
However, it never came to this pass, for the king`'s power was tottering already,
though he endeavored to support it, even with good means.

There were now at Norwich, about forty of the people called Quakers,
who having petitioned the king that he would be pleased to cause them to be made freemen,
obtained the following order from him:

[.embedded-content-document.legal]
--

[.letter-heading]
To our trusty and well-beloved our Attorney-General.

[.signed-section-context-open]
James R.

[.salutation]
Trusty and well-beloved, we greet you well:

Whereas we have received a good report of the loyalty of our well-beloved subjects,
Thomas Howard, Peter Launce, William Booley, Henry Jackson, Edward Pears, John Jenn,
Nicholas Comfit, John Harridence, John Gurney, Samuel Wasey, Edmund Cobb, Philip Paine,
Josiah Sherringham, Anthony Alexander, Thomas Darmar, John Cadee, John Fiddeman,
William Kiddle, James Pooley, John Defrance, Jr., Daniel Sharpen, William Milchar,
William Brown, John Sharpen, Jr., Samuel Kettle, Stephen Ames, Richard Rose,
Benjamin Stud, Edward Monk, John Cornish, John Hodson, James Polls, Michael Parker,
Richard Brown, Daniel Dye, Jr., John Elsegood, John Pike, and John Allen,
we have thought fit hereby to require you forthwith to make all and every
one of the persons above mentioned freemen of our city of Norwich,
with all the rights and privileges belonging thereunto,
without tendering them any oath or oaths whatsoever,
with which we are graciously pleased to dispense on their behalf.
And for so doing this shall be your warrant; and so we bid you farewell.

Given at our court at Whitehall, the 13th day of July, 1688,
in the fourth year of our reign.
By his majesty`'s command.

[.signed-section-signature]
Sunderland

--

Many now said that the king had no right to do this;
and those who grudged the Quakers this liberty,
did not hesitate to set forth the king`'s order in very ill-favored colors; indeed,
they even claimed William Penn had advised the king
to do what he could not do without breaking his promise.
Yet if the king had made no greater infringement than this,
his reign might have lasted longer.
But his dispossessing of the fellows at Oxford, the imprisonment of the bishops,
and the public admittance of Jesuits and monks,
caused a great ferment in the minds of the people.
The seven bishops were now tried at the king`'s bench bar, in Westminster-Hall;
but they were acquitted, and so released.
The king also appointed some "`ecclesiastical commissioners,`"
but many looked upon this as a kind of inquisition,
and it seemed not well to agree with true liberty of conscience,
which if he had maintained justly,
it is not likely that he would have come to such
a difficulty as he soon found himself in.

Not long before this time, one Theophila Townsend, a woman of years and understanding,
published a book wherein she gave a relation of the grievous persecution her
friends in Gloucestershire had suffered by imprisonment and spoiling of goods,
and how she herself had also undergone many sufferings,
and had been imprisoned in the castle of Gloucester more than three years.
Among other things, she relates how, some time before her imprisonment,
she was seized in the street by order of justices Thomas Cutler and James George,
at which time she said to the latter that the Lord would plead her cause,
and that whatever measure he used would be measured back to him.
And it thus happened, that before she was released from prison,
the wife of the said James George, who had taken Theophila from her husband,
was taken from him by death.
Sometime after this, J. George came with the bishop of Gloucester into a meeting,
where Theophila was on her knees praying.
The bishop asking George whether she was the woman he had spoken of, and he answering,
"`Yes,
my lord;`" the bishop took her by the arm with such
violence that he almost pulled her down backward,
saying, "`Give over, woman, and obey the king`'s officers.`"
But such was her zeal, that her prayer could not be stopped;
for the more opposition she met with,
the more she felt herself encouraged and inspired to praise God for His goodness.
And though the bishop stirred up the justice,
yet it seemed not in his power to stop the current of her speech;
so that they let her alone until she finished and stood up.
Then the names of those who had met together were taken in writing,
and it was sometime after this that she, though aged and weakly,
was in the winter-season led three or four miles through the snow,
and committed to jail at Gloucester, where she was kept three years and four months,
and then released by king James.

Afterward she published a book, as has been said already,
in which she gave an account how some of her friends had been beaten, punched,
and abused to such a degree that they died of their wounds,
as she testified to have seen herself.
"`Yet,`" said she, "`though many died who were stronger than I,
it has pleased the Lord to preserve my life that I may speak to the praise of His name,
and tell of His wonders,
and put you persecutors once more in mind of what belongs to your peace.
Blessed be the Lord, He has risen for Zion`'s sake, which you have plowed long as a field.
And when their enemies have done their worst,
then the Lord shall make His Zion to be an everlasting glory,
and His Jerusalem the praise of the whole earth.
And as you can see in others that persecution is evil, so see it also in yourselves,
and repent in dust and ashes.
Remember who it was that said, '`the wise man`'s eyes are in his head,
but the fool walks in darkness.`' The eye of the fool looks out for mistakes in others,
and they blame in others what they are guilty of themselves.`"
Going on thus,
she reproved the informers who had enriched themselves with the spoils of their neighbors;
and she also related how the priest of Gloucester
had signed his name on a petition to the king,
in which justice J. George and others desired that the meetinghouse
of the Quakers might be given to the town,
to make a work-house for the poor.
"`But,`" said she, "`this is like Judas, who,
when the woman came with an alabaster box of very precious spikenard, said,
'`Why was this waste made?
Why was not this ointment sold and the money given to the poor?`' But the scripture says,
that '`this he said, not that he cared for the poor, but because he was a thief,
and held the bag.`'`"

Then speaking to those who had a hand in the spoiling of goods,
and setting forth the odiousness of that work, she said at last,
"`I do not write this from a spirit of revenge against any,
but in the love of God to warn you, and to exhort you to repentance,
that you may find mercy with the Lord, which is the real desire of my soul.
I can truly say, in the presence of the Lord,
that I have nothing in my heart but love and good-will to the worst of our enemies,
and this in purity of heart and in sincerity of mind.
I really desire your eternal peace and well-being,
though you have hardened your hearts against the Lord, and His truth and people.
Turn to the Lord, I beseech you.
Bow before the Almighty, who will plead with all flesh, and shall call all to an account,
and reward everyone according to what he has done in the body, whether it be good or bad.
Consider this therefore while you have time,
and mind the things that belong to your peace, before they are hidden from your eyes.
For the long-suffering of the Lord will come to an end, who said,
'`My Spirit shall not always strive with man.`' Therefore while the Spirit of the Lord,
His light, His grace, yet strives in your hearts to turn you from your evil ways,
be willing to embrace it, believe in it, take counsel of it,
submit to it with all your heart.
Be willing to be led and guided by it,
and incline your hearts to follow it in all things,
and then it will lead you to rest and peace with the Lord forever.`"
Much more she said, but I break off.
By such compelling speeches, sometimes persecutors have been so touched to the heart,
that they themselves have become harmless Christians.

I have almost come now to a conclusion of my relation concerning persecution;
about which I could have written much more,
but I was unwilling to extend my work beyond what I should have been well able to complete.
Yet before I altogether part with this matter,
I will mention something concerning Theophilus Green,
of whom mention has been made before.
He lived at Battersea, not far from London,
and was a man beloved of his neighbors because of his honest conduct;
yet he was much persecuted, both for attending meetings and for preaching.
Once it happened that some officers came to his house to see whether there was a meeting,
and they behaved themselves moderately;
for their coming there seemed to be contrary to their desire,
it being only in obedience to the order of justice Duke, who,
on account of a former offense, had issued warrants to seize goods.
These officers not feeling satisfied in the case, and seeing no meeting taking place,
went their way and returned the warrant.
T+++.+++ Green afterwards went to the said justice and said to him,
"`Consider what that mouth and tongue of yours has formerly said,
that I have always been kind to you.
And is this what you give in return?
Know for certain that the God whom I have served, and for whose cause I now suffer,
will avenge me; for vengeance is the Lord`'s, and He will repay it one way or other,
unless you speedily repent.`"
Hearing these words, the justice began to tremble, and crying out, said,
"`I will do you no more hurt than I will do my own soul!
Please,
go to the officers and tell them I will never trouble them again on your account.`"
Green did so; and the officers were glad of it.
But when this justice was later dismissed because of some complaint,
one Sir John Broadrick succeeded in his place,
and kept Theophilus and his friends out of their
meetinghouse for about two and a half years.

Afterwards they were permitted again to go into their meetinghouse,
but one justice Forster coming, and taking their names,
fined Theophilus 10 as a preacher.
After this,
the said justice and some others came with a constable to seize goods for the fine.
The constable having come to the door of the house, said, "`Neighbor Green, where are you?
We have come to seize your goods, if you will let us in.`"
But this so displeased the justice that,
looking over the property and seeing some oars and poles,
he required the constable to take them away.
To this the constable answered, "`I am no porter.`"
"`Then,`" said the justice, "`command some others to do it.`"
To which the constable replied, "`I command _you_ to do it.`"
This so enraged the justice that he fined him.

Some time after this,
justice Forster came again with a high constable
and another petty constable and seized a small boat,
and had it carried away, and several times sought to sell it, but none would buy it.
And after it had been carried about from place to place for sale,
at length it was found adrift by one who knew not of its being seized; and this man,
hearing that it was Theophilus`'s boat, brought it to him.
But Theophilus went to the constables and told them where the boat was,
and how it had come back to him, and said,
since it had come to him again he was willing to keep it;
but if they took it away again he would not hinder them.
This account being given to the justice,
he sent a warrant and committed Theophilus to the Marshalsea prison.
After three weeks the court session was held at Marshalsea;
and upon the last day the said justice came to him in the prison, saying,
"`I have come out of love to see you, and to advise you for your good; which is,
that you pay your fine.
For I am sure the grand jury has decided against you; and if you are released,
I have such an influence with the judge as to cause the oath to be tendered to you;
and I know you will not take it.
Then you will be forced into a premunire,
and are not likely to come out of prison as long as you live.`"
To which Theophilus answered, "`You said your coming was in love,
to advise me for my good; but by what you have said, it appears the contrary;
for now I perceive you have devised as much mischief against me as you can.
As to the fine, if it were but ten pence, I would not pay it.
And if the Lord should permit you to do as you have said,
and so be the cause of bringing my grey hairs the sooner to the grave,
my blood will be at your door, and will cry out for vengeance against you.`"

The next day the two constables being called before the grand jury,
were asked what they had against Theophilus Green.
The high constable answered, "`As for Theophilus Green, though a Quaker,
he is as honest a man as lives about us.
He was lately in office for the poor,
and behaved himself as well in it as any has done these last twenty years.
And regarding the boat he is indicted for, when it was returned to him,
he came to us and told how it came, and where he had laid it, saying,
if we would take it away again he would not hinder us.
This is all we have to say.`"
Some of the grand jury knew Theophilus very well, and the cause too,
which did not much work in the justice`'s favor; and as for the indictment,
they brought it in _ignoramus_.^
footnote:[The decision of a grand jury that there is not evidence to support the charges,
upon which all proceedings are stopped, and the accused person is discharged.]
So Theophilus was cleared by proclamation; and sir Richard How, being one of the jury,
advised him to prosecute the justice, there being two clear charges against him, namely,
defamation and false imprisonment.
But Theophilus said he acknowledged their love,
but would leave the thing to the Lord for whose cause he suffered;
for vengeance was the Lord`'s, and He would repay.
And it was but a little time after this that the said justice Forster died,
as was reported, in great horror and misery.
The time when this happened I do not exactly know,
yet I take it to have been some years before the time I now describe.

Before I conclude this year I must mention something concerning William Penn,
who when the government of king James was sinking,
not only bore the blame of many miscarriages, but by some was called a Papist,
though this was altogether false.
But Penn had a great many enemies;
and it was no new thing to brand the Quakers with the odious name of Jesuits;
for thirty years before this time, in Bristol,
great endeavors were used to persuade people they were Franciscans.
William Penn patiently bore the slander of being decried as a Papist,
saying little in justification of himself,
till at length he made a reply to a letter sent by one who seriously begged of him to
give an answer to those accusations that had been forged against his reputation.
In this paper he ascribed his free access to the
king as partly due to the relation his father,
as admiral,
had had in the service of the king when still duke of York and high admiral of England;
also do his favor in releasing him out of the tower of London in the year 1669.
To this he added:

[.embedded-content-document.paper]
--

My father`'s humble request to him upon his deathbed, was,
to protect me from the inconveniences and troubles
that my religious persuasion might expose me unto;
which he kindly promised to do, and also performed exactly.
When all of this is considered, anybody that has the least pretense to good-nature,
gratitude, or generosity, must necessarily know how to interpret my access to the king.
Is there, therefore, anything more foolish as well as false, than to suggest that,
because I am often at Whitehall,
I must be the author of all that is done there that does not please people abroad.
But supposing some such things to have been done;
please tell me if I am bound to oppose anything I am not called to do.
I never was a member of council, cabinet, or committee,
where the affairs of the kingdom are transacted.
I have had no office or trust,
and consequently nothing can be said to have been done by me.
And unless calling at Whitehall once a day, upon many occasions,
or my not being turned away, be the evidence of my compliance in disagreeable things,
I know not what else can with any truth be alleged against me.

I am not without apprehensions of the cause of this behavior towards me;
I mean my constant zeal for an impartial liberty of conscience.
But if that be it, the cause is too good to be in pain about it.
I have always understood this to be the natural right of all men;
and that he that had a religion without it, his religion was not his own.
For if it is not a religion of man`'s choice,
then it is the religion of another who imposes it;
so that liberty of conscience is the first step to having a real religion.
This is no new opinion with me.
I have written many apologies within the last twenty years to defend it,
and that impartially.
Yet I have as constantly declared, that bounds ought to be set to this freedom,
and that morality was the best bounds;
and that as often as that was violated under a pretense of conscience,
it was fitting that civil power should take its place.
Nor did I ever once think of promoting any sort of liberty of conscience
for anybody which did not preserve the common Protestant kingdom,
and the ancient rights of the government; for to say truth,
the one cannot be maintained without the other.

--

From this little abstract of William Penn`'s defense,
it appears sufficiently what kind of liberty he defended;
and such a liberty afterwards took place in the reign of the next king.

Of George Fox I have been long silent,
and I do not meet with any very remarkable transactions that concerned him at this time,
except that he wrote much, both for the edification of his friends,
and for the instruction and admonition of others.
He was continually occupied with the care of the church,
and desirous that things might be kept in good order, which, to perform the better,
he now stayed a long while in and about London.

In this year died William Dewsbury,
one of the first preachers among those called Quakers,
having been a very zealous teacher, and an eminent instrument to the conversion of many.
He was born in Yorkshire, and in his youth was a shepherd,
and afterwards was put apprentice to a cloth maker;
but when the civil wars broke out he became a soldier and
joined with those who said they fought for the gospel.
Now though he was religious according to his understanding,
yet growing more and more serious, and turning his mind inwardly,
he saw there were inward and spiritual enemies to encounter,
according to the saying of the apostle, "`We wrestle not against flesh and blood;
but against spiritual wickedness,`" etc.
And this state was inwardly manifested to him in the words of our Savior:
"`Put up your sword into the sheath.
If my kingdom were of this world, then would my servants fight.`"
This wrought so powerfully upon his mind,
that he could no longer meddle with military affairs, but left the army,
and returned to his former trade, endeavoring to grow in true godliness,
in which he so advanced,
that when George Fox came to Balby in Yorkshire in
the year 1651 and preached the gospel there,
he could not but consent to the doctrine declared by him as being
the same of which he had already been convinced in his mind,
namely,
that heed ought to be given to the inward Divine reproving for that which is evil.
This doctrine was preached by George Fox under the name of "`the true light which enlightens
every man coming into the world;`" saying that this light must be heeded,
as being a manifestation of that grace that "`brings salvation`" and "`has appeared
to all men,`" Titus 2:11. W. Dewsbury not only agreed with G. Fox in this point of doctrine,
but in process of time became a very zealous preacher of it,
for which he fell under great sufferings;
insomuch that he was prisoner at Warwick nineteen years for religion`'s sake,
besides the imprisonments he suffered on the same account in other places.
But being now released, he came in the month called May to London,
and there preached a sermon concerning regeneration,
which was taken from his mouth in short hand, and afterwards printed as follows.

[.embedded-content-document]
--

[.letter-heading]
A Sermon preached by William Dewsbury, at Gracechurch Street, the 6th of the Third month,
1688.

[.salutation]
My Friends,

[.offset]
Except you be regenerated and born again, you cannot inherit the Kingdom of God.

This is the word of the Lord God to all people this day.
This lies not in an airy profession, in vain imagination,
or in whatsoever else you might deck yourselves with; no,
every particular man and woman must be born again,
else you cannot enter into the kingdom of heaven.
This was the doctrine of Christ when He was in that "`prepared body,`"^
footnote:[Hebrews 10:5]
in which He appeared in the world and preached to Nicodemus
that standing doctrine which remains to this moment of time,
and will continue to remain while any man breathes upon the earth.
There is no other way, no other gate to enter into life,
but by this great work of regeneration.
Now, to come to this great work,
and to set forward and travel from earth to heaven (all having been driven
out of Paradise by the cherubim set with a flaming sword),
you must know that there is no returning to that blessed life except
by the loss of that life that did grieve the Spirit of God,
and which did cause man to be driven out.
There is no other way of return again but by this new birth.
As you are all driven and forced out of Paradise,
and the flaming sword and the cherubim are set to guard the way of the tree of life,
so you must return into the favor of God again by the light of Christ;
and so you have "`line upon line, precept upon precept, here a little,
and there a little,`"^
footnote:[Isaiah 28:10, 13]
to direct your minds to the light of Christ Jesus.
"`As the first Adam was made a living soul, so the second Adam is a quickening Spirit.`"
Know this for certain,
that no man or woman can be quickened and raised up into the life of the second Adam,
till the life of the first Adam be taken away from them.

So now, let every one of you deal plainly with your own hearts.
Have you come to be a slain people to the life of the first Adam,
in which life there is a working of the mystery of iniquity in every part of man?
One cries, "`Lo here is Christ;`" another,
"`Lo there is Christ;`" and every one is following
his own imagination about the letter of the Scripture.
But this is still but the vain spirit of man running and striving to recover himself;
and this is the cause why there is so much profession of God,
and so little of His nature appearing among the sons and daughters of men.
But all of you who seek to be regenerated, you must come to the light of Christ;
there is no other way to it.
He will search your hearts, and try your mind, and set your sins in order before you,
and trace out the iniquities that compass you about.
You must see yourselves to be a lost people, a sinful people,
and so come to feel the weight of your sins upon your consciences.
There is no other way to come to life.
You will never complain of sin until you are burdened with it,
till you have a trumpet sounding in your ears to awaken you,
that you may arise from the dead, that Christ may give you light.
There is no other way, dear people, you must bring your deeds to the light of Christ,
and abide in the sentence of condemnation.
If you save your lives, you lose them; if you will lose your lives for Christ`'s sake,
there is no danger to your eternal life.
John the Baptist, Christ`'s forerunner, declared,
"`I indeed baptize you with water unto repentance,
but He that comes after me is mightier than I,
whose sandal strap I am not worthy to unloose,
He shall baptize you with the Holy Spirit and with fire.
His fan is in His hand, and He will thoroughly purge His floor,
and will gather His wheat into His garner;
but the chaff He will burn with unquenchable fire.`"
What good is it for you to read the Scripture, if you know not this fiery baptism,
which all must know who are regenerated.
Do not deceive yourselves, Christ will appear in flaming fire,
and take vengeance on all those who know not God,
and who do not obey the gospel of our Lord Jesus Christ.

I stand here as a witness of the Lord of life this day,
there is no way for people to come to salvation,
but by knowing Christ revealed in their hearts.
What is He doing there but rendering vengeance upon the carnal mind, all self-pleasing,
and inordinate affections?
He comes with vengeance to take away your life;
He will baptize you with the Holy Spirit and with fire.
If you do not know this baptism, you are not a true Christian.
You will never look death in the face with joy, nor go down to the grave with triumph.
If you live at home in the body, and flee for your life,
and are not willing to lose your life for Christ if you are called to it;
and if you will not have Christ to wash you,
(some for shyness and some for self-love will refuse this), I say,
if Christ does not wash you, you have no part in Him.
You must come to Christ to purify you in the fiery furnace.
The day of the Lord shall burn as an oven (as the prophet speaks);
this is a dreadful day, a day of vengeance,
the day of the Lord Jesus Christ who redeems His people from their sins.
Zion is redeemed with judgment and established with righteousness.
Do not make the way to heaven easier on your minds and imaginations than it indeed is,
nor think it sufficient to live in an outward observance of the ways of God.
If your own wills remain alive, and your corruptions remain unmortified,
the judgment of God will be your portion.

Therefore, in the Lord`'s name come along with me.
I have come to declare what I have heard and seen of the Father.
Come now and examine your conscience.
Have you brought your deeds to the light?
If you have, then you have received condemnation upon yourself,
and your haughtiness is bowed down and laid low,
and you see yourself a poor miserable wretch before the eternal God.
Whatever you may know of the mind of God, have you reformed your ways?
Come along with me, and tell me what is the ground of your faith and your confidence?
Read the book of conscience; have you no ground for your faith?
You have put on the reformed faith, but have you lived an unreformed life?
Search and try yourself, man or woman.
Do you watch over yourself and keep in a sense of your approaching dissolution,
notwithstanding all your qualifications and partial reformation?
Do you strive to enter in at the strait gate, and the narrow way,
to lose the life of your will, the life of the first Adam?
The justice of God will not allow you to make a savior of your duties and qualifications;
or to take God`'s jewels, and to deck yourself with them.
No, you cannot be saved without the righteousness of God in Christ Jesus.
What does your conscience say?
Are you brought to a change of your mind and of your conduct?
Are you willing to part with your sins, with your pride and haughtiness?
Are you willing to part with your vile affections?
This is the work of God`'s grace upon you.
Do you place your confidence in your duties and qualifications,
and take God`'s jewels and ornaments, and deck yourself with them?
"`You took my jewels,`" says the Lord,
"`and did play the harlot;`" if you return to the Lord, and humble yourself,
and pass through this tribulation, you will be happy forever.
This judgment of God, this flaming sword that turns every way,
will keep you from returning to sin.
It will bring you to Christ, and cut you off from all hope of salvation but by Him,
and make you to see the absolute need of a Savior,
and that your life is hid with Christ in God.

It is God`'s infinite goodness to men that He will "`hide pride from them,`"^
footnote:[Job 33:17]
and humble them under His mighty hand.
This is the condition of poor creatures that are slain by the hands of the Most High.
How may I know when I am slain and baptized, and have come to sincerity?
They that have this baptism enter into a heavenly life.
If you love the light of Christ Jesus, it will be thus with you;
God will do a quick work in your earth.
He will set your sins in order before you, and make you watchful unto prayer,
and lead you to holiness of life and conduct, and make you abhor yourself,
and despise all the pomps and pleasures and vanities of this world.
When He has adorned you with His graces, then watch for the light,
and in the light of Christ you shall see light,
and know that all you have done and can do, is but your duty.
And if you diligently wait, you shall see more light,
and the sword that proceeds out of the mouth of Christ (who is called the Word of God)
will cut you off from all your hopes of salvation from anything you have done,
from any of your qualifications, from anything that you can do;
so that you will be a hopeless soul, having nothing in your own sense and apprehension.
The power of the first Adam must die before Him, and you will cry out, "`I am a dead,
lost, and undone creature!
There is a life hid with Christ in God for me,
but I can never have it till I be slain and fall into the will of God,
and become as a little child,
and be stripped of all my own excellency that I have attained.
I must come to a sense of my own misery, and fall down at the foot of God.
And when I have become as a little child, humbled and slain as to my own will,
and all confidence in my own righteousness, I shall indeed live a holy life.
But I will give all the life I once had, for that life which is hid with Christ in God.`"
Oh, anyone who comes this far will never miss eternal life.
All dishonest people who desire to have salvation by Christ,
but will not let Him exercise His heavenly power,
His princely glorious power to baptize them into His death,
they indeed will come short of salvation.
But all who yield themselves up to Christ to be redeemed through judgment,
and have become as little children, these are in a happy state.
You know that our Lord Jesus Christ took a little child in his arms, and said,
"`Whosoever will not become as a little child, cannot enter into the kingdom of heaven.`"
You must all become as little children, and depend upon the mercy and free grace of God.
You must all come to a holy resignation of your wills to God`'s disposal.
If you come to Christ as little children, and depend upon Him,
you cannot miss His salvation.
It is bestowed upon such souls as hear the voice of Christ;
for they that hear the voice of the Son of God shall live.

I stand here as a witness for the God of heaven, I never heard the voice of Christ,
as His follower, till I was slain and baptized,
and lay as a little child under His heavenly chastisements.
But as soon as my soul was brought to this state, in my humiliation,
oh then the dreadful judgment was taken away, and the book of life was opened unto me,
and the Lord spoke comfortably to me, "`I have loved you with an everlasting love.`"
So I was made a Christian through a day of vengeance, and of burning as an oven,
and the haughtiness and pride of man in me was brought low.
Now, it is through this conformity to Christ`'s death that people may die unto life;
and blessed are the dead that die in the Lord, for they rest from their labors,
and their works do follow them.
Away then with your own wills, and your pride and haughtiness,
and your hypocrisy and deceit, and all dependency upon any qualifications of your own.
You must come to have your life separated from you, or else you will perish.
Those who will die with Christ, and be willing to die for Him,
to them He is revealed as a Savior.
He came to us in the days of His flesh, and complied with His father`'s will.
He was nailed to the cross.
The Son of God, when He had come to the depth of His sufferings, cried, "`My God, My God,
why have You forsaken Me?`" This was for your sake, and my sake,
and every man and woman`'s sake that believes in Him.
He drank the cup which His Father gave Him to drink.
If it was done thus to the green tree, what shall be done unto the dry?
He went before us, that when He comes again He takes us to Himself,
and takes us from the filth of sin, that we may be made new creatures.

Now except we be born again we cannot enter into the kingdom of God,
and there is no becoming new creatures until we are slain to the old man.
You must be slain to your pride and haughtiness, to the corruption of your own will,
and all selfishness; these things God must burn up in you.
The Holy Spirit will destroy and burn up nothing in you
but that which will bring an eternal fire upon your soul.
"`Show me, You whom my soul loves, where is the path of life,
the footsteps of the flock of Your companions?
Why should I be as one that goes aside?`"
Now everyone that lives at home in the bosom of self, take this with you:
though you profess the truth, and live in an outward conformity thereunto,
yet if you secretly indulge your corrupt wills, and live a flesh-pleasing life,
and consult with flesh and blood, and are not broken off from your lusts,
you cannot enjoy the Lord of life.
"`While I am at home in the body, I am absent from the Lord.`"
The body of sin is like a magnet to draw you from the life of God,
and from glorying in the cross of Christ.
It is flesh and blood, and flesh and blood cannot inherit the kingdom of God.
For the Lord`'s sake, for your soul`'s sake, and for the sake of your eternal happiness,
do not put off this work, but pursue it, and it will be perfected.
Experience Christ to be revealed in you by His Holy Spirit and fire.
God will redeem you by the spirit of judgment and burning.
It is not by roving abroad in your minds,
but you must know "`Christ __in you__ unless you be reprobates.`"^
footnote:[2 Corinthians 13:5]

If He has set your eyes and hearts upon Himself,
and made you to water your couch with your tears;
if He has broken your sleep so that you have cried out, "`I shall be damned,
and never come to salvation,`" (this will be your cry; it was once my cry),
oh then let not your eyes slumber, nor your eye-lids take any rest,
till you be sure that the Lord is your God.
If you find these marks, then you are on your way;
otherwise you will be like a deceitful bow, and never abide in judgment.
If you reject the counsel of God against yourselves,
and refuse to be crucified with Christ, and to be baptized with His baptism,
you will never have life.
But by His baptism,
and through the heavenly operation of His Spirit (having faith in Christ`'s name),
you shall be married to Him in everlasting righteousness.
Salvation shall be brought to us, and eternal life be bestowed upon us,
even that life which is hid with Christ in God.
He will give to every poor mournful soul that submits to His blessed will,
and believes in the Lord Jesus Christ.
This is not a faith of our own making, nor a garment of our own embroidery,
but that which the Lord has given to us.
Oh happy is the man or woman that obtains this gift of God!
Oh who will not lose their lives for this everlasting life?
Who will not die for this eternal life?
The matter lies in the death of your own wills.
And when you have done the will of God, then watch that your own wills remain slain,
and that cursed _self_ takes not the jewels of God, or His bracelets and ornaments,
to bestow them upon self, to paint and deck cursed self,
or to take the members of Christ, and make them the members of a harlot.
If you are dead to your own wills, you are risen with Christ,
and shall receive a resurrection to eternal life.
Oh, crucify self, and set the world at nought, and trample upon it and all things of it,
and count them as dross and dung in comparison to Christ,
whom the Father has revealed to be our life in the days of our sorrow and mourning,
in the day of our calamity, in the day when we cried out that our hope was lost.

Thus it has been with the holiest people on earth.
It is not by works of righteousness of your own that you can be saved;
Christ comes to cut all these down,
that you may be ingrafted into Him and justified by His grace.
Do not make this a matter of talk, and say,
"`I have already heard this and that;`" but look into your
own hearts and see what heavenly workings are there.
What have you experienced there of the power of the Lord Jesus?
Has His power made you to loathe this world, and the inordinate love of the creation,
that you may enjoy all these things as if you enjoyed them not?
When we are slain and crucified to this world, we cannot help but say,
"`My life is in Christ.`"
We come to ascribe nothing to ourselves, and all to Christ.
Here is a blessed harmony: broken hearts, melted spirits, and yet joyful souls.
Poor creatures that were mourning and sighing,
and crying before the Lord in secret places, saying, "`My hope is cut off,
I will lie down in Your will, O God; do what You will with me.
It is Your sovereign pleasure and free gift, whether You give me life or deny it to me.`"
Oh there must be a resignation of ourselves to the will of God.
It was so with the Lord Jesus, and it is so with every true saint of God.
You must be humbled as little children before the judgment will be taken away,
and the lovingkindness of God sealed up to your souls.
But if you seek this work of God, you will find it, if you seek it upon your beds,
in all your labors and concerns, in all your stations and relations.
If you press after the new birth, you must use this world as if you used it not,
and live a married life as if you were unmarried,
for the form of this world is passing away.

But let me tell you, a new world comes by regeneration.
The new man is not lifted up in his own mind, but laid low in his own eyes;
he waits for the wisdom of God to govern him, and he is as a steward of the grace of God,
to give to those that stands in need.
When a man is regenerated and born again, he is as contented with bread and water,
as with all the enjoyments of this world.
What is the reason?
His own will is gone and put down under his feet,
together with whatever gives life to all his vain desires and affections.
Oh there is a harmony of all within.
There is a man praising of God, and blessing His holy name,
with no entanglements to draw away the heart from serving God and seeking His glory.
And if God should call the husband from the wife,
or the wife from the husband for the glory of His name,
there is no whining and complaining and crying out; but rather a giving them up,
and a praising and blessing God when they are called to such an exercise.
And if they are not so called,
then they set their hearts to glorify God in their several places and stations,
and have full contentment in a blessed resignation.
Here their wills are slain,
and they praise God they have no desire but "`Lord
Your will be done,`" always praising Him,
and having the fear and glory of God before their eyes.
All mischief is hatched in pleasing men`'s own wills; that is,
in the counsel of the heart that Christ does not govern.
Will you live as the Quakers?
Then you must live contemptibly, and everyone must walk in humility and love,
and in true acquaintance with the God of heaven.
Here is now a new world, and the fashions of the old world are gone.
All pride, haughtiness, anger, and trampling upon one another are gone,
all slain through the operation of Christ.

What remains now?
Christ is in me, and we are all one in Him.
Christ laid down His life for you and me, and now He reigns in me.
He has prepared my body to die for the truth,
as His prepared body was laid down for my sin.
It is foolish when men make a profession of Christ, and yet live in covetousness,
profaneness, sensuality, and the like.
They that have come to this heavenly birth, seek the things that are above,
and can do no other.
First make the tree good, and the fruit will be good.
You must be ingrafted into the vine of God`'s righteousness.
Oh slight not the day of your visitation!
What was it to me to read of another being born again, until I myself was slain,
and knew the heavenly baptism of Christ Jesus,
and saw the flaming sword ready to slay me in every turning?
The light of Christ convinced me of sin, and His righteousness justified me,
and then all works were abominable to me that hindered my soul`'s passage to Christ.
In marrying my soul to Himself, Christ seized upon me, and did work effectually in me;
and there now is a testimony of Christ in me that
He has sealed up my soul to the day of my redemption.
Here is a certain travel,
and a certain way which no one can miss if they will but lose their lives for Christ.
If you are not ready and willing to lose your lives for Christ, you cannot come here.
None come to the strait gate, and the narrow way,
but those who will die into a heavenly oneness with Christ.
Oh friends, let us empty ourselves, that Christ may fill us!
Let us be nothing in our own eyes, that we may be all in Him, and receive of His fulness!

Now I commend you to God`'s witness, that you may remember what has been spoken among you.
But consider, if you do not hearken to it,
it will follow you and be a plague to you to all eternity.
If you will not yield yourselves up to Christ in this day that burns like an oven,
then you must dwell in this fire when out of the body,
and there will be no quenching the fire forever.
But if you will be so wise as to resign yourselves up to Christ,
and to come to Him as little children,
you will see that this will not hinder your earthly concerns.
Though the world may account you a fool,
yet you will have the heavenly wisdom to do what you do unto God.
You will carry yourself towards your wife as in the sight of God,
that she may be sanctified to you, and you to her.
You will carry yourself becomingly to your children and servants,
and so will abound in grace, and in every good work,
which will be for your eternal welfare.

Oh, I beseech you people, for the Lord`'s sake,
to wait for the light of Christ to guide you!
Learn of Him to be meek and lowly, then you will be happy.
For He dwells with the humble, but beholds the proud afar off.
This new birth--which is a true work, a real and heavenly work-- will make you so forever.
Oh make room for Christ in your hearts,
or else it is not likely He will ever dwell with you;
for He loves to dwell with the poor and humble and contrite spirit.
He abhors the proud, but He will empty your souls, that He may fill them.

And so I commend you to God.
I have been long held in restraint under great weakness;
and I was restless till I could come up to this great city
of London to preach the everlasting gospel among you;
and now you see I am here among you.
Come now, every one of you, turn inward.
Let not these words, passing through a contemptible vessel,
be as a bare and empty discourse of truth to you, which you only hear,
and then take no further care for your salvation.
Take heed of despising the light that shines in the midst of you,
but press forward to the heavenly work that is established in the power of Christ Jesus,
even through judgment into death, and then He will give you eternal life.
May the Lord confirm this, and it may rest upon your hearts,
so that you may be dead to the things of the world.
We have not come to Mount Sinai, which gives birth to bondage,
but have come to Mount Zion, and to the city of the living God, the heavenly Jerusalem,
to an innumerable company of angels,
to the general assembly and church of the firstborn who are registered in heaven,
to God the Judge of all, to the spirits of just men made perfect,
to Jesus the Mediator of the new covenant,
and to the blood of sprinkling that speaks better things than that of Abel.
This is the inheritance of the redeemed of the Most High.
Blessed be the name of the Lord!
Oh let us rest in hope, till He brings us to humility and lowness of mind,
that He may clothe us with heavenly glory according to His promise,
"`I will beautify My house with glory, says the Lord.`"
This is the portion of a poor people, who cast themselves down before the Lord,
that He may lift them up, and be all in all to them.
And in His blessed presence they shall have joy,
and rivers of pleasures at His right hand forevermore.

--

William Dewsbury`'s intention was to have attended the yearly meeting of his friends;
but he was prevented by illness; and therefore before he grew worse,
he returned to Warwick where he lived.
Having come there, his infirmity increased, and lying very sick in bed,
and being visited by some of his friends, he said to them in great weakness of body,
as follows:

[.embedded-content-document]
--

My God has yet put it in my heart to bear a testimony to His name and blessed truth.
I can never forget the day of His great power and blessed appearance,
when He first sent me to preach the everlasting gospel
and proclaim the day of the Lord to all people.
Therefore friends, be faithful, and trust to the Lord your God; for this I can say,
I never since played the coward, but as joyfully entered prisons as palaces,
and in the prison-house I sang praises to my God,
and esteemed their bolts and locks upon me as jewels.
And friends, this I must once again testify to you in the name of the Lord God,
that what I saw above thirty years ago,
still rests as a testimony for me to leave behind,
that a dreadful terrible day is at hand, and will certainly come to pass;
but the time when, I cannot say.
But all put on strength in the name of the Lord,
and wait to feel His eternal power preserve you through
the tribulations of those days that approach very near.
This I have further to signify, that my departure draws near.
Blessed be my God, I am prepared,
and I have nothing to do but die and put off this corruptible and mortal tabernacle,
this flesh that has so many infirmities.
But the life that dwells in it, ascends out of the reach of death, hell, and the grave;
and immortality and eternal life is my crown forever.
Therefore you that are left behind, fear not, nor be discouraged,
but go on in the name and power of the Lord,
and bear a faithful and living testimony for Him in your day.
The Lord will prosper His work in your hand,
and cause His truth to flourish and spread abroad.
For truth shall have the victory, and no weapon formed against it shall prosper.

--

Thus fervent in spirit was William Dewsbury in his latter end.
He prayed to God very earnestly for all his friends,
especially those that were then together at the annual assembly in London,
and so very piously departed this life at his house, in a good old age,
in the month called June, in this current year.
He was indeed a man of a remarkable zeal and perception.
He sometimes spoke to young lads as to men,
telling them that the blessing of the Lord would
rest upon them if they lived a godly life;
and some of these, having since come to be men,
have indeed experienced the truth of his words.

Two days before the decease of William Dewsbury,
Rebecca Travers departed this life at about the age of seventy-nine years.
She was an exceedingly well-gifted woman,
who not only spoke sometimes in public for the edification of the church,
but wrote also several books for the advancement of piety.
In one of her books she signified that,
though she had been a reader of the Scriptures from a child of six years old,
yet when by the power of the eternal gospel she was turned from darkness to light,
the Scriptures then became much more plain to her, as not lacking interpretation.
She was an excellent, open-hearted woman, and took great care of the poor.
She had several times been imprisoned for religion,
but persevered constantly in the faith, and so piously entered into eternal rest.

As to state affairs, there now appeared a great agitation in England,
since it was reported that the queen^
footnote:[Mary of Modena, James II`'s second wife.]
was expecting a child.
The endeavors of the king for introducing popery,
together with his encroaching upon some rights and privileges, had caused such a stir,
that William the third,^
footnote:[William III was the Protestant nephew and son-in-law of king James II.]
prince of Orange, and lord deputy of Holland,
etc. was entreated and invited by the English Protestants to come to their assistance.
This at length he did, coming over with a fleet and a considerable number of forces.
The outcome of this expedition is very amply described by other pens,
and not properly my business to relate;
wherefore I think it sufficient to my purpose only to say, that William III,
after some difficulty at sea, came into England; and having many adherents there,
the king (many of whose forces deserted him) resolved to go to France,
where the queen with their young child had already gone sometime before.
Accordingly James went into France, where he was well received by Louis XIV,
who provided him a court at St. Germain`'s. In the meantime,
the prince of Orange came to London and was saluted
there by the great ones as "`the deliverer of England.`"
And after the lord mayor, aldermen, and sheriffs of London had congratulated him,
the prince sent for some of the members of former parliaments to come to him,
and signified that he had desired them to meet to advise him in the best
manner how to pursue the ends of his declaration in calling a free parliament,
for the preservation of the Protestant religion,
and the restoring of the rights and liberties of the kingdom,
that they might not be in danger of being again subverted.
In answer to this,
thanks were given to the prince for his care and pains in defense of the people,
their religion, and laws.
And all things took a favorable turn for him.

In Holland, a good while before this time, a paper was published in print, called,
"`A Copy of a Letter written by a Quaker in London to his Friend at Rotterdam.`"
This forged letter mentioned several things that were not altogether untrue,
and prince William`'s coming over to England was also in a manner predicted.
Who the author of the said letter was, I could never find,
but of this I am fully satisfied, that he was no Quaker;
for it never was their way to ridicule princes,
and to characterize them with ridiculous denominations,
as in the said letter we find mentioned of James of Great Britain, Mary of Modena,
William of Orange, and Mary of England, his wife.
Such foolish language betrays itself,
and serves for a palpable evidence that it never proceeded
from the pen of any of the people called Quakers.
But perhaps the author of the letter knew a secret of the government,
whereof (in order to remain unknown) he sought to acquaint the world in a ridiculous way;
so that under the cloak of being a Quaker, he could best continue undiscovered,
and that by this scheme the letter would spread the more, as indeed it did;
for it circulated very quickly.
