== Chapter XXII

[.section-date]
1689--1694

I proceed now to the year 1689,
in the beginning of which the peers of the realm offered
the administration of the government to the prince of Orange,
which he accepted.
Not long after this,
he called a "`convention of the commons;`" for it could not be called a parliament,
since in England no one but a king has power to call a parliament.
In the meantime,
the prince had caused the princess to come over from Holland into England;
and at length the convention (after many great debates)
came to the resolution that the throne was vacant;
the consequence of which was,
that the prince and princess of Orange were declared by the names of William the third,
and Mary the second, to be king and queen of England,
and accordingly were afterwards crowned.
A large relation of these events can be found in several books, so I will only say,
that the coronation was performed by the bishop of London,
the archbishop of Canterbury having refused to act in the solemnity.
At the performance of the coronation, the king and queen were asked by the bishop,
"`Will you solemnly promise and swear to govern the people
of this kingdom of England and the dominions belonging thereto,
according to the statutes agreed to in parliament,
and the laws and customs of the same?`"
To which, the king and queen having answered,
"`I solemnly promise so to do;`" the bishop asked, "`Will you, according to your power,
cause the law, in justice and mercy, to be executed in all your judgments?`"
The answer was made, "`I will.`"
The next question was, "`Will you, to the utmost of your power, maintain the law of God,
the true profession of the gospel,
and the Protestant Reformed religion established by law?
And will you preserve unto the bishops and clergy of this realm,
and to the churches committed to their charge,
all such rights and privileges as by law do or shall appertain to them, or any of them?`"
To this the king and queen answered, "`All this I promise to do.`"
After this, each of them laying their hands upon the book of the gospel, they said,
"`These things which I have here before promised, I will perform and keep.
So help me God.`"
Under these punctual and nice questions, there was more hidden than some would think.
For the king, having answered as has been said,
could not now free any from paying tithes to the clergy without a violation of his oath.

Not long after William and Mary were thus made king and queen of England,
they were also declared king and queen of Scotland.
Shortly after this, a war was proclaimed against France, and the late king, James,
supported by the French king, went over to Ireland.
In the process of time he was driven away from there by king William,
after the bloody battle near the river Boyne;
but these events not belonging to this history,
I will not detain my reader with a relation thereof.

A new king having now mounted the throne,
the convention of the commons was turned into a parliament;
and then this grand assembly made it their business to restrain the forcing of conscience;
and an act was passed for exempting Protestant dissenters from the penal laws,
by which some dissenters, and especially the Quakers,
had suffered and been persecuted for many years.
Yet care was taken to keep a law in force by which Papists were
excluded from sitting in parliament and serving in high offices.
The aforesaid act also gave liberty to dissenters to keep religious meetings,
provided the doors were not locked, barred or bolted, during the time of their meetings.
But none of these dissenters were freed from paying tithes,
or other church dues (so called) to the clergy,
nor from being cited before bishops`' courts.
However, this liberty of keeping public meetings was not allowed to Papists;
for all that desired to participate in the said liberty
were required to take the oath of allegiance.
Yet to comply with the people called Quakers,
who for conscience-sake scrupled to take any oath,
this act required that they should subscribe to the following declaration:

[.embedded-content-document.legal]
--

I +++_______+++, do sincerely promise and solemnly declare, before God and the world,
that I will be true and faithful to king William and queen Mary;
and I do solemnly profess and declare, that I do from my heart abhor,
detest and renounce, as impious and heretical,
that damnable doctrine and position that princes excommunicated or deprived by the Pope,
or any authority of the see of Rome, may be deposed or murdered by their subjects,
or any others whatsoever.
And I declare that no foreign prince, person, prelate, state, or potentate, has,
or ought to have any power, jurisdiction, superiority, preeminence, or authority,
ecclesiastical or spiritual, within this realm.

--

Besides this they were obliged to subscribe to another also,
with respect to their orthodoxy, and for excluding Socinianism.

[.embedded-content-document.legal]
--

I +++_______+++, profess faith in God the Father, and in Jesus Christ his eternal Son,
the true God, and in the Holy Spirit, one God, blessed forevermore;
and do acknowledge the holy Scriptures of the Old
and New Testament to be given by divine inspiration.

--

And lest any Papist might make use of this declaration,
there were required sufficient Protestant witnesses
to prove that the declarer was a Protestant dissenter.
Besides this, no congregation or assembly for religious worship was allowed by this act,
until the place of such meeting was certified by the bishop of the diocese,
or the archdeacon,
or the justices of the peace at the general or quarter-sessions of the peace,
and registered in the said bishop`'s or archdeacon`'s court respectively,
or recorded at the said general or quarter-sessions;
for which the register or clerk should not take greater fee or reward than sixpence.

Here we at last see the religion of the Quakers acknowledged
and tolerated by an act of parliament;
and themselves released from all persecution for performance of their public worship,
and for their refusal to take the oath of allegiance.
This was a work reserved for that great prince king William,
who being born in a country where force upon conscience
was abolished under a Protestant government,
he now also, according to his ability, introduced the same Christian liberty in England.
But to release dissenters from the payment of tithes was beyond his reach,
regardless how unreasonably the clergy acted in this case.
A noticeable instance of this was published in print about this time,
where one John Bishop, a countryman at Wortham, had taken from him for two years tithes,
various horses, kine, and sheep, to the value of about seventy-six pounds,
according to the estimate of impartial persons,
though rated by himself to be worth eighty-three pounds.
And yet the priest, Thomas Thurlow, had declared upon his oath,
that he believed the amount due to him for the tithes of both years
amounted to three pounds seventeen shillings and sixpence.

In Barbados, in the West Indies, where the inhabitants were marshaled to bear arms,
the Quakers (notwithstanding what had been ordered in their
favor by king James) continued yet under hard sufferings.
Those who were thus oppressed,
now sent over a petition to the king wherein they set forth how they were molested,
and requested relief.
This had such effect, that the king issued forth the following order:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
At the Council at Whitehall, Dec. 12, 1689.

[.salutation]
Present the king`'s most excellent majesty in council.

Upon reading a petition of the people called Quakers, inhabiting the island of Barbados,
setting forth how, because the said Quakers cannot bear arms,
nor take an oath in any case,
they have suffered much by virtue of an act made to settle the militia in the said island;
as in the petition hereunto annexed is more at length expressed,
his majesty is graciously pleased to refer the matter of
the said petition to the examination of James Kendal esq.,
his majesty`'s governor of Barbados for the time being,
who is to give the petitioners such relief in relation to the militia,
as to him seems just and reasonable to answer their particular circumstances,
and then to make report thereof to his majesty.

[.signed-section-signature]
Richard Colling

--

This year deceased Alexander Parker, sometimes mentioned in this history,
being a man not only of a godly life and conduct,
but also of a godly mien and grave deportment.
In the following year, 1690, Robert Barclay also departed this life,
a man of eminent gifts and great endowments,
being an expert not only in the languages of the learned,
but also well versed in the writings of the ancient
fathers and other ecclesiastical writers,
and furnished with a great understanding, being not only of a sound judgment,
but also strong in arguments, and cheerful in sufferings.
Besides this, he was of a friendly and pleasant, yet grave conduct,
and eminently fitted for settling differences;
and he really lived up to what he professed, being of an unblameable conduct,
truly pious, and well-beloved by those he conversed with.
In this happy state it pleased God to take him out
of this valley of tears into a glorious immortality,
in the prime of his age, having not lived much above half the life of a man,
as it is commonly accounted, that is, in his 42nd year.
He died the third of October, at his house at Ury, Scotland,
of a sickness which did not last long, yet he signified with a good understanding,
that it was well with him as to his soul.

This year Stephen Crisp wrote an epistle of tender love and brotherly
advice to all the churches of Christ throughout the world,
in which he exhorted them more particularly to charity.
And since several remarkable duties are held forth and recommended therein,
I cannot well omit to insert a copy of it here, which is as follows:

[.embedded-content-document.epistle]
--

Dearly beloved friends and brethren,
gathered out of the world by the eternal arm and power of the mighty God,
to bear His holy name in your generation;
my love and life in the fellowship of the universal Spirit salutes you all,
and my prayer to God is that you may be kept steadfast
and immoveable in the grace of God,
and in the communion of His Holy Spirit, so that you may bring forth fruit in abundance,
according to the abundant mercy and grace bestowed upon you, to the glory of God,
and to your mutual joy, comfort, and edification.

And that you may so do, let your eye be kept daily to the Lord,
and behold and take notice of the wondrous works that He has wrought in you and for you,
since the day you were first quickened by His immortal Word,
and stirred up to seek after Him, and to wait upon him.
How good and gracious has He been to you, in bringing you from the barren mountains,
where your souls languished for the heavenly nourishment,
and where you knew not the Lord, nor one another, but were without a comforter,
or any to sympathize with you in your mournings.
Oh, how has He pitied your groanings, and had compassion on your sighings,
and brought you into acquaintance with those that were in similar exercises.
He then taught you to believe on Him who was able to help you;
and these who were thus taught of the Father,
and felt His drawing cords of love prevailing upon them, came to Christ their Savior,
and in Him began to feel a unity one with another in the faith you had received in Him.
And thus you believed that He would give you of His
spirit to teach and guide you in the way of truth,
righteousness, and peace; and in this way the foundation of your holy communion was laid,
and a lively hope was raised in each particular soul,
that He who had begun this blessed work would carry it on.
This hope made you not ashamed to make a public profession of His name before the world,
but to cheerfully take up His cross and deny yourselves of your former pleasures,
friendships, and the delights of this world.
And this hope has been your support in many sharp trials and the bitter
combats you have had with the enemy of your souls`' peace within,
and with the enemies of God`'s holy way and truth without;
and in all your conflicts you have found Him near at hand to put forth
His power on your behalf as you have depended upon Him for assistance.
And by these experiences of His goodness, your faith has been strengthened;
and by the same Word of life that quickened you, many more have been reached unto,
so that you have seen a daily addition of strength to yourselves,
and also an addition to your number, to your great comfort and encouragement.
Indeed, many have come to wait upon the Lord with you,
and many are daily inquiring the way to Zion, with their faces turned thitherward.
These things are worth your remembrance and serious considerations,
that you may look upon these great mercies to be obligations upon your souls,
to walk humbly before the Lord, and to be devout and fervent in your testimony,
for God has indeed done great things for you.

And friends,
consider the great works that this mighty Arm of the Lord has brought to pass in general,
as well as in particular cases.
How many contrivances have been plotted, and laws and decrees made to lay you waste,
and to make you cease to be a people, and how have the wicked rejoiced thereat,
for a season, crying, "`Ah, ha!
They are all now given over to banishments, to imprisonments, to spoil and ruin!
Now let us see if that invisible arm they trust in can deliver them.`"
Oh friends!
How has your God been your support in the midst of all these exercises!
And when He has pleased, how He has quieted the sharpest storms,
and turned back the greatest floods and torrents of persecution that ever you met with!
And how has He confounded His and your enemies,
and brought confusion upon the heads of those who sought your hurt!
Were not these things wrought by the power of God?
Did you numbers, your wisdom, your influence, or anything that might be called your own,
contribute anything to these great preservations and deliverances?
If not, then let God have the glory,
// lint-disable obsolete-spellings
and acknowledge to His praise that these have been the Lord`'s doings,
and they are marvelous in our eyes.

Again, dear friends,
consider how the wicked one has wrought in a mystery among you to scatter you,
and to lay you waste from being a people as at this day.
How many various ways has he tried,
raising up men of perverse minds to subvert and turn you from the faith,
and from the simplicity that is in Christ Jesus our Lord;
and to separate you from that invisible power that has been your strength,
and to separate you one from another,
and by subtle wiles to lead you into a false liberty above the cross of Christ.
And sometimes by sowing seeds of heresy and seditions,
he has endeavored to corrupt the minds of whomever he could with pernicious principles.
But oh, how have their designs been frustrated,
and the authors thereof been confounded and brought to nothing!
And how have you been preserved as a flock under the hand of a careful Shepherd,
even unto this day, which gives great cause of thanksgiving to all the faithful,
who have witnessed the working of this preserving power in their own particulars.

Also, my friends, it is worth your consideration to behold how, by this invisible power,
so many faithful watchmen have been raised up upon the walls of your Zion;
so that in most of your meetings there are men and women upon whom
God has laid a concern to take care for the good of the whole,
and to take the oversight upon them,
to see that all things are kept in good and decent order,
and to make due provision for the comforting and
relieving the necessities of the needy and distressed,
that nothing be lacking to make your way comfortable.
And these watchmen have not been, nor are brought under this charge by any act of yours,
but God has raised up pastors and teachers,
elders and deacons of His own election and choice,
and bowed their spirits to take upon them the work and service to which they are appointed,
for the Lord`'s sake, and for the body`'s sake, which is the church;
to whom it may truly be said, as in Acts 20:28, "`Take you heed to the flock of God,
over which the Holy Spirit has made you overseers.`"
And these ought to be hearkened to in the discharge of their duty,
as those that must give an account to Him that called them and gifted
them for their various works and services in the church.

And by these ways and means the Lord has established among you a heavenly government,
and built as it were a hedge about you,
that you may be preserved from generation to generation,
a people fitted for the glory that is,
and shall daily more and more be revealed among and upon the faithful,
who delight in that power which has called them to be saints,
and bear a profession for the holy name of God against the many
names and ways that men in their changeable minds have set up,
so that the name of the Lord alone may be exalted.

And dear friends and brethren, I entreat you,
that the consideration of these great and weighty
things which God has wrought for you and among you,
may have a deep and weighty influence upon your souls,
that you may find yourselves engaged to answer the
love and mercy of God in your lives and conducts,
and in all you have to do in this world.
And may you show forth the honor of God in all things,
that the light which has shined in you, may shine forth through you unto others,
who yet sit in darkness, that all men may know by your innocent and harmless conduct,
and by your keeping close to the Lord,
that you are a people who are assisted and helped
by a supernatural power which governs your wills,
and subjects them to His blessed will; and that guides and orders your affections,
and sets them upon heavenly and divine objects,
and that gives you power to deny your own private interests wherever
they happen to stand in competition with the interests of truth.
For these, and these only, will be found the true disciples of our Lord Jesus Christ,
who deny themselves, take up their cross daily,
and follow Him in the guidance of His regenerating power, which brings death upon self,
and crucifies the old nature with its affections and lusts,
and raises up a birth in you that has a holy will and desire to serve the Lord,
and to do His will in the earth.
Such as these are instruments in the hand of God by which He may work,
and do works of righteousness, justice, charity,
and all other virtues belonging to a Christian life, to the honor of God,
and for the comfort and benefit of His church and people.

And all you, dear friends, upon whom the Lord has laid a care for His honor,
and for the prosperity of the truth,
and gathered you into the good order of the gospel
to meet together to manage the affairs thereof;
take heed that you have a single eye to the Lord,
to do the Lord`'s business in the leading of His Spirit.
For the leading of His Spirit is but one,
and it brings all that are given up to be governed by it to be of one mind and heart,
at least in the general purpose and service of those meetings.
And although through the diversity of exercises,
and the several degrees of growth among the brethren,
every one may not see or understand alike in every matter,
yet this makes no breach of the unity, nor hinders the brotherly-kindness,
but rather puts you often upon an exercise and an inward travailing to
feel the pure peaceful wisdom that is from above to open among you.
And as every one`'s ear is open to this, in whomsoever it speaks,
so a sense of life is thereby given to the meeting to which
all that are of a simple and tender mind will join and agree;
but if any among you should be contrary-minded in the management
of some outward affair relating to the truth,
this does not presently break the unity that you have in Christ;
nor should it weaken the brotherly love,
so long as this one keeps waiting for an understanding from
God to be gathered into the same sense with you,
and continues walking with you according to the law of charity.
Such a one ought to be borne with and cherished,
and the supplications of your souls will go up to God for him,
that God may reveal it to him if it be His will;
that no difference may be in understanding,
so far as is necessary for the good of the church.

For, my friends,
it is not of absolute necessity that every member of the church
should have the same measure of understanding in all things;
for then where would be the duty of the strong bearing with the weak?
And where would be the brother of low degree?^
footnote:[James 1:9]
Where would be any submitting to those who are set over others in the Lord,
which things all tend to the preserving of unity in the church,
notwithstanding the different measures and different growths of the members thereof.
For even as "`the spirits of the prophets are subject to the prophets;`"^
footnote:[1 Corinthians 14:32]
so are the spirits of all that are kept in a true
subjection to the Spirit of life in themselves,
kept in the same subjection to the sense of life given by the same Spirit in the church;
and by this means we come to know the one Master, even Christ,
and have no room for other masters in matters of our obedience to God.
And while everyone keeps in this true subjection, a sweet concord is known,
and the oil is not only upon Aaron`'s head,
but it reaches to the skirts of his garment also;
and all things are kept sweet and savory,
and you love one another in sincerity from the greatest to the least,
and as the apostle says, "`without hypocrisy.`"^
footnote:[Romans 12:9]
And this love excludes all whisperings of evil things, all backbiting, talebearing,
grudging, and murmuring, and keeps friends`' minds clean one towards another,
waiting for every opportunity to do each other good,
and to preserve each other`'s reputation,
and their hearts are comforted at the sight of one another.
And in all their affairs, both relating to the church and to the world,
they will be watchful over their own spirits,
and keep in the Lord`'s power over that nature and
ground in themselves that would be apt to take offense,
or construe any word or action to a worse sense than
the intention of the other concerned will allow of.

And whereas it may often happen, that among a great many people,
some may have a different apprehension of a matter from the rest of their brethren,
especially in outward or temporal things;
there ought to be a Christian liberty maintained
for such to express their sense with freedom of mind,
or else they will go away burdened.
Whereas, if they speak their minds freely,
and a friendly and Christian conference be allowed thereupon, they may be eased,
and oftentimes the different apprehension of such a one comes to be wholly removed,
and his understanding is opened to see as the rest see.
For the danger in society does not lie so much in that some few may have
a differing apprehension in some things from the general sense,
as it does in this: namely,
when those who differ allow themselves to be led out of the bond of love,
and so labor to impose their private sense upon the rest of their brethren,
and are offended and angry if it be not received.
This is the seed of sedition and strife that has grown up in too many, to their own hurt.

Therefore, my dear friends, beware of this,
and seek not to drive a matter on in fierceness or in anger,
nor take offense into your minds at any time because
what seems to be clear to you is not presently received.
But let all things in the church be propounded with an awful
reverence for Him who is the head and life of it;
who has said, "`Where two or three are gathered in My name,
I will be in the midst of them.`"
And so He is, and may be felt by all who keep in His Spirit.
But he that follows his own spirit, sees nothing as he ought to see it.
Therefore let all beware of their own spirits and
natural tempers (as they are sometimes called),
and let all keep in a gracious temper;
for then are you fit for the service of the house of God, whose house you are,
as you keep upon the foundation that God has laid.
He will build you up, and teach you how to build up one another in Him.
And as every member must feel life in themselves, and all life flows from one Head,
so this life will not hurt itself in any, but will be tender of the life in all.
For by this one life of the Word you were begotten, and by it you are nourished,
and made to grow into your several services in the church of God.
It is not a man`'s learning or artificial acquirements,
nor his riches or greatness in this world, nor his eloquence and natural wisdom,
that makes him fit for government in the church of Christ; unless he,
with all his endowments, be seasoned with the heavenly salt, and his spirit be subjected,
and his gifts pass through the fire of God`'s altar
as a sacrifice to His praise and honor.
Thus self will be crucified and baptized in death,
and all gifts will be made use of in the power of
the resurrection of the life of Jesus in him.
And when this great work is wrought in a man,
then all his gifts and qualifications are sanctified and used for the good of the body,
which is the church,
and are as ornaments and jewels that serve for the joy and comfort of all who
are partakers of the same divine fellowship of life in Christ Jesus our Lord.
Thus many come to be fitted and furnished for good works,
which are brought forth in their due seasons for
the edification and building up of the weak,
and for repairing the decayed places, and also for a defense of those who are feeble,
that hurtful things may not come near them.

Oh friends, great is the work that the Lord has called you to, and is preparing you for,
who innocently wait upon Him.
And the Lord has opened my heart unto you,
and laid it upon me to exhort and beseech you to
have a care that you act as you ought to do,
in whatever God requires of you.
And for the more particular expressing of what lies before me in the matter,
I shall set down a few particular observations for your benefit and advantage.
My soul`'s desire is, that my labor of love may have a good effect in all your bosoms,
that God may be honored thereby.

Now friends,
you know that the chief business to which you are called in your
men and women`'s meetings falls under these two heads:
justice and charity.
First, to see that everyone has what is right done to them; and second,
to see that nothing is lacking for the comfort of the poor
who are made partakers of the same faith with you.
And when you meet together about these things, keep the Lord before your eyes,
and wait to feel His power to guide and direct you,
to speak and behave yourselves in the church of God as becomes the peaceable gospel.
Beware of all brittleness of spirit, and all sharp reflections upon each other`'s words,
for this will kindle up passion, and create a false fire;
and when one takes liberty to speak a sharp word (spoken outside of true
fear and tenderness) it oftentimes becomes a temptation to another;
who, if he is not careful, will be drawn out also.
Then the first is guilty of two evils: first, being led into a temptation himself,
and then secondly, becoming a tempter to others.
Therefore all have need to be upon their watch, that they neither tempt, nor be tempted.
And let none think it is a sufficient excuse for them that they were provoked;
for we are as answerable to God for every evil word spoken upon provocation,
as well as without provocation; and for this end has the Lord revealed His power to us,
to keep and preserve us in His fear and counsel in the time of our provocations.
Therefore if any man, through lack of watchfulness,
should be overtaken with heat or passion,
then "`a soft answer appeases wrath,`" says the wise man.
Such a time is best for a soft answer, lest the enemy prevail on any to their hurt,
and to the grief and trouble of their brethren;
for it is the proper duty of watchmen and overseers to protect the flock; that is,
to let nothing come near them that will hurt, wound and grieve them.
Indeed, the good apostle was so careful over the flock of believers,
that if there were any doubtful matters to be disputed,
he would not have those who were weak in the faith be present at such disputes;
much less then ought they who are weak see those who are strong descend from their strength,
and go into the weakness where they are not able to bear up.
The apostle in the place before-mentioned,
when he sent for the elders of Ephesus to Miletus, said, "`Take you heed to yourselves.`"
And indeed we are not able to discharge ourselves well towards others,
unless we also take heed to ourselves,
to be kept in that sober innocent frame of spirit which the truth calls for.

In the next place, my dear friends, when you are called upon in a point of justice,
to give your sense of right between friend and friend,
take heed that neither party gets possession of your spirit beforehand,
by any way or means whatsoever,
or obtains any word or decision from you in the absence
of the other party before he has been heard.
There is nothing more beautiful among men than impartial judgment;
for judgment is a seat where neither personal interest, or affection,
or former kindness may come.
We may make no difference of the worthiness or unworthiness of persons in judgment,
as we may in charity; but in judgment, if a good man, being mistaken, has a bad cause,
or a bad man has a good cause, according to his cause he must have his sentence.
Therefore let all be done as unto the Lord,
and as you are willing to answer it in His presence;
and although some may for a time be discontent,
yet in time God shall clear up your innocency as the sun at noon-day,
and they that kick against sound judgment will find it to be hard work,
for they do but kick against that which will prick them.
And though some, through their willfulness, may hurt themselves,
yet you will be preserved,
and enjoy your peace and satisfaction in the discharge
of your consciences in the sight of God.

And concerning practical charity, you know it is supported by generosity,
and where generosity ceases, charity waxes cold; indeed, thus far it ceases.
Where there is no contribution, there is no distribution; where the one is sparing,
the other is sparing.
Therefore let everyone nourish charity in its root, that is, keep a generous mind,
keep a heart that looks upon the substance that is given him as
really bestowed upon him as much for the support of charity,
as for the support of his own body.
And where people are of this mind,
they will be careful not to keep back any of God`'s part; for in all ages He has,
in a most remarkable manner, espoused the cause of the poor, the widow, and fatherless;
and has often signified by His prophets and ministers,
a special charge upon rich men who had this world`'s goods,
that they should be faithful stewards of what they possessed, being found in good works,
not allowing their hearts so to cleave to uncertain riches as to neglect
the service for which God has given them the things of this life.

Now, concerning the necessities of the poor,
there is great need of wisdom when you meet together about that affair;
for as I said before,
though the worthiness or unworthiness of persons is not to be considered in judgment,
yet in charity it is; and you will find some that God has made poor,
and some that have made themselves poor, and some that others have made poor,
which all must have their different considerations.
In this you ought to labor to be unanimous,
and not be taken up with an affection to one person more than another;
but let everyone love everyone in the universal Spirit,
and then deal out their love in an outward manifestation according to the measure
that the Lord (in His wisdom working in you) shall measure forth to them.

And as to those who by sickness, lameness, age, or other impotency,
are brought into poverty by the hand of Providence;
these are the peculiar care and objects pointed out to you, to bestow your charity upon,
for by them the Lord calls for it.
For as the earth is the Lord`'s, and the fulness of it,
He has by His sovereign power commanded in every dispensation
that a part of what we enjoy from Him should be thus employed.
The Israelites were not to reap the corners of their fields,
nor to gather the gleanings of their corn or grapes; it was for the poor.
And in the time of the gospel,
they were to lay apart on the first day of the week a part of what God
had blessed them with for the relief of those that were in need.
And indeed, they did not confine themselves in charity to their own meetings,
but had a universal eye through the whole church of Christ,
and upon extraordinary occasions,
sent their benevolence to relieve the saints at Jerusalem in a time of need.
Surely, all who keep within the guidance of the same universal Spirit,
will make it their business to be found in the same practice of charity and good works.
"`Do not forget to do good and to share,`" says the apostle;
and those who forget not this Christian duty will discover the poor`'s
part in the corners and gleanings of the profits of their trades,
just as the old Israelites did in the corners and gleanings of their fields.
And in the distribution of these things, have a regard to comfort the hearts of such,
who by the divine providence of God,
are put out of a capacity of enjoying the outward comforts of health,
and strength and plenty, which others do enjoy;
for while they are partakers of the same faith,
and walk in the way of righteousness with you,
submitting themselves patiently to the dispensation of God`'s providence towards them,
they are to be considered of your household, and under your care,
both to visit and to relieve, as members of one body, of which Christ Jesus is head.
And here, "`he that gives to such poor, lends to the Lord,`" and He will repay it.

But there is another sort of poor,
who make themselves poor through their own sloth and carelessness,
and sometimes by their willfulness, being rash and high-minded,
taking things in hand that are more than they can manage, and flourishing for a season,
and then, through their own neglect, are plunged down into great poverty.
These are a sort the primitive churches began to
be troubled with in the early days of the gospel;
for the apostle took notice of some that would not work at all,
and sharply reproved them, saying, "`they that would not work should not eat.`"
These are commonly a sort of busy-bodies, and meddlers with others`' matters,
while they neglect their own, and run into a worse way than the unbelievers;
for while they profess to be believers,
yet they do not take due care for those of their own household.

The charity that is proper to these, is to give them admonition and reproof,
and to convince them of their sloth and negligence; and if they submit to your reproof,
and are willing to amend their ways,
then care ought to be taken to help them into a way and means to support themselves;
and sometimes by a little help of this kind,
some have been reclaimed from the snares of their souls`' enemy.
But if they will not receive your wholesome counsel and admonitions,
but rather kick against it, either by their words or actions,
then Friends will be clear of such in the sight of God.
For it is unreasonable to feed those that will not be governed by you,
as they break the obligation of society by their disorderly walking;
for our communion does not stand only in attending meetings and hearing truth preached,
but in submission to the blessed Seed of truth in life and conduct,
and therein both the rich and the poor have fellowship one with another.

There are another sort that are made poor by the oppressions and cruelties of others.
These oppressed poor cry loud in the ears of the Almighty,
and in His own time He will avenge their cause.
But in the meantime there is a tenderness to be extended to them,
not knowing how soon it may be our turn to suffer.
And if there is need of council and advice,
or if any petitions can be made to any that are able to deliver them from the oppressors,
in such cases let all that are capable be ready and willing to advise, relieve,
and help the distressed.
This is an acceptable work of charity,
and a great comfort to those who are in painful afflictions,
and their souls will bless the instruments of their ease and comfort.

And my dear friends, as God has honored you with so high and holy a calling,
to be His servants and workmen in this great and notable day,
and to work together in His power, in setting forth His praise and glory in the earth,
and gathering together into one the scattered seed in this and other nations; oh,
let the dignity of your calling provoke and encourage you to be diligent
attenders upon this work and service that you are called to.
Let not your concerns in the world draw you from observing
the times and seasons appointed to meet together;
but you who are older, set a good example to the younger sort,
by a due observation of the hour appointed,
so that those who come one time will not discouraged by their long waiting for others,
and so arrive late the next time.
When the time for meeting has come, leave your business for the Lord`'s work,
and He will take care that your business will not suffer,
but will add a blessing upon it.

And when you have to deal with perverse, self-willed, or disorderly persons,
whom you have occasion to reprove and rebuke for the truth`'s sake,
and you find them proud and lofty, casting reproach upon you;
then is a time for the Lamb`'s meekness to shine forth,
and for you to feel your authority in the name of Christ to deal with such a one,
and to wait for the pure and peaceable wisdom from
above to bring down and confound their earthly wisdom.
And in this frame of mind,
let your labor together be to to pull the entangled sheep out of the thicket,
and to restore that which has gone astray to the fold again, if you can.
But if you cannot restore them, still you save yourselves from the guilt of their blood;
and if in the end they perish, their blood will be on their own head.
But on the other hand, if you allow their perverse spirits to enter,
and their provocations to have a place in you,
so as to kindle your spirits into the heat of passion, then you get hurt,
and are incapable of doing them any good;
but rather words will break out that will need repentance,
and the wicked will be stiffened and strengthened thereby,
and you will miss the service that you did really intend.

Therefore, dearly beloved, keep upon your watch.
Keep on your spiritual armor;
keep your feet shod with the preparation of the gospel of peace,
and the God of peace will be with you, and crown your endeavors with good success,
to your joy and comfort.
And He will raise His power up over all adversaries and opposers still more and more,
before which many shall bow and bend in your sight,
and so He will bring shame and confusion upon the rebellious,
who harden their hearts and stiffen their necks against the Lord and His Christ,
and kingdom.
For it is this kingdom that we seek to exalt in the earth,
notwithstanding all that Satan,
and all his evil instruments can do to hinder the
growth and progress of His blessed truth;
for it is written, "`Of the increase of His government and peace there will be no end.`"

And now, friends, I have cleared my conscience of what lay upon me for some time,
to write by way of remembrance, and as the exhortation of my life unto you.
And although my outward man decays,
yet in the inward man I am comforted in daily beholding
the great things that our God has done,
and is still doing for those that have their sole dependance upon Him.
So committing you to the grace of God as your director and preserver,
in these and all your various services unto which God has called you,
that by the operations of His mighty power you may
be kept blameless and unspotted of the world,
to His honor and your comfort,
and to the universal comfort and edification of the church,
that so praises and thanksgivings may fill your hearts and mouths, your families,
and your meetings; for He is worthy who is our tower, our support, the Lord of hosts,
the King of saints, to whom be glory, honor and renown, through this and all generations,
forever and ever.
Amen.

From your friend and brother,
in the communion and fellowship of the gospel of peace and purity,

[.signed-section-signature]
Stephen Crisp.

[.signed-section-context-close]
London, the 15th of the 7th month, 1690.

--

Passing now by other matters of this year, we pass on to the next, being 1691,
about the beginning of which G. Fox departed this life,
who even in this last period of his life wrote much,
and continued laborious without fainting.
The last epistle I find of his was addressed to his friends and brethren in Ireland, who,
because of the revolution and troubles there, suffered much,
chiefly at the hands of the Papists;
and therefore in the said epistle he exhorted his friends to steadfastness.
This was in the month called January; and the next day, being the first of the week,
and the 11th of the said month, he went to the meeting at Grace-church-street,
where he preached very effectually,
touching on many things with great power and clearness; and concluded with a prayer.
After the meeting had ended, he went to Henry Gouldney`'s, in White-Hart court,
near the meetinghouse, where he said to some that came with him,
that he thought he felt the cold strike to his heart as he came out of the meeting.
Yet he added, "`I am glad I was here.
Now I am clear, I am fully clear.`"
When those friends that were with him had withdrawn,
he lay down in his clothes upon a bed, but soon rose again.
Yet after a little time he lay down again, still complaining that he felt cold;
and finding his strength decaying, he not long after this undressed and went to bed,
where he lay in much contentment and resignation, continuing very sensible to the last.

His illness increasing, and perhaps perceiving that his end was at hand,
he sent for some friends and recommended to them the spreading
of books containing the doctrine of truth.
And to some others who came to visit him in his illness, he said, "`All is well,
the Seed of God reigns over all, and over death itself.
And though,`" he continued, "`I am weak in the body, yet the power of God is over all,
and the Seed reigns over all disorderly spirits.`"
He often used, even in his preaching, when he spoke of Christ, to call Him the Seed,
therefore those that were with him very well knew
what he meant when he spoke of the Seed.
Thus he lay in a heavenly frame of mind,
with his spirit being wholly exercised towards the Lord,
and grew weaker and weaker in body until, on the third day of the week,
and the third day of his sickness also, he piously departed this life.
About four or five hours before, being asked how he was, he answered, "`It matters not,
the power of the Lord is above all sickness and death.
The Seed reigns, blessed be the Lord.`"
And thus triumphing over death, he departed from here in peace,
and slept sweetly on the 13th of the month called January, about ten o`'clock at night,
in the 67th year of his age.
His body was buried near Bunhill-fields, on the 16th of the said month,
the corpse being accompanied by great numbers of his friends and of other people also.
For though he had had many enemies, yet he had also made himself beloved of many.

He was tall of stature, and pretty big-bodied, yet very moderate in food and drink;
neither did he yield much to sleep.
He was a man of a deep understanding, and of a discerning spirit.
And though his words were not always linked together by a neat grammatical connection,
and his speech sometimes seemed abrupt, as having a kind of gap,
yet he expressed himself intelligently;
and what was lacking in human wisdom was abundantly supplied with heavenly knowledge.
He was of a quick apprehension, and though his wit was not polished by human art,
yet he was ingenious.
And in his prayers, which generally were not very long, but were powerful,
there appeared a becoming gravity mixed with an awful reverence,
to the admiration of those who heard him.
His qualities are at length set forth by Thomas Ellwood, an eminent author,
who having been much with him, gave the following description of his character.

[.embedded-content-document.testimony]
--

He was indeed a heavenly-minded man, zealous for the name of the Lord,
and preferred the honor of God before all things.
He was valiant for the truth, bold in asserting it, patient in suffering for it,
unwearied in laboring in it, steady in his testimony to it, immoveable as a rock.
Deep he was in divine knowledge, clear in opening heavenly mysteries,
plain and powerful in preaching, fervent in prayer.
He was richly endued with heavenly wisdom, quick in discerning, sound in judgment;
able and ready in giving, discreet in keeping counsel; a lover of righteousness;
an encourager of virtue, justice, temperance, meekness, purity, chastity, modesty,
and self-denial in all, both by word and example.
Graceful he was in countenance, manly in personage, grave in gesture,
courteous in conduct, weighty in communication, instructive in discourse;
free from affectation in speech and carriage.
A severe reprover of hard and obstinate sinners;
a mild and gentle admonisher of such as were tender and sensible of their failings.
Not apt to resent personal wrongs; easy to forgive injuries,
but zealously earnest where the honor of God, the prosperity of truth,
or the peace of the church were concerned.
Very tender,
compassionate and pitiful he was to all that were under any sort of affliction;
full of brotherly love, full of fatherly care,
for indeed the care of the churches of Christ was daily upon him,
the prosperity and peace of which he diligently sought.

--

Still more is said of him to his praise, both by Thomas Ellwood and others,
but I will not detain my reader any longer therewith.
His wife, about six months before his death, came to him at London,
and being glad of his health (which was then better than some time before), she,
after some stay in the said city, returned home well satisfied,
leaving him at London where his general service to
the church seemed to be then most requisite.
After his decease an epistle was found, which was written with his own hand,
and left sealed up with this superscription, "`Not to be opened before the time.`"
What this signified, seemed to be a riddle; but he being now deceased,
it was judged to be the time to open this letter, which was directed to his friends,
and was as follows:

[.embedded-content-document.epistle]
--

[.letter-heading]
For the yearly and second-day`'s-meeting in London and to
all the children of God in all places in the world.
By and from G. Fox.

This is for all the children of God everywhere, that are led by His Spirit,
and do walk in His light, in which they have life, unity,
and fellowship with the Father and the Son, and with one another.

Keep all your meetings in the name of the Lord Jesus, which are gathered in His name,
by His light, grace, truth, power and Spirit;
by which you will feel His blessed and refreshing presence among you, and in you,
to your comfort and God`'s glory.

And now friends, all your meetings, both men`'s and women`'s, monthly, quarterly,
and yearly, etc. were set up by the power, and Spirit, and wisdom of God.
And in them you know that you have felt both His power, and wisdom,
and His blessed refreshing Spirit amongst you, and in you, to His praise and glory,
and your comfort; so that you have been a city set on a hill that cannot be hid.

And although many loose and unruly spirits have risen
at times to oppose you and your meetings,
both in print and in other ways, you have seen how they have come to nothing;
and the Lord has blasted them, and brought their deeds to light,
and made them manifest to be the trees without fruit, and wells without water,
and wandering stars from the firmament of God`'s power, and the raging waves of the sea,
casting up their mire and dirt.
And many of them have been like the dog that turned to his vomit,
and the sow that was washed, but turned again to the mire.
And this has been the condition of many, God knows.

Therefore, all stand steadfast in Christ Jesus your head, in whom you are all one,
male and female, and know His government,
and of the increase of His government and peace there shall be no end.
But there will be an end of the devil`'s, and of all those who are out of Christ,
and do oppose Him and His kingdom, whose judgment does not linger,
and their damnation does not slumber.
Therefore live and walk in God`'s and Christ`'s light, life,
Spirit and power that is over all (and in the Seed of it),
in love and innocency and simplicity.
And dwell in righteousness and holiness, and in His power and Holy Spirit,
in which God`'s kingdom does stand.
All keep your eyes on the new and heavenly Jerusalem that is from above, and is free,
with all her holy, spiritual children.

And as for this spirit of rebellion and opposition
that has risen both formerly and lately,
it is outside of the kingdom of God and heavenly Jerusalem,
and is for judgment and condemnation, with all its books, words and works.
Therefore friends are to live and walk in the power and Spirit of God that is over it,
and in the Seed that will bruise and break it to pieces;
in which seed you have joy and peace with God, and power and authority to judge it.
And your unity is in the power and Spirit of God that does judge it,
and all God`'s witnesses in His tabernacle go out against it, and always have and will.

And let no man live to self, but to the Lord, as they will die in Him;
and seek the peace of the church of Christ, and the peace of all men in Him,
for blessed are the peace-makers.
And dwell in the pure, peaceable, heavenly wisdom of God, that is gentle, full of mercy,
and easy to be entreated, all striving to be of one mind, heart, soul,
and judgment in Christ, having His mind and Spirit dwelling in you,
building up one another in the love of God which does edify the body of Christ,
His church, who is the holy head thereof.
Glory to God through Christ, in this and all other ages, who is the rock and foundation,
and the Immanuel, God with us, over all, the beginning and the end, amen.
Live and walk in Him, in whom you have life eternal, and in whom you will feel me,
and I you.

All children of the new Jerusalem that descends from above,
the holy city and temple which the Lord and the Lamb is the light of;
in this city they are born again of the Spirit.
So the Jerusalem that is above is the mother of those who are born of the Spirit.
And so those who come, and who have come, to heavenly Jerusalem,
are those who receive Christ; and He gives them power to become the sons of God,
and are born again of the Spirit, so that the Jerusalem that is above is their mother.
These come to the heavenly mount Zion, and to the innumerable company of angels,
and to the spirits of just men made perfect;
and have come to the church of the living God, written in heaven,
and have the name of God, and the city of God written upon them.
So then, here is a new mother that brings forth a heavenly and a spiritual generation.

There is no schism, nor division, nor contention, nor strife, in heavenly Jerusalem,
nor in the body of Christ, which is made up of living stones, a spiritual house.
And Christ is not divided, for in Him there is peace.
Christ says, "`In Me you have peace.`"
He is from above, and not of this world; but in the world below, in the spirit of it,
there is trouble.
Therefore keep in Christ, and walk in Him.
Amen.

[.signed-section-signature]
G+++.+++ Fox

[.postscript]
====

P+++.+++ S. Jerusalem was the mother of all true Christians before the apostasy;
and since then, the outward Christians are broken into many sects,
and they have gotten many mothers.
But all who have come out of the apostasy by the power and Spirit of Christ,
have Jerusalem above as their mother, who does nourish all her spiritual children.

====

[.signed-section-signature]
G+++.+++ Fox

[.signed-section-context-close]
Read at the Yearly Meeting in London, 1691.

--

This year I find that William Goodridge of Banwell, in Somersetshire,
was released from prison, where he had been confined about thirteen years.
He had been premunired for refusing to take the oath,
and his goods--whereof the moveables were estimated
at about two hundred and forty-four pounds,
and the real estate counted worth sixty pounds per annum--were confiscated.
To suffer the spoiling of goods in this way has been the lot of many others,
and among these was Benjamin Brown, an ancient man, of Brownish in Suffolk, who also,
for not taking the oath, was stripped of all he had,
so that his wife and child were made to lie on the floor without a bed.

Now time calls me to say something of the sad apostasy of George Keith,
who being in Pennsylvania, made a great bustle there.
He was a witty person, and was esteemed very learned;
and at the university had obtained the degree of master of arts.
He often also gave proofs of a high soaring knowledge,
and was very ready to show from philosophy the reasons
and causes of many things in the creation;
but the doctrine of Francis Mercurius, baron of Helmons,
concerning the transmigration of souls, became so palatable to him,
that he not only in some manner approved it,
but also was believed to have contributed to the
book containing two hundred queries about that matter,
great part of which (as I have been informed) he acknowledged to have written himself,
though it appeared in public without the author`'s name.
But this notion meeting with no acceptance among the Quakers,
his love to them began to abate.
And his discontent increased,
because two persons who opposed him had allegedly used some unwarrantable expressions,
but were not as sharply reproved as he, who was of a fiery temper, desired.
He accused these two men of saying that the light within
was sufficient to salvation without anything else;
and from this he endeavored to prove that they excluded
the man Jesus Christ as not necessary to salvation;
but they denied this to be their doctrine.

He afterwards said that William Stockdell,
one of the abovementioned two persons in Philadelphia,
had charged him with preaching two Christs, because he preached faith in Christ within,
and in Christ without us.
Now though W. Stockdell would not allow this to be true,
and some of the hearers also denied that it had been said,
yet G. Keith blew upon the fire of this quarrel, and so got some adherents.
He also charged the deputy-governor, Thomas Lloyd,
with having said that faith in Christ without us, as he died for our sins and rose again,
was not necessary to our salvation.
But others said that these words were not so, and that the matter was not fairly stated.
For the question was not whether faith in Christ without us,
as He died for our sins and rose again, was not necessary to our salvation;
but whether such faith in the outward history of Christ`'s death
and resurrection were indispensably necessary to all mankind,
and that none could be saved without it, even if they had not the means, opportunity,
or capacity to know or receive it.
This being asserted,
it was thought that such a position did not only exclude from salvation entire nations,
but also infants, and deaf and dumb persons.
But it had been better if such questions never had been started,
for the passionate maintaining of a different position often breeds strife and contention.
And George Keith, with some others, having now separated themselves from the society,
said that his dissatisfaction was only with some unsound Quakers in America;
but that he was in unity with all faithful friends in England.

He now began to behave himself very disrespectfully,
and was on that account sharply reproved by the aforesaid Thomas Lloyd;
to whom he did not hesitate to speak in a reproachful way, charging him with impudence,
and saying that he was unfit to be a governor, and that "`his name would stink,`" etc.
And because some members of the council did not expect to be better treated
by him (since he had called one of the magistrates an "`impudent rascal`"),
this was much resented, and even more,
because G. Keith had published a paper wherein he not only scandalously
slandered the diligence of the magistrates in the restraining of robbers,
but also their judicial proceedings against murderers.
The consequence of this case was that G. Keith and one Thomas Budd,
who with him had compiled of the aforesaid paper, were fined for it;
but yet the government was so moderate that the fine was never exacted.
Nevertheless, G. Keith did not hesitate to make a great clamor about his sufferings;
and about two years after this he came again into England
to make his complaint to the church at London.

This year in the month called August, Stephen Crisp deceased near London.
He had long been weak in body, and was much afflicted with the stone,
but nevertheless had continued his ministry of the gospel.
His service was very acceptable because he had a gift beyond many,
being not only sound in doctrine and judgment, but grave and elegant in his utterance,
and well-qualified for the convincing of his hearers, often touching them to the heart,
so that he generally met with a great concourse of people.
Four days before his decease, lying sick in bed and being under great pain,
he was visited by George Whitehead, to whom he said in substance,
"`I see an end of mortality, and yet I cannot come at it.
I desire the Lord to deliver me out of this painful body.
If He will but say the word, it is done.
Yet there is no cloud in my way.
I have a full assurance of my peace with God in Christ Jesus.
My integrity and uprightness of heart is known to the Lord,
and I have peace and justification in Jesus Christ, who made me so.`"
The day before his departure, G. Whitehead having come again to see him,
found him in a dying state and almost speechless; yet he was understood to say, "`I hope,
I am being gathered, I hope, I hope.`"
G+++.+++ Whitehead upon parting from him,
asked him whether he had anything he desired to communicate to friends;
to which he gave this answer, "`Remember my dear love in Jesus Christ to all friends.`"
The next day, being the 28th of the aforesaid month, he died at Wandsworth,
about five miles from London.
Many of his sermons taken in short hand from his mouth are published in print,^
footnote:[These thirty-two sermons are available at friendslibrary.com]
and give proof of his having indeed been an able minister of the gospel.

In this year died also Catharine Evans, who, as has been mentioned before,
had been long imprisoned at Malta.
She had suffered much for her religion.
In the year 1657, having at Salisbury exhorted the people to repentance,
this so incensed the magistrates, that,
by order of justice Henry Ditton and mayor Robert Good,
she was stripped and fastened to the whipping-post in the market, and then whipped.
Afterwards coming there again and speaking to the people in the market by way of admonition,
she was sent to Bridewell, and put into a dark nasty place.
After her return from Malta, imprisonment fell to her share several times;
once at Welchpool in Montgomeryshire in the year 1666, for refusing to swear;
and several years after this she was also imprisoned at Bristol.
But after many adversities and great sufferings, having lived to a great age, she died,
and so entered into everlasting rest.

Now I return again to George Keith,
who appeared in the annual assembly at London in the year 1694,
but there he showed himself so passionate and boisterous,
that no means could be found to resolve the difference.
He seemed to get adherents among some of the Separatists around London;
but when these also soon grew weary of him,
he got a place called Turner`'s-hall to preach in.
Here at first he had a great concourse of people,
since novelties generally beget curiosity.
But seeming more and more to court those of the church of England,
and falling in with the Episcopalians,
he began to lose his esteem among people of other persuasions,
especially when at length he entirely conformed to the national
church which he had formerly zealously attacked in print.
And in the process of time, he took a gown, and was ordained a preacher among them.
After this he sometimes preached with the surplice^
footnote:[A white, loose fitting vestment,
worn over other clothing by Episcopalian ministers during religious ceremonies.]
on,
which in all probability he would have abhorred even before he joined with the Quakers;
for he had been a member of the Presbyterian Kirk of Scotland,
which always has been a zealous opposer of the episcopal ceremonies.
And since George Keith had contradicted the doctrine
which he had formerly asserted and defended;
and also charged the Quakers with a belief that they never had acknowledged to be theirs,
they found themselves obliged publicly to set forth their faith anew in print,
which they had often before asserted both in words and writing,
thereby to manifest that their belief was really orthodox,
and agreeable with the Holy Scriptures.
This they did by the following treatise,
which in the year 1693 came forth in print in London, as follows:

[.embedded-content-document.treatise]
--

[.letter-heading]
The Christian Doctrine and Society of the People called Quakers, Cleared, etc.

Whereas several accounts have been lately published in print regarding some recent
divisions and disputes between some persons under the name of Quakers in Pennsylvania,
having to do with several fundamental doctrines of
the Christian faith (as is pretended by one party),
and because occasion has herein been taken by our
adversaries to reproach both the Christian ministry,
the whole body of the people commonly called Quakers,
and their holy and Christian profession both in England and elsewhere
(though they are in no way involved in the said division,
but were rather grieved and troubled at it,
and at the indiscreet and reproachful management of it in print):

We are, therefore, tenderly concerned for truth`'s sake, on behalf of the said people,
to use our just endeavors to remove the reproach,
and all causeless suspicion concerning us regarding those doctrines of
Christianity that are supposed to be in question because of the said division.
We therefore, in the fear of God, and in simplicity and plainness of His truth received,
solemnly and sincerely declare what our Christian belief and profession has been,
and still is, in respect to Jesus Christ the only begotten Son of God, His suffering,
death, resurrection, glory, light, power, great day of judgment, etc.

[.offset]
We sincerely profess:

Faith in God by His only begotten Son Jesus Christ, as being our light and life,
our only way to the Father, and also our only mediator and advocate with the Father.

That God created all things; He made the worlds by His Son Jesus Christ,
He being that powerful and living Word of God by whom all things were made;
and that the Father, the Word, and Holy Spirit are one, in Divine Being inseparable;
one true, living and eternal God, blessed forever.

Yet that this Word, or Son of God, in the fullness of time, took flesh,
became perfect man, according to the flesh,
descended and came of the seed of Abraham and David,
but was miraculously conceived by the Holy Spirit, and born of the Virgin Mary.
And also further, "`He was declared powerfully to be the Son of God,
according to the Spirit of sanctification, by the resurrection from the dead,`" Rom.
1:4.

We believe that in the Word (or Son of God) was life,
and the same life was the light of men;
and that He was that "`true light which enlightens every man coming
into the world;`" and therefore men are to believe in the light,
that they may become the children of the light.
Hereby we believe in Christ the Son of God as He is the light and life within us;
having sincere respect and honor to, and belief in Christ herein,
even as we do in His own unapproachable and incomprehensible glory and fullness;
for He is the fountain of life and light, and the giver thereof unto us;
being--both as He is in Himself, and as He is in us--not divided.
And we believe that as man, Christ died for our sins, rose again,
and was received up into glory in the heavens; He having, in His dying for all,
been that one great universal offering and sacrifice for peace,
atonement and reconciliation between God and man;
and He is "`the propitiation not for our sins only,
but for the sins of the whole world.`"
"`We were reconciled by His death, but saved by His life.`"

We believe that Jesus Christ,
who sits at the right hand of the throne of the majesty in the heavens,
yet is also a king, high-priest, and prophet, in His church,
"`a minister of the sanctuary, and of the true tabernacle which the Lord pitched,
and not man.`"
He is intercessor and advocate with the Father in heaven,
and there appears in the presence of God for us,
being touched with the feeling of our infirmities, sufferings and sorrows.
And also by His Spirit in our hearts,
"`He makes intercession according to the will of God,`" crying, Abba, Father.

We believe that for any whom God has gifted,
and sincerely called to preach faith in the same Christ, both as within and without us,
this cannot be to preach two Christs, but rather one and the same Lord Jesus Christ,
having respect to those degrees of our spiritual knowledge of Christ Jesus in us,
and to His own unspeakable fulness and glory as in Himself, in His own entire being,
wherein Christ Himself and the least measure of His light or life (as in us,
or in mankind) are not divided nor separable,
any more than the sun is separable from its own light.
And as He ascended far above all heavens,
"`that He might fill all things,`" His fulness cannot
be comprehended or contained in any finite creature;
but in some measure it is known and experienced in us,
as we are capable to receive the same,
for "`of His fulness we have received grace for grace.`"
Christ our Mediator received the Spirit, not by measure, but in fulness;
but to every one of us, grace is given "`according to the measure of His gift.`"

We believe that the gospel of the grace of God should
be preached in the name of the Father,
Son, and Holy Spirit, being one in power, wisdom, and goodness, and indivisible,
or not to be divided, in the great work of man`'s salvation.

We sincerely confess and believe in Jesus Christ, both as He is true God and perfect man;
and that He is the author of our living faith in the power and goodness of God,
as manifested in His Son Jesus Christ, and by His own blessed Spirit, or divine unction,
revealed in us, whereby we inwardly feel and taste His goodness, life, and virtue;
and our souls live and prosper by and in Him.
And the inward sense of this divine power of Christ, and faith in the same,
and this inward experience, is absolutely necessary to make a true, sincere,
and perfect Christian, in spirit and life.

We believe that divine honor and worship is due to the Son of God; and that He,
in true faith, is to be prayed unto, and the name of the Lord Jesus Christ called upon,
as the primitive Christians did,
because of the glorious union or oneness of the Father and the Son;
and that we cannot acceptably offer up prayers and praises to God,
nor receive a gracious answer or blessing from God,
but in and through His dear Son Christ.

We believe that the body of Christ that was crucified was not the godhead,
yet by the power of God it was raised from the dead;
and that the same Christ that was therein crucified,
ascended into heaven and glory is not at all questioned by us.
His flesh saw no corruption, it did not corrupt;
but yet doubtless His body was changed into a more glorious and heavenly
condition than when it was subject to various sufferings on earth.
But how and what manner of change it experienced after it was raised from
the dead so as to become such a glorious body as it is declared to be,
is too wonderful for mortals to conceive, to apprehend or to pry into,
and is more fitting for angels to see.
The Scripture is silent on this point as to the manner thereof,
and we are not curious to inquire or dispute about it;
nor do we esteem it necessary to make ourselves wise above what is written concerning
the manner or condition of Christ`'s glorious body as it is in heaven;
no more than to inquire how Christ appeared in various manners or forms after His resurrection,
or how He came in among His disciples with the doors being shut;
or how He vanished out of their sight after He had risen, etc.
However, we have cause to believe His body, as in heaven,
is changed into a most glorious condition, far transcending what it was in on earth,
otherwise how could our low body be changed so as
to be "`made like unto His glorious body.`"
For when He was on earth, and attended with sufferings,
He was said to be like unto us in all things, sin only excepted;
which may not be so said of Him as He is now in a state of glory (which He prayed for);
otherwise where would be the change both in Him and us?

We believe that true and living faith in Christ Jesus
the Son of the living God has respect to,
1) His entire being and fullness, that is, to Him entirely as in Himself,
and as all power in heaven and earth is given unto Him; and also,
2) to the same Son of God as He inwardly makes Himself
known to the soul in every degree of His light,
life, Spirit, grace, and truth.
He is both the Word of faith, and a quickening Spirit in us,
whereby He is the immediate cause, author, object,
and strength of our living faith in His name and power,
and of the work of our salvation from sin and the bondage of corruption.
The Son of God cannot be divided from the least or lowest
appearance of His own divine light or life in us or in mankind,
any more than the sun can be divided from its own light.
We do not set up the sufficiency of His light within
us in opposition to Him as the man Christ Jesus,
or in opposition to His fullness considered as in Himself;
nor do we say that any measure or degree of light received from Christ, as such,
can properly be called the fullness of Christ, or Christ in fullness;
nor does this exclude Him, so considered, from being our complete Savior.
For to know Christ Himself as our light, our life, and our Savior, is so congruous,
that without His light we could not know His life,
nor could we experience Him to save us from sin or deliver us from darkness,
condemnation or wrath to come.
And where the least degree or measure of this light
and life of Christ within is sincerely waited in,
followed and obeyed, there is a blessed increase of light and grace known and felt,
just as "`the path of the righteous shines more and more until the perfect day.`"
Hereby a growing in grace,
and in the knowledge of God and of our Lord and Savior Jesus Christ, has been,
and is truly experienced.
And this light, life, or Spirit of Christ within (for they are one divine principle),
is sufficient to lead into all truth,
having in it the various ministrations both of judgment and mercy,
both of law and gospel,
even that gospel which is preached in every intelligent creature under heaven.
It does not only (as in its first ministration) manifest sin,
and reprove and condemn for sin;
but also excites and leads those who believe in it to true repentance,
and thereby to receive that mercy, pardon, and redemption in Christ Jesus,
which He has obtained for mankind in those gospel terms of faith in His name,
true repentance and conversion to Christ.

So that the light and life of the Son of God within,
truly obeyed and followed--as being the principle of the second or new covenant,
or the Seed or Word of faith in all men--this does not leave men or women,
who believe in the light, under the first covenant, nor as the sons of the bond-woman,
as the literal Jews were when they had gone from
the Spirit of God and His Christ in them;
but it naturally leads them into the new covenant, in the new and living way,
and to the adoption of sons, to be children and sons of the free woman,
or Jerusalem above.

It is true that we ought not to lay aside, nor in any way undervalue,
but rather highly esteem true preaching and the holy Scriptures.
Nor should we undervalue the sincere belief and faith of Christ as He died for our sins,
and rose again for our justification; together with His inward and spiritual appearance,
and His work of grace in the soul, which livingly opens the mystery of His death,
and perfectly effects our reconciliation, sanctification, and justification.
And we say that wherever Christ qualifies and calls any
to preach and demonstrate the mystery of His coming,
death, and resurrection, etc. even among the Gentiles,
there He ought accordingly to be both preached, believed, and received.

Yet, supposing there have been, or are such pious and conscientious Gentiles,
in whom Christ was and is as a seed or principle of the second or new covenant,
as the light or the Word of faith;
and supposing that these live uprightly and faithfully to the measure of light they have,
or to what is made known of God in them;
and supposing also that these have not the outward advantage of preaching, Scripture,
or the knowledge of Christ`'s outward coming; can such, thus considered,
be justly excluded from Christianity, or from the covenant of grace, as to the virtue,
life, and nature thereof?
Or must all be excluded from any true knowledge or faith in Christ within them,
unless they also have the knowledge of Christ without them?
Surely no!
For that would imply insufficiency in Christ and His light within them,
and would frustrate God`'s good purpose and promise in Christ,
and His free and universal love and grace to mankind in sending His Son.
We charitably believe the contrary; namely,
that such conscientious Gentiles must have some true faith in,
and some benefit from Christ and His mediation,
because of God`'s free love in Christ to all mankind,
and Christ`'s "`dying for all men,`" and His being given "`as a light to the Gentiles,
and for salvation to the ends of the earth;`" and thus, living piously,
sincerely and faithfully according to their measure of His light in them,
they may be accepted and saved.
For we cannot reasonably consider a sincere, pious, or godly man,
to be wholly void of true Christianity, regardless what nation he be of;
for none can come to God or to godliness but by Christ, that is,
by His light and grace in them.
Nevertheless we grant that, if there be such pious, sincere men or women,
as have not the Scriptures or the knowledge of Christ (as having been outwardly crucified,
raised, etc.),
then these are not perfect Christians according to knowledge and understanding,
or according to points of doctrine and the outward profession of Christ.
They may be sincere and perfect Christians in kind or nature, in life and substance,
though not so in knowledge and understanding.
A man or woman having the life and fruits of true Christianity,
the fruits of the Spirit of Christ in them, who can talk little of creeds, points,
or articles of faith (or perhaps cannot even read letters),
yet may be a true Christian in spirit and life.
Some indeed could die for Christ, who could not dispute for Him.
And we also believe that even infants that die in
innocence are not excluded from the grace of God,
nor from salvation in and by Christ Jesus, who is in some measure in them,
and they under God`'s care and special Providence.
See Matt, 18:2, 10.

And though we had the holy Scriptures of the Old and New Testament,
and a belief in Christ crucified and risen, etc.,
we never truly knew the mystery thereof,
until we were turned to the light of His grace and Spirit within us.
We knew not what it was to be reconciled by His death, and saved by His life;
or what it was to know the fellowship of His sufferings, the power of His resurrection,
or to be made conformable unto His death, until He opened our eyes,
and turned our minds from darkness unto His own divine life and light within us.

Notwithstanding, we do sincerely and greatly value the holy Scriptures,
and the preaching and teaching of faithful, divinely inspired, gifted,
and qualified persons, and ministers of Jesus Christ,
knowing such to be great outward helps, and instrumental in His hand, and by His Spirit,
for conversion, wherever God is pleased to afford those outward helps and means.
And we neither do, nor may,
regard the sufficiency of the light or Spirit of Christ within in any way so as to disregard,
dis-esteem, reject, or undervalue these outward helps or means;
for they all proceed from the same light and Spirit,
and tend to turn men`'s minds thereunto, and all center therein.

Nor can the holy Scriptures or true outward preaching,
be justly set in opposition to the light or Spirit of God, or Christ within;
for His faithful messengers are ministers thereof,
being sent to turn people to the same light and Spirit in them.

It is certain, that great is the mystery of godliness in itself,
in its own being and excellency: namely,
that God should be and was "`manifest in the flesh, justified in the Spirit,
seen of angels, preached unto the Gentiles, believed on in the world,
and received up into glory.`"

And it is a great and precious mystery of godliness and Christianity also,
that Christ should be spiritually and effectually in men`'s hearts,
to save and deliver them from sin, Satan, and the bondage of corruption;
for He is thus revealed in true believers, and dwells in their hearts by faith,
"`Christ within the hope of glory,`" our light and life, who is "`made unto us wisdom,
righteousness, sanctification, and redemption,`" 1 Cor.
1:30. And therefore this mystery of godliness, as in its own being and glory,
and also as in men (in many hidden, and in some revealed),
has been and must be testified, preached, and believed,
wherever God is pleased to give the commission,
and prepare people`'s hearts for the same, and not in the will of man.

Concerning the resurrection of the dead, and the great day of judgment yet to come,
beyond the grave, or after death,
and Christ`'s coming outwardly to judge the quick and the dead,
we have great reason to believe, and not to question,
what the holy Scriptures plainly declare and testify in these matters,
having always been ready to embrace the testimonies
and prophecies of Christ and His apostles.

[.offset]
1+++.+++ As for the doctrine of the resurrection:

"`If in this life only we have hope in Christ,
we are of all men the most miserable,`" 1 Cor.
15:19. We sincerely believe,
not only in a resurrection in Christ from the fallen sinful state here,
but a rising and ascending into glory with Him hereafter; that when He at last appears,
we may appear with Him in glory, Col.
3:4. 1 John 3:2. But that all the wicked who live
in rebellion against the light of grace,
and die finally impenitent, shall come forth to a resurrection of condemnation.

And we believe that the soul or spirit of every man and
woman shall be reserved in its own distinct and proper being,
(so as there shall be as many souls in the world to come as in this,) and every seed,
yes every soul, shall have its own proper body, as God is pleased to give it, 1 Cor.
15+++.+++ A natural body is sown, a spiritual body is raised;
that being first which is natural, and afterward that which is spiritual.
And though it is said that "`this corruptible shall put on incorruption,
and this mortal shall put on immortality,`" yet the change shall
be such as flesh and blood cannot inherit the kingdom of God,
neither does corruption inherit incorruption, 1 Cor.
15+++.+++ We shall be raised out of all corruption and corruptibility, out of all mortality;
and the children of God and of the resurrection shall
be equal to the angels of God in heaven.

And as the celestial bodies do far excel terrestrial,
so we expect our spiritual bodies in the resurrection
shall far excel what our bodies now are;
and we hope that none can justly blame us for thus
expecting better bodies than they now are.
Howbeit, we esteem it very unnecessary to dispute or question how the dead are raised,
or with what body they come;
but rather submit such things to the wisdom and pleasure of the Almighty God.

[.offset]
2+++.+++ As for the doctrine of eternal judgment:

God has committed all judgment unto His Son Jesus Christ;
and He is both judge of the living and dead, and of the states and ends of all mankind,
John 5:22, 27; Acts 10:42; 2 Tim.
4:1; 1 Pet.
4:5.

And we believe that there shall hereafter be a great harvest,
which is the end of the world, a great day of judgment,
and concerning the judgment of that great day, the holy Scripture is clear, Mat.
13:39-41, ch.
10:15, 11:24, and Jude 6. "`When the Son of Man comes in His glory,
and all the holy angels with Him, then shall He sit upon the throne of His glory,
and before Him shall be gathered all nations, etc.`"
Matt.
15:31, 32, to the end, compared with ch.
22:31. Mark 8:38; Luke 9:26, and 1 Cor.
15:52; 2 Thes.
1:7, 8, to the end, and 1 Thes.
4:16; Rev.
20:12-15.

We believe that this blessed heavenly man, this Son of Man,
who has so deeply suffered and endured so many great
indignities and persecutions from His adversaries,
both to Himself and His members and brethren, shall at last,
even in the last and great day, signally and manifestly appear in glory and triumph,
attended with all His glorious heavenly host and retinue before all nations,
before all His enemies, and those who have denied Him.
And this will be to their great terror and amazement,
that this most glorious heavenly man, and His brethren,
that have been so much contemned and disregarded,
should be thus exalted over their enemies and persecutors, in glory and triumph;
and that they who have suffered with Him,
should appear with Him in glory and dignity when He thus appears at last.
Christ was judge of the world, and the prince thereof, when on earth, John 9:39,
and 12:31. He is still judge of the world, the wickedness and the prince thereof,
by His light, Spirit, and gospel in men`'s hearts and consciences, John 16:8, 11; Matt.
12:20; Isa.
42:1; Rom.
2:16; 1 Pet.
4:6. And He will be the judge and final determiner thereof in that great day appointed,
"`God having appointed a day wherein He will judge the world
in righteousness by that Man whom He has ordained.`"
Christ foretold it shall be more tolerable for those of
the land of Sodom and Gomorrah in the day of judgment,
than for that city or people that would not receive His messengers or ministers.
etc. Matt.
10:15, and see chap.
11:24, and Mark 6:11; Luke 10:12-14.
It is certain that God knows how to deliver
the godly out of all their trials and afflictions,
and at last to bring them forth, and raise them up into glory with Christ;
so He knows also how to reserve the unjust and impenitent
unto the day of judgment to be punished,
2 Pet.
2:9. He will bring them forth unto the day of destruction, Job 21:30.
The Lord can and will reserve such impenitent,
presumptuous and rebellious criminals,
as bound under chains of darkness (as were the fallen angels),
unto the judgment of the great day, Jude 6; Matt.
25:30. It is not for us to determine or dispute the manner how they shall be so reserved;
but leave it to God; for He knows how.

[.offset.centered]
A Postscript relating to the doctrine of the Resurrection and eternal Judgment.

At the last trumpet of God, and the voice of the archangel,
the dead shall be raised incorruptible, the dead in Christ shall rise first, 1 Cor.
15:52; 1 Thes.
4:16, compared with Matt.
24:31.

Many in this time of probation are often alarmed
in conscience by the word and voice of God,
who yet stop their ears and slight His warnings;
but they cannot stop their ears or escape the great and final alarm of the last trumpet,
for it will unavoidably seize upon, and further awaken them finally to judgment.
They that will not be alarmed in their consciences unto repentance here,
nor leave off their sins here, must certainly be alarmed unto judgment hereafter.

Whoever will willfully shut their eyes, hate, contemn, or shun the light of Christ,
or His appearance within, shall at last be made to see,
and not be able to shun or hide themselves from His glorious
and dreadful appearance from heaven with His mighty angels,
as with lightning and flaming fire, to render vengeance on all that know not God,
nor obey the gospel of our Lord Jesus Christ, 1 Thes.
4:16; Matt.
24:27; Luke 17:24; Dan.10:6; Job 37:3.

And though many now evade and reject the inward convictions and judgment of the light,
and shut up the records or books thereof in their own consciences,
these shall be at last opened,
and every one shall be judged by the things recorded therein, according to their works,
Rev.
20:12-15.

[.signed-section-closing]
Signed in behalf of our Christian profession and the people aforesaid by,

[.signed-section-signature]
George Whitehead, Charles Marshall, Ambrose Rigge, John Bowater, William Fallowfield,
John Vaughton, James Parke, William Bingley.

--

This paper generally gave satisfaction, and was also well received in Holland,
where having translated it into Dutch, I got it published in print.
Now since Francis Bugg, an envious apostate,
charged the Quakers with some Socinian notions; and being encouraged by some churchmen,
endeavored also to render them odious to the government,
the following confession of faith (signed by thirty-one persons,
of which G. Whitehead was one) was in December presented to the parliament:

[.embedded-content-document.paper]
--

[.offset]
Be it known to all that we sincerely believe and confess:

[.numbered-group]
====

[.numbered]
I+++.+++ That Jesus of Nazareth, who was born of the Virgin Mary, is the true Messiah,
the very Christ, the Son of the living God, to whom all the prophets gave witness;
and that we do highly value His death, sufferings, works, offices,
and merits for the redemption of mankind, together with His laws, doctrine,
and ministry.

[.numbered]
II+++.+++ That this very Christ of God,
who is the Lamb of God that takes away the sins of the world, was slain, was dead,
and is alive, and lives forever in His divine, eternal glory, dominion,
and power with the Father.

[.numbered]
III+++.+++ That the holy Scriptures of the Old and New Testament, are of divine authority,
as being given by the inspiration of God.

[.numbered]
IV+++.+++ And that magistracy or civil government is God`'s ordinance,
the good ends thereof being for the punishment of evil-doers,
and the praise of them that do well.

====

--

By this and the similar writings,
the eyes of many that were at the helm began to be more opened;
and even among the bishops there were some inclined to moderation;
for the king endeavored as much as he could to promote the
most moderate among the churchmen to those high places;
so that prejudice, which had blinded many in respect to the Quakers,
began to abate more and more.
But yet there was one thing that continually caused them much hardship, namely,
their refusing to swear;
for by reason of this they were not only deprived of their rights as freemen,
but also of giving evidence in courts of judicature.
They did not therefore omit from time to time to petition the parliament,
wherein they desired to be relieved of this heavy burden,
though hitherto they had not been able to obtain this favor.
Therefore, on the 26th of November, they delivered a petition to the parliament,
setting forth the great sufferings they had endured because their
solemn declaration would not be accepted instead of an oath.
This petition concluded thus:

[.embedded-content-document.paper]
--

We therefore earnestly and humbly request,
that you will be pleased to give leave to bring in a bill,
allowing for our solemn answer, affirmation or denial, to be accepted instead of an oath,
to relieve us in the cases aforesaid,
or in such of them as you in your wisdom shall see fit.
And we freely submit, that if anyone reputed to be a Quaker shall falsify the truth,
and be duly convicted thereof,
that every such person shall undergo the like pains and
penalties as are provided against perjured persons.

[.signed-section-signature]
William Mead, William Bingley, George Whitehead, Samuel Waldenfield, William Crouch,
John Staploe, Walter Rental, William Macker, Thomas Hart, Joseph Wright,
Jr. Michael Russet, Theodore Ecclestone.

--

[.offset]
The petition being read in the House of Commons, they came to the following resolution:

[.embedded-content-document]
--

A petition of the people called Quakers was read.
Resolved, that the consideration thereof be referred to a committee;
and that they report their opinions therein to the house.

--

[.offset]
A committee being ordered accordingly, sat thereupon, and gave their judgment as follows:

[.embedded-content-document]
--

Upon the whole it is the opinion of this committee,
that the Quakers ought to be relieved according to the request of their petition.

--

Nevertheless, nothing was obtained during that session;
for their enemies were yet powerful enough in parliament,
that they found means to retard this beneficial work, and to stay the progress of it.
For though the Quakers were now not liable to persecution
on account of their public worship,
they were still vulnerable to other abuses and ill-treatment
having not yet been relieved in the case of oaths.
Therefore, on the 22nd of December, in the year 1694,
a representation of their case of not swearing,
being signed on their behalf by Theodore Ecclestone,
was delivered to the members of parliament, and was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
A brief representation of the Quakers`' case of not swearing;
and why they might have been, and yet may be relieved therein by Parliament.

It is a certain truth, that among Christians, and Protestants especially,
there are several particular things in religion which
are conscientiously scrupled by some as unlawful,
and which others esteem orthodox.
It is therefore not to be wondered at,
that the Quakers differ from many others (though not from all) in this case of oaths;
they believing they are absolutely forbidden to swear in any case by the positive command
of Christ in Matthew 5:12. And that this is undeniably their true Christian persuasion,
is evidenced by their sufferings these many years for not swearing.

Their case may therefore be worth the charitable notice of the government,
in enacting a law to relieve them therein;
and not keeping them and their families exposed to ruin because of their religious persuasion;
who, along with their neighbors, cheerfully pay taxes for the support of the government,
and who by their trades and industry, according to their capacities,
advance the national stock.

It may therefore, be humbly offered,
that it is not in the interest of the government to refuse them this relief.

Their industry in trade, both at sea and land, brings profit to the government;
and the station they stand in as merchants, farmers, manufacturers,
improvers of lands and stocks, is advantageous to their neighbors as well as to others.
And as it seems not in the interest of the government in general
that they should be discouraged in their honest industry,
so neither is it in the interest of any eminent part of the government (namely,
the judges), that they should not be relieved.

For the frequent lawsuits that are brought against the Quakers,
before the chancery and exchequer judges, are no doubt very troublesome and burdensome,
because of the difficulty of obtaining a just outcome, for lack of swearing,
whereby justice is delayed, and their causes often held very long.
And no doubt when just judges see the Quakers wronged and abused,
and cannot relieve them, this is irksome to them; so that, it is humbly conceived,
it would be a great ease to these courts to have
the Quakers relieved in this case of oaths.

It is also to the advantage to the king`'s other courts,
to be able to use the evidence of one who is called a Quaker,
in their witnessing to a bill, bond, debt, or deed of indenture;
or when they give testimony in cases of unnatural deaths, cases of trespass or felony,
etc.

Seeing then that their relief is so needful to them, so harmless to all,
and so useful to the government and their neighbors;
let us a little consider the common objections; which may be summed up in short thus:

[.numbered-group]
====

[.numbered]
__First objection:__ How shall we be certain that they speak the truth?

[.numbered]
__Secondly:__ Why should the laws be altered for them?

[.numbered]
__Thirdly:__ This would be to tear down old foundations.

[.numbered]
__Fourthly:__ And it would allow them into the government.

====

It is hoped that these will not be difficult to answer one by one,
and that to reasonable satisfaction.

__As to the first, namely, the doubt of certainty:__
It may be rationally affirmed that whosoever is bound to tell the truth,
especially against a man`'s own interest (which is where the temptation, if any,
mainly lies), such are either so bound by the law of God, or by the law of men, or both.

Now the obligation on the conscience by the law of God is binding upon all good men,
whether they give answers with an oath, or by solemn affirmation in the fear of God;
and dishonest men are only ever bound by the penal laws of men.
And if these penal laws are made equally severe to those that give
fallacious answers both without an oath and by an oath,
it would then be equally effectual and binding both
to them that give answers without swearing,
and to them that swear.

__As to the second objection, that it would be an alteration of the law:__
It would not be an alteration of the substance of the law, but only of a circumstance;
and if the change has no detriment in it, but is really an amendment,
and is a conveniency to an honest and industrious people, why should it not be done?
What sessions of parliament is there that passes,
but some law or other is made for the ease, security, or relief of some subjects?

If foreigners are too hard for our sea-faring people,
then an act of parliament is soon sent out to prevent it.
If our poor at home need silk to work with,
how soon is it granted by an act of parliament?
And shall the ease of trade be so quickly granted,
while the ease of conscience be so long denied,
knowing that the scruple of this people arises from a positive command of Christ?

__And for the third objection, that this is to tear down old foundations:__ I answer, not so;
it is rather to mend them, which is the proper work of parliament.

Did not parliament abrogate popery, with all its claims to antiquity?
Did not a parliament make the act of __Habeas Corpus__^
footnote:[The act of __Habeus Corpus__ gave persons who were deprived of their
liberty the right to challenge the legality of their arrest or detention.]
against the claim of royal prerogative?
And was it more reasonable to protect a subject from
perpetual imprisonment by a king without a trial,
than it is to prevent a subject from imprisoning another till death,
merely for not giving his answer upon oath?
Does it not belong to parliament to secure the people in their estates, liberties,
and properties?
And should it not also belong to parliament to secure
the Quakers from the loss of their whole estates,
simply because they dare not comply to a circumstance of the law,
when (as they understand it) it is against an express command of Christ?
Surely no.
And therefore their relief in parliament is a fitting
case to be there tenderly taken notice of,
and provided for.

__As to the fourth objection, that it will tend to let them into the government:__
In answer to this I say, you may bar this in whatever manner you please;
only do not let this concern,
(from which they may so easily and so willingly be excluded) be a hindrance
to that relief and benefit which the government may so easily grant them.

But while you have opportunity by the station that Providence has placed you in,
pray be of such noble, generous spirits as to relieve them,
though they differ from you in the interpretation of a scripture
text which they esteem plain and positive on their side,
and from which they dare not swerve.
And in this they have the concurrence of many ancient fathers and martyrs,
and more recently of the Mennists, and the late Francis Osbourne, esq.
in his [.book-title]#Political Reflections#, 7th edition, p. 319, who speaking of judicial cases,
calls not swearing,
a "`yielding sincere and faithful obedience to the precept of our Savior,
'`Swear not at all:`' which,`" says he,
"`the corrupt glosses of our expositors labor much, though all in vain, to elude.`"
And William Swinderby, in his appeal to the king,
complaining of the errors of the Papists, says: "`As Christ forbids swearing,
so the Pope justifies swearing, and compels men to swear.`"

Since therefore not only profane swearing,
but also solemn swearing was early complained of by Protestants,
let it not seem strange to any that the Quakers now scruple swearing,
and for ease therein have often sought relief in parliament, which is the proper place,
seeing they believe they have the authority of Christ`'s command,
and the apostle`'s exhortation (James 5:12), and the martyrs`' doctrine on their side.
And though some of you are not so persuaded,
yet let the world behold your justice and willingness, according to your power,
to do good to all the honest and industrious people you both represent and govern,
by enacting that their solemn affirmation shall be accepted in lieu of an oath,
and all that falsify therein, shall be punished equally with perjured persons.

It having been made clear to a committee of this parliament, Dec.
2, 1692, that these people are exposed to great hardships as aforesaid;
and not only themselves, but others also; the said committee was of the opinion,
and did report it to the house,
that the Quakers ought to be relieved according to the request
of their petition then presented to the house.

Therefore as liberty has been given them to declare
their allegiance to the government without swearing,
for which ease they are sincerely thankful; so be pleased to add to that kindness,
their relief in the matter of oaths between them and other subjects,
as well as between the government and them.

[.signed-section-closing]
Signed on behalf of the said people,

[.signed-section-signature]
Theodore Ecclestone

[.signed-section-context-close]
London, Dec. 22, 1694.

--

Though after the delivering of this representation,
the parliament this year did not come to a full resolution for their relief,
yet several members showed themselves more inclined to it,
and in the next year the matter was sincerely considered again.

Toward the conclusion of this year, Mary the 2nd, queen of England, deceased.
She was a princess eminent beyond many, being well-versed in reading,
and of great knowledge, of which I will mention only this instance:
how the ambassador of the king (her father),
having tried by many arguments to bring her over to the popish religion,
said afterwards in the presence of some great men,
that he never before believed that a woman could be found anywhere who
was so well experienced in the doctrine of the Christian religion;
and that he therefore would not advise any to enter
into discourse with her about that matter.

On the 21st of December some symptoms of the small-pox appeared on the queen,
who had been ill a day or two before;
and her distemper suddenly increased to such a degree
that the physicians began to despair of her recovery.
This, however, was so far from frightening her, that she said, "`God be thanked,
I am prepared.`"
And this quietness of mind did not leave her, even when she felt death approaching;
for she was then heard to say, "`I believe now that I shall die shortly; and I thank God,
that from my youth I have learned this true doctrine,
that repentance ought not to be deferred to a dying bed.`"
In such a Christian disposition she continued unto her dying hour,
and so quietly gave up her spirit to her Creator, from whom she had received it,
departing at Kensington not long after midnight, between the 26th and 27th of December,
leaving the king in unspeakable sorrow, who in all the time of her sickness, it is said,
had not departed from her chamber.
Many pens labored to celebrate her praises, and to bewail her death;
and perhaps no queen in many ages has been more beloved than she was.
But I break off;
others have given an account of her excellent qualities and character to the world,
and it may be none better than Gilbert Burnet, bishop of Salisbury,
in a treatise entitled, [.book-title]#An Essay on the Memory of the late Queen#.
