== Chapter XXIII

[.section-date]
1695--1702

Now I return again to the case and affairs of the Quakers.
Since those of Barbados in America were still at
this time much molested for not bearing arms,
they sent over a list in the year 1695,
of what had been taken from them under the government of colonels Searle and Muddiford,
the president Wallum, the lords Francis Willoughby and William Willoughby,
the knights Jonathan Atkins and Richard Dutton,
and the colonels Edwin Stede and James Kendal,
all of which amounted to 1,423,164 pounds of muscovado sugar, and 2,910£ 16s in money.
To this list was joined an account of the disasters
which befell several of the persecutors in Barbados,
in which I find above thirty marshals or deputies named, who,
though they had enriched themselves with the spoil
and havoc of the goods of honest people,
yet they all died poor, and several of them either by an unnatural death,
or with great pains; but I decline mentioning all the particulars.
Among these was one John Thurborn, marshal to colonel Tidcomb,
who used scoffingly to call the Quakers his milk cows,
saying that George Gray (one of these people) was one of his best cows,
and gave a large quantity of milk.
For he and other such birds of prey always took much more than the fine amounted to.
But at length this marshal Thurborn died in poverty,
being afflicted with an abscess in his rectum that admitted of no cure.

It was not only for not bearing arms that the Quakers suffered thus;
but other occasions were frequently sought to trouble them.
For when, in order to bring their negroes to some knowledge of the true God,
they caused them to meet together for an hour or two once
a week to instruct them according to their capacity,
by reading to them some parts of the Holy Scriptures
and speaking something to this purpose;
a law was then made forbidding the Quakers to let their negroes
come into their meetings (though held in their own houses) on pain
of forfeiting every such negro as was found there,
or ten pounds instead there.

By one Thomas Cobham,
a lawsuit was brought against Ralph Fretwell for eighty
of his negroes who had attended a meeting in his own family.
But though the justice, John Merrick, did what he could to asist the said Cobham,
yet after several sessions of the court, judgment was given in favor of the defendant.
And it was remarkable that this T. Cobham, though a robust and handsome young man,
became dejected and generally weak;
and soon after was taken with a fever and an inflammation in his neck and throat,
which so increased, that towards his latter end he cried out, "`Fire, fire;
I am all on fire!`"
And to his mother he said, she needed not provide a coffin for him;
for he would burn up before it was made, crying out, "`This is neither heaven nor hell,
but all fire, fire!`"
To which he added,
"`Now the Quakers will say it is a judgment of God that has fallen on me.`"
After this manner he miserably ended his days.
And justice Merrick`'s exit was also dismal.
For riding to his house after having drank too much, he was thrown from his horse,
whereby his brain was so injured that he lay some days in a violent raving condition,
to the terror of his friends, and so died.
In like manner William Sharp,
a judge of the court who had been a great opposer to the Quakers instructing their negroes,
riding from his house to Bridgetown, fell from his horse, and was so hurt,
that he was not heard to speak anything else afterwards, besides, "`Oh my head!`"
And three or four days after his fall, he died.

Sir Timothy Thornhill, major-general,
had often threatened to take away the Quakers`' lives,
and was such an abominable blasphemer,
that I feel myself seized with horror in reading the most detestable
and dreadful blasphemies which this monstrous wretch belched out.
For being at a feast,
and drinking so excessively that some of the company refused to drink more,
he said he wished he were God Almighty,
that he might condemn the souls of those who were unwilling to drink with him.
At another time,
being in company where a woman spoke of the power and omnipotency of Almighty God,
he returned this accursed language (which is worse than that of the devil himself):
"`God damn you; go to the top of that tree,
and see if God Almighty can save you from breaking your neck before you hit bottom.`"
Other devilish language he spoke which I pass by in silence.
When once a person was brought before him for not bearing arms,
and told him he could not do so for conscience-sake, he returned,
"`God damn your conscience!
If I cannot make your conscience bow,
I will make your stubborn dog`'s back bend;`" and so he tied him neck and heels
with his own hands so violently that he almost deprived the man of life.
He also once, when a declaration of war was published in the island, said,
that the first time any enemy appeared, he would hang up the Quakers,
binding his words with abominable oaths, to which he was so accustomed,
that he seldom spoke without them.
But at length the time came for him to be removed from this to the other world.
Having been sick, and being pretty well recovered,
he boasted among his companions of his conquest over death,
and daringly said that he had taken a new lease of
his life from God Almighty for thirty years longer.
But within a few months after this, the thread of his life was cut,
and his pretended lease was taken from him by the Sovereign of the universe.
Thus he died unlamented by moderate people, and cursed by others,
who lost considerable money by him,
notwithstanding he had been left a great estate by his father.

Much more happy was Thornhill`'s marshal, John Batt,
who also had taken much goods from the Quakers.
But on his dying bed, some years before this (in 1679),
he was so sensibly touched with repentance that he
caused the following paper to be written,
and signed it.

I, John Batt the younger, of the island of Barbados,
was lately by commission from Colonel Thornhill,
a marshal to his regiment of foot soldiers;
and by that power did sieze the estates of several of the people called Quakers,
and took and carried away many parcels of their sugar and other goods,
for their failure to appear in arms in the said regiment,
which they refused out of tenderness of conscience, to which I had no regard.
But now,
the Lord having laid His hand sorely on me by afflicting
me with a hard and grievous sickness,
those things done to the aforesaid people come fresh
in my mind to my very great grief and terror;
and I do declare that all the sins that I have been guilty of besides,
which are very many,
do not trouble or lie so heavy upon my conscience as my evil doings to that people;
and I do believe that no man will ever be blessed or prosper,
that practices such things against that people.
In witness whereof I have hereunto set my hand, this tenth day of May, 1679.

John Batt, Jr. Witness William Howard, Antrobus.

Well had others done, if they had taken example by this;
but it was not in vain that our Savior in the parable of the rich man and Lazarus,
made Abraham say to the rich man, "`If they do not hear Moses and the prophets,
neither will they be persuaded though one rise from the dead.`"
But other persecutors took no warning by this penitent John Batt;
for not long after this some others in Barbados most furiously
showed their malice and rage against the Quakers,
and among these one Alexander Ruddock, a Scotchman,
who was not only a colonel of a regiment of foot soldiers, but also judge of a court,
and one of the council.
He caused one of the society of the Quakers to be fined four hundred
pounds of sugar for payment of the priest`'s wages,
who was his son-in-law; whereas, upon the complaint of the said person, and upon inquiry,
it appeared that the pretended due was only ten pounds of sugar.
And it was well known that this Quaker and his friends
duly paid for maintaining the poor,
and for mending their highways; but all this could not avail him;
for a cow was taken from him worth ten pounds sterling.
And though some of the magistrates, seeing the unreasonableness of these proceedings,
would have had the cow returned to the right owner,
yet such was the power of the said A. Ruddock, that they were not able to withstand it.
And because the aforesaid Quaker complained of the wrong and oppression he suffered,
this so incensed Ruddock, that he caused him to be fined five pounds sterling,
for refusing to take the oath as constable, though he was willing to serve the office.
For this fine Ruddock issued a warrant against him,
for which was taken from him a negro woman, who was sold for twenty-six pounds sterling,
and all was kept for the fine of five pounds.
From this same man was taken the value of above seven thousand
pounds of sugar in one year by the direction of Ruddock;
which the sufferer laying before him (in the presence of his daughter,
the priest`'s wife),
and telling him he had suffered all that for complaining
of the wrong he had done him about his cow,
Ruddock, as though rejoicing at it, said it should be so every year,
so long as he was a magistrate.
But he did not live one year after this.

He was of a fierce temper, and very ready to put negroes to death as an example, saying,
"`What is it for Barbados to put twenty or thirty
negroes to death yearly for the sake of example?`"
And as he troubled the Quakers many ways,
so he showed his grudge also by taking the food they bought and paid for.
Indeed, he was so malicious,
that once meeting a butcher carrying food to the house of a man that bought it,
he commanded him to carry it back, saying "`the Quakers shall not eat fresh meat.`"
But at length the measure of his iniquity was full; for he came one day from the council,
where an order had been issued from the governor to break up the Quakers`' meetings,
and he promised the governor diligently to obey all his commands.
But on his very way home he was taken ill, and having come to his house,
he called for some cream of tartar which he used to take in his broth;
but by his own mistake he took arsenic instead thereof, and so wretchedly ended his days.
And regardless how wicked he was, yet the priest Kennedy, his countryman,
did not hesitate when preaching his funeral sermon,
to take his text from these words of the apostle, "`I have fought a good fight,
I have finished my course, I have kept the faith;
henceforth there is laid up for me a crown of righteousness.`"
And in this sermon it was declared of him,
that he had "`attained to the prudence of a judge, the dignity of a colonel,
and the honor of a counsellor; had served his king and country faithfully,
and died a saint.`"
This last expression seemed to relate to some repentance he had showed;
but whatever it was, we must commit that to God;
and in the meantime not rely too much on such a repentance,
since Judas also repented of his wickedness.
If I did not seek brevity,
I could relate more remarkable cases concerning the persecutors in Barbados;
but now I break off.

Now I return to England, where the parliament sat the latter end of this year,
and effectually took in hand the making of an act to ease
the people called Quakers from that heavy burden of swearing.
This work met with great opposition;
for though many good-natured members were inclined to it in good earnest,
yet their enemies were so active in altering and clipping the bill,
that it looked almost as if the whole project would have come to nothing.
But the king himself forwarded the work, and to his praise be it said,
he was the principal promoter of it.
Thus in the beginning of the year 1696, it was enacted by the king and parliament,
that the solemn affirmation and declaration of the people called
Quakers would be accepted instead of an oath in the usual form,
as appears by the following act:

An Act that the solemn Affirmation and Declaration of the people called Quakers,
shall be accepted instead of an Oath in the usual form.

Whereas various dissenters, commonly called Quakers,
refusing to take an oath in courts of justice and other places,
are frequently imprisoned,
and their estates sequestered by process of contempt issuing out of such courts,
to the ruin of themselves and families; for remedy thereof,
let it be enacted by the king`'s most excellent majesty--by and
with the advice and consent of the spiritual and temporal lords,
and this present parliament assembled,
and by the authority of the same--that from and after the fourth day of May, 1696,
every Quaker within this kingdom of England and the dominion of Wales,
who shall be required upon any lawful occasion to take an
oath in any case where an oath is required by law,
shall, instead of the usual form,
be permitted to make his or her solemn affirmation
or declaration in these following words:

"`I +++_______+++, do declare in the presence of Almighty God,
who is the witness of the truth of what I say, etc.`"

II. This solemn affirmation or declaration shall be adjudged and taken,
and is hereby enacted and declared to be of the same force and effect,
to all intents and purposes, in all courts of justice and other places,
wherever an oath is required by law within this kingdom
of England and the dominion of Wales,
as if such Quaker had taken an oath in the usual form.

III.
And let it be further enacted by the aforesaid authority, that if any Quaker,
making such a solemn affirmation or declaration,
shall be lawfully convicted of having willfully, falsely,
and corruptly affirmed or declared any matter or thing,
which would have amounted to willful perjury if the same had been declared with an oath,
every such Quaker so offending shall incur the same penalties
and forfeitures as by the laws and statutes of this realm
are enacted against persons convicted of willful perjury.

IV. And let it be it enacted, that no Quaker,
or reputed Quaker shall by virtue of this act be qualified
or permitted to give evidence in any criminal causes,
or serve on any juries, or bear any office or place of profit in the government.

V+++.+++ Provided, that this act shall continue in force for the space of seven years,
and from there to the end of the next session of parliament, and no longer.

Thus the Quakers were discharged and freed from that grievous
burden by which they had been oppressed so many years.

Mention has been made already that George Keith obtained
a place in London called Turner`'s-hall to preach in;
and as his auditory consisted chiefly of persons who were envious against the Quakers,
so there were among these also many of the vulgar sort,
who are generally fickle and unsteady, and often inclined to novelties.
And though Keith in some respects still desired to
be looked upon as an adherent of the Quakers,
he had also published some papers wherein he endeavored to make
it appear that they held several heterodox sentiments.

The books which he had published concerning this
matter were so fully answered by the Quakers,
that being at a loss to make a reply to their answers,
pretended that he was not in a financial condition to set the press at work,
and bear the charges of the printing.
But that this was a frivolous evasion was well known.
Yet he, to do something, fell upon another project, and published an advertisement,
that on the 11th of the month called June,
he would defend his charge against the Quakers,
and therefore summoned some of them to appear there at the time to answer for themselves.
Beginning now to comply with the Episcopalians,
he had (as he afterwards said) given notice of his intention to the lord mayor of London,
who not forbidding it, caused him to grow more bold.
But the Quakers did not think it fitting to appear
there to enter into a dispute with him,
in part because the king at that time was beyond sea,
and many of the common persons were idle for lack of work
and trade (occasioned by the scarcity of money,
which then was very great, by reason of the recoining it),
insomuch that it could not be foreseen whether some discontented
persons might gather together and cause a dangerous disturbance.
They therefore declined to appear there, and gave the following reasons of their refusal,
which were read at the appointed meeting, and afterwards published in print:

Whereas George Keith has, after his customary irregular and unruly manner,
has challenged several of us to defend ourselves against such charges
as he desires to exhibit against us at Turner`'s hall;
the following is to certify the reasons why we decline any such meeting,
before all whom it may concern:

First.
Because the said G. Keith has given us such frequent proofs of his very passionate
and abusive behavior at the many private meetings we have had with him,
in all manner of sweetness, long-suffering and patience on our side,
to satisfy and preserve him from these extremes;
so that we cannot assure ourselves now of any better reception,
or that the meeting can have any desirable success.

Secondly.
We decline to meet because it is not a meeting agreed upon by both sides,
which it ought to have been.
And where this is not possible, the press is the next fair way and expedient,
which indeed he has begun, but now seems to decline;
nor has he sent us any copy of his charges or accusations against us,
which he also ought to have done.

Thirdly.
He has two of our books in vindication of us and our doctrines from his accusations,
and which he has not yet answered; so that he is not upon equal terms with us.
We therefore we think his challenge, appointment, and summons to be unfair;
and we believe that all who are not partial will be of the same mind with us.

Fourthly.
Such public and uncontrolled meetings are too often attended with passion, levity,
and confusion, and do not answer the end desired by sober and inquiring men.
Besides this,
it may set up a practice which the authorities may judge to be an abuse to our liberty,
and so make us appear to be no friends to the civil peace.

Fifthly.
We know not what religion or persuasion this wavering man belongs to,
nor what church or people he adheres to,
nor who will receive and acknowledge him with his vain speculations,
or who will be accountable to us for him and his irregularities and abuses.

Sixthly, and lastly.
Let it therefore be known unto all, that for the sake of true religion,
the liberty granted us, and the civil peace, we decline to meet him;
and not from any apprehension we have of his abilities,
or of our own consciousness of error, or any injustice to the said G. Keith;
whose weak and unbridled temper we know is such that,
whatever learning and abilities he has,
have not been able to balance and support him on lesser occasions,
so that we may say they are in poor hands.
And if he proceeds as he has begun,
all his gifts and learning will be employed to a sad end,
which--poor man!--cannot be otherwise, unless he change his course.
This we indeed heartily pray for, that he may find a place of repentance;
and through a true contrition, the remission of his great sin of envy,
and of evilly treating the Lord`'s people, and way, which we profess,
and which he too--the said G. Keith--has long and even recently both professed,
and zealously vindicated as such.

As has been said, these reasons the Quakers published in print,
to show the world that it was not without a weighty
cause that they did not accept G. Keith`'s summons.
Now though George Whitehead and William Penn,
for the above-said reasons did not appear in Turner`'s hall,
yet some of their friends were there as spectators,
to see what would come of the business.
G+++.+++ Keith, seeing himself thus disappointed in his intention,
nevertheless took upon himself to defend his charge in the absence of his adversaries,
which now he could easily do, since none contradicted him;
and he was applauded by the frequent shoutings of
the mob that had assembled in great numbers.
After the reasons for the Quakers`' non-appearance were read,
Keith signified that they were not satisfactory, calling them "`slender, weak,
and frivolous.`"
"`What,`" said he, "`may a criminal make this excuse:
You shall not call me before a justice without my consent?
No. If a man robs me, I may complain of him as a robber,
and without his consent call him to account.`"
This reason he published in print in his narrative of that day`'s work.
But who would formerly ever have thought, that such a little man as he was,
could have been so big in his own eyes;
for it looked as if he thought the Quakers were obliged
to appear as criminals before the pretended judge Keith,
accompanied by his assistants, the mob.
And to keep to G. Keith`'s comparison, though a criminal may not say,
'`you shall not call me before a justice without my consent;`'
yet with some good reason he might say,
'`you shall not make yourself a justice,`' as Keith now did.
It is probable that he was supported by some great churchmen,
otherwise such a bold action might easily have turned to his disadvantage.

My limits do not admit of a circumstantial relation
of what was transacted at that time in Turner`'s-hall;
yet, in order to show briefly how G. Keith handled matters,
I will produce one or two instances, whereby, ut ex ungue leonem,
(i.e. the whole may be judged by the part).
He said he would charge the Quakers with nothing
but what he would prove from their own writings,
and he went on thus:
"`I offer to prove that George Whitehead has denied Christ both to be God and man.`"
This was a strange claim indeed,
since it was very well known that G. Whitehead had
published a book of above twenty sheets in length,
with the title, "`The Divinity of Christ,
and Unity of the Three that bear record in Heaven,
with the blessed end and effect of Christ`'s appearance, coming in the flesh, sufferings,
and sacrifice for sinners, confessed and vindicated by his followers called Quakers.`"
G+++.+++ Keith could not pretend ignorance of this book,
for he picked something out of it in his narrative.
But in order to maintain his charge, he appealed to a book of G. Whitehead`'s, called,
"`The Light and Life of Christ Within.`"
This book G. Whitehead had written in answer to W. Burnet, a Baptist preacher,
who writing of Christ, said, "`As He was God, He was Co-Creator with the Father,
and so was before Abraham, and had Glory with God before the world was,
and in this sense came down from heaven.`"
To this G. Whitehead answered, "`What nonsense and unscripture-like language is this,
to speak of God being Co-Creator with the Father?
Or that God had glory with God?
Does this not imply two gods?
Let the reader judge.`"
Certainly it appears from this plainly,
that G. Whitehead did not intend anything but to
censure the unscriptural expressions of his opponent,
as Co-Creator, implying two gods: for not only the apostle says,
"`God is One,`" but Christ himself says "`I and the Father are One.`"
Yet G. Keith did not hesitate to say, "`G. Whitehead denies the divinity of Christ,
and he deceives the nation and the parliament by telling them that
the Quakers acknowledge Christ to be both God and man,
and believe all that is recorded of Him in the holy Scriptures.`"

Now to prove that G. Whitehead had denied Christ to be man,
Keith cited the following passage from the aforementioned book,
called "`The Divinity of Christ,
etc.;`" "`Where does the Scripture say that His soul was created?
For was He not the brightness of the Father`'s glory,
and the express image of His divine substance?
But supposing the soul of Christ was with the body created in time, etc.`"
Here Keith broke off his citation and omitted the following words: "`I ask,
if from eternity He was a '`person`' distinct from God and His holy Spirit,
without either soul or body?
Where does the Scripture speak of any '`person`' without either soul or body?
Let us have plain Scripture.`"
Now though G. Whitehead had written this to show how we often get ourselves into
inextricable difficulties when we do not stick to the words of the holy Scripture
(which nowhere speak of three separate '`persons`' in the Deity);
yet Keith perverting the passage abusively, said to his auditory,
"`Here you see He will not acknowledge that Christ had a created soul.`"
After this manner Keith reasoned and treated other passages of the said book.
But how fiercely would he have complained to others,
if they had quoted his words in such bits and pieces.

But seeing that he began more and more to declare
himself in favor of the episcopal church;
somebody of that persuasion (who made himself known only by the initial letters,
W+++.+++ C.) made it his business to show the changeableness of Keith`'s opinion
and sentiments from his own writings which he had published in print.
He thereby evidently proved that in every respect Keith had turned an apostate,
though he appeared much offended at the Quakers for having called him so.
"`But,`" said this author, "`if the Presbyterian principles,
of which society Keith once was a member, were better than the Quakers,
then Mr. Keith is an apostate in revolting from and deserting the Presbyterians,
and turning his coat Quaker-fashion.
But if the Quakers were more in the right than the Presbyterians,
then the contrary is true.`"

Now he appeared to fawn on the episcopal clergy,
and esteemed lawful things that he formerly had zealously opposed.
For he was in hopes that by opposing the Quakers
he would be best rewarded among the Episcopalians;
and this was not altogether without reason;
for it being no more in their power to persecute the Quakers in the same manner as formerly,
they made use of other means to render them and their doctrine odious.
For this purpose Keith seemed to them a useful tool;
for he was not only of a witty and impetuous temper, but was also crafty, subtle,
cunning, and violent in his expressions.
And in order to charge the Quakers with unorthodoxy,
he himself launched out into a heterodox sentiment,
insisting that the historical knowledge of Christ`'s sufferings, death, resurrection,
etc. was absolutely necessary for salvation.
Who could have imagined that this same G. Keith would have accused the Quakers
of unorthodoxy in a point of doctrine which he had often so effectually defended;
and among the rest, in a book against one Cotton Mather, wherein,
upon the charge of their being guilty of many heresies and blasphemies,
Keith said after this manner:
"`Our principles do mostly agree with the fundamental
articles of the Christian Protestant faith.
According to my best knowledge of the people called Quakers,
and those acknowledged by them as preachers and publishers of their
belief (those who are of an unquestionable esteem among them,
and worthy of double honor, as there are many such),
I know none of them that are guilty of such heresies
and blasphemies as they are charged with.
And I think I should know, and do know those called Quakers,
having been conversant in public meetings as well as in private
discourses with the most noted and esteemed among them,
for about twenty years past, and that in many places of the world,
both in Europe and America.`"
Who would ever have thought then,
that one who had conversed so many years with the Quakers, preached their doctrine,
and defended it publicly both by writing and by word of mouth,
would afterwards have decried them as deniers of
the most essential points of the Christian faith?
But to what extravagancies temporal gain may transport a man,
let the case of Balaam serve for an evidence.

I have in all this relation of George Keith`'s behavior,
set down nothing but what I believe to be really true.
Nor have I endeavored to aggravate his failures; for I never bore him ill-will,
but rather a good esteem when I believed him to be upright,
because in that time I perceived in him some good abilities.
And I yet wish from my very heart, that it may please God, in his unsearchable mercy,
so to touch his heart before the door of grace be shut,
that seeing the greatness of his transgression, he may by true repentance,
obtain forgiveness from the Lord of his evil;^
footnote:[Editor`'s Note:
George Keith continued to revile and persecute Friends for many years,
the details of which can be found in the journals of John Richardson, Samuel Bownas,
Thomas Wilson, James Dickenson, and others.
Falling more and more into general disrepute,
many of Keith`'s neighbors were accustomed to say they should
be glad if the Quakers would take him back again,
so that they might be rid of so turbulent a spirit.
William Hodgson,
in his "`Select Historical Memoirs of the Religious Society of
Friends,`" relates the following interesting information regarding
his final days:
{footnote-paragraph-split}
"`There is ground to hope,
that near George Keith`'s latter end, he had some hours of serious reflection,
wherein he was sensible of the peaceful state he
had once enjoyed in fellowship with Friends,
and felt remorse for its loss; for, paying a visit to Hurst-pierpoint,
and a conversation arising concerning the Quakers,
he acknowledged before several persons, that since he had left them,
he had lost one qualification that they had amongst them, which was,
that in their religious meetings they could stop all thoughts which hindered their devotions,
which he admitted he had never been able to attain to since.
And near the close of his life, a Friend paid him a visit;
which he appeared to receive kindly,
and amongst other remarks expressed himself to this effect:
'`I wish I had died when I was a Quaker,
for then I am sure it would have been well with my soul.`'`" He died in Sussex, England,
the 27th of March, 1716.]
which I take to be worse,
because by his craftiness he endeavored to set false
colors on things that were really good,
thereby to insinuate himself into favor with the episcopal party.^
footnote:["`This was written some years before I
heard G. Keith was deceased.`"--William Sewel]
For now the old tale that there were Papist emissaries
among the Quakers was revived and divulged anew.
And three episcopal clergymen in Norfolk also drew up a paper to the king and parliament,
intending to blacken the Quakers from their own writings; but George Whitehead,
William Penn, and others, were not slow to show how their words,
or the true meaning thereof, had been perverted.

At this time, the late king James purposed an invasion upon England,
and great preparations for it were made in France.
A plot was also discovered in England against king William,
which gave occasion to the House of Commons to draw up a
kind of declaration to be signed by all their members,
as follows:

Whereas, there has been a horrible and detestable conspiracy,
formed and carried on by Papists and other wicked and traitorous
persons for the assassinating of his majesty`'s royal person,
in order to encourage an invasion from France, to subvert our religion, laws,
and liberties; we whose names are hereunto subscribed, do heartily, sincerely,
and solemnly promise, testify, and declare, that his present majesty, king William,
is the rightful and lawful king of these realms.
And we do mutually promise and engage to stand by and assist each other,
to the utmost of our power,
in the support and defense of his majesty`'s most sacred person and government,
against the late king James, and all his adherents.
And in case his majesty comes to any violent and untimely death--which God forbid--we
do hereby further freely and unanimously oblige ourselves to unite,
associate, and stand by each other,
in revenging the same upon his enemies and their adherents,
and in supporting and defending the succession of the crown,
according to an act made in the first year of the reign of king William and queen Mary,
entitled, "`An Act declaring the Rights and Liberties of the Subjects,
and settling the succession of the Crown.`"

A declaration was also signed by the lords, and both were presented to the king,
and were followed by all the corporations in England.^
footnote:[See The Life of King William, vol.
III.]
The dissenters also presented declarations to the
king that had some resemblance to the others.
But the Quakers, professing non-resistance and an inoffensive behavior,
could in no way enter into such a league.
Nevertheless, to show that they were loyal and faithful to the king,
they drew up the following declaration, and published it in print:

The ancient testimony and principle of the people called Quakers renewed,
with respect to the king and government, and touching the present declaration:

We, the said people, do solemnly and sincerely declare,
that it has been our judgment and principle from the first day we were called to profess
the light of Christ Jesus manifested in our consciences unto this day,
that the setting up and putting down of kings and governments,
is God`'s peculiar prerogative, for causes best known to Himself;
and that it is not our work or business to have any hand or contrivance therein,
nor to be busy-bodies in matters above our station.
Much less is it our place to plot and contrive the ruin or overturn of any of them,
but rather to pray for the king and for the safety of our nation,
and the good of all men,
that we may live a peaceable and quiet life in all godliness and honesty,
under the government which God is pleased to set over us.

And according to this our ancient and innocent principle,
we often have given forth our testimony, and now do, against all plotting, conspiracies,
and contriving insurrections against the king or the government,
and against all treacherous, barbarous, and murderous designs whatsoever,
as works of the devil and darkness.
And we sincerely bless God, and are heartily thankful to the king and government,
for the liberty and privileges we enjoy under them by law;
esteeming it our duty to be true and faithful to them.

And whereas, we are required to sign the said declaration,
we sincerely declare that our refusing so to do is
not out of any disaffection to the king or government,
nor in opposition to his being declared rightful and lawful king of these realms,
but purely because we cannot for conscience-sake, fight, kill, or revenge,
either for ourselves or for any other man.

And we believe that the timely discovery and prevention of the late barbarous
design and mischievous plot against the king and government,
and the sad effects it might have had, is an eminent mercy from Almighty God.
And for this, we, and the whole nation, have great cause to be humbly thankful to Him,
and to pray for the continuance of His mercies to them and to us.

From a meeting of the said people in London, the 23rd of the first month, called March,
1669.

In this year Roger Haddock died of a fever at his house in Penketh, in Lancashire,
about the age of fifty-three years.
He had been in Holland the year before,
in which time I more than once had an opportunity to speak with him privately,
and thereby did discover many Christian qualities in him that were indeed excellent;
therefore the news of his decease did much affect me.
And because his ministry, in which he was eminent,
was more than ordinarily full of valuable matter in his preaching,
his death was much lamented among those churches
in England where he had labored most in the gospel.
His wife Eleanor, in her testimony concerning him, said the following:

My spirit has been,
and is bowed under a deep sense of my great loss
and trial in the removal of my dear husband,
whom it has pleased God in His wisdom to take away from me, who was a comfort to my life,
and a joy to my days in this world,
being given to me by God in great mercy and lovingkindness;
and so he has been enjoyed by me in thankfulness of heart,
to the end of the time God had appointed.
And now he is taken from the world, with all its troubles and exercises,
as also from all his labors and travails,
which were great amongst the churches of Christ,
who with me have no small loss by his removal.
But what shall I say?
Wise and good is the Lord, who does what He will in heaven and in earth,
and amongst His churches and His chosen.
He can break and bind up, wound and heal, kill and make alive again,
that the living may see His wonders, and magnify His power in all, through all,
and over all, who is God eternal, blessed forever.
Amen.

Then in her testimony she gives an account of his life,
and how in her young years he had been to her a faithful instructor in godliness,
and at length became her husband.
After a description of his life, and his many travels in the ministry of the gospel,
to edify and build up the churches, she says also,
that though his love to her was above all visible things,
as the best of enjoyments he had in this world,
yet she was not too dear to him to give up to serve the truth of God.
Thus, she said,

I was made a blessing to him, more comfortable every day than the one before.
He would often express it; and truly he was so to me every day, every way,
and in every respect.
No tongue nor pen can relate the fullness of that
comfort and joy we had in God and one in another.
Yet we find such has been the pleasure of God concerning those He has loved,
to try them in their most near and dear enjoyments,
that it might be manifest how He was loved above all;
that no gifts may be preferred above the Giver, but that He may be all in all, who is,
and is to come, God blessed forever.
And truly we have had great care and watchfulness over one another,
and over our own spirits, to see that our love, though great,
was bounded and kept within its proper compass, the truth being its origin,
its Alpha and Omega.
And although it has been the pleasure of God to try me,
in the removal of so great a blessing from me, sure it is,
that I may be the more inward to Him, and have His love always in my remembrance,
who gives and takes away, and in all things bless His name.
My soul travails that I may always follow His foot-steps of self-denial in all things,
that I may finish my course in this world to the glory of God, as He did,
and have my part in that mansion of glory with Him eternal in the heavens.
And though it may be my lot to stay for a time in this world of troubles,
yet I have hope in immortality and eternal blessedness,
when time in this world shall be no more.

Thus she wrote; but to avoid prolixity, I break off.
She then giving some account of his life and ministry, mentions,
that having been away from home, she was not present at his death;
but that they having taken leave of each other before, had parted in great love,
with mutual breathings to God for one another`'s welfare.
And she concludes with these words: "`Though I saw not his going away,
yet I have seen in what he went,
and that it was full of zeal and fervency in the love of God and the life of righteousness.
So in pure submission to the will of God,
I conclude this short and true relation of my worthy dear husband,
whose name and memory is blessed, and will live,
and be of a sweet savor in the hearts of the righteous through ages.`"
With such a testimony,
Eleanor transmitted the memorial of her beloved partner to posterity.

Meeting in this year with no more remarkable occurrences, I pass over to 1697,
in which year a treaty of peace was concluded between England, France, and Holland.
And though many thought it would be lasting,
yet among the Papist clergy there were those that had another opinion of it;
concerning which this artificial distich^
footnote:[Two verses or poetic lines making a complete sentence; or a couplet.]
was an evidence, which being sent over by a clergyman from Ghent in Flanders to Holland,
fell first into my hands:

Prospicimus modo quod durabunt Fcedera longo

Tempore, nee nobis pax cito diffugiet.

Which may be turned into English thus,
"`We foresee now that the confederacy shall last a long time,
and that peace will not quickly fly away from us.`"
However, if one reads this distich backward, it runs thus:

Diffugiet cito pax nobis, nee tempore longo

Fcedera durabunt, quod modo prospicimus.

And it makes out a quite contrary sense, namely: "`Peace will soon fly from us,
and the covenant shall not last long; which we foresee already.`"

This peace being concluded,
the inhabitants of England vied with one another
to congratulate their king on that account,
who was now acknowledged as king of Great Britain by the French king Lewis XIV.
And since the magistrates of cities, the heads and fellows of the universities,
and people of all societies and persuasions addressed the king,
the Quakers also drew up also an address, which they presented to the king,
and was as follows:

To King William III over England, etc.

The grateful acknowledgment of the people commonly called Quakers, humbly presented:

May it please the King,

Seeing the most high God, who rules in the kingdoms of men,
and appoints over them whomsoever He will, has, by His overruling power and providence,
placed you in dominion and dignity over these realms;
and by His divine favor has signally preserved and
delivered you from many great and eminent dangers,
and graciously turned the calamity of war into the desired mercy of peace;
we heartily wish that we and all others concerned may be truly
sensible and humbly thankful to Almighty God for the same,
that the peace may be a lasting and perpetual blessing.

And now, O king, the God of peace having brought you back in safety,
it is cause of joy to those who fear Him to hear your good and reasonable
resolution effectually to discourage profaneness and immorality,
knowing that righteousness is that which exalts a nation.
And as the king has been tenderly inclined to give ease and liberty of conscience to
his subjects of different persuasions (of whose favors we have largely partaken),
so we esteem it our duty gratefully to commemorate and acknowledge the same;
earnestly beseeching Almighty God to assist the king
to prosecute all his just and good inclinations,
that his days here may be happy and peaceable,
and hereafter he may partake of a lasting crown that will never fade away.

London, the 7th of the 11th Month, called January, 1697.

This address being signed, and presented to the king by George Whitehead, Thomas Lower,
Daniel Quare, John Vaughton, John Edge, and Gilbert Latey,
was favorably received and accepted by that prince;
who gave signal proofs that he bore no ill will to
any for difference of opinion in religion,
if they were honest people; of which this may serve for an evidence,
that both his watchmaker, and the nurse of the young duke of Gloucester,
were of the Quakers`' persuasion.

I think it was about the beginning of the year 1698 that a bill was brought into parliament,
for restraining the liberty of the press.
Those called Quakers, perceiving that this might be pernicious,
drew up the following remarks, which they delivered to the members of parliament:

Some considerations humbly offered by the people called Quakers,
relating to the bill for restraining the liberty of the press.

To prevent the printing and publishing of seditious
or treasonable books against the government,
or scandalous pamphlets tending to vice and immorality,
is the wisdom of all good governments, and must be the desire of all good men.

But to limit religious books to a license, where the tolerated persuasions are many,
we conceive to be altogether unsafe to all persuasions except that of the licenser,^
footnote:[One who grants permission or authorization to others.]
who by this bill has power to allow what he shall judge sound and orthodox,
or reject what he shall construe to be either heretical, seditious, or offensive.

History and experience have taught how the obscure term "`heresy`" has been turned
and stretched against primitive Christian martyrs and famous reformers.
Nor should it be forgotten for what reason the writ De Haeretico Comburendo^
footnote:[De haeretico comburendo (2 Hen.4 c.15) was a law
passed by Parliament under King Henry IV of England in 1401,
punishing heretics with burning at the stake.
This law was one of the strictest religious censorship statutes ever enacted in England.]
was abolished.

Indeed,
it is no strange thing to have learned men of the same church disagree
in their opinions concerning several texts of holy Scripture;
and it is uncertain when these opinions come before the licenser,
whether the world shall receive in print the best opinions or not.

The different apprehensions men have of various parts of Scripture,
gives birth to different persuasions,
who yet all make the Scriptures the proof of their doctrines;
which being tolerated by the kindness of the government,
we conceive that all ought to be left free to defend their doctrines from the misrepresentations,
prejudice, or mistake of others,
without being subjected to the censure of a licenser
who is of a different religious persuasion.

We therefore humbly hope that nothing may be enacted that will lessen the toleration,
which we thankfully enjoy under the favor of this, as well as the former government.

These considerations, with others that were offered,
were of such an effect that the bill was dropped.

About this time the writings of Antoinette Bourignon were not only translated into English,
but also published in print in London.
This displeased many of the clergy, and an author was employed to write against them,
who also wrote largely against the Quakers.
He called his book, The Snake in the Grass; but his own name he concealed;
though it was discovered afterwards that he was a suppressed parson,
who had refused the oath of allegiance to king William.
This man, in order to render the Quakers odious,
had picked up and collected many things from their writings;
but he had so mutilated their expressions by omitting several important words,
and by skipping over parts,
that they gave quite another meaning than the authors had intended.
To this he added relations of several things that happened (as he said) among the Quakers.
Some of these were fictitious, and mere untruths;
but he also raked up things that had never been approved by the Quakers,
like the case of James Nayler (described before in its due place);
notwithstanding the said James Nayler had publicly given eminent tokens of true repentance.

Among the author`'s untruths, was the claim that the Quakers, in their schools,
did not allow the children to read the holy Scriptures.
The falseness of this was made to appear very evidently by a certificate
of the French assistant at one of their schools at Wandsworth,
near London, who himself was no Quaker;
as also by the testimonies of some of the neighbors who were people of note,
and who declared that the Bible was daily read by the students in the said school,
beginning with Genesis, and going on to the end of the Revelations;
and then from Genesis again.
The false quotations of this author were also clearly set forth; showing that,
if any would be so malicious, it might by his method be insinuated from Psalm 14:1^
footnote:["`The fool has said in his heart,`'There is no God.`'`"]
that holy Scriptures declare,
"`There is no God;`" simply because these words are indeed found there.

This poisonous book was answered at length by George Whitehead and Joseph Wyeth;
a work which required more toil and labor than art,
to review all the manifold citations from many authors,
and to show the unfairness and disingenuity of The Snake in the Grass.
Now since many were very ready to believe the falsities in this book,
along with those propagated in the pamphlets of the apostate
Francis Bugg (who had gone over to the church of England),
a book of John Crook (who was still alive,
though above eighty years of age) was republished this year,
which had first been published thirty-five years previous, in the year 1663.
The title of this book was Truth`'s Principles concerning the Man Christ, His Suffering,
Death, Resurrection, Faith in His Blood, the Imputation of His Righteousness, etc.
By this it appeared that the sentiments of the Quakers
concerning these points were not only orthodox now,
but that they had been so from their early days.

Having thus again made mention of John Crook,
of whom I have spoken several times in this history,
I proceed now to mention something concerning his decease,
since he departed this life in the year 1699.
He left behind in writing the following exhortation or advice to his children and grandchildren,
written scarcely two months before his death:

Dear Children,

I must leave you in a wicked age,
but commend you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ; and as you love it,
and mind the teachings of it,
you will find it a counsellor to instruct you in the way everlasting,
and to preserve you out of the ways of the ungodly.

I have seen much in my days,
and have always observed that the fear of the Lord God proved the best portion,
and that those who walked in it were the only happy people,
both in this life (while they continued faithful) and when they come to die,
though they meet with many hardships in their passage.
By experience I can speak it,
that the ways of holiness afford more true comfort and peace to
the upright soul than the greatest pleasures that this world;
the former reach to the heart and soul,
while the delights of this world are but a show and appearance only,
vanishing like a dream; and whoever believes otherwise of them,
will certainly find them to be but lying vanities.
Therefore the apostle, Rom.
6:21, might boldly put the question to the converted Romans,
"`What fruit had you then in those things whereof you are now ashamed?
For the end of those things is death.`"

Therefore, dear children, be in love with holiness; make it your companion,
and those that walk in it.
You may find buddings of it from a holy seed in your hearts;
and as you mind the inner man, the light will manifest its stirrings after God,
which I felt from my tender years,
although I understood it not so plainly till I heard the truth declared.

I advise you to keep a pure conscience, both towards God and man;
for if your conscience is defiled,
hypocrisy and formality will deprive you of all comfortable feeling of God`'s presence;
and then deadness and dryness will be your miserable portion.

Be careful how you spend your precious time,
for an account must be given of every idle word, though but few regard it;
but foolish jesting and vain talking are said to grieve the spirit of God; read Eph.
4:29-30. But improve your time in prayer and religious exercises,
etc. and be diligent in your lawful callings; for,
"`The desire of the slothful man kills him.`"
Prov.
21:25.

Be careful what company you frequent;
for a man is commonly known by the company he keeps,
as much as by any other outward thing.
And watch over your behavior in company;
for I have found that a wise and sober deportment adds much
to a man`'s reputation and credit in the world.

Watch to the light, and its discoveries of good and evil,
that you may not be ignorant of Satan`'s devices;
thus the net will be spread in vain in the sight of the bird,
for watchfulness will make you love a retired estate.
And the more truly and perfectly any man knows and understands himself,
the better discerning he will have of other men; as in the beginning,
when deep silence of all flesh was more in use,
the spirit of discerning was more common and quick, than since it has been neglected.
Therefore be sure you spend some time, at convenient seasons,
in waiting upon God in silence, though it be displeasing to flesh;
for I have had more comfort and confirmation in the truth in my inward retiring in silence,
than from all words I have heard from others,
though I have often been refreshed by these also.

Love the Holy Scriptures, preferring them to all other books whatsoever;
and be careful to read them with a holy awe upon your spirits,
lest your imaginations put constructions upon them to your hurt.
But exercise faith in the promise of Christ, who has said,
"`My Spirit shall take of what is Mine, and show it unto you.`"

Keep faithfully to religious meetings amongst friends; but look to your affections,
that you respect not persons,
but rather the power and life of truth from whomsoever it comes.
And do not mind the tickling of your affections,
but the demonstration of the truth to your understandings and consciences;
for that will abide, when the words have ended,
and all flashes of affections have faded and come to nothing.

Love one another truly, manifesting your love by good counsel,
and being helpful to each other upon all occasions;
being good examples to all you converse with,
especially to your children and those of your own families.
And let pride and vanity not be countenanced by you, but rather reproved;
remembering that while your families are under your government,
you must give an account of the discharge of your duty towards them to God.

Lastly, be always mindful of your latter end, and live as you would die,
not knowing how soon your days may be finished in this world.
And while you do live here, despise not the chastenings of the Lord, whatever they are.
I have been afflicted from my youth up, both inwardly and outwardly,
but the God whom I served provided for me, when all my outward relations forsook me,
none of them giving me any portion with which to begin in this world.
This I speak to let you know, that I shall leave more outwardly,
even to the least of you, than was left to me by all my relations.
I need not mention this sharp affliction in my old age, which is beyond expression,
because, in some measure, you know it; but I could not have gone without it,
as the Lord has shown me, for I have seen His wonders in the deeps.
Therefore I say again, despise not afflictions,
but embrace them as messengers of peace to your souls, though displeasing to the flesh.

These things I commend unto you out of true love to your souls,
knowing how the vain mind of man little regards such advice as this I leave behind me.
But by this advice I show my true love to you all, desiring God`'s blessing upon it;
to whom I commit you all, my dear children, and so end my days.

Your loving father and grandfather,

John Crook

Hertford, the first of the First month, 1699.

The sharp affliction he speaks of in this writing was more than a single illness;
for kidney stones, gout, and colic attacked him sometimes sorely,
and though this had continued a long time, yet he always behaved himself patiently.
His pain, however, was sometimes so violent that he was often heard to say,
that if he did not feel and witness an inward power from the Lord,
he could not subsist under such great pains.
That of the kidney stones was the greatest, which continued with him to his end;
and yet he was never heard to utter any unsavory word, or to cry out impatiently;
but when the extremity of his fits were over, he then expressed his inward joy and peace,
and so praised the Lord.

He had an excellent gift in opening the mysteries of the holy Scriptures,
so that he was like Apollos, of whom we find upon record, that he was "`an eloquent man,
and mighty in the Scriptures.`"
And by his zealous and effectual preaching, when he was in his strength of life,
many were convinced of the truth.
In his latter days,
he sometimes said that the furnace of affliction was of
good use to purge away the dross and earthly part in us.
And under the sorrow and grief he had concerning some of his offspring,
he would sometimes comfort himself with these words of David,
"`Although my house be not so with God, yet he has made with me an everlasting covenant,
ordered in all things, and sure.`"

In his old age he was many times heard to say,
"`Many of the ancients have gone to their long home,
and we too are making haste after them.
They step away before me, and I, who desire to go, cannot.
Well, it will soon be my turn also.`"
He seemed to rejoice in the consideration that the time of his dissolution,
when he would be free from his sore ailments, approached quickly.
Yet in the latter part of his life he often appeared so strong in the spiritual warfare,
that some judged he might have said with Caleb,
"`As yet I am as strong this day as on the day that Moses sent me;
just as my strength was then, so now is my strength for war,
both for going out and for coming in.`"
About three weeks before his death, though he was weak in body, yet he said powerfully,
and in a prophetical manner, "`Truth must prosper, truth shall prosper,
but a trying time must first come,
and afterwards the glory of the Lord shall more and more appear.`"
He continued in a calm and truly Christian frame of mind to the last period of his life,
and departed the 26th of the month called April, in the eighty-second year of his age,
in his house at Hertford, where he had lived many years.
I knew him in England, and he has also been in Holland,
so that I do not speak of one that was unknown to me.

George Keith, by vilifying the doctrine of the Quakers,
was now so much in favor with the episcopal clergy,
that he began to serve them as a vicar;
having been ordained by the bishop of London about the year 1700.
And since this seemed strange and astonishing to many,
somebody (of what religious persuasion I do not know) made a collection
of his critical sentiments concerning the national church and its clergy,
and what account he gave of their rites and ceremonies from
books and papers he had published many years before;
to which the author gave this title,
"`Mr. George Keith`'s Account of the National Church and Clergy,
Humbly Presented to the Bishop of London.`"
To this were added some queries he once wrote concerning
what is called the sacrament of the Lord`'s supper.
This account was now published in print, and presented to the bishop of London,
ending with these words of the apostle, "`If I build again the things which I destroyed,
I make myself a transgressor.`"

In the next year, 1701, the late king James died in France.
I mentioned before how this unhappy prince, after having ascended the throne,
fell suddenly by his hasty conduct and ardent desire to introduce popery in England,
and all his endeavors to regain his lost kingdoms proved ineffectual.
In September, being at mass, he was seized with a sudden attack of illness,
and the sickness increasing, within a day or two he vomited blood,
and all remedies made use of were unprofitable.
If what was written about that time from Paris is true,
he declared that he forgave all men whatever they had done amiss to him,
and on the 16th of the said month he died at St. Germain`'s, in France,
where he kept his court.

About this time, King William returned from Holland,
where he had been because of new troubles drawing on from France.
And since the succession of the crown of England was now settled in the Protestant line,
the king was congratulated on that account with many addresses from his subjects.
And hearing that a horrible plot had been discovered against his life,
those called Quakers also thought it their duty to address him,
with a thankful acknowledgment of his favors.
This they did as follows, in a letter presented to the king in December,
by George Whitehead, William Mead, and Francis Camfield.

To King William III.
over England, etc.

An Address from the people commonly called Quakers humbly presented:

May it please the King,

We, your dutiful subjects, sincerely express our joy for your safe return to your people;
having great cause to love, honor, and pray for you,
as a prince whom we believe God has promoted and established for the good ends of government,
under whose reign we enjoy great mercies and favors;
and particularly that of liberty to tender consciences in religious worship,
as a proper means of uniting your Protestant subjects in interest and affection.

For this great mercy we cannot but be humbly thankful to God;
and renew our grateful acknowledgment to the king,
whom God by his almighty power has eminently preserved, and made exemplary in prudence,
as well as goodness, to other kings and princes,
whereby your memorial will be renowned to posterity.

We are also engaged to bless the Lord that he has manifestly frustrated
the mischievous and treacherous designs of yours and the nation`'s adversaries,
both against the lawful establishment of your throne,
and the true interest of your Protestant subjects.

And we beseech Almighty God to bless the good designs and just undertakings of the king,
and his great council, for the good of his people,
and for obtaining with Europe a firm and lasting peace.
May He continue you, O king, as a blessing to these nations,
establishing your throne in mercy and truth,
giving you a long and prosperous reign over us, and hereafter a glorious immortality.
This is, and shall be, the fervent prayer of us, your true and faithful subjects.

Signed in behalf and by appointment of the aforesaid people, at a meeting in London,
the 8th month, 1701

This address being read to the king, was favorably received,
and he thanked those that presented it, and replied, "`I have protected you,
and shall protect you.`"
Then returning with the address to his chamber,
he read it over again (as was understood afterwards) and spoke in its commendation.
But keeping the paper some days by him,
without giving it to be made public in the Gazette,
some French news-writers in London forged a very ridiculous address in the name of Quakers,
and sent it beyond the sea.
The French Gazetteers in Holland were very ready to print such fictitious nonsense,
though the expressions therein were so exceeding blunt and ill-mannered,
that they could not be spoken to a king except by such who
were impudent enough to publicly make a mockery of the crown,
which the Quakers have never been guilty of.
But after a few days, the king made public the real address,
and then everybody could see how shamefully the French
news-mongers had exposed their malice.

This year having come to an end, that of 1702 followed,
which also brought the end of king William`'s life.

The French king, upon the death of the king of Spain, had not only placed his grandson,
the duke of Anjou, on the throne of that kingdom,
but had also acknowledged the pretended prince of Wales^
footnote:[James Francis Edward Stuart, nicknamed the Old Pretender,
was the Catholic son of King James II.]
as king of England, seeking in this manner, to attain king William`'s crown.
William thereupon took occasion to make alliances
for his security with other princes and potentates.
Of this he gave notice to the parliament that was then sitting,
who promised to assist him to the utmost of their power,
and to maintain the succession of the crown in the Protestant line.
An abjuration was also drawn up,
wherein it was declared that the aforesaid pretended prince,
who now allowed himself to be called James the Third, king of England,
etc. had no right or claim to the crown of that kingdom,
or any dominions appertaining thereto.
Now though all this was intended for maintaining and assisting the rightful king William,
yet he lived not to see the effect of it; for his time had near expired,
and his glass run, as soon appeared.

About the beginning of the month called March, king William went hunting,
and riding a horse he had never ridden before, the horse fell, and the king,
at the same time, broke his collar-bone.
The fracture was soon set, and all seemed likely to do well;
but the king having endured many fatigues and hardships,
had been weak in body for some time before this;
insomuch that this sore fall seemed to occasion a sickness
which soon followed and put an end to his life.
But before his departure, he did yet one more good work for the Quakers.
Knowing that the term of seven years,
which had been granted for their affirmation to be accepted instead of an oath,
was near expiring,
they solicited the king and parliament that this
act might be continued and confirmed by a new one,
which was obtained;
for the king always showed himself willing to favor them as his peaceable subjects;
and many eminent members of parliament were now well-disposed towards them.
Thereupon this renewed act,
containing a prolongation of the said grant for the space of eleven years,
passed at length, after mature consideration,
the king having named several commissioners, who on the third of March,
gave the royal assent to it in the house of Lords, because, by reason of his illness,
William could not appear himself on the throne.

He also sent a message to the parliament,
recommending the uniting of the two kingdoms of England and Scotland into one,
commissioners having already been appointed in Scotland
to meet with the English concerning this affair.
But time showed that he was not to bring this work to an end,
since the accomplishing thereof was reserved for his successor.
And though some hopes appeared for his recovery,
for he had been walking a little in his garden to take the air,
he afterwards sat down and caught cold, which was followed by a fever;
and his sickness so increased, that on the next first-day of the week,
being the eighth of the month called March, he died at Kensington,
to the great grief of all his faithful subjects.
Indeed, such was the sorrow upon the death of that excellent prince,
that the news of it having come to Holland, it caused a general dejection,
and drew tears from many eyes;
for perhaps no king in these late ages has been more beloved than he was.
The day before his demise,
he had given the royal assent to the bill of abjuration of the pretended prince of Wales;
and the following night, feeling death approaching, he sent for the princess Anne,
sister of his deceased consort, queen Mary.
And having kept her sometime with him, after tenderly embracing,
he wished her his last farewell.
He then sent for the archbishop of Canterbury,
and his understanding continuing good to the last, with evident tokens of piety,
and a resignation to the will of his Creator, at about eight o`'clock in the morning,
he gave up his spirit to Him from whom he had received it,
having entered into the fifty-second year of his age,
and reigned as king above thirteen years.

In the afternoon the princess Anne was proclaimed queen of England, Scotland, France,
and Ireland, etc. and the parliament promised to assist her,
in maintaining those alliances that were already made, or should yet be made,
with foreign powers.
This the queen accepted with much satisfaction,
and confirmed the ministers and high officers in their respective stations.
She also wrote to the States-general of the United Netherlands,
that she would keep to the alliances made with the States by the deceased king,
her brother-in-law.

The body of the king, which was lean and much emaciated, was opened after his death,
and many of his inward parts appeared sound, especially the brain; yet in general,
little blood was found in the body; but in the lungs, which adhered much to the pleura,
there was more than in all other parts.
His heart was firm and strong,
but some inflammation on the left side of the lungs was thought
to have been the immediate cause of the king`'s death,
for he had long been asthmatic.

He was of a medium stature; his face lean and oblong; his eyes were exceeding good,
quick, and piercing; his hands very fine and white.
He did not talk much, but was solid in thought; of a strong memory and composed mind,
quick of apprehension, and not given to luxuriance, but grave in his deportment.
He often gave evidence of a devout attention at the hearing of the name of God;
and even in the midst of dangers, put great trust in divine Providence.
Thus he was valiant and undaunted, but without rashness;
for where he judged his presence to be necessary, he proceeded there without fear.
He was a great lover of hunting, that being his most pleasant diversion,
which made him the more fit to endure the fatigues of war.
He was easy of access, and gave a favorable hearing to everybody,
and those that spoke to him he treated discreetly; and such was his devotion,
that he often retired privately when some thought he was about other business.
Many had conceived hopes that this great prince, in that critical juncture,
would have lived yet somewhat longer; but his work was done;
and God has since shown very eminently that He is not limited to any instruments;
and the queen who succeeded on the throne,
afterwards gave signal proofs of it to the world.
His corps was interred the 12th of the month called April, about midnight,
in the chapel of king Henry the VIIth, in Westminster Abbey.

It was by the favor of this king, a Hollander by birth,
that the Quakers (so called) were tolerated as a free people;
so that now they saw fulfilled the truth of what some of
their deceased friends had prophetically foretold,
namely: That it would not be in the power of their enemies to root them out,
but that God, in His own time, would work their deliverance.

Thus we have seen from what weak beginnings this people had their rise,
and how they increased and became a great people against all opposition,
of which at first there seemed little probability,
as may be seen in the beginning of this history.
And looking back a little, the same may also appear by a testimony of George Fox,
published after his death, in the collection of his epistles:

When the Lord first sent me forth in the year 1643, I was sent as an innocent lamb,
and young in years, amongst men in the nature of wolves, dogs, bears, lions, and tigers,
into the world, which the devil had made like a wilderness.
And I was sent to turn people from darkness to the light, which Christ, the second Adam,
did enlighten them with; that so they might see Christ, their way to God,
with the Spirit of God, which He does pour upon all flesh,
and that with it they might have an understanding, to know the things of God,
and to know Him and His Son Jesus Christ, which is eternal life;
and so that they might worship and serve the living God, their Maker and Creator,
who cares for all, and is Lord of all;
and that with the light and Spirit of God they might know the Scriptures,
which were given forth from the Spirit of God in the saints,
and holy men and women of God.

And when many began to be turned to the light, which is the life in Christ;
and when the Spirit of God gave them an understanding to find the path of the just,
the shining light; then did the wolves, dogs, dragons, bears, lions, tigers, wild beasts,
and birds of prey, make a roaring and screeching noise against the lambs, sheep, doves,
and children of Christ, and were ready to devour them and me, and to tear us to pieces.
But the Lord`'s arm and power did preserve me,
though many times I was in danger of my life,
and very often cast into dungeons and prisons, and hauled before magistrates.
But all these things did work together for good.
And the more I was cast into outward prisons,
the more people came out of their spiritual and inward
prisons through the preaching of the gospel.
But the priests and professors were in such a great rage,
and stirred the rude and profane people into such a fury,
that I could hardly walk in the streets, or go in the highways,
without them often times ready to do me mischief.
But Christ, who has all power in heaven and in the earth,
did so restrain and limit them with His power that my life was preserved,
though many times I was nearly killed.

Oh, the burdens and travails that I went under in that day!
Often my life was pressed down under the spirits of professors and teachers without life,
and the profane!
And besides this, the troubles afterwards with backsliders, apostates,
and false brethren, which were like so many Judas`'s betraying the truth,
and God`'s faithful and chosen seed, and causing the way of truth to be evil spoken of!
But the Lord blasted, wasted, and confounded them, so that none did stand long;
for the Lord did either destroy them, or bring them to nothing,
and His truth did flourish, and His people in it, to the praise of God,
who is the avenger of His chosen.

G+++.+++ Fox

G+++.+++ Fox then,
having in England been the first of the Quakers that preached and proclaimed
Christ "`the light which enlightens every man coming into the world,`"
gained many adherents in a short time (as we have seen in this history),
notwithstanding all opposition,
whereby several others also began to preach the same doctrine.
And many of these first preachers were like "`sons of thunder;`" for they
testified of the light of Christ shining in the consciences of men,
and proclaimed that the day of the Lord had dawned and should yet further break forth,
to the destroying of the former buildings of human inventions and institutions;
but to the confirming of what had formerly been felt and enjoyed by the
true operations of the Spirit of God in the hearts of many people.
By their powerful way of preaching repentance,
many were awakened out of a sleep of careless security,
and came to see that their covering was too short,
and that they were not yet covered with the true wedding garment.
And many that had been of a rude life,
came to be so touched to the heart by these zealous preachers,
that crying out "`what shall we do to be saved?`",
they were brought to repentance and conversion; and so from wild and rough,
they came to be calm and sober.
And as in the beginning many of these first preachers did run on like a mighty torrent,
and seemed fit to thresh and grind the mountains and stones, and to hew down tall cedars,
and wash away all opposition; so there were others also who, as sons of consolation,
proclaimed glad tidings to the hungry and thirsty souls, insomuch that some said,
"`Now the everlasting gospel is preached again.`"
And it was indeed remarkable,
that though these promulgators of the doctrine of the inward light
shining in the hearts of men were contemptible and uneducated,
yet many people of note, not only such as were in magistracy,
but also many preachers of several persuasions,
were so touched at the heart by their lively preaching,
that they not only received their doctrine,
but came themselves in the process of time to be zealous publishers thereof,
and thus a great crop was gathered.
Indeed,
sometimes even men of great skill and sharp wit were
deeply struck by plain and homely preaching;
of whom,
Isaac Penington (mentioned more than once in this history) was a signal instance,
as may appear from a relation concerning himself, written with his own hand,
and found among his papers after his death, wherein he speaks as follows:

I have been a man of sorrow and affliction from my childhood,
feeling my lack of the Lord, and mourning after Him; separated by Him from the love,
nature and spirit of this world, and turned in spirit towards Him,
almost ever since I could remember.

In this sense of my low state, I sought after the Lord; I read Scriptures,
I watched over my own heart, I cried unto the Lord for what I felt the lack of,
I blessed His name in what He mercifully did for me, and bestowed on me, etc.
I gave myself, according to my understanding,
to the faithful practice of whatever I read in the Scriptures;
being content to meet with all the reproach, opposition, and several kinds of sufferings,
which it pleased the Lord to measure out to me therein; and I cannot but say,
that the Lord was good unto me, did visit me, did teach me, and help me,
did testify His acceptance of me many times,
to the refreshing and joy of my heart before Him.

But my soul was not satisfied with what I met with, nor indeed could it be,
for there were further quickenings and pressings in my spirit after a more full, certain,
and satisfactory knowledge; even after the sense,
sight and enjoyment of God as was testified in the Scriptures
to have been felt and enjoyed in former times.
For I saw plainly, that there had been a stop of the streams,
and a great falling short of the power, life, and glory, which they partook of.
We did no have the Spirit in the same way, nor were we in the same faith,
nor did we walk and live in God as they did.
They had come to Mount Zion and the heavenly Jerusalem, etc.,
and we had hardly so much as the literal knowledge
or apprehension concerning what these were.
So that I saw the whole course of religion among us, was, for the most part, but a talk,
compared to what they felt, enjoyed, possessed, and lived in.

The sense of this made me sick at heart indeed, and set me upon deep crying to God,
close searching the Scriptures, and waiting on God,
that I might receive the pure sense and understanding of them, from and in the light,
and by the help of his Spirit.
And what the Lord did bestow on me in that state,
with thankfulness I remember before Him at this very day; for He was then my God,
and a pitier and a watcher over me;
though He had not yet been pleased to direct me how
to stay my mind upon Him and abide with Him.
And then I was led, (indeed I was led, I did not run of myself),
into a way of separation from the worship of the world, into a gathered society;
for both the Scriptures and the Spirit of God in me gave testimony unto this.
And what we then met with, and what leadings and help we then felt,
there is a remembrance and testimony in my heart to this day.
But there was something lacking, and we mistook our way;
for whereas we should have pressed forward into the Spirit and power,
we ran too much outward into the letter and form.
And though the Lord in many things helped us, yet in this He was against us,
and brought darkness, confusion, and a scattering upon us.
I was sorely broken and darkened, and in this darkened state,
sometimes lay still for a long season,
secretly mourning and crying out to the Lord night and day.
Sometimes I ran about, hearkening after what might appear or break forth in others,
but I never met with anything to which there was the least answer in my heart,
except in one people who had a touch of truth;
but I never expressed so much to any of them,
nor indeed felt them at all able to reach my condition.

At last, after all my distresses, wanderings, and sore travails,
I met with some writings of this people called Quakers,
which I cast a slight eye upon and disdained, as falling very short of that wisdom,
light, life, and power, which I had been longing for and searching after.
I had likewise, some time after this, an opportunity of meeting with some of them,
and several of them were by the Lord moved (I know it to be so since), to come to me.
As I remember, at the very first they reached to the life of God in me,
which life answered their voice, and caused a great love in me to spring to them.
But still in my reasonings with them, and disputes alone in my mind concerning them,
I was very far off from acknowledging them, as either knowing the Lord,
or appearing in His life and power as my condition needed, and as my soul waited for.
Yes, the more I conversed with them,
the more I seemed in my understanding and reason to get over them,
and to trample them under my feet, as a poor, weak, silly, contemptible generation;
who had some smatterings of truth in them, and some honest desires towards God,
but very far off from the clear and full understanding of His way and will.
And this was the effect of almost every discourse with them: they still reached my heart,
and I felt them in the secret of my soul, which caused the love in me always to continue,
yes sometimes to increase towards them;
but daily my understanding got more and more over them,
and therein I daily more and more despised them.

After a long time I was invited to hear one of them, (as I had often been,
they in tender love pitying me, and feeling my lack of that which they possessed),
and there was an answer in my heart, and I went in fear and trembling,
with desires to the Most High, who was over all, and knew all,
that I might not receive anything for truth which was not of Him,
nor withstand anything which was of Him,
but might bow before the appearance of the Lord my God, and none other.
And indeed, when I came, I felt the presence and power of the most High among them;
and words of truth, from the Spirit of truth, reaching to my heart and conscience,
opening my state as in the presence of the Lord.
Yes, I did not only feel words and demonstrations from without,
but I felt the dead quickened, the seed raised, insomuch that my heart,
in the certainty of light and clearness of true sense, said, "`This is He, this is He,
there is no other; this is He whom I have waited for and sought after from my childhood,
who was always near me, and had often begotten life in my heart,
but I knew Him not distinctly, nor how to receive Him, or dwell with Him.`"
And then in this sense, in the melting and breaking of my spirit,
I was given up to the Lord to become His,
both in waiting for the further revealings of His seed in me,
and to serve Him in the life and power of His seed.

Now what I met with after this, in my travails, in my waitings,
in my spiritual exercises, is not to be uttered; only in general I may say this,
that I met with the very strength of hell.
The cruel oppressor roared upon me, and made me feel the bitterness of his captivity,
while he had any power; yes, the Lord was far from my help,
and from the voice of my roaring.
I also met with deep subtitles and devices to entangle me in that wisdom,
which seems able to make wise in the things of God;
but indeed is foolishness and a snare to the soul, bringing it back into captivity,
where the enemy`'s snares prevail.
And what I met with outwardly from my own dear father, from my kindred, from my servants,
from the people and powers of the world, for no other cause but fearing my God,
worshipping Him as He has required of me, and bowing to His seed,
(which is His Son,) who is to be worshipped by men and angels forevermore,
the Lord my God knows, before whom is my heart and my way,
and who preserved me in love to them in the midst of all I suffered from them,
and does still so preserve me, blessed be His pure and holy name.

But some may desire to know what I have at last met with.
I answer, "`I have met with the seed.`"
Understand that word, and you will be satisfied, and inquire no further.
I have met with my God, I have met with my Savior;
and He has not been present with me without His salvation;
but I have felt the healing drops upon my soul from under His wings.
I have met with the true knowledge, the knowledge of life, the living knowledge,
the knowledge which is life;
and this has had the true virtue in it which my soul has rejoiced in,
in the presence of the Lord.
I have met with the seed`'s Father, and in the seed I have felt Him to be my Father;
there I have read His nature, His love, His compassions, His tenderness,
which have melted, overcome, and changed my heart before Him.
I have met with the seed`'s faith,
which has done and does that which the faith of man can never do.
I have met with the true birth, with the birth which is heir of the kingdom,
and inherits the kingdom.
I have met with the true Spirit of prayer and supplication,
wherein the Lord is prevailed with,
and which draws from Him whatever the condition needs,
the soul always looking up to Him in the will,
and in the time and way which is acceptable with Him.
What shall I say?
I have met with the true peace, the true righteousness, the true holiness,
the true rest of the soul, the everlasting habitation, which the redeemed dwell in.
And I know all these to be true, in Him that is true, and am capable of no doubt,
dispute, or reasoning in my mind about them, as it abides there,
where it has received the full assurance and satisfaction.
And also I know very well and distinctly in spirit, where the doubts and disputes are,
and where the certainty and full assurance is,
and in the tender mercy of the Lord I am preserved out of the one, and in the other.

Now, the Lord knows, these things I do not utter in a boasting way,
but would rather be speaking of my nothingness, my emptiness, my weakness,
my manifold infirmities, which I feel more than ever.
The Lord has broken the man`'s part in me, and I am a worm and no man before Him.
I have no strength to do any good or service for Him; no,
I cannot watch over or preserve myself.
I feel daily that I keep not alive my own soul, but am weaker before men,
yes weaker in my spirit, as in myself, than ever I have been.
But I cannot but utter to the praise of my God, that I feel His arm stretched out for me;
and my weakness, which I feel in myself, is not my loss, but my advantage, before Him.
And these things I write, as having no end at all therein of my own,
but felt it this morning required of me, and so in submission and subjection to my God,
have I given up to do it, leaving the success and service of it with Him.

I+++.+++ Penington.

Aylesbury, 10th of 3rd month, 1667.

From this conclusion, we see the humility of the mind of this friend, who,
when he wrote this, was already much advanced in the way of godliness,
and had lived several years in the communion of those called Quakers.
Now, though it be the duty of every man not to be conceited of himself,
yet it is certain, that men of refined wits, above all others,
have need to continue truly humble, and not to rely thereupon,
since the trusting to acuteness of wit has rather drawn off many from the way of truth,
than led them to it.
Indeed, it has occasioned the fall of some.
But that Isaac Penington endeavored to continue in true humility,
appears plainly from the relation above.
He was a man of a very compassionate temper, and yet valiant in adversities.
He also suffered not a little on the account of religion,
enduring many tedious and long imprisonments; which were the more hard to him because,
being of a weakly constitution, the suffering of cold and hardship did him the more harm.
And yet he never fainted, but continued steadfast to the end of his life,
which was in the latter part of the year 1679,
when he departed in a pious frame of mind.

By the foregoing relation,
it appears evident that I. Penington was very earnestly seeking the true
way to salvation even before he attained to a perfect quietness of mind;
yet at that time, there was no lack of such as could be truly helpful to him,
offering good and wholesome advice; and among these was John Crook,
whose occurrences make up no small part of this history.
And since there is yet extant a letter of John Crook written to Isaac Penington,
wherein he not only speaks very effectually to his inward condition,
but for his instruction and encouragement,
also gives an account of the great difficulties and temptations he himself had met with,
I cannot well omit to insert the same here.
For from the candid and open-hearted letters of familiar friends to one another,
we may generally discover very plainly their inward state,
and also their outward qualities.
This letter was as follows:

Dear Friend,

My dear and tender love salutes you, in that love from which I had my being,
and from which sprang all my Father`'s children, who are born from above,
heirs of an everlasting inheritance.
Oh, how sweet and pleasant are the pastures which my Father causes all His sheep to feed in.
There is a variety of plenty in His pastures, milk for babes,
and strong meat for those of riper age,
and wine to refresh those that are ready to faint; even the wine of the kingdom,
that makes glad the heart when it is ready to faint by reason of infirmities.
Sure I am, that none can be so weary, but He takes care of them;
nor so near fainting but He puts His arm under their heads;
nor can any be so beset with enemies on every side, but He will arise and scatter;
nor so heavy laden, but He takes notice of them and gently leads them,
and will not leave them behind unto the merciless wolf.
For they are His own, and His life is the price of their redemption,
and His blood the price of their ransom; and if they are so young that they cannot go,
He carries them in His arms; and when they can feel nothing stirring after Him,
His heart yearns after them; so tender is this good Shepherd after all His flock.

I can testify, for I was as one that once went astray,
and wandered upon the barren mountains.
And when I had wearied myself with wandering, I went into the wilderness,
and there I was torn as with briers, and pricked as with thorns,
sometimes thinking this was the way, and sometimes concluding that was the way,
and by and by concluding that all were out of the way.
And then bitter mourning came upon me, and weeping for lack of an interpreter;
for when I sought to know what was the matter, and where I was, it was too hard for me.
Then I thought I would venture on some way where I was most likely to find a lost God;
and I would pray with them that prayed, and fast with them that fasted,
and mourn with them that mourned, if by any means I might come to rest,
but still I found it not, until I came to see the candle lit in my own house,
and my heart swept clean from those thoughts and imaginations,
those willings and runnings, and to die unto them all, not heeding,
but rather watching against them, lest I should let my mind go a whoring after them.
And here I dwelt for a time, as in a desolate land uninhabited,
where I sat alone as a sparrow upon the house top,
and was hunted up and down like a partridge upon the mountains.
I could rest nowhere, without some lust or thought following me at my heels,
and disquieting me night and day; until I came to know Him in whom there is rest,
and no occasion of stumbling, in whom the devil has no place.
And He became unto me as a hiding-place from the storms and tempests.
Then my eyes came to see my Savior, and my sorrow began to fly away,
and He became made unto me all in all, my wisdom, my righteousness, my sanctification,
in whom I was and am complete,
to the praise of the riches of His grace and goodness that endures forever.

Therefore be not discouraged, O you who are tossed as with tempests;
nor be dismayed in yourself,
because you sees such mighty hosts of enemies rising up against you,
and besetting you on every side.
For none was ever so beset, and tried, and tempted as the true Seed was,
who was a Man of sorrows, and acquainted with grief.
But be still in your mind, and let the billows pass over, wave upon wave,
and fret not yourself because of them,
neither be cast down as if it should never be otherwise with you.
Sorrow comes at night, but joy comes in the morning,
and the days of your mourning shall be over, and God will cast out the accuser forever.
For this reason I was afflicted and not comforted, and tempted and tried for this end,
that I might know how to speak a word in due season unto
those who are tempted and afflicted as I once was,
as it was said unto me in that day when sorrow lay heavy upon me.
Therefore be not disconsolate,
neither give heed unto the reasonings and disputing of your own heart,
nor the fears that rise therefrom.
But be strong in the faith, believing in the light which lets you see them;
and you will know His grace to be sufficient for you,
and His strength to be made perfect in your weakness.
And so will you rather glory in your infirmities, that His power may rest upon you,
than in your earnest desires to be rid of them.
And by these things you will come to live in the life of God, and find joy in God,
and glory in tribulation, when you have learned in all conditions to be contented;
and through trials and deep exercises is the way to learn this lesson.

These things, in dear love to you, I have written,
being somewhat sensible of your condition, and the many snares you are daily liable to.
Therefore watch, that you fall not into temptation,
and may my God and Father keep you in the arms of eternal love, over all, unto the end,
and unto His praise.
Amen.

John Crook.

This John Crook had been a man of note in the world,
not only because he had been a justice of peace, as has been said in due place,
but also because he was a man of good intellect.
Yet his zeal for what he believed to be truth was such that
he became willing to bear the reproach of the world,
that so he might enjoy peace with God.
And though he was a man of learning,
yet most of the first preachers of the doctrine held forth by those
called Quakers were people of small account in the world;
yet they were so powerful in their preaching,
that many were thereby turned to true godliness.

Some have been reached by the sayings of dying penitents;
for there have been remarkable instances of young people of honest parents who,
having walked in the broad way, very earnestly bewailed their out-goings on a dying bed,
and declared, that if it pleased God to raise them up again,
they would no longer be ashamed of the despised way of the Quakers,
nor fear any mocking or persecution,
but would serve the Lord in uprightness and with all their heart.
These thus repenting with tears for their transgressions,
have experienced after great agonies, that God wills not the death of sinners,
but that they should repent and so live in everlasting happiness.

Of several such like cases, I will only mention one,
that of a young maid in London called Susanna Whitrow,
whose mother was of the society of the Quakers, but not her father.
On her dying bed she complained exceedingly of her rebellion and vain behavior.
"`Ah,`" said she to her mother,
"`how often have you said that the Lord would plead with us; and now the day has come.
Pride and disobedience were my cursed fruits,
which I brought forth when I was a hearer in the public church.
How often have I adorned myself as fine in their fashion as I could;
and yet they despised my dress, and said, '`How tastelessly have you dressed yourself;
you are not at all in fashion.`' Then coming home on the Sabbath-day,
I went immediately up into my chamber, and locking the door, I altered all my laces,
and so went to their worship in the afternoon, dressed in their fashion,
and then I pleased them.`"
At another time she said,
"`O that I might have a little time longer to go into the country,
and walk in the woods to seek the Lord.
O what do fine houses and silk apparel matter?
O remember Him who sat on the ground, and wore a garment without a seam,
our blessed holy Lord, who went up to the mountains to pray,
and withdrew Himself into gardens and desolate places.
I have done nothing for the Lord, but He has done all for me; therefore I desire to live,
that I might live a holy and righteous life, that my citizenship might be in heaven,
though my body be here on earth.
How would I then invite and warn others not to spend
their precious time in adorning themselves like Jezebel,
patching and painting, and curling their hair.
O the Christian life is quite another thing!
We must not give ourselves the liberty to think our own thoughts,
much less to act such abominations.`"

Several days she was in a strong wrestling and conflict of spirit,
and in fervent prayer to God,
so that when somebody was for diverting her attention a little, she refused it saying,
"`I must not permit a thought to wander; for if I move, I shall be drawn off my watch,
and then the tempter will prevail.`"
Continuing in this conflict, she at length conceived some hopes of forgiveness,
and being thus strengthened by mercy, she said to the Lord,
"`O what can my soul say of Your power?
I sought You, but could not find You; I knocked hard, but none did open for me.
For my sins stood like mountains, so that I could not come near You.
I would eagerly have prayed to You, but could not.
Thus I lay several days and nights struggling for life, but could find none,
and so I said, '`There is no mercy for me.`' Then I said, '`I will never leave You;
if I perish, I will perish here.
I will never cease crying unto You.`' And then I heard a voice say,
'`Jacob wrestled all night before he obtained the blessing.`' Oh then your Word, O Lord,
was strong to my soul!
Then my stony heart was broken to pieces,
and the spirit of prayer and supplication was poured upon me.
And now I can sing as David did, of both mercy and judgment.
'`Unto You, O Lord, will I sing, with a rent heart,
and with my mouth in the dust will I sing praises to You,
my blessed Savior.`'`" In this frame she endeavored to continue,
and once she prayed for her father, Robert Whitrow, part of which prayer was as follows:
"`O Lord, remember not his offenses, let me bear them.
Let it be easy to him; make his friends to be enemies to him,
that You may have mercy upon him.
His temptations are great, Lord; carry him through.
O let him not perish with the world, but support him over this world.
Shall a little dirt of this world draw away his mind?
O Lord, let his mind be set on things above; fix his mind upon You.`"
Thus fervently this young maid prayed for her father,
herself now having attained a full assurance of her salvation,
so that she once said to the Lord, "`O You beloved of my soul, what shall I say of You,
for You are too wonderful for me.
O praises be unto you.`"
And afterward perceiving that her end was approaching, she said to her mother,
"`I must lay down this body,
the Lord will not trust me longer in this present wicked world.
Happy I am.
O my Savior, my soul loves You dearly; Your love is better than wine.
My Savior, my holy One, how glorious You are.
I have seen Your glory.
I am overcome with Your sweet countenance.
O how lovely You are!
My heart is ravished with the sweet smiles of Your glorious countenance.
O, come away, come away, why do You stay?
I am ready, I am ready.`"
Then she lay some time very still, and so departed this life without sigh or groan,
which was about the year 1677.

Such dying persons have sometimes been the means to stir up others to true godliness,
whereby they came to join with the people called Quakers;
and though in time this people came to be very numerous,
yet at first there were but few laborers in the ministry of the word.
But these recommending one another to give diligent heed to the Word of God in the heart,
and to mind that as their Teacher, did often meet together and keep assemblies,
sitting down with such a deep retiredness of mind, being turned inward to God,
that tears trickled down their cheeks, to the astonishment of many that looked upon them.
Some, only by beholding this retiredness unto the Lord,
came to be so effectually reached that they also joined with them,
and frequented their meetings.
In the meantime,
many of these became more and more confirmed in their
minds by silently waiting upon the Lord,
and their understandings came to be so opened,
that in process of time they became apt and fit instruments to exhort others to godliness.
And among these several women also found it their duty to preach the gospel.

There have been many who at one time were very averse to the Quakers,
and yet came to join with them in the faith.
Among others, was one Christopher Bacon, in Somersetshire, who, about the year 1656,
came into a meeting, not with an intention to be edified there, but rather to scoff,
and to fetch his wife from there.
However, he was so reached by the lively exhortation he heard,
that he was not only convinced of the truth preached there,
but in time became a zealous preacher himself, and was valiant in sufferings.
Once being taken up at a meeting in Glastonbury, and brought before bishop Mew, at Wells,
who called him a rebel for meeting contrary to the king`'s laws,
Christopher (having formerly been a soldier for the king), said to him,
"`Do you call me rebel?
I would have you to know that I have ventured my life for the king in the field,
when such as you lay behind hedges.`"
By this he stopped the bishop`'s mouth, who did not expect such an answer,
and therefore was willing to be rid of him.

The like instance of an unexpected conversion, was seen also in William Gibson,
whom I knew well, and who at the time of the civil wars, being a soldier at Carlisle,
he and three others having heard that a Quakers`' meeting was appointed in that city,
they agreed to go there and abuse the preacher, whose name was Thomas Holmes;
but Gibson hearing him powerfully declare the truth, was so affected by his testimony,
that he stepped in near him, to defend him, if any should have offered to abuse him:
and he himself afterwards came to be a zealous preacher
of that truth he had been convinced of.

To these instances I may add that of a certain trumpeter,
who coming into a Quakers`' meeting, began in an insolent manner to sound his trumpet,
in order to drown the voice of him that preached.
This however, had a contrary effect, and stirred up the zeal of the preacher even more,
so that he went on as if nothing disturbed him.
The trumpeter at length, to recover his breath, was made to cease blowing;
but being still governed by an evil spirit, after some intermission began to sound again;
but whatever he did, he was not able to divert the preacher from his discourse,
though he hindered the auditory from hearing what was spoken.
Thus he wearied himself so much that he was forced again to rest, whereby,
in spite of his evil will, he came to hear what the preacher spoke,
which was so piercing, that the trumpeter came to be deeply affected with it,
and bursting into tears, confessed his crime, and came to be a true penitent.
A remarkable evidence of the truth of that saying of the apostle, "`So then,
it is not of him that wills, nor of him that runs, but of God that shows mercy.`"

Among those, who,
contrary to their intent entered into communion with the Quakers (so called),
may be reckoned also Anthony Pearson, the justice,
who (as has been mentioned in its place) was so reached by G. Fox at Swarthmore,
that he came to be one of his followers.
This is true,
yet before that time he had already been somewhat convinced by
James Nayler of the doctrine maintained by the people called Quakers.
For when Nayler was called upon an indictment of
blasphemy to appear at the sessions at Appleby,
in the month called January, 1652,
he found the said justice Pearson sitting there on the bench as one of his persecutors.
And Pearson asking him several questions, received such pertinent answers from J. Nayler,
that he was in a great degree convinced of the truth held by Nayler and his friends.

By what has been related here,
it may be seen how unexpectedly some entered into society with the Quakers (so called);
more instances of which might be produced if needful.
For I have known some, who being naturally of a boisterous temper,
yet were so struck with the terror of the Lord,
that they came to be of a quiet spirit and harmless behavior.
And though formerly they would not permit the least provocation,
so now they bore all reviling and mocking with an even and undisturbed mind;
because the fear of God had made such deep impression upon them,
that they were careful lest by an angry or impetuous
deportment they should sin against Him.
And thus continuing to live in fear and reverential awe, they grew in true godliness,
insomuch that they preached by their pious lives as well as others did with words.

After this manner the number of their society increased.
But then, as has been related, grievous sufferings ensued;
for the priests could not endure to see their hearers leave them.
The furious mob was therefore spurred on, and among the magistrates there were many who,
being of a fierce temper,
used all their strength to root out the professors
of the light (as they were called at first),
and to suppress and stifle their doctrine.
But all this proved in vain, as appears abundantly from this history,
though there were hardly any prisons in England where
some of these people were not shut up;
besides the spoiling of goods and cruel whippings, etc. that befell some of them.
Yet all this they bore with a more than ordinary courage, and without making resistance,
notwithstanding many of them had been valiant soldiers who had often slain
their enemies in the field without regarding danger.

In the consideration of this undaunted steadfastness,
it has seemed to me that there have been some among this people,
whose talent was valiantly to endure persecution for a good cause;
and who perhaps in a time of ease would not have been such
good Christians as they proved to be under these sufferings;
resembling the camomile, which, the more it is depressed or rubbed, the belter it grows,
and yields the stronger scent.
For being thus oppressed,
they found themselves under a necessity of continuing vigilant and watchful, and,
according to king Solomon`'s advice, to "`keep their hearts with all diligence.`"
This made them love what they judged to be truth more than their lives,
and caused them to be careful,
lest (like the church of Ephesus) having lost their first love,
their candlestick would be removed out of its place.
Thus their mutual love increased,
and they valued not their own lives when the grieving of
their consciences stood in competition with it.

Having thus passed through many adversities, with an unwearied and lasting patience,
and having become a great people known by the name of Quakers, they were at length,
by the generous clemency of king William III.
and the favor of the Parliament, declared to be a Christian society,
who would henceforth be tolerated in the kingdom as Protestant dissenters,
with liberty to perform their religious worship in public without disturbance.
