== Chapter XXIV

[.section-date]
1702--1717

Queen Anne,^
footnote:[Queen Anne (1665-1714), daughter of James II and younger sister of Queen Mary,
was queen of England, Scotland and Ireland from March 8, 1702 to August 1, 1714.]
having now ascended the throne, and taken in her hand the reins of government,
was congratulated from all quarters;
and the people called Quakers thought themselves no less
obliged than others to condole the king`'s death,
and to testify their affection and fidelity to the Queen.
They therefore drew up an address;
and when some of them (of whom George Whitehead was one)
went to present it on the 11th of the month called April,
they were introduced by the duke of Marlborough and the duke of Ormond.
The address was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To Queen Anne, over England, etc.

[.salutation]
May it please the Queen,

We, your peaceable subjects,
cannot but be sorrowfully affected with a deep sense of the loss
sustained by the death of our late king William the Third,
whom God made the instrument of much good to these nations.
He was a prince who indeed desired to be the common father of his people,
and as such did by his great example, as well as by precept,
endeavor to unite them in interest and affection,
and promoted and confirmed a legal liberty to tender consciences,
by all which his reign was adorned, to the renown of his memory.

And it having pleased the all-wise God, the disposer of kingdoms,
to preserve you to succeed to the government of these nations,
and thereby to maintain and consummate those great works so happily begun,
we humbly beg leave to congratulate your free and peaceable accession to the throne,
from which we observe the queen`'s excellent declaration,
manifesting her care for the good of all her people, and therefore doubt not but we,
her Protestant dissenting subjects, shall partake of her royal favor and protection.

We sincerely declare that, with the assistance of the grace of God, we will always,
according to our Christian duty, demonstrate our good affection, truth,
and fidelity to the queen and her government.
And we heartily pray that His wisdom may direct,
and His blessing be upon the queen and her great council,
to the suppressing of vice and immorality, and the promoting of piety, peace,
and charity, to the glory of God, and the benefit of these nations.

May the King of kings make your reign long and glorious,
in addition to which temporal blessing we shall pray for your eternal happiness.

[.signed-section-context-close]
Signed on behalf and by appointment of the aforesaid people, at a meeting in London,
the 10th of the second month, 1702.

--

This address was very favorably received by the queen, and after it was read to her,
she answered: "`I thank you for your address, and I assure you of my protection.`"

It was scarce a month after this, when war was proclaimed in England against France,
which had also been proclaimed in Holland against that crown some days before.
Not long after this followed the general yearly meeting of those called Quakers,
held at London,
in which it was thought fit to thank the queen for her declaration that
she would maintain the act of toleration in favor of the dissenters.
Therefore an address was drawn up by the said assembly, which was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To Quean Anne, over England, etc.

[.offset]
The humble and thankful acknowledgment of the people commonly called Quakers,
from their yearly meeting in London, the 30th day of the 3rd month, called May, 1702.

[.salutation]
May it please the Queen,

We, your peaceable and dutiful subjects,
having met from most parts of your dominions at our usual
yearly meeting (for the promotion of piety and charity),
and being deeply affected with your free and noble resolution
in your late speech at the prorogation of the parliament,
to preserve and maintain the act of toleration for the ease and quiet of all your people,
could not but in gratitude esteem ourselves engaged both
to thank Almighty God for that favorable influence,
and to renew and render our humble and hearty acknowledgments to the queen for the same,
assuring her, on behalf of all our friends,
of our sincere affection and Christian obedience.

And we beseech God, the fountain of wisdom and goodness,
to direct all your counsels and undertakings, so that righteousness,
which exalts a nation, and mercy and justice, which establish a throne,
may be the character of your reign, and the blessings of these kingdoms under it.

[.signed-section-context-close]
Signed by the appointment and on the behalf of the said meeting.

--

Of those who presented this address, William Penn was the deliverer,
and the queen was pleased to speak to him in a very kind manner,
not only receiving the said address favorably, but after it was read,
giving the following gracious answer: "`Mr. Penn,
I am so well pleased that what I have said is to your satisfaction,
that you and your friends may be assured of my protection.`"^
footnote:[This, from the Record,
appears to be the substance rather than the exact words of the answer.]

This year died Margaret, the widow of G. Fox, at about eighty-seven years of age,
as appears to me from an account of her son-in-law, Dr. Thomas Lower,
in which I find that she was born at Marsh-Grange, in the parish of Dalton,
in Lancashire.
Her father was John Askew, a gentleman of an ancient family, a man of a good estate,
and famous for his piety and charity.
His daughter Margaret was religious even in her young years,
and was married before she attained the age of eighteen to Thomas Fell of Swarthmore;
who being bred a lawyer, became a justice of the peace,
and having afterwards been a member in several parliaments,
was made a vice-chancellor of the county of Lancaster, and in process of time a judge,
being beloved because of his justice, wisdom, moderation, and mercy.

In the year 1652,
George Fox coming the first time to his house when judge Fell was not at home,
did by his exhortations so reach the family,
that a priest with some gentlemen went and told judge Fell
that a great disaster had befallen his wife and family,
they having been seduced and turned Quakers.
This was so odiously represented to him that it troubled him greatly.
But returning home,
and being received very kindly by his wife according to her usual manner,
he soon perceived that the priest intended to make
him believe untruths and possess him with prejudice.
Not long after this, George Fox had an opportunity to speak to him,
which gave him such satisfaction that he acknowledged what was spoken to be the truth;
and his wife ordered a dinner to be made ready for
her friend G. Fox and those that were with him.
And some time after this,
when judge Fell heard that Margaret and her friends
were consulting where to have a meeting,
he told her that they might meet in his hall, which they accordingly did.
And though he himself did not come into the room, yet when a meeting was kept,
he used to sit in a chair so near to it, that though he could not be seen by everybody,
yet he could hear what was preached; which he liked so well,
that after hearing George Fox,
it is not known whether he ever frequented the public church again.
And though he never entered into full society with the Quakers, yet he favored them,
and several times stopped the malice of their persecutors,
when it was in his power to do so.

After he had been married twenty-six years to Margaret, and had nine children by her,
he deceased in the year 1658, leaving behind him one son and seven daughters.

Margaret being thus become a widow, neglected no opportunity to serve her friends.
In the year 1660, when king Charles II. was restored,
scarce two weeks after he had come in,
she went to London and spoke several times with that prince,
desiring that he would cause the sufferings of her friends to cease.
And for this same end, she wrote letters not only to him,
but also to the dukes of York and Gloucester, the queen mother, the princess of Orange,
and the queen of Bohemia.
And after having been about fifteen months in London,
she at length prevailed with the king,
so that her friends who were in prison were released by proclamation.
But persecution beginning again afterwards,
she again went to speak with the king and the duke of York at Hampton Court.
In the year 1664, for refusing to swear,
she was confined in Lancaster Castle and kept for several years;
for because of her great service in the church, she was much envied,
as well as George Fox,
to whom she was married about eleven years after the decease of her first husband,
judge Fell.
But not long after her marriage, she was again imprisoned, and continued a year in jail,
being sickly the greater part of that time;
and afterwards was fined several times for preaching.

In the seventieth year of her age, she spoke again with the king,
which was the last time; but she was not received as favorably as before,
for he seemed to be somewhat angry.
She therefore wrote to him, and stayed at London in hopes of receiving an answer;
but the king was suddenly taken away by death.
After this she spoke with king James, and wrote to him also.
And at length, after a laborious and godly life, she piously departed at a great age,
as has been said already,
having uttered in the time of her sickness many excellent sayings,
by which it appeared that she was prepared for death, and longed to be dissolved.
She had been a zealous preacher, and had also written much.
Among the rest of her publications was a book entitled, [.book-title]#The Call of
the Jews out of Babylon,# which she
dedicated to the famous Manasseh Ben Israel,
and charged him, as he would answer it before God,
to cause it to be read among his brethren.
This book being translated by William Ames into Dutch,
was also printed in that language while her first husband still lived.

The same year that she died, George Keith,
who now preached up and down wherever the bishops thought fit,
went by their order to New England, New York, and Pennsylvania,
for it seems he imagined that in those parts he should
gain many adherents among the Quakers.
But he came very short of his aim; for even in Pennsylvania,
where many of the Baptists formerly sided with him,
he was by them now looked upon with disdain,
and rejected for wearing a clergyman`'s gown;
and appearing to them to be a great apostate,
there was no likelihood for him to get entrance or to be esteemed there.
After some time having returned into England, he got a living in the parish of Edburton,
in Sussex, worth about 120£ a year.
Now though the Episcopalians seemed to be in great expectation
that Keith would suppress the doctrine of the Quakers,
yet all his endeavors proved vain.
For whatever some may think, it is certain, and appears clearly from this history,
that they have become a great people in a very extraordinary manner,
and that all projects and attempts to root them out have been quashed and come to nothing.
And it is from the consideration of this, I believe,
that many of the Quakers (so called) in their preaching
did sound forth these words of Balaam:
"`There is no enchantment against Jacob, nor divination against Israel;`"^
footnote:[Numbers 23:23]
as I myself have often heard.
And at last the strength and power of their violent opposers
was broken by the favor of king William the Third;
and his successor, queen Anne,
has favorably confirmed the liberty of conscience and worship
which was granted by an act of parliament to the Quakers.
So that now we may look upon them as a free people,
and a society tolerated by the supreme authority; and so I might now finish this history,
as to the import of the title.

But before I conclude, I intend to say something concerning their doctrine,
of which mention has often been made in this work, namely: that their chief principle,
in which they differ from the generality of modern Christian societies is,
that every man is enlightened with a measure of Divine light,
according to the evangelist John, who in the first chapter, speaking of Christ,
as He was from eternity with the Father, calls him the Word, and says.
"`That the Word was God, that all things were made by Him, that in Him was life,
and the life was the light of men.`"
The evangelist speaking concerning John the Baptist, who was sent from God, says,
"`He was not that light, but was sent to bear witness of that light.
That was the true light, which enlightens every man that comes into the world.`"
By this it appears that the Quakers have not coined a new phrase,
but only made use of the express words of the holy Scriptures.
I am not unacquainted that, during the great apostasy,
people generally have not clearly understood this; yet this ought not to seem strange,
because the evangelist expressly says, "`The light shines in darkness,
and the darkness comprehended it not.`"
But to elucidate this doctrine a little more, it may serve for information,
that the Quakers believe this light to be the same that
the apostle Paul calls "`The grace of God that brings salvation,
and has appeared to all men;`" and concerning its operation, he says, "`teaching us,
that denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in this present world.`"^
footnote:[Titus 2:11-12]

Thus much briefly concerning the above-mentioned names of this divine light.
And to make it appear more plainly what this phrase means,
"`Take heed to the Light;`" we thereby understand,
that each one should mind the counsel of the light in their souls,
and so learn to fear God, and to hate pride, arrogance, and every evil way;
which will beget in us such a reverential awe towards God,
that we dare do nothing which we certainly know will displease Him.
This indeed is the first step to godliness;
and therefore both David and Solomon have said that "`The
fear of God is the beginning of wisdom;`" that is,
the fear which is due Him, accompanied with circumspection and caution.
And as we persevere in this fear,
we are taught and enabled to serve the Lord with holiness
and righteousness all the days of our life.

But since we can only do this by the grace of God,
it is absolutely necessary that we take heed to it;
and therefore we ought to pray to God continually for His assistance.
But that brings me to another point, about which people generally have strong notions;
for all sorts of Christians agree that we must often pray to God,
but many greatly err in the manner and nature of prayer.
For some think they perform this duty of praying to God when,
in the mornings and evenings, and at others set times of the day,
they repeat or recite some forms of prayer, and do not seem to consider,
that men "`ought always to pray, and not to faint.`"^
footnote:[Luke 18:1]
And the apostle Paul exhorts to "`pray without ceasing.`"^
footnote:[1 Thessalonians 5:17]
And what this means he himself explains in these words,
"`Praying always with all prayer and supplication in the Spirit,`"^
footnote:[Ephesians 6:18]
which plainly shows that this prayer consists not in a continual repetition of words,
but in pious and devout breathings to God, raised in the soul by the Spirit of Christ,
beseeching Him to keep us continually in His fear and counsel,
since we are in need of constant support from Him.
And thus praying in faith, we receive an answer to our breathings in some measure,
though not always as soon as we desire.
But we must not faint;
and our prayer must be from a sincere believing and breathing of the heart;
otherwise we pray amiss, and do not receive,
according to the saying of the apostle James, "`You ask, and receive not,
because you ask amiss.`"^
footnote:[James 4:3]
But oh what devices and wiles have been invented by the enemy of man`'s soul,
to keep him off from this continual state of prayer!--even
though Christ very expressly says,
"`Watch and pray, that you enter not into temptation;`"^
footnote:[Matthew 26:41; Mark 14:38]
and, "`What I say unto you, I say unto all, watch.`"^
footnote:[Mark 13:37]
And with regard to the instruction that we may reap from these words,
He does not imply a continual outward watching without sleeping,
but a vigilance of the mind, which Solomon recommends in these words,
"`Keep your heart with all diligence.`"^
footnote:[Proverbs 4:23]
Now though our constitution does not seem to allow an incessant
continuance in the deepest retiredness of mind;
yet this is certain, that the more fervently we turn our minds to God,
the more we are kept from evil.
And the man who perseveres in this godly exercise,
is less in danger of falling into spiritual pride,
since he finds that his preservation is in true humility,
and in a continual dependance upon God.
And if he ever departs from there, and thinks himself safe enough,
and now needs not to walk circumspectly in fear as he once did,
then he is caught already, and has in some measure gone astray from his spiritual Guide:
that is, he has gone out from that which showed unto him his transgressions,
and troubled him while he was in the evil way.
And this is "`the manifestation of the Spirit,`" which the apostle says,
"`is given to every man to profit withal.`"^
footnote:[1 Corinthians 12:7]

Now to call this gift or principle, which reproves men for evil,
and consequently discovers it, "`Light`" does not carry with it any absurdity,
especially if we consider that this name is often found in sacred writ.
Evil deeds are called by the apostle the "`works of darkness;`" and says he,
"`All things that are reproved, are made manifest by the fight:
for whatsoever does make manifest, is light.`"^
footnote:[Ephesians 5:13]
By which it appears plainly, that the Quakers have not coined a new phrase,
but only followed the scripture language.
And that they are not the only people that have declared of this light,
might be proved from many other authors of good esteem, if necessity required.

As to oaths, they judge the taking of an oath unlawful; and why,
may abundantly be seen in this history from a multitude of instances.

The making of war they also believe to be inconsistent with pure Christianity,
and esteem that Christ`'s followers, being led by His precepts,
"`will come to beat their swords into plowshares, and their spears into pruning-hooks,
and not to learn war any more,`" according to the prediction of the prophet in Isaiah 2:
4+++.+++ Christ, the author of our faith, unto whom we are commanded to look, expressly says,
"`My kingdom is not of this world; if My kingdom were of this world,
then would My servants fight.`"
And the apostle, in James 4, gives us to understand that wars and fighting come of lusts.
And they believe that by receiving the Spirit of Christ in their souls,
and being entirely guided by it, enmity and lusts, the root of wars and fightings,
come to be destroyed, and His love remains,
by which they not only love one another sincerely, but also can love their enemies,
and pray for them, as also for those who hate and persecute them for His name,
not rendering evil for evil, but good for evil.
And this they believe to be that lamb-like spirit which will prevail, and must overcome,
and therefore they judge it not lawful to make war.
And in these sincerely held beliefs,
they believe they may very safely be tolerated by any civil government;
not only because they are willing and ready to pay taxes to Caesar, but also that,
though they cannot fight _for_ the government, neither can they fight _against_ it.

Concerning the sword of magistracy,
they do in no way assert that it is unlawful for Christians to be magistrates;
for saying so would imply the unchristianing of magistrates, whom they truly honor;
knowing magistracy to be the ordinance of God.
But although they believe this office to be consistent with the Christian religion,
yet they generally think it more safe for themselves not to seek it.

Tithes to the priests they do not look upon to be a gospel maintenance,
since our Savior said in express terms to His disciples, "`Freely you have received,
freely give.`"
Yet they do not stretch this so far as to forbid those who have imparted their
spiritual gifts from receiving temporal gifts if they are in need thereof,
provided that such maintenance of a minister of the gospel is free and not forced;
and also that it consists not in a fixed stipend,
which turns the ministry of the gospel into a means of providing a livelihood.
This they look upon to be far beneath the dignity of the ministerial office,
which ought to be performed purely out of love to God and our neighbor,
and not with any regard to secular gain.

The ordinary way of showing respect or honor in common
conduct is also something they scruple;
for to give the same outward sign of respect to men which is given to God, that is,
the uncovering of the head, they think (and not without good reason) to be unfitting.
They likewise esteem the giving of flattering titles of honor,
since Christ so sharply reproved the greetings in the markets,
and being called of men Rabbi, Rabbi, saying,
"`Be not called Rabbi;`" which title of that time may be
compared to the modern titles "`master`" or "`sir.`"
Thus Christ says also, "`How can you believe, who receive honor from one another?`"
Yet they limit this only to common conversation among one`'s equals;
for a servant may call his master by that title,
and subjects may refer to magistrates by the title of their office.
These honorary titles may be spoken according to truth,
whereas the other is nothing but mere flattery,
invented to gratify and cherish men`'s pride.
They therefore also think it inconsistent with the true gravity
of a Christian to call one`'s self "`your humble servant,`" etc.,
to one who has not any real mastership over us;
for they believe we cannot be too cautious in speaking, since our Savior says,
"`That every idle word that men shall speak,
they shall give account thereof in the day of judgment.`"
The common fashion of greetings they also decline,
thinking it more safe not to imitate the ordinary customs therein.
They instead find it more agreeable with Christian
simplicity to greet one another by giving their hand,
or by other innocent and harmless notices in passing by,
which are signs of friendship and respect that may be showed
without giving to man what pertains to God.

As the Quakers testify against the common vain salutations,
so they are likewise against gaming, silly play acting, jesting,
and all sinful and unprofitable recreations, and the drinking of healths,
all of which they believe to be contrary to the exhortation of the apostle,
"`Whether you eat or drink, or whatsoever you do, do all to the glory of God.`"

In their method of marriage, they also depart from the common way;
for in the Old Testament they do not find that the joining
of a couple in marriage was ever the office of a priest;
nor in the gospel was any preacher among Christians appointed thereto.
Therefore it is their custom, that when any intend to enter into marriage,
they first obtaining the consent of parents or guardians,
acquaint the respective men`'s and women`'s meetings of their intention,
and after due inquiry, all things appearing clear,
they in a public meeting solemnly take each other in marriage,
with a promise of love and fidelity,
and not to leave one another before death separates them.
Of this union a certificate is drawn up,
mentioning the names and distinctions of the persons thus joined,
which first being signed by themselves,
is then signed by those who are present as witnesses.

In the burying of their dead they keep decency in mind, and endeavor to avoid all pomp.
The wearing of a particular dress or habit for mourning is not approved among them;
for they think that the mourning which is lawful,
may be showed sufficiently to the world by a modest and grave deportment.

As to water-baptism, and the outward supper, though they do not use the external signs,
witnessing Christ the substance to have come,
yet they are not for judging others who do use them conscientiously and devoutly.
They do not deny that water-baptism was used by some in the primitive church;
but let it be considered unto whom it was administered, that is,
to such that came over either from the Jews or the Gentiles, into the Christian society.
And baptism was as much a Jewish ceremony as circumcision; for,
according to the account of Maimonides,^
footnote:[Moses ben Maimon, commonly known as Maimonides,
was a well known Jewish philosopher of the Middle Ages.
See Vid. John Leusdcn Philog. Hebrseo-mixt, Dissertat. xxi. de Proselyt. Sect. 1. pag. mihi 144.]
a Gentile who desired to be received into the covenant of the Jews,
had to be baptized as well as circumcised, whereby he became a proselyte.
From which it evidently appears that baptism did not replace circumcision,
as it has been often urged to persuade the ignorant.
However, in the time of the apostles,
to make one a true and real member of the church of God,
the baptism of the Spirit was required as the main thing;
which made John the baptist say, "`I indeed baptize you with water unto repentance,
but He who is coming after me shall baptize you with the Holy Spirit and fire.`"^
footnote:[Matthew 3:11]
And the apostle Peter signifies that "`the baptism which now saves us,
is not the putting away of the filth of the flesh,
but the answer of a good conscience towards God.`"^
footnote:[1 Peter 3:21]
This was that baptism of which God, by the prophet Ezekiel, said concerning Israel,
"`I will take you from among the heathen, and gather you out of all countries.
Then will I sprinkle clean water upon you;
and you shall be clean from all your filthiness,`" etc.

It is a common objection that Christ Himself was baptized with water,
and that we are required to follow His footsteps.
But let it be considered that He was circumcised also,
though the one as well as the other was not needed for His own improvement,
but was done for our sake, to show us by the latter that our hearts must be circumcised,
that is, separated from all evil fleshly inclinations and lusts.
And by the baptism which He allowed to be administered to Him,
is signified to us that we must be baptized by His spiritual baptism.
And if it be objected that Christ said to Nicodemus,
"`Except a man be born of water and of the spirit,
he cannot enter into the kingdom of God;`" it may be answered,
that if this is understood of outward water,
the consequence will be that water-baptism is of such an absolute necessity,
that if any be deprived of it, he is to be shut out of heaven; which,
though this is a doctrine believed by Papists, yet I think few Protestants will say so;
neither was John Calvin^
footnote:[Vid. Calvin, Epist. 184. and 229.]
of that opinion.
It is also worth taking notice, that John the Baptist said,
"`That Christ would baptize with fire;`" by which it appears that both water and fire,
in reference to baptism, are metaphorical expressions;
for they both serve for cleansing and purifying, though in a different way.
Now although some did baptize with water, yet it ought to be considered,
that if the command of Christ to His disciples, "`Go and teach all nations,
baptizing them in +++[+++Gr. __into__]
the name of the Father, and of the Son,
and of the Holy Spirit,`" related absolutely to water-baptism,
it would indeed have been very strange that Paul, that eminent apostle of the Gentiles,
did not think himself commissioned for the administration of that baptism.
For though he considered that "`he was not at all inferior to the
most eminent apostles,`" yet he also says in express terms,
"`Christ sent me not to baptize, but to preach the gospel.
And I thank God that I baptized none of you but Crispus and Gaius, etc.`"
And yet he says, "`There is one Lord, one faith,
one baptism,`" which was the baptism of the Spirit.
The same apostle also says, "`As many as have been baptized into Christ,
have put on Christ;`" and this cannot have relation to water-baptism,
because many received an outward baptism who never
put on Christ and became conformable to His image.
To this may be added,
that if the command to baptize in Matthew 28:19 were literally restricted to water-baptism,
then why are our Savior`'s words not equally understood to be literal
where he speaks to Peter about washing the disciple`'s feet,
"`If I do not wash you, you have no part with me;`" and to His disciples,
"`If I then your Lord and Master have washed your feet,
you also ought to wash one another`'s feet.`"
More might be said on this subject;
but since Robert Barclay has treated of this matter at length,
the reader may refer to his [.book-title]#Apology for the true Christian Divinity#.

Concerning the outward supper, it may be truly said,
that it was the Passover that was kept by Christ at the eating of the paschal lamb;
which likewise was a judaical ceremony,
which nearly all Christians now take to be a figure or shadow.
But is not the modern use of the outward supper in remembrance of Christ`'s sufferings,
also a figure, i.e. of His spiritual supper with the soul?
And does it not seem absurd that one figure or shadow
should be the fulfillment of the other?
The passover was not a memorial of another sign that was to follow;
but was a memorial of the slaying of all the first-born in Egypt,
and of the preservation of Israel and their first-born.
Moreover, we find that the apostles, "`Breaking bread from house to house,
did eat their food with gladness and singleness of
heart;`" which implies a usual meal or eating.
And certainly they do well who daily, at their meals, remember Christ and his sufferings;
for the spiritual supper, which is the thing required,
ought to be partaken of by every true Christian; and this cannot be unless,
being attentive, we open the door of our hearts to Christ and let Him come in.
Let it also be considered that the soul lacks daily food as well as the body;
and being destitute of that, it will faint and languish and so become unable to do good;
and therefore our Lord recommended His disciples to pray for daily bread.
Now, that this chiefly had relation to the spiritual manna,
the bread that comes down from heaven, appears from this saying of Christ,
"`Labor not for the food which perishes,
but for that food which endures unto everlasting life.`"
Besides this, the apostle tells us that, "`the kingdom of God is not food and drink,
but righteousness, and peace, and joy in the Holy Spirit.`"
And the author to the Hebrews says,
"`It is a good that the heart be established by grace,
not with foods which have not profited those who have been occupied with them.`"

All this being duly considered by those called Quakers,
has kept them from the use of those ceremonies.
For the man who, through grace, has become truly spiritual,
has no need of ceremonies or outward means to depend upon,
but finds himself excited to rely on the inward divine grace,
and to depend upon God alone, walking continually in reverential watchfulness before Him.
And so, keeping to the immediate teachings of Christ in his heart,
he approaches with boldness to the throne of grace, and with a full assurance of faith,
becomes a partaker of salvation.

But I leave this matter, to say something also concerning the Quakers`' way of worship.
It is usual among them when they meet together in their religious assemblies,
to spend some time in a devout silence and retiredness of mind,
inwardly praying with pure breathings to God,
which they generally call waiting upon the Lord.
And if under this spiritual exercise anyone feels himself stirred
up by God to speak something by way of doctrine or exhortation,
he does so, and sometimes more than one, but always orderly, one after another.
And that this was usual in the primitive apostolical church, appears from what Paul says,
"`If any thing be revealed to another that sits by, let the first hold his peace;
for you may all prophesy one by one.`"^
footnote:[1 Corinthians 14:31]
And what prophesying signifies under the new covenant,
the apostle himself explains with these words, "`He that prophesies,
speaks unto men to edification, and exhortation, and comfort.`"^
footnote:[1 Corinthians 14:3]
Yet let none think this liberty of speaking to be so unlimited,
that everybody who can say something may freely do so in the congregation;
for he that will speak there, must also by all means be of a good, and honest,
and holy life, and sound in doctrine.
And if, in the process of time,
he finds in himself a concern from the Lord to travel in the ministry,
and desires a certificate of his soundness in doctrine and orderly life,
he may acquire it from the congregation where he resides.
And certainly a preacher himself ought to have experience of the work of sanctification,
before he is qualified to instruct others in the way thereto;
for mere brain-knowledge cannot do this effectually.
Sometimes in their meetings there is a public prayer before preaching;
and preaching is often concluded with a prayer.

Now preaching among them is not confined to the male sex only, as it is among others;
for they believe that women whom the Lord has gifted for
gospel-ministry may exercise their gifts among them to edification;
for who will presume to say unto the Lord "`What are you doing?`"^
footnote:[Daniel 4:35], when He, by His apostle, has said, "`Quench not the Spirit.`"^
footnote:[1 Thessalonians 5:19]
They are not ignorant that the same apostle said to the Corinthians,
"`Let your women keep silence in the churches.`"
Now the word "`your`" here, seems to carry an emphasis along with it,
as being chiefly applicable to those Corinthian women; but not insisting upon that,
it nevertheless appears by what follows that this admonition
is spoken with regard to women who are still ignorant,
since it is said, "`If they will learn anything,`" that is,
if they will be further instructed concerning some points of doctrine,
"`Let them ask their husbands at home.`"
Whereby it appears that this saying has relation to such women who,
either from indiscretion or curiosity,
or out of a desire to be looked upon as having something to say,
proposed questions to the whole church,
and thereby caused more confusion than edification; "`For it is indeed a shame for +++[+++such]
women to speak in the church;`" and the apostle`'s precept is,
"`Let all things be done decently and in order.`"
Moreover, it ought to be considered that these words,
"`Let your women keep silence,`" has reference also
to the subjection which women owe to their husbands,
because it is said there also, that women are commanded "`to be under obedience.`"
This the apostle explains further in one of his epistles to Timothy, where he says,
"`Let the women learn in silence with all subjection:
but I permit not a woman to teach nor usurp authority over the man.`"
Now, that the apostle does not absolutely forbid women
speaking to the edification of the church,
appears from his own words, when he says,
"`Every woman that prays or prophesies with her head uncovered, dishonors her head.`"
Here he gives to women a prescript how to behave themselves when they prophesy;
and what he means by prophesying, he himself declares in the same epistle,
as has been mentioned already, where he says,
"`He that prophesies speak unto men to edification, and exhortation,
and comfort;`" and "`he that prophesies edifies the church.`"
For though prophesying under the old covenant often
seems to signify a prediction of what is to come,
yet it is certain that the ancient prophets were also preachers;
and according to the New Testament language,
it is evident that prophesying is chiefly preaching under the influence of the Spirit.
Hence we may easily understand what the four daughters of Philip were, who did prophesy,^
footnote:[Acts 21:9]
and what kind of servant of the church Phoebe^
footnote:[Romans 16:1]
was, and "`Tryphena, and Tryphosa, who labored in the Lord;`" and "`Persis,
who labored much in the Lord.`"^
footnote:[Romans 16:12]
How significantly does the apostle call Priscilla and Aquila his helpers in Christ Jesus.
And what he means by his helpers in that sense,
we may see in Philippians 4:3 where he speaks of
"`women which labored with me in the gospel.`"
All this then being duly considered,
the Quakers (so called) think it unlawful to forbid
such women to preach whom the Lord has gifted,
and who are of a godly life and conduct;
since it appears sufficiently that in the primitive
church they were not debarred from that service.
And as in those days, so in ours, it has evidently appeared,
that some pious women have had a very excellent gift to the edification of the church.
All of which tends to the glory of God, who is no respecter of persons,
and is pleased to make use of weak instruments to show forth his praise.

As to singing the words of David in the Psalms,
since these do not suit the state and condition of mixed assemblies,
they disuse the customary and formal way of singing in the churches,
which has neither precept nor precedent in the New Testament.

Concerning the resurrection, their belief is orthodox,
and agreeable with the testimonies of the holy Scriptures.
But because they judge it to be very improper to say that we shall
rise again with the same identical bodies we now have,
their opposers have falsely accused them of denying the resurrection;
though they fully believe this saying of the apostle,
"`If in this life only we have hope in Christ, we are of all men most miserable.`"^
footnote:[1 Corinthians 15:9]
And as to the qualities of the bodies wherewith we shall arise, Paul says,
"`It is sown a natural body, it is raised a spiritual body.`"^
footnote:[1 Corinthians 15:44]
"`For,`" says the same apostle, "`our citizenship is in heaven,
from which we look for the Savior, the Lord Jesus Christ, who shall change our vile body,
that it may be fashioned like unto His glorious body,
according to the working whereby He is able to subdue all things unto Himself.`"^
footnote:[Philippians 3:21]
And therefore they have counted it more safe,
not to try to determine with what kind of bodies we shall be raised,
provided we have a firm belief that there is to be a resurrection of the dead.
For from such a determination many difficulties may arise, which otherwise are avoided;
and therefore they have also said to their antagonists,
"`Christ`'s resurrection is indeed an argument for our resurrection,
but would it be valid from there thus to argue: that because Christ`'s body,
which was without sin, and was not corrupted in the grave,
was raised the same as it was buried; therefore our bodies, which do admit of corruption,
must also be raised the same as they are buried?`"
No, by insisting stiffly on this point, we fall into many difficulties.
Who will venture to say that,
when people die and are buried about the age of ninety years,
their bodies in the resurrection shall be the same decrepit bodies that were when buried?
Or that unborn children dying, shall be raised with such small bodies as they had then?
To shun therefore such absurdities,
they think it better not to allow human wit to extend itself too far,
more especially since the apostle says, "`Mind not high things;`" and advises every man,
"`not to think of himself more highly than he ought to think.`"

Now as to church government, both for looking after the orderly conduct of the members,
and for taking care of the poor, indigent widows and orphans,
and also for making inquiry into marriages solemnized among them,
they have particular meetings, either weekly, or every two weeks, or monthly,
according to the size of the churches.
They have also quarterly meetings in every county,
where matters are brought that cannot well be settled in the particular meetings.
To these meetings come not only the ministers and elders,
but also other members that are known to be of sober conduct;
and what is agreed upon there, is entered into a book belonging to the meeting.
Besides these meetings a general annual assembly is kept at London in the Whitsun week^
footnote:[Also called Pentecost week, beginning the seventh Sunday after Easter.]
(so called);
not for any superstitious observation that the Quakers
have for that more than at any other time,
but because that season of year best suits the general accommodation.

To this yearly meeting, which sometimes lasts four, or five, or more days,
come such as are sent from all churches of this society in the world,
to give an account of the state of the particular churches;
which from some places is done only by writing.
And from this annual meeting is sent a general epistle to all the churches,
which commonly is printed;
and sometimes particular epistles are sent also to the respective churches.
In this way it may be known every year, in what condition the churches are;
and in the said epistle, a godly life and conduct are generally recommended,
along with due care for the education of children.
If it happens that the poor are in need in any place,
then their needs are supplied by others who have an abundance,
or sometimes by an extraordinary collection.

As to the name by which they are distinguished from other religious societies, it is,
as is well known,
"`Quakers;`" but since this name was given to them
in scorn (as has been said in due place),
they do not assume it any further than for distinction-sake from others;
and the name whereby they call one another is that of Friends.
And herein they have the example of primitive Christians,
as may be seen Acts 24:3 where it is said,
that "`Julius the centurion treated Paul kindly,
and gave him liberty to go unto the friends^
footnote:[KJV says "`his friends`" but the Greek reads only "`friends`" or "`the friends.`"]
to refresh himself.`"
And in 3 John 14 we read, "`The friends salute you.
Greet the friends by name.`"
Now this name of Friends is so common among the Quakers in England,
that others societies also know them and sometimes call them by that name.

It was, as I find, in the year 1705, that Anne, the late wife of Thomas Camm,
deceased at a great age;
and having already made mention of her by the name of Anne Audland,
I will say something more of her before I describe her exit.
She was the daughter of Richard Newby, in the parish of Kendal in Westmoreland,
being born in the year 1627.
Having been well educated and come to maturity,
she conversed much with the most religious people of that time.
About the year 1650, she was married to John Audland, and in the beginning of 1652,
they were both, by the ministry of G. Fox, convinced of the truth he preached;
and in the next year they began to preach the same doctrine to others.
For this, in the following year,
Anne was committed to prison in the town of Aukland in the county of Durham,
where she had opportunity to speak to the people through the window,
which she did so movingly, that several were affected with her testimony.
After being released, she travelled up and down the country and had good service;
but not long after,
she was again committed to prison upon the accusation of having spoken blasphemy.
For this she was tried at Banbury in Oxfordshire,
the indictment drawn up against her containing the charge that she had said,
"`God did not live;`" whereas she had only said that true
words might be a lie in the mouth of some that spoke them,
alleging the saying of the prophet Jeremiah 5:2. "`Though they say the Lord lives,
surely they swear falsely.`"
The judge before whom she appeared behaved himself moderately,
observing how wisely she answered his questions with a modest boldness.
Some of the justices upon the bench who sought her destruction,
perceiving they should not obtain their end (for
it had been spread abroad that she would be burned),
went off to influence the jury and bias them.
This had the effect that they brought her in guilty of misdemeanor;
which made one present say, "`It is illegal to indict her for one thing,
and to bring her in guilty of another;`" since they ought to have found her either
guilty or not guilty upon the matter of fact charged in the indictment.
The judge, though he had carried himself discreetly,
nevertheless had some desire to please the justices that were her enemies;
and therefore at her refusal to give bond for her good behavior,
she was sent to prison again;
though the judge was heard to say that she ought to have been discharged.
The prison where she was sent was a nasty place, several steps under ground;
on the side of which was a common sewer, which sometimes stunk very much,
and frogs and toads crawled in her room.
Here she was kept about eight months, but she showed herself content,
being persuaded that it was for the Lord`'s sake she thus suffered.

Her husband, John Audland, died, as has been said before,
about the beginning of the year 1664,
and two years after this she was married to Thomas Camm, also a minister of the gospel.
She lived very retiredly, spending much of her time in solitude,
and was almost daily exercised in reading the holy Scriptures and other edifying books.
Her husband suffered imprisonment for three years at Kendal,
and about six years at Appleby.
Thus she came to be well-acquainted with adversities;
but by all these she was the more spurred on to advance in true piety,
and became a very remarkable teacher in the church,
having an extraordinary gift to declare the truth.
And yet she was very modest and humble,
insomuch that no matter how much she had to declare,
she rarely appeared to preach in large meetings where
she knew there were men qualified for that service;
and she was grieved when she perceived any of her sex being forward on such occasions.
She therefore advised them to be cautious,
though she did not fail to encourage the good in all,
and endeavored not to quench the Spirit in any.
Thus she continued in a virtuous life to the end of her days.
She once fell so sick at Bristol, that it was thought she was near death.
She then exhorted those who stood by her to prize their time,
and to prepare for their latter end, "`as God`" she said, "`has inclined me to do,
so that I enjoy unspeakable peace here,
with full assurance of eternal rest and felicity in the world to come.`"

She nevertheless recovered from this sickness; and when her dying hour finally came,
which was in her dwelling place near Kendal, she was not less prepared, but said,
"`I bless the Lord I am prepared for my change.
I am full of assurance of eternal salvation, and a crown of glory,
through my dear Lord and Savior Jesus Christ.`"
Many other excellent sayings she uttered during the time of her sickness;
and when she drew near her end, some of her friends asking her whether she knew them,
she said, "`Yes, I know every one of you.
I have my understanding as clear as ever; and how should it be otherwise,
since my peace is made with God through the Lord Jesus Christ.
I have no disturbance in mind, therefore my understanding and judgment is good and clear;
but to lie under affliction of body and mind,
to feel pinching pangs of body even unto death,
and to lack peace with God--oh that would be intolerable to bear!`"
She advised her husband to free himself from the
cumber of the things of this world after her death,
that he might attend the ministry of the gospel with more freedom, and said, "`Warn all,
but especially the rich, to keep low, and not to be high-minded;
for humility and holiness are the badge of our profession.`"
A little before her departure, some fainting fits overcame her,
but reviving again she said, "`I was glad, thinking I was going to my eternal rest,
without disturbance.
I have both a sight and an earnest of eternal rest with God in the world to come.`"
A little after she said, "`I think I grow weak and cold.
My hands and feet have grown very cold, yet my heart is very strong.
I must meet with sharper pangs than I have yet felt.
This pain is hard to flesh and blood, but it must be endured a little time;
ease and eternal rest is at hand.
I am glad I see death so near me.`"
A little after this, seeing some of her friends weep, she said, "`Be not concerned,
for all is well.
I have only death to encounter, and the sting of it is wholly taken away.
The grave has no victory, and my soul is ascending above all sorrow and pain.
So let me go freely to my heavenly mansion; disturb me not in my passage.
My friends, go on to the meeting; let me not hinder the Lord`'s business,
but let it be the chief thing, done faithfully by you all,
so that in the end you may receive your reward; for mine is sure.
I have not been negligent; my day`'s work is done.`"
Feeling afterwards her pains increasing,
she prayed the Lord to help her through the agony of death; and a little after she said,
"`O my God, O my God, You have not forsaken me, blessed be Your name forever.
O my blessed Savior, who suffered for me and all mankind,
great pains in your holy body upon the cross,
remember me your poor handmaid in this my great bodily affliction.
My trust is in You, my hope is only in You, my dear Lord.
O come, come dear Lord Jesus, come quickly, receive my soul, to You I yield it up,
help me now in my bitter pangs.`"
Then her husband prayed to God that He would be pleased to make her passage easy.
And she had no more such pangs,
but drew her breath shorter by degrees and said little more,
except that "`it was good to leave all to the Lord.`"
And so she slept in the Lord the 30th of November, 1705, in the 79th year of her age.
Thus Anne Camm departed this life,
and her husband said afterwards that he counted it
a great blessing to have had her for his wife;
for she was indeed a very excellent woman,
and for the same reason I have described her latter end the more circumstantially.

Having now related what I thought to be remarkable and of importance
with respect to the rise and progress of the people called Quakers,
I think what I have written may suffice to answer
the contents of the title of this history.
I will therefore only add only a few occurrences, and then come to a conclusion.

Many years previous, in the time of King James I.,
endeavors were used to unite England and Scotland into one kingdom, but all was in vain.
King William III.
also tried what could be done to this purpose,
but his life did not permit him to bring the work to perfection.
Yet at length the matter was agreed upon and settled
about the beginning of the year 1707,
in the reign of Queen Anne,
it being concluded that these two kingdoms should henceforth be united into one,
and called Great Britain.
In the forepart of the year 1708,
Scotland was threatened with an invasion by the pretended prince of Wales;
but he failed in the attempt, and his design came to nothing.
Now since the union of Scotland with England was at last accomplished,
and the succession of the crown in the Protestant line was established by law,
the queen was congratulated on that account by a multitude of addresses; and the Quakers,
so called, judged themselves obliged also to testify their affection to the princess,
as they did by the following address:

[.embedded-content-document.address]
--

[.letter-heading]
To Anne, Queen of Great Britain, etc.

[.offset]
The grateful and humble Address of the People commonly called Quakers,
from their Yearly Meeting in London, this 28th day of the third month, called May, 1708.

We, having good cause to commemorate the manifold mercies of
God vouchsafed to this united kingdom of Great Britain,
believe it our duty to make our humble acknowledgments, first to the Divine Majesty,
and next to the queen, for the liberty we enjoy under her kind and favorable government.
Our hearty desires and prayers are to Almighty God,
(who has hitherto disappointed the mischievous and wicked designs of her enemies,
both foreign and domestic,) that He will so effectually replenish the queen`'s heart,
together with those of her great council, with His divine wisdom, that righteousness,
justice and moderation--which are the ornaments of the queen`'s reign,
and which exalt a nation--may increase and be promoted.

And we take this opportunity to give the queen the renewed assurance
of our hearty affection toward the present established government,
and that we will as a people in our respective stations,
according to our peaceable principles, by the grace of God,
prove ourselves in all fidelity the queen`'s faithful and obedient subjects.
As such, we conclude with fervent prayers to the Lord of Hosts, that after a prosperous,
safe and long reign in this life, you, O queen,
may be blessed with an eternal crown of glory.

--

This address was signed in the name of the meeting by fourteen members thereof,
who were also ordered to present it.
But it being understood that the queen preferred to be presented with it in private,
only seven, among whom were George Whitehead and Thomas Lower, went in with it,
and were introduced by the principal secretary of state Boyle.
G+++.+++ Whitehead presenting it said, "`We heartily wish the queen health and happiness.
We have come to present an address from our yearly meeting,
which we could have desired might have been more early and seasonably timed,
but could not, because our said meeting was not held until last week;
and therefore we now hope the queen will favorably accept our address.`"
Then, as G. Whitehead delivered the address, the queen said,
"`Please read it;`" whereupon he took and read it, and the queen answered,
"`I thank you very kindly for your address, and I assure you of my protection.
You may depend upon it.`"

To which G. Whitehead replied, "`We thankfully acknowledge that God,
by His power and special providence,
has preserved and defended the queen against the evil designs of her enemies,
having made the queen an eminent instrument for the
good of this nation and realm of Great Britain,
in maintaining the toleration and the liberty we
enjoy in respect to our consciences against persecution.
This liberty,
being grounded upon the late king`'s desire to unite
the Protestant subjects in interest and affection,
is now further settled and strengthened by the union of Great Britain;
for in union is the strength and stability of a kingdom; and without union,
no kingdom or people can be safe, but remain weak and unstable.
The succession of the crown being settled and established in the Protestant line,
must necessarily be very acceptable to all true Protestant subjects.
And now, O queen,
our sincere desire is that the Lord may preserve and defend you for the future,
the remainder of your days,
and support you under all your great cares and concerns for the
safety and good of this nation and kingdom of Great Britain,
and that the Lord may bless and preserve you to the end.`"

To this the queen replied, "`I thank you for your speech, and for your address;
and you may be assured I will take care to protect you.`"

G+++.+++ Whitehead then replied,
"`The Lord bless and prosper the queen and all her good intentions.`"
And thereupon he and his friends withdrew.

Enjoying at last the liberty to perform their religious
worship publicly and without disturbance,
the most remarkable occurrences that the Quakers in England
now met with were the publications of their enemies who,
from ignorance or envy,
continued to represent them as maintainers of heterodox sentiments.
But as they never failed to answer their accusers in print, the eyes of many were opened,
and some came over to them.
And though it sometimes happened that those of the national church succeeded
in drawing over one who was born and educated among the Quakers,
but who inclined to more liberty and to be esteemed by the world,
yet there have been others of the episcopal church who,
not from any earthly consideration, but merely by a convincement of their mind,
have entered into society with the Quakers,
not fearing to make public profession of their religion.
This may appear by two letters which I will insert here; the one of Samuel Crisp,
a clergyman of the episcopal church,
who gave the following account of his change to one of his near relations.

[.embedded-content-document.letter]
--

[.salutation]
My dear Friend,

I received a letter from you, the week before last, which was sent by your uncle Bolton:
there were a great many kind expressions in it, and in your sister Clopton`'s likewise:
I acknowledge myself much obliged to you both, and to the whole family,
for many repeated kindnesses, and if my school had not engrossed so much of my time,
I would have taken opportunity to answer my dear friend`'s letter now,
and upon that account my delay will be more excusable.

The news you have heard of my late change is really true--I cannot conceal it,
for it is what I glory in--nor was it any prospect
of temporal advantage that induced me to it,
but a sincere love to the truth, and a pure regard to my own soul.
Neither can I be sufficiently thankful to God that
He has let me live to this glorious day,
and not cut me off in the midst of my sins and provocations against Him.
He is long-suffering to us, not willing that any should perish,
but that all should come to repentance.
He has brought me off from the forms and shadows of religion, and let me see,
in a more illustrious manner, what is the _life_ and _substance_ of it,
as He found me in some degree faithful to that measure of light and knowledge
He had bestowed on me while I was in the communion of the Church of England.
Therefore He was pleased of late, as I humbly waited upon Him,
to make known to me greater and deeper mysteries of His kingdom.
And I can truly say,
that I find by daily experience (as I keep low and retired
unto that pure gift which He has planted within me),
things are more and more cleared up to me,
and the truth shines and prevails greatly over the kingdom of darkness;
and if I should now turn my back upon such manifestations as these,
and entangle myself again with the yoke of bondage,
surely I should grieve the Holy Spirit,
so that He might justly withdraw His kind operations,
and never more return to assist and comfort me.
For God is not mocked; religion is a very serious and weighty thing.
Repentance and salvation are not to be trifled with;
nor is turning to God to be put off till our own time, leisure, or convenience.
But we must love and cherish the least appearance of Christ,
not slighting or despising the day of small things,
but embracing the first opportunity of following Christ in any of His commands.
When He speaks, it is with such force and authority that we cannot stand to cavil,
dispute, or ask questions;
for unless we will be so obstinate as to shut our eyes against the sun,
we must necessarily confess to the truth of His doctrine, and presently fall in with it.

Therefore,
when for several weeks I had lived more privately and retiredly in London than was usual,
fasting twice or three times in a week, and sometimes more,
spending my time in reading the Scriptures and in prayer to God,
this was a good preparation for my mind to receive the truth
which He was then about to make known to me.
I lamented the errors of my past life,
and was desirous to attain a more excellent degree
of holiness than I had found in the Church of England.
In this religious retirement, God knew the breathings of my soul,
and how sincere I was and resigned to Him when alone.
I needed Him to set me free, and to speak peace and comfort to my soul,
which was grieved and wearied with the burden of my sin.
For though I had strictly conformed myself to the
orders and ceremonies of the Church of England,
and had kept myself from running into any great or scandalous
sins (the fear of the Almighty preserving me),
yet still I had not that rest and satisfaction in
myself which I desired and greatly longed for.
I found when I had examined my state and condition towards God,
that things were not right with me.

As for having a sober and convincing conduct in the eyes of the world,
I knew that was a very easy attainment.
A good natural temper, with the advantage of a liberal education,
will quickly furnish a man with abilities for that,
so that he may be looked upon as a saint, and very spiritual,
when he is perhaps still in chains of darkness, in the gall of bitterness,
and in the very bond of iniquity.
If this sort of righteousness would have done,
perhaps I might have made as fair pretensions in that way as some others; but alas,
I quickly saw the emptiness and unsatisfactoriness of such things.
Truly,
this is a covering that will not protect or hide us from
the wrath of the Almighty when He comes to judgment.
It is not a man`'s natural temper, nor his education, that makes him a good Christian;
this is not the righteousness that the gospel calls for,
nor is it the "`truth in the inward parts,`" which God requires.
The heart and affections must be cleansed and purified
before we can be acceptable to God;
it was therefore death to me to think of taking up my rest in a formal pretense of holiness,
in which covering I saw (to my grief) an abundance of people had wrapped themselves,
and were sleeping securely and quietly, dreaming of the felicity of paradise,
as if heaven were now their own and they needed not
trouble themselves any more about religion.
I could not entertain so dangerous an opinion as this;
for then I would be tempted to take up my rest along the way,
while still traveling towards the Promised Land.

While I lived in the communion of the national church,
I think I made a little progress in a holy life,
and through God`'s assistance I weakened some of my spiritual enemies.
I thank my God I can truly say, that while I used their prayers,
I did it with zeal and sincerity, in His fear and dread;
but still I ceased not my earnest supplication to Him in
private that He would show me something mere excellent;
that I might get a complete victory over all my lusts and passions,
and might perfect righteousness before Him.
For I found a great many sins and weaknesses daily attending me,
and though I made frequent resolutions to forsake those sins,
yet still the temptations were too strong for me;
so that I had often cause to complain with the apostle in the bitterness of my soul,
"`O wretched man that I am!
Who shall deliver me from the body of this death?`"
Who shall set me free and give me strength to triumph over sin, the world,
and the devil?--that in everything I may please my God,
and that there may not be the least thought, word or motion, gesture or action,
but what is exactly agreeable to His most holy will, as if I saw Him standing before me,
and as if I were to be judged by Him for the thought of my heart the next moment!
Oh divine life!
Oh seraphic soul!
Oh that I could always stand here!
For here is no reproach, no sorrow, no repentance;
but at God`'s right hand there is perfect peace and a river of unspeakable joy.
Oh that we might imitate the life of Jesus,
and be thoroughly furnished unto every good word and work!
This was the frequent breathing of my soul to God when I was in the country,
but more especially after I had left my new office as a chaplain,
and took private lodgings in London.
In this retirement (I hope I may say without boasting), I was very devout and religious,
and found great comfort and refreshment in it from the Lord,
who let me see the beauty of holiness.
Indeed, the sweetness that arises from a humbled, mortified life,
was then very pleasant to my taste,
and I rejoiced in it more than in all the delights and pleasures of the world.

And now it pleased God to show me,
that if I would indeed live such a strict and holy life as adorns the gospel,
then I must leave the communion of the Church of England;
but I knew not yet which way to go, nor to which body of men I should join myself,
who were more orthodox and more steady in their lives.
As for the Quakers (so called),
I was so great a stranger to them that I had never read any of their books,
nor do I remember that I ever conversed with any
one man of that society in my whole life.
I think there was one in Foxly while I was a curate there, but I never saw the man,
though I went several times to his house on purpose to talk with him,
and to bring him off from his mad and wild enthusiasm,
as I then ignorantly thought it to be.
As for that way, I knew it was everywhere spoken against;
for he that had a mind to appear more witty and ingenious than the rest,
would choose them for the subject of his profane jests and mockery.
In this way men make sport, and entertain their company,
for a Quaker is but another name for a fool or a madman,
and is scarcely ever mentioned but with scorn and contempt.
As for mockery, I confess I was never any great friend to it; but indeed,
if all was true that was laid to the Quakers`' charge,
I thought they were some of the worst people that ever appeared in the world,
and wondered how they could call themselves Christians,
since I was told they denied the fundamental articles of the holy faith,
for which I ever bore the highest veneration and esteem.
And furthermore, I had always lived at the greatest distance from this people,
and was very zealous in the worship of the Church of England,
and upon all occasions would speak very honorably of it,
and was even content to suffer a few inconveniences upon that account,
as you very well know.
Yet my father still looked upon me as inclining to the Quakers,
and some years ago signified to a friend that he was afraid I would become an enthusiast.
And while I was at Bungan school,
he sent me two books to read that were written against the Quakers,
one of which was John Faldo`'s;
who has been sufficiently exposed for it by William Penn.

While I lived, in London, in that private, retired manner I was just now speaking of,
walking very humbly in the sight of God,
and having opportunity to reflect upon my past life,
I had occasion one day to be at a bookseller`'s shop,
and happened to cast my eye upon Robert Barclay`'s works.
Having heard in the country that he was a man of great account amongst the Quakers,
I had a mind to see what their principles were,
and what defense they could make for themselves; for surely, thought I,
these people cannot be so silly and ridiculous, nor maintainers of such horrid opinions,
as the author of [.book-title]#The Snake#^
footnote:[This book, which came out in the year 1696, was published anonymously.
The author was employed by some of the clergy to render
Friends and their principles odious to the world.
His misrepresentations were disproved, and his crafty artifices made manifest,
by Joseph Wyeth and George Whitehead in a book entitled, [.book-title]#A Switch for the Snake#.]
and some others would make us believe.
I took Barclay home with me, and I read him through in a week`'s time,
except for a little treatise at the end, which, finding to be very philosophical,
I omitted.
However,
I soon read enough to convince me of my own blindness and ignorance in the things of God.
For upon reading I found a light to break in upon my mind,
which did mightily refresh and comfort me in that poor, low,
and humbled state in which I then was; for indeed I was then,
and had been for a considerable time before, very hungry and thirsty after righteousness,
and therefore received the truth with all readiness of mind.
It was like balm to my soul,
and as showers of rain to the thirsty earth that is parched with heat and drought.
This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the Scriptures so clearly to me, that without standing to criticize, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God;
and weeping for joy that I had found so great a treasure,
I many times thanked Him with tears in my eyes for so kind a visitation of His love,
that He was graciously pleased to look towards me when my soul cried out for Him.
So, though before I was in great doubt and trouble of mind,
not knowing which way to turn,
yet now I found the sun breaking out so powerfully upon me that the clouds were scattered.
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.

So I immediately left the communion of the Church of England,
and went to Gracechurch Street Meeting.
After I had read Barclay, I read some other books of that kind,
among which was an excellent piece,
though in a small volume, called [.book-title]#No Cross, No Crown#.^
footnote:[By William Penn]
Thus I continued reading and frequenting meetings for several weeks together,
but did not let any one soul know what I was doing.
The first man I conversed with was George Whitehead;
and this was several weeks after I began to read Barclay, and attend Friends`' meetings.
By him I was introduced into more acquaintance with them; and still the further I went,
the more I liked their plainness, and the decency and simplicity of their conduct.
They do not use the ceremonies and salutations of the Church of England,
but shake hands freely,
and converse together as brothers and sisters that are sprung of the same royal Seed,
and made kings and priests unto God.
O the love,
the sweetness and tenderness of affection I have
seen among this people! "`By this,`" says Christ,
"`shall all men know that you are My disciples, if you love one another.`"
"`Put on therefore,`" says the apostle, "`as the elect of God, holy and beloved,
tender mercies, kindness, humbleness of mind, meekness, longsuffering.`"

Thus, my dear friend, I have given you an account of my proceedings in this affair.
As to my bodily state, if you desire to know what it is,
I may acquaint you that I have my health as well as ever,
and I bless God I have food and clothing sufficient for me,
so that I lack no outward thing.
Indeed, I have the necessities and conveniences of life,
so let us not burden ourselves with taking care for the vanities and superfluities of it.
Let us possess our vessels in sanctification and honor;
and even as we bring our minds into perfect subjection to the whole will of God,
so let us bring our bodies to the most simple and natural way of living.
Let us be content with the fewest things, never seeking to gratify our lustful appetites,
nor following the customs and humors of men,
but rather seeking how we may so govern our earthly cares
and pleasures that we may bring most glory to God,
most health and peace to our own souls, and do most service to the Truth.
And if this be our aim,
then certainly a very small portion of the things of this world will suffice us.
Seeing we are Christians,
we should therefore earnestly pursue those things which bring us nearest to God.
For whatever is more than a necessity, seems to be a burden to a soul,
which desires to breathe in a pure vessel,
that so it may have a living sense and relish of all blessings,
both of the superior and inferior worlds.

You know, my dear friend, that religion is a very serious thing.
Repentance is a great work,
and one precious immortal soul is of more worth than ten thousand perishing worlds,
with all their pomp and glory.
Therefore let us take courage and be valiant for the truth upon the earth.
Let us not content ourselves with a name and profession of godliness,
but let us come to the life and power of it, never despairing of getting the victory.
We have a little strength from God;
let us be faithful to Him and He will give us more strength,
so that we shall see the enemy of our peace fall before us,
and nothing shall be impossible unto us.
I say, my friend,
let us be faithful to that measure of light and knowledge which God has given us,
to be profited and edified by it in a spiritual life.
And as God sees we are diligent and faithful to work with the strength we have received,
He will more and more enlighten us,
so that we shall see to the end of those forms and
shadows of religion in which we formerly lived.
But if He sees we are about to take up our rest in those shadows,
or that we grow cold and indifferent in the pursuit of holiness,
running out into notions and speculations,
and have more a mind to dispute and to make a show of learning
and subtlety than to lead a holy and devout life,
then it is just for God to leave us in a carnal and polluted state.
Thus we will continue only in the outward court,
where we may please ourselves with beholding the beauty and ornaments of a worldly sanctuary,
and never witness the veil being taken away,
and being brought by the blood of Jesus into the holiest of all,
where alone there is true peace with God, and rest to the weary soul.
I could say much upon this subject, if time or leisure would give leave.

As for a particular answer to your letter, I have not time now to give it,
but desire for the present to let this general answer suffice.
And if you will consider things in their pure nature,
and not allow the prejudice of education to sway you,
but in fear and humility will search out the truth for yourself,
you will find that there is need for no other answer
to your letter than what I have already given.
For by waiting upon God, and diligently seeking Him,
you will find an answer to it in your own bosom; and this will be much more full, clear,
and satisfactory than I, or any other man living, can pretend to give you.
For truly I desire that you,
together with all the sincere-hearted in the Church of England,
may come to witness the almighty power of God to save and redeem them from every yoke;
and that they may clearly "`see to the end of those things which are abolished,`"^
footnote:[2 Corinthians 3:13]
and come to the enjoyment of spiritual and heavenly things themselves.
Indeed, this is the daily prayer and deep travail of my soul, God knows.

Until I can be more particular, if you please you may communicate this to the others,
and let them know that I am well, and thank them for their kind letters.
Let us remember to pray for one another with all fervency,
that we may stand perfect in the whole will of God.
Amen, says my soul.

[.signed-section-closing]
I am your most affectionate friend and servant in Jesus,

[.signed-section-signature]
Samuel Crisp

--

[.offset]
The following letter, or account of one Evan Jevans, is also remarkable.

[.embedded-content-document.letter]
--

Since it has pleased divine goodness to endue me with reason,
I heartily thank His most excellent Majesty,
that it has been the further product of His good will to give me life and being
in that part of the world where I have had the freedom to use it;
especially in the choice of my religious persuasion,
and the way of returning my acknowledgment to Him.
I wish that all who make any pretensions to religion,
would make use of this noble faculty (in subjection to the
divine will) to determine their choice in this grand affair;
and not let the religion of their education necessarily be that of their judgment.
If people were thus truly wise unto their own salvation,
and did not too lazily resign themselves to the conduct of other guides--thereby
regarding more their ease than their safety--they would not only be the
better able to give a reason for the hope that is in them,
but they would show more heart in their devotion, more charity in their religion,
and more piety in their conduct than they presently do.

When I was visited some time ago by the chastising hand
of the Lord for my sin and disobedience to His holy will,
I labored under great affliction of mind and anguish of spirit.
And though I was consistent above many in my attendance
of the public prayers of the church,
strict in my observation of its ceremonies,
and exceedingly frequent in the use of private devotion, yet my burden increased,
and I waxed worse.

In this wretched and doleful condition, when I was at a relation`'s house,
who had providentially returned from Pennsylvania to his native country,
I happened upon Robert Barclay`'s [.book-title]#Apology# for the Quakers;
by the reading of which I was well persuaded of their principles.
And by turning my mind inward to the divine gift (according to their doctrine),
it gave me victory in great measure over our common enemy,
banishing away my disorderly imaginations, and restoring me to my former regularity.
Indeed, I received such satisfaction and comfort to my distressed soul at this time,
that I thereupon left the church of England and joined myself in society with them.
And I am now even more confirmed in my change,
especially concerning the worship of our Creator,
for it is not only the most agreeable to the Scriptures of Truth, but,
in my own experience, heaven has many times given us an assurance of approbation,
powerfully crowning our meetings with the presence of the Most High.

I hope none will begrudge me this mercy just because I did not receive it by their ministry.
If they do,
I have cause to suspect that their charity is not truly of a Christian latitude,
since our blessed Redeemer did not approve of such narrowness
in His disciples in a somewhat similar case.

Oh that I may never forget the Lord`'s mercy to my soul,
who had compassion on me when I wallowed in my blood, and who said to the dry bones,
"`Live!`"
Oh that all who are visited by the chastising hand
of their Maker would seriously lay it to heart,
and consider their own welfare and salvation!
I could wish with all my heart, that those who labor under this anxiety of mind,
would take encouragement to hope in the Lord`'s mercy,
because of His kindness and long forbearance with me.
I am a living monument of it now;
and I hope I shall continue to be so while he affords me a being here.
If these lines should come to the hands of any that
are afflicted and distressed as I was,
I have (through mercy) an effectual remedy to prescribe unto them:
Turn your minds inward to the grace of God in your own hearts,
refrain from your own imaginations, be still,
and quietly resign yourselves to His holy will,
and so you shall find health to your souls, refreshment to your spirits,
and the sweet consolation of the Lord in your own bosoms.
Indeed, you shall find your mourning turned to gladness, and your heaviness into joy.
This has been my experience of the goodness of the Holy One of Israel,
who abhors sin and iniquity, and I therefore recommend it to you.

As for your charge that I have "`renounced the covenant
which I and every Christian ought to be under,
of forsaking the devil and all his works,`" I am so far
from entertaining one thought of neglecting that duty,
that I think myself wholly obliged to observe it.
And if I should affirm that, through the grace of God, and His assistance,
(for otherwise I know I cannot do it), the observation of this covenant is possible,
I can find no reason why it should be considered a false doctrine in a Quaker,
more than it is in a churchman.

As for "`deserting that church and ministry which the Son of God came down from
heaven to establish,`" I am not conscious of any guilt in this regard.
For, I believe Christ Himself is the head of our church,
and am convinced that His Spirit and His grace are what ordains our ministry.

And as to your last query,
I may let you know that my former despair and forlorn condition has been (since my adhering
to this reproached people) changed into a sweet enjoyment of the goodness of God.
I cannot conceal the Lord`'s goodness, lest he should withdraw His mercies from me.

There was no secular interest that corrupted my decision in this change.
Indeed, it is apparent to many, that I rather declined it.
For it was peace with God my Maker, and mercy to my soul, that I needed,
and having at last found the pearl of great price, I parted with all to purchase it.

--

From this account,
it appears that the writer aimed at nothing in his change of religious persuasion,
but the quietness of his mind, and the salvation of his soul.

Now I am to mention that the queen, in the year 1710, in her speech to the parliament,
having again declared that she would maintain the toleration and liberty of conscience,
was addressed by many;
wherefore the people called Quakers also esteemed it their
duty to show their grateful acknowledgment of this favor,
which they did by the following address.

[.embedded-content-document.address]
--

[.letter-heading]
To Queen Anne, of Great Britain, etc.

[.offset]
The humble and thankful address from people called Quakers,
in and about the city of London, on behalf of themselves,
and the rest of their persuasion.

When we consider the queen`'s royal regard to protect our religious liberty,
and the fresh assurance from the throne of her Christian resolution
to maintain the indulgence by law allowed to scrupulous consciences,
and her tender care that the same may be transmitted to
posterity in the Protestant succession in the house of Hanover,
we find ourselves gratefully obliged to acknowledge her goodness therein,
and so take this occasion to assure the queen of our duty and affection,
and peaceable behavior under her government, as is our principle,
and has always been our practice.

And we heartily desire our fellow-subjects may lay aside all animosities,
and in a spirit of love and meekness,
endeavor to outdo each other in virtue and universal love.

That it may graciously please Almighty God to defend and bless you, O queen,
and guide you by His counsel in a long and prosperous reign here,
and afterwards receive you to glory, is the hearty prayer of your faithful subjects.

--

To this address the Queen was pleased to answer, "`I thank you for your address,
and you may depend upon my protection.`"
The animosities mentioned in this address had regard to a division
that had begun to increase by a change of the ministry.
But this being out of my scope, I will not meddle with it.

In the year 1712, died Richard Cromwell, the son of Oliver the protector,
at about the age of ninety years.
This man had seen great changes in his lifetime,
having himself been at one time the supreme ruler of England,
as has been mentioned in its due place.

Although I do not intend to relate many more occurrences,
because I hasten towards a conclusion,
yet I think it worthwhile to add the following case:

In the year 1713, in the spring,
there was a lawsuit upon the _Act against Occasional Conformity_.^
footnote:[The __Act against Occasional Conformity__ was a law created to prevent
dissenters and Roman Catholics from "`occasionally`" attending the national church
for the sole purpose of making themselves eligible to hold public office.]
It happened that one John Penry,
a justice of peace of Allborough in the county of Suffolk,
while going to the parish church,
understood along the way that no service was to be held there at that time;
but hearing that there was a Quakers`' meeting in that place, he went to it instead.
One Wall, the bailiff of the place, being informed of this,
imagined that the said justice was not permitted
to go there because of the aforesaid act.
He therefore, thinking that something might be gained by it,
got witnesses to declare that justice Penry had been in the meeting;
and said afterwards in a boasting way to him, "`Now I have caught you!`"
To this the justice replied, "`I will stand to it.`"
The bailiff then entered his lawsuit in the name of one who lived thereabouts on charity.
When the case was pleaded at the court sessions, the judge,
who was baron Salathiel Lovel, declared the meaning of the aforementioned act to be thus:
That it did not regard any who periodically went into a meeting of dissenters;
but that it was against those who pretended a conformity with the Church of England,
thereby to qualify themselves for an office, without truly changing their religion.
But this was quite another case;
for the priest of the parish himself gave a certificate
declaring the said justice to be a good member of the church.
From here it appeared that the suit was mere malice;
and the witnesses (or informers) were brought into such a pinch,
that they dared not pursue a verdict from the jury,
for fear that they should be condemned to pay charges, and therefore let the thing fall.

The next year, being that of 1714, the queen was often ill,
and there was much division among the people;
for a bill was brought into parliament called __An Act to Prevent the Growth of Schism__;
and the prevailing party was very active to get this bill passed.
And since it aimed to deprive Protestant dissenters from keeping private schools,
granting that liberty to none but members of the Episcopal church,
or at least to none but those who were licensed by them, it met with great opposition,
and many reasons against it were published.
The people called Quakers also offered to the legislature several objections against it.
But whatever was objected, the said bill at length passed,
and was confirmed with the royal assent.
This gave occasion to the Quakers to add in the conclusion
of their printed epistle from their annual assembly at London,
the following caution and exhortation:
"`There seems at present to be a cloud hanging over us, threatening a storm.
Let us all therefore watch and pray,
and retire to our munition and stronghold in our
spiritual Rock and Foundation which stands sure;
that our God may continue to defend, help, and bless us as His peculiar people,
to the end of our days and time here,
and to the full fruition of the heavenly kingdom and glory hereafter.`"

About Midsummer this year died Sophia,
widow and electoral princess of Brunswick Lunenburg,
on whom the succession of the crown of Great Britain had been settled.
Scarcely two months after her demise, queen Anne also deceased,
who after having languished a long time,
at length was taken away by death on the first of August,
the very same day that the __Act to Prevent the Growth of Schism__ was to take effect.

The very same day, George, prince elector of Brunswick Lunenburg,
was proclaimed the new king of Great Britain; who returning to England some time after,
made his entry into London on the 20th of September.
Not long after his arrival,
he declared in council that he would maintain the
toleration in favor of the Protestant dissenters.
Hereupon many addresses of congratulation were presented to him,
and on the third of October the people called Quakers also offered their address,
which was delivered by George Whitehead and about forty of his friends,
having been introduced by the lord Townsend, one of the principal secretaries of state.
Not only was the king present, but many of the nobles, and others also;
and G. Whitehead presenting the address to the king, said,
"`We have come on behalf of the people called Quakers,
to present to king George our address and acknowledgment.
May it be favorably accepted.`"
Being then presented to the king, G. Whitehead said,
"`One of us may read it to the king.`"
Whereupon receiving it again, he delivered it to Joseph Wyeth, who read it audibly,
being as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To George, King of Great Britain, etc.

[.offset]
The humble address of the people commonly called Quakers.

[.salutation]
Great Prince,

It having pleased Almighty God to deprive these kingdoms of our late gracious queen,
we do in great humility approach your royal presence with hearts
truly thankful to divine Providence for your safe arrival,
with the prince your son,
and for your happy and uninterrupted accession to the crown of these realms; for,
to the universal joy of your faithful subjects,
this has secured to your people the Protestant succession,
and dissipated the just apprehensions we were under of losing those religious and civil
liberties which were granted us by law in the reign of king William III.,
whose memory we mention with great gratitude and affection.
We are also obliged to thankfully acknowledge your
early and gracious declaration in council,
wherein you have manifested your just sense of the state of your people,
which we hope will make all classes of your subjects feel easy.

And as it has been our known principle to live peaceably under government,
so we hope it will always be our practice, through God`'s assistance, to prove ourselves,
with hearty affection, your faithful and dutiful subjects.

May the wonderful Counselor and great Preserver of men,
guide the king by His divine wisdom; protect him by His power;
give him health and length of days here, and eternal felicity hereafter.
And may He so bless his royal offspring,
that they may never fail to adorn the throne with
a successor endowed with piety and virtue.

--

To this address the king was pleased to give this gracious answer:
"`I am well satisfied with the marks of duty you express in your address,
and you may be assured of my protection.`"

After the address was read, G. Whitehead spoke to this effect: "`We welcome you,
king George, and heartily wish you health and happiness, and your son the prince also.
King William III.
was a happy instrument in putting a stop to persecution, by promoting toleration, which,
being intended for the uniting of the king`'s Protestant subjects in interest and affection,
has so far had the effect as to make them more kind to one another,
even among the differing persuasions, than they were in former times of persecution.
We desire the king may have further knowledge of us and our innocency;
and be assured that to live a peaceable and quiet life in all godliness and honesty,
under the king and his government, is according to our principle and practice.`"

G+++.+++ Whitehead having thus spoken, his name was asked; whereupon he answered,
"`George Whitehead.`"
And having it upon his mind to see the king`'s son also,
and intimating this desire to a lord who was a gentleman to the prince`'s bed-chamber,
he made way for it.
Thus G. Whitehead, with some of his friends, got access to the prince.
They were introduced by one of the prince`'s gentlemen into a chamber,
where the prince met them; and then G. Whitehead spoke to him in substance what follows:
"`We take it as a favor that we are thus admitted to see the prince of Wales,
and we are truly very glad to see you.
Having delivered our address to the king, your royal father,
and being desirous to give you a visit in true love,
we very heartily wish health and happiness to you both;
and that if it should please God you should survive your father, and come to the throne,
you may enjoy tranquillity and peace.
I am persuaded, that if the king your father, and yourself,
do stand for the toleration for liberty of conscience to be kept inviolable,
God will stand by you.
May king Solomon`'s choice of wisdom be your choice,
together with holy Job`'s integrity and compassion to the oppressed.
And may the state of the righteous ruler commended by king David be yours, namely,
that '`He who rules over men must be just, ruling in the fear of God;
and he shall be like the light of the morning when the sun rises,
a morning without clouds,
like the tender grass springing out of the earth by clear shining after rain.`'^
footnote:[2 Samuel 23:3-4]`" This speech was favorably heard by the prince.

It was not long after the king`'s coming in that Dr. Gilbert Burnet, bishop of Salisbury,
the renowned author of the [.book-title]#History of the Reformation in England#, died.
He generally had showed himself moderate,
and had written very plainly against persecution in matters of faith,
especially in his [.book-title]#Apology for the Church of England#,
first printed in Holland in the year 1688, and afterwards also in England,
wherein among other things, he said,
"`I will not deny that many of the dissenters were
put to great hardships in many parts of England.
I cannot deny it, and I am sure I will never justify it.
And I will boldly say this, that if the church of England,
after she has gotten out of this storm,
will return to hearken to the peevishness of some sour men,
she will be abandoned both by God and man,
and will set both heaven and earth against her.`"

This year having come to an end, I go on to that of 1715.
In the month called May,
the term of the act for the Quakers`' solemn affirmation had almost expired;
and it was thereupon resolved in parliament that a bill
should be brought in to prolong that said term.
Thus, on the 7th of the said month,
a bill was accordingly brought into the House of Commons, read the first time,
and five days after the second time, and then committed.
And whereas the former act was limited to a number of years,
this limitation was now omitted, and consequently the act was to be perpetual.
Having advanced thus far, the bill was at length passed in the House of Commons,
and sent to the Lords, from which it was sent back with this addition,
that this favor should be extended also to the northern part of Great Britain,
known by the name of Scotland,
and to other plantations belonging to the crown of Great Britain for five years,
for the former act had not yet reached so far.

This amendment was agreed to by the House of Commons on the 13th of the said month,
and on the last of that month it was confirmed by the royal assent.
Thus the Quakers were protected anew against the heavy repercussions which
they otherwise might have expected on their refusal of an oath.
King George on all occasions having shown himself favorable to them,
they did not fail to thankfully acknowledge his kindness,
as appears from the general epistle of their annual assembly,
where they expressed their gratitude in these words:

[.embedded-content-document.epistle]
--

The Lord our God, who, for the sake of His heritage,
has often heretofore rebuked and limited the raging waves of the sea, has,
blessed be His name, mercifully dispersed the cloud threatening a storm,
which lately seemed to hang over us.
This, together with the favor God has given us in the eyes of the king and the government,
for the free enjoyment of our religious and civil liberties,
call for true thankfulness to Him.
And to humbly pray to Almighty God for the king and those in authority,
for his and their safety and defense, is certainly our Christian duty,
as well as to walk inoffensively as a grateful people.

--

Thus they signified their thankfulness for the favor they enjoyed;
and as this people did now enjoy both liberty and quiet,
so the other subjects were also maintained in their rights under a gentle government,
so that none who behaved themselves like peaceable subjects had cause to fear.
And yet, in many places in England there were still great convulsions and tumults;
and some hot-headed clergymen were not a little instrumental therein;
whereupon an open rebellion ensued,^
footnote:[The Battle of Preston (November 9-14,
1715) was the final battle of the Jacobite uprising of 1715,
an attempt to put James Francis Edward Stuart on
the British throne in place of George I.]
but the rebels were at last defeated near Preston by the king`'s forces.

Before I conclude this year, I must say that the French king Lewis XIV.
did not live to see the end of it, but on the first of September,
after having long languished from a malignant distemper,
he died in the 77th year of his age; having before appointed his brother`'s son,
the duke of Orleans, as regent of the kingdom of France.

This death seemed in some measure to alter the designs
of the Old Pretender (James Francis Edward Stuart),
who nevertheless, in the beginning of the year 1716,
came over from France to Scotland in hopes of making an inroad from there into England.
This attempt, however, miscarried, and his forces were routed by those of the king.
The common opinion was that he chiefly relied on assistance from France,
which was denied him by that court, though he seemed to have counted upon it.
He then lingered some time in Great Britain after his forces were defeated;
but seeing no way to invade the throne, he returned at length to France,
and after some time was made to depart from there also,
to the joy of many inhabitants of England;
for it was thought that the rebels being deprived of their chief,
the disturbance would be at an end.

Thus king George remained upon his throne,
and having solemnly assured the Quakers (so called) of his protection,
they continued to enjoy the due liberty of subjects that behave themselves
peaceably and dutifully under the government set over them,
and therefore have not neglected to exhort one another
to show their thankfulness to Almighty God,
and to pray for the king,
as has been shown already in one of the epistles of their yearly meeting.
And since mention has several times been made in this history of
the epistles of the annual assembly to the particular churches,
I have thought fit to insert one here, from the year 1717, which is as follows:

[.embedded-content-document.epistle]
--

[.blurb]
=== The Epistle from the Yearly Meeting in London, held from the 10th day of the Fourth month, to the 14th of the same, 1717. To the quarterly and monthly meetings of Friends in Great Britain, and elsewhere.

Our salutation, in the love of Christ Jesus our blessed Lord is freely extended unto you,
whose tender care and mercy to this our annual assembly
we do humbly and thankfully acknowledge,
by the love, goodwill,
and tender condescension manifested amongst us in
the divine power and goodness of the Lord our God,
and in the service of His church and people.

We are truly comforted to understand that there is such a general agreement
and union among all Friends with our former epistles of counsel,
recommending true and universal love, unity, peace,
and good order to be earnestly endeavored and maintained among us as a peculiar people,
chosen of the Lord out of the world,
to bear a faithful testimony to His holy name and truth in all respects;
and that all that is contrary must be watched against and avoided, such as strife,
discord, contention, and disputes tending to divisions.
Indeed, these must be utterly suppressed and laid aside,
as the light and righteous judgment of Truth require.

Oh, that all the churches and congregations of the faithful
would be stirred up by the Spirit of the dear Son of God,
to fervently pray for the prosperity of His church and people throughout the world,
that Zion may more and more shine in the beauty of holiness,
to the glory and praise of the King of glory.

The friends and brethren who have come up from the
several quarterly meetings in this nation,
have given a good report to us of truth`'s prosperity,
and that friends are generally in love and unity one with another.
Moreover, by several epistles from friends of North Carolina, Jersey, Pennsylvania,
Maryland, Barbados, Holland, Scotland, Ireland, and Wales,
which have been read in this meeting;
as also by verbal accounts given by several friends that
have lately travelled in many parts of America and elsewhere,
we have received comfortable accounts of the state of truth and friends in those parts;
by which we are encouraged to hope that truth prevails in many places,
and a concern grows upon friends for the prosperity thereof;
and that there is an inclination in many to hear the truth declared.

By the accounts brought up this year,
we find that fines imposed upon Friends`' in England and
Wales amount to five thousand two hundred and ninety pounds,
chiefly for tithes, priests`' wages, and steeple-house fees; and that,
notwithstanding four Friends have been discharged this last year,
there yet remain twenty Friends who are prisoners on these accounts.

We advise that a tender care remain upon Friends in all places
to be faithful in keeping up our Christian testimony against tithes,
being fully persuaded that God has called His people to this in our day;
and seeing by daily experience, that those who are not faithful therein,
do thereby add to the sufferings of honest friends,
and hinder their own growth and prosperity in the most blessed truth.

With regard to the upbringing of Friends`' children,
for which this meeting has often found a concern,
we think it our duty to recommend to you that there be a care in preserving children
in a plainness of speech and dress that is suitable to our holy profession;
and also that no opportunity be omitted, nor any endeavor lacking,
to instruct them concerning the light or seed of truth which we profess;
that thereby they, being sensible of its operations in themselves,
may not only find their spirits softened and tendered,
and made fit to receive the impressions of the divine image,
but also may find themselves under a necessity to be faithful
in the several branches of our Christian testimony.
And as this will be most beneficial to them, being the fruits of their own convictions,
so it is the most effectual way of propagating the same throughout the churches of Christ.
And knowing there are times and seasons wherein their spirits are, more than at others,
disposed to have those things impressed upon them; so we desire that all parents,
and others concerned in the oversight of youth,
might wait in the fear of God to know themselves divinely qualified for that service,
that in His wisdom they may make use of every such
opportunity which the Lord shall put into their hands.
And we do hereby warn and advise Friends in all places
to flee from every appearance of evil,
and to keep out of pride,
and away from following the vain fashions and customs of this world,
as recommended in the Epistle from 1715.

And as we always find it our concern to recommend love, concord,
and unity in the churches of Christ everywhere, we therefore,
as a means to effect the same,
earnestly desire that Friends labor to know their
own spirits subjected to the Spirit of Truth;
that thereby, being baptized into one body,
they may be truly one in the foundation of their love and unity,
and therein they may labor to find a nearness to each other in spirit.
This is the true way to experience a thorough reconciliation, wherever there is,
or may have been any differences of apprehension.
And thereby Friends will be preserved in that sweetness of spirit that is,
and will forever be, the bond of true peace throughout all the churches of Christ.

Finally, dear Friends and brethren,
be careful to walk unblameable in love and peace among yourselves,
and towards all men in Christian charity;
and be humbly thankful to the Lord our most gracious God for the
favor He has given us in the eyes of the king and civil government,
in the peaceable enjoyment of our religious and Christian liberties under them;
and the God of peace, we trust, will be with you to the end.

The grace of our Lord Jesus Christ be with your spirits.
Amen.

[.signed-section-closing]
Signed in, and on the behalf, and by the order of this meeting, by

[.signed-section-signature]
Benjamin Bealing.

--

From this epistle my readers may judge something of the others,
which are sent from the yearly meeting of the people called
Quakers to the particular meetings of their society everywhere.
We see by it, that they give notice of the condition of their particular churches,
and that they earnestly recommend love and unity among their brethren,
with other Christian virtues, and especially a good upbringing of their children,
besides other matters which they judge to be fitting and necessary.
With this epistle here inserted, I will finish this work,
as having performed my design and intention, namely,
the giving of a plain and circumstantial account
and relation of the rise of this religious society,
which, as we have seen, sprung from low beginnings, to a great increase and progress.
Indeed, it has now extended itself very far,
notwithstanding the violent opposition and most grievous severity so often
put in practice by their enemies for suppressing and rooting them out,
but all in vain.
And they now enjoy an undisturbed liberty to perform
the public exercise of their worship to God,
since their religion is permitted by law;
which liberty they in no way have obtained by making resistance,
but only by a long-suffering patience, a peaceable deportment,
and a dutiful fidelity to the government set over them.
So that now they see clearly, that God does not forsake those who do not forsake Him,
according to what the prophet Azariah formerly said to king Asa,
and to all Judah and Benjamin, 2 Chron.
15:2. "`The Lord is with you while you are with Him.
If you seek Him, He will be found by you; but if you forsake Him, He will forsake you.`"

[.asterism]
'''

Having thus performed what I intended with this historical relation, I now conclude it,
to the praise and glory of the Most High, who has afforded me life and ability,
after a long and difficult labor, to bring this history to a suitable end.

[.the-end]
End of Volume II
