== Forward by Editor

William Sewel`'s History of the Rise, Increase,
and Progress of the Christian People Called Quakers was first published in Dutch in 1717,
and then translated into English (by Sewel himself) and printed in 1722.
The original publication consisted of twelve volumes,
but was reprinted (with slightly modernized spelling
and punctuation) in 1832 in two large volumes.
The 1832 edition is in public domain,
and PDF scans of the two volumes are available online.
This particular version was obtained by copying the text from the PDFs,
pasting it into a Word document,
and then formatting the text and fixing the thousands
of errors that result from this process.
Most errors were found and fixed (by comparing them to the text of a printed copy),
but there are doubtless some that have been missed.

This document is the unabridged, two volume 1832 edition.
I have not modified the text in any way, except to modernize spelling (i.e. hath-has,
doth-does, etc.) and update a few archaic words (i.e. physic-medicine, Papist-Catholic,
etc.). I have also added one explanatory footnote, two or three definitions in brackets,
and some English translations for Latin phrases found throughout.
Before beginning, I suggest a quick perusal of the terms defined below.

Jason R. Henderson
April, 2017

Short Glossary of Terms:

Professor - One who professes faith in Christ

Forms - Outward ceremonies, structures, ordinances, practices in religion

Premunire - Premunire was a legal judgment designed to disenfranchise
those who refused to formally swear allegiance to the King of England.
Those under a sentence of premunire were considered traitors to their country.
They lost all rights to property and possessions,
were removed from under the kings protection, and were often imprisoned for life.

Prolixity - Unnecessary length, wordiness

Apostasy - falling away, departure, desertion of original Christianity.

Conventicle - An unlawful religious gathering
