== The Preface

After a labor of more than five and twenty years,
this history at length appears in public view;
to the compiling of which I was induced from the consideration
that the rise and increase of that religious society,
which in this work I have given a circumstantial account of,
is indeed so rare and wonderful a thing,
that I think few will be met with in modern histories,
which in the like respect may be compared therewith; because the Quakers, so called,
are become a great people, under such heavy oppression as is herein after mentioned:
and that not by any human power, or making resistance,
but merely by a harmless deportment, and the exercising of patience;
for bearing arms and resisting the wicked by fighting, they always have counted unlawful,
and contrary to the doctrine of our Savior.
Thus they who had no king, prince, nor potentate to protect them;
and who in the beginning had not among themselves any man of renown or literature,
but relying on their integrity, and trusting to God alone;
have at length triumphed over the malice of their opposers, by suffering,
(which rose to that degree that it was at the expense of the lives
of many of them,) under violent oppression from high and low,
and the opposition of learned and unlearned.

All this after much search, being found out by assiduous diligence,
appeared so wonderful to me, that I resolved to give a relation thereof,
notwithstanding the great labor I soon perceived this work required.
To this may be added, that when I considered that several authors,
both Germans and others,
had published books and accounts of this people stuffed with gross untruths,
I was the more spurred on thereby to set down in due order,
(for my countrymen`'s sake,) what I knew of the matter;
for it seems indeed to be of small advantage that when any thing is well known to us,
we keep that knowledge only to ourselves, without imparting it to others.

Now how difficult soever I found it, yet having made a beginning, I resolved to go on;
and so I did, though often stopped by several accidents, and also other work:
for during this labor I have not only translated several bulky books into Dutch,
besides Kennet`'s Antiquities of Rome, but also composed several treatises of importance,
and among these my great dictionary, English and Low Dutch.
And notwithstanding all these impediments,
I continually resumed this work by intervals so often,
that I have written it almost thrice to make it complete; for doubting of some things,
and finding others defective, it made me write to England for better information;
which having gotten at length, after much pains and long writing,
I was several times obliged to lay aside part of my former description and make anew one;
which happened so often, that had I not been supported by an unwearied application,
the difficulty of the labor, which had been much greater in Holland,
than if I had composed the work in England, would have made me give it over.
But I went on, and so finished this history in that form as it now appears.

And I am not without thoughts,
that I was prepared to be instrumental for such a work as this:
for several remarkable things I have made use of,
I had noted down before ever I thought of composing such a history;
and even in my young years, when I was in England,
I copied out from manuscripts several pieces and letters,
which are inserted in this history: it may be hardly to be found elsewhere.

At the first sight perhaps some will be ready to
think that I might have superseded this labor,
since the learned world has long ago seen a book written by Gerard Croese,
with the title of [.book-title]#Historia Quakeriana#.
But be it known to the reader,
that though the author got the chief contents thereof from me,
yet that relation which he gives of the rise and progress of the Quakers,
is very imperfect and defective;
and that he presumed to relate things of which he had no true knowledge.
I gave him indeed many things in writing, but not all I had collected;
besides having since that time written to my acquaintance in England,
I got narratives of many remarkable occurrences given forth in print there,
and many authentic pieces in manuscript.
Now though this collection was, as Ovid calls the chaos,
_'`rudis indigeslague moles,`'_ "`a rude undigested heap;`" yet from there,
and from my own collection of matters known to me,
I have compiled the greatest part of this history:
but as to the life and transactions of George Fox, who is largely treated in this work,
I took them chiefly from his journal; and the greatest part of other occurrences,
or the lives and transactions of others, I have taken from the works of deceased authors;
and out of abundance of small books published in print not long after the things happened,
and not contradicted by whatever I could learn.

Thus I have endeavored to assert nothing but what I had good authority for;
which in regard of some circumstances,
would have been yet far more difficult after the expiration of some years:
for now time gave opportunity to be informed of many things,
which some ancient people had yet remembrance of,
and which after their decease perhaps would have been buried in oblivion.

I cannot well omit here publicly to acknowledge the signal kindness and
diligence of my well-beloved and much esteemed friend Theodore Eccleston,
of London, who has furnished me with abundance of materials, not only very useful,
but also absolutely necessary for the compiling of this work:
from him I had intelligence on that account, and have exchanged a multitude of letters.
And thus by a long continued correspondence I came
to be acquainted with many things and circumstances,
which after some years might have been more difficult to obtain.

Add to this, that I have described several things well known to me,
which few besides myself within these thirty or forty years had better knowledge of.
I have also mentioned several remarkable cases,
which I noted down from the mouths of credible persons who have been dead many years,
and thought not that at any time I should have published them in print.
In the meanwhile I took account of what seemed to me worthy to be left upon record,
and collected a great quantity of books,
wherein many occurrences mentioned in this history were related.
Of such kind of relations and accounts I have made use of,
without taking from there all that was remarkable;
for it has not been for lack of matter that this history has not run out further,
since I could have made it thrice as big, if I had been minded so to do.
But as I was unwilling to extend my work any further than
my strength and health in all probability should permit,
so I would not glut my reader with many things of one and the same nature:
but have endeavored by variety of matter, to quicken his appetite;
and therefore have intermixed the serious part sometimes with a facetious accident.

Yet I have not thought myself bound to take notice of every
odd case that may have happened among the Quakers,
so called:
for there have conversed among them such who acted some particular
things that were not approved of by those of that society.
And if any one, swayed by human passion,
commits any excess which is disapproved of by his fellow members of the church,
such an act may not be duly imputed to the people he makes profession with.
Among such particulars may be reckoned the case of one Hester Biddle,
which Croese makes mention of about the end of his history.
For though it was told him from the relation she gave of it at Amsterdam,
not with any intention that he should publish it,
yet this was a particular case which she herself must be responsible for;
since experience has taught that imagination sometimes works so powerfully on the mind,
that one thinks himself obliged to do a thing which were better left undone.

Yet for all that, it is true, that men fearing God, may mistake,
and through ignorance do something,
which others not without reason might judge not commendable.
Also it may happen that some again, from a godly fear, have omitted what others,
no less pious, would not have scrupled.
And though some among the Quakers, in the beginning of their rise,
for fear of transgressing Christ`'s command, "`Be not you called Rabbi,
for one is your Master, even Christ,`" speaking to persons in authority,
called them by the name of Friend;
yet others of the same persuasion have not therefore thought themselves
bound to refuse to magistrates their distinguishing titles of magistracy.
No, if any, for some special reason,
may not have given a full or direct answer to a query,
yet others of the same society have not looked upon this as a pattern to imitate.
For the most eminent valiants among this people in the beginning,
were not men of note or learning, though of great courage:
insomuch that their immoveable steadfastness sometimes so exasperated their enemies,
that their fear of doing or omitting any thing which they judged would displease God,
often has been stamped with the odious denomination of stubbornness and stiff-neckedness;
but they have borne this patiently,
believing that it was their duty to persevere immovably in minding their Christian profession,
and in frequenting their religious assemblies.
And that such a steadfastness was the duty of a Christian,
seems also to have been the judgment of the authors of the
confession of faith of the reformed churches in the Netherlands,
Art.
xxviii.
where it is said, that it is the office or duty of all believers,
to separate themselves according to the word of God,
from those that are not of the church; and to join to this congregation,
in what place soever God has placed them,
though the magistrates and edicts of princes were against it;
and that death or any corporeal punishment was annexed to it.

It is true, there have been such among the Quakers,
who were exceedingly bold in representing to their enemies their evil behavior and deportment;
but this has been a peculiar talent of pious men,
of whom examples are extant in the [.book-title]#Book Of Martyrs#, i. e.
that some of them in very plain terms told their persecutors of their wickedness.
Very remarkable in that respect is the speech of John Molleus, who about the year 1653,
being prisoner at Rome,
without any dissimulation exposed to public view
the wicked lives of the cardinals and bishops,
who were ordered by the Pope to examine him.
The like boldness appears also in the letter of Hans van Ovendam,
to the magistrates of Ghent in Flanders,
as may be seen in the Mirror of Martyrs of the Baptists; from which it appears,
that the Quakers have not been the only people who have told their persecutors
very boldly of their wicked deportment and cruelty.

It cannot be denied that there have been at times
among this society some people of an odd behavior,
who in process of time embraced strange opinions and perverse notions;
but that is no new thing, since this has happened also among those of other persuasions,
though none of these would allow that this was the consequence or effect of their doctrine.
We find in Sacred Writ, that even in the primitive Christian church there were apostates;
either such as maintained strange doctrine, as the Nicholatians;
or such who finding the straight way too narrow for them, left it, and like Demas,
falling in love again with the world, entered into the broad way.
And therefore it can now, no more than then, be argued from there,
that the exorbitances to which some launched out,
were the effects of the doctrine they forsook.

Since in this history some predictions are also mentioned,
and some biassed by prejudice will perhaps look upon them as frivolous,
imagining that the Quakers pretend to have the spirit of prophecy; I will answer to this,
that though among thousands of them there may have
been one that prophetically foretold a thing,
which afterwards truly, happened;
yet others of that society presumed to have that
gift no more than to have that of being a preacher;
and are not called to that work.
There must be predecessors and leaders in the religious economy,
as well as in the politic state;
for if everyone not qualified should assume the office of governing,
things would soon run into confusion.
Now though some have had this false conceit,
that to be able to predict future things was a quality the Quakers attributed to themselves;
as proceeding from their doctrine, that Christians ought to be led by the Spirit of God;
yet this is a very sinister and preposterous conceit;
for what they say concerning the leading and guiding of the Spirit of God,
is agreeable with the doctrine of the apostle, who says,
"`As many as are led by the Spirit of God, they are the sons of God.`"
And this was also the doctrine of the first reformers.
What must we think then of those who will not be led by this spirit,
but call this doctrine by the odious denomination of enthusiasm?
The same apostle tells us also,
"`If any have not the Spirit of Christ he is none of his.`"
And he says also,
"`The manifestation of the Spirit is given to every man to profit withal.`"
But from there it does in no way follow that the spirit of prophecy is given to everyone;
neither that although it might please God to reveal to one a thing which yet was to come,
such a one therefore was endued with such a prophetical spirit,
that he was able at any time to predict future things.

If this position be true,
then those of other persuasions might also lay claim to that prerogative;
because among them sometimes there have been pious men who predicted remarkable things,
which afterwards really happened; as among the rest, James Usher, archbishop of Armagh,
and primate of Ireland,
who foretold the rebellion in Ireland forty years before it came to pass;
besides the intestine war and miseries that befell England,
and other things that were fulfilled:
which leads us not to reject as frivolous his prediction of the dreadful persecution
that would fall upon all the Protestant churches by the Roman Catholics;
for though one of his friends once objected to him,
that since Great Britain and Ireland had already suffered so deeply,
there was reason to hope that the judgments of God
in respect of these kingdoms might have been past;
yet he replied to it, '`Fool not yourselves with such hopes,
for I tell you all you have yet seen has been but the beginning of sorrows,
to what is yet to come upon the Protestant churches of Christ,
who will before long fall under a sharper persecution than ever yet has been upon them.
And therefore look you be not found in the outward court,
but a worshipper in the temple before the altar:
for Christ will measure all those that profess his name, and call themselves his people;
and the outward worshippers he will leave out, to be trodden down by the Gentiles.
The outward court is the formal Christian,
whose religion lies in performing the outside duties of Christianity,
without having an inward life and power of faith and love, uniting them to Christ:
and these God will leave to be trodden down and swept away by the Gentiles.
But the worshippers within the temple and before the altar,
are those who indeed worship God in spirit and in truth:
whose souls are made his temples,
and he is honored and adored in the most inward thoughts of their hearts;
and they sacrifice their lusts and vile affections, yes, and their own wills to him;
and these God will hide in the hollow of his hand, and under the shadow of his wings.
And this shall be the great difference between this last,
and all the other preceding persecutions;
for in the former the most eminent and spiritual
ministers and Christians did generally suffer most,
and were most violently fallen upon;
but in this last persecution these shall be preserved by God as a seed to partake
of that glory which shall immediately follow and come upon the church,
as soon as ever this storm shall be over; for as it shall be the sharpest,
so it shall be the shortest persecution of them all,
and shall only take away the gross hypocrites and formal
professors +++[+++i.e. professors of the Christian faith];
but the true spiritual believers shall be preserved till the calamity be over past.`'

If any now-a-days should speak at this rate,
it is credible that many who think themselves to be good Christians,
would decry this as mere enthusiasm.
But the said bishop is still in such great repute with the learned,
and has obtained such a high esteem by his writings,
that his words are likely to be of more weight with many, than those of other pious men.
And therefore I was willing to renew them, and revive his memory,
if perhaps this might make some impression upon the minds of any:
for this is a certain truth, that no outward performances will avail any,
if they do not worship God in spirit and in truth; for such worshippers God seeks,
according to what our Savior himself said; besides, that '`not everyone that says to him.
Lord, Lord, shall enter into the kingdom of heaven:`" no,
when many in that day will say to him, "`Lord, have we not prophesied in your name?`"
He will say to them, "`I never knew you; depart from me you that work iniquity.`"

As the many singular cases related in this history will
afford no un-pleasing entertainment to curious readers,
so they will be found also instructive;
for we shall not only meet with instances of true piety and love to one`'s neighbor,
and of saints triumphing on their death beds,
and also with remarkable examples of sinners truly penitent at the hour of death;
but we may also find here abundance of proofs of a peaceable behavior: for the Quakers,
so called, have not plotted against the government,
nor meddled with treasonable practices or rebellions;
and how much soever they were oppressed, yet they always were quiet,
and never made any resistance;
but with a harmless patience they have borne their most heavy oppressions and injuries,
and so at length overcame:
for to be subject to magistracy has always been one of their principles;
and that they were really dutiful subjects, they have showed at all times,
by paying obedience to the higher power, in all they could do with a good conscience.
And when any thing was required of them,
which from a reverential respect to God they dared not do, or omit;
they have showed their obedience by suffering, without making any resistance,
or joining with others who were inclined thereto.

Now though many have made it their business to represent them in odious colors,
and to write great untruths concerning them; no,
to fasten doctrines upon them which they never approved,
and that not a few of the learned have contended against them with their pens;
yet among these there have also been such, who though they never joined with,
yet gave a good account and favorable testimony concerning them,
as may be seen in Richard Claridge`'s answer to a book of Edward Cockson, page 266,
and seq.
And at Amsterdam in Holland, many years ago, a learned man published a book called,
_Lucerna super Candelabrum,_
wherein he very eminently defended the doctrine of the inward light;
and this book was published in Dutch, and afterwards also into English,
with the title of _The Light upon the Candlestick:_ and since the name of William Ames,
a zealous preacher among the Quakers, was placed upon the title,
many have believed him to be the author of that book,
because his doctrine of the divine and inward light was so effectually asserted therein.
That he approved the contents of the book I know;
but I know also that it never proceeded from his pen.
And many years afterwards it was published under
the name of one Peter Balling as the author,
though there were those who fathered it upon Adam Boreel,
because it is found printed in Latin among his _Scripta Postuma._
And this opinion is not altogether improbable,
for among his works are found also some other writings
that contain several positions asserted by the Quakers;
besides, he and some other of the collegians,
and among these also Dr. Galenus Abrahamson,
were so effectually convinced of the doctrine preached
by William Ames when he first came to Amsterdam,
that they approved of it; though afterwards from a misapprehension they opposed it.
Now if we presuppose that Adam Boreel was the author of the said Latin book,
Peter Balling might be the translator thereof into Dutch;
for that it was originally written in Latin seems to me very probable.

But however this be, it appears plainly, that the author would not publicly be known;
for the title seemed designedly composed so that the readers
should believe W. Ames to be the author of it,
namely:_ The Light on the Candlestick,_
serving for illustration of the principal matters in the book called,
_The Mysteries of the Kingdom of God, Etc._ against Galenus Abrahamson and his Assenters,
treated of, and written by W. Ames.
And this name stood in capital letters underneath,
in such a manner as the name of an author is usually placed upon a title;
though the publisher meant no more but that W. Ames was the author of the book called,
_The Mysteries of the Kingdom of God._
And there was no printer`'s name added to it, but only, Printed for the author, 1662.

Now though I cannot tell certainly who was the author, yet I have though fit,
since the said book is not easily to be got in Latin,
to insert it in the appendix of this history; from which it may appear,
as well as from the writings of some others,
that there have been such as either commended the Quakers, or defended their doctrine,
though they themselves never could resolve to join with them publicly.

But notwithstanding all this, there have been others, who,
to render the deportment and carriage of the Quakers suspected and odious,
have been ready to represent their honest behavior
and religious life as Pharisaical righteousness;
although Christ and his apostles earnestly recommended such a life.
Pray, what mean these words of our Savior, "`Be perfect,
even as your Father which is in heaven is perfect;`" but that we ought to endeavor,
to the utmost of our power, to lead a virtuous and godly life?
when those that heard the apostle Peter preach, were thereby pricked in their hearts,
and said, "`Men and Brethren, what shall we do?`"
he answered, "`Repent.`"
And at another time, "`Repent, you, and be converted, that your sins may be blotted out.`"
The apostle Paul says, "`Be not conformed to this world,
but be transformed by the renewing of your mind.`"
And the apostle Peter, agreeable to this, says, As obedient children,
not fashioning yourselves according to the former lusts in your ignorance;
but as he which has called you is holy,
so be holy in all manner of conduct;`" all which clearly implies,
that a Christian ought to be very strict and careful in his conduct;
and of this judgment were also the first reformers:
and that Archbishop Tillotson was also of the same mind appears
from many passages that are to be found in his sermons.

But though the Quakers have endeavored to make their
life and conduct agree with their Christian profession,
yet this has raised envy, grudge, and malice against them:
and among the clergy there have been such, who, to render them odious,
did not hesitate to represent them as disguised Roman Catholics,
notwithstanding these were none of their meanest enemies.
For, after a due reflection and consideration, it has seemed to me,
that when king Charles the second was on the throne, the Romanists,
and such among the church of England as favored them,
were the chief promoters of persecution.
And these, to pursue their wicked ends, would not proceed according to law,
in the trials of the imprisoned Quakers;
but they continually strove to introduce an arbitrary power, and so, from time to time,
they did not omit to prosecute the Quakers severely: thinking that,
when they were once suppressed, the other dissenters must fall of necessity,
though they were not for non-resistance.
But Providence acted very remarkably; for,
when a Catholic prince afterwards would introduce liberty of conscience,
the eyes of the most moderate maintainers of the church of England came to be so opened,
that, in the reign of King William III.
they promoted a general liberty of conscience,
by which the people called Quakers at length obtained liberty
to perform their public worship without molestation.

Thus far the limits of this history are extended; and being arrived there,
I did not think myself bound to enlarge any further;
what follows being no more than an overplus.

I have related nothing in this work but what I believed to be unquestionably true:
for what seemed doubtful to me, I rather chose to pass by;
having never been of so credulous a temper, as easily to take things on trust,
without due examination:
for we often see that high soaring imaginations make
people believe things that are far from being true.
But for all that,
we ought not to reject as untrue everything that appears strange or unusual;
since experience convinces us of the contrary, namely,
that sometimes we have seen a thing which, if we had not beheld with our own eyes,
we could hardly have believed.
Wherefore I would not reject as untrue what was extraordinary or unusual,
when it was told me by credible persons, or confirmed by eye-witnesses.
And therefore, though my reader may meet with some very singular occurrences,
yet this is true, that I have endeavored to the utmost to relate nothing but what,
after a nice inquiry, seemed to me to be true, or at least very probable.
And yet I have silently passed over some cases which I did not question to be true,
lest any might think me too credulous.

As to the transactions of state affairs,
I have taken them mostly from the history of the rebellion and the civil wars in England,
written by Edward Earl of Clarendon, and from the memoirs of Edward Ludlow.
Yet some few things relating to state affairs, that have not been mentioned by them,
nor in any other public history that I know of,
I thought worthy to be delivered to posterity by my pen.

For my style, I know it is but indifferent:
I do not pretend to elegancy in the English tongue; for, being a foreigner,
and never having been in England but about the space of ten months,
and that near fifty years ago,
it ought not to be expected that I should write English so well as Dutch,
my native language.
If therefore my pen has sometimes been guilty of a Belgicism, I beg excuse of my reader.
And since my absence has hindered me from correcting the printer`'s mistakes,
either in omissions or other errors, such faults I do not think myself responsible for,
because I have been willing to trust the oversight and correction of my work to others,
who may have been more liable to let errors escape than myself should have been.
This I hope will suffice to excuse me with discreet persons.

What the envious may judge of this work I little care for,
well knowing that the most eminent authors have been exposed to envy,
and been obnoxious to the censures of pedantic critics.
Whatever any may think, this I am well assured of,
that my chief scope has been by the relation of many unusual occurrences,
not only to delight my reader but also to lead him to virtue.
If I may be so happy as to have contributed thereto,
I shall think my pains well rewarded; and if not,
I shall have at least this satisfaction, that according to my ability,
I have endeavored to be beneficial to others,
and to edify my fellow-mortals in that which is good;
which I cannot but think to be well pleasing to God.
And if I have performed any thing that is good,
the honor and glory thereof belongs to him, who is the Giver of all good gifts;
and it is from Him alone I have received all my ability to do any good thing.
Thus concluding, I wish the reader discretion, and an impartial judgment.
