== Chapter I.

=== 1415--1650

[.chapter-synopsis]
* Gradual progress of Reformation
* Sufferings of Individuals on account of their religious principles
* Rise of the Puritans
* Birth and parentage of George Fox
* Beginning of civil war
* George Fox`'s early religious exercises
* Gradual unfolding of the doctrines of Truth on G. Fox`'s mind
* G. Fox begins to preach and travel from place to place
* Progress of the civil war
* Establishment of several meetings of Friends
* Every man enlightened by Christ
* Plain language of Thou and Thee
* First imprisonment of G. Fox
* Origin of the name Quaker
* Sundry addresses of G. Fox to Magistrates, Priests, &c.

That the wonderful Work of Reformation was small and of very-little account in its beginning,
and yet has been advanced with remarkable progress, will, I believe be denied by none,
that have with attention and due consideration read the history of its first rise;
since God the beginner and author of this glorious work, proceeding by steps and degrees,
used therein such singular wisdom and prudence, that every circumstance duly considered,
instead of censuring any part thereof, we shall be obliged to cry out.
You, O Lord, alone know the right times and seasons to open the eyes of the people,
and to make them capable of your truth!

If we look to the first beginnings, to go back no further than John Huss, we shall find,
that though in many things he was considerably enlightened,
yet he remained still in several gross errors;
for although he had a clear sight of the vain doctrines of purgatory, praying to,
and worshiping of images,
etc. nevertheless it is reported of him that he favored the invocation of saints,
the seven sacraments, auricular confession, and other tenets of the church of Rome;
and yet Christian charity constrains us to believe,
(though we find Protestant writers who deny him the name of a martyr,) that by his death,
which he suffered in the flames at Constance in Germany,
on the 6th of the month called July, in the year 1415,
he was an acceptable sacrifice unto God:
and with what a sedate and well composed mind he suffered death,
may be concluded from this,
that seeing a country fellow very zealously carrying wood to burn him, he said,
with a smiling countenance, O holy simplicity!
And after the fire was kindled, he sang with joy in the flames,
his mind being firmly established on God;
for he had been faithful according to his knowledge,
and had not hid his talent in the earth, but improved it,
having shown himself zealous promoter of that small
illumination which God was pleased to grant him;
it being without question great enough in that grievous night of darkness,
when idolatry had so universally blinded mankind, that, morally speaking,
it would have been impossible for them to have understood
the declaration of an entirely reformed religion;
whereas it is evident that the most sober and discreet people of that age were
capable to understand the doctrine and sermons of that honest man.

To give a clearer prospect into this matter, let it be considered,
that if a man had been kept shut up a long time in a dark prison,
where he could neither behold the light of the sun nor moon,
and should have been let out on a sudden at clear noon day,
he would not only not be able to endure the bright day light, but would also,
if he strove to open his eyes by force, be endangered of loosing his sight,
and falling into a worse condition than he was in before;
whereas if he had been brought into the open air at the time of twilight,
he would by degrees, have learned to discern the objects,
and come to an ability of beholding everything in a clear day aright.

Agreeably to this, in the reigns of Kings Henry the VIIIth, and the bloody Queen Mary,
the principal test in England was,
whether a man acknowledged the corporal presence of Christ in the sacrament;
and he who denied this, was to be burnt as a heretic.
Also in the Netherlands, it was enough to bring a man to the stake,
if he confessed he had been re-baptized.
In so much that it seems the Lord did raise in those days zealous
men chiefly to testify against the idolatry of the host,
and the error of infant baptism,
and that so gradually he might break down the great structure of human inventions.

Now, how small soever the beginnings of this great work of Reformation were,
yet it increased from time to time;
and oftentimes singular instances were seen of the
workings of the power and Spirit of God.

In the year 1513, I find that one John Le Clerc, of Meaux in France,
being at Metz in Lorrain, was filled with such zeal against idolatry,
that he broke to pieces the images in a chapel,
which the next day were to have been worshipped in a very solemn manner.
And being taken prisoner for this fact, and cruelly tortured to death,
he was so eminently strengthened, even to the amazement of the beholders,
that in the height of the torments, being torn with red hot pincers, he said,
from Ps. 115
"`Their idols are silver and gold, the work of men`'s hands.`"

Not less was the zeal of one Aymond a Vie, imprisoned in France about the year 1541,
because he had preached the gospel undauntedly; and though he had been advised to fly,
yet he would not be persuaded thereto, but said with a heroic mind,
'`I would rather never have been born, than commit such a base act;
for it is the duty of a good pastor not to fly from danger, but to stay in it,
lest the sheep be scattered.`'
He was tortured cruelly to betray his fellow believers; but no torment how great soever,
could extort the name of any from him;
and he suffered death valiantly for the testimony of Jesus,
feeling himself very powerfully strengthened by the Spirit of God,
which worked so gloriously in the martyrs of those times,
that those of Merindol in Provence said, '`The Holy Ghost is an infallible teacher,
by whose inspiration all Christians receive the knowledge of truth:
this spirit dwells in them, he regenerates them to a new life,
he slays the old man in them, and he makes them alive to every good work,
consoling them in tribulations, and strengthening them in adversities,`' etc.

And the pious professors at Meaux, I find mentioned in the year 1546,
that though a great number of men and women were led prisoners by but a few,
they yet made no resistance, but showed themselves harmless, not sad with grief,
but singing with joy.

No, so powerfully did God work in Gabriel Beraudin,
who was executed at Chambery in Savoy, in the year 1550,
that after his tongue was cut off by the hangman, he spoke intelligibly to the people,
and celebrated God`'s praise in a miraculous manner.

Claude Morier being burnt very cruelly at Lyons in France,
wrote while in his prison,`' Let us pray our heavenly Father continually,
that he create in us a clean heart, that he give us a new heart,
that he guide our will by the leadings of his Spirit.`'

Very remarkable it is also, that Godfried de Hammelle, a year after that,
being imprisoned at Tournay in the Netherlands,
and being told that the Apostle in his Epistle to the Ephesians,
had called marriage a sacrament, said in a letter,
'`That though at first this had puzzled him,
yet the Lord had not long left him in this difficulty, but put him in mind by his Spirit,
that the word there was not sacrament, but mystery.`'
For the martyrs of those times did not hesitate to profess,
with the primitive Christians, that the children of God must be led by his Spirit.

Peter Schryver, burnt at Lyons about the year 1552, wrote from prison,
'`That he having heard God`'s pure word preached, believed it,
because the Spirit of God gave him a testimony +++[+++or evidence]
of it in his heart: and did so confirm it to him,
and he could not question it in the least.`'
He also says in his letter, '`That once having prayed to God,
he had been so refreshed by the virtue of his Spirit, and so strengthened,
that though he sat in a dark nasty place, yet he felt such consolation and joy,
that overcame all sorrow and anguish.
No, said he, the least comfort and joy I feel now in my bonds,
surpasses all the joys that ever I had in my life;
for now the Holy Ghost puts me in mind of those gracious promises
that are made to those who suffer for his name`'s sake.`'
And being asked how he knew that which he asserted to be the pure word of God,
he answered, '`Because it did agree with the doctrine of the prophets and apostles,
and that of Jesus Christ; and that the Holy Ghost gave him a certain evidence thereof.`'
Concerning the indwelling of God`'s Spirit in man,
he also speaks very notably in his letter to John Chambon,
(whose wonderful conversion in prison,
was an eminent proof of the truth of his sayings,) telling him,
'`That his heavenly Father was near him, and by his Spirit dwell in his heart.`'

That this was also the doctrine of John Calvin,
appears from his letters to the said man and his fellow-prisoners, where he says,
'`Do not doubt but God will, in those things wherein he will use your service,
give you that power, by which the work in you being begun will be perfected,
for that he has promised to do:
and we have many examples and instances of that excellent faith,
by which we clearly know,
that God never in any thing has failed those who have been led and guided by his Spirit.
Trust firmly, brethren, that when it is needful, you will become so strong and steadfast,
that you shall not faint under any burden of temptations, how great and heavy soever.
The fight is now at hand, to which the Holy Ghost exhorts us, not only that we should go,
but even that with all alacrity of mind, we should run.`'
Many other excellent testimonies of eminent men of those times might be produced:
and it also is very remarkable that Peter Bergier, being prisoner at Lyons,
in the year 1553, and afterwards suffering death, cried in the midst of the flames,
'`I see the heavens opened.`'

Now that the doctrine of being taught by the Spirit of God,
was generally received by the martyrs of those times,
we learn from many of their writings.
Denis Peloquin, burnt in the said year at Vile Franche, said in his confession,
'`That it was the Holy Ghost that gave him witness in his conscience,
that the books of the Old and New Testament were the Holy Scripture.
Lewis de Marsac being about the same time put to death by fire at Lyons,
when he was asked how he knew the Holy Scriptures to be the gospel, said,
'`God has taught me so by his Spirit:`' and being also asked
whether it was his incumbent duty to read the Holy Scriptures,
and who had instructed him concerning them; he answered,
'`That God by his Spirit had effected it, that he got some knowledge thereof;
and that without his grace and the enlightening of his Spirit,
he could not comprehend and understand any thing in the gospel.`'
John Calvin did also write to the aforesaid Peloquin and Marsac;
'`God will cause that the confession which you will make
according to the measure of the Spirit he has given you,
will produce a greater fruit of edification, than all others that might be sent you.`'
And to Matthew Dymonet, prisoner at Lyons,
he wrote thus:`' Submit modestly to the guidings of God`'s Spirit;
answer with all moderation and discretion, keeping to the rule of the Scriptures.
I have believed, and therefore I will speak;
but let not this hinder you to speak freely and sincerely,
being persuaded that he who promised to give us a mouth,
and such wisdom as the gainsayers cannot withstand, will never forsake you.`'

More of the like instances of the operations of the
Spirit of God in his witnesses I could allege,
if I had so intended;
but I give here only a slender draft of the sincerity and the principle
of those that were come but to the dawnings of the Reformation;
for higher I cannot esteem that time,
because the eyes of the most zealous men of those days,
were yet so much covered with the fogs which then were,
and the prejudice of the old leaven,
that they did not discern all things in a full clearness;
for one saw the error of one thing, and others of another,
but human affection did work too strong, and thereby they judged one another,
as is abundantly mentioned in history.

If we rightly look into this, it seems very absurd to think that the Reformation,
(which in former times had been pretty much advanced by some eminent men; as Luther,
Melancthon, (Ecolompadius, Calvin, Menno, and others,) then was brought to perfection:
for we perceive that even those reformers themselves
at first had not such a clear sight into many things,
as afterwards they got, which to demonstrate at large, I count unnecessary.
Since England being the chief stage on which the
things I intend to describe have been transacted,
I will turn my face thitherward,
to take a view cursorily of the beginning and progress of the Reformation there.

Passing by Wickliffe and others, I begin with Thomas Cranmer, who,
because of his sincere and good life,
being advanced by King Henry the VIIIth to the Archbishop`'s see of Canterbury,
did all that was in his power to reform the errors crept into the Church of Rome;
and therefore in the year 1536, he exhorted the King, who much loved him,
to proceed to a reformation,
and that nothing in religion should be determined without clear proofs from Scripture;
and therefore he proposed that these points, '`Whether there was a purgatory,
Whether deceased saints ought to be invocated, and how images were to be regarded?`'
well needed to be inquired into;
since it began to appear that several things were errors,
for which some people not long before had suffered death.

Some time after, Thomas Cromwel a chief minister of the kingdom,
and a great friend of Cranmer, published some injunctions in the king`'s name,
wherein all churchmen were required, no more to recommend to people, images, relics,
or pilgrimages, but to teach them the Lord`'s Prayer, the Creed,
and the Ten Commandments in English.
This was a great step towards the translation of the Bible into English,
which being also furthered by Cranmer, the next year came out in print;
and by the king`'s warrant, the clergy were required to set up Bibles in their churches;
so that now all that could, might read the holy Scripture in their native tongue.
Cranmer not content with this, obtained in the year 1539,
a permission for all people to have the Bible in their houses; yet for all that,
he still was an asserter of the corporal presence of Christ in the host,
until in the year 1549, in the reign of King Edward VI. when the times were more free,
he was induced by Nicholas Ridley, a zealous reformer,
and afterwards a martyr under Queen Mary, to inquire better into the thing,
and to discover the absurdity of it;
from which he did not only oppose and suppress that superstition, but also many others;
and it is likely, that if opportunity had been given him, he would have reformed more.
Nevertheless it cannot but be wondered at,
that he who seems to have been a man of a meek temper,
could give his vote to the burning of those whom he looked upon to be heretics;
as John Nicholson alias Lambert, in the reign of Henry VIII.
for denying the corporal presence of Christ in the sacrament;
and Joan Bocher and George Parr,
under Edward VI. the first for denying that Christ had taken flesh from the Virgin Mary,
and the latter for not believing the deity of Christ: from which we may see,
what a strong zeal for religion is able to effect: but without question,
he was come to be of another mind, when in the year 1556,
under the bloody reign of Queen Mary, this was not only laid in his dish,
but he was also forced to undergo the same lot of being burnt alive.

Now, though after his death,
the bishops under Queen Elizabeth were content with the reformation made by Cranmer,
yet it pleased God in the year 1568,
to raise other persons that testified publicly against many of the remaining superstitions;
and although Coleman, Burton, Hallingham and Benson were imprisoned by the Queen`'s order,
yet they got many followers, and also the name of Puritans.
And notwithstanding the Archbishop, to prevent this, drew up some articles of faith,
to be signed by all clergymen, yet he met with great opposition in the undertaking:
for one Robert Brown, a young student of Cambridge,
(from whom the name of Brownists was afterwards borrowed,) and Richard Harrison,
a schoolmaster, published in the year 1583, some books,
wherein they showed how much the Church of England was still infected with Romish errors;
which was of such effect, that the eyes of many people came thereby to be opened,
who so valiantly maintained that doctrine which they believed to be the truth,
that some of the most zealous among them, namely, Henry Barrow, John Greenwood,
and John Penry, about the year 1593, were put to death because of their testimony, more,
(as may very well be believed,) by the instigation of the clergy,
than by the desire of the Queen: for some time after it happened,
that she asked Dr. Reynolds his opinion of those men, especially Barrow and Greenwood:
To which he answered,
'`That it would not avail any thing to show his judgment concerning them,
seeing they were put to death.`'
But the Queen yet pressing him further, he said,
'`That he was persuaded if they had lived,
they would have been two as worthy instruments for the Church of God,
as had been raised up in that age.`'
At which the Queen sighed, and said no more.
But afterwards riding by the place where they were executed,
and calling to mind their death, she demanded of the Earl of Cumberland,
who was present when they suffered, what end they made; he answered, '`A very godly end,
and they prayed for your Majesty and the State.`'
Moreover one Philips, a famous preacher, having seen Barrow`'s preparation for death,
said, '`Barrow, Barrow, my soul be with yours.`'

After the death of Queen Elizabeth, when James I. had ascended the throne,
the followers of those men suffered much for their separation from the Church of England:
but very remarkable it is, that even those of that persuasion,
of which many in the reign of King Charles I. went to New England,
to avoid the persecution of the bishops,
afterwards themselves turned cruel persecutors of pious people, by inhuman whippings,
etc. and lastly by putting some to death by the hands of a hangman: a clear proof indeed,
that those in whom such a ground of bitterness was left still,
though it had not always brought forth the like abominable fruits,
were not come yet to a perfect reformation;
for though the stem of human traditions and institutions sometimes had been shaken strongly,
yet much of the root was left.
Therefore it pleased God, who is used to enlighten men gradually,
to make yet a clearer discovery of his truth,
which in some places already darted forth its beams to mankind,
in a time when many godly people were zealously seeking
after a further manifestation of the will of God,
from a sense that,
notwithstanding all their outward observations of religious performances,
there still stood a partition wall whereby the soul was hindered
from living in perfect peace with its Creator.

For in that time there were in England many separate societies,
and among the rest also, such as were called Seekers,
who at first seemed to promise great matters;
but the sequel showed that their foundation was not the Rock of Ages,
and so many of them soon lost their first integrity.
Now those people who began to take heed to a divine conviction in the conscience,
and accordingly preached to others the doctrine of an inward light,
wherewith Christ had enlightened men,
in the latter end of the time of King Charles I. began to increase in number,
and they became a separate society among men, and in process of time the name of Quakers,
was in scorn imposed on them; and in most countries in Europe,
they have been accused of many exorbitant absurdities, both in life and doctrine.
I have designed to describe impartially, and according to truth,
the first beginnings and rise, and also the progress of that people,
and to stretch out the relation of their increase and transactions,
so far as my time of life and leisure will permit.

I enter upon a work, which consisting of many very singular instances,
in its beginning appears hard and difficult, and in the process often sad and dreadful.
For among manifold adversities, we shall not only meet with bitter revilings,
scornful mockings, rude abuses, and bloody blows from the fool-hardy rabble;
but also severe persecutions, hard imprisonments, grievous banishments,
unmerciful spoil of goods, cruel whippings, cutting off of ears, smotherings in prisons,
and also putting to death by the hands of the hangman, by order of the magistrates;
afterwards some quiet and rest; then again severe persecution,
until the furious promoters of it, at last wearied,
desisted from their mischievous labor for a time, more by being at their wits end,
than out of mercy.
And among all these vicissitudes,
notable instances have been seen of unfeigned godliness, sincere love,
much true-heartedness, extraordinary meekness, singular patience, ardent zeal,
undaunted courage, and unshaken steadfastness, even among the female sex,
which though the weakest, yet in the hardest attacks, showed a more than manly spirit;
insomuch,
that seldom any age has afforded matter where more
powerful examples to virtue have been seen.

The first I find that was thus immediately reached in his mind,
was a young man called George Fox, born at Drayton in Leicestershire,
in the month called July, in the year 1624,
from parents that were members of the public church, or church of England,
as appears to me from a paper, in his life-time drawn up by his order, at my request,
and sent me.
His father was Christopher Fox, a weaver by trade, an honest man,
and of such a virtuous life, that his neighbors were used to call him Righteous Christer.
His mother was Mary Lago, an upright woman, and of the stock of the martyrs.
This George Fox was even in his minority endued with a gravity and staidness of mind,
that is seldom seen in children;
so that he seeing how old people carried themselves lightly and wantonly,
had such an aversion to it, that he would say within himself,
'`If ever I come to be a man, surely I will not be so careless.`'
His parents in the meanwhile endeavored to train him up,
as they did their other children, in the common way of worship,
his mother especially contributing thereto, as being eminent for piety:
but even from a child he was seen to be of another frame of mind than his brethren;
for he was more religious, retired, still, and solid,
and was also observing beyond his age, as appeared from the answers he gave,
and the questions he asked, concerning religious matters,
to the astonishment of those that heard him.
His mother seeing this extraordinary temper and godliness,
which so early did shine through him, so that he would not meddle with childish plays,
did not think fit to trouble him about the way of worship,
but carried herself indulgent towards him.
Meanwhile he learned to read pretty well,
and to write so much as would serve him afterwards to signify his meaning to others.
When he was come to eleven years of age, he endeavored to live a pure and righteous life,
and to be faithful in all things, both inwardly to God, and outwardly to man;
since the Lord by his good spirit had showed him, that he was to keep his word always,
and that he ought not to commit excess in eating or drinking.
Thus growing up in virtue,
some of his relations were for having him trained up in the schools,
to make a priest of him; but others persuaded to the contrary,
and so he was put to a shoemaker, that dealt also in wool, and in cattle.
In his master`'s employment he took most delight in sheep,
and was very skillful in what belonged thereto,
for it was an employment that very well suited his mind; and his thus being a shepherd,
was, as an eminent author says, '`A just emblem of his after ministry and service.`'
He acquitted himself so diligently in his business, and minded it so well,
that his master was successful in his trade while George was with him.
He often used in his dealings the word Verily, and then he kept so strict to it,
that people that knew him, would say, '`If George says Verily, there is no altering him.`'

Now, though my design is not to give a description of state affairs,
yet I find it necessary to mention something of the chief temporal occurrences in England,
in as much as they may have relation to the affairs of the church,
lest my history might seem an incomplete work.
Transiently therefore I will say, that in England about this time,
appeared the beginnings of a civil war, in which religion had some share;
for the bishops began to introduce several innovations,
and caused not only rails to be made about the communion table,
which now was called the high altar; but those that approached it, bowed thrice,
and a bow was made at the pronouncing of the name of Jesus.
Thus ceremonies increased from time to time;
and those preachers that were really religious, and spoke most to edification,
were slighted and set by; the bishops, in their visitations,
minding chiefly to promote such rites as favored popery:
and this was not only done in England,
but in Scotland also endeavors were made to bring in episcopacy.
This caused a ferment among the people, which when it came to an insurrection,
they generally believed that it was for religion`'s sake,
which made some cry in the open streets, where there was any confluence of people,
'`To your tents, O Israel.`'
And because the Parliament was of opinion that King
Charles I. encroached upon their privileges,
which they would not permit, this so exasperated that prince,
that he brought together an army, and set up his standard,
first on the castle of Nottingham, where it was blown down the same evening,
on the 25th of the month called August, in the year 1642.
But before that time the king had taken possession of some fortified places,
and the Parliament on the other hand, had also got some in their power.
Some time after, a battle was fought between the Royalists and the Parliament,
near Edge Hill, in Warwickshire, where neither party prevailed much.

About this time George Fox, who more and more endeavored to lead a godly life,
being come to the nineteenth year of his age, it happened at a fair,
that a cousin of his and another coming to him,
asked whether he would drink a jug of beer with them; he being thirsty, said yes,
and went with them to an inn; but after each had drank a glass,
they began to drink healths, and said, that he that would not drink should pay for all.
This grieved George much, seeing that people who professed to be religious,
behaved themselves thus, and therefore he rose up to be gone,
and putting his hand into his pocket, he took a groat, and laid it down upon`',the table,
saying, '`If it be so I`'ll leave you;`' and so he went away;
and when his business was done, he returned home; but did not go to bed that night,
but prayed and cried earnestly to the Lord;
and it seemed to him that his supplications were answered after
this manner,`' You see how young people go together into vanity,
and old people into the earth; therefore you must forsake all,
both young and old and be as a stranger to them.`'
This, which he took to be a divine admonition,
made such a powerful impression on his mind,
that he resolved to break off all familiar fellowship
and conversation with young and old,
and even to leave his relations, and live a separate and retired life.
On the 9th of September, in the year 1643, he departed to Lutterworth,
where he stayed some time, and from there went to Northampton,
where he also made some stay, and then passed to Newport-Pagnel, in Buckinghamshire;
and after having stayed a while there, he went to Barnet,
where he came in the month called June, in the year 1644.

While he thus led a solitary life, he fasted often,
and read the holy Scriptures diligently, so that some professors took notice of him,
and sought to be acquainted with him.
But he soon perceiving they did not possess what they professed, grew afraid of them,
and shunned their company.
In this time he fell into a strong temptation, almost to despair,
and was in mighty trouble, sometimes keeping himself retired in his chamber,
and often walking solitary to wait upon the Lord.
In this state he saw how Christ had been tempted;
but when he looked to his own condition, he wondered, and said, '`Was I ever so before?
He began to think also that he had done amiss against his relations,
because he had forsaken them; and he called to mind all his former time,
to consider whether he had wronged any.
Thus temptations grew more and more;
and when Satan could not effect his design upon him that way,
he laid snares for him to draw him to commit some sin, thereby to bring him to despair.
He was then about twenty years of age, and continued a long while in this condition,
and would eagerly have put it from him;
which made him go to many a priest to look for comfort, but he did not find it from them.
In this miserable state he went to London,
in hopes of finding some relief among the great professors of that city;
but being come there, he saw them much darkened in their understandings.
He had an uncle there, one Pickering, a baptist,
and those of that persuasion were tender then;
yet he could not resolve to impart his mind to them, or join with them,
because he saw all, young and old, where they were.
And though some of the best would have had him stayed there, yet he was fearful,
and so returned homewards;
for having understood that his parents and relations were troubled at his absence,
he would rather go to them again lest he should grieve them.
Now when he was come into Leicestershire, his relations would have had him married;
but he prudently told them he was but a lad, and must get wisdom.
Others would have had him in the auxiliary band among the forces of the Parliament,
which being entered now into an intestine war with the king, had,
with their forces this year, beaten not only the king`'s army under Prince Rupert,
but also had conquered the city of York.
But to persuade George to list himself a soldier, was so against his mind,
that he refused it, and went to Coventry,
where he took a chamber for a while at a professor`'s house, where he stayed some time,
there being many people in that town who endeavored to live religiously.
After some time he went into his own country again, and was there about a year,
in great sorrows and troubles, walking many nights by himself.

Nathaniel Stevens, the priest of Drayton,
(the town of George`'s birth,) would often come to him, and George to the priest;
and when Stevens visited him, he would sometimes bring another priest along-with him,
and then George would ask them questions, and reason with them.
Once Stevens asked him why Christ cried out upon the cross.
"`My God, my God, why have you forsaken me:`'--and why he said, If it be possible,
let this cup pass from me; yet not my will but yours be done.`'
To this George answered thus: '`At that time the sins of all mankind were upon Christ,
and their iniquities and transgressions with which he was wounded, which he was to bear,
and to be an offering for them, as he was man; but died not, as he was God: and so,
in that he died for all men, and tasted death for every man,
he was an offering for the sins of the whole world.`'
When George Fox spoke this, he was in some measure sensible of Christ`'s sufferings,
and what he went through.
And his saying did so please the priest, that he said it was a very good full answer,
and such a one as he had not heard.
He would also applaud and speak highly of George Fox to others,
and what George said in discourse to him,
that he would preach of on the First-days of the week:
for which George did not like him.

After some time he went to an ancient priest at Mansetter, in Warwickshire,
and reasoned with him about the ground of despair and temptations;
but he being altogether ignorant of George`'s condition, bid him take tobacco,
and sing psalms.
But George signified that he was no lover of tobacco, and as for psalms,
he was not in a state to sing.
Then the priest bid him come again, and that then he would tell him many things.
But when George came, the priest was angry and pettish,
for George`'s former words had displeased him; and he was so indiscreet,
that what George had told him of his sorrows and griefs, he told again to his servants,
so that it got among the milk-lasses;
and grieved him to have opened his mind to such a one;
and he said they were all miserable comforters.
Then he heard of a priest living about Tamworth, who was accounted an experienced man,
and therefore he went to him, but found him like an empty hollow cask.

Hearing afterwards of one Dr. Cradock of Coventry, he went to him also,
and asked him from where temptations and despair did arise,
and how troubles came to be wrought in man.
The priest, instead of answering, asked him who was Christ`'s father and mother.
George told him Mary was his mother; and he was supposed to be the son of Joseph;
but he was the Son of God.
Now as they were walking together in Dr. Cradock`'s garden, it happened that George,
in turning, set his foot on the side of a bed, which so disturbed that teacher,
as if his house had been on fire, and thus all their discourse was lost;
and George went away in sorrow, worse than he was when he came,
seeing he found none that could reach his condition, after this he went to one Macham,
a priest of high account; and he, no more skillful than the others,
was for giving George some medicine, and for bleeding him;
but they could not get one drop of blood from him, either in the arms or the head;
his body being, as it were, dried up with sorrows, grief, and trouble,
which were so great upon him, that he could have wished never to have been born,
to behold the vanity and wickedness of men; or that he had been born blind,
and so he might never have seen it; and deaf,
that he had never heard vain and wicked words, or the Lord`'s name blasphemed.
And when the time called Christmas came,
while others were feasting and sporting themselves, he went from house to house,
looking for poor widows, and giving them some money.
And when he was invited to marriages, (as sometimes he was,) he would go to none at all;
but the next day, or soon after, he went and visited those that were newly married;
and if they were poor, he gave them some money;
for he had wherewith both to keep himself from being chargeable to others,
and to administer something to the needful.

While the mind of George Fox was thus in trouble,
the state of England was also in a great stir;
for the Parliament was for turning out of bishops,
and introducing the Presbyterian Directory; which, however,
as yet could not be well affected, although William Laud, Archbishop of Canterbury,
had been made to stoop to the block;
and the power of the king by this time was much weakened;
for his army was this summer near Naseby, not far from Leicester,
overcome by an army of untrained bands, and about six thousand men,
among whom many great officers were taken prisoners, and his cabinet,
with abundance of letters of great importance, was seized; insomuch,
that though they had some skirmishes, yet no decisive battle was fought afterwards.

But since a circumstantial description of these state affairs is not within my design,
I will return again to George Fox, who in the beginning of the year 1646,
as he was going to Coventry, and entering towards the gate,
a consideration arose in him how it was said that all Christians
are believers both Protestants and Catholics:
and it was opened to him, that if all were believers, then they were all born of God,
and passed from death to life; and that none were true believers but such:
and though others said they were believers, yet they were not.
At another time as he was walking in a field on a First-day morning,
it was discovered unto his understanding,
that to be bred at Oxford or Cambridge was not enough
to make a man to be a minister of Christ.
At this he wondered, because it was the common belief of people; but for all that,
he took this to be a divine revelation, and he admired the goodness of the Lord,
believing now the ordinary ministers not to be such as they pretended to be.
This made him unwilling to go any more to church, as it was called,
to hear the priest Stevens, believing that he could not profit thereby:
and therefore instead of going there, he would get into the orchard, or the fields,
by himself, with his Bible, which he esteemed above all books,
seeking thus to be edified in solitariness.
At this his relations were much troubled; but he told them,
did not John the Apostle say to the believers, "`that they needed no man to teach them,
but as the anointing teaches them;`" and though they knew this to be Scripture,
and that it was true, yet it grieved them,
because he would not go to hear the priest with them,
but separated himself from their way of worship:
for he saw now that a true believer was another thing than they looked upon it to be;
and that being bred at the universities did not qualify a man to be a minister of Christ.
Thus he lived by himself, not joining with any, no, not of the dissenting people,
but became a stranger to all, relying wholly upon the Lord Jesus Christ.

Some time after, it was opened in him, that God, who made the world,
did not dwell in temples made with hands.
And though this seemed at first strange to him,
because both priests and people used to call their churches dreadful places, holy ground,
and temples of God; yet it was immediately showed him,
that the Lord did not dwell in these temples which man had erected,
but in peoples hearts, and that his people were the temple he dwelt in.
This was discovered to him when he was walking in
the fields to the house of one of his relations.
And when he came there, it was told him,
that Nathaniel Stevens the priest had been there, and told them he was afraid of Fox,
for going after new lights.
This made him smile, because now he saw the true state of the priests.
But he said nothing of this to his relations, who,
though they saw that something more was required than the vulgar way of worship,
yet they continued therein,
being grieved because he would hot also go to hear the priests.
Only he told them there was an anointing in man, to teach him;
and that the Lord would teach his people himself.
He had great openings now concerning the things written in the Revelations;
and when he spoke of them, the priests and professors would say,
that was '`a sealed up book.`'
But to this he said, Christ could open the seals,
and that the things contained in that book, very nearly concerned us;
since the Epistles of the Apostles were written to the saints of those times,
but the Revelations point at things to come.`'

In England, in those days, were people of very odd notions,
and among the rest such as held,`' that women have no souls.`'
He lighting on some of these, could not forbear reproving them, since the Scripture,
as he told them plainly, held forth the contrary; for the blessed Virgin Mary said,
"`My soul does magnify the Lord; and my spirit has rejoiced in God my Savior.`"
He also came among a people that relied much on dreams; but he told them,
'`Except they could distinguish between dream and dream,
their observations would be nothing but confusion,
since there were three sorts of dreams;
for multiplicity of business sometimes caused dreams;
and there were whisperings of Satan in the night seasons;
and there were also speakings of God to man in dreams.`'
But because these people were more in need of a clear discerning, than of good will,
they at length came out of those imaginations,
and at last became fellow-believers with him; who,
though he had great openings in his understanding,
yet great trouble and temptations many times came upon him; so that when it was day,
he wished for night, and when it was night, he wished for day.
Nevertheless among all those troubles, his understanding was so opened,
that he could say with David, "`Day unto day utters speech,
and night unto night shows knowledge;`" for even in these troubles
he had great openings of many places in scripture.

As to state affairs, things continued in a distracted condition; for the King,
who after his army had been beaten, was gone to the Scots,
was by them delivered up to the English; to whom now he could no more prescribe laws,
but was willing to receive them.
And the Churchmen were also at variance; for the Independents,
(several of which sat also in Parliament) began to say, that between Episcopacy,
(against which they had fought conjunctly,) and Presbytery,
the difference was only in the name, and some few outward circumstances;
since people of a tender conscience might apprehend no less oppression from the Presbyterians,
than from the Episcopalians: and that this fear was not vain or idle,
time afterwards has shown abundantly.

But let us return to George Fox, who in the beginning of the year 1647,
feeling some drawings to go into Derbyshire, went there,
and meeting there with some friendly people, had many discourses with them.
Then passing further into the Peak-Country, he met with more such people,
and also some that were swayed by empty and high notions.
And traveling into Nottinghamshire, there he met with a tender people,
and among these one Elizabeth Hooton, of which woman more will be said in the sequel:
with these he had some meetings and discourses.
But his troubles and temptations still continued; and he fasted much,
and walked often abroad in solitary places, taking his Bible with him;
and then sat in hollow trees, and lonesome places till night came on;
and frequently in the night he walked mournfully about,
being surrounded with many sorrows in the times of
these first workings of the Lord in him.

During all this time, he never joined in profession of religion with any,
but gave up himself to the disposing of the Lord;
having forsaken not only all evil company, but also taken leave of father and mother,
and all other relations; and so he travelled up and down as a stranger on the earth,
which way he felt his heart inclined: and when he came into a town,
he took a chamber to himself there, and tarried sometimes a month, sometimes more,
sometimes less, in a place; for he was afraid of staying long in any place, lest,
being a tender young man, he should be hurt by too familiar a conversation with men.

Now, though it might seem not very agreeable with the gravity of my work,
to mention what kind of clothes he wore in these first years of his peregrination;
yet I do not count it absurd to say here,
that it is indeed true what a certain author named Gerard Croes, relates of him,
that he was clothed with leather; but not, as the said author adds, because he could not,
nor would not, forget his former leather work;
but it was partly for the simplicity of that dress,
and also because such a clothing was strong, and needed but little mending or repairing;
which was commodious for him who had no steady dwelling place,
and everywhere in his traveling about sought to live in a lonely state:
for keeping himself thus as a stranger, he sought heavenly wisdom,
and endeavored to get knowledge of the Lord, and to be weaned from outward things,
to rely wholly on the Lord alone.
Although his troubles were great, yet they were not so continual,
but that he had some intermissions, and was sometimes brought into such a heavenly joy,
that admiring the love of God to his soul, he would say with the Psalmist, "`You, Lord,
make a fruitful field a barren wilderness, and a barren wilderness a fruitful field.`"
Now he regarded the priests but little,
because he clearly saw that to be trained up in the universities,
and to be instructed in languages, liberal arts, and the like sciences,
was not sufficient to make any one a minister of the gospel;
but he looked more after the dissenting people; yet as he had forsaken the priests,
so he left the separate preachers also,
because he saw there was none among them all that could speak to his condition.
And when all his hopes in them, and in all men were gone, then he heard,
according to what he relates himself, a voice which said, '`There is one,
even Christ Jesus, that can speak to your condition.`'
Having heard this, his heart leapt for joy,
and it was showed him why there was none upon the earth that could speak to his condition;
namely, that he might give the Lord alone all the glory,
and that Jesus Christ might have the preeminence.

He then experimentally knowing that Christ enlightens man, and gives him grace, faith,
and power, his desires after the Lord,
and his zeal in the pure knowledge of God grew stronger;
so that he wished to increase therein without the help of any man, book, or writing.
Yet he was a diligent reader of the holy Scriptures,
that speak at large of God and Christ, though he knew him not but by revelation, as he,
who had the key, did open.
Thus he entered into no fellowship with any society of people,
because he saw nothing but corruptions everywhere;
which made him endeavor to keep fellowship only with Christ:
since in the greatest temptations, when he almost despaired, it was showed him,
that Christ had been tempted by the same devil; but that he had overcome him,
and bruised his head, and that therefore through the power, light, grace,
and Spirit of God, he himself might also overcome.
Thus the Lord assisted him in the deepest miseries and sorrows,
and he found his grace to be sufficient: insomuch,
that though he had yet some desires after the help of men,
his thirst was chiefly after the Lord, the Creator of all, and his Son Jesus Christ;
because nothing could give him any comfort but the Lord by his power;
and he clearly saw that all the world, though he had possessed a king`'s state,
would not have profited him.

In this condition his understanding came more and more to be opened,
so that he saw how death in Adam had passed upon all men; but that by Christ,
who tasted death for all men, a deliverance from it, and an entrance into God`'s kingdom,
might be obtained.
Nevertheless his temptations continued,
so that he began to question whether he might have sinned against the Holy Ghost.
This brought great perplexity and trouble over him for many days;
yet he still gave up himself to the Lord: and one day,
when he had been walking solitarily abroad, and was come home,
he became exceeding sensible of the love of God to him,
so that he could not but admire it.
Here it was showed him, that all was to be done in and by Christ;
that he conquers and destroys the tempter, the devil, and all his works;
and that all these troubles and temptations were good for him,
for the trial of his faith.
The effect of this was, that though at times his mind was much exercised,
yet he was stayed by a secret belief; and his soul, by a firm hope,
which was to him as an anchor, was kept unhurt in the dissolute world,
swimming above the raging waves of temptations.
After this, (as he relates himself,) there did a pure fire appear in him;
and he saw that the appearance of Christ in the heart was as a refiner`'s fire,
and as the fuller`'s soap; and that a spiritual discerning was given to him,
by which he saw what it was that veiled his mind, and what it was that did open it:
and that which could not abide in patience, he found to be of the flesh,
that could not give up to the will of God, nor yield up itself to die by the cross,
which is the power of God.
On the other hand,
he perceived it was the groans of the Spirit which did open his understanding,
and that in that Spirit there must be a waiting upon God to obtain redemption.

About this time he heard of a woman in Lancashire that had fasted twenty-two days,
and he went to see her: but coming there he saw that she was under a temptation:
and after he had spoken to her what he felt on his mind, he left her,
and went to Duckenfield and Manchester,
where he stayed awhile among the professors he found there,
and declared to them that doctrine which now he firmly believed to be truth;
and some were convinced, so as to receive the inward divine teaching of the Lord,
and take that for their rule.
This, by what I can find, was the first beginning of George Fox`'s preaching;
which as I have been credibly informed, in those early years,
chiefly consisted of some few, but powerful and piercing words,
to those whose hearts were already in some measure
prepared to be capable of receiving this doctrine.
And it seems to me that these people, and also Elizabeth Hooton,
(already mentioned,) have been the first who by such
a mean or weak preaching came to be his fellow believers:
though there were also some others who, by the like immediate way, as George Fox himself,
were convinced in their minds,
and came to see that they ought diligently to take
heed to the teachings of the grace of God,
that had appeared to them.
And thus it happened that these unexpectedly and unaware came to meet with fellow-believers,
which they were not acquainted with before,
as will be more circumstantially related hereafter.

But to return again to George Fox; it set the professors of those times in a rage,
that some of their adherents hearkened to his preaching;
for they could not endure to hear perfection spoken of, and a holy and sinless life,
as a state that could be obtained here.
Not long after he travelled to Broughton in Leicestershire,
and there went into a meeting of the Baptists,
where some people of other nations also came.
This gave him occasion to preach the doctrine of truth among them, and that not in vain;
for since he had great openings in the scriptures,
and that a special power of the Lord`'s workings began to spring in those parts,
several were so reached in their minds, that they came to be convinced,
and were turning from darkness to light, partly by his preaching,
and partly by reasoning with some.
Yet he himself was still sometimes under great temptations,
without finding any to open his condition to, but the Lord alone,
unto whom he cried night and day for help.

Some time after he went back into Nottinghamshire,
and there it pleased the Lord to show him,
that the natures of those things which were hurtful without, were also within,
in the minds of wicked men; and that the natures of dogs, swine, vipers,
and those of Cain, Ishmael, Esau, Pharaoh, etc. were in the hearts of many people.
But since this did grieve him, he cried to the Lord, saying, '`Why should I be thus,
seeing I was never addicted to commit those evils?
And inwardly it was answered him,
'`That it was needful he should have a sense of all conditions;
how else should he speak to all conditions?`'
He also saw there was an ocean of darkness and death;
but withal an infinite ocean of light and love, which flowed over the ocean of darkness;
in all which he perceived the infinite love of God.
About that time it happened that walking in the town of Mansfield,
by the steeple-house side, it was inwardly told him,
'`That which people trample upon must be your food;`' and at the saying of this,
it was opened to him, that it was the life of Christ people did trample upon;
and that they fed one another with words,
without minding that thereby the blood of the Son of God was trampled under foot.
And though it seemed at first strange to him,
that he should feed on that which the high professors trample upon,
yet it was clearly opened to him how this could be.

Then many people came far and near to see him;
and though he spoke sometimes to open religious matters to them,
yet he was fearful of being drawn out by them.
Now the reason of people thus flocking to him might proceed partly from this:
there was one Brown,
who upon his deathbed spoke by way of prophecy many
notable things concerning George Fox,
and among the rest,`' that he should be made instrumental
by the Lord to the conversion of people.`'
And of others that then were something in show, he said,
'`That they should come to nothing; which was fulfilled in time,
though this man did not live to see it, for he was not raised from his sickness.
But after he was buried, George Fox fell into such a condition,
that he not only looked like a dead body,
but unto many that came to see him he seemed as if he had been really dead;
and many visited him for about fourteen days time,
who wondered to see him so much altered in countenance.

At length his sorrows and troubles began to wear off, and tears of joy dropped from him,
so that he could have wept night and day with tears of joy, in brokenness of heart.
And to give an account of his condition to those that are able to comprehend it,
I will use his own words: '`I saw,`' says he, '`into that which was without end,
and things which cannot be uttered;
and of the greatness and infiniteness of the love of God,
which cannot be expressed by words:
for I had been brought through the very ocean of darkness and death,
and through and over the power of Satan, by the eternal glorious power of Christ:
even through that darkness was I brought which covered all the world,
and which chained down all, and shut up all in the death.
And the same eternal power of God, which brought me through those things,
was that which afterwards shook the nation, priests, professors, and people.
Then could I say, I had been in spiritual Babylon, Sodom, Egypt, and the grave;
but by the Eternal power of God I was come out of it, and was brought over it,
and the power of it, into the power of Christ.
And I saw the harvest white, and the seed of God lying thick in the ground,
as ever did wheat, that was sown outwardly, and none to gather it;
and for this I mourned with tears.`'
Thus far George Fox`'s own words, of whom now a report went abroad,
that he was a young man that had a discerning spirit: whereupon many professors, priests,
and people came to him, and his ministry increased;
for he having received great openings, spoke to them of the things of God,
and was heard with attention by many, who going away, spread the fame thereof.
Then came the tempter, and set upon him again,
charging him that he had sinned against the Holy Ghost; but he could not tell in what;
and then Paul`'s condition came before him,
how after he had been taken up into the third heavens,
and seen things not lawful to be uttered, a messenger of Satan was sent to buffet him,
that he might not exalt himself.
Thus George Fox, by the assistance of the Lord, got also over that temptation.

Now the 47th year of that century drew to an end,
and state affairs in England grew more and more clouded and intricate;
for the King not thinking himself any longer safe at Hampton Court,
where he had been brought from the army; he withdrew to the Isle of Wight,
while the Parliament still insisted on the abrogation of Episcopacy,
and would be master of the military forces: which the King not being willing to yield to,
was now kept in closer custody, and no more regarded as a Sovereign,
to whom obedience was due from the Parliament.

Under these intestine troubles,
the minds of many people came to be fitted to receive a nearer way and doctrine of godliness,
and it was in the year 1648, that several persons, seeking the Lord,
were become fellow-believers, and entered into society with George Fox;
insomuch that they began to have great meetings in Nottinghamshire,
which were visited by many.
About that time there was a meeting of priests and professors at a justice`'s house,
and George Fox went among them and heard them discourse
concerning what the Apostle Paul said.
He had not known sin, but by the law, which said, you shall not lust.
And since they held that to be spoken of the outward law, George Fox told them,
Paul spoke that after he was convinced; for he had the outward law before,
and was bred up in it, when he was in the lust of persecution:
but it was the law of God in his mind, which he served,
and which the law in his members warred against.
This saying found so much entrance, that those of the priests and professors,
that were most moderate, yielded, and consented that it was not the outward law,
but the inward, that showed the inward lust, which the Apostle spoke of.
After this, he went again to Mansfield,
where was a great meeting of professors and other people; and being among them,
and moved to pray, such an extraordinary power appeared,
and seized on the hearts of some in so eminent a manner,
that even the house seemed to be shaken: and after prayer,
some of the auditory began to say, '`That this resembled that in the days of the Apostles,
when on the day of Pentecost, the house where they were met was shaken.`'

Not long after this, there was another great meeting of professors,
where G. Fox came also, who hearing them discourse about the blood of Christ,
he cried out among them: '`Do you not see the blood of Christ?
You must see it in your hearts, to sprinkle your hearts and consciences from dead works,
to serve the living God.`'
This was a doctrine which startled these professors,
who would have the blood of Christ only without them,
not thinking that it was to be felt inwardly.
But a certain captain, whose name was Amos Stoddard, was so reached,
that seeing how they endeavored to bear G. Fox down with many words, he said,
'`Let the youth speak,
hear the youth speak;`' and coming afterwards to be more acquainted with G. Fox,
he had an opportunity to be further instructed in the way of godliness,
of which he came to be a faithful follower.

Some time after, G. Fox returned to Leicestershire, his own country,
where several tender people came to be convinced by his preaching.
Passing from there into Warwickshire, he met with a great company of professors,
who being come together in the field, were praying and expounding the Scriptures.
Here the Bible was given him, which he opened on the 5th of Matthew,
where Christ expounded some parts of the law;
from which G. Fox took occasion to open to them the inward and outward state of man:
and that which he held forth getting some ground,
they fell into a fierce contention among themselves, and so parted.

Then he heard of a great meeting to be at Leicester, for a dispute,
wherein those of several persuasions, as Presbyterians, Independents, Baptists,
and Episcopalians, were said to be all concerned.
This meeting being appointed to be in the steeple house, he went there,
where abundance of people were met, some of those that spoke being in pews,
and the priest in the pulpit.
At last, after several reasonings, a woman started a question, and asked,
'`What that birth was the Apostle Peter spoke of,
"`a being born again of incorruptible seed, by the word of God,
that lives and abides forever.`"
The priest, instead of answering this question, said to her,
'`I permit not a woman to speak in the church;`' though
he had before given liberty for any to speak.
This kindled G. Fox`'s zeal, so that he stepped up, and asked the priest.
Do you call this place, (the steeple-house,) a church?
Or do you call this mixed multitude a church?
But the priest not answering to this, asked, what a church was: and G. Fox told him.
The church was the pillar and ground of truth, made up of living stones, living members,
a spiritual household, which Christ was the head of:
but he was not the head of a mixed multitude, or of an old house made up of lime, stones,
and wood.
This caused such a stir, that the priest came down out of his pulpit,
and others out of their pews, whereby the dispute was marred.
But G. Fox went to a great inn,
and there disputed with the priests and professors of all sorts,
maintaining what he had said, till they all went away;
yet several were convinced that day, and among these,
the woman who asked the question aforesaid.

After this, G. Fox returned again into Nottinghamshire, and went into the vale of Beavor,
where he preached repentance to the people: and he staying some weeks there,
and passing through several towns, many were convinced of the truth of his doctrine.
About that time, as he was sitting by the fire one morning, a cloud came over him,
and a temptation beset him, and he sitting still, it was suggested.
All things come by nature; and he was in a manner quite clouded:
but he continuing to sit still, the people of the house perceived nothing:
at length a living hope arose in him, and also a voice, that said.
"`There is a living God,
who made all things;`" and immediately the cloud and temptation vanished away,
whereby his heart was made glad, and he praised the Lord.

Not long after, he met with some people that had a mischievous notion,
that there was no God, but that all things came by nature.
But he, reasoning with them, so confounded them, that some were made to confess,
that there was a living God.
Then he saw that it was good for him to have been tried under such a cloud.
Now in those parts he had great meetings, and a divine power working in that country,
and thereabouts, many were gathered.
Then coming into Derbyshire, there was a great meeting of his friends at Eaton,
where many of them began to preach the doctrine of truth,
who afterwards were moved to declare the truth in other places also.

George Fox coming about this time to Mansfield, heard,
that in a town about eight miles off, there was to be a sitting of justices,
to deliberate about hiring of servants; and he, feeling a constraint upon his mind,
went there, and exhorted them, not to oppress the servants in their wages,
but to do that which was right and just to them; and the servants,
many of whom were come there, he admonished, to do their duty, and serve honestly;
and they all received his exhortation kindly.
He felt himself also moved, to go to several courts and steeple-houses at Mansfield,
and other places, warning them to leave off oppression, deceit, and other evils.
And having heard at Mansfield of one in the country, who was a common drunkard,
and a noted whore-master, and a poet also, he went to him,
and reproved him in an awful manner for his evil courses; which so struck him,
that coming afterwards to G. Fox, he told him,
that he was so smitten when he spoke to him, that he had scarce any strength left in him.
And this man was so thoroughly convinced,
that he turned from his wickedness and became an honest, sober man,
to the astonishment of those that knew him before.
Thus the work of G. Fox`'s ministry went forward,
and many were thereby turned from darkness to light; and many meetings of his friends,
who were much increased in number since the year 1646,
were now set up in several places.

George Fox was now come up to quite another state than formerly he had lived in;
for he knew not only a renewing of the heart, and a restoration of the mind,
but the virtues of the creatures were also opened to him;
so that he began to deliberate whether he should practice medicine for the good of mankind.
But God had another service for him; and it was showed him,
that he was to enter into a spiritual labor;
and also that those who continued faithful to the Lord,
might attain to a state in which the sinful inclination was subdued.
Moreover, the three great professions in the world, namely, medicine, theology, and law,
were opened to him, whereby he saw that the physicians lacking the wisdom of God,
by which the creatures were made, knew not their virtues:
that the lawyers generally were void of equity and justice, and so out of the law of God,
which went over the first transgression, and over all sin,
and answered the Spirit of God that was oppressed in man: and that the priests,
for the most part, were out of the true faith, which Christ is the author of,
and which purifies the heart, and brings man to have access to God.
So that these physicians, lawyers, and priests, who pretended to cure the body,
to establish the property of the people, and to cure the soul,
were all without the true knowledge and wisdom they ought to possess.
Yet he felt there was a divine power, by which all might be reformed,
if they would receive, and bow unto it.
And he saw also, that though the priests did err,
yet they were not the greatest deceivers spoken of in the Scriptures;
but that these great deceivers were such, who, as Cain, had heard the voice of God,
and who, as Korah, Dathan, and Abiram, and their company, were come out of Egypt,
and through the Red Sea, and had praised God on the banks of the sea shore;
and who being come as far as Balaam, could speak the word of the Lord,
as having heard his voice, and known his Spirit,
so that they could see the star of Jacob, and the goodliness of Israel`'s tents,
which no enchantment could prevail against:
these that could speak so much of their divine experience,
and yet turned from the Spirit of God, and went into the gainsaying,
these he saw would be the great deceivers, far beyond the priests.
He saw also that people generally did read the Scriptures,
without having a true sense of them; for some cried out much against Cain, Ishmael, Esau,
Korah, Balaam, Judas,
etc. not regarding that the nature of these was yet alive in themselves;
whereby they always applied to others that nature, in which they themselves lived.

The Lord had also opened to him now,
that every man was enlightened by the divine light of Christ;
and he saw that they that believed in it, came out of condemnation,
and became the children of the light: but they that hated it, and did not believe in it,
were condemned by it, though they made a profession of Christ.
All this he saw in the pure openings of the light.
He also saw that God had afforded a measure of his Spirit to all men,
and that thereby they could truly come to serve the Lord, and to worship him;
and that his grace, which brings salvation, and had appeared to all men,
was able to bring them into the favor of God.

And on a certain time, as he was walking in the fields,
he understood that it was said to him: '`Your name is written in the Lamb`'s Book of Life,
which was before the foundation of the world.`'
This he took to be the voice of the Lord, and believed it to be true.
Then he felt himself powerfully moved to go abroad into the world,
which was like a briery thorny wilderness;
and he found then that the world swelled against him,
and made a noise like the great raging waves of the sea:
for when he came to proclaim the day of the Lord among the priests, professors,
magistrates, and people, they were all like a disturbed sea.
Now he was sent to turn people from darkness to the light,
that they might receive Christ Jesus; for he saw,
that to as many as should receive him in his light,
he would give power to become the sons of God:
and that therefore he was to turn people to the grace of God,
and to the truth in the heart; and that by this grace they might be taught,
and thereby obtain salvation; since Christ had died for all men,
and was a propitiation for all, having enlightened all men with his divine saving light,
and the manifestation of the Spirit of God being given to every man to profit withal.
He now being sent thus to preach the everlasting gospel, did it with gladness,
and endeavored to bring people off from their own ways, to Christ,
the new and living way; and from their churches, which men had made and gathered,
to the church in God, the general assembly written in heaven,
which Christ is the head of; and from the world`'s teacher`'s, made by men,
to learn of Christ, who is the way, the truth, and the life; and of whom the Father said,
"`This is my beloved Son, hear you him;`" and off from the world`'s worship,
to the Spirit of God in the inward parts, that in it they might worship the Father,
who seeks such to worship him.

Now he found also that the Lord forbade him to put off his hat to any man, high or low;
and he was required to _Thee_ and _Thou_ every man and woman without distinction,^
footnote:[Editor`'s Note - Most modern English speakers are unaware that the words "`you`"
and "`your`" were originally plural pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600`'s,
it became fashionable (as a means of showing honor or flattery) to use
the plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Early Friends stuck to what was then considered "`plain
language`" (using thee and thou to every single person,
and you and your to two or more),
rather than showing preferment by addressing certain individuals in the plural.]
and not to bid people "`Good Morrow`" or "`Good Evening`"
neither might he bow or scrape with his leg to any one.
This was such an unusual thing with people,
that it made many of all persuasions and professions rage against him;
but by the assistance of the Lord, he was carried over all,
and many came to be his fellow-believers, and turned to God in a little time;
although it is almost unspeakable what rage and fury arose, what blows, pinchings,
beatings and imprisonments they underwent,
besides the danger they were sometimes in of losing their lives for these matters:
so indiscreet is man in his natural state.
For here it did not avail to say.
That the hat-honor was an honor from below, which the Lord would lay in the dust,
and stain it; that it was an honor which the proud looked for,
without seeking the honor which came from God alone;
that it was an honor invented by men in the fall,
who therefore were offended if it were not given them;
though they would be looked upon as church members, and good Christians;
whereas Christ himself said, "`How can you believe, who receive honor of one another,
and seek not the honor that comes from God only?`"
That it was an honor, which in relation to the outward ceremony, that is,
the putting off the hat, was the same which was given to God;
so that in the outward sign of reverence, no distinction,
or difference was made between the Creator and the creature; no,
that the saying of you to a single person, went yet a degree further;
for not only kings and princes formerly among the Heathens and Jews,
had not been offended at it when they were Thee`'d and Thou`'d,
but experience showed that this still was the language wherewith God was daily spoken to,
both in religious assemblies, and without.
But all these reasons found little entrance with priests, magistrates, and others:
bitter revilings, ill usage, and shameful abuses,
were now become the lot and share of those who for conscience-sake,
could no longer follow the ordinary custom:
for though it was pretended that "`the putting off of the hat was but a small thing,
which none ought to scruple; yet it was a wonderful thing,
to see what great disturbance this pretended small
matter caused among people of all sorts;
so that even such that would be looked upon as those that practiced humility and meekness,
soon showed what spirit they were of, when this worldly honor was denied them.
But all this served to strengthen the fellow-believers
more and more in their plain carriage,
and made them live up faithfully to the convincement of their conscience,
without respect of persons.

In the meanwhile the troubles of the land continued.
We left the King in the foregoing year in the Isle of Wight, in effect unkinged.
Some time after the Duke of York, second son to the King,
being then past fourteen years of age, fled to Holland, disguised in woman`'s apparel;
and his eldest brother the Prince of Wales, who two years before fled to France,
came now to Helvoet-Sluys in Holland, and went from there with some English men of war,
whose commanders were for the King, to the Downs in England,
with intention to take the ships coming from London.
He also published, by the spreading of a declaration, that he came to release his father.
Now there was also a negotiation on foot between the King and the Parliament,
and there seemed some hopes of an accommodation; had not the army,
the chief instrument in breaking down the royal power, opposed it,
by calling for justice against all those who had wronged the country, none excepted.
This broke off the treaty, several suspected members were turned out of the Parliament,
and the King was carried to Windsor about the time called Christmas;
and it was resolved henceforth to send no more deputations to him,
nor receive any from him, who now was no more named King, but only Charles Stuart:
a very strange turn of mundane affairs,
and a mighty evidence of the fluctuating inconstancy thereof.
But things made no stand here, for it was concluded to bring him to a trial;
and the Parliament appointed General Thomas Fairfax, and Oliver Cromwell,
Lieutenant General, with more than a hundred other persons, to be his judges.
These being formed into a court of justice,
the King was conducted from Windsor to St. James`'s,
and from there brought before them in Westminster Hall,
where he was arraigned as guilty of high treason,
for having levied war against the Parliament and people of England.
But he not acknowledging that court to be lawful, nor acknowledging their authority,
said '`I am not entrusted by the people,
they are mine by inheritance:`' and being unwilling to answer to the charge,
he was on the 27th of the month, called January, sentenced to death, as a tyrant,
traitor, murderer, and a public enemy to the Commonwealth.
But before this sentence was pronounced,
'`the King`' desired that he might be permitted to make a proposition
to both Houses of Parliament in the painted Chamber,
designing as was since said to propose his own resignation, and the admission of his son,
the Prince of Wales, to the throne.
But this request was denied by the Court.
Now though the said Prince of Wales, considering his father`'s danger,
had applied himself to the States-General of the United Provinces at the Hague for assistance;
and that these sent two Ambassadors to the Parliament,
who coming to London on the same day the fatal sentence was pronounced,
could not obtain admission till next day to the Speakers of both Houses,
and were afterwards with Fairfax and Cromwell, and other commanders;
and one of them had also his audience in the Parliament
to intercede with them for the King`'s life;
yet all proved in vain: for on the 30th of the aforesaid month,
the King was brought on a scaffold erected before the banqueting house,
and his head severed from his body.
The same day the Parliament ordered a declaration to be published,
whereby it was declared treason to endeavor to promote the Prince of Wales,
Charles Stuart, to be King of England,
or any other single person to be the chief governor thereof.
And then, after having abolished the House of Peers,
they assumed to themselves the chief government of the nation, with the title of,
The Parliament of the Commonwealth of England.

The news of the King`'s death was no sooner come into Scotland, but Charles,
Prince of Wales, was proclaimed, at Edinburgh, King of Great Britain, provided he should,
before assuming the royal authority,
give satisfaction about some matters concerning religion.
And though this displeased the English,
yet the Scots asserted that they might as well do so, as the English,
who had done the same at the death of the late King`'s father, in the year 1625.

Leaving state affairs, let us return to G. Fox, who in the year 1649,
was much exercised to declare openly against all sorts of sins:
and therefore he went not only to the courts, crying for justice,
and exhorting the judges and justices to do justice,
but he warned also those that kept public houses for entertainment,
not to let people have more drink than what would do them good.
He also testified against wakes, may-games, plays, and shows,
by which people were led into vanity, and drawn off from the fear of God;
the days that were set forth for holidays,
being usually the times wherein God was most dishonored.
When he came into markets, he also declared against deceitful merchandising,
and warned all to deal justly, and to speak the truth;
and he testified against the mountebanks playing tricks on their stages:
and when occasion offered,
he warned schoolmasters and schoolmistresses to teach
their children to mind the fear of the Lord;
saying, that they themselves ought to be examples and patterns of virtue to them.
But very burdensome it was to him,
when he heard the bell ring to call people together to the steeple-house;
for it seemed to him just like a market bell, to gather the people,
that the priest might set forth his ware to sale.

Going once on a First-day of the week, in the morning,
with some of his friends to Nottingham, to have a meeting there;
and having seen from the top of a hill the great steeple-house of the town,
he felt it required of him to cry against that idol temple, and the worshippers therein:
yet he said nothing of this to those that were with him,
but went on with them to the meeting, where after some stay he left them,
and went away to the steeple-house,
where the priest took for his text these words of the Apostle, 2 Pet. 1:19.
"`We have also a most sure word of prophecy,
whereunto you do well that you take heed, as unto a light that shines in a dark place,
until the day dawn, and the day-star arise in your hearts.`"
And he told the people that this was the Scripture,
by which they were to try all doctrines, religions, and opinions.
G+++.+++ Fox hearing this, felt such mighty power, and godly zeal working in him,
that he was made to cry out, "`O no, it is not the Scripture, but it is the Holy Spirit,
by which the holy men of God gave forth the Scriptures, whereby opinions, religions,
and judgments are to be tried.
That was it which led into all truth, and gave the knowledge thereof.
For the Jews had the Scriptures, and yet resisted the Holy Ghost, and rejected Christ,
the bright morning star, and persecuted him and his Apostles;
though they took upon them to try their doctrine by the Scriptures;
but they erred in judgment, and did not try them aright,
because they did it without the Holy Ghost.`"
Thus speaking, the officers came and took him away,
and put him into a nasty stinking prison.
At night he was brought before the mayor, aldermen, and sheriffs of the town;
and they examining him, he told them,
that the Lord had moved him to come there into the steeple-house:
and though the mayor at first appeared peevish and fretful, yet he was allayed: however,
after some discourse, G. Fox was sent back to prison.
But some time after, the head sheriff John Reckless sent for him to his house,
and when G. Fox came in, the sheriff`'s wife met him in the hall,
and taking him by the hand said,
'`Salvation is come to our house;`' for his speech in the steeple-house had so amazed many,
that they could not get the sound of it out of their ears;
and not only this woman was wrought upon, but also her husband, children,
and servants were much changed by the power of the Lord.

George Fox thus coming to lodge at this sheriff`'s house, had great meetings there,
and some persons of quality in the world came to them;
and they were reached very eminently in their minds by an invisible power.
Reckless being of this number, sent for the other sheriff,
and for a woman they traded with; and he told her in the presence of the other sheriff,
that they had wronged her in their dealings with her,
and that therefore they ought to make her restitution;
to which Reckless exhorted the other sheriff, being himself made sensible,
that this was an indispensable duty: for a mighty change was now wrought in him,
and his understanding came to be opened; so that on the next market day,
as he was walking with G. Fox in the chamber, in his slippers, he said,
'`I must go into the market and preach repentance to the people;`'
and accordingly he went in his slippers into the market,
and into several streets, preaching repentance.
Some others also in the town were moved to speak to the mayor and magistrates,
and to the people, exhorting them to repent.
But this the magistrates could not endure; and to vent their passion on G. Fox,
they sent for him from the sheriff`'s house, and committed him to the common prison,
where he was kept till the court session came on,
and then he was to have been brought before the judge,
but that the sheriff`'s man being somewhat long; in fetching him,
the judge was risen before G. Fox came to the session-house; however,
the judge was a little displeased, having said, '`He would have admonished the youth,
(meaning G. Fox,) if he had been brought before him.`'
So he was carried back again to prison.
In the meanwhile such a wonderful power broke forth among his friends,
that many were astonished at it, so that even several of the priests were made tender,
and some did confess to the power of the Lord.
Now though the people began to be very rude,
yet the governor of the castle was so moderate,
that he sent down soldiers to disperse them.
G+++.+++ Fox having been kept prisoner a pretty long time, was at length set at liberty,
and then travelled as before in the work of the Lord.

Coming to Mansfield-Woodhouse, he found there a distracted woman under a doctor`'s hand,
being bound, and with her hair loose; and the doctor being about to let her blood,
could get no blood from her which made G. Fox desire to unbind her;
and after this was done, he spoke to her, and bade her in the name of the Lord,
to be quiet and still.
This proved of such effect that she became still; and her mind coming to be settled,
she mended, and afterwards received the doctrine of truth,
and continued in it to her death.

While G. Fox was in this place, he was moved to go to the steeple-house,
and declare there the truth to the priest and the people; which doing,
the people fell upon him, and struck him down, almost smothering him,
for he was cruelly beaten and bruised with their hands, bibles, and sticks.
Then they hauled him out, though hardly able to stand, and put him in the stocks,
where he sat some hours: and they brought horsewhips, threatening to whip him.
After some time they had him before the magistrates, at a knight`'s house;
who seeing how ill he had been used, set him at liberty, after much threatening.
But the rude multitude stoned him out of town; and though he was scarce able to go,
yet with much ado he got about a mile from the town,
where he met with some people that gave him something to comfort him,
because he was inwardly bruised.
But it pleased the Lord soon to heal him again;
and some people were that day convinced of the truth,
which had been declared by him in the steeple-house, at which he rejoiced.

Out of Nottinghamshire he went to Leicestershire, accompanied by several of his friends;
and coming to Barrow, discoursed with some Baptists; and one of them saying.
What was not of faith was sin; he asked.
What faith was, and how it was wrought in man: but they turning off from that,
spoke of their water-baptism; which gave occasion to G. Fox, and his friends,
to ask who baptized John the Baptist, and who baptized Peter, John,
and the rest of the Apostles.
But they were silent at those questions.
After some other discourse they parted.
On the next First-day of the week, G. Fox, and those that were with him,
came to Bagworth, and went to a steeple-house; and after the priest had done,
they had some service there by speaking to the people.

Passing from there, he heard of a people that were in prison in Coventry for religion;
and as he was walking towards the jail, the word of the Lord,
(as he relates,) came to him, saying, '`My love was always to you,
and you are in my love.`'
By this he was overcome with a sense of the love of God,
and much strengthened in his inward man.
But coming into the jail, a great power of darkness struck at him;
for instead of meeting such as were imprisoned for religion,
he found them to be blasphemers, who were come to that degree,
that they said they were gods;
and this their wicked opinion they endeavored to maintain by Scripture,
misapplying what was said to the Apostle Peter, when the sheet was let down to him,
that is,
'`What was sanctified he should not call common or
unclean:`' and the words of the Apostle Paul,
concerning '`God`'s reconciling all things to himself, things in heaven,
and things on earth.`'
G+++.+++ Fox was greatly grieved at this profaneness,
told them that these Scriptures were nothing to their purpose;
and seeing they said they were gods, he asked them,
if they knew whether it would rain tomorrow; and they saying, they could not tell;
he told them God could tell.
He asked them also, if they thought they should always be in that condition,
or should change: and they answering, that they could not tell; G. Fox told them,
that God could tell it, and that he did not change.
This confounded them and brought them down for that time:
so after having reproved them for their blasphemous expressions he went away.
Not long after this, one of these ranters, whose name was John Salmon,
gave forth a book of recantation, upon which they were set at liberty.
From Coventry, G. Fox went to Atherstone, where, going into the chapel,
he declared to the priests and the people, that God was come to teach his people himself,
and to bring them off from all their man-made teachers, to hear his Son.
And though some few raged, yet they were generally pretty quiet, and some were convinced.

After this service, he went to Market-Bosworth,
and coming into the public place of worship, he found Nathaniel Stevens preaching,
who as has been said already, was priest of the town where G. Fox was born;
here G. Fox taking occasion to speak, Stevens told the people, he was mad,
and that they should not hear him;
though he had said before to one Colonel Purfoy concerning him,
that there was never such a plant bred in England.
The people now being stirred up by this priest, fell upon G. Fox and his friends,
and stoned them out of the town.
Nevertheless this wrought on the minds of some others, so that they were made loving.

G+++.+++ Fox now traveling on, came to Twy-Cross, where he spoke to the exciseman,
and warned them to take heed of oppressing the poor.
There being in that town a great man, that had long lain sick,
and was given over by the physicians, he went to visit him in his chamber;
and after having spoken some words to him, he was moved to pray by his bedside;
and the Lord was entreated, so that the sick man was restored to health.
But G. Fox being come down, and speaking to some that were in a room there,
a servant came with a naked rapier in his hand, and threatened to stab him;
but he looking steadfastly on the man, said, '`Alack for you, poor creature!
What will you do with your carnal weapon!
It is no more to me than a straw.`'
He being stopped thus, went away in a rage,
and his master hearing of it turned him out of his service,
and was afterwards very loving to Friends; and when G. Fox came to that town again,
both he and his wife came to see him.

After this he went into Derbyshire,
where his fellow-believers increased in godly strength; and coming to Chesterfield,
he found one Bzitland to be priest there,
who having been partly convinced of the doctrine of truth,
had spoken much in behalf of it, and saw beyond the common sort of priests.
But when the priest of that town died, he got the parsonage.
G+++.+++ Fox now speaking to him and the people,
endeavored to bring them off from man`'s teaching, unto God`'s teaching;
and though the priest was not able to gainsay, yet they had him before the mayor,
and threatened, to send him to the house of correction:
but when it was late in the night the officers and the watchmen led him out of the town.

Concerning state affairs it has been said already,
that Charles II. had been proclaimed king by the Scots; but he being still in Holland,
they sent to him there, that he would subscribe the Covenant,
and so abrogate Episcopacy in Scotland:
it was also desired that he would put some lords from him.
But those that were sent, received only an answer from the young king in general terms,
which made them return home again, where we will leave them,
to see in the meanwhile how it went with G. Fox, who had been sent away,
as has been said, from Chesterfield, came to Derby in the year 1650,
and lay at a doctor`'s house, whose wife was convinced of the truth he preached.
Now it happened, as he was walking there in his chamber, he heard the bell ring,
and asked the woman of the house what the bell rung for.
She told him, there had been a great lecture that day;
so that many of the officers of the army, and priests and preachers were to be there,
as also a colonel that was a preacher.
Then he felt himself moved to go to that congregation; and when the service was done,
he spoke to them what he believed the Lord required of him; and they were pretty quiet.
But there came an officer, who took him by the hand, and said, that he,
and the other two that were with him, must go before the magistrates.
Coming then about the first hour in the afternoon before them, they asked him,
why he came there; to which having answered, that God had moved him to it;
he further said, that God did not dwell in temples made with hands;
and that all their preaching, baptism, and sacrifices, would never sanctify them;
but that they ought to look unto Christ in them, and not unto men;
because it is Christ that Sanctifies.
They then running into many words, he told them,
they were not to dispute of God and Christ, but to obey him.
But this doctrine did so displease them, that they often put him in and out of the room,
and sometimes told them scoffingly, that he was taken up in raptures.
At length they asked him, whether he was sanctified; and he answering, yes;
they then asked, if he had no sin; to which he said,
"`Christ my Savior has taken away my sin, and in him there is no sin.`"
Then he and his friends were asked, how they knew that Christ did abide in them;
G+++.+++ Fox said, "`By his Spirit, that he has given us.`"
Then they temptingly asked, if any of them was Christ; but he answered, "`No,
we are nothing, Christ is all.`"
At length they also asked, if a man steal, is it no sin;
to which he answered with the words of scripture, "`All unrighteousness is sin.`"
So when they had wearied themselves in examining him,
they committed him and another man to the house of correction in Derby, for six months,
as blasphemers, as appears by the following court order.

[.embedded-content-document.legal]
--

[.letter-heading]
To the Master of the House of Correction in Derby

[.salutation]
Greetings,

We have sent you herewithal the bodies of George Fox,
late of Mansfield in the county of Nottingham; and John Fretwell,
late of Staniesby in the county of Derby, husbandman, brought before us this present day,
and charged with the avowed uttering and broaching of several
blasphemous opinions contrary to a late act of Parliament,
which, upon their examination before us, they have confessed.
These are therefore to require you, forthwith upon sight hereof, to receive them,
the said George Fox and John Fretwell into your custody,
and them therein safely to keep during the space of six months,
without bail or mainprise,
or until they shall find sufficient security to be of good behavior,
or be there delivered by order from ourselves.
Hereof you are not to fail.
Given under our hands and seals this 30th day of October, 1650,

[.signed-section-signature]
Ger.
Bennet, Nath.
Barton.

--

George Fox being thus, as has been said, locked up,
the priests bestirred themselves in their pulpits to preach up sin for term of life;
and they endeavored to persuade people that it was an erroneous doctrine,
to assert a possibility of being freed from sin in this life,
as was held forth by the Quakers;
for this began now to be the name whereby G. Fox`'s fellow-believers were called,
in a reviling way:
and since that denomination has continued to them from that time downward,
we canned therefore pass by the first rise of it with silence.
Until this time those who professed the light of Christ as shining in man`'s heart,
and reproving for sin, were not improperly called Professors of the Light,
or Children of the Light: but Gervas Bennet,
one of the justices of the peace who signed the aforesaid court order,
and an Independent, hearing that G. Fox bade him, and those about him,
tremble at the word of the Lord! took hold of this weighty saying with such an airy mind,
that from there he took occasion to call him, and his friends, scornfully, QUAKERS.
This new and unusual denomination was taken up so eagerly,
and spread so among the people,
that not only the priests there from that time gave
no other name to the Professors of the Light,
but sounded it so gladly abroad, that it soon run over all England;
and making no stand there, it quickly reached to the neighboring countries,
and adjacent kingdoms, insomuch, that the said Professors of the Light,
for distinction sake from other religious societies,
have been called everywhere by that English name,
which sounding very odd in the ears of some foreign nations,
has also given occasion to many silly stories.

Now because in those early times, among the many adherents of this persuasion,
there were some that having been people of a rude and dissolute life,
came so to be pricked to the heart, that they grew true penitents,
with real sorrow for their former transgressions;
it happened that they at meetings did not only burst out into tears,
but also were affected with such a singular commotion of the mind,
that some shakings of their bodies were perceived;
some people naturally being more affected with passions of the mind than others;
for even anger does transport some men so violently, that it makes them tremble;
whereas others will quake with fear: and what wonder then,
if some being struck with the terrors of God did tremble.
But this being seen by envious men, they took occasion from there to tell,
that these Professors of the Light performed their worship with shaking;
yet they themselves never asserted that trembling
of the body was an essential part of their religion,
but have occasionally said the contrary;
though they did not deny themselves to be such as tremble before God;
and they also did not hesitate to say that all people ought to do so;
however thereby not enjoining a bodily shaking.

We have seen just now,
how one Fretwell was committed with G. Fox to the house of correction;
but he not standing faithful in his testimony, obtained, by intercession of the jailer,
leave of the justice to go see his mother, and so got his liberty:
and then a report was spread, that he had said,
that G. Fox had bewitched and deceived him.

G+++.+++ Fox was now become the object of many people`'s hatred; magistrates,
priests and professors were all in a rage against him; and the jailer,
to find something where with to ensnare him,
would sometimes ask him such silly questions, as, whether the door were latched or not;
thinking thereby to draw some sudden unadvised answer from him,
whereby he might charge sin upon him: but he was kept so watchful and circumspect,
that they could get no advantage of him.
Not long after his-commitment,
he was moved to write both to the priests and magistrates of Derby.

Now since G. Croese in the beginning of history,
represents G. Fox as one altogether unfit, not only to write legibly,
but also to express his mind clearly in writing,
and that therefore he always was obliged to employ
others that could set down his meaning intelligibly,
it will not be beside the purpose to say,
that this is more than any will be able to prove.
For though it cannot be denied that he was no elegant writer, nor good speller,
yet it is true, that his characters being tolerable, his writing was legible,
and the matter he treated of was intelligible,
though his style was not like that of a skillful linguist.
And albeit he employed others, because himself was no quick writer,
yet generally they were young lads,
who as they dared not have attempted to alter his words and phrases,
so they would not have been skillful enough to refine his style.
This I do not write from hearsay; but have seen it at sundry times.
And how true it is what the same author says, that mostly all G. Fox did write,
was scarce any thing besides a rough collection of several scripture places,
may be seen by the sequel of this history, wherein will be found many of his writings.
The first of his letters I meet with is the following,
which he wrote to the priests of Derby, from the house of correction,
where certainly he had not the convenience of a writing clerk.

[.embedded-content-document.letter]
--

O Friends, I was sent unto you to tell you, that if you had received the gospel freely,
you would minister it freely without money or price:
but you make a trade and sale of what the prophets and apostles have spoken;
and so you corrupt the truth.
And you are the men that lead silly women captive, who are ever learning,
and never able to come to the knowledge of the truth: you have a form of godliness;
but you deny the power.
Now as Jannes and Jambres withstood Moses, so do you resist the truth;
being men of corrupt minds, reprobate concerning the faith.
But you shall proceed no further; for your folly shall be made manifest to all men,
as theirs was.
Moreover the Lord sent me to tell you, that he does look for fruits.
You asked me, if the Scripture was my rule; but it is not your rule,
to rule your lives by; but to talk of in words.
You are the men that live in pleasures, pride, and wantonness,
in fullness of bread and abundance of idleness: see if this be not the sin of Sodom.
Lot received the angels: but Sodom was envious.
You show forth the vain nature: you stand in the steps of them that crucified my Savior,
and mocked him: you are their children; you show forth their fruit.
They had the chief place in the assemblies; and so have you:
they loved to be called Rabbi; and so do you.

[.signed-section-signature]
G+++.+++ Fox

--

That which he wrote to the magistrates who committed him to prison, was to this effect:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

I am forced, in tender love unto your souls, to write unto you,
and to beseech you to consider what you do, and what the commands of God call for.
He does require justice and mercy to break every yoke, and to let the oppressed go free.
But who calls for justice or loves mercy, or contends for the truth?
Is not judgment turned backward, and does not justice stand afar off?
Is not truth silenced in the streets, or can equity enter?
And do not they that depart from evil, make themselves a prey?
Oh! consider what you do in time, and take heed whom you do imprison:
for the magistrate is set for the punishment of evil doers,
and for the praise of them that do well.
Now, I entreat you, in time, take heed what you do, for surely the Lord will come,
and will make manifest both the builders and the work: and if it be of man, it will fail;
but if it be of God, nothing will overthrow it.
Therefore I desire and pray, that you would take heed, and beware what you do,
lest you be found fighters against God.

[.signed-section-signature]
G+++.+++ Fox

--

George Fox having thus cleared his conscience, continued waiting in patience,
leaving the event to God.
And after some time he felt himself constrained to
write to the justices that had committed him to prison,
to lay their doings before them, that so they might come to a due consideration thereof;
one of them, (already mentioned,) was justice Bennet, the other Nathaniel Barton,
both a justice and a colonel, as also a preacher: to these he wrote as follows:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

You did speak of the good old way, which the prophet spoke of;
but the prophets cried against the abominations which you hold up.
Had you the power of God, you would not persecute the good way.
He that spoke of the good way was set in the stocks: the people cried,
'`Away with him to the stocks,`' for speaking the truth.
Ah! foolish people, which have eyes and see not, ears and hear not,
without understanding! '`Fear not me,`' says the Lord,
'`and will you not tremble at my presence?`'
O your pride and abominations are odious in the eyes of God: you,
(that are preachers,) have the chiefest place in the assemblies,
and are called of men Master; and such were and are against my Savior and Maker:
and they shut up the kingdom of heaven from men, neither go in themselves,
nor permit others.
Therefore you shall receive the greater damnation, who have their places,
and walk in their steps.
You may say, if you had been in the days of the prophets, or Christ,
you would not have persecuted them; wherefore you are witnesses against yourselves,
that you are the children of them, seeing, you now persecute the way of truth.
O consider, there is a true judge,
that will give every one of you a reward according to your works.
O mind where you are,
you that hold up the abominations which the true prophet cried against!
O come down, and sit in the dust!
The Lord is coming with power; and he will throw down everyone that is exalted,
that he alone may be exalted.

--

Having thus written to them jointly, he after some time, wrote to each of them apart.
That to justice Bennet was thus:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You that do profess God and Christ in words, see how you do follow him.
To take off burdens, and to visit them that be in prison, and show mercy,
and clothe your own flesh, and deal your bread to the hungry;
these are God`'s commandments: to relieve the fatherless,
and to visit the widows in their afflictions,
and to keep yourself unspotted of the world; this is pure religion before God.
But if you do profess Christ, and follow covetousness and greediness,
and earthly-minded-ness, you deny him in life, and deceive yourself and others,
and take him for a cloak.
Woe be to you greedy men, and rich men, weep and howl for your misery that shall come.
Take heed of covetousness, and extortion; God does forbid that.
Woe be to the man that covets an evil covetousness, that he may set his nest on high,
and cover himself with thick clay.
O do not love that which God forbids: his servant you are whom you do obey,
whether it be of sin unto death, or of obedience unto righteousness.
Think upon Lazarus and the rich man: the one fared sumptuously every day;
the other was a beggar.
See, if you be not the rich man.
Be not deceived; God is not mocked with vain words:
evil communication corrupts good manners.
Awake to righteousness and sin not.

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
And that to justice Barton was thus worded:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You that preach Christ, and the Scriptures in words, when any come to follow that,
which you have spoken of, and to have the life of the Scriptures,
then they that speak the Scriptures, but do not lead their lives according thereunto,
persecute them that do.
Mind the prophets, and Jesus Christ, and his apostles, and all the holy men of God;
what they spoke, was from the life; but they that had not the life, but the words,
persecuted and imprisoned them that lived in the life, which they had backslidden from.

[.signed-section-signature]
G+++.+++ Fox

--

Now, though the Mayor of Derby did not sign the court order,
yet having had a hand with the rest in sending G. Fox to prison,
he also wrote to him after this manner:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

You are set in place to do justice;
but in imprisoning my body you have done contrary to justice, according to your own law.
O take heed of pleasing men more than God,
for that is the way of the Scribes and Pharisees;
they sought the praise of men more than God.
Remember who said, '`I was a stranger and you took me not in; was in prison,
and you visited me not.`'
O friend, your envy is not against me, but against the power of truth.
I had no envy to you, but love.
O take heed of oppression, '`for the day of the Lord is coming,
that shall burn as an oven; and all the proud, and all that do wickedly,
shall be as stubble; and the day that comes, shall burn them up,`' says the Lord of Hosts:
'`it shall leave them neither root nor branch.`'
O friend, if the love of God were in you, you would love the truth,
and hear the truth spoken, and not imprison unjustly: the love of God bears, and suffers,
and envies no man.
If the love of God had broken your hearts, you would show mercy;
but you do show forth what rules you.
Every tree does show forth its fruit: you do show forth your fruits openly.
For drunkenness, swearing, pride, and vanity, rule among you,
from the teacher to the people.
O friend! mercy and true judgment, and justice, are cried for in your streets.
Oppression, unmercifulness, cruelty, hatred, pride, pleasures, wantonness, and fullness,
is in your streets; but the poor is not regarded.
O take heed of the woe:
woe be to the crown of pride! woe be to them that drink wine in bowls,
and the poor is ready to perish.
O remember Lazarus and the rich man: one fared deliciously every day;
and the other was a beggar.
O friend, mind these things, for they are near, and see,
whether you be not the man that is in the rich man`'s state.

--

To those of the Court at Derby, he also wrote the following exhortation.

[.embedded-content-document.letter]
--

I am moved to write unto you, to take heed of oppressing the poor in your courts,
or laying burdens upon poor people, which they cannot bear: and of false oaths,
or making them to take oaths, which they cannot perform.
The Lord says, '`I will come near to judgment,
and I will be a swift witness against the sorcerers, against the false swearers,
and against the idolaters, and against those that do oppress widows and fatherless.`'
Therefore take heed of all these things betimes.
The Lord`'s judgments are all true and righteous, and he delights in mercy: so love mercy,
dear people, and consider in time.

--

And because the ringing of bells for joy,
is a thing generally tending to stir up vanity and immorality,
he also wrote a few lines to the bell-ringers of the steeple-house, called St. Peter`'s,
in Derby.

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Take heed of pleasures, and prize your time now, while you have it;
and do not spend it in pleasures, nor earthliness.
The time may come, that you will say, you had time, when it is past:
therefore look at the love of God now, while you have time:
for it brings to loathe all vanities, and worldly pleasures.
O consider! time is precious: fear God and rejoice in him, who has made heaven and earth.

--

While G. Fox was in prison there, several of the professors came to discourse with him,
and he perceiving that they came to plead for sin and imperfection, asked them,
Whether they were believers, and had faith?
and they saying Yes, he further asked them, In whom?
to which they answering.
In Christ; he replied.
If you are true believers in Christ, you are passed from death to life;
and if passed from death, then from sin that brings death.
And if your faith be true, it will give you victory over sin and the devil,
and purify your hearts and consciences,
(for the true faith is held in a pure conscience,) it will bring you to please God,
and give you access to him again.
But such language as this they could not endure; for they said,
they could not believe that any could be free from sin on this side the grave.
To which he answered.
That then they might give over their talking concerning the Scriptures,
which were the words of holy men; while they themselves pleaded for unholiness.
At another time, another company of such professors came, and they also pleading for sin,
he asked them.
Whether they had hope?
to which they answered.
Yes, God forbid but we should have hope.
Then he asked.
What hope is it you have?
Is Christ in you, the hope of your glory?
Does it purify you, as he is pure?
But they could not abide to hear of being made pure here,
and therefore he bade them forbear talking of the Scriptures,
which were the holy men`'s words; for the holy men that wrote the Scriptures,
(said he,) pleaded for holiness in heart, life, and conduct here;
but since you plead for impurity and sin, which is of the devil,
what have you to do with the holy men`'s words?

Now the keeper of the prison, who was also a high professor,
was much enraged against G. Fox, and spoke wickedly of him.
But it pleased the Lord one day to strike him so,
that he was under great anguish of mind: and G. Fox walking in his chamber,
heard a doleful noise, and standing still to hearken, he heard him say to his wife.
Wife, I have seen the day of judgment, and I saw George there, and was afraid of him,
because I had done him so much wrong, and spoken so much against him to the ministers,
and professors, and to the justices, and in taverns and alehouses.
After this, towards the evening, the keeper came up into his chamber, and said to him,
I have been as a lion against you; but now I come like a lamb,
and like the jailer that came to Paul and Silas trembling.
And he desired that he might lie with him; to which G. Fox answered,
That he was in his power, he might do what he would.
But said the other, No, I will have your leave; and I could desire to be always with you,
but not to have you as a prisoner.
G+++.+++ Fox, unwilling to deny his desire, complied with it, and allowed him to lie with him.
Then the keeper told him all his heart, and said,
he believed what he had said of the true faith and hope, to be true:
and he wondered that the other man that was put into prison with him,
did not stand to it: for, said he,
That man was not right, but you are an honest man.
He also confessed,
that at those times when G. Fox had asked him to let him
go and speak the word of the Lord to the people,
and at his refusal had laid the weight thereof upon him,
that then he used to be under great trouble, amazed, and almost distracted for some time.
The next morning the keeper went to the justices, and told them,
that he and his house had been plagued for G. Fox`'s sake.
To which one of the justices, that is, Bennet, said,
That the plagues were on them too for keeping him.
The justices now to be rid of him, gave leave that he should have liberty to walk a mile.
But he perceiving their end, told the jailer,
if they would set down to him how far a mile was,
he might take the liberty of walking it sometimes:
for he believed they thought he would go away; and the jailer also told him afterwards,
that this was their intent.
But he signified to him, that he had no mind to get his liberty that way.
And so he remained prisoner, and was visited by the jailer`'s sister,
who was so affected with what he spoke to her, that she coming down,
told her brother they were an innocent people, that did no hurt to any, but good to all;
and she desired that he might be treated civilly.

Now, since by reason of his restraint,
he had not the opportunity of traveling about to declare the doctrine of truth, he,
to discharge himself, wrote the following paper,
and sent it forth for the opening of people`'s understandings in the way of truth,
and directing them to the true teacher in themselves.

[.embedded-content-document.paper]
--

The Lord does show unto man his thoughts, and discovers all the secret workings in man.
A man may be brought to see his evil thoughts, and running mind, and vain imaginations,
and may strive to keep them down, and to keep his mind in; but cannot overcome them,
nor keep his mind within to the Lord.
Now, in this state and condition, submit to the Spirit of the Lord that shows them,
and that will bring to wait upon the Lord; and he that has discovered them,
will destroy them.
Therefore stand in the faith of the Lord Jesus Christ,
(who is the author of the true faith,) and mind him;
for he will discover the root of lusts, and evil thoughts, and vain imaginations,
and how they are begotten, conceived, and bred; and then how they are brought forth,
and how every evil member does work.
He will discover every principle from its own nature and root.

So mind the faith of Christ, and the anointing which is in you, to be taught by it,
which will discover all workings in you: and as he teaches you, so obey and forsake;
else you will not grow up in the faith, nor in the life of Christ,
where the love of God is received.
Now love begets love, its own nature and image: and when mercy and truth do meet,
what joy there is! and mercy does triumph in judgment and love
and mercy does bear the judgment of the world in patience.
That which cannot bear the world`'s judgment, is not the love of God;
for love bears all things, and is above the world`'s judgment;
for the world`'s judgment is foolishness.
And though it be the world`'s judgment and practice, to cast all the world`'s filthiness,
that is among themselves, upon the saints; yet their judgment is false.
Now the chaste virgins follow Christ the Lamb that takes away the sins of the world:
but they that are of that spirit, which is not chaste,
will not follow Christ the Lamb in his steps; but are disobedient to him in his commands.
So the fleshly mind does mind the flesh, and talks fleshly, and its knowledge is fleshly,
and not spiritual; but savours of death, and not of the spirit of life.
Now some men have the nature of swine, wallowing in the mire:
and some men have the nature of dogs, to bite both the sheep and one another;
and some men have the nature of lions, to tear, devour, and destroy:
and some men have the nature of wolves, to tear and devour the lambs and sheep of Christ:
and some men have the nature of the serpent, (that old adversary,) to sting,
envenom and poison.
He that has an ear to hear, let him hear, and learn these things within himself.
And some men have the natures of other beasts and creatures, minding nothing,
but earthly and visible things, and feeding without the fear of God.
Some men have the nature of a horse, to prance and vapor in their strength,
and to be swift in doing evil.
And some men have the nature of tall sturdy oaks,
to flourish and spread in wisdom and strength, who are strong in evil, which must perish,
and come to the fire.
Thus the evil is but one in all, but works many ways;
and whatsoever a man`'s or woman`'s nature is addicted to, that is outward,
the evil one will fit him with that, and will please his nature and appetite,
to keep his mind in his inventions, and in the creatures, from the Creator.
O therefore let not the mind go forth from God; for if it do, it will be stained,
and venomed and corrupted: and if the mind go forth from the Lord,
it is hard to bring it in again.
Therefore take heed of the enemy, and keep in the faith of Christ.
O! therefore mind that which is eternal and invisible,
and him who is the Creator and Mover of all things; for the things that are made,
are not made of things that do appear; for the visible covers the invisible sight in you.
But as the Lord, who is invisible, does open you, by his invisible Power and Spirit,
and brings down the carnal mind in you;
so the invisible and immortal things are brought to light in you.
O therefore you that know the light,
walk in the light! for there are children of darkness that will talk of the light,
and of the truth, and not walk in it; but the children of the light love the light,
and walk in the light.
But the children of darkness walk in darkness, and hate the light;
and in them the earthly lusts, and the carnal mind choke the seed of faith,
and that brings oppression on the seed, and death over them.
O therefore mind the pure spirit of the everlasting God,
which will teach you to use the creatures in their right place;
and which judges the evil.
To you, O God, be all glory and honor,
who are Lord of all visibles and invisibles! to you be all praise,
who bring out of the deep to yourself; O powerful God,
who are worthy of all glory! for the Lord who created all,
and gives life and strength to all, is over all, and merciful to all.
So you who have made all, and are over all, to you be all glory; in you is my strength,
refreshments, and life, my joy and my gladness, my rejoicing and glorying forevermore!
So to live and walk in the Spirit of God, is joy, and peace, and life;
but the mind going forth into the creatures, or into any visible things from the Lord,
this brings death.
Now when the mind is got into the flesh, and into death, then the accuser gets within,
and the law of sin and death, that gets into the flesh;
and then the life suffers under the law of sin and death;
and then there is straitness and failings.
For then the good is shut up, and then the self-righteousness is set a-top;
and then man does work in the outward law, and he cannot justify himself by the law;
but is condemned by the light; for he cannot get out of that state,
but by abiding in the light, and resting in the mercy of God, and believing in him,
from whom all mercy does flow: for there is peace in resting in the Lord Jesus.
This is the narrow way that leads to him, the life; but few will abide in it:
therefore keep in the innocency, and be obedient to the faith in him.
And take heed of conforming to the world, and of reasoning with flesh and blood,
for that brings disobedience; and then imaginations and questionings do arise,
to draw from disobedience to the truth of Christ.
But the obedience of faith destroys imaginations, and questionings, and reasonings,
and all the temptations in the flesh, and buffetings, and lookings forth,
and fetching up things that are past.
But not keeping in the life and light,
and not crossing the corrupt will by the power of God, the evil nature grows up in man:
and then burdens will come, and man will be stained with that nature.
But Esau`'s mountain shall be laid waste, and become a wilderness, where the dragons lie:
but Jacob, the second birth, shall be fruitful, and shall arise; for Esau is hated,
and must not be lord; but Jacob, the second birth, which is perfect and plain,
shall be lord: for he is beloved of God.

[.signed-section-signature]
G+++.+++ Fox

--

About the same time he wrote to his friends the following paper:

[.embedded-content-document.paper]
--

The Lord is King over all the earth! therefore all people,
praise and glorify your King in the true obedience, in the uprightness,
and in the beauty of holiness.
O consider, in the true obedience the Lord is known,
and an understanding from him is received.
Mark and consider in silence, in the lowliness of mind,
and you will hear the Lord speak unto you in your mind: his voice is sweet and pleasant;
his sheep hear his voice, and they will not hearken to another:
and when they hear his voice, they rejoice and are obedient; they also sing for joy.
Oh, their hearts are filled with everlasting triumph!
they sing and praise the eternal God in Zion:
their joy shall never man take from them.
Glory be to the Lord God forevermore!

--

And since many, that had been convinced of the truth, turned aside,
because of the persecution that arose, he wrote for the encouragement of the faithful,
these lines:

[.embedded-content-document.letter]
--

Come you blessed of the Lord, and rejoice together; keep in unity and oneness of spirit;
triumph above the world; be joyful in the Lord; reigning above the world,
and above all things that draw from the Lord; that in clearness, righteousness, pureness,
and joy, you may be preserved to the Lord.
O hear, O hearken to the call of the Lord, and come out of the world,
and keep out of it forevermore! and come, sing together, you righteous ones,
the song of the Lord, the song of the Lamb; which none can learn,
but they who are redeemed from the earth, and from the world.

--

Now while G. Fox was at Derby in the house of correction, his relations came to see him,
and being sorry for his imprisonment, they went to the justices,
by whose order he was put there, and desired that he might be released,
offering to be bound in one hundred pounds,
and others in Derby in fifty pounds apiece with them,
that he should no more come there to declare against the priests.
But he being brought before the justices,
would not consent that any should be bound for him,
because he believed himself to be innocent from any ill behavior.
Then justice Bennet rose up in a rage,
and as G. Fox was kneeling down to pray to the Lord to forgive him, Bennet ran upon him,
and struck him with both his hands, crying.
Away with him, jailer; take him away, jailer.
Whereupon he was carried back again to prison, and there kept,
until the time of his commitment for six months was expired.
But now he had liberty of walking a mile; which he had made use of, in his own freedom:
and sometimes he went into the market and streets, and warned the people to repentance.
And on the First-days he now and then visited the prisoners in their religious meetings.
But the justices having required sureties for his good behavior,
it came upon him to write to them again, as follows:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

See what it is in you that does imprison; and see, who is head in you; and see,
if something do not accuse you?
Consider, you must be brought to judgment.
Think upon Lazarus and Dives; the one fared sumptuously every day; the other a beggar;
and now you have time, prize it, while you have it.
Would you have me to be bound to my good behavior?
I am bound to my good behavior, and do cry for good behavior of all people,
to turn from the vanities, pleasures, and oppression, and from the deceits of this world:
and there will come a time, that you shall know it.
Therefore take heed of pleasures, and deceits, and pride: and look not at man,
but at the Lord; for look unto me, all you ends of the earth, and be saved,
says the Lord.

--

[.offset]
Not long after he wrote to them again, thus:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Would you have me to be bound to my good behavior from drunkenness, or swearing,
or fighting, or adultery, and the like?
The Lord has redeemed me from all these things;
and the love of God has brought me to loathe all wantonness, blessed be his name.
They who are drunkards, and fighters, and swearers, have their liberty without bonds:
and you lay your law upon me, whom neither you,
nor any other can justly accuse of these things, praised be the Lord!
I can look at no man for my liberty, but at the Lord alone;
who has all men`'s hearts in his hand.

--

And after some time, not finding his spirit clear of them, he wrote again, as follows:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

Had you known who sent me to you, you would have received me;
for the Lord sent me to you, to warn you of the woes that are coming upon you;
and to bid you, look at the Lord, and not at man.
But when I had told you my experience, what the Lord had done for me,
then your hearts were hardened, and you sent me to prison;
where you have kept me many weeks.
If the love of God had broken your hearts, then would you see what you have done.
You would not have imprisoned me, had not my Father permitted you;
and by his power I shall be loosed; for he opens and shuts, to him be all glory!
In what have I misbehaved myself, that any should be bound for me?
All men`'s words will do me no good, nor their bonds neither, to keep my heart,
if I have not a guide within, to keep me in the upright life to God.
But I believe in the Lord, that through his strength and power,
I shall be preserved from ungodliness and worldly lusts.
The Scripture says, Receive strangers; but you imprison such.
As you are in authority, take heed of oppression and oaths, and injustice and gifts,
or rewards, for God does loathe all such: but love mercy, and true judgment, and justice,
for that the Lord delights in.
I do not write with hatred to you, but to keep my conscience clear:
take heed how you spend your time.

--

To the priests of Derby he also wrote again in this manner:

[.embedded-content-document.letter]
--

[.salutation]
Friends,

You do profess to be the ministers of Jesus Christ in words,
but you show forth by your fruits, what your ministry is.
Every tree does show forth its fruit; the ministry of Jesus Christ is in mercy and love,
to unloose them that be bound, and to bring out of bondage,
and to let them that are captivated go free.
Now, friends, where is your example,
(if the Scriptures be your rule,) to imprison for religion?
Have you any command for it from Christ?
If that were in you, which you do profess, you would walk in their steps,
who spoke forth those words, the Scriptures which you do profess.
But he is not a Jew, who is one outward, whose praise is of men; but he is a Jew,
who is one inward, whose praise is of God.
But if you do build upon the prophets and apostles in words, and pervert their life,
remember the woes which Jesus Christ spoke against such.
They that spoke the prophets`' words, but denied Christ, they professed a Christ to come;
but had they known him they would not have crucified him.
The saints, which the love of God did change,
were brought thereby to walk in love and mercy; for he that dwells in love,
dwells in God, But where envy, pride, and hatred does rule,
the nature of the world does rule, and not the nature of Jesus Christ,
I write with no hatred to you, but that you may weigh yourselves,
and see how you pass on your time.

--

Having thus cleared his conscience to the priests,
it was not long before a concern came upon him to write again to the justices,
which he did as follow:

[.embedded-content-document.letter]
--

I am moved to warn you to take heed of giving way to your own wills.
Love the cross, and satisfy not your minds in the flesh;
but prize your time while you have it, and walk up to that you know, in obedience to God;
and then you shall not be condemned for that you know not, but for that you do know,
and do not obey.
Consider betimes, and weigh yourselves, and see where you are, and whom you serve.
For if you blaspheme God, and take his name in vain; if you swear and lie;
if you give way to envy, hatred, covetousness, and greediness, pleasures, and wantonness,
or any other vices, be assured then, that you do serve the devil;
but if you fear the Lord, and serve him, you will loathe all these things.
He that loves God, will not blaspheme his name; but where there is opposing of God,
and serving the devil, that profession is sad and miserable.
O prize your time, and do not love that which God does forbid; lying, wrath, malice,
envy, hatred, greediness, covetousness, oppression, gluttony, drunkenness, whoredom,
and ail unrighteousness, God does forbid.
So consider, and be not deceived, evil communication corrupts good manners.
Be not deceived,
God will not be mocked with vain words the wrath of God
is revealed from heaven against all ungodliness.
Therefore obey that which does convince you of all evil, and tells you,
that you should do no evil.
It will lead to repentance, and keep you in the fear of the Lord!
O look at the mercies of God, and prize them, and do not turn them into wantonness.
O eye the Lord, and not earthly things!

--

Besides this, he wrote the following to Nathaniel Barton, who, as was hinted before,
was both a justice, and a preacher.

[.embedded-content-document.letter]
--

[.salutation]
Friend,

Do not cloak and cover yourself: there is a God who knows your heart,
and will uncover you; he sees your way.
Woe be to him that covers, and not with my Spirit, says the Lord.
Do you do contrary to the law, and then put it from you in Mercy,
and true judgment you neglect: look what was spoken against such.
My Savior said to such, "`I was sick and in prison, and you visited me not;
I was hungry and you fed me not; I was a stranger and you took me not in.`"
And when they said.
When saw we you in prison, and did not come to you, etc.
He replied, "`Inasmuch as you did it not to one of these little ones,
you did it not to me.`"
Friend, you have imprisoned me for bearing witness to the life and power of truth;
and yet profess to be a minister of Christ: but if Christ had sent you,
you would bring out of prison, and out of bondage, and would receive strangers.
You have been careless upon earth; you have lived plenteously, and nourished your heart,
as in a day of slaughter: you have killed the just.
O look where you are, and how you have spent your time!
O remember yourself, and now, while you have time, prize it,
and do not slight the free mercy of God, and despise the long suffering of God,
which is great salvation; but mind that in you, which does convince you,
and would not let you swear, nor lie, nor take God`'s name in vain.
You know you should do none of these things:
you have learned that which will condemn you; therefore obey the light,
which does convince you, and forsake your sins, and look at the mercies of God,
and prize his love in sparing you till now, The Lord says,
"`Look unto me all you ends of the earth, and be saved:`" and, "`Cease from man,
whose breath is in his nostrils.`"
And friend, prize your time, and see whom you serve; for his servant you are,
whom you do obey, "`Whether of sin unto death, or obedience unto righteousness.`"
If you serve God, and fear him, you will not blaspheme his name, nor curse, nor swear,
nor take his name in vain; nor follow pleasures and wantonness, whoredom,
and drunkenness, or wrath, or malice, or revenge, or rashness, or headiness,
pride or gluttony, greediness, oppression or covetousness, or foolish jesting,
or vain songs; God does forbid these things, and all unrighteousness.
If you profess God, and acts any of these things, you take him for a cloak,
and serve the devil: consider with yourself, and do not love that which God does hate.
He that loves God, keeps his commandments.
The devil will tell you, it is a hard thing to keep God`'s commandments;
but it is an easy thing to keep the devil`'s commandments,
and to live in all unrighteousness and ungodliness,
turning the grace of God into wantonness.
"`But let the unrighteous man forsake his ways, and turn unto me,`" says the Lord,
"`and I will have mercy. Turn, why will you die?`"
says the Lord.

Howl you great ones, for the plagues are pouring out upon you!
Howl you oppressors, for recompense and vengeance is coming upon you!
Woe unto them that covetously join one house to another,
and bring one field so nigh unto another, that the poor can get no more ground,
and that you may dwell upon the earth alone:
these things are in the ears of the Lord of Hosts.
Woe unto him that covetously gets ill-gotten goods into his house,
that he may set his nest on high, to escape from the power of evil.

--

It has been said already, that some of G. Fox`'s friends were moved, as well as he,
to preach the doctrine of truth; and in this year it also happened,
that Elizabeth Hooton, of whom mention has been made before,
from a true experience of the Lord`'s work in man,
also felt herself moved publicly to preach the way of salvation to others,
being the first woman preacher, by what I am informed,
among those that began now generally to be called by the name of Quakers.
Yet I have found in a Dutch book, printed at Dordt, in the year 1647, and called,
[.book-title]#History of the Troubles in England#,_ concerning the various Sects risen there,
that among other persuasions at London,
there were also women that did preach in large meetings,
and were heard by many with great satisfaction;
so that the preaching of a woman was not such a novelty as otherwise it might have been.

In the foregoing year it has been said,
that some Scotch Commissioners having been with Charles II. in Holland,
were returned to Scotland;
and though the King at first seemed backward to consent to the Presbyterian Covenant,
yet seeing no other way open to the Scottish throne, he came to other thoughts,
and so went over to Scotland, and made his entry into Edinburgh,
through the gate on which were placed the quarters of the Earl of Montrose,
who having endeavored not long before to subdue the Scots,
had been beaten with his forces, and, being taken prisoner, was executed.
The young King being now come into Scotland,
seemed willing to comply as much as he could, thereby to ingratiate himself,
not only with the Scots, but also with the English, if possible; and in order thereunto,
he gave forth a declaration at his Court at Dumfermling, dated the 16th day of August,
1650, and in the second year of his reign, as it is there said, in which declaration,
I meet with the following words:--

[quote]
____
Though his Majesty, as a dutiful son, be obliged to honor the memory of his royal father,
and have in estimation the person of his mother,
yet does he desire to be deeply humbled and afflicted in spirit before God,
because of his father`'s hearkening to evil counsels,
and his opposition to the Work of Reformation, and to the Solemn League and Covenant,
(by which so much of the blood of the Lord`'s people has been shed
in these kingdoms,) and for the idolatry of his mother.
____

Here the King confessed openly, that his father`'s house was guilty of great crimes,
and plainly signified, that the nation indeed had been wronged by his father`'s behavior;
and he seemed to promise amendment, if he came to be restored.
In the meanwhile, they began to see in England,
that the Scots were like to make head against them:
and therefore they ordered to send General Fairfax with an army there;
but he showed himself unwilling to go, chiefly, as it was believed,
by the advice of his wife, who hearkened to the counsel of the Presbyterian preachers;
and these thought it would contribute to their own settlement,
if those of their own persuasion in Scotland were not resisted.
But the Parliament, many of whose members were independents, did not matter that;
but resolved, since Fairfax resigned voluntarily,
to create Oliver Cromwell general of the national forces, in the room of Fairfax.
Which being done, Cromwell was sent with an army to Scotland,
and beat the Scots not far from Edinburgh,
whereby that city not long after yielded to him.

In this year was born in Holland, on the 14th of the month called November,
N+++.+++ S. William the Third, Prince of Orange,
whose mother was daughter of the late King Charles the First.
And this prince, by a strange revolution of human affairs,
has since been advanced to the English throne; and is at present, while I write this,
King of Great Britain, etc.
