== Chapter V.

=== 1654 -1656.

W+++.+++ Caton and J. Stubbs travelling together,
are cruelly whipped--They go to Zealand and Holland--Return,
and go into Scotland -- Labors and cruel suffering of J. Parnel -- His death--E. Burrough
and F. Howgill in Ireland--W. Ames convinced--E. Burrough and F. Howgill banished from
Ireland-Barbara Blaugdone in Ireland -- Extraordinary circumstances attending her visit
in Ireland -- M. Halhead goes to London --His letter to his wife - Imprisonment of M.
Halhead and T. Salthouse-- Imprisonment of G. White head,
R+++.+++ Clayton,
and J. Harwood--Remarkable conversation between W. Dewsbury and
Judge Atkins--G. Fox`'s fear respecting J. Nayler--Remarkable account
of J. Lilburn-- Plot of the Royalists against Cromwell.

I return to W. Caton and J. Stubbs.
They went from Lydd to Ashford, Tenterdeu, Cranbrook, and Staplehurst,
where they found an open and tender-hearted people, who embraced their doctrine,
and some would have given them money, no, even have forced it upon them,
yet they would not take any: but as they freely had received, so they freely gave:
telling people it was not theirs, but them, which they sought.
From there they travelled to Maidstone,
where J. Stubbs went to the public place of worship,
and W. Caton to the meeting of the Independents.
J+++.+++ Stubbs was taken at the steeple-house, and W. Caton, the day following from his inn,
and were both sent to the house of correction, where they were searched, and their money,
inkhorns, and bibles, etc. taken from them.
Afterwards they were stripped, and their necks and arms put in the stocks,
and in that condition were desperately whipped.
A hard encounter indeed, especially for such a young man as W. Caton was;
but they were supported by an invisible hand.
Afterwards means were used to compel them to work; and it was told them,
he that would not work should not eat.
But they were not free to consent thereto, because they esteemed this demand unjust,
not being guilty of the breach of any law.
Thus they were kept without food for some days,
only a little water once a day was allowed them.
In the meanwhile, the malefactors that were there, would have given them of their bread;
yes, the women of the house being moved with compassion,
would have given them something privately; but they were not free to accept of either.
Now the report of this cruelty being spread in the town, many began to be offended at it;
so that an officer was sent to make restitution of some of their things,
which had been taken from them, and then they bought food with their own money.
Not long after, they were parted, and with officers conveyed out of the town,
one at the one end of it, and the other at the other.

At length W. Caton came to London, where he found his companion, J. Stubbs;
but being there, it came upon them to return to the town from which they came,
which was no small trial to them; but yet they resigned,
and gave up to what they believed to be the will of the Lord.
Now Providence so ordered it, that none meddled with them, though they,
to be more fully seen, went on a First-day of the week to the steeple-house.
They went also to Canterbury, where, at the meetings of the Baptists and Independents,
they had pretty good liberty to declare the Truth among them; and some,
being convinced, received their testimony.
They were likewise at Sandwich,
where W. Caton had some service among the Dutch people at their steeple-house.

It was now nigh Midsummer, when he felt a motion to go over to Calais, in France.
For that end he went to Dover, and so to Calais,
where coming to their high place of worship,
his spirit was very much grieved and burdened, with the great idolatry in vogue there;
for he saw how some were worshipping before their dumb idols,
and he could not well ease his spirit for lack of the language.
Having some time walked about in the town,
he came to be known to some of the chief of the city, who desiring to speak with him,
some of them came down in person to the quay, to look for him;
and understanding he was aboard, he was called ashore, and conveyed to a large house,
where several of the great ones were come to see and hear him:
so that he had a very good opportunity to declare the Truth among them,
there being a Scotch lord who interpreted for him.
And after he had cleared his conscience, they allowed him to depart quietly.

Soon after he returned for England, and found his companion, J. Stubbs, at Dover;
and it being upon him to go for Holland, W. Caton was made free to accompany him.
With this intent, they went together to Yarmouth,
but could not find passage there for Holland, and so they passed further to the North;
and coming to Swarthmore, W. Caton found his friends very glad to see him,
especially Margaret Fell, who had been as a nursing mother to him.
After some stay there, having been abundantly refreshed, they went to Shields,
where they heard of a ship bound for Flanders; but having little inclination to go there,
came soon after to Yarmouth, where they found a ship intended for Flushing, in Zealand.
With this vessel they went over, and arrived safely at the said town:
and on the First-day of the week,
they went to the congregation of the English and Scotch,
where many wondered at them because of their non-conformity;
and after they began to speak, there arose a great stir,
so that they were soon hurried out.
The same day they went to Middleburg, where being come,
before the afternoon`'s worship was ended,
one of thorn began to speak after the priest had done: but he stopped him presently,
thinking at first they were such as came there begging; but perceiving the contrary,
he and others were the more violent.
After that, he sent for them to his house, and reasoned awhile with them;
but he being of a lofty mind, they found but a slight entertainment there.
After a short stay in town, they embarked themselves for Rotterdam, in Holland,
where being come, when they had been some few days in the city,
they got a meeting at an English merchant`'s house: but he that interpreted for them,
not rendering their words truly, it seemed not to satisfy the hearers.
After some time they returned to Zealand, and from there again to England,
where being arrived, W. Caton journeyed to Swarthmore, and was received there with joy;
and having some drawings to Scotland, he went to Bishopric,
where he found his companion J. Stubbs again, with whom he travelled towards Scotland.
It was about the beginning of the month called December,
when they came to Berwick upon Tweed, where W. Caton went into the great public assembly;
and when the priest had done, stepped upon a seat, and beginning to speak,
none seemed to make such haste to get away, as the priest:
in the meanwhile W. Caton spoke with great boldness,
and had pretty good liberty to declare the Truth.
But when he had done, he was taken hold of, and brought before the magistrates,
who ordered that he should be turned out of the town; which was done.
J+++.+++ Stubbs was that day in a meeting of the Baptists, and had some service there.
Not long after, W, Caton, who wandering up and down,
could not well get any lodging for his money, returned, and came into the town again,
the guard allowing him very freely to pass.

Then they both travelled to Edinburgh, in Scotland,
where they found things somewhat out of order,
through the unfaithfulness of some that were convinced of the Truth;
but their ministry was so effectual among them,
that they were brought into better order again:
and so they edified the church according to their ability,
the meeting being kept at the house of William Osborn, who had been a lieutenant-colonel,
and afterwards become a zealous minister among the flock there.
While W. Caton was there, he went once to the chief steeple-house, where,
after the priest had done, he spoke to the people; but, the multitude combining,
he was not allowed to say much, but was carried out; and coming into the street,
there was a guard of soldiers,
who conducted him with drawn swords to the places where he desired to be.
He was about that time also with general Monk, who behaved himself moderately,
and heard him.
J+++.+++ Stubbs now returning to England, W. Caton went to Stirling, where,
being carried to the governor, he was at first high, but when W. Caton,
who was a man of meek behavior, had spoke a little to him, he became cool and sedate.
He then went to the English chaplain`'s house, who was kind to him.
From Edinburgh he went to Glasgow, where, going into the great cathedral,
after the service was done, he had some liberty to speak to the multitude in the yard,
the rude people being kept under by the English soldiers, who were moderate,
so that he had very good service there.
He also went to Douglas, where his service was no less,
both in the steeple-house and elsewhere: so that having cleared himself in Scotland,
he returned to England, and came again to Swarthmore,
where he was received as formerly in very great love.

Leaving him there, I turn again to G. Fox, whom we left in Bedfordshire.
From there he went by London to Kent, and came to Romney,
not long after W. Caton and J. Stubbs had been there.
Here he had a very large meeting, where Samuel Fisher also came,
and there was a great convincement that day,
so that many were turned to the light of Christ:
and after the meeting S. Fisher`'s wife said,
'`Now we may discern between flesh and spirit,
and distinguish spiritual teaching from fleshly.`'

From here G. Fox went to Dover and Canterbury, and further into Sussex,
and so to Reading, where they had a great meeting, and many were convinced that day.
There came also George Bishop, of Bristol, who, being a captain, then wore a sword,
though in time, he entirely left it off:

G+++.+++ Fox, going from here, passed up to London, where, leaving him for some time,
we will go and behold the life and occurrences of James Parnel, who was born at Retford,
in Nottinghamshire, and trained up in the schools of literature.
He labored very early in the ministry of the gospel, having been convinced by G. Fox,
when not quite sixteen years of age, and then embraced the Truth;
though for that reason despised and rejected by his relations.
He was, (though of low stature,) endued with great ability, and did not fear,
wherever he came, to call people to repentance.
Being imprisoned at Cambridge for his zealous testimony,
and afterward turned out of town like a vagabond,
he soon came back and disputed with the scholars of the university;
but met with rude and bad entertainment from them.
In the beginning of this year he came into Essex, being then about eighteen years of age,
and preached the gospel in several parts of that county, as Felsted, Stebbing, Witham,
Coggeshall, Halsted, and other places, and many received the word by his ministry.
About the middle of the summer he came to Colchester,
and there preached the gospel on a First day of the week in a steeple-house,
after the sermon; then in a great meeting appointed on purpose;
and after that disputed with the town-lecturer, and another priest, in the French school,
all in one day; so that many were convinced of the Truth preached by him;
and among these also Stephen Crisp, of whom more will be said hereafter.
J+++.+++ Parnel spent that week in the said town, preaching, exhorting, and disputing,
to the convincing of many; though others were enraged, insomuch,
that his godly zeal was often rewarded with blows;
as once coming out of Nicholas`' steeple-house, he was struck by one with a great staff,
who said, '`There, take that for Christ`'s sake.`'
To which he meekly answered, '`Friend, I do receive it for Jesus Christ`'s sake.`'
Many other grievous affronts he bore, without showing any heat or anger;
so that he was a real pattern of patience and meekness.

Having labored in the gospel about ten days in Colchester, he went to Coggeshall,
where a fast was proclaimed, to be held upon the 12th of the month called July,
to pray against the errors of the people called Quakers.
J+++.+++ Parnel being come there, went into the steeple-house, where he stood still,
till the priest was coming out of the pulpit.
Now since this priest Sammes, who was an Independent,
had cried out fiercely against the Quakers, as deceivers,
J+++.+++ Parnel esteemed it his duty to say something to that;
and the first words he spoke were, '`This is the order of the true church,
that all may speak one by one; and if any thing be revealed to him that stands by,
let the first hold his peace.`'
Then he spoke on behalf of those called Quakers: but the priest, interrupting,
asked what he would object against him?
To which J. Parnel answered, in that he reviled the people called Quakers,
and said they were built upon a sandy foundation, and so called them Shakers.
'`But,`' said he, '`I will prove their foundation not to be sandy,
and you to be a false prophet.`'
After some more words spoken by him, some accused him, that he acknowledged no church:
to which he said it was false.
Then it was asked him what church he acknowledged?
And he answered, the church in God.
Then priest Willis stood up, and said, he spoke nothing but nonsense.
Parnel bade him name one word which he had spoken that was nonsense.
At which Willis said, '`To say the church in God.
Then Parnel took out his bible,
and read 1 Thess. 1:1. where the apostle writes to the church,
which is in God the Father.
The priest now was at a loss, and Parnell told him,
that he blasphemed in saying the church in God was nonsense.
Then priest Stellum stood up, and accused Parnel with lies and slanders,
and not permitting him to clear himself from those accusations,
he got up into the pulpit, and began to pray; but Parnel not taking off his hat,
the magistrates called to him to put it off.
To which he returned, '`Order the priest to put off his cap;`' and further said,
before he should be subject to their wills,
he would rather pass out of the meeting place; and so he went out.

Not long after, justice Dionysius Wakering followed him,
and struck him with his hand upon his back,
saying he arrested him in the name of the lord protector.
Parnel, not knowing him to be a magistrate, asked him where his court order was.
Wakering said he had one; but showed none.
Then Parnel was hurried into a house, and some of his friends engaged,
that he should be forthcoming when their worship was done.
And accordingly he appeared where four justices and six or seven priests were met together.
Then justice Wakering pulled his hat off his head, and threw it away;
and they questioned him concerning many things; all which he answered,
with many frivolous questions asked to ensnare him.
At last he was committed to the common jail at Colchester,
where none of his friends were permitted to come to him.
The time of the sessions at Chelmsford being come, he,
with several felons and murderers was fastened to a chain,
and thus led about eighteen miles through the country,
remaining chained both night and day.

Being brought into the court before judge Hills,
the jailer took off his hat and cast it upon the floor.
Then the clerk read his indictment, and asked him if he was guilty; to which he said,
that he denied all guilt; and he called for his accusers.
The judge said he might see them; and that he ought to say guilty, or not guilty.
On which Parnel told him, he was not guilty.
Then a jury of twelve men was called, whose foreman was a drunkard;
priest Willis was also called, who swore against him, and so did two justices;
one of their men swearing that they would speak nothing against him but the truth.
The accusations were,
that in a riotous manner he did enter into the parish church at Great Coggeshall;
that he there did stand up, and told the minister he blasphemed, and spoke falsely,
using many other reproachful words against him:
and he could not give a good account where he was last settled,
or of his life and conduct, appearing to be an idle person.
He was also accused with contempt of the magistracy, and of the ministry.
To this he answered, that he no ways in a riotous manner entered the steeple-house,
but came there quietly, and alone:
for being followed by several boys that would have come in after him,
he bade them go in before, rather than to go in disorderly,
whereby to occasion any disturbance.
That he had said to priest Willis, he blasphemed,
by saying the church in God was nonsense, he denied not;
but did not acknowledge himself to be a vagabond and idle person.
And he did not think it indecent to call an unjust judge, unrighteous; a persecutor,
persecutor; and a deceiver, deceiver.
Thus Parnel pleaded his cause.
Yet the judge said to the jury, that if they did not find him guilty,
the sin would he upon their heads;
thus condemning the prisoner before the jury had considered the case.
Then J. Parnel began to speak, to inform them concerning his cause,
but the judge would not permit him, though one of the jury desired it.
After consultation, the jury had nothing to lay to his charge,
but a paper in which he had answered the court order,
though he had already acknowledged this paper to be his writing.
But in that they were at a loss, because in the indictment he was accused of a riot:
yet the judge and the clerk strove to draw some words from the foreman,
which the other jurymen did not consent to,
and he himself was unwilling to answer fully to their questions.
Then J. Parnel was made to withdraw; and being called in again,
the judge fined him to the value of about forty pounds,
for contempt of the magistracy and ministry;
for he said the lord protector had charged him to punish
such persons as should contemn either magistracy or ministry.
Thereupon J. Parnel was carried back again to the prison, being an old ruinous castle,
built as it is reported, in the time of the ancient Romans:
here he was to be kept until the fine should be paid: and the jailer was commanded,
not to let any giddy-headed people,
(by which denomination they meant his friends,) come at him.

The jailer was willing enough to comply with this order, allowing none to come to him,
but such as abused him; and his wife, who was a wicked shrew,
did not only set her man to beat him,
but several times herself laid violent hands upon him,
and swore she would have his blood:
she also set other prisoners to take away the food brought to him by his friends;
and would not let him have a trundle bed, which they would have brought him to lie on,
so that he was forced to lie on the cold and damp stones.
Afterwards he was put into the hole in the wall, a room much like a baker`'s oven;
for the walls of that building, which is indeed a direful nest,
are of an excessive thickness, as I have seen myself,
having been in the hole where this pious young man ended his days,
as will be said by and by.
Being confined in the said hole, which was, as I remember,
about twelve feet high from the ground, and the ladder too short by six feet;
he must climb up and down by a rope on a broken wall,
which he was forced to do to fetch his food, or for other necessities:
for though his friends would have given him a cord and a basket to draw up his food in,
yet such was the malice of his keepers, that they would not allow it.

Continuing in this moist hole, his limbs grew benumbed; and thus it once happened,
that as he was climbing up the ladder, with his food in one hand,
and come to the top thereof, catching at the rope with his other, he missed the same,
and fell down upon the stones, whereby he was exceedingly wounded in his head,
and his body so bruised, that he was taken up for dead.
Then they put him into a hole underneath the other;
for there were two rows of such vaulted holes in the wall.
This hole was called the oven, and so little, that some baker`'s ovens were bigger,
though not so high.
Here, (the door being shut,) was scarcely any air, there being no window or hole.
And after he was a little recovered from his fall,
they would not allow him to take the air, though he was almost spent for lack of breath:
and though some of his friends, namely, William Talcot and Edward Grant,
did offer their bond of forty pounds to the justice Henry Barrington, and another,
whose name was Thomas Shortland, to lie body for body,
that Parnel might but have his liberty to come to W. Talcot`'s house, and return,
when recovered; yet this was denied; no so immoveable were they set against him,
that when it was desired that he might only walk a little sometimes in the yard,
they would not grant it by any means: and once the door of the hole being open,
and he coming forth, and walking in a narrow yard between two high walls,
so incensed the jailer, that he locked up the hole,
and shut him out in the yard all night, being in the coldest time of the winter.
This hard imprisonment did so weaken him,
that after ten or eleven months he fell sick and died.
At his departure there were with him Thomas Shortland, and Ann Langley:
and it was one of these, that came often to him,
who long after brought me into this hole where he died.

Several things which are related here, I had from the mouth of eyewitnesses,
who lived in that town.
When death approached, he said, '`Here I die innocently.`'
A little after he was heard to said, '`Now I must go:`' and turning his head to Thomas,
he said, '`This death must I die; Thomas, I have seen great things: don`'t hold me,
but let me go.`'
Then he said again, '`Will you hold me?
To which Ann answered, '`No, dear heart, we will not hold you.`'
He had often said that one hour`'s sleep would cure him of all:
and the last words he was heard to say, were, '`Now I go;`' and then stretched out himself,
and slept about an hour, and breathed his last.
Thus this valiant soldier of the Lamb conquered through sufferings:
and so great was the malice and envy of his persecutors,
that to cover their guilt and shame, they spread among the people,
that by immoderate fasting, and afterwards with too greedy eating,
he had shortened his days.
But this was a wicked lie;
for though it be true that he had no appetite to eat some days before he fell sick,
yet when he began to eat again, he took nothing but a little milk,
as was declared by credible witnesses.
During his imprisonment he wrote several edifying epistles to his friends.

By continuing this relation without breaking off, I am advanced somewhat as to time;
but going back a little,
let us see the transactions of Edward Burrough and Francis Howgill.
It was in the year 1655, that they went together to Ireland,
where they came in the summer, and stayed more than six months,
having spent at Dublin about three months, without being disturbed,
though they omitted no opportunity to declare the doctrine of Truth.
Henry Cromwell, son of the protector, was at that time lord deputy of Ireland;
and it was in his name that they were carried from Cork,
(where they were gone,) to Dublin; for since several received their testimony,
and adhered to the doctrine they preached, it was resolved upon,
not to let them stay any longer in Ireland.
Here it was, as I have been told, that William Ames, by their ministry,
was brought over into the society of the Quakers, so called.
He was a Baptist teacher, and also a military officer,
who being of a strict life himself, kept his soldiers under a severe discipline.
I remember how he used to tell us,
when any soldier under his colors had been guilty
of any immorality on a First-day of the week,
he presently had him bound neck and heels.
But being now entered into the society of the despised Quakers,
and in process of time becoming a minister among them,
it was not long before he was cast into prison; of whom more may be said hereafter.

Now E. Borrough and F. Howgill were banished out of Ireland;
but on the same day that they were sent away, Barbara Blaugdone arrived there.
She went from England in a vessel bound for Cork, but by foul weather carried to Dublin.
When the tempest was high, the seamen said, that she being a Quaker was the cause of it,
and they conspired to cast her overboard.
Aware of this plot, she told the master what his men designed to do,
and said that if he did permit this, her blood would be required at his hands.
So he charged them not to meddle with her.
The storm continuing, and it being on a First-day of the week, she went upon the deck,
feeling herself moved to speak to the seamen by way of exhortation, and to pray for them;
for their priest, afraid like the rest, could not say any thing among them.
Having spoke what was upon her, she concluded with a prayer;
and all the ship`'s crew were very quiet and sedate, saying,
that they were more beholden to her than to their priest, because she prayed for them;
and he, for fear, could not open his mouth to speak.
At length they arrived safe at Dublin, without damage, which indeed was strange,
and made the master say, that he was never in such a storm without receiving any loss.

Barbara going ashore, went to the house of the deputy; but the people told her,
there was for her no speaking with him;
for she might know that he had banished two of her
friends out of the nation the day before,
Then she met with the secretary, and desired him to help her to speak with the deputy,
He answered that he did not think he could;
then she told him that if he would be so civil,
as to go up and tell the deputy that there was a women below that would speak with him;
if he refused, she was answered.
So the secretary went up; and there came a man to fetch her into the withdrawing-room;
and after she had been there awhile, a person came out of the deputy`'s chamber,
and all that accompanied him stood bare-headed; for they knew she never saw the deputy,
but she had a sense it was a priest, who showed himself covered to deceive her:
and the room being almost full of people,
they asked her why she did not do her message to their lord.
To which she answered, '`When I see your lord, then I shall do my message to him.`'
A little after the deputy came forth, and sat down on a couch: she then stood up,
and speaking to him what was upon her mind,
bade him beware that he was not found fighting against God, in opposing the Truth,
and persecuting the innocent; but like wise Gamaliel, to let them alone;
for if it was of God, it would stand; but if of man, it would fall.
Further, that the enmity did not lie so much in himself,
but he was stirred up to it by evil magistrates, and bad priests;
and that God`'s people were as dear to him now, as ever; and they that touched them,
touched the apple of his eye.
In the meanwhile, in his name, and by his power,
there was much hurt done to the people of God, all over the nation,
and it would at last lie heavy upon him.
Moreover, that the teachers of the people did cause them to err,
and that he knew the priests`' condition.
She touching upon that, the deputy said to the priest that stood by, '`There`'s for you,
Mr. Harrison:`' and she spoke with such power, that it made the deputy much concerned:
and when she had done, he asked the priest what he had to say to that which she spoke.
And he said, it was all very true, and very good, and he had nothing to say against it,
if she did speak as she meant.
Then she told the priest, that the Spirit of God was true, and did speak as it meant,
and meant as it spoke; but that men of corrupt minds did pervert the Scriptures,
by putting their own imaginations and conceivings upon it, and so did deceive the people:
but the holy men of God wrote,
and gave forth the Scriptures as they were inspired of the Holy Ghost;
and that they were of no private interpretation;
and could not be understood but by the same spirit that gave them forth.

After having thus spoken, she went away, and returned to her lodging,
which was at one captain Rich`'s house, who coming home, said,
that the deputy was so sad and melancholy, after she had been with him,
that he could not go to bowls, or to any other pastime.

Barbara having now performed her service at Dublin, went to Cork,
where she had some relations and acquaintance; but great were her sufferings thereabout;
for she was imprisoned almost wherever she came,
being moved to follow those of her acquaintance, into several steeple-houses:
yet wherever her mouth was opened, there was some that received her testimony,
Once she was made to speak in a market-place where
a butcher swore he would cleave her head;
and having lifted up his cleaver to do it, there came a woman behind him,
and catching his arms, stopped him, till the soldiers came and rescued Barbara.
Many of her acquaintance, with whom she formerly had been very conversant,
were now afraid of her; for sometimes she spoke so awfully to them in their houses,
that it made them tremble; and some said she was a witch; and, running away,
their servants turned her out of doors.
After having been there some time, she returned home to Bristol;
but it was not very long before she was moved to go to Ireland again;
and being come near Dungarvon, the ship foundered near the shore:
the master and the passengers got into the boat, save one man and a woman,
who were cast away; and Barbara who was still in the cabin,
was almost stifled by waves that beat in upon her; yet at length she got upon the deck.
The master in the meanwhile being come ashore, called to her,
that if she would leap down,
he and another would venture to come into the water to save her.
Accordingly they came up to their necks, and she leaping down, they caught her;
but being entangled in the ropes in leaping down, she was drawn from them again:
but presently a wave came rolling and beat the ship outward,
which was their preservation; for if it had beaten inward,
it might have killed them all three; she was thus caught again, and drawn to shore.
Then she went to Dublin, where coming into the court of justice, she spoke to the judges,
and exhorted them to righteousness.
But this was taken so ill, that she was put into prison,
where she lay upon straw on the ground, and when it rained,
the wet and filth of the house of office ran in under her.
Being arraigned at the bar, she was required to plead guilty or not guilty.
She answered that there was no guilt upon any one`'s conscience
for what was done in obedience to the Lord God.
But she not answering in that form of words they bid her, was sent back to prison again,
where she suffered much.
In the meanwhile, there happened a singular instance,
which I cannot pass by with silence.

At that time there was in prison an innkeeper, with his family,
being accused of a murder: now the brother of him that was either murdered, or lost,
could not enjoy some land, except he could prove that his brother was dead;
and in order thereto, he brought a fellow into the prison, who said,
he would prove that the man was killed at such an inn, and buried under a wall:
and he accused the innkeeper and his wife, their man and maid, and a smith,
to be guilty of this murder; they being already in prison.
Barbara having heard of this, found means to go to this desperate fellow:
and asked him how he could conceal this murder so long, when he was, according to law,
as guilty of it as any of them, if what he said were true.
At this question he trembled so exceedingly, that his knees struck one against another;
and he confessed that he never before saw the people with his eyes,
nor ever was at the place in his life, nor knew anything of it,
but only he was drawn in by the man that was to have the land,
and was persuaded to witness the fact.
Other prisoners heard this confession also, and Barbara sent to the deputy,
desiring him to send down his priest, that he might hear the said confession.
The priest came, and the fellow confessed the same to him as he had done to Barbara;
and he once also confessed the same before the judge.
But afterwards he eat his words; for the man that had induced him, came every day,
and made him drink plentifully, and also caused the jailer to lock up Barbara,
that she might not come to him.
Then she wrote to the innkeeper, and his wife, and man, and judge Pepes,
and told him the day of his death did draw nigh,
wherein he must give an account of his actions; and that therefore he ought to take heed,
that he did not condemn innocent people, having but one witness,
in whose mouth so many lies were found, the others all saying they were innocent.
For all that, the judge went on, and condemned all the accused, and the accuser also,
as conscious to the crime.
Hereupon a priest came to speak with the maid that was condemned,
and was in the same prison with Barbara, but she would not see him, saying, '`No,
he can do me no good; I have done with man forever: but God,
you know that I am innocent of what they lay to my charge.`'
But, however, they were all hanged, and the witness first,
probably for fear he should have made another confession
after he had seen the others hanged.

Now some friends of Barbara, namely, Sir William King, colonel Fare, and the lady Brown,
hearing she was in prison, came to see her,
and afterwards went to the afore-mentioned judge, to get her released:
but when they came to him, he told them, that he was afraid of his life.
At which they laughed, and said, they had known her from a child,
and there was no harm in her at all.
And being all very earnest to get her liberty, they at last obtained it.
Then she went to the steeple-house where this judge was, and cleared herself of him.
He being come home, went to bed, and died that night.
The noise of which sudden death being spread, it made people say,
that Barbara had been a true prophetess unto him.

She now went to Limerick, where she was put into prison,
but after a while being released, she took shipping for England again;
and at sea was robbed of all that she had, by a privateer, who, coming on board,
took the master away, until he should pay them a sum of money, for the ship and goods;
but she came safe to England.
She travelled at her own charge, paying for what she had.

But leaving her, I will return to Miles Halhead, who, as he was following the plough,
in the beginning of this year, felt a motion to go to London.
Taking York and Hull in his way,
and passing from there through Lincolnshire and Leicestershire,
he came to the city of London, from which, after some stay,
he went to Bristol with Thomas Salthouse, and so to Exeter and Plymouth,
where he suffered much persecution, and was imprisoned.
He wrote about that time a letter to his wife,
which I think worth the while to insert here, and was as follows:

Anne Halhead,

My dear heart, my dear love in the bowels of love, in the Lord Jesus Christ,
salutes you and my children.
My soul, my soul is poured forth in love to you daily, and the breathings,
of my soul to my Father is for you, that you may be kept in the fear of the Lord,
and in his counsel daily, that so you may come to rest and peace,
that is laid up for all that fear him,
and walk in obedience to the light that Jesus Christ has enlightened them withal.
So my dear heart, I declare to you, in the presence of the living God,
who is Lord of heaven and earth, and before men and angels,
there is no other way that leads to peace, and eternal rest,
but walking in obedience to the light that comes from Jesus Christ,
and of this light you have received a measure.
Therefore my dear heart, be faithful to the Lord in what is made known unto you,
that you may come to witness true peace and rest, that eye has not seen, nor ear heard,
neither has it entered into the heart of man, what is laid up for all them that fear him.
So, my dear heart, as I have found peace and eternal rest to my soul from the Lord,
so I am moved of the Lord in love to your soul,
to show you the way that leads to peace and eternal rest; which way is Christ,
who is the light, and the way that leads to the Father, from which all light comes;
and of this light which comes from Christ, I bear record you have received a measure.
Therefore, in dear love, I exhort you to walk in obedience to your measure,
which you have received from the Lord.
So, in the presence of the Lord God do I declare,
that walking in obedience to this light that comes from Christ,
is the way that leads to eternal rest and peace.
Therefore, as you tender the eternal good of your soul,
be faithful to the light that comes from Christ, which light bears witness against lying,
and swearing, and vain talking, and all manner of evil.
So, my dear wife, in bowels of dear love to your soul,
which is more precious than all the world, have I showed you the way;
if you will walk in it, it will lead you into the eternal covenant of life and peace.
So, my dear wife, in love, in love I have cleared my conscience to you,
in the presence of the living God, as a true and faithful husband to you,
desiring your eternal good and welfare as my own, the Lord God is my witness.
Dear wife, remember my dear love to all my friends and countrymen,
according to the flesh; for I desire the eternal good and welfare of you all,
and that you all may come to believe in the light in your own consciences,
which Jesus Christ has enlightened you with; which light bears witness against lying,
and swearing, and all manner of evil.
This is the light of Christ,
and walking in obedience to this light is the way that leads out of sin and evil,
up to God eternal, blessed forevermore:
and he that acts contrary to this light in his own conscience, it is his condemnation.
Now, dear friends, while you have time prize it.

Your husband, and a lover of your soul,

Miles Halhead

Wiltshire, the 7th of the Third month, 1655.

This year also he wrote the following epistle to his fellow-believers.

Dearly beloved friends and brethren,

In the North of England, even to the South, the land of our nativity,
whom the Lord God of heaven and earth has called and chosen
in this the day of his eternal everlasting love,
to serve him in truth and in righteousness,
who has received the Lord`'s Truth in the love of it, not only to believe in his name,
but to suffer bonds and imprisonments, and hard sentences for the testimony of Jesus,
and the word of God.
Dear friends, and beloved brethren, my prayers to the Lord God of heaven and earth,
and my soul`'s desire is for you all,
that you may all dwell together as children of one father, in the eternal bond of love,
and oneness of the spirit; that you may all grow in the eternal living Truth of God,
to be established upon the rock and sure foundation,
that the gates of hell and death cannot prevail against you;
that under the shadow of the wings of the Almighty,
you may all be kept and preserved in peace and rest, now in the day of trial,
and hour of darkness, when hell has opened her mouth,
and the raging sea cast out her proud waves, even like to overflow the banks.
Glory, glory, and eternal living praises be given to the Lord God,
and to the Lamb forevermore, of all the children of the light,
who has found a resting-place for all his dear ones, lambs, and babes,
and children of light to flee into, in the needful time of trouble,
where none can make them afraid, nor take away their peace,
as they abide faithful to him, who is our way, our light, our life, our strength,
and eternal portion forever.
My dear friends and brethren, I beseech you in the bowels of dear and tender love,
that you walk as dear children,
faithful to him who has called you with an honorable calling,
and loved you from the beginning with an everlasting love,
that all your friends and neighbors, and men of this world,
that see your life coupled with fear, may be made to confess and acknowledge,
to the honor and glory of the living Lord, that the God whom we serve and fear,
is the only true God of Israel:
and herein you become a precious savour unto the living eternal God,
and a sweet smelling savour unto all the children of light,
and no good thing will the Lord God withhold from you;
the mouth of the Lord God of Hosts has spoken it,
whose promises are yes and amen to his own seed forevermore.

Miles Halhead.`'

Given forth the 14th of the Sixth Month, 1655, when I was a prisoner at the prison-house,
in the city of Exeter, in Devonshire, for the testimony of Jesus, and the word of God.

A chief cause why he was imprisoned there, was, that Thomas Salthouse,
with whom he travelled, (having heard that one George Brooks,
a priest belonging to the Nightingale frigate, said,
after the declarations of M. Halhead, and T. Salthouse, at Plymouth,
that it was the eternal truth which they had spoken,
with many other words in vindication of what they said,) told Brooks,
that he had spoken many good words, and fair speeches; but asked him,
whether he lived the life of what he spoke?
Further, '`He that enters not by the door, but climbs up some other way, is,
as Christ said, a thief and a robber.`'
For T. Salt-house thought, and that not without reason, as will be shown by and by,
that he did not lack the praises of this priest,
that were not better than those of the damsel possessed with a spirit of divination,
which she spoke concerning Paul and Silas, namely,
'`These men are the servants of the most high God,
which show unto us the way of salvation.`'
Now what T. Salthouse had spoken to the priest, was called provoking language;
the rather, because when the priest was speaking of the trinity,
T+++.+++ Salthouse had asked him, where that word was to be found in the Scriptures:
saying further,`' I know no such Scripture that speaks of the three persons in the trinity;
but the three that the Scripture speaks of, are the Father, the Son, and the Holy Ghost,
and these three are one.`'
From here T. Salthouse, and M. Halhead,
were accused as such as denied the Holy Three that are One.
But because about this accusation, they were at a loss in the court,
something else was thought of to ensnare them, namely,
they were required to take the oath of abjuration of the Pope.
This oath the mayor of Plymouth had already tendered them,
when they were first apprehended; and they refusing to swear, were sent to Exeter prison:
and now being brought to trial, and the said oath required of them, they answered thus:

In the presence of the Eternal God, and before all this people, we do deny,
with as much detestation as any of you do, the Pope and his supremacy, and the purgatory,
and all that is in the form of the oath mentioned, we declare freely against:
and we do not deny to swear because of any guilt that is upon us,
but in obedience to the command of Christ, who says,
"`Swear not at all:`" and we will not come under the condemnation of an oath,
for the liberty of the outward man.`'

Thus refusing to swear,
merely that they might not offend against the command of our Savior,
they were sent back to prison again, as such that clandestinely adhered to the Pope:
and use has been made of this snare during the space of many years, to vex the Quakers,
so called.
The next day the prisoners were brought again before the bench, and were asked:

Will you confess, that you wronged G. Brooks, in calling him thief, and be sorry for it,
and make him satisfaction?`'

To this M. Halhead answered:

One of us did not speak one word to him, and therefore I deny to make him satisfaction,
or to be sorry for it; and what was spoken was no such thing;
therefore we will not lie for our liberty,
nor confess that we are sorry for that which we never spoke.

Then the court fined them five pounds a piece;
and they were to go to the house of correction till payment,
and to find sureties for their good behavior: and for refusing to take the oath,
the court threatened to send into the North to seize on their estates.
So they were returned to prison; and what follows,
was entered as the record of their proceedings.

July 10, 1655.
Thomas Salthouse, and Miles Halhead, for provoking words against G. Brooks, clerk,
who refused to be tried by the country, fined 5£ a piece,
committed to Bridewell till payment, and finding sureties for their good behavior.

What is said here of refusing to be tried by the country, was a notorious untruth:
and as to finding sureties, that seemed of little importance;
for though the giving of security had been offered before,
when they were taken prisoners, yet that was not accepted of; and the mayor, John Page,
had the boldness to assert, that they refused to give security,
as will appear by the warrant by which he sent them to the common jail in Exeter,
whereof the following is a true copy.

Devon,

John Page, merchant, mayor of the borough of Plymouth, in the county aforesaid,
and one of his highness`'s justices of the peace within the said borough,
to the keeper of his highness`'s jail at Exon castle,
or to his lawful deputy in that behalf, greeting.
I send you herewithal by the bearer hereof, the bodies of Thomas Salthouse,
late of Dragglibeck, in the county of Lancaster, husbandman; and Miles Halhead,
late of Kendal, in the county of Westmoreland, lately apprehended here,
as disturbers of the public peace,
and for several other high misdemeanors against a late proclamation,
prohibiting the disturbing of ministers and other
Christians in their assemblies and meetings,
and against an ordinance of his said highness the lord protector, and his council,
lately made against duels, challenges, and all provocations thereto,
who have refused to give sufficient security for their personal
appearance at the next general sessions of the peace,
to be held for the county of Devon;
and in the mean time to be of good behavior towards his highness the lord protector,
and all his liege people.
These are therefore in his said highness`'s name, to will and command you,
that when the bodies of the said Thomas Salthouse and Miles Halhead,
shall be unto you brought, you them safely detain, and keep them,
until by due course of law they shall be from there delivered:
hereof fail not at your peril.
Given under my hand, and seal of Plymouth aforesaid, the 28th day of May,
in the year of our Lord God, 1655.

JOHN PAGE, Mayor.

By this may be seen under what frivolous pretences those called Quakers were imprisoned,
that is, because of an ordinance made against duels,
etc. and as for their having refused to give security, how untrue this was,
as well as other accusations, may appear from the following certificate.

We whose names are hereunto subscribed, do testify,
that the several particulars in an answer made by our friends, are true,
and that they did not at all disturb the public peace,
nor were they at any other meeting,
(but that which was appointed by us,) to disturb any ministers,
or other Christians in their assemblies and meetings;
nor were they guilty of any challenges, duels, and provocations thereunto,
in the least measure, while they were among us.
And as for their refusal to give security, two of us, whose names are Robert Gary,
and Arthur Cotton, had given security to the mayor,
by entering into recognizance for their appearance at the next sessions,
the day before their sending to prison,
but that the town-clerk made it void the next day,
pretending it could not be according to law.

Ralph Fogg, Thomas Faulkener, Arthur Cotton, Nicholas Cole, Robert Cary, John Martindale,
Richard Smith, Richard Lepincote, Anthony Todde, John Harris, sen.
John Harris, jun.

Now to what a height of confidence the aforesaid mayor.
Page, was come, in saying,
that Thomas Salthouse and Miles Halhead had refused to give bail, no,
that this was the cause of their confinement,
may also appear from the following letter he wrote to general Desborough,
to excuse his proceedings against him.

Plymouth, June 1, 1655.

Right honorable,

Captain Hatsell has communicated to me what you wrote him in reference to those two men,
Thomas Salthouse and Miles Halhead, of whom, and of their imprisonment,
your honor had heard something from some persons of this place,
and received a copy of a letter which they sent me.
By the enclosed copies of their examinations,
your honor will see some part of the cause of their confinement,
which was on their refusal to give bail for their appearance the next general sessions,
to be held for the county of Devon; they being, as I conceive,
offenders within the late ordinance of his highness the lord protector and council,
made against duels, challenges, and all provocations thereunto,
and also his highness`'s late proclamation against Quakers;
and they still refusing to give bail for their appearance as aforesaid,
went from here to the jail at Exon on Tuesday last.
Indeed, sir, their carriage here was not becoming men, much less Christians;
and besides their contempt of authority, all the while they were in prison,
they never sought God by prayer at any time,
nor desired a blessing on any creature they received, or gave thanks for them.
And these very men were about two months past taken up by colonel Cupplestone,
high sheriff of our county, and after fourteen days restraint,
were sent away by him for Taunton, from tithing to tithing, as by their own examination;
and they show no occasion they have to come to these parts.
They are by profession Quakers, but husbandmen by their calling:
one of them is a Lancashire man, the other of Westmoreland; and they left their families,
relations, and callings, about three months since, as they say, and do not work,
nor employ themselves in their calling, to procure themselves a livelihood,
but wander up and down in all parts, to vent their wicked opinions,
and discover their irregular practices in the breach of peace,
and disturbance of good people.
Indeed, sir, they hold many sad opinions, destructive to the true religion,
and the powder of godliness.
I have hereby according to my duty,
given your honor an account of what passed here in reference to these men.
I could say much more in reference to their examination and discourse with them;
but I fear I have already trespassed upon your honor`'s
patience in the perusal of these lines,
and humbly desiring your excuse for giving you this trouble,
do most thankfully acknowledge your honor`'s continued favors to this place,
for which we stand very much obliged,
desiring your honor still to retain such an opinion of us,
as those that desire to do nothing unbecoming Christians,
and persons that desire the welfare and peace of this commonwealth and government,
and shall ever labor to appear

Your honor`'s very humble servant, (For myself and my brethren,)

JOHN PAGE, Mayor.

That General Desborough was but little satisfied with this letter, seems not improbable,
because, inquiring into the matter, he let others have a copy of it,
so that Thomas and Miles wrote an answer to it; and it was also, some time after,
given out in public print at London, by Giles Calvert,
with other writings relating thereunto.
Now as to what is said in this letter of his highness`'s proclamation against Quakers,
it was a gross untruth; for in the proclamation the Quakers were not named;
but it was against the disturbing of Christians in their assemblies; and besides,
the Quakers, so called,
judged that their public worship was permitted them
by the 37th article of the instrument of government,
which said, '`That all that profess faith in God by Jesus Christ,
shall not be restrained from, but be protected in,
the profession of the faith and exercise of their religion,`' etc.
As concerning their contempt of authority the mayor charged them with,
it was nothing else,
but that for conscience sake they could not take off their hats to the magistrates;
neither did they give that honor to any other but God alone.
And as to what was said, that all the while they were in prison,
they never sought God by prayer, etc. this was no other matter,
than that they did not follow the formal way of prayers;
for they were indeed religious men, who often prayed to God, and gave him thanks;
though they were represented in the letter as very wicked men,
and vagabonds that had left their calling, and wandered up and down the country;
although it was well known that they were honest men, and travelled on horseback,
lying at the best inns on the road, and paying for what they received there.
And, therefore, after they had got a copy of the said letter,
they wrote a large letter to the mayor, Page, and showed him his abominable untruths,
and told him, that they had been moved several times in prison, as well as out of prison,
to go to prayers, and to give thanks for the blessings of God which they received.
And in the conclusion of their letter, they signified,
that they would not render railing for railing; but,
(said they,) in the spirit of love and meekness we exhort you all to repent,
and fear to offend the Lord, etc.

Now as concerning the provoking words against George Brooks,
for which they had been fined, it has been said already what they were;
but this Brooks was of a dissolute life, and a debauched fellow,
having for his drunkenness not only been turned out
of the frigates in which he had served,
but also once in the ship Nightingale,
ignominiously exposed with a quarter can about his neck,
as appears by the following testimonies.

I having been formerly desired to relate upon what account it was that Mr. George Brooks,
chaplain of the frigate under my command, was put on shore.
First, because he was a busy body, and disturbed the whole ship`'s company.
Secondly, being on shore, it was his common practice to abuse the creature in such sort,
that he was drunken, void of good reason,
that he would abuse any one that came in his company, by ill language,
besides the abuse of himself and the good creature,
daily complaints coming unto me both aboard and on shore.
Therefore, knowing him to be a debauched fellow, and not fit for that employment,
I put him on shore, and I dare acknowledge it, whoever shall call me to question.
Witness my hand,

ROBERT VESSAY.`'

Mr. Brooks being formerly with me in the Nightingale, I found him to be very idle,
and continually drunk, which once made me to put a quarter can about his neck;
whereunto I subscribe,

JOHN JEFFERY, Captain of the Nantwich.

The person above-mentioned I have seen drunk on shore,
in testimony whereof I have set my hand,

RICHARD POTTER, Captain of the Constant Warwick frigate.

From such evidences as these it appears,
that it was not without reason that he and the like
priests sometimes were treated a little roughly.
But to return to M. Halhead; he continued prisoner many months before he was released.

In the meanwhile it happened that George Whitehead, Richard Clayton, and John Harwood,
coming on the 30th of the month called July, to Bures, in Suffolk,
were imprisoned on this occasion.
R+++.+++ Clayton had set up a paper on the steeple-house door, containing these queries.

Whether setting up such ministers as seek for their gain from their quarters,
such as the prophet disapproves; Isaiah 56:11.
such as the prophet Jeremiah disapproves; Jer. 5. and of whom mention is made also,
Ezek. 34. and Mic. 3. such as are called of men,
masters, loving the chief places in the assemblies;
such as Christ disapproved; Matt, 23.
such as the apostle Peter disapproves, 2 Pet. 2.
and which the apostle Paul disapproved also; Phil. 3.
or when such were set up that would not allow another to speak that stands by,
when any thing is revealed, but send him to prison;
whether this was not the setting up a persecuting spirit, limiting the Spirit of God,
and despising prophecies, not daring to try all things?
Whether it was expedient to give to scoffers, scorners, drunkards, swearers,
and persecutors, David`'s conditions to sing?
And if such were set up that took tithes,
though the apostle said that the priesthood was changed, and the law also, Heb.
vii. Whether by the setting up of such,
they did not set up such as did not labor in the Lord`'s vineyard.

This paper being set up, people came to read it.
G+++.+++ Whitehead being there, and laying hold of this opportunity,
spoke a few words to the people,
and exhorted them to turn to the Lord from the vanities and wickedness they lived in.
And when G. Whitehead and his fellow-travelers were passing away,
there came a constable who stayed them, and carried them before Herbert Pelham,
justice of peace.
He asking several vain questions, and behaving himself rudely,
G+++.+++ Whitehead began to speak to him concerning his rage:
but Pelham said he did not send for him to preach.
And not being able to lay the transgression of any law to their charge,
he sent them by the constable, to Thomas Walgrave, justice of peace at Smallbridge,
in Suffolk.
Being come into his house, Richard Clayton was first examined, of his name and country,
and where he had been.
The same and some other frivolous questions were asked of G. Whitehead.
Then Walgrave asked John Harwood,
if he would answer him all the questions he would demand of him;
but J. Harwood refused to be limited thus to his will.
Justice Pelham now being come there also, J. Harwood told justice Walgrave, that Pelham,
who had before examined him, had his examination in writing.
Then the two justices consulted together what to do in the case;
and not long after Thomas Walgrave asked G. Whitehead, if he would work at hay?
But he denied to be bound to such task-masters,
as being in that calling whereunto God had called him,
and wherein he was chargeable to no man.
The conclusion of their consultation was, that they caused R. Clayton to be whipped,
under pretence of having fastened a seditious paper to the steeple-house;
and the other two were imprisoned.

It was about this time that William Dewsbury,
and several other of his friends were put into prison at Northampton.
It happened that he being at Wellingborough, and going along the streets, the priest,
Thomas Andrews, called to him in these words, '`Give over deceiving the people,
lest the plagues of God fall on you.`'
To this Dewsbury returned, '`Do you say I deceive the people?
Make it manifest wherein I deceive them.`'
Then Andrews said, '`You say there is not any original sin;`' to this Dewsbury replied,
'`Did you hear me say so?
But the priest, unwilling to answer that question, went away.
Afterwards Dewsbury went into the steeple-house in the said town,
and after the sermon was done,
he demanded of the priest that he would prove there before the people,
what he had openly accused him of, namely, that he had said there was no original sin.
Yet the priest would not answer, but went away.
There was also information given, that Dewsbury had said, '`The priests preach for hire,
and the people love to have it so: but what will you do in the end thereof?
But that this was really so, I do not find.

Dewsbury then being committed to prison, and kept there above half a year,
was at last brought to his trial at Northampton, with other prisoners, his friends;
and being set to the bar, the judge, Atkins, said to the jailer,
'`Do you use to bring prisoners before the court in this manner?
You deserve to be fined ten pounds, for bringing them before the court covered.`'
The jailer answered, '`If you command me, I will take off their hats.`'
To which the judge gave command, and the jailer`'s man took them off.
Then the judge said to Dewsbury, '`What are you here for?`'
Dewsbury answered, '`The court order will express what I was committed for;
but a copy of it I am denied by the keeper of the jail.`'
The next query of the judge was, '`What is your name?`'
And the answer was,`' Unknown to the world.`'
'`Let us hear,`' said the judge,`' what name that is, that the world knows not.`'
'`It is,`' quoth Dewsbury, '`known in the light, and none can know it, but he that has it;
but the name the world knows me by, is William Dewsbury.`'
Then said the judge, '`What countryman are you?`'
Dewsbury answered, '`Of the land of Canaan.`'
That is far off,`' replied the judge; '`No,`' said Dewsbury, '`for all that dwell in God,
are in the holy city, New Jerusalem, which comes down from Heaven,
where the soul is in rest, and enjoys the love of God in Jesus Christ,
in whom the Union is with the Father of light.`'
To this the judge returned, '`That is true; but are you ashamed of your country?
Is it a disparagement for you to be born in England?`'
'`No,`' said Dewsbury, '`I am free to declare that my natural birth was in Yorkshire,
nine miles from York, towards Hull.`'
Then the judge said, '`You pretend to be extraordinary men,
and to have an extraordinary knowledge of God.`'
To which Dewsbury replied,
'`We witness the work of regeneration to be an extraordinary work,
wrought in us by the Spirit of God.`'
'`But,`' said the judge, '`the apostles wrought with their hands in their callings.`'
'`They had,`' answered Dewsbury, '`callings in the world, some were fishermen, Paul,
a tent-maker: but when they were called to the ministry of Christ,
they left their callings to follow Christ, where he led them by his Spirit,
to preach the word: and I had a calling in the world, as they had, and in it did abide,
until the Father revealed his Son in me,
and called me from my calling I had in the world,
to preach the eternal word he had made known to me in the great work of regeneration.`'
'`Why,`' queried the judge, '`did you not abide in your own country,
and teach people in those parts?`'
'`There I did stay,`' returned Dewsbury,
'`until I was called from there to go to where I was led by the Spirit of the Lord;
and as many as are led by the Spirit of God, are the sons and daughters of God;
and they that have not the Spirit of Christ are none of his.`'
To this the judge said, '`You say well; for we must in charity conclude,
that everyone in this place has the Spirit of God in him:
but how do you know that you are guided by the Spirit of God?`'
'`They that have the Spirit of God,`' replied Dewsbury, '`are known by their fruits:
and he that believes in Jesus Christ, and is guided by his Spirit,
has the witness in himself.`'
'`That is true,`' said the judge, '`yet notwithstanding, I see by your carriage,
that what my brother Hale did at the last court session,
in requiring bond for your good behavior, he might justly do it;
for you are against magistrates and ministers.`'
But Dewsbury returned, '`Make that manifest wherein we are against them.`'

Then said the judge to the clerk, '`Robert Guy, what have you against these men?
And he gave relation of what Dewsbury had said to priest Andrews in the steeple-house.
Dewsbury then giving an account of the matter of fact, and how the thing happened;
and that it was not any breach of the law of the nation; the judge resumed,
'`But in that you are found wandering in the country, you break the law;
for there is an old law,
that if any did go from their dwellings to travel
in the country without a certificate from some justice,
they were to be taken as wandering persons.
To this Dewsbury said, '`If there be any such law, read it to us;
and if there be such a law, you know in your conscience it is contrary to the scripture;
for the apostles and ministers of Christ went to and fro in the country,
preaching the word of eternal life;
and there were added to the church daily such as should be saved;
and the number of the saints and brethren daily increased;
and the law that is in force in this nation,
does allow all who profess faith in Jesus Christ,
to have free liberty to walk in the faith, which is according to Scripture.`'
To this the judge said, '`You have an eloquent tongue, and you are proud of it.`'
'`Pride I deny,`' replied Dewsbury, '`but the Truth I witness, which will judge pride,
and torment all that live in it, until it be destroyed.`'
The judge then spoke to the other prisoners; and though he behaved himself moderately,
yet he could not resolve to set them at liberty; but they were continued in prison,
though they had been kept there above twenty-nine weeks.

One of these prisoners was John Huchin, whom they had nothing else to charge with,
but that being come into the steeple-house at Wellingborough,
he stood there peaceably in silence, but before half the sermon was over,
priest Andrews commanded to have him taken away; which was done by the church-warden,
Henry Hensnan, who carried him to an alehouse, where it was told him by the constable,
that if he would not come into the church in the afternoon he should be set free.
But he refusing to make such a promise, though they let him alone then,
yet some days after, a constable came to his master`'s shop, where he was working,
and took him away without showing any warrant.

Another of the prisoners was Michael Pattison, who having been in the same steeple-house,
and stood peaceably in silence until priest Andrews had done,
and the people were going away, said to him, '`Friend,
can you witness this to be the word of the Lord,
that you have spoken here before the people?
But this so offended the priest, that he commanded the officers to take Michael away,
which the constable, John Brown, did.

Thomas Goodyear, who was also one of`' the prisoners, being come to Northampton,
to visit his friends in prison there, it was denied him by the jailer;
and he meeting the mayor and some aldermen in the streets,
spoke to them about persecution; but one of the aldermen struck off his hat,
and said he would teach him better manners,
than to stand and talk before the mayor with his hat on.
Then they required sureties for his good behavior; and he told them,
that he was bound to good behavior by the righteous law of God`';
and refusing to find sureties, he was taken up in the street,
and sent to prison without court order, or further examination.
But I will not detain my reader any longer with these prisoners;
for if I should relate all occurrences of this nature that are come to my knowledge,
and under what unreasonable pretences,
even such that were as yet not fully entered into the communion of those called Quakers,
were committed to prison, I must write much more than I might be able to do,
though my life should yet be lengthened considerably.

I find among my papers of this time, the names of about a hundred persons, who,
for not paying tithes to the priests, and refusing to swear,
suffered either by seizure of their cattle and goods, or imprisonment.
Thomas Aldam, for not paying of tithes to the priest Thomas Rookby, of Warnsworth,
was imprisoned at York in the year 1652, where he was kept above two years and a half,
and besides had thirteen beeves and two horses taken from him.

But passing by a multitude of the like cases, I return again to G. Fox,
whom I left at London.
He, having had there several large meetings, went from there to Colchester, where,
with difficulty he visited James Parnel in prison.
From Colchester he went to Ipswich, and so on to Norwich and Yarmouth,
finding service everywhere.

Travelling further, in company with R. Hubberthorn, towards Lynn,
and by the way being in bed at an inn, a constable and officers came there,
being sent with a hue and cry from a justice of peace,
to search for two horsemen that rid upon grey horses and in grey clothes;
a house being broken up at night, as was reported.
Now though they said they were honest and innocent men,
yet a guard with halberds and pikes was set upon them that night,
and in the morning they were carried before a justice of peace about five miles off.
The justice grew angry because they did not put off their hats to him:
but G. Fox told him, he had been before the protector,
and he was not offended at his hat; why then should he be offended at it,
who was but one of his servants?
The justice, having examined them, said,
he believed they were not the men that had broken open the house;
but he was sorry that he had no more against them.
But G. Fox told him, he ought not to be sorry for not having evil against them;
but rather to be glad.
The justice, though stirred up by the constable to send them to prison, yet let them go.
G+++.+++ Fox being thus set at liberty, travelled on to Lynn, from which he went to Sutton,
where he had a great meeting, many people from other places being come there,
and also the mayor`'s wife of Cambridge;
and many hundreds were convinced of the truth he preached.
From there he passed to Cambridge, and though the scholars were exceeding rude,
yet he got safe into an inn.
In the dark of the evening, the mayor of the town came, and fetched him to his house,
where some friendly people were sent for, and he had a meeting there.
Next morning he departed the town and returned to London, where he stayed some time.

In this year came out the oath of abjuration against King Charles,
whereupon he wrote to the protector, acquainting him, that many of his friends,
who could not swear for conscience sake, suffered much on this account.

From London he went to Leicestershire, and coming to Whetstone,
where formerly he had been taken by colonel Hacker, he now had a great meeting,
to which Hacker`'s wife, and his marshal came, and they, besides many more,
were convinced of G. Fox`'s ministry:
who going from there after having passed through many places, came again to London,
where meeting James Nayler, and casting his eyes upon him,
he was struck with a fear concerning him; being, as it were,
under a sense of some great disaster that was like to befall him.

In this year Edward Burrough wrote a letter to the protector, wherein he told him,
that the Lord`'s controversy was against him,
because he had not been faithful in God`'s work;
but that he had taken his rest and ease upon a lofty mountain of pride and vain glory;
having set up himself to be worshipped, and exalting his own horn,
without giving glory and honor to God.
Moreover, that he had not performed his vows made to the Lord in the day of distress;
and that now he suffered grievous oppression, cruelty,
and tyranny to be acted in his name, by unjust imprisonments,
and persecution of the Lord`'s people.
That therefore the Lord would bring his judgments upon him, except he did repent.
How boldly soever Burrough wrote in this letter to Cromwell,
yet I do not find that he showed himself angry because of it;
but yet he hearkened too much to the flatteries of those teachers, who,
being now entered into the possession of the Episcopalians, exalted him as their idol,
by their applause.
And he revering them as such who could strengthen his authority with the people,
winked at the grievous persecution, by their instigation carried on against the Quakers,
so called.

In the meanwhile there were many malcontents,
who could not bear that Cromwell should force the members of parliament
to consent to make no change in the government then established,
and would not permit any one to sit in the house, without having promised by writing,
not to oppose, or give his consent there, to the change of the said government.
This gave occasion, that even some of those who had been his eminent friends,
now did not hesitate to reprove him sharply.

Among these was lieutenant-colonel John Lilburn, who being an extraordinary bold man,
very stiff and inflexible,
had more than once showed himself a public asserter of the people`'s liberties and freedoms;
for which he had been prosecuted at law; once in the year 1645,
when he was imprisoned as guilty of treason, but was discharged; and afterwards,
in the year 1649, when, having published several books,
to expose to the public the arbitrary power he thought was exercised in the government,
he was confined in the tower: and, after having been prisoner about seven months,
was impeached of high treason.
But he so vigorously defended his cause,
that though strong persuasions had been used to move the jury to bring him in guilty,
yet he so far prevailed, that at length he was set at liberty again:
though I find that once he was whipped for a crime laid to his charge,
of which he gloried publicly.
And when Cromwell had usurped the supreme power, Lilburn made bold to charge him,
both by word of mouth, and by writing, with falseness and tyranny;
and he went on at that rate, that Cromwell,
foreseeing that if this man continued thus to expose his doings,
he should not be able to maintain his credit and authority,
ordered him to be taken into custody, and impeached of high treason.
When Lilburn, thus accused, appeared at the bar,
he behaved himself with that undaunted-ness, and so defended his cause,
that he seemed less to plead for his life, than for the freedom of his country; and,
boldly answering what was objected to him,
said that what he had done was not only no high treason; but the government was such,
that no high treason could be committed against it;
and that therefore all true Englishmen were obliged to oppose the tyranny that was exercised.
He also said that having been once in favor with Cromwell,
he might have attained to great preferment, if he would have been quiet;
but that he having thought this unlawful,
it was now resolved to have his life taken away; which he did not fear,
because he asserted a good cause.
Thus vigorously Lilburn pleaded, and he defended his cause with such strong arguments,
that the jury brought him in not guilty,
notwithstanding the endeavors of the judges to the contrary.

Now, though according to law, he must have been set at liberty,
yet Cromwell would not consent to it, but kept him prisoner:
and because he indeed feared him, as one that would weaken his government,
he ordered him to be carried from one prison to another;
till at length he came to be confined in the castle of Dover,
in which town lived Luke Howard, mentioned before;
who thereby having occasion to speak with Lilburn concerning religion,
gave him such convincing reasons for his professions,
as prevailed upon Lilburn to receive the Truth;
as he himself signified in a letter he wrote to his wife;
who having visited him in prison, afterwards wrote to him this following exhortation.

My dear,

Retain a sober patient spirit within you,
which I am confident you shall see shall be of more force to recover you,
than all your keen metal has been.
I hope God is doing a work upon you and me too,
as shall make us study ourselves more than we have done.

These words were so acceptable to Lilburn, that repeating them in his letter to her,
he answered thus, after many other passages.

O, my dear love!
I am deeply already entered into my part of it:
the mighty power of God enable you to get in too, and also to go through yours,
and effectually to go cheerfully and willingly along hand in hand with me,
which would render you abundantly more amiable, lovely, and pleasant in my eyes,
although you were then clothed in rags, than you could be to me in the drawing back,
or standing still where you were when I last saw you,
though therein you were clothed all over with rich
and outwardly glistering earthly diamonds,
and in the greatest of earthly prosperity.
I am sorry you are so straitly put to it for money; but to live upon God by faith,
in the depth of straits, is the lively condition of a Christian.
O that your spirit could attain unto this, according to your desire in your letter,
and my own present frame of spirit!
I now can contentedly feed savourily upon bread and cheese, and small beer alone,
for saving of money.
And for my liberty, about which you so weariest and spend yourself,
as your letter acquaints me you do, can say to you,
that I am in my present temper of spirit, ready really with Peter,
at the sight of the glorious transfiguration of Christ, to say, it is good being here.
For here in Dover Castle, through the lovingkindness of God,
I have met with a more clear, plain, and evident knowledge of God and myself,
and his gracious outgoings to my soul, than ever I had in all my lifetime,
not excepting my glorying and rejoicing condition under
the bishops.--And now submissively and heartily I can say,
the will of my heavenly Father be done in me, by me, and for me;
in whose will I leave you and yours, with all your and my friends,
and rest yours in the strength of renewedness of true love,

JOHN LILBURN

From Dover Castle,
the place of the present enjoyed delightful dispensation of the eternal,
everlasting love of God unto my soul.
The 4th of the Tenth Month, 1653.

While Lilburn was prisoner here, Cromwell, as it seemed, would have released him,
if he would have signed a declaration that he would never draw a sword against his government.
But Lilburn as yet not being fully convinced,
that to refrain from the use of the carnal sword, was the duty of a true Christian,
refused; thinking that though G. Fox had signed such a declaration,
yet this did not become him,
because he did not perfectly approve that point of self-denial.
But however, continuing in faithfulness,
to persevere in respect of that knowledge he had already attained to, he became,
in process of time, such an asserter of the true Christian life, that in a paper,
which at his desire was given out in print, he expressed himself thus:

I have now the faithful and true witness in my own soul, that the Lord himself is become,
within me, the teacher of my soul,
and enabler of me to walk in a measure of his pure ways and paths; yes,
and so clear a teacher within me is he already become unto me,
as that I with confidence believe my inward teacher
shall never now more be removed into a corner;
but is, and shall be, as a continual voice speaking in my ears, "`This is the way,
walk in it:`" by which divine teaching, I am now daily taught to die to sin,
and led up by it into living power, to be raised up,
and enabled to live in a pure measure of righteousness;
and by which inward spiritual teachings, I am, I say again, led up into power in Christ,
by which I particularly can, and do hereby witness, that I am already dead,
or crucified to the very occasions, and real grounds of all outward wars,
and carnal sword-fightings, and fleshly bustlings and contests;
and that therefore confidently I now believe,
I shall never hereafter be a user of a temporal sword more,
nor a joiner with those that so do.
And this I do here solemnly declare, not in the least to avoid persecution,
or for any political ends of my own,
or in the least for the satisfaction of the fleshly wills of any of my great adversaries,
or for satisfying the carnal will of my poor weak afflicted wife;
but by the special movings and compulsions of God now upon my soul,
am I in truth and righteousness compelled thus to declare;
that so I may take away from my adversaries, all their fig-leaf covers, or pretences,
for their continuing of my every way unjust bonds.
And that thereby, if yet I must be an imprisoned sufferer, it may from this day forward,
be for the Truth as it is in Jesus;
which Truth I witness to be truly professed and practised
by the savouriest of people called Quakers.

And to this my present declaration,
which I exceedingly long and earnestly desire to have in print,
and for which I know that I can cheerfully and assuredly lay down my life,
if I be called to witness the truth of it, I subscribe my name,

JOHN LILBURN.

From my innocent and every way causeless captivity in Dover Castle,
the place of my soul`'s delightful and contentful abode,
where I have really and substantially found that
which my soul many years has sought diligently after,
and with unsatisfied longingness thirsted to enjoy: this present First-day of the week,
being the 4th of the Third Month, 1635.

It sufficiently appears by this,
that Lilburn did not think that this declaration would procure his liberty;
and he guessed not wrong; for before he was released, Cromwell died.
Lilburn being then discharged from his confinement,
continued steadfast to the doctrine of the Truth he had embraced,
and died at London in the year 1660.
But being advanced in the time, I go therefore back a little,
and intend in the sequel to give a more circumstantial description of Cromwell`'s death.

And thus I conclude this book with the year 1655,
in which year there was a plot of the royalists against Cromwell;
and in Nottinghamshire they had already surprised some places;
and towards the West the city of Salisbury.
The young king, (Charles,) was now come from Cologne into Zealand,
to be the nearer if the attempt succeeded.
But his time of ruling was not yet come;
for the cavaliers were soon forced to give way to the power of Cromwell:
and the design being thus squashed, king Charles returned to Cologne.
In the meanwhile, Cromwell, to raise his esteem abroad, sent a fleet, under admiral Penn,
to the West Indies, and another, under the command of admiral Blake,
towards the Mediterranean sea.
