== Chapter VI.

=== 1656.

[.chapter-synopsis]
* Convincement of William Baily
* The laughing Captain
* Major Ceely and Geo. Fox
* Trial of G. Fox before Judge Glyn
* G. Fox charged with conspiracy to raise 40,000 men
* Doomsdale Prison
* Quakers whipped as vagabonds
* Retribution on a cruel Jailor
* S. Fisher`'s attempt to speak before Parliament
* Cruel treatment of H. Smith, A+++.+++ Rigg, and F. Robinson
* W. Caton and W. Ames in Holland
* Extravagances of some called Quakers in Holland
* History of J. Nayler
* His cruel punishment
* Petition to Parliament on his account
* His recantation and penitence
* Acknowledgment to his brethren
* His restoration

Near the beginning of the year 1656, G. Fox went from London to Surry, Chichester,
Portsmouth, and Pooel; where Willam Baily, a Baptist teacher, and some others,
were convinced by G. Fox`'s ministry,
and entered into the society of those called Quakers; among whom,
Baily afterwards became an eminent minister.
From Poole, G. Fox went to Southampton, and Dorchester,
where he desired of the Baptists to have their meetinghouse to meet in;
but they refusing, he sent them word, that they might come to his inn, if they pleased.
Many of them came, with their teacher, and they fell into a discourse about water-baptism.
G+++.+++ Fox asked them, whether they could say they were sent of God to baptize people,
as John was; and whether they had the same spirit and power, that the apostles had.
They said they had not.
Then he asked them, how many powers there are.
Whether there are any more than the power of God, and the power of the devil;
and they said, there was not any power than those two.
Then said G. Fox, '`If you have not the power of God, that the apostles had,
then you act by the power of the devil.`'
And his speaking was of such effect,
that many substantial people were convinced that night.
Next morning when he was passing away,
the Baptists began to shake the dust from off their feet after him.
'`What, said he, in the power of darkness?
We who are in the power of God, shake off the dust of our feet against you.`'

Leaving Dorchester, he came to Weymouth, where, inquiring after the sober people,
about fourscore of them gathered together at the priest`'s house,
and most of them were turned to Christ Jesus,
who had enlightened them with his divine light,
by which they were reproved of their sins.
There was at that time a captain of horse in the town,
who rode about seven miles out of town with G. Fox.
This captain was of such a merry temper, and so exceedingly given to laughter,
that G. Fox several times spoke very seriously to him about it;
but it was become so customary to him that he would laugh almost at any thing he saw.
But G. Fox still admonished him to gravity, and the fear of the Lord;
and of this he spoke to him again when they parted.
The next time G. Fox saw him, the captain told him, that when he spoke to him at parting,
the power of the Lord so struck him, that before he got home he was serious enough,
and had left his laughing.
He indeed became a serious and good man; and being convinced of the Truth,
died in the real profession thereof.

For brevity`'s sake I do not intend to mention all the places G. Fox passed through,
much less all his occurrences.
At Kingsbridge he had good service; and returning in the evening to his inn,
and there being many people drinking, he was moved to go among them,
and to direct them to the light which Christ, the heavenly man,
had enlightened them withal; by which light they might see all their evil ways, words,
and deeds; and by the same light they might also see Christ Jesus their Savior.
But this discourse did not please the innkeeper,
seeing it hindered his guests from drinking:
and hearing G. Fox speak so much of the light, he snatched away the candle, and said,
'`Come, here is light for you to go into your chamber.`'

The next day, G. Fox went to Plymouth, and from there to Cornwall;
and travelling through the country, he came to Market-Jew.
Being there at an inn, he met with some trouble from the magistrates:
and he wrote a paper to show, that the Lord was come to teach his people himself,
by Jesus Christ, etc.
This paper came accidentally to the hands of Peter Ceely, a major in the army,
and also a justice of peace at Ives, where G. Fox came.
Here Edward Pyot and William Salt, who were G. Fox`'s fellow travellers,
were hauled before the said major, while G. Fox was walking down to the sea-side:
but he hearing this, followed them, and came also into the justice`'s house,
where the aforesaid paper being produced, it was asked him,
whether he would acknowledge it: and he said, '`Yes.`'
Then the major tendered them the oath of abjuration,
G+++.+++ Fox thereupon putting his hand in his pocket, drew forth the answer to it,
which had been given to the protector.
A priest being present there, found fault with his hair, which then was pretty long,
and asked to have cut it; but G. Fox told him, he had no pride in it.
It happened also at other times, that because of his long hair he was spoken to,
as I have seen myself; but of this I am fully persuaded,
that he had not the least pride in it; but it seems to me not improbable, that he,
seeing how some would make it a kind of holiness to wear short hair,
did the contrary to show that, in some things, there was a Christian liberty,
for which we ought not to judge one another.
But to proceed, G. Fox and his companions were taken into custody,
and with a guard of horse sent to prison with this court order.

[.embedded-content-document.legal]
--

[.blurb]
Peter Ceely, one of the justices of the peace of this county,
to the keeper of his highness`'s jail at Launceston,
or his lawful deputy in that behalf greeting.

I send you herewithal by the bearers hereof, the bodies of Edward Pyot, of Bristol,
and George Fox, of Drayton and Clay, in Leicestershire, and William Salt, of London,
which they pretend to be the places of their habitations,
who go under the notion of Quakers, and acknowledge themselves to be such;
who have spread several papers, tending to the disturbance of the public peace,
and cannot render any lawful cause of coming into these parts,
being persons altogether unknown,
and having no pass for their travelling up and down the country,
and refusing to give sureties of their good behavior,
according to the law in that behalf provided, and refuse to take the oath of abjuration, etc.
These are therefore, in the name of his highness, the lord protector,
to will and command you, that when the bodies of the said Edward Pyot, George Fox,
and William Salt, shall be unto you brought, you them receive,
and in his highness`'s prison aforesaid you safely keep them,
until by due course of law they shall be delivered.
Hereof fail you not, as you will answer the contrary at your peril.
Given under my hand, and seal, at St. Ives, the 18th day of January, 1656.

[.signed-section-signature]
P+++.+++ Ceely.

--

By this court order it appears under what odd pretences the Quakers, so called,
were committed to prison; for such reasons as are mentioned therein,
might be found and picked up at any time.
Thus G. Fox and his companions were carried through Redruth, Falmouth, and Bodmin,
to Launceston.
By the way they suffered great insolence, both from the soldiers that conducted them,
and from others, by the connivance of captain Keat;
but I will not detain my reader with all those particulars.
Being come to Launceston, Keat delivered the prisoners to the jailed.
And though many were greatly enraged against them, and expected that these prisoners,
who _thee`'d_ and _thou`'d_ all, and did not put off their hats to any man,
should at the court session be condemned to be hanged
if they did not pay that respect to the bench;
yet there were many friendly people, out of several parts of the country,
that came to visit them;
for it was about nine weeks from the time of their commitment to the court session:
by reason of which several got opportunity to speak with them,
which had that good effect,
that many were convinced of the truth of the doctrine held forth by them.

At the time of the court session, abundance of people came from far and near,
to hear the trial of the Quakers; who being guarded by the soldiers,
and the sheriff`'s men to the court,
had much ado to get through the multitude that filled the streets:
besides the doors and windows were filled with people looking out upon them.
Being brought into the court, G. Fox after all was quiet, said, '`Peace be among you.`'
The judge, (Glyn,) who was then chief justice of England, said to the jailer,
'`What be these you have brought here into the court?
'`Prisoners, my lord,`' said he.
'`Why do you not put off your hats?`'
said the judge to them.
They saying nothing; '`Put off your hats,`' said the judge again;
and they still continuing silent, the judge said,
'`The court commands you to put off your hats.`'
Then G. Fox began to speak, and said, '`Where did ever any magistrate, king, or judge,
from Moses to Daniel, command any to put off their hats,
when they came before them in their courts, either among the Jews,
(the people of God,) or among the heathen?
And if the law of England does command any such thing,
show me that law either written or printed.`'
The judge, then growing angry, said, '`I do not carry my law books on my back.`'
'`But,`' said G. Fox, '`where is it printed in any statute-book, that I may read it?`'
At this the judge said, '`Take him away, prevaricator!
I`'ll ferk him.`'
Then the prisoners were taken away, and put among the thieves,
But presently after the judge called to the jailer, '`Bring them up again.`'
This being done, '`Come,`' said he, '`where had they hats from Moses to Daniel? Come,
answer me; I have you fast now.`'
To this G. Fox replied, '`You may read in the third of Daniel,
that the three children were cast into the fiery furnace, by Nebuchadnezzar`'s command,
with their coats, their hose, and their hats on.`'
This plain instance stopped him: so that not having any thing else to say,
he cried again, '`Take them away jailer.`'
Accordingly they were taken away, and being thrust among the thieves,
they were kept there a great while, and at length carried again to prison;
but in the afternoon they were brought up again into the court.

G+++.+++ Fox seeing the jurymen there, gave them a paper, which he had written against swearing.
This paper passing from the jury to the justices, they presented it to the judge;
and he bid the clerk give G. Fox that paper,
and then asked him whether that seditious paper was his:
to which he said if they would read it in open court, that he might hear it,
if it was his, he would acknowledge it, and stand by it.
The judge would have G. Fox to have taken it, and looked upon it in his own hand.
But he desired again that it might be read, that all in the court might hear it,
and judge whether there was any sedition in it, or no; for if there were,
he was willing to suffer for it.
At length the clerk of the court session read it with an audible voice;
and when he had done, G. Fox said it was his paper, and he would acknowledge it;
and so might they too, except they would deny the Scripture;
for was it not Scripture language, and the words and commands of Christ and the apostles,
which all true Christians ought to obey.
Then they let fall that subject,
and the judge speaking again about the hats of the prisoners,
bid the jailer take them off.
Then they asked what they had lain in prison for these nine weeks,
seeing now nothing was objected against them, but what concerned their hats:
'`And,`' said G. Fox, '`as for putting off our hats,
that was the honor which God would lay in the dust,
though they made so much ado about it: the honor which is of men,
and which men seek one of another, is the mark of unbelievers: for,
"`How can you believe,`" says Christ, "`who receive honor one of another,
and seek not the honor that comes from God only?`"
And Christ says also, "`I receive not honor from men.`"
And all true Christians should be of his mind,`' Then the judge make a speech,
how he represented the lord protector`'s person;
and how he made him lord chief justice of England, and sent him to come that circuit, etc.
Thereupon the prisoners desired him,
that he would do them justice for their false imprisonment,
which they had suffered nine weeks.

But instead thereof, an indictment was read against them, but so full of untruths,
that G. Fox thought it had been against some of the thieves: for it contained,
that they came by force of arms, and in a hostile manner, into the court;
whereas they were brought there as prisoners; which made him say it was all false.
And still they cried for justice for their false imprisonment,
being taken up in their journey without cause, by major Ceely.
Then this Peter Ceely, who, as a justice of peace, sat also on the bench,
said to the judge, '`May it please you, my lord, this man,
(pointing to G. Fox,) went aside with me,
and told me how serviceable I might be for his design;
that he could raise forty thousand men at an hour`'s warning,
and involve the nation in blood, and so bring in king Charles;
and I would have aided him out of the country, but he would not go.
And if it please you, my lord, I have a witness to swear it.`'
And so he called upon his witness, who, without question, was one that was bribed.
But the judge, perceiving this palpable lie, was not forward to examine the witness:
then G. Fox desired the judge that he would be pleased to let his court order be read,
in which the pretended crime was signified, for which he was committed to prison.
But the judge said it should not be read: G. Fox still insisting to have it read, said,
'`It ought to be; for if I have done any thing worthy of death, or of bonds,
let all the country know it.`'
Seeing then they would not read it, he said to one of his fellow-prisoners,
'`You have a copy of it; read it up.`'
'`It shall not be read,`' said the judge; '`jailer, take him away;
I will see whether he or I shall be master.`'

Then G. Fox was taken away, and awhile after called for again.
He still cried to have the court order read; and the people being eager to hear it,
he bid his fellow-prisoner read it up; which being done,
and read according to the copy already mentioned, G. Fox said to the judge and justices,
'`You that say you are chief justice of England, and you that be justices, you know,
that if I had put in sureties, I might have gone where I pleased,
and have carried on the design, if I had one, which major Ceely has charged me with.
And if I had spoken these words to him, which he has declared, then judge you,
whether bail or mainprise could have been taken in that case.`'
Then directing his speech to major Ceely, he said, '`When or where did I take you aside?
Was not your house full of rude people,
and you as rude as any of them at our examination, so that I asked for a constable,
or other officer, to keep the people civil?
But if you are my accuser, why do you sit on the bench?
That is not a place for you to sit in; for accusers do not use to sit with the judges:
you ought to come down, and stand by me, and look me in the face.
Besides, I would ask the judge and justices this question,
whether or no major Ceely is not guilty of this treason, which he charges against me,
in concealing it so long as he has done?
Does he understand his place, either as a soldier or a justice of the peace?
For he tells you here, that I went aside with him,
and told him what a design I had in hand; and how serviceable he might be for it:
that I could raise forty thousand men in an hour`'s time, and bring in Charles,
and involve the nation in blood.
Moreover, that he would have aided me out of the country, but I would not go;
and therefore he committed me to prison for lack of sureties for the good behavior,
as the court order declares.
Now do not you see plainly,
that major Ceely is guilty of this plot and treason that he talks of,
and has made himself a party to it, by desiring me to go out of the country,
and demanding bail of me; and not charging me with this pretended treason till now,
nor discovering it?
But I deny and abhor his words, and am innocent of his devilish design.`'

The judge by this seeing clearly that Ceely, instead of ensnaring G. Fox,
had ensnared himself, let fall that business.
But then Ceely got up again, and said to the judge, '`If it please you, my lord,
to hear me: this man struck me, and gave me such a blow, as I never had in my life.`'
G+++.+++ Fox smiling at this, said, '`Major Ceely, are you a justice of peace,
and a major of a troop of horse,
and tells the judge here in the face of the court and country, that I, who am a prisoner,
struck you; and gave you such a blow, as you never had the like in your life?
What! are you not ashamed?
Prithee, major Ceely, where did I strike you; and who is your witness for that?
Who was by?`'
To this Ceely said it was in the castle-green,
and that captain Bradden was standing by when G. Fox struck him;
who then desired the judge to let him produce his witness for that:
and he called again upon Ceely, to come down from off the bench;
telling him it was not fit that the accuser should sit as judge over the accused.
Ceely then said, captain Brad-den was his witness:
which made G. Fox say to captain Bradden, who was present there,
"`Did you see me give him such a blow, and strike him as he says?
Bradden made no answer, but bowed his head.
G+++.+++ Fox then desired him to speak up, if he knew any such thing:
but he only bowed his head again.
'`No,`' said G. Fox, '`speak up, and let the court and country hear,
and let not bowing of the head serve the turn.
If I have done so, let the law be inflicted on me.
I fear not sufferings, nor death itself;
for I am an innocent man concerning all his charge.`'
But Bradden would not testify to it.
And the judge, finding those snares would not hold, cried, '`Take him away,
jailer;`' and fined the prisoners twenty marks apiece, for not putting off their hats,
and to be kept in prison till they paid their fine:
and so they were brought back to jail again.

At night captain Bradden came with seven or eight justices to see them:
and they being very civil, said, they did not believe that either the judge,
or any in the court, believed those charges which major Ceely had made upon G. Fox.
And Bradden said, major Ceely had an intent to have taken away G. Fox`'s life,
if he could have got another witness.
'`But,`' said G. Fox, '`captain Bradden, why did not you witness for me, or against me,
seeing major Ceely produced you for a witness, that you saw me strike him?
and when I desired you to speak either for me, or against me,
according to what you saw or knew, you would not speak.`'
'`Why,`' said he, '`when Major Ceely and I came by you,
as you were walking in the castle-green, he put off his hat to you, and said,
how do you do, Mr. Fox?
Your servant, sir.
Then you said to him, major Ceely, take heed of hypocrisy, and of a rotten heart;
for when came I to be your master, or you my servant?
Do servants use to cast their masters into prison?
This was the great blow he meant that you gave him.`'
G+++.+++ Fox hearing this, called to mind, that they walking by,
Ceely had spoken the aforesaid words, and that he himself indeed made such an answer,
as is mentioned; and he thought he said nothing amiss,
since Ceely so openly had manifested his hypocrisy and rotten-heartedness,
when he complained of this to the judge in open court, and would have made all believe,
that G. Fox gave him a stroke outwardly with his hand.
A report of this trial being spread abroad, many people,
of whom some were of account in the world,
came far and near to see him and his friends in prison,
which tended to the convincement of some.

Being settled in prison upon such a commitment,
that they were not likely to be soon released,
they forbore giving the jailer seven shillings a week apiece for themselves,
and as much for their horses, which he had in a manner extorted from them:
but upon this he grew so very wicked,
that he turned them down into a nasty stinking place where
they used to put persons condemned for witchcraft and murder.
This place was so noisome, that it was observed few who went into it,
did ever come out again in health: for there was no outhouse in it,
and the excrement of the prisoners that from time to time had been put there,
had not been carried out for many years; so that it was all like mire,
and in some places to the top of the shoes;
and the jailer would not allow them to cleanse it,
nor let them have beds or straw to lie on.
At night some friendly people of the town brought them a candle and a little straw;
of which they were about to burn a little to take away the stink.
The thieves lay over their heads, and the head jailer in a room by them,
over their heads also.
But it seems the smoke went up into the room where he lay,
which put him into such a rage, that he took the pots of the thieves`' excrement,
and poured them down through a hole upon their heads; whereby they were so bespattered,
that it was loathsome to touch themselves, or one another:
besides the stink so increased, that by it, and the smoke,
they were almost in danger of being suffocated.
And all this could not satisfy the rage of this cruel jailer,
but he railed against them so hideously, and called them such horrible nicknames,
that they never had heard the like before.
In this manner they were forced to stand all night, for they could not sit down,
the place being so filthy.
Thus he kept them a great while, before he would let them cleanse it,
or allow them to have any food brought in, but what they got through the grate.
And even this could not be done without difficulty;
for a lass one time having brought them a little food,
he sued her in the town-court for breaking the prison; perhaps,
because she had a little bent a half-broken bar of the grate,
to get a small dish through it.
That this jailer was so desperately wicked, is not so much to be wondered at, since,
as they were informed, he had been a thief,
and was on that account burnt both in the hand and on the shoulder;
and the under-jailer in like manner: their wives had also been burnt in the hand.
It was not at all strange, then,
that the prisoners suffered most grievously from such a wicked crew;
but it was more to be wondered at, that colonel Bennet, a Baptist teacher,
having purchased the jail and lands belonging to the castle,
had there placed this head-jailer.

It was much talked of, that spirits haunted this dungeon, and walked there,
and that many had died in it; some thinking to terrify the prisoners therewith.
But G. Fox told them, that if all the spirits and devils in hell were there,
he was over them in the power of God, and feared no such thing; for Christ, their priest,
would sanctify the walls and the house to them; he who bruised the head of the devil;
as the priest was to cleanse the plague out of the walls of the house under the law.

Now the time of the sessions at Bodmin being come,
the prisoners drew up their suffering case, and sent the paper there;
upon reading of which, the justices gave order, that the door of Doomsdale,
(thus the dungeon was called,) should be opened,
and that they should have liberty to cleanse it, and to buy their food in the town.
Having obtained this liberty, they wrote to London, and desired Anne Downer,
a young woman already mentioned in this work, to come down,
and to buy and dress their food: which she being very willing to do,
was therein greatly serviceable to "`them; for she was a good writer,
and could take things in shorthand.
They also sent up a relation of their sufferings to the protector;
who thereupon sent down an order to the governor of Pendennis Castle,
to examine the matter.
On which occasion Hugh Peters, one of the protector`'s chaplains,
told him they could not do George Fox a greater service for the
spreading of his principles in Cornwall than to imprison him there.
This was not altogether untrue, for he was much visited,
and many were turned from darkness to the light;
notwithstanding the mayor of Launceston was a fierce persecutor,
casting in prison all he could get;
and he did not hesitate to search substantial grave women, for letters, as supposed.

In Devonshire it was not much better; for many of those called Quakers,
that travelled through the country, were taken up and whipped,
under pretense of being vagabonds: no, some clothiers,
that were going to mill with their cloth, and other substantial men,
were seized and whipped; and Henry Pollexfen,
who had been a justice of peace for the most part of forty years before,
was cast into prison, under presence of being a Jesuit.

In the meanwhile Edward Pyot, who had been a captain,
and was a man of good understanding in the laws and rights of the nation,
wrote a large letter to the lord chief justice John Glyn,
wherein he plainly set before him his unlawful dealings; and queried with him,
whether his saying if you will be uncovered, (or put off your hats,) I will hear you,
and do you justice,
was not an overthrow of the laws that were made to maintain right and justice.
Many other particulars, and among the rest,
that of G. Fox`'s striking major Ceely were also mentioned in this letter.
G+++.+++ Fox himself wrote also several papers,
wherein the odiousness of persecution was plainly set forth.

Among those that came to visit him was Thomas Lower, a doctor of medicine at London; who,
while I am writing this, is yet alive: and he,
asking many questions concerning religious matters,
received such satisfactory answers from G. Fox,
that he afterwards said his words were as a flash of lightning, they ran so through him;
and that he never met with such wise men in his life, etc.
Thus he came to be convinced of the Truth,
and so entered into the communion of the despised Quakers.
While G. Fox was still in prison, one of his friends went to Oliver Cromwell,
and offered himself body for body, to he in Doomsdale prison in his stead,
if he would take him, and let G. Fox go at liberty.
But Cromwell said he could not do it, for it was contrary to law:
and turning to those of his counsel, '`Which of you,`' quoth he, '`would do so much for me,
if I were in the same condition?`'

Thus G. Fox continued in prison,
and it was yet a good while before he and his fellow-prisoners were released.
The next year the wicked jailer received a recompense of his deeds;
for he was turned out of his place, and for some wicked act was cast into jail himself;
and there his carriage was so unruly, that he was, by the succeeding jailer,
put into Doomsdale, locked in irons, and beaten,
and bid to remember how he had abused those good men, whom he had wickedly,
without any cause, cast into that nasty dungeon;
but that now he deservedly should suffer for his wickedness;
and the same measure he had meted to others, he should have meted out to himself:
and this mischievous fellow, who might have grown rich if he had carried himself civilly,
grew now very poor, and so died in prison.

About the same time that G. Fox was released, Cromwell called a parliament,
which met for the first sitting, in the painted chamber at Westminster,
on the 17th of the month called September.
Samuel Fisher got an opportunity to come into this assembly,
where he heard the protector`'s speech, and in it these words,
'`that he knew not of any one man that had suffered imprisonment unjustly in all England.`'
And after he had got the convenience of a standing,
he said that he had a word to speak from the Lord to the protector, to the parliament,
and the people, and then he began thus:

[quote]
____
The burden of the word of the Lord God of heaven and of earth,
as it came unto me on the 22nd day of the last month,
and as it now lies upon me to declare it in his name, even unto you, Oliver Cromwell,
protector, (so called,) of these three nations, England, Scotland, and Ireland;
and also to all you who are chosen out of the several
parts thereof to sit in parliament this day,
to consider of such things as concern the commonwealth thereof;
and likewise to the three nations themselves, and all the people thereof,
whose rulers and representatives you are: which word of the Lord,
as you do not deem yourselves too high, or too great, or too good,
to be spoken to from the Lord;
and as you will not fall under the guilt of that sin of saying to the seers.
See not, and to the prophets, Prophesy not, prophesy not unto us right things,
prophesy smooth things, prophesy deceits; I charge you all,
in the name of the living God, that without interruption or opposition,
whether you like it, or like it not, you stand still and hear it: and when I have done,
you may do with me as the Lord shall give you leave,
or leave me under the power of your hands to do;
no law of equity condemning any man before he be heard,
especially when he speaks on so high an account as from the God of heaven himself,
though to such as are no less than God`'s under him here on earth.
____

Scarce had he spoken thus much, but some cried, '`A Quaker, a Quaker; keep him down,
he shall not speak:`' yet the protector and the parliament-men were still and quiet.
But some others, among whom two justices of peace, had not so much patience; but Fisher,
as he related afterwards,
believed that the protector and the parliament-men would have given him audience,
had not others set him at nought: some saying the protector had spoken long,
and was very hot and weary: and that he, +++[+++Fisher,]
might be ashamed to occasion his stay any longer.
Thus Fisher was interrupted, and the protector and parliament-men, rising, went away,
though Fisher did not question but the protector would have heard him:
for his moderation in hearing what was said, having been experienced before,
Fisher was willing to acknowledge his nobility as
freely as Paul took notice of the like in Festus;
whom he held most noble in that he would hear him, though he thought him mad.
Fisher being thus prohibited, published his speech in print,
so as he intended to have delivered it, though not one syllable of it was written before.
It was pretty long, and contained a sharp reproof to the hypocrisy of those, who,
under a show of godliness, made long prayers, kept fasts, and, nevertheless,
lived in pride, pomp, and luxury, persecuting those who really were a pious people.
And to the protector he said, that unless he took away the wicked from before him,
and all flattering false accusers,
his throne would never be established in righteousness.
In the introduction placed before this speech,
he says that before this burden came upon him,
he had prayed God that he might have been excused of this message,
thinking that a more unworthy one than himself could not have been singled out;
but whatever he did, he could not be rid of it;
and though he spent a whole week with fasting, tears, and supplication,
yet during the time of that abstinence,
he felt a daily supply and refreshment to his spirits,
so that he fully resigned to do what he believed was required of him from the Lord;
and he felt all fears of the frowns of men removed from him.
Some other speeches which he intended to have made to the parliament,
but was obstructed therein, he also published afterwards in print.

In the latter part of this year it happened that
Humphrey Smith coming to Evesham in Worcestershire,
was disturbed in a meeting by the mayor, Edward Young,
who said he would break the Quakers`' meetings, or else his bones should lie in the dirt.
Thus resolved, he came in the month called October,
on a First-day of the week in the morning, into their meeting,
in a house where H. Smith was: and several persons after being rudely abused,
were hauled out to prison.
In the afternoon a meeting being kept in the street,
some of the company were by order of the said mayor put into the stocks, and others,
of which the aforesaid Smith was one, into a dark dungeon:
and though the mayor then said it was an unlawful assembly,
but if they would meet in houses he would not molest them;
yet on next First-day of the week,
he seeing one going to a meeting that was appointed in a house, put him in prison.
H+++.+++ Smith and his friends had some bedding and bed-clothes sent them,
but the mayor caused it to be taken away from them;
and afterwards when some straw was brought them to lie upon,
the jailer would not allow it; no, when one came,
and asked liberty to fetch out their dung from them, the mayor denied it,
and ordered him to be put in the stocks.
The place where they were kept, was not twelve feet square, and the hole to take in air,
was but four inches wide, so that even by day-light they were made to burn candle,
when they had it.
Here they were kept above fourteen weeks, with their own dung in the same room;
so that one of them grew sick of the stink; and yet the jailer said,
if they had been there for theft or murder,
he could have let them have more liberty than now he dared, because of the mayor.
James Wall, one of the prisoners, was a freeman of the town, and a shopkeeper,
and yet the mayor forbade his wife to stand in the market-place,
which for many years she had done.
She going to him about it, he began to fawn upon her, and said:
'`I hear that your husband does abuse you.`'
To which she answered, '`My husband did never abuse me;
but as for that judgment which he now holds, once I could not acknowledge it;
but now seeing it is so much persecuted, makes me acknowledge it,
because the way of God was always persecuted.`'
He hearing her speak so, said, she should not have a standing place for five pounds.

About a month after, Margaret Newby and Elizabeth Courton came to this town,
and had a meeting at the house of one Edward Pitwayes:
but coming in the afternoon to visit the prisoners,
the mayor himself laid violent hands on them, and caused them to be put in the stocks,
with their legs near a yard one from another;
and he would not allow them to have a block to sit on, though they desired it;
yet as one that would seem to have some modesty, he bid the constable fetch a block,
and put between their legs, uttering indecent expressions;
in this posture they were kept for the space of fifteen hours, and then,
in a freezing night sent out of the town,
without suffering them to go to any place to refresh themselves.
And as to Humphry Smith, and those with him, they were yet kept a good while in prison.

In this year Alexander Parker was at Radnor in Wales,
and bearing there a testimony against the priest Vavasor Powel,
he also preached the doctrine of Truth, as occasion offered.
It was, I think, about this time, that Ambrose Rigge and Thomas Robinson came to Exeter;
from there to Bristol, and afterwards to Basingstoke in Hampshire.
Here, after much trouble, they got a meeting appointed;
but before all the people were assembled, the chief priest, with the magistrates,
came there, and causing them to be taken away, tendered them the oath of abjuration.
But they denying to swear for conscience sake, were committed to prison:
and the jailer nailed planks before the window, to deprive them of the light;
neither would he allow them to have a candle at night.
Here they were kept about a quarter of a year; having nothing to lie on but some straw.
But this their suffering had such effect,
that some of the inhabitants seeing these unreasonable dealings,
began to inquire into the doctrine held forth by the sufferers,
and so came to be convinced of the truth thereof.
They at last being released, Robinson went to Portsmouth, where he preached repentance.
Some time after A. Rigge came also there,
and reaped what Robinson in some respect had sowed;
though it was not long before he was sent out of town.
But returning within a short time, he found opportunity to have a meeting there;
and by his preaching some were convinced, and embraced his doctrine.

From there he went to the Isle of Wight,
where some also received the doctrine maintained by him.
After some stay he returned to Sussex, where he had great service.
And traveling up and down the county, he came to Weymouth and Melcombe-Regis,
where speaking in the steeple-house against the priest,
he was seized and locked up in a nasty dungeon where
there was nothing to lie on but some filthy straw,
and a stone to sit on: there was also no house of office;
but on the ground lay a heap of dung, where he was also forced to ease himself.
But there being an opening at the top of the room,
he could see people go along the streets, and thus took occasion,
from this subterranean cave, to preach to the passengers with such power and efficacy,
that his doctrine entered into the hearts of the hearers and stuck there.
This manner of preaching often has been in England, and I myself, in my young years,
have been an eye-witness of it; and have heard the prisoners lift up their voice so,
that it could be heard very easily in the streets; which made people that passed by,
stand still, and hearken to what was spoken by such zealous preachers.
And though these were often hindered of having meetings,
yet it was impossible to stop up the fountain from which their words flowed.
Thus it was also with A. Rigge, who, after an imprisonment of eleven weeks,
being set at liberty, travelled up and down again; but in many places where he came,
a prison was his lot; sometimes even when nothing could be laid to his charge,
but that he was gone from his dwelling-place; for the parliament had made a law,
that all who were gone from home,
and could not give a satisfactory account of their business,
should be taken up as vagabonds.
Under this pretense, many who travelled to the markets with their goods,
were seized by the way; for if it did but appear that such a one was a Quaker,
which was presently seen by his not putting off his hat,
then there lacked no pretended reason to clap him up in prison.

Ambrose Rigge traveling on,
came also to visit some of his friends in prison at Southampton.
This was taken so ill, that the mayor, Peter Seal, without examining,
caused him to be fastened to the whipping-post, in the market place,
where he was severely lashed by the executioner, and then put into a cart,
and sent out of the town, in freezing snowy weather; the mayor threatening him,
that if ever he returned, he should be whipped again,
and burnt in the shoulder with an R. signifying rogue.
Notwithstanding this, he was moved to return,
and the mayor was very eager to have this executed on him;
but the other magistrates would not consent;
and not long after the mayor died of a bloody flux.
This relation has carried me a little beyond the course of time.
But now I leave A. Rigge for a while, intending to make further mention of him hereafter.

In this year William Caton went again into Scotland, from which returning,
he travelled to Bristol, from there to Plymouth, and so to London;
from which he made a voyage again to Holland,
where William Ames and John Stubbs had been,
and also found some among the English people at Amsterdam,
who had received the doctrine they preached, though afterwards they turned from it again.
W+++.+++ Ames found also some reception among the Baptists there,
who at first were pleased with him, but J. Stubbs did not please them so well:
as Dr. Galenus Abrahams once told me,
who compared Ames to a musician that played a very melodious tune,
and Stubbs to a disturber of the harmonious music; though Ames afterwards,
for his great zeal, was found fault with also.

W+++.+++ Caton now arrived at Dort, and from there repaired to Rotterdam, where,
for lack of an interpreter that understood English, he was made to make use of the Latin.
But it grieved him exceedingly to meet with some unruly spirits there,
that having been in some measure convinced by W. Ames,
ran out under the denomination of Quakers, into extremes, both in words and writings.
Some of these persons I know,
and have seen also some of the books they published in print, in which,
under a pretence of plainness, not one capital letter was to be found,
even not to proper names, no, not to names of authors themselves.
And since they ran out into several other extravagances, it was not much to be wondered,
that the magistrates clapped them up in Bedlam.
The ringleader of these people, was one Isaac Furnier, who formerly,
(as I have heard my uncle tell, who had seen it himself,) lived as another Diogenes,
using at the fire, instead of a pair of tongs, a split stick;
and now conversing among the Quakers, so called,
made it a piece of holiness to use the most blunt language, he could think of;
how absurd and irregular soever.
In fine, he so behaved himself, that the orthodox Quakers rejected his society.
He it was, as I have understood, who was the author of that ridiculous saying,
'`My spirit testifies:`' which, though not approved nor used by the true Quakers,
yet has been so spread among the people in the Low Countries,
that it has been constantly credited, and is not yet quite disbelieved,
that the Quakers used to say so of any thing they intend to do; and that if any one,
whoever it be, says so, they will give credit to his saying.
The above said Dr. Galenus told me, that this man coming to his door,
and finding the doctor`'s name written on the post of the door,
(as is usual in Holland,) did with his knife,
scratch out the letters Dr. signifying doctor.
On which the doctor asked him, why he did so?
And his answer was, because the spirit did testify so unto him.
And being asked farther,
if so be that spirit did move him to stab the doctor with the knife,
whether he would follow that motion, he answered,
(if the relation be true,) as the doctor affirmed to me, '`Yes.`'
But however it be, this is true, that this Furnier was a passionate,
and giddy-headed man, whom the true Quakers could not acknowledge,
though he had translated many of their books out of English into Dutch;
and would also preach among them.
But at length he left them, and turning Roman Catholic,
fell into a dissolute and debauched life.

But to return to William Caton: coming to Amsterdam,
he did not find much more satisfaction there than at Rotterdam;
for several high-conceited professors,
who seemed to approve the doctrine preached by the Quakers,
were more apt to take upon them to teach others, than to receive instruction from others.
Wherefore W. Caton did not stay long at Amsterdam, but returned to Rotterdam;
and from there went to Zealand, arriving at Middleburgh,
accompanied with a certain young man,
who went to some of the meeting-places in that city, and was apprehended;
which Caton understanding, went to visit him,
and they perceiving that he was his companion, secured him also;
and after having been kept in prison some days, being weak in body,
it was ordered that they should be sent to England;
and so they were carried in a coach-wagon to the waterside,
being conducted by a guard of soldiers, to protect them against the rude multitude,
and brought on board a ship of war, where Caton suffered great hardship;
for the seamen were so ill-natured,
that they would not allow him so much as a piece of sailcloth,
but he was made to lie upon the bare boards, in very cold and stormy weather.
But though thus hardly used, yet he felt his strength increase,
and so experienced the mercies of God.
It was in November when he arrived at London,
where he was kindly received by the brethren: after some stay there,
he went to Hampshire, Surry, Sussex, and Kent.

Not long before this, G. Fox came to Exeter, where James Nayler was in prison,
and spoke to him by way of reproof; which Nayler slighted,
though he offered to kiss G. Fox: but he unwilling to permit this, said,
since he had turned against the power of God, he could not receive his show of kindness.
It appeared by letters the magistrates found in his pocket at Bristol,
that the Quakers found fault with him, and had reproved him of his high-mindedness,
before it launched out into that extravagant act
which made so great a noise in the world,
and has been mixed with many untruths, and false turns.
I have therefore thought it worth while to inquire narrowly into it,
in order to give a true relation of matters of fact.

This James Nayler was born of honest parents,^
footnote:[His father was a husbandman, and of good repute,
having a competent estate to live on, with industry,
according to the manner of the country where he dwelt.
He was educated in good English, and wrote well.
About the age of twenty-two he married, and then removed into Wakefield parish;
where he continued, till the wars broke out in 1641, and then went into the army,
and was a soldier eight or nine years, first under the Lord Fairfax,
and afterwards quarter-master under major-general Janibert,
till disabled by sickness in Scotland,
he returned home about 1649.--J. Whiting`'s account.]
in the parish of Ardesley, near Wakefield in Yorkshire, about the year 1616.
He had served in the parliament army,
being quarter-master in major-general Lambert`'s troop in Scotland;
was a member of the Independents; and afterwards, in the year 1651,
he entered into the communion of the Quakers, so called.^
footnote:[He and Thomas Goodair were convinced by G. Fox, about Wakefield around 1651,
as were also Richard Farnsworth, Thomas Aldam, William Dewsbury, and wife,
about the same time.
And in the beginning of the year following, as he was in the field at plough,
meditating on the things of God, he heard a voice,
bidding him to go out from his kindred, and from his father`'s house;
and had a promise given with it, that the Lord would be with him;
whereupon he did exceedingly rejoice that he had heard the voice of God,
whom he had professed from a child, and endeavored to serve:
and when he went home he made preparation to go; but not being obedient,
the wrath of God was upon him, so that he was made a wonder,
and it was thought he would have died.
Afterwards being made willing, and going out with a friend,
not thinking then of a journey, he was commanded to go into the West,
not knowing what ho was to do there; but when he came, he had given him what to declare;
and so he continued, not knowing one day what he was to do the next;
and the promise of God, that he would be with him,
he found made good to him every day.--Collect, of J. N.`'s writings.]
He was a man of excellent natural parts, and at first did acquit himself well,
both in word and writing among his friends,
so that many came to receive the Truth by his ministry.
He came to London towards the latter end of the year 1654, or beginning of 1655,
and found there a meeting of friends, which had already been gathered in that city,
by the service of Edward Burrough, and Francis Howgill;
and there he preached in such an eminent manner, that many admiring his great gift,
began to esteem him much above his brethren, which as it brought him no benefit,
so it gave occasion of some difference in the society; and this ran so high,
that some forward and inconsiderate women, of whom Martha Simmons was the chief,
assumed the boldness to dispute with F. Howgill and E. Burrough,
openly in their preaching, and thus to disturb the meetings:^
footnote:[These women`'s practice we may suppose to be somewhat
like that which gave occasion to the apostle Paul to say,
"`Let your women keep silence in the churches,
for it is not permitted unto them to speak.`" 1 Cor. 14:34.
This prohibition of speaking, must be voluntary discourse,
by way of reasoning or disputing, and not when they had an immediate impulse,
or concern to prophesy; for the apostle in the same epistle,
has defined prophesy to be speaking unto
"`Men to edification, exhortation, and comfort.`" chap. 14:3. And has also chap. 9.
made express mention of women`'s praying and prophesying, together with the men.]
whereupon they, who were truly excellent preachers, did not fail,
according to their duty to reprove this indiscretion.
But these women were so disgusted, that Martha, and another woman,
went and complained to J. Nayler, to incense him against F. Howgill and E. Burrough;
but this did not succeed,
for he showed himself afraid to pass judgment upon his brethren, as they desired.
Hereupon Martha fell into a passion, in a kind of moaning or weeping, and,
bitterly crying out with a mournful shrill voice, said, '`I looked for judgment,
but behold a cry;`' and with that cried aloud in a passionate lamenting manner,
which so entered and pierced J. Nayler,
that it smote him down into so much sorrow and sadness,
that he was much dejected in spirit, or disconsolate.
Fear and doubting then entered him, so that he came to be clouded in his understanding,
bewildered, and at a loss in his judgment, and became estranged from his best friends,
because they did not approve his conduct;
insomuch that he began to give ear to the flattering praises of some whimsical people,
which he ought to have abhorred, and reproved them for.
But his sorrowful fall ought to stand as a warning,
even to those that are endued with great gifts, that they do not presume to be exalted,
lest they also fall, but endeavor to continue in true humility,
in which alone a Christian can be kept safe.

Hannah Stranger, whom I very well know,
and have reason to believe a woman of high imaginations,
at this time wrote to him several very extravagant letters;
calling him the everlasting Son of Righteousness, Prince of Peace,
the only begotten Son of God, the fairest of ten thousands, etc.
In the letters of Jane Woodcock, John Stranger, and others,
were expressions of the like extravagance; and the said Hannah Stranger, Martha Simmons,
and Dorcas Erbury, arrived to that height of folly, that in the prison at Exeter,
they kneeled before Nayler, and kissed his feet:
but as to what has been divulged concerning his committing of fornication,
I never could find, though very inquisitive in the case,
that he was in the least guilty thereof.^
footnote:[As to that accusation,
as if I had committed adultery with some of those
women who came with us from Exeter prison,
and also those who were with me at Bristol, the night before I suffered there,
of both which accusations I am clear, before God,
who kept me at that day both in thought and deed, as to all women, as a little child,
God is my record.
Collect, of J. Nayler`'s writings, p. 54.
See more particularly in his answer to [.book-title]#Bloome`'s Fanatic History#,
in the said Collect, at p. 652.]
But for all that, he was already too much transported, and grew yet more exorbitant;
for being released from that prison, and riding to Bristol in the beginning of November,
he was accompanied by the aforesaid and other persons;
and passing through the suburbs of Bristol,
one Thomas Woodcock went bareheaded before him; one of the women led his horse; Dorcas,
Martha, and Hannah, spread their scarfs and handkerchiefs before him,
and the company sung, "`Holy, holy, holy, is the Lord God of hosts,
Hosannah in the highest: holy, holy, holy, is the Lord God of Israel.`"
Thus these mad people sung, while they were walking through the mire and dirt,
till they came into Bristol; where they were examined by the magistrates,
and committed to prison; and not long after he was carried to London,
to be examined by the parliament.
How it went there may be seen in the printed trial,
which the parliament was pleased to publish.^
footnote:[But the extravagance of the sentence,
which that parliament passed upon him with other circumstances,
give great reason to suspect the account was partially taken,
and published to justify their cruelty,
which is also set forth in part by way of annotation on the said trial.
And, (as J. W. says,) some of his answers were innocent enough, some not clear,
and some aggravated by his adversaries; some of them he denied, some he owned;
they reported the worst, and more than was true in some things,
adding and diminishing as they were minded;
much was lacking of what he had spoken to the committee;
wresting and perverting his words what they could,
and endeavoring to draw words out of him to ensnare him, and take away his life:
and to show their confusion when he was before them, they would have had him to kneel,
and put off his hat to them, though a part of the charge against him was,
that some kneeled to him.]
I believe that J. Nayler was clouded in his understanding in all this transaction:
but how grievous soever his fall was, yet it pleased God,
in his infinite mercy to raise him up again, and to bring him to such sincere repentance,
that, (as we may see in the sequel,) he abhorred not only this whole business,
but also manifested his heavy sorrow, in pathetic expressions, which were published,
as will be shown in its proper place.

What has been said of the odd doings in Exeter prison, and of his riding into Bristol,
was not denied by him, nor by the rest of the company,
when they were examined by a committee of parliament,
who made their report on the 5th of December, to which the house agreed next day.
On the 16th this business, which had, (not without much contradiction;
for many members of the parliament did not approve the severity
used against him,) been treated both forenoons and afternoons,
was proposed the twelfth time: which made an ingenious author say afterwards,
that it was wondered at by many, what the cause might be,
that this foolish business should hold so many wise men so long at work.
On the 17th, after a long debate, they came to this resolution,

[.embedded-content-document.legal]
--

That James Nayler be set on the pillory, with his head in the pillory,
in the Palace-yard, Westminster, during the space of two hours, on Thursday next,
and be whipped by the hangman through the streets, from Westminster to the Old Exchange,
London; and there likewise be set on the pillory, with his head in the pillory,
for the space of two hours, between the hours of eleven and one, on Saturday next,
in each place wearing a paper containing an inscription of his crimes;
and that at the Old Exchange his tongue be bored through with a hot iron,
and that he be there also stigmatized in the forehead with the letter B.;
and that he be afterwards sent to Bristol, and be conveyed into,
and through the said city on horseback, with his face backward,
and there also publicly whipped the next market-day after he comes there;
and that from there he be committed to prison in Bridewell, London,
and there restrained from the society of all people,
and there to labor hard till he shall be released by parliament;
and during that time he be debarred the use of pen, ink, and paper,
and shall have no relief but what he earns by his daily labor.

--

They were long before they could agree on the sentence;
for suppose there was blasphemy committed,
yet his tongue seemed not properly guilty of it,
since it was not proved that blasphemous words had been spoken by him.^
footnote:[At Lancaster sessions the priest got some to swear blasphemy against G. Fox,
(which was the common accusation in those days,) but he was cleared, and the priests,
etc. were enraged, who thereupon sent a petition to the council of state,
against G. Fox and J. N. who answered the same in a book called, [.book-title]#Saul`'s Errand to Damascus.#
After this, J. N. was persecuted in several places, beaten, stoned,
and cruelly used by the priests and their rude followers, and in danger of his life.
Afterward, by the instigation of the priest,
he and F. Howgill were committed to Appleby jail,
and tried on an indictment for blasphemy, for saying Christ was in him,
according to Col. 1:27. "`Christ in you the hope of glory.`"
He was also another time charged with blasphemy, for asserting in a book,
[.book-title]#Justification by the Gift of God`'s Righteousness#, which he proved from Rom. 5
and so stopped their mouths, and cleared himself:
by which we may see what that generation, who were righteous in their own eyes,
would have made blasphemy. --J. Whiting`'s account.]
Many thought it to be indeed a very severe judgment to be executed upon
one whose crime seemed to proceed more from a clouded understanding,
than any willful intention of evil.

Now although several persons of different persuasions,
being moved with compassion towards Nayler,
as a man carried away by foolish imaginations,
had offered petitions to the parliament on his behalf,
yet it was resolved not to read them, till the sentence was pronounced against him.

There lived then at London, one Robert Rich, a merchant,
(a very bold man,) who wrote a letter to the parliament,
wherein he showed what was blasphemy; and on the 15th of December,
several copies thereof were delivered to particular members;
and in that which was given to the speaker, these words were written at the bottom,
'`If I may have liberty of those that sit in parliament, I do here attend at their door,
and am ready, out of the Scriptures of Truth, to show,
that not any thing J. Nayler has said or done, is blasphemy,`' etc.

The parliament after judgment was concluded,
resolved that the speaker should be authorized to issue
his warrants to the sheriffs of London and Middlesex,
the sheriff of Bristol, and governor of Bridewell,
to see the said judgment put in execution.
By some it was questioned whether that was a sufficient warrant,
unless the protector concurred in the matter; but he seemed unwilling to meddle with it.
The thing being thus far agreed upon, J. Nayler was brought up to the bar;
and when the speaker, sir Thomas Widdrington,
was about to pronounce the aforementioned sentence,
Nayler said he did not know his offense.
To which the speaker returned, he should know his offense by his punishment.
After sentence was pronounced, though J. Nayler bore the same with great patience,
yet it seemed he would have spoken something, but was denied liberty;
nevertheless was heard to say, with a composed mind, '`I pray God,
he may not lay it to your charge.`'

The 18th of December, J. Nayler suffered part of the sentence;
and after having stood full two hours with his head in the pillory, was stripped,
and whipped at a cart`'s tail, from Palace-yard to the Old Exchange,
and received three hundred and ten stripes;
and the executioner would have given him one more,
(as he confessed to the sheriff.) there being three hundred and eleven kennels,
but his foot slipping, the stroke fell upon his own hand, which hurt him much.
All this Nayler bore with so much patience and quietness,
that it astonished many of the beholders,
though his body was in a most pitiful condition:
he was also much hurt with horses treading on his feet,
whereon the print of the nails were seen.
Rebecca Travers, a grave person, who washed his wounds,
in a certificate which was presented to the parliament, and afterwards printed, says,
'`There was not the space of a man`'s nail free from stripes and blood, from his shoulders,
near to his waist, his right arm sorely striped, his hands much hurt with cords,
that they bled, and were swelled:
the blood and wounds of his back did very little appear at first sight,
by reason of abundance of dirt that covered them, till it was washed off.`'
No, his punishment was so severe,
that some judged his sentence would have been more mild, if it had been present death:
and it seemed indeed that there was a party,
who not being able to prevail so far in parliament as to have him sentenced to death,
yet strove to the utmost of their power to make him sink under the weight of his punishment:
for the 20th December was the time appointed for executing the other part of the sentence,
that is, boring through his tongue, and stigmatizing in his forehead;
but by reason of the most cruel whipping, he was brought to such a low ebb,
that many persons of note, moved with compassion,
presented petitions to the parliament on his behalf,
who respited his further punishment for one week.

During this interval, several persons presented another petition,
in which are these words:

[.embedded-content-document.legal]
--

Your moderation and clemency in respiting the punishment of J. Nayler,
in consideration of his illness of body,
has refreshed the hearts of many thousands in these cities,
altogether unconcerned in his practice;
wherefore we most humbly beg your pardon that are
constrained to appear before you in such a suit,
(not daring to do otherwise,) that you would remit the remaining
part of your sentence against the said J. Nayler,
leaving him to the Lord, and to such gospel remedies as he has sanctified;
and we are persuaded you will find such a course
of love and forbearance more effectual to reclaim;
and will leave a seal of your love and tenderness upon our spirits.

And we shall pray, etc.

--

This petition being presented at the bar of the house by about one hundred persons,
on the behalf of the whole, was accordingly read and debated by them;
but not being likely to produce the desired effect,
the petitioners thought themselves in duty and conscience bound to address the protector,
for remitting the remaining part of the sentence; who, thereupon,
sent a letter to the parliament, which occasioned some debate in the house.
But the day for executing the remaining part of the sentence drawing near,
the petitioners made a second address to the protector.
It was, indeed, very remarkable,
that so many inhabitants that were not of the society of those called Quakers,
showed themselves so much concerned in this business;
but to me it seems to have proceeded merely from
compassion towards the person of J. Nayler;
whom they regarded as one that was rather fallen into error, through inconsiderateness,
than to have been guilty of willful blasphemy:
for then he would not have deserved so much pity.

But, notwithstanding all these humble petitions, the public preachers, it seems,
prevailed so much with Cromwell,
that he could not resolve to put a stop to the intended execution;
for five of these ministers, whom I find named thus, Caryl, Manton, Nye, Griffith,
and Reynolds, came on the 24th of December, by order from the parliament,
(as it was said,) to Nayler,
to speak with him concerning the things for which he was detained;
and would not permit either friend or other to be present in the room.
A certain impartial or neutral person desired it earnestly, but it was denied him;
but coming into the prison, after the conference,
he asked Nayler what had been the result of it, who told him,
that he told those ministers, that he saw they had an intent to make him suffer,
(though innocent,) as an evil-doer;
and therefore had denied any to be present that might
be indifferent judges between them and him;
and that therefore he should not say any thing, unless what passed was written down,
and a copy thereof given him to keep, or left with the jailer, signed by them.
This was by them consented to, and so they propounded several questions unto him,
and took his answers in writing.
He further told,
that they asked him if he was sorry for those blasphemies that he was guilty of,
and whether he did recant and renounce the same; to which his answer was,
'`What blasphemies, name them?
but they not being able to instance in any particular, he continued,
'`Would you have me recant and renounce, you know not what?`'
Then they asked him whether he did believe there was a Jesus Christ?
to which he answered, he did believe there was,
and that Jesus had taken up his dwelling in his heart and spirit,
and for the testimony of Him he now suffered.
Then one of the preachers said,
'`But I believe in a Jesus that never was in any man`'s heart:`' to which Nayler returned,
he knew no such Christ, for the Christ he witnessed filled heaven and earth,
and dwelt in the hearts of the believers.
Next they demanded of him why he allowed those women to worship and adore him?
to which he replied, '`Bowing to the creature I deny;
but if they beheld the power of Christ, wherever it is, and bow to it,
he had nothing by which he might resist that, or gainsay it;^
footnote:[The most that I find in his examination, either in Bristol or London,
before the committee of parliament, as published from their report, was,
that he owned Christ in him, but never that he was Christ;
and that he took the honor given, not as to himself, but to Christ in him;
which yet is more than any man ought to receive; for when the beloved disciple, John,
fell at the angel`'s feet to worship him, he, (though an angel,) said unto him,
"`See you do it not, I am your fellow servant,
and of your brethren that have the testimony of Jesus, worship God.`" Rev. 19:10.
And if an angel ought not,
surely no mortal man ought to receive or accept it, on any presence whatsoever;
though falling down, or kneeling to one another,
is too frequently used by some other people, and if it is not to their person,
it must be to their function, quality, or character in the church:
but that he received it to himself, as a creature, he utterly denied.
Trial, p. 15. And that there could not be a more abominable thing,
than to take from the Creator, and give to the creature, etc.
J+++.+++ W.]
and withal said to the ministers, '`Have you thus long professed the Scriptures,
and do you now stumble at what they hold forth?`'
Whereupon they desiring one instance of Scripture wherein such a practice was held forth,
he answered,
'`What think you of the Shunamite`'s falling down at
the feet of Elisha and bowing before him?
As also several others in Scripture spoken of, as of Abigail to David,
and that of Nebuchadnezzar to Daniel;`' upon which they pausing awhile, said at length,
'`That was but a civil act or acknowledgement:`' to which he returned,
'`So you might interpret the act of those women also, if your eye were not evil,
seeing the outward action is one and the same:`' and he perceiving
that they were seeking to wrest words from him to their own purpose,
said, '`How soon have you forgot the works of the bishops, who are now found in the same,
seeking to ensnare the innocent.`'
Whereupon they rose up, and with bitterness of spirit,
burnt what they had written before, and so left him with some bemoaning expressions;
and when they were departing,
he desired of them that the parliament would send him such
questions in writing as they desired satisfaction to,
and give him leave to return his answers in writing also.

By this it seems that Nayler, though still under some cloud,
yet was a little more clear in his understanding than before;
but he was encountered by fierce enemies,
and therefore the execution of his sentence was not stopped,
but performed on the 27th of December.
Robert Rich, that forward man, of whom something has been mentioned already,
was this day at the parliament door, from eight in the morning till about eleven,
crying variously to the parliament men, as they passed by.
To one whom he judged to be innocent, he said, "`He that dwells in love, dwells in God,
for God is love:`" and to another, whom he thought to be swayed by envy, he said,
"`He that hates his brother is a manslayer,
and he that hates his brother is a murderer.`"
Some then thought that Nayler would not have suffered any further punishment,
because many honorable persons had attended the parliament
and the protector on his behalf;
but Rich knowing how the case stood,
told the people that the innocent was going to suffer;
and to some of the parliament men he cried, that he was clear from the blood of all men;
and that he desired them to be so too.
Then he went towards the Exchange, and got on the pillory,
held Nayler by the hand while he was burnt in the forehead, and bored through the tongue;
and was not a little affected with Nayler`'s suffering, for he licked his wounds,
thereby as it seems to allay the pain; and he led him by the hand from off the pillory.
It was very remarkable that notwithstanding there might be many thousands of people,
yet they were very quiet, and few heard to revile him, or seen to throw any thing at him:
and when he was burning, the people both before and behind him, and on both sides,
with one consent stood bareheaded,
as seeming generally moved with compassion and goodwill towards him.

Many now rejoiced, seeing how some few among the Quakers, as Rich,
and the like sort of people, did side with Nayler,
while the Quakers generally spoke against him and his doings;
for those who hoped to see the downfall of them, signified not obscurely,
that now things went as they would have, since the Quakers,
(as they said,) were divided among themselves.
But time showed that this pretended division soon came to an end,
and those diviners and guessers overshot themselves.
How it went with the execution of Nayler`'s sentence at Bristol, I am not informed;^
footnote:[He was sent to Bristol, and there whipped from the middle of Thomas street,
over the bridge, up High street, to the middle of Broad street,
all which ho bore with wonderful patience, as related by an eye-witness,
and then sent by Tower lane the back way to Newgate,
and from there returned to Bridewell, London, according to the sentence.
--J. W.]
but by a letter of one Richard Snead, an ancient man of about eighty years,
I have understood that Nayler had written a letter to the magistrates of Bristol,
wherein he had disapproved, and penitently condemned, his carriage there.^
footnote:[After he was set at liberty, he went to Bristol, where in a public meeting,
he made confession of his offence, as to his former fall,
and declared in so powerful a manner, as tendered and broke the meeting into tears,
so that there wore few dry eyes,
(as related by some then present,) and many were bowed in
their minds and reconciled to him.--J. W`'s account.]
After this he was brought to Bridewell, London,
(as sentenced,) where he continued prisoner about two years,
during which confinement he came to a true repentance of his transgression;
and having got the use of pen and ink, wrote several books and papers,
condemning his error, which were published in print; and after his release,
he published several others, one of which by way of recantation, runs thus:

[.embedded-content-document.paper]
--

Glory to God Almighty, who rules in the heavens,
and in whose hands are all the kingdoms of the earth; who raises up,
and casts down at his will; who has ways to confound the exaltation of man,
and to chastise his children, and to make man to know himself to be as grass before him;
whose judgments are above the highest of men, and his pity reaches the deepest misery;
and the arm of his mercy is underneath, to lift up the prisoner out of the pit,
and to save such as trust in him from the great destruction, which vain man,
through his folly, brings upon himself; who has delivered my soul from darkness,
and made way for my freedom out of the prison-house,
and ransomed me from the great captivity; who divides the sea before him,
and removes the mountains out of his way,
in the day when he takes upon him to deliver the oppressed out
of the hand of him that is too mighty for him in the earth:
let his name be exalted forever, and let all flesh fear before him;
whose breath is life to his own, but a consuming fire to the adversary.

And to the Lord Jesus Christ, everlasting dominion upon earth,
and his kingdom above all the power of darkness;
even that Christ of whom the Scriptures declares, who was, and is, and is to come,
the light of the world to all generations;
of whose coming I testify with the rest of the children of light,
begotten of the immortal seed, whose truth and virtue now shine in the world,
unto the righteousness of eternal life, and the Savior of all that believe therein;
who has been the rock of my salvation,
and his spirit has given quietness and patience to my soul in deep affliction,
even for his name`'s sake: praises forever.

But condemned forever be all those false worships with
which any have idolized my person in the night of my temptation,
when the power of darkness was above.
All their casting of their clothes in the way, their bowing and singing,
and all the rest of those wild actions which did any ways tend to dishonor the Lord,
or draw the minds of any from the measure of Christ Jesus in themselves,
to look at flesh, which is as grass, or to ascribe that to the visible,
which belongs to Christ Jesus; all that I condemn,
by which the pure name of the Lord has been any ways blasphemed through me,
in the time of temptation: or the spirits of any people grieved,
that truly love the Lord Jesus throughout the whole world, of what sort soever.
This offence I confess, which has been sorrow of heart,
that the enemy of man`'s peace in Christ,
should get this advantage in the night of my trial,
to stir up wrath and offenses in the creation of God;
a thing the simplicity of my heart did not intend, the Lord knows;
who in his endless love has given me power over it, to condemn it.
And also that letter which was sent me to Exeter, by John Stranger, when I was in prison,
with these words, '`Your name shall be no more James Nayler,
but Jesus,`' this I judge to be written from the imaginations;
and a fear struck me when I first saw it, so I put it into my pocket, close,
not intending any should see it; which they finding on me, spread it abroad,
which the simplicity of my heart never approved.
So this I deny also, that the name of Christ Jesus was received instead of James Nayler,
or ascribed to him; for that name is to the promised seed to all generations;
and he that has the Son, has the name, which is life and power,
the salvation and the unction, into which name all the children of light are baptized.
So the name of Christ I confess before men,
which name to me has been a strong tower in the night and in the day;
and this is the name of Christ Jesus, which I confess, the Son and the Lamb,
the promised seed, where he speaks in male and female.
But who has not this in himself, has not life, neither can have, by idolizing my person,
or the person of any flesh; but in whom the heir is born, and has spoken, or does speak,
there he must not be denied the mouth to speak by, who is head over all,
and in all his own, God blessed forever.

And all those ranting wild spirits,
which then gathered about me in that time of darkness;
and all their wild actions and wicked words against the honor of God,
and his pure spirit and people; I deny that bad spirit, the power and the works thereof;
and as far as I gave advantage, through lack of judgment,
for that evil spirit in any to arise, I take shame to myself justly;
having formerly had power over that spirit, in judgment and discerning, wherever it was;
which darkness came over me through lack of watchfulness
and obedience to the pure eye of God,
and diligently minding the reproof of life, which condemns the adulterous spirit.
So the adversary got advantage, who ceases not to seek to devour;
and being taken captive from the true light,
I was walking in the night where none can work, as a wandering bird fit for a prey.
And if the Lord of all my mercies had not rescued me, I had perished;
for I was as one appointed to death and destruction, and there was none could deliver me.
And this I confess, that God may be justified in his judgment,
and magnified in his mercies without end, who did not forsake his captive in the night,
even when his spirit was daily provoked and grieved;
but has brought me forth to give glory to his name forever.
And it is in my heart to confess to God, and before men,
my folly and offence in that day:
yet were there many things formed against me in that day to take away my life,
and bring scandal upon the Truth, of which I am not guilty at all; as that accusation,
as if I had committed adultery with some of those
women who came with us from Exeter prison,
and also those who were with me at Bristol the night before I suffered there;
of both which accusations I am clear before God,
who kept me in that day both in thought and deed, as to all women, as a child,
God is my record.
And this I mention in particular,
(hearing of some who still cease not to reproach therewith God`'s Truth
and people,) that the mouth of enmity might be shut from evil speaking;
though this touches not my conscience.

And that report, as though I had raised Dorcas Erbury from the dead carnally,
this I deny also, and condemn that testimony to be out of the Truth;
though that power that quickens the dead, I deny not, which is the word of eternal life.
And this I give forth,
that it may go as far as the offence against the Spirit of Truth has gone abroad,
that all burdens may be taken off of the Truth, and the Truth cleared thereby,
and the true light, and all that walk therein, and the deeds of darkness be condemned;
and that all that are in darkness, may not act in the night, but stay upon God,
who dwells in the light, who with the workers of iniquity has no fellowship;
which had I done, when first darkness came upon me, and not been led by others,
I had not run against that rock to be broken, which so long had borne me,
and of whom I had so largely drank, and of which I now drink in measure;
to whom be the glory of all, and to him must every tongue confess, as Judge and Savior,
God over all, blessed forever.

--

The author adding to this an exhortation to the reader, how to behave himself,
if at any time he came to be tempted to sin; and also a warning,
not to rely too much on gifts, wisdom, and knowledge, concludes thus:

[.embedded-content-document.paper]
--

This I have learned in the deeps, and in secret, when I was alone;
and now declare openly in the day of your mercy, O Lord.
Glory to the Highest forevermore, who has thus far set me free,
to praise his righteousness and his mercy; and to the eternal, invisible, pure God,
over all, be fear, obedience, and glory forevermore.
Amen.

[.signed-section-signature]
James Nayler.

--

He wrote another paper, wherein he related at large,
how by unwatchfulness he came to fall,
after having once obtained much victory over the power of Satan, by the grace of God,
when he daily walked humbly in his fear,
having for some years labored faithfully in the ministry of the gospel.
But what is remarkable, though wherever he did use to come,
he went with great boldness through all opposition, yet coming to the city of London,
he entered it with the greatest fear that ever he came into any place with,
in spirit foreseeing, as he relates, something to befall him there,
but not knowing what it might be:

[.embedded-content-document.paper]
--

Yet had I, (thus he says,) the same presence and power as before,
into whatever place or service I was led of the Spirit;
in that life I never returned without victory in Christ Jesus, the Lord thereof.
But not minding in all things to stand single and
low to the motions of that endless life,
by it to be led in all things within and without; but giving away to the reasoning part,
as to some things which in themselves had no seeming evil,
by little and little it drew out my mind after trifles, vanities, and persons,
which took the affectionate part, by which my mind was drawn out from the constant watch,
and pure fear, into which I once was begotten.
Thus having in a great measure lost my own guide, and darkness being come upon me,
I sought a place where I might have been alone to weep and cry before the Lord,
that his face I might find, and my condition recover.
But then my adversary, who had long waited his opportunity, had got in,
and bestirred himself every way, so that I could not be hid:
and several messages came to me, some true, some false, as I have seen since.
So I knowing some to be true, namely, how I had lost my condition,
with this I let in the false message also;
and so letting go that little of the true light which I had yet remaining in myself,
I gave up myself wholly to be led by others;
whose work was then to divide me from the children of light, which was done:
though much was done by several of them to prevent it,
and in bowels of tender love many labored to have stayed me with them.
And after I was led out from them,
the Lord God of my life sent several of his servants with his word after me,
for my return; all which was rejected; yes,
the provocation of that time of temptation was exceeding
great against the pure love of God;
yet he left me not; for after I had given myself under that power,
and darkness was above, my adversary so prevailed,
that all things were turned and perverted against my right seeing, hearing,
or understanding; only a secret hope and faith I had in my God, whom I had served,
that he would bring me through it, and to the end of it,
and that I should again see the day of my redemption from under, it all;
and this quieted my soul in my greatest tribulation.

--

The author, moreover, seriously exhorting others,
who also might come to fall into great temptation, concludes with these words:

[.embedded-content-document.paper]
--

He who has saved my soul from death thus far, and has lifted my feet up out of the pit,
even to him be immortal glory forever, and let every troubled soul trust in him;
for his mercy endures forever.

[.signed-section-signature]
James Nayler.

--

That he came to a perfect recovery from his having been in a maze,
seems to appear plainly by the following thanksgiving to God for his mercies,
which he published after his fall:

[.embedded-content-document.paper]
--

It is in my heart to praise you, O my God; let me never forget you,
what you have been to me in the night, by your presence in the day of trial,
when I was beset in darkness, when I was cast out as a wandering bird,
when I was assaulted with strong temptations,
then your presence in secret did preserve me, and in a low state I felt you near me.
When the floods sought to sweep me away,
you did set a compass for them how far they should pass over.
When my way was through the sea, and when I passed under the mountains,
there were you present with me.
When the weight of the hills was upon me, you upheld me, else had I sunk under the earth.
When I was as one altogether helpless;
when tribulation and anguish was upon me day and night, and the earth without foundation;
when I went on the way of wrath, and passed by the gates of hell;
when all comforts stood afar off, and he that is my enemy had dominion;
when I was cast into the pit, and was as one appointed to death;
when I was between the millstones, and as one crushed with the weight of his adversary;
as a father, You were with me, and the rock of your presence.
When the mouths of lions roared against me, and fear took hold of my soul in the pit,
then I called upon you in the night, and my cries were strong before you daily;
who answered me from your habitation, and delivered me from your dwelling-place; saying,
I will set you above all your fears, and lift up your feet above the head of oppression,
I believed, and was strengthened, and your word was salvation.
You did fight on my part when I wrestled with death;
and when darkness would have shut me up, then your light shone about me,
and your banner was over my head.
When my work was in the furnace, and as I passed through the fire,
by you I was not consumed, though the flames ascended above my head.
When I beheld the dreadful visions and was among the fiery spirits,
your faith stayed me, else through fear I had fallen.
I saw you and believed, so the enemy could not prevail.

When I look back into your works I am astonished, and see no end of your praises.
Glory, glory to you, says my soul, and let my heart be ever filled with thanksgiving.
While your works remain, they shall show forth your power.
Then did you lay the foundation of the earth, and lead me under the waters,
and in the deep did you show me wonders, and your forming of the world.
By your hand you led me in safety, till you showed me the pillars of the earth.
Then did the heavens shower down, they were covered with darkness,
and the powers thereof were shaken, and your glory descended;
you filled the lower parts of the earth with gladness,
and the springs of the valleys were opened, and your showers descended abundantly;
so the earth was filled with virtue.
You made your plant to spring, and the thirsty soul became as a watered garden:
then did you lift me out of the pit, and set me forth in the sight of my enemies.
You proclaimed liberty to the captive, and called my acquaintance near me:
they to whom I had been a wonder, looked upon me,
and in your love I obtained favor in those who had forsook me.
Then did gladness swallow up sorrow, and I forsook all my troubles; and I said,
how good is it that man be proved in the night, that he may know his folly;
that every mouth may become silent in your hand until you make man known to himself,
and have slain the boaster, and showed him the vanity that vexes your spirit.

[.signed-section-signature]
James Nayler.

--

This plainly appears to be a poetical piece;
for the author all along makes use of allegorical sayings,
to signify the great anguish and tribulation he had been under.

The hatred of his enemies was the fiercer,
because he had undisguisedly and clearly demonstrated their duty, to the rulers,
and preachers, and lawyers: for in a certain book, published by him in the year 1653,
to exhort men to repentance, he writes thus to the rulers:

[quote]
____
O you rulers of the people, who are set up to judge between a man and his neighbor,
ought not you to judge for God, and not for man?
Ought not you to be men fearing God, and hating covetousness,
not judging for gifts and rewards?
Ought not you to countenance and encourage them that do well,
and to be a terror to them which do evil?
Justice is so.
And he that is of God, and bears his sword,
turns the edge of it against all sin and wickedness, injustice and oppression;
and so sets up justice and judgment in the gates,
that the poor may be delivered from him that is too mighty for him,
and that the cause of the fatherless, widow, and stranger may not fall;
but has an ear open to the cries of the poor and helpless, who has but little money,
and few friends; that a poor man may not be afraid to appear in a good cause,
against the greatest oppressor in the nation.

And ought not you to judge without respect to persons,
or without seeking respect to your own persons, worship or honor from men;
but only to advance justice, equity, and righteousness, which is of God;
that so you may be honored by the Lord; for true humility is honor,
and he that honors the Lord, him will He honor; and such have been honored in all ages,
though they never sought it from men.
____

This and much more he wrote to the rulers; and to the preachers thus:

[quote]
____
And you who say you are the teachers of the nation,
how long will it be before you look at your own ways?
Is not all manner of filthiness among you, which you should lead the people out of?
Is there not among you drunkenness, gluttony, whoredom, and sporting,
sitting down to eat and to drink, and rising up to play; swearing, lying, backbiting,
false accusing, railing, slandering, contention, strife, and envy?
Yes, are not the best of you given to pride and covetousness, which is idolatry;
fulness of bread, and abundance of idleness?
Are not you hirelings, and teach for the fleece?
Do not you contend for money with your own hearers, and sue them at law for it; yes,
although they cannot satisfy your demands,
without sinning against the light in their own consciences, and so sin against God?
Are you not bitter, and persecutors of any that come to discover your lewdness,
crying out to the magistrate to uphold you in your beastly ways,
and to stop the mouths of all those whom God has sent to witness against you?
And many more works of this nature are among you,
which the pure all-seeing God has showed unto his people, to be among you,
and therefore it is that they come out from you,
lest they partake with you of your sins and plagues.
But are not you Hind leaders of the blind,
when you neither see these to be the works of darkness, nor those that follow you.
Woe unto you that devour souls for money and gain, the day of your account is at hand.
O repent, the blood of souls is upon you, etc.
____

The lawyers in the same writing had a stroke also thus:

[quote]
____
And you lawyers, ought not you to plead the cause of equity,
between man and man for equity sake, without respect to yourselves or others,
but only to truth itself;
that a just cause may be acknowledged in whomsoever it concerns?
But is not the justest cause sure to fall,
if the party have not money to satisfy your demands;
which are many times very unreasonable?
And you who should instruct people in the ways of truth and peace,
do not you by your wisdom teach them lies and strife?
Do not you advise your plaintiffs, as you call them, to declare in bills,
things that are not true, and make small offences seem very great by false glosses?
For say you, we may declare what we will, and prove what we can; so that you,
and they whom you act for, know beforehand, that scarce one thing of ten can be proved,
neither is true?
Is this the way to make up the breach, and preserve peace and truth among people?
O miserable fall from God, when that law which should preserve in peace,
is used to aggravate offences beyond truth, and so make differences greater.
And do not you delight to fish in troubled waters:
and the greater dissension among the people, the more is your gain?
Are not your purses filled, and your estates raised in the ruins of the people?
And are not those laws which ought to be used to preserve people from oppression,
by abusing, made the undoing of whole families, impoverishing towns and countries?
The law, as it is now used, is scarce serviceable for any other end,
but for the envious man, who has much money to revenge himself upon his poor neighbors,
which, may be, never did him wrong.
Is there any appearing for the poor against the rich, although his cause be just;
but by deceit, delays, and expenses, the remedy is worse than the disease?
____

Much more he wrote to the lawyers, to stir them up to do justice,
and then addressed himself to the people in general, in these words:

[quote]
____
And you people of the nation,
that have seen the hand of God against the prince
and people for these and the like abominations,
and you yourselves are escaped, as brands plucked out of the fire;
have you at all turned to him who has smitten you; or are you bettered by correction;
or have you made your peace with the Almighty?
Although you have seen war, and the sword reaching to the very soul,
are you not every one, to your own power,
gathering fuel to that fire which has been burning in the land,
and has consumed thousands; which should have been as a warning unto you who are escaped,
to return to the Lord from the evil of your doings?
But are not you still making the breach wider between God and the nation,
as though you were left for no other end,
but to fill up the measure of iniquity that is yet behind,
that the just God may sweep the land with the broom of destruction?
O when will you cease to provoke the Lord by your sins?
Where is your Redeemer you have professed so long in words and forms?
Can you witness him in your works?
And what has he redeemed you from?
For says he, "`Why do you call me Lord, and do not the things which I say?`"
Is He your Lord, and you servants to all manner of filthiness?
And notwithstanding you have seen his wonders in the nation,
yet do not you exceed all that ever went before you, in pride, covetousness, drunkenness,
swearing, envying, quarreling, backbiting, slandering, false accusing, self-love,
and deceit in all manner of merchandise and trading; false weights and measures, sayings,
protesting one towards another, in your bargaining, speaking things that are not true,
and hereby to overreach your brethren, and get dishonest gain.
How many false oaths, and idle words are spent about every bargain in your markets,
and open streets, without blushing, or being ashamed?
Yes, it is able to break the hearts of any who know the pure God, to know it,
and hear it; for it is come to such a height of deceit, that none can trust his brother,
for lying, swearing, and forswearing, which abound in the nation;
and yet you will profess yourselves to be the members of Jesus Christ:
and had Jesus Christ ever such a body as this?
No, all that are members of him, are of one heart, and one soul.

And you talk of a communion of saints: had ever the saints such a communion as this,
to defraud one another for money; and profess a Redeemer, and are servants to the devil,
and your own lusts, in all the motions and temptations thereof,
and are led captive at his will?
But what redemption is this you witness?
So long as sin, the partition wall between God and you, stands still whole in your wills,
you will be drunk, swear, lie, and commit adultery, dissemble,
and satisfy your lusts in all things, and say we are redeemed;
yet commit all these abominations and live in them, under a pretence of a profession,
and going to the idols`' temple once a week.
Did ever Jesus Christ redeem such a people, or dwell in such a people?
Those whom he has redeemed, he has freed from the servitude of sin,
by separating them from sin, and reconciling them to God,
from which they are fallen by sin: for God and sin cannot dwell in one.
And to such he says, "`Be holy,
for I am holy:`" and as he is the "`Lamb of God who
takes away the sins of the world,`" now see,
how is your sins taken away, when the kingdom of darkness does wholly rule in you,
and leads you into works and ways of darkness?
Are you reconciled to God, and have you fellowship with him?
Are not you yet strangers to him, and worship an unknown God?
"`For he that commits sin, has not seen him, neither known him,`" and so worship,
they know not what, in formal and superstitious worships.
____

Thus J. Nayler wrote: but I now break off that I may not be tedious.

So zealous was he before his fall;
which was wholly of another nature than the common sins and transgressions; for,
by the wiles of Satan, he accepted the idolatrous honor that some persons gave him,
instead of which he ought to have reproved them;
and thus was he so stupified in his understanding,
that he imagined the bowing and kneeling before him,
was not done on account of his person, but for Christ:
and with this false opinion he blinded himself for a time,
till it pleased God to pity him, and to give him light again;
after he had suffered such an unheard of punishment for his transgression,
as is already related in this history.
And because his freedom of speech against unrighteousness of all sorts,
and his preaching, ran very sharp upon all, several were angry with him,
became his enemies,
and took occasion from his crime to revenge themselves fiercely upon him,
by making him suffer a cruel punishment,
which was no ways proportionate to his transgression.
But herein barbarous cruelty played its part so much,
that the soberest inhabitants did detest it,
and therefore a petition was presented to the parliament,
desiring a discharge of part of the punishment,
of which the first subscriber was Colonel Scroop, who was governor of Bristol.

While he lay in the house of correction,
he wrote several papers to manifest his regret and repentance for his crime;
some of which are already inserted in this history.
Since, is come to my hand a letter to his friends,
being written with his own hand to this purport:

[.embedded-content-document.letter]
--

[.salutation]
Dear brethren,

My heart is broken this day for the offence that
I have occasioned to God`'s truth and people,
and especially to you, who in dear love followed me, seeking me in faithfulness to God,
which I rejected; being bound wherein I could not come forth, till God`'s hand brought me,
to whose love I now confess: and I beseech you,
forgive wherein I evilly requited your love in that day.
God knows my sorrow for it, since I see it, that ever I should offend that of God in any,
or reject his counsel; and how that paper you have seen lies much upon me,
and I greatly fear further to offend, or do amiss, whereby the innocent Truth,
or people of God should suffer, or that I should disobey therein.

Unless the Lord himself keep you from me,
I beseech you let nothing else hinder your coming to me,
that I might have your help in the Lord:
in the mercies of Christ Jesus this I beg of you, as if it was your own case,
let me not be forgotten of you.

And I entreat you, speak to Henry Clarke, or whoever else I have most offended;
and by the power of God, and in the spirit of Christ Jesus,
I am willing to confess the offence, that God`'s love may arise in all hearts, as before,
if it be his will, who only can remove what stands in the way;
and nothing thereof do I intend to cover: God is witness herein.

--

He also wrote several other confessions of his faults about this time, in one of which,
among others, I find these words:

[.embedded-content-document.letter]
--

And concerning you, the tender plants of my Father, who have suffered through me,
or with me, in what the Lord has allowed to be done with me,
in this time of great trial and temptation; the Almighty God of love,
who has numbered every sigh, and put every tear in his bottle,
reward it a thousand fold into your bosoms, in the day of your need,
when you shall come to be tried and tempted;
and in the meantime fulfill our joy with his love, which you seek after.
The Lord knows, it was never in my heart to cause you to mourn,
whose suffering is my greatest sorrow that ever yet came upon me,
for you are innocent herein.

--

When he had finished that letter, and set his name, he wrote as follows:

[.embedded-content-document.letter]
--

I beseech you, (all that can,) to receive it, even as you would be received of the Lord;
and for the rest, the Lord give me patience to suffer, till he make up the breach.

--

While he was in Bridewell, he wrote to the parliament,
who had punished him as a blasphemer,
to let them know what his true opinion concerning Jesus Christ was.

[.embedded-content-document.letter]
--

Christ Jesus, (the Immanuel,
of whose sufferings the Scriptures declare,) him alone I confess before men;
for whose sake I have denied whatever was dear to me in this world, that I might win him,
and be found in him, and not in myself;
whose life and virtue I find daily manifest in my mortal body,
(which is my eternal joy and hope of glory;) whom alone I seek to serve in spirit,
soul and body, night and day,
(according to the measure of grace working in me,) that in me he may be glorified,
whether by life or death; and for his sake I suffer all things,
that he alone may have the glory of my change, whose work alone it is in me:
even to that eternal Spirit be glory, and to the Lamb forever.

But to ascribe this name, power, and virtue, to James Nayler,
(or to that which had a beginning, and must return to dust,) or for that to be exalted,
or worshipped, to me is great idolatry,
and with the Spirit of Christ Jesus in me it is condemned;
which Spirit leads to lowliness, meekness, and long-suffering.

So having an opportunity given, (with readiness,) I am willing,
in the fear of God the Father, (in honor to Christ Jesus,
and to take off all offences from every simple heart,) this to declare to all the world,
as the truth of Christ is in me, without guile or deceit,
daily finding it to be my work to seek peace in truth with all men in that spirit.

[.signed-section-signature]
James Nayler.

--

After this,
hearing that some had wronged him about that which
he had spoken to the committee of the parliament,
and understanding how men had perverted his words, he wrote a paper,
declaring himself further concerning his belief of Christ, and his sufferings, and death, etc.
Also he complained of things that some had published,
under the title of James Nayler`'s recantation, wherein they had much perverted him;
and he declared:

[.embedded-content-document.paper]
--

And as touching the printing of that paper,
(called J. N.`'s recantation,) it was not done by me, nor with my knowledge in the least,
nor do I yet at all know the man that has done it; but out of the Truth,
and against the Truth he has done it, and for evil towards me, whoever it was;
the Lord God of my life, who has kept me alive in all distress, turn it for good,
and forgive the evil: and though he that has done it, has not done it in Truth,
nor love to it, yet what of truth there is in the paper, I shall acknowledge,
as stands on Truth`'s behalf: for thus it was,
that after I was put into the hole at Bridewell,
I heard of many wild actions done by a sort of people
who pretended that they took my side;
and these were earnestly stirred up at that day, with much violence,
and many unseemly actions,
to go into the meetings of the people of the Lord called Quakers,
on purpose to hinder their peaceable meetings;
and yet would take that holy and pure name of God and Christ frequently in their mouths,
whereby the name of the Lord was much dishonored, and his pure Spirit grieved,
and much disorder they caused in many places of the nation,
to the dishonor of Christ Jesus, for which I felt wrath from God;
which when I understood that they had any strength through me,
I used all means I could to declare against that evil spirit,
which under the name of God and Christ, was against God and Christ, his Truth and people;
and something I did give forth about a year and a half since, in denial of these spirits,
which it seems to me, he that has done this, has got a sight of,
and has added to it the thoughts of his own heart, and so has brought out this darkness,
that people know not what to make of it.

Therefore, so far as it testifies against those unclean ranting spirits,
and all the actions wherein the holy name of God has been dishonored,
and his Spirit grieved, so far I acknowledge it;
but in that it is turned as though I denied the Lord Jesus Christ, and his Truth,
which has called me out of the world, or his people, whom he has called into light,
in that I acknowledge it not; for in the patience and tribulation of Christ Jesus,
and with those who have the power this day to testify therein,
against all the evils of this present world,
I am one in heart and soul to the utmost of my strength,
till the coming of the Lord Jesus over all; and the throne of meekness and truth,
be set on the top of enmity and deceit;
in which faith and power I am given up to live or die, suffer or rejoice, as God will,
even so be it, without murmuring.

[.signed-section-signature]
James Nayler.

--

This is certain, that James Nayler came to very great sorrow,
and deep humiliation of mind; and therefore,
because God forgives the transgressions of the penitent, and blots them out,
and remembers them no more,
so could James Nayler`'s friends do no other than forgive his crime,
and thus take back the lost sheep into their society.
He having afterwards obtained his liberty, behaved himself as became a Christian,
honest and blameless in conduct; and patiently bore the reproach of his former crimes.
