== Chapter VII.

=== 1656-1657.

[.chapter-synopsis]
* "`The Fanatic History`"
* Answered by J. Nayler
* Death of J. Nayler
* M. Fisher and A. Austin go to New England
* Their barbarous usage
* Laws made to prevent Quakers from going to New England
* Interview between the Protector and G. Fox and E. Pyot
* Letters of warning from E. Burrough to the Protector
* Singular conference between C. Birkhead and an English congregation at Middleburg, Zealand
* Travels of W. Ames and W. Caton
* Author`'s parents convinced
* G. Fox and the Governor of Tenby
* Quakers excommunicated in Scotland
* G. Fox travels over Scotland
* Severities against Quakers in New England
* Singular incidents of G. Robinson`'s travels to Jerusalem

When king Charles the Second had ascended the throne, one Richard Blome published a book,
entitled,
[.book-title]#The Fanatic History#,
which was said to be published with the approbation of orthodox divines,
(so called,) and dedicated by him to the king.
This book struck chiefly against the Quakers,
and was stuffed with a multitude of lying stories,
and the fall of J. Nayler was not concealed in it.
He being then alive, took up the pen, and answered the falsities contained in it,
relating to himself: and because R. Blome, in his dedication, said,
'`That if his majesty put not forth his royal hand of power suddenly, to restrain us,
we are so numerous, and seducing, that we will,
(in a little time,) diffuse our poison over the better part of his kingdom,
which none but a regal authority can stifle.`'

[.embedded-content-document.paper]
--

I say then, what is become of your spiritual weapons?
Have not your teachers told people of the strength of truth, and the power of godliness?
Have you lost both, (may wisdom say,) and run you now to the arm of flesh,
to get errors stifled, (as you call them,) or else your hope is lost,
and your faith fails you?
Did ever any of Christ`'s ministers leave their spiritual weapons,
to run to the arm of flesh, or a carnal weapon to stop seducers?
I say, no.
This they never did; but with spiritual weapons they wrestled,
and overcame spiritual wickedness, and with them cut down heresies, blasphemies,
and false worships, and cleared the churches of Christ of them,
and drove them down before them in the world:
for none could resist the spirit by which they spoke, of all the false priests,
and false worshippers; but being put to the worst, they cried,
(as you do,) to rulers and people, Help us, or all will be overrun:
for they that turn the world upside down are come here,
(mind your cry.) And then the rude multitude ran on heaps upon them,
and made tumults often, and fell upon them with staves and fists,
and assaulted the houses that entertained them, as you do,
and so hauled them before rulers, who took their parts herein, and put them in prison,
and often whipped them; unless it were some that were so noble,
as not to heed the cry of the multitude; but would hear their cause,
and give them leave to speak, before they would sentence them that were accused.
And this was the nobility of heathen kings and rulers;
and do not you seek to make England`'s rulers worse than them?
Beware lest heathens rise up in the day of judgment against them who are called Christians,
and condemn them.

And is this your cry for help, against so contemptible a people,
(as you count them,) you, like silly women,
do but discover your weakness and worthlessness;
and if God open the eyes of King Charles, he will see it.
What! have you preached and wrestled yourselves out of all hope and faith,
that either you must have sudden help from him, or all is lost and overrun?
Surely it may be said, you have been bad watchmen, and idle shepherds, who have lost all,
if sudden help come not from another hand.
Now if any had come against you with carnal weapons,
then had you had some excuse in crying to the earthly powers;
but in that nothing but spirit comes against spirit, and yet you have lost the day.
This does clearly manifest, that the power of God you have not in you,
but have lost the kingdom of the Most High, and so are become unreasonable men,
who would have two weapons against one, and another to do your work for you,
and yet are unwilling to forego your wages; yes,
this advantage you have had several years, but have not prevailed therewith?

And whereas you say your book is of great consequence;
and so you presume to make king Charles the patron of it:
and then ask pardon for your presumption, when you have done.

I say you have need: the substance of your book being made up of false accusations,
gathered up out of books formerly written against us,
which have been disproved by answers several times over:
and to these you have added some new accusations, as false as the old,
and spied out the failings of some few, who have mourned before God,
that ever they should sin, and give occasion to the enemy of God so to blaspheme.
And many things which were done and spoken by others, who are not of us, nor ever were:
and of this is your book made up, as any may see who reads it,
and our several answers to the charges therein, many of them of several years standing,
against these false accusations, which have most of them been printed over and over,
and presented to the former powers that have risen, and as often answered:
so there needed no more to be said, than has been,
were it not for the sake of some who may yet be strangers
to your way of dealing towards us,
under every power that has been.
Now discretion will say, that to make another man the father of such a work,
to which he is a stranger, (but especially a king,) is presumption indeed,
rashness and folly, and needs a pardon.

And whereas you now say, that none but a regal authority can stifle; it is true,
you have tried parliaments and protectors, (as you called them,) and parliaments again;
and to make them then work for you, your priests used these arguments to them, namely,
That in the late wars they had exposed lives, liberties, estates, and relations,
with all other personal advantages, in maintaining the just proceedings of parliaments,
and from them you then claimed our stifling, as the price of your prayers, purses,
hazards, losses, banishment, and blood,
as may be read in the Westmoreland petition against us,
which you have printed in page 197 and 198. And was not
this power that which you then called the common enemy,
in the same petition, page 200, which you now cry to,
and would put him upon that work against us now, as defender of your faith, etc.
Ah! a faithless generation have you been to God and man,
may you not be ashamed of this work, to print it, and send it to king Charles,
and call him to defend it, and patronize it:
how has envy bereaved you of your reasonableness?
Shall he who defends this, defend either faith or truth?
But this is, that you may cover yourselves with your shame and envy,
that both king and people, and parliaments, may see what a generation you are,
that will run under any power to get your bloody ends; but indeed true to none;
for if it was true, that you were so faithful to that parliament, with your prayers,
purses, and blood, as there you plead, then is your faith but new,
which now you would have defended; but if not true, then how great deceivers,
and how little to be trusted, or defended, in your cruel designs.

The king that faithfully judges the poor, his throne shall be established forever.
But, if a ruler hearken to lies, all his servants are wicked.`" Prov. 29:12,14.

And to you, who have set forth this book of mischief, I say with the Scriptures,
"`Lay not wait, O wicked man, against the dwelling of the righteous,
spoil not his resting place.
For a just man falls seven times, and rises up again;
but the wicked shall fall into mischief.`" Prov. 24:15-16.
See also Mic. 7:8.

[.signed-section-signature]
J+++.+++ N.

--

=== In answer to the book.

[.embedded-content-document.paper]
--

The day is come that the Scripture is fulfilled, which the Lord spoke by his prophet, Isa. 44:25.
That he will make the diviners mad;
and that the prophets shall be ashamed, every one of his vision, Zach.
xiii.
4+++.+++ The which does now evidently appear, and their folly is made manifest unto all,
that will see and behold it,
according to 2 Tim. 3:9. And is not this manifest madness and folly in them,
called orthodox and divines, to present unto the king their packet of Hes,
which have been seven years told over, and so long since disproved and confuted,
as may be seen in a book called, [.book-title]#Saul`'s Errand to Damascus,
Etc.# printed in the year 1653, and in several other books since.
It already has been, and is now manifest unto all men of sober understandings,
that these men, falsely called orthodox and divines, have had no defence,
either to vindicate themselves, or disprove the people called Quakers,
but this refuge of lies, which they first presented to the parliament sitting in 1652,
and likewise to other parliaments which have been since that time,
and to the two protectors, and which now to this present king is directed;
and you presumptuously charge him to be the patron of it,
requiring him to defend those lies which you falsely call the faith.
But this we know, according as it is written, Prov. 29:12,19.
that '`if a ruler hearken to lies, and his servants are wicked;
but a wise king scatters the wicked, and brings the wheel over them.`"
Chap. 20:26.

These pretended divines are such as have bowed and
crouched under every appearance of a power,
and by flatteries seem to cleave unto them, that they might uphold, maintain,
and satisfy their God, which is their bellies.
These were of them which said, that Oliver Cromwell was the light of their eyes,
and the breath of their nostrils:
so that now with shame they might rather confess that they are blind, and dead,
(from the light and life of God,) than to multiply
lies in their accustomed manner as formerly.
These also were of them that said, Oliver Cromwell was Moses,
who had led them into a sight of the good land; and that Richard his son was Joshua,
which should lead them into the possession.
But we, with many more, do see that their hope is false,
and their faith also proved vain, and that they are not yet in the land of promise,
for there no liars come.
And those former rulers hearkening to their lies, were deceived by them,
which was the cause of God`'s judgments, and utter destruction coming upon them;
which while they put into the priests`' mouths they cried peace unto them,
calling them Moses, Aaron, and Joshua; but when they ceased,
and could not put into their mouths, then they cried out,
that Moses and Joshua were tyrants and oppressors: and so will they do unto the king now,
who are seeking to cleave unto him by flattery and deceit;
and if he deny to be the patron and defender of their lies,
will be apt to cry as much against him.
So that he, or they, are blessed, whose ears are not open to their clamours,
but whose hearts are joined to the Truth,
and who are led by the Spirit of God as their instructor;
for such shall discern hypocrites, and false-hearted men,
under every pretence of flattery or dissimulation;
for the folly of these begins to be manifest unto all men. 2 Tim. 3:9.

Now in answer to the history concerning John Tolverdey, asserted by a company of priests,
as Brooks, Cocking, Goodwin, Jenkin, Jacomb, Alderry, Tombs, and Poole,
who themselves say, that they have but perused a part, as page 99,
and yet pretend to witness the whole;
whose witness is disproved and denied by the said John Toldervey,
both by his own book given forth from him, and by his life and conduct, being now,
(since his return from his out-going,) a living witness, not against, but for the way,
doctrine, principle, and practice, which the people called Quakers do live in,
against those lies published abroad Concerning him.

And as for your charge you have against J. Nayler,
through the everlasting mercy of my God, I have yet a being among the living,
and breath to answer for myself, though against the intents of many cruel bloody spirits,
who pursued my soul, unto death, (as much as in them lay,) in that day of my calamity,
when my adversary was above, and wherein I was made a sign to a backsliding generation,
who then would not see nor hear what now is coming upon them;
but rejoiced against this piece of dust,
and had little pity towards him that was fallen into their hands;
wherein God was just in giving me up for my disobedience, for a little moment,
as a father to correct; yet should not they have sought to aggravate things against me,
as you do; for it was a day of deep distress, and lay sore upon my soul,
and the merciful God saw it, who, though he was displeased for a time,
yet his thoughts were not to cast off forever, (but extend mercy,) as it is at this day;
glory be to his name from my delivered soul, eternally.

And in that day there were many spirits flocked about me, and some whom,
(while the candle of the Lord shone upon my head,) I ever judged and kept out from me,
who then got up and acted, and spoke several things not in the light and Truth of God,
by which they who sought occasion against me,
were then strengthened to afflict this body,
and he that watches for evil in you and some others,
makes use of still against God`'s Truth and innocent people;
whose mouths the God of my mercy stop,
and so finish the trouble on my heart as to that thing;
for my soul has long dwelt among lions, even among them that are set on fire,
whose teeth are spears and arrows, and their tongues a sharp sword,
speaking mischievous things to shed blood.

But, O man, or men, whoever you are,
whose work it is to gather the failings of God`'s people in the time of temptation,
or night of their trial, and aggravate them,
and add thereto the wickedness and mischievous lies of your own hearts,
as you have done in your book, and then come cut with those,
against God`'s everlasting holy Truth, it to reproach;
I say you are set on work by an evil spirit,
and you do but show yourselves to be enemies to God and his children;
and it is our sorrow, that any of us should give occasion to blaspheme;
and it has been trouble of soul to all the people of God,
that have ever loved righteousness, when they have thus occasioned the joy of the wicked,
or to feed the man that watches for iniquity, and feeds on mischief; yet know this,
you that are of that brood, God will not cast off his people;
though he be sometimes provoked to correct them, even before their adversaries,
(which is a sign to them,) yet is his anger but for a moment,
and his favor shall return as streams of life;
then shall the food be taken out of the mouth of the viper,
and the prey from between the teeth of the devourers;
and God will feed them with their own vomit,
and the poison that has long lain under their tongues,
shall be bitter in their own bowels.
Thus will God certainly plead with Zion`'s enemies, as he bends her sons for himself,
and God will make up her breaches: and this has my soul seen, Jacob`'s captivity restored,
and the diggers of the pit are fallen therein;
neither has he smitten him as he smote them that smote him,
nor is he slain according to the slaughter of them that are slain by him,
but this is all his fruit to purge away his sin.

So he that has long watched for my faltering, then got advantage against me;
yet had I then power to bear his utmost envy, through Christ Jesus,
whom I then confessed before men, who then was my support in all, and under all,
and who is over all, blessed forever of all who have proved him in the depth.

But that which was, and is the sorrow of my heart,
is the advantage the enemy then took against the name of Christ, his Truth,
and his despised people, in that time of temptation,
which is that which you are now pursuing with hatred and lies,
as that I was suspected to have a woman in bed with me,
the night before I suffered at Bristol,
when there were six or seven persons in the room that night, and a man, namely,
Robert Rich, in bed with me.
But this, and several other false things, you have written in your book,
of which I am clear before the Lord, so they touch me not at all;
nor shall I here mention them against you in particular; but to God alone I look,
in his time, to be cleared from all offences in his sight,
who only knows my heart in this thing, in whose presence I can say,
that nothing is more odious and burdensome to my soul,
than that any of the glory or worship which belongs to God or to Christ,
should be given to flesh and blood, in myself, or others:
and how it was with me in that day many talk of, but few know;
so the judgment of such I bear; desiring that none in judging me,
might have condemned themselves in God`'s sight; whose counsels are a great deep,
and the end of his work past finding out, till he himself reveal them;
but in the end he will be justified of all, and in all he does,
that all flesh may be silent before him.

And however myself, or any others, may be left to themselves, to be tried in the night,
yes, should any utterly fall, or whatever may be acted by any man or woman,
that is not justifiable in God`'s sight, yet in vain do you, or you, gather up sin,
or watch for iniquity, to cast upon the light,
which condemns it in every enlightened conscience,
and there will clear himself to be no author nor actor therein;
and I know by the Spirit of Jesus, which I have received, and which works in me,
that this is not his work, nor his seed; and in him that loves his enemies, you are not;
but the old accuser of the brethren it is that works strongly in you;
and in the light which you reproaches, are you seen to be the man that makes lies,
and carries tales to shed blood.`' Ezek. 22:9.
12.

--

Thus much and more J. Nayler wrote to answer the falsehoods whereof he was accused,
and to apologize for the doctrine of which he had made profession,
and to show that the fault of his crime must no ways be attributed
to the same as many envious persons in those times asserted,
namely,
that his fall was a consequence of the doctrine that
men must take heed to the saving grace,
the inward anointing,
or the light wherewith every man coming into the world is enlightened from God^
footnote:[J. Nayler was a man who had been highly
favored of God with a good degree of grace,
which was sufficient for him, had he kept to its teachings; for while he did so,
he was exemplary in godliness and great humility, was powerful in word and doctrine,
and thereby instrumental in the hand of God, for turning many from darkness to light,
and from the power of Satan to the power of God.
But he, poor man, became exalted above measure, through the abundance of revelation;
and in that exaltation did depart from the grace and Holy Spirit of God,
which had been his sufficient teacher.
Then blindness came over him,
and he did allow himself to be accounted of above what he ought:
here he slipped and fell, but not irrecoverably;
for it did please God of his infinite mercy, in the day of his affliction,
to give him a sight and sense of his outgoings and fall, and also a place of repentance.
And he, with the prodigal, humbled himself for his transgression,
and besought God with true contrition of soul,
to pardon his offences through Jesus Christ.
God, I firmly believe, forgave him, for he pardons the truly penitent.
His people received him with great joy, for that he who had gone astray from God,
was now returned to the Father`'s house,
and for that he who had separated himself from them through his iniquity, was now,
through repentance and forsaking of it, returned into the unity of the faith,
and their holy fellowship in the gospel of Christ.
And I do hereby testify,
that I do esteem it a particular mark of God`'s owning his people,
in bringing back into unity with them, a man who had so dangerously fallen,
as did James Nayler.
And here let none insult, but take heed lest they also, in the hour of their temptation,
do fall away.
Nor let any boastingly say, "`Where is your God.`"
Or blasphemously suppose his grace is not sufficient for man in temptation,
because the tempted may go from, and neglect the teaching of it.
David and Peter,
as their transgression came by their departing from this infallible guide,
the Holy Spirit, so their recovery was only by it.--Jos.
Wyeth`'s [.book-title]#Anguis Flagel#.]

Yet to proceed further with J. Nayler: he wrote, after his recovery,
many papers and edifying letters: he also answered two letters, which,
when the persecution in New England burnt so fierce,
were sent over from there in defence of that fact; one under the name of John Endicot,
governor of Boston, and the other in that of Richard Bellingham.
All the arguments for the persecution of the Quakers to be lawful and necessary,
he answered at large,
and showed how little agreement their crime of pursuing persecution
had with the name wherewith they had called themselves,
for a distinction from other persuasions, namely.
Independents, by which they would have it known, that they were independent of all,
except the Spirit of Jesus Christ, on whom they pretended alone to be dependent: and yet,
nevertheless, it now appeared manifestly,
that it was the fleshly arm whereby they supported themselves.
He wrote also some papers to the parliament, and the rulers,
to check the vanities that were publicly committed, and to mend their faults;
to ease the oppressed, and to take care for the maintenance of liberty.

At length he died at Huntingdonshire,^
footnote:[He was a man of great self-denial, and very jealous of himself,
ever after his fall and recovery.--At last, departing from the city of London,
about the latter end of the Eighth month, 1660, towards the North,
intending to go home to his wife and children, at Wakefield, in Yorkshire,
he was seen by a friend of Hertford,
(sitting by the way-side in a very awful weighty
frame of mind,) who invited him to his house,
but he refused, signifying his mind to pass forward,
and so went on foot as far as Huntingdonshire, and was observed by a friend,
as he passed through the town, in such an awful frame,
as if he had been redeemed from the earth, and a stranger on it,
seeking a better country and inheritance.
But going some miles beyond Huntingdon, he was taken ill, (being,
as it is said,) robbed by the way, and left bound:
whether he received any personal injury, is not certainly known,
but being found in a field by a countryman toward evening, was had,
or went to a friend`'s house at Holm, not far from King`'s Rippon, where Thomas Parnel,
a doctor of medicine dwelt, who came to visit him;
and being asked if any friends at London should be sent for to come and see him;
he said '`No,`' expressing his care and love to them.
Being shifted, he said '`You have refreshed my body,
the Lord refresh your souls;`' and not long after departed this life,
in peace with the Lord, about the Ninth month, 1660, and the 44th year of his age,
and was buried in Thomas Parnel`'s burying ground
at King`'s Rippon aforesaid.--J. W.`'s account.]
in the latter end of the year 1660, about the 44th year of his age.
About two hours before his death, he spoke,
in the presence of several witnesses these words:

[.embedded-content-document.testimony]
--

There is a spirit which I feel, that delights to do no evil, nor to revenge any wrong,
but delights to endure all things, in hope to enjoy its own in the end.
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptations.
As it bears no evil in itself, so it conceives none in thought to any other:
if it be betrayed, it bears it;
for its ground and spring is the mercies and forgiveness of God.
Its crown is meekness, its life is everlasting love unfeigned,
and takes its kingdom with entreaty, and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regard it, or can acknowledge its life.
It is conceived in sorrow, and brought forth without any to pity it;
nor does it murmur at grief and oppression.
It never rejoices but through sufferings; for with the world`'s joy it is murdered.
I found it alone, being forsaken.
I have fellowship therein with them who lived in dens, and desolate places of the earth,
who through death obtained this resurrection, and eternal holy life.^
footnote:[N. B. There is a passage in the book called, [.book-title]#The Complete History of England,
Vol.
iii#. page 201, which says that J. Nayler died with no fruits,
nor so much as signs of repentance.
How the author came by such information, we cannot tell,
but that it is a manifest mistake we doubt not but
the impartial reader is by this time abundantly convinced.]

[.signed-section-signature]
James Nayler.

--

This was J. Nayler`'s last testimony, or dying words; and thus he gave proof,
that though he had erred, yet with great confidence he hoped for a happy resurrection.
So I conclude the story of J. Nayler, and leaving him now, time calls me to New England.

It was in the month called July, of this present year,
when Mary Fisher and Ann Austin arrived in the road before Boston,
before ever a law was made there against the Quakers; and yet they were very ill treated;
for before they came ashore, the deputy-governor, Richard Bellingham,
(the governor himself being out of town,) sent officers aboard,
who searched their trunks and chests, and took away the books they found there,
which were about one hundred, and carried them ashore,
after having commanded the said women to be kept prisoners aboard;
and the said books were, by an order of the council,
burnt in the market place by the hangman.
Afterwards the deputy-governor had them brought on shore,
and committed them by a court order to prison as Quakers, upon this proof only,
that one of them speaking to him, had said thou, instead of you; whereupon he said,
he needed no more, for now he saw they were Quakers.
And then they were shut up close prisoners,
and command was given that none should come to them without leave;
a fine of five pounds being laid on any that should otherwise come at,
or speak with them, though but at the window.
Their pens, ink, and paper were taken from them,
and they not allowed to have any candle-light in the night season; no, what is more,
they were stripped naked, under pretense to know whether they were witches,
though in searching, no token was found upon them but of innocence:
and in this search they were so barbarously misused, that modesty forbids to mention it:
and that none might have communication with them,
a board was nailed up before the window of the jail.
And seeing they were not provided with food, Nicholas Upshal,
one who had lived long in Boston, and was a member of the church there,
was so concerned about it, liberty being denied to send them provision,
that he purchased it of the jailer at the rate of five shillings a week,
lest they should have starved.
And after having been about five weeks prisoners, William Chichester, master of a vessel,
was bound in one hundred pounds bond to carry them back,
and not to permit any to speak with them, after they were put on board;
and the jailer kept their beds, which were brought out of the ship, and their bible,
for his fees.

Such was the entertainment the Quakers first met with at Boston, and that from a people,
who pretended, that for conscience-sake, they had chosen the wilderness of America,
before the well-cultivated old England; though afterwards,
when they took away the lives of those called Quakers, they,
to excuse their cruel actions, did not hesitate to say,
that at first they had used no punishment against the Quakers.

Scarce a month after the arrival of the aforesaid women at Boston,
there came also Christopher Holder, Thomas Thirstone, William Brend, John Copeland,
Mary Prince, Sarah Gibbons, Mary Whitehead, and Dorothy Waugh;
they were locked up in the same manner as the former, and after about eleven weeks stay,
sent back; Robert Locke, a master of a ship,
being compelled to carry these eight persons back on his own charge,
and to land them no where but in England;
having been imprisoned till he undertook so to do.

The Governor, John Endicot, whose blood-thirstiness will appear in the sequel,
being now come home, bid them '`Take heed you break not our ecclesiastical laws,
for then you are sure to stretch by a halter.`'
And when they desired a copy of those laws it was denied them;
which made some of the people say, '`How shall they know then when they transgress?
But Endicot remained stiff, having said before,
when at Salem he heard how Ann Austin and Mary Fisher had been dealt with at Boston,
'`If I had been there, I would have had them well whipped.`'
Then a law was made,
prohibiting all masters of ships from bringing any Quakers-into that jurisdiction,
and themselves from coming in, on penalty of the house of correction.
When this law was published, Nicholas Upshal, already mentioned,
could not forbear to show the persecutors the unreasonableness of their proceedings:
warning them to take heed that they were not found fighting against God,
and so draw down a judgment upon the land.
But this was taken so ill, that though he was a member of their church,
and of good repute, as a man of unblameable conduct,
yet he was fined in twenty-three pounds, and imprisoned also for not coming to church,
and next they banished '`him out of their jurisdiction.
This fine was exacted so severely that Endicot said,
'`I will not bate him one groat`' And though a weakly old man,
yet they allowed him but one month`'s space for his removal,
so that he was forced to depart in the winter.

Coming at length to Rhode Island, he met an Indian prince,
who having understood how he had been dealt with, behaved himself very-kindly,
and told him, if he would live with him, he would make him a warm house.
And further said, '`What a God have the English,
who deal so with one another about their Cod!`' For it seems Upshal was
already looked upon as one that was departing from his church-membership.
But this was but a beginning of the New England persecution, which in time grew so hot,
that some of the Quakers were put to death on the gallows,
as will be related in its due time.

Now I return to Old England, where we left G. Fox at Exeter,
from which he went to Bristol.
Here he had a great meeting in an orchard;
and since some thousands of people were come there, and many very eager to see him,
he stepped upon a great stone that stood there, and having put off his hat,
stood a pretty while silent, to let people look at him.
A Baptist was there named Paul Gwyn, who began to find fault with G. Fox`'s hair,
and at last said to the people, '`You wise men of Bristol, I strange at you,
that you will stand here, and hear a man speak,
and affirm that which he cannot make good.`'
Hereupon G. Fox asked the people whether they ever heard him speak before,
or ever saw him before?
And he bid them take notice what kind of man this Gwyn was, who so impudently said,
that he spoke and affirmed that which he could not make good;
and yet neither Gwyn nor they ever heard him, or saw him before;
and that therefore it was a lying, envious, and malicious spirit that spoke in him.
Then G. Fox charging Gwyn to be silent, began to preach, which lasted some hours,
without being disturbed.

After this meeting, G. Fox departed from Bristol, and passing through Wiltshire,
Marlborough, and other places, he returned to London; and when he came near Hyde Park,
he saw the Protector coming in his coach; whereupon he rode up to the coach side,
and some of his lifeguard would have put him away; but the protector forbade them.
Then riding by his coach side,
he spoke to him about the sufferings of his friends in the nation,
and showed him how contrary this persecution was to Christ and his apostles,
and to Christianity.
And when they were come to the gate of St. James`'s Park, G. Fox left Cromwell,
who at parting desired him to come to his house.
The next day Mary Sanders, afterwards Stout, one of Cromwell`'s wife`'s maids,
came to G. Fox`'s lodging, and told him, that her master coming home,
said he would tell her some good news; and when she asked him what it was,
he told her G. Fox was come to town; to which she replied, that was good news indeed.
Not long after, G. Fox and Edward Pyot went to Whitehall,
and there spoke to Cromwell concerning the sufferings of their friends,
and directed him to the light of Christ,
who had enlightened every man that comes into the world.
To which Cromwell said.
This was a natural light; but they showed him the contrary,
saying that it was divine and spiritual, proceeding from Christ,
the spiritual and heavenly man.
Moreover G. Fox bid the protector lay down his crown at the feet of Jesus.
And as he was standing by the table, Cromwell came and sat upon the table`'s side by him,
and said he would be as high as G. Fox was.
But though he continued to speak in a light manner,
yet afterward was so serious that when he came to his wife and other company,
he said that he never parted so from the Quakers before.

G+++.+++ Fox having visited the meetings of his friends in and about London,
departed from there, and travelled almost through all England,
not without many occurrences, which for brevity`'s sake I pass by.
At length he returned to London again, this year being now come to an end.

In the parliament which Cromwell had called,
a law was made whereby Charles Stuart`'s title of king was rejected,
and the year 1657 being come, subsidies were granted to Cromwell,
and there was a contrivance underhand to make him king, of which,
though he expressed his dislike, yet he seemed not altogether averse to it;
for speaking once with general Fleetwood, and colonel Desborough,
he began to droll with them about the word monarch, and said,
it was but a feather in a man`'s cap;
and therefore he wondered that men would not please the children,
and permit them to enjoy their rattle.
But they not obscurely signified to him, that this business did displease them;
and told him, that those who put him upon it, were no enemies to Charles Stuart;
and that if he accepted of it, he would infallibly draw ruin upon himself.
Now, though he would not openly oppose them, yet he did not hesitate to tell them,
they were a couple of scrupulous fellows, and so left them.
It is related also, that major-general Lambert told Cromwell,
that if he accepted the crown, he could not assure the army to him.
The design thus miscarrying,
and Cromwell having now seen that the matter would not go so cleverly,
he refused the title of king;
and the parliament confirming him in his title of protector,
it was agreed that the parliament henceforth should consist of a lower house,
and another house; and that the protector should name a successor in the government.
Now he was solemnly vested in his authority,
a throne for that purpose being erected in Westminster Hall,
and he being clothed in a purple robe lined with ermines,
and the sceptre and sword being presented him, took the oath to rule faithfully.
Cromwell having called a new parliament, it consisted of two houses, namely,
a house of commons, and another house as they called it.
And many excluded members having taken place again in the house of commons,
it was believed that more than a hundred of the members were enemies to Cromwell;
and the authority of the upper house began to be called in question by some,
because it was filled up with many of his creatures, some of them of low rank.
And this matter was so carried on in the house of commons,
that Cromwell dissolved the parliament;
and he also made major-general Lambert surrender his commission.

Edward Burrough, who often wrote to Cromwell,
having heard of the design of making him king, wrote a letter to him, wherein I find,
that after having told the protector, that he had had many warnings from the Lord,
he thus speaks to him:

[.embedded-content-document.letter]
--

I as one that has obtained mercy from the Lord, and unto whom his word is committed,
being moved of him, do hereby in his presence yet once more warn you,
that you fear before him, and diligently hearken to him,
and seek him with all your heart, that you may know his will and counsel concerning you,
and may do it, and find favor in his sight, and live.
Now is the day that his hand is stretched forth unto you,
to make you a blessing or to leave you a curse forever;
and the days of your visitation are near an end, when God will no more call unto you,
nor hear you, when in the day of your trouble you call to him.
And if you reject the counsel of the Lord, and follow the desires of your own heart,
and the wills of men, and will not have the light of the world, Christ Jesus,
only to rule you, and to teach you, which condemns all evil,
then shall evil surely fall upon you, if you love not the light in you which condemns it;
and the judgments of God, nor the day of his last visitation with vengeance,
you may not escape.
Therefore consider and mark my words, and let this counsel be acceptable unto you;
let it move you to meekness, to humbleness, and to fear before the Lord;
assuredly knowing that it is he that changes time and things, and that brings down,
and sets up whomsoever he will; and how that you were raised from a low estate,
and set over all your enemies.
And in that day when you were raised up, when the fear of the Lord was before your face,
and your heart was towards him, and you were but little in your own eyes,
then was it well with you, and the Lord blessed you.
And it was not once thought concerning you,
that the hands of the ungodly would have been strengthened
against the righteous under you,
or that such grievous and cruel burdens and oppression
would ever have been laid upon the just,
and acted against them in your name, and under your dominion,
as unrighteously have come to pass in these three years:
and this your suffering of such things is your transgression,
and you have not requited the Lord well for his goodness unto you,
nor fulfilled his will in allowing that to be done under you, and in your name,
which the Lord raised you against, and to break down, have you been faithful to the end.

Again, consider, and let it move on your heart, not to exalt yourself,
nor to be high-minded, but to fear continually, knowing that you stand not by yourself,
but by another, and that he is able to abase you,
and give you into the will of your enemies whensoever he will;
and how the Lord has preserved you sometimes wonderfully, and does unto this day,
from the murderous plots, and crafty policy of evil men, who seek your evil,
and would rejoice in your fall, and in the desolation of your family and countries:
how have they, and do they lay snares for your feet,
that you may be cut off from among men, and die unhappily, and be accounted accursed.
And yet to this day he has preserved you, and been near to keep you,
though you have hardly known it; and the Lord`'s end is love to you in all these things,
and yet a little longer to try you, that you may give him the glory.

O that your heart were opened to see his hand, that you might live unto him,
and die in him, in peace.
And beware lest hardness of heart possess you, if you slight his love,
and so be shut up in darkness and given to the desires of your enemies,
and left to the counsels of treacherous men, who may seek to exalt you by flattery,
that they may the better cast you down, and destroy you,
and blot out your name in reproach, and make your posterity a people miserable.
But now, O consider, and let it enter into your heart,
for you have not answered the Lord, but been lacking to him, for all this,
and have chosen your own way and glory, rather than his,
and not fulfilled his counsel in raising you;
for the bonds of cruelty are not loosed by you,
and the oppressed are not altogether set free;
neither is oppression taken off from the back of the poor, nor the laws regulated,
nor the liberty of pure consciences altogether allowed:
but these dominions are filled with cruel oppressions,
and the poor groan everywhere under the heavy hand of injustice;
the needy are trodden down under foot, and the oppressed cry for deliverance,
and are ready to faint for true justice and judgment.

The proud exalt themselves against the poor,
and the high-minded and rebellious contemn the meek of the earth;
the horn of the ungodly is exalted above the Lord`'s heritage,
and they that are departed from iniquity, are become a prey to oppressors:
and the cruel-hearted deal cruelly with the innocent in these nations.
Many are unjustly, and woefully sufferers, because they cannot swear on this,
or that occasion; though in all cases they speak the truth,
and do obey Christ`'s commands, even such are trodden upon,
by unjust fines charged upon them;
and this is by the corruptness of some that bear rule under you,
who rule not for God as they ought, but turn the sword of justice.
Some suffer long and tedious imprisonments, and others cruel stripes and abuses,
and danger of life many times, from wicked men, for reproving sin,
and crying against the abominations of the times,
(which the Scriptures also testify against,) in streets, or other places:
some having been sent to prison, taken on the highway, and no evil charged against them;
and others committed, being taken out of peaceable meetings, and whipped,
and sent to prison, without transgression of any law, just or unjust,
wholly through the rage and envy of the devil,
and such who have perverted judgment and justice;
and some in prison have suffered superabundantly
from the hands of the cruel jailers and their servants,
by beatings and threatenings, and putting irons on them,
and not permitting any of their friends to visit them with necessaries;
and some have died in the prisons, whose lives were not dear to them,
whose blood will be reckoned on account against you one day.
Some have suffered hard cruelties, because they could not respect persons,
and bow with hat or knee;
and from these cruelties can you not altogether be excused in the sight of God,
being brought forth in your name, and under your power.
Consider, friend, and be awakened to true judgment, and let the Lord search your heart;
and lay these things to mind, that you may be an instrument to remove every burden,
and may at last fulfill the will of God.
O be awakened, be awakened, and seek the Lord`'s glory, and not your own;
lest you perish before the Lord and men: no, if men would give you honors,
and high titles, and princely thrones, take them not;
for that which would exalt and honor you in the world, would betray you to the world,
and cast you down in the sight of the world: and this is God`'s word to you:
what! shall the whole nation be perjured men, and you the cause of it?
And will you transgress by building again that which you have destroyed?
Give heed unto my words, and understand my speech: be not exalted by man,
lest man betray you.
Deal favorably, and relieve the oppressed; boast not yourself,
though the Lord has used you in his hand; but know that when he will, he can cast you,
as a rod, out of his hand, into the fire; for in his hand you are.
If you will honor him, he will honor you; otherwise he can, yes, and will confound you,
and make you weak as water before him.
His love through my heart breathes unto you: he would your happiness,
if you willfully contemn it not, by exalting yourself, and seeking your own glory,
and hardening your heart against the cry of the poor.
This I was moved in bowels of pity to lay before you, who am your friend,
not in flattery, but in an upright heart, who wishes well unto you in the Lord.

[.signed-section-signature]
Edward Burrough

--

That which Edward Burrough mentions in the forepart of this letter,
of the grievous burdens and oppression laid upon the just,
seems chiefly to regard the tithes which the priests extorted from the Quakers,
so that many thereby were reduced to poverty;
and the heinousness of this was not unknown to Cromwell;
for when he was about to give battle to his enemies, near Dunbar in Scotland,
he said in his prayer to God,
that if the Lord would be pleased to deliver him at that time,
he would take off that great oppression of tithes.
But this promise he never performed,
but allowed himself to be swayed by the flatteries of his teachers;
and therefore it was not without great cause that Edward
Burrough laid this grievous oppression before him.
A copy of the said letter, of which but a part is inserted here, to shun prolixity,
was given into the hands of Oliver Cromwell, then protector,
in the Third month of this year.
In the next month Edward Burrough spoke with him about it,
and Cromwell told him in effect that all persecution and cruelty was against his mind,
and said that he was not guilty of those persecutions
acted unjustly upon Burrough`'s friends.
This made Edward Burrough write again to him, and bid him,

[.embedded-content-document.letter]
--

Consider what the cause is,
that what you desire not to be done, is yet done: is it not that you may please men;
making it appear you are more willing to do the false teachers of this nation,
and wicked men, a pleasure, than to acknowledge the people of God, in relieving them,
and easing them of their cruel burdens and oppression, laid upon them by unjust men?
For a word of your mouth, or a show of your countenance,
in dislike of these cruel and unjust persecutions,
would bind the hands of many blood-thirsty men.
Therefore consider: you can not be cleared in the sight of the Lord God from them,
being acted under you, and in your name:
for there seems rather to be a favoring of them in you,
by forbearance of the actors of cruelty, by which their hands are strengthened,
than any dislike showed by you, in bearing your witness, as you ought to do,
against them.
For you know of some in this city, and elsewhere, whom we know to be just men,
who suffer imprisonment, and the loss of their liberties,
because for conscience-sake they cannot swear; and many others in this nation,
suffering cruel things upon the like, or same ground: even for well-doing,
and not for evil; which oppression might be removed,
and their unjust sufferings taken off by you, by a word from your mouth or pen;
and this makes that you can not be clear in the sight of God in these things,
because not helped by you, who have the power to help it.

And as concerning the light of Christ, at which you stumbles,
by which every man that comes into the world is enlightened, in short, this I say:
this light to you is given of God, and you must acknowledge it to be your only teacher,
to receive by it from the Father, and to be guided by it in all things,
if ever you inherit God`'s kingdom.

The kingdom of Christ is setting up by his own power,
and all must bow and become subject thereto; he needs none of your policy,
nor the strength of your arm to advance it;
yet would he have you not to prove yourself an open enemy thereof, by doing,
or allowing to be done,
cruelty and injustice against them whom the Lord is redeeming out of this world,
into subjection unto that kingdom; lest you be such a one, as will not enter yourself,
nor permit others to enter, and so destruction come upon you.
Wherefore arise as out of sleep, and slumber not in this world`'s glory and honor;
be not overcome by the pleasures of this world, nor the flattering titles of men;
wink not at the cruelty and oppression acted by some, who shelter under you,
and make your name a cloak for mischief against the upright.

Consider, I say, consider, and be changed in your mind and heart;
least you having forgotten God, and his many deliverances, be shut up,
and numbered for destruction.
I desire the Lord may give you a more perfect understanding of his ways and judgments,
and that the crown immortal you may strive for, by meekness and righteousness,
through relieving the oppressed, and showing mercy to the poor,
and removing every burden which lies upon the innocent;
and this is the desire of him who is your friend,
and would not have you crowned with dishonor,
through suffering the people of God to be oppressed in your name,
which will be your overthrow absolutely, if you removes! it not, by turning,
and easing the oppressed.

[.signed-section-signature]
E+++.+++ Burrough

--

This letter was delivered to Oliver Cromwell, in the Fourth month,
and in the month following Edward Burrough wrote again to him,
that the good name PROTECTOR, by the great oppression, acted in his name,
was abused and subverted; and that instead of protection by it,
great injustice was acted under it, and covered with it.
Besides, that several justices of the peace, and other officers, in trust under him,
when they had approved the people called Quakers, had been cast out of their places;
though they had not denied to serve him and the commonwealth,
neither had unfaithfulness to their trust been proved against them.

In September, E. Burrough wrote another letter to Cromwell, wherein he signified to him,
that he had many enemies, some of which endeavored to destroy him by any means,
without regarding the danger that might be in the attempt.
And that he going on in oppressing through tyranny, or allowing it,
perhaps the Lord might raise up the wicked to be a plague to wickedness,
and permit the oppressors to overthrow oppression.
That there were others, namely, the Fifth Monarchy men, who,
though not so bad as the former, yet secretly murmured against him, and envied him,
not being friends to his government, some of them being cast out and rejected,
without just cause, as they supposed.
'`And as to us, how can we, (said he,) mention you in our prayers to God,
except it be to be delivered from you, who are daily unjustly sufferers by you,
or because of you?
Or how can we be friends to that government,
under which we daily suffer such hard and cruel things,
as the loss of our liberty and estates, and are in danger of life also?`'

It was about the beginning of this year, that Christopher Birkhead came to Zealand,
having been before at Rochelle, in France?
where, having spoken and written against the Catholic religion,
he was imprisoned and examined by the bishop: and some would have had him burnt,
but the criminal judge absolved him.
It was in the latter end of the month called February, when he came to Middleburgh,
in Zealand; and going to the English congregation there, after the preacher,
William Spanke, had preached about three quarters of an hour, he said, '`Friends,
the apostle says, that we may all prophesy, one by one;
that two or three prophets may speak, and the others judge;
and if any thing be revealed to another that sits by, let the first hold his peace.`'
This speaking caused a great stir in the congregation, and the rather,
because he stood in the place where the women used to sit:
so he was apprehended by order of the magistrates,
and examined in the presence of some of the public preachers.
When he was asked what his name was?
He answered, that his name, according to the flesh, was Christopher Birkhead.
Then it was asked him, whether he had yet another name?
And his answer was, '`Yes, written in the Lamb`'s book of life.`'
Being inquired what that name was, he made answer, '`None knows it but he that has it.`'
To which was said, '`Why, if you have it, tell it us.`'
'`No,`' replied he, '`read it, if you have seen the book of the Lamb opened:
it is forbidden me to tell it.`'
Then the English teacher, Spanke, asked whether he had seen the book of the Lamb opened?
And he answered, '`Yes.`'
The next question was, whether he had opened it?
'`No,`' said Birkhead, '`it was the Lamb that did it.`'
Then Spanke asked, whether his name in the book of the Lamb was not Jesus.
'`No,`' quoth Birkhead, '`that is the name of the Lamb.`'
More other questions to ensnare him, Spanke put to him;
and being examined by the magistrates concerning the place of his abode,
his calling or trade, etc.
Spanke was asked, what he had to say against him.
Who then related what had happened in the congregation.
Concerning this, several questions were asked of Birkhead,
but since he understood not Dutch, and the French tongue but imperfectly,
he complained that he could not fully answer for himself so as he wished.
He was asked also, whether any body else came along with him?
And he was charged to speak the truth.
To which he said, that God did not permit him to lie.
One of the preachers then said that all men were liars.
To this Birkhead replied, that though all men were liars,
yet he knew a deliverance from lying.
Then Spanke bid him, not to add to the Scriptures:
for Birkhead had accused him a little before,
that he had added his meaning to the Scriptures.
And it being strongly asserted, that all men were liars,
Birkhead took occasion from there, to ask Spanke whether he was a liar?
Who, without hesitation, answering, '`Yes,`' Birkhead bluntly told him,
'`Then you are of your father the devil.`'
Now the matter of J. Nayler having caused strange reports of the Quakers everywhere,
and Birkhead, for lack of the language,
not being able to answer so plainly every objection, his offence, without question,
was aggravated the more; and the conclusion was,
that he was sentenced to be confined in the house of correction.
But after some time he was released, at the intercession of the Heer Newport,
ambassador of the States General in England.

In this year it was, I think, that one George Baily coming into France,
was taken into custody, and died in prison there;
he having zealously testified against popery,
and spoken boldly against worshipping of images.

William Ames returning this year to Amsterdam, and one Humble Thatcher,
(whom I could never learn to have been truly in communion
with the Quakers,) coming with him,
it caused some jealousy: for Ames, who formerly had been in military employment,
was an extraordinary bold man; and about this time it seems,
a paper was put on the door of the English meeting-house,
though Ames declared he knew nothing of it, or who was the author.
About this time also, the strange business of J. Nayler being noised abroad,
by a book that was published in print at Amsterdam, and some other pamphlets,
stuffed with several untruths, and abominable lies; it was not to be wondered at,
that the magistrates fearing some mischief,
sent for Ames and Thatcher to appear before them,
and commanded them to depart the town within twenty four hours:
but they being persuaded of their own innocence, did not obey this command.
The next day appearing again before the magistrates, and not putting off their hats,
it seems they were looked upon as such as did not acknowledge magistrates;
(for this the Quakers stood charged with in public print,
and were compared to the tumultuous crew of Anabaptists, or Fifth Monarchy men,
at Munster, in the foregoing age:) and so they were kept in custody for some days,
and then at night were led through the Regulars gate, and so banished out of the town.
But William Ames judging that he had committed no evil,
came again the next day into the city, and passed the great market-place, called the dam.
It is reported,
that some of the magistrates seeing him out of the windows of the town-house,
walking along the street, said, '`Lo, there`'s the Quaker;
if we had a mind now to make martyrs, here would be an opportunity for it.`'
But it seems not without reason, that it was looked upon to be most safe to wink at this;
for though strange reports were spread up and down of the Quakers,
yet there was no proof of their evil carriage here.
Meanwhile Ames stayed some time in town,
and the doctrine he preached found a little entrance, even with some of the collegians.

It was about this time, that my parents, Jacob Williamson Sewel, of Utrecht,
free citizen and Surgeon at Amsterdam, and his wife, Judith Zinspenning,
born in this town, both members of the Flemish Baptists church there,
were convinced of the Truth preached by W. Ames;
she having before had immediate openings, that if ever she would become a child of God,
she must give heed to this light, which reproved for sin.
They, with two or three more, were the first orthodox Quakers in Amsterdam;
orthodox I say,
because I very well remember what a strange and odd sort of people about that time,
did flock to the Quakers in this country.
But these whimsical people not being sincere in heart: but more inclined to novelties,
than to true godliness; perceived in time that they were not regarded by them:
and they were also contradicted by Ames and others;
so that at length after many exorbitances, they left the Quakers.

In the forepart of this year, William Caton came also to Amsterdam.
Before he left England, he had had a meeting at the east side of Sussex,
on the day called Shrove Tuesday, where there had never been any of his friends before.
But the people being on that day more rude than ordinary,
came up to the house with a drum, in such a desperate manner,
as if they would have pulled the house down.
Caton stepping out, asked what they wanted; they answered, Quakers;
at which he told them he was one.
And he spoke so plainly to them, and with so much power, that fear falling upon them,
they withdrew with shame and confusion.

Not long after he went to London, and from there to Holland;
and being safely arrived at Rotterdam, he repaired to Amsterdam;
where he came in due time to stop the unruliness of some froward spirits,
among which one Anne Garghil, an English woman, was not one of the least:
whose rudeness grew in time to that degree,
that she would not permit W. Ames to preach peaceably in the meeting,
but laid violent hands on him; so that at length to be rid of her,
he bade an English seaman that was present, to take her away, which was done accordingly:
and how haughty she was, and continued, I well remember still.
W+++.+++ Caton procured also some books to be printed at Amsterdam,
to prevent evil and malicious reports concerning the Quakers;
and he went with W. Ames to Zutphen in Gelderland;
where meeting with nothing but opposition, he returned to Amsterdam,
and from there by Leyden and the Hague, to Rotterdam;
from which place he went to Zealand,
where he wrote the book called [.book-title]#The Moderate Enquirer Resolved#, both in Latin and English,
which was afterwards translated indifferently into Dutch.
After some stay, Caton returned again to England, and came to London,
where the society of his friends was in a thriving condition,
and many were added to the church.

In this city we left G. Fox:
he wrote there several papers for the opening of the understandings of people,
and for the edification of his friends.
From there he travelled into Kent, Sussex, and Surry; and coming to Basingstoke,
though the people were rude there, yet he had a quiet meeting in the place:
in the inn he had some trouble with the innkeeper, who was a drunkard.
Afterwards he came to Portsmouth, Exeter, Bristol, and into Wales, where many came to him.
At Brecknock, (where he was accompanied by Thomas Holmes, who,
first of the Quakers in Wales, had preached the doctrine of the inward light;
and by John-ap-John,
who three years before had been sent by a priest out of Wales into the North,
to inquire what kind of people the Quakers were;)
he had a great meeting in the steeple-house yard,
where was a priest, and one Walter Jenkin who had been a justice, and another justice.
Here he preached so effectually, that many were convinced: and after the meeting,
he went with Jenkin to the other justice`'s house, who said to him,
'`You have this day given great satisfaction to the people,
and answered all the objections that were in their minds.`'
At Leominster he had a great meeting, where priest Tombs made some opposition, by saying,
that the light G. Fox spoke of, was but a natural light;
but G. Fox asserted the contrary, and said,
that he had spoken of no other light than John bore witness
to--"`The Word which was in the beginning with God,
and which Word was God;
and that was the true light which enlightens every man that comes into the world.`"

G+++.+++ Fox coming from this place to Tenby, as he rode in the street,
a justice of peace came out and desired him to alight, and to stay at his house,
which he did; and on the First-day of the week had a meeting there,
where the mayor and his wife, and several others of the chief of the town came.
John-ap-John, who was then with G. Fox, left the meeting, and went to the steeple-house,
and was by the Governor cast into prison.
The next morning the governor sent one of his officers to the justice`'s house,
to fetch G. Fox; which grieved the mayor and the justice,
and so they went up to the Governor, and a while after G. Fox went with the officer,
and coming in,
said '`Peace be unto this house;`' and before the Governor could examine him, he asked,
why he had cast his friend into prison?
and the governor answered, '`For standing with his hat on in the church.`'
'`Why,`' resumed G. Fox,`' had not the priest two caps on his head,
a black one and a white one?
And if the brim of the hat, which was but to defend from the weather, had been cut off,
then my friend would have had but one cap,`' '`These are frivolous things,`' said the governor:
'`Why then,`' said G. Fox, '`do you cast my friend into prison for such frivolous things?`'
Then the governor asked him, whether he believed in election and reprobation?
'`Yes,`' said he, '`and you are in the reprobation.`'
This so incensed the governor, that he told G. Fox, he would send him to prison,
till he proved it.
G+++.+++ Fox not at all at a loss, said, '`I will prove that quickly,
if you will but confess truth:`' and then he asked him, whether wrath, fury, and rage,
and persecution, were not marks of reprobation?
For he that was born of the flesh, persecuted him that was born of the spirit;
and Christ and his apostles never persecuted nor imprisoned any.
This speech of his so struck the governor, that he fairly confessed,
that he had too much wrath, haste, and passion in him: which made G. Fox say,
that Esau the first birth was up in him, not Jacob the second birth.
By this the man was so reached, that he confessed to Truth,
and inviting G. Fox to dinner with him, he set his friend at liberty.
It was with great satisfaction that G. Fox departed the town;
and in several other places of Wales he had some singular occurrences;
and though the people were rude, yet some were convinced.

At length he came to Lancaster, where, at the inn, he met with colonel West,
who was very glad to see him.
Next he came to Swarthmore, where he wrote some epistles and other papers.
After having stayed there some days, he went to some other places in the North,
and to Scotland.
Here, traveling from town to town, he met with great opposition from some priests:
for in an assembly, they had drawn up several articles, or curses,
to be read in their steeple-houses, the first of which was,
'`cursed is he that says every man has a light within him sufficient to lead him to salvation:
and let all the people say.
Amen.`'
An independent pastor preaching one day against the Quakers, and the light,
and calling the light natural, cursed it, and so fell down as dead in his pulpit;
the people carrying him out, and pouring strong waters into him,
it brought him to life again; but he was mopish, and, as one of his hearers said,
he never recovered his senses.

In October G. Fox came to Edinburgh, where he was summoned to appear before the council,
who, though indifferently civil, yet told him,
he must depart the nation of Scotland by that day seven-night:
against which he not only spoke but wrote also.
While G. Fox was in Scotland, his friends there were brought to a great strait; for,
being excommunicated by the Presbyterian teachers, charge was given,
that none should buy or sell, nor eat nor drink with them.
Hence it came to pass, that some having bought bread, or other provisions,
of their neighbors, these frightened with the curses of their priests, did run,
and fetch it from them again.
But colonel Ashton, a justice of peace, put a stop to these proceedings,
and being afterwards convinced of the Truth, had a meeting settled at his house,
and declared the Truth, and lived and died in it.

G+++.+++ Fox now travelled almost over all Scotland,
and had in some places good opportunities to declare the gospel,
being often heard with satisfaction by the English soldiers;
but the Scotch generally gave little heed.
He went also among the Highlanders, who were a mischievous people.
Returning at length to Leith, the innkeeper told him,
that the council had granted forth warrants to apprehend him,
because he was not gone out of the nation after the seven days were expired,
that they had ordered him to depart in.
Some others told him the same, to whom he said,
'`What do you tell me of their warrants against me?
If there were a cart load of them I do not heed them;
for the Lord`'s power is over them all.`'
From Leith he went to Edinburgh again, and went to the inn where he had lodged before,
and no man offered to meddle with him.
Alexander Parker and Robert Widders being also there,
he resolved to go with Parker to Johnston,
out of which town some time before he had been led by soldiers;
and he came into Johnston just as they were drawing up the bridges,
the officers and soldiers never questioning him.
And coming to captain Davenport`'s house, from which he had been hauled before,
he found there many officers, who lifting up their hands, wondered that he came again;
but he told them, the Lord God has sent him among them again.
Then the Baptists sent him a letter by way of challenge,
that they would discourse with him again the next day.
And he sent them word, that he would meet them at a certain house,
about half a mile out of the town, at such an hour.
For he thought if he should stay in town to speak with them, they might,
under pretence of discoursing with him,
have raised people to carry him out of the town again, as they had done before.
At the time appointed he went to the place,
captain Davenport and his son accompanying him; and there he stayed some hours,
but none of them came; whereby the intent of the Baptists was sufficiently discovered.
Being thus disappointed, he went back again to Edinburgh, and past through the town,
as it were, against the cannon`'s mouth.
The next day, being the first day of the week, he went to the meeting in the city,
and many officers and soldiers came to it, and all was quiet.
The following day he went to Dunbar,
where walking with a friend or two of his in the steeple-house yard,
and meeting with one of the chief men of the town there;
he spoke to one of his friends to tell him, that about the ninth hour next morning,
there was to be a meeting there, of the people of God, called Quakers,
of which they desired him to give notice to the people of the town.
To which he said, that they were to have a lecture there by the ninth hour;
but that a meeting might be kept there by the eighth hour, if they would.
G+++.+++ Fox thinking this not inconvenient, desired him to give notice of it.
Accordingly in the morning many came, both poor and rich;
and a captain of horse being quartered in the town, came there with his troopers also.
To this company G. Fox preached, and after some time the priest came,
and went into the steeple-house;
but G. Fox and his friend being in the steeple-house yard,
most of the people stayed with them; so that the priest having but few hearers,
made short work, and coming out, stood a while and heard G. Fox, and then went away.
This was the last meeting he had in Scotland, and he understood afterwards,
that his labor had not been in vain, but that the number of believers increased.
Now he departed from Dunbar, and came to Berwick in Northumberland,
and from there to Newcastle, where we will leave him awhile,
and return again to New England.

We have seen before, that a law was made there,
to prevent the Quakers coming into that country.
The first I find that came after that, were Anne Burden, a widow,
whose business was to gather up some debts in the country, that were due to her;
and Mary Dyer from Rhode Island, who, before her coming,
knew nothing of what had been done there concerning the Quakers.
These two were both imprisoned, which William Dyer, Mary`'s husband, hearing,
came from Rhode Island, and did not get her released without a great deal of pains;
becoming bound in a great penalty, not to lodge her in any town in that colony,
nor to permit any to speak with her:
an evident token that he was not of the society of Quakers, so called,
for otherwise he would not have entered into such a bond; but then without question,
he would also have been clapped up in prison.
As for Anne Burden, she was kept in prison, though sick, about a quarter of a year.
While she was in this restraint,
some tender-hearted people had procured of her debts
to the value of about thirty pounds in goods;
and when she at length was to be sent away,
she desired that she might have liberty to pass for England, by Barbados,
because her goods were not fit for England.
Now how reasonable soever this request was,
yet a master of a ship was compelled to carry her to England, without her goods,
for which she came there, except to the value of about six shillings,
which an honest man sent her upon an old account.
And when the master of the ship asked who should pay for her passage,
the magistrates bid him take so much of her goods as would answer it.
But he was too honest to do so, being persuaded that she would not let him be a loser,
though he could not compel her to pay, since she went not of her own will:
yet for all that she paid him at London.
After she was gone, when he that had the first trust from her husband,
was to convey her goods to Barbados,
these rapacious people stopped to the value of six pounds ten shillings for her passage,
for which they paid nothing,
and seven shillings for boat-hire to carry her on ship-board,
though the master offered the governor to carry her in his own boat,
but that was not allowed; she being sent with the hangman in a boat that was pressed:
besides, they took to the value of fourteen shillings for the jailer,
to whom she owed nothing.
Now, though this widow had made such a great voyage,
to get something of what was due to her, to relieve her, and her fatherless children,
yet after three years she had nothing of it come to her hands;
and whether she got any thing since I never understood.

The next of the Quakers that came to Boston, was Mary Clark, who,
having left her husband, John Clark, a merchant taylor, with her children at London,
came there to warn these persecutors to desist from their iniquity:
but after she had delivered her message,
she was unmercifully rewarded with twenty stripes of a whip with three cords,
on her naked back, and detained prisoner about twelve weeks in the winter season.
The cords of these whips were commonly as thick as a man`'s little finger,
having each some knots at the end; and the stick was sometimes so long,
that the hangman made use of both his hands to strike the harder.

The next that came were Christopher Holder and John Copeland,
who had been banished before; and coming to Salem, a town in the same colony.
Holder spoke a few words in their meeting, after the priest had done;
but was hauled back by the hair of his head,
and a glove and handkerchief thrust into his mouth, and so turned out with his companion;
and next day had to Boston,
where each of them received thirty stripes with a knotted whip of three cords,
the hangman measuring his ground,
and fetching his strokes with the greatest strength he could:
which so cruelly cut their flesh, that a woman seeing it fell down as dead.
Then they were locked up in prison, and the jailer kept them three days without any food,
not giving them so much as a swallow of water;
and so close that none might come to speak with them;
lying on the boards without bed or straw.
Thus they were kept nine weeks prisoners, without fire, in the cold winter season.
And Samuel Shattock, of Salem,
who endeavored to stop the thrusting of the glove and handkerchief into Holder`'s mouth,
lest it should have choked him, was also carried to Boston, and there imprisoned,
till he had given bond for twenty pounds, to answer it at the next court,
and not to come at any meeting of the Quakers.

The career of this cruelty did not stop here; for Lawrence Southick and Cassandra,
his wife, members of the public church at Salem, and an ancient and grave couple,
having entertained the aforesaid C. Holder and J. Copeland, were committed to prison,
and sent to Boston, where Lawrence being released,
his wife was kept seven weeks prisoner,
and then fined forty shillings for owning a paper of exhortation,
written by the aforesaid Holder and Copeland.

The next that came from England,
as being under a necessity from the Lord to come to this land of persecution,
was Richard Dowdney, who was apprehended at Dedham, and brought to Boston,
having never before been in that country; yet he was not spared for all that,
but thirty stripes were also given him in like manner as the former.
And after twenty days imprisonment, he was sent away with Holder and Copeland;
after having been threatened with cutting off their ears, if they returned.
These cruel dealings, so affected many inhabitants,
that some withdrew from the public assemblies,
and meeting by themselves quietly on the First days of the week,
they were fined five shillings a week, and committed to prison.
The first whose lot this was, were the aforesaid Lawrence and Cassandra Southick,
and their son Josiah, who, being carried to Boston, were all of them,
notwithstanding the old age of the two, sent to the house of correction,
and whipped with cords, as those before, in the coldest season of the year,
and had taken from them to the value of four pounds thirteen shillings,
for not coming to church.

Leaving New England for a while, I will turn another way.
It was in this year, about the latter end of summer,
that a certain young man named George Robinson, felt a motion to travel to Jerusalem.
In order thereunto, he embarked in a ship bound for Leghorn, in Italy, where,
having stayed about two weeks, being daily visited by English and others,
he went with a French ship towards St. John D`'Acre, formerly called Ptolemais,
a city in Asia bordering upon the Mediterranean sea, near Palestine, where,
having lodged about eight days in a French merchant`'s house,
he embarked in a vessel bound for Jaffa or Joppa.
What occurred by the way with some Turks, who demanded unreasonable tribute of him,
I pass by; but a certain Armenian on that occasion having seen his meek behavior, said,
he was a good Christian, and was very kind to him.
Being arrived at Jaffa, he went to Ramoth,
but the Friars at Jerusalem having heard of his coming, gave orders to some to stop him,
which was done accordingly; and after having been locked up about a day,
there came an ancient Turk, a man of great repute, who took him into his house,
and courteously entertained him.
After four or five days there came an Irish friar from Jerusalem, with whom,
falling into discourse of religious matters, the friar at first behaved himself kindly,
but told him afterwards, that was not the business he came about,
but that he was sent from his brethren, the friars, at Jerusalem,
to propound to him some questions.

[.numbered]
1+++.+++ Whether he would promise, when he came to Jerusalem,
that he would visit the holy places as other pilgrims did?

[.numbered]
2+++.+++ Whether he would pay so much money as pilgrims used to do?

[.numbered]
3+++.+++ Whether he would wear such a sort of habit as was usual with pilgrims?

[.numbered]
4+++.+++ That he must speak nothing against the Turks laws.

[.numbered]
5+++.+++ And when he came to Jerusalem, not speak any thing about religion.

Not being willing to enter into a promise, he was by the Irish friar,
(with a guard of horse and footmen, he brought with him,) carried back to Jaffa,
and embarked in a vessel bound for St. John D`'Acre; where being come,
a French merchant called Surrubi, took him into his house,
and lodged him about three weeks.
This man entertained him very kindly,
and would say sometimes that it was the Lord`'s doings;
'`For,`' said he, `'when my own countrymen come to me, they are little to me,
but you I can willingly receive.`'
After much trouble, Robinson got opportunity, by the help of the said French merchant,
who was an ancient man, to return by sea to Jaffa;
from which he went on his journey a-foot, and by the way met three men,
two of them riding upon asses, and the other going a-foot; and they asking him for money,
one held his gun to his breast, and another put his hands into his pockets,
and took some things out.
He suffering all this without any opposition,
the man that took his things from him put them up again;
and one of the three taking him by the hand, led him a little on his way,
in a friendly manner, and so left him.
At length Robinson came to Ramoth, where he was presently known,
and two that belonged to the friars laid hold on him, and hurried him away;
but two Turks took him from them, and one leading him by one arm,
and the other by the other, they brought him into a mosque, or Turkish temple.
Thus innocently entering there, many people came flocking in,
and also some of the Mahometan priests, who having caused him to sit down,
asked him whether he would turn to the Mahometan religion?
But he refusing, they pressed him much, made great promises,
and said that he had no need to fear what the Christians might do unto him.
Nevertheless he answered he could not turn unto them for all the world.
But they continued to strive much with him,
and would have him hold up one of his fingers, as a sign of acknowledging them;
and one bid him say, '`Christ is bad;`' but he answered, he knew him to be good,
and he was his servant.
Then some growing angry, said if he would not turn to their religion, he would die.
To which he replying that he would rather die than turn unto them; it was answered,
he should then die.
And so by their order,
the executioner hauled him away to the place where it was expected
that he should have been burnt to death with camel`'s dung.
Here he was made to sit down upon the ground, and was as a sheep among wolves.
While he was thus sitting with a retired mind,
the Turks began to fall out among themselves, and while they were at odds,
a grave ancient Turk, a man of note, came to him,
and said whether he would turn from his religion or not, he should not die.
Then he was brought before the priests again, who asked him, '`Will you turn?
and he answering '`No,`' they recorded in a book, that he was no Roman Catholic,
but of another religion; for though he denied to be such a Catholic,
yet he had acknowledged that he was a Christian.

The Turks coming now to be more sedate,
the aforesaid ancient man ordered his servants to conduct Robinson to his house,
where he was friendly entertained,
and soon perceived that the friars had thus plotted against him;
for he went not into the mosque of his own accord; being led into it;
but heaven preserved him.
After having been four or five days in the house of the ancient Turk,
there came a guard of horsemen, hired by the friars, to carry him to Gaza;
for they had pre-informed the bashaw of that place against him;
but Robinson being come there, things took another turn than they expected;
for the bashaw being by some Turks made acquainted
with the mischievous design of the friars,
made them not only pay a considerable fine,
but also commanded them to convey Robinson safely to Jerusalem.
While he, was at Gaza, he was visited by many Turks, Greeks, and Armenians;
the latter of which having heard he was a Christian,
and that he chose rather to die than to turn from his religion, became very loving,
as were the Turks, the Jews also showed themselves moderate towards him.
Then according to the aforementioned order of the bashaw, he was carried to Jerusalem,
and there, by the appointment of the friars, brought into their convent,
where at first they seemingly showed love unto him, and one confessed,
there was now an evident sign, that he was a good Christian,
for he was come through persecution and sufferings;
and those things which had been spoken in his prejudice, were manifest to be untrue.
Robinson told the friar,
it was he and his brethren that had been the cause of his sufferings,
and withstood his coming to Jerusalem.
To which the other returned, that the English friar had misinformed them by his writing,
which had caused them to do what they had done;
and that therefore they desired he would now pass by those things,
seeing he was come through in such a miraculous manner; for,
(continued the friar,) it was the Lord`'s work, thus to carry him through,
and he might praise God he was preserved.

The next morning a friar came to him, and asked if he would become an obedient child,
and go to visit the holy places, according to their custom; he answered,
'`No.`' Then the friar said, '`Whereas others give great sums of money to see them,
you shall see them for nothing.`'
But Robinson replied '`I shall not visit them in your manner,
for in so doing I should sin against God.`'
This did not please the friar,
yet he said they would honor him as much as ever
they honored any Englishman that came there,
if he would conform unto them.
But Robinson continued immoveable, and said he should not conform;
and as for their honor, he did not matter it.
Then the friar became angry,
and said they would make him an example to all Englishmen that came there.
To which Robinson returned, '`I choose your dishonor rather than your honor.`'
The friar seeing he could not prevail, went away in anger,
and within a short time came again; and other friars being present,
one asked him if he would visit their church, and the holy sepulchre, and Bethlehem,
with the rest of the holy places, as other pilgrims did?
But he told them, at present he had no business to visit them;
and in their manner he should not visit them at all, that is, to worship them.
Then one said to him, '`How can you be a servant of God,
and will not go to visit the places where the holy men of God dwelt?
To which he returned, that they under pretence of doing service to God,
in visiting the places where the holy men dwelt, did oppose that way,
and resist that life, which the holy men of God lived and walked in.
Then one of the friars said, '`What do you preach unto us for?
To which he replied,
that he would have them turn from those evil practices they lived in,
else the wrath of the Almighty would be kindled against them.
But they did not at all like such discourse, and therefore said,
if he would not go and visit the aforesaid places, yet he must give twenty-five dollars,
as was the manner of those that visited them; for, said they, the Turks must be paid,
whether he would visit them, or not; but if he would visit them,
then they would pay it for him.
To this he signified, that he could not submit to such unreasonable terms.

Then they brought him before a Turk in authority in that place,
who asked him several questions, to which he soberly gave answers; and they discoursing,
about the worship of the Christians, the Turk asked also,
what was the ground of his coming to Jerusalem.
To which he answered,
that it was by the command of the Lord God of heaven and earth he came there;
and that the great and tender love of God was made manifest in visiting them;
his compassionate mercies being such,
that he would gather them in this the day of his gathering.
This was the message which Robinson believed he had from the Lord to declare unto them,
whether they would hear, or forbear.
And afterwards he wrote, that having thus cleared his conscience,
he found great peace with the Lord, and therefore he magnified his glorious name,
who had gone along with him, and preserved him in many trials.
For the friars, who intended him mischief,
were commanded by the Turks to carry him again safe and free of charges, to Ramla.
Here I leave him, because I do not find how he came home;
but that he returned there in safety,
appears to me from the relation he afterwards published of his travels.
