== Chapter X.

=== 1660.

[.chapter-synopsis]
* A warning to Parliament
* General Monk
* G. Fox and the Cornwall wreckers
* Restoration of Charles II.
* G. Fox the Younger imprisoned by order of Parliament
* Exhortations to Charles II.
* Queries to the Quakers by the Royalists
* Answers by E. Burrough
* Imprisonment of G. Fox at Lancaster
* Margaret Fell and the king
* Release of G+++.+++ Fox
* Interview between R. Hubberthorn and the King
* Friends at Leghorn, Venice and Rome
* A message to the Turkish Sultan
* Quakers heard before the House of Lords
* Fifth monarchy men
* Laws against Papists executed upon Quakers
* Oath of allegiance
* A consolatory epistle

About the beginning of this year,
E+++.+++ Burrough wrote the following letter to the parliament,
which then had the power again in their hands.

[.embedded-content-document.letter]
--

[.salutation]
Friends,

All these over-turnings, and almost wonderful changings,
were effected through the justice of the Lord`'s hand.
You are now again at the stern of government, and on the throne;
and I dare not but say it is of and by the Lord,
and that he has done it contrary to the expectations of many; and what his end is in it,
remains with him.
But I am sure one cause is,
that you may execute part of his wrath upon that treacherous
generation of hypocritical and deceitful men,
some of the army I mean.
I need not say to you, how that many of them were raised up from a low estate; and,
instead of serving the nation, became their lords and oppressors;
they have abused the Lord`'s mercy to them, and exalted themselves,
and became as great oppressors, and as grievous to the nation,
as ever they were that went before them;
and some of them took the very tithes and estates of their enemies,
and followed their evil spirit also, though the Lord was long-suffering to them,
and gave them a day, and put opportunity into their hands,
wherein they might have done good; but they also neglected to serve God and the nation,
to themselves; and because of the ambition and pride of some of them,
the Lord permitted them to make this last interruption upon you,
which was great treachery in man`'s account,
that thereby their measure might be filled up,
and that he might give you occasion against them,
and allow you to be filled with indignation towards them, to break them to pieces:
and what you do to some of them, in casting them out, and afflicting them,
you are but God`'s executioners therein; you are the executioners of his anger,
in what you do to them; and who shall prevent you, or forbid him to go on?
For they have long enough dissembled with this nation, in professing more than others,
and doing less, and their downfall is now.
And God has looked upon you, to be hard-hearted and cruel enough,
and very fit executioners of vengeance upon such men, as I have mentioned.

But now concerning you, and your present state, as you are in present place and power,
I have something to say to you; though they are fallen, and you yet stand,
and you have a little time after them; but this I say, do not glory over their fall,
neither glory as though you should stand forever;
for they were not greater sinners than you are,
neither are you one whit more righteous than some of them; but you are as sure to fall,
as they are fallen,
with no less measure of dishonor and affliction than is come upon them;
and you are in your last hour; and I dare not say, that God expects much more from you,
than for the end aforesaid, that is,
to be the executioners of justice upon men as sinful as yourselves;
so do not glory over them that are fallen: but know that your time also is but short,
and our fall may prove to your destruction, and theirs may prove to make them better,
and refine them: and if God has chosen you to execute some part of his wrath upon them,
for their wickedness, he will doubtless find instruments to execute his wrath upon you,
else he will do it with his own hands; for he purposes not to spare you;
for your sins cry as loud as any other people`'s,
and the oppressions are as great under you, as under them whom you condemn.
And I desire, if there be any good men among you, that such who are wise may consider,
and mind the hand of the Lord in and through all these things that are come to pass;
for God is working as well as you, he is seeking to set up a kingdom as well as you,
and his government and yours cannot stand together;
and he will make you know that he is stronger, and his government of more force,
and your kingdom cannot stand in place with his.

Therefore, Oh that you would take heed!
Oh that you would be wise,
if so be some of you may be spared! and be not too zealous in your way,
nor too furious in your proceedings;
do but to others as you intend to receive from others, and from the Lord;
and go not beyond your commission; for a permission at least you have had from God,
even to scourge hypocrites, and to be a judgment upon that hypocritical,
seeming religious generation of men aforesaid,
which have many a time as it were mocked God, and pretended love to him with their lips,
when their hearts have yearned after self-honor, and treasures of this world: I say,
your present hour and permission is for this end,
but not to persecute the people of the Lord, nor to destroy God`'s heritage;
but if you shall extend your power unto such a work,
and if you do persecute the innocent without cause,
and make war against the Lamb and his followers, and make laws,
and execute them to the oppression of the saints of the Most High,
then you go beyond your commission; for God has not called you unto this,
but to be instruments in another cause.
And the children of Zion, they trust in the living God,
and fear not the terror of mighty men,
neither can they be afraid at the roaring of the sea,
nor at the present threatening of the heathen, for God is with them.
And I say unto you,
the servant of the Lord has pondered and considered all these proceedings,
and viewed the present state of things at this day,
and there is no vision from God unto you of peace and comfort,
nor of a happy and lasting government, as you stand:
if any prophet shall divine this unto you, he speaks what he has not from the Lord,
but the vision of his own heart, and he deceives you and himself;
for you are not established upon a right foundation,
neither are you acted by a right spirit, which can truly govern for God;
but the spirit of wrath and fury is put into you, for the work to which you are called.
And I know not how to warn you, that you do not persecute the people of God.
For why?
It may be you must fill up your measure of wickedness thereby,
that God may break you perpetually; yet the less will be your judgment, if you do it not:
but and if you do it, the Lord will take occasion against you, to wound you,
and you shall never be healed, and as you do afflict others,
so and much more shall it be done unto you from the Lord.

Wherefore, consider what I have said; for this is the vision of the Almighty unto you,
that shall not go unfulfilled: and what you do, you must do it quickly;
for your time is short, and your power will God subdue;
and his kingdom and power will he speedily exalt over your heads,
and make you and the nations know that he is God, and that all power is with him,
and that he can do whatsoever he will; and it is his right alone to reign,
and his children`'s portion to possess the kingdom with him.
Let the whole earth, and all the powers thereof, bow and tremble before him:
let not your hearts be stout and rebellious against him, for he can grind you to powder,
and sink you into confusion and misery, as a stone into the sea.

[.signed-section-signature]
E+++.+++ Burrough.

--

This was directed for the hands of the speaker in parliament,
and accordingly was given to William Lenthal,
being enclosed to him with these lines following

[.embedded-content-document.letter]
--

[.salutation]
Friend,

The enclosed I do commend unto you to present unto the house,
and to endeavor sincerely the reading of it in your assembly;
for it is of special concernment to you all; and in the name of the Lord,
and by his Spirit, I do charge you not to be negligent in this matter,
as though it were not of worth to you; and I do lay it upon you,
as you will answer the contrary at the dreadful day of God,
when the King of Righteousness shall judge you and all mankind.

[.signed-section-signature]
E+++.+++ Burrough.

[.signed-section-context-close]
The 24th of the Eleventh month, 1659.

--

This parliament did so lord it,
that about fifteen hundred military officers were cashiered,
and others put into their places.

About this time George Fox the younger wrote also
a letter to the parliament and the army,
which was as follows:

[.embedded-content-document.letter]
--

Your day into darkness is turned; the sun is gong down over you.
You have had a large day, and power given unto you, to have done the will of God,
but you have abused the power, and slighted your day;
and you have refused to do the Lord`'s work, and have sought to serve yourselves,
and not the Lord; therefore in justice and righteousness,
is the day wherein you might have wrought for God, taken from you;
and the thick dark night of confusion is come upon you,
wherein you are groping and stumbling, and cannot work; the decree is gone out,
and sealed against you, and it cannot be recalled; you are not the men,
(as you stand,) in whom God will appear to work deliverance for his people,
and creatures; and yet deliverance shall come, but not according to man`'s expectations.
But as for you, you have rejected the counsel of the Lord, and grieved his Spirit,
and he has long borne you; yes, you are departed from the Lord,
and his presence is departed from you; indeed he has hewed with you,
and if you had been faithful to the end, he would have honored and prospered you,
and would have been your sufficient reward: you were his axe,
but you have boasted yourselves against him; therefore as you have beaten, and hewed,
and broken others, even so must you be beaten, hewed, and broken;
for you have grievously provoked the Lord; and if he should now allow that tree,
which you have cut, to fall upon you, and to break part of you, it were just.

O you treacherous, willful, proud, self-seeking people,
who have despised the counsel of the Lord, and would not take warning,
though he has sent his prophets and servants early and late among you,
some of whom you have imprisoned and despitefully used; what will you do now?
Whom will you now flee unto for help; seeing you are departed from the Lord,
and are now rending and tearing, biting and devouring one another, for proud, ambitious,
self ends?
(Mark.) If you would now build again the thing that you once destroyed,
that shall not be able to hide or shelter you from the wrath of the Lamb;
that way whereby you think to strengthen yourselves,
thereby shall you make yourselves much weaker, and help forward your own destruction;
you are now but a rod, remember your end, which hastens greatly.
Now breach upon breach, insurrection upon insurrection, overturning upon overturning,
heaps upon heaps, division upon division shall there be, until he come to reign,
whose right it is; and all nations must bow before him,
else he will break them with his iron rod.

They that trust in, or lean upon you for help,
it is as if they leaned upon a broken reed, which is not able to help itself, nor others;
indeed you have been made to do many good things,
but you would not go through with the work which God will have accomplished,
and therefore are these things come upon you;
therefore tremble and dread before the Lord, you who have been as strong oaks,
and tall cedars, for now shall your strength fail you, and you shall be weak,
even as the weakest of men; but if you would yet believe in the light,
and truly submit to God`'s righteous judgments,
many of you might come to witness your souls saved, in the day of the Lord;
though many of your bodies are to be thrown by, because of your grievous backslidings,
as not counted worthy to be the Lord`'s workmen.

There is a small remnant yet among you, for whom my soul breathes,
who may be winnowed out; and if they will acknowledge the judgments of the Lord,
and truly and thoroughly deny themselves, and follow his leadings,
he will heal their backslidings, and purge them,
that so they may be instruments in his hand:
but they that will continue with you in your sins,
shall partake with you of your judgments.

The rod of the wicked shall not always rest upon the back of the righteous;
yet even as gold is tried, so shall they be, that they may be white,
and without spot before the Lamb; but God will avenge their cause,
and woe then will be to their oppressors;
and then shall the majesty and the glory of the Lord fill his people,
who have long been trodden under, and they shall be the dread of all nations;
the zeal of the Lord of Hosts shall perform this.

[.signed-section-signature]
George Fox, the younger.

[.signed-section-context-close]
11th Month, (59.)

--

This letter being printed, a copy of it was given to each parliament man,
before Monk with his army came into London;
and how soon the predictions contained therein, as well as those of E. Burrough,
in the foregoing year, came to be fulfilled,
when many of the great ones were hanged and quartered, we shall see in the sequel.

General Monk came now, with part of the army he commanded, out of Scotland; into England,
and made great alterations among the officers,
putting in such as were believed to be no enemies to Charles Stuart;
for whatsoever Monk said of his resolution to be true and faithful to the parliament,
and to promote the interest of a commonwealth;
yet it appeared before long that he aimed at something else;
which he could do the easier, because he lacked not adherents in the parliament;
though he did not hesitate to say to Edmund Ludlow, '`We must live and die for, and with,
a commonwealth:`' and to others he declared,
that he would oppose to the utmost the setting up of Charles Stuart.
In the meanwhile he so ordered it, that many members of the parliament,
that had been long excluded as unqualified, took session again in that assembly;
and these brought it about, that sir George Booth, who was confined to the Tower,
for having carried on a design for Charles Stuart, was set at liberty.
Neither was the city of London in a condition to oppose Monk;
for he caused the port-cullies, and doors of the city gates,
and the posts to be pulled down; and the royalists were now become so bold,
that they printed a list of the names of the judges
that condemned king Charles the First to death;
and some of them were secured, while others fled away.
General Lambert was also sent to the Tower, and Monk, whose authority now increased,
sent for the lords, who until the year 1648, had sat in parliament,
and bade them return to the house where they formerly used to sit.

In these over-turnings G. Fox came to London in the
time when they were breaking the city gates.
He then wrote a paper to those that were now sinking, and told them,
that now the prophecies were fulfilling upon them, which had been spoken to them;
and that they who used to call the Quakers fanatics, and giddy-heads,
now seemed themselves giddy, and fugitives or wanderers.

From London G. Fox went to Sussex, and from there to Dorsetshire.
At Dorchester he had a great meeting in the evening at the inn where he lodged,
and there came many soldiers, who were pretty civil.
But the constables and officers of the town came also,
under pretence to look for a Jesuit, whose head, they said, was shaved.
So they took off G. Fox`'s hat, but not finding any bald place on his head,
they went away with shame.
This was of good service among the soldiers and others, and it affected the people,
who were turned to the Lord Jesus Christ.

Then he passed into Somersetshire, where his friends meetings were often disturbed.
One time there came a wicked man, who having a bear`'s skin on his back,
played ugly pranks in the meeting;
and setting himself opposite to the person that was preaching,
lolled his tongue out of his mouth, and so made sport for his wicked followers,
and caused great disturbance in the meeting.
But as he went back from there, an eminent judgment overtook him;
for there being a bull-baiting in the way, he stayed to see; and coming within his reach,
the bull pushed his horn under the man`'s chin, into his throat,
and forced his tongue out of his mouth,
so that it hung out in the same manner as before
he lolled it out in derision in the meeting:
and the bull running his horn into the man`'s head,
swung him about in a most fearful manner.

G+++.+++ Fox traveling through Somersetshire, came into Devonshire, and so went into Cornwall,
till he came to the Land`'s End.
While he was in Cornwall, there were great shipwrecks about the Land`'s End.
Now it was the custom of that country,
that at such times both rich and poor went out to get as much of the wreck as they could,
not caring to save the people`'s lives; and this custom so prevailed,
that in some parts of the country they called shipwrecks, God`'s grace.
This grieved G. Fox not a little,
considering how far these professed Christians were below the heathen at Melita,
who courteously received Paul, and the others that had suffered shipwreck with him,
and made him a fire.
On this consideration, he was moved to write a paper to the magistrates, priests,
and others, both high and low; in which he showed them the wickedness of their deeds,
and reproved them for such greedy actions,
telling them how they were ready to fight with one another for the spoil,
and spend what they got in taverns or alehouses, letting those that escaped drowning,
go a begging up and down the country.
Therefore he seriously exhorted them, to do unto others,
what they would have done to themselves.

This paper he sent to all the parishes thereabouts:
and after having had many meetings in Cornwall,
and several eminent people being convinced of the Truth preached by him,
he went to Bristol,
where the meetings of his friends were exceedingly disturbed by the soldiers.
Having heard this, he desired George Bishop, Thomas Gouldney, Thomas Speed,
and Edward Pyot, to go to the mayor and aldermen,
and desire them to let his friends have the town-hall to meet in,
provided it should not be on such days when the mayor
and aldermen had business to do in it;
and that for this use they would give twenty pounds a year,
to be distributed among the poor.
These four persons were astonished at this proposal, and said,
the mayor and aldermen would think them mad;
for the mayor and the commander of the soldiers had combined
together to make a disturbance in their meetings.
But G. Fox so encouraged them, that at last they consented to what he desired.
Being come to the mayor, he was moderate beyond expectation;
and when they had laid the thing before him, he said, for his part,
he could consent to it; but he was but one.
So they left him in a loving frame of mind; and coming back,
G+++.+++ Fox desired them to go also to the colonel that commanded the soldiers,
and to acquaint him of their rude carriage, and how they disturbed the meetings.
But the aforesaid four persons were backward to go to him.
Next morning being the First day of the week, a meeting was kept in an orchard,
where many people came; and after G. Fox had been preaching a pretty while,
there came several rude soldiers, some with drawn swords, and some drunk,
and among these one that had bound himself with an oath to cut down,
and kill the man that spoke.
But when he came pressing in through the crowd, and was within two yards of G. Fox,
he stopped at those four persons before mentioned, and fell a jangling with them;
but at length his sword was put up again.
The next day they went and spoke with the colonel,
and he having heard how mischievous his soldiers had been, sent for them,
and cut and slashed some of them.
When this was told G. Fox, he blamed those his friends,
thinking they might have prevented the cutting of the soldiers,
if they had gone to the colonel when he would have had them.
Yet this had such effect,
that the meeting there was kept without disturbance a good while after.

G+++.+++ Fox then also had a general meeting at Edward Pyot`'s, near Bristol,
at which were several thousands of people; and so many of Bristol, that some said,
the city looked naked; and all was quiet.

But in other places, about this time, things were not so quiet; for the soldiers,
under general Monk`'s command, were often very rude in disturbing of meetings.
But when complaint was made to him, who was then at Westminister,
he showed that he would not countenance such wickedness,
and did in that respect better than several other generals had done,
for he gave forth the following order.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
St. James`'s, March 9, 1659-60.

I do require all officers and soldiers,
to forbear to disturb the peaceable meetings of the Quakers,
they doing nothing prejudicial to the parliament or commonwealth of England.

[.signed-section-signature]
George Monk.

--

Monk having thus long declared for a commonwealth, and against a king,
began now to take off the mask;
for the old lords had now taken their places again in the House of Peers,
out of which they had been kept so many years; and by the advice of Monk, Charles Stuart,
(who for several years had lived at Cologne, and, having made a voyage to Spain,
was from there come, by France, to Brussels,) repaired to Breda:
and in England it being resolved upon to call him back, and to restore him,
he gave forth the following declaration at Breda;
thereby to persuade those that were yet backward to acknowledge him.

[.embedded-content-document.legal]
--

Charles, by the grace of God, king of England, Scotland, France, and Ireland,
defender of the faith, etc.
To all our loving subjects, of what degree or quality soever, greeting.
If the general distraction and confusion which is spread over the whole kingdom,
does not awaken all men to a desire and longing that those
wounds which have for so many years together been kept bleeding,
may be bound up, all we can say will be to no purpose.
However, after this long silence, we have thought it our duty to declare,
how much we desire to contribute thereunto; and that as we can never give over the hope,
in good time to obtain the possession of that right
which God and nature has made our due;
so we do make it our daily suit to the Divine Providence, that he will,
in compassion to us and our subjects, after so long misery and sufferings, remit,
and put us into a quiet and peaceable possession of that our right,
with as little blood and damage to our people as is possible.
Nor do we desire more to enjoy what is ours,
than that all our subjects may enjoy what by law is theirs,
by a full and entire administration of justice throughout the land,
and by extending our mercy where it is needed and desired.

And to the end that the fear of punishment may not engage any,
conscious to themselves of what is past, to a perseverance in guilt for the future;
by opposing the quiet and happiness of their country, in the restoration both of king,
peers, and people, to their just, ancient, and fundamental rights;
we do by these presents declare, that we do grant a free and general pardon,
which we are ready upon demand to pass under our great seal of England,
to all our subjects, of what degree or quality soever, who,
within forty days after the publishing hereof,
shall lay hold upon this our grace and favor;
and shall by any public act declare their doing so,
and that they return to the loyal y and obedience of good subjects;
excepting only such persons as shall hereafter be excepted by parliament.
Those only excepted, let all our subjects, how faulty soever,
rely upon the word of a king, solemnly given by this present declaration,
that no crime whatsoever, committed against us, or our royal father,
before the publication of this, shall ever rise in judgment,
or be brought in question against any of them, to the least endamagement of them,
either in their lives, liberties, or estates; or as far forth as lies in our power,
so much as to the prejudice of their reputations, by any reproach,
or term of distinction, from the rest of our best subjects; we desiring, and ordaining,
that henceforward all notes of discord, separation, and difference of parties,
be utterly abolished among all our subjects,
whom we invite and conjure to a perfect union among themselves, under our protection,
for the resettlement of our just rights, and theirs, in a free parliament, by which,
upon the word of a king, we will be advised.

And because the passion and uncharitableness of the
times have produced several opinions in religion;
by which men are engaged in parties and animosities against each other, which,
when they shall hereafter unite, in a freedom of conversation, will be composed,
or better understood; we do declare a liberty to tender consciences,
and that no man shall be disquieted, or called in question,
for differences of opinion in matter of religion,
which do not disturb the peace of the kingdom;
and that we shall be ready to consent to such an act of parliament, as,
upon mature deliberation,
shall be offered to us for the full granting of that indulgence.

And because, in the continual distractions of so many years,
and so many and great revolutions, many grants and purchases of estates,
have been made to, and by, many officers, soldiers, and others,
who are now possessed of the same,
and who may be liable to actions at law upon several titles,
we are likewise willing that all such differences,
and all things relating to such grants, sales, and purchases,
shall be determined in parliament;
which can best provide for the just satisfaction of all men who are concerned.

And we do further declare, that we will be ready to consent to any act,
or acts of parliament, to the purposes aforesaid,
and for the full satisfaction of all arrears due to the officers,
and soldiers of the army, tinder the command of general Monk;
and that they shall be received into our service,
upon as good pay and conditions as they now enjoy.

[.signed-section-signature]
Charles R.

[.signed-section-context-close]
Given under our sign manual and privy signet at our court at Breda,
this 14th day of April, 1660, in the Twelfth year of our reign.

--

The original of this declaration was sent to the House of Lords,
and a duplicate in a letter to the House of Commons;
and repeated and sent in a letter to General Monk, the council of state,
and the officers of the army.
Hereupon it was resolved by the parliament, to prepare an answer;
and both in the House of Lords, and in the House of Commons,
it was voted to proclaim king Charles at Whitehall, and in London,
as lawful sovereign of his kingdoms, which was done on the 8th of the month called May.

Now the king, who by the Spaniards was invited to return to Brussels,
and by the French to come to Calais, chose,
at the pressing invitation of the States-general of the United Provinces,
to go by Holland: and so he went, with the yachts of the States, to Rotterdam,
and from there with coaches to the Hague; where having stayed some days,
he took shipping at Schevenningen for England,
and made his entry at London on the anniversary of his birth-day.
Thus we see Charles the Second, (who not long after was crowned,) restored,
not by the sword, but by the marvelous hand of the Lord.

About this time G. Fox the younger came to Harwich, where he was hauled out of a meeting,
and imprisoned under a pretense of having caused a tumult.
But to give to the reader a true sight of the matter, I must go back a little.

About four years before this time, some of the people called Quakers,
being come into the said town,
one of them spoke a few words by way of exhortation
to the people that came from the steeple-house;
and passing on, he and those with him went to an inn.
The mayor hearing thereof, sent to them, commanding that they should depart the town,
which they did after a short space; but about night they returned,
and lodged at their inn, and the next day passed away peaceably.
Not long after, the woman that kept the inn,
was commanded to come before the magistrates; who threatened to take away her license,
unless she promised to lodge no more such persons.
But how eager soever they were for keeping out the Quakers, yet it proved ineffectual;
for it seems some of those that had been spoken to in the streets, were so reached,
that they came to be obedient to the inward teachings
of the Lord they had been recommended to.
And so a way was made for meetings there,
whereby the number of those of that society began to increase.
And because they could no longer comply with superstitious burials,
they bought a piece of ground to bury their dead in,
but met with great opposition at their burials; and once,
when several came along to bury a corpse, it was by force taken from them,
and set by the sea side, where having lain above ground part of two days and one night,
it was privately covered by some with small stones.

In the month called May, G. Fox the younger came to Harwich, to preach the Truth there.
The mayor of the town, whose name was Miles Hubbard, having heard of this,
stopped several that were going to the meeting.
The rude multitude seeing it, grew insolent,
and made a hideous noise before the house where the meeting was kept,
and some were for pulling it down.
G+++.+++ Fox hearing the noise, while he was preaching, grew very zealous,
and with a mighty power was made to say, '`Woe,
woe unto the rulers and teachers of this nation, who suffer such ungodliness as this,
and do not seek to suppress it.`'
Some that heard him thus speaking, went and told the magistrates of it,
perhaps not in the self-same words as were uttered by him.
The officers then coming,
the mayor commanded the constables to take the said G. Fox into custody;
who hearing this, said, '`If I have done any thing worthy of death, or bonds,
I shall not refuse either; but I desire you to show me what law I have transgressed;
which you ought to do, before you sends me to prison,
that I may know for what I am sent there.`'
But the mayor told him, he should know that afterward; and so he was carried to prison.
Robert Grassingham, who was shipwright of the admiralty in that port,
being at the meeting, out of which G. Fox was hauled,
in love went freely along with him to prison.
This seemed to please the mayor,
who some days before had been heard to say concerning Grassingham,
'`If I could but gel him out of the town,
I should know what course to fake with the other Quakers.`'
Some time after G. Fox was imprisoned, a court order was sent to the jailer,
in which the prisoner was charged with causing a tumult in that borough,
and disturbing the peace thereof.
This court order was signed by Miles Hubbard, mayor, Anthony Woolward, and Daniel Smith;
and these magistrates sent notice of what they had done, to the parliament,
under a specious pretense, that so they might not fall into disgrace.
The parliament receiving this information, issued forth the following order:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Monday, May 21,1660.

The house being informed, that two Quakers, that is to say,
George Fox and Robert Grassingham, have lately made a disturbance at Harwich,
and that the said George Fox, who pretends to be a preacher,
did lately in his preaching there,
speak words much reflecting on the government and ministry,
to the near causing of a mutiny,
and is now committed by the mayor and the magistrates there;

Ordered that the said George Fox and Robert Grassingham be forthwith brought up in custody;
and that the sheriff of the county of Essex do receive them,
and give them his assistance for the conveying them up accordingly,
and delivering them into the charge of the sergeant at-arms attending this house.

Ordered, that the thanks of this house be given to the mayor and magistrates of Harwich,
for their care in this business.

[.signed-section-signature]
William Jessop, Clerk of the Common House of Parliament.

--

By this it appeared that the magistrates of Harwich had special friends in the parliament.
R+++.+++ Grassingham being at liberty, was gone to London; and when this order came to Harwich,
G+++.+++ Fox was delivered to the sheriff of Essex and his men: these went with him to London,
and upon the road they met Grassingham, who was coming from London to Harwich,
in pursuance of an order which he had received from
the commissioner of the admiralty and navy,
for refitting one of the king`'s frigates.
But notwithstanding Grassingham showed his order to the sheriff,
yet he brought him back to London with Fox,
and delivered them into the custody of the sergeant at arms attending the house,
who committed them to Lambeth house.
They having been there about three weeks,
wrote a letter to the House of Commons wherein they gave some account
of the manner of their imprisonment and desired that they with
their accusers might be brought face to face before the parliament,
saying, that if any thing could be proved against them, worthy of punishment,
they should not refuse it.
But they thought it to be unjust and unreasonable,
that a man should be hauled out of a peaceable meeting, and sent to prison,
without being examined,
only for declaring against the cursing and the wickedness of the rude people,
and against such as allowed such ungodliness, and did not seek to suppress it.

This was the chief contents of their paper,
which they enclosed in a letter to the speaker of the House of Commons in these words:

[.embedded-content-document.letter]
--

[.letter-heading]
For the Speaker of the House of Commons.

[.salutation]
Friends,

We desire you to communicate this enclosed to the House of Commons,
it being a few innocent, just,
and reasonable words to them though not in the eloquent language of man`'s wisdom,
yet it is in the truth which is honorable.
We are friends to righteousness and truth, and to all that are found therein.

[.signed-section-signature]
Robert Grassingham, George Fox

--

But the speaker did not deliver the paper,
under pretense that it was not directed with the ordinary title,
'`To the Right honorable the House of Commons.`'
Therefore by the help of their friends they got it printed,
that so each member of parliament might have a copy of it.
Now after they had lain about fourteen weeks in Lambeth gate-house without being examined,
one of the members of parliament moved this business in the house;
whereupon the following order was made:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Thursday, October 30th, 1660.

Ordered that George Fox and Robert Grassingham,
who by virtue of a former order of this house,
were taken into custody by the sergeant at arms attending this house,
for some disturbance at Harwich, be forthwith released, and set at liberty,
upon bail first given to render themselves, when they shall be in that behalf required.

[.signed-section-signature]
William Jessop, Clerk of the House of Commons

--

Shortly after this order was issued forth,
the sergeant at arms sent his clerk to demand fees and chamber rent of the prisoners,
asking fifty-pounds for fees, and ten shillings a week for chamber rent.
But since no evil was laid to their charge,
they could not resolve to satisfy this unreasonable demand,
yet offered to pay two shillings and six pence a week,
though the chamber where they had lain, was the highest room in a lofty tower,
and all the windows open, until they had gotten them glazed,
without any charge to the sergeant.
Matters standing thus, their cause was referred to the king`'s privy council.
But it lasted yet a good while before they were released;
for several evasions were made use of to keep them in custody.

While G. Fox was prisoner, he wrote a little book, which he called,
[.book-title]#A Noble Salutation to King Charles Stuart#, wherein
he showed him how matters had gone in England,
viz. That his father`'s party scorned those that appeared
in arms against them because of their meanness;
for they were tradesman, plowmen, servants, and the like;
which contemptible instruments God made use of to bring down the loftiness of the others.
But those of the parliament party growing from time to time successful, and prevailing,
got into the possessions of those they conquered,
and fell into the same pride and oppression which they had cried out against in others;
and many of them became greater oppressors, and persecutors than the former had been.
Moreover,
the author exhorted the king to observe the hand of the Lord in restoring of him.
Therefore,`' said he, '`Let no man deceive you,
by persuading you that these things are thus brought to pass,
because the kingdom was your own proper right,
and because it was withheld from you contrary to all right;
or because that those called royalists are much more
righteous than those who are now fallen under you.
For I plainly declare unto you, that this kingdom, and all the kingdoms of the earth,
are properly the Lord`'s. And this know, that it was the just hand of God,
in taking away the kingdom from your father and you: and giving it unto others;
and that also it is the just hand of the Lord to take it again from them,
and bring them under you: though I shall not say,
but that some of them went beyond their commission against your father,
when they were brought as a rod over you; and well will it be for you,
if you become not guilty of the same transgressions.

The author further exhorts the king to consider, this his station was not without danger,
because of the changeableness of the people, a great part of which were perfidious;
since one while they had sworn for a king and parliament;
and shortly after they swore against a king, single person, or house of Lords;
and afterwards again they swore for a single person.
Some time after they cried up a parliament again.
And when O. Cromwell had turned out the parliament, and set up himself,
then the priests prayed for him, and asserted his authority to be just; and when he died,
they fawned upon his son Richard,
and blasphemously termed his father the light of their eyes,
and the breath of their nostrils; and they told him,
that God had left him to carry on that glorious work which his father had begun.
No, some priests compared Oliver to Moses, and Richard to Joshua,
who should carry them into the promised land.
Thus they continually would flatter those that were at the helm.
For when George Booth made a rising, and they thought there would be a turn,
then some of the priests cried out against the parliament,
and cursed such as would not go out against them.
But when Booth was taken, then many began to petition the parliament,
and to excuse themselves, that they had no hand in that rising.

Next the author set forth the wickedness of the people by excessive drinking and drunkenness,
thereby as it were to show their loyalty to the king; and he relates also,
how having preached at Harwich, against the grievous wickedness of the people,
he was hauled to prison in the king`'s name.
Finally, he exhorts the king, to take heed of seeking revenge; and to show mercy.

This paper, which was not a small one, for it took up several sheets,
was delivered in writing by Richard Hubberthorn, into the king`'s hand at Whitehall,
and was not long after by the author published in print.

Now one of the most eminent royalists drew up several queries to the Quakers,
desiring them to answer them, and to direct their answer with this superscription,
_Tradite hanc amico Regis,_ that is, '`Deliver this to the king`'s friend.`'
For it was clearly seen, that several of their predictions came to be fulfilled,
of which those of Edward Burrough were not the least.
And therefore some,
(as it seems,) thought that by the Quakers they might get some knowledge
whether any stability of the king`'s government was to be expected.
By the queries it appeared, that the author of them was a man of understanding,
and of some moderation also; and though I do not know who he was,
yet I am not without thoughts that Edward, earl of Clarendon, and high chancellor,
may have been the penman thereof.
The tendency of these queries chiefly was to know from the Quakers,
what their judgment was concerning the king`'s right to the crown;
and whether they ever did foresee his return;
and also whether they could judge that his reign and government should be blessed or not.
Moreover, whether he might justly forgive, or avenge himself:
and whether he might allow liberty of conscience to all sorts of people, etc.
Edward Burrough answered these queries, and published his answer in print.
It was directed to the king and the royalists.
In it he showed, that in some of their writings it had been signified,
that they had some expectations of the king`'s restoration.
That the king`'s coming to the throne was reasonable and equitable,
because through the purpose of the Lord.
That his reign and government might be blessed, or not blessed, according to his carriage.
And that he might justly forgive his, and his father`'s enemies;
for though he and his father might have been injured,
yet for as much as they had applied to the sword
to determine their controversy with the nation,
the sword went against them; and by that whereby they thought to stand, they did fall;
and who then should they blame for that which befell them, seeing the sword,
which they themselves did choose, destroyed them.
However, the author signified, that this was not meant of the king`'s death;
that being quite another case.
And if such, who had destroyed kingly government in name and title,
and pretended to govern better, and did not make reformation, but became oppressors,
having broke their promises, came to be punished on that account with death or otherwise,
such could not be said to suffer for a good conscience, nor for righteousness sake;
but it was because they were oppressors;
and suffering for that cause could not be called persecution.

[quote]
____
But none of us, (thus ran Edward Burrough`'s words,) can suffer for that cause,
as not being guilty thereof.
If we suffer in your government, it is for the name of Christ;
because nothing can be charged against us in this capacity as we now stand,
and in this state into which we are now gathered and changed,
not in any matter of action or rebellion against the king nor his father;
nor in any thing but concerning the law and worship of our God,
and the matters of his kingdom, and our pure consciences.
And if any that are now among us were any way engaged
in the parliament service in the wars,
it was not in rebellion against the king or his father,
as that we sought their destruction as men; but upon sober and reasonable principles,
and not for corrupt ends, nor to get honor and riches to ourselves,
as some others might do, who went into the war for self ends, and continue! in action,
after the cause which was once engaged for was utterly lost.
And that principle, which some time led some into action to oppose oppression,
and seek after reformation, that principle is still justified,
though we are now better informed than once we were.
For though we do now more than ever oppose oppression, and seek after reformation,
yet we do it not in that way of outward warring and
fighting with carnal weapons and swords;
and you and the king ought to put a difference between
such as some time acted in the wars against you,
in and upon sober and reasonable principles,
and that did not make themselves rich and high in the world through your sufferings,
and between such as have acted against you for self ends, and have insulted over you,
and have made themselves great and rich in this world through your afflictions and sufferings.`'
____

To the query, whether the great afflictions sustained by the king several years,
from subjects of his own nation, and the guilt thereof,
did lie upon all the subjects in general; or whether upon any,
or some particular sorts of people, who were such more than others;
E+++.+++ Burrough made this answer,

[quote]
____
So far as his sufferings were unjust,
the guilt thereof does not lie upon all the subjects in general,
but upon some more than others; and such are easy to be distinguished from others,
if it be considered who they are that raised the war in this nation against the king,
and who first preached and prayed up the war,
and prosecuted it against the king`'s father,
and who cast out the bishops and prelates from their places,
and took their revenues and benefices, and are become men as corrupted,
as covetous and self-seeking, as proud and ambitious, as unjust persecutors,
as ever the men were which they cast out:
and who is it that has gotten great estates in the nation, and worldly honor,
and raised themselves from nothing by the wars, and by your sufferings;
and who got the estates and titles of their enemies,
and pretended to free them from all oppressions, but have not done it;
but have continued the old oppressions,
and have been striving among themselves who should rule, and who should be great?
And as for us, who are called Quakers,
we are clear from the guilt of all the king`'s sufferings.
We have not cast out others, and taken their places of great benefices,
neither have we made war with carnal weapons against any, ever since we were a people.
Neither have we broken oaths and engagements, nor promised freedom and deliverance,
and for self ends and earthly riches betrayed, as others have done,
what we have pretended to.
And in many particulars it does appear that we are clear from his sufferings,
for we have been a suffering people as well as they,
by the same spirit which caused them to suffer, which has been much more cruel, wicked,
and unjust towards us, than it has been towards them,
though our persecution has been in another manner.
But what they have done against us we can freely forgive them,
and would have you to follow the same example.
And if you could accuse them in many things, so could we:
but this is not a time to accuse one another, but to forgive one another,
and so to overcome your enemies.
When they had gotten the victory, they did not reform, but became oppressors,
as well as others, and became cruel towards others, that would not say and do as they:
and for this cause the Lord has brought them down,
and may justly suffer others to deal with them as they have dealt with others.
Yet notwithstanding I must still say and it is my judgment,
that there was very great oppression and vexation under the government of the late king,
and bishops under his power, which the Lord was offended with,
and many good people oppressed by;
for which cause the Lord might and did justly raise up some to oppose,
and strive against oppressions and injustice,
and to press after reformation in all things.
And that principle of sincerity,
which in some things carried them on in opposing oppressions and pressing after reformation,
I can never deny, but acknowledge it; though many soon lost it, and became self-seekers,
forgetting the cause pretended to, etc.
____

This is but a small part of the queries, and the answers thereunto,
which E. Burrough concluded with a bold exhortation to the king,
to fear and reverence the Lord.

[.small-break]
'''

Now we return again to G. Fox the elder, whom we left about Bristol;
from which he passed to Gloucester, Worcester, Drayton,
(the place of his nativity,) and Yorkshire.
In that country at that time a Yearly meeting was kept at Balby, in an orchard,
where some thousands of people were met`' together.
At York, about thirty miles off, notice being given of this meeting,
a troop of horse came from there:
and when G. Fox stood preaching in the meeting on a stool, two trumpeters came riding up,
sounding their trumpets pretty near him; and then the captain bid him come down,
for he was come, he said, to disperse the meeting.
G+++.+++ Fox then speaking, told him, he knew they were peaceable people;
but if he did question that they met in a hostile manner,
he might make search among them; and if he found either sword or pistol about any there,
such may suffer.
But the captain told G. Fox, he must see them dispersed,
for he came all night on purpose to disperse them.
G+++.+++ Fox asked him,
what honor it would be to him to ride with swords
and pistols among so many unarmed men and women?
But if he would be still and quiet,
the meeting probably might not continue above two or three hours; and when it was done,
as they came peaceably, so they should part: for he might perceive,
the meeting was so large, that all the country thereabouts could not entertain them,
but that they intended to depart towards their homes at night.
But the captain said, he could not stay so long.
G+++.+++ Fox desired then, that if he himself could not stay to see the meeting ended,
he would let a dozen of his soldiers stay.
To this the captain said, he would permit them an hour`'s time;
so he left six soldiers to stay there, and then went away with his troop: he being gone,
the soldiers that were left, told those that were met together,
they might stay till night, if they would.
This they were not for, but parted about three hours after, without any disturbance.
But if the soldiers had been of such a temper as their captain,
perhaps the meeting would not have ended thus quietly: for he was a desperate man,
having once told G. Fox in Scotland, that he would obey his superiors`' command;
and if it were to crucify Christ, he would do it;
or execute the great Turk`'s commands against the Christians, if he were under him.

Now G. Fox went to Skipton,
where there was a general meeting concerning the affairs of the church.
For many of his friends suffered much, and their goods being taken from them,
and some brought to poverty, there was a necessity to provide for them.
This meeting had stood several years;
for when the justices and captains came to break them up,
and saw the books and accounts of collections for relief of the poor,
and how care was taken that one county should help another, and provide for the poor,
they commended such practice, and passed away in love.
Sometimes there would come two hundred poor people, belonging to other societies,
and wait there till the meeting was done:
and then the Friends would send to the baker`'s for bread,
and give every one of these poor people a loaf, how many soever there were:
for they were taught to do good unto all, though especially to the household of faith.

From here G. Fox went to Lancaster, and so to Swarthmore,
where he was apprehended at the house of Margaret Fell, who was now a widow,
judge Thomas Fell, her husband, having been deceased about two years before.
Now some imagined they had done a remarkable act; for one said,
he did not think a thousand men could have taken G. Fox.
They led him away to Ulverstone, where he was kept all night at the constable`'s house,
and a guard of fifteen or sixteen men were set to watch him;
some of which sat in the chimney, for fear he should go up the funnel.
Next morning he was carried to Lancaster, but exceedingly abused by the way;
and being come to town, was brought to the house of a justice,
whose name was Henry Porter, and who had granted the warrant against him.
He asked Porter, for what, and by whose order, he had sent forth his warrant;
and he complained to him of the abuse of the constables and other officers:
for they had set him upon a horse behind the saddle, so that he had nothing to hold by;
and maliciously beating the horse, made him kick and gallop, and throw off his rider.`'
But Porter would not take any notice of that, and told G. Fox, he had an order;
but would not let him see it, for he would not reveal the king`'s secrets.
After many words were exchanged, he was carried to Lancaster prison.
Being there a close prisoner in the common jail, he desired two of his friends,
one of which was Thomas Green, the other Thomas Cummings, a minister of the gospel,
(with whom I was very familiarly acquainted,) to go to the jailer,
and desire of him a copy of his court order.
They went, but the jailer told them he could not give a copy of it;
yet he gave it them to read; and to the best of their remembrance,
the matters therein charged against him were,
that G. Fox was a person generally suspected to be
a common disturber of the peace of the nation,
an enemy to the king, and a chief upholder of the Quakers`' sect: and that he,
together with others of his fanatic opinion,
had of late endeavored to raise insurrections in these parts of the country,
and to embroil the whole kingdom in blood.
Wherefore the jailer w-as commanded to keep him in safe custody,
till he should be released by order from the king and parliament.
No wonder that the jailer would not give a copy of his court order,
for it contained almost as many untruths as words.
G+++.+++ Fox then wrote an apology, wherein he answered at large to all those false accusations.
And Margaret Fell, considering what injury was offered to her,
by hauling G. Fox out of her house, wrote the following information, and sent it abroad.

[.embedded-content-document.letter]
--

[.letter-heading]
To all magistrates, concerning the wrong taking up,
and imprisoning of George Fox at Lancaster.

I do inform the governors of this nation, that Henry Porter, mayor of Lancaster,
sent a warrant with four constables to my house, for which he had no authority nor order.
They searched my house, and apprehended George Fox in it,
who was not guilty of the breach of any law, or of any offense against any in the nation.
After they had taken him, and brought him before the said Henry Porter,
there was bail offered, what he would demand for his appearance,
to answer what could be laid to his charge: but he, (contrary to law,
if he had taken him lawfully,) denied to accept of any bail;
and clapped him up in close prison.
After he was in prison, a copy of his court order was demanded,
which ought not to be denied to any prisoner,
that so he may see what is laid to his charge: but it was denied him;
a copy he could not have; only they were permitted to read it over.
And everything that was there charged against him, was utterly false;
he was not guilty of any one charge in it, as will be proved,
and manifested to the nation.
So, let the governors consider of it.
I am concerned in this thing, inasmuch as he was apprehended in my house;
and if he be guilty, I am so too.
So I desire to have this searched out.

[.signed-section-signature]
Margaret Fell.

--

After this, Margaret determined to go to London,
to speak with the king about this matter: which Porter having heard of,
said he would go too; and so he did.
But because he had been a zealous man for the parliament against the king,
several of the courtiers put him in mind of his plundering of their houses.
And this so troubled him, that he quickly left the court, and returned home,
and then spoke to the jailer about contriving a way to release G. Fox.
But in his court order he had overshot himself, by ordering G. Fox to be kept prisoner,
till he should be delivered by the king or parliament.
G+++.+++ Fox also sent him a letter, and put him in mind,
how fierce he had been against the king, and his party,
though now he would be thought zealous for the king.
And among other passages he called to his remembrance, how,
when he held Lancaster Castle for the parliament against the king,
he was so rough and fierce against those that favored the king, that he said,
he would leave them neither dog nor cat,
if they did not bring him in provision to his castle.

One Anne Curtis coming to see G. Fox, and understanding how he stood committed,
resolved also to go to the king about it; for her father,
who had been sheriff of Bristol, was hanged near his own door,
for endeavoring to bring in the king: upon which consideration,
she was in hopes to be admitted to the king`'s presence to speak with him.
Coming to London, she and Margaret Fell went together to the king, who,
when he understood whose daughter Anne was, received her kindly.
She having acquainted the king with the case of G. Fox, desired,
that he would be pleased to send for him up, and hear the cause himself.
This the king promised her he would do,
and commanded his secretary to send down an order for the bringing up G. Fox.
But it was long before this order was executed, for many evasions were sought,
as well by carping at a word, as by other craft;
whereby the sending up of G. Fox was retarded above two months.
He thus continuing prisoner, wrote several papers, and among the rest also this:

[.embedded-content-document.paper]
--

[.letter-heading]
To the King.

[.salutation]
King Charles,

You earnest not into this nation by sword, nor by victory of war;
but by the power of the Lord; now if you do not live in it, you will not prosper.
And if the Lord has showed you mercy, and forgiven you,
and you do not show mercy and forgive, the Lord God will not hear your prayers,
nor them that pray for you: and if you do not stop persecution, and persecutors,
and take away all laws that do hold up persecution about religion;
but if you do persist in them, and uphold persecution,
that will make you as blind as them that have gone before you:
for persecution has always blinded those that have gone into it;
and such God by his power overthrows, and does his valiant acts upon;
and brings salvation to his oppressed ones: and if you do bear the sword in vain,
and let drunkenness, oaths, plays, may-games, with fiddlers, drums, trumpets,
to play at them, with such like abominations and vanities be encouraged,
or go unpunished; as setting up of maypoles, with the image of the crown atop of them,
etc. the nations will quickly turn like Sodom and Gomorrah,
and be as bad as the old world, who grieved the Lord till he overthrew them:
and so he will you, if these things be not suddenly prevented.
Hardly was there so much wickedness at liberty before now, as there is at this day;
as though there was no terror, nor sword of magistracy;
which does not grace a government, nor is a praise to them that do well.
Our prayers are for them that are in authority, that under them we may live a godly life,
in which we have peace; and that we may not be brought into ungodliness by them.
So hear, and consider, and do good in your time, while you have power; and be merciful,
and forgive, that is the way to overcome, and obtain the kingdom of Christ.

[.signed-section-signature]
G+++.+++ Fox

--

The sheriff of Lancaster still refused to remove G. Fox, unless he would become bound,
and pay for the sealing of the writing, and the charge of carrying him up.
But this he would not.
Then they consulting how to convey him,
it was at first proposed to send a party of horse with him.
But he told them, if he were such a man as they had represented him to be,
they had need to send a troop or two of horse to guard him.
But considering that this would be a great charge to them,
they concluded to send him up guarded only by the jailer, and some bailiffs.
On further consideration, they found that this also would be very chargeable,
and thereupon told him, if he would put in bail,
that he would be in London such a day of the term,
he should have leave to go up with some of his own friends.
G+++.+++ Fox told them, he would neither put in any bail, nor give any money:
but if they would let him go up with one or two of his friends, he would go up,
and be in London such a day, if the Lord did permit.
So at last, when they saw they could not make him bow,
the sheriff consented that he should go up with some of his friends,
without any other engagement than his word,
to appear before the judges at London such a day of the term, if the Lord did permit.
Whereupon they let him go out of prison, and after some stay,
he went with Richard Hubberthorn and Robert Withers, to London,
where he came on a day that some of the judges of king Charles the First,
were hanged and quartered at Charing Cross:
for now what E. Burrough and others had plainly foretold, was fulfilling on them.

The next morning G. Fox, and those with him, went to judge Thomas Mallet`'s chamber,
who then was putting on his red gown, to sit upon some more of the king`'s judges,
and therefore he told him he might come another time.
G+++.+++ Fox did so, being accompanied by Marsh Esq., one of the king`'s bed-chamber.
When he came to the judge`'s chamber, he found there also the lord chief justice Foster,
and delivered to them the charge that was against him: but when they read those words,
that he and his friends were embroiling the nation in blood,
etc. they struck their hands on the table: whereupon G. Fox told them,
that he was the man whom that charge was against;
but that he was as innocent of any such thing as a newborn child;
that he brought it up himself, and that some of his friends came up with him,
without any guard.
As yet the judges had not minded G. Fox`'s hat, but now seeing his hat on,
they said why did he stand with his hat on?
He told them, he did not stand in any contempt to them.
Then they commanded one to take it off;
and having called for the marshal of the King`'s Bench, they said to him,
'`you must take this man and secure him, but you must let him have a chamber,
and not put him among the prisoners.`'
But the marshal said his house was so full,
that he could not tell where to provide a room for him, but among the prisoners.
Judge Foster then said to G. Fox,
'`Will you appear tomorrow about ten of the clock at the King`'s Bench Bar,
in Westminster Hall?`'
'`Yes,`' said he, '`if the Lord give me strength.`'
Hereupon the said judge said to the other judge, '`If he say yes, and promises it,
you may take his word.`'

So he was dismissed for that time,
and the next day appeared at the King`'s Bench Bar at the hour appointed,
being accompanied by Richard Hubberthorn, Robert Withers, and esquire Marsh,
before-named.
And being brought into the middle of the court,
he looked about and turning to the people, said, '`Peace be among you.`'
Then the charge against him was read, and coming to that part which said,
that he and his friends were embroiling the nation in blood, and raising a new war,
and that he was an enemy to the king, etc. those of the bench lifted up their hands.
He then stretching out his arms, said, '`lam the man whom that charge is against;
but I am as innocent as a child concerning the charge,
and have never learned any war postures.
Do you think, that if I and my friends had been such men as the charge declares,
that I would have brought it up myself against myself?
Or that I should have been allowed to come up with only one or two of my friends with me?
For had I been such a man as this charge sets forth,
I had need to have been guarded up with a troop or two of horse:
but the sherif and magistrates of Lancashire had thought
fit to let me and my friends come up by ourselves,
almost two hundred miles, without any guard at all,
which we may be sure they would not have done,
if they had looked upon me to be such a man.`'
Then the judge asked him, whether it should be filed, or what he would do with it?
And he answered, '`You are judges, and able, I hope, to judge in this matter:
therefore do with it what you will.`'
The judges said, they did not accuse him, for they had nothing against him.
Whereupon esquire Marsh stood up and told the judges, it was the king`'s pleasure,
that G. Fox should be set at liberty, seeing no accuser came against him.
Then they asked him, whether he would put it to the king and council?
He answered, '`Yes, with a good will.`'
Thereupon they sent the sheriff`'s return, which he made to the order of _habeas corpus_,
to the king, and the return was thus:

[.embedded-content-document.legal]
--

By virtue of his Majesty`'s order, to me directed, and hereunto annexed, I certify,
that before the receipt of the said order, George Fox, in the said order mentioned,
was committed to his Majesty`'s jail, at the castle of Lancaster, in my custody,
by a warrant from Henry Porter, esq.
one of his Majesty`'s justices of the peace within the county palatine aforesaid,
bearing date the 5th of June now last past; for that he, the said George Fox,
was generally suspected to be a common disturber of the peace of this nation,
an enemy to our sovereign lord the king, and a chief upholder of the Quakers`' sect;
and that he, together with others of his fanatic opinion,
have of late endeavored to make insurrections, in these parts of the country,
and to embroil the whole kingdom in blood.
And this is the cause of his taking and detaining.
Nevertheless, the body of you said George Fox I have ready before Thomas Mallet, knight,
one of his Majesty`'s justices, assigned to hold pleas before his said Majesty,
at his chamber in Sergeants-Inn, in Fleet Street,
to do and receive those things which his Majesty`'s said
justice shall determine concerning him in this behalf,
as by the aforesaid order is required.

[.signed-section-signature]
George Chetham, Esq. Sheriff.

--

The king upon perusal of this, and consideration of the whole matter,
being satisfied of G. Fox`'s innocency,
commanded his secretary to send the following order to judge Mallet for his release:

[.embedded-content-document.legal]
--

It is his Majesty`'s pleasure that you give order for the releasing,
and setting at full liberty, the person of George Fox, late a prisoner in Lancaster jail,
and commanded here by an _habeas corpus._
And this signification of his Majesty`'s pleasure shall be your sufficient warrant.
Dated at Whitehall, the 24th of October, 1660.

[.signed-section-signature]
Edward Nicholas.

[.signed-section-context-close]
For Sir Thomas Mallet, knight, one of the justices of the King`'s Bench.

--

When this order was delivered to judge Mallet,
he forthwith sent his warrant to the marshal of the King`'s Bench, for G. Fox`'s release:
which warrant was thus:

[.embedded-content-document.legal]
--

By virtue of a warrant which this morning I have
received from the right honorable sir Edward Nicholas,
knight, one of his Majesty`'s principal secretaries,
for the releasing and setting at liberty of George Fox,
late a prisoner in Lancaster jail, and from there brought here, by habeas corpus,
and yesterday committed unto your custody;
I do hereby require you accordingly to release, and set the said prisoner, George Fox,
at liberty: for which this shall be your warrant and discharge.
Given under my hand the 25th day of October, in the year of our Lord God, 1600.

[.signed-section-signature]
Thomas Mallet.

[.signed-section-context-close]
To Sir John Lenthal, knight, marshal of the King`'s Bench, or his deputy.

--

G+++.+++ Fox having been prisoner now above twenty weeks,
was thus very honorably set at liberty by the king`'s command.
After it was known that he was discharged, several that were envious and wicked,
were troubled, and terror seized on justice Porter;
for he was afraid G. Fox would take the advantage of the law against him,
for his wrong imprisonment, and thereby undo him:
and indeed G. Fox was put on by some in authority,
to have made him and the rest examples.
But he said, he should leave them to the Lord; if the Lord did forgive them,
he should not trouble himself with them.

About this time, Richard Hubberthorn got an opportunity to speak with the king,
and to have a long discourse with him, which soon after he published in print.
Being admitted into the king`'s presence,
he gave him a relation of the state of his friends, and said,

[quote]
____
Since the Lord has called us, and gathered us to be a people, to walk in his fear,
and in his truth,
we have always suffered and been persecuted by the powers that have ruled,
and been made a prey of, for departing from iniquity;
and when the breach of no just law could be charged against us,
then they made laws on purpose to ensnare us;
and so our sufferings were unjustly continued.
____

[.discourse-part]
_King:_ It is true, those who have ruled over you have been cruel,
and have professed much which they have not done.

[.discourse-part]
_R+++.+++ Hubberthorn:_
And likewise the same sufferings do now abound in
more cruelty against us in many parts of this nation:
as for instance, one at Thetford in Norfolk, where Henry Fell,
(ministering unto the people,) was taken out of the meeting and whipped,
and sent out of the town, from parish to parish, towards Lancashire;
and the chief ground of his accusation in his pass, (which was shown to the king,) was,
because he denied to take the oath of allegiance and supremacy;
and so because that for conscience sake we cannot swear,
but have learned obedience to the doctrine of Christ, which says,
"`Swear not all;`" hereby an occasion is taken against us to persecute us;
and it is well known that we have not sworn for any, nor against any,
but have kept to the truth, and our yes has been yes, and our no, no, in all things,
which is more than the oath of those that are out of the truth.

[.discourse-part]
_King:_ But why can you not swear?
for an oath is a common thing among men to any engagement.

[.discourse-part]
_R+++.+++ Hubberthorn:_ Yes, it is manifest, and we have seen it by experience;
and it is so common among men to swear, and engage either for, or against things,
that there is no regard taken to them, nor fear of an oath;
that therefore which we speak of in the truth of our hearts,
is more than what they swear.

[.discourse-part]
_King:_ But can you not promise before the Lord, which is the substance of the oath?

[.discourse-part]
_R+++.+++ Hubberthorn:_ Yes, what we do affirm, we can promise before the Lord,
and take him to our witness in it; but our so promising has not been accepted,
but the ceremony of an oath they have stood for,
without which all other things were accounted of no effect.

[.discourse-part]
_King:_ But how may we know from your words that you will perform?

[.discourse-part]
_R+++.+++ Hubberthorn:_ By proving of us; for they that swear are not known to be faithful,
but by proving of them; and so we, by those that have tried us,
are found to be truer in our promises, than others by their oaths;
and to those that do yet prove us, we shall appear the same.

[.discourse-part]
_King:_ Pray, what is your principle?

[.discourse-part]
_R+++.+++ Hubberthorn:_ Our principle is this, "`That Jesus Christ is the true light,
which enlightens everyone that comes into the world,
that all men through him might believe;`" and that they were to
obey and follow this light as they have received it,
whereby they may be led unto God, and unto righteousness, and the knowledge of the truth,
that they might be saved.

[.discourse-part]
_King:_ This do all Christians confess to be truth;
and he is not a Christian that will deny it.

[.discourse-part]
_R+++.+++ Hubberthorn:_ But many have denied it, both in words and writings,
and opposed us in it;
and above a hundred books are put forth in opposition unto this principle.

[.small-break]
'''

Then some of the Lords standing by the king, said,
that none would deny that everyone is enlightened.

And one of the lords asked, how long we had been called Quakers,
or did we approve that name?

[.discourse-part]
_R+++.+++ Hubberthorn:_ That name was given to us in scorn and derision,
about twelve years since;
but there were some that lived in this truth before we had that name given unto us.

[.discourse-part]
_King:_ How long is it since you owned this judgment and way?

[.discourse-part]
_R+++.+++ Hubberthorn:_ It is near twelve years since I owned this truth,
according to the manifestation of it.

[.discourse-part]
_King:_ Do you own the sacrament?

[.discourse-part]
_R+++.+++ Hubberthorn:_ As for the word sacrament, I do not read of it in the Scripture;
but as for the body and blood of Christ I acknowledge it,
and that there is no remission without blood.

[.discourse-part]
_King:_ Well, that is it; but do you not believe that everyone is commanded to receive it?

[.discourse-part]
_R+++.+++ Hubberthorn:_ This we do believe, that according as it is written in the Scripture,
that Christ at his last supper took bread and broke it, and gave to his disciples,
and also took the cup and blessed it, and said unto them, "`And as often as you do this,
(that is,
as often as they broke bread,) you show forth the Lord`'s
death till he come;`" and this we believe they did;
"`and they did eat their bread in singleness of heart from house to house;`"
and Christ did come again to them according to his promise;
after which they said, "`We being many are one bread,
for we are all partakers of this one bread.`"

[.small-break]
'''

King`'s friend. Then one of the king`'s friends said, It is true;
for as many grains make one bread, so they being many members, were one body.

Another of them said, if they be the bread, then they must be broken.

[.discourse-part]
_R+++.+++ Hubberthorn:_
There is a difference between that bread which he broke at his last supper,
wherein they were to show forth, as in a sign, his death until he came;
and this whereof they spoke, they being many, are one bread;
for herein they were come more into the substance, and to speak more mystically,
as they knew it in the spirit.

[.discourse-part]
_King`'s friends:_
Then they said, it is true, and he had spoken nothing but truth.

[.discourse-part]
_King:_ How know you that you are inspired by the Lord?

[.discourse-part]
_R+++.+++ Hubberthorn:_ According as we read in the Scriptures,
that "`The inspiration of the Almighty gives understanding;`" so by his
inspiration is an understanding given us of the things of God.

Then one of the lords said, How do you know that you are led by the true spirit?

[.discourse-part]
_R+++.+++ Hubberthorn:_ This we know, because the Spirit of Truth reproves the world of sin,
and by it we were reproved of sin, and also are led from sin, unto righteousness,
and obedience of truth, by which effects we know it is the true spirit;
for the spirit of the wicked one does not lead into such things.

[.small-break]
'''

Then the king and his lords said it was truth.

[.discourse-part]
_King:_ Well, of this you may be assured,
that you shall none of you suffer for your opinions or religion,
so long as you live peaceably, and you have the word of a king for it;
and I have also given forth a declaration to the same purpose,
that none shall wrong you or abuse you.

[.discourse-part]
_King:_ How do you acknowledge magistrates, or magistracy?

[.discourse-part]
_R+++.+++ Hubberthorn:_ Thus we do acknowledge magistrates: whosoever is set up by God,
whether king as supreme, or any set in authority by him,
who are for the punishment of evil-doers, and the praise of them that do well,
such we shall submit unto, and assist in righteous and civil things,
both by body and estate: and if any magistrates do that which is unrighteous,
we must declare against it; only submit under it by a patient suffering,
and not rebel against any by insurrections, plots, and contrivances.

[.discourse-part]
_King:_ That is enough.

[.small-break]
'''

Then one of the lords asked, Why do you meet together,
seeing every one of you have the church in yourselves?

[.discourse-part]
_R+++.+++ Hubberthorn:_ According as it is written in the Scriptures, the church is in God,
1 Thess. 1:1 "`And they that feared the Lord,
did meet often together in the fear of the Lord,`" and to us it is profitable,
and herein we are edified and strengthened in the life of Truth.

[.discourse-part]
_King:_ How did you first come to believe the Scriptures were truth?

[.discourse-part]
_R+++.+++ Hubberthorn:_ I have believed the Scriptures from a child to be a declaration of truth,
when I had but a literal knowledge, natural education, and tradition;
but now I know the Scriptures to be true,
by the manifestation and operation of the Spirit of God fulfilling them in me.

[.discourse-part]
_King:_ In what manner do you meet, and what is the order in your meetings?

[.discourse-part]
_R+++.+++ Hubberthorn:_ We do meet in the same order as the people of God did, waiting upon him:
and if any have a word of exhortation from the Lord, he may speak it;
or if any have a word of reproof or admonition, and as every one has received the gift,
so they may minister one unto another, and may be edified one by another;
whereby a growth into the knowledge of the Truth is administered to one another.

[.discourse-part]
_One of the lords:_ Then you know not so much as you may know,
but there is a growth then to be admitted of?

[.discourse-part]
_R+++.+++ Hubberthorn:_ Yes, we do grow daily into the knowledge of the Truth,
in our exercise and obedience to it.

[.discourse-part]
_King:_ Are any of your friends gone to Rome?

[.discourse-part]
_R+++.+++ Hubberthorn:_ Yes, there is one in prison in Rome.

[.discourse-part]
_King:_ Why did you send him there?

[.discourse-part]
_R+++.+++ Hubberthorn:_ We did not send him there,
but he found something upon his spirit from the Lord,
whereby he was called to go to declare against superstition and idolatry,
which is contrary to the will of God.

[.small-break]
'''

King`'s friend said, There were two of them at Rome, but one was dead.

[.discourse-part]
_King:_ Have any of your friends been with the great Turk?

[.discourse-part]
_R+++.+++ Hubberthorn:_ Some of our friends have been in that country.

[.small-break]
'''

Other things were spoken concerning the liberty of the servants of the Lord,
who were called of him into his service,
that to them there was no limitation to parishes or places,
but as the Lord did guide them in his work and service by his spirit.

So the king promised that we should not any ways suffer for our opinion or religion;
and so in love passed away.

[.small-break]
'''

The king having promised Richard Hubberthorn over and again,
that his friends should not suffer for their opinion, or religion, they parted in love.
But though the king seemed a good-natured prince, yet he was so misled,
that in process of time he seemed to have forgot what he
so solemnly promised on the word of a king.

Now in this discourse mention being made of Rome, etc.
I will say by the bye, that one John Perrot and John Love being come to Leghorn in Italy,
and having been examined there by the inquisition,
they answered so well that they were dismissed.
Being come afterwards to Venice, Perrot was admitted to the doge, or duke, in his palace,
spoke with him, and gave him some books:
and from there he went with his fellow traveller to Rome.
Here they bore testimony against the idolatry committed there, in such a public manner,
that they were taken into custody.
John Love died in the prison of the inquisition; and though it was divulged,
that he had fasted to death, yet some nuns have told that he was dispatched in the night,
for fear he should annoy the church of Rome.
However it was, he died in sincerity of heart, and so was more happy than Perrot,
who though then perhaps he was in a pretty good frame of mind,
yet afterwards turned an eminent apostate,
having continued prisoner at Rome a great while, and at length got his liberty.
He was a man of great natural parts, but, not continuing in true humility,
ran out into exorbitant imaginations, of which more may be said hereafter.
About this time Samuel Fisher and John Stubbs were also at Rome,
where they spoke with some of the cardinals,
and testified against the Catholic superstition.
They also spread some books among the friars,
some of whom confessed the contents thereof to be truth: but, said they,
if we should acknowledge this publicly, we might expect to be burnt for it.
Notwithstanding Fisher and Stubbs went free, and returned unmolested.

The case of Mary Fisher, a maiden, and one of the first Quakers, so called,
that came into New England, as has been mentioned before, I cannot pass by in silence.
She being come to Smyrna, to go from there to Adrianople,
was stopped by the English consul, and sent back to Venice,
from which she came by another way to Adrianople,
at the time that Sultan Mahomet the fourth was encamped with his army near the said town.
She went alone to the camp, and got somebody to go to the tent of the grand vizier,
to tell him that an English woman was come who had
something to declare from the great God to the Sultan.
The vizier sent word,
that next morning he should procure her an opportunity for that purpose.
Then she returned to the town, and repaired next morning to the camp again,
where being come, she was brought before the sultan, who had his great men about him,
in such a manner as he was used to admit ambassadors.
He asked by his interpreters, whereof there were three with him,
whether it was true what had been told him,
that she had something to say to him from the Lord God?
She answered, '`Yes.`'
Then he bade her speak on: and she not being forward,
weightily pondering what she might say,
and he supposing that she might be fearful to utter her mind before them all, asked her,
whether she desired that any might go aside, before she spoke?
She answered, '`No.`' He then bade her speak the word of the Lord to them, and not to fear,
for they had good hearts, and could hear it.
He also charged her, to speak the word she had to say from the Lord,
neither more nor less, for they were willing to hear it, be it what it would.
Then she spoke what was upon her mind.

The Turks hearkened to her with much attention and gravity, till she had done;
and then the sultan asking her whether she had any thing more to say?
She asked him, whether he understood what she said?
And he answered, '`Yes, every word,`' and further said, that what she had spoken was truth.
Then he desired her to stay in that country, saying,
that they could not but respect such a one,
as should take so much pains to come to them so far as from England,
with a message from the Lord God.
He also offered her a guard to bring her into Constantinople, where she intended.
But she not accepting this offer, he told her it was dangerous traveling,
especially for such a one as she;
and wondered that she had passed so safe so far as she had: saying also,
it was in respect to her, and kindness that he offered it,
and that he would not for any thing she should come to the least hurt in his dominions.
She having no more to say, the Turks asked her, what she thought of their prophet Mahomet?
She answered warily that she knew him not; but Christ, the true prophet, the Son of God,
who was the light of the world, and enlightened every man coming into the world,
him she knew.
And concerning Mahomet she said, that they might judge of him to be true or false,
according to the words and prophecies he spoke; saying further,
'`If the word that a prophet speaks, come to pass,
then shall you know that the Lord has sent that prophet; but if it come not to pass,
then shall you know that the Lord never sent him.`'
The Turks confessed this to be true; and Mary having performed her message,
departed from the camp to Constantinople, without a guard,
where she came without the least hurt or scoff.
And so she returned safe to England.

Concerning Catharine Evans, and Sarah Cheevers, two women,
who at this time lay in the prison of the inquisition at Malta,
and were not released till after three years confinement,
where they suffered most grievous hardships; I intend to speak hereafter,
when I come to the time of their deliverance;
and then I propose to make a large and very remarkable description concerning it.

In the meanwhile I return to the affairs of England,
where the government now was quite altered.
Many of the late king`'s judges were now hanged and quartered:
among those was also colonel Francis Hacker, of whom, about six years before this time,
it has been said that he took George Fox prisoner.
But he now himself was in prison,
and impeached not only as one of those that kept the king prisoner,
but also that he signed the warrant for the king`'s execution,
and had conducted him to the scaffold.
To all which, and more, he said little, but that what he did,
was by order of his superiors; and that he had endeavored to serve his country.
But this did not avail him, for he was condemned for high treason,
and hanged and quartered in October.
A day or two before his death Margaret Fell visited him in prison;
and when he was put in mind of what formerly he had done against the innocent,
he remembered it, and said, he knew well whom she meant, and had trouble upon him for it.
For G. Fox, (who had compared him to Pilate,) bade him,
when the day of his misery and trial should come upon him,
to remember what he said to him.
And as Hacker`'s son-in-law, Needham, then did not hesitate to say,
that it was time to have G. Fox cut off,
so it came to be the lot of Hacker himself to be cut off at Tyburn, where he was hanged.
Such now was the end of many, who were not only guilty of the king`'s death,
and the putting to death of others who were for king Charles the Second,
but had also transgressed against God by persecuting godly people.
They had been often warned,
and several times told that God would hear the cries of the widows and fatherless,
that had been cruelly oppressed by them;
and as they had made spoil of the goods of those whom in scorn they called Quakers,
so now fear and quaking was brought upon them,
and their estates became a spoil to others.
How plainly E. Burrough had foretold this, has been said before;
and not to mention others, I will only say,
that one Robert Huntington came once into the steeple-house at Brough, near Carlisle,
with a white sheet about him, and a halter about his neck,
to show the Presbyterians and Independents there,
that the surplice was to be introduced again,
and that some of them should not escape the halter.
Now how mad soever this was said to be,
yet time showed it a presage of the impending disaster of the cruel persecutors:
for when king Charles had ascended the throne,
his most fierce enemies were dispatched out of the way.

The parliament sitting at this time,
some of those called Quakers were admitted to appear in the House of Lords,
where they gave reasons why they should not frequent the public worship, nor swear,
nor pay tithes; and they were heard with moderation.
The king also about this time showed himself moderate; for being solicited by some,
and more especially by Margaret Fell,
he set at liberty about seven hundred of the people called Quakers,
who had been imprisoned under the government of Oliver and Richard Cromwell,
This passed the easier, because those that were now at the helm,
had also suffered under the former government:
there seemed likewise some inclination to give liberty of conscience;
but there being among those that were now in authority, some also of a malicious temper,
they always found means to hinder this good work;
and it just now fell out so that something started up,
which put a stop to the giving such a liberty as aforesaid;
though it was advanced so far,
that an order was drawn up for permitting the Quakers the free exercise of their worship;
only the signing and seal to it was lacking,
when all on a sudden the Fifth Monarchy-men made an insurrection.
There was at that time a great number of this turbulent people in England; who,
perceiving that their exorbitant opinion was inconsistent with kingly government,
which now had taken place,
thought it not fitting for their cause to sit still while the government,
which was yet but new, should be fully settled and established.
Perhaps they had also some intent to free some of the late king`'s judges,
who were imprisoned; for among these was also Sir Henry Vane,
who having been one of the chief of the commonwealth party,
was likewise said to be one of the heads of the Fifth Monarchy-men.
It was in the night when these people made a rising; which caused such a stir,
that the king`'s soldiers sounded an alarm by the beating of drums.

The train-bands appeared in arms, and all was in an uproar,
and both the mob and soldiers committed great insolences for several days;
so that the Quakers, though altogether innocent,
became the object of the fury of their enemies,
and many were hauled to prison out of their peaceable meetings.

At that time George Fox was at London, and being lodged in Pall-mall,
at night a company of troopers came, and knocked at the door where he was;
which being opened, they rushed into the house, and laid hold on him.
One of these that had formerly served under the parliament,
clapped his hand to G. Fox`'s pocket, and asked, whether he had any pistol?
G+++.+++ Fox told him, he knew he did not use to carry pistols,
why then did he ask such a question of him, whom he knew to be a peaceable man?
Others of these fellows ran up into the chambers, and there found esquire Marsh,
before mentioned, in bed, who though he was one of the king`'s bed-chamber,
yet out of love to G. Fox, came and lodged where he did.
When the troopers came down again, they said, '`Why should we take this man away with us?
We will let him alone.`'
'`Oh,`' said the parliament soldier,`'he is one of the heads, and a chief ringleader.`'
Upon this the soldiers were taking him away.
But esquire Marsh hearing of it, sent for him that commanded the party,
and desired him to let G. Fox alone, since he would see him forthcoming in the morning,
and then they might take him.
Early in the morning there came a company of foot to the house;
and one of them drawing his sword, held it over G. Fox`'s head, which made him ask,
wherefore he drew his sword at a naked man?
At which his fellows being ashamed, bid him put up his sword:
and sometime after they brought him to Whitehall, before the troopers came for him.
As he was going out, he saw several of his friends going to the meeting,
it being then the First day of the week; and he intended to have gone there himself,
if he had not been stopped: but now it being out of his power to keep them company,
he commended their boldness, and encouraged them to persevere therein.
When he was come to Whitehall, seeing the soldiers and people were exceeding rude,
he began to exhort them to godliness.
But some great persons coming by, who were envious to him, said, '`What,
do you let him preach?
Put him into such a place, where he may not stir.`'
So he was put into that place, and the soldiers watched over him; but G. Fox told them,
though they could confine his body, and shut that up,
yet the word of life they could not stop.
Some then asked him, what he was?
He told them he was a preacher of righteousness.
After he had been kept there two or three hours, esquire Marsh spoke to the lord Gerard,
who came, and bid them set G. Fox at liberty.
When he was discharged, the marshal demanded fees.
G+++.+++ Fox told him he could not give him any: and he asked him,
how he could demand fees of him who was innocent?
Nevertheless he told him, that in his own freedom, he would give them two-pence,
to make him and the soldiers drink.
But they shouted at that, which made him say, if they would not accept it,
they might choose; for he should not give them fees.
Then he went through the guards, and came to an inn,
where several of his friends at that time were prisoners under a guard,
and about night he went to the house of one of his friends.

This insurrection of the Fifth-Monarchy-men, caused great disturbance in the nation;
and though the Quakers did not at all meddle with those boisterous people,
yet they fell under great sufferings because of them;
and both men and women were dragged out of their houses to prison,
and some sick men off their beds by the legs; among which was one Thomas Pachyn,
who being in a fever, was dragged by the soldiers out of his bed to prison,
where he died.

This persecution going on throughout the nation, Margaret Fell went to the king,
and gave him an account how her friends,
that were in nowise concerned in the said insurrection and riots, were treated;
for several thousands of them were cast into prison.
The king and council wondered how they could have such intelligence,
since strict charge was given for the intercepting of all letters,
so that none could pass un-searched.
But notwithstanding this, so much was heard of the numbers of the imprisoned,
that Margaret Fell went a second time to the king and council,
and acquainted them of the grievous sufferings of her friends.
G+++.+++ Fox then wrote a letter of consolation to his suffering friends;
and also published in print a declaration against all seditions, plotters, and fighters,
wherein he manifested, that they were a harmless people, that denied wars and fightings,
and could not make use of the outward sword, or other carnal weapons.
This declaration was presented to the king and his council, and was of such effect,
that the king gave forth a proclamation, that no soldiers should go to search any house,
but with a constable.
When afterwards some of the Fifth Monarchy-men were put to death because of their insurrection,
they did the Quakers, so called, that right,
that they cleared them openly from having a hand in, or knowledge of their plot.
This and other evidences caused the king, being continually importuned thereunto,
to issue forth a declaration,
that the Quakers should be set at liberty without paying fees.

Many of the Presbyterian preachers now temporized, and for keeping their benefices,
joined with the Episcopalians, and did not hesitate to put on the surplice.
But this gave occasion to many of their hearers to leave them, and join with the Quakers,
so called, who could not comply with the times.
Others, who were a little more steadfast, made use of their money to get liberty,
though under the government of Cromwell they would
permit no liberty of conscience to others;
insomuch that one Hewes, an eminent priest at Plymouth in Oliver`'s days,
when some liberty w`'as granted,
prayed that God would put it into the hearts of the chief magistrates of the nation,
to remove this cursed toleration.
But this Hewes, after the king was come in, being asked by one,
whether he would account toleration accursed now, answered only by shaking his head.

Now though many of the Quakers, as has been said, were released from prison,
yet they suffered exceedingly in their religious assemblies.
Once a company of Irishmen came to Pall-Mall, when G. Fox was there;
but the meeting was already broke up; and he being gone up into a chamber,
heard one of those rude persons, who was a colonel, say, he would kill all the Quakers.
Whereupon G. Fox came down, and told him, '`The law said, an eye for an eye,
and a tooth for a tooth; but you threatens to kill all the Quakers,
though they have done you no hurt:`' but said he further, '`Here is gospel for you:
here`'s my hair, here`'s my cheek, and here`'s my shoulder,`' turning it to him.
This so surprised the colonel, that he and his companions stood amazed, and said,
'`If this be your principle as you say, we never saw the like in our lives.`'
To which G. Fox said, '`What I am in words I am the same in life.`'
Then the colonel carried himself lovingly;
though a certain ambassador who stood without and then came in, said,
that this Irish colonel was such a desperate man, that he dared not come in with him,
for fear he should have done great mischief.

Notwithstanding such like rude encounters, yet by the change of the government,
some stop was put to the fierce current of persecution;
for the king being but newly settled on the throne, showed yet an inclination to lenity.
But this quiet did not last long, and was but a time of respiration: for the churchmen,
instigated, as it seems very probable, by the favorers of popery, continued envious,
and stayed but for an opportunity to show their malice.
An instance of which has been seen already on the insurrection of the Fifth Monarchy-men,
and in the sequel will be seen much clearer: since,
though they did not seem to persecute for conscience-sake, yet under a color of justice,
laws were made use of, that had formerly been enacted for the suppression of popery,
and to secure the kingdom against Jesuits, and other traitorous Catholics;
these being the laws, of which G. Fox in his letter to the king had said,
that they held up persecution about religion.

That it may be known what laws those were,
and that it may also appear what an unreasonable use has been made thereof,
I shall here set them down, or abstracts of them; that so it may be more plainly seen,
what awkward means have been made use of, and how sinistrously the laws were executed.
Sometimes I may interweave among these abstracts, some observations,
or an account of a case, which, though not placed in due time,
may yet be serviceable to give a true notion of things.
I now repair to those laws.

In the 27th year of king Henry the eighth, a law was made for payment of tithes:
for that king having either given or sold many chapels and abbeys to laymen,
those laymen had no right, as priests claimed to have,
to summon to ecclesiastical courts those that failed in paying of tithes.
But for this a law was provided, by virtue of which,
a judge of an ecclesiastical court might be helpful to laymen,
and in that law it was said,

[.embedded-content-document.legal]
--

If the judge of an ecclesiastical court make complaint to two justices of peace,
(_quorum unus,_) of any contumacy,
or misdemeanor committed by a defendant in any suit there depending for tithes,
the said justices shall commit such defendant to prison,
there to remain till he shall find sufficient surety to be bound before them by recognizance,
or otherwise to give due obedience to the process, proceedings, decrees,
and sentences of the said court.

--

By this law, which is pretended to be still in force, many honest people have suffered,
and been kept very long in prison;
for they refusing to find surety for the payment of tithes,
which for conscience-sake they could not give to
such ministers who lived from a forced maintenance,
and did not, as they judged, profit the people;
it was in the power of the priests to detain them prisoners,
till the pretended debt was paid; which the persecuted judged so unreasonable,
that some have therefore continued in prison for many years,
choosing rather to die in jail, than to uphold such preachers, by paying tithes to them.
And the Quakers, so called, have never offered resistance,
but suffering and forbearance have always been their arms,
though they were almost continually vexed with laws that were never made against them;
and more especially were they molested with the oath of supremacy,
which was made in the beginning of the reign of queen Elizabeth, though, it may be,
projected in the time of Henry the eighth, which runs thus:

[.embedded-content-document.legal]
--

I, A. B., do utterly testify and declare in my conscience, that the +++[+++king`'s]
highness is the only supreme governor of this realm,
and of all other (his) highnesses dominions and countries,
as well in all spiritual or ecclesiastical things or causes, as temporal.
And that no foreign prince, prelate, state, or potentate, has,
or ought to have any jurisdiction, power, superiority, preeminence, or authority,
ecclesiastical or spiritual, within this realm: and therefore I do utterly renounce,
and forsake all foreign jurisdictions, powers, superiorities, and authorities,
and do promise, that from henceforth I shall bear faith,
and true allegiance to the +++[+++king`'s]
highness +++[+++his]
heirs and lawful successors; and to my power, shall assist and defend all jurisdiction,
privileges, preeminences, and authorities, granted, or belonging to the +++[+++king`'s]
highness +++[+++his]
heirs and successors, or united and annexed to the imperial crown of his realm.
So help me God, and the contents of this book.

--

In the first year of queen Elizabeth, an act was made for uniformity of common-prayer,
and church service, having this clause:

[.embedded-content-document.legal]
--

Every person shall resort to their parish church, or upon let thereof, to some other,
every Sunday and holiday, upon pain to be punished by censures of the church,
and also to forfeit twelve-pence, to be levied by the church-wardens, there,
for the use of the poor, upon the offender`'s goods, by way of distress.

--

Here is to be noted, that some have prosecuted the pretended offenders on this clause,
to obviate greater severities; although this law was made because of the Catholics,
thereby to force them to come to church;
for about that time there were not so many Protestant Dissenters in England,
as afterwards; but these appearing in time,
were as well under the lash of this law as the Catholics;
for their religious assemblies were not reckoned to be churches
as the steeple-houses by a metonymy generally have been called;
at the same rate as the Jews`' meeting-houses have been called synagogues,
though the word itself properly signifies the assembly of the people.

Now, since the aforesaid law was not strictly obeyed, not only by Catholics,
but also by others, who aiming at a further reformation,
could not longer comply with the rites of the church of England,
in the 23rd year of Elizabeth, a more severe law was made, with this clause:

[.embedded-content-document.legal]
--

Every person not repairing to church, according to the statute of 1 Eliz.
2, shall forfeit twenty pounds for every month they so make default;
and if they so forbear by the space of twelve months, after certificate thereof,
made by the ordinary unto the King`'s Bench, a justice of the court, jail-delivery,
or peace of the county where they dwell,
shall bind them with two sufficient sureties in 200. at least, to their good behavior,
from which they shall not be released until they
shall repair to church according to the said statute.

--

This law it seems was not thought severe enough;
therefore in the 29th year of the said queen, another law was made with this clause:

[.embedded-content-document.legal]
--

The queen may seize all the goods,
and two-third parts of the lands and leases of every
offender not repairing to church as aforesaid,
in such of the terms of Easter and Michaelmas,
as shall happen next after such conviction,
for the sum then due for the forfeiture of twenty pounds a month, and yearly after that,
(in the same terms,) according to the rate of twenty pounds a month for so long time
as they shall forbear to come to church according to the said statute of 23 Eliz.
I.

--

Upon these acts many were prosecuted; but in the height of this proceeding,
George Whitehead, Gilbert Latey, and others,
solicited king Charles the Second in the behalf of their friends; which had such effect,
that the king ordered stay of process in various counties;
yet afterwards the prosecution was continued till after his death,
both as to imprisonment, as well as seizing of goods:
and other old laws were also made use of:
for in the 35th year of queen Elizabeth`'s reign,
when the Catholics sometimes were forming plots against the queen, an act was made,
containing the effect of this clause:

[.embedded-content-document.legal]
--

If any of above sixteen years of age shall be convicted
to have absented themselves above a month from church,
without any lawful cause, impugned the queen`'s authority in causes ecclesiastical,
or frequented conventicles, or persuaded others so to do,
under pretense of exercise of religion, they shall be committed to prison,
and there remain until they shall conform themselves,
and make such open submission as hereafter shall be prescribed:
and if within three months after such conviction, they refuse to conform,
and submit themselves, being thereunto required by a justice of the peace,
they shall in open session, abjure the realm:
and if such abjuration happen to be before justices of the peace in sessions,
they shall make certificate thereof at the next court session, or jail-delivery.

And if such an offender refuse to abjure, or going away accordingly,
does return without the queen`'s license, he shall be adjudged a felon,
and shall not enjoy the benefit of clergy; but if before he be required to abjure,
he makes his submission, the penalties aforesaid shall not be inflicted upon him.

--

Though it maybe supposed this act was made chiefly against Catholics,
yet some few of the Quakers, so called, had been prosecuted thereupon,
which was for their lives; for if they had been willing to depart the realm, yet such,
who for conscience-sake could not swear at all,
could not oblige themselves by oath that they would do so.
And this being very well known, it once happened, that one William Alexander,
of Needham in Suffolk, being with several more indicted upon this act, was asked,
'`Guilty or not guilty?
He not being hasty to answer, the judge said, '`Why don`'t you plead guilty or not guilty?`'
To which Alexander replied, '`What would you advise us to plead?`'
The judge, (who sometimes used to be severe enough,) said, '`Do you ask my advice?
'`Yes,`' said Alexander.
'`Then,`' returned the judge, '`you shall have it; and I`'ll advise you to plead not guilty.`'
So the prisoners accordingly pleaded not guilty.
Then said the judge to the prosecutors,`' Now you must prove these men,
neither to have been at their own parish church, nor at any other church or chapel,
else they are not within this act, which is a sanguinary law.`'
Thus the judge carried on his discourse,
to a discharge of Alexander and his friends from that severe indictment:
for the prosecutors were not able to prove this with evidence, as the law required.
One William Bonnet, had also been long in prison at Edmondsbury in Suffolk, on this act,
and one Richard Vickris near Bristol.
But now I go back again.

[.small-break]
'''

After the demise of queen Elizabeth, when James the First had ascended the throne,
the Catholics still continued their wicked designs,
of which the gunpowder plot may serve for an instance.
To suppress therefore these malicious people, and for the better discovering of them,
in the third year of that king`'s reign, an act was made,
in which was contained the following oath, which was to be taken by Catholic recusants:

[.embedded-content-document.legal]
--

I A. B. do truly and sincerely acknowledge, profess, testify,
and declare in my conscience before God and the world,
that our sovereign lord king James, is lawful and rightful king of this realm,
and of all other his majesty`'s dominions and countries; and that the Pope,
neither of himself, nor by any authority of the church, or see of Rome,
or by any other means, with any other, has any power or authority to depose the king,
or to dispose of any of his majesty`'s kingdoms or dominions,
or to authorize any foreign prince to invade, or annoy him, or his countries,
or to discharge any of his subjects from their allegiance and obedience to his majesty,
or to give license or leave to any of them to bear arms, raise tumults,
or to offer any violence or hurt to his majesty`'s royal person, state, or government,
or to any of his majesty`'s subjects, within his majesty`'s dominions.
Also I do swear from my heart, that notwithstanding any declaration,
or sentence of excommunication, or deprivation, made or granted,
or to be made or granted, by the Pope or his successors, or by any authority derived,
or pretended to be derived from him or his see, against the said king, his heirs,
or successors, or any absolution of the said subjects from their obedience,
I will bear faith and true allegiance to his majesty, his heirs and successors,
and him and them will defend to the uttermost of my power,
against all conspiracies and attempts whatsoever,
which shall be made against his or their persons, their crown and dignity,
by reason or color of any such sentence or declaration, or otherwise:
and will do my best endeavor to disclose, and make known unto his majesty,
his heirs and successors, all treasons, and traitorous conspiracies,
which I shall know or hear of to be against him, or any of them.
And I do further swear, that I do from my heart abhor, detest, and abjure,
as impious and heretical, this damnable doctrine and position,
that princes which be excommunicated, or deprived by the Pope, may be deposed,
or murdered by their subjects, or any other whatsoever.
And I do believe, and in my conscience am resolved, that neither the Pope,
nor any person whatsoever, has power to absolve me of this oath, or any part thereof,
which I acknowledge by good and full authority to be lawfully ministered unto me,
and do renounce all pardons and dispensations to the contrary.
And all these things I do plainly and sincerely acknowledge,
and swear according to the express words by me spoken,
and according to the plain and common sense and understanding of the same words,
without any equivocation, or mental evasion, or secret reservation whatsoever.
And I do make this recognition and acknowledgment, heartily, willingly, and truly,
upon the true faith of a Christian.
So help me God.

--

This oath, commonly called the oath of allegiance,
was afterwards called by the name of the test;
and the introduction of it makes mention of the gunpowder-plot,
and signifies that this expedient was contrived to discover Roman Catholics;
and yet many of the people called Quakers, have suffered thereby many years;
for though they did not refuse to declare their allegiance,
yet because it was well known they were not for swearing at all,
this oath was continually made use of as a snare to imprison them.
Now the punishment stated against these recusants, was a _premunire:_
and how grievously many Quakers have been oppressed on that account,
though not easily related,
yet I may give instances in due places of several in the sequel.
Other severe laws for persecution have been made since,
as will be seen in their proper time.

At the close of this year,
E+++.+++ Burrough wrote a consolatory epistle to his
fellow-laborers in the ministry of the gospel,
which I cannot omit to insert here,
because it shows very evidently how valiant he was in the service of Truth,
which epistle is as follows;

[.embedded-content-document.epistle]
--

Dearly and well-beloved brethren, in the heavenly relation, and blessed immortal birth,
of which we are born most dearly in our Father`'s love;
my salutation extends unto you all,
as one with you perfectly in sufferings and in rejoicings, in faith and patience,
and even in all things which you do and suffer for in the name of the Lord our God;
and my soul greets you, and embraces you, and fervently wishes peace, love, and unity,
and the increase of every good gift unto you all; for I am perfectly one with you;
if you receive of our father`'s fulness, I am refreshed; and if you rejoice, I am glad;
and if you suffer, and be in heaviness, I freely partake with you; whatsoever is yours,
whether liberty or bonds, whether life or death, I partake of the same;
and whatsoever I enjoy, the same also is yours; we are of one birth, of one seed,
of one line, even of the generation of him who is without beginning of days,
or end of life, who is a high priest, made after the power of an endless life;
and as he was blessed of the Father, so are we, because we are of the same birth,
and are partakers of his nature, and he lives in us, and we in him.

Well, my dear companions, I need not multiply words unto you,
as if you knew not these things; for what know I, that you know not?
Or, what can I say, but you know the same?
Yet bear with me, for my heart is very full, and my soul ready to be poured forth,
that I may once more express a little quantity of what is abounding in my heart;
for love, even perfect love, even that love wherewith we are beloved of the Father,
fills my heart at this time towards all of you, from the least to the greatest;
and I know nothing but love towards you all;
and I doubt not but in the same love you do receive this my salutation,
which is from the fountain of love, which at this time is opened in my heart.

Now, dearly beloved,
the present considerations of my heart are very many
concerning the great love of the Father,
which hitherto has been showed unto us; we all know, how that he called us by his grace,
and turned our hearts from the vanities and evil ways of this world,
and sanctified us by his word, and put his image upon us, and called us by his name,
and redeemed us unto himself,
and gave us the testimony of his holy Spirit in our own hearts,
that we should be his people, and he would be our God; he taught us, and instructed us,
and fed us, and gave us peace and rest in himself,
and freed us from the bondage of sin and corruption, and from his terror because of sin;
and he removed our transgressions, and blotted them out, and ceased to smite us any more,
but brought us into the land of rest, flowing with mercy, and peace, and knowledge,
and all good things: this did the Lord our God do for us in the days of our infancy,
even when we were yet in our sins he called us forth, and cleansed us from them:
and when we were strangers to him, he made himself known unto us;
and when we were wholly ignorant, he gave us knowledge; and when we were not a people,
he raised us up, and made us worthy to be called by his name; and thus,
after this manner, did the Father love us, and show his love unto us: this you know,
even as I do, and the consideration of it causes me thus to express it.

Again, when he had thus wrought for us, and showed his love unto us,
he was pleased to call us out into his work,
to the turning and converting of others unto the way of life; he put his Spirit into us,
and gave us gifts of knowledge and utterance, and armed us with wisdom, and strength,
and courage,
and every way fitted us for that work and service in which he has carried us on; he,
I say, fitted us for his work, and called us into it, and carried us on joyfully in it,
and all this of his free love, and infinite power; and what we have been,
and what we have done, it has been only of the Lord, and not of ourselves,
even of his love, which to us may be admirable: for alas! what were we but children,
and neither prophets, nor prophets`' sons,
and our education unanswerable for these things, and to perform this calling?
And therefore it is the Lord, and only he that has effected his own purpose through us,
and by us, as instruments mean of ourselves, but by him very excellent.

Again, he has mightily prospered us in his work,
and a glorious effect we have beheld of our labors, and travels, and testimony; yes,
the Lord has been with us abundantly, and his arm has compassed us about,
and he has often given us great victory over the wise and prudent of this world;
he has made his own word often very powerful in our mouths,
to the wounding of the consciences of our enemies;
and the Lord has blessed our testimony, to the confounding the wisdom of this world,
and to the gathering of many unto himself;
and he has gone forth before us in his authority,
and been always with us in his own work; and our testimonies, labors,
and travels have been very precious and pleasant unto the Lord, and all his people;
and the effect thereof causes my soul to rejoice, because the Lord has been with us,
and prospered us into a great people, who have received our witness,
and accepted thereof unto their salvation; and unto the Lord alone,
the glory of all this appertains.

And for these eight years and upward,
the hand of the Lord has carried us through great labors and travels in his service,
and many dangers, and persecutions, and afflictions have attended us all this time;
and you know that many a time has the Lord delivered us
from the hands of such as would have destroyed us;
and we have been delivered again and again, out of dangers and difficulties,
and the Lord has been a present help unto us, in the time of our trouble;
for the plotting of the wicked, for the purpose of ungodly men,
has often been broken for our sakes,
even many a time have we been delivered out of the snare that has been laid for us,
and we have seen our enemies fall before us on the right hand, and on the left,
even the wise in their worldly wisdom, and the foolish in their brutishness,
both professors and profane has our God often cut short
in their desires and endeavors for our destruction;
and we have been wonderfully preserved unto this day;
and all this I attribute to the infinite love and power of the Lord God,
who is blessed forevermore.

And through all these things we are yet alive,
and the Lord does not fail us unto this hour, but he lives and walks in us,
and his testimony is with us, even the seal of his good Spirit in our hearts,
that we are his sons and servants,
and we are confirmed by many tokens that he is our God, and we are his people,
and that great oppressions which we have met withal, have not restrained us,
but through it all, have we grown, and prospered unto this day:
and concerning the things whereof we have testified these many years,
I am no way doubtful but our God will fulfill them,
neither can my confidence be shaken by what is or can come to pass;
for antichrist must fall, false ministry and worship, false ways and doctrines,
God will confound, false power and false church the Lord will lay low,
and truth and righteousness must reign; and God will gather his people more and more,
and glorious days will appear; God will exalt his kingdom upon earth,
and throw down the kingdom of the man of sin; all oppression must cease,
and the oppressors shall be no more; and God will free his people,
and they shall be happy in this world, and forever:
these things have we prophesied from day to day; and my faith is constant and unmovable,
that God will effect these things in his season: for the Lord never yet deceived me,
but what he has said, will surely come to pass.

And therefore, brethren, let us be in hope and patience,
and live in the word of patience, and not be fainthearted,
as though the Lord had forgotten us, or was unmindful of us,
or as though he would not perform what he had testified of by us; for he is not a man,
that he should lie, nor as a man, that he is given to change: but lift up your heads,
for the Lord is with us, even in our greatest tribulations and afflictions,
and he will accomplish his purpose; for he is mighty to save his people,
and to destroy his enemies.

It is true, the gates of hell at this time seem to be open against us,
and we are a people like to be swallowed up of our enemies,
and floods of wickedness seem to overflow,
and the waves of the great sea seem to be void of mercy,
and the hope of our adversaries is to extinguish us from being a people,
and to destroy us from the face of the earth;
and the hands of our persecutors are highly exalted at this day,
as though all that we have done for the Lord, by our labors and travels,
should now be made of none effect.

Well, dear brethren, though it be thus, yet our God can deliver us,
and confound our adversaries; and we can appeal unto our God,
and can spread our cause before him:
and he knows that our sufferings and afflictions are altogether unjust, and unequal,
and unrighteous, and that our persecutors do afflict us out of their envy,
and without any just cause administered unto them by us; our God knows it,
angels and saints know it, that we are at this day a persecuted people,
for religion`'s sake; and this our present affliction is not any just punishment,
either from the justice of God, or from the justice of men.

For God has given us the witness of his eternal Spirit,
that wrath is not in him towards us; his wrath be to his enemies,
but unto us is joy and peace forevermore: and the Lord clears us, and he justifies us,
who then shall condemn us?
He charges no guilt upon us, as if we were unto ourselves the cause, by our evil deeds,
of these our present sufferings, and as if this were come to pass upon us,
as punishment from the hand of God: I say, it is not so;
these our present sufferings are not out of God`'s anger towards us,
for his love is to us, let his wrath be to his enemies: and as I said,
neither is this suffering in the justice of men; for unto all the world we can say,
(and God himself shall plead our cause,) whom have we wronged or done evil to?
What evil have we done to any man`'s person?
Whose goods have we falsely taken or coveted?
Against whom have we designed mischief?
Even the Lord himself be judge between us and our persecutors in this matter;
for unto him we are known that we do desire the good of all, and not the hurt of any,
and yet we are dealt with as evil-doers;
when as the God of heaven is witness in our consciences,
that we neither plot nor contrive,
nor agitate in thought or word the hurt of any man`'s person:
but we walk justly towards all,
it being our principle to do to others as we would be done unto;
and we can plead our cause unto our God, and he shall plead our cause with our enemies,
and this is the present state of our case;
what we suffer at this time it is singly in the cause of God, and for righteousness-sake,
and for the testimony of Jesus, which we hold;
therefore freely let us commit our cause unto the God of heaven, and if we die,
it is for him, and if we live, it is to him;
and we seek not vengeance against our enemies,
but leave it to the Lord to plead with them.

And, dearly beloved,
I hope I need not exhort you to be patient and faithful in this day of our trial,
knowing that the cause is so excellent in which we are tried,
it is God`'s cause and not our own;
and I hope you all have the testimony of his Spirit in your consciences,
verifying the truth of the cause for which we suffer; and having that evidence,
we need not to be doubtful as towards God, nor ashamed before men,
if so be that everyone feels the evidence of the Spirit of God bearing witness,
that we suffer for righteousness-sake, and for the name of Christ Jesus.

And so dear brethren, lift up your heads, and be assured, that we are the Lord`'s,
and in his cause we are tried,
and he will judge and avenge our persecutors in his season,
and we shall be a people when the Egyptians lie dead upon the sea-shore,
and when the raging sea is dried up, this same people shall be safe;
for has the Lord done so excellent things for us?
Has he led us forth, and blessed us unto this day?
And has he preserved us hitherto through many tribulations and dangers?
Has he showed infinite love and favor unto us to this hour?
And will he now allow us to be destroyed from being a people?
Surely no.
Will he give our enemies their heart`'s desire to cut us all off,
that they may blaspheme his name?
Surely no.
And if it be the pleasure of the Lord,
that some of us should seal our testimony with our blood, good is the will of the Lord;
not ours, but his will be done;
for the testimony that we have borne for these many years,
has been so excellent in itself, and in its fruits and effects,
that the finishing of it deserves the best seal that possibly we can sign it with,
which is indeed our heart`'s blood; and this dwells upon my spirit; and yet,
though it should be thus, my confidence is sure, that the work of the Lord shall prosper,
and our testimony shall be glorious forever,
and this people shall never be extinguished from being a people.

And I know not any thing that remains upon our part at this day,
but that we commit ourselves into the hand of the Lord, living in the seed of God,
wherein our election is sure, before the world was, and forever;
and let us remember one another, and pray one for another;
and let us stir up all the children of our Father to faithfulness and patience,
while we have time; I say, let us walk to the glory of the Lord,
keeping faith and a good conscience to our last end; our testimony shall never die,
nor our memories ever perish when we are ceased to be;
and though we suffer now the loss of life, and all we have,
yet the effects thereof will be glorious in ages to come,
and our present sufferings will hasten the glory of God`'s work throughout the world:
receive this as my salutation to you all.

It is now eight days since I left Ireland,
where my service has been precious for the Lord for full six months,
all which time the Lord carried me in much faithfulness and diligence in his service,
to the confirming of many in the truth of God, and to the converting of others;
and through and because of the presence of the Lord which was with me,
I had a very precious time,
and was wonderfully preserved through many dangers and trials;
and I travelled near two thousand miles to and fro in that land,
and had very free passage in the principal cities and towns,
till my work for the present was fully ended there,
having more time than could be expected to clear my conscience to all people.
It would be too large to mention every particular transaction,
wherein I perceived the eminent hand of God with me;
and also many things I observed concerning the present
slate of things which I shall not mention;
for what have we to do with the affairs of worldly kingdoms?
But as for friends, it was well with them,
they grow and increase in the blessings and fulness of the Father;
and when I came from there all was quiet, and very few in prison, though, I suppose,
the tidings of things as they are here, will produce the same sufferings upon them:
but I hope they will be bold and valiant for the truth,
in giving their testimony by faithful sufferings, till these things be finished.

Thus I remain in life and death, and when I am no more, in everlasting remembrance,
your dear brother and companion,
by doing and suffering for the name of the Lord and his truth.
I am well, and at liberty, as yet.

[.signed-section-signature]
E+++.+++ B.

[.signed-section-context-close]
Eleventh of the Twelfth month, 1660.

--
