== Chpater XI.

=== 1661-62.

[.chapter-synopsis]
* Continuation of persecution in New England
* Wm. Leddra
* Wenlock Christison
* Remarkable Trials
* The king`'s Mandamus
* Cruel whippings
* Indignities committed on the Regicides
* Letter to the king by G. Fox the Younger
* Death of G. Fox the Younger
* Principles of Friends relating to Government
* Deputies from New England in London
* "`A Battledoor`" published
* Conference between Quakers and Jesuits
* John Perrot
* Trial and Legal Decision respecting the marriages of Friends
* The penitent jailor
* Imprisonment of Catherine Evans and Sarah Cheevers
* Constancy under suffering
* Final escape
* Letters

The year 1661 being come, the government was altogether changed,
Charles the Second was now seated on the throne of England in peace,
and the power of persecution seemed somewhat restrained;
so that there was an appearance of some quiet and calm.
Therefore I will now take a turn to New England,
to draw back the curtains of the bloody stage at Boston.
We have already seen in the foregoing relation, how William Robinson,
Marmaduke Stevenson, and Mary Dyer, were put to death by their persecutors,
but their blood-thirstiness was not yet quenched.

William Leddra, who was banished from Boston on pain of death,
was under such necessity of conscience, that he could not forbear returning there;
where he came about the conclusion of the foregoing year; but was soon taken prisoner,
and being fastened to a log of wood, was kept night and day locked in chains,
in an open prison, during a very cold winter; where we will leave him for the present,
and in the meanwhile insert here an apology of the
Boston persecutors concerning their cruel carriage,
which may serve to confirm the truth of what has
been already related of their wicked dealings.
For it seems,
that fearing their bloody deeds would be disapproved by the court of England,
they thought it safest for them to gild their transactions with a specious pretense;
though this was of no other effect than that thereby
they yet more exposed their own shame to public view,
and in process of time they also incurred the King`'s displeasure;
for though Charles the Second was inclined to voluptuousness, yet he was good-natured,
and the persecution in his reign proceeded chiefly
from the instigation of other malicious men.
But to come to the apology or declaration of the bloody persecutors, it was as follows:

[.embedded-content-document]
--

Although the justice of our proceedings against Wm. Robinson, Marmaduke Stevenson,
and Mary Dyer, supported by the authority of this court, the laws of this country,
and the law of God,
may rather persuade us to expect encouragement and
commendation from all prudent and pious men,
than convince us of any necessity to apologize for the same:
yet for as much as men of weaker parts, out of pity and commiseration,
a commendable and Christian virtue, yet easily abused,
and susceptible of sinister and dangerous impressions, for lack of a full information,
may be less satisfied; and men of perverse principles, led to calumniate us,
and render us as bloody persecutors; to satisfy the one,
and stop the mouths of the other, we thought it requisite to declare,
about three years since, several persons professing themselves Quakers,
(of whose pernicious opinions and practices we had received intelligence
from good hands from Barbados and England,) arrived at Boston,
whose persons where only secured to be sent away the first opportunity,
without censure or punishment, although their professed tenets,
turbulent and contemptuous behavior to authority,
would have justified a severer animadversion;
yet the prudence of this court was exercised,
only in making provision to secure the peace and order here established,
against their attempts, whose design, (we were well assured by our own experience,
as well as by the example of their predecessors in
Munster,) was to undermine and ruin the same.

And accordingly a law was made and published, prohibiting all masters of ships,
to bring any Quakers into this jurisdiction,
and themselves from coming in on penalty of the house of correction,
till they should be sent away.
Notwithstanding which, by a back door they found entrance,
and the penalty inflicted on themselves proving insufficient
to restrain their impudent and insolent obtrusions,
was increased by the loss of the ears of those who offended the second time;
which also being too weak a defense against their impetuous frantic fury,
necessitated us to endeavor our security; and upon serious consideration,
after the former experiments by their incessant assaults, a law was made,
that such persons should be banished upon pain of death,
according to the example of England, in their provision against Jesuits;
which sentence being regularly pronounced at the last court of assistants,
against the parties above named, and they either returning,
or continuing presumptuously in this jurisdiction after the time limited,
were apprehended, and acknowledging themselves to be the persons banished,
were sentenced by the court to death, according to the law aforesaid,
which has been executed upon two of them.
Mary Dyer, (upon petition of her son,
and the mercy and clemency of this court,) had liberty to depart within two days;
which she has accepted of.
The consideration of our gradual proceeding will
vindicate us from the clamorous accusations of severity,
our own just and necessary defense calling upon us, (other means failing,
to offer the point, which these persons have violently and willfully rushed upon,
and thereby become felons de se; which, might it have been prevented,
and the sovereign law, _salus populi,_ (English: the safety of the people) been preserved,
our former proceedings,
as well as the sparing Mary Dyer upon an inconsiderable intercession,
will manifestly evince, that we desire their lives absent,
rather than their deaths present.

[.signed-section-signature]
Edward Rawson, Secretary.

--

In this apology, wherein the Quakers, (who always were a harmless people,
and never made resistance with outward arms,) are compared
to the mutinous and riotous Anabaptists of Munster,
it is also said of them, that by a back door they found entrance.
And this reflects on some who unexpectedly came into New England by land,
since they could find no opportunity to come by sea,
because the ship-masters fearing the severity of the Boston laws,
were unwilling to carry any Quakers there.
This gave occasion to Thomas Thirstone, (who having been already at Boston,
was sent away on board a ship,) to think on other means;
for finding himself moved in spirit to go there again, he and Josiah Cole,
of whom mention has been made before, and who may be further spoken of hereafter,
went from England to Virginia, from which they, with one Thomas Chapman,
travelled several hundreds of miles on foot through vast wildernesses and woods,
and so at length came into New England, which made the persecutors there astonished;
for they thought this impossible,
that way having been counted impassable for other men than the Indians,
many of whom in those parts are warlike men,
who behaved themselves well toward our travelers, whose journey however was very hard;
for they had not only hunger and cold, it being winter time, to encounter with,
but they were also in danger of being devoured by wild beasts,
or of perishing in unknown marshes or bogs.
But they were preserved by an Almighty hand;
though this marvelous passage was represented like a criminal sauciness,
by these New England persecutors.

It seems to me that the aforesaid apology, which was published in print,
and likewise answered, was given forth before Mary Dyer was put to death;
but after her death the general court of Boston sent
over an address to king Charles the Second,
signed by their governor John Endicot, to justify their cruel proceedings.
Herein they said, that they had chosen rather the pure Scripture worship,
with a good conscience, in that remote wilderness among the heathen,
than the pleasures of England, with subjection to the imposition of the then so disposed,
and so far prevailing hierarchy, which they could not do without an evil conscience.

Concerning the Quakers, they said, that they were open capital blasphemers,
and seducers from the glorious Trinity, the Lord Christ, the blessed gospel;
open enemies to the government itself;
and malignant promoters of doctrines directly tending to subvert both church and state.

Moreover they said, that at last they had been constrained for their own safety,
to pass a sentence of banishment against them on pain of death,
since the magistrate in conscience judged himself called for the defense
of all to keep the passage with the point of the sword held towards them;
and that this could do no harm to them that would be warned thereby.
But the Quakers rushing themselves thereupon was their own act, and a crime,
bringing their blood upon their own heads.

Could they have made the king believe this, they would willingly have done it;
but he had too much sense to be thus imposed upon,
though they did whatever they could to prevent his hearing the other party,
in order whereunto they said, '`Let not the king hear men`'s words;
your servants are true men, fearers of God and the king, and not given to change,
zealous of government and order; not seditious to the interest of Caesar.`'

How smooth and plausible soever this seemed, yet it could not stand the test;
and E. Burrough, who answered it in print, addressed the king thus:

[.embedded-content-document.address]
--

O king, this my occasion to present you with these considerations is very urgent,
and of great necessity, even in the behalf of innocent blood,
hoping that my work will find such favor with you,
as to induce you to the reading and serious consideration thereof.

--

E+++.+++ Burrough then examining all their pretended reasons,
represented also to the king how some of these petitioners some time before
had not stuck to write in a letter from Boston to one Gordon:
'`There is more danger in these Quakers, to trouble and overcome England,
than in the king of Scots,
and all the Catholic princes in Germany;`' which plainly denoted,
that they reputed the king a troubler of England,
whom they numbered with the Catholic princes of Germany.
What E. Burrough obtained of the king for his friends, we may see hereafter.

But first I return to William Leddra, whom I left in prison:
it was on the 9th of the First month of this year,
that he was brought into the court of assistants, with his chains and log at his heels.
And he asking the jailer, when he intended to take off the irons from his legs,
the jailer roughly answered, '`When you are going to be hanged.`'
W+++.+++ Leddra then being brought to the bar, it was told him by the rulers,
speaking of their law, that he was found guilty, and so, that he was to die.
He said, '`What evil have I done?`'
The answer was, his own confession was as good as a thousand witnesses.
He asked, what that was?
To which they answered, that he acknowledged these Quakers that were put to death,
and that they were innocent.
Besides, that he would not put off his hat in court, and that he said thee and thou.
Then said William to them, '`You will put me to death for speaking English,
and for not putting off my clothes?
To this major-general Denison returned,`'A man may speak treason in English.`'
And William replied, '`Is it treason to say _thee_ and _thou_ to a single person?
But none answered, only Simon Broadstreet, one of the court, asked him,
whether he would go for England?
To which he answered, '`I have no business there.`'
Hereupon Broadstreet, pointing to the gallows, said, '`Then you shall go that way.`'
To which William returned, '`What,
will you put me to death for breathing in the air in your jurisdiction?
And for what you have against me I appeal to the laws of England for my trial;
and if by them I am guilty, I refuse not to die.`'
Of this no notice was taken, but instead thereof,
they endeavored to persuade him to recant of his error,
(as they styled it,) and to conform; to which with a grave magnanimity he answered,
'`What! to join with such murderers as you are?
Then let every man that meets me say,
lo this is the man that has forsaken the God of his salvation.`'

While the trial of W. Leddra was you going on, Wenlock Christison,
who was already banished upon pain of death, came into the court.
This struck a damp upon them,
insomuch that for some space of time there was silence in the court:
but at length one of the bloody council cried, '`Here is another,
fetch him up to the bar,`' Which the marshal performing, the secretary Rawson said,
'`Is not your name Wenlock Christison?`'
'`Yes,`' said Wenlock.
'`Well,`' said the governor, John Endicot, '`,what do you here?
Were you not banished upon pain of death?`'
To which Wenlock answered, '`Yes, I was.`'
And to the question, '`What do you here then?
he answered, '`I am come here to warn you that you should shed no more innocent blood;
for the blood that you have shed already,
cries to the Lord God for vengeance to come upon you.`'
Whereupon it was said, '`Take him away, jailer.`'
It having been told W. Leddra,
that at the last general court he had liberty given him to go for England,
or to go out of their jurisdiction; and that promising to do so, and come there no more,
he might save his life; he answered, '`I stand not in my own will,
but in the will of the Lord: if I may have my freedom, I shall go,
but to make you a promise I cannot.`'
But this was so far from giving content,
that they proceeded to pronounce sentence of death against him; which being done,
he was led from the court to prison again,
where the day before his death he wrote the following letter to his friends:

[.embedded-content-document.epistle]
--

[.salutation]
Most dear and inwardly beloved,

The sweet influences of the morning star,
like a flood distilling into my innocent habitation,
has so filled me with the joy of the Lord in the beauty of holiness,
that my spirit is as if it did not inhabit a tabernacle of clay,
but is wholly swallowed up in the bosom of eternity, from which it had its being.

Alas, alas, what can the wrath and spirit of man, that lusts to envy,
aggravated by the heat and strength of the king of the locusts,
which came out of the pit, do unto one that is hid in the secret places of the Almighty,
or unto them that are gathered under the healing wings of the Prince of Peace?
under whose armor of light they shall be able to stand in the day of trial,
having on the breastplate of righteousness, and the sword of the spirit,
which is their weapon of war against spiritual wickedness, principalities, and powers,
and the rulers of the darkness of this world, both within and without.
Oh, my beloved!
I have waited as a dove at the windows of the ark, and have stood still in that watch,
which the Master,
(without whom I could do nothing,) did at his coming reward with fulness of his love,
wherein my heart did rejoice,
that I might in the love and life of God speak a
few words to you sealed with the spirit of promise,
that the taste thereof might be a savor of life, to your life,
and a testimony in you of my innocent death: and if I had been altogether silent,
and the Lord had not opened my mouth unto you, yet he would have opened your hearts,
and there have sealed my innocency with the streams of life,
by which we are all baptized into that body which is in God,
whom and in whose presence there is life; in which, as you abide,
you stand upon the pillar and ground of truth; for, the life being the truth and the way,
go not-one step without it, lest you should compass a mountain in the wilderness;
for unto everything there is a season.

As the flowing of the ocean does fill every creek and branch thereof,
and then retires again towards its own being and fulness, and leaves a savor behind it,
so does the life and virtue of God flow into every one of your hearts,
whom he has made partakers of his divine nature; and when it withdraws but a little,
it leaves a sweet savor behind it, that many can say,
they are made clean through the word that he has spoken to them:
in which innocent condition you may see what you are in the presence of God,
and what you are without him.
Therefore, my dear hearts, let the enjoyment of the life alone be your hope,
your joy and consolation,
and let the man of God flee those things that would lead the mind out of the cross,
for then the savor of the life will be buried:
and although some may speak of things that they received in the life, as experiences,
yet the life being veiled,
and the savor that is left behind washed away by the fresh floods of temptation,
the condition that they did enjoy in the life, boasted of by the airy thing,
will be like the manna that was gathered yesterday, without any good scent or savor.
For, it was only well with the man while he was in the life of innocency;
but being driven from the presence of the Lord into the earth, what can he boast of?
And although you know these things, and many of you, much more than I can say; yet,
for the love and zeal I bear to the truth and honor of God,
and tender desire of my soul to those that are young,
that they may read me in that from which I write,
to strengthen them against the wiles of the subtle serpent that beguiled Eve, I say,
stand in the watch within, in the fear of the Lord, which is the very entrance of wisdom,
and the state where you are ready to receive the secrets of the Lord:
hunger and thirst patiently, be not weary, neither doubt.
Stand still, and cease from your own working,
and in due time you shall enter into the rest, and your eyes shall behold his salvation,
whose testimonies are sure and righteous altogether: let them be as a seal upon your arm,
and as jewels about your neck, that others may see what the Lord has done for your souls:
confess him before men, yes, before his greatest enemies;
fear not what they can do unto you: greater is he that is in you,
than he that is in the world: for he will clothe you with humility,
and in the power of his meekness you shall reign over all
the rage of your enemies in the favor of God;
wherein, as you stand in faith, you are the salt of the earth; for,
many seeing your good works, may glorify God in the day of their visitation.
'`Take heed of receiving that which you saw not in the light,
lest you give ear to the enemy.
Bring all things to the light, that they may be proved, whether they be wrought in God;
the love of the world, the lust of the flesh, and the lust of the eye,
are without the light, in the world;
therefore possess your vessels in all sanctification and honor,
and let your eye look at the mark: he that has called you is holy:
and if there be an eye that offends, pluck it out, and cast it from you:
let not a temptation take hold, for if you do, it will keep from the favor of God,
and that will be a sad state; for, without grace possessed,
there is no assurance of salvation: by grace you are saved;
and the witnessing of it is sufficient for you,
to which I commend you all my dear friends, and in it remain.

[.signed-section-closing]
Your brother,

[.signed-section-signature]
William Leddra.

[.signed-section-context-close]
Boston Jail, the 13th of the First Month, 1660-61. The day before he suffered.

--

The next day after this letter was written, the execution of W. Leddra was performed,
which was on the 14th of the First month.
After the lecture was ended, the governor, John Endicot,
came with a guard of soldiers to the prison, where W. Leddra`'s irons were taken off,
with which he had been chained to a log both night and day during a cold winter;
and now they were knocked off, according to what the jailer once said,
as has been related before.
William then having taken his leave of Wenlock Christison, and others then in bonds,
when called, went forth to the slaughter,
encompassed with a guard to prevent his speaking to his friends;
which Edward Wharton an inhabitant of Salem, and also banished on pain of death, seeing,
and speaking against, one among the company said,
'`O Edward it will be your turn next!`' To which Captain Oliver added,
'`if you speak a word, I`'ll stop your mouth.`'
Then W. Leddra being brought to the foot of the ladder, was pinioned,
and as he was about to ascend the same, he took leave of his friend, E. Wharton,
to whom he said, '`All that will be Christ`'s disciples, must take up the cross.`'
He standing upon the ladder, somebody said, '`William,
have you any thing to say to the people?`'
Thereupon he spoke thus, '`For the testimony of Jesus,
and for testifying against deceivers, and the deceived, I am brought here to suffer.`'
This took so much with the people, that it wrought a tenderness in many.
But to quench this, priest Allen said to the spectators, '`People,
I would not have you think it strange to see a man so willing to die;
for that`'s no new thing.
And you may read how the apostle said, that some should be given up to strong delusions,
and even dare to die for it.`'
But he did not say where the apostle speaks so,
neither have I found it any where in the holy writ; though I know that Paul says, Romans 5:7.
"`Peradventure for a good man some would even dare to die.`"
But it seems it was sufficient for Allen, if he could but render Leddra odious:
who however continued cheerful:
for as the executioner was putting the halter about his neck, he was heard to say,
'`I commit my righteous cause unto you, O God.`'
The executioner then being charged to make haste, W. Leddra,
at the turning of the ladder, cried,
'`Lord Jesus receive my spirit;`' and so he was turned off, and finished his days.
The hangman cut down the dead body,
and lest it should be so barbarously used as those
of William Robinson and Marmaduke Stevenson,
(which none holding when cut down,
fell to the ground to the breaking of W. Robinson`'s skull,) Edward Wharton,
John Chamberlain, and others, caught the body in their arms and laid it on the ground,
till the hangman had stripped it of its clothes; who having done so, said,
that he was a comely man, as indeed he was.
The body being stripped, William`'s friends took it, laid it in a coffin, and buried it.
For further confirmation of what has been related,
the following letter of one of the spectators, that was there accidentally, may be added:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Boston, March 26, 1661.

On the 14th of this instant, there was one William Leddra, who was put to death.
The people of the town told me, he might go away if he would;
but when I made further inquiry, I heard the marshal say, that he was chained in prison,
from the time he was condemned, to the day of his execution.
I am not of his opinion: but yet truly I thought the Lord did mightily appear in the man.
I went to one of the magistrates of Cambridge,
who had been of the jury that condemned him, as he told me himself,
and I asked him by what rule he did it?
He answered me that he was a rogue, a very rogue.
But what is this to the question, I said, where is your rule?
He said, he had abused authority.
Then I goes after the man, and asked him,
whether he did not look on it as a breach of rule to slight and undervalue authority?
And I said that Paul gave Festus the title of honor, though he was a heathen.
(I do not say that these magistrates are heathens).
Then, when the man was on the ladder, he looked on me, and called me friend, and said,
know that this day I am willing to offer up my life for the witness of Jesus.
Then I desired leave of the officers to speak, and said, Gentlemen,
I am a stranger both to your persons and country, and yet a friend to both:
and I cried aloud, for the Lord`'s sake, take not away the man`'s life;
but remember Gamaliel`'s council to the Jews.
If this be of man it will come to nought, but if it be of God, you cannot overthrow it:
but be careful you be not found fighters against God.
And the captain said, why had you not come to the prison?
The reason was, because I heard the man might go if he would;
and therefore I called him down from the tree, and said, come down, William,
you may go away if you will.
Then captain Oliver said, it was no such matter; and asked, what I had to do with it?
And besides, bade me be gone: and I told them, I was willing;
for I cannot endure to see this, I said.
And when I was in the town,
some did seem to sympathize with me in my grief But I told them,
that they had no warrant from the word of God, nor precedent from our country,
nor power from his majesty to hang the man.
I rest,

[.signed-section-closing]
Your Friend,

[.signed-section-signature]
Thomas Wilkie.

[.signed-section-context-close]
To Mr. George Lad, master of the "`America`" of Dartmouth, now at Barbados.

--

William Leddra being thus dispatched,
it was resolved to make an end also of Wenlock Christison.
He therefore was brought from the prison to the court at Boston, where the governor,
John Endicot, and the deputy-governor, Richard Bellingham, being both present,
it was told him, '`Unless you renounce your religion, you shall surely die.`'
But instead of shrinking, he said with an undaunted courage, '`No,
I shall not change my religion, nor seek to save my life;
neither do I intend to deny my master; but if I loose my life for Christ`'s sake,
and the preaching of the gospel, I shall save my life.`'
This noble resolution gave such a check to his persecutors,
that they did not then go on with the trial, but sent him away to prison again.
And it being said by somebody, that William Leddra was dead,
a certain person said to Wenlock, '`O your turn is next.`'
To which he gravely replied,
'`The will of the Lord be done,`' showing thereby his entire resignation.

Being now locked up again in prison, he was kept there till about the Fourth month:
but then the court being set, a spirit of confusion appeared there,
and a division among several of the members;
for though the greatest part were for taking the same course
with him as with those that were already put to death,
yet several would not consent to it.
And as natural occurrences sometimes cause reflections among observing people,
so it happened here; for during their deliberations how to deal with Wenlock Christison,
which lasted for the space of two weeks, the sun in the firmament shone not,
a thing at that season somewhat extraordinary;
which gave occasion for some to say that the sun abhorring this bloody business,
hid itself from them.
But after many debates, the sanguinary council at length agreed,
and Wenlock was brought to the bar, where the governor, John Endicot, asked him,
what he had to say for himself, why he should not die?
He answered, '`I have done nothing worthy of death; if I have I refuse not to die.`'
To this another said, '`You are come in among us in rebellion,
which is as the sin of witchcraft, and ought to be punished.`'
Hence it appears how perversely these blood-thirsty persecutors
applied the Holy Scriptures to their cruel ends,
and so made a wrong use of the prophet Samuel`'s words to Saul;
to which false conclusion Wenlock answered, '`I came not in among you in rebellion,
but in obedience to the God of heaven, not in contempt to any of you,
but in love to your souls and bodies; and that you shall know one day,
when you and all men must give an account of the deeds done in the body.
Take heed, (thus he went on,) for you cannot escape the righteous judgments of God.`'
Then said major-general Adderton, '`You pronounce woes and judgments,
and those that are gone before you pronounced woes and judgments;
but the judgments of the Lord God are not come upon us as yet.`'
So insolent and hard-hearted may man become,
as not to hesitate even to defy the Most High.
But before we draw the curtains of this stage,
we shall see the tragical end of this Adderton,
who now received this answer from Wenlock: '`Be not proud,
neither let your spirits be lifted up:
God does but wail till the measure of your iniquity be filled up,
and that you have run your ungodly race;
then will the wrath of God come upon you to the uttermost.
And as for your part, it hangs over your head, and is near to be poured down upon you,
and shall come as a thief in the night suddenly, when you think not of it.`'

Then Wenlock asked, '`By what law will you put me to death?`'
The answer was, '`We have a law, and by our law you are to die.`'
'`So said the Jews of Christ, (replied Wenlock,) We have a law,
and by our law he ought to die.
Who empowered you to make that law?`'
To which one of the board answered, we have a patent, and are the patentees;
judge whether we have not power to make laws.`'
Hereupon Wenlock asked again,
'`How! have you power to make laws repugnant to the laws of England?`'
'`No,`' said the governor.
'`Then, (replied Wenlock,) you are gone beyond your bounds,
and have forfeited your patent; and that is more than you can answer.
Are you, (asked he,) subjects to the king, yes, or no?`'
'`What good will that do you,`' replied the secretary?
'`If you are, (answered Wenlock,) say so; for in your petition to the king,
you desire that he would protect you,
and that you may be worthy to kneel among his loyal subjects.`'
To which one said, '`Yes, we are so.`'
'`Well, (said Wenlock,) so am I, and for any thing I know, am as good as you,
if not better; for if the king did but know your hearts as God knows them,
he would see that you are as rotten towards him, as they are towards God.
Therefore seeing that you and I are subjects to the king,
I demand to be tried by the laws of my own nation.`'
It was answered,
'`You shall be tried by a bench and a jury:`' for it seems they began
to be afraid to go on in the former course of trial without a jury,
this being contrary to the laws of England.
But Wenlock said, '`That is not the law, but the manner of it;
for I never heard nor read of any law that was in England to hang Quakers.`'
To this the governor replied, that there was a law to hang Jesuits.
To which Wenlock returned.
'`If you put me to death, it is not because I go under the name of a Jesuit,
but of a Quaker: therefore I appeal to the laws of my own nation.`'
But instead of taking notice of this, one said, that he was in their hands,
and had broken their law, and they would try him.
Wenlock still appealed to the law of his own nation: yet the jury being called over,
went out, but quickly returned, and brought him in guilty.
Whereupon the secretary said, '`Wenlock Christison, hold up your hand.`'
'`I will not,`' said Wenlock, '`I am here and can hear you.`'
Then the secretary cried, '`Guilty or not guilty?`'
'`I deny all guilt,`' replied Wenlock, '`for my conscience is clear in the sight of God.`'
But the governor said, '`The jury has condemned you.`'
Wenlock answered, '`The Lord does justify me; who are you that condemns?`'

They then voted as to the sentence of death, but were in a manner confounded,
for several could not vote him guilty of death.
The governor seeing this division, said,
'`I could find in my heart to go home:`' being in such a rage,
that he flung something furiously on the table;
which made Wenlock cry,`' It were better for you to be at home than here,
for you are about a bloody piece of work.`'
Then the governor put the court to vote again; but this was done confusedly,
which so incensed the governor, that he stood up and said, '`You that will not consent,
record it: I thank God I am not afraid to give judgment.`'
Thus we see that to be drunk with blood, does not quench the thirst after blood;
for Endicot the governor, seeing others backward to vote,
precipitately pronounced judgment himself, and said, '`Wenlock Christison,
hearken to your sentence: You must return to the place from which you came,
and from there to the place of execution,
and there you must be hanged until you are dead, dead, dead.`'
To which Wenlock said, '`The will of the Lord be done, in whose will I came among you,
and in whose counsel I stand, feeling his eternal power,
that will uphold me unto the last gasp.`'
Moreover he cried thus: '`Known be it unto you all,
that if you have power to take my life from me,
my soul shall enter into everlasting rest and peace with God,
where you yourselves shall never come.
And if you have power to take my life from me, the which I do question,
I do believe you shall never more take Quakers`' lives from them: note my words:
do not think to weary out the living God, by taking away the lives of his servants.
What do you gain by it`'? for the last man that you have put to death,
here are five come in his room.
And if you have power to take my life from me,
God can raise up the same principle of life in ten of his servants,
and send them among you in my room, that you may have torment upon torment,
which is your portion; for there is no peace to the wicked, says my God.`'
The holy confidence with which he uttered these words show,
and the sequel made it appear plainly, that something supernatural was contained in them:
and it is remarkable, that among the imprisoned Quakers,
there were then several that had been banished on pain of death;
and among these also Elizabeth Hooton;
and Edward Wharton stayed in his habitation contrary to his sentence of banishment.

Wenlock having received sentence of death, was brought to prison again,
where having been detained five days,
the marshal and a constable came to him with an order from the
court for his enlargement with twenty-seven more of his friends,
then in prison for their testimony to the Truth,
saying they were ordered by the court to make him acquainted with their new law.
'`What means this?`'
said Wenlock, '`Have you a new law?
'`Yes,`' said they.
'`Then you have deceived most people,`' said Wenlock.
'`Why?`'
said they.
'`Because,`' said he, '`they did think the gallows had been your last weapon.
Your magistrates said that your law was a good and wholesome law made for your peace,
and the safeguard of your country.
What, are your hands now become weak?
The power of God is over you all.`'

Thus the prison doors were opened, and Wenlock, with twenty-seven more of his friends,
as aforesaid, set at liberty, save that two of them, namely,
Peter Pearson and Judith Brown, being stripped to the waist,
and fastened to a cart`'s tail,
were whipped through the town of Boston with twenty stripes apiece.

Now though not long after an order came from the king, as will be said anon,
whereby these persecutors were charged to desist from putting the Quakers to death,
yet is seems they had got some scent of the king`'s displeasure,
who had a mind to stop their bloody career:
for having got a book written by George Bishop,
containing a relation of the cruel persecution in New England,
and reading a passage concerning major-general Denison, who,
to put off those that complained of their wicked proceeding, said,
'`This year you will go to complain to the parliament,
and the next year they will send to see how it is;
and the third year the government is changed.`'
He took much notice of this, and calling to the lords to hear it, said, '`Lo,
these are my good subjects of New England: but I will put a stop to them.`'

It was not long before an opportunity was offered;
for the news of William Leddra`'s death being come into England,
with an information of the danger that others were in of going the same way,
their friends took it so to heart, especially Edward Burrough,
that having got audience of the king,
he said to him there was a vein of innocent blood opened in his dominions,
which if it were not stopped would overrun all.
To which the king replied, '`But I will stop that vein.`'
Then Burrough desired him to do it speedily; '`for we know not,`' said he,
'`how many may soon be put to death.`'
The king answered, '`As soon as you will.
Call, said he to some present, the secretary, and I will do it presently.`'
The secretary being come, a mandamus was forthwith granted.
A day or two after, going again to the king, to desire dispatch of the matter,
the king said he had no occasion at present to send a ship there;
but if they would send one, they might do it as soon as they could.
E+++.+++ Burrough then asked the king if it would please
him to grant his deputation to one called a Quaker,
to carry the mandamus to New England.
The king answered, '`Yes, to whom you will.`'
Whereupon E. Burrough named one Samuel Shattock, who being an inhabitant of New England,
was banished on pain of death, if ever he returned there.
And the king accordingly granted the deputation to him,
with full power to carry the mandamus, which was as follows:

[.embedded-content-document.legal]
--

[.letter-heading]
Charles R.

Trusty and well-beloved, we greet you well.
Having been informed that several of our subjects among you, called Quakers, have been,
and are imprisoned by you, whereof some have been executed, and others,
(as has been represented unto us,) are in danger to undergo the like:
we have thought fit to signify our pleasure in that behalf for the future;
and do hereby require, that if there be any of those people called Quakers among you,
now already condemned to suffer death, or other corporal punishment,
or that are imprisoned, and obnoxious to the like condemnation,
you are to forbear to proceed any further therein;
but that you forthwith send the said persons,
(whether condemned or imprisoned,) over into this our kingdom of England,
together with the respective crimes or offenses laid to their charge;
to the end that such course may be taken with them here,
as shall be agreeable to our laws, and their demerits.
And for so doing, these our letters shall be your sufficient warrant and discharge.

Given at our court at Whitehall, the 9th day of September, 1661,
in the 13th year of our reign.

[.signed-section-closing]
By his majesty`'s command,

[.signed-section-signature]
William Morris.

--

[.offset]
The superscription was:

[.embedded-content-document.legal]
--

To our trusty and well-beloved John Endicot, Esq.
and to all and every other the governor, or governors of our plantations of New-England,
and of all the colonies thereunto belonging; that now are, or hereafter shall be:
and to all and every the ministers and officers of
our said plantations and colonies whatsoever,
within the continent of New England.

--

Thus favorable the king manifested himself;
and in England persecution for religion was a little at a stand;
but it was but a kind of respite.
G+++.+++ Fox the younger, a man of excellent qualifications, and great boldness,
foresaw an imminent storm; and lest any carelessness might enter among his friends,
in the Fourth month he wrote the following exhortation to them:

[.embedded-content-document.epistle]
--

What my heavenly Father has determined for these men to do, no man can stop it:
O that patience might be abode in by all that know his name,
and his will submitted unto by them that he has called.
O be still, strive not, but drink the cup which our Father allows to be given;
I know it will be bitter to some;
but whosoever strives against it shall come to loss and shame:
for the Lord will yet further try his people,
till it be fully and clearly manifest who are the approved in his sight.
This he will certainly do;
therefore let not the present calm beget a wrong security in any, for lo the day hastens,
and comes swiftly, that another storm must arise;
and in vain will it be to fly to the tall cedars and strong oaks for shelter;
for nothing but the name of the Lord can preserve in that day.

[.signed-section-signature]
George Fox, the younger:

--

That this G. Fox did not reckon amiss,
when in this exhortation he said the day hastens that another storm must arise,
we shall see before long: but first we must take a view of things in America.

This mandamus to the rulers of New England being obtained, as has been said,
quick dispatch was thought necessary to send it there.
And Samuel Shattock being empowered by the king to carry it,
an agreement was made with one Ralph Goldsmith, who was master of a good ship,
and also one of those called Quakers, for three hundred pounds,
(goods or no goods,) to sail in ten days.
He then immediately made all things ready to set sail,
and with a prosperous gale arrived in about six weeks
time before the town of Boston in New England,
upon a First-day of the week.
The townsmen seeing a ship come into the bay with English colors, soon came on board,
and asked for the captain.
Ralph Goldsmith told them he was the commander.
Then they asked him whether he had any letters; and he said '`Yes.`'
Whereupon they asked if he would deliver them; but he said, '`No, not today.`'
So they went ashore, and reported there was a ship full of Quakers,
and that Samuel Shattock was among them,
who they knew was by their law liable to be put to death,
for coming in again after banishment: but they knew not his errand nor authority.

All being thus kept close,
and none of the ship`'s company allowed to go on shore that day,
next morning Samuel Shattock, the king`'s deputy, and Ralph Goldsmith,
the commander of the vessel, went on shore;
and sending the men that landed them back to the ship,
they two went through the town to the governor John Endicot`'s door, and knocked.
He sending a man to know their business,
they sent him word their business was from the king of England,
and that they would deliver their message to none but the governor himself.
Thereupon they were admitted to go in, and the governor came to them,
and commanded Shattock`'s hat to be taken off,
and having received the deputation and the mandamus, he laid off his hat;
and ordering Shattock`'s hat to be given him again, he looked upon the papers,
and then going out, went to the deputy-governor,
and bid the king`'s deputy and the master of the ship to follow him.
Being come to the deputy-governor, and having consulted with him about the matter,
he returned to the two aforesaid persons and said, '`We shall obey his majesty`'s command.`'
After this, the master of the ship gave liberty to the passengers to come ashore,
which they did, and met together with their friends of the town,
to offer up praises to God for this wonderful deliverance.

Now for as much as several of their friends were yet in prison at Boston,
the following order was given forth by the council not long after.

[.embedded-content-document.legal]
--

[.letter-heading]
To William Salter, keeper of the prison at Boston.

You are required by authority, and order of the general court,
forthwith to release and discharge the Quakers, who at present are in custody.
See that you do not neglect this.

[.signed-section-closing]
By order of the court,

[.signed-section-signature]
Edward Rawson, Secretary.

[.signed-section-context-close]
Boston, 9th Dec. 1661.

--

They then consulted what to do that they might not incur the king`'s displeasure;
and it was agreed to send a deputation to him.
First,
colonel Temple was sent to acquaint the king with their having set the Quakers at liberty;
and he was followed not long after by the chief priest John Norton,
and Simon Broadstreet, one of the magistrates.

The year was now spent: but before I conclude it I must take notice,
as a pregnant instance of the marvelous vicissitude of mundane affairs,
that in the forepart of this year, the body of O. Cromwell,
which had been buried with great state in Westminster Abbey, was dug up,
as were also the bodies of Bradshaw and Ireton,
which three corpses were carried in carts to Tyburn, and there hanged on the gallows.
Then the executioner chopped off the heads, stamped with his foot on the bodies,
which were tumbled into a pit, dug near the gallows;
and the heads were exposed on the top of Westminster Hall,
where I remember to have seen them.
And that now befell Cromwell which he said about
seven years before in his speech to the parliament,
as has been mentioned in its due place,
viz. That he would rather be rolled into the grave, and buried with infamy,
than give his consent to the throwing away one of the fundamentals of that government,
namely, liberty of conscience.
And yet he allowed persecution to go on, as has been related at large: but now,
according to his saying, he was roiled with infamy into the grave;
which may serve indeed for a remarkable instance
of the justice and equal judgments of God.

About this time a book came out at London, bearing the title of [.book-title]#Semper Idem,# i. e.
[.book-title]#Always the Same,# or [.book-title]#A Parallel of Fanatics.#
The author concealed his name;
but he made it appear sufficiently that he was a Roman Catholic, and it may be a Jesuit:
for he inveighed not only against the Quakers and Baptists,
but also against the Presbyterians, and even Episcopalians,
and consequently against all Protestants.
No, the martyrs that were burnt in the bloody reign of queen Mary,
eldest daughter to king Henry the Eighth, were no less vilified than the Quakers,
in the said book, by the scornful name of rebels, and fanatics.
This book was sold publicly, and it seemed that none dared oppose it,
for fear of displeasing the court.
But E. Burrough, who was of an undaunted courage, and so continued till his death,
employed his pen to refute it, and gave forth his answer in print,
plainly showing what the anonymous author aimed at,
viz. That he would have the cruel usage of fire and faggots revived,
and wished to see the burning of reputed heretics brought again into vogue.
Which was the more to be taken notice of,
because such a publication of vilifying the martyrs with calumnies,
had not been seen at London for above a hundred years;
and all the groundless positions of the said author were
very notably answered by the said E. Burrough.

And since persecution in the latter end of this year
began to appear with open face again,
he published a book, which he called [.book-title]#Antichrist`'s Government Justly Detected#.
This he dedicated to all the rulers, etc. in the (so called) Christian world;
and therein, with sound arguments,
manifested the unlawfulness and injustice of persecution, and from which it had its rise;
and how dangerous it was to impose religion.

Next he treated at large concerning heresy,
and what punishment pertained to such as are truly convicted of it.
But lest any might think that he was for opposing
the duty of the civil magistrate against malefactors,
he said concerning the punishment of heresy,
(which he stated to be only an ecclesiastical censure,) that he only intended this,
where the error of a man and his heresy in his mind and judgment,
did only extend to the hurt of his own soul, and against God,
and not to the harm of his neighbor`'s person or estate.
But, thus continued he,
if his error and heresy do extend further than only against God and his own soul,
even to outward wrongs, or evils, or violence, or visible mischiefs committed,
as murders, or other the like crimes against men, to the injuring of others,
then I forbid not outward external punishment,
to be corporally inflicted upon the person and estate of such a man;
but it ought to be done, and that by the laws of men, provided for the same end;
even such a man`'s error, in such his wrong dealing,
may justly and lawfully be punished with death, banishment or penalties,
according to the desert of the crime, etc.
The author also wrote circumstantially concerning the government of antichrist,
and showed the deceit that was in it, and who were the subjects of his kingdom.

It was somewhat before this time that George Fox the younger, being a prisoner,
and seeing an intent of promoting popery, wrote the following letter to the king:

[.embedded-content-document.letter]
--

The King of kings has beheld, yes,
the King of kings has seen even all your actings in the dark,
and he has traced your walkings in obscure places;
and you have not hid your counsels from the almighty,
but he has seen all the intents of your heart,
and your good words have not at all deceived him,
nor those that purely stood in his counsels; for he has seen the snares,
and beheld the pits which privily have been preparing for the innocent,
(even in the time when smooth words have been given,) and he has showed them unto others.
Oh that you would have taken counsel of the Lord,
and obeyed the same! you should have been prospered;
but you have taken counsel of them which have caused you to err:
you have also sought to exalt and establish yourself, and your own honor,
and not the truth and honor of God only; which if you had truly done,
(in the self-denial,) God would have honored you:
you have not taken the Lord for your strength and stay,
but you have leaned to that which cannot help you,
even to that which will prove a broken reed unto you, if you come to prove its strength.
You have greatly dishonored and grieved the Lord,
by your setting up ministers which he loathes,
and by your providing a forced maintenance for them by an unjust law,
that so they may yet make a prey upon his people,
who for conscience-sake cannot put into their mouths,
being spiritually gathered therefrom by the word of the Lord.
You have also grieved the Spirit of the Lord,
in that you have not put a difference between that which the Spirit of the Lord moved,
and that which is moved by the evil lusts of men;
and hereby you have justified that which God has condemned,
and condemned that which he has justified, and will justify in the sight of his enemies.
O, friend, it is not the person of any man which the Lord regards,
but it is righteousness which he has respect to, and so far as man,
(whatever he may be,) by the drawing of the Truth comes into righteousness,
and acts therein, so far has the Lord unity with him, and no further:
these things should have been considered by you.
You have also grieved the Holy Ghost by the allowing
all these wicked and profane shows and sports,
which have abounded since your coming in,
by which the Lord`'s good creatures have been abused, wasted, and devoured.
You have highly displeased the Lord God,
by your allowing persecution to be acted in your name,
even while you in words have promised liberty; yes,
many are this day in holes and prisons, for the testimony of a good conscience,
and obeying the doctrine of Christ.
Oh! the Lord is grieved with the pride and wickedness that is lived in,
both in your family and dominions,
and you yourself have not been such a pattern and
example among them as you ought to have been.
O, friend! when I behold the wickedness, cruelty, and oppression,
that abounds in this nation in open view,
and also the secret abominations which are committed,
and are plotting and lurking in the chambers;
verily my life is even bowed down because of the fierce wrath of the Almighty,
which I see is kindled;
and because of the great destruction which I see attends the wicked,
whose ends and counsels the Lord will frustrate,
and upon whom he will pour out everlasting contempt.
Yes, and it has been often in me, before you came last into the land, and also since,
even when it has been shown me, what idolatry is intended in secret to be brought in,
that certainly it had been better for you that you had never come,
for I have seen it tending to your destruction.
And when I have seen the abomination and cruelties which are committed and intended,
there has a pity arose in me towards you for your soul`'s sake; and it has been my desire,
if it might stand with the will of God,
that he would put it into your heart to go out of the land again,
that so your life might be preserved, and that you might have time to repent;
for although many men flatter and applaud you for self ends,
yet I see the Lord is displeased with your ways.
Let no man deceive you by feigned words; God will not be mocked: such as you sows,
such must you reap.
You can not hide yourself from the Lord,
nor deliver yourself from the stroke of his hand:
O consider how soon has the Lord taken away your brother, who,
according to outward appearance, might have lived longer than you!
O, think not that men can preserve you, though all the nations about promise to help you!
Yet when the Lord appears against you, you must fall;
verily there is a great desolation near, your hand cannot stay it;
God has decreed that he may exalt his own kingdom: the nations are like a boiling pot,
a little flame will set them on Are;
and the windy doctrine of the priests shall help to kindle it;
oh the day will be terrible, who may abide it!
The stubble will be consumed, and the chaff shall be burned; the ungodly shall be abased,
for they cannot stand in judgment; but the seed shall be exalted.
O what shall I say that might be for your safety?
Verily I can say little; the Lord`'s decree must stand, the Lord is highly displeased,
and his wrath is near to be revealed: and he is swift in his goings,
and he will shorten the days of his enemies for his elect`'s sake.
O that your soul might be saved in the day of the
Lord! my spirit is in suffering for you,
my soul is afflicted within me because of the approaching of the day of your calamity,
from which no man can deliver you.
This is the Truth that must stand, and in love to your soul it is declared,
by him who must deal uprightly with all men: though for it I suffer outwardly,
yet I have a witness in your conscience, unto which I am made manifest;
and peace with the Lord is my portion, which is better than an earthly crown.

[.signed-section-signature]
George Fox, the younger.

[.signed-section-context-close]
This was given him the 9th day of the Eighth month, 1660.

--

This letter,
(a clear evidence of the author`'s innocent courage,) was delivered to the king,
who read it, and seemed to be reached thereby, and touched at heart: but his brother,
the duke of York, was displeased with it, and being violently set against the author,
advised the king to use severity towards him; but the king being good-natured, said,
'`It were better for us to mend our lives.`'

While the said G. Fox was prisoner in Lambeth-house, he wrote also a small treatise,
called, '`England`'s sad Estate and Condition lamented.`'
Herein he reproved the grievous abominations committed among the inhabitants,
oppression by persecution, and the hypocrisy of the priests.
He also predicted the pestilence, as may be mentioned hereafter in due place;
and signified not obscurely,
that endeavors would be used publicly to introduce superstition and idolatry;
but that those who intended to do so, should be frustrated by the Lord in their attempts.
And that others, whose worship also did displease the Lord,
should grind and waste one another: but that beyond their expectation,
he would pluck out from them, and preserve a holy seed.
And that after he should have executed his vengeance
upon the rebellious and treacherous dealers,
he would then bring forth the remnant of his holy seed,
which should be preserved from their fury; and then they should spread over all,
and stand in dominion.
'`But,`' thus continued he, '`although these things, touching the holy remnant,
shall certainly be fulfilled in their season, yet before they will be fully accomplished,
great will be the trials of many of the righteous,
and there will be great judgments executed in you, O land, by him,
who ofttimes makes a fruitful land barren,
because of the wickedness of them that dwell therein.`'
This, and much more he wrote, and published it in print.
Several of his predictions we have seen fulfilled,
as in the progress of this history may appear: and this last we must refer to time.
After the writing of this treatise, he also gave forth the following prayer.

[.embedded-content-document.prayer]
--

Surely it was you, O Lord, that gave bounds unto the sea,
that the floods thereof could not overwhelm your chosen: you can let forth the winds,
and suffer a storm; and you can make a calm when you pleases.
Have you the glory of all, you King of saints, you Savior of Israel.
You can do whatever you pleases, therefore will we trust in your name,
neither will we fear what men can do unto us, because you will not forsake us;
but you will plead our cause in the sight of our adversaries,
and they shall know that you are our God, who are able to save to the uttermost O Lord,
our righteousness, we will praise your name; for your mercies endure forever.
Our eyes, O God, are unto you, for we have no other helper.
Our faith, O Lord, stands in you, who can not forget your people.
You have revealed and brought up Jacob, who wrestles with you, and prevails as a prince,
therefore must the blessing come.
O Lord, the birth, the birth, cries unto you, your own elect,
which long has been oppressed.
You can not deny yourself, therefore have we faith, and hope, which makes not ashamed.
O Lord, how unsearchable are your ways!
You have even amazed your people with the depth of your wisdom;
you alone will have the glory of their deliverance;
and therefore have you suffered these things to come to pass.
O Lord, you are righteous in all your judgments:
only preserve your people which you have gathered, and will gather unto yourself,
in the day of trial,; that so they may sing of your power,
and magnify your name in the land of the living.

--

This G. Fox wrote also in prison several other papers and epistles,
for exhortation and consolation of his friends: but his work was soon done,
so that not long after he departed this life, which was in this, or the next year.
He was, as may be seen from his writings, a man of extraordinary resignation and courage;
and that he gave up his life, if required, may appear from a small book that he wrote,
being prisoner in Lambeth-house, which he called,
[.book-title]#The Dread of God`'s Power Uttering Its Voice Through Man, Unto the Heads of the Nation.#
Herein he exhorted the rulers very earnestly to do justice; and said among the rest,
'`Friends, I must deal plainly with you in the sight of God,
who has made me a prophet to the nation.
I may not flatter any of you.
My life is in the hand of my Maker,
and not one hair of my head can fall to the ground without his providence.
He has redeemed my soul from hell, and my mind from the earth;
and he has given me his good Spirit to lead me.
I am henceforth no more my own, but I am the Lord`'s, who has formed me to his praise,
and has brought me forth, that I may sound forth his powerful Truth among the people.
Therefore must I not fear man, neither must I be afraid of the sons of men.`'

Thus undaunted he showed himself: but it was not long before he made his exit,
of which I cannot but say something.
In his sickness I find, that though he was weak in body, yet he was strong in spirit,
so that he would sing for joy of heart.
He exhorted his friends to keep in unity, foreseeing, it may be,
that something would rise which might give occasion for division:
and then with much fervency of spirit, he prayed God, and exhorted his friends,
to keep their garments unspotted of the world,
because great was the day of trial that was at hand.
Afterwards recommending them to the Lord, he took his leave of them,
and slept in perfect peace with the Lord, being of sound memory to the last.
Now the dust was returned to the earth, and the spirit unto God who gave it.
Thus he was freed of all danger of losing the crown of immortal life,
which man by temptation, and the casualties of this life, is liable unto,
if he continues not diligently watchful.
But this valiant was now beyond the reach of all temptations, and so I leave him,
that I may pass on to other matters.

In this year E. Burrough wrote a paper to the king and his council, which he called,
'`A just and Righteous Plea,`' in which he proposed at large,
the reasons why the people called Quakers, refused to take the oath of allegiance,
namely: That it was not because they would not be faithful to the king,
but only for conscience-sake, since Christ so expressly had commanded his followers,
"`Swear not at all,`" which command they dared not transgress.
Yet to assure the government of their faithfulness, he said thus:

[.embedded-content-document.paper]
--

We are now, and shall be faithful, innocent, and peaceable,
in our several stations and conditions,
under this present government of king Charles the Second,
whom we acknowledge supreme magistrate and governor over this kingdom;
and for conscience-sake we are obedient and submissive to him, as such,
in all his commands, either by doing and performing of what he justly requires,
or by patient suffering under whatsoever is inflicted upon us,
in the matters for which we cannot be obedient for conscience-sake,
when any thing is required of us different from the just law of God.
And to this subjection to the king and his government,
we are bound by the law of righteousness;
and such has ever been our principle and practice, and is unto this day,
even to be quiet, and peaceable, and patient, under every authority that is set over us;
and not in unrighteousness, to plot, or contrive, or rebel, against any government,
or governors,
nor to seek our own deliverance from injustice and oppression in such a way.
And we are persuaded to seek the preservation of the king`'s person and authority,
by all just and lawful means, and not to rebel against him with carnal weapons;
and so far as his government is in justice, mercy, and righteousness,
we declare true and faithful subjection and obedience thereunto;
and wherein it is otherwise,
we shall be subject by patient suffering what is unequally imposed upon us,
and yet not rebel in any turbulent way of conspiracies and insurrections:
for our principles are not for war, but for peace with all men so much as in us lies;
neither may we render evil for evil to any,
but are to be subject to the king and his government, actively or passively,
upon the conditions aforementioned.

And we renounce all foreign authority, power, and jurisdiction of the Pope, or any else,
from having any supremacy whatsoever over the king, or any the good subjects of England.
And this we declare, acknowledge, and testify, in the fear and presence of God,
(to whom we and all mankind must give an account,) and that without secret equivocation,
or any deceitful mental reservation.

--

Thus fully E. Burrough declared himself,
and gave also a circumstantial relation of the practice of his friends meeting together,
or their way of public worship,
thereby to assure the government of their peaceable behavior and fidelity.
But all this proved in vain; for it being well known that the Quakers denied swearing,
they continually were vexed and persecuted,
under a pretense of not giving due satisfaction of their being faithful to the government,
and so transgressing the laws.

Now the deputies of New England came to London,
and endeavored to clear themselves as much as possible, but especially priest Norton,
who bowed no less reverently before the archbishop, than before the king;
and thus fawning upon the Episcopalians,
they found means to keep in a condition to vex the Quakers, so called,
though they were forbidden to put them to death:
and that many of the bishops were great enemies to the said Quakers,
appeared plainly from the cruel persecution which after a short calm arose in England.

But to return to the New England deputies,
they would eagerly have altogether excused themselves:
and priest Norton thought it sufficient to say,
that he did not assist in the bloody trial, nor had advised to it: but John Copeland,
whose ear was cut off at Boston, charged the contrary upon him: and G. Fox, the elder,
got occasion to speak with them in the presence of some of his friends;
and asked Simon Broadstreet, one of the New England magistrates,
whether he had not a hand in putting to death, those they nick-named Quakers?
He not being able to deny this, confessed he had.
Then G. Fox asked him and his associates that were present,
whether they would acknowledge themselves to be subjects to the laws of England;
and if they did, by what laws they put his friends to death?
They answered, they were subjects to the laws of England;
and they had put his friends to death by the same law,
as the Jesuits were put to death in England.
Hereupon G. Fox asked, whether they did believe that those his friends,
whom they had put to death, were Jesuits, or jesuitically affected?
They said, '`No.`' Then replied G. Fox, '`You have murdered them;
for since you put them to death by the law that Jesuits are put to death here in England,
it plainly appears, you have put them to death arbitrarily, without any law.`'
Thus Broadstreet finding himself and his company ensnared by their own words, asked,
'`Are you come to catch us?`'
But he told them, they had caught themselves,
and they might justly be questioned for their lives;
and if the father of "`William Robinson,
(one of those that were put to death,) were in town,
it was probable he would question them, and bring their lives into jeopardy:
for he not being of the Quakers`' persuasion,
would perhaps not have so much regard to the point of forbearance, as they had.
Broadstreet seeing himself thus in danger, began to flinch and to skulk;
for some of the old royalists were earnest with the
Quakers to prosecute the New England persecutors.
But G. Fox and his friends said, they left them to the Lord, to whom vengeance belonged,
and he would repay it.
Broadstreet however, not thinking it safe to stay in England, left the city,
and with his companions went back again to New England.

Not long before this time, G. Fox, with the help of John Stubbs and Benjamin Furly,
published a book called, [.book-title]#A Battledoor.#
In this book were set forth examples of about thirty languages,
to show that every language had its particular denomination
for the singular and the plural number,
in speaking to persons; and in every place where the description began,
the shape of a battledoor was delineated.
This work was promoted to public view by G. Fox, to show the learned,
(if possible to convince them,) that the custom of those called Quakers,
to say Thou to a single person, though it were to the king, and not You,
was not irregular nor absurd, but had been used anciently;
and that therefore they could not justly be charged with unmannerliness,
because they followed not the common custom, which was crept in by the pride of men.
Now though Ger.
Croese does disapprove in G. Fox,
that he put his name to this book as well as J. Stubbs and Benjamin Furly,
yet I do not think it so improper as the said author does;
for G. Fox was a great promoter of that work; and though he was not skilled in languages,
and some were for calling him an idiot, or a fool,
yet I know him to have been a man of good understanding, and of deep judgment.
In his journal he freely acknowledges,
that John Stubbs and Benjamin Furly took great pains in the compiling of the said book,
which he put them upon, and added also some things to it;
so that in some respect he might be esteemed author too.
At the end of the book he added:

[.embedded-content-document]
--

The Pope set up _you_ to one in his pride,
and it is pride which cannot bear _thee_ and _thou_ to one, but would have _you,_
from the author of and their father in their pride, which must not have the word__ thou,__
which was before their father the Pope was, which was God`'s language,
and will stand when the Pope is ended.

[.signed-section-signature]
G+++.+++ Fox

--

This book,
(in which J. Stubbs and B. Furly gave also directions for learners to read the Hebrew,
Oriental, and other languages,) was liberally disposed of;
some of them were presented to the king and his council, to the archbishop of Canterbury,
and to the bishop of London, and also one to each university.
The king confessed that the distinction between plural and singular,
in regard of persons, was the proper language of all nations;
and the archbishop being asked what he thought of it, was so at a stand,
that he could not tell what to say to it; for it appears he would not commend it,
neither could he resolve to disapprove it.
Yet it did so inform and convince people,
that many afterward were not near so much offended
at saying _thee_ and _thou_ to a single person,
as they were before.

Now many Roman Catholics and Jesuits began to fawn upon those called Quakers,
and said publicly, that of all the sects the Quakers were the best,
and most self-denying people;
and that it was great pity that they did not return to the holy mother church:
and though they might have been in hopes thereby
to have gained proselytes from the Quakers,
yet they were disappointed.
In the meanwhile they did but ill service to the Quakers thereby;
for this gave occasion to their enemies to divulge,
that there was an affinity and collusion between the Quakers and the Roman Catholics.
Some Jesuits signifying that they would willingly discourse with the Quakers,
G+++.+++ Fox consented to it, and in order thereunto, time and place were appointed:
whereupon two of the loyalists came, being dressed like courtiers,
and they asked the names of G. Fox and those with him.
G+++.+++ Fox then asked them the same question he had once before, as has been said already,
asked a Jesuit, that is,
whether the church of Rome was not degenerated from the church in the primitive times;
from the spirit, and power, and practice, that they were in, in the apostles`' time.
The Jesuit to whom the question was put, said he would not answer it.
G+++.+++ Fox asked him, why?
but he would give no reason.
His companion then said they were not degenerated from the church in the primitive times.
Then G. Fox asked the other, whether he was of the same mind; and he said, '`Yes.`'
G+++.+++ Fox, to give no room to any excuses of a mistake, repeated his question thus:
Whether the church of Rome now was in the same purity, practice, power, and spirit,
that the church in the apostles`' time was in.
The Jesuits seeing how exact G. Fox would be with them,
said it was presumption in any to say, they had the same power and spirit,
which the apostles had.
But G. Fox, told them,
it was presumption in them to meddle with the words of Christ and his apostles,
and make people believe they succeeded the apostles, and yet be forced to confess,
they were not in the same power and spirit, that the apostles were in.
'`This,`' said he, '`is a spirit of presumption, and rebuked by the apostles`' spirit.`'
Thereupon he showed them how different their fruits and practices were,
from the fruits and practices of the apostles.
This so displeased the Jesuits, that one of them said, '`You are a company of dreamers.`'
'`No,`' said G. Fox, '`you are the dreamers, who dream you are the apostles successors,
and yet confess, you have not the same power and spirit, which the apostles were in.`'
Then he began to tell them also, how they were led by an evil spirit;
and that this spirit had induced them to pray by beads, and to images,
and to put people to death for religion.
He spoke yet more; but the Jesuits soon grew weary of this discourse, and went away,
giving charge afterwards to those of their persuasion, not to dispute with the Quakers,
nor to read any of their books.

Sometime after G. Fox went to Colchester, where he had very large meetings.
From there he went to Coggeshall;
not far from which there was a priest convinced of the truth
of the doctrine held forth by him and his friends;
and he had a meeting in his house.
And after having visited his friends in their meetings thereabouts,
he returned to London, where he found more work: for John Perrot,
of whom mention has been made already that he was at Rome,
had so far complied with his vain imaginations,
that he thought himself further enlightened than G. Fox, and his friends;
and from this presumption he would not approve, that when any one prayed in the meeting,
others should put off their hats, calling this a formality,
and a common custom of the world, which ought to be departed from.
And since novelties often draw people after them, so it was in this case,
insomuch that he got a pretty many adherents.
But he did not stand here; for as one error proceeds from another,
so he made another extravagant step, and let his beard grow;
in which he was followed by some.
In the meanwhile G. Fox labored both by word and writing, to stop his progress:
and though most of his friends also bore testimony against it,
yet there passed several years before this strange, fire was altogether extinguished:
to the quenching whereof, it contributed not a little that Perrot,
who now walked in an erroneous path, grew worse from time to time, even to that degree,
that being come into America, he fell into manifest sensualities, and works of the flesh:
for he not only wore gaudy apparel, but also a sword;
and being got into some place in the government, he became a severe exactor of oaths,
whereas before he had professed that for conscience-sake he could not swear.
Before I leave Perrot, I will insert here a letter wrote by him from Rome,
when he was released from prison:
and though I believe he was then in a better state than afterward,
yet in that letter some sparks of spiritual pride maybe seen,
which though then under some limitation, yet in process of time so broke forth,
that it caused his fall.
The letter was thus:

[.embedded-content-document.letter]
--

O Israel: the host of the most high God;
his majesty has fulfilled to me the vision of my head,
having showed himself to be the Holy One, and Just:
he has lately delivered me from the prison of the city of Rome,
besides the two lambs with me, whose faces, through God, are turned to you:
for which I beseech you in the holy spirit of meekness,
to bless the name of the Lord God.
Give thanks to him for his power.
The God of life promote you all in the virtue of his mercy and forgiveness,
and keep you in the power of his everlasting love, unto the end.

[.signed-section-signature]
John.

[.signed-section-context-close]
Written to you all without the gates of Rome, the 2nd day of the Fourth month,
1661 Send this forward and read my life in your meetings.

--

He added not his surname, in imitation, as it seems, of the apostle John.
He omitted it likewise in another letter he wrote from the prison at Rome,
which began thus:

[.embedded-content-document.letter]
--

I John the prisoner, being in the sense of the spirit of life with you all, etc.

--

Who were the two lambs he mentions in his letter, I cannot tell;
whether they were persons that had been imprisoned with him in the inquisition jail,
and converted by him, as he thought; or whether he meant John Stubbs and Samuel Fisher,
I know not; it may rather be supposed that he meant Charles Bayley and Jane Stoakes,
who went to Rome to procure his liberty:
but J. Stubbs and S. Fisher came away long before; yet if I am not mistaken,
it was about this time that these were at Rome, and they perhaps,
having endeavored to obtain his liberty, departed before him towards England.

When Perrot afterward lived in America, about the beginning of the year 1665,
John Taylor wrote thus from Jamaica concerning him:

[.embedded-content-document.letter]
--

One of the judges of this place told me,
that he never had seen one who so severely exacted
an oath from people as John Perrot did;
for he says, that if they will go to hell, he will dispatch them quickly.
And another judge that was also present, said,
that Perrot had altogether renounced his faith, and aimed at nothing but his profit.

--

Such a one was John Perrot, though even some wise men admired him for a time;
but he became a man of a rough behavior.
Whether he ever repented sincerely, I cannot tell.
Robert Rich, who took too much part in the extravagancies of James Nayler,
as has been related, did also combine with Perrot, and became estranged from the Quakers,
and in that condition he died: but he was of the number of those,
of whom the apostle John said, "`They went out from us, but they were not of us.`"

Now since persecution continued in England, Edward Burrough,
who continually was laborious with the pen to oppose this evil, wrote also a small book,
which he called,
[.book-title]#The Case of Free Liberty of Conscience in the Exercise of Faith and Religion,
Presented Unto the King and Both Houses of Parliament#.
In this treatise he showed,
that to deprive honest and peaceable people of liberty
of conscience in the exercise of worship to God,
was unjust, an intrenching on God`'s sovereignty, and a usurpation of his authority.
He also recommended it to consideration, that to impose by force a religion upon men,
was the way to fill the land with hypocrites.
And he showed with sound reasons,
that to persecute people for the exercise of religion and their worshipping of God,
must unavoidably tend to destroy trading, husbandry, and merchandise.
To which he added, that such as were called heretics were punished, as malefactors,
whereas drunkards and other vicious persons were left unpunished;
which to inculcate with more strength, he made use of the words of Dr. Taylor,
a bishop in '`Ireland, who said thus:
'`Why are we so zealous against those we call heretics,
and yet great friends with drunkards, and swearers, and fornicators,
and intemperate and idle persons?
I am certain a drunkard is as contrary to the laws of Christianity as a heretic:
and I am also sure that I know what drunkenness is;
but I am not so sure that such an opinion is heresy,`' etc.

It happened about this time in England that some covetous persons,
to engross inheritances to themselves,
would call the marriages of those called Quakers in question.
And it was in this year that such a cause was tried at the court session at Nottingham.
A certain man dying, and leaving his wife with child, and an estate in copyhold lands:
when the woman was delivered, one that was near of kin to her deceased husband,
endeavored to prove the child illegitimate:
and the plaintiff`'s counsel willing to blacken the Quakers, so called,
asserted the child to be illegitimate,
because the marriage of its parents was not according to law; and said bluntly,
and very indecently, that the Quakers went together like brute beasts.
After the counsel on both sides had pleaded, the judge whose name was Archer,
opened the case to the jury, and told them, that there was a marriage in Paradise,
when Adam took Eve, and Eve took Adam;
and that it was the consent of the parties that made a marriage.
And as for the Quakers, said he, he did not know their opinion;
but he did not believe they went together as brute beasts, as had been said of them,
but as Christians; and therefore he did believe the marriage was lawful,
and the child lawful heir.
And the better to satisfy the jury,
he related to them this case:`' A man that was weak of body, and kept his bed,
had a desire in that condition to marry,
and did declare before witnesses that he did take such a woman to be his wife;
and the woman declared, that she took that man to be her husband.
This marriage was afterwards called in question:
but all the bishops did at that time conclude it to be a lawful marriage.`'
The jury having received this instruction, gave in their verdict for the child,
and declared it legitimate.

It has been mentioned before, that G. Fox being prisoner at Derby, in the year 1650,
was exceedingly vexed and ill treated by the keeper of the prison.
But this man being struck with the terrors of the Lord, became such a notable convert,
that in the year 1662, he wrote the following letter to G. Fox:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

Having such a convenient messenger,
I could do no less than give you an account of my present condition,
remembering that to the first awakening of me to a sense of life,
and of the inward principle, God was pleased to make use of you as an instrument;
so that sometimes I am taken with admiration,
that it should come by such means as it did; that is say,
that Providence should order you to be my prisoner,
to give me my first real sight of the Truth.
It makes me many times to think of the jailer`'s conversion by the apostles.
Notwithstanding my outward losses are since that time such,
that I am become nothing in the world, yet I hope I shall find,
that all these light afflictions, which are but for a moment,
will work for me a far more exceeding and eternal weight of glory.
They have taken all from me; and now instead of keeping a prison,
I am rather waiting when I shall become a prisoner myself Pray for me,
that my faith fail not, but that I may hold out to the death,
that I may receive a crown of life.
I earnestly desire to hear from you, and of your condition,
which would very much rejoice me.
Not having else at present, but my kind love unto you,
and all Christian friends with you, in haste I rest,

[.signed-section-closing]
Yours in Christ Jesus,

[.signed-section-signature]
Thomas Sharman.

[.signed-section-context-close]
Derby, the 22nd of the Fourth month, 1662.

--

I have heretofore made some mention of the imprisonment of Catharine Evans,
and Sarah Cheevers, by the inquisition at Malta.
It was about this time that they were released: for G. Fox and Gilbert Latey,
having understood that the lord d`'Aubigny could procure their liberty, went to him,
and having informed him concerning their imprisonment,
desired him to write to those in authority at Malta for their release.
This he promised to do, and told them if they would come again within a month,
perhaps they might hear of their discharge.
They went again to him about that time,
but he said he thought his letters had miscarried; yet he promised he would write again,
and so he did; which had such effect,
that the said two women were discharged of their long imprisonment.
G+++.+++ Fox had now opportunity to reason with this lord,
(who was a Roman Catholic priest in orders,) about religion,
and he brought him to confess that Christ had enlightened
every man that comes into the world with his spiritual light;
and that he had tasted death for every man; and that the grace of God,
which brings salvation, has appeared to all men; and that it would teach them,
and bring their salvation if they did obey it.
Then G. Fox asked him what the Romanists would do with all their relics and images,
if they did acknowledge and believe in this light, and receive the grace to teach them,
and bring their salvation?
And he answered, those things were but policies to keep people in subjection.

But leaving these discourses,
I will now give a clear and circumstantial relation of the
imprisonment of the aforementioned Catharine Evans,
and Sarah Cheevers, chiefly collected from letters and papers, written by them in prison,
and sent from there to England, where they were published in print,
not long after their return, in the year 1662.

In the year 1658, these women having drawings in their mind to travel towards Alexandria,
went in a ship from England to Leghorn in Italy,
and having been thirty-one days between Plymouth and Leghorn,
they at length safely landed at that city:
where they found some of their countrymen and friends, and stayed there several days,
dispersing many books when occasion offered.
They spoke also with people of various degrees, without being molested by any.
From there they got passage in a Dutch ship bound for Alexandria, or Scanderoon;
but the master of the ship being in company with another ship going to Malta,
went also there, though he had no business in the place: but before they came there,
Catharine fell into such an anguish of mind, that she cried out,
'`Oh! we have a dreadful cup to drink at that place!`' Being come into the harbour,
and standing on the deck of the ship, and looking upon the people who stood on the walls,
she said in her heart, '`Shall you destroy us?
If we give up to the Lord, then he is sufficient to deliver us out of your hands:
but if we disobey our God, all these could not deliver us out of his hand.`'
And so all fear of man was taken from them.

The next day, being the First-day of the week, they went on shore,
where the English consul met them, and asked them what they came there for;
they answered what they thought convenient, and gave him some books.
Then he told them there was an inquisition; and kindly inviting them to his house,
said all that he had was at their service while they were there.
They accepting of this invitation, went there, and many came to see them,
whom they called to repentance, so that several became tender.
About night they went on ship-board, and the next day came again into the city,
and going to the governor he told them he had a sister in the nunnery,
who desired to see them.
Thereupon they went to the nunnery, and talked with the nuns, and gave them books:
and one of their priests, who brought them into the chapel,
would have them bow to the high altar, but they refused,
being grieved because of the idolatry committed there, and went to the consul`'s again,
where they stayed some weeks.
During that time they once went into one of the places of worship in the time of worship;
and Catharine standing in the midst of the people, turned her back to the high altar,
and kneeling down, she lifted up her voice in prayer to the Lord.
The priest that officiated, put off his surplice, and kneeled near her till she had done.
Then he reached forth his hand to them to come to him, and offered her a token,
which she taking to be the mark of the beast, refused.
Thereupon he put the piece into Sarah`'s hand, but she gave it him again,
and showed him her purse that she had to give, if any had need,
and as yet was in no need.
He then asked if they were Calvinists or Lutherans`'? And they answered,
'`No.`' He asked if they would go to Rome to the Pope.
They denying this, he asked if they were Catholics;
to which they said they were true Christians, servants of the living God.
But since they had yet learned but little of the language spoken there,
they expressed themselves very defectively;
what they did was partly in words and partly by signs, as well as they could:
and many that came about them were amazed: however at last they departed peaceably.
Some time after they went again to a mass-house, where the sacrament, as they call it,
was administered: there were many lights, and great costliness and fineries;
and being grieved because of their idolatry, they stood about three quarters of an hour,
weeping and trembling, especially Catharine:
and this so struck the congregation with amazement,
that some removed further from them for fear.
At length they both went out, but yet under such a trembling,
that they went along the street reeling and staggering,
so that they became a wonder to all that saw them.

They were about three months at the house of the English consul; and he, for that reason,
being under a suspicion, did not what he might have done to save them;
but in some respect he delivered them up to the inquisition,
though by his oath he was obliged to protect the English there.
In the meanwhile he kept them in his house, and permitted them not to go abroad,
though the governor had told him he might let them go about their business;
'`For,`' said he, '`they are honest women.`'
The consul might also have let them go free,
before they came under the power of the black rod.
Now they perceiving that something to their prejudice was in agitation,
and making account already that a prison would be their lot,
they signified that they suspected him,
and told him that Pilate would do the Jews a service,
and yet wash his hands in innocency.
He being at a loss, required a sign of them, if they were the messengers of God.
And they gave him to understand, that this might serve for a sign:
that it would be well with them; but that it should not go off well with him.

Afterwards it happened that they were sent for by the inquisition:
and that day the consul`'s wife brought them some food; but as she passed by,
Catharine was smitten, as with an arrow, to the heart, and she seemed to hear a voice,
saying, '`She has obtained her purpose.`'
Then Catharine would not taste of the food, but went aside, and wept exceedingly.
The consul having called her, told her, the inquisition had sent for them,
having received letters from Rome, but that he did hope they should be set free;
which however was not true, for he knew,
(as they understood afterwards,) there was a room
prepared for them in the prison of the inquisition.
Neither was it long before there came the chancellor, the consul,
and one with the black rod, who brought them before the lord inquisitor;
and he asked them whether they had changed their minds;
for it seems that had been required of them before.
But they answered, '`No,`' and that they should not change from the Truth.
Then he asked what new light it was they talked of; they answered it was no new light,
but the same the prophets and apostles bore testimony to.
Next he asked how this light came to be lost since the primitive times; they replied,
it was not lost; men had it still in them, but they did not know it,
by reason that the night of apostasy had overspread the nations.
Then he said, if they would change their minds, and do as they would have them,
they should say so, or else they would use them as they pleased.
But they, signifying that they would not change, said, '`The will of the Lord be done.`'
He then arose, and went away with the consul, leaving them there:
and the man with the black rod, and the keeper,
took and put them into an inner room in the inquisition,
which had only two little holes in it for light and air.
This place was so exceeding hot, that it seemed as if their intent was to stifle them,
as we may see in the sequel.

Not long after they were brought before the inquisitors to be further examined,
and they not only asked their names, but also the names of their husbands and parents,
and what children they had, and also why they came there?
To which they answered, they were servants of the living God,
come there to call them to repentance.
The next day they were called again, but then examined asunder;
and Sarah being asked whether she was a true Catholic, said,
that she was a true Christian, worshipping God in Spirit and in Truth.
Then they held forth a crucifix to her,
and would have her swear that she should speak the truth.
To which she said, she should speak the truth, but she would not swear;
for Christ had commanded, "`Swear not at all.`"
The English consul who was present, endeavored to persuade her to swear,
and said that none should do her any harm.
She having some books with her, they were taken from her; and they asked her,
wherefore she brought those books; to which she answered,
because they could not speak their language.
Then they asked her, what George Fox was?
She answered, '`A minister.`'
Further they asked, wherefore she came there?
And she replied, to do the will of God as she was moved of the Lord.
The next question was, how the Lord did appear unto her: to which she answered,
'`By his Spirit.`'
And being asked whether she did see his presence, and hear his voice, her answer was,
she heard his voice, and saw his presence.
They then asked what he said to her?
She answered, that he required of her to go over the seas to do his will.
This made them ask how she knew it was the Lord who required this of her?
To which she answered, that since he had signified to her,
that his living presence should go along with her, she found him to perform his promise,
for she did feel his living presence.
After this they went away.

Two days after the inquisitors came and called for Catharine,
and offering her the crucifix, they told her, the magistrates commanded her to swear,
that she should speak the truth.
To which she said, that she should speak the truth, for she was a witness for God;
but she should not swear, since a greater than the magistrates said, "`Swear not at all;
but let your yes, be yes, and your no, no; for whatsoever is more, comes of evil.`"
Then said they, '`You must obey the justice; and he commands you to swear.`'
She returned, '`I shall obey justice, but if I should swear, I should do an unjust thing;
for the just, (Christ,) said,
"`Swear not at all.`"`' Then they asked her whether
she did acknowledge the Christ that died at Jerusalem?
She answered, '`We acknowledge the same Christ and no other; he is the same yesterday,
today, and forever.`'
Next they asked her, what she would do at Jerusalem: she answered,
she did not know that she should go there; but she intended to have gone to Alexandria.
They asked what to do: her answer was, '`The will of God: and,
(said she,) if the Lord opened my mouth, I should call people to repentance,
and declare to them the day of the Lord, and direct their minds from darkness to light.`'
They asked her also, whether she did see the Lord: she answered, God was a spirit,
and he was spiritually discerned.

Now, though from the answers of these women little could be got to blame them,
yet they were kept close prisoners, which seemed to grieve the English consul,
for he came to them with tears in his eyes, and said he was sorry as for his own flesh;
for it seems he had received something for delivering them up,
which he would willingly have given back,
if thereby he could have obtained their liberty: but a slavish fear possessed him,
and he never had peace while he lived.
Some days after this came a magistrate, two friars, the man with the black rod, a scribe,
and the keeper of the inquisition to examine them; and they were again required to swear:
but they answered as before, that Christ said,
"`Swear not at all;`" and that the apostle James gave the same charge.
Hereupon the magistrate asked if they would speak truth: and they said, '`Yes.`'
He then asked whether they believed the creed; to which they said,
they did believe in God, and in Jesus Christ, who was born of the Virgin Mary,
and suffered at Jerusalem under Pontius Pilate,
and arose again from the dead the third day, and ascended to his Father,
and shall come to judgment, to judge both quick and dead.
He further asked, how they did believe the resurrection: and they answered,
that they believed that the just and the unjust should arise according to the Scriptures.
Next he said, '`Do you believe in the saints, and pray to them?
'`To which the answer was,`' We believe the communion of saints,
but we do not pray to them, but to God only, in the name of Jesus.`'
His next question was, whether they did believe in the Catholic church:
and they answered, they did believe the true church of Christ, '`but the word Catholic,
said they, we have not read in Scripture.`'
He also asked if they believed in purgatory: to which they said, '`No;
but a heaven and a hell.`'
Then one of the friars, who was an Englishman, said,
we were commanded to pray for the dead; for, those that are in heaven have no need;
and for those that are in hell, there is no redemption;
therefore there must be a purgatory: and he asked if they believed the holy sacrament;
to which their answer was, they never read the word sacrament in Scripture.
The friar replied, '`Where you read in your bibles sanctification,
it is sacrament in ours.`'
And he said, their holy sacrament was bread and wine,
which they converted into the flesh and blood of Christ, by the virtue of Christ.
'`Then,`' said the women, '`you work miracles,
for Christ`'s virtue is the same as it was when he turned water into wine,
at the marriage in Cana.`'
The friar said, '`If we do not eat the flesh, and drink the blood of the Son of God,
we have no life in us.`'
They replied, '`The flesh and blood of Christ is spiritual, and we do feed upon it daily;
for that which is begotten of God in us, can no more live without spiritual food,
than our temporal bodies can without temporal food.`'
Then he said, '`You never hear mass.`'
'`But we,`' said they, '`hear the voice of Christ; he only has the words of eternal life;
and that is sufficient for us.`'
He said, '`You are heretics and heathens;`' to which they replied,
'`They are heretics that live in sin and wickedness,
and such are heathens that know not God.`'

Then it was asked them who was the head of their church: they told him, '`Christ.`'
It was further asked what George Fox was: and they said, '`He is a minister of Christ.`'
And it being asked whether he sent them, their answer was, '`No:
the Lord did move us to come.`'
Then the friar said, '`You are deceived, and have not the faith;
though you had all virtues.`'
And they replied, '`Faith is the ground from which virtues proceed.`'
Hereupon it was told them,
if they would take the holy sacrament they might have their liberty;
or else the Pope would not leave them for millions of gold;
but they should lose their souls and bodies too.
To this they said, '`The Lord has provided for our souls,
and our bodies are freely given up to serve him.`'
Then it was asked them if they did not believe marriage was a sacrament:
and they answered, it was an ordinance of God.
It was further asked if they did believe men could forgive sins: and their answer was,
that none could forgive sins but God only.
After some other words to and fro, the women asked, '`Wherein have we wronged you,
that we should be kept prisoners all the days of our life?
Our innocent blood will be required at your hands.`'
The friar said he would take their blood upon him.
They replied, the time would come he should find he had enough upon him without it.
Then it was told them the Pope was Christ`'s vicar,
and what he did was for the good of their souls.
To which they answered, '`The Lord has not committed the charge of our souls to the Pope,
nor to you neither; for he has taken them into his own possession:
glory be to his name forever.`'
Then it was said unto them they must be obedient.
And they returned, they were obedient to the government of Christ`'s Spirit or light.
The friar said, '`None have the true light but the Catholics;
the light that you have is the spirit of the devil.`'
'`Woe, (said they,) to him that curses Jesus;
can the devil give power over sin and iniquity?
That would destroy his own kingdom.`'
'`You,`' replied the friar, '`are laughed at and mocked of everyone.`'
'`But,`' said they, '`what will become of the mockers`'?`' '`It was no matter,`' he said:
'`you run about to preach, and have not the true faith.`'
They returned, '`The true faith is held in a pure conscience,
void of offence towards God and men.
Everyone has the true faith, that believes in God, and in Jesus Christ whom he has sent:
but they that say they do believe, and do not keep his commandments, are liars,
and the truth is not in them.`'
The friar confessed this to be true,
though he was continually very troublesome to them with threats, to make them turn;
and to this end they were locked up in a room, so exceeding hot,
that it was said it was impossible they could live long in it.
They were also so exceedingly stung by gnats, when they lay in bed,
that their faces became swollen, as if they had been sick of the small-pox,
so that many began to be afraid of them; and the friar said to Sarah,
he spied an evil spirit in her face.

At another time being examined, they were asked,
how many of their friends were gone forth into the ministry, and into what parts:
they answering to that query what they knew, it was told them,
all that came where the Pope had any thing to do, should never go back again.
But they said, the Lord was as sufficient for them,
as he was for the children in the fiery furnace, and their trust was in God.
Catharine being sickly, was asked why she looked so; whether her spirit was weak:
she answered, '`No: my body is weak, because I eat no meat.`'
The friar hearing this, offered her a license to eat flesh; for it was in their Lent.
But she refused this, and said, she could not eat any thing at all.
And going afterwards to bed, she lay there night and day for twelve days together,
fasting and sweating, for she was in much affliction, and great was her agony.

After having lain ten days, there came to her two friars, the chancellor,
the man with the black rod, a physician, and the keeper.
One of the friars commanded Sarah to go out of the room,
and then pulled Catharine`'s hand out of the bed, and said, '`Is the devil so great in you,
that you cannot speak?`'
To which she said, '`Depart from me you worker of iniquity:
the power of the Lord is upon me, and do you call him devil?`'
Hereupon he took his crucifix to strike her on the mouth;
and she asked him whether it were that cross that crucified Paul to the world,
and the world unto him.
This ignorant monk said it was.
But she denied it, and said, '`The Lord has made me a witness for himself,
against all workers of iniquity.`'
He then bade her be obedient, and went to strike her; at which she said,
'`Will you strike me?`'
And he saying he would, she further said, '`You are out of the apostles`' doctrine,
for they were no strikers.
I deny you to be any of them who went in the name of the Lord.`'
To which he said, he had brought her a physician in charity: and she returned,
'`The Lord is my physician, and my saving health.`'
The monk growing angry, said she should be whipped and quartered,
and burnt that night at Malta, and her mate too.
But she told him modestly, she did not fear; the Lord was on her side;
and he had no power but what he had received;
and if he did not use it to the same end the Lord gave it him, the Lord would judge him.
At these words they were all struck dumb, and went away.`'
Then the friar went to Sarah, and told her that Catharine called him worker of iniquity.
'`Did she,`' said Sarah, '`are you without sin?
'`To which he said he was.
'`Then,`' replied Sarah, '`she has wronged you.`'

Late in the evening, something was proclaimed at the prison gate, by beating of a drum,
and early in the morning some came again with a drum, and guns.
It seems to me that this was done on purpose to frighten these poor women,
and to make them believe that they should be put to death;
for indeed they looked for little else,
having for several weeks expected that they should be led to the stake:
but they were fully resigned, and given up to what the Lord might be pleased to permit.
In the meanwhile Catharine continuing sickly, the friar came again with the physician.
But she told him, she could not take any thing, unless she felt freedom.
He then said, they must never come forth of that room while they lived:
and pretending to be kind to them, he further said, '`You may thank God and me,
that it is no worse; for it was like to be worse.`'
Thereupon they said, that if they had died,
they had died as innocent as ever any servants of the Lord.
He then said, it was well they were innocent; and turning to Sarah,
bade her take notice what torment Catharine should be in at the hour of death; saying,
thousands of devils would fetch her soul to hell.
But Sarah told him, she did not fear any such thing.
He then asked Catharine if she did not think it expedient
for the elders of the church to pray over the sick.
And she said, '`Yes, such as are moved of the Spirit of the Lord.`'
He then fell down on his knees, and did howl, and wish bitter wishes upon himself,
if he had not the true faith.
The physician in the meanwhile was enraged, because she did not bow to him.

Now while Catharine was sick, Sarah was not without great affliction:
for it grieved her to see her dear companion so ill; and she easily foresaw,
that if Catharine died, her own sufferings would be heavier.
But yet she was given up to the will of the Lord,
and would not in the least grudge at Catharine`'s eternal rest.
But in time Catharine began to mend, and grow hungry; and eating, she was refreshed.
But the room wherein they were locked was so excessively hot,
that they were often made to rise out of their bed,
and lie down at the chink of the door for air to fetch breath;
and this heat was the greater, because it came not only from without, but within also:
which so affected them that their skin was parched, the hair fell off their heads,
and they fainted often; and their afflictions were so great,
that when it was day they wished for night, and when it was night, they wished for day;
yes, through human weakness, they desired death, eating their bread weeping,
and mingling their drink with tears.
Once Catharine asked the monks, who came to her with a physician,
and said it was in charity, whether they did not keep them in that hot room to kill them,
and bring a physician, to keep them longer alive?
To this the friar said,
the inquisitor would lose his head if he should take them from there;
and it was better to keep them there, than to kill them.
Then they wrote to the inquisitor, and laid their innocency before him; and said also,
if it were their blood they thirsted after, they might take it any other way,
as well as to smother them in that hot room.
But this so incensed him, that he sent the friar to them, who took away their ink-horns,
their bibles, being taken from them before.
They asked them, why their goods were taken away: to which it was answered, '`All is ours;
and your lives too, if we will.`'
Then they asked, how they had forfeited their lives: to which it was told them,
'`For bringing books and papers.`'
they replied, if there were any thing in them that was not true,
they might write against it.
To this the monk said, they scorned to write to fools and asses,
that did not know true Latin.
And it was further told them, the inquisitor would have them separated,
because Catharine was weak, and she should go into a cooler room;
but Sarah should abide there.
Then Catharine took Sarah by the arm, and said, '`The Lord has joined us together,
and woe be to them that part us.
I had rather die here with my friend, than part from her.`'
This so struck the friar, that he went away, and came no more in five weeks,
and the door of their room was not opened in all that time.

Then the monks came again to part them, but Catharine was sick,
and broken out from head to foot.
They thereupon sent for a doctor, and he said, they must have air, or else they must die.
This was told the inquisitor, and he ordered the door to be set open six hours in a day.
But ten weeks after they were parted; which was such a grievous affliction,
that they declared death itself would not have been so hard to them.
But the monks said they corrupted each other, and that being parted,
they would bow and submit.
But they saw themselves disappointed; for the women were stronger afterwards than before,
the Lord fitting them for every condition.
Before they were parted, the friars brought them a scourge of small hempen cords,
asking them if they would have it;
and saying they were used to whip themselves till the blood came.
But the women said, that could not reach the devil, he sat upon the heart.
Then the monks said, '`All the people of Malta are for you; if you will be Catholics,
none but will like you.`'
To which they returned, '`The Lord has changed us into that which changes not.`'
The monks then said, '`All our holy women do pray for you:
and you shall be honored of all the world, if you will turn.`'
They replied, '`The world lies in wickedness;
and the honor and glory of the world we have denied.`'
To this the monks said, '`You shall be honored of God too; but now you are hated of all.`'
'`This,`' said one of the women, '`is an evident token whose servants we are.
The servant is not greater than his Lord.`'

Once, on a First-day of the week, the friars came,
and commanded them to kneel down with them to prayer.
They signified they could pray but as they were moved by the Lord.
Then the friars commanded them the second time, and kneeled down by their bedside,
and prayed after their manner; which being done, they said to the women,
'`We have tried your spirits;
now we know what spirit you are of But they told them they could not know that,
unless their minds were turned to the light of Christ in their consciences.
The English friar then growing angry, showed them his crucifix, and bade them look on it.
But they told him, the Lord says,
"`You shall not make to yourself the likeness of any thing that is in heaven above,
or in the earth beneath, or in the water under the earth; you shall not bow down to them,
nor worship them; but I the Lord your God am a jealous God.`"
The friar seeing Sarah speak so boldly to him, called for the irons to chain her.
She then bowed her head, and said to him, '`Not only my hands and feet,
but my neck also for the testimony of Jesus.`'
The friar seeming appeased, said he would do them any good he could;
for he saw what they did was not in malice.
And the friars came often, and said to them,
'`If you would do but a little you should be set at liberty;
but you will do nothing at all, but are against everything.`'
To which they returned, that they would do any thing that might tend to God`'s glory.

While they were imprisoned here,
it happened that the inquisition house was new built or repaired,
which took up about the space of a year and a half; and during this time,
some of the great ones came often to see the building,
which gave opportunity to these women to speak to them,
and to declare the Truth in the name of the Lord.

Now, though they were threatened by the monks for preaching the light of Christ so boldly,
yet not only the magistrates, but the lord inquisitor grew moderate towards them,
and gave order they should have pens, ink, and paper, to write to England.
And they seemed inclined to have them set at liberty;
but the friars worked mightily against it;
and had labored about three quarters of a year to part them,
before they could bring it to pass.
And when at length they had effected it,
they told Catharine that they should never see one another`'s faces again.

In the meanwhile Catharine being sickly, had little stomach to eat,
and had no mind to eat any thing but what came from Sarah to her.
And having told one of the friars that she needed somebody to wash her linen,
and to prepare some warm food for her,
he sent to Sarah to know if she would do it for her; and she said she would.
And by that means they for some weeks heard of one another every day;
and the friar said once to Catharine, '`You may free yourself of misery when you will;
you may make yourself a Catholic,
and have your freedom to go where you will:`' to which she told him,
'`Thus I might have a name that I did live when I was dead:
you have Catholics enough already endeavor to bring
some of them to the light in their consciences,
that they may stand in awe and sin not.`'
But he w`'as so eager,
that he said he would loose one of his fingers if she and Sarah would be Catholics.
Then she told him that it was Babylon that was built with blood,
but Zion was redeemed through judgment.

Many ways were used to draw them off;
and once they would have persuaded her to set a picture at her bed`'s head,
for a representation: but she said, as with abhorrence, '`What,
do you think I need a calf to worship?
Do you walk by the rule of Scriptures?
'`To which the friar said, '`We do, but we have traditions too.`'
She replied,
'`If your traditions derogate or dissent from the fundamentals of Christ`'s doctrine,
the prophets, and apostles, I deny them in the name of the Lord.`'
But he asserted that they did not.
Then she asked what rule they had to burn those that could not join with them for conscience-sake:
and he returned, '`St. Paul did worse, for he gave them to the devil:`' and further said,
that they did judge all damned that were not of their faith.
Then she objected to him several of the superstitious rites of the church of Rome,
and mentioned also the forbidding of marriage, which, said she is a doctrine of devils,
according to the saying of the apostle.
The friar being put to a nonplus, told her that St. Peter was the Pope of Rome,
and did build an altar there, and the Pope was his successor,
and he could do what he would.
But she refuted this with sound reason.
He then boasting of the antiquity of their church,
she signified that the church she was of was yet older; '`For,`' said she,
'`our faith was from the beginning; and Abel was of our church.`'
The friar being at a loss, and no longer able to hold out against Catharine,
went to Sarah, and talked with her at the same rate;
and she also told him Abel was of our church: to which he said,
'`Abel was a Catholic;`' and quite overshooting himself, he said likewise,
'`And Cain and Judas were so.`'
To which Sarah returned, '`Then the devil was a Catholic; and I will not be one:
I will not turn; though you would tear me to pieces,
I believe the Lord would enable me to endure it.`'

At another time the said friar, whose name was Malachy, came again to Catharine,
and told her if she would be a Catholic, she should say so;
otherwise they would use her badly, and she should never see the face of Sarah again,
but should die by herself, and a thousand devils should carry her soul to hell.
She then asked him if he were the messenger of God to her: and he said '`Yes.`'
'`Why, what is my sin,`' said she, '`or wherein have I provoked the Lord,
that he does send me such a message?
'`It is,`' returned the monk, '`because you will not be a Catholic`'

Whereupon she said, '`I deny you and the message too, and the spirit which speaks in you;
for the Lord never spoke so.`'
He growing angry, said that he would lay her in a whole pile of chains,
where she should see neither sun nor moon.
She intimating how resigned she was,
said he could not separate her from the love of God in Christ Jesus,
lay her wherever he would.
And he further saying he would give her to the devil, she resumed,
'`I do not fear all the devils in hell; the Lord is my keeper.
Though you had the inquisition, with all the countries round about it on your side,
and I was alone by myself, I do not fear them; if they were thousands more,
the Lord is on my right hand; and the worst they can do, is but to kill the body,
they can touch my life no more than the devil could Job`'s.`'
Then the monk said she should never go out of the room alive.
To which she courageously said, '`The Lord is sufficient to deliver me;
but whether he will or no, I will not forsake the living fountain,
to drink at a broken cistern.
And you have no law to keep us here, but such a law as Ahab had for Naboth`'s vineyard.`'
The monk then cursing himself, and calling upon his gods, ran away;
and as he was pulling the door, he said, '`Abide there, member of the devil.`'
To which she said, '`The devil`'s members do the devil`'s works;
and the woes and plagues of the Lord will be upon them for it.`'

He then went and told the inquisitor of it, who laughed at him; and before he came again,
Catharine was moved out of that room:
when he came he brought one of the inquisitor`'s men with him, and two very good hens,
and said, the lord inquisitor had sent them in love to her.
To which she said, she received his love,
but yet she showed herself not very ready to accept them;
and signified that she was willing to pay for them,
being unwilling to be chargeable to any, while she had of her own.
The friar, who it seems would have had them lay down their money at his feet,
said they must not count any thing their own,
for in the primitive times they sold their possessions,
and laid them down at the apostles`' feet.
He further said, '`You shall not lack any thing, though we should spend a thousand crowns.
But you are proud,
because you will not take the inquisitor`'s hens which he sent you in charity.`'
She then asking what kind of charity this was, since he kept her in prison;
the friar said, it was for the good of their souls he kept them in prison;
further adding, '`If you had not been going to preach,
you might have gone where you would.`'
She returned, '`Our souls are out of the inquisitor`'s reach.
Why should your love extend more to us than to your own family:
for they commit all manner of sin, which you cannot charge us with.
Why do not you put them into the inquisition, and bid them turn?
He then said, '`You have not the true faith;`' and showing her his crucifix, asked her,
if she thought he did worship that: and she asked him, what then did he with it:
to which he answered, it was a representation.
And she replied, it did not represent Christ,
for he was the express image of his Father`'s glory, which is light and life.
'`But,`'continued she,`' if you can put any life in any of your images,
then bring them to me.
What representation had Daniel in the lion`'s den, or Jonah in the whale`'s belly?
They cried unto the Lord, and he delivered them.`'
The friar, who could not abide to hear her speak so much against idols,
said she talked like a mad woman, adding, '`I will give you to the devil.`'
She not fearing this, said, '`Give your own, I am the Lord`'s.`' He then stood up, and said,
'`I will do to you as the apostles did to Ananias and Sapphira.`'
She then standing up also, said, '`I deny you in the name of the Lord, the living God,
you have no power over me.`'
Then away he went with the hens to Sarah, and told her that Catharine was sick,
and the lord inquisitor had sent two hens, and she would be glad to eat a piece of one,
if she would dress one of them presently, and the other tomorrow.
Sarah no less circumspect and cautious than Catharine,
and unwilling to receive this gift before she knew what might be expedient,
answered him accordingly as Catharine did.
Then carried the hens away again, saying, '`You would eagerly be burnt,
because you would make the world believe,
you love God so well as to suffer in that kind.`'
Catharine hearing this, said, '`I do not desire to be burnt;
but if the Lord should call me to it,
I believe he will give me power to undergo it for his Truth;
and if every hair of my head was a body,
I could offer them up all for the testimony of Jesus.`'

The friar coming afterwards,
again asked Catharine whether she had not been inspired of the Holy Ghost to be a Catholic,
since she came into the inquisition: she said, '`No:`' but he maintaining the contrary,
said, '`You are those who call the Spirit of the Holy Ghost the Spirit of the devil.`'
No:`' replied they,
(who though they were parted could hear one another,)`' the
Spirit of the Holy Ghost in us will resist the devil;
and the inspiration of the Holy Ghost is not wrought in the will of man,
nor in man`'s time; but in God`'s will and time.`'
More discourse they had about this matter, and then asking for their bibles,
which had been taken from them, he said they should never see them again,
for they were false.

Thus they were often troubled and importuned by the friars,
who generally came two at a time, though sometimes but one.
One of these often lifted up his hand to strike them, but did not:
for they not being moved by fear, he was put out of countenance,
and would say they were good women, and he would do them any good.
As indeed sometimes he did work for them, and would say it was for God`'s sake,
and that they ought to thank him for it; to which they replied,
those that did anything for God, did not look for a reward from man;
which once made him so angry, that he said they were the worst of all creatures,
and that they should be used worse than the Turks, Armenians, and Lutherans.
Whereupon one of them said, '`The pure life was ever counted the worst; and if we suffer,
we are the Lord`'s, and can trust him.
Do what you will with us, we do not fear any evil tidings:
we are settled and grounded in Truth; and the more you persecute us,
the stronger we grow.`'
For this they experienced indeed, according to what they signified in their letters,
though they were separated a year from each other.
The friars coming once to Sarah, told her if she would she might go out of the prison,
and say and do nothing.
And she saying she would on that account, they said they would come next morning.
But Sarah perceived their deceit, and therefore when they came, she, to avoid the snare,
could not resolve to go forth, though the friars behaved themselves friendly,
and told her that the inquisitor had said, if they needed linen, woolen, stockings,
shoes, or money, they should have it.

Once it happened that an Englishman who lived there,
having heard that Sarah was in a room with a window next the street, got up by the wall,
and spoke a few words to her; but he was violently hauled down,
and cast into prison upon life and death; for he was one they had taken from the Turks,
and made a Roman Catholic of him.
The friars coming to them to know whether he had brought them any letters,
they said '`No.`' Neither had Catharine seen him; yet it was told them,
he was like to be hanged.
Of this Sarah gave information to Catharine, by writing a few lines to her,
(for it seems they then could not hear one another,) and she told her,
she thought the English friars were the chief actors of this business.
This grieved Catharine, and she wrote to Sarah again,
(for they had a private way to send to each other.) In this letter, after her salutation,
she said to Sarah, that she might be sure the friars were the chief actors;
but that she believed the Lord would preserve that poor Englishman for his love,
and that she was made to seek the Lord for him with tears;
and that she desired her to send him something once a day, if the keeper would carry it;
that she herself was ravished with the love of God to her soul,
and her beloved was the chiefest of ten thousands;
and that she did not fear the face of any man, though she felt their arrows:
moreover that she had a prospect of their safe return into England.
And in the conclusion, she bade Sarah take heed, if she was tempted with money.
But this letter, (by what means they never knew,) came to the English friar`'s hands,
who translating it into Italian, delivered it to the lord inquisitor;
and afterwards came with the inquisitor`'s deputy to Catharine,
and showed her both the papers, and asked her if she could read the English one:
'`Yes,`' said she, '`I wrote it.`'
'`O, did you indeed?`'
said he.
'`And what is it you say of me here?
'`Nothing but what is true,`' replied she.
Then he said, '`Where is the paper Sarah sent?
Give it, or else I will search your trunk, and everywhere else.`'
She then bidding him search where he would, he said,
she must tell him who it was that brought her ink,
or else she should be tied with chains presently.
And she returned she had done nothing but what was just and right in the sight of God;
and what she did suffer on that account would be for Truth`'s sake.
And she would not meddle with the poor workmen.
Then he said, '`For God`'s sake tell me what Sarah did write.`'
And she told him something, and said, what she spoke was truth.
'`But,`' returned he, '`you say it is much we do not tempt you with money.`'
And this indeed happened afterwards.
The deputy then took Catharine`'s ink, and threw it away; and so they went also;
and the poor Englishman was released the next morning.
They now coming to Sarah, told her that Catharine honestly had confessed all,
and that she had best to confess too: and they threatened her with a halter,
and that they would take away her bed and trunk, and her money too: to which Sarah said,
it may be she might not send to Catharine any more: and she asked the deputy,
whether he was a minister of Christ, or a magistrate; if he were a magistrate, said she,
he might take her money, but she would not give it him.
He then growing angry, said she was possessed; to which she replied, if so,
then it was with the power of an endless life.

Thus from time to time they suffered many assaults;
and sometimes it so happened that those who came to see them, were struck to the heart,
which offended the friars.
Now at length their money was almost gone, they having sometimes employed it for food.
But the friars told them they might have kept their money for other services;
for they should have maintained them while they kept them prisoners.
To this they said they could not keep their money and be chargeable to others.
Then it so fell out that their stomachs were taken away,
and they did eat but little for three or four weeks,
till at length they found themselves obliged to fasting for several days together:
which made the friars say,
that it was impossible that people could live with so little food as they did.
And it was told them the lord inquisitor had said, they might have any thing they would.
To which they signifying that it was not in their own will they fasted,
said they must wait to know the mind of the Lord, what he would have them to do.
They continued weak, especially Sarah, who apprehending her death near,
did therefore dress her head as she would lie in the grave.
They both were so feeble that they could not put on their clothes, neither put them off,
being also unable to make their beds.
And though they desired to be together in one room, yet the friars would not permit it.
In this condition they concluded they were like to die;
but heaven had provided otherwise.

Catharine about that time, being exercised in supplication to the Lord,
that it might please him to put an end to their trial,
which way it seemed good in his sight, thought she heard a voice saying,
'`You shall not die:`' and she took this to be a heavenly voice:
and from that time they felt themselves refreshed with the living presence of the Lord,
to their great joy and comfort, so that they felt freedom to eat again:
and then they were provided with good food;
but yet they were under a fear of eating any thing
which in some respect might be counted unclean;
and therefore they cried unto the Lord, and said,
'`We had rather die than eat any thing that is polluted and unclean.`'
And Catharine believed it was said to her from the Lord, '`You may as freely eat,
as if you had wrought for it with your hands.`'
And Sarah, who sometimes wrought for others in the inquisition house,
was persuaded that it was told her by inspiration,
'`You shall eat the fruit of your hands, and be blessed.`'
And so they did eat, and for eight or ten days they got whatever they did call for.
But afterwards they were so straitened for lack of food,
that it did them more hurt than their fast.
Yet they being preserved alive, the friar said,
'`The Lord keeps them alive by his mighty power, because they should be Catholics.`'
To which they returned, it should be known one day the Lord had another end in it.
But the friars told them plainly there was no redemption for them.
Whereupon they said, With the Lord there was mercy and plenteous redemption:
and they bade them take heed, '`you be not found fighters against God.`'
To which the friars returned, '`You are foolish women.`'
'`Then we are, '`replied they, '`the Lord`'s fools;
and they are dear and precious in his sight.`'
The friars then showing their shaven crowns, said that they were the Lord`'s fools; and,
pointing to their gowns,
said they did wear them for God`'s sake to be laughed at by the world.
One of the friars about this time did what he could to send Catharine to Rome;
and not succeeding, he said they should go both.
But this not taking effect, the friar was sent there with a paper,
containing matter of charge against Catharine; but she speaking zealously to the scribe,
pronounced woe against it, and defied it in the name of the Lord.
Before the friar departed, he told Sarah that Catharine was a witch,
and that she knew what was done elsewhere.
He said this, because once telling Catharine abundance of lies,
she told him she had a witness for God in her, which was faithful and true;
and she believed this witness.
After he was gone,
the English consul came to her with a dollar from the master of a ship,
who came from Plymouth.
She told him she did receive her countryman`'s love, but could not receive his money.
He then asked her what she would do if she would take no money; to which she answered,
'`The Lord is my portion, and thus I cannot lack any good thing.
We were in your house near fifteen weeks, did you see any cause of death and bonds in us?
And he saying No, she signified to him,
that in some respect he had been accessory to their imprisonment,
and had not been ignorant of the intent: '`You know,`' said she,
'`that a room was provided for us in the inquisition;
and had we not been kept alive by the mighty power of God,
we might have been dead long since endeavoring to excuse himself, he said,
'`how could I help it?
Then she put him in mind of what happened at his house, when they were there,
and how they called them to repentance, and forewarned them.
To which he said, '`However it be, it will go well with you.`'
Then she told him how he required a sign of her, when they were at his house,
if they were the servants of the Lord God:
and she asked him whether that was not true they spoke to him:
'`You are a condemned person, and stands guilty before God; yet nevertheless repent,
if you can find a place.`'
While she thus spoke to him, his lips quivered, and he trembled,
so that he could scarce stand upon his legs: and though otherwise a very handsome man,
and in his prime, yet he now looked as one that was pining away;
and this was a sufficient sign for the whole city, if they had duly taken notice of it.

Catharine having refused the piece of money, he went to Sarah with it:
but she likewise told him she could not take it;
but if he had a letter for them she should be free to receive it.
He saying he had not any, asked her what she did lack; and she answered,
the Lord was her shepherd, she could not lack any good thing;
but she did long for her freedom.
He, not willing to discourage her, said, '`That you may have in time.`'
But he did not live to see it, for the next time they heard of him he was dead.

While the friar was gone to Rome, it was told them they were also to be sent there;
and there was indeed great workings about it;
but it seems they could not agree in the matter.
In the meanwhile Catharine and Sarah remained separated,
and there were five doors between them with locks and bolts;
and yet Sarah sometimes found an opportunity either by the carelessness of the keeper,
or that it was done on purpose, to come where she could see Catharine;
and how much soever the friars did watch them, yet she came to Catharine`'s door by night.
But being once discovered, she was locked up again;
yet not long after the doors were again open, so that they sat in sight of each other.

Sometimes there were of various nations brought prisoners into the inquisition;
and the friars, and other great men, endeavored in their way, to make Christians of them.
Then these women would often show the errors of popery, and declare the Truth,
for which they were willing to suffer death, if required: but this was taken very ill.
At length it happened that two Englishmen came into that city,
and tried to obtain their liberty, but in vain.
Yet a little while after, the magistrates sent for and asked them whether they were sick;
or whether they did lack any thing; saying they might write to England,
ordering the scribe to give them ink and paper.

Not long after came one Francis Steward, a captain of a ship, and a friar of Ireland,
who both took great pains to get them released;
and their friends in England had not been lacking
in any thing that might procure their liberty.
But the time for it was not yet come.
The said captain, and the new English consul, endeavored much to procure their liberty;
but it was not in the magistrates power, for the inquisitor said,
he could not set them free, without an order from the Pope.
Yet Catharine and Sarah were brought into the court chamber,
and the English consul asked them if they were willing to go back to England,
and they said, Yes, if it were the will of God they might.
The captain of the ship, who also was there, spoke to them with tears in his eyes,
and told them what he had done in their behalf, but in vain.
'`It is the inquisitor,`' said he, '`who will not let you go free:
you have preached among these people.`'
To which they said, that they had witnessed the Truth,
which they were willing to maintain with their blood.
He replied, if they could be set free, he would freely give them their passage,
and provide for them.
And they returned, his love was as well accepted of the Lord, as if he did carry them.
He also offered them money, but they refused to take any.
They then gave him a relation of their imprisonment and sufferings,
and said they could not change their minds, though they were to be burnt to ashes,
or chopped in small pieces.
The friar then drawing near, said they did not work: but this was not true,
for they had work of their own, and did work as they were able.
They also told him their work and business was in England.
He confessing this was true, said they had suffered long enough, and too long,
and that they should have their freedom within a short time,
but that there was needed an order from the Pope.
In the meanwhile it grieved the captain that he could not obtain their liberty;
and going away, he prayed God to comfort them;
and they besought the Lord to bless and preserve him unto everlasting life,
and never to let him, nor his, go without a blessing from him, for his love.
For he ventured himself exceedingly in that place, by laboring to get their freedom.

After he was gone, they met with worse usage, and the inquisitor coming,
looked upon them with indignation; for the taking away of their lives was again on foot,
and their doors were shut up for many weeks.
After some time the inquisitor came again into the tower where they sat;
and Sarah called to him,
and desired the door might be opened for them to
go down into the court to wash their clothes.
He then ordered the door to be opened once a week:
and not long after it was open every day.
And since it had been said, that they could not be released without the Pope`'s leave,
Sarah said to him, '`If we are the Pope`'s prisoners, we appeal to the Pope:
send us therefore to him.`'
But those that had their abode in the inquisition, especially the friars,
were their mortal enemies,
although they would sometimes have fed them with the best of their provisions,
and given them whole bottles of wine, if they would have received it;
and it troubled them exceedingly, that they refused to eat and drink with them;
which they did, because they looked upon them as their fierce persecutors.

Once there came two or three English ships into the harbor,
and the English consul telling them of it, said, that he did what he could for them,
but that they would not let them go, unless they would turn Catholics,
and that therefore they must suffer more imprisonment yet.
Before Sarah knew these ships were come there, she saw them in the night in a dream,
and heard a voice saying that they could not go yet.
When the ships were gone, they were sent for,
and it was asked them if they would be Catholics; to which they answered,
they were true Christians, and had received the Spirit of Christ.
One of the magistrates showing them the cross, they told him,
they did take up the cross of Christ daily,
which was the power of God to crucify sin and iniquity.
Knowing that there was a friar, who, as the captain had told them,
took a great deal of pains for them, but not seeing him there,
(for he secretly favoring them, was now absent,) they said to those that were present,
'`One of your fathers has promised us our liberty.`'
But this availed nothing.
Yet they acknowledged his kindness, and told him afterwards,
he would never have cause to repent it.
A friar once coming to them, said, '`It is God`'s will you should be kept here,
or else we could not keep you.`'
On which Catharine told him, '`The Lord allows wicked men to do wickedness,
but he does not will them to do it; he allowed Herod to take off John the Baptist`'s head,
but he did not will him to do it: he allowed Stephen to be stoned,
and Judas to betray Christ; but he did not will them to do so; for if he had,
he would not have condemned them for it.`'
The friar hereupon asking, '`Are we then wicked men?`'
She answered, '`They are wicked men that work wickedness.`'
'`But,`' said he, '`you have not the true faith.`'
To which she answered, '`By faith we stand, and by the power of God we are upheld.
Do you think it is by our own power and holiness we are kept from a vain conduct,
from sin and wickedness?
He then saying that was their pride, she told him, '`We can glory in the Lord,
we were children of wrath once as well as others;
but the Lord has quickened us that were dead, by the living word of his grace,
and has washed, cleansed, and sanctified us in soul and spirit, in part,
according to our measures; and we do press forward towards that which is perfect.`'
He then said, '`You are good women: but yet there is no redemption for you,
except you will be Catholics.`'
This was the old lesson of the friars, who, at another time, said, '`You may be Catholics,
and keep your own religion too, and yet shall not be known to be Catholics,
except you were brought before a justice.`'
To which they returned, '`What, should we profess a Christ we should be ashamed of?

Some of those that came to see them would pity them for not turning Catholics;
but others showed their hatred, by crying that they must be burnt, and by bawling,
_'`Fuoco, fuoco,`'_ (fire, fire.) While they were separated from each other,
Catharine was often much concerned for Sarah, and afraid that she should be ensnared;
for one of the friars many times accosted her with fawning words:
but they both continued steadfast,
and were often ravished by the inward joy and consolation they felt.
Catharine in one of her letters said, that the spirit of prayer was once upon her,
but that she was afraid to speak to the Lord,
for fear she should speak one word that would not please him.
And then it was returned from the Lord, '`Fear not, daughter of Zion; ask what you will,
and I will grant it you, whatsoever your heart can wish.`'
But she desired nothing of the Lord, but what would make for his glory,
whether it were her liberty, or bondage, life or death.
And in this resignedness she found herself accepted of the Lord.

Sometimes they spoke so effectually to those that came to them,
that they could not gainsay them, but were made to confess that God was with them;
though others would make a hideous noise, and cry, '`Jesu Maria,`' and run away,
as people that were struck with fear.
Catharine`'s prison being so near the street,
that she could be heard of those that went by,
she was moved sometimes to call them to repentance,
and to turn to the light wherewith they were enlightened,
which would lead them out of all their wicked ways and works,
to serve the true and living God, in spirit and in truth.
This so reached some, that they did sigh and groan, and stay to hear her; but not long,
it being forbidden upon great pain.
Yet some that passed by to their worship houses were so wicked,
that they threw stones at her window, and often made a sad noise, and howled like dogs.

Thus they were assaulted both from abroad, and within doors from the friars,
who fiercely threatened them for their bold testimony against idolatry.
Once when they showed Sarah the Virgin Mary and her babe pictured against a wall,
and would have her look upon it, she, to show her zeal against idol-worship,
stamped with her foot, and said, '`Cursed are all images, and image-makers,
and those that fall down to worship them.`'

It happened that some French and Spanish ships came to join with the cavaliers of Malta,
to fight against the Turks; Sarah hearing this, said, '`God is angry, God is angry;
go not forth to kill one another; Christ came not to destroy life, but to save it.`'
This she told many who were persuaded of obtaining a victory; but it fell out otherwise,
for their fleet was beaten by the Turks, and they returned with great damage.

A friar coming once to Catharine, asked her why she did not work;
which made her say to him, '`What work do you?`'
He answered, '`I write.`'
To which she returned, '`I will write too, if you will bring me pen, ink, and paper.`'
He not willing she should write, said, '`St. Paul did work at Rome;
and by knitting she might get about three half-pence a day.`'
She told him, '`If we could have that privilege among you,
which Paul had at Rome under Caesar, who was a heathen prince, we would have wrought,
and not have been chargeable to any; for he lived in his own hired house two years,
preaching the gospel, and doctrine of the Lord Jesus Christ.`'
She asked him also, whether he knew the holy war of God?
'`And if you know it,`' said she,
'`then you can not but know that we cannot be without exercise day nor night.`'
This stopped his mouth; besides it was well known that they spent not their time idly;
for they knit stockings for those that were serviceable to them;
they made garments for the poor prisoners, and mended their clothes;
though they were not willing to work for the friars, who sometimes coming to her,
kneeled down, and would have Catharine to say after them the words they spoke.
But this she refused to do, though it made these men grow more angry.
Such and the like occurrences so grieved her,
that once in anguish of spirit she cried out to God,
'`It were better for me to die than to live thus.`'
For being almost continually constrained to testify against idolatry and superstition,
she would have been willing to have laid down her life for a testimony against it,
if it had been required of her.
And when once the friars told her that Sarah was to be carried to Rome,
while she should stay at Malta, it so grieved her, that with supplication,
she asked the Lord if he did not count her worthy to go to Rome also,
and to offer up her life there for the testimony of Jesus: because,
if she was at liberty to choose, she would rather do so,
than return without her to England.

At another time, when it was told them that their bibles were false,
Catharine asked the friar that said so, '`Wherein are they false?`'
He replied, because the books of the Maccabees were not in them.
To which she answered, that though something might be lacking,
yet the rest might be good for all that: but if something were added,
then the bible was corrupted.
This struck at some additions she had seen in the bibles there.
Then he asked her whether she did not think that everyone must bow at the name of Jesus;
and she answering, '`Yes,`'he said, '`Jesus,`' and bade her to kneel down, or to bow herself.
To which she said, that her heart and whole body was bowed down under the name of Jesus;
but that she would not bow at the will of him, or any body else.
'`He that departs from iniquity, (thus she continued,) bows before the name of Jesus;
but they that live in sin and wickedness, do not bow before the Son of God.`'
Then he said, that he and his companions stood in the same power,
and were led by the same spirit as the apostles.
Which made her ask, why then they abused that power, and used carnal weapons?
He answered, they did not do so, for their inquisition, no,
even their chains and fetters were spiritual.
Then he asked her,
whether she did not think all those damned that were not of her persuasion; she said,
'`No, Christ has not taught us so; for those that are today in a state of reprobation,
the Lord, if it please him, can call tomorrow out of it.`'
He then said, '`We think you damned, and all those that are not of our belief.`'
To which she returned, '`The judgment of man does not hurt us.`'

Sometimes some came to the prison upon their saints`' days,
and asked them what day it was: and they not being acquainted with those saints,
would answer, '`We do not know it.`'
When the others then told them, that it was such or such a saint`'s day,
and that this saint would punish them that night, because they did not observe his day;
they answered, that they knew the saints to be at peace with them,
and that therefore they did not fear them.
Another time a friar came and told them, it was seventeen days to Christmas,
and that the Virgin Mary conceived that present day.
On which Catharine made this remark, that indeed this was very singular,
that she did go with child but seventeen days.
Such like occurrences grieved her exceedingly,
when she considered the gross darkness these people were in:
and as she was crying to the Lord in prayer,
that it seemed that all their travail and labor was fruitless, she felt this answer:
'`Be not grieved, though Israel be not gathered,
the seed of Malta is to increase into multitude; that which you have sown shall not die,
but live.`'

After Catharine and Sarah had been imprisoned at Malta about three years,
there came one Daniel Baker, who did whatever he could, and went also to the inquisitor,
to obtain their liberty, but in vain;
for he required that some English merchants at Leghorn, or at Messina,
should engage for four thousand dollars, that they being released,
should never return into those parts.
But they were unwilling to enter into those terms,
as not knowing what the Lord one time or other might require of them.
Daniel, seeing he could not obtain their deliverance this way,
offered himself to be imprisoned instead of them; and this not being accepted,
he went yet further, and signified,
that he was willing to lay down his life for their liberty,
if it was not to be purchased otherwise.
Great love indeed! of which but few instances are to be found.
And they hearing of this, were touched with exceeding great admiration.
In the meanwhile, he found a way to get some letters delivered to them,
and wrote also himself, both to comfort and exhort them to steadfastness.
At length he found means also to speak to them: for on a time,
as they stood at the prison gates, he being come in their sight,
saluted them in those words: '`The whole body of God`'s elect, right dearly beloved,
acknowledge your testimony, and you are a sweet savor unto the Lord and his people.`'
To which one of them answered,
that it was a trouble to them that they could not be more serviceable.
This made his heart melt with pity and compassion,
considering the wonderful mercy of the Lord in preserving
them without fainting in that sharp trial:
and they beholding one another at a distance through the iron grates,
were mutually refreshed at that season.
They afterwards wrote to him, and signified with the most tender expressions,
how highly they valued his great love;
and also sent him letters for their friends and relations in England;
and he neglected not to write back again to them during his stay,
which was in the forepart of the year 1662.
But he was forced to leave them prisoners there:
yet the time of their redemption drew nigh,
which was brought about at the instance of George Fox and Gilbert Latey,
by writing to the lord Aubigny, as has been said already.

Some time before Daniel Baker came to Malta, it had been told them,
that if they would turn Catholics, they might dwell at Malta.
To which their answer was, that they were true Catholics.
One of the magistrates said, that if they would not turn Catholics,
they must yet suffer long imprisonment by the Pope`'s order.
And yet it was not true that there was such an order.
It was also told them, if they would kiss the cross, they should be released;
and they might stay at the house of the English consul,
until an opportunity offered to carry them to England.
In the meanwhile they heard that the Pope had given order
to let them pass to England without doing them any hurt.
But however it was, they were preserved well contented, and they said resolutely,
that they would not kiss the cross, nor purchase their liberty at that rate.
It seems the consul aimed at some advantage by their releasement;
for he told them that the inquisitor had said,
if any one would engage for three or four thousand dollars to be paid,
if ever they came there again, they should be set at liberty.
This he said also to D. Baker, and added, that if none would engage,
they must die in prison, and that this was the Pope`'s order.
After Baker`'s departure, word was sent to some English merchants,
concerning such an engagement, but none appeared willing to enter into it;
and the prisoners were so far from desiring, that they spoke against it.
Yet there were many that sought to obtain their liberty,
showing themselves willing to engage for what was reasonable;
but all their endeavors were in vain.

Once they fasted three days, and though it was a cold season, they sat upon the ground,
with a very little clothes, without stockings or shoes,
having nothing upon their heads but ashes.
The inquisitors seeing it, wondered exceedingly;
and Sarah began to speak zealously against superstition and idolatry.
And when the time of their fast was expired, Catharine composed the following,

[verse]
____
HYMN TO GOD.

All praise to him that has not put
Nor cast me out of mind.
Nor yet his mercy from me shut.
As I could ever find.

Infinite glory, laud, and praise.
Be given to his name.
Who has made known in these our days.
His strength and noble fame.

Oh none is like unto the Lamb!
Whose beauty shines bright,
O glorify his holy name.
His majesty and might.

My soul praise you the only God,
A fountain pure and clear.
Whose crystal streams spread all abroad.
And cleans far and near.

The well-springs of eternity,
Which are so pure and sweet,
And do arise continually,
My bridegroom for to meet.

My sweet and dear beloved one,
Whose voice is more to me
Than all the glory of the earth,
Or treasures I can see.

He is the glory of my life.
My joy and my delight.
Within the bosom of his love
He closed me day and night.

He does preserve me clean and pure
Within his pavilion,
Where I with him should be secure,
And saved from all wrong.

My soul praise you the Lord, I say.
Praise him with joy and peace;
My spirit and mind both night and day.
Praise him and never cease.

O magnify his majesty.
His fame and his renown,
Whose dwelling is in Zion high.
The glory of his crown.

O praises, praises to our God,
Sing praises to our King;
O teach the people all abroad,
His praises for to sing.

A Zion song of glory bright,
That does shine out so clear;
O manifest it in the sight
Of nations far and near;

That God may have his glory due.
His honor and his fame.
And all his saints may sing anew
The praises of his name.
____

After Catharine had joyfully sung thus, she went to the well in the court,
and drank much water in the sight of the prisoners, as did Sarah also:
for they were very dry, and Sarah washing her head also in cold water,
they cried out in their language, '`You will kill yourselves, and goto the devil.`'
But this they did not fear, neither caught they any cold,
and so became a wonder to others.

About half a year after Daniel Baker was gone, it came into Catharine`'s heart,
that if she could speak with the inquisitor, he would grant them their liberty.
And it was not long after that he came to the inquisition court chamber,
which they hearing, desired to speak with him, which was granted,
and being admitted into his presence,
they told him they had not wronged or defrauded any,
but had suffered innocently almost four years for conscience-sake, etc.
After this the inquisitor was very courteous to them,
and promised their liberty in a few days, saying he would send for the consul,
and get him to engage for five hundred dollars,
to be paid for them if ever they came again.
And in case the consul denied this, he would send to Rome to the Pope,
to set them at liberty without any obligation.

Not many days after the inquisitor came with his lieutenant, the chancellor, and others,
and after some discourse,
asked them whether they would return back again to their husbands and children,
if it were the will of God: to which they answered,
it was their intent in the will of God so to do.
Hereupon they were released, and the inquisitor took his leave very courteously of them,
and wished them a prosperous return to their own country;
so likewise did the magistrates, and the inferior officers,
not requiring one pennyworth for fees or attendance;
yet in their own freedom they gave something to the keeper and some poor men.

Being thus set at liberty,
they kneeled down and prayed God never to lay to their charge what they did unto them,
because they knew them not.
And then they were delivered into the consul`'s hands,
who told them that he had engaged for them to get them free;
but they could never find that it was true.
Now they were kept eleven weeks at the consul`'s house,
before they could get a passage from there.
Catharine in the meanwhile, being under a great concern,
because of a judgment that was impending over the city,
wrote a paper to the rulers of Malta, in which she said,
that on the 25th of the month called August,
it came upon her from the Lord to write thus to them in his name,

[.embedded-content-document.letter]
--

My wrath is kindled against you, and my judgment is set up among you,
because of your hard-heartedness and unbelief I the Lord, who desire the death of no man,
but that all should return unto me and live, have cast my servants among you,
contrary to their will, and without their knowledge,
to go and forewarn you of the evil that was coming upon you.
For all the wicked shall be brought to judgment.
I will establish my beloved Son upon his throne, and he shall rule in his princely power,
and reign in his kingly majesty, whose right it is over all;
and his own spiritual government shall he set up in all places,
righteous rule and pure worship in Spirit and in Truth.
There is nothing that can prevent the Lord, who says, If you will not hear my servant,
which speaks my word, whom you proved almost these four years,
whose life has been harmless and spotless, in pure innocency among you,
then will I bring woe upon woe, and judgment upon judgment upon you,
till the living shall not be able to bury the dead.
My mouth has spoken it, and my zeal will perform it;
and every man`'s hand shall be upon his loins for pain; for the day of recompense is come.
But if you will hear my servant which speaks in my name,
and return in your minds to the light in your consciences, which convinces of all evil,
and deny all evil thoughts, words, and actions, then will I pour out my spirit upon you,
and will soon cure you of your diseases, and heal you of your pain.

--

This, and more she wrote, and delivered to the consul to give it to the grand master,
and the rest of the governors; but the consul not being pleased with it,
threatened her with imprisonment again.
What further became of the paper I do not find, but this, that on the 8th of October,
there was great thunder and lightning,
which set on fire and blew up one of the powder-houses about a mile out of the city,
and another powder-house was thrown down; and in the city, five houses were overthrown,
most of the glass windows of the palaces and other houses broken,
the doors lifted off their hooks, the walls torn, and the whole city terribly shaken,
so that being at midnight, a cry went through the whole city, and the bells were rung.
At the bed`'s leet where Catharine and Sarah lay, was a glass window,
which also was broken, but they received no hurt,
though the house was so shaken that they did exceedingly fear and quake;
but being given up unto the Lord to live and die, their fear was soon taken from them,
and turned into joy in the Lord.
When it was day the consul came to them, and they being still and quiet,
he asked whether they were not dead: and while he was speaking others came in,
telling what was done in the city;
and he told them that even the ships in the harbor had suffered damage.
Then they said, '`One woe is past, and behold another woe comes quickly,
if you do not repent.`'

Some days after Sarah fasted, sitting upon the ground with ashes upon her head,
her neck and shoulders bare;
and she spoke to the consul to desire the grand master to proclaim a fast,
and to make the people to meet together to wait upon the Lord,
with their minds turned to him, that so he might turn away his judgments from them;
for the hour of his judgments was come,
wherein the painted harlot should be stripped naked,
and receive a cup of trembling from the hand of the Lord.
The consul performed this message to the magistrates,
and the friars said the woman had a good intent.
Sometime after the inquisitor came, and talking with them, said, '`Your intent is good,
but the devil has deceived you.`'
And they asked him whether the devil could give power over sin: to which he said,
the devil could transform himself into an image of light.
This they assented to, but yet said he could not hide himself from the children of light;
though they that were in the dark could not discern him.
He could not abide to hear this, but went away, and the consul, who was present,
wrought against them to get them into bondage again, but in vain.
Many now died in the town of a violent fever:
whether any other disaster followed upon their prediction, I cannot tell.

At length there came one of the king of England`'s frigates, called the Sapphire,
commanded by captain Samuel Titswel, who took them in,
together with some knights of Malta; among them was the inquisitor`'s brother,
who often spoke to the captain, that they might not lack any thing that was in the ship,
and he told them, if they came to Malta again, they should not be persecuted so.
And to the captain he said, '`If the}`' go to heaven one way, and we another,
yet we shall all meet together at last.
But they told him that Christ Jesus, the light of the World,
was the only way to the Father.

Departing from Malta, after some time they came to Leghorn,
where the merchants showed them great kindness,
and sent wine and other things for their refreshment, offering them also money;
but they were unwilling to accept it.
From there they came to Tangier,
which the king of England had in marriage with the daughter of the king of Portugal.
This place was at that time besieged by the Moors,
yet Catharine and Sarah entered the town,
and many came flocking into the house where they were lodged,
for they boldly exhorted the people to depart from wickedness.
They also went to the governor, who was courteous to them,
and took their admonition in good part, and promised to follow their counsel.
And he would have given them money, but they took none, though they accepted his love;
for he commanded that none of the garrison should abuse them either in word or deed,
upon pain of severe punishment:
yet the Portuguese and Irish were ready enough to have done them mischief.
They being inclined to go out to the Moors, desired the governor to let them go forth,
but he told them they must expect from that savage people nothing but cruel death,
or bonds forever:
and though they signified to him that they believed the Lord would preserve them,
since they were persuaded that he required of them to go to the Moors,
yet the governor in a friendly manner withheld them from going.
Being thus stopped, they believed that the Lord accepted of their good will.
When they went aboard again, though in another ship, several took shipping with them,
from a belief, that on their account, they should have a safe passage.
The captain and others that were in the ship,
behaved themselves very civilly towards them; and though they met with tempests,
yet at length they arrived safe in England.

Catharine afterwards related, that when,
(in the inquisition,) she was for many days together
in expectation that they should be burnt,
she saw in a dream in the night, a large room, and a great wood fire in the chimney,
and she beheld one sitting in the chair by the fire, in the form of a servant,
whom she took to be the Eternal Son of God:
likewise she saw a very amiable well-favored man-child,
sitting in a hollow chair over the fire,
(not appearing to be above three-quarters of a year old,
and having no clothes on but a little fine linen about the
upper parts,) and the fire flamed about it;
yet the child played, and was merry.
She would then have taken it up, for fear it should have been burnt;
but he that sat in the chair bid her let it alone.
Then turning about she saw an angel,
and he that sat in the chair bid her take up the child, which she did,
and found it had no harm; and then awaking, she told her dream to Sarah,
and desired her not to fear, since the heavenly host thus followed them.

I have collected this relation of the occurrences of these women at Malta,
from several papers and letters,
which not long after their return home were published in print.
And since no due order was observed there, and many things mentioned,
which to avoid prolixity I have passed by, as not very material,
I may have haply missed in some case or other, as to the order or series of time,
but yet I think the matters of fact are not mutilated.
Now to give the reader an idea of the frame of these women`'s minds, and their sufferings,
I will insert some of their letters:
among those which they wrote to their friends in England was this following:

[.embedded-content-document.epistle]
--

O dearly beloved friends, fathers, and elders, and pillars of God`'s spiritual house,
and brethren and sisters in the Lord Jesus Christ,
in the measure of love and life of our God, do we salute you all,
and do embrace you in that which is eternal, and we do greatly rejoice,
and glorify the name of our heavenly Father,
that he has counted us worthy to be partakers of the death
and sufferings of his blessed Son with you;
though we be the least of God`'s flock, yet we are of the true fold,
whereof Christ Jesus is shepherd; and he has had as tender a care over us,
as he has had of any of his lambs which he has called forth in this the day of his power,
and has carried us through and over as great afflictions
as most of our brethren and sufferers for his name,
both in mockings, scoffings, scornings, reproaches, stripes, contradictions,
perils at land, perils at sea, fiery trials, cruel threatenings, grief of heart,
sorrow of soul, heats and colds, fastings, and watchings, fears within,
and fightings without; terrible temptations and persecutions, and dreadful imprisonments,
and buffetings of Satan; yet in all these our trials, the Lord was very gracious unto us,
and did not absent himself from us, neither permitted his faithfulness to fail us,
but did bear us up, and keep us from fainting in the midst of our extremity.
We had not another to make our moan to, but the Lord alone;
neither could we expect a drop of mercy, favor, or refreshments,
but what he did distill from his living presence, and work by his own strength;
for we sat one in one room, and the other in another, near a year; as owls in deserts,
and as people forsaken in solitary places.
Then did we enjoy the presence of the Lord, and did behold the brightness of his glory,
and we did see you, our dear friends, in the light of Jesus,
and did behold your order and steadfastness of your faith and love to all saints,
and were refreshed in all the faithful-hearted,
and felt the issues of love and life which did stream from
the hearts of those that were wholly joined to the fountain,
and were made sensible of the benefit of your prayers.

O the sorrows, the mournings, the tears! "`But those that sow in tears,
shall reap in joy.`"
A true sorrow begets a true joy; and a true cross a true crown:
for when our sorrows did abound, the love of God did abound much more:
the deeper the sorrows, the greater the joys; the greater the cross,
the weightier the crown.

Dear friends and brethren, marvel not that Israel is not gathered,
our judgment remains with the Lord, and so do our labors;
for it was not for lack of travail, nor pain, nor love to their souls;
for we could have been contented to have fed upon the grass on the ground,
so we might have had our freedom among them: for,
had it not been for the great opposition, they would have followed after us,
as chickens after a hen, both great and small.
But oh! the swelling seas, the raging and foaming waves, stormy winds and floods,
and deep waters, and high mountains and hills, hard rocks, rough ways, and crooked paths,
tall cedars, strong oaks, fruitless trees, and corrupted ones, that cumber the ground,
and hinder the righteous seed to be sown, and the noble plants from being planted.
Oh! they shut up the kingdom against the simple-hearted,
and hide the key of knowledge from the innocent ones,
and will not enter into the kingdom themselves, nor allow them that would enter,
but stir up the magistrates to form carnal weapons,
thinking to prevent the Lord of taking to him his inheritance, and to dispossess his Son,
who is heir of all, that he might not have a dwelling-place among them,
nor a habitation nigh them; because that his light will discover their darkness,
and his brightness will burn up all their abominations, and mar their beauty,
and stain their glory, their pomp, and their pride,
that it may perish as the untimely figs, and fall as the flower of the field,
and wither as the grass upon the house-top.
Oh! the belly of hell, the jaws of Satan, the whole mystery of iniquity is at the height,
and all manner of abomination that makes desolate, stands where it ought not,
and is upholden by a law, that upon pain of death none must speak against it,
nor walk contrary to it.
But praises to our God, he carried us forth to declare against it daily.
Oh! the blind guides, the seducing spirits, that do cause the people to err,
and compel them to worship the beast and his image, and have his mark in their foreheads,
and in their hands, and to bow to pictures and painted walls,
and to worship the things of their own hands,
and to fall down to that which their own fingers have fashioned,
and will not allow them to look towards Zion upon pain of death,
nor to walk towards Jerusalem upon pain of faggot and fire, but must abide in Babel,
and believe whatsoever they speak or do to be truth.
But oh! the ways, the worships, the fashions, forms, customs, traditions, observations,
and imaginations, which they have drawn in by their dark divinations,
to keep the poor people in blindness and ignorance,
so that they perish for lack of knowledge, and are corrupted,
because the way of Truth is not made known among them; they are all in the many ways,
out of the one true living way, and their ways be so many and so monstrous,
that they are unrehearsable;
but the Lord our God has kindled a fire in the midst of them,
that will consume all forms, fashions, customs, and traditions of men,
and will burn up the briers, thorns, and tares, stubble, and fruitless trees,
and corrupted ones; and will blast all the fruits, works,
and labors of wicked and ungodly men, with the mildews of his wrathful indignation,
and will scatter all his enemies with the whirlwinds of his displeasure.
They do not know the Scriptures:
their bibles would grieve any honest heart to behold them, because of the corruption.

--

This letter was signed by both of them, though perhaps Catharine was the writer,
who also wrote a letter of exhortation to the Catholic inquisitor at Malta,
and another to friar Malachy.
Among the letters she wrote to her husband and children,
I count the following really worthy to be delivered to posterity:

[.embedded-content-document.letter]
--

For the hands of John Evans, my right dear, and precious husband,
with my tender-hearted children,
who are more dear and precious to me than the apple of my eye.

Most dear and faithful husband, friend, and brother, begotten of my eternal Father,
of the immortal seed of the covenant of light, life, and blessedness,
I have unity and fellowship with you day and night, to my great refreshment,
and continual comfort.
Praises, praises be given to our God forevermore,
who has joined us together in that which neither sea nor land can separate or divide.

My dear heart, my soul does dearly salute you, with my dear and precious children,
who are dear and precious in the light of the Lord, to your endless joy,
and my everlasting comfort; glory be to our Lord God eternally,
who has called you with a holy calling,
and has caused his beauty to shine upon you in this the day of his power,
wherein he is making up of his jewels,
and binding up of his faithful ones in the bond of everlasting love and salvation,
among whom he has numbered you of his own free grace; in which I beseech you,
dear hearts, in the fear of the Lord, to abide in your measures,
according to the manifestation of the revelation of the Son of God in you.
Keep a diligent watch over every thought, word, and action,
and let your minds be stayed continually in the light,
where you will find out the snares and baits of Satan, and be preserved out of his traps,
nets, and pits, that you may not be captivated by him at his will.
Oh, my dear husband and children,
how often have I poured out my soul to the everlasting Father for you,
with rivers of tears night and day,
that you might be kept pure and single in the sight of our God,
improving your talents as wise virgins, having oil in your vessels;
and your lamps burning, and clothed with the long white robe of righteousness,
ready to enter the bed-chamber, and to sup with the Lamb,
and to feed at the feast of fat things, where your souls may be nourished, refreshed,
comforted, and satisfied, never to hunger again.

My dear hearts, you do not lack teaching; you are in a land of blessedness,
which flows with milk and honey, among the faithful stewards,
whose mouths are open wide to righteousness,
to declare the eternal mysteries of the everlasting kingdom,
of the endless joys and eternal glory;
whereunto all the willing and obedient shall enter and be blessed forever.

My dear hearts, the promises of the Lord are large,
and are all Yes and Amen to those that fear his name;
he will comfort the mourners in Zion,
and will cause the heavy-hearted in Jerusalem to rejoice, because of the glad tidings:
they that do bear the cross with patience, shall wear the crown with joy;
for it is through the long-suffering and patient waitings,
the crown of life and immortality comes to be obtained.
The Lord has exercised my patience, and tried me to the uttermost, to his praise,
and my eternal comfort, who has not been lacking to us in anything in his own due time;
we are witnesses he can provide a table in the wilderness, both spiritual and temporal.
Oh, the endless love of our God,
who is an everlasting fountain of all living refreshment,
whose crystal streams never cease running to every thirsty soul,
that breathes after the springs of life and salvation.

In our deepest affliction, when I looked for every breath to be the last,
I could not wish I had not come over sea,
because I knew it wag my eternal Father`'s will to prove me,
with my dear and faithful friend.
In all afflictions and miseries the Lord remembered mercy,
and did not leave nor forsake us, nor allow his faithfulness to fail us;
but caused the sweet drops of his mercy to distill upon us,
and the brightness of his glorious countenance to shine into our hearts,
and was never lacking to us in revelations or visions.
Oh, how may I do to set forth the fulness of God`'s love to our souls:
no tongue can express it, no heart can conceive it, nor mind can comprehend it.
Oh, the ravishments, the raptures,
the glorious bright shining countenance of our Lord God, who is our fulness in emptiness,
our strength in weakness, our health in sickness, our life in death, our joy in sorrow,
our peace in disquietness, our praise in heaviness,
our power in all needs or necessities; he alone is a full God unto us,
and to all that can trust him.
He has emptied us of ourselves, and has unbottomed us of ourselves,
and has wholly built us upon a sure foundation, the rock of ages, Jesus Christ,
the Light of the World, where the swelling seas, nor raging, foaming waves,
nor stormy winds, though they beat vehemently, can be able to remove us.
Glory, honor, and praise, is to our God forever, who, out of his everlasting treasures,
does fill us with his eternal riches day by day;
he did nourish our souls with the choicest of his mercies,
and does feed our bodies with his good creatures,
and relieve all our necessities in a full measure.
Praises, praises be to him alone, who is our everlasting portion, our confidence,
and our rejoicing, whom we serve acceptably with reverence and godly fear;
for our God is a consuming fire.

Oh, my dear husband, and precious children, you may feel issues of love and life,
which stream forth as a river to every soul of you,
from a heart that is wholly joined to the fountain.
My prayers are for you day and night without ceasing;
beseeching the Lord God of power to pour down his tender mercies upon you,
and to keep you in his pure fear, and to increase your faith,
to confirm you in all righteousness,
and strengthen you in believing in the name of the Lord God Almighty,
that you may be established as Mount Zion, that can never be moved.
Keep your souls unspotted of the world, and love one another with a pure heart fervently;
serve one another in love, build up one another in the Eternal,
and bear one another`'s burdens for the Seed`'s sake, and so fulfill the law of God.
This is the word of the Lord unto you, my dearly beloved.

Dear hearts, I do commit you into the hands of the Almighty, who dwells on high,
and to the word of his grace in you,
who is able to build you up to everlasting life and eternal salvation.
By me, who am your dear and precious wife, and spouse, in the marriage of the Lamb,
in the bed undefiled,

[.signed-section-signature]
C+++.+++ E.

[.postscript]
My dearly beloved yokemate in the work of our God, does dearly salute you.
Salute us dearly to our precious friends in all places.
I do believe we shall see your faces again with joy.

[.signed-section-context-close]
This was written in the Inquisition at Malta, in the 11th month, in the year 1661.

--

The following letter was written by Sarah to her husband, Henry Cheevers, and Children.

[.embedded-content-document.letter]
--

My dear husband, my love, my life is given up to serve the living God,
and to obey his pure call in the measure of the manifestation of his love, light, life,
and Spirit of Christ Jesus, his only begotten Son, whom he has manifested in me,
and thousands, by the brightness of his appearing, to put an end to sin and Satan,
and bring to light immortality, through the preaching of the everlasting gospel,
by the Spirit of prophesy,
which is poured out upon the sons and daughters of the living God,
according to his purpose; whereof he has chosen me, who am the least of all: but God,
who is rich in mercy, for his own name-sake has passed by my offences,
and has counted me worthy to bear testimony to his holy name,
before the mighty men of the earth.
Oh the love of the Lord to my soul!
My tongue cannot express, neither has it entered into the heart of man,
to conceive of the things that God has laid up for them that fear him.

Therefore does my soul breathe to my God for you and my children, night and day,
that your minds may be joined to the light of the Lord Jesus,
to lead you out of Satan`'s kingdom, into the kingdom of God,
where we may enjoy one another in the life eternal,
where neither sea nor land can separate; in which light and life do I salute you,
my dear husband, with my children, wishing you to embrace God`'s love,
in making his truth so clearly manifest among you; whereof I am a witness,
even of the everlasting fountain that has been opened by the messengers of Christ,
who preach to you the word of God, in season and out of season,
directing you where you may find your Savior, to purge and cleanse you from your sins,
and to reconcile you to his Father, and to have unity with him and all the saints,
in the light, that you may be fellow-citizens in the kingdom of glory, rest, and peace,
which Christ has purchased for them that love him, and obey him.
What profit is there for to gain the whole world, and lose your own souls?
Seek first the kingdom of God and the righteousness thereof,
and all other things shall be added to you.
Godliness is great gain, having the promise of this life that now is,
and that which is to come; which is fulfilled to me,
who have tasted of the Lord`'s endless love and mercies to my soul;
and from a moving of the same love and life do I breathe to you my dear husband,
with my children; my dear love salutes you all; my prayers to my God are for you all,
that your minds may be joined to the light, wherewith you are lightened,
that I may enjoy you in that which is eternal, and have communion with you in the spirit.
He that is joined to the Lord, is one spirit, one heart, one mind, one soul;
to serve the Lord with one consent.
I cannot by pen or paper set forth the large love of God,
in fulfilling his gracious promises to me in the wilderness,
being put into prison for God`'s truth, there to remain all the days of my life,
being searched, tried, examined, upon pain of death,
among the enemies of God and his Truth; standing in jeopardy for my life,
until the Lord had subdued and brought them under by his mighty power,
and made them to feed us, and would have given us money or clothes;
but the Lord did deck our table richly in the wilderness.
The day of the Lord is appearing, wherein he will discover every deed of darkness,
let it be done never so secretly;
the light of Christ Jesus will make it manifest in every conscience;
the Lord will rip up all coverings that are not of his own spirit.
The God of peace be with you all.
Amen.

Written in the Inquisition prison by

[.signed-section-signature]
Sarah Cheevers.

--

Several other letters both she and Catharine wrote to their husbands, and relations.
But since great part of my narrative was fetched from there, I pass them by.
But by these inserted, one may see that they were not women of a dull temper,
but ingenious and cheerful.

In a letter of Sarah`'s to her friends in Ireland, I find these words:

[.embedded-content-document.letter]
--

My life is given up to the service of the Lord: bonds, chains, bolts, irons,
double doors, death itself, is too little for the testimony of Jesus,
and for the word of God; so the seed be gathered, it is but`'a reasonable sacrifice.
Bonds and afflictions betide the gospel of Christ.
Those that will five godly in Christ Jesus, must suffer persecution.

--

[.offset]
And in a letter to Daniel Baker, Catharine said,

[.embedded-content-document.letter]
--

The time is too little for me to disclose the twentieth part of the terrible trials;
but whensoever we were brought upon any trial, the Lord did take away all fear from us,
and multiplied our strength,
and gave us power and boldness to plead for the Truth of the Lord Jesus,
and wisdom of words to stop the mouths of the gainsayers; but then they would say,
we had not the true faith, but we had all virtues.
Dearly beloved, pray for us, that we fall not, nor fail;
whereby our enemies may have any advantage to rejoice, and say,
we served a god that could not serve us, and called upon a god that could not deliver us;
as if we were like them, to call upon stocks, stones, pictures, and painted walls,
and dead things that cannot hear, see, nor speak.
We do beseech you to tell all our dear friends, fathers, and elders,
the pillars of our spiritual building, with all the rest of our Christian brethren,
that we do desire their prayers, for we have need of them.

--

[.offset]
This letter they concluded with the following Poem:

[verse]
____
How strong and powerful is our King
To all that do believe in him!
He does preserve them from the snare,
And teeth of those that would them tear.

We that are sufferers for the seed,
Our hearts are wounded,
and do bleed To see the oppression, cruelty.
Of men that do your Truth deny.

In prisons strong, and dungeons deep,
To God alone we cry and weep:
Our sorrows none can learn nor read,
But those that in our path do tread.

But he whose beauty shines bright,
Who turns darkness into light,
Makes cedars bow, and oaks to bend
To him that`'s sent to the same end.

He is a fountain pure and clear,
His crystal streams run far and near,
To cleanse all those that come to him
For to be healed of their sin.

All them that patiently abide,
And never swerve nor go aside.
The Lord will free them out of all
Bondage, captivity, and thrall.
____

They composed several others, which fell into the hands of their enemies,
and copies of them were given to the inquisitor.
But now I leave them.
