== Chapter XII.

=== 1662-1664.

[.chapter-synopsis]
* Daniel Baker at Malta and Gibraltar
* Persecutions in Leicester
* Friends outlawed for refusing to swear
* Sufferings of A. Rigg and T. Luxford
* Act to prevent dangers by Quakers
* E. Burrough`'s Apology for the Quakers
* Continuation of persecution in New England
* Josiah Southwick
* Three women sentenced to be whipped through eleven towns
* Ann Coleman
* Cruel usage of Elizabeth Hooton and Joan Broksup
* Cruelties exercised upon Edward Wharton
* Impious expressions of New England persecutors
* Deaths of New England persecutors
* Effect of shedding innocent blood at Boston

Before I return to transactions in England,
I shall relate a singular case of Daniel Baker, who being come to Smyrna,
with intent to travel from there to Constantinople, was stopped by the English consul,
and sent to the Isle of Zante, where a ship lay bound for Venice, in which he embarked,
and coming into that city, he stayed there a week, and went from there to Leghorn,
with intent to take shipping there for England: but during his stay in that place,
he inwardly felt drawings towards Malta,
to try whether he could be helpful to Catharine and Sarah, that were prisoners there,
since he had several times been stirred up thereto;
and though the difficulty of the matters had kept him back,
yet he could not have peace in his mind, before he gave himself up to that service;
and so he embarked in a French ship for Sicily: and coming to Syracuse,
he stayed there five days, and then set sail for Malta; where being arrived,
he got admitted to the Pope`'s inquisitor,
to whom he spoke in the Italian tongue in this way:
'`I am come to demand the just liberty of my innocent friends,
the English women in prison in the inquisition.`'
The inquisitor asked him if he were related to them as husband or kinsman,
and whether he came out of England on purpose with that message.
To this Daniel answered, that he came from Leghorn for that same end.
But the inquisitor told him they should abide in prison till they died,
except some English merchants, or others that were able,
would engage for the value of three or four thousand dollars,
that they should never return into those parts.
His request being thus denied, he went to the English consul,
and spoke with him and several others: but all his endeavors proved vain;
and he himself was threatened with the inquisition;
and the Pope`'s deputy would have had him bound,
that he should neither speak good nor evil to any body, while he was on the island,
save to him and the consul.

After a stay here of three weeks, he passed again to Italy,
and from there took shipping for England: but being come into the Straits of Gibraltar,
he saw that the high mountain there,
was the same place he had seen the foregoing year in a dream,
when prisoner in Worcester jail in England.
Here the ship wherein he was, with several other vessels, lay about a month,
because of the contrary wind, so that they could not set sail.
In the meanwhile being under a burden, he perceived there was a service for him ashore;
but, considering this to be dangerous, he wished to have been excused of it;
but felt no peace before he fully gave up, whatever, either bonds or death, might ensue.
While the fleet lay here wind-bound, several ships attempted to pass through,
but could not: and the like temptation attended him as that of Jonah, that is,
to flee from the place, and so to escape the burden under which he labored.
But he found, as afterwards signified in a printed relation, that obedience was his duty,
though it was required of him to be a sign against the idolatry of the church of Rome.
He then told the master of the ship in which he was a passenger, something of the matter,
and said that he believed that God would soon give
opportunity for the fleet to pass away,
after his service was performed.
The master was hard to be persuaded to put him ashore, yet at length he allowed it,
upon the day they used to call Maunday Thursday.
Being now landed, he went to the town, and so into the mass-house,
where he found the priest at the high altar, upon his knees, in his white surplice,
adoring the host.
After he had awhile been viewing this idolatry,
he felt the indignation of God kindled in his heart against it:
and turning his back upon the priest and his dead god,
he set his face towards the people, and saw the multitude upon their knees also,
worshipping they knew not what.
In this posture, spreading forth his arms, he slipped off his upper garment,
and rent it from top to bottom in several pieces,
which he cast from him with indignation: then he took his hat from off his head,
as being the uppermost covering of man, and casting it down,
stamped upon it with his feet, and appearing in sackcloth covering, he with a loud voice,
thrice sounded repentance,
and said that the life of Christ and his saints was arisen from the dead.
And so he passed away unmolested,
sounding the same message with repentance through the streets,
till he came to the sea-side, where he kneeled down to pray,
and gave thanks to the Lord for his wonderful preservation,
and that he had allowed no man to touch or do him any harm.
Being no shore, he delivered a paper, written in the Spanish tongue,
to the governor and inhabitants of Gibraltar, with some Latin books.
That to the governor, etc. was as follows:

[.embedded-content-document.paper]
--

Behold, behold, the great day of God is come, and of his wrath,
and of the wrath of his Lamb.
The hour of his judgment is come.
Wherefore, O inhabitants of the earth, repent, repent, repent!
Fear God,
and give glory and honor to him that made heaven and earth and the fountains of waters.
Woe, woe, woe to the inhabitants of the earth.
John heard another voice from heaven saying, "`Come out of her my people,
that you partake not of her sins, and that you receive not of her plagues.`"
These are the words of the power of Christ, that is contrary to the false church.
Behold, behold, plagues, plagues, plagues are coming upon the church of Rome,
and upon her heads in all parts of the world.

--

Daniel being now come again on ship-board, the next day the Lord gave them a rear wind,
and all the fleet set sail; and after some time he arrived safe in England.
But being come to London, it was not long, before he,
who had travelled without hurt in foreign parts, was imprisoned by his countrymen,
as will be related hereafter: and being shut up in prison,
he wrote a narrative of his travels, from which I look my relation.

About this time John Stubbs returned into England,
having been in the dominions of the great Turk.
But I do not find that he met with any singular occurrences,
but that he had spread some books.
He and Alexander Parker coming to London, found G. Fox there,
with whom they travelled towards Bristol: by the way they had several meetings,
and being come to Bristol,
they understood that the officers were likely to come and disturb the meeting.
Yet on the First day of the week they went there, and A. Parker stood up first to preach;
but while he was speaking, the officers came and took him away.
Then G. Fox stood up and preached undisturbed, so that the meeting ended peaceably.
And he, staying in town that week, visited his friends, and was visited by them.
The next First-day some of his friends came to him,
and endeavored to persuade him not to go to the meeting that day; '`For,`' said they,
'`the magistrates have threatened to take you away, and in order thereto,
have raised the trained bands.`'
G+++.+++ Fox desired them to go their way to the meeting,
without telling them what he intended to do.
Yet not long after he went there: but being met by some of his friends,
they did what they could to stop him; and, '`What,`' said one,
'`Will you go into the mouth of the beast?`'
'`Will you go into the mouth of the dragon?
said another.
But G. Fox would not allow himself to be thus prevented, but went on.
Being come there he perceived a concern and fear upon his friends for him,
but his preaching there was so powerful, that all fear departed from them;
and having concluded his sermon with a prayer, he stood up again and told the auditory,
now they might see there was a God in Israel that could deliver:
for the officers and soldiers had been breaking up another meeting,
which had taken up their time; and they were in a great rage that they had missed him;
for it was resolved on now to persecute the Quakers, and, if possible to root them out.

G+++.+++ Fox, after having tarried yet some days at Bristol,
went through Wiltshire and Berkshire, back again to London;
yet he did not stay long there, but travelled towards Leicestershire,
and passing by Barnet Hills, he found there one captain Brown, a Baptist,
whose wife belonged to the society of those called Quakers.
This captain, for fear his wife should go to meetings and be cast into prison,
had left his house at Barrow, and taken a place on the said hills,
thinking himself more safe there.
G+++.+++ Fox going to see the wife, and being come into the house, asked him how he did;
'`How Idol`' said he, '`the plagues and vengeance of God are upon me, a runnagate, a Cain,
as I am: God may look for a witness for me, and such as me;
for if all were no faithfuller than I, God would have no witness left in the earth.`'
In this condition Brown lived there on bread and water, and thought it too good for him;
but at length he returned with his wife to his own house at Barrow,
where he came to be convinced of the Truth professed by those called Quakers,
and died in it; and a little before his death,
he said that though he had not borne a testimony for Truth in his life,
he would bear a testimony in his death;
desiring to be buried in his orchard in a plain way.

But I return to G. Fox, who being come into Leicestershire, went to Swanington,
to the house of a widow woman, where at night came one called the lord Beaumont,
and a company of soldiers, who took him out of the hall where he was,
and brought him to the said lord who asked him his name: to which he answered,
'`My name is George Fox, and I am well known by that name.`'
'`Aye,`' said Beaumont, '`you are known all the world over.`'
Then he put his hands into George`'s pockets to search them, and pulled out his comb-case,
and afterwards commanded one of the officers to search for letters:
which made G. Fox say, that he was no letter carrier,
asking him why he came among a peaceable people
with swords and pistols without a constable;
since this was contrary to the king`'s proclamation;
and it could not be said there was a meeting;
for G. Fox had been talking in the hall only with the widow woman and her daughter.
Beaumont sending then for the constables, gave them charge to watch G. Fox,
and some that were with him that night; accordingly the constables set a watch upon them,
and next morning brought them to Beaumont`'s house,
who then told them they met contrary to the act:
for not long before this time the parliament, by the instigation of the clergy,
had made an act against conventicles (i.e. unlawful religious gatherings),
containing that if any were convicted of having been at a conventicle,
they should incur a fine not exceeding five pounds,
or imprisonment not above three months.
G+++.+++ Fox saying to the lord Beaumont, that he did not find them in a meeting,
and so there was no transgression of the said act, Beaumont asked him,
whether he would take the oaths of allegiance and supremacy: to which G. Fox answered,
'`I never took any oath in all my life.`'
And desired him to show that oath,
that they might see whether it was not for the discovery of Catholic recusants.
But Beaumont being unwilling, caused a court order to be made,
which mentioned that they were to have had a meeting:
a cunning artifice indeed to vex an innocent people.
And with the court order he charged the constables to convey them to Leicester jail.
The constable who was charged to bring G. Fox and his friends to prison,
was unwilling to do it himself, and being harvest time,
it was hard to get any body to go with them;
and therefore he would have given them the court
order to carry it themselves to the jailer.
This they refused, though sometimes some of their friends had done so:
for the constables had such experience of their fidelity,
that they dared trust them even in such a case, without fearing the bird would escape.
Then the constable hired a poor man, who was reluctant to go with them on this errand.
Yet they rode with him through the country, being five in number,
and some carried their bibles open in their hands, and passing through towns,
they told people they were the prisoners of the Lord Jesus Christ,
going to suffer bonds for his name`'s sake.
Being come to Leicester, and going into an inn,
the master of the house seemed somewhat troubled that they should go to prison;
but they being unwilling to consult with lawyers, to which they were advised,
suffered themselves to be had to prison; where being come,
G+++.+++ Fox asked whether the jailer or his wife was master: and it was told him,
'`The wife,`' who though she was lame, and not able to go without crutches, yet,
would beat her husband when he came within her reach,
if he did not do as she would have him.

G+++.+++ Fox perceiving from this that without her leave
he should not be able to agree with her husband,
got somebody to bargain with her for a room, for him and his friends,
and to leave it to them to give her what they would; to which she consented.
But then it was told the prisoners,
the jailer would not permit them to fetch any drink out of the town into the prison;
but what beer they drank they must take it of him, and that, as was easily to be guessed,
would be at a dear rate.

This made G. Fox say, he could remedy that;
for since the jailer could not deny them water, he would get a pail of it once a day,
and put some wormwood into it, and that might serve their turn.
So long as G. Fox was in prison there,
he and his friends had a meeting every First-day of the week in the yard,
to which came not only the debtors and felons that were prisoners,
but also several people out of the town and country;
whereby many were convinced of the truth he preached,
and continued to be faithful witnesses for it.

While G. Fox was confined there, several more of his friends were sent to prison;
to the number of about twenty.
And when the sessions came they were brought before the justices,
who tendered to them the oaths of allegiance and supremacy:
for this was the ordinary snare, when no other thing could be found to lay hold on.
But G. Fox told them he never took any oath in his life;
'`And you know we cannot swear because Christ and his apostles forbade it;
and therefore this is but as a snare to us;
yet if you can prove that after Christ and his apostles forbade swearing,
they ever did command Christians to swear, then we will take these oaths;
otherwise we are resolved to obey Christ`'s command, and the apostle`'s exhortation.`'
To this it was returned that they must take the oath
to manifest their allegiance to the king.
G+++.+++ Fox, to show that he was not unfaithful to the king,
told them that formerly he had been sent up a prisoner by colonel Hacker,
from that town to London,
under pretense that he held meetings to plot for bringing in king Charles.
Then he desired that their court order might be read,
which set forth the cause of their commitment to be, that they were to have a meeting.
And he said also, that the lord Beaumont could not by the act send them to jail,
unless they had been taken at a meeting;
and therefore he urged the reading of the court order,
that it might be seen how wrongfully they were imprisoned.
But whatever he said, they would not take notice of the court order, but called a jury,
and indicted the prisoners by refusing to take the oaths of allegiance and supremacy.
When the jury was sworn and instructed, as they were going out,
one that had been an alderman spoke to them,
and recommended them to have a good conscience: but one of the jury being a peevish man,
told the justices there was one affronted the jury.
Whereupon he was called up, and to try whether he was a Quaker,
the oath was also tendered to him, and he took it;
and thus the snare intended against him did not hold.

While the prisoners stood waiting,
a cut-purse had put his hand into the pockets of some of them,
which they told the justices of, and showed them the man.
They then called him up, and upon examination he could not deny the fact,
yet they let him go free, just as if the robbing of those called Quakers was no crime.

It was not long before the jury returned, and brought the prisoners in guilty.
And then the justices whispered together,
and bade the jailer take the prisoners and carry them back to jail.
But a little after they were in prison again, the jailer came to them and said,
'`Gentlemen, it is the court`'s pleasure that you should all be set at liberty,`' etc.
Thus they were released on a sudden, which was indeed remarkable,
because the jury had brought them in guilty;
on which passing of sentence must have followed.
But G. Fox`'s liberty seems to have been owing to the following cause:
he had a letter from the lord Hastings, who having heard of his imprisonment,
had written from London to the justices of the sessions to set him at liberty.
This letter he had not as yet delivered to the justices,
who perhaps had some knowledge of the said lord`'s mind from another hand,
which made them resolve on this sudden discharge.
G+++.+++ Fox being now free, carried this letter to the lord Beaumont,
who having opened and read it, seemed somewhat troubled; and yet threatened him,
if he had any more meetings at Swanington, he would disperse them,
and send him to prison again.
But notwithstanding these threatenings, he and his friends went to Swanington,
and had a meeting there without being disturbed.
From there he travelled to London, where we will leave him,
and in the meanwhile see what happened elsewhere.

Some time before, Thomas Goodair and Benjamin Staples were imprisoned at Oxford,
and being brought into the court of judicature before Sir William Walter,
who sat there as judge, and Goodair being examined and nothing found against him,
the oath of allegiance was tendered, to which he answered,
that he acknowledged the king as supreme ruler in civil temporal matters,
and that he was willing to obey him in all just commands.
'`But,`' said he, '`if king Charles and those who are in authority under him,
enjoin me to any thing contrary to the command of Christ,
then I will rather obey Christ than king Charles, or those in authority under him.
It is for conscience-sake that I cannot swear,
though I could gain the whole world thereby; for Christ has forbidden it,
and said "`Swear not at all;`" and James says, "`Above all things swear not.`"
But whatever Goodair said was in vain, for they would needs have him swear.
He continuing to refuse swearing,
justice Walker asked those that were with him on the bench,
whether they had any thing to say against his passing sentence against them:
to which they having said no, bespoke thus to Goodair, '`Hearken to your sentence:
you are out of the king`'s protection.
All your lands, real estate, and chattels, are forfeited,
and shall be seized for the king`'s use:
and you are to remain prisoner during the king`'s pleasure.`'
Then he bid the jailer take Goodair away,
who asked whether the jailer had charge to fetter him,
for he had been fettered as thieves and felons,
before he had been brought into the court.
Whereupon the judge answered, '`The jailer may do with you what he will:
for you are now out of the king`'s protection.`'
Then he was led away, and B. Staples brought to the bar,
to whom the oath being also tendered, and he refusing to take it,
the same sentence was passed on him.
Both being returned to prison,
the jailer said to the other prisoners that were there for evil or debts,
'`If you need coats, you may take those of the Quakers,
for they are now out of the protection of the law.`'
But one of the prisoners was so honest as to say he would rather go naked,
than take away those men`'s coats.
How long they were in prison, and whether they died there, or were at length released,
I know not.^
footnote:[They both were supposed to be discharged at the next general jail delivery:
for T. Goodair in 1666, had been prisoner some years at Warwick,
being premunired without legal trial or judgment.
At length he died at Selby in Yorkshire, 1693.--J. Whiting`'s Account.]

But now I return to Ambrose Rigge, who being come to Hurst Pier-point in Sussex,
had a meeting there at the house of his father-in-law, captain Thomas Luxford;
this so displeased the priest Leonard Letchford,
that Rigge was taken and brought before the Justices, Walter Burril, Nisel Rivers,
and Richard Bridger, who being minded to bring him under sufferings,
tendered him the oath of allegiance; and he,
saying that for conscience-sake he could not swear, was forthwith sent to Horsham prison,
and at the time of the court session brought into the court,
where judge Samuel Brown then sat, and passed the sentence of premunire upon him.
Then he was carried back, and by the instigation of the said Leonard Letchford,
committed close prisoner, where he continued above ten years,
and suffered during that time much hardship by the malice of the jailers,
since such prisoners as he was, are shut out of the king`'s protection.
In the meanwhile the aforesaid priest Letchford summoned Rigge`'s wife for tithes,
and she refusing payment, was also imprisoned at the prosecution of this priest;
and then he seized her goods,
taking away also that which her husband had earned in prison by his hard labor,
not leaving him and his wife a bed to lie on; no,
he also took away a pot they had borrowed from other prisoners to boil food in,
and vaunted he had Rigge so fast, that it was not in the King`'s power to release him.
But notwithstanding this wicked boast, yet to his great disquiet and vexation,
he lived to see Rigge released by the king under the great seal.
And Thomas Luxford, Ambrose Rigge`'s father-in-law,
being also become one of the society of those called Quakers,
and refusing to pay him tithes, felt likewise the effects of his fury;
for he caused him also to be cast into jail, where he kept him six years:
and the prisoners being then released by the sheriff, he was excommunicated by Letchford,
and afterwards at his suit, by virtue of the statute _De excommunicato capiendo,_
shut up again in prison, from which he was set at liberty by an act of parliament.
(_De excommunicato capiendo_ was an ancient writ ordering the imprisonment
of an excommunicated person until he or she submitted to the church)

Not long after, Letchford got a warrant to sue also some others of the Quakers,
so called, belonging to his parish, for not paying tithes:
but before he could get them imprisoned, it happened,
that having at night gone to bed healthy,
in the morning he was found stiff dead in his bed,
according to the testimony of his neighbors;
and this prevented the stroke he had levelled against others.

Not being willing to finish this relation abruptly, I am advanced in time,
but now I return to the year 1662.
In the middle of this year, Sir Henry Vane and John Lambert,
both vigorous champions against king Charles the First,
and having been in great authority under the former government,
were brought to their trial.
Vane behaved himself with very great presence of mind:
how far he was guilty I am not to inquire; but he was declared guilty,
and afterwards beheaded on Tower-Hill.
He was reputed to be a man of great knowledge,
having been one of the chief members of the long parliament,
and also an opposer of Cromwell: for he was an entire republican,
and had a great share in the administration of state affairs.
Lambert, who had been an eminent general, saved his life: for since Vane, as Ludlow says,
pleaded for the lives and liberties of his country, and Lambert for his own,
he evaded the storm which took away Vane.
Lambert now, though condemned to death, begged mercy,
and was confined to perpetual imprisonment, and carried to a small isle near Plymouth,
where he finished his days.

Seeing, on the insurrection of the Fifth-monarchy-men,
occasion was taken to make an act against plotting, and seditious meetings,
the persecution against the Quakers increased,
under a pretense that their meetings were dangerous,
and to the terror of the king`'s subjects,
and an act was made against those who refused to take an oath,
as appeared by the title of it:

[.embedded-content-document.legal]
--

[.letter-heading]
An Act for Preventing Mischiefs and Dangers That
May Arise by Certain Persons Called Quakers,
and Others Refusing to Take Lawful Oaths.

Whereas of late times, certain persons under the name of Quakers,
and other names of separation, have taken up,
and maintained sundry dangerous opinions and tenets, and among others,
that the taking of an oath, in any case whatsoever, although before a lawful magistrate,
is altogether unlawful, and contrary to the word of God;
and the said persons do daily refuse to take an oath, though lawfully tendered,
whereby it often happens, that the truth is wholly suppressed,
and the administration of justice much obstructed: and whereas the said persons,
under a pretence of religious worship,
do often assemble themselves in great numbers in several parts of this realm,
to the great endangering of the public peace and safety, and to the terror of the people,
by maintaining a secret and strict correspondence among themselves,
and in the meantime separating and dividing themselves
from the rest of his majesty`'s good and loyal subjects,
and from the public congregations, and usual places of divine worship:

II. For the redressing therefore,
and better preventing the many mischiefs and dangers that do,
and may arise by such dangerous tenets, and such unlawful assemblies,
(2) Be it enacted by the king`'s most excellent majesty,
by and with the advice and consent of the lords spiritual and temporal,
and commons assembled in parliament, and by authority of the same,
that if any person or persons, who maintain that the taking of an oath,
in any case soever, (although before a lawful magistrate,) is altogether unlawful,
and contrary to the word of God, from and after the four-and-twentieth day of March,
in this present year of our Lord, one thousand six hundred and sixty-one,
shall willfully and obstinately refuse to take an oath, where,
by the laws of the realm he or she is, or shall be bound to take the same,
being lawfully tendered, (3) or shall endeavor to persuade any other person,
to whom any such oath shall in like manner be duly and lawfully tendered,
to refuse and forbear the taking of the same, (4) or shall by printing, writing,
or otherwise go about to maintain and defend that
the taking of an oath in any case whatsoever,
is altogether unlawful; (5) and if the said persons, commonly called Quakers,
shall at any time after the said four-and-twentieth day of March,
depart from the places of their several habitations,
and assemble themselves to the number of five or more,
of the age of sixteen years or upwards, at any one time,
in any place under pretense of joining in a religious worship,
not authorized by the laws of this realm, (6) that then in all and every such cases,
the party so offending, being thereof lawfully convicted, by verdict of twelve men,
or by his own confession, or by the notorious evidence of the fact,
shall lose and forfeit to the king`'s majesty, his heirs and successors,
for the first offense, such sum as shall be imposed upon him or her,
not exceeding five pounds; (7) and if any person or persons,
being once convicted of any such offense, shall again offend therein,
and shall in form aforesaid be thereof lawfully convicted,
shall for the second offense forfeit to the king, our sovereign lord,
his heirs and successors, such sum as shall be imposed upon him or her,
not exceeding ten pounds: (8) the said respective penalties to be levied by distress,
and sale of the party`'s goods so convicted,
by warrant of the parties before whom they shall be so convicted,
rendering the overplus to the owners, if any be: (9) and for lack of such distress,
or non-payment of the said penalty within one week after such conviction,
that then the said parties so convicted shall for
the first offense be committed to the common jail,
or house of correction, for the space of three months;
and for the second offense during six months, without bail or main-prize,
there to be kept to hard labor: (10) which said moneys so to be levied,
shall be paid to such person or persons,
as shall be appointed by those before whom they shall be convicted,
to be employed for the increase of the stock of the house of correction,
to which they shall be committed, and providing materials to set them on work:
(11) and if any person after he, in form aforesaid, has been twice convicted,
of any the said offenses shall offend the third time, and be thereof, in form aforesaid,
lawfully convicted, that then every person so offending, and convicted,
shall for his or her third offence, abjure the realm;
or otherwise it shall and may be lawful to, and for his majesty,
his heirs and successors, to give order, and to cause him, her, or them,
to be transported in any ship or ships,
to any of his majesty`'s plantations beyond the seas.

III.
And it is ordained and enacted by the authority aforesaid,
that all and every justice of Qyer and Terminer, justices of court, and jail-delivery,
and the justices of the peace, shall have full power and authority,
in every of their open and general quarter-sessions, to inquire, hear,
and determine all and every the said offenses,
within the limits of their commission to them directed,
and to make process for the execution of the same,
as they may do against any person being indicted before them of trespass,
or lawfully convicted thereof.

IV. And be it also enacted, that it shall and may be lawful to,
and for any justice of peace, mayor, or other chief officer, of any corporation,
within their several jurisdictions, to commit to the common jail, or bind over,
with sufficient sureties to the quarter-sessions,
any person or persons offending in the premises,
in order to his or their conviction aforesaid

V+++.+++ Provided always, and be it hereby further enacted,
that if any of the said persons shall, after such conviction as aforesaid,
take such oath or oaths, for which he or she stands committed,
and also give security that he or she shall for the time to come
forbear to meet in any such unlawful assembly as aforesaid,
that then, and from thereforth,
such person and persons shall be discharged from all the penalties aforesaid:
any thing in this act to the contrary notwithstanding.

VI. Provided always, and be it ordained and enacted by the authority aforesaid,
that all and singular lords of the parliament,
for every third offense committed against the tenor of this act,
shall be tried by their peers, and not otherwise.

--

This act caused E. Burrough to write a small book, called,
[.book-title]#The Case of the People Called Quakers, Stated,
to Show the Falsehood of the Accusations Charged Upon Them.#
First he showed in this treatise,
that suppose the Quakers were heretics and erroneous people, which was never yet proved;
yet we found no examples in.
Scripture that such should be imprisoned, or afflicted with corporal punishments.
Having treated of this matter at large,
he laid down the state of their way of meeting and worship,
appealing to others on this account, with these words:

[.embedded-content-document.treatise]
--

What judgment do our neighbors give in this case?
They say, concerning our meetings,
that they have known us to meet together in such manner, for many years,
in towns and villages, and never knew, nor understood of any harm or danger therein,
nor ever were any way prejudiced, either in their persons or estates, in our meetings.
The very witness of God in all our neighbors does testify, and give judgment,
that our meetings have always been peaceable and quiet,
and that we come together in peace and good order, and part in the same,
and no person has been harmed by such our meetings; inquire of the neighborhood,
and they will tell you they believe in their consciences, our meetings are for good,
and have good effects, and are not evil, nor bring forth any evil, to any.

And as for the manner of our meeting and sitting together, it is orderly and decently,
and of good report among men;
and for any doctrine that ever was there held or heard by any,
none can truly accuse it to be either error, or heresy, or sedition; but on the contrary,
they know it witnesses against all sin and iniquity,
and tends to the turning of people from ungodliness
and unrighteousness to truth and holiness:
and many can tell, this is effected by our doctrine preached in our meetings;
and our neighbors can witness that we part again in peace and good order,
and in convenient time; and they can show you they are not terrified,
nor the peace of the land disturbed, (on our part,) by our meetings,
which are in God`'s fear, and to the glory of his name,
which all sober men know are according to the law of God, and gospel,
and primitive Christian example.

[.small-break]
'''

We are accused as heinous offenders, and imprisoned,
because it is supposed we do not submit to obey the known laws of the land,
but break them, and will not conform to the church, pay tithes, take oaths,
have meetings together, etc. though we know the laws of the land command these things.

Plea: First, as to submitting to all known laws of the land;
this is known to God and our neighbors, that our principle and practice is,
and ever has been, to submit to every government, and to submit to all laws of men,
either by doing or by suffering,
as at this day we resist not the greatest of afflictions
and tribulations that can be imposed onus;
and this is well known to our neighbors and all people,
that we are submissive to all laws of men, by patient suffering without resistance:
even when any law requires any thing of us, which we cannot perform for conscience-sake,
that law we fulfill by patient suffering, resisting no man,
nor rendering evil for evil to any.
And the judgment of the Scriptures, which are according to both law and gospel,
and the precedents of saints justify us in this case,
in choosing patiently to suffer the greatest penalties of the law, rather than to obey,
(by doing,) any such law as requires things contrary to our pure consciences;
as in the example of the three children, Dan.
iii. who were commanded, to fall down and worship the golden image,
at what time soever they heard the sound of the music,
upon the penalty of being cast into the midst of the burning fiery furnace:
which commandment they could not obey, nor could they fall down to worship the image;
but rather chose to suffer the penalty of being cast
into the midst of the burning fiery furnace,
which accordingly was done unto them.
Again in the case of Daniel, chap.
vi. who was commanded to make no petition to any god or man for thirty days,
save to king Darius, upon the penalty and affliction of being cast into the lion`'s den:
but Daniel did rather choose to suffer the penalty, to be cast into the den of lions,
than to obey the commandment; and was cast into the lion`'s den.
By these examples of holy men, with many more that might be given out of the Scriptures,
it is evident,
that righteous men will rather choose to suffer than
to obey any law of man contrary to their consciences.
So the law of God, and example of saints, and Holy Scriptures,
give judgment for us in this case, of rather choosing to suffer,
than to obey laws contrary to our consciences;
and consequently must needs condemn such that persecute and imprison us,
because they require obedience of us in things against our consciences.

Secondly: '`Though we disobey laws, and cannot actively obey every law of man,
when it requires and commands things contrary to a good conscience;
yet herein also are we justified by the law of God,
example of saints and Holy Scriptures, and they give judgment for us,
and consequently against our enemies in this case;
and in particular in the two examples before-mentioned in Daniel,
the three children were expressly commanded to fall down and worship the golden image:
and Daniel was also required by the king`'s decree, not to pray to any God or man,
save to king Darius;
yet all these holy men of God did absolutely disobey
the law and decree so requiring of them,
and did contrary to the commandment: for the three children did not bow,
nor Daniel cease to pray to God, but prayed as at other times,
and yet were justified of God in so doing.
Also the apostles of our Lord Jesus Christ,
(Acts 4:18) were commanded to preach no more in the name of Jesus;
but the apostles did disobey their commandment,
and went on and preached in the Spirit and power of Christ,
contrary to the commandment of the rulers; and appealed to them,
whether it were not better to obey God than man.
Many examples we might collect out of the Scriptures,
that the servants of God did disobey the commands of kings and rulers,
and could not obey, (by doing,) any command contrary to God,
but rather chose to suffer afflictions, and death itself,
than to obey such laws and decrees, as required any thing contrary to a pure conscience:
and this is our case at this day: we cannot obey,
(by doing,) any thing against our consciences, but must break the laws of men,
and disobey their commandments, rather than break the law of God,
and sin against our own consciences, whatsoever we suffer because hereof;
and the examples of saints and Scriptures justify us in this behalf.

[.small-break]
'''

And let our enemies cease to cry out,
'`Rebellious and disobedient to laws and government;`' for we are
not such as do willfully and obstinately disobey any laws of men,
but for conscience-sake, and that we may not sin against God,
nor offend his witness in us; therefore we cannot obey laws contrary to our consciences,
whatsoever we suffer, which we resist not, nor rebel against any in this case:
so that our principles and practices are to obey every law and government,
either by doing or suffering.
And though we disobey such laws as are not according to the law of God,
and rather do choose to suffer, yet herein we are justified by the law of God,
and the Holy Scriptures.

Thirdly: And as for our conduct among men,
in respect of our daily walking and converse with them in our dealing,
in respect of honesty and faithfulness, and truth and justness in works and words,
our neighbors shall give witness for us.
We will not justify ourselves, it is God that justifies us, and the law of God,
gospel of Christ, Scriptures, examples of holy men, our neighbors,
and the witness of God in all men`'s consciences shall bear witness to us;
and all these do give judgment for us in these cases, to whom we do appeal for judgment.
And O Lord God everlasting, do you judge our cause;
do you make it manifest in your due season to all the world, that we are your people;
that we love you above all; that we fear your name more than all;
that we love righteousness and hate iniquity;
and that we now suffer for your holy name and truth, and for your honor and justice,
and for your truth and holiness.
O Lord, you know we are resolved to perish, rather than to lose one grain hereof.
Amen, Amen.

Our accusations and answers truly compared,
and weighed in the balance of justice and truth in every man`'s conscience,
let all the world judge of the case: do we deserve to be ruined, destroyed,
imprisoned and banished, and to be devoured of wild beasts,
as our enemy threatens us he will do?
Is it so?
Are we heretics?
Are we seditious?
Are we drunkards?
Are we double dealers?
Are we such as the law of God condemns?
What evil have we done in the land?
Do we hurt any body?
Are we not innocent before the Lord and men?
We appeal to the just witness of God and men.
Let it be answered; and though no man will hear and consider our cause this day,
yet the Lord will plead our cause in his time, and season,
and make the world to know we are his people;
in the meantime we are willing to suffer the reproaches of ungodly men,
till the Lord works deliverance in the earth.

But now it may be objected by the magistrates and rulers,
that we have now a law against you, and you must suffer,
for we cannot but put the law in execution, according to our oaths and offices;
and it is not we that persecute you,
but it is the law of the land by which you now suffer;
and we cannot be blamed for your suffering, we only execute the law.
And after this manner is the reasoning of some at this day, etc.

Answer: To all which I do answer: It is true there is a law now enacted against us,
which is pretendedly made the ground of our suffering;
but whether that law be in itself just or unjust, I shall not now demonstrate,
but shall leave it to the judgment of all Christian men that know us, our principles,
doctrines, ways, conduct;
and let them judge whether we deserve the penalties and punishments therein described,
for any principles or practice held and maintained by us.
And though there be a law against us, yet the magistrates that are executors thereof,
may execute the same with moderation or with violence; with discretion,
or too much rigor;
and it will be well for them to use moderation and discretion in this case:
hereby may they save themselves from that weight
of anger and indignation of the Lord God,
that will come upon all violent-doers, who seek to destroy the innocent,
and rejoice in the occasion administered.

And though this law be enacted against meetings, not ours I may say,
but such meetings as are dangerous to the public peace, and to the terror of the people:
but our meetings are not such,
and therefore this law may not justly extend in its
execution to the breaking of our meetings,
nor to banish us because of our meeting together, which is for the worship of God,
and are peaceable and of good report among all good men;
and are not for disturbance of the peace, nor terror of the people,
and therefore justly free from this law as aforesaid.

And though this law is pretended against us, for to banish us,
and to rid the land of us, as some vainly suppose;
yet must it needs be executed to the height of it, without limitation or restriction?
Must this law be executed to its height more than
some others laws that are as truly enacted,
and as fully in force as this act can be?
Yet some such laws there are, which better deserve execution than this,
yet they lie dormant, as it is visibly apparent at this day,
as in 4 Jac. c. 5, in these words: '`Be it enacted,
etc. that all and every person or persons,
which after forty days next following the end of this present session of parliament,
shall be drunk, and of the same offense of drunkenness shall be lawfully convicted,
shall for every such offense, forfeit and lose five shillings,
etc. to be paid to the hands of the church-wardens
of that parish where the offense shall be committed,
who shall be accountable therefor to the use of the poor of the same parish.
And if the said person or persons so convicted,
shall refuse or neglect to pay the said forfeiture,
then the same shall be levied off the goods of every such person or persons,
by warrant of precept from the court, judge, or justices,
before whom the same conviction shall be;
and if the offender be not able to pay the sum of five shillings,
then he shall be committed to the stocks for the space of six hours.`'
I pray you read the statute at large; it is worth a sober man`'s pains to read over,
and then judge whether that law be duly executed at this day:
and also whether it deserves not more strict execution than the present act against us.
Also the 1 Jac. c. 7, in these words:
'`That all persons calling themselves scholars, going about begging;
all idle persons going about in any country, either begging or using any subtle craft,
or unlawful games or plays, or feigning themselves to have knowledge in physiognomy,
or pretending that they can tell fortunes, or such other like fantastical imaginations;
all fencers, bear-wards, common players of interludes and minstrels, wandering abroad,
shall be taken, adjudged, and deemed as rogues, vagabonds, and sturdy-beggars,
and shall suffer such pains and punishments as are expressed in 39 Eliz. c. 4. that is,
'`That every such person shall be stripped naked from the middle upwards,
and shall be openly whipped, until his or her body be bloody,
etc. and shall be forthwith sent from parish to parish,`' etc.
Read the statute at large, and then consider how duly it is executed now,
and whether it deserve not the execution as much as the late act against us,
though in some places the one is more executed than the other,
where many of our friends being honest sober persons, and of good conduct,
yet are hauled out of their meetings, where they are met only to worship God,
and for no other end, and sent to prison,
and persecuted to the very height of the said act;
whereas idle persons following unlawful games and plays, and bear-wards,
common players of interludes and minstrels of various kinds,
do wander up and down city and country, and having their play-houses public,
where their wickedness is acted; such persons and such things, though appearing publicly,
yet are permitted, and little or no notice taken of them by some of the magistrates,
so as to punish them for breach of the laws, for the preventing of these evils;
but such wickedness is too much suffered,
though there be several acts of parliament against such persons and such actions,
as well as there is one against our meetings;
yet the act against us is more put in execution in some-places,
for the breaking of our meetings, which are for the worship of God,
than the good laws for suppressing of wickedness,
though there is better law for the one than for the other.
Several other laws and statutes made for good ends,
for the suppressing of wickedness in the land there are,
which are but easily executed at this day;
but here is one act against peaceable meeting together for the worship of God,
which is violently prosecuted and executed upon innocent men;
let all just men judge of these things.
Though there be a law enacted against our meetings,
so there is against drunkards and drunkenness,
and unseasonable tippling in taverns and ale-houses, and against minstrels, fiddlers,
pipers and players, common players, and stage players that go up and down the countries,
and have their play-houses in public cities; which statute ought rather to be executed,
though they are not: but these things we shall leave to all sober people to judge of.

And seeing that the law against us is more put in execution than those other laws,
it does appear that there is more envy against us and our
peaceable religious meetings than there is against profaneness,
and wickedness, drunkenness, and stage-playing, and such like:
and such magistrates wheresoever they are, are not excusable in the sight of God,
though there is a law against us, while they prosecute it against us,
and not those other good laws, against profane and ungodly persons and practices;
and therefore seeing we do suffer,
we must say it is not only because there is a law against us, but it is also, or rather,
because there is enmity, and wrath, and wickedness in the hearts of men against us,
which is the main cause of our sufferings at this day.

--

Thus was E. Burrough always laborious,
and like a faithful and diligent minister of Christ,
he was so totally devoted to the service of God and the church,
both in preaching and writing in the defence of the gospel,
that he scarce reserved any time for himself, and seldom took rest,
but continued to work incessantly till the time of his departure drew near;
plainly manifesting that it really was his food and
drink to do the will of his heavenly Father;
and this he endeavored unweariedly to the end of his days.

Now I turn again to New England, where though the murdering part was acted to the full,
yet their blood-thirstiness was not quenched,
as may appear from the following relation I shall
give of the cruel whippings inflicted on some.
If I should relate all of that kind that happened there,
it would make up a pretty big volume by itself;
and therefore I will mention some few instances only.

Among these, I meet with Josiah Southick, (whose father and mother,
Lawrence and Cassandra,
had been of the first that were banished from Boston because of their religion,
as has been said before;
and whose brother and sister had been ordered to be sold for bound slaves,) who,
having been in Old England, and had found himself obliged notwithstanding the severe law,
to return to Boston, was sentenced to be whipped at a cart`'s tail, first at Boston,
and then at Roxbury and Dedham, when with out-stretched arms,
he said to those who sentenced him, '`Here is my body;
if you need a further testimony of the Truth I profess, take it, and tear it to pieces;
it is freely given up; and for your sentence, I matter it not:`' adding further,
'`it is no more terrifying unto me,
than if you had taken a feather and blown it up in the air, and had said,
take heed it hurt you not:
for surely tongue cannot express nor declare the
goodness and love of God to his suffering people.`'
Then he was stripped and tied to the cart`'s tail in Boston,
where the hangman scourged him with what vehemency he could.
It is remarkable that the whip used for those cruel executions, was not of whip-cord,
as those in England, but of dried guts, and every string with three knots at the end,
which, being fastened to a stick, the hangman many times laid on with both his hands,
which must cause violent torture to the body.
But all this cruelty was not able to make Josiah faint;
for as he was led through the streets of Boston at the cart`'s tail, he sung aloud,
and was heard to utter these words: '`They that know God to be their strength,
cannot fear what man can do.`'
The same day he was whipped also at Roxbury, and the next morning, it being very cold,
at Dedham, where he was discharged and turned into the wilderness;
for so inhuman were these furious New England professors,
that they seemed to think that whatever it was,
there was nothing done amiss to the Quakers.
No, it has happened that being shut up with thieves,
and endeavoring to turn them from their wicked lives,
they have been ill treated on that account, and the thieves set at liberty,
lest they should turn Quakers.

At Dover, in New England, Anne Coleman, Mary Tomkins, and Alice Ambrose,
were sentenced to very cruel whipping, only for being come there:
the warrant was as follows:

[.embedded-content-document.legal]
--

[.letter-heading]
To the constables of Dover, Hampton, Salisbury, Newbury, Rowley, Ipswich, Wenham, Linn,
Boston, Roxbury, Dedham,
and until these vagabond Quakers are carried out of this jurisdiction.

You and every of you, are required in the king`'s majesty`'s name,
to take these vagabond Quakers, Anne Coleman, Mary Tomkins, and Alice Ambrose,
and make them fast to the cart`'s tail, and driving the cart through your several towns,
to whip them upon their naked backs, not exceeding ten stripes apiece on each of them,
in each town; and so to convey them from constable to constable,
till they are out of this jurisdiction, as you will answer it at your peril;
and this shall be your warrant.

[.signed-section-closing]
Per me:

[.signed-section-signature]
Richard Waldron.

[.signed-section-context-close]
At Dover, dated December 22, 1662.

--

Cruel indeed was this order;
because to whip these three tender women through eleven towns,
with ten stripes apiece at each place, through a length of near eighty miles,
in bitter cold weather, would have been enough to have beaten their bones bare,
and their lives out of their bodies.

Now in a very cold day the deputy Walden, at Dover,
caused these women to be stripped naked from the middle upward, and tied to a cart,
and then whipped them, while the priest looked on, and laughed at it;
which some of their friends seeing, and taking notice of Walden`'s cruelty,
testified against him; for which Walden put two of them in the stocks.

The women being thus whipped at Dover, were carried to Hampton,
and there delivered to the constable, William Fifield,
who having understood by the constable of Dover what
work he had in bringing them through a deep road,
thought to have daunted them, and said,
'`I profess you must not think to make fools of men.`'
To which they answered, they should be able to deal with him as well as the other.
This constable the next morning would have whipped them before day, but they refused,
saying that they were not ashamed of their sufferings.
Then he would have whipped them on their clothes when he had them at the cart;
but they said, '`Set us free,
or do according to your order;`' which was to whip them on their naked backs.
He then spoke to a woman to take off their clothes;
but she said she would not do it for all the world.
'`Why,`' said he, '`I profess I will do it myself.`'
So he stripped them, and then stood trembling with the whip in his hand,
and so he did the execution, though at first he professed himself so stout.
Then he carried them to Salisbury, through dirt and snow, half the leg deep,
and here they were whipped again.
Among the rest of the spectators, Edward Wharton accidentally passing along that way,
came to be one; and beholding this whipping, one Thomas Broadbury,
clerk of the courts of Salisbury and Hampton, said to him,
'`Edward Wharton, what are you doing here?`'
'`I am here,`' answered he,
'`to see your wickedness and cruelty, that so if you kill these women,
I may be able to declare how you murdered them:`'
for indeed their bodies were so torn,
that if Providence had not watched over them,
they might have been in danger of their lives.
But it fell out so that they were discharged: for the constable at Salisbury,
who must have carried then to Newberry, was desired by one Walter Barefoot,
to make him his deputy, who thus receiving the warrant, set them at liberty;
though John Wheelwright, the priest, advised the constable to drive on,
as his safest way.

These three women being thus unexpectedly released, went to New Quechawanah,
where they had a meeting, and Shubal Drummer, the priest of the place, came also there,
and sat quiet.
And the meeting being ended, he stood up and said, '`Good women, you have spoken well,
and prayed well; pray what is your rule?`'
They answering, '`The Spirit of God is our rule, and it ought to be yours, and all men`'s,
to walk by:`' he replied, '`It is not my rule, nor I hope ever shall be.`'
A clear evidence how prejudice may bias even discreet people;
for being prepossessed thereby, men will speak sometimes rashly,
without considering what.

Not long after these women returned to Dover to visit their friends,
and being in a meeting the next First-day of the week, the constables, Thomas Roberts,
and his brother John, rushed in, and laid hands on Alice Ambrose, as she was in prayer,
and taking her, one by the one arm, and the other by the other,
they dragged her out of doors, almost a mile, with her face towards the snow,
which was near knee deep, over stumps and old trees,
having put on their old clothes on purpose not to dirty their better suits.
They then locked her up in a certain house, and so went back to fetch Mary Tomkins,
whom they dragged in the same manner, which their father, old Thomas Roberts seeing,
lamented, and cried, '`Woe that ever I was father to such wicked children.`'
But they seemed not to matter what their father said, who had been,
a member of the church at Dover above twenty years;
but because he no longer frequented their worship for their degeneracy,
they took away his cow, which with its milk, helped to support him and his wife.
Mary Tomkins being brought into the house where Alice was, Anne Coleman was also fetched.
Next morning they got a canoe, and threatened the women they would now do so with them,
that they should be troubled with them no more;
by which saying they seemed to signify that they
would give them up to the mercy of the sea,
which made the women unwilling to go to the water-side.
Then one Edward Weymouth took Mary by the arms,
and dragged her on her back over the stumps of trees, down a very steep hill,
by which she was much bruised, and often died away.
They also laid hold on Alice, whom they plucked violently into the water,
and kept her swimming by the canoe,
so that she was in danger of being drowned or frozen to death.
Anne Coleman was also rudely dealt with,
and all this in the presence of one Hate-evil Nutwel, a ruling elder,
who stirred up the constables to this wicked action,
and so showed that he bore a wrong name.
But the wicked intention of these men was stopped by a power from on high,
for on a sudden a great tempest arose,
so that they brought the women back again to the house,
and about midnight they turned them all out of doors in the snow,
the weather being so frosty that Alice`'s clothes were frozen like boards.
How barbarously soever these women were treated,
yet the Lord was pleased to preserve and support them.

Afterwards it happened that Anne Coleman and four
of her friends were whipped through Salem,
Boston, and Dedham, by order of William Hawthorn, who before he was a magistrate,
had opposed compulsion for conscience;
and when under the government of Cromwell it was proposed
to make a law that none should preach without license,
he publicly said at Salem, that if ever such a law took place in New England,
he should look upon it as one of the most abominable
actions that were ever committed there,
and that it would be as eminent a token of God`'s having forsaken New England,
as any could be:
and yet afterward this man became a fierce persecutor
of those who asserted liberty of preaching:
though formerly it may be,
if any one had foretold him how he would be given to persecution,
he would have said as Hazael to the prophet Elisha, '`What,
is your servant a dog that he should do this great thing?`'
But to return to Anne Coleman, when she was to be whipped at Dedham,
and fastened to a cart, deputy Bellingham having seen Hawthorn`'s warrant, said,
'`The warrant is firm;`' and then bade the executioner go on; who, thus encouraged,
laid on so severely, that with the knot of the whip he split the nipple of her breast,
which so tortured her, that it had almost cost her her life; and she,
who was a little weakly woman, thinking this would have been her lot, said once,
that if she should happen to die thus,
she was willing that her body should be laid before Bellingham`'s door,
with a charge from her mouth that he was guilty of her blood.

The usage Elizabeth Hooton met with, I cannot pass by in silence, because of her age,
being about sixty, who hearing of the wickedness committed by those of New England,
was moved to make a voyage to America.

In order thereto she went from England in the year 1661,
having one Joan Broksup with her, a woman near as aged as herself,
who freely resolved to be her companion:
and because they could not find a master of a ship
that was willing to carry them to New England,
because of the fine for every Quaker that was brought there,
they set sail towards Virginia,
where they met with a ketch which carried them part of the way,
and then they went the rest by land, and so at length came to Boston.
But there they could not soon find a place of reception,
because of the penalty on those that received a Quaker into their houses.
Yet at length a woman received them.
Next day they went to the prison to visit their friends;
but the jailer altogether unwilling to let them in, carried them to the governor Endicot,
who with much scurrilous language called them witches,
and asked Elizabeth what she came for: to which she answered,
'`To do the will of him that sent me.`'
And he demanding what was that: she replied,
'`To warn you of shedding any more innocent blood.`'
To which he returned that he would hang more yet;
but she told him he was in the land of the Lord, who could take him away first.^
footnote:[Which was fulfilled,
for after that he never took away the lives of any more of those called Quakers.]
This so displeased him, that he sent them to prison,
where many more of their friends were.
After consultation what to do with them,
they were carried two days`' journey into the wilderness, among wolves and bears;
but by Providence they got to Rhode Island, where they took ship for Barbados,
and from there to New England again, and so they returned to Boston.
But then they were put into a ship, which carried them to Virginia,
from which Elizabeth departed to Old England,
where she stayed some time in her own habitation.

But it came upon her to visit New England again; and so she did,
taking her daughter Elizabeth along with her.
And being arrived, those of the magistrates that were present,
would have fined the master of the ship a hundred pounds,
for bringing her over contrary to their law.
But he telling them that Elizabeth had been with the king,
and that she had liberty from him to come there to buy her a house,
this so puzzled these snarling persecutors, that they found themselves at a loss,
and thus were stopped from seizing the master`'s goods.

Elizabeth being come to Boston, notwithstanding the rulers, went to them,
and signified that she came there to buy a house for herself to live in.
She was four times at the court for that purpose, but it was denied her;
and though she said that this denial would give her
occasion if she went to England again,
to lay it before the king, it was in vain, and had no influence upon them.

Departing then, and passing through several places, she came to Cambridge,
and was thrust into a stinking dungeon, where there was nothing to lie down or sit on.
Here they kept her two days and two nights,
without affording her any thing to eat or drink;
and because a certain man in compassion brought her a little milk,
he was also cast into prison and fined five pounds.
Being brought to the court, they ordered her to be sent out of their coasts,
and to be whipped at three towns with ten stripes at each.
So at Cambridge she was tied to the whipping-post, and lashed with ten stripes,
with a three-stringed whip, with three knots at an end.
At Water Town she had ten stripes more with willow rods; and to make up all, at Dedham,
in a cold frosty morning, she received ten cruel lashes at a cart`'s tail.
And being thus beaten and torn,
she was put on horse-back and carried many miles into the wilderness,
and towards night they left her there, where were many wolves, bears,
and other wild beasts, and many deep waters to pass through;
but being preserved by an invisible hand,
she came in the morning into a town called Rehoboth, being neither weary nor faint;
and from there she went to Rhode Island, where coming to her friends,
she gave thanks to God for having counted her worthy,
and enabled her to suffer for his name`'s sake, beyond what her age and sex,
morally speaking, could otherwise have borne.

After some stay there, she returned to Cambridge, about eighty miles,
to fetch her linen and clothes,
which the inhuman persecutors would not allow her
to take with her after they had whipped her.
Having fetched these things, and going back with her daughter and Sarah Coleman,
an ancient woman, she was taken up by the constable of Charlestown,
and carried prisoner to Cambridge; where being asked by one of the magistrates,
whose name was Daniel Goggin, wherefore she came there,
seeing they had warned her not to come there any more:
she answered that she came not there of her own accord, but was forced there,
after she had been to fetch her clothes,
which they would not let her take with her when she was whipped and sent away;
but that now returning back, she was taken up by force out of the highway,
and carried there.
Then the other old woman was asked whether she acknowledged Elizabeth and her religion:
to which she answered, she acknowledged the Truth.
And of Elizabeth`'s daughter he demanded, '`Do you acknowledge your mother`'s religion?`'
To which she was silent: and yet they were sent to the house of correction,
with order to be whipped.
Next morning the executioner came betimes before it was light,
and asked them whether they would be whipped there:
which made Elizabeth ask whether he was come to take away their blood in the dark:
and whether they were ashamed that their deeds should be seen:
but not heeding what she said, he took her downstairs,
and whipped her with a three-stringed whip.
Then he brought down the ancient woman, and did the like to her.
And taking Elizabeth`'s daughter he gave the like to her also, who never was there before,
nor had said or done any thing.
After this Elizabeth the mother was whipped again
at the cart`'s tail at Boston and other places,
where she came to see her friends:
since which I have several times seen her in England in a good condition.

I could relate many more severities of the New England persecutors;
but I long to come to an end, and therefore shall make a large step,
and outrun some space of time.

In the year 1664, it happened that Mary Tomkins and Alice Ambrose came again to Boston,
having been in Virginia, where for their religion they had not only been pilloried,
but whipped also each of them with thirty-two stripes, with a whip of nine cords,
and every cord with three knots; and they were handled so severely,
that the very first lash drew blood, and made it run down from their breasts.
Being afterwards arrived at Boston, Mary grew so sick,
that she was thought to be near death;
which made Edward Wharton with Wenlock Christison come from Salem to visit her.
But after they had been there a little time, two constables came in,
and notwithstanding Mary`'s weak condition, forced them all to the governor`'s house.
Now though Mary seemed to be a little on the mending hand, yet she was so ill,
that she fell down as it were dead in the way.
But one of the constables stayed with her till she came to herself again,
and then brought her before the governor,
where were also deputy Bellingham and Thomas Daufort, one of the magistrates;
who ordered all four of them to be whipped; but because Mary was so weak,
and lest probably she might die under their hands,
they gave order that she and Alice should not be whipped at Boston,
but at the towns beyond.
And this was to have been executed, but that colonel Temple coming in,
interceded and prevailed for three of them.
And now Edward became the mark of their fury, on whom they vented their passion,
though they had nothing to charge him with,
but that he was come from Salem to Boston to visit his sick friend;
and for this pretended crime the following warrant was framed:

[.embedded-content-document.legal]
--

[.letter-heading]
To the constables of Boston, Charlestown, Maiden, and Lynn.

You are required to take into your custody respectively, Edward Wharton,
convicted of being a vagabond, from his own dwelling-place;
and the constable of Boston is to whip him severely
with thirty stripes on his naked body.
And from constable to constable you are required to convey him until he come to Salem,
the place where he says he dwells: and in so doing this shall be your warrant.

[.signed-section-signature]
John Endicot.

[.signed-section-context-close]
Dated at Boston, the 20th of June, 1664.

--

Pursuant to this warrant, Edward, (who therein was called a vagabond,
for no other reason but that he was gone from his
dwelling-place,) was led away to the market place,
and there being stripped, his arms were bound to the wheel of a great gun.
Then the constable John Loel, bade the hangman to do his work severely;
which he did so cruelly that it was testified peas might lie in the holes
that the knots of the whip had made in the flesh of his arms and back.
And his body was swelled and very black from the waist upwards.
Such was the doings of those, who to enjoy the free exercise of their worship,
had left Old England; and thus they treated a man that was of good repute,
and had lived in that country above twenty years;
and was once by the governor himself acknowledged to be his friend,
when he supplied him with necessaries in his need, saying then,
that if ever it lay in his power he would requite him; which now he did,
but in what an inhuman and barbarous manner!
That this governor Endicot once had been a man of but a mean condition,
appears from a letter written to him shortly after the death of Mary Dyer,
by one John Smith, because he had not only caused his wife to be whipped severely,
but had also kept her prisoner a whole winter, separate from her children,
and had been assisting in the making of an order that no
man or woman should bring any thing to the imprisoned Quakers,
or carry any thing from them, upon the penally of five pounds for the first time,
and ten pounds for the second.
In this letter John Smith said:

[.embedded-content-document.letter]
--

O my spirit is grieved for you,
because that the love I did once see in you is departed from you,
and there remains in you a spirit of cruelty, of hard-heartedness to your poor neighbors,
which you have formerly been much beholden to, and helped by, in time of need,
when you had no bread to eat.
O consider of these times, and forget them not,
and of the love you did find among poor people in your necessity,
and how evil you have dealt with, and requited some of them now;
and how you do walk and act contrary to what you did formerly profess: yes,
I have heard you say that all the armies on earth cannot subdue one lust in man or woman.
And now you pronounce sentence of death upon some,
because they cannot submit to your wills, nor worship as you do.

--

But I return to Edward Wharton,
who after his whipping was not led the direct way to Salem, but by Charlestown,
and so about the country, as if they had a mind to make a show of him:
yet at Charlestown the constable was so compassionate,
that he entertained him in his house, and anointed his stripes;
and the next day he was conveyed to his home.
Since that time the said Wharton was whipped again severely;
but I pass by particulars to avoid prolixity.
Yet I cannot forbear to say, that before he was whipped at Boston, as has been said,
it was told him that if he would promise the governor
to come no more to the Quakers`' meeting in Boston,
then it was likely the governor would let him have his liberty: to which Edward returned,
'`Not for all the world.
And friends, I have a back to lend to the smiter,
and I have felt your cruel whippings before now,
and the Lord has made me able to bear them; and as I abide in his fear,
I need not fear what you shall be allowed to do unto me.`'

The case of one Anne Needham being also very remarkable, I will give a short hint of it.
She was fined at Boston for being one of those called Quakers;
but her husband refused to pay the fine, asking them,
seeing the law for adultery was death, whether if his wife had committed adultery,
he must by that law have suffered death.
She then was sentenced to be whipped, which the constable, Thomas Roots,
performed with great cruelty; for seeing she kept silent while he lashed her,
he did whatever he could with his tormenting whip, to make her cry out;
but all his endeavors proved in vain;
which made him say that the Quakers were a hard-hearted people:
though this epithet much better fitted himself,
and all those cruel persecutors that were really
become hard-hearted to the highest decree,
insomuch that they had not only shaken off humanity, but all true sense of piety,
which I shall prove by instances whereof some are even blasphemous.

One Barlow, who formerly had been a preacher at Exeter, afterwards turned lawyer,
and at length being become a marshal,
would boast that when he went to distrain for fines,
he would think what goods were most serviceable to the Quakers,
and then he would take them away.
By such doings he encouraged others to vice;
for a certain Indian taking a knife from an Englishman`'s house,
and being told he should not steal, answered that he himself had thought so,
but now he saw that Barlow and the magistrates did so by the Quakers.
This Barlow in the days of Cromwell being grown rich with the spoils of the innocent,
grew poor after king Charles was restored;
which made Barlow say that he hoped for a good time again:
and took the shameful liberty to add,
he thought the Quakers would not let him be in need.

At Hampton, priest Seaborn Cotton,
understanding that one Eliakim Wardel had entertained Wenlock Christison,
went with some of his herd to Eliakim`'s house,
having like a sturdy herdsmen put himself at the head of his followers,
with a truncheon in his hand.
Wenlock seeing him in this posture, asked him what he did with that club:
to which he answered, he came to keep the wolves from his sheep.
Wen-then asking whether those he led were his sheep, got no answer,
but instead thereof was led away by this crew to Salisbury.
This same Cotton having heard that major Shapleigh was become a Quaker,
said he was sorry for it, but he would endeavor to convert him.
And afterwards drinking in a house in an isle in the river Piscataway,
and hearing the major was there in a warehouse, he went there; but going up stairs,
and being in drink, he tumbled down, and got such a heavy fall,
that the major himself came to help this drunken converter.

When Edward Wharton was told once by governor Endicot,
that every soul ought to be subject to the higher power;
he thereupon asked whether that which set up the golden image,
and required all to fall down and worship it, was the higher power: he answered, '`Yes.`'
Then Edward queried whether the power that required
Daniel to be cast into the lion`'s den,
for praying to any besides the king for thirty days, was the higher power:
the governor said, '`Yes.`'
The next question Edward asked, was,
whether the three children that were cast into the fiery furnace for not falling down to,
and worshipping the golden image, did well:
and whether Daniel for praying to his God contrary
to what the said higher power did command,
did well: the governor replied, '`Yes,`' also.
But secretary Rawson seeing how the governor had talked himself into a noose,
to help him out said, they did obey the higher power by suffering:
to which Edward returned, '`So do we too.`'

Another of these magistrates whose name was Brian Pembleton,
was asked by George Walton and his wife Alice,
who was reputed one of the most godly women thereabout,
what the anointing was which the apostle John exhorted the saints unto in that day:
but what a wicked man this Pembleton was,
may appear by the abominable answer he gave--that John was either a fool or a madman,
or else he did not know what he said.
And blasphemous in a very high degree was what he said to the question,
'`What was that light which shone about Paul?
For his answer was, '`It was the light of the devil for aught he did know.`'

Joshua Scotaway, also one of the magistrates,
asked Mary Thom-kins in the court at Boston, where she dwelt:
to which she answered in the words of the apostle, '`In God; for in him we live and move,
and have a being.`'
To which Scotaway did not hesitate to say, '`So does every dog;and cat.`'
No wonder truly, that men thus darkened in their minds,
grew also quite hardened in persecuting, so as to glory in it; as did Thomas Daufort,
a magistrate of Cambridge, who in the governor`'s house at Boston,
laying his hand on Wenlock Christison`'s shoulder, said to him,
'`Wenlock I am a mortal man, and die I must, and that erelong;
and I must appear at the tribunal seat of Christ,
and must give an account for my deeds done in the body;
and I believe it will be my greatest glory in that day,
that I have given my vote for you to be soundly whipped at this time.`'
This made Wenlock say, '`O wicked man, if you have nothing to glory in that day,
but in drawing the blood of the innocent,
and in laying stripes upon the servants of the living God,
your glory will be turned into shame, and woe will be your portion.`'

But no exhortation, how extraordinary soever,
seemed to take any hold on these persecutors:
for once a girl of thirteen or fourteen years of age, called Hannah Wright,
whose sister had been banished for religion, was stirred with such zeal,
that coming from Long Island, some hundreds of miles from Boston, into that bloody town,
she appeared in the court there,
and warned the magistrates to spill no more innocent blood.
This saying so struck them at first, that they all sat silent;
till Rawson the secretary said, '`What, shall we be baffled by such a one as this?
come, let us drink a dram.`'

Here we see the religion of these men,
who were once so precise that they would not join
with the worship of the church of England.
But it seems not improbable that they fell away to this hardness of heart,
because being convinced in their understandings of some superstitious
ceremonies that were yet remaining in the church of England,
they were not faithful to testify against those things,
and to set their light on the candlestick;
but that to shun the cross and avoid sufferings, they chose to go into a strange country.
And yet they were so presumptuous as to say they were the purest church on earth,
and their magistrates and preachers very godly men,
and it may be some of their cruel executioners seeing how their magistrates,
(as has been said of Thomas Daufort,) did glory in cruelty,
have been foolish enough to persuade themselves that their
excessive whipping was some kind of meritorious work.
But whatever these English people thought, they were worse than others,
for in some places of America lived also Swedes,
who in regard of their worship were no less despised by the English,
than were the old Samaritans by the Jews;
and yet these Swedes entertained the Quakers when they came among them,
far better than the English did:
and thus they made it appear that they surpassed them in life, if not in possession.
But the precise New England-men seemed to place great virtue in a sturdy severity,
of which the following is an instance.

A Dutchman, an Ostender, whose name was John Lawrence, was committed for adultery,
and brought before the court at Boston, where the governor John Endicot,
asked him whether he was guilty or not guilty: to which the prisoner,
who it seems spoke but bad English, said '`No guilt.`'
On which Endicot said in a scoffing manner, '`No gelt;
there`'s no money:`' for gheld signifies money in Dutch.
Thus the Dutchman`'s words and meaning were scoffingly perverted;
and though there was no clear evidence against him, yet he was condemned to be hanged;
but he denying the tact, the execution was deferred; and in the meanwhile the priests,
John Wilson and James Mayo, came to him in prison to see what they could get out ol`' him;
and Mayo told him his time was near at an end, and that he must shortly die:
and therefore he would have him now confess.
To which the prisoner returned, '`What will you have me to confess that which I never did?`'
But Mayo did not desist, but said, '`Confess, my son, and give glory to God.`'
Yet the prisoner continued in denying the charge, and affirmed he was clear.
But, said the priest, '`You cannot be clear; for our Lord and Savior says.
"`Whosoever looks upon a fair woman, and lusts after her,
he has committed adultery with her already in his heart.`"
Truly a very perverse use of the Scripture for compassing a false end.
But the Dutchman seeing how they came to betray him, was cautious, and at length,
after a long and tedious imprisonment, found means to break prison,
and thus escaped from those who grew accustomed to be merciless;
so that sometimes others as well as Quakers, felt the weight of their severity.

As it happened about the time that William Leddra was put to death,
one Elizabeth Nicholson and her two sons, Christopher and Joseph,
were charged with the death of her husband and their father Edmund Nicholson,
who was found dead in the sea;
and information being given that these people did
show love to those they called cursed Quakers,
they were all three fetched from their habitation at Salem and carried to Boston,
and were tried for their lives merely on suspicion;
but nothing of murder was proved against them; yet the mother was fined a great sum,
and her two sons were sentenced to stand under the gallows certain hours,
with ropes about their necks, and to be whipped in the market place,
which was performed accordingly.
And because these young men were not daunted, priest Wilson standing by, said, '`Ah,
cursed generation.`'
And at Salem they were whipped also,
which was done so mercilessly that one of the young men sunk down,
or died away under the torture, though he was raised up and came to life again.

By this we may see how these New England persecutors
were become inured to excessive severity.
But before Heave them, I must also mention the dreadful exit of some of them.

The last act of governor Endicot`'s bloody part that occurs,
was the cruel whipping of Edward Wharton at Boston, related before;
for the time was now come that he must go off the stage,
to give an account of his extravagant severity before
another tribunal than that of his sanguinary court.
The measure of his iniquity was now filled up,
and he was visited with a loathsome disease, insomuch that he stunk alive,
and so died with rottenness,
his name being like to give a bad savor through ages to come.

Yet more remarkable was the death of major-general Adderton,
who when Mary Dyer was hanged, said scoffingly, and in an insulting way,
that she hung as a flag, for others to take example by; and who also,
when Wenlock Christison being condemned to death,
warned the persecutors because of the righteous judgments of God, presumptuously said,
'`You pronounce woes and judgments,
and those that are gone before you pronounced woes and judgments;
but the judgments of the Lord God, are not come upon us as yet.`'
But how he himself was struck by these judgments, and served for an example to others,
we are to see now.

He, upon a certain day, having exercised his soldiers,
and riding proudly on his horse towards his house,
when he came about the place where usually they loosed the Quakers, so called,
from the cart, after they had whipped them, a cow came and crossed the way,
at which his horse taking fright, threw him down so violently, that he died,
his eyes being started out of his head, his brains out of his nose,
his tongue out of his mouth, and his blood out of his ears.
Thus God`'s judgments came upon him suddenly and unaware.

And John Norton, the chief priest of Boston died likewise on a sudden.
It was he who promoted the putting to death of those martyrs that died at Boston,
as has been related;
and when he saw the magistrates paused upon the execution of W. Robinson and M. Stevenson,
he encouraged them thereto, especially because John Winthrop, governor of Connecticut,
earnestly dissuaded the shedding of innocent blood.
He it was also, who when William Brend was beaten so barbarously with a rope,
as has been related in its due place, did not hesitate to say,
since William Brend endeavored to beat their gospel ordinances black and blue,
it was but just upon iiim if he was beaten black and blue also.
But this Norton was now struck with a blow that made him sink:
for having been at his worship house in the forenoon,
and intending to go in the afternoon,
as he was walking in his house he fetched a great groan,
and leaning his head against the mantle tree of the chimney, he was heard to say,
'`The hand, or the judgments of the Lord are upon me.`'
These were his last words, and he sunk down,
and had fallen into the fire if he had not been caught by somebody that was present.
More examples of this nature I could produce, but these may suffice.

What I have related of these cruelties and much more,
was published in print about that time,
that so the king and parliament of England might know what happened there;
for those actions were come in public view, and known there all about the country.
All that they did was to set a false color upon their severity, and to disguise matters:
and it was their happiness that they had not to do with revengeful people,
else they might have been involved in great straits:
but the friends of the persecuted committed vengeance to God;
though some of the great ones in England advised them to sue the persecutors,
which according to law they might have done.

Richard Bellingham, a fierce persecutor, and governor after John Endicot,
went distracted ten years after, and so died.
Not long before, William Coddington, governor of Rhode Island, wrote a letter to him,
wherein he put him in mind of the former times; for he,
(the said Coddington,) had been one of the first erectors of colonies in New England,
and the first that built a house at Boston, and afterwards was a magistrate seven years,
but when persecution arose he declared against it;
and the case was debated three days in the court, but the moderate party was the weakest,
and was opposed by all the priests, except one John Cotton,
who said he remembered how at their departure from England he had preached on Acts 4:11,
and had showed from that text that there was an inward grace which was to be minded,
and that therefore he would not give his vote for
persecuting the asserters of that doctrine;
showing thereby much more sense of religion than the other persecuting priests.
Now though Coddington was one of the greatest merchants or traders in that country,
and in all probability might have acquired great riches there,
yet seeing his good counsel was not hearkened to, he resolved to depart that place,
and to go and live somewhere else.
But whatever he said in his letter to Bellingham,
this man remained hardened like Pharaoh, having showed himself cruel,
even when Mary Fisher and Anne Austin first came to Boston,
where he treated them in a barbarous manner.

Yet one thing remarkable I may mention here, which when I first heard,
I could not fully give credit to;
but thinking it worth the while to make a narrow inquiry into it, I did so,
not only by writing, but also from the mouths of persons that had been eye-witnesses,
or had been informed by such; and from these I got this concurring observation, namely,
that the country about Boston was formerly a very
fruitful soil that produced excellent wheat;
but that since the time this town had been stained with the blood of the Quakers,
so called, no wheat, etc. would grow to perfection within twenty miles,
though the ground had been plowed and sown several times;
for sometimes what was sown was spoiled by vermin or insects; at other times it grew up,
but scarce yielded more than was sown, and so could not countervail the charge;
and in another year the expected harvest was quashed by another accident;
and these disappointments continuing many years,
the people at length grew weary of making further trial, and so left the ground untilled;
notwithstanding that twenty miles off from Boston the soil is fruitful,
and yields very good corn.
But there having been so many reiterated instances of unfruitfulness nearer the town,
ancient people that are alive still, and remember the first times,
generally agree in their opinion that this is a judgment from heaven,
and a curse on the land, because of the shedding of innocent blood at Boston.
This relation I had from so many credible persons,
(though the one knew nothing of the other,
as differing much in time,) yet what they told me did so well agree in the main,
that I could not but believe it, though I do not use to be credulous;
and therefore I have been the more exact in my inquiry,
so that I can no longer question the case;
but it seems to me as a punishment on that blood-thirstiness
which now has ceased long ago.

In the island of Barbados those called Quakers suffered also much by the people,
instigated not a little by the priests, Samuel Graves, Mathew Gray, Thomas Manwaring,
and Francis Smith; for these being often drunk, gave occasion thereby to be reproved:
and one Thomas Clark coming once into the place of public worship,
and exhorting the auditors to desist from lewdness, and to fear God,
was so grievously beaten with sticks, that he fell down in a swoon;
and Graves who had preached then, went to the house of the said Clark,
pulled his wife out of doors, and tore her clothes from her back.
And Manwaring, who had threatened Clark that he would procure a law to be made,
by which his ears should be cut off, once wrote in a letter to him,
'`I am sorry that your zeal surpasses your moderation,
and that a club must beat out of you what the devil has inspired.
And this was because Clark had told him that his
conduct was not becoming a minister of the Gospel.
Other rough treatment Clark met with I pass by,
though once he was set in the stocks and imprisoned.
But now I leave America, and return to England.
