== Chapter XIII.

=== 1662.

[.chapter-synopsis]
* Severe Persecution throughout Great Britain
* Cruelty practised on Friends in London
* Alderman Brown
* Attempts to prevent Friends holding their meetings
* Arrests and imprisonment without warrant
* Boys sent to Bridewell
* Cruelty to D. Baker
* Prisoner beaten in open court
* Barbarous conduct of R. Brown
* Testimony of F. Howgill respecting the continuance of the Society of Friends
* Persecution in Southwark
* Trial and sentence of several Friends there
* Trial of J. Crook
* Indictment
* Sentence of Premunire
* The Quaker Cobler
* Condition of Friends confined in Newgate
* An Impostor
* Thos. Ellwood
* Richard Hubberthorn dies in prison

Having now left America, and being returned to England,
let us go and see the state of persecution at London, where desperate fury now raged;
though it was not in that chief city alone the Quakers, so called,
were most grievously persecuted:
for a little before this time there was published in print
a short relation of the persecution throughout all England,
signed by twelve persons,
showing that more than four thousand and two hundred of those called Quakers,
both men and women, were in prison in England;
and denoting the number of them that were imprisoned in each county,
either for frequenting meetings, or for denying to swear, etc.
Many of these had been grievously beaten, or their clothes torn or taken away from them;
and some were put into such stinking dungeons, that some great men said,
they would not have put their hunting dogs there.
Some persons were crowded full both of men and women,
so that there was not sufficient room for all to sit down at once;
and in Cheshire sixty-eight persons were in this manner locked up in a small room;
an evident sign that they were a harmless people, that would not make any resistance,
or use force.
By such ill-treatment many grew sick, and not a few died in such jails;
for no age or sex was regarded, but even ancient people of sixty, seventy,
and more years of age, were not spared: and the most of these being tradesmen,
shopkeepers, and husbandmen, were thus reduced to poverty;
for their goods were also seized, for not going to church,
(so called,) or for not paying tithes.
Many times they were made to lie in prison on cold nasty ground,
without being allowed to have any straw;
and often they have been kept several days without food:
no wonder therefore that many died by such hard imprisonments as these.

At London, and in the suburbs,
were about this time no less than five hundred of those called Quakers, imprisoned,
and some in such narrow holes, that every person scarcely had convenience to lie down;
and the felons were allowed to rob them of their clothes and money.
Many that were not imprisoned,
nevertheless suffered hardships in their religious meetings, especially that in London,
known by the name of Bull and Mouth.
Here the trained bands came frequently, armed generally with muskets, pikes,
and halberds, and conducted by a military officer, by order of the city magistracy;
and rushing in, in a very furious manner, fell to beating them,
whereby many were grievously wounded, some fell down in a swoon,
and some were beaten so violently, that they lived not long after it.
Among these was one John Trowel, who was so bruised and crushed,
that a few days after he died.
His friends therefore thought it expedient to carry the corpse into the aforesaid meeting-place,
that it might lie there exposed for some hours, to be seen of everyone.
This being done, raised commiseration and pity among many of the inhabitants;
for the corpse, beaten like a jelly, looked black, and was swelled in a direful manner.
This gave occasions to send for the coroner, and he being come,
impanelled a jury of the neighbors, and gave them in charge, according to his office,
to make true inquiry upon their oaths,
and to present what they found to be the cause of his death.
They viewing the corpse, had a surgeon or two with them,
to know their judgment concerning it; and then going together in private,
at length they withdrew without giving in their verdict,
only desiring the friends to bury the corpse, which was done accordingly that evening.
And though the coroner and jury met several times together upon that occasion,
and had many consultations, yet they never would give in a verdict;
but it appeared sufficiently, that the man was killed by violent beating.
The reasons some gave for the suspense of a verdict were,
that though it was testified that the same person, now dead,
was seen beaten and knocked down; yet it being done in such a confused crowd,
no particular man could be fixed upon, so that any could say, that man did the deed.
And if a verdict was given that the deceased person was killed,
and yet no particular person charged with it,
then the city was liable to a great fine at the pleasure of the king,
for conniving at such a murder in the city in the daytime, not committed in a corner,
but in a public place, and not apprehending the murderer, but allowing him to escape.
In the meanwhile the friends of the deceased were
not lacking to give public notice of the fact,
and sent also a letter to the lord mayor, which afterwards they gave out in print,
together with a relation of this bloody business.
In this letter it was said, '`It may be supposed you have heard of this thing,
for it was done not in the night, but at the mid-time of the day; not suddenly, unaware,
or by mishap, but intendedly, and a long space of time a doing; and not in a corner,
but in the streets of the city of London;
all which circumstances do highly aggravate this murder,
to the very shame and infamy of this famous city, and its government.`'

A certain person who spread some of these printed relations,
was imprisoned for his pains; nevertheless another brought one of them to the king,
and told him how the thing had been done; at which the king said,
'`I assure you it was not by my advice that any of your friends should be slain:
you must tell the magistrates of the city of it, and prosecute the law against them.`'
This saving of the kins; was not long after also published in print:
but violence prevailed still;
for the person that was apprehended for spreading the said books, was sent to prison,
by the special order of Alderman Brown, of whom,
since mention may be made several times in this work,
it gives me occasion to say something of what kind of man he was.

In the time of Cromwell he had been very fierce against the royalists,
especially at Abington, not far from Oxford;
for this error he endeavored now to make compensation
by violently persecuting the harmless Quakers;
otherwise he was a comely man, and could commit cruelty with a smiling countenance.
But more of his actions may be represented hereafter.

The Quakers, so called, seeing that they could not obtain justice,
let the matter of the murdered persons alone; for suffering was now their portion,
and therefore they left their cause to God.
Oftentimes they were kept out of their meetinghouses by the soldiers;
but then they did not use to go away, but stood before the place,
and so their number soon increased;
and then one or other of their ministers generally stepped upon a bench,
or some high place, and so preached boldly.
Thus he got sometimes more hearers than otherwise he might have had.
But such a one sometimes was soon pulled down,
which then gave occasion for another to stand up and preach,
and thus often four or five one after another, were taken away, as innocent sheep,
and carried to prison with others of their friends, it may be forty or fifty at once.
This puts me in mind of what I heard my mother Judith Zinspenning say,
who in the year next following being gone for England, with William Caton and his wife,
who lived at Amsterdam, to visit her friends there, and coming to London,
went with others to the Bull and Mouth meeting; but entrance being denied,
they stayed in the street, where she saw one preacher after another pulled down,
at the instant cry of some officer or other, '`Constable, take him away.`'
Several being thus led away, the constable came also to her,
and perceiving by her dress that she was a Dutch woman, pulled her by the sleeve,
and said with admiration, '`What a Dutch Quaker!`' but meddled no further with her.
This keeping of meetings in the streets became now a customary thing in England;
for the Quakers, so called,
were persuaded that the exercise of their public
worship was a duty no man could discharge them from,
and they believed that God required the performing of this service from their hands.
And by this meeting in the streets, it happened sometimes that more than one, no,
it may be three or four at a time, did preach, one in one place, and another in another,
which in their meeting places could not have been done conveniently.
But thus they got abundance of auditors, and among these sometimes eminent men,
who passing by in their coaches, made their coachmen stop.
At this rate they found there was a great harvest,
and thus their church increased under sufferings;
and in those sharp times they were pretty well purified of dross,
since the trial was too hot for such as were not sincere:
for by frequenting their meetings in such a time, one was in danger of being imprisoned,
or beaten lame, or unto death; but this could not quench the zeal of the upright.

Now the taking away of one preacher, and the standing up of another,
became an ordinary thing in England, and it lasted yet long after,
as I myself have been an eye-witness of there.
And when there were no more men preachers present, it may be a woman would rise,
and minister to the meeting; no, there were such,
who in years being little more than boys, were endued with a manly zeal,
and encouraged their friends to steadfastness.
In the meanwhile many also were imprisoned, without being hauled out of their meetings;
for some have been apprehended for speaking only something on the behalf of their friends;
as Rebecca Travers, who, going to the lieutenant of the Tower,
desired him to have compassion on some who were imprisoned for frequenting of meetings.
But he grew angry at this; and when she went away,
one of the keepers gave her ill language: on which she exhorting him,
to be good in his place, while it was the Lord`'s will he had it, he was so offended,
that going back to the lieutenant, he complained that she had spoken treason,
and thereupon she was apprehended, and sent to prison.
No, the rude soldiers were encouraged to cruelty by officers who were not a whit better,
for they themselves would sometimes lay violent hands on peaceable people;
as among the rest of the aforementioned, alderman Richard Brown,
who formerly had been a major-general under Cromwell,
and now behaved himself with such outrageous fierceness,
that even the comedians did not hesitate to expose him, by an allusion to his name Brown,
and saying, '`The devil was brown.`'

A book was also printed, wherein many base abuses,
and also his furious behavior were exposed to public view;
and this book was dedicated to him with this small epistle:

[.embedded-content-document.letter]
--

[.salutation]
Richard Brown,

If you are not sealed up already for destruction,
and if repentance be not utterly hid from your eyes, the Lord convert you,
and forgive you all your hard and cruel dealings towards us:
we desire your repentance rather than your destruction;
and the Lord God of heaven and earth give judgment
of final determination between you and us,
that all the earth may know whether your cause against us,
or our cause be just before him, who only is the righteous judge.

--

The said book, though published without the author`'s name,
yet one of them was not only sent to Brown, but as a sign that the Quakers, so called,
approved it, others were, by about thirty of them, delivered to the lord mayor,
and the sheriffs of London, that so they might know what was acted under their authority;
for some, though not authorized, yet being favorites at court,
made bold to act against the Quakers whatever their malice prompted them to.
Among these was one Philip Miller, who, though not an officer,
yet in the month called May of this year, came into a meeting of the said people,
in John`'s street, in the parish of Sepulchres, at London, without any order or warrant,
and having a cane in his hand,
commanded the rabble who attended him to secure whom he pleased;
and then he fetched a constable, whom he forced by his threats to go along with him,
and five persons he apprehended, among whom was John Crook,
of whom further mention is like to be made again.
Some days after, this Miller came to the said meeting place again,
and struck several persons with his cane, because they would not depart at his command;
and then he charged the constables, whom he brought along with him,
to secure and take into custody whom he pleased.

About the latter end of the aforesaid month, on a First-day of the week,
one captain Reeves, and some soldiers with muskets and drawn swords,
came violently rushing into the Bull and Mouth meeting,
where they pulled down him that was preaching, and presently laid hold of another,
who desired Reeves to show his order for this his doing: to which he answered,
he would not in that place; but it appeared afterwards that he could not,
as having no warrant.
Yet he caused his soldiers to take away about forty persons,
(some of whom were not at the meeting,
but had been taken up in the streets,) and have them into Paul`'s yard,
where they were kept till the public worship was ended there;
and then alderman Richard Brown came into the place where the prisoners were guarded,
and with great rage and fury laid hands first on a very aged person,
and pulled him down twice by the brim of his hat, whereby he lost it.
Then he served another in like manner,
and a soldier struck this person a great blow with a pistol on his bare head:
two others Brown used in the like manner, and then he sent them all to Newgate,
guarded by soldiers.

The same day some soldiers came to a meeting in Tower street, and without any warrant,
took away twenty-one persons, called Quakers, and carried them to the Exchange,
where they kept them some time, and then brought them before the said Richard Brown,
who in a most furious manner struck some, and kicked others;
which made one of the prisoners, seeing how Brown smote one with his fist on the face,
and kicked him on the shin, say, '`What Richard, will you turn murderer?
You did not do so when I was a soldier under your command at Abingdon,
and you command me with others, to search people`'s houses for pies and roast meat,
because they kept Christmas as a holy time;
and we brought the persons prisoners to the guard, for observing the same.`'
For such a precise man the said Brown was at that time,
that he pretended to root out that superstitious custom;
though there is reason to question, whether his heart were sincere in this respect:
however, such blind zeal was unfit to convince people of superstition;
and Brown well knowing that by his former carriage,
he had very much disobliged those of the church of England,
endeavored now to make amends for it,
by his fierce brutality against the harmless Quakers,
and so to come into favor with the ecclesiastics and courtiers.
One of Brown`'s family having heard what was said to him, replied,
'`There is an Abingdon bird.`'
To which Brown, returned,
'`He is a rogue for all that,`' and struck him with his fist under the chin;
which made another prisoner say, '`What,
a magistrate and strike!`' Upon which Brown with both his
hands pulled him down to the ground by the brim of his hat,
and then commanded the soldiers to take them all away, and carry them to Newgate.

Upon a First-day of the week, in the month called June,
a company of soldiers came into the Bull and Mouth meeting, with pikes, drawn swords,
muskets, and lighted matches, as if they were going to fight;
though they knew well enough they should find none there but harmless people.
The first thing they did was to pull down him that preached,
whom they hauled out of the meeting,
rejoicing as if they had obtained some great victory:
then they brought him to the main guard at Paul`'s, and returned to the Bull and Mouth,
where they apprehended some more, whom they also carried to Paul`'s. After some hours,
these prisoners were carried to the house of the fore-mentioned Brown, and he,
asking the names of the prisoners, and hearing that of John Perrot, said, '`What,
you have been at Rome to subvert,`' but recalling himself, said, to convert the Pope.`'
On which Perrot told him,
'`He had suffered at Rome for the testimony of Jesus.`' Whereupon Brown returned,
'`If you had converted the Pope to your religion,
I should have liked him far worse than I do now`'.`' To which Perrot replied,
'`But God would have liked him better.`'
After some more short discourse, Brown committed them all to Newgate.

After this manner, the meetings of those called Quakers were disturbed at that time,
of which I could produce, if necessary, many more instances.
Once, one Cox, a wine-cooper, came with some soldiers into a meeting, where,
after great violence used, they took up two men of those called Quakers,
whom they beat most grievously, because they refused to go along with them,
though they showed no warrant fur it.
At length the soldiers carried them both upon muskets into Paul`'s yard,
and when they laid them down, they dragged one of them by the heels on his back,
in a very barbarous manner; which being done, the said wine-cooper was heard to say,
he would go and get a cup of sack, for these devils had even wearied him out:
and yet he went to another meeting-place of these people,
where he also behaved himself very wickedly; and being asked for his order,
his answer was holding out his sword, this is my order.
Thus it seems he would ingratiate himself with Brown, who now being in favor at court,
was knighted, and sometime after also chosen lord mayor of London;
and by his furious behavior,
the soldiers were also encouraged to commit all manner of mischief; insomuch,
that being asked, what order they had for their doings, one lilting up his musket, said,
'`This is my order:`'so that things now were carried by a club-law.
Nor did the soldiers respect age, but took away out of a meeting at Mile-end, two boys,
one about thirteen and the other about sixteen:
and they were brought before the lieutenant of the Tower, who to one present, saying,
he supposed they were not of the age of sixteen years,
and then not punishable by the act, returned, they were old enough to be whipped;
and they should be whipped out of their religion.
And so he sent them to Bridewell, where their hands were put into the stocks,
and so pinched for the space of two hours, that their wrists were much swollen;
and this was done because they refused to work,
as being persuaded that they had not deserved to be treated so;
they also eating nothing at the charge of the said workhouse.
These lads, though pretty long in that prison, yet continued steadfast,
rejoicing they were counted worthy to suffer for the name of the Lord:
and they wrote a letter to their friends`' children,
exhorting them to be faithful in bearing their testimony for the Lord,
against all wickedness and unrighteousness.

Some days before this time, Thomas and John Herbert, living in London,
and other musketeers, came with their naked swords into some private dwellings,
and broke two or three doors; (for when some persons were seen to enter a house,
though it was only to visit their friends,
it was called a meeting.) Now it happened in one house,
these rude fellows found five persons together, one of whom was William Ames,
who was come there out of Holland, and another was Samuel Fisher:
and when it was demanded what warrant they had, they held up their swords, and said,
'`Do not ask us for a warrant; this is our warrant.`'
And thereupon they took away these persons by force, and carried them to Paul`'s yard,
where they were a laughing-stock to the soldiers;
and from there they were brought to the Exchange,
where they met with no better reception from the rude soldiers;
and from there they were conducted to alderman Brown`'s house in Ivy-lane.
He seeing these prisoners, sent them to Bridewell with a court order,
to be kept at hard labor.
But afterwards bethinking himself,
and '`finding that his court order was not founded on justice,
(for these persons were not taken from a meeting,)
next morning he sent another court order,
wherein they were charged with unlawful assembling themselves to worship.
Now, suppose one of the musketeers had heard any of these persons speak
byway of exhortation to faithfulness in this hot time of persecution,
this would have been taken for a sufficient charge, though not cognizable by law:
but they ran upon shifts, how poor or silly soever.

Thus these persons were committed to Bridewell, and required to beat hemp;
and they were treated so severely, that W. Ames grew sick, even nigh to death,
wherefore he was discharged; for in a sense it might be said,
that his dwelling-place was at Amsterdam in Holland,
since he was there the most part of the time for some years successively,
and that he might not be chargeable, he worked at wool-combing;
and it being alleged that he was of Amsterdam,
it seems they would not have him die in prison, as some of his friends had done.
The others having been six weeks in Bridewell,
were presented at the sessions in the Old Bailey:
but instead of being tried for what was charged against them,
they were required to take the oath of allegiance, as the only business,
(according to what the deputy recorder said,) they were brought there for.
The prisoners then demanded, that the law might be read,
by virtue of which the said oath was required of them.
This was promised by the court to be done; but instead thereof,
they ordered the clerk to read only the form of the oath,
but would not permit the law for imposing it to be read.
But before the prisoners had either declared their willingness to take it,
or their refusal of it, they were commanded to be taken away;
which the officers did with such violence, that they threw some of them down upon stones.
This made Samuel Fisher say, '`Take notice people,
that we have not yet refused to take the oath;
but the court refused to perform their promise which
they made but just now before you all,
that this statute for it should be read: if such doings as this ever prosper,
it must be when there is no God.`'
But this was not regarded; and the prisoners, without any justice were sent to Newgate.
Among these, was also one John Howel,
who had been sent by alderman Brown to work at Bridewell,
because he being brought before him, did not tell on a sudden what was his name:
and being demanded in the court why he did not tell his name, he answered,
because he had been beaten and abused in the presence of Richard Brown,
when he was brought before him.
Brown, who was also on the bench, asked him roughly, '`Wherein were you abused?`'
And Howel replied, '`Blood was drawn on me in your presence;
which ought not to be done in the presence of a justice of peace.`'
But Brown growing very impetuous, returned,`' Hold your prating,
or there shall be as much done again here in the presence of the court.`'

About midsummer, Daniel Baker returned into England, (who, as has been related,
had been at Malta,) and about a fortnight after his arrival, he, with four others,
were taken by a band of soldiers from the Bull and Mouth meeting,
and carried to Paul`'s yard, where having been kept for some hours,
they were brought to Newgate; but in the evening they were had before alderman Brown,
to whom Baker with meekness said,
'`Let the fear of God and his peace be set up in your heart.`'
But Brown fell a laughing, and said,
'`I would rather hear a dog bark;`' and using more such scoffing expressions,
he charged Baker, etc. with the breach of the king`'s law in meeting together.
To which Baker said, '`The servants of God in the apostles`' days,
were commanded to speak no more in the name of Jesus; and they answered, and so do I too,
whether it be better to obey God than men, judge you.`'
He also instanced the case of the three children at Babylon,
and Daniel who obeyed not the king`'s decrees.
But Brown grew so angry, that he commanded his men to smite Daniel on the face.
This they did, and pulling him four or five times to the ground,
they smote him with their fists, and wrung his neck so,
as if they would have murdered him.
This these fellows did to please Brown, showing themselves to be ready for any service,
how abominable soever.
And Baker reflecting on his travels, signified,
that even Turks and heathens would abhor such brutish actions.
His fellow-prisoners were also abused by Brown, and then sent to Newgate again.
And after some days, they were called to the sessions, where their indictment was read,
which like others in such cases, did generally run in these terms: that the prisoners,
under pretense of performing religious worship,
otherwise than by the laws of the kingdom of England established,
unlawfully and tumultuously did gather and assemble themselves together,
to the great terror of his majesty`'s people,
and to the disturbance of the peace of the king, in contempt of our said lord the king,
and his laws, to the evil example of all others in the like case offending, etc.
The indictment being read, no witness appeared against the prisoners, save Brown,
who sat on the bench: and therefore the oath, as the ordinary snare,
was tendered to them; for it was sufficiently known,
that their profession did not allow them to take any oath.
They denying to swear, were sent back to prison,
to stay there until they should have taken the oath.

If I would here set down all such like cases as have happened,
I might find more work than I should be able to perform:
for this vexing with the oath was become so common,
that some have been taken up in the streets, and brought to a justice of the peace,
that he might tender the oath to them, and in case of denial, send them to prison,
though this was directly contrary to the statute of Magna Charta, which expressly says,
'`No freeman shall be taken or imprisoned, or be disseized of his freehold or liberties,
but by the law of the land.`'
But this was not regarded by Richard Brown, who did whatever he would;
for force and violence were now predominant:
and sometimes when the prisoners were brought to the bar, for frequenting meetings,
freedom was denied to them to justify themselves;
but to be hectored and baffled was their lot.

Once it happened, that a prisoner, who had been a soldier formerly under Brown,
seeing that no justice or equity was observed, called to him, saying,
'`That he was not fit to sit on the bench;
for he made the son to hang the father at Abingdon;
so that he could prove him to be a murderer.`'
This bold saying caused some disturbance in the court, and Brown,
how heavy soever the charge was, did not deny the thing in court,
nor clear himself from it:
yet the other Quaker prisoners did not approve this upbraiding, but signified,
that though the fact were true,
yet they were not for reproaching any magistrate upon the bench,
whose place and office they did respect and honor.
But I do not find that Brown,
(on that account,) ever prosecuted him that spoke so boldly,
although otherwise he did whatever he would, without fearing that his fellow-magistrates,
(who respected him that was a favorite at court,) would disclaim it,
as may appear by this following instance.

A certain person who had been in a very violent and abusive
manner taken to prison by the soldiers out of a meeting,
because he was not willing to go, said in the court, that his refusing to go,
was because they would not show him any warrant for their apprehending him:
since for aught he knew, they might be robbers or murderers,
with whom he was not bound to go.
But Brown, who was for violence, said to this,
if they had dragged him through all the kennels in the street, they had served him right,
if he would not go.
This he spoke in such a furious manner, that one of the prisoners told him,
'`You have had many warnings and visitations in the love of God, but have slighted them;
therefore beware of being sealed up in the wrath of God.`'
Hereupon one of the jailers can)e with his cane and
struck several of the prisoners so hard,
that several of them were much bruised; and it was reported by some,
that Brown cried knock him down, though others,
(for mitigating it a little,) would have it, pull him down.
But the former seems most probable: for the blows were so violent,
that some of the spectators cried out, murder! murder! and asked,
'`Will you allow men to be murdered in the court?`'
Whereupon one of the sheriffs in person came down from his seat to stop the beating.
But Brown was so desperately filled with anger, that he said to the prisoners,
'`If any of you be killed,
your blood shall be upon your own head:`' and the
hangman standing by with his gag in his hand,
threatened the prisoners to gag any of them that should speak any thing.
Thus innocence was forced to give way to violence.
And once, when one at the common juridical question, guilty, or not guilty, answered,
I deny I am guilty, and I can say I am not guilty; and also in Latin, _non reus sum._
Yet he was sentenced as mute, and fined accordingly, though the words he spoke,
fully signified not guilty, albeit he had not expressed them in the same terms.
But now they were for crossing the Quakers in every respect.

I will yet mention some more instances of Brown`'s brutality, before I leave him.
Another being demanded to answer to his indictment, guilty, or not guilty,
and not presently answering, but thinking a little what to speak safely.
Brown scoffingly said, '`We shall have a revelation by and by.`'
To which the prisoner said, '`How long will you oppose the innocent?
How long will you persecute the righteous seed of God?`'
But while he was speaking,
Brown indecently began to cry in the language of
those wenches that go crying up and down the streets,
'`Aha, aha, Will you have any wall-fleet oysters?`'
And, '`have you any kitchen-stuff, maids?`'
And when a prisoner at the bar said he could not for conscience-sake
forbear meeting among the people of God,
Brown scurrilously returned, '`Conscience,--a dog`'s tail.`'
And when alderman Adams speaking to one of the prisoners said,
'`I am sorry to see you here.`'
'`Sorry!`' said Brown, '`What should you be sorry for?
'`Yes,`' said Adams, '`He is a sober man.`'
But Brown, who could not endure to hear this, replied,
that there never was a sober man among them, meaning the Quakers.
The spectators, who took much notice of him, dis-commended this his carriage exceedingly.
But he seemed to be quite hardened;
for at a certain time two persons being upon their trial for robbing of a house,
he told them, they were the veriest rogues in England, except it were the Quakers.

Sometimes it happened that the prisoners were brought to the bar without being indicted;
and when they said, '`What have we done?`'
and desired justice; Brown, having no indictment against them, often cried,
'`Will you take the oath?`'
And they then saying, '`that for conscience-sake they could not swear,
were condemned as transgressors,
though such proceedings as these were directly against the law.
But this seemed at that time little to be regarded.

However, sometime before, it happened at Thetford in the county of Norfolk,
that judge Windham, at that time showing himself just in the like case,
sharply reproved the justices upon the bench,
for having not only committed some persons to prison, but also had them up to the bar,
when no accuser appeared against them.
But Richard Brown did whatever he would, and showed himself most furiously wicked,
when any prisoner was brought before him with his hat on.

One John Brain, being taken in the street, and not in any meeting,
was brought by some soldiers before Brown; who, seeing him with his hat on,
ordered him to be pulled down to the ground six or seven times, and when he was down,
they beat his head against the ground, and stamped upon him; and Brown, like a madman,
bade them pull off his nose; whereupon they very violently pulled him by the nose.
And when he got up, they pulled him to the ground by the hair of his head,
and then by the hair pulled him up again.
And when he would have spoken in his own behalf against this cruelty,
Brown bade them stop his mouth.
Whereupon they not only struck him on the mouth,
but stopped his mouth and nose also so close, that he could not draw breath,
and was like to be choked: at which actions Brown fell a laughing,
and at length sent him to jail.

Thomas Spire, being brought before Brown, he commanded his hat to be taken off;
and because it was not done with such violence as he intended,
he caused it to be put upon his head again, saying,
'`It should not be pulled off so easily.`'
Then he was pulled down to the ground by his hat, and pulled up again by his hair.
William Hill being brought before him, he commanded his hat to be pulled off,
so that his head might be bowed down: whereupon he being pulled to the ground,
was plucked up again by the hair of his head.
George Ableson was thus pulled five times one after another to the ground,
and plucked up by his hair, and so beaten on his face, or the sides of his head,
that he staggered, and bled, and for some days was under much pain.

Nicholas Blithold being brought before Brown, he took his hat with both his hands,
endeavoring to pull him down to the ground;
and because he fell not quite to the ground forwards, he pushed him,
to throw him backwards; and then he gave him a kick on the leg,
and thrust him out of doors.
Thomas Lacy being brought before him, he himself gave him a blow on the face;
and Isaac Merrit, John Cook, Arthur Baker, and others, were not treated much better;
so that he seemed more fit to have been hangman, than an alderman, or justice.
But I grow weary of mentioning more instances of his cruelty.
These his abominable achievements were published in print,
more at large than I have mentioned them: and the book, as has been said already,
was dedicated to him.
And yet I do not find any have been prosecuted on that account;
though his wickedness was extravagant,
and such as if he needed to have stakes erected at Smith field to vend his wood;
being by trade a wood-monger.

In this hot time of persecution, Francis Howgill wrote,
and gave forth the following paper for encouragement of his friends.

[.embedded-content-document.paper]
--

The cogitations of my heart have been many, deep, and ponderous some months, weeks,
and days,
concerning this people which the Lord has raised to bear testimony unto his name,
in this the day of his power; and intercession has been made often for them to the Lord,
and a patient waiting to know his mind concerning them for the time to come;
which often I received satisfaction in as to myself,
but yet something I was drawn by the Lord to wait for,
that I might comfort and strengthen his flock by an assured testimony.
And while I was waiting out of all visible things,
and quite out of the world in my spirit, and my heart upon nothing but the living God,
the Lord opened the springs of the great deep,
and overflowed my whole heart with light and love;
and my eyes were as a fountain because of tears of joy, because of his heritage,
of whom he showed me, and said unto me in a full, fresh, living power, and a holy,
full testimony, so that my heart was ravished there with joy unspeakable,
and I was out of the body with God in his heavenly paradise,
where I saw and felt things unutterable, and beyond all demonstration or speech.
At last the life closed with my understanding, and my spirit listened unto him;
and the everlasting God said,
"`Shall I hide any thing from them that seek my face in righteousness?
No, I will manifest it to them that fear me; I will speak, do you listen,
and publish it among all my people, that they may be comforted, and you satisfied.`"
And thus said the living God of heaven and earth, upon the 28th of the Third month, 1662.

'`The sun shall leave its shining brightness, and cease to give light to the world;
and the moon shall be altogether darkness, and give no light unto the night;
the stars shall cease to know their office or place; my covenant with day, night, times,
and seasons, shall sooner come to an end, than the covenant I have made with this people,
into which they are entered with me, shall end, or be broken.
Yes, though the powers of darkness and hell combine against them,
and the jaws of death open its mouth, yet I will deliver them, and lead them through all.
I will confound their enemies as I did in Jacob,
and scatter them as I did in Israel in the days of old.
I will take their enemies, I will hurl them here and there, as stones hurled in a sling;
and the memorial of this nation, which is holy unto me, shall never be rooted out,
but shall live through ages, as a cloud of witnesses, in generations to come.
I have brought them to the birth, yes, I have brought them forth; I have swaddled them,
and they are mine.
I will nourish them, and carry them, as on eagles`' wings;
and though clouds gather against them, I will make my way through them;
though darkness gather together on a heap, and tempests gender,
I will scatter them as with an east wind; and nations shall know they are my inheritance,
and they shall know I am the living God,
who will plead their cause with all that rise up in opposition against them.`'

These words are holy, faithful, eternal, good, and true;
blessed are they that hear and believe unto the end:
and because of them no strength was left in me for a while;
but at last my heart was filled with joy,
even as when the ark of God was brought from the house of Obed-Edom,
when David danced before it, and Israel shouted for joy.

[.signed-section-signature]
Francis Howgill.

--

That this writing of F. Howgill, who was a pious man, of great parts,
together with many other powerful exhortations of such who valiantly went before,
and never left the oppressed flock,
tended exceedingly to their encouragement in this hot time of persecution, is certain.
For how furious soever their enemies were,
yet they continued faithful in supplications and fervent prayers to God,
that he might be pleased to assist them in their upright zeal,
who aimed at nothing for self, but from a true fear and reverence before him,
dared not omit their religious assemblies.
And they found that the Lord heard their prayers,
insomuch that I remember to have heard one say,
that at a meeting where they seemed to be in danger of death from their fierce persecutors,
he was as it were ravished, so that he hardly knew whether he was in or out of the body.
They then persevering thus in faithfulness,
to what they believed the Lord required of them, in process of time,
when their enemies had taken such measures,
that they were persuaded they had found out such means,
by which they should suppress and extinguish the Quakers,
they saw the Lord God Almighty rose up in their defense,
and quashed and confounded the wicked devices of their cruel persecutors,
as will be seen in the course of this history.

In the meanwhile let us take a view of the persecution in Southwark.
Here the Quakers`' meetings were no less disturbed than in London.
Several persons having been taken from their religious meetings, were committed;
and after having been in White-lion prison about nine weeks, were brought to the bar,
where Richard Onslow sat judge of the sessions.
The indictment drawn up against them was as follows.

[.embedded-content-document.legal]
--

The jurors for our lord the king do present upon their oath, that Arthur Fisher,
late of the parish of St. Olave, in the borough of Southwark, in the county of Surry,
yeoman; Nathaniel Robinson, of the same, yeoman; John Chandler, of the same, yeoman;
and others, being wicked, dangerous, and seditious sectaries, and disloyal persons,
and above the age of sixteen years, who on the 29th day of June,
in the year of the reign of our lord Charles the Second, by the grace of God,
king of England, Scotland, France, and Ireland, etc. the fourteenth,
have obstinately refused, and every one of them has obstinately refused,
to repair unto some church, chapel, or usual place of common prayer,
according to the laws and statutes of this kingdom of England,
in the like case set forth and provided,
(after forty days next after the end of the session of parliament,
begun and held at Westminster, on the 29th day of February,
in the year of our lady Elizabeth, late queen of England, the thirty-fifth,
and there continued until the dissolution of the same, being the tenth day of April,
in the 35th year above-said.) Namely, on the 3rd day of August,
in the year of the reign of the said Charles, King of England, the fourteenth above-said,
in the parish of St. Olave aforesaid, in the borough of Southwark aforesaid,
in the county aforesaid, of themselves, did voluntarily and unlawfully join in,
and were present at an unlawful assembly, conventicle, and meeting,
at the said parish of St. Olave, in the county aforesaid,
under color and pretense of the exercise of religion,
against the laws and statutes of this kingdom of England,
in contempt of our said lord the king that now is, his laws,
and to the evil and dangerous example of all others in the like case offending
against the peace of our said lord the king that now is,
his crown and dignity,
and contrary to the form of the statute in this same case set forth and provided.

--

I have inserted this indictment,
that the reader may see not only the manner of proceeding,
but also with what black and heinous colors the religious meetings of those called Quakers,
were represented.
This indictment being read,
the prisoners desired that they might be tried by
the late act of parliament against conventicles.
But it was answered, they might try them by what they would that was in force.
Then the prisoners desired that the statute, (that is,
the 35th of Elizabeth,) might be read.
This was done but in part, and it was said to the clerk, it was enough.
The prisoners said then, that that act was made in the time of ignorance,
when the people were but newly stepped out of popery;
and they showed also how unjustly they were dealt with.
Then being required to plead guilty, or not guilty, to the indictment,
some who were not very forward to answer, were hauled out of the court,
as taken _pro confessi_ (Enlglish: having confessed), and so sent back to prison.
The rest, being twenty-two in number, pleaded not guilty.
Then the jurymen were called, and when they had excepted against one,
the judge would not allow it,
because he did not like the reason they gave--that they saw envy, prejudice,
and a vain deportment in him.
Another was excepted against, because he was heard to say, that he hoped before long,
that the Quakers should be arraigned at the bar, and be banished to some land,
where there were nothing but bears.
At this the court burst out into a laughter; yet the exception was admitted,
and the man put by.
The prisoners not thinking it convenient to make more exceptions, the jury were sworn;
then two witnesses were called, who testified at most,
that in such a place they took such persons met together,
whose names were specified in writing.
Then the prisoners bid the jury, take heed how they did sport or dally with holy things,
and that those things, which concerned the conscience, were holy things.
And as a man was not to sport with the health or illness of his neighbor,
so he was not to sport with the liberty or the banishment of his neighbor.
And whereas they were accused of being wicked, dangerous, and seditious sectaries,
that was not true; for they were not wicked, but such as endeavored to live soberly,
righteously, and godly in the world; concerning the truth of which,
they appealed to themselves.
Neither were they seditious, but peaceable.
And whereas they were charged for not coming to hear the common prayer,
this was incongruous;
for the service book was not quite printed several weeks after the said 29th of June;
so that they could not be charged of neglecting to
hear that which was not to be heard read any where.
This puzzled the court not a little;
and other pinching reasons were also given by the prisoners,
some of whom were men of learning;
insomuch that the judge was not able to answer the objections,
but by shifts and evasions.
At length the jury went out to consult, and one of them was heard to say,
as they were going up stairs, '`Here is a deal to do indeed,
to condemn a company of innocent men.`'

After some time, the jury coming again,
and being asked whether the prisoners at the bar were guilty or not guilty,
they said they were guilty in part, and not guilty in part.
But this verdict did not please the judge.
The jury then going out again, and prevailing upon one another, quickly returned,
and declared the prisoners guilty, according to the form of the indictment.
Hereupon the judge Onslow pronounced sentence, namely:
That they should return to prison again, and lie there three months without bail;
and if they did not make submission according as the law directed,
either at or before the end of the aforesaid three months,
that then they should abjure the realm: but in case they refused to make abjuration,
or after abjuration made, should forbear to depart the realm within the time limited,
or should return again without license, they should be proceeded against as felons.

Just before sentence given, the judge said to one of the prisoners,
there was a way to escape the penalty, namely: Submission.
And being asked, what that was?
the judge answered, '`To come to common prayer, and refrain these meetings.`'
The prisoner giving reasons for refusal of both, the judge said,
'`Then you must abjure the land.`'
'`Abjure,`' returned the prisoners, is '`forswear.`'
To which one of the justices said laughingly, '`And you cannot swear at all.`'
Just as if it were but jest, thus to treat religious men.
But they had signified already to the jury, that they must rather die than do so.
How long they were kept prisoners, and how released, I could not learn; but this I know,
that many in the like cases have been long kept in jail,
till sometimes they were set at liberty by the king`'s proclamation.

In this year it was the share of John Crook,
(who himself once had been a justice,) to be taken
out of a meeting at London in John`'s street,
as has been said already, by one Miller, though not in office.
And he with others was brought to his trial in the said city,
before the lord mayor of London, the recorder of the same, the chief justice Forster,
and other judges and justices, among whom was also Richard Brown.

Now since J. Crook published this trial in print, and by that we may judge,
as _ex ungue leonem,_ (English:
from a part we may judge the whole) of other trials of the Quakers,
I will give it here at large.

[.embedded-content-document]
--

J+++.+++ Crook being brought to the sessions house in the Old Bailey, with two of his friends,
Isaac Gray, doctor of medicine, and John Bolton goldsmith:
one of the prisoners was called to the bar, and then asked by the

[.discourse-part]
_Chief Judge:_ What meeting was that you were at?

[.discourse-part]
_Prisoner:_ I desire to be heard, where is my accuser?

[.discourse-part]
_Chief Judge:_ Your tongue is not your own,
and you must not have liberty to speak what you wish.

[.discourse-part]
_Prisoner:_ I speak in the presence and fear of the everlasting God,
that my tongue is not my own, for it is the Lord`'s,
and to be disposed of according to his pleasure, and not to speak my own words;
and therefore I desire to be heard:
I have been so long in prison then he was interrupted by the judge.

[.discourse-part]
_Judge:_ Leave your canting; and commanded him to be taken away, which he was accordingly,
by the jailer.

[.small-break]
'''

This was the substance of what the prisoner aforesaid spoke the first time.

[.discourse-part]
_Chief Judge:_ Call John Crook to the bar; which the crier did accordingly,
he being among the felons as aforesaid.

[.discourse-part]
_J+++.+++ Crook:_ being brought to the bar:

[.discourse-part]
_Chief Judge:_ When did you take the oath of allegiance?

[.discourse-part]
_J+++.+++ Crook:_ I desire to be heard.

[.discourse-part]
_Chief Judge:_ Answer to the question, and you shall be heard.

[.discourse-part]
_J+++.+++ Crook:_ I have been about six weeks in prison, and am I now called to accuse myself?
For the answering to this question in the negative, is to accuse myself,
which you ought not to put me upon; for, _Nemo debet seipsum prodere_ (in English:
No one should be obliged to betray himself.) I am an Englishman,
and by the law of England I ought not to be taken, nor imprisoned,
nor disseized of my freehold, nor called in question, nor put to answer,
but according to the law of the land; which I challenge as my birthright,
on my own behalf, and all that hear me this day;
(or words to this purpose.) I stand here at this bar as a delinquent,
and do desire that my accuser may be brought forth to accuse me for my delinquency,
and then I shall answer to my charge, if any I be guilty of.

[.discourse-part]
_Chief Judge:_ You are here demanded to take the oath of allegiance,
and when you have done that, then you shall be heard about the other;
for we have power to tender it to any man.

[.discourse-part]
_J+++.+++ Crook:_ Not to me upon this occasion, in this place;
for I am brought here as an offender already, and not to be made an offender here,
or to accuse myself; for I am an Englishman, as I have said to you,
and challenge the benefit of the laws of England;
for by them is a better inheritance derived to me as an Englishman,
that that which I received from my parents: for by the former the latter is preserved;
and this is seen in the 29th chapter of Magna Charta, and the petition of right,
mentioned in the third of Car. I. and in other good laws of England;
and therefore I desire the benefit and observance of them:
and you that are judges upon the bench, ought to be my counsel, and not my accusers,
but to inform me of the benefit of those laws; and wherein I am ignorant,
you ought to inform me,
that I may not suffer through my own ignorance of those advantages,
which the laws of England afford me as an Englishman.

[.small-break]
'''

Reader, I here give you a brief account of my taking and imprisoning,
that you may the better judge what justice I had from the court aforesaid;
which is as follows.

I being in John`'s street, London, about the 13th day of the Third month,
(called May,) with some other of the people of God, to wait upon him,
as we were sat together, there came in a rude man called Miller,
with a long cane in his hand, who laid violent hands upon me, with some others,
beating some, and commanding the constables who came in after him, but having no warrant,
were not willing to meddle; but as his threatenings prevailed, they, being afraid of him,
joined with him to carry several of us before justice Powel,
(so called,) who the next day sent us to the sessions, at Hicks`'s Hall;
where after some discourse several times with them;
we manifested to them the illegality both of our commitment,
and their proceedings thereupon; yet notwithstanding, they committed me and others,
and caused an indictment to be drawn against us,
founded upon the late act against Quakers and others; and then remanded us to New Prison,
where we continued for some days; and then removed us to Newgate,
where we remained until the sessions in the Old Bailey aforesaid:
whereby you may understand what justice I met withal, by what went before,
and now further follows:

[.discourse-part]
_Chief Judge:_ We sit here to do justice, and are upon our oaths;
and we are to tell you what is law, and not you us: therefore, sirrah, you are too bold.

[.discourse-part]
_J+++.+++ Crook:_ Sirrah is not a word becoming a judge: for I am no felon:
neither ought you to menace the prisoner at the bar:
for I stand here arraigned as for my life and liberty,
and the preservation of my wife and children, and outward estate,
(they being now at the stake;) therefore you ought to hear me to the full,
what I can say in my own defence, according to law, and that in its season,
as it is given me to speak: therefore I hope the court will bear with me,
if I am bold to assert my liberty, as an Englishman, and as a Christian;
and if I speak loud, it is my zeal for the Truth, and for the name of the Lord;
and my innocency makes me bold--

[.discourse-part]
_Judge:_ (Interrupting John Crook;) It is an evil zeal.

[.discourse-part]
_J+++.+++ Crook:_ No, I am bold in the name of the Lord God Almighty, the everlasting Jehovah,
to assert the Truth, and stand as a witness for it: let my accuser be brought forth,
and I am ready to answer any court of justice--

Then the judge interrupted me, saying sirrah, with some other words I do not remember.
Rut I answered, You are not to threaten me,
neither are those menaces fit for the mouth of a judge;
for the safety of the prisoner depends upon the indifferency of the court:
and you ought not to behave yourselves as parties,
seeking all advantage against the prisoner,
but not heeding any thing that may make for his clearing or advantage.
The judge again interrupting me, saying.

[.discourse-part]
_Judge:_ Sirrah, you are to take the oath, and here we tender it you, (bidding, read it.)

[.discourse-part]
_J+++.+++ Crook:_ Let me see my accuser,
that I may know for what cause I have been six weeks imprisoned,
and do not put me to accuse myself by asking me questions;
but either let my accuser come forth, or otherwise let me be discharged by proclamation,
as you ought to do--Here I was interrupted again.

[.discourse-part]
_Judge Twisden:_ We take no notice of your being here otherwise than of a straggler,
or as any other person, or of the people that are here this day;
for we may tender the oath to any man.
And another judge spoke to the like purpose.

[.discourse-part]
_J+++.+++ Crook:_ I am here at your bar as a prisoner restrained of my liberty,
and do question whether you ought in justice to tender me
the oath on the account I am now brought before you,
because I am supposed to be an offender;
or else why have I been six weeks in prison already?
Let me be cleared of my imprisonment,
and then I shall answer to what is charged against me,
and to the question now propounded; for I am a lover of justice with all my soul,
and am well known by my neighbors, where I lived, to keep a conscience void of offense,
both towards God and towards man.

[.discourse-part]
_Judge:_ Sirrah, leave your canting.

[.discourse-part]
_J+++.+++ Crook:_ Is this canting, to speak the words of the scripture?

[.discourse-part]
_Judge:_ It is canting in your mouth, though they are Paul`'s words.

[.discourse-part]
_J+++.+++ Crook:_ I speak the words of the Scripture, and it is not canting, though I speak them;
but they are words of truth and soberness in my mouth, they being witnessed by me,
and fulfilled in me.

[.discourse-part]
_Judge:_ We do ask you again, whether you will take the oath of allegiance?
It is but a short question, you may answer if you will.

[.discourse-part]
_J+++.+++ Crook:_ By what law have you power to tender it?
Then, after some consultation together by whispering, they called for the statute book,
and turning over the leaves, they answered,

[.discourse-part]
_Judge:_ By the third of King James.

[.discourse-part]
_J+++.+++ Crook:_ I desire that statute may be read; for I have consulted it,
and do not understand that you have power by that statute to tender me the oath,
being here before you in this place, upon this occasion, as a delinquent already;
and therefore I desire the judgment of the court in this case,
and that the statute may be read.

[.discourse-part]
_Judge:_ Then they took the statute-book, and consulted together upon it, and one said,
we are the judges of this land, and do better understand our power than you do,
and we do judge we may lawfully do it.

[.discourse-part]
_J+++.+++ Crook:_ Is this the judgment of the court?

[.discourse-part]
_Judge:_ Yes.

[.discourse-part]
_J+++.+++ Crook:_
I desire the statute to be read that empowers you to tender
the oath to me upon this occasion in this place;
for, _Vox audita perit, sed litera scripta manet_ (in English: Words only spoken are lost;
writing remains), therefore let me hear it read.

[.discourse-part]
_Judge:_ Hear me.

[.discourse-part]
_J+++.+++ Crook:_ I am as willing to hear as to speak.

[.discourse-part]
_Judge:_ Then hear me: you are here required to take the oath by the court,
and I will inform you what the penalty will be, in case you refuse;
for your first denial shall be recorded,
and then it shall be tendered to you again at the end of the sessions:
and upon the second refusal you run into a premunire,
which is the forfeiture of all your estate, (if you have any,) and imprisonment.

[.discourse-part]
_J+++.+++ Crook:_ It is justice I stand for; let me have justice,
in bringing my accuser face to face, as by law you ought to do,
I standing at your bar as a delinquent; and when that is done,
I will answer to what can be charged against me, as also to the question; until then,
I shall give no other answer than I have already done, at least at present.

[.small-break]
'''

Then there was a cry in the court, '`take him away,`' which occasioned a great interruption:
and J. Crook spoke to this purpose, saying,
'`Mind the fear of the Lord God, that you may come to the knowledge of his will,
and do justice; and take heed of oppressing the innocent,
for the Lord God of heaven and earth will assuredly plead their cause: and for my part,
I desire not the hurt of one of the hairs of your heads; but let God`'s wisdom guide you.`'
These words he spoke at the bar, and as he was carrying away.

On the sixth day of the week, in the forenoon following, the court being sat,
John Crook was called to the bar.

[.discourse-part]
_Chief Judge:_ Friend Crook,
we have given you time to consider of what was said yesterday to you by the court,
hoping you may have better considered of it by this time; therefore,
without any more words, will you take the oath?
And called to the clerk, and bid him read it.

[.discourse-part]
_J+++.+++ Crook:_ I did not, neither do I deny allegiance,
but do desire to know the cause of my so long imprisonment; for, as I said,
I stand at your bar as a delinquent, and am brought here by force, contrary to the law;
therefore, let me see my accuser, or else free me by proclamation, as I ought to be,
if none can accuse me; for the law is grounded upon right reason,
and whatsoever is contrary to right reason, is contrary to law;
and therefore if no accuser appear, you ought to acquit me first,
and then I shall answer, as I have said, if any new matter appear;
otherwise it is of force, and that our law abhors,
and you ought not to take notice of my so being before you; for what is not legally so,
is not so; and therefore I am in the condition, as if I were not before you:
and therefore it cannot be supposed, in right reason, that you have now power,
at this time, and in this place, legally to tender me the oath.

[.discourse-part]
_Judge:_ Read the oath to him; and so the clerk began to read.

[.discourse-part]
_J+++.+++ Crook:_ I desire justice, according to the laws of England;
for you ought first to convict me, concerning the cause of my so long imprisonment;
for you are to proceed according to laws already made, and not to make laws,
for you ought to be ministers of the law.

[.discourse-part]
_Judge:_ You are a saucy and an impudent fellow: will you tell us what is law,
or our duties?
Then said he to the clerk, read on; and when the clerk had done reading,

[.discourse-part]
_J+++.+++ Crook:_ said, read the preface to the act; I say again,
read the title and preamble to the act; for titles to laws are _claves legum,_
as keys to open the law; for by their titles, laws are understood and known,
as men by their faces.
Then the judges would have interrupted me, but I said as follows:
if you will not hear me, nor do me justice,
I must appeal to the Lord God of heaven and earth, who is judge of quick and dead;
before whom we must all appear, to give an account of the deeds done in the body;
for he will judge between you and me this day, whether you have done me justice or not.

[.small-break]
'''

These words following, (or the like,) I spoke as going from the bar, being pulled away,
"`Mind the fear of the Lord God, that you may do justice,
least you perish in his wrath.`"
For sometimes the court cried, '`pull him away,`' and then said, '`bring him again:`'
and thus they did several times, like men in confusion and disorder.

The same day, in the afternoon, silence being made, John Crook, was called to the bar,
before the judges and justices aforesaid: the indictment being read, the judge said,

[.discourse-part]
Mr. Crook, You have heard your indictment, what say you?
Are you guilty or not guilty?

[.discourse-part]
_J+++.+++ Crook:_ I desire to speak a few words in humility and soberness,
in regard my estate and liberty lies at stake,
and am like to be a precedent for many more;
therefore I hope the court will not deny me the right and benefit of the law,
as being an Englishman.
I have some reason, before I speak any thing to the indictment, to demand and tell you,
that I desire to know my accusers; I have been kept these six weeks in prison,
and know not, nor have seen the faces of them.

[.discourse-part]
_Judge:_ We shall afford you the right of the law, as an Englishman.
God forbid you should be denied it; but you must answer first, guilty, or not guilty,
that so in your trial you may have a fair hearing and pleading;
but if you go on as you do, (and will not answer guilty,
or not guilty,) you will run yourself into a premunire,
and then you lose the benefit of the law, and expose yourself`', body and estate,
to great hazards; and whatever violence is offered to your person or estate,
you are out of the king`'s protection, and lose the benefit of the law;
and all this by your not answering, (guilty, or not guilty.) If you plead not guilty,
you may be heard.

[.discourse-part]
_J+++.+++ Crook:_ It is recorded in the statutes of the 28
Edw. 3. &c 3. and 42 Edw. 3. & L 3. in the words.
'`No man is to be taken, or imprisoned, or be put to answer,
without presentment before justices, or matter of record, or by due process,
or writ original, according to the old law of the land;
and if any thing from henceforth be done to the contrary, it shall be void in law,
and held for error.
And also in the 25th of Edw. 1. 2. and the 3 Car. L and the 29 cap. Mag. Chart.
No freeman shall be taken and imprisoned but by the law of the land: these words,
(the law of the land,) are explained by the statute of 37 Edw. 3. 8.
to be, without due process of law; and if any judgments are given contrary to Mag.
Chart, they are void, 25 Edw. 1. 2.

[.discourse-part]
_Judge:_ Mr. Crook, you are out of the way, and do not understand the law,
though you adore the statute law so much, yet you do not understand it.

[.discourse-part]
_J+++.+++ Crook:_ I would have you tell me the right way.

[.discourse-part]
_Judge:_ Mr. Crook, hear me: you must say, guilty, or not guilty; if you plead not guilty,
you shall be heard, and know how far the law favors you.
And the next thing is,
there is no circumstance whatsoever that is the cause of your imprisonment,
that you question, but you have, as a subject, your remedies, if you will go this way,
and waive other things, and answer guilty, or not guilty; and what the law affords you,
you shall have, if you do what the law requires you;
or else you will lose the benefit of the law, and be out of the king`'s protection.

[.discourse-part]
_J+++.+++ Crook:_ Observe how the judge would draw me into a snare--By first pleading, (guilty,
or not guilty,) and when I have done so, he and his brethren intend suddenly to put me,
(as an outlawed person) out of the king`'s protection;
and how then can I have remedy for my false imprisonment?
Therefore first clear me, (or condemn me.) from my false imprisonment,
while I am in a capacity to have the benefit of the law,
and not to outlaw me for an offense created by yourselves; and then, to stop my mouth,
you tell me, that if I have been wronged, or false imprisoned,
I may have my remedy afterwards: this is to trepan me,
and contrary to both law and justice, etc.

[.discourse-part]
_Judge:_ You must plead guilty, or not guilty.

[.discourse-part]
_J+++.+++ Crook:_ I do desire in humility and meekness to say, I shall not;
I dare not betray the honesty of my cause, and the honest ones of this nation,
whose liberty I stand for, as well as my own; as I have cause to think I shall,
if I plead to the present indictment, before I see the faces of my accusers; for truly,
I am not satisfied in my judgment and conscience,
that I ought to plead to a created offense by you,
before I be first acquitted of the cause of my being brought prisoner to your bar;
and therefore it sticks with me to urge this further:
That I may see my accusers-- (Interruption.)

[.discourse-part]
_Judge:_ The most arrant thief may say, he is not satisfied in his conscience.

[.discourse-part]
_J+++.+++ Crook:_ My case is not theirs, yet they have their accusers;
and may not I call for mine?
And therefore call for them, for you ought to do so: as Christ said to the woman, Woman,
where are your accusers?
So you ought to say to me, Man, where are your accusers?
-- (Interruption.)

[.discourse-part]
_Judge:_ Your indictment is your accuser, and the grand jury have found you guilty,
because you did not swear: what say you, Mr. Crook, are you guilty, or not guilty?
If you will not answer, or what you have said, be taken for your answer,
as I told you before, you lose the benefit of the law; and what I tell you,
is for your good.

[.discourse-part]
_J+++.+++ Crook:_ What is for good, I hope I shall take it so.

[.discourse-part]
_Judge:_ If you will not answer, you run yourself into a premunire;
and you will lose the benefit of the law, and the king`'s protection,
unless you plead guilty, or not guilty.

[.discourse-part]
_J+++.+++ Crook:_ I stand as brought forcibly and violently here:
neither had I been here but by a violent action;
and that you should take no notice of it, seems strange to me; and not only so,
but that you should hasten me so fast into a course,
that I should not be able anyways to help myself,
by reason of your hasty and fast proceedings against me,
to put me out of the king`'s protection, and the benefit of all law:
was ever the like known, or heard of, in a court of justice?

[.discourse-part]
_Judge:_ Friend, this is not here in question, whether you are unjustly brought here,
or not: do you question that by law,
but not disable yourself to take advantage by the law: if brought by a wrong hand,
you have a plea against them; but you must first answer guilty, or not guilty.

[.discourse-part]
_J+++.+++ Crook:_ How can I help myself when you have outlawed me?
Therefore let proclamation be made in the court, that I was brought by force here,
and let me stand cleared by proclamation, as you ought to do;
for you are __discernere per legem, quid sit juslum,__^
footnote:[To determine by law what is just.]
and not to do what seems good in your own eyes--here I was interrupted again,
but might have spoken justice Crook`'s words in Hampden`'s case, who said,
That we who are judges speak upon our oaths,
and therefore must deliver our judgments according to our consciences;
and the fault will lie upon us, if it be illegal, and we deliver it for law:
and further said, We that are judges must not give our judgments according to policy,
or rules of state, nor conveniences, but only according to law.
These were his words, which I might have spoken; but was interrupted.

[.discourse-part]
_Judge:_ What, though no man tendered the oath to you, when you were committed,
(as you say,) it being now tendered to you; from the time you refused it,
being tendered to you by a lawful authority, you refusing, are indicted:
we look not upon what you are here for, but here finding you, we tender you the oath;
and you refusing it, your imprisonment is now just, and according to law.
(Something omitted which I spoke afterwards.)

[.discourse-part]
_J+++.+++ Crook:_ How came I here, if you know not?
I have told you it is by force and violence, which our law altogether condemns;
and therefore I not being legally before you, am not before you;
for what is not legally so, is not so; and I not being legally brought to your bar,
you ought not to take notice of my being here.

[.discourse-part]
_Judge:_ No, no, you are mistaken; so you may say of all the people gazing here,
they not being legally here, are not here: I tell you, a man being brought by force here,
we may tender him the oath; and if he take it not, he may be committed to prison;
authority has given us the power,
and the statute-law has given us authority to tender the oath to any person,
and so have we tendered it to you; and for your not taking it,
you are indicted by the grand jury: answer the accusation, or confute the indictment;
you must do the one or the other; answer, guilty, or not guilty.

[.small-break]
'''

Here I was interrupted, but might have said, that the people that were spectators,
beholding and hearing the trials, are not to be called gazers, as the judge terms them;
because it is their liberty and privilege, as they are Englishmen,
and the law of England allows the same;
so that they are not to be termed gazers upon this account,
but are legally in that place, to hear trials, and see justice done,
and might have spoken, (if occasion had been,) any thing in the prisoner`'s defense,
tending to clear up the matter in difference, and the court must have heard them or him:
and this as a stander-by, or __amicus curiae;__^
footnote:[A friend of the court.]
so says Cook.

[.discourse-part]
_J+++.+++ Crook:_ The law is built upon right reason, or right reason is the law;
and whatever is contrary to right reason, is contrary to law; the reason of the law,
being the law itself.
I am no lawyer, and my knowledge of it is but little,
yet I have had a love to it for that reason I have found in it,
and have spent some leisure hours in the reading thereof;
and the law is that which I honor, and is good in its place;
many laws being just and good, not all, but, I say, a great part of them,
or much of them; and it is not my intention in the least to disparage,
or derogate from them.

[.discourse-part]
_Judge:_ Mr. Crook, you have been told, you must plead guilty or not guilty,
or else you run yourself into a premunire; be not you own enemy, nor be so obstinate.

[.discourse-part]
_J+++.+++ Crook:_ I would not stand obstinately before you, neither am I so;
if you understand it otherwise, it is a mistake indeed.

[.discourse-part]
_Judge:_ Will you speak to the indictment, and then you may plead?
If you will not answer guilty, or not guilty, we will record it,
and judgment shall go against you.
Clerk, enter it.

[.discourse-part]
_Recorder:_ Mr. Crook, if you will answer, you may plead for yourself:
or will you take the oath?
The court takes no notice how you came here; what say you?
Will you answer?
For a man maybe brought out of Smithfield by head and shoulders,
and the oath tendered to him, and may be committed,
without taking notice how he came here.

[.discourse-part]
_J+++.+++ Crook:_ That kind of proceeding is not only unjust,
but unreasonable also--(here was some interruption,) and against the laws aforesaid,
which say.
No man shall be taken or imprisoned but by warrant, or due process of law:
so that this speech of the recorder`'s, savors more of passion than justice; and cruelty,
than due observance of law; for every forcible restraint of a man`'s liberty,
is an imprisonment in law.
Besides, this kind of practice, to take men by force, and imprison them,
and then ask them questions, the answering of which makes them guilty,
is not only unrighteous in itself, but against law,
and makes one evil act the ground of another; and one injury offered to one,
the foundation of another; and this is my case this day--Interruption.

[.discourse-part]
_Judge:_ Mr. Crook you must not be your own judge, we are your judges;
but for our parts we will not wrong you: will you answer, guilty or not guilty?
If not, you will run yourself into a premunire unavoidably,
and then you know what I told you would follow; for we take no notice how you came here,
but finding you here, we tender you the oath.

[.discourse-part]
_J+++.+++ Crook:_ Then it seems you make the law a trepan to ensnare me, or as a nose-of-wax,
or what you please: well, I shall leave my cause with the Lord God,
who will plead for me in righteousness.
But suppose I do take the oath (now,) at this time, you may call me again,
(tomorrow,) and make a new tender; or others may call me before them.

[.discourse-part]
_Judge:_ Yes, if there be new matter;
or if there fall out any emergent occasion whereby
you may minister on your part new occasion:
Mr. Crook, will you swear?

[.discourse-part]
_J+++.+++ Crook:_ If I do take it today, it may be tendered me again tomorrow, and so next day,
_ad infinitum,_ whereby a great part of my time may be spent and taken up,
in taking the oath and swearing.

[.discourse-part]
_Chief Judge:_ When you have (once) sworn, you may not be put upon it again,
except you minister occasion on your part.

[.discourse-part]
_J+++.+++ Crook:_ Is this the judgment of the court,
that the oath (once) taken by me is sufficient,
and ought not to be tendered a second time, without new matter ministered on my part?

[.discourse-part]
_Judge:_ Yes; you making it appear you have (once) taken it.

[.discourse-part]
_J+++.+++ Crook:_ Is this the judgment of the whole court?
For I would not do any thing rashly.

[.discourse-part]
_Judges:_ Yes, it is the judgment of the court; to which they all standing up, said, Yes.

[.discourse-part]
_J+++.+++ Crook:_
Then it seems there must be some new occasion ministered
by me after I have (once) taken it,
or it ought not to be tendered to me the second time.

[.discourse-part]
_Judges:_ Yes.

[.discourse-part]
_J+++.+++ Crook:_ Then by the judgment of this court,
if I may make it appear that I have taken the oath (once)
and I have ministered no new matter on my part,
whereby I can be justly charged with the breach of it,
then it ought not to be tendered to me the second time:
but I am the man that have taken (once) being a freeman of the city of London,
when I was made free; witness the records in Guildhall, which I may produce,
and no new matter appearing to you on my part; if there do, let me know it; if not,
you ought not, by your own judgment, to tender me it the second time;
for _de non apparentibus el non existentibus eadem ratio est_ (in English:
That which does not appear,
is to be judged as if it did not exist.) (Interrupted by the shout of the court,
when these last words might have been spoken.)

[.discourse-part]
_Judge:_ Mr. Crook, you are mistaken,
you must not think to surprise the court with criticisms,
nor draw false conclusions from our judgments.

[.discourse-part]
_J+++.+++ Crook:_ If this be not a natural conclusion from the judgment of the court,
let right reason judge; and if you recede from your own judgments in the same breath,
(as it were,) given even now, what justice can I expect from you?
For, if you will not be just to yourselves, and your own judgments,
how can I expect you should be just to me?

[.discourse-part]
_Judge:_ Mr. Crook, if you have taken it, if there be a new emergency,
you are to take it again; as for instance, the king has been out of England,
and now is come in again; there be many that have taken it twenty, thirty,
or forty years since, yet this new emergency requires it again;
and although you have taken it, yet you must not make it appear before you answer guilty,
or not guilty; therefore do not wrong yourself, and prejudice yourself and family:
do you think that every fellow that comes here, shall argue as you do?
We have no more to do, but to know of you, whether you will answer (guilty,
or not guilty,) or take the oath, and then you shall be freed from the indictment:
if you will not plead, clerk, record it: What say you?
Are you guilty, or not guilty?

[.discourse-part]
_J+++.+++ Crook:_ Will you not stand to your own judgments? Did you not say, even now,
that if I had (once) taken the oath, it ought not to be tendered to me the second time,
except I administered new matter on my part that I have not kept it, etc.
But no such matter appearing, you ought not to tender it to me the second time,
by your own confession, much less to indict me for refusal.

[.discourse-part]
_Judge:_ If you will not plead, we will record it, and judgment shall be given against you;
therefore say, guilty, or not guilty, or else we will record it.
(The clerk beginning to record it.)

[.discourse-part]
_J+++.+++ Crook:_ Before I answer, I demand a copy of my indictment;
for I have heard it affirmed by counsel learned in the law,
that if I plead before I have a copy, or have made my exceptions,
my exceptions afterwards against the indictment will be made void:
therefore I desire a copy of the indictment.

[.discourse-part]
_Judge:_ He that said so, deserves not the name of a counsel; for the law is,
you must first answer, and then you shall have a copy.
Will you plead guilty or not guilty?

[.discourse-part]
_J+++.+++ Crook:_ If my pleading guilty, or not guilty,
will not deprive me of the benefit of quashing the indictment for insufficiency,
or other exceptions that I may make against it, I shall speak to it.

[.discourse-part]
_Judge:_ No, it will not.
Will you answer, guilty, or not guilty.
If you plead not, the indictment will be found against you: will you answer?
We will stay no longer.

[.discourse-part]
_J+++.+++ Crook:_ I am upon the point: will not my pleading deprive me of the benefit of the law?
For I am tender in that respect, because it is not my own case only,
but may be the case of thousands more;
therefore I would do nothing that might prejudice others, or myself, as a Christian,
or as an Englishman.

[.discourse-part]
_Judge:_ Understand yourself, (but we will not make a bargain with you,
said another judge,) you shall have the right done you as an Englishman,
the way is to answer, guilty or not guilty: if you plead,
and find the indictment not good, you may have your remedy; answer,
guilty or not guilty?

[.discourse-part]
_J+++.+++ Crook:_ As to the indictment it is very large, and seems to be confused,
and made of some things true, and some things false; my answer therefore is,
what is true in the indictment I will not deny, because I make conscience of what I say,
and therefore, of what is true, I confess myself guilty, but what is false,
I am not guilty of.

[.discourse-part]
_Judge:_ That is not sufficient, either answer guilty, or not guilty,
or judgment will be given against you.

[.discourse-part]
_J+++.+++ Crook:_ I will speak the truth, as before the Lord,
as all along I have endeavored to do: I am not guilty of that which is false,
contained in the indictment, which is the substance thereof.

[.discourse-part]
_Judge:_ No more ado; the form is nothing, guilty, or not?

[.discourse-part]
_J+++.+++ Crook:_ I must not wrong my conscience, I am not guilty of what is false,
as I said before; what is true, I am guilty of; what is not true,
I am not guilty of that; which is the substance thereof, as I said before.

[.discourse-part]
_Recorder:_ It is enough, and shall serve turn.
Enter that, clerk.

[.small-break]
'''

The seventh day of the week, called Saturday.

Silence being made, John Crook was called to the bar.
The clerk of the sessions read something concerning the jury,
which was impanneled on purpose,
(as we said,) the jury being discharged who were
eyewitnesses of what passed between us and the court:
and this jury, were several of them soldiers,
some of whom did by violence and force pull and haul Friends out of their meetings,
and some of us out of our houses; and these were of the jury by whom we were to be tried.
The clerk reading the indictment, (as I remember.)

[.discourse-part]
_J+++.+++ Crook:_ I desire to be heard a few words, which are these,
that we may have liberty till the next quarter sessions to traverse the indictment,
it being long and in Latin, and like to be a precedent: and I hope I need not press it;
because I understood that you promised, (and especially the recorder, who answered,
when it was desired, you shall,) that we should have counsel also,
the which we cannot be expected to have had the benefit of as yet,
the time being so short, and we kept prisoners,
that we could not go forth to advise with counsel,
neither could we tell how to get them to us;
we having no copy of the indictment before this morning;
and because so suddenly hurried down to the sessions,
we cannot reasonably be supposed to be provided,
(as to matter of law,) to make our defense.

[.discourse-part]
_Judge:_ We have given you time enough, and you shall have no more;
for we will try you at this time, therefore swear the jury.

[.discourse-part]
_J+++.+++ Crook:_ I desire we may have justice, and that we may not be surprised in our trial,
but that we may have time till the next quarter sessions, our indictment being in Latin,
and so large as it is; and this is but that which is reasonable,
and is the practice of other courts: for, if it be but an action above forty shillings,
it is not ordinarily ended under two or three terms.
And in the quarter sessions, if one be indicted for a trespass,
if it be but to the value of five shillings, he shall have liberty to enter his traverse,
and upon security given to prosecute, he shall have liberty till the next sessions,
which is the ordinary practice: which liberty we desire, and we hope it is so reasonable,
it will not be denied, especially upon this occasion,
we being like to be made a precedent:
and courts of justice have used to be especially careful in making of precedents;
for we are not provided, according to law, to make our defense at this time;
and therefore if we be put upon it, it will be a surprisal.

[.discourse-part]
_Judge:_ There is no great matter of law in the case; it is only matter of fact,
whether you have refused to take the oath or not; this is the point in issue:
and what law can arise here?

[.discourse-part]
_Recorder:_ Mr. Crook, the keeper of the prison was spoken to, to tell you,
that we intended to try you this day,
and therefore ordered him that counsel might come to you if you would;
and also that the clerk should give you a copy of the indictment: this is fair;
therefore we will go on to swear the jury, for the matter is,
whether you refuse the oath, or not?
And that is the single point, and there needs neither law nor counsel in the case;
and therefore we considered of it last night, when we sent you word,
and did determine to try you; and therefore it is in vain to say any thing,
for the court is resolved to try you now; therefore swear the jury, cryer.

[.discourse-part]
_J+++.+++ Crook:_ I hope you will not surprise us.

[.small-break]
'''

Then the other prisoners, (who also were indicted,) cried out,
(having spoken something before,) let us have justice,
and let not the jury be sworn till we be first heard.
So there was a great noise, the court being in a confusion, some crying, Take them away;
others.
Stay, let them alone; others saying, Go on to swear the jury; and the cryer,
in this uproar and confusion, did do something as if he had done it:
then we all cried out for justice and liberty till the next sessions;
the court being in a confusion, some crying one thing, and some another,
which now cannot be called to mind,
by reason of the great distraction that was in the court; neither what we said to them,
nor they to us, the noise was so great,
and the commands of the court so various to the officers,
some commanding them to take us away; others, to let us alone; others,
to bring us nearer; others cried, put them into the bail-dock; others,
to put them within the furthest bar where the felons use to stand;
which we were forced into accordingly.
And in this hurly-burly and confusion that was among them, some men were sworn,
to testify that we refused to take the oath, which we never positively did;
other officers of the court, whom they would have sworn, refused to swear,
though pressed to it by the chief justice, they desired to be excused.
Then spoke one of the prisoners again pretty much, but could hardly be understood,
by reason of the noise in the court; but the people, to whom he spoke with a loud voice,
by way of exhortation, might hear the substance of what he said,
which cannot now particularly be called to mind;
but it was to express the presence and love of God to himself,
and to exhort others to mind his fear, that they also might be acquainted with God, etc.

[.discourse-part]
_Judge:_ Stop his mouth, executioner.
Which was accordingly done.

[.discourse-part]
_Prisoners:_ Then we cried out, will you not give us leave to speak for ourselves?
We except against some of the jury, as being our enemies,
and some of them who by force commanded us to be pulled out of our meetings,
contrary to law, and carried us to prison without warrant, or other due process of law;
and shall these be our judges`'? We except against them.

[.discourse-part]
_Judge:_ It is too late now, you should have done it before they had been sworn jurymen.
Jury, go together, that which you have to find,
is whether they have refused to take the oath, or no,
which has been sworn before you that they did refuse: you need not go from the bar.
And like words said the recorder and others,
there being a confusion and noise in the court, many speaking together.

[.discourse-part]
_Prisoners:_ Then we cried for justice, and that we might be heard, to make our defense,
before the jury gave their verdict; but the judge and recorder said,
we should not be heard, (making good by their practice,
what the chief judge had said the day before, namely: That if we had liberty to speak,
we would make ourselves famous and them odious,) crying again stop their mouths,
executioner; which was done accordingly, with a dirty cloth,
and also endeavored to have gagged me, striving to get hold of my tongue,
having a gag ready in his hand for that purpose; and so we were served several times.
Then I called out with a loud voice, Will you condemn us without hearing?
This is to deal worse with us, than Pilate did with Christ, who,
though he condemned him without a cause, yet not without hearing him speak for himself;
but you deny us both.

[.discourse-part]
_Judge:_ Let Mr. Gray come to the bar.

[.small-break]
'''

Room being made, he was conveyed to an officer in the inner bar,
where he spoke to the court to this purpose: I desire to know whether, according to law,
and the practice of this court, myself and my fellow prisoners,
may have liberty to put in bail, to prosecute our traverse at the next sessions?

[.discourse-part]
_Court:_ No, we will try you presently.

[.discourse-part]
_Judge:_ Stop their mouths, executioner: and this was the cry of many upon the bench,
they being still in a continued confusion; some crying to the jury, Give in your verdict,
for we will not hear them; with other words which could not be heard for the noise,
the court being in confusion.

[.discourse-part]
_J+++.+++ Crook:_ You might as well have caused us to have been murdered before we came here,
as to bring us here under pretense to try us, and not give us leave to make our defense;
you had as good take away our lives at the bar, as to command us thus to be abused,
and to have our mouths stopped: was ever the like known?
Let the righteous God judge between us.
Will you hear me?
You have often promised that you would.

[.discourse-part]
_Judge:_ Hear me, and we will hear you: then he began to speak,
and some others of the bench interrupted him:
sometimes they speaking two or three at a time,
and a noise among the officers of the court: but the judge said,
We may give you liberty till the next sessions, but we may choose;
and therefore we will try you now.

[.discourse-part]
_J+++.+++ Crook:_ I bade the people take notice of their promise,
that I should have liberty to speak, saying, See now you be as good as your words.

[.discourse-part]
_Judge:_ The law of England is not only just, but merciful;
and therefore you shall not be surprised,
but shall have what justice the law allows--(Interruption.)

[.discourse-part]
_J+++.+++ Crook:_ I remember what the judge said even now,
that the law of England was a merciful law; that the court had said before,
they might if they would, give us liberty till the next sessions, but they would not;
and the maxim of the law also is, _Summum jus est summa injuria;_ (in English:
The extreme of the law is extreme injustice);
therefore I hope your practice will make it good, that it is a merciful law;
and not to execute _summum jus,_ etc., upon me,
and thereby condemn yourselves out of your own mouths.

[.discourse-part]
_Judge:_ Jury, give in your verdict.

[.discourse-part]
_J+++.+++ Crook:_ Let me have liberty first to speak, it is but few words,
and I hope I shall do it with what brevity and pertinency
my understanding will give me leave,
and the occasion requires; it is to the point in these two heads: Matter of law,
and matter of conscience.
To matter of law I have this to say, First, as to the statute itself,
it was made against the Roman Catholics, occasioned by the gunpowder plot,
and is entitled, for the better discovery and suppressing of Catholic Recusants:
but they have liberty, and we are destroyed,
what in you lies--(Interrupted by the judges and disturbance of the court.) As to conscience,
I have something to say, and that is, it is a tender thing,
and we have known what it is to offend it;
and therefore we dare not break Christ`'s commands, who has said.
Swear not at all; and the apostle James said.
Above all things my brethren swear not.--(Interrupted.)
The court calling again to the executioner to stop my mouth;
which he did accordingly, with his dirty cloth, as aforesaid, and his gag in his hand.

[.discourse-part]
_Judge:_ Hear the jury; who said something to him,
which was supposed to give in the verdict, according to his order;
for they were fit for his purpose, as it seems,
they beginning to lay their heads together, before we had spoke any thing to them,
only upon his words.

[.discourse-part]
_Judge:_ Cryer, make silence in the court: then the recorder,
taking a paper into his hand, read to this purport: that the jury for the king do find,
that John Crook, John Bolton, and Isaac Gray,
are guilty of refusing to take the oath of allegiance;
for which you do incur a premunire,
which is the forfeiture of all your real estates during life,
and your personal estates forever; and you to be out of the king`'s protection,
and to be imprisoned during his pleasure: and this is your sentence.

[.discourse-part]
_J+++.+++ Crook:_ But we are still under God`'s protection.

--

Then the prisoners were remanded to Newgate,
where J. Crook found opportunity to make a narrative of the whole trial,
which was printed as aforesaid, together with the Latin indictment,
in which he showed several errors, either by wrong expressions, or by omissions.
Thus the injustice of these arbitrary proceedings were exposed to public view,
when this trial appeared in print; that the king himself might see thereby,
how ill his subjects were treated.
But at that time there were so many among the great ones and bishops,
who were inclined to promote the extirpation of the Quakers,
that there seemed no human help.
J+++.+++ Crook showed also circumstantially, how in many cases of trial,
they had acted against law; for he himself having formerly been a justice,
knew well enough how, and after what manner,
justice ought to be administered and maintained.
How long he continued prisoner, I cannot tell.
But by this trial alone the reader may see, how the Quakers, so called,
were treated in regard of the oath;
and such kind of proceeding was the lot of many of them,
because the intent of those in authority seemed to be to suppress them quite.

Now follows, (to continue J. Crook`'s words,) a copy of the indictment,
with some notes and observations on the same; whereby it may appear, how false it is,
and how easily it might have been quashed for insufficiency, had we been allowed time,
(which by law they ought to have granted,) and been allowed to have made our own defense;
but that they would not do, but stopped our mouths, as before is said,
by the hands of the executioner, to prevent what otherwise,
(as the judge said,) might have come to pass, namely, having liberty to make our defense,
by that means we should make ourselves famous, and them odious.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
London Session.

I do truly and sincerely acknowledge, profess, testify, and declare, in my conscience,
before God and the world, that our sovereign lord King Charles the Second^
footnote:[It ought to be with some expression of _mutatis
mutandis,_ of the name of king Charles the Second,
instead of king James, who is only named in the act.
This is error it is not agreeable to the statute; for that saith only king James;
and certainly the statute intended no otherwise; for it is said,
For the trial of his majesty`'s subjects, how they stand affected, etc.,
and not the subjects of his majesty`'s heirs and successors.]
is lawful and rightful king of this realm,
and of all other his majesty`'s dominions and countries: and that the Pope,
neither of himself, nor by any authority of the church, or see of Rome,
or by any other means with any other, has any power or authority to depose the king,
or to dispose of any of his majesty`'s kingdoms or dominions,
or to authorize any foreign prince to invade or annoy him or his countries,
or to discharge any of his subjects of their allegiance and obedience to his majesty,
or to give license or leave to any of them to bear arms, raise tumults,
or to offer any violence or hurt to his majesty`'s royal person, state or government,
or to any of his majesty`'s subjects, within his majesty`'s dominions.
Also, I do swear from my heart, that notwithstanding any declaration,
or sentence of excommunication, or deprivation, made or granted,
or to be made or granted by the Pope, or his successors, or by any authority derived,
or pretended to be derived from him or his see, against the said king,
his heirs or successors, or any absolution of the said subjects from their obedience;
I will bear faith and true allegiance to his majesty, his heirs and successors,
and him and them will defend to the uttermost of my power,
against all conspiracies and attempts whatsoever,
which shall be made against his or their persons, their crown and dignity,
by reason or color of any such sentence or declaration, otherwise;
and will do my best endeavors to disclose and make known unto his majesty, his heirs,
and successors, all treasons and traitorous conspiracies, which I shall know or hear of,
to be against him or any of them.
And I do further swear, that I do from my heart abhor, detest, and abjure,
as impious and heretical, this damnable doctrine and position,
that princes which be excommunicated or deprived by the Pope,
may be deposed or murdered by their subjects, or any other whatsoever.
And I do believe, and in my^
footnote:[(My) not in the statute.]
conscience am resolved, that neither the Pope, nor any person whatsoever,
has power to absolve me of this oath, or any part thereof,
which I acknowledge by good and full authority to be lawfully ministered unto me,
and do renounce all pardons and dispensations to the contrary.
And alt these things I do plainly and sincerely acknowledge
and swear according to these express words by me spoken,
and according to the plain and common sense and understanding of the same words,
without any equivocation, or mental evasion, or secret reservation whatsoever.
And I do make this recognition and acknowledgment heartily, willingly, and truly,
upon the true faith of a Christian.
So help me God.

[.signed-section-signature]
WILD.

--

Any Englishman that understands Latin, may, notwithstanding the abbreviations,
indifferently understand this indictment: but a foreigner not understanding English,
though a scholar, will be at a loss in many places: yet to complete my work,
I thought it convenient not to quit such an authentic piece.

Memorand.
That in the writ of Oyer and Terminer, Pasche 9 Hen. 8.
upon the insurrection in London, it was resolved clearly by all the justices of England,
that the justices of Oyer and Terminer cannot in quire one day,
and the same day determine; no more can the justices of the peace, etc.
But the justices of jail delivery, and justices in Eyre, may well do it:
El. 8. Keyleway`'s Rep. f. 159. b. pl. 2.
But they do not call themselves so in the indictment.

If one in his absence be found guilty of an offence, whereby he incurs a premunire,
he hath two months`' time allowed him after he is outlawed, to be heard, 27 Ed. 3 1 cap.
Coke upon Littleton, sect. 201. fo. 134. b. saith,
That the ancient law was, upon trials for felony,
etc. the defendant had fifteen days`' time, or more,
(if he prayed it,) to consider of his answer.

With this agrees Britton, fo. 10. b.

_Fortesque in libro de laubid. legum Angliae._

Mirror of Justice, cap. 4. sect. 7.

The statute of 28 Edw. 1. 9.
provides that inquests shall be of the next neighbors, most sufficient,
and least suspicious, upon penalty of double damages.

25 Edw. 3. cap. 3. No indictor be upon the inquests for felony nor trespass, if challenged.

34 Edw. 3. 4.
Juries to be of the next people, not to be suspected or procured.
With this agrees Regist. fo. 178.

11 Hen. 4. 9.
That if any indictment be made, but by inquest re turned by the sheriff,
(without denomination to him of their names,) by any but his sworn officer,
it shall be void.

By these and the like treatments,
we see how the persecutors endeavored to root out the Quakers, if possible;
for the effecting of which, alderman Richard Brown did whatever he could,
continually letting loose the reins to his exorbitant malice,
without regarding whether that which he was bent against, was really punishable, or not,
whereof the following instance may serve for an evidence.

A certain mender of old shoes, who belonged to the society of the Quakers,
was desired by a laboring man, on a Seventh day of the week, late at night,
to mend a pair of shoes for him, that he might have them again in the morning,
because he had no other to wear.
The cobbler, to accommodate the man, set up at work till after midnight;
but the shoes not being finished then, he went to bed, and rising early in the morning,
went to his work again as privately as he could in his chamber;
but an envious neighbor informed against him for working on a Sunday;
whereupon he was had before the said R. Brown, who committed him to Bridewell,
to be there kept to hard labor.
And he refusing to beat hemp,
as being fully persuaded that he had not deserved such a punishment, was cruelly whipped,
but he bore it with great constancy, and not yielding,
he was turned up among those of his society,
who were imprisoned there on a religious account.

As this case, which befell an honest man, was to be pitied,
so there happened about that time, something among the Quakers at London,
which was facetious and ridiculous:
for several of them being taken out of their religious meetings,
were confined in Newgate, where in the night they lodged in a large room,
having in the middle of it a great pillar,
to which they fastened their hammocks at the one end,
and to the opposite wall on the other, quite round the room, in three stories high,
one over another;
so that they who lay in the upper and middle rows were made to go to bed first,
being obliged to climb up to the higher, by getting into the lower:
and under the lower rank of hammocks, by the wall side, were laid beds, upon the floor.
Such a multitude of bedding for so many persons in one room,
could not but somewhat infect the air, and cause an unhealthy steam:
so that some of the prisoners grew sick, and one of them died.
This caused some bustle,
and it was not without good reason that an ancient grave citizen,
having seen the prisoners thus crowded up, said.
This is enough to breed an infection among them.
And this having been told by Sir Willam Turner, one of the sheriffs of London,
he came into Newgate,
and bidding the turnkey bring down the said prisoners to him in the press-yard,
were he was, he ordered they should return to Bridewell, where they had been before.

Now among these was a shabby fellow, who, to get food without working,
had thrust himself among the Quakers, when they were taken at a meeting,
on purpose to be sent to prison, and to be maintained by them.
This lazy varlet was no small burden to our prisoners;
for whenever any food was brought in to them, either for their money,
or sent to them by their friends,
he did not hesitate to thrust in with his knife in hand, and make himself his own carver;
and such was his impudence, that if he saw the provision was short,
he would be sure to take enough, though others were in need.
But how burdensome soever this lazy drone was to the prisoners, they could get no relief;
for to whom should they complain?
Since the keepers, as well as others, were for vexing and oppressing them.
But now at length an opportunity was come to be rid of his troublesome company.
Among the prisoners was Thomas Ellwood, a man of literature, and of an acute wit,
with whom, long after, I entered into a familiar and pleasing correspondence by letters.
The said Ellwood, when he had heard that they were to be sent to Bridewell,
drew near to the sheriff, and pointing to the aforesaid fellow, said.
That man is not only none of our company, but an idle dissolute fellow,
who has thrust himself among our friends, that he might live upon them;
therefore I desire we may not be troubled with him at Bridewell.
The sheriff smiling, and seeing this fellow standing with his hat on,
and looking as demurely as he could, that the sheriff might take him for a Quaker,
called him forth, and said to him, '`How came you to be in prison?
'`I was taken at a meeting,`' said he.
'`But what business had you there,`' said the sheriff.
'`I went to hear,`' returned the fellow.
'`Ay, you went upon a worse design, it seems,`' replied the sheriff;
'`but I will disappoint you,`' continued he; '`for I will change your company,
and send you to them that are like yourself.`'
Then calling for the turnkey, he said, '`Take this fellow, and put him among the felons;
and be sure let him not trouble the Quakers any more.`'
The fellow, not a little astonished at the hearing of this doom,
on a sudden parted with his Quakership; for off went his hat,
and falling to bowing and scraping, he said to the sheriff,
'`Good your worship have pity upon me, and set me at liberty.`'
'`No, no,`' said the sheriff, '`I will not so far disappoint you:
since you had a mind to be in prison, in prison you shall be for me.`'
Then bidding the turnkey once more to take him away, he had him up,
and put him among the felons.
After this manner this pretended Quaker was rewarded according to his deeds;
and so the true Quakers got rid of him.

Breaking off now this jocose and diverting, though true, narrative,
I return to a serious relation of the sufferings of the faithful,
which caused the death of some of them; among these was Richard Hubberthorn,
who some time before, as has been related, had a conference with the king;
who then promised him,
that he and his friends should not suffer for their opinions or religion.
But now he was in the month called June, violently hauled from the meeting,
bearing the name of the Bull and Mouth, and brought before alderman Richard Brown,
who with his own hands pulled down his hat upon his head with such violence,
that he brought his head near to the ground, and then committed him to Newgate,
where being thronged among others, he soon grew sick; and his sickness so increased,
that he had hardly been two months in prison, before he was taken away by death.
Two days before his departure, being visited by some of his friends,
who asked him if any thing was upon his spirit, he said,
that there was no need to dispute matters, for he knew the ground of his salvation,
and was satisfied forever in his peace with the Lord.
He also said, '`That faith which has wrought my salvation, I well know,
and have grounded satisfaction in it.`'
In the morning before he deceased, one Sarah Blackberry was with him, to whom he said,
'`Do not seek to hold me, for it is too strait for me,
and out of this straitness I must go; for I am wound into largeness,
and am to be lifted up on high, far above all.`'
In this frame of mind he departed this life, in the evening,
and so entered with happiness into eternity.
