== Chapter XIX.

=== 1674-1676.

[.chapter-synopsis]
* Dispute with the Baptists
* Jeremy Ives
* An unfaithful Friend
* Dispute at Barbican between J+++.+++ Ives and the Quakers
* Persecution continued
* Cruelties practised in Leicestershire, Norfolk and Somersetshire
* Sad end of Persecutors
* Death of W. Bayly
* Penitence of M. Hide
* Death of Priest Lampitt
* Barbarous usage of E. Cooper
* Insolence of Informers
* Outrages at Hereford
* Successful appeal of J. Layton
* Death of two hundred Quakers in prison since the Restoration
* Law in Barbados to prevent Negroes from going to Friends`' Meetings
* R. Barclay and Adrian Paets
* Correspondence
* Exposition of some of the doctrines of Friends

The year was now come to an end.
But before I go over to the next, I am to mention that the Baptists in England,
losing from time to time some of their best members,
wrote therefore very fiercely against the Quakers,
endeavoring thereby to render them no Christians.
But those writings were continually answered, and that with so many convincing reasons,
that the Quakers got more adherents by it.
The consequence of this was,
that a public dispute was appointed to be held between the Baptists and the Quakers,
in the meeting-house of the Baptists at London.
For the Quakers, there spoke by turns, George Whitehead, Stephen Crisp, William Penn,
and George Keith; and the opponents were Jeremy Ives, William Kiffin, Thomas Plant,
Thomas Hicks, and Robert Ferguson, a Presbyterian, afterwards eminently known in Holland,
by the fierce declaration drawn up by him in the name of the duke of Monmouth,
when that unhappy prince went over to England with forces,
to dispute the throne against king James.

Jeremy Ives was an eminent teacher among the Baptists,
that had been in prison in London fourteen years before on a religious account,
and chiefly because for conscience-sake he refused to take the oath.

Not long after he wrote a smart letter from the prison, to two of his society,
(who having been imprisoned with him for the same cause, had taken the oath,
thereby to obtain their liberty,) wherein he reproved them for their falling away,
and signified that thus they had increased the burden of their faithful brethren,
from the bearing of which they had withdrawn themselves.
But what a changeable creature is man, if he does not continue watchful,
and keep close to the divine grace, continually laying hold thereon!
For scarce five days passed, but this inconstant Jeremy grew weary of imprisonment,
and took the oath also to get out of prison.
Neither did he stop here; for it is plain that he was now departed from his profession.
To temporize therefore, and to find out excuses for what he had done,
he put forth a book in print, wherein he asserted the lawfulness of swearing.
It was asked of him, whether he was that same Jeremy Ives,
that once had been of such a tender conscience, that he dared not take an oath,
and had afterwards publicly defended swearing as lawful]
And he did not deny the fact, for it was notoriously known:
but he went about to disguise the matter, and said,
'`I am that Jeremy who took the oath of allegiance,
and wrote a book to prove that some oaths were lawful, though not all.`'
Neither did he deny the fore-mentioned letter, for it was extant, and written as follows:

[.embedded-content-document.letter]
--

[.salutation]
Brother Pitman and Brother Shewel,

I am at this time surprised with a holy passion;
and though Jonah could not say concerning the gourd, that he did well to be angry; yet,
if my experience in the word of the Lord does not deceive, I can truly say,
I do well to be angry with you; whom I have had a godly jealously of all along,
that you would be as easily persuaded to part with, as unwilling to suffer for,
your spiritual liberties.
Oh my brethren!
Where is your first love?
How unlike the Christians in former times are you?
Whose zeal was so hot for God, that their eyes prevented the morning,
that thereby they might prevent the rage of the adversary, who, as it is now,
commanded them no more to worship in the name of the Lord.
I always did conclude,
that those that would quit the cause of righteousness would quit the ways of holiness,
as yesterday`'s sad experience has taught, to the perpetual joy of your adversaries,
and the saddening the hearts,
and adding afflictions to the bonds of the prisoners of the Lord.
I do therefore conjure you, as you will answer the great God another day, to consider,
that now is the time for you to look to your ministry,
and to the flock over which the Lord has made you overseers,
that you may be able through grace to say, '`You are clear from the blood of all men;
and observe, that God is now come to prove you,
to see whether you will keep his commandments or not.
Remember when that apostate`'s case was debated,
you had no zeal nor indignation against him, but you smothered all with this,
'`If it were in a matter of faith and worship that he had fallen from,
you would have been as one man against it.`'
Well, behold the Lord is come home to you; the matter now is purely for worshipping God;
now God is proving you to see whether you will obey him or no:
and did not yesterday`'s work witness, that you were willing to prefer the fear of a man,
that must die, before the fear of the great God;
and the fear of them that can kill the body, before the fear of the Lord,
that can cast body and soul into hell?
I have no more to say but this,
that your cowardly temporizing and complying with the precepts of men, makes me jealous,
that your fear towards the Lord is taught by the precepts of men.
I would not be too censorious, but my grounds are great; and my bonds are my crown;
but your cowardly spirit is my great cross.
You little think what a scandal it is among us
to hear it affirmed that one of you should say,
you had rather have given fifty pounds than have sworn,
and yet swear that you swear willingly.
Oh! for the Lord`'s sake, do something that may roll away this reproach;
which that you may, is the prayers of your brother,
who could be contented to write himself,

[.signed-section-closing]
Your companion in tribulation,

[.signed-section-signature]
Jeremy Ives

[.signed-section-context-close]
Jan. 14, 1660.

[.postscript]
====

Brother Ward, my fellow-prisoner, desires to present his love to you,
and so do some others.

====

--

Thus zealously Jeremy Ives wrote to his fellow-teachers, who for human fear,
and to avoid sufferings, had, against their profession,
and the conviction of their consciences, taken the oath.
But who could have imagined on sight of; such letter,
that he himself within so short a space of time,
should have done that which he reproved so severely in others.
Certainly in this case the saying of the prophet Jeremiah seems to be very applicable,
"`The heart is deceitful above all things, and desperately wicked; who can know it?
Let therefore him who stands, be cautious lest he fall.`"
Happy had this man been,
if he had been so sensible of his transgressions as one Edward Chilton,
who though by profession a Quaker, yet when it came to a trial,
either to take the oath of allegiance, or to be premunired, he wavered and fainted;
yet not so, that he fell away totally:
for he became so penitent for the evil he had committed,
that he found himself constrained to give proof thereof
by a letter he wrote to his friends,
who remained prisoners, because for conscience-sake they could not swear; whereas he,
to be released from imprisonment, had taken the oath that was demanded of him.
But of what a bitter relish this became to him,
and what terror and horror he was seized with, the following letter will show:

[.embedded-content-document.letter]
--

[.salutation]
My dear Friends,

I desire to lay before you this my condition in this my fall,
that my fall may be no cause for you to stumble,
but that you by it may be the more encouraged to stand;
for I have yielded to the betrayer, and so betrayed the innocent seed in me;
for I forsook the counsel of the Lord, and consulted with flesh and blood,
and so I fell into the snare of the world, and yielded to the covenant;
and so I rested satisfied in what I had done, for some certain hours;
but when the Lord in his power looked back upon me, then I remembered what I had done;
then I remembered that I had denied truth, which once I had professed,
though once I thought I should have stood when others fell.
So the terrors of the Lord have taken hold on me,
and I lie under the judgments of the Lord.

And now I feel the truth of the words that were spoken by Christ,
'`that he that fails in one tittle, is guilty of all;
and now I feel the truth of that,`' that it is better to forsake wife and children,
and all that a man has, even life itself, for Christ and the truth`'s sake,
than to break one tittle of the law of God written in the heart.`'
So I hope that, by mercy and judgment, the Lord will redeem me to himself again.
The Lord may allow some to fall,
that the standing of them that stand faithful may seem to be the more glorious,
and for them to take heed lest they fall.

Now I know and feel, that it is better to part with any thing of this world,
though it be as dear to one as the right hand, or the eye,
than to break our peace with God.

Pray for me; for my bonds are greater than yours.

[.signed-section-signature]
Edward Chilton.

[.signed-section-context-close]
Windsor, the 22nd of the 11th month, 1660.

--

It is remarkable, that this Chilton in the conclusion of his letter says,
that his bonds were greater than those of his friends, who neither feared a premunire,
nor loss of their liberty, when they must pay so dear for it, as the taking of an oath.
For when any one truly abides in the fear of God, he dares not,
against the convictions of his conscience, transgress the Divine commandments,
and seek evasions to avoid the stress thereof: for certainly God will not be mocked.
Could our Savior have spoken in more plain and express terms than he did, when he said,:
"`Swear not at all.`"
And yet what cunning devices have been invented by those who boast of the name of Christians,
to enervate the force of these express words.
It is not a proper place here to refute their reasons;
but yet I cannot think it unsuitable to show briefly how dangerous
it is to act against the express commandments of sacred writ,
and '`against the conviction of one`'s conscience, thereby to avoid persecution:
for not only the apostle James said, "`Whosoever shall offend in i one point,
he is guilty of all;`" but our supreme lawgiver Christ himself says,
"`Whosoever shall deny me before men,
him will I also deny before my Father which is in heaven.
And whosoever shall be ashamed of me, and of my words,
of him also shall the Son of Man be ashamed, when he comes in the glory of his Father,
with the holy angels.`"
And to encourage us to faithfulness he has also said,
"`Fear not them which kill the body, but are not able to kill the soul;
but rather fear him which is able to destroy both soul and body in hell.`"
Which words indeed are so emphatic,
that it ought not to displease any that I repeat them,
as they have been left on record by the evangelist Luke, thus, "`I say unto you,
my friends, be not afraid of them that kill the body,
and after that have no more that they can do.
But I will forewarn you whom you shall fear: fear him, which after he has killed,
has power to cast into hell: yes, I say unto you, fear him.`"
Can it be otherwise,
but that such words must needs make a powerful impression on a real Christian?
And the more when we consider,
that nothing in the world can retrieve or restore a perishing soul,
as may appear from these of our blessed Lord, "`What is a man profited,
if he shall gain the whole world, and lose his own soul?
Or what shall a man give in exchange for his soul?`"
A clear proof that the whole world, and all that is contained therein,
is not able to save one soul, or to afford any thing that can redeem it.
If I here thought it requisite,
a godly zeal at present would make me say more on this subject;
but not to expatiate too far beyond the limits of this historical tract,
I shall not pursue this digression any further,
but return to my relation from which I thus stepped aside.

To take up again then the broken thread of my discourse, I once more come to Jeremy Ives,
who, to avoid persecution, had taken the oath contrary to his understanding;
and it was Thomas Rudyard, mentioned here before, who objected this to him;
and he feeling himself pinched by it, endeavored to break the stress thereof by saying,
that the reason why in a letter he had blamed a friend,
was for his saying he had rather have given fifty
pounds than have took the oath of allegiance,
and yet swore he took it freely and willingly.
But who sees not what a poor shift this was?

Now to come to the dispute; I already mentioned it was asserted,
that the Quakers were no Christians; and to maintain this, Thomas Hicks said,
'`They that deny the Lord`'s Christ, are no Christians:
but the Quakers deny the Lord`'s Christ,`' etc.
To which W. Penn said, '`I deny the minor,
that is '`that the Quakers deny the Lord`'s Christ.`'
And T. Hicks returned, '`They that deny Christ to be a distinct person without them,
deny the Lord`'s Christ; but the Quakers deny Christ to be a distinct person without them:
therefore,`' etc.
W+++.+++ Penn then desired that T. Hicks would explain
what he meant by the term person And T. Hicks answered,
'`I mean the man Christ Jesus.`'
To which W. Penn replied, '`Then I deny the minor, that is,
'`that we deny the man Christ Jesus.`'
To which Hicks returned, '`I prove you deny the man Christ Jesus.
One of your own writers says, that Christ was never seen with carnal eyes,
nor heard with carnal ears,`' etc.
To this J. Ives added, '`He that denies that Christ was ever seen with carnal eyes,
etc. denies the man Christ:
but the Quakers deny that Christ was ever seen with carnal eyes,`' etc.
George Keith then said, '`I answer by distinguishing:
Christ as God was never seen with carnal eyes; but as man he was seen with carnal eyes.`'
To this J. Ives returned: '`But he was Christ as he was man:
how then was not Christ seen with carnal eyes?`'
To this question G. Keith answered thus:
'`We are to consider that the terms or names Jesus Christ,
are sometimes applied to him as God, and sometimes to him as man; yes,
sometimes to the very body of Jesus: but the question is,
whether do those names more properly, immediately, and originally belong to him as God,
or as he was before he took the manhood upon him; or to the manhood?
We affirm, those names are given to him most properly and eminently as God;
and less properly, yet truly, as man; and least properly to his body,
yes to his dead body.`'
Then J. Ives asked, '`Where do you read that the carcase was called the Christ?`'
This irreverent expression so displeased many, that some cried out,
'`Where did you ever read that Christ`'s dead body was called a carcase?`'
From this disgust W. Penn said, '`I beseech you for the Lord`'s sake,
that we may treat of these things as becomes Christians.`'

G+++.+++ Keith then resuming the discourse, answered J. Ives`'s question thus:
'`I prove that the dead body of Jesus was called Christ, from the words of Mary,
"`Where have you laid him?`"
For she had just before called the body her Lord: likewise the angel said to her,
"`See the place where the Lord lay:`" and that he was Jesus Christ before he took flesh,
I prove from the saying of the apostle,
"`Who created all things by Jesus Christ.`"`' Then T. Hicks said,
'`I will prove the Quakers to be no Christians:`' and J. Ives added,
'`They that say that Christ cannot be seen with carnal eyes,
and was never visible to wicked men, do deny the Lord`'s Christ;
for he was seen with carnal eyes, and by wicked men.`'
To this W. Penn said, '`I distinguish upon the word seen;
wicked men might see him in that bodily appearance,
and yet not see him to be the Christ of God; they saw his manhood,
but not his Christ-ship: this I will prove from Christ`'s words to Peter,
when he confessed him to be Christ, the Son of the living God, saying.
"`Flesh and blood has not revealed this unto you,
but my Father which is in heaven:`" therefore Peter with
a carnal eye could not have seen the Lord`'s Christ,
much less wicked men.
My second proof is from the apostle`'s words,
"`Whom none of the princes of this world knew; for had they known him,
they would not have crucified him.`"
W+++.+++ Penn enlarging a little more on this subject, said also,
that seeing and knowing in Scriptures are sometimes equivalent.
And G. Keith added, '`Christ said, "`He that has seen me,
has seen the Father:`" but no wicked man has seen the Father,
therefore no wicked man has seen Christ, as such.`'
Ives and his companions scoffed at this distinction: but the Quakers averred,
that all who saw Jesus as the carpenter`'s son, did not see him as the Christ of God.
Then Ives asked, '`Is the manhood a part of the Lord`'s Christ?`'
To which W. Penn returned, '`Is this to prove the charge of our denying the Lord`'s Christ.
It seems we must be here to be catechized, and you will not answer us one question,
yet I shall answer J. Ives his question, if he will promise to answer mine.`'

Ives then saying that he would answer it, W. Penn returned, '`I here declare,
that we do faithfully believe that holy manhood to be a member
of the Christ of God:`' and directing his question to Ives,
he said, '`Was he the Christ of God before he was manifest in the flesh?`'
'`He was,`' answered Ives, '`the Son of God.`'
'`But,`' replied W. Penn, '`Was he the Lord`'s Christ?
I will prove him to have been the Lord`'s Christ as well before as after:
first from the apostle Paul`'s words to the Corinthians,
"`That rock was Christ:`" next from Jude, where some Greek copies have it thus,
"`That Jesus brought the people of Israel out of Egypt.`"
'`But to this Ives gave no answer, how often soever he was called upon for it.
And this was no great wonder,
since it was well known that there were such among
the Baptists who favored the Socinian principles.
But Ives, that he might not appear altogether mute, came on again with a question,
saying, '`Do you believe that Christ in his human nature is in heaven?`'
This made G. Whitehead say to the auditory, '`You have heard the charge against us,
and the distinction that has been made between seeing, and seeing of Christ,
as namely between the spiritual saving sight of the Lord`'s Christ,
and the seeing of his outward man, person, or body.
In this last sense it could never be intended that it was not visible to the outward eye;
but it was the spiritual rock which all Israel drank of,
and as he was before Abraham was,
and as glorified with the Father before the world began;
and as Christ himself said to Philip, "`He that sees me,
sees my Father also:`" and only saints, or children of light, could truly say,
"`We have seen his glory as the only begotten of the Father, full of grace and truth.`"
In all which considerations, or senses of seeing,
the Lord`'s Christ was only seen spiritually, and not with carnal eyes.`'
This Ives granted, that so it might be left: yet presently after,
instead of proving the Quakers no Christians, he asked again,
'`Do you believe or own that Christ is in heaven with his human nature?`'
To which W. Penn answered, '`We do believe the man Christ Jesus to be glorified in heaven.`'
Which answer Ives refusing to accept, because it was not in the terms of his question,
Penn asked, '`What difference do you make between the manhood and human nature of Christ?`'
'`None,`' returned Ives, '`if you mean candidly.`'
To which Penn replied, '`I do mean and speak candidly;
we do believe that holy manhood to be in heavenly glory.`'

Now since it began to grow dark, the Baptists desired to leave off,
and to resume the matter at another time; as was done also:
but the parties did not agree for all that;
for though the Baptists continued to assert that the Quakers were no Christians,
yet these had abundance of reasons to maintain the contrary;
and this they did so effectually, that those of the other party,
under a pretense of the meeting-place being overcharged with people,
and that the gallery gave way, broke up the meeting, without a final conclusion.

Persecution in this year was not very sharp at London, but for all that,
active in other places, so that I do not lack matter to make a relation of it;
but to shun prolixity, I will mention but one case.

One Robert Tillet, in Buckingham, sick of a consumption,
and believing his death to be nigh at hand, desired some of his friends to visit him.
At this invitation some came to his house, yet not above the number of fourteen persons;
and two informers went and acquainted a justice of the peace thereof,
who recorded this small assembly as a seditious meeting,
and fined the sick man twenty pounds for this pretended transgression;
and so his goods were seized, and six cows taken from him.
And one Robert Smith, being overheard by the informers to have spoken five or six words,
was fined also twenty pounds as a preacher;
which fine was afterwards extorted from some others then present.

The peace between England and Holland was concluded this year, at the instance of Spain,
but the war between Holland and France continued still.

I now pass over to the year 1675.
About the beginning whereof G. Fox came to London, while the parliament was sitting,
who advised the king to the suppressing of the growth of popery;
but in the meanwhile the Quakers bore the chiefest shock;
for their religious meetings were styled seditious conventicles.

After G. Fox had been at the yearly-meeting of his friends at London, he left the city,
and went to Lancaster, and from there to Swarthmore,
where having a dwelling-place of his awn, he stayed about two years to rest himself:
having contracted distempers by hardships and imprisonments,
which had much weakened his body.
Being there,
he understood that four young students at Aberdeen were convinced
at a dispute held by Robert Barclay and George Keith,
with some of the scholars of that university.
And being visited by some of the neighborhood,
among others came also to him colonel Kirby, his old persecutor,
who now carried himself very lovingly, and bid him welcome into the country.
Yet notwithstanding this appearance of kindness,
sometime afterwards he ordered the constables of Ulverstone to tell G. Fox,
that they must have no more meetings at Swarthmore, for if they had,
they were commanded by him to break them up; and they were to come the next Sunday after.
But this threatening did not make G. Fox afraid; for he, with his friends,
had a meeting on that First day of the week, and none came to disturb them.
During his abode at home, when he did not travel to and fro in the country,
as he used to do, to edify his friends by his ministry, he supplied this with his pen,
and exhorted them by writing, where he could not do it by word of mouth:
besides he wrote other serviceable treatises, for he was a diligent man.

In the meanwhile persecution for the worship of God did not cease altogether:
the act against seditious conventicles gave opportunity to the
malicious to disturb the religious meetings of the Quakers,
who never met in a clandestine manner, but always publicly:
and on this account fines were extorted from them; to which may be added,
that oftentimes they were still very ill treated, and most grievously abused,
as among the rest at Long Claxston in Leicestershire,
where some women were dragged by the neck along the street; and among these a widow,
the skin of whose neck was rubbed off by this rudeness; and an ancient woman,
above seventy, was violently cast down to the ground.
Some of the men were dragged by the hair, and others by their legs,
besides the many blows given them:
and some were trodden upon till the blood gushed out of their mouth and nose.
Yet all this they bore patiently, without making any resistance;
whereby it happened sometimes that some who had not the gift of preaching,
reached others by their patient suffering; showing by their meek behavior,
that their works did agree with their Christian profession:
and though many were robbed of all they had, even clothes and beds not excepted,
yet they continued steadfast without fainting;
though often it was called a meeting when some were come together,
not properly to perform religious worship, as has been related already.

At Kirby Muckloe, where some were come to the house of John Penford,
to provide for their poor, the priest of the parish, called John Dixon,
informed against them by letter to Wenlock Stanly of Branston,
who sent three of his servants to take inspection of the said meeting;
and though these looking into the book,
in which the charitable distributions were entered,
found that this meeting had been only to consider of the necessities of the poor,
yet several were fined, and Penford himself twenty pounds for his house,
and ten pounds for the preacher, when there was never any one there;
but they having heard him speak,
this was counted sufficient to make him pass for a preacher.
Now though he and Richard Woodland appealed for justice,
yet the court positively denied their appeal,
unless they would first take the oath of allegiance.
This was the old snare, so that the hearing of the matter was denied,
and treble damage given against them.

At Lewes in Sussex, the priest, William Snat, became himself an informer,
and went several times to the Quakers`' meeting there;
and from there to the justice Henry Shully, to whom he declared on oath,
in whose house the meeting had been, and who had preached; and this was so gross,
that once he gave a false information with respect to the house;
but the gain proceeding from this work, how abominable soever, did shine so alluringly,
that his kinsman, James Clark, entered upon this informer`'s office:
which any one could easily do, without making suit for it.

In Norfolk, the rage of the persecutors was such, that some having been bereaved of all,
were obliged, even in winter time, (as among the rest, Joseph Harrison,
with his wife and children,) to lie on straw; and yet they, unwearied,
did not leave frequenting their religious meeting; no,
even the dead were not allowed to rest, for outrageous barbarity came to that pitch,
that Mary, the wife of Francis Larder, being dead and buried, was,
by order of one Thomas Bretland, dug up again, whereby the coffin was broken,
which they tied together, and carrying it away, exposed the corpse in the market-place.
Thus this deceased woman was no more allowed to lie quiet in her grave,
than in her sick bed, where the day before her death,
she had been threatened by order of one Christopher Bedinfield,
to have her bed taken from under her while living.
Now the reason of thus taking up the corpse was,
that though her husband was one of those called Quakers,
yet she not being properly a member of that society,
it was taken ill that she had been buried in a plain way,
without paying to the priest his pretended due, for the ordinary service over the dead.

In Somersetshire thirty-two persons were fined for having been at a burial.
The like happened in the county of Derby, where Samuel Roe,
(his wife being deceased,) was fined twenty pounds,
because his friends met in his house to conduct the corpse to the grave.
Of this the priest, John Wilson, was informer to the justice of peace, John Loe;
and out of the house of the said Samuel Roe, was taken the value of thirty pounds;
so that the share of the informer was no less than ten pounds; since according to law,
his due was a third of the spoil.
I could here relate several instances of great adversities,
and sad mischiefs that befell cruel persecutors; but not to expatiate too far,
I have silently passed by many remarkable cases.

Yet, in general terms I may say, that many of the persecutors, both justices, informers,
and others, came to a miserable end: some being by sudden, or unnatural death,
and others by lingering sicknesses, or distempers, or by foul and stinking diseases,
taken out of this life; while some, who by spoil had scraped much together,
fell to great poverty and beggary; whose names I could set down,
and mention also time and place; and among these some rapacious ecclesiastics,
who came to a sad end; but I studiously omit particularizing such instances,
to avoid the appearance of grudging and envy.
Some of those that had been so active in spoil,
signified themselves the terrible remorse of conscience they felt,
because of their having persecuted the Quakers; insomuch,
that they roared out their gnawing grief, mixed with despair,
under the grievous pains they suffered in their body.
And it was judged by many a very remarkable case, that one Christopher Glin,
priest at Burford, who had acted with a very indiscreet zeal against the Quakers,
having about the year 1663, read his text in the pulpit,
and then intending to read his sermon, was on a sudden struck with blindness,
and continued blind till he died.
But none of the persecutors seemed to take notice, or to regard such instances;
for they let their rage loose against the Quakers; who,
for all that continued in patience,
though they did not think it unlawful to give notice
of the grievous oppression their friends suffered,
to those that were in authority;
lest they might have excused themselves as ignorant of these violent proceedings.
Therefore it was not omitted to publish in public print,
many of those crying instances that have been related here,
and to present them to the king and parliament, with humble addresses to that purpose.
But all this found but small entrance.
King Charles it seems was not to be the man that should take off this yoke of oppression;
this work was reserved for others.
His brother James that succeeded him, made a beginning thereof,
with what intention Heaven knows; and William III.
that excellent prince, brought it to perfection as far as it was in his power.

This year deceased at sea William Bayly, coming from the West Indies,
in the ship called the '`Samuel`', of London, in the latitude of 46 degrees and 36 minutes:
he had been a teacher among the Baptists, and had read much in the books of Jacob Behmen,
but could not find thereby true satisfaction to his soul.
And being afterwards entered into society with the Quakers, so called,
he became a zealous preacher among them.
When in this his last voyage he was grown sick, and felt death approaching,
he bid John Clark, master of the said vessel,
remember him to his dear wife and little ones, and also, to G. Fox,
G+++.+++ Whitehead and others; and being filled with joy, began to sing, saying,
'`The creating word of the Lord endures forever.`'
He took several that were about him by the hand, and exhorted them to fear the Lord,
and not to fear death: '`Death,`' said he, '`is nothing in itself;
for the sting of death is sin.
Tell the Friends at London, that would have been glad to have seen my face,
I go to my Father and their Father, to my God and their God.
Remember my love to my dear wife; she will be a sorrowful widow:
but let her not mourn too much, for it is well with me.`'
And having spoken something concerning his outward business to the master,
he said in regard to his wife and children, '`I have left them no portions,
but my endeavor has been to make God their father.
Shall I lay down my head upon the waters?
Well, God is the God of the whole universe; and though my body sink,
I shall swim a-top of the waters.`'
Then taking his leave of the company, he said, '`I see not one of you,
but I wish you all well.`'
And one asking, how it was with him?
he answered, '`I am perfectly well.`'
After having spoken many more sensible words,
about four in the morning he departed quietly, as if he had fallen asleep.
His wife Mary, the same that had formerly been at Adrianople,
and spoken with the emperor of the Turks,
gave an excellent testimony in writing concerning him; and J. Crook,
in a preface to W. Bayly`'s works, said of him,
(the truth of which I know by my own experience,)
'`As he was bold and zealous in his preaching,
being willing to improve his time, as if he had known it was not to be long among us;
so was he as valiant in suffering for his testimony, when called thereunto.
I think I see how once I saw him stand at the bar to plead his innocent cause,
like holy Stephen, in the senate-house,
when the threats of his persecutors resembled the showers of stones,
falling upon that blessed martyr, crying out with a hideous noise, '`take him away,
jailer,`' etc. and yet all this while he changed not his countenance,
except by the additional ornaments of some innocent smiles.
Sometimes by cruel persecutors he has been thrown down and
dragged upon the ground by the hair of his head,
and his mouth and jaws endeavored to be rent and broken asunder,
so that the ground whereon he lay was smeared with his blood: yet,
as if this butchering had not been enough to make
him a fit sacrifice for the shambles of their cruelty,
a heavy gross bodied persecutor stamped upon his breast with his feet,
endeavoring to beat the breath out of his body:
and when this persecutor had done his pleasure, he commanded the jailer to take him away,
and put him in some nasty hole for his entertainment and cure.
And had not the God of Israel been his physician there,
he had been taken from us long before this.`'
Thus far John Crook.

At the beginning of this year, 1676, died at London, Matthew Hyde,
who had made it his business, during the space of about twenty years,
publicly to contradict the Quakers in their meetings,
and to disturb them in their worship of God, thinking from a blind zeal,
that he did God an acceptable piece of service,
by zealously opposing what he judged to be heresy.
Now how much soever this man was bent against them, yet he showed this moderation,
that in his gainsaying he did not behave himself furiously,
but appeared to be well meaning, although he erred exceedingly,
and often hindered the preaching of ministers among the Quakers;
which induced W. Penn sometimes to pray to God very earnestly for him,
and to tell him in the presence of many auditors,
that God would plead with him by his righteous judgments;
and that the time would come he should be forced to confess
to the sufficiency of that light he then opposed,
and to acknowledge that God was with those called Quakers.

This same Hyde being by sickness brought to the brink of death,
desired that G. Whitehead, and some of his friends, might be sent for:
and to one Cotton Oade, who asked him, if he had any thing to say to clear himself,
concerning his having so often opposed the friends called Quakers,
in their declarations and prayers, he said, that he was sorry for what he had done: for,
added he, they are the people of God.
G+++.+++ Whitehead, then, though it was late in the evening, being come to him,
with some others, said, '`I am come in love and tenderness to see you.`'
To which Hide returned, '`I am glad to see you.`'
And Whitehead again, '`If you have any thing on your conscience to speak,
I would have you to clear your conscience.`'
To this Hide replied, '`What I have to say, I speak in the presence of God:
as Paul was a persecutor of the people of the Lord, so have I been a persecutor of you,
his people, as the world is who persecute the children of God.`'
More he spoke, but being very weak, his words could not well be understood.
Then G. Whitehead resumed, '`Your understanding being darkened when darkness was over you,
you have gainsaid the truth and people of the Lord;
and I knew that that light which you opposed, would rise up in judgment against you.
I have often with others, labored with you to bring you to a right understanding.`'
To which Hide said, '`This I declare in the presence of God, and of you here,
I have done evil in persecuting you who are the children of God, and I am sorry for it:
the Lord Jesus Christ show mercy unto me, and the Lord increase your number,
and be with you.`'
After some pause G. Whitehead said to him, '`I would have you, if you are able to speak,
to ease your conscience as fully as you can.
My soul is affected to hear you thus confess your evil,
as the Lord has given you a sense of it.
In repentance there is mercy and forgiveness; in confessing and forsaking sin,
there is mercy to be found with the Lord, who in the midst of judgment remembers mercy,
that he may be feared.`'
Hide being in great anguish, and striving for breath, said, a little after,
'`I have done evil in opposing you in your prayers; the Lord be merciful unto me;
and as I have been an instrument to turn many from God,
the Lord raise up many instruments to turn many to him.`'
G+++.+++ Whitehead resumed,
'`I desire you may find mercy and forgiveness at the hand of the Lord.
How is it with your soul?
Do not you find some ease?`'
'`I hope I do,`' answered Hide, '`and if the Lord should lengthen my days,
I should be willing to bear a testimony for you,
as publicly as I have appeared against you.`'
His wife then said, '`It is enough; what can be desired more?
'`If,`' queried Whitehead, '`the Lord should not lengthen out your days,
do you desire what you say should be signified to others?`'
'`Yes,`' answered Hide, '`I do, you may;
I have said as much as I can say,`' After some silence,
he being much straitened for breath.
Whitehead said, '`If this company be wearisome unto you, we may withdraw.`'
To which he returned,`' you may use your freedom.`'
G+++.+++ Whitehead then taking leave of him, said, '`I shall leave you to the Lord,
desiring he may show mercy and forgiveness unto you, as I hope he will.`'
Upon which Hide replied, '`The Lord be with your spirits.`'

All this was spoken to G. Whitehead and his friends, in the presence of Hide`'s wife,
and some others of his acquaintance, about two hours before his death:
and thus he gave manifest proofs of a sincere repentance; for Elizabeth his wife,
having perceived him to be much troubled in his mind, had asked him,
if he would speak with some of the Quakers?
and he smiting his hand on his breast, said, '`With all my soul.`'
After G. Whitehead and his friends were gone, it being the seventh day of the week,
he desired several times that he might live till morning, and might bear on that day,
(the first day of the week) a testimony for the truth,
he had on that day so often opposed;
yet he signified that he had found some ease to his spirit.
He also exhorted his wife, who conversed much with people that were great in the world,
to use the plain language of the Quakers.
And after some more words to this purpose, spoken by him, with good understanding,
he stretched himself out, and died very quietly.
An evident token of God`'s unspeakable mercy, who wills not the death of a sinner,
but that he should repent and live;
and who entirely knowing the real disposition of man`'s heart, forgives sin by mere grace,
without any merit in man, but for his own sake, as he has said himself,
"`I am he that blots out your transgressions for my own sake,
and will not remember your sins.`"
The truth of which saying very plainly appeared in the converted thief on the cross,
though his impenitent fellow-sufferer hardened his heart against it.

In this year, while G. Fox was at Swarthmore, died William Lampitt,
the priest of Ulverstone, who formerly had been a great friend to Margaret,
now the wife of G. Fox, but grew so envious against the friends she was in society with,
that he said in the year 1652, he would wage his life upon it,
that the Quakers would all vanish and come to nought within half a year.
But on his deathbed he said to one of his hearers, who came to visit him,
'`I have been a preacher a long time, and thought I had lived well;
but I did not think it had been so hard a thing to die.`'

At Norwich now great spoil was made upon the Quakers, for their religious assemblies.
Erasmus Cooper coming once into the house of Anthony Alexander, said to his wife,
who was big with child, he came to seize all she had.
'`All,`' said she, '`and that for seven pounds fine, that is hard.`'
But he slighting what she said, replied, he would not leave her a bed to lie on.
And then began to break the doors with a pick-axe;
he and his companions behaving themselves so desperately,
that it drew tears from some of the neighbors who beheld it;
and the warranted spoilers forced Alexander`'s man to help them; which made Alexander say,
that it was a most unreasonable thing,
to require a servant to assist in the taking his master`'s goods: for which the warden,
Robert Clerk, snarled at him, saying, '`They are our goods.`'
To the house of Samuel Duncon, the aforesaid officers came also,
and with them the informer, Charles Tennison, and the hangman.
Here they stayed several days and nights, and kept Samuel`'s wife, who was big with child,
as a prisoner in her own house, not allowing her to speak with any,
so much as at the door, nor any to come to her.
And after they had broken open all the locked doors,
they took away to the value of about forty-three pounds in goods;
and so insolent the informers were, that one did not hesitate to say,
'`I will make the mayor wait upon me as often as I will, at my pleasure.`'
No, this wicked crew was become so powerful, that none dared oppose them,
for fear of falling into disgrace with the court:
since they were encouraged by such as were in high stations,
and probably at the instance of the Catholics, or Catholicly affected.
The constable, William Poole, coming this summer into a meeting at Norwich,
with an informer, who made him come, and hearing efficacious preaching there,
cried with tears in his eyes, '`What shall I do!
I know the power of God is among you:`' and told the informer,
that if there were a curse hung over any people upon the earth,
it was over the informers.
And Tennison the informer, who had assisted in taking away Samuel Duncon`'s goods,
being afterwards committed to prison for debt,
confessed he never prospered since he took in hand that work;
and said if he were at liberty, he would never meddle with it more.

In Nottinghamshire also great spoil and havoc was made,
to which the justice Robert Thoroton, was greatly instrumental;
for at Sutton he gave forth a warrant to seize the goods of two persons,
one of which was a woman, who having in a meeting spoken five or six words, which,
according to the testimony of some officers that were present,
were not at all like preaching, was however informed against as a preacher,
and so by the said Thoroton fined twenty pounds; and she being unable to pay,
the one half of the fine was charged upon her, and the other half upon John Fulwood.
At another time Thoroton gave order to seize the goods of William Day, a miller,
because he having been at a meeting at Sutton, in the street,
the fine of a pretended preacher, that was unable, was charged upon him;
though Day proved, and the officers who kept the friends out of their meeting place,
declared also, that those words, which were called preaching,
were no more than an answer to what another had spoken.
But for all that, Thoroton, to protect, and to gratify the informer, said,
'`Though but one word were spoken, it is sufficient.`'
A poor woman at South Collingham,
who was already bereaved of almost all that she possessed,
and since by her friends provided with a bed and other necessaries,
was also deprived of this little, because she continued to frequent meetings.
Matthew Hartly, a poor man, who lived by spinning of wool, was likewise,
for frequenting the meeting there, bereaved of what he had;
and so it was with many others, whose names and surnames I could mention,
if I had a mind to enlarge.
And if their friends had not taken care of them, and other impoverished families,
who had lost all by spoil, many might have perished.

In the town of Hereford the meetings were also disturbed from time to time,
chiefly by boys, who threw among those that were met, not only stones, and excrement,
but burning squibs; and used all manner of insolence and mischief they could think of,
against these harmless people, either by breaking the glass windows,
or the forms and seats.
One of the leaders of this turbulent company, was the son of one Abraham Seward,
who about this time was elected mayor;
but when complaints were made to him of the outrageous actions of the said wicked crew,
he pretended to be ignorant of his son`'s doings,
and for all that threatened those that came to him,
with the execution of the law upon them, if they did not leave off to keep meetings.
And as it was well known that the chief master of the town-school
was displeased at the extravagant insolence of some of his scholars,
so it was reported also, that he was forbidden to correct them for it;
and that the college priests had set them on,
and said they would bear them out in what they did;
for some of those brutish boys were choristers.
Two friends went to the justices, Robert Simons and Thomas Simons,
to acquaint them with the excessive abuses they met with.
But the justices not at all regarding their complaint,
the said Robert endeavored to draw some confession of a meeting from one of them,
intending, as he himself said, immediately to have fined him, if he had confessed;
but he was wary.
Now since the insolence of the boys was thus encouraged by authority,
it was no wonder it continued there a whole year.
At length eight men were taken from the meeting, by the aforesaid mayor, Abraham Seward,
and carried to the town-hall; and in their passage along, he said,
they should never meet there more.
To which a friend, going with him, said,
'`We are a people gathered by the power of the Lord;
and therefore the power of man cannot scatter us.`'
Being come to the town-hall, the oaths of allegiance and supremacy were tendered to them,
on which they said, '`We are Christians, therefore cannot break the command of Christ,
which forbids to swear at all; but to render just and lawful allegiance to the king,
we do not deny, nor refuse.`'
And they persisting in their refusal to swear, were committed to prison.
The next day after, one Walter Rogers, a prebend, walking by the '`meeting-house,
and observing how it was broken, said to some, that they were very good boys,
and had done their work better than he thought they had.

At one of the quarter-sessions in Nottingham, one John Sayton appeared, who,
being fined twenty pounds for allowing a conventicle at his house,
in the parish of Blyth, came to appeal for justice.
The witness produced against him, said, '`I was there on that day,
and there were several people met, but were all silent, and no words spoken among them;
but I did not see John Sayton there.`'
And that the said John Sayton was above sixty miles from home the same day,
for which he was fined twenty pounds,
was made appear in open court by substantial evidence.
Then the counsel for the appellant said, in the first place,
forasmuch as there was neither preaching, praying, nor reading,
as their own witness does testify, therefore it was no conventicle.
Secondly, being they cannot prove he was there, therefore how can it be judged,
that he did either wittingly or willingly consent to that meeting,
if they could make it a conventicle?
To this the informer`'s counsel objected, that although there was neither preaching,
praying, nor reading,
yet it was evident enough that they met under a pretense of religious exercise;
and seeing there were more than five, and not of John Sayton`'s family,
therefore it must needs be a conventicle.
And as to the second, seeing they cannot prove he was there,
we must leave it to the consciences of the jury,
whether he did willingly consent to that meeting or no.
After the counsel had spoken on both sides, Peniston Whaley, one of the justices,
who sat in the chair as judge of the court, stood up, and said to the jury,
'`Although there was no visible exercise that can be proved, yet the Quakers say,
they worship God in spirit and truth;
and we know their manner is to sit sighing and groaning,`' etc.
The jury returning, and being asked by the court, '`Do you find it for the king,
or for the appellant,`' answered, '`For the appellant.`'
This so displeased the said justice Whaley, that he bid them go forth again.
But one of the jurymen saying, they were agreed,
and they had considered the thing very well, he thereupon fell into such a rage,
that he said, '`You deserve all to be hanged; for you are as ill as highwaymen.`'
Perhaps he himself was either an informer, or a special friend to such,
and therefore was sorry that the jury deprived him of the booty, or a share of it.
There was now great persecution in all parts of England,
neither did it go better in the principality of Wales.
Nine persons being taken prisoners,
and brought this summer to the court session held for the county of Merioneth,
in the town Bala, upon an indictment for not resorting to their parish churches,
the oaths of allegiance and supremacy were tendered to them, Kemick Eyton,
and Thomas Walcot being judges; and upon their refusal of taking these oaths,
the said judges declared it as their opinion in open court,
that in case the prisoners would refuse the oaths the second time,
they should be prosecuted as traitors, the men to be hanged and quartered,
and the women to be burnt.
But this threat could not make them afraid;
for at the next court session the oaths being tendered them again,
they continued in refusing,
though they solemnly acknowledged allegiance to the king as supreme magistrate;
and thereupon were remanded to close imprisonment, where Edward Rees, one of them,
being above sixty years of age, and not able to bear the cold,
died about the height of the frost, not having been allowed the use of fire.

Sometime before, it happened within the corporation of Pool, in Montgomeryshire,
that the justice, David Maurice,
coming into a house where a small number of people were peaceably met, and all silent,
required them to depart.
Hereupon Thomas Lloyd, one of the company, began to speak a few words,
by way of defining true religion, and what true worship was;
and what he said was so reasonable, that the said justice approved of it as sound,
and according to the doctrine of the church of England;
yet notwithstanding he fined the said Thomas Lloyd in twenty pounds for preaching.

This year died in prison John Sage, being about eighty years of age,
after having been in prison at Ivelchester in Somersetshire, almost ten years,
for not paying of tithes.
And it appeared that since the restoration of king Charles,
above two hundred of the people called Quakers, died in prisons m England,
where they had been confined because of their religion.
I could relate abundance of occurrences this year, if I had a mind to extend my work,
but I study brevity; yet cannot omit to mention, that in this year,
in the island of Barbados, in the West Indies,
a law was made to prevent negroes coming into the meetings of the Quakers,
which was of this tenor:

[.embedded-content-document.legal]
--

Whereas of late, many negroes have been allowed to remain at the meetings of the Quakers,
as hearers of their doctrine, and taught in their principles,
whereby the safety of the island may be much hazarded: be it enacted,
that if at anytime after publication hereof, any negro, or negroes,
be found with the people called Quakers, at any of their meetings,
as hearers of their preaching, he or they shall be forfeited,
one half to such as shall seize, or sue for him or them,
if belonging to any of the Quakers, and the other moiety to the public use of the island;
provided that if he or they be seized, such as seize,
shall bring their actions upon this statute, within three months,
against the owner of the negro, or negroes:
wherein the defendant having ten days summons, shall appear, plead,
and come to trial at the first court after summons,
or judgment to be given by _nihil dicit,_ (in English:
"`he says nothing`") and execution immediately to issue.
And if such negro, or negroes,
do not belong to any of the persons present at the same meeting,
any person or persons may bring an action upon this statute,
against any of the persons present at the said meeting, at the election of the informer,
and so recover ten pounds for every negro, or negroes,
present at the said meeting as aforesaid, to be divided as aforesaid,
and in such actions proceedings to be as aforesaid.
And no person whatsoever, shall keep any school, to instruct any child in any learning,
unless within one month after the publication hereof,
he first take the oaths of allegiance and supremacy,
before some justice of peace of the parish where the party lives,
and have a certificate thereof, or have a special license from the governor,
on pain of three months imprisonment, and forfeiture of 3001bs, of Muscovado sugar,
the one moiety to the informer, and the other to the public use of the island,
to be recovered as aforesaid.
And no person whatsoever, who is not an inhabitant and resident of this island,
and has been so for twelve months together, shall hereafter publicly discourse,
or preach at the meeting of the Quakers, on pain of six months imprisonment,
and forfeiture of 1000 lbs.
Muscovado sugar, the one moiety to such as sue for it,
the other to the public use of the island, to he recovered as aforesaid:
provided that all actions upon this statute,
be brought within six months after the offense.

Read, and passed the council the 21st of April, 1676,
and consented to by his excellency +++[+++the governor]
the same day.

[.signed-section-signature]
Edward Steed, Deputy-secretary.

--

Although in the beginning of this statute,
the instructing of the negroes in the doctrine of the Quakers,
is represented as a thing whereby the safety of the island might be much hazarded,
yet the sequel shows that this was not the matter,
but that it was endeavored to deprive the Quakers of their due liberty.
What was the issue hereof I am unacquainted with.

This year Robert Barclay wrote a letter to the Herr Adrian Pacts,
with whom he had some discourse when the said Herr returned from Spain,
where he had been ambassador for the States of the United Provinces.
This Pacts having a strange opinion of the doctrine of the Quakers,
had a good while ago wrote a letter^
footnote:[To be found in the book called [.book-title]#Prastantium ac
eruditorum virorum Epistole Eccksiastique & Theologica.#
Amatelodami _apud_ Franciscum Halman.
1704]
to Christian Hartzoeker, at Rotterdam, about their doctrine;
and having afterwards discoursed with Barclay concerning
the inward and immediate revelation of the Spirit of God,
this induced Barclay to write a letter on the said subject in Latin,
to the aforementioned Herr, wherein he made a more large reply to his arguments,
than he had done by word of mouth.
This letter being sent over from Scotland to Holland,
was delivered by Benjamin Furly at Rotterdam, to the said Herr Pacts,
with a desire that he might be pleased to return an answer to it,
which he promised he would.
But he continuing deficient in the case,
Furly at last published the said letter in print,
but without mentioning the name of him to whom it was written, only his character,
__Cuidam legato.__^
footnote:[To a certain ambassador.]

In this letter was set down first the objection of the Herr Pacts, namely,
that since the being and substance of the Christian
religion consists in the knowledge of,
and faith concerning, the birth, life, death, resurrection,
and ascension of Christ Jesus,
he considered the substance of the Christian religion as contingent truth;
which contingent truth was matter of fact.
And matter of fact could not be known but by the relation of another,
or by the perception of the outward senses;
because there are naturally in our souls no ideas of contingent truths,
such as are concerning necessary truths, such as, that God is,
and that the whole is greater than the part.
And since it might without absurdity be said,
that God cannot make a contingent truth to become a necessary truth;
neither can God reveal contingent truths or matters of fact,
but as contingent truths are revealed;
and matters of fact not being revealed but by the outward senses,
the conclusion drawn from there is,
that men are not obliged to believe God producing
any revelation in the soul concerning matter of fact,
whether of a thing done, or to be done,
unless there be added some miracles obvious to the outward senses,
by which the soul may be ascertained that that revelation comes from God.
All these arguments Barclay answered very circumstantially, premising first,
that it was falsely supposed that the essence of the Christian religion
consisted in the historical faith and knowledge of the birth,
life, death, resurrection and ascension of Christ.
That faith and historical knowledge is indeed a part of the Christian religion,
but not such an essential part as that without which the Christian religion cannot consist;
but an integral part, which goes to the completing of the Christian religion,
as the hands or feet of a man are the integral parts of a man,
without which nevertheless a man may exist, but not an entire and complete man.
Yet he agrees,
that the historical knowledge of Christ is commonly
manifested to us by the holy Scriptures as the means;
but nevertheless he asserts,
that God could without such an outward mean manifest
the said historical knowledge to our minds:
and also, that a contingent truth may be known by a supernatural knowledge.
And he says,
that when God does make known unto men any matter of fact by divine immediate revelation,
he then speaks as to the ear of the heart of the inward man.
And, that as when any natural idea is excited in us, we clearly know it;
so also when a supernatural idea is raised, we clearly know that whereof it is the idea.
He also holds forth, what properly is the inward supernatural sense in man;
and then he distinguishes between contingent and necessary truths,
and shows how a divine revelation may be known to be such,
saying that natural and spiritual senses are distinguishable by their objects,
and demonstrating how godly men may know they are in the favor of God,
and how the wicked feel the wrath of God as fire.
He also relates after what manner the spiritual senses distinguish the good and the evil;
and he confesses there is in all men, as well the godly as the ungodly,
some sort of idea of God, as of a most perfect being: but he asserts,
that the supernatural idea of God differs much from the natural;
and that in all men there is a supernatural idea of God.
He also shows, wherein the motions of the mind differ from those of the body;
and that there are ideas as well of supernatural, as of natural things.
And showing from where the errors of false likenesses of reason proceed, he says,
that the natural reason cannot perceive supernatural things.
He also asserts,
that the revelations to the prophets were by inward inspirations in their minds;
and that they were most certainly persuaded that they were divinely inspired,
even without any outward miracle;
and that it is by the inspiration of the same divine Spirit,
by which the prophets prophesied,
that we do believe their words and writings to be divine, concerning contingent truths,
as well past as to come.
Moreover he inquires, whether faith comes by outward hearing,
and he shows how the outward senses may be deceived; no,
that often they are vitiated both by outward casualties and natural infirmities,
whereunto the godly are no less subject than the wicked.

All this is treated at large by Barclay, as may be seen in the said letter,
and several years after, when the heer Pacts was at London,
being one of the commissioners for the Dutch East India company,
Barclay spoke with him again, and so represented the matter,
that he readily yielded that he had been mistaken in his notion of the Quakers;
for he found they could make a reasonable plea for the foundation of their religion.
And thereupon R, Barclay translated the said letter into English as follows:

[.embedded-content-document.letter]
--

[.salutation]
My Friend,

Albeit I judge I did fully answer to all your arguments in that conference we had,
concerning the necessity and possibility of inward immediate revelation,
and of the certainly of true faith from there proceeding; nevertheless,
because after we had made an end, and were parting,
you would needs remit to my further consideration the strength of your argument,
as that in which you supposes the very hinge of the question to lie:
that I might satisfy your desire, and that the truth might more appear,
I did further consider of it, but the more I weighed it, I found it the weaker.
And therefore that you yourself may make the truer judgment of it,
I thought fit to send you my further considerations thereon;
(which I had done before now, had not I, both at London and elsewhere,
been diverted by other necessary occasions,) wherein I doubt not,
but you will perceive a full and distinct answer to your argument.
But if you can not as yet yield to the truth,
or think my answer in any part to be defective,
so that there yet remains with you any matter of doubt or scruple;
I do earnestly desire you, that as I for your sake, and out of love to the truth,
have not been lacking to examine your argument,
and to transmit to you my considerations thereon;
so you may give yourself the trouble to write and send me what you have further to say:
which my friend, N. N. who delivers you this will, at what time you shall appoint,
receive from you, and transmit to me your letter;
that at last the truth may appear where it is.

And that the whole matter may the more clearly be understood,
it will be fit in the first place, to propose your argument,
whereby you opposed the immediate revelation of God in the saints:
from there concluding you have fully overturned the
foundation of the people called Quakers.
Which argument of yours is;

That since,
(as you judge) the being and substance of the Christian
religion consists in the knowledge of,
and faith concerning, the birth, life, death, resurrection,
and ascension of Christ Jesus,
you considers the substance of the Christian religion as a contingent truth;
which contingent truth is matter of fact.
From which you reason that:

[.syllogism]
* Matter of fact cannot be known but by the relation of another, or by perception of the outward senses; because there are naturally in our souls no ideas of contingent truths, such as are concerning necessary truths: namely, that God is; and that the whole is greater than the part.--And since it may without absurdity be said,that
* God cannot make a contingent truth to become a necessary truth; neither can God reveal contingent truths or matters of fact, but as contingent truths are revealed: but matters of fact are not revealed but by the outward senses. From which you conclude that
* Men are not even obliged to believe God producing any revelation in the soul concerning matter of fact, whether of a thing done, or to be done, unless there be added some miracles obvious to the outward senses, by which the soul may be ascertained, that that revelation comes from God.

All this you endeavor also to prove from the Scripture, Rom. 10 where the apostle says,
"`Faith comes by hearing:`" and because the apostle speaks
afterwards of those who were sent in the plural number;
from there you conclude that to be spoken of outward preaching by the ministry of men:
and since the apostle uses a question, saying,
"`How shall they believe unless they hear,`" you gathers
from the induction and connection of the text,
that the apostle treats only of outward hearing; from there concluding,
that without outward hearing, faith cannot be produced: and therefore,
that there can be no immediate revelation by the
simple operation of the Spirit in the mind,
unless there be something proposed to the outward senses.

Before I proceed to a direct answer to this argument,
some things are necessary to be premised:

[.numbered-group]
====

[.numbered]
_First_ then; That it is falsely supposed,
that the essence of the Christian religion consists
in the historical faith and knowledge of the birth,
death, life, resurrection, and ascension of Jesus Christ.
That faith and historical knowledge is indeed a part of the Christian religion;
but not such an essential part,
as that without which the Christian religion cannot consist: but an integral part,
which goes to the completing of the Christian religion;
as the hands or feet of a man are integral parts of a man,
without which nevertheless a man may exist, but not an entire and complete man.

[.numbered]
_Secondly,_ If by immediate revelation be understood such a revelation of God,
as begets in our souls a historical faith and knowledge
of the birth of Christ in the flesh,
without the means of the holy Scripture, we do not contend for such a revelation,
as commonly given, or to be expected by us, or any other Christians.
For albeit many other evangelical truths be manifested
to us by the immediate manifestation of God,
not using the Scripture as the means;
yet the historical knowledge of Christ is not commonly manifested to us,
nor to any others, but by the holy Scripture, as the means,
and that by way of a material object:
even as when we see the person of Peter or Paul to our vision faculty immediately,
yet not without the medium of that person concurring
as a material object to produce that sight;
while the light of the sun concurs, as the formal object of that visit or sight.
So that when we livingly and spiritually know the
history of the birth of Christ in the flesh;
the inward revelation or illumination of God, which is like the sun`'s light,
proceeding from the divine sun, does shine into the eye of the mind,
and by its influence moves the mind to assent unto
the historical truth of Christ`'s birth,
life, etc. in the reading or hearing the Scripture, or meditating therein.

[.numbered]
_Thirdly,_ Nevertheless we do firmly assert, that God can most easily, clearly,
and certainly, manifest to our minds the historical truths of Christ`'s birth,
etc. when it so pleased him, even without the Scripture, or any other outward means.
And because this argument seems to be formed against the possibility of such a revelation,
therefore I shall proceed to discuss it: but first you may mind,
that the prophets who foretold Christ`'s coming in the flesh,
and being to be born of a virgin, and afterwards to suffer death,
did know these truths of fact by the inward inspiration of God, without outward means:
for which see 1 Pet. 1:10-11. Now that which has been may be.

[.numbered]
_Fourthly,_ This argument does at most conclude,
that we cannot know naturally any truth of fact,
but by the relation of another without us, or by the perception of the outward senses;
because there are naturally in our minds no ideas concerning contingent truths,
(and every truth of fact is a contingent truth,) as there are of necessary truths.
This then proves, that we cannot naturally know any contingent truth,
but by the relation of another, or perception of the outward senses:
but that hinders not, but we may know a contingent truth by a supernatural knowledge,
God supplying the place of an outward relator; who is so true, that he may,
and ought to be believed, since God is the fountain of truth.

[.numbered]
_Fifthly,_
When God does make known unto men any matter of fact
by divine immediate revelation or inspiration,
God speaking as to the ear of the heart of the inward man,
or as by his finger writing therein,
two things are to be considered in such an immediate revelation.

To _Materiale,_ The matter of fact, or thing revealed, which is contingent.

To _Formale,_ The form or mode, how the revelation is made: which form is an inward,
divine, and supernatural revelation, which is the voice or speech of God,
inwardly speaking to the ear of the inward man or mind of man,
or a divine writing supernaturally imprinted therein.
Now as to the material part, or the thing and matter revealed,
this is indeed a contingent truth, and of itself is not manifest to the mind;
but because of the form, that is, because of the divine mode,
and supernatural inward operation, the matter is known to be true.
For that divine and supernatural inward operation,
which the mind does feel and perceive in itself, is the voice of God speaking unto man,
which by its nature and specific property is as clearly
distinguished and understood to be the voice of God,
as the voice of Peter or James is known to be the voice of such men.
For every being as a being is knowable, and that by its own specific nature,
or property proceeding from its nature; and has its proper idea,
by which it is distinguishable from every other thing,
if so be its idea be stirred up in us, and clearly proposed to us.

[.numbered]
_Sixthly:_ Now as some beings are natural, some supernatural, so some ideas are natural,
some supernatural: and as when any natural idea is excited in us, we clearly know it;
so also when a supernatural idea is raised, we clearly know that, whereof it is the idea.
But the voice of God speaking to the mind of man, is a supernatural being,
and stirs up in us a supernatural idea,
by which we clearly know that inward voice to be the voice of God,
and not the voice or operation of another, or of any evil spirit, or angel,
because none of these have a supernatural idea, as the voice of God,
and his divine operation has: for it is full of vigor, virtue, and divine glory,
as says the psalmist, who had often experience of it;
and we also in our measures are witnesses thereof,
for the voice of God is known to be his by its divine virtue.

[.numbered]
_Seventhly:_ The senses are either outward or inward:
and the inward senses are either natural or supernatural;
we have an example of the inward natural sense in being angered or pacified,
in love and hatred; or when we perceive and discern any natural truth,
such as the natural maxims, namely, that the whole is greater than the part,
etc. or when we deduce any conclusion by the strength of natural reason,
that perception also in a larger sense, may be called an inward sense.
But an example of an inward supernatural sense is, when the heart or soul of a pious man,
feels in itself divine motions, influences, and operations,
which sometimes are as the voice or speech of God,
sometimes as a most pleasant and glorious illustration
or visible object to the inward eye,
sometimes as a most sweet savor or taste, sometimes as a heavenly and divine warmness,
or, so to speak, melting of the soul in the love of God.
Moreover, this divine and supernatural operation in the mind of man,
is a true and most glorious miracle;
which when it is perceived by the inward and supernatural
sense divinely raised up in the mind of man,
does so evidently and clearly persuade the understanding to assent to the thing revealed,
that there is no need of an outward miracle:
for this assent is not because of the thing itself,
but because of the revelation proposing it, which is the voice of God.
For when the voice of God is heard in the soul,
the soul does as certainly conclude the truth of that voice, as the truth of God`'s being,
from whom it proceeds.

====

These things being thus premised, I now proceed to a direct answer.
For what is said, that God cannot make a contingent truth to become a necessary truth,
I agree;
but when any contingent truth is manifest to us by the immediate revelation of God,
there is in it two things to be considered, namely, the thing revealed,
which is contingent; and the revelation itself: which upon the supposition,
that it is a divine revelation, is no contingent truth, but a most necessary truth.
And this all mankind will say, that this proposition,
every divine revelation is necessarily true, is as clear and evident,
as that proposition, that every whole is greater than its part.

But you will say; how knows you that a divine revelation is a divine revelation?
I answer, how knows you that a whole is a whole, and a part is a part?
you will say, by the natural idea excited in me of a whole, and of a part.
I answer again;
even so a divine revelation is known to be such by a supernatural
idea of divine revelation stirred up in us,
and that by a divine motion, or supernatural operation.
But it is no wonder that men, who have no experience of supernatural ideas,
or at least do not heed them, do deny them; which is,
as if a man naturally blind denied light or colors; or a deaf man sounds,
because they experience them not.
Therefore, we cannot dissemble,
that we feel a fervent zeal even divinely kindled in us against such an absurd opinion,
as affirms, that God cannot ascertain us of his will in any contingent truth,
but by proposing it to the outward senses.
This opinion does in a manner turn men into brutes,
as if man were not to believe his God,
unless he propose what is to be believed to the outward senses,
which the beasts have common with us; yes, it derogates from God`'s power,
and imputes weakness to him, as if he could not do that,
which not only both good and evil angels can do, but which the meanest creatures can do,
and the most insensible.
As for instance: the heat of the fire, the coldness of the air and water works upon us;
yes, if a pin prick us, we feel it, and that by the outward sense;
because the objects are outward and carnal:
but since God is a most pure and glorious Spirit,
when he operates in the innermost parts of our minds by his will;
shall not he and his will be clearly felt according to his nature, that is,
by a spiritual and supernatural sense?
For as the nature of God is, so is the nature of his will, that is, purely spiritual,
and therefore requires a spiritual sense to discern it; which spiritual sense,
when it is raised up in us by a divine operation,
does as clearly and certainly know the voice or revelation of the will of God,
concerning any thing which God is pleased to reveal, however contingent,
as the outward sense knows and perceives the outward object.
And it is no less absurd, to require of God, who is a most pure Spirit,
to manifest his will to men by the outward senses, else not to be credited;
as to require us to see sounds, and hear lights and colors.
For as the objects of the outward senses are not to be confounded,
but every object is to have its proper sense;
so must we judge of inward and spiritual objects, which have their proper sense,
whereby they are to be perceived.
And tell me, how God does manifest his will concerning matters of fact,
when he sends his angels to men, since angels,
(as is commonly received,) have not outward senses, or at least not so gross ones,
as ours are?
Yes, when men die, and appear before the tribunal of God,
whether unto eternal life or death, how can they know this,
having laid down their bodies, and therewith their outward senses?
And nevertheless this truth of God is a truth of fact,
as is the historical truth of Christ`'s birth in the flesh.
And which is yet more near:
how do good and holy men even in this life most certainly know,
that they are in the favor and grace of God?
no outward revelation does make this known unto them; but the Spirit,
as says the apostle, bears witness with our spirits, that we are the children of God.
For the mere testimony of a human conscience,
without inward testimony of the holy Spirit,
cannot beget in us a firm and immoveable testimony of our sonship,
because the heart of man is deceitful; and if the testimony thereof were true,
at most it is but a human testimony, which begets in us only a human faith:
but that faith, by which holy men believe they are the sons of God, is a divine faith,
which leans upon a divine testimony of the holy Spirit,
witnessing in them that they are the sons of God.
Moreover, when a good man feels in himself that undeclarable joy of the holy Spirit,
concerning which the holy Scripture speaks,
and which is the common privilege of the saints, how or from where feels he this joy?
Truly, this argument concludes no less against this heavenly spiritual joy,
which is begotten in the souls of the saints by the holy Spirit,
than it does against the immediate revelation of God:
for there is no natural idea of this spiritual joy, else mere natural men, yes,
such as are profane and ungodly, would feel it as much as the godly:
but because it is a supernatural thing,
therefore it can have no true idea but what is supernatural.
Moreover,
how is it that profane men feel sometimes in themselves the wrath of God as fire,
when all things, as to the outward, go as prosperously with them as with the godly,
and oftentimes more prosperously?
For there is no natural idea in men of this inward wrath of God.
There is also an inward grief oftentimes raised up
in wicked men from the sense of this wrath of God,
which very much vexes and torments their minds;
and nevertheless this grief has no natural idea in us:
for oftentimes wicked men feel not this sorrow; for God sometimes is, as it were, silent,
while the wicked sin, as in Psalm 1.

All which things do most clearly demonstrate,
that there are in men supernatural ideas of supernatural beings;
which ideas are nevertheless not perceived by us,
unless they be stirred up by some supernatural operation of God,
which raises up in us supernatural and spiritual senses,
which by their nature are as distinguishable from the natural senses,
whether inward or outward,
as the natural senses are distinguished one from another by their specific difference.
Of which spiritual senses the Scripture speaks frequently, as Heb. 5 and 14.
where is spoken of the spiritual senses in general,
by which the spiritual man has the discerning of good and evil:
which good is of a spiritual nature,
and conduces to feed in us a spiritual and divine life; and the evil is of that kind,
by which the spiritual life is in us hurt; that is to say, sins,
whether carnal or spiritual;
all which cannot be discerned but by such who have spiritual senses stirred up in them,
as says the apostle.
In other places the Scripture also speaks of these spiritual senses in particular;
as of the spiritual seeing. Ps. 34:9.
Of the spiritual hearing, Psalm lxxxv.
V+++.+++ Of spiritual tasting. Ps. 34:8.
Of spiritual smelling, Song. 1:3, Of spiritual touching, Acts 17:8,
and in many other places of Scripture we read of those spiritual senses in particular.
Yes, it is the promise of the gospel, that the glory of God shall be seen of holy men,
such as are clean of heart, even in this life: Isaiah 33:17.
Matt. 5:8. Which were fulfilled in the primitive Christians,
see John 1:14. 1 John 1:2-4. 2 Cor. 3:18, and chap.
iv. 0. But what is this vision of God and divine glory,
which the souls of the saints enjoy in this life,
which is only as the earnest or first-fruits of that
more abundant glorious vision in the life to come,
concerning which the Scripture so much declares,
which is the highest happiness of the immortal soul.

For this argument seems to do no less injury to the saints,
than to rob them of this most glorious treasure both in this life, and that to come.
For there is in us no natural idea of this divine glory,
as there is not of God himself which is any ways proportionable unto so great happiness,
which the Scripture so much declared of,
by which the godly are rewarded partly in this life,
and plenarily in that which is to come.
We confess indeed, there is in all men, as well the godly as ungodly,
some sort of idea of God, as of a most perfect being;
and that therefore this proposition, there exists a most perfect being,
does as clearly appear to human understanding,
as that the whole is greater than the part: and therefore this proposition,
that a most perfect being exists, ought to be numbered among the principles,
that of themselves are manifest.
But this idea of God is as manifest to ungodly, as to godly men; yes,
it is clearly perceived by the devil, as by the most holy angels:
for all the devils know that God is; but yet how blind is the devil, and all wicked men,
as to the vision of God, which is the chief reward of the saints.

There is then either no such vision of God, neither in this life, nor in that to come;
or there is a supernatural idea of God in us,
by which we are made capable of this vision;
which supernatural idea of God differs much from that natural idea of God,
which Cartesius and his followers so much talk of,
(albeit others long before Cartesius did observe this natural idea of God,
and spoke of it.) But the happiness of the saints consists
not in contemplating this natural idea of God,
else the wicked would be as happy as the godly; yes,
the very devil as the most holy angel: since, as is said,
both the devil and most wicked men do as clearly perceive this natural idea of God,
as the most holy men or angels.

If the Scripture then be true, there is in men a supernatural idea of God,
which altogether differs from this supernatural idea: I say, in all men;
because all men are capable of salvation,
and consequently of enjoying this Divine vision.
Now this capacity consists herein, that they have such a supernatural idea in themselves:
for if there were no such idea in them, it were impossible they should so know God.
For whatsoever is clearly and distinctly known, is known by its proper idea;
neither can it other-ways be clearly and distinctly known:
for the ideas of all things are divinely planted in our souls;
for they are not begotten in us by outward objects, or outward causes,
as the better philosophy teaches,
but only are by these outward things excited or stirred up.
And this is true not only in supernatural ideas of God, and things divine,
and in natural ideas of the natural principles of human understanding,
and conclusions from there deduced by the strength of human reason:
but even in the ideas of outward objects, which are perceived by the outward senses;
as that noble Christian philosopher Boetius has well observed;
to which also the Cartesian philosophy agrees.
For when I see any outward object, whether it be a man, or horse, or bird,
the outward object does not treat in my eye, nor yet in my mind the idea of those things;
for the outward object does nothing but imprint in our sensible organs a corporeal motion.
Now there is nothing in a corporeal motion that can form in us the ideas of those things;
for all ideas are of a spiritual nature:
now nothing that is corporeal can produce that which is spiritual,
because the less excellent cannot produce the more excellent,
else the effect would exceed its cause: which is against all sound reason,
that it should bring forth what were of a higher and more excellent kind.
Therefore all ideas, whether of natural or spiritual things,
are divinely implanted in our minds; which nevertheless do not always appear,
but sometimes appear, and sometimes are as it were hid in us,
and sometimes are stirred up in us by causes outward or inward,
and again do as it were sleep and shun our observation,
and seem not to be otherwise distinguished by our minds,
but as thoughts and perceptions of the mind from the mind itself; that is,
as the mode from the subject, or as a bodily motion from the body,
whereof it is the motion: for as is the relation of a bodily motion to a body,
so is the relation of a thought or perception of the mind to the mind.
In this nevertheless they differ, that the mind can move itself, and operate in itself:
which a body cannot do: but as a body can be moved by another,
so also can the mind after this manner be moved by another,
and that both by outward and inward causes, but chiefly by God himself,
in whose hand all souls and creatures are.
But of these things there is enough said at present; and I hope,
I have not thus far impertinently philosophized.

As there are then natural ideas concerning the things of the natural world;
as for instance, ideas of light and colors, ideas of voice and sound,
ideas of savoring and smelling, ideas of tasting and feeling, as of heat and cold,
of grief and joy; it follows also, that there are ideas of supernatural things,
concerning the divine and supernatural things of the divine and supernatural world;
as ideas of those things above-mentioned in the spiritual world.
And as the natural ideas are stirred up in us by outward and natural bodies,
so those divine and supernatural ideas are stirred up in us by a certain principle,
which is a body in naturals, in relation to the spiritual world,
and therefore may be called a divine body; not as if it were a part of God,
who is a most pure spirit; but the organ, or instrument of God, by which he works in us,
and stirs up in us these ideas of divine things.
This is that flesh and blood of Christ, by which the saints are nourished;
which is a mystery to all unregenerated and mere natural men,
never to be reached by them, while they remain in that state.

Now if there be such supernatural ideas, there are also senses,
or perceptive faculties by which those ideas are perceived;
for those are two relatives that suppose and infer one another:
but in wicked men those senses or faculties do as it were sleep,
as the vision faculty of a blind man; but in the godly they are stirred up.
Now by these divine and spiritual senses,
which are distinct and distinguishable from all the natural faculties of the soul,
whether of imagination, or natural reason,
spiritual minded men do behold the glory and beauty of God, in respect whereof,
and for which, all the glory of this world is despicable to them; yes,
even as dross and dung.
And they also hear God inwardly speaking in their souls, words truly divine and heavenly,
full of virtue and divine life; and the savor and taste of divine things, and do,
as it were, handle them with the hands of their souls.
And those heavenly enjoyments do as really differ in their nature from all false similitudes,
and fictitious appearances of them,
which either the mind of man by its own strength can imitate,
or any evil spirit to deceive man can counterfeit;
as a true man differs from the dead image of a man, or true bread, honey, wine, or milk,
does from the mere picture of those things.
And albeit either the imagination of man, or subtlety of the devil,
may counterfeit false likenesses of these enjoyments, by which men may be deceived;
and no doubt many are deceived; that does not hinder,
but that those divine enjoyments are clearly perceived in such,
in whom the divine and spiritual senses are truly opened,
and the true supernatural ideas of those things truly raised up.

And if there be at any time a mistake,
the divine illumination is not the cause of that mistake,
but some evil disposition of the mind;
as happens in those things relating to natural reason.
For there are many false appearances of reason, which differ as much from true reason,
as those false and pretended revelations,
and diabolical inspirations from such as are truly divine.
Now, how many men who would be esteemed philosophers,
are miserably deceived by those false likenesses of reason,
judging their false reasons to be the true similitudes of things and solid ratiocinations;
which nevertheless moves no man of sound reason, to reject sound and solid reason,
as doubtful and uncertain?
For even sound natural reason is an excellent gift of God, and very useful to mankind,
when used in its proper place:
but let none think to comprehend by their natural reason
things that are of a divine and supernatural kind.
And as we use to do, when any one is deceived by false appearances of reason,
we endeavor to reduce them to contemplate the first natural ideas of natural things,
and to meditate therein, which is as a test or touchstone,
by which all the appearances and likenesses of reason are to be examined;
if they contradict them, to be rejected;
so also when any one is deceived by his own imagination, or the cunning of Satan,
thinking any evil inspiration of the devil to be a true divine revelation,
he that is so deceived, is to be reduced to the natural ideas of things,
(if so be that pretended revelation does contradict them,
for no true divine revelation can contradict the true natural
ideas,) or to the supernatural ideas of divine things,
which are most simple, clear, and obvious to the minds of men,
if they will turn their minds to the divine seed in them;
or at least those ideas are readily and easily stirred up.
For as in natural ideas, so in supernatural, some are more easily raised than others:
for there is a certain order both of natural and supernatural ideas,
whereby they are gradually excited: nor is there any mortal man,
in whose mind at some time or other there is not stirred
up some idea that is truly supernatural and divine,
and who has not felt in himself both the wrath and judgment of God for his sins;
and also some tender and gentle taste of God`'s love and goodness,
by which wicked men are invited to repentance.
Now that which is thought to be a divine revelation,
and is felt to contradict any divine and supernatural idea,
which is clearly perceived in the soul,
it is a manifest token that it is not a divine revelation,
but either a false imagination, or the wicked suggestion of some evil spirit.

But to proceed: if we will hear the Scripture,
(as all Christians ought,) it testifies to us,
that God has declared his mind and will even concerning contingent truths to come,
in the prophets; as that of the first to the Hebrews does evidently declare: "`God,
who at sundry times, and in various manners spoke to our fathers in the prophets.`"
Yes, let us hear the prophets themselves; Hosea, chap. 1. says plainly,
"`That the word of the Lord was made in him,`" as it is in the Hebrew.
Habakuk also says, As he was standing on his watch,
to see what Jehovah would speak in him.
And it is so manifest that the most heavenly revelations are by inward illustrations,
and inspirations in the very minds of the prophets,
that it is strange how any that believe in the Scripture should doubt of it.
And if it happened at any time,
such revelations were made in the natural imaginations of the prophets,
or any of their inward natural senses, then it may be confessed,
they could not be infallibly certain they came from God;
unless they also felt God in the divine and supernatural senses,
by which they did most nearly approach to him,
from these superior and most inward senses,
working upon the lower and less noble faculties of the mind.
But whichever way the prophets were certain, that they were inspired of God,
even when they foretold contingent truths to come, it is without doubt,
they were most certainly persuaded, that they were divinely inspired,
and that frequently without any outward miracle.
For John the Baptist did no miracle; and many prophesied,
where there appeared no miracle: as in the Scriptures may be often observed.
And we also by the inspiration of the same Divine spirit,
by which the prophets prophesied, do believe their words and writings to be divine,
concerning contingent truths, as well past as to come; else that faith,
by which we believe the Scripture, would not be divine, but merely human.
And from there we need no outward miracles to move us to believe the Scriptures;
and therefore much less were they necessary to the prophets who wrote them.
For we see in many places of the prophets,
where they declare prophesies as revealed to them of God,
there is not a word mentioned of any outward miracle,
as that by which alone they were certain of it.

Moreover, the falseness of this argument does appear,
in that the Scripture does declare many contingent
truths to have been revealed to the prophets in dreams.
Now as natural and wicked men do not see what they
dream by a real perception of the outward senses,
but by inward ideas which are presented to the mind, and perceived by it,
so it is also in divine revelations of this nature.
Of which we have a clear example in Joseph, the husband of the blessed Virgin, who,
when he observed his wife with child, was told in a dream,
that she had conceived by the Holy Ghost: now I would know,
to which of Joseph`'s outward senses was this revealed?
or what miracle had he to induce him to believe which could neither be proved,
so as to make an infallible application to Mary, by the testimony of the Scripture;
and which being against the order of nature, did choke his reason.
The Scripture mentions no miracle in this matter;
and yet no doubt Joseph had highly sinned had he not believed this revelation,
and notwithstanding, rejected his wife as an adulteress.
But if you say, that according to your hypothesis there must have been a miracle;
that is only to beg the question: and how false this hypothesis is,
the apostle shows clearly, 1 Cor. 2:14. the natural or animal man know not,
receive not, the things of God.
Now divine revelations are of this nature;
if either chiefly or only those things were to be judged by the outward senses,
it would contradict the apostle.
For natural men, yes, the most wicked,
have the use of the outward senses as true and exact as the most godly.
And whereas the apostle adds, "`For they are spiritually discerned,
it puts the matter out of all question: for from there it abundantly appears,
that this discerning is not by the outward senses according to the following verse;
for the apostle says, The spiritual man judges all things:
this then must be done by some senses or properties peculiar to the spiritual man,
and in which he excels the natural man, which is not in the outward senses,
as we all do know.
Therefore the perception of spiritual things cannot be by the outward senses,
either as the chief or only means as is falsely contended for.

Now as to these words of the apostle, Rom. 10.
That faith comes by hearing; Zuinglius observed well,
that the apostle intended not to affirm faith to come by the hearing of the outward word;
neither do the following words prove it, "`How shall they believe, unless they hear?
and how shall they hear without a preacher?
and how shall they preach, unless they be sent?`"
for the apostle uses these words, not as his arguments,
but as objections which might be formed; as the same apostle uses in other places;
to which objections he answers in the same chapter, as appears verse 18.
"`But I say, have not they all heard?
yes, truly their voice went into all the earth:`" that is, of the Father and Son,
or the Father in the word; which word is not only near us,
but according to the same apostle in the same chapter, in our mouths, and in our hearts.
But further you can conclude nothing from this,
but that faith is begotten by outward hearing only, and no otherwise:
for this is the strength of your argument,
that since faith cannot be without outward hearing,
therefore nothing can certainly be believed,
but where something is proposed to the outward hearing.
For if you acknowledge faith can be begotten any otherwise than by hearing,
you loses the strength of your argument: and if that argument hold,
that faith comes only by outward hearing, you destroys the whole hypothesis.
For having before affirmed,
that outward miracles are sufficient to render one certain of the truth of any revelation;
whether it be the healing of the sick, or the raising of the dead, would avail nothing,
because those, (as for the most part all miracles,) are obvious to the sight,
not to the hearing: and if it be not by outward hearing only,
you can conclude nothing from this place.

But I the more wonder your using of this argument,
considering the discourse we had together before we entered upon this debate:
for when we were speaking of the opinion of a certain person,
who denied the certainty of everything, but what was discerned by the outward senses,
you condemned it as most absurd; but why, I cannot conceive,
since there is no great difference between these two opinions:
the one says there can be no great certainty concerning any truths,
whether they be necessary or contingent, but by the perception of the senses:
the other affirms the same of contingent truths, though not of necessary truths.
But among the number of contingent truths you esteems what belongs to Christian religion,
for you reckons the necessary truths only to belong to natural religion.
This then is all the difference, that that other person says,
there is no certainty of any religion, neither natural nor Christian,
but by the perception of the outward senses:
but you say though you esteems the certainty of natural religion to be without them,
yet not of the Christian religion.
But again,
since you esteems that not natural religion but the
Christian religion is necessary to salvation,
you must necessarily conclude, that those truths which are necessary to salvation,
are only known and believed by the benefit of the outward senses: in which conclusion,
(which is the sum of all,) you yields the matter to that other person.

But lastly: if all the certainty of our faith, hope, and salvation,
did depend upon the infallibility of outward senses, we should be most miserable;
since these senses can be easily deceived, and,
by many outward casualties and natural infirmities,
whereunto the godly are no less subject than the wicked, are often vitiated;
and there are, (as the Scripture affirms,) false miracles, which, as to the outward,
cannot be distinguished from the true;
of which we cannot infallibly judge by the outward senses,
which only discern what is outward.

There is a necessity then to have recourse to some other means.

From all which it does appear, how fallacious and weak this argument is:
but thanks be unto God,
who would not that our faith should be built upon so uncertain and doubtful a foundation.
And whoever has known true faith,
or has felt the divine testimony of God`'s spirit in his soul, will judge otherwise,
neither will be moved by such reasonings.
I pray God therefore to remove these clouds, which darken your understanding,
that you may perceive the glorious gospel of Christ;
this is that saving word of grace which I commend you unto;
and that God may give you a heart inclinable to believe and obey the truth,
is the desire of your faithful friend,

[.signed-section-signature]
R+++.+++ Barclay.

[.signed-section-context-close]
From the prison of Aberdeen, in Scotland,
where I am confined for the sake of the testimony of Jesus.

[.signed-section-context-close]
November 24, 1676.

This letter, a year ago,
at the desire of my friend R. B. I delivered into the hands of the afore-named ambassador,
desiring his answer in writing, which he then promised; but not having as yet done,
it was seen fit to be published.

[.signed-section-signature]
B+++.+++F.

[.signed-section-context-close]
Rotterdam, the 28th of March, 1678.

--

[.embedded-content-document.letter]
--

[.blurb]
=== A brief and distinct Solution of the Argument which the Ambassador aforesaid uses against Robert Barclay`'s Thesis, whereby he attempts to evince that not the inward revelation of the Holy Spirit, but the outward by the Scripture, is the principal rule, and foundation of our faith: at least to us Europeans, who have the Scriptures.

As to his argument, as it was transmitted to us,
if he considers the strength and substance of it, thus it stands:
'`The history of the outward coming, nativity, death, resurrection,
and ascension of Jesus Christ, is either necessary to their salvation,
to whom the Scriptures came, or it is not necessary to be known and believed.
If we say the second, namely,
that the history is not necessary to be known and believed
in order to the salvation of us Europeans who have the Scriptures,
then it will follow that we are not Christians, because we deny that true, essential,
and constitutive character of the Christian religion,
which consists in believing that Christ was sent into the world, born of the Virgin Mary,
dead and buried, rose again the third day, ascended into heaven,
where he sits at the right hand of the Father, etc.
But if they say the first,
viz. That the knowledge and faith of the history are necessary to our salvation,
then it will follow, that the Scripture,
and not the inward revelation of the holy Spirit,
is the principal rule and foundation of that historical faith and knowledge.

Now this he endeavors to prove, both from some other principles of the Quakers,
so called, and from R. B.`'s sixth Thesis, after this manner:

That, said the ambassador, is the principal rule and foundation of our faith,
which is the only medium or mean,
whereby that historical knowledge and faith are brought unto us: but,
according to the Quakers, and the sixth Thesis, the Scripture is the only medium or mean,
whereby that historical knowledge and faith are brought unto us: therefore,
according to the Quakers, and the sixth Thesis,
the Scripture is the principal rule and foundation of our faith.

The minor he proves thus: the author of the Thesis,
(says he,) confesses in his sixth Thesis, that there is a people, to whom God,
by some inevitable accident, has made that historical knowledge and faith impossible:
and the reason why that historical knowledge and faith are impossible to that people,
is because they are destitute of the Scriptures, and live in those corners of the world,
whereunto the outward preaching of the history never came;
from which argument it will follow, that the Scriptures are the only medium or mean,
whereby the historical knowledge and faith of Christ came to any people.

For the clearer understanding the solution of this argument,
some things worthy observation are to be considered:

[.numbered-group]
====

[.numbered]
1+++.+++ First then observe, that the force of this argument at most intends to prove this:
That the Scripture is the principal rule and foundation of historical faith and knowledge;
but we with good reason distinguish between historical and saving knowledge,
and between historical and saving faith;
because many may have a historical knowledge and faith,
who have not that which is saving.
Yes, it is possible, that a man, by the inward revelation of the holy Spirit,
may have a historical knowledge and faith,
who yet may not have that faith which is saving; because saving faith has regard to God,
not precisely as revealing some outward history concerning God
and Christ but as revealing very God and Christ by his grace,
goodness, mercy, and power, ready and willing to save us,
according to his unspeakable good-will towards us:
by which saving faith we rest upon God through Christ, our light and life,
as upon our most merciful Father; which faith can neither exist,
nor be conceived without love to God, humility before God, denial,
and diffidence of self; and therefore such a faith is saving.
But historical faith,
though wrought in the hearts of men by the inward
revelation and operation of the holy Spirit,
may be without that divine love, humility and self-denial:
wherefore precisely considered in its own nature, it is not saving.
It was this kind of knowledge and faith which wicked Balaam had,
who saw and knew many historical futurities, and believed them,
but had not saving faith.

[.numbered]
2+++.+++ Observe, secondly.
That the knowledge and faith necessary to salvation, are to be understood two ways,
either by a necessity antecedent, or in way of priority, or by a necessity consequent,
or in way of posteriority.
Necessity antecedent, or in way of priority, is,
when something is absolutely necessary to our salvation,
that we both know and believe it; and because it is necessary,
God does therefore reveal it to us; of which sort are such principles as these, namely:
That God follows men with his love and good-will;
that he invites and persuades them to come unto him;
that he is ready to show favor to men, and pardon their sins,
if they sincerely repent themselves of their past misspent life,
and lead a new one for the time to come;
that God hears the prayers of those that are truly humble and suppliant;
that he is a glorious rewarder of all that live soberly, righteously, and godly;
that he is a most just avenger against all those who despise his grace and love,
and repent not of their sins, etc.
All which, in some degree, are to all men,
even to those who are destitute of the Scriptures,
revealed by that inward evangelical light, which enlightens all men.
Necessity consequent, or in way of posteriority, is,
when something is not absolutely necessary to our salvation, but after a certain sort,
or under some respect, condition, and limitation;
of which kind are those things which are not revealed, because they are necessary;
but because they are revealed, they are necessary to be believed by us: for example;
if God should reveal to any man, that it was his will and command,
he should go to Rome to reprove tyranny and superstition;
certainly this revelation were necessary to be believed to that man`'s salvation,
by a necessity consequent, because that faith is an act of obedience;
and to obey God is necessary to salvation.

[.numbered]
3+++.+++ Observe in the third place,
that among those things that are necessary to be
believed to salvation by a necessity consequent,
there are some things, though not absolutely necessary,
yet are they very profitable and conducive means to our salvation;
of which sort are the historical knowledge and faith concerning God,
the creation and government of the world.
Christ`'s taking flesh, and dying therein for our sins,
etc. whether that historical knowledge come to us,
either by the sole inward revelation of the holy Spirit,
without the medium or mean of Scripture, or also by both, that is,
both by the inward inspiration of the holy Spirit, and by the Scriptures;
which two mediums or means,
do sometimes concur in producing in men historical
knowledge and faith concerning God and Christ,
as is said before, but in a different manner.
The outward revelation, as it is called, of Scripture, is a medium or mean,
by way of material object, in producing that historical knowledge and faith:
but the inward inspiration and revelation wrought in the hearts of men by the holy Spirit,
are a medium or mean by way of formal object,
in producing the same historical knowledge and faith.
By the material object we understand that which is believed;
and therefore the Scriptures which are believed,
are the material object of historical knowledge and faith.
By the formal object we understand the principal motive in respect to the object,
for which the Scriptures are believed.
But the principal motive in respect of the object, is not the Scripture itself,
but that inward testimony of the holy Spirit, which when we hear or read the Scriptures,
when it pleases the most good and great God to inspire the hearts of men,
works an assent in us,
whether it inclines us to assent to the historical
truths hitherto declared in the Scriptures or no:
wherefore we do not affirm that the holy Spirit does ordinarily
and commonly speak in us something that is new,
or declare to our inward hearing those particular histories of God and Christ,
(though God may, if he shall please, do it at this day;) but we say,
that God does by his holy Spirit,
through his sensible and perceptible motions and
operations objectively representing themselves,
move and incline us to assent unto, and believe the Scriptures,
and the historical truths declared of in the Scriptures.

====

These things considered, we affirm,
that though the Scriptures are ordinarily and commonly a certain medium or mean,
by way of material object or condition,
for the producing of historical knowledge and faith in us; and that, commonly speaking,
a necessary mean too,
as being that without which God does not ordinarily
reveal the outward history of God and Christ;
yet we utterly deny that in true Christians the Scripture,
or outward history in the Scriptures, is the principal motive, foundation,
or principal rule of that historical faith, much less of saving faith,
to the producing of which the letter of the Scripture does very frequently,
(as to many of its acts, if not all,) not concur or cooperate,
either as a material object, or as a necessary condition,
which it is commonly called in the schools.
_Causa sine qua non,_ or a cause or condition without which a thing cannot be done,
though it does not influence the effect.

Now for a direct solution of the argument aforesaid, we answer,
that the historical knowledge and faith concerning Christ`'s being born, dead, buried,
etc. to us Europeans, who have the Scriptures, are necessary to salvation,
that is to say, by a necessity consequent, or in way of posteriority,
(as was before explained,) which assertion of ours
nevertheless militates not against the sixth Thesis,
which grants,
that that historical knowledge and faith are impossible
to those who live in those corners of the world,
where the knowledge of the history is lacking:
which impossibility is not absolutely to be understood, but after a sort,
and in some respect; because, without doubt,
God does ordinarily communicate that historical knowledge unto men,
by the medium or mean of the Scriptures; yet not as the principal medium or mean,
much less as by the only one:
because certainly that inward motion of the holy Spirit wrought in our hearts,
moving and inclining us objectively to assent unto, and believe the Scriptures,
is the principal motive in respect of the object, for which we believe the Scriptures,
and therefore is the foundation and principal rule of our historical faith also.

Wherefore we answer unto the minor proposition of the last syllogism,
by plainly and directly denying that minor proposition, namely:
That the Scriptures are the only medium or mean for
attaining to the knowledge of the history:
they are indeed one certain medium or mean, and that necessary;
but they are not the only or principal.
An example for the illustration hereof, occurs in natural and outward vision:
for when I see a white or red rose,
that white or red rose is the material object of my sight,
and one necessary medium for the producing of that sight;
yet that rose is not the only medium or mean; for the light is another,
no less necessary, concurring to produce my sight, by way of formal object,
by means of which I see that rose represented under such or such a color and figure.
Moreover, in that he asserts,
these inward motions brought by the holy Spirit in the hearts of believers,
are so un-discernible by us,
that believers cannot clearly and infallibly distinguish
them from their own private and proper motions;
this he supposes but proves not.
And therein he is deceived, either through his inexperience, or lack of that due waiting,
and attention to those motions in the divine illumination of Christ,
wherewith he has enlightened both him +++[+++the ambassador]
and all men coming into the world.
But our experience, together with the experience of the holy prophets and apostles,
is a stronger motive to induce us to believe,
that divine inward revelation is sufficiently clear
and convincing by its own light and evidence,
than his own bare and naive supposition to the contrary,
by reason of his lack of experience or attention.

As to the Latin, we have not been very curious in this writing, by reason of haste;
yet have briefly answered the argument as a friend communicated it to us by letter;
if he has omitted any thing in this transmission, or we may seem not to have understood,
or touched the strength of the argument, let it be remitted to us; and we,
through divine assistance, shall answer it at large.

[.signed-section-signature]
George Keith, and Robert Barclay.

--

This solution was delivered to the said ambassador,
not long before the epistle cited page 537, and at page 17,
in the Appendix to Sewel`'s [.book-title]#Dutch History.#

[.blurb]
=== A brief Unknotting of an Argument proposed by another person.

Moreover as to what relates to another person`'s argument
against that part of R. B`'s second Thesis,
which asserts,
that divine inward revelation is that which is evident and clear of itself,
moving the well-disposed understanding by its own evidence,
etc. to the end of the Thesis.

The argument is thus formed: Such an evidence as is asserted in the Thesis,
is destructive of faith, because it is not the evidence of faith.
He proves the antecedent by the words of the Apostle,
"`Faith is the evidence of things not seen.`" Heb. 11:1.
By which words the apostle seems to intimate,
that faith has not this kind of evidence; for if it were of things seen,
it would contradict the apostle.

The solution of this argument is easy; for evidence is three-fold.

The first is the evidence of things sensible, appertaining to the outward senses.

The second is the evidence of things intellectual, but natural,
appertaining to natural reason.

The third is the evidence of things spiritual and supernatural,
as they are proposed to the understanding by the inward
illumination and revelation of the Holy Spirit.

The first evidence may be called the evidence of sense, or animal evidence.

The second, the evidence of reason, or rational evidence.

The third, the evidence of faith, or spiritual evidence.

But faith is the evidence of things not seen, that is,
neither visible by the outward senses, or by natural reason; yet these things hinder not,
but that faith may be the evidence of things not seen by the understanding of a man,
not as operating in its own natural way,
but as divinely elevated and assisted by the inward
illumination and operation of the holy Spirit.
Wherefore, though things appertaining to faith may be very obscure,
and as it were mere darkness, both to the outward senses, and natural reason;
yet they have their evidence, if duly proposed to an understanding divinely enlightened.
Is it not said in the same chapter to the Hebrews, concerning Moses,
that by faith he saw God.
That is to say, not by the outward eye, nor by the eye of natural reason,
but by the eye of faith.

The curious may see the original Latin, from which the preceding are translated,
in the Appendix to William Sewel`'s [.book-title]#Dutch History of the Quakers.#
