== Chapter XX.

=== 1677-1684.

[.chapter-synopsis]
* Friends travelling in Holland and Germany
* Princess Elizabeth of the Palatinate
* Correspondence between Princess Elizabeth, and W. Penn and R. Barclay
* Anna Maria Schurman and the Labadites
* Letter of W. Penn to the Council and Senate of Embden
* Rough usage from the Count of Bruch
* Dispute of G. Fox and W. Penn with Galenus Abraham
* Further correspondence between the Princess Elizabeth and W. Penn
* Continued persecution under the Conventicle Act
* Epistle of comfort from G. Fox
* Barclay`'s Apology, and the Ambassadors at Nimeguen
* Death of Isaac Penington
* Queries to the Pop
* G. Whitehead arrested as a Jesuit
* Trial at Ware
* Account of Friends`' sufferings presented to Parliament
* Grant of Pennsylvania
* Admiral Penn
* Persecution at Bristol
* Meetings kept up by Children
* Cases of exceeding Cruelty
* Seven hundred Quakers in prison
* Letter of consolation from W. Dewsbury
* Wilkinson and Story
* Separation
* Address to the King
* Gabriel Shad the Informer
* Death of King Charles

The year 1677 was scarce begun, when G. Fox, though the roads were yet covered with snow,
travelled again.
After he had passed many places, and preached in the meetings of his friends,
he came to York, and going from there to Nottingham, went to the house of John Reckless,
who was sheriff there when G. Fox preached the first time in that town,
and was imprisoned on that account: but he taking G. Fox into his house,
had been so reached by what he spoke, that he embraced the doctrine he held forth,
and never departed from the profession thereof.
From here G. Fox passed through Leicestershire, Derbyshire, Warwickshire,
Buckinghamshire, and Bedfordshire, where he met with William Dewsbury,
and so came again to London, where having assisted at the annual meeting, he,
with William Penn, Robert Barclay, George Keith, etc. went over to Holland,
to see his friends there, and to edify them with his gift.
William Penn and Robert Barclay travelled up into Germany,
and since R. Barclay the year before had spoken with the princess Elizabeth of the Palatinate,
daughter of Frederick, king of Bohemia, and sister of Sophia, late duchess of Hanover,
mother of George, king of Great Britain,
W+++.+++ Penn had also written two letters to her from England,
which she answered by this following:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Hereford, May 2, 1667.

This, friend, will tell you that both your letters were very acceptable,
together with your wishes for my obtaining those virtues which may make
me a worthy follower of our great King and Savior Jesus Christ.
What I have done for his true disciples is not so much as a cup of cold water:
it affords them no refreshment;
neither did I expect any fruit of my letter to the duchess of L. as I have expressed
at the same time unto B. F. But since R. B. desired I should write it,
I could not refuse him,
nor omit to do any thing that was judged conducing to his liberty,
though it should expose me to the derision of the world.
But this a mere moral man can reach at; the true inward graces are yet lacking in.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Elizabeth.

--

G+++.+++ Fox also from Amsterdam wrote a letter to this virtuous princess,
wherein he commended her modest and retired life,
and exhorted her to piety and godliness: to which she answered with this letter:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

I cannot but have a tender love to those that love the Lord Jesus Christ,
and to whom it is given not only to believe in him, but also to suffer for him:
therefore your letter, and your friends`' visit, have been both very welcome to me.
I shall follow their and your counsel, as far as God will afford me light and unction;
remaining still

[.signed-section-closing]
Your loving friend,

[.signed-section-signature]
Elizabeth.

[.signed-section-context-close]
Herford, the 30th of August, 1677.

--

This correspondence gave occasion to William Penn and Robert Barclay,
to pass towards Herford, a town on the frontiers of Paderborn,
and to give the said princess, who resided there, a visit.
With her lived Ann Maria, countess of Homes; and in one of the chambers of the princess,
William Penn and Robert Barclay had a meeting with the princess, the countess,
and several others, to their great satisfaction.
And the countess, who was one of Labadie`'s adherents, signified to William Penn,
that she wished a meeting might be had where the inferior servants might freely appear.
William Penn not refusing this, the princess consented to it; and after the meeting,
(where she was not present,
that so her servants might have a more free access,) she
expressed much satisfaction in having had that good opportunity.
And then so earnestly invited William Penn and Robert Barclay,
(who lodged at an inn,) to sup with her,
that they not being well able to refuse the invitation, yielded to it.
There was then with her a French woman of quality,
who having had before a very slight opinion of the Quakers, now became deeply broken,
and very affectionately kind and respectful to William Penn and Robert Barclay.
The next day was the first of the week;
and it being agreed with the princess to have another meeting,
William Penn desired that not only as many of her own family,
but as many of the town as would willingly be there, might be admitted.
To this she yielded.
And thus William Penn and Robert Barclay had a large opportunity to preach effectually,
and to discharge themselves.
After the meeting was done, the princess came to William Penn,
and taking him by the hand,
she spoke to him of the sense she had of the power
and presence of God that had been among them;
and thus going on she broke forth into an extraordinary passion, crying out,
'`I cannot speak to you, my heart is full,`' clapping her hand upon her breast.
This affected William Penn not a little,
yet he spoke a few words to her by way of admonition; and then taking his leave of her,
she said, '`Will you not come here again?
Pray call here as you return out of Germany.`'
To this he returned, '`We are in the hand of the Lord, and being at his pleasure,
cannot so fully dispose of ourselves.`'
Solemn I leave then being taken, Robert Barclay returned to Amsterdam,
and William Penn went to Paderborn, and so by the way of Cassel,
(where he spoke with the aged and learned Dureus,) to Frankfort.
Here he found several persons of note, with whom he had several times a meeting,
and once at the house of a young gentlewoman, noble of birth,
called Johannah Eleonora Merlane, who said to him, '`Our quarters are free for you,
let all come that will come; and lift up your voices without fear.`'

Departing from there William Penn came to Chrisheim, a village near Worms,
where then lived some of his friends, who afterwards went to Pennsylvania,
and settled themselves there.
While William Penn was in the Palatinate,
he wrote an exhortatory epistle to Elizabeth princess Palatine,
and Anna Maria countess of Homes;^
footnote:[See Penn`'s [.book-title]#Travels in Holland, etc.# 3rd impression, p. 77. Ibid. p. 84.]
and then went to Heidelberg, the chief city of the Palatinate,
to speak with the prince Elector, Charles Ludowick,
brother of the said princess Elizabeth;
but the said prince then happened to be out of town:
and since this chief message was to desire the prince that
the Quakers at Chrisheim might be treated more mildly,
for tithes were exacted from them not only by the parson of the village,
but also by the Catholic priests of Worms; and the vaught, or mayor of the town,
endeavored to restrain their due liberty of religious meeting together,
he from there took occasion to write a letter in their favor to the said prince,
because he had not been able to speak to him.
Returning afterwards to Chrisheim, and preaching there in a meeting of his friends,
he was overheard by the vaught, or chief officer,
who stood at the back-door that he might not be seen,
who was so well pleased with what he heard, that he afterwards told the parson,
that it was his work, if the Quakers were heretics, to discover them to be such:
'`But for my part,`' continued he, '`I heard nothing but what was good;
and therefore I would not meddle with them.`'
For the parson had busied himself to persuade the
vaught that it was his duty to suppress heresy:
but the vaught made it appear that he had no mind to persecute for religion`'s-sake.
W+++.+++ Penn having now cleared his conscience, returned by way of Frankfort, Cologne, Cleves,
etc. to Amsterdam, where at Cologne he received a letter from the princess Elizabeth,
in answer to that he had written to her from the Palatinate:
the said letter was as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
September, 1677.

[.salutation]
Dear Friend,

I have received your greetings, good wishes, and exhortations, with much joy,
and shall follow the latter as far as it will please
our great God to give me light and strength.
I (Jan say little for myself, and can do nothing of myself;
but I hope the Lord will conduct me in his time, by his way, to his end,
and that I shall not shrink for his fire.
I do long for it; and when he assures my ways,
I hope he will give me power to bear the cross I meet therein;
I am also glad to hear the journey has been prosperous
both in the constitutions of your bodies,
to withstand the badness of the weather, and in the reception you had in Cassel,
Frankfort, and Chrisheim.
Nothing surprised me there but the good old Dury,
in whom I did not expect so much ingenuousness, having lately wrote a book, entitled,
[.book-title]#Le Veritable Chretien# that does speak in another way.
I wish to know what reception you have had at Fredericksburg,
and if this find you at Cleves,
I wish you might take an occasion to see the two pastors of Mulheim,
which do really seek the Lord, but have some prejudice against your doctrine,
as also the countess there.
It would be of much use for my family to have them disabused;
yet God`'s will be done in that, and all things else concerning

[.signed-section-closing]
Your loving friend in the Lord Jesus,

[.signed-section-signature]
Elizabeth.

--

While William Penn made this journey into Germany,
George Fox was gone to Hamburg and Frederickstadt, to visit his friends there;
and Penn being returned to Amsterdam, went from there to Friesland,
and met George Fox as he was coming back to Holland, at Leewarden;
from which he made a step to Wiewart, where a society of the Labadites dwelt.
Here he spoke with the famous Anna Maria Schurman, the gentlewomen Somerdykes,
the French pastor Peter Yvon, and others.
After some discourse from both sides,
when Yvon had given a relation concerning John de Labadie,
how he was bred among the Jesuits, and deserted them,
and embraced the Protestant religion,
and how becoming dissatisfied with the formal Protestants,
he with some that adhered to him, had separated themselves from the vulgar assemblies,
Anna Maria Schurman began to speak, and gave an account of her former life,
of her pleasure in learning, and her love to the religion she was brought up in,
but confessed she knew not God or Christ truly all that while.
And though from a child God had visited her at times,
yet she never felt such a powerful stroke, as by the ministry of John de Labadie:
and then she saw her learning to be vanity, and her religion like a body of death;
and therefore resolved to despise the shame,
desert her former way of living and acquaintance,
and to join herself with this little family, that was retired out of the world.
This and much more she spoke in a sensible frame, and with a serious mind,
not without some trembling.
And then one of the Somerdykes gave also an ample relation, concerning her inward state,
and how she had been reached by the preaching of Labadie;
and how before that time she had mourned because of the
deadness and formality of the vulgar Christians,
and said within herself,`' O the pride, the lusts,
the vain pleasures in which Christians live!
Can this be the way to heaven?
Is this the way to glory?
Are these followers of Christ?
O no!
O God where is your little flock.
Where is your little family that will live entirely to you, that will follow you?
Make me one of that number.`'
Then she told how being pricked to the heart, when she heard Labadie preach,
she had resolved to abandon the glory and pride of this world; and further said,
that she counted herself happy to have joined with this separated family.
After some others had likewise given an account of their change,
William Penn also gave a circumstantial relation,
how he had been gradually drawn off from the vanity and pride of life;
what adversities he had met with in the university at Oxford,
because of his not joining with the debauchery committed there; and how,
after having lived some time in France,
he had been convinced by the effectual ministry of Thomas Loe,
and so came to be joined with the despised Quakers.
This his relation he concluded with a serious admonition how they ought to go on,
and to grow in the true fear of God.
At parting, one of the pastors asked him if the truth rose not first among a poor,
illiterate, and simple sort of people.
'`Yes,`' answered William Penn;
'`and it is our comfort that we owe it not to the learning of this world.`'
To which the pastor returned,
'`Then let not the learning of this world be used to defend
that which the Spirit of God has brought forth;
for scholars now coming among you,
will be apt to mix school learning among your simpler and purer language,
and thereby obscure the brightness of your testimony.`'
W+++.+++ Penn, having answered to the purpose, took his leave,
and travelled by way of Groninghen to Embden,
where the Quakers at that time were persecuted severely with imprisonments and banishments:
but I wave the relation thereof, because it has long ago been published in print,
and the magistrates there,
being afterwards moved to pity by the persecution the protestants suffered in France,
came to a better resolution, as may be mentioned in the sequel.

When W. Penn came to Embden, he went to speak with the burgomaster Andre, at his house,
and asked him if he and the senate had not received a letter
in Latin from an Englishman about two years since,
concerning their severity towards the people called Quakers?^
footnote:[Which being translated into English, runs thus,
and deserves the serious consideration of all magistrates.]
The burgomaster said he had.
W+++.+++ Penn then replied, '`I am that man,
and am constrained in conscience to visit you on their behalf,`' etc.
The burgomaster deported himself with more kindness than was expected,
and gave some faint hope of alteration;
but it appeared sufficiently that the senate was not as yet so disposed,
for persecution continued there yet a long while.

A copy of W. Penn`'s letter, being translated into English, runs thus,
and deserves the serious consideration of all magistrates.

[.embedded-content-document.address]
--

[.letter-heading]
To the Council and Senate of the City of Embden.

The King of kings, and Lord of lords, who is God of all the families of the earth,
incline your hearts to justice, mercy, and truth.

The noise of your severe treatment of several persons that are inhabitants of your state,
reproachfully termed Quakers, has reached these parts,
and filled several with compassion and surprise:
compassion to hear of the miseries of men innocent and upright,^
footnote:[Our account says, some were cruelly beaten by order; others banished;
some put in a dungeon, and fed with bread and water only;
several fined greater sums of money, it is thought, than they had to pay.]
against whom you have nothing to object,
but the pure exercise of their conscience to God; surprise, that you, a Protestant state,
should employ your civil power to deter, punish,
and grievously afflict men for answering the convictions of their consciences,
and acting according to the best of their understanding.
I think you should not be oblivious of your own condition in the loins of your ancestors,
who, you think, with great reason and justice,
strenuously advocated the cause of liberty of conscience
against the Pope`'s bulls and the Spanish inquisition;
how did they anti-christian all force on conscience or punishment for non-conformity?
Their own many and large apologies,
and particularly their demands at the diets of Nurimburg and Spire,
are pregnant proofs in the case;
and your practice does not lessen the weight of their reasons; on the contrary,
it aggravates your unkindness, let me say, injustice.

Protestants,
(and such you glory to be thought,) got their name by protesting against imposition;
and will you turn imposers?
They condemned it; and will you practice it?
They thought it a mark peculiar to the beast;
and can you repute it the care of a Christian magistracy?
I mean, that persons must not live under your government,
unless they receive your mark in the forehead or right hand?
Which in plainer terms is, to submit their consciences to your edicts,
and to ask your leave what religion they should be of.
Remember, that faith is the gift of God; and, that what is not of faith is sin:
nothing can be more unreasonable, than to compel men to believe against their belief,
or to trouble them for practicing what they believe,
when it thwarts not the moral law of God.

You doubtless take yourselves to be Christians,
and would esteem it no little injury to be otherwise represented;
yet what more unchristian,
than to use external force to sway the consciences
of men about the exercise of religious worship.

Christ Jesus, the Lord and author of the Christian religion,
censured his own disciples that would have had fire from heaven to destroy
those that conformed not to what their blessed Master taught:
are you surer of your religion?
Are you better Christians.
Or have you more Christian authority, than they that were the chosen witnesses of Jesus?
However, remember, they called but for fire from heaven;
and can you kindle fire on earth to devour them?
Them, I say, that are of your own people, merely for their religious dissent from you?
Doubtless,
if that was then thought no fit argument to induce
men to conformity by him that was wiser than Solomon;
it reflects greatly upon your modesty and prudence, that you should find out new ways,
or rather old exploded ones to effect so ill a design.
Besides, you do not say you know ail you ought to know,
or that there is nothing further to be revealed; have a care therefore,
that you persecute not angels, by being harsh to that which you call strange;
think not ill, much less speak, and least of all act,
that which is so against what you do not perfectly understand.
I am well persuaded, that those you inflicted such severe penalties upon,
mean well in what they believe, (to be sure much better than you think they do,
or else you are extremely to blame,) and that the
reason of their present distance from you,
is not to introduce or insinuate dangerous or exotic opinions,
but to live a life of more holiness, purity, and self-denial, than before:
they do not think that you walk up to your own principles;
and have reason to believe the power of godliness is much lost among you;
and having long lain under a decay and languishing
of soul for lack of true spiritual nourishment,
they have now betaken themselves to that heavenly gift and
grace of God in themselves for divine satisfaction,
even that holy anointing that is able to teach them
all things necessary for them to know;
as the blessed apostle speaks; and they find the joys of the Holy Ghost in so doing:
and I am persuaded they are not less peaceable, sober, just,
and neighborly than formerly,
and altogether as consistent with the prosperity of civil society;
and I am sure it is both found and confessed among us here by some men of quality,
learning, and virtue.
Further, be pleased to consider with yourselves,
that you justify the ancient persecutions of the Christians and first reformers,
whose superiors thought as ill of them, as you do of these men; no,
you show the Catholics what to do in their dominions to your own brethren.
Do as you would be done by: if you would have liberties give it;
you know that God`'s witness in your hearts dictates this to you as an immutable law.

Could you give faith, it were more excusable for you to punish such as should resist;
but since that is impossible, the other is unreasonable;
for it is to afflict men for not being what they cannot be unless they turn hypocrites:
that is the highest pitch your coercive power can arrive at;
for never did it convert or preserve one soul to God;
instead thereof it offers violence unto conscience,
and puts a man either upon the denial of his faith and reason,
or being destroyed for acting according to them:
but what greater disproportion can there be, than what lies between the intellect of man,
and prisons, fines, and banishments?
They inform no man`'s judgment, resolve no doubts, convince no understanding:
the power of persuasion is not to be found in any such barbarous actions,
no more than the doctrine of Christianity.
This course destroys the bodies and estates of men, instead of saving their souls:
were they in the wrong, it would become you to use God`'s weapons,
his sword of the Spirit, that saves the creature; and slays the evil in him;
this course tends to heart-burnings and destruction; I am sure it is no gospel argument.

I beseech you for the sake of that Lord Jesus Christ,
that suffered so patiently for his own religion,
and so sharply prohibited making other men to suffer for theirs,
that you would have a care how you exercise power over men`'s consciences.
My friends, conscience is God`'s throne in man, and the power of it his prerogative:
it is to usurp his authority, and boldly ascend his throne, to set lords over it.
Were their conduct scandalous, and destructive to the good of your state,
you were to be held excusable: but verily, no man of mercy and conscience,
can defend your practice upon poor men so peaceable and inoffensive.
Gamaliel will rise up in judgment against you, if you persevere in this course.
Do not you help to fill the catalogue of persecutors: in much love I entreat you;
but as becomes Christian men and true Protestants,
leave men to their particular persuasions of affairs relative of the other world,
which have no ill aspect on the affairs of this:
but vice has an evil consequence as to both: therefore punish vice,
and affect truth and righteousness,
and bend not your civil power to torment religious dissenters, but to retrieve good life,
lamentably lost amidst the great pretenses that are made to religion.
Doubtless magistracy was both ordained of God, and elected by men,
to be a terror of evil-doers, and not to them that do well,
though of different judgments.
You oppugn the Roman church for assuming infallibility to herself,
and yet your own practice makes you guilty of the same presumption or worse:
for either you do exercise that severity upon an infallible knowledge, or you do not;
if you do, you take that to yourselves your principle denies to any church whatever,
which is a contradiction; if you do not,
you punish people for not conforming to what you yourselves deny any certainty about:
and how do you know but you compel them to that which is false,
as well as that which is true?
Verily, this dilemma is not easily avoided,
as well as that this inhuman practice will stain your profession, infame your government,
and bring a blot upon your posterity.

Remember that they are men as well as yourselves, born free,
and have equal plea to natural and civil common privileges with yourselves:
the different persuasion of their consciences about things relating to another life,
can no ways render them unfit for this; it neither unmans nor uncivilizes them.
They have the same right to their liberty and property as ever,
having by no practice of theirs in the least forfeited any of those human advantages,
the great charters of nature and Scripture have conferred upon them:
and the opulence of your neighbors and prosperity of their affairs,
prove to you that indulgence is not inconsistent with policy; howbeit,
you have now tried the sincerity of their procedure by what you have already inflicted,
and they sustained; let the time past suffice,
and make them not sacrifices for their conscientious constancy.
If they are in the wrong, it is more than they know;
will you persecute men for being what they must be, if they will be true to themselves;
this were great violence; rather commiserate than thus violently compel them.
I beseech you, seek some cheaper way to accommodate yourselves,
than by their destruction, who are so very remote from seeking yours.
Oh! the day will come, wherein one act of tenderness about matters of conscience,
shall find a better reward,
than all the severity by which men use to propagate their persuasions in the world;
and there is great reason for it, since the one flows from the Savior,
the other from the destroyer of men.
In fine, let your moderation be known unto all men, for the Lord is at hand,
whose reward is with him; and he will recompense every man, family, state, kingdom,
and empire, according to the nature of their works, committed in his mortal body;
at whose bar it shall never be laid to your charge,
that out of fear of taking God`'s office out of his hands,
and being unmerciful to tender consciences,
you admitted men of differing judgments to dwell quietly among you: truly,
you cannot be too tender in this point.

Imitate the God of nature and grace, by being propitious to all; his sun shines on all;
his rain falls on all, ho gives life and being to all; his grace visits all,
and in times of ignorance he winks: and though such you may repute ours,
I hope you cannot think you wink at it, who make such broad tokens of your displeasure.
Oh! how forbearing and merciful is ho towards you?
Have you so lately escaped the wrath of enemies,
and can you already thus sharply treat your friends?
Had he entered into judgment with you, what had become of you?
Let his goodness to you prevail with you, to express clemency to others,
that so the great God of the whole earth, even the God of the spirits of all flesh,
who respects not the persons of the rich, poor, or powerful in judgment,
may show you mercy in the day of his righteous judgments.
Amen.
Your friend with the greatest integrity in the universal principle of love and truth,

[.signed-section-signature]
W+++.+++ Penn.

[.signed-section-context-close]
London, December 14, 1674.

--

After W. Penn had stayed some time at Embden, he took a turn again to Herford,
where he was received very kindly by the princess Elizabeth, and the countess of Homes;
and more than once he had a meeting in her chamber;
and the princess was so reached and affected by his speaking, that she said,
'`I am fully convinced;
but oh my sins are great!`' this gave occasion to W. Penn
to speak to the princess and the countess apart,
with respect to their particular conditions; which made a deep impression on their minds,
especially the countess`'s. Being much pressed by the princess to stay and sup with her,
he yielded: and the countess from a serious sense of her compliance with the world,
told him, _'`Il faut que je rompe, il faut que je rompe,`'_ i. e. '`I must break off,
I must break off.`'
And at another time with a weighty countenance she cried out,
'`O the cumber and entanglements of this vain world; they hinder all good.`'
Once the princess said to them, '`It is a hard matter to be faithful to what one knows.
I fear that I am not weighty enough in my spirit.`'
At another time she told him,
'`Among my books I have records that the gospel was
by the English first brought from England into Germany;
and now it is come again.`'
Thus this excellent princess signified how highly she valued
the preaching of the gospel to her by W. Penn,
and how much she esteemed his labor and ministry.
When he took his leave of these eminent persons, having taken the princess by the hand,
which she received with a weighty kindness, being much broken in spirit,
he wished the blessing and peace of Jesus with and upon her;
and then exhorting the countess, she frequently besought him to remember her,
and implore the Lord on her behalf.

Next taking wagon for Wesel, from there he travelled to Duisburgh, Dusseldorp,
and Cologne, and then back again to Dusseldorp,
to see if he could get an opportunity at Mulheim,
to speak with the countess of Falkenstein,
who was reported to be a very religious person,
and therefore in his former journey he had endeavored to visit her, but in vain;
for the count of Bruch and Falkenstein, her father,
kept her as it were under a confinement, because she was of a religious temper;
and therefore he called her a Quaker,
though she did not at all converse with any of the Quakers.
He had also used W. Penn very roughly, when, being necessitated to pass by his castle,
he being lord of that country, asked him and his friends from where they came,
and where they went?
to which they answered, that they were Englishmen come from Holland,
and going no further in those parts than his town Mulheim:
but they not pulling off their hats, the count called them Quakers, and said,
'`We have no need of Quakers here.
Get you out of my dominions, you shall not go to my town.`'
And he commanded some of his soldiers, to see them out of his territory.
Thus W. Penn, and those with him, were necessitated to lie that night in the open air.
But the next day he wrote a letter to the said count, and therein told him,
'`For your saying, we need no Quakers here, I say, under favor, you do;
for a true Quaker is one that trembles at the word of the Lord,
that works out his salvation with fear and trembling.`'

W+++.+++ Penn being come to Mulheim,
could now no more find opportunity to speak with the countess
than the first time he was in those parts;
and therefore he went to Duisburgh, Wesel, and Cleves,
where having had conferences with some religious people,
he returned by way of Utrecht to Amsterdam, where G. Fox was also come back again.

Here W. Penn and G. Fox had a conference and dispute with Dr. Galenus Abraham,
an eminent Baptist teacher, and some of that persuasion.
Galenus asserted, that nobody now-a-days could be accepted as a messenger of God,
unless he confirmed his doctrine by miracles.
W+++.+++ Penn lacked no arguments to contradict this,
since the Christian religion had been once already confirmed by miracles,
and that therefore this now was needless among Christians.
G+++.+++ Fox now and then spoke also something to the matter;
but he being somewhat short breathed, went several times away,
which some were ready to impute to a passionate temper;
but I well know that therein they wronged him.
This dispute was indeed a troublesome business;
for the parties on both sides were made to speak by an interpreter,
which generally was performed so imperfectly, that at last the conference was broke off,
without coming to a decision,
although many weighty arguments were objected against the position.
Certainly it cannot be denied that John the Baptist was sent of God to preach repentance;
and yet in sacred writ it is said positively, John did no miracle;
and yet many believed in him.
And although there were some among the prophets that wrought miracles,
yet we do not find in the holy Scriptures that Jonah,
who was indeed a notable preacher of repentance, did any miracle,
and nevertheless the Ninevites believed him, and deprecated those judgments he denounced,
unless they repented.
Of several other true prophets we find not the least mention of any miracles they did;
but on the contrary, the Scriptures signify, that possibly false prophets might arise,
and give signs or wonders; and that the doing of miracles could not always be a proof,
or sure evidence, that any one was sent of God,
appears plainly from what our Savior himself said,
that among those to whom he should one day say,
"`Depart from me,`" would be such that should say,
"`Have we not in your name cast out devils, and in your name done many wonderful works?`'
And what shall we think of the sorcerers of Egypt;
did not they seem to do the same wonders as Moses and Aaron did?
And yet those wonders wherewithal they deceived Pharaoh and his men,
were in no ways wrought by a divine power.
Now, since it appears plainly from the holy Scriptures, and Christ himself said,
'`There shall arise false prophets,
and shall show great signs and wonders,`" we might
with good reason suspect the doctrine of one,
who now-a-days wrought miracles, on purpose to make what he denounced, pass for truth.

This being duly considered, it seems to be very absurd,
to require miracles again for confirmation of the
same gospel which once has been confirmed by miracles;
and to desire that the truth of what once has been declared by the apostles,
and strengthened by wonderful works, should be sealed anew with outward wonders.
But it would indeed have been another case, if a new gospel was preached,
and that any pretended to give forth new holy Scriptures;
for then it might be said with some reason,
that it was necessary that this new gospel should be made credible,
and confirmed by visible miracles.
But where no other gospel is preached,
than what has been once delivered to the Christians
by the first promulgators of the Christian religion,
and where this is not done among heathens, but among Christians,
or at least such as bear the name,
there it cannot injustice be required to confirm this doctrine once more with miracles,
the rather because, as has been showed already,
the doing of miracles may not always pass for an irrefragable
proof of one`'s being really pious and godly.
To this may be added, that the miracles which Christ and his apostles wrought,
to give credit to the appearing of the Son of God in the flesh,
may be considered as types and figures of those spiritual
wonders which should be wrought in the souls of people,
when Christ was to be seen the second time, and to appear by his spirit,
to the salvation of those who wait for him; for the eyes of the mind being blinded,
must be opened and enlightened by him; and many that are dead in sin and trespasses,
shall by him be raised, and made alive.
This I think may suffice to show,
that the position of Dr. Galenus could not stand the test; but whatever was objected,
he continued to maintain his opinion.

Not long after this dispute, G. Fox and W. Penn returned to England, where,
having sustained a violent tempest at sea, they arrived safely at Harwich:
passing from there to London,
W+++.+++ Penn there received the following letter from the princess Elizabeth,
in answer to his:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Herford, Oct.
29, 1677.

[.salutation]
Dear Friend,

Your tender care of my eternal well-being does oblige me much,
and I will weigh every article of your counsel to follow it as much as lies in me,
but God`'s grace must be assistant, as you say yourself;
he accepts nothing that does not come from him.
If I had made me bare of all worldly goods, and left undone what he requires most,
I mean to do all in and by his Son,
I shall be in no better condition than at this present.
Let me feel him first governing in my heart, then do what he requires of me;
but I am not able to teach others,
being not taught of God myself Remember my love to G. Fox B. F. G. K. and dear Gertrude.^
footnote:[This was Gertrude Dericks, who had visited the princess,
and afterwards came to live in England, and was married to Stephen Crisp.]
If you write no worse than your postscript, I can make a shift to read it.
Do not think I go from what I spoke to you the last evening;
I only stay to do it in a way that is answerable before God and man:
I can say no more now, but recommend to your prayers,

[.signed-section-closing]
Your true friend,

[.signed-section-signature]
Elizabeth.

[.postscript]
====

P+++.+++ S. I almost forget to tell you, that my sister writes me word,
she had been glad you had taken your journey by Osenburgh, to return to Amsterdam.
There is also a Drossard of Limbourg near this place,
(to whom I gave an exampler of R. B.`'s apology,)
very desirous to speak with some of his friends.

====

--

Yet another letter W. Penn received from the said princess,
in answer to one he wrote from the Briel, at his passage towards England,
which was as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
To the princess Elizabeth, Salvation in the Cross, Amen.

[.salutation]
Dear and truly respected friend,

My soul most earnestly desires your temporal and eternal felicity,
which stands in your doing the will of God now on earth, as it is done in heaven.
O dear princess, do it!
Say the word once in truth and righteousness, "`Not my will, but yours be done, O God!`"
Your days are few, and then you must go to judgment.^
footnote:[She died about four years after.]
Then an account of your talent God will require from you.
What improvement have you made?
Let it prove and show its own excellency, that it is of God,
and that it leads all that love it, to God.
O that you may be able to give an account with joy!

I could not leave this country, and not testify the sentiments I bear in my mind,
of that humble and tender entertainment you gave us at your court:
the Lord Jesus reward you: and surely he has a blessing in store for you.
Go on, be steadfast, overcome, and you shall inherit.
Do not despond; one that is mighty is near you;
a present help in the needful time of trouble.
O let the desire of your soul be to his name, and to the remembrance of him.
O wait upon the Lord, and you shall renew your strength!
The youth shall faint, and the young men shall fail,
but they that trust in the Lord shall never be confounded.

I wish you all true and solid felicity, with my whole soul.
The Lord God of heaven and earth have you in his keeping, that you may not lose,
but keep in that divine sense, which by his eternal word, he has begotten in you.
Receive, dear princess, my sincere and Christian salutation: grace, mercy, and peace,
be multiplied among you all that love the Lord Jesus.

Your business I shall follow with all the diligence and discretion I can,
and by the first give you an account,
after it shall please the Lord to bring me safe to London.
All my brethren are well, and present you with their dear love;
and the rest with you that love Jesus, the light of the world, in your family.
You have taught me to forget you are a princess, and therefore I use this freedom;
and to that of God in you am I manifest; and I know my integrity.
Give, if you please, the salutation of my dear love to A. M. de Homes, with the enclosed.
Dear princess, do not hinder, but help her.
That may be required of her, which,
(considering your circumstances.) may not yet be required of you.
Let her stand free, and her freedom will make the passage easier unto you.
Accept what I say, I entreat you, in that pure and heavenly love and respect,
in which I write so plainly to you.
Farewell, my dear friend, and the Lord be with you.
I am more than I can say,

[.signed-section-closing]
Your great lover, and Respectful friend,

[.signed-section-signature]
W+++.+++ Penn.

[.postscript]
====

I refer you to the enclosed for passages.
We visited Gichtel and Hooftman, and they us:
they were at one or two of the meetings at Amsterdam.
_Vale in sternum._

====

--

[.offset]
To this letter the princess returned the following answer.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
This 17 November, 1677.

[.salutation]
Dear Friend,

I have received a letter from you that seem to have
been written at your passage into England,
which I wish may be prosperous: without date,
but not without virtue to spur me on to do and suffer the will of our God.
I can say in sincerity and truth, Your will be done, O God, because I wish it heartily;
but I cannot speak in righteousness,
until I possess that righteousness which is acceptable unto him.
My house and my heart shall be always open to those that love him.
Gichtel has been well satisfied with the conferences between you.
As for my business, it will go as the Lord pleases, and I remain in him,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Elizabeth.

--

G+++.+++ Fox now being come to London, received there letters from New England,
with an account of the cruel proceedings of the magistrates against his friends there:
for persecution being hot in Old England, it made those in New England the worse;
insomuch that they did not only whip the Quakers that were there,
but also some masters of ships that were no Quakers,
only for bringing some of that persuasion there.
But about that time the Indians made an inroad upon the English,
and slew three-score of their men; and having taken one of their captains,
they flayed off the skin of his head, while he was alive,
and carried it away in triumph.

Now since the people called Quakers were also much persecuted in Scotland,
they drew up an account of their sufferings,
and delivered it to the king in the beginning of this year;
but whether they got any ease thereby, I cannot tell.

In the latter part of this year, G. Fox travelled through many places of England.
In the meanwhile I will again make some mention of the persecution there.
At Plymouth about this time,
those called Quakers were generally kept out of their meetinghouse,
and then performing their worship in the open street, as a duty they owed to God,
and for the omission of which they judged no man could be dispensed with,
they suffered exceedingly, not only in winter, by the sharpness of the weather,
but also in summer;
for it was more than twelve months that they thus kept their meetings in the open street,
being grievously abused by the rabble and the soldiers;
for beating and punching seemed not sufficient;
fiery squibs and burning coals were thrown among them,
and filthy excrement cast down upon them out of a window: besides,
fines were extorted for their having been at the meeting,
on the account of one Richard Samble, who was fined as preacher,
for having been on his knees at prayer,
which fine was laid upon four of them that were at the said meeting.

At Frenchay in Gloucestershire, the justice, John Merideth,
behaved himself exceedingly furious in disturbing the Quaker`'s meetings;
for he himself did not only beat them, but more than once drew his knife to mark them,
as he called it, had he not been restrained by his servants,
who for all that could not prevent his taking some by the hair of the head,
and pulling them away, no, the havoc and spoil which was made, was so extravagant,
that from one Thomas Holbrow, an ancient blind man, they took his bed from under him,
so that he and his wife lay about a quarter of a year on straw;
and when his friends provided him with some clothing against winter,
part of that was also taken from him: for such plundering now went on with a full career;
and the basest men were authorized to deprive others of their goods,
if there was but a justice that favored such.

At Bayton, in Suffolk, Edmund Bally was by warrant from justice Burwel,
despoiled of what he had, both within doors and without,
his goods having been distrained five times; and though he was made to lie on straw,
yet he was not left unmolested, for they came in the night, armed with pistols,
and broke open his door, threatening to destroy him.
It happened there also, that a poor blind widow, on her sick bed,
was visited by some persons; and this was made a conventicle, and they were fined,
and warrants issued out by the aforesaid justice to make distress on their goods.
In many other places things went no better;
but I may not detain my reader with every particular.

This year died in prison William Dobson, of Brightwell in Berkshire,
having been spoiled of his goods from time to time, during the space of thirteen years,
and almost always in prison too, till his hard sufferings ended with his life.

It was also in this year that William III.
prince of Orange, came from Holland into England,
and there entered into matrimony with the princess Mary,
eldest daughter of the duke of York,
which in process of time made way for him to the throne of Great Britain.
He accomplished his marriage there on the 4th of November, being his birthday;
and not long after returned to Holland with his spouse.

About the beginning of the year 1678, G. Fox came to London,
and the parliament sitting at that time,
he and G. Whitehead presented to them an account
of the grievous sufferings of their friends,
by laws made against the Catholics;
and they were not without hopes of obtaining some ease,
because several of the members of that august assembly seemed to favor them;
but the parliament was suddenly prorogued, whereby a stop was put to their endeavors.

G+++.+++ Fox then traveling through many places,
came home to Swarthmore in the latter part of the year;
and since many of his friends at this time were under great persecution, and in prison,
he wrote the following epistle to them:

[.embedded-content-document.epistle]
--

[.salutation]
My dear Friends,

Who are sufferers for the Lord Jesus`' sake, and for the testimony of the truth,
the Lord God Almighty with his power uphold you,
and support you in all your trials and sufferings; and give you patience,
and content in his will,
that you may stand valiant for Christ and his truth upon the earth,
over the persecuting and destroying spirit, which makes to suffer, in Christ,
(who bruises his head,) in whom you have both election and salvation.
And for God`'s elect sake the Lord has done much from the foundation of the world;
as may be seen throughout the Scriptures of Truth; and they that touch them,
touch the apple of God`'s eye, they are so tender to him.
And therefore it is good for all God`'s suffering children to trust in the Lord,
and to wait upon him; for they shall be as mount Zion,
that cannot be removed from Christ, their rock and salvation,
who is the foundation of all the elect of God, of the prophets and the apostles,
and of God`'s people now, and to the end: glory to the Lord and the Lamb over all.
Remember my dear love to all friends; and do not think the time long,
for all time is in the Father`'s hand, his power.
And therefore keep the word of patience, and exercise that gift;
and the Lord strengthen you in your sufferings, in his holy Spirit of faith.
Amen.

[.signed-section-signature]
George Fox.

[.signed-section-context-close]
Swarthmore, the 5th of the 12th month, 1678.

--

Persecution was now very hot in many places.
At Bawnasse, in Westmoreland,
it happened that those of the society called Quakers being religiously met together,
were much abused by the rude people; and besides other insolence that were committed,
a dog being thrown among them, one John Thompson said to this wicked crew,
that they ought to behave themselves civil and moderate;
and for saying so he was informed against as a preacher,
and on that account fined twenty pounds.
Mary Tod, a poor ancient widow in Yorkshire, having had a meeting at her house,
was also fined twenty pounds by justice Francis Driffield;
and when the informers told him that her goods were not worth so much,
he ordered them to take all that they could find: this they did,
and did not leave her a bed to lie on; no, took away all her clothes.

This year the ambassadors of the king of France, and those of the United Netherlands,
with those of several other potentates, were met at Nimeguen,
to treat about a general peace;
and therefore Robert Barclay wrote an epistle to them in Latin,
to exhort them to this good work: the epistle,
together with his Apology for the true Christian Divinity, in Latin,
was delivered to each of the said ambassadors, a book for every one of them,
and one for their principals.
George Fox also wrote an exhortatory epistle to them,
which being translated and printed in Latin, was also sent to them.
And before this year came to an end, the peace was concluded.

In the meanwhile persecution went on in England,
and those that were envious did not lack a specious pretense to gild their malice;
for about this time a plot of the Catholics being discovered,
there seemed a necessity to watch against seditious assemblies; insomuch,
that those who had no mind to persecute, were in a manner constrained to it;
of which an instance was seen in the year 1679, at Castle Dumington in Leicestershire:
for John Evat having been fined for a meeting at his house,
and goods enough to answer not being found, the constable,
and three other officers were fined each five pounds,
because they had been backward to take away the said Evat`'s goods.
But the ecclesiastics showed themselves more covetous,
to get what they pretended to be their due; and one Michael Reynolds,
at Farringdon in Berkshire, was this year despoiled of cattle, barley, and beans,
for tithes, to the value of more than ninety-seven pounds,
and all this only for one year.

Thus honest men were oppressed, which gave occasion to a certain writer of that time,
(who in print gave many instances of this nature,) to say,
'`Truly the Catholics may laugh because of their victory, now they have got a law,
whereby one Protestant fights against another.`'
This was chiefly leveled against conventicles;
for thereby many families were impoverished,
because often they were robbed of thrice as much as the fine amounted to;
and the basest means that could be thought of were used
to enrich the persecutors with the spoil of the innocent:
for it happened that four of those called Quakers traveling on the way,
this was deemed a transgression,
by adding a fifth to their number who was not of their society.
And thus the informers, (some of whom were often whores,
or wives of informers,) made a meeting of it, and this passed;
so great was the power of these profligates;
and on this account the goods of the said four persons were distrained.
More abominable actions of that kind I could mention,
if I did not think it might seem tedious.
Such despoiling was permitted now to any naughty fellow, and this made them so insolent,
that one John Hill, constable at Walsingham in Norfolk,
when he was showed the injustice of the warrant he had, said '`Justice or no,
I will take it for all that.`'

At Norwich lived one William Wat,
who for several years had carried on the trade of informing,
but whatever he got by it turned to no account;
and often he was seized with such fits of weakness, that he could not stand on his legs;
but this year, in October, the hand of God fell so heavy upon him,
that it put a period to his life.
He had supped at night, and was as well, according to his wife`'s relation, as ever;
but on a sudden he sunk down to the ground, and his daughter crying aloud,
he seemed to look at her, and so died without more ado:
but what was looked upon as a very strange thing, his corpse stunk so grievously,
that none were willing to carry it,
and the overseers of the poor were necessitated to
hire four men to bear it to the grave.

Far otherwise was the exit of Issac Penington,
an eminent minister and author among those called Quakers, and a man of an acute wit,
and great endowments, who in the year 1658, on Whitsunday, so called,
being in a meeting at the house of John Crook in Bedfordshire,
was so reached by the preaching of G. Fox, that he, who before that time,
had contradicted the Quakers with his natural wisdom,
now embraced their doctrine as truth,
and did not hesitate to make public profession of it,
for which he afterwards several times suffered imprisonments
during the space many of years;
but he continued steadfast to the end without fainting, and died piously in October,
at his house near Goodnestone in Kent,
from which his corpse was carried to Buckinghamshire, where he formerly lived,
and was honorably interred there.

Some time before, G. Fox had written some queries to the Pope and the Catholics,
which being translated into Dutch, and printed,
I was desired by him to translate into Latin, and to send them to Rome to the Pope.
This I did at his desire, but never received or heard of any answer to them.

These queries in Latin, with what the author W. S. wrote to the Pope on that occasion,
are to be seen in the Appendix to the [.book-title]#Dutch History,# which being translated into English,
the reader may take as follows.

[.embedded-content-document.address]
--

[.letter-heading]
To Innocent XII.
Pope of Rome, S.

[.salutation]
Great Prelate,

Thou will perhaps at first sight admire that the writing enclosed should be sent to you;
but know it was done at the command of the author; and not undeservedly;
for if you rightly weigh and consider the matter, you must with us acknowledge,
that it would be very unworthily done to keep this little treatise from your view,
which has been already printed in the Dutch language,
and carries the Pope`'s name in the frontispiece.
Nor will you be able to deny, that you are not only not injured hereby,
but that we have also performed a duty that we owed you,
in transmitting these questions which properly belong to you.
But if you please to read them and return an answer, you will both oblige the author,
and also remove the suspicion of error from your religion,
in the sight of all Christendom, provided you can give a clear answer to the objections,
not only in word, but in deed also,

I write this at the request of certain of my friends called Quakers.

[.signed-section-signature]
W+++.+++ Sewel

[.signed-section-context-close]
Amsterdam, the 23rd day of the month called April, 1679.

--

[.embedded-content-document.address]
--

[.letter-heading]
Some questions presented to the Catholics,
and the Pope of Rome, as the supreme head of their church,
and commended to their consideration by George Fox.

[.salutation]
Friends,

[.numbered-group]
====

[.numbered]
1+++.+++ How comes it to pass,
that the Pope and cardinals grant not to the Protestants living in Spain, Italy,
and at Rome, that liberty of meeting together for the right performing of divine worship,
which you yourselves enjoy in England, Holland, and other places,
where the Protestants have the chief power?

Would not the Pope and his ministers persecute, deliver to the inquisition and burn them,
if they should at any time set up as many meetings in Spain, Italy, and at Rome,
as you yourselves enjoy in many places in Protestant countries?

Is the royal law of God thus fulfilled, which teaches,
to do to all men whatsoever we would have done to ourselves? Matt. 7:12.
Would you have those things done to you by Protestants,
which you have done to them?
But if not, where then are the royal law and gospel among you?
God forbid, that we should deny liberty to any one that acknowledges God,
and believes in his Son, the Lord Jesus Christ.
It seems therefore very strange to us,
that the Pope and Catholics do deny the same liberty in the pre-mentioned places,
which they themselves enjoy among the protestants;
because it is not only contrary to reason, but always to law and gospel;
for the apostle affirms,
"`That he that was born after the flesh persecuted him that was born after the Spirit.`" Gal. 4:29.
Have not the Catholics therefore openly
showed in themselves the fleshly birth,
which is contrary to reason, law, and gospel.

[.numbered]
2+++.+++ Where did Christ or his apostles ever command men to bow themselves to images,
and to worship them, and keep holy days?
Where did they command holy days to be appointed in remembrance of themselves,
and the same to be honored?
Why do you not tell us where in the gospels, epistles, or in the revelation,
any such thing was commanded those churches,
which were in the time of the apostles and primitive Christians?

Where, I say, did Christ or his apostles give command to whip, hang, or burn men; or,
to speak as gently as may be, at least to imprison any because they dissented from them,
and could not adhere to their religion?

[.numbered]
3+++.+++ Where ever did Christ or his apostles in the primitive
churches command that candles should be lighted at noon-day?
Well, show us where it is written, whether it be in the gospels, or epistles.
Is not therefore the Roman church degenerated from the church of the primitive times?
Is she not fallen from spiritual weapons to carnal;
has she not revolted from that purity and virginity,
wherein she witnessed in time past Christ to be the head of the churches?

[.numbered]
4+++.+++ Did the churches of ancient time make choice of a private man,
and account him for head of the universal church?
Where ever did the primitive church command infants to be sprinkled with water?
Did not Christ say, "`Teach all nations, baptizing them,`' etc. Matt. 28:19.
Ought they not therefore to be taught before they were baptized?
Are you not degenerated from that faith which Christ is the author and finisher of,
and which purifies the heart, and gives victory over sin, and evil,
which separate from God, and by which we have access to God,
and wherewith he is well pleased?
Are you not degenerated from the light, truth, grace, power and spirit,
wherein the apostles were?

[.numbered]
5+++.+++ Have you not degenerated from the ancient church,
because you allow not the people to read the holy Scripture in their mother-tongue?
For does not the apostles say, "`And when this epistle is read among you,
cause that it be also read in the church of the Laodiceans,`" Col. 4:16,
and elsewhere, "`I charge you by the Lord,
that this epistle be read unto all the holy brethren,`" 1 Thess. 5:27. Yes,
did not Christ also say, "`O fools, and slow of heart,
to believe all that the prophets have spoken.`" Luke 24:25.

How can it possibly be, that your common people should believe those things which Christ,
the prophets, and apostles have spoken,
unless it be granted them to read or recite the same in their own tongue,
to the end they might-both hear and understand them by the Spirit which gave them forth?
Why then do you take away the use of the holy Scriptures from the common people?
Are you afraid lest the truth should appear manifest,
whereby they might see and believe what is written in the law and prophets,
and by Christ and his apostles?
Had not the Jews the law and the prophets in their mother-tongue,
that their children might read them?
Ought not therefore all Christians likewise to have the New Testament,
that makes mention of Christ and his apostles, in their mother-tongue?
But if not, why do you not show us where Christ or his apostles have forbidden it?

[.numbered]
6+++.+++ But what do you say of the sacrament of the altar, as it is called?
Why have you slain many, and burnt others alive in England, France, the Low Countries,
and other places, because they could not approve or receive it?
You assert it as a thing certain, that the bread and wine,
as soon as you have consecrated there, are made Christ, yes, whole Christ,
consisting of soul, spirit, flesh, blood, and bones.
Besides you boldly affirm, that all who receive that sacrament do receive whole Christ,
and that after your consecration, that very thing becomes immortal and divine.

Wherefore come, O pope, cardinals and priests,
let us take a bottle of wine and a loaf of bread,
and equally divide the wine into two basins, and cut the bread into two parts:
then let the Pope, cardinals, or priests consecrate one part, which they please;
which being done, let us lay up the consecrated and the unconsecrated together,
in some close place, and secure the same with seven locks and keys on your part,
and with as many on ours, both Catholics and protestants keeping watch over it.
But if it plainly appear, that the consecrated bread and wine are immortal and divine,
and lose nothing of their virtue and savour, nor grow moldy or sour,
as though they had been unconsecrated, then we will come over to you:
but if they lose their property, quality, and savour,
and both parts of the bread do alike grow moldy,
then it will be reasonable for you to come over to us,
and confess that your sacrament of the altar, so called, is neither Christ nor his flesh,
nor anything immortal or divine; for his flesh saw no corruption.
Acts 2:27. 31.--13. 35. 37, and his precious blood, which delivers from sin and corruption,
cannot be corruptible.

Let trial then be made hereof; but let judgment be left to just and equal arbitrators,
both Catholics and protestants,
and that in a place where the protestants may have the same power that you have:
for it would be unjust to make this trial or experiment,
where you have the whole administration of the commonwealth,
and an equal liberty is denied the protestants.
This thing will make the truth manifest, and turn to the honor of God:
for you have shed much blood upon this occasion.

Wherefore permit your Christ, whom you have made, to be tried,
that it may be seen whether he be the true Christ, or antichrist;
whether he be the true God, or a false one?
For it would be somewhat hard that Baal`'s prophets should outdo you,
for they were willing to have their god tried,
though they had before slain many of the people of God,
because they would not worship their god; as you also have often done.

Come you forth therefore publicly, and make trial;
that it may appear at length to all Christendom,
whether yours be the divine and immortal Christ and God, or no?
Or is not rather that mortal and corruptible Christ, which you yourselves have made,
and for whose sake you have slain multitudes of the people of God,
because they could not believe or comply with you?

[.numbered]
7+++.+++ Further, where did Christ or his apostles ever speak to the saints of purgatory,
wherein men should be purged from their sins after death.
Show us where it is written in the New Testament.
Is it not therefore a plain denying that Christ`'s blood purges from all sin,
to tell the people a fable of a certain purgatory to purge them from sins after death?
Is it not likewise a denying of Christ`'s baptism with the holy Spirit,
and of spiritual circumcision, and faith in Christ, which purges in this life,
and gives the victory?

====

Did not Christ answer some that desired fire might come down from
heaven and consume those that would not receive him;
"`You know not what manner of spirit you are of?`"
Did not he rebuke them,
saying "`That he came not to destroy men`'s lives but to save them?`" Luke 9:54-56.

You therefore who have destroyed such a vast number of men and
women for their dissenting from you about rites and ceremonies,
and taken away their lives by such kind of instruments, racks and fires,
as were never sent down from heaven, but devised and invented by yourselves;
are you not worse than they,
who desired fire to be called from heaven to destroy men`'s lives?
And seeing Christ told them, that they knew not what manner of spirit they were of,
do you know what manner of spirit you are of,
who have devised so many ways and torments for the killing of men,
and have actually made use of them?

With what front can you persuade us to commit our souls, bodies, and lives, to you,
who know not of what spirit you are children, neither have the mind of Christ who said,
"`He came not to destroy men`'s lives, but to save them?`"

Are you not all therefore, as many as take away men`'s lives for worship devised by you,
obnoxious to the rebuke of Christ?
For when did Christ or any of his apostles ever give command, or by their example teach,
that any one that was disobedient to them, or rejected their doctrine and religion,
should be persecuted and imprisoned, or punished by any carnal weapons?
Tell us where any tiling of this kind is contained,
either in the four evangelical histories,
or in the epistles written to the Christian Churches?

Did ever Christ or his apostles go to the rope-makers to buy whips and halters,
to whip and hang men for dissenting from them as you have done?
Did they ever go to the blacksmiths to make chains, fetters, bolts and locks?
Or to the gunsmiths to buy guns and muskets;
or to the sword-cutlers to buy swords and halberts?
Did they ever build prisons, or get holes and vaults dug,
to force men by such means to their religion?
Show us an example and precept given by Christ or his apostles,
which commands and makes the use of such weapons and instruments lawful.

But if you cannot make proof thereof, it is necessary for you to confess and acknowledge,
that you are fallen and degenerated from the true Christian weapons,
which the apostles and primitive Christians used, saying,
"`The weapons of our warfare are not carnal, but mighty through God,`" that is,
spiritual, 2 Cor. 10:4.

[.signed-section-signature]
G+++.+++ Fox

--

[.embedded-content-document.treatise]
--

[.letter-heading]
To Innocent XI. Pope of Rome, S.

Behold, great prelate, a few questions written for the sake of you, and your adherents,
a copy whereof we sent you by the post, about three months ago;
but being uncertain whether it was delivered into your hands or no,
we thought good to write the questions over again, and send them to you,
that it might not belong to us, that you do not read them.
For we think it convenient,
that you should earnestly concern yourself to inspect what was printed in Dutch,
and inscribed to the Pope and his adherents, which if you shall please to do,
and also vouchsafe your pains in answering them both by fact and writing,
it will satisfy the author`'s desire,
and remove a doubt or scruple out of many persons`' minds.
Farewell.

This I have written in the name of some of my friends called Quakers.

[.signed-section-signature]
William Sewel.

[.signed-section-context-close]
Amsterdam, the 24th of the month called July, 1679.

--

This year there was a great commotion in England about a plot carried
on by the Catholics against the life of the king,
who made his brother, the duke of York, go beyond sea for some time;
for the parliament suspecting him,
a motion was made in the house of commons to exclude
him from the succession to the crown;
but this project was quashed.

In the beginning of the year 1680,
it happened that George Whitehead and Thomas Burr coming to Norwich,
and preaching there in the meeting of their friends, were taken prisoners,
as it was said, under a frivolous pretense, as if G. Whitehead-might have been a Jesuit:
and being brought before justice Francis Bacon, who then was recorder of the city,
he after some odd examination, demanded of them, as preachers,
the fine of twenty pounds a man; which they refusing, he asked them,
whether they would take the oath of allegiance; and they answering,
that they could take no oath for conscience-sake, he said,
if they would neither pay the fines, nor take the oath, he would commit them to jail.
They having showed that they were no vagrants, but men of competent estates,
that had settled habitations, as was well known, Bacon said, _De non apparentibus,
et non existentibus eadem est ratio:_ i.e. Of things not appearing,
and things not in being, there is the same reason: just as if he had said,
your estates that are at London, where G. Whitehead lived, and Ware, where T. Burr dwelt,
appear not at Norwich, and therefore they are not in being.
Now though they showed the absurdity of this strange kind of logic,
yet Bacon would not hearken to it, but called them seducers, and seditious,
and told them, there was a statute yet in force, that was made in queen Elizabeth`'s days,
to hang such persons as they were.
And they asking him, if he could prosecute them upon that law, or execute it upon them,
he answered, '`Yes, if the king should give order to have it put in execution,
I would do it, and have you hanged, if you would not quit the realm.`'
From this it may appear what a violent man this recorder was,
and that the prisoners could not expect any good treatment from him.
So night being come, he sent them to the jail.

About a month after, at the quarter-sessions,
they were called into the court of judicature to be tried; and being brought to the bar,
George Whitehead said, '`We have been five weeks in prison;
it is fitting the court should know for what; pray let our court order be produced.`'
But the recorder who sat as judge in the court, said,
'`There is no need of your court order to be read here:
I will give an account of the cause.`'
And then he told the court,
'`how they had gathered together a company of about two hundred,
and that officers went from him to dissipate them, but could not;
that thereupon he sent the sheriff, who took them away;
and that they being brought before him, he offered them, if they would pay their fines,
he would not commit them; and that they refusing,
he tendered the oath of allegiance to them; which they not being willing to take,
he sent them to jail.`'

And though G. Whitehead with good reason said,
that they being Englishmen had a right to travel in any part of the nation:
and T. Burr added, that he being a person that was concerned in trading in corn,
by the law of England he might travel from place to place about his concerns;
yet this so displeased the recorder, that he said,
'`Had not you better have been turning your malt at home, than to come here to preach?
The Scripture says, God added to the church such as should be saved;
but you draw from the church: and,`' said he further,
'`the church of England will never be at quiet till some of you be hanged.`'
G+++.+++ Whitehead then showing how unreasonably the recorder behaved himself,
and that a judge ought not thus to inveigh against the prisoners, and threaten them,
alleged to that end a notable instance, how, in the case of Humphrey Stafford,
an arch traitor, the chief justice Hussey had been unwilling,
(in compliance with the king`'s desire,) to declare his opinion
concerning him before he was judicially proceeded against.
The recorder then asked, what king`'s reign was that in?
'`In king Henry VII.`'s`' replied George Whitehead.
'`I perceive you are read,`' returned the recorder.
And so he was indeed; and he defended his cause so well in the court,
that the magistrates seemed at a loss;
for he showed so evidently that he was unjustly committed to prison, that the mayor,
(to whom, and to the justices he had appealed,) said, '`You have appealed to me;
truly we are tradesmen, and no lawyers: we leave matters of law to the recorder;
he knows the law, and we must acquiesce in his judgment.`'
If I should repeat here all that was spoken pro and contra, so as I find it extant,
I should be made to be almost as large as I have been in
the relation of the trials of John Crook and William Penn:
and therefore I will only say briefly, that, after much reasoning,
the recorder tendered the oath of allegiance again to them,
that so by their refusal he might get occasion to premunire them.
But this recorder, before the whole process came to an end,
being turned out by the magistrates, it did not come to that pitch;
though it was a good while yet before the aforesaid
George Whitehead and Thomas Burr were released,
after they had shown the illegality of their imprisonment; first,
by more than one warrant from the recorder, and afterward, to color the error the better,
by an order from the quarter-sessions.

This year those called Quakers, at London,
published a brief relation of the sufferings of their friends,
since the king`'s restoration, and presented it to the king and parliament,
showing therein, how many had been fined by the bishops`' courts, robbed of all they had,
put into prisons, and there died;
the number of which was computed to be two hundred and forty-three persons,
many whereof had been so grievously beaten and wounded
because of their frequenting religious assemblies,
that they died of their hurts and wounds.
There came forth also a printed account of the unjust proceedings of the informers,
and how at their instance, without a juridicial process,
the accused were bereaved of their goods,
the unlawfulness of which was plainly shown from the books of eminent lawyers.

G+++.+++ Fox now travelled through many places,
and came to London about the time of the annual meeting;
and traveling afterwards again into the country, he returned into the said city,
and stayed there the most part of the winter.

The parliament was then very busy with enquiring into the plot carried on by the Catholics;
and the house of commons especially were very active in the case,
so that a bill to exclude the duke of York from the succession to the crown,
passed after a third reading: but this was opposed in the house of lords;
for by a majority, among which were the bishops, who would not consent to the exclusion,
the bill was rejected.
Now since some ill-natured Episcopalians were very
forward to place the Quakers among the plotters,
G+++.+++ Fox gave forth the following declaration:

[.embedded-content-document.address]
--

It is our principle and testimony,
to deny and renounce all plots and plotters against the king, or any of his subjects;
for we have the Spirit of Christ, by which we have the mind of Christ,
who came to save men`'s lives, and not to destroy them:
and we would have the king and all his subjects to be safe.
Wherefore we do declare, that we will endeavor, to our power,
to save and defend him and them, by discovering all plots and plotters,
which shall come to our knowledge, that would destroy the king or his subjects:
this we do sincerely offer unto you.
But as to swearing and fighting, which in tenderness of conscience we cannot do,
you know,
that we have suffered these many years for our conscientious
refusal thereof And now that the Lord has brought you together,
we desire you to relieve us, and free us from those sufferings:
and that you will not put upon us to do those things,
which we have suffered so much and so long already for not doing?
For if you do, you will make our sufferings and bonds stronger, instead of relieving us.

[.signed-section-signature]
George Fox.

--

Not long after he also wrote a paper to all rulers and magistrates in England, Scotland,
and Ireland, to dissuade them from persecution for religion.
His labor seemed not altogether ineffectual with the parliament,
for about the beginning of the year 1681, the house of commons resolved.

[.embedded-content-document.legal]
--

That it is the opinion of the house,
that persecution of Protestant dissenters upon the penal laws,
is at this time grievous to the subjects; a weakening of the Protestant interest,
an encouragement to popery, and dangerous to the peace of this kingdom.

--

But though the house of commons came to this resolution, yet it did not stop persecution;
for as long as the laws, (by virtue whereof they persecuted,) were not repealed,
which could not be done without the concurrence of the house of lords and the king,
those that were malicious continued in their old way,
which lasted yet three or four years.

George Fox now also came into some trouble; since he and his wife were sued for tithes,
though she had lived three and forty years at Swarthmore,
and in all that time no tithe had been paid nor demanded.
Of this George Fox had certificates;
but since they would not accept them without an oath,
it made his case the more difficult.
He proposed the matter to four judges at London,
and found one more moderate than the others;
which put a stop to what her enemies designed.
And the judges wondered when they heard he had made a promise in writing,
not to meddle with his wife`'s estate.

This year the king dissolved the parliament, and called a new one, to sit at Oxford,
and so it did; but for all that he could not make it comply with his demands,
and so he dissolved this also.
Some time after he desired the prince of Orange to come over,
who thereupon came from Holland into England, and after a short stay,
returned to the Hague.

It was also in this year that the king gave a country
or great tract of land in America to William Penn,
with a patent under the great seal, to him and his _in perpetuum,_
since the king owed him still a considerable sum for the
services of his father the admiral sir William Penn.
This tract of land on the river Delaware,
from the fortieth degree to the three and fortieth, with all the isles belonging to it,
the king gave to W. Penn, with full power to erect a new colony there, to sell lands,
to create magistrates, to make laws, not contrary to the laws of England,
and power to pardon crimes: and in the patent,
the king declared that this tract of land henceforth should bear the name of Pennsylvania.
This favor of the king, William Penn chiefly owed, I think, to James, then duke of York,
who being chief admiral of England, sir William Penn, the father, on his dying bed,
desired him to protect his son against his enemies, who, because of his religion,
were like to fall hard upon him.
This the duke promised, and performed;
and it was not without reason that William Penn afterwards,
when the said duke had ascended the throne,
showed himself ready to be serviceable to him in
all that he thought might be beneficial to the kingdom.
William Penn now went with much company to America.
And having seen the land given him, he founded there the chief city Philadelphia,
and some other towns.
And that he might the more peaceably enjoy the country,
he purchased from the Indians so much land that he became
proprietor of a country twice as big as all the United Provinces,
as he himself once told me: and this colony increased so suddenly,
that after a few years, at Philadelphia, there were built six hundred brick houses.

William Penn`'s father was deceased long before,
and on his dying bed he declared that he had a gracious God,
and he gave marks of a true Christian disposition of mind:
he also gave his son several wholesome admonitions how to behave himself in this world.
He complained much of the wickedness of the times, and was heard at sundry times to say,
'`Woe to you, O England!
God will judge you, O England!
Great plagues are at your door, O England!`' He also said, '`God has forsaken us.
We are infatuated; we will shut our eyes.
We will not see our true interest and happiness: we shall be destroyed.`'
When he was near death, and took his leave of his relations, he said to William Penn,
'`Son William, if you and your friends keep to your plain way of preaching,
and keep to your plain way of living,
you will make an end of the priests to the end of the world.
Bury me by my mother, live all in love, shun all manner of evil;
and I pray God to bless you all; and he will bless you.`'
Thus died the valiant admiral Penn, father of William Penn, proprietor of Pennsylvania:
and now I return to other matters.

I left George Fox at London, and since he continued there and thereabout a good while,
I will take a turn to Bristol, where in the year 1682,
a dismal scene of persecution was opened:
for the meetings of those called Quakers were disturbed,
not only by grievously abusing and imprisoning them;
but they were also vexed by breaking into their houses,
and committing all manner of violence, as among the rest in the house of Richard Marsh,
an eminent merchant in that city: for, to get of him the fine that was pretended,
first a cask of wine, worth twenty pounds, was taken, and sold for four pounds;
as often it happened, that the goods thus taken, were sold for less than the half,
because honest people being unwilling to buy such goods,
they were sold to any one that would but bid some money, how little soever:
for what was lacking of the fine was taken anew from the fined person,
and so they did here also; for they broke open his counting-house, sought for money,
and took away his ledger, journal, cash-book, and other books and accounts,
besides many household goods; and several chambers were rifled, though the wife,
of the said Marsh lay in child-bed at that time.
The chief actors of these insolence were the sheriff John Knight,
and John Helliar an attorney, who, with his companions Lugge, Tilley, Casse, Patrick,
Hoare, and Watkins, served for informers.
Knight and Helliar came frequently with a multitude of boys
and rude rabble to disturb the meetings of the Quakers;
and then they carried them to the prisons, which grew so full,
that about fifty persons were crowded into one room, which was so nasty,
that one of the aldermen, sir Robert Cann, said,
if he had a dog which he loved he would not put him there.
And though sir Thomas Earl, mayor of the city, and some justices and aldermen,
at the request of others,
showed themselves inclined to allow the prisoners a better place,
yet the power of the aforesaid sheriff John Knight, was such, that he hindered it.

The meetings of other Protestant dissenters were now also disturbed,
but they fainted and gave way; whereas the Quakers stood firm, how much soever vexed;
which often was done in a very outrageous manner:
for their meetings were not only disturbed often with the noise of drums and fiddles,
but liberty was given to the vilest fellows to commit all kind of insolence
without showing any regard to those of the female sex,
whose hoods and scarfs were torn; and Helliar,
to give the boys a sign to attack the women, was used to say to these,
'`have a care of your hoods and scarfs;`' for then the boys fell upon them,
and both aged women and ancient men were carried to prison,
and forced to go faster than they well could, by pushing them,
and pinching their arms black and blue;
and when once a girl spoke a word against this cruelty, she was pulled by the hair,
and hauled to prison; no, little boys were beaten on the head till they grew giddy,
and then they were carried to Bridewell,
where Helliar charged the keeper to get a new cat of nine tails,
endeavoring to terrify the children, by making them believe they should be whipped,
unless they would promise to come no more to meetings: but this succeeded not;
for his extravagant malice did not subdue the constancy of these children.

With such diabolical rage they persecuted this people at Bristol,
and not a stone was left unturned to afflict them.
Once they were nailed up in their meetinghouse, and thus kept about six hours;
which could not but be very hard to nature,
since there were also women of no mean families,
and among these the widow of the upper sheriff Lane.
So many also were taken prisoners, that at length there was no more room in the jails.
By these proceedings many families were ruined: for their goods were taken from them,
not only on the account of meeting, but when any were believed to be of good estates,
the oath of allegiance was tendered to them.
At court it seems they were the more offended against the Quakers,
because in the election of members of parliament
some had voted for such as they believed to be moderate,
and no favorers of popery; and therefore it was said underhand,
that if Mr. Penn or Mr. Whitehead would undertake for the
Quakers not to vote at elections of parliament-men,
there should be no further persecution of them.

In the meanwhile the behavior of the persecutors
in the meetings was brutish in the highest degree;
insomuch that a certain woman,
seeing that the attorney Helliar lifted up her child by the hair of his head,
and asking him, why he so abused her child, was therefore ill treated herself by him.
And by order of the said Helliar a lass was committed to Bridewell,
because she gave an impudent boy, that would have turned up her coats, a box on the ear;
for which defending of her modesty,
this brutish Helliar called her a rioter and seditious person: for he was,
as has been said already, a leader of insolent and saucy boys,
which he from time to time took along with him to disturb the meetings of the Quakers.
And sheriff Knight did often with his cane very violently beat those that were met together,
and once grievously abused an ancient man called Britton;
and some women were pinched violently in their arms.
Susannah York, an aged woman, was thrown down to the ground;
Mary Hooper was very roughly handled by Helliar, had her scarf torn off her back,
and was so thrust and flung about, that she was much out of order long after;
and Mary Page, being big with child, was so violently hauled out of the meeting,
that her life was endangered by it.
With Helliar it became customary to call men rogues, and the women whores, jades,
carrions, and damned bitches: he also bid the boys to tear their scarfs and take up dirt,
and throw upon them.
Of this his beastly rage there were many witnesses;
for these abominable dealings displeased many people of other persuasions:
but it seems these enraged fellows had encouragement at court, whereon they dared rely:
for the sheriff John Knight was knighted, and therefore grew more insolent.
Once it happened that Helliar having disturbed a meeting,
drove the women along the streets as if they had been cattle;
and being asked whether he made beasts of them, he answered, '`You are worse than beasts;
for beasts will be driven, but you will not.`'

This disturbing of meetings continued till almost all the
men belonging thereto were clapped up in prison;
and some of them sending a petition to the mayor and justices of the city,
that they might be pleased to let them have larger rooms, since not only their health,
but their lives also were endangered,
the said magistrates showed themselves inclined to
allow the prisoners some ease or enlargement:
but the power of sheriff Knight was such, that whatever they said or did,
all proved in vain.
The mayor also signified to the sheriff,
that he would have all convictions made above board, and not in ale-houses and taverns;
and that he would have the distrained goods brought into a public warehouse,
and not in a by-lane.
But though the mayor _ex officio_ might have commanded the sheriff,
yet this officer was so countenanced, that he did not care for whatever the mayor said;
no, so exorbitant was he, that his adherents began to threaten the mayor,
he should not be a parliament-man; insomuch that he was forced to comply in some degree.
In the meanwhile the havoc and spoil was so enormous,
that generally twice as much was taken as the fine amounted to.
The prisoners, some of whom lay on the floor, others in hammocks,
and some in a cold and open room, exposed to the wind, and injury of the weather,
suffered great inconveniences,
and the jailer Isaac Dennis imagining that nothing could be too bad for them,
would not show them any favor, but at a very unreasonable rate;
and his wife showed herself no less unreasonable than he,
so that one extortion was at the heels of another.
Four physicians of Bristol, namely: John Griffith, William Turgis, J. Chauncy,
and T. Bourn, seeing how straitly the prisoners were penned up and thronged together,
gave a certificate under their hands, in which they declared,
that they resenting their condition with compassion,
and considering what dangerous consequence such close confinement might be of,
were moved to certify, that the prisoners being destitute of room for rest,
it had a ready tendency to breed infectious distempers,
to the endangering of their lives, etc.
But all this did not avail them,
it being not counted worth the while to be concerned for them.
No, so desperately wicked was the jailer,
that when the prisoners complained for lack of room, he said to his man,
if he could but shut the door, it would be well enough.
But in due time we shall see what anguish and horror befell him.

After most of the people called Quakers at Bristol were in prison,
the women who continued to keep up their religious meetings, were also seized,
and confined to that degree, that at length few or none but children,
that stayed with the servants in the houses of their parents, were left free.
The number of the prisoners for the sake of their
religion amounted now to one hundred and fifteen,
and some of them were confined in Bridewell, among whom were also Barbara Blaugdon,
(several times mentioned before,) and Catharine Evans,
who had learned at Malta what it was to suffer a tedious and hard imprisonment.
It is very remarkable that children under sixteen years
of age now performed what their parents were hindered from:
for these children kept up their religious meetings as much as was in their power.
But though they were not within the reach of the law,
yet once nineteen of these youths were taken and carried to the house of correction,
where they were kept for some time.
And though they were threatened with whipping if ever they returned to the meeting,
yet they continued valiant without fainting,
although they suffered exceedingly from the wicked rabble.
But so great was their zeal, that they despising all reproach and insolence,
remained steadfast; and thus showed in spite of their enemies,
that God would not permit that the Quakers`' meeting should be altogether suppressed,
as it was intended.
This persecution continued till the next year, as it did in several other places also;
for there lacked no-informers, who continually lay in wait for prey,
even to such a degree, that I find that some of those called Quakers,
being come from other places to market, and being gone into an inn to refresh themselves,
a snatching informer did not hesitate to declare upon his oath,
that the Quakers had kept a meeting there.

But before I leave Bristol, I must give some account of a ridiculous act,
performed on one Erasmus Dole, who bore the name of a Quaker.
He having said that he scrupled not to declare the contents of the oath of allegiance,
it was contrived that he should speak after the clerk,
and skip over such words he disliked, and pronounce another in its room, as I declare,
instead of I swear.
This went on, and while he was thus speaking, the jailer held his hand to the book,
and when Erasmus had said all, put it to his mouth, to make this pass for kissing it.
With this the court seemed satisfied;
and the bishop of Bristol seeing these apish tricks, told the court,
that altered it not from being an oath, at which they gloried,
as having obtained a conquest.
But this was but a pitiful one; for Erasmus being a man of an irregular life,
the Quakers had but little cause to regret the loss of such a member,
who grew so dissolute,
that in process of time they found themselves necessitated to deny him,
because of his offensive conduct.

In Gloucestershire the people called Quakers were also under great sufferings by imprisonment,
for keeping their meetings; and the wife of one John Boy,
being at a peaceable meeting at Little Badmanton,
was through instigation of the priest of the parish,
in a violent manner dragged out of the meeting by the lord Herbert`'s footmen;
through which abuses the woman fell sick and miscarried, to the endangering of her life;
and her husband, who was also taken prisoner at the same place,
was not allowed at his request to see his wife.

In Leicestershire it went no better: one Elizabeth Hill being in a meeting at Broughton,
was by the rude boys dragged out, and so abused, that she was seemingly quite spent,
and near dead; and laying in the dirt, one of the boys,
to try whether she was still alive, put his finger into her mouth,
and perceiving her to breathe, said, '`Let us at her again.
The devil is yet in her, and we will squeeze him out.`'
These cruel abuses made a neighborly woman cry out,`' What, will you kill the woman?
To which the boys said, '`What care we?
Mr. Cotton bid us do so.`'
'`Did he indeed?`'
asked the woman.
'`Aye, indeed,`' replied the boys.
'`Then,`' said she, '`he may be ashamed of it.`'
Thus these boys openly said, that it was the parson, Thomas Cotton,
who was the priest of the parish, encouraged them to this excessive wickedness;
and his man said in plain terms, his master was one of the best men in England;
for if every one would serve them so, this heresy would be rooted out.
And this man, whose name was Thomas Ambrose, did not hesitate to say,
that nothing would drive the Quakers away, but either fire or water;
and if the house was his,
(meaning the house where they met together,) he would burn it on their heads.
More instances of such exorbitant wickedness which happened at sundry places,
I could mention, if I did not study brevity.

George Fox being this year at London about the time
of choosing new sheriffs for the city,
he wrote a few lines to those who, standing candidates for that office,
desired his friends to give their voices for them.
And he said in the conclusion, '`Shall we be free to serve and worship God,
and keep his commands, if we give our voices for you?
For we are unwilling to give our voices for such as will imprison and persecute us,
and spoil our goods.`'
The constables now at London were sent sometimes
with warrants to disturb the Quakers`' meetings;
but it was easily seen that they would rather have been freed from such a commission:
for coming there, they would bid George Fox or others that preached,
to give over speaking; but they and the soldiers who sometimes came along with them,
generally behaved themselves moderate,
sufficiently showing that they were not for persecution,
and that what they did was for the sake of their office.
Sometimes indeed they hindered the friends going into their meetings;
but these then being thus kept out, the number notwithstanding increased.

Once it happened that George Fox was stopped by the
constables from going into Devonshire-house meeting;
and after having stood awhile in the yard, till he was weary,
one gave him a stool to sit on; after awhile he stood up and preached,
and in his declaration said, '`You need not come against us with swords and staves,
for we are a peaceable people,
and have nothing in our hearts but good-will to the king and magistrates,
and to all people upon the earth.
And we do not meet under pretense of religion, to plot against the government,
or to raise insurrections; but to worship in spirit and in truth.`'
When he had spoken what was upon him at that time, he sat down,
and after a while concluded the meeting with prayer,
at which the constables and soldiers as well as others put off their hats;
and when the meeting was finished, a constable putting off his hat, seriously said,
'`The Lord bless you;`' and all were allowed to pass away unmolested.

Thus this year came to an end.
All other Protestant dissenters were now suppressed;
for they were restrained from exercising any public worship; and some there were, who,
in their nocturnal meetings, would pray God,
that it might please him to keep the Quakers steadfast,
that so they might be as a wall about them,
in order that other dissenters might not be rooted out.
And yet these, to render the Quakers odious,
formerly had been very active in setting them forth in very ill colors.
But the said people continued now so valiant, and without fainting,
that some of their persecutors have been heard to say,
that the Quakers could not be overcome,
and that the devil himself could not extirpate them.

In the year 1683, persecution continued in many places;
and by computation it appeared that above seven hundred
of those called Quakers yet suffered imprisonment in England.
I could mention several instances of persecution in Leicestershire, Northamptonshire,
and elsewhere; but to avoid being prolix, I will only take a turn again to Bristol,
where persecution continued still;
for if sometimes any of the people called Quakers came to a meeting,
they presently were committed to prison; among these was one Richard Lindy, a blind man,
of about fourscore and ten years of age, who was carried to jail,
and forced to sit up three nights in a chair,
though others offered to pay for his lodging,
if some convenient place to lie down on had been allowed him.
Some of the prisoners, being tradesmen, would willingly have worked in prison,
to earn something for their sustenance: but the jailer Isaac Dennis,
would not permit them that liberty.
Other prisoners fell sick of the spotted fever, and some died of it:
yet all this did not soften the said hard-hearted jailer.
But at length a heavy stroke fell from heaven upon him.
About the middle of the month of October he fell sick,
and was seized with terrible anguish of mind.
Then he wished he had never seen the inside of the jail;
and he desired some of the Quakers to pray for him,
and to forgive him for what he had done.
To which they answered, that they forgave him; but he should ask forgiveness of God.
But still his anguish increased; and when the physicians ordered him to be let blood,
he said, no medicine would do him good, his distemper being another thing:
and that no man could do him good, his day being over;
and there was no hope of mercy from God for him.
Some of those called Quakers seeing him in this woful condition, signified,
that they desired, if it was the will of the Lord, he might find a place of repentance.
And it was told him, they hoped his day was not over,
because he had such a full sense of his condition.
To which he answered, '`I thank you for your good hope; but I have no faith to believe.`'
And he further said, '`Faith is the gift of God.`'
Whatever was spoken to him, he continued in saying, that his day was over,
and there was no mercy for him.
Such a gnawing worm is the guilt of conscience;
and in this desperate slate he continued above a month, and died the last of November,
without any visible signs of forgiveness;
but the judgment thereof we must commit to God.

Although the people called Quakers were oppressed by sufferings all over the country,
yet generally they continued valiant;
and as George Fox did not omit from time to time to encourage
them by letters to faithfulness and steadfastness,
so several others of their teachers did not neglect
to exhort them to perseverance both byword and writing:
and what was indeed remarkable, those who travelled to and fro in tho country,
and publicly preached in the meetings of their friends, generally went free;
and the informers were often disappointed of catching a preacher.
I find it left upon record by Charles Marshall, who was none of the least,
that though in the time when persecution was most hot, he travelled through the nation,
yet none laid hands on him, or fined him for his preaching,
which was the more remarkable, because he being a very zealous man,
was used to lift up his voice in a very powerful manner.

William Dewsbury, who was now grown ancient in his imprisonment at Warwick,
had wrote an epistle of consolation to his suffering friends,
which was thought fit to be reprinted, and is as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Brethren and Sisters,

Hear the word of the Lord.
Thus says the Lord, '`Though you now drink the cup of adversity,
and eat the bread of affliction, and are trampled upon,
as though you were not worthy to live upon the earth,
yet notwithstanding all the fury of men,
you are resolved in the strength of my Spirit forever
to be deprived of the sweet enjoyments of wife,
husband, tender children, parents, and outward possessions, liberty, and life,
before you deny the testimony of my name before the sons of men.
Oh! you dear and tender children, who love not your lives unto death this day,
that you may furnish a good testimony for the glory of my name, says the Lord God;
lift up your heads in the light of my covenant, and believe in my name,
for I am near unto you, says the mighty God of safety;
and let not any weight or burden lie upon you: for I will be more than husband to wife,
and more than wife to husband, or parents to children, or children to parents; yes,
I will be a husband to the widow,
and a father to the children who are deprived of their tender parents for my name`'s sake:
I will enlarge your borders in the life of my righteousness:
you that suffer in true innocence, will I refresh with the depth of my mercies, yes,
I will guard you with the angel of my presence,
and all that devise mischief against you shall be
confounded before the glory of my power,
with which I will keep and preserve you in the word of my patience, and safety,
in my presence, says the Lord God.

'`Therefore, you dear children, who drink the deepest in sufferings, think it not hard,
for it is my purpose unto you all that have not an eye to self,
but alone seek my glory in all you do;
I will make you more and more honorable in the glory of my life,
and double my blessings upon you and yours; for I have beheld your integrity,
and my bowels are mightily moved with compassion towards you;
therefore am I risen for your sakes this day, to declare unto you, my suffering people,
that not a hair of your head shall perish,
neither shall you be detained in prisons and desolate holes any
longer than I have determined shall be for your eternal good,
and the glory of my name forever; therefore in my life stand faithful,
in resistance of every evil thought, or whatever would cause you to murmur,
or desire any thing but what you know will advance the glory of my name,
and the exaltation of my truth, over all that rises up against it,
in your being truly subject to the measure of my light and life,
that will not let any seek a preeminence or esteem among men;
neither let self-striving nor self-serving have power in any; but in true humility, love,
and meekness watch one over another; and let the strong take the weak by the hand,
that you may all gently, in love, meekness, and holy fear, dread my name,
and serve one another; that your love may be manifest unto me, says the Lord your God,
and one unto another in the naked simplicity of your spirits;
then will I make my dwelling among you, and with you;
and my dreadful and glorious presence you shall all feel mightily in you,
and among you, moving in the exercise of my Spirit, to the renown of my name,
and the comfort of one another; and I will crown you with heavenly blessings,
and the glory of my powerful life; and you shall praise my name forever,
that I made you my jewels, and counted you worthy to suffer for the testimony of my name.
I will go before you through all the waters and floods of afflictions;
and I will appear with you before all the councils of the sons of men;
and my saving power shall compass you about in your hot and sharp afflictions,
all you who have your confidence alone in me, the Lord your God.
Therefore, trust in my name, you my dear children, and cast all your care upon me;
and if any of you joyfully suffer the spoiling of your goods,
I will supply with what is needful for you and yours;
and if any of you seal your testimony in the word of my patience with your blood,
I will take care of your tender wives and children, or parents,
for whom your souls have been poured forth in prayers unto me for their good.

'`Therefore hear my word,
which is sounded unto you from the throne of my grace and eternal glory;
rejoice not too much in spirits being made subject, but throw down your crowns before me,
that there be not a self-seeking, self-serving spirit in the family of my people,
but all feel the birth immortal raised up in the resurrection of my life in you all,
which truly makes self of no reputation, so that all loftiness be laid low,
and all haughtiness bowed down in everyone, that I the Lord God in you all may be loved,
obeyed, and exalted; who is taking, and will take to me my great power,
to exalt the meek upon the earth, and reign over all the pride of the children of men,
(that is exalted above my witness in their conscience,)
that so my sons may be brought from far,
and my daughters from the ends of the earth, in the sight of all people,
whom I will make to confess, in subjection to my power,
that you are the beloved people of the most high God,
and of the righteous seed which the Lord has blessed;
and not any weapon formed against you shall prosper, but come to nought,
which will be hastened to your comforts,
and certainly performed according to what is here declared, to your eternal joy;
and you shall assuredly know the mouth of the Lord has spoken it.`'

The word of the Lord, before expressed, came to me in the prison-house at Warwick,
the 13th day of the First-month, 1664,
which constrained me to send it to be read among you, dear, faithful,
and suffering people of the Almighty God,
in whom I remain your brother and companion in tribulation
and kingdom of patience in the Lord Jesus Christ.

[.signed-section-signature]
William Dewsbury.

--

While persecution was on foot in England,
there was some division among those called Quakers, which had its rise some years before.
Those who first appeared to head it, were John Wilkinson and John Story,
preachers among them, who showed themselves discontented against George Fox,
chiefly about the management of church affairs,
because things went not always so as they would have it:
and since George Fox had been the first institutor of good order among his friends,
he was the chief object of the envy of the malcontented.
And because in the beginning there were no such meetings, or discipline,
and yet they had lived in mutual peace and unity; it was asserted,
that such meetings were needless,
and that everyone ought to be guided by the Spirit of God in his own mind,
and not to be governed by rules of man.
By which it appeared,
that they were against the establishing of any order of government in the church.
But they were greatly bent against the women`'s meetings, who as deaconesses,
met together at set times, to provide for poor families,
and sick people that were in need.
It is true,
it was objected that in those meetings sometimes
was debated what was not so convenient in every respect;
because young women were admitted there also,
to see and learn how matters were treated by the grave and ancient women:
and what if some had been a little too forward to
meddle with affairs properly belonging to the men?
The creeping in of a wrong use can by no means justify
the abrogating what is really useful;
and that honest and ancient women took care for the
poor and indigent members of the church,
was indeed laudable.
But as in great communities generally are found some men who love to govern,
without being fit for it; so some of these soon adhered to Wilkinson and Story:
besides several others, who in time of persecution, rather would have met privately,
than have come into public meetings, and so be exposed to the fury of their enemies;
and such also as rather would pay tithes to the priests,
than suffer spoil or imprisonment for the refusal thereof.

From here rose a schism or rent first in the north of England,
and some who went under the denomination of Separatists,
began to keep meetings by themselves, and so to leave their former friends,
though they pretended to agree with them in matter of doctrine.
To these Separatists afterwards resorted such as were not strict livers,
and therefore were unwilling to submit to church discipline:
for this was now become the common saying of these people,
that everyone having received a measure of the Spirit of God,
ought to regard that leader, without minding any rules prescribed by others.

In process of time William Rogers and Thomas Crisp
appeared in print against their quondam brethren,
and upbraided them with every imprudent behavior, or inconsiderate act: besides that,
on mere hearsay, they published a multitude of untruths, and decried even lawful things;
an instance of which appeared when Rogers in paltry verses scornfully reviled them,
that some sustenance had been given from the public cash to indigent preachers, who,
to shun the neglect of their public ministry, could not duly mind their private affairs;
though this supply never exceeded necessary provision.
To this it was answered,
that if it pleased God to call to his ministry persons of mean estate,
the church was not warranted to hinder it, and let such suffer need; since he,
as Sovereign of the universe, could not be limited in the distribution of his gifts.
Rogers would continually appeal to the primitive times,
and to give some color to what they asserted,
he and his adherents published a paper with Edward Burrough`'s name to it,
who had been dead above twenty years; but G. Whitehead and others gave good proofs,
that the apostate John Perrot, had been the author of that so much applauded paper.
At length this rent appeared also in London, where likewise malcontents were not lacking,
who not being strictly conscientious, would rather live without any restraint;
and even some that were honest, were by fair words persuaded to separation;
for among the Separatists one Charles Harris preached, who was pretty fluent in speech,
and not unelegant in his expressions, as I have seen and heard myself.
But how specious soever the pretense of these Separatists was,
and whatever endeavors were made, yet they were not able to continue and subsist firmly;
but at length they decayed and vanished as snow in the fields;
for the best among them came in time to see that they had been deceived;
and the less honest grew worse, for among themselves, they were not free from division:
and though George Keith,
(whose apostasy will be mentioned in the sequel,) endeavored to skulk among them,
yet he got no adherents there.
I have often wondered how Wilkinson, Harris, and Keith,
(all of whom I have known,) could apostatize to such a degree as they did:
but yet this is not so exceeding strange as some may think it to be;
for we find on record, that even in the primitive apostolical church,
was an Alexander the coppersmith, and Hymeneus and Philletus,
who made shipwreck of the faith, and caused a rent, insomuch that it is said,
their words would eat as did a canker.

At London the meetings this year were often disturbed;
but the magistrates themselves seemed not to approve of it,
for they clearly saw there was nothing to be feared from the Quakers,
and yet they were reluctant to give offence to the court party which then prevailed.
G+++.+++ Fox coming once to the meeting in Gracechurch-street,
and being kept out by the constables, stood up in the court and preached to the people;
but a constable plucked him down, and afterwards let him go free.
At another time having been in the meeting at the Savoy, and being brought to a justice,
there was one Gabriel Shad, an informer, who was so full of impertinent talk,
that the justice grew angry; and yet he thought himself bound to do something;
and so asked G. Fox if he did not preach in the meeting; to which he warily answered,
that he did confess what Christ had done for his soul, and did praise God;
and that he thought he might have done that in the streets, and in all places:
and this he was not ashamed to confess,
neither was this contrary to the liturgy of the church of England.
To this the justice said,
the laws were against such meetings as were contrary to the church of England;
and at length spoke of sending G. Fox to Newgate, and said,
he would make a court order after he had dined; but the constable coming then,
the justice bid him come again after the evening service; which the constable doing,
the justice told him, he might let G. Fox go:
and next day he signified to one of G. Fox`'s friends,
that by some accident he had been disappointed of fining him.

Thus G. Fox was freed, and was now much at London,
where a plot was said to be on foot against the king and the duke of York,
of which the duke of Monmouth was said to be the head.
This design, whatever it was, cost the lives of several persons,
among whom was the earl of Essex, who unfortunately perished in the Tower,
and the lord Russel, who was made to bow to the axe.

Now since persecution continued with some color of justice,
those called Quakers drew up the following address to the king:

[.embedded-content-document.address]
--

[.letter-heading]
TO THE KING.

The humble Address of the people commonly called Quakers.

[.salutation]
O King,

The King of kings, and Lord of the whole earth,
incline your heart to that which is just and merciful in his sight,
and to make such clear and equal distinctions,
as that the innocent may not suffer in any case for the guilty;
that it may ever redound to your honor and safety, and the peaceable subject`'s comfort.

Our innocence, love,
and good-will to your person and government that God has committed to you,
encourage us in this our humble address and application.

Whereas the plot against the king, and his brother the duke of York,
etc. is made an occasion to persecute many of us for our religious meetings,
more severely than formerly;
we do solemnly declare that it is known to the Divine Majesty,
and the all-seeing wisdom whereby kings reign, and princes decree justice,
that our manifold, extreme, and continued sufferings, being only on a religious account,
have not been the least motive or provocation to us to desire,
much less to contrive the least hurt, either to your person or government,
or to the person of your brother the duke of York, etc.
We are clear in the sight of God, angels, and men, from all hellish plots,
traitorous conspiracies,
and from all murderous designs and undertakings against the king, his brother,
or any person on earth whatsoever, being works of the devil and darkness;
having contrariwise learned of Christ Jesus our Lord,
by his light and grace in our hearts, not so much as by force to defend,
much less avenge ourselves from the injuries done us,
but to commit the cause to him that judges righteously,
as peaceable followers of our Savior and Redeemer, in his patient example and sufferings,
who is the Prince of Peace.

O king, we do further declare,
that God Almighty has taught and engaged us to acknowledge,
and actually to obey magistracy, as his ordinance,
in all things not repugnant to his law and light in our consciences,
which is certainly agreeable to the holy Scripture,
and admits not of any immoral or injurious actions, and that even where,
through tenderness of conscience we cannot conform, it is our duty patiently to suffer,
and not to rebel, nor seek revenge; and we hope, by his divine grace,
ever to demean ourselves as peaceable minded Christians, in our conduct,
under the civil government; and as we do sincerely and with reverence,
confess to Divine power and Providence in your restoration
and preservation of your person hitherto;
so our prayers and supplications are to the Almighty for your future safety and peace,
and that in a thankful remembrance of God`'s great mercies towards you,
you may be thereby obliged to show mercy,
and relieve the oppressed from these unmerited afflictions and persecutions,
which a great number of us your peaceable subjects do even at this day suffer under,
in our persons and estates; not only by laws made against,
but also by laws never intended against us; and which is more extreme,
several severities of late have been, and still are inflicted,
for which no color or pretense of law has been, or can be alleged;
several jails being so filled, as that they lack air,
and many innocent persons held under extreme distress, without regard to age, sex,
or condition, to the loss of some lives already, and apparent hazard of many more;
if not to the endangering infection in several cities and places in this nation;
and so many houses, shops, barns, and fields, ransacked and swept of goods, corn,
and cattle; tending also to the great discouragement of trade and husbandry,
and to the impoverishing of a great number of quiet and industrious people;
and that for no other cause,
but for their religious worship and exercise of their tender
consciences towards Almighty God that made them,
who is the sovereign Lord of all, and King in men`'s consciences.

Therefore we humbly entreat you, O king, in princely justice.
Christian charity, and compassion, to open our prison doors, and take off our bonds,
where the innocent and oppressed in your land, that fear God, and, in conduct,
truly honor the king; and let not the ruin of such as are quiet in the land,
the widow and the fatherless for their peaceable consciences,
to lie at the door of a prince professing the tender and compassionate religion of Christ.

--

This address was presented to the king at Windsor, on the 8th of the month called August,
in this year, by George Whitehead, Alexander Parker, Gilbert Latey, and Francis Camfield,
in behalf of themselves and their friends;
and it was read to him and his brother the duke of York, then present with some others;
but no considerable ease followed: king Charles, it seems,
was not to be the instrument thereof:
and though that prince by nature was not hard-hearted,
yet there were some that could persuade him to severity.

I find about this time, that one Gabriel Shad,
who had made it his business to serve as informer against the Quakers,
and who had lately informed also against G. Fox, as has been said,
being confined in Newgate at London, for stealing goods from one William Leman,
to the value of three hundred pounds, had been found guilty of felony at the Old Bailey;
but he had such friends, that he was freed from the gallows,
and having obtained the benefit of the clergy,
was discharged with being burnt in the hand.
Such infamous persons were the informers;
for honest people scorned to meddle with such a base and abominable work.

This year the princess Anne, daughter of the duke of York,
was married to prince George of Denmark.
The duke of Monmouth having been under disgrace, came into favor again;
for the king his father indeed loved him, though he was reluctant,
in prejudice of his brother the duke of York, to declare him his legitimate son,
as some great men wished he had.
But the king persisted in his declaration,
that he never had been married to Monmouth`'s mother.

In the next year, 1684, G. Fox and Alexander Parker,
came into Holland to visit their friends there; and after some stay,
they returned to their native country.

In this year died Thomas Stordy of Moorhouse in Cumberland,
a gentleman who twenty-two years before had been condemned to a premunire,
because for conscience-sake he could not swear;
for which sheriff John Lowther seized his estate, real and personal, for the king`'s use,
and kept him prisoner eleven or twelve years,
till discharged by the king`'s declaration in 1672, or 73, and his real estate restored.
After which, he suffered under great fines and spoil for meeting,
and after that was prosecuted on the act for twenty
pounds a month for not coming to their worship;
on which he continued prisoner several years, till he died in December,
having been made willing rather to lose all for Christ`'s sake,
than to be disobedient to him.
This Thomas Stordy released to the land-owners, and their heirs forever,
an impropriation of ten pounds per annum,
which descended to him from his father and grandfather,
making conscience as well of receiving as paying tithes.
Not long before his decease, he exhorted those that were come to visit him,
to faithfulness; '`For,`' said he,
'`if you continue faithful to the Lord while you live in this world, he will reward you,
as now he rewards me, with his sweet peace.`'
Thus piously Thomas Stordy departed this life,
showing forth that he was really a gentleman,
whose chiefest nobility consisted in virtue.
I could mention some other instances, or cases of persecution;
but to make the more speed towards a conclusion,
I will not detain my reader with the relation thereof.

Thomas Briggs, who also had suffered very much,
having been one of the first preachers among the Quakers, and being become old and weak,
about this time wrote a letter to G. Fox,
in which he signified his perseverance in godliness; and not long after,
about the beginning of the year 1685, he died.

It was about this time also,
that the king was seized with such violent fits of convulsion,
that he died in the month called February.
The throne by his death being become vacant,
was filled again by his brother James the Second, who succeeding him,
was the same day proclaimed king.
Now I cannot but take notice, that persecution went on to the death of king Charles,
and continued hot to that very instant; and he being gone off the stage,
many seemed to fear that worse times were at hand,
and that burning of heretics would come in vogue again, as in the former age:
yet some there were who imagined that ease was like to follow;
and that they guessed not amiss, time showed.
