== Chapter XXI.

=== 1685-1688.

[.chapter-synopsis]
* Petition to Parliament for liberty of conscience
* Application to the King
* Statement of the sufferings of Friends
* Proclamation of the King favoring Dissenters
* Stop put to persecution
* Cruelty of an apostate Quaker
* Duke of Monmouth
* Judge Jeffries
* Magistrates of Emden invite Friends to settle in that city
* Consequent correspondence
* The King sets most of the imprisoned Friends at liberty
* Death of David Barclay
* Death of Anne Whitehead
* Liberty of conscience granted
* Addresses to King James
* King`'s order to relieve Friends from taking oaths
* Encroachments of the King in favor of Popery
* Imprisonment of the Bishops
* Address of the Yearly Meeting
* Firmness and faithfulness of Theophila Townsend
* Suffering and deliverance of Theophilus Green
* William Penn and King James
* Convincement, sufferings and death of William Dewsbury
* William, Prince of Orange, lands in England

King James had not been long at the helm of the government,
but the dissenters applied to him for liberty of worship,
and among these were also the Quakers, who made the following petition:

[.embedded-content-document.address]
--

To the King and both houses of parliament,
the suffering condition of the peaceable people called Quakers,
only for tender conscience towards Almighty God, humbly presented.

Showing, that of late above one thousand five hundred of the said people,
both men and women, having been detained prisoners in England, and part of them in Wales,
(some of which being since discharged by the judges, and others freed by death,
through their long and tedious imprisonment,) there are now remaining,
according to late accounts, about one thousand three hundred, eighty and three;
about two hundred of them women.
Many under sentence of premunire, both men and women,
and more than three hundred near it; not for denying the duty,
or refusing the substance of allegiance itself, but only because they dare not swear:
many on writs of excommunication and fines for the king, and upon the act for banishment:
besides above three hundred and twenty have died in prison, and prisoners,
since the year 1660, near one hundred whereof, by means of this long imprisonment,
as it is judged, since the account delivered to the late king and parliament, in 1680;
thereby making widows and fatherless, and leaving them in distress and sorrow:
the two last hard winters restraint,
and the close confinement of great numbers in many jails,
unavoidably tending towards their destruction,
their healths being evidently impaired thereby.

And here in London, the jail of Newgate has been from time to time crowded,
within these two years,
(sometimes near twenty in one room) to the prejudice of their health;
and several poor innocent tradesmen, of late,
have been so suffocated by the coldness of the prison,
that they have been taken out sick of a malignant fever, and died in a few days after.

Besides these long-continued and destructive hardships upon the persons of men and women,
as aforesaid, great violence, outrageous distresses, and woful havoc and spoil have been,
and still are frequently made upon our goods and estates,
both in and about this city of London, and other parts of this nation,
by a company of idle, extravagant, and merciless informers,
and their prosecutions upon the conventicle act; many being convicted and fined,
unsummoned and unheard in their own defense.
As also on _qui tam_ writs, at the suit of informers,
who prosecute for one-third part for themselves, and on other processes,
for twenty pounds a month, and two-thirds of estates, seized for the king;
all tending to the ruin of trade, husbandry, and farmers,
and the impoverishing of many industrious families, without compassion shown to widows,
fatherless, or desolate: to some not a bed left to rest upon; to others,
no cattle to till their ground, nor corn for bread or seed, nor tools to work withal:
the said informers and sheriffs bailiffs in some places
being outrageous and excessive in their distresses,
and seizures, breaking into houses, and making great waste and spoil.
And all these and other severities done against us by them,
under pretence of serving the king and the church, thereby to force us to a conformity,
without inward conviction or satisfaction of our tender consciences,
wherein our peace with God is concerned, which we are very tender of.

The statutes on which we, the said people, suffer imprisonment, distress, and spoil,
are as follows:

The 5th of Eliz.
ch. 23. _De excommunicato Capiendo._
'`The 23rd of Eliz.
ch. 1, for twenty pounds per month.

The 29th of Eliz.
ch. 6, for continuation.

The 35th of Eliz.
ch. 1, for abjuring the realm, on pain of death.
'`The 1st of Eliz.
ch. 2, for twelve pence a Sunday.

The 3rd of K. James I. ch.
4, for premunire, imprisonment during life, and estates confiscated.

The 13th and 14th of K. Charles II. against Quakers, etc. transportation.

The 22nd of K. Charles II. ch.
1, against seditious conventicles.

The 17th of K. Charles II. ch.
2, against nonconformists.

The 27th of Hen.
VIII.
ch. 20, some few suffer thereupon.

Upon indictments at common law,
pretended and framed against our peaceable religious assemblies, for riots, routs,
breach of the peace, etc. many, both men and women, thereupon fined, imprisoned,
and detained for non-payment, some till death.
Instance, the city of Bristol,
what a great number have been these several years straitly confined and crowded in jail,
mostly above one hundred on such pretense, about seventy of them women, many aged.
And in the city of Norwich, in the years 1682 and 83, about seventy kept in hold,
forty-five whereof in holes and dungeons for many weeks together,
and great hardships have been, and are in other places.
So that such our peaceable meetings are sometimes fined on the conventicle act,
as for a religious exercise, and other times at common law, as riotous, routous,
etc. when nothing of that nature could ever be proved against them,
there being nothing of violence or injury either done, threatened, or intended,
against the person or property of any other whatsoever.

The during and tedious imprisonments,
are chiefly on the writs__ de excommunicatu capiendo__ (i.e. a writ ordering the
imprisonment of an excommunicated person until he or she submitted to the church),
upon the judgment of premunire, and upon fines, said to be for the king.

The great spoil and excessive distresses and seizures,
are chiefly upon the conventicle act, and for twenty pounds a month,
two-thirds of estates, and on _qui tam_ writs.
In some counties many have suffered by seizures and
distresses above eight years last past,
and writs issued out for further seizures in several counties, for twenty pounds a month,
amounting to the value of many thousands of pounds,
sometimes seizing for eleven months at once, and making sale of all goods and chattels,
within doors and without, both of household goods, beds, shop-goods, moveables, cattle,
etc. and prosecution hereupon still continued, and in several counties much increased;
so that several, who have long employed some hundreds of poor families in manufacture,
and paid considerable taxes to the king, are greatly disabled from both,
by these writs and seizures, as well as by long imprisonments.
So many serge-makers of Plymouth, as kept above five hundred poor people at work,
disabled by imprisonment.
Many in the county of Suffolk, under a long imprisonment, sentenced to a premunire,
one whereof employed at least two hundred poor people in the woolen manufacture,
when at liberty.
Omitting other instances, that we may not seem too tedious,
these may evince how destructive such severities are to trade and industry,
and ruinous to many poor families.

On the conventicle act, within these two years last past,
many in and about this city of London have been extremely oppressed, impaired,
and spoiled in their estates and trades, upon numerous convictions and warrants,
made against them in their absence,
upon the credit of information sworn by concealed informers,
several of them impudent women,
who swear for their profit in part of the fines and seizures,
their husbands being prisoners for debt through their own extravagance.
The warrants commonly made to break open and enter houses,
which is done with rigor and great spoil, not sparing widows, fatherless,
or poor families, who are sustained by their daily care and industry,
not leaving them a bed to rest upon.
The fines upon one justice`'s warrants amounting to many hundreds of pounds;
frequently ten pounds a warrant, and two warrants at once for twenty pounds,
executed upon one person; and three warrants at once from another justice,
for sixty pounds upon another person,
and all his goods carried away in about ten cart loads;
and five warrants at once for fifty pounds upon another,
etc. besides what we have suffered by others in the like kind.
And in this destructive course the informers have encouragement,
and are allowed still to go on,
to the ruining many families in their trades and livelihoods;
several so discouraged and disabled,
that they are forced to give over their shops and trades.

These informers being accepted for credible witnesses, yet parties,
swearing for their own profit and gain, in the absence of the persons prosecuted;
this we think is very hard, and undue proceeding,
and not consistent with common law or justice.

As also convicting and fining us upon their depositions,
unsummoned and unheard in our own defense, and so keeping us ignorant of our accusers,
unless upon traverse of our appeals.
This procedure appears contrary to the law of God, common justice, and equity,
and to the law and justice of the ancient Romans, and of nations.

And although it has been openly manifested, upon trial of appeals,
at several quarter-sessions, both for Middlesex and London, and other places,
that the depositions of many informers have been false in fact:
yet the great trouble and charge in the traverse of appeals,
and the great encouragement informers have from him who grants the most warrants,
has been a discouragement to many from seeking such difficult remedy,
considering also the treble costs against the appellant, in case he succeeds not,
or is not acquitted upon trial:
whereas there is no costs nor restitution awarded nor given against the informers,
for unjust prosecution.
Some also have refused to grant appeals,
others denied copies of warrants to prevent appeals: which,
whether this be equal or just, pray consider, you that are wise and judicious men:
and whether it be for the king`'s honor, and the people`'s interest, that idle, drunken,
extravagant informers,
should either be encouraged or permitted to go on thus to ruin trade,
husbandry and families, or to command and threaten justices of peace,
with the forfeiture of a hundred pounds, if they do not make convictions,
and issue out warrants upon their late information, and uncertain depositions,
frequently in the absence of the accused.

And lastly, one-third part of the fines being assigned to the king,
he can only remit that; but the informers and poor being assigned two-third parts,
seems not to allow him to remit them, how much cause soever may appear to him,
to extend his favor in that case.
Is not this against the king`'s prerogative, to restrain his sovereign clemency?
And how far it reflects upon the government, and is scandalous thereto,
for beggarly rude informers, some of them confident women, not only to command, threaten,
and disquiet justices, peace-officers, etc. but to destroy the king`'s honest,
industrious and peaceable subjects, in their properties and estates,
is worthy of your serious considerations:
and whether the said conventicle act ought not therefore justly to be repealed.
A noted instance of the like case, we have, concerning the statute of the 11 Hen.
VII. ch.
3, for determining certain offenses and contempt only upon informers`' prosecutions,
being repealed in the first year of K. Hen.
VIII.
ch. 6, though that, in some respects, was more tolerable than this.

Be pleased to make our case your own, and do to us as you would be done unto;
as you would not be oppressed or destroyed in your persons, or estates,
nor have your properties invaded,
and posterities ruined for serving and worshipping Almighty God, that made all mankind,
according to your persuasions and consciences, but would, no doubt,
enjoy the liberty thereof,
so we intreat you to allow the same liberty to tender consciences,
that live peaceably under the government, as you would enjoy yourselves;
and to disannul the said conventicle act, and to stop these devouring informers,
and also take away all sanguinary laws, corporal and pecuniary punishments,
merely on the score of religion and conscience;
and let not the ruin and cry of the widow, fatherless, and innocent families,
lie upon this nation, nor at your door,
who have not only a great trust reposed in you for
the prosperity and good of the whole nation,
but also do profess Christianity, and the tender religion of our Lord Jesus Christ.

And notwithstanding all these long-sustained extremities, we, the said suffering people,
do solemnly profess and declare in the sight of the all-seeing God,
who is the searcher of hearts,
that as we have never been found in any seditious or treasonable designs,
they being wholly contrary to our Christian principle and profession,
so we have nothing but good will,
and true Christian affection to the king and government,
sincerely desiring his and your safety, prosperity, and concurrence in mercy and truth,
for the good of the whole kingdom.

Having thus given you, in short, the general state of our suffering case,
in matter of fact, without personal reflection, we, in Christian humility,
and for Christ`'s sake,
intreat that you will tenderly and charitably consider of the premises,
and find out some effectual expedient or way for our relief from prisons, spoil,
and ruin.

--

[.offset]
The following application was likewise presented.

[.embedded-content-document.address]
--

[.letter-heading]
TO KING JAMES THE SECOND.

The humble application of the people called Quakers.

Whereas it has pleased Almighty God, by whom kings reign,
to take away the late king Charles the Second, and to preserve you peaceably to succeed;
we your subjects heartily desire, that the Giver of all good and perfect gifts,
may please to endue you with wisdom and mercy in the use of your great power,
to his glory, the king`'s honor, and the kingdom`'s good;
and it being our sincere resolution, according to our peaceable principles and conduct,
by the assistance of Almighty God, to live peaceably and honestly,
as becomes true and faithful subjects under the king`'s government,
and a conscientious people, that truly fear and serve God;
we do humbly hope that the king`'s tenderness will appear and extend,
with his power to express the same; recommending to his princely clemency,
the case of our present suffering friends hereunto annexed.

--

[.embedded-content-document.address]
--

[.letter-heading]
TO THE KING.

The distressed Case and request of the suffering people commonly called Quakers,
humbly presented.

[.salutation]
Showing,

That according to accounts lately given, above fourteen hundred of the said people,
both men and women, are continued prisoners in England and Wales,
only for tender conscience towards Almighty God that made them;
many under sentence of premunire, and many near it,
not for refusing the duty or substance of allegiance itself,
but only because they dare not swear; others under fines upon the act of banishment,
many on writs of excommunication; besides some hundreds have died prisoners;
many by means of this long imprisonment since the year 1680,
(as it is judged,) thereby making widows and fatherless,
and leaving poor innocent families in distress and sorrow;
these two hard winters confinement,
tending also to the destruction of many in cold holes and jails,
their healths being greatly impaired thereby;
besides the violence and woful spoil made by merciless informers on the conventicle act,
upon many, convicted unsummoned and unheard in their own defence,
both in city and county, as also on qui tarn writs, and other process,
on twenty pounds a month, and two-thirds of estates seized for the king,
all tending to the ruin of trade, husbandry, and industrious families;
to some not a bed left; to others no cattle to till their ground, or give them milk;
nor corn for bread or seed; nor tools to work withal.
And also these and other severities done under pretense of serving the king, and church,
thereby to force us to violate our consciences, and consequently to destroy our souls,
which we are very tender of, as we are of our peace with God, and our own consciences,
though accounted as sheep for the slaughter:
and notwithstanding all these long extremities,
we the said people do solemnly profess and declare in the sight of the heart Searcher,
that we have nothing but good-will and true affection to the king,
praying for his safety, and the kingdom`'s peace.
We have never been found in any seditious or treasonable designs,
as being wholly contrary to our Christian principles and holy profession.

And knowing that where the word of a king is, there is power, we in Christian humility,
and for Christ`'s sake, intreat,
that the king will please to find out some expedient for our relief in these cases,
from prison, spoil, and ruin, and we shall, as in Christian duty bound,
pray God for the king`'s welfare in this world,
and his eternal happiness in that which is to come.

[.centered]
=== An account of the number of the said prisoners, called Quakers in the several counties.

Bedfordshire....................................................30

Leicestershire....................................................37

Berkshire.........................................................37

Loncolnshire...................................................12

Bristol............................................................103

London and Middlesex....................................66

Buckinghamshire..............................................19

Norfolk.............................................................52

Cambridgeshire..................................................8

Northampton.....................................................59

Cheshire..............................................................9

Nottinghamshire.................................................6

Cornwall..........................................................32

Oxon.................................................................7

Cumberland.....................................................22

Shropshire........................................................18

Derbyshire......................................................... 1

Somersetshire..................................................36

Devonshire.....................................................104

Southampton....................................................15

Dorsetshire.......................................................13

Staffordshire......................................................1

Durham............................................................39

Suffolk.............................................................79

Ely....................................................................11

Surrey...............................................................29

Essex................................................................10

Sussex.............................................................17

Gloucestershire................................................66

Warwickshire...................................................31

Hertfordshire....................................................18

Westmoreland....................................................5

Herefordshire....................................................18

Wiltshire ..........................................................34

Huntingdonshire...............................................10

Worcestershire..................................................15

Kent..................................................................16

Yorkshire........................................................279

Lancashire.........................................................73

Wales................................................................30

Total of Prisoners..........................................1460

[.small-break]
'''

Delivered to the king the 3d of the First month called March, 1683.

--

This list, with the aforesaid petition to the king and parliament,
was not altogether ineffectual: for there was much talk now of liberty of conscience;
but since all the liberty that was enjoyed was only precarious,
it could be but little depended upon;
yet many seemed to be in expectation that some grant
of that liberty would be published in print,
and thus it became a common saying that liberty of conscience was in the press,
which being of an equivocal signification, sometimes afforded matter of sport.
But many of the Episcopal church were so strongly
bent to withhold that liberty from other Protestants,
that there were no ill-grounded reports, that some in authority had promised the king,
to give their vote for liberty of conscience to the Catholics,
provided it was not granted to other dissenters.
Nevertheless the above said petition of the Quakers had such effect,
that the king resolved to ease them from the burden of their oppression,
by way of pardon; for thus far his power reached;
but the abrogating of laws could not be done without the consent of the parliament,
which grew jealous that by the repeal of those laws, the Catholics,
who now had a king of their own religion, would become too powerful.
In the meanwhile the king published the following proclamation:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
James R.

Whereas our most entirely beloved brother, the late king, deceased,
had signified his intentions to his attorneys general for the pardoning such
of his subjects who had been sufferers in the late rebellion for their loyalty,
or whose parents or nearest relations had been sufferers
in the late rebellion for that cause,
or who had themselves testified their loyalty and affection to the government,
and were prosecuted, indicted, or convicted for not taking,
or refusing to take the oaths of allegiance and supremacy, or one of them,
or had been prosecuted upon any writ, or any penalty, or otherwise,
in any of the courts of Westminster Hall, or in any of the ecclesiastical courts,
for not coming to church, or not receiving the sacrament:

And whereas the several persons,
whose names are mentioned in the schedule annexed to this our warrant;
have produced unto us certificates for the loyalty
and sufferings of them and their families:

Now in pursuance of the said will of our said most dear brother,
and in consideration of the sufferings of the said persons, our will and pleasure is,
that you cause all process and proceedings, _ex officio,_
as well against the said persons mentioned in the said schedule hereunto annexed,
as against all other persons as shall hereafter be produced unto you,
to be wholly superseded and stayed;
and if any of the said persons be decreed or pronounced excommunicated,
or have been so certified, or are in prison upon the writ _de excommunicato capiendo,_
(a writ ordering the imprisonment of an excommunicated person until he
or she submitted to the church) for any of the causes aforesaid,
our pleasure is, that you absolve and cause such persons to be absolved, discharged,
or set at liberty,
and that no process or proceedings whatsoever be hereafter made in any
court against any of the said persons for any cause before mentioned,
until our pleasure therein shall be further signified.

Given at our Court at Whitehall, this 18th of April, 1685,
in the first year of our reign.

To all archbishops and bishops, to their chancellors and commissioners,
and to all archdeacons and their officials,
and all other ordinaries and persons executing ecclesiastical jurisdiction.

[.signed-section-closing]
By his majesty`'s command,

[.signed-section-signature]
Sunderland.

--

This was the king`'s first step towards liberty of conscience, as well for Catholics,
as other persons mentioned in the schedule annexed,
which put an effectual stop to persecution,
and the power of the informers was thereby much broken.
And since the most of these were generally base fellows, and profligate persons,
who did not care what they did, provided they might enrich themselves,
they often dealt treacherously even with the persecuting justices;
who also were eager for having part of the prey,
and yet by the artifices of these rapacious wretches were deprived of it,
which some of them now smarted for.
Among the rest, I find that one John Hilton was committed to jail,
as may appear from this warrant of the recorder:

[.embedded-content-document.legal]
--

[.letter-heading]
To the keeper of Newgate.

Receive into your custody the body of John Hilton, herewith sent you,
being charged upon oath before me,
for compounding several warrants under my hand and seal,
for levying of several sums of money on persons convicted
for being at several conventicles in Kent,
London, and Middlesex;
and being also indicted for the same in the several counties aforesaid,
and the bills found against him; and also that he the said John Hilton,
has refused to obey the right honorable sir Edward Herbert, lord chief justice`'s warrant.
And him safely keep, until he shall be discharged by due course of law.
And for so doing this shall be your warrant.
Dated the 23rd of December, 1685.

[.signed-section-signature]
Tho. Jenner, Recorder.

[.postscript]
Let notice be given to me before he be discharged.

--

Thus the informers met with a stop, and the persecuted Quakers got some rest;
for persecution not only ceased, but many,
who for religion`'s sake had been several years kept in prison,
obtained liberty by the favor of a Catholic prince,
which they had not been able to get from his brother, king Charles the Second.
Now many of the fierce persecutors came to shame, some to poverty,
and others to a miserable end, of which no small number of instances might be produced,
if I were minded to enlarge; however I will mention one or two.

One Edward Davis, who once professed to be a Quaker, but not being sincere,
found that way too narrow for him, and so left his friends, whom afterwards,
being become keeper of the jail of Ivelchester in Somersetshire,
he vexed most grievously; and from mere malice fettered some, saying to John Whiting,
and another, whom he had hand-bolted together,
those bolts should not be taken off if lice did eat them up.
And his comrade Joseph Newberry was but little better, for when somebody told him,
that their hands did swell with the irons, he said,
he did not care if their hearts did swell also.
And when one John Dando once asked Davis,
what he thought would become of him when he came to die; he answered,
that he knew what would become of him then,
and therefore he would make the best of his time now.
Also, that he knew where he went out, and where he must come in again,
if ever he was saved; and if he thought he should never return again,
he would be as wicked as he could.
Truly a most desperate saying,
just as if the door of mercy always continued open for man,
and the day of the visitation of God`'s love never passed over his head,
though he persevered in rebellion.
But this Davis came to a most pitiful state, so that he fell into poverty,
and was himself imprisoned for debts, of which more hereafter.
And Newberry fell into a sad condition, being taken with a severe palsy,
and yet he did not leave off cursing and swearing,
talking of the devil in a dreadful manner.
And by lying long in bed, the flesh rotted on his back,
and he who had formerly said concerning the hand-bolted prisoners,
he did not care if their hearts did swell, got now such a sore tongue,
that it swelled out of his mouth, and grew black,
and so he died miserably on the 10th of December.
Thus God sometimes punishes the wicked even in this life.
And though persecutors come not always to such a miserable end,
yet many of these fell into poverty,
and others were discontented because they saw that those whom they had cruelly persecuted,
now enjoyed an undisturbed liberty; for the king who was now on the throne,
continued to give liberty to those that had been oppressed for religion.

But before I say more of this,
I cannot but mention something of the design of the unhappy duke of Monmouth,
who at the death of his father king Charles the Second, was gone to Brussels,
and being come from there into Holland,
he was spurred on so vigorously by some hot-headed Englishmen,
that having got money and assistance of malcontents,
he went over to England with three men of war and some forces,
having given forth a declaration against king James,
which vented a fiery passion toward that prince, and was written,
as I have been credibly told, by the violent Robert Ferguson.
Monmouth being landed with his forces in the West of England, near Lime,
and afterwards routed by the king`'s troops,
was taken prisoner by the perfidiousness of a certain ford,
who thereby obtained pardon for himself; but Ferguson escaped by a cunning artifice,
crying along the road where he came galloping on horseback, '`The rebels are routed,
the rebels are routed!`' Just as if he had been a
courier sent on purpose to court and elsewhere.
But thus he escaped, and come again into Holland,
he told this crafty trick to his acquaintance.
Monmouth having been declared guilty of high treason by a bill of attainder,
as soon as the news came of his design,
was but two or three days after his arrival at London, beheaded.
I count it not unworthy to be mentioned,
that he undauntedly received the news of the death-warrant being come;
and on the scaffold on Tower-Hill, he told the bishops that accompanied him,
'`If I had no true repentance, I should not be so free from the fear of death.`'
And when it was objected, that he ought not to rely too much on that,
since that might be the effect of natural courage, he said, '`No;
I do not ascribe this to my nature; for naturally I am more fearful than others;
but now I am freed from fear; because I feel something in me,
which gives me assurance that I shall go to God.`'
The executioner gave him several strokes with the axe,
before the head was severed from the body; and some ecclesiastics afterwards said,
he died an enthusiast: for not showing himself very ready to comply with their service,
and his saying that something within him assured him that he should go to God,
seemed to them an enthusiastic tenet.
But whatever it was, yet it seems very probable to me, that he was a true penitent,
and so he died in peace; for though I cannot but disapprove his design,
yet by true repentance he might not only have obtained forgiveness of God,
but also have had a full assurance of it.

The earl of Argyle, who rebelled in Scotland against king James, had no better lot;
but I will not detain my reader therewith,
neither with a relation of the dismal execution of many,
who having been found guilty of high treason, either for actual rebellion,
or having been abetters of Monmouth, were sentenced to death by the infamous Jeffries,
who then was lord chief justice, and afterwards chancellor;
the fierceness of cruelty of this judge being such,
that some lost their lives only for having given some hay or food to Monmouth`'s soldiers.
But this not being within my circuit, I will pass it by, and go over to the year 1686.

Therefore leaving England, I will take a turn to Embden, in East Friesland,
where a small company of those called Quakers had
been under a severe persecution for several years,
as I have hinted before,
But the magistrates having persecuted by the instigation of their preachers,
the citizens began to be displeased with it.
And since the Protestants in France were now persecuted violently,
and the Catholic prince had mounted the English throne,
those at Embden grew more inclined to moderation.
Probably the decay of trade also contributed a little to this charge;
for it appeared that the magistrates were for getting more inhabitants into their town,
though they should be Quakers: and this was counted a matter of such importance,
that the common council deliberated on the subject; and two of the members of that board,
namely, Polman and Bonhuyren, were sent to Magdalena van Loar, an inhabitant of Embden,
desiring her to write to England and Holland,
that the magistrates of the city had resolved to give liberty to the people called Quakers,
to live, trade, and traffic there; which grant they offered to confirm by the city seal.
According to their desire notice was given to those of that persuasion at Amsterdam,
from which an answer being returned to the said Magdalena van Loar,
she gave it to the counsellor Polman, and he delivered it to the senate.
After some deliberation, the magistrates with the council of forty,
and the ecclesiastical court met together, and came to a resolution,
of which a copy was sent to Amsterdam.
In this writing were mentioned some conditions on which the magistrates
at Embden were willing to grant liberty to the Quakers,
to live in their city.
But those of that society at Amsterdam, having weighed and duly considered the thing,
found that the proposal contained some expressions, which by others,
who afterwards might come to the helm, and not be so moderate as these at present,
might be used as snares against the Quakers,
if they now should enter upon such terms as were prescribed.
Therefore it was thought more safe not to enter into any engagement,
whereby great inconvenience might afterwards attend their friends,
when the magistracy same to be in other hands.
Yet the conclusion was, to acknowledge the good intention of the magistrates of Embden,
by drawing up the following letter, and sending it to them.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Lords, Burgomasters, Counsellors, and Rulers of the city of Embden.

These are to acquaint you with due respect, that a scheme or plan of yours,
dated the 11th of February, 1686, is come to our hands, which having been perused by us,
we have thought it convenient in the fear of the Lord, to send you the following answer.

First,
we thank God Almighty for the ease and liberty which
our friends at present enjoy under your government,
and are like to enjoy in the future.
And, secondly, we cannot but acknowledge very acceptably your clemency and meekness,
which you show by taking notice of the state of a despised and oppressed people,
who because of their way and worship, differing from the many ways in the world,
are gain-sayed everywhere.
And therefore it is that we are the more stirred up in our minds
to pray fervently to the Lord God for your peace and prosperity,
and the continuance of your good resolution;
that so all those who serve the Lord in uprightness of heart
may lead a peaceable and godly life among you,
by showing forth the fruits of true Christianity in truth, sincerity, and righteousness.
Now as to what you have been pleased to declare,
that you were willing to confirm the aforesaid your good resolution by a public act,
we let you know,
that we are so well satisfied with your word and
oral declaration concerning the aforementioned thing,
that this is more to us than any thing we could further desire,
as knowing that good men think themselves bound by
their good words to perform what is good.
And since you are sensible on what ground you came to the aforesaid resolution,
and declared yourselves thus,
we doubt not but the same persuasion and reason continuing with you,
will prove a more strong engagement to you to perform the same,
than any outward seal can be.
And in that engagement we were willing to acquiesce,
and should not have mentioned any other, unless some among you, as we have been informed,
first had made mention thereof.
And as to what you demand of us,
we declare in the nakedness and simplicity of our hearts,
that in regard of our temporal conduct and deportment, we desire no further protection,
than when we deal righteously to all, and walk according to that golden rule,
that we do unto all men, what we desire should be done to us.
And concerning our religion and worship, which we believe we owe to Almighty God,
it is thus: That since it differs from other persuasions,
it makes us obnoxious not only to the mocking and reviling of ignorant people,
but exposes us also to the malice and envy of many, who hate us without a just cause;
and therefore it is that we stand in need of your favorable interpretation,
and your best construction of what we do, and what we leave undone.
And if we should err in those matters, we shall be the greatest losers by it;
and if truth be on our side, then our adversaries shall not be able to prevail;
for truth is the strongest, and it is not good for any to fight against it.
Howsoever then it may be with us in this matter, yet we hope that you will be pleased,
if we behave ourselves peaceably and honest towards you and all men,
to let us be partakers with our peaceable neighbors, of your general protection.
And though you might please to give us a public act of your aforesaid resolution,
yet we clearly foresee, that it would be hardly possible to use such expressions,
that our enemies, by some wresting or other of the words,
or a wrong interpretation of the expressions contained therein,
should not be able to make us esteemed guilty of transgression,
and so find matter against us.
And therefore we think it very safe, to rely on your word and good resolution,
in which it has pleased you to declare,
that we shall enjoy liberty to live and trade in your city,
provided we pay custom and taxes, which other citizens are subject to;
and that then we shall be at liberty to meet together to worship
God in such a way as he has convinced us we ought to do,
and to call upon him, and to exhort one another to love and good works,
and a Christian conduct.
And on your behalf it will tend to the praise of the magistrates,
that you favor us in this.
And it will also be to the promoting of God`'s glory: and will oblige us to pray for you,
that the Lord God may be pleased to preserve you, and to make you continue in such good,
wholesome, and well-grounded resolution.
We are, and rest,

[.signed-section-closing]
Your true friends and well-wishers,

[.signed-section-signature]
Barent Van Tongeren, William Sewel, Jacob Claus, Stephen Crisp, John Roelofs, John Claus,
Peter Hendriksz.

[.signed-section-context-close]
Amsterdam, the 13th of the Third month, alias March, 1686.

--

In answer to this,
the senate sent the following resolution to the subscribers of the aforesaid letter,
being, as appears by the contents, the decree of the senate,
so as it was entered into their records, of which the authentic copy,
signed by the city`'s secretary, is in my custody.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Lunce 15 Marti, 1686.

Received a letter on the 9 instant, written at Amsterdam the 17th of the same month,
and signed by Barent Van Tongeren, William Sewel, Jacob Claus, Stephen Crisp,
John Roelofs, John Claus, Peter Hendriksz,
in answer to our resolution of the 20th of February last,
with thanks for the promised admission and protection of this city, in their free trade,
and the exercise of their religion, without offending any; signifying thereby also,
that they will be content without an act under our seal,
and willing to rely on our words.
This having been under deliberation, it was thought fit, and resolved,
that our word shall effectually be kept to the rescribers,
and all others of their persuasion,
and that the promised protection shall be really performed.

[.signed-section-closing]
_Ad mandatum senatus speciale,_

[.signed-section-signature]
O+++.+++ Hillings, Sec.

--

Thus it pleased the senate of Embden to give to those called Quakers,
liberty to dwell among them, with the free exercise of their religion.
Sometime after it happened, that the burgomaster Andrews,
coming to the house of Magdalena Van Loar, and the preacher Alardyn,
to the house of her daughter Magdalena Haasbaant,
desired both that they would cause what the senate had resolved,
to be written to England, that so it might be known there,
that if any of the Quakers`' persuasion would come over, and settle at Embden,
they should be well received there.

Hereby we see how God has the hearts of all men in his hands,
and that he turns them wheresoever he will: for the magistrates of Embden,
had some years before from a blind zeal, kindled by those who ought to have stopped it,
given forth very severe edicts against the Quakers, and persecuted them fiercely;
but now they allowed them an entire liberty.

But leaving Embden, I turn again to England,
where persecution by this time also came to a stand,
insomuch that the king ordered that all such imprisoned
Quakers as it was in his power to release,
should be set at liberty; for those that were in prison, for not paying tithes,
etc. were under the ecclesiastical jurisdiction, which was out of the king`'s reach.
But many others who had been in custody several years,
appeared now at London in the annual meeting of their friends,
to the great joy of their brethren;
and when some of these went to thank the king for his favor, they were kindly admitted;
and thereby he drew their inclination towards him; for his endeavors were now,
as he said, to bring about a complete liberty of conscience.
What his aim was, I am not to investigate, for he never attained to it.
In the meanwhile he made persecution generally to cease, not only in England,
but also in other places of his dominions:
for having heard that the Quakers in the isle of Barbados, in the West Indies,
were very much molested, because for conscience-sake they could not bear arms,
he ordered some of the members of his council to write the following letter:

[.embedded-content-document.letter]
--

After our hearty commendations,
his majesty having been pleased to refer unto us
the petition of the Quakers inhabiting in the Barbados,
we have thought fit hereby to pray and require you to examine the
allegations of the said petitions and papers hereunto annexed.
And in as much as his majesty, having lately extended his favor to those people here,
may be inclined to continue the same towards them in this particular,
we desire you to report unto us what ease may be
given them in reference to the militia act,
and the penalties thereby imposed,
as far as it may consist with the safety of the island,
and the preserving of the militia, according to the intention of the said act.
And so we bid you heartily farewell.

[.signed-section-closing]
Your loving friends,

[.signed-section-signature]
Jefferies, Craven, Albemarle, Middleton.

[.signed-section-context-close]
From the Council chamber, Whitehall, the 23rd July, 1686.

--

From this letter it appears plainly that the king endeavored to
relieve the Quakers from that burden of persecution they were under.
The following letter is also a proof of it, written by the earl of Sunderland, then,
as I think, president of the privy council, to the earl of Huntington,
to stop the persecution in Leicestershire and Nottinghamshire,
where one John Smith had acted most grievously:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Whitehall, Dec.
7, 1686.

[.salutation]
My Lord,

The king being informed that one John Smith, a common informer,
does very vexatiously persecute the Quakers in the county of Leicester,
and in the town and county of Nottingham;
and his majesty being pleased to extend his favor to those of that persuasion,
his majesty would have your grace direct the justices of
peace to give no sort of countenance to the said John Smith,
and his prosecution, against the Quakers.

My lord, I am for his grace the duke of Newcastle,
one of his majesty`'s most honorable privy council, etc.

[.signed-section-closing]
Your grace`'s most faithful and humble servant,

[.signed-section-signature]
Sunderland, P.

[.signed-section-context-close]
To the right honorable the earl of Huntingdon,
one of his majesty`'s most honorable privy council, chief recorder of Leicester, custos,
rotulorum of the county of Leicester.

--

The king being thus inclined to give liberty to prisoners,
those who were in custody for religion, neglected no opportunity to obtain it;
of which the following petition is an evidence.

[.embedded-content-document.legal]
--

[.letter-heading]
To chief Justice Herbert and judge Wright, assigned to hold court session,
and jail-delivery for the western circuit, at Wells for the county of Somerset,
the thirtieth of the month called March, 1686.

Several of the people called Quakers, now prisoners in the jail at Ivelchester,
in the county of Somerset, on behalf of themselves and many others of the same people,
in humility show,

That since the wise Disposer of all things,
has ordered your employment in this honorable service, to relieve the oppressed,
and deliver the captives; and since king James II. that now is,
has committed part of his clemency to your custody,
to distribute the same according as the Lord has inclined his heart;
and having taken particular notice of our sufferings,
and signified his will and pleasure, that we, the people commonly called Quakers,
should receive the full benefit of his general pardon, with all possible ease;
which grace and favor we with all thankfulness, acknowledge to God as the chief author,
who has the hearts of kings at his disposal; and to the king,
as being ready herein to mind that which the Lord inclined his heart unto;
and not without hope to find the like opportunity to render to you our hearty thanks,
for the full accomplishment of that`' which our God allows,
and the king so readily grants us;
and also hearing the report of your nobility and moderation,
in managing this weighty trust committed to you,
we are emboldened thus to address ourselves, though in plainness of speech,
yet in sincerity of heart, to lay before you,
that we have for several years been prisoners in the jail aforesaid,
not for any plotting against the king or government, or harm done to his subjects;
our peaceable lives have manifested our fidelity to the king, and love to our neighbors,
it being contrary to our principles to do otherwise; but only for conscience-sake,
because in obedience to Christ Jesus we dare not swear at all, or forbear to worship God,
as he has ordained, nor conform to those worships which we have no faith in;
which to omit the one, or practice the other, we should therein sin,
and so wound our consciences, and break our peace with God:
and what good then shall our fives do us,
if we might enjoy never so much of the world`'s favor and friendship.

Our humble request therefore to you is,
to consider and have compassion for our suffering condition,
and improve the power and authority that God and the king has entrusted you withal,
for our relief and liberty; we still resolving, and hoping, through God`'s assistance,
for the future, to manifest our fear to God, honor to the king,
and honesty to all his subjects, by our godly, humble, and peaceable conduct.
The particular causes of our imprisonments are herewith attested, under our keeper`'s hand.
And we further pray, that mercenary informers, and envious prosecutors against us,
only for conscience-sake, may, according to your wisdom and prudence,
be discouraged from prosecuting such actions;
by which many industrious and conscientious families
and persons are in danger of being ruined;
and we encouraged in our diligence in our respectable calling,
and may enjoy the benefit of our industry;
and so shall we be the better enabled to perform
with cheerfulness the duties we owe to God,
the king, and all men.
The Lord guide you in judgment, and more and more incline your hearts to love mercy,
and do justice, and grant you the reward thereof; which is truly our desire and prayer.

--

This petition was signed by sixteen persons, some of which had been imprisoned fifteen,
others ten, and some fewer years; and to the time of their imprisonment was added,
on what account, that is, on premunire, excommunication, and for tithes, etc.
And it had such effect, that chief justice Herbert discharged these prisoners;
but before this was done, several of those that had been imprisoned there, died.
Many also were set at liberty by the king`'s proclamation;
and it was indeed an unusual thing to enjoy such a free liberty,
that the malicious persecutors were restrained by the higher power.

George Fox was now mostly in and about London,
endeavoring to bring all things among his friends into good order;
and therefore he wrote several papers since he could not be everywhere in person,
and discharge himself by word of mouth.
And lest carelessness should creep in, by reason of the liberty that was now enjoyed,
he wrote the following epistle to his friends:

[.embedded-content-document.epistle]
--

[.salutation]
Friends,

The Lord by his eternal power has opened the heart of the king, to open the prison doors,
by which about fifteen or sixteen hundred are set at liberty;
and has given a check to the informers:
so that in many places our meetings are pretty quiet.
So my desires are, that both liberty and sufferings, all may be sanctified to his people;
and friends may prize the mercies of the Lord in all things, and to him be thankful,
who stills the raging waves of the sea, and allies the storms and tempests,
and makes a calm.
And therefore it is good to trust in the Lord, and cast your care upon him,
who cares for you.
For when you were in your jails and prisons,
then the Lord did by his eternal arm and power uphold you, and sanctified them to you,
and unto some he had made them as a sanctuary; and tried his people,
as in a furnace of affliction, both in prisons and spoiling of goods.
And in all this the Lord was with his people,
and taught them to know that the earth was the Lord`'s, and the fulness thereof;
and that he is in all places; who crowns the year with his goodness.
Psalm Ixv.
Therefore let all God`'s people be diligent and careful to keep the camp of God holy,
pure, and clean; and to serve God, and Christ, and one another,
in the glorious peaceable gospel of life and salvation;
which glory shines over God`'s camp; and his great prophet, and bishop,
and shepherd is among or in the midst of them, exercising his heavenly offices in them:
so that you his people may rejoice in Christ Jesus, through whom you have peace with God.
For he that destroys the devil and his work, and bruises the serpent`'s head,
is all God`'s people`'s heavenly foundation and rock to build upon;
which was the holy prophets`' and apostles`' rock in days past,
and is now a rock of our age; which rock and foundation of God stands sure.
And upon this the Lord God establish all his people.
Amen.

[.signed-section-signature]
George Fox.

[.signed-section-context-close]
London, the 25th of the Seventh month, 1686.

--

In this year David Barclay died at Ury in Scotland.
Before his departure he uttered many excellent expressions indeed.
I may not omit to mention some particulars.
In the latter end of September, being past the 76th year of his age,
he was taken with a fever, which continued two weeks;
and being much troubled with the gravel,
his sickness was accompanied with pain in making water.
Two days before his death, feeling his weakness, and being in an agony,
he said to his son Robert, who was with him, '`I shall now go to the Lord,
and be gathered to many of my brethren who are gone before me.`'
On the 11th of October, very early in the morning, he growing weaker,
the said Robert Barclay signified to him, that his travail was,
that He that loved him might be near him to the end.
To which he answered, '`The Lord is nigh;`' and said further to those about him,
'`You are my witnesses in the presence of God that the Lord is nigh.`'
And a little after he said, '`The perfect discovery of the day-spring from on high,
how great a blessing it has been to me and my family!`' Robert Barclay`'s
wife asking if he would have something to refresh him,
he said it needed not; and laying his hand upon his breast, he said,
'`he had that inwardly that refreshed him.`'
A little while after, he was heard several times to say,
'`The truth is over all:`' and taking his eldest son to him, he blessed him, and said,
'`he prayed God he might never depart from the truth.`'
Then his son`'s eldest daughter coming near, he said, '`Is this Patience?
(for that was her name,) '`Let patience have its perfect work in you.`'
And after kissing the other four of his son`'s children, he laid his hands upon them,
and blessed them.
His apothecary that attended him coming also near, he took him by the hand, and said,
'`You will bear me witness,
that in all this exercise I have not been curious to tamper nor to pamper the flesh.`'
To which the apothecary said, '`Sir,
I can bear witness that you have always minded the better and more substantial part;
and I rejoice to see the blessed end the Lord is bringing you to.`'
To this the sick man replied, '`Bear a faithful and true witness:
yet it is the life of righteousness, the life of righteousness it is,
that we bear testimony to, and not to an empty profession.`'
Then he called several times, '`Come, Lord Jesus, come, come!`' And said also,
'`My hope is in the Lord.`'
Afterwards he slept now and then for some hours;
and seeing a carpenter coming into the room, he said to his son,
'`See you charge him to make no manner of superfluity upon the coffin.`'
In the afternoon several of his friends came to see him, which he having observed,
said they were come in a seasonable time: and after some words were spoken,
and that Patrick Livingston had prayed, which ended in praises,
the sick old man held up his hands, and said, '`Amen, amen,
forever!`' And after those that were present stood up he said,
'`How precious is the love of God among his children,
and their love to one another! thereby shall all men know that you are Christ`'s disciples,
if you love one another.
How precious a thing it is to see brethren dwell together
in love! my love is with you,`' I leave it among you.`'
Several of his friends, pretty late at night, standing about the bed,
and perceiving some of them to weep, he said, '`Dear friends, all mind the inward man,
heed not the outward.
There is one that does reward, the Lord of Hosts is his name.`'
Next morning, after he had heard the clock strike three, he said, '`Now the time comes.`'
And a little after he was heard to say, '`Praises, praises,
praises to the Lord I Let now your servant depart in peace.
Into your hands, O Father, I commit my soul, spirit and body.
Your will, O Lord, be done in earth as it is in heaven.`'
These sentences he spoke by little intervals, one after another;
and soon after five in the morning, the 12th of October, he slept in peace and quiet,
there being present at his end above twenty persons,
who were witnesses to what has been here related.
His corpse was attended to the grave by numerous followers;
and though he had ordered not many to be called to his burial,
yet a great number of the gentry came uninvited, from an esteem they bore to his memory.

In this year also Anne Downer departed this life,
one of the first of those called Quakers at London:
she had been married first to Benjamin Greenwel,
and was afterwards wife to George Whitehead.
Being taken ill, she removed to a place out of London, and her sickness increasing,
she perceived it was like to take her away.
Her ancient friend Mary Stout visiting her, asked her, if she knew her, she said '`Yes,
very well, it is Mary Stout.
I have my memory very well, and my understanding is clear, though I am very weak;
but I am given up-unto the will of the Lord, whether to die, or to live;
for I have been faithful to him in what I knew, both in life and death.`'
Perceiving some to be troubled concerning her, she said,
'`There is no cause for you to be troubled or concerned; for I am well, and in peace.`'
Many Christian exhortations she gave on her dying bed,
and said to some of her friends who came to visit her, '`What,
do you come on purpose to see me?
I take it as an effect of the love of God, and I pray God bless-your children.`'
To another she was heard to say, '`If I never see your face more, it is well with me;
God does know my integrity, and how I have been, and walked before him.`'
The evening before she died, she said to her husband, George Whitehead, etc,
'`The Lord is with me, I bless his name.
I am well; it may be you are afraid I shall be taken away; and if it be,
the will of the Lord be done.
Do not trouble yourselves, nor make any great ado about me; but, my dear, go to bed;
go to rest; and if I should speak no more words to you,
you know the everlasting love of God.`'
She was heard also to say, that she had done with all things in this life,
and she had nothing to trouble her, but was at true peace and easy every way.
And a few hours before she departed, she said, '`Though I am in a dying condition,
yet it is a living death; for though weakness seizes the body,
yet my understanding is as clear as when in health.`'
Thus she departed this life quietly, about the age of sixty-three years,
having been a woman well gifted, and very serviceable to the church,
not only with wholesome exhortations,
but also by her Christian care for the sick and poor, and for widows, and orphans,
who by her decease lost an eminent mother.

About this time George Fox wrote several general epistles,
some of which were pretty large, to his friends, exhorting them to shun strife,
to keep to mutual love and unity, and to mind true piety.
He wrote many other edifying papers; and since the Catholics now appeared barefaced,
and performed their worship publicly, and there was much talk of their praying to saints,
and by beads; in the year 1687, he emitted the following paper concerning prayer,
not fearing to contradict openly that which he judged to be superstition,
though the king himself was of the Catholic religion.

[.embedded-content-document.paper]
--

Christ Jesus when he taught his disciples to pray, said unto them, "`When you do pray,
say.
Our Father, who art in heaven, hallowed be your name,`" etc.
Christ does not say, that they should pray to Mary the mother of Christ; nor does he say,
that they should pray to angels, or to saints, that were dead.
Christ did not teach them to pray to the dead, nor for the dead.
Neither did Christ or his apostles teach the believers to pray by beads,
nor to sing by outward organs; but the apostle said, he would sing and pray in spirit;
for the spirit itself makes intercessions; and the Lord, that searches the heart,
knows the mind of the spirit.

To take counsel of the dead was forbidden by the law of God;
but they were to take counsel of the Lord: and he has given Christ in the new covenant,
in his gospel-day, to be a counsellor and a leader to all his believers in his light.
And men are not to run to the dead for the living:
for the law and testimony of God forbids it.
Those Jews, that refused the running waters of Shiloah,
the floods and waters of the Assyrians and Babylonians came over them,
and carried them into captivity: and they that refuse the waters of Christ,
they are overflown with the flood of the world, that lies in wickedness.
They that asked counsel of stocks and stones,
their state was in the spirit of error and whoredom;
and they were gone a whoring from God, Hos. 4:12.
And they that joined themselves to Baal-Peor,
and ate the sacrifices of the dead, provoked the Lord`'s anger,
and brought the Lord`'s displeasure upon them, Ps. 106:28-29. So here you may see,
the sacrifices of the dead were forbidden.
"`The living know that they shall die; but the dead know not any thing,
neither have they any more a reward,
for the memory of them is forgotten,`" Ecc. 9:5. "`Woe to the rebellious children,
says the Lord, that take counsel, but not of me; and that cover with a covering,
but not of my spirit, that they may add sin to sin.`" Isa. 30:1.

[.signed-section-signature]
George Fox.

--

On the 20th of the month called March, being the 1st month, Robert Widders,
one of the first preachers among those called Quakers, died;
and G. Fox was now much at London; but he grew more and more weak in body,
having endured many hardships in cruel imprisonments for the truth.
Sometimes he went into the country to take the fresh air,
and at other times he was awhile at the country-house of his son-in-law, William Mead,
who married one of his wife`'s daughters.
In the meanwhile he wrote much, for he was of a laborious temper,
and did not omit under all his business to visit the meetings of his friends,
and to edify them by his admonitions and exhortations.
For now they were permitted to keep their meetings unmolested,
since the king in the month called April,
published his long expected declaration for liberty of conscience to all his subjects,
which contained.
That henceforth the execution of all penal laws concerning ecclesiastical matters,
for not coming to church, for not receiving the sacraments,
or for any other non-conformity with the established religion,
or for performing religious worship in any other way, should be suspended, etc.

It would indeed have been more acceptable if this
liberty had been established by the king and parliament,
this being granted as yet only by virtue of his royal prerogative: but however it was,
liberty was enjoyed.
The friends therefore of the church at London,
seeing how those of other persuasions presented addresses of thanks to the king,
for his declaration for liberty of conscience, which was now published,
and whereby the Dissenters were permitted to perform their worship freely,
provided their preaching did not tend to make the minds of people averse to the government,
thought it convenient to draw up an address also, and present it to the king;
which was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To King James II. over England, etc.

The humble and thankful address of several of the king`'s subjects,
commonly called Quakers, in and about the city of London,
on behalf of themselves and those of their communion.

[.salutation]
May it please the king,

Though we are not the first in this way,
yet we hope we are not the least sensible of the great favors
we are come to present the king our humble,
open, and hearty thanks for; since no people have received greater benefits,
as well by opening our prison-doors,
as by his late excellent and Christian declaration for liberty of conscience;
none having more severely suffered nor stood more
generally exposed to the malice of ill men,
upon the account of religion;
and though we entertain this act of mercy with all the acknowledgments
of a persecuted and grateful people;
yet we must needs say, it does the less surprise us,
since it is what some of us have known to have been the declared principle of the king,
as well long before, as since he came to the throne of his ancestors.

And as we rejoice to see the day that a king of England should
from his royal seal so universally assert this glorious principle,
that conscience ought not to be constrained,
nor people forced for matters of mere religion;
(the lack of which happy conduct in government, has been the desolation of countries,
and reproach of religion,) so we do with humble and sincere hearts, render to God first,
and the king next, our sensible acknowledgments;
and because they cannot be better expressed than in a godly, peaceable, and dutiful life,
it should be our endeavor, with God`'s help,
always to approve ourselves the king`'s faithful and loving subjects;
and we hope that after this gracious step the king
has made towards the union of his people,
and security of their common interest, has had a due consideration,
there will be no room left for those fears and jealousies
that might render the king`'s reign uneasy,
or any of them unhappy.

That which remains, great prince, for us to do, is to beseech Almighty God,
by whom kings reign, and princes decree justice,
to inspire you more and more with his excellent wisdom and understanding,
to pursue this Christian design of ease to all religious dissenters,
with the most agreeable and lasting methods: and we pray God to bless the king,
his royal family and people, with grace and peace;
and that after a long and prosperous reign here,
he may receive a better crown among the blessed.

Which is the prayer of, etc.

--

This address was received favorably, and therefore those of the yearly-meeting,
which some time after was held at London,
also drew up an address and some deputies of that meeting went to Windsor,
where the court then was, and where W. Penn,
one of those that had been chosen to present the address,
made the following speech to the king;

[quote]
____
May it please the King,

It was the saying of our blessed Lord to the captious Jews, in the case of tribute,
"`Render to Caesar the things that are Caesar`'s,
and to God the things that are God`'s.`" As this distinction ought
to be observed by all men in the conduct of their lives,
so the king has given us an illustrious example in his own person that excites us to it;
for while he was a subject, he gave Caesar his tribute; and now he is a Caesar,
gives God his due, that is, the sovereignty over consciences.
It were a great shame then for any Englishman that pretends to Christianity,
not to give God his due.
By this grace he has relieved his distressed subjects from their cruel sufferings,
and raised to himself a new and lasting empire, by adding their affections to their duty.
And we pray God to continue the king in this noble resolution,
for he is now upon a principle that has good nature, Christianity,
and the goodness of civil society on its side;
a security to him beyond all the little arts of government.

I would not that any should think,
that we came here with design to fill the gazette with our thanks;
but as our sufferings would have moved stones to compassion, so we should be harder,
if we were not moved to gratitude.

Now since the king`'s mercy and goodness have reached
to us throughout the kingdom of England,
and principality of Wales,
our assembly from all those parts met at London about our church affairs,
has appointed us to wait upon the king with our humble thanks, and me to deliver them:
which I do by this address, with all the affection and respect of a dutiful subject.
____

After W. Penn had thus delivered himself, he presented the address to the king,
which that prince kindly receiving, gave it him again to read; which W, Penn did,
and it was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To King James II over England, etc.

The humble and grateful acknowledgements of his peaceable subjects called Quakers,
in this kingdom, from their usual yearly-meeting in London,
the 19th day of the third month, vulgarly called May, 1687.

We cannot but bless and praise the name of Almighty God,
who has the hearts of princes in his hand,
that he has inclined the king to hear the cries of his suffering subjects for conscience-sake;
and we rejoice, that instead of troubling him with complaints of our sufferings,
he has given us so eminent an occasion to present him with our thanks.
And since it has pleased the king out of his great compassion,
thus to commiserate our afflicted condition,
which has so particularly appeared by his gracious proclamation and warrants last year,
whereby above twelve hundred prisoners were released from their severe imprisonments,
and many others from spoil and ruin in their estates and properties,
and his princely speech in council, and Christian declaration for liberty of conscience,
in which he does not only express his aversion to all force upon conscience,
and grant all his dissenting subjects an ample liberty to worship God,
in the way they are persuaded is most agreeable to his will;
but gives them his kingly word the same shall continue during his reign; we do,
as our friends of this city have already done, render the king our humble, Christian,
and thankful acknowledgements, not only on behalf of ourselves,
but with respect to our friends throughout England and Wales;
and pray God with all our hearts, to bless and preserve you, O king,
and those under you in so good a work:
and we can assure you king it is well accepted in the counties from which we came;
so we hope the good effects thereof, for the peace, trade, and prosperity of the kingdom,
will produce such a concurrence from the parliament,
as may secure it to our posterity in after-times; and while we live,
it shall be our endeavor, through God`'s grace,
to demean ourselves as in conscience to God, and duty to the king, we are obliged.

[.signed-section-signature]
His peaceable, loving, and faithful subjects.

--

After William Penn had read the said address, the king spoke as follows:

[quote]
____
Gentlemen,

I thank you heartily for your address.
Some of you know, I am sure you do, Mr. Penn,
that it was always my principle that conscience ought not to be forced;
and that all men ought to have the liberty of their consciences.
And what I have promised in my declaration, I will continue to perform as long as I live;
and I hope before I die, to settle it so,
that after-ages shall have no reason to alter it.
____

Here we see what the king declared to be his intention;
but perhaps that prince did not consider,
that if such a general liberty had been procured,
he should not have been able to make it continue longer
than the Catholic clergy would have thought it convenient.
For who is ignorant what an unlimited power the Roman prelates have usurped,
not only in the ecclesiastical, but also in the political part?
Insomuch, that though the king`'s intention might have been really sincere,
yet it is like it would have been thwarted,
though he might have been willing that it should be otherwise.
That his meaning was sincere, several I know that were not of his persuasion,
have believed, and among these there were such,
who thought that liberty of conscience might have been so established,
that it should not have been in the powder of the Catholics to break it.
But time has shown that king James was not to be
the instrument for settling such a liberty of conscience;
and that the repealing of the penal laws was reserved for another prince.
Yet the king was by some thought to do what he could to stop rapacious persecutors,
and to restrain their power, with respect to imposing of oaths.
It is true it was said, that the king might not do so;
for by granting this liberty to the Quakers,
he opened a door for the Romanists to bear offices, without taking the required oaths.
Now that he discharged the Quakers from these oaths,
may appear by the following order to the lord mayor of London:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Whitehall, Nov.
6, 1687.

[.salutation]
My Lord,

The king being informed, that Edward Brooker, Henry Jefferson, and Joseph Tomlinson,
being Quakers, are by Mr. Barker, steward of Southwark, put upon several offices,
as constables and the like, which they are willing to do;
but the oaths being tendered to them,
from which they think themselves exempted by the king`'s declaration for liberty of conscience,
they are threatened to be fined and otherwise molested, for their refusal to take them;
his majesty commands me to let your lordship know, that his pleasure is,
that the said Edward Brooker, Henry Jefferson, and Joseph Tomlinson,
and all other Quakers, should now, and for the future,
either be allowed to serve the said offices, without taking any oaths,
or else that they be not fined or otherwise molested upon that account;
and his majesty would have you give order therein accordingly.

[.signed-section-closing]
I am, my Lord, Your Lordship`'s most humble servant,

[.signed-section-signature]
Sunderland.

--

Now whereas in some places goods taken from the Quakers lay still unsold,
the king ordered those goods to be restored to them,
as may appear by the following letter, written to the mayor and aldermen of Leeds,
in Yorkshire:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Whitehall, Dec.
14, 1687.

[.salutation]
Gentlemen,

The King being informed, that some goods belonging to John Wales,
and other Quakers of Leeds,
which were seized and taken from them upon the account of their religious worship,
do remain unsold in the hands of John Todd, who was constable at the time of the seizure,
or in the hands of some other persons; and his majesty`'s intention being,
that all his subjects shall receive the full benefit
of his declaration for liberty of conscience,
his majesty commands me to signify his pleasure to you,
that you cause the goods belonging to the said John Wales,
and all other Quakers of Leeds,
which were heretofore seized upon the account of religious worship, and are unsold,
in whose hands soever they remain, to be forthwith restored to the respective owners,
without any charge.

[.signed-section-closing]
I am, gentlemen.
Your affectionate friend and servant,

[.signed-section-signature]
Sunderland.

--

By such means some got their goods again,
that had been taken from them upon the account of religious worship;
for in many places they lay long unsold, because few would buy goods so taken.
And that the king by these his favors,
drew the love and affection of many of his subjects towards himself, none need to wonder;
for whatever his religion was, he delivered them from that grievous burden,
under which they had been oppressed so many years.
To this may be added, that he used them kindly in all respects;
and would not allow his servants to molest any for not pulling off their hats,
when they came near his royal person.
No, so far went his condescension, that a certain countryman of the Quakers`' persuasion,
coming to him with his hat on his head, the king took off his own hat,
and held it under his arm; which the other seeing, said,
'`The king needs not keep off his hat for me.`'
To which that prince returned, '`You do not know the custom here,
for that requires that but one hat must be on here.`'
I have been told of more such like occurrences, which I pass by;
but it appears from there that the king endeavored to have
among the Quakers the repute of a mild and courteous prince.
And this year he gave also full liberty of conscience in Scotland,
and freed those that were still under sufferings,
granting them the free liberty of their religious meetings.
The said liberty he also allowed to the Presbyterians,
provided they should not meet in the fields, or in sheds, as some did.

The king having thus granted liberty of conscience to people of all persuasions,
did whatever he could to introduce popery in England;
for he permitted the Jesuits to erect a college in the Savoy at London;
and permitted the friars to go publicly in the dress of their monastical orders.
This was a very strange sight to Protestants in England,
and it caused no small fermentation in the minds of people,
when the fellows of Magdalen College at Oxford, were by the kings order dispossessed,
to make way for Romanists, This was such a gross usurpation, that W. Penn,
who had ready access to the king,
and who endeavored to get the penal laws and test abrogated,
thinking it possible to find oat a way whereby to limit the Catholics so effectually,
that they should not be able to prevail, did, for all that,
not omit to blame this usurpation at Oxford and to tell the king
that it was an act which could not in justice be defended,
since the general liberty of conscience did not allow of depriving any of their property,
who did what they ought to do, as the fellows of the said college appeared to have done.
But this could not cool the king`'s zeal for popery, for he drove on so fast,
without disguise, to that degree, that the Pope`'s nuncio, D`'Ada,
this summer made his public entry at Windsor in very great state.

Great endeavors were now made to repeal the penal laws and tests,
for when this point was gained,
then Catholics might be admitted into the-government as well as others;
and such a general liberty of conscience making an alluring show, several dissenters,
as Baptists and others, served the king with their pens on this account: and W. Penn,
who always had been a defender of liberty of conscience,
was also not inactive in this affair, though with a good intent,
howbeit he might have failed in his expectation.
I remember when in those days the patrons of the church of Rome
asserted liberty of conscience to be a Christian duty.
I heard somebody say, "`Can the Ethiopian change his skin, or the Leopard his spots?`"
The king labored also to persuade the prince and princess of Orange,
to give their assent to the repealing of the test and penal laws;
but this could not be obtained of them.
And since the king caused the advocate James Stuart,
to write concerning this matter to the here Fagel,
counsellor and chief pensionary at the Hague;
Fagel answered this paper in a letter to the said James Stuart,
wherein he declared the judgment of the prince and princess in this case;
and signified that they were willing to assent to the repealing of the penal laws,
as far as they had any tendency to the exercise of worship,
but as for those that debarred Catholics from sitting
in parliament of which the test was not the least,
they could not give their assent to the repealing of such limitations.
This letter was generally approved by the Protestants in England,
but the king for all that went on with the introducing of popery;
and about the beginning of the year 1688,
he not only put in several Romanists to be fellows of Magdalen College at Oxford,
but endeavored also to usher those of his persuasion into the magistracy;
and the better to cloak this design, he would have other dissenters also chosen:
but they generally rejected this offer, as did also Stephen Crisp, at Colchester,
who was too circumspect to be caught thus, and therefore he declined the offer.

The king`'s declaration for liberty of conscience was,
on the 27th of the month called April, published again,
to show that he was firm and constant in his resolution,
and that his intentions were not changed since he issued it out,
to excite his subjects to join in it,
and to choose such members of parliament as might
do their part to finish what he had begun.
Hereto was annexed an order of the council,
for reading this declaration in all churches and chapels throughout the kingdom;
and ordering the bishops to send and distribute the
declaration throughout their several dioceses,
to be read accordingly.
But they refused to do so, pretending it was not legal,
(though some there were who thought it was,) because they were against liberty of conscience.
Now the archbishop of Canterbury, and six other bishops,
petitioned the king not to insist on the distribution and reading of his declaration;
alleging that their great averseness to the distribution and publication of it in their
churches proceeded neither from any lack of duty and obedience to his majesty,
nor yet from any lack of due tenderness to dissenters;
but because it was founded upon such a dispensing power,
as had been often declared illegal in parliament.

This refusal the king so resented, that he sent these bishops to the tower.
While they were thus confined, there was much discourse everywhere about this matter;
and since it was well known that some bishops had been the promoters of the former persecutions,
some it seems spoke also in prejudice of these that were now in confinement.
This being reported to them, they said that the Quakers belied them,
and divulged that they, (the bishops,) had been the cause of the death of some.
This gave occasion to Robert Barclay to visit the bishops in the tower;
and speaking with them, he gave them undeniable proofs of some persons who,
by order of bishops, had been kept in prison till death;
though they had been told of the danger of those persons by physicians,
that were not Quakers.
This was so evidently manifested by R. Barclay, that they were not able to deny it:
yet Barclay told them, that since they themselves were now under oppression,
the intention of the Quakers was in no way to publish such matters,
lest thereby they should exasperate the king against them.
And they were careful indeed not to do any thing
that might aggravate the case of these prisoners;
for it was not time now to rub old sores,
since the bishops themselves seemed to be inclined to declare for liberty of conscience.
And since this liberty was now enjoyed all over the kingdom,
those called Quakers thought it convenient at their yearly meeting,
which was held this summer at London, again to draw up an address to the king,
and to acquaint him of one thing more, which continued to be troublesome to them.
This address they presented to him, and was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To King James II. over England, etc.

The humble address of the People called Quakers, from their Yearly-Meeting in London,
the 6th day of the month called June, 1688.

We, the king`'s loving and peaceable subjects, from various parts of his dominions,
being met together in this city, after our usual manner,
to inspect the affairs of our Christian society throughout the world,
think it our duty humbly to represent to him,
the blessed effects the liberty he has graciously granted
his people to worship God according to their consciences,
has had, both on our persons and estates:
for whereas formerly we had ever long and sorrowful lists
brought to us from almost all parts of his territories,
of prisoners, and the spoils of goods by violent and ill men, upon account of conscience;
we bless God, and thank the king, the jails are everywhere clear,
except in cases of tithes, and the repairs of parish churches, and some few about oaths;
and we do in all humility lay it before the king,
to consider the hardships our friends are yet under for conscience-sake in those respects;
being in the one chiefly exposed to the present anger of the offended clergy,
who have therefore lately imprisoned some of them till death;
and in the other they are rendered very unprofitable to the public and themselves;
for both in reference to freedoms in corporations, probates of wills and testaments,
and administrations, answers in chancery and exchequer,
trials of our just titles and debts, proceeding in our trade at the custom-house,
serving the office of constables, etc. they are disabled,
and great advantages taken against them, unless the king`'s favor do interpose:
and as we humbly hope he may relieve as,
so we confidently assure ourselves he will ease us what he can.

Now since it has pleased you, O king,
to renew to all your subjects by your last declaration,
your gracious assurances to pursue the establishment of this Christian
liberty and property upon an unalterable foundation;
and in order to it, to hold a parliament in November next at furthest:

We think ourselves deeply engaged to renew our assurances of fidelity and affection,
and with God`'s help intend to do our parts for the
perfecting so blessed and glorious a work;
that so it may be out of the power of any one party
to hurt another upon the account of conscience:
and as we firmly believe that God will never desert
this just and righteous cause of liberty,
nor the king in maintaining of it; so we hope by God`'s grace,
to let the world see we can honestly and heartily appear for liberty of conscience;
and be inviolably true to our own religion,
whatever the folly or malice of some men on that account may suggest to the contrary.

--

This address being presented to the king, was well received.
Some have been ready to think,
that the latter part of this address concerned the office of magistrates, which,
not without reason, it is believed that a Christian might serve,
with no more disparagement to an inoffensive life,
than it is inconsistent for a pious father to give
due correction to his rebellious child:
for though our Savior charges not to resist evil, but to love enemies:
and that he reproving Peter,
who from a forward zeal cut off the high priest`'s servant`'s ear, said to him,
"`Put up your sword into the sheath:`" and that also
the apostle James disapproves war and fighting,
yet we find in sacred writ, that the apostle Paul calls the magistrate,
the minister of God, and a revenger to execute wrath upon him that does evil:
and he says in plain terms, that he bears not the sword in vain.

But to return to my relation, and to take up again the thread of this history,
from which I have been diverted a little by this digression;
I know there were some in those days,
who thought that if people of all persuasions in England had a share in the government,
proportionable to their number, a means might have been found out to hinder any party,
especially the Catholics, from exalting themselves above the others.
But to me it seems not improbable, that if this had effect,
and a higher hand had not cut off the way thereto,
it would have appeared that those men did not reckon well.
But it never came to this pass, for the king`'s power was tottering already,
though he endeavored to support it, even with good means;
for to be helpful to his subjects, who, though free-born men,
were deprived of their freedom, merely because for conscience-sake they could not swear;
and to help them to this right to which they were entitled as well as others,
could not be judged undue means,
unless under it had been hidden an intent to introduce
this liberty also in favor of the Catholics,
though they did not believe swearing unlawful.

There were now at Norwich, about forty of the people called Quakers,
who having petitioned the king,
that he would be pleased to cause them to be made freemen,
obtained the following order from him:

[.embedded-content-document.legal]
--

[.letter-heading]
To our trusty and well-beloved our Attorney-General.

[.signed-section-context-open]
James R.

Trusty and well-beloved, we greet you well:
whereas we have received a good character of the loyalty of our well-beloved subjects,
Thomas Howard, Peter Launce, William Booley, Henry Jackson, Edward Pears, John Jenn,
Nicholas Comfit, John Harridence, John Gurney, Samuel Wasey, Edmund Cobb, Philip Paine,
Josiah Sherringham, Anthony Alexander, Thomas Darmar, John Cadee, John Fiddeman,
William Kiddle, James Pooley, John Defrance, jun.
Daniel Sharpen, William Milchar, William Brown, John Sharpen, jun.
Samuel Kettle, Stephen Ames, Richard Rose, Benjamin Stud, Edward Monk, John Cornish,
John Hodson, James Polls, Michael Parker, Richard Brown, Daniel Dye, jun.
John Elsegood, John Pike, and John Allen,
we have thought fit hereby to require you forthwith
to make all and every the persons above mentioned,
freemen of that our city of Norwich,
with all the rights and privileges thereunto belonging,
without administering into them any oath, or oaths whatsoever,
with which we are graciously pleased to dispense in their behalf;
and for so doing this shall be your warrant; and so we bid you farewell.
Given at our court at Whitehall, the 13th day of July, 1688,
in the fourth year of our reign.
By his majesty`'s command.

[.signed-section-signature]
Sunderland.

--

It was now said commonly that the king might not do thus;
and those who grudged the Quakers this liberty,
did not hesitate to set forth this dispensation in very ill-favored colors; no,
they said that William Penn advised the king to do
what he could not do without breaking his promise.
Yet if the king had made no greater infringement,
his reign it may be would have lasted longer:
but the dispossessing of the fellows of Magdalen College at Oxford,
the imprisonment of the bishops, and the public admittance of Jesuits and monks,
caused a ferment in the minds of people.
Now the bishops were tried at the king`'s bench bar, in Westminster-Hall;
but they were acquitted, and so released.
The king also had appointed some ecclesiastical commissioners;
but many looked upon this as a kind of inquisition,
and it seemed not well to agree with liberty of conscience,
which if he had maintained justly,
according to the advice of the Quakers in their address,
it is not likely that he would have come to such a strait, as now he was put to.

Not long before this time, one Theophila Townsend, a woman of years, and understanding,
published a book,
wherein she gave a relation of the grievous persecution
her friends in Gloucestershire had suffered,
by imprisonment and spoil of goods,
and how she herself had also undergone many sufferings,
and had been imprisoned in the castle of Gloucester more than three years.
Among other cases, she relates also, how some time before her imprisonment, it happened,
that by order of the justices, Thomas Cutler and James George,
she being seized in the street, said to the latter, that the Lord would plead her cause,
and that what measure he meted, should be measured to him again.
And it thus happened, that before she was released, the wife of the said George,
who took her from her husband, was by death taken from him.
Afterwards this George came with the bishop of Gloucester into a meeting,
where Theophila was on her knees praying;
at which the bishop asking him whether she was the woman he spoke of, and he answering,
'`Yes, my lord;`' the bishop took her by the arm with such violence,
that he had almost pulled her down backward, saying, '`Give over, woman,
and obey the king`'s officers.`'
But such was her zeal, that it could not be stopped;
for the more opposition she met with, the more she felt herself encouraged, and inspired,
to praise God for his goodness: and though the bishop stirred up the justice,
yet it seemed not in his power to break off the current of her speech;
so that they let her alone, till she having discharged herself, stood up.
Then the names of those that were met, were taken in writing: and sometime after, she,
though aged and weakly, was in winter-season led three or four miles through the snow,
and committed to jail at Gloucester, where she was kept three years and four months,
and then released by king James.

Afterward she published a book, as has been said already,
in which she gave an account how some of her friends had been beaten, punched,
and abused, to that degree, that they died of it, as she testified to have seen herself:
'`Yet,`' said she, though many died who were stronger than I,
it has pleased the Lord to preserve my life, that I may speak to the praise of his name,
and tell of his wonders, and put you, persecutors,
once more in mind of what belongs to your peace.
Blessed be the Lord, he is risen for Zion`'s sake, which you have plowed long as a field;
and when their enemies have done their worst,
then the Lord shall make his Zion to be an everlasting glory,
and Jerusalem the praise of the whole earth.
And as you see now in others that persecution is evil, so see it also in yourselves;
repent in dust and ashes.
Remember who it was that said, the wise man`'s eyes are in his head,
but the fool walks in darkness.
The eyes of fools look out for mistakes in others,
and they blame in others what they are guilty of themselves.
I think the eye-lids of the morning, that is now dawned and rising before you,
ought to bring you to a true sight of your condition in this matter.`'
Going on thus,
she reproves the informers who had enriched themselves with the spoils of their neighbors;
and she also relates how the priest of Gloucester
had put his name to a petition to the king,
in which, justice George, and others,
desired that the meeting-house of the Quakers might be given to the town,
to make a work-house of for the poor, '`But,`' said she, '`this is like Judas, who,
when the woman came with an alabaster box of very precious spikenard, said,
'`Why was this waste made?
Why was not this ointment sold, and the money given to the poor?`'
But the scripture says, that this he said, not that he cared for the poor,
but because he was a thief, and had the bag.
Thus the priest made it appear by what he did,
that he was not a true minister of the gospel; for he came short of the works of the law,
which says, '`You shall not covet your neighbor`'s house,
nor any thing that is your neighbor`'s.`' And Christ commands to do unto men,
what we would have them to do to us;
by which it is plain that such doings are contrary to the law and the gospel.
Those now who will have such blind sleepy watchmen to be their teachers,
let them pay them, and not constrain others, who know them to be blind,
to pay them also.`'

Then speaking to those who had a hand in the spoiling of goods,
and setting forth the odiousness of that work, she says at last,
'`I do not write this from a spirit of revenge against any, but it is in the love of God,
to warn you, and to exhort you to repentance, that you may find mercy with the Lord,
which is the real desire of my soul: I can truly say, in the presence of the Lord,
that I have nothing in my heart but love and good-will to the worst of our enemies,
and this in purity of heart, and in sincerity of mind.
I desire really your eternal peace, and well-being,
though you have hardened your hearts against the Lord, and his truth and people.
Turn to the Lord, I beseech you; bow before the Almighty, who will plead with all flesh,
and shall call all to an account,
and reward everyone according to what he has done in the body, whether it be good or bad.
Consider this therefore while you have time,
and mind the things that belong to your peace, before they be hid from your eyes:
for the long suffering of the Lord will come to an end, who said,
"`My spirit shall not always strive with man.`"
Therefore while the spirit of the Lord, his light, his grace, yet strives in your hearts,
to turn you off from your evil ways, be willing to embrace it, believe in it,
take counsel of it, submit to it with all your heart,
be willing to be led and guided by it,
and incline your hearts to follow it in all things,
and then it will lead you to rest and peace with the Lord forever.
Yet more she said; but I break off.
By such kind of emphatical speeches,
sometimes persecutors have been so touched to the heart,
that they themselves became harmless Christians.

I am come now almost to a conclusion of my relation concerning persecution;
of which I could have written much more,
but that I was unwilling to extend my work beyond
what I should have been well able to complete.
Yet before I altogether part with this matter,
I will mention something concerning Theophilus Green,
of whom mention has been made before.
He lived at Battersea, not far from London, and was a man beloved of his neighbors,
because of his honest conduct; yet he was much persecuted, both for attending meetings,
and for preaching.
Once it happened that some officers came to his house to see whether there was a meeting,
and they behaved themselves moderately: for what they did seemed against their mind,
it being only in obedience to the order of justice Duke, who,
on account of a former offence, had issued out warrants to make distress.
The officers not satisfied in the case, and seeing no meeting, went their way,
and returned the warrant; and T. Green went afterwards to the said justice,
and speaking to him,
said among the rest,`' Consider what that mouth and tongue of yours has said formerly,
that I had been ever kind to you; and is this the way of requiting it?
Know for certain, that that God whom I have served, and for whose cause I now suffer,
will avenge me; for vengeance is the Lord`'s, and he will repay it one way or other,
except you speedily repents.`'
At this saying the justice began to tremble, and crying out, said,
'`I will do you no more hurt than I will do my own soul.
Pray go to the officers and tell them,
I will never trouble them any more upon the account of you.`'
Green did so; and they were glad of it.
And Duke being upon some complaint dismissed,
one Sir John Broadrick succeeded in his room; and he was so moderate,
that he prevented the informers,
by keeping Theophilus and his friends out of their meeting-house,
which was for about two years and a half.

Afterwards they were permitted again to go into their meeting-house,
but then justice Forster came once, and taking their names,
fined Theophilus 10 as a preacher.
And afterwards he with others coming with a constable to seize for the fine,
the constable being come to the door of the house, said, '`neighbor Green, where are you?
We are come to seize your goods, if you will let us in.
But this so displeased the justice, that going down the yard,
and seeing some oars and poles, he required the constable to take them away.
To which he answered, '`I am no porter.`'
'`Then,`' said the justice, '`command some others to do it.`'
To which the constable returned, '`I command you to do it.`'
This so enraged the justice, that he fined him.
Some time after the said justice coming again with a high constable,
and another petty constable, seized a barge, and had it carried away,
and several times offered it to sale, but none would buy it.
And after it had been carried about from place to place for sale,
at length it was found adrift by one who knew not of its being seized;
and hearing that it was Theophilus`'s barge, he brought it to him.
But Theophilus went to the constables, and told them how it came to him,
and where he had it, saying, since it was come to him again he was willing to keep it;
but if they took it away again he would not hinder them.
This account being given to the justice, he sent a warrant,
and committed Theophilus to the Marshalsea prison.
After three weeks the sessions was held at the Marshalsea;
and the last day the said justice came to him in the prison, saying,
he came out of love to see him, and to advise him for his good; which was,
that he would have him pay his fine; '`for,`' said he,
'`I am sure the grand jury has found the bill against you; and if you should come off,
I have such an influence with the judge, as to cause the oath to be tendered to you;
and I know you will not take it; and then you will be run to a premunire,
and are not like to come out as long as you live.`'
To which Theophilus answered, '`You said your coming was in love,
to advise me for my good; but by what you have said, it appears the contrary;
for now I perceive you have devised as much mischief as you can against me.
As to the fine, if it were but ten pence, no ten farthings, I would not pay it.
And if the Lord should permit you to do as you have said,
and so be the cause of bringing my grey hairs the sooner to the grave,
my blood will be at justice Forster`'s door, and it will cry vengeance against you.`'

The next day the two constables being called before the grand jury,
were asked what they had against Theophilus Green, that stood there indicted;
and the high constable answered, '`As to Theophilus Green, he is as honest a man,
though a Quaker, as lives about us; and he was lately in office for the poor,
and behaved himself as well in it as any has done these twenty years.
And touching the barge he is indicted for, when it came to him he came to us,
and told how it came, and where he had laid it, saying,
if we would take it away again he would not hinder us.
This is all we have to say.`'
Some of the grand jury knowing Theophilus very well, and the cause too,
did aggravate the matter very high against the justice:
and as to the indictment they brought it in ignoramus.
So Theophilus was cleared by proclamation: and sir Richard How, being one of the jury,
advised him to arrest the justice, there being two good actions,
as defamation and false imprisonment.
But Theophilus said he acknowledged their love, but would leave the thing to the Lord,
for whose cause he suffered; for vengeance was the Lord`'s, and he would repay it.
And it was but some little time after that the said justice Forster died,
as was reported, in great horror and misery.
The time when this happened I do not know exactly,
yet I take it to have been some years before the time I now describe.
We see by this instance a very singular deliverance, such as did not befall everyone,
but which could not but encourage Theophilus the more.

Before I conclude this year I must mention something concerning W. Penn,
who when the government of king James was sinking,
not only bore the blame of many miscarriages; but by some was styled a Catholic,
though this was altogether false.
But he had a great many enemies;
and it was no new thing to brand the Quakers with the odious name of Jesuits:
for thirty years before this time at Bristol great endeavors
were used to persuade people they were Franciscans.
William Penn patiently bore the slander of being decried as a Roman Catholic,
saying but little in justification of himself,
till at length he made a return to a letter sent by one who seriously begged of him
to give an answer to those accusations that had been forged in prejudice of his reputation.
In this paper he ascribed his free access to the king, partly to the relation his father,
as admiral, and to the service of the said king, and who was then duke of York,
and high admiral of England;
and his special favor also in releasing him out of the tower of London in the year 1669.
To this he added, '`My father`'s humble request to him, upon his deathbed, was,
to protect me from the inconveniences and troubles my persuasion might expose me unto;
and his friendly promise to do it, and exact performance of it,
from the moment I addressed myself to him: I say, when all this is considered,
anybody that has the least pretense to good-nature, gratitude, or generosity,
must needs know how to interpret my access to the
king.--Is any thing more foolish as well as false,
than that because I am often at Whitehall,
therefore I must be author of all that is done there, that does not please abroad.
But supposing some such things to have been done;
pray tell me if I am bound to oppose any thing I am not called to do:
I never was a member of council, cabinet, or committee,
where the affairs of the kingdom are transacted.
I have had no office or trust, and consequently nothing can be said to be done by me;
nor for that reason could I lie under any test or any obligation
to discover my opinion of public acts of state:
and therefore, neither can any such acts, nor any silence about them,
in justice be made my crime.
Volunteers are blanks and cyphers in all governments.
And unless calling at Whitehall once a day, upon many occasions,
or my not being turned out of nothing,
(for that no office is,) be the evidence of my compliance in disagreeable things,
I know not what else can with any truth be alleged against me.
I am not without apprehensions of the cause of this behavior towards me;
I mean my constant zeal for an impartial liberty of conscience.
But if that be it, the cause is too good to be in pain about it.
I ever understood that to be the natural right of all men;
and that he that had a religion without it, his religion was none of his own.
For what is not the religion of man`'s choice, is the religion of him that imposes it:
so that liberty of conscience is the first step to have a religion.
This is no new opinion with me,
I have wrote many apologies within the last twenty years to defend it,
and that impartially.
Yet I have as constantly declared, that bounds ought to be set to this freedom,
and that morality was the best;
and that as often as that was violated under a pretence of conscience,
it was fit the civil power should take place.
Nor did I ever once think of promoting any sort of liberty of conscience for any body,
which did not preserve the common protestancy of the kingdom,
and the ancient rights of the government: for to say truth,
the one cannot be maintained without the other.--And till I saw my own friends,
with the kingdom delivered from the legal bondage which
penal laws for religion had subjected them to,
I could with no satisfaction think of leaving England,
though much to my prejudice beyond sea, and at my great expense here,
having in all this time never had either offense, or pension,
and always refusing the rewards or gratuities of those I have been
able to oblige,`' From this little abstract of William Penn`'s Apology,
it appears sufficiently what kind of liberty he defended;
and such a liberty afterwards took place in the reign of the next king.

Of George Fox I have been long silent,
and I do not meet with any very remarkable transactions that concerned him,
except that he wrote much, both for edification of his friends,
and for the instruction and admonition of others;
for he was continually occupied with the care of the church,
and that things might be kept in good order, which to perform the better,
he now stayed a long while in and about London.

In this year died William Dewsbury,
one of the first preachers among those called Quakers;
having been a very zealous teacher, and an eminent instrument to the conversion of many.
He was born in Yorkshire, and in his youth was a shepherd,
and afterwards put apprentice to a clothier; but when the civil wars broke out,
he became a soldier and joined with those who said they fought for the gospel.
Now though he was religious according to his knowledge;
yet growing more and more serious, and turning his mind inwardly,
he saw there were inward and spiritual enemies to encounter with,
according to the saying of the apostle, '`We wrestle not against flesh and blood;
but against spiritual wickedness,`' etc.
And this state was inwardly manifested to him in the words of our Savior:
'`Put up your sword into the sheath.
If my kingdom were of this world, then would my servants fight.`'
This wrought so powerfully upon his mind,
that he could no longer meddle with martial affairs, but left the army;
and returned to his former calling, endeavoring to improve in true godliness,
in which he so advanc ed gradually, that when George Fox in the year 1651,
came to Balby in Yorkshire, and preached the gospel there,
he could not but consent to the doctrine declared by him,
as being the same of which he himself was already convinced in his mind, namely,
that heed ought to be given to the inward Divine reproving for that which is evil,
which doctrine was preached by George Fox under the denomination of the true light,
which enlightens every man coming into the world; and that heed must be given thereunto,
as being the grace which brings salvation,
of which the apostle speaks in his epistle to Titus 2:11, saying,
"`That it has appeared to all men.`"
W+++.+++ Dewsbury having heard such a sermon as this,
agreed not only with G. Fox in this point of doctrine,
but in process of time became himself also a very zealous preacher of it,
for which he fell under great sufferings;
insomuch that he was prisoner at Warwick nineteen years for religion`'s sake,
besides the imprisonments he suffered on that account in other places.
But being now released, he came in the month called May to London,
and preached a sermon there concerning regeneration,
which was taken from his mouth in short hand, and afterwards printed as underneath.

[.embedded-content-document]
--

[.letter-heading]
A Sermon preached by William Dewsbury, at Gracechurch Street, the 6th of the Third month,
1688.

[.salutation]
My Friends,

Except you be regenerated and born again, you cannot inherit the Kingdom of God.

This is the word of the Lord God to all people this day;
this lies not in airy profession, and in vain imagination,
and whatsoever else it is that you deck yourselves withal;
you must every particular man and woman be born again,
else you cannot enter into the kingdom of heaven.
This was the doctrine of Christ in that prepared body wherein he appeared in the world,
and preached to Nicodemus, that standing doctrine to this moment of time,
and will be so while any man breathes upon the earth; there is no other way,
no other gate to enter into life, but by this great work of regeneration.
Now to enforce people to come to this great work,
and to set forward from earth to heaven,
all being driven out of Paradise by the cherubim set with a flaming sword,
there is no returning to that blessed life,
but by the loss of that life that did grieve the Spirit of God,
and which did cause man to be driven out;
there is no other way of return again but by this new birth.
As you are all driven and forced out of Paradise,
and the flaming sword and the cherubims are set to keep the way of the tree of life,
so you must return into the favor of God again, by the light of Christ;
and you have line upon line, precept upon precept, here a little, and there a little,
to direct your minds to the light of Christ Jesus,
As the first Adam was made a living soul, so the second Adam is a quickening spirit.
This know for certain, no man or woman can be quickened,
and raised up into the life of the second Adam,
till the life of the first Adam be taken away from them.

So now, let every one of you deal plainly with your own hearts,
how you came to be a slain people to the life of the first Adam,
in which life there was a working of the mystery of iniquity in every part of man.
One cries,
'`Lo here is Christ;`' another,`' Lo there is Christ;`' and every one
is following his own imagination about the letter of the Scripture;
this is still but the vain spirit of man, running and striving to recover himself;
and this is the cause there is so much profession of God,
and so little of his nature appearing among the sons and daughters of men.
Now all of you that come to be regenerated, you must come to the light of Christ;
there is no other way to it.
He will search your hearts, and try your reins, and set your sins in order before you,
and trace out the iniquities that compass you about;
therefore you must see yourselves a lost people, a sinful people,
and so come to feel the weight of your sins upon your consciences,
there is no other way to come to life;
you will never complain of sin till you are burdened with it,
till you have a trumpet sounding in your ears, to awaken you,
that you may arise from the dead, that Christ may give you light: there is no other way,
dear people, you must bring your deeds to the light of Christ,
and abide in the sentence of condemnation; if you save your lives, you lose them;
if you will lose your lives for Christ`'s sake, there is no danger of your eternal life.
John the Baptist, Christ`'s forerunner, declared,
"`I indeed baptize you with water unto repentance,
but he that comes after me is mightier than I,
the latchet of whose shoes I am not worthy to unloose,
he shall baptize you with the Holy Ghost, and with fire: whose fan is in his hand,
and ho will thoroughly purge his floor, and will gather his wheat into his garner,
but the chaff he will burn with unquenchable fire.`"
What is it the better for you to read the Scripture, if you know not this fiery baptism,
which all must know that are regenerated; deceive not yourselves,
Christ will appear in flaming fire, and take vengeance on all those that know not God,
and that obey not the gospel of our Lord Jesus Christ.

I stand here as a witness of the Lord of life this day,
there is no way for people to come to salvation,
but they must know Christ revealed in all their hearts.
What is he doing but rendering vengeance upon the carnal mind, self-pleasing,
and all inordinate affections; he comes with vengeance to take away your life;
he will baptize you with the Holy Ghost, and with fire.
If you know not this, you are not a true Christian,
you will never look death in the face with joy, nor go down to the grave with triumph.
If you live at home in the body, and flee for your life,
and will not be willing to lose your life for Christ if you are called to it,
and if you will not have Christ to wash you,
(some for shyness and some for self-love will refuse this,) if Christ does not wash you,
you have no part in him; you must come to Christ to purify you in the fiery furnace;
the day of the Lord shall burn as an oven,
(as the prophet speaks:) this is a dreadful day, a day of vengeance,
the day of the Lord Jesus Christ, who redeems his people from their sins.
Zion is redeemed with judgment, and established with righteousness.
Do not make the way to heaven easier on your minds and imaginations than indeed it is,
and think it not sufficient to live in an outward observance of the ways of God.
If your own wills be alive, and your corruptions remain unmortified,
the judgment of God will be your portion,
therefore in the Lord`'s name come along with me;
I am come to declare what I have heard and seen of the Father.
Come and examine your conscience.
Have you brought your deeds to the light?
Then you have received condemnation upon yourself, and your haughtiness is bowed down,
and laid low, and you see yourself a poor miserable wretch, before the eternal God.
Whatsoever you know of the mind of God, have you reformed your ways?
Come along with me, and tell me what is the ground of your faith, and your confidence.
Is it your obedience and qualifications?
Because your obedience is right, and your qualifications right,
what use do you make of them?
Read the book of conscience; have you no ground for your faith?
You have put on the reformed faith, and lives an unreformed life:
search and try yourself, man or woman.
Do you watch over yourself, and keep in a sense of your dissolution,
notwithstanding all your qualifications and partial reformation?
Do you strive to enter in at the strait gate, and the narrow way?
Here is the lost sheep you seek, the life of your will, the life of the first Adam;
the Justice of God will not allow you to make a saviour of your duties and qualifications;
and to take God`'s jewels, and to deck yourself with them,
you can not be saved without the righteousness of God in Christ Jesus.
What says your conscience, are you brought to this change of your mind,
and of your conduct?
Are you all willing to part with your sins, with your pride and haughtiness?
Are you willing to part with your vile affections?
This is the work of God`'s grace upon you.
Do you place your confidence in your duties and qualifications,
and take God`'s jewels and ornaments, and deck yourself with them?
You took my jewels, says the Lord, and did play the harlot; if you return to the Lord,
and Humble yourself, and get through this difficulty, you will be happy forever.
This judgment of God, this flaming sword that turns every way,
will keep you from returning to sin, and bring you to Christ,
and cut you off from all hope of salvation but by him,
and make you to see the absolute need of a Savior,
and that your life is hid with Christ in God.

It is God`'s infinite goodness to men that he will hide pride from them,
and humble them under his mighty hand.
This is the condition of poor creatures that are slain by the hands of the Most High.
How may I know when I am slain and baptized, and come to have sincerity?
They that have this baptism enter into the heavenly life;
if you love the light of Christ Jesus, it will be thus with you;
God will make short work in the earth.
He will set your sins in order before you, and make you watchful unto prayer,
and lead you to holiness of life and conduct, and make you abhor yourself,
and despise all the pomps and pleasures and vanities of this world.
When he has adorned you with his graces, then watch for the light,
and in the light of Christ you shall see light, and that all you have done, and can do,
is but your duty.
All this you ought to do; you are God`'s creature,
and all this will not justify you in order to your eternal salvation,
for these services you owe unto God.
If you diligently wait, you shall see more light;
then the sword that proceeds out of the mouth of Christ, who is called the Word of God,
will cut you off from all your hopes of salvation from any thing you have done,
from any of your qualifications, from any thing that you can do;
so that you will be a hopeless soul, nothing in your own sense and apprehension;
the power of the first Adam must die before him, and you will cry out, '`I am a dead,
lost, and undone creature; but there is a life hid with Christ in God for me,
but I can never have it till I be slain into the will of God,
and become as a little child,
and be stripped of all my own excellency that I have attained;
I must come to a sense of my own misery, and fall down at the foot of God;
when I am become as a little child, humbled and slain as to my own will,
and confidence in my own righteousness;
I will not then question but I shall live a holy life,
but I will give all that life I had, for that life which is hid with Christ in God.`'
O! there is none come so far that ever miss of eternal life.
All shuffling people that would have salvation by Christ,
and will not let him exercise his heavenly power,
his princely glorious power to baptize them into his death,
it is they that come short of salvation;
but all those that yield themselves up to Christ to be redeemed through judgment,
and are become as little children, these are in a happy state.
You know that our Lord Jesus Christ took a little child in his arms, and said,
"`Whosoever becomes not as a little child,
cannot enter into the kingdom of heaven:`" you must all of you become as little children,
and depend upon the mercy and free grace of God;
you must all come to a holy resignation of your wills to God`'s disposal;
if you come to Christ as little children, and depend upon him,
you cannot miss of salvation; it is entailed upon such souls as hear the voice of Christ,
they that hear the voice of the Son of God shall live.

I stand here as a witness for the God of heaven, I never heard the voice of Christ,
as his follower, till I was slain and baptized,
and lay as a little child under his heavenly chastisements;
as soon as ever my soul was brought to this in my humiliation,
O then the dreadful judgment was taken away, and the book of life was opened unto me,
and the Lord spoke comfortable to me, I have loved you with an everlasting love:
and I was made a Christian through a day of vengeance, and of burning as an oven,
and the haughtiness and pride of man in me was brought low.
Now in this conformity to Christ`'s death people may die into life,
and blessed are the dead that die in the Lord, for they rest from their labors,
and their works do follow them.
Away with all your own wills, and your pride, and haughtiness,
and your hypocrisy and deceit, and all dependency upon any qualifications of your own;
you must come to have your life separated from you, else you will all perish.
Those that will die with Christ, and be willing to die for him,
he is revealed as a Savior to them.
He was before us in the days of his flesh, and complied with his father`'s will:
he was nailed to the cross.
The Son of God, when he was come to the depth of his sufferings, what was his cry,
"`My God, my God, why have you forsaken me?`"
This was for your sake, and my sake,
and every man and woman`'s sake that do believe in him:
he drank the cup which his Father gave him to drink.
If it was done thus to the green tree, what shall be done unto the dry?
He went before us, and when he comes again he will take up to himself,
and take us from the filth of sin, that we may be made new creatures.

Now except we be born again we cannot enter into the kingdom of God,
and there is no becoming new creatures, till we be slain to the old man.
You must be slain to your pride and haughtiness,
and the corruption of your own will and all selfishness,
you must have God to burn it up in you: the Holy Ghost will destroy,
and burn up nothing in you, but that which will bring an eternal fire upon your soul.
Show me you whom my soul loves; where is the path of life, the footsteps,
of the flock of your companions.? Why should I be as one that goes aside.`'
Now everyone that lives at home in the bosom of self, take this with you,
though you profess the truth, and live in an outward conformity thereunto,
yet if you secretly indulge your corrupt wills, and live a flesh-pleasing life,
and consult with flesh and blood, and are not rent off from your lusts,
you cannot enjoy the Lord of life; while I am at home in the body,
I am absent from the Lord.
'`The body of sin is a loadstone to draw you from the life of God,
and from glorying in the cross of Christ: this is flesh and blood,
and flesh and blood cannot inherit the kingdom of God.
For the Lord`'s sake, for your soul`'s sake, and for the sake of your eternal happiness,
put not of this work, but pursue it, and it will be perfected.
See how Christ is revealed in you by the Holy Ghost, and with fire.
God will redeem you by the spirit of judgment and burning;
it is not ranging abroad in your minds,
but you must know Christ is in you except you be reprobates;
if he has set your eyes and hearts upon himself,
and made you to water your couch with your tears; if he has broken your sleep,
so as you have cried out, '`I shall be damned,
and never come to salvation;`' (this will be your cry,
it was once my cry,) O let not your eyes slumber, nor your eye-lids take any rest,
till you be sure the Lord is your God; if you find these justifications,
you are on your way, otherwise you will be like a deceitful bow,
and never abide in judgment; if you reject the counsel of God against yourselves,
and refuse to be crucified with Christ, and to be baptized with his baptism,
you will never have life; but by his baptism,
and through the heavenly operation of his Spirit, if you have faith in Christ`'s name,
you shall be married to him in everlasting righteousness;
salvation shall be brought to us, and eternal life be bestowed upon us;
even that life which is hid with Christ in God,
he will give to every poor mournful soul that submits to his blessed will,
and believes in the Lord Jesus Christ: this is not a faith of our own making,
nor a garment of our own embroidery, but that which the Lord has given to us.
O happy man or woman, that obtain this gift of God!
O, who will not lose their lives for this everlasting life?
Who will not die for this eternal life?
Now the '`matter lies in the death of your own wills; when you have done the will of God,
then watch that your own wills be slain,
and that your cursed self take not the jewels of God, and his bracelets and ornaments,
and bestow them upon self, and paint and deck cursed self:
and take not the members of Christ, and make them the members of a harlot;
if you be dead to your own wills, you are risen with Christ,
and shall receive a resurrection to eternal life: crucify self,
and set the world at nought, and trample upon it, and all things of it,
and count them as dross and dung in comparison of Christ;
that the Father has revealed to be our life, in the days of our sorrow and mourning,
in the day of our calamity, in the day when w`'e cried our hope is lost.

Thus it has been with the holiest people on earth;
it is not by works of righteousness of your own that you can be saved;
Christ comes to cut all these down, that you may be ingrafted into him,
and justified by his grace.
Do not make this matter of talk, and say, I have heard this and that;
but look into your own hearts, and see what heavenly workings are there;
what there is of the power of the Lord Jesus, that has made you to loathe this world,
and the inordinate love of the creature, that you may enjoy all these things,
as if you enjoyed them not.
We cannot when we are slain and crucified to this world, but say, my life is in Christ,
when we come to ascribe nothing to ourselves, and all to Christ:
here is a blessed harmony, broken hearts, melted spirits, and yet joyful souls;
poor creatures that were mourning and sighing,
and crying before the Lord in retired places, and yet rejoicing in Christ Jesus,
I am risen with Christ, I said, my hope is cut off, I will lie down in your will, O God;
do what you will with me, it is in your sovereign pleasure and free gift,
whether you give me life or deny it to me:
there must be a resignation of ourselves to the will of God;
it was so with the Lord Jesus, and it is so with every true saint of God;
you must be humbled as little children before the judgment be taken away,
and the lovingkindness of God sealed up to your souls; if you seek this work of God,
you will find it; if you seek it upon your beds, in all your labors and concernments,
in all your stations and relations; if you press after the new birth,
you must use this world as if you used it not, and live a married life,
as if you were unmarried, for the fashion of this world passes away.
This is not rantism.

But let me tell you, a new world comes by regeneration;
a man is not lifted up in his own mind, but laid low in his own eyes,
he waits for the wisdom of God to govern him, and he is as a steward of the grace of God,
to give to them that stands in need.
When a man is regenerated and born again, he is as contented with bread and water,
as with all the enjoyments of this world; what is the matter?
His own will is gone, and put down under his feet,
and whatsoever it is that gives life to all his vain desires and affections,
there is a harmony of all within, a man praising of God, and blessing his holy name;
there are no entanglements shall draw away the heart from serving of God,
and seeking his glory; and if God shall call the husband from the wife,
or the wife from the husband, for the glory of his name,
there is no whining and complaining, and crying out, but giving them up,
and a praising and blessing God, when they are called to such an exercise;
and if they are not called to that,
then they set their hearts to glorify God in their several places and stations;
then they have a full content in a blessed resignation.
Here their wills are slain, but they praise God they have no desire,
but Lord your will be done, always praising God,
always having the fear and the glory of God before their eyes.
All the mischief is hatched in pleasing men`'s own wills: that is,
the counsel of every heart that Christ does not govern.
Will you live as the Quakers?
Then you must live contemptibly, the mistress and the maid are hail fellows well met.
No, everyone must walk in humility, and love in acquaintance with the God of heaven;
she that is wrought upon by the same spirit,
must with all diligence behave herself as becomes a servant of the Lord.
Here is now a new world, and the fashions of the old world are gone; all pride,
haughtiness, crossness, and trampling upon one another are all gone,
all slain through the operation of Christ.

What remains now, Christ is in me, and we are all one in him;
Christ laid down his life for you and me; now he reigns in me,
and he has prepared my body to die for the truth,
as his prepared body was laid down for my sin.
It is a kind of foolish profession, to make profession of Christ,
and live in covetousness, profaneness, sensuality, and the like;
they that are come to this heavenly birth, seek the things that are above,
you can do no other; make the tree good, and the fruit will be good.
You must be ingrafted into the vine of God`'s righteousness;
O slight not the day of your visitation.
What was it to me to read of any being born again, till I was slain,
and knew the heavenly baptism of Christ Jesus?
Till I saw the flaming sword ready to slay me in every way, in every turning.
The light of Christ convinced me of sin, and his righteousness justified me,
and those works were abominable to me, that hindered my soul`'s passage to Christ;
Christ Jesus in marrying my soul to himself seized upon me,
and did work effectually in me: there is the testimony of Christ in me,
he has sealed up my soul to the day of my redemption.
Here is a certain passage, and a certain way which never any miss of,
that lose their lives for Christ:
if you be not ready and willing to lose your lives for Christ, you shall never come here;
the gate is straight, and the way is narrow,
none come here but those that die into a heavenly oneness with Christ.
O, friends, let us empty ourselves, that Christ may fill us;
let us be nothing in our own eyes, that we may be all in him, and receive of his fulness,

Now I commend you to God`'s witness, that you may remember what has been spoken among you;
but consider, if you do not hearken to it, it will follow you,
and be a plague to you to all eternity;
if you will not yield up ourselves to Christ this day that burns like an oven,
this fire you must dwell with when out of the body,
there will be no quenching of this fire forever; but if you be so wise for your souls,
as to resign yourselves up to Christ, and come to him as little children,
this will not hinder your earthly concerns, though the world may account you a fool,
yet you have that part of heavenly wisdom to do what you do as unto God:
you carry yourself to your wife, as in the sight of God,
that she may be sanctified to you, and you to her;
and you carry yourself becomingly to your children and servants,
and you will abound in grace, and in every good work,
which will be for yours eternal welfare.

O, I beseech you people, for the Lord`'s sake, wait for the light of Christ to guide you;
learn of him to be meek and lowly, then happy are you; for he dwells with the humble,
but he beholds the proud afar off.
This new birth, which is a true work, a sincere and heavenly work,
it will make you forever.
O make room for Christ in your hearts, or else he is never like to dwell with you;
he loves to dwell with the poor and humble and contrite spirit, he abhors the proud,
he will empty your souls, that he may fill them.

And so I commend you to God.
I have been long held in durance under great weakness; and I was restless,
till I could come up to this great city of London,
to preach the everlasting gospel among you, and you see I am among you here;
pray every one of you turn inward; let not these words, passing through a mean vessel,
be as a bare empty discourse of truth to you, which you only hear,
and take no further care of your salvation.
Take heed of despising the light that shines in the midst of you,
and be pressing forward to the heavenly work that is laid in the power of Christ Jesus,
even through judgment into death, and then he will give eternal life;
the Lord confirm this, that it may rest upon your hearts,
that you may be dead to the things of the world: we are not come to Mount Sinai,
that genders to bondage, but we are come to Mount Zion, the city of the living God,
the heavenly Jerusalem, and to an innumerable company of angels, to the general assembly,
and church of the first-born which are written in heaven, and to God the judge of all,
and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,
that speaks better things than that of Abel.
This is the inheritance of the redeemed of the Most High,
blessed be the name of the Lord; let us rest in hope,
till he bring us to humility and lowness of mind,
that he may clothe us with heavenly glory, according to his promise,
I will beautify my house with glory, says the Lord.
This is the portion of a poor people, that cast down themselves before the Lord,
that he may lift them up, and be all in all to them,
in whose blessed presence they shall have joy,
and rivers of pleasures at his right hand forevermore.

--

His intention was to have been at the yearly meeting of his friends;
but by illness he was prevented; and therefore before he grew worse,
he returned to Warwick, where he lived.
Being come there, his disease increased, and lying very sick in bed,
and being visited by some of his friends, he said to them in great weakness of body,
as follows:

[.embedded-content-document.testimony]
--

My God has yet put it in my heart to bear a testimony to his name and blessed truth,
and I can never forget the day of his great power and blessed appearance,
when he first sent me to preach the everlasting gospel,
and proclaim the day of the Lord to all people.
Therefore, friends, be faithful, and trust to the Lord your God; for this I can say,
I never since played the coward, but as joyfully entered prisons as palaces,
and in the prison-house I sang praises to my God,
and esteemed the bolts and locks upon me as jewels.
And, friends, this I must once again testify to you, in the name of the Lord God,
that what I saw above thirty years ago, still rests as a testimony to leave behind me,
that a dreadful terrible day is at hand, and will certainly come to pass;
but the time when, I cannot say; but all put on strength in the name of the Lord,
and wait to feel his eternal power,
to preserve you through the tribulations of those days that approach very near.
This I have further to signify, that my departure draws nigh.
Blessed be my God, I am prepared, and I have nothing to do but die,
and put off this corruptible and mortal tabernacle,
this flesh that bath so many infirmities; but the life that dwells in it,
ascends out of the reach of death, hell, and the grave;
and immortality and eternal life is my crown forever.
Therefore you that are left behind, fear not, nor be discouraged,
but go on in the name and power of the Lord,
and bear a faithful and living testimony for him in your day.
And the Lord will prosper his work in your hand,
and cause his truth to flourish and spread abroad.
For it shall have the victory, and no weapon formed against it shall prosper.

--

Thus fervent in spirit was W. Dewsbury in his latter end,
and he prayed to God very earnestly for all his friends,
especially those that were met at the annual assembly at London.
And so he very piously departed this life at his house, in a good old age,
in the month called June, in this current year.
He was indeed a man of a remarkable zeal and perception.
He spoke sometimes to young lads as to men,
telling them that the blessing of the Lord would
rest upon them if they lived a godly life:
some of which being since come to man`'s estate,
have experienced the truth of his saying.

Two days before the decease of William Dewsbury,
Rebecca Travers departed this life at about the age of seventy-nine years.
She was a woman exceedingly well gifted;
and spoke not only sometimes in public for edification of the church,
but wrote also several books for the advancement of piety; in one of which she signified,
that though she had been a reader of the Scriptures from a child of six years old;
yet when by the power of the eternal gospel she was turned from darkness to light,
the Scriptures then became much more plain to her, as not lacking interpretation.
She was an excellent open-hearted woman, and took great care of the poor:
she had several times been imprisoned for religion,
but persevered constantly in the faith, and so piously entered into eternal rest.

As to state affairs, there now appeared a wonderful agitation in England,
since it was reported that the queen was big with child.
And the endeavors for introducing popery,
besides the encroaching upon some rights and privileges, caused such a stir,
that William the third, prince of Orange, and stadholder, (or lord deputy,) of Holland,
etc. was in-treated and invited by the English Protestants, to come to their assistance.
This at length he did, and came over with a fleet, and a considerable number of forces.
What was the issue of this expedition, is very amply described by other pens,
and not properly my province to relate;
wherefore I think it sufficient to my purpose to say,
that the prince after some difficulty at sea, came into England;
where having many adherents, the king, many of whose forces deserted him,
resolved to go to France, where the queen with the young child was gone sometime before.
Accordingly he went over, where he was well received by the French king,
who provided him a court at St. Germain`'s. In the
meanwhile the prince of Orange came to London,
and was saluted there by the great ones as the deliverer of England.
The lord mayor of the said city, with the aldermen and the sheriffs,
having congratulated him,
the prince sent for some of the members of former parliaments to come to him,
and signified to them that he had desired them to meet to advise him in the best
manner how to pursue the ends of his declaration in calling a free parliament,
for the preservation of the Protestant religion,
the restoring of the rights and liberties of the kingdom, and settling the same,
that they might not be in danger of being again subverted.

In answer to this,
thanks were given to the prince for his care and pains in defense of the people,
their religion, and laws.
And all things took a favorable turn for him.

In Holland a good while before a paper was published in print, called,
'`A Copy of a Letter written by a Quaker at London to his Friend at Rotterdam.`'
In which forged letter were mentioned several things that were not altogether untrue,
and the prince`'s going over to England, was also in a manner predicted.
Who was the author of the said letter, I could never learn,
but of this I am fully satisfied, that he was no Quaker;
for it never was their way to ridicule princes,
and to characterize them with ridiculous denominations,
as in the said letter we find mentioned, of James of Great Britain, Mary of Modena,
William of Orange, and Mary of England, his wife.
This was no more the language of Quakers,
than the following expressions that are found in this letter.
'`The Spirit has inspired me to tell you, I should not be able to declare my opinion,
before the Spirit shall have revealed it to me.
If the Spirit does dictate it to you, go and speak with him.
Dentsch has had a revelation, and the Spirit has assured him,`' etc.
This foolish language betrays itself, and serves for a palpable evidence,
that it never proceeded from the pen of any of the people called Quakers.
But perhaps the author of that letter knew a secret of state, whereof,
(to remain unknown,) he would acquaint the world in a ridiculous way;
that under the cloak of being a Quaker, he should best continue undiscovered,
and that by this device the letter would spread the more, as indeed it did;
for it had a very quick vent.
