== Chapter XXII.

=== 1689-1694.

[.chapter-synopsis]
* Revolution in England
* Parliament confirms liberty of conscience
* Friends`' declaration of fidelity
* Friends in Barbados relieved
* Death of R. Barclay
* Epistle of S. Crisp to all the churches of Christ
* Sickness and death of G. Fox
* Character of G. Fox
* Epistle of G. Fox to all the children of God everywhere
* Apostacy of G. Keith
* G. Keith`'s misrepresentations of the principles of Friends
* Declaration of the Christian doctrine of the Quakers
* Francis Bugg
* Petition to Parliament for an Affirmation instead of an Oath
* State of the case by T. Ecclestone
* Death of Queen Mary

I proceed now to the year 1689, in the beginning of which the peers of the realm,
etc. offered the administration of the government to the prince of Orange,
which he accepted of.
Not long after he-called a convention of the commons;
for a parliament it could not be named,
since in England none but a king has power to call a parliament.
In the meanwhile the prince had caused the princess his consort,
to come over from Holland, into England;
and at length the convention after many great debates, came to this resolution,
that the throne was vacant; the consequence of which was,
that the prince and princess of Orange were declared by the names of William the third,
and Mary the second, king and queen of England,
etc. and according were afterwards crowned.
A large relation thereof is to be found in several books.
By the way I will only say, that the coronation was performed by the bishop of London,
the archbishop of Canterbury having refused to act in that solemnity;
at the performance of which the king and queen were asked by the bishop,
'`Will you solemnly promise and swear to govern the people of this kingdom of England,
and the dominions thereto belonging, according to the statutes in parliament agreed to,
and the laws and customs of the same?`'
To which the king and queen having answered,
'`I solemnly promise so to do;`' the bishop asked,
'`Will you to your power cause law in justice and mercy to be executed in all your judgments?`'
Answer was made, '`I will.`'
The next question was, '`Will you to the utmost of your power maintain the law of God,
the true profession of the gospel,
and the Protestant Reformed religion established by law?
And will you preserve unto the bishops and clergy of this realm,
and to the churches committed to their charge,
all such rights and privileges as by law do or shall appertain to them, or any of them?`'
To which the king and queen answered, '`All this I promise to do.`'
After this they laying each of them their hands upon the book of the gospel, said,
'`These things which I have here before promised, I will perform and keep.
So help me God.`'
Under these punctual and nice questions was more hidden than some would think.
For the king having answered so as has been said,
could not now free any from paying tithes to the clergy, without violation of his oath.

Not long after William and Mary were thus made king and queen of England,
they were also in Scotland declared king and queen of Scotland.
Not long after this a war was proclaimed against France, and the late king, James,
supported by the French king, went over to Ireland,
from where in process of time he was driven away by king William,
after the bloody battle near the river Boyne; but that not belonging to this history,
I will not detain my reader with a relation thereof.

A king having now mounted the throne, the convention was turned into a parliament;
and then this august assembly made it their business to restrain the forcing of conscience;
and an act passed for exempting Protestant dissenters from the penal laws,
by which some dissenters, and especially the Quakers,
had suffered and been persecuted many years.
Yet care was taken to keep that law in force by which
Catholics were excluded from sitting in parliament.
And those penal laws, of which mention has been made heretofore in due place,
were now restrained, except the test act, properly required for serving in high offices,
and to keep out the Catholics.
The aforesaid act gave also liberty to dissenters to keep religious meetings,
provided the doors were not locked, barred or bolted, during the time of such meeting.
But none of these dissenters were freed from paying tithes, or other church duties,
so called, to the clergy, nor from being cited before bishops`' courts.
But this liberty of keeping public meetings was not allowed to Catholics;
for all that would participate of the said liberty,
were required to take the oath of allegiance;
yet to comply with the people called Quakers,
who for conscience-sake scrupled to take any oath,
this act enjoined that they should subscribe the following declaration:

[.embedded-content-document.legal]
--

I, _A. B._ do sincerely promise and solemnly declare, before God and the world,
that I will be true and faithful to king William and queen Mary;
and I do solemnly profess and declare, that I do from my heart abhor,
detest and renounce, as impious and heretical, that damnable doctrine and position,
that princes excommunicated or deprived by the Pope, or any authority of the see of Rome,
may be deposed or murdered by their subjects, or any other whatsoever.
And I declare that no foreign prince, person, prelate, state, or potentate, has,
or ought to have any power, jurisdiction, superiority, preeminence, or authority,
ecclesiastical or spiritual, within this realm.

--

Besides this they were obliged to subscribe also another,
with respect to their orthodoxy, and for excluding Socinianism.

[.embedded-content-document.legal]
--

I, _A. B._ profess faith in God the Father, and in Jesus Christ his eternal Son,
the true God, and in the holy Spirit, one God, blessed forevermore:
and do acknowledge the holy Scriptures of the Old
and New Testament to be given by divine inspiration.

--

And lest any Roman Catholic might make use of this declaration,
there were required sufficient Protestant witnesses that the declarer was a Protestant dissenter.
Besides no congregation or assembly for religious
worship was permitted or allowed by this act,
until the place of such meeting should be certified to the bishop of the diocese,
or to the archdeacon of the archdeaconry;
or to the justices of the peace at the general or
quarter-sessions of the peace for the county,
city, or place, in which such meeting should be held,
and registered in the said bishop`'s or archdeacon`'s court respectively,
or recorded at the said general or quarter-sessions:
for which the register or clerk should not take greater fee or reward than sixpence.

By this we now see the religion of the Quakers acknowledged
and tolerated by an act of parliament;
and themselves released from all persecution for performance of their public worship,
and their refusal of the oath of allegiance.
This was a work reserved for that great prince king William,
who being born in a country where force upon conscience was abrogated,
when a Protestant government was settled there,
now also according to his ability introduced the like Christian liberty in England:
but to release from the payment of tithes was beyond his reach,
how unreasonably soever the clergy acted in this case;
whereof about this time a notable instance was published in print, of one John Bishop,
a countryman at Wortham, from whom for two years tithes-there had been taken, horses,
kine, and sheep, to the value of about seventy-six pounds,
according to the estimate of impartial persons,
though rated by himself at eighty-three pounds.
And yet the priest, Thomas Thurlow, had declared upon his oath,
that he believed that the tithes of every year`'s growth of the said Bishop,
did amount one year with another, to three pounds seventeen shillings and sixpence;
but the charges were reckoned so high,
and the rating of the distrained goods was so very much beneath the real value,
that the loss thereby sustained was exceeding great.

In Barbados, in the West Indies, where the inhabitants were marshalled to bear arms,
the Quakers, notwithstanding what had been ordered in their favor by king James,
continued yet under hard sufferings, of which more in the sequel.
They now that were thus oppressed, sent over a petition to the king,
wherein they set forth how they were molested, and prayed for relief;
which had such effect, that the king issued forth the following order:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
At the Council at Whitehall, Dec.
12, 1689.

Present the king`'s most excellent majesty in council.

Upon reading a petition of the people called Quakers, inhabiting the island of Barbados,
setting forth, that because the said Quakers could not bear arms,
nor take an oath in any case,
they have suffered much by virtue of an act made to settle the militia in the said island;
as in the petition hereunto annexed, is more at large expressed;
his majesty in council is graciously pleased to refer the matter
of the said petition to the examination of James Kendal,
esq.
his majesty`'s governor of Barbados for the time being,
who is to give the petitioners such relief in relation to the militia,
as to him shall seem just and reasonable to answer their particular circumstances,
and to make report thereof to his majesty.

[.signed-section-signature]
Richard Collinge.

--

This year deceased Alexander Parker, sometimes mentioned in this history,
being a man not only of a godly life and conduct,
but also of a godly mien and grave deportment.
In the following year, 1690, Robert Barclay also departed this life,
a man of eminent gifts and great endowments,
expert not only in the languages of the learned,
but also well versed in the writings of the ancient fathers,
and other ecclesiastical writers, and furnished with a great understanding,
being not only of a sound judgment, but also strong in arguments,
and cheerful in sufferings.
Besides, he was of a friendly and pleasant, yet grave conduct,
and eminently fitted for composing of differences;
and he really lived up to what he professed, being of an unblameable deportment,
truly pious, and well beloved of those he conversed with.
And in this happy state it pleased God to take him away out of this vale of tears,
into a glorious immortality, in the prime of his age,
having not lived much above half the life of a man, as it is commonly accounted, that is,
in his 42nd year, on the third of October, at his house at Ury, in Scotland,
where he died of a sickness, which did not last long,
yet he signified with a good understanding, that it was well with him as to his soul.

This year Stephen Crisp wrote an epistle of tender love and brotherly
advice to all the churches of Christ throughout the world,
in which he exhorted them more particularly to charity;
and since therein several remarkable duties are held forth and recommended,
I cannot well omit to insert a copy of it here, which is as follows:

[.embedded-content-document.epistle]
--

Dearly beloved friends and brethren,
gathered out of the world by the eternal arm and power of the mighty God,
to bear his holy name in your generation;
my love and life in the fellowship of the universal spirit salutes you all,
and my prayer to God is, you may be kept steadfast and immoveable in the grace of God,
and in the communion of his holy Spirit, that you may bring forth fruit in abundance,
according to the abundant mercy and grace bestowed upon you, to the glory of God,
and to your mutual joy, comfort, and edification.

And that you may so do, let your eye be kept daily to the Lord,
and behold and lake notice of the wondrous works that he has wrought in you, and for you,
since the day you were first quickened by his immortal word,
and stirred up to seek after him, and to wait upon him:
how good and gracious he has been to you, in bringing you from the barren mountains,
where your souls languished for the heavenly nourishment; where you knew not the Lord,
nor one another, but were without a comforter,
or any to sympathize with you in your mournings; Oh, how has he pitied your groanings,
and had compassion on your sighings,
and brought you into acquaintance with those that were in the like exercises;
and then he taught you to believe on him that was able to help you:
and those that were thus taught of the Father,
and felt his drawing cords of love prevailing upon them;
these came to Christ their Savior, and in him began to feel a unity one with another,
in the faith you had received in him;
whereby you believed he would give you of his spirit
to teach and guide you in the way of truth,
righteousness, and peace; and thus was the foundation of your holy communion laid,
and a lively hope raised in each particular soul,
that he that had begun this blessed work would carry it on;
and this hope made you that were not ashamed to make
a public profession of his name before the world;
but cheerfully to take up his cross, and deny yourselves of your former pleasures,
friendships, and delights of this world:
this hope has been your support in many sharp trials,
and bitter combats you have had with the enemy of your souls`' peace within,
and with the enemies of God`'s holy way and truth without;
and in all your conflicts you have found him nigh at hand,
to put forth his power on your behalf, as you have depended upon him for assistance;
and by these experiences of his goodness, your faith has been strengthened;
and by the same word of life that quickened you, many more have been reached unto,
so that you have seen a daily addition of strength in the particular,
and also an addition to your number, to your great comfort and encouragement;
and many have come to wait upon the Lord among you;
and many are daily inquiring the way to Zion, with their faces thitherward.
These things are worth your remembrance and serious considerations,
that you may look upon these great mercies as obligations upon your souls,
to walk humbly before the Lord, and to be devout and fervent in your testimony,
for that God that has done thus great things for you.

And, friends,
consider of the great works that this mighty arm
of the Lord has brought to pass in the general,
as well as in the particular; how many contrivances have been framed,
and laws and decrees made to lay you waste, and to make you cease to be a people,
and how have the wicked rejoiced thereat, for a season, crying, '`Ah,
ah! thus would we have it; they are all now given up to banishments, to imprisonments,
to spoils and ruins;
now let us see if that invisible arm they trust in can deliver them.`'
Oh friends! how has your God been your support in the midst
of all these exercises! and when he has pleased,
how he has quieted the sharpest storms,
and turned back the greatest floods and torrents of persecution
that ever you met! and how has he confounded his and your enemies,
and brought confusion upon the heads of them that sought your hurt!
Were not these things wrought by the power of God.
Did you number, your policy, your interest, or any thing that might be called your own,
contribute any thing to these your great preservation and deliverance?
If not, then let God have the glory, and acknowledge, to his praise,
these have been the Lord`'s doings, and are marvelous in our eyes.

Again, dear friends,
consider how the wicked one has wrought in a mystery among yourselves, to scatter you,
and to lay you waste from being a people as at this day;
how many several ways has he tried, raising up men of perverse minds,
to subvert and to turn you from the faith,
and from the simplicity that is in Christ Jesus our Lord;
and to separate you from that invisible power that has been your strength,
and to separate you one from another,
and by subtle wiles to lead you into a false liberty above the cross of Christ;
and sometimes by sowing seeds of heresy and seditions,
endeavoring to corrupt the minds of whom they could with pernicious principles; but oh,
how have their designs been frustrated,
and the authors thereof confounded and brought to nought:
and how have you been preserved as a flock under the hand of a careful shepherd,
even unto this day, which ministers great cause of thanksgiving unto all the faithful,
who have witnessed the working of this preserving power in their own particulars.

Also, my friends, it is worth your considerations,
to behold how that by this invisible power so many faithful
watchmen are raised up upon the walls of your Zion;
that in most of your meetings there be men and women,
upon whom God has laid a concern to be taking care for the good of the whole;
and to take the oversight upon them, to see all things kept in good and decent order,
and to make due provision for the comforting and
relieving the necessities of the needy and distressed;
that nothing be lacking to make your way comfortable; and these have not been,
nor are brought under this charge by any act of yours,
but God has raised up pastors and teachers,
elders and deacons of his own election and choice,
and bowed their spirits to take upon them the work and service to which they are appointed,
for the Lord`'s sake, and for the body`'s sake, which is the church;
to whom it may truly be said, as in Acts 20:28. "`Take you heed to the flock of God,
over which the Holy Ghost has made you overseers,`" etc.
And such ought to be hearkened to in the discharge of their trust,
as those that must give an account to him that called them,
and gifted them for their several works and services in the church.

And by these ways and means has the Lord established among you a heavenly government,
and built as it were a hedge about you,
that you may be preserved from generation to generation,
a people fitted for the glory that is,
and shall daily more and more be revealed among and upon the faithful,
who delight in that power that called them to be saints,
and to bear a profession for the holy name of God,
against the many names and ways that men in their changeable minds have set up,
that the name of the Lord alone may be exalted.

And, dear friends and brethren, I entreat you,
that the consideration of these great and weighty things which God has wrought for you,
and among you, may have that deep and weighty influence upon your souls,
that you may find yourselves engaged to answer the
love and mercy of God in your lives and conducts,
and in all you have to do in this world;
that you may show forth the honor of God in all things,
that the light which has shined in you, may shine forth through you unto others,
who yet sit in darkness; that all men may know by your innocent and harmless conducts,
and by your close keeping to the Lord,
that you are a people who are assisted and helped by a supernatural power,
which governs your wills, and subjects them to his blessed will;
and that guides and orders your affections,
and sets them upon heavenly and divine objects,
and that gives you power to deny your own private interests,
where they happen to stand in competition with the interest of truth; for these,
and these only, will be found the true disciples of our Lord Jesus Christ,
who can deny themselves, take up a cross daily,
and follow him in the guidance of his regenerating power; which brings death upon itself,
and crucifies the old nature, with its affections and lusts,
and raises up a birth in you, that has a holy will and desire to serve the Lord,
and do his will in the earth;
and such as these are instruments in the hand of God for him to work by,
and to do works of righteousness, of justice, of charity,
and all others the virtues belonging to a Christian life, to the honor of God,
and for the comfort and benefit of his church and people.

And all you, dear friends, upon whom the Lord has laid a care for his honor,
and for the prosperity of the truth; and gathered you into the good order of the gospel,
to meet together to manage the affairs thereof;
take heed that you have a single eye to the Lord,
to do the Lord`'s business in the leadings of his Spirit, which is but one,
and brings all that are given up to be governed by it, to be of one mind and heart,
at least in the general purpose and service of those meetings;
although through the diversity of exercises,
and the several degrees of growth among the brethren,
every one may not see or understand alike in every matter,
at the first propounding of it; yet this makes no breach of the unity,
nor hinders the brotherly-kindness,
but puts you often upon an exercise and an inward travailing,
to feel the pure peaceful wisdom that is from above to open among you;
and every one`'s ear is open to it, in whomsoever it speaks,
and thereby a sense of life is given to the meeting,
to which all that are of a simple and tender mind join and agree;
but if any among you should be contrary minded in the management of some outward affair,
relating to the truth, this does not presently break the unity that you have in Christ;
nor should weaken the brotherly love,
so long as he keeps waiting for an understanding from God,
to be gathered into the same sense with you, and walks with you,
according to the law of charity.
Such a one ought to be borne with and cherished,
and the supplications of your souls will go up to God for him,
that God may reveal it to him if it be his will;
that no difference may be in understanding,
so far as is necessary for the good of the church,
no more than there is in matters of faith and obedience to God; for, my friends,
it is not of absolute necessity that every member of the church
should have the same measure of understanding in all things;
for then where were the duty of the strong bearing with the weak?
Then where were the brother of low degree?
Where would be any submitting to them that are set over others in the Lord;
which all tend to the preserving unity in the church,
notwithstanding the different measures and different growths of the members thereof;
for as the spirits of the prophets are subject to the prophets;
so are the spirits of all that are kept in a true
subjection to the spirit of life in themselves,
kept in the same subjection to the sense of life given by the same spirit in the church;
and by this means we come to know the one master, even Christ,
and have no room for other masters in the matter of our obedience to God:
and while everyone keeps in this true subjection, the sweet concord is known,
and the oil is not only upon Aaron`'s head, but it reaches the skirts of his garment also;
and things are kept sweet and savory,
and you love one another from the greatest to the least in sincerity, and,
as the apostle says, without dissimulation;
and this love excludes all whisperings of evil things; all backbiting, talebearing,
grudging, and murmuring; and keeps friends`' minds clean one towards another,
waiting for every opportunity to do each other good,
and to preserve each other`'s reputation;
and their hearts are comforted at the sight of one another; and in all their affairs,
both relating to the church and to the world,
they will be watchful over their own spirits, and keep in the Lord`'s power,
over that nature and ground in themselves that would be apt to take an offense,
or construe any word or action to a worse sense than the simplicity thereof,
or the intention of the other concerned will allow of.

And whereas it may often fall out, that among a great many,
some may have a different apprehension of a matter from the rest of their brethren,
especially in outward or temporal things;
there ought to be a Christian liberty maintained
for such to express their sense with freedom of mind,
or else they will go away burdened; whereas if they speak their minds freely,
and a friendly and Christian conference be admitted thereupon, they may be eased,
and oftentimes the different apprehension of such a one comes to be wholly removed,
and his understanding opened, to see as the rest see;
for the danger in society does not lie so much in that,
that some few may have a differing apprehension in some things from the general sense,
as it does in this, namely, when such that so differ,
do allow themselves to be led out of the bond of charity,
and shall labor to impose their private sense upon the rest of their brethren,
and to be offended and angry if it be not received;
this is the seed of sedition and strife that has grown up in too many,
to their own hurt.

And, therefore, my dear friends, beware of it,
and seek not to drive a matter on in fierceness or in anger,
nor to take offense into your minds at any time, because what seems to be clear to you,
is not presently received;
but let all things in the church be propounded with an awful
reverence for him that is the head and life of it;
who has said, "`Where two or three are met in my name, I will be in the midst of them.`"
And so he is, and may be felt by all who keep in his spirit;
but he that follows his own spirit, sees nothing as he ought to see it.
Therefore let all beware of their own spirits and natural tempers,
as they are sometimes called, but let all keep in a gracious temper;
then are you fit for the service of the house of God, whose house you are,
as you keep upon the foundation that God has laid; and he will build you up,
and teach you how to build up one another in him,
and as every member must feel life in themselves, and all from one head;
this life will not hurt itself in any, but be tender of the life in all;
for by this one life of the word you were begotten, and by it you are nourished,
and made to grow into your several services in the church of God.
It is no man`'s learning, nor artificial acquirements; it is no man`'s riches,
nor greatness in this world; it is no man`'s eloquence and natural wisdom,
that makes him fit for government in the church of Christ; unless he,
with all his endowments, be seasoned with the heavenly salt, and his spirit subjected,
and his gifts pass through the fire of God`'s altar, a sacrifice to his praise and honor;
that so self be crucified and baptized in death,
and the gifts made use of in the power of the resurrection of the life of Jesus in him;
and when this great work is wrought in a man,
then all his gifts and qualifications are sanctified,
and they are made use of for the good of the body, which is the church;
and are as ornaments and jewels,
which serve for the joy and comfort of all who are partakers of
the same divine fellowship of life in Christ Jesus our Lord;
and thus come many to be fitted and furnished to good works,
which are brought forth in their due seasons, for edification and building up the weak,
and for repairing the decayed places, and also for defence of them that are feeble,
that hurtful things may not come near them.

Oh friends! great is the work the Lord has called you to, and is fitting you for,
who innocently wait upon him; and the Lord has opened my heart unto you,
and laid it upon me to exhort and beseech you to
have a care that you quit yourselves as you ought,
in what God requires of you;
and for the more particular expressing what lies before me in the matter,
I shall set down a few particular observations for your benefit and advantage;
and my soul`'s desire is, that my labor of love may have a good effect in all your bosoms,
that God may be honored thereby.
And, friends, you know the chief business,
to which you are called in your particular men and women`'s meetings,
is under these two heads, justice and charity; the first,
to see that every one has right done him; and the other,
to take care there be nothing lacking to the comfort of the poor,
that are made partakers of the same faith with you.

And when you meet about these things, keep the Lord in your eye,
and wait to feel his power to guide and direct you,
to speak and behave yourselves in the church of God, as becomes the peaceable gospel:
and beware of all brittleness of spirit, and sharp reflections upon each other`'s words;
for that will kindle up heats, and create a false fire;
and when one takes liberty of a sharp word spoken out of the true fear and tenderness,
it oftentimes becomes a temptation to another; and if he has not a great care,
it will draw him out also, and then the first is guilty of two evils, first,
being led into a temptation, and then secondly, he becomes a tempter to others;
therefore all had need be upon their watch, neither to tempt, nor be tempted;
and let none think it a sufficient excuse for them that they were provoked;
for we are as answerable to God for every evil word spoken upon provocation,
as without provocation; for, for that end has the Lord revealed his power to us,
to keep and preserve us in his fear and counsel in the time of our provocations;
and therefore if any man through lack of watchfulness,
should be overtaken with heat or passion, a soft answer appeases wrath,
says the wise man; and therefore such a time is fittest for a soft answer,
lest the enemy prevail on any to their hurt,
and to the grief and trouble of their brethren;
for it is the proper duty of watchmen and overseers to spare the flock; that is,
let nothing come nigh them that will hurt them, and wound and grieve them; no,
the good apostle was so careful over the flock of believers,
that if there were any doubtful matters to be disputed of,
he would not have them that were weak in the faith at such disputes;
much less ought they that are weak, to see those that are strong,
descend from their strength, and go into the weakness where they are not able to bear;
for that is certainly the weak that cannot bear;
those that really live in the strength and power,
they can bear even burdens for them that cannot bear their own.
The apostle in the place before-mentioned,
when he sent for the elders of Ephesus to Miletus, and left a charge with them,
before he said, take heed to the flock of God, he said, "`Take you heed to yourselves.`"
And indeed we are none of us like to discharge ourselves well towards others,
but by taking heed to ourselves, to be kept in that sober innocent frame of spirit,
which the truth calls for.

In the next place, my dear friends, when you are called upon in point of justice,
to give a sentence of right between friend and friend,
take heed that neither party get possession of your spirit afore hand,
by any way or means whatsoever,
or obtain any word or sentence from you in the absence of the other party,
he not being yet heard: there is nothing more comely among men than impartial judgment;
judgment is a seat where neither interest, nor affection, nor former kindness may come;
we may make no difference of the worthiness or unworthiness of persons in judgment,
as we may in charity; but in judgment, if a good man, being mistaken, has a bad cause,
or a bad man a good cause, according to his cause must he have sentence.
It was a good saying, he that judges among men, judges for the Lord, and he will repay it.
Therefore let all be done as unto the Lord,
and as you are willing to answer it in his presence;
and although some may for a time be discontent thereat,
yet in time God shall clear up your innocence as the sun at noon-day;
and they that kick at sound judgment will find but hard work of it;
they do but kick against that which will prick them;
and however such through their willfulness,
and their abounding in their own sense may hurt themselves, yet you will be preserved,
and enjoy your peace and satisfaction in the discharge
of your consciences in the sight of God.

And as concerning practical charity, you know it is supported by liberality,
and where liberality ceases, charity waxes cold, yes, so far ceases;
where there is no contribution, there is no distribution; where the one is sparing,
the other is sparing; and therefore let every one nourish charity in the root, that is,
keep a liberal mind: a heart that looks upon the substance that is given him,
as really bestowed upon him for the support of charity,
as for the support of his own body: and where people are of this mind,
they will have a care of keeping back any of God`'s part, for he has in all ages,
in a most singular manner, espoused the cause of the poor, the widow, and fatherless;
and has often signified by his prophets and ministers,
a special charge upon rich men that had this world`'s goods,
that they should look to it that they were faithful stewards of what they possessed,
and that they might be found in good works,
and might not allow their hearts so to cleave to uncertain riches,
as to neglect the service God had given them the things of this life for:
either to give them up when called for in a testimony of his worthy name,
or to communicate of them to those that were in necessity.

Now as concerning the necessities of the poof,
there is great need of wisdom when you meet together about that affair:
for as I said before,
though the worthiness or unworthiness of persons is not to be considered in judgment,
yet in this it is; and you will find some that God has made poor,
and some that have made themselves poor, and some that others have made poor,
which must all have their several considerations;
in which you ought to labor to be unanimous,
and not one to be taken up with an affection to one person more than another;
but everyone to love everyone in the universal spirit,
and then to deal out that love in the outward manifestations thereof,
according to the measure, that the Lord in his wisdom working in you,
shall measure forth to them.

And as to those who by sickness, lameness, age, or other impotency,
are brought into poverty by the hand of Providence;
these are your peculiar care and objects pointed out to you, to bestow your charity upon,
for by them the Lord calls for it; for as the earth is the Lord`'s, and the fulness of it,
he has by his sovereign power commanded in every dispensation,
that a part of what we enjoy from him, should be thus employed.
The Israelites were not to reap the corners of their fields,
nor to gather the gleanings of the corn nor vintage; it was for the poor;
and in the time of the gospel, they were to lay apart on the First day of the week,
a part of what God had blessed them with, for the relief of those that were in necessity;
no, they did not confine themselves in their charity to their own meetings,
but had a universal eye through the whole church of Christ,
and upon extraordinary occasions,
sent their benevolence to relieve the saints at Jerusalem in a time of need;
and all that keep in the guidance of the same universal Spirit,
will make it their business to be found in the same practice of charity and good works.
To do good, and communicate, forget not, says the apostle:
so they that forget not this Christian duty will find out the poor`'s part in
the corners and gleanings of the profits of their trades and merchandisings,
as well as the old Israelite did the corners and gleanings of his field;
and in the distribution of it, will have a regard to comfort the bowels of such,
who are by the divine providence of God,
put out of a capacity of enjoying those outward comforts of health,
and strength and plenty, which others do enjoy;
for while they are partakers of the same faith,
and walk in the way of righteousness with you,
submitting themselves patiently to the dispensation of God`'s providence towards them,
they are of your household, and under your care, both to visit and to relieve,
as members of one body, of which Christ Jesus is head; and he that gives to such poor,
lends to the Lord, and he will repay it.

But there is another sort of poor,
who make themselves poor through their sloth and carelessness,
and sometimes by their willfulness, being heady and high-minded,
and taking things in hand that are more than they can manage,
and making a flourish for a season, and then, through their own neglects,
are plunged down into great poverty.
These are a sort the primitive churches began to
be troubled withal in the early days of the gospel;
for the apostle took notice of some-that would not work at all,
and sharply reproved them, and said, they that would not work should not eat;
and these are commonly a sort of busy-bodies, and meddlers with others`' matters,
while they neglect their own, and run into a worse way than the unbelievers,
while they profess to be believers,
yet do not take a due care for those of their own household.

The charity that is proper to such, is to give them admonition and reproof,
and to convince them of their sloth and negligence; and if they submit to your reproof,
and are willing to amend,
then care ought to be taken to help them into a way and means to support themselves;
and sometimes by a little help of this kind,
some have been reclaimed from the snares of their souls`' enemy:
but if they will not receive your wholesome counsel and admonitions, but kick against it,
either in their words or actions, friends will be clear of such in the sight of God;
for it is unreasonable to feed them that will not be ruled by you,
they break the obligation of society by their disorderly walking;
for our communion does not stand only in frequenting meetings,
and hearing truth preached, but in answering the blessed principle of truth,
in life and conduct,
and therein both the rich and the poor have fellowship one with another.

There are another sort that are made poor by the oppressions and cruelties of others.
These oppressed poor cry loud in the ears of the Almighty,
and he will in his own time avenge their cause;
but in the meantime there is a tenderness to be extended to them,
not knowing how soon it may be our turn; and if there be need of council and advice,
or if any applications can be made to any that are able to deliver them from the oppressors;
in such cases let all that are capable be ready and willing to advise, relieve,
and help the distressed; and this is an acceptable work of charity,
and a great comfort to such in their sharp afflictions,
and their souls will bless the instruments of their ease and comfort.

And my dear friends, as God has honored you with so high and holy a calling,
to be his servants and workmen in this his great and notable day,
and to work together in his power, in setting forth his praise and glory in the earth,
and gathering together in one the scattered seed in this and other nations; oh,
let the dignity of your calling provoke and encourage you to be
diligent attenders upon this work and service you are called to,
and let not your concerns in the world draw you from observing
the times and seasons appointed to meet together;
but you that are elder, set a good example to the younger sort,
by a due observation of the hour appointed, that they that come first one time,
may not by their long staying for others be discouraged,
so as perhaps they may be last another time; but when the time is come,
leave your business for the Lord`'s work,
and he will take care your business shall not suffer, but will add a blessing upon it,
which will do more for you than the time can do that might be saved out of his service.

And when you have to do with perverse, and froward, or disorderly persons,
whom you have occasion to reprove, and to rebuke for the truth`'s sake,
and you find them stout and high, and reflecting upon you;
then is a time for the Lamb`'s meekness to shine forth,
and for you to feel your authority in the name of Christ, to deal with such a one,
and to wait for the pure and peaceable wisdom from above,
to bring down and confound the earthly wisdom.
And in this frame of mind you labor together to pull
the entangled sheep out of the thicket,
and to restore that which is gone astray, to the fold again, if you can;
but if you cannot, yet you save yourselves from the guilt of his blood;
and if such do perish, his blood will be on his own head: but on the other hand,
if you allow their perverse spirits to enter,
and their provocations to have a place in you,
so as to kindle your spirits into a heat of passion, then you get a hurt,
and are incapable to do them any good;
but words will break out that will need repentance,
and the wicked will be stiffened and strengthened thereby,
and you miss the service that you did really intend.
Therefore, dearly beloved, keep upon your watch, keep on your spiritual armor;
keep your feet shod with the preparation of the gospel of peace,
and the God of peace will be with you, and crown your endeavors with good success,
to your joy and comfort,
and will bring up his power over your adversaries and opposers more and more,
to which many shall bow and bend in your sight;
and will bring shame and confusion upon the rebellious,
who harden their hearts and stiffen their necks against the Lord, and his Christ,
and kingdom; which he will exalt in the earth, notwithstanding all that Satan,
and all his evil instruments can do to hinder the
growth and progress of his blessed truth;
for of the increase of the government, and of the peace of the kingdom of Christ,
there shall be no end.

And now, friends, I have cleared my conscience of what lay upon me for some time,
to write by way of remembrance, and as the exhortation of my life unto you,
I remain travailing in spirit for the welfare of Zion:
and although the outward man decays, yet in the inward man I am comforted,
in beholding daily the great things that our God has done,
and is still doing for those that have their sole dependance upon him.
So committing you to the grace of God, for your director and preserver,
in these and all your several services unto which God has called you,
that by the operations of his mighty power you may
be kept blameless and unspotted of the world,
to his honor and your comfort,
and to the universal comfort and edification of the church,
that so praises and thanksgivings may fill your hearts and mouths, your families,
and your meetings; for he is worthy who is our tower, our support, the Lord of hosts,
the King of saints, to whom be glory, honor and renown, through this and all generations,
forever and ever.
Amen,

From your friend and brother,
in the communion and fellowship of the gospel of peace and purity,

[.signed-section-signature]
Stephen Crisp.

[.signed-section-context-close]
London, the 15th of the 7th month, 1690.

--

Passing now by other matters of the year, we step to the next, being that of 1691,
about the beginning of which G. Fox departed this life,
who even in the last period thereof wrote much, and continued laborious without fainting.
The last epistle I find of his, was to his friends and brethren in Ireland, who,
because of the revolution and troubles there, suffered much, chiefly, as I think,
by the Catholics;
and therefore in the said epistle he exhorted his friends to steadfastness.
This was in the month called January; and the next day, being the first of the week,
and the 11th of the said month, he went to the meeting at Grace-church-street,
where he preached very effectually,
treating of many things with great power and clearness; and concluded with a prayer.
After which, the meeting ending, he went to Henry Gouldney`'s, in White-Hart court,
near the meetinghouse, where he said to some that came with him,
he thought he felt the cold strike to his heart as he came out of the meeting.
Yet added, '`I am glad I was here: now I am clear, I am fully clear.`'
When those friends that were with him were withdrawn,
he lay down in his clothes upon a bed, but soon rose again;
yet after a little time he lay down again, complaining still of cold;
and his strength decaying, he not long after undressed, and went to bed,
where he lay in much contentment and resignation, continuing very sensible to the last.
His distemper increasing, and perhaps perceiving that his end was at hand,
he recommended to some of his friends that came to him after having been sent for,
the spreading of books containing the doctrine of truth.
And to some others who came to visit him in his illness, he said, '`All is well,
the seed of God reigns over all, and over death itself.
And though, continued he, I am weak in the body, yet the power of God is over all,
and the seed reigns over all disorderly spirits.`'
He used often, even in his preaching, when he spoke of Christ, to call him the seed;
wherefore those that were with him very well knew
what he meant when he spoke of the seed.
Thus he lay in a heavenly frame of mind,
his spirit being wholly exercised towards the Lord,
and he grew weaker and weaker in body, until, on the third day of the week,
and of his sickness also, he piously departed this life.
About four or five hours before, being asked how he did, he answered, '`Do not heed,
the power of the Lord is above all sickness and death; the seed reigns,
blessed be the Lord,`' And thus triumphing over death, he departed from here in peace,
and slept sweetly on the 13th of the month, anciently called January,
for being as a door or entrance into the new year, about ten o`'clock at night,
in the 67th year of his age.
His body was buried near Bunhill-fields, on the 16th of the said month,
the corpse being accompanied by great numbers of his friends, and of other people also:
for though he had had many enemies, yet he had made himself also beloved of many.

He was tall of statute, and pretty big-bodied, yet very moderate in food and drink;
neither did he yield much to sleep.
He was a man of a deep understanding, and of a discerning spirit:
and though his words were not always linked together by a neat grammatical connection,
and his speech sometimes seemed abrupt, as with a kind of gap;
yet he expressed himself intelligently, and what was lacking in human wisdom,
was abundantly supplied with heavenly knowledge.
He was of a quick apprehension; and though his wit was not polished by human art,
yet he was ingenious; and in his prayers, which generally were not very long,
though powerful, appeared a decent gravity, mixed with an awful reverence, to admiration.
His qualities are at large set forth by Thomas Ellwood, an eminent author,
who having much conversed with him, gave the following character of him.

[.embedded-content-document.testimony]
--

He was indeed a heavenly-minded man, zealous for the name of the Lord,
and preferred the honor of God before all things.
He was valiant for the truth, bold in asserting it, patient in suffering for it,
unwearied in laboring in it, steady in his testimony to it, immoveable as a rock.
Deep he was in divine knowledge, clear in opening heavenly mysteries,
plain and powerful in preaching, fervent in prayer.
He was richly endued with heavenly wisdom, quick in discerning, sound in judgment:
able and ready in giving, discreet in keeping counsel; a lover of righteousness;
an encourager of virtue, justice, temperance, meekness, purity, chastity, modesty,
and self-denial in all, both by word and example.
Graceful he was in countenance, manly in personage, grave in gesture,
courteous in conduct, weighty in communication, instructive in discourse;
free from affectation in speech and carriage.
A severe reprover of hard and obstinate sinners;
a mild and gentle admonisher of such as were tender and sensible of their failings.
Not apt to resent personal wrongs; easy to forgive injuries: but zealously earnest,
where the honor of God, the prosperity of truth, the peace of the church, were concerned.
Very tender,
compassionate and pitiful he was to all that were under any sort of affliction;
full of brotherly love, full of fatherly care;
for indeed the care of the churches of Christ was daily upon him,
the prosperity and peace whereof he studiously sought.

--

Yet more is said of him to his praise, both by the said Thomas Ellwood and others,
but I will not detain my reader any longer therewith.
His wife, about six months before his death, came to him at London,
and being glad of his health, which then was better than some time before, she,
after some stay in the said city, returned home well satisfied, leaving him at London,
where his general service to the church seemed to be then most requisite.
After his decease an epistle was found, which was written with his own hand,
and left sealed up with this superscription, '`Not to be opened before the time.`'
What this signified, seemed to be a riddle, but he being now deceased,
it was judged to be the time to open this letter, which was directed to his friends,
and was as follows:

[.embedded-content-document.epistle]
--

For the yearly and second-day`'s-meeting in London and to
all the children of God in all places in the world.
By and from G. Fox.

This for all the children of God everywhere, that are led by his spirit,
and do walk in his light, in which they have life, and unity,
and fellowship with the Father and the Son, and one with another.

Keep all your meetings in the name of the Lord Jesus, that be gathered in his name,
by his light, grace, truth, power and spirit;
by which you will feel his blessed and refreshing presence among you, and in you,
to your comfort and God`'s glory.

And now all friends, all your meetings, both men`'s and women`'s, monthly and quarterly,
and yearly, etc. were set up by the power, and spirit, and wisdom of God:
and in them you do know that you have felt both his power, and spirit, and wisdom,
and blessed refreshing spirit among you, and in you, to his praise and glory,
and your comfort: so that you have been a city set on a hill, that cannot be hid.

And although many loose and unruly spirits have risen betimes to oppose you and them,
both in print and other ways; but you have seen how they have come to nought;
and the Lord has blasted them, and brought their deeds to light,
and made them manifest to be the trees without fruit, and wells without water,
and wandering stars from the firmament of God`'s power, and the raging waves of the sea,
casting up their mire and dirt:
and many of them are like the dog turned to his old vomit, and the sow that was washed,
turned again to the mire.
And this has been the condition of many, God knows, and his people.

And therefore all stand steadfast in Christ Jesus your head, in whom you are all one,
male and female, and know his government,
and of the increase of his government and peace there shall be no end;
but there will be an end of the devil`'s, and of all them that be out of Christ,
and do oppose it and him, whose judgment does not linger,
and their damnation does not slumber: and therefore in God`'s and Christ`'s light, life,
spirit and power live and walk, that is over all,
(and the seed of it,) in love and in innocency, and in simplicity;
and righteousness and holiness dwell, and in his power and Holy Ghost,
in which God`'s kingdom does stand.
All children of new and heavenly Jerusalem, that is from above, and is free,
with all her holy, spiritual children, to her keep your eyes.

And as for this spirit of rebellion and opposition, that has risen formerly and lately;
it is out of the kingdom of God and heavenly Jerusalem;
and is for judgment and condemnation, with all its books, words and works.
And therefore friends are to live and walk in the power and spirit of God,
that is over it, and in the seed, that will bruise and break it to pieces:
in which seed you have joy and peace with God, and power and authority to judge it;
and your unity is in the power and spirit of God, that does judge it;
and all God`'s witnesses in his tabernacle go out against it, and always have and will.

And let no man live to self, but to the Lord, as they will die in him;
and seek the peace of the church of Christ, and the peace of all men in him:
for blessed are the peace-makers.
And dwell in the pure, peaceable, heavenly wisdom of God,
that is gentle and easy to be entreated, that is full of mercy;
all striving to be of one mind, heart, soul, and judgment in Christ,
having his mind and spirit dwelling in you, building up one another in the love of God,
which does edify the body of Christ, his church, who is the holy head thereof.
So glory to God through Christ, in this age, and all other ages,
who is the rock and foundation, and the Immanuel, God with us.
Amen, over all, the beginning and the ending; in him live and walk,
in whom you have life eternal, in whom you will feel me, and I you.

All children of new Jerusalem, that descends from above, the holy city,
which the Lord and the Lamb is the light thereof, and is the temple:
in it they are born again of the spirit:
so Jerusalem that is above is the mother of them that are born of the spirit.
And so they that come, and are come, to heavenly Jerusalem, are them that receive Christ;
and he gives them power to become the sons of God, and are born again of the spirit:
so Jerusalem that is above, is their mother.
And such do come to heavenly mount Zion, and the innumerable company of angels,
and to the spirits of just men made perfect;
and are come to the church of the living God, written in heaven,
and have the name of God, and the city of God written upon them: so here is a new mother,
that brings forth a heavenly and a spiritual generation.

There is no schism, nor division, nor contention, nor strife, in heavenly Jerusalem,
nor in the body of Christ, which is made up of living stones, a spiritual house.
And Christ is not divided, for in him there is peace.
Christ says, in me you have peace.
And he is from above, and not of this world; but in the world below, in the spirit of it,
there is trouble: therefore keep in Christ, and walk in him, Amen.

[.signed-section-signature]
G+++.+++ Fox

[.postscript]
====

P+++.+++ S. Jerusalem was the mother of all true Christians before the apostacy; and since,
the outward Christians are broken into many sects, and they have gotten many mothers;
but all they that are come out of the apostacy by the power and spirit of Christ,
Jerusalem that is above, is their mother, and none below her;
who does nourish all her spiritual children.

====

[.signed-section-signature]
G+++.+++ Fox

[.signed-section-context-close]
Read at the Yearly Meeting in London, 1691.

--

This year I find that William Goodridge, of Banwell, in Somersetshire,
was released from prison, where he had been confined about thirteen years.
He had been premunired for refusing to take the oath: and his goods,
whereof the moveables were rated at about two hundred and forty-four pounds,
and the real estate counted worth sixty pounds per annum, were confiscated.
Thus to suffer spoil of goods has been the lot of many others,
and among these was Benjamin Brown, an ancient man, of Brownish in Suffolk, who also,
for not taking the oath, was stripped of all,
so that his wife and child were made to lie on the floor without a bed.

Now time calls me to say something of the apostasy of George Keith,
who being in Pennsylvania, made a great bustle there.
He was a witty person, and esteemed very learned;
and at the university obtained the degree of master of arts.
He often also gave proofs of a high soaring knowledge,
and was very ready to show from philosophy the reasons
and causes of many things in the creation;
but the doctrine of Francis Mercurius, baron of Helmons,
concerning the transmigration of souls, became so palatable to him,
that he not only in some manner approved it,
but also was believed to be concerned in the book
containing two hundred queries about that matter,
great part of which, as I have been informed,
he acknowledged to have been put in writing by himself,
though it appeared in public without the author`'s name.
But this notion meeting with no acceptance among the Quakers,
his love to them began to abate; and his discontent increased, because two persons,
who opposed him, had, as he said, used some unwarrantable expressions,
and were not so sharply reproved, as he, who was of a fiery temper, desired.
He accused them that they had said, that the light within was sufficient to salvation,
without any thing else.
From which he endeavored to prove, that they excluded the man Jesus Christ,
as not necessary to salvation; but they denied this to be their doctrine.

He afterwards said of William Stockdell,
one of those two persons at Philadelphia in Pennsylvania,
that he had charged him G. K. to have preached two Christs,
because he preached faith in Christ within, and in Christ without us.
Now though Stockdell would not allow this to be true,
and some of the hearers also denied it, though asserted by two others of his party,
yet G. Keith blew the fire of this quarrel, and so got some adherents.
He also charged the deputy-governor, Thomas Lloyd, to have said,
that faith in Christ without us, as he died for our sins, and rose again,
was not necessary to our salvation.
But others said, that the words were not so, and that the matter was not fairly stated;
since the question was not, whether faith in Christ without us, as he died for our sins,
and rose again, was not necessary to our salvation;
but whether that faith were indispensably necessary to all mankind,
and that none could be saved without it, though they had not the means, opportunity,
or capacity to know or receive it.
Which being asserted,
it was thought that such a position did not only exclude from salvation whole nations,
but also infants, and deaf and dumb persons.
Better had it been that such questions never had been started,
for a passionate maintaining of a different position often breeds strife and contention.
But G. Keith, with some others, having now separated themselves from the society,
he said his dissatisfaction was only with some unsound Quakers in America;
but he was in unity with all faithful friends in England.

And now he began to behave himself very disrespectfully,
and was on that account sharply reproved by the aforesaid Thomas Lloyd;
to whom he did not hesitate to speak in a reproachful way, charging him with impudence,
and saying, that he was unfit to be a governor, and that his name should stink, etc.
And because some members of the council did not expect to be better treated by him,
since he had called one of the magistrates impudent rascal; this was much resented,
and the more, because G. Keith having drawn in a printer, published a paper,
wherein he not only scandalously slandered the diligence
of the magistrates in restraining of robbers,
but also the judicial proceedings against murderers.
And seeing several Mennonites of the county of Meurs lived also in Pennsylvania,
it was not much to be wondered,
that they who count it unlawful for a Christian to bear the sword of magistracy,
did stick to him; and to get adherents seemed the main thing he aimed at;
for he himself was not trained up under such a notion,
but in the doctrine of the kirk of Scotland.
The consequence of this case was, that Keith and one Thomas Budd, who, with him,
had been compiler of the aforesaid paper, were fined for it;
but yet the government was so moderate, that the fine was never exacted:
and for all that G. Keith did not hesitate to make a great clamor of his sufferings;
and about two years after he came into England,
to make his complaint to the church at London.

This year in the month called August, Stephen Crisp deceased near London.
He had long been weak in body, and was much afflicted with the stone,
performing nevertheless his ministry of the gospel; and his service was very acceptable,
because he had a gift beyond many, being not only sound in doctrine and judgment,
but grave and elegant in his utterance, and well qualified for convincing his hearers,
and to touch them to the heart;
so that he generally met with a great concourse of people.
Four days before his decease, lying sick in bed, and being under great pain,
he was visited by G. Whitehead, to whom he said in substance, '`I see an end of mortality,
and yet cannot come at it; I desire the Lord to deliver me out of this painful body:
if he will but say the word, it is done: yet there is no cloud in my way.
I have a full assurance of my peace with God in Christ Jesus;
my integrity and uprightness of heart is known to the Lord;
and I have peace and justification in Jesus Christ, who made me so.`'
The day before his departure, G. Whitehead being come again to see him,
found him in a dying state and almost speechless; yet he was understood to say, '`I hope,
I am gathering, I hope, I hope.`'
G+++.+++ Whitehead near parting from him, asked him whether he had any thing to his friends;
to which he gave this answer, '`Remember my dear love in Jesus Christ to all friends.`'
The next day, being the 28th of the aforesaid month, he died at Wandsworth,
about five miles from London.
Many of his sermons taken in short hand from his mouth are published in print,
and give proofs of his having been indeed an able minister of the gospel.

In this year died also Catharine Evans, who, as has been mentioned here before,
had been long imprisoned at Malta.
She had suffered much for her religion; and in the year 1657,
having at Salisbury exhorted the people to repentance, this so incensed the magistrates,
that by order of Henry Ditton, justice, and Robert Good, mayor, she was stripped,
and fastened to the whipping-post in the market, and then whipped.
Afterwards coming there again, and speaking to the people in the market,
by way of admonition, she was sent to Bridewell, and put into a dark nasty place.
After her return from Malta, imprisonment fell to her share several times;
once at Welchpool in Montgomeryshire in the year 1666, for refusing to swear;
and several years after she was also imprisoned at Bristol.
And after many adversities and great sufferings, having lived to a great age, she died,
and so entered into everlasting rest.

Now I return again to George Keith, who appeared in the annual assembly at London,
anno 1694, but there he showed himself so passionate and boisterous,
that no means could be found to compose the difference.
Yet he seemed to get adherents among some of the Separatists about London:
but these also soon growing weary of him,
he got a place called Turner`'s-hall to preach in.
Here at first he had a great concourse of people,
since novelties generally beget curiosity.
But he from time to time more and more courting those of the church of England,
and falling in with the Episcopalians,
began to lose his esteem among people of other persuasions,
especially when at length he entirely conformed to that church,
which formerly in print he had zealously attacked: but in process of time he took a gown,
and was ordained to be a preacher.
After which he sometimes preached with the surplice on,
which in all probability he would have abhorred before ever he joined with the Quakers;
for he had been a member of the Presbyterian kirk of Scotland,
which always has been a zealous opposer of the episcopal ceremonies.
And since he had contradicted that,
which formerly he had asserted and defended in good earnest;
and charged the Quakers with a belief, which they never had acknowledged to be theirs,
they found themselves obliged publicly, to set forth their faith anew in print,
which they had often before asserted both in words and writing,
thereby to manifest that their belief was really orthodox,
and agreeable with the Holy Scriptures.
This they did by the following representation, which in the year 1693,
came forth in print at London, as follows, with this title.

[.embedded-content-document.paper]
--

[.letter-heading]
The Christian Doctrine, and Society of the People called Quakers, cleared, etc.

Whereas, divers accounts have been lately published in print,
of some late division and disputes between some persons
under the name of Quakers in Pennsylvania,
about several fundamental doctrines of the Christian faith,
(as is pretended by one party,) which being particularly mentioned,
and thereupon occasion very unduly taken by our adversaries,
to reproach both the Christian ministry,
and whole body of the people commonly called Quakers,
and their holy and Christian profession, both in England and elsewhere,
though no ways concerned in the said division or matters charged,
but rather grieved and troubled at it,
and at the indiscreet and reproachful management thereof in print,
to the amusing and troubling the world therewith, and giving occasion to the loose,
ignorant, and profane, to slight and contemn the truth,
and the interest of the tender religion of our Lord Jesus Christ:

We are, therefore, tenderly concerned for truth`'s sake, in behalf of the said people,
(as to the body of them, and for all of them who are sincere to God,
and faithful to their Christian principle and profession,)
to use our just endeavors to remove the reproach,
and alt causeless jealousies concerning us, touching those doctrines of Christianity,
or any of them pretended, or supposed, to be in question in the said division;
in relation whereunto we do in the fear of God,
and in simplicity and plainness of his truth received,
solemnly and sincerely declare what our Christian belief and profession has been,
and still is, in respect to Jesus Christ the only begotten Son of God, his suffering,
death, resurrection, glory, light, power, great day of judgment, etc.

We sincerely profess faith in God by his only begotten Son Jesus Christ,
as being our light and life, our only way to the Father,
and also our only mediator and advocate with the Father.^
footnote:[Hebrew xii.
2.; 1 Peter 1:21.; John 14:6.; 1 Tim. 2:5.]

That God created all things, he made the worlds, by his Son Jesus Christ,
he being that powerful and living Word of God by whom all things were made;^
footnote:[Eph. 3:9.; John 1:1-3.; Heb. 1:2.]
and that the Father, the Word, and Holy Spirit are one, in Divine Being inseparable;
one true, living and eternal God, blessed forever.^
footnote:[1 John 5:7.]

Yet that this Word, or Son of God, in the fulness of time, took flesh,
became perfect man, according to the flesh,
descended and came of the seed of Abraham and David,^
footnote:[Rom. 1:3-4.]
but was miraculously conceived by the Holy Ghost, and born of the Virgin Mary.^
footnote:[Matt. 1:23.]
And also further, declared powerfully to be the Son of God,
according to the spirit of sanctification, by the resurrection from the dead.^
footnote:[Rom. 1:3-4.]

That in the Word, (or Son of God,) was life, and the same life was the light of men;
and that he was that true light which enlightens every man coming into the world;^
footnote:[John 1:4,9.]
and therefore that men are to believe in the light,
that they may become the children of the light;^
footnote:[John 12:36.; Isa. 2:5.]
hereby we believe in Christ the Son of God, as he is the light and life within us;
and wherein we must needs have sincere respect and honor to, and believe in, Christ,
as in his own unapproachable and incomprehensible glory and fulness:^
footnote:[1 Tim. 6:16.]
as he is the fountain of life and light, and giver thereof unto us; Christ,
as in himself, and as in us, being not divided.
And that as man, Christ died for our sins, rose again,
and was received up into glory in the heavens.^
footnote:[1 Pet. 3:18.; 1. Tim.
iii. 16.; Matt. 19:28.; and xxv.
31.; Luke 9:26.; and xxiv.
26.]
He having, in his dying for all, been that one great universal offering,
and sacrifice for peace, atonement and reconciliation between God and man;^
footnote:[Rom. 5:10-11.; Heb. 2:17-18.; Eph. 2:16-17.; Col. 1:20-22.]
and he is the propitiation not for our sins only, but for the sins of the whole world.^
footnote:[1 John 2:2.; 2 Cor. 5:14-15.; Heb. 2:9.]
We were reconciled by his death, but saved by his life.

That Jesus Christ,
who sits at the right hand of the throne of the majesty in the heavens,
yet he is our king, high-priest, and prophet,^
footnote:[Zech. 9:9.; Luke 19:38.; John 12:15.; Heb. 3:1.; Duet. 18:15,18.
; Acts 3:22, and vii.
37.]
in his church, a minister of the sanctuary,
and of the true tabernacle which the Lord pitched, and not man.^
footnote:[Heb. 8:1-2.]
He is intercessor and advocate with the Father in heaven,
and there appearing in the presence of God for us,^
footnote:[Heb. 7:25.; Heb. 9:24.]
being touched with the feeling of our infirmities, sufferings and sorrows.
And also by his spirit in our hearts, he makes intercession according to the will of God,
crying, Abba, Father.^
footnote:[Rom. 8:26,27,34.; Gal. 4:6.]

For any whom God hath gifted,^
footnote:[Eph. 3:7.; 1 Pet. 4:10.]
and called sincerely to preach faith in the same Christ, both as within and without us,
cannot be to preach two Christs, but one and the same Lord Jesus Christ,^
footnote:[1 Cor.
viii, 6.]
having respect to those degrees of our spiritual knowledge of Christ Jesus in us,^
footnote:[John 15:26. and xvi.
13, 14, 15,]
and to his own unspeakable fulness and glory,^
footnote:[John 1:16.]
as in himself, in his own entire being,
wherein Christ himself and the least measure of his light or life,
as in us or in mankind, are not divided nor separable,
no more than the sun is from its light.
And as he ascended far above all heavens, that he might fill all things,^
footnote:[Eph. 4:10.]
his fulness cannot be comprehended, or contained in any finite creature;^
footnote:[Col. 1:19. and ii.
9]
but in some measure known and experienced in us, as we are capable to receive the same,
as of his fulness we have received grace for grace.
Christ our Mediator, received the spirit, not by measure,^
footnote:[John 3:34.]
but in fulness; but to every one of us is given grace,
according to the measure of his gift.^
footnote:[Eph. 4:7.]

That the gospel of the grace of God should be preached in the name of the Father, Son,
and Holy Ghost,^
footnote:[Matt. 28:19.]
being one^
footnote:[John 1:1-4,]
in power, wisdom, and goodness, and indivisible, or not to be divided,
in the great work of man`'s salvation.

We sincerely confess and believe in Jesus Christ, both as he is true God and perfect man,^
footnote:[John 1:1-2,; Rom. 9:5.; 1 John 5:20.; 1 Tim. 2:5]
and that he is the author of our living faith in the power and goodness of God,
as manifested in his Son Jesus Christ, and by his own blessed spirit, or divine unction,
revealed in us,^
footnote:[1 John 2:20,27.]
whereby we inwardly feel and taste of his goodness,^
footnote:[1 Pet. 2:3.; John 6:33,35,51,57,58.]
life, and virtue; so as our souls live and prosper by and in him:
and the inward sense of this divine power of Christ, and faith in the same,
and this inward experience, is absolutely necessary to make a true, sincere,
and perfect Christian, in spirit and life.

That divine honor and worship is due to the Son of God;^
footnote:[John 5:23.; Heb. 1:6.]
and that he is, in true faith to be prayed unto,
and the name of the Lord Jesus Christ called upon, as the primitive Christians did,^
footnote:[1 Cor. 1:2.; Acts 7:59]
because of the glorious union or oneness of the Father and the Son;^
footnote:[John 10:30.; 1 John v.]
and that we cannot acceptably offer up prayers and praises to God,
nor receive a gracious answer or blessing from God,
but in and through his dear Son Christ.

That Christ`'s body that was crucified was not the godhead,
yet by the power of God was raised from the dead;
and that the same Christ that was therein crucified, ascended into heaven and glory,^
footnote:[Luke 24:26.]
is not questioned by us.
His flesh saw no corruption,^
footnote:[Ps. 16:10.; Acts 2:31.; and xiii.
35.37]
it did not corrupt; but yet doubtless his body was changed into a more glorious^
footnote:[Phil. 3:21.]
and heavenly condition than it was in when subject to divers sufferings on earth;
but how and what manner of change it met withal after it was raised from the dead,
so as to become such a glorious body, as it is declared to be,
is too wonderful for mortals to conceive, to apprehend or pry into,
and more meet for angels to see: the scripture is silent therein,
as to the manner thereof, and we are not curious to inquire or dispute it;
nor do we esteem it necessary to make ourselves wise above^
footnote:[1 Cor. 4:6.]
what is written as to the manner or condition of Christ`'s glorious body, as in heaven;
no more than to inquire how Christ appeared in divers manners or forms;^
footnote:[John 20:15.]
or how he came in among his disciples, the doors being shut;^
footnote:[John 20:19.; Luke 24:36-37,; and xxiv.
31.]
or how he vanished out of their sight after he was risen.
However, we have cause to believe his body, as in heaven,
is changed into a most glorious condition, far transcending what it was in on earth,
otherwise how could our low body be changed,
so as to be made like unto his glorious body;^
footnote:[Phil. 3:21.]
for when he was on earth, and attended with sufferings,
he was said to be like unto us in all things, sins only excepted;^
footnote:[Heb. 2:17, and iv.
15.]
which may not be so said of him as now in a state of glory, as he prayed for;^
footnote:[John 22:5.]
otherwise where would be the change both in him and us?

True and living faith in Christ Jesus the Son of the living God,^
footnote:[John 14:1.]
has respect to his entire being and fulness, to him entirely as in himself,
and as all power in heaven and earth is given unto him;^
footnote:[Matt. 28:18, and xi.
27.; John 17:2.; Heb. 2:8.]
and also an eye and respect to the same Son of God^
footnote:[John 14:23, and xvii.
21, 22, 23, 24, 26.]
as inwardly making himself known to the soul, in every degree of his light, life, spirit,
grace, and truth; and as he is both the word of faith, and a quickening spirit in us;^
footnote:[1 Cor. 15:45.; Rom. 10:7-8.]
whereby he is the immediate cause, author, object,
and strength of our living faith in his name and power;
and of the work of our salvation from sin and bondage of corruption:
and the Son of God cannot be divided from the least
or lowest appearance of his own divine light,
or life in us or in mankind, no more than the sun from its own light:
nor is the sufficiency of his light within by us
set up in opposition to him the man Christ,
or his fulness, considered as in himself, as without us;
nor can any measure or degree of light, received from Christ, as such,
be properly called the fulness of Christ, or Christ as in fulness, nor exclude him,
so considered, from being our complete Savior; for Christ himself to be our light,
our life, and Savior,^
footnote:[John 1:4,9, and iii.
19, 20, and xii.
35, 36, 46, and viii.
12.]
is so consistent, that without this light we could not know life,
nor him to save us from sin or deliver us from darkness, condemnation or wrath to come:
and where the least degree or measure of this light
and life of Christ within is sincerely waited in,
followed and obeyed; there is a blessed increase of light and grace known and felt;
as the path of the just it shines more and more, until the perfect day;^
footnote:[Prov. 4:18.; Ps. 36:9.]
and thereby a growing in grace, and in the knowledge of God,
and of our Lord and Savior Jesus Christ, hath been, and is truly experienced.
And this light, life, or spirit of Christ within,
(for they are one divine principle,) is sufficient to lead unto all truth;
having in it the divers ministrations both of judgment and mercy, both of law and gospel,
even that gospel which is preached in every intelligent creature under heaven:
it does not only, as in its first ministration, manifest sin,
and reprove and condemn for sin;
but also excites and leads them that believe in it to true repentance;
and thereupon to receive that mercy, pardon, and redemption in Christ Jesus,
which he hath obtained for mankind in those gospel terms of faith in his name,
true repentance and conversion to Christ, thereby required.

So that the light and life of the Son of God within, truly obeyed and followed,
as being the principle of the second or new covenant,
as Christ the light is confessed to be,
even as he is the seed or word of faith in all men, this does not leave men or women,
who believe in the light, under the first covenant, nor as the sons of the bond-woman,
as the literal Jews were, when gone from the Spirit of God, and his Christ in them;
but it naturally leads them into the new covenant, in the new and living way,
and to the adoption of sons, to be children and sons of the free woman,
of Jerusalem from above.

It is true, that we ought not to lay aside, nor any way to undervalue,
but highly to esteem, true preaching and the holy scriptures;
and the sincere belief and faith of Christ, as he died for our sins,
and rose again for our justification;
together with Christ`'s inward and spiritual appearance, and work of grace in the soul;
livingly to open the mystery of his death, and perfectly to effect our reconciliation,
sanctification, and justification;
and wherever Christ qualifies and calls any to preach
and demonstrate the mystery of his coming,
death, and resurrection, etc. even among the Gentiles,
Christ ought accordingly to be both preached, believed, and received.

Yet supposing there have been, or are such pious and conscientious Gentiles,
in whom Christ was and is as the seed or principle of the second or new covenant,
the light, the word of faith, as is granted;
and that such live uprightly and faithfully to that light they have,
or to what is made known of God in them, and who therefore in that state cannot perish,
but shall be saved, as is also confessed;
and supposing these have not the outward advantage of preaching, scripture,
or thence the knowledge of Christ`'s outward coming,
being outwardly crucified and risen from the dead; can such, thus considered,
be justly excluded Christianity, or the covenant of grace, as to the virtue, life,
and nature thereof, or truly deemed no Christians,
or void of any Christian faith in the life and power of the Son of God within,
or be only sons of the first covenant, and bond-woman, like the literal outside Jews;
or must all be excluded any true knowledge or faith of Christ within them,
unless they have the knowledge of Christ as without them?
No sure! for that would imply insufficiency in Christ and his light, as within them,
and to frustrate God`'s good end and promise of Christ,
and his free and universal love and grace to mankind, in sending his Son.
We charitably believe the contrary,
that they must have some true faith and interest in Christ and his mediation,
because of God`'s free love in Christ to all mankind, and Christ`'s dying for all men,^
footnote:[2 Cor. 5:14-15.]
and being given for a light of the Gentiles, and for salvation to the ends of the earth;^
footnote:[Isa. 49:6.; Luke 2:32.; Acts 13:47.]
and because of their living up sincerely and faithfully
to his light in them--their being pious,
conscientious, accepted and saved, as is granted.
We cannot reasonably think a sincere, pious, or godly man, wholly void of Christianity,
of what nation soever he be, because none can come to God or godliness but by Christ,^
footnote:[John 14:6.]
by his light and grace in them: yet we grant if there be such pious,
sincere men or women, as have not the scripture or knowledge of Christ,
as outwardly crucified, etc. they are not perfect Christians in all perfections,
as in all knowledge and understanding, all points of doctrine,
outward profession of Christ; so that they are better than they profess or pretend to be;
they are more Jews inward, and Christians inward, than in outward show or profession.
These are Christians sincere and perfect in kind or nature, in life and substance,
though not in knowledge and understanding.
A man or woman having the life and fruits of true Christianity,
the fruits of the Spirit of Christ in them, that can talk little thereof, or of creeds,
points, or articles of faith, yea many that cannot read letters,
yet may be true Christians in spirit and life; and some could die for Christ,
that could not dispute for him; and even infants that die in innocence,
are not excluded the grace of God, or salvation in and by Christ Jesus,
the image and nature of the Son of God, being in some measure in them,
and they under God`'s care and special Providence.
See Matt, xviii, 2. 10.

And though we had the holy Scriptures of the Old and New Testament,
and a belief of Christ crucified and risen, etc. we never truly knew the mystery thereof,
until we were turned to the light of his grace and spirit within us:
we knew not what it was to be reconciled by his death, and saved by his life;
or what it was to know the fellowship of his sufferings, the power of his resurrection,
or to be made conformable unto his death, we knew not, until he opened our eyes,
and turned our minds from darkness unto his own divine life and light within us.

Notwithstanding, we do sincerely and greatly value the holy Scriptures,
preaching and teaching of faithful, divinely inspired, gifted, and qualified persons,
and ministers of Jesus Christ, as being great outward helps,
and instrumental in his hand, and by his spirit, for conversion,
where God is pleased to afford those outward helps and means;
as that we neither do nor may oppose the sufficiency
of the light or Spirit of Christ within,
to such outward helps or means, so as to reject, dis-esteem, or undervalue them;
for they all proceed from the same light and spirit,
and tend to turn men`'s minds thereunto, and all centre therein.

Nor can the holy Scriptures or true preaching without,
be justly set in opposition to the light or Spirit of God or Christ within;
for his faithful messengers are ministers thereof,
being sent to turn people to the same light and spirit in them.

It is certain, that great is the mystery of godliness in itself,
in its own being and excellency: namely,
that God should be and was manifest in the flesh, justified in the spirit,
seen of angels, preached unto the Gentiles, believed on in the world,
and received up into glory.

And it is a great and precious mystery of godliness and Christianity also,
that Christ should be spiritually and effectually in men`'s hearts,
to save and deliver them from sin, Satan, and bondage of corruption,
Christ being thus revealed in true believers, and dwelling in their hearts by faith,
Christ within the hope of glory, our light and life, who of God is made unto wisdom,
righteousness, sanctification, and redemption, 1 Cor. 1:30.
And therefore this mystery of godliness,
but as in its own being and glory, and also as in men, (in many hid,
and in some revealed,) hath been and must be testified, preached, and believed;
where God is pleased to give commission, and prepare people`'s hearts for the same,
and not in man`'s wills,

Concerning the resurrection of the dead, and the great day of judgment yet to come,
beyond the grave, or after death, and Christ`'s coming without us,
to judge the quick and the dead,
(as divers questions are put in such terms,) what the holy
Scriptures plainly declare and testify in these matters,
we have great reason to credit, and not to question,
and have been always ready to embrace,
with respect to Christ and his apostles own testimony and prophecies.

[.numbered-group]
====

[.numbered]
1+++.+++ For the doctrine of the resurrection;

If in this life only we have hope in Christ, we are of all men the most miserable, 1 Cor. 15:19.
We sincerely believe,
not only a resurrection in Christ from the fallen sinful state here,
but a rising and ascending into glory with him hereafter; that when he at last appears,
we may appear with him in glory, Col. 3:4. 1 John 3:2.

But that all the wicked who live in rebellion against the light of grace,
and die finally impenitent, shall come forth to the resurrection of condemnation.

And that the soul or spirit of every man and woman shall
be reserved in its own distinct and proper being,
(so as there shall be as many souls in the world to come as in this,) and every seed,
yea every soul, shall have its proper body, as God is pleased to give it, 1 Cor.
xv. A natural body is sown, a spiritual body is raised;
that being first which is natural, and afterward that which is spiritual.
And though it is said, this corruptible shall put on incorruption,
and this mortal shall put on immortality;
the change shall be such as flesh and blood cannot inherit the kingdom of God,
neither does corruption inherit incorruption, 1 Cor.
xv. We shall be raised out of all corruption and corruptibility, out of all mortality;
and the children of God and of the resurrection,
shall be equal to the angels of God in heaven.^
footnote:[Matt. 22:30.; Mark 12:25.; Luke 20:36.]

And as the celestial bodies do far excel terrestrial,
so we expect our spiritual bodies in the resurrection,
shall far excel what our bodies now are;
and we hope that none can justly blame us for thus
expecting better bodies than now they are.
Howbeit, we esteem it very unnecessary to dispute or question how the dead are raised,
or with what body they come:
but rather submit that to the wisdom and pleasure of the Almighty God.

[.numbered]
2+++.+++ For the doctrine of eternal judgment;

God hath committed all judgment unto his Son Jesus Christ;
and he is both judge of quick and dead, and of the states and ends of all mankind,
John 5:22. 27. Acts 10:42. 2 Tim. 4:1. 1 Pet. 4:5.

That there shall be hereafter a great harvest, which is the end of the world,
a great day of judgment, and the judgment of that great day, the holy Scripture is clear,
Matt. 13:39-41, 10:15, and 11:24. Jude 6.
"`When the Son of Man comes in his glory, and all the holy angels with him,
then shall he sit upon the throne of his glory,
and before him shall be gathered all nations, etc.`"
Matt. 25:31-32, to the end,
compared with ch. 22. 31. Mark 8:38. Luke 9:26, and 1 Cor. 15:52. 2 Thess. 1:7-8, to the end,
and 1 Thess. 4:16. Rev. 20:12-15.

That this blessed heavenly man, this Son of Man,
who hath so deeply suffered and endured so many great
indignities and persecutions from his adversaries,
both to himself and his members and brethren, should at last,
even in the last and great day, signally and manifestly appear in glory and triumph,
attended with all his glorious heavenly host and retinue before all nations,
before all his enemies, and those that have denied him;
this will be to their great terror and amazement, that this most glorious heavenly man,
and his brethren, that have been so much contemned and set at naught,
should be thus exalted over their enemies and persecutors, in glory and triumph,
is a righteous thing with God; and that they that suffer with him,
should appear with him in glory and dignity when he thus appears at last.
Christ was judge of the world, and the prince thereof, when on earth,
John 9:39. and 12:31.
He is still judge of the world, the wickedness, and prince thereof, by his light,
spirit, and gospel in men`'s hearts and consciences, John 16:11-8.
Matt. 12:20. Isa. 42:1. Rom. 2:16. 1 Pet. 4:6.
And he will be the judge and final determiner thereof in that great day appointed;
God having appointed a day wherein he will judge the world
in righteousness by that man whom he hath ordained.
Christ foretold it shall be more tolerable for them
of the land of Sodom and Gomorrah in the day of judgment,
than for that city or people that would not receive his messengers or ministers.
etc. Matt. 10:15. and see chap.
xi. 24. and Mark 6:11. Luke 10:12. 14. It is certain that God knows
how to deliver the godly out of all their trials and afflictions,
and at last to bring them forth, and raise them up into glory with Christ;
so he knows also how to reserve the unjust and finally
impenitent unto the day of judgment to be punished, 2 Pet. 2:9.
He will bring them forth unto the day of destruction, Job 21:30.
The Lord can and will reserve such impenitent,
presumptuous and rebellious criminals, as bound under chains of darkness,
as were the fallen angels, unto the judgment of the great day,
Jude 6. Matt. 25:30. It is not for us to determine
or dispute the manner how they shall be so reserved;
but leave it to God; he knows how.

====

[.centered]
=== A Postscript relating to the doctrine of the Resurrection and eternal Judgment.

At the last trump of God, and the voice of the archangel,
the dead shall be raised incorruptible, the dead in Christ shall rise first, 1 Cor. 15:52.
1 Thess. 4:16. compared with Matt. 24:31.

Many are often alarmed in conscience here by the word and voice of God,
who stop their ears and slight those warnings,
but the great and final alarm of the last trumpet, they cannot stop their ears against,
nor escape, it will unavoidably seize upon, and further awaken them finally to judgment.
They that will not be alarmed in their consciences, unto repentance,
nor out of their sins here, must certainly be alarmed to judgment hereafter.

Whosoever do now willfully shut their eyes, hate, contemn, or shun the light of Christ,
or his appearance within, shall at last be made to see,
and not be able to shun or hide themselves from his glorious
and dreadful appearance from heaven with his mighty angels,
as with lightning and flaming fire, to render vengeance on all them that know not God,
and obey not the gospel of our Lord Jesus Christ, 1 Thess. 4:16.
Matt. 24:27. Luke 17:24. Dan. 10:6. Job 37:3.

And though many now evade and reject the inward convictions and judgment of the light,
and shut up the records or books thereof in their own consciences,
they shall be at last opened, and every one judged of these things recorded therein,
according to their works, Rev. 20:12-15.

Signed in behalf of our Christian profession and people aforesaid,

[.signed-section-signature]
George Whitehead,
Charles Marshall, Ambrose Rigge, John Bowater, William Fallowfield, John Vaughton,
James Parke, William Bingley.

--

This paper generally gave satisfaction, and was well received also in Holland,
where having translated it into Dutch, I got it published in print.
Now since Francis Bugg, an envious apostate,
charged the Quakers with some Socinian notions; and being set on by some churchmen,
endeavored also to render them odious with the government,
the following confession of faith, signed by one and thirty persons,
of which G. Whitehead was one, was in December presented to the parliament:

[.embedded-content-document.address]
--

Be it known to all that we sincerely believe and confess:

[.numbered-group]
====

[.numbered]
I+++.+++ That Jesus of Nazareth, who was born of the Virgin Mary, is the true Messiah,
the very Christ, the Son of the living God, to whom all the prophets gave witness:
and that we do highly value his death, sufferings, works, offices,
and merits for the redemption of mankind, together with his laws, doctrine,
and ministry.

[.numbered]
II. That this very Christ of God,
who is the Lamb of God that takes away the sins of the world, was slain, was dead,
and is alive, and lives forever in his divine, eternal glory, dominion,
and power with the Father.

[.numbered]
III. That the holy Scriptures of the Old and New Testament, are of divine authority,
as being given by the inspiration of God.

[.numbered]
IV. And that magistracy or civil government, is God`'s ordinance,
the good ends thereof being for the punishment of evil-doers,
and praise of them that do well.

====

--

By this and the like writings,
the eyes of many that were at the helm began to be more opened;
and even among the bishops were some that inclined to moderation;
for the king endeavored as much as he could to promote the
most moderate among the churchmen to those high dignities;
and prejudice, which had blinded many in respect to the Quakers,
began to abate more and more.
But yet there was one thing that continually caused them much hardship, namely,
their refusing to swear;
for by reason of this they were not only deprived of their rights as freemen,
but also of giving evidence in courts of judicature.
They did not therefore omit from time to time, to petition the parliament,
wherein they desired to be relieved of this heavy burden,
though hitherto they had not been able to obtain this favor:
wherefore on the 26th of November, they delivered a petition to the parliament,
setting forth their great sufferings,
for lack of their solemn declaration being taken instead of an oath;
and that not in their own cases only, but in evidence wherein others were concerned.
This petition concluded thus:

[.embedded-content-document.legal]
--

We therefore earnestly and humbly request,
that you will favorably please to give leave to bring in a bill to admit,
that our solemn answer, affirmation or denial, may be accepted instead of an oath,
to relieve us in the cases aforesaid,
or in such of them as you in your wisdom shall see fit: we freely submitting,
that if any reputed a Quaker, shall falsify the truth, and be duly convicted thereof,
that every such person shall undergo the like pains and penalties,
as are provided against perjured persons.
And your petitioners shall, as in duty bound, pray, etc.

[.signed-section-signature]
William Mead, William Bingley, George Whitehead, Samuel Waldenfield, William Crouch,
John Staploe, Walter Rental, William Macker, Thomas Hart, Joseph Wright, jr.
Michael Russet, Theodore Ecclestone.

--

The petition being read in the House of Commons, they came to the following resolution:

[.embedded-content-document.legal]
--

A petition of the people called Quakers was read.
Resolved, that the consideration thereof be referred to a committee;
and that they report their opinions therein to the house.

--

A committee being ordered accordingly, sat thereupon, and gave their judgment as follows:

[.embedded-content-document.legal]
--

Upon the whole it is the opinion of this committee,
that the Quakers ought to be relieved according to the prayer of their petition.

--

But nothing was obtained that session;
for their enemies were yet so powerful in parliament,
that they found means to retard this beneficial work, and to stay the progress of it:
for so long as the Quakers were not relieved in the case of oaths, they,
who now were not liable to persecution on account of their public worship,
might yet for all that be otherwise molested and vexed.
Wherefore on the 22nd of December, in the year 1694,
a representation of their case of not swearing,
being signed in their behalf by Theodore Ecclestone,
was delivered to the members of parliament, and was as follows:

[.embedded-content-document.legal]
--

A brief representation of the Quakers`' case of not swearing;
and why they might have been, and yet may be relieved therein by Parliament.

It is a certain truth, that among Christians, and Protestants especially,
there are several particular things about religion,
conscientiously scrupled by some as unlawful, that others esteem orthodox:
and therefore it is not to be wondered, that the Quakers differ from many others,
though not from all, in this case of oaths;
they believing they are absolutely forbidden to swear in any case,
by that positive command of Christ, Matt. 5:12.
And that this is undeniably their Christian persuasion,
is evidenced by their sufferings these many years for not swearing.

And therefore their case may be worth the charitable notice of the government,
by law to relieve them therein; and not, for their religious persuasion,
to continue them and their families exposed to ruin;
who among their neighbors cheerfully pay to the support of the government;
and by their trades and industry, according to their capacities,
advance the national stock.

It may therefore, be humbly offered,
that it is not the interest of the government to refuse them relief.

Their industry in trade both at sea and land,
bringing profit to the government as well as others;
the station they stand in as merchants, farmers, manufacturers,
improvers of lands and stocks, is advantageous to their neighbors as truly as others.
And as it seems not the interest of the government in general that
they should be any ways discouraged in their honest industry,
so neither is it the interest of any eminent part of the government,
that they should not be relieved, viz. the judges.

For the frequent suits that are brought against the Quakers,
before the chancery and exchequer judges, are no doubt very troublesome and burdensome,
by the difficulty of getting at a just issue, for lack of swearing,
whereby justice is delayed, and their causes often held very long;
and no doubt when just judges see the Quakers wronged and abused,
and cannot relieve them, it is irksome to them: so that, it is humbly conceived,
it would be a great ease to those courts,
to have the Quakers relieved in this case of oaths.

Neither is it without advantage to the king`'s other courts,
to be able to use the evidence of one who is now a Quaker,
that perhaps was not so some years ago; when he was witness to a bill, bond, book-debt,
or deed of indenture; or when he was steward or trustee, or servant,
either to persons of quality, or to others of trade or estate.

Nor may their testimony be unuseful to coroners, in cases of unnatural deaths;
nor inconvenient in cases of trespass or felony, etc.

And it is further proposed,
that it is not the interest of the subjects to continue them unrelieved;
for it is not the interest of those the Quakers are indebted to;
because though such may sue and harass the Quakers in person and estate,
yet they may long lack a decision of their debt or claim, as to the right of it,
for lack of an answer upon oath.

It is not the interest of those they are concerned with in any doubtful case,
because of the difficulty to come to trial.

And for those that owe money to the Quakers,
to be allowed to fly into chancery for a refuge, to obstruct paying just debts,
is such an injury as it is hoped no one that is rational will countenance,
or desire should be continued upon them.
And may it not then be asserted,
that it is no honest man`'s true and just interest to have the Quakers denied relief; no,
not the gown-men of Westminster-hall, whose few fees from the Quakers as plaintiffs,
might suggest, though unduly, that they have no long-tailed debts to sue for,
nor titles to recover; but if they so suppose, it is a mistake,
for it is rather their despair of relief,
and their well-known inability to pursue a cause,
that is their common determent to begin.

So that of all causes that crowd these courts, few are brought by the Quakers,
though they may need it as much as others, to the great loss of the learned in the law,
as well as the poor injured Quaker.

And one might think it were great pity an industrious
people should be kept liable to all injurious suits,
and so much barred from suing for their rights, be their cause never so reasonable, just,
or necessary.

Seeing their relief is to them so needful, so harmless to all,
and so useful to the government and their neighbors;
let us a little consider the common objections; which may be summed up in short thus:

[.numbered-group]
====

[.numbered]
_First objection,_ How shall we then be at a certainty?

[.numbered]
_Secondly,_ Why should the laws be altered for them?
For,

[.numbered]
_Thirdly,_ It would be to rase old foundations

[.numbered]
_Fourthly,_ And let them into the government.

====

Which it is hoped will not be difficult to answer one by one,
and that to reasonable satisfaction.

And to the first, namely, the doubt of certainty.
It may be rationally affirmed, that whosoever is bound to tell the truth,
especially against men`'s own interest, where the temptation, if any, mainly lies,
such are either so bound by the law of God, or the law of men, or both.

Now the obligations by the law of God are binding on good men,
whether they give answers on oath, or on their solemn affirmation in the fear of God;
and knaves are only bound by the penal laws of men;
which if made equally severe to those that give fallacious answers,
as well without oath as by oath, would be equally effectual and binding,
both to them that give answers without swearing, and to them that swear.

The second objection.
That it would be an alteration of the law.
Not of the substance of the law, but of a circumstance;
and if that has no detriment in it, but that the alteration be really an amendment,
and a conveniency to an honest industrious people, pray why should it not be done?
What sessions of parliament is there that passes,
but some law or other is made for the ease, security, or relief of the subject?

If foreigners are too hard for our sea-faring people,
out goes an act of navigation to prevent it.

If our poor at home need silk to work with, how soon is it granted,
notwithstanding the same act, to come over land, and not directly in shipping,
from the places of its produce, as the said act before did enjoin;
and shall the ease of trade be so soon granted against a positive statute;
and the ease of conscience be so long denied in this, as positive a command of Christ,
at least really so believed and accepted?

And for the third objection.
That it is to rase old foundations.
Answer, No, as it was said it is rather to mend them; a proper work for parliaments.

Did not parliaments abrogate popery, with all its claim to antiquity?
Did not a parliament make the act of Habeas Corpus against the claim of prerogative?
And was it more reasonable to secure the subject
from perpetual imprisonment by a king without a trial,
than it is to secure one subject from imprisoning another till death,
for not giving an answer in chancery or exchequer upon oath?
Does it belong to parliaments to secure other subjects in their estates, liberties,
and properties,
and is it unparliamentary to secure the Quakers from
sequestrations against their whole estates,
because they dare not comply to a circumstance of the law, when, as they understand it,
it is against an express command of Christ?
Surely no:
and therefore their relief in parliament is a fitting
case to be there tenderly taken notice of,
and provided for.

May it not then be well worth the while for the present
parliament to relieve these distressed people,
and afford their suffering case redress:
that thereby their causes may the sooner come to an issue,
whether they sue for just debts, or are sued; whereby many unjust and vexatious suits,
by injurious and litigious persons, may be prevented;
which have often tended rather to the Quakers`' ruin and others`' damage,
than recovery of their right?

As to the fourth objection.
That it will tend to let them into the government.
For answer thereto, bar that as hard as you please; only do not let the supposal of that,
from which so easily and so willingly they may be excluded,
be a hindrance to that ease and benefit the government may so easily afford them.

But now, while you have opportunity by the station Providence has placed you in,
pray be of such noble, generous spirits as to relieve them;
though they differ from you in the construction of
a text they esteem plain and positive on their side,
and from which they dare not swerve;
having therein the concurrence of many ancient fathers and martyrs,
and since them the Mennists, and of the late Francis Osbourne, esq.
in his Political Reflections, 7th edition, p. 319, who treating of judicial cases,
calls not swearing,
a yielding a sincere and faithful obedience to the precept of our Savior,
"`Swear not at all:`" which, says he, the corrupt glosses of expositors labor much,
though all in vain, to elude.

And Swinderby, in his appeal to the king, complaining of the errors of the Catholics,
says thus: '`As Christ forbids swearing, so,`' says he, '`the Pope justifies swearing,
and compels men to swear.

Which no man can rationally say is only spoken of swearing in communication,
for his complaint is against justifying swearing, and compelling men to swear,
which cannot be pretended to mean other than solemn swearing; for no age that we read of,
did ever authorize profane swearing, much less compel to it.

Since therefore not only profane swearing,
but also solemn swearing was early complained of by Protestants,
let it not seem strange to any, that the Quakers now scruple swearing,
and for ease therein have often sought relief in parliament, the proper place.

Seeing then they believe they have the authority of Christ`'s command,
and the apostle`'s exhortation, and the martyrs`' doctrine on their side,
though some of you are not so persuaded:

Yet let the world behold your justice and willingness, according to your power,
to do good to all the honest and industrious people you both represent and govern;
by enacting that their solemn affirmation shall be accepted in lieu of an oath,
and all that falsify therein, shall be punished equally with perjured persons.

It having been made appear to a committee of this parliament, Dec.
2, 1692, that they are exposed to great hardships as aforesaid; and not themselves only,
but others also; which was the case of a member or two of this present parliament;

So that upon the whole matter, the said committee were of opinion,
and did report it to the house,
that the Quakers ought to be relieved according to the prayer of their petition,
then newly presented to the house.

Wherefore as liberty has been given them to declare
their allegiance to the government without swearing,
for which ease they are sincerely thankful; so be pleased to add to that kindness,
their relief in the matter of oaths, between them and other subjects,
as well as between the government and them.

[.signed-section-closing]
Signed in behalf of the said people,

[.signed-section-signature]
Theodore Ecclestone.

[.signed-section-context-close]
London, Dec. 22, 1694.

--

Though after the delivering of the said representation,
the parliament this year came not to a full resolution for their relief,
yet several members showed themselves more inclined to it,
and in the next year the matter was taken in hand again in good earnest.

Toward the conclusion of this year, Mary the 2nd, queen of England, deceased.
She was a princess eminent beyond many, being well versed in reading,
and of great knowledge, of which I will mention only this passage,
how the ambassador of the king, her father at the Hague,
having tried by many arguments to bring her over to the Catholic religion,
said afterwards in the presence of some great men,
that he never before believed that a woman was to be found any
where so well experienced in the doctrine of the Christian religion;
that therefore he would not advise any to enter into discourse with her about that matter.
On the 21st of December some symptoms of the small-pox appeared on the queen,
who had been ill a day or two before;
and her distemper suddenly increased to that degree,
that the physicians began to despair of her recovery:
but this was so far from frightening her, that she said, '`God be thanked, I am prepared.`'
And this quietness of mind did not leave her, even when she felt death approaching;
for then she was heard to say, I believe now that I shall die shortly; and I thank God,
that from my youth I have learned this true doctrine,
that repentance ought not to be deferred to a dying bed.`'
In such a Christian disposition she continued to her dying hour,
and so quietly gave up the ghost to her Creator, from whom she had received it,
departing at Kensington not long after midnight, between the 26th and 27th of December,
and left the king in unspeakable sorrow, who in all the time of her sickness, it is said,
had not departed from her chamber.
Many pens labored to celebrate her praises, and bewail her death;
and perhaps no queen in many ages has been more beloved than she was.
But I break off;
others have given an account of her excellent qualities and character to the world,
and it may be none better than Gilbert Burnet, bishop of Salisbury,
in a treatise entitled, '`An Essay on the Memory of the late Queen.`'
