== Chapter II.

=== 1650-1652

[.chapter-synopsis]
* Convincement of a Trooper
* Labors of G. Fox in divers places
* Injustice of Death penalty for Stealing
* Letters of G. Fox to different individuals
* Convincement of R. Farns worth, J+++.+++ Nayler and W. Dewsbury
* G. Fox preaches in several Steeple-houses
* Several Priests convinced, and become Quakers
* King`'s army beaten at Worcester
* General convincement
* Cruelty inflicted on G. Fox at Pattrington
* G. Fox travels into Nottinghamshire, Lincolnshire and Yorkshire
* Convincement of F. Howgill and J. Audland
* Convincement of E. Burrough
* Swarthmore
* Convincement in the family of Judge Fell
* Increase of Preachers among the Quakers

The year 1651 had scarce begun, when the Scots resolved, notwithstanding their overthrow,
to crown their new King, which, after he had sworn to maintain the Covenant,
they did in the beginning of the month called January.
But leaving this.

We return again to George Fox, whom we left at Derby, in the house of correction;
where about this time a trooper came to him, who said,
that having been in the steeple-house, hearing the priest,
exceeding great trouble came upon him, and that a voice,
(which he took to be that of the Lord,) said to him,
'`Dost thou not know that my servant is in prison?
Go to him for direction.`'
G+++.+++ Fox speaking to his condition, told him,
'`That which showed him his sins and troubled him for them,
would also show him his salvation; because He that shows a man his sin,
is the same that takes it away.`'
Whilst he was thus speaking,
the trooper`'s understanding began to be opened concerning the truth,
and he was sensible of God`'s mercies,
which made him speak boldly in his quarters among the soldiers, and others,
alleging the Scriptures for what he believed to be truth.
He also said, his colonel, (which I take to be Barton,) was as blind as Nebuchadnezzar,
to cast the servant of the Lord into prison.
This so incensed his colonel, that, when at Worcester fight,
the two armies lying near one another,
two from the King`'s army challenged any two of the Parliament`'s army to fight with them,
the said colonel made choice of him and another to answer the challenge:
and when in the encounter his companion was slain,
he drove both his enemies within a musket-shot of the town,
without firing a pistol at them.
Thus he returned victorious; but then he saw the deceit of the officers,
and how wonderfully the Lord had preserved him;
and in process of time becoming sensible that fighting was unlawful for a true Christian,
he laid down his arms, henceforth to fight under the banner of the Prince of Peace,
by entering into the spiritual warfare.

Now the time of G. Fox`'s commitment to the house of correction being very near out,
and there being many new soldiers raised,
the commissioners would have made him captain over them, and the soldiers cried,
They would have none but him.`'
So the keeper of the house of correction was commanded to bring
him up before the commissioners and soldiers in the market place;
and there they proffered him that preferment,
(as they called it,) asking him if he would not take up arms for the Commonwealth,
against Charles Stuart.
G+++.+++ Fox, never having been a fighter, though it has appeared he was bold and valiant,
told them, '`That he could not do so, as well knowing from whence all wars do arise,
(viz. from the lusts,
according to the doctrine of the apostle James,) and that
he lived in the virtue of that life and power,
that took away the occasion of all wars.`'
The commissioners, to fawn upon him, said,
'`They offered him the office in love and kindness, because of his virtue.`'
But he not mattering those flattering words, replied, '`If this be your love and kindness,
I trample it under my feet.`'
This bold answer presently showed how shallow their pretended kindness was:
for it so enraged them, that they said, '`Take him away, jailer,
and put him into the dungeon amongst the rogues and felons.`'
Thus G. Fox was put into a lousy stinking place amongst thirty felons,
where he had no bed, and was kept almost half a year,
unless that at times he was suffered to walk in the garden,
for they believed of him that he would not run away.
Being in this nasty prison, it was said among the people, that he never should come out:
but he, trusting in God, believed the contrary, it being showed him from the Lord,
(according to what he relates,) that he was not yet to be removed from that place,
there being a service for him to do.

In the meanwhile it was noised abroad, that he was in Derby dungeon,
and his relations came again to see him, they being much troubled about it;
for they thought it a great shame to them, that he should lie thus in jail: besides,
it was a strange thing then to be imprisoned for religion.
But some judged him to be mad, because he maintained the doctrine of purity,
righteousness, and perfection.
Among others that came to see him, there was also a soldier from Nottingham,
who said to him, '`Your faith stands in a man that died at Jerusalem;
and there was never any such thing.`'
This so grieved G. Fox, that he said to him,
'`How! did not Christ suffer without the gates of Jerusalem, by the professing Jews,
the chief priests, and Pilate?
'`No,`' said the other, '`he did not suffer there outwardly.`'
Then G. Fox asked him, '`Whether there were not Jews, chief priests, and Pilate outwardly?`'
This puzzled the soldier a little, so that he could not deny it.
Then he told him, '`As certainly as there was a chief priest, and Jews, and Pilate,
so certainly Christ did suffer there outwardly under them.`'
Yet this inconsiderate person said also, '`That never any of the prophets or apostles,
or holy men of God, suffered any thing outwardly;
but that all their sufferings were inward.`'
Then G. Fox instanced to him many of the prophets and apostles, how they suffered,
and by whom they suffered, thereby to confound his silly imaginations.
Yet such was the malice of some, that a slander was raised among the people,
that the Quakers denied Christ that suffered and died at Jerusalem.
This, indeed, is a singular evidence of the credulity of people,
taking upon trust any story, how false soever,
when it relates to those that are become the object of vulgar odium.
Now as G. Fox was often visited by those that came out of curiosity,
it is not to be wondered that sometimes he was contradicted
by presumptuous and self-conceited persons.
Once there came to him some that pretended they were triers of spirits;
and these he asked, '`What was the first step to peace:
and what it was by which a man might see his salvation.`'
But they, being of an airy mind, took this to be such a strange question,
that they did not stick to say he was mad.
Thus it appeared that these who pretended to try spirits,
did not know what spirit they themselves were of,
and that they had not sufficient knowledge to make a good judgment of the corpora]
constitution, saying he was mad, who was in no wise out of his senses.

In the time of his imprisonment,
he was much exercised in mind about the proceedings of the magistrates,
because men were put to death for stealing of cattle, money,
etc. and he was the more troubled about it,
because this practice was contrary to the law of God in old time.
Wherefore he writ the following two letters to the judges.

[.embedded-content-document.letter]
--

I am moved to write unto you to take heed of putting men to death for stealing cattle,
or money, etc. for the thieves in the old time were to make restitution;
and if they had not wherewithal, they were to be sold for their theft.
Mind the laws of God in the Scriptures, and the Spirit that gave them forth;
and let them be your rule in executing judgment: and show mercy,
that you may receive mercy from God, the Judge of all.
And take heed of gifts and rewards, and of pride; for God doth forbid them,
and they do blind the eyes of the wise.
I do not write to give liberty to sin; God hath forbidden it:
but that you should judge according to his laws, and show mercy:
for he delighteth in true judgment, and in mercy.
I beseech you to mind these things, and prize your time, now you have it; and fear God,
and serve him; for he is a consuming fire.

--

[.offset]
The other letter was thus.

[.embedded-content-document.letter]
--

I am moved to write unto you, that ye do true justice to every man,
and see that none be oppressed, nor wronged: nor no oaths imposed;
for the land mourneth because of oaths, and adulteries, and sorceries, and drunkenness,
and profaneness.
O consider, ye that be men set in authority: be moderate,
and in lowliness consider these things.
Show mercy to the fatherless, and to the widows, and to the poor:
and take heed of rewards or gifts, for they do blind the eyes of the wise:
the Lord doth loath all such.
Love mercy and true judgment, justice, and righteousness, for the Lord delighteth in such.
Consider these things in time, and take heed how ye do spend your time: now ye have time,
prize it, and show mercy, that ye may receive mercy from the Lord:
for he is coming to try all things, and will plead with all flesh, as by fire.

--

Whilst G. Fox was in prison among the felons, it grieved him to hear their foul language;
and he often reproved them for their wicked words, and evil carriage towards each other:
and people did admire that he was so preserved among this bad company,
without being defiled by their conversation:
but the fear of God so prevailed in his heart,
that he could not be charged with any evil word or action all the time he was there:
yet he perceived that it was dangerous to converse with such a naughty crew,
and therefore he laid before the judges what a hurtful thing it was,
that prisoners should lie long in a jail, because they learned wickedness one of another,
in talking of their bad deeds; and that therefore speedy justice ought to be done.

Now whilst he was confined here,
there was a young woman in the jail for robbing her master of some money;
and she being to be tried for her life, he wrote concerning her to the judge and jury,
showing them, how contrary it was to the law of God of old,
to put people to death for stealing; and that it was an incumbent duty to show mercy.
But notwithstanding his writing so, she was condemned to die,
and a grave was made for her.
G+++.+++ Fox having heard this, writ a few words, containing,
'`A warning for all people to beware of covetousness, and to fear the Lord,
and prize their time, while they have it; that so they might avoid wickedness.`'
And when the woman, at the time appointed, was carried forth to execution,
he gave this writing to be read at the gallows; but when she was upon the ladder,
with a cloth over her face, and ready to be turned off, she was reprieved,
and was brought back again to prison,
where afterwards she came to be convinced of the truth,
as held forth by G. Fox and his friends.

In the jail there was also detained a wicked man, who was said to be a conjurer;
this man threatened G. Fox, and also the jailer, that he would raise the devil,
and break the house down; so that he made the jailer afraid.
But G. Fox went to him, and said, '`Come, let us see what thou canst do, and do thy worst:
the devil is raised high enough in thee already; but the power of God chains him down.`'
At this undaunted speech the fellow slunk away.

Now the justices to get rid of G. Fox, resolved to press him for a soldier,
seeing he would not voluntarily accept of a command;
and Bennet sent constables to give him press-money:
but he told him,`'That he was brought off from outward war, and was dead to it.`'
And though the commissioners over and again proffered him money,
yet he would not take it; at which they grew so angry,
that he was committed close prisoner.
Hereupon G. Fox wrote to the justices, and those that were concerned in his commitment,
the following lines.

[.embedded-content-document.letter]
--

You, who are without Christ, and yet use the words which he and his saints have spoken,
consider, neither he nor his apostles did ever imprison any;
but my Savior is merciful even to the unmerciful and rebellious.
He doth bring out of prison and bondage: but men, while the carnal mind doth rule,
do oppress and imprison.
My Savior saith "`Love your enemies, and do good to them that hate you,
and pray for them that despitefully use you and persecute
you:`" for the love of God doth not persecute any;
but loveth all, where it dwelleth: "`he that hateth his brother,`" is a murderer.
You profess to be Christians, and one of you a minister of Jesus Christ,
yet you have imprisoned me who am a servant of Jesus Christ.
The apostles never imprisoned any; but were imprisoned themselves:
take heed of speaking of Christ in words, and denying him in life and power.
O friends, the imprisoning my body is to satisfy your wills;
but take heed of giving way to your wills, for that will hurt you.
If the love of God had broken your hearts, ye would not have imprisoned me;
but my love is to you, as to all my fellow creatures: and that you may weigh yourselves,
and see how you stand, is this written.

--

About this time he gave forth a paper to those that were convinced of the truth,
to show them the deceit of the world, and how the priests had deceived the people, viz.

[.embedded-content-document.paper]
--

Christ was ever hated; and the righteous, for his sake.
Mind who they were, that did ever hate them.
He that was born after the flesh, did persecute him that was born after the Spirit;
and so it is now.
And mind, who were the chiefest against Christ; even the great learned men,
the heads of the people, rulers and teachers, that did profess the law and the prophets,
and looked for Christ; they looked for an outwardly glorious Christ,
to hold up their outward glory: but Christ spake against the works of the world;
and against the priests, and scribes, and Pharisees, and their hypocritical profession.
He that is a stranger to Christ, is a hireling:
but the servants of Jesus Christ are freemen.
The false teachers always laid burdens upon the people:
and the true servants of the Lord did speak against them.
Jeremiah did speak against hirelings, and said, "`It was a horrible thing;`" and said,
"`What will ye do in the end?`" for the people and priests were given to covetousness.
Paul did speak against such as did make gain upon the people;
and exhorted the saints to turn away from such as were covetous men and proud men,
such as did love pleasures more than God; such as had a form of godliness,
but denied the power thereof.
"`For of this sort, (said he,) are they that creep into houses,
and lead captive silly women, who are ever learning,
but never able to come to the knowledge of the truth; men of corrupt minds,
reprobate concerning the faith; and as Jannes and Jambres withstood Moses, so,
(saith he,) do these resist the truth; but they shall proceed no further,
for their folly shall be made manifest unto all men.`" Moses forsook honors and pleasures,
which he might have enjoyed.
The apostle in his time saw this corruption entering,
which now is spread over the worlds of having a form of godliness, but denying the power.
Ask any of your teachers, whether you may ever overcome your corruptions and sins?
None of them doth believe that; but as long as man is here, he must,
(they say,) carry about with him the body of sin.
Thus pride is kept up, and that honor and mastership, which Christ denied;
and all unrighteousness: yet multitudes of teachers; heaps of teachers;
the golden cup full of abominations!
Paul did not preach for wages; but labored with his hands,
that he might be an example to all them that follow him.
O people, see, who follow Paul!
The prophet Jeremiah said, "`The prophets prophesy falsely,
and the priests bear rule by their means;`" but now the "`priests bear rule
by the means they get from the people:`" take away their means,
and they will bear rule over you no longer.
They are such as the apostle said, intruded into those things, which they never saw,
being vainly puffed up with a fleshly mind; and,
as the Scriptures declare of some of old, "`They go in the way of Cain,
(who was a murderer,) and in the way of Balaam,
who coveted the wages of unrighteousness.`" The prophet
Micah also cried against the judges,
that judged for reward; and the priests, that taught for hire;
and the prophets that prophesied for money; and yet leaned on the Lord, saying,
"`Is not the Lord amongst us?`" Gifts to blind the eyes of the wise:
and the gift of God was never purchased with money.
All the holy servants of God did ever cry against deceit:
and where the Lord hath manifested his love, they do loathe it,
and that nature which holdeth it up.

--

He also wrote a serious exhortation to the magistrates of Derby,
to consider whom they imprisoned.

[.embedded-content-document.letter]
--

[.salutation]
Friends,

I desire you to consider in time, whom ye do imprison:
for the magistrate is set for the punishment of evil-doers,
and for the praise of them that do well.
But when the Lord doth send his messengers unto you,
to warn you of the woes that will come upon you, except you repent;
then you persecute them, and put them into prison, and say, '`We have a law,
and by our law we may do it.`'
For you indeed justify yourselves before men; but God knoweth your hearts;
he will not be worshipped with your forms and professions, and shows of religion.
Therefore consider, ye that talk of God, how ye are subject to him;
for they are his children, that do his will.
What doth the Lord require of you, but to do justice, to love and show mercy,
to walk humbly with him, and to help the widows and fatherless to their right,
but instead thereof ye oppress the poor.
Do not your judges judge for reward, and your priests teach for hire?
The time is coming, that he who seeth all things, will discover all your secrets.
And know this assuredly, the Lord will deliver his servants out of your hands,
and he will recompense all your unjust dealings towards his people.
I desire you to consider of these things, and search the Scriptures,
and see whether any of the people of God did ever imprison any for religion;
but were themselves imprisoned.
I desire you consider, how it is written, that when the church is met together,
they may all prophesy, one by one: that all may hear, and all may learn,
and all be comforted: and then, "`If any thing be revealed to him that sitteth by,
let the first hold his peace.`" Thus it was in the true church; and thus it ought to be.
But it is not so in your assemblies; but he that teaches for hire, may speak,
and none may contradict him.
Again, consider the liberty that was given to the apostles,
even among the unbelieving Jews; when after the reading the law and the prophets,
the rulers of the synagogue said unto them, "`Ye men and brethren,
if ye have any word of exhortation for the people,
say on.`" I desire you to consider in stillness, and strive not against the Lord;
for he is stronger than you.
Though he hold his people fast for a time; yet when he cometh,
he will make known who are his: for his coming is like the refiner`'s fire,
and like fuller`'s soap.
Then the stone that is set at nought of you builders,
shall be the headstone of the corner.
O friends, lay these things to heart, and let them not seem light things to you.
I wrote unto you in love, to mind the laws of God, and your own souls,
and do as the holy men of God did.

--

During his imprisonment there, he was under a great exercise and travail in spirit,
because of the wickedness of that town;
for though some were convinced there of the doctrine of truth,
yet generally they were a hardened people:
and he seeing the visitation of God`'s love pass away from them, he mourned,
and wrote the following lamentation.

[.embedded-content-document]
--

O Derby! as the waters run away when the flood gates are up,
so doth the visitation of God`'s love pass away from thee,
O Derby! therefore look where thou art, and how thou art grounded; and consider,
before thou art utterly forsaken.
The Lord moved me twice,
before I came to cry against the deceits and vanities that are in thee;
and to warn all to look at the Lord, and not at man.
The woe is against the crown of pride,
and the woe is against drunkenness and vain pleasures,
and against them that make a profession of religion in words,
and are high and lofty in mind, and live in oppression and envy.
O Derby! thy profession and preaching, stinks before the Lord.
Ye do profess a Sabbath in words, and meet together, dressing yourselves in fine apparel;
and you uphold pride.
Thy women go with stretched forth necks, and wanton eyes,
etc. which the true prophet of old cried against.
Your assemblies are odious, and an abomination to the Lord; pride is set up,
and bowed down; covetousness abounds: and he that doth wickedly is honored:
so deceit doth bear with deceit; and yet they profess Christ in words.
O the deceit that is within thee! it doth even break
my heart to see how God is dishonored in thee,
O Derby!

--

After he had written this,
he perceived that his imprisonment there would not continue long;
for the magistrates grew uneasy about him, and could not agree what to do with him:
one while they would have sent him up to the Parliament,
and another while they would have banished him to Ireland.
At first they called him a deceiver, and a blasphemer; and afterwards,
when the judgments of God befell them, they said he was an honest virtuous man.
But their well or ill speaking was nothing to him; for the one did not lift him up,
nor did the other cast him down.
At length they turned him out of jail, about the beginning of the winter,
in the year 1651, after he had been prisoner in Derby about a year:
six months whereof in the house of correction,
and the rest of the time in the common jail and dungeon.

Being set at liberty, he went into Leicestershire, and had meetings where he came,
preaching so effectually, that several were convinced.
He went after to Nottinghamshire again, and from thence into Derbyshire,
where having visited his friends, he passed into Yorkshire, and coming into Doncaster,
and other places, he preached repentance.
Afterwards he came to Balby,
where Richard Farnsworth and several others were convinced by his preaching.
And coming afterwards into the parts about Wakefield, James Nayler came to him,
and also acknowledged the truth of that doctrine he held forth;
likewise William Dewsbury, with many more; and these three named,
became in time also ministers of the gospel.
But by the way,
I must say that William Dewsbury was one of those
that had already been immediately convinced,
as G. Fox himself was, who coming to him, found himself in unity with him:
and of these was also G. Fox the younger, of whom more hereafter.

But I return to the other G. Fox, who coming about Selby, passed from thence to Beverly,
where he went into the steeple-house, and after he that preached there had done,
George Fox spoke to the congregation, and said,
that '`they ought to turn to Christ Jesus as their teacher.`'
This struck a dread amongst the people, and the mayor spoke to him;
but none meddled with him.
In the afternoon he went to another steeple-house, about two miles off, where,
after the priest had done, he spoke to him, and the people,
showing them the way of life and truth, and the ground of election and reprobation.
The priest saying he could not dispute, G. Fox told him he did not come to dispute,
but to hold forth the word of truth, that they might all know the one seed,
to which the promise was, both in the male, and in the female.
Here his speaking did so please the auditory,
that he was desired to come again on another day, and to preach there.
But he directed them to their teacher Christ Jesus, and so went away.

The next day he came to Crantsick, to Captain Pursloe`'s,
who accompanied him to Justice Hotham`'s, and entering into discourse with G. Fox,
told him, he had known that principle above ten years,
and was glad that the Lord did publish it abroad among the people.
While G. Fox was there,
a great woman of Beverly came to speak with the said justice about some business,
who in discourse said, that the last sabbath-day,
(as she called it,) there was an angel or spirit came into the church at Beverly,
and spoke the wonderful things of God, to the astonishment of all that were there:
and that when it had done, it passed away, they not knowing whence it came,
nor whither it went; but it astonished all, both priest and professors,
and the magistrates of the town.
This relation justice Hotham gave himself afterwards; and then G. Fox told him,
that it was he who had been that day at Beverly steeple-house,
and had declared truth there.
The next First-day of the week captain Pursloe came to G. Fox,
and they both went to the steeple-house, where G. Fox, when the priest had done,
spoke to both priest and people, and directed them where they might find their teacher,
the Lord Jesus Christ, viz. inwardly, in their hearts; which was of such effect,
that some received that doctrine of truth, and continued in it.
In the afternoon he went to another steeple-house, about three miles off,
where one preached that bore the title of doctor: he took his text from Isaiah,
Iv. "`Every one that thirsteth, come ye to the waters, and he that hath no money, come ye,
buy and eat, yea come, buy wine and milk, without money,
and without price.`" G. Fox stayed till the priest had done,
and well knowing what kind of teacher he was, he was kindled with such a zeal,
that he said.
Come down thou deceiver: dost thou bid people come freely,
and to take of the water of life freely,
and yet thou takest three hundred pounds a year of them! mayest not thou
blush with shame! did the prophet Isaiah and Christ do so,
who spake the words, and gave them forth freely?
did not Christ say to his ministers, whom he sent to preach.
Freely ye have received, freely give?
the priest being amazed, hastened away,
and so gave G. Fox as much time as he could desire, to speak to the people;
who then directed them to the light, and the grace of God,
and to the spirit of God in their inward parts, to be taught and instructed thereby.
Having thus cleared himself among the people,
he returned to justice Hotham`'s house that night, who embracing him, said,
'`My house is your house;`' and also signified,
that he was exceedingly glad at the work of the Lord, and that his power was revealed.

From thence G. Fox went through the country, and came at night to an inn,
where he bid the woman of the house, if she had any meat, to bring him some.
But because he said thee and thou to her, she looked strangely on him.
Then he asked her if she had any milk; and she said, no.
He believing she spoke falsely, and seeing a churn stand in the room,
would try her further, and asked her if she had any cream;
but she denied that she had any.
Then a little boy playing about the churn, put his hands into it, and pulling it down,
threw all the cream on the floor.
Thus the woman appeared to be a liar, and she being amazed,
took up the child and whipped it sorely: but he reproved her for her lying,
and going out of the house, went away, and that night lay in a stack of hay,
in rain and snow.
The next day he came to York, and the first day of the week being come,
he went to the cathedral; when the priest had done, he said,
he had something from the Lord God to speak to the priest and people.
Then, (said a professor,) say on quickly; for it was very cold weather.
G+++.+++ Fox then told them, '`this was the word of the Lord God unto them,
that they lived in words; but God Almighty looked for fruits among them.`'
As soon as these words were out of his mouth, he was hurried out,
and thrown down the steps.
But he got up again without hurt, and went to his lodging.
Yet several of the people was so reached, that they became convinced of the truth.

He having now done his service in York, went from thence,
and came the next day to Burraby, and going into a certain meeting,
where there was a priest also, he had occasion to declare the truth,
and many were convinced; and the priest himself confessed to the truth,
though he came not to live up to it.
The following day G. Fox passed to Cleaveland, where having a meeting,
some were convinced.
The first day of the next week he went to the steeple-house,
and when the priest had done, he directed the people to their teacher within,
Christ Jesus, who had bought them.
The priest then coming to him, he had little discourse with him,
and put him soon to silence.

From thence he went to Stath, where he had great meetings,
and many received the truth he preached, among whom was Philip Scarth, a priest,
that afterwards came to be a minister of the gospel among those called Quakers,
who now began thereabout to increase in number, and had great meetings.
It happened here, that a certain Scotch priest, walking with G. Fox,
asked him many questions concerning the light and the soul:
to all which he answered fully.
But after they parted, this Scotch priest met Philip Scarth,
and breaking his cane against the ground, said in anger,
'`If ever he met with G. Fox again, he would have his life,
or Fox should have his;`' adding, '`That he would give his head,
if G. Fox was not knocked down within a month.`'
Yet what is marvelous, this same Scotch priest, after some years,
came to be one of the people called Quakers,
and afterwards G. Fox visited him at his house.
Not much unlike to this, was, that a woman of note, among the independents,
being swayed by prejudice against G. Fox, said,
she would willingly have gone to have seen him hanged; but when she heard him preach,
was so reached, that, being convinced of the truth he declared,
she came to be one of his friends.
Oftentimes he had opportunity to speak with the priests, who,
when they heard of his coming would hide themselves; for it was a dreadful thing to them,
when it was told them, the man in leather breeches is come;
for this was indeed his dress in those days, not out of any superstition,
but because leather clothes being strong,
it was not unsuitable for one that travelled so much as he did.

Coming to Malton he had great meetings;
but it was thought such a strange thing to preach in houses,
that many durst not come there, for fear of their relations;
and therefore he was much desired to come and preach in the churches,
as the steeple-houses are commonly called: nay, one of the priests himself, called Boyes,
(who was so taken with him,
that he called him brother,) did invite him to preach in his steeple-house:
but G. Fox had little inclination to that, because both priests and people,
called that place of worship,
'`The house of God;`' whereas the apostle said to the Athenians,
"`God dwelleth not in temples made with hands.`" And
therefore he endeavored to draw people off from them,
and to make them sensible, that God and Christ ought to dwell in their hearts,
that so their bodies might be made the temples of God.
Yet for that time he went into the steeple-house at Malton,
where there was not above eleven hearers, to whom the priest was preaching;
but after it was known in the town that G. Fox was there, it was soon filled with people.
And when the priest had done, he sent the other that had invited him thither,
to bring him up into the pulpit.
But G. Fox sent him word, that he needed not go into the pulpit.
This priest, not satisfied with this refusal, sent again, desiring him to go up unto it,
for, said he, it is a better place to be seen of the people.
But G. Fox answered, that he could be seen and heard well enough where he was;
and that he came not there to hold up such places, nor their maintenance and trade.
This created some displeasure, and it was said,
that false prophets were to come in the last times.
But this saying grieved many of the people, and some began to murmur at it:
whereupon G. Fox stood up, and desiring all to be quiet, he stepped upon a high seat;
and since somewhat had been spoken of false prophets, he declared to the auditory,
the mark of those prophets; and he showed, that they were already come,
and were out of the steps of the true prophets, and of Christ and his apostles.
He also directed the people to their inward teacher, Christ Jesus,
who would turn them from darkness to light.
And having opened divers Scriptures to them,
he directed them to the Spirit of God in themselves, by which they might come to God,
and also to know who the false prophets were.
And having thus had a large time to preach to the people,
he went away without disturbance.

After some time, he came to Pickering,
where the justices held their sessions in the steeple-house,
justice Robinson being chairman.
At the same time G. Fox had a meeting in the school-house,
where many priests and professors came, and asked several questions,
which were answered to their satisfaction: so that many persons, and amongst these,
four chief constables, were convinced that day; and word was carried to Justice Robinson,
that his priest, whom he loved more than all the others, was overthrown and convinced.
After the meeting was done, they went to an inn, and the said priest was very loving,
and would have paid for G. Fox`'s dinner: but this he would not suffer by any means.
Then he offered that he should have his steeple-house to preach in; but he refused,
and told him and the people, that he came to bring them off from such things to Christ.
The next morning he went with the four chief constables to visit justice Robinson,
who meeting him at his chamber door, G. Fox told him,
he could not honor him with man`'s honor: to which the justice said,
he did not look for it.
Then he went into his chamber,
and spoke to him concerning the state of the false prophets, and of the true;
and also concerning election and reprobation,
showing that reprobation stood in the first birth, and election in the second;
and what it was that the promise of God was to, and what the judgment of God was against.
All this so pleased the said Robinson, that he not only confessed it to be truth,
but when another justice that was present made some little opposition, he informed him;
and at their parting, he said to G. Fox,
it was very well that he did exercise that gift which God had given him.
And he took the chief constables aside, and would have given them some money for G. Fox,
saying, he would not have him to be at any charge in this country.
But they told him, that they themselves could not get him to take any money.
G+++.+++ Fox passing from thence, priest Boyes went along with him:
but the year being now come to an end,
let us take a short view how it stood with state affairs.

It hath been said already, that Charles the II. had been crowned king by the Scots,
but having been beaten, with his forces, by Cromwell,
he marched afterwards with a new army into England,
and took Worcester without opposition: yet, in the month of September,
his forces were so entirely routed by Cromwell, that king Charles,
to prevent being taken prisoner after the battle,
hid himself a whole day in a hollow oak, and afterwards, being clothed like a servant,
and called by the name of William, passed the country,
and through many hazards escaped out of England,
and arrived on the coast of Normandy in France:
where we will leave him to return again to G. Fox,
who coming with priest Boyes into a town to bait, and hearing the bells ring,
asked what that was for.
They told him, that it was for him to preach in the steeple-house.
Walking thither, he saw the people were gathered together in the steeple-house yard.
The priest who accompanied him, would have had him to go into the steeple-house;
but he said, it was no matter.
This seemed strange to the people,
that he would not go into that which they called the house of God.
But he stood up in the steeple-house yard, and declared to them,
that he came not to hold up their idol temples, nor their priests, nor their tithes,
nor their Jewish and heathenish ceremonies; that the ground on which their temples stood,
was no more holy than any other piece of ground; that the apostles,
going into the Jews synagogues, and temples, was to bring people off from that temple,
etc. and from the offerings and tithes, and covetous priests of that time;
that such who came to be converted, and believed in Christ,
afterwards met together in dwelling-houses; and that all who preach Christ,
the word of life, ought to preach freely, as the apostles did,
and as Christ had commanded;
and that the Lord God of heaven and earth had sent him to preach freely,
and to bring people off from the outward temples made with hands,
in which God dwelleth not;
that so they might know their bodies were to become the temples of God and Christ.
Moreover, that they ought to leave all their superstitious ceremonies, traditions,
and doctrines of men; and not regard such teachers of the world, that took tithes,
and great wages, preaching for hire, and divining for money;
whom God and Christ never sent, according to their own confession, when they say,
they never heard God`'s voice.
That therefore people ought to come to the Spirit and grace of God in themselves,
and to the light of Jesus in their own hearts:
that so they might come to know Christ their free teacher, to bring them salvation,
and to open the Scriptures to them.
This speech had such effect, that many of them declared they were convinced of the truth.

From this place he went to another town, and priest Boyes went along with him.
Thither came several professors, but he sat silent for some hours;
which made them often ask the priest, '`When will he begin?
When will he speak?`'
To which the priest said,
'`Wait:`' and told them that the people waited upon Christ a long while before he spake:
now, though G. Fox by silence was to famish people from words,
yet at length he felt himself moved to speak, which he did so effectually,
that many were reached, and there was a general convincement amongst them.

From hence he passed on, the priest continuing to go with him, as did several others;
and as they went along, some people called to the priest, and said, '`Mr. Boyes,
we owe you some money for tithes, pray come and take it.`'
But he throwing up his hand, said, he had enough, and would have none of it;
they might keep it; and he praised the Lord he had enough.
At length they came into this priest`'s steeple-house in the moors;
and the priest going before, held open the pulpit door: but G. Fox told him,
he would not go into it.
And this steeple-house being very much painted, he told him and the people,
that the painted beast had a painted house.
Then he spoke to them concerning the rise of all those houses,
and their superstitious ways; and he told them that,
as the end of the apostles`' going into the temples and synagogues,
was not to hold them up, but to bring people to Christ, the substance;
so the end of his coming there, was not to hold up these temples, priests, and tithes,
but to bring them off from all these things, to Christ, the substance.
Moreover, he declared to them what the true worship was, which Christ had set up;
and he distinguished Christ, the true way, from all the false ways;
opening the parables to them, and turning them from darkness to the true light,
that by it they might see themselves and their sins, and Christ their Savior,
that so believing in him, they might be saved from their sins.

After this, he went to the house of one Birdet, where he had a great meeting,
and the priest Boyes accompanied him still, leaving his steeple-house.
Then he returned towards Crantsick, to Captain Pursloe`'s, and Justice Hotham`'s,
who received him kindly, being glad that truth was spread, and so many had received it.
And Justice Hotham said, '`If God had not raised up this principle of light and life,
which G. Fox preached, the nation had been overrun with Ranterism,
and all the justices in the nation could not have stopped it with all their laws:
because, (said he,) they would have said as we said, and done as we commanded,
and yet have kept their old principle still:
but this principle of truth overthrows their principle,
and the root and ground thereof.`'

Now, though G. Fox found good entertainment, yet he did not settle there,
but kept in continual motion, going from one place to another, to beget souls unto God.
I do not intend to relate all his occurrences,
but will give a short hint only of some of the chief.

Coming then towards night into Patrington, he walked through the town,
and meeting the priest in the street, he warned both him and the people to repent,
and turn to the Lord.
And people gathering about him, he declared to them the word of life,
directing them to the inward word, viz. the light wherewith they are enlightened.
Going afterwards to an inn, for it was dark, he desired lodging, but it was denied him:
then he asked for a little meat, or milk, offering to pay for it;
but this also was refused him.
Being thus put off, he walked out of the town, and some rude fellows following,
asked him, '`What news?
To which his answer was, '`Repent, and fear the Lord.`'
After he was gone a pretty way out of the town, he came to another house,
where he desired to have some meat, drink, and lodging, for his money,
but they would not suffer him to stay there: then he went to another house,
but met with the like refusal.
By this time it was grown so dark, that he could not see the highway,
but perceiving a ditch, he found a little water,
and so refreshed himself Then he got over the ditch, and being weary,
sat down amongst the furze bushes, till it grew day; and then he arose,
and passing on through the fields, a man came after him with a pike-staff,
and went along with him to a town, where he raised the people,
with the constable and chief constable, before the sun was up.
G+++.+++ Fox seeing the multitude,
warned them of the day of the Lord that was coming upon all sin and wickedness,
and exhorted them to repent.
But they laying hold on him, carried him back to Patrington,
and guarded him with halberts, pikes, staves, etc.
Being come to the said town, all was in an uproar;
and the priest and constables consulting together what to do with him,
lie took that opportunity to exhort the people to repentance,
and to preach the word of life to them.
At last a discreet man called him into his house, where he got some milk and bread,
not having eaten for some days before.
Then he was carried about nine miles to a justice; and when he was come near his house,
there came a man riding after, and asked him whether he was the man that was apprehended.
G+++.+++ Fox asking him, why?
the other said, '`For no hurt.`'
Then he told him, he was; and so the man rode away to the justice.

Now the men that guarded G. Fox, said, it would be well,
if the justice was not drunk when they came to him, because he used to be drunk early,
G+++.+++ Fox being brought in before him, and not putting off his hat, and saying _thou_ to him,
the justice asked the man that rode thither before, whether he was not mazed or fond?
But the man said, "`No: it is his principle so to behave himself G. Fox,
who was unwilling to let any opportunity slip, without admonishing people to virtue,
warned the justice to repent,
and bid him come to the light which Christ had enlightened him with,
that by it he might see all his evil words and actions, and so return to Christ Jesus,
whilst he had time, and that he ought to prize that time.
'`Aye, aye,`' said he, '`the light that is spoken of in the third of John.`'
G+++.+++ Fox desired him that he would mind it, and obey it; and laying his hand upon him,
he was so brought down by the Lord`'s power, that all the watchmen stood amazed.
Then he took G. Fox with him into a parlor, with the other men,
and desired to see what he had in his pockets, of letters, or intelligence;
for it seems they suspected him to be an enemy to the Commonwealth.
Then he pulled out his linen, and showed that he had no letters;
which made the justice say, '`He is not a vagrant, by his linen.`'
and set him at liberty.
Then G. Fox went back to Patrington again,
with that man who had rid before to the justice, and who lived in that town.
Coming to his house, he desired G. Fox to go to bed, or to lie down upon it;
which he did, that they might say, they had seen him in a bed, or upon a bed;
for there was a report, that he would not lie on any bed, raised doubtless,
because about that time he had lain often without doors.

When the First-day of the week was come, he went to the steeple-house,
and declared the doctrine of Truth to the priest and people, without being molested.
Then presently after, he had a great meeting at that man`'s house where he lay,
and many were convinced that day of the truth he preached;
and they were exceeding sorry that they had not given
him lodging when he was there before.
From thence he travelled through the country, warning people,
both in towns and in country villages, to repent,
and turn to Christ Jesus their teacher.

On a First-day of the week he came to one colonel Overton`'s house,
and had a great meeting of the chief of the people of that country;
where he opened many things out of the Scriptures, which they never heard before.
Coming afterwards again to Patrington,
he understood that a tailor and some wild blades in that town,
had occasioned his being carried before the justice.
This taylor came to ask him forgiveness, fearing he would complain of him;
the constables also were afraid lest he should trouble them; but he forgave them all,
and exhorted them to turn to the Lord, and to amend their lives.
Now that which made them the more afraid, was,
that he having been not long before in the steeple-house at Oram,
there came a professor that gave him a push on the breast,
and bid him get out of the church.
To which G. Fox said, '`Dost thou call the steeple-house the church?
The church is the people, whom God hath purchased with his blood, and not the house.`'
But justice Hotham having heard of this man`'s thus abusing G. Fox, sent a warrant,
and bound the said man over to the sessions.
So zealous was this justice to keep the peace, that he had asked G. Fox before,
whether any people had abused him: but he esteeming it his duty to forgive all,
told him nothing of that kind.

From Patrington he went to several great men`'s houses, warning them to repent.
Some received him lovingly, and some slighted him.
Passing thus through the country, at night he came to another town,
where he desired lodging and meat, offering to pay for it; but they would not lodge him,
unless he went to a constable to ask leave, which they said was the custom of strangers.
But he told them, that custom was for suspected persons, and not for such as he,
who was an innocent man.
So after he had warned them to repent, and to mind the day of their visitation,
and directed them to the light of Christ, and Spirit of God, he passed away.
As it grew dark, he spied a hay-stack, and went and sat under it till morning.
The next day he came to Hull, where he admonished the people to turn to Christ Jesus,
that they might receive salvation.
And being very weary with traveling on foot so far, he got that night a lodging there.

From thence he went to Nottinghamshire, visiting his friends there;
and so passed into Lincolnshire, where he did the like.
And coming to Gainsborough, where one of his friends had been preaching in the market,
he found the town and people all in an uproar; the more,
because a certain man had raised a false accusation, reporting,
that G. Fox had said he was Christ.
Here going into the house of a friendly man, the people rushed in after him,
so that the house soon was filled; and amongst the rest was also this false accuser,
who said openly before all the people, that G. Fox said he was Christ;
and that he had got witnesses to prove the same.
G+++.+++ Fox kindled with zeal, stepped upon the table, and said to the people,
that Christ was in them, except they were reprobates; and that it was Christ,
the eternal power of God, that spoke in him at that time unto them;
not that he was Christ.
This gave general satisfaction, except to the false accuser himself, to whom G. Fox said,
that he was a Judas, and that Judas`'s end should be his,
and that that was the word of the Lord through him, (Fox,) to him.
The minds of the people coming thus to be quieted, they departed peaceably.
But very remarkable it was: this Judas shortly after hanged himself,
and a stake was driven into his grave.
Now, though this was a well known thing in this country,
yet some priests Spread a report, that a Quaker had hanged himself in Lincolnshire,
and had a stake driven through him.
And though this was taken upon trust by hearsay, yet, out of mere malice,
a certain priest gave out this falsehood in print, as a true matter.
But this wicked slander prevailed so little,
that many people in Lincolnshire were convinced of the truth preached by G. Fox.

After this he passed into Yorkshire, and coming to Warnsworth,
went to the steeple-house in the forenoon, but found no acceptance; and being thrust out,
he was sorely beaten with staves, and clods and stones were thrown at him;
yet he exhorted to repent, and turn to Christ.
In the afternoon he went to another steeple-house;
but the sermon was finished before he got thither;
so he preached repentance to the people that were not departed,
and directed them to their inward teacher, Christ Jesus.
From hence he came to Doncaster, where he had formerly preached in the market;
but now on the First-day of the week he went into the steeple-house;
and after the priest had done, he began to speak, but was hurried out,
and hauled before the magistrates, who threatened him with death,
if ever he came thither again.
But notwithstanding all this, G. Fox bid them mind the light of Christ in them, saying,
that God was come to teach his people himself, whether they would hear or not.
After a while, being put out with some of his friends that were with him,
they were stoned by the rude multitude.
A certain innkeeper, that was a bailiff, seeing this, came and took them into his house,
but one of the stones that were thrown hit his head, so that the blood ran down his face.
The next First-day G. Fox went to Tickhill; where he went into the steeple-house,
and there found the priest and the chief of the parish in the chancel,
to whom he began to speak; but they immediately fell upon him,
and the clerk struck him with his bible so violently on the face,
that the blood gushed out, and he bled exceedingly.
Then the people thrust him out of the steeple-house, beat and threw him down,
and dragged him along the street, so that he was besmeared with blood and dirt,
and his hat taken away.
When he was got up again, he spoke to the people,
and showed them how they dishonored Christianity, Some time after, the priest coming by,
scoffingly called G. Fox and his friends, Quakers.
But he was spoken to, in such an authority and dread, that he fell a trembling;
which made one of the people say, '`Look how the priest trembles and shakes,
he is turned a Quaker also.`'
Some moderate justices now, hearing how G. Fox and his friends had been abused,
came to examine the business; and the clerk was afraid of having his hand cut off,
for striking him in the church: but G. Fox, as a true Christian, forgave him,
and would not appear against him.

Thus far G. Fox only hath been mentioned as a preacher of repentance;
but now some others of his persuasion began also to preach publicly, viz. Thomas Aldam,
Richard Farnsworth, and, not long after, William Dewsbury.
This made such a stir,
that the priest of Warns-worth procured a warrant from the justices against G. Fox,
and Thomas Aldam.
The constable who came with this order which was to be executed
in any part of the West Riding of Yorkshire,
took Thomas Aldam, and carried him to York, and G. Fox went with him twenty miles;
but though the constable had a warrant for him also, yet he meddled not with G. Fox,
saying, he was loth to trouble men that were strangers;
but Thomas Aldam was his neighbor.
About this time Richard Farnsworth went into an eminent steeple-house,
in or about Wakefield; where he spoke so powerfully, that the people were amazed.
The priest of that place, whose name was Marshal, spread a slanderous report,
that G. Fox carried bottles about with him, and made people drink thereof,
which made them follow him.
And that he rid upon a great black horse, and was seen in one country upon that horse,
and in the same hour in another country three score miles off.
But these horrid lies were so far from turning to the priest`'s advantage,
that he preached many of his hearers away from him;
for it was well known that G. Fox had no horse at that time, but travelled on foot.
He coming now into a steeple-house not far from Bradford;
the priest took his text from Jer. 5:31. "`My people
love to have it so;`" leaving out the foregoing words,
"`The prophets prophesy falsely,
and the priests bear rule by their means.`" G. Fox unwilling to let this pass unregarded,
showed the people the priest`'s unfair dealing; and, directing them to Christ,
the true inward teacher, declared, that God was come to teach his people himself,
and to bring them off from all the world`'s teachers and hirelngs,
that they might come to receive freely from him;
concluding his speech with a warning of the day of
the Lord that was coming upon all flesh.
He passed from thence without much opposition,
and travelled now for some time with Richard Farnsworth:
with whom he once passed a night in the open field, on a bed they made of fern.

Then parting from him, he came to Wentzerdale, where he went into the steeple-house;
and after the lecture,
he spoke to the people much in the same terms as he used to do on the like occasions;
and had not much opposition there.
Thus he went from place to place, and often met with strange occurrences,
some of which were more jocose than serious; others very rude,
and even dangerous to his life.
But he trusted in God, really believing that he had sent him to preach repentance,
and to exhort people to a true conversion.

Thus traveling on, he came near Sedbergh; there he went to a meeting at Justice Benson`'s,
where a people met that were separated from the public worship; and,
by his preaching he gave such general satisfaction,
that most of the hearers were convinced of the Truth declared by him.
Thus the number of his fellow-believers increased so,
that now they had meetings by themselves, in many places of the country.

About this time there being a fair at Sedbergh,
G+++.+++ Fox declared the day of the Lord through the fair;
and afterwards went into the steeple-house yard, where abundance of people came to him:
here he preached for several hours, showing,
that the Lord was come to teach his people himself,
and to bring them off from all the world`'s ways and teachers, to Christ,
the true teacher, and the true way to God.
Moreover, he showed the declining state of the modern doctors and teachers;
and exhorted the people to come off from the temples made with hands,
and wait to receive the Spirit of the Lord,
that they might know themselves to be the temples of God.
None of the priests, several of whom were there, spoke against what he had declared;
but a captain said, '`Why will ye not go into the church;
for this is not a fit place to preach in?`'
G+++.+++ Fox told him,`'That he did not approve of their church.`'
Then stood up one Francis Howgill, who was a preacher,
and though he never had seen G. Fox before, yet he was so affected with him,
that he answered the captain, and soon put him to silence: for, said Howgill,
'`This man speaks with authority, and not as the scribes.`'
After this, G. Fox opened to the people,
'`That that ground and house was not more holy than another place;
and that the house was not the church, but the people,
whom Christ was the head of,`' Then the priests coming to him he warned them to repent;
upon which one of them said, he was mad; but notwithstanding his saying so,
many were convinced there that day; and amongst these, one Captain Ward.

The next First-day G. Fox came to Firbank chapel in Westmoreland,
where the said Francis Howgill, and one John Audland, had been preaching in the morning.
The chapel at that time was so full of people, that many could not get in:
and Howgill said afterwards, he thought G. Fox looked into the chapel,
and his spirit was ready to fail.
But G. Fox did not look into it; however,
Howgill had been so reached when he heard him preach in the steeple-house yard at Sedbergh,
that he was as it were, checked, and so quickly made an end of his sermon;
thinking as well as others, that G. Fox would preach there that day, as indeed he did.
For having refreshed himself at noon, with a little water out of a brook,
he went and sat down on the top of a rock hard by the chapel,
intending to have a meeting there.
At this people wondered, because they looked upon the church,
(so called,) as a holy place, requisite for worship.
But G. Fox told them afterwards, that the ground whereon he stood,
was as good as that of the steeple-house; besides, we find,
that Christ himself did preach on a mountain, and also at the seaside.
Now in the afternoon, the people gathered about him, with several of their preachers,
and amongst these, F. Howgill, and John Audland.
To this auditory, which was judged to consist of more than a thousand people,
G+++.+++ Fox began to preach, and spoke about the space of three hours,
directing all to the Spirit of God in themselves,
that so they might be turned from darkness to light, and from the power of Satan,
which they had been under, unto God; by which they should become children of the light,
and, by the Spirit of Truth, be led into all truth;
and so sensibly understand the words of the prophets of Christ, and of the apostles,
and come to know Christ to be their teacher to instruct them,
their counsellor to direct them, their shepherd to feed them,
their bishop to oversee them, and their prophet to open divine mysteries to them;
that so their bodies might be prepared, sanctified,
and made fit temples for God and Christ to dwell in.
Moreover he explained the prophets, and the figures, and shadows,
and directed his hearers to Christ the substance.
He also opened the parables and sayings of Christ,
and showed the intent and scope of the apostles`' writings, and epistles to the elect.
Then he spoke also concerning the state of apostasy,
that hath been since the apostles`' days; how the priests had gotten the Scriptures,
without being in that spirit which gave them forth;
and how they were found in the steps of the false prophets, scribes,
and Pharisees of old, and were such as the true prophets, Christ,
and his apostles cried against;
insomuch that none that were guided by the Spirit of God now could own them.

Whilst G. Fox was thus preaching, many old people went into the chapel,
and looked out at the windows, thinking it a strange thing to see a man preach on a hill,
and not in the church,
(as they called it.) He perceiving this said,`'That the steeple-house,
and the ground whereon it stood, was no more holy than that hill; and that those temples,
which they called the dreadful houses of God,
were not set up by the command of God and Christ;
nor their priests instituted as Aaron`'s priesthood was;
nor their tithes appointed by God, as those amongst the Jews were;
but that Christ was come, who ended both the temple, and its worship,
and their priests and their tithes; and that therefore all ought to hearken unto him;
for he said, "`Learn of me;`" and God said of him, "`This is my beloved Son,
in whom I am well pleased, hear ye him.`" In conclusion, he said,
'`That the Lord God had sent him to preach the everlasting gospel,
and word of life amongst them; and to bring them off from all these temples, tithes,
priests, and rudiments of the world, which were gotten up since the apostles`' days,
and had been set up by such as had erred from the spirit and power the apostles were in.`'
Thus preached G. Fox,
and his ministry was at that time accompanied with such a convincing power,
and so reached the hearts of the people, that many,
and even all the teachers of that congregation, who were many,
were convinced of that Truth which was declared to them.

After this meeting was over, G. Fox went to John Audland`'s who,
as well as Francis Howgill, and others,
had been quite brought over by his effectual preaching.
And as these had been zealous preachers amongst those of their former persuasion,
so it was not long before they became publishers of that doctrine, which now,
by the ministry of G. Fox they had embraced;
and were so far from approving their former service,
that they gave back the money they received for their
preaching to the parish of Colton in Lancashire;
being now resolved to give freely what they had received freely.
And here I shall make some small digression,
in saying something concerning these two excellent men.

John Audland was a young man, and of a comely countenance, and very lovely qualities.
When he was but seventeen or eighteen years old, he was very religious,
and a zealous searcher of the Holy Scriptures; and having a good understanding,
and strong memory, he thereby gathered a large treasure of Scripture learning,
became an eminent teacher among the Independents, and had a very numerous auditory.
But when he heard G. Fox preach, he was thereby so reached to the heart,
that he began in process of time to see the emptiness of his great literal knowledge,
and that all his righteousness was but as filthy rags.
This brought him to a state of mourning,
for now he saw that all his profession and wisdom could not bring him to true happiness.
But the Lord, who doth not break the bruised reed, nor quench the smoking flax,
did pity him in this state of deep humiliation,
and bore him up again by his supporting power;
whereby in time he came to be prepared for that service he was appointed to by God.

Concerning Francis Howgill; he was also a religious man, who,
having seen the superstitions of the Episcopal church, had left it,
and applied himself to the Independents.
But although he, who had been trained up in the university to be a minister,
became a teacher amongst the independents, and was zealous in virtue:
yet he remained dissatisfied in himself, finding that notwithstanding all his fasting,
praying, and good works, the root of sin still remained in him;
and although the common doctrine was,
that Christ had taken the guilt of sin upon himself, yet this could not satisfy him;
because his conscience told him, "`His servant thou art,
whom thou obeyest.`" Thus increasing in understanding,
it was resolved to him that the Lord according to what the prophets had foretold,
would teach his people himself; and it seemed also to him,
that this time was near at hand.
Some while after it happened, as hath been said already,
that he was present when G. Fox preached, and when he heard him say,
that the light of Christ in man, was the way to Christ,
he believed this to be the word of truth;
and he saw how he had been ignorant of the principle of true religion.
Submitting then to the reproofs of this inward light,
he saw the unfruitfulness of all his labor, and anguish and sorrow seized on him,
and judgment went over all his former actions.
But he being given up, and resigned in that state, saying within himself, '`Thou, O God,
art just in all thy judgments,`' it pleased the Lord
in due time to fill his heart with joy,
and to make him a minister of his everlasting word.
But no sooner did he enter into that service, but both priests and magistrates,
of whom he formerly had been beloved, became his enemies;
and envy was so kindled against him, that he was locked up in a nasty place at Appleby,
in Westmoreland, and was kept there prisoner for some time.

But let me now return to G. Fox, who coming to Kendal,
had a meeting there in the town hall; where declaring the word of life,
he showed the people how they might come to the saving knowledge of Christ,
and to have a right understanding of the Holy Scripture;
opening to them what it was that would lead them into the way of reconciliation with God,
This was of such effect, that several became convinced of the truth published by him;
and others were so well affected to him, that when he went to Under-Barrow,
several people accompanied him, and he had great reasonings with them,
but especially with one Edward Burrough, who, though of extraordinary parts,
and acquired knowledge, was not able to withstand the efficacious sayings of G. Fox.
And because this Burrough became an eminent man among the Quakers, so called;
being endued with courage and understanding, fit to overcome his opposers,
and to break even stony hearts; I will mention here a little of his descent and quality.

He was born in the barony of Kendal, in Westmoreland,
of parents who for their honest and virtuous life, were in good repute;
he was well educated and trained up in such learning as that country did afford.
His knowledge and understanding soon passed his years;
for being but a boy he had the spirit of a man,
and in his youth was endued with wisdom above his equals in years.
Moreover, he was very religious,
conversing frequently with those that were in esteem for piety and godly life.
Neither was he inclined to the ordinary pleasures of youth;
but it was his delight to be exercised in reading of Holy Scripture,
wherein he was well versed.
By his parents he was trained up in the Episcopal worship;
yet when but twelve years of age, he often went to the meetings of the Presbyterians,
because their doctrine in many things seemed to him to approach nearer to truth,
than that of the public church; wherefore he became a follower of the Presbyterians,
although he was reviled for it by his acquaintance.
But being come to the age of about seventeen years,
and growing more and more sensible of his own condition, he was often struck with terror;
and when he had been praying, he heard, as it were, a voice`' Thou art ignorant of God;
thou knowest not where he is, nor what he is; to what purpose is thy prayer?`'
This brought him under such a concern, that he began to take diligent heed to his life,
so that he abstained not only from all vanities, but, when occasion offered,
he reproved others for their vain conversation and wickedness;
but for this he was derided and looked upon scornfully by many,
yet continued to live religiously, and felt sometimes sweet refreshments to his soul.
But though he had the Truth in his comprehension,
yet he wanted the real and experimental knowledge of it, and so became darkened again,
losing what he once possessed: and being too ready to flatter himself, would say,
'`Whom God loves once, he loves forever.`'
Now he grew weary of hearing any of the priests;
for he saw they did not possess what they spoke of to others;
and sometimes he began to question his own experience.
Being thus many times put to a stand, he seemed almost to be at a loss.
In this condition he heard G. Fox preach, and afterwards reasoned with him;
and it pleased the Lord so to open his understanding, that he perceived,
(as he relates himself,) that he was in the prodigal state, above the cross of Christ,
and not in the pure fear of the Lord.
Being thus convinced, he entered into the society of the despised Quakers,
though he was now rejected by his relations, and, by a blind zeal,
turned out of his father`'s house.
This he bore patiently, and continued faithful in the doctrine he had embraced.
And in process of time he so advanced in true knowledge,
that he became a very eminent minister of the gospel.
But what adversities did he not undergo?
Reviling, slandering, buffeting, and caning, were often his lot;
watching and fasting were many times his portion; and imprisonments, great jeopardies,
and danger of life, he was not unacquainted with.
But nothing could make this hero shrink: he always was laborious,
and seldom had any hours of rest.
In his preaching he was very acceptable, and eloquent in his speech, and had the tongue,
(according to what an eminent author relates,
that knew him from his youth,) of a learned orator,
to declare himself to the understandings and consciences of all men he met with.
He was also a great writer,
and often would engage in disputes with those of other persuasions, sparing no pains,
where he thought he could serve the Lord and the church.
Thus much, for this time, of E. Borrough.

Let us return now to G. Fox, whom we left at Under-Barrow, where,
with the consent of the inhabitants, he had a great meeting in the chapel,
and many were convinced, and received the truth preached by him.
From thence he went to Lancashire,
and having in some places spoken in the steeple-houses, he came to Ulverstone,
and so to Swarthmore, to the house of Thomas Fell, a Judge in Wales,
where many priests frequently came.
The judge was at that time abroad, employed in the exercise of his office,
and his wife Margaret was also gone abroad that day.
G+++.+++ Fox in the meanwhile coming thither, met the priest William Lampitt,
who was a high notionist, and rich in words.
But G. Fox soon perceiving that he was without the possession of what he professed,
opposed him boldly.
Before it was night, Margaret Fell returned home,
and her children told her that Lampitt and Fox had disagreed,
which did somewhat trouble her, for she,
making much of the priests especially admired Lampitt.
That same night G. Fox had much reasoning there,
and declared the Truth to her and her family.
The next day Lampitt came again,
and G. Fox discoursed with him in the presence of Margaret Fell,
who then began clearly to discern the priest.

The following day being appointed for a humiliation,
Margaret went with her children to the steeple-house at Ulverstone,
having asked G. Fox before to go with her: but he replying,
That he must do as he was ordered by the Lord, left her, and walked into the fields;
and there he felt a strong motion to go also to the steeple-house.
When he came there, the people were singing, but what they sung was,
according to his opinion, altogether unsuitable to their states.
After they had done, he stepped up on a form, and asked leave to speak:
the priest consenting, G. Fox began thus: '`He is not a Jew that is one outwardly;
neither is that circumcision which is outward: but he is a Jew that is one inwardly;
and that is circumcision, which is of the heart.`'
And so he went on, and said, '`That Christ was the light of the world,
and enlightened every man that cometh into the world,
and that by this light they might be gathered to God,`' etc.
Margaret Fell standing up in her pew, wondered at this doctrine,
having never heard any such before.
In the meanwhile G. Fox went on, and opening the Scriptures, said,
'`That they were the prophet`'s words, and Christ`'s, and the apostles`' words;
and that what they spoke, they enjoyed and possessed, and had it from the Lord.
What have any to do, said he, with the Scriptures,
if they come not to the Spirit that gave them forth?
You will say, Christ saith this, and the apostles say this; but what canst thou, O man,
say thyself concerning this?
Art thou a child of the light; dost thou walk in the light,`' and what thou speakest,
is it inwardly from God?`'
He showed also, "`That God was come to teach his people himself by his Spirit,
and to bring them off from their churches, and religions,
and their ways of worship,`' etc.
These his words did so effectually reach the aforesaid Margaret,
that she sat down in her pew again, and weeping bitterly,
cried in her spirit to the Lord, '`We are all thieves!
We are all thieves!
We have taken the Scriptures in words, and know nothing of them in ourselves.`'
G+++.+++ Fox still going on, declared against the false prophets, and said,
that their way of worship was but talking of other mens`' words,
and that they themselves were out of the life and
spirit which those were in who gave them forth.
Then cried out a justice of peace, called John Sawrey,`' Take him away.`'
But Margaret Fell said to the officers,`' Let him alone.
Why may not he speak as well as any other?`'
Priest Lampitt, it is like to please her, said also, '`Let him speak.`'
G+++.+++ Fox then speaking yet awhile, was at length led out by the constable,
according to the order of the said justice Sawrey;
and then he spoke to the people in the graveyard.

In the evening he came again into the house of judge Fell,
where he took occasion to speak to the servants, and those of the family,
who most of them came so effectually to be convinced by him,
that they embraced the Truth which he preached.
Among these, was also William Caton, of whom more hereafter.
Margaret Fell in the meanwhile being come home, was so reached,
that she scarce knew what to do, her husband being from home;
for she clearly perceived what she had heard G. Fox preach, was truth.

The First-day after, he went to Aldenham steeple-house, where, when the priest had done,
he spoke to the people, and admonished them to return to the Lord.
From thence he went to Ramside, where was a chapel, in which one Thomas Lawson,
who was an eminent priest, used to preach; who having some notice of G. Fox`'s coming,
preached in the morning,
and told the people that G. Fox was to come there in the afternoon;
by which means very many people were gathered together.
When he came,
he saw there was no place so convenient to speak to the people as the chapel,
and therefore he went into it.
The priest Lawson, willing to give a full opportunity to G. Fox,
went not up into the pulpit, but left all the time to him.
And G. Fox so powerfully declared the doctrine of Truth, that many received it,
and among these, the priest himself, who left off his preaching for hire,
and in process of time, came to preach the Lord Jesus Christ,
and his glorious gospel freely;
which however did not hinder him to exercise himself in the knowledge of herbs,
wherein he came to be so experienced, that he was, as I have been told,
one of the most skillful herbalists in England;
which gave occasion to an eminent botanist, who at first seemed a little shy of him,
when he perceived his great skill, to love him as a singular friend.
But this transiently.

Now I return again to G. Fox, who having performed his service about Ram side,
went somewhere else, and came also to Brerecliff,
where he found some people that told him, they could not dispute.
But he bid them to fear the Lord, and not to speak the words of God in an airy manner,
but to do the things required.
Moreover, that they ought to mind the light of Christ,
and take heed to his Spirit in their hearts,
whereby they would come to see their evil thoughts, words, and actions; for this light,
(he said,) would show them their sins, and by following this light,
they should also see that their Savior Christ Jesus, saved them from sin: and he said,
the first step to peace was to stand still in the light,
which showed them their sins and transgressions;
by which they should see they were in the fall of the old Adam, in darkness and death,
alienated from the covenant of the promise, and without God in the world;
and that Christ who died for them, was their Savior and Redeemer, and their way to God.
After G. Fox had spoken thus, he went to a new built chapel near Gleaston,
wherein none had yet preached: hither came a great many people, unto whom he preached,
and many were convinced.

From thence he returned to Swarthmore again; for Margaret Fell being full of fear,
and expecting her husband`'s return home, had desired G. Fox to come,
since some of the great ones of the country, being gone to meet her husband,
had informed him, that a great disaster had befallen the family:
and that the Quakers were witches, and had turned them from their religion;
and that he must send them away, or all the country would be undone.
Without all question, this was a very sad message to judge Fell,
for he came home greatly offended:
and one may easily think what a condition his wife was in,
being in fear that she should either displease her husband, or offend God.

At that time Richard Farnsworth and James Nayler were at her house,
and she desired them to speak to her husband; which they did very moderately and wisely:
and though at first he was displeased, yet after he had heard them speak,
he was better satisfied.
And they making as if they would go away, she desired them to stay,
because she expected G. Fox that evening; and she wished for an opportunity,
that both he and they might speak to her husband,
whereby he might satisfy himself further about them.
Dinner in the meantime being ready, judge Fell, and his wife Margaret, sat down at table,
and whilst they were sitting, an extraordinary power seizing on her,
made such an operation on her mind, that he was struck with amazement,
and knew not what to think of it; but he was quiet and still;
and the children also were become so grave and modest,
that they could not play on their music they were learning.
At night G. Fox came, and judge Fell sitting in the parlor,
Margaret asked him if G. Fox might come in; and he said, '`Yes.`'
George then coming in without any compliment, began to speak presently;
at which the family, as well as J. Nayler, and R. Farnsworth, entered.
He now speaking, declared what the practice of Christ and the apostles was in their day;
and showed how the apostasy came in since;
and what was the practice of the modern priests in the apostasy.
He also answered all the objections of judge Fell,
and so thoroughly satisfied him by the Scriptures,
that the was convinced in his judgment,
and asked if he was that George Fox whom justice Robinson had spoken
so much in commendation of amongst many of the parliament men?
To this G. Fox answered him,
that he had been with the justices Robinson and Hotham in Yorkshire;
that they had been very civil and loving to him,
and that they were convinced in their judgments by the Spirit of God,
that the principle he bore testimony to was the Truth;
and that they saw beyond the priests of the nation.`'
All this so satisfied judge Fell, that he was very quiet that night, and went to bed.
The next morning came Lampitt, the priest of Ulverstone,
and walking with the judge into the garden, spoke much to him there,
to render the doctrine of the Quakers odious to him, having also said to others,
that G. Fox held strange notions.
But judge Fell had seen the night before so much,
that the priest got little entrance upon him.
And when Lampitt came into the house again, G. Fox spoke sharply to him, and asked him,
when God spake to him, and called him to preach to the people.
The priest not liking such questions, it was not long before he went away.
And whilst some were speaking how several in those
parts were convinced of the Truth now declared,
and that they knew not where to get a meeting place; judge Fell hearing them,
said of his own accord, '`You may meet in my hall, if you will.`'
So the next First-day there was at his house a meeting, and a large one indeed,
being the first meeting of the people called Quakers, that was at Swarthmore;
and so it continued to be kept there until the year 1690,
when a new meeting-house was built there.
Judge Fell not being willing to appear in that meeting,
went that day to the steeple-house, and none with him but his clerk and his groom.
Yet in process of time he came to be so well affected to the doctrine of the Quakers,
so called, that though he did not enter publicly into their society, yet he loved them,
and several years before his death, did not frequent the steeple-house any more.

After G. Fox had stayed some days at the house of judge Fell, he went to Lancaster,
and there preached in the market; and on the next First-day,
had a great meeting in the street, amongst the soldiers, to whom he declared the Truth;
and in the afternoon went to the steeple-house; but speaking there,
and directing people to the Spirit of God, he was hauled out,
and stoned along the street.

Then having travelled about some time, and preached in some places,
sometimes with rude opposition, he returned to Swarthmore,
where discoursing with several priests at judge Fell`'s house, he asked them,
whether any of them ever heard the voice of God or Christ,
commanding them to go to any people, and declare the word of the Lord to them.
But none of them answered this with Yea: yet one saying,
'`I can speak of my experience as much as you;`' G. Fox told him experience was one thing,
but to go with a message, and to have the word of the Lord,
as the prophets and apostles had, was quite another.
An ancient priest, whose name was Thomas Taylor,
did ingenuously confess before judge Fell, that he had never heard the voice of God,
nor of Christ, but that he spoke his experiences,
and the experiences of the saints in former ages.
This very much confirmed judge Fell in the persuasion he had already,
that the priests were not what they pretended to be: for he had thought,
as the generality of the people did then, that they were sent from God.
At this time,`'the saying of G. Fox wrought so close on the mind of the said T. Taylor,
that he was convinced, and travelled with him into Westmoreland;
and coming into Crossland steeple-house, T. Taylor`'s mouth was opened,
so that he declared amongst the people, how lie had been before he was convinced;
and like the good scribe, brought forth things new and old from his treasury,
to the people; and showed them how the priests were out of the way.

Now great rage arose among the priests, and they began as much as they could,
to stir up to persecution;
for not only T. Taylor after some time preached the gospel freely, but several others,
viz. John Audland, Francis Howgill, John Camm, Edward Burrough, Richard Hubberthorn,
Miles Halhead, and others, appeared zealous preachers among those called Quakers;
and often declared the doctrine they professed in steeple-houses, and markets;
whereby the number of their friends began greatly to increase.
