== Chapter III.

=== 1652-1654

[.chapter-synopsis]
* Impropriety of calling places of worship Churches
* Great cruelty of the people at Walney
* G. Fox accused of blasphemy
* G. Fox cleared in open session
* Several persons of note convinced
* Number of preachers among Friends
* G. Fox foretells the dissolution of the long Parliament
* Several hundreds convinced at one time
* G. Fox committed to prison as a blasphemer
* J. Parnel
* M. Halhead
* Cruel persecution of M. Halhead
* Remarkable occurrence to M. Halhead`'s wife
* Effect of M. Halhead`'s presence on two priests
* R. Widders
* Means by which Quakers became so numerous
* Why they visit Steeple houses
* G. Fox travels into the north of England
* John ap John sent to prove the Quakers
* Cromwell declared Protector

In the meanwhile G. Fox returned into Lancashire, and went to Ulverstone,
where Lampitt before mentioned was priest.
He now seeing how the people called Quakers did set up meetings,
and met in private houses, said they forsook the temple,
and went to Jeroboam`'s calves houses; whereas formerly he had preached of a people,
that would own the teachings of God,
and that men and women should come to declare the gospel.
Now it was told him, that the old mass houses, which were called churches,
were more like Jeroboam`'s calves houses;
though man strove to persuade people that such a building was the house of God:
whereas Christ was the head of the church, and never was called the head of an old house;
and that the apostle speaking of Christ said,
"`Whose house we are,`" Heb. 3:6. This passage puts me in mind,
how some of the parliament soldiers, observing, over some of the steeple-house doors,
these words of the patriarch Jacob, when God had appeared to him in a dream,
'`This is none other but the house of God,
and this is the gate of heaven,`' could not endure
to see this gross conceit concerning those buildings,
but rased out the words, '`of God,`' and '`of heaven;`' so that nothing was left,
but '`This is none other but the house,
and this is the gate:`' and certainly their zeal was
more reasonable that the conceit of those,
who think that in the gospel days a building of lime and stone,
may be called the house of God.
It seems also a silly conceit, to call a meeting-house, furnished with a steeple,
a church; and to deny that name to the congregation-houses of dissenters, calling them,
and them only, meeting-houses.
But this notion hath kept up the esteem of those mass-houses; and the priests,
that they might not lose their gain of burials,
have endeavored to keep people in the belief,
that the ground of these buildings was holy;
and this gave occasion to the people called Quakers, to call those buildings,
steeple-houses.
Now since a fantastical man I very well knew in Holland,
conversing there among the people of that persuasion,
undertook to translate that denomination into Dutch, Gespitate hyyzen,
it gave occasion to some Latin writers in Germany, to complain,
that the Quakers scornfully called their temples __Domus acuminates.__^
footnote:[Steeple-house]
And though Croese says also in [.book-title]#Historia Quauriana# concerning them,
__Templa cuncti Quakeri contumeliose vocabant cedes pyramidatas,__^
footnote:[All the Quakers contemptuously called churches steeple-houses.]
yet he knew better.
But this digression has led me off from G. Fox, whom I left at Ulverstone,
where he went to the steeple-house whilst priest Lampitt was preaching.
And when G. Fox began to speak, John Sawrey the justice came to him, and said,
if he would speak according to the scriptures, he should speak.
G+++.+++ Fox told him he should speak according to the Scriptures,
and bring the Scriptures to prove what he had to say.
But then Sawrey, contradicting himself, said he should not speak;
and incensing the people against him, they fell upon G. Fox, knocked him down,
kicked him, and trampled upon him.
At last Sawrey came, took him from the people, and led him out of the steeple-house,
bidding the constables to whip him.
Then he was dragged out of the town and given up to the rage of the rude multitude,
who did so terribly beat him with switches and staves, that at length fainting,
he fell down upon the wet common; but recovering again,
and being strengthened by an immediate power, he stood up, and stretching out his arms,
said with a loud voice, '`Strike again, here are my arms, my head, and my cheeks.`'
Then a mason gave him such a heavy blow over the back of his hand with his rule,
that it was much bruised, and his arm so benumbed,
that he could not draw it to him again, so that some of the people cried out,
'`He has spoiled his hand forever.`'
But he being preserved through the love of God, stood still,
and after a while felt such an extraordinary strengthening power,
that he instantly recovered strength in his hand and arm.

This made the people fall out among themselves; and some said,
if he would give them money, they would secure him from the rest.
But he, instead of doing so, showed them their false Christianity, and told them,
they were more like Jews and heathens, than true Christians;
and that their fruits were an evidence of the unprofitable ministry of their priests.
Then he felt himself moved to return to Ulverstone, and went into the market there:
and as he went, a soldier meeting him, said, '`Sir, I see you are a man,
and I am ashamed and grieved that you should be thus abused,`' But G. Fox told him,
the Lord`'s power was over all.
And this he experienced, when he walked through the people in the market;
for none of them had power to touch him then, though some of his friends were abused.
And he seeing the soldier among them, with his naked rapier,
bade him put up his sword again, if he would go along with him;
for he was willing to draw him out of the company, lest some mischief should be done:
and yet a few days after seven men fell upon this soldier, and beat him cruelly,
because he had taken part with G. Fox and his friends.

G+++.+++ Fox having performed his service at Ulverstone, came again to Swarthmore,
where he found several of his friends dressing their wounds
and bruises received by the hearers of priest Lampitt.
And now the priests began to prophesy again, that within half a year,
the Quakers should all be put down and gone.
But they reckoned wrong; for it fared with those people as with trees,
which grow best when most lopped.
__Duris ut ilex tonsa pipennibus, perdamna, per caedes, ab ipso, ducit opes animumque ferro__^
footnote:[_Imitated:_
`    As by the lopping axe, the sturdy oak
     Improves her shade, and thrives beneath the stroke;
     Though present loss and wounds severe she feel,
     She draws fresh vigour from the`' invading steel. `]

G+++.+++ Fox keeping in continual motion, went with James Nayler to Walney Island,
having first had a meeting at a little town called Cockan,
after which a man came to him with a pistol, and held it at him, but it would not go off.
G+++.+++ Fox then zealously speaking to him, he was so struck, that he trembled with fear,
and went away.
The next morning G. Fox went over in a boat to James Lancaster`'s,
and as soon as he came to land, about forty men with staves, clubs, and fishing-poles,
fell upon him, beating and punching him,
and endeavored to thrust him "`backward into the sea: but he pressing on,
was knocked down and stunned.
When he came to himself again, he saw James Lancaster`'s wife,
throwing stones at his face, and her husband James was lying over him,
to keep the blows and the stones from off him; for the people had persuaded this woman,
that G. Fox had bewitched her husband, and promised her to kill him when he came thither.
But the Lord, by his invisible power, preserved him wonderfully,
so that they could not take away his life.
At length he got up, but was soon beat down again into the boat;
which James Lancaster observing, came to him, and set him over the water.
Being come to the other side, they saw how the wicked crew was fallen upon James Nayler,
with a horrible cry, '`Kill him; Kill him.`'
For whilst they had been beating G. Fox, they had not minded Nayler,
who was walking up into a field.

G+++.+++ Fox being now come again to Cockan, met with no better entertainment,
for the people came on with pitchforks, flails, and staves, to keep him out of the town,
crying, '`Kill him; Knock him on the head.`'
But he was preserved alive; and after having been much abused,
they drove him a pretty way out of the town, and left him.
Then James Lancaster went back to look after James Nayler.
In the meanwhile G. Fox went to a ditch of water,
and washed himself from the blood and dirt.
After which he walked about three miles to the house of one Thomas Hutton,
but was so bruised that he could hardly speak; only he told where he left James Nayler.
Whereupon the said Hutton, and Thomas Lawson, the priest mentioned before,
(who lodged then at Hutton`'s house,) took each of them a horse,
to see if they could find James Nayler; and they lighting on him,
brought him thither that night.

Margaret Fell the next day hearing what was befallen G. Fox, sent a horse for him;
but he was so sore bruised, that he was not able to bear the shaking of the horse,
without much pain.
When he was come to Swarthmore,
the justices Sawrey and Thompson gave forth a warrant against him;
but judge Fell coming home, made it ineffectual,
and sent out warrants into the Isle of Walney, to apprehend all those riotous persons:
whereupon some of them fled the country.
But what is remarkable, James Lancaster`'s wife, who so wickedly behaved herself,
repented so of her evil, that she became afterwards one of G. Fox`'s friends.

Judge Fell now desired of G. Fox a relation of what had befallen him:
but he was backward, and said,
that those people could not do otherwise in the spirit they were;
and that they manifested the fruits of their priests`' ministry.
Which made the judge afterward say to his wife,
'`G. Fox spoke of the things as a man that had not been concerned.`'

The occasion upon which a warrant was issued out against him,
was a design the priests had laid to touch his life;
in order to which a report was spread, that in a certain meeting he had spoken blasphemy;
and they, to maintain this forgery, had suborned false witnesses.
The time of the sessions at Lancaster being come, G. Fox went thither with judge Fell,
who on the way told him, that such a matter had never been brought before him,
and that he did not know what to do in the case.
But G. Fox said, '`When Paul was brought before the rulers,
and the Jews and priests accused him of many false things, he stood still all that while,
till they had done; and when they had done, Felix, the governor,
beckoned to him to speak for himself.
And so, said G. Fox, '`thou mayest do by me.`'

Being come to Lancaster, at the sessions, there appeared about forty priests against him;
and these had chosen one Marshal, priest of Lancaster, to be their speaker;
and the witnesses they had provided, were a young priest, and two priests`' sons.
When the justices were set, and had heard all the charges of the priests and witnesses;
which were, that G. Fox had said, that God taught deceit,
and that the Scripture contained but a parcel of lies;
the witnesses were examined upon oath; but they were so confounded, and at such a loss,
that one of them, not being able to answer directly to what was asked him, said,
the other could say it; which made the justices say, '`Have you sworn it,
and do you now say, the other can say it?
It seems you did not hear those words spoken yourself,
though you have given it in upon your oath.`'
There were several persons in the court,
who declared that they had heard one of the two priests`' sons say,
if he had power he would make George deny his profession;
and that he would take away his life.
The young priest, who also was a witness, confessed,
that he should not have meddled with the thing, had not another priest sent for him,
and set him on work.
After all the accusations had been heard,
several men of reputation in the country affirmed in court, that no such words,
as had been sworn against G. Fox, were spoken by him at the meeting;
for most of the serious men on that side of the county, that were then at the sessions,
had been at that meeting,
wherein the witnesses swore he spake the aforesaid blasphemous words.
Colonel West, being a justice of the peace, and then upon the bench,
was so well pleased with these evidences, that he,
(having long been weak in body,) said he blessed the Lord that had healed him that day;
adding, that he never saw so many sober people, and good faces together in all his life.
And then turning himself to G. Fox, said, '`George,
if thou hast any thing to say to the people, thou mayest freely declare it.`'
Then he began to speak; but priest Marshal, the orator for the other priests,
went away presently.
Now that which G. Fox declared, was,
that '`the holy Scriptures were given forth by the Spirit of God;
and that all people must first come to the Spirit of God in themselves,
by which they might know God and Christ, of whom the prophets and apostles learnt,
and also know the holy Scriptures.
For as the Spirit of God was in them that gave forth the Scripture;
so the same Spirit of God must also be in those that
come to know and understand the Scriptures:
by which Spirit they might have fellowship with the Father, and with the Son,
and with one another: and that without that Spirit,
they could know neither God nor Christ, nor the Scriptures,
nor have right fellowship with one another.`'
No sooner had he spoken these words,
but about half a dozen priests burst out into a passion, and one of them,
whose name was Jackus, said that the Spirit and the letter were inseparable:
which made G. Fox answer, '`Then every one that hath the letter, hath the Spirit;
and they might buy the Spirit with the letter of the Scripture.`'
To which judge Fell, and colonel West added, that according to that position,
they might carry the Spirit in their pockets, as they did the Scriptures.
The justices also bid Jackus prove what he had said.
But he finding himself caught, would have denied it;
and the other priests endeavored to disguise his words with a pretended meaning.
But the justices would admit no other meaning, than the plain sense of the words.
And seeing the witnesses did not agree,
and perceiving that they were set on by the envy of the priests, they discharged him,
and after judge Fell had spoken to the justices Sawrey and Thomson,
concerning the warrant they had given forth against G. Fox,
showing that this tended to encourage such riots as those in the Isle of Walney,
he and colonel West granted a supersedes, to stop the execution of the said warrant.

G+++.+++ Fox, being thus cleared in open sessions, many people rejoiced,
and were that day convinced of the Truth declared by him in the court; and among these,
one justice Benson, and the mayor of Lancaster, whose name was Ripan;
also one Thomas Briggs, who had been very averse to, and an opposer of,
the Quakers so called;
and this same Briggs became afterwards a faithful minister of the gospel amongst them,
and remained so to the end of his days.

G+++.+++ Fox stayed yet some days at Lancaster.
But to relate all that he and his friends met with, is not my intention;
for to set down at large all such occurrences,
would be a work requiring more leisure and strength than can be expected from me.
And therefore I intend only to describe what I find most remarkable;
though many notable things have happened,
of which I could not fully be informed in every circumstance, as name, place, time, etc.
But it is probable that this may give occasion in England, to some other author after me,
to make such discoveries, that posterity will wonder at it.
For such abuses as G. Fox met with, was the share also of many others of his friends,
especially the preachers, who this year were no less than twenty-five in number;
and almost in every place where they came, they met with opposition,
and became as it were the prey of the rude multitude.
But neither the beating, buffeting, nor stoning of the mad rabble, nor the jails,
nor whippings that befell them from the magistrates,
were able to stop the progress of the doctrine they preached to the people in markets,
streets, and also in steeple-houses.
And many and even of those that had been enraged like wolves,
became afterwards like lambs; and suffered patiently from others,
what formerly they themselves, in a blind zeal, had committed.

Thus the Quakers so called, by a firm and lasting patience,
have surmounted the greatest difficulties, and are at length become a numerous people,
many not valuing their own lives,
when they met with any opportunity for the service of God.
And though their enemies on this account,
have charged them with stubbornness and obstinacy,
yet they meekly resigned to what befell them,
well knowing that thus to be accused hath been always the
lot of those who suffered for the testimony of truth.
Neither could they be charged with resistance or making head against their persecutors;
for one man did sometimes lead a great many of them to prison,
who never forsook their religious assemblies, how hot soever persecution was.
That this was also the practice of the primitive Christians, appears by what Cyprian,
who died a martyr, wrote to Demetrian, viz. __Nemo nostrum, quando apprehenditur,
reluctatur; nee se adversus injustam violentiam veslram,
quamvis nimius et copiosus sit noster populus, ulcisctitur.__^
footnote:[No one of us makes resistance when he is taken up;
nor takes any revenge on your unrighteous violence,
although our numbers are greater than yours.]
But let not my reader think,
that these I have described have been the greatest sufferings of this harmless people;
for I believe them to have been a hundred times more than my pen will be able to mention.
Now I take up again the thread of my relation.

G+++.+++ Fox being acquitted by the court, as hath been said,
it made the priests fret to hear it cried about, that the priests had lost the day,
and that the Quakers had kept the field.
To revenge this, they got some envious justices to join with them,
who at the following assizes at Lancaster, informed judge Windham against G. Fox;
which so prevailed upon him, that he commanded colonel West,
who was clerk of the assizes, to issue forth a warrant for apprehending him,
but the said colonel telling the judge of his innocency, spoke boldly in his defense.
The judge offended at this, commanded him again, either to write a warrant,
or to go off from his seat.
Then the colonel told him in plain terms, that he would not do it,
but that he would offer up all his estate, and his body also for G. Fox.
Thus the judge was stopped; and G. Fox coming that night to Lancaster,
heard of a warrant to be given out against him,
and therefore judged it better to show himself openly,
than to make his adversaries seek him.
So he went to the chambers of judge Fell and colonel West; and as soon as he came in,
they smiled, and the colonel said, '`What! are you come into the dragon`'s mouth?`'
But G. Fox was always undaunted, and did not use to flinch in danger.
So he stayed some days in town, and walked up and down there, without being meddled with,
or questioned by any.

Yet his Friends in the meanwhile did not suffer the less;
for all the villainy or insolence that could be thought of,
was not judged by some to be too bad to vex them.
It was about this time that Richard Hubberthorn and several
others were hauled out of a meeting by some wicked men,
and carried some distance off in the fields, where they bound them,
and left them so in the winter season.

G+++.+++ Fox being now come again to Swarthmore,
wrote several letters to the magistrates and priests who had raised persecutions thereabouts.
That to justice John Sawrey, was very sharp, and after this manner:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

Thou wast the first beginner of all the persecution in the North.
Thou wast the first stirrer of them up against the righteous seed,
and against the truth of God;
and wast the first strengthener of the hands of evil-doers
against the innocent and harmless:
and thou shalt not prosper.
Thou wast the first stirrer up of strikers, stoners, persecutors, stockers, mockers,
and imprisoners in the North; and of revilers, slanderers, railers, and false accusers,
and scandal-raisers.
This was thy work, and this thou stirredst up!
So thy fruits declare thy spirit.
Instead of stirring up the pure mind in the people, thou hast stirred up the wicked,
malicious and envious; and taken hand with the wicked.
Thou hast made the people`'s minds envious, up and down the country: this was thy work.
But God hath shortened thy days, and limited thee, and set thy bounds,
and broken thy jaws, and discovered thy religion to the simple and babes,
and brought thy deeds to light.
How is thy habitation fallen, and become the habitation of devils!
How is thy beauty lost, and thy glory withered!
How hast thou showed thy end, and thou hast served God but with thy lips,
and thy heart far from him, and thou in thy hypocrisy!
How hath the form of thy teaching declared itself to be the mark of the false prophets,
whose fruit declares itself! for by their fruits they are known.
How are the wise men turned backward!
View thy ways, and take notice, with whom thou hast taken part.
That of God in thy conscience will tell thee.
The ancient of days will reprove thee.
How hath thy zeal appeared to be the blind zeal; a persecutor,
which Christ and his apostles forbad Christians to follow!
How hast thou strengthened the hands of evil-doers, and been a praise to them,
and not to them that do dwell!
How like a mad man, and a blind man,
didst thou turn thy sword backward against the saints, against whom there is no law!
How wilt thou be gnawed and burned one day,
when thou shalt feel the flame and have the plagues of God poured upon thee,
and thou begin to gnaw thy tongue for pain, because of the plagues!
Thou shalt have thy reward according to thy works.
Thou canst not escape; the Lord`'s righteous judgment will find thee out,
and the witness of God in thy conscience shall answer it.
How hast thou caused the heathen to blaspheme, and gone on with the multitude to do evil,
and joined hand in hand with the wicked!
How is thy latter end worse than thy beginning, who art come with the dog to bite,
and art turned as a wolf to devour the lambs!
How hast thou discovered thyself to be a man more fit to be kept in a place to be nurtured,
than to be set in a place to nurture?
How wast thou exalted and puffed up with pride!
And how art thou fallen down with shame,
that thou comest to be covered with that which thou stirredst up, and broughtest forth.
Let not John Sawrey take the words of God into his mouth, till he be reformed.
Let him not take his name into his mouth, till he depart from iniquity.
Let not him and his teacher make a profession of the saints`' words,
except they intend to proclaim themselves hypocrites,
whose lives are so contrary to the lives of the saints;
whose church hath made itself manifest to be a cage of unclean birds.
You having a form of godliness, but not the power, have made them that be in the power,
your derision, your bye-word, and your talk at your feasts.
Thy ill savour, John Sawrey, the country about have smelled,
and of thy unchristian carriage all that fear God have been ashamed;
and to them thou hast been a grief.
In the day of account thou shalt know it, even in the day of thy condemnation.
Thou wast mounted up, and hadst set thy nest on high;
but never gottest higher than the fowls of the air.
But now thou art run amongst the beasts of prey, and art fallen into the earth;
so that earthliness and covetous-ness have swallowed thee up;
and thy conceitedness would not carry thee through,
in whom was found the selfish principle, which hath blinded thy eye.
Thy back must be bowed down always; for thy table is already become thy snare.

[.signed-section-signature]
G+++.+++ F.

--

Sharp indeed was this letter; but G. Fox thought himself moved thereto by the Lord:
and it is remarkable that this justice Sawrey,
who was the first persecutor in those parts, afterwards was drowned,
and so died not a natural death.
To the priest William Lampitt he writ also, and another letter to others,
to reprove them for their wickedness.

Some time after he went to Westmoreland, where mischief was intended against him,
but prevented by justice Benson, and some considerable men besides.
Coming to Grayrigg, he had a meeting there where an-jest came to oppose,
but was confounded; and there being many people,
some of the milk-pails that stood upon the side of the house,
tumbled down by reason of the crowd; from which the priest afterwards raised a slander,
that the devil frighted him, and took away one side of the house.
And though this was a known falsehood, yet it was given out as true in public print.

Another time this priest came to another meeting, and fell to jangling; saying first,
that the Scriptures were the word of God.
To which G. Fox said, that they were the words of God, but not Christ, who is the Word.
And when he urged the priests for proof of what he had said, the priest, being at a loss,
was not long before he went away.
Some time after coming again into a meeting,
and hearing that G. Fox directed the people to Christ Jesus,
the priest taking out his bible, said, it was the word of God.
Then G. Fox told him, it was the words of God; but not God, the Word.
The priest however persisted in what he had said,
and offered to prove before all the people, the Scriptures to be the word of God.
But this quarrel tending to vain logomachies, or contest about words, ended in confusion;
and many of the priest`'s followers came to see the vanity of his assertions.

The year being now come to an end, and a war kindled between England and Holland,
King Charles II. then in exile,
asked the Dutch to he-received in their navy as a volunteer, without any command:
but this-was courteously refused by the States-General.
Oliver Cromwell in the meanwhile, strove for the supreme authority in England,
the more because he perceived how some of the parliament,
jealous of his increasing greatness, endeavored to cross him in his design.
This made him labor to get the parliament dissolved:
but they not going on so quickly as he would have them, to put a period to their sitting,
he resolved arbitrarily to make an end of them.
And entering the house In the month called April, 1653,
after having rudely inveighed against them,
that they had made a bad use of their authority,
and that without their dissolution the realm would not be safe,
etc. he at length cried out,
'`You are no parliament:`' and then ordering some musqueteers to enter,
he made the members depart the house, and ordered the doors ta be shut;
thus putting an end to this assembly, that had been sitting nigh thirteen years.

But what is remarkable, G. Fox not long before being come to Swarthmore,
and hearing judge Fell and justice Benson discoursing together concerning the parliament,
he told them, '`That before that day two weeks the parliament should be broken up,
and the speaker plucked out of his chair.`'
And thus it really happened:
for at the breaking up of the parliament the speaker
being unwilling to come out of his chair,
said that he would not come down unless he were forced:
which made general Harrison say to him.
Sir, I will lend you my hand; and thereupon taking him by the hand, the speaker came down.
This agreed with what G. Fox had predicted.
And a fortnight after justice Benson told judge Fell,
that now he saw George was a true prophet;
since Oliver had by that time dissolved the parliament.

Now in Cumberland great threatenings were spread, that if ever G. Fox came there again,
they would take away his life.
He hearing this went thither; but nobody did him any harm.
Returning then to Swarthmore, where justice Anthony Pearson was at that time;
he so effectually declared truth, that this justice was convinced,
and not long after entered into the society of the despised Quakers.

G+++.+++ Fox then, going again into Cumberland, went to Bootle,
and there found preaching in the steeple-house, a priest from London,
who gathered up all the Scriptures he could think of, that speak of false prophets,
antichrists, and deceivers, and made application of them to the Quakers.
But when he had done, George began to speak,
and returned all those Scripture places on the priest; who being displeased at this,
said that he must not speak there.
But G. Fox; told him that the hour-glass being run, and he having done,
the time was free for him, as well as for the priest,
who was himself but a stranger there.
He having said this went on, and showed who were the false prophets,
and what marks the '`Scriptures gave them; directing people to Christ their teacher.
When he had done,
the priest of the place made a speech to the people in the steeple-house yard, and said,
'`This man hath gotten all the honest men and women in Lancashire to him;
and now he comes here to do the same.`'
To which G. Fox returned, '`What will thou have left?
and what have the priests left them, but such as themselves?
for if it be the honest that receive the Truth and are turned to Christ,
then it must be the dishonest that follow thee, and such as thou art.`'
Some words were also exchanged about tithes; and G. Fox told them,
that Christ had ended the tithing priesthood,
and had sent forth his ministers to give freely, as they had received freely.

From thence he went to Cockermouth, near which place he had appointed a meeting;
and coming thither he found James Lancaster speaking under a tree,
which was so full of people, that it was in danger of breaking.
G+++.+++ Fox now looked about for a place to stand upon, for the people lay spread up and down.
But at length a person came to him, and asked if he would not go into church.
He seeing no place more convenient to speak to the people, told him, yes.
Whereupon the people rushed in on a sudden, so that the house was so full of people,
he had much ado to get in.
When they were settled he stood up on a seat, and preached about three hours;
and several hundreds were that day convinced of the truth of this doctrine.

From thence he went to other places, and particularly to Brigham,
where he preached in the steeple-house with no less success.
Afterwards coming into a certain place, and casting his eye upon a woman unknown to him,
he told her that she had lived a lewd life; to which she answered,
that many could tell her of her outward sins, but of her inward, none could.
Then he told her, her heart was not right before the Lord: and she was so reached,
that afterwards she came to be convinced of God`'s truth.

Then he came near Coldbeck, to a market town, where he had a meeting at the cross,
and some received the truth preached by him.

From thence he went to Carlisle, where the teacher of the Baptists,
with most of his hearers, came to the abbey, in which G. Fox had a meeting.
After the meeting the Baptist teacher, who was a notionist, and an airy man, came to him,
and asked what must be damned?
and he told him, that which spake in him was to be damned.
And this stopped his mouth.
Then he opened to him the states of election and reprobation, so that he said,
he never heard the like in his life,
and came afterwards also to be convinced of the Truth.
Then he went up to the castle among the soldiers,
who by beating of the drum called the garrison together.
Among these he preached;
directing them to the measure of the Spirit of Christ in themselves,
by which they might be turned from darkness to light, and from the power of Satan to God:
he warned them also to do no violence to any man, etc.
G+++.+++ Fox having thus discharged himself, none opposed him, except the Sergeants,
who afterwards came to be convinced.
On the market-day he went into the market,
though he had been threatened that if he came there, he would meet with rude treatment.
But he willing to obey God more than man, showed himself undaunted,
and going upon the cross,
he declared that the day of the Lord was coming upon all deceitful ways and doings,
and deceitful merchandise; and that they should put away all cozening and cheating,
and keep to yea, and nay, and speak the truth to one another.

On the First-day following, he went into the steeple-house,
and after the priest had done he began to preach.
Now the priest going away, and the magistrate desiring G. Fox to depart,
he still went on,
and told them he came to speak the word of life and salvation from the Lord amongst them.
And he spoke so powerfully that the people trembled and shook,
and they thought the steeple house shook also: nay,
some of them feared it would have fallen down on their heads.
Some women in the meanwhile making a great bustle,
at length the rude people of the city rose,
and came with staves and stones into the steeple-house:
whereupon the governor sent some musqueteers to appease the tumult;
and these taking G. Fox by the hand in a friendly manner, led him out.
Then he came to the house of a lieutenant, where he had a very quiet meeting.
The next day the justices and magistrates sent for him to come before them in the town-hall.
So he went thither, and had a long discourse with them concerning religion,
and showed them that though they were great professors,
(viz. Presbyterians and Independents,) yet they were
without the possession of what they professed.
But after a long examination they committed him to prison as a blasphemer, a heretic,
and a seducer.
There he lay till the assizes came on, and then all the talk was,
that he was to be hanged: and the high sheriff Wilfrey Lawson,
was so eager to have his life taken away, that he said,
he himself would guard G. Fox to execution.
This made such a noise that even great ladies came to see him, as one that was to die.
But though both judge and magistrates were contriving how they might put him to death,
yet the judge`'s clerk started a question,
which puzzled them and confounded their counsels,
so that he was not brought to a trial as was expected; which however was contrary to law.
But such was their envy against him,
that the jailer was ordered to put him amongst thieves and murderers,
and some naughty women; which wicked crew were so lousy,
that one woman was almost eaten to death with lice: but what made the prison the worse,
there was no house of office to it,
and in this nasty place men and women were put together against all decency.
Yet these prisoners, how naught soever, were very loving to G. Fox,
and so hearkened to his wholesome counsel, that some of them became converts.
But the under jailer did him all the mischief he could.
Once when he had been at the grate, to take in the meat his friends brought him,
the jailer fell a beating of him with a great cudgel, crying,
'`Come out of the window,`' though he was then far enough from it.
But whilst the jailer was thus beating him, he was so filled with joy,
that he began to sing, which made the other rage the more,
so that he went and fetched a fiddler, thinking thereby to vex him.
But when this fellow played, he sang a hymn so loud,
that with his voice he drowned the sound of the fiddle,
and thereby so confounded the player, that he was fain to give over and go his ways.

Not long after,
Justice Benson`'s wife felt herself moved to eat no
meat but what she should eat with G. Fox,
at the bars of the dungeon-window.
Afterwards she herself was imprisoned at York, when she was big with child,
for having spoken, it is like, zealously to a priest.
And when the time of her travail came, she was not suffered to go out,
but was delivered of her child in the prison.

Whilst G. Fox was in the dungeon at Carlisle, there came to see him one James Parnel,
a little lad of about sixteen years of age;
and he was so effectually reached by the speaking of G. Fox,
that he became convinced of the truth of his sayings; and notwithstanding his youth,
was by the Lord quickly made a powerful minister of the gospel,
showing himself both with his pen, and his tongue, a zealous promoter of religion,
although he underwent hard sufferings on that account, as will be mentioned hereafter.

There were also many others, who not sticking at any adversities,
came to be zealous preachers of repentance;
among these was Thomas Briggs already mentioned, who went through many cities, towns,
and villages, with this message: '`Repent, repent,
for the mighty terrible day of the Lord God of power is appearing,
wherein no worker of iniquity shall stand before him,
who is of purer eyes than to behold iniquity, for he wills not the death of a sinner;
and if ye repent, and turn to him, he will abundantly pardon.`'
Sometimes he went into markets and steeple-houses, and was often cruelly abused.
Once being in a steeple-house at Warrington in Lancashire,
and speaking a few words after the priest had done,
he was very violently knocked on his head: after which, a man taking hold of his hair,
smote him against a stone, and pulled off a handful of it,
which Thomas taking up from the ground, mildly said,
'`Not one hair of my head shall fall without my Father`'s permission.`'
At another time he speaking to a priest in Cheshire, as he was going in his journey,
the priest was much offended at him; and one of his hearers,
as it were in revenge of this pretended affront, struck him on the head,
and knocked him down; but Thomas getting up again, and turning his face to the smiter,
he smote him on his teeth, so that the blood gushed out exceedingly;
which some of the standers by could not but cry out against But not long after,
the man that struck him thus, fell sick, and died, crying upon his deathbed,
'`Oh that I had not smitten the Quaker!`' This Thomas once going through Salisbury,
and calling the inhabitants to repentance, was apprehended,
and brought before several justices, who proffered him the oath,
under pretense of his being a Jesuit: but he saying, he could not swear,
because Christ had commanded, not to swear at all, was sent to prison,
where he was kept a month.
He also went up and down the streets of Yarmouth,
proclaiming the terrible day of the Lord, that all might repent, and fear Him,
that made heaven and earth, and the sea.
And being followed by a great multitude of rude people, and turning about,
he spoke so powerfully to them, and with such piercing words,
that they ran away for fear.
At length an officer came and took hold of him, but leading him gently,
he had opportunity to continue preaching to the people, and to clear himself.
Being brought before the magistrates, they ordered him to be led out of the town;
which being done, Thomas came in again by another way,
and having performed his service there to his satisfaction, he departed the town.

When he came to Lynn, and warned people to repent, a great mastiff`' dog was set upon him,
but the dog coming near him, fawned upon him.
Thus he went through many places, passing sometimes five or six towns in one day;
and though swords were drawn against him, or axes taken up to hew him down,
yet he went on, and spoke so awfully, that even some, who did not see his face,
were so reached by the power that accompanied him, that they became converts.
Coming to Clayzons in Wales, and many hearing him attentively,
the constable stirred up the rude people, and cried, '`Kill him;
Kill him;`' as if he had been a mad dog; and they threw such great stones upon him,
that he admired they did not kill him; but he was preserved by such a mighty power,
that according to his relation, they were to him as a nut, or a bean.
Many other rude encounters he met with,
but was preserved wonderfully in the greatest dangers;
which strengthened him not a little in the belief, that God,
who so miraculously saved him, did require this service from him.
He was also in America, and died in a good old age,
after having labored above thirty years in the service of the gospel.

Miles Halhead was also one of the first zealous preachers among the Quakers so called.
He was the first of those of his persuasion, that was imprisoned at Kendal.
Once he went to Swarthmore to visit his friends, and to assist at their meeting;
by the way he met the wife of the justice Thomas Preston,
and because he passed by her quietly, without the ordinary way of greeting,
she grew so offended, that she commanded her man to go back and beat him; which he did.
At which Miles being kindled with zeal, said to her, '`O thou Jezebel!
Thou proud Jezebel!
Canst thou not permit and suffer the servant of the Lord, to pass by thee quietly?`'
She then held forth her hands, as if she would have struck him, and spit in his face,
saying, '`I scorn to fall down at thy words.`'
This made Miles say again, '`Thou proud Jezebel, thou that hardenest thy heart,
and brazenest thy face against the Lord and his servant,
the Lord will plead with thee in his own time, and set in order before thee,
the things that thou hast done this day to his servant,`' And so he parted with her,
and went to Swarthmore.
About three months after this, he felt himself moved to go and speak to her;
and when he came to Houlker Hall, he asked for Thomas Preston`'s wife:
she then coming to the door, and Miles not knowing her, asked her,
if she was the woman of the house; to which she said, '`No:
but if you would speak with Mrs.
Preston, I will intreat her to come to you,`' Then she went in,
and coming back with another woman, said,
'`Here is mistress Preston:`' but then it was manifested to him,
that she herself was the woman.
It is true, as hath been said, some time before he had seen her on the way,
and spoken to her; but it may be, she was then in so different a dress,
that by reason thereof he did not know her; yet firmly believing that it was she,
he said, '`Woman, how darest thou lie before the Lord and his servant?
Thou art the woman I came to speak to.`'
And she being silent, not speaking a word, he proceeded, '`Woman,
hear what the Lord`'s servant hath to say unto thee: O woman,
harden not thy heart against the Lord; for if thou dost,
he will cut thee off in his sore displeasure; therefore take warning in time,
and fear the Lord God of heaven and earth, that thou mayest end thy days in peace.`"
Having said this, he went away, she, how proud soever, not doing him any harm,
being withheld, without knowing by what.
But, notwithstanding that, she continued the same: for several years after,
when G. Fox was prisoner at Lancaster, she came to him,
and belched out many railing words, saying amongst the rest,
that his tongue should be cut off, and he be hanged.
But some time after, the Lord cut her off, and she died, as it was reported,
in a miserable condition.

But before I leave this woman, I must also say,
that about three years after she had made her man beat Miles,
it happened that as he was riding from Swarthmore, near to Houlker Hall,
he met with a person who said to him, '`Friend, I have something to say unto you,
which hath lain upon me this long time.
I am the man that, about three years ago, at the command of my mistress,
did beat you very sore; for which I have been very much troubled,
more than for any thing that I ever did in all my life: for truly,
night and day it hath been often in my heart,
that I did not well in beating an innocent man, that never did me any hurt or harm.
I pray you forgive me, and desire the Lord to forgive me,
that I may be at peace and quiet in my mind.`'
To this Miles answered, '`Truly friend, from that time to this day,
I never had any thing in my heart against thee, nor thy mistress, but love.
The Lord forgive you both; I desire that it never may be laid to your charge;
for ye knew not what ye did.`'
Here Miles stopped, and so went his ways.
Many a notable occurrence he had in his life,
and therefore he is to appear yet more than once in the course of this history.

Travelling once in Yorkshire, he came to Skipton, where declaring the word of truth,
he was so sorely abused and beaten, that he was laid for dead; nevertheless,
by the Lord`'s power, he was healed of all his bruises,
and within three hours he was healthy and sound again,
to the astonishment of those that had so abused him,
and to the convincing of many that beheld him.

Then he went to Bradford, Leeds, and Halifax,
where he also declared the doctrine of truth amongst the people;
but riot without meeting with great persecution.

From thence he came to Doncaster,
and there went on a First-day of the week to a steeple-house, where,
after the worship was done, he spoke to the priest and people: but they,
instead of hearkening to what he said, fell upon him in a great rage,
and drove him out of the town; and he being sorely bruised, they left him for dead.
But before his going from home, he had been firmly persuaded,
that the Lord would preserve him in all dangers:
and it happened so to him according to his belief; for he got up again,
and went to a friend`'s house, where he laid himself down upon a bed.
But not long after, he felt a very strong motion to go to a certain chapel,
and there to declare the word of the Lord: forthwith he felt also an inward assurance,
that if he gave up to do so, the Lord would heal him from his bruises.
Then he rose, as well as he could, and came down stairs with great difficulty,
by taking hold of the walls for a stay, and going out, he began to mend by degrees;
and coming at length into the chapel, he spake as he was moved;
and when he had cleared himself, he went back to the house from whence he came,
and the Lord made him sound of all his bruises.

Thence he went to York, and there spoke to the lord mayor, and other rulers of that city:
and passing through Yorkshire, he went into several steeple-houses, to exhort the people;
and though he met with great hardships, yet he was supported by an invisible hand.
So being clear of that country, he returned to his house at Mount-joy, in Underbarrow,
in the county of Westmoreland.
But his going thus often from home, was an exceeding great cross to his wife,
who in the first year of his change, not being of his persuasion,
was very much troubled in her mind, and would often say from discontent,
'`Would to God I had married a drunkard, then I might have found him at the alehouse;
but now I cannot tell where to find my husband.`'
But after the space of a year, it pleased the Lord to visit her.
She had a little son of about five years of age, which child she loved extraordinarily,
insomuch that she thought it was her only delight and comfort;
but it happened that this darling died,
and some time after she spoke thus to her husband: '`Truly, husband,
I have something to tell thee: one night being in bed,
mourning and lamenting with tears in my eyes, I heard a voice, saying,
'`Why art thou so discontented concerning thy husband?
I have called and chosen him to my work; my right hand shall uphold him.
Therefore be thou content and pleased, that he serve me, and I will bless thee,
and thy children for his sake; and all things shall prosper that thou shalt take in hand.
But if thou wilt not be content, but grudge and murmur, and repine against me,
and my servant, whom I have chosen to do my work,
I will bring a greater cross upon thee`" These words
being fresh in my mind both night and day,
I often said within myself.
What cross can this be, that would be greater than the want of my husband?
But for all this, I could not be content: all the joy I had, or could find,
was in our little boy, who would often, when he saw me weeping and mourning,
take me about my neck, and say, My dear mother, pray be content,
for my father will come home in a little time.
This child would often comfort me in this manner; but for all that I could not be content.
Not long after, it pleased the Lord to take from me this my only son, my chiefest joy.
Then the voice which I had heard came into my mind,
and I perceiving that this was the cross which the Lord would bring upon me,
smote upon my breast, and said within myself,
that I was the very cause why the Lord had taken away my little son.
A great fear then seizing upon me, I said, O Lord,
my God! give me power to be content to give up my husband freely to do thy will, lest,
O Lord, thou take away from me all my children.
From that time I never durst oppose thee, my husband, anymore in the work of the Lord,
for fear that his judgments might also fall upon me and my children.`'
This served not a little to strengthen and encourage Miles.

Some time after, walking in his garden,
he felt a motion to go to Stanley chapel in Lancashire.
Now though he might expect to meet with rude entertainment there,
yet he consulted not with flesh and blood, but went to the aforesaid chapel.
Being come, he was not suffered to enter, but the door was violently turned against him.
Then he walked in the yard till the worship was done, and the people that came out,
(one may guess how edified,) fell upon him with great rage,
and one captain William Rawlinson, took hold of his arms and shoulders,
and calling another man to take him by the feet and legs, they threw him over the wall;
by which fall he was exceedingly bruised, so that he had much to do to get home.
By the way it was inwardly said to him,
that he must be content with what was befallen him that day,
and that if he was faithful in what the Lord required of him then,
he would heal him again.
Being come home, he waited upon the Lord to know his will.
In this resignedness, within six days, he was moved to go to Windermere steeple-house,
and it was, as it were said unto him, Fear not the face of any man,
but speak the word of the Lord freely;
and then thou shalt be made sound again of all thy bruises.
So he went to the said steeple-house,
and having spoken the word of the Lord to the priest and people,
without receiving any harm, he was healed that day of his sore bruises.

Some time after by another motion, he came to Furneiss in Lancashire,
to the house of captain Adam Sands, where he found a great number of professors gathered,
and priest Lampitt preaching.
But as soon as Miles entered, Lampitt was silent, and which continuing a pretty while,
captain Sands said to him, '`Sir, what is the matter:
are you not well to which the priest answered, '`I am well,
but I shall speak no more as long as this dumb devil is in the house.
'`A dumb devil,`' said the captain, '`where is he?
This is he,`' said the priest, pointing with his hand, '`that standeth there.`'
Then the captain said, '`This man is quiet and saith nothing to you: I pray you, sir,
go on in the name of the Lord; and if he trouble or molest you in my house,
I will send him to Lancaster castle.`'
But the priest said again,
'`I shall not preach as long as this dumb devil is in the house.`'
Then the captain said to one Camelford, a priest also, '`I pray you, sir,
stand up and exercise your gift, and I will see that you be not disturbed.`'
But the priest answered as the other,`' I shall not
speak as long as this dumb devil is in the house.`'
Then the people cried, '`Lord rebuke thee Satan; Lord rebuke thee Satan:
what manner of Spirit is this that stops our ministers`' mouths?
Then the captain came to Miles, and taking him by the hand, led him out of the house.
In all that time he had not spoke a word,
and saw now the accomplishment of what he had been persuaded of before,
viz. that an invisible power would confound by him
the wisdom of the priests when he spoke never a word.
The said Camelford was one who,
a good while before had stirred up the rabble against G. Fox;
and the other was that Lampitt, who has been mentioned already,
and who had been so esteemed by Margaret Fell,
before she came to be acquainted with G. Fox.

Some time after this occurrence.
Miles went to Newcastle, and there said to the mayor, rulers, and priests of that town,
that God`'s anger was kindled against them,
because they had shut the kingdom of heaven against men, and would not enter themselves,
nor suffer them that would.
Because of this he was imprisoned: but the mayor being much troubled,
sent for the sheriff, for these two had committed Miles; when come, he said to him,
'`We have not done well in committing an innocent man to prison: pray let us release him.`'
The sheriff consenting, Miles was set at liberty.
Then he declared the word of the Lord in those parts,
and many were convinced of the truth held forth by him.
But now I part with this Miles Halhead, who hereafter is to be mentioned again.

About this time, viz. in the summer, general Cromwell had called a new parliament,
consisting mostly, (as hath been said by some,) of members of his own choice;
for it was a certain number of persons out of each county and city in England, Scotland,
and Ireland, nominated by the council of officers, and sent for to meet at Westminster.
Into the hands of these, Cromwell delivered the supreme authority of the nation,
by an instrument, or commission, signed by himself and the officers;
but the authority of this meeting lasted scarce half-a-year,
as will be said in the sequel.

To this parliament a report was made, that at Carlisle, a person was imprisoned,
who was to die for religion.
This was G. Fox, whom we have left thus long in the dungeon at Carlisle,
and now are returning to him again.
The parliament then caused a letter to be sent down concerning him to the sheriff,
and other magistrates.
And G. Fox knowing how scandalously he had been beheld, about speaking blasphemous words,
gave forth a paper, wherein he challenged all who found fault with his doctrine,
to appear in public;
since he was ready to stand the test of whatsoever he might have spoken.
He also wrote a significant letter to the justices at Carlisle,
wherein he showed them plainly the injustice of their dealings,
and the horrid evil of persecution, as having been always the work of the false church.
Mention hath been made already of the justices Benson and Anthony Pearson:
these had desired, more than once, leave to visit G. Fox in prison;
but this having been denied them, they wrote a letter to the magistrates, priests,
and people at Carlisle,
wherein they emphatically described the wickedness of persecution,
and what would be the reward of persecutors; saying also,
that these were worse than the heathen that put Paul into prison;
because none of his friends or acquaintance were hindered by them from coming to him.
However, at length Pearson got an opportunity to come with the governor into the dungeon,
where G. Fox was kept, and they found the place so bad, and of so noisome a smell,
that the governor cried shame of the magistrate,
for suffering the jailer to treat G. Fox after such a manner;
and calling the jailers into the dungeon,
required them to find sureties for their good behavior, and put the under-jailer,
who had been very cruel to G. Fox, into the dungeon with him.
In the meanwhile, those who had imprisoned G. Fox began to grow afraid, the rather,
it may be, because the parliament took notice of these doings;
and it was not long after that he was released;
and then coming to the house of one Thomas Bewly, near Coldbeck, in Cumberland,
there came a Baptist teacher to oppose him:
but he found what G. Fox spoke to be so efficacious,
that he became convinced of the truth thereof.

At that time there was also Robert Widders,
who being moved to go to Coldbeck steeple-house, the Baptist teacher went with him.
Widders coming into the steeple-house, there was one Hutton preaching, to whom he spoke;
but the rude people threw him down, and dragged him into the yard,
where they pushed and beat him till the blood gushed out of his mouth,
so that he lay for dead some time; but a certain woman coming to him, held up his head,
so that at length he recovered his breath.
The Baptist who went along with him, had his sword taken from him,
and was sorely beaten with it; yet this did not frighten or discourage him;
and he not only left off the wearing of a sword,
but also freely gave up the inheritance of an impropriation of tithes.

The same day that this preacher was thus attacked with his own sword,
being the first of the week, several of G. Fox`'s friends, and among them,
William Dewsbury, went, one to this, and others to other steeple-houses;
and by such means, the number of the said friends increased;
though Dewsbury at that time was so violently beaten
by the people that he was almost killed;
but the Lord`'s power healed him.

But to return to Robert Widders: he being recovered from the rude treatment he met with,
as hath been said, felt himself so encouraged anew, and strengthened in his undertakings,
that he went, the same day in the afternoon, seven miles to Ackton steeple-house,
when he spoke to priest Nichols, and calling him an enemy of Christ, told him, also,
that the hand of the Lord was against him.
Then William Briscoe, a justice of Crofton, commanded the constable to secure Robert;
which he did, and carried him to the priest`'s house; where being examined by the justice,
the priest began to fawn upon him.
Thereupon Robert told the priest, that the spirit of persecution lodged in him.
But the priest said, '`No, he was not such a man.`'
Yet presently after he said to the justice,
that Robert had stolen the horse he came with: and,
that he could find in his heart to become his executioner with his own hands:
which made Robert say, '`Did I not say unto thee,
that the spirit of persecution lodged in thee?`'
Then the aforesaid justice writ a warrant to send Robert to Carlisle jail;
and after having given the warrant to the constable he asked Robert,
by what authority or power he came to seduce and bewitch the people?
Robert answered, '`I came not to seduce and bewitch people,
but I came in that power which shall make thee, and all the powers of the earth,
bend and bow down before it, to wit, the mighty power of God.`'
Whilst Robert was speaking thus, the dread of the Lord seized on the justice,
and so struck him, that he called for his warrant again,
and took it out of the constable`'s hand, suffering Robert, about night, to go away.

He being thus freed, did not leave visiting the steeple-houses from time to time,
for which he was sometimes imprisoned, and at other times saved remarkably.
Once coming near Skipton in Yorkshire,
at the steeple house,-he spoke very sharply to the priest, Webster;
since he was one that had been partly convinced of the doctrine of the inward light,
but becoming disobedient thereunto, was turned back again.
He also spoke to the people, and to justice Coats,
bidding them to mind the word of God in the heart,
which divided between the precious and the vile.
After having cleared himself,
he went to a place where a few of his friends were met together;
but he had not been long there, when there came some horsemen and foot,
who took him away, and carried him to the said justice; who examining him, said,
he had broken the law, by disturbing the minister and the people,
and that he might send him prisoner to York castle, Robert answered,
'`Send me to jail thither, if thou darest;
for I appeal to the witness of God in thy conscience.`'
But the justice being a moderate man, said,
'`I neither dare nor will;`' and taking Robert by the hand, told him,
he might take his own time in going away.

To relate all the occurrences of this Robert Widders, would be too prolix;
therefore I will only say, that as he was very zealous in speaking to the priests,
so he suffered very much in his estate,
because for conscience-sake he refused to pay them tithes;
and on that account there was taken from him, at sundry times,
to the value of 143. besides what he suffered for meetings, and for Sunday shillings,
so called, which also amounted to a considerable sum.
And this not only befell him, but it was the portion of many hundreds, nay,
perhaps thousands of those of his persuasion.
Wherefore I will not undertake to relate all that might be mentioned of this kind;
for that would be beyond my reach.

However, by this that hath been said, may be seen, by what means the Quakers, so called,
grew so numerous in those early times.
As on one hand there were raised zealous preachers; so on the other,
there were abundance of people in England, who, having searched all sects,
could nowhere find satisfaction for their hungry souls.
And these now understanding that God by his light was so near in their hearts,
began to take heed thereunto,
and soon found that this gave them far more victory over the corruption of their minds,
under which they had long groaned,
than all the self-willed worships which they with some zeal had performed many years.
And besides those that were thus prepared to receive
a further manifestation of the way of life,
there were also many of a rude life, who being pricked to the heart,
and brought over by the Christian patience of the despised Quakers,
became as zealous in doing good, as formerly they had been in working evil.

Perhaps some will think it was very indecent that they went so frequently to the steeple-houses,
and there spoke to the priests; but whatsoever any may judge concerning this,
it is certain that those teachers generally did not brmg forth the fruits of godliness,
as was well known to those who themselves had been priests,
and freely resigned their ministry, thenceforth to follow Christ in the way of his cross;
and these were none of the least zealous against that society among
whom they formerly had ministered with an upright zeal.
Yet they were not for using sharp language against such teachers, who,
according to their knowledge, feared God;
but they leveled their aim chiefly against those, who were only rich in words,
without bringing forth true Christian fruits, and works of justice.
Hence it was that one Thomas Curtis, who was formerly a captain in the parliament army,
but afterwards entered into the society of the people called Quakers, wrote,
in a letter to Samuel Wells, priest of Banbury,
and a persecutor of those of that persuasion, amongst other things, these words:
'`To thy shame, remember I know thee scandalous.
How often hast thou sate evening after evening, at cards, and sometimes whole nights,
playing, and sometimes compelling me to play with thee, for money;
yet then thou wast called of the world a minister; and now art thou turned persecutor,
etc.`'
None therefore need think it strange,
that those called Quakers did look upon such teachers as hirelings.
And that there were not a few of that sort,
appeared plainly when King Charles II was restored;
for those who had formerly cried out against episcopacy, and its liturgy,
as false and idolatrous, then became turn-coats, and put on the surplice,
to keep in the possession of their livings and benefices.
But by so doing, these hypocrites lost not a few of their auditors,
for this opened the eyes of many,
who began to inquire into the doctrine of the despised Quakers,
and saw that they had a more sure foundation,
and that this it was which made them stand unshaken against the fury of persecution.

Let us again take up the thread of these transactions which concern G. Fox: who,
now traveling through many places in the north of England,
had everywhere great meetings; but now and then met with some opposition;
sometimes with hands, and at others with the tongue.
Among the rest, at Derwentwater, in Northumberland; where,
in a dispute recommending perfection, he was contradicted; but to prove his position,
he said that Adam and Eve were perfect before they fell;
and all that God made was perfect;
and that the imperfection came by the devil and the fall: but that Christ,
who came to destroy the devil, said,
'`Be ye perfect`' To this one of the professors answered, that Job said,
'`Shall mortal man be more pure than his Maker?
The heavens are not clean in his sight.
God charged his angels with folly.`'
But G. Fox showed him his mistake, and told him that it was not Job that said so,
but one of those that contended against him.
Then the professors said, the outward body was the body of death and sin;
but G. Fox replied, that Adam and Eve had each of them an outward body,
before the body of death and sin got into them;
and that men would have bodies when the body of sin and death was put off again,
and they were renewed into the image of God again by Christ Jesus.

Thus G. Fox found work almost everywhere, and passing to Hexham,
he had a great meeting there on the top of a hill.
The priest, indeed, had threatened that he would come and oppose; but came not.

G+++.+++ Fox, then traveling on, came into Cumberland,
where he had a meeting of many thousands of people on a hill near Langlands.
Once he came into Brigham steeple-house, before the priest was there,
and declared the Truth to the people; but when the priest came in, he began to oppose,
but was wearied so, that at length he went away.

There being now also several others who preached the doctrine of the inward light of God,
which convinceth man of sin,
the number of those professors of the light increased greatly.
And as it had been said at first, that they should be destroyed within a short time;
so now the priests began to say, that they would eat out one another.
For many of them, after meetings, having a great way to go,
stayed at their friends`' houses by the way,
and sometimes more than there were beds to lodge, so that some lay on the hay-mows.
This made some of the public church grow afraid that this hospitality would cause poverty,
and that when these friends had eaten out one another,
they would come to be maintained by the parishes, and so be chargeable to them.
But "`it fell out quite otherwise, for these people were the more blessed, and increased,
without falling into want.
This puts me in mind of what one of the daughters of Judge Thomas Fell once told me,
viz. that her father having been abroad, and coming home with his servants,
found the shed so full of the horses of strange guests, (for Margaret, his wife,
had cleared the stable where they first stood,
to make room for her husband`'s own horses,) that he said to his wife,
this was the way to be eaten out,
and that thus they themselves should soon be in want of hay.
But to this Margaret said, in a friendly way, that she did not believe,
when the year was at an end, that they should have the less for that.
And it so fell out; for this year their stock of hay was such,
that they sold a great parcel of what they had in abundance.
Thus the proverb was verified, that charity doth not impoverish.
The truth of this was also experienced by those called Quakers;
for though many people at first were shy, and would not deal with them,
because of their nonconformity with the vulgar salutation,
and their saying Thou and Thee to a single person, instead of You,
etc. insomuch that some that were tradesmen lost their customers,
and could hardly get money enough to buy bread; yet this changed in time,
when people found by experience they could better trust to the words of these,
than to that of those of their own persuasion.
Hence it was, that often when any came into a town, and wanted something, they would ask,
where dwells a draper, or taylor, or shoemaker, or any other tradesman, that is a Quaker?
But this so exasperated others, that they began to cry out,
if we let these Quakers alone, they will take the trade of the nation out of our hands.
Now the cause of their trade`'s thus increasing, was,
because they were found upright in their dealings;
for integrity did then shine out among them above many others:
to this the true fear of God led them, and to this they were exhorted from time to time.
G+++.+++ Fox also writ a general epistle to them, which was as followeth:

[.embedded-content-document.epistle]
--

[.letter-heading]
To you all, Friends everywhere, scattered abroad.

In the measure of the life of God, wait for wisdom from God, even from him,
from whence it comes.
And all ye, who be babes of God,
wait for the living food from the living God to be nourished up to eternal life,
from the one fountain, from whence life comes; that orderly, and in order,
ye may all be guided and walk: servants in your places,
young men and young women in your places, and rulers of families; that every one,
in your respective places, may adorn the Truth; every one in the measure of it.
With it, let your minds be kept up to the Lord Jesus, from whence it doth come;
that a sweet savor you may be to God, and in wisdom ye may all be ordered and ruled;
that a crown and a glory ye may be one to another in the Lord.
And that no strife, nor bitterness, nor self-will may appear amongst you;
but with the light, in which the unity is, all that may be condemned.
And that every one in particular may see to, and take care of,
the ordering and ruling of their own family;
that in righteousness and wisdom it may be governed,
the fear and dread of the Lord in every one`'s heart set,
that the secrets of the Lord every one may come to receive,
that stewards of his grace you may come to be,
to dispense it to every one as they have need; and so in savoring and right discerning,
you may all be kept: that nothing that is contrary to the pure life of God,
may be brought forth in you, or among you; but all that is contrary to it,
may by it be judged: so that in light, in life, and love, ye may all live;
and all that is contrary to the light, and life, and love, may be brought to judgment,
and by that light condemned.
And that no fruitless trees be among you: but all cut down and condemned by the light,
and cast into the fire; so that everyone may bear and bring forth fruit to God,
and grow fruitful in his knowledge, and in his wisdom.
And so that none may appear in words beyond what they be in the life,
that gave forth the words: here none shall be as the untimely figs:
and none shall be of those trees, whose fruit withers: such go in Cain`'s way,
from the light; and by it are condemned.
And that none amongst you boast yourselves above your measure; for if you do,
out of God`'s kingdom you are excluded: for in that boasting part gets up the pride,
and the strife, which is contrary to the light; which light leads to the kingdom of God:
and gives every one of you an entrance thereinto, and an understanding,
to know the things that belong to the kingdom of God.
And there the light and life of man everyone receives, him who was, before the world was,
by whom it was made: who is the righteousness of God, and his wisdom: to whom all glory,
honor, thanks, and praise belongs, who is God blessed forever.
Let no image, nor likeness be made; but in the light wait,
which will bring condemnation on that part, that would make the images;
for that prisons the just.
So to the lust yield not the eye, nor the flesh; for the pride of life stands in that,
which keeps out of the love of the Father;
and upon which his judgments and wrath remains,
where the love of the world is sought after, and a crown that is mortal:
in which ground the evil enters, which is cursed; which brings forth briars and thorns,
where the death reigns, and tribulation and anguish is upon every soul,
and the Egyptian tongue is heard: all which is by the light condemned.
And there the earth is which must be removed; by the light it is seen,
and by the power it is removed, and out of its place it is shaken;
to which the thunders utter their voices, before the mysteries of God be opened,
and Jesus revealed.
Therefore all ye whose minds are turned to this light,
(which brings condemnation upon all those things before-mentioned,
that are contrary to the light, wait upon the Lord Jesus for the crown, that is immortal,
and that fadeth not away.

[.signed-section-signature]
G+++.+++ F.

--

This epistle he sent to be read at the meetings of his friends.
Not long after, a certain priest of Wrexham in Wales, whose name was Morgan Floyd,
sent two of his congregation into the north of England,
to inquire what kind of people the Quakers were.
These two coming thither, found the doctrine of the said people such,
that they became convinced of the truth thereof, and so embraced it; and after some stay,
they returned home.
One of these was called John ap John, and continuing faithful,
became a minister of the gospel he had thus received;
but the other afterwards departed from his convincement.

Let us now take a short view of state affairs in England.
We have seen already Cromwell`'s power so great,
that he ventured to dissolve the long parliament, and that he called another in its room.
But before the year`'s end,
this Parliament resigned their power into the hands of Cromwell,
from whom they had received it.
Thus he, with his council of field officers,
saw himself again in the possession of the supreme government:
audit was not long before this council declared:
'`that henceforth the chief rule of the nation should be entrusted to a single person,
and that this person should be Oliver Cromwell,
chief general of all the forces in England, Scotland, and Ireland;
that his title should be Lord Protector of the Commonwealth of England, Scotland,
and Ireland; and all the dominions belonging thereunto;
and he was to have a council of twenty-one persons to assist him in the government.`'

This matter being thus stated, the commissioners of the great seal,
and the lord mayor and aldermen of London, were required, on the 16th of December,
to attend Cromwell, and his council, in Westminster-hall.
Being come thither, the instrument of government was read,
whereby Cromwell was declared Protector, he standing all this while bare-headed,
and major-general Lambert kneeling, presented him with a sword in the scabbard,
representing the civil sword: which Cromwell accepting, put off his own,
to intimate thereby, that he would no longer rule by the military sword.
The said instrument being writ on parchment, contained,
'`That the Protector was to call a Parliament every three years;
that their first meeting should be on the 13th of September next ensuing:
that he should not be permitted to dissolve a parliament, before it had set five months;
that the bills presented to him for his consent,
if he did not confirm them within twenty days, should have the force of laws;
that he was to have a council, who were not to exceed the number of twenty-one,
and not to be under thirteen; that forth-with after his death,
the council was to choose another Protector; that no Protector after him,
should be capable of being chief general of the army;
and that it should be in the power of the Protector to make war and peace.`'
Whilst this instrument was reading, Cromwell held his hand on the bible,
and afterwards took the oath, that he would perform all that was contained therein.
This being done, he covered himself, all the others remaining uncovered.
Then the commissioners delivered the seals to him,
and the lord mayor of London the sword; all which he restored again,
with an exhortation to use them well.
Afterward general Lambert carried the sword before him to his couch,
in which he went to Whitehall, where he was proclaimed Protector,
which was done also in the city of London.
Now he was attended like a prince, and created knights, as kings used to do.
Thus Cromwell, by a singular, and very strange turn of mundane affairs,
saw himself placed in the palace,
from whence he and his adherents had cast out King Charles the First.
