== Chapter IV.

=== 1654

A general Convincement --Increase of Ministers -- First Quakers in London--F. Howgill
and the Protector--First meeting settled in London--Persecution of Quakers in Bristol
--The Protector and Liberty of conscience--Cruelties practised at Bristol--R. Hubber
thorn convinced--G. Whitehead convinced--Barbarous usage of Elizabeth Heavens and Elizabeth
Fletcher at Oxford--Remarkable account of Barbara Blaugdone--M. Halhead and J. Lancaster
in Ireland and Scotland --G. Fox in Yorkshire and Lincolnshire -- G. Fox disputes with
Priest Stevens --G. Fox sent prisoner to London --His intercourse with the Protector
-- Public transactions --J. Crook convinced --Account of W. Caton -- Luke Howard convinced--Account
of S. Fisher.

Oliver Cromwell in the beginning of the year 1654,
seeing himself invested with the supreme authority of the nation, required,
both of the soldiers and others, the oath of fidelity.
But since amongst the first, there were many, who,
though convinced of the truth of the doctrine of the Quakers so called,
yet had not convenient opportunity to leave the military service,
it now presented itself; for when the oath was tendered them,
they declared that in obedience to Christ`'s command, they could not swear;
whereupon they were disbanded.
Among these was John Stubbs, a man skilled not only in Latin, Greek, and Hebrew,
but also in the Oriental languages; he was convinced by G. Fox, when in Carlisle prison,
and became afterwards a faithful minister of the gospel.
But some of the soldiers, who had been convinced in their judgment,
not continuing steadfast, took the required oath, but not long outlived it;
for marching afterwards into Scotland, and passing by a garrison there, these,
thinking they had been enemies, fired at them, whereby several were killed.

G+++.+++ Fox now seeing the churches of his friends in the North settled,
passed from Swarthmore, (where he was about the beginning of this year,) to Lancaster,
and from thence to Synder-hill-green,
where he had a great meeting of some thousands of people,
among whom were many persons of note; and a general convincement there was,
so that a great number entered into the communion of those called Quakers:
with whom about this time, Ambrose Rigge was also united, who,
having been inclined to godliness from a youth, hearing G. Fox preach,
and being convinced of the truth of the doctrine he taught, received it,
and became a professor of it,
though for that reason he was cast out by his parents and relations.

We have seen the first rise of these Christians, called Quakers, in the North of England,
and how they increased under the oppression of persecution,
so that in most places in those parts meetings were settled:
it remains to relate how they spread further.

There were now about sixty ministers of the word raised among them,
and these went out in the service of the gospel, to turn people,
where they could have an opportunity, from darkness to the light,
and from the power of Satan to God.
Of these, Francis Howgill and Edward Burrough, went to London;
John Camm and John Audland, to Bristol; Richard Hubberthorn and George Whitehead,
to Norwich; Thomas Holmes into Wales, and others other ways.
G+++.+++ Fox, well knowing this to be a weighty work, writ a large epistle to these ministers,
wherein he admonished them to prudence, advising them, to know the seed of God,
which bruiseth the head of the serpent; also to know the power of God,
and the cross of Christ: to receive wisdom from God by the light; and not to be hasty,
or to run in their own wills, but to continue in patience.

I will first mention somewhat of the occurrences at London,
whither Edward Burrough and Francis Howgill, with Anthony Pearson,
who had been a justice of peace, came in the fore-part of the summer.
Howgill and Pearson, were the first of the people called Quakers,
that had a meeting in this great city,
where they preached in the house of one Robert Dring, in Watling-street;
and Burrough was, as I have been informed, that day in an assembly of a separate society.
Yet I have been told also, that Ruth, wife of William Crouch, merchant in London,
had said, that somewhat before that time,
there had been in the said house meetings of some few persons, of whom she was one;
and also Anne Downer, afterwards married to George Whitehead; that one Isabella Buttery,
with another woman, having spread in London some books, and among these one of G. Fox`'s,
called, '`The way to the Kingdom,`' had met with this small company,
of which were but two or three men, one of which was Amos Stoddard,
formerly a military officer, mentioned already;
and that the said Isabella sometimes spoke a few words in this small meeting.
But when F. Howgill and E. Burrough were come to London,
things began to have another face;
for they laid hold of all opportunities they could light on to preach the gospel.

At London there is a custom in summer time, when the evening approaches,
and tradesmen leave off working, that many lusty fellows meet in the fields,
to try their skill and strength in wrestling,
where generally a multitude of people stands gazing in a round.
Now it so fell out, that E. Borrough passed by the place where they were wrestling,
and standing still amongst the spectators,
saw how a strong and dexterous fellow had already thrown three others,
and was waiting for a fourth champion, if any durst venture to enter the lists.
At length, none being bold enough to try, E. Burrough stepped into the ring,
(commonly made up of all sorts of people,) and having
looked upon the wrestler with a serious countenance,
the man was not a little surprised, instead of an airy antagonist,
to meet with a grave and awful young man; and all stood as it were amazed at this sight,
eagerly expecting that would be the issue of this combat.
But it was quite another fight E. Burrough aimed at.
For having already fought against spiritual wickedness, that had once prevailed on him,
and having overcome in measure, by the grace of God,
he now endeavored also to fight against it in others,
and to turn them from the evil of their ways.
With this intention, he began very seriously to speak to the standers by,
and that with such a heart-piercing power,
that he was heard by this mixed multitude with no less attention than admiration;
for this speech tended to turn them from darkness to the light,
and from the power of Satan to God.
To effect this he labored with convincing words,
showing how God had not left himself without a witness,
but had given to man a measure of his grace,
and enlightened every one with the light of Christ.
Thus he preached zealously; and though many might look upon this as a novelty,
yet it was of such effect, that some were convinced of the Truth;
for he was a breaker of stony hearts, and therefore by a certain author, not unjustly,
called a son of thunder; though he also omitted not in due season,
to speak a word of consolation to those that were of a broken heart,
and of a contrite spirit.

But to thunder against sin and iniquity was his peculiar talent; insomuch,
that once preaching very zealously in meeting,
and perceiving there were some contrite souls, that wanted spiritually-refreshing food,
he was heard to intimate, that though his present speaking was not milk for babes,
yet he would remember such anon, and administer to them also;
but now he must thresh the whore.
And indeed he was one of those valiants, whose bow never turned back,
nor sword empty from the slaughter of the mighty;
for the Lord blessed his powerful ministry with very glorious success: nay,
he was such an excellent instrument in the hand of God,
that even some mighty and eminent men were touched
to the heart by the power of the word of life,
which he preached.
And although coals of fire, as it were, came forth of his mouth,
to the consuming of briers and thorns, and he passing through unbeaten paths,
trampled upon wild thistles and luxuriant tares;
yet his wholesome doctrine dropped as the oil of
joy upon the spirits of mourners in Zion,
Hence it was that Francis Howgill not unjustly said of him when deceased, '`Shall days,
or months, or years, wear out thy name, as though thou hadst had no being?
Oh nay: shall not thy noble and valiant acts, and mighty works which thou hast wrought,
through the power of him that separated thee from the womb, live in generations to come?
Oh yes!
The children that are yet unborn shall have thee in their mouths,
and thy works shall testify of thee in the generations who yet have no being.`'

The said Howgill, also an eminent and eloquent man, being now at London, went to court,
to utter what was in his mind to Oliver Cromwell.
And after having spoke to him,
he thought it convenient to express himself further in writing;
as he did in the following letter:

Friend,

I was moved of the Lord to come to thee, to declare the word of the Lord,
as I was moved of the Lord, and deal plainly with thee, as I was commanded,
and not to petition thee for any thing; but to declare what the Lord had revealed to me,
concerning thee; and when I had delivered what I was commanded, thou questioned it,
whether it was the word of the Lord or not, and soughtest by thy reason to put it off;
and we have waited some days since, but cannot speak to thee,
therefore I was moved to write to thee, and clear my conscience, and to leave thee.
Therefore hear the word of the Lord.
Thus saith the Lord, I chose thee out of all the nations,
when thou wast little in thy own eyes,
and threw down the mountains and the powers of the earth before thee,
which had established wickedness by a law, and I cut them down,
and broke the yokes and bonds of the oppressor, and made them stoop before thee,
and I made them as a plain before thee, that thou passed over them,
and trode upon their necks; but thus saith the Lord,
now thy heart is not upright before me, but thou takest counsel, and not of me;
and thou art establishing peace, and not by me; and thou art setting up laws,
and not by me; and my name is not feared, nor am I sought after;
but thy own wisdom thou establishest.
What, saith the Lord, have I thrown down all the oppressors, and broken their laws,
and thou art now going about to establish them again, and art going to build again,
that which I have destroyed?
Wherefore, thus saith the Lord, Wilt thou limit me, and set bounds to me, when,
and where, and how, and by whom I shall declare myself, and publish my name?
Then will I break thy cord, and remove thy stake, and exalt myself in thy overthrow.
Therefore this is the word of the Lord to thee, whether thou wilt hear or forbear.
If thou take not away all those laws which are made concerning religion,
whereby the people which are dear in mine eyes are oppressed,
thou shalt not be established; but as thou hast trodden down my enemies by my power,
so shalt thou be trodden down by my power, and thou shalt know that I am the Lord;
for my gospel shall not be established by thy sword, nor by thy law; but by my might,
and by my power, and by my Spirit.
Unto thee, this is the word of the Lord, Stint not the eternal Spirit,
by which I will publish my name, when and where, and how I will; for if thou dost,
thou shalt be as dust before the wind; the mouth of the Lord hath spoken it,
and he will perform his promise.
For this is that I look for at thy hands, saith the Lord,
that thou shouldst undo the heavy burdens, and let the oppressed go free.
Are not many shut up in prison, and some stocked, some stoned, some shamefully entreated?
And some are judged blasphemers by those who know not the Lord,
and by those laws which have been made by the will of man,
and stand not in the will of God;
and some suffer now because they cannot hold up the types,
and so deny Christ come in the flesh; and some have been shut up in prison,
because they could not swear, and because they abide in the doctrine of Christ; and some,
for declaring against sin openly in the markets, have suffered as evil-doers: and now,
if thou let them suffer in this nature by those laws, and count it just;
I will visit for those things, saith the Lord,
I will break the yoke from off their necks, and I will bring deliverance another way,
and thou shalt know that I am the Lord.

Moved of the Lord to declare and write this, by a servant of the Truth for Jesus`'s sake,
and a lover of thy soul, called,

Francis Howgill

The last of the First Month, about the ninth hour, waiting in James`' Park, at London.

How this was received, I am not acquainted; but this I have understood,
that some of Cromwell`'s servants, and among these one Theophilus Green, and Mary,
afterwards wife of Henry Stout, were so reached by F. Howgill`'s discourse,
that after some time they entered into the society of the Quakers, so called.

Now in the said letter, or speech, we find notice taken of laws made concerning religion:
these I do not look upon as made by the induction of Cromwell;
but such as were made in former times, which he could have altered,
if he would have done it: as afterwards many penal laws were abrogated,
under the reign of King William and Queen Mary, as will be said in its proper place.
For I do not find that in Cromwell`'s time any laws were made to constrain
people to frequent the worship of the public or national church.
But notwithstanding, the Quakers, so called, were imprisoned for refusing to swear,
or for not paying tithes to maintain the priests; and they were whipped like vagabonds,
for preaching in markets, or in other public places;
or they were fined for not taking off their hats before magistrates;
for this was called contempt of the magistracy;
and when for conscience sake they refused to pay such a fine,
either the spoiling of goods, or imprisonment became their share:
and thus always a cloak or cover was found to persecute them,
and malice never wanted pretenses to vex them.
And it also often happened that E. Burrough and F.
Howgill were opposed by the chiefest of several sects,
whereby disputes were raised,
which many times gave occasion for some of the hearers to embrace
the doctrine maintained by the said Burrough and Howgill;
which so enraged their enemies, that no slanders were spared,
and they sometimes branded them as witches.

In the meanwhile the people called Quakers so increased in London,
that they began to have settled meetings, the first of which was in Aldersgate Street,
at the house of one Sarah Sawyer.
The first among woman of this society that preached at London publicly,
was the already mentioned Anne Downer, afterwards married to one Greenwell,
and being become a widow,
in process of time entered into matrimony with George Whitehead,
as hath been hinted already.

The number of the said people increasing at London from time to time,
several meetings were now erected there, one of which was in the house of one Bates,
in Tower Street, and another at Gerard Robert`'s, in Thomas Apostles;
until the church became so great, that a house known by the name of the Bull and Mouth,
in Martin`'s le Grand, near Aldersgate, was hired for a meeting-house;
and it being a building that had belonged to some great man,
there was a large hall in it that would hold many people,
and so was very convenient for a meeting place.

Abundance of books were now spread against the Quakers, as seducers and false prophets;
and these written by the priests and teachers of several sects:
for they perceiving that many of their hearers forsook them,
left no stone unturned to stop it.
But the event did not answer their hope,
since Burrough and Howgill did not suffer those writings to go unanswered,
but clearly showed the malice and absurdities of those writers.

Leaving them busy with this work, we will take a turn toward Bristol,
to behold the performances of John Audland, and Thomas Airey;
who came thither in the month called July in this year,
and going into the meetings of the Independents and Baptists,
they found opportunity to preach Truth there, and also had occasion to speak to others,
so that many received their testimony.

From thence they went to Plymouth in Devonshire, and so to London,
where they met with John Camm; but after some stay there,
John Audland returned to Bristol with John Camm,
and found there a door opened for their ministry.
Among those that did receive their testimony, were Josiah Cole, George Bishop,
Charles Marshal, and Barbara Blaugdone,
concerning which persons more is to be said hereafter.
It was not long ere F. Howgill and E. Burrough, having gathered a church at London,
came also to Bristol, where persecution now began to appear with open face:
for the magistrates commanded them to depart the city and the liberties thereof;
to which they answered, that they came not in the will of man;
and that when He who moved them to come thither, did move them also to depart,
they should obey; that if they were guilty of the transgression of any law,
they were not unwilling to suffer by it; that they were freeborn Englishmen,
being free from the transgression of any law;
and that if by violence they were put out of the city, they were ready to suffer,
and would not resist; and so they departed out of the presence of the rulers.
But now the priests, especially one Ralph Farmer, began to incite and enrage the people,
and to set the city, as it were, on fire.

Hence it was that J. Camm and J. Audland, intending to have a meeting at Brislington,
about two miles from Bristol, and passing over a bridge,
were assaulted by the rabble of the city, and several apprentices of Farmer`'s parish,
who having got notice of their coming, were gathered there,
and violently abused them with beating, kicking, and a continual cry, knock them down,
kill them, or hang them presently.
Thus they were driven back, and forced into the city again,
narrowly escaping with their lives.
But the tumult did not yet cease; for some of the multitude were heard to say,
that they should find more protection from the magistrates, than those strangers,
viz. Camm and Audland.
But the officers of the garrison, thinking it unwarrantable to permit such a tumult,
since it was not without reason to be feared, that the royalists,
or abettors of King Charles,
might take hold of such an opportunity to raise an insurrection,
caused three of the ringleaders to be seized; but this made such a stir,
that the next day more than five hundred people, as it was thought,
were gathered together in a seditious manner,
so that their companions were set at liberty.
This made the tumultuous mob more bold and saucy,
the rather because they saw that the magistrates,
hearing that J. Camm and J. Audland not only had kept a meeting at Brislington,
but also had visited some in their houses at Bristol, had bid them to depart the town.

Now the riotous multitude did not stick to rush violently into the houses of the Quakers,
so called, at Bristol, under a pretense of preventing treasonable plottings.
And when some in zeal told the priests, these were the fruits of their doctrine,
they incited the people the more,
and induced the magistrates to imprison some of those called Quakers.
This instigated the rabble to that degree,
that now they thought they had full liberty to use
all kind of insolence against the said people;
beating, smiting, pushing, and often treading upon them, till blood was shed:
for they were become a prey to every malapert fellow,
as a people that were without the protection of the law.
This often caused a tumult in the town; and some said,
(not without good reason,) that the apprentices durst not have left their work,
had not their masters given them leave.
And a certain person informed the mayor and aldermen upon his oath,
that he had heard an apprentice say, that they had leave from their masters,
and were encouraged; for alderman George Heliier had said,
he would die rather than any of the apprentices should go to prison,
Now an order of sessions came forth, that the constables do once in every fortnight,
make diligent search within their several wards,
for all strangers and suspicious persons; and that all people be forewarned,
not to be present at any tumult, or other unlawful assembly,
or gather into companies or multitudes in the streets,
on pain of being punished according to law.
But this order was to little purpose, for the tumultuous companies and riots continued;
and once when a proclamation was read in the name of the Lord Protector,
requiring everyone to depart, some of the rioters were heard to say,
'`What do you tell us of a Protector?
tell us of King Charles.`'
In the meanwhile the Quakers, so called, were kept in prison,
and it plainly appeared that the order against unlawful
assemblies was leveled against their meetings:
and though the magistrates pretended that they must answer for it to the Protector,
if they did let the Quakers alone without disturbing their meetings, which at that time,
for the most part, were silent, and nothing was spoken,
but when now and then one of their ministers from abroad visited them;
yet this was not at all agreeable with the Protector`'s
speech he made on the 12th of the month called September,
to the parliament, in the painted chamber, where he spoke these words:

Is not liberty of conscience in religion a fundamental?
so long as there is liberty for the supreme magistrate,
to exercise his conscience in erecting what form of church
government he is satisfied he should set up,
why should he not give it to others?
Liberty of conscience is a natural right, and he that would have it, ought to give it,
having liberty to settle what he likes for the public.
Indeed that hath been the vanity of our contests: every sect saith.
Give me liberty; but give it him, and to his power he will not yield it to any body else.
Where is our ingenuity?
Truly that is a thing that ought to be very reciprocal.
The magistrate hath his supremacy, and he may settle religion according to his conscience.
And I may say to you, I can say it,
all the money in the nation would not have tempted
men to fight upon such an account as they have engaged,
if they had not had hopes of liberty, better than they had from episcopacy,
or than would have been afforded them from a Scottish Presbytery, or an English either,
if it had made such steps,
or been as sharp and rigid as it threatened when it was first set up.
This I say is a fundamental: it ought to be so.
It is for us and the generations to come.

Cromwell spoke more in confirmation hereof; and indeed he would have been a brave man,
if really he had performed what he asserted with binding arguments.
But though now he seemed to disapprove the behavior of Presbytery,
(for then he was for Independency,) yet after some time he courted the Presbyterians;
and these fawning upon him from the pulpit,
as their preserver and the restorer of the church,
he suffered the Quakers to be persecuted under his government,
though he pretended not to know it, when he might easily have stopped it.
But by hearkening to the flatteries of the clergy, at length he lost his credit,
even with those who with him had fought for the common liberty;
and thus at last befell him after his death,
what he seemed to have imprecated on himself in the foregoing speech,
if he departed from allowing; due liberty.
For he further said,
that many of the people had been necessitated to
go into the vast howling wilderness in New England,
for the enjoyment of their liberty; and that liberty was a fundamental of the government;
adding, that it had cost much blood to have it so, and even the hazarding of all.
And in the conclusion he said,
that he could sooner be willing to be rolled into his grave, and buried with infamy,
than give his consent to the willful throwing away of that government;
so testified unto in the fundamentals of it.
Now who knows not what infamy befell him afterwards,
when in the reign of King Charles the Second, it is said, his corpse was dug up,
and buried near the gallows, as may be further mentioned in its due place?

But I return now to Bristol, where several were kept in prison still,
and no liberty granted them; nay,
they were even charged with what they utterly denied themselves to be guilty of.
Among these, one John Worring was accused of having called the priest, Samuel Grimes,
a devil: but Worring denied this, though he did not stick to say,
he could prove somewhat like it by his own words.
And it being asked him how, he answered, that the priest had said at the meeting,
that in all things he did, he sinned; and if in all things,
then as well in his preaching, as in other things; and he that sinneth is of the devil.
If you will not believe me, believe the Scriptures.
It may be easily conjectured that this answer did not please the priests`' followers,
and therefore Worring and some others were kept in prison:
and among these also Elizabeth Marshall, who in the steeple-house,
after the priest John Knowls had dismissed the people with what is called the blessing,
spoke to him, and said, '`This is the word of the Lord to thee.
I warn thee to repent, and to mind the light of Christ in thy conscience.`'
And when the people, by order of the magistrates then present, violently assaulted her,
giving her many blows with staves and cudgels, she cried out,
'`The mighty day of the Lord is at hand, wherein he will strike terror on the wicked.`'
Some time before she spoke also in the steeple-house to the priest Ralph Farmer,
after he had ended his sermon and prayer, and said,
"`This is the word of the Lord to thee.
Woe, woe, woe from the Lord to them who take the word of the Lord in their mouths,
and the Lord never sent them.`'

A good while after this, the magistrates gave out the following warrant:

City of Bristol.

To all the constables within this city, and to every one of them.

Forasmuch as information hath been given us, that John Camm, and John Audland,
two strangers, who were commanded to depart this city, have, in contempt of authority,
come into this city again, to the disturbance of the public peace:
these are therefore to will and require you forthwith to apprehend them,
and bring them before us to be examined, according to law.
Given this 22d of January, 1654.
Signed,

William Cann, Richard Vickirs, Dept.
Mayor.
Joseph Jackson, Henry Gibbs, Gabriel Sherman, John Lock.

Camm and Audland had departed the town before this time, having never been commanded,
(as the warrant saith,) to depart the city, either by the magistrates themselves,
or by any other at their command;
though F. Howgill and E. Burrough had been required to do so.
So this warrant proving ineffectual,
the magistrates caused another to be formed in these words:

City of Bristol.

To the constables of the peace of the ward of +++________+++ and to every of them.

Forasmuch as information hath been given us upon oath,
that certain persons of the Franciscan order in Rome,
have of late come over into England, and under the notion of Quakers,
drawn together several multitudes of people in London; and whereas certain strangers,
going under the names of John Canrn, John Audland, George Fox, James Nayler,
Francis Howgill, and Edward Burrough, and others unknown,
have lately resorted to this city, and in like manner, under the notion of Quakers,
drawn multitudes of people after them, and occasioned very great disturbances amongst us;
and forasmuch as by the said information it appeareth to us to be very probable,
and much to be suspected, that the said persons so lately come hither,
are some of those that came from Rome, as aforesaid;
these are therefore in the name of his highness, the lord protector,
to will and require you to make diligent search through
your ward for the aforesaid strangers,
or any of them, and all other suspected persons,
and to apprehend and bring them before us, or some of us,
to be examined and dealt with according to law: hereof fail you not.
Given the 25th of Jan. 1654. Signed,

John Gunning, Mayor.
William Cann, Gabriel Sherman, Joseph Jackson, Henry Gibbs, John Lock, George Hellier,
Richard Vickirs.
Gabriel Sherman,

Hereunto these magistrates affixed their seals;
and that alderman Sherman might be sure his name was down, he wrote it twice.
How frivolous this pretense of persons of the Franciscan order was,
even a child might perceive;
for the Quakers were by this time so multiplied in the North of England,
that they could no more be looked upon as an unknown people.
And as for G. Fox, and James Nayler, they had not yet been at Bristol,
and therefore it seemed absurd to seek for them there.
But it was thought expedient to brand the Quakers with odious names,
that so under the cloak thereof,
they might be persecuted as disturbers of the public peace:
as appeared when one Thomas Robertson, and Josiah Cole, being at Nicholas`' steeple-house,
and standing both still without speaking a word, until the priest Hazzard had ended,
and dismissed the people, were very rudely treated; for Thomas then lifting up his voice,
was presently, even when the word was yet in his mouth, struck on the head by many,
as was also his companion, though he did not attempt to speak.
But Thomas, after being a little recovered of a heavy blow, began to speak again,
and said to the people, '`Tremble before the Lord, and the word of his holiness.`'
But this so kindled their anger, that they were both hurried out of the steeple-house,
and with great rage driven to the mayor`'s, who commanded them both to Newgate prison.

Not long after one Jeremy Hignel, being in his shop attending his calling,
was sent for by the mayor and aldermen, to come before them; which he presently doing,
the mayor asked him whether he knew where he was; he answered he did.
Then the mayor asked where; he replied, '`In the presence of the Lord.`'
'`Are you not,`' said the mayor, '`in the presence of the Lord`'s justices?`'
his answer was, '`If you be the Lord`'s justices, I am.`'
Whereupon one of the aldermen said, without any more words passing at that time,
'`We see what he is; take him away to Newgate.`'
For since he did not take off his hat, it was concluded he was a Quaker,
and this was counted cause enough to send him to prison;
and so he was immediately brought thither,
where the keeper received him without a mittimus,
and kept him close prisoner nineteen days, permitting none to come to him but his wife.

No better was the treatment of Daniel Wastfield, who, being sent for by the mayor,
appeared before him, and alderman Vickirs; then the mayor said to him, '`Wastfield,
come hither;`' and he thereupon drawing near, the mayor asked him three several times,
'`What art thou?`'
Though he knew him well enough, having called him by his name as above said.
Wastfield answered, '`I am a man.`'
'`But what`'s thy name?`'
said the mayor.
'`My name is Daniel Wastfield,`' answered he.
Then said the mayor to one of his officers,
'`Take him and carry him to Newgate;`' further adding,
that he came thither to contemn justice: to which Wastfield replied, '`No,
I came hither in obedience to thy order;`' for the mayor had sent for him,
as hath been said.
Thus he was carried away without a mittimus, the mayor saying his word was a mittimus;
and he was kept a close prisoner thirty-three days,
and none suffered to come to him but his servants, notwithstanding he was a widower,
and must now leave his house and trade to their management;
and a child of his died in the meanwhile, and was buried, and he kept from seeing it.

The magistrates having thus begun persecution,
became from time to time more vigorous in it, insomuch,
that several others were imprisoned, and among these Christopher Birkhead, who,
standing still in Nicholas`' steeple-house, with his hat on,
and being asked by the priest, Ralph Farmer, what he stood there for; answered,
'`I stand in obedience to the righteous law of God in my conscience;
I have neither offended the law of God, nor of the nation.
A wonderful and horrible thing is committed in the land.`'
More he would have spoken, but was stopped with beating and thrusting,
and so carried to prison.

Now the magistrates were not a little incited to persecution by the said Farmer;
and there being several that were very bold,
they did not stick to write sharp letters to him;
and his indecent carriage was also told him to his face, by word of mouth,
in the steeple-house, after sermon; and those who did so, were sent to prison.
At length these prisoners were brought to trial;
and since it could not be proved that they had transgressed any law,
some of the magistrates seemed inclined to set them at liberty,
if they would have declared that they were sorry for what they had done.
Among them was also one William Foord, and nothing material being found against him,
but that he was one of those called Quakers,
he was accused of having kept a stranger at work; which he however esteemed to be lawful,
since his trade of wool-combing did not belong to the company of milliners,
who complained of him.
Yet he was asked whether he was sorry for what he had done; which denying,
as well as those who had reproved the priests,
he that was not guilty was sent to prison again,
as well as those that were pretended to be so.
Among these last was also Sarah Goldsmith, who,
from a well meant zeal to testify against pride, having a coat of sackcloth,
and her hair disheveled, with earth or dust strewed on her head,
had gone through the city without receiving any considerable harm from the people,
because some looked upon her to be crack-brained.
There was also one Temperance Hignel, who,
having said in the steeple-house to the priest, after he had ended his sermon,
'`Woe from the Lord God to thee, Jacob Brint,`' was presently struck down,
and so violently abused, that blood ran down her face, and she,
being committed to prison, fell sick; and when they saw her life was in danger,
she was carried out in a basket, and died three days after.
The reason she gave, when in prison, why she spoke in that manner to the priest was,
that he had scarce any hearers, but what were swearers, drunkards, strikers, fighters,
and railers, etc.
And that therefore his ministry was in vain, since he preached for gain;
whereas he himself ought to have brought forth good fruits.

How long the others were kept in prison, I do not know certainly; however,
it was a pretty long time; for George Bishop, and Dennis Hollister,
who formerly had been a member of the parliament, and three others,
put all these transactions in writing at large, and sent it to the magistrates,
in hopes that thereby they might see the evil of persecution: but this proving in vain,
they gave it out in print five months after,
that so every one might know how the Bristollers treated their inhabitants,
which was to that degree, that an author said,
'`Was such a tyrannical iniquity and cruelty ever heard of in this nation`'
Or would the ministers under king Charles have ventured to do so I Was
not Stafford but a mean transgressor in comparison of these?`'
And though Archbishop Laud was beheaded,
yet it could not be proved that the Episcopalians had persecuted so fiercely,
as these pretended asserters of liberty of conscience had done, who,
being got into possession of the power, did oppress more than those they had driven out.
This made the persecuted, some of which formerly had also fought for the common liberty,
the more in earnest against those that were now in authority.

But I will turn away from Bristol towards Norwich, whither Richard Hubberthorn,
and George Whitehead were gone.
Here it happened, that R. Hubberthorn, having spoken to a priest in a steeple-house yard,
and not having taken off his hat before the magistrates, was imprisoned in the castle,
where he was kept great part of the following year, and in the meanwhile,
writ several epistles of exhortation to his friends; and his companion,
G+++.+++ Whitehead`'s preaching had such an effect,
that a meeting of their friends was settled in that city.

But before I go on,
it will be convenient to give some account of the quality of these two persons:
R+++.+++ Hubberthorn was born in the North of Lancashire,
and descended from very honest parents:
his father was a yeoman of good reputation among men, and Richard was his only son,
and from a youth inclined to piety.
Being come to man`'s estate, he became an officer in the parliament`'s army,
and from a zeal for godliness, preached sometimes to his soldiers.
But entering afterwards into the society of the Quakers so called,
he left his military employment, and testified publicly against it;
for he was now become a soldier under another banner, viz. that of Christ Jesus,
Prince of Peace; not fighting as formerly, with the outward sword,
but with the sword of the Spirit, which is the word of God.
In his ministry he had an excellent gift, and though not so loud in voice as some others,
yet he was a man of a quick understanding, and very edifying in his preaching.

G+++.+++ Whitehead, (who, whilst I write this, is yet alive,) was trained up to learning,
and though but a youth, instructed others in literature,
and continued in that calling sometime after he came to be convinced
of that Truth which was preached by the professors of the light;
and he strove to bring up children in the fear of the Lord.
But before this change he was a diligent hearer of the world`'s teachers,
and usually frequented the steeple-house at Orton in Westmoreland:
yet the singing of David`'s psalms became so burdensome to him,
that sometimes he could not join therewith;
for he saw that David`'s conditions were not generally
suitable to the states of a mixed multitude;
and he found himself to be short of what they sung.
This consideration brought him into such a strait,
that often he durst not sing those psalms the priests gave their hearers to sing,
lest he should have told lies unto God.
Now also he began to see that the priests`' lives
and practices did not agree with their doctrine;
for they themselves spoke against pride and covetousness, and yet lived in them.
This likewise made him go to hear some that were separated from the national church,
and got into a more specious form of godliness; but he soon saw, that,
though there was a difference in the ceremonial part,
and that these had a more true form of words than the priests,
yet they were such as ran before they were sent by God,
speaking peace to that nature in him, wherein he felt no true peace.
And when he was about seventeen years of age, which was in the year 1652,
he first heard the doctrine of Truth preached by
those that were reproachfully called Quakers;
and their testimony wrought so powerfully on his mind, that he received it,
and so entered into their communion.
Now he found, that to grow up in the true wisdom,
and to become wise in the living knowledge of God, he must become a fool to that wisdom,
wherein he had been feeding upon the tree of knowledge,
having in that state no right to the tree of life: and he continuing in faithfulness,
it pleased the Lord to ordain him a minister of the gospel:
in which service he acquitted himself well, to the convincing of others,
and the edification of the church.

But now leaving him, let us go and see what happened at Oxford in the year 1654.
At the latter end of the month called June, there came two women,
named Elizabeth Heavens, and Elizabeth Fletcher.
These spoke in the streets to the people, and in the college they exhorted the scholars,
who wickedly requiting their zeal,
violently pushed Elizabeth Fletcher against a gravestone,
and then threw her into the grave; and their malice grew to that pitch,
that they tied these two women together, and drove them under the pump:
and after their being exceedingly welted with pumping water upon them,
they threw them into a miry ditch, through which they dragged Elizabeth Fletcher,
who was a young woman, and so cruelly abused her,
that she was in a painful condition till her death, which fell out not long after.
Some short time after this rude encounter, she and her companion,
on a First-day of the week, went into the steeple-house at Oxford,
and when the priest had ended, they began to admonish the people to godliness:
but two justices there present, commanded them to be taken into custody,
and carried to the prison called Bocardo, where none but felons were used to be lodged.
The justices desiring the magistrates to meet on this account,
the mayor would not meddle with it, but said,
'`Let those who have committed them deal with them according to law,
if they have transgressed any;`' adding that he had nothing to say against them;
but that he would provide them with victuals, clothes, or money, if they wanted any.
Yet he came into the assembly where these women were examined,
and whither the vice-chancellor of the university was also required to come,
who charged them, that they blasphemed the name of God, and did abuse the Spirit of God,
and dishonored the grace of Christ: and asking them whether they did read the Scriptures,
they answered yea they did.
Then he asked whether they were not obedient to the power of the magistrate;
to which their answer was, they were obedient to the powder of God,
and to the power that was of God they were subject for conscience-sake.
'`Well,`' said the vice-chancellor, '`you profane the word of God,
and I fear you know not God, though you so much speak of him.`'
Then the women being made to withdraw,
it was concluded that there w-as matter enough for their commitment and punishment,
and agreed that a paper should be drawn up for their being whipped out of the city.
When this was done, it was presented to the mayor to set his hand to it; but he refused,
and said he was not willing to do so.
Then one of the justices said, that it was the privilege of the city,
that if any vagrant was taken within the franchises and liberties thereof,
a paper must be drawn up, that such a one, mayor, had committed such and such persons;
and that then it was to be sealed with the office seal.
But the mayor refused this as well as the other.
Which made some say, that if he would not, it should be done by them.
And then it was agreed upon, that they should be whipped soundly;
which was performed the next morning, though with much unwillingness in the executioner:
and the mayor had no hand in it.

But leaving these, I will turn to another, one Barbara Blaugdone,
of whom mention hath already been made,
that she was one of those that received the Truth,
by the ministry of John Audland and John Camm.
She was from her youth inclined to godliness, and her employment was to instruct children.
But being entered into the society of those called Quakers, she became plain,
both in speech and habit, and thereupon the children she taught, were taken from her;
and, going sometimes into the steeple-houses,
to bear testimony against their formalities, she was put in prison,
and kept there a quarter of a year at a time.
Afterwards she led a very severe life, and abstained from all flesh, wine, and beer,
drinking only water for the space of a whole year.
In the meanwhile she grew up and prospered in true piety.
Once it happened,
that coming from a meeting that was at George Bishop`'s house at Bristol,
a rude fellow ran a knife, or some sharp instrument, through all her clothes,
into the side of her belly, which if it had gone but a little further,
might have killed her.
Then she went to Marlborough, where, exhorting people,
in the steeple-houses and other places, to fear God,
she was put into prison for the space of six weeks,
and there she fasted several days and nights.
When she was released, she went to Isaac Burges, the man that committed her,
and discoursing with him, he was really convinced of the Truth,
but could not resolve to take up the cross;
yet he was afterwards very loving to her friends, and stood by them upon all occasions,
never more persecuting any of them: and coming some time after to Bristol,
he went to her house and confessed, that he knew her doctrine was Truth,
but that he could not take up the cross to walk in that way.
A while after she went into Devonshire, to Moulton, Barnstable, and Bediford,
in all which places a prison was her lot.
She went also to him, that after was earl of Bath, where, being acquainted,
she had formerly vainly spent much time,
but now she was moved to call this family to leave off their vanity.
And she asked to speak with the lady; but one of the servants that knew her,
bid her to go to the back door, and their lady would come forth that way,
to go into the garden.
Barbara being come thither, a great mastiff dog was set loose upon her;
and he running fiercely, as if to devour her, turned suddenly,
and went away crying and halting, whereby she clearly saw the hand of the Lord in it,
to preserve her from this danger.
The lady then came and stood still, hearing what Barbara spoke,
and gave her thanks for her exhortation, yet did not invite her to come in,
though she often had been lodged there, and had eaten and drank at her table.

Then Barbara went to Great Torrington, and, going into the steeple-house,
spoke somewhat to the people by way of exhortation;
but not having sufficient opportunity to clear herself, went to her lodging,
and sat to writing.
After noon the constables came to her, and took away what she had written,
and commanded her to go along with them to their worship.
To which she answered, that they would not suffer her to speak there,
and that she knew no law that could compel her to go thither twice in a day;
and that they all knew she was there in the morning.
Being thus unwilling to go, the next day the mayor sent for her; when come,
she found him moderate, and loth to send her to prison; but the priest being present,
was very eager, and said she ought to be whipped for a vagabond.
She then bid him prove where ever she asked any one for a bit of bread;
but he said she had broken the law by speaking in their church;
and he so pressed the mayor, that at length he made him write a mittimus,
and send her to Exeter prison, which was twenty miles distant:
there she remained for some time, until the assizes came,
but was not brought forth to a trial.
And after the sessions were over,
she was put to lodge one night among a great company of gypsies,
that were then in prison; and the next day the sheriff came with a beadle,
who brought her into a room, where he whipped her till the blood ran down her back,
and she never startled at a blow; but sang aloud,
and was made to rejoice that she was counted worthy to suffer for the name of the Lord;
which made the beadle say, '`Do ye sing?
I will make you cry by and by;`' and with that he laid on so hard,
that one Ann Speed seeing this began to weep;
but Barbara was strengthened by an uncommon and more than human power,
so that she afterwards declared if she had been whipped
to death in the state she then was,
she should not have been terrified or dismayed.
And the sheriff seeing that all the wrath of man could not move her,
bid the fellow leave oft`" striking; and then Ann Speed was suffered to dress her stripes.
The next day she was turned out with all the gypsies,
and the beadle followed her two miles out of the town; but as soon as he left her,
she returned back, and went into the prison to see her friends,
that were prisoners there, and having visited them, she went home to Bristol.

But by the way coming to Bediford, she was taken up, and put into the town-hall,
and searched to see whether she had either knife or scissors about her.
Next day she was brought before the mayor, who discoursing much with her,
had a sense of what she spoke to him; and at last he set open two doors,
one right against the other, and said he would give her her choice,
which she would go out at; whether she would go forth to prison again, or go home.
And she told him, that she would choose liberty rather than bonds.
So she went homeward, and then he took his horse and followed; and overtaking her,
would have had her ride behind him; but when any whom he knew met them,
he would slacken his pace; and as soon as they were passed, he came up again to her;
which she perceiving, refused to ride behind him;
yet he rode three or four miles with her, and discoursed all the way:
and when they parted, she kneeled down and prayed for him,
all which time he was very serious, and afterwards grew very solid and sober.
She writ once to him; but not long after, he died.

Being come home she was moved to go to Basingstoke,
to endeavor to obtain liberty for two of her friends, viz. Thomas Robinson,
and Ambrose Rigge,
who were taken up at the first meeting that their friends had had there.
But when she came thither the entrance of the prison was denied her.
And she having a letter from John Camm to them, put it in at the chink of the door,
and then she went to the mayor to desire their liberty; he told her,
that if he saw the letter which she brought them, they should have their liberty.
She then said he should see it; and so went and fetched it; which he having read,
told her that she should have her brethren out;
but that he could not let them out presently.
Yet it was not long before her friends had their liberty.

Now leaving Barbara for some time, we return to Miles Halhead.
In the First month of this present year, he was moved to go to Ireland,
and declare the word of the Lord there; and speaking of this to James Lancaster,
and Miles Bateman, they quickly resolved to keep him company,
and so they went for Ireland; where they proclaimed the Truth in cities, towns, villages,
and before magistrates, as occasion offered; and their testimony was received by many.
After they had discharged themselves, they returned to England,
where Miles soon found himself moved to go to Scotland.
In his way thither, he met his friend James Lancaster, who was very free to go with him;
and so they went into Scotland;
but were not the first of those called Quakers in that country; for Christopher Fell,
George Wilson, and John Grave, had been there before;
so that a little church of those of their communion, was already planted in that kingdom,
before Halhead went thither: and one Alexander Hamilton had,
a year before ever any Quakers appeared in Scotland, erected a meeting at Drumbowy,
and also at Heads, and he received their testimony when they came there,
as also his wife Joan, James Gray, James Miller, and others.
I find also that Scotland was early visited by Catherine Evans, and Sarah Chivers,
two eminent women, of whom something extraordinary is to be related in its due time.

But I return to J. Lancaster, and Miles Halhead, who being come to Dumfries,
went on a First-day of the week into the steeple-house in that town,
where seeing many people gathered together, howling and crying,
and making great lamentation, as if they had been touched with a sense of their sins.
Miles was silent until their worship was done; but then,
being grieved with their deceit and hypocrisy, spoke as he was moved;
but met with great opposition, many of the people being in such a rage,
that they drove him and his companion out of the town, near to the side of a great river;
and it was intended that the women of the town should stone them;
but they prevented this by wading through the river.

Being thus safely passed the water, they went to Edinburgh and Leith,
where they stayed about ten days.
During that time.
Miles spoke to the people when occasion offered; as also to the garrisons,
and to the captains and officers of the army, who were much affected,
and confessed that the Lord had been very good unto them; for Miles`'s message was,
that the anger of the Lord was kindled against them,
because they had not performed their promises,
which they made to him in the day of their distress,
when their enemies encompassed them on every side; for then the Lord delivered them,
and gave them victory; but they had returned him evil for good,
and committed violence against those he sent to declare his word amongst them.
This being told them at large by Miles, he went to Glasgow and Stirling,
where he also spoke as he was moved; and so returned to England.

But before I leave Scotland, may say, that as the first meetings were at Drumbowy,
and Heads, so it was not long ere meetings were settled also at Garshore, at Edinburgh,
and also at Aberdeen.
The first Scotch preachers of those called Quakers, I find to have been William Osborn,
Richard Ree, and Alexander Hamilton, already mentioned.
Of the said Hamilton, I may mention a singular instance: after he and his wife,
with her and his sister, had separated themselves from the society of the Independents,
it happened that Thomas Charters, a teacher of that sect, at Kilbride,
not far from Drumbowy, seeing that he could not draw Hamilton,
and those of his family back again, threatened them with excommunication,
and appointed a day for it, giving notice thereof to Hamilton some days beforehand.
Hamilton warned him to forbear, or else the anger of God would seize on him.
But he answered, '`It is but Alexander Hamilton that saith so.`'
To which Hamilton returned in the presence of many witnesses, that it was not only he,
but what he had said was of the Lord.
But Charters persisting in what he intended,
and walking two days before the appointed time in the steeple-house yard,
where his horse was feeding, stepped to him to stroke him; but the horse growing wanton,
gave Charters such a violent kick on his side,
that he died about the same hour which was appointed by him for the excommunication.
Whether this case happened in the year I now describe, I am not certain; but however,
it was either in, or near it.

This year Miles Halhead came to Berwick in Northumberland,
and went to the mayor of that town, and spoke to him in his shop thus; '`Friend,
hear what the servant of the Lord hath to say unto thee.
Give over persecuting the Lord`'s servants,
whom he doth send in love to this town of Berwick,
to show you the way that leads to life eternal.
I charge thee, O man, touch not the Lord`'s anointed, nor do his prophets any harm,
least thou procure the anger of the living eternal God against thee.`'
This bold language so offended the mayor, that he sent Miles to prison,
where he was about ten weeks, and then was brought to the sessions,
where a bill drawn up against him, was read in open court:
but he denied the contents thereof, yet said, '`But what I said to the mayor of this town,
I will not deny.`'
And then he related the aforesaid words he spoke to the mayor.
Whereupon the recorder said, '`Sirs, as I understand by his own words,
if he cannot prove the mayor of the town a persecutor,
in my judgment he hath wronged him.`'
To this Miles answered, '`If the mayor of this town of Berwick,
dare say in the presence of the Lord, whose presence is here, that he is no persecutor,
but the persecuting nature is slain in him,
I will be willing to abide the judgment of the court.`'
Then the clerk of the court said, Mr. Mayor, if you will say that you are no persecutor,
but the persecuting nature is slain in you,
he is willing to abide the judgment of the court.`'
To this the mayor answered, '`I know not what to do; I would I had never seen him;
I pray you, let him go, and let us be no more troubled with him.`'
Then Miles said that he would prove this mayor of
Berwick the greatest persecutor in town or country.`'
I was once, +++[+++thus he went on,]
committed to the prison in this town before,
by some of the justices that are now in this court; but thou, O man,
hast exceeded them all; thou hast committed me, and kept me in close prison,
for about ten weeks, for speaking to thy own person, in thy own shop.
Now I make my appeal to the recorder of this town of Berwick,
as I am a freeborn Englishman, whether my imprisonment be legal,
according to the law of this nation, or not?`'
Then the recorder of the town stood up and said,
'`It is not very legal for any minister of the law to imprison any man in his own cause.`'
Then the court cried, '`Take him away.`'
The chief priest of the town then stood,
and desired the court that he might ask Miles one question; to this Miles said,
'`The Lord knows thy heart, O man,
and at this present has revealed thy thoughts to his servant;
and therefore now I know thy heart also, thou high priest,
and the question thou wouldst ask me: and if thou wilt promise me before the court,
that if I tell thee the question thou wouldst ask me, thou wilt deal plainly with me,
I will not only tell thee thy query, but I will answer it.`'
Then the priest said he would.
Then Miles proceeded: '`Thy question is this:
thou wouldst know whether I own that Christ that died at Jerusalem, or not?`'
To this the priest wondering, said, '`Truly that is the question.`'
Then Miles said, '`According to my promise, I will answer it before this court:
in the presence of the Lord God of heaven,
I own no other Christ than him that died at Jerusalem,
and made a good confession before Pontius Pilate,
to be the light and way that leads fallen man out of sin and evil, up to God eternal,
blessed forevermore.`'
More questions were not asked him, but the jailer was commanded to take him away.
Yet within a short time, the court gave order to release him.
Then going to Newcastle, he returned to his wife and children at Mount-joy,
where we will leave him for some time, and in the meanwhile return again to G. Fox,
whom we left at Synder-hill-green, from hence he travelled up and down in Yorkshire,
as far as Holderness, visiting his friends,
and finding the churches in a flourishing state.
To relate all his occurrences there, would be beyond my pale.

Passing then through the countries, he went to Lincolnshire,
and to the meeting where he was, came the sheriff of Lincoln,
who made great contention for a time; but at length the power of the Lord so reached him,
that he was convinced of the Truth, as were several others also that did oppose him.

Whilst G. Fox was in this country, the church of his friends increased,
and many received the doctrine preached by him, and amongst these,
was one sir Richard Wrey, with his brother, and the brother`'s wife,
who both continued steadfast till they died; but sir Richard found this way so narrow,
that he afterwards ran out;
for persecution in that time fell so fast on those called Quakers,
that none could abide in their society, but such as were willing to hazard all.

G+++.+++ Fox now went to Derbyshire, and the above said sheriff of Lincoln traveling with him,
they came into Nottinghamshire, and so into the Peak country,
where having a meeting at Thomas Hammersley`'s, several ranters came and opposed him;
and when he reproved them for swearing, they said Abraham, Jacob, and Joseph swore.
But though G. Fox did not deny this, yet he said, '`Christ, (who said before Abraham was,
I am,) saith.
Swear not at all.
And Christ ends the prophets, as also the old priesthood, and the dispensation of Moses;
and he reigns over the house of Jacob, and of Joseph, and saith, Swear not at all.
And God when he bringeth in the first-begotten into the world, saith,
Let all the angels of God worship him, to wit, Christ Jesus, who saith.
Swear not at all.
And as for the plea that men make for swearing to end their strife, Christ, who says.
Swear not at all, destroys the devil and his works, who is the author of strife;
for that is one of his works.
And God said, This is my beloved Son in whom I am well pleased, hear ye him.
So the Son is to be heard, who forbids swearing: and the apostle James,
who did hear the Son of God, and followed him, and preached him, forbids also all oaths.`'
Thus G. Fox prevailed, and many were convinced that day.
It is remarkable that Thomas Hammersley, being summoned upon a jury,
was admitted to serve without an oath; and when he being foreman brought in the verdict,
the judge did declare, that he had been a judge so many years,
but never heard a more upright verdict than that the Quaker had then brought in.

G+++.+++ Fox traveling on, came to Swanington, in Leicestershire,
where there was a general meeting, to which many of his friends came from several parts,
and among these, J. Audland, and F. Howgill, from Bristol; and E. Burrough, from London.
After this, G. Fox came to Twycross, and some ranters there sang and danced before him;
but he reproved them so earnestly, that some of them were reached,
and became modest and sober.

Then he went to Drayton, his birth-place, to visit his relations;
where Nathaniel Stevens, the priest, having gotten another priest, sent for him.
G+++.+++ Fox, having been three years abroad, knew nothing of their design,
but yet at last he went to the steeple-house yard,
where the two priests had gathered abundance of people;
and they would have had him gone into the steeple-house:
but he asked them what he should do there; and it was answered him,
Mr. Stevens could not bear the cold.
At which G. Fox said, '`He may bear it as well as I.`' At last they went into a great hall,
R+++.+++ Farnsworth being with him,
where they entered into a dispute with the priests concerning their practice,
how contrary it was to Christ and his apostles.
The priests asked where tithes were forbidden, or ended;
whereupon G. Fox showed them out of the epistle to the Hebrews, chap.
vii. that not only tithes, but the priesthood that took tithes, was ended;
and that the law was ended and dis-annulled, by which the priesthood was made,
and tithes were commanded to be paid.
Moreover, he, knowing Steven`'s condition, laid open his manner of preaching, showing,
that he, like the rest of the priests, did apply the promises to the first birth,
which must die; whereas the promises were to the seed, not to many seeds,
but to the one seed, Christ, who was one in male and female:
for all were to be born again, before they could enter into the kingdom of God.
Then Stevens said, that he must not judge so.
But G. Fox told him, he that was spiritual judged all things.
Stevens confessed, that this was a full scripture: but`' neighbors,`' said he,
'`this is the business; G. Fox is come to the light of the sun,
and now he thinks to put out my star-light.`'
To this G. Fox returned, that he would not quench the least measure of God in any,
much less put out his star-light, if it were true star-light,
light from the morning star: but that if he had any thing from Christ, or God,
he ought to speak it freely, and not take tithes from the people for preaching;
seeing Christ commanded his ministers to give freely, as they had received freely.
But Stevens said, he would not yield to that.

This dispute being broke off for that time,
was taken up again a week after by eight priests, in the presence of many people:
and when they saw that G. Fox remained unshaken, they fawningly said,
'`What might he have been if it had not been for the Quakers!`' Afterwards
the dispute was resumed in the steeple-house yard,
where G. Fox showed, by abundance of Scriptures,
that they who preach for wages were false prophets and hirelings;
and that such who would not preach without wages or tithes,
did not serve the Lord Jesus Christ, but their own bellies.
This he treated on so largely, that a professor said,`'George,
what! wilt thou never have done?`'
To this his answer was, that he should have done shortly.
And when he broke off, one of the priests said,
they would read the Scriptures he had quoted.
'`With all my heart;`' said he: then they began to read Jer.
xxiii.
and when they had read a verse or two, George said, '`Take notice, people.`'
But the priests cried, '`Hold thy tongue, George.`'
He then bid them read the whole chapter throughout; but they stopping,
asked him a question: and he told them,
that if the matter he charged them with was first granted,
then he would answer their question:
for his charge had been that they were false prophets, and false teachers,
such as the true prophets, Christ and his apostles, cried against.
'`Nay,`' said a professor to that: but he said, '`Yes; for you, leaving the matter,
and going to another thing, seem to consent to the proof of the former charge.`'
Now their question was, seeing those false prophets were adulterated,
whether he did judge priest Stevens an adulterer.
To this he answered, that he was adulterated from God in his practice,
like those false prophets.

Then they broke up the meeting, and Stevens desired, that G. Fox,
with his father and mother, might go aside with him,
that he might speak to him in private.
George, though his relations yielded to it, was very loth to do so; yet,
that it might not be said he was disobedient to his parents, he went:
but many of the people being willing to hear, drew close to them.
Then Stevens said, if he was out of the way, George should pray for him;
and if George was out of the way, he would pray for him: moreover,
that he would give to George a form of words to pray by.
To this G. Fox replied, '`It seems thou dost not know,
whether thou art in the right way or no; but I know that I am in the everlasting way,
Christ Jesus, which thou art out of: and thou wouldst give me a form of words to pray by,
and yet thou deniest the common prayer book to pray by,
as well as I. If thou wouldst have me pray for thee by a form of words,
is not this to deny the apostles`' doctrine and practice
of praying by the Spirit as it gave words and utterance?`'
Here, though some of the people fell a laughing, yet others, that were grave and sober,
were convinced of the Truth, and the priests were greatly shaken:
insomuch that George`'s father, though he was a hearer and follower of the priest,
was so well satisfied, that, striking his cane upon the ground, he said, '`Truly I see,
he that will but stand to the Truth, it will carry him out.`'

G+++.+++ Fox did not stay long at Drayton, but went to Leicester, and from thence to Whetstone,
where a meeting was to be kept; but before it began, there came about seventeen troopers,
of colonel Hacker`'s regiment, who, taking him up, brought him to the said colonel,
where there was also his major and captains.
Here he entered into a long discourse with them, about the priests, and about meetings;
for at this time there was a noise of a plot against Cromwell:
and he spoke also much concerning the light of Christ,
which enlighteneth every man that Cometh into the world.
The colonel hearing him speak thus,
asked whether it was the light of Christ that made Judas betray his Master,
and afterwards led him to hang himself?
G+++.+++ Fox told him, '`No; that was the spirit of darkness which hated Christ and his light.`'
Then the colonel said to George, he might go home, and keep at home,
and not go abroad to meetings.
But he told him, he was an innocent man, free from plots, and he denied all such works.
Then the colonel`'s son, Needham, said, '`Father, this man hath reigned too long;
it is time to have him cut off.`'
G+++.+++ Fox asked him for what?
'`What have I done, or whom have I wronged from a child; and who can accuse me of any evil?
Then the colonel asked him, if he would go home, and stay there.
To which G. Fox answered, that if he should promise him so,
it would imply that he was guilty of something, to go home,
and make his home a prison to himself; and if he went to meetings, they would say,
he broke their order; but that he should go to meetings, as the Lord should order him;
and that therefore he could not submit to their requirings: and having further added,
that he and his friends were a peaceable people: the colonel said, '`Well then,
I will send you tomorrow morning by six o`'clock, to my lord Protector, by captain Drury,
one of his life-guard.`'
The next morning, about the appointed time, he was delivered to captain Drury.
Then G. Fox desired he would let him speak with the colonel, before he went;
and so the captain brought him to the colonel`'s bedside,
who again bade him go home and keep no more meetings.
But G. Fox told him he could not submit to that; but must have his liberty to serve God,
and go to meetings.
'`Then,`' said the colonel, '`you must go before the Protector.`'
Whereupon G. Fox kneeled on his bedside, and prayed the Lord to forgive him: since,
according to his judgment, he was as Pilate, though he would wash his hands;
(for he was stirred up and set on by the priests,) and therefore George bade him,
when the day of his misery and trial should come upon him,
then to remember what he had said to him.
Far was it now from Needham, who would have had G. Fox cut off,
to think that one time this would befall his father, in an ignominious manner, at Tyburn.
But what afterwards happened,
when he was condemned as one of the judges of King Charles the First,
will be related in its due place.

G+++.+++ Fox then having left colonel Hacker, was carried prisoner by captain Drury to London;
where the captain went to give the Protector an account of him; and coming again,
he told G. Fox, the Protector did require, that he should promise,
not to take up a carnal sword or weapon against him, or the government as it then was:
and that he should write this in what words he saw good, and set his hand to it.
G+++.+++ Fox considering this, next morning writ a paper to the Protector,
by the name of Oliver Cromwell, wherein he did in the presence of God declare,
that he denied the wearing or drawing of a carnal sword, or any outward weapon,
against him, or any man:
and that he was sent of God to stand a witness against all violence,
and against the works of darkness; and to turn people from darkness to the light,
and to bring them from the occasion of war and fighting, to the peaceable gospel;
and from being evil-doers, which the magistrates sword should be a terror to.
Having writ this, he set his name to it, and gave it to captain Drury,
who delivered it to Oliver Cromwell; and after some time returning to the Mermaid,
near Charing-cross, where G. Fox was lodged, he carried him to Whitehall,
and brought him before the Protector who was not yet dressed,
it being pretty early in the morning.
G+++.+++ F. coming in, said,
'`Peace be in this house,`' and bid the Protector keep in the fear of God,
that he might receive wisdom from him; that by it he might be ordered,
and with it might order all things under his hands to God`'s glory.
He had also much discourse with him concerning religion,
wherein Cromwell carried himself very moderately,
but said that G. Fox and his friends quarreled with the ministers, meaning his teachers.
G+++.+++ Fox told him, he did not quarrel with them;
but they quarreled with him and his friends.
'`But, (thus continued he,) if we own the prophets, Christ, and the apostles,
we cannot uphold such teachers, prophets, and shepherds, as the prophets, Christ,
and the apostles declared against;
but we must declare against them by the same power and spirit.`'
Moreover, he showed that the prophets, Christ, and the apostles preached freely,
and declared against them that did not declare freely, but preached for filthy lucre,
and divined for money, or preached for hire, being covetous and greedy,
like the dumb dogs, that could never have enough: and that they that had the same spirit,
which Christ, the prophets, and the apostles had,
could not but declare against all such now, as they did then.
He also said, that all Christendom, (so called,) had the Scriptures,
but they wanted the power and spirit, which they had who gave them forth;
and that was the reason they were not in fellowship with the Son, nor with the Father,
nor with the Scriptures, nor one with another.
Whilst he was thus speaking, Cromwell several times said, it was very good,
and it was truth.
G+++.+++ Fox had many more words with him; but seeing people coming in, he drew a little back:
and as he was turning, Cromwell caught him by the hand, and with tears in his eyes, said,
'`Come again to my house; for if thou and I were but an hour of a day together,
we should be nearer one to another: adding,
that he wished him no more ill than he did to his own soul.
To this G. Fox returned, that if he did, he wronged his own soul;
and bid him hearken to God`'s voice, that he might stand in his counsel, and obey it;
and if he did so, that would keep him from hardness of heart;
but if he did not hear God`'s voice, his heart would be hardened.
This so reached the Protector, that he said it was true.

Then G. Fox went out; and captain Drury following, told him,
that the lord Protector said he was at liberty, and might go whither he would:
yet he was brought into a great hall, where the protector`'s gentlemen were to dine;
and he asked what they did bring him thither for?
They told him it was by the Protector`'s order, that he might dine with them.
But George bid them tell the Protector he would not eat a bit of his bread,
nor drink a sup of his drink.
When Cromwell heard this, he said, '`Now I see there is a people risen, and come up,
that I cannot win either with gifts, honors, offices, or places;
but all other sects and people I can.`'
But it was told him again, that the Quakers had forsook their own,
and were not like to look for such things from him.

It was very remarkable that captain Drury, who, while G. Fox was under his custody,
would often scoff at him, because of the nickname of Quakers,
which the Independents had first given to the professors of the light,
afterwards came to him, and told him,
that as he was lying on his bed to rest himself in the day time,
a sudden trembling seized on him, that his joints knocked together,
and his body shook so, that he could not rise from his bed; he was so shaken,
that he had not strength enough left to rise.
But he felt the power of the Lord was upon him, and he tumbled off his bed,
and cried to the Lord, and said, he would never speak against the Quakers more,
viz. such as trembled at the word of God.

The particular occurrences that befell G. Fox, when he was at liberty in London,
I pass by.
He had great meetings there, and the throngs of people were such,
that he could hardly get to and from the meetings, because of the crowd.
In the meanwhile the number of his friends increased exceedingly,
and some belonging to Cromwell`'s court were also convinced of the Truth preached by him.
He wrote about that time several papers, one of which was against pride, gaudy apparel,
and the world`'s fashions.

I do not find that about this time there was at London any persecution from the magistrates,
but in other places there was:
and it was in this year that Anne the wife of John Audland,
coming into a steeple-house at Banbury, said, after the priest had ended,
that those that were without the doctrine of Christ, though they said the Lord liveth,
yet spoke falsely,
according to Jer. 5:2. For this she was imprisoned as guilty of blasphemy,
and two boys swore against her, that she had said that the Lord did not live.
Thus false accusations prevailed, and at this rate persecution was cloaked.

The year drew now to an end, and Cromwell concluded a peace with the United Netherlands;
to get things the more clear at home, it seems he endeavored to remove troubles abroad.
And there being a rumor spread of a plot as hath been hinted already,
to be the more assured of the parliament,
he caused a guard to be set upon the door of the house,
to keep out those members that refused to sign a paper,
whereby they promised to be faithful to the lord Protector,
and to make no alteration in the government, so as it was settled, on a single person,
and a parliament.
But several of the members would not sign this paper, saying,
that it was a violation of the privileges of the parliament,
and a depriving them of their liberty; and therefore they were kept out;
but others who subscribed the said paper were admitted.
Yet this assembly not acting to the satisfaction of Cromwell,
he dissolved them after a session of five months.
The young king Charles, who lived in exile, had left France,
and was come to Cologne on the Rhine, where he stayed for some time.

But I return to London, where we left G. Fox.
He was in that city continually at work, discharging his duty everywhere,
both with mouth and pen, suffering no time to be lost.
There being commissioners appointed for the trying of ministers, he writ a paper to them,
wherein he advised them, to see whether they were not such whom the prophets, Christ,
and the apostles disapproved; and who would admire men`'s persons because of advantage, etc.
He stayed at London till the year 1655; and after having cleared himself,
he went to Bedfordshire, and came to the house of John Crook, a justice of peace,
where there was a great meeting, and many were convinced of the Truth he declared,
of which number John Crook also was one;
but for this he was soon turned out from being a justice.

Whilst G. Fox was in Bedfordshire, there was also Alexander Parker,
one of the early ministers among those called Quakers.
But leaving them there, I now intend to speak of Willam Caton, who,
as it hath been said already, was one of the family of judge Fell.
When he was but about fourteen years of age,
his father procured leave for him to dwell in the said family;
and his behavior was so pleasing, that he was allowed the judge`'s son,
as a companion night and day; he ate as he did, and went with him a hunting, shooting,
and fishing, partaking of the same pleasure with him in every, thing,
and living in ease and plenty; so that he had cause of joy,
that Providence had cast his lot into such a noted family; for not only judge Fell,
but also his wife Margaret, and their daughters, were well qualified.
W+++.+++ Caton conversing with such choice company, grew up in piety,
and was very zealous in performing his private devotions,
staying often in the bed-chamber, till the judge`'s son, his bed-fellow, was gone down,
so that he might the more freely pour out his heart before God in prayer.
Having attained to the age of fifteen years, he was very diligent,
when he had been at a lecture, to write down the chief heads thereof;
for such of the family as could make repetitions of sermons, and paraphrase thereupon,
were held in esteem.
But William Caton found that what he reaped thereby,
could not satisfy the hunger and thirst of his immortal soul.

After he and the judge`'s son had for some time learned Latin together in the family,
where there was a priest that instructed them,
they were removed to a school at Hawkshead:
but here he found company which he disliked more than that in the judge`'s family.

It was in the year 1652, about Midsummer, that G. Fox,
(as hath been said in its proper place,) first came to the house of judge Fell at Swarthmore.
His non-conformity to the ordinary salutations, W. Caton not a little wondered at;
but yet it did not hinder him from giving due attention to the doctrine G. Fox preached,
which in substance was, to give heed to the light,
which Christ Jesus had enlightened us withal, and which shining in our hearts,
convinceth us of sin and evil.
This so reached W. Caton,
that in due time he began to be subject to this inward convincement,
by which he came to be much restrained in his carriage,
and could not allow himself so great liberty as he was wont to do;
for though he was no ways extravagant,
yet now he saw that a true Christian must be weaned from all vanity;
and that the common diversions of youth displeased God.
This he clearly perceived,
for the witness of God had awakened and reproved
him of that which was contrary to true gravity,
and sobriety of mind.
He had not yet left the school: but, though he was pretty much advanced in his learning,
the making of Latin verses became a burden to him,
because he could not give his thoughts that liberty for invention as others did;
neither could he well any longer give to the master
of the school the compliment of the hat,
as he was used to do: this I had from his own mouth.
One may easily guess that hereby he was brought into a strait; but Margaret Fell,
seeing that he longed to be freed from the school, caused him to stay at home,
where he was employed by her in writing, and teaching her children.
And when he was about seventeen years of age,
he became more and more strengthened in the spiritual warfare,
and his heart was often filled with joy,
because of the mercy and lovingkindness of the Lord to him.

Thus advancing in godliness,
he was frequently moved to go to the places of public worship, and also to markets,
to warn people to repentance; but then beating and buffeting was his share,
and because of his youth he was despised by many; yet he fainted not:
and esteeming it his duty now to labor in the ministry of the gospel,
he desired to be discharged of his service.
Judge Fell was very unwilling to part with him; but Margaret his wife,
though she could not well give him up before,
yet believing that the Lord required his service, not only freely resigned him,
but also prevailed with her husband to let him go:
for he did not desire his liberty to save other men,
but to enter into the service of the Lord, and to proclaim the everlasting gospel.
About the end of the year 1654, being eighteen years of age,
he took his leave of that family,
which was not done without mutual shedding of tears at parting.

He then went to visit his friends in Lancashire, Yorkshire, Derbyshire, and Warwickshire;
from thence to Norwich, and so to Wellingborough, in Northamptonshire;
where he found an opportunity to declare the Truth of God in the steeple-house.
After that he travelled to Cambridge, visiting his friends there;
and then returned to Norwich, where he visited his friends in prison,
and had great meetings in that city.
Then he went to London,
where he was very kindly received by those of the household of faith;
and on a First-day of the week was at two steeple-houses,
at one of which he had large liberty to speak, being indeed persuasive in speech;
and in the afternoon, at a meeting of dissenters from the public worship,
he had liberty to publish Truth without opposition, or contradiction from any;
and many were added to the faith:
for at that time there were twelve ministering brethren,
most of them come out of the North of England, among whom was John Stubbs,
already mentioned, with whom he travelled into Kent: and coming to Dover,
where they were altogether strangers, not knowing any body in the town,
they took their lodging at an inn.
J+++.+++ Stubbs went on the first day of the week to a meeting of the Baptists,
and W. Caton to the steeple-house, where he had but little liberty;
but in the yard he had more opportunity to clear his conscience to the people.
In the afternoon he went up to the castle, where the Independents performed their worship.
Shortly after, he and J. Stubbs went into the Baptists`' meeting,
unto which much people resorted, and many began to be affected with their testimony,
and adhered to it.
This made such a stir, that they were hauled before the magistrates, who examined them,
and ordered that none should entertain them on a certain penalty;
whereupon they were turned out of their lodging.
But one Luke Howard, a shoemaker, who had already heard W. Caton at London,
and afterwards at Dover, in the steeple-house yard,
though he little regarded him at London, but said to his companion,
'`I know more than he can tell me,
or more than either I or he is able to live up to;`' yet
now he became so affected with W. Caton`'s testimony,
that he invited him and J. Stubbs to his house, where he entertained them;
and not long after they had a meeting there;
and he heard the testimony of his guests with no less satisfaction, than Agrippa of old,
did the speech of the apostle Paul, when he said to him,
'`Almost thou persuadest me to be a Christian:`' For Luke Howard was not
yet come so far that he could resolve to conform himself with the Quakers,
so called: but yet, such was his love to them,
that when the mayor of the town sent four constables to his house,
with an order to deliver them up, that so they might be carried out of the town,
he refused to do so, relying on his right as a freeman of the corporation;
and the doors being shut, kept the constables out of his house,
and told them from the shop window,
that the mayor had no lawful authority to have these men hauled out of his house,
and sent out of town, there being no hue and cry come after them.
They stayed yet some days in his house, and he became so strengthened by their ministry,
that he joined with them in profession,
and also gave up his house to be a meeting-place for their friends.

Then W. Caton and J. Stubbs departed the town, and went to Folk-stone,
and from thence to Hithe,
in both which places they found opportunity to preach the Truth.
After some stay, they went to Romney, and so to Lydd.
Here it was, that Samuel Fisher, both by their ministry, and by that of Ambrose Rigge,
and Thomas Robinson,
(who now were also gone forth in the service of the gospel,) was convinced,
and brought over to their society.

He was trained up to literature, and had studied diligently in the University;
and though but young then, yet was of a pious conversation,
and disliked many ceremonies and customs usual in the schools.
When he had finished his course there, he was ordained a priest of the church;
and a certain great man took him to be his chaplain;
and afterwards he got a living at Lydd, worth about two hundred pounds a year.
But after having been thus employed some time,
he came to see that infant baptism was a human institution,
and to preach for wages unlawful.
To this may be added, that Luke Howard, some time before he knew the Quakers, so called,
not being satisfied concerning the singing of David`'s psalms at the public worship,
so troubled his master that he had been apprentice with, that he got Samuel Fisher,
as a learned minister, to come and discourse with him, and to try to convince him:
and S. Fisher talking with him, L. Howard told him, that God was a Spirit,
and must be worshipped in Spirit and Truth,
of all those that would worship him acceptably.
And also, that it was contrary to Truth, for a proud man to sing,
"`he was not put in mind, he had no scornful eye,
and he did not exercise himself in things that were too high;`" when he lived in pride,
wherein God beheld him afar off`". And further,
that it was very unbecoming such a one to sing, "`Rivers of tears run down mine eyes,
because other men keep not thy laws,`" when he never
knew a true sorrow and repentance for his own sins.
This reason of Howard`'s against the customary singing in their worship,
had so much influence upon S. Fisher,
that from that time he was stopped from any more
giving David`'s conditions to the people to sing;
and becoming in time more and more uneasy to go on
in acting what was burdensome to his conscience,
he resolved to desist from his ministry, and so went to the bishop,
and delivered up the commission that he had received from him to preach:
and casting himself upon God`'s providence, he took a farm, and turned grazier,
by which means he maintained his wife and children
much better to his content than before.

Departing thus from the Episcopalian church, he went over to the Baptists,
and became a zealous teacher among them.
It was about this time, that W. Caton, and J. Stubbs came to Lydd,
whom S. Fisher received into his house, remembering that Scripture exhortation,
"`Be not forgetful to entertain strangers,
for many thereby have entertained angels unawares.`"
W+++.+++ Caton went to the meeting of the Independents,
and Stubbs to that of the Baptists, where Fisher then preached;
and J. Stubbs having got opportunity to speak, declared Truth so plainly,
that S. Fisher being very much affected with it, began to paraphrase upon it,
with excellency of speech.
W+++.+++ Caton and J. Stubbs departing this place, went to another town in this county,
but not long after returning to Lydd, they found S. Fisher in fellowship with themselves;
for it happened that this fellow-teacher, George Hammond,
in his sermon so violently inveighed against those called Quakers,
that S. Fisher could not be satisfied, until he stood up in the said meeting,
and bore a testimony against the revilings of Hammond: saying to him, '`Dear brother,
you are very dear and near to me, but the Truth is nearer and dearer:
it is the everlasting Truth and gospel which they hold forth.`'
And speaking more words to that effect,
he openly defended the doctrine of the reviled Quakers.
This so vexed Hammond, that falling into a greater rage, he said,
'`Our brother Fisher is also bewitched.`'
But Fisher rendered not reviling for reviling, but continued with patience in the faith.
This was he who afterwards writ a book, called Rusticus ad Academicos,
wherein he often encountered the priests with their own weapons;
for he was very dexterous at that, and so well versed in the ancient poets,
that he now and then with their words, gave home blows to his adversaries,
allowing himself sometimes the freedom of the prophet
Elijah against the prophets of Baal.
He writ also a paper in Hebrew to the Jews, in which language he was well skilled.
