== Chapter VIII.

=== 1657--1659

G+++.+++ Fox and the man about to set up a College to make Ministers -- Bedfordshire
Yearly Meeting --Dispute between Jesuits and Quakers--Letters to the Protector
respecting Friends and their Sufferings--The Lady Claypole--G. Fox`'s Address
respecting "`Fasts`" --Many Friends offer to lie in Prison instead of their Brethren
--Dissolution of Parliament foretold- E. Burrough`'s letters to the Protector
and to his Family -- Death of O. Cromwell--R. Cromwell proclaimed Protector--Exposition
of the sufferings of Friends by E. Burrough--Great Persecution--Restoration foreseen--Cromwell`'s
Funeral--R. Cromwell resigns the Protectorate--Barbarities towards Friends in
New England--Cruel Laws--W. Brend and W. Leddra at Boston--Inhuman Treatment
of W. Brend--Quakers compared to Wolves--Cutting off the ears of Quakers.

The year being come to an end, I return again to G. Fox, whom we left at Newcastle.
Whilst he was there, he, with Anthony Pearson, visited some of the aldermen;
and among these one Ledger, who as well as the priests,
had said the Quakers would not come into any great towns,
but lived in the fields like butterflies.
G+++.+++ Fox desired to have a meeting amongst them; but they would not yield to it.
He therefore asked Ledger, whether they had not called his friends butterflies,
and said they would not come into any great towns?
'`But,`' said he, '`now we are come into your town, you will not come to us;
who are the butterflies now?`'
Then Ledger began to plead for the sabbath day; which made G. Fox say,
they kept markets on that which was the sabbath day,
for that was the seventh day of the week;
whereas that day which the professed christians now meet on, and call their sabbath,
was the first day of the week.
No leave for a public meeting being obtained,
G+++.+++ Fox got a little meeting among his friends, and some friendly people at Gateside.

Traveling from thence and passing through Northumberland, and Bishopric,
he came to Durham, where was a man come down from London, to set up a college there,
to make ministers of Christ, as they said.
G+++.+++ Fox entering into discourse with this man, said that to teach men Hebrew, Greek,
and Latin, and the seven arts, was not the way to make them ministers of Christ;
for the languages began at Babel;
and to the Greeks that spake Greek as their mother tongue,
the preaching of the cross of Christ was foolishness;
and to the Jews that spake Hebrew as their mother tongue, Christ was a stumbling block.
And as for the Romans, who spake Latin, they persecuted the Christians; and Pilate,
one of the Roman governors, set Hebrew, Greek, and Latin,
atop of Christ when he crucified him.
Thus the languages, which began at Babel, had been set above Christ the Word.
And John the Divine, who preached the Word, that was in the beginning,
said that the beast and the whore had power over tongues and languages,
and they were as waters, and in the mystery Babylon, for they began at Babel;
and the persecutors of Christ set them over him, when he was crucified by them.
'`Dost thou think,`' said G. Fox to the man,
'`to make ministers of Christ by these natural confused languages,
which sprang from Babel, are admired in Babylon, and set atop of Christ, the life,
by a persecutor?`'
The man, puzzled a little by this, confessed to many things spoken by G. Fox.
Then it was showed him further, that Christ made his ministers himself,
and gave gifts unto them, and bid them pray to the Lord of the harvest,
to send forth laborers: that Peter and John,
though unlearnt and ignorant as to school-learning, preached Christ the Word,
which was in the beginning before Babel was: and that Paul also was made an apostle,
not of man, nor by man, but by Jesus Christ, who is the same now, and so is his gospel,
as it was at that day.
This discourse had such effect upon the man, that he became very loving;
and having considered the matter further, he never set up his intended college.

From Durham G. Fox passed to Nottingham, where he gathered again a scattered people,
that having about eight years before been convinced of the Truth,
had been led aside by one Rice Jones.

From hence he went into Warwickshire,
and passing through Northamptonshire and Leicestershire, he came into Bedfordshire,
and so to John Crook`'s house, where a general yearly meeting was appointed,
which lasted three days:
and many of G. Fox`'s friends from most parts of the nation came to it,
so that the inns in the towns thereabouts were filled.
Here was also William Caton, who after the meeting was ended, went with Thomas Salthouse,
formerly his fellow servant in the house of judge Fell, to Westmoreland, Cumberland,
and Swarthmore in Lancashire.
In the said general meeting,
G+++.+++ Fox made a long speech concerning the several states of man,
but more especially for instruction of the ministers of the word,
exhorting them at large to be circumspect in their station.

After the meeting was over, there came a party of horse with a constable,
to seize upon G. Fox, who then was walking in J. Crook`'s garden: and though somebody,
when they came to the house, had told them G. Fox was there, yet they were so confounded,
that they came not into the garden to look for him, but went away without him.

Parting from thence, he came to London, where he heard that a Jesuit,
who was come over with an ambassador from Spain, had challenged all the Quakers,
to dispute with them at the earl of Newport`'s house.
G+++.+++ Fox then let him know by some of his friends, that they would meet him:
whereupon the Jesuit sent word,
he would meet with twelve of the wisest learned men they had.
A while after he sent word, he would meet with but six; and after that,
he sent word again, he would have but three to come.
Then G. Fox went, with Edward Burrough, and Nicholas Bond, to the aforesaid house,
and bade them to go up, and enter the discourse with the Jesuit,
whilst he would be walking in the yard, and then come up after them.
He had advised them to state this question.
Whether the church of Rome, as it now stood,
was not degenerated from the true church which was in the primitive times,
from the life and doctrine, and from the power and spirit that those believers were in?
They having stated the question accordingly, the Jesuit affirmed,
that the church of Rome now was in the virginity and purity of the primitive church.
By this time G. Fox being come in, the Jesuit was asked,
whether they had the Holy Ghost poured forth upon them, as the apostles had?
And he said, '`No.`' Then said G. Fox,
'`If ye have not the same Holy Ghost poured forth upon you,
and the same power and spirit that the apostles had,
then ye are degenerated from the power and spirit which the primitive church was in.`'
And he asked the Jesuit, what Scripture they had for setting up cloisters for nuns,
abbies and monasteries for men, and for their praying by beads and to images,
and for making crosses, for forbidding of meats and marriages,
and for putting people to death for religion?
'`If,`' said he,`' ye are in the practice of the primitive church,
in its purity and virginity, then let us see by Scripture,
wherever they practised such things?
For it was agreed mutually, that both the Jesuits and the Quakers,
should make good by Scripture what they said.
Then the Jesuit said, there was a written, and an unwritten word.
Which made G. Fox ask, what he called his unwritten word?
And he answered, '`The written word is the Scriptures,
and the unwritten word is that which the apostles spake by word of mouth,
which are all those traditions that we practice.`'
Then G. Fox bid him prove that by Scripture;
and the Jesuit alleged the words of the apostle, 2 Thess. 2:5. "`When I was with you,
I told you these things:`" '`That is,`' said he, '`I told you of nunneries and monasteries,
of putting to death for religion, and of praying by beads and to images,`' etc.
This he affirmed to be the unwritten word of the apostles, which they told then,
and had since been continued by tradition unto these times.
Then G. Fox desired him to read that Scripture again,
that he might see how he had perverted the apostles words,
since that which the apostle said there he had told them before,
was not an unwritten word, but was written down there; namely, that the man of sin,
the son of perdition, should be revealed before the great and terrible day of Christ,
which he was writing of, should come.
And therefore this was not telling them any of those things the church of Rome practiced.
Besides, the apostle in the third chapter of the said epistle told the church,
of some disorderly persons he heard were amongst them, busy bodies,
who did not work at all; concerning whom he had commanded them by his unwritten word,
when he was among them, that if any would not work, neither should he eat;
which now he commanded them again in his written word in this epistle, 2 Thess.
iii.

The Jesuit now finding no other scriptural proof for the tradition of the church of Rome,
let that point fall, and came to the sacrament of the altar,
to prove the reality of which, he began with the paschal lamb, and the showbread,
and so came to the words of Christ,
"`This is my body,`" and to what the apostle writ to the Corinthians,
concluding from thence, that after the priest had consecrated the bread and wine,
it was immortal and divine, and that he who received it, received the whole Christ.
To this G. Fox said, that the same apostle told the Corinthians,
after they had taken bread and wine in remembrance of Christ`'s death,
that they were reprobates if Christ was not in them.
But that if the bread they eat was Christ, he must of necessity have been in them,
after they had eaten it.
Besides, if the bread and wine which the Corinthians ate and drank, was Christ`'s body,
how then (continued he,) hath Christ a body in heaven?
And he also signified to him, that both the disciples at the supper,
and the Corinthians afterwards,
were to eat the bread and drink the wine in remembrance of Christ,
and to show forth his death till he came;
which plainly proved that the bread and wine which they took, was not his body.
For if it had been his real body that they ate, then he had been come,
and was then there present;
and it would have been improper to have done such a thing in remembrance of him,
if he had been then present with them; as he must have been, if that bread and wine,
which they ate and drank, had been his real body.
And as to the words of Christ, "`This is my body,`" G. Fox told him,
'`Christ calls himself a vine and a door, and is called in Scripture a rock:
is Christ therefore an outward rock, door, or vine?`'
'`O,`' said the Jesuit, '`the words are to be interpreted.`'
'`So,`' said G. Fox,`'are those words of Christ,
"`This is my body.`'`" And having thus stopped the Jesuit`'s mouth, he made this proposal:
that, seeing he said the bread and wine was immortal and divine, and the very Christ,
and that whosoever received it, received the whole Christ;
a meeting might be appointed between some such Papists
as the pope and his cardinals should appoint,
and some of those called Quakers: '`And then,`' said he, '`let a bottle of wine,
and a loaf of bread be brought, and divided each into two parts,
and let them consecrate which of those parts they will;
and then let the consecrated and unconsecrated bread and wine be set in a safe place,
with a sure watch upon it; and let trial then be made,
whether the consecrated bread and wine will not lose its goodness,
viz. the bread grow dry and moldy, and the wine turn dead and sour,
as well and as soon as that which was unconsecrated;
for by this means the truth of this matter may be made manifest.
And if the consecrated bread and wine change not, but retain their savour and goodness,
this may be a means to draw many to your church.
But if they change, decay, and lose their goodness,
then ought you to confess and forsake your error, and shed no more blood about it,
as hath been done, especially in queen Mary`'s days.`'
To this the Jesuit made this reply:`' Take a piece of new cloth,
and cut it into two pieces, and make two garments of it,
and put one of them upon king David`'s back, and the other upon a beggar`'s,
and the one garment shall wear away as well as the other.`'
'`Is this,`' said G. Fox, '`thy answer?
'`Yes,`' said the Jesuit.
'`Then,`' said G. Fox, '`by this the company may all be satisfied,
that your consecrated bread and wine is not Christ.
Dost thou now say that the consecrated bread and wine,
which you have told people was immortal and divine,
and the real body and blood of Christ, will wear away, or decay as well as the other?
Then I must tell thee, Christ remains the same to day as yesterday, and never decays;
but is the saints`' heavenly food in all generations, through which they have life.`'
To this the Jesuit replied no more, but let the thing fall;
for he perceived that those which were present saw his error,
and that he could not defend it.

Then G. Fox asked him, why the church of Rome did persecute,
and put people to death for religion?
and he answered, it was not the church did it, but the magistrates.
G+++.+++ Fox asked,
whether those magistrates were not counted and called believers and Christians?
'`Yes,`' said he.
'`Are they not members of the church?`'
asked G. Fox.
'`Yes,`' said the Jesuit.
Then G. Fox left it to the people to judge, whether the church of Rome did not persecute,
and put people to death for religion.
Thus they parted; the Jesuit`'s subtlety being comprehended by the simplicity of G. Fox,
and his friends.

Whilst G. Fox was at London, his friends, both in England and Ireland,
were under great sufferings, which made him write to the protector about it:
and there being much talk of making Cromwell king,
he went to him and warned him against it, because of the dangers that would attend it;
and which if he did not avoid, would bring shame and ruin upon him and his posterity.
Which counsel Cromwell seemed to take well, and thanked him for it:
yet G. Fox wrote also concerning the same thing to him in this manner:

O Protector,

Who hast tasted of the power of God, which many generations before thee have not so much,
since the days of apostacy from the apostles, take heed that thou lose not thy power;
but keep kingship off thy head, which the world would give to thee;
and earthly crowns under thy feet, lest with that thou cover thyself,
and so lose the power of God.
When the children of Israel went from that of God in them,
they would have kings as other nations had, as transgressors had;
and so God gave them one; and what did they do then?
and when they would have taken Christ, and made him a king, he hid himself from them;
he was hid from that which would have made him a king,
he who was the king of the Jews inward.
O Oliver, take heed of undoing thyself, by running into things that will fade,
the things of this world that will change.
Be subject and obedient to the Lord God.

GEORGE FOX.

About this time G. Fox wrote also another letter to Oliver Cromwell,
wherein he signified to him, that if he had been faithful, and thundered down deceit,
he would yet have done many mighty things.
And he also advised him, not to slight sober men, and true hearts;
but to mind the law of God, and his fear and dread; to take heed of flatteries,
and to prize his time now he had it.

The lady Claypole, Cromwell`'s most beloved daughter, being sick,
and much troubled in mind, so that none that came could minister any comfort to her,
G+++.+++ Fox visited her with the following letter:

Friend,

Be still and cool in thy own mind and spirit from thy own thoughts,
and then thou wilt feel the principle of God, to turn thy mind to the Lord God,
from whom life comes; whereby thou mayest receive his strength,
and power to allay all blustering storms and tempests.
That is it which works up into patience, into innocency, into soberness, into stillness,
into stayedness, into quietness, up to God with his power.
Therefore, mind, that is the word of the Lord unto thee,
that the authority of God thou mayest feel,
and thy faith in that to work down that which troubles thee:
for that is it which keeps peace, and brings up the witness in thee,
which hath been transgressed, to feel after God with his power and life,
who is a God of order and peace.
When thou art in the transgression of the life of God in thy own particular,
the mind flies up in the air, and the creature is led into the night,
and nature goes out of its course, and an old garment goes on, and an uppermost clothing;
and thy nature being led out of its course, it comes to be all on a fire,
in the transgression; and that defaces the glory of the first body.
Therefore be still awhile from thy own thoughts, searching, seeking, desires,
and imaginations, and be stayed in the principle of God in thee,
that it may raise thy mind up to God, and stay it upon God,
and thou wilt find strength from him, and find him to be a God at hand,
a present help in the time of trouble, and of need.
And thou being come to the principle of God, which hath been transgressed,
it will keep thee humble; and the humble, God will teach his way, which is peace,
and such he doth exalt.
Now as the principle of God in thee hath been transgressed, come to it,
that it may keep thy mind down low to the Lord God; and deny thyself,
and from thy own will, that is the earthly, thou must be kept;
then thou wilt feel the power of God, which will bring nature into its course,
and give thee to see the glory of the first body.
And there the wisdom of God will be received, (which is Christ,
by which all things were made and created,) to be
thereby preserved and ordered to God`'s glory.
There thou wilt come to receive and feel the Physician of value,
who clothes people in their right mind, whereby they may serve God, and do his will.
For all distractions, unruliness, and confusion, is in the transgression:
which transgression must be brought down, before the principle of God,
which hath been transgressed against, be lifted up;
whereby the mind may be seasoned and stilled,
and a right understanding of the Lord may be received; whereby his blessings enter,
and are felt, over all that is contrary, in the power of the Lord God,
which raiseth up the principle of God, within, and gives a feeling after God,
and in time gives dominion.
Therefore keep in the fear of the Lord God; that is the word of the Lord God unto thee;
for all these things happen to thee for thy good,
and for the good of those concerned for thee, to make you know yourselves,
and your own weakness, and that ye may know the Lord`'s strength and power,
and may trust in him.
Therefore let the time that is past be sufficient to every one,
who in any thing hath been lifted up in transgression, out of the power of the Lord:
for he can bring down and abase the mighty, and lay them in the dust of the earth.
Therefore all keep low in his fear,
that thereby ye may receive the secrets of God and his wisdom,
and may know the shadow of the Almighty, and sit under it in all tempests, storms,
and heats.
For God is a God at hand, and the Most High rules in the children of men.
So then, this is the word of the Lord God unto you all.
What the light doth make manifest and discover, as temptations, distractions, confusions,
do not look at the temptations, confusions, corruptions,
but at the light which discovers them, and makes them manifest.
And with the same light you may feel over them, to receive power to stand against them.
The same light which lets you see sin and transgression,
will let you see the covenant of God, which blots out your sin and transgression,
which gives victory and dominion over it; and brings into covenant with God.
For looking down at sin and corruption, and distraction, ye are swallowed up in it;
but looking at the light which discovers them, ye will see over them:
that will give victory, and ye will find grace and strength;
and there is the first step to peace.
That will bring salvation,
and by it ye may see to the beginning and the glory
that was with the Father before the world began;
and so come to know the seed of God, which is the heir of the promise of God,
and of the world which hath no end, and which bruises the head of the serpent,
who stops people from coming to God.
That ye may feel the power of an endless life, the power of God which is immortal,
which brings the immortal soul up to the immortal God, in whom it doth rejoice.
So in the name and power of the Lord Jesus Christ, God Almighty strengthen thee.

G+++.+++ F.

The paper being read to the aforesaid lady, it stayed her mind somewhat;
but she lived not long after, so that O. Cromwell met with almost continual trouble,
for discontent against him increased more and more.

Now, since the Protestants in the valley of Lucerne, and elsewhere, were much persecuted,
there came forth a declaration from the protector to keep a fast,
and one also for a collection for the relief of distressed Protestant churches.
On this occasion, G. Fox to show what kind of fast it was that God requires and accepts,
wrote the following paper:

To the heads and governors of this nation, who have put forth a declaration,
for the keeping of a day of solemn fasting and humiliation, for the persecution,
as you say, of divers people beyond the seas, professing the reformed religion, which,
ye say, has been transmitted unto them from their ancestors.

A profession of the reformed religion may be transmitted to generations,
and so holden by tradition; and in that, wherein the profession and tradition is holden,
is the day of humiliation kept; which stands in the will of man,
which is not the fast that the Lord requires,
to bow down the head like a bulrush for a day,
and the day following be in the same condition as they were the day before.
To the light of Christ Jesus in your consciences do I speak,
which testifieth for God every day, and witnesseth against all sin and persecution;
which measure of God, if ye be guided by it, doth not limit God to a day,
but leads to the fast which the Lord requires, which is,
"`To loose the bonds of wickedness, to undo the heavy burdens, to break every yoke,
and let the oppressed go free.`" Isa. 58:6-7. This is the fast the Lord requires;
and this stands not in the transmission of times, nor in the traditions of men:
but this stands in that which was before times were, and which leads out of time,
and shall be, when time shall be no more.
And these that teach for doctrine the commandments of men,
are they that ever persecuted the life and power when it came.
And whereas ye mention a decree, or edict,
that was made against the said persecuted Protestants; all such decrees or edicts,
proceed from the ground of the pope`'s religion and supremacy;
and therein stands his tyranny and cruelty, acted in that will, which is in that nature,
which exerciseth lordship, over one another, (as you may read, Mark 10:42.
Luke 22:25) as all the heathen do, and ever did;
and in the heathenish nature is all the tyranny and persecution exercised,
by them that are out of the obedience to the light of Christ Jesus in the conscience,
which is the guider and leader of all who are tender of that of God in the conscience.
But who are not led by this, know not what it is to suffer for conscience sake.

Now, whereas ye take into your consideration the sad persecution, tyranny,
and cruelty exercised upon them, whom ye call your Protestant brethren,
and do contribute and administer to their wants outwardly; this is good in its place,
and we own it, and see it good to administer to the necessities of others,
and to do good to all: and we who are sufferers by a law derived from the pope,
are willing to join, and to contribute with you, to their outward necessities.
"`For the earth is the Lord`'s, and the fulness thereof;`" who is good to all,
and gracious to all, and wiling that all should be saved,
and come to the knowledge of the Truth.
But in the meantime, while ye are doing this, and taking notice of others cruelty,
tyranny, and persecution, turn your eye upon yourselves,
and see what ye are doing at home.
To the light of Christ Jesus in all your consciences I speak, which cannot lie,
nor cannot err nor cannot bear false witness; but doth bear witness for God,
and cries for equity, and justice, and righteousness to be executed.
See what ye are doing, who profess the Scriptures,
which were given forth by the saints in light,
who dwelt in the light and in the life of them.
For them who do now witness the same light, the same life, and the same power,
which gave forth the Scriptures, which ye in words profess, them ye persecute,
them ye haul out of your synagogues and markets, them ye beat, stock, and imprison.
Now let that of God in your consciences, which is just and righteous, and equal,
examine and try, whether ye have any example or precedent to exercise this persecution,
which now many in this nation suffer under, who are a people harmless and innocent,
walking in obedience towards God and man.
And though ye account the way of Truth they walk in, heresy;
yet therein do they exercise themselves to have always
a conscience void of offence towards God and man,
as ye may read the saints of old did, (Acts 24:14-16) not wronging any man,
neither giving any just cause of offence;
only being obedient to the commands of the Lord, or declare,
as they are moved by the Holy Ghost; and standing for the testimony of a good conscience,
speaking the truth in Christ, their consciences bearing them witness that they lie not:
for this do they suffer under you,
who in words profess the same thing for which they suffer.

Now see if any age or generation did ever persecute as ye do:
for ye profess Christ Jesus who reveals the Father,
and persecute them that witness the revelation of the Father by Christ Jesus unto them.
Ye profess Christ Jesus,
who is the light of the world,`" that enlightens every one that
cometh into the world;`" and yet persecute them that bear witness,
and give testimony to this light.
Ye profess that the Word is become flesh, and yet persecute them that witness it so.
Ye profess that whosoever confesseth not that Jesus Christ is come in the flesh,
is an antichrist; and yet persecute them that do confess him come in the flesh,
and call them antichrists and deceivers.
Ye profess that the kingdom of Christ is come;
and yet persecute them that witness it come.
Ye profess Christ Jesus the resurrection and the life;
and yet persecute them that witness him to be so.
If ye say, '`How shall we know that these people who say they witness these things, do so,
or no?
I answer, turn your minds to the light which Christ Jesus has enlightened you withal,
which is one in all; and if ye walk in the light, ye shall have the light of life,
and then ye will know and see what ye have done, who have persecuted the Lord of glory,
(in his people,) in whom is life, and the life is the light of men.
To no other touchstone shall we turn you, but into your own consciences,
and there shall ye find the truth of what we have declared unto you,
and of what we bear testimony to, according to the Holy Scriptures.
And when the books of consciences are opened, and all judged out of them,
then shall ye witness us to be of God, and our testimony to be true,
though now you may stop your ears,
and harden your hearts,`" while it is called today.`"
But then ye shall know what ye have done,
and whom you have transgressed against;
and then you will see that no persecutors in any
age or generation that ever went before you,
did ever transgress against that light and measure of God made manifest,
in such a manner as ye have done.
For though Christ and the Apostles were persecuted in their times, the Jews,
for the most part of them, did not know that he was the Christ, when he came,
notwithstanding that they had the Scriptures, which prophesied of him;
neither did they believe that he was risen again,
when the apostles preached his resurrection.
But ye say, ye believe he is come; and ye say, ye believe his resurrection,
and yet ye persecute those that witness him come in the flesh,
those that are buried with him in baptism, those that are conformable to his death,
and know the power of his resurrection; those ye persecute,
those ye haul before magistrates, and suffer to be beaten in your synagogues;
those ye cause to be whipped and stocked, and shamefully entreated, and into prison cast,
and kept: as many jails in this nation, at this day testify to your faces.

Therefore honestly consider what ye are doing,
while ye are taking notice of others`' cruelties, lest ye overlook your own.
There is some difference in many things between the Popish religion,
and that which ye call the Protestant:
but in this persecution of yours there is no difference; for ye will confess,
that the foundation of your religion is grounded upon the Scriptures;
and yet now ye are persecuting those,
that be in the same life which they were in who spake forth the Scriptures;
yourselves being the meanwhile under a profession of the words they spake:
and this ye shall one day witness.
So ye have a profession and form, and persecute them that are in the possession, life,
and power.
Therefore know assuredly that ye must come to judgment;
for he is made manifest to whom all judgment is committed.
Therefore to the light of Jesus Christ in your consciences,
which searcheth and trieth you, turn your minds, and stand still,
and wait there to receive the righteous law,
which is according to that of God in the conscience, which is now rising,
and is bearing witness against all ungodliness and unrighteousness of men;
and they whom ye persecute, are manifest to God,
and that of God in all consciences shall bear witness for us, that we are of God;
and this ye shall one day witness, whether ye will hear, or forbear.
Our rejoicing is in the testimony of our consciences,
that in simplicity and godly sincerity, (not with fleshly wisdom,
but by the grace of God,) we have had our conversation in the world;
not handling the word of God deceitfully, but, in the manifestation of the Truth,
commending ourselves to every man`'s conscience in the sight of God;
and if our Gospel be hid, it is hid to them that are lost:
and for the witnessing the holding the mystery of faith in a pure conscience,
do we suffer, and are subject for conscience sake.
This is thank-worthy, if a man for conscience sake endure grief and suffering wrongfully.
And in this is our joy and rejoicing, having a good conscience,
that whereas we are evil spoken of, as evil-doers, they may be ashamed,
that falsely accuse our good conversation in Christ;
which is not only the putting away of the filth of the flesh,
but the answer of a good conscience towards God, by the resurrection of Jesus Christ.
And this we witness made manifest,
(eternal praises to the living God,) and bear testimony
to that which spake it in the apostle in life and power:
and therefore do we bear witness, and testify against those,
who being got into a form and profession of it, do persecute the life and power.

Therefore to the eternal light of Christ Jesus, the searcher and trier of all hearts,
turn your minds, and see what ye are doing,
lest ye overturn your foundation and bottom whereon ye pretend to stand,
while ye are professing the Scriptures, and persecuting the life, light, and power,
which they were in, who gave them forth.
For the stone cut out of the mountain without hands,
is now striking at the feet of the image, the profession which is set up,
and stands in the will of man.
Now is that made manifest, unto which all must answer,
and appear before the judgment seat of Christ;
that every one may receive the thing done in his body, according to that he hath done,
whether it be good or bad.
Knowing therefore the terror of the Lord, we persuade men;
but we are made manifest unto God, and shall be made manifest in all your consciences,
which ye shall witness.

G+++.+++ F.

Divers times when a fast was proclaimed, G. Fox wrote on that subject;
and since commonly some mischief was then contrived against the Quakers,
no wonder that he would say, that these fasts were like unto Jezebel`'s.

Many of his friends being at this time in prisons and dungeons,
several others of them went to the parliament,
and offered to lie in the same prisons where their brethren lay;
that so those that were in prison, might not perish in stinking dungeons,
and their persecutors thereby bring innocent blood upon their own heads.
But this could not be obtained;
for some of the parliament would threaten these compassionate
men that thus attended them,
with whipping, if they did not desist.
And because the parliament then sitting, consisted mostly of such who,
pretending to be more religious than others,
were indeed great persecutors of those that were truly religious,
G+++.+++ Fox could not let this hypocrisy go unreproved, but wrote the following lines to them:

O friends, do not cloak and cover yourselves; there is a God that knoweth your hearts,
and that will uncover you.
He sees your way: '`Woe be to him that covereth, but not with my Spirit,`' saith the Lord.
Do ye contrary to the law, and then put it from you?
Mercy and true judgment ye neglect.
Look, what was spoken against such: my Savior spake against such: "`I was sick,
and ye visited me not; I was hungry, and ye fed me not; I was a stranger,
and ye took me not in; I was in prison, and ye visited me not,`" But they said,
"`When saw we thee in prison,
and did not come to thee?`" "`Inasmuch as ye did it not unto one of these little ones,
ye did it not unto me.`" Friends, ye prison them that be in the life and power of Truth,
and yet profess to be the ministers of Christ: but if Christ had sent you,
ye would bring out of prison, and out of bondage, and receive strangers.
Ye have lived in pleasure on the earth, and been wanton;
ye have nourished your hearts as in a day of slaughter:
ye have condemned and killed the just, and he doth not resist you.

G+++.+++ F.

It was not G. Fox alone who was grieved with the said hypocrisy,
but others of his friends also declared zealously against it.
A certain woman came once into the parliament with a pitcher in her hand,
which she breaking before them, told them, so should they be broken to pieces;
which came to pass not long after.
And because,
when the great sufferings of G. Fox`'s friends were laid before Oliver Cromwell,
he would not believe it, this gave occasion to Thomas Aldam and Anthony Pearson,
to go through all, or most of the jails in England,
and get copies of their friends commitment under the jailers`' hands,
to lay the weight of the said sufferings upon O. Cromwell, which was done; but he,
unwilling to give order for their release, Thomas Aldam took his cap from off his head,
and tearing it to pieces, said to him,
'`So shall thy government be rent from thee and thy house.`'

About the beginning of this year, E. Burrough wrote a letter to O. Cromwell,
and his council, complaining of, and warning them against persecution,
as being what would draw down God`'s anger against them.

Several copies of the said letter were delivered to Oliver, and his council:
and some months after E. Burrough wrote the following letter to him.

To the Protector.

Friend,

The salutation of my life wishes well unto thee in the Lord,
and most especially that thy precious soul may be redeemed out of death to God, and live,
that thou mayest have a rest and habitation in him when this world is no more.

Now whereas it is a general outcry among the teachers and people of this nation,
and also is doubted, and hath been sometimes objected by thyself,
that the people called Quakers, are deluded and deceived, and in error, and such like:
and now, if it be possible, that thyself and others may be resolved concerning us;
put therefore all thy objections and doubtings into plain positions,
or let the wisest of thy teachers do it for thee; that whatsoever thyself,
or any for thee; can object against us, or what thou doubtest of, or stumbles at,
either in respect of our doctrines or practice, let the matter be stated in plain words,
in positions, or queries; and if God permit, a sufficient answer thou mayest receive,
to remove all conscientious scruples,
and to confound all subtle allegements and evasions;
whereby hereafter forever thou mayest be altogether inexcusable of all doubting,
or speaking against us, or suffering evil to be done,
or spoken against us upon that account.
And this I am moved to give forth and send to thee, that thou mayest be satisfied;
and all things tried and made manifest in the sight of all men;
and that all rash judgment, and false supposition, which lodges in the hearts of many,
may be confounded and brought to nought; and let it be left off, to cry out deceivers,
and heresy, etc. and causing any to suffer on suspicion thereupon;
but bring all things to light, and true judgment;
that what is proved to be the Truth may be owned and not persecuted any more;
for we are willing to be made manifest to all men;
and if any thing be objected against us, which may not be sufficiently answered,
and resolved to sober men, then our enemies are more free,
and have whereof to glory in against us;
but if all occasion of stumbling be removed by answers, according to the Scriptures,
and our principles, practices, and doctrines thereby vindicated,
then let all the teachers, and all our adversaries, shut their mouths from biting at us,
and railing against us, and accusing of us to thee;
and let thy ear be shut from believing lies against the innocent;
and let none suffer in thy dominion under the cruelty of men, upon such a ground.
Hereof I shall be glad to receive an answer, and to join issue in this cause;
and in the meantime, and always, am a lover of thy soul,
but a witness against all oppression.

E+++.+++ B.`'

This was delivered to his hands at Hampton Court, in the Fourth Month, 1658.

I never understood that any thing of moment followed upon this;
but about two months after he wrote another letter to Cromwell,
which was delivered to him at Hampton Court, in the sixth month.

=== To the Protector

Friend,

Know that there is a God that doth whatsoever he will.
All power is in his hand, and he bringeth to pass the counsel of his own heart,
and he rules in the kingdoms of men, and bringeth down and setteth up:
he killeth and makes alive; and he changes times, and seasons, and governments,
and bringeth to nought the counsels of men;
for all power in earth and in heaven is in him, and all his doings are right,
and his ways are equal, and thou and all mankind are as clay in the hand of the potter:
he can honor and exalt as he pleaseth, and he can mar, and break to pieces,
and dishonor whensoever he will; wherefore be humble, and low in heart before him,
for he is the highest power, that subdueth all things under his feet.
If he would, who can heal?
And if he kill, there is none can make alive; and know thou,
it is the Lord God Almighty that doth this,
in whose hands are the issues of life and death; and he it is who can break thee down,
and build thee up; who can wound thee, and restore thee; and bring thee to destruction,
and say unto thee, return; and to know him that doth this, belongs to thy eternal peace,
etc.

Be thou faithful in what the Lord calls thee to, and thou shalt have thy reward;
and seek his honor, and he will honor thee;
and let thy mind be to the Lord in all things, and feel his word and power,
and presence in thee, to quench all that which is contrary,
and then thou wilt be blessed in this life, and in the life to come;
but if thou continues in thy oppression, the Lord will suddenly smite thee.

By a friend unto thee in the Lord,

E+++.+++ B.

That the Lord, according to this prediction did suddenly smite Cromwell, time verified;
for he lived but about a month after the receipt of the said letter.
And that E. Burrough tenderly loved him, appears to me from several circumstances:
and the ardent desire he had for his eternal welfare,
occasioned this plain language to him.

G+++.+++ Fox also wrote to him, that it was not improbable, that because of his wickedness,
the Lord might once raise the royalists against him,
to be instruments of executing his wrath;
as once Cromwell himself had been an instrument to their overthrow.
And a very short time before his death, G. Fox went to Hampton Court,
to speak with him about the sufferings of his friends.
With this intention, he met him riding into Hampton Court park,
and before he came to him,
(according to his relation,) he perceived a waft of death go forth against him;
and coming to him, he looked like a dead man.
So after G. Fox had laid the sufferings of his friends before him, and had warned him,
Oliver bid him come to his house; whereupon G. Fox went to Kingston,
and the next day came to Hampton Court again;
but there he understood that the protector was sick; and Dr. Harvey told,
that the doctors were not willing that he should speak with the protector.
So he passed away, and never saw Oliver Cromwell any more: who,
since the death of his daughter, the lady Claypole, had been distempered,
and troubled with a malignant humour in his foot; which,
when his physicians endeavored to disperse they drove upward,
(as was said,) to his heart: and being seized with a violent fever,
he grew weaker and weaker; yet his preachers endeavored to conceal the danger he was in:
and it is reported that Dr. Goodwin, one of his chaplains,
in a prayer during the time of his sickness, made use of this expression, '`Lord,
we beg not for his recovery, for that thou hast already granted, and assured us of;
but for his speedy recovery.`'
Whilst the protector was sick,
Edward Burrough wrote the following letter to his wife and children, etc.

Friends

Remember, that by the Lord you were raised from a low state,
and when he will he can abase you, and bring you down; he gave you the palace of princes,
and threw out them before you.

O, remember this, every one of you, and come to the witness of God in you, and be humble,
and meek, and lowly, and let the Lord`'s fear be in your hearts;
and be of a tender spirit, having your minds exercised in purity, in holiness,
and in righteousness; and exalt not yourselves,
nor be lifted up in your hearts in the pride and vain glories, and honors of this world,
lest the Lord cast you down, and make your name and posterity a reproach,
as he hath done many before you; and if you walk in the same steps,
and do the same things, and become guilty of the same abominations,
and suffer the children and servants of the Lord to be persecuted,
(as many are at this day, some unto death,) shall the Lord spare you?
Nay, he will cause you to feel his hand of judgment, and bring you down with sorrow,
and he will vex you in his wrath, and smite you with his rod more and more,
till you learn his fear, and depart from all your iniquities;
and the Lord will deface your glory, and pull down your crown; and he will make you know,
that he is Lord, that doth whatsoever he will.

Wherefore humble yourselves under the hand of God, and search your own hearts,
and cast out the abominations that vex the Spirit of the Lord;
and suffer not the people of the Lord`'s precious flock to be devoured,
and made a prey to the wicked; for because of this the rod of affliction cometh upon you,
and may suddenly break you to pieces; but mind the seed of God in you,
which is oppressed, and wait to know the power of the Lord,
which will redeem you out of sin and death, and reconcile you to God,
and bring you into fellowship with himself, to enjoy peace and rest for your souls,
that you may be made heirs of the inheritance of an endless life:
and this would make you truly honorable, and will be more satisfaction to you, and joy,
and content, and true rejoicing, than all worldly crowns, and worldly glories:
which will waste and consume away, and leave you miserable.
And remember that you are now warned from the Lord God,
by whom I am moved to write this unto you, in dear and tender love to you all;
and one day you shall witness it.

And as concerning the Quakers, so called, who are accounted as vile in the sight of men,
and are cast out of all power and place in the nation, being despised of all;
and also are reproached, persecuted, and imprisoned,
and all manner of evil and injustice unrighteously done and spoken against them,
by wicked and corrupt men in authority;
yet are they the children and servants of the living God, and greatly beloved of him,
and are as dear to him as the apple of his eye, and his power and presence is with them;
and the time is at hand that the Lord will make their persecutors fall,
and their enemies bow and tremble, though now they suffer unjustly, and are trodden down,
as not deserving a place on the earth; yet it is for righteousness sake,
and because they show forth the image of the Father, and not for evil doing:
and will not their sufferings lie upon you?
For many hundreds have suffered cruel and great things, and some the loss of life,
though not by, yet in the name of, the protector;
and about a hundred at this present day, lie in holes, and dungeons, and prisons,
up and down the nation; and some at this time are sick, nigh unto death,
whose sufferings cry for vengeance, and the Lord heareth the cry.
Wherefore save yourselves, and let the innocent be delivered,
and the cruel bonds of oppression broken, and the exercise of a pure conscience go free,
without persecution; and then the Lord will turn away his anger,
and cease to smite you with his rod, which hath been upon you:
and he will give you peace, and make you blessed,
if you come to be led by his Spirit into all Truth.

And though these innocent lambs of Christ suffer thus under this present power,
yet are they not enemies to you, but are friends to your persons and families,
and pity you, and love you, and desire well for you in the Lord;
that you may repent and be healed,
and even that your hearts may be opened to receive refreshments to your souls;
and that you may be established in righteousness and truth over all your enemies,
and may not be confounded, nor your posterity brought into reproach,
which is hastening unto you: and though our love be despised,
and we accounted hateful in your sight, and looked upon with derision,
yet we bear all things in patience, truly desiring your returning and repentance,
and not your destruction.
But if these doleful sufferings of the Lord`'s poor
lambs be continued by this present power,
it will destroy you, and undo you, and break you, and confound you;
and the Lord will not cease to smite you with his rod of sharp rebukes;
and he will make you know his people`'s cause shall not be unpunished.
Oh, did you but know how hundreds have and do suffer!
How the bodies of some have been tortured by stocks and cruel whippings!
And how some lie sick in stinking holes and dungeons, on the ground,
or a little straw at best; ten, or often more, in a prison together,
and sometimes their own friends not suffered to come to visit them with necessaries!
Oh, did but your eyes behold, or your hearts perceive,
the greatness of the cruelty which some of the Lord`'s dear servants,
and your faithful friends, undergo, it would make your hearts ache,
and your spirits to tremble!
And all this is done in the name and under the authority of-- Protector;
therefore how should the Lord but lay it to your charge, and afflict him and his family!
He will make you know there is a God that can do whatsoever he will,
and that life and death are in his hands,
and all creatures are as clay in the hand of the potter;
and he rules in the kingdoms of men, and puts down one, and sets up another,
according to his pleasure: but if the love of God be withholden from you,
it is because of disobedience to him, and your transgression.
Wherefore be obedient to him, and love his ways and judgments,
that he may make you more happy with a crown immortal, that never fades away.
And remember once more the Lord hath warned you, by a friend unto you in the Lord.

E+++.+++ BURROUGH.

Written the 1st day of September, 1658.

Oliver Cromwell was snatched away by death at unawares;
however the day before his decease this letter was delivered to his relations.
It was not but in the last period of his life that
he named his son Richard to be his successor.
And when death looked in his face, remorse did not stay behind; for,
according to what Ludlow relates, he seemed above all concerned for the reproaches,
(he said,) men would cast upon his name, in trampling on his ashes when dead.
In this temper of mind he departed this life about two in the afternoon,
on the 3d of September, at the age of about fifty-five years.
The news of his death being brought to those who were met together to pray for him,
one Sterry stood up, and said, '`This is good news;
because if he was of great use to the people of God when he was amongst us,
now he will be much more so, being ascended to heaven, there to intercede for us.`'
O horrid flattery!
Thus I call it, if he had been the greatest saint on earth; which he came much short of,
though he was once endued with some eminent virtues.
His dying day was remarkable by a most grievous tempest, not only in England,
but also in the Low countries,
where trees were torn out of the ground by the violence of the wind,
and many ships foundered.
'`He was,`' saith Edward, Earl of Clarendon,
'`one of those persons whom even his enemies could not vilify without praising him.`'
And I have heard impartial men say, that in the beginning of his achievements,
he was indeed an excellent man; but being come to a high station,
he soon lost that zeal for the public welfare,
by which at first he seemed to be animated.

The body of the deceased was laid in Somerset House,
in an apartment enlightened only with wax tapers, the corpse being richly adorned.

After his death, Richard, eldest son to Oliver,
was proclaimed Protector of the Commonwealth; to whom E. Burrough wrote a letter,
superscribed to Richard Cromwell, chosen to be protector and chief magistrate,
etc. wherein he gave him some account of the most cruel sufferings of his friends;
and speaking of the rulers, he saith thus:

As for magistracy, it was ordained of God to be a dread and terror,
and limit to evil-doers, and to be a defence and praise to all that do well;
to condemn the guilty, and to justify the guiltless;
but the exercise thereof at this day in these nations is degenerated,
and some that are in authority are greatly corrupted,
and regard not the just and pure law of God, to judge only thereby;
but oppress the poor by injustice,
and subvert the good laws of God and men to a wrong end and use, abusing authority,
and turning the sword against the just, whereby Irue judgment is turned backward,
and the innocent made unjustly to suffer for righteousness sake,
through the corruption of men in authority;
and didst thou but know what we know in this particular, it would pierce thy heart.
Why? It is frequent among some of the judges and magistrates, to commit a man to prison,
and impose some great fine upon him, and to cast him into a dungeon, or hole,
among thieves and murderers, for a long season; for no other offence,
or breach of any law, but because he cannot put off his hat to them,
and respect their persons, by the hat or bowing the knee: and many others that fear God,
and for conscience sake cannot swear upon a book, by kissing it,
and laying hands upon it, because Christ saith,
"`Swear not at all;`" though they deny not to speak and do the truth in all things,
as in the presence of God and all men: and many others,
that because they are moved to cry against sin,
and declare against the iniquities of the times, in teachers, rulers, and people,
that highly abound; perhaps in a market or steeple-house, or highway, or other places,
as they are moved of God: and many others,
because for conscience sake they cannot pay tithes,
nor give money and wages to maintain a priest, or false teacher,
that they receive no profit by; or to maintain a steeple-house,
where the world worships in vain traditions, and not in the spirit and power of God:
and many have been taken out of peaceable meetings,
where they were waiting upon the Lord; and some out of their inns and friends`' houses;
and many have been taken on the way, traveling about their lawful occasions;
and some from their callings and labors; and for these causes,
through the envy of wicked men, and without any just conviction of the breach of any law,
or any lawful trial or examination, have hundreds of just men, being wholly innocent,
been sent to prison, and lain many months, and some for years; or whipped,
or put in the stocks,
and grievously abused by cruel executioners of wicked men`'s envy and injustice.
And upon such grounds only, and for such causes mentioned,
and without the transgression of any just law,
have and do at this day many hundreds of faithful subjects suffer hard and cruel things,
long and sore imprisonment, and cruel and sharp whipping, and stocking,
and unjust banishment out of towns and cities; yea, friend, it is hard to be expressed,
and large to be declared, how many of the Lord`'s servants do,
and have suffered great injustice in these nations, through the abuse of good government,
and degeneration of magistracy from its perfect state and place,
whereunto it was ordained of God in the beginning, etc.

This remonstrance, how powerful and large soever, had not its due effect;
but persecution continued, without being stopped by him:
for the churchmen fawned upon him, calling him not only their Joshua,
but the preachers of Suffolk said in their address to him, '`Though our sun is gone down,
yet no night ensued.`'
Sol occubuit, nox nulla secuta est.

About this time was given forth a paper, called.
The Church Faith; and G. Fox having got a copy of it before it was published,
wrote an answer to it; and when the book of The Church Faith appeared,
his answer was also in print.
This so incensed some of the parliament men, that one of them told G. Fox,
they must have him to Smithfield.
To which he answered, that he was over their fires, and feared them not:
and further asked,
whether all the people had been without a faith these sixteen hundred years,
that now the priests must make them one?
And since Christ Jesus was the author of the apostles`'s faith,
and of the church`'s faith in the primitive times, and of the martyrs`' faith;
should not all people look unto him to be the author and finisher of their faith,
and not unto the priests?
Nothing material was answered to this; but the priests called G. Fox`'s friends,
house-creepers, because they met together in houses,
and would not maintain the priests`' temples.
One major Wiggan, that was present when G. Fox discoursed with the parliament men, said,
Christ had taken away the guilt of sin, but had left the power of sin remaining in us.
G+++.+++ Fox told him this was strange doctrine;
for Christ came to destroy the devil and his works, and the power of sin,
and so to cleanse men from sin.

Now there was great persecution, both by imprisonment and breaking up of meetings;
and many died in prisons; for the priests speaking evil of the Quakers,
at did kindle the insolence of the rabble not a little,
so that they did not stick to throw squibs into the meetings,
to cast rotten eggs on those that were met, to beat on drums and kettles,
and so to make hideous noise,
and to abuse people most grievously with blows and violent pushes.

One day there being a meeting appointed near London,
they beat and abused about eighty persons that came out of the city to meet there,
tearing their coats and cloaks from off their backs,
and throwing them into ditches and ponds.
The next First-day of the week after this, G. Fox, though at that time very weak,
went thither, and preaching with the bible in his hand, he showed the rude people, their,
and their teachers`' fruits,
and how disagreeable these mad actions were to the doctrine contained in the Holy Scriptures.
Many of his imprisoned friends were now brought up to London to be tried by the committee;
where sir Henry Vane, being chairman, would not suffer them to come in,
except they would put off their hats.
But since many of them had been imprisoned upon contempts,
(as the not putting off hats before magistrates was called,) others
signified that it must not be expected that now they should comply;
and so through the mediation of some that persuaded Vane, they were at length admitted;
where they so well defended their cause, that several were set at liberty.

Sufferings now growing very sharp, G. Fox, to encourage his friends,
wrote the following lines to them:

My dear friends, everywhere scattered abroad, in prison, or out of prison, fear not,
because of the reports of sufferings;
let not the evil spies of the good land make you afraid,
if they tell you the walls are high, and that there be Anakims in the land;
for at the blowing of the ram`'s horns did the walls of Jericho fall down;
and they that brought the evil report, perished in the wilderness.
But dwell ye in the faith, patience, and hope, having the word of life to keep you,
which is beyond the law; and having the oath of God, his covenant, Christ Jesus,
which divides the waters asunder; and makes them to run all on heaps; in that stand,
and ye shall see all things work together for good, to them that love God;
and in that triumph when sufferings come, whatever they be: your faith, your shield,
your helmet, your armor you have on; ye are ready to skip over a mountain, or a wall,
or a hill, and to walk through the deep waters, though they be heaps upon heaps:
for the evil spies of the good land may preach up hardness, but Caleb,
which signifies a heart, and Joshua, a savior, triumph over all.

G+++.+++ F.

There was at that time great discord among those that were at the helm of government;
and G. Fox relates, that he did then foresee the king`'s coming in again;
and that therefore when some forward spirits, who frequented the meetings of his friends,
would have bought Somerset House to keep meetings in, he dissuaded them from it.
There came also a woman to him, who having,
(as she said,) had a revelation concerning the restoring of king Charles,
three years before he came in, said, she must go to him to declare it:
but G. Fox advised her to keep this revelation to herself,
since if she went on such a message, it would have been counted treason.

How the corpse of Oliver Cromwell was laid in Somerset House to be seen,
hath been said already; but afterwards an image of him lying there in state,
was accompanied with trumpeters, who sounded over the said image.
This vanity so grieved G. Fox, that he wrote the following lines to the authors thereof:

Oh friends, what are ye doing!
And what mean ye to sound before an image!
Will not all sober people think ye are like mad people?
Oh, how am I grieved with your abomination!
Oh, how am I wearied! '`My soul is wearied with you,`' saith the Lord,
'`will I not be avenged of you, think ye, for your abominations?
Oh, how have ye plucked down, and set up!
Oh, how are your hearts made whole, and not rent; and how are ye turned to fooleries!
Which things in times past ye stood over:
therefore how have ye left my dread,`' saith the Lord.
O, therefore, fear, and repent, lest the snare and the pit take you all.
The great day of the Lord is come upon all your abominations,
and the swift hand of the Lord is turned against them all.
The sober people in the nation stand amazed at your doings, and are ashamed,
as if you would bring in popery.

G+++.+++ F.

Sometime after this, the funeral of Oliver Cromwell was solemnized with very great pomp,
not at all agreeable to that condition he was once in;
for the time was when he would have abhorred such
an idolatrous honor as was now paid to his image.
On the day of this pompous funeral, which was the 23rd of November,
it happened that Edward Burrough came riding from Kingston into London,
not knowing any thing of what was done there.
As he entered at Charing-cross,
he beheld a great multitude of people thronging exceedingly,
the streets being filled as far as he could see, and abundance gazing at the windows,
and upon the balconies, and house tops.
There were also guards of horse and foot that stopped his horse, and it was told him,
that he might not pass that way.
Yet he did not know what was the matter;
but at length he perceived that Cromwell`'s image, richly adorned,
was to be carried that way towards Westminster.
The consideration of this, was like an arrow which pierced his breast:
and because of this idolatry, he felt such a fire kindled in him, that he was,
as it were, filled with the indignation of the Lord, whose fury ran through him, to cry.
Plagues, plagues, and vengeance against the authors of this abomination.
Nay, so ardent was his zeal, that if he had been moved to it,
and it had been possible to have done it, he could,
(not at all minding his own life,) have ridden through the guards and multitude,
to have sounded (the judgments of God against the idolaters.
And considering that all this sinful idolatry,
was about the funeral of Oliver Cromwell:`' Alas, for him,`' said Burrough with himself,
'`who was once a great instrument in the hand of the Lord,
to break down many idolatrous images!
Did not the Lord once stir up his heart against all such things?
And did not once his children, officers, soldiers and army,
pull down all the images and crosses, and all such like popish stuff,
wherever they met with it?
What grievous and abominable work is this?
Have they now made a costly image of him?
And are such as were once his soldiers now guarding it, and watching over it,
and his children and officers following it,
and multitude of the inhabitants of London wondering and gazing after an image of him?
This is sad, and great pity: what a change is this in so short a time?`'

This zealous testimony Edward Burrough caused to be printed,
whereby he raised to himself a more lasting monument,
than by the erecting of a statute was made to his quondam friend O. Cromwell.
Now since the persecution of E. Burrough`'s friends,
notwithstanding that he had written to Richard Cromwell, did not cease,
and that all exhortations and warnings were rejected, E. Burrough in the month December,
wrote the following lines to Richard and his council:

To the Protector and his Council.

The Lord God will shortly make you know that we are his people;
though we be accounted as sheep for the slaughter,
yet our king of righteousness will break you to pieces, if you harden your hearts,
and repent not.
And though that love will not draw thee,
neither the gentle leadings of our God have any place in you,
yet judgments shall awaken you,
and his heavy hand of indignation shall lie upon your consciences,
and you will be scattered and distracted to pieces.

E+++.+++ BURROUGH.

How soon this prediction was fulfilled, we shall see in the next year;
for it was but a few months after the delivering of this letter,
when Richard laid down the government.

In the meanwhile we will take again a view of the persecution in New England.
There was, as hath been said already,
a fine settled of five shillings a week to be paid for not coming to church,
as it was called.
And thus from time to time occasion was found to use cruelty against the inhabitants,
though none of those called Quakers came from abroad.
William Shattock, a shoemaker at Boston, being on a First-day of the week,
found in his house, instead of coming to the public worship,
was hauled to the house of correction; where, at his first entrance,
he was cruelly whipped, and then kept to work,
whilst his wife and innocent children were in want because of his absence.
In the meantime the deputy-governor, Richard Bellingham,
did not stick to say to William`'s wife, that since he was poor,
and could not pay five shillings a week for not coming to church,
they would continue him in prison.
Thus was verified that saying of Solomon,
"`cruel are the mercies of the wicked.`" Bellingham also endeavored to persuade this woman,
that what her husband had done, was to be rid of her,
and therefore advised her to disown him.
Now these persecutors began to have abundance of business; and taking away of goods,
and cruel whippings became almost daily work,
which was performed without regard of age or sex;
all which to relate would exceed my limits.

Two women, named Sarah Gibbons, and Dorothy Waugh, being come to Boston,
and having in the public meeting-place, after the lecture was ended, spoken a few words,
were brought to the house of correction, and three days before their being whipped,
and three days after, were kept from victuals, though they had offered to pay for them.
And when Sarah afterward asked the governor, John Endicot,
whether this was justice or equity: adding,
that by this all might see that God was with them,
that they were thus preserved without food; and if they perished,
their blood would fall heavy on those that were the occasion thereof; he answered,
that he mattered it not.

Not long after, Hored Gardner, an inhabitant of Newport, in Rhode Island,
came with her sucking babe, and a girl to carry it, to Weymouth: from whence,
for being a Quaker, she was hurried to Boston,
where both she and the girl were whipped with a three-fold knotted whip.
After whipping, the woman kneeled down, and prayed the Lord to forgive those persecutors:
which so reached a woman that stood by, that she said,
surely she could not have done this, if it had not been by the Spirit of the Lord.

But when should I have done,
if I would describe all the whippings inflicted on the Quakers, so called,
in those parts!
For now a law was made, which furnished continual work to the persecutors there.
The contents thereof were,
that whosoever of the inhabitants should directly or indirectly
cause any of the Quakers to come into that jurisdiction,
he should forfeit a hundred pounds to the country, and be committed to prison,
there to remain till the penalty should be satisfied.
And whosoever should entertain them, knowing them to be so,
should forfeit forty shillings to the country for every hour`'s entertaining or concealment;
and be committed to prison till the forfeiture should be fully paid and satisfied.
And further, that all and every of those people that should arise among them there,
should be dealt withal,
and suffer the like punishment as the laws provided for those that came in,
viz. That for the first offense, if a male, one of his ears should be cut off,
and be kept at work in the house of correction,
till he should be sent away on his own charge.
For the second, the other ear, and be kept in the house of correction as aforesaid.
If a woman, then to be severely whipped, and kept as aforesaid, as the male,
for the first; and for the second offense to be dealt withal as the first.
And for the third, he or she should have their tongues bored through with a hot iron,
and be kept in the house of correction, close at work,
till they be sent away on their own charge.

In the latter part of the Fifth month, it came to pass,
that William Brend and William Leddra, having been at Salem, came to Newbury; where,
at the house of one Robert Adams, they had a conference with the priest,
in the presence of captain Gerish, who had promised that they should not suffer;
but after the conference was ended, the captain would not let them go,
but on promise presently to depart the town; which, being loth to comply with,
as they were on their way, they were sent for back, and captain Gerish riding after them,
commanded them to return: which they refusing, he compelled them thereunto,
and sent them with a constable to Salem; where, being brought before the magistrates,
they were asked whether they were Quakers; to which they answered,
that they were such that were in scorn called so.
Next it was objected to them, that they maintained dangerous errors.
They asking what these were, it was told them,
that they not only denied that Christ at Jerusalem had suffered on the cross,
but also that they denied the Holy Scriptures.
They boldly contradicted this,
and said they owned no other Jesus but he that had suffered death at Jerusalem,
and that they also owned the Scriptures.

Now, although nothing could be objected against this,
yet they were carried to the house of correction, as such who,
according to the law made at Boston, might not come into those parts.
Some days after they were carried to Boston,
where in the next month they were brought into the house of correction, to work there.
But they unwilling to submit thereto, the jailer,
who sought his profit from the work of his prisoners, would not give them victuals,
though they offered to pay for them.
But he told them, it was not their money, but their labor he desired.
Thus he kept them five days without food,
and with a three-corded whip gave them twenty blows.
An hour after he told them, they might go out,
if they would pay the marshal that was to lead them out of the country.
They judging it very unreasonable to pay money for being banished, refused this,
but yet said, that if the prison-door was set open, they would go away.

The next day the jailor came to William Brend, a man in years, and put him in irons,
neck and heels so close together, that there was no more room left between each,
than for the lock that fastened them.
Thus he kept them from five in the morning, till after nine at night,
being the space of sixteen hours.
The next morning he brought him to the mill to work, but Brend refusing,
the jailer took a pitched rope about an inch thick,
and gave him twenty blows over his back and arms, with as much force as he could,
so that the rope untwisted; and then, going away, he came again with another rope,
that was thicker and stronger, and told Brend,
that he would cause him to bow to the law of the country, and make him work.
Brend judged this not only unreasonable in the highest degree,
since he had committed no evil, but he was altogether unable to work:
for he wanted strength for want of food; having been kept five days without eating,
and whipped also, and now thus unmercifully beaten with a rope.
But this inhuman jailer relented not, but began to beat anew with his pitched rope,
on this bruised body, and foaming at his mouth like a madman,
with violence laid fourscore and seventeen blows more on him,
as other prisoners that beheld it with compassion, have told; and if his strength,
and his rope had not failed him, he would have laid on more;
he threatened also to give him the next morning as many blows more.
But a higher power, who sets limits even to the raging sea, and hath said,
"`hitherto thou shalt come, but no further,`" also limited this butcherly fellow;
who was yet impudently stout enough to say his morning prayer.
To what a most terrible condition these blows brought the body of Brend,
who because of the great heat of the weather,
had nothing but a serge cassock upon his shirt, may easily be conceived;
his back and arms were bruised and black,
and the blood hanging as in bags under his arms; and so into one was his flesh beaten,
that the sign of a particular blow could not be seen; for all was become as a jelly.
His body being thus cruelly tortured, he lay down upon the boards, so extremely weakened,
that the natural parts decaying, and strength quite failing, his body turned cold:
there seemed as it were a struggle between life and death; his senses were stopped,
and he had for some time neither seeing, feeling, nor hearing,
till at length a divine power prevailing, life broke through death,
and the breath of the Lord was breathed into his nostrils.

Now, the noise of this cruelty spread among the people in the town,
and caused such a cry, that the governor sent his surgeon to the prison,
to see what might be done;
but the surgeon found the body of Brend in such a deplorable condition, that,
as one without hopes, he said, his flesh would rot from off his bones,
ere the bruised parts could be brought to digest.
This so exasperated the people, that the magistrates, to prevent a tumult,
set up a paper on their meeting-house door, and up and down the streets,
as it were to show their dislike of this abominable, and most barbarous cruelty;
and said, the jailer should be dealt withal the next court.
But this paper was soon taken down again upon the instigation of the high-priest,
John Norton, who having from the beginning been a fierce promoter of the persecution,
now did not stick to say,
'`W. Brend endeavored to beat our gospel ordinances black and blue,
if he then be beaten black and blue, it is but just upon him;
and I will appear in his behalf that did so.`'
It is therefore not much to be wondered at, that these precise and bigoted magistrates,
who would be looked upon to be eminent for piety, were so cruel in persecuting,
since their chief teacher thus wickedly encouraged them to it.

In the meanwhile it pleased God, even miraculously to heal William Brend,
and to keep him alive;
but as if the hearts of these persecutors were more hardened thereby,
to show themselves obedient followers of their teacher, they made an order,
that the jailer, if the Quakers that were in his custody refused to work,
should whip them twice a week, the first time with ten lashes,
the next time with fifteen, and so at each time with three more, till they would work.
This was performed on four persons, two of which were William Leddra and John Rous,
who may be mentioned hereafter.
And to keep the passionate jailer within due bounds, forsooth,
it was ordered that each time he should warn two constables to see the execution.
But how little moderation was truly meant, and that this was more like a jest,
may appear in that the jailer the first time laid
fifteen lashes apiece on the said persons,
and so added five stripes to the first number often.

It happened about this time, that some of the people called Quakers that lived there,
being had before the magistrates, it was demanded by one of them,
how they might know a Quaker; to which Simon Broad-street, one of the magistrates,
answered, '`Thou art one, for coming in with thy hat on.`'
Which made the other reply, it was a horrible thing to make such cruel laws,
to whip and cut off ears, and bore through the tongue, for not putting off the hat.
Then one of the bench said, that the Quakers held forth blasphemies at their meetings.
To which one of the others desired him to make such a thing appear, if it were so,
that they might be convinced: and further,
that they should do well to send some to their meetings, that they might hear,
and give account of what was done and spoken there;
and not conclude of a thing they knew not.
'`But,`' said major-general Denison,`' if ye meet together, and say any thing,
we may conclude that ye speak blasphemy.`'
A very strange syllogism indeed.
No better, (to prove persecution lawful,) was the argument of Charles Chauncy,
chief teacher at the university, "`who in a sermon at Boston, argued thus:
suppose you should catch six wolves in a trap,
and ye cannot prove that they killed either sheep or lambs:
and now you have them they will neither bark nor bite:
yet they have the plain marks of wolves, and therefore ye knock them down.`'
A base expression, thus to compare man to a beast; for God said in plain terms to Noah,
"`Whoso sheddeth man`'s blood,
by man shall his blood be shed.`" But these persecutors thought
there was stress enough in it to call the Quakers wolves;
and to make one pass for a Quaker, they counted it a sufficient proof,
when they saw he did not put off his hat to men; '`Knock him down, it is a wolf.`'

And if the hat was not found fault with, something else was though on;
for at Salem twelve persons were fined forty pounds nineteen shillings,
for not coming to church; and of others much money was extorted,
because their wives absented themselves from the public worship.
William Marston, of Hampton, was fined ten pounds for two books found in his house,
viz. John Lilburn`'s resurrection, and W. Dewsbury`'s Mighty Day of the Lord.
Thus these people did whatever they would, without any regard to the laws in Old England:
and when once some prisoners appealed to it, the governor, John Endicot,
and his deputy Bellingham, cried, '`No appeal to England!
No appeal to England.`'
And they seemed to fear nothing for what they did to the Quakers:
according to what major-general Denison said in open court,
'`This year you will go and complain to the parliament,
the next year they will send some to see how things go,
and in the third year the government will be changed.`'
Now they not at all caring for Old England,
denied also the prisoners their request of being
tried according to the laws of that realm,
by a jury.
And the rulers dealing thus arbitrarily,
the jailer of the house of correction did the like;
for when some of his prisoners showed themselves not unwilling to work,
provided that their families should have something of the gain, he would not allow that,
unless they paid him eight-pence for every twelve-pence gain: and when they refused this,
the whipping-post was his refuge.

But to go on: in the foregoing year mention was made of John Copeland,
and Christopher Holder, these coming in the sixth month to Dedham,
lodged there one night; but the next day, were taken up by a constable,
and carried to Boston, where being brought before the governor, he said in a rage,
'`Ye shall be sure to have your ears cut off.`'
Not long after, John Rouse came again to Boston, but was shortly after taken,
and committed to prison.
On the 17th of September, he, with Holder, and Copeland,
were brought before the magistrates in the court, where the deputy-governor told them,
that they, in contempt of the magistrates and ministers,
being come there again to seduce the people, might know that whatever befell them,
whether the loss of their ears, or of their lives,
their blood would be upon their own heads.
They denying this, and saying, that the Lord had sent them hither, the governor, Endicot,
said, '`You are greater enemies to us, than those that come openly;
since under pretense of peace, you come to poison the people.`'
Being asked for proof that the Lord had sent them they replied,
that it was some kind of proof that the Lord had sent them,
because they met with such entertainment as Christ
had told his disciples would be meted to them,
for his name sake, viz. whipping, etc.
To this, major-general Denison said, '`Then when malefactors are whipped,
they suffer for Christ`'s sake.
Then John Rouse, whose father was a lieutenant-colonel in Barbados, said,
'`If we were evil-doers,
the judgments of God would be heavier upon us than those we suffer by you.`'
To which major Denison replied, '`Mr. Rouse, (for so I may call you,
having heard your father is a gentleman,) what judgment
of God do you look for greater than is upon you,
to be driven from your father`'s house, and to run about here as a vagabond,
with a company of deceivers, except you look for a halter?`'
To this Rouse said,`'I was not driven from my father`'s house,
but in obedience to the Lord I left it;
and when the Lord shall have cleared me of this land, I shall return to it again.`'
Then Endicot called to the secretary to read the law,
who thereupon read this clause in it, that if any that had suffered the law,
should presume to return again, they should have one of their ears cut off.
Some more words were spoken, and among the rest, Endicot said,
'`The Quakers have nothing to prove their commission by, but the spirit within them,
and that is the devil.`'
And when one of the prisoners said, '`We have seen some of your laws,
that have many scriptures in the margin;
but what example have you in Scripture for cutting off ears?`'
Endicot asked, '`What Scripture is there for hanging?
'`To which Denison said scoffing, '`Yes, they would be crucified.`'
Then Endicot called the three prisoners by name, and said in great passion,
'`It is the sentence of the court,
that you three have each of you his right ear cut off by the hangman.`'
Then they were carried to the prison, and on the 16th of September,
the Marshal`'s deputy came thither, letting as many come in as he thought meet;
and when the doors were made fast, the said marshal read the following order:

To the marshal-general, or his deputy: you are to take with you the executioner,
and repair to the house of correction,
and there see him cut off the right ears of John Copeland, Christopher Holder,
and John Rouse, Quakers; in execution of the sentence of the court of assistants,
for the breach of the law, entitled Quakers.

EDWARD RAWSON, Secretary.

Then the prisoners were brought into another room, where John Rouse said to the marshal,
'`We have appealed to the chief magistrate of England.`'
To which he answered, he had nothing to do with that.
Holder said, '`Such execution as this should be done publicly, and not in private;
for this was contrary to the law of England.`'
But captain Oliver replied, '`We do it in private to keep you from tattling.`'
Then the executioner took Holder, and when he had turned aside his hair,
and was going to cut off his ear, the marshal turned his back on him,
which made Rouse say, '`Turn about and see it; for so was his order.
The marshal then, though filled with fear, turned, and said, '`Yes, yes,
let us look on it.`'
Rouse, who was more undaunted than his persecutor, suffered the like,
as well as the third, and they said, '`those that do it ignorantly,
we desire from our hearts the Lord to forgive them; but for them that do it maliciously,
let our blood be upon their head; and such shall know in the day of account,
that every drop of our blood shall be as heavy upon them as a millstone.`'
Afterwards these persons were whipped again;
but this practice becoming so common in New England as if it was but play,
I will not detain my reader with it.

Persecution being now come to the cutting off of ears, did not stop there,
but went higher, and rested not, before it came to the taking away of lives.
But to compass that proved very difficult;
for there were many honest people who abhorred such a cruelty.
Yet John Norton, and the other priests, petitioned the magistrates,
to cause the court to make some law to banish the Quakers, upon pain of death.
This gave encouragement to the magistrates,
for since the churchmen pushed on so wicked a business,
no scruple was made to go on with this bloody work;
and the court of magistrates voted it to be put in execution by a country court,
which three magistrates made up, the majority of which might hang at pleasure,
without trial by a jury; a thing not heard of in Old England:
but it served the purpose of Norton, and his fellow preachers.
The court where this law was made, consisted of twenty-five persons;
and when it was put to the vote it was carried in the affirmative,
the speaker and eleven being on the negative, but thirteen on the affirmative,
so that one vote carried it.
This so troubled one Wozel, when he heard it, having through illness been absent,
that he got to the court, and weeping for grief,
that his absence should occasion such a law to pass, said, if he had not been able to go,
he would have crept upon his knees, rather than it should have passed.
But what he said proved in vain; they had now passed the Rubicon,
and what was eagerly desired, was obtained.
Yet there was a great difference in the court,
and the twelve that had voted in the negative,
resolved to enter their dissents to that law; which the others seeing,
and that so many difficulties would weaken their law, they admitted this addition,
to be tried by a special jury; though a standing law of the country contained,
that none be sentenced to death and banishment, but by a special jury,
and a court of assistants; and such a court consisted of seven magistrates at the least.
But it was now resolved, to prosecute the Quakers to death; and all this trial,
when it came to it, was but, whether they were Quakers?
Which they judged by their coming in covered;
and that they had been banished out of the country.
Now to enter upon this bloody business, the following act was made at a general court,
held at Boston, the 20th of October, in this year, 1658.

=== An Act made at a general court, held at Boston, the 10th of October, 1658.

Whereas there is a pernicious sect, (commonly called Quakers,) lately risen,
who by word and writing have published and maintained many dangerous and horrid tenets,
and do take upon them to change and alter the received laudable customs of our nation,
in giving civil respect to equals, or reverence to superiors,
whose actions tend to undermine the civil government,
and also to destroy the order of the churches,
by denying all established forms of worship,
and by withdrawing from orderly church-fellowship,
allowed and approved by all orthodox professors of the Truth, and instead thereof,
and in opposition thereunto, frequently meeting themselves,
insinuating themselves into the minds of the simple,
or such as are least affected to the order and government of church and commonwealth,
whereby divers of our inhabitants have been infected, notwithstanding all former laws,
made upon the experience of their arrogant and bold obtrusions,
to disseminate their principles among us, prohibiting their coming in this jurisdiction,
they have not been deterred from their impetuous attempts to undermine our peace,
and hazard our ruin.

For prevention thereof, this court doth order and enact, that every person, or persons,
of the cursed sect of the Quakers, who is not an inhabitant of,
but is found within this jurisdiction, shall be apprehended without warrant,
where no magistrate is at hand, by any constable, commissioner, or select man,
and conveyed from constable to constable, to the next magistrate,
who shall commit the said person to close prison, there to remain, without bail,
unto the next court of assistants, where they shall have a legal trial:
and being convicted to be of the sect of the Quakers,
shall be sentenced to be banished upon pain of death:
and that every inhabitant of this jurisdiction,
being convicted to be of the aforesaid sect, either by taking up, publishing,
or defending the horrid opinions of the Quakers, or the stirring up mutiny, sedition,
or rebellion against the government,
or by taking up their absurd and destructive practices,
viz. Denying civil respect to equals and superiors,
and withdrawing from our church assemblies,
and instead thereof frequent meetings of their own, in opposition to our church order;
or by adhering to, or approving of any known Quaker,
and the tenets and practices of the Quakers,
that are opposite to the orthodox received opinions of the godly,
and endeavoring to disaflect others to civil government, and church orders,
or condemning the practice and proceedings of this court against the Quakers,
manifesting thereby their complying with those,
whose design is to overthrow the order established in church and state,
every such person, upon conviction before the said court of assistants,
in manner as aforesaid, shall be committed to close prison for one month, and then,
unless they choose voluntarily to depart this jurisdiction,
shall give bond for their good behavior, and appear at the next court,
where continuing obstinate, and refusing to retract and reform the aforesaid opinions,
they shall be sentenced to banishment upon pain of death; and any one magistrate,
upon information given him of any such person, shall cause him to be apprehended,
and shall commit any such person to prison, according to his discretion,
until he come to trial, as aforesaid.

Here ends this sanguinary act, being more like to the decrees of the Spanish Inquisition,
than to the laws of a reformed Christian magistracy, consisting of such who,
to shun persecution themselves,
(which was but a small fine for not frequenting the public worship,) had left Old England.
This act was answered by Francis Howgill, and the said answer published in print,
wherein was plainly shown,
that it spoke the language of the ancient persecuting Jews and heathen.
In the sequel we shall see the bloody execution of it upon some persons
