== Chapter IX

[.section-date]
1659--1660.

[.chapter-synopsis]
* W+++.+++ Caton in Holland
* W. Ames in Germany
* W. Ames confined in Bedlam
* Sufferings of Friends laid before Parliament
* One hundred and sixty Friends offer to lie in jail in place of their brethren
* Remarkable Prophecy of E. Burrough
* E. Burrough and S. Fisher at Dunkirk
* Controversy with Friars
* R. Cromwell retires to private life
* Intrigues of the Military Officers to retain Power
* Message of E. Burrough to the Rulers of England
* Letter to the Cavaliers
* Continuation of Persecution in New England
* Instances of dreadful Cruelty
* Sufferings of R. Hodshone
* Banishment on pain of Death
* Trial and Execution of W. Robinson and M. Stevenson
* Mary Dyer

In the forepart of the year 1659, there was great discord,
and several factions among the people in England;
for some adhered to the protector Richard,
and others to the chief members of the long parliament;
and the royalists made also a party.
G+++.+++ Fox being under a concern lest some young or raw people,
who sometimes came amongst his friends,
might be drawn into some of those several interests, wrote an epistle,
warning such to be careful, and not at all to meddle with any plotting;
but to consider that their warfare was a spiritual one,
and not at all wanting the use of carnal weapons.

About this time William Caton came again into Holland,
and finding at Amsterdam some malicious people who endeavoured
to bring his fellow-believers there into trouble,
and to stir up the mob against them,
that so the magistrates might take occasion to look upon the Quakers as rioters,
advised those of that persuasion to be circumspect,
and to avoid as much as possibly they could the impending storm.
In order thereto it was thought meet that their religious meetings,
which on the weekdays were kept pretty late at night,
on the first days of the week should not always be kept in one place,
but sometimes in this, and at other times in another house.
Sometimes a meeting was kept in an alley, at the town wall near the Regulars gate,
where several English people dwelt, from whence it was called the English Alley,
and has that name still: hither came very rude company, committing great insolence.
The time before that W. Caton was in Holland,
he met with an extraordinary rude encounter at the said place,
insomuch that he seemed in danger of his life; for some wicked people,
not daring to do their utmost in the house where he was, pushed him out of doors;
but then a woman pulled him into her house, where he was safe,
though at first he knew not whether he was among friends or foes.
I yet well remember this fact,
being at that time with my parents in the said disturbed meeting.
Now Caton being a discreet and judicious person,
and perceiving that some of his friends there had more of a rash zeal than true wisdom,
advised the most moderate of them often to change meeting-places.
In the beginning a meeting was kept now and then in St. John`'s street, so called;
and afterwards on Eland`'s Graff, in an alley, at the house of one Richard Langham;
and also on the Angelier`'s Graff, in the house of my father;
and some time after in the English alley abovesaid; and also without the town,
near the river Amstel, in Kuypers Padt, or Cooper`'s Lane;
from whence the meeting was removed in the forepart of this year,
(if my memory doth not deceive me,) into the Verwers Padt, or Dyer`'s Lane;
which was then without the city freedom,
and the meeting-place was in a large garret of a tanner`'s house,
where oftentimes came abundance of people, and among these not a few of the rude rabble.
Here the meeting was continued till the year 1663,
when that place came into the possession of another owner.

W+++.+++ Caton, after some stay in Holland, returned again to England.
I think it was in this year that William Ames went into Germany,
where being come into the Palatinate, he went to Heidelburgh,
and came to the court of the prince Elector, Charles Lodowick, who treated him kindly,
even at his own table, and seemed not to take offence at Ames`'s hat, which he kept on,
though the lords and others that were in the company, stood bareheaded.
The baron of Helmont, who also was at that court, was wont to tell afterwards,
that Ames walking once with his hat on, next to the prince in his garden,
the courtiers asked the prince, whether they should question Ames for this incivility;
but the prince said, "`No, for I did expect that.`"
At another time the prince made his chaplain and Ames both dine with him, on purpose,
as it seems, that Ames, whom he knew to be a bold man,
might find occasion to reprove his chaplain; for at meat he suffered his jester to come,
who playing his tricks, the chaplain was silent; but Ames, who loved gravity,
and was averse to jesting, took occasion from thence to reprove such vain actions;
but chiefly he aimed at the chaplain, whom,
because of his silence at the lewd behaviour of the jester, he called a dumb dog;
which seemed to please the prince.

Now whilst William Ames was in the Palatinate,
he got acquaintance with the Baptists at Krieshiem, a town not far from Worms;
and among those people he found such entrance,
that some families receiving the doctrine he preached,
bore a public testimony for it there,
and so continued till the settlement of Pennsylvania in America,
when they unanimously went thither,
not as it seemed without a singular direction of Providence; for not long after,
a war ensued in Germany, where the Palatinate was altogether laid waste by the French,
and thousands of people were bereft of their possessions, and reduced to poverty.

But to return to Ames, when some in the Palatinate began to give an ear to his preaching,
a fine was settled upon those that gave him entertainment: but the prince Elector,
being informed hereof, took off that fine;
and though those of the consistory did send for Ames,
the prince generously ordered them not to meddle with him.
The prince`'s sister also behaved herself very kindly towards him,
and received his exhortations favourably.

A year after Ames came again into the Palatinate, with John Higgins,
and visiting the prince Elector, he understood from the captain of the prince`'s guard,
that the prince was glad of Ames`'s return thither.
Awhile after Higgins delivered to the prince Elector a book of G. Fox,
with a letter of Ames to the said prince, who was so well pleased with it,
that he bade Higgins to thank Ames on his behalf,
saying also that he took the coming of Ames and Higgins to him and his family very kindly,
and really believed that what they spoke was in love to their souls.

Several years after this, some others of Ames`'s friends from England,
visited the aforesaid prince Elector, and he always,
(to his praise be it said,) received them kindly.
W+++.+++ Ames, who was at sundry times in Germany, came not only to Hamburgh,
but travelled also through Bohemia to Dantzick, and from thence to Poland.
At Hamburgh and Dantzick he met with some that received the Truth he preached;
but in Poland people were too rude and haughty, to get entrance among them.

In the forepart of this year, W. Ames being at Rotterdam in Holland,
was confined there in Bedlam; which having made a great a noise,
I will give a brief relation of it here.
At Moordrecht, a village near Gouda, lived at that time one Martin Martinson,
a cooper by trade;
this man approving the doctrine preached by Ames at Rotterdam and elsewhere,
began to assert it as truth:
and seeing now and then he with some of his sober neighbours kept a meeting at his house,
this caused a great stir in the town,
insomuch that sometimes he suffered rude treatment from the people.
Ames coming once there, and keeping a meeting in Martin`'s house,
great insolence was committed by the wicked rabble.
And going from thence to pass over the water to Gouwerek,
he was followed by a multitude of riotous people, both young and old,
with a hideous cry of "`Quake, Quake, Quake!`"
And was pelted with stones and clods, till he came to the boat that carried him over.
The preacher of Gouwerek hearing the noise, came to the boat,
and asked what the matter was, why people made such a sad noise?
To which Ames answered, "`It seems the people are not taught better.`"
To which the preacher returned,
"`They are not used to make such ado against honest people;
but I believe you to be a deceiving wolf, that comes among the sheep to seduce them,
and therefore they cry so.`"
"`Prove this,`" replied Ames.
"`I do not know you,`" said the preacher.
"`Learn then,`" returned Ames, "`better manners, than to call one thou knowest not,
a wolf and deceiver.`"
And so going his way, shortly after he wrote from Rotterdam to Martin,
and bade him go to the preacher,
and desire him to appoint a time to prove that Ames was a deceiving wolf.
But to this the preacher showed himself backward; yet to be rid of Martin,
he said at length, "`Come, I will prove it presently.`"
But Martin replied, "`I am not come for that;
but this must be done to Ames;`" and insisting thereon, "`Well,`" said the preacher,
"`let him come next Sunday before noon, after sermon;
then I will prove it publicly before all the people.`"

Of this Martin sent word to Ames; but things were managed so,
that this project of proof was quashed:
for the preacher of Gouwerek went to his colleague at Moordrecht,
and consulted with him what to do in the case;
and Ames being come to Moordrecht on the first day of the month called March,
and the last of the week, though it was late at night, was seen and known by some;
who committed much violence upon the house of Martin, where Ames was entered.
The next day it was reported that some of the sheriff`'s men of
Gouda were come to Gouwerek to apprehend Ames when he came there;
and at Moordrecht the dikegrave`'s men came for the same purpose;
and so they took Ames prisoner, and carried him to Rotterdam,
where he was locked up in Bedlam, as a madman.
And a week after, Martin, for having kept meetings at his house,
where not above eight persons were come together,
was also by the dikegrave`'s men taken prisoner in his house, and carried to Rotterdam,
where he was locked up with Ames.
Who were the instigators of this business is plain enough, though I do not mention them.

After Ames had not been much above three weeks in Bedlam,
the deputy-governor of the house, on the 27th of the month, about night,
came to him and Martin, and said, "`If I was in your place, I would go out.`"
Which made Ames ask, whether he would suffer them to do so?
To which he answered, that he should not hinder them.
Then Ames returned, "`I will not be reputed as one that broke prison.`"
To which the deputy replied, "`Nay, why should you be reputed so?
You may go out freely; all is unlocked, and the door will stand open for you;
for the governors are not minded that you should stay here.`"
Then Ames said, "`Well, I intend to go out tomorrow.`"
The next day Martin`'s wife came to see her husband; but the deputy told her,
that he had an order in writing from the dikegrave,
that rather than to let Martin`'s wife come to him,
he might let him and Ames go out together.
The issue was, that they were both let out that morning, it being the 28th of the month.
But they stayed at Rotterdam,
intending not to depart the town before they had given notice
to the dikegrave of their being let out;
lest occasion might be given for saying that they had broken prison.
And it was not without reason they were so cautious; for the next day, in the morning,
the deputy came to them, and said, "`I desire that you will not bring me into trouble,
for I am an ancient man; and the dikegrave hath been with me, and asked for you;
to which I answered, that you were gone out; but he took this very ill.
I desire, therefore, that you would say that you were gone out without my knowledge.`"
But this was not to be expected from Ames, whom I knew so well,
that I truly believe that he would rather have died, than to have spoken a lie:
for in such a case he was without question of the same mind as formerly Christian Langedul,
uncle to my grandmother by the mother`'s side, who, when at Antwerp, he, with others,
martyrs, was led to the stake to be burnt, cried out undauntedly,
"`If we would once but have told a lie, we might have escaped this.`"
But to return to Ames, he told the deputy,
that he himself intended to go and speak with the dikegrave;
and if he was displeased at their going out,
he might put them in again where they had been;
for they would not have the name of prison-breakers.

Then they both went to the dikegrave, and told him after what manner they were come out;
saying also that they would not have it said, that they broke out.
"`That name,`" said the dikegrave, "`you would have had, if you had departed the town;
for the deputy hath told me that you got out by breaking a window.`"
After some other words were exchanged, he further said,
"`I have nothing to object against your life and conversation,
having heard nothing concerning you but a good report;
neither do I seek to persecute you.
But would you be willing to return to Bedlam?`"
Ames answered, "`Here we stand before thee;
thou mayest do with us according to thy pleasure.
And if thou desirest us to return thither, we will do so.`"
The dikegrave signifying that this was his desire,
said that they might go and walk in the gallery then, till another order came.
And so he caused his messenger to go along with them.
Being come thither, they not long retained the liberty to walk in the gallery,
but on the 31st of the month, they were locked up again, each in a hole by himself.
Now Ames acquainted the deputy that he heard from the dikegrave,
that he had been informed by him, that they were got out by breaking a window.
But the deputy denied to have said so.
They were detained there yet sometime, and were pretty much visited,
and this often by such as sought nothing but to scoff at them;
and among these a certain clergyman did not stick to say to Ames, that he was a deceiver,
because he wore pewter buttons, to make people believe they were silver ones.
Whilst Ames was confined here, he wrote some papers which afterwards he published,
and among these a reply to an answer of one Jacob Koelman,
to eighty-three queries given forth by the said Ames; who now being set at liberty,
travelled to Germany, as hath been said before,
and from thence going back to his native country,
after some time returned again into Holland, as did also William Caton.

But now I turn again to England,
where an account was published in print of the sufferings of the people called Quakers,
which being offered to the parliament, was delivered to the speaker, Thomas Bampfield.
This contained a relation of above one hundred and forty persons,
all distinguished by their names, who for keeping of meetings, refusing to swear,
not putting off their hats, not paying of tithes,
and their travelling up and down the country, had been taken up and imprisoned,
and many also had been deprived of their goods,
and one and twenty of these died either by sickness in prison, or by violent abuses;
among whom was Richard Sale, near West Chester, who being constable,
had a minister of the people called Quakers brought to him, with a pass as a vagabond,
whose conversation so convinced the constable, that he gave him his pass and liberty.
And because the said Sale judged both priests and people to be exceedingly darkened,
he entered upon an extraordinary act,
to show them by a sign that they wanted to be enlightened,
viz. he came in the day time with a lantern and a burning candle into the steeple-house,
during the sermon.
But this was resented to such a high degree,
that by order of the mayor he was put into prison,
and thrust into a hole called Little Ease, which was so strait,
that it could not well receive his body; but he was thrust in with such violence,
that his body was bruised, and he spit blood, and shortly after grew sick;
and his body swelling, occasioned by the squeezing it into the hole,
he died in great pain.
In the before mentioned account it was also said that in the last six years,
about two thousand persons, for being Quakers, had suffered in their body and goods.
To this was added a paper, signed by more than one hundred and sixty persons,
(several of whom I knew,) whereby they offered to the parliament
to put themselves in the stead of their brethren,
who were confined either in prisons, or houses of correction, or in dungeons,
some being fettered, and others lying sick only on a little straw;
wherefore they declared themselves ready to change places with them out of true love,
that so they might go out, and not die by hardship, as many had done already;
to prevent which,
they were willing to take upon themselves the sufferings of their brethren,
and lay down their lives for them.
Under their names they added, "`If we had been of Esau`'s race,
we should have fainted before this time; and if we had been of Cain`'s progeny,
we should have fought with his weapons: but this never was,
neither is it the way of the righteous and chosen, of which we are,
from the foundation of the world.`"
It was in the month called April, that this paper was delivered to the parliament,
but I do not find that this offer was accepted,
or any thing done for releasing the imprisoned.

About this time also Edward Burrough published a paper,
containing a very remarkable prediction of what followed the next year;
when king Charles the Second was placed on the throne.
In it he saith, that as he was travelling in Warwickshire, in the 1st month,
his meditations being upon the Lord,
and considering what unjust and woful sufferings had been
inflicted upon the Lord`'s people within these few years,
a cry went through him, "`The Lord will be avenged,
the Lord will be avenged upon his enemies, and he will avenge the cause of his people.`"
This cry stuck close upon him, and his heart was even broken therewith,
and his spirit melted before the Lord, it being as it were said to him,
"`Write unto the rulers, and yet once more warn them of that recompense,
and of that indignation, which is at hand upon them,
even a just recompense for all their deeds; and as they have done,
even so shall it be done to them;
as they have sought to destroy the generation of the righteous,
even so shall they be destroyed from off the face of the earth;
and as they have unjustly judged and condemned the innocent, so shall they be condemned,
and justly judged of the Lord;
and as they have cast the bodies of the poor lambs of Christ into prison,
and been a snare upon them, even so shall they be insnared,
and into captivity shall they go.
And as they have caused the goods and possessions of the innocent to be spoiled,
and made a prey,
even so in like manner shall the curse of the Lord spoil their substance.
And as they have done, so shall it be done unto them; and as they have meted to others,
so shall it be meted to them again.`"

[.embedded-content-document.paper]
--

And I [writes Edward Burough] saw a great misery
and desolation nigh at hand, even the sword of the Lord;
and that it should slay them; and I beheld it was made ready for the slaughter;
and in the sense of these things a sadness fell upon my spirit,
considering the desolation and the judgment that is at hand,
to be executed upon the cruel oppressors.`"

Wherefore all ye rulers, and all ye that have trodden down the heritage of God,
and ye that have disregarded these many warnings that ye have had; I say unto you all,
in the power of the Lord God, in his dominion, and by his Spirit,
this is once more a warning to you from the Lord,
and that these things must surely come to pass, and be fulfilled in their season,
and no man shall be able to deliver his brother; but every man shall bear his own burden,
and drink his own cup prepared for him:
and though it hath been counted a light thing amongst you,
and you have despised the reproof, and gone on without fear;
yet in as much as the Lord hath spared you, and not speedily executed judgment upon you,
but rather waited for your return; yet the dealing of the Lord towards you,
in sparing of you, you have not accepted;
and therefore shall his judgments be the greater upon you.
For if you do now come to the witness in your own consciences,
what evil hath this people done?
Whose ox have they taken, or what have they desired of you?
Or what have they sought from you?
Or wherein have they been a burden to you?
Saving that they have reproved you for your iniquities, and desired your redemption?
Would you but now at last come to consider this,
and confess the Truth in your consciences, will not that tell you,
that they have patiently suffered all things that you have cruelly imposed upon them?
And have not they walked peaceably towards you, and humbly, meekly,
and justly among their neighbours?
And have they not been meek and innocent even as lambs,
and as the sheep before the shearers?
And have they wrought offences towards any?
Have they sought the overthrow of the government,
or have they sought vengeance against their enemies?
Or what injury have they done to any man`'s person, or estate,
saving to Satan and his kingdom?
Have they not sought to reform and reclaim the ungodly from their ways?
And have they not pitied and prayed for their enemies?
And have they not in all things walked in good conscience towards the Lord,
and towards all men?
Yea, my friends, in the day of the Lord,
when the witness in your consciences shall not be limited, but shall speak plainly,
and when the impartial judge shall appear upon his throne,
then shall you acknowledge these things.

Wherefore I say unto you, receive the judgment of the Lord to purify you,
otherwise the judgment shall destroy you; and now come to be more wise,
that some of you may be as a brand plucked out of the fire,
and be reserved from being consumed; for the visitation of the Lord is near an end,
when his lovingkindness will be shut from you, and his long suffering turned into fury;
and he will make you know that we are his people, with whom you have thus dealt; yea,
you shall suddenly know it;
the time is not long till he will crown his people in the sight of his enemies;
he will crown them with praise and with righteousness, with honour and majesty,
and he will keep them in safety, even when sorrow compasses you about;
his mercy and lovingkindness shall extend towards them,
even when his wrath and judgment smites you, and confound you.
O! What shall I say unto you; for the deep sense thereof remains upon my heart;
when I consider, how that in all ages the Lord did avenge his people`'s cause,
and when the time of their suffering was expired, he broke the bonds of iniquity,
and set them free.
Thus did he with his people Israel of old, and many times it was his way with his people,
to bring them low by suffering, and then to raise them up again in glory;
and he suffered their enemies for a season to glory over them,
that he might bring them down.
And thus he did in England,
in the case between the bishops and their crew of persecutors,
and the poor people at that day called Puritans:
did not he confound that persecuting crew, and deliver his people?
And is not he the same to effect the same work at this very day?
Yea, doubtless, and much more will he do,
in as much as the manifestation of Truth is more clear than it was in their days;
and in as much as the rulers and people of this nation have rejected a more clear testimony,
than either the Papists in Queen Mary`'s days, or the bishops and prelates in their days;
even so much the more will the Lord God execute his vengeance with more violence,
in a more manifest way; and all shall know, that it is he that doth it,
and he will set his people free: for he hath regarded their sufferings,
and he hath said it is enough; for he hath tried them, and found them faithful;
and all this hath been suffered to prove them, and not to destroy them:
and like as he hath preserved them in patience and peace through it all,
even so will he give them hearts to walk answerably to their deliverance;
and as they have abounded in patience in their sufferings,
so shall they abound in praises everlasting in the day of their freedom;
and the earth shall be glad, and shall yield the increase and blessing:
the heavens and earth shall rejoice, and the hearts of the righteous shall leap for joy;
when the Lord hath broken the yoke of the oppressed, and set his people free,
inwardly and outwardly; and then shall they sing to the Lord over all their enemies,
who shall be tormented and vexed in the Lord`'s sore displeasure;
for their reward cometh, and their recompense shall be even as their work,
and he will give unto them sorrow and anguish, instead of rejoicing.

But again, when I considered the long-suffering, and patience,
and forbearance of the Lord`'s innocent people under all their sufferings;
and when I looked at their innocency, and at their righteousness, and spirit of holiness,
with which the Lord hath blessed them,
my heart was made glad in the consideration of this; and the more was my joy,
the more I beheld their innocency, and the guiltlessness of their cause;
whereby the unjustness of their suffering did the more appear: and withal,
when I looked and beheld their increase under all their sufferings,
and how that the Lord had turned all these things to their good,
and to the overthrow of all their enemies; how that by that way,
wherein their enemies intended to destroy them from being a people,
even thereby did the Lord most wonderfully increase them to be a great people;
for through all have they grown in life and power, and in strength, and in number,
and through it all have they been encouraged to follow the Lord with more zeal and boldness.
And in the consideration of this I did rejoice, with magnifying the Lord forever,
that he had brought forth his praise, even through the wickedness of the wicked,
and he had increased his people,
and exalted them through the cruelty of all their enemies;
and that through all opposition they were attained unto a happy rest,
and through all the tempest of great trial,
they were arrived into the harbour of renown and great glory: and when I consider this,
how that the Lord hath given them dominion,
and brought their life to reign over all their enemies, these things were a joy unto me;
and looking back into ages, seeing there was nothing, nor any people for generations,
that had grown, and risen through all opposition like unto these;
wherefore it is a sign and testimony that we are the Lord`'s,
and that these things are of him, and from him, and by him alone,
that he might be praised forever.

Again, when I do consider, how that the Lord had raised his people, even out of the dust;
and them that were not a people, are become a people,
and the Lord hath provoked nations by them that were not a people within these few years;
and the Lord hath carried on this work amongst his people, not by any thing of man,
nor by the arm of flesh; but in pure innocency and simplicity hath it been accomplished;
not by the wisdom of this world, nor by men in places of honour,
and of power in the nations; for all that has been wanting to them; and what they are,
it is through the opposition of all this;
for they have had none of the great men of the earth on their side to defend them,
and establish them, but all have been against them;
and even oppression and tyranny executed upon them, rather than any approbation,
or justification from men in outward authority: so that truly it may be said,
there hath been nothing of man in this work, but all of the Lord, by his own power;
and in a contrary way to all the false sects, and false churches,
hath the beginning and carrying on of these things been:
for we know that all the false sects in this nation,
have risen and been established through the countenance of men in place and power;
and upon man, and the wisdom of this world, and authority of the powers of the earth,
hath the rise and fall of all false churches depended;
and as the powers of the earth have sided with them, so have they been set up;
and at the displeasure of authority, have been cast down.
But as for this people, they are raised of the Lord, and established by him,
even contrary to all men; and they have given their power only to God,
and they cannot give their power to any mortal men,
to stand or fall by any outward authority, and to that they cannot seek;
but to the Lord alone, who heareth their cry, and will avenge their cause.

Wherefore let all the persecutors bow before the Lord,
and let all the saints walk humbly in his sight,
and let them continue in that innocent life in which they have begun;
and let them never forget the mercies of the Lord, and what he hath brought to pass,
who hath manifested great things,
and will do more and more to the confounding of all his enemies,
and to the praise of his elect people.
And all ye saints upon the earth, have ye the Lord in respect continually,
and turn you not unto idols, but let the Lord be your joy forevermore.

[.signed-section-signature]
E+++.+++ B.

--

Not long after the publishing of this paper, to wit, in the month called May,
Edward Burrough, and Samuel Fisher, went from Dover to Dunkirk,
where there was an English garrison.
Being come there, it quickly spread over the town.
The governor, Lockhart, now not being there, his deputy, colonel Alsop,
with the council of officers, sent for them; and they being come, were asked,
what their business was there?
To which they gave answer, and the next morning signified in writing,
that their coming was to visit the jesuits, friars, and priests, and other papists,
to show them the errors of their ways, and the falseness of their worship,
etc. they being called to preach the everlasting gospel to the nations.
They were some hours in discourse with the said deputy, and the officers,
and not unkindly treated; but the deputy however said,
that it would be dangerous for them to stay in the town:
and therefore he desired them to depart.
To which their answer was, that if he desired them, they,
could not receive any such desire; and if he commanded them,
they could not obey his command in that case;
because they could not depart the town but in the will of God;
according to which will they came thither.
After much reasoning they left them, and the next day went to the Capuchin friars,
and had some discourse with the chiefest of them in their garden,
concerning the light of Christ, that every man is enlightened withal; and told them,
that the mighty day of the Lord was at hand upon them;
and that the Lord was come to search and try them;
and that he would hew down their idolatrous ways, worships and works.
The next day Burrough wrote some queries to the friars and nuns, in and about that town,
which were sent to them in Latin.
The introduction was thus:

[.embedded-content-document]
--

The mighty day of the Lord is come, and coming upon you, and all the world.
Awake, awake, ye that sleep in the earth,
for the dreadful God is arising to plead with you,
and to give unto all the world the cup of his fierce indignation,
because of your idolatries, and hypocrisies, and abominations,
which have corrupted the earth, and are come up before him, and have provoked him;
and the cry of the just, who have been smitten, and laid slain,
is entered into the ears of the Most High, and his sword, which is the word of his mouth,
is awakened to wound and destroy all his enemies.
And the day of your visitation is now come, wherein the Lord is searching you,
and trying you, that he may recompense you: and this is the word of the Lord to you.

Wherefore, I am moved of the Lord to propound some few queries to you,
for the trial of your spirits and ways; to which I demand your answer,
that all things may be brought to light and true judgment,
and that you may be judged justly,
and by the spirit of the Lord cleared or condemned according to your deeds.

--

These queries were partly concerning the orders of friars and nuns,
whether any such were in the church in the apostles`' days;
and concerning the popish worship and ceremonies,
demanding proof of their lawfulness from the Holy Scriptures.
After the delivering of these queries to the Capuchins,
Burrough and Fisher went also to the friars of other orders,
and entered into discourse with them:
but their plain speeches against the idolatrous rites and ceremonies, found no entrance.
After some stay in the town, they going to the college of the jesuits,
got into discourse with their chief rector; and after a conference of about three hours,
he grew weary, and pretending other business, would stay no longer with them;
and so they parted, asking him, whether he would admit more discourse at some other time;
but he refused it.
Burrough afterwards wrote a letter to him, which began thus: "`Friend,
thy wisdom and thy knowledge is earthly and sensual,
and thereby canst thou not know the things of the
kingdom of God:`" and he concluded with this query:
"`What is that whore that hath sat upon multitudes of people?
and what is that golden cup in her hand?
and what are the abominations and fornication of which her cup is full,
which she hath caused the kings and people to drink,`" etc.

But neither this query nor the others were answered.
Burrough and Fisher did also visit the nuns; and speaking to them through a grate,
they asked if they were of the order of those called Quakers;
and soon perceiving they were such, they said, they might not hear them,
and so presently passed away;
whereby Burrough and Fisher were deprived of any opportunity to speak to them;
only they witnessed against them.
E+++.+++ Burrough wrote also some propositions to the jesuits, priests, and friars,
wherein he particularly represented the tyranny of the church of Rome in true colours;
and these propositions were sent to them in Latin.
They stayed yet some days in town, and had divers meetings among the English soldiers:
and Burrough also wrote to them, and bid them be faithful to the Lord,
and not to seek themselves in their service, but the honour of God:
he also showed them what their duty was in their military station; and,
(not to give them too rough a brush, but to meet them somewhat in their own way;
following therein the example of John the Baptist, when he spoke to the soldiers,
Luke 3:14) told them,
"`What do you know but the Lord may have some good work for you to do,
if you be faithful to him?`"
and he also signified to them,
that since the Lord one day would avenge the innocent blood shed in the pope`'s dominion,
and appear against Babylon and Rome, the seat of the whore,
and the kingdom of antichrist, it seemed not improbable to him,
that the Lord would make way thereto by the English nation.
"`It is,`" said he, "`the Lord`'s work, I know, to make men truly religious;
but yet he may work by you, to break down the briars and thorns,
and the rocks and hills that have set themselves against the Lord,`" etc.
He also advised them, if ever such a work fell to be their lot, not to be ambitious,
nor vain-glorious,
but to make it their work to demand the disannulling
of the popish inquisition and cruel laws.
And the officers he charged, not to be as tyrants and oppressors over the poor soldiers,
but to be loving and meek, and examples of all goodness unto them; to this he added:
"`and having no sin lying upon your consciences,
then shall ye face your enemies with courage, and not fear death,
but shall be ready to lay down your lives in a good cause.`"
But lest any might think he was for the bearing of arms,
and not for harmlessness or non-resistance, he told them also,
that the Lord had a more honourable work to work after them,
viz. to destroy the kingdom of the devil, and the ground of wars.
And that there was a more honourable victory to be waited for, to wit,
the victory over sin, etc.

Burrough and Fisher being once sent for by the governor Lockhart,
found many officers with him; and after some friendly discourse,
they advised them to moderation, and the fear of God, and so parted from them:
and after having performed their service in the town, they returned to England.

Not long after Burrough gave the aforesaid queries out in print,
and wrote also a paper to the parliament;
exhorting those that were members of that assembly, to fear God,
and not to oppress honest people, but to free them from oppression and tyranny;
lest the Lord come suddenly upon them and break them to pieces.

The power of the protector Richard Cromwell already declining,
he was prevailed upon by the officers of the army to dissolve this parliament,
which began to make inquiry how the subsidies were employed;
and by the direction of some of the chief republicans,
the long parliament was called again.
This parliament set up a committee of safety,
for apprehending those that disturbed the peace,
and for making an alteration among the military officers, either by cashiering them,
or otherwise; and, increasing in power, erected also a council of state;
and word was sent to Richard Cromwell, who was now deprived of all power,
to remove from Whitehall, which at length he did,
the parliament allowing him two thousand pounds for the charges of removing,
and promising to pay his debts contracted for the public: and his brother Henry,
who was lord deputy of Ireland, was called back by the parliament.
Thus these two brothers were again reduced to the state of private men.

E+++.+++ Burrough now wrote a letter to the parliament,
and seriously exhorted them therein to desist from all persecution for religion,
and to take away that which gave occasion thereunto.
About this time there was an insurrection in Cheshire for king Charles,
under sir George Booth; who, having received a commission from that prince,
got such numbers of followers, that he seized the city of Chester.
In the meanwhile the parliament sent Edmund Ludlow to Ireland,
to be commander in chief of the army there, instead of Henry Cromwell,
and general Lambert was sent with an army against Booth.
Now since some rash people that went under the name of Quakers,
were for taking up arms under Lambert;
and that the committee of safety offered great places and commands to some of that persuasion,
thereby to draw them off from the truth they professed; G. Fox wrote a paper,
wherein he showed the unlawfulness of wars and fightings,
representing it as a work not at all becoming the followers of Christ:
and he exhorted his friends not to join with those that took up arms,
but to fight only with spiritual weapons, which took away the occasion of the carnal.
This he also recommended in his preaching, for an harmless and inoffensive life,
was that which he always asserted and practised.

As for Booth, he was defeated, and endeavouring to make his escape in women`'s clothes,
was discovered in an inn, and taken into custody; and being carried to London,
by an order of the parliament, he was committed to the Tower.
The officers of the army, of which George Fleetwood was now commander in chief,
were very busy to get the upper hand of the parliament;
which caused great division and distraction in the nation;
for it was well known that if the supreme power was offered up to the army,
they then could do what they would; and thus the nation would be governed by the sword.
It was also fresh in memory,
that it was the army by which Cromwell had been advanced so as to become protector,
and supreme ruler of the nation: and therefore many opposed the design on foot.

About this time also the military officers moved the taking off of the burden of tithes,
and to settle another maintenance for the national preachers.
But being unwilling that the parliament should be masters of the army,
they complained of having been deceived by the parliament; and colonel Desborough said,
that they had not performed any part of the promises they had made to the army;
that they had taken no care to secure a liberty to tender consciences;
and that their intention was to remove the principal officers,
and place others in their commands, who were of different principles.

Now the council of officers was for calling a new parliament;
but this met with no small opposition.
In this bustle the council of officers began to insinuate with the clergy,
and they agreed with them,
that their maintenance by tithes should not be taken away till
another revenue as ample and certain should be settled upon them;
that some provision should be made for those who differed
in faith and worship from the established church;
but that the Quakers and some others,
whose principles they said tended to the destruction of civil society,
should not be tolerated at all.
In this distracted state of affairs, when some were for,
and others against the parliament,
so that it was hardly well known in whom the supreme authority resided,
Edward Burrough wrote and published in print a large speech, which he stiled, [.book-title]#A Message to the Present Rulers of England, Whether Committee of Safety, So Called,
Council of Officers, or Others Whatsoever.#
He signified by way of introduction,
that the contents had been upon him to deliver by speech and word of mouth,
to the men then in power; but no way being made for him so to do,
he had written what was upon him.
And then he begins thus with a majestic strain.

[.embedded-content-document]
--

[.salutation]
Friends,

My Master, is a high, and mighty, and powerful prince, and very honourable; and fear,
reverence, respect, and subjection belong to him alone, from you and all mankind.
He is wise, and understanding, and of great strength,
and his dominion is from everlasting to everlasting;
and he can do whatsoever he will in heaven and earth,
for he rules with his iron rod over the world, and whatsoever he saith, it is done;
for his word is an everlasting command.
If he saith to a man, live, it is so; if he saith to a man, die, it cometh to pass;
and if he give peace to a man, or a nation, none can make war;
and if he make war with a person, or in a nation, no man is able to make peace.
For why?
He hath all power in his hand, and to him all judgment and authority is given;
he is the Son of the living God, the everlasting Creator.
He was, and is, and is to come; his eye beholdeth all things,
and his arm compasseth heaven and earth; and what his purpose is,
he hath always and will ever bring it to pass.
If he set up rulers, they must rule; and if he pull them down none can hinder:
whom he will, he honoureth; and if it be his pleasure, he bringeth men to shame.
If he break a nation down, none can build it up;
and if he confound powers and authorities in the kingdoms of men,
they all fall as withered grass before him.
Behold, ye men!
He is so great and mighty, and of so great authority, that whatsoever he saith,
it is done; and whatsoever he willeth, it cometh to pass; and none is able to resist him,
and overcome his power, when his pleasure is to accomplish a work.
By him all things are that be, and all things live that have life,
and through him all things move, and of his fullness,
every creature in heaven and earth receive.
And this, my Master, is altogether honourable in birth, and otherwise,
and altogether mighty in all his works; he is just and merciful, full of goodness,
righteousness, and truth; all virtue dwells in him, and his judgment and mercy,
his authority and meekness, and his wrath and his love, they are companions:
and what are ye before him?
Or how shall ye be able to resist him, or to turn backward what his purpose is,
concerning you, and this nation?
For ye have no being nor breath without him.
Behold ye men!
Ye are verily as the dust before the wind, so are ye to him, soon blown away,
and your place not found; as the grass before the mower, so are ye before him,
soon cut down, and whithered, and your beauty utterly extinguished:
as a potter`'s vessel under an iron rod, even so are you to him,
he can immediately break you, never to be bound up; as a drop to the fountain,
so are you to him, soon dried up and made nothing.
Wherefore, ye men, ye mortal creatures, ye ignorant persons, sons of a transgressor,
ye dust and ashes: for thus you are in comparison of him, this mighty prince;
hearken to his message, which cometh to you from him; hear and fear,
and be not stout-hearted against the Lord God, that is about to speak unto you.

As for this little island of England, wherein your present place and being is,
it is an island which the Lord hath showed great favour unto in ages past,
and in this present time; and I must tell you, he hath a purpose of love towards it,
and to honour it in the view of the world, though through great tribulations:
and he hath an intent of great good unto it; for he hath a seed,
a precious seed in it scattered abroad, and he hath a people that fear his name,
and have walked in his ways, and he hath made them, and elected them, and what they are,
it is by him; that he may dwell among them, and have the whole government over them all;
yea, he hath a speedy purpose verily concerning this nation,
and he will purify it in judgment,
and refine its inhabitants through the fire of tribulations,
that it may be pleasant to him, and fit to do his will:
he hath a purpose to work some great thing in it, I must tell you,
as he hath said unto me so to do;
he will have his name exalted and reverenced in this island,
and his terror shall be sent out of it through the world,
and his branch from it shall spread over the earth;
he doth purpose in his season to take it into his own hand,
and to sway the government thereof with his own sceptre,
and to set up righteousness alone, and to overthrow all oppressors and oppressions;
and the kingdoms of this world must become the kingdoms of the Lord, and of his Christ.

True it is, such hath been the coming to pass of time,
and of things for many ages by-past, that my master hath been, as it were,
banished from the nation, and hath not been suffered to enjoy his right;
but hath been expelled, even, as it were, by the force of Satan and antichrist,
who hath long usurped authority over the inhabitants of this nation;
and in my Master`'s absence, lamentable injustice, cruelty, unmercifulness, tyranny,
and oppression have been exercised upon the inhabitants;
and the poor creatures have been held in great slavery by their rulers,
that have ruled by the dragon`'s power; and been kept in great blindness and ignorance,
and under great oppression, both in body and spirit, by antichristian teachers,
for this many years; even while the great King hath been absent, and, as it were,
gone into a far country;
even all this time hath antichrist and the devil ruled and reigned,
and have made and executed oppression, and tyrannical laws and decrees,
both in church and state; and all the nation hath been out of right order,
and laid waste and barren of good fruit,
and it hath been as a wilderness by reason hereof;
and men that have ruled for many years, have not ruled singly by my Master`'s authority,
but by another power; though not without the knowledge of my Lord,
neither as though he had not power to have done otherwise;
but for his own pleasure he hath suffered it thus to be,
and let men go on to rule and govern in their own wills, and after their own lusts;
and people have walked wickedly towards him, and towards one another;
and all this he hath suffered; not as if he gave toleration for it;
for his messengers now and then, and his witness in people`'s consciences,
have been reproving their ungodly ways;
and he hath often showed his dislike by divers ways, and tokens, and many judgments,
and strange overturning, to the way and proceedings of both rulers, prophets,
and teachers of this nation; but yet they have gone on against his mind,
and contrary to his will, notwithstanding his reproofs and judgments.
Not that he had not power to have executed his pleasure in wrath upon them,
and to have destroyed them altogether, and have made the nation a heap,
and as nothing long before this day; for power was in his hand to have done it;
but he hath been long-suffering and of great patience, and borne all things,
and taken the injustice, and cruelty, and wickedness, and idolatry,
and all unrighteousness that hath abounded in the nation upon himself,
and suffered under it, and borne it for its season,
while woful and lamentable oppressions have been practised in civil state,
even hellish laws, and devilish executors of them;
merciless tyrants have borne the sceptre,
and reigned for many years over the inhabitants,
and in church and state have been heinous idolatry and superstitious
vanities committed in a high nature and measure,
and even all men, and states of men,
and orders of men of every degree have been abominably corrupted in the sight of my Lord,
even from the prince to the beggar, even rulers and subjects, teachers and people,
judges and prophets.
They have been corrupted both in heart and hand,
and they have dealt falsely and wickedly towards him and towards one another;
even to the great displeasure and vexation of him, and his blessed spirit,
and to the high provocation of him to their own destruction,
if his long-suffering had not prevailed;
and all this while he hath lain as it were asleep, and at rest in himself;
and he hath left men to try them, what they will do, and he hath given them a day;
many kings and rulers, he hath let them have a little time, to see how they would use it,
but they have abused it and not ruled for him,
nor accomplished his work nor fulfilled his will,
but acted even in defiance of him and of his power, and to his great dishonour.

Alack!
I must be plain with you: my Lord hath been utterly exiled, and greatly dishonoured,
and highly provoked and vexed by reason of such proceedings,
as have been in this nation for this many years,
through the corruption of all sorts of men in place and power,
who have not ruled for him, but for the devil to their own corrupted ends:
only he hath suffered men to go on in their course for a season;
some as it were appearing on the stage for a time,
and suddenly cast down again for their iniquities sake;
and his hand hath been in all these things, though very privately and secretly,
not known and discerned by the sons of men, yet hath he ruled over the kingdoms of men,
and pulled down one, and set up another.
And to forbear the several actings and proceedings of many by-passed ages,
and to come to this generation,
and to speak of things that have happened within these few years,
and of the changing and overturning that hath happened in this nation;
such was the cruelty, tyranny, oppression and idolatry both in church and civil state,
that the people of this nation were held under, in the days of papal power; such, I say,
was the exceeding height of the cruelty and tyranny of that time,
that not any that feared or reverenced my Lord, in any measure, could scarce live,
or have a being in the nation.
Even against every man that did but incline towards him,
and desire the knowledge of his ways, hell`'s mouth was opened against them,
and they were swallowed, and many of their lives taken from the earth,
by the hellish power that had in that day usurped authority in this island;
and when thus it was, then he looked down from heaven,
and his bowels of compassion were opened,
for the sake of the oppressed people that desired after him,
in so much that he broke and threw down the power of their oppressors in some measure,
as it stood in papal authority, and when the iniquity of that power was filled up,
he took vengeance upon it; and I must tell you, it was he that brought it about,
even the destroying of that power in this nation, and freeing the nation from it,
though the men that were instruments in the cause were not his servants,
otherwise than as Nebuchadnezzar served him;
for he hath a secret way to have a service from the wicked, and such is his power,
that he can turn the wickedness of the wicked to his glory,
and he can make a rod to whip his adversaries, and burn it when he hath done,
and he hath often destroyed one wickedness by another.

Well, but to leave that, though he did in some measure,
free the nation from much tyranny and cruelty, in the casting out popish authority,
yet alack! the nation in a few years was near as much violated by injustice and cruelty,
under the succeeding power, as ever it was once under the papal power; though before,
there had been some small reformation and change in outward appearance,
though little in ground and nature; yet oppression, and idolatry, and superstition,
in church and state, and all profaneness and wickedness among people were grown so high,
like as it had been under the papal power before; and all that desired after the Lord,
and were weary of iniquity, and of the then present oppressions and idolatries,
were persecuted, and slain, and destroyed; and injustice and cruelty exercised upon them,
even almost to the rooting out of righteousness,
and to the grieving of the Lord`'s spirit.
Well then, because of the cry of the people,
and the oppression of the nation under that authority, my Lord looked down again;
and even for his name`'s sake, and for his seed`'s sake,
he had compassion on this nation, to set it free, and to break off its oppressions;
and in a great measure he did deliver the people of this nation in many things,
and there was a part of reformation wrought, and much pretended and looked for;
and all this came to pass through him, and my Lord did accomplish it,
however the instruments by which he wrought proved deceitful, and became oppressors,
as others before them; and though there was in this nation a day of great troubles,
and wars, and contention, and great strife, and the wasting of much blood,
and earthly treasure, and none of these things, I must tell you,
fell without the ordering of my Master`'s hand; yet so it was, and came to pass,
that after this nation was restored to peace,
though much unrighteousness and injustice was removed,
yet there was much also left behind; and men that he had used as instruments in his hand,
in a good work, and to whom he had given wisdom and understanding,
and appeared in much mercy and in great deliverance,
yet they even turned to seek themselves,
and became corrupted in the spoils of their enemies.
And when peace and plenty abounded, the Lord was forgotten again;
and then the land fell under oppressors, and began again to cry out for freedom,
even when other horns of the first beast sprang up,
and went on each of them after his fellow.
And though one horn hath striven to break another, yet after one hath been cast down,
another hath risen, and made an image to the first;
and ruled and reigned by the same spirit, and authority,
derived from the dragon`'s power in cruelty and oppression;
and made laws and executed them to the dishonour of the Lord,
and to the great oppression of his people,
and to the filling of this island with injustice and cruelty,
even from one generation to another, until this day:
and thus up and down have times and seasons been altered,
powers and authorities changed and altered, statutes, laws, and decrees,
changeable and alterable; for as the iniquity of one power was filled up,
that was cast down, and another had its day, till the measure thereof was also filled up,
that it might partake of the same judgments.
And in all these overturnings, breakings-down, and overthrowings,
the very hand of my Lord hath been, though secretly, and not discerned;
yet his power hath brought about, and suffered all these things to come to pass:
and who shall charge him with injustice?
Or, who shall say, "`What hast thou done?`"
Or, "`Why hast thou done it?`"
For, as I have said, he is a high and mighty prince, and can do whatsoever he will;
and he is the supreme power and authority,
which rules and reigns in and over all the kingdoms of men.
And what though he hath used wicked men as an instrument to accomplish his work,
and made the wicked his rod; and even brought it to pass,
that one wickedness should destroy another, and one oppressor break down another,
and the kingdom of antichrist confound itself; yet what of all these things?
All flesh must be silent before him, and all people,
and the whole earth must be subject unto him;
for the government and dominion over heaven and earth is his,
and all power and dominion belongeth to him alone, and all judgment is in his hand,
to bring to pass whatsoever he will, and by whomsoever, as he pleaseth.

But now, my friends, though I would not be tedious to you, yet must I tell you the truth,
and faithfully deliver the Lord`'s message unto you;
and as concerning this last overturning,
there was something of the hand of my Lord in it; and he can,
and will bring forth his own work and praise by it,
and it shall be for the good of all his people, that wait upon him,
though there was much ambition and corrupted ends in the instruments,
and neither part were perfectly single to the Lord in their proceedings,
but their work was tainted with the false idolatrous spirit of self-seeking;
yet notwithstanding, the Lord may bring forth his government, and his pleasant plant,
through and beyond all this, even out of another root,
which yet appears not among either of them; and righteousness may arise in the nation,
contrary to both of them, out of another stem, and he will set up his kingdom,
and in the meantime, leave one potsherd of the earth to break another.

And as for you, that now sit on the throne and bear rule, whether committee of safety,
so called, chiefly, though it is not without my Master,
for he hath the knowledge of it at least, yet you are not the only men of his choice,
truly called of him to the place of government,
neither is your government the government of the Lamb,
neither must it be forever established by him; its foundation is not blessed,
nor can its building be prosperous.
For why?
Alas, it is but another horn of that fourth beast,
that hath been made to rule over the world, and upon the earth for many generations,
and it is but hitherto a very little refined from the last, and is of the last,
even as the eighth was of the seventh, spoken of by that servant, Rev. 17:11,
and it may also make war with the Lamb and his followers for a little season,
and it may have a small measure of injustice and persecution to bring forth in the land,
even till the words of God be fulfilled, and his kingdom be fully come,
the way of which is but yet preparing by all these overturnings.
And this your present government originally is leavened with the spirit of the old dragon,
that hath killed the saints, and drunk their blood, and how should the Lord establish it?
Nay, your kingdom may prove but small and little, and full of uproars and troubles,
and little peace, and satisfaction and establishment in it to yourselves,
or the people under you; but confusion will attend it, and fears will compass it about:
though this I must tell you, as you are men, you have your day of trial what you will do,
as many others have had before you; and something you may and ought to do,
if but to make the whore, (the false church,) more naked, and to scourge her,
more than some others have done; and indeed my Lord requires something more of you,
(as such,) to do, than others before you could do;
and you have a price put into your hands, which you may improve to the Lord`'s honour,
and to the nation`'s good, and to your own happiness; which,
if you will be faithful to the Lord, to do what he requires of you,
and if you become meek and humble men, and fear his name, and deny yourselves,
and not seek your own honours, nor any earthly advantage to yourselves; if you do thus,
then my Lord will show mercy to you, and you shall not suddenly fall before your enemies,
though many may rise up against you; but your days shall be lengthened,
and the purpose of the Lord may be turned to your longer continuance,
and not to your sudden destruction; and if you walk in this way,
and rule only for the Lord, then shall you be honoured as men if not as an authority,
and you and the nation preserved in peace,
and the force of the wicked shall be turned backward, and you shall not suddenly fall.

And the late sundry overturnings in this nation may be examples to you,
that you follow not the steps of those that God hath cast out,
lest you come to the same end of confusion and misery: for,
as concerning that assembly of men, that last sat on the throne,
something was done by them in their day and time, and in both their assemblings,
in some things they served my Lord, and they were a rod in his hand to smite his enemies;
yet they were not faithful to the end, till all his enemies were destroyed,
but rather joined themselves to fight against the Lord and his people,
and were hastening on towards the way of oppression and persecution;
and it was time for the Lord to remove them, and to lay them aside as an empty vessel,
sometime useful; and to break them as a rod,
sometime of service to be a scourge upon his enemies.
And when the day of their trial was over, which God gave unto them, being any longer,
(at present,) unfit instruments for his hand, then he cast them into the fire;
and this his purpose came to pass upon them;
so that they and the whole nation may be contented,
and yield themselves subject to what he hath done concerning them;
for they being entering into the very same spirit of wickedness,
of oppression and persecution, which the Lord had once reproved through them,
and cast out by them; then was a rod raised up against them,
even as they had been against others,
and they were dealt withal as they had done to others;
and this was in the justice of my Lord`'s hand;
and what hath mortal man to question his proceedings?
And though some of you,
(present rulers,) be looked upon as great traitors
and tyrants in your dealings towards them;
and doubtless the men of that part will seek vengeance against you,
even by preaching and praying; and they will curse you in the name of their God,
and seek continually your destruction, as such as have taken away part of their strength,
and cast down their idol; but alas!
All this is nothing; for the Lord doth not account as men;
for these things must needs thus come to pass,
for the furtherance of the kingdom and government of Jesus Christ,
that it may arise through all;
and if you were but faithful to what the Lord requires of you, in your proceedings,
what you have done unto them should not be reckoned on account against you,
neither by God, nor good men.
But if you of the army be always treacherous and disobedient towards him,
and abuse your power, and disregard your price that God hath given you,
and trifle away your hour about places of honour, and such self-seeking matters,
and the cause of God be neglected by you,
and his people continued oppressed sufferers under you, as they have long been;
even then shall you be cast aside with shameful disgrace,
and the heavy hand of the Lord shall be upon you in judgment,
and you shall be smitten more than any before you;
your estates shall not be spared from the spoiler, nor your souls from the pit,
nor your persons from the violence of men, no, nor your necks from the axe:
for if you be unfaithful, and continually treacherous to the cause of God,
then shall you be left to the will of your enemies,
and they shall charge treachery and treason upon you,
and your persons and estates shall be given for a prey to your enemies;
and you shall not deliver yourselves,
neither will the Lord deliver you from the execution of merciless men;
for my Lord shall leave the cruel hearted to plead with you.

Wherefore, that you may be warned, I advise you to be faithful;
let not the cause of God fall, nor the cause of his enemies prosper before you;
for there is no other way whereby you can be preserved,
nor no other defence shall you ever find from the wrath of the Lord,
and from the fury of your devouring enemies, than your faithfulness in God`'s cause;
and therefore relieve the oppressed, and take off all oppressions,
break down all unjust laws, and set all people free from unjust burdens,
and let all oppression cease, both in church and civil state;
and even all oppressive laws, and unjust judges, and evil men in power,
let all these be removed, and the nation clean quitted and discharged,
even from all men and laws whatsoever, that have held under oppression the persons,
estates, and consciences of the good people of this land;
and let the nation be corrected, and all orders and places of men,
and laws and decrees be purified: for this my Lord, the great King, requireth,
and he will suddenly have it brought to pass in the nation, if not by you,
then contrary to you, and to your utter destruction.
And this is the very substance of my message to you,
that my Master hath given me to say unto you;
and on his behalf I am come to claim of you my Master`'s long lost right:
let him have his right, from which he hath long been banished; I demand it of you,
all ye whatsoever, that seem to bear rule in the nation;
I charge you in his name let him have his title and prerogative,
let him be Lord and King wholly in his own kingdom,
let him have the exercise of his people`'s consciences by his own
Spirit in all things relating to his worship and service;
and let him have the full authority by his Spirit
in all things pertaining to church and ministry,
and faith, and religion;
and let his Spirit have the alone authority to persuade and dissuade people from, or to,
such or such ministry, worship, and practices of religion;
and let all forced maintenance to ministers, and tithes, be speedily taken away;
and let all laws and decrees whatsoever, made and practised in the days of antichrist,
upon the bodies, estates, and consciences of the people,
in oppression and unjustness about church, and worship, and religion,
be utterly repealed, and made void, and never more be in force in this nation;
but let my Lord be sole ruler and governor,
and have the full authority in his own kingdom,
in all things whatsoever pertaining thereunto.
And let no man henceforth hereafter be entrusted
with the liberties of the members of Christ`'s kingdom,
as they are such, nor to judge over them in any matters of faith and worship,
but give that right and privilege wholly unto the Spirit of Jesus Christ;
for unto him only it pertaineth to be whole judge,
and to have full power in his own kingdom; and until you give him the right,
and deliver up unto him his own kingdom,
and the exercise of peoples`' consciences in all things about religion,
you shall never prosper, nor none that cometh after you,
that shall in any measure abridge my Master of his proper right,
from which he hath long been banished, as I have said; and till his right be given him,
in the case aforesaid, he will dash one man against another,
and none shall ever be established; but horn after horn shall be broken,
and one power after another brought into confusion.

And, therefore, ye men, do not strive with him in this matter,
but yield unto him the exercise of your own consciences by his Spirit in you,
and let him do so unto all others, even as ye hope to prosper,
and upon the penalty of his sore displeasure upon you in this world,
and in the world to come; and let just men, and righteous men, and meek men,
and men that have the fear and wisdom of God in them, without acceptation of birth,
or otherwise; let such men have the power and judgment committed to them,
to determine in things between man and man.
Down with all the false-hearted flatterers, that have ruled for man and not for God,
and for themselves, and not for the good of the people; cast all such out from you;
for the good among you is choked by them: down with all that judge for rewards;
and away with all hireling rulers, that execute the law for money,
and will not plead the cause of the poor without great fees;
and down with all that will not serve places of trust without so large stipends;
away with all these things out of the land, for they are heinous oppressions unto men,
and great abominations in the sight of God;
and the land hath long groaned under the weight and burden of these things,
and the earth is weary of them, and my Lord requires their utter dissolution,
as being iniquities fully ripe, and having the guilt of so much cruelty, injustice,
and oppression lying upon the nation because hereof;
therefore is the Lord`'s season to destroy them, and remove them out of the land;
which if you be the instruments in such a work, it will be your greatest crown,
and your perpetual honour.
For the Lord`'s purpose is one way or other to cleanse
the land of all these and other oppressions whatsoever,
that the people of this land may be a free people from all the heavy yokes of antichrist,
which have long sorely pressed them down;
and the purpose of the Lord is to break the yokes of oppression
and tyranny from off the necks of this people;
and therefore it is that he overturneth, yea, and will overturn,
all men and authorities that shall oppose his work,
and none shall be able to stand before him;
for the presence of my Lord is more dreadful to a nation, when he shows himself in wrath,
than any multitude of armed men; and woe is unto you, if you be found opposing of him;
and if you seek to stop his work, you shall not cumber the earth very long,
nor oppress the nations many days.
Wherefore consider, cursed will you be,
if you be unfaithful in what you have to do on the Lord`'s behalf;
for your hour passeth over, that is allotted you; and will be suddenly expired,
never to be recalled, and then you cannot work.

And whereas there is a great cry about ministry, for sending forth and maintaining,
and encouraging a godly ministry, as you say.

Now to this I do answer on my Lord`'s behalf, and I must tell you plainly;
as for a true godly ministry, truly called and sent of God, such a ministry,
and such ministers you can never be able to hinder; but the Lord will send them out,
maintaining them and preserving them, whether you will or no;
and while you are troubling yourselves about such a matter,
you are but meddling with things above your line, and out of your jurisdiction,
while you act in such a case; for it belongs to his government to send out ministers,
whom, and as he will, and to maintain them and defend them according to his own pleasure,
and all this without you; for such ministers, truly called thereunto,
and sent of the Lord, will not seek to you to be sent forth, or maintained by you,
they will not be beholden to you in such a case; but even without you,
and contrary to you, must they be sent out and maintained;
so that the Lord will have a ministry in this nation purely of his own, and not of man,
nor by man, and such a ministry you shall not be able to hinder.

And I must tell you plainly, as for these men called ministers, in this nation,
the way of their setting up, and sending forth, and the way of their maintenance,
and the way of their standing and defence, and in every particular of their being such,
they are the greatest and most woful oppression in the nation;
even the most abominable and unjust cruelties and tyrannies are acted through them,
as any other thing in the nation; and they are,
(as such aforesaid,) the woful cause of the nation`'s groaning under merciless dealing;
and there is upon their account, the guilt of blood, injustice,
and oppression lying upon this nation; their iniquities, their iniquities,
cry for vengeance upon their own heads; for they are full, they are full,
and the measure thereof is near finished,
and God`'s eternal vengeance is their next reward from the eternal God.
What shall I say of them, but this?
The earth is oppressed by them, the inhabitants groan under them,
and the righteous God is vexed through them,
and they are the very men of high indignation and fierce wrath, and all their practices,
(as such,) are the fuel of his anger, to be consumed by the fire of his jealousy;
the nation is weary, and its inhabitants, and the Lord is weary, because of these men:
and is this the ministry cried up by you as godly and pious?
etc. Are these the men that the nation must be forced
to maintain in their pride and idolatry?
Is this the ministry that must be encouraged?
Well, if these be the men,
and this the ministry which must be established and encouraged by you,
in so doing you shall never prosper,
but thereby gain the displeasure of the Almighty unto you,
to bring a curse upon all your doings, even because hereof; for I must tell you,
the hand of my Lord is against them; and whosoever shall seek to defend them,
shall not prosper in their doings, because their oppressions, cruelties, deceits,
and abominations, are nigh finished and fulfilled; wherefore take heed unto yourselves,
for this is my Master`'s advice unto you; let this ministry alone,
and join not yourselves to Baal, lest you perish,
neither take part with antichrist any longer,
neither be ye fighters against the Lamb and his kingdom; but free the nation,
and let all its inhabitants be freed, from the cruel tasks and yokes of such men,
and such a ministry as aforesaid; uphold it not against the Lord, for if you do,
you shall never be established, and this is from the mouth of my Lord unto you.

And, last of all, my Master hath a people in this nation, even a suffering people,
that have borne the burden of the cruelty and injustice, and wickedness,
both of rulers and teachers, who have, as it were, trodden them down,
and made them a very prey to their devouring mouths;
the very cry of their sufferings hath reached unto heaven,
and the very sound thereof your ears have heard; and this people are greatly beloved,
and my Lord will assuredly honour them,
and his hand shall be continued to preserve them
and defend them against all their enemies whatsoever;
and he doth reserve them to himself, and for a glorious work that he hath to do by them;
and he hath formed them for himself,
and they cannot join with any of the horns of the great beast,
neither can a place of honour pervert them from their perfect way; but my Lord,
he compasseth them about on every side, and hath kept them in the midst of trials,
reproaches, and sufferings, and covered them in the heat, and in the storm,
till his pleasure is to make further use of them.
They are his, and not their own; and they must fulfill his will, and none besides;
and they lie at rest in him, while mountains are overturned,
and while one potsherd of the earth breaks another;
and this must be even till the appointed time: and to say no more of them,
though much more might be said, they are had in remembrance before the Lord,
to do with them even for his own glory, and for the nation`'s perpetual good;
and to the authority of the Most High, through them, shall kings of the earth,
and nations of the world bow and tremble; wherefore, ye men, touch them not,
neither do ye afflict them, even as you hope to prosper; remember their cause,
and suffer it not always to be rejected, as it hath long been,
but keep yourselves free from the injustice and cruelty
of them that have gone before you,
who have been merciless, and oppressors of that people,
even till my Lord hath confounded them, and brought them into confusion;
for there is the weight of blood, tyranny, and oppression,
lying upon the nation in that people`'s cause,
and my Lord will revenge them in his season;
and though they are not weary of their sufferings,
but are in the patience which beareth all things, yet the nation can never be happy,
nor its government ever blessed, while this people are held in bondage;
and their sufferings are deeply considered of the Lord,
and the season thereof is expiring towards an end; and when this cometh to pass,
then woe unto the kingdom of antichrist, and to the whore and false prophet,
even when their strength is dried up,
by which they have made war against the Lamb and his followers: yea, woe unto them;
great fearfulness shall be upon all the world when
the king of that people reigns upon the earth,
and the time is at hand: blessed is the man that waiteth for it,
and blessed is he that is not offended in his coming,
but is prepared to receive him in his appearing,
which suddenly cometh upon all the world.

And thus I have told the Lord`'s present message unto you, which I received from him,
and thus far I am clear; and whether you accept it, or reject it,
my peace and reward is forever with him, who am a subject of his kingdom,
and a friend to this nation, however otherwise judged by ignorant men.

[.signed-section-signature]
E+++.+++ Burrough.

[.signed-section-context-close]
The Ninth month, 1659.

--

Now how soon after these sayings of Burrough,
"`Your estates shall not be spared from the spoiler, nor your necks from the axe;
your enemies shall charge treason upon you,
and if you seek to stop the Lord`'s work you shall
not cumber the earth very long,`" were fulfilled,
we shall see shortly.

About this time also he wrote several epistles to his friends,
wherein he so powerfully exhorted them to faithfulness and steadfastness,
that thereby he hath procured to himself a name that will never die;
as living still in the remembrance of thousands,
though he long ago went the way of all flesh,
having laid down his life in bonds for the testimony of Jesus,
as will be said in its due place.

There is also extant a piece of a letter written about this time to the cavaliers, which,
whether done by E. Burrough, or by George Fox the younger, or by George Bishop,
I cannot tell: but thus it speaks:

[.embedded-content-document.letter]
--

The very spirit of pride and oppression, and idolatry, is entered into them,
(viz. your enemies,) and now lives in them in as
high a measure as ever it lived amongst you;
and their iniquities are well nigh finished,
and the Lord will one way or other correct and reprove them;
and they shall be dealt with in like manner as they have dealt with you;
for they were no more than a rod in the hand of the Lord for a season,
and they must also be broken and cast into the fire;
and whether the Lord may ever make use of you to reprove them,
as he did of them to reprove you, this I determine not,
but leave it to him who can discover whatsoever he will, by what instrument he pleaseth.
It is true, you have made many attempts to be revenged upon them,
but you have not hitherto prospered; but could you be humbled,
and come into the meek Spirit of the Lord, then might you prosper;
hitherto the Lord hath always defeated you,
and bowed you down under a people as unworthy as others;
but their time will come to an end.
Submit therefore unto the will of the Lord in what is come to pass,
and seek not vengeance to yourselves, and then the Lord will avenge your cause;
for the iniquities of your adversaries are ripe.
And Charles Stuart must either be converted to God, and ruled by him,
or else he can never rightly rule for God in this nation; though this I believe,
it is not impossible but that he may be a rod upon them that once smote him:
and their oppressions and ambitions may receive a check through him.

--

Among several other eminent preachers,
Stephen Crisp was now also become a public minister of the word of God;
and it was about this time that he went to Scotland, to preach the gospel there,
and to edify the churches with his gift.

G+++.+++ Fox the younger, this year wrote an exhortation to the military officers,
and the army, showing them how they were departed from their first integrity,
and fallen into pride and wantonness.

G+++.+++ Fox the elder, about the Tenth month, was at Norwich, where a meeting being appointed,
and the mayor having got notice of it,
intended to have given out a warrant to apprehend him, but he having heard of this,
sent some of his friends to the mayor, to speak with him about it.
And his answer was, that he feared such a meeting would cause tumults in the town.
But being spoken to in a kind way, he behaved himself moderately,
and a large peaceable meeting was kept; to which, among others,
several priests also came, and among these was one Townsend, who stood up and cried,
"`Error, Blasphemy,`" etc.
G+++.+++ Fox desired him not to burden himself with that which he could not make good.
But he asserted it to be error and blasphemy,
that G. Fox had said that people must wait upon God by his power and Spirit,
and feel his presence when they did not speak words.
On this G. Fox asked him, whether the apostles and holy men of God,
did not hear God speak to them in their silence before they spake forth the Scriptures,
and before it was written?
He replied "`Yes,`" and confirmed it by saying plainly,
that David and the prophets did so.
Then G. Fox showed people how absurd it was, that Townsend,
had called such a practice error and blasphemy.
This so puzzled Townsend, that he said,
"`O this is not that George Fox I would speak withal; but this is a subtle man.`"
Now when some of the auditory called to the priest,
and bade him prove the blasphemy and error which he had charged G. Fox with,
he went away; and being afterwards spoken to by George Whitehead,
and Richard Hubberthorn, who were then also about Norwich,
he was soon confounded and brought down.

The committee of safety being now in power,
Edmund Ludlow continued to urge the restoring of the parliament; and general Monk,
who commanded the army in Scotland, aiming at the restoration of the king,
yet wrote to the speaker, Lenthal, that he would act for the parliament:
and so it was restored.

G+++.+++ Fox the younger, wrote to this parliament a letter, wherein he told them,
that their day was turned into darkness; and that the sun was gone down over them.
Yea, that the decree was gone out, and sealed against them, and it could not be recalled:
with many other remarkable expressions.
He had written at other times to the army, and to the parliament,
as did also Richard Hubberthorn, which to avoid prolixity, I pass by.

Let us now again take a view of the persecution in New England.
I have already made mention of Lawrence and Cassandra Southwick, and their son Josiah,
of whom more is to be said hereafter; but first I will speak of Daniel and Provided,
son and daughter of the said Lawrence and Cassandra.
These children seeing how unreasonably their honest parents and brothers were dealt with,
were so far from being deterred thereby,
that they rather felt themselves encouraged to follow their steps,
and not to frequent the assemblies of such a persecuting generation;
for which absence they were fined ten pounds,
though it was well known they had no estate,
their parents being already brought to poverty by their rapacious persecutors.
To get this money, the following order was issued in the general court at Boston.

[.embedded-content-document.legal]
--

Whereas Daniel Southwick, and Provided Southwick, son and daughter of Lawrence Southwick,
absenting themselves from the public ordinances,
have been fined by the courts of Salem and Ipswich, pretending they have no estates,
and resolving not to work, the court upon perusal of a law,
which was made upon the account of debts,
in answer to what should be done for the satisfaction of the fines, resolves,
that the treasurers of the several counties are,
and shall be fully impowered to sell the said persons to any of the English nation,
at Virginia, or Barbados, to answer the said fines, etc.

[.signed-section-signature]
Edward Rawson, _Secretary._

--

The subject of this order was answered effectually at large in print, by G. Bishop,
who showed the unreasonableness of this work very plainly from sacred writ;
as from Amos 2:6,
where the judgments of God are denounced against those who sold the righteous for silver,
and the poor for a pair of shoes; and from Lev. 25:42,
where the making the children of Israel bondmen, is expressly forbidden;
this being not lawful, but in the case of theft,
if the thief had nothing to make satisfaction with.
But to return to Daniel and Provided,
there wanted nothing but the execution of the said order against them.
Wherefore Edmund Butter, one of the treasurers, to get something of the booty,
sought out for passage, to send them to Barbados for sale;
but none were willing to take or carry them: and a certain master of a ship,
to put the thing off, pretended, that they would spoil all the ship`'s company.
To which Butter returned, "`No, you need not fear that,
for they are poor harmless creatures, and will not hurt any body.`"
"`Will they not so,`" replied the shipmaster:
"`and will you offer to make slaves of such harmless creatures?`"
Thus Butter, maugre his wicked intention, the winter being at hand, sent them home again,
to shift for themselves, till he could get a convenient opportunity to send them away.

It happened also in this year, that a girl, about eleven years old, named Patience Scot,
whose religious mother had been cruelly whipt by these people,
bore witness against their wicked persecution; which so incensed the persecutors,
that they sent her to prison: and the child having been examined,
spoke so well to the purpose, that she confounded her enemies; some of whom confessed,
that they had many children, who had been well educated,
and that it were well if they could say half so much for God, as she could for the devil.
But this child not being of years to be obnoxious to the law,
how wicked soever they were, it seems they could not resolve to proceed to banishment,
as they did with others.

All that hitherto I have said of the New England persecution, is but cursorily,
and only a very small part of those manifold whippings that were inflicted there;
besides the extortions of fines, which were exorbitant to a high degree;
as may appear by what was done to William Maston, at Hampton,
who was fined ten pounds for two books found in his house,
five pounds for not frequenting their church, and three pounds besides,
as a due to the priest: and he not being free in conscience to pay this fine,
had taken from him what amounted to more than twenty pounds.
I find also, that not long after this time,
above a thousand pounds was extorted from some,
only because they had separated themselves from the persecuting church:
and it seems they were deemed such as were shut out from the protection of the law;
insomuch that Thomas Prince, governor of Plymouth, did not stick to say,
that in his conscience the Quakers were such a people, that deserved to be destroyed,
they, their wives, and children, their houses and lands, without pity or mercy.
I find also that one Humphrey Norton at Newhaven, for being a Quaker, was whipt severely,
and burnt in the hand with the letter "`H`" to signify _heretic._

This cruelty of the English did also stir up the Dutch to persecution:
for without inquiring what kind of people the Quakers were,
they seemed ready to conclude them to be men of pernicious opinions,
since those of their own nation, who pretended to more purity than other Protestants,
did so severely persecute them.

It happened that one Robert Hodshone, being in the Dutch plantation at Hamstead,
had a meeting with some of his friends that were English, and lived there;
but as he was walking in an orchard, an officer came and took hold of him,
and brought him before one Gildersleave, an Englishman, and a magistrate there,
who committed him to prison, and rode to the Dutch governor to acquaint him therewith:
and coming back with a guard of musqueteers, the fiscal searched the prisoner,
and took away his knife, papers, and bible, and pinioned him, and kept him so all night,
and the next day.
And making inquiry after those that entertained him,
he took into custody two women on that occasion, one of whom had two small children,
the one yet sucking at her breast.
Then they got a cart and carried the women away in it,
and Robert was fastened to the hinder part of the cart, pinioned,
and so drawn through the woods in the night season, whereby he was much torn and abused.
And being come to New Amsterdam, (now New York,) he was loosed, and led by the rope,
with which he had been fastened to the cart, to the dungeon, being a filthy place,
full of vermin; and the two women were carried to another place.
Some time after he was examined, there being one captain Willet of Plymouth,
who had much incensed the governor against him, who before had been moderate.
The conclusion was, that a sentence was read in Dutch, to Robert, to this effect,
that he was to work two years at the wheelbarrow with a negro, or pay,
or cause to be paid, six hundred guilders.
To this he attempted to make his defence in a sober way, but was not suffered to speak,
and sent to the dungeon again; where no English were suffered to come to him.
After some days he was taken out, and pinioned,
and being set with his face towards the court chamber, his hat was taken off,
and another sentence read to him in Dutch, which he did not understand:
but that it displeased many of that nation, did appear by the shaking of their heads.
Then he was cast again into the dungeon, where he was kept some days.

At length, betimes in the morning, he was hauled out, and chained to a wheelbarrow,
and commanded to work: to which he answered, he was never brought up,
nor used to such a work.
Upon which they made a negro to take a pitched rope, nigh four inches about,
and to beat him; who did so, till Robert fell down.
Then they took him up again, and caused the negro to beat him with the said rope,
until he fell down the second time,
and it was believed that he received about one hundred blows.
Thus he was kept all that day in the heat of the sun, chained to the wheelbarrow;
and his body being much bruised and swelled with the blows, and he kept without food,
grew very faint, and sat upon the ground, with his mind retired to the Lord,
and resigned to his will, whereby he felt himself supported.
At night he was locked up again in the dungeon,
and the next morning he was chained again to the wheelbarrow,
and a sentinel set over him, that none might come so much as to speak with him.
On the third day he was had forth, and chained in like manner;
and no wonder that he still refused to work,
for besides the unreasonableness of requiring such
a servile work of him who had committed no evil,
he was not in a condition to perform it,
being made altogether unable by the cruel blows given him.
In this weak state he was brought before the governor, who demanded him to work,
otherwise he said, he should be whipt every day.
Robert asked him what law he had broken?
And called for his accusers, that he might know his transgression.
But instead of an answer he was chained to the wheelbarrow again, and threatened,
that if he spake to any one, he should be punished worse.
Yet he did not forbear to speak to some that came to him, so as he saw meet,
and thought convenient.
Then seeing they could not keep him silent, they put him into the dungeon again,
and kept him close there several days, and two nights; one day and a half of it,
without bread or water.

After this, he was brought very early in the morning, into a private room,
and stript to the waist, and hung up by his hands,
and a great log of wood tied to his feet, so that he could not turn his body;
and then a strong negro was set to whip him with rods, who laid many stripes upon him,
which cut his flesh very much.
Then he was let down again, and put into the dungeon as before,
and none suffered to come to him.
Two days after he was had forth again, and hung up as before,
and many more stripes were laid upon him by another negro.
He almost fainting, and not knowing but his life might be taken away,
desired that some English might be suffered to come to him: which was granted,
and an English woman came and washed his stripes,
finding him brought so low that she thought he would not live till the next morning.
And she telling this to her husband, it made such an impression upon him,
that he went to the fiscal and proffered him a fat ox,
to suffer Robert to be at his house until he was well again.
But the fiscal would not permit this, unless the whole fine was paid.
And though there were some that would willingly have paid the fine for him,
yet he could not consent to it; but within three days after he had thus been whipped,
he was made whole, and as strong as before, and was free to labour,
that he might not be burdensome to any.
Some others of those called Quakers,
(who came thither from the plantations in New England to enjoy liberty of conscience,
and whose names and sufferings I pass by for brevity`'s
sake,) met also with hard measure from the governor,
by the instigation of the aforesaid Captain Willet.
Robert now though guiltless, being kept like a slave to hard work,
it raised compassion in many, and the governor`'s sister,
who was much affected with his sufferings, became instrumental in obtaining his liberty;
for she so plied her brother, that he at length set him free without paying one penny,
or any body for him; by which the governor showed,
that though he had been too easily wrought upon to commit evil,
yet he was not come near to that height of malice as the New England persecutors;
who increased in their hard-heartedness, and became inured to cruelty,
insomuch that if any one amongst them would not give his vote for persecution,
he was counted unworthy to be a magistrate: as appears by a letter of one James Cudworth,
written some time before to one of his friends in Old England,
wherein I meet with these words:

[.embedded-content-document.letter]
--

As for the state and condition of things amongst us, it is sad.
The antichristian persecuting spirit is very active, and that in the powers of this world.
He that will not whip and lash, persecute,
and punish men that differ in matters of religion, must not sit on the bench,
nor sustain any office in the commonwealth.
Last election Mr. Hatherly and myself left the bench,
and myself was discharged of my captainship,
because I had entertained some of the Quakers at my house,
that thereby I might be the better acquainted with their principles.
I thought it better to do so, than with the blind world to censure, condemn, rail at,
and revile them, when they neither saw their persons,
nor knew any thing of their principles.
But the Quakers and myself cannot close in divers things;
and so I signified to the court I was no Quaker,
but must give my testimony against sundry things that they held,
as I had occasion and opportunity.
But withal, I told them, that as I was no Quaker, so I would be no persecutor.

--

Now shall I enter upon the narrative of their putting some to death, who died martyrs;
for this was yet wanting to complete the tragedy,
which it seems could not be done to the satisfaction of the actors,
without playing a murdering part.

The two first that sealed their testimony with their blood, were William Robinson,
merchant of London, and Marmaduke Stevenson, a countryman of Yorkshire.
These coming to Boston in the beginning of September,
were sent for by the court of assistants,
and there sentenced to banishment on pain of death.
This sentence was passed also on Mary Dyar, mentioned heretofore, and Nicholas Davis,
who were both at Boston.
But William Robinson, being looked upon as a teacher,
was also condemned to be whipt severely;
and the constable was commanded to get an able man to do it.
Then Robinson was brought into the street, and there stript;
and having his hands put through the holes of the carriage of a great gun,
where the jailer held him,
the executioner gave him twenty stripes with a three-fold cord whip.
Then he and the other prisoners were shortly released, and banished;
which that it was for no other reason but their being Quakers,
may appear by the following warrant:

[.embedded-content-document.legal]
--

You are required by these, presently to set at liberty William Robinson,
Marmaduke Stevenson, Mary Dyar, and Nicholas Davis,
who by an order of the court and council, had been imprisoned,
because it appeared by their own confession, words, and actions, that they are Quakers;
wherefore a sentence was pronounced against them,
to depart this jurisdiction on pain of death,
and that they must answer it at their peril, if they,
or any of them after the 14th of this present month, September,
are found within this jurisdiction, or any part thereof.

[.signed-section-signature]
Edward Rawson.

[.signed-section-context-close]
Boston, September 12, 1659.

--

Now though Mary Dyar and Nicholas Davis left that jurisdiction for that time,
yet Robinson and Stevenson, though they departed the town of Boston,
could not yet resolve, (not being free in mind,) to depart that jurisdiction,
though their lives were at stake.
And so they went to Salem,
and some place thereabout to visit and build up their friends in the faith.
But it was not long before they were taken, and put again into prison at Boston,
and chains locked to their right legs.
In the next month Mary Dyar returned also.
And as she stood before the prison, speaking with one Christopher Holder,
who was come thither to inquire for a ship bound for England, whither he intended to go,
she was also taken into custody.
Thus they had three persons, who, according to their sanguinary law,
had forfeited their lives.
And on the 20th of October, these three were brought into the court,
where John Endicot and others were assembled.
And being called to the bar, Endicot commanded the keeper to pull off their hats:
and then said, that they had made several laws to keep the Quakers from amongst them;
and neither whipping, nor imprisoning, nor cutting off ears,
nor banishing upon pain of death, would keep them from amongst them.
And further he said, that he or they desired not the death of any of them.
Yet notwithstanding, his following words without more ado, were, "`Give ear,
and hearken to your sentence of death.`"
W+++.+++ Robinson then desired that he might be permitted to read a paper,
giving an account of the reason why he had not departed that jurisdiction.
But Endicot would not suffer it to be read, and said in a rage, "`You shall not read it,
nor will the court hear it read.`"
Then Robinson laid it on the table.
He had written this paper the day before, and some of the contents were,
that he being in Rhode Island, the Lord had commanded him to go to Boston,
and to lay down his life there.
That he also had felt an assurance that his soul was to enter into everlasting peace,
and eternal rest.
That he durst not but obey, without inquiring further concerning it;
believing that it became him as a child, to show obedience to the Lord,
without any unwillingness.
That this was the cause, why after banishment on pain of death,
he stayed in their jurisdiction: and that now with sincerity of heart he could say,
Blessed be the Lord, the God of my life, who hath called me hereunto,
and counted me worthy to testify against wicked and unjust men, etc.
This paper being handed to Endicot, he read it to himself, and after he had done,
said to Robinson, "`You need not keep such ado to have it read;
for you spoke yesterday more than here is written.`"
Yet this was not so;
for it contained a circumstantial relation of the divine operations on his mind;
and that he was not come there in his own will, but in obedience to his Creator:
and that travelling in Rhode Island, on the 8th of the Eighth month,
he had been moved thereto from the Lord,
and therefore had submitted to his divine pleasure without murmuring.
W+++.+++ Robinson desired again that the paper might be read,
that so all that were present might hear it, it was denied him, and Endicot said,
"`W. Robinson hearken to your sentence of death;
you shall be had back to the place from whence you came,
and from thence to the place of execution,
to be hanged on the gallows till you are dead.`"
This sentence was not altogether unexpected to W. Robinson;
for it was four months now that he had believed this would be his share.

Robinson being taken away, M. Stevenson was called, and Endicot said to him,
"`If you have any thing to say, you may speak.`"
He knowing how they dealt with his companion, was silent,
though he had also written in prison a paper,
containing the cause of his being come there; but he kept it with him,
and found afterwards occasion to deliver it to somebody.
Then Endicot pronounced sentence of death against him, saying, "`M. Stevenson,
you shall be had to the place from whence you came, and from thence to the gallows,
and there be hanged till you are dead.`"
Whereupon M. Stevenson spoke thus: "`Give ear, ye magistrates, and all who are guilty;
for this the Lord hath said concerning you, and will perform his word upon you,
that the same day ye put his servants to death,
shall the day of your visitation pass over your heads,
and you shall be cursed forevermore.
The mouth of the Lord of hosts hath spoken it.
Therefore in love to you all, I exhort you to take warning before it be too late,
that so the curse may be removed.
For assuredly if you put us to death, you will bring innocent blood upon your own heads,
and swift destruction will come upon you.`"

After he had spoken this, he was taken away, and Mary Dyar was called:
to whom Endicot spoke thus: "`Mary Dyar, you shall go to the place from whence you came,
(to wit, the prison,) and from thence to the place of execution,
and be hanged there until you are dead.`"
To which she replied, "`The will of the Lord be done.`"
Then Endicot said, "`Take her away, marshal.`"
To which she returned, "`Yea, joyfully I go.`"
And in her going to the prison, she often uttered speeches of praise to the Lord; and,
being full of joy, she said to the marshal, he might let her alone,
for she would go to the prison without him.
To which he answered, "`I believe you, Mrs.
Dyar: but I must do what I am commanded.`"
Thus she was led to prison, where she was kept a week, with the two other,
her companions, that were also condemned to die.

The paper of Marmaduke Stevenson, mentioned before,
which he gave forth after he had received sentence of death, was thus:

[.embedded-content-document.paper]
--

In the beginning of the year 1655, I was at the plough, in the east parts of Yorkshire,
in Old England, near the place where my outward being was,
and as I walked after the plough,
I was filled with the love and presence of the living God,
which did ravish my heart when I felt it;
for it did increase and abound in me like a living stream,
so did the love and life of God run through me like precious ointment,
giving a pleasant smell, which made me to stand still; and as I stood a little still,
with my heart and mind stayed on the Lord,
the word of the Lord came to me in a still small voice, which I did hear perfectly,
saying to me,
in the secret of my heart and conscience,--I have ordained thee a prophet
unto the nations.--And at the hearing of the word of the Lord,
I was put to a stand, being that I was but a child for such a weighty matter.
So at the time appointed, Barbados was set before me,
unto which I was required of the Lord to go, and leave my dear and loving wife,
and tender children: for the Lord said unto me immediately by his Spirit,
that he would be as a husband to my wife, and as a father to my children,
and they should not want in my absence, for he would provide for them when I was gone.
And I believed that the Lord would perform what he had spoken,
because I was made willing to give up myself to his work and service,
to leave all and follow him, whose presence and life is with me,
where I rest in peace and quietness of spirit,
(with my dear brother,) under the shadow of his wings,
who hath made us willing to lay down our lives for his own name sake,
if unmerciful men be suffered to take them from us; and if they do,
we know we shall have peace and rest with the Lord forever in his holy habitation,
when they shall have torment night and day.
So, in obedience to the living God, I made preparation to pass to Barbados,
in the Fourth month, 1658.
So, after I had been some time on the said island in the service of God,
I heard that New England had made a law to put the servants of the living God to death,
if they returned after they were sentenced away, which did come near me at that time:
and as I considered the thing, and pondered it in my heart,
immediately came the word of the Lord unto me, saying,
"`Thou knowest not but that thou mayest go thither.`"
But I kept this word in my heart, and did not declare it to any until the time appointed.
So, after that, a vessel was made ready for Rhode Island, which I passed in.
So, after a little time that I had been there,
visiting the seed which the Lord hath blessed, the word of the Lord came unto me, saying,
"`Go to Boston with thy brother William Robinson.`"
And at his command I was obedient, and gave up myself to do his will,
that so his work and service may be accomplished: for he hath said unto me,
that he hath a great work for me to do; which is now come to pass:
and for yielding obedience to, and obeying the voice and command of, the ever-living God,
who created heaven and earth, and the fountains of waters, do I, with my brother,
suffer outward bonds near unto death, and this is given forth to be upon record,
that all people may know, who hear it, that we came not in our own wills,
but in the will of God.
Given forth by me, who am known to men by the name of

[.signed-section-signature]
Marmaduke Stevenson.

[.postscript]
====

But having a new name given me, which the world knows not of, written in the Book of Life.

====

[.signed-section-context-close]
Written in Boston prison, in the 8th Month, 1659.

--

[.offset]
Mary Dyar being returned to prison, wrote the following letter,
which she sent to the rulers of Boston.

[.embedded-content-document.letter]
--

[.letter-heading]
To the General Court in Boston.

Whereas I am by many charged with the guiltiness of my own blood;
if you mean in my coming to Boston, I am therein clear, and justified by the Lord,
in whose will I came, who will require my blood of you, be sure,
who have made a law to take away the lives of the innocent servants of God,
if they come among you, who are called by you, cursed Quakers; although I say,
and am a living witness for them and the Lord, that he hath blessed them,
and sent them unto you; therefore be not found fighters against God,
but let my counsel and request be accepted with you, to repeal all such laws,
that the Truth and servants of the Lord may have free passage among you,
and you be kept from shedding innocent blood,
which I know there are many among you would not do, if they knew it so to be;
nor can the enemy that stirreth you up thus to destroy his holy seed,
in any measure countervail the great damage that you will, by thus doing, procure.
Therefore seeing the Lord hath not hid it from me, it lieth upon me,
in love to your souls, thus to persuade you.
I have no self-ends the Lord knoweth; for if my life were freely granted by you,
it would not avail me, nor could I expect it of you,
so long as I should daily hear or see the sufferings of these people, my dear brethren,
and the seed with whom my life is bound up, as I have done these two years;
and now it is like to increase, even unto death, for no evil doing, but coming among you.
Was ever the like laws heard of among a people that profess Christ come in the flesh?
And have such no other weapons but such laws to fight against spiritual wickedness withal,
as you call it?
Woe is me for you!
Of whom take ye counsel?
Search with the light of Christ in you, and it will show you of whom,
as it hath done me and many more, who have been disobedient and deceived, as now ye are:
which light as ye come into, and obeying what is made manifest to you therein,
you will not repent that you were kept from shedding blood, though it were by a woman.
It is not mine own life I seek, (for I choose rather to suffer with the people of God,
than to enjoy the pleasures of Egypt,) but the life of the seed,
which I know the Lord hath blessed,
and therefore seeks the enemy thus vehemently to destroy the life thereof,
as in all ages he ever did.
O hearken not unto him, I beseech you, for the seed`'s sake, which is one and all,
and is dear in the sight of God, which they that touch, touch the apple of his eye,
and cannot escape his wrath; whereof I having felt,
cannot but persuade all men that I have to do withal,
especially you who name the name of Christ,
to depart from such iniquity as shedding blood, even of the saints of the Most High.
Therefore let my request have as much acceptance with you, if you be Christians,
as Esther`'s had with Ahasuerus,
whose relation is short of that that is between Christians;
and my request is the same that her`'s was: and he said not that he had made a law,
and it would be dishonourable for him to revoke it;
but when he understood that those people were so prized by her,
and so nearly concerned her, as in truth these are to me,
you may see what he did for her.
Therefore I leave these lines with you,
appealing to the faithful and true witness of God, which is one in all consciences,
before whom we must all appear; with whom I shall eternally rest,
in everlasting joy and peace, whether you will hear or forbear.
With him is my reward, with whom to live is my joy, and to die is my gain,
though I had not had your forty-eight hours warning,
for the preparation of the death of Mary Dyar.

And know this also,
that if through the enmity you shall declare yourselves worse than Ahasuerus,
and confirm your law, though it were but by taking away the life of one of us,
that the Lord will overthrow both your law and you,
by his righteous judgments and plagues poured justly upon you, who now,
whilst ye are warned thereof, and tenderly sought unto, may avoid the one,
by removing the other.
If you neither hear, nor obey the Lord, nor his servants,
yet will he send more of his servants among you, so that your end shall be frustrated,
that think to restrain them ye call cursed Quakers, from coming among you,
by any thing you can do to them.
Yea, verily, he hath a seed here among you, for whom we have suffered all this while,
and yet suffer; whom the Lord of the harvest will send forth more labourers to gather,
out of the mouths of the devourers of all sorts, into his fold,
where he will lead them into fresh pastures, even the paths of righteousness,
for his name`'s sake.
Oh, let none of you put this good day far from you,
which verily in the light of the Lord I see approaching,
even to many in and about Boston, which is the bitterest and darkest professing place,
and so to continue so long as you have done, that ever I heard of.
Let the time past, therefore, suffice,
for such a profession as brings forth such fruits as these laws are.
In love, and in the spirit of meekness, I again beseech you,
for I have no enmity to the persons of any; but you shall know,
that God will not be mocked; but what ye sow, that shall ye reap from him,
that will render to every one according to the deeds done in the body,
whether good or evil.
Even so be it, saith

[.signed-section-signature]
Mary Dyar.

[.signed-section-context-close]
A copy of this was given to the general court after
Mary Dyar had received sentence of death,
about the 8th or 9th month, 1659.

--

The day appointed to execute the bloody sentence, was the 27th of October,
when in the afternoon the condemned prisoners were
led to the gallows by the marshal Michaelson,
and captain James Oliver, with a band of about two hundred armed men,
besides many horsemen;
as if they were afraid that some of the people would have rescued the prisoners:
and that no actors on the stage might be wanting, the priest Wilson joined the company,
who, when the court deliberated how to deal with the Quakers, said, "`Hang them,
or else`" (drawing his finger athwart his throat,) as if he would have said,
"`Dispatch `'em this way.`"
Now the march began, and a drummer going next before the condemned,
the drums were beaten, especially when any of them attempted to speak.
Glorious signs of heavenly joy and gladness were
beheld in the countenances of these three persons,
who walked hand in hand, Mary being the middlemost, which made the marshal say to her,
who was pretty aged, and stricken in years,
"`Are not you ashamed to walk thus hand in hand between two young men?`"
"`No,`" replied she,
"`this is to me an hour of the greatest joy I could enjoy in this world.
No eye can see, nor ear can hear, no tongue can utter, and no heart can understand,
the sweet incomes, or influence, and the refreshings of the spirit of the Lord,
which now I feel.`"
Thus going along, W. Robinson said, "`This is your hour, and the power of darkness.`"
But presently the drums were beaten; yet shortly after the drummers leaving off beating,
Marmaduke Stevenson said, "`This is the day of your visitation,
wherein the Lord hath visited you.`"
More he spoke, but could not be understood, by reason of the drums being beaten again.
Yet they went on with great cheerfulness, as going to an everlasting wedding feast,
and rejoicing that the Lord had counted them worthy to suffer death for his name`'s sake.

When they were come near the gallows, the priest said in a taunting way to W. Robinson,
"`Shall such jacks as you come in before authority with their hats on?`"
To which Robinson replied, "`Mind you, mind you,
it is for the not putting off the hat we are put to death!`"
Now being come to the ladder, they took leave of each other with tender embraces,
and then Robinson went cheerfully up the ladder, and being got up, said to the people,
"`This is the day of your visitation, wherein the Lord hath visited you:
this is the day the Lord is risen in his mighty power,
to be avenged on all his adversaries.`"
He also signified, that he suffered not as an evil-doer:
and desired the spectators to mind the light that was in them; to wit,
the Light of Christ, of which he testified, and was now going to seal it with his blood.
This so incensed the envious priest, that he said, "`Hold thy tongue; be silent;
thou art going to die with a lie in thy mouth.`"
The rope being now about his neck, the executioner bound his hands and legs,
and tied his neckcloth about his face: which being done, Robinson said,
"`Now ye are made manifest;`" and the executioner being about turning him off, he said,
"`I suffer for Christ, in whom I live, and for whom I die.`"
He being turned off, Marmaduke Stevenson stepped up the ladder, and said,
"`Be it known unto all this day, that we suffer not as evil-doers,
but for conscience sake.`"
And when the hangman was about to turn him off, he said,
"`This day shall we be at rest with the Lord;`" and so he was turned off.

Mary Dyar seeing her companions hanging dead before her, also stepped up the ladder;
but after her coats were tied about her feet, the halter put about her neck,
and her face covered with a handkerchief, which the priest Wilson lent the hangman,
just as she was to be turned off, a cry was heard, "`Stop, for she is reprieved.`"
Her feet then being loosed, they bade her come down.
But she whose mind was already as it were in heaven, stood still, and said,
she was there willing to suffer as her brethren did,
unless they would annul their wicked law.
Little heed was given to what she said, but they pulled her down,
and the marshal and others taking her by the arms, carried her to prison again.
That she thus was freed from the gallows, this time, was at the intercession of her son,
to whom it seems they could not then resolve to deny that favour.
She, now having heard why she was reprieved, wrote the next day,
being the 28th of October, the following letter to the court.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
The 28th of the Eighth month, 1659.

Once more to the general court assembled in Boston, speaks Mary Dyar, even as before.
My life is not accepted, neither availeth me,
in comparison of the lives and liberty of the Truth, and servants of the living God,
for which in the bowels of love and meekness I sought you: yet, nevertheless,
with wicked hands have you put two of them to death, which makes me to feel,
that the mercies of the wicked are cruelty.
I rather choose to die than to live, as from you, as guilty of their innocent blood:
therefore seeing my request is hindered, I leave you to the righteous Judge,
and searcher of all hearts, who,
with the pure measure of light he hath given to every man to profit withal,
will in his due time let you see whose servants you are,
and of whom you have taken counsel, which I desire you to search into:
but all his counsel hath been slighted, and you would none of his reproofs.
Read your portion, Prov. 1:24 to 32. For verily the night cometh on you apace,
wherein no man can work, in which you shall assuredly fall to your own master.
In obedience to the Lord, whom I serve with my spirit, and pity to your souls,
which you neither know nor pity, I can do no less than once more to warn you,
to put away the evil of your doings; and kiss the Son, the light in you,
before his wrath be kindled in you; for where it is,
nothing without you can help or deliver you out of his hand at all;
and if these things be not so, then say,
there hath been no prophet from the Lord sent amongst you; though we be nothing,
yet it is his pleasure, by things that are not, to bring to nought things that are.

When I heard your last order read, it was a disturbance unto me,
that was so freely offering up my life to him that gave it me,
and sent me hither so to do, which obedience being his own work,
he gloriously accompanied with his presence, and peace, and love in me,
in which I rested from my labour; till by your order and the people,
I was so far disturbed, that I could not retain any more of the words thereof,
than that I should return to prison, and there remain forty and eight hours;
to which I submitted, finding nothing from the Lord to the contrary,
that I may know what his pleasure and counsel is concerning me, on whom I wait therefore,
for he is my life, and the length of my days; and as I said before,
I came at his command, and go at his command.

[.signed-section-signature]
Mary Dyar.

--

The magistrates now perceiving that the putting William
Robinson and Marmaduke Stevenson to death,
caused great discontent among the people, resolved to send away Mary Dyar,
thereby to calm their minds a little.
And so she was put on horseback,
and by four horsemen conveyed fifteen miles towards Rhode Island,
where she was left with a horse and a man, to be conveyed the rest of the way:
which she soon sent back, and so repaired home.
By the style of her letters, and her undaunted carriage,
it appears that she had indeed some extraordinary qualities; I find also,
that she was of a comely and grave countenance, of a good family and estate,
and a mother of several children: but her husband it seems was of another persuasion.

Whilst I now leave her at home, I am to say that one John Chamberlain,
an inhabitant of Boston, having seen the execution of W. Robinson and M. Stevenson,
was so reached by their pious speeches, that he received the doctrine of the Truth,
for which they died: but his visiting those in prison was so ill resented,
that afterwards he was whipped several times severely; as was also Edward Wharton,
an inhabitant of Salem:
who having said that the guilt of Robinson and Stevenson`'s blood was so great and heavy,
that he was not able to bear it, was, for this his pretended sauciness,
whipped with twenty lashes, and fined twenty pounds.

But before I quite leave the persons that were hanged, I must say, that being dead,
their countenances still looked fresh;
(for the terror of death had not seized them.) But being cut down,
they were very barbarously used, none taking hold of their bodies:
which so fell down on the ground, that thereby the scull of W. Robinson was broken:
and even their shirts were ripped off with a knife,
and their naked bodies cast into a hole which was digged, without any covering.
And when some of their friends would have laid their bodies into coffins,
it was denied them.
Neither would they suffer the place where the bodies were cast, to be fenced with pales,
lest ravenous beasts might prey upon them.

When the people returned from the execution, many seemed sad and heavy;
and coming to the drawbridge, one end of it fell upon some, and several were hurt,
especially a wicked woman, who had reviled the said two persons at their death;
but now she was so bruised, that her flesh rotted from her bones,
which made such a noisome stink, that people could not endure to be with her:
in which miserable condition she remained till she died.
But the magistrates, instead of taking notice of this, grew more hardened;
and priest Wilson did not stick to make a ballad on the executed.

Now I return again to Mary Dyar, who being come to Rhode Island,
went from thence to Long Island, where she stayed the most part of the winter:
and then coming home again, she was moved to return to the bloody town of Boston,
whither she came on the 21st of the Third month, 1660,
and on the 31st she was sent for by the general court.
Being come, the governor, John Endicot, said,
"`Are you the same Mary Dyar that was here before?`"
And it seems he was preparing an evasion for her,
there having been another of that name returned from Old England.
But she was so far from disguising, that she answered undauntedly,
"`I am the same Mary Dyar that was here the last general court.`"
Then Endicot said, "`You will own yourself a Quaker, will you not?`"
To which Mary Dyar said, "`I own myself to be reproachfully called so.`"
Then the jailer, (who would also say something,) said, "`She is a vagabond.`"
And Endicot said, the sentence was past upon her the last general court,
and now likewise: "`You must return to the prison,
and there remain till tomorrow at nine o`'clock;
then from thence you must go to the gallows, and there be hanged till you are dead.`"
To which Mary Dyar said, "`This is no more than what thou saidst before.`"
And Endicot returned, "`But now it is to be executed;
therefore prepare yourself tomorrow at nine o`'clock.`"
She then spoke thus: "`I came in obedience to the will of God the last general court,
desiring you to repeal your unrighteous laws of banishment on pain of death;
and that same is my work now, and earnest request; although I told you,
that if you refused to repeal them,
the Lord would send others of his servants to witness against them.`"
Hereupon Endicot asked her, whether she was a prophetess?
And she answered, "`she spoke the words that the Lord spoke in her;
and now the thing was come to pass.`"
And beginning to speak of her call, Endicot cried, "`Away with her; away with her.`"
So she was brought to the prison house where she was before,
and kept close shut up until the next day.

About the appointed time the marshal Michaelson came, and called her to come hastily;
and coming into the room where she was, she desired him to stay a little;
and speaking mildly, said, she should be ready presently.
But he being of a rough temper, said he could not wait upon her,
but she should now wait upon him.
One Margaret Smith, her companion, being grieved to see such hard-heartedness,
spoke something against their unjust laws and proceedings; to which he said,
"`You shall have your share of the same.`"
Then Mary Dyar was brought forth, and with a band of soldiers led through the town,
the drums being beaten before and behind her, and so continued,
that none might hear her speak all the way to the place of execution,
which was about a mile.
With this guard she came to the gallows, and being gone up the ladder, some said to her,
that if she would return, she might come down and save her life.
To which she replied, "`Nay, I cannot, for in obedience to the will of the Lord I came,
and in his will I abide faithful to the death.`"
Then captain John Webb said, that she had been there before,
and had the sentence of banishment upon pain of death,
and had broken the law in coming again now;
and therefore she was guilty of her own blood.
To which she returned, "`Nay, I came to keep blood-guiltiness from you,
desiring you to repeal the unrighteous and unjust law of banishment upon pain of death,
made against the innocent servants of the Lord;
therefore my blood will be required at your hands, who willfully do it:
but for those that do it in the simplicity of their hearts,
I desire the Lord to forgive them.
I came to do the will of my Father, and in obedience to his will, I stand even to death.`"
Then priest Wilson said, "`Mary Dyar, O repent, O repent, and be not so deluded,
and carried away by the deceit of the devil.`"
To this Mary Dyar answered, "`Nay, man, I am not now to repent.`"
And being asked by some, whether she would have the elders pray for her, she said,
"`I know never an elder here.`"
Being further asked, whether she would have any of the people to pray for her?
She answered, she desired the prayers of all the people of God.
Thereupon some scoffingly said, "`It may be she thinks there is none here.`"
She looking about, said, "`I know but few here.`"
Then they spoke to her again, that one of the elders might pray for her.
To which she replied, "`Nay, first a child, then a young man, then a strong man,
before an elder in Christ Jesus.`"
After this she was charged with something which was not understood what it was,
but she seemed to hear it; for she said, "`It is false, it is false;
I never spoke those words.`"
Then one mentioned that she should have said, she had been in paradise.
To which she answered, "`Yea, I have been in paradise several days.`"
And more she spoke of the eternal happiness into which she was now to enter.
In this well-disposed condition she was turned off, and died a martyr of Christ,
being twice led to death, which the first time she expected with undaunted courage,
and now suffered with Christian fortitude.

Thus this honest, valiant woman finished her days:
but so hardened were these persecutors, that one of the court said scoffingly,
"`She did hang as a flag for others to take example by.`"
And putting to death for religion did not yet cease, as will be related hereafter:
but first I will take a turn again to Old England, where there was now great division,
and a revolution in the state.
