== Chapter XIV.

=== 1662-1664.

[.chapter-synopsis]
* Sickness and death of E. Burrough
* Testimony of F. Howgill concerning E. Burrough Sickness and death of Wm. Ames
* Letter of G. Fox on the death of E. Burrough
* Geo. Fox answers the question, '`Who made the devil?`"
* Fanatic hunting
* Awful death of Colonel Robinson
* Geo. Fox and Colonel Kirby
* Arrest of G. Fox
* Long examination
* Cruel persecution at Colchester
* Giles Barnardiston
* Proceedings against Friends at Worcester
* Narrative of the change of Thos. Lurting from a fighting Sailor to a peaceful Quaker
* Turkish Pirates
* Quaker Slaves at Algiers
* The Author`'s Mother visits England
* Account of Stephen Crisp
* Muggleton and Reeves
* Case of Oliver Atherton

Now I come also to the glorious exit of E. Burrough, that valiant hero,
of whom mention hath often been made in this history.
For several years he had been very much in London,
and there preached the gospel with piercing and powerful declarations.
And that city was so near to him, that oftentimes, when persecution grew hot,
he said to Francis Howgill, his bosom friend, '`I can freely go to the city of London,
and lay down my life for a testimony to that Truth,
which I have declared through the power and Spirit of God.`'
Being in this year at Bristol, and thereabouts, and moved to return to London,
he said to many of his friends, when he took his leave of them,
that he did not know he should see their faces any more;
and therefore he exhorted them to faithfulness and steadfastness,
in that wherein they had found rest for their souls.
And to some he said, '`I am now going up to the city of London again,
to lay down my life for the gospel, and suffer amongst Friends in that place.`'

Not long after, coming to London,
and preaching in the meetinghouse called the Bull and Mouth,
he was violently pulled down by some soldiers, and had before alderman Richard Brown,
and committed to Newgate.
Several weeks afterwards, being brought to the sessions-house in the Old Bailey,
he was fined by the court twenty marks, and to lie in prison till payment.
But judging this unreasonable in a high degree,
he could not bend thereto for conscience-sake.
He was kept there in prison about eight months, with six or seven score prisoners beside,
upon the same account.
But they being so crowded, that for want of room their natures were suffocated,
many grew sick and died, of which number he was one.
And though a special order from the king, was sent to the sheriffs of London,
for his and some other prisoners release,
yet such was the enmity of some of the city magistrates, especially Brown,
that they did what was in their power to prevent the execution of the said order.
And thus E. Burrough continued prisoner, though his sickness increased.
During the time of his weakness, he was very fervent in prayer,
as well for his friends as for himself;
and many consolatory and glorious expressions proceeded from his mouth.
Once he was heard to say,
'`I have had the testimony of the Lord`'s love unto me from my youth: and my heart, O Lord,
hath been given up to do thy will.
I have preached the gospel freely in this city,
and have often given up my life for the gospel`'s sake; and now, O Lord,
rip open my heart, and see if it be not right before thee.`'
Another time he said, '`There is no iniquity lies at my door;
but the presence of the Lord is with me, and his life I feel justifies me.`'
Another day he was thus heard in prayer to God,
'`Thou hast loved me when I was in the womb; and I have loved thee from my cradle:
and from my youth unto this day; and have served thee faithfully in my generation.`'
And to his friends that were about him, he said, '`Live in love and peace,
and love one another.`'
And at another time he said,
"`The Lord taketh the righteous from the evil to come.`"
And praying for his enemies and persecutors,
he said, '`Lord, forgive Richard Brown, if he maybe forgiven.`'
And being sensible that death was approaching, he said,
'`Though this body of clay must turn to dust,
yet I have a testimony that I have served God in my generation;
and that spirit which hath lived and acted, and ruled in me,
shall yet break forth in thousands.`'
The morning before he departed this life,
(which was about the latter end of this year,) he said,
'`Now my soul and spirit is centered into its own being with God;
and this form of person must return from whence it was taken.`'
And after a little season he gave up the ghost.
This was the exit of E. Burrough, who, in his flourishing years,
viz. about the age of eight and twenty; in an unmarried state,
changed this mortal life for an incorruptible,
and whose youthful summer flower was cut down in the winter season,
after he had very zealously preached the gospel about ten years.

About the 19th year of his age, he first came to London with a public testimony,
and continued almost eight years together to preach the word of God in that city,
with great success; so that many came to be convinced,
and great addition was made to the church there.
In his youth he surpassed others of his age in knowledge; and though G. Croese,
who wrote the pretended history of the Quakers, calls him a rustic fellow,
yet he was no more such than the said author himself, who is a country preacher:
for he was well educated and instructed in that learning which the place of his nativity,
viz. the barony of Kendal in Westmoreland, afforded.
Insomuch, that though he was not skillful in languages,
yet he had the tongue of the learned; and in his public ministry was very fluent,
and elegant in speech, even according to the judgment of learned men.

His enemies now began to rejoice,
for they seemed to imagine that the progress of that doctrine,
which he so powerfully and successfully had preached,
by his decease would have been stopped or retarded?
but they made a wrong reckoning.
Francis Howgill then gave forth a kind of _epicedium_
(i.e. lamentation) which though in prose,
yet was not void of poetical expressions, and was as follows.

[.embedded-content-document.testimony]
--

Shall days, or months, or years, wear out thy name, as though thou hadst no being?
Oh nay!
Shall not thy noble and valiant acts,
and mighty works which thou hast wrought through
the power of him that separated thee from the womb,
live in generations to come?
O yes!
The children that are yet unborn, shall have thee in their mouths,
and thy works shall testify of thee in generations, who yet have not a being,
and shall count thee blessed.
Did thy life go out as the snuff of a candle?
O nay!
Thou hast penetrated the hearts of many,
and the memorial of the just shall live forever;
and be had in renown among the children of men:
for thou hast turned many to righteousness,
and shall shine as a star of God in the firmament of God`'s power, forever and ever;
and they that are in that, shall see thee there, and enjoy thee there,
though thou be gone away hence, and can no more be seen in mutability;
yet thy life and thy spirit shall run parallel with immortality.
Oh Edward Burrough!
I cannot but mourn for thee, yet not as one without hope or faith,
knowing and having a perfect testimony of thy well-being in my heart,
by the Spirit of the Lord; yet thy absence is great,
and years to come shall know the want of thee.
Shall I not lament as David did for a worse man than thee, even for Abner;
when in wrath he perished by the hand of Joab, without any just cause,
though he was a valiant man?
David lamented over Abner, and said, died Abner as a fool dies! (Oh nay!
He was betrayed of his life.) Even so hast thou been
bereaved of thy life by the hand of the oppressor,
whose habitations are full of cruelty.
Oh my soul, come not thou within their secret,
for thy blood shall be required at the hands of them who thirsted after thy life;
and it shall cry as Abel`'s who was in the faith; even so wert thou,
it shall weigh as a ponderous millstone upon their necks, and shall crush them under,
and be as a worm that gnaws, and shall not die.
When I think upon thee, I am melted into tears of true sorrow;
and because of the want that the inheritance of the Lord hath of thee,
my substance is even as dissolved.
Shall I not say as David did of Saul and Jonathan, when they were slain in mount Gilboa,
the beauty of Israel is slain upon the high places:
even so wast thou stifled in nasty holes, and prisons,
and many more who were precious in the eyes of the Lord:
and surely precious wast thou to me, oh dear Edward, I am distressed for thee my brother,
very pleasant hast thou been to me, and my love to thee was wonderful,
passing the love of woman: Oh thou whose bow never turned back,
nor sword empty from the blood of the slain, from the slaughter of the mighty;
who made nations and multitudes shake with the word of life in thy mouth,
and wast very dreadful to the enemies of the Lord; for thou didst cut like a razor,
and yet to the seed of God brought forth, thy words dropped like oil,
and thy lips as the honeycomb.
Thou shalt be recorded amongst the valiants of Israel, who attained to the first degree,
through the power of the Lord, that wrought mightily in thee in thy day,
and wast worthy of double honor, because of thy works.
Thou wast expert to handle thy weapon, and by thee the mighty have fallen,
and the slain of the Lord have been many;
many have been pricked to the heart through the power of the word of life;
and coals of fire from thy life came forth of thy mouth, that in many a thicket,
and among many briers and thorns it came to be kindled,
and did devour much stubble that cumbered the ground, and stained the earth.
Oh how certain a sound did thy trumpet give!
And how great an alarm didst thou give in thy day,
that made the host of the uncircumcised greatly distressed!
What man so valiant, though as Goliath of Gath,
would not thy valor have encountered with, while many despised thy youth?
And how have I seen thee with thy sling and thy stone,
(despised weapons to war with,) wound the mighty!
And that which hath seemed contemptible to the dragon`'s party,
even as the jaw bone of an ass, with it thou hast slain the Philistines heaps upon heaps,
as Samson.
Thou hast put thy hand to the hammer of the Lord,
and hast often fastened nails in the heads of the Lamb`'s enemies, as Jael did to Sisera;
and many a rough stone hast thou polished and squared,
and made it fit for the buildings of God;
and much knotty wood hast thou hewed in thy day,
which was not fit for the building of God`'s house.
Oh thou prophet of the Lord, thou shall forever be recorded in the Lamb`'s book of life,
among the Lord`'s worthies, who have followed the Lamb through great tribulations,
as many can witness for thee from the beginning; and at last hast overcome,
and been found worthy to stand with the Lamb upon Mount Zion, the hill of God;
as I have often seen thee, and thy heart well tuned as a harp, to praise the Lord,
and to sound forth his great salvation;
which many a time hath made glad the hearts of them that did believe,
and strengthened their faith and hope.
Well, thou art at rest, and bound up in the bundle of life;
and I know tears were wiped away from thy eyes,
because there was no cause of sorrow in thee:
for I know thou witnessed the old things done away, and there was no curse,
but blessings were poured upon thy head as rain, and peace as a mighty shower,
and trouble was far from thy dwelling; though in the outward man trouble on every side,
and hast had a greater share in that, for the gospel-sake, (though a youth,) in thy time,
than many besides: but now thou art freed from that,
and hast obtained a name through faith, with the saints in light.
Well, hadst thou more to give up than thy life for the name of Jesus in this world?
Nay: and to seal the testimony committed unto thee with thy blood,
as thou hast often said in thy day,
which shall remain as a crown upon thee forever and ever.
And now thou art freed from the temptations of him who had the power of death;
and from thy outward enemies, who hated thee because of the love that dwelt in thee;
and remains at the right hand of God,
where there is joy and pleasure forevermore in the everlasting light;
which thou hast often testified unto, according to the word of prophecy in thy heart,
which was given unto thee by the Holy Ghost; and art at rest in the perfection thereof,
in the beauty of holiness; yet thy life and thy spirit I feel as present,
and have unity with it, and in it, beyond all created and visible things,
which are subject to mutation and change; and thy life shall enter into others,
to testify unto the same Truth, which is from everlasting to everlasting;
for God hath raised, and will raise up children unto Abraham,
of them that have been as dead stones; his power is Almighty,
great in his people in the midst of their enemies.

--

With these sublime expressions F. Howgill lamented his endeared friend E. Borrough.

In the latter end of this year, William Ames also deceased at Amsterdam,
being come from England in a weak condition,
for he had suffered so much hardship in Bridewell, London,
that his health was much impaired when he came into Holland.
In his sickness, which was a lingering disease, he was told,
that among the Baptists and Collegians, it was said of him,
that he had changed his judgment, and was grieved for having judged them wrongfully.
But to this he said, '`It was not so; but that he still judged their way of worship,
especially their disputations and will worship, to be out of the way of the Lord.`'
And in this belief he died in peace.

In his youth he was of a cheerful temper, and a lover of such company;
but being in that condition often disquieted in his mind,
he became a close follower of the priests and teachers,
and exercised himself diligently in reading the holy scriptures, which,
though good in itself, yet did not bring him to true peace with God;
but being of a quick understanding, he could talk much out of them, insomuch,
that entering into society with the Baptists, he became a teacher among them.
Now, though he was more precise, and endeavored to avoid the committing of sins,
yet he found that root from whence they sprang remained alive in him;
for when he met with something that was contrary to his own will, or mind,
anger soon prevailed: nevertheless, in that state he would speak of justification,
sanctification, and cleansing by the blood of Christ,
though he himself was not come to that pure washing.
In this state he perceived that he was no true member of Christ,
because regeneration was still wanting.
Thus he saw that a high profession would not avail,
and that something more was required to obtain a happy state; but as yet,
he knew not what it was that thus disquieted him; though sometimes,
on the committing of any sin, he felt something that struck him with terror.
At length it pleased the Lord, that hearing one of the Quakers, so called, preach,
that that which convinces man of sin, was the light of Christ,
which enlightens every man coming into the world, this doctrine entered so deep with him,
that he embraced it as wholesome;
and thus walking with great circumspection and fear before the Lord,
he found that by giving diligent heed to that which
inwardly reproved and condemned him from evil,
he came to be delivered therefrom, and to witness sanctification.
And thus advancing in godliness he himself became a zealous preacher of that doctrine,
which had struck him so to the heart.
He was indeed a zealous man, and though some were ready to think him too zealous,
yet he was discreet; and I know that he was condescending in indifferent matters,
thinking that there were customs, which though not followed in one country,
were yet tolerable in another.
He was also generous, and lest he might seem to be burdensome to any,
he rather choose to work with his hands.

Now I return again to the occurrences of G. Fox, whom we left at London, where,
having spent some time, he went about the beginning of the year 1663, to Norwich,
and from thence to Cambridgeshire, where he heard of E. Burrough`'s decease, and,
being sensible how great a grief this loss would be to his friends,
wrote the following lines to them,

[.embedded-content-document.letter]
--

Friends, be still and quiet in your own conditions, and settled in the seed of God,
that doth not change; that in that ye may feel dear E. B. among you, in the seed,
in which, and by which, he begot you to God, with whom he is;
and that in the seed ye may all see and feel him,
in which is the unity with him in the life;
and to enjoy him in the life that doth not change, which is invisible.

[.signed-section-signature]
G+++.+++ F.

--

G+++.+++ Fox afterwards traveling through several places, came again to London,
where having visited his friends in their meetings, which were numerous,
he travelled with Thomas Briggs into Kent, and coming to Tenterden,
they had a meeting there,
where many came and were convinced of the Truth that was declared.
But when he intended to do-part with his companion, he saw a captain,
and a company of soldiers, with muskets and lighted matches;
and some of these coming to them said, they must come to their captain.
And when they were brought before him, he asked, where was G. Fox?
Which was he?
To which G. Fox answered, '`I am the man.`'
The captain being somewhat surprised, said,
'`I will secure you among the soldiers:`' yet he carried himself civilly,
and said some time after, '`You must go along with me to the town.`'
Where being come, he brought G. Fox and T. Briggs, with some more of their friends,
to an inn, which was the jailer`'s house.
And after a while the mayor of the town, with the said captain and the lieutenant,
who were justices, came and examined G. Fox, asking,
why he came thither to make a disturbance?
G+++.+++ Fox told them, he did not come to make a disturbance, neither had he made any there.
They then said, there was a law, which was against the Quakers`' meetings,
made only against them.
G+++.+++ Fox told them he knew no such law.
Then they produced the act which was made against Quakers and others.
G+++.+++ Fox seeing it, told them,
that law was against such as were a terror to the king`'s subjects, and were enemies,
and held principles dangerous to the government;
and therefore it was not against his friends, for they held truth,
and their principles were not dangerous to the government,
and their meetings were peaceable, as was well known.
Now it was not without good reason that George said, he knew no such law;
since they had said, there was a law made only against the Quakers`' meetings:
whereas the act had the appearance of being made against plotters,
and enemies to the king, which certainly the Quakers were not.
Yet it was said to G. Fox he was an enemy to the King; but this he denied, and told them,
how he had once been cast into Derby dungeon, about the time of Worcester fight,
because he would not take up arms against the king;
and how afterwards he had been sent up to London by colonel Hacker,
as a plotter to bring in king Charles,
and that he was kept prisoner at London till he was set at liberty by Oliver Cromwell.
They asked him then, whether he had been imprisoned in the time of the insurrection?
And he said '`Yes,`' but that he was released by the king`'s own command.
At length they demanded bond for his appearance at the sessions,
and would have had him to promise to come thither no more.
But he refused the one as well as the other.
Yet they behaved themselves moderately, and told him, and Thomas Briggs, and the others,
'`Ye shall see we are civil to you;
for it is the mayor`'s pleasure you should all be set at liberty.`'
To which G. Fox returned, their civility was noble: and so they parted;
and he passed on to many places, where he had singular occurrences,
and though wiles were laid for him,
yet sometimes he escaped the hands of his persecuting enemies.

Coming into Cornwall he found there one Joseph Hellen, and George Bewly,
who though they professed Truth,
yet had suffered themselves to be seduced by Blanch Pope, a ranting woman,
who had ensnared them chiefly by asking, '`Who made the devil, did not God?`'
This silly question, which Hellen and Bewly were at a loss to answer,
they propounded to G. Fox, and he answered it with, '`No;
for,`' said he,`' all that God made was good, and was blest, but so was not the devil:
he was called a serpent, before he was called a devil and an adversary;
and afterward he was called a dragon, because he was a destroyer.
The devil abode not in the truth, and by departing from the truth he became a devil.
Now there is no promise of God to the devil, that ever he shall return into truth again;
but to man and woman, who have been deceived by him, the promise of God is,
that the seed of the woman shall bruise the serpent`'s head,
and break his power and strength to pieces.`'
With this answer, G. Fox gave satisfaction to his friends; but Hellen was so poisoned,
and run out, that they denied him;
but Bewly was recovered from his fault by sincere repentance.

G+++.+++ Fox, having performed his service there, went to Helston near Falmouth,
where he had a large meeting, at which many were convinced;
for he opened to the auditory, the state of the church in the primitive times,
and the state of the church in the wilderness,
as also the state of the false church that was got up since:
next he showed that the everlasting gospel was now preached again,
over the head of the whore, beast, antichrist, and the false prophets,
which were got up since the apostles`' days;
and that now the everlasting gospel was received and receiving,
which brought life and immortality to light.
And this sermon was of such effect, that the people generally confessed,
it was the everlasting Truth that had been declared there that day.

G+++.+++ Fox passing on, came at length to the Land`'s End,
where there was an assembly of his friends, and also a fisherman, call Nicholas Jose,
who preached among them,
having three years before been convinced there by the ministry of G. Fox.

Whilst in these parts, there happened a very dismal and dreadful case.

One colonel Robinson was, since the king came in, made justice of the peace;
and became a cruel persecutor of those called Quakers, of whom he sent many to prison;
and hearing that some liberty was allowed them, by the favor of the jailer,
to come home sometimes, to visit their wives and children,
he made complaint thereof to the judge at the assizes, against the jailer;
who thereupon was fined a hundred marks by judge Keeling.
Not long after the assizes, Robinson sent to a neighboring justice,
desiring he would go with him a fanatic hunting,
(meaning the disturbing of Quakers`' meetings.) On
the day that he intended thus to go a hunting,
he sent his man about with his horses, and walked himself to a tenement that he had,
where his cows and dairy were kept, and where his servants were then milking.
Being come there, he asked for his bull, and the maids said,
they had shut him into the field, because he was unruly amongst the kine.
He then going into the field,
and having formerly accustomed himself to play with the bull,
he began to fence at him with his staff, as he used to do; but the bull snuffing,
went a little back, and then ran fiercely at him, and struck his horn into his thigh,
and lifting him upon his horn, threw him over his back,
and tore up his thigh to his belly; and when he came to the ground, he broke his leg,
and the bull then gored him again with his horns, and roared, and licked up his blood.
One of the maid servants hearing her master cry out, came running into the field,
and took the bull by the horns to pull him off; but he, without hurting her,
gently put her by with his horns, and still fell to goring him, and licking up his blood.
Then she ran and got some workmen that were not far off, to come and rescue her master;
but they could not at all beat off the bull,
till they brought mastiff dogs to set on him; and then the bull fled.
His sister having notice of his disaster, came and said, '`Alack, brother,
what a heavy judgment is this!`' And he answered, '`Ah, sister,
it is a heavy judgment indeed: pray let the bull be killed,
and the flesh given to the poor.`'
So he was taken up, and carried home, but so grievously wounded, that he died soon after;
and the bull was become so fierce, that they were forced to kill him by shooting.
This was the issue of Robinson`'s mischievous intent to go a fanatic hunting.
I remember that in my youth I heard with astonishment
the relation of this accident from William Caton,
who by a letter from England had received intelligence of it;
for the thing was so remarkable, that the tidings of it were soon spread afar off.

Now I return to G. Fox, who from Cornwall travelled to Bristol, and so into Wales,
from whence passing through Warwickshire and Derbyshire, he came to York.
Here he heard of a plot,
which made him write a paper to his friends wherein he admonished them to be cautious,
and not at all to meddle with such bustlings.
And traveling towards Lancashire, he came to Swarthmore, where they told him,
that colonel Kirby had sent his lieutenant thither to search for him,
and that he had searched trunks and chests.
G+++.+++ Fox having heard this, the next day went to Kirby hall, where the said colonel lived;
and being come to him, he told him,`'I am come to visit thee,
understanding that thou wouldst have seen me,
and now I would fain know what thou hast to say to me,
and whether thou hast any thing against me.`'
The colonel who did not expect such a visit, and being then to go up to London,
to the parliament, said before alf the company,
'`as I am a gentleman I have nothing against you: but Mrs.
Fell must not keep great meetings at her house; for they meet contrary to the act.`'
G+++.+++ Fox told him, '`That act does not take hold on us,
but on such as meet to plot and contrive, and to raise insurrections against the king;
and we are none of those, but are a peaceable people.`'
After some words more, the colonel took G. Fox by the hand, and said,
he had nothing against him; and others said, he was a deserving man.

Then G. Fox parted, and returned to Swarthmore,
and shortly after he heard there had been a private meeting
of the justices and deputy lieutenants at Houlker-hall,
where justice Preston lived, and that there they had issued a warrant to apprehend him.
Now he could have gone away, and got out of their reach; but considering that,
there being a noise of a plot in the north, if he should go away,
they might fall upon his friends; but if he stayed, and was taken,
his friends might escape the better; he therefore gave up himself to be taken.
Next day an officer came with his sword and pistols to take him.
G+++.+++ Fox told him, '`I knew thy errand before, and have given up myself to be taken;
for if I would have escaped imprisonment, I could have been gone forty miles off;
but I am an innocent man, and so matter not what ye can do to me.`'
Then the officer asked him, how he heard of it,
seeing the order was made privately in a parlor.
G+++.+++ Fox said, it was no matter for that: it was sufficient that he heard of it.
Then he asked him to show his order.
But he laying his hand on his sword, said, '`You must go with me before the lieutenants,
to answer such questions as they shall propound to you.`'
Now though G. Fox insisted to see the order,
telling him it was but civil and reasonable to show it, yet the officer would not;
and then G. Fox said, '`I am ready`' So he went along with him, and Margaret Fell also,
to Houlker-hall.
Being come thither, there was one justice Rawlinson, Sir George Middleton,
justice Preston, and several more whom he knew not.
Then they brought one Thomas Atkinson, one of his friends, as a witness against him,
for some words which he had told to one Knipe, who had informed against him;
and these words were, that he had written against the plotters,
and had knocked them down: but from these words little could be made.
Then Preston asked him, whether he had a hand in the Battledore?
(being a folio book already mentioned,) '`Yes,`' said G. Fox.
He then asked him whether he understood languages?
He answered, '`sufficient for myself.`'

Preston having spoken something more on that subject, said, '`Come,
we will examine you of higher matters:`' then said George Middleton, '`You deny God,
and the church, and the faith.`'
'`Nay,`' replied G. Fox, '`I own God, and the true church,
and the true faith:`' '`But,`' asked he,
(having understood Middleton to be a Papist,)`' what church dost thou own?`'
The other, instead of answering this question, said '`You are a rebel and a traitor.`'
G+++.+++ Fox perceiving this Middleton to be an envious man, asked him whom he spoke to?
or whom he called a rebel?
The other having been silent a while, said at last, '`I spoke to you.`'
G+++.+++ Fox then striking his hand on the table, told him,
'`I have suffered more than twenty such as thou, or any that are here;
for I have been cast into Derby dungeon for six months together, and have suffered much,
because I would not take up arms against this king, before Worcester fight;
and I have been sent up prisoner out of my own country by colonel Hacker to O. Cromwell,
as a plotter to bring in king Charles.
Ye talk of the king, a company of you; but where were ye in Oliver`'s days;
and what did ye do then for the king?
But I have more love to him, for his eternal good and welfare, than any of you have.`'
Then they asked him, whether he had heard of the plot?
And he said, '`Yes.`'
Hereupon he was asked, how he had heard of it, and whom he knew in it?
And he answered, he had heard of it through the high sheriff of Yorkshire,
who had told Dr. Hodgson, that there was a plot in the north;
but that he never heard any thing of it in the south;
and that he knew none of them that were in it.
Then they asked him, '`Why would you write against it,
if you did not know some that were in it.`'
'`My reason was,`' answered he,
'`because ye are so forward to mash the innocent and guilty together;
therefore I wrote against it to clear the Truth from such things,
and to stop all forward foolish spirits from running into such things:
and I sent copies of it into Westmoreland, Cumberland, Bishopric, and Yorkshire,
and to you here; and I sent also a copy of it to the king and his council;
and it is like it may be in print by this time.`'
Then said one of them, '`O this man hath great power.`'
'`Yes,`' said he, '`I have power to write against plotters.`'
'`But,`' said one of them, '`you are against the laws of the land.`'
'`Nay,`' said he, '`for I and my friends direct all the people to the Spirit of God in them,
to mortify the deeds of the flesh: this brings them into well doing,
and from that which the magistrates`' sword is against; which eases the magistrates,
who are for the punishment of evil doers,`' etc.

Middleton now weary, as it seemed, of his speaking, cried, '`Bring the book,
and put the oath of allegiance and supremacy to him.`'
But G. Fox knowing him to be a Papist, asked him, whether he who was a swearer,
had taken the oath of supremacy;
for this oath tending to reject the pope`'s power in England,
was a kind of test to try people whether they were Papists, or no:
'`But as for us,`' said G. Fox, '`we cannot swear at all,
because Christ and his apostles have forbidden it.`'
Now some of these that set there, seeing Middleton was thus pinched,
would not have had the oath put to G. Fox; but others would,
because this was their last snare, and they had no other way to get him into prison:
for all other things had been cleared;
but this was like the Papists`' sacrament of the altar,
by which they formerly ensnared the martyrs:
and in the Low Countries they asked the Baptists, whether they were re-baptized;
and if this appeared, then they said, '`We do not kill you,
but the emperor`'s decree condemns you.`'
So they tendered G. Fox the oath, and he refusing to take it,
they consulted together about sending him to jail: but all not agreeing,
he was only engaged to appear at the sessions: and so for that time they dismissed him.

Then he went back with Margaret Fell to Swarthmore, where colonel West,
who was at that time a justice of the peace, came to see him.
And G. Fox asking him, what he thought they would do with him at the sessions, he said,
they would tender the oath to him again.
The time of the sessions now approaching, G. Fox went to Lancaster,
and appeared according to his engagement; where he found upon the bench,
justice Flemming,
who in Westmoreland had offered five pounds to any man that would apprehend G. Fox.
There were also the justices Spencer and Rawlinson, and colonel West;
and a great concourse of people in court, and when G. Fox came up to the bar,
and stood with his hat on, they looked earnestly upon him.
Then proclamation being made for all to keep silence on pain of imprisonment,
he said twice, '`Peace be among you.`'
Then Rawlinson, who was chairman, spoke, and asked, if he knew where he was?
To which he answered, '`Yes, I do; but it may be my hat offends you;
but that`'s a low thing, that`'s not the honor I give to magistrates:
for the true honor is from above;
and I hope it is not the hat which ye look upon to be the honor.
To which the chairman said, '`We look for the hat too.
Wherein do you show your respect to magistrates, if you do not put off your hat?`'
G+++.+++ Fox replied, '`In coming when they call me.`'
They then bid one take off his hat.
After some pause, the chairman asked him, whether he knew of the plot.
To which he returned, that he had heard of it in Yorkshire,
by a friend that had it of the high-sheriff.
The next question was, whether he had declared it to the magistrates; and his answer was,
'`I have sent papers abroad against plots and plotters, and also to you,
as soon as I came into the country,
to take all jealousies out of your minds concerning me and my friends: for it was,
and is our principle to declare against such things.`'
Then they asked him, if he knew not of an act against meetings.
To which he made answer,
that he knew there was an act that took hold of such
as met to the terrifying of the king`'s subjects,
and were enemies to the king, and held dangerous principles.
'`But I hope,`' said he, '`ye do not look upon us to be such men;
for our meetings are not to terrify the king`'s subjects, neither are, we enemies to him,
or any man.`'

That which followed hereupon,
was the tendering of the oath of allegiance and supremacy to him.
To which he told them, that he had never taken any oath in his life:
and that he could not take any oath at all,
because Christ and his apostles had forbidden it.
Then Rawlinson, who was a lawyer, asked him, whether he held it was unlawful to swear?
G+++.+++ Fox presently perceived this question to be put on purpose to ensnare him;
for by a certain act 13 and 14 Car. 2. cap. 1, such who said,
it was unlawful to swear, were liable to banishment, or to a great fine.
Therefore to avoid this snare, he told them,
that in the time of the law amongst the Jews, before Christ came,
the law commanded them to swear; but Christ who did fulfill the law in the gospel time,
commands, not to swear at all; and the apostle James forbids swearing,
even to them that were Jews, and had the law of God.
Now after much other discourse, the jailer was called, and G. Fox committed to prison.
He then having the paper about him which he had written against plots,
desired it might be read in the court; but this they would not suffer.
Being thus committed for refusing to swear, he said to those on the bench,
and all the people, '`Take notice that I suffer for the doctrine of Christ,
and for my obedience to his command.`'
Afterwards he understood, the justices said,
that they had private instructions from colonel Kirby to prosecute him,
notwithstanding his fair carriage, and seeming kindness to him before.

[.small-break]
'''

Leaving G. Fox in prison, I am to say that the act already mentioned,
whereby a penalty was laid on all such who should say, it was unlawful to take an oath,
was that which extended to banishment, being made not long before,
and expressly leveled against the Quakers, as plainly appeared by the title.
This is that act, by direction whereof the Quakers, so called, were afterwards banished,
as may be related in due time and place;
and though the king himself was pretty good-natured,
yet he suffered himself to be so swayed by the instigations of some envious men,
as well among the ecclesiastics, as among the laity,
that he gave the royal assent thereto.

Whilst G. Fox was prisoner at Lancaster, many of his friends were also imprisoned,
for frequenting religious meetings, refusing to take oaths,
and for not paying tithes to the priests;
but since he was not brought to his trial till next year,
we will leave him still in jail, and in the meanwhile will take a turn to Colchester,
where persecution now was exceeding fierce.

In the month of October, William More, mayor of that town,
came on a First-day of the week, and broke up the meeting of the Quakers, so called,
and committed some of them to prison; the next week he did so again,
and a week after he caused a party of the county troop to come to the meeting.
These beat some, and did much mischief to the forms, seats,
and windows of the meeting-place.
And afterwards the mayor employed an old man to stop
people from going in at the gate to the meeting-room;
who told those that would have entered,
that the mayor had set him there to keep them out.
Now though they knew he was no officer, nor had any warrant, yet they made no resistance,
but continuing in the street, thus kept their meeting in a peaceable manner,
being not free for conscience-sake to leave off their public worship of God,
though in that time of the year it was cold, and often wet weather;
and thus it continued many weeks, though attended with so much difficulty.

In the forepart of December there came about forty of the king`'s troopers, on horseback,
in their armor, with swords, carbines, and pistols, crying, '`What a devil do ye here?`'
And falling violently upon this harmless company, they beat them, some with swords,
and others with carbines, without distinction of male or female, old or young,
until many were much bruised, chasing them to and fro in the streets.
The next First-day of the week these furious fellows came again, having now got clubs,
wherewith, as well as with swords and carbines,
they most grievously beat those that were peaceably
met together in the street to worship God.
This cruel beating was so excessive, that some got above a hundred blows,
and were beaten so black and blue, that their limbs lost their natural strength.
One there was whom a trooper beat so long,
that the blade of his sword fell out of the hilt, which he that was thus beaten seeing,
said to the other, '`I will give it thee up again,`' which he did, with these words,
'`I desire the Lord may not lay this day`'s work to thy charge.`'

But to avoid prolixity,
I shall not mention all the particular misusages
which I find to have been committed there.
These cruel doings continued yet several weeks, and some were beaten so violently,
that their blood was shed in the streets, and they sunk down and fainted away.
One Edward Graunt, a man of about threescore and ten years of age,
(whose wife and daughters I was well acquainted with,) was so terribly knocked down,
that he outlived it but a few days.
So hot was this time now, that these religious worshippers,
when they went to their meeting, seemed to go to meet death;
for they could not promise to themselves to return home either whole or alive.
But notwithstanding all this, their zeal for their worship was so lively,
that they durst not stay at home, though human reasoning might have advised them thereto.
And some of them had been people of note in the world; as,
among others one Giles Barnadiston, who having spent six years in the university,
in the study of human literature, afterwards came to be a colonel;
but in process of time, having heard G. Fox the younger, preach,
he was so entirely convinced of the Truth by him declared,
that laying down his military command,
he entered into the society of those called Quakers, and continuing faithful,
he in time became a minister of the gospel among the said people;
being a man of a meek spirit, and one whom I knew very well.
This Barnadiston did not forbear frequenting meetings,
how hot soever the persecution was,
being fully given up to hazard his life with his friends.

One Solomon Fromantle, a merchant, with whom I was well acquainted,
was so grievously beaten, that he fell down and lost much of his blood in the street;
and yet the barbarous troopers did not leave off beating him.
His wife, a daughter of the aforesaid Edward Graunt, fearing lest he should be killed,
fell down upon him,
to cover and protect him from the blows with the hazard of her own body,
as she herself told me in the presence of her said husband:
a conjugal love and fidelity well worthy to be mentioned, and left upon record.
And though she then did not receive very fierce blows yet there
were some women whose lot it was to be sorely beaten with clubs,
whereinto iron spikes were driven, as among the rest an aged widow,
who received no less than twelve such bloody blows on several parts of her body;
and another woman was pierced in her loins with such a spiked club.
An ancient man of sixty-five years was followed a
great way by three on foot and one on horseback,
and so beaten and bruised, that a woman, pitying this old man,
spoke to these mischievous fellows to leave off;
but this so incensed him that was on horseback,
that he gave her a hard blow with his sword on the shoulder, with cursing and railing.
This barbarity continued,
till the persecutors seemed to be more wearied out than the persecuted,
who seemed to grow valiant in these sore tribulations, how grievous soever.
A great promoter of this furious violence was captain Turner,
who drove on his troopers to act thus; nay, such was his malice,
that once at the breaking up of a meeting, he not only gave order to beat the people,
but also to spoil the doors, windows, and walls,
so that the damage came to five and twenty pounds.

Now I could enter upon a large relation of the trial of many prisoners at Worcester,
before the judges Hide and Terril;
but since that trial was much after the same manner as that of John Crook,
here before-mentioned at large, I will but cursorily make some mention of it.
When the prisoners, being brought to the bar, asked,
why they had been kept so long in prison; they were answered with the question,
whether they would take the oath of allegiance.
And endeavors were used to draw some to betray themselves, by asking them,
where they had been on such a day.
For if they had said, at meeting,
then it would have appeared from their own mouth that they had acted contrary to the law;
but they answered warily, that they were not bound to accuse themselves.
Others by evidence were charged with having been at a meeting; and when they said,
that their meetings were not always for public worship;
but that they had also meetings to take care for widows, fatherless,
and others that were indigent; yet it was said to the jury,
that though there was no evidence, that there had been any preaching in the meeting,
yet if they did but believe that the prisoners had kept a meeting for religious worship,
it was sufficient for them to approve the indictment.
And yet such proceedings in other cases would have been thought unwarrantable.

One Edward Bourn being imprisoned for having been at a meeting,
and afterwards brought to his trial, the oath was tendered to him.
Among other words he spoke in defense of himself, he said,
'`Suppose Christ and his apostles kept a meeting here in this time,
would this act against conventicles also take hold of them?`'
'`Yes,`' said the judge, '`it would.`'
But bethinking himself, he said, '`I wont answer your questions; ye are no apostles.`'
The conclusion was,
that Bourn and several of his friends were fined each of them five pounds.

Now since those that were fined thus, did not use to pay the fines,
judging that the thing which they were fined for
was an indispensable duty they owed to God,
and therefore they could not pay any such fine with a good conscience,
the consequence thereof generally was imprisonment, and distraining of their goods,
whereby some lost twice, and it may be, thrice as much as the fine amounted to.
Some of the prisoners made it appear, that they had been somewhere else,
and not in the meeting, at the house of one Robert Smith,
at such time as the evidence declared by oath;
yet because they gave no satisfactory answer to the question,
whether they had not been there on that day, they were deemed guilty.
The said Robert Smith was premunired: for the oath of allegiance being tendered to him,
and he, menaced by the judge with a premunire, asked, for whom that law,
for taking the said oath, was made, whether not for Papists.
And on suspicion that some of that persuasion sat on the bench, he asked also,
whether they, for the satisfaction of the people, there present,
ought not also to take the oath.
But the judge waived this, telling him, he must take the oath,
or else sentence should be pronounced against him.
Smith asked then, whether the example of Christ should decide the question;
but the judge said,
'`I am not come here to dispute with you concerning the doctrine of Christ,
but to inform you concerning the doctrine of the law.`'
Then Smith was led away, and afterwards,
when an indictment for his refusing the oath was drawn up,
he was brought into the court again, and asked,
whether he would answer to the indictment, or no;
and the reasons he gave not being accepted, the judge said,
before Smith had done speaking, '`This is your sentence, and the judgment of the court:
You shall be shut out of the king`'s protection,
and forfeit your personal estate to the king forever, and your real estate during life.`'
To this Robert said with a composed mind, '`The Lord hath given,
and if he suffers it to be taken away, his will be done.`'
Thus Robert Smith suffered, with many more of his friends, there and elsewhere:
all which I believe my life-time would not be sufficient to describe circumstantially.

Passing then by the other persecutions of this year,
I will relate one remarkable case that happened in this year, 1663,
where patience triumphed very eminently over violence.
But before I enter upon this narrative, it will not be amiss to go back a little,
and mention some singular cases of the chief actor of the fact I am going to describe.

His name was Thomas Lurting, who formerly had been boatswain`'s mate in a man of war,
and often had been preserved in imminent dangers: as once being at the Canary islands,
under admiral Blake commander in this expedition,
they ruined the admiral and vice-admiral of the Spanish galleons, and this being done,
he with seven men was sent with a pinnace to set on fire three galleons in the bay;
which order he executed, by setting one of them on fire, which burnt the other two.
But returning, and passing by a breast-work, they received a volley of small shot,
by which two men, close to one of which Thomas sat, were killed,
and a third was shot in his back, but Thomas received no harm.
And going out of the bay, they came within about four ships length of the castle,
which had forty guns; and when they came directly over against the castle,
the guns were fired, and a shot cut the bolt-rope a little above Thomas`'s head,
without hurting him.
In more dangers he was eminently preserved, but that I may not be too prolix,
I will now relate, how from a fighting sailor he became a harmless Christian.

About the year 1654,
it happened that among the soldiers which were in the ship he was in,
there was one that had been at a meeting of those called Quakers in Scotland,
and there were two young men in the ship who had some converse with him;
but he was soon taken away from the ship.
Yet these two young men seemed to be under some convincement; for about six months after,
they scrupled to go and hear the priest, and to put off their hats to the captain;
by which they came to be called Quakers.
These two met often together in silence, which being seen by others of the ship,
their number increased; but this troubled the captain exceedingly,
and the priest grew not a little angry, and said to our boatswain, '`O Thomas,
an honest man and a good Christian; here is a dangerous people on board,
viz. the Quakers, a blasphemous people, denying the ordinances and word of God.`'
This made Thomas so furious,
that in a bigoted zeal he fell to beating and abusing these men,
when religiously met together.
But this was not the way to have a quiet and sedate mind;
for the remembrance of his former deliverances stuck so close upon him,
that he could no more beat any of the said people; and then he came to a further sight,
insomuch that he clearly saw what a fellow the priest was:
for when Thomas could ho longer abuse the said people,
then he was not accounted by him either an honest man or a good Christian.
Now being under condemnation because of his outgoings, he made many promises to the Lord;
but these being made in his own will, were of little effect.
Yet by the grace of God it was showed him, that since he did not perform these promises,
he could not be benefited thereby, which caused him much trouble.

Among those in the ship called Quakers, was one Roger Dennis, whom he entirely loved,
and therefore never struck him; tor this man had a check on Thomas, to that degree,
that looking only upon him,
he durst not touch any of those whom he intended to have abused.
In this state, feeling no peace in his mind, after some time he much desired to be alone,
the more freely to pour out his heart before the Lord;
and though he then felt himself inwardly condemned, yet judgments became pleasant to him,
because thereby his heart was tendered and broken:
in which state he could not forbear sometimes to cry out, O Lord!
But this, being observed by the ship`'s crew, made some say, he was mad, and others,
he was distracted; and of this some wrote home to England.
Now it fell to his share to be mocked and ridiculed;
but he endeavored to be fully given up,
if he might but have peace in his conscience with God.

And being one evening alone, he was very earnest with the Lord,
to know what people he should join himself to; and then it was plainly showed him,
the Quakers.
But this so startled him at that time, that he desired of the Lord,
rather to die than to live:
for to join with a people whom he so often had been beating and abusing,
seemed to be harder to him than death itself;
and by the subtlety of Satan he was often assaulted by various thoughts,
to keep him off from the said people.
But when the Lord made him mindful of his manifold preservations and deliverances,
it mollified his heart, so that at length he came to this resolution,
whether Quaker or no Quaker, I am for peace with God.
Yet it cost him many a bitter sigh, and many a sorrowful tear,
before he could come to a lull resignation.
But the inward reproofs of the Lord, attended with judgments, followed him so close,
that he could no longer forbear, but gave up.
And then he took opportunity to discover his heart to his friend Roger Dennis,
who spoke so to the purpose, that he had great satisfaction.
But not long after temptations assaulted him again in this manner, '`What,
to join thyself to such a foolish people!`' And the
very thoughts of this were so grievous to him,
that he grew even weary of his life; for thus to expose himself to scorn,
seemed to him an intolerable cross;
but this struggling was not the way to get peace with God.
The First-day of the week being come, he resolved to go to the small meeting,
which was now of six in number; but it being reported that he was among the Quakers,
many of the company left their worship to see him; and they made a great noise.
When the worship was over, the captain asked the reason of that noise;
and it was told him, that Thomas was amongst the Quakers; on which he sent for him,
there being several officers also present; but the first that spoke was the priest,
saying, '`Thomas, I took you for a very honest man, and a good Christian,
but am sorry you should be so deluded.`'
And the captain endeavored to prove from the bible, the Quakers were no Christians.
Thomas in the meanwhile was still and quiet;
and the others seeing they could not prevail upon him that way, took another course,
and said, that the Quakers sometimes came to him saying, '`Do such and such a thing.`'
But because he knew this to be altogether false,
and saw how they would bear him down with lies, he was the more strengthened;
so that going to his friends, he said to them,`' When I went to the captain,
I was scarce half a Quaker;
but by their lies and false reports they have made me almost a whole Quaker;
or at least I hope to be one.`'

He continuing to meet with his friends for the performing of worship,
some more came to be joined to them, so that in less than six months after,
they were twelve men, and two boys, one of which was the priest`'s. Now,
there was none aboard that would abuse the Quakers, though much tried by the captain;
for he got some men out of other ships on purpose to vex them:
but how fiercely soever these behaved themselves, a higher power limited them.
At length, there was a sickness on board the ship,
which swept away above forty in a short time; and most of them called Quakers,
had the distemper also, but none died of it, though some were brought very low.
They took great care of one another when sick, and whatever one had was free for all;
which care being seen by others, made some of them cry upon their deathbed,
'`O carry me to the Quakers, for they take great care of one another,
and they will take some care of me also.`'
This visitation in the ship, changed the captain so much,
that he was very kind to Thomas, and often sent him part of what he had.
Thomas seeing him in such a good humor,
desired of him to have the cabin he lay in before his change, which request was granted;
for none were willing to lie therein,
because they told one another it was troubled with an evil spirit;
since three or four had died therein within a short space of time.
This cabin he made use of also for a meeting-place;
and the captain was now so well pleased with him, that when something was to be done,
he would often say, '`Thomas, take thy friends, and do such or such a thing:
for as yet they were not against fighting, and therefore no complete Quakers.
And thus when Thomas and his friends were sent out on some expedition,
they did their work beyond his expectation.
But though they were not brought off from fighting, yet when, with others,
they annoyed their enemies, they would take none of the plunder;
and in all desperate attempts they received no hurt,
though several others were killed and wounded; and they behaved themselves so valiantly,
that their captain would say to other captains,
that he cared not if all his men were Quakers,
for they were the hardiest men in his ship.
But though this was a time of liberty,
yet Thomas looked upon it as a forerunner of further exercise;
for he saw what was done in pretended friendship, was but to serve their own ends;
and therefore he expected a time of trial would come, and so it did.

For being come to Leghorn, they were ordered to go to Barcelona,
to take or burn a Spanish man of war.
Their station was to lie against a castle, and batter it; which they did;
and one corner of the castle playing some shot into their ship,
Thomas was for beating down that part: and those called Quakers,
fought with as much courage as any.
He himself being stripped to his waistcoat, and going into the forecastle,
he leveled the guns, but said, '`Fire not, till I go out to see where the shot lights,
that we may level higher or lower;`' he being yet as great a fighter as any;
but as he was coming out of the forecastle door to see where the shot fell,
suddenly it run through him, '`What if now thou kills a man?`'
This struck him as a thunderbolt, and he that can turn men`'s hearts, at his pleasure,
changed his in a minute`'s time to that degree, that whereas, just before,
he bent all his strength to kill men, he now found in himself no will thereto,
though it were to gain the world; for he presently perceived it was from the Lord;
and then putting on his clothes, he walked on the deck,
as if he had not seen a gun fired; and being under great exercise of mind,
some asked him, if he was hurt.
He answered, '`No;
but under some scruples of conscience on the account of fighting,`'
though then he knew not that the Quakers refused to fight.

When night came, they went out of the reach of the castle shot,
and he took occasion to speak with two of his friends in the ship,
and inquired their judgment concerning fighting; but they gave little answer to it,
but said however, if the Lord sent them well home, they would never go to it again.`'
To which he returned, that if he stood honest to that of God in his own conscience,
and they came to it tomorrow, with the Lord`'s assistance,
he would bear his testimony against it; for he clearly saw,
that forasmuch as they had been such great actors in fighting,
they now must bear their testimony against it, and wait what would be the issue;
saying with themselves, '`The will of the Lord be done.`'
The next day they heard that several were killed on shore,
which grieved Thomas not a little.
Some time after, one of Thomas`'s friends went to the captain to be cleared;
and he asking why?
His answer was, that he could fight no longer.
To which the captain said, '`He that denies to fight in time of engagement,
I will put my sword in his guts.`'
'`Then,`' said the other,`' thou wilt be a manslayer,
and guilty of shedding blood:`' for which the captain,
(who was a Baptist preacher,) beat him sorely with his fist and cane;
and he that had been their friend, was now become their open enemy.

Some time after, (about the year 1665,) being at Leghorn,
they were ordered to go a cruising;
and one morning spied a great ship bearing down upon them,
which they supposed to be a Spanish man of war.
Presently orders were given to clear the ship for fight.
Thomas then being upon the deck, saw plainly that a time of trial was now come,
and he prayed to the Lord very earnestly for strength:
and that which seemed most expedient to him, was to meet with his friends, which,
after notice given, was done accordingly.
Being all met, he told them how it was with him,
and that things seemed very dark and cloudy, yet his hopes were,
that the Lord would deliver him, and all such as were of his faith; to which he added,
'`I lay not this as an injunction upon any one,
but leave you all to the Lord:`' moreover he said, '`I must tell you,
that the captain puts great confidence in you;
therefore let us be careful that we give no just occasion; and all that are of my mind,
let us meet in the most public place upon the deck, in the full view of the captain,
that he may not say we deceived him, in not telling him that we would not fight,
so that he might have put others in our room.`'

Then Thomas went upon the deck, and set his back against the geer capstan,
and a little after turning his head, he saw his friends behind him;
at which though he rejoiced, yet his bowels rolled within him for them,
who stood there as sheep ready for the slaughter.
Within a little time came the lieutenant, and said to one of them,
'`Go down to thy quarters;`' to which he returned, '`I can fight no more.`'
The lieutenant then going to the captain, made the worst of it, saying,
'`Yonder the Quakers are all together; and I do not know but they will mutiny;
and one says he cannot fight.`'
The captain having asked his name, came down to him, flung his hat overboard,
and taking hold of his collar, beat him with a great cane,
and dragged him down to his quarters.
Then he went upon the half deck again, and called for his sword,
which his man having brought him, he drew with great fury.
No sooner was this done, but the word of the Lord, (as Thomas took it,) run through him,
saying, '`The sword of the Lord is over him; and if he will have a sacrifice,
proffer it him.`'
And this word was so powerful in him, that he quivered and shook,
though he endeavored to stop it, fearing they should think he was afraid,
which he was not; for turning his head over his shoulder, he said to his friend Roger,
'`I must go to the captain.`'
To which he returned,`' Be well satisfied in what thou doest.`'
And Thomas replied, there was a necessity upon him.
Then seeing the captain coming on with his drawn sword,
he fixed his eye with great seriousness upon him, and stepped towards him,
keeping his eyes upon him,
(in much dread of the Lord,) being carried above his furious looks.
At which the captain`'s countenance changed pale, and he, turning himself about,
called to his man to take away his sword, and so he went off.
Not long after, the ship they expected to fight withal, proved to be a Genoese,
their friend; and before night, the captain sent the priest to Thomas,
to excuse his anger, it having been in his passion.
To which Thomas`'s answer was, that he had nothing but good will to him;
and he bade the priest tell the captain, that he must have a care of such passions;
for if he killed a man in his passion, he might seek for repentance,
and perhaps not find it.
Thus Thomas overcame this storm, and at length got safe home.

Now leaving men-of-war, he afterwards went to sea in a merchantman, or trading ship:
but then it fell to be his lot several times to be pressed into the king`'s service,
and being carried into a man of war, he suffered very much.
Once he fasted five days, taking only at times a draught of water;
for he could easily guess, that if he had eaten of their victuals,
it would have gone the harder with him; since he scrupled to do any ship-work,
though it did not belong to fighting;
for he judged all this to be assistance to those whose business it was to fight;
and that therefore in such a ship he could do nothing, whatever it was,
but it was being helpful and assisting.

In this condition he met with several rude occurrences for some years together.
Being once at Harwich, hard at work in a ship, heaving out corn in a lighter,
he was pressed; but one of the men saying, that he was a Quaker, the captain,
who with his boat was come aboard, said in a scoffing manner to him, '`Thou art no Quaker,
for if thou wast a Quaker, thou should be waiting upon the Lord,
and let his ravens feed thee, and not be toiling thy body.`'
For Thomas being stripped to his shirt and drawers, his shirt was wet with sweat;
and being a little time silent, said at length to the captain,
'`I perceive thou hast read some part of the scriptures.
Didst thou never read,
that he is worse than an infidel that will not provide for his family?
I have often heard the Quakers blamed for not working,
but thou art the first that ever I heard blame them for working.`'
At this the captain said, '`Turn him away, he is a Quaker.`'
But a little after he cried, '`Pull him again, he is no Quaker;`' and said to Thomas,
'`Thou art no Quaker; for here thou brings corn, and of it is made bread,
and by the strength of that bread we kill the Dutch; and therefore no Quaker.
Or art not thou as accessary to their deaths as we?
Answer me.`'
Thomas not presently answering, was much scoffed and jeered by the seamen;
but at length he said to the captain, '`I am a man that can feed my enemies,
and well may I you, who pretend to be my friends.`'
To which the captain replied, '`Turn him away,
he is a Quaker:`' and thus that storm ceased.

But a few days after he was pressed again out of the same vessel,
and carried on board a man of war; there he was ordered to go into the cabin,
where the captain and several officers were; and being entered,
the captain began to curse the Quakers, and swore, that if he did not hang Thomas,
he would carry him to the duke of York, and he would.
But Thomas said very little, and felt himself kept by the Lord from fear.
And when the captain had tired himself with scolding and railing, he said more mildly,
'`What, dost thou say nothing for thyself?
To which Thomas answered,
'`Thou sayest enough for thee and me too:`' and he found it most safe to say little.
This was indeed the best way; for generally no reasons, how good soever,
avail with passionate men; who often think it a disparagement to them,
when they hearken to what is said by one they look upon to be their inferior.
But such sometimes find they reckon amiss; as this captain did, who,
notwithstanding his haughtiness, was soon struck by a superior power;
for the next night a sudden cry was heard, '`Where is the Quaker?
Where is the Quaker?`'
Thomas hearing this, said, '`Here I am: what lack you at this time of the night?`'
To which it was told him, '`You must come to the captain presently.`'
He then coming to the cabin door, the captain said, '`Is the Quaker there?`'
To which Thomas having answered, '`Yes,`' the captain said, '`I cannot sleep,
thou must go on shore.`'
Thomas replied, '`I am in thy hand, and thou mayest do with me as thou pleases.`'
So with the boat he was put on shore at Harwich, by order of the captain,
who in his fury had said, that hanging was too good for him.
But now, because his mind was disquieted, he could not sleep, though Thomas,
who lay on the hard boards, slept very well.

Having said thus much of this seaman: let us now take a view, and behold how,
and in what an industrious manner, he,
without passing the bounds of a peaceable disposition,
retook a ship that was taken by a pirate; which happened in the year 1663,
after this manner:

A master of a ship, whose name was George Pattison,
one of the society of those called Quakers, about the month of October,
being with his ship in the Mediterranean, coming from Venice, near the island of Majorca,
was chased by a pirate of Algiers, and their vessel sailing well,
they endeavored to escape; but, by carrying over-much sail,
some of their materials gave way, by which means the Turks came up with them,
and commanded the master on board, who accordingly, with four men more, went in his boat,
leaving only his mate,
(the before-mentioned Thomas Lurting,) with three men and a boy on board his vessel,
as soon as those came on board the pirate,
the Turks put thirteen or fourteen of their men into the boat,
to go towards the English ship.
In the meanwhile the mate was under great exercise of mind,
the rather because the master, with four of his men, were then with the Turks,
and those that were left, were somewhat unruly.
In this concern, however, he believed it was told him inwardly by the Lord,
'`Be not afraid,
for thou shalt not go to Algiers:`' for having had
formerly great experience of the Lord`'s deliverances,
as hath been said above, he had already learned to trust in God, almost against hope.
On the consideration of this, all fear was removed from him;
and going to the ship`'s side to see the Turks come in,
he received them as if they were his friends, and they also behaved themselves civilly:
then he showed them all the parts of the vessel, and what she was laden with.
Afterwards he said to the men that were with him, '`Be not afraid,
for all this we shall not go to Algiers: but let me desire you,
as ye have been willing to obey me, to be as willing now to obey the Turks.`'
This they promised him, and by so doing, he soon perceived they gained upon the Turks;
for they seeing the seamen`'s diligence, grew the more careless and favorable to them.
And having taken some small matter of the lading, some went again to their own ship,
and eight Turks stayed with the English.

Then the mate began to think of the master,
and the other four that were in the Turk`'s ship; as for himself, and the others with him,
he had no fear at all; nay, he was so far from it, that he said to one of his men,
'`Were but the master on board, and the rest of our men,
if there were twice as many Turks, I should not fear them.`'
By this he encouraged the seamen, who not being of his persuasion,
thought much otherwise than he,
and would have been ready enough to have killed the Turks, if they had seen opportunity.
In the meanwhile the mate`'s earnest desire to the Lord was,
that he would put it into the heart of the Turks,
to send the master and the four others back.
And his desire was answered; for soon after the master and those men were sent on board.

Then all manner of fear concerning going to Algiers was taken away from him;
which made some say to him, he was a strange man,
since he was afraid before he was taken, but now he was not.
For before they were taken, he having heard there were many Turks at sea,
endeavored to persuade the master to have gone to Leghorn,
and there to stay for a convoy, and so long they would have no wages.
But to this the master would not agree.
Now the mate, to answer the seamen, who blamed his behavior, said to them,
'`I now believe I shall not go to Algiers: and if ye will be ruled by me,
I will act for your delivery, as well as my own.`'
However, though he spoke thus boldly, yet he saw no way for it;
for the Turks were all armed, and the English without arms.
Now these being altogether, except the master, he said to them,
'`What if we should overcome the Turks, and go to Majorca.`'
At which they very much rejoiced, and one said,
'`I will kill one or two;`' '`And I,`' said another,
'`will cut as many of their throats as you will have me.`'
But at these sayings the mate was much troubled, for he intended not to hurt any,
and therefore told the men, '`If I knew that any of you would touch a Turk at that rate,
I would tell it the Turks myself But,`' said he, '`if ye will be ruled, I will act for you;
if not, I will be still.`'
They seeing that he would not suffer them to take their own course,
agreed to do what he would have them.`'
'`Well,`' said he, '`if the Turks bid you do any thing, do it without grumbling,
and with as much diligence and quickness as ye can, for that pleases them,
and will cause them to let us be together.`'
To this the men all agreed; and then he went to the master, and told him their intention.
But his answer was, '`If we offer to rise, and they overcome us,
we had as good be burnt alive.`'
The mate knew very well the master was in the right,
viz. that if they failed in the attempt,
they were like to meet with the most cruel treatment
from the Turks that could be thought of.
Now the reason why the master, though a very bold spirited man,
did not readily consent to the proposal, was, because he feared they would shed blood,
but his mate told him, they were resolved, and he questioned not but to do it,
without shedding one drop of blood; and besides, he would rather have gone to Algiers,
than to kill one Turk.
Speaking thus, he so swayed the master,
that at last he agreed to let him do what he would, provided they killed none.

Now since two Turks lay in the cabin with the master,
it was agreed that he should continue to lie there, lest they should mistrust any thing.
In the meanwhile it began to be bad weather,
so that they lost the company of the Turkish man of war,
which was the thing the mate much desired;
and the Turks seeing the diligence of the English sailors, grew careless concerning them,
which was what the mate aimed at.
The second night after, the captain of the Turks, and one of his company,
being gone to sleep in the cabin with the master,
the mate persuaded one to lie in his cabin,
and about an hour after another in another cabin; and at last it raining very much,
he persuaded them all to lie down and sleep: and when they were all asleep,
he coming to them, fairly got their arms into his possession.
This being done, he told his men, '`Now we have the Turks at our command,
no man shall hurt any of them; for if ye do, I will be against you: but this we will do,
now they are under deck, we will keep them so, and go for Majorca.
And having ordered some to keep the doors, they steered their course to Majorca,
and they had such a strong gale, that in the morning they were near it.
Then he ordered his men, if any offered to come out,
not to let above one or two at a time; and when one came out,
expecting to have seen his own country,
he was not a little astonished instead thereof to see Majorca.
Then the mate said to his men, '`Be careful of the door,
for when he goes in we shall see what they will do.
But have a care not to spill blood.`'
The Turk being gone down, and telling his comrades what he had seen,
and how they were going to Majorca, they, instead of rising, all fell a crying,
for their courage was quite sunk; and they begged that they might not be sold.
This the mate promised, and said, they should not.
And when he had appeased them, he went into the cabin to the master,
who knew nothing of what was done, and gave him an account of the sudden change,
and how they had overcome the Turks.
Which when he understood, he told their captain,
that the vessel was now no more in their possession, but in his again;
and that they were going for Majorca.
At this unexpected news the captain wept, and desired the master not to sell him;
which he promised he would not.
Then they told him also, they would make a place to hide them in,
that they Spaniards coming aboard should not find them.
And so they did accordingly, at which the Turks were very glad.

Being come into the port of Majorca, the master, with four men, went ashore,
and left the mate on board with ten Turks.
The master having done his business, returned on board, not taking license,
least the Spaniards should come and see the Turks: but another English master,
being an acquaintance, lying there also with his ship, came at night on board;
and after some discourse, they told him what they had done, under promise of silence,
least the Spaniards should come and take away the Turks.
But he broke his promise, and would have had two or three of the Turks,
to have brought them to England.
His design then being seen, his demand was denied; and seeing he could not prevail,
he said to Pattison and his mate, that they were fools,
because they would not sell the Turks,
which were each worth two or three hundred pieces of eight.
But they told him, that if they would give many thousands, they should not have one,
for they hoped to send them home again; and to sell them, the mate said,
he would not have done for the whole island.
The other master then coming ashore, told the Spaniards what he knew of this,
who then threatened to take away the Turks.
But Pattison and his mate having heard this, called out the Turks, and said to them,
'`Ye must help us or the Spaniards will take you from us.`'
To this the Turks, as one may easily guess, were very ready,
and so they quickly got out to sea: and the English, to save the Turks,
put themselves to the hazard of being overcome again;
for they continued hovering several days,
because they would not put into any port of Spain, for fear of losing the Turks:
to whom they gave liberty for four or five days, until they made an attempt to rise;
which the mate perceiving, he prevented, without hurting any of them,
though he once laid hold of one; yet generally he was so kind to them,
that some of his men grumbled, and said he had more care for the Turks than for them.
To which his answer was, they were strangers, and therefore he must treat them well.
At length, after several occurrences, the mate told the master,
that he thought it best to go to the coasts of Barbary,
because they were then like to miss their men of war.
To this the master consented.
However, to deceive the Turks, they sailed to and fro for several days;
for in the daytime they were for going to Algiers,
but when night came they steered the contrary way, and went back again,
by which means they kept the Turks in ignorance, so as to be quiet.

But on the 9th day, being all upon deck,
when none of the English were there but the master, his mate, and the man at the helm,
they began to be so untoward and haughty, that it rose in the mate`'s mind,
what if they should lay hold on the master, and cast him overboard:
for they were ten lusty men, and he but a little man.
This thought struck him with terror; but recollecting himself, and taking heart,
he stamped with his foot and the men coming up, one asked for the crow,
and another for the axe, to fall on the Turks;
but the mate bade them not to hurt the Turks, and said,
'`I will lay hold on their captain:`' which he did,
for having heard them threaten the master, he stepped forward,
and laying hold of the captain, said, he must go down, which he did very quietly,
all the rest following him.
Two days after, being come on the coast of Barbary, they were,
according to what the Turks said, about fifty miles from Algiers, and six from land;
and in the afternoon it fell calm.
But how to set the Turks on shore was yet not resolved upon.
The mate saw well enough, that he being the man who had begun this business,
it would be his lot also to bring it to an end.
He then acquainted the master that he was willing to carry the Turks on shore;
but how to do this safely, he as yet knew not certainly;
for to give them the boat was too dangerous, for then they might get men and arms,
and so come and retake the ship with its own boat;
and to carry them on shore with two or three of the ship`'s men, was also a great hazard,
because the Turks were ten in number: and to put one half on shore was no less dangerous;
for then they might raise the country,
and so surprise the English when they came with the other
half In this great strait the mate said to the master,
if he would let him have the boat and three men to go with him,
he would venture to put the Turks on shore.
The master, relying perhaps on his mate`'s conduct, consented to the proposal,
though not without some tears dropped on both sides.
Yet the mate taking courage, said to the master,`' I believe the Lord will preserve me,
for I have nothing but good-will in venturing my life,
and I have not the least fear upon me; but trust that all will do well.`'

The master having consented, the mate called up the Turks,
and going with two men and a boy in the boat, took in these ten Turks,
all loose and unbound.
Perhaps somebody will think this to be a very inconsiderate act of the mate,
and that it would have been more prudent to have tied the Turks`' hands,
the rather because he had made the men promise, that they should do nothing to the Turks,
until he said, he could do no more;
for then he gave them liberty to act for their lives so as they judged convenient.
Now since he knew not how near he should bring the Turks ashore,
and whether they should not have been necessitated to swim "`a little,
it seemed not prudent, to do any thing which might have exasperated them;
for if it had fallen out so that they must have swam,
then of necessity they must have been untied; which would have been dangerous.
Yet the mate did not omit to be as careful as possible he could.
For calling in the captain of the Turks, he placed him first in the boat`'s stern;
then calling for another, he placed him in his lap, and one on each side,
and two more in their laps, until he had placed them all;
which he did to prevent a sudden rising.
He himself sat with a boat-hook in his hand on the bow of the boat,
having next to him one of the shipmen, and two that rowed, having one a carpenter`'s adze,
and the other a cooper`'s heading-knife.
These were all their arms, besides what belonged to the Turks,
which they had at their command.
Thus the boat went off, and stood for the shore.
But as they came near it, the men growing afraid, one of them cried out of a sudden,
'`Lord have mercy on us, there are Turks in the bushes on shore.`'
The Turks in the boat perceiving the English to be afraid, all rose at once.
But the mate, who in this great strait continued to be hearty,
showed himself now to be a man of courage,
and bid the men to take up such arms as they had;
but do nothing with them until he gave them leave.
And then seeing that there were no men in the bushes,
and that it was only an imagination, all fear was taken away from him,
and his courage increasing, he thought with himself, '`It is better to strike a man,
than to cleave a man`'s head; and turning the boat-hook in his hand,
he struck the captain a smart blow, and bid him set down: which he did instantly,
and so did all the rest.
After the boat was come so near the shore, that they could easily wade,
the mate bid the Turks jump out, and so they did;
and because they said they were about four miles from a town, he gave them some loaves,
and other necessaries.

They would fain have persuaded the English to go with them ashore to a town,
promising to treat them with wine, and other good things;
but though the mate trusted in Divine Providence,
yet he was not so careless as freely to enter into an apparent danger,
without being necessitated thereto:
for though he had some thoughts that the Turks would not have done him any evil,
yet it was too hazardous thus to have yielded to the mercy of those that lived there;
and therefore he very prudently rejected their invitation,
will knowing that the Scripture saith,
"`Thou shalt not tempt the Lord thy God.`" The Turks seeing they could not persuade him,
took their leave with signs of great kindness, and so went on shore.
The English then putting the boat closer in, threw all their arms on shore,
being unwilling to keep any thing of theirs.
And when the Turks got up the hill, they waved their caps at the English,
and so joyfully took their last farewell.
And as soon as the boat came again on board, they had a fair wind,
which they had not all the while the Turks were on board.
Thus Thomas Lurting saved the ship and its men; which being thus wonderfully preserved,
returned to England with a prosperous wind.

Now before the vessel arrived at London,
the news of this extraordinary case was come thither;
and when she was coming up the Thames, the king, with the duke of York,
and several lords, being at Greenwich, it was told him,
there was a Quaker`'s ketch coming up the river, that had been taken by the Turks,
and redeemed themselves without fighting.
The king hearing this, came with his barge to the ship`'s side,
and holding the entering rope in his hand, he understood from the mate`'s own mouth,
how the thing had happened.
But when he heard him say, how they had let the Turks go free, he said to the master,
'`You have done like a fool,
for you might have had good gain for them:`'and to the mate he said,
'`You should have brought the Turks to me.`'
But the mate answered, '`I thought it better for them to be in their own country.`'
At which the king and others smiled, and so went away,
thinking that the master had done foolishly; but he and his mate were of another opinion,
and they made it appear that they did approve the lesson of our Savior,
"`Love your enemies, and do good to those that hate you,`" not only with their mouths,
but that they had also put it into practice.

Though I have described this fact from a printed relation,
yet I have added some circumstances from the mouth of the said mate,
with whom I had some acquaintance.

Several years afterwards, when some seamen of the people called Quakers,
were in slavery at Algiers, G. Fox wrote a book to the grand sultan,
and the king at Algiers, wherein he laid before them their indecent behavior,
and unreasonable dealings, showing them from their Alcoran that this displeased God,
and that Mahomet had given them other directions.
To this he added a succinct narrative of what hath been
related here of G. Pattison`'s ship being taken and retaken,
and how the Turks were set at liberty, without being made slaves:
by which the Mahometans might see what kind of Christians the Quakers were,
viz. such as showed effectually that they loved their enemies,
according to the doctrine of their supreme lawgiver, Christ.
Now concerning those Quakers at Algiers,
of whom mention hath been made that they were slaves there,
it was a pretty long time before opportunity was found to redeem them;
but in the meanwhile they so faithfully served their masters,
that they were suffered to go loose through the town, without being chained or fettered;
and liberty was also allowed them to meet at set times for religious worship:
and their patrons themselves would sometimes come and see what they did there;
and finding no images or prints,
as Papist slaves in the exercise of their worship made use of,
but hearing from their slaves that they reverently adored and worshipped the living God,
Creator of Heaven and Earth, they commended them for it, and said it was very good,
and that they might freely do so.
And since one of them was raised to speak by way of edification to his friends,
some other English slaves frequenting that meeting, came to be united with them.
In the meanwhile the Quakers`' name came to be known at Algiers,
as a people that might be trusted beyond others.

It was in this year that William Caton went to England with his wife from Holland,
(where he was married,) and two friends more, one of which was Judith Zinspenning,
my mother, who was moved to speak at the meeting at Kingston,
where W. Caton interpreted for her.
At another time being in a meeting at London, and he not present,
and feeling herself stirred up to declare of the lovingkindness
of the Lord to those that feared him,
she desired one Peter Sybrands to be her interpreter; but he, though an honest man,
yet not very fit for that service, one or more friends told her,
they were so sensible of the power by which she spoke,
that though they did not understand her words,
yet they were edified by the life and power that accompanied her speech;
and therefore they little mattered the want of interpretation;
and so she went on without any interpreter.
She had indeed a very good talent, and left such repute behind her,
that I coming several years after into England,
kindness was showed me in several places on her account.
After a stay of some weeks at London, and thereabouts, she went to Colchester,
in order to return with W. Caton`'s wife to Holland; but making some stay in that town,
she there wrote a book of proverbs, which, W. Caton having translated into English,
was printed at London.
After her departure, he staying behind, travelled through Essex, Warwickshire,
Staffordshire, Derbyshire, Nottinghamshire, and Yorkshire; and coming into Lancashire,
he repaired to Swarthmore, and found there not only his ancient mistress, Margaret Fell,
who received him very kindly, but also G. Fox, not long before he was taken prisoner.

From thence Caton went to Sunderland, and so to Scarborough,
where meeting with a vessel bound for Holland, he embarked,
and went off with a fair wind: but it was not long before the wind changed;
and being about ten leagues from the land, the sky began to look tempestuous;
which made Caton advise the master to return;
but he thinking the weather would soon change, was unwilling to do so;
yet it fell out otherwise, for a violent storm arose,
by which the ship was so exceedingly tossed, that she grew leaky, and took so much water,
that the pumps continually must be kept going.
But this so wearied the seamen, that Caton also fell to pumping;
for though he found himself prepared to meet death, if it had been the will of the Lord,
yet he knew it to be the duty of a man to preserve his life by lawful means,
as long as possible; besides, he pitied the poor seamen,
and so was made willing to help them as much as lay in his power.
But at length they lost the use of the rudder, and were near the sands and shallows,
by which the danger was greatly increased, and death seemed to approach.

Now Caton, though given up in the will of the Lord,
and prepared to have found his grave in the deep, yet did not omit to call upon the Lord,
and to pray to the Most High for deliverance, if it were consistent with his holy will;
and when the storm was at the highest, his supplication was heard,
and the tempest on a sudden began to cease, and the wind to abate;
which gave him occasion to praise the Almighty for
the great mercy showed to him and the mariners.
Yet the wind being contrary, the master resolved to enter Yarmouth,
where Caton met with another storm: for on the First-day of the week,
being at a meeting of his friends, he with seven more were apprehended,
and carried to the main guard.
The next day they were brought before the bailiffs of the town,
who tendered them the oath of allegiance; which they refusing to take,
were sent to prison, where he was kept above six months,
so that it was not till the next year that he returned into Holland.

Whilst he was in jail, Stephen Crisp came the first time into Holland,
to visit his friends there, and to edify them with his gift.
It would not be amiss here to say a little of his qualifications.
He was a man of notable natural abilities,
and had been zealous for religion before ever he
entered into fellowship with those called Quakers.
But when the report of this people spread itself in the place where he lived,
he made inquiry after them and their doctrine,
and though he heard nothing but evil spoken of them,
it nevertheless made some impression upon his mind,
when he considered how they were derided, hated, slandered, and persecuted;
because this generally had been the lot of those that truly feared God.
But having heard that one of their tenets was, that sin might be overcome in this life,
this seemed to him a great error.
And therefore, when James Parnel came to Colchester, he armed himself with arguments,
to oppose him earnestly: for looking upon him as one that was but a youth,
he thought he should be able to prevail upon him.
He himself was then about seven and twenty years of age,
being not only well versed in sacred writ,
but also in the writings of many of the ancient philosophers.
After he had heard Parnel preach very powerfully,
and found his words more piercing than he had imagined,
he ventured to oppose him with some queries;
but he soon found that this young man was endued with sound judgment;
and with all his wisdom and knowledge he was not able to resist him,
but was forced to submit to the truth he held forth.
Now he thought himself so enriched, that for a month or two he made it his business,
by the strength of his reason, to defend the Truth he had embraced.
But he soon found that this was not sufficient; for self was not subdued under the cross,
and he was not yet come to an experimental knowledge
of what he asserted and defended with words.
In this condition he saw that he must truly become poor in spirit,
if God ever should enrich him with heavenly wisdom.
This brought him to mourning and sorrow,
by which he came more and more to be weaned from his natural knowledge,
wherein he used to delight.
And continuing faithful in this way of self-denial,
he at length began to enjoy peace in his mind,
and so advanced in virtue and real knowledge,
that in time he became an eminent minister of the gospel, and traveling to and fro,
many were converted by his ministry.

About this time appeared in England, one Lodowick Muggleton,
who pretended that he and one John Reeves were the two witnesses which are spoken of. Rev. 11:3.
And though it was not long before Reeves died,
yet Muggleton continued in his wild imaginations, which grew to that degree,
that he gave forth a paper, in which he said, '`That he was the chief judge in the world,
and in passing the sentence of eternal death and
damnation upon the souls and bodies of men.
That in obedience to his commission,
he had already cursed and damned many hundreds of people both body and soul,
from the presence of God, elect men, and angels, to eternity.
That he went by as certain a rule in so doing, as the judges of the land do,
when they give judgment according to law.
And that no infinite Spirit of Christ, nor any god, could,
or should be able to deliver from his sentence and curse,`' etc.
These abominable blasphemies he gave forth in public.

Richard Farnsworth, a zealous and intelligent minister, among those called Quakers,
answered this blasphemer in writing,
and discovered the horribleness of his profane and cursed doctrine and positions;
and he said, among the rest, in a book he published in print,
'`Consider the nature of thy offense, how far it extends itself; and that is,
to pass the sentence of eternal death and damnation,
both upon the bodies and souls of men and women, and that to eternity.
Consider that thy injustice, done by color of office,
deserves to have a punishment proportionable to the offense;
and can the offense in the eye of the Lord be any less than sin against the Holy Ghost,
because thou hast pretended to do it in the name of the Holy Ghost,
and so wouldest make the Holy Ghost the author of thy offense, which it is not?
And seeing thou art guilty of sin against the Holy Ghost,
there is a punishment already proportioned for such an offense;
and also thou art punishable by the law of the land, for presuming,
under pretense of a commission, and as a judge,
to pass the sentence of death upon the bodies of men and women,
and pretending to go by a certain rule in so doing, as the judges of the land do, etc.`'
Thus continued Farnsworth to answer Muggleton at large,
and showed him how his judgment was not only contrary to truth,
but also against the law of the land.
But he was daring enough to give a reply to this serious answer, and said in it,
that he should commend Farnsworth, first, for setting his name to it; and, secondly,
for setting down his words so truly and punctually,
that it made his commission and authority to shine the more bright and clear.
And that he was as true an ambassador of God, and judge of all men`'s spiritual estate,
as any ever was since the creation of the world, '`And if you Quakers, and others,
(thus continued he,) can satisfy yourselves,
that there never was any man commissioned of God to bless and curse,
then you shall all escape that curse I have pronounced upon so many hundreds:
and I only shall suffer for cursing others, without a commission from God.
But my commission is no pretended thing, but as true as Moses`'s, the prophets`',
and the apostles`' commission were.

A multitude more of abominations this blasphemer belched out, and among the rest,
that no man could come to the assurance of the favor of God,
but in believing that God gave this power unto John Reeves and himself.
That he had power given him over all other gods, and infinite spirits whatsoever:
that he, (Muggleton,) had the keys of heaven, and of hell;
and that none could get into heaven, except he opened the gates.
That he had power to remit their sins who received his doctrine,
and to retain and bind their sins more close upon their consciences, for their despising,
or not receiving his doctrine.
That he was single in doctrine, knowledge, judgment, and power, above all men,
either prophets, or apostles, since the beginning of the world,
or that should be hereafter whilst the world doth endure.
That there was no true minister, messenger, nor ambassador of God in the world,
but himself; neither should there be sent any of God after him to the world`'s end.
That a God without him, spoke to him by voice of words, to the hearing of the ear.
That no person condemned by him, could make his appeal unto God, neither by himself,
nor by any other; because God was not in the world at all.
'`This power to condemn, (saith he,) hath God given unto me,
and in this regard I am the only and alone judge,
what shall become of men and women after death;
neither shall those that are damned by me, see any other god or judge but me.`'
I am loth to transcribe more of those most horrible blasphemies;
and we have cause to wonder at the long forbearance of God,
that he thus bore the disdainful affront offered by this inhuman monster,
in defiance of his Almightiness.

This Muggleton said also to Farnsworth,
that because he was not under the sentence of his commission by verbal words, or writing,
he should give answer to his letter.
'`For,
(said he,) I never give answer in writing to any
one that is under the sentence of my commission.`'
This shuffle, not to be bound to answer,
when he had shut up any one under his pretended damnation, seemed comical and facetious.
Yet Farnsworth did not omit to answer his blasphemous positions publicly,
and to show the absurdity of Muggleton, and John Reeve`'s being the two witnesses.

Hereafter I shall have occasion again to make mention of this Muggleton,
for he lived yet several years:
and do not find that any punishment was inflicted on him by the magistrates,
other than the pillory, and half a year`'s imprisonment; though many think,
(not without good reason,) that such blasphemers ought to
be secluded from conversation with men.

Francis Howgill, in the latter part of this year, being in the market at Kendal,
in Westmorland, about his business,
was summoned by the high constable to appear before the justices of the peace at a tavern,
For being a zealous preacher among those called Quakers,
occasion was watched to imprison him under some color of justice, how unjust soever.
Being come to the place appointed, the oath of allegiance was tendered him;
and because for conscience-sake he refused to swear,
they committed him to prison till the assizes at Appleby.
Then appearing at Appleby, the same oath was tendered him in court by the judges;
for not taking of which he was indicted,
only he had liberty to answer to the indictment at the next assizes.
In the meantime there being a jail delivery at Appleby,
he was required to enter into bond for his good behavior:
but well knowing this was only a snare to bring him into further bonds, he refused,
and so was recommitted to prison.
And not being tried till next year, we shall leave him there.

About this time happened a singular case, which I cannot well pass by unmentioned.
One Oliver Atherton, a man of a weak constitution,
having refused to pay tithes to the countess of Derby,
who laid claim to the ecclesiastical revenues of the parish of Ormskirk, where he lived,
was by her prosecution imprisoned at Derby, in a moist and unwholesome hole,
which so weakened him, that after having lain there two years and a half, he grew sick;
and a letter was wrote in his name to the countess,
in which was laid before her not only the cause why he had refused the payment of tithes,
viz. for conscience-sake, but also that his life was in danger,
if he stayed longer in that unwholesome prison:
and that therefore she ought to show compassion,
lest she drew the guilt of innocent blood upon her.

Now though Oliver`'s son, who brought this letter,
met with rough treatment for not uncovering his head,
yet the letter was delivered into her own hands: but the countess continued hard-hearted.
Godfrey, the son, returned to his father in prison, and told him,
(who was now on his death bed,) that the countess would not allow him any liberty.
To which he said, '`She has been the cause of much bloodshed;
but this will be the heaviest blood to her that ever she spilt.`'
And not long after he died.
His friends having got his corpse, carried it to Ormskirk, but at Garstang, Preston,
and other towns they past, they fastened to the market cross the following inscription,
which also had been put on his coffin.

'`This is Oliver Atherton from the parish of Ormskirk,
who by the countess of Derby had been persecuted to death,
for keeping a good conscience towards God and Christ, in not paying of tithes to her.`'

Now though three more, who with him were imprisoned for the same cause,
gave notice of this to the countess, that they might not likewise die in prison,
as their fellow prisoner had, yet she would show no pity;
and threatened to accuse those at Garstang, to the king and his council,
for having suffered the putting up of the said inscription.
But by this she opened people`'s mouth`'s the more,
and an omnipotent hand prevented the executing of her threatening;
for exactly three weeks after the day Atherton was buried, she died.

This year also in October, Humphrey Smith, a preacher among those called Quakers,
having been prisoner a year at Winchester, for his religion,
was by death delivered from his bonds.
He had a vision in the year 1660, in the month called July,
concerning the fire of London, which happened six years after:
a relation of which he gave forth in print.

In the year 1662, being about London, he said to some of his friends,
that he had a narrow path to pass though; and more than once signified,
he saw he should be imprisoned, and that it might cost him his life.
And coming not long after to Alton in Hampshire,
he was taken from a meeting of his friends,
and committed to a stinking close prison at Winchester,
where after a whole year`'s imprisonment, he fell sick;
and in the time of his sickness spoke many excellent words to those about him,
signifying, that he was given up to the will of the Lord either in life or death.
And lying in great weakness, he said, '`My heart is filled with the power of God.
It is good for a man at such a time as this, to have the Lord to be his friend.`'
At another time he was heard to say, '`Lord, thou hast sent me forth to do thy will,
and I have been faithful unto thee in my small measure,
which thou hast committed unto me; but if thou wilt yet try me further,
thy will be done.`'
Also he said, '`I am the Lord`'s, let him do what he will.`'
Not long before his departure he prayed very earnestly, saying, '`O Lord,
hear the inward sighs and groans of thine oppressed,
and deliver my soul from the oppressor.
Hear me, O Lord, uphold and preserve me.
I know that my Redeemer liveth.
Thou art strong and mighty, O Lord.`'
He also prayed to God, that he would deliver his people from their cruel oppressors.
And for those that had been convinced by his ministry,
that the Lord would be their teacher.
He continued quiet and sensible to the last period of his life,
dying a prisoner for bearing witness to truth;
and thus he stepped from this troublesome and transitory life,
into one that is everlasting.
