== Chapter XVI.

=== 1664-1667

[.chapter-synopsis]
* Continuation of persecution under the Conventicle Act
* Account of the Author`'s Parents
* "`Epistle to the Friends of Truth`"
* Six hundred Friends in the jails of England
* Some of those banished set ashore by the Captains of Vessels
* Vessels not allowed to sail to the West Indies without taking banished Quakers
* Plague in London
* Further trials and banishment of Quakers
* I. Penington on Persecution
* G. Fox and Margaret Fell again brought to trial and premunired
* Removal of G. Fox to Scarborough Castle
* Interesting interviews
* Incidents in the life of W. Dundas
* Death of W. Caton
* Death of many banished Friends on board ship
* Captured by a Privateer
* G. Fox and Dr. Cradock
* G. Fox released
* Great fire in London
* T. Ibbitt
* Epistle of S. Crisp
* Persecution by W. Armorer
* Death of R. Farnsworth
* Robert Barclay
* Persecutors of M. Halhead

Again, in December, twelve of those called Quakers, were condemned to banishment;
for it was resolved to go on, not regarding what George Bishop gave forth in print,
and caused to be delivered to the king and the members of parliament, being as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To the King and both Houses of Parliament, thus saith the Lord.

Meddle not with my people, because of their conscience to me,
and banish them not out of the nation because of their conscience; for if ye do,
I will send my plagues upon you, and ye shall know that I am the Lord.

Written in obedience to the Lord, by his servant,

[.signed-section-signature]
George Bishop.

[.signed-section-context-close]
Bristol, the 29th of the Fifth month, 1664.

--

The fulfilling of this prediction we shall see;
for within a short time a war ensued with the Dutch,
and the pestilence appeared at London; but before it broke out,
yet more of the imprisoned Quakers were condemned to banishment,
viz. two and thirty persons, both men and women,
who were sentenced by the court on the 6th, 14th, and 15th of December;
for whatever they said in defense of themselves, proved ineffectual.
One asked.
If we meet really to worship God, must we suffer for that?
And judge Hide answered,`'Yes, that you must.`'
But judge Keeling, to mend the matter a little, said,
'`You shall not suffer for worshipping God,
but for being at an unlawful assembly contrary to the law.`'
Another said, I meet to worship the eternal God in Spirit,
as he persuades my heart and conscience; and must I be condemned to banishment for that?
'`Yes, yes,`' said judge Keeling, '`for the law is against it.`'
To which judge Twisden added, '`He hath confessed that he was there to worship God;
and their worship is contrary to the liturgy of the church of England.`'
Thus we see, if there was but evidence that the prisoners had been at a meeting,
this was counted sufficient to condemn them.
A woman being asked, what she had to say to the evidence given, answered,
'`Be it known unto you all, if I had as many bodies as hairs on my head,
I could lay them all down for the living eternal truth of the living God.`'
After all the prisoners had been called to the bar,
they were at length sentenced to be transported to Jamaica,
and to remain there seven years.

This year in September died my mother, Judith Zinspenning at Amsterdam in Holland,
where she was born of religious parents among the Baptists,
into whose society her father Conrad Zinspenning was entered in a singular manner;
of which, though it may seem somewhat out of my road,
yet because of the remarkable steps of Providence appearing therein,
I will give a short account.
He being of Cologne in Germany, was bred a Papist;
and after he had past the Latin schools, his father thrust him into a cloister;
(for Papists used to think it meritorious to offer up one of their children to
the clergy.) But he found the monastical life so much against his inclination,
that his father dying before the probation year was expired,
he begged his mother to assist him in his intention to leave the fraternity,
since he was not yet bound by vow.
She complied with his desire, and so he got out, and then he was put to a trade.
After he had served his time, he resolved to travel, and first took a turn to Holland,
from thence to France, and then to Italy, and the metropolis Rome, and so back again.
Having been a lay-friar,
he got letters of recommendation to such monasteries as
were of the order of those monks he had lived with;
that so he might freely find lodging there for sometime.
And because in Holland there are no cloisters,
he was recommended to some eminent Papists at Amsterdam: whither being come,
he liked the place so well, that he resolved to stay there sometime; which he did,
after having found employment.
And thus getting into acquaintance, he came in time to live with a Baptist,
who employed him as a journeyman.
He never till now met with the New Testament, in which he began to read so eagerly,
that the Lord cooperating by his good Spirit, his understanding came to be opened,
so that he got a clear sight of the superstition and errors of the popish religion,
in which he was trained up; and then entering into discourse with his master,
was persuaded to renounce popery, and to enter into the communion of the Baptists.
This broke all his measures concerning his intended travels;
and then resolving to settle where he was, he took to wife one Catharine de Mol,
a virtuous maid,
whose father was one of the primitive Baptists that arose under the persecution in Flanders,
from whence he with many more came to settle in Holland.

From these parents my mother descended, who was religiously inclined even from her youth,
and became so well versed in the Holy Scriptures;
and was so diligent in writing down so much of the sermons she heard,
as she could retain by memory; that her father said sometimes,
'`It is a pity that this girl is not a boy,
who then in time might become an eminent instrument in the church.
After she was come to age, though much inclined to lead a single life,
yet at length she was married to my father, Jacob Williamson Sewel,
a very religious young man; whose father William Sewel,
from Kidderminster in Worcestershire, having been one of those Brownists,
that left England and settled in Holland, married a Dutch wife at Utrecht,
where my father was born; who being come to age, endeavored to walk in the narrow way,
and conversed mostly with the strictest professors of those days.
And both he and my mother came in time to grow dissatisfied
with that worship to which they were joined;
yet in clearness of understanding my mother exceeded my father;
nevertheless she continued dissatisfied as well as he,
with the common way of worship she belonged to; so that oftentimes,
when she came from the meeting-house, she resolved not to go there any more,
because she reaped no real and substantial benefit by it.
But then the first day of the week being come again, she was in a straight,
thinking that however it was,
yet by the apostle we were exhorted not to forsake the assemblies.
In this irresolute condition she continued a long time;
and being incumbered with the cares of the family,
she was not so much at liberty for performing religious duties, (viz. prayers,
reading of, and meditating on the Holy Scriptures, visiting the sick,
and such like pious exercises,) as she was before she was married;
which made her wish sometimes she had never entered into matrimony,
and that she might live to enjoy again that peace and quiet which once she had.
But she knew not yet that it was the love of the Lord thus working upon her,
to draw her off from transitory things.
In this state she was often seized with grief and sorrow,
so that she counted herself the most miserable of women;
for neither husband nor children, nor any outward enjoyments,
could afford her any pleasure; but all her desire was to attain to an undefiled state,
in which she might live an unblamable life, not only before men, but also before God;
for feeling there was yet something in her which was evil and polluting,
she struggled to overcome it; but all her labor proved in vain.
This made her cry earnestly to the Lord as one in great danger;
and her doubts whether it was possible to attain to perfection increased.
But in this forlorn state it pleased the Lord to manifest himself to her in some measure,
though she knew not then it was he.
And often she cried out,
'`Lord what will it avail me to know that thou hast sent thy Son into the world,
and that he was crucified and died for the sins of the world, if I am not saved by it.
Lord forgive my sins, and have mercy upon me.`'
And once when she was alone, pouring out her heart before the Lord,
he made himself known to her, and spoke to her soul, that if she would be perfect,
she must follow the light in every respect.
Having heard this, she desired to know what this light was; and the Lord showed her,
that the light was the life of men.
This she understood in some degree,
and so separated herself as much as ever she could conveniently from conversation,
endeavoring to live retiredly.
And having about this time heard Dr. Galenus Abrahams, an eminent Baptist teacher,
preach upon the parable of the seedsman; that which he spoke concerning the good ground,
and how the ground must be fitted by the Lord`'s working, so affected her,
that she resolved to rest from all her own labor;
and so she left frequenting the Baptists`' assemblies any more.

In this retired state she continued a good while,
and at length came to hear William Ames preach;
and he declaring the light of Christ as the true teacher,
this agreed with what had already been told her inwardly
by the immediate manifestations of the Lord to her.
And thus she came fully to be convinced that this
was the truth she had so long desired to know.
Now she saw that it was her duty to give up all, and to keep nothing back:
for she had already seen, that if she would be Christ`'s disciple, she must forsake all,
even her own self.
But a fear of the cross was no small impediment to her; yet now she gave up to obedience;
and saw that her former performances had been defective;
and now all came into remembrance.
This caused sorrow; but she prayed to the Lord both night and day,
and then he manifested his power by which she was led out of the darkness and bondage,
wherein she had been held captive; and her supplication was to the Lord,
that it might not be with her as formerly, to wit, sometimes great zeal,
and then coldness again; but that she might continue in fervency of spirit.
After a long time of mourning the Lord manifested his kindness to her,
by which she came to be quickened and refreshed;
and by the judgments of the Lord all was narrowly searched out,
so that nothing could be hid;
and a separation was made between the precious and the vile, and death passed over all.
But thus to part with all her own wisdom, and forsake her great attainments,
was no small cross: But she became willing to bear it,
although many violent tempests rose to draw her off, if possible,
from closely adhering to the beloved of her soul; yet she was not forward in imitation:
for my father, who when he was convinced of the truth preached by W. Ames and W. Caton,
soon left off the common way of salutation,
would sometimes persuade her by arguments to do so too; but she told him,
if the leaving off of that custom was a thing the Lord required,
she believed he would show it her in his own time,
because she was given up to follow his requirings.
And so the Lord did in due time; and she continuing zealously faithful,
he was pleased after my father`'s death to give her a public testimony,
and she became eminently gifted:
for her natural abilities surpassing the ordinary qualifications of her sex,
and becoming sanctified by the Spirit of the Lord, could not but produce good effects;
and she came to be much visited and sought to by professors;
and the Fifth monarchy-men applauded her because of her pathetical admonitions.
But she was above flattery, and trampled upon it.
Nay, she was so well esteemed, that I remember,
having some movings to visit the collegians in their meeting,
after one of them had left off speaking, she stood up, and said,
that she had something upon her mind to speak to them by way of exhortation.
But knowing that they suffered not women to speak amongst them,
she was not willing bluntly to intrude herself; but desired their leave,
which they readily granted, and one of their chief speakers said to her, '`It is true,
friend, we do not allow women to speak in the church; yet we bear that respect to you,
that we give you the liberty of speaking.`'
And then she cleared herself, having formerly been a frequenter of that assembly.
And when she had done speaking, I do not remember she was contradicted by any;
but one of their speakers concluded the meeting with a prayer.

Before that time she wrote and published a small book to those of her former society,
which she called [.book-title]#A Serious Reproof of the Flemish Baptists:#
in which she dealt very plainly with them; and showed how they were apostatized.
She wrote also some other treatises, extant in print;
and was much beloved and well esteemed by English friends,
as appears by several letters written to her from England, and yet extant.
Those of her own nation often resorted to her for instruction,
she being so well exercised in the way of the Lord,
that she was able to speak a word in season to various conditions.
Many times she visited the meetings at Alkmaar, Haarlem and Rotterdam;
and was often invited by her friends to come and edify them with her gift.
She wrote also many letters for edification and admonition to particular persons,
and some epistles also to the church.
But it pleased the Lord to take her early to himself.
When she fell sick, she soon had a sense that she was not like to recover,
and therefore spoke much to me in private,
and acquainted me with several things touching myself,
and relating to her outward estate.
And the night before she departed, she called me to her bedside,
and exhorted me very fervently to depart from evil, and to fear the Lord:
which by the mercy of God in time, made very deep impressions on my mind;
so that still I find reason to bless the name of the Lord for having
been pleased that I was the son of such an excellent mother:
who early in the morning when she felt death approaching, called me up out of my bed,
and sent me to her brother, and to W. Caton, to come and see her;
and I had hardly been returned a quarter of an hour before she departed this life,
and slept in peace, to my great grief then; though afterwards,
when I came to years of discerning,
I saw reason to believe that it was not without a
singular providence that the Lord had taken her away:
for one had long continued to be an importunate suitor to her,
who in time lost his integrity.
To give a small instance of her true zeal for God,
I will insert here the following epistle she wrote to her friends,
to stir up the pure mind in them.

[.embedded-content-document.epistle]
--

[.letter-heading]
AN EPISTLE TO THE FRIENDS OF THE CHURCH.

Grace and peace be multiplied among you, my dearly and much beloved friends,
you that have received a blessing from God the heavenly Father in Christ Jesus,
the Lord of glory; who by his unspeakable love, and his unchangeable light,
hath drawn you off from the imaginary worships,
and brought you in measure to know him who was from the beginning.
Dear friends, keep in the light by which ye are enlightened, and in the knowledge of God,
which every one hath received for himself; watching against the seducings of Satan,
that your eyes may be kept open, lest deceit should prevail in any of you,
by which truth might lose its splendor, and the brightness of the Lord become darkened.

I write these things to you in true love, and though but young,
yet as one that takes care for you;
for the Lord knows how often ye are in my remembrance; desiring for you,
that ye may not only know the truth,
but that ye may be found to be living witnesses of it: for I,
knowing the preciousness of it,
cannot but desire that others may also participate of the same; labor, therefore, for it,
my friends, that so, when the Lord comes and calls to an account,
every one may be found faithful according to what he hath received:
for this is the talent which the Lord hath given, viz. the knowledge of him who is true,
and who rewards every one according to his deeds:
but the negligent and slothful servant said that his Lord was a hard man,
and that he gathered where he had not strewed, and this was his condemnation:
for the Lord said, "`Thou knew that I was an austere man;
wherefore then gave not thou my money into the bank,
that at my coming I might have required mine own with usury?`" Mind these things,
my beloved friends, ye that have an ear to hear,
and dig after this parable in yourselves; for we all have received talents, some more,
and others less.
Let therefore every one be faithful to the Lord, according to what he hath received;
for truly some of you, I believe, have received five talents.
Let it but be duly considered and seen in the light of the Lord,
what knowledge ye have had of the eternal God beyond many,
even when ye were yet in darkness: how often hath the Lord appeared,
and clearly made manifest himself?
And how abundantly hath he made it known in the heart,
that he it was who was worthy to be feared and served?
Certainly that is a great and weighty talent, and therefore the Lord may say justly,
what could I have done more to my vineyard?
O my friends, besides all this,
he hath caused his eternal light to shine into our hearts,
whereby we have seen the corrupted ways of the world, and paths leading to death.
This, I say, the Lord hath showed us by his eternal light:
glory and praises be given to our God forever.

Dear friends, go on in that in which ye have begun; for I can bear witness for the Lord,
that his love hath been abundantly shed abroad upon us, without respect of persons:
because those that fear him, and work righteousness, are acceptable to him;
and he makes his truth manifest among us, and causes his peace and mercy to rest upon us.
It is true, that Satan doth not rest to scatter this,
and to sow doubts and unbelief in our hearts; but we keeping close to the Lord,
are preserved from his snares;
and happy is he who hath found a place where he is freed from tempests:
but before this place be found, there are many hidden rocks that may be struck on,
not unknown to me.
And therefore I have true compassion on those who are not past them all yet;
for shipwreck may easily be suffered on any of these.

Yet in all this danger there is something on which we may rely safely,
and to which we may trust, being as a beacon, viz. the light shining into our hearts,
though it be sometimes but as a spark, and so small, in regard of the manifold seducings,
that it can hardly be discerned.
Here then is no small grief and anguish; here all the mercies of the Lord,
which formerly we enjoyed abundantly, are called in question, or doubted of;
here is danger, and yet certainty; for by not sinning, the beacon is minded,
and by relying on a true hope to be saved, we are preserved in the tempest.
I write these things for the information of those
that are traveling towards a city that hath a foundation,
and whose builder and maker is God; for to such my love is extended,
and my desire to the Lord for them is, that they may be kept by his power,
to remain standing at his coming.

Dear friends, keep your meetings in the fear of the Lord,
and have a care that your minds are not drawn out to hear words outwardly;
but stand in the cross to that which desires refreshment from without:
and when at any time ye feel but little refreshment,
let it not enter into your hearts that the Lord is not mindful of you;
but centre down into yourselves, in the pure light, and stand still therein:
then it may be ye will find the cause why the presence
of the Lord is departed from you for some time;
and ye putting away the cause, shall enjoy the Lord again to your comfort.

May God Almighty preserve you all by his powder,
lest any strife or discord be found among you; and may you grow up in love,
and thereby be obliged to bear each other`'s burdens;
and let no transitory things cumber your hearts, but be resigned to the Lord;
for that to which we are called, is not to be compared to that which is transitory,
or perishing; since it is a treasure that is everlasting, and to which the world,
and all that is in it, is but as dung;
because the most glorious part of it is but vanity of vanities.
O, my friends,
let none be stopped by that which is an impediment to entering into the kingdom of heaven;
but strive all to enter the narrow gate; and search every one of you your own hearts,
with the light ye are enlightened with, which shall manifest your own states to you;
and keeping there, it shall multiply your peace,
and every one shall find therein his own teacher,
as those have experienced who sought the Lord with all their heart.
Now the God of all mercies, who alone is immortal, keep you and us altogether to the end;
that so in these dangerous times we may remain standing, to the glory of his great name.
O friends, keep out craftiness,
and enter not readily into discourse with those that are out of the truth;
for they speak in their own wills, and are crafty, and, knowing no bridle to their mind,
it produces that by which the simple and innocent are caught; but stand ye rather,
and keep in that wherein ye see their subtlety; for then,
though ye may not have a word to apologize for yourselves, yet ye shall he above them.

This is written from me, a young plant, in love to you,
according to the gift received from the Lord.
My salutation is to you all in the light of truth.

[.signed-section-signature]
Judith Zinspenning.

--

In the year 1664 came forth a small book in print, to the king,
and both houses of parliament, wherein were set forth,
not only the violent persecution almost over all England, with the names of persons,
places, and cases, which indeed were woful, and some bloody; but it was also represented,
that there were at that time in prison above six hundred of those called Quakers,
merely for religion`'s sake.

In the month called January, in the year 1664-5, thirty-six of that persuasion,
among which were eight women, were condemned to be transported to Jamaica.
The jury not being so forward to declare the prisoners guilty as the court desired,
were persuaded however by the threatenings of judge Keeling, the recorder Wild,
and the boisterous Richard Brown, to do what was demanded of them.

On the 18th and 22d of the next month,
thirty-four of the said people were sentenced to be carried to Jamaica,
and five to Bridewell.
The manner of their trial I pass by with silence, to avoid prolixity.
Those that were tried on the 18th were sentenced by judge Wharton;
and those on the 22d by judge Windham, who said to Anne Blow, who declared,
that the fear of the Lord being upon her heart,
she durst not conform to any thing that was unrighteous, '`Anne Blow,
I would show you as much favor as the court will allow you,
if you will say that you will go no more to that seditious meeting,`' meaning the Bull-and-Mouth.
To which she answered,
'`Wouldest thou have me sin against that of God in my own conscience?
if I were set at liberty to day, if the Lord required it of me,
I should go to the Bull-and-Mouth tomorrow.`'

Concerning one John Gibson, the said judge spoke to the jury in this manner: '`Gentlemen,
although it is true, as this Gibson saith,
that it cannot be proved that they were doing any evil at the Bull-and-Mouth;
yet it was an offense for them to be met there,
because in process of time there might be evil done in such meetings:
therefore this law was made to prevent them.`'
By this we may see with what specious colors the persecutors cloaked their actions.
I find among my papers, a letter of John Furly, and Walter Miers,
(both of whom I knew well,) mentioning, that some of the jury,
for refusing 1o give such a verdict as was required of them, were fined in great sums,
and put into prison, there to remain till they should pay the fine.

Having now said thus much of sentencing, it grows time to speak of the execution thereof.

Some of the persons ordered for banishment, fell sick, and died in prison;
some became apostates, and some were redeemed by their relations that were not Quakers;
but yet a considerable number was, though with great pains, brought on ship-board,
to be transported to the West Indies.
We have seen already how those that were sentenced at Hertford,
by judge Orlando Bridgman, having been put ashore by the master of the ship, returned.
And it was not long after, that three of their friends,
being on board the ship the Many-fortune of Bristol,
were also set on shore with a certificate from the master of the ship,
signed by him and seven of his men, wherein they complained of their adversity, and said,
that God had said as it were in their hearts.
"`Accursed be the man that separates husband and wife;
and he who oppresses the people of God, many plagues will come upon him.`"

But the first of those called Quakers, who really tasted banishment, were Edward Brush,
and James Harding, who were banished, not only out of London,
where they as citizens had as much right to live as the chiefest magistrates,
but also out of their native country, contrary to the right of a freeborn Englishman:
these, with one Robert Hays, were on the 24th of the month called March,
early in the morning fetched from Newgate in London, and brought to Blackfriars`' stairs,
where they were put into a boat, and so carried down to Gravesend,
and there had on board a ship.
Hardly any warning had been given to these prisoners; and Robert Hays being sickly,
had taken some physic, which had not done working;
and since it was very cold that morning,
and he had got nothing to eat before he came to Gravesend,
he was seized in the ship with so severe sickness, that he died of it,
and then his corpse was carried to London, and there buried.
The other two were carried to Jamaica, where, by the providence of God,
in time it fared well with them, and Edward Brush lived to return into England.
It was remarkable, that not long after these persons were banished,
the pestilence broke out at London,
first of all in the house of a meal-man in Bearbinder-lane,
next door to the house where the said Edward lived,
which by some was thought worthy of being taken notice of;
since that house was the first which was shut because of the sickness.

With the other prisoners they had more trouble and pains,
because no shipmasters could be found that would carry them:
wherefore an embargo was laid on all merchantmen,
with order that none should go down the river without having a pass from the Admiral;
and this they would give to no master going to the West Indies,
unless he made promise to carry some Quakers along
with him to the place to which they were banished.
Whatever any masters spoke against this, intimating that there was a law,
according to which no Englishman might be carried
out of his native country against his mind,
was in vain.
At length by force they got one to serve their turn;
and then seven persons that were sentenced to banishment, were,
on the 18th of the month called April, carried from Newgate to Blackfriars`' stairs,
and so in a boat to Gravesend.
But in the meantime the pestilence increased, and not long after judge Hide,
who had been very active in persecuting, was, with many others,
suddenly taken away out of this life;
for he having been seen in the morning at Westminster in health,
as to outward appearance,
it was told in the afternoon that he was found dead in his chamber;
being thus summoned to appear and give account of his deeds
before a higher court than ever he presided in.

Yet transportation was not come to a stand; first, as hath been said, three persons,
next seven, and on the 16th of the month called May,
eight were carried down the river to Gravesend, and put on ship-board;
but as the number of those that were carried away was heightened,
so also the number of those that died of the pestilence much more increased.
But notwithstanding this scourge from Heaven, transportation continued;
for a master of a ship was found at length, who had said, as was reported,
that he would not stick to transport even his nearest relations.
And so an agreement was made with him,
that he should take between fifty and sixty Quakers into his ship,
and carry them to the West Indies.
Of these eight or ten at a time were brought to the waterside,
and so with boats or barges carried to the ship, which lay at anchor in the Thames,
in Bugbey`'s-hole, a little beyond Greenwich.
Many of these prisoners, among which several women,
not showing themselves ready to climb into the ship,
lest it should seem as if they were instrumental to their transportation,
were hoisted up with the tackle; and the sailors being unwilling to do this work,
and saying, that if they were merchants`' goods,
they should not be unwilling to hoist them in, the officers took hold of the tackle,
and said, '`They are the king`'s goods.`'
This was on the 20th of the month called July, and on the 4th of the next month, when,
according to the bill of mortality, three thousand and forty died in one week,
the rest of the banished prisoners were carried with soldiers to the said ship,
in which now were fifty-five of the banished Quakers, and among these eighteen women.
But something adversely hindered this ship from going away,
and the pestilence also entered into it, which took away many of the prisoners,
and so freed them from banishment.
But though the pestilence grew more hot at London,
and that a war was risen between England and Holland,
yet the fire of persecution continued hot,-and great rejoicings
were made when the Dutch were beaten at sea,
and their admiral Obdam was blown up with his ship.
Neither did the persecutors leave off`" to disturb the meetings of those called Quakers,
and imprison many of them; nay, so hardened and unrelenting were some,
that when at London more than four thousand people died in one week, they said,
that the only means to stop the pestilence, was to send the Quakers out of the land.
But these fainted not, but grew emboldened against violence.
In September some meetings were still disturbed at London,
though the number of the dead in one week was heightened to above seven thousand,
being increased in that time nigh two thousand.
Now such as intended to have met at the Bull-and-Mouth,
were kept out from performing worship there; but yet meeting in the street,
they were not disturbed; for there seemed to be some fear of the common people,
who grew discontented because there was little to be earned by tradesmen;
and the city came to be so emptied,
that grass grew in the streets that used to be most populous,
few people being seen by the way.
Thus the city became as a desert, and the misery was so great,
that it was believed some died for want of attendance.

It was about this time that Samuel Fisher,
who first had been a prisoner in Newgate at London, and afterwards in Southwark,
since the beginning of the year 1663, till now, being about a year and a half,
died piously.

It is reported that the king, in the time of this great mortality, once asked,
whether any Quakers died of the plague?
And having been told, yes, he seemed to slight that sickness, and to conclude,
that then it could not be looked upon as a judgment or plague upon their persecutors.
But certainly his chaplains might well have put him in mind of what Solomon saith,
"`There is one event to the righteous and to the wicked:`" and of this saying of Job,
"`He destroys the perfect and the wicked:`" as also that of the prophet,
"`That the righteous is taken away from the evil to come.`"

Now traveling in the country was stopped,
which made some people go with boats along the coast,
and so went ashore where they had a mind.
Thus did Stephen Crisp, who came about this time to York,
where the duke of York was then, with many of the great ones.
About this time Alexander Parker, and George Whitehead came to London,
where they had good service in preaching the truth.

Great fires were now kindled in the streets to purify the contagious air;
but no relief was found by it;
for in the latter end of September there died at
London above eight thousand people in one week,
as I remember to have seen in one of the bills of mortality at that time.
In the meanwhile the ship in which the banished prisoners were, could not go off,
but continued to lie as a gazing-stock for those ships that passed by;
for the master was imprisoned for debt.

Now the prediction of George Bishop was fulfilled,
and the plagues of the Lord fell so heavily on the persecutors,
that the eagerness to banish the Quakers, and send them away, began to abate.
The same G. Bishop about Mid-summer, wrote from the prison at Bristol,
(where he made account that he also should have been banished,)
a letter to his friends to exhort them to steadfastness,
foretelling them, that if they happened to be banished,
God would give them grace in the eyes of those among whom they should be sent,
if they continued to adhere to him; and that when he should have tried them,
he should bring them again into their native country; and that none should root them out;
but they should be planted and built up there;
and that the Lord should visit their enemies with the sword and pestilence,
and strike them with terror.
This is but a short hint of what he wrote at large.

G+++.+++ Fox, the younger, had also in the year 1661 given forth a little book,
of which some small mention hath been made before, in which he lamented England,
because of the judgments that were coming upon her
inhabitants for their wickedness and persecution;
saying among the rest, that the Lord had spoken in him concerning the inhabitants,
'`The people are too many, the people are too many, I will thin them, I will thin them.`'
Besides that the spirit of the Lord had signified unto him, that an overflowing scourge,
yea even an exceeding great and terrible judgment, was to come upon the land,
and that many in it should fall, and be taken away.
And that this decree of the Lord was so firm,
that though some of the Lord`'s children and prophets
should appear so as to stand in the gap,
yet should not that alter his decree.
This with much more he wrote very plainly; and though he was deceased long ago,
yet this paper was reprinted,
to show the inhabitants how faithfully they had been warned.

What Isaac Penington, being a prisoner, wrote about this time to the king and parliament,
and published in print, was also very remarkable,
being designed with Christian meekness to dissuade them if possible
from going on with this mischievous work of persecution.
In this paper, containing some queries, among many weighty expressions,
I find these also:

[.embedded-content-document.paper]
--

After ye have done all ye can, even made laws as strong as ye can,
and put them in the strictest course of execution ye can,
one night from the Lord may end the controversy,
and show whether we please the Lord in obeying him,
or ye in making laws against us for our fidelity and obedience to him.

As the Lord is able to overturn you, so if ye mistake your work,
misinterpreting the passages of his providence,
and erring in heart concerning the ground of his former displeasure; and so,
through the error of judgment, set yourselves in opposition against him,
replanting the plants which he will not have grow,
and plucking up the plants of his planting; do ye not in this case provoke the Lord,
even to put forth the strength which is in him against you?
We are poor worms.
Alas, if ye had only us to deal with, we should be nothing in your hands!
But if his strength stand behind us, we shall prove a very burdensome stone,
and ye will hardly be able to remove us out of the place wherein God hath set us,
and where he pleases to have us disposed of And happy were it for you,
if instead of persecuting us,
ye yourselves were drawn to wait for the same begettings of God, which we have felt,
out of the earthly nature into his life and nature,
and did learn of him to govern in that; then might ye be established indeed,
and be freed from the danger of those shakings, and over-turnings,
which God is hastening upon the earth.

Now, because ye may be apt to think, that I write these things for my own sake,
and the sakes of my friends and companions in the truth of God,
that we might escape the sufferings and severity which we are like to undergo from you,
and not so mainly and chiefly for your sakes,
lest ye should bring the wrath of God and misery upon your souls and bodies;
to prevent this mistake in you, I shall add what follows.
Indeed this is not the intent of my heart: for I have long expected,
and do still expect this cup of outward affliction and persecution from you,
and my heart is quieted and satisfied therein,
knowing that the Lord will bring glory to his name, and good to us out of it:
but I am sure it is not good for you to afflict us
for that which the Lord requires of us,
and wherein he accepts us;
and ye will find it the bitterest work that ever ye went about,
and in the end will wish that the Lord had rather never given you this day of prosperity,
than that he would suffer you thus to make use of it.
Now that ye may more clearly see the temper of my spirit,
and how my heart stands to this thing, I shall a little open unto you,
my faith and hope about it, in these ensuing particulars:

[.numbered-group]
====

[.numbered]
_First,_ I am assured in my heart and soul, that this despised people, called Quakers,
is of the Lord`'s begetting in his own life and nature.
Indeed, had I not seen the power of God in them,
and received from the Lord an unquestionable testimony concerning them,
I had never looked towards them: for they were otherwise very despicable in my eyes.
And this I cannot but testify concerning them,
that I have found the life of God in me owning them,
and that which God hath begotten in my heart, refreshed by the power of life in them:
and none but the Lord knows the beauty and excellency of glory,
which he hath hid under this appearance.

[.numbered]
_Secondly,_ The Lord hath hitherto preserved them against great oppositions,
and is still able able to preserve them.
Every power hitherto hath made nothing of overrunning them; yet they have hitherto stood,
by the care and tender mercy of the Lord;
and the several powers which have persecuted them, have fallen one after another.

[.numbered]
_Thirdly,_ I have had experience myself of the Lord`'s goodness and preservation of me,
in my suffering with them for the testimony of his truth,
who made my bonds pleasant to me, and my noisome prison,
(enough to have destroyed my weakly and tenderly
educated nature,) a place of pleasure and delight;
where I was comforted by my God night and day, and filled with prayers for his people,
as also with love to, and prayers for,
those who had been the means of outwardly afflicting me,
and others on the Lord`'s account.

[.numbered]
_Fourthly,_ I have no doubt in my heart that the Lord will deliver us.
The strength of man, the resolution of man is nothing in my eye in compare with the Lord.
Whom the Lord loves, he can save at his pleasure.
Hath he begun to break our bonds and deliver us, and shall we now distrust him?
Are we in a worse condition than Israel was, when the sea was before them,
the mountains on each side, and the Egyptians behind pursuing them?
He indeed that looks with man`'s eye, can see no ground of hope,
nor hardly a possibility of deliverance; but, to the eye of faith,
it is now nearer than when God began first to deliver.

[.numbered]
_Fifthly,_ It is the delight of the Lord, and his glory to deliver his people,
when to the eye of sense it seems impossible.
Then doth the Lord delight to stretch forth his arm, when none else can help:
and then doth it please him to deal with the enemies of his truth and people,
when they are lifted up above the fear of him,
and are ready to say in their hearts concerning them, they are now in our hands,
who can deliver them?

====

Well, were it not in love to you, and in pity,
in relation to what will certainly befall you, if ye go on in this course,
I could say in the joy of my heart, and in the sense of the good-will of my God to us,
who suffers these things to come to pass; go on, try it out with the spirit of the Lord,
come forth with your laws, and prison, and spoiling of our goods, and banishment,
and death, if the Lord please, and see if ye can carry it:
for we come not forth against you in our own wills,
or in any enmity against your persons or government,
or in any stubbornness or refractoriness of spirit;
but with the lamb-like nature which the Lord our God hath begotten in us,
which is taught, and enabled by him, both to do his will,
and to suffer for his name-sake.
And if we cannot thus overcome you, even in patience of spirit, and in love to you,
and if the Lord our God please not to appear for us,
we are content to be overcome by you.
So the will of the Lord be done saith my soul.

--

This the author concludes with a postscript,
containing a serious exhortation to forsake evil.
Besides this he gave forth another paper,
wherein he proposed this question to the king and both houses of parliament:
Whether laws made by man, in equity,
ought to extend any further than there is power in man to obey.
And if it was not cruel to require obedience in such cases,
wherein the party hath not a capacity in him of obeying.`'
And to explain this a little further,
he said, '`In things concerning the worship of God, wherein a man is limited by God,
both what worship he shall perform, and what worship he shall abstain from,
here he is not left at liberty to obey what laws shall be made by man contrary hereunto.`'
Thus Penington strove by writing to show the persecutors the evil of their doings:
but a fierce party prevailed then:
and the clergy continually blew the fire of persecution; nay,
many presumed the time was now come totally to destroy the Quakers;
and in December twelve more were condemned to transportation.

Concerning those banished that were now in the ship which lay in the Thames,
I will yet leave them there, and take again a view of George Fox,
whom in the foregoing year we left in a hard prison at Lancaster.
In the month called March this year he was brought again to his trial before judge Twisden;
and though judge Turner had given charge at the assize before,
to see no such gross errors were in the indictment as before,
yet in that respect this was not much better than the former,
though the judge examined it himself.
The jury then being called to be sworn, and three officers of the court having deposed,
that the oath had been tendered to him at the last assizes, according to the indictment,
the judge said, it was not done in a corner: and then asked him,
what he had to say to it; and whether he had taken the oath at the last assizes?
George Fox thereupon gave an account of what had been done then, and that he had said,
that the book they gave him to swear on, saith.
"`Swear not at all.`" And repeating more of what he spoke then, the judge said,
'`I will not dispute with you but in point of law.`'
George Fox offering to speak something to the jury concerning the indictment,
he was stopped by the judge; and then George Fox asked him,
whether the oath was to be tendered to the king`'s subjects only,
or to the subjects of foreign princes`'? The judge replied,`'To the subjects of this realm.`'
'`Well,`' said he, '`look to the indictment,
and thou mayest see that the word subject is left out of this indictment also.`'
Several other great errors as to time, etc. he had observed in the indictment,
but no sooner had he spoke concerning the errors, but the judge cried,
'`Take him away jailer, take him away.`'
Then he was hurried away; yet the people thought he should have been called again;
but that was not done.
After he was gone, the judge asked the jury, whether they were agreed?
They said, '`Yes,`' and found for the king against him.
The reason why George Fox was led away so suddenly,
seemed to be that they expected he would have proved
the officers of the court to have sworn falsely,
seeing the day on which the oath had been tendered to him at the assizes before,
was wrong in the indictment; and yet they had sworn,
that on that day he had refused to take the oath.
Before George Fox was brought before the judge,
he had passed sentence of premunire against Margaret Fell,
for having refused to take the oath.
And though this sentence had not been passed against George Fox,
yet he was recorded as a premunired person;
though it had not been asked him what he had to say
why sentence should not be pronounced against him.
And thus he continued prisoner in Lancaster castle.

Whilst he was there, though weak of body, he wrote several papers;
but the neighboring justices labored much to get
him removed from thence to some remote place;
for it was pretty well known among the people,
how the court at the assizes had dealt with him.
So about six weeks after,
they got an order from the king and council to remove him from Lancaster;
and they received also a letter from the earl of Anglesey, wherein it was written,
that if these things which he was charged with, were found true against him,
he deserved no clemency or mercy: and yet the greatest matter they had against him,
was his refusal of the oath.
His persecutors now having prepared for his removal, the under sheriff`',
and the head sheriff`'s men, with some bailiffs, came and fetched him out of the castle,
when he was so weak, by lying in that cold, wet, and smoky prison,
that he could hardly go or stand.
So they brought him down into the jailer`'s house where justice William Kirby,
and several others were.
They called for wine to give him, but he well knowing their malice against him,
told them, he would have none of their wine.
Then they cried, '`Bring out the horses.`'
G+++.+++ Fox therefore desired, that if they intended to remove him,
they would first show him their order, or a copy of it.
But they would not show him any but their swords.
He then told them, there was no sentence passed upon him, neither was he premunired,
that he knew of; and therefore he was not made the king`'s prisoner,
but was the sheriff`'s:
for they and all the country knew that he was not fully heard at the last assizes,
nor suffered to show the errors that were in the indictment,
which were sufficient to quash it.
And that they all knew there was no sentence of premunire passed upon him;
and therefore he not being the king`'s prisoner, but the sheriff`'s,
desired to see their order.
But instead of showing him their order, they hauled him out,
and lifted him upon one of the sheriff`'s horses; for he was so very weak,
that he was hardly able to sit on horseback.
Riding thus along the street, he was much gazed upon by the people,
and had great reason to say, that he received neither Christianity, civility,
nor humanity, for how ill and weak soever he was,
yet they hurried him away about fourteen miles to Bentham in Yorkshire;
and so wicked was the jailer, one Hunter, a young fellow,
that he lashed the horse on which G. Fox rode, with his whip, to make him skip and leap,
insomuch that he had much ado to sit him; and then would this wanton fellow come,
and looking him in the face, say, '`How do you Mr. Fox?`'
To which he answered, it was not civil in him to do so.
Yet this malicious fellow seemed little to regard it;
but he had not long time to delight in this kind of insolence;
for soon after he was cut off by death.

G+++.+++ Fox being come to Bentham, was met by a marshal and several troopers,
and many of the gentry, besides abundance of people, come thither to stare at him.
Being entered the house, and very much tired,
he desired they would let him lie down on a bed, which the soldiers permitted;
and the marshal, to whom he was delivered, set a guard upon him.
After having stayed there a while, they pressed horses,
and sending for the bailiff and the constables, they had him to Giggleswick that night.
And there they raised the constables, who sat drinking all night in the room by him,
so that he could get but little rest.
The next day coming to a market town, several of his friends came to see him,
and at night he asked the soldiers, whither they intended to carry him?
To which some said, beyond sea, and others to Tinmouth Castle.
And there was a fear amongst them, lest some should rescue him;
but there was not the least reason for it.
The next night he was brought to York, where the marshal put him into a great chamber,
where many of the troopers then came to him.
He then speaking something by way of exhortation to the soldiers,
many of them were very loving to him.
A while after the lord Frecheville, who commanded those horse, came to him,
and was civil and loving, and G. Fox gave him an account of his imprisonment.

After a stay of two days at York,
the marshal and five soldiers were sent to convey him to Scarborough Castle:
these behaved themselves civilly to him.
On the way they baited at Malton, and permitted his friends to see him.
Afterwards being come to Scarborough, they brought him to an inn,
and gave notice of it to the governor, who sent six soldiers to guard him that night.
The next day they had him into the castle, and there put him into a room,
with a sentinel to watch him.
Out of this room they soon brought him into another, which was so open,
that the rain came in, and it smoked exceedingly; which was very offensive to him.
One day the governor, sir John Croslands came into the castle with one sir Francis Cob.
G+++.+++ Fox desired the governor to come into his room, and see how it was, and so they did:
and G. Fox having got a little fire made in the room, it was so filled with smoke,
that they could hardly find the way out again.
And he being a Papist, G. Fox told him,
that was his purgatory which they had put him into.
For it plainly appeared that there was an intent to vex and distress him:
for after he had been at the charge of laying out about fifty shillings,
to keep out the rain, and somewhat to ease the smoke, they put him into a worse room,
which had neither chimney nor fire-hearth; and lying much open toward the sea-side,
the wind so drove in the rain, that the water not only ran about the room,
but also came upon his bed.
And he having no fire to dry his clothes when they were wet,
his body was so benumbed with cold,
and his fingers swelled to that degree that one grew as big as two.
And so malicious were his persecutors that they would
hardly suffer any of his friends to come at him,
nay, not so much as to bring him a little food;
so that he was forced to hire somebody to bring him necessaries.
Thus he spent about a quarter of a year,
and afterwards being put into a room where a fire could be made,
he hired a soldier to fetch him what he wanted.
He then eat almost nothing but bread, and of this so little,
that a threepenny loaf commonly served him three weeks: and most of his drink was water,
that had wormwood steeped in it; and once when the weather was very sharp,
and he had taken a great cold, he got some elecampane beer.

Now, though he desired his friends and acquaintances might be suffered to come to him,
yet this was refused; but some others were admitted to come and gaze upon him,
especially Papists, of whom a great company once being come, they affirmed,
that the pope was infallible, and had been so ever since St. Peter`'s time.
But G. Fox denied this, and alleged from history, that Marcellinus,
one of the bishops of Rome, denied the faith, and sacrificed to idols;
and therefore was not infallible.
And he said also,`' If the Papists were in the infallible spirit,
they would not maintain their religion by jails, swords, gallows, fires, racks,
and tortures, etc. nor want such means to hold it up by:
for if they were in the infallible spirit, they would preserve men`'s lives,
and use none but spiritual weapons about religion.`'
He also told them how a certain woman that had been a Papist,
but afterwards entered into the society of those called Quakers,
having a taylor at work at her house,
and speaking to him concerning the falseness of the popish religion,
was threatened to have been stabbed by him, for which end he drew his knife at her:
since it was the woman said, the principle of the Papists,
if any turn from their religion to kill them if they can.
This story he told the Papists, and they did not deny this to be their principle,
but asked, if he would declare this abroad.
And he said, '`Yes, such things ought to be declared abroad,
that it may be known how contrary your religion is to true Christianity.`'
Whereupon they went away in a rage.
Some time after another Papist came to discourse with him, and said,
that all the patriarchs were in hell, from the creation till Christ came;
and that when he suffered he went into hell, and the devil said to him,
'`What comest thou hither for; to break open our strong holds?
And Christ said, '`To fetch them all out.`'
And so, he said, Christ was three days and three nights in hell, to bring them all out.
On which G. Fox said to him that was false; for Christ said to the thief,
"`This day thou shalt be with me in paradise.`" He also said,
that Enoch and Elijah were translated into heaven; and that Abraham also was in heaven,
since the Scripture saith, that Lazarus was in his bosom.
And Moses and Elias were with Christ upon the mount, before he suffered.
With these instances he stopped his adversary`'s mouth, and put him to a non-plus.

Another time there came to him a great physician, called Dr. Witty,
being accompanied with the lord Falconbridge, the governor of Tin-mouth Castle,
and several knights.
G+++.+++ Fox being called to them, this doctor undertook to discourse with him, and asked,
what he was in prison for?
G+++.+++ Fox told him, because he would not disobey the command of Christ, and swear.
To which the doctor said, he ought to swear his allegiance to the king.
Now G. Fox knowing him to be a great Presbyterian, asked him,
whether he had not sworn against the king and the house of lords,
and taken the Scotch covenant; and whether he had not since sworn to the king.
The doctor having no ready answer to this, G. Fox asked him,
what then was his swearing good for: telling him further,
'`My allegiance doth not consist in swearing, but in truth and faithfulness.`'
After some further discourse, G. Fox was led away to his prison again;
and afterwards the doctor boasted, that he had conquered G. Fox; which he having heard,
told the governor, it was a small boast in him to say he had conquered a bondman.

A while after, this doctor came again, having many great persons with him,
and he affirmed before them all,
that Christ had not enlightened every man that cometh into the world;
that the grace of God, which brought salvation, had not appeared unto all men;
and that Christ had not died for all men.
G+++.+++ Fox asked him, what sort of men those were, which Christ had not enlightened;
and whom his grace had not appeared unto.
To which the doctor answered,`' Christ did not die for adulterers, and idolators,
and wicked men.`'
Then G. Fox asked him, whether adulterers and wicked men were not sinners; and he said,
'`Yes.`'
Which made G. Fox say, '`And did not Christ die for sinners?
Did he not come to call sinners to repentance?`'
'`Yes,`' said the doctor.
'`Then,`' replied G. Fox, '`thou hast stopped thy own mouth.`'
And so he proved, that the grace of God had appeared to all men,
though some turned it into wantonness, and walked despitefully against it;
and that Christ had enlightened all men, though some hated the light.
Several of those that were present confessed it was true;
but the doctor went away in a rage, and came no more to him.

Another time the governor came to him, with two or three parliament-men,
and they asked him, whether he owned ministers and bishops; to which he said, '`Yes,
such as Christ sent forth; such as had freely received, and would freely give;
and such as were qualified, and were in the same power and spirit that they were in,
in the apostles`' days.
But such bishops and teachers as yours are,
that will go no further than they have a great benefice, I do not own;
for they are not like the apostles:
for Christ saith to his ministers,`" Go ye into all
nations and preach the gospel.`" But ye parliament-men,
that keep your priests and bishops in such great fat benefices, ye have spoiled them all:
for do you think they will go into all nations to preach,
or will go any further than they have great fat benefices`'? Judge yourselves,
whether they will or no.`'
To this they could say little, and whatever was objected to G. Fox,
he always had an answer in readiness; and because sometimes it was simple and plain,
his enemies from thence took occasion to say, that he was a fool.
But whatever such said, it is certain that he had a good understanding,
though he was not educated in human learning.
This I know by my own experience, for I have had familiar conversation with him.

In this his prison he was much visited, even by people of note.
General Fairfax`'s widow came once to him with a great company, one of which was a priest,
who began to quarrel with him, because speaking to one person, he said _thou_ and _thee,_
and not _you;_ and those that spoke so, the priest said, he counted but fools.
Which made G. Fox ask him, whether they, that translated the Scriptures,
and that made the grammar and accidence, were fools;
seeing they translated the Scriptures so, and made the grammar so, thou to one,
and you to more than one.
With these and other reasons he soon silenced the priest;
and several of the company acknowledged the truth he declared to them,
and were loving to him; and some of them would have given him money,
but he would not receive it.

Whilst I leave him yet prisoner, I will go to other matters,
and relate the remarkable case of one William Dundas,
who being a man of some repute in Scotland,
came over to the communion of those called Quakers, in a singular manner.
He was a man of a strict life,
and observed the ecclesiastical institutions there
as diligently as any of the most precise;
but in time he saw, that bodily exercise profited little,
and that it was true godliness which the Lord required from man.
]n this state, becoming more circumspect than he was accustomed to be,
he did not frequent the public assemblies so much as formerly.
But this was soon taken notice of, and being asked the reason why, he said,
that there was a thing beyond that, which he looked for.
But it was told him, this was a dangerous principle.
To which Dundas replied, that he was not to receive the law from the mouth of man.
Then the minister, so called, said to him, that he tempted God.
To which Dundas returned, that God could not be tempted to evil.
Now that which made him more averse to the priests of that nation,
was to see their domineering pride: and how they forced some that were not one with them,
in their principles, to comply with their institutions,
sprinkling the children of parents even without their consent.
Add to this, their going from one benefice to another,
being always ready to go over from a small church to a great one,
under pretense of more service for the church; whereas it plainly appeared,
that selfish interest generally was the main cause.
This behavior of the clergy, and their rigid persecution,
if any deviated a little from the church ceremonies and the common form,
turned Dundas`'s affection from them.
An instance of this rigidness was, that one Wood,
who had some charge in the custom-house of Leith,
and approved in some respect the doctrine of those called Quakers, had said,
that Christ was the word, and that the letter was not the word.
For this he was cited before the ecclesiastical assembly of Lothian,
where Dundas was present; and Wood so well defended his saying,
that none were able to overthrow his arguments; chiefly drawn from these words of John,
"`That the word was made flesh,
and dwelt among us.`" Wood continuing to maintain his assertion,
they began to threaten him with excommunication,
and would not allow him so much time as to give his answer to the next assembly.
Excommunication there was such a penalty,
that people under it were very much deprived of conversation with men.
The fear of this made Wood comply in a little time;
and meeting Dundas about three months after in the street at Edinburgh, he told him,
that he had been forced to bow to the assembly against his light:
for if he had been excommunicated, he had lost his livelihood.
Thus Wood bowed through human fear, but he hardly outlived this two years.

In the meanwhile the priests became more and more jealous of Dundas;
for he not having them in such an esteem as they wished,
they said that he would infect the whole nation.
And they did not stick here, but to know with whom he corresponded in England,
they opened, (so great was their power,) his letters at the post-house,
and sometimes kept them: but if they found nothing in them,
by which they could prejudice him, they caused them to be sealed up again,
and delivered to him.
By this base practice, they came to know that one Gawen Lawry, merchant of London,
sent him a box, with about three pounds sterling worth of books.
This box Dundas found afterwards that the priest, John Oswald, had taken away:
and whatever he did, he could not get them again, till the English came into Scotland,
but then many of them were wanting.
Dundas in the meanwhile unwilling to comply with the kirk, was at length excommunicated;
but he was generally so well esteemed, that none seemed to regard that sentence,
so as to keep at a distance from him; which made this act the more contemptible.
Now though Dundas favored the doctrine of the Quakers,
yet they were such a despised people, that he,
who was a man of some account in the world, could not as yet give up to join with them.

It happened once that he was riding from Edinburgh to his house, in a winter evening,
and hearing a noise of some men as if fighting,
he bade his man ride up in haste to see what it was, which he did, and calling out, said,
that there were two men on horseback, beating another on foot, Dundas riding up to them,
saw the two beating the other man, who said to them,`' What did I say to you,
but bid you fear God?
By this Dundas presently perceived that the man thus beaten was a Quaker;
and asking his name, which the other telling, he knew it,
though he did not know the man by sight: and then he fell a beating the two with his rod,
and ordered those that were with him, to carry them to the next prison:
but the said Quaker intreated him to let them go, which he did,
after having asked their names, and dwelling-places.
About a week after,
the said Quaker told a relation of Dundas what kindness he showed him,
and how he had in some manner been saved by him; '`yet,`' said he,
'`I found the same spirit in him that was in the other two men who beat me.`'
Such a saying as this would have offended some men,
but with Dundas it had a contrary effect; for these words so reached him,
that some time after meeting the said Quaker again, he desired,
that as he passed that way, he would make his house his lodging place:
which kind invitation he seemed not unwilling to accept of.
Dundas had now attained so much experience,
that he could discern between the spirits of meekness and rashness;
and sufficiently perceive that the said Quaker, by that which he spoke concerning him,
had not made himself guilty of the latter; but yet he could not bow so low,
as to join in society with the Quakers,
though secretly he endeavored more and more to live up to their doctrine;
and therein he enjoyed more peace in his heart than formerly.

But his outward condition in the world not being very forward, he went into France,
and settled at Dieppe.
Whilst he dwelt there, a certain woman out of England, came thither with her maid,
and spread in the town some books of George Fox and William Dewsbury,
translated into French; and she herself having written some papers,
got them turned into French by Dundas, and so distributed them.
But the message she chiefly came for, she hid from him, and that not without reason;
for what she acted there, was so singular, that if it had been known before,
it is probable she would not have been able to perform it.
Though I do not find what her intent was in the thing, yet it seems likely to me,
that she, not knowing the language there spoken,
would by a sign testify against their apparel and dress, and that on this wise:
on the First-day of the week she came to the meeting-house of the Protestants there,
where some thousands of people were met: and,
having set herself in the most conspicuous place, just over against him that preached,
before the service was finished, she stood up, with the maid that was with her,
who taking off a mantle and hood she was covered with,
she appeared clothed in sack-cloth, and her hair hanging down, sprinkled with ashes:
thus she turned herself round several times, that all the people might see her.
This sight struck both preacher and auditory with no small consternation;
and the preacher`'s wife afterwards telling somebody how this sight had affected her,
said, '`This is of deeper reach than I can comprehend.`'
The said women having stood thus awhile, fell both down upon their knees, and prayed,
and then went out of the meeting, many following them, and distributed some books.
Then they came to their lodging, which was in a Scotchman`'s house;
but he refusing them entrance, they came to Dundas`'s lodging,
who knew nothing of all this.
They therefore told him, that the work they came for in that nation, was now done;
and he asking what they had done, they told him,
and signified that they wanted lodging till they went away.
Then he went abroad to see if he could find lodging for them, but in vain;
he then offered them his bed, being willing to shift for himself somewhere else,
but they refused to accept of his offer;
and his landlady not being willing to let them sit up that night in any of her rooms,
they were fain to stay that night in an out-house.

Now this business had made such a stir in the town,
that one of the king`'s officers coming the next day to Dundas, told, him,
that he had transgressed the laws of the nation,
by receiving persons of another religion to his lodging:
for the king tolerated only two religions, viz. Papists and Protestants.
To this Dundas said, that he had not transgressed the law of hospitality,
and he had been forced to do so, since he could not let them lie in the street,
where they would have been in danger of their lives by the rude multitude.
Then the women were taken away, and sent to prison;
and they not being provided with food, Dundas took care of that.
Sometime after, an order being come from the parliament, at Rouen, it was read to them,
viz. that they should be transported forthwith back to England,
with the first passage-boat, and all their papers and books to be burnt in the market,
and themselves also, if ever they should come to that nation again.
In pursuance of this they were put into a passage-boat in the night time,
and so sent to England.
Afterwards the people at Dieppe intended to pursue Dundas as one of their judgment;
but he was unwilling to be looked upon as such,
though the Protestants had informed against him, that he did not come to their meetings:
but of this no crime could be made, and Dundas told them, if they persecuted him,
being a merchant, and trafficking there,
they might expect the like to be done to their merchants in England.
And when the judge affirmed that Dundas was of the judgment of these women,
he told them that they were better than he;
but that their way was too strait for him to walk in.
There fell out two things which Dundas took singular notice of; the one was,
that the Scotchman who shut out the women, died within twelve months after;
and the other, that the house of his landlady, who refused them a chamber to sit in,
was burnt within the said time, without its being known whence the fire came,
no house being burnt besides, though it was in the middle of the town.

In the meanwhile Dundas continued in an unquiet condition; for by reason of human fear,
he found himself too weak to profess publicly before men, what he believed to be truth.

Then he went to Rouen, but could get no rest there, being somewhat indisposed in body;
and having from England gotten a great many books,
treating of the doctrine of those called Quakers,
he sent some of them to the judge criminal at Dieppe,
and some to the Jesuits`' college there, and at Paris.
Afterwards he spread some books also at Caen, where many Protestants lived.
But since those books spoke against the Papists,
and the Calvinists were in fear that thereby they might be brought to sufferings,
they complained to the lieutenant-general of the town, of Dundas,
as one that did not come to their meeting.
By this he was forced to leave that place, and went to Alencon, where staying a while,
the judge criminal sent for him; and after a long discourse,
he and Dundas agreed so well, that he invited him to come and see him oftener,
and that if he would, he might have an opportunity to discourse with some of the Jesuits.
But Dundas told him, that he was not willing to dispute with any;
yet he should not be afraid to maintain his principles,
against all the Jesuits of the nation.
This being told the Jesuits, it so exasperated them against him,
that being once out of town, they caused his chamber-door to be broken up,
to search his lodging.
He complaining of this to the judge criminal, the judge told him, he knew nothing of it,
and if there was any thing, it did proceed from the Jesuits,
because of his confidence against them.
This seemed not improbable,
for he found his letters opened at the post-house several times,
and when he challenged the post-master, he received for an answer,
that they came so to him.

Some time after he returned to Caen, where he was not long;
but his correspondent at Alencon sent him word, that the day after he went from thence,
the governor of the town had been at his lodging to seek for him.

In the next year, when a war arose between England and France, he came again to Dieppe,
in order to return to England; having got passage in company of the lord Hollis,
ambassador from England; where being arrived,
he frequented the meetings of those called Quakers,
yet was not bold enough to own the name of Quaker,
but continued in the common way of salutations, etc.
Yet at length the truth they professed, had such power over him,
that not being able to enjoy peace without yielding
obedience to the inward convictions upon his mind,
he at length gave up, and so entered into their society,
and obtained a true peace with the Lord, which he had long reasoned himself out of.
In process of time he published a book in print, from which I have drawn this relation,
which he concluded with a poem,
in which he thanked God for his singular dealings and mercies bestowed upon him,
wishing that others might reap benefit by it.

Thus parting with William Dundas, I am now to say, that in this year, 1665, in December,
William Caton died at Amsterdam.
He was a man not only of literature, and zealous for religion,
but of a courteous and affable temper and conversation,
by which he was in good esteem among those he was acquainted with:
and as to the respect he had there, this may serve as an instance.
Holland at this time being in war with England,
there were several English prisoners of war in the
prison of the court of admiralty at Amsterdam,
who now and then were visited by Caton, and supplied with some sustenance:
but in this he was hindered by an officer of that court,
who seemed offended because Caton did not give him hat honor.
This gave occasion to Caton to complain of if to a burgomaster of the city,
I think the lord Cornelius Van Vlooswyh,
who at that time was one of the lords of the admiralty;
he bid Caton come to his house at such a time as he was to go to the court; which he did,
and went with the said burgo master towards the court, where being come,
and entrance denied him by the said officer,
the burgomaster charged him not to hinder Caton from visiting the prisoners.
About this time a law was made in England, called,

[.embedded-content-document.legal]
--

[.letter-heading]
An Act for restraining Non-Conformists from inhabiting in Corporations.

Whereas divers persons, vicars, curates, lecturers, and other persons in holy orders,
have not declared their unfeigned assent and consent in the use
of all things contained and prescribed in the [.book-title]#Book of Common Prayer,#
and administration of the sacraments, and other rites and ceremonies of the church,
according to the use of the church of England,
or have not subscribed to the declaration or acknowledgment
contained in a certain act of parliament,
made in the fourteenth year of his majesty`'s reign, and entitled,
'`An act for the uniformity of public prayers, and administration of sacraments,
and other rites and ceremonies, and for the establishing the form of making,
ordaining and consecrating of bishops, priests,
and deacons in the church of England,`' according to the said act,
or any other subsequent act.
And whereas they, or some of them,
and divers other person and persons not ordained
according to the form of the church of England,
and as they have, since the act of oblivion,
taken upon them to preach in unlawful assemblies, conventicles,
or meetings under color or pretense of exercise of religion,
contrary to the laws and statutes of this kingdom,
and have settled themselves in divers corporations in England,
sometimes three or more of them in a place,
thereby taking an opportunity to distil the poisonous principles
of schism and rebellion into the hearts of his majesty`'s subjects,
to the great danger of the church and kingdom.

II. Be it therefore enacted by the king`'s most excellent majesty,
by and with the advice and consent of the lords spiritual and temporal,
and the commons in this present parliament assembled, and by the authority of the same,
that the said parsons, vicars, curates, lecturers, and other persons in holy orders,
or pretended holy orders, or pretending to holy orders, and all stipendiaries,
and other persons who have been possessed of any ecclesiastical or spiritual promotion,
and every of them, who have not declared their unfeigned assent and consent,
as aforesaid, and subscribed the declaration as aforesaid,
and shall not take and subscribe the oath following:

(2) I, A. B., do swear, that it is not lawful upon any pretense whatsoever,
to take arms against the king;
and that I do abhor that traitorous position of taking
arms by his authority against his person,
or against those that are commissioned by him, in pursuance of such commission;
and that I will not at anytime endeavor any alteration of government,
either in church or state: shall not come within five miles of any city,
etc. nor teach school, on pain to forfeit 40.

--

And though this act was chiefly made against the Presbyterians and Independents,
who formerly had been employed in the public church, yet they suffered but little by it;
but it was cunningly made use of to vex the Quakers, who,
because for conscience-sake they could not swear,
were on this law prosecuted and imprisoned, etc.

Now since the pestilence had been so fierce this year at London,
that about a hundred thousand people were swept away by it and otherwise,
and also many of those called Quakers,
there must be consequently many poor widows and fatherless
children among those of that society.
And because the men, who at times kept meetings to take care for the poor,
found that this burden grew too heavy for them,
they offered part of this service and care to the
most grave and solid women of their church,
who for this service met once a week at London,
and this in time gave rise to the women`'s monthly meetings in other places in England.

I return now to the ship with the banished prisoners, which I left lying in the Thames;
but the owners having put in another master, whose name was Peter Love, the ship,
after long lingering, left the river, and came into the Downs.
In the month called January of the year ensuing, Luke Howard wrote from Dover,
that of fifty-four banished persons,
who almost half a year ago had been brought on ship-board, but twenty-seven remained,
the rest being dead.
By this long stay the ship several times wanted a fresh supply of provision,
and the ship`'s crew grew so uneasy, that two of them having gone ashore with the boat,
ran away, leaving the boat floating, by which it was staved to pieces.
At length the master, though he had but few, and those mostly raw sailors,
and was ill provided with victuals, yet resolved to set sail.
And so they weighed anchor, and went down the channel as far as Plymouth,
where after some stay, they set sail again,
which was on the 23d of the month called February,
but the next day being advanced as far as the Land`'s End,
a Dutch privateer came and took the ship; and to avoid being retaken,
went about the backside of Ireland and Scotland,
and so after three weeks came with some of the banished to Horn, in North Holland,
and some days after the prize, with the rest of them, entered also into that port.
Here they were kept some time in prison,
but the commissioners of the admiralty having understood,
that there was no likelihood to get the banished Quakers
exchanged for Dutch prisoners of war in England,
resolved to set them at liberty, and gave them a letter of passport, and a certificate,
that they had not made an escape, but were sent back by them.
They coming to Amsterdam, were by their friends there provided with lodging and clothes;
for their own had been taken from them by the privateer`'s crew;
and in process of time they all returned to England, except one,
who not being an Englishman, stayed in Holland.
Thus the banished were delivered,
and the design of their persecutors was brought to nought by an Almighty hand.

In the meanwhile G. Fox continued prisoner in Scarborough Castle,
where the access of his friends was denied him,
though people of other persuasions were admitted.
Once came to him one doctor Cradock with three priests,
accompanied with the governor and his wife, and many besides.
Cradock asked him, what he was in prison for?
He answered, for obeying the command of Christ and his apostle in not swearing: but,
if he, being both a doctor and a justice of peace, could convince him,
that after Christ and the apostle had forbidden swearing,
they commanded christians to swear, then he would swear.
'`Here`'s a bible,`' continued he, '`show me any such command if thou canst.`'
To this Cradock said, '`It is written, ye shall swear in truth and righteousness.`'
'`Aye,`' said G. Fox, '`it was written so in Jeremiah`'s time,
but that was many ages before Christ commanded not to swear at all:
but where is it written so since Christ forbade all swearing?
I could bring as many instances out of the Old Testament for swearing as thou,
and it may be more too,
but of what force are they to prove swearing lawful in the New Testament,
since Christ and the apostles forbade it?
Besides, where it is written,
"`Ye shall swear,`" was this said to the Gentiles or to the Jews?`'
To this Cradock would not answer; but one of the priests said, it was to the Jews.
'`Very well,`' said G. Fox, '`but where did God ever give a command to the Gentiles to swear?
For thou knows that we are Gentiles by nature.`'
'`Indeed,`' said Cradock,
'`in the gospel-time everything was to be established
out of the mouths of two or three witnesses,
and there was to be no swearing then.`'
'`Why then,`' returned G. Fox, '`dost thou force oaths upon Christians,
contrary to thine own knowledge in the gospel-times?
And why dost thou excommunicate my friends?`'
Cradock answered, '`For not coming to church.`'
'`Why,`' said G. Fox, '`ye left us above twenty years ago, when we were but young,
to the Presbyterians, Independents, and Baptists, many of whom made spoil of our goods,
and persecuted us because we would not follow them: now we being but young,
knew little then of your principles,
and those that knew them should not have fled from us,
but ye should have sent us your epistles or homilies;
for Paul wrote epistles to the saints, though he was in prison:
but we might have turned Turks or Jews for ought we had from you for instruction.
And now ye have excommunicated us, that is, ye have put us out of your church,
before ye have got us into it, and before ye have brought us to know your principles.
Is not this madness in you to put us out, before we were brought in?
But what dost thou call the church?`'
continued he, '`That which you,`' replied Cradock, '`call the steeple-house.`'
Then G. Fox asked him, whether Christ`'s blood was shed for the steeple-house,
and whether he purified and sanctified it with his blood;
'`And seeing,`' thus continued he,`' the church is Christ`'s bride and wife,
and that he is the head of the church,
dost thou think the steeple-house is Christ`'s wife and bride;
and that he is the head of that old house, or of his people?`'
'`No,`' said Cradock, '`Christ is the head of the people, and they are the church.`'
'`But,`' replied G. Fox, '`ye have given that title to an old house,
which belongs to the people, and ye have taught people to believe so.`'
He asked him also why he persecuted his friends for not paying tithes;
and whether God did ever give a command to the Gentiles, that they should pay tithes;
and whether Christ had not ended tithes,
when he ended the Levitical priesthood that took tithes;
and whether Christ when he had sent forth his disciples to preach,
had not commanded them to preach freely, as he had given them freely;
and whether all the ministers of Christ were not bound to observe this command of Christ.
Cradock said, he would not dispute that: and being unwilling to stay on this subject,
he turned to another matter; but finding G. Fox never to be at a loss for answer,
and that he could get no advantage on him, he at length went away with his company.

With such kind of people G. Fox was often troubled whilst he was prisoner there;
for most that came to the castle would speak with him,
and many disputes he had with them.
But as to his friends, he was as a man buried alive,
for very few of them were suffered to come to him.
Josiah Coale once desiring admittance, the governor told him,
'`You are an understanding man, but G. Fox is a mere fool.`'
Now, though the governor dealt hardly with him, yet in time he altered,
for having sent out a privateer to sea, they took some ships that were not their enemies,
which brought him in some trouble; after that he grew somewhat more friendly to G. Fox:
to whom the deputy-governor said once,
that the king knowing that he had a great interest in the people, had sent him thither,
that if there should be any stirring in the nation, they should hang him over the wall.
And among the Papists, who were numerous in those parts,
there was much talk then of hanging G. Fox.
But he told them, if that was it they desired, and it was permitted them, he was ready,
for he never feared death nor sufferings in his life;
but was known to be an innocent peaceable man, free from all stirrings, and plottings,
and one that sought the good of all men.
But the governor now growing kinder,
G+++.+++ Fox spoke to him when he was to go to the parliament at London,
and desired him to speak with esq.
Marsh, sir Francis Cob, and some others, and to tell them,
how long he had lain in prison, and for what.
This the governor did, and at his coming back told him, that esq.
Marsh said, he knew G. Fox so well,
that he would go a hundred miles barefoot for his liberty;
and that several others at court had spoken well of him.

After he had been prisoner in the castle there above a year,
he sent a letter to the king, in which he gave an account of his imprisonment,
and the bad usage he had met with, and also that he was informed,
that no man could deliver him but the king.
Esq. Marsh, who was a gentleman of the king`'s bed-chamber,
did whatever he could to procure his liberty,
and at length obtained an order from the king for his release;
the substance of which order was,
'`That the king being certainly informed that G. Fox
was a man principled against plotting and fighting,
and had been ready at all times to discover plots, rather than to make any,
etc. that therefore his royal pleasure was,
that he should be discharged from his imprisonment, etc.`'
This order being obtained, was not long after brought to Scarborough,
and delivered to the governor, who upon the receipt thereof, discharged him,
and gave him the following passport:

[.embedded-content-document.legal]
--

Permit the bearer thereof, George Fox, late a prisoner here,
and now discharged by his majesty`'s order, quietly to pass about his lawful occasions,
without any molestation.
Given under my hand at Scarborough Castle, this first day of September,

[.signed-section-signature]
Jordn Croslands, Governor of Scarborough Castle.

--

G+++.+++ Fox being thus released,
would have given the governor something for the civility
and kindness he had of late showed him;
but he would not receive any thing; and said,
whatever good he could do for him and his friends, he would do it,
and never do them any hurt: and so he continued loving to his dying day; nay,
if at any time the mayor of the town sent to him for soldiers,
to disperse the meetings of those called Quakers, if he sent any,
he privately charged them, not to meddle with the meeting.

The very next day after G. Fox was released, the fire broke out at London,
and the report of it came quickly down into the country,
how that city was turned into rubbish and ashes,
insomuch that after an incessant fire which lasted near four days,
but little of old London was left standing,
there being about thirteen thousand and two hundred houses burnt;
the account whereof hath been so circumstantially described by others,
that I need not treat of it at large; but I cannot omit to say, that Thomas Briggs,
some years before passing through the streets of London,
preached repentance to the inhabitants; and coming through Cheapside, he cried out,
that unless London repented, as Nineveh did, God would destroy it.

Now I may relate another remarkable prediction.

Thomas Ibbitt, of Huntingdonshire,
came to London a few days before the burning of that city, and,
as hath been related by eye witnesses, did upon his coming thither,
alight from his horse, and unbutton his clothes in so loose a manner,
as if they had been put on in haste just out of bed.
In this manner he went about the city on the sixth, being the day he came thither,
and also on the seventh day of the week,
pronouncing a judgment by fire which should lay waste the city.
On the evening of these days some of his friends had meetings with him,
to inquire concerning his message and call, to pronounce that impending judgment:
in his account whereof he was not more particular and clear,
than that he said he for sometime had the vision thereof,
but had delayed to come and declare it as commanded, until he felt, as he expressed it,
the fire in his own bosom:
which message or vision was very suddenly proved to be sadly true,
as the foregoing brief account doth in part declare.
The fire began on the 2d of September, 1666, on the first day of the week,
which did immediately follow those two days the said Thomas Ibbitt
had gone about the city declaring that judgment.

Having gone up and down the city, as hath been said,
when afterwards he saw the fire break out, and beheld the fulfilling of his prediction,
a spiritual pride seized on him, which, if others had not been wiser than he,
might have tended to his utter destruction:
for the fire being come as far as the east end of Cheapside,
he placed himself before the flame, and spread his arms forth,
as if to stay the progress of it; and if one Thomas Matthews, with others,
had not pulled him, (who seemed now altogether distracted,) from thence,
it was like he might have perished by the fire.
Yet in process of time, as I have been told, he came to some recovery,
and confessed this error: an evident proof of human weakness,
and a notorious instance of our frailty,
when we assume to ourselves the doing of anything, which heaven alone can enable us.

I cannot well pass by without taking notice of it,
that about three weeks before the said fire,
the English landed in the island of Schelling in Holland,
under the conduct of captain Holmes, and setting the town on fire,
there were above three hundred houses burnt down,
belonging mostly to Baptists that did not bear arms.
It may be further observed, that the English were beaten at sea this summer by the Dutch,
under the conduct of admiral De Ruyter, in a fight, which lasted four days;
so that they had occasion to call to mind how often
the judgments of God had been foretold them,
which now came over their country, viz. pestilence, war, and fire.

G+++.+++ Fox being at liberty, did not omit to visit his friends,
and in their meetings to edify them with his exhortations,
whereby others also sometimes came to be convinced.
And coming to Whitby, he went to a priest`'s house, who fourteen years before had said,
that if ever he met G. Fox again he would have his life, or he should have his.
But now his wife was not only become one of G. Fox`'s friends,
but this priest himself favored the doctrine professed by his wife,
and was very kind to G. Fox, who passed from thence to York,
where he had a large meeting, and visited also justice Robinson,
who had been loving to him from the beginning.
At this time there was a priest with him, who told G. Fox,
'`It is said of you that ye love none but yourselves.`'
But he showed him his mistake, and gave him so much satisfaction,
that they parted friendly.

In this county G. Fox had many meetings, and one not far from colonel Kirby`'s abode,
who had been the chief means of his imprisonment at Lancaster and Scarborough castles:
and when he heard of his release, said, he would have him taken again:
but now when G. Fox came so near him, he himself was caught by the gout,
which had seized him so that he was fain to keep his bed;
and afterwards he met with adversities,
as did most of the justices and others who had been
the cause of the imprisonment of G. Fox,
who now coming to Synder-hill Green, had a large meeting there,
where the priest sent the constable to the justices for a warrant;
but the notice being short, the way long,
and having spent time in searching for G. Fox in another house,
before the officers came where the meeting was, it was ended,
though they had almost spoiled their horses by hard riding.

G+++.+++ Fox passing from thence through Nottinghamshire, Bedfordshire, Buckinghamshire,
and Oxfordshire, and visiting his friends in all places where he came,
and edifying them in their meetings, gets at length to London: but he was so weak,
by lying almost three years in hard and cold imprisonments,
and his joints and body were so stiff and benumbed,
that he could hardly get on horseback.

Being now at London, he beheld the ruins of the city,
and saw the fulfilling of what had been shown him some years before.
Notwithstanding this stroke on London, persecution did not cease,
which gave occasion to Josiah Coale to write these lines to the king:

[.embedded-content-document.address]
--

[.salutation]
King Charles,

Set the people of God at liberty,
who suffer imprisonments for the exercise of their conscience towards him,
and give liberty of conscience to them to worship and serve him as he requires,
and lead them by his spirit; or else his judgments shall not depart from thy kingdom,
until thereby he hath wrought the liberty of his people, and removed their oppressions.
And remember thou art once more warned,

[.signed-section-closing]
By a servant of the Lord,

[.signed-section-signature]
Josiah Coale.

[.signed-section-context-close]
London, Dec. 2nd, 1666.

--

About this time, or it may be in the next month, Stephen Crisp published an epistle,
containing an exhortation to his friends,
and also a prediction concerning succeeding times, which is as follows:

[.embedded-content-document.espistle]
--

Friends, I am the more drawn forth at this time to visit you with an epistle,
because the Lord hath given me some sight of his great and dreadful day,
and workings in it, which is at hand, and greatly hastens,
of which I have something to say unto you, that ye may be prepared to stand in his day,
and may behold his wondrous working among his enemies,
and have fellowship with his power therein,
and may not be dismayed nor driven away in the tempest, which will be great.

And as concerning those succeeding times, the spirit of the Lord hath signified,
that they will be times of horror and amazement, to all that have,
and yet do reject his counsel: for as the days of his forbearance, warning and inviting,
have been long, so shall his appearance amongst those that have withstood him,
be fierce and terrible; even so terrible, as who shall abide his coming?
for the Lord will work both secretly and openly,
and his arm shall be manifest to his children in both.

Secretly he shall rise up a continual fretting anguish among his enemies,
one against another, so that being vexed and tormented inwardly,
they shall seek to make each other miserable, and delight therein for a little season;
and then the prevailer must be prevailed over,
and the digger of the pit must fall therein;
and the confidence that men have had one in another shall fail,
and they will beguile and betray one another, both by counsel and strength;
and as they have banded themselves to break you, whom God hath gathered,
so shall they band themselves one against another, to break,
to spoil and destroy one another; and through the multitude of their treacheries,
all credit or belief, upon the account of their solemn engagement, shall fail;
so that few men shall count themselves, or what is theirs,
safe in the hand of his friend,
who hath not chosen his safety and friendship in
the pure light of the unchangeable truth of God;
and all the secret counsels of the ungodly shall be brought to nought,
sometimes by the means of some of themselves,
and sometimes by impossibilities lying in their way,
which shall make their hearts fail of ever accomplishing what they have determined;
and in this state shall men fret themselves for a season,
and shall not be able to see the hand that turns against them,
but shall turn to fight against one thing, and another, and a third thing,
and shall stagger, and reel in counsel and judgment,
as drunken men that know not where to find the way to rest;
and when they do yet stir themselves up against the holy people,
and against the holy covenant of light, and them that walk in it,
they shall but the more be confounded; for they shall be helped with a little help,
which all the ungodly shall not hinder them of, to wit, the secret arm of the Lord,
maintaining their cause,
and raising up a witness in the very hearts of their adversaries to plead their innocency,
and this shall make them yet the more to vex themselves, and to go through hard-bestead;
for when they shall look upward to their religion, to their power, policy,
or preferments, or friendships, or whatsoever else they had trusted in, and relied upon,
they shall have cause to curse it;
and when they look downwards to the effects produced by all those things,
behold then trouble, and horror, and vexation take hold on them,
and drive them to darkness; and having no help but what is earthly,
and being out of the knowledge of the mighty overturning power of the Lord God Almighty,
they shall despair and wear out their days with anguish; and besides all this,
the terrible hand of the Lord is,
and shall be openly manifested against this ungodly generation,
by bringing grievous and terrible judgments and plagues upon them,
tumbling down all things in which their pride and glory stood,
and overturning even the foundations of their strength; yea,
the Lord will lay waste the mountain of the ungodly,
and the strength of the fenced city shall fail; and when men shall say,
"`We will take refuge in them,`" Nah. 3:12-13, they shall become but a snare,
and there shall the sword devour: and when they shall say, we will go into the field,
and put trust in the number and courage of our soldiers, they shall both be taken away;
and this evil also will come of the Lord, and his hand will be stretched out still,
and shall bring confusion, ruin upon ruin, and war upon war;
and the hearts of men shall be stirred in them, and the nations shall be as waters,
into which a tempest, a swift whirlwind is entered,
and even as waves swell up to the dissolution one of another,
and breaking one of another, so shall the swellings of people be:
and because of the hardship and sorrow of those days,
many shall seek and desire death rather than life.

Ah! my heart relents, and is moved within me in the sense of these things,
and much more than I can write or declare, which the Lord will do in the earth,
and will also make haste to accomplish among the sons of men,
that they may know and confess, that the Most High doth rule in the kingdoms of men,
and pulls down and sets up according to his own will:
and this shall men do before seven times pass over them,
and shall be content to give their glory unto him that sits in heaven.

But, oh friends! while all these things are working and bringing to pass,
repose ye yourselves in the munition of that rock that all these shakings shall not move,
even in the knowledge and feeling of the eternal power of God,
keeping you subjectly given up to his heavenly will,
and feel it daily to kill and mortify that which remains in any of you,
which is of this world; for the worldly part in any, is the changeable part,
and that is up and down, full and empty, joyful and sorrowful,
as things go well or ill in the world: for as the truth is but one,
and many are made partakers of its spirit; so the world is but one,
and many are partakers of the spirit of it; and so many as do partake of it,
so many will be straightened and perplexed with it, but they who are single to the truth,
waiting daily to feel the life and virtue of it in their hearts,
these shall rejoice in the midst of adversity;
these shall not have their hearts moved with fear, nor tossed with anguish,
because of evil tidings,
Ps. 112:7-8. Because that which fixes them remains with them:
these shall know their entrance with the bridegroom, and so be kept from sorrow,
though his coming be with a noise; and when a midnight is come upon man`'s glory,
yet they being ready and prepared, it will be well with them,
and having a true sense of the power working in themselves,
they cannot but have unity and fellowship with the works of it in the earth,
and will not at all murmur against what is, nor wish nor will what is not to be;
these will be at rest till the indignation passeth over,
and these having no design to carry on, nor no party to promote in the earth,
cannot possibly be defeated nor disappointed in their undertakings.

And when you see divisions, and parties, and rendings in the bowels of nations,
and rumors and tempests in the minds of the people,
then take heed of being moved to this party, or to that party,
or giving your strength to this or that, or counseling this way or that way,
but stand single to the truth of God, in which neither war, rent, nor division is;
and take heed of that part in any of you,
which trusts and relies upon any sort of men of this world,
in the day of their prosperity;
for the same party will bring you to suffer with them in the time of their adversity,
which will not be long after; for stability in that ground there will be none;
but when they shall say, come join with us in this or that,
remember you are joined to the Lord by his pure spirit,
to walk with him in peace and in righteousness, and you feeling this,
this gathers out of all bustlings, and noises, and parties, and tumults,
and leads you to exalt the standard of truth and righteousness,
in an innocent conversation, to see who will flow unto that;
and this shall be a refuge for many of the weary, tossed,
and afflicted ones in those days, and a shelter for many whose day is not yet over.

So dearly beloved friends and brethren,
who have believed and known the blessed appearance of the truth,
let not your hearts be troubled at any of these things:
oh let not the things that are at present, nor things that are yet to come,
move you from steadfastness, but rather double your diligence, zeal,
and faithfulness to the cause of God: for they that know the work wrought in themselves,
they shall rest in the day of trouble.
Yea, though the fig-tree fail, and the vine brings not forth,
and the labor of the olive-tree ceases, and the fields yield no meat,
and '`the sheep be cut off from the fold,
and there be no bullocks in the stall,`'yet then mayest thou rejoice in the Lord,
and sing praises to the God of thy salvation. Hab. 3:16-17.

And how near these days are to this poor nation, few know,
and therefore the cry of the Lord is very loud unto its inhabitants,
through his servants and messengers, that they would prize their time while they have it,
lest they be overturned, wasted, and laid desolate before they are aware;
and before destruction come upon them, and there be no remedy,
as it hath already done upon many.

Oh, London!
London! that thou and thy rulers would have considered, and hearkened and heard,
in the day of thy warnings and invitations, and not have persisted in thy rebellion,
till the Lord was moved against thee,
to cut off the thousands and multitudes from thy streets,
and the pressing and thronging of people from thy gates,
and then to destroy and ruin thy streets also, and lay desolate thy gates,
when thou thought to have replenished them again.

And, oh! saith my soul, that thy inhabitants would yet be warned,
and persuaded to repent and turn to the Lord,
by putting away every one the evil that is in their hearts,
against the truth in yourselves, and against those that walk in it,
before a greater desolation and destruction overtake you.

Oh, what shall I say to prevail with London, and with its inhabitants!
The Lord hath called aloud, he hath roared out of Zion unto them,
but many of them have not hearkened at all, nor considered at all.

Well, oh my friends, and thou, oh my soul, return to your rest,
dwell in the pavilion of the house of your God, and my God,
and shelter yourselves under the shadow of his wings,
where ye shall be witnesses of his doings, and see his strange act brought to pass,
and shall not be hurt therewith, nor dismayed.

Oh, my friends,
in the bowels of dear and tender love have I signified these things unto you,
that ye might stand armed with the whole armor of God, clothed in righteousness,
and your feet shod with the preparation of the gospel of peace;
and freely given up in all things to the disposing of the Lord, who will deliver us,
not by might, nor by sword, nor spear, but by his own eternal, invisible arm,
will he yet save us and deliver us, and get himself a name by preserving of us;
and we shall yet live to praise him who is worthy of glory, of honor and renown,
from the rising of the sun, to the setting of the same, now and forever, amen, amen,
saith my soul.

--

In the year 1667 a book came forth in print at London, with this title,
[.book-title]#Persecution Appearing With Its Open Face in William Armorer.#
This was written by some of the prisoners called Quakers,
and contained a relation of the impetuous carriage of the said Armorer,
who being a knight and justice of peace, had made it his business many years,
one after another, to persecute the Quakers,
and from time to time to disturb their religious meetings.
From a multitude of cases I meet with in the said book, I will pick out but a few.
The aforesaid Armorer came very often to the house of Thomas Curtis, at Reading,
to disturb the meeting, taking many persons prisoners from thence,
particularly once thirty-four, both men and women, at a time.
And when they were brought to their trial,
the oath was tendered them as the most ready means to ensnare and to keep them in prison.
Among the prisoners taken out of the meeting was one Henry Pizing,
who coming to the bar with his hat in his hand, judge Thomas Holt said,
here is a man that hath some manners, and asked him,
if he would take the oath of allegiance?
to which Pizing answered, he had taken it twice already.
But said the judge, '`You were no Quaker then.`'
To which the said Henry replied, '`Neither am I now, but have been many weeks among them,
and I never met with any hurt by them, but found them to be an honest and civil people.`'
Upon which William Armorer, who had taken him prisoner, said,
'`Why did you not tell me so before?`'
to which Henry returned, your worship was so wrathful, that you would not hear me.
Then the judge said, '`He must take the oath again.`'
The oath being read, he took it, upon which they let him go free without paying any fees.
But they required of him, to go out at a back door, and to come no more among the Quakers.
But Pizing told them, he hoped now he was freed, he might go out at which door he would.

Thomas Curtis afterwards being called, the judge asked him,
if he would take the oath of allegiance?
to which he answered,
that he did not refuse the oath upon the account of not bearing allegiance to the king,
but because Christ had commanded not to swear at all:
for he was persuaded that he had manifested himself to be
as good a subject to the king as most in the county,
since he came into it, and that if he could take any oath,
either to save his estate or life, he professed he would begin with that oath.
Then he desired,
that the court would be pleased to let some of their ministers show him by the Scriptures,
how he might take it, and not break the command of Christ.
And the judge called to one Worrel, a priest, that was near him,
and desired him to satisfy Curtis in that particular.
But the priest putting off his hat, and bowing to the court, desired to be excused,
saying, he had had to do with some of them already,
but they were an obstinate people and would not be satisfied.
'`Aye,`' said Curtis, '`this is commonly the answer we have from these men,
when they are desired to answer us a question according to the Scripture;
for when we make it appear that they give no satisfactory answer to the question,
they use to say, we are obstinate.`'
Curtis, (whose wife Anne was a daughter of a sheriff of Bristol,
that had been hanged near his own door,
for endeavoring to bring in the king,) was released after some small time;
but quickly taken prisoner again by Armorer,
who perceiving that he intended to have gone to Bristol fair,
caused him to be brought to an inn, where he told him, '`You are going to Bristol fair,
but I will stop your journey.`'
And then commanding the constable to carry him to prison,
he was compelled thither without a mittimus.

About this time Curtis`'s imprisoned friends wrote a paper,
and it is like he had a hand in it,
to show the hurt and mischief proceeding from swearing.
This paper being sent by him to one of the magistrates,
and leave being given him to read it in the council chamber,
at the reading of these words,
'`Because of swearing the land mourns,`' Alderman Johnson said that was very true.

Sometime after it happened that Thomas Curtis,
his wife and man-servant being all prisoners.
Armorer sent his man to inquire if there were any in the house more than the family,
to which the maid having answered no, a little after Armorer came himself,
and knocked at the door; but the maid being in fear, did not open it.
Armorer then pulling an instrument out of his pocket, picked the lock, entered the house,
and searching from room to room, came at length where he found one Joseph Coale,
who dwelt in the house, and was not well at that time; and Armorer taking him by the arm,
and pulling him down stairs, said to him, '`Will you take the oath of allegiance?
Which he refusing, was sent to the house of correction,
whither the day before seven women, taken from a meeting, had also been brought.
This bold act of picking the lock he did at other times also,
and once when the maid was gone out to carry some
victuals to her master and mistress in prison.
In the meanwhile he searched the warehouse, where was much cloth;
and to a woman that was there, and spoke against his picking of the locks, he said,
'`What have you to do with it?`'
And '`Where`'s that whore?
meaning the maid servant.
The woman answered him, she had to do with it;
for she was to see that nobody did steal any thing out of the house.
Besides,
Armorer continually made it his business to disturb
the meeting which commonly was twice a week;
and then he used to curse, and to strike those he found there with a great cane,
always sending some to prison.
Having once caused three women to be brought before him from the house of correction,
he would have them pay a fine for having been at a meeting;
to which one Anne Harrison said, '`Thou hast got our house already that we built,
and hast taken away our means;
and wouldst thou have me pay more money when I have broken no law?
We were but four above the age of sixteen years, and the act says, it must be above four.`'
To which Armorer said, his man told him there were six: and two of them ran away.
'`It is false,`' said Anne, '`there was Frances Kent, but she being a midwife,
was fetched out of town; and as for the sixth, she was not there.`'
But Armorer not regarding whatever Anne said, spoke in a rude manner, '`I shall have Mrs.
Kent, and then let the best lady in the land want her, she shall not go,
except the king or court send for her.`'

If I should mention all the enormities of Armorer`'s violent behavior,
this relation must needs be very large; and therefore I pass by the most cases,
and touch but on some few.
More than once it happened when the prisoners being brought to their trial,
reproved Armorer because of his injustice,
and put him in mind that once he must give an account for his bad deeds;
he in a most impudent manner said,
'`you shall see at the day of judgment whose arse will be blackest, yours or mine.`'
And when a prisoner told him,
it was an uncivil thing for one called a justice to speak such words, he replied, '`Why,
sirrah, what incivility is it?
Is not your nose your nose, and your arse your arse?`'
Other absurdities the prisoners met with in the court, I pass by,
as also how from time to time, they were treated when they refused the oath.
From what hath been said already in more than one place concerning the like cases,
one may easily guess how matters were transacted here, which sometimes was so grossly,
that the spectators showed their dislike.
When once the jury for want of good witnesses, could not agree to find the bill,
Armorer rose off the bench, and appeared as a witness.
But notwithstanding the jury, returning the second time, brought it in _ignorumus._
Upon which the other justice said to them, that sir William Armorer,
an honorable gentleman, had taken his oath also.
To which the jury returned, it was true, sir William Armorer was an honorable gentleman,
but was a man subject to passion.
And they continuing unwilling to bring in the prisoners guilty,
the two justices Proctor and Armorer,
(for there were then no more on the bench,) for all that would not discharge the prisoners,
but sent them to jail again, as seditious persons;
for Proctor had told the jury the day before,
that if they did not bring in the prisoners guilty,
they would make William Armorer and the clerk perjured persons.

Anne, the wife of Thomas Curtis, being called to the bar,
and asked if she would take the oath, said, '`I look on it as a very hard thing,
that I should be required to take this oath, being under covert,
and my husband being here a present sufferer, for the same thing;
for there is no other woman in England, that I have heard of, under covert,
that is required to take that oath, and kept in prison on that account.`'
But Armorer full of passion, cried, '`Hold your tongue, Nan, and turn your back.`'
And so she, with another woman, that had also been required to take the oath,
was sent back to jail, as dangerous and suspected persons.
At length some justices procured her liberty; and this so displeased Armorer,
that he did not rest before he had her in prison again:
but others it seems so eagerly desired her liberty,
that she was discharged a second time, though her husband`'s goods and money were seized.
How a prisoner who spoke something in his own defense, was threatened to be gagged,
how girls were sent to the house of correction,
and how Armorer coming in winter-time into the meeting,
and having got a bucket of water into the room,
he himself threw it with a nasty bowl in the faces of some young maidens,
I cursorily skipped over.
He seemed exceedingly offended with Anne Curtis, who being a witty woman, did not omit,
when occasion was offered, to tell of his uncivil behavior:
and therefore he soon had her in jail again;
and when it was proposed in the summer-time to discharge some of the prisoners,
because of the extreme hot weather, provided they gave security, '`No,`' said Armorer,
'`Mrs.
Curtis shall not go out, though she would give security,
but she shall lie in jail till she rot.`'
But how wicked soever he was, yet he could not prevent,
that all his exorbitant carriage against the Quakers was published in print.

But such behavior was at that time no rare or uncommon thing;
for since persecution was continually cloaked with a pretense
of rebellion and sedition all over the country,
such were found, who to their utmost power did persecute the Quakers, so called;
as among others, one Henry Marshall, priest at Crosthwait in Westmoreland,
who being also a prebendary, and having several benefices,
yet how great soever his revenues were,
kept poor people of that persuasion in prison for not paying tithes to him:
and once he said very presumptuously from the pulpit,
that not one Quaker should be left alive in England.
But this temerity he did not out-live long:
for as he was going half-undressed to his chamber to bed, he fell down stairs,
as was concluded from the circumstances; for he was found lying on the floor,
with his skull broken, wrestling with death, without being able to speak one word;
and being taken up he died, leaving his wife and children in such a condition,
that by reason of debts they fell into poverty.

About this time a certain popish author,
who expressed his name no further than with the letters A. S. gave forth a book called,
[.book-title]#The Reconciler of Religions;# Or, [.book-title]#A Decider of All Controversies in Matters of Faith.#
Josiah Coale, who was very zealous for religion, and well saw what this author aimed at,
answered him by a book that appeared in print, with the title of, [.book-title]#The Whore Unveiled;
or the Mystery of the Deceit of the Church of Rome Revealed.#
Now although the said A. S. chiefly struck at the Quakers as the worst of heretics,
falsely perverting their doctrine, as importing,
that the same spirit that reproved Judas of sin, did also induce him to desperation,
and to hang himself;
yet he omitted not to encounter the doctrine of other Protestant societies;
and the Roman church he stated as the true church,
from which they were unjustly departed, and to whom they must all return again:
for the Roman, said he, was the true church, and not any other;
she was the holy Catholic and apostolical church, that was infallible, and could not err,
and had the power to work miracles.
He also asserted, that she was one in matters of faith,
that she was governed by one invisible head Christ, and by a visible head, the pope;
and that therefore she was the true church.
Now for as much as he held forth at large these and several other positions,
so Josiah Coale did not omit to answer all these pretenses distinctly and emphatically;
for he was an undaunted and zealous disputant.
Besides the superstition, idolatry, and cruel persecution of the Roman church,
which had taken away the lives of many thousands of honest and pious people,
supplied abundant matter to Josiah Coale, to show the papal errors,
and clearly to prove her to be the false church.
For though he did not deny that the true church was Catholic, or universal,
yet he denied that the universality of the church of Rome
was a sufficient argument to prove her to be the true church,
'`What church, (thus he queried,) is more universal than the great whore,
the false church, who had a name written.
Mystery Babylon the Great, the Mother of Harlots, and Abominations of the Earth,
Who sits upon the waters, which are peoples, and multitudes, and nations, and tongues?
And did not the whole world wonder after the beast that carried the whore?
Did she not sit as queen over them all, with her fair profession,
or golden cup in her hand, full of abominations, and filthiness of her fornication?
And did not all the inhabitants of the earth, and the kings of the earth,
drink of the wine of her fornication, and commit fornication with her?
Mark how universal was this great whore, the false church; and how confident she was:
for she said in her heart that she should see no sorrow; and she glorified herself,
and reigned over the kings of the earth.
Is not this the very state of the church of Rome at this day?
Doth she not reign over the kings of the earth?
And hath she not done so long, even for many ages?
And how she hath exercised authority over kings,
may appear from the case of the emperor Frederick,
who was fain to hold the pope`'s stirrup while he got on horseback.
And did not the great whore, which John saw,
drink the blood of the saints and martyrs of Jesus.
Surely the histories of many generations past testify this.
And was she not to have blood given her to drink?
as may appear not obscurely from Rev. 17:6.`' At this rate Josiah
Coale encountered the masked A. S. but in a more copious way;
and thus he answered his assertions.
To that, that the church of Rome should always remain to the end of the world,
and that therefore she was infallible, J. Coale said,
that the bare affirmation of A. S. was no proof,
except he would produce that saying of the mother of harlots, '`I sit as a queen,
and am no widow, and shall see no sorrow.`'
But indeed that would be a very pitiful argument to prove the church of Rome infallible,
unless she was first proved to be the true church.
And as J. Coale answered these and other objections at large,
so he showed also the vanity of the boast of miracles,
of which the church of Rome gloried;
and he refuted all the falsities which that anonymous
author had belched out against the Quakers,
as a people that might be wronged without incurring any danger.
But I omit to recite all J. Coale`'s answers for brevity sake;
yet may make mention of a poem which he wrote sometime before,
when he was prisoner at Launceston, in Cornwall, to which the reader is referred,
being to be found in Josiah Coale`'s works, at page III.

Thus zealously J. Coale wrote against popery; and yet such hath been the malice of many,
that they represented the Quakers as favorers of the church of Rome,
though on many occasions they had effectually shown the contrary.
But their enemies endeavored to brand them many ways;
and they left no stone unturned to blacken them;
to which sometimes false brethren gave occasion:
for about this time there were yet many of the adherents of John Perrot,
who often ill-treated, and spoke evil of those who did not approve their absurdities.
This befell Richard Farnsworth, one of the first preachers among those called Quakers,
though he was a man of a notable gift,
and on his dying bed he gave evidences of a firm and steadfast trust in God;
for it was not long before this time that he fell sick, and deceased at London.
Among the many expressions which signified his good frame of mind,
and the divine consolation he felt, were also these words,
that were taken in writing from his mouth:

[.embedded-content-document.testimony]
--

[.salutation]
Friends,

God hath been mightily with me, and hath stood by me at this time;
and his power and presence hath accompanied me all along,
though some think that I am under a cloud for something.
But God hath appeared for the owning of our testimony,
and hath broken in upon me as a flood,
and I am filled with his love more than I am able to express;
and God is really appeared for us, etc.

--

This he spoke but a short time before his departure;
and exhorted his friends to faithfulness and steadfastness,
and that nothing might be suffered to creep in of
another nature than the truth they professed,
to intermix therewith, saying, '`No linsey-woolsey garment must be worn.`'
Some more consolatory words he spoke,
and his last testimony was as a seal unto all the
former testimonies he had given for the Lord.
And after having lain yet an hour or two, he slept in peace with the Lord,
and left a good repute behind, with those who truly were acquainted with him,
and knew how zealously he labored in the ministry of the gospel for many years.

Now I return again to G. Fox, who was this year not only in Wales,
but in several other places, without being imprisoned, though at Shrewsbury,
where he had a great meeting, the officers being called together by the mayor,
consulted what to do against him, since it was said,
the great Quaker of England was come to town.
But they could not agree among themselves, some being for imprisoning him,
and others for letting him alone: and they being thus divided, he escaped their hands.

As several eminent men among those called Quakers, were taken away by death,
so others came in who filled their places; among these,
and none of the least was Robert Barclay, son of colonel David Barclay,
descended of the ancient and famous family of the Barclays, and of Katharine Gordon,
from the house of the dukes of Gordon.
This his son Robert being born at Edinburgh, in the year 1648,
was educated in France and trained up in literature,
having lived some years with his uncle at Paris,
where the Papists were very active to bring him over to their religion.
But though in that tender age he seemed a little to hearken to them,
yet growing up in years, and so advancing in knowledge,
he soon got a clear sight of their errors.
During his stay in France, he not only became master of the French,
but also of the Latin tongue;
and after he had been instructed in the language of the learned,
and other parts of human literature, he returned to Scotland; but during his absence,
his father had received the doctrine of the Quakers, and showed by his pious behavior,
that he had not therein acted inconsiderately.
Robert Barclay having attained the age of nineteen years,
and being come to a good maturity of understanding,
found so much satisfaction in the religion which his father made profession of,
that he also embraced it, and openly showed before all the world,
that the despised name of Quakers,
could not hinder him from-maintaining boldly that which he now apprehended to be truth.
Nay, he grew so zealous and valiant in the doctrine he now professed,
that he became a public promulgator of it;
and often engaged in disputes with the scholars, not only verbally, but also by writing:
for he was so skillful in school learning,
that he was able to encounter the learned with their own weapons,
and of such quick apprehension, as not to be inferior to the refined wits;
his meekness also was eminent;
and these qualifications were accompanied with so taking a carriage,
as rendered him very acceptable to others.
And though his natural abilities were great enough
to have made him surpass others in human learning,
and so to have become famous among men, yet he so little valued that knowledge,
that he in no wise endeavored to be distinguished on that account.
But his chief aim was to advance in real godliness,
as the conversation I had with him hath undoubtedly assured me:
for I was well acquainted with him; as also with Roger Haydock of Lancashire,
a learned and intelligent man,
who about this time also came to enter into society with those called Quakers,
whose doctrine his eldest brother John Haydock, had received before him.
But it so happened, that Roger coming once to his father`'s house,
was by his mother put on to discourse with his brother John,
in hopes that thereby he might have been drawn off from the way of the Quakers.
But John gave such weighty reasons for what he asserted to be truth,
that he quickly put Roger to silence, which so displeased his mother,
who was inclined to the Presbyterian way,
that she blamed him for not having held it out longer against his brother:
but he told her, '`It is truth, I dare not say against it.`'
Being thus convinced, he also became a public professor of the doctrine of the Quakers,
and in time a zealous preacher of it too.
And he being a man of great parts, well read and full of matter,
many times engaged in disputes with the priests,
sometimes making use of his pen also to that end; for he was an unwearied laborer,
and suffered the spoiling of his goods, and several imprisonments;
and though he was attended with bodily weaknesses, yet he did not use to spare himself,
but travelled much to visit the churches in England, Scotland, Irekind, Holland, etc.
And he continued steadfast to the end of his days; not only for which,
but also because of a special affection he bore me, his remembrance is dear to me still.

I must now make some mention again of Miles Halhead,
several times named in this history, who this year coming into Devonshire,
and being brought before the magistrates, it was asked him, what business he,
(who dwelt in Westmoreland,) had in Devonshire?
to which he answered, that he was come there to see his old friends, whom formerly,
about ten years ago, he had acquaintance with.
One of the magistrates asked him, what were the names of those friends he meant?
To which he returned, '`One Sir John Coplestone, who was then high sheriff of Devonshire;
John Page, who was mayor of Plymouth; one justice Howel,
who was then the judge of the sessions of Exeter, and one colonel Buffet,
who was also a justice at that time.`'
One of the magistrates then said to the others, '`Truly, gentlemen,
this man calls these men his friends, yet they have been his persecutors.`'
Another of the magistrates then gave him an account,
into what pitiful condition those men were fallen, and how they lost their estates; nay,
Buffet had been committed to prison for high treason, and was escaped out of jail,
and not to be seen in his own country.
And further he said to Halhead,
'`Thus I have given you a true account of your old friends;
if these men were your persecutors, you may be sure they will trouble you no more:
for if they that trouble you and persecute you, have no better fortune than these men,
I wish that neither I, nor any of my friends, may have any hand in persecuting of you.`'
And thus these discreet magistrates suffered him to go his ways,
without meddling with him.

Neither was persecution now generally so hot in England as it had been before,
yet the Presbyterians and some others durst not keep public meetings,
lest they should be fined; but at times when they have met for worship,
they have had tobacco pipes, bread and cheese, and cold meat on the table,
having agreed before-hand, that if the officers came in upon them,
they should leave their preaching and praying, and fall to their meat.
This made G. Fox say to one Pocock, whose wife was one of his friends,
'`Is not this a shame to you who persecuted and imprisoned us, and spoiled our goods,
because we would not follow you, and be of your religion, and called us house-creepers?`'
'`Why,`' said Pocock, '`we must be wise as serpents,`' To which G. Fox returned,
'`This is the serpent`'s wisdom indeed.
Who would ever have thought, that you Presbyterians and Independents,
who persecuted and imprisoned others, for not following your religion,
now should flinch away yourselves, and not stand to, and own your own religion.`'

G+++.+++ Fox travelled this year through England, and visited his friends in their meetings.
But I pass by his occurrences.

This year also came forth the perpetual edict, so called, in Holland,
made as the title recites, for the maintenance of liberty,
and for preservation of the unity,
and the common quiet of the country of Holland and West-Friesland.
By this edict, the chief command of the military forces of the states,
and the stadt-holder-ship, (or deputy-ship,) were separated.
This was on purpose to prevent the prince of Orange`'s becoming too potent,
for hereupon followed the suppression of the stadt-holder-ship.
But how strong soever this law was made, and confirmed by oaths,
yet afterwards it was broken by the instigation of the rabble,
as will be seen in its due time.
This year also a peace was concluded between England and Holland,
not long after the Dutch had burnt some of the king`'s ships in the Thames.
