== Chapter XVII.

=== 1668--1670.

[.chapter-synopsis]
* Convincement of W. Penn
* What brings Salvation
* G+++.+++ Fox and Esquire Marsh
* The Penitent Infanticide
* Dying expressions of T. Loe
* Dispute between the Baptists and Friends
* "`Sandy Foundation Shaken`"
* Circumstances attending the death of J. Coale
* Death of F. Howgill
* Excellent counsel for young maidens
* G+++.+++ Fox in Ireland
* Solomon Eccles
* Story of G. Fox having turned Presbyterian
* Marriage of G. Fox
* Margaret Fox in prison
* Second Conventicle Act
* Informers
* Illness of G. Fox.

In the beginning of the year 1668, William Penn, son of admiral sir William Penn,
began to show himself openly an adherer to,
and an asserter of the doctrine of those called Quakers.
He had been trained up in the university of Oxford,
and he was afterwards by his father sent into France, where for some time he lived,
(as himself once told me,) with the famous preacher, Moses Amyrault.
After a considerable stay in that kingdom, being returned and come into Ireland,
he once went to a meeting of those called Quakers, which being disturbed, he,
though finely clothed as a young gentleman, and wearing a great periwig,
was with others carried from thence to prison, where by his fellow prisoners,
he was more confirmed in that doctrine which he already apprehended to be truth.
But when it come to be known that he was the son of Admiral Penn, he was soon released.
This change did not a little grieve his father,
who intended to have trained him up for the court;
but now saw his eldest son in the early part,
being about the twenty-second year of his age,
entered into the society of the despised Quakers.
Several means were used, nay even his necessaries were withheld from him,
to draw him off`", if possible, and bring him to other resolutions.
But all devices and wiles proved in vain: for he continued steadfast,
and conversed much with Josiah Coale,
who likewise in his young years came over to the Quakers.

This summer Stephen Crisp was prisoner at Ipswich,
where the number of friends was considerably increased by his ministry.
I, with some other friends of Holland, visited him there in prison,
and we found him in a cheerful condition, as well contented as if he had been at liberty:
for he suffered for the ministry of the gospel,
and continued to preach in prison when his friends came to visit him.

The journey which G. Fox made this year through England and Wales I pass by.
The latter part of the summer he returned to London,
where with great satisfaction I heard him preach several times before a numerous auditory:
for about that time, the meetings of dissenters were not disturbed at London,
but all was so quiet, that the Quakers, so called,
were suffered to build a large meeting place in Gracechurch-street,
where the first time a meeting was kept, I was present, and saw G. Fox,
and heard him preach there, besides some others.

Whilst he was at London, he gave a visit to esquire Marsh,
who now was a justice of the peace in Middlesex,
and it so happened that he was at dinner when G. Fox came to his house,
which so pleased him, that he kindly invited him to sit down with him to dinner,
but G. Fox courteously excused himself.
There were at that time several great persons at table with justice Marsh,
who said to one of them, (a Papist,) '`Here is a Quaker you have not seen before.`'
From this the said Papist took occasion to ask G. Fox,
whether he did own the christening of children?
To which G. Fox answered, there was no Scripture for any such practice.
'`What!`' said he, '`not for christening children?`'
Nay,`' replied G. Fox, '`the one baptism by the one Spirit into one body, we own;
but to throw a little water on a child`'s face,
and to call that baptizing and christening it, there is no Scripture for that.`'
Then the Roman Catholic asked him, whether he did not own the Catholic Faith?
'`Yes,`' said G. Fox, but he added,
that neither the pope nor the Papists were in that Catholic Faith;
since the true faith worked by love, and purified the heart;
and if they were in that faith which gives victory,
by which they might have access to God,
they would not talk to the people of a purgatory after death;
neither would they ever use prisons, racks, or fines, to force others to their religion;
because that was not the practice of the apostles and primitive Christians;
but it was the practice of the faithless Jews and heathens, to use such forcing means.
'`But,`' continued G. Fox, '`seeing thou art a great and leading man among the Papists,
and sayest, there is no salvation but in your church, I desire to know of thee,
what it is that brings salvation in your church,`' To this the Roman Catholic answered,
'`A good life:`' '`And nothing else?`'
said G. Fox.
'`Yes,`' replied the other, '`good works.`'
'`Is this your doctrine and principle,`' said G. Fox.
'`Yes,`' said he.
Then G. Fox replied, '`Neither thou nor the pope, nor any of the Papists know,
what it is that brings salvation.`'
Then the Roman Catholic asked him, what brings salvation into your church?
G+++.+++ Fox answered, '`That which brought salvation to the church in the apostles`' days,
namely, the grace of God, which the Scripture says brings salvation,
and hath appeared to all men; and teaches us to deny ungodliness, and worldly lusts,
and to live godly, righteously, and soberly in this present world.
By this it appears, it is not the good works, nor the good life,
that brings the salvation, but the grace.`'
'`What!`' said the Roman Catholic, '`doth this grace, that brings salvation,
appear unto all men?`'
'`Yes,`' said G. Fox.
'`I deny that,`' returned the other.
'`All that deny that,`' replied G. Fox, '`are sect-makers,
and are not in the universal faith, grace, and truth, which the apostles were in.`'
Then the Roman Catholic began to speak about the mother-church,
which gave occasion to much discourse, and G. Fox asserted,
that if any outward place had claim to be the mother-church, above all other churches,
that Jerusalem had much more right to it than Rome.
But in conclusion he said, that there was no other mother-church but Jerusalem,
which is above, and is free, and which is the mother of us all, as saith the apostle.
Upon this subject G. Fox did so paraphrase,
that esquire Marsh said at length to the Roman Catholic, '`O you do not know this man.
If he would but come to church now and then, he would be a brave man.`'

After some other discourse together, G. Fox,
got an opportunity to go aside with the said Marsh into another room,
and to desire that he who had much of the management of affairs,
would prevent the persecution of his friends as much as possibly he could.
Marsh showed himself not averse to this, but said,
he was in a strait how to act between the Quakers and some other dissenters.
'`For,`' said he, '`you say ye cannot swear, and the Independents, Baptists,
and Fifth-monarchy people, say also, they cannot swear.`'
To this G. Fox said, '`I will show thee how to distinguish:
the members of those societies thou speaks of, do swear in some cases,
but we cannot swear in any case.
If any one should steal their cows or horses,
and thou shouldest ask them whether they would swear they were theirs?
Many of them would readily do it.
But if thou triest our friends, they cannot swear for their own goods.
Therefore when thou puts the oath of allegiance to any of them,
ask them whether they can swear in any other case; as for their cow or horse?
Which if they be really of us, they cannot do, though they can bear witness to the truth.`'
Then G. Fox gave him a relation of a trial in Berkshire,
viz. '`A thief having stolen two beasts from one of those called Quakers, was imprisoned;
but somebody having informed the judge, that the man that prosecuted was a Quaker,
and he, (the judge,) perceiving that he would not swear,
would not hear what the man could say,
but tendered him the oath of allegiance and supremacy, which the said Quaker refusing,
the judge premunired him, and let the thief go free.`'

Esquire Marsh having heard this relation, said that judge was a wicked man.
And by what G. Fox had told him,
he sufficiently perceived how he might distinguish between the Quakers and other people.
True it is,
the Baptists in those days made some profession of the unlawfulness of swearing,
but when they came to be tried on that account,
they soon desisted from that part of their profession,
as will be shown more at large in the sequel.
But they and the Independents, etc. were very loth to take the oath of allegiance,
because of a grudge they had to the government;
and this was well known to those that were at the helm.
But the innocent Quakers were continually exposed to the malice of their persecutors,
and bore the hardest shock of the laws made against dissenters.
But now justice Marsh did not omit to free the Quakers
from persecution as much as was in his power;
for he kept several from being premunired in those parts where he was a justice.
And when sometimes he could not avoid sending those
that were brought before him to prison,
he sent some only for a few hours, or for a night.
And even this was such hard work to him, that at length he told the king,
he had sent some of the Quakers to prison contrary to his conscience,
and that he could not do so any more.
He also advised the king to give liberty of conscience:
and he was so serviceable to stop the violence of persecution,
that about this time little was heard about disturbing of meetings.

About the forepart of this year, if I mistake not, there happened a case at Edmondsbury,
which I cannot well pass by in silence,
viz. A certain young woman being delivered of a bastard child, destroyed it,
and was therefore committed to prison: whilst she was in jail, it is said William Bennit,
a prisoner for conscience-sake, came to her, and in discourse asked her,
whether during the course of her life,
she had not many times transgressed against her conscience?
And whether she had not often thereupon felt secret checks and inward reproofs,
and been troubled in her mind because of the evil committed;
and this he did in such a convincing way,
that she not only assented to what he laid before her,
but his discourse so reached her heart, that she came clearly to see,
that if she had not been so stubborn and disobedient to those inward reproofs,
in all probability she would not have come to such a miserable fall as now she had:
for man not desiring the knowledge of God`'s ways, and departing from him,
is left helpless, and cannot keep himself from evil,
though it may be such as formerly he would have abhorred in the highest degree,
and have said with Hazael, '`What, is thy servant a dog,
that he should do this great thing?`'
W+++.+++ Bennit thus opening matters to her,
did by his wholesome admonition so work upon her mind,
that she who never had conversed with the Quakers,
and was altogether ignorant of their doctrine,
now came to apprehend that it was the grace of God that brings salvation,
which she so often had withstood; and that this grace had not yet quite forsaken her,
but now made her sensible of the greatness of her transgression.
This consideration wrought so powerfully, that from a most grievous sinner,
she became a true penitent, and with hearty sorrow she cried to the Lord,
that it might please him not to hide his countenance.
And continuing in this state of humiliation, and sincere repentance,
and persevering in supplication, she felt in time some ease;
and giving heed to the exhortations of the said Bennit,
she attained at length to a sure hope of forgiveness
by the precious blood of the immaculate Lamb,
who died for the sins of the world.

Of this she gave manifest proofs at her trial before judge Matthew Hale,
who having heard how penitent she was, would fain have spared her,
having on purpose caused to be inserted in the indictment,
that she had committed the fact willfully and designedly.
But she being asked according to the form, '`Guilty or not guilty`' readily answered,
'`Guilty.`'
This astonished the judge,
who purposely had got the words willfully and designedly inserted in the indictment,
that from thence she might find occasion to deny the charge,
and so to quash the indictment; and therefore he told her,
that she seemed not duly to consider what she said;
since it could not well be believed that such a one as she,
who it may be inconsiderately had roughly handled her child,
should have killed it willfully and designedly.
Here the judge opened a back door for her to avoid the penalty of death.
But now the fear of God had got so much room in her heart, that no tampering would do;
no fig leaves could serve her for a cover;
for she knew now that this would have been adding sin to sin,
and to cover herself with a covering, but not of God`'s Spirit;
and therefore she plainly signified to the court,
that indeed she had committed the mischievous fact intendedly, thereby to hide her shame;
and that she having sinned thus grievously, and being affected now with true repentance,
she could by no means excuse herself,
but was willing to undergo the punishment the law required;
and therefore she could not but acknowledge herself guilty,
since otherwise how could she expect forgiveness from the Lord?
This undisguised and free confession, being spoken with a serious countenance,
did so affect the judge, that tears trickling down his face, he sorrowfully said, '`Woman,
such a case as this I never met with before; perhaps you, who are but young,
and speak so piously, as being struck to the heart with repentance,
might yet do much good in the world: but now you force me,
that _ex officio_ I must pronounce sentence of death against you,
since you will admit of no excuse.`'
Standing to what she had said, the judge pronounced sentence of death.
And when afterward she came to the place of execution,
she made a pathetical speech to the people, exhorting the spectators,
especially those that were young, '`To have the fear of God before their eyes,
to give heed to his secret reproofs for evil,
and so not to grieve and resist the good spirit of the Lord;
which she herself not having timely minded, it had made her run on in evil,
and thus proceeding from wickedness to wickedness,
it had brought her to this dismal exit.
But since she firmly trusted to God`'s infinite mercy, nay surely believed her sins,
though of a bloody dye, to be washed off by the pure blood of Christ,
she could contentedly depart this life.`'
Thus she preached at the gallows the doctrine of the Quakers, so called,
and gave heart-melting proofs that her immortal soul was to enter into paradise,
as well as anciently that of the thief on the cross.
I have been credibly informed by a person who had it from
the mouths of such as were present at the execution,
that in her request to God she prayed, that it might please him to give a visible sign,
that she was received into his favor.
And that though it was then a cloudy day, yet immediately after she was turned off,
the clouds broke a little, and the sun for a few moments shined upon her face,
and presently after ceased shining, and the sky continued overcast.
She thus in a serious frame of mind, suffered death, which her crime justly deserved.

This year at London died Thomas Loe, a man of an excellent gift,
who zealously had labored in the ministry of the gospel in Ireland,
and by his preaching had brought many over into the society of his friends,
and among others also William Penn, to whom on his deathbed he spoke thus,
'`Bear thy cross, and stand faithful to God;
then he will give thee an everlasting crown of glory, that shall not be taken from thee.
There is no other way which shall prosper than that
which the holy men of old have walked in.
God hath brought immortality to light, and life immortal is felt.
Glory, glory to him, for he is worthy of it.
His love overcomes my heart, nay, my cup runs over: glory be to his name forever.`'
No wonder that this speech of one that was at the point of entering into eternity,
confirmed William Penn exceedingly in that doctrine, which he had now embraced as truth.
At another time Thomas Loe said to his friends that stood at his bedside,
'`Be not troubled, the love of God overcomes my heart.`'
And to George Whitehead and others he said, '`The Lord is good to me;
this day he hath covered me with his glory.
I am weak, but am refreshed to see you.
The Lord is good to me.`'
Another friend asking him how it was with him, he answered, '`I am near leaving you,
I think: but am as well in my spirit as I can desire: I bless the Lord:
I never saw more of the glory of God than I have done this day.`'
And when it was thought he was departing, he began to sing praises to the Lord, saying,
'`Glory, glory to thee forever!`' Which did not a little affect the standers by,
thus to hear a dying man sing.
And in this glorious state he departed this life the 5th of October.

Now since persecution was at a stand this year at London,
those of other persuasions sometimes bitterly inveighed
from the pulpit against the Quakers,
and would challenge them also to a dispute.
William Burnet and Jeremy Ives, eminent Baptist teachers,
had encountered George Whitehead this summer at Chertsey, and Horn, in Surry,
about the resurrection, and Christ`'s body in heaven,
endeavoring to blacken the Quakers in respect of those points,
because they kept to Scripture words, from which the others departing,
advanced very gross absurdities.

One Thomas Vincent, a Presbyterian teacher,
was much disturbed because some of his auditory were
gone over to the society of the Quakers;
and to render them odious,
he and his fellow teachers accused them of erroneous doctrine concerning the Trinity;
and this was chiefly because they did not approve of such
expressions as were not to be found in the holy Scriptures,
as that of Three persons.
On this subject a dispute was held in the Presbyterian meeting-house at London,
between the said Vincent on one side, and George Whitehead on the other.
That which Vincent and his brethren advanced first, was an accusation,
that the Quakers held damnable doctrine.
George Whitehead denying this,
would have given the people an information of the principles of his friends;
but Vincent instead thereof, stated this question, '`Do you own one Godhead,
subsisting in three distinct and separate persons`'?`' Whitehead
and those with him denying this as an unscriptural doctrine,
Vincent framed this syllogism.

[quote]
____
There are Three that bear record in heaven, the Father, the Word, and the Holy Ghost:
and these three are one.

These are either three manifestations, three operations, three substances,
or three somethings else besides subsistences.

But they are not three manifestations, three operations, three substances,
nor three any things else besides subsistences.

Ergo, Three subsistences.
____

G+++.+++ Whitehead rejected these terms, as not to be found in Scripture,
not deducible from the 1 John 5:7, the place Vincent instanced.
And therefore he desired an explanation of those terms,
insomuch as God did not use to wrap up his truths in heathenish metaphysics,
but in plain language.
But whatever was said, no better explanation could be obtained, than person,
or the mode of a substance.
G+++.+++ Whitehead and William Penn, who also was there, alleged several places from Scripture,
proving God`'s complete unity: and they queried how God was to be understood,
if in an abstracted sense from his substance?
But instead of answering the question,
they concluded it a point more fit for admiration than disputation.
Then W. Penn denied the minor proposition of Vincent`'s syllogism; '`For,`' said he,
'`no one substance can have three distinct subsistences, and preserve its own unity:
for every subsistence will have its own substance; so that three distinct subsistences,
or manners of beings, will require three distinct substances or beings:
consequently three Gods:
for if the infinite godhead subsists in three separate manners or forms,
then is not any one of them a perfect and complete subsistence without the other two:
so parts, and something finite is in God; or if infinite,
then three distinct infinite subsistences; and what is this, but to assert three Gods,
since none is infinite but God?
On the contrary, there being an inseparability betwixt the substance and its subsistence,
the unity of substance will not admit a Trinity of
incommunicable or distinct subsistences.`'

After several words on both sides, G. Whitehead,
to bring this strange doctrine nearer to the capacity of the people,
comparing their three persons to three apostles, said, he did not understand, how Paul,
Peter, and John could be three persons and one apostle.
At which one Mad-docks, one of Vincent`'s assistants, framed this odd syllogism;
'`He that scornfully and reproachfully compares our
doctrine of the blessed Trinity of Father,
Son, and Spirit, one in essence, but three in persons, to three finite men, as Paul,
Peter, and John, is a blasphemer.
But you, G. Whitehead, have done so.
Ergo.
A rash conclusion; but how firm, let the judicious reader determine.
I have no mind to enter further into this quarrel,
since the parties on both sides went away unsatisfied:
for Vincent had not been able to prove the doctrine of the Quakers damnable,
as he had asserted.
But his passion had transported him,
as well as when he said from the pulpit to those of his society,
that he had as lief they should go to a bawdy-house,
as to frequent the Quakers`' meetings, because of their erroneous and damnable doctrines.
And pointing to the window he further said, '`If there should stand a cup of poison,
I would rather drink it, than suck in their damnable doctrines.`'
But this untimely zeal did not profit him;
for it gave occasion to some of his hearers to inquire into the doctrines of the Quakers;
and thus some came to be convinced of the truth thereof.

Now since the aforesaid dispute made a great noise at London,
William Penn published a book with this title, [.book-title]#The Sandy Foundation Shaken,#
in which he explained the points controverted,
and defended his positions with good reason and the Holy Scriptures.
But yet this book, which he himself spread, caused such a stir,
that it was evil spoken of, and not long after he was committed to the Tower,
and some thought it was not without his father`'s being acquainted with it,
perhaps to prevent a worse treatment.

This was at the latter end of the year,
about which time Josiah Coale fell into a sickness,
which took him off the stage of this life; he had languished long,
and yet did not at all spare his voice,
but was used both in preaching and praying so to raise it,
that he spent his natural strength exceedingly,
though he was yet as in a flourishing age; nay,
it was his life and joy to declare the gospel, and to proclaim the word of God,
for which he had an excellent ability: and when he spoke to the ungodly world,
an awful gravity appeared in his countenance,
and his words were like a hammer and a sharp sword.
But though he was a son of thunder,
yet his agreeable speech flowed from his mouth like a pleasant stream,
to the consolation and comfort of pious souls.
Oh! how pathetically have I heard him pray, when he, as transported and ravished,
humbly beseeched God, that it might please him to reach to the hard-hearted,
to support the godly, and to preserve them steadfast: nay,
with what a charming and melodious voice did he sound forth the praises
of the Most High in his public prayers! but his work was now done,
he had finished his course, and a time of rest from his labors was come.
Although he grew weak, yet his manly spirit and great courage bore him up for some time;
but his disease, which seemed to be a kind of consumption, at length so increased,
that he was fain to keep within doors for several weeks; then mending a little,
he went abroad again, and came into a meeting in London,
where I beheld his countenance much unlike what it used to be,
for it clearly manifested his bodily indisposition:
nevertheless he preached with a godly zeal,
and his salutary exhortations flowed like a stream from his lips,
which seemed to be touched with a coal from the altar of heaven,
whilst he was preaching the gospel to the edification of his hearers.
Now he began to lift up his voice again to that degree, that judging from thence,
one would have supposed him to have been pretty well restored:
but the ground of his distemper not being taken away,
he was soon necessitated to keep at home again;
and his natural strength wasted away so fast, and he so declined,
that his death began to be expected, which not very long after fell out accordingly.
A little before he died, G. Fox being come to see him, asked him,
whether any thing lay upon him to write to the friends in England?
But he signified that he had nothing to write,
only desired that his love might be remembered to them,
and desired G. Fox to pray to God, that he might have an easy passage,
for he felt his end approaching.
He having complied with his desire, and seeing him begin to be heavy,
bid him go and lie on the bed: which J. Coale did; but finding this, as it seems,
more uneasy, with the help of his friends he rose again, and sat on the side of the bed;
and his friends sitting about him, he felt himself so lively and powerfully raised,
that he spoke to them after this manner:

[.embedded-content-document.testimony]
--

Well, friends, be faithful to God, and have a single eye to his glory;
and seek nothing for self, or your own glory; and if any thing of that arise,
judge it down by the power of the Lord God, that so ye may be clear in his sight,
and answer his witness in all people; then will ye have the reward of life.
For my part, I have walked in faithfulness with the Lord;
and I have thus far finished my testimony, and have peace with the Lord:
his majesty is with me, and his crown of life is upon me.
So mind my love to all friends.

--

Then he ceased speaking; and a little time after he said to Stephen Crisp, '`Dear heart,
keep low in the holy seed of God, and that will be thy crown forever.`'
After a short pause, he said, '`a minister of Christ, must walk as he walked.`'

A little afterwards fainting, and being stayed by his friends, he departed in their arms,
without the least sigh or groan, but as one falling into a sweet sleep;
and being filled with heavenly consolations, he passed from this mortal life,
to that which is immortal, having attained the age of thirty-five years and two months,
and preached the gospel about twelve years.
He had travelled much in the West Indies, sustained great hardships,
and labored in the ministry at his own charge,
being freely given up to spend his substance in the service of the Lord.
And though he went through many persecutions, imprisonments, and other adversities,
yet he was not afraid of danger, but always valiant; and continued in an unmarried state,
that so he might more freely labor in the heavenly harvest,
and many were converted by his ministry.
He lived to see the desire of his heart accomplished;
for when first he was raised up to true goodliness,
being under the sense of his former transgressions, he cried to the Lord for deliverance,
and said with David, '`If thou, O God, wilt help me thoroughly,
then will I teach transgressors thy ways, and sinners shall be converted unto thee.`'
He had been long in a mournful state, though naturally of a cheerful temper;
and having himself passed through a path of sorrow,
he was the more able to comfort the mourners of Zion.
The church was very sensible of this great loss;
and I have reason to think his corpse was attended
to the grave by more than a thousand of his friends,
among whom I was then one; and his burying being very public and well known,
drew the eyes of many spectators towards it.
Let none think it strange, that I have here expatiated somewhat largely,
seeing he was indeed dear to me, and I have his kind usage yet in fresh remembrance;
for the piety of my mother, whom he had seen in England,
caused him to give me marks of the esteem he bore to her memory:
and his excellent endowments so affected me,
that I was eager to go to that meeting where I heard he was likely to be; nay,
I imagined I saw something in him so extraordinary valuable,
that I bore a very reverent respect to him, and the more,
because difference of age deprived me of a familiar conversation with him.

On the 20th of the First month called January, 1668-9, Francis Howgill,
after a sickness of nine days, died in the prison at Appleby,
where he had been kept above five years.
During his sickness he was in perfect good understanding,
and often very fervent in prayer, uttering many comfortable expressions,
to the great refreshment of those about him.
He was often heard to say, '`That he was content to die,
and praised God for the many sweet enjoyments and
refreshments he had received in that his prison-house-bed,
whereon he lay, freely forgiving all who had a hand in his restraint.`'
And said lie, '`This was the place of my first imprisonment for the truth,
here at this town, and if it be the place of my laying down the body, I am content.`'
Several persons of note, inhabitants of Appleby, as the mayor, and others,
came to visit him; and some of these praying that God might speak peace to his soul,
he returned, '`he hath done it.`'
About two days before his departure, being attended by his wife,
and several of his friends, he said to them: '`Friends, as to matter of words,
ye must not expect much more from me, neither is there any great need of it,
or to speak of matters of faith to you who are satisfied:
only that ye remember my dear love to all friends who inquire of me;
for I ever loved friends well, or any in whom truth appeared.
Truly God will own his people, as he hath ever hitherto done,
and as we have daily witnessed; for no sooner had they made the act of banishment,
to the great suffering of many good friends,
but the Lord stirred up enemies against them,
whereby the violence of their hands was taken off`". I say, again,
God will own his people, even all those that are faithful.
And as for me, I am well, and content to die, I am not at all afraid of death;
but one thing was of late in my heart,
and that I intended to have written to George Fox and others,
even that which I have observed, viz. that this generation passeth fast away;
we see many good and precious friends within these few years have been taken from us;
and therefore friends had need to watch, and be very faithful, that we may leave a good,
and not a bad savor, to the next succeeding generation;
for we see that it is but a little time that any of us have to stay here.`'
A few hours before he departed, some friends from other places being come to visit him,
he inquired about their welfare, and prayed fervently, with many heavenly expressions,
that the Lord by his mighty power,
might preserve them out of all such things as would spot and defile.
His voice then, by reason of his great weakness failed him,
and a little after he recovering some strength,`"said,
'`I have sought the way of the Lord from a child, and lived innocently as among men;
and if any inquire concerning my latter end,
let them know that I die in the faith in which I lived, and suffered for.`'
After these words, he spoke some others in prayer to God,
and so sweetly finished his days in peace with the Lord,
in the fiftieth year of his age.

He left a good name behind him amongst all who knew him.--Sometime before his sickness,
considering this mutable state, and finding in himself some decay of nature,
he made his will, in which, as his love was very dear to his brethren,
with whom he had labored in the ministry,
so he gave to each of them a remembrance of his love;
he left also a legacy to his poor friends in those parts where he lived.

For although his moveable goods were forfeited to the king forever,
yet the confiscation of his real estate was only for life;
so that from thence having something left, he could dispose of it by his will.

During his imprisonment,
he neglected not to comfort and strengthen his brethren by writing,
effecting that by his pen, which he could not by word of mouth:
he also defended his doctrine against those who opposed the same; and among others,
he wrote a large treatise against oaths,
contradicting the opinion of those who account it lawful to swear under the gospel.

About two years before his decease,
he wrote an epistle of advice and counsel as his
last will and testament to his daughter Abigail,
a child whom he much loved, who was born in a time of deep exercises and trouble,
which nevertheless by the Lord`'s goodness he was patiently brought through;
wherefore he named this child Abigail, signifying, the father`'s joy.
In this testament he gave her instructions for the future conduct of her life,
the beginning whereof is thus:

[.embedded-content-document.letter]
--

Daughter Abigail, this is for thee to observe and keep,
and take heed unto all the days of thy life,
for the regulating thy life and conversation in this world, that thy life may be happy,
and thy end blessed, and God glorified by thee in thy generation.
I was not born to great possessions, or did inherit great matters in this world;
but the Lord hath always endowed me with sufficiency and enough,
and hath been as a tender father unto me, because my heart trusted in him,
and did love the way of righteousness from a child.
My counsel unto thee is, that thou remember thy Creator in the days of thy youth,
and fear the Lord in thy youth, and learn to know him and serve him all thy days:
first seek the kingdom of God and the righteousness thereof; it is not far from thee,
it is within thee; it consists in life and power, and it stands in righteousness, truth,
and equity, justice, mercy, long-suffering, patience, love, light, and holiness,
this is the being and centre thereof; therefore seek not lo here,
or lo there without thee, in this or that outward observation,
for many seek there and never find it; but seek and thou shalt find,
wait and thou shalt receive.
If thou inquire, in what must I seek?
and what must I wait in?
and how must I seek?
I inform thee, that thou must silence all thy own thoughts,
and thou must turn thy mind to that which is pure, and holy, and good within thyself,
and seek and wait in that in the light of Jesus Christ, wherewith thou art enlightened,
which shows thee when thou dost evil, and checks and reproves; take heed unto that,
and it will show the evil motions and thoughts: and as thou loves it,
it will subdue them, and preserve thee for the time to come out of evil:
for though thou be born into the world a reasonable creature,
yet thou must be born again, and be made a new creature,
or else thou canst not enter into God`'s kingdom;
thou must know the seed of the kingdom in thyself,
of which thou must be born and formed again into God`'s image.
I have told thee God hath sown it in thee, a grain of it, a measure of it,
a portion of it, a measure of light and truth, of righteousness and holiness;
keep in thy mind to that, and love it,
and thou wilt feel the heavenly Father working in thee,
and begetting thee to life through Jesus Christ that hath enlightened thee,
and thou wilt feel the power of the Lord strengthening thee, in thy little,
and making thee to grow in the immortal seed of his kingdom,
and outgrow and overgrow all evil, so that thou wilt daily die to that,
and have no pleasure in it, but in the Lord,
and in his goodness and virtue shed abroad in thy heart,
which thou wilt taste and feel within, and have joy and comfort therein:
love the Lord with thy heart and soul, even him that made thee, and gave thee a being,
and all things in heaven and earth; and still wait for the knowledge of him in thyself,
he is not far from thee, but near unto thee,
and unto all that call upon him in an upright heart;
and do thou inquire of thy dear mother, she will inform thee, she knows him,
and the way to life and peace, and hearken to her instruction: God is a spirit, of light,
and life, and power, that searches the heart, and shows thee when thou dost, or thinks,
or speaks evil, and shows unto man or woman their thoughts.
That which shows the evil, is good, and that which shows a he, is truth; this is within,
take heed to it, this is called God`'s spirit in the Scriptures, believe in it, love it,
and it will quicken thy heart to good, and it will subject the evil:
here is thy teacher near thee, love it, and if thou act contrary, it will condemn thee;
therefore take heed unto this spirit of truth, and it will enlighten and enliven thee,
and will open thy understanding, and give thee to know what God is,
and to do that which is good and acceptable in his sight; this spirit never errs,
but leads out of all error into all truth.
Be sober-minded in thy youth, and wait on the Lord within, hearken unto him.
God is light immortal, life immortal, truth immortal, an everlasting eternal Spirit:
he speaks spiritually and invisibly within the hearts and consciences of men and women:
hear what he speaks, and obey his voice, and thy soul shall live; fear to offend him,
or sin against him, for the wages of sin are death;
therefore prize his love in thy young and tender years,
and do thou read the Scriptures and Friends`' books,
and take heed to what thou reads to obey it, as far as thou understands;
and pray often unto the Lord, that he will give thee his knowledge,
and open thy understanding in the things of his kingdom;
search thy heart often with the light of Christ in thee,
manifest and bring thy deeds to it, that they may be tried;
and examine thyself how the case stands betwixt the Lord and thee;
and if thou sees thyself wrong, humble thyself, and be sorry, and turn unto him,
and he will show thee mercy; and take heed for the time to come,
that thou run not into the same evil again; keep thy heart clean,
watch against the evil in thyself, in that which shows it; therein there is power,
and thereby thou hast power to overcome all evil.
And, dear child, mind not the pleasures of sin, which are but for a moment,
and the end is misery; but keep under and cross thy will and affliction,
so thy mind will have no pleasure in the evil, but in good;
and thou wilt feel the immortal seed springing up in thee,
which God`'s peace and love is to.
O child! these are great and weighty things, not to be slighted.
Accompany thyself always with them that fear the Lord,
and fear and worship him in spirit and truth,
and lead a holy and blameless life and conversation; deny them not, but love them,
and suffer with them.
Take heed that thou follow not the hireling teachers, who preach for gain and lucre,
and abide not in Christ`'s doctrine; believe them not, heed them not,
they do people no good; but thou wilt see them thyself,
they have an outside show of godliness sometimes,
but deny the power of God and true holiness; remember I have told thee,
who have had perfect knowledge of them.
But be sure that thou let nothing separate thy love from God and his people;
those are his people that keep his law, and obey Christ`'s voice, and lead a holy life,
and they were ever hated and belied, and persecuted, and evil-spoken of,
always by bad and evil loose people; these are God`'s people, and his love, and peace,
and blessing is with them; do thou grow as a natural branch,
(up among them,) of the living vine,
and continue all thy days in obedience unto God`'s will,
and thou wilt feel joy and love in thy heart, which above all things covet after,
and thou shalt attain and obtain everlasting peace, which the Lord grant unto thee,
according to the riches of his mercy and love, which endure forever and ever.
Amen.

And now, Abigail, concerning thy well-being in this life,
this is my advice and counsel unto thee; love thy dear mother,
and ever obey her and honor her, and see thou grieve her not;
be not stubborn nor willful, but submit unto her, and be as an obedient child unto her,
whose love and care hath been too great over thee and thy sisters,
which hath brought too much trouble upon herself; learn in thy youth to read and write,
and sew and knit, and all points of good labor that belong to a maid,
and flee idleness and sloth, that nourishes sin; and as thou grows up in years,
labor in the affairs of the country, and beware of pride, and riotousness, and curiosity,
but be well content with such apparel as thy mother will permit thee,
that thou mayest be a good example unto others.
Be not wanton, nor wild, nor light, but temperate, moderate, and chaste,
and not forward in words, nor speech, but swift to hear, slow to speak;
and do thou always live with thy mother, and be a help unto her,
and cherish her in her old age and latter years, that she may be comforted in thee,
and her soul may bless thee.
Love thy sisters, and be always courteous to them and thy brother,
encourage one another in good: and if thou live to be a woman of perfect years,
keep thyself unspotted, and let not thy mind out after sports nor pastimes,
the end of all those is sorrow: neither after young men; if thou have a desire to marry,
do not thou seek a husband, but let a husband seek thee; and if thou live in God`'s fear,
and an honest life and virtuous, them that fear God will seek unto thee;
let not thy affections out unto every one that proffers love, but be considerate,
and above all things, choose one, (if thou dost marry,) that loves and fears the Lord,
whose conversation and manner, and course of life, thou knows well,
before thou give consent.
Be discreet and wise, hide nothing from thy mother, and she will advise thee, no doubt,
for thy good; and if she be living, marry not without her consent:
and if thou join to a husband, be sure thou love him in thy heart,
and be obedient unto him, and honor him among all, so will his heart be more to thee,
and his love increase; grieve him not, but be gentle, and easy to be intreated,
and mind thy own business; and if the Lord give thee children,
bring them up in God`'s fear, and good exercise, and keep them in subjection unto thee,
and be an example of virtue and holiness unto them,
that the Lord`'s blessing thou mayest feel in youth and in age, and all thy life long.
O Abigail! remember these things, keep in mind these things,
read often this writing over, get it copied over, and lay up my words in thy heart,
and do them, so wilt thou be happy in this life, and in the life to come:
these things I give thee in charge to observe, as my mind and will,
and counsel unalterable unto thee, as witness hereof I have set my hand,

[.signed-section-closing]
Thy dear father,

[.signed-section-signature]
Francis Howgill.

[.signed-section-context-close]
The 26th of the 5th Month, 1666.

--

In the beginning of this year the members of this society,
held a general Yearly-meeting at London, which since that time,
hath been used to be held there annually, in the week called Whitsun-week,^
footnote:[It hath since been fixed to be held on the Second-day
immediately following the third First-day in the 5th month.]
because at that time of the year it is commonly best traveling, etc.
Several are deputed from all places to this meeting,
and what concerns the church in general, is there treated on.

Persecution for religion seemed now to be at a stand,
which displeased some of the most rigid sort of churchmen,
which we not only have already, but may again in due place demonstrate.

About this time, as I take it, a certain bishop said occasionally,
that the Quakers by their unlimited freedom, increased much,
and therefore it was very needful to take care of them,
seeing they often had much greater assemblies than the national church; '`For,`' said he,
'`at such a time I preached myself, and there were but a few hearers,
when at the same time the Quakers`' meeting just by was crowded full;
and thereupon he desired them to consider whether
it was not high time to stop these sectaries?
After he had set forth his matter at large, another lord then present among others, said,
that indeed it seemed that the lord bishop had spoken what was very reasonable,
that the sectaries had often more hearers than the national church-preachers,
and that it was not strange to him that it displeased him,
since he took so much upon himself; '`For,`' said he, '`his lordship observed,
that he preached himself; and the professed Quakers, who had such great assemblies,
preached Christ Jesus, and therefore no wonder that they had the more hearers.`'
This was such a witty turn upon the bishop,
as no doubt made him so sensible as not to think
fit to enter upon the debate in a doubtful dispute,
for it is observable,
this lord`'s turn upon the bishop was chiefly to stop him from promoting persecution.

This spring G. Fox traveling to York,
went through several other places in the North of England;
and although he came near to his old enemy, colonel Kirby, who had a fit of the gout,
and had threatened him, yet he passed on unmolested.
So he went to Liverpool, whence he, with some of his friends, passed over for Ireland:
among others, were Thomas Briggs and John Stubbs; and being arrived at Dublin,
he was kindly received by his friends; and journeying into the country,
he met with no small opposition from the Papists, of whom there are many there.
Being come to a certain place, he challenged the Jesuits, priests, and monks,
to try whether their god, which they make of a wafer, be an immortal god,
but they could not be brought to it; wherefore he said,
they were worse than Baal`'s priests, for Baal`'s priests tried their god.
Then he went to Cork, where they had knowledge of his coming,
and intended to take him prisoner;
for the Quakers in Ireland were many years sharply persecuted,
as their brethren were in England,
of which to mention all circumstances it would make a very large treatise.
At this time there were many prisoners at Cork, among whom was Samuel Thornton,
with whom I was well acquainted,
who being met with his friends in a chamber one First-day,
the officer Quinnal came and shut the door of the room, and locked them in,
to the number of eighty persons, and carried the key to the mayor, Matthew Dean,
who gave order that there should neither victuals nor drink be carried to them,
and they could only get what was pulled up with ropes through the grate,
or thrown in through a hole: under this chamber the soldiers were ordered to keep guard,
that none might get away, and they made so great a smoke,
that many of the prisoners were sick, among whom were some weakly old people,
and some women with child, and nurses, who were almost stifled;
and complaint thereof being made to the mayor, he answered in a scoffing manner,
'`They are all brethren and sisters, let them lie upon one another;
and if they are stifled it is their own fault.`'
Thus they were kept twenty-four hours, and afterwards some of them made prisoners.

Solomon Eccles, whom I also knew very well,
was this year in prison at Gallaway in Ireland, where he was put, by a strange accident.
He was an extraordinary zealous man, and what he judged evil he warmly opposed,
even to the hazard of his life.
This zeal led him to perform a strange action in
a chapel of the Papists without the town;
for he went naked above his waist,
with a chafing-dish of coals and burning brimstone on his head,
and entered the chapel when all the people were on their knees to pray to their idol,
and spoke as follows: '`Woe to these idolatrous worshippers!
God hath sent me this day to warn you,
and to show you what will be your portion except you repent.`'
Which when he had done, he went away to the town, where he was presently made a prisoner.
What the benefit of this strange action might be, I leave.

Amongst the martyrs of the reformed,
we find some instances of persons zealous to a strange degree,
as of William Gardiner at Lisbon, and Bertrand le Bias at Tournay,
whose actions were not less remarkable; for this last,
his snatching the host from the priest in their church as they were at mass,
was certainly a bold attempt, and not praiseworthy,
if it was only an act of human contrivance;
but I shall leave the judgment thereof unto God, as I account it safest, and the rather,
because under the sharpest punishment they could inflict, they seemed not to shrink,
but rather to be strengthened.
However so sharp a trial did not fall to Eccles`'s portion,
and I think it safer not to judge hastily of this uncommon performance.
He was, to my knowledge, a bold and undaunted man, and before this action in the chapel,
as above, he did something of a like nature at London at the fair-time,
amongst the plays,
where he suffered much by the coachmen whipping him grievously on his naked back;
but that could not lay his fervent zeal,
which was kindled not only against the immodest and
ungodly carriage of the pretended fools,
but also against those other vanities there used.
To what height his zeal carried him, the following instance will show:
he who had been a member of the church of England, and then went to the Presbyterians,
and afterwards among the Independents, and after that was a Baptist,
had been an eminent musician, so that by his art he could get near 150£. a-year;
but at last being a Quaker, he could not follow for conscience-sake,
what he now called his Babylonish trade of music:
wherefore he learned to make clothes to get his living by,
and sold his musical books and instruments; but, as he declared,
he had no peace in his conscience; for observing them to be instruments of vanity,
he judged they ought to be destroyed, and therefore bought them again,
although they were worth above 20/. and carried them, viz. virginals, fiddles,
etc. to Tower-hill, where laying them together, he set fire to them;
but when some who were by, endeavored to hinder him,
and to get one of the virginals away, he stamped upon it with his foot,
and would not rest until he had destroyed it; and after that he said,
he found peace in his conscience,
having made an offering of that which he once entirely loved,
and in the use of which he was educated; for not only his father and grandfather,
but his grandfather`'s father had been musicians,
and he himself had the name of an eminent music-master.

Another account we have of his strange zeal:
when he saw how the Quakers were belied by William Burnet, Jeremy Ives,
and Matthew Kiffin, teachers amongst the Baptists,
as if they believed not in Christ nor the resurrection, he challenged all the teachers,
and priests, and Jesuits, openly in a book which he printed, to come to a proof with him,
who were the true worshippers; first, to fast seven days and seven nights,
and neither to eat nor drink; and then the next seven days not to sleep day nor night;
but we may well think that none were to be found to enter the lists with him,
nor to put themselves on such a test; and although some reckoned him out of his wits,
yet he was not, for I remember the time very well,
and had many an opportunity both to see and to hear him speak.

I now return to G. Fox at Cork in Ireland, where they intended to take him,
nevertheless they let him go unmolested, although he rode through the market,
by the mayor`'s door, who not only saw him, but said,
'`There goes G. Fox,`' and yet he let him pass quietly.
After he had travelled through many places in Ireland, he came again to Dublin,
from whence he returned to England, and coming into Gloucestershire,
he heard at Nailsworth of a report which had been spread abroad in the country,
that he was turned Presbyterian, and they had prepared a pulpit for him in the open yard,
where he was to preach.
G+++.+++ Fox hearing this, thought it very strange, whereupon he went to the place spoken of,
where he indeed found a pulpit; but the case was this: a certain Presbyterian preacher,
named John Fox, who went preaching about the country, was to pi-each there,
and it seems some had changed his name from John to George,
whereupon it was reported that he was turned from being a Quaker, to be a Presbyterian:
this begat so great a curiosity in the people,
that many went thither to hear this Quaker turned Presbyterian;
so this John Fox came to have a great auditory of several hundreds,
who would not have went a foot to have heard him, had they known it.
Now some hundreds of them hearing afterwards that
the real G. Fox was not far off at a meeting,
they went thither and were sober and attentive;
where they were by him directed to the grace of God in themselves,
which would teach them and bring them salvation.
And when the meeting was over, some of the people said,
they liked George Fox the Quaker`'s preaching, better than G. F. the Presbyterian.
Not long after this John Fox was complained of in the house of commons,
for having a tumultuous meeting, in which treasonable words were spoken.
This John Fox had formerly been priest of Marshfield in Gloucestershire,
and being put out of that place,
was afterwards permitted by a common-prayer priest to preach sometimes in his steeple-house;
at length this Presbyterian priest presuming too
far upon the parish priest`'s former grant,
began to be more bold than welcome,
and would have preached there whether the priest would or not;
which caused a great bustle and contest between the two priests,
and their hearers on either side, in which the common-prayer book was cut to pieces,
and it is said some treasonable words were then spoken,
by some of the followers of this John Fox;
which case was quickly put into the newspapers,
and some malicious Presbyterians caused it to be
so worded as if it had proceeded from G. F. the Quaker,
but some members of the house of commons certified it under their hands,
that it was John Fox, formerly priest of Marshfield,
who was complained of to be the ringleader of that unlawful assembly.

After this G. F. travelled to Bristol, where he met with Margaret Fell, then a widow,
who came thither to visit her daughter Yeomans.
He had before this intimated to her his affection,
and proposed to take her in marriage at a suitable time;
but though he had a sense in himself, it was of the Lord,
yet he did not at first find a freedom to accomplish the same,
but all obstructions being now removed, he so proposed the matter,
that if she was willing to give her consent, that the same should be accomplished,
she might first send for her children; who being come,
he asked both her daughters and their husbands,
whether they had any thing against his taking their mother to be his wife?
And they all severally expressed their satisfaction therein.
Then he asked Margaret, whether she had performed her husband`'s will?
And the children, whether, if their mother married, they should lose by it?
The children said, she had answered it to them, and desired him to speak no more of that.
So observing they were all well satisfied, he proceeded in his marriage,
and took Margaret Fell to wife in a public meeting of friends in Bristol.
She was a woman of a noble endowment, and this I know not only by her writings,
but I have also heard her preach an hour together,
delivering her matter compactly and orderly.

G+++.+++ F. being married, he stayed with his wife about a week in Bristol,
and then they went together to Oldstone, and there taking leave of each other,
they parted, she went homeward into the north, and he travelled through Wiltshire,
Berkshire, Oxfordshire, Bucks, and so to London: for although now he had a wife,
yet he did not neglect his care towards the churches, all the nation over,
in the gift which he had received of God, both in word and writing to their edification,
and among the rest he had a special regard, that the poor might be taken care of,
to which end he wrote an epistle in London, to this effect,
that poor children should be put forth apprentices to trades, whereby in time,
they might help their aged parents, and enable them to bring up their families,
and maintain themselves handsomely.

G+++.+++ Fox stayed not long in London; but the year 1670 being now come,
he travelled through Hertfordshire, Cambridgeshire, Huntingdonshire, and Leicestershire,
where he expected to have met with his wife; for he had wrote her word,
if she found it convenient, to meet him there;
but instead thereof he understood she was hauled
out of her house and carried to Lancaster prison,
upon the old premunire, which was executed upon her five years before,
from which she was discharged by order of the king and council the last year.
Wherefore, after he had visited friends in those counties, he returned to London,
where he found two of his wife`'s daughters, whom he hastened to go to the king,
to acquaint him how their mother was dealt with, which they did,
but met with much difficulty; yet they diligently attended the same,
as it behooved them for their mother, who was a mother or overseer of the church also,
and therefore of the greater concern; but at last through assiduous application,
they got to "`the speech of the king, to whom one of them said,
that instead of their waiting upon him to return
him thanks for the discharge of their mother,
they were now necessitated to make complaint of their
mother`'s being cast into prison a second time.
Whereupon the king gave command to sir John Otway, to write to the sheriff of Lancashire,
to set her at liberty,
which letter G. F. accordingly hastened his daughters with into the country.

The parliament now sitting, made a law, entitled.
_An Act to Prevent and Suppress Seditious Conventicles,_ which is as follows:

[.embedded-content-document.legal]
--

For providing farther and more speedy remedies against the
growing and dangerous practices of seditious sectaries,
and other disloyal persons, who under pretense of tender consciences,
have or may at their meetings contrive insurrections,
(as late experience hath shown,) (2) Be it enacted by the king`'s most excellent majesty,
by and with the advice and consent of the lords spiritual and temporal,
and commons in this present parliament assembled, and by authority of the same,
that if any person of the age of sixteen years or upwards, being a subject of this realm,
at any time after the tenth day of May next, shall be present at any assembly,
conventicle, or meeting, under color or pretense of an exercise of religion,
in other manner than according to the liturgy and practice of the church of England,
in any place within the kingdom of England, dominion of Wales,
or town of Berwick-upon-Tweed, at which conventicle, meeting, or assembly,
there shall be five persons or more assembled together,
over and besides those of the same household,
if it be in a house where there is a family inhabiting; or if it be in a house, field,
or place where there is no family inhabiting; then where any five persons or more,
are so assembled, as aforesaid,
it shall and may be lawful to and for any one or more justices of the peace of the county,
limit, division, corporation or liberty,
wherein the offense aforesaid shall be committed,
or for the chief magistrate of the place where the offense aforesaid shall be committed;
and he and they are hereby required and enjoined upon proof
to him or them respectively made of such offense,
either by confession of the party, or oath of two witnesses;
(3) (which oath the said justice and justices of the peace,
and chief magistrate respectively,
are hereby empowered and required to administer,) or be
notorious evidence and circumstance of the fact,
to make a record of every such offense under his or their hands and seals respectively:
which record so made, as aforesaid,
shall to all intents and purposes be in law taken and adjudged to be a
full and perfect conviction of every such offender for such offense:
and thereupon the said justice, justices, and chief magistrate respectively,
shall impose on every such offender so convicted, as aforesaid,
a fine of five shillings for such first offense:
which record and conviction shall be certified by the said justice, justices,
or chief magistrate, at the next quarter-sessions of the peace,
for the county or place where the offense was committed.

[.numbered]
II. And be it further enacted by the authority aforesaid,
that if such offender so convicted, as aforesaid,
shall at any time again commit the like offense or offenses, contrary to this act,
and be thereof in manner aforesaid convicted,
then such offender so convict of such like offense or offenses
shall for every such offense incur the penalty of ten shillings;
(2) which fine and fines, for the first and every other offense,
shall be levied by distress and sale of the offender`'s goods and chattels;
or in case of the poverty of such offender,
upon the goods and chattels of any other person or persons who shall be then
convicted in manner aforesaid of the like offense at the same conventicle,
at the discretion of the said justice justices or chief magistrate respectively,
so as the sum to be levied on any one person in case of the poverty of other offenders,
amount not in the whole to above the sum of ten pounds, upon occasion of any one meeting,
as aforesaid; (3) and every constable, head-borough, tithingman, churchwardens,
and overseers of the poor respectively,
are hereby authorized and required to levy the same accordingly,
having first received a warrant under the hands and seals of the said justice, justices,
or chief magistrate respectively, so to do; (4) the said monies so to be levied,
to be forthwith delivered the same justice, justices, or chief magistrate,
and by him or them to be distributed,
the one third part thereof to the use of the king`'s majesty, his heirs and successors,
to be paid to the high sheriff of the county for the time being, in manner following;
that is to say,
the justice or justices of peace shall pay the same
into the court of the respective quarter-sessions,
which said court shall deliver the same to the sheriff,
and make a memorial on record of the payment and delivery thereof,
which said memorial shall be a sufficient and final
discharge to the said justice and justices,
and a charge to the sheriff,
which said discharge and charge shall be certified into the exchequer together,
and not one without the other:
and no justice shall or may be questioned or accountable
for the same in the exchequer or elsewhere,
than in quarter-sessions;
another third part thereof to and for the use of the poor
of the parish where such offense shall be committed;
and the other third part thereof to the informer and informers
and to such person and persons as the said justice,
justices or chief magistrate respectively shall appoint,
having regard to their diligence and industry in the discovery,
dispersing and punishing of the said conventicles.

[.numbered]
III.
And be it further enacted by the authority aforesaid,
that every person who shall take upon him to preach or teach in any such meeting,
assembly or conventicle, and shall thereof be convicted, as aforesaid,
shall forfeit for every such first offense the sum of twenty pounds,
to be levied in manner aforesaid upon his goods and chattels;
(2) and if the said preacher or teacher so convicted, be a stranger,
and his name and habitation not known, or is fled, and cannot be found,
or in the judgment of the justice,
justices or chief magistrate before whom he shall be convicted,
shall be thought unable to pay the same, the said justice, justices,
or chief magistrate respectively,
are hereby empowered and required to levy the same by warrant, as aforesaid,
upon the goods and chattels of any such persons who shall be present at the same conventicle;
any thing in this or any other act, law, or statute to the contrary notwithstanding;
and the money so levied, to be disposed of in manner aforesaid:
(3) and if such offender so convicted as aforesaid,
shall at any time again commit the like offense or offenses contrary to this act,
and be thereof convicted in manner aforesaid,
then such offender so convicted of such like offense or offenses,
shall for every such offense, incur the penalty of forty pounds,
to be levied and disposed, as aforesaid.

[.numbered]
IV. And be it further enacted by the authority aforesaid,
that every person who shall wittingly and willingly suffer any such conventicle, meeting,
or unlawful assembly aforesaid, to be held in his or her house, outhouse, barn, yard,
or backside, and be convicted thereof in manner aforesaid,
shall forfeit the sum of twenty pounds, to be levied in manner aforesaid,
upon his or her goods and chattels; or in case of his or her poverty or inability,
as aforesaid,
upon the goods and chattels of such persons who shall be convicted in manner aforesaid,
of being present at the same conventicle; and the money so levied,
to be disposed of in manner aforesaid.

[.numbered]
V+++.+++ Provided always, and be it enacted by the authority aforesaid,
that no person shall by any clause of this act be
liable to pay above ten pounds for any one meeting,
in regard of the poverty of any other person or persons.

[.numbered]
VI. Provided also, and be it further enacted, that in all cases of this act,
where the penalty or sum charged upon any offender exceeds the sum often shillings,
and such offender shall find himself aggrieved,
it shall and may be lawful for him within one week after
the said penalty or money charged shall be paid or levied,
to appeal in writing from the person or persons convicting,
to the judgment of the justices of the peace in their next quarter-sessions,
(2) to whom the justice or justices of the peace, chief magistrate, or alderman,
that first convicted such offender, shall return the money levied upon the appellant,
and shall certify under his and their hands and seals
the evidence upon which the conviction passed,
with the whole record thereof, and the said appeal:
(3) whereupon such offender may plead and make defense,
and have his trial by a jury thereupon:
(4) and in case such appellant shall not prosecute with effect,
or if upon such trial he shall not be acquitted,
or judgment pass not for him upon his said appeal,
the said justices at the sessions shall give treble
costs against such offender for his unjust appeal:
(5) And no other court whatsoever shall intermeddle
with any cause or causes of appeal upon this act,
but they shall be finally determined in the quarter-sessions only.

[.numbered]
VII.
Provided always, and be it further enacted, that upon the delivery of such appeal,
as aforesaid,
the person or persons appellant shall enter before the person or persons convicting,
into recognizance, to prosecute the said appeal with effect:
(2) which said recognizance the person or persons
so convicting is hereby empowered to take,
and required to certify the same to the next quarter-sessions:
(3) and in case no such recognizance be entered into,
the said appeal to be null and void.

[.numbered]
VIII.
Provided always,
that every such appeal shall be left with the person or persons so convicting,
as aforesaid, at the time of the making thereof

[.numbered]
IX. And be it further enacted by the authority aforesaid, that the justice,
justices of the peace, and chief magistrate respectively, or the respective constables,
head-boroughs, and tithingmen, by warrant from the said justice, justices,
or chief magistrate respectively, shall and may with what aid,
force and assistance they shall think fit, for the better execution of this act,
after refusal or denial to enter, break open, and enter into any house or other place,
where they shall be informed any such conventicle, as aforesaid, is or shall be held,
as well within liberties as without:
(2) and take into their custody the persons there unlawfully assembled,
to the intent they may be proceeded against according to this act:
(3) and that the lieutenants or deputy-lieutenants,
or any commissionated officer in the militia, or other of his majesty`'s forces,
with such troops or companies of horse and foot; and also the sheriffs,
and other magistrates and ministers of justice, or any of them, jointly or severally,
within any of the counties or places within this kingdom of England, dominion of Wales,
or town of Berwick-upon-Tweed, with such other assistance as they shall think meet,
or can get in readiness with the soonest,
on certificate made to them respectively under the hand
and seal of any one justice of the peace or chief magistrate,
of his particular information or knowledge of such unlawful meeting or conventicle held,
or to be held in their respective counties or places,
and that he with such assistance as he can get together,
is not able to suppress and dissolve the same, shall and may,
and are hereby required and enjoined to repair unto the place where they are so held,
or to be held, and by the best means they can, to dissolve,
dissipate or prevent all such unlawful meetings,
and take into their custody such and so many of the said
persons so unlawfully assembled as they shall think fit,
to the intent that they may be proceeded against according to this act.

[.numbered]
X+++.+++ Provided always, that no dwelling-house of any peer of this realm,
where he or his wife shall then be resident, shall be searched by virtue of this act,
but by immediate warrant from his majesty, under his sign manual,
or in the presence of the lieutenant, or one deputy-lieutenant,
or two justices of the peace, whereof one to be of the quorum,
of the same county or riding.

[.numbered]
XI. And be it further enacted by the authority aforesaid, that if any constable,
head-borough, tithingman, churchwarden or overseer of the poor, who shall know,
or be credibly informed of any such meetings or conventicles held within his precincts,
parishes, or limits, and shall not give information thereof to some justice of the peace,
or the chief magistrate,
and endeavor the conviction of the parties according to his duty; but such constable,
head-borough, tithingman, churchwarden, overseers of the poor,
or any person lawfully called in aid of the constable, head-borough, or tithingman,
shall willfully and wittingly omit the performance of his duty,
in the execution of this act, and be thereof convicted in manner aforesaid,
he shall forfeit for every such offense, the sum of five pounds,
to be levied upon his goods and chattels, and disposed in manner aforesaid:
(2) and that if any justice of the peace, or chief magistrate,
shall willfully and wittingly omit the performance
of his duty in the execution of this act,
he shall forfeit the sum of one hundred pounds,
the one moiety to the use of the informer, to be recovered by action, suit, bill,
or plaint, in any of his majesty`'s courts at Westminster, wherein no essoin, protection,
or wager of law shall lie.

[.numbered]
XII.
And be it further enacted by the authority aforesaid,
that if any person be at any time sued for putting in execution
any of the powers contained in this act,
otherwise than upon appeal allowed by this act,
such person shall and may plead the general issue,
and give the special matter in evidence; (2) and if the plaintiff be non-suit,
or a verdict pass for the defendant, or if the plaintiff discontinue his action,
or if upon demurrer judgment be given for the defendant,
every such defendant shall have his full treble costs.

[.numbered]
XIII.
And be it further enacted by the authority aforesaid, that this act,
and all clauses therein contained,
shall be construed most largely and beneficially for the suppressing of conventicles,
and for the justification and encouragement of all
persons to be employed in the execution thereof:
(2) and that no record, warrant, or mittimus to be made by virtue of this act,
or any proceedings thereupon, shall be reversed, avoided,
or any way impeached by reason of any default in form.
(3) And in case any person offending against this act,
shall be an inhabitant in any other county or corporation,
or fly into any other county or corporation after the offense committed,
the justice of peace or chief magistrate before whom he shall be convicted as aforesaid,
shall certify the same under his hand and seal,
to any justice of peace or chief magistrate of such other county
or corporation wherein the said person or persons are inhabitants,
or are fled into; (4) which said justice or chief magistrate respectively,
is hereby authorized and required to levy the penalty or penalties in this act mentioned,
upon the goods and chattels of such person or persons,
as fully as the said other justice of peace might have done,
in case he or they had been inhabitants in the place where the offense was committed.

[.numbered]
XIV.
Provided also,
that no person shall be punished for any offense against this act unless such
offender be prosecuted for the same within three months after the offense committed.
(2) And that no person who shall be punished for any offense by virtue of this act,
shall be punished for the same offense by virtue of any other act or law whatsoever.

[.numbered]
XV. Provided, and be it further enacted by the authority aforesaid,
that every alderman of London for the time being, within the city of London,
and the liberties thereof, shall have,
(and they and every of them are hereby empowered and required
to execute,) the same power and authority within London,
and the liberties thereof, for the examining, convicting,
and punishing of all offenses within this act committed within London,
and the liberties thereof,
which any justice of peace hath by this act in any county of England,
and shall be subject to the same penalties and punishments,
for not doing that which by this act is directed to be done
by any justice of peace in any county of England.

[.numbered]
XVI.
Provided, and be it enacted by the authority aforesaid, that if the person offending,
and convicted as aforesaid, be a femme-covert, cohabiting with her husband,
the penalties of five shillings, and ten shillings, so as aforesaid incurred,
shall be levied by warrant, as aforesaid,
upon the goods and chattels of the husband of such femme-covert.

[.numbered]
XVII.
Provided also,
that no peer of this realm shall be attached or imprisoned
by virtue or force of this act;
any thing, matter, or clause, therein to the contrary notwithstanding.

[.numbered]
XVIII.
Provided also, that neither this act, nor any thing therein contained,
shall extend to invalidate or make void his majesty`'s supremacy in ecclesiastical affairs:
(2) but that his majesty, and his heirs and successors, may from time to time,
and at all times hereafter,
exercise and enjoy all powers and authority in ecclesiastical affairs,
as fully and as amply as himself or any of his predecessors
have or might have done the same:
any thing in this act notwithstanding.

--

By this very law many an honest family was impoverished;
for the Quakers did not leave off meeting together publicly,
but the most sincere amongst them were the more zealous,
and they were the more winnowed from the chaff,
which in time of ease gets in amongst religious professors; and none need wonder at it,
since the Quakers having gained the repute of an upright-hearted people, some,
for by-ends, might creep in amongst them.

At London, as well as at other places,
many were spoiled of their goods very unmercifully,
and many times people of good substance brought to mere poverty,
seeing not only the shop goods of some, but also their household goods have been seized,
insomuch that the very sick have had their beds taken from under them,
and they themselves laid upon the floor; nay, they have been so cruel,
as to leave them nothing; insomuch that when the child`'s pap hath stood in a pannikin,
they have thrown out the pap to take the pannikin away.

Should I sum up all the particulars I have received, and the account I could give,
it would make a volume of itself; for the informers were generally poor,
and sometimes also the justices,
so that they knew how to part their booty belonging to the king, as well as to the poor;
and thus the king and the poor got but little of their plunder.
Nevertheless it so happened sometimes, that those who were finable,
were freed by the justices; for they knew very well, that these informers,
who were also witnesses, were cunning sharkers,
who were also concerned to get their thirds of the booty,
and therefore found out a way by which they showed
that they were knavish and unjust in their office,
therefore not fit to give evidence; so that it hath sometimes fallen out,
that an honest justice hath cleared those informed against,
when the informer missed in his evidence, either in the day of the month, or the like,
in the complaint.

At London there once appeared before the lord mayor, sitting at a court of aldermen,
an impudent informer having such a quantity of informations for fines as would have
wronged the parties to the value of 1500£. but the mayor abominating such a practice,
adjourned the court, and went away.
But this hardy informer was not content to let the matter fall thus,
but appeared before the court from time to time,
to make a booty of honest people`'s goods; but they still put him off,
until at last he was himself arrested for debt, and carried to prison,
where he ended his days.

Although now the law against seditious conventicles had passed,
upon a supposition that the Presbyterians were ready to rise,
considering the bustle and tumult occasioned by John Fox in Gloucestershire,
which was much taken notice of, as I have mentioned before,
yet nevertheless the Quakers`' meetings became the
chief object in the execution of this law.
Whereupon G. Fox being in London, set forth in print the injustice of this law, in order,
if possible, to moderate the government not to put the same in execution.
Nevertheless, being also sensible that a great storm hung over the heads of friends,
he also wrote an epistle to them, to exhort them to faithfulness,
and to encourage them to stand fast in their testimony,
and bear with Christian patience the suffering that was come upon them.
Now the First-day that this law took place,
he went to the meeting of friends at Gracechurch-street in London;
but being come to the place, he found the street full of people,
and a guard to keep them out of their meeting-house; whereupon he went to Lombard street,
(out of which there was also a passage to the meetinghouse,)
and there he also found a guard;
but there being a court before the door, which was full of people,
one of the Quaker ministers was there preaching to the people, and when he had ended,
G+++.+++ Fox stood up and said, "`Saul, Saul, why persecutes thou me;
it is hard for thee to kick against the pricks.`" Which words he thus explained:
that it was Saul`'s nature that persecuted;
and that they persecuting Christ in his members, were kicking against the pricks;
and that it was the birth of the flesh that persecuted the birth of the Spirit;
and that it was the nature of dogs to tear and devour the sheep,
but that they suffered like sheep, who did not bite again; but were a peaceable people,
who loved even their persecutors.
While G. Fox was thus preaching, there came a constable and an informer, with soldiers,
who pulled him down from the place he stood on.
Then, said he,
"`Blessed are the peace-makers,`" but the commander
of the soldiers ordered them to secure him:
'`For,`' said he, '`you are the man I looked for.`'
Wherefore he with two more of his friends, John Burnet and another,
were had before the lord mayor; and as they were going, the informer said,
'`It will never be a good world,
until all people come to the good old religion that was two hundred years ago.`'
G+++.+++ Fox hearing this, said, '`Art thou a Papist?
What! a Papist informer?
For two hundred years ago there was no other public profession
of religion but that of the Papists in this nation.`'
It vexed the informer that G. Fox heard him speak thus;
for he now saw he was ensnared in his own talk.
When he came into the court before the lord mayor`'s house,
some people who were there asked G. Fox, why he was brought thither prisoner?
'`Pray,`' said he, '`ask that informer,
and ask him his name;`' but he would not tell his name.
Then one of the mayor`'s officers looking out at a window, told him,
he should tell his name before he went away: '`For,`' said he,
'`the lord mayor will know by what authority you have intruded yourself with soldiers
in the execution of those laws which it belongs to the civil magistrate to execute,
and not the military.
The informer understanding this, got away, but not without some difficulty,
because they would not then let him out of the court;
but he forcibly pulling open the door, and being got into the street,
the people gave a great shout, crying out,
'`a Papist informer! a Papist informer!`' and he would have come off but badly,
had not G. Fox advised the constable and soldiers
to keep him out of the hands of the common people.
Whereupon he went into the house and changed his periwig, and so got away.

When the lord mayor came home, and G. Fox was brought before him, he said, '`Mr. Fox,
you are an eminent man among those of your own profession,
pray will you be instrumental to persuade them from meeting in such great numbers:
'`for,`' said he, '`seeing Christ hath promised, where two or three are met in his name,
he will be in the midst of them;
and the king and parliament are graciously pleased
to allow of four to meet together to worship God,
why will not you be content to partake both of Christ`'s promise to two or three,
and the king`'s indulgence to four?`'
To which G. Fox answered in his own words as follows:

[quote]
____
That Christ`'s promise was not to discourage many from meeting together in his name;
but to encourage the few, that the fewest might not forbear to meet,
because of their fewness.
But if Christ hath promised to manifest his presence in the midst of so small an assembly,
where but two or three were gathered in his name;
how much more would his presence abound where two
or three hundred are gathered in his name.
G+++.+++ F. wished him to consider, whether this act would not have taken hold of Christ,
with his twelve apostles and seventy disciples,
(if it had been in their time,) who used to meet often together;
and that with great numbers`'? However, he told him, this act did not concern us;
for it was made against seditious meetings,
of such as met under pretense and color of religion, to contrive insurrections, as,
the act says, late experience had shown; but we had been sufficiently tried and proved,
and always found peaceable:
and therefore he should do well to put a difference between the innocent and the guilty.
He said the act was made against meetings, and a worship not according to the liturgy.
G+++.+++ F. told him, '`according to,`' was not the very same thing; and asked him,
whether the liturgy was according to the Scriptures`'?
And whether we might not read Scriptures,
and speak Scriptures?
he said Yes.
And told him,
that this act took hold only of such as meet to plot and contrive insurrections,
as late experience had shown; but they had never experienced that by us.
Because thieves are sometimes on the road,
must not honest men travel therefore`'? And because
plotters and contrivers have met to do mischief,
must not an honest, peaceable people, meet to do good?
If we had been a people that did meet to plot and contrive insurrections,
etc. we might have drawn ourselves into fours;
for four might do more mischief in plotting, than if there were four hundred;
because four might speak out their minds more freely one to another,
than four hundred could: therefore we being innocent,
and not the people this act concerns, we keep our meetings as we used to do; and said,
he believed that he knew in his conscience we were innocent.
____

After this and more discourse, the lord mayor, whose name was Samuel Starling,
let them go, seeing the informer was gone before, and now nobody accused them.
The treatment this informer met with, made others scrupulous,
yet several of their meetings in London were disturbed,
and some of their preachers cast into prison;
but though the Baptists and other dissenters ceased their public meetings,
yet the Quakers continued to keep theirs, as they used to do,
whereby it happened that some of their meeting-houses were pulled down,
and amongst others that at Ratcliffe, which was a substantial building, almost new.

After some time, the heat of persecution in the city began to abate,
but in other places it raged more fiercely; this engaged G. Fox to leave the city,
and travel about the country in divers places to visit his friends.

This year G. Fox, had a very great fit of sickness, to such a degree,
that he became both blind and deaf, insomuch that his recovery was despaired of by some;
but after a time he grew better.

In the meanwhile persecution in many places grew very dismal;
for many of the friends were beaten with swords, and pikes, and muskets, to that degree,
that their blood ran along the ground,
and the informers were so very eager to hunt after their prey,
that they informed of meetings when there was none.
Amongst others, this following was an instance.
A Droitwitch, John Cartwright came to a friend`'s house there, who sitting down to supper,
he prayed before they ate, which being heard by an informer,
the room being next to the street,
he thereupon went immediately and informed that there was a meeting in the house,
and so got a warrant to distrain the goods;
and when he came riding with them in the evening, he fell from his horse,
and brake his neck, thereby getting his death instead of his prey,
which he hunted after.
