== Chapter XXIII

[.section-date]
1695-1702.

[.chapter-synopsis]
* Sufferings of Friends in Barbados
* Dismal end of sundry Persecutors
* Penitence of J. Batt
* Colonel Ruddock
* Act allowing Quakers to take an Affirmation instead of an oath
* Marriage Act
* G. Keith again inveighs against Friends
* G. Keith turns Episcopalian
* "`Association`" by the House of Commons
* Quakers`' testimony relating to the "`Association`"
* Death and Character of R. Haydock
* Address of the Quakers to William III. on the conclusion of peace
* Bill for restraining the press
* "`Snake in the grass`"
* Account of J. Crook
* Address of Friends to the King on the settlement of the succession
* Death of King William
* Queen Anne proclaimed
* Epistle of G. Fox concerning his first mission
* The fruits of G. Fox`'s mission
* I. Penington`'s relation concerning himself
* Letter from J. Crook to I. Penington
* Case of Susanna Withrow
* Singular convincements
* Increase of the Society of Friends

Now I return again to the case and affairs of the Quakers.

And since those of Barbados in America were still about this time much molested,
for not bearing arms, they sent over a list in the year 1695,
of what had been taken from them under the government of the colonels Searle and Muddiford,
the president Wallum, the lords Francis Willoughby, and William Willoughby,
the knights Jonathan Atkins and Richard Dutton,
and the colonels Edwin Stede and James Kendal, all which amounted to 1,423,164 lbs.
Muscovado sugar, and 2,910£ 16s. in money.
To this list was joined an account of the disasters
which befel several of the persecutors in Barbados.
In this account I find above thirty marshals, or the deputies, named, who,
though they had enriched themselves with the spoil
and havoc of the goods of honest people,
yet they all died poor, and several either by an unnatural death, or with great pains;
but I decline mentioning all the particulars.
Among these was John Thurborn, marshal to colonel Tidcomb,
who used scoffingly to call the Quakers his milch cows, saying, that George Gray,
one of these people, was one of his best cows,
and gave a brave mess of milk every exercising day.
For he and other such birds of prey took always much more than the fine amounted to:
but at length he died in poverty, being afflicted with a fistula in his fundament,
that did admit of no cure.

It was not only for not bearing arms that the Quakers suffered thus;
but frequent occasions were sought to vex them.
For when they, to bring their negroes, if possible, to some knowledge of the true God,
caused them to meet together for an hour or two once a week,
to instruct them according to their capacity,
by reading to them some part of the Holy Scriptures,
and speaking something to this purpose; a law was made,
forbidding the Quakers to let their negroes come into their meetings,
though kept in their own houses,
on pain of forfeiting every such negro as was found there, or ten pounds instead thereof.
And by one Thomas Cobham, an action was brought against Ralph Fretwell,
for eighty negroes of his own at a meeting in his own family.
But though the justice, John Merrick, did what he could to countenance the said Cobham,
yet after several sessions of the court, at which the said justice was an assistant,
judgment was given in favour of the defendant;
and it was remarkable that the abovesaid Cobham, though a lusty likely young man,
became dejected, and generally slighted;
and soon after was taken with a fever and an inflammation in his neck and throat,
which so increased, that towards his latter end he cried out, "`Fire, fire;
I am all on fire;`" and to his mother he said, she needed not provide a coffin for him;
for he should be burnt up before it was made: crying out, "`Neither heaven nor hell,
but all fire, fire;`" to which he added,
"`Now the Quakers will say it is a judgment fallen on me.`"
After this manner he miserably ended his days.
And justice Merrick`'s exit was also dismal: for riding to his house,
after having drank too much, he was thrown from his horse, whereby his brain was so hurt,
that he lay some days in a violent raving condition, to the terror of his friends,
and so died.
In like manner William Sharp, a judge of the court,
who had been a great opposer to the Quakers instructing their negroes,
riding from his house to Bridgetown, fell from his horse, and was so hurt,
that he was not heard to speak any thing else afterwards,
but "`O my head;`" and three or four days after his fall, he died.

Sir Timothy Thornhill, major-general,
had often threatened to take away the Quakers`' lives,
and was such an abominable blasphemer,
that I feel myself seized with horror in reading the most detestable
and direful blasphemies which this monstrous wretch belched out:
for being at a feast, and drinking so excessively,
that some of the company refused to drink so hard, he wished, (shall I say it,
or be silent,) __Seipsum esse Deum Omnipotentem,
// lint-disable invalid-characters "ò"
quò posset damnare animas eorum qui cum ipso bibere nollent.__
At another time, being in company where a woman, by way of discourse,
spoke of the power and omnipotency of Almighty God, he returned this accursed language,
worse than that of the devil himself, Matt. 4. "`God damn ye,
go to the top of yonder tree,
and see if God Almighty can save you from breaking
your neck before you come to the bottom.`"
Other devilish language he spoke, I pass by with silence.
When once a person was brought before him for not appearing in arms, and told him,
he could not do so for conscience-sake, he returned, "`God damn your conscience;
if I cannot make your conscience bow,
I will make your stubborn dog`'s back bend,`" and so tied him neck and heels
with his own hands so violently that he almost deprived the man of life.
He also once, when a declaration of war was published in the island, said,
that the first time any enemy appeared, he would hang up the Quakers,
binding his words with abominable oaths, to which he was so accustomed,
that he seldom spoke without them.
But now at length the time came that he must remove from this to the other world.
He had been sick, and being pretty well recovered,
he boasted among his companions of his conquest over death,
and daringly said that he had taken a new lease of
his life from God Almighty for thirty years longer.
But within a few months after, the thread of his life was cut,
and his pretended lease was taken from him by the Sovereign of the universe.
Thus he died unlamented by moderate people, and cursed by others,
who lost considerably by him, notwithstanding a great estate left him by his father.

But more happy was his marshal, John Batt, who had taken much goods from the Quakers;
yet on his dying bed, some years before, viz. 1679,
was so sensibly touched with repentance,
that he caused the following paper to be written, and signed it.

[.embedded-content-document.paper]
--

Whereas, I John Batt the younger, of the island of Barbados,
was lately by commission from Colonel Thornhill,
marshal to his regiment of foot soldiers;
and by that power did distrain upon the estates of several of the people called Quakers,
and took and carried away many parcels of their sugar, and other goods,
for their defaults in not appearing in arms to the said regiment;
which they refused out of tenderness of conscience, to which I had not regard;
but now the Lord having laid his hand sorely on me,
by afflicting me with a hard and grievous sickness,
those things done to the aforesaid people come fresh
in my mind to my very great grief and terror;
and I do declare that all the sins that I have been guilty of besides,
which are very many, do not trouble or lie so heavy upon my conscience,
as those my doings to that people;
and do believe that no man will ever be blessed or prosper,
that practises such things against that people.
In witness whereof I have hereunto set my hand, this tenth day of May, 1679.

[.signed-section-signature]
John Batt, Jun.

[.signed-section-signature]
William Howard, _Witness_

[.signed-section-context-close]
Antrobus.

--

Well had others done, if they had taken example by it;
but it was not in vain that our Saviour in the parable of the rich man and Lazarus,
made Abraham say to the rich man, "`If they hear not Moses and the prophets,
neither will they be persuaded though one rose from the dead.`"
But other persecutors took no caution by this penitent John Batt;
for yet not long after some others in Barbados most furiously
showed their malice and rage against the Quakers,
and among these one Alexander Ruddock, a Scotchman,
who was not only a colonel of a regiment of foot, but also judge of a court,
and one of the council.
He caused one of the society of the Quakers to be rated four hundred pounds of sugar,
for payment of the priest`'s wages, who was his son-in-law;
whereas upon complaint of the said person, and upon inquiry,
it appeared that the pretended due was but ten pounds of sugar:
and it was well known that he and his friends duly paid for maintaining the poor,
and for mending highways: but all this could not avail him;
for a cow was taken from him worth ten pounds sterling.
And though some of the magistrates, seeing the unreasonableness of these proceedings,
would have had the cow returned to the right owner,
yet such was the power of the said Ruddock, that they were not able to withstand it.
And because the aforesaid man had complained of the wrong and oppression he suffered,
that so incensed Ruddock, that he caused him to be fined five pounds sterling,
for having refused to take the oath as constable,
though he was willing to have served the office.
For this fine Ruddock issued out a warrant against him,
upon which was taken from him a negro woman,
that by the management of Ruddock was valued at about
two thousand three hundred pounds of sugar,
which as the price of sugar then went, might amount to eleven pounds ten shillings:
and yet the negro was sold for six and twenty pounds sterling,
and all kept for the fine of five pounds.
From this same man was taken the value of above seven
thousand pounds of sugar in one year,
by the direction of Ruddock;
which the sufferer laying before him in the presence of his daughter, the priest`'s wife,
and telling him he had suffered all that for complaining
of the wrong he had done him about his cow,
he, as rejoicing at it, said it should be so yearly, so long as he was magistrate.
But he did not live a year after.

He was of a fierce temper, and very ready to put negroes to death for example, saying,
"`What is it for Barbados to put twenty or thirty
negroes to death yearly for example sake?`"
And as he vexed the Quakers many ways,
so he showed his grudge also by taking the meat they bought and paid for; nay,
so malicious he was,
that meeting once a butcher carrying meat to the house of him that bought it,
he commanded him to carry it back, saying the Quakers shall not eat fresh meat.
But at length the measure of his iniquity was full: he came from the council,
where an order was issued from the governor to break up the Quakers`' meetings,
and he promised the governor diligently to obey all his commands.
But in his very way home he was taken ill, and being come to his house,
he called for some cream of tartar, which he used to take in his broth;
but by his own mistake he took arsenic instead thereof, and so wretchedly ended his days.
And how wicked soever he was, yet the priest Kennedy, his countryman,
did not stick when he was to preach his funeral sermon,
to take his text from these words of the apostle, "`I have fought a good fight,
I have finished my course, I have kept the faith:
henceforth there is laid up for me a crown of righteousness.`"
And in this sermon it was declared of him,
that he had attained to the prudence of a judge, the dignity of a colonel,
and the honour of a counsellor; and that he had served his king and country faithfully,
and died a saint.
This last expression seemed to regard some repentance he had showed; but whatever it was,
we must commit that to God; and in the meanwhile not rely too much on such a repentance:
since Judas also repented of his wickedness.
If I did not study brevity,
I could relate more remarkable cases concerning the persecutors in Barbados;
but I break off.

Now I return to England, where the parliament sitting the latter end of this year,
had effectually taken in hand the making an act to ease
the people called Quakers from that heavy burden of swearing;
but this work met with great opposition:
for though many good-natured members were inclined to it in good earnest,
yet their enemies were so active in altering and clipping the bill,
that it looked almost as if the whole project would have come to nought.
But the king himself forwarded the work, and to his praise be it said,
he was the principal promoter of it: insomuch that in the beginning of the year 1696,
it was enacted by the king and parliament,
that the solemn affirmation and declaration of the people called
Quakers shall be accepted instead of an oath in the usual form,
as appears by the act, which was as followeth:

[.embedded-content-document.legal]
--

[.blurb]
=== An Act that the Solemn Affirmation and Declaration of the People Called Quakers, Shall be Accepted Instead of an Oath in the Usual Form.

Whereas divers dissenters, commonly called Quakers,
refusing to take an oath in courts of justice, and other places,
are frequently imprisoned,
and their estates sequestered by process of contempt issuing out of such courts,
to the ruin of themselves and families; for remedy thereof,
be it enacted by the king`'s most excellent majesty,
by and with the advice and consent of the lords, spiritual and temporal,
and commons in this present parliament assembled, and by the authority of the same,
that from and after the fourth day of May,
which shall be in the year of our Lord one thousand six hundred and ninety-six,
every Quaker within this kingdom of England, dominion of Wales,
or town of Berwick-upon-Tweed,
who shall be required upon any lawful occasion to take an oath in any case,
where by law an oath is required, shall, instead of the usual form,
be permitted to make his or her solemn affirmation or declaration,
in these words following, viz.

[.numbered-group]
====

[.numbered]
I+++.+++ _A. B._ do declare in the presence of Almighty God,
the witness of the truth of what I say.

[.numbered]
II. Which said solemn affirmation or declaration, shall be adjudged and taken,
and is hereby enacted and declared to be of the same force and effect,
to all intents and purposes in all courts of justice, and other places,
where by law an oath is required, within this kingdom of England, dominion of Wales,
or town of Berwick-upon-Tweed, as if such Quaker had taken an oath in the usual form.

[.numbered]
III.
And be it further enacted by the authority aforesaid, that if any Quaker,
making such solemn affirmation or declaration, shall be lawfully convicted, willfully,
falsely, and corruptly, to have affirmed or declared any matter or thing,
which if the same had been in the usual form,
would have amounted to wilful and corrupt perjury,
every such Quaker so offending shall incur the same penalties and
forfeitures as by the laws and statutes of this realm are enacted
against persons convicted of wilful and corrupt perjury.

[.numbered]
IV. And whereas by reason of a pretended scruple of conscience,
Quakers do refuse to pay tithes and church rates,
be it enacted by the authority aforesaid, that where any Quaker shall refuse to pay,
or compound for his great or small tithes, or to pay any church rates,
it shall and may be lawful,
to and for the next two justices of the peace of the same county,
other than such justice of the peace as is patron of the church or chapel,
where the said tithes do or shall arise, or any ways interested in the said tithes,
upon the complaint of any parson, vicar, farmer, or proprietor of tithes,
churchwarden or churchwardens, who ought to have, receive, or collect the same,
by warrant under their hands and seals,
to convene before them such Quaker or Quakers neglecting
or refusing to pay or compound for the same,
and to examine upon oath,
which oath the said justices are hereby empowered to administer,
or in such manner as by this act is provided,
the truth and justice of the said complaint,
and to ascertain and state what is due and payable by such
Quaker or Quakers to the party or parties complaining,
and by order under their hands and seals to direct and appoint the payment thereof,
so as the sum ordered as aforesaid, do not exceed ten pounds;
and upon refusal by such Quaker or Quakers to pay according to such order,
it shall and may be lawful to and for any one of
the said justices by warrant under his hand and seal,
to levy the money thereby ordered to be paid,
by distress and sale of goods of such offender, his executors or administrators,
rendering only the overplus to him, her, or them,
necessary charges of distraining being thereout first
deducted and allowed by the said justice:
and any person finding him, her,
or themselves aggrieved by any judgment given by two such justices of the peace,
shall and may appeal to the next general quarter sessions to be held for the county,
riding, city, liberty, or town corporate: and the justices of the peace there present,
or the major part of them, shall proceed finally to hear and determine the matter,
and to reverse the said judgment, if they shall see cause:
and if the justices then present, or the major part of them,
shall find cause to continue the judgment given by the first two justices of the peace,
they shall then decree the same by order of sessions,
and shall also proceed to give such costs against the appellant,
to be levied by distress and sale of the goods and chattels of
the said appellant as to them shall seem just and reasonable:
and no proceedings or judgment had or to be had by virtue of this
act shall be removed or superseded by any writ of _certiorari_ or
other writ out of his majesty`'s courts at Westminster,
or any other court whatsoever, unless the title of such tithes shall be in question.

[.numbered]
V+++.+++ Provided always, that in case any such appeal be made as aforesaid,
no warrant of distress shall be granted until after such appeal be determined.

[.numbered]
VI. Provided, and be it enacted, that no Quaker,
or reputed Quaker shall by virtue of this act be qualified
or permitted to give evidence in any criminal causes,
or serve on any juries, or bear any office or place of profit in the government;
any thing in this act contained to the contrary in any wise notwithstanding.

[.numbered]
VII.
Provided, that this act shall continue in force for the space of seven years,
and from thence to the end of the next session of parliament, and no longer.

====

--

Thus the Quakers became discharged and free from that grievous
burden by which they had been oppressed so many years.
This parliament made also an act for enforcing the laws
which restrain marriages without licenses or bands;
and for the better registering marriages, births, and burials;
and for keeping a distinct register of all persons born;
for which no more was to be paid than sixpence.

Mention hath been made already that George Keith had at
London got a place called Turner`'s-hall to preach in;
and as his auditory consisted chiefly of persons envious against the Quakers,
so there were among these also many of the vulgar sort,
who generally are fickle and unsteady, and often inclined to novelties:
though Keith would as yet in some respect be looked upon as an adherent of the Quakers,
he also had published some papers,
wherein he endeavoured to make it appear that they held several heterodox sentiments.

The books which he had published concerning this
matter were so fully answered by the Quakers,
that he being at a loss to make a reply to their answers,
pretended that he was not in a condition to set the press at work,
and bear the charges of the impression.
But that this was a frivolous evasion was well known.
Yet he, to do something, fell upon another project, and published an advertisement,
that on the 11th of the month called June,
he would defend his charge against the Quakers,
and therefore he summoned some of them to appear there at the time,
to answer for themselves.
Beginning now to comply with the Episcopalians, he had, as he said afterwards,
given notice of his intention to the lord mayor of London, who not having forbidden it,
he grew the more bold.
But the Quakers did not think it meet to appear there to enter into a dispute with him,
the rather because the king at that time was beyond sea,
and many of the vulgar were idle for want of work and trade,
occasioned by the scarcity of money, which then was very great,
by reason of the recoining it,
insomuch that it could not be foreseen whether some
disaffected persons might not have got together,
and caused a dangerous disturbance.
And therefore, they declined to appear there,
and gave the following reasons of their refusal,
which were read in the appointed meeting, and afterwards published in print:

[.embedded-content-document]
--

Whereas, G. Keith hath, after his wonted irregular and unruly manner,
challenged divers of us to defend ourselves against such
charges as he has to exhibit against us at Turner`'s-hall:
these are to certify all whom it may concern,
that the reasons why we decline any such meeting are as follow:

[.numbered-group]
====

[.numbered]
_First._
Because the said G. Keith hath given us such frequent
proofs of his very passionate and abusive behaviour,
at the many more select meetings we have had with him, in all manner of sweetness,
long-suffering and patience, on our side,
to satisfy and preserve him from these extremes:
that we cannot assure ourselves now of any better entertainment,
or that the meeting can have any desirable success, for a thorough information.

[.numbered]
_Secondly._
We decline to meet, because it is not an agreed meeting on both sides,
which it ought to have been, and where that is not, or cannot be adjusted,
the press is the next fair way and expedient, which he has begun with,
and now seems to decline;
nor hath he sent us a copy of his charge or indictment against us,
which also he ought to have done.

[.numbered]
_Thirdly._
That he has two of our books which lie hard at his door,
in vindication of us and our doctrines from his exceptions,
and which he has not yet answered; so that he is not upon equal terms with us;
and therefore we think his challenge, appointment, and summons, unfair;
and that all that are not partial will be of the same mind with us.

[.numbered]
_Fourthly._
Such public and unlimited meetings, are too often attended, with heats, levity,
and confusion, and answer not the end desired by sober and inquiring men.
Besides,
that it sets up a practice that authority may judge to be an abuse to our liberty,
and so draw that under reflection, as no friend to the civil peace.

[.numbered]
_Fifthly._
We know not what religion or persuasion this wavering man is of,
or what church or people he adheres to, or will receive him, with his vain speculations,
that have led him to desert us;
nor who are accountable to us for him and his irregularities and abuses;
the generality of such assemblies usually making ill auditors, worse judges,
and no good security for our satisfaction.
And we must therefore take leave to say,
it seems to us an indirect way of disquieting and invading our present liberty,
that so irreligious a meeting should be held,
whose end is to abuse other men for their religion.
If this should be imitated by all the several sorts
of different persuasions in this city,
what heats and confusions must necessarily ensue.

[.numbered]
_Sixthly, and lastly._
Wherefore be it known unto all, that for the sake of religion, the liberty granted us,
and the civil peace, we decline to meet him;
and not from any apprehension we have of his abilities,
or our own consciousness of error, or injustice to the said G. Keith;
whose weak and unbridled temper we know is such, that what learning and parts he hath,
have not been able to balance and support him on less occasions,
so that we may say they are in ill hands: and if he proceeds as he begins,
they will be employed to an ill end, which his, poor man! cannot but be,
unless he change his course; which we heartily pray for,
that a place of repentance he may find; and through a true contrition,
the remission of his great sin of envy, and evilly entreating the Lord`'s people,
and way, which we profess, and which he the said G. Keith,
hath long and lately both professed, and zealously vindicated as such.

====

--

These reasons the Quakers, as hath been said, published in print, to show the world,
that it was not without a weighty cause, that they did not accept G. Keith`'s summons.
Now though G. Whitehead, and W. Penn,
for the abovesaid reasons did not appear in Turner`'s-hall,
yet some of their friends were there as spectators,
to see what would be the issue of the business.
G+++.+++ Keith seeing himself thus disappointed in his intention,
took upon him for all that to defend his charge in the absence of his adversaries,
which now he could do easily, since none contradicted him;
and he was applauded by the frequent shoutings of the mob that was there in great numbers.
After the reasons of non-appearance were read,
Keith signified that they were not satisfactory, by calling them slender, weak,
and frivolous.
"`What,`" said he, "`may a malefactor make this excuse;
You shall not call me before a justice without my consent?
If a man robs me, I may complain of him as a robber,
and without his consent call him to account.
But here is a strange thing:
if injuring men may not be called to account without their consent,
it will trespass against the law, and intrenches upon liberty of conscience.`"
This reason he published in print, in his narrative of that day`'s work:
but who would formerly ever have thought, that such a little man as he was,
would have been so big.
It looked just as if the Quakers were obliged to appear
as malefactors before the pretended judge Keith,
accompanied with his assistants, the mob, and I do not know who.
And to keep to G. Keith`'s comparison, though a malefactor may not say,
you shall not call me before a justice without my consent,
yet with some good reason he might say, you shall not make yourself a justice,
as Keith now did.
It is probable that he was supported by some great churchmen,
otherwise such a bold action might easily have turned to his disadvantage.

My limits do not admit of a circumstantial relation
of what was transacted at that time in Turner`'s-hall;
yet to show briefly how he treated matters, I will produce one or two instances,
by which my reader may know, __ut ex ungue leonem,__^
footnote:[As of a lion by his claw.]
and so judge of the rest.
He said he would charge the Quakers with nothing
but what he would prove from their own writings,
and he went on thus:
"`I offer to prove that G. Whitehead hath denied Christ both to be God and man.`"
A strange thing indeed,
since it was very well known that G. Whitehead had
published a book of above twenty sheets,
under this title, [.book-title]#The Divinity of Christ,
and Unity of the Three that Bear Record in Heaven,
with the Blessed End and Effect of Christ`'s Appearance, Coming in the Flesh, Sufferings,
and Sacrifice for Sinners, Confessed and Vindicated by his Followers called Quakers.#
This book G. Keith could not pretend ignorance of,
for he picked somewhat out of it in his narrative: but to maintain his charge,
he appealed to a book of G. Whitehead`'s, called, [.book-title]#The Light and Life of Christ within.#
This book G. Whitehead had written in answer to W. Burnet, a Baptist preacher,
who writing of Christ, said, As he was God, he was Co-Creator with the Father,
and so was before Abraham, and had Glory with God before the world was,
and in this sense came down from heaven.
To which G. Whitehead answered, "`What nonsense and unscripture-like language is this,
to tell of God being Co-Creator with the Father?
Or that God had glory with God?
Doth not this imply two gods, and that God had a father?
Let the reader judge.`"
Certainly it appears from this plainly, that G. Whitehead did not intend any thing else,
but to censure the unscriptural expressions of his antagonist, as Co-Creator,
and implying two gods: for not only the apostle saith, God is One,
but Christ himself saith I and the Father are One.
Yet G. Keith did not stick to say, G. Whitehead denieth the divinity of Christ,
and he deceives the nation and the parliament by telling
them the Quakers own Christ to be both God and man,
and believe all that is recorded of him in the holy scripture.
This he strove to prove from a passage taken out of the aforementioned book,
which in sense agreed with the former; and speaking in another page of the same matter,
viz. The Baptists calling God the Word, Co-Creator with the Father,
G+++.+++ Whitehead answers thus to it: "`To tell of the Word God Co-Creator with the Father,
is all one as to tell of God being Co-Creator with God, if the Father be God;
and this is to make two gods and two creators:
for God Co-Creator with the Father plainly implies two.`"
Was this showing of others their absurd expressions, a denial that Christ was God,
as Keith would have it?
Might it not be asked here, whether the acute wit of Keith was now altogether flown away?
But a great part of his auditory consisted of an ignorant crew,
and one or other of them was continually heard to cry out, It is sufficient.

Now to prove that G. Whitehead had denied Christ to be man,
Keith cited from the forementioned book, called [.book-title]#The Divinity of Christ#, etc. these words, "`If the body and soul of the Son of God were both created,
doth not this render him a fourth person?`"
Here Keith stopped, and broke off with an etc. without adding the following words;
"`For creation was in time, which contradicts the doctrine of three distinct, uncreated,
co-eternal, co-essential persons in the Deity,
seeing that which was created was not so.`"
This G. Whitehead asked and said, to show his opponent, T. Danson,
the absurdity of his assertions about the personalities of the Deity.
But Keith went on, reading from G. Whitehead`'s book thus:
"`Where doth the Scripture say that his soul was created?
For was not he the brightness of the Father`'s glory,
and the express image of his divine substance?
But supposing the soul of Christ was with the body created in time,`" etc.
Here Keith broke off again, omitting the following words: "`I ask,
if from eternity he was a person distinct from God and his holy Spirit,
without either soul or body?
Where doth the Scripture speak of any person without either soul or body?
Let us have plain Scripture.`"

Now though G. Whitehead had written this to show,
how we often enter into inextricable straits,
when we do not keep to the words of the holy Scripture,
which no where speaks of three persons in the Deity;
yet Keith perverting the passage abusively, said to his auditory,
"`Here ye see he will not own that Christ had a created soul.`"
At this rate, and after this manner, Keith reasoned, and treated the other passages.
But how smartly would he have carped at others,
if they had cited his words thus piecemeal.

But now he had a temporal reward in this view, and seeing for that end,
he began more and more to declare himself in favour of the episcopal church;
somebody of that persuasion,
who did not further make himself known than by these initial letters,
W+++.+++ C. made it his business to show the changeableness of Keith`'s opinion and sentiments,
from his own writings, which he had published in print; and thereby evidently proved,
that in every respect Keith was turned an apostate,
though he appeared much offended at the Quakers, because they had called him so.
"`But,`" said this author, "`if the Presbyterian principles,
of which society Keith once was a member, were better than the Quakers,
then is Mr. Keith an apostate, in revolting from, and deserting the Presbyterians,
and turning his coat Quaker-fashion.
// lint-disable invalid-characters "è", "á"
But if the Quakers were more in the right than the Presbyterians, then _è contrá._`"

Now he appeared to fawn on the episcopal clergy,
and esteemed lawful what formerly he had zealously oppugned.
For he was in hopes that by opposing the Quakers
he should be best rewarded among the Episcopalians;
and this was not altogether without reason;
for it being no more in their power now to persecute the Quakers in manner as formerly,
they made use of other means as much as possibly they could,
to render them and their doctrine odious; for which Keith seemed to them no unfit tool;
for he being both of a witty impetuous temper, was also crafty, subtle, cunning,
and violent in his expressions.
And to charge the Quakers with inorthodoxy,
he himself launched out into an heterodox sentiment.
For it was believed, that for maintaining this position,
that the historical knowledge of Christ`'s sufferings, death, resurrection,
etc. was absolutely necessary for salvation,
he had no other ground than the twelve pretended transmigrations
or transitions of man`'s soul from one body into another;
and because the ignorant souls from hence seemed to get opportunity of being informed,
before the end of the world, concerning the death and resurrection of our Saviour.
Who would have imagined before that this same G. Keith should
have accused the Quakers of inorthodoxy in point of doctrine,
which he had often so effectually defended; and among the rest,
in a book against one Cotton Mather,
wherein upon the charge of their being guilty of many heresies and blasphemies,
he said after this manner;
"`Our principles do mostly agree with the fundamental
articles of the Christian Protestant faith.
According to my best knowledge of the people called Quakers,
and those owned by them as preachers and publishers of their belief,
being of an unquestionable esteem among them, and worthy of double honour,
as there are many such,
I know none of them that are guilty of such heresies
and blasphemies as they are charged with.
And I think I should know, and do know those called Quakers,
having been conversant with them in public meetings as well as in private discourses,
with the most noted and esteemed among them, for about twenty years past,
and that in many places of the world, both in Europe and America.`"
Who would ever have thought then,
that one who had conversed so many years with the Quakers, preached their doctrine,
and defended it publicly both by writing and by word of mouth,
should afterwards have decried them,
as deniers of the most essential points of the Christian faith?
But to what extravagancies may not temporal gain transport a man,
the case of Balaam may serve for an evidence.

I have in all this relation of Keith`'s behaviour,
set down nothing but what I believe to be really true;
neither have I endeavoured to aggravate his failures; for I never bore him ill-will,
but a good esteem when I believed him to be upright,
because in that time I perceived in him some good abilities.
And I yet wish from my very heart, that it may please God, in his unsearchable mercy,
so to touch his heart, before the door of grace be shut,
that seeing the greatness of his transgression, he may by true repentance,
obtain forgiveness from the Lord, of his evil; which I take to be worse,
because by his craftiness he endeavoured to set false
colours on things that were really good,
thereby to insinuate himself into favour with the episcopal party.^
footnote:[N. B. This was written some years before I heard G. Keith was deceased.]
And since some others suborned thereto did no omit also to render the Quakers odious,
as such that held inorthodox sentiments, these did not neglect to show in print,
how they were injured and wronged.
For now the old tale, that there were Popish emissaries among them,
was revived and divulged anew.
But it was no hard matter for them to show how ill-grounded this conceit was;
and therefore they might say, "`We are so well known to our neighbours,
that if this were true,
our adversaries would be very active to find out and discover such emissaries,
since the law against them is still in force.`"
Three episcopal clergymen in Norfolk,
had also drawn up a paper to the king and parliament,
to blacken the Quakers from their own writings; but George Whitehead, William Penn,
and others, were not backward to show how their words, or the true meaning thereof,
were perverted; since at such a rate,
even the salutary lessons of the holy Scriptures might be exposed as wicked expressions.

Now the late king James intending an invasion upon England,
and great preparations being made in France in order thereto,
a plot was discovered in England against king William;
this gave occasion to the House of Commons to draw up a kind of declaration,
which was called an association, to be signed by all their members, as follows:

[.embedded-content-document.legal]
--

Whereas, there has been a horrible and detestable conspiracy,
formed and carried on by Papists,
and other wicked and traitorous persons for assassinating his majesty`'s royal person,
in order to encourage an invasion from France, to subvert our religion, laws,
and liberties, we whose names are hereunto subscribed, do heartily, sincerely,
and solemnly promise, testify, and declare, that his present majesty king William,
is rightful and lawful king of these realms.
And we do mutually promise and engage to stand by and assist each other,
to the utmost of our power,
in the support and defence of his majesty`'s most sacred person and government,
against the late king James, and all his adherents.
And in case his majesty come to any violent and untimely death, which God forbid,
we do hereby further freely and unanimously oblige ourselves to unite, associate,
and stand by each other, in revenging the same upon his enemies and their adherents,
and in supporting and defending the succession of the crown,
according to an act made in the first year of the reign of king William and queen Mary,
entitled, "`An Act Declaring the Rights and Liberties of the Subjects,
and Settling the Succession of the Crown.`"

--

An association was also signed by the lords, and both presented to the king,
and were followed by all the corporations in England.
See [.book-title]#Life of king William, vol.
III.# The dissenters also presented declarations to the king,
that had some resemblance with the other.
But the Quakers professing non-resistance, and an inoffensive behaviour,
could in no wise enter into such a league;
yet to show that they were loyal and faithful to the king,
they drew up the following declaration, and published it in print:

[.embedded-content-document]
--

[.blurb]
=== The ancient testimony and principle of the people called Quakers renewed, with respect to the king and government, and touching the present association:

We, the said people, do solemnly and sincerely declare,
that it hath been our judgment and principle from the first day we were called to profess
the light of Christ Jesus manifested in our consciences unto this day,
that the setting up, and putting down kings, and governments,
is God`'s peculiar prerogative, for causes best known to himself;
and that it is not our work or business to have any hand or contrivance therein,
nor to be busy-bodies in matters above our station;
much less to plot and contrive the ruin or overturn of any of them;
but to pray for the king and for the safety of our nation, and good of all men,
that we may live a peaceable and quiet life, in all godliness and honesty,
under the government which God is pleased to set over us.

And according to this our ancient and innocent principle,
we often have given forth our testimony, and now do, against all plotting, conspiracies,
and contriving insurrections against the king or the government,
and against all treacherous, barbarous, and murderous designs whatsoever,
as works of the devil and darkness: and we sincerely bless God,
and are heartily thankful to the king and government,
for the liberty and privileges we enjoy under them by law:
esteeming it our duty to be true and faithful to them.

And whereas, we the said people are required to sign the said association,
we sincerely declare, that our refusing so to do,
is not out of any disaffection to the king or government,
nor in opposition to his being declared rightful and lawful king of these realms,
but purely because we cannot for conscience-sake, fight, kill, or revenge,
either for ourselves or any man else.

And we believe that the timely discovery and prevention of the late barbarous
design and mischievous plot against the king and government,
and the sad effects it might have had, is an eminent mercy from Almighty God;
for which we, and the whole nation, have great cause to be humbly thankful to him,
and to pray for the continuance of his mercies to them and us.

[.signed-section-context-close]
From a meeting of the said people in London, the 23rd of the first month, called March,
1695-6.

--

In this year Roger Haydock died of a fever, at his house in Penketh, in Lancashire,
about the age of fifty-three years.
He had been in Holland the year before,
in which time I had more than once opportunity to speak with him privately,
and thereby discovered such Christian qualities in him, that were indeed excellent;
therefore the news of his decease did much affect me; and because of his ministry,
in which he was eminent, being more than ordinary full of matter in his preaching,
his death was much lamented among those churches
in England where he had laboured most in the gospel.
His wife Eleanor, in her testimony concerning him, said,

[.embedded-content-document.testimony]
--

My spirit hath been, and is bowed under a deep sense of my great loss and exercise,
in the removal of my dear husband,
whom it hath pleased God in his wisdom to take away from me, who was comfort to my life,
and joy to my days in this world, being given me of God,
in great mercy and lovingkindness;
and so he hath been enjoyed by me in thankfulness of heart,
to the close of that time God had appointed; and now is taken from the world,
with all its troubles and exercises, as also from all his labours and travels,
which were great amongst the churches of Christ,
which with me have no small loss in his removal.
But what shall I say: wise and good is the Lord,
who doth what he will in heaven and in earth, and amongst his churches and his chosen.
He can break and bind up, wound and heal, kill and make alive again,
that the living may see his wonders, and magnify his power in all, through all,
and over all, who is God eternal, blessed forever.
Amen.

--

Then in her testimony she gives an account of his life,
and how in her young years he had been to her a faithful instructor in godliness,
and at length became her husband.
After a description of his life, and his many travels in the ministry of the gospel,
to edify and build up the churches, she saith also,
that though his love to her was above all visibles,
as the best of enjoyments he had in this world,
yet she was not too dear to him to give up to serve the truth of God.

[.embedded-content-document.testimony]
--

I was made (said she,) a blessing to him, more comfortable every day than other:
he would often express it; and truly so was he to me every day, every way,
and in every respect.
No tongue nor pen can relate the full of that comfort
and joy we had in God and one in another.
Yet we find such hath been the pleasure of God concerning them he hath loved,
to try them in the most near and dear enjoyments,
that it might be manifest he was loved above all;
that no gifts may be preferred above the giver; but that he may be all in all, who is,
and is to come, God blessed forever.
And truly there hath been great care and watchfulness one over another,
and over our own spirits, to see that our love, though great,
was bounded and kept within its compass, the truth being its original,
the Alpha and Omega also.
Although it hath been the pleasure of God to try me,
in the removal of so great a blessing from me, sure it is,
that I may be the more inward to him, and have his love always in my remembrance,
who gives and takes away, and in all bless his name.
My soul travails that I may always follow his foot-steps of self-denial in all things,
that I may finish my course in this world to the glory of God, as he did,
and have my part in that mansion of glory with him eternal in the heavens;
though it may be my lot to stay for a time in this world of troubles,
yet I have hope in immortality and eternal blessedness,
when time in this world shall be no more.

--

Thus she wrote: but to shun prolixity, I break off.
She then giving some account of his life and ministry, mentions,
that being gone from home, she was not present at his death;
but that they having taken leave of each other before, had parted in great love,
with mutual breathings to God, for one another`'s welfare;
and she concludes with these words:

[.embedded-content-document.testimony]
--

Though I saw not his going away, yet I have seen in what he went,
and that it was full of zeal and fervency in the love of God, and life of righteousness.
So in pure submission to the will of God,
I conclude this short and true relation of my worthy dear husband,
whose name and memory is blessed, and will live,
and be of a sweet savour in the hearts of the righteous through ages.

--

With such a testimony it was,
that Eleanor transmitted the memorial of her beloved consort to posterity.1697.

Meeting in this year with no more remarkable occurrences, I pass over to 1697,
in which a treaty of peace was concluded between England, France, and Holland,
and though many thought it would be lasting,
yet among the popish clergy there were those that had another opinion of it:
of which this artificial distich,
sent over by a clergyman from Ghent in Flanders to Holland,
so that it fell first into my hands, was an evidence:

// lint-disable invalid-characters "ó", "œ"
__Prospicimus modó quod durabunt Fœdera longo
// lint-disable invalid-characters "ô"
Tempore, nec nobis pax citô diffugiet:__

which may be turned into English thus,
"`We foresee now that the confederacy shall last a long time,
and that peace will not quickly fly away from us.`"
But if one reads this distich, backward, it runs thus:

// lint-disable invalid-characters "ô"
__Diffugiet citô pax nobis, nec tempore longo
// lint-disable invalid-characters "ó", "œ"
Fœdera durabunt, quod modó prospicimus:__

and it makes out a quite contrary sense, viz. "`Peace will soon fly from us,
and the covenant shall not last long; which we foresee already.`"

This peace being concluded,
the inhabitants of England vied with one another
to congratulate their king on that account,
who was now acknowledged as king of Great Britain, by the French king Lewis XIV.
And since the magistrates of cities, the heads and fellows of the universities,
and people of all societies and persuasions addressed the king,
the Quakers were not wanting in this respect, and therefore drew up also an address,
which they presented to the king, and was as followeth:

[.embedded-content-document.address]
--

[.blurb]
=== To King William III. over England, etc. The grateful acknowledgment of the people commonly called Quakers, humbly presented:

[.salutation]
May it please the King,

Seeing the most high God, who ruleth in the kingdoms of men,
and appointeth over them whomsoever he will, hath,
by his overruling power and providence,
placed thee in dominion and dignity over these realms;
and by his divine favour hath signally preserved
and delivered thee from many great and eminent dangers,
and graciously turned the calamity of war into the desired mercy of peace;
we heartily wish that we and all others concerned may be truly
sensible and humbly thankful to Almighty God for the same,
that the peace may be a lasting and perpetual blessing.

And now, O king, the God of peace having returned thee in safety,
it is cause of joy to them that fear him,
to hear thy good and reasonable resolution effectually
to discourage profaneness and immorality,
righteousness being that which exalteth a nation:
and as the king has been tenderly inclined to give ease and liberty
of conscience to his subjects of different persuasions,
(of whose favours we have largely partaken,) so we esteem it our
duty gratefully to commemorate and acknowledge the same:
earnestly beseeching Almighty God to assist the king
to prosecute all these his just and good inclinations,
that his days here may be happy and peaceable,
and hereafter he may partake of a lasting crown that will never fade away.

[.signed-section-context-close]
London, the 7th of the 11th Month, called January, 1697.

--

This address being signed, and presented to the king by George Whitehead, Thomas Lower,
Daniel Quare, John Vaughton, John Edge, and Gilbert Latey,
was favourably received and accepted by that prince;
who gave signal proofs that he bore no ill will to
any for difference of opinion in religion,
if they were honest people; of which this may serve for an evidence,
that both his watchmaker, and the nurse of the young duke of Gloucester,
were of the Quakers`' persuasion.

I think it was about the beginning of the year 1698,
that a bill was brought into parliament, for restraining the licentiousness of the press.
Those called Quakers, perceiving that this might be pernicious,
drew up the following remarks, which they delivered to the members of parliament:

[.embedded-content-document]
--

[.blurb]
=== Some considerations humbly offered by the people called Quakers, relating to the bill for restraining the licentiousness of the press.

This bill is, they conceive, of the like nature with the expired act, 13 and 14 Car.
II. ch.
33, and many inconveniences did attend the subjects by it whilst in force,
by which the said people were sufferers.

To prevent the printing and publishing of seditious
or treasonable books against the government,
and scandalous pamphlets tending to vice and immorality,
is the wisdom of all good governments, and must be the desire of all good men.

But to limit religious books to a license, where the tolerated persuasions are many,
they conceive, seems altogether unsafe to all, but that whose opinion the licenser is of,
who by this bill hath power to allow what he shall judge sound and orthodox,
or reject what he shall construe to be either heretical, seditious, or offensive.

History and experience have taught how the obscure term of heresy
hath been turned and stretched against primitive Christian martyrs,
and famous reformers:
// lint-disable invalid-characters "æ"
nor is it forgotten for what reason the writ _De Hæretico Comburendo_ was abolished.

It is no strange thing to have learned men of the same church interfere
in their opinions concerning several texts of holy scripture;
and it is uncertain when their opinions come to the licenser,
whether the world shall have the best or no.

The different apprehensions men have of divers parts of Scripture,
gives birth to different persuasions, who yet all make the Scripture the test thereof;
which by the kindness of the government being tolerated,
they conceive they ought to be left free to defend them from the misrepresentations,
prejudice, or mistake of others,
without being subjected to the censure of a licenser of a different persuasion.

They therefore humbly hope that nothing may be enacted that will lessen the toleration,
which they thankfully enjoy under the favour of this, as well as the late government.

--

These considerations, with what others were offered, were of such effect,
that the bill dropped.

About this time the writings of Antonia Bourignon were not only translated into English,
but also published in print at London.
This displeased many of the clergy, and an author was employed to write against them,
but chiefly against the Quakers.
He called his book, [.book-title]#The Snake in the Grass;# but his own name he concealed;
though it was discovered afterwards that he was a suppressed parson,
who had refused the oath of allegiance to king William.
This man, to render the Quakers odious,
had picked up and collected many things from their writings;
but he had so mutilated their expressions, by omitting several words that went before,
or followed, and by skipping over some in the midst of the period,
that they made out quite another sense than the authors had given.
To this he added relations of several things that happened, as he said, among the Quakers.
Whereas, some of these were fictitious, and mere untruths;
he also raked up things that never had been approved by the Quakers,
as the case of James Nayler, described here before in its due place;
notwithstanding the said James Nayler had publicly given eminent tokens of true repentance.

Among the author`'s untruths, this was one,
that the Quakers in their schools did not suffer the children to read the holy Scriptures.
The falseness of which was made to appear very evidently by a certificate
of the French usher of one of their schools at Wandsworth,
near London, who himself was no Quaker;
as also by the testimonies of some of the neighbours that were people of note;
and declared that the bible was daily read by the scholars in the said school,
beginning with Genesis, and going on to the end of the Revelations:
and then from Genesis again.
The false citations of the aforesaid author, were also clearly set forth:
for if any would be so malicious,
it might by his method be insinuated from Ps. 14:1. and Ps. 53:1,
that in the holy Scriptures was said,
"`There is no God;`" because these words are indeed found there.
But who would be so desperate as to draw such a conclusion from thence,
unless he were an atheist, who openly made a mock of what is sacred.
The answerers of this poisonous book, [.book-title]#The Snake in the Grass,#
were George Whitehead and Joseph Wyeth;
this being a work which required more toil and labour than art,
to review all those manifold citations from many authors,
and to show the unfairness and disingenuity of [.book-title]#The Snake.#
Now since many were very ready to take for true the falsities in that book,
and also in the pamphlets of the apostate Francis Bugg,
who was gone over to the church of England, at the request of John Crook,
who was still alive, though above eighty years of age, a book of his was reprinted,
first published in the year 1663, and so five and thirty years before,
the title of which was, [.book-title]#Truth`'s Principles Concerning the Man Christ, His Suffering,
Death, Resurrection, Faith in his Blood, the Imputation of his Righteousness,# etc.
By this it appeared that the sentiments of the Quakers
concerning these points were not only orthodox now,
but that they had been so in those early days.

Having thus again made mention of John Crook,
of whom I have spoken several times in this history,
I proceed now to mention somewhat concerning his decease,
since he departed this life in the year 1699.
He left behind in writing an exhortation or advice to his children and grandchildren,
written scarce two months before his death, and of this tenor:

[.embedded-content-document.letter]
--

[.salutation]
Dear Children,

I must leave you in a wicked age,
but commend you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ; and as you love it,
and mind the teachings of it,
you will find it a counsellor to instruct you in the way everlasting,
and preserve you out of the ways of the ungodly.

I have seen much in my days,
and I always observed that the fear of the Lord God proved the best portion:
and those that walked in it were the only happy people, both in this life,
while they continued faithful, and when they come to die,
though they meet with many hardships in their passage.
By experience I can speak it,
that the ways of holiness afford more true comfort and peace to
the upright soul than the greatest pleasures this world can afford;
the former reaches the heart and soul, while the delights of this world are but a show,
and appearance only, vanishing like a dream; and whoever believes otherwise of them,
will certainly find them to be but lying vanities; therefore the apostle, Rom. 6:21,
might boldly put the question to the converted Romans,
viz. "`What fruit had you then in those things whereof you are now ashamed?
For the end of those things is death.`"

Therefore, dear children, be in love with holiness; make it your companion,
and those that walk in it; you may find buddings of it from an holy seed in your hearts;
as you mind the inner man, the light will manifest the stirrings of it after God,
which I felt from my tender years;
although I understood them not so plainly till I heard the truth declared.

I advise you to keep a pure conscience, both towards God and man: for if that be defiled,
hypocrisy and formality will deprive you of all comfortable feeling of God`'s presence;
and then deadness and dryness will be your miserable portion.

Be careful how you spend your precious time,
for an account must be given of every idle word, though but few regard it;
but foolish jesting and vain talking are said to grieve the spirit of God;
read Eph. 4:29-30. But improve your time in prayer and religious exercises,
etc. and be diligent in your lawful callings; for,
"`The desire of the slothful man killeth him.`" Prov. 21:25.

Be careful what company you frequent;
for a man is commonly known by the company he keeps, as much as by any one outward thing:
and of your behaviour in company; for I have found that a wise and sober deportment,
adds much to a man`'s reputation and credit in the world.

Watch to the light, and its discoveries of good and evil,
that you may not be ignorant of Satan`'s devices;
so the net will be spread in vain in the sight of the bird,
for watchfulness will make you in love with a retired estate;
and the more truly and perfectly any man knows and understands himself,
the better discerning will such have of other men; as in the beginning,
when deep silence of all flesh was more in use,
the spirit of discerning was more common and quicker, than since it hath been neglected;
therefore be sure you spend some time, at convenient seasons,
in waiting upon God in silence, though it be displeasing to flesh;
for I have had more comfort and confirmation in the truth,
in my inward retiring in silence, than from all words I have heard from others,
though I have often been refreshed by them also.

Love the Holy Scriptures, preferring them to all other books whatsoever;
and be careful to read them with an holy awe upon your spirits,
lest your imaginations put constructions upon them to your hurt;
but exercise faith in the promise of Christ, who hath said,
"`My spirit shall take of mine, and show them unto you.`"

Keep constantly to religious meetings amongst friends; but look to your affections,
that you respect not persons, but the power and life of truth from whomsoever it comes;
not minding the tickling of your affections,
but the demonstration of the truth to your understandings and consciences;
for that will abide, when flashes of affections will fade and come to nothing,
after the words are ended.

Love one another truly, manifesting your love by good counsel,
and being helpful to each other upon all occasions;
being good examples to all you converse with, especially to your children,
and those of your own families; that pride and vanity may not be countenanced by you,
but rather reproved; remembering while they are under your government,
you must give an account of the discharge of your duty to God towards them.

Lastly, Be always mindful of your latter end, and live as you would die,
not knowing how soon your days may be finished in this world:
and while you do live in it despise not the chastenings of the Lord,
whatever they be he is pleased to visit you withal.
I have been afflicted from my youth up, both inwardly and outwardly,
but the God whom I served provided for me, when all my outward relations forsook me,
none of them giving me any portion to begin the world withal.
This I speak, to let you know, I shall leave more outwardly,
even to the least of you than was left me by all my relations, etc.
I need not mention this sharp affliction, beyond expression, in my old age, because,
in some measure, you know it; but I could not have been without it,
as the Lord hath showed me, or I have seen his wonders in the deeps;
therefore I say again, despise not afflictions,
but embrace them as messengers of peace to your souls, though displeasing to the flesh.

These things I commend unto you, out of true love to your souls,
knowing how the vain mind of man little regards such advice as this I leave behind me;
but by this advice I show my true love to you all, desiring God`'s blessing upon it;
to whom I commit you all, my dear children, and end my days

[.signed-section-closing]
Your loving father and grandfather,

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
Hertford, the first of the First month, 1698-99.

--

The sharp affliction he speaks of in this writing was more than one distemper,
for the stone, gout, and cholic, attacked him sometimes sorely;
and though this had been for a long time, yet he always behaved himself patiently,
though his pain was sometimes so violent, that he was often heard to say,
that did he not feel and witness inward power from the Lord,
he could not subsist under his great pains.
That of the stone was the greatest, which continued with him to his end;
and yet he was not heard to utter any unsavoury word, or to cry out impatiently;
but when the extremity of his fits were over, then he expressed his inward joy and peace,
and so praised the Lord.
He had an excellent gift in opening the mysteries of the holy Scriptures,
so that he was like Apollos, of whom we find upon record, that he was an eloquent man,
and mighty in the Scriptures.
And by his zealous and effectual preaching, when he was in his strength of life,
many were convinced of the truth.
In his latter days he said sometimes that the furnace of affliction
was of good use to purge away the dross and earthly part in us.
And under the sorrow and grief he had concerning some of his offspring,
he would sometimes comfort himself with the words of David,
"`Although my house be not so with God, yet he hath made with me an everlasting covenant,
ordered in all things, and sure.`"
In his old age he was many times heard to say,
"`Many of the ancients are gone to their long home, and we are making haste after them:
they step away before me, and I, that would go, cannot.
Well, it will be my turn soon also.`"
And then he seemed to rejoice in the consideration, that the time of his dissolution,
to be freed from his sore distempers, approached apace.
Yet in the latter part of his life he often appeared so strong in the spiritual warfare,
that some judged that in some respect he might have said with Caleb,
"`As yet I am as strong this day, as I was in the day that Moses sent me;
as my strength was then, even so is my strength now, for war, both to go out,
and to come in.`"
About three weeks before his death, though he was weak in body, yet he said powerfully,
and after a prophetical manner, "`Truth must prosper, truth shall prosper,
but a trying time must first come,
and afterwards the glory of the Lord shall more and more appear.`"
He continued in a sedate and truly Christian frame
of mind to the last period of his life,
and departed the 26th of the month called April, in the eighty-second year of his age,
in his house at Hertford, where he had lived many years.
I knew him in England, and he hath also been in Holland,
so that I do not speak of one that was unknown to me.

George Keith, by vilifying the doctrine of the Quakers,
was now so much in favour with the episcopal clergy,
that he began to serve them as a vicar;
having been ordained by the bishop of London about the year 1700.
And since this seemed strange and wonderful to many, somebody,
of what persuasion I do not know,
made a collection of his sentiments concerning a national church, and its clergy,
and what account he gave of their rites and ceremonies,
from books and papers he had published many years before;
to which the author gave this title, [.book-title]#Mr. George Keith`'s Account of a National Church and Clergy,
Humbly Presented to the Bishop of London.#
To this were added some queries he once wrote concerning
what is called the sacrament of the Lord`'s supper.
This account was now published in print, and presented to the bishop of London,
ending with these words of the apostle, "`If I build again the things which I destroyed,
I make myself a transgressor.`"

In the next year, viz. 1701, the late king James died in France.
I mentioned before how that unhappy prince, after having ascended the throne,
fell suddenly by his hasty conduct, and ardent desire to introduce popery in England,
and all his endeavours to regain his lost kingdoms proved ineffectual.
In September, being at mass, he was seized with a qualm, and the distemper increasing,
within a day or two he vomited blood, and all remedies made use of were unprofitable.
If what was written about that time from Paris be true,
he declared that he forgave all men what they had done amiss to him:
and on the 16th of the said month he died at St. Germain`'s, in France,
where he kept his court.

King William was returned from Holland, where he had been,
because of new troubles drawing on from France.
And since the succession of the crown of England was now settled in the Protestant line,
and for want of nearer Protestant heirs, then to the house of Hanover,
the king was congratulated on that account with many addresses from his subjects:
and therefore those called Quakers thought it also their duty to address him,
against whose life a horrible plot was discovered,
with a thankful acknowledgment of his favours.
This they did as followeth, it being presented to the king in December,
by George Whitehead, Wm. Mead, and Francis Camfield.

[.embedded-content-document.address]
--

[.blurb]
=== To King William III. over England, etc. An Address From the People Commonly Called Quakers Humbly Presented:

[.salutation]
May it please the King,

We, thy dutiful subjects, sincerely express our joy for thy safe return to thy people;
having great cause to love, honour, and pray for thee,
as a prince whom we believe God hath promoted and principled for the good ends of government,
under whose reign we enjoy great mercies and favours;
and particularly that of liberty to tender consciences in religious worship,
as a proper expedient to unite thy Protestant subjects in interest and affection.

For which great mercy we cannot but be humbly thankful to God;
and renew our grateful acknowledgment to the king,
whom God by his almighty power hath eminently preserved, and made exemplary in prudence,
as well as goodness, to other kings and princes,
whereby thy memorial will be renowned to posterity.

We are also engaged to bless the Lord for that he hath manifestly frustrated
the mischievous and treacherous designs of thine and the nation`'s adversaries,
both against the lawful establishment of thy throne,
and the true interest of thy Protestant subjects.

And we beseech Almighty God to bless the good designs and just undertakings of the king,
and his great council, for the good of his people,
and for obtaining to Europe a firm and lasting peace; and continue thee, O king,
a blessing to these nations, establish thy throne in mercy and truth,
give to thee a long and prosperous reign over us, and hereafter a glorious immortality,
is, and shall be the fervent prayer of us, thy true and faithful subjects.

[.signed-section-context-close]
Signed in behalf and by appointment of the aforesaid people, at a meeting in London,
the 8th month, 1701.

--

This address being read to the king, was favourably received,
and he thanked those that presented it.
George Whitehead and the others saying what they thought material to the case,
the king returned, "`I have protected you,
and shall protect you:`" and repairing with the address to his closet,
he read it over again, as was understood afterwards, and spoke in its commendation.
But he keeping the paper some days by him,
without giving it to be made public by the Gazetteer, some French news-writers,
at London, forged a very ridiculous address, and sent it beyond sea;
and the French Gazetteers in Holland were very ready
to divulge in their prints such fictitious stuff,
though the expressions therein were so exceeding blunt and unmannerly,
that they could not be spoken to a king,
but by such who were impudent enough publicly to make a mock of crowned heads,
which the Quakers never have been guilty of.
After a few days the king gave the address to be made public;
and then every body could see how shamefully the
French newsmongers had exposed their malice.

This year being come to an end, that of 1702 followed,
and also the end of king William`'s life.

The French king, upon the death of the king of Spain, had not only placed his grandson,
the duke of Anjou, on the throne of that kingdom,
but had also acknowledged the pretended prince of Wales as king of England; by which,
in a manner, he attained king William`'s crown;
who thereupon took occasion to make alliances for his security,
with other princes and potentates.
Of this he gave notice to the parliament that was then sitting,
who promised to assist him to the utmost of their power,
and to maintain the succession of the crown in the Protestant line.
And an abjuration was also drawn up,
wherein it was declared that the aforesaid pretended prince,
who now suffered himself to be called James the Third, king of England,
etc. had no right or claim to the crown of that kingdom,
or any dominions appertaining thereto.
Now though all this was intended for maintaining and assisting the rightful king William,
yet he lived not to see the effect of it; for his time was near expired,
and his glass run, as soon appeared.

About the beginning of the month called March, he went a hunting,
and riding a horse he never rode on before, the horse fell, and the king,
at the same time, broke his collar-bone: the fracture was soon set,
and all seemed like to do well; but the king having endured many fatigues and hardships,
had been weak in body some time before;
insomuch that this sore fall seemed to occasion his sickness, which soon followed,
and put a period to his life.
But before his departure, he did yet one good work more for the Quakers;
for the term of seven years,
granted for their affirmation to be accepted instead of an oath, was near expiring;
and therefore they solicited the king and parliament that this act might be continued,
and confirmed by a new one, which was obtained;
for the king always showed himself willing to favour them as his peaceable subjects;
and in parliament many eminent members were well affected towards them.
Thereupon this renewed act,
containing a prolongation of the said grant for the space of eleven years,
passed at length, after mature consideration, the king having named commissioners,
who on the third of March, gave the royal assent to it in the house of Lords, because,
by reason of his illness, he could not appear himself on the throne.
He also sent a message to the parliament,
recommending the uniting of the two kingdoms of England and Scotland, into one,
commissioners being already appointed in Scotland,
to treat with the English concerning that affair:
but time showed that he was not to bring that work to an end,
since the accomplishing thereof was reserved for his successor,
though some hopes appeared of his recovery;
for he had been walking a little in his garden to take the air,
and sitting down afterwards, he caught cold, which was followed by a fever;
and his sickness so increased, that on the next first-day of the week,
being the eighth of the month called March, he died at Kensington,
to the great grief of all his faithful subjects; nay,
such was the sorrow on the death of that excellent prince,
that the news of it being come to Holland, it caused a general dejection,
and drew tears from many eyes;
for perhaps no king in these late ages hath been more beloved than he was.
The day before his demise,
he had by commissioners given the royal assent to the bill
of abjuration of the pretended prince of Wales;
and the following night, feeling death approaching, he sent for the princess Anne,
sister of his deceased consort, queen Mary; and having kept her sometime with him,
after tender embracing, he wished her the last farewell.
Then he sent for the archbishop of Canterbury,
and his understanding continuing good to the last, with evident tokens of piety,
and a resignation to the will of his Creator, in the morning about eight of the clock,
he gave up the ghost to him from whom he had received it,
being entered into the fifty-second year of his age,
and having reigned as king above thirteen years.

In the afternoon the princess Anne was proclaimed queen of England, Scotland, France,
and Ireland, etc. and the parliament promised to assist her,
in maintaining those alliances that were already made, or should yet be made,
with foreign powers.
This the queen accepted with much satisfaction,
and confirmed the ministers and high officers in their respective stations.
She also wrote to the States-general of the United Netherlands,
that she would keep to the alliances made with the States by the deceased king,
her brother.

The body of the king, which was lean, and much emaciated, was opened after his death,
and many of the inward parts appeared sound, especially the brain;
yet in general little blood was found in the body; but in the lungs,
which adhered much to the pleura, was more than in all other parts;
his heart was firm and strong; but some inflammations, on the left side of the lungs,
was thought to have been the immediate cause of the king`'s death,
for he had long been asthmatical.

He was of a middle stature; his face lean and oblong; his eyes were exceeding good,
quick, and piercing; his hands very fine and white; he did not talk much,
but was solid in thought; of a strong memory, quick of apprehension, of a composed mind,
and not given to voluptuousness, but grave in his deportment;
he often gave evidence of a devout attention at the hearing of the name of God;
and even in the midst of dangers, put great trust in divine Providence.
Thus he was valiant and undaunted without temerity;
for where he judged his presence to be necessary, he repaired thither without fear.
He was a great lover of hunting, that being his most pleasant diversion,
which made him the more fit to endure the fatigues of war.
He was easy of access, and gave a favourable hearing to every body,
and those that spoke to him he treated discreetly; and such was his devotion,
that he often retired privately, when some thought he was about other business.
Many had conceived hopes that this great prince, in that critical juncture,
would have lived yet somewhat longer: but his work was done;
and God hath since that time showed very eminently,
that he is not limited to any instruments; and the queen who succeeded on the throne,
gave afterwards signal proofs of it to the world.
His corpse was interred the 12th of the month called April, about midnight,
in the chapel of king Henry the VIIth, in Westminster Abbey.

It was by the favour of this king, a Hollander by birth, that the Quakers, so called,
were tolerated a free people;
so that now they saw fulfilled the truth of what some of
their deceased friends had prophetically foretold,
viz. That it should not be in the power of their enemies to root them out, but that God,
in his own time, should work their deliverance.

Thus we have now seen from what weak beginnings they had their rise,
and how they increased and became a great people against all opposition,
of which at first there seemed little probability;
as in the beginning of this history may be seen: and to look a little back,
it may appear also, by a testimony of George Fox, published after his death,
in the collection of his epistles, viz.

[.embedded-content-document.testimony]
--

When the Lord first sent me forth in the year 1643, I was sent as an innocent lamb,
and young in years, amongst men in the nature of wolves, dogs, bears, lions, and tigers,
into the world, which the devil had made like a wilderness,
no right way then found out of it.
And I was sent to turn people from darkness to the light, which Christ, the second Adam,
did enlighten them withal; that so they might see Christ, their way to God,
with the Spirit of God, which he doth pour upon all flesh,
that with it they might have an understanding, to know the things of God,
and to know him, and his Son Jesus Christ, which is eternal life;
and so might worship and serve the living God, their Maker and Creator,
who takes care for all, who is Lord of all;
and with the light and Spirit of God they might know the Scriptures,
which were given forth from the spirit of God in the saints,
and holy men and women of God.

And when many began to be turned to the light, which is the life in Christ,
and the Spirit of God, which gave them an understanding,
and had found the path of the just, the shining light; then did the wolves, dogs,
dragons, bears, lions, tigers, wild beasts, and birds of prey, make a roaring,
and a screeching noise against the lambs, sheep, doves, and children of Christ,
and were ready to devour them and me, and to tear us to pieces.
But the Lord`'s arm and power did preserve me,
though many times I was in danger of my life,
and very often cast into dungeons and prisons, and hauled before magistrates.
But all things did work together for good: and the more I was cast into outward prisons,
the more people came out of their spiritual and inward
prison through the preaching of the gospel.
But the priests and professors were in such a great rage,
and made the rude and profane people in such fury,
that I could hardly walk in the streets, or go in the highways,
but they were ready ofttimes to do me a mischief.
But Christ, who hath all power in heaven and in the earth,
did so restrain and limit them with his power, that my life was preserved;
though many times I was near killed.

Oh, the burdens and travails that I went under!
Often my life pressed down under the spirits of professors and teachers without life,
and the profane!
And besides, the troubles afterwards with backsliders, apostates, and false brethren,
which were like so many Judas`'s in betraying the truth,
and God`'s faithful and chosen seed,
and causing the way of truth to be evil spoken of! but the Lord blasted, wasted,
and confounded them, so that none did stand long; for the Lord did either destroy them,
or bring them to nought, and his truth did flourish, and his people in it,
to the praise of God, who is the revenger of his chosen.

[.signed-section-signature]
G+++.+++ F.

--

G+++.+++ Fox then,
having in England been the first of the Quakers that
preached and proclaimed Christ the light,
which enlighteneth every man coming into the world, had in a short time,
as we have seen in this history, notwithstanding all opposition, many adherents,
whereby several others also began to publish that doctrine.
And many of these first preachers were like sons of thunder;
for they testifying of the light of Christ shining in the consciences of men, proclaimed,
that the day of the Lord was dawned and should yet further break forth,
to the destroying of the former buildings of human inventions and institutions;
though not of that which had formerly been felt and enjoyed by true experience
of the operations of the Spirit of God in people`'s hearts.
By their powerful way of preaching repentance,
many were awakened out of the sleep of careless security,
and came to see that their covering was too short,
and that they were not covered with the true wedding garment:
and many that had been of a rude life,
came to be so touched to the heart by these zealous preachers,
that crying out what shall we do to be saved?
they were brought to repentance and conversion; and so from wild and rough,
came to be sedate and sober.
And as in the beginning many of these first preachers did run on like a mighty stream,
and seemed fit to thresh and grind mountains and stones, and to hew down tall cedars,
and wash away all opposition; so there were others also, who as sons of consolation,
proclaimed glad tidings to the hungry and thirsty souls,
many of which were in England about that time, insomuch that some said,
Now the everlasting gospel is preached again.
And it was indeed remarkable,
that though these promulgators of the doctrine of
the inward light shining in the hearts of men,
were mean and illiterate, yet many people of note, not only such as were in magistracy,
but also many preachers of several persuasions,
were so touched at the heart by their lively preaching,
that they not only received their doctrine, but came themselves in process of time,
to be zealous publishers thereof, and thus a great crop was gathered;
nay sometimes even men of great skill, and sharp wit,
were deeply struck by plain and homely preaching; of whom,

Isaac Penington, mentioned more than once in this history, was a signal instance,
as may appear from a relation concerning himself, written with his own hand,
and found among his papers after his death, wherein he speaks as followeth:

[.embedded-content-document.testimony]
--

I have been a man of sorrow and affliction from my childhood,
feeling the want of the Lord, and mourning after him; separated by him from the love,
nature and spirit of this world, and turned in spirit towards him,
almost ever since I could remember.

In this sense of my low estate, I sought after the Lord, I read Scriptures,
I watched over mine own heart, I cried unto the Lord for what I felt the want of,
I blessed his name in what he mercifully did for me, and bestowed on me, etc.
Whatever I read in the Scriptures, as the way of God to my understanding,
I gave myself to the faithful practice of; being contented to meet with all the reproach,
opposition, and several kinds of sufferings,
which it pleased the Lord to measure out to me therein; and I cannot but say,
that the Lord was good unto me, did visit me, did teach me, and help me,
did testify his acceptance of me many times,
to the refreshing and joy of my heart before him.

But my soul was not satisfied with what I met with, nor indeed could be,
there being further quickenings and pressings in my spirit, after a more full, certain,
and satisfactory knowledge; even after the sense, sight and enjoyment of God,
as was testified in the Scriptures to have been felt and enjoyed in the former times;
for I saw plainly, that there was a stop of the streams,
and a great falling short of the power, life, and glory, which they partook of.
We had not so the spirit, nor were so in the faith, nor did so walk and live in God,
as they did.
They were come to Mount Zion and the heavenly Jerusalem,
etc. which we had hardly so much as the literal knowledge or apprehension what they were.
So that I saw the whole course of religion among us, was, for the most part, but a talk,
to what they felt, enjoyed, possessed, and lived in.

This sense made me sick at heart indeed, and set me upon deep crying to God,
close searching the Scriptures, and waiting on God,
that I might receive the pure sense and understanding of them, from and in the light,
and by the help of his Spirit.
And what the Lord did bestow on me in that state,
with thankfulness I remember before him at this very day: for he was then my God,
and a pitier and a watcher over; though he had not pleased then to direct me,
how to stay my mind upon him and abide with him.
And then I was led, (indeed I was led,
I did not run of myself,) into a way of separation from the worship of the world,
into a gathered society;
for this both the Scripture and the Spirit of God in me gave testimony unto;
and what we then met with, and what leadings and help we then felt,
there is a remembrance and testimony in my heart to this day.
But there was somewhat wanting, and we mistook our way,
for whereas we should have pressed forward into the spirit and power,
we ran too much outward into letter and form;
and though the Lord in many things helped us, yet therein he was against us,
and brought darkness, confusion, and scattering upon us.
I was sorely broken and darkened, and in this darkened state,
sometimes lay still for a long season,
secretly mourning and crying out to the Lord night and day; sometimes I ran about,
hearkening after what might appear or break forth in others,
but never met with any thing, whereto there was the least answer in my heart,
save in one people, who had a touch of truth;
but I never expressed so much to any of them,
nor indeed felt them at all able to reach my condition.

At last, after all my distresses, wanderings, and sore travails,
I met with some writings of this people called Quakers,
which I cast a slight eye upon and disdained, as falling very short of that wisdom,
light, life, and power, which I had been longing for and searching after: I had likewise,
some pretty distance of time after this, opportunity of meeting with some of them,
and divers of them were by the Lord moved, (I know it to be so since,) to come to me:
as I remember at the very first they reached to the life of God in me;
which life answered their voice, and caused a great love in me to spring to them;
but still in my reasonings with them, and disputes alone, in my mind, concerning them,
I was very far off from owning them, as so knowing the Lord,
or so appearing in his life and power as my condition needed, and as my soul waited for.
Yea, the more I conversed with them,
the more I seemed in my understanding and reason to get over them,
and to trample them under my feet, as a poor, weak, silly, contemptible generation;
who had some smatterings of truth in them, and some honest desires towards God,
but very far off from the clear and full understanding of his way and will.
And this was the effect almost of every discourse with them, they still reached my heart,
and I felt them in the secrets of my soul,
which caused the love in me always to continue, yea sometimes to increase towards them;
but daily my understanding got more and more over them,
and therein I daily more and more despised them.

After a long time I was invited to hear one of them, (as I had been often,
they in tender love pitying me,
and feeling my want of that which they possessed,) and there was an answer in my heart,
and I went in fear and trembling, with desires to the most High, who was over all,
and knew all, that I might not receive any thing for truth, which was not of him,
nor withstand any thing which was of him,
but might bow before the appearance of the Lord my God, and none other: and indeed,
when I came, I felt the presence and power of the most High among them:
and words of truth, from the spirit of truth, reaching to my heart and conscience,
opening my state as in the presence of the Lord.
Yea, I did not only feel words and demonstrations from without,
but I felt the dead quickened, the seed raised, insomuch as my heart,
in the certainty of light and clearness of true sense, said, "`This is he, this is he,
there is no other; this is he whom I have waited for and sought after from my childhood,
who was always near me, and had often begotten life in my heart,
but I knew him not distinctly, nor how to receive him, or dwell with him.`"
And then in this sense in the melting and breakings of my spirit,
was I given up to the Lord, to become his,
both in waiting for the further revealings of his seed in me,
and to serve him in the life and power of his seed.

Now what I met with after this, in my travails, in my waitings,
in my spiritual exercises, is not to be uttered; only in general I may say this,
I met with the very strength of hell.
The cruel oppressor roared upon me, and made me feel the bitterness of his captivity,
while he had any power; yea, the Lord was far from my help,
and from the voice of my roaring.
I also met with deep subtilties and devices to entangle me in that wisdom,
which seemeth able to make wise in the things of God;
but indeed is foolishness and a snare to the soul, bringing it back into captivity,
where the enemy`'s gins prevail.
And what I met with outwardly from my own dear father, from my kindred, from my servants,
from the people and powers of the world, for no other cause but fearing my God,
worshipping him as he hath required of me, and bowing to his seed,
(which is his Son,) who is to be worshipped by men and angels forevermore,
the Lord my God knoweth, before whom my heart and way are,
who preserved me in love to them, in the midst of all I suffered from them,
and doth still so preserve me, blessed be his pure and holy name.

But some may desire to know what I have at last met with: I answer,
"`I have met with the seed.`"
Understand that word, and thou wilt be satisfied, and inquire no further.
I have met with my God, I have met with my Saviour;
and he hath not been present with me without his salvation;
but I have felt the healing drop upon my soul from under his wings.
I have met with the true knowledge, the knowledge of life, the living knowledge,
the knowledge which is life; and this hath had the true virtue in it,
which my soul hath rejoiced in, in the presence of the Lord.
I have met with the seed`'s father, and in the seed I have felt him my father;
there I have read his nature, his love, his compassions, his tenderness,
which have melted, overcome, and changed my heart before him.
I have met with the seed`'s faith,
which hath done and doth that which the faith of man can never do.
I have met with the true birth, with the birth which is heir of the kingdom,
and inherits the kingdom.
I have met with the true spirit of prayer and supplication,
wherein the Lord is prevailed with,
and which draws from him whatever the condition needs,
the soul always looking up to him in the will,
and in the time and way which is acceptable with him.
What shall I say?
I have met with the true peace, the true righteousness, the true holiness,
the true rest of the soul, the everlasting habitation, which the redeemed dwell in.
And I know all these to be true, in him that is true, and am capable of no doubt,
dispute, or reasoning in my mind about them, it abiding there,
where it hath received the full assurance and satisfaction.
And also I know very well and distinctly in spirit, where the doubts and disputes are,
and where the certainty and full assurance is,
and in the tender mercy of the Lord am preserved out of the one, and in the other.

Now, the Lord knows, these things I do not utter in a boasting way,
but would rather be speaking of my nothingness, my emptiness, my weakness,
my manifold infirmities, which I feel more than ever.
The Lord hath broken the man`'s part in me, and I am a worm and no man before him:
I have no strength to do any good or service for him; nay,
I cannot watch over or preserve myself: I feel daily that I keep not alive my own soul,
but am weaker before men, yea weaker in my spirit, as in myself, than ever I have been.
But I cannot but utter to the praise of my God, that I feel his arm stretched out for me;
and my weakness, which I feel in myself, is not my loss, but advantage, before him.
And these things I write, as having no end at all therein of my own,
but felt it this morning required of me, and so in submission and subjection to my God,
have I given up to do it, leaving the success and service of it with him.

[.signed-section-signature]
I+++.+++ Penington.

[.signed-section-context-close]
Aylesbury, 15th of 3rd month, 1667.

--

From this conclusion, we see the humility of the mind of this friend, who,
when he wrote this, was already much advanced in the way of godliness,
and had lived several years in the communion of those called Quakers.
Now, though it be the duty of every one, not to be conceited of himself,
yet certain it is, that men of refined wits, above all others,
have need to continue truly humble, and not to rely thereon,
since the trusting to acuteness of wit, hath rather drawn off many from the way of truth,
than led them to it; nay, it hath occasioned the fall of some.
But that I. Penington endeavoured to continue in true humility,
appears plainly from the relation above.
He was a man of a very compassionate temper, and yet valiant in adversities:
he also suffered not a little on the account of his religion,
but endured many tedious and long imprisonments; which were the more hard to him,
because he being of a weakly constitution, the suffering of cold and hardship,
did him the more hurt.
And yet he never fainted, but continued steadfast to the end of his life,
which was in the latter part of the year 1679, when he departed in a pious frame of mind.

By the foregoing relation,
it appears evidently that he was very earnestly seeking after the true way to salvation,
before he attained to a perfect quietness of mind;
yet in that time there wanted not such as were helpful
to him with good and wholesome advice;
and among these John Crook, whose occurrences make up no small part of this history,
was none of the least.
And since there is yet extant a letter of his to him,
wherein he not only spoke very effectually to the inward state of I. Penington;
but for his instruction and encouragement,
gave also an account of the great difficulties and temptations he himself had met with,
I cannot well omit to insert the same here;
because from the ingenuous and open-hearted letters of familiar friends to one another,
we generally may discover very plainly their inward state,
and also their outward qualities.
This letter was as followeth:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

My dear and tender love salutes thee, in that love from whence I had my being,
from whence sprang all my Father`'s children, who are born from above,
heirs of an everlasting inheritance.
Oh! how sweet and pleasant are the pastures which
my Father causeth all his sheep to feed in:
there is a variety of plenty in his pastures, milk for babes,
and strong meat for them of riper age, and wine to refresh those that are ready to faint;
even the wine of the kingdom, that makes glad the heart when it is ready to faint,
by reason of the infirmities: sure I am, none can be so weary, but he takes care of them;
nor none so nigh fainting, but he puts his arm under their heads;
nor none can be so beset with enemies on every side, but he will arise and scatter;
nor none so heavy laden and big with young, but he takes notice of them,
and gently leads them, and will not leave them behind unto the merciless wolf;
because they are his own, and his life is the price of their redemption,
and his blood of their ransom; and if they be so young that they cannot go,
he carries them in his arms; and when they can feel nothing stirring after him,
his bowels yearn after them; so tender is this good Shepherd after all his flock.
I can tell, for I was as one that once went astray,
and wandered upon the barren mountains: and when I had wearied myself with wandering,
I went into the wilderness, and there I was torn as with briers,
and pricked as with thorns; sometimes thinking this was the way,
and sometimes concluding that was the way,
and by and by concluding all were out of the way.
And then bitter mourning came upon me, and weeping for want of the interpreter;
for when I sought to know what was the matter, and where I was, it was too hard for me;
then I thought I would venture on some way where it was most likely to find a lost God;
and I would pray with them that prayed, and fast with them that fasted,
and mourn with them that mourned, if by any means I might come to rest, but found it not,
until I came to see the candle lighted in my own house,
and my heart swept from those thoughts and imaginations, and willings, and runnings;
and to die unto them all, not heeding of them; but watching against them,
lest I should let my mind go a whoring after them; and here I dwelt for a time,
as in a desolate land uninhabited; where I sat alone as a sparrow upon the house top,
and was hunted up and down like a partridge upon the mountains; and could rest no where,
but some lust or thought or other followed me at the heels,
and disquieted me night and day, until I came to know him in whom was rest,
and no occasion of stumbling, in whom the devil hath no part;
and he became unto me as a hiding-place from the storms, and from the tempests;
then came my eyes to see my Saviour, and my sorrow to fly away,
and he became made unto me all in all, my wisdom, my righteousness, my sanctification,
in whom I was and am complete,
to the praise of the riches of his grace and goodness that endures forever.

Therefore be not discouraged, O thou tossed as with tempests, nor dismayed in thyself,
because thou seest such mighty hosts of enemies rising up against thee,
and besetting thee on every side; for none was so beset, and tried,
and tempted as the true seed was, who was a man of sorrows, and acquainted with grief:
but be thou still in thy mind, and let the billows pass over, and wave upon wave,
and fret not thyself because of them,
neither be cast down as if it should never be otherwise with thee: sorrow comes at night,
but joy in the morning, and the days of thy mourning shall be over,
and the accuser will God cast out forever; for therefore was I afflicted,
and not comforted, and tempted and tried for this end,
that I might know how to speak a word in due season unto
those who are tempted and afflicted as I once was:
as it was said unto me in that day when sorrow lay heavy upon me.
Therefore be not disconsolated,
neither give heed unto the reasonings and disputings of thy own heart,
nor the fears that rise therefrom; but be strong in the faith,
believing in the light which lets thee see them;
and his grace thou wilt know to be sufficient for thee,
and his strength to be made perfect in thy weakness;
and so wilt thou rather glory in thy infirmities, that his power may rest upon thee,
than in thy earnest desires to be rid of them;
for by these things thou wilt come to live in the life of God, and joy in God,
and glory in tribulation; when thou hast learned in all conditions to be contented;
and through trials and deep exercises is the way to learn this lesson.
These things, in dear love to thee, I have written,
being somewhat sensible of thy condition, and the many snares thou art daily liable unto;
therefore watch, that thou fall not into temptation,
and my God and Father keep thee in the arms of eternal love, over all, unto the end,
unto his praise.
Amen.

[.signed-section-signature]
John Crook.

--

This John Crook had been a man of note in the world,
not only because he had been a justice of peace, as hath been said in due place,
but also because he was a man of good intellects;
and yet his zeal for what he believed to be truth, was such,
that he became willing to bear the reproach of the world,
that so he might enjoy peace with God.
But though he was a man of learning,
yet most of the first preachers of the doctrine held forth by those called Quakers,
were people of small account in the world;
but yet they were so powerful in their preaching,
that many thereby were turned to true godliness.

Some have been reached by the sayings of dying penitents;
for there have been remarkable instances of young people sprung from honest parents,
who having walked in the broad way,
did very earnestly bewail their outgoings on a dying bed, and then declared,
that if it pleased God, to raise them up again, they would not, as before,
be ashamed of the despised way of the Quakers, nor fear any mockings or persecution,
but that they would serve the Lord, in uprightness, and with all their heart.
These thus repenting with tears for their transgressions,
have experienced after great agonies, that God wills not the death of sinners,
but that they should repent, and so live in everlasting happiness.

Of several such like cases, I will only mention one, viz. that of a young maid at London,
called Susanna Whitrow, whose mother was of the society of the Quakers,
but not her father.
On her dying bed she complained exceedingly of her rebellion and vain behaviour:
"`Ah,`" said she to her mother, "`how often hast thou said, the Lord would plead with us:
now the day is come.
Pride and disobedience were my cursed fruits,
which I brought forth when I was a hearer in the public church.
How often have I adorned myself as fine in their fashion as I could make me;
yet they despised my dress, and said, '`How like a tawdry have you dressed yourself;
you are not at all in the mode.`' Then coming home on the Sabbath-day,
I went immediately up into my chamber, and locking the door, I altered all my laces,
and so went to their worship in the afternoon, dressed in their mode,
and then I pleased them.`"
At another time she said,
"`O that I might have a little time longer to go into the country,
and walk in the woods to seek the Lord.
O what matter for fine houses and silk apparel: O remember him that sat on the ground,
and wore a garment without a seam, our blessed holy Lord,
who went up to the mountains to pray,
and withdrew himself into gardens and desolate places.
I have done nothing for the Lord, but he hath done all for me:
therefore I desire to live, that I might live an holy and righteous life,
that my conversation might be in heaven, though my body be here on earth.
How would I then invite and warn others,
not to spend their precious time in adorning themselves like Jezebel,
patching and painting, and curling their hair.
O the Christian life is quite another thing:
we must not give ourselves the liberty to think our own thoughts,
much less to act such abominations.`"
Several days she was in a strong wrestling and conflict of spirit,
and in fervent prayer to God, so that when somebody was for removing her head a little,
she refusing it, said, "`I would not suffer a thought to wander; if I move,
I shall be drawn off my watch, and then the temper will prevail.`"

Continuing in this conflict, she conceived at length hopes of forgiveness;
and being thus strengthened by mercy, she said to the Lord,
"`O what can my soul say of thy power: when I sought thee, but could not find thee;
I knocked hard, but none did open: for my sins stood like mountains,
that I could not come near thee: I would fain have prayed to thee, but could not.
Thus I lay several days and nights struggling for life, but could find none: and I said,
'`There is no mercy for me:`' then I said, "`I will never leave thee; if I perish,
I will perish here; I will never cease crying unto thee.`' And then I heard a voice say,
'`Jacob wrestled all night before he obtained the blessing.`' Oh then thy word, O Lord,
was strong to my soul: then my stony heart was broken to pieces,
and the spirit of prayer and supplication was poured upon me.
And now I can sing as David did, of mercy, and of judgment: '`Unto thee, O Lord,
will I sing, with a rent heart,
and with my mouth in the dust will I sing praises to thee,
my blessed Saviour.`'`" In this frame she endeavoured to continue,
and once she prayed for her father, called Robert Whitrow,
part of which prayer was as followeth: "`O Lord, remember not his offences,
let me bear them; let it be easy to him; make his friends to be enemies to him,
that thou mayest have mercy upon him.
His temptations are great; Lord, carry him through; O let him not perish with the world;
do thou support him over this world.
Shall a little dirt of this world draw away his mind: O Lord,
let his mind be set on things above; fix his mind upon thee.`"
Thus fervently this young maid prayed for her father,
herself now having attained a full assurance of her salvation,
so that she once said to the Lord, "`O thou beloved of my soul, what shall I say of thee,
for thou art too wonderful for me: O praises be unto thee.`"
And afterward perceiving that her end was approaching, she said to her mother,
"`I must lay down this body,
the Lord will not trust me longer in this present wicked world: happy am I: my Saviour,
my soul loves thee dearly; thy love is better than wine: my Saviour, my holy One,
how glorious art thou: I have seen thy glory; I am overcome with thy sweet countenance;
O how lovely art thou!
My heart is ravished with the sweet smiles of thy glorious countenance.
O, come away, come away, why dost thou stay?
I am ready, I am ready.`"
Then she lay some time very still, and so departed this life without sigh or groan:
which was about the year 1677.

Such like dying persons have been the means sometimes to stir up others to true godliness,
whereby they came to be joined with the people called Quakers;
and though these in time came to be very numerous,
yet at first there were but few labourers in the ministry of the word.
But these recommending one another to give diligent heed to the word of God in the heart,
and to mind that as their teacher, did often meet together and keep assemblies,
sitting down with such a deep retiredness of mind, being turned inward to God,
that tears trickled down their cheeks, to the astonishment of many that looked upon them,
some of which, only by beholding this retiredness, came to be so effectually reached,
that they also joined with them, and frequented their meetings.
In the mean while many of these became more and more
confirmed in their minds by this silent exercise,
and their understandings came to be so opened,
that in process of time they became apt and fit instruments to exhort others to godliness:
and among these several women also found it their duty to preach the gospel.

There have been many who were very averse to the Quakers,
and yet came to join with them in the faith; as among others, Christopher Bacon,
in Somersetshire, who, about the year 1656, coming into a meeting,
not with intention to be edified there, but rather to scoff,
and to fetch his wife from thence, who went thither against his mind,
was so reached by the lively exhortation he heard,
that he was not only convinced of the truth preached there,
but in time became a zealous preacher of it himself, and was valiant in sufferings.
Once being taken up at a meeting in Glastonbury, and brought before bishop Mew, at Wells,
who called him a rebel, for meeting contrary to the king`'s laws,
Christopher having formerly been a soldier for the king, said to him,
"`Dost thou call me rebel: I would have thee to know,
that I have ventured my life for the king in the field,
when such as thou lay behind hedges.`"
By this he stopped the bishop`'s mouth, who did not expect such an answer,
and therefore was willing to be rid of him.

The like instance of an unexpected conversion, was seen also in William Gibson,
whom I knew well, and who at the time of the civil wars, being a soldier at Carlisle,
he and three others having heard that a Quakers`' meeting was appointed in that city,
they agreed to go thither and abuse the preacher, whose name was Thomas Holmes;
but Gibson hearing him powerfully declare the truth, was so affected by his testimony,
that he stepped in near him, to defend him, if any should have offered to abuse him:
and he himself afterwards came to be a zealous preacher
of that truth he had been at unawares convinced of.

To these instances I may add that of a certain trumpeter,
who coming into a Quakers`' meeting, began in an insolent manner to sound his trumpet,
thereby to drown the voice of him that preached: but this had a contrary effect,
and stirred up the zeal of the preacher the more,
so that he went on as if none disturbed him.
The trumpeter at length, to recover his breath, was fain to cease blowing;
but being still governed by an evil spirit, after some intermission began to sound again;
but whatever he did, he was not able to divert the preacher from his discourse,
though he hindered the auditory from hearing what was spoken.
Thus he wearied himself so much that he was forced to rest again for respiration:
whereby in spite of his evil will, he came to hear what the preacher spoke,
which was so piercing, that the trumpeter came to be deeply affected with it,
and bursting into tears, confessed his crime, and came to be a true penitent:
a remarkable evidence of the truth of that saying of the apostle, "`So then,
it is not of him that willeth, nor of him that runneth, but of God that showeth mercy.`"

Among these, who contrary to their intent entered into communion with the Quakers,
so called, may be reckoned also Anthony Pearson, the justice,
of whom in this history it hath been mentioned, that he was so reached by G. Fox,
at Swarthmore, that he came to be one of his followers; which though true,
yet it was before that time that he was in some respect convinced
of the doctrine maintained by the people called Quakers:
which happened to be by James Nayler, who upon an indictment of blasphemy,
appearing at the sessions at Appleby, in the month called January, 1652,
found the said justice Pearson sitting there on the bench as one of his persecutors:
who asking him several questions received such pertinent answers from J. Nayler,
that in a great degree he was convinced of the truth held by J. Nayler and his friends.

By what hath been related here may be seen how unexpectedly
some entered into society with the Quakers,
so called; more instances of which might be produced if needful; since I have known such,
who being naturally of a boisterous temper,
yet were so struck with the terror of the Lord,
that they came to be of such a quiet spirit, and harmless behaviour,
that as formerly they could not suffer the least provocation,
so now they bore all revilings and mockings with an even and undisturbed mind;
because the fear of God had made such deep impression upon them,
that they were careful lest by an angry or impetuous
deportment they should sin against him.
And thus continuing to live in fear, and a reverential awe,
they improved in true godliness;
insomuch that by their pious lives they preached as well as others with words.
After this manner the number of their society increased;
but then grievous sufferings ensued;
for the priests could not endure to see that their hearers left them;
the furious mob was spurred on, and among the magistrates there were many, who,
being of a fierce temper,
used all their strength to root out the professors of the light,
(as they were called at first,) and to suppress and stifle their doctrine;
but all proved in vain, as appears abundantly from this history;
although there were hardly any prisons in England,
where some of these people were not shut up; besides the spoil of goods,
and cruel whippings that befel some of them.
Yet all this they bore with a more than ordinary courage, without making resistance,
how great soever their number was;
and notwithstanding many of them had been valiant soldiers,
who often had slain their enemies in the field, without regarding danger.

In the consideration of this undaunted steadfastness, it hath seemed to me,
that there have been some such among this people,
whose talent was valiantly to endure persecution for a good cause;
and who perhaps in ease would not have been such good Christians
as they proved to be under these sufferings;
resembling the camomile in this, which the more it is depressed or rubbed,
the better it grows, and yields the stronger scent.
Being then thus oppressed,
they found themselves under a necessity of continuing vigilant and watchful; and,
according to king Solomon`'s advice, to keep their hearts with all diligence.
This made them love what they judged to be truth, more than their lives,
and it caused them to be careful,
lest that should come over them which the church of Ephesus was threatened with,
because she had left her first love,
viz. the removing of her candlestick out of its place.
Thus their mutual love increased, and their own lives they valued not,
when the grieving of their consciences stood in competition with it.

Having thus passed through many adversities, with an unwearied and lasting patience,
and being become a great people, known by the name of Quakers, they were at length,
by the generous clemency of king William III.
and the favour of the Parliament, declared to be a society,
who should henceforth be tolerated in the kingdom as Protestant dissenters,
with liberty to perform their religious worship in public without disturbance.
