== Chapter XXIV.

=== 1702--1717.

[.chapter-synopsis]
* Address from Friends to the Queen on her ascending the throne
* Address of the Yearly Meeting to the Queen on her declaring she would maintain the Act of Toleration
* Account of the life and death of Margaret Fox
* G. Keith and the fruits of apostacy
* Friends doctrine concerning the Light and some account of their testimonies
* Death and character of Anne Audland
* Union of England and Scotland
* Address of the Yearly Meeting on account of the Union
* G. Whitehead and the Queen
* Letter of Samuel Crisp a Clergy man turned Quaker
* Evan Jevan`'s account of his change
* Address of the Quakers in London on account of the Queen`'s renewed promise to maintain toleration
* Address of the Quakers on the peace between England and France
* Remonstrance against a bill to prevent the growth of Schism
* Death of the Queen
* King George proclaimed
* Address of the Quakers to the King
* Speeches of G. Whitehead to the King and Prince
* King George favorable to Friends
* Congratulation of King George on the suppression of the rebellion by the Yearly Meeting
* Epistle from the Yearly Meeting in London in 1717
* Conclusion

Queen Anne having now ascended the throne, and taken in hand the reins of government,
was congratulated from all quarters;
and the people called Quakers thought themselves no less
obliged than others to condole the king`'s death,
and testify their affection and fidelity to the Queen;
and therefore they drew up an address; and when some of them,
of whom G. Whitehead was one, went to present it, (which was on the 11th of the 2d month,
April,) they were introduced by the then earl, but now duke, of Marlborough,
and the duke of Ormond.
The address was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To Queen ANNE, over England, etc.

[.salutation]
May it please the Queen,

We, thy peaceable subjects,
cannot but be sorrowfully affected with a deep sense of the loss
sustained by the death of our late king William the Third,
whom God made the instrument of much good to these nations;
a prince who indeed desired to be the common father of his people,
and as such did by his great example, as well as precept,
endeavor to unite them in interest and affection,
and promoted and confirmed a legal liberty to tender consciences,
by all which his reign was adorned, to the renown of his memory.

And it having pleased the all-wise God, the disposer of kingdoms,
to preserve thee to succeed to the government of these nations;
and thereby to the maintaining and consummating those great works so happily begun;
we humbly beg leave to congratulate thy free and peaceable accession to the throne,
from whence we observe the queen`'s excellent declaration,
manifesting her care for the good of all her people, and therefore doubt not but we,
her Protestant dissenting subjects, shall partake of her royal favor and protection.

We sincerely declare, that with the assistance of the grace of God, we will always,
according to our Christian duty, demonstrate our good affection, truth,
and fidelity to the queen and her government;
and heartily pray that his wisdom may direct,
and his blessing be upon the queen and her great council,
to the suppressing of vice and immorality, and the promoting of piety, peace,
and charity, to the glory of God, and the benefit of these nations.

May the King of kings make thy reign long and glorious,
to which temporal blessing we shall pray for thy eternal happiness.

[.signed-section-context-close]
Signed on behalf and by appointment of the aforesaid people, at a meeting in London,
the 10th of the second month, 1702.

--

This address was very favorably received by the queen, and after it was read to her,
she answered, '`I thank you for your address, and I assure you of my protection.`'

It was scarce a month after, when war was proclaimed in England against France,
which had been proclaimed in Holland also against that crown some days before.
Not long after followed the general yearly meeting of those called Quakers,
held at London, in which it was thought fit to thank the queen for her declaration,
that she would maintain the act of toleration in favor of the dissenters;
and therefore an address was drawn up by the said assembly, which was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To Quean ANNE, over England, etc.

The humble and thankful acknowledgment of the people commonly called Quakers, from,
their yearly meeting in London, the 30th day of the 3d month, called May, 1702.

[.salutation]
May it please the Queen,

We, thy peaceable and dutiful subjects,
met from most parts of thy dominions at our usual yearly meeting,
(for the promotion of piety and charity,) being deeply affected with thy free
and noble resolution in thy late speech at the prorogation of the parliament,
to preserve and maintain the act of toleration for the ease and quiet of all thy people,
could not but in gratitude esteem ourselves engaged both
to thank Almighty God for that favorable influence,
and to renew and render our humble and hearty acknowledgments to the queen for the same,
assuring her, on behalf of all our friends,
of our sincere affection and Christian obedience.

And we beseech God, the fountain of wisdom and goodness,
so to direct all thy counsels and undertakings, that righteousness,
which exalts a nation, and mercy and justice, that establish a throne,
may be the character of thy reign, and the blessings of these kingdoms under it.

[.signed-section-signature]
Signed by the appointment and on the behalf of the said meeting.

--

Of those who presented this address, William Penn was the deliverer,
and the queen was pleased to speak to him in a very kind manner,
and not only received the said address favorably, but after it was read to her,
she made the following most gracious answer:

[quote]
____
Mr. Penn, I am so well pleased that what I have said is to your satisfaction,
that you and your friends may be assured of my protection.
^
footnote:[This, from the Record,
appears to be rather the substance than the exact words of the answer.]
____

This year died Margaret, the widow of G. Fox, at about eighty-seven years of age,
as appears to me from an account of her son-in-law, Dr. Thomas Lower, in which I find,
that she was born at Marsh-Grange, in the parish of Dalton, in Lancashire.
Her father was John Askew, a gentleman of an ancient family, a man of a good estate,
and famous for his piety and charity.
His daughter Margaret was religious even in her young years, and was married,
before she attained the age of eighteen, to Thomas Fell of Swarthmore;
who being bred a lawyer, became a justice of the peace,
and having afterwards been a member in several parliaments,
was made a vice-chancellor of the county of Lancaster, and in process of time a judge,
being beloved because of his justice, wisdom, moderation, and mercy.

In the year 1652, George Fox coming the first time to his house,
when he himself was from home, did by his exhortations so reach to the family,
that a priest with some gentlemen went and told judge Fell,
that a great disaster had befallen his wife and family,
they being seduced and turned Quakers.
This was so odiously represented to him, that it troubled him not a little:
but being come home, and received very kindly by his wife, according to her usual manner,
he soon perceived that it had been intended to make him believe untruths,
and possess him with prejudice.
Not long after George Fox got opportunity to speak to him,
which gave him such satisfaction, that he owned that which was spoken to be truth;
and his wife ordered a dinner to be made ready for her friend G. Fox,
and those that were with him.
And some time after he told his wife,
when he heard that she and her friends were consulting where to have a meeting,
that they might meet in his hall, which they did;
and though he himself did not come there, yet when a meeting was kept,
he used to sit in a chair so near to it, that though he could not be seen of every body,
yet he could hear what was preached; which he liked so well,
that it is not known that after he had heard George Fox,
he ever frequented the public church: insomuch,
that though he entered not into full society with the Quakers, yet he favored them,
and several times stopped the malice of their persecutors,
when it was in his powder so to do.

After he had been married six and twenty years to Margaret, and had nine children by her,
he deceased in the year 1658, leaving behind him a son and seven daughters.

Margaret being thus become a widow, neglected no opportunity to serve her friends.
In the year 1660, when king Charles II. was restored, scarce two weeks after he came in,
she went to London, and spoke several times with that prince,
that he would cause the sufferings of her friends to cease;
and in order thereto she wrote, not only to him,
but also to the dukes of York and Gloucester, the queen mother, the princess of Orange,
and the queen of Bohemia.
And after having been about fifteen months at London,
she at length prevailed with the king, that her friends who were in prison,
were released by proclamation.
But persecution afterwards beginning again,
she went to speak with the king and the duke of York, at Hampton Court.
In the year 1664, for refusing to swear, she was confined in Lancaster Castle,
and kept long in durance: for because of her great service in the church,
she was much envied, as well as George Fox,
to whom she was married about eleven years after
the decease of her first husband judge Fell.
But not long after, she was again imprisoned, and continued a year in jail,
being most part of that time sickly;
and afterwards was several times fined for preaching, In the seventieth year of her age,
she spoke again with the king, which was the last time;
but she was not received so favorably as formerly, far he seemed to be somewhat angry;
and therefore she wrote to him, and stayed at London in hopes of an answer;
but he was suddenly taken away by death.
Afterwards she spoke with king James, and wrote to him also.
And at length after a laborious and godly life,
she piously departed from hence in a great age, as hath been said already,
having uttered in the time of her sickness, many excellent sayings,
by which it appeared that she was prepared for death, and longed to be dissolved.
She had been a zealous preacher, and also written much,
and among the rest a book entitled, [.book-title]#The Call of the Jews out of Babylon,# which she
dedicated to the famous Manasseh Ben Israel,
and charged him, as he would answer it before God,
to cause it to be read among his brethren.
This book being translated by William Ames into Dutch, was also printed in that language,
whilst her first husband lived.

The same year she died, George Keith,
who now preached up and down where the bishops thought fit,
went by their order to New England, New York, Pennsylvania,
etc. for it seems he imagined that in those parts
he should get many adherents among the Quakers:
but he came much short of his aim; for even in Pennsylvania,
where many of the Baptists formerly sided with him,
he was by them looked upon with disdain, and rejected for wearing a clergyman`'s gown;
and now appearing to be a great apostate,
there was no likelihood for him to get entrance, or to be esteemed there.
After some time being returned into England, he got a living in the parish of Edburton,
in Sussex, worth about 120/. a year.
Now though the Episcopalians seemed to be in great expectation
that Keith should suppress the doctrine of the Quakers,
yet all his endeavors proved in vain; for whatever some may think, it is certain,
and appears from this history,
that they are become a great people after a very singular manner,
and that all projects and attempts to root them out, have been quashed,
and come to nought: and from this consideration it was, as I have reason to think,
that many of the Quakers, so called, in their preaching did sound forth these words,
being as it were extorted from Balaam: "`There is no enchantment against Jacob,
nor divination against Israel;`" as I myself have often heard.
And now the strength and power of their violent opposers
was broken by the favor of king William the Third,
and his successor, queen Anne,
hath favorably confirmed the liberty of conscience and worship,
granted by an act of parliament to the Quakers.
So that now we may look upon them as a free people,
and a society tolerated by supreme authority;
and therefore I might now finish this history, as to the import of the title.

But before I conclude, I intend to say something concerning their doctrine,
of which mention hath been often made in this work, viz., That their chief principle,
in which they differ from the generality of modern Christian societies, is,
That every man is enlightened with the Divine light, according to the evangelist John,
who in the first chapter, speaking of Christ, as he was from eternity with the Father,
calls him the Word, and saith.
"`That the Word was God, that all things were made by him, that in him was life,
and the life was the light of men,`" And the evangelist
speaking concerning John the Baptist,
who was sent from God, saith,`" He was not that light,
but was sent to bear witness of that light.
That was the true light,
which lights every man that cometh into the world.`" By this it appears,
that the Quakers have not coined a new phrase,
but only made use of the express words of the holy Scripture.
I am not unacquainted that, during the great apostasy,
people generally have not clearly understood this; yet it ought not to seem strange,
because the evangelist saith, "`The light shines in darkness,
and the darkness comprehended it not.`" But to elucidate this doctrine a little more,
it may serve for information,
that the Quakers believe this light to be the same that
the apostle Paul calls "`The grace of God that brings salvation,
and hath appeared to all men:`" and concerning its operation, he saith, "`teaching us,
that denying ungodliness, and worldly lusts, we should live soberly, righteously,
and godly in this present world.`"

Thus much briefly, concerning the above-mentioned denominations of this divine light;
and to make it appear more plainly what this phrase means,
"`Take heed to the Light;`" thereby we understand,
that each one minding the counsel of the light in their souls, may learn to fear God,
and hate pride, arrogance, and every evil way;
which will beget in us such a reverential awe towards God,
that we dare not do any thing which we certainly know will displease him;
and this is the first step to godliness: and therefore both David and Solomon have said,
that the fear of God is the beginning of wisdom; viz. that fear which is filial,
accompanied with circumspection and cautiousness; and as we persevere in this fear,
we are enabled to serve the Lord with holiness and
righteousness all the days of our life.

But since we can do this only by the grace of God,
it is absolutely necessary that we take heed thereto:
and therefore we ought to pray to God continually for his assistance.
But here starts up something, of which people generally have a strong notion:
for all sorts of Christians agree, that we must often pray to God,
but in the manner of it many err greatly.
For some think they perform this duty of praying to God,
when in the mornings and evenings,
and at others certain times of the day they repeat or recite some forms of prayer,
and do not seem to consider, that men ought always to pray, and not to faint.
And the apostle Paul exhorts to pray without ceasing.
And what this means he himself explains in these words,
"`Praying always with all prayer and supplication in the Spirit,`" which plainly shows,
that it consists not in a continual repeating of prayers,
but in pious and devout breathings to God, raised in the soul by the spirit of Christ,
that it may please him to keep us continually in his fear and counsel,
since we are in want of daily support from him.
And thus praying in faith, we receive an answer to our breathings in some measure,
though not always so soon as we desire; but we must not faint;
and our prayer must be from a sincere believing and breathing of the heart;
otherwise we pray amiss, and do not receive:
according to the saying of the apostle James, "`Ye ask, and receive not,
because ye ask amiss.`" But what devices and wiles
have not been invented by the enemy of man`'s soul,
to keep him off from this continual state of prayer!
although Christ very expressly saith,
"`Watch and pray, that ye enter not into temptation.
And, what I say unto you, I say unto all, watch;`" which,
in regard to the instruction we may reap thence,
doth not imply a continual watching without sleeping, but a vigilance of the mind,
which Solomon recommends in these words,
"`Keep thy heart with all diligence.`" Now though our constitution doth not seem
to admit an incessant continuance in the deepest retiredness of mind;
yet this is certain, that the more fervently we turn our minds to God,
the more we are kept from evil.
And man persevering in this godly exercise,
is the less in danger of falling into spiritual pride;
since he finds that his preservation is in true humility,
and in a continual dependance upon God; for if he once departs from thence,
and thinks himself safe enough,
and that now he needs not to walk circumspectly in fear as he once did,
then he is caught already, and somewhat gone astray from his spiritual guide: to wit,
from that which showed unto him his transgressions,
and troubled him whilst he was in the evil way.
And this is the manifestation of the spirit, which the apostle saith,
is given to every man to profit withal.

Now to call this principle, which reproves men for evil, and consequently discovers it.
Light, doth not carry with it any absurdity,
especially if we consider that this denomination is found in sacred writ.
Evil deeds are called by the apostle the works of darkness; and saith he,
"`All things that are reproved, are made manifest by the fight:
for whatsoever doth make manifest, is light.`" By which it appears plainly,
that the Quakers have not coined a new phrase, but only followed the scripture language.
And that they are not the only people that have declared of the light,
might be proved from other authors of good esteem, if necessity required.

As to oaths, they judge the taking of an oath unlawful; and why,
may abundantly be seen in this history from a multitude of instances.

The making of war they also believe to be inconsistent with pure Christianity,
and esteem that its followers, being led by its precepts,
will come to beat their swords into plowshares, and their spears into pruning-hooks,
and not to learn war any more, according to the prediction of the prophet, Isaiah 2:4:
and Christ, the author of our faith, unto whom we are commanded to look, saith expressly,
"`My kingdom is not of this world: if my kingdom were of this world,
then would my servants fight.`" And the apostle, James iv.
giveth us to understand, that wars and fightings come of lusts.
And we believe that by receiving the spirit of Christ in our souls,
and being entirely guided by it, enmity and lusts, the root of wars and fightings,
come to be destroyed, and his love remains,
by which we not only love one another sincerely, but also can love our enemies,
and pray for them; as also for those who hate and persecute us for his name,
not rendering evil for evil, but good for evil;
and this we believe to be that lamb-like spirit which will prevail, and must overcome,
and therefore they judge it not lawful for them to make war,
and for all that they think that they may very safely be tolerated by the civil government:
not only because they are willing and ready to pay taxes to Caesar,
but also that since they cannot fight for the government,
neither can they fight against it.

Concerning the sword of magistracy, they do in no wise assert,
that it is unlawful for some Christians to be magistrates: for to say so,
what doth it imply, but the unchristianing of magistrates, whom they truly honor;
magistracy being the ordinance of God.
But although they believe this office to be consistent with Christian religion,
yet they think it more safe for themselves not to seek for it.

Tithes to the priests they do not look upon as a gospel maintenance;
since our Savior said in express terms to his disciples, "`Freely ye have received,
freely give;`" yet they do not stretch this so far,
as not to suffer that any who hath imparted of his spiritual gifts to others,
might not receive temporal gifts of them, if he himself was in want thereof,
provided the maintenance of a minister of the gospel be free, and not forced;
and also that it consists not in a fixed stipend,
which leads to turn the ministry of the gospel into a provision of a livelihood;
which they look upon to be far beneath the dignity of the ministerial office,
which ought to be performed purely out of love to God and our neighbor,
and not with any regard to secular gain.

The ordinary way of showing respect or honor in common
conversation is also what they scruple;
for to give the same outward sign of respect to men, which is given to God,
viz. the uncovering of the head, they think, not without good reason, to be unfit;
and so they esteem also the giving flattering titles of honor;
since Christ so sharply reproves the greetings in the markets,
and the being called of men Rabbi, Rabbi, saying,
"`Be not ye called Rabbi;`" which title of that time
may be equalled with the modern master or sir.
Thus Christ saith also, "`How can ye believe,
who receive honor of one another?`" Yet they limit
this only to common conversation with one`'s equals:
for a servant may call his master by that title,
and subjects their magistrates by the title of their office,
and this may be spoken not contrary to truth;
whereas the other is nothing but mere flattery, invented to gratify and cherish pride:
and therefore they think it inconsistent with the true gravity of a Christian
to call one`'s self a servant of one who has not any mastership over us;
and they believe we cannot be too cautious in speaking, since our Savior saith,
"`That every idle word that men shall speak,
they shall give account thereof in the day of judgment.`"
The common fashion of greeting they also decline,
thinking it more safe not to imitate the ordinary custom therein.
But that it is more agreeable with Christian simplicity
to greet one another by giving their hand,
or by other innocent and harmless notice in passing by,
which are signs of friendship and respect, that may be showed,
without giving to man that which appertains to God,
as the uncovering of the head is among Christians:
for the uncovering of the head is an outward sign
of the worship and honor that is paid to God:
and if we give the same token also to men, it may be queried,
wherein the difference consists?
If it be answered that it consists in the meaning and intention,
then use is made of the same argument,
whereby Papists endeavor to excuse their adoration of images and relics.

As the Quakers testify against the common vain way of salutation,
so likewise against gaming, interludes, jesting,
and all sinful and unprofitable recreations, and drinking of healths,
all which they believe to be contrary to the exhortation of the apostle,
"`Whether ye eat or drink, or whatsoever ye do, do all to the glory of God.`"

In their method of marriage, they also depart from the common way:
for in the Old Testament they find not that the joining
of a couple in marriage ever was the office of a priest,
nor in the gospel, any preacher among Christians appointed thereto.
Therefore it is their custom, that when any intend to enter into marriage,
they first having the consent of parents or guardians,
acquaint the respective men`'s and women`'s meetings of their intention,
and after due inquiry, all things appearing clear,
they in a public meeting solemnly take each other in marriage,
with a promise of love and fidelity,
and not to leave one another before death separates them.
Of this a certificate is drawn,
mentioning the names and distinctions of the persons thus joined,
which being first signed by themselves, those then that are present sign as witnesses.

In the burying of their dead they mind decency, and endeavor to avoid all pomp;
and the wearing of mourning is not approved among them;
for they think that the mourning which is lawful,
may be showed sufficiently to the world by a modest and grave deportment.

As to water-baptism, and the outward supper, though they do not use the external signs,
witnessing Christ the substance to be come,
yet they are not for judging others who do use them conscientiously and devoutly.
They do not deny that water-baptism was used by some in the primitive church;
but let it be considered unto whom it was administered,
viz. to such that came over either from the Jews or the Gentiles,
to the Christian society: and baptism was as well a judaical ceremony as circumcision:
for, according to the account of Maimonides,^
footnote:[Vid. John Leusdcn Philog. Hebrseo-mixt,
Dissertat. xxi. de Proselyt. Sect. 1. pag. mihi 144.]
a Gentile, who would be received into the covenant of the Jews,
must be baptized as well as circumcised, whereby he became a proselyte.
Whence it evidently appears that baptism did not come in the place of circumcision,
as it hath been often urged to persuade the ignorant.
But as a Jewess proselyte needed not to get the child she brought forth baptized,
since the Jews did not baptize their children,
but administered baptism only to such of the Gentiles that came over to them;
so we do not find the least evidence that the primitive
Christians in the time of the apostles,
did baptize their issue, that so they might claim to be members of the church;
but the contrary seems rather to appear from what the apostle saith,
"`The unbelieving husband is sanctified by the wife,
and the unbelieving wife is sanctified by the husband; else were your children unclean,
but now they are holy:`" which implies no more, but that such children,
whose father or mother alone was a believer, were not excluded from, but comprehended in,
the outward membership: for this cannot have any relation to that sanctification,
whereby the mind comes to be cleansed:
but in regard of being partaker of the outward fellowship, this reached so far,
that if but one of the parents, either father or mother, was a believer,
the child thereby became entitled to the outward society:
for to make one a true and real member of the church of God,
the baptism of the spirit was required, as the main thing; which made John the baptist,
speaking of Christ, say,
"`He shall baptize you with the Holy Ghost.`" And the apostle Peter signifies,
that baptism, which now saves us, is not the putting away of the filth of the flesh,
but the answer of a good conscience towards God.
This was that baptism of which God by the prophet Ezekiel said concerning Israel,
"`I will take you from among the heathen, and gather you out of all countries.
Then will I sprinkle clean water upon you;
and ye shall be clean from all your filthiness,`" etc.

It is a common objection, that Christ himself was baptized with water,
and that we are required to follow his footsteps:
but let it be considered that he was circumcised also,
though the one as well as the other needed not to his melioration,
but was done for our sake, to show us by the latter, that our hearts must be circumcised,
that is, separated from all evil inclinations and lusts.
And by the baptism which he suffered to be administered to him,
is signified to us that we must be baptized by his spiritual baptism.
And if it be objected, that Christ said to Nicodemus,
'`Except a man be born of water and of the spirit,
he cannot enter into the kingdom of God;`" it may be answered,
that if this must be understood of outward water, the consequence will be,
that water-baptism is of such an absolute necessity, that if any be deprived of it,
he is to be shut out of heaven, which, though believed by Papists,
yet I think Protestants will hardly say so; neither was John Calvin^
footnote:[Vid. Calvin, Epist. 184. and 229.]
of that opinion.
It is also worth taking notice, that John the Baptist, said,
"`That Christ should baptize with fire;`" by which it appears,
that both water and fire in this sense, are metaphorical expressions;
for they both serve for cleansing and purifying, though in a different way.
Now although some did baptize with water, yet it ought to be considered,
that if the command of Christ to his disciples, "`Go ye and teach all nations,
baptizing them in the name of the Father, and of the Son,
and of the Holy Ghost,`" related absolutely to water-baptism,
it would indeed have been very strange, that Paul, that eminent apostle of the Gentiles,
did not think himself commissioned for the administration of that baptism.
Whereas, if the apostles had really received a commission from the Lord to that purpose,
he by no means would have been singled out; since speaking of himself he saith.
That he supposed he was not a whit behind the very chiefest apostles;
and yet he also saith in express terms, "`Christ sent me not to baptize,
but to preach the gospel.
And I thank God that I baptized none of you but Crispus and Gaius.
And I baptized also the household of Stephanus: besides,
I know not whether I baptized any other.`" And yet he saith, "`There is one Lord,
one faith, one baptism,`" which was the baptism of the Spirit.
And the same apostle saith also, "`As many as have been baptized into Christ,
have put on Christ:`" and this cannot have relation to water-baptism,
because many receive that, who never put on Christ, and become conformable to his image,
which however is required of all Christians.
To this may be added, that if the command to baptize, Matt. 28:19,
were literally restricted to water-baptism,
then why not our Savior`'s words be as well understood
literally concerning the washing his disciples`' feet,
when he said to Peter, "`If I wash thee not,
thou hast no part with me;`" and to his disciples,
"`If I then your Lord and Master have washed your feet,
ye also ought to wash one another`'s feet.`" More might be said on this subject;
but since R. Barclay hath treated of this matter at large long ago,
the reader may apply to his [.book-title]#Apology for the True Christian Divinity.#

Concerning the outward supper, it may be truly said,
that it was the passover that was kept by Christ at the eating of the paschal lamb;
which likewise was a judaical ceremony,
that Christians generally take to be a figure or shadow.
But is not the modern use of the outward supper in remembrance of Christ`'s sufferings,
also a figure, viz. of his spiritual supper with the soul; and doth it not seem absurd,
that one figure should be the antitype of the other.
The passover was not a memorial of another sign that was to follow;
but it was a memorial of the slaying of all the first-born in Egypt,
and of the preservation of Israel and their first-born.
Moreover it may be said, that the paschal lamb was eaten in their families,
whereas the outward supper now is celebrated in public places for worship.
We find, that the apostles, "`Breaking bread from house to house,
did eat their meat with gladness and singleness of
heart;`" which implies an usual meal or eating.
And certainly they do well, who daily at meals remember Christ and his sufferings:
for the spiritual supper, which is the thing required,
ought to be partaken of by every true Christian; and this cannot be, unless, we,
being attentive, open the door of our hearts to Christ, and let him come in.
Let it also be considered, that the soul wants daily food as well as the body;
and being destitute of that, will faint and languish, and so become unable to do good;
and therefore our Lord recommended his disciples to pray for daily bread:
for that this chiefly had relation to the spiritual manna,
the bread that comes down from heaven, appears from this saying of Christ,
"`labor not for the meat which perishes,
but for that meat which endures unto everlasting life.`" Bedsides, the apostle tells us,
'`That the kingdom of God is not meat and drink, but righteousness, and peace,
and joy in the Holy Ghost.`" And the author to the Hebrews saith,
"`It is a good thing that the heart be established with grace, not with meats,
which have not profited them that have been occupied therein.`"

All this then being duly considered by those called Quakers,
it hath restrained them from the use of those ceremonies.
For the man who through grace is become truly spiritual,
hath no need of ceremonies or outward means to depend upon,
but finds himself excited to rely on the inward divine grace,
and to depend upon God alone, walking continually in reverential watchfulness before him,
and so keeping to the immediate teachings of Christ in his heart,
he approaches with boldness to the throne of grace, and with a full assurance of faith,
becomes a partaker of salvation.

But I leave this matter, to say something also concerning the Quakers`' way of worship.
It is usual among them when they meet together in their religious assemblies,
to spend some time in a devout silence and retiredness of mind,
inwardly praying with pure breathings to God, which they generally call,
waiting upon the Lord:
and if under this spiritual exercise any one feels himself stirred
up of God to speak something by way of doctrine or exhortation,
he doth so, and sometimes more than one, but orderly, one after another.
And that this was usual in the primitive apostolical church,
appears from what Paul saith, "`If any thing be revealed to another that sits by,
let the first hold his peace:
for ye may all prophesy one by one.`" And what prophesying signifies under the new covenant,
the apostle himself explains with these words, "`He that prophesies,
edifies the church.`" Yet let none think this liberty of speaking to be so unlimited,
that every body that can say something, may freely do so in the congregation:
for he that will speak there, must also by all means be of a good, and honest,
and holy life, and sound in doctrine;
and if in process of time he finds in himself a concern
from the Lord to travel in the ministry,
and desires a certificate of his soundness in doctrine and orderly life,
he may have it from the congregation where he resides.
And certainly a preacher himself ought to have experience of the work of sanctification,
before he is qualified to instruct others in the way thereto:
for mere brain-knowledge cannot do that effectually.
Sometimes in their meetings there is a public prayer before preaching;
and preaching is generally concluded with a prayer.

Now preaching among them is not confined to the male sex as among others:
for they believe that women whom the Lord hath gifted for gospel-ministry,
may exercise their gifts among them to edification: for who will presume to say to him.
What dost thou?
To him namely, who, by his apostle, hath said,
"`Quench not the Spirit.`" They are not ignorant that the same apostle said to the Corinthians,
"`Let your women keep silence in the churches.`" Now not to insist on the word your,
which seems to carry an emphasis along with it,
as being chiefly applicable to those Corinthian women,
yet by what follows it appears plainly, that it regards ignorant women,
since it is said there, "`If they will learn any thing,`" that is,
if they will be further instructed concerning some points of doctrine,
"`Let them ask their husbands at home.`" Whereby it
appears that this saying hath relation to such women,
who either from indiscretion or curiosity,
or out of a desire to be looked upon as such that know also to say something,
proposed questions to the church, and thereby caused more confusion than edification:
"`For it is indeed a shame for +++[+++such]
women to speak in the church;`" and the apostle`'s precept is,
"`Let all things be done decently and in order.`" Moreover, it ought to be considered also,
that these words,
"`Let your women keep silence,`" have a tendency also
to the subjection which women owe to their husbands,
because it is said there also,
that women are commanded "`To be under obedience,`" This the
apostle explains further in one of his epistles to Timothy,
where he saith, "`Let the women learn in silence with all subjection:
but I suffer not a woman to teach nor usurp authority over the man.`" Now that
the apostle doth not absolutely forbid women speaking to edification in the church,
appears from his own words, when he saith, "`Every woman that prays, or prophesies,
with her head uncovered,
dishonors her head:`" for here he gives to women a
prescript how to behave themselves when they prophesy;
and what he means by prophesying, he himself declares in the same epistle,
as hath been hinted already, where he saith,
"`He that prophesies speak unto men to edification, and exhortation, and comfort;
and he that prophesies edifies the church.`" And pray what
is this but that which we now a-days call preaching?
For though prophesying under the old covenant seems
chiefly to signify a prediction of what is to come,
yet it is credible that the ancient prophets were also preachers;
and according to the New Testament language,
it is evident that prophesying is chiefly preaching.
Hence we may easily understand what kind of virgins the four daughters of Philip were,
which did prophesy, and what kind of servant of the church Phoebe was, and Tryphena,
and Tryphosa, who labored in the Lord, and Persis, who labored much in the Lord,
which is considerably more than what is said of that Mary,
who bestowed much labor on the apostles.
How significantly doth the apostle call Priscilla and Aquila, his helpers in Christ Jesus.
And what he means by his helpers in that sense,
we may see Phil. 4:3. where he speaks of women which labored with him in the gospel.
All this then being duly considered, the Quakers, so called,
think it unlawful to forbid such women to preach whom the Lord hath gifted,
and who are of a godly life and conversation;
since it appears sufficiently that in the primitive
church they were not debarred from that service.
And as in those days, so in ours, it hath evidently appeared,
that some pious women have had a very excellent gift to the edification of the church.
All which tends to the glory of God, who is no respecter of persons,
and is pleased to make use of weak instruments to show forth his praise.

As to singing the words of David,
since they do not suit the state and condition of mixed assemblies,
they disuse the customary formal way of singing in the churches,
which has neither precept nor precedent in the New Testament.

Concerning the resurrection, their belief is orthodox,
and agreeable with the testimonies of the holy Scriptures:
but because they judge it to be very improper to say that we shall
rise again with the same numerical bodies we now have,
their opposers have falsely accused them, as such who deny the resurrection;
though they fully believe this saying of the apostle,
"`If in this life only we have hope in Christ,
we are of all men most miserable.`" And as to the
qualities of the bodies wherewith we shall arise,
he saith, "`It is sown a natural body,
it is raised a spiritual body:`" "`For,`" saith the same apostle,
"`our conversation is in heaven, from whence we look for the Savior,
the Lord Jesus Christ, who shall change our vile body,
that it may be fashioned like unto his glorious body,
according to the working whereby he is able to subdue all things
unto himself,`" And therefore they have counted it more safe,
not to determine with what kind of bodies we shall be raised,
provided we have a firm belief that there is to be a resurrection of the dead:
for from such a determination many difficulties may arise, which otherwise are avoided;
and therefore they have also said to their antagonists,
'`Christ`'s resurrection is indeed an argument for our resurrection;
but would it be valid from thence thus to argue: because Christ`'s body,
which was without sin, and was not corrupted in the grave,
was raised the same it was buried; therefore our bodies, which admit of corruption,
must also be raised the same they are buried?
Nay, by insisting stiffly on this point, we fall into many difficulties:
who will venture to say, that when people die,
and are buried about the age of ninety years,
their bodies in the resurrection shall be the same decrepit bodies they were when buried;
and that unborn children dying, shall be raised with such small bodies as they had then?
To shun therefore such kind of absurdities,
they think it better not to suffer human wit to expatiate too far,
since the apostle saith, "`Mind not high things;`" and advises every man,
"`not to think of himself more highly than he ought to think.`"

Now as to church government, both for looking to the orderly conversation of the members,
and for taking care of the poor, and of indigent widows and orphans,
and also for making inquiry into marriages solemnized among them,
they have particular meetings, either weekly, or every two weeks, or monthly,
according to the greatness of the churches.
They have also quarterly meetings in every county,
where matters are brought that cannot well be adjusted in the particular meetings.
To these meetings come not only the ministers and elders, but also other members,
that are known to be of sober conversation; and what is agreed upon there,
is entered into a book belonging to the meeting.
Besides these meetings a general annual assembly is kept at London in the Whitsun week,
so called;
not for any superstitious observation the Quakers
have for that more than at any other time,
but because that season of year best suits the general accommodation.

To this yearly meeting, which sometimes lasts four, or five, or more days,
are admitted such as are sent from all churches of that society in the world,
to give an account of the state of the particular churches;
which from some places is done only by writing;
and from that meeting is sent a general epistle to all the churches,
which commonly is printed;
and sometimes particular epistles are sent also to the respective churches.
By which it may be known every year, in what condition the churches are:
and in the said epistle generally is recommended a godly life and conversation,
and due care about the education of children.
If it happens that the poor any where are in want,
then that is supplied by others who have in store,
or sometimes by an extraordinary collection.

As to the denomination by which they are distinguished from other religious societies,
it is, as is well known, Quakers; but since that name was given them in scorn,
as hath been said in due place,
they do not assume it any further than for distinction-sake from others;
but the name whereby they call one another is that of friends.
And herein they have the example of primitive Christians,
as may be seen Acts 27:3. where it is said,
that Julius the centurion courteously intreated Paul,
and gave him liberty to go unto the friends, (for so the Greek hath it,)^
// lint-disable invalid-characters
footnote:[Ηρὸς τοὺς φίλους and ἐι φ`'λοι, which is not his friends, or our friends,
as it is rendered, but the friends.]
to refresh himself, and 3 Epist.
John 14. we read, '`The friends salute thee; and greet the friends by name.`'
Now this name of Friends is so common among the Quakers in England,
that others also know them, and sometimes call them by that name.

[.small-break]
'''

It was, as I find, in the year 1705, that Anna, the late wife of Thomas Camm,
deceased in a great age;
and having already made mention of her by the name of Anne Audland,
I will say something more of her before I describe her exit.
She was daughter of Richard New-by, in the parish of Kendal in Westmoreland,
being born in the year 1627, and well educated; and being come to maturity,
she conversed much with the most religious people of that time.
About the year 1650, she was married to John Audland, and in the beginning of 1652,
they both were by the ministry of G. Fox, convinced of that truth he preached;
and in the next year they began to preach that doctrine to others,
for which in the following year she was committed to prison
in the town of Aukland in the county of Durham,
where she had opportunity to speak to the people through the window;
which she did so pathetically, that several were affected with her testimony;
and after being released, she travelled up and down the country, and had good service;
but not long after,
she was again committed to prison on an accusation of having spoken blasphemy,
for which she was tried at Banbury in Oxfordshire;
the indictment drawn up against her containing that she had said, God did not live:
whereas that which she said was,
that true words might be a He in the mouth of some that spoke them,
alleging for truth the saying of the prophet Jeremiah
5:2. "`Though they say the Lord liveth,
surely they swear falsely.`" The judge before whom she appeared,
behaved himself moderately,
and observing how wisely she answered to his questions with a modest boldness,
proposed the matter to the jury thus;
'`That she acknowledged the Lord her God and Redeemer to live,
and that there were gods of the heathen that were dead gods.`'
Some of the justices upon the bench, who sought her destruction,
perceiving they should not obtain their end,
for it had been divulged that she should be burnt, went off to influence the jury,
and bias them; which had this effect, that they brought her in guilty of misdemeanor:
which made one present say, it was illegal to indict her for one fact,
and to bring her in guilty of another;
since they ought to have found her either guilty or not
guilty upon the matter of fact charged in the indictment.
The judge, though he had carried himself discreetly,
had a mind however somewhat to please the justices that were her enemies;
and therefore at her refusal to give bond for her good behavior,
she was sent to prison again; though he was heard to say,
that she ought to have been discharged.
And the prison whither she was sent was a nasty place, several steps under ground;
on the side whereof was a common sewer, which sometimes stunk very much,
and frogs and toads crawled in the room.
Here she was kept about eight months, but showed herself content,
being persuaded that it was for the Lord`'s sake she thus suffered.

Her husband, John Audland, died, as hath been said before,
about the beginning of the year 1664, and two years after she was married to Thomas Camm,
a minister also of the gospel.
She lived very retiredly, and spent much time in solitariness,
and was almost daily exercised in reading the holy Scriptures, and other edifying books.
Her husband suffered imprisonment three years, at Kendal, and about six years,
at Appleby; insomuch that she came to be well acquainted with adversities:
but by all these she was the more spurred on to advance in true piety;
and was a very remarkable teacher in the church,
having an extraordinary gift to declare the truth.
And yet she was very modest and humble, insomuch that how full soever she was of matter,
she rarely appeared to preach in large meetings,
where she knew there were men qualified for that service;
and she was grieved when she perceived any of her sex to be too forward on such occasions;
and therefore she advised them to be cautious,
though she did not omit to encourage the good in all,
and endeavored not to quench the Spirit in any.
Thus she continued in a virtuous life to the end of her days.
At Bristol she once fell so sick, that it was thought she was nigh death;
and then she exhorted those that stood by, to prize their time,
and to prepare for their latter end, as God said she, hath inclined me to do,
so that I enjoy unspeakable peace here,
with full assurance of eternal rest and felicity in the world to come.

But she recovered from this sickness; and when her dying hour came,
which was in her dwelling place near Kendal, she was not less prepared, but said,
'`I bless the Lord I am prepared for my change.
I am full of assurance of eternal salvation, and a crown of glory,
through my dear Lord and Savior Jesus Christ.`'
Many other excellent sayings she uttered during the time of her sickness;
and when she drew near her end, some of her friends asking her, whether she knew them,
'`Yes,`' said she, '`I know you every one.
I have my understanding as clear as ever: for how should it be otherwise,
since my peace is made with God through the Lord Jesus Christ.
I have no disturbance in mind,
therefore is my understanding and judgment so good and clear;
but to lie under affliction of body and mind,
to feel pinching pangs of body even to death, and to want peace with God;
O that would be intolerable to bear!`' She advised her husband
to quit himself of the cumber of the things of this world,
after her death, that he might with the more freedom attend the ministry of the gospel,
and, said she, '`Warn all, but especially the rich, to keep low,
and not to be high-minded: for humility and holiness is the badge of our profession.`'
A little before her departure, some fainting fits taking her, she revived again,
and said, '`I was glad, thinking I was going to my eternal rest, without disturbance.
I have both a sight and earnest of eternal rest with God in the world to come.`'
A little after she said, '`Methinks I grow weak and cold.
My hands and feet are grown very cold, yet my heart is very strong.
I must meet with sharper pangs than I have yet felt--This
pain is hard to flesh and blood,
but must be endured a little time; ease and eternal rest is at hand;
I am glad I see death so near me.`'
A little after, seeing her friends weep, she said, '`Be not concerned, for all is well:
I have only death to encounter, and the sting of it is wholly taken away:
the grave hath no victory, and my soul is ascending above all sorrow and pains.
So let me go freely to my heavenly mansion, disturb me not in my passage.
My friends, go to the meeting; let me not hinder the Lord`'s business,
but let it be the chief, and by you all done faithfully,
that at the end ye may receive your reward; for mine is sure.
I have not been negligent, my day`'s work is done.`'
Feeling afterwards her pains increasing,
she prayed the Lord to help her through the agony of death; and a little after she said,
'`O my God, O my God, thou hast not forsaken me, blessed be thy name forever.
O my blessed Savior, that suffered for me and all mankind,
great pains in thy holy body upon the cross,
remember me thy poor handmaid in this my great bodily affliction.
My trust is in thee, my hope is only in thee, my dear Lord.
O come, come dear Lord Jesus, come quickly, receive my soul, to thee I yield it up,
help me now in my bitter pangs.`'
Then her husband prayed to God, that he would be pleased to make her passage easy.
And she had no more such pangs, but drew her breath shorter by degrees,
and said little more, but that it was good to leave all to the Lord.
And so she slept in the Lord the 30th of November, 1705, in the 79th year of her age.
Thus Anne Camm departed this life,
and her husband said afterwards that he counted it
a great blessing to have had her to wife;
for she was indeed a very excellent woman,
and therefore I have described her latter end thus circumstantially.

Having now related what hath come to my knowledge, that I thought remarkable,
and of singular moment in respect of the rise and profess of the people called Quakers,
I think what I have written may suffice,
and answer the contents of the title of this history;
and therefore I will add only a few occurrences, and then come to a conclusion.

Many years ago,
even in the time of King James I. endeavors were
used to unite England and Scotland into one kingdom,
but all in vain: king William III.
also tried what could be done in this case,
but his life did not permit him to bring the work to perfection.
Yet at length the matter was agreed and settled about the beginning of the year 1707,
in the reign of Queen Anne,
it being concluded that these two kingdoms henceforth should be united into one,
and called Great Britain.
In the forepart of the year 1708,
Scotland was threatened with an invasion by the pretended prince of Wales;
but he failed in the attempt, and his design came to nought.
Now since the union of the said kingdom with that of England was accomplished,
and the succession of the crown in the Protestant line established by law,
the queen on that account was congratulated by a multitude of addresses of her subjects;
and the Quakers, so called,
judged themselves obliged also to testify their affection to that princess,
as they did by the following address:

[.embedded-content-document.address]
--

[.letter-heading]
To Anne, Queen of Great Britain, etc.

The grateful and humble Address of the People commonly called Quakers,
from their Yearly Meeting in London, this 28th day of the third month, called May, 1708.

We having good cause to commemorate the manifold mercies
of God vouchsafed to this united kingdom of Great Britain,
believe it our duty to make our humble acknowledgments, first to the Divine Majesty,
and next to the queen, for the liberty we enjoy under her kind and favorable government,
with hearty desires and prayers to Almighty God,
(who hath hitherto disappointed the mischievous and wicked designs of her enemies,
both foreign and domestic,) that he will so effectually replenish the queen`'s heart,
together with those of her great council, with his divine wisdom, that righteousness,
justice and moderation, which are the ornaments of the queen`'s reign,
and which exalt a nation, may be increased and promoted.

And we take this opportunity to give the queen the renewed assurance
of our hearty affection to the present established government,
and that we will as a people in our respective stations,
according to our peaceable principles, by the grace of God,
approve ourselves in all fidelity the queen`'s faithful and obedient subjects,
and as such conclude with fervent prayers to the Lord of Hosts, that after a prosperous,
safe and long reign in this life, thou, O queen,
mayest be blessed with an eternal crown of glory.

--

This address was signed in the name of the meeting by fourteen members thereof,
who also were ordered to present it;
but it being understood that the queen seemed willing to be attended with it in private,
only seven, among whom were G. Whitehead and Thomas Lower, went in with it,
and were introduced by the principal secretary of state Boyle;
and G. Whitehead presenting it, said, '`We heartily wish the queen health and happiness:
we are come to present an address from our yearly meeting,
which we could have desired might have been more early and seasonably timed,
but could not, because our said meeting was but the last week;
and therefore now hope the queen will favorably accept our address.`'
Then G. Whitehead delivering it, the queen said,
'`Pray read it:`' whereupon he took and read it, and the queen answered:

[quote]
____
I thank you very kindly for your address, and I assure you of my protection;
you may depend upon it.
____

[.offset]
To which G. Whitehead replied,

[qutoe]
____
We thankfully acknowledge,
that God by his power and special providence,
hath preserved and defended the queen against the evil designs of her enemies,
having made the queen an eminent instrument for the
good of this nation and realm of Great Britain,
in maintaining the toleration,
the liberty we enjoy in respect to our consciences against persecution.
Which liberty being grounded upon this reason in the late king`'s reign,
for the uniting the Protestant subjects in interest and affection,
the union of Great Britain now settled tends to the strength and safety thereof;
for in union is the strength and stability of a nation, or kingdom; and without union,
no nation or people can be safe; but are weak and unstable.
The succession of the crown being settled and established in the Protestant line,
must needs be very acceptable to all true Protestant subjects.

And now, O queen, that the Lord may preserve and defend thee for the future,
the remainder of thy days,
and support thee under all thy great care and concern for the safety
and good of this nation and kingdom of Great Britain,
and that the Lord may bless and preserve thee to the end, is our sincere desire.
____

To this the queen returned, '`I thank you for your speech, and for your address;
and ye may be assured I will take care to protect you.`'

And G. Whitehead replied,
'`The Lord bless and prosper the queen and all her good intentions.`'
And thereupon he and his friends withdrew.

The most remarkable occurrences the Quakers in England now met with,
were that they enjoying the liberty to perform their religious worship publicly,
without disturbance,
were afterward encountered by the writings of their enemies from ignorance or envy,
and represented as maintainers of heterodox sentiments; but they not failing of answers,
the eyes of many were opened, and some came over to them.
And though sometimes those of the public church had the success
to draw over one that was born and educated among the Quakers,
but inclined to more liberty, and to be esteemed by the world,
yet there have been others of the episcopal church,
who not from any earthly consideration, but merely by a convincement of their mind,
have entered into society with the Quakers;
not fearing to make public profession of their religion,
as may appear by two letters which I will insert here; the one of Samuel Crisp,
a clergyman of the episcopal church,
who gave the following account of his change to one of his near relations:

[.embedded-content-document.letter]
--

[.salutation]
My dear Friend,

I received a letter from thee, the week before last, which was sent by thy uncle Bolton:
there were a great many kind expressions in it, and in thy sister Clopton`'s likewise:
I acknowledge myself much obliged to you both, and to the whole family,
for many repeated kindnesses, and if my school had not engrossed so much of my time,
I would have taken opportunity to answer my dear friend`'s letter now,
and upon that account my delay will be more excusable.

The news thou hast heard of my late change is really true, I cannot conceal it,
for it is what I glory in;
neither was it any prospect of temporal advantage that induced me to it,
but a sincere love to the truth, and pure regard to my own soul:
neither can I be sufficiently thankful to God,
that he hath let me live to this glorious day,
and not cut me off in the midst of my sins and provocations against him;
he is long suffering to US-ward, not willing that any should perish,
but that all should come to repentance:
he hath brought me off from the forms and shadows of religion,
and let me see in a more illustrious manner what is the life and substance of it,
as he found me in some degree faithful to that measure
of light and knowledge he had bestowed on me,
whilst I was in the communion of the church of England; therefore he was pleased of late,
as I humbly waited upon him to make known to me greater
and deeper mysteries of his kingdom;
and I can truly say, that I find by daily experience,
as I keep low and retired into that pure gift which he hath planted within me,
things are every day more and more cleared up to me,
and the truth shines and prevails greatly over the kingdom of darkness;
and if I should now turn my back upon such manifestations as these,
and entangle myself again with the yoke of bondage,
surely I should grieve the Holy Spirit,
so that he might justly withdraw his kind operations,
and never return more to assist and comfort me; for God is not mocked;
religion is a very serious and weighty thing;
repentance and salvation are not to be trifled with, nor is turning to God,
to be put off till our own time, leisure or conveniency,
but we must love and cherish the least appearance of Christ,
not slighting or despising the day of small things,
but embrace the first opportunity of following Christ in any of his commands:
when he speaks, there is such force and authority in it, that we cannot stand to cavil,
dispute, or ask questions;
for unless we will be so obstinate as to shut our eyes against the sun,
we must needs confess to the truth of his doctrine, and presently strike in with it;
and therefore when for several weeks I had lived more privately and retiredly in London,
than was usual, fasting twice or thrice in a week, or sometimes more,
spending my time in reading the Scriptures, and in prayer to God,
this was a good preparation of my mind,
to receive the truth which he was then about to make known to me.
I lamented the errors of my past life,
and was desirous to attain a more excellent degree of holiness
than I had discovered in the church of England.
In this religious retirement God knew the breathings of my soul, how sincere I was,
and resigned to him when alone.
I wanted him to set me free, and to speak peace and comfort to my soul,
which was grieved and wearied with the burden of my sin:
for though I had strictly conformed myself to the
orders and ceremonies of the church of England,
and had kept myself from running into any great or scandalous enormities,
the fear of the Almighty preserving me,
yet still I had not that rest and satisfaction in myself which I desired,
and greatly longed for.
I found when I had examined my state and condition to God-ward,
that things were not right with me.

As for a sober and plausible conversation in the eye of the world,
I knew that was a very easy attainment.
A good natural temper, with the advantage of a liberal education,
will quickly furnish a man with abilities for that,
so that he shall be looked upon as a saint, and very spiritual;
when perhaps in chains of darkness, in the gall of bitterness,
and in the very bond of iniquity.
If this sort of righteousness would have done,
perhaps I might make as fair pretensions that way as some others; but alas,
I quickly saw the emptiness and unsatisfactoriness of those things:
this is a covering that will not protect or hide us from the wrath of the Almighty,
when he comes to judgment.
It is not a man`'s natural temper, or his education, that makes him a good Christian;
this is not the righteousness which the gospel calls for,
nor is this the truth in the inward parts which God requires.
The heart and affections must be cleansed and purified
before we can be acceptable to God;
therefore it was death to me to think of taking up my rest in a formal pretense of holiness,
wherein yet I saw to my grief, abundance of people wrapped themselves,
slept securely and quietly; dreaming of the felicity of paradise,
as if heaven were now their own,
and they needed not trouble themselves any more about religion.
I could not entertain so dangerous an opinion as this,
for then I should be tempted to take up my rest by the way,
whilst I was traveling towards the promised land.
I think I made a little progress in a holy life,
and through God`'s assistance I weakened some of my spiritual enemies,
whilst I lived in the communion of the national church.
I thank my God, I can truly say, whilst I used those prayers,
I did it with zeal and sincerity, in his fear and dread;
but still I ceased not my earnest supplication to him in private,
that he would show me something more excellent;
that I might get a complete victory over all my lusts and passions,
and might perfect righteousness before him;
for I found a great many sins and weaknesses daily attending me:
and though I made frequent resolutions to forsake those sins,
yet still the temptation was too strong for me;
so that often I had cause to complain with the apostle in the bitterness of my soul,
"`O wretched man that I am,
who shall deliver me from the body of this death?`" Who shall set me free,
and give me strength to triumph over sin, the world, and the devil:
that I may in everything please God, and there may not be the least thought, word,
or motion, gesture or action, but what is exactly agreeable to his most holy will,
as if I saw him standing before me,
and as if I were to be judged by him for the thought of my heart next moment?
O divine life!
O seraphic soul!
O that I could always stand here; for here is no reflection, no sorrow, no repentance:
but at God`'s right hand there is perfect peace, and a river of unspeakable joy.
O that we might imitate the life of Jesus,
and be thoroughly furnished unto every good word and work.
This was the frequent breathing of my soul to God when I was in the country,
but more especially after I had left my new preferment of a chaplain,
and took private lodgings in London.
In this retirement I hope I may say without boasting,
that I was very devout and religious,
and I found great comfort and refreshment in it from the Lord,
who let me see the beauty of holiness; and the sweetness that arises from a humbled,
mortified life, was then very pleasant to my taste,
and I rejoiced in it more than in all the delights and pleasures of the world.

And now it pleased God to show me,
that if I would indeed live strictly and holily as becomes the gospel,
then I must leave the communion of the church of England;
but knew not yet which way to determine myself, nor to what body of men I should join,
who were more orthodox and more regular in their lives.
As for the Quakers, so called, I was so great a stranger to them,
that I had never read any of their books,
nor do I remember that ever I conversed with any
one man of that communion in my whole life.
I think there was one in Foxly, whilst I was curate there; but I never saw the man,
though I went several times to his house on purpose to talk with him,
and to bring him off from his mad and wild enthusiasm,
as I then ignorantly thought it to be.
As for that way, I knew it was everywhere spoken against.
He that had a mind to appear more witty and ingenious than the rest,
would choose this for the subject of his profane jests and drollery;
with this he makes sport, and diverts the company;
for a Quaker is but another name for a fool or a mad man,
and was scarce ever mentioned but with scorn and contempt.
as for drollery, I confess I was never any great friend to it;
but indeed if all was true that was laid to the Quakers`' charge,
I thought they were some of the worst people that ever appeared in the world,
and wondered with what face they could call themselves Christians;
since I was told they denied the fundamental articles of the holy faith,
to which I ever bore the highest veneration and esteem;
and notwithstanding I had always lived at the greatest distance from that people,
and was very zealous in the worship of the church of England,
and upon all occasions would speak very honorably of it,
moreover was content to suffer some few inconveniencies upon that account,
as thou very well knows; yet my father still looked upon me as inclining to the Quakers;
and some years ago signified to a friend, he was afraid I would become an enthusiast;
and whilst I was at Bungan school,
he sent me two books to read that were written against the Quakers,
one of which was John Faldo`'s: who had been sufficiently exposed for it by William Penn.

Whilst I lived in London in that private retired manner,
I was just now speaking of walking very humbly in the sight of God,
and having opportunity to reflect upon my past life,
as I had occasion to be one day at a bookseller`'s shop,
I happened to cast my eye on Barclay`'s works: and having heard in the country,
that he was a man of great account amongst the Quakers,
I had a mind to see what their principles were,
and what defense they could make for themselves; for sure, thought I,
these people are not so silly and ridiculous; nor maintainers of such horrid opinions,
as the author of the Snake, and some others would make us believe.
I took Barclay home with me, and I read him through in a week`'s time,
save a little treatise at the end, which I found to be very philosophical, I omitted;
but however,
I soon read enough to convince me of my own blindness and ignorance in the things of God;
there I found a light to break in upon my mind,
which did mightily refresh and comfort me, in that poor, low, and humbled state,
in which I then was; for indeed I was then, and had been for a considerable time before,
very hungry and thirsty after righteousness,
and therefore I received the truth with all readiness of mind:
it was like balm to my soul, and as showers of rain to the thirsty earth,
which is parched with heat and drought.
This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the Scriptures so clearly to me, that without standing to cavil, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God;
and weeping for joy that I had found so great a treasure,
I often thanked him with tears in my eyes for so kind a visitation of his love,
that he was graciously pleased to look toward me when my soul cried after him; so,
though before I was in great doubt and trouble of mind,
not knowing which way to determine myself,
yet now the sun breaking out so powerfully upon me, the clouds were scattered:
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.

So I immediately left the communion of the church of England,
and went to Gracechurch-street meeting.
After I had read Barclay, I read some other books of that kind,
among which was an excellent piece, though in a small volume, called No Cross No Crown.
Thus I continued reading and frequenting meetings for several weeks together,
but did not let any one soul know what I was about.
The first man I conversed with was George Whitehead,
and this was several weeks after I began to read Barclay, and frequent their meetings.
By him I was introduced into more acquaintance, and still the further I went,
the more I liked their plainness, and the decency and simplicity of their conversation.
They do not use the ceremonies and salutations of the church of England,
but shake hands freely, and converse together as brothers and sisters,
that are sprung of the same royal seed, and made kings and priests unto God.
O, the love, the sweetness and tenderness, and affection,
I have seen among this people! "`By this,`" says Christ,
'`shall all men know that ye are my disciples,
if ye have love one to another.`" "`Put on therefore,`" says the apostle,
"`(as the elect of God, holy and beloved,) bowels of mercy, kindness, humbleness of mind,
meekness, long-suffering.`"

Thus, my dear friend, I have given thee an account of my proceeding on this affair.
As to my bodily state, if thou desires to know what it is,
I may acquaint thee that I have my health, as well as ever,
and I bless God I have food and raiment sufficient for me,
so that I want no outward thing;
and I have the necessities and convenience of life liberally:
let us not burden ourselves with taking care for the vanities and superfluities of it;
let us possess our vessels in sanctification and honor;
and as we bring our minds into perfect subjection to the whole will of God,
so let us bring our body to the most simple and natural way of living;
being content with the fewest things, never studying to gratify our wanton "`appetites,
nor to follow the customs and humours of men;
but how we may so contract our earthly cares and pleasures,
that we may bring most glory to God, most health and peace to our own souls,
and do most service to the truth; and if this be our aim,
certainly a very small portion of the things of this world will suffice us,
seeing we are Christians;
we should therefore earnestly pursue those things which bring us nearest to God,
and which are most perfective of human nature: for what is more than a competency,
seems to be a burden to a generous philosophical soul,
which would breathe in a pure vehicle,
that so it may have a quick sense and relish of all blessings,
both of the superior and inferior worlds.

Thou knows, my dear friend, that religion is a very serious thing,
and repentance is a great work,
and one precious immortal soul is of more worth than ten thousand perishing worlds,
with all their pomp and glory; therefore let us take courage,
and be valiant for the truth upon the earth,
let us not content ourselves with a name and profession of godliness,
let us come to the life and power of it, let us not despond of getting the victory.
We have a little strength for God: let us be faithful to him,
and he will give us more strength,
so that we shall see the enemy of our peace fall before us,
and nothing shall be impossible unto us: I say, my friend,
let us be faithful to that measure of light and knowledge which God has given us,
to be profited and edified by it in a spiritual life,
and as God sees we are diligent and faithful to work with the strength we have,
he will more and more enlighten us,
so that we shall see to the end of those forms and
shadows of religion wherein we had formerly lived;
but if he sees we are about to take up our rest in those shadows,
that we grow cold and indifferent in the pursuit of holiness,
running out into notions and speculations; and have more mind to dispute,
and to make a show of learning and subtlety, than to lead a holy and devout life,
then it is just with God to leave us in a carnal and polluted state;
to continue yet but in the outward court,
where we may please ourselves with beholding the beauty and ornaments of a worldly sanctuary,
and never witness the veil being taken away,
and that we are brought by the blood of Jesus, into the holiest of all,
where alone there is true peace with God, and rest to the weary soul.
I could say much upon this head, if time or leisure would give leave.

As for a particular answer to thy letter, I have not time now to give it;
and for the present let this general answer suffice:
and if thou wilt consider things in their pure abstracted nature,
and not suffer the prejudice of education to sway thee,
but in fear and humility wilt search out the truth for thyself,
thou wilt find that there needs no other answer to
thy letter than what I have already given;
for by waiting upon God, and diligently seeking him,
thou wilt find an answer to it in thy own bosom, and this will be much more full, clear,
and satisfactory than I, or any other man living can pretend to give thee,
or any other friend who hath lovingly written to me; for whom I desire,
with all the sincere-hearted in the church of England,
that they may come to witness the Almighty power of God,
to save and redeem them from every yoke;
and that they may see clearly to the end of those things which are abolished,
and come to the enjoyment of spiritual and heavenly things themselves,
is the daily prayer and deep travail of my soul, God knows.
Till I can be more particular, if thou please thou mayest communicate this to them,
and let them know that I am well, and thank them for their kind letters.
Let us remember to pray for one another with all fervency,
that we may stand perfect in the whole will of God, Amen, saith my soul.
I am thy most affectionate friend and servant in Jesus,

[.signed-section-signature]
Samuel Crisp.

--

The following letter, or account of one Evan Jevans, is also remarkable.

[.embedded-content-document.letter]
--

Since it hath pleased the divine goodness to endue me with reason,
I heartily thank his most excellent Majesty:
that it has been the further product of his good will to
give me life and being in that part of the world,
where I have had the freedom to use it; especially in the choice of my persuasion,
and way of returning my acknowledgment to him.
I wish that all, who make any pretensions to religion,
would make use of this noble faculty with subjection to the divine
will to determine their choice in this grand affair;
and not let the religion of their education be that of their judgment.
If people were thus truly wise unto their own salvation,
and did not too lazily resign themselves to the conduct of their guides,
thereby regarding more their ease than safety,
they would not only be the better able to give a reason of the hope that is in them,
but they would show more warmth in their devotion, more charity in their religion,
and more piety in their conversation than at present they do.

When I was visited some time ago by the chastising hand of the Lord,
for sin and my disobedience to his holy will, I labored under great affliction of mind,
and anguish of spirit;
and though I was constant above many in my attendance on the public prayers of the church,
strict in my observation of its ceremonies,
and exceeding frequent in the use of private devotion, yet my burden increased,
and I waxed worse.

In this wretched and doleful condition I was, when at a relation`'s house,
who had providentially returned from Pennsylvania to his native country,
I lighted upon R. Barclay`'s Apology for the Quakers;
by the reading whereof I was so well persuaded of their principles,
and by turning my mind inward to the divine gift,
(according to their doctrine,)`" it gave me victory, in a great measure,
over our common enemy, banished away my disorderly imaginations,
and restored me to my former regularity;
I received such satisfaction and comfort to my distressed soul,
that thereupon I left the church of England, and joined myself in society with them;
and I am the more confirmed in my change,
especially where it respects the worship of our Creator;
because it is not only the most agreeable to the Scriptures of Truth,
but heaven has given us assurance of its approbation thereof, it having been at times,
to my own experience, most powerfully attended with the presence of the Most High.

I hope none will begrudge me this mercy, because I received it not by their ministry;
if they do, I have cause to suspect their charity is not of a Christian latitude,
since our blessed Redeemer approved not of that narrowness
in his disciples in somewhat a like case.

But here to obviate the objection some may make to my change,
because of the distress I lay under, and the discomposure I was subject to at times,
I would have it remarked, that I read the said Apology beyond my expectation,
with more sedateness than usual, and a more quiet composure of mind:
so that with the influence of the Almighty, or Providence, or both,
I had also the benefit of that distinguishing faculty of man in the change of my opinion.
O that I may never forget the Lord`'s mercy to my soul,
who had compassion on me when I wallowed in my blood, and who said to the dry bones,
Live.
O that all such as are visited by the chastising
hand of their Maker would seriously lay it to heart,
and consider their own welfare and salvation; I could wish with all my heart,
that such who labor under this anxiety of mind,
would take encouragement to hope in the Lord`'s mercy through their blessed Redeemer,
by his kindness and long forbearance with me.
I am a living monument of it now; and I hope I shall be so, while he affords me a being;
here.
If these lines should come to the hands of any that
are afflicted and distressed as I was,
I have an effectual remedy, through mercy, to prescribe unto them.
Turn your minds inward to the grace of God in your own hearts,
refrain from your own imaginations, be still,
and quietly resign yourselves to his holy will, so you shall find health to your souls,
refreshment to your spirits, and the sweet consolation of the Lord in your own bosoms;
you shall find your mourning turned to gladness, and your heaviness to joy;
this has been my experience of the goodness of the Holy One of Israel,
who abhors sin and iniquity; therefore I recommend it to you,
and I think this is no mistrusting of the cause,
for they are the sick and wounded in spirit, not the whole, that need the physician.

As for renouncing the covenant, which I and every Christian ought to be under,
of forsaking the devil and all his works,
I am so far from entertaining one thought of neglecting that duty,
that I think myself wholly obliged to observe it: and if I should affirm,
that through the grace of God, and his assistance,
(for otherwise I am satisfied I cannot do it,) the observation of it is possible,
I can find no reason why it should be false doctrine in a Quaker,
more than in a churchman.

As for deserting that church and ministry which the
Son of God came down from heaven to establish,
I am not conscious to myself thereof; for I say, Christ himself,
is the head of our church, and, by his Spirit and grace, the ordainer of our ministry.

And as to the last query, my ingenious acquaintance is pleased to propose,
I do let him know, that my former despair and forlorn condition has been,
since my adhering to that reproached people,
changed into a sweet enjoyment of the goodness of God.
I could not conceal the Lord`'s goodness, lest he should withdraw his mercies from me.

I had no secular interest to corrupt me in this change.
It is apparent to many, I declined it; but as it was peace with God my Maker,
and mercy to my soul I wanted; so having found the pearl of great price, among them,
I parted with all to purchase it; or rather, I was restored to all, I mean,
the enjoyment of the divine goodness, and of myself, by setting a due value upon it.

--

From this account it appears,
that the writer thereof aimed at nothing in his change of religion,
but the quietness of his mind, and the salvation of his soul.

Now I am to mention, that the queen, in the year 1710, in her speech to the parliament,
having again declared that she would maintain the toleration and liberty of conscience,
was addressed by many;
wherefore the people called Quakers esteemed it their duty
to show also their grateful acknowledgment of this favor,
which they did by the following address.

[.embedded-content-document.address]
--

[.letter-heading]
To Queen ANNE, of Great Britain, etc.

The humble and thankful Address of the Queen`'s Protestant subjects,
the people called Quakers, in and about the city of London, on behalf of themselves,
and the rest of their persuasion.

When we consider the queen`'s royal regard to protect our religious liberty,
and the fresh assurance from the throne,
of her Christian resolution to maintain the indulgence
by law allowed to scrupulous consciences,
and her tender care that the same may be transmitted to
posterity in the Protestant succession in the house of Hanover,
we find ourselves concerned gratefully to acknowledge her goodness therein,
and the ready concurrence of her great council therewith:
taking this occasion to assure the queen of our duty and affection,
and peaceable behavior under her government, as is our principle,
and hath always been our practice.

And we heartily desire our fellow-subjects may lay aside all animosities,
and in a spirit of love and meekness,
endeavor to outdo each other in virtue and universal charity.

That it may graciously please Almighty God to defend and bless thee, O queen,
and guide thee by his counsel in a long and prosperous reign here,
and afterwards receive thee to glory, is the hearty prayer of thy faithful subjects.

--

To this address the Queen was pleased to answered:

[quote]
____
I thank you for your address, and ye may depend upon my protection.
____

The animosities mentioned in this address, did regard the division,
which having been a good while among the subjects,
began to increase as many thought by the change of the ministry.
But this being out of my province, I will not meddle with it.

In the year 1712, died Richard Cromwell, the son of Oliver the protector,
about the age of ninety years.
Great changes this man had seen, having himself been the supreme ruler of England,
as hath been mentioned in due place.

Although I do not intend to relate much more of any occurrences,
because I hasten towards a conclusion,
yet I think it worth the while to add the following case:

In the year 1713, in the spring, there was a suit at law,
on the act against Occasional Conformity.
It happened that one John Penry, a justice of peace of Allborough,
in the county of Suffolk, going to the parish church, understood by the way,
that no service was to be done there at that time;
but hearing that there was a Quakers`' meeting there, he went to it.
One Wall, the bailiff of the place, being informed thereof,
imagined that the said justice might not go there, because of the aforesaid act,
and therefore thinking that something might be gained by it,
got witnesses to declare that the said justice had been in the meeting;
and said afterwards in a boasting way to him, '`Now I have hooked you.`'
To which the other replied, '`I will stand to it.`'
The bailiff`" then entered his suit in the name of one that lived thereabouts by charity.
When the case was pleaded at the sessions, the judge, who was baron Salathiel Lovel,
declared the meaning of the fore mentioned act to be thus,
viz. That it did not regard any who accidentally went into a meeting of dissenters;
but that it was against those who conformed with the church,
thereby to qualify themselves for an office, without changing their religion.
But this was quite another case;
for the priest of the parish himself gave a certificate
that the said justice was a good member of the church.
From hence it appeared that the suit was mere malice; and the informers, or witnesses,
were brought to that pinch, that they durst not expect the verdict of the jury,
for fear that they should have been condemned to pay the charges,
and therefore they let the thing fall.

Being now entered into this year, I cannot omit to say,
that a peace between England and France being concluded,
and the subjects from all parts of the nation congratulating the queen with addresses,
the Quakers did not omit also to present an address; being as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To Anne, Queen of Great Britian, etc.

[.signed-section-context-open]
The humble Address of her Protestant dissenting subjects, called Quakers,
met at our annual meeting in London, the 3d day of the Fourth month, called June, 1713.

[.salutation]
May it please the Queen,

We having been sorrowfully affected at the calamity which war brought on Europe,
cannot omit to express our satisfaction and gladness for the queen`'s great care,
and Christian concern, for establishing so long desired a peace.

We are also under a dutiful sense of the queen`'s gracious government
and compassion manifested towards tender consciences at home,
as well as noble and Christian interposition, in favor of persecuted Protestants abroad.

And further crave leave to assure the queen, that we shall, as in duty bound,
approve ourselves, in all humility and faithfulness, the queen`'s obedient subjects;
and though but a small part of those that enjoy, under thy mild government,
protection in religion and civil liberties, we cannot but earnestly pray for,
and desire the quiet and safety of our country;
which evidently appears to be the queen`'s care to establish,
in having done so much for securing the protestant interest,
and maintaining perfect friendship with the house of Hanover.
That it may please Almighty God in his mercy and
goodness to assist with his wisdom the queen,
in all her councils,
and give her long to enjoy the quiet fruit of lasting peace in this life,
and in that which is to come, joy and peace everlasting,
is our hearty and fervent prayer.

--

This address, which chiefly contained an assurance of fidelity to the queen,
was accepted favorably.

The next year, being that of 1714, the queen was often ill,
and there was much division among the people:
for a bill was brought into parliament called.
An Act to prevent the growth of Schism;
and the party that prevailed was very active to get this bill passed.
And since it tended to deprive the dissenters from keeping schools,
and to allow that liberty to none but members of the episcopal church,
or at least to nobody but who had license from them, it met with great opposition,
and many reasons against it were published;
the people called Quakers offered also to the legislature
the following reasons against it:

[.embedded-content-document.address]
--

[.numbered]
I+++.+++ The church of England hath frequently declared, by several of her members,
in a clerical, as well as civil capacity,
by those who framed and espoused one or more of the bills against occasional conformity,
that she is in principle against persecution, and for preserving the toleration.

[.numbered]
II. The promoters of this bill may please to remember,
that the queen hath declared from the throne,
that she will maintain the toleration inviolable.

[.numbered]
III.
The Protestant subjects of this kingdom, who are parents of children,
are supposed to have preserved to them, by the fundamental laws of this kingdom,
the natural right of the care and direction of the education of their own children;
-which natural right this bill seems calculated to take away and destroy.

[.numbered]
IV. If the governments, which are now either heathen or Mahometan,
should take into the same policy,
the society which the queen hath incorporated for
the propagation of the gospel in foreign parts,
can have very little, if any, good effect or success.

[.numbered]
V+++.+++ May it not seem an objection and contradiction to the many princely and Christian
solicitations which the queen by ministers hath made at foreign courts,
on the behalf of Protestants, against the violent intrusions of Papists,
into their rights and just privileges`'?

[.numbered]
VI. It may be a means to oblige the carrying out
of large sums of money for foreign education.

[.numbered]
VII.
It may probably do much hurt to charitable foundations.

[.numbered]
VIII.
It seems not to be agreeable to that great law of Christ, Matt. 7:12,
"`Therefore all things whatsoever ye would that men should do to you,
do ye even so to them; for this is the law and the prophets.`"

--

But whatever was objected, the said bill at length passed,
and was confirmed with the royal assent,
which gave occasion to the Quakers to add in the conclusion
of the printed epistle of their annual assembly at London,
the following caution and exhortation: '`There seems at present to hang over us a cloud,
threatening a storm.
Let us all watch and pray,
and retire to our munition and strong hold in our
spiritual rock and foundation which standeth sure;
that our God may defend, help, and bless us as his peculiar people,
to the end of our days and time here,
and the full fruition of the heavenly kingdom and glory hereafter.`'

About Midsummer this year died Sophia,
widow and electoral princess of Brunswick Lunenburg,
on whom the succession of the crown of Great Britain was settled.
Scarce two months after her demise, queen Anne deceased,
who after having languished a long time,
at length was taken away by death on the first of August,
the self-same day that the act against the growth of schism was to have taken effect.

The same day George, prince elector of Brunswick Lunenburg,
was proclaimed king of Great Britain; who some time after repairing to England,
made his entry at London on the 20th of September.
Not long after his arrival he declared in council,
that he would maintain the toleration in favor of the Protestant dissenters.
Hereupon many addresses of congratulation were presented to him,
and on the third of October the people called Quakers also offered their address,
which was delivered by George Whitehead, and about forty of his friends,
introduced by the lord Townsend, one of the principal secretaries of state.
The prince was not only present, but many of the nobles, and others also;
and G. Whitehead presenting the address to the king, said,
'`We are come in behalf of the people called Quakers,
to present to king George our address and acknowledgment: may it be favorably accepted.`'
Being then presented, G. Whitehead said, '`One of us may read it to the king.`'
Whereupon he receiving it again, delivered it to Joseph Wyeth, who read it audibly,
being as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To George, King of Great Britain, etc.

The humble address of the people commonly called Quakers.

[.salutation]
Great Prince,

It having pleased Almighty God to deprive these kingdoms of our late gracious queen,
we do in great humility approach thy royal presence with hearts
truly thankful to divine Providence for thy safe arrival,
with the prince thy son,
and for thy happy and uninterrupted accession to the crown of these realms; which,
to the universal joy of thy faithful subjects,
hath secured to thy people the Protestant succession,
and dissipated the just apprehensions we were under,
of losing those religious and civil liberties, which were granted us by law,
in the reign of king William III.
whose memory we mention with great gratitude and affection.
We are also in duty obliged thankfully to acknowledge
thy early and gracious declaration in council,
wherein thou hast, in principle and Christian expressions,
manifested thy just sense of the state of thy people,
and which we hope will make all degrees of thy subjects easy.

And as it hath been our known principle to live peaceably under government,
so we hope it will always be our practice, through God`'s assistance,
to approve ourselves of hearty affection, thy faithful and dutiful subjects.

May the wonderful Councellor and great Preserver of men,
guide the king by his divine wisdom; protect him by his power;
give him health and length of days here, and eternal felicity hereafter.
And so bless his royal offspring,
that they may never fail to adorn the throne with
a successor endowed with piety and virtue.

--

To this address the king was pleased to give this gracious answer:

[qutoe]
____
I am well satisfied with the marks of duty you express in your address,
and you may be assured of my protection.
____

The address being read, G. Whitehead spoke to this effect:

[quote]
____
Thou art welcome to us, king George; we heartily wish thee health and happiness,
and thy son the prince also.
King William III.
was a happy instrument in putting a stop to persecution, by promoting toleration,
which being intended for the uniting the king`'s Protestant
subjects in interest and affection,
it hath so far that effect as to make them more kind to one another,
even among the differing persuasions, than they were when persecution was on foot.
We desire the king may have further knowledge of us anti our innocency;
and that to live a peaceable and quiet life in all godliness and honesty,
under the king and his government, is according to our principle and practice.
____

G+++.+++ Whitehead having thus spoken, his name was asked;
whereupon he answered,`' George Whitehead.`'
And having it upon his mind to see the prince also,
and intimating his desire to a lord who was gentleman to the prince`'s bed-chamber,
he made way to it; and thus G. Whitehead, with some of his friends, got access;
and they were introduced by one of the prince`'s gentlemen into a chamber,
where the prince met them; and then G. Whitehead spoke to him,
the substance of which was as follows:

[quote]
____
We take it as a favor that we are thus admitted to see the prince of Wales,
and truly we are very glad to see thee; having delivered our address to the king,
thy royal father, and being desirous to give thyself a visit in true love,
we very heartily wish health and happiness to you both;
and that if it should please God thou shouldest survive thy father,
and come to the throne, thou mayest enjoy tranquillity and peace, etc.

I am persuaded, that if the king thy father, and thyself,
do stand for the toleration for liberty of conscience to be kept inviolable,
God will stand by you.

May king Solomon`'s choice of wisdom be thy choice,
with holy Job`'s integrity and compassion to the oppressed;
and the state of the righteous ruler commended by king David, viz,
he that ruleth overmen must be just, ruling in the fear of God;
and he shall he as the light of the morning, when the sun riseth,
even a morning without clouds,
as the tender grass springing out of the earth by clear shining after rain.
____

[.offset]
This speech was favorably heard by the prince.

It was not long after the king`'s coming over, that Dr. Gilbert Burnet,
bishop of Salisbury, the renowned author of the History of the Reformation in England,
died.
He generally had showed himself moderate,
and had written very plainly against persecution in matters of faith,
especially in his '`Apology for the Church of England,`'
first printed in Holland in the year 1688,
and afterwards also in England, wherein among other things, he said, '`I will not deny,
but many of the dissenters were put to great hardships in many parts of England;
I cannot deny it, and I am sure I will never justify it.
And I will boldly say this, that if the church of England,
after she is got out of this storm,
will return to hearken to the peevishness of some sour men,
she will be abandoned both of God and man,
and will set both heaven and earth against her.`'

The year being come to an end, I go on to that of 1715.
In the month called May, it was moved in parliament,
that the term of the act for the Quakers`' solemn affirmation was almost expired;
and thereupon it was resolved,
that a bill should be brought in to prolong that said term;
and on the 7th of the said month a bill was accordingly brought into the House of Commons,
read the first time, and five days after the second time, and committed.
And whereas the former act was limited to a term of years,
this limitation was omitted now, and consequently the act was to be perpetual.
The bill thus far advanced, was at length engrossed,
and on the second of the month called June, after a third reading,
passed in the House of Commons, and sent to the Lords,
from whence it was sent back with this addition,
that this favor should be extended also to the northern part of Great Britain,
known by the name of Scotland,
and to the plantations belonging to the crown of Great Britain for five years,
for so far the former act had not reached,
and to the end of next sessions of parliament.

This amendment was agreed to by the House of Commons on the 13th of the said month,
and on the last of that month was confirmed by the royal assent.
Thus the Quakers were protected anew against the heavy shock which
otherwise they might have expected on the refusal of an oath.
King George on all occasions having shown himself favorable to them,
they did not omit thankfully to acknowledge his kindness,
as appears from the general epistle of their annual assembly,
where they expressed their gratitude in these words:

[.embedded-content-document.epistle]
--

The Lord our God, who, for the sake of his heritage,
hath often heretofore rebuked and limited the raging waves of the sea, hath,
blessed be his name, mercifully dispersed the cloud threatening a storm,
which lately seemed to hang over us; which,
together with the favor God hath given us in the eyes of the king and the government,
for the free enjoyment of our religious and civil liberties,
call for true thankfulness to him.
And humbly to pray to Almighty God for the king and those in authority,
for his and their safety and defense, is certainly our Christian duty,
as well as to walk inoffensively as a grateful people.

--

Thus they signified their thankfulness for the favor they enjoyed;^
footnote:[But seeing from the first grant of an affirmation instead of an oath,
the form then obtained was not entirely such as was desired,
and many were not easy therewith;
they several times applied to the parliament for a more easy form, which at length,
through the merciful providence of God, and the favor of king George and the parliament,
was obtained in the latter end of the year 1721; the form now being, '`I,
A+++.+++ B. do solemnly, sincerely, and truly declare and affirm,`' etc.]
and as they did now enjoy liberty, and quiet,
so the other subjects were also maintained in their rights under a gentle government,
so that none had cause to fear, who behaved themselves like peaceable subjects.
And yet in many places in England were great convulsions and tumults;
and some hot-headed clergymen were not a little instrumental therein;
whereupon an open rebellion ensued,
but the rebels were defeated near Preston by the king`'s forces.

Before I conclude this year, I am to say that the French king Lewis XIV.
did not live to see the end of it, but on the first of September,
N+++.+++ S. after having long languished by a malignant distemper,
died in the 77th year of his age; having before appointed his brother`'s son,
the duke of Orleans, regent of the kingdom of France.

This death seemed not a little to have altered the measures of the Pretender;
nevertheless in the beginning of the year 1716, he came over from France to Scotland,
in hopes to make an inroad from thence into England, but his attempt miscarried,
and his forces were discomfited by those of the king.
The common opinion was, that he chiefly relied on assistance from France;
but that was denied him by that court, though he seemed to have reckoned upon it.
He also lingered some time in Great Britain, after his forces were defeated;
but seeing no way to invade the throne he aimed at, he returned at length to France,
which kingdom he hath been fain to depart since,
to the joy of many inhabitants of England;
for it was thought that the rebels being deprived of their chief,
the disturbance would be at an end.

This rebellion being thus happily quenched,
induced the inhabitants pf Great Britain to congratulate the king with addresses;
and these congratulations being become so general,
the people called Quakers were not wanting to prepare also an address,
to testify their loyalty; and to express their joy for the quelling of the rebellion;
and therefore in their yearly meeting they drew up an address,
which they presented to the king on the last day of the month called May,
being introduced by the earl of Manchester,
one of the gentlemen of the king`'s bedchamber, when G. Whitehead said in substance:

[quote]
____
That in their annual assembly held for the religious concerns of their society,
endeavoring to promote and put in practice the duties of religion professed by them,
the sense of the great deliverance had such a weight upon their minds,
that they were willing to express it in an address to king George,
whom God by his providence had brought hither and preserved, so that he could well say,
he was George, by the grace of God, king of Great Britain, etc.
And that as men carried that saying stamped on the money in their pockets,
so it was to be wished it might be imprinted in the hearts of the subjects.
____

Hereupon the address was presented, and read to the king, being as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To GEORGE, King of Great Britain, etc.

[.signed-section-context-open]
The humble Address of the People called Quakers, from their yearly meeting in London,
the 26th day of the Third month, called May, 1716.

[.salutation]
May it please the King,

We thy faithful and peaceable subjects, being met in this our annual assembly,
do hold ourselves obliged, in point of principle and gratitude,
rather than by formal and frequent addresses,
humbly and openly to acknowledge the manifold blessings and kind providences of God,
which have attended these kingdoms ever since thy happy accession to the throne.

And as our religion effectually enjoins us obedience to the supreme authority,
so it is with great satisfaction that we pay it to a prince, whose justice, clemency,
and moderation, cannot but endear,
and firmly unite the hearts and affections of all his true Protestant subjects.

We are therefore sorrowfully affected with the unhappiness of those our countrymen,
who have so little gratitude or goodness,
as to be uneasy under so just and mild an administration;
nor can we reflect on the late unjust and unnatural rebellion,
without concluding the promoters thereof, and actors therein, were men infatuated,
and hurried by such an evil spirit,
as would lay waste and destroy both the civil and religious
liberties of these Protestant nations.

And as God, the Lord of Hosts,
hath most signally appeared to the confounding that Black Conspiracy,
so we pray his good Providence may always attend the king`'s councils and undertakings,
to the establishing his throne in righteousness and peace,
and making his house a sure house.

Permit us therefore, great prince,
to lay hold of this opportunity to approach thy royal presence
with our hearty thanks to the king and his great council,
for all the privileges and liberties we enjoy.
To behold a prince upon the throne, solicitous for the ease and happiness of his people,
beyond any other views, so heightens our satisfaction and joy,
that we want words to express our full sense thereof.
And therefore we can do no less than assure the king,
that as it is our duty to demean ourselves towards the king`'s
person and government with all faithful obedience,
so we are determined by divine assistance,
devoutly and heartily to pray the God and father
of all our mercies to vouchsafe unto the king,
a long, peaceable, and prosperous reign;
and that when it shall please the Almighty to remove from us so precious a life,
by taking it to himself,
there may not want a branch of the royal family endowed
with wisdom and virtue to fill the throne,
till time shall be no more.

--

To this address the king was pleased to give this gracious answer.

[quote]
____
I thank you for the assurance of duty and affection to my person and government,
contained in this address; and you may always depend upon my protection.
____

Thus we again see a prince on the throne, who solemnly assures the Quakers, so called,
of his protection;
so that now they enjoy the due liberty of subjects that behave themselves
peaceably and dutifully under the government set over them,
in like manner as other inhabitants of Great Britain:
and therefore they have not neglected to exhort one
another to show their thankfulness to Almighty God,
and to pray for the king, as it hath been intimated already,
that this was recommended in one of the epistles of their yearly meeting.
Now since mention hath several times been made in this history
of those epistles of the annual assembly to the particular churches,
I have thought fit to insert here one of them, viz. that of the year 1717,
which is as follows:

[.embedded-content-document.epistle]
--

[.blurb]
=== The Epistle from the Yearly Meeting in London, held by adjournment, from the 10th day of the Fourth month, to the 14th of the same inclusive, 1717.

[.letter-heading]
To the quarterly and monthly meetings of Friends in Great Britain, and elsewhere.

Our salutation, in the love of Christ Jesus our blessed Lord,
is freely extended unto you, whose tender care over, and mercy to,
this our annual assembly, we do humbly and thankfully acknowledge, in the love, amity,
tender condescension, and peaceable procedure thereof,
with respect to the divine power and goodness of the Lord our God,
and the service of his church and people;
sincerely desiring the prosperity of his whole heritage,
even in all the churches of Christ among us, in his dear love, unity and peace,
to his eternal glory,
and our universal comfort and perpetual joy in the kingdom of the dear Son of God.

We are truly comforted,
in that we understand there is such a general concurrence and union among Friends,
with our former earnest desires and counsel, for true and universal love, unity, peace,
and good order to be earnestly endeavored and maintained among us, as a peculiar people,
chosen of the Lord out of the world,
to bear a faithful testimony to his holy name and truth, in all respects;
and that all that is contrary be watched against and avoided; as strife, discord,
contention, and disputes tending to divisions, may be utterly suppressed and laid aside,
as the light and righteous judgment of truth require.

Oh! that all the churches and congregations of the faithful,
would be excited by the Spirit of the dear Son of God,
fervently to pray for the prosperity of his church and people throughout the world,
that Zion may more and more shine in the beauty of holiness,
to the glory and praise of the King of glory.

The friends and brethren,
come up from the several quarterly meetings in this nation) have
given a good account to this meeting of truth`'s prosperity,
and that friends are generally in love and unity one with another;
and by several epistles, from friends of North Carolina, Jersey, Pennsylvania, Maryland,
Barbados, Holland, Scotland, Ireland, and Wales, which have been read in this meeting;
as also by verbal accounts given by several friends
that have lately travelled in divers parts of America,
and elsewhere,
we have received comfortable accounts of the state of truth and friends in those parts;
by which we are encouraged to hope truth prevails in many places,
and a concern grows upon friends for the prosperity thereof;
and that there is an inclination in people to hear the truth declared.

By the accounts brought up this year,
we find that friends`' sufferings in England and Wales,
amount to five thousand two hundred and ninety pounds, and upwards chiefly for tithes,
priests`' wages, and steeple-house rates; and that,
notwithstanding there have been four friends discharged the last year,
there yet remain twenty friends prisoners on these accounts.

We advise that a tender care remain upon friends in all places,
to be faithful in keeping up our Christian testimony against tithes,
as being fully persuaded,
it is that whereunto God hath called his people in this our day;
we seeing by daily experience, that such as are not faithful therein,
do thereby add to the sufferings of honest friends,
and hinder their own growth and prosperity in the most blessed truth.

As touching the education of Friends`' children,
for which this meeting hath often found a concern;
we think it our duty to recommend unto you,
the necessity that there is of a care in preserving
of them in plainness of speech and habit,
suitable to our holy profession: and also that no opportunity be omitted,
nor any endeavor wanting, to instruct them in the principle of truth which we profess;
that thereby they, being sensible of the operation thereof in themselves, may find,
not only their spirits softened and tendered,
fit to receive the impressions of the divine image,
but may also from thence find themselves under a necessity to appear
clear in the several branches of our Christian testimony.
And as this will be most beneficial to them, being the fruits of conviction,
so it is the most effectual way of propagating the same throughout the churches of Christ.
And there being times and seasons wherein their spirits are, more than at others,
disposed to have those things impressed upon them; so we desire that all parents,
and others concerned in the oversight of youth, might wait in the fear of God,
to know themselves divinely qualified for that service,
that in his wisdom they may make use of every such opportunity,
which the Lord shall put into their hands.
And we do hereby warn and advise friends in all places to flee every appearance of evil,
and keep out of pride, and following the vain fashions and customs of this world,
as recommended in the Epistle, 1715.

And as we always found it our concern to recommend love, concord,
and unity in the churches of Christ everywhere, so as a means to effect the same,
we earnestly desire that Friends,
but more especially such as are concerned in meetings of business,
do labor to know their own spirits subjected by the Spirit of Truth;
that thereby being baptized into one body,
they may be truly one in the foundation of their love and unity,
and that therein they may all labor to find a nearness to each other in spirit;
this being the true way to a thorough reconciliation, wherever there is,
or may have been any difference of apprehension:
thereby Friends will be preserved in that sweetness of spirit, that is,
and will be the bond of true peace, throughout all the churches of Christ.

And, dear friends, the Friends of this meeting,
to whom the inspection of the accounts was referred, made report,
that having perused the same, they found the stock to be near expended;
whereupon this meeting thinks it necessary to recommend unto you,
that a general and free contribution be made in every county,
and that what shall be thereupon collected, be sent up to the respective correspondents.

Finally, dear Friends and brethren,
be careful to walk unblamable in love and peace among yourselves,
and towards all men in Christian charity,
and be humbly thankful to the Lord our most gracious God,
for the favor he hath given us in the eyes of the king and civil government,
in the peaceable enjoyment of our religious and Christian liberties under them;
and the God of peace, we trust, will be with you to the end.

The grace of our Lord Jesus Christ be with your spirits.
Amen.

Signed in, and on the behalf, and by the order of this meeting,

[.signed-section-signature]
By Benjamin Bealing.

--

From this epistle may be judged in some degree of the others,
which are sent from the yearly meeting of the people called Quakers
to the particular meetings of their society everywhere.
We see by it, that they give notice of the state of their particular churches,
and that they earnestly recommend love and unity among their brethren,
with other Christian virtues, and especially a good education of their children,
besides other matters which they judge to be meet and necessary.
With this epistle here inserted, I will finish this work,
as having performed my design and intention,
viz. the giving of a plain and circumstantial account
and relation of the rise of this religious society,
which, as we have seen, sprung from mean beginnings, to a great increase and progress,
and extended itself far, notwithstanding the violent opposition,
and most grievous severity, for suppressing and rooting them out,
so often put in practice, and committed by their enemies, but all in vain.
And they now enjoy an undisturbed liberty to perform
the public exercise of their worship to God,
since their religion is permitted by law;
which liberty they in no wise have obtained by making resistance,
but by a long-suffering patience, a peaceable deportment,
and a dutiful fidelity to the government set over them: so that now they see clearly,
that God doth not forsake those that do not forsake him,
according to what the prophet Azariah formerly said to king Asa,
and all Judah and Benjamin, 2 Chron. 15:2. "`The Lord is with you,
while ye be with him; and if ye seek him, he will be found of you: but if ye forsake him,
he will forsake you.`" Having thus performed what I intended with this historical relation,
I concluded it, to the praise and glory of the Most High,
who hath afforded me lifetime and ability, after a long and difficult labor,
to bring this history to a suitable end.
