== APPENDIX

The following narrative we have thought proper to insert in the very words of the sufferer,
as taken from his own mouth.
The candid reader will easily excuse the simplicity of its style,
and the plainness of its expressions.
It is the more like the man,
and carries the greater evidence of the honesty and integrity of the relater, viz.

[.blurb]
=== The account of the sufferings of Richard Seller, of Keinsey a fisherman who was pressed in Scarborough-Piers, in the time of the two last engagements between the Dutch and English, in the year 1665.

I was pressed in Scarborough-Piers, and refusing to go on board the ketch,
they beat me very sore on the sand, and I refusing to go on board,
they hoisted me in with a tackle,
on board of the ketch that pressed for the ship called the Royal Prince,
and they bunched me with their feet, that I fell into a tub, and was so maimed,
that they were forced to swaddle me up with clothes:
from thence we sailed into Bridlington bay,
where Thomas Swailes and Mary Stranger hearing of me,
sent me victuals on board of the ketch; then we sailed to the Buoy and Nore,
where they hauled me in at a gunport, on board of the ship called the Royal Prince.
The 1st day of the third month they commanded me to go to work at the capstane;
I refused, and told them, that '`As I was not free to do the king`'s work,
(i.e. fight in his war) I would not live at his charge for
victuals;`' then the boatswain`'s mate beat me sore,
and thrusting me about with the capstane till he was weary.
Then the captain sent for me upon the quarter deck, and asked me,
'`Why I refused to fight for the king, and why I refused to eat of his victuals?`'
I told him, '`I was afraid to offend God, for my warfare was spiritual,
therefore I durst not fight with carnal weapons.`'
Then he fell upon me and beat me with his small cane,
then called for his great cane and beat me sore,
and felled me down to the deck three or four times,
and beat me as long as his strength continued.

Then came one Thomas Horner, (who was brought up at Easington) and said, '`I pray you,
noble captain, be merciful, for I know him to be an honest man, and a good man.
Then said the captain '`He is a Quaker,
I will beat his brains out;`' then falling on me again, he beat me till he was weary;
then called some to help him;`' for,`' said he,
'`I am not able to beat him enough to make him willing to do the king`'s service.`'
Then came out the commander`'s jester, and told the captain,
'`He would lay a guinea with him that he would make me work,
and haul the king`'s ropes,`' and told the captain,`' he was
a fool;`' so two guineas were thrown down upon the deck:
then the jester called for two seamen,
and made them make two ropes fast to the wrists of my arms,
and reeved the ropes through two blocks in the mizen-shrouds, on the starboard side,
and hoisted me up aloft, and made the ropes fast to the gunnel of the ship,
and I hung some time.
Then the jester called the ship`'s company to '`behold and bear him witness,
that he made the Quaker haul the king`'s ropes;`' so veering the ropes,
they lowered me half way down, then made me fast again:
'`Now,`' said the jester,`' Noble captain,
you and the company see that the Quaker hauleth the king`'s ropes,`' and with that
he commanded them to '`let fly the ropes loose,`' where I fell upon the deck.
'`Now,`' said the jester,`' Noble captain, the wager is won,
he hauled the ropes to the deck, and you can haul them no farther, nor any man else.`'
Then the captain called the boatswain`'s mate, and bid him take the Quakerly dog away,
and put him to the capstane (a large rotating device on
ships used for weighing anchor or raising heavy sails),
and make him work, and beat him, and spare him not.
So the boatswain`'s mate had me down to the geer-capstane,
and thrust me about with the men at the capstane, and beat me withal,
when he could get time; then he went and sat him down upon a chest-lid,
and I went and sat down upon another chest-lid beside him,
then he fell on me and beat me again, then called his boy to bring his two seizings,
and he seized my arms to the capstan`'s bars, caused the men to heave the capstane about,
and in three or four times passing about, the seizings were loosed, no man knew how,
nor when, nor could they ever be found, although they sought them with lighted candles:
then the boatswain`'s mate, seeing what was done,
caused all the men to come from the capstane, and took a bible,
and commanded them all to swear, that they neither loosed me, nor knew how I came loose,
(they all being willing to swear,) he then searched their pockets for the seizings,
but could find none, so he let them go; then he called them all again to him, and said,
'`Hear what I shall say to you; you see this is a wonderful thing,
which is done by an invisible hand, which loosed him,
for none of you could see his hands loosed, that were so near him: I suppose this man,
said he, is called a Quaker, and for conscience sake refuseth to act,
therefore I am afflicted, and do promise before God and man, that I will never beat,
nor cause to be beaten, either Quaker,
or any other man that doth refuse for conscience sake to act for the king; if I do,
I wish I may lose my right hand.`'

Then on the third-day came the admiral, sir Edward Spragg, on board of his own ship,
called the Royal Prince, and hearing of a man that was pressed on board,
that was called a Quaker; also hearing that the boatswain`'s mate had beaten me much,
and had given me over, and had denied to beat me any more,
he was therefore called to come before the admiral, to answer for himself,
why he would not beat the Quaker?
He said, '`I have beat him very sore, and I seized his arms to the capstane`'s bars,
and forced them to heave him about, and beat him, and then sat down,
and in three or four times of the capstane`'s going about, the seizings were loosed,
and he came and sat down by me; then I called the men from the capstane,
and took them sworn, whether they had loosed him or no,
but they all denied that they either loosed him, or knew by what means he was loosed,
neither could the seizings over be found; therefore I did,
and do believe that it was an invisible power that set him at liberty,
and I did promise before God and tho company, that I would never beat a Quaker again,
nor any man else for conscience-sake.`'
The admiral told him, '`He must lose his cane:`' he willingly yielded it.
And told him, '`He must also lose his place;`' he was willing.
He also told him,`' He must lose his right hand:`' he held it out and said,
'`take it from me if you please.`'
So they took his cane from him, and displaced him.
So the commander gave order to the seven yeomen, to beat me wherever they met with me,
for seven days and nights, and make me work.
They being called to an account, what they had made me do?
told the commander, that '`They were weary, and could not make me work,
so they desired to be excused.`'
Then the eighth yeoman was called, who promised`' he would beat me,
and make me work:`' and he did beat me for a day and a night, when he met with me,
and being weary, he desired to be excused.
Then the commander sent for me upon the quarter-deck before him,
and caused my clothes to be stripped off, shirt and all, from my waist downward,
then he took a view of my body to see what wounds and bruises I had,
but he could find none, no not so much as a blue spot in my skin.
Then the commander was angry with them for not beating me enough:
then captain Fowler answered him, and said, '`I have beat him myself,
as much as would have killed an ox.`'
The jester said, '`He had me hung a great while by the arms up aloft in the shrouds.`'
The men said, '`They also had beat me very sore,
and they might as well beat the main-mast,`' Then said the commander,
'`I will cause irons to be laid upon him, during the king`'s pleasure and mine.`'
Then the boatswain was called, and commanded to call the ship`'s company together,
and make ready the irons: the commander, sir Edward Spragg, said,
'`You gentlemen sailors and soldiers, whosoever serves here under me for the king,
on board of his majesty`'s ship called the Royal Prince, the admiral of die blue,
you are to take notice, that there is a man on board called a Quaker,
he is to be laid in irons during the king`'s pleasure and mine, for refusing to fight,
and eat the king`'s victuals, therefore I charge you all and every man,
that none of you give or sell him any victuals, meat, drink, or water, for if you do,
you shall have the same punishment that he hath.`'
So this being called three times over, he commanded the boatswain to take me away,
and put me in irons.

So I being kept in irons six days and nights, and falling sick of a fever,
I grew very weak, insomuch that when I was set out to ease myself,
(which was but once in twenty-four hours) I could neither stand nor go:
so the officers that let me out,
called some of my countrymen to carry me into the ship`'s-head to ease myself,
and bring me back again to the irons.
Then the officer took pity of me, and bid me lay down upon the bilboes that night,
and he would hap me with a coverlid, so I lay there that night,
and next day till evening; then the officer desired me to go by the way a little,
seeing all was quiet, and see if I could get a little rest:
so I being lame of a leg with the irons, was creeping over the larboard-side of the ship,
the lieutenant coming down, said, '`Thou damned rogue,
(and many other wicked words) hast thou broken the irons?
and with that drew his rapier, and swore he would stab me,
and so drove me back again to the irons, and called the yeoman,
and would have known who let me out, and said he should be punished,
and I would not tell him; but the same yeoman came in the crowd,
and I put my hand out to him, and he locked it, and none knew how:
I then being the king`'s prisoner, I bid them '`begone, they had nothing to do with me.`'
So I remained in irons six days more, and recovered very well of my weakness:
then on the seventh day at night, several, all seamen, fell to drinking of brandy,
and playing at cards, and became very loud, the boatswain`'s mate hearing of them,
came down, and desired them to leave; they being full of drink would not,
so a quarrel arose,
and the boatswain`'s mate cried out '`murder,`' and
immediately there came assistance to him,
but the men ran away and hid themselves, only two were taken, and put in irons with me.

Now I shall speak a little of the carpenter`'s mate`'s kindness to me:
when I had been in irons some days, and my food being taken from me,
which was three day`'s victuals,
that I had left of that which Thomas Swales and Mary Stringer sent me in Bridlington bay,
he came in the crowd, and joined himself so near me,
that he put about a pint of brandy into my pocket, and no man knew; likewise some meat,
and none knew; and told me he would supply me daily, '`for,`' said he,
'`I have meat of my own, which is not at the king`'s charge;`' and said farther,
'`that he had a strict charge given him by his wife and his mother,
before he came on board, that if any Quaker came on board with him,
he should be kind to him;`' and that he had lately received a letter from them,
wherein they charged him to '`remember his promise, and be kind to Quakers,
if any were on board.`'
But there being some occasion more than ordinary, he was taken off on board,
and I had nothing for three days and three nights; and the two men before spoken of,
that were in irons with me, while the commander was with us,
the men would lie no where but upon me, and as soon as he was gone, they laid off me,
and gave me brandy to drink, and promised me they would not hurt me.
Then the lieutenant came at the middle of the night, and found them lying upon me,
he asked '`Why they did lie upon me?
they said, '`You would have him killed,
so now we will kill him for you;`' then he came down the third time in the morning,
and found them lying upon me, for they sat one to watch his coming,
and found them lying very close upon me, so that he could see nothing but my feet,
I being so pressed and weak, that he could scarce hear my voice.

Then the lieutenant went to Sir Edward`'s cabin door, and knocked; the boy answered,
'`Who was there?
He told him, '`It was the lieutenant that would speak with Sir Edward,
for there had been a mutiny in the ship by some men playing at cards,
and they had beat the boatswain`'s mate.`'
He told him, '`He should have laid them in irons, and not called on him.`'
He said, '`They are already in the bilboes.`'
He also said, '`If it please your highness.
Sir Edward, to remember that there is a poor Quaker in yet,
that was laid in two weeks since, and they will lie no where but upon him,
and they will kill him for us.`'
He bid him '`go to the yeomen that had the keys, and take him out of the bilboes,
and put up a flag at the mizen-mast`'s head, and call a council of war; which was done.
Then the captains of the other ships all came on board, to answer the council of war,
before eight o`'clock in the morning,
(it being the first day of the week.) So I being brought before the council of war,
the commander asked me, '`If I would go on board of a hoy that was a tender,
and had six guns?
I refused, and desired to stay on board, and bear the punishment that I had to abide.
Then he bid the council of war go on with their business; so they did proceed,
and I being set on a bulk head, being so lame with the irons that I could not stand,
and hearing them pass sentence of condemnation upon me.
The judge was a Papist, being governor of Dover castle, and went to sea on pleasure.
So they could not tell at present, what death to put me to.
The judge said, '`I should be put into a barrel or cask driven full of nails,
with their points inwards, and so rolled to death.
But the council of war taking it into consideration, thought it too terrible a death,
and too much unchristian-like, so they agreed to hang me.
And I hearing them speak several things against me, which I was clear of,
had a desire to arise from my knees, where I was set to answer for myself,
but I had not any power to arise or open my mouth, but was condemned within myself,
insomuch that I had not power to breath unto God.
Proffering to rise again the second time, there came a motion within me,
and bid me '`Be still, be still, be still,`' three times; which I obeyed,
and was comforted; then I believed God would arise: and when they had done speaking,
then God did arise, and I was filled with the power of God,
and my spirit lifted up above all earthly things,
and wonderful strength was given me to my limbs,
and my heart full of the power and wisdom of God,
and with glad tidings my mouth was opened to declare to
the people the things that God had made manifest to me.
With sweat running down, and tears trickling from my eyes, I told them,
'`The hearts of kings were in the hand of the Lord, and so are both yours and mine,
and I do not value what you can do to this body, for I am at peace with God and all men,
and you my adversaries; for if I might have a hundred and thirty years longer,
I can never die in a better condition, for the Lord hath satisfied me,
that he hath forgiven me all things in this world, and I am glad through his mercy,
that he hath made me willing to suffer for his name`'s sake; and not only so,
but I am heartily glad, and do really rejoice, and with a seal in my heart to the same.`'
Then there came a man and laid his hand upon my shoulder, and said,
'`Where are all thy accusers?`'
Then my eyes were opened, and I looked about me, and they were all gone; and one said,
'`There goeth thy chief friend, the judge.`'
Then it arose in my heart, that I had news for him from the power of God, and I said,
'`Man, come back, I have news for thee better than ever thou heardst in any coffee house,
or elsewhere; and answer for what thou hast done.`'
Then came a lieutenant, and said, '`Sir Edward, this is a hypocrite Quaker.`'
I said, '`Commander I intreat thee to look upon me a little.`'
So I loosed my knee strings and put down my stockings and let him
see how the blood and rotten stuff ran down my leg round about.
He said, '`Put up thy stocking, there is enough.`'
Then presently came an ancient soldier, and loosed down his knee-strings,
and put down his stockings, and put his cap under his knees,
and begged his pardon three times.
Then said he, '`Arise up soldier, and speak;`' and he intreated him, and said,
'`Noble Sir Edward, you know that I have served his majesty under you many years,
both in this nation, and other nations, by sea, and you were always a merciful man;
therefore I do intreat you in all kindness, to be merciful to this poor man,
who is condemned to die tomorrow, and only for denying your order,
for fear of offending God, and for conscience-sake; and we have but one man on board,
out of nine hundred and fifty, but one which doth refuse for conscience-sake,
and shall we take his life away?
Nay, God forbid; for he hath already declared, that if we take his life away,
there shall a judgment appear upon some on board within eight and forty hours,
and to me it hath appeared; therefore I am forced to come upon quarter-deck before you,
and my spirit is one with his; and therefore I desire you in all kindness,
when you take his life away to give me the liberty to go off on board,
for I shall not be willing to serve his majesty any longer on board of ship:
so I do intreat you once more, to be merciful to this poor man: so God bless you,
Sir Edward, I have no more to say to you.`'

Then came the chief gunner, that had been a captain, and loosed down his knee-strings,
and did beg his pardon three times, being upon his bare knees before Sir Edward.
Then he said, '`Arise up, gunner, and speak.`'
So he said, '`If it please your worship.
Sir Edward, we know you are a merciful man, and therefore I intreat you in all kindness,
to be merciful to this poor man,
in whom there remains something more than flesh and blood, therefore I intreat you,
let us not destroy that which is alive, neither endeavor to do it; and so God bless you,
Sir Edward, I have no more to say to you.`'
Then he went away.
Then the commander desired me to go down,
and take leave of my friends (this day) that were on board; so he gave order,
that any that had a mind to give me victuals might,
and that I might eat and drink with whom I pleased,
and that none should molest me that day.
Then came the lieutenant, and sat by me while they were at their worship,
and he he would have given me brandy, but I refused.
Then the dinner came up to be served, and several gave me victuals to eat,
and I did eat freely, and was kindly entertained that day; and night being come,
a man kindly proffered me his hammock to lie in that night,
because I had laid long in irons, and I accepted of his kindness,
and laid me down and slept well that night.
The next morning being come, it being the second-day of the week,
on which I was to be executed, about eight of the clock in the morning,
the rope being veered upon the mizen-yard`'s arm, and the boy ready to turn me off,
and boats having come on board with captains of other
ships that were of the council of war,
who came on purpose to see me executed.
I was thereupon called to come to be executed, then I coming to the execution place,
the commander asked the council, '`How their judgment did stand?`'
So most of them did consent, and some of them were silent.
Then he desired me freely to speak my mind,
if I had any thing to say before I was executed.
I told him I had little at present to speak.
So then came a man, and bid me go forward to be executed,
so I stepped upon the gunnel to go towards the rope; the commander bid me stop there,
if I had any thing to say.
Then spake the judge, and said, '`Sir Edward is a merciful man,
that puts that heretic to no worse death than hanging.
Sir Edward turned him about to the judge, and said,
'`What saidst thou '`I say,`' replied he, '`you are a merciful man,
that puts him to no worse death than hanging,`' '`But`' said he,
'`what is the other word that thou saidst, that heretic:`' I say, said the commander,
'`he is more a christian than thyself; for I do believe thou wouldst hang me,
if it were in thy power.`'
Then said the commander unto me, '`Come down again, I will not hurt a hair of thine head,
for I cannot make one hair grow.`'
Then he cried, '`Silence all men,`' and proclaimed it three times over,
that if any man or men on board of the ship, would come and give evidence,
that I had done any thing that I deserved death for, I should have it,
provided they were credible persons.
But nobody came, neither opened a mouth against me then.
So he cried again, '`Silence all men,
and hear me speak:`' then he proclaimed that the Quaker
was as free a man as any on board the ship was.
So the men heaved up their hats, and with a loud voice cried, '`God bless Sir Edward,
he is a merciful man.`'
The shrouds, tops, and decks being full of men, several of their hats Hew overboard,
and were lost.

Then I had great kindness showed me by all men on board,
but the great kindness of the Lord exceeded all; for the day I was condemned to die on,
was the most joyful day that ever I had in my life-time,
and so remained exceeding joyful, until the very time that I was proclaimed a free man.
But soon after troubles came upon me again; for I being laid upon the deck one night,
as it was my usual lodging-place, there was something appeared to me,
and struck me as it were dead; and I being in great dread and fear,
believed our ship was to engage such a day of the month, with the wind at south-east;
then appeared also a small cloud to me, about as big as a hat.
After being engaged, the same cloud spread, and became a great one,
insomuch that it darkened part of the ship;
then I stepped over on the starboard side of the ship, into the shrouds, and looked aft,
and I saw a thick water arising in the wake of the rudder,
then I feared the ship was near ground.
This appeared to me three times that night, and I would gladly have put it from me,
but I could not.
Then I did believe, and was satisfied of the truth of it,
then I was at peace and quiet in my mind, but then I was to make it known to the pilot,
and I did believe it was death by law to discourage them; so I thought,
then I should give them an occasion that they should take away my life;
but I could not rest, eat, drink, or sleep, until I had declared it.
So I breathed unto God, and desired that he would find me a way to reveal it.
So it remaining with me two days and two nights, and being walking upon the deck,
and taking notice of the chief gunner of the ship, I was ordered to go to him,
and walk with him.
Very solitary were both of us,
and he perceived I had something to say to him of some weighty matter,
so he desired me to speak my mind to him, and I told him,
I had such a weighty matter to declare, that it was death by the law to declare it,
I desired that he would stand true to me in that respect,
and he promised me fidelity in the presence of God, before whom we were,
that he would be true to me in all respects, and if one suffered, both should suffer.
Then we espied the mate of the ship walking, he being a sober man, we drew near to him,
and he perceived we were both afflicted, and desired to know what was the matter?
So we told him, we had a weighty matter,
and if he would be as faithful to us as we were one to another,
we would declare it to him; so he promised to be faithful to us,
for he did believe it did concern him.
Then we told him the matter; and he was fully satisfied of the truth of it.
'`But,`' said he, '`it doth belong most of all to the pilot;`' so we must speak to him,
and he being such a brickle, high-spirited man, we scarce knew how to speak to him,
but calling him to us, and walking with him, he took notice of our heaviness,
and asked our business with him; we told him,
'`We had a matter to declare to him of great concern,
therefore we desired him to be faithful to us,
and we would declare the matter to him,`' and he promised to be as faithful to us,
as he supposed we were one to another.
So they told him the matter; then he asked, '`Who saw it?`'
I told him, '`I see it.`'
Then he fell into a rage, and seemed to fly from his promise, and said,
'`He would go and tell the commander.`'
So away he went, and said, '`He would have me executed speedily.`'
I said, '`Let him do; better I die, than the whole company perish.`'
But they said, '`If thou die, we will all die.`'
Then he came to us again near weeping, and told us,
that when he came before the commander, his mouth was stopped,
that he could not speak a word good or bad.
He was very tender, and praised God that he had such a messenger.
Then he took me by the hand, and desired me to tell him the name of the sand.
I told him I did not know, I never came there; but at that time I looked up with my eyes,
and told him whereabouts the sand laid: so he desired me to go to the compass,
and he asked me, if I knew the compass?
I told him, very well; so I showed him upon what point of the compass the said land laid,
and he took a book out of his pocket, and found the sand, and the name of it.
Some days after we were engaged on that very point with the Hollanders,
and as soon as we were engaged, the cloud appeared to me, and came and darkened the ship.
Then I stepped into the main shrouds, and I saw the thick water,
which I showed to the pilot, and he called two of the best men to the lead.
They called, '`Five fathom and a quarter.`'
Then the pilot cried, '`Starboard your helm.`'
On which the commander cried '`Larboard your helm, and bring her too.`'
The pilot said, '`He would bring the king`'s ship no nearer, he would give over his charge.`'
The commander cried, '`Bring her too.`'
The pilot cried to the lead-men, '`Sing aloud,
that Sir Edward may hear;`' (for the outcry was very great amongst the officers and seamen,
because the ship was so near aground, and the enemies upon them) so they cried,
'`A quarter less five.`'
The commander cried, '`We shall have our Royal Prince on ground, take up your charge,
pilot.`'
Then he cried hard, '`Starboard your helm,
and see how our ship will veer;`' so she did bear round up.
The men at the lead cried, '`Five fathom, and a better depth.`'
Then the commander cried, '`God preserve the Royal Prince.`'
Then the pilot cried, '`Be of good cheer, commander.`'
They cried, six fathom, then nine fathom, then fifteen fathom, then sixteen fathom.
The Hollanders, then shouted, and cried, '`Sir Edward runs.`'
Then he cried, '`Bring her too again;
and the fight continued till the middle of the day was over, and it fell calm.
The ships being engaged ahead of us, we could see nothing but fire and smoke;
so out of that smoke I espied a fire ship designed
to lay us on board of the larboard bow.
Then I cried to the chief gunner to come to me quickly,
and I showed him the fire ship coming to board us on the larboard bow.
Then he fired a chace-gun with a ball in her;
and as soon as the smoke was gone from the gun, we espied the fire-ship all on a fire,
blown up, and what remained of her sallied on board of the Cambridge,
and only burned her ancient.
The fight continued, and my employ was to carry down the wounded men,
and look out for fire-ships, and the commander was mightily pleased with my service,
and said '`It would have been a great pity that my life should have
been taken away before the engagement;`' and the chief gunner said,
'`I was instrumental, through mercy,
not only for giving notice of the ship coming on ground upon the sand,
but also for preventing of the fire-ship that was near to board us,
who gave me the first notice, whereof I am witness.`'
And the lieutenant said to the commander,
that '`There was not a more undaunted man on board, except his highness.`'

Eight days after, we were engaged again with the Hollanders,
and the officers sent for me upon the quarter deck, and asked me.
What I would do that day?
I told them, I was willing to do as I had done before;
they desired I would do that service, and take that care upon me,
only to look out for fire-ships coming on board.
I told them I was free to do it, likewise to carry down the wounded men,
if there was occasion; so presently we engaged,
but not one fire-ship troubled us that day, but we lost about two hundred men.
The lieutenant meeting me, he asked me, If I had received any wounds?
I told him, I had received none, but was well.
He asked me, How came I to be so bloody?
Then I told him.
It was with carrying down wounded men.
So he took me in his arms, and kissed me;
and that was the same lieutenant that persecuted me so with irons at the first.
Then we came to the Buoy and Nore again, and then went up near Chatham,
and the king coming on board,
the lieutenant desired me to go and walk upon the deck with him, in sight of the king,
that haply some might give him notice of me, hoping I might be brought to a trial,
and have my liberty: but I did not understand that he had any intelligence of me.
The next day the same lieutenant came to me,
and desired me to walk along with him upon the quarter deck.
I being somewhat unwilling, told him, I did not use to go upon the quarter-deck,
unless I was called by the officers.
He said, '`My uncle hath much business, and doth forget you; so walk along with me,
I desire you.`'
And I did as he desired me, and he being with me, walked away and left me alone.
The commander being there, and several captains with him, he came from his company to me,
and laid his hand upon my head, and said '`Thou hast done well,
and very well too:`' so he walked by me, and I blushed.
Then he asked me.
Why I blushed?
I told him I desired to know wherein I had done so well.
He said, '`By encouraging them which should have encouraged both thee and me.`'
Then said he, '`Thou shalt have thy liberty to go on shore.`'
I asked him.
If I might go on shore to recruit, or go to my own being?
He said, '`I should choose whether I would.`'
I told him, I had rather go to my own being.
He said, '`I should do so.`'
Then I told him, there was one thing that I requested of him yet,
that he would be pleased to give me a certificate under his hand,
to certify that I was not run away.
He said, '`Thou shalt have one to keep thee clear at home,
and also in thy fishing;`' for he knew I was a fisherman.
So he called the captain, and ordered him to write me a certificate, and bring it to him;
which he did with speed, but he did not like it, but flung it him again,
and ordered him to make me one more legible.
Then he brought another, and he signed it, and gave it me, and wished me well, and said,
'`He desired to hear from me if I got well home;`' and I told him,
I would send him a letter, and so I did.
But soon after I got into London, two press-crews came to me, and said.
'`This is Sir Edward`'s Quaker; you are welcome to shore,
will you please to go to the tavern with us?`'
I told them I would not go, nor drink any thing.
Then they wished me well home.

Also they proffered me my pay, before I came off on board, and said,
'`I deserved it as well as any man on board.`'
But I refused, and told them, I had of my own, that I hoped would serve me home.
And the lieutenant was troubled because I would take nothing;
he would have given me twenty shillings, but I would not take it.`'

Thus ends the remarkable narrative of the sufferings of this faithful sailor,
who rather than violate his conscience by being instrumental
to destroy other men`'s lives,
endured with much patience many and sore trials,
persevering faithful in his testimony against war and fighting, even to death;
to which he was wholly resigned,
and from which he was preserved by a singular providence attending him,
in those moments of time which he thought would have been his last.
But the virulence of the popish judge against him as a heretic, gave the commander,
Sir Edward Spragg, who professed himself a protestant, such disgust,
that scorning to be made a tool to execute the vengeance of a papist in this case,
he delivered the innocent man from the death he was condemned to:
being thus preserved alive, he was made instrumental to the saving of the ship,
and the lives of many therein:
and by the exercise of an undaunted Christian courage and constancy,
triumphed over the malice of his adversaries, who conscious of his innocence,
at length became his friends and favorers.

[.asterism]
'''

[.blurb]
=== A narrative of the Sufferings of John Philly and William Moore, in the Inquisition of Hungary, from the first month 1662, to the seventh month 1663. Taken from a letter written by William Moore to William Caton, dated Amsterdam, 11th month, 1663.

[.embedded-content-document.letter]
--

On the 29th of the first month, 1662, John Philly and William Moore,
being refreshed with the overflowings of the love of God through thee,
we took our leave of thee and the rest of our dear friends in Germany;
and what a cross it was to my flesh and blood to leave thee and them,
and to take such an unknown journey,
is best known to him that seeth the secrets of all hearts, and what a capacity I was in,
is pretty well known to thyself,
yet we passed according to the information thou hadst procured for us of the way,
together with what we got elsewhere, and we prospered in our journey,
and arrived the 16th of the second month at Cutshort, by the Hottersche brethren,^
footnote:[These Hottersche brethren were a kind of Baptists, who lived in a community,
having, like the primitive Christians, their goods and possessions in common.
They also refused to swear or fight,
and dwelt by hundreds of them together in one family.]
about a day`'s journey from Presburgh in Hungaria,
where we were pretty kindly entertained by some of them,
and there I dealt some books among them, which I had carried with me,
and the next day I went alone to another family of them:
and in my going thither the Lord preserved me out
of the hands of a wicked man which I met withal,
who seeing me a stranger, would, it`'s like, have laid violent hands on me,
or have knocked me on the head for my money, had not the Lord restrained him,
and the brethren (so called) wondered I was preserved,
for they could not go so far as to the next village, but were in danger.
After we had some pretty good service among them,
we got the names of some more of their families,
and one of them was three hundred miles farther, at a city called Pattock,
in Upper Hungaria, but some of them would have dissuaded us from going any farther,
but rather only to have visited the families thereabouts,
which I could have been free unto, but John was pressed to go forward,
and I had not freedom to leave him, he not having their language, which I had.

After that we returned to Presburgh, where the Danube divideth itself,
and it meets at Comora, where we were taken, which happened as followeth:
we finding a boat going with meal to the garrison at New-Hausell,
which lies in the way to Pattock, we went to her, and when we came near unto the place,
the boatmen asked me, '`Whether I had acquaintance there?`'
I said, '`No.`' '`Whether we had a pass?`'
I said, '`No.`' Then said they,
'`It is dangerous going thither,`' because they would be suspicious of us,
and to travel farther in that land, they being tributaries to the Turk,
we should be in danger of being killed either by the countrymen, or by some of the Turks,
and at that garrison they did use to put men to cruel deaths, which have been found,
without leave, on the tributary ground.
Yet John was desirous to be at that village which was near there, but said the boatmen,
'`He will not take counsel before ye shall remember our words,
and repent it when ye cannot help it;`' and their words had the more impression on me,
because I had seen a night or two before in my sleep,
that which afterwards came to pass at Comora, where we arrived,
and were brought to a Hungarian`'s lodging, but we could not understand one another;
but the next night they sent for a student from the college,
who asked me in Latin,`' Whence we were, and whither we were intended?
I told him, '`We came from Great Britain, and desired to be at Pattock.`'
Afterwards we entered into a discourse about religion, and when we parted, he said,
'`He wished us well, though there was a vast difference in our judgment,`' etc.

The next day we endeavored to get over the river,
and made signs to a countryman with some money,
who began to make his boat ready to help us, but an old Dutchwoman came forth, and said,
'`What do ye?
And told me, '`The governor would presently cause him to be hanged,
if he set us over;`' so we let it rest, and we returned to our former lodging,
and the next day I went over the water on the south-side of the town,
where I heard there were many Dutch people and soldiers,
hoping to find some countrymen to speak with, and some books I took with me,
which I would willingly have sent to Pattock; and coming to the soldiers,
asked for countrymen, but finding none, I asked leave of the guard,
and walked out into the field, where a trooper sat sentinel,
discoursed a little with him, and passed on farther, where some were ploughing.
And as I returned back, there did meet me a soldier of captain Fusch`'s company,
with two other, and having a book in my hand, called, [.book-title]#A Paper Sent Forth into the World, to Show the Grounds and Reasons Why We Denied the Priests of the World.#
He looked on the title, and began voluntarily to tell me,
that '`Such a place was in Turkey, and if a man went thither,
he might have good days there,`' etc.
But I said,
'`I will go from whence I came,`'and intending to return
to John on the other side the water,
the aforesaid soldier came to me again at the water-side, and told me,
'`I must come to the captain,`' and when I came before him he asked for the book,
and looking on it, asked, '`If I was a Quaker?`'
I said, '`Yea.`'
And he being in a rage, said, '`These rogues show no respect;`' and said,
'`I was a young Hus come forth to seduce the people, and make uproars, etc.`'
And he caused the soldiers to pull off my clothes, and to search me for letters,
and took my money from me: and I spake something to them,
to give them to understand they would not be so done by.
But he said, '`When you get clear, you shall have your money again.`'
But he did not think that should be, so he sent me to the guard a while,
and sent for me again, and searched me more narrowly,
and found the books which were enclosed between the linings of my breeches:
then I was sent to the guard again,
and the marshal was to put iron shackles with a chain upon my foot and hand;
and there was a talk as if I should be stuck upon a wooden spit,
as some had been who had but gone to the next village without their order;
but I turned my mind inward, and was pretty well resigned up to the lord.
So they having sent over to the chief officer to inform him,
there were two soldiers sent with their burning matches to fetch me,
and I little expecting less than present death,
had told some soldiers,`' I had a companion in the inn on the other side,
and he would marvel what was become of me if he did not hear.`'
Afterwards I was carried to the officer aforesaid, who asked me,
'`If Mary had continued always a virgin?`'
To which, when I had answered, '`Thou rogue,`' said he, '`if I had but power over thee,
I would presently drown thee in this water.`'
Afterwards they went to our lodging, and apprehended John also,
howbeit free of that crime they imputed to me, which was for going over,
and into the garrison.
I was put in the Dutch prison, called the Stock-house,
and John into the Hungarian`'s vault, which was twenty foot long, where they rack people,
and there was a private gallows, a pair of stocks, and a filthy tub of excrements;
and the aforesaid officer took our portmantle,
but afterwards it was given to the marshal, who took what pleased him out of it,
with the Bible and papers, and left the rest to another officer, who feignedly,
after our commitment, seemed to be troubled that we had no bread, and asked me,
Whether John had no money, which I could not deny, and then he went to the other prison,
and threatened him to give it him.
So John gave him a ducat, which he got changed, and brought us the money,
and desired we would give him some of it, and he would be worth it at our hands.
John afterwards expecting they would search him for gold, did afterward hide some,
and kept some by him.

The day following, we were first examined by the inquisitor.
Whence we were?
Whither we intended?
How old we were?
Who was the author of our coming forth?
What money we had taken up?
And John was searched, and the gold found which he had left by him:
and I was examined concerning the books, and told, It was a capital crime,
and would cost me my life.
But I said, '`What I had done therein, I had done in simplicity,`' etc.
And he asked, '`Who had spoke with us in our lodging?`'
I told him,`' A student,`' with many more words.

And after the first examination,
one colonel Fusch desired to have me brought forth before him,
and he asked me several questions concerning the books;
and`' Who was the first bringer up of this doctrine?`'
I told him,
'`George Fox was one of the first preachers of it in this generation,`' and because
I owned the books aforesaid to be wrote by the motion of the Spirit of God,
he was very bitter against me, and several cunning questions did he ask me,
as thereby to ensnare me, but it did not avail.
Something he read in one of the books concerning their steeple-houses,
as advice to people that they should go no more to them,
etc. which seemed to be very odious to him; and he told me,
that '`He would cause all those books and writings
to be copied and sent to his prince at Mentz,
and when he could spare them the inquisitor should have them.`'
Afterwards I was taken to the deputy governor,
(a cruel old fox) who asked me several questions, and said,
'`He would send me with a message to the devil;`' and he said,
'`I had done more than if I had killed a hundred men;`'
and because I would not take off my hat,
he judged that to be a Turkish principle,
and I not being free at that time to drink wine, he asked me, '`Why I said,
'`because I would bring my body into subjection.`'
'`How long,`' said he, '`will you abstain?`'
I said, '`till night at least.`'
'`That,`' said he '`is another Turkish point, to fast till night.`'
He had also sent for the Hungarian student, and commanded him to tell him in Latin,
all what had passed between us in our lodging,
which the inquisitor afterwards took to read when we were examined,
but he would not read it openly,
lest the sitters by should have heard and owned the truth thereof
Afterwards they brought our attempt to go over the water,
as a mighty crime against us, and the aforesaid soldier was called to testify against me,
whose testimony being false, I withstood him, and told the inquisitor,
who did much seek occasion against me, that '`He should beware what he did,
for if he should cause my blood to be shed under such a pretence,
it would cry to the Lord for vengeance,
and thereby he might draw the wrath of God upon him and others.`'
And I desired the other soldiers might be examined, who also had heard what I said;
which after some time was granted, and I was put forth,
and my adversary and accuser he was kept within, and one of the other was called;
and then I thought,`'Now if the Lord doth not assist me,
they may persuade him to speak the same thing.`'
But when he came forth, he told me, '`He did not speak as the other,
for that which the other had affirmed,
was not true;`' then I thanked the Lord that this pretence failed them.
But afterwards the inquisitor told me, '`The books were enough,
though there were nothing else;`' and asked me,
'`Whether I knew not that the catholics had laws to burn and torment heretics,
and such as carried such books?`'
I said,
'`I should not have expected such dealing among good Christians,`' and so did not tell him.
Howbeit, I knew well, that they were cruel and bloody enough.

Then he opened a book of the corrupt popish laws, and read therein,
how that such persons as carry such books and papers are to be racked, etc.
And about this time was John searched yet farther for gold,
by the command of the inquisitor,
and having taken so far off as one of his shoes and stockings,
he was slow in taking off that where the gold was, and the marshal thinking it tedious,
and thinking there had been no more, bid him put them on again.
And upon a certain time he gave it me in half a little white loaf,
when we stood with the soldiers waiting to be called.
And they seeing the book called [.book-title]#The Way to the Kingdom,# that it was printed at Amsterdam,
asked me, '`What books I brought from thence to Paltz, and how many?`'
And one morning having sent for one of the priests.
He got that written book of George Fox`'s of the [.book-title]#Apostasy of Christendom,#
who looking on it, began to be hot and wrathful, saying,
'`How are we (meaning the papists) apostatized, and how can that be proved?`'
I said, '`Friend, it becometh not a spiritual man to be so furious, but gentle, meek,
peaceable,`' etc.
Then was his countenance dashed, and he had little more to say.
The inquisitor asked me farther concerning the sacrament, etc.
And I told him how Christ said, '`The flesh profiteth little,
it was the spirit that quickened,`' etc. which seemed strange to him,
and he asked the priest, Sir, father, how is that?`'
who bethought himself, and said,
'`He did remember there was such a saying;`' and more words passed between us,
which would now be too long to relate.
Farther, the inquisitor asked me,`' If I would be a catholic?
I said, '`If I should be so for fear or favor of them, the Lord not requiring it of me,
I should not have peace in my conscience,
and the displeasure of the Lord would be more intolerable than theirs;
and as for compelling people, that did but make them hypocrites,
and doth not truly change the heart.`'
Which the priest could not deny but that it was true.
And notwithstanding our innocence, the governor would have us racked, which seemed to me,
according to relation, a cruel torment;
and in those days I often poured forth my supplication to the Lord with tears.
And being almost every day examined until the eighth day,
they made ready benches to sit on, lighted the candle, and put John out of his room,
and sent for me.
The inquisitor sitting there with two more officers,
and the marshal and the hangman by them.

The inquisitor said, '`William, that you may not think we deal with you as tyrants,
we will lay it before you, that you may tell what you know in time, for if you be racked,
you will be but a miserable man, and must have your head cut off besides.`'
But I told him, '`I knew no evil, nor had any such thing in my heart against them.`'
Then he read a few lines to this purpose.
'`We, Leopoldus, etc.
Emperor, etc. having understood of two impeached persons, John Philly and William Moore,
found by our frontier garrisons, our desire is they should be racked,
to know their intent.`'
And then the hangman, according to order, put on an iron screw hard upon my thumbs,
and bid me, '`Tell out.`'
Then he slacked them and screwed them harder again; but that not availing,
he was commanded to proceed farther,
and so he tied a small cord about my wrist behind my back,
and drew me up some degrees on the ladder, and tied my hands to one of them,
and another cord about my ankles, with a battel of wood between my feet,
lifted up my body quite from the ladder,
and at the first pull my left arm gave a pretty loud crack out of joint,
being shorter tied above that wrist; then he was bid put it in joint again.
So he slacked, and they asked me, having three things especially to ask.
1st. Why did I ask the student, if one should come to them, and say,
He intended to buy somewhat of them, if they would then kill him?
Why we had desired to be set over the water at the town, and who was the author?
3d. Why I had written up some of the names of the garrisons, and other places,
notwithstanding I had them in the maps`'?

And though he mentioned but three questions at the first,
yet he would have forced me to have told, whether J. Philly was an engineer, a gunner,
or a minister?
Now this suspicion of his being a minister, had an Irishman, it seems,
put into their heads,
who had almost an irreconcilable hatred or malice in him against Englishmen,
as I afterward out of his mouth plainly understood, especially against ministers,
as authors of their ruin and exile: and this man was interpreter between me and them.
But I answered, and kept to this, that he was a husbandman and a maltman,
and I knew him not till he came to Amsterdam.
He asked me, '`If I had a mind to go to the Turks, and to be one?
I said, '`I had rather die than be one.`'
In the mean time I was so racked, that my chin was so close to my breast,
and closed my mouth, that I was almost choked, and could not well speak any longer,
and I should not wish any to experience how painful it was,
and yet they would be questioning me.
Then I asked them '`Where is now the Christian love,
and do ye now as ye would be done unto?`'
And I cried the louder,
that the people without might hear and bear witness what they were a doing to me,
for the door was shut and guarded, and sometimes when I was slacked,
it was almost as painful as the pulling: but something they would have out of me,
and I told them,
how that they might by such means force one (as I
believed many had done) to say more than they knew,
to be out of their pain;
for I had rather they had proceeded to have beheaded me according to their threatenings,
than to have tormented me; but yet that they would not do then,
for he (the inquisitor) would have me say yea to it,
which it`'s likely would have been enough to them,
though they had known us to have confessed a lie: however finally I confessed,
it was for love to our religion that we were come to those places.
Then they left off, as thinking there was crime enough:
yet he spake as if I should be racked again on the third day.

Then they fetched John, who not seeing me, but having heard me crying out before,
he thought I had been hanged on the private gallows, and put out of the way.
But he was given up, being confident in the Lord,
who had sealed to him (he said) that he should have
his life for a prey before he came forth:
so they laid four things to him chiefly to answer, and his thumbs were screwed,
and he was drawn on the ladder twice, and he cried out,`' Innocent.`'
And they asking the interpreter, What that was?
He said, '`they were smitten in their consciences, and they left off:`' I judge the sooner,
because if there had been any evil, they would have got it out of me,
with whom they had more delight to meddle, because they could understand me, and I them:
and then it was afternoon, and they hungry, it`'s like, for they had begun early with me,
and when all was done, and they could find no contradiction, they invented a lie,
and the marshal came unto me, and told me, John had said, I had no money by me,
but what I had was his; and bade me tell how it was?
But I knew it was otherwise: but they sought occasion against us,
that they might yet have tormented us more, but I kept to truth,
which he also had spoken, and their expectation failed them.

Afterward a priest with the marshal came,
and felt my ears to see whether I had been a rogue, or some one of account,
which they would have concluded, if they had been either cut or bored.

When they had done all this, they told me,
There would be twenty or thirty men of note appointed out of the quarters round about,
to hold a court of justice upon us, and to determine what deaths we should die,
and to make new laws for our sake; but in the mean time the inquisitor came,
and would have me first write some of the heads of my religion,
so I did write many particulars, which I cannot now set down word by word,
at some of which he raged very much.

About that time John Philly,
feeling much of the wickedness of the inquisitor and priests,
and being sensible how they plotted to take away our lives,
did once cry out to the governor when he was in his coach,
and he sent to know what he would have,
which was to acquaint him with the particulars laid, before him in his racking,
and what his answers were, and how there was no contradiction found in our answers,
for he was jealous,
that the inquisitor and priests would prevent our words to the governor,
and afterwards he got pen and ink, and wrote to the governor, but the inquisitor got it,
and sought to keep it from the governor, for it is like,
he was convicted in his conscience of his dealing so evil with us.
But John perceiving he would smother it, called to the governor again,
who commanded him to give me it to translate for him, which was done;
so not long after came the inquisitor to me, having been sick three days upon the bed,
and told me, he was sent by the governor,
that we might go forth and fill a little earth in the wheelbarrow,
whereby we might earn near two pence a day to buy us bread;
for,`' said he,`' that which remains in my hands of the money is little for my pains,
and the marshal and hangman will have some for their pains.`'
This was about five weeks after our coming to Comora,
and we were willing to accept of the governor`'s offer,
that we might thereby have the benefit of the fresh air,
and that our bonds might be manifest to such as might somewhat take it to heart;
for there were both Lutherans and Calvinists that did partly commiserate our conditions,
but durst not venture to come and see us in the castle,
and sometimes was some small thing given us by some, and the papists marveled,
and others were glad we had obtained the favor as to be suffered to work;
yet sometimes the marshal would not suffer us to go out,
and sometimes he kept back of our wages, and on saints days, so called, and rainy days,
we had no wages.
Howbeit the Lord provided for us,
for there were some women that remembered us on these days,
and pretty much we could have gotten, had we spoken to rich people, and to officers,
but we were not free to beg of any, whereupon the marshal was angry.
And as for that gold which John had hid in the prison-wall, some had found it,
and taken it away.
And when we had been about seven weeks asunder,
John obtained that favor as to be with me,
but one night he was in danger of being murdered by a student,
who privily got to him when he was asleep, and took him by the neck,
and might have choked him, had not the Lord preserved him.

After that John wrote again to the governor,
and commended his wisdom in forbearing to proceed
so severely against us as some would have had him,
but that paper the inquisitor did also intercept, and he sent for me,
and threatened that he would help us to the gallows himself,
howbeit I have spared and helped you before, said he;
and about that time I did eat but little,
that I might be the better prepared to die the sooner,
if they should have been suffered to have hung me upon a hook by the ribs,
as it was their manner with some,
who lived in a most miserable pain for three or four days.

After that I wrote something to the governor, but the inquisitor did also intercept that,
and I spoke with the governor`'s secretary and his chamberlain,
who were two pretty discreet young men, and one of them told me,
how the inquisitor was made to give his lord our papers which he had intercepted;
and it appeared, that he was come into disfavor with the governor, and the chief-priest,
our great adversary, was in danger of being punished,
but for what cause we did not yet certainly know;
however that evening the chain was taken off from each of us,
and but a little left upon one leg.

After that came down the general-president with the deputy-chancellor and others,
to view the garrison, and they came riding by us where we were at work,
and one looking out of the coach, and seeing us not take off our hats,
cried '`These are the Quakers;`' and the same day was a new gallows made,
and we were called in, and by the way the marshal said, '`We were to go before a general,
and if we did not take off our hats, we should see what would become of us,
for the gallows was ready.`'

And coming before them, there sat a priest at the table, and said,
'`We had forfeited our lives by desiring to go over the river,`' etc.
But I told him, '`They thirsted after blood,
and the potentates of the earth hearkened unto them.`'
And as for us, we had no man but God to plead for us;
and many sophistical arguments he produced, as thereby to ensnare me,
but some of the rest desiring to speak with me, I regarded what he said the less,
and with much boldness I spake unto them.
And as for the president, who seemed to be the wisest among them, he called John to him,
and spoke French with him, and afterwards called me, and spake with me.
The deputy-chancellor asked me,`' Whether I would rather turn papist, or be hanged?
I said,`'I did not desire to have them put it to my choice.`'
The president asked, Whether I would not that all people were as I was?
I answered, and said.
Whatsoever is good in me, I wish them like me in that.
He asked.
Whether I would not they were all of my religion?
I said, I wished all might be faithful to that which they knew already to be good.
Then he caused them to bring us our hats again, which some had thrown off,
and when they had dined, they desired us to write for certificates,
and so went their way.

And upon a certain time colonel Fusch came riding by where we were at work,
and some Italian lords with him, who were intended for Rome,
and he proffered to send me with them if I pleased, or if I would be a Papist,
or Calvinist, (i. e. Presbyterian) he would procure my liberty, etc.
And many more temptations we had daily, which would be too long here to relate.
And often there came officers and asked us, What saith the Spirit now?
Hath the Spirit sent you to work?
And had he not done better to have counseled you to stay at home?
And doth he not yet tell you that you must be Catholics?
And when I had done speaking to them, and they not knowing how to defend themselves,
they would say,
'`Such heretics ought to be burned;`' and more bad words to the same purpose.

And when sixteen weeks were expired of our imprisonment, the Hungarian deputy-governor,
a bitter old man, came where we were at work, and said,
'`He must send us to Caesar;`' for John had before in his paper appealed unto him.

Then we went into the garrison, until four soldiers and an interpreter, and letters,
were ready, that went along with us, and there were iron-bolts put upon our feet,
and we put into a waggon.
And the interpreter told us, how he had heard the letter which was come concerning us,
but nevertheless, he said, we should not come into England.
So that whole night we rode,
and arrived the third day at the house of one called his excellency,
lord Francis of Nadasti, etc.
Judex Curias Hungariie,
the Emperor`'s majesty`'s active privy counselor and lord chamberlain,
etc. to whom the governor of Comora had given us over, it was supposed,
partly to make friendship with him, for they had been formerly at variance;
and when he came from his worship he caused us to be called, and asked me.
If we were Quakers?
I said,

'`Yea:`' He said, '`Very well.`'
And in the afternoon his wife looked out of a window, and asked me several questions,
and I had much freedom to answer her,
which she interpreted to some Hungarians that were with her:
and the next morning we were taken to the vice-king`'s parlour,
where the lords of that kingdom and of the other dominions were set about the table,
and John was ordered to go to one end by the secretary,
who seemed to be an understanding man, and he was partly reached by John`'s answers,
and he was forward to repeat them aloud to the archbishop and the rest;
and Nadasti asked me several questions, but hastily, about our rehgion,
of which we gave friends an account formerly.

And though they had little or nothing to say against our answers,
yet they passed sentence upon us, that we should be burned,
if we would not be instructed, and embrace their religion; for they had a law, they said,
which tolerated but three religions, viz. theirs, the Lutherans, and the Calvinists,
and whosoever brought a new religion there, was according to their law, to be burned;
and upon that we were sent away.
And John told me, The power of the Lord would divide them in their council,
as an Irish priest did afterwards tell him,
who was sent to require an account of our religion in writing, and when it was done,
the Irishman got an English copy of it, and said, '`He would tell them the contents of it,
and help us what he could;`' but we thought it would be the best that I translated it,
which accordingly I did, and I gave it Nadasti in his hand.

Afterwards they sent the priest to convert us, and there he read out of his catechism,
and asked John concerning the creed, pater-nosters, seven sacraments, mass, faith, hope,
love, patience, and more such like things, to which John answered him.
After that came down some priests, and asked us.
If we were come forth to sow our seed?
O, said the Irish priest, '`they cannot speak Latin;`' yet he and others know that I could.
And seeing they could not prevail with us there, we were sent to another place,
five Dutch miles from Wien, (the Emperor`'s seat) with two soldiers, by Nadasti`'s command,
and when we were come thither,
the priests gave order to put us in the hole with the Turks,
because they suspected us to be preachers, and by their instigation,
and with the consent of the court-master, (who told me,
that there should be wood and straw fetched to burn
us) did the soldiers take off our coats,
and searched our pockets, and took our books and papers, and the next day,
because we would not speak Latin,
nor take off our hats to their images in their churches
(so called) they set others upon us to ensnare us in words,
and strove to do it themselves, that they might have occasion to take away our lives,
which they often threatened to do,
and when they could not prevail with all their cunning baits,
nor make us bow to their worship, they manifested their cruelty farther,
in causing iron-shackles to be put upon our hands;
and though they were so little that I was forced even to cry out,
by reason of the extremity of pain, yet with force they thrust on the lock,
and beheld it with joy.

And in the hole we had scarce room to put forth our feet without touching the Turks,
whose feet were in the stocks, and hands in irons,
and necks and feet in iron-bands tied to the walls with strong chains.
Afterwards the priests being drunk at their feasts, sent for us to examine us farther,
and they said '`They could not believe but John was a preacher,
for an husbandman could not answer so readily.`'
And one of the chief of them told us, that they had several instruments of cruelty,
which they could also let us taste of; that they could burn men under their arms,
and put hot iron or copper-plates upon their breasts: he also told us,
that we should be sent down into Hungaria to be burned.
I spoke to one of the priests, and desired we might be dealt withal as men or Christians,
and might have a little straw or hay to lie upon, for we were worse used than the Turks.
'`Yea,`' said he, '`we prefer them before you.`'
And about that time they proffered us a drink in an urging manner,
which it was supposed was made to poison us; and John refusing to take it,
one of the priests said, _Suspectum est nos._
One of the priests asked me, If I had a wife?
I said, '`I never knew woman-kind.`'
He said, '`The heretics had not that grace of chastity, neither had I any grace from God.`'
The Turks, he said, had some grace, they were good soldiers,
and somewhat else he said of them.
Another priest asked me, '`How I had lain in the hole,
and how the iron-shackles pleased me?
And threatened we should be put into the miry-dungeon in the tower,
and called me filthy names in the Hungarian tongue, before the people.

Howbeit, blessed be the Lord, we had slept well in the shackles,
upon the besoms in a corner; yea, better than could be expected,
though at the first my wrist-band pained me much.
And when the priests and others were seeking much to discourage us,
I was upon a time setting musing upon a bench, and thinking Lord help us,
what will be the end of this, and whether they shall have power to murder us here,
where few may know of it, for in this place are no other sects to be witnesses,
as at Comora and Presburgh, and then my mind was turned inwards,
and I was as if I had slept;
and on a sudden it was as if I had seen a man all clothed in white,
sitting on a milk-white horse, riding in posthaste to me-wards,
as if he were hastening to rescue me; then I looked up and was pretty much comforted,
thinking it was from the Lord to encourage me, lest I should be too much cast down.
And the very same day there came tidings from the earl,
that he was displeased at what they had done, as he told his barber,
to whom he showed the papers which John had writ; and the barber hearing of us,
together with his perusing the aforesaid papers, the witness of God was reached in him,
which had stirred much in him in the time of his youth,
by which he was stirred up to declare against the
darkness and deadness of the brethren`'s forms aforesaid,
among whom he had been educated;
neither could he be well satisfied in himself until he came to see me,
and after some discourse with us, was yet more convinced, and he told us,
how that the earl did judge that the priests had been drunk, which was true,
both with rage and wine.
Then did the streams begin to turn, and some desired our favor,
both the officer and priest began to flatter us,
with others who had been high against us;
and then they had no more power to put us into the
hole to exercise their cruelty upon us,
as they had done before, which was no small cross to their wills.

After that there came a spiritual lord (so called) an Englishman, from Wien,
and he asked John, If we were come to plant our religion?
saying, '`Sects had occasioned much mischief in England, but now they would be rooted out.`'
But John said, '`The love of God can reconcile them again.`'
'`A pox o`' God, take that love,`' said he, with other such unsavory words,
whereby he showed himself to be carnal indeed, although he was called spiritual.
Another came to us, who was called Frater Valentine,
and speaking with us concerning the bible, he said,
'`It had brought many thousands into hell,`' and reading a paper of John`'s,
which he had writ to the earl and council, wherein John showed, how he was an Englishman,
and forasmuch as there was no discord betwixt

England and the Empire,
he knew not why an Englishman coming into any of the emperor`'s dominions,
to visit a sort of people, and to spend his money, should be so used, etc.
But said the aforesaid Frater, '`They ought to be beheaded,
for if they had done so to Luther at first, said he,
there had not been so many Lutherans or heretics at this day.`'
Farther he said,
'`We were forerunners of Antichrist;`' and this rumor went through the kingdom and elsewhere,
that Antichrist was taken, and was at Nadasti`'s court.
However, soon after it was thought we might have been set at liberty,
but that the priest did so much incense the earl against us,
and we having writ according to order for certificates, which in due time came to hand,
from friends in Holland, and they were of good service,
with the king`'s proclamation for setting Friends at liberty;
but the earl was taken exceeding sick at Wien, so that the thing was not then effected.

In the mean time Adam Bien, the earl`'s barber, had desired, unknown to us,
that we might have the liberty to come forth, and be in his house, the winter being cold,
and we in a cold guard, where the doors stood open all day, and much of the night;
and he proffered his own person in our stead, if we should run away.
Howbeit, we were not free to be so burdensome to him, though he had obtained the thing,
but chose rather to content ourselves where they had appointed us,
that the burden might come the heavier upon them,
that they might be the sooner weary of us;
and what storms and assaults we had from the priests and soldiers, and others with them,
and how they sought to ensnare us, would be too long here to relate:
but in the mean time we were often refreshed through Adam`'s and his wife`'s love,
together with a sense of the love of God, and of friends who were afar off;
and our adversaries might have been the worse to us,
but that many of them there stood in pretty much awe of Adam,
who stood in his integrity over them, for he having such daily access to the earl,
and knowing most of them at court guilty of more or less,
they did therefore dread him the more.
And sometimes we did go to his house,
and had sometimes opportunity to speak with some of the aforementioned brethren,
who were warned of that sore desolation which is since come upon many of them.
For of nine families there is but one remaining, and the rest were burned,
with the value of many thousands in them,
and above two hundred of the men were slain and taken captive.

And about that time there was a gentleman (so called)
appointed for to bind and carry me away,
whose waiting-man came to me, and gave me two big glasses,
as if I should have gone with him to have fetched some wine or something else;
but presently I was sensible all was not right or well,
for he had a great cudgel in his hand,
and that same morning he had given me very bad words,
and when I had followed him into the fields, there came many sleds,
(for the snow was so deep that wagons could not travel,) and when the first came at us,
the man that had given me the bottles, caused me to lay them down,
and get upon one of the sleds, and he returned back again.
The other, who had so much threatened me formerly, came towards me,
and then I was very sensible of mischief intended by them,
and then I was troubled for John and Adam,
lest they should have avenged themselves on them, through pretending I had been run away,
(for they were become full of envy against Adam for his love to
us,) so I resolved to endeavor to get back to the town;
thinking, that if they did stop me, it might be the better manifest I was not run away.
But when I essayed so to do, that wicked man caught me by the hair in a great fury,
and shed pretty much of my blood, and I thought he had quite struck out one of my eyes,
and he pulled me down in the snow, and did sorely abuse me,
and bound my arms with thongs, as also my feet, and bound me so in the sled,
that I hung also by the arms and feet with my face in the hay,
neither knew I to the contrary,
but that they would have murdered me in that wood which was close by; but O, thought I,
that I might but live one quarter of an hour,
that peradventure some might pass by and see me,
whereby Adam and John might come to know what was become of me;
afterwards we came by a gallows, where I thought they might have executed me,
but there we passed by, and people coming that way, they muzzled me with a cloak,
and one sat upon me till the people were passed by.
Howbeit, I hearing their feet in the snow,
called to them and desired them to acquaint the aforesaid barber that I was there;
but then did the soldier beat me sore again,
the other having charged him not to suffer me to say any thing.
Then where we came at night, the irons were put on my feet, and a long big chain,
tied on high about a beam, was put about my neck all night.
Next morning we came to a village, when I would gladly have spoken with one,
but they caused me to lie down until we were passed both village and castle,
and so we travelled towards a place in the wilderness, as I was informed,
and finally we came to a place where they were building a new cloister;
but the prior not being at home,
the other priests would not take me in without his order,
so that night I was put in chains as before,
and the next morning was led up to the castle,
and was ordered to be put in a dark hole where no light was,
for he that came along with me bade them blindfold me, and put me in a deep dungeon,
and give me but little bread and water, and that none should tell of me,
and there being a Jew, he was forbidden on pain of death to say any thing;
and I was soon after put into an hole where there was but little light,
and there I was four days and four nights in cold frosty weather,
and it was much I was not starved.
But after the prior wrote home to the monks, I was sent for;
and when they used their ceremonies, and sprinkled their infants, etc.
I did not conform to them in their kneeling and the like, at which they marveled,
but said not much in my presence, but when I went to my lodging, they said,
I was a bad dog, and a stubborn rogue;
and sometime they sent for an armed soldier to guard me, or rather to afright me.
And when I had been there about twelve days, the prior came home,
and it seems he had some orders to rack me for writing letters at Puttendorf:
then did the prior send for me, and asked me concerning our coming into the country,
and to what end, and concerning some points of our religion, to which I answered,
him according to truth; but he said, '`That was not enough,
we must believe that the Pope was Christ`'s Vicar,
and that he and they had power to bind and loose,`' etc.

And when we had reasoned a while together, he said,
'`I must have my habitation again in the castle,
and that he would come sometimes by me and bring the bible.`'
And afterwards he came up sometimes to see his corn and provision,
but had little delight to speak with me; but once he called me where he sat, and told me,
'`The earl had desired him to inform me, that I should not marvel that he sent me thither,
for it was not for my sake alone, but for seducing so many souls,
and if it could be proved I was come on such purpose,
I should be laid on an heap of wood, meaning, I should be burned.
In the mean time I bore my testimony against their fruits of covetousness, pride,
persecution, etc. and against their weapons, which were not like Christ`'s,
nor his apostles; and with this some that stood by were affected;
and many things passed betwixt us at that time, which I shall not now rehearse;
and afterwards I was told, how he had said to some, he had spoken to many learned men,
but never did any answer him as I did.
And afterwards I had more liberty and more respect showed me, and the report went,
how that none that dealt with me could gain at my hand.

And after I was so treacherously taken away, as before mentioned, from Adam and John,
the earl told Adam, I was run away, and he might see where to find me; he said,
'`He could not believe that, but afterward he got intelligence where I was,
and writ some lines by the officer of the castle, but he was unwilling to give it me,
but gave me bad language, saying, '`He had appointed a hangman to flea off my skin,
if I did not turn papist; but finally, I got a sight of it,
and he told me how closely the design of my removal was carried on,
insomuch that but three did know of it at first.
He also told me, how he had longed for an opportunity to send me bodily necessaries,
which he afterwards did, and gave orders to give me bread enough on his account:
and finally, the earl being sick, nigh unto death,
Adam obtained a promise of him to let us have our liberty.
But after that he in whose custody I was had set me free,
he kept me six weeks to help the masons,
and promised to tell me a good message when he returned, if I would be diligent.
And afterward he took me aside, and told me, '`The Earl would have me informed,
that if I would be a catholic I should have good service and preferment, but if not,
however he could not detain me, for he had prisoners enough besides.`'
But this was concluded, if I was found afterwards in Hungaria or Austria,
I should be burned, and my companion also.

And before I was brought from thence he did try me many ways,
for he would have me learn to shoot, and hath tied match about my fingers,
and hath struck me to make me hold the musket.
But I was like a fool, and they made themselves sport with me,
and several times would put pistols in my hands and bid me shoot,
sometimes in seeming earnest, and sometimes to make sport before strangers.

Afterwards I was examined about my religion,
and they thinking such a liver would adorn their profession,
they did threaten to have my tongue cut out if I would not be a papist;
and afterwards a priest was sent for to instruct me, and convert me,
but when he could not prevail a tub was made ready,
and a rope put through the ears of it, and I was set in it, and they said,
I should be let down into a well thirty-six fathoms deep above the water,
and I knew not but that it might have come to pass,
howbeit they drew the rope but over a beam to affright me, and I falling out of that,
they laid me cross over the saddle of an ass, and drew me up, and turned me hard about,
and then let it go with a whirl to make my head dizzy; but I was silent,
and valued it little, whereat they marveled, as if I had been past all feeling.
And from thence they carried me to another place,
and there they locked my neck and feet near together, and my hands spread abroad,
and locked in a thing wherein they torture the Turks
to make them confess of what ability they are,
or their friends, whereby to get great ransom, and some asked, if it was painful?
and others said, they committed more sins than they did profit thereby.

And at another time I was put in a wheel which was made for the well,
and they caused the soldiers to turn it about, that I might tumble to and again in it,
which might have done me much hurt, but that I held fast on the side of it,
yet however one of my elbows was in great danger of being sorely harmed,
and afterwards I was much threatened, as if they would have racked me again.

And about that time I was told by the secretary and others, that the emperor,
by reason of the hot wars that were in the country,
had given orders to set all the Christian prisoners at liberty,
so that it was thought they could not detain us much longer.

And about the 4th of the seventh month, 1663,
I was carried into the country with the prior and a priest from Rome, and others,
and when we came to the water which parts the two countries, we parted;
and the aforesaid Adam had ordered one of them to give me some money to bear my charges,
and he gave me but five groshees, which is about the value of ten-pence.
After that I came to a place called Pink-field, where several Lutheran barons,
and others, came to see me; and many things they asked me, to which,
according to freedom, I answered.
And I had a desire to have gotten to Wien, but they told me,
'`It was impossible for me to pass, that would not take off my hat,
besides there were abundance of soldiers that way;`' and
one desired me to stay by him till I could have opportunity.
Afterwards I was directed to go through Stoyermack to Gratz, a great city,
where there were merchants from Noremberg at the fair, and one of them it was thought,
might be somewhat of my opinion, and thither I went,
but going in at the gates was called back, and was not suffered to go in,
for they were fearful of the enemy, and suspicious of strangers.

The next day, when I saw I could not meet with the aforesaid merchant,
I resolved to travel on my journey,
and to trust to the Lord to take care for my sustenance, who had often done it,
when as to the outward there was little appearance of relief.
And in my journey I inquired for the privatest ways, which I found to be most peaceable.
Howbeit, when I came to the west-end of Austria I was twice stopped,
as if I might have been sent from the Turks to spy out and burn towns,
but when I produced my certificate I was suffered to pass,
but charged not to tarry at their town,
and after that I avoided coming into cities and villages as much as I could,
and so got forward, though not without difficulty.
And I have great cause to thank the Lord for his goodness, for I did not much want food,
but through mercy got either bread or fruit, or something;
for in those countries they are accustomed to give travellers and tradesmen bread,
and lodging in their barns,
and sometimes I told them how I had been robbed by soldiers and abused,
and then their hearts were moved so much the more with pity towards me.

And I proceeded on my journey,
and through mercy got about the 2d of the eighth
month into some part of the Paltz in Germany,
and came through Heidelberg and Manheim,
and upon the 7th of the same month I arrived at Christein among friends,
and being there kindly entertained, and abundantly refreshed, I tarried there some weeks,
waiting to have heard of John or from Adam.

Now the last news which I had of John was by dear Adam`'s letter,^
footnote:[That letter signified that John Philly was set at liberty,
and departed toward Germany on the 6th of the seventh month, 1663]
which I hope may be come to thy hands before this.
Several more passages might be set down, and what we suffered together,
and since we parted, but this for the present may suffice till another opportunity.
Farewell.

[.signed-section-closing]
Thy dear friend in the love and light of God,

[.signed-section-signature]
William Moore.

[.signed-section-context-close]
Amsterdam, the 11th month, 1663.

--

The narrative contained in the preceding letter,
exhibits many instances of that protecting Providence of God,
which supports and accompanies those who in a holy obedience to
the commands of his spirit are devoted to answer its requirings.
The many dangers and trials through which they passed,
the despite the tortures with which their enemies
were suffered to prove their meekness and patience,
the cruel and shameful deaths wherewith they were threatened,
give the clearest demonstrations of their steadfastness
in the faith from which they could not be moved;
for they looking unto Jesus, the author and finisher of their faith,
who for the joy that was set before him endured the cross, despising the shame,
and is set down at the right hand of the throne of God,
and considering him that endured such contradiction of sinners against himself,
were not weary, nor did faint in their minds.
See Heb.
xii. But in all their afflictions were supported by the consciousness of their integrity,
and the consolations of the Spirit of God, raising their spirits above the fear of man,
and enabling them to persevere in a steady confession of their faith,
and supplying them with that wisdom which is from above,
whereby they were enabled to withstand the subtle devices
and snares of those who sought their ruin and destruction:
from which they were preserved by the power of the Lord,
the only preserver of those that put their trust in him,
whom he delivers out of the hand of the wicked,
and out of the hand of the unrighteous and cruel man. Ps. 71:4.

[.the-end]
The End
