[short="To King George"]
== To George, King of Great Britain, Ireland, etc. Prince Elector of Brunswick, Lunenburg, etc.

Great and Mighty Prince,

As there is a great variety in the inclinations of men in general,
so it is particularly remarkable in those who addict
themselves to the studies of nature and human literature:
for some with great eagerness inquire into the operations of nature;
and the natural causes of things: some endeavour to dig up antiquities from the dark,
by searching out the signification of statues, the inscriptions of antique stones,
and old and almost worn out medals; and others peruse with unwearied diligence,
the histories both of modern and ancient times; and not without good cause;
for history is not unjustly called the looking-glass of human life;
not only because it showeth unto us matters of fact,
which are either commendable or reproveable, and we behold therein that which is past,
as if it were present;
but also because from things which have already happened
we may learn what is best for us to do,
and what we ought to avoid.
And, therefore, great benefit may be reaped from the reading of histories,
besides the pleasure which the variety of transactions affords to our senses,
when matters are accompanied with singular circumstances, and unexpected events.

Now, since the reading of historical treatises was one
of the most pleasant diversions of my youth,
this drew me when I attained to some maturity of age,
to inquire after many things that had happened in thy kingdoms and dominions,
which by many were almost forgotten.
And having gathered great store of very remarkable cases,
which I thought worthy to be kept upon record, and not buried in oblivion,
I was induced to compose an history, which contains such rare occurrences,
and unusual matters as I believe are not easily paralleled.

And after a long and difficult labour, having at length finished the work,
so far as to expose it to public view; and then thinking to whom I should dedicate it,
it presently came into my mind, that this could not be done more suitably to any,
than to the king of these countries, which are the chief theatre of this history;
and the rather, because therein is described the rise of a people,
who are no small part of his faithful subjects,
(for so I may safely call them,) since they never, how much soever wronged and oppressed,
offered any resistance to the government;
and when for conscience-sake they could not comply with what was required of them,
by patient suffering they showed their subjection and obedience to the higher power.
Nay, when opportunity was offered to revenge themselves of their enemies,
even then they would not, but left it to the Lord:
and thus at all times they behaved themselves like a peaceable people.

And since I have also had occasion in this history to mention
some illustrious branches of thy royal family,
to whom could I with more justice offer this work, than to thee, O King of Great Britain,
who, having already made thyself gloriously renowned by thy eminent clemency,
bestowed even upon such who by their unnatural rebellion had forfeited it,
didst rather choose to establish thy throne thereby, than by severity,
and thus effectually to observe this lesson of the wisest of kings,
"`Mercy and truth preserve the king, and his throne is upholden by mercy.`"

All this hath emboldened me, great king, to dedicate this work to thee, with due regard,
and in a way of humble address to approach thy royal presence.
Be pleased, therefore, according to thy wonted goodness to excuse this modest freedom;
and to know, that though it be offered by a foreigner,
yet it proceeds from him who heartily wisheth that God may vouchsafe
thee long to reign in peace and tranquillity over thy subjects;
and when removed hence from an earthly and perishing diadem,
to grant thee an heavenly and incorruptible crown of glory:
which is the unfeigned desire of,

Thy affectionate and sincere well-wisher,

William Sewel.
