== Chapter XV

1664.

Trial of G. Fox at Lancaster Assizes--Arbitrary course of the Judges--Recommitment
to prison--Cruelties practised on G. Fox in prison--G. Fox writes to the Emperor,
Kings of France and Spain,
and to the Pope--Trial of F. Howgill at Appleby--Account of J.
Camm--Account of J. Audland--Second trial of F. Howgill,
and his sentence--"`Act to prevent and suppress Seditious Conventicles`"--Trial of Quakers
at Hartford for attending meeting--Sentence of banishment--Trial of Quakers at Heck`'s
Hall under the Conven ticle Act--Determination to destroy the Quakers by severity of
punishment--Faithfulness under suffering--Large numbers taken from meetings,
tried, and sentenced--Exhortations to Constancy--Warning to the King and Parliament

In the foregoing year we left G. Fox in Lancaster prison, where at the sessions,
the oath of allegiance being tendered to, and refused by him,
he was brought to his trial in the month called March, which begins the year 1664.
Being brought to the bar before judge Twisden, he said, "`Peace be amongst you all.`"
At which the judge looking upon him, said,
"`What! do you come into the court with your hat on?`"
Whereupon the jailer taking it off, G. Fox said,
"`The hat is not the honour that comes from God.`"
Then said the judge, "`Will you take the oath of allegiance?`"
G+++.+++ Fox answered, "`I never took any oath in my life.`"
"`Well,`" said the judge, "`will you swear or no?`"
G+++.+++ Fox replied, "`I am a Christian, and Christ commands me not to swear;
and so doth the apostle James likewise; and whether I should obey God or man,
do thou judge.`"
"`I ask you again,`" said the judge, "`whether you will swear or no?`"
To which he made answer, "`I am neither Turk, Jew, nor Heathen, but a Christian,
and should show forth Christianity.
Dost thou not know, (thus he went on,) that Christians in the primitive times,
under the ten persecutions, and some also of the martyrs in queen Mary`'s days,
refused swearing, because Christ and the apostle had forbidden it?
Ye have experience enough, how many men have sworn first to the king,
and then against him.
But as for me, I have never taken an oath in all my life;
and my allegiance doth not lie in swearing, but in truth and faithfulness:
for I honour all men, much more the king.
But Christ, who is the great Prophet, who is the King of kings, the Saviour of the world,
and the great Judge of the whole world, he saith, I must not swear.
Now the point is, whether I must obey Christ, or thee.
For it is in tenderness of conscience, and in obedience to the command of Christ,
that I do not swear.
And we have the word of a king for tender consciences.`"
G+++.+++ Fox having spoken thus much, asked the judge, if he did own the king?
To which he said, "`Yes, I do own the king.`"
"`Why then,`" said he, "`dost thou not observe his declaration from Breda,
and his promises made since he came into England,
that no man should be called in question for matters of religion,
so long as they lived peaceably?
Now if thou ownest the king, why dost thou call me into question,
and put me upon taking an oath, seeing thou, nor none,
can charge me with unpeaceable living?`"
The judge looking angry, said, "`Sirrah, will you swear?`"
To which G. Fox told him, "`I am none of thy sirrahs; I am a Christian; and for thee,
who art an old man and a judge, to sit there and give nicknames to the prisoners,
doth not become either thy grey hairs or thy office.`"
The judge being a little more cool, after some words to and fro, said, "`G. Fox,
say whether thou wilt take the oath, yea, or nay?`"
To which he replied, "`If I could take any oath at all, I should take this:
for I do not deny some oaths only, or on some occasions, but all oaths,
according to Christ`'s doctrine, who said, '`Swear not at all.`' Now if thou,
or any of you, or any of your ministers or priests here,
will prove that ever Christ or his apostle, after they had forbidden all swearing,
commanded Christians to swear, then I will swear.`"
None of the priests offering to speak, the judge said, "`I am a servant to the king,
and the king sent me not to dispute with you, but to put the laws in execution;
and therefore I tender the oath of allegiance.`"
G+++.+++ Fox continuing to refuse swearing, was sent again to prison.
Two days after, being brought again before the judge, it was asked him,
whether he would traverse or submit?
To which G. Fox said, he desired he might have liberty to traverse the indictment,
and try it.
Then order was given to take him away, and he was kept in prison till the next assizes.

Being prisoner in Lancaster castle,
there was much talk of the Turk`'s great progress in Hungary,
there being at that time a war between the Emperor and the Turks; and many being afraid,
he said to some, that walking once in his chamber,
he saw the Lord`'s power turn against the Turk, and that he was turning back again.
And within a month after news came that he was defeated.
Another time, as he was walking in the room, with his mind upon the Lord,
he saw an extraordinary great light, and looking up, he beheld an angel of the Lord,
with a glittering sword stretched southward, which shone so bright,
as if the court had been all on fire.
Of which I have for proof what he mentions of it in his journal,
and also another small book he gave out with the title of A Warning to England.
Not long after a war broke out between England and Holland,
and some time after the pestilence appeared at London,
(which lies southwardly from Lancaster,) and after
two years that city by the fire was turned into rubbish.

But I return to the Lancaster assizes.
Margaret Fell, who was now a widow,
was also under confinement for refusing the oath of allegiance.
And G. Fox being in prison, wrote several papers to the magistrates,
in which he manifested the evil of persecution, and exhorted to virtue and piety.

In the month called August, the assizes were held again at Lancaster.
G+++.+++ Fox being brought thither,
(judge Turner then sitting on the crown-bench,) and being called to the bar,
the judge asked the justices,
whether they had tendered him the oath at the foregoing sessions?
They saying they had, and having sworn it, the jury were sworn too.
Then the judge asked him, whether he had not refused the oath at the last assizes?
To which he answered, "`I never took an oath in my life;
and Christ the Saviour and Judge of the world said,
'`Swear not at all.`'`" The judge seeming not to take notice of this answer,
asked him whether or no he had not refused to take the oath at the last assizes?
G+++.+++ Fox maintaining the unlawfulness of swearing, the judge said,
he was not at that time to dispute whether it was lawful to swear,
but to inquire whether he had refused to take the oath, or no.
G+++.+++ Fox then signifying that he did not disapprove the things mentioned in the oath, said,
"`Plotting against the king, and owning the Pope`'s, or any other foreign power,
I utterly deny.`"
"`Well,`" said the judge, "`you say well in that: but did you deny to take the oath;
what say you.`"
"`What wouldest thou have me to say?`"
replied he, "`I have told thee before what I did say.`"
After some more words from both sides, the indictment was read.
G+++.+++ Fox having informed himself of the errors that were in it, said,
he had something to speak to it, for there were many gross errors in it.
The judge signified that he would not hear him,
but when he was at the point of giving judgment, the jury going out, soon returned,
and brought him in guilty.
Whereupon he told them, that both the justices and they too had forsworn themselves;
which caused such confusion in the court, that the pronouncing judgment was delayed.
Margaret Fell being next brought to the bar, was also declared guilty.

The next day she and G. Fox were brought up again to receive sentence.
Her counsel pleading many errors in her indictment, she was set by;
and G. Fox then being called, showed himself unwilling to let any man plead for him;
which seemed to make some stop; yet he was asked by the judge, what he had to say,
why he should not pass sentence upon him.
At which he told him, "`I am no lawyer, but yet I have much to say,
if thou wilt but have patience to hear?`"
Thereupon those on the bench laughed, and said, "`Come what have you to say?`"
Then he asked the judge whether the oath was to be tendered to the king`'s subjects,
or to the subjects of foreign princes.
To which the judge said, "`To the subjects of this realm.`"
"`Then,`" said George, "`look on the indictment,
and ye may see that ye have left out the word subject:
and not having named me in the indictment as a subject,
ye cannot premunire me for not taking the oath.`"
They then looking to the statute, and the indictment, saw that it was as he said,
and the judge confessed that it was an error.
Next G. F. told him, he had something else to stop judgment;
and he desired them to look what day the indictment said
the oath was tendered to him at the sessions there?
They looking, said it was the eleventh of January.
Then he asked, "`What day of the week was that sessions held on?`"
"`On a Tuesday,`" said they.
To which G. F. said, "`Look in your almanac,
and see whether there was any session held at Lancaster on the eleventh of January.`"
They looking, found that the eleventh day was the day called Monday,
and that the sessions were on the day called Tuesday,
which was the twelfth day of the said month: "`Look ye now,`" said he,
"`ye have indicted me for refusing the oath in the quarter-sessions
held at Lancaster on the eleventh day of January last,
and the justices have sworn that they tendered me
the oath in open sessions here that day,
and the jury upon their oath have found me guilty thereupon;
and yet ye see there was no sessions held at Lancaster that day.`"
The judge, to cover the matter, asked,
whether the sessions did not begin on the eleventh day?
To which some in the court answered, "`No; the sessions held but one day,
and that was the twelfth.`"
Then the judge said, this was a great mistake, and an error.
Some of the justices grew so angry at this,
that they seeming ready to have gone off the bench, stamped, and said,
"`Who hath done this?
Somebody hath done this on purpose.`"
Then said G. F. "`Are not the justices here that have sworn to this indictment,
forsworn men?
But this is not all;
I have more yet to offer why sentence should not be given against me,
in what year of the king was it, that the last assizes,
which was in the month called March, was holden here?`"
To this the judge said it was in the sixteenth year of the king.
"`But,`" said G. Fox, "`the indictment says it was in the fifteenth year.`"
This was also acknowledged to be an error:
but both judge and justices were in such a fret, that they knew not what to say;
for it had been sworn also,
that the oath was tendered to G. Fox at the assize mentioned in the indictment,
viz. in the fifteenth year of the king, whereas it was in the sixteenth;
which made G. Fox say, "`Is not the court here forsworn also,
they having sworn a whole year false?`"
Some other remarkable errors he showed, which I, having no mind to be tedious,
pass by with silence.

G+++.+++ Fox then desiring justice, and saying, that he did not look for mercy, the judge said,
you must have justice, and you shall have law: which made him ask,
"`Amos 1 now free from all that hath been done against me in this matter?`"
"`Yes,`" said the judge; but then starting up in a rage he said,
"`I can put the oath to any man here; and I will tender you the oath again.`"
G+++.+++ Fox then telling him,
that he had examples enough of yesterday`'s swearing and false swearing;
"`For I saw before my eyes,`" said he,
"`that both justices and jury forswore themselves;`"
yet the judge asked him if he would take the oath?
But he replied,
"`Do me justice for my false imprisonment all this while;`" for he had been locked up,
as was well known, in a wet and cold room, and therefore he said,
"`I ought to be set at liberty.`"
At which the judge said, "`you are at liberty, but I will put the oath to you again.`"
G+++.+++ Fox then turning himself about, said to the people, "`Take notice, this is a snare;
but I ought to be set free from the jailer, and from this court.`"
But the judge instead of hearkening to that, cried, "`Give him the book.`"
G+++.+++ Fox then taking the book, and looking in it, said, "`I see it is a bible,
and I am glad of it.`"
In the meanwhile the jury being called by order of the judge, they stood by;
for though they had desired, after they had brought in their former verdict,
to be dismissed, yet he told them, he could not dismiss them yet,
because he should have business for them; and therefore they must attend, and be ready.
G+++.+++ Fox, perceiving his intent, looking him in the face, which made him blush:
nevertheless he caused the oath to be read,
and then asked G. Fox whether he would take the oath or no; to which he said,
"`Ye have given me a book here to kiss, and to swear on; and this book says,
kiss the Son; and the Son says in this book,
'`Swear not at all,`' and so says also the apostle James: now I say, as the book says,
and yet ye imprison me, for doing as the book bids me.
How chance ye do not imprison the book for saying so?
How comes it that the book is at liberty amongst you, which bids me swear not?
Why do not ye imprison the book also?`"
Whilst he was speaking thus, he held up the bible open,
to show the place where Christ forbids swearing.
But the book was taken from him, and the judge said, "`No,
but we will imprison George Fox.`"

This case was so singular, that it was spread over all the country, as a by-word,
that they gave G. Fox a book to swear on, that commanded him not to swear at all,
and that this book, viz. the Bible, was at liberty, and he in prison,
for doing as the Bible said.
But the judge urged him still to swear; to which G. Fox said,
"`I am a man of a tender conscience; consider therefore,
that it is in obedience to Christ`'s command that I cannot swear:
but if any of you can convince me,
that after Christ and the apostle had commanded not to swear,
they did alter that command, and commanded Christians to swear,
then ye shall see I will swear.`"
And he seeing there several priests, said, "`If ye cannot do it, let your priests do it.`"
But none of the priests said any thing; and the judge said,
"`All the world cannot convince you.`"
To which he replied, "`How is it like the world should convince me?
For the whole world lies in wickedness: but bring out your spiritual men,
as ye call them, to convince me.`"
Then the sheriff and the judge said, that the angel swore in the Revelations.
To which G. Fox replied, "`When God bringeth in his first-begotten Son into the world,
he saith, '`Let all the angels of God worship him;`' and he said,
'`Swear not at all.`'`"--"`Nay,`" said the judge, "`I will not dispute.`"
Then he told the jury, it was for Christ`'s sake that he could not swear;
and therefore he warned them not to act contrary to that of God in their consciences,
because they must all appear before his judgment seat.
After some more words spoken, the jailer took him away.

In the afternoon he was brought up again:
and the jury having brought him in guilty of what he was charged within the indictment,
viz. his not taking the oath, the judge asked him, what he had to say for himself.
He then desired the indictment to be read;
since he could not answer to that which he had not heard.
The clerk reading it, the judge said, "`Take heed it be not false again.`"
But the clerk read it in such a manner, that G. Fox could hardly understand what he read.
And when he had done, the judge asked G. Fox what he had to say to the indictment.
To which he said, "`At once hearing so large a writing read, and that at such a distance,
that I could not distinctly hear all the parts of it;
I cannot well tell what to say to it: but if you will let me have a copy of it,
and give me time to consider, I shall answer it.`"
This put the court to a little stand; but at length the judge asked him,
what time he would have?
And he answered, "`Till the next assize.`"
"`But,`" said the judge, "`What plea will you make now; are you guilty, or not guilty?`"
To which he replied,
"`I am not guilty at all of denying swearing obstinately and willfully:
and as for those things mentioned in the oath, as jesuitical plots, and foreign powers,
I utterly deny them in my heart: and if I could take any oath, I should take this;
but I never took any oath in all my life.`"
To this the judge returned, "`You say well; but the king is sworn,
the parliament is sworn, I am sworn, the justices are sworn,
and the law is preserved by oaths.`"
On which G. Fox told him, they had had sufficient experience of men`'s swearing,
and had seen how the justices and jury swore wrong the other day: and continued he,
"`If thou hast read in the Book of Martyrs, how many of them did refuse to swear,
both within the time of the ten persecutions, and in bishop Bonner`'s day,
thou mayest see that to deny swearing in obedience to Christ`'s command,
is no new thing.`"
To this the judge said, he wished the laws were otherwise.
G+++.+++ Fox said then, "`Our yea is yea, and our nay is nay:
and if we transgress our yea and our nay, let us suffer as they do, or should do,
that swear falsely.
This I have offered to the king, and the king said it was reasonable.`"

After some further discourse, G. Fox was committed to prison again,
and Colonel Kirby ordered the jailer to keep him close,
and to suffer nobody to come to him, as one that was not fit to be discoursed with.
The jailer did not scruple to follow this order, for he locked him up in a smoky tower,
where the smoke of the other prisoners came up so thick,
that sometimes one could hardly see a burning candle;
so that there seemed to have been an intent to choke him;
for the turnkey could hardly be persuaded to unlock
one of the upper doors a little to let out the smoke.
Besides this hardship, in wet weather it rained in upon his bed to that degree,
that his shirt grew wet.
In this pitiful condition he lay during a long cold winter, which so afflicted him,
that his body swelled, and his limbs were much benumbed.
Here we will leave him till he was brought again to his trial,
which was not before the next year.

But before I part with him, I must mention,
that some time before he had written several papers to the emperor,
the kings of France and Spain, and also to the pope.
These writings were by somebody else turned into Latin, and so given out in print.
In these he levelled chiefly against persecution for religion`'s sake.
He reproved the king of Spain more especially, because of the inquisition,
and the burning of people: and he did not spare the pope,
as being the spring of these evils, saying,

Innocent blood hath long cried for vengeance to the Lord:
the earth almost swims with innocent blood; and the cry of it is heard.
Your frozen profession, and your cold winter images being set up in your streets,
the Lord God of power and death, and of heaven and earth, will be avenged on thee,
and you all; his day is approaching.
Ye great and rich cardinals and pope, ye have been fed like fat hogs;
and seeing that thou wouldest not receive the Lord`'s messengers,
but threw them in prison, and in your inquisition,
it may be the Lord may give you a visit another way, for his dread is gone out,
and his zeal is kindled against you.--The fields
are sprinkled with the blood of the innocent,
and ye are the aceldama, or the field of blood.
But the Lord is coming to take vengeance upon you; his hand is stretched over your heads,
and his power is gone over you; with that he will rule you, and smite you down,
and bring you that are lofty from your seats, and abase your pride,
and take the glory to himself.--How much blood, which is unmeasurable,
and cannot be measured here, have ye drank since the days of the apostles,
and made yourselves drunk with it!
But now is the indignation and wrath of the Almighty come and coming upon you;
and thou pope must feel it.
Tremble therefore, thou pope, tremble, fear, and quake thou pope, tremble ye cardinals,
tremble ye jesuits, tremble ye priors, tremble ye monks and friars, of what rank soever,
for the army of the Lord God is coming over you, by whom ye shall be taken,
and dashed to pieces.

These are but small sparkles of that flame which G. Fox blew against the pope,
intermixing his writings with many demonstrations,
that the Romish church was the whore of Babylon,
and that she it was that had defiled herself with idolatry and superstition,
and had bathed herself in the blood of the saints,
having furiously attacked them with sword and fire.
This he concluded with these words:

The plagues of God will be thy portion, O pope, who hath deceived the nations:
and all ye jesuits and cardinals, howl, for your misery is coming,
the mighty day of the Lord God upon you all; the Lord God,
who will be worshipped in spirit and in truth, and with none of your inventions.

Thus G. Fox wrote in that day to the pope and his counsellors;
and no wonder that he paid dear for this sharp language
against the head of the church of Rome;
for it may be believed, that a great many of the court party, in those days,
were either concealed Papists, or favourers of them: and yet among the national clergy,
and even those of other persuasions,
many branded the Quakers with the odious name of secret Papists,
thereby to make them incur the hatred of the people.

Now I return to Francis Howgill, whom in the foregoing year we left in prison at Appleby.
It was in the forepart of this year that he was brought to his trial.
Being come into court before the judges sat, he spoke to the clerk of the assizes,
and told him, he did not know whether they expected his appearance then or not:
the clerk said, "`You have done well,`" and that he would acquaint the judge,
and he should only engage to him to appear the next assizes,
to answer the indictment against him, and that he should not appear in court;
Francis bid him do what he would.
In the meantime Sir Philip Musgrave, (so called,) a great adversary to the Truth,
and the great and chief prosecutor of Francis, had informed the judges against him,
that he was a dangerous person, a ringleader,
and a keeper up of meetings of dangerous consequence,
and destructive of the peace of the nation;
so then they concluded he should appear in court; and so the clerk informed him,
and told him about what time he should be called.
So the court began; judge Twisden gave the charge to the grand jury, in which he said,
there was a sort of people, who under pretence of conscience and religion,
seemed to build upon the king`'s declaration from Breda,
and under colour of this hatched treasons and rebellions,
and gave the jury charge to inquire and present such,
that the peace of the nation might be preserved; so they impanneled the jury,
and Francis was called to the bar, and the judge spake as followeth:

Judge, speaking calmly to him, said,
the face of things was much altered since the last assizes,
and made a large speech to him and the country, telling him,
that all sects under pretence of conscience did violate the laws, and hatched rebellions,
"`Not, (saith he,) that I have any thing to charge you with;
but seeing the oath of allegiance was tendered to you the last assizes,
and you refused to take it,
it was looked upon that such persons were enemies to the king and government;`" and said,
"`I will not trouble you now to answer to your indictment,
but I must do that the next assizes;
in the meantime you must enter into recognizance for your good behaviour.`"

To which F. H. answered, I desire liberty to speak, which he had without interruption,
and said as followeth:

F+++.+++ H. Judge Twisden, thou very well knowest upon how slender an account, or none,
I was brought before thee the last assizes,
where thou wert pleased to tender me the oath of allegiance,
though I believe both thou and the rest of the court,
did know it was a received principle among us not to swear at all;
many reasons I gave thee then, many more I have to add, if I may have audience;
for it may appear to you an absurd thing, and obstinacy in me to refuse it,
if I should not tender a reason; I am,
(said he,) none of those that make religion a cloak of maliciousness,
nor conscience a cloak to carry on plots or conspiracies,
the Lord hath redeemed me and many more out of such things,
and seeing I am engaged to appear at the next assizes,
I desire no further thing may be required of me.

Judge.
You must enter into bond this dangerous time, and therefore consider of it,
and tell me now, or before the assizes end.

The second day of the assizes he was called again.

F+++.+++ H. Seeing thou art pleased to let me answer to the indictment,
which I am willing to do, I have been of good behaviour, and shall so continue;
but it seems a hard thing to me, and full of severity,
that seeing I am obliged to appear to answer an indictment of so high a nature,
(if prosecuted against me,) which tends to the loss of my liberty for life,
and my estate forever, I hope the court will not envy my liberty for five months.

Judge Turner said, We do not desire your imprisonment, if you will be of good behaviour.

F+++.+++ H. pressed that they would not put him upon giving bond to be of good behaviour,
knowing himself to be bound by the truth, that he could not misbehave himself.

One Daniel Flemming, another persecuting justice,
had framed another indictment against him for meeting, and stood up,
(fearing the snare of giving bond would not hold,) and said as followeth:

D+++.+++ Flemming.
My lord, he is a great speaker, it may be the Quakers cannot want him.

Judge.
Let him be what he will, if he will enter into bond.

F+++.+++ H. said he had nothing to accuse himself of,
for his conscience bore him witness that he loved peace, and sought it with all men.

Judges both spake.
What do you tell of conscience?
We meddle not with it; but you contemn the laws, and keep up great meetings,
and go not to church.

F+++.+++ H. We are fallen in a sad age; if meeting together peaceably, without arms, or force,
or intention of hurt to any man, only to worship God in Spirit,
and exhort one another to righteousness, and to pray together in the Holy Ghost,
as the primitive Christians of old,
that this should be reckoned breach of peace and misbehaviour.

Judge Twisden.
Do you compare these times with them?
They were heathens that persecuted, but we are Christian magistrates.

F+++.+++ H. It is a doctrine always held by us, and a received principle which we believe,
that Christ`'s kingdom could not be set up with carnal weapons;
nor the gospel propagated by force of arms, nor the church of God built with violence;
but the Prince of Peace was manifested amongst us, and we could learn war no more,
but could love enemies, and forgive them that did evil to us.

Philip Musgrave stood up, and said, "`My Lord, we have been remiss towards this people,
and have striven with them, and put them in prison again and again, and fined them,
and as soon as they are out they meet again.`"

Then stood up John Lowther, called a justice, and said, "`My Lord, they grow insolent,
notwithstanding all laws, and the execution of them, yet they grow upon us,
and their meetings are dangerous.`"

Philip Musgrave stood up, and produced a paper, (and justice Flemming, so called,
seconded him,) in great capital letters, and gave it the judge; he told the judge,
that it happened some Quakers were sent to prison, and one of them died at Lancaster,
and they carried his corpse through the country, and set that paper upon his coffin,
"`This is the body of such an one, who was persecuted by Daniel Flemming till death.`"

Judge.
We have spent much time with you; I will discourse no more.

F+++.+++ H. I acknowledge your moderation towards me, allowing me liberty to speak;
I shall not trouble you much longer;
I shall be willing to appear to answer to the indictment at the assizes,
and in the meantime to live peaceably and quietly, as I have done, if that will satisfy.

Judge.
You must enter into bond to come at no more meetings.

F+++.+++ H. I cannot do that; if I should, I were treacherous to God and my own conscience,
and the people and you would but judge me a hypocrite.

They were loth to commit him, yet at last they did.

This was in the latter part of the month called March,
and he was kept about five months as before in a bad room,
and none suffered to speak with him,
but who got secretly to him without the jailer`'s knowledge.

It was about this time that John Audland departed this life.
He and his bosom friend, John Camm,
(whose decease was some years before,) had travelled
much together in the ministry of the gospel:
therefore I will give an uninterrupted relation of their latter end;
but first that of John Camm.

He was of very good parentage, born at Camsgil, in the barony of Kendal in Westmoreland,
which seat had been possessed by his ancestors long before him.
From his childhood he was inclined to be religious, and seeking after the best things,
he joined with those that were the most strict in performing religious duties.
And having afterwards heard G. Fox, he embraced as truth the doctrine he preached,
and growing up in it,
he himself became an eminent minister of the gospel among those called Quakers.
He and his bosom friend John Audland,
were the first of that society who preached at Bristol,
where having been in the meetings of the Baptists and Independents,
they also had meetings in several places without the city,
where there was a great concourse of people, and many received their doctrine.
Since that time these two ministers travelled much together,
and many were convinced by their ministry.
But at length John Camm, who did not spare himself,
began to fall under a kind of consumption,
insomuch that through weakness he was fain to stay at home;
and then he often called his children and family together, exhorting them to godliness,
and praying to the Lord for them.
Some weeks before his death, he once expressed himself thus:
"`How great a benefit do I enjoy above many,
having such a large time of preparation for death, being daily dying,
that I may live forever with my God, in that kingdom that is unspeakably full of glory.
My outward man daily wastes and moulders down, and draws towards its place and centre;
but my inward man revives,
and mounts upwards towards its place and habitation in the heavens.`"
The morning that he departed this life, he called his wife, children, and family, to him,
and exhorting them to fear the Lord, to love his truth, to walk in it,
and to be loving and kind to one another, telling them that his glass was run,
the time of his departure was come; and he was to enter into everlasting ease, joy,
and rest: charging them all to be patient and content with their parting with him.
And so fainting, he passed into a sweet sleep;
but by the weeping and crying of those about him, he awakened,
and desired to be helped up a little in his bed, and then he spoke to this effect:
"`My dear hearts, ye have wronged me and disturbed me, for I was at sweet rest;
ye should not so passionately sorrow for my departure;
this house of earth and clay must go to its place;
and this soul and spirit is to be gathered up to the Lord, to live with him forever,
where we shall meet with everlasting joy.`"
Then taking leave of his family, he charged them to be content with his departure;
and lying down, within a little time deceased.

His beloved friend John Audland,
(who often bemoaned the loss of so dear a companion,) died also of a kind of consumption:
for his ardent zeal made him strain his voice beyond what his body was well able to hear.
In a meeting, which he once had with J. Camm, in a field without Bristol,
where Charles Marshall was one of his auditors, after J. Camm had left off speaking,
he stood up, with an awful and shining countenance:
and lifting up his voice as a trumpet, he said,
"`I proclaim a spiritual war with the inhabitants of the earth,
who are in the fall and separation from God,
and I prophesy to the four winds of heaven.`"
Thus he went on with mighty power, exhorting to repentance;
and spoke with such a piercing authority, that some of the auditory fell on the ground,
and cried out under the sense of their transgression.
And when at Bristol he many times preached in an orchard to a great multitude,
he would lift up his voice exceedingly, in order to be heard by all.
Thus he spent his natural strength, though he was but a young man.
About the twentieth year of his age, he married with one Anne Newby, of Kendal,
a virtuous maid, not only of good family, but also excelling in piety,
and therefore she freely gave him up to travel in the service of the gospel,
notwithstanding his company was very dear to her; which made her say,
that she believed few ever enjoyed a greater blessing in a husband so kind and affectionate.
And how heartily and tenderly she loved him,
may be seen by the following letter she wrote to him.

Dear Husband,

Thou art dearer to me than ever; my love flows out to thee,
even the same love that I am loved withal of my Father.
In that love salute me to all my friends, for dear you are all unto me;
my life is much refreshed in hearing from you.
I received thy letters, and all my soul desireth is to hear from thee in the life;
dear heart, in life dwell, there I am with thee out of all time, out of all words,
in the pure power of the Lord, there is my joy and strength;
O! how am I refreshed to hear from thee,
to hear of thy faithfulness and boldness in the work of the Lord.
O! dear heart, I cannot utter the joy I have concerning thee;
thy presence I have continually in spirit, therewith am I filled with joy;
all glory and honour be to our God forever.
O! blessed be the day in which thou wast born,
that thou art found worthy to labour in the work of the Lord.
Surely the Lord hath found thee faithful in a little,
therefore he hath committed much unto thee;
go on in the name and power of the Lord Jesus Christ, from whence all strength cometh,
to whom be all glory, and honour forever.
O! dear heart, go on, conquering and to conquer, knowing this, that thy crown is sure.
So, dear heart, now is the time of the Lord`'s work,
and few are willing to go forth into it.
All the world lieth in wickedness, doing their own work;
but blessed be the Lord forever, who hath called us from doing our own work,
into his great work.
O! marvellous are his works, and his ways past finding out.
O! dear heart, thou knowest my heart,
thou mayest read daily how that I rejoice in nothing
more than in thy prosperity in the work of the Lord:
Oh! it is past my utterance to express the joy I have for thee.
I am full, I am full of love towards thee, never such love as this;
the mighty power of the Lord go along with thee, and keep thee faithful and valiant,
and bold in his pure counsel, to stand single out of all the world.
O! dear heart, all my love to thee is purer than gold seven times purified in the fire:
O! pure is he that hath loved us, therefore let purity and holiness cover us forever.
A joyful word it was to me, to hear that thou wast moved to go for Bristol:
O my own heart, my own life! in that which now stands, act and obey,
that thou mayest stand upon thy alone guard; so, dear heart, let thy prayers be for me,
that I may be kept pure out of all temptations, singly to dwell in the life: so farewell.

Anne Audland.

By this letter it appears,
that there was an endeared mutual love between this virtuous couple.
He was a man of great knowledge,
but when his understanding came to be opened by the preaching of G. Fox, he would say,
sometimes, "`Ah, what have we been doing!
Or what availeth our great profession?
All our building tumbles down; our profession is high as the wind;
the day of the Lord is upon it, and his word, as a fire, consumes it as dry stubble;
and puts an end to all empty professions and high notions, without life or substance;
to all the wisdom of fallen man.
We must forsake the world, and all its glory;
it is all but vanity and vexation of spirit: it is a Saviour that I long for;
it is him that my soul pants after.
O that I may be gathered into his life, and overshadowed with his glory,
sanctified throughout by his word, and raised up by his eternal power!`"
He continuing in this state of daily supplication and inward travail of soul,
it pleased the Lord at length to furnish him with
an extraordinary qualification to proclaim his word,
which he did some years faithfully, and with great zeal.
And though his wife loved him dearly,
and preferred his company above what the world could give;
yet in regard of his gospel service, she gave him up freely to be much from home;
whereby during a great part of the time of their marriage,
she had not his desirable company.

In the meanwhile he laboured diligently in the Lord`'s harvest,
till his bodily strength failing, and meeting with hard imprisonments,
he was seized with a most violent cough, which was followed by a fever,
so that his sleep was taken from him, which made him grow very weak;
but he bore his sickness with great patience, and said once,
that in those great meetings in the orchard at Bristol, he often forgot himself,
not considering the inability of his body, from a desire to be heard by all:
but that his reward was with him, and he content to be with the Lord,
which his soul valued above all things.
Not long before his departure, being visited by some of his friends,
he spoke so comfortably, and with such power,
as one that was beyond the feeling of his weakness.
To his wife, who was big with child, and nigh her delivery,
well knowing how tenderly she loved him, he said, "`My will is in true subjection,
submitting to the will of the Lord, whether life or death;
and therefore give me up freely to his disposing.`"
And she, how dear soever he was to her, did so; which gave him some ease,
seeing her sincere resignedness; and being sometimes overcome with joy,
he praised God in his sickness; nay so ardent was his zeal, that once, though very weak,
he desired to be helped up in bed upon his knees;
and thus he fervently supplicated the Lord in the behalf of his churches,
that they might be preserved in the truth, out of the evil of the world,
and that his gospel might spread,
and be published to the gathering of all that pertain to Israel.
His strength now diminishing daily, he sweetly departed at the age of thirty-four years,
about three weeks after the fever first seized him.
And his widow, who ten days after his decease was delivered of a son,
behaved herself discreetly, and said afterwards in a paper concerning him:
"`The eternal God, who by his providence, joined us together in marriage,
in our young days,
in his blessed counsel also caused his day to spring from on high upon us:
in the marvellous light, and bright shining whereof, he revealed his Son Christ in us,
and gave us faith to believe in him, the eternal word of life,
by which our souls came to be quickened, and made alive in him:
and also in and by the quickening of his holy power,
were made one in a spiritual and heavenly relation,
our hearts being knit together in the unspeakable love of truth, which was our life, joy,
and delight, and made our days together exceeding comfortable:
as being that whereby all our temporal enjoyments were sanctified,
and made a blessing to us.
How hard it was, and how great a loss,
to part with so dear and tender an husband as he was to me,
is far beyond what I can express: the dolour of my heart,
my tongue or pen is not able to declare.
Yet in this I contented myself,
that it was the will of the Lord that he was taken from the evil; and that my loss,
though great, was not to be compared to his eternal gain.`"
This widow, in process of time, was married to Thomas Camm, son of John Camm,
her former husband`'s bosom friend.
She was indeed a woman of great virtue, but now I part with her,
with intention to say more of her when I shall come to the time of her decease.

I return to Francis Howgill, whom we left in prison,
and who now appeared again at the assizes, which were holden at Appleby,
in the month called August.
And he having got liberty to speak with the clerk of the assizes, who told him,
that he must prepare himself to come to a trial, answered, he was prepared,
but thought that all he could say, would little avail,
believing they purposed to prosecute him with all severity: which proved so,
as will appear by what follows;
for the county justices had incensed the judges against him beforehand.
Yet Howgill endeavoured all he could to convince them of his innocency;
and to that end drew up the substance of the oath
into several heads which he could subscribe to;
to this he joined another paper to judge Turner,
showing the cause of his first commitment and the former proceedings against him:
and how unequal it was to prosecute him upon a statute made against popish recusants.
He also signified in that paper, that he was a man of a tender spirit,
and feared the Lord from a child, and he had never taken any oath but once in his life,
which was twenty years ago; and that his refusing to take the oath of allegiance,
was not in any evil intent to the king`'s person or government,
but merely upon a conscientious account, and that he could not swear,
being otherwise persuaded of the Lord, seeing it was against the command of Christ,
and the apostle James`'s doctrine.
Besides,
that he was able to make it evident to be against the example
of the primitive Christians for divers hundred years,
and so no new opinion.
That he did neither in willfulness nor obstinacy refuse it,
being sensible of the damage that would come thereby,
if they did prosecute him upon that statute, he having a wife and children,
and some small estate, which he knew lay at stake in the matter;
but that though it were his life also, he could not revolt from,
or deny that which he had most certainly believed in;
but if any could convince him either by scripture or reason, he had an ear to hear.
And therefore all those things considered,
he desired he might he dismissed from his bonds,
and from their persecution of him upon that account.
These papers were delivered to the judges and justices before he appeared in court,
and were read by them.
He then being called to the bar at the assizes holden at Appleby,
judge Turner said to him,
"`Here is an indictment against you for refusing to take the oath of allegiance;
so you must plead to it, either guilty or not guilty.`"

F+++.+++ H. with a heart girded up with strength and courage, said, "`Judge Turner,
may I have liberty to speak, and make my defence,
for I have none to plead my cause but the Lord?`"

Judge.
You may.

F+++.+++ H. I will lay the true state of my case before thee,
and of the proceedings against me from the first, seeing judge Twisden is not here,
who had knowledge of all the proceedings hitherto.
I am a countryman, born and brought up in this country;
my carriage and conversation is known, how I have walked peaceably towards all men,
as I hope my countrymen can testify.
About a year ago being at my neighbouring market-town
about my reasonable and lawful occasions,
I was sent for by an high constable out of the market to the justices of peace,
before whom I went; and when I came there, they had nothing to lay to my charge,
but fell to ask me questions to ensnare me about our meetings;
and when they could find no occasion, they seemed to tender the oath of allegiance to me,
though they never read it to me, neither did I positively deny it,
yet they committed me to prison; and so I was brought hither to this assize,
and then the mittimus by which I was committed, was called for, and the judge read it,
and said to the justices it was insufficient:
nevertheless judge Twisden tendered the oath of allegiance to me;
many things I did allege then, and many more I have to say now, if time will permit:
from that time I was under an engagement to appear at the next assizes,
and so was called, and did appear at the last jail-delivery,
and a further obligation was required of me for good behaviour, which I could not give,
lest I should be brought into a further snare;
and since that time I have been committed prisoner these five months,
of which time I have been kept under great restraint,
my friends not permitted to speak to me:
and thus briefly I have given thee an account hitherto.
As to the oath, the substance thereof, with the representation of my case,
is presented to the court already, unto which I have set my hand,
and also shall in those words testify the same in open court, if required;
and seeing it is the very substance the law doth require I desire it may be accepted,
and I cleared from my imprisonment.

Judge.
I am come to execute the law, and the law requires an oath, and I cannot alter it;
do you think the law must be changed for you, or only for a few; if this be suffered,
the administration of justice is hindered, no action can be tried,
nor evidence given for the king, nor other particular cases tried;
and your principles are altogether inconsistent with the law and government;
I pray you show me which way we shall proceed, show me some reason,
and give me some ground.

F+++.+++ H. I shall: in the mouth of two or three witnesses every truth is confirmed;
and we never denied to give,
and still are ready to give evidence for the king wherein we are concerned,
and in any other matter for the ending of strife between man and man in truth and righteousness,
and this answers the substance of the law.

Judge.
Is this a good answer, think you?
whether to be given with or without oath: the law requires an oath.

F+++.+++ H. Still evidence is and may be given in truth, according to the substance of the law,
so that no detriment cometh unto any party,
seeing that true testimony may be borne without an oath;
and I did not speak of changing the law: yet seeing we never refused giving testimony,
which answereth the intent and substance of the law,
I judged it was reasonable to receive our testimony,
and not to expose us to such sufferings,
seeing we scrupled an oath only upon a conscientious account,
in tenderness of conscience, for fear of breaking the command of Christ,
the Saviour of the world, which if we do,
there is none of you able to plead our cause for us with him.

Judge.
But why do not you go to church, but meet in houses and private conventicles,
which the law forbids.

F+++.+++ H. We meet together only for the worship of the true God in Spirit and Truth,
having the primitive Christians for our example, and to no other end,
but that we may be edified, and God glorified;
and when two or three are met together in the name of Christ,
and he in the midst of them, there is a church.

Judge.
That is true: but how long is it since you have been at church?
Or will you go to the church the law doth allow of?
Give me some reasons why you do not go.

F+++.+++ H. I have many to give thee, if thou hast patience to hear me: first,
God dwells not in temples made with men`'s hands.
Secondly, the parish house hath been a temple for idols, to wit,
for the mass and the rood; and I dare have no fellowship with idols,
nor worship in idols`' temples; for what have we to do with idols,
their temples and worship?

Judge.
Were there not houses called the houses of God, and temples?

F+++.+++ H. Yes, under the law; but the Christians, who believed in Christ,
separated from these,
(and the temple was made and left desolate,) and from the Gentiles`' temples too,
and met together in houses, and broke bread from house to house;
and the church was not confined then to one particular place, neither is it now;
many more things I have to say: the judge interrupted.

Judge.
Will you answer to your indictment?

F+++.+++ H. I know not what it is, I never heard it, though I have often desired a copy.

Judge.
Clerk, read it.

So he read it: how that F. H. had willfully, obstinately,
and contemptuously denied to swear when the oath was tendered.

F+++.+++ H. I deny it.

Judge.
What do you deny?

F+++.+++ H. The indictment.

Judge.
Did you not deny to swear?
And the indictment convicts you that you did not swear.

F+++.+++ H. I gave unto the court the substance of the oath, as you all know.
Secondly, I told you I did not deny it out of obstinacy or willfulness,
neither in contempt of the king`'s law or government;
for my will would rather choose my liberty, than bonds;
and I am sensible it is like to be a great damage to me; I have a wife and children,
and some estate, which we might subsist upon, and do good to others,
and I know all this lies at stake; but if it were my life also,
I durst not but do as I do, lest I should incur the displeasure of God;
and do you judge I would lose my liberty willfully, and suffer the spoiling of my estate,
and the ruining of my wife and children in obstinacy and willfulness?
Surely nay.

Judge.
Jury, you see he denies the oath, and he will not plead to the indictment,
only excepts against it because of the form of words, but you see he will not swear,
and yet he says he denies the indictment, and you see upon what ground.

And then they called the jailer to witness and swear
that at the last assizes F. H. did refuse,
etc. which he did; and the jury, without going from the bar, gave in their verdict,
guilty, and then the court broke up that night.

The next day towards evening, when they had tried all the prisoners,
Francis was brought to the bar to receive his sentence.

Judge stood up and said, "`Come, the indictment is proved against you,
what have you to say why sentence shall not be given?`"

F+++.+++ H. I have many things to say, if you will hear them.
First, as I have said, I denied not out of obstinacy or willfulness,
but was willing to testify the truth in this matter of obedience,
or any other matter wherein I was concerned.
Secondly, because swearing was directly against the command of Christ.
Thirdly, against the doctrine of the apostle.
Fourthly, even some of your principal pillars of the church of England; as bishop Usher,
some time primate of Ireland, he said in his works,
the Waldenses did deny all swearing in their age,
from that command of Christ and the apostle James, and it was a sufficient ground;
and Dr. Gauden, late bishop of Exeter, in a book of his I lately read,
he cited very many ancient fathers, to show,
that the first three hundred years Christians did not swear,
so that it is no new doctrine.

To which the court seemed to give a little ear, and said nothing,
but talked one to another, and Francis stood silent, and then the judge said,

Judge.
Sure you mistake.

F+++.+++ H. I have not the books here.

Judge.
Will you say upon your honest word they denied all swearing?

F+++.+++ H. What I have said is true.

Judge.
Why do you not come to church, and hear service, and be subject to the law,
and to every ordinance of man for the Lord`'s sake?

F+++.+++ H. We are subject, and for that cause we do pay taxes, tribute, and custom,
// lint-disable invalid-characters ""
and give unto Csar the things that are his, and unto God the things that are his,
to wit, worship, honour, and obedience; and if thou mean the parish assembly,
I tell thee faithfully, I am persuaded, and upon good ground,
their teachers are not the ministers of Christ, neither their worship the worship of God.

Judge.
Why; it may be for some small things in the service, you reject it all.

F+++.+++ H. First, it is manifest they are time-servers,
one while preaching up that for divine service to people,
that another while they cry down, as popish, superstitious and idolatrous;
and that which they have preached up twenty years together,
made shipwreck of all in a day; and now again call it divine,
and would have all compelled to that themselves once made void.

Judge.
Why; never since the king came in?

F+++.+++ H. Yes, the same men that preached it down once, now cry it up;
for they are so unstable and wavering,
that we cannot believe they are the ministers of Christ.
Secondly, they teach for hire, and live by forced maintenance,
and would force a faith upon men, contrary to Christ and his apostle`'s rule,
who would have every one persuaded in their own minds, and said,
whatsoever is not of faith is sin; and yet they say, faith is the gift of God;
and we have no such faith given; but yet they would force theirs upon us,
and because we cannot receive it, they cry,
you are not subject to authority and the laws, and nothing but confiscations,
imprisonment and banishment is threatened, and this is their greatest plea;
I could mention more particulars; then the judge interrupted.

Judge.
Well, I see you will not swear, nor conform, nor be subject,
and you think we deal severely with you, but if you will be subject, we should not need.

F+++.+++ H. I do so judge indeed,
that you deal severely with us for obedience to the commands of Christ;
I pray thee canst thou show me how any of those people, for whom the act was made,
have been proceeded against by this statute, though I envy no man`'s liberty.

Judge.
Oh yes, I can instance you many up and down the country that are premunired,
I have done it myself, pronounced sentence against divers.

F+++.+++ H. What, against Papists?

Judge.
No.

F+++.+++ H. What, against the Quakers?
So I have heard indeed; though then that statute was made against Papists,
thou lettest them alone, and executest it against the Quakers.

Judge.
Well, you will meet in great numbers, and do increase,
but there is a new statute will make you fewer.

F+++.+++ H. Well, if we must suffer, it is for Christ`'s sake, and for well doing.

Francis then being silent, the judge pronounced the sentence, but spake so low,
that the prisoner, though near to him, could scarce hear it.

The sentence was, You are put out of the king`'s protection, and the benefit of the law,
your lands are confiscated to the king during your life;
and your goods and chattels forever, and you to be prisoner during your life.

F+++.+++ H. A hard sentence for my obedience to the commands of Christ;
the Lord forgive you all.

So he turned from the bar; but the judge speaking, he turned again,
and many more words passed to the same purpose, as before: at last,
the judge rose up and said.

Judge.
Well, if you will yet be subject to the laws, the king will show you mercy.

F+++.+++ H. The Lord hath showed mercy unto me, and I have done nothing against the king,
nor government, nor any man, and blessed be the Lord, and therein stands my peace;
for it is for Christ`'s sake I suffer, and not for evil doing.
And so the court broke up.
The people were generally moderate, and many were sorry to see what was done against him;
but Francis signified how contented and glad he was,
that he had any thing to loose for the Lord`'s precious Truth,
of which he had publicly borne testimony,
and that he was now counted worthy to suffer for it.

This he did cheerfully, and died in bonds, after above four years`' imprisonment,
as may be related in its due time.
He was a man of learning, and a great writer among his fellow believers; insomuch,
that during his confinement he wrote not only several edifying
epistles to exhort them to constancy and steadfastness,
in the doctrine of Truth, but also some books to refute the opposers of it.

We have here seen how the judge said, there is a new statute which will make you fewer.
This statute bore the title of an act to prevent and suppress seditious conventicles.
And though the act made two years before did extend to banishment,
yet that punishment was renewed, and expressed more at large in this,
which was as followeth:

Whereas an act made in the five and thirtieth year
of the reign of our late sovereign lady queen Elizabeth,
intitled an act to retain the queen`'s majesty`'s subjects in their due obedience,
hath not been put in due execution by reason of some doubt of late made,
whether the said act be still in force; although it be very clear and evident,
and it is hereby declared, that the said act is still in force,
and ought to be put in due execution:

II. For providing therefore of further and more speedy remedies
against the growing and dangerous practices of seditious sectaries,
and other disloyal persons, who under pretence of tender consciences,
do at their meetings contrive insurrections, as late experience hath showed;

III.
Be it enacted by the king`'s most excellent majesty,
by and with the advice and consent of the lords spiritual and temporal,
and commons in this present parliament assembled, and by the authority of the same,
that if any person of the age of sixteen years or upwards, being a subject of this realm,
at any time after the 1st day of July, which shall be in the year of our Lord,
one thousand six hundred sixty and four, shall be present at any assembly,
conventicle or meeting, under colour or pretence of any exercise of religion,
in other manner than is allowed by the liturgy or practice of the
church of England in any place within the kingdom of England,
dominion of Wales, and town of Berwick-upon-Tweed; at which conventicle, meeting,
or assembly, there shall be five persons or more assembled together,
over and above those of the same household;
then it shall and may be lawful to and for any two justices of the peace of the county,
limit, division or liberty wherein the offence aforesaid shall be committed,
or for the chief magistrate of the place where such offence aforesaid shall be committed,
(if it be within a corporation where there are not two justices
of the peace,) (2) and they are hereby required and enjoined
upon proof to them or him respectively made of such offence,
either by confession of the party, or oath of witness, or notorious evidence of the fact,
(which oath the said justices of the peace, and chief magistrate respectively,
are hereby empowered and required to administer,) to make a record of
every such offence and offences under their hands and seals respectively;
(3) which record so made, as aforesaid,
shall to all intents and purposes be in law taken and adjudged to be a
full and perfect conviction of every such offender for such offence:
and thereupon the said justices and chief magistrate respectively
shall commit every such offender so convicted,
as aforesaid, to the jail or house of correction,
there to remain without bail or mainprize,
for any time not exceeding the space of three months,
unless such offender shall pay down to the said justices or chief
magistrate such sum of money not exceeding five pounds,
as the said justices or chief magistrate,
(who are hereby thereunto authorized and required,) shall fine the said offender at,
for his or her said offence;
which money shall be paid to the church wardens for the relief
of the poor of the parish where such offender did last inhabit.

IV. And be it further enacted by the authority aforesaid,
that if such offender so convicted, as aforesaid,
shall at any time again commit the like offence contrary to this act,
and be thereof in manner aforesaid convicted,
then such offender so convicted of such second offence,
shall incur the penalty of imprisonment in the jail or house of correction,
for any time not exceeding six months, without bail or mainprize,
unless such offender shall pay down to the said justices or chief magistrate,
such sum of money, not exceeding ten pounds, as the said justices or chief magistrate,
(who are thereunto authorized and required,
as aforesaid,) shall fine the said offender at, for his or her said second offence,
the said fine to be disposed in manner aforesaid.

V+++.+++ And be it further enacted by the authority aforesaid,
that if any such offender so convicted of a second
offence contrary to this act in manner aforesaid,
shall at any time again commit the like offence contrary to this act,
then any two justices of the peace, and chief magistrate, as aforesaid, respectively,
shall commit every such offender to the jail, or house of correction,
there to remain without bail or mainprize until the next general quarter sessions,
assizes, jail-delivery, great sessions,
or sitting of any commission of Oyer and Terminer in the respective county, limit,
division or liberty which shall first happen;
(2) when and where every such offender shall be proceeded
against by indictment for such offence,
and shall forthwith be arraigned upon such indictment,
and shall then plead the general issue of not guilty,
and give any special matter in evidence, or confess the indictment:
(3) and if such offender proceeded against, shall be lawfully convicted of such offence,
either by confession or verdict,
or if such offender shall refuse to plead the general issue,
or to confess the indictment,
then the respective justices of the peace at their general quarter sessions,
judges of assize and jail-delivery, justices of the great sessions at the great sessions,
and commissioners of Oyer and Terminer at their sitting,
are hereby enabled and required to cause judgment to be entered against such offender,
that such offender shall be transported beyond the
seas to any of his majesty`'s foreign plantations,
(Virginia and New England only excepted,) there to remain seven years:
(4) and shall forthwith under their hands and seals make out warrants to the sheriff
or sheriffs of the same county where such conviction or refusal to plead or to confess,
as aforesaid, shall be,
safely to convey such offender to some port or haven nearest
or most commodious to be appointed by them respectively;
and from thence to embark such offender to be safely transported
to any of his majesty`'s plantations beyond the seas,
as shall be also by them respectively appointed,
(Virginia and New England only excepted:) (5) whereupon
the said sheriff shall safely convey and embark,
or cause to be embarked such offender, to be transported, as aforesaid,
under pain of forfeiting for default of so transporting every such offender,
the sum of forty pounds of lawful money, the one moiety thereof to the king,
and the other moiety to him or them that shall sue
for the same in any of the king`'s courts of record,
by bill, plaint, action of debt, or information; in any of which no wager of law,
essoign or protection shall be admitted:
(6) and the said respective court shall then also make out warrants to the several constables,
headboroughs,
or tithingmen of the respective places where the estate real or personal
of such offender so to be transported shall happen to be,
commanding them thereby to sequester into their hands the profits of the lands,
and to distrain and sell the goods of the offender so to be transported,
for the reimbursing of the said sheriff all such reasonable charges as he shall be at,
and shall be allowed him by the said respective court for such conveying,
or embarking of such offender so to be transported, rendering to the party,
or his or her assigns, the overplus of the same, if any be, unless such offender,
or some other on the behalf of such offender so to be transported,
shall give the sheriff such security as he shall approve of,
for the paying all the said charges unto him.

VI. And be it further enacted by the authority aforesaid,
that in default of defraying such charges by the parties to be transported,
or some other in their behalf; or in default of security given to the sheriff,
as aforesaid,
it shall and may be lawful for every such sheriff to contract with any master of a ship,
merchant, or other person, for the transporting of such offender at the best rate he can:
(2) and that in every such case it shall and may be lawful for such persons
so contracting with any sheriff for transporting such offender,
as aforesaid, to detain and employ every such offender so by them transported,
as a labourer to them or their assigns, for the space of five years,
to all intents and purposes,
as if he or she were bound by indentures to such person for that purpose:
(3) and that the respective sheriffs shall be allowed or paid from the king,
upon their respective accompt in the exchequer, all such charges by them expended,
for conveying, embarking and transporting of such persons,
which shall be allowed by the said respective courts
from whence they received their respective warrants,
and which shall not have been by any of the ways aforementioned paid, secured,
or reimbursed unto them, as aforesaid.

VII.
Provided always, and be it further enacted,
that in case the offender so indicted and convicted for the said third offence,
shall pay into the hands of the register or clerk
of the court or sessions where he shall be convicted,
(before the said court or sessions shall be ended,) the sum of one hundred pounds,
that then the said offender shall be discharged from imprisonment and transportation,
and the judgment for the same.

VIII.
And be it further enacted, that the like imprisonment, indictment,
arraignment and proceedings shall be against every such offender,
as often as he shall again offend after such third offence;
nevertheless is dischargeable and discharged,
by the payment of the like sum as was paid by such offender
for his or her said offence next before committed,
together with the additional and increased sum of
one hundred pounds more upon every new offence committed;
(2) the said respective sums to be paid as aforesaid, and to be disposed as followeth,
viz. the one moiety for the repair of the parish church or churches,
chapel or chapels of such parish within which such conventicle, assembly,
or meeting shall be held;
and the other moiety to the repair of the highways of the said parish or parishes,
(if need require,) or otherwise for the amendment of such highways as the justices
of peace at their respective quarter sessions shall direct and appoint.
(3) And if any constable, headborough or tithingman,
shall neglect to execute any the said warrants made unto them for sequestering,
distraining, and selling any of the goods and chattels of any offender against this act,
for the levying such sums of money as shall be imposed for the first or second offence,
he shall forfeit for every such neglect,
the sum of five pounds of lawful money of England, the one moiety thereof to the king,
and the other moiety to him that shall sue for the
same in any of the king`'s courts of record,
as is aforesaid.
(4) And if any person be at any time sued for putting in
execution any of the powers contained in this act,
such person shall and may plead the general issue,
and give the special matter in evidence; (5) And if the plaintiff be nonsuited,
or a verdict pass for the defendant thereupon,
or if the plaintiff discontinue his action, or if upon demurrer,
judgment be given for the defendant,
every such defendant shall have his or their treble costs.

IX. And be it further enacted,
that if any person against whom judgment of transportation
shall be given in manner aforesaid,
shall make escape before transportation, or being transported as aforesaid,
shall return unto this realm of England, dominion of Wales,
and town of Berwick-upon-Tweed, without the special license of his majesty,
his heirs and successors, in that behalf first had and obtained,
that the party so escaping or returning, shall be adjudged a felon,
and shall suffer death as in case of felony, without benefit of clergy,
(2) and shall forfeit and lose to his majesty all his or her goods and chattels forever;
and shall further lose to his majesty all his or her lands,
tenements and hereditaments for and during the life only of such offender, and no longer:
and that the wife of any such offender by force of this act, shall not lose her dower,
nor shall any corruption of blood grow,
or be by reason of any such offence mentioned in this act;
but that the heir of every such offender by force of this act,
shall and may after the death of such offender, have and enjoy the lands,
tenements and hereditaments of such offenders, as if this act had not been made.

X+++.+++ And for better preventing of the mischiefs which
may grow by such seditious and tumultuous meetings,
under pretence of religious worship,
(2) Be it further enacted by the authority aforesaid,
that the lieutenants or deputy-lieutenants, or any commissioned officers of the militia,
or any other of his majesty`'s forces, with such troops or companies of horse or foot;
and also the sheriffs and justices of peace,
and other magistrates and ministers of justice, or any of them jointly or severally,
within any the counties or places within this kingdom of England, dominion of Wales,
or town of Berwick-upon-Tweed, with such other assistance as they shall think meet,
or can get in readiness with the soonest,
on certificate made to them respectively under the
hand and seal of any one justice of the peace,
or chief magistrate, as aforesaid,
of his particular information or knowledge of such unlawful meetings or
conventicles held or to be held in their respective counties or places,
and that he, (with such assistance as he can get together,
is not able to suppress or dissolve the same,) shall and may,
and are hereby required and enjoined to repair unto the place where they are so held,
or to be held, and by the best means they can to dissolve and dissipate,
or prevent all such unlawful meetings,
and take into their custody such of those persons so unlawfully assembled
as they shall judge to be the leaders and seducers of the rest,
and such others as they shall think fit to be proceeded
against according to law for such their offences.

XI. And be it further enacted by the authority aforesaid,
that every person who shall wittingly and willingly suffer any such conventicle,
unlawful assembly, or meeting aforesaid, to be held in his or her house, outhouse,
barn or room, yard or backside, woods or grounds,
shall incur the same penalties and forfeitures as
any other offender against this act ought to incur,
and be proceeded against in all points,
in such manner as any other offender against this act ought to be proceeded against.

XII.
Provided also, and be it enacted by the authority aforesaid,
that if any keeper of any jail or house of correction,
shall suffer any person committed to his custody for any offence against this act,
to go at large, contrary to the warrant of his commitment according to this act,
or shall permit any person who is at large,
to join with any person committed to his custody by virtue of this act,
in the exercise of religion, differing from the rites of the church of England,
then every such keeper of a jail or house of correction,
shall for every such offence forfeit the sum of ten pounds, to be levied, raised,
and disposed by such persons and in such manner as the penalties
for the first and second offences against this act are to be levied,
raised, and disposed.

XIII.
Provided always, that no person shall be punished for any offence against this act,
unless such offender be prosecuted for the same within
three months after the offence committed:
(2) and that no person who shall be punished for any offence by virtue of this act,
shall be punished for the same offence by virtue of any other act or law whatsoever.

XIV.
Provided also, and be it enacted,
that judgment of transportation shall not be given against any femme covert,
unless her husband be at the same time under the like judgment,
and not discharged by the payment of money as aforesaid; but that instead thereof,
she shall by the respective court be committed to the jail or house of correction,
there to remain without bail or mainprize, for any time not exceeding twelve months,
unless her husband shall pay down such sum, not exceeding forty pounds,
to redeem her from imprisonment, as shall be imposed by the said court,
the said sum to be disposed by such persons, and in such manner,
as the penalties for the first and second offence against this act are to be disposed.

XV. Provided also, and be it enacted by the authority aforesaid,
that the justices of the peace,
and the chief magistrate respectively empowered as aforesaid to put this act in execution,
shall and may, with what aid, force, and assistance they shall think fit,
for the better execution of this act, after refusal or denial, enter into any house,
or other place, where they shall be informed any such conventicle as aforesaid,
is or shall be held.

XVI.
Provided, that no dwelling-house of any peer of this realm,
whilst he or his wife shall be there resident, shall be searched by virtue of this act,
but by immediate warrant from his majesty under his sign manual,
or in the presence of the lieutenant, or one of the deputy lieutenants,
or two justices of the peace,
whereof one to be of the quorum of the same county or riding:
(2) nor shall any other dwelling-house of any peer or other person whatsoever,
be entered into with force by virtue of this act,
but in the presence of one justice of the peace, or chief magistrate respectively,
except within the city of London,
where it shall be lawful for any such other dwelling-house to be entered into as aforesaid,
in presence of one justice of the peace, alderman, deputy alderman,
or any one commissioner for the lieutenancy for the city of London.

XVII.
Provided also, and be it enacted by the authority aforesaid,
that no person shall by virtue of this act be committed to the house of correction,
that shall satisfy the said justices of the peace, or chief magistrate respectively,
that he or she, (and in case of a femme covert,
that her husband,) hath an estate of freehold, or copyhold,
to the value of five pounds per annum, or personal estate to the value of fifty pounds;
any thing in this act to the contrary notwithstanding.

XVIII.
And in regard a certain sect called Quakers, and other sectaries,
are found not only to offend in the matters provided against by this act,
but also obstruct the proceedings of justice by their obstinate refusal
to take oaths lawfully tendered unto them in the ordinary course of law;
(2) Therefore be it further enacted by the authority aforesaid,
that if any person or persons being duly and legally served with process,
or other summons, to appear in any court of record, except courtleets, as a witness,
or returned to serve of any jury, or ordered to be examined upon interrogatories,
or being present in court,
shall refuse to take any judicial oath legally tendered
to him by the judge or judges of the same court,
having no legal plea to justify or excuse the refusal of the same oath;
(3) Or if any person or persons being duly served with process,
to answer any bill exhibited against him or them in any court of equity,
or any suit in any court ecclesiastical,
shall refuse to answer such bill or suit upon his or their corporal oath,
in cases where the law requires such answer to be put in upon oath;
or being summoned to be a witness in any such court,
or ordered to be examined upon interrogatories, shall for any cause or reason,
not allowed by law, refuse to take such oath, as in such cases is required by law;
(4) that then, and in such case,
the several and respective courts wherein such refusal shall be made, shall be,
and are hereby enabled to record, enter, or register such refusal,
which record or entry shall be, and is hereby made a conviction of such offence;
(5) and all and every person and persons so as aforesaid offending,
shall for every such offence incur the judgment and punishment of transportation
in such manner as is appointed by this act for other offences.

XIX.
Provided always, that if any the person or persons aforesaid shall come into such court,
and take his or their oath in these words:

I do swear that I do not hold the taking of an oath to be unlawful,
nor refuse to take an oath on that account.

XX. Which oath the respective court or courts aforesaid,
are hereby authorized and required forthwith to tender, administer,
and register before the entry of the conviction aforesaid,
(2) or shall take such oath before some justice of the peace,
who is hereby authorized and required to administer the same,
to be returned into such court,
(3) such oath so made shall acquit him or them from such punishment;
any thing herein to the contrary notwithstanding.

XXI.
Provided always, that every person convicted as aforesaid in any courts aforesaid,
(other than his majesty`'s court of king`'s bench, or before the justices of assize,
or general jail-delivery,) shall by warrant containing a certificate
of such conviction under the hand and seal of the respective judge
or judges before whom such conviction shall be had,
be sent to some one of his majesty`'s jails in the
same county where such conviction was had,
there to remain without bail or mainprize until the next assizes,
or general jail-delivery, (2) where,
if such person so convicted shall refuse to take the oath aforesaid,
being tendered unto him by the justice or justices of assize or jail-delivery,
then such justice or justices shall cause judgment of transportation to be executed
in such manner as judgment of transportation by this act is to be executed:
but in case such person shall take the said oath, then he shall thereupon be discharged.

XXII.
Provided always, and be it enacted by the authority aforesaid,
that if any peer of this realm shall offend against this act,
he shall pay ten pounds for the first offence, and twenty pounds for the second offence,
to be levied upon his goods and chattels by warrant from any two justices of the peace,
or chief magistrate of the place or division where such peer shall dwell:
(2) and that every peer for the third,
and every further offence against the tenour of this act, shall be tried by his peers,
and not otherwise.

XXIII.
Provided also, and be it further enacted by the authority aforesaid,
that this act shall continue in force for three years
after the end of this present session of parliament;
and from thence forward to the end of the next session
of parliament after the said three years,
and no longer.

A learned man at London, of what persuasion I know not,
published a little book in relation to this act,
wherein he showed from the laws of England, the absurdity of it:
since all religious acts, exercised by six persons,
not according to the formality of the church of England, were forbidden;
and that at this rate it might be reckoned a transgression, if a woman being in travail,
and in danger of life, one of the company said a prayer;
or if any one spoke something to comfort the near relations of a deceased person;
or prayed for the health or happiness of a young married couple,
etc. by which it might happen, that some by the malice of their enemies,
might not only incur imprisonment for three months,
but also by virtue of the act of banishment, might be condemned to transportation.
That this was not without danger,
did appear sufficiently by what judge Orlando Bridgman said at Hertford to the jury,
viz. "`You are not to expect a plain punctual evidence against
them for any thing they said or did at their meeting;
for they may speak to one another, though not with or by articular sound,
but by a cast of the eye, or a motion of the head or foot, or gesture of the body.
So that if you find or believe in your hearts that they
were in the meeting under colour of religion in their way,
though they sat still only and looked upon each other, it was an unlawful meeting.`"
At this rate the jurymen, who ought to be impartial judges, or mediators, were swayed,
so that without fear they might find the Quakers that were
met together guilty of transgressing the law.

Now, since at that time they were resolved to banish the Quakers, so called,
George Whitehead published a little book,
in which he showed the unreasonableness of the persecutors,
and also strengthened his friends with solid arguments against the charge of stiffneckedness,
answering some specious objections; amongst the rest,
that the Quakers might keep small meetings, and so not fall under the lash of the law;
for if they did not meet above five in number, they kept without the reach of the law;
and by keeping private meetings they might also acquit their consciences before God.
But to this G. Whitehead answered,
that it might have been objected to the prophet Daniel,
that he might have prayed secretly, and not with open windows and thrice a day,
after king Darius had signed the decree,
that whosoever should ask a petition of any god or man for thirty days, save of the king,
he should be cast into the den of lions; but that Daniel, notwithstanding this decree,
had continued to pray to God as before.
"`Since then,`" said G. Whitehead, "`our meetings are kept in obedience to the Lord God,
and according to the freedom he hath given us,
we may not leave off our testimony for God in that case; but we must be faithful to him,
whatever we suffer on that account.
For neither the threatenings of men, nor their severity or cruelty acted against us,
how far soever it may be extended,
can make us to forsake the Lord in not keeping our assemblies,
or to be ashamed of Christ before men,
lest hereafter he be ashamed of us before his Father which is in heaven.`"
Besides,
he showed how unreasonable it was to incite the jury on an ill-grounded suspicion,
without leaving them the liberty of their own judgment:
and the judges he showed their duty from the law, and Magna Charta.
He also showed how unequal it was, that soldiers,
who abused his friends in their meetings, should be called as witnesses against them;
and that they should be locked up with thieves and felons,
since this was contrary to the right of a free-born Englishman.
But this representation of G. Whitehead was slighted,
since they were resolved to go on with banishing of the Quakers,
and to transport them to the West Indies; which however, according to the ancient laws,
might not be done to a free-born Englishman against his mind.
Josiah Coale about this time gave forth also a paper,
being a warning to the king and both houses of parliament,
to dissuade them from persecution.
But this did not avail, for persecution went on.

In the month called August, eight of those called Quakers, viz. Francis Prior,
Nicholas Lucas, Henry Feast, Henry Marshal, Jeremiah Hern, Thomas Wood, John Blendale,
and Samuel Trahern, were tried at Hertford before judge Orlando Bridgman,
already mentioned.
The indictment contained,
that they had been at an unlawful meeting under colour and pretence of religion;
and the witnesses declared, that they had met together above the number of five,
and were taken at such times, and such places;
for they must have transgressed thrice before they could be condemned to banishment:
but the witnesses declared also, that they neither heard them speak any words,
nor saw them do any thing at their meeting, but sit still.
The indictment having been delivered to the grand jury,
they could not agree in their verdict;
for there were some amongst them whose consciences would
not give them leave to be accessary to this work of persecution;
and therefore they brought in their verdict ignoramus.
Now, though such a verdict as this ought not to be rejected,
yet judge Bridgman standing up, and seeming to be angry,
spoke to the jury after this manner: "`My masters, what do you mean to do?
Will you make a nose-of-wax of the law, and suffer the law to be baffled?
Those that think to deceive the law, the law will deceive them.
Why do not ye find the bill?`"
To which one of the jury said, that it concerned them to be wary,
and well satisfied in what they did, for they were upon men`'s lives for ought they knew.
"`No,`" said the judge, "`I desire not their lives,
but their reformation:`" and then he gave the jury some directions,
and he so coloured the matter, that they going out again soon returned,
and found the bill.

Then four of the prisoners were called to the bar, their indictment read, and they asked,
guilty, or not guilty; to which they answered,
"`Not guilty,`" and that they had transgressed no just law.
"`But,`" said the judge, "`ye have transgressed this law,
(having the act in his hand,) and ye have been twice convicted already upon record,
and if ye are found guilty by the jury this time,
I must pass the sentence of transportation upon you.
Now, therefore ye shall see that we do not desire to strain the law to the highest severity;
neither do I believe that it was the aim of the law-makers to be severe,
but for conforming.
If ye will promise that ye will not go, or be at any more such meetings,
I will show you this favour, as to acquit you for what is past:
this favour ye may receive before the jury is charged with you;
but afterwards I cannot do it.
And know also, if the jury for want of punctual evidence, should not find you guilty,
yet if ye are taken again, ye will be in the same case ye now are in.
What say you?
Will ye promise to meet no more?`"
To this the prisoners answered, they could promise no such thing.
Then a jury was called, and the indictment read a second time, containing,
that the prisoners had been at an unlawful meeting at such a time and place, the first,
second, and third time.
The witnesses being called, gave the same evidence as before;
and then the judge said thus to the jury: "`My masters, the jury,
ye hear what evidence the witnesses give; how they took them at such times,
at such places, which are places they use to meet in;
and that they were above the number of five,
besides the persons of the family where they met;
and that they are twice convicted already upon record: and this is the third offence,
which incurs the sentence of transportation, if ye find them guilty.`"
Then he spoke these words which have been mentioned already,
viz. "`Ye are not to expect a plain punctual evidence against
them for any thing they said or did at their meeting,
etc. for dumb men may speak to one another,
so as they may understand each other by signs: and they themselves say,
that the worship of God is inward, in the spirit, and that they can discern spirits,
and know one another in spirit.
So that if ye find or believe in your hearts that they were in the meeting,
under colour of religion in their way, though they sat still only,
it was an unlawful meeting;
and their use and practice not according to the liturgy of the church of England;
for it allows and commands when people meet together in the church,
that divine service shall be read, etc.
And ye must find the bill; for ye must have respect to the meaning and intent of the law,
which the king and parliament have in wisdom and policy made,
not only against conventicles, but the words assembly and meeting were added;
for we have had late experience of the danger of such meetings under colour of religion:
and it is an easy matter at such meetings to conspire and consult mischief.
Therefore the wisdom and policy of the king and parliament,
lest they should be undermined, have made this law,
which is not a law against conscience, for it doth not touch conscience at all,
as I confess some other laws do, which enjoin coming to church, and some other things.`"
This and more judge Bridgman spoke to the jury,
to persuade them to bring the prisoners in guilty.
And the jury being gone out, within the space of an hour returned,
and their foreman said, that Nicholas Lucas, and the other three, were guilty.

What the judge had said,
that they had had late experience of the danger of such meetings under colour of religion,
was of no force at all;
for it never had appeared that the Quakers in religious meetings
did any thing else than the performing of their worship,
though there were other evidences concerning the Fifth monarchy-men;
but it was universally known that the Quakers had no part therein,
nor joined with them in the least degree.
It was also a very absurd saying of the judge, that this law did not touch conscience:
for it was merely for conscience-sake that the Quakers frequented
not the public service and liturgy of the church of England,
and kept religious meetings by themselves.
But the jury seemed well satisfied with what the judge had told them;
and he having thus obtained his aim, read the prisoners`' names, and said to them,
"`What can ye say for yourselves, that judgment of transportation should not pass,
or be given against you?`"
To which they said, "`We are innocent, and have transgressed no just law;
if we must have that sentence, we give up our bodies freely into the hands of the Lord;
the will of the Lord be done.`"
"`Have ye nothing more to say?`"
said the judge.
"`Nothing, but that we are innocent,`" replied the prisoners, "`we have wronged no man.`"
"`Then hearken to your sentence,`" said the judge.
"`Ye shall be transported beyond the seas, to the island of Barbados,
there to remain seven years.`"

Then Jeremiah Hern and Thomas Wood were called to the bar, and their indictment read,
to which they pleaded, "`Not guilty, but innocent;`" and Jeremiah said,
he was no such person as the act mentioned, for plotting and contriving insurrections.
Then the judge interrupting him, said, "`You are a forward man,
you have an estate;`" and so he caused him to be set by: and to Thomas Wood he said,
"`I hear a good report of you; consider what you do; I am sorry,
seeing you have a good report among your neighbours, that you should be found guilty,
which I fear you will if you put yourself upon trial: I am willing to show you favour;
and it may be one man may fare the better for another.`"
This reflected on Jeremiah, who, by the malice of one John King,
had been falsely represented to the judge.
Yet Jeremiah having shown how he had been wronged, the judge said,
they should both partake of his favour, if they would but desire it,
and this favour consisted in this, as he himself said,
that he would wave the proceedings of the court, and give them till the next assizes,
to consider better with themselves.
"`What say you, (thus he continued,) will ye have it deferred till the next assizes?
for if the jury find the bill, you will be sent to Jamaica;
ye must not all go to one place.`"
To this the prisoners returned, "`We have transgressed no law of God,
nor wronged any man: we leave it to the court; we desire it not.`"
"`If you will not desire it,`" replied the judge, "`I cannot, nor will do it.`"

Then three other prisoners were brought to the bar, among whom was one John Reynolds,
who, according to the deposition of the witnesses,
had been within a yard of the door of the meeting-place, with his face from it.
The judge then said,
"`God forbid that I should do any thing that is not right and just against my conscience;
there is that which is written upon the wall before me, which puts me in mind,
that I should not judge for man, but for God.`"
Then turning to the jury, he spoke to them almost after the same manner,
as he did concerning the other four prisoners: and to induce them to declare Reynolds,
(who was taken but not in the meeting,) guilty, he spoke thus:
"`Suppose a man be killed in a house, and nobody saw him killed,
but a man is met coming out of the house with a bloody knife in his hand,
it is a very probable evidence that he is guilty of the murder.
So though the witnesses do not say that they saw and took him in the meeting,
yet they swore he was within a yard of the door with
his face from the place where they usually met;
and he hath been taken twice already, and convicted upon record.
My masters, I leave it to you, go forth.`"
Then a bailiff was called, and charged to provide the jury a room,
and to let none speak with them, nor to let them have either bread, drink, or candle,
till they brought in their verdict.
The jury being gone out, soon agreed, and after they were returned said,
that four of the five prisoners were guilty,
and that the other who stood without the door was not guilty.
So he was acquitted; but the other four being brought to the bar, the judge asked them,
what they could say why judgment of transportation should not be given against them.
Their answer was, "`We are innocent, and have not offended any just law of God or man,
to deserve that sentence; we leave it to the witness of God in thy or your consciences.`"
Then the judge said, "`Ye have offended against this law,
(having the act before him,) which is made by the king and parliament,
and executed by us their subordinate ministers: if it be not righteous and just,
we must answer for that.`"
One of the prisoners had said before, "`If I have transgressed any just law,
let me suffer; and if not, he that judgeth for God will not condemn me.`"
To which the judge returned, "`You do well to put me in mind of my duty;
pray think of your own.`"
And now he asked the prisoners, "`Have you any more to say?`"
To which they answered, "`Nothing, but that we are innocent.`"
Then he said, "`Hear your sentence: you shall be transported beyond the seas,
to the island of Jamaica, being one of his majesty`'s foreign plantations,
there to remain seven years.
Now I have this one thing to acquaint you with, that if you, and either of you,
will pay down here into the court, an hundred pounds before the court riseth,
you and every one of you shall be discharged, and clearly acquitted for what is past.
And I will show you this favour, not to discharge the court at this present,
but shall adjourn it till afternoon.`"
This was done; and the court being met again,
the judge sent to the condemned prisoners to know
if they would pay down the hundred pounds;
but they answering, "`No,`" the court was then soon discharged.

Seven of these prisoners not long after were carried
on ship-board to be transported to the West Indies;
but (which was remarkable,) the ship by contrary
winds and stormy weather was hindered going to sea.
Not only the master, whose name was Thomas May, but also his men,
grew very uneasy at this: for they believed that Heaven was against them: nay,
the sailors threatened to leave the ship,
if the master would not set those prisoners ashore.
And he himself, considering how after having lain long in the Downs,
and more than once set sail, they were hindered to go on by contrary winds,
resolved at length, after having lingered about two months, to set the banished ashore;
and so he did, giving them a certificate, of which I have a copy in my custody,
that they were not run away, but freely put ashore by him, for which, among others,
he gave these reasons, that seeing the great adversities they had met with,
he concluded from thence, that the hand of God was against him,
and that therefore he durst not go off with these prisoners,
because he found them to be honest men, who had not deserved banishment.
And also that there was a law extant,
that no Englishman might be transported against his mind.
And that his men refused to proceed on the voyage if he would carry away these people.
This certificate he gave under his hand, and so let them go away free;
and not long after the ship set sail with a fair wind.
I do not find that the banished, who returned home again,
were prosecuted on this account:
for the sentence against them was executed as far as it could at that time,
and they had made no opposition, but had been sufferers.

Persecution in the meanwhile did not cease:
but this did not discourage those called Quakers; they continued valiant,
as I have seen in many letters sent about that time to some of my acquaintance.
One said in the court of justice, "`We are in the service of the Lord,
and may not leave it;`" another who was offered to be freed of banishment,
if he would pay down an hundred pounds, said, "`Though I had an hundred lives to lose,
and could redeem them all for an hundred pence, yet I would not do it.`"
But this could not stop the violence of the persecutors;
till an heavier hand reached them, as may be related hereafter.

In the months of October and December many were condemned to transportation,
and among these several women, whose trials I shall but cursorily speak of:
for if I should relate all particulars, the description would far exceed my limits;
and therefore I will but touch upon some few things.

On the 13th of October, sixteen of those called Quakers were tried at Hicks`'s Hall,
in Middlesex, for the third offence,
as they called it.--The grand jury consulting together about finding the bill of indictment,
could not well agree.
And the justices giving them a check, one of the jurymen desired to know,
by what law they ought to find a bill against any persons,
without witnesses to testify the fact committed.
To which answer was made by the court, that their records testified the crime or fact,
and that such their record was a sufficient witness without the testimony of any man.
And for a proof of this it was further said,
"`The records in Chancery serve as a sufficient testimony; and if it be so in Chancery,
why not here?`"
The jury having been twice upon this business, was sent up a third time;
and Edward Shelton, the clerk, said he would go up also to help them, and so he did;
it having been threatened, that if the jurymen did not find a bill, they should be fined.
Nevertheless, at their return they answered, "`No verdict.`"
Whereupon the justices finding the jurymen not to answer their ends, took them apart,
and examined them one by one,
telling them that the only thing they were to look upon was,
that they did assemble together above the number of five in company; which,
according to what they said, their records showed.
This made some of the jury comply; but others stood it out,
and signified that in conscience they could not consent to what was required of them.
But the major part complying with the justices, upon their threatening them,
and the others being strongly pressed, the bill was, by a kind of force,
accepted at length.
But how hard a case this was to some,
appeared by the mournful confession of one of the jury,
who to ease his conscience published in print a small book,
with the title of The Wounded Heart, or The Juryman`'s Offences,
etc. in which he openly disapproved the fact, to which he had been induced by human fear.
The pains had been so great to persuade the jury to bring
in a verdict according to the mind of the court,
that the clerk, as was reported, said, he had rather have given twenty pounds,
than have been so troubled.

The next day the prisoners were brought to the bar, and William Proctor, of Gray`'s Inn,
sat as judge in the court.
The questions and answers I pass by for brevity sake.
One Hannah Trigg pleading she was innocent, was asked how old she was;
to which she saying she was not sixteen years old;
one of the justices did not stick to say, she told a lie;
and that he thought the Quakers would not lie.
In the meanwhile it appeared, that he only said so by guess to baffle her;
for by a certificate of some that were present at her birth,
(which was divulged in print,) it was proved that she,
being the daughter of Timothy Trigg,
was born at London on the 20th of the month called August, 1649;
and so was but fifteen years of age, and dealt with against the law;
which was the harder, because this maid falling sick, died in prison,
after the sentence of banishment had been past upon her:
which sentence was now pronounced against twelve persons, among whom were four maids;
and four married women were condemned to a confinement of eleven months in Bridewell.
The judge in the pronouncing the sentences was so disturbed in his mind,
that ordering some to be transported to Virginia, and others to Barbados,
he condemned some also to be sent to Hispaniola;
at which the people were not a little surprised, for he made it plainly appear,
that he did not consider what he said;
since Hispaniola was no place in the dominions of the king of England:
but he was so confounded,
that he also accused the prisoners of having transgressed the laws of the commonwealth,
forgetting that England was no more a commonwealth,
as it was before the restoration of king Charles II.

On the 15th of October above forty of the prisoners called Quakers,
were tried before the judges Hide and Keeling.
To mention all the exhorbitances of this trial, which were not few, I count needless;
for as to the questions and answers, and the passing of sentence,
the reader may form to himself an idea of it from
what hath been said already of the trial at Hertford, etc.
A maid being asked, guilty, or not guilty, answered,
"`I never was taken at any seditious meeting or conventicle in my life.`"
To which the judge said, "`But, woman,
were not you taken at the Bull and Mouth the 21st of August?`"
She answered, "`I am innocent in the sight of God and all good people.`"
That this was true the judge did not deny, but said, "`I believe that, woman,
but you have transgressed a law.`"
She replied, "`As for the Bull and Mouth.
I believe I have been there an hundred times, and if the Lord permit me life and liberty,
I do not know but I may go there an hundred times more.`"
The judge then saying, "`Woman, will you plead or no, guilty or not guilty,
or else I must pass sentence upon you.`"
She answered, "`The will of the Lord be done, I am innocent.`"
Yet this could not avail her,
though judge Hide had said a little before concerning the prisoners,
"`If they are innocent, then they are not guilty.`"
But she was set by as mute, or pro confesso,
as to the fact charged against her in the indictment.
Others who complained of the unreasonableness of the proceedings,
were hectored as impudent:
and the jury showing themselves dissatisfied concerning the witnesses,
judge Hide said to them, it was no untruth if a man did mistake in the time,
and that his evidence was good, though he did not see one in the house: "`For,`" said he,
"`if forty men be in a room, and one is brought out of the room to me,
standing at the door, cannot I swear that he was in that room, if I see him come out?
You must not make such scruples.`"

In the meanwhile there were some among the witnesses
who did not know the prisoners by face;
so that there was reason enough to disprove their testimony.
But whatever was objected, the business must go on:
for though one of the witnesses declared that the meeting,
from which the prisoners had been taken was peaceable;
and though one of the prisoners said, that the law was made against seditious meetings,
and that nothing of sedition had been proved against them: yet judge Keeling said,
the act was made to prevent such meetings, because under colour and pretence of religion,
plots and conspiracies might be carried on.
And when a prisoner said, that he was at a peaceable godly meeting,
and received much comfort there; the judge returned, "`That is as much as we desire.
You confess you were there; and though it was a peaceable meeting,
yet it was an unlawful one.`"
Another of the prisoners who pleaded that the law
the court acted by was contrary to Magna Charta,
and the ancient fundamental laws of the land, was answered by judge Hide,
"`If the king and parliament should make a law that two justices without
a jury should adjudge a man to death for the third offence as a felon,
without benefit of clergy, it would be a good law, and according to Magna Charta,
and the law of the land; and we should be bound to execute it.`"
It seems this judge,
(who not long after was suddenly summoned hence to
appear before the divine assizes,) was of opinion,
that since the legislative power resided in the king and parliament,
all that they resolved and enacted, must pass for good law.
But if I should mention all the absurdities I meet with in these proceedings,
when should I come to an end?
True it is, that sometimes a show was made of pity: for judge Keeling said to two maids,
"`We are sorry that such young maids should be thus deluded.`"
But because they would not promise to go to the public church,
though they declared themselves ready to assist at divine service,
they were deemed as guilty.
Another prisoner being asked by judge Hide, whether he would go to church, answered,
"`If I have my liberty, I shall go to church.`"
But when it appeared that he did not mean the established or public church,
this promise could not save him.
One Richard Poulton, a lad of fifteen years of age, who by a certificate showed,
that he was not yet sixteen years old, and therefore no transgressor of the law,
was asked, if he would swear he was not sixteen,
just as if he could have remembered the time of his birth; to which he answered,
that he was not brought up to swearing: and being asked,
whether he would promise to go to church, he answered, he should promise no such thing.
Then he was returned to the rest that were to be sentenced.

This was on the 17th of the aforesaid month; when nineteen persons,
among which were some women, were condemned to banishment,
and four married women to twelve months imprisonment in Bridewell.
None of the judges it seems had a mind to pronounce sentence,
and therefore they left this business to the city recorder.
He then bidding the prisoners to hearken to the judgment of the court, spoke so softly,
that he could not well be heard, which made one of the prisoners say,
that he ought to speak louder, for they could not hear him.
But he continuing to speak softly as before,
two or three others of the prisoners told him, they could not tell what he said.
To which he answered, he cared not whether they did or no; and then said,
"`Hearken to your sentence, You and every of you, shall be transported beyond the seas,
the men to Barbados, and the women to Jamaica, being two of his majesty`'s plantations,
there to remain seven years.`"
Thus the persecutors endeavoured to be rid of the Quakers:
but though persecution now was very hot, yet they fainted not,
neither were they in want of such vigilant assistants,
as both by example and words continually encouraged them to faithfulness: who yet,
(which was remarkable,) were not condemned to banishment, as many others.

Among these was Josiah Coale also, who about this time, as I have been told,
was in prison at London; and both by writing, and by word of mouth,
did exhort his fellow-believers to constancy: for,
(when under confinement,) he betook himself to his pen, and recommended to his friends,
that they would not forsake their meetings, though they were to undergo great sufferings,
since it was God`'s good pleasure to let their patience be tried.
"`And,`" said he, "`that these afflictions come upon us is by God`'s permission:
who then shall gainsay him,
or endeavour to reason with him about matters of so great a concern,
since his way is hid from man.`"
He also signified to them that this was done to try their faith,
and that therefore they ought to continue bold, and persevere valiantly.
"`And though,`" said he, "`great sufferings and afflictions attend us, yet my heart,
praised be the Lord, is not troubled, neither hath fear seized me,
because I see the intent of the Lord in it.`"
And in one letter he spoke thus: "`Friends, this know:
that for the sake of the residue of the seed which is yet ungathered,
is my life freely sacrificed up into the hand of the Lord;
and ready and willing am I to lay it down for the testimony of God`'s blessed truth,
which he hath given me to hear, if thereunto I am called:
for bonds and afflictions attend me daily, and I may say,
we are in jeopardy of our lives daily: so let your prayer to God be for me,
that I may be kept unto the end, to finish my testimony with joy,
and in all things to bring glory and honour to the name of the Lord, who is over all,
blessed forever.`"
This his Christian desire he obtained, as will be said in due place.
It was a time of suffering; and those to whose share it fell, continued valiant:
whilst others did not neglect to exhort the king and parliament to leave off persecution.
Among these was William Bayly,
who gave forth a very serious exhortation and warning
against the persecution to the king and parliament,
etc. beginning thus:

For the King and Parliament, etc.

Friends,

The God of heaven hath put it into my heart to write a few words unto you,
in the fear and dread of his name, and in the counsel of his own will,
concerning the work which ye have taken in hand against him and his people;
this is not the end and work for which the Lord God hath
permitted you into the places of government and rule,
in this nation, (nor the way for you to prosper,
nor to prolong your days in the earth,) thus to persecute
and afflict an innocent and harmless people,
who are peaceable, and walk uprightly towards God and man; therein endeavouring,
in all things, to keep their consciences void of offence,
and who have no helper in the earth but the Lord alone;
neither is their kingdom of this world,
but they are verily the children and servants of the most high God,
whom he hath gathered from amongst men, and from the kindness of the earth,
to be the first fruits unto him, and to the Lamb in this age; and we are his,
and not our own, he hath brought us, and redeemed us unto himself,
and to him alone have we committed our innocent cause,
and he hath undertaken to plead it for us, with all our adversaries;
and no weapon formed against us shall ever prosper, but be broken to pieces.

Therefore friends, be awakened and open your eyes,
and see what a stir and ado here is in this nation;
to haul and drag up and down a company of tender, innocent, and harmless people,
men and women, and children, from their peaceable meetings,
who meet together in the fear and tender love of God,
without any evil or bad intent toward any;
but have good-will and compassion toward all men, even to the worst of our enemies,
as the Lord bears us witness;
and these are they that are driven as sheep to the slaughter,
and thrown into your noisome jails, and prisons, and houses of correction;
by rude and brutish people, your servants, whom you have set on work by your authority,
till many of them have (patiently) suffered till death,
whose innocent blood will assuredly be required at your hands,
(though they shall not go free of the guilt, who have had the least hand in it,
without speedy repentance.) And thus ye may see and read,
how the disciples of Christ Jesus,
are as sheep and Lambs in the midst of wolves in this age, and as a lily among thorns,
and all this is only for obeying his commands,
and for worshipping the everlasting invisible God, in the spirit, and in the truth,
according to the Scriptures, the which, if you knew and understood,
you would tremble to think what you have done against them,
to cause so many of the little ones, which believe in Christ, so grievously to suffer,
who said, it were better a millstone were hanged about his neck,
and be drowned in the depth of the sea, that should offend one of these little ones,
that believe in me; and as true as Christ Jesus suffered, and rose again,
and as God liveth, who raised him from the dead,
we are some of those his little ones that believe in him, who,
(in derision and scorn in this age,) are called Quakers, as ye might call Moses,
the prophets and apostles,
(in days past,) who did quake and tremble at the presence of the Lord,
who is the same now as ever he was, though the ungodly know him not, nor his power:
and we are of that poor and afflicted people,
mentioned Zeph. 3:12,19. "`Whose trust is in the name of the Lord,
who will undo all that afflict them.`"

But what shall I say unto you; if ye will not, or cannot believe our faithful testimony,
(or the testimony of God through us,) and the innocency of our cause and sufferings,
neither will ye believe, if one should rise from the dead and declare it unto you;
for many tender visitations, and timely warnings, and gentle reprehensions have you had,
from the pure spirit of the Lord God, both from his witness in your own consciences,
and from his faithful servants, and messengers,
who have written and declared unto you in his name and power in this your day.
And as for my part, who am one of the least of the thousands of Israel,
I could willingly have been silent as toward you at this time, but the Lord,
whom I serve in my spirit, hath laid it upon me to warn you once more,
for whose sakes I have borne a burden, in the true sight and sense of your sad estate,
and of the day of thick darkness, wrath, and distress,
which is hastening upon you from the Almighty.

Wherefore be not proud nor rebellious, but hear, and obey the word of the Lord;
for thus saith the Lord God that made heaven and earth, let my innocent people alone,
and touch them not any more, as ye have done; for they are mine, and I have called them,
and chosen them, and redeemed them; they are my jewels, which I am making up,
they shall show forth my glory before men to the whole world; I have anointed them,
and I will preserve them and deliver them, and crown them with an everlasting salvation.
I will rebuke kings and rulers for their sakes, and distress nations,
and dethrone the mighty from their seats that rise up against them, as I have done;
and let my everlasting gospel have a free passage in these nations;
and do not reproach and afflict my servants and messengers so any more,
whom I have chosen and sent to preach and declare the way
of life and salvation to the ends of the earth,
but bow your ear and your heart unto them and their testimony,
that it may be well with you, and prolong your days;
for he that blesseth them shall be blessed, and he that curseth them shall be cursed,
and every hand shall wither that opposeth them, as hath been, and shall be,
henceforth forever: I the Lord have spoken it.

But and if you will not hear, but will still persist, and go on, as ye have done,
to oppress my heritage, and harmless people,
and make war and opposition against my power and truth,
and thus set yourselves and your power against me, the living God,
I will bring you down suddenly, to the astonishment of nations,
and I will cut your day short, and turn your pleasures into howling and lamentation,
and shame and contempt shall cover your memorial as a garment.
Thus will I work for the deliverance of my seed, and none shall let it;
for the year of my redeemed is come, and the day of vengeance is in my heart,
to plead its cause with all flesh.

Therefore, consider your ways, and see what ye are doing,
and what the effect of this your work will be; ye are but men, and the children of men,
who were but as yesterday; your breath also is in your nostrils,
and your life is but a vapour, which will soon vanish away: you labour in the very fire,
and bring forth wind, which blows up the flame of that which will consume you,
and deprive you of all happiness forever: O that ye had but hearts to consider it!
For the more you strive with the Lord, and oppress his people,
the more will they multiply, and grow stronger and stronger:
and you shall wax weaker and weaker, and your works shall be your heavy burden;
for life and immortality is risen,
and the power of God is stirring in the hearts of thousands, and light and understanding,
the excellent spirit which was in Daniel, is breaking forth like the lightning,
which shines out of the east into the west, in the sight of many people,
whereby they know, it is the day of the coming of the Son of Man,
with power and great glory, that every eye may see him,
and they that have pierced him shall mourn bitterly: so, your labour is in vain,
and your works for the fire, and your striving with your Maker to no purpose,
as to effect your end and aim.
And of these things you have been often forewarned,
and the Lord hath been very long suffering towards you, in sparing you thus long,
and suffering you thus far to act against him and his dear people;
and his mercy and forbearance hath been evidently showed in a large measure unto you,
in deferring his heavy judgments thus long,
which must have been confessed to be just upon you.
And will you thus requite the Lord,
by increasing your tasks of oppression upon his tender innocent people?
O unwise and ungrateful generation!
Hath not God yet showed you, that you should do justly, and love mercy, and walk humbly?
But are these your fruits and practices, fruits of mercy or justice?
Or if there be any tincture or spark of love, or humility in them, let God`'s witness,
the light in all your consciences, and in people, answer.
I tell you plainly, that such fruits and doings among you,
that profess yourselves Christians, have made the very name of Christ and Christianity,
a proverb of reproach through nations,
and have caused the God of heaven to be blasphemed; and how could it be otherwise,
seeing you who profess the most knowledge of God,
and have talked of converting the heathen, as some of your leaders have done,
are found the least in the life and fruits thereof.
But to what would they convert them?
to pride and swearing, and drunkenness, and oppression, and all manner of excess,
and to persecute people for their good conscience?
They have no need of that; for, some of them have said,
they did not use to swear and be drunk, etc. till they came among the Christians,
and learned of them; they did not do so in their own country:
ye are so far from converting them,
being out of the life of what ye profess and talk of yourselves,
that the very heathen or infidels, (as ye call them,) do judge and condemn you,
who are making inquiry, concerning these your proceedings against this harmless people,
among whom some of them have been kindly entreated,
who visited them at the Lord`'s requiring, though contrary in opinion and religion;
and this doth rise up in judgment against you.

But, friends, have you yourselves been under sufferings,
and some of you been driven into strange countries, or lands, for your cause,
as it was called?
Nay, did not the king himself once flee for refuge to a tree,
to save himself from his enemies`' hands?
If not, why are there such representations made of it, in so many places in the nation?
And was not this as great a mercy and deliverance from God,
so to obscure and preserve him, from them who pursued him, and many of you also?
And are these things forgotten?
Can mercy be loved, except it be remembered?
And do you remember and love his mercies, by doing justly, and walking humbly with him,
as he doth require?
Or do you boast in vain glory, as if your own arm had done it,
or your own strength or deserts had delivered you?
If so, then God must needs be forgotten, and his mercies trodden under foot,
and his visitations and counsels cast behind your back; and so, all that forget God,
shall be torn in pieces, and there shall be none to deliver them, as it is written.

And were these your sufferings, which you sustained by them ye opposed,
unjust and unequal?
And if you should say, they were: then I say,
it is much more unjust and very unequal in the sight of God,
and all sober people that fear him, for you,
thus to inflict such cruel sufferings as imprisoning,
and stifling up to death in your noisome jails and holes among thieves and murderers,
and to pronounce sentence of banishment upon an innocent, harmless, peaceable people,
that do not oppose you in the least, with any outward force,
neither do so much as the thoughts of it lodge within our breasts,
as the Lord God knoweth, who hath called us to peace,
but on the contrary have sought and do seek your welfare and happiness,
both in this world, and in the world to come,
which in time shall be manifest to the whole earth.

And if you say, your sufferings were unjust and unequal, though you did oppose them,
and make war against them so long as you could,
because they deprived you of your rights and privileges, and just liberties,
and natural birthrights, etc. which were your due to enjoy,
as being free-born of the nation: then how much more is it unjust, and unequal,
and unrighteous, thus to inflict sufferings upon your friends,
and oppress your peaceable neighbours, who are free-born people of the same nation,
and do not oppose you, but are tender towards you, as aforesaid,
and subject to all wholesome just laws, and tributary to you,
for which causes we ought to have our just liberty,
and enjoy the privilege of our birthright,
which is our due so long as we live peaceably and harmlessly,
but if it be not a privilege to be pleaded for,
then are all your own grounds and reasons, and cause, without a foundation,
and you and the whole nation may be swept away by any that are able to do it,
without being charged with injustice or oppression,
which is contrary to the just balance, the light of Christ in all people`'s consciences.
And as we are the dearly beloved people of the most high God,
who doth bless us with his presence,
and manifest his everlasting love and good-will towards us daily,
and overshadows us with his power and tender mercies,
whom he hath gathered out of the evil ways and spirit of this world,
and all the vanities thereof, unto himself, to walk with him who is invisible,
in the upright, blameless, undefiled life,
in the midst of a crooked and perverse generation; I say, considering these things,
how greatly and unrighteously do our sufferings appear to all sober people,
whose eyes are open,
and will be more open to discern and savour the bitterness of that proud, envious,
wrathful spirit, which thus hath acted and deceived you:
and its end is numbered by them that have wisdom from above.

For friends, set aside the reproachful name of Quakers,
and the other titles of derision and scorn,
which the envious and blood-thirsty spirit hath invented
to render the people of God odious in all ages,
and tell me what ye have justly to charge against this people,
whom you so furiously pursue to the dens and caves of the earth,
to the loss of the lives of so many of them; by which children are made fatherless,
and tender-hearted women, mournful widows, and let it come forth to open view,
and declare it abroad, as your articles against them, to the whole world,
and speak the truth, and nothing but the truth, as you use to tell one another,
that all people may rightly know and understand the very ground and most secret cause,
who do inquire, of these your present proceedings against them;
for notice is taken by many, and ere long it must be manifest to all men,
as the folly and madness of Jannes and Jambres were, that withstood Moses;
for you withstand no less than him of whom Moses wrote; who said,
"`I am the light of the world,`" against whom Saul was once exceedingly mad,
and had thoughts to do very much against that way, which was then as well as now,
called Heresy, till the light of Jesus, whom he persecuted, met with him,
with his letters, or warrants, to haul men and women to prison, as your servants do,
and smote him to the ground, and made him tremble, who, from that time,
became such a Quaker, as you now persecute and imprison till death;
but the light of Jesus Christ, the Son of the living God, will meet with all persecutors,
and oppressors about religion, let them be never so mad,
or think they ought to do much against that way, they call Heresy,
as some of you have said, who have made a mock at the light, even publicly,
which many took notice of, and even marvelled at such blasphemy in an open court,
against the Saviour of the world:
and there is no other name under heaven by which men shall be saved, but him who said,
John 7:12-7, and 16. "`I am the light of the world,
who lighteth every man that cometh into the world.`"

And this is he, in whom we have believed, and of whom we have declared,
and must declare and hear testimony, as long as we have a being;
and the world shall know that our testimony is true; and for his name and truth only,
do we thus patiently suffer the contradictions of sinners,
as our brethren did by the zealous Jews in ages past;
but you are not so zealous for Christ`'s law and commandments,
as they were of Moses and the prophets, which Christ ends and fulfils,
who thought it was not lawful to do good on the Sabbath-day, as to heal the sick,
for then would you "`Do to all men,
as ye would they should do to you;`" for his law runs thus,
"`And be ye merciful,`" etc. and "`Love you your enemies;
and swear not at all,`" etc. as ye may read.

But behold, how both Jews and Gentiles take notice, and are ashamed and grieved,
to hear and see what a deal of bad works you do, even on your Sabbath-day,
as some of you call it, and how you profane the day of your worship, with your cattle,
and servants, which are within your gates, what riding and running, and toiling,
in rage and fury, like madmen, sweating, and swearing, and cursing, and dragging,
and hauling the innocent members of Christ`'s body out of their peaceable meetings,
into your jails and holes; on your day of worship.
But are your sacrifices, ye offer at that time, accepted?
Have ye peace whilst these things are acting in your name, and by your authority?
If you have peace and pleasure therein, let me tell you from the righteous God,
you are hardened in your sins against him, and he will break your peace speedily,
and turn your pleasure into bitterness and lamentation:
and his innocent people`'s meetings shall stand, and be increased;
and their way shall prosper, and the truth shall spread and prevail,
and have dominion over all nations; and their enemies shall fall and be confounded,
let them strive what they can against them; for they are of God, and not of man,
or the will of man, and they seek his glory and not their own;
and such as abide faithful to him, shall triumph over all the principalities,
and powers of the rulers of the darkness of this world,
and make a show openly of the victory over all that do or may oppose them;
for their life is immortal, and the Lord of heaven and earth is their strength,
who is with them as a mighty terrible one;
therefore shall their persecutors fall before them.

And let me tell you again, that by these your unreasonable, and unjust dealings,
the understandings of thousands are the more opened; and the tender, sober part,
or principle in them, doth feel the weight and burden of this grievousness,
which you have prescribed, and do so eagerly pursue,
to the imprisoning to death so many innocent persons and free-born people of this nation,
besides hundreds are liable to the same, which yet remain in your prisons.
And your unnatural, cruel sentence of banishment,
to separate dear and tender husbands from their dear and tender wives,
and tender children, and little innocent babes:
Oh! how do you rend the bowels of the meek of the earth, whom God hath blessed?
What is become of all your promises of liberty for tender consciences?
God`'s curse and vengeance will come upon you,
and his plagues will pursue you to destruction if ye proceed in this work;
and your wives shall be widows, and your children fatherless; the Lord hath spoken it.
If you had the hearts of men, or of flesh, ye would be afraid,
and blush at the very thoughts hereof; my heart and soul melts within me,
and I am even bowed down, with cries to God, in my spirit,
to think of the hardness of your hearts.

God Almighty, cut short thy work in righteousness,
and shorten the days of oppression and cruelty for thine elect`'s sake;
which cry night and day unto thee,
and make known thy name and power to the ends of the earth; and let the heathen hear,
and fear, and bow to thy righteous sceptre,
and let the kings of the earth lay down their crowns at the feet of the Lamb,
that through thy righteous judgments they may partake of thy tender mercies,
which endure forever; that their eyes may be no longer withholden,
nor blinded by the god of this world, the power and prince of darkness,
but that they may come to see thee, who art invisible,
and enjoy the same precious life of pure unfeigned love,
which abounds in the hearts of thy hidden ones; and receive thy peaceable wisdom,
to be governed, and to govern therein; then would they surely know, that we are thine,
and confess to thy glorious truth, and speak good of thy name, and magnify thy power,
and no longer count the blood of thy everlasting covenant,
(wherewith we are sanctified,) as an unholy thing.

But, O thou righteous, holy, pure, eternal God,
art unknown unto all them that sit in darkness,
and dwell in the spirit of enmity against thee and thy people;
though thou art come near to judgment, according to the promise, Mal. 3:5.
And thy way of life and salvation is hid from them,
therefore they hate us without a cause,
and thus evilly entreat us in the darkness of their minds,
and in the ignorance and hardness of their hearts; for which my soul doth pity them,
and even entreat thee for them, that if possible their eyes may be yet opened,
and their hearts yet softened, and their spirit humbled,
that they may see what they are doing in the dark, and consider the effect of their work,
which will assuredly follow:
and if thy warnings and gentle visitations will not humble them,
then let thy judgments awaken them, and bring them down, and humble them,
that they may perceive something of what thou art doing, in these latter days,
and art resolved to do to the ends of the earth,
though the whole world should gather and band together to oppose thy work and people;
for thou hast begun, and thou wilt go through and perfect thy work;
thou wilt raise thy seed, and gather thine elect from the four winds,
and bring them from the ends of the earth,
and scatter the proud in the vain imaginations of their hearts;
and thou wilt break thy way through all that oppose
thee in this the day of thy mighty power,
in which thou art arisen, as a giant to run his race, to finish transgression,
and make an end of sin, and bring in and establish everlasting righteousness;
that the kingdom of this world may become thy kingdom, and of thy Christ,
as thou hast promised, and art now fulfilling; glory and honour, and thanks,
and everlasting praises be to thy glorious name, world without end.
Amen.

So friends,
ye are and have been warned again and again by the
faithful messengers and servants of the Lord,
in love to your souls; and you are left without excuse,
if never words more should be mentioned unto you; by which ye might perceive,
how the Lord doth strive with you, that ye might repent,
and be saved from the wrath to come,
though some of you feel little of it in your own consciences;
but his spirit will not always strive with you: for if you will not believe them,
but slight and reject them,
and neither make conscience of what hath proceeded out of your own mouth,
nor regard to perform your own words and public engagements, in that which is just,
which the Lord requireth of you, nor remember his by-past and present mercies,
and long suffering towards you, but trample all under foot; I say,
if it be thus with you, and you are resolved to go on, you will wholly be given up,
and be exceedingly hardened, and grow desperate in cruelty and oppression against God,
and his truth and people, till your whole earth is filled with violence; and then,
(as true as God liveth,) will the flood come upon you,
and ye shall fall after the manner of Egypt; and the weight of the dreadful judgments,
due for all your abominations and cruelties,
shall sink you down into the pit that is bottomless, and that suddenly,
as the Lord hath spoken.

By his servant, who is a lover of the welfare of all your souls,
and I am thus far clear of all your blood,

William Bayly.

Written in the Tenth month, 1664, at Hartford.
