== Addenda

The Author towards the conclusion of this history,
having given some account of the principles of the people called Quakers, thought fit,
in the Dutch Appendix, among other things, to add the following treatise in Latin,
concerning the Light, written about the year 1662.
And since in this English translation the subject matters contained
in the said Appendix are inserted in the body of the history,
in those places to which they properly belong, and no reference being made to this,
but as mentioned in the preface, it is thought fit to subjoin it here,
with the following words of the Author prefixed to the same.

In the preface to this history, mention is made of a certain book,
intitled The Light upon the Candlestick, published in the name, as many supposed,
of William Ames, yet no ways written by him, though it contains his doctrine,
but by a certain learned man, unwilling to be known publicly, and as it seems to me,
written originally in Latin; which, though printed, being but in few hands,
I have thought fit to reprint.

And the original in Latin, soon after the first publication,
being translated into English by B. F. was printed in the year 1663,
from which translation take it as follows, viz.

=== The Light Upon the Candlestick

Things are not for words, but words for things; if therefore we understand things aright,
and as they ought, by words,
it must be by such as are fit to imprint the things
themselves in those to whom they should occur,
and then it were enough,
(to make known our thoughts to others as we conceive
them,) only to make use of such words.

But forasmuch as we find the matter in this case far otherwise,
and that two men speaking or writing the same words, may nevertheless have different,
yea, contrary thoughts, the disability of performing this fitly by words or discourse,
is clearly inferred.
Nor may we at all wonder at it,
seeing we know to what a perpetual change languages are subject, even such,
that the very words may be changed from their pristine signification.
And the imperfection is so great, that whosoever should have invented them,
such as now they are in use,
we should certainly believe that he had little or no knowledge
of those things that are thereby intended to be signified.
So that if we would better express things unto another, by words and speeches,
we had need find new words, and consequently a whole new language:
but that would be a toil and labour indeed.

In the meanwhile we see what a sea of confusion flows from hence upon all mankind:
for although there should be none, who sometimes through ignorance,
and sometimes by subtlety or wickedness,
might wrest or pervert words contrary to the mind of the speaker or writer,
in such manner as themselves, that so do, should think best for their own ends,
from whence consequently all this deceit, slandering, contention, and the like proceeds;
yet, so it is, that how uprightly or prudently soever a man goes to work in this matter,
he nevertheless finds himself liable to mislead, or to be misled.

But although the case be thus with words and discourses at present in use;
yet for all that, they are the most ready, and so far as I know,
the fittest means to make known all our thoughts unto others by;
and for this reason therefore,
though so much confusion and deceit happen to arise from hence,
that no man that hath any experience can be ignorant thereof;
yet may we not therefore be too much afraid of them neither,
as many yet do manifest themselves to be, who, because they have some experience hereof,
are apt to believe we are about to deceive them,
especially if they be forewarned thereof.

This, as in many things,
so it hath chiefly taken place in that which is commonly esteemed for religion;
in which it is so with most men, that they will scarce give audience to,
much less take into consideration, any thing held forth unto them,
by any whom they judge not to be of their own opinion; to avoid as they imagine,
being thereby deluded.

Yet if they were to act thus towards their own party,
we might think it was an act of prudence, and that they would see with their own eyes;
but no, in nowise, this is too hard a task;
whatsoever cometh on that side is received with such
partiality for good and current coin,
as if there were no danger nor possibility of erring: whereas nevertheless,
it is all alike with the one as with the other opinion.
It all depends but upon a possibility of being nearest to the truth;
and for the upholding every one his own opinion, and defending it against others,
there is so much ado, so much pains taken, so much scholastic learning, study,
and disputing, that one would rather believe that there were no true religion at all,
than that this should needs be it.

Seeing then it is thus at present, can we much blame the common people,
that they despair of ever being able to solve this difficulty,
and are glad when they can but find any that are greedy of the work,
upon whom they may cast the whole burden?
surely no: for he that sees but a little clearly,
sees that there is always contention behind, and no end till a man grows weary of it:
nor is the conquest his that hath truth, but his that can best handle his tongue.
A miserable thing if it were thus to be sought and found:
but it is not so with the true religion.

Go to, then, O man, whoever thou art, we will not draw thee off from one society of men,
to carry thee over to another; it is somewhat else we invite thee to.
Lend us but a little audience; surely thou knowest thus much,
that as it is an absurdity to receive all things
without distinction that present themselves to us,
so it is no less so to reject all things without judgment.
We invite thee to something which may be a means
whereby to attain to thy own salvation and well-being.
Be as distrustful, or rather prudent, or foresighted as thou wilt,
thou canst not in reason refuse us thy ear in this thing.
All the damage thou canst possibly have by doing that which we exhort thee to,
is only to have taken a little pains in vain,
if that which is promised should not succeed; whereas, on the contrary,
if it should succeed, thou mayest come to the enjoyment of a matter of so great worth,
that should not be exchanged for all that is esteemed great in the earth.
Moreover it is not far to seek, but at hand; it is nigh thee, yea, and in thyself.
And there thou mayest experience the trial of that which we declare,
which is the most certain and sure that can be desired.

We direct thee then to look within thyself; that is, that thou oughtest to turn into,
to mind, and have a regard unto, that which is within thee, viz. the light of truth,
the true light, which enlighteneth every man that cometh into the world.
Here it is that thou must be, and not without thee.
Here thou shalt find a principle certain and infallible,
and whereby increasing and going on therein,
thou mayest at length arrive unto a happy condition:
of this thou mayest safely adventure the trial.
But if thou darest not do so much, it is hard to help thee.
And if thou happenest to be one of those that would know all things,
before thou dost begin, yea,
even those things which are experienced in a condition to which thou art so much a stranger,
that there is nothing in thee hath so much agreement therewith,
as to comprehend it according to truth; know this, thou dost therein,
just as those that would learn to read, without knowing the letters.

To desire to know all things that we are capable of, is good and laudable:
but to go further is folly.
There will be always something else to ask, and our knowledge will ever be too short.
He that will not adventure till he be fully satisfied, will never begin,
much less finish to his own salvation.

But we judge it needful, as much as in us lies,
to open unto you that unto which we do exhort you,
that people may understand what it properly is.

We say then, that we exhort every one to turn unto the light that is in him.
We give it rather the appellation of light, than any thing else,
otherwise it is all one to us whether ye call it, Christ, the Spirit, the Word,
etc. seeing these all denote but one and the same thing:
yet the word Light being in its natural signification
somewhat else than that which we intend thereby,
we shall therefore in brief endeavour clearly to express what we intend under this denomination.

The Light, then we say,
is a clear and distinct knowledge of truth in the understanding of every man,
by which he is so convinced of the being and quality of things,
that he cannot possibly doubt thereof.

From this definition which is here given of the light, it is clear,
that it must needs comprehend in it the principal effect of showing us,
and giving us the knowledge of what is truth and falsehood, what is good and evil:
which verily is a matter of so great concernment,
that without it men must needs wander up and down in continual darkness,
uncertainty of opinion, and in sin, neither knowing truth at all, nor doing any good,
but, as it were, by hap-hazard, and without certainty.

This light then, Christ the truth,
etc. is that which makes manifest and reproves sin in man,
showeth him how he is strayed from God, accuseth him of the evil which he doth,
and hath committed; yea, this is it which judgeth and condemneth him.
Again,

This is the preaching to every creature under heaven,
though they have never read or heard of the scripture.
This is it which leads man in truth, into the way to God,
which excuseth him in well-doing, giving him peace in his conscience, yea,
brings him to union with God, wherein all happiness and salvation do consist.

Moreover,
seeing it is properly the nature of this light infallibly to discover sin and evil,
to reprove and convince thereof; it can never possibly consent thereunto.
And although it be true indeed,
that the operations of the light are not in all men alike powerful,
in whom nevertheless it is; yea, though in some men it seems to have no operation at all;
yet this is occasioned only by those impediments that do hinder it;
for as the natural light by the interposition of other bodies or covers,
may be hindered from having its operation there, where else it would,
were those things which impede removed, the light,
(itself,) still abiding in itself unchanged;
even so it is also with this light whereof we speak.
The hindrances in this are manifold.
All that we meet with in this world, seems to proclaim war in this case.
What is there that hath not a powerful operation upon one or other of the senses of man,
through which, passing over into the soul, the memory is so filled,
that nothing else can enter?
The eyes and ears stand so perpetually open to all things,
that they never want an object to bring to mind the
experience of that which pleased the body so well;
and this stirs up the desire to enjoy it, yet all without satiety:
the acts are multifarious, the enjoyment can be but single and transient,
and the incitements incessant.

Now, where this operateth in us after this manner,
by education and example in manners and customs which are regulated by opinion,
and not by the true light, that men live altogether therein; is it any wonder that here,
(in these men,) there is so little, or no operation of the light?
Not at all.

We are so involved in the idea of that which is high in the world,
so overwhelmed in pleasures,
that it is almost impossible for the light to cause
one desire after good to spring or bubble up.

Where then those so contrary operations to the light are,
there it can never break through.

According to the nature and kind of everything, is the operation thereof:
where they are opposite, the one must give way unto the other,
and that which is most powerful prevails;
from whence also the effects thereof become most visible.
The light, notwithstanding, abides always the same; and therefore although man by sin,
through his love and union to corruptible things, comes to perish, be damned,
and miss of his everlasting happiness, the light nevertheless,
which is in every man that comes into the world, abides forever unchangeable.

The light is also the first principle of religion.
For, seeing there can be no true religion without the knowledge of God,
and no knowledge of God without this light,
religion must necessarily have this light for its principle.

God being then known by this light,
according to the measure of knowledge which the finite and circumscribed
creature can have of the infinite and uncircumscriptible Creator,
man hath obtained a firm foundation, upon which he may build all firm and lasting things:
a principle whereby he may, without ever erring, guide the whole course of his life,
how he is to carry himself towards God, his neighbour, and himself, and all things else,
whereby he may happily attain unto his soul`'s salvation,
which consisteth only in union with God.
And thus this light is therefore the first principle of religion.

Without this light, there is no power or ability at all in man to do any good.

This must first raise him and quicken him out of the death of sin.
It is folly to expect any thing, where nothing is; there is no effect without a cause;
there must be something then which must cause a man to act, if he does any thing.

And this cause must have in it whatsoever the effect produced hath in it: as for example,
if the effects of light be produced, light must do it, and nothing else.

And therefore, is it not a silly thing,
that all men would have people to do this or that as good,
and leave this or that as evil, because they tell them so, without any more ado,
or at best assigning only the accustomary motives thereto,
and think they have reason too, just as if this were enough?
Who can see such effects as are hereby required, included in this cause?
Not I, for my part.

Experience also teacheth us the same;
else how could it all pass away in a train and custom, without any fruit:
these are therefore not the right means;
but such we must endeavour to furnish people with;
means from whence power may issue forth to do that which they are exhorted to.
Such is the nature of man, that he is moved to choose that which he judgeth to be best,
before the worst, and is always willing to change for the best.

Now if it so happens, as for the most part it doth,
that a man chooseth the worst before the best, it is for want of knowledge,
and contrary to his aim, and so he erreth, not being led by the true light.

Here then it should be begun;
it is easy leading a man to that which of himself he is desirous of:
if these now who make it their work to teach others,
were but led themselves by the true light,
knowing better things than those to which the multitude are linked so fast with love,
they would be able to hold them forth clearly to others:
and so making it their continual work,
it were impossible their labour should be fruitless; for people knowing better,
would do better.
Who remembers not the play of our youth, how much we were in love therewith,
and yet how ridiculous is it now unto us but to think upon it?
And why?
Because we now know that, which we judge better: hence, not by force,
but very easily and of itself, it comes in time to be worn out and pass away,
that there is now no desire nor motion moving thereunto.
How may we think then it would be,
if the soul came but once to apprehend those things aright which are durable and incorruptible,
and which infinitely transcend all bodily toys in worth?
So far as those things then should come to be esteemed
more glorious than all bodily things,
so much the more powerful would be the annihilation of those things in which all men,
even to old age, yea, death itself, do take so much delight;
and then we might hope and expect that those things, which are, indeed,
alone worthy to be known, would gain entrance, and being brought forth in the light,
would be also owned and received by every one,
according to the measure in which they should stand in the same light.

Hence from within, the amendment and conversion is to be waited for:
from within it must begin, if with a foundation; the outward then will follow of itself:
the weakest must give way to the strongest,
all depends but upon the knowledge of something better,
to make a true and lasting change.
Therefore to hold this forth to men, is the best thing we can give them.
This light is the inward ear, by which alone, and by no other, the voice of God,
viz. the truth, can be heard.

By this alone must the sense and mind of him that would signify any thing by words,
or any outwards sign, be comprehended and understood.
So that if the truth of God be presented to a man who stands not in the light of truth,
it is impossible he should understand it,
although he hears and comprehends the words after a manner,
yet he is still fenced off from the true sense and meaning thereof.

Hence therefore it is, that, among so many hearers,
there are so few that have ears to hear.

He that hears truth aright, that is, understands it well, must not stand out of,
but in the truth itself.

Therefore neither is it any wonder that all men do not understand
and conceive those things that are brought forth by the light.
Those only that stand in it are alone capable thereof.

The case being thus,
we see of how great concernment it is continually to exhort
and excite men to turn unto the light that is in them,
that so they may go on to such a condition and measure therein,
as to be fit to understand aright the word: that is, the truth of God,
because out of this there can be nothing understood,
and concluded from the words and writings given forth from the light, but mere opinions,
and probably errors.
This light, Christ, etc. is the truth and word of God, as hath been already said,
and everywhere appears by what we have hitherto laid down: for this is a living word,
and translateth man from death to life, is powerful,
and enableth a man to bear witness of it everywhere.

This is also the true rule according unto which all our actions are to be squared.

This hath the preeminence before any writing, scripture, doctrine,
or any thing else that we meet with from without.
We are born into the world, and brought up, as every body knows;
from the very first we hear differences, every one pretends that he knows the matter,
and hath truth: one holds forth this, another that, to us.
If now the light which is in every man that comes into the world, shall not be judge,
whither shall we go?
To believe all, is impossible; to reject all, no less: who shall be judge here?
Who else can be, but the light within us?
For whatsoever comes from without, is the thing to be judged of: who then fitter;
seeing this is infallible?

Again, is not this, (the light,) that by which we must see and know God,
and so consequently that by which we must judge all things divine?
Certainly it is: then it follows also, that we can judge of no doctrine,
of no book that is divine, but by this light; and judging it thereby to be divine,
it cannot but be truly so.
As for example, if we experience that the book called the Bible,
in regard of the divine doctrine therein comprised,
hath such an harmony with that in which God is known,
that he must needs have been the author of it;
there cannot rationally any more powerful demonstration
be demanded.--With them that are thus,
the Scripture may become living and powerful, and not a dead letter,
as it must needs be to those men who have no feeling of this thing.
And from hence then it is apparent,
seeing this light must be preferred to all things
whatsoever that we meet with from without,
that then Man must first of all be directed to this: for without it what profit is there,
I pray, to be reaped any where by any external sign but by it?
Lay the book of the Scripture freely before any man;
let him also have all the fitness the universities can give him,
to look into it in its proper language in which it may have been first written,
what will all be without the light?
Nothing.
The letters, the words, are not the Scriptures, but the meaning alone is the Scripture,
and this meaning can never be truly and justly hit,
but by those alone that stand in the same light, out of which the Scriptures proceeded.

These are they then to whom the Scripture is a co-witness,
and as a seal of their being sons of God; while by experience they find themselves,
every one according to his measure,
in the same condition in which the saints formerly were,
who spake and wrote all those things comprehended in the book of the Scripture;
these then have the true understanding and meaning of the Scriptures,
not those that imagine unto themselves a meaning by opinion and guess,
through a thousand imaginations, without the least assurance of not erring;
which becomes the very ground of all jangling and contention.

In fine, this light in every man is the means to come to the knowledge of God.
And seeing all external signs must needs presuppose this knowledge,
therefore itself must need be immediate, without any external sign:
that signs must presuppose such a knowledge, is undeniable;
for these signs must either be words or effects, works or miracles.

If words, we see at first an impossibility in the thing itself:
for words are created and finite, and God who should make known himself by them,
uncreated and infinite: and therefore here is so infinite a difference,
that there is no manner of agreement,
nor any thing in the words by which they might be capable to do it.
But again, if you fly to the meaning of the words, as being fit for such a thing,
then that which we say will more manifestly appear; as put a case, for example-sake,
that God, about to make known himself by words, should say,
"`I am God,`" and that this should be the sign by which he would make himself known,
we see clearly, that it would be impossible for a man at first to know God by this:
for if he should comprehend any thing out of the sense of the words,
he must needs formerly have had the signification of the word, God,
and what he is to understand by it: in like manner, if God maketh his will known to man,
the knowledge of God, which hath its original from the true light,
must precede and convince him, that that manifestation can be from none but God alone,
whereupon he is then sufficiently assured.

If by effects, or outward miraculous works, it is the same thing;
for these are no less created, no less finite:
and though we might observe something in the nature of a thing,
which might be too difficult for the power of any creature, which we know, to effect;
yet this at the utmost would be but a demonstration taken from our impotency,
and not from the nature and all the operations of it;
and this kind of demonstration could not be certain and stable,
till we were able clearly and distinctly to see that there was
not a concurrency of many causes to produce such an effect,
but that it must needs have been caused by an infinite and unlimited cause,
whom we call God?
But who knoweth this?
Or who can declare it?

Add to this, That the knowledge of God in all things must first be,
before the knowledge of any creature or particular thing;
so that no particular thing without this can be well known;
and consequently is altogether incapable to come to know God by,
or certainly to make known himself to man by.

Go to, then; without thyself, O man, thou hast no means to look for,
by which thou mayest know God.
Thou must abide within thyself, to the light that is in thee thou must turn thee,
there thou wilt find it, and no where else.

God is, considered in himself, nearest unto thee, and every man.
He that goeth forth of himself to any creature, thereby to know God, departs from God,
and so much the further, as he comes more to admire the creature,
and stand in contemplation thereof, to mistake himself by it.
This thou must then shun, and the contrary mind, viz. Mind the light that is in thee,
by it to work, unmoveably and faithfully to persevere.
